### ISSUE TITLE
File versions and descriptions are stripped in ASP.NET Runtime Bundle installer.

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10003]
In the **ASP.NET Core Runtime Installer** EXE installer, the file versions and descriptions of DLLs appear to be missing.

**Repro steps:**

1. Download the ASP.NET Core Runtime EXE Installer (for example https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-preview5-windows-x64-asp.net-core-runtime-installer)
2. Unpack it using `dark`
3. Check the property page for any DLL in the Microsoft.AspNetCore.App folder (for example `aspnetcorev2_inprocess.dll`)

**Expected Results:**

Non-empty "File description", "File version" and "Product version" values

**Actual Results:**

Empty values:

![image](https://user-images.githubusercontent.com/7574/57242769-3ba14a80-6fe9-11e9-847f-48341b9bf35b.png)

As far as I can tell, all the other EXEs (.NET SDK, Hosting Bundle, etc.) are built from the same ".wixlib" project ([src/Installers/Windows/SharedFrameworkLib](https://github.com/aspnet/AspNetCore/blob/master/src/Installers/Windows/SharedFrameworkLib)). The Hosting Bundle (built from [src/Installers/Windows/WindowsHostingBundle](https://github.com/aspnet/AspNetCore/tree/master/src/Installers/Windows/WindowsHostingBundle)) **is _not_ affected**, while the SharedFrameworkBundle (build from [src/Installers/Windows/SharedFrameworkBundle](https://github.com/aspnet/AspNetCore/tree/master/src/Installers/Windows/SharedFrameworkBundle)) **is affected**. I'm not sure what's different about them though. Thoughts @joeloff ?

To clarify, **only the circled installers here are affected**:

![image](https://user-images.githubusercontent.com/7574/57242394-3abbe900-6fe8-11e9-98be-f39ce20e9a6a.png)

**Comment by joeloff** [comment]
Nope, they have properties. I just extracted the full MSI. Did you view it indirectly through something like a compressed folder. If you do that you won't see properties always.

![image](https://user-images.githubusercontent.com/7409981/57244078-75278500-6fec-11e9-8c0b-685be8a94ab2.png)

**Comment by anurse** [comment]
Hrm... Ok, weird. I used `dark` to unpack them and looked at the files. It looks like you're right, I'm on the wrong track for expanding these :). False alarm!
