### ISSUE TITLE
Client Side Deep Links with WebpackDevMiddleware 404s

### ISSUE THREAD

**Issue by NotMyself** [aspnet/AspNetCore#10002]
I have an asp.net core app that is using spa services to serve up a vue.js client-side application. When running in Development mode with the WebpackDevMiddleware enabled, all client-side deep links return a 404.

How can I configure the fall back routes for the WepackDevMiddleware?

### To Reproduce
1. Clone the repository: `https://github.com/NotMyself/bivrost.git`
1. Switch branches: `git checkout adding-client-side-routing-and-storage`
1. Open in Visual Studio Code
1. Comment out lines [35-36 in Startup.cs](https://github.com/NotMyself/bivrost/blob/adding-client-side-routing-and-storage/src/server/Startup.cs#L35-L36) to prevent TwitchBot from trying to connect.
1. Run the `.NET Core Launch (web)` debugger
1. Note that the route: `http://localhost/` serves up the vue app with HMR enabled
1. Enter the URL directly into the address bar: `http://localhost/overlays/chat`
1. Note the app throws a 404.

### Expected behavior
I expect the spa application to be served up on client side routes.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg can you please look into this? Thanks!

**Comment by NotMyself** [comment]
Feel free to reach out to me if you need anything @ryanbrandenburg. I have kind of moved on with development, but the branch is the same.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @NotMyself.
After looking into this a bit more it seems this is purely a question which you'll get a faster answer from [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by NotMyself** [comment]
Giving it a try. Will see what happens. If anyone googles and finds my question here, my StackOverflow question can be found [here](https://stackoverflow.com/questions/56094371/client-side-deep-links-with-webpackdevmiddlware-404s).

**Comment by NotMyself** [comment]
Repository with minimum reproduction of the problem is located [here](https://github.com/NotMyself/webpack-dev-middleware-bug).
