### ISSUE TITLE
Create new IIS sub-status code handler load failure

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#10008]
Epic https://github.com/aspnet/AspNetCore/issues/8833

Today we use a 500.0 to indicate a handler load failure. Let's create a new sub-status code for better SEO for folks running into this issue.

**Comment by shirhatti** [comment]
We should have different sub-status codes for
- Incorrect bitness
- Handler not found

**Comment by anurse** [comment]
Also a separate status code for "Only one inprocess application is allowed per IIS application pool. Please assign the application '/LM/W3SVC/2/ROOT/movies' to a different IIS application pool."

**Comment by jkotalik** [comment]
I'm going to merge my current PR once tests pass and do a follow up PR to make the pages prettier and maybe handle a few other cases.

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [x] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: https://github.com/aspnet/AspNetCore.Docs/pull/12605
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: 3.0.100-preview6-012162
            * ASP.NET Core Runtime: 3.0.0-preview6.19301.2
            * .NET Core Runtime: 3.0.0-preview6-27730-01
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
