### ISSUE TITLE
Disable CaptureStartupErrors when running in ANCM out-of-process

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#10006]
We should stop Capturing startup errors when running in ANCM out-of-process.

**Comment by shirhatti** [comment]
@anurse We should back-port this to 2.1 as well

**Comment by anurse** [comment]
@jkotalik and @Tratcher talked about this and decided it was a bad idea (PR: https://github.com/aspnet/AspNetCore/pull/10655)
