### ISSUE TITLE
MissingMethodException: EndpointRoutingApplicationBuilderExtensions.UseRouting

### ISSUE THREAD

**Issue by dpedrelli** [aspnet/AspNetCore#10000]
I have an .NET Core 3, MVC app that runs fine inside of VS 2019.  When I deploy it to a server running IIS, I get the following error page:

`An error occurred while starting the application.
MissingMethodException: Method not found: 'Microsoft.AspNetCore.Builder.IApplicationBuilder Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseRouting(Microsoft.AspNetCore.Builder.IApplicationBuilder, System.Action`1<Microsoft.AspNetCore.Routing.IEndpointRouteBuilder>)'.

ResolveROI.ScheduledServices.CrystalQuartz.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)

    MissingMethodException: Method not found: 'Microsoft.AspNetCore.Builder.IApplicationBuilder Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseRouting(Microsoft.AspNetCore.Builder.IApplicationBuilder, System.Action`1<Microsoft.AspNetCore.Routing.IEndpointRouteBuilder>)'.
        ResolveROI.ScheduledServices.CrystalQuartz.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)

.NET Core 3.0.0-preview4-27615-11 X64 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 3.0.0-preview4-19216-03    |    Microsoft Windows 6.3.9600    |   Need help? `

I installed ASP.NET Core/.NET Core 3.0.0-preview4-19216-03 on the server.  I installed NuGet Microsoft.AspNetCore.App 3.0.0-preview3-19153-02.

Here is my program.cs
`        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>()
                                .UseIIS()
                                .CaptureStartupErrors(true) // the default
                                .UseSetting("detailedErrors", "true")
                                .UseContentRoot(Directory.GetCurrentDirectory());
                });
    }
`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dpedrelli.
The issue you're facing indicates that the app you're trying to run is compiled against a different runtime than the one available on the machine.
Try to install the same runtime on the target machine.
