### ISSUE TITLE
[ANCM] [out of process] Write stdout to EventLog when exit code is non-zero

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#10005]
Epic https://github.com/aspnet/AspNetCore/issues/8833

To better diagnose pre-main errors, we should buffer whatever's written to stdout and write to EventLog in event of a non-zero exit code.

**Comment by anurse** [comment]
To be clear, we mean both `stdout` and `stderr`.

**Comment by anurse** [comment]
Let's log the first 30KB and see where that takes us for now.

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here:
        * [x] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: 3.0.100-preview6-012113
            * ASP.NET Core Runtime: 3.0.0-preview6-19279-01
            * .NET Core Runtime: 3.0.0-preview6-27728-04
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
