### ISSUE TITLE
[ANCM] [in proc] Write pre-main errors to the browser when running in development

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#10011]
Epic #8833 

For pre-main errors, in addition to writing to the event log, surface these errors in the browser when running in a development environment.

**Comment by anurse** [comment]
"Pre-main" meaning errors that occur **prior** to even loading the application.

**Comment by anurse** [comment]
As part of this, we should follow up with the CTI test scripts that deploy to Azure App Service and have them set `ASPNETCORE_ENVIRONMENT` to `Development` when deploying, or if we have a variable to directly control showing detailed errors, use that instead. We've gotten a few errors from those tests that just report as ANCM `500.30` errors with no context. It seems reasonable for them to enable detailed errors in their tests (unless they are directly testing the undetailed errors)

**Comment by anurse** [comment]
@jkotalik can you confirm a minimal set of steps necessary to enable detailed errors? I'd like to get our CTI scripts updated to have them enable these detailed errors (even in Antares deployments) since it will improve our bug reports from that team.

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [x] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: https://github.com/aspnet/AspNetCore.Docs/pull/12605
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: 3.0.100-preview6-012162
            * ASP.NET Core Runtime: 3.0.0-preview6.19301.2
            * .NET Core Runtime: 3.0.0-preview6-27730-01
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
