### ISSUE TITLE
Consider moving to Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by divega** [aspnet/AspNetCore#10013]
ASP.NET Core includes a caching provider and tool that uses System.Data.SqlClient, and perhaps there are other ways ASP.NET Core depends on SqlClient that I am not aware of. 

Now that [Microsoft.Data.SqlClient is available in NuGet](https://www.nuget.org/packages/Microsoft.Data.SqlClient/), and EF Core will be upgraded to it in 3.0, we could consider upgrading to it as well. 

Although the two providers can coexist in the same application, it would ideal to avoid the duplication. 

On the hand, Microsoft.Data.SqlClient should probably be considered even more of an out-of-band dependency than System.Data.SqlClient, in the sense that it doesn't build from source in CoreFx. Maybe additional caution is required because of this, and perhaps we should avoid including it the shared framework. 

cc @DamianEdwards, @Eilon, @natemcmaster

**Comment by natemcmaster** [comment]
First I've heard of this new package. When do we recommend Microsoft.Data.SqlClient vs System.Data.SqlClient to our customers? What's the primary difference?

**Comment by divega** [comment]
Is the new version of SqlClient. All future development will happen on it and System.Data.SqlClient is going to be in maintenance. 

It uses a new namespace and is out of band from both .NET Framework and .NET Core rather than type forwarding in .NET Framework.

In this preview, the main functional differences are support for Always Encrypted on .NET Core, SQL Server UTF-8 support, and Data Classification. 

More details are in the readme and release notes at https://github.com/dotnet/sqlclient/, and in the .NET Core 3.0 preview 5 announcement blog post.

**Comment by divega** [comment]
> When do we recommend Microsoft.Data.SqlClient vs System.Data.SqlClient to our customers?

The idea is that we recommend it from now on, although existing applications that don’t need new functionality or optimizations can stay on System.Data.SqlClient.

**Comment by Eilon** [comment]
I added a card to our PM/engr sync https://github.com/orgs/aspnet/projects/22?fullscreen=true so we can discuss this week.

**Comment by blowdart** [comment]
@HaoK can you size this please?

**Comment by blowdart** [comment]
Taking this out of identity because we'll get it for free with EF

**Comment by natemcmaster** [comment]
The only non-test code in this repo which directly depends on System.Data.SqlClient is the **dotnet-sql-cache** command line tool. I think we need to re-evaluate this dependency. Everything that ships in the .NET Core SDK is supposed to be open-source and source-buildable for Linux distros. The plans for open sourcing Microsoft.Data.SqlClient are unclear at the moment, and I'm not sure if this dependency will make it into source-build by the 3.0 timeframe.

There is an assembly in aspnet/Extensions still using System.Data.SqlClient: Microsoft.Extensions.Caching.SqlServer. Unlike dotnet-sql-cache, this package doesn't have the same OSS or source-build requirements, so it might be easier to have this adopt the new version. @divega it's probably worth opening an issue on that repo too so we can discuss implications of updating that package separately.

**Comment by divega** [comment]
FWIW, the SqlClient team has committed to make Microsoft.Data.SqlClient source code available in https://github.com/dotnet/sqlclient in coming weeks, but it will depend on stable releases and not be integrated into our dependency update mechanisms, so source-build maybe off the table, so the outcome is the same. 

I created https://github.com/aspnet/Extensions/issues/1723 for Microsoft.Extensions.Caching.SqlServer.

**Comment by natemcmaster** [comment]
We made dotnet-sql-cache OOB in https://github.com/aspnet/AspNetCore/pull/10272, which resolves the concern about its dependency on SQL Client and its impact on source-build and the SDK. We could switch its dependency to Microsoft.Data.SqlClient, but as this is a console tool, not a class library, it doesn't really matter what it is using under the hood unless there is some feature of Microsoft.Data.SqlClient that the tool desperately needs. This tool has very few downloads, so I'm okay if we backlog this until someone requests a change.

Given that I think the only remaining work here is to update test code to react to https://github.com/aspnet/EntityFrameworkCore/pull/15761. @ajcvickers as this is largely going to be test code for Identity, I'm putting this back into area-identity.

**Comment by ajcvickers** [comment]
Closing this as Identity no longer depends on SQL Server, even for testing.
