### ISSUE TITLE
How to return a JavaScript Promise object to Blazor

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#10034]
Good people, help is needed here:

I'm returning a JavaScript Promise object from a JavaScript function, and this works well:

--- shorten for brevity ----
`
if (this.status >= 200 && this.status < 300) {
        resolve(xhr.response);
 } 
`
--- ---

But when I call the function from Blazor, the variable data is not populated with the expected value. 
`
var data = await JSRuntime.InvokeAsync<string>("methods.submit");

Is this the way to call a JavaScript function that returns a Promise ?
Do I have to do something additional to get the data variable populated ?

Thanks...
`

**Comment by RemiBou** [comment]
Can you post the full methods.submit function ? xhr.response might be of many type (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response), you should use responseText  if you want to get the text.

**Comment by enetstudio** [comment]
Most certainly:

window.methods={
    submit: function () {
            return new Promise((resolve, reject) => {
                var form = document.getElementById("newTestForm");
                var data = new FormData(form);
                var xhr = new XMLHttpRequest();


                var method = form.getAttribute('method');
                var action = form.getAttribute('action');
                xhr.open(method, action);
                xhr.onload = function () {
                    if (xhr.status == 200) {
                        resolve(xhr.response); //data gets here in correct format !!!!!!!
                    }
                    else if (xhr.status != 200) {
                        reject("Failed to submit form with status" + xhr.status);
                    }
                }
                xhr.send(data);
            });
        }
} 

thanks...

**Comment by RemiBou** [comment]
You should use responseText, the type of response is dynamic.

BTW you can do all that (getting value from form, sending ajax query, reading result) without using JSInterop as all. Look at this example https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/testassets/StandaloneApp/Pages/FetchData.razor

**Comment by enetstudio** [comment]
Thanks a lot, @RemiBou !!!
