### ISSUE TITLE
System.Text.Json serializer doesn't work with Guid and Guid?

### ISSUE THREAD

**Issue by nguyenquyhy** [aspnet/AspNetCore#10033]
### Describe the bug
System.Text.Json serializer doesn't work with `Guid` and `Guid?`. The behavior is as following:

- For `Guid`: the serialized data is always `{}` regardless of the `Guid` value.
- For `Guid?`: get exception `ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.`

### To Reproduce
1. Using ASP.NET Core 3.0 Preview 5
2. Create a default API template and remove AddNewtonsoftJson()
3. Change `IEnumerable<int>` in ValueController to `IEnumerable<Guid>` or `IEnumerable<Guid?>` and the returned data accordingly.
4. Test the API

### Expected behavior
`Guid` and `Guid?` should serialized into strings or null.

**Comment by pranavkm** [comment]
@Eilon could you transfer this to https://github.com/dotnet/corefx?

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#37496
