### ISSUE TITLE
.NET Interop or how to Webforms or MVC 

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetCore#10031]
there exists a lot of LOB Intranet solutions based on Webforms or ASP.NET MVC (15 years of Code)

it would make sense for Customers to make future code Investments into dotnet core (net 5)

As already pointed out there are several issues
-diffrent processes
-missing reportintg plugins
-dublicate authentication
-Layout Frame (Masterpages)
-missing Language support for vb.net
and so on

there must be some integration part, to get startet with core and not to rewrite everthing.

**Comment by danroth27** [comment]
Hi @hannespreishuber, 

It is true that .NET Core does take a fresh take on web development with .NET, which has enabled us to deliver improved performance and greater platform agility. It is not a goal of ASP.NET Core to have binary or source compatibility with existing ASP.NET apps. We do support the MVC model in ASP.NET Core, but the underlying framework is substantially different. Migrating existing apps does require a fair amount of work. If you wish to continue to use the ASP.NET MVC or WebForms models then you should continue to run on .NET Framework, which will be supported for many years to come. You can also consider adding new functionality using .NET Core side-by-side with the existing app and then migrating pieces as it makes sense.

**Comment by hannespreishuber** [comment]
@danroth27 
we are teaching thousands developers in Microsoft Technology stack (B2B). Perhaps I am wrong, but choosing MIcrosoft was not a Question of open source Code or moving faster than others or even better Quality or to get it for free. For me it was a Question of trust. 
Can I run my Code for years or decades? Is there a Company which gives me the guarantee, fix the Bugs, takes care of security issues. 
And I tell you as I have done VB 6, the Migration path ( as worth the result have been) have opened the doors.
Microsoft works hard to throw this USP over board. Canceling Silverlight, Windows Phone without any sorry destroys my investment. OK- shit happens, but my personal advice: don't do that again.
I have seen my customers leaving Microsoft to take the OS path, and I see the want back stability, like Microsoft have promised over decades. So they come back on dotnetcore, or want to 

Webforms
No I dont think a Migration tool is a good idea. I have done a by Hand Migration Webforms VB.NET to Razor C# and it took longer than to write the Webforms based solution.

The hurdle is: there is no -NO- suggested path. Rewrite your Code, is no path.
1) support VB.NET
2) allow same Directory and share Security Cookies within IIS hosted 
(look at the aspx https://www.eurowings.com/skysales/Search.aspx?culture=de-DE)
3)add some external config possibility to aspnet- It make absoultly sense to allow admins config Jobs 
(can give you a list, like, SMTP, Cookie Path, Credentials…)
4)look at Major use cases like reporting &SQL
5)allow shared master pages for core

I know your Budget is limited, but your customers Budget spent in Webforms (and also MVC) is it also and they spent at least 1000x more in this Projects.

-Hannes

PS sorry for german spell checking :-)
