### ISSUE TITLE
input type file with both ref and bind crashes in ms Edge

### ISSUE THREAD

**Issue by Tewr** [aspnet/AspNetCore#10035]
### Describe the bug
`input` element with `type=file` crashes in edge when the value is changed if both `ref `and `bind` attributes are set

### To Reproduce
1. Using this version of ASP.NET Core '3.0.100-preview5-011568'
2. Create this code in a `.razor` file in a Blazor (Client-side) project

```
<input type="file" ref="fileInputRef" bind="@fileInputBind" />

@functions {
    ElementRef fileInputRef;
    string fileInputBind;
}
```

3. With these arguments: Run the project in Microsoft Edge and choose any file using the file input
4. See error in console

The reset button and reset method is just a use case, not really needed to reproduce the issue as the exception happens already when a file is chosen.

A more elaborate use case: working with the file input and wanting to reset the value.

```
<input type="file" ref="fileInputRef" bind="@fileInputBind" />
<button onclick="@Reset">Reset</button>

@functions {
    ElementRef fileInputRef;
    string fileInputBind;
    public async Task Reset()
    {
        fileInputBind = "";
    }
}
```

### Expected behavior
See chrome for expected behavior, basically no crash and value can be reset

### Additional context
Possible workaround: 
Skip using `bind` for this purpose, and invoke interop for setting `element.value = ""`;. If `ref` is used there's most likely some interop going on anyway.

Console output in edge:
```
 WASM: ﻿Unhandled exception rendering component:
blazor.webassembly.js (1,32075)

 WASM: Microsoft.JSInterop.JSException: InvalidStateError
blazor.webassembly.js (1,32075)

 WASM: undefined
blazor.webassembly.js (1,32075)

 WASM:   at Mono.WebAssembly.Interop.MonoWebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,T2,TRes] (System.String identifier, T0 arg0, T1 arg1, T2 arg2) <0x1d1e150 + 0x00044> in <0544639430f948ad82c54a3effb7ea00>:0 
blazor.webassembly.js (1,32075)

 WASM:   at Mono.WebAssembly.Interop.MonoWebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,TRes] (System.String identifier, T0 arg0, T1 arg1) <0x1d1e078 + 0x00016> in <0544639430f948ad82c54a3effb7ea00>:0 
blazor.webassembly.js (1,32075)

 WASM:   at Microsoft.AspNetCore.Blazor.Rendering.WebAssemblyRenderer.UpdateDisplayAsync (Microsoft.AspNetCore.Components.Rendering.RenderBatch& batch) <0x1d1df80 + 0x0001e> in <91b564433c704544acd7894656c3aff9>:0 
blazor.webassembly.js (1,32075)

 WASM:   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue () <0x1bf4ee0 + 0x000be> in <13ab8f8dacb6489b93c9655168c56037>:0 
blazor.webassembly.js (1,32075)

```

Include the output of `dotnet --info`:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007474 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008533 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by hosezelt** [comment]
I stumbled upon a similar issue with <input type="file"> server-side Blazor.

**To Reproduce**
- Same steps as laid out by @Tewr 
- After choosing a file, the iisexpress.exe exits with code -1. In Chrome nothing happens, as expected.

**Context**

.Net core Preview 5 SDK, VS Preview 3, Edge Dev Version 76.0.152.0

**Comment by mgochmuradov** [comment]
For server-side it is enough just adding a tag, without binding:
```
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<input class="form-control" type="file" id="file" name="file" />
```

After this press on Browse, and select a file or just cancel, app will stop.

**Comment by Tewr** [comment]
I have upgraded to preview6. 
As the syntax has changed slightly, here's my new code:

```
<input type="file" @ref="@fileInputRef" @bind="@fileInputBind" />
@functions {
    ElementRef fileInputRef;
    string fileInputBind;
}
```

Still doesnt work but the behaviour is very different: 
Edge crashes on application startup. Chrome still works as expected.

Edge console output:

```
Stacktrace: 

 Error
   at Anonymous function (http://localhost:65271/_framework/wasm/mono.js:1:19058)
   at _emscripten_asm_const_i (http://localhost:65271/_framework/wasm/mono.js:1:19231)
   at Module[_mono_wasm_load_runtime] (http://localhost:65271/_framework/wasm/mono.js:1:220077)
   at ccall (http://localhost:65271/_framework/wasm/mono.js:1:7192)
   at Anonymous function (http://localhost:65271/_framework/wasm/mono.js:1:7548)
   at Anonymous function (http://localhost:65271/_framework/blazor.webassembly.js:1:34965)
   at callRuntimeCallbacks (http://localhost:65271/_framework/wasm/mono.js:1:14059)
   at postRun (http://localhost:65271/_framework/wasm/mono.js:1:15221)
   at doRun (http://localhost:65271/_framework/wasm/mono.js:1:239523)
   at run (http://localhost:65271/_framework/wasm/mono.js:1:239680)

 WASM: * Assertion at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/metadata/metadata.c:1233, condition `disabled>' 
```







donet --info
```

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf


```

**Comment by Tewr** [comment]
I have upgraded to preview 6.
After having modified my example above to use the latest syntax, this now works as expected.
