### ISSUE TITLE
Various projects are now depending on .Net Core instead of .Net Standard

### ISSUE THREAD

**Issue by jeroenlandheer** [aspnet/AspNetCore#10039]
Various projects depend on netcoreapp while they used to depend on netstandard. This narrows the availability of these projects to a single platform. (i.e. .Net Core). (.NetStandard can be used from the .Net Framework as well.)

For example, we use here the Microsoft.AspNetCore.Authentication.JwtBearer as a library to validate JWT tokens. Up to version 2.x this works fine, from V3 onward this library has become a .Net Core library and is no longer usable from .Net Standard libraries.

Is there a possibility that these libraries could remain in .Net Standard?

**Comment by PinpointTownes** [comment]
This has been discussed at length here: https://github.com/aspnet/AspNetCore/issues/3753.

If your library depends on ASP.NET Core, then the most sensible option is to move to `netcoreapp3.0`. If it doesn't, you'll probably want to directly use `System.IdentityModel.Tokens.Jwt`, which is the package the ASP.NET Core JWT handler relies on under the hood.

**Comment by jeroenlandheer** [comment]
@PinpointTownes Alright, wasn't aware of that discussion, thanks for the info :)
