### ISSUE TITLE
Better linker issue diagnosis

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#10045]
Lots of users encounter issues with the Mono linker, and its error messages are unclear. This costs time for customers and for the team in making sense of issues.

**Suggestion**

1. We should create a wiki page describing how to interpret linker errors. Basically it needs to cover "why you can't use native code and what the errors look like" and "how to check if disabling the linker fixes your issue (e.g., because it's stripping code you need)", and in both cases what to do about them.
2. We should follow up with the Mono team about improving the error messages. It should at least be able to identify the "native code" case and tell you clearly which dependency isn't usable.

**Comment by danroth27** [comment]
Updating the linker to provide a better error message is tracked by: https://github.com/mono/mono/issues/12916

**Comment by mkArtakMSFT** [comment]
Closed in favor of the linked issue.
