### ISSUE TITLE
[OnSerializing] attribute callback not triggering when using System.Text.Json

### ISSUE THREAD

**Issue by alextech** [aspnet/AspNetCore#10047]
`[OnSerializing]` Attribute is not triggered when using System.Text.Json . The .Net Core Preview 5 blog post suggests moving from NewtonSoft serializer to builtin one, but does not mention any migration paths, so I assume they should work the same way. Is this the case?

### To Reproduce
In object to be serialized, such as output of a REST API controller, mark a method with `[OnSerializing]` attribute.

### Expected behavior
Marked method executes before output to page

### Additional context
dotnet --info
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#37503
