### ISSUE TITLE
Static Resources In Razor Class Libraries

### ISSUE THREAD

**Issue by alexandrereyes** [aspnet/AspNetCore#10046]
I'm trying to include static resources to a razor class library following this tutorial: https://www.mikesdotnetting.com/article/330/including-static-resources-in-razor-class-libraries-in-asp-net-core

But it's throwing the error:
Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'MyAssembly'

The class library already does reference to the package Microsoft.Extensions.FileProviders.Embedded

Does Blazor support it?

**Comment by rynowak** [comment]
Please provide a repro project if you want us to be able to help. 

Did you set `<GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>`?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @alexandrereyes.
This is now supported through the `Static assets` support feature: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/
