### ISSUE TITLE
Worker Service .NET Core Project Not Accepting Ctrl+C SIGINT input in VS Code

### ISSUE THREAD

**Issue by luisquintanilla** [aspnet/AspNetCore#10051]
Using .NET CLI to run / stop a Worker Service project in VS Code integrated terminal does not accept SIGINT `Ctrl+C` to stop the application. For more details, see issue raised in VS Code repo.

microsoft/vscode#73435

**Comment by Tratcher** [comment]
Sounds like the events are not reaching the app. Try hooking `Console.CancelKeyPress` in Program.Main and see if you can hit a breakpoint in your callback in the different environments.

**Comment by luisquintanilla** [comment]
Hmm. Not sure if any changes went in between the time I raised the issue and now. I tried setting `Console.CancelKeyPress` and that worked both in VS Code and CMD/PowerShell. I then ran the application again without it and it worked as expected.

**Comment by Tratcher** [comment]
At least it's working now 😁
