### ISSUE TITLE
The Identity (UserManager) architecture is bad and/or unintuitive 

### ISSUE THREAD

**Issue by gliljas** [aspnet/AspNetCore#10055]
At first glance, the architecture and the implementations needed to create the various "stores" in an Identity storage provider seems clear cut.

In IUserPasswordStore<TUser>:
`Task SetPasswordHashAsync(TUser user, string passwordHash, CancellationToken cancellationToken);`

Easy peasy. It's a store. I'll implement something that stores the password for a user!

Done.

Let's use the UserManager. It's after all part of the raison d'être of this system.

Create a user with a password.

Boom!

Huh? The UserManager calls SetPasswordHashAsync before Create(User). 

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Core/src/UserManager.cs#L585

Since the user doesn't exist, my IUserPasswordStore either throws an error or doesn't do anything.

Sure, the IUserPasswordStore is always the IUserStore, but the behavior is unexpected. Even more so since SetPasswordHashAsync is async. Nothing indicates that the store is actually a unit of work.

From the docs.
> The IUserPasswordStore<TUser> interface defines the methods you implement to persist hashed passwords.

No, it doesn't. 100% of the full implementations I've seen requires TUser to hold the password hash, and SetPasswordHashAsync just modifies this property (and returns a Task). That's not persisting. It works fine, sort of, for things like the Entity Framework provider, but even then it can be debated if the store abstractions are suitable.

I can store the hash in e.g a Dictionary, perhaps with a WeakReference, and pull it out in Create(User), but that smells a bit. Some kind of unit of work would be nice. 

[Related issue from the archived Identity project](https://github.com/aspnet/Identity/issues/1865)

**Comment by blowdart** [comment]
@HaoK thoughts please.

**Comment by gliljas** [comment]
Adding....

1. Yes.. I can create a derived UserManager type, but that sort of defeats the model.
2. It's not only SetPasswordHashAsync that behaves like this. 
3. Having an explicit UpdateAsync method on IUserStore indicates that it's not actually a unit of work suitable for OR-mappers etc., where the entire TUser instance is change tracked and persisted. I'm guessing that it would be possible to end up making unintended modifications. Maybe not.

**Comment by blowdart** [comment]
So this isn't a unit of work thing, we simply don't have that concept. You need to create the user first, and not just by newing up a user, you need to create one, and then pass it through.

Yes the architecture is old, but we're constrained by back compat and we don't have the investment to change it just yet.

I'd suggest looking at the templates to see how the flow is supposed to go.

**Comment by gliljas** [comment]
I understand that it's not something that will be fixed tomorrow, but it's certainly something that should be discussed. If not here, where?
