### ISSUE TITLE
We should remove the namespace Microsoft.AspNetCore.Http.Endpoints

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#10066]
The only thing in this namespace is the extension methods `GetEndpoint()` and `SetEndpoint()`. `Endpoint` is defined in `Microsoft.AspNetCore.Http`. We should move these extension methods there too.

**Comment by rynowak** [comment]
@davidfowl

**Comment by davidfowl** [comment]
Yep

**Comment by anurse** [comment]
Assigning to me to confirm and mark accepted.
