### ISSUE TITLE
Inject IViewLocalizer to model

### ISSUE THREAD

**Issue by spaasis** [aspnet/AspNetCore#10069]
### Is your feature request related to a problem? Please describe.
I am trying to add localized error messages to ModelState in a Razor Page model. I am using IViewLocalizer in the view, and would like to store the error messages in the same resource files as well.

### Describe the solution you'd like
I would like to be able to inject ViewLocalizer into the model and use it directly. Currently it throws a nullreference when trying to get a string, since _localizer is null (probably because model != view).

### Describe alternatives you've considered
One alternative is for me to create a dummy class for the resource files, which would allow me to use for example IStringLocalizer<DummyClass>, but I don't like this approach. It creates a bunch of useless files, and will cause confusion because some resource files have the classes and some don't (if they don't need any specific error messages). Plus, editing the resource files under a dummy class is a bit annoying in VS19 since everytime such a file is opened and edited, VS throws a confirmation dialog my way.

Another option is to add a new resource file for the model, but that doesn't seem too good either, since the resource files would mostly contain only a few lines.

**Comment by GuidoNeele** [comment]
I'm injecting IStringLocalizerFactory so I can use the same resource file for different controllers/models. 
`factory.Create(typeof(MyResource))`
You will need the dummy MyResource class file.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @spaasis.
It's not clear what you're trying to do, actually. Can you please share some more details with us regarding your scenario as well as a repro project so we can try to help.

**Comment by spaasis** [comment]
@GuidoNeele Yup, that will certainly work, but I would like to avoid the dummy class if at all possible for the reasons mentioned in the starting post.

@mkArtakMSFT let's see if I can clarify (I can whip up a project if necessary, but let's see).

Assume that I have a View `MyView.cshtml` and a corresponding Model `MyViewModel` in `MyView.cshtml.cs`.
In the View I `@inject IViewLocalizer`, which loads the localized strings automatically from `Resources/MyView.en.resx`. Everything is fine at this point.

Now in the Model I need to have some translated messages. These messages logically belong in the  same resource file `MyView.en.resx`. I would like to do this by injecting `IViewLocalizer` to the Model, but this doesn't currently work, as it works only for .cshtml-files.

Currently my options are to create a dummy class `Resources/MyView.cs` or create a new resource dictionary `Resources/MyViewModel.cs`, but I don't think these approaches are perfect due to the reasons mentioned in the opening post.

Does this clarify the proposal? In a nutshell I'm suggesting that IViewLocalizer resource fetching should work equally for Views and Models.

**Comment by spaasis** [comment]
Could there be something added here so it checks the .cshtml.cs-file also? https://github.com/aspnet/AspNetCore/blob/def36fab1e45ef7f169dfe7b59604d0002df3b7c/src/Mvc/Mvc.Localization/src/ViewLocalizer.cs#L105

**Comment by GuidoNeele** [comment]
@spaasis Ah I see, you still want the separate resx files per view, just with the model translations also included. Still think you can use the IStringLocalizerFactory for that. See https://www.jeffogata.com/asp-net-core-localization-strings/. `var sharedStringLocalizer = stringLocalizerFactory.Create("Shared", null);`. No need for a dummy file if you use strings in the Create().
If this doesn't work you can always write your own custom localizer and inject that one. See https://github.com/aspnet/Localization/blob/master/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs

**Comment by spaasis** [comment]
Oh, that's a nice trick (using strings in the create)! That'll probably suite me the best of the current options, so I'll close this. Thanks for the help, both of you!
