### ISSUE TITLE
EventCallback<T> Error cannot convert from 'method group' to 'EventCallback'

### ISSUE THREAD

**Issue by drinkwater99** [aspnet/AspNetCore#10077]
### Describe the bug
Using the following two components, the compiler emits an error in the Parent component  in the OnSelect event parameter.

Error cannot convert from 'method group' to 'EventCallback'

```
<Child Data="@Data" OnSelect="@OnSelect">
</Child>
```

Is this an issue or I am doing this wrong ?

### To Reproduce

```
@*Parent.razor*@

@page "/Parent"

<div>
    <Child Data="@Data" OnSelect="@OnSelect">
    </Child>
</div>

@functions {
    List<Item> Data = new List<Item>();

    private void OnSelect(Item item)
    {        
    }
}
```
```
@*Child.razor*@

@typeparam TData

<div>
    @foreach (var item in Data)
    {
        <button onclick="@(() => OnSelect.InvokeAsync(item))"></button>
    }
</div>

@functions {
    [Parameter]
    public IEnumerable<TData> Data { get; set; }

    [Parameter]
    private EventCallback<TData> OnSelect { get; set; }
}
```
```
// Item.cs
public class Item
{
     public Item()
     {

     }
}
```

**Comment by enetstudio** [comment]
shouldn't you use async  before () => OnSelect.InvokeAsync(item)  ?
shouldn't you define Task instead of void with the definition of OnSelect ?
Would you try Func<TData, Task> instead of EventCallback ?

**Comment by drinkwater99** [comment]
Using async and Task does not change anything - the error remains.

The only way I am able to make it work is by doing the following in the Parent component event handler :
```
<Child Data="@Data" OnSelect2="@((Item item) => { OnSelect(item); })"></Child>
```
instead of :
```
<Child Data="@Data" OnSelect="@OnSelect">
```

Seems kind of strange to me that it would need to be done that way though.

**Comment by stsrki** [comment]
@drinkwater99 You're seeing this error because of generics(typeparam) with EventCallback, It's not supported yet.
I have also reported that bug months ago and still waiting. see #8385

**Comment by rynowak** [comment]
This has been added in **preview 7** - https://github.com/aspnet/AspNetCore/pull/10730
Note that **preview 6** is the next release so you will have to wait a few weeks.

**Comment by MichaelPeter** [comment]
Hey I have Installed preview but I still get this error, shouldn't this be fixed?
