### ISSUE TITLE
System.Text.Json serialize accurate DateTime incorrectly!

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/AspNetCore#10070]
aspnetcore3.0 preview5 using System.Text.Json as input- and outputformatter:
if DateTime is too accurate (sqlserver datetime2), it will serialize it to invalid format like: **2019-05-08T00:00:5406760219**
This kind of result could not even be recognized by **DateTime.Parse**.
I think it should be **2019-05-08T00:00:54.06760219** (with a dot between seconds number and others) which can be parsed by DateTime class.

![批注 2019-05-08 143028](https://user-images.githubusercontent.com/3364218/57354392-e9edf100-719d-11e9-88b9-be9d2c86744a.png)

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#37515

**Comment by Eilon** [comment]
Done. BTW you can use https://hubbup.io/Mover (runs on Blazor WASM!) to move issues as well.

**Comment by pranavkm** [comment]
@Eilon please move to dotnet/corefx.
