### ISSUE TITLE
Debugger in Visual Studio Code crashes

### ISSUE THREAD

**Issue by emilmuller** [aspnet/AspNetCore#10072]
I'm unsure if I'm posting this in the correct repository, so please correct me if this is not the case.

I have created an ASP.NET Core application, and I'm debugging in Linux. The application is a Web API. To ensure that it is stable, I am stress testing it locally while debugging.

What happens is I'm sending a couple of thousand requests, and then it crashes. There are no error messages in the Debug Console. The debug session just ends silently in Visual Studio Code (debugging buttons disappears as if the application has stopped). If I restart Visual Studio Code and try to start my application it again, it will fail with an error message saying that the port is busy. I have to kill dotnet manually.

As mentioned earlier, I don't see any error messages when this happens, but maybe there are some logs somewhere that I can provide here? Please let me know!

Kind regards

**Comment by Eilon** [comment]
Hi @emilmuller , have you enabled any logging in the application at all? Even something like the Console Logger could emit some useful info. But, an app just suddenly stopping is often an indication that a background task/thread has thrown an exception that wasn't caught, because that will immediately terminate the application. You can try setting the debugger to catch *all* exceptions (incl. First Chance exceptions) and see if that's the case.

**Comment by emilmuller** [comment]
@Eilon I won't be back in the office until Monday, so I will try and enable some more exception catching then :)

However, when I compile this in release mode, it runs stable and does not crash. I have no pragmas in my code, so it should mostly be executing the same code.

And when debugging, the application doesn't seem to terminate. In Visual Studio code, the debugging session seems to end, but the dotnet process is still running. I have to kill it manually when restarting Code to be able to use the port again.

I am catching all exceptions in code and breaking, but there are currently none.

**Comment by Eilon** [comment]
@emilmuller that is certainly very odd... any additional information you can provide would be helpful. If you can upload the app or a simplified repro to a GitHub repo that would be awesome.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
