### ISSUE TITLE
Blazor renders incorrect HTML after contentedibale is edited

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#10087]
I have just made a simple application to partially solve the problem described here #9974 
In this application (complete project available here https://github.com/Andrzej-W/ContentEditable) I have a simple `div` element and a button. I can click the button to enable/disable editing in the `div`. Unfortunately when I click the button to disable editing Blazor renders wrong HTML code for this `div` element.
I'm using ASP.NET Core Preview 5 and VS 2019 16.1.0 Preview 3.0.

```html
@page "/"
@inject IJSRuntime JS

<div ref="editor" contenteditable="@editMode">@((MarkupString)content)</div>
<button onclick="@ChangeMode">@buttonText</button>
<div>Current content:<br />@content</div>
```
```c#
@functions
{
    ElementRef editor;
    const string buttonTextStart = "Start editing";
    const string buttonTextStop = "Stop editing";
    string content = "ab";
    bool editMode = false;
    string buttonText = buttonTextStart;

    async Task ChangeMode()
    {
        editMode = !editMode;
        buttonText = editMode ? buttonTextStop : buttonTextStart;
        if (!editMode)
        {
            string tmp = await JS.InvokeAsync<string>("JsLib.getInnerHtml", editor);
            content = tmp.Replace("<!--!-->", string.Empty);
        }
    }
}
```
JavaScript code used to get inner html of `div`
```js
window.JsLib = {
    getInnerHtml: function (element) {
        console.log(element);
        return element.innerHTML;
    }
};
```
When page is first rendered html for `div` element looks like this:
```html
<div _bl_2="">
  <!--!-->
  ab
</div>
```
Now click the button to enable editing. Position your cursor between letter `a` and `b` and press `Enter` key to move letter `b` to new line. HTML will look like this:
```html
<div _bl_2="" contenteditable="">
  <!--!-->
  <div>a</div>
  <div>b</div>
</div>
```
Click the button again to disable editing. Program will call JS code to read inner HTML. Comment `<!--!-->` will be removed and new content will be rendered as MarkupString to preserve HTML tags. After all this we can see wrong HTML in `div`:
```html
<div _bl_2="">
  <div>a</div>
  <div></div>
  <!--!-->
  <div>a</div>
  <div>b</div>
</div>
```
Correct HTML should be:
```html
<div _bl_2="">
  <!--!-->
  <div>a</div>
  <div>b</div>
</div>
```

**Comment by Andrzej-W** [comment]
The above test has been done in Firefox. Chrome creates only one `div` element after `Enter`
```html
<div _bl_2="" contenteditable="">
  <!--!-->
  a
  <div>b</div>
</div>
```
but final result is also wrong:
```html
<div _bl_2="">
  a
  <div></div>
  <!--!-->
  a
  <div>b</div>
</div>
```

**Comment by SteveSandersonMS** [comment]
I'd recommend populating your contenteditable div via JS interop instead of via `MarkupString`, because then Blazor will not be trying to control the contents of that element.

In general, contenteditable is a nightmare for cross-browser compatibility, as all browsers do differently bizarre things. It's one of the few areas of modern web dev where it feels like we're still back in 2001 - nothing about it has really been standardised. It's not an area we'll be focusing on soon, so I'd recommend that whatever you do with it, you do via JS interop so that Blazor's renderer is not involved.

**Comment by SteveSandersonMS** [comment]
I'm closing this as it's not an area we plan to take action on soon, and we do already have a separate issue tracking the whole matter of contenteditable as a feature.
