### ISSUE TITLE
Can the HostingRequestFinishedLog.ToString include the request url too?

### ISSUE THREAD

**Issue by kevinlo** [aspnet/AspNetCore#10097]
[HostingRequestFinishedLog.ToString ](https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/Hosting/src/Internal/HostingRequestFinishedLog.cs#L47) currently just has the elapsedTime, but not the request URL.

> "Request finished in {elapsedTime}ms {statusCode} {ContentType}",  

It is easier to match with the Request starting if it can include the URL like this.

> Request starting HTTP/1.1 GET http://myserver/myapi/myitem/123 [ 16984:92 ]
> Request finished HTTP/1.1 GET http://myserver/myapi/myitem/123 in 501.525ms 200 application/json; charset=utf-8 [ 16984:98 ]
> 

In my log files, sometimes it has a few Request finished around the same time and I cannot tell which one is which quickly without spending time to trace back the log.

This HostingRequestFinishedLog class is internal, I cannot find an easy way I can customize it to provide a custom ToString.

The HostingRequestStartingLog and HostingRequestFinishedLog are run in different thread, I cannot use the threadId to match the log.

**Comment by benaadams** [comment]
This work? https://github.com/aspnet/AspNetCore/pull/10102

**Comment by kevinlo** [comment]
@benaadams.   That works.  Which version will have it?

**Comment by benaadams** [comment]
Up to ASP.NET team 😄

**Comment by davidfowl** [comment]
> @benaadams. That works. Which version will have it?

If we take it, 3.0.

**Comment by kevinlo** [comment]
@davidfowl  For 2.x, is there any alternative solution?

**Comment by benaadams** [comment]
You could add your own middleware at the start of the pipeline and then log on the way out; see https://github.com/aspnet/AspNetCore/issues/5894#issuecomment-421688486

**Comment by kevinlo** [comment]
@benaadams I know I can add my own middleware at the beginning of the pipeline.  But then it will have duplicated logging as the Webhost one that I could not turn off.   Moreover, I think the Webhost one provide more accurate elapsed from start to finish.   

I just want to check if there is a better solution.   If not, I can add my own Middleware for now.

Thanks all for your help.
