### ISSUE TITLE
SignalR amd module

### ISSUE THREAD

**Issue by zefubachs** [aspnet/AspNetCore#10108]
I'm using razor pages in combination with typescript and knockout to create page based viewmodels.

I'm using AMD (requirejs) to load knockout and other (transpiled) typescript files.
Documentation only shows how to use SignalR directly using a `<script>` tag or via webpack, which i would like to avoid because i'm already using amd module loading and adds extra js build dependencies.

Is there an amd module variant of SignalR available to use, or which steps could be taken to load signalr as an amd module?

**Comment by anurse** [comment]
The "browser" version (the one used by `<script>` tags) is designed as a [Universal Module Definition (UMD)](https://github.com/umdjs/umd#umd-universal-module-definition) module. So if you import it via a `<script>` tag, it registers itself as a global. But if you use `requirejs` to load it, it will load as an AMD module.

The default `index.js` file for the module is the "CommonJS" version (for NodeJS and WebPack-style bundlers), so you will need to configure requirejs to load the `dist/browser/signalr.js` file from within the package.

**Comment by zefubachs** [comment]
Hey anurse,

Directly using the browser js file worked but there is no intellisense in Visual Studio since there is no signalr.d.ts file.

**Comment by anurse** [comment]
The default `.d.ts` file in the package should work fine for the UMD build (the browser one). How are you referencing the package? Do you have the `@aspnet/signalr` npm package installed?

**Comment by zefubachs** [comment]
Yes, i'm using the @aspnet/signalr package from npm but manually copy the `signalr.js` file to a lib folder in the wwwroot of my project.

**Comment by anurse** [comment]
> manually copy the `signalr.js` file to a lib folder

That's the problem then. Since you aren't referencing it as a package the VS IntelliSense doesn't know how to find the `.d.ts` file. 

There is no unified `.d.ts` file to copy. Is the `node_modules` directory still under your project root? If so, you can tell TypeScript/JavaScript intellisense to look at it by setting the `types` value in your `tsconfig.json` file (see https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)

For example:

```json
{
    "compilerOptions": {
        "types": [
            "@aspnet/signalr"
        ]
    }
}
```
