### ISSUE TITLE
Can I send binary data from a JS Promise to a Blazor client-side ?

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#10104]
Help is needed here...

Can I send binary data from a JS Promise to a Blazor client-side, using HttpClient ? How to do that ?

Many thanks...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @enetstudio.
It's not clear what you mean by `using HttpClient`? Please provide more details about what you're trying to do.

**Comment by enetstudio** [comment]
Thanks... I've found the answer here: https://github.com/aspnet/Blazor/pull/815
