### ISSUE TITLE
Symbols from daily builds of master brancn are not published to symbol server

### ISSUE THREAD

**Issue by gregg-miskelly** [aspnet/AspNetCore#10113]
## Summary
The C# extension test team recently did a test of symbol server support using a preview6 build of the framework and found that one assembly, Microsoft.AspNetCore.Routing.Abstractions, had a PDB file, but the PDB wasn't published to symbol server.

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-011799
 Commit:    3816213dde

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview6-011799/

Host (useful for support):
  Version: 3.0.0-preview6-27707-07
  Commit:  c9e7f134dc

.NET Core SDKs installed:
  3.0.100-preview6-011799 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview6-19257-04 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27707-07 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
VS Code version: 1.33.1
C# Extension version: 1.19 (v1.19.1)
## Steps to reproduce
1. Create a new ASP.NET Razor project by doing
 
 
	mkdir razor
	cd razor
	dotnet new razor

2. Open razor with VScode
3. It may ask at the bottom right to install assets to build and debug, say yes.  
4. After it has done this it will have created a .vscode directory in the ‘razor’ directory and a ‘launch.json’ file in that directory.   Open the ‘.vscode’ directory, and double click on the ‘launch.json to edit it. 
5. Add the following lines after the “name” line of the “Configurations” object.   (This allows debugging through the framework.  
	 
		"justMyCode": false,
		"symbolOptions": {
		      "searchMicrosoftSymbolServer": true
		},
		"suppressJITOptimizations": true,
 
 
6. Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code. 
7.  Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file).  
	Console.WriteLine("x " + 3);
 
8. Place a breakpoint on that line (F9). 
9. Run the application until it hit that breakpoint (F5).   

## Expected  behavior
It will load symbols from the Microsoft symbol server successfully.

## Actual behavior
One assembly, Microsoft.AspNetCore.Routing.Abstractions, didn't have symbols.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gregg-miskelly.
@natemcmaster can you please advise where the symbols are?

**Comment by natemcmaster** [comment]
Symbols for daily builds of AspNetCore will be available on the Microsoft public symbols server. This is currently broken for the master branch of this repo. https://github.com/aspnet/AspNetCore-Internal/issues/2126 tracks re-enabling our symbols publishing.

**Comment by dougbu** [comment]
@natemcmaster last I looked, symbol publishing was working fine. We just got errors about using the current task in a release pipeline. Has something changed?

**Comment by natemcmaster** [comment]
@dougbu It looks like Gregg is trying to use a build that came from our master branch. I think our pipeline is only publishing symbols for release/* branches. IIRC last time we talked about it, we planned to enable publishing symbols for the master branch too once https://github.com/aspnet/AspNetCore-Internal/issues/2126 was resolved.

**Comment by dougbu** [comment]
@natemcmaster :ok:

@gregg-miskelly to confirm: You were unable to find symbols for _any_ assembly from this repo (for Preview 6 i.e. from 'master') and Microsoft.AspNetCore.Routing.Abstractions was just an example?

Side question; https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview5.md shows we now produce "symbol sets" for 3.0 releases. But, I could find no documentation on how to use those. Do you have a link?

**Comment by gregg-miskelly** [comment]
@Jepson109 is actually who ran into this problem. I just routed the issue to the right home. @Jepson109 can you copy/paste your debug console text?

**Comment by dougbu** [comment]
Almost done. Will almost-unconditionally enable the new symbol deployment step in the release pipeline once an official build containing aspnet/AspNetCore@3bb9cda189da completes.
