### ISSUE TITLE
Unify TS and C# auto-reconnect APIs

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#10128]
In 3.0, auto-reconnect support is being added to the TS and C# SignalR clients. The APIs are mostly the same except for two notable differences.

In the TS client, we have:

```TS
IReconnectPolicy.nextRetryDelayInMilliseconds(previousRetryCount: number, elapsedMilliseconds: number): number | null;
```

And in the C# client, we have:

```C#
IRetryPolicy.NextRetryDelay(RetryContext retryContext);

public sealed class RetryContext
{
    public long PreviousRetryCount { get; set; }
    public TimeSpan ElapsedTime { get; set; }
    public Exception RetryReason { get; set; }
}
```

The first difference is `IReconnectPolicy` vs `IRetryPolicy`. I prefer changing the TS client to use `IRetryPolicy` since the interface could be used for more than just reconnects in the future (e.g. retrying starting the connection initially).

The second difference is having a `RetryContext` instead of individual parameters. I like having the `RetryContext` since you don't need to add new overload methods to the interface to add more information. I wouldn't mind renaming `RetryContext` to `RetryInfo` in both clients though. I think "Info" is more familiar than "Context" in JS/TS, and I don't think it's too out-of-place in .NET.

The TS client changes would break anyone who wrote a custom IReconnectPolicy using the preview. I'm not sure if this warrants a breaking change announcement.

@anurse

**Comment by anurse** [comment]
👍 

> I think "Info" is more familiar than "Context" in JS/TS

Is it? I'm not a fan of "Info" unless we really think that's the very common pattern.

> I'm not sure if this warrants a breaking change announcement.

Better to announce it.

**Comment by mikaelm12** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [ ] This is a Docs issue.
* [x] The fix contains product changes (**check all items below**).
	* [x] Relevant XML documentation comments for new public APIs are present. - Not needed
	* [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [x] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [https://github.com/aspnet/AspNetCore.Docs/pull/12875]
		* [ ] The change requires no docs changes.
	* [x] Verification has been completed. (**check one item below**)
    	* [ ] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [version]
			* ASP.NET Core Runtime: [version]
			* .NET Core Runtime: [version]
	    * [x] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: aspnet-signalr-3.0.0-preview7.19325.3
