### ISSUE TITLE
not found (>= 2.2.4) package Microsoft.NETCore.App

### ISSUE THREAD

**Issue by bluetianx** [aspnet/AspNetCore#10132]
### Describe the bug
dotnet publish error about not found (>= 2.2.4) 的package Microsoft.NETCore.App ,when I execute cmd that dotnet publish -c release -o C:\test -r win-x64 --self-contained.
### To Reproduce
I have Migrated from ASP.NET Core 2.1 to 2.2 for using Microsoft.AspNetCore.SignalR.StackExchangeRedis.

but there is a error in my build & deploy server,when I execute cmd that dotnet publish -c release -o C:\publis -r win-x64 --self-contained.
the erroe info : 
```
E:\Agent1\signalr\SignalR\SignalR\SignalR.csproj : error NU1102: 找不到版本为 (>= 2.2.4) 的包 Microsoft.NETCore.App
E:\Agent1\signalr\SignalR\SignalR\SignalR.csproj : error NU1102:   - 在 Microsoft Visual Studio Offline P
ackages 中找到 7 个版本[ 最接近版本: 1.1.2 ]
E:\Agent1\signalr\SignalR\SignalR\.SignalR.csproj : error NU1102:   - 在 LocalSource 中找到 5 个版本[ 最接
近版本: 2.2.0 ]
E:\Agent1\signalr\.SignalR\SignalR\SignalR.csproj : error NU1102: 找不到版本为 (>= 2.2.4) 的包 Microsoft.AspNetCore.App
E:\Agent1\signalr\SignalR\SignalR\SignalR.csproj : error NU1102:   - 在 LocalSource 中找到 1 个版本[ 最接
近版本: 2.1.5 ]
E:\Agent1\signalr\SignalR\SignalR\.SignalR.csproj : error NU1102:   - 在 Microsoft Visual Studio Offline P
ackages 中找到 0 个版本

```
english error info:

```
Csproj: error NU1102: cannot find package Microsoft.NET core.app with version (>= 2.2.4)
E:\Agent1\signalr\ signalr\ signalr\ signalr. Csproj: error NU1102: - in Microsoft Visual Studio Offline P
7 versions found in ackages [nearest version: 1.1.2]
E:\Agent1\signalr\ signalr\ signalr\. Signalr. Csproj: error NU1102: - find 5 versions in LocalSource
Recent version: 2.2.0]
E:\Agent1\signalr\. Signalr \signalr\ signalr. Csproj: error NU1102: Microsoft. Aspnetcore. App with version (>= 2.2.4) could not be found
E:\Agent1\signalr\ signalr\ signalr\ signalr. Csproj: error NU1102: - find 1 version in LocalSource
Recent version: 2.1.5]
E:\Agent1\signalr\ signalr\ signalr\. Signalr. Csproj: error NU1102: - in Microsoft Visual Studio Offline P
Find 0 versions in ackages

```

### Additional context
my dotnet sdk list as ：
1.1.9 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.2.203 [C:\Program Files\dotnet\sdk]

VS: vs2017
OS:Windows Server 2016 Standard

**Comment by anurse** [comment]
Do you have `NuGet.org` configured as a package source? The error message indicates you're only installing from a custom local source and the VS offline feed. `Microsoft.NETCore.App 2.2.4` and `Microsoft.AspNetCore.App 2.2.4` are required in order to perform a self-contained publish of this application.

**Comment by bluetianx** [comment]
Yep .I did that.But I have installed dotnet core SDK 2.2.203 on my compute

**Comment by bluetianx** [comment]
SDK 2.2.203 dose not include Microsoft.NETCore.App 2.2.4 and Microsoft.AspNetCore.App 2.2.4 ？

**Comment by anurse** [comment]
I don't believe the SDKs carry the packages needed for *self-contained* deployments like this. I believe you still need packages from NuGet.org when doing that kind of deployment.

**Comment by bluetianx** [comment]
I got it,I used to  think Microsoft.NETCore.App 2.2.4 and Microsoft.AspNetCore.App 2.2.4 are part  of SDK.

**Comment by bluetianx** [comment]
I have resoled it， Thank you very much @anurse
