### ISSUE TITLE
Asp.Net Core throws exception when the model class was changed

### ISSUE THREAD

**Issue by wryba** [aspnet/AspNetCore#10145]
> We're closing this as we can't reproduce this issue. If you can provide a repro project, feel free to reopen the issue so we can investigate it further.
_Originally posted by @mkArtakMSFT in https://github.com/aspnet/Mvc/issues/8525#issuecomment-429399722_

### To Reproduce
1. Using this version of ASP.NET Core '2.2.0'
2. Create Asp.Net Core app (API) project
3. Add cshtml page and the corresponding model class
4. Add UseMvc(); in Startup.Configure method
5. Use IRazorViewEngine to generate page using cshtml and a model class
6. Build, Run, initiate page creation with IRazorViewEngine 
7. Add new project (Razor Class Library) to sln
8. Move cshtml and model to new project
9. Fix all reference issues and errors
10. Build, Run, initiate page creation with IRazorViewEngine 
11. Runtime exception will appear

### Expected behavior
No runtime exception.

### Workaround
1. Close solution 
2. Delete "bin" and "obj" folders from project (API) 
3. Delete ".vs" folder from solution level

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
@wryba what are you really trying to do? What is your scenario?
If cleaning up your projects (bin , obj folders) fixes this, then I don't think there is worth for us to spend time on this, as this is then very minor issue.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
