### ISSUE TITLE
[Blazor] Using client-side without serving? Hash routung?

### ISSUE THREAD

**Issue by MrFoxPro** [aspnet/AspNetCore#10141]
Hi. Great work! Currently i want to use Blazor as UI for my project and I need to run Blazor app in CEF from file system, without static hosting.

For some reasons, chromium doesn't support fetching local files, so i decided to repalce fetch with shim that uses xhr. It's also doesn't work in chrome because of CORS policy, but i was anyway intrested in getting Blazor working offline, and in Firefox seems to be running OK with some errors: 
![image](https://user-images.githubusercontent.com/17229619/57518564-b7293180-7332-11e9-9608-d0011269ee53.png)
Despite this, Blazor works, but routing isn't because of slashes, so, i think it will be cool to implement feature for local blazor using with hash routing, like in react, for example.

Sorry for my bad English.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MrFoxPro.
Given that you're exploring an unsupported scenarios here, you'll have to come up with your custom hash based router implementation. This is not something we currently prioritizing. Hope you'll get help from the community anyway.
