### ISSUE TITLE
IApplicationFeatureProvider.PopulateFeature executes earlier for aspnetcore 2.2

### ISSUE THREAD

**Issue by ExplicitlyImplicit** [aspnet/AspNetCore#10157]
Before 2.2 I could add a derived type of IApplicationFeatureProvider<ControllerFeature> during startup in `ConfigureServices` and then configure it inside `Configure` after `UseMvc` is called. Now I must configure it before `UseMvc` as `PopulateFeature` is called during that `UseMvc` call. This makes it difficult for me since I need to overwrite routes declared in `UseMvc`.

Why was this changed and does anyone know of some workaround?

![image](https://user-images.githubusercontent.com/19637414/57551820-4dc51500-736a-11e9-93b5-24c849690eb1.png)

**Comment by pranavkm** [comment]
@rynowak \ @JamesNK, possibly a side-effect of using endpoint routing.

**Comment by rynowak** [comment]
You can work work around this for now with:

```C#
services.AddMvc(options => options.EnableEndpointRouting = false)
```

I'd be really interested to learn more about your requirements and why this is needed.  Care to explain what you're doing?

**Comment by ExplicitlyImplicit** [comment]
Thank you @pranavkm and @rynowak! disabling endpoint routing solves it - even though I probably need to solve it some other way since I'm not in control of calling `AddMvc`. 

I'm trying to update my library [Fluent Actions for ASP.NET Core MVC](https://github.com/ExplicitlyImplicit/AspNetCore.Mvc.FluentActions) which programmatically creates Controller types for MVC. 

Thank you for pinpointing what was causing it, I'm closing this issue since my questions been answered :)

**Comment by rynowak** [comment]
> Thank you for pinpointing what was causing it, I'm closing this issue since my questions been answered 

I'm glad that this unblocks you but this isn't really a solution. We've added a new routing system, and this is an escape hatch that lets you use the old one. I'd suggest trying this out with [3.0](https://dotnet.microsoft.com/download/dotnet-core/3.0) using one of the templates as a starter.

**Comment by ExplicitlyImplicit** [comment]
Yeah, it does not solve my use case unless I want to change my API. At least I know why now so I can investigate further. I'll give it some more time until I settle on a workaround, I'll also try out 3.0, thank you for the suggestion!
