### ISSUE TITLE
Blazor: Add onLeave event to razor pages

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore#10158]
It would be great to have an onLeave event added somehow.

It could be used to prompt the user when they try to leave the page to save their work or not.  Or to remove added listeners, send metrics to the server to capture time on page, etc. 

Reference this for a use case: https://github.com/aspnet/AspNetCore/issues/10147

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @VR-Architect.
This is not something we plan to do, as discussed here: #10098
