### ISSUE TITLE
Intelisense doesn`t work currently for Blazor component .razor files in VS2019 latest version

### ISSUE THREAD

**Issue by olkuziv** [aspnet/AspNetCore#10153]
### To Reproduce
1. Create .razor file
2. Add some logic and view
3. Close and open .razor file while intelisense dont stop working

### Expected behavior
Intelisense helps with namespace including
1. Create .razor file
2. Add some logic and view
3. All working as with cshtml file

### Screenshots
Current
![image](https://user-images.githubusercontent.com/33831834/57547880-32f1a100-7368-11e9-96bf-5a1c844585b0.png)
Expected result:
![image](https://user-images.githubusercontent.com/33831834/57547914-50bf0600-7368-11e9-8af5-445ac9d1aa5b.png)

**Comment by danroth27** [comment]
@olkuziv Please make sure you are using the latest Visual Studio *Preview* release (https://visualstudio.com/preview). Blazor tooling requires Visual Studio updates that are not available in the stable release of Visual Studio 2019.

I'm going to go ahead and close this issue, but if you still have issues with the latest Visual Studio preview, please let us know!

**Comment by olkuziv** [comment]
I was install latest preview version. Result stay the same:
![image](https://user-images.githubusercontent.com/33831834/57554098-2fb2e100-7379-11e9-981a-f715ebdedb5c.png)

**Comment by danroth27** [comment]
@olkuziv Is the namespace of the `MainLayoutModel` type in scope? What happens if you qualify `MainLayoutModel` with it's namespace?

**Comment by olkuziv** [comment]
When i full path all is working

**Comment by danroth27** [comment]
@olkuziv Could you please share the .csproj file contents for the project that is not showing correct intellisense?

**Comment by rynowak** [comment]
Closing due to lack of response.
