### ISSUE TITLE
Review pubternal types in SignalR and make them internal or public

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10169]
Pubternal is so last year. Let's review SignalR pubternal types and make decisions about what we want to make public and if there's anything we want to take internal.

**Comment by halter73** [comment]
@anurse Should we file a similar issue for Kestrel and all the other solutions that still have pubternal types? Or do we want this issue to track that as well?

**Comment by halter73** [comment]
Never mind. We merged https://github.com/aspnet/AspNetCore/pull/8517 already. https://github.com/aspnet/AspNetCore/issues/8308 is probably what we'd consider the "Epic" for this issue.

**Comment by anurse** [comment]
The first work item here is to find them and list them.

**Comment by mikaelm12** [comment]
**Microsoft.AspNetCore.Http.Connections.Client.Internal**
- ITransport
- ITransportFactory
- LongPollingTransport
- ServerSentEventsTransport
- WebsocketsTransport


**Microsoft.AspNetCore.Http.Connections.Internal.Transports**
- IHttpTransport
- LongPollingTransport
- ServerSentEventsTransport
- WebSocketsTransport
 Microsoft.AspNetCore.Http.Connections.Internal
- ServerSentEventsMessageFormatter


**Microsoft.AspNetCore.SignalR.Internal**
- DefaultHubActivator
- DefaultHubCallerContext
- DefaultHubDispatcher
- DefaultHubProtocolResolver
- HubCallerClients
- HubDispatcher
- HubOptionsSetup
- HubOptionsSetup<THub>
- HubReflectionHelper
- TypeBaseEnumerationExtensions


**Microsoft.AspNetCore.SignalR.StackExchangeRedis.Internal**
- GroupAction
- RedisGroupCommand
- RedisInvocation
- RedisProtocol

**Comment by anurse** [comment]
Nice, let's look at this in triage
