### ISSUE TITLE
Oauth metadata is acquired almost every request in Webapi with multiple schemes

### ISSUE THREAD

**Issue by rodan01** [aspnet/AspNetCore#10164]
A multitenant Webapi accepts tokens from multiple authorities. It configures multiple JwtBearer schemes. It calls HttpContext.AuthenticateAsync() for every scheme in each request, using a policy or manually.

The problem is that the authentication process validates the token starting with the signature, that's inefficient because obviously a token from a different issuer won't pass. But even worst. when the signature validation fails, the metadata cache is cleared because it could be a case of keys rollover. So in each request, the metadata of all the other schemes is lost and they have to acquire it again in the next request.

Validation should start with the cheap stuff, issuer obviously.

Metadata should only be deleted if the issuer of the token matches the issuer of the scheme or if the issuer is not being validated, for example, for the Azure AD common endpoint. I don't know how you can solve that particular case.

Here snippets of the code that causes the problem.

`validatedToken = ValidateSignature(token, validationParameters);`
`return ValidateTokenPayload(validatedToken as JwtSecurityToken, validationParameters);`
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs   Line 722

`// Refresh the configuration for exceptions that may be caused by key rollovers. The user can also request a refresh in the event.`
`if (Options.RefreshOnIssuerKeyNotFound && Options.ConfigurationManager != null`
`	&& ex is SecurityTokenSignatureKeyNotFoundException)`
`{`
`	Options.ConfigurationManager.RequestRefresh();`
`}`
https://github.com/aspnet/AspNetCore/blob/f4972dc6b61968ab244f6e030535974376298ba1/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs   Line 116

**Comment by brockallen** [comment]
> A multitenant Webapi accepts tokens from multiple authorities. It configures multiple JwtBearer schemes. It calls HttpContext.AuthenticateAsync() for every scheme in each request, using a policy or manually.

This is a bad design to begin with. You should only have one token server your API trusts, and let it do the brokering out to other token servers: http://docs.identityserver.io/en/latest/topics/federation_gateway.html

**Comment by rodan01** [comment]
> > A multitenant Webapi accepts tokens from multiple authorities. It configures multiple JwtBearer schemes. It calls HttpContext.AuthenticateAsync() for every scheme in each request, using a policy or manually.
> 
> This is a bad design to begin with. You should only have one token server your API trusts, and let it do the brokering out to other token servers: http://docs.identityserver.io/en/latest/topics/federation_gateway.html

Multiple schemes is a supported scenario described in the [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x#use-multiple-authentication-schemes), however It is broken as described above.

Thanks for the suggestion.

**Comment by blowdart** [comment]
There's nothing asp.net can do here, the behaviour is done by, as you have pointed out, https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet and the asp.net side is already configurable

Please create an issue there in the AzureAD repo.

**Comment by Tratcher** [comment]
Mitigation: Disable RefreshOnIssuerKeyNotFound. Keys don't actually change very often.

**Comment by rodan01** [comment]
> There's nothing asp.net can do here, the behaviour is done by, as you have pointed out, https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet and the asp.net side is already configurable
> 
> Please create an issue there in the AzureAD repo.

I don't have the luxury of sending my customers to complain with the author of the library I decided to use. I have to fix it or do it in another way. So, here is the issue:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1168

**Comment by brentschmaltz** [comment]
@rodan01 I commented on AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1168. It is worth noting that SecurityTokenSignatureKeyNotFoundException derives from SecurityTokenInvalidSignatureException

@Tratcher which exception are we catching to trigger the metadata refresh?

**Comment by Tratcher** [comment]
SecurityTokenSignatureKeyNotFoundException

**Comment by brentschmaltz** [comment]
@Tratcher that's what I thought.

**Comment by brentschmaltz** [comment]
@rodan01 after talking to @Tratcher I see what you are saying.  Reading the token then examining a Metadata cache of trusted issuers could solve this problem. Are you working with multitenant across identity providers { google, msft, FB, …} OR  Azure tenants OR ALL of the above.

**Comment by Tratcher** [comment]
Closing this as this is being tracked in identity model.
