### ISSUE TITLE
Intelisense doesn`t work currently for Blazor component .razor files in VS2019 latest preview version 

### ISSUE THREAD

**Issue by olkuziv** [aspnet/AspNetCore#10161]
### Expected behavior
Intelisense helps with namespace including
1. Create .razor file
2. Add some logic and view
3. All working as with cshtml file

### Screenshots
Current
![image](https://user-images.githubusercontent.com/33831834/57547880-32f1a100-7368-11e9-96bf-5a1c844585b0.png)
Expected result:
![image](https://user-images.githubusercontent.com/33831834/57547914-50bf0600-7368-11e9-8af5-445ac9d1aa5b.png)

**Comment by olkuziv** [comment]
![image](https://user-images.githubusercontent.com/33831834/57554301-bebff900-7379-11e9-95ac-2e8a7d493c5c.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @olkuziv. Please make sure you're using latest .Net Core 3.0 Preview 5 with VS 2019 Preview (16.1 Preview 3) and Blazor VS extension installed. Also, please follow the migration guide https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/
