### ISSUE TITLE
BLAZOR - Float Right style breaks onClick event on button

### ISSUE THREAD

**Issue by GuiguiMtl** [aspnet/AspNetCore#10162]
On a button with a float:right property the method defined on the OnClick event is never called.
Remove the float: right and it works as expected.

` <button style="float: right" class="btn btn-secondary delete-item" onclick="@OnRemoved">X</button>`

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by karthickthangasamy** [comment]
@GuiguiMtl : It's working with `VS 2019 16.2.0 Preview 1.0` and `Blazor 3.0.0 Preview5`. May be element is hidden or not displayed as block element.

Try with `style=display:block`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
