### ISSUE TITLE
Move IServerVariables feature and friends to Http.Abstractions

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10167]
The IIS server adds an HTTP feature `IServerVariablesFeature`. Server Variables are not an IIS-exclusive concept and date all the way back to CGI so it seems reasonable that a server may want to provide them. We should move this type out of Servers.IIS and in to HttpAbstractions.

Specific changes:
* Move [`IServerVariablesFeature`](https://github.com/aspnet/AspNetCore/blob/master/src/Servers/IIS/IIS/src/IServerVariableFeature.cs) to [Http.Features](https://github.com/aspnet/AspNetCore/tree/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Http/Http.Features/src)
* Add `GetServerVariables` extension method in [Http.Features](https://github.com/aspnet/AspNetCore/tree/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Http/Http.Features/src).
* Change [`GetIISServerVariables`](https://github.com/aspnet/AspNetCore/blob/master/src/Servers/IIS/IIS/src/HttpContextExtensions.cs) extension method to just call `GetServerVariables` (and mark as `[Obsolete]`?)
* Update all [reference assemblies](https://github.com/aspnet/AspNetCore/blob/master/docs/ReferenceAssemblies.md)
* Add [`TypeForwardedToAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.typeforwardedtoattribute?view=netcore-3.0) to [`Servers.IIS`'s `AssemblyInfo.cs`](https://github.com/aspnet/AspNetCore/blob/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Servers/IIS/IIS/src/AssemblyInfo.cs) pointing at the new type.

**Comment by davidfowl** [comment]
Maybe type forwarding is pointless since it won’t be compatible anyways

**Comment by Tratcher** [comment]
Type forwarding IServerVariablesFeature would be compatible, no? Unless you change the namespace.

GetIISServerVariables can stay for compat, GetServerVariables would be a new extension method. Note GetServerVariables does not go in Http.Features, it would go into Http.Extensions.

**Comment by davidfowl** [comment]
Ah it’s an extension method, I didn’t look at the interface

**Comment by mderriey** [comment]
Cool, thanks for the clear instructions. I'll wait until #10022 is merged to take a stab at it.

**Comment by anurse** [comment]
Updated instructions

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] Verified against ASP.NET Core App Version 3.0.0-preview7.19351.2
