### ISSUE TITLE
Blazor: Import DLLs with components - UI as a Service

### ISSUE THREAD

**Issue by 3x0dv5** [aspnet/AspNetCore#10177]
### Import DLLs with components - UI as a Service
It would be good if we could have a functionality to allow import a DLL from the .razor page so we could actually implement UI as a service.
Something like:
```html
<link src="https://ui-resources.my-company-azure.net/1.0.*/text/smart-textbox.dll" asp-type="blazor-lib"/>
```

This would allow a UI team to implement and maintain a set of components. In case a bug is found in version 1.0.1, the UI core team only fixes the bug and deploys version 1.0.2.
The feature team does not need to recompile their application and go over the release/deployment process. Blazor would download the latest version and load it.

This is something that today can be achieved with Web components, but would be nice to have this in Blazor.

This feature might be very similar to allow the use of CDNs to load the assemblies at https://github.com/aspnet/AspNetCore/issues/9624

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @3x0dv5.
This is not something we plan to add to the framework. This is definitely something you can build on top of the framework.

**Comment by 3x0dv5** [comment]
Hi,
Isn't the framework only loading DLLs from the _framework folder? Is there a way to load DLLs from other sources that not the server from where the App is being sourced?
I mean, from the client side, can I download a DLL from a different server and load it into my application, any example?
