### ISSUE TITLE
Blazor - Client-side application failed to start

### ISSUE THREAD

**Issue by alexandermujirishvili** [aspnet/AspNetCore#10175]
I have created client-size blazor application from template and for some reason application fails to start.

![BlazorProblem](https://user-images.githubusercontent.com/46314872/57569397-92ea5500-7405-11e9-86c8-2ac9a1afa373.png)

I have installed latest blazor extension:

![blazorExtension](https://user-images.githubusercontent.com/46314872/57569406-ab5a6f80-7405-11e9-8627-a4825c555ffe.png)

this is link of the project: https://github.com/alexandermujirishvili/BlazorTest

**Comment by 3x0dv5** [comment]
I cloned your repo, and it works for me.
![image](https://user-images.githubusercontent.com/250271/57571473-bfeb3780-7406-11e9-891d-5cc793954a8a.png)

![image](https://user-images.githubusercontent.com/250271/57571491-e27d5080-7406-11e9-92c8-d503fe3c4de4.png)

**Comment by alexandermujirishvili** [comment]
I Rebuilded project and the following error was shown:

![image](https://user-images.githubusercontent.com/46314872/57571797-84129b00-7423-11e9-8d90-6b15c40601eb.png)

Then I have added this line in BlazorTest.csproj file:

`<PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2" />`

And now I have the following error:

![image](https://user-images.githubusercontent.com/46314872/57571829-e23f7e00-7423-11e9-8ea7-ba0a75a8387f.png)

Despite this, project  'Build succeeded', but application fails to start again..

**Comment by 3x0dv5** [comment]
did you install dotnet core 3 preview 5 sdk https://dotnet.microsoft.com/download/dotnet-core/3.0?

**Comment by alexandermujirishvili** [comment]
@3x0dv5 I reinstalled it and it solved my problem. Thank you.

**Comment by 3x0dv5** [comment]
Awesome!
