### ISSUE TITLE
HttpClient.PostAsync() send Get requests

### ISSUE THREAD

**Issue by olkuziv** [aspnet/AspNetCore#10176]
### Describe the bug
After adding [Authorize] attribute on Post method, aftert calling HttpClient.PostAsync() working like GetAsync(). 

### To Reproduce
1. Create default blazor app
2. Add Coockies auth
2. Add new Get endpoint
3. Add [Authorize] attribute for new Post endpoint
4. Call this Post endpoint
5. In debug could see that HttpClient send Get request

### Screenshots
![image](https://user-images.githubusercontent.com/33831834/57570366-aac3d800-7409-11e9-917c-ba6c4c7819aa.png)

![image](https://user-images.githubusercontent.com/33831834/57570341-63d5e280-7409-11e9-99ae-43034ef6ba75.png)

**Comment by olkuziv** [comment]
After adding handler
![image](https://user-images.githubusercontent.com/33831834/57570549-fb3c3500-740b-11e9-870d-f33717e62a32.png)
PostAsync returns "Found 302" status code, but endpoid still not working.

**Comment by DAllanCarr** [comment]
There is certainly some weirdness here. What are you expecting to be returned from the endpoint? 

Regards to the response with the auth challenge, that's normal. 
You may need to consider how you initiate the auth flow with respect to  the blazor client. There will developments in this area so you may need future best practices in this area.

https://github.com/aspnet/AspNetCore/issues/4048

**Comment by enetstudio** [comment]
@olkuziv, HttpClient is automatically added to your application as a Singleton service. The HttpClient is based on the WebAssemblyHttpMessageHandler. Why do you add HttpClient as a scoped service, and based on HttpClientHandler ? I'm not suggesting that it is related to your issue...just wondering why you coded that way ?

**Comment by enetstudio** [comment]
@olkuziv, perhaps this link can solve your problem:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler?view=netcore-3.0#httpclienthandler-in-net-core

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @olkuziv.
You're most probably being auto-redirected by the server to the authentication endpoint, which is the expected behavior when using the `CookieAuthentication`. So your HttpClient automatically sends a get request to the authentication endpoint, and that's what you're observing here. To successfully make the request, make sure that the user is authenticated and you pass the cookie as part of the first request.

**Comment by olkuziv** [comment]
> Thanks for contacting us, @olkuziv.
> You're most probably being auto-redirected by the server to the authentication endpoint, which is the expected behavior when using the `CookieAuthentication`. So your HttpClient automatically sends a get request to the authentication endpoint, and that's what you're observing here. To successfully make the request, make sure that the user is authenticated and you pass the cookie as part of the first request.

Yes, You are right. I should pass cookies in HttpClient headers
