### ISSUE TITLE
Blazor Client-side builds but can't run, .exe doesn't exist

### ISSUE THREAD

**Issue by psychotaker** [aspnet/AspNetCore#10178]
### When I try to run only Blazor client-side I got this error. When I go to path it indeed doesn't has WebApp1.exe but it has a WebApp1.dll. I have tried switching executable from .exe to .dll and it works partially, only log window says it's running and I can't access to http://localhost:5001 nor http://localhost:5000.

***Notice***
**Last night was running perfectly when I tested it, in the morning it does not.**

I have tried with making new project and problem persist, I have tried reinstalling dotnet, mono, nothing fixes it.

1. _Using this version of ASP.NET Core:_
 **Microsoft.NETCore.App 3.0.0-preview5-27626-15** 
2. _Using this OS:_ **Fedora 30**
2. _Using this IDE:_ **Jetbrains Rider**
3. _Debug configuration_
![debug conf](https://user-images.githubusercontent.com/22131674/57572138-b964bc00-7416-11e9-9d6d-2f2b8425f437.png)
4. _ERROR_
`Error running 'Default': File /home/teufik/Blazor/WebApp1/bin/Debug/netstandard2.0/WebApp1.exe doesn't exist`
![error](https://user-images.githubusercontent.com/22131674/57572085-4eb38080-7416-11e9-8f41-452f2b3de0eb.png)
**As you can see build is successful**

### Additional context
Including the output of `dotnet --info`
![dotnet --info](https://user-images.githubusercontent.com/22131674/57572217-8bcc4280-7417-11e9-9bcd-e6d4e33022a5.png)

**Comment by 3x0dv5** [comment]
Blazor CS doesn't create an exe. The WebApp1.dll will be downloaded to the browser and executed by the mono engine.
What happen if you go to the project directory and execute a `dotnet run`?

**Comment by 3x0dv5** [comment]
This might be a tooling issue. Jetbrains Rider doesn't seem to fully support Blazor client side, vote up here: https://youtrack.jetbrains.com/issue/RSRP-469186 . 
I've tried a project that works well on Visual Studio 2019 but it shows the error you mentioned when trying to run from Jetbrains Rider.
Just give it a try, `dotnet run`, you can always try Visual Studio Code (I've never used it for Blazor though) take a look at this: https://visualstudiomagazine.com/articles/2019/04/23/vs-code-blazor.aspx

**Comment by psychotaker** [comment]
> Blazor CS doesn't create an exe. The WebApp1.dll will be downloaded to the browser and executed by the mono engine.
> What happen if you go to the project's directory and execute a `dotnet run`?

When I run through dotnet run it work, I got ports listening on 5000 and 5001 and simply navigate to it on browser and it works.

I think it is Jetbrains Rider but I'm wondering how first time it managed to run

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @psychotaker.
We recommend follow up on the issue filed on the `jetbrains.com` shown above:
>  Jetbrains Rider doesn't seem to fully support Blazor client side, vote up here: https://youtrack.jetbrains.com/issue/RSRP-469186 .
