### ISSUE TITLE
Razor Runtime Compile Error when Changed

### ISSUE THREAD

**Issue by WilsonDotNet** [aspnet/AspNetCore#10184]
ASP.NET CORE v3.0 Preview 5

Create New ASP.NET CORE Razor project 
Add package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
Update ConfigureServices method in Startup.cs:
services.AddRazorPages().AddRazorRuntimeCompilation();
Add `<PreserveCompilationReferences>true</PreserveCompilationReferences>` to Project file
Build and Deploy to IIS
All works at first but make a change to Index.cshtml file and it does NOT work.

500 error displayed: InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery

**Comment by pranavkm** [comment]
> Build and Deploy to IIS

Are you also deploying your cshtml files? Publishing should not include these files by default. If I try this locally, without having to publish the app, things work fine with preview5 bits.

**Comment by WilsonDotNet** [comment]
Yes, my cshtml files are deployed. There would be nothing to try to change
if they were not deployed!

I am glad that there is a way to not have to deploy cshtml files, but it
should also not be so difficult to be able to edit them in place as they
are essentially "content" files to many of us!

Thanks, Paul Wilson

**Comment by pranavkm** [comment]
@WilsonDotNet I can't reproduce the error you're running in to using preview5 bits. Do you have an application that you can share so that I can investigate this further?

**Comment by pranavkm** [comment]
Feel free to reopen once you've an application to share with us.
