### ISSUE TITLE
[Blazor] _content is generated in /dist regardless of the value of BaseBlazorDistPath

### ISSUE THREAD

**Issue by honkmother** [aspnet/AspNetCore#10183]
### Describe the bug
In the project settings,  the **_content** folder will be generated inside of /dist, regardless of the value  in ```BaseBlazorDistPath```. Additionally, **BaseBlazorPackageContentOutputPath** is ignored completely and I cannot change the output folder name of **_content**.

### To Reproduce
Blazor p4 & Visual Studio 16.1.0 Preview 2

Toss ```<BaseBlazorDistPath>HONK/</BaseBlazorDistPath>``` into the project settings.

### Expected behavior
**_content** should be generated inside of **/HONK/_content/** and if I change the ```BaseBlazorPackageContentOutputPath```, it should set the according content output folder.

🐊

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @honkmother.
This is not a supported scenario. Can you tell us why do you want to change the `BaseBlazorDistPath`?

**Comment by honkmother** [comment]
A lot of systems (most notably Android) will choke if you have an underscore as the prefix for a folder name.

**Comment by danroth27** [comment]
@honkmother Are you then trying to embed Blazor into a native Android app somehow? Would it be sufficient if we changed the default paths to not use leading underscores?

**Comment by honkmother** [comment]
@danroth27 Right on the money. I have Blazor running inside of PhoneGap on Android and iOS, but the underscores are throwing it off for Android unless I manually edit the paths post-build. 

Yes, removing the leading underscores would fix it.

**Comment by danroth27** [comment]
> I am targeting all three platforms (web, mobile+pwa, and crossplatform+native) with one source tree.

Nice! 👍 

@SteveSandersonMS @mkArtakMSFT I think we should do something to address this. Can we simply remove the leading underscores?

**Comment by javiercn** [comment]
@danroth27 Maybe we could do this as part of the static assets support we are building?

**Comment by SteveSandersonMS** [comment]
@javiercn If you think it's straightforwards to make `_framework`/`_content` configurable, that's something we'd want at least eventually. It would need to work in all cases, including publishing standalone apps, so I'm guessing there's quite a lot of code paths to go through.

I'm not convinced we should just drop the leading underscores by default, as it's far more likely to clash with the developer's own files if it was just `framework` and `content` by default.

**Comment by javiercn** [comment]
@SteveSandersonMS I think it won't be very problematic. It might need some minimal MSBuild tweaks, but that's it. We can try and tackle this as part of preview7/8 once we have the static asset work in place.

I'm gonna park this for now, until I can give what I have in mind a try.

**Comment by danroth27** [comment]
Closing this as a duplicated of https://github.com/aspnet/AspNetCore/issues/5582
