### ISSUE TITLE
Crash: Comment Block Shortcut crashes VS2019 16.1.0 Preview 3

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore#10182]
This is repeatable. When I upgraded to Preview 5 my VS crashes every time use Ctrl+e, c to comment out a block of code. VS will reboot and attempt to recover the page. If I do it again, VS shuts down. 

This is occurring in a Blazor ASPCore server hosted *.razor page. 

Note, this is repeatable. It didn't have this issue with Preview 2. Also note I have the latest preview versions of the Blazor VSIX and .NET Core 3.0 preview. So not sure which software is causing this.

**Comment by VR-Architect** [comment]
Sorry, I just realized I posted this to the wrong forum group. Can anyone in MS forward this to the VS Team? or give me the forum for it?

**Comment by davidfowl** [comment]
You can report changes in vs using the "Send Feedback" button:

![image](https://user-images.githubusercontent.com/95136/57574799-8f020700-73f4-11e9-8ce2-f49625b5bb92.png)

You can even record a video (and it'll collect traces and a dump to aid in diagnosis).

**Comment by rynowak** [comment]
@ajaybhargavb

**Comment by ajaybhargavb** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/9723. This is a bug in VS Editor

**Comment by rynowak** [comment]
@ajaybhargavb @NTaylorMullen - what's the timeline for fixing this? Is there an internal bug tracking it?

**Comment by NTaylorMullen** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/866654 is the tracking bug. I've been poking over email.
