### ISSUE TITLE
.NET Core 2.1 cannot detect many nuget packages anymore after the latest windows 10 update

### ISSUE THREAD

**Issue by precogtyrant** [aspnet/AspNetCore#10187]
### Describe the bug
After the latest windows 10 automatic update from a few days ago (Version 1083 ( OS Build 17134.706)), my perfectly working asp.net core 2.1 application started throwing errors. It doesn't detect packages like Pomelo Entity Framework Core, Ncrontab etc. After upgrading to .Net Core 2.2 and choosing the framework as .net core 2.2 in the build, the problems went away but still thought I would let you know. 

### To Reproduce
Try using Pomelo entity framework core or ncrontab in the windows version  (Version 1083 ( OS Build 17134.706)) with .net core 2.1 selected.

**Comment by davidfowl** [comment]
Runtime errors? Do you have the exception message?

**Comment by precogtyrant** [comment]
hi @davidfowl,
Actually it doesn't detect the packages as installed(not sure what this phenomenon is called ;) ). Visual studio doesn't detect `using`s for those extensions and gives red squigglies. 

Here's an example of an error I get when i do `dotnet run`
`Startup.cs(78,29): error CS1061: 'DbContextOptionsBuilder' does not contain a definition for 'UseMySql' and no accessible extension method 'UseMySql' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)`

This error is related to https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.2.0 
Also, it doesn't detect Ncrontab (https://www.nuget.org/packages/ncrontab/) either. So maybe some stuff that those packages are not supported with the latest windows update? Visual studio is not showing any squigglies for some other packages though like Bouncy Castle, Newtonsoft Json etc.

**Comment by davidfowl** [comment]
Sounds unrelated to windows. That’s a build error, not a runtime one. Are there errors in the error window in visual studio? When you run restore do you see error or failures?

**Comment by precogtyrant** [comment]
@davidfowl nope, no errors on restore. Since I couldn't even build it, no runtime errors either. Here is a sample project I just created, installing just the Pomelo package which was working fine before the Windows update. Now Visual studio doesn't recognize it.(works ok, if i use netcore2.2 and update the package)
[WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3170306/WebApplication1.zip)

**Comment by Pilchie** [comment]
@jjmew @davkean - this seems like a project system or Roslyn issue.  Can you take a look?

**Comment by jjmew** [comment]
> @jjmew @davkean - this seems like a project system or Roslyn issue. Can you take a look?

I am following up with my team

**Comment by davkean** [comment]
This is not a project-system or Roslyn issue; there's no `UseMySql` extension method anywhere in scope for the above project. The closest one I found was in the `MySql.Data.EntityFrameworkCore` package under `Microsoft.EntityFrameworkCore.MySQLDbContextOptionsExtensions.UseMySQL` (notice the casing is different) which is not anywhere in the package graph. 

I'll leave it to the EF folks/ASP.NET/Pomelo.EntityFrameworkCore.MySql folks to answer what the difference is between your existing project and the one above.

**Comment by Pilchie** [comment]
@ajcvickers - is this part of the removal of EFCore from the shared framework?

**Comment by ajcvickers** [comment]
@Pilchie I don't think so, but I will take a look at the repro tomorrow to see if I can see what is going on.

**Comment by ajcvickers** [comment]
@precogtyrant The package `Microsoft.EntityFrameworkCore.Tools.DotNet` is obsolete and should be removed. In general you need to be using a consistent set of EF packages, so if there is a 2.0 EF package being used in a 2.1 application, then this is usually an error.

**Comment by precogtyrant** [comment]
Just a quick update here - 
The issue resurfaced with netcoreapp2.2 as well. Someone suggested clearing the nuget cache and after doing that and running `dotnet restore` it started working again. 
Sorry for the trouble, however, this issue is something that a lot of people seem to be facing.
