### ISSUE TITLE
Blazor Anchor tag execute href and onClick together, is this correct?

### ISSUE THREAD

**Issue by medeirosraul** [aspnet/AspNetCore#10194]
### The bug
When I have an anchor tag with an onclick event in my .razor page, after click the anchor, the page redirects and then execute onclick.

### To Reproduce
With ASP.NET Core Preview 5 Blazor Server-Side, have a anchor tag like this:

`<a href="#" class="btn btn-primary" onclick="@TheEvent">Do it</a>`

When I click on anchor, the page redirects to "/" path (initial page) and then execute `TheEvent` method.

### Expected behavior
I've expected the anchor execute only `onclick` event and ignores `href="#"`. This implies if I have a "NavigateTo" call in my event method, because page goes to "/" path and then navigate to seted url.

Is this current behavior correct?

**Comment by enetstudio** [comment]
Read these: 
https://github.com/aspnet/Blazor/issues/715
https://github.com/aspnet/AspNetCore/issues/5545

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @medeirosraul.
As was mentioned by @enetstudio, Event Propagation is indeed something which can help you in this situation.

**Comment by ichensky** [comment]
To prevent executing href you can use `a` like this.
```html
<a href="javascript: void(0)" class="btn btn-primary" onclick="@TheEvent">Do it</a>
```

**Comment by enetstudio** [comment]
@ichensky, is "javascript: void(0)" JavaScript thing or Blazor ? 
This is a very bad solution.

**Comment by ichensky** [comment]
This is js thing. While functionality for event management from aspnet/Blazor#715 #5545 still not implemented, this fix can be used as temporary solution for now. I do not know yet other options as it is now possible prevent `href` execution in `a` attribute.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
