### ISSUE TITLE
.net 3 preview 5 Cannot run on VS Code

### ISSUE THREAD

**Issue by mammadkoma** [aspnet/AspNetCore#10196]
Blazor and other template (MVC & WebApp) in .net 3 preview 5 not work and start (F5) with microsoft VS Code!
We want to create launcher and start (F5) like flutter framework.

![image](https://user-images.githubusercontent.com/17564001/57587375-4b54ed80-7519-11e9-9710-d85182adc19c.png)

![image](https://user-images.githubusercontent.com/17564001/57587378-514ace80-7519-11e9-97b1-9a0ed84d9055.png)

![image](https://user-images.githubusercontent.com/17564001/57587379-56a81900-7519-11e9-9a7b-90066daf83a1.png)

Boom and Start with F5.

**Comment by Eilon** [comment]
Hi @mammadkoma , can you please provide more info on what isn't working? Can you share your project and steps to reproduce the problem? At this time there is not enough information for us to investigate.

**Comment by mammadkoma** [comment]
do you create a blazor project with "dotnet new blazor" and open it by vscode?

![image](https://user-images.githubusercontent.com/17564001/57642649-1dc97c00-75cd-11e9-9783-431b13ed6c2b.png)

The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) (CS0246) [Blazor]

**Comment by NTaylorMullen** [comment]
@mammadkoma could you see if this resolves your issue https://github.com/aspnet/Razor.VSCode/issues/365#issuecomment-491461408 ? I believeboth this and that issue are the same but want to make sure 😄

**Comment by mammadkoma** [comment]
If dotnet core is open source it must open and launch with a open source ide like vs code. 
Flutter framework works fine with vs code like top images.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mammadkoma. We're closing this issue in favor of tracking the work in the issue referenced above.
