### ISSUE TITLE
NewtonSoft not included in preview5 blazor project

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#10197]
### Describe the bug

I am update the blazor samples from .NET Core SDK preview4 to preview5. All are working fine. But when i running the samples in browser, it throws the following error. "FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.".
How to resolve this.

### Screenshots
![image](https://user-images.githubusercontent.com/31958591/57601415-0f05a980-757a-11e9-9f8d-ec1ad994f6b3.png)

### Additional context
This is my .csproj file config.
![image](https://user-images.githubusercontent.com/31958591/57601465-2cd30e80-757a-11e9-9a45-a2761693ac29.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kmuthukumar23.
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
