### ISSUE TITLE
Question:IServerAddressesFeature  behaviour different in whole lifetime

### ISSUE THREAD

**Issue by zirain** [aspnet/AspNetCore#10199]
Hi, I'm running aspnetcore with consul got something confused.
see the code via:[ConsulAppBuilderExtensions](https://github.com/zirain/AspNetCore-Playground/blob/master/src/ConsulTraefikDemo/ConsulTestApi/ConsulAppBuilderExtensions.cs)
I got an address with something like `http://*:57308/`
then see the code via:[ConsulHostedService](https://github.com/zirain/AspNetCore-Playground/blob/master/src/ConsulTraefikDemo/ConsulTestApi/ConsulHostedService.cs)
I got another address with something like `http://localhost:57308/` or `http://[::]:57308/`
what make this change?

**Comment by Tratcher** [comment]
The first example is from before the server started, and the second is from after. When the server starts it resolves some wildcards and updates IServerAddressesFeature to more specific values.

Check out this example where the middleware delays reading the values until after server start:
https://github.com/aspnet/AspNetCore/blob/c95ee2b051814b787b07f55ff224d03d550aafeb/src/Middleware/HttpsPolicy/src/HttpsRedirectionBuilderExtensions.cs#L31
https://github.com/aspnet/AspNetCore/blob/c95ee2b051814b787b07f55ff224d03d550aafeb/src/Middleware/HttpsPolicy/src/HttpsRedirectionMiddleware.cs#L139

**Comment by zirain** [comment]
Hi @Tratcher , so this is by design?

In my opinion, this first example is more meaningful, I do not want register to a consul service in some IHostedService which looks like more than a workaround. How can I make it work right now? Is there any extension function can be run after the server started?

**Comment by Tratcher** [comment]
You're trying to send those addresses to an external component? Have you tried IApplicationLifetime.ApplicationStarted? You're already using ApplicationStopping.

**Comment by zirain** [comment]
@Tratcher yes, I'm trying to register those addresses to Consul/zookeeper/eureka

Can I get the address like `http://localhost:57308/` or `http://[::]:57308/` in IApplicationLifetime.ApplicationStarted?

**Comment by Tratcher** [comment]
Yes, if you hold onto the IServerAdressesFeature it should get updated.

**Comment by zirain** [comment]
@Tratcher I will try you suggestion and update result later, thanks for your reply

**Comment by zirain** [comment]
@Tratcher It's works. 
BTW, ` When the server starts it resolves some wildcards and updates IServerAddressesFeature to more specific values.` so where is the resolves code?

**Comment by Tratcher** [comment]
Deep in the server. Here's part of it:
https://github.com/aspnet/AspNetCore/blob/68cc5e7846240bacc146854dfc6a175e30ff0f60/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs#L135-L151

**Comment by zirain** [comment]
@Tratcher thanks!
