### ISSUE TITLE
Build errors when create Razor View in BlazorLib

### ISSUE THREAD

**Issue by ericgrantholland** [aspnet/AspNetCore#10205]
1. Create a new Blazor App
2. Right-click the solution in Solution Explorer, click open folder in file explorer. 
3. In file explorer, clear the path info in the top bar and type "cmd" to open a command prompt in the solution folder(alternatively, open a command prompt and navigate to the solution folder). 
4. Run the following command "dotnet new blazorlib -o MyComponentLib1"
5. Go back to visual studio, right click the solution and select "Add -> Existing Project", then find the MyComponentLib1 project in your solution folder. 
6. Add a reference to MyComponentLib1 in the newly created blazor app. 
7. Create a new razor view in the MyComponentLib1 library. 

At this point, I'm seeing 15 errors saying "The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)

I'm using VS 2019 and the following blazor templates:
Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01

**Comment by Lupusa87** [comment]
You need latest VS 2019 preview.

**Comment by pranavkm** [comment]
@ericgrantholland as @Lupusa87 pointed out, you'll need to install the latest preview build of VS. It's available to download from - https://visualstudio.microsoft.com/vs/preview. See https://github.com/aspnet/AspNetCore/issues/9851 for a previous discussion on this.
