### ISSUE TITLE
Blazor, AMP compatability

### ISSUE THREAD

**Issue by AidanSpeakss** [aspnet/AspNetCore#10203]
AMP just came out with a huge new feature; they are allowing 150kb of custom javascript. But the Blazor javascript code is more than 150kb. I would like for blazor to be AMP compatible because, with AMP and Blazor working side by side, websites could be incredibly fast, responsive, and use minimal resources! 

AMP disallows very specific parts of the code that slows down the browser, and it does a lot of this by preventing pages from painting new elements after it's loaded, if the browser has to for example: modify the style sheet, then it has to repaint the page again, slowing things down a ton. AMP already has figured out what slows down the browser the most and gave us guidelines to keep things running smooth. And now, with Blazor, we would never have to reload the page at all, thanks to its powerful single page applications. Please, make this AMP compatible!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AidanSpeakss.
This is not a goal for us at the moment. In the future we may look into reducing our JavaScript footprint.
