### ISSUE TITLE
Cannot create "Code Behind" components in VS 2019

### ISSUE THREAD

**Issue by rabejens** [aspnet/AspNetCore#10201]
### Describe the bug
Code (`.g.cs`) is generated from `.razor` file despite `.razor.cs` exists

### To Reproduce
1. Use VS Community 2019, Version 16.1.0 Preview 3
2. Use Blazor Extension 16.0.19227.1
3. Use the .net Core SDK 3.0.100-preview5-011568
4. Install the newest Blazor: `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01`
5. Create a new Hosted Blazor project
6. Create `Components` folder in the client project
7. Add a file `Foo.razor` in the components folder with these contents:
  ```html
<h1>@foo</h1>
  ```
8. Add a file `Foo.razor.cs` along the `Foo.razor` containing, in the correct namespace,:
  ```csharp
    public class Foo: ComponentBase {

        public string foo = "Foo";
    }
  ```
8. Try to compile the project
9. See:
  ```
Error	CS0101	The namespace 'CodeBehindBug.Client.Components' already contains a definition for 'Foo'
  ```

### Expected behavior
Visual Studio should discover the `.razor.cs` file and stop autogenerating the class twice

### Screenshots
![image](https://user-images.githubusercontent.com/8402886/57618464-c4892a80-7583-11e9-9a57-47a272398592.png)
![image](https://user-images.githubusercontent.com/8402886/57618479-ce129280-7583-11e9-9886-c747c9b31a54.png)

### Additional context
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rabejens.
You can do this today using [inheritance](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#base-class-inheritance-for-a-code-behind-experience). In the meantime we're working on enabling support for [partial classes](https://github.com/aspnet/AspNetCore/issues/5487) which will make this even simpler.
