### ISSUE TITLE
Add manifest to ASP.NET targeting pack

### ISSUE THREAD

**Issue by dsplaisted** [aspnet/AspNetCore#10215]
The targeting pack for ASP.NET Core should have a manifest listing all of the reference assemblies along with their assembly and file versions.  This should be in the `data\FrameworkList.xml` file, and the format should be like this:

```xml
<FileList Name=".NET Core 3.0" TargetFrameworkIdentifier=".NETCore" TargetFrameworkVersion="3.0" FrameworkName="Microsoft.NETCore.App">
  <File AssemblyName="Microsoft.CSharp" PublicKeyToken="..." AssemblyVersion="..." FileVersion="..." />
  <File AssemblyName="Microsoft.VisualBasic" PublicKeyToken="..." AssemblyVersion="..." FileVersion="..." />
  <File AssemblyName="System" PublicKeyToken="..." AssemblyVersion="..." FileVersion="..." />
  <!-- etc. -->
</FileList>
```

Related issue for the other targeting packs: https://github.com/dotnet/core-setup/issues/5074

@natemcmaster @pranavkm

**Comment by natemcmaster** [comment]
I'm assuming this is copy-pasted from core-setup, but the values need to change to something like this, right?
```diff
- <FileList Name=".NET Core 3.0" TargetFrameworkIdentifier=".NETCore" TargetFrameworkVersion="3.0" FrameworkName="Microsoft.NETCore.App">
+ <FileList Name="ASP.NET Core 3.0" TargetFrameworkIdentifier=".NETCore" TargetFrameworkVersion="3.0" FrameworkName="Microsoft.AspNetCore.App">
```

**Comment by nguerrera** [comment]
I think so

Also,
``` diff
-TargetFrameworkIdentifier=".NETCore"
+-TargetFrameworkIdentifier=".NETCoreApp"
```

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] Verified by partner team
