### ISSUE TITLE
Add file manifest to ASP.NET runtime packs

### ISSUE THREAD

**Issue by dsplaisted** [aspnet/AspNetCore#10216]
The runtime packs should have a manifest listing the assets, what type the assets are (managed or native), and the file and assembly versions.

Suggested format is in the following issue: https://github.com/dotnet/core-setup/issues/6409

@natemcmaster @pranavkm

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] Verified by partner team
