### ISSUE TITLE
Should OAuth handlers dispose of HttpRequestMessage/HttpResponseMessage?

### ISSUE THREAD

**Issue by martincostello** [aspnet/AspNetCore#10229]
While reviewing https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/268, I looked at the [`GoogleHandler`](https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Google/src/GoogleHandler.cs) class to see if the built-in OAuth handlers do the same as a hint as to whether the disposal is really required or not, which it does not.

This raises the question, _should_ the built-in OAuth handlers be disposing of the `HttpRequestMessage`/`HttpResponseMessage` instances they create, or are they a special case for IDisposable like `HttpClient` and `Task`/`Task<T>` where warnings from static analyzers are false positives?

**Comment by blowdart** [comment]
@Tratcher 

I find it not concerning, because they're going to get GCed anyway, and there's no unmanaged resources behind them that need clearing up sooner rather than later, but Chris may have other opinions.

**Comment by Tratcher** [comment]
There's a long thread on this here: https://github.com/dotnet/corefx/issues/34983

Summary: No. Disposing the HttpRequest/ResponseMessage only calls Dispose on the HttpContent. The HttpContent only needs to be disposed in the streaming scenario. In the buffered / string scenario (default), the underling resources are already cleaned up before HttpClient.SendAsync even returns.

**Comment by Tratcher** [comment]
That said, I wouldn't object to the use of C#8's new `using` dispose keyword:
`using var response = await Backchannel.SendAsync(request, Context.RequestAborted);`

**Comment by martincostello** [comment]
@blowdart @Tratcher Thanks both - I'll feed that back to the original PR.
