### ISSUE TITLE
Use default interfaces for breaking change in IAuthorizationPolicyProvider

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#10222]
Last part of https://github.com/aspnet/AspNetCore/pull/9759

**Comment by anurse** [comment]
Do the DIM.

**Comment by HaoK** [comment]
uh oh netstandard 2.0 doesn't support default interface implementation :(

```
IAuthorizationPolicyProvider.cs(30,35): error CS8701: Target runtime doesn't support default interface implementation. 
```

cc @rynowak

**Comment by anurse** [comment]
Why is this `netstandard2.0`? Blazor? (cc @davidfowl)

We may need to just take the break then (cc @Pilchie @natemcmaster).

**Comment by anurse** [comment]
I thought this came up in our API review but I think it actually just came up in normal security triage. Anyway, I believe the API break has been made, this was an issue to allow us to "unbreak" it using DIM (I may be wrong though).

**Comment by HaoK** [comment]
Yeah, we took the break thinking we could 'unbreak' it later with DIM, in the meantime (or in parallel) we decided to 're'target netstandard2.0 with this package (that's what it used to target, but we temporarily had it target netcoreapp3.0 when we smushed the Authorization.Policy into Core, which we recently backed out for Blazor to be able to consume the Core AuthZ package.)

**Comment by rynowak** [comment]
We don't have to break this. A clean way to make this change would be to introduce an abstract base class that implements the interface, and have the places in code that use this do the downcast.

**Comment by HaoK** [comment]
Moving to preview 8 since having issues with dim still

**Comment by anurse** [comment]
Contingency plan: If we don't get DIM working and in, announce this as a breaking change. We could un-break in 3.1 in theory.

**Comment by anurse** [comment]
We're going to punt on DIM changes due to the limitations (VB support, crossgen issues). Let's doc this breaking change (@HaoK)

**Comment by HaoK** [comment]
https://github.com/aspnet/Announcements/issues/375

**Comment by rynowak** [comment]
If we're going to make a breaking change should we make this an abstract class so we don't relive this again in the next release?

**Comment by HaoK** [comment]
I think the plan is that DIM should be working in 3.1 and beyond (at least that's our hope)
