### ISSUE TITLE
Blazor demo project only shows "Loading..." page on some browsers

### ISSUE THREAD

**Issue by Gogglehead** [aspnet/AspNetCore#10223]
### Describe the bug
I've tried the Blazor demo project for an evaluation in my company and only see the "Loading..." page on Microsoft Edge and IE11, but everything works fine on all other browsers.

### To Reproduce

1. Use higher security settings on used browsers.
2. Install according to this guide: https://docs.microsoft.com/de-de/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio
3. Run from Visual Studio in Edge or IE11 --> stuck on "Loading..." screen
4. Run in every other Browser --> works fine

### Expected behavior
Same behavior in every browser

### Additional context
This issue is only on my company device with higher security settings in every browser. If the same template runs on my private machine, everything works fine.

But if Blazor is (randomly?) blocked by some browsers with higher security settings, it is not acceptable even for a test application, because I don't know if it works for some users and for some users not.

Unfortunately I don't have permissions on my company device to see the exact security settings, but, are there any know issues which settings might affect Blazor?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Gogglehead.
Your repro steps aren't clean enough. Can you provide the full list of granular policies you've set for those two browsers?

In the meantime, we're going to create a docs article or a wiki page as part of https://github.com/aspnet/AspNetCore/issues/10237 to create a Browser support matrix.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
