### ISSUE TITLE
Adding Properties and Events in Layout @Body

### ISSUE THREAD

**Issue by tsmccartan** [aspnet/AspNetCore#10230]
In the default Blazor App, is it possible to hide/show Menu Items in the NavMenu.razor (<div>) from a Button Click in the Index.razor file?

I don't know how to control the razor file that is loaded into the @Body area by default?  I believe it has to do with the @Route "/".  I have data being loaded there with a selection list of items.  And based on what the user chooses, I want to show/hide navigation items in the NavMenu. 

Is this possible?
How do you determine the default razor page that is loaded in the @Body area of the layout?
If I add a component in the Layout <Component /> you can add Parameters, etc.  <Components "@MyParam"> /> but I don't know if this is possible with the default index.razor that is being loaded by default in the @Body?

Thanks,
Tom

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tsmccartan.
You can achieve this using either a service registered in DI and passed to different pages, or using  `CascadingParameter`-s.
Also we're trying to address and simplify this as part of the work we're tracking at https://github.com/aspnet/aspnetcore/issues/10131
