### ISSUE TITLE
Identity Core with SQLite on Lockout: InvalidCastException

### ISSUE THREAD

**Issue by mysteryx93** [aspnet/AspNetCore#10231]
Using .NET Core 2.2 Identity Framework with SQLite. Database created from scratch before testing. Login works, I enter 5 wrong passwords, and it goes on lockout. From there on, login throws

> InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTimeOffset'. 

This looks like a bug in the framework. Any way to work around it?

**Comment by blowdart** [comment]
@ajcvickers as you're working on better tests for SQLite

**Comment by ajcvickers** [comment]
@HaoK Moving this back to you, since this wasn't an issue with not testing against SQLite. Something else is going on.

**Comment by mysteryx93** [comment]
Note that in my project, I was running System.Data.Sqlite provider instead of the Microsoft one. Don't know if that changes something here.

**Comment by ajcvickers** [comment]
@mysteryx93 What EF Core provider are you using with that?

**Comment by mysteryx93** [comment]
Using the latest Entity Framework with System.Data.Sqlite on .NET Core 2.2

**Comment by ajcvickers** [comment]
@mysteryx93 Being a bit more specific, I'm not aware of an EF Core provider that works with the `System.Data.Sqlite` package. If you're trying to use the EF Core provider for SQLite that is shipped by Microsoft, then it needs to be used with `Microsoft.Data.Sqlite`. If you are using some other EF Core provider (one written to work with `System.Data.Sqlite`) then can you tell us which one?

**Comment by mysteryx93** [comment]
```
var connString = Configuration.GetConnectionString("Satrimono").Replace("~", _env.ContentRootPath);
var conn = new SQLiteConnection(connString);
services.AddDbContext<SatrimonoContext>(options => options.UseSqlite(conn));

```
This works with System.Data.Sqlite. If I want to use Microsoft.Data.Sqlite, then I replace UseSqlite(conn) with UseSqlite(connString)

**Comment by ajcvickers** [comment]
@mysteryx93 If it works, then that's accidental. It is not expected to work. You'll need to use the `Microsoft.Data.Sqlite` provider.
