### ISSUE TITLE
I have a problem with a signalr cluster

### ISSUE THREAD

**Issue by bluetianx** [aspnet/AspNetCore#10232]
### Describe the bug
I have a signalr cluster which has four nodes. I am going to replace redisDbIndex 1 (eg: ip:port?db=1) of cluster  with redisDbIndex 2 (eg: ip:port?db=2). I replace redisdbconnetString (ip:port?db=1 -> ip:port?db=2) and restart node one by one. Some nodes in cluster write data to db2,but other nodes in cluster write data to db1.I do not know why?  All nodes in cluster write data to db2, when I restart them after I closed all the nodes，The problem never reappeared.

### Additional context
The version of asp.net core is 2.1;
The OS is windows server 2016.

**Comment by anurse** [comment]
> Some nodes in cluster write data to db2,but other nodes in cluster write data to db1.

Is it the nodes you haven't yet restarted that are writing to db 1? SignalR does not reload configuration automatically so you have to complete the restart before it will start using the new database ID.

**Comment by bluetianx** [comment]
I change redisConnectStr of node and restared it one by one  today,The problem comes up again

**Comment by anurse** [comment]
Are you seeing nodes write to the old database **after** all of them have been restarted? If you're restarting *one by one* I would definitely expect some messages to be written to the old database, until those nodes restart.

**Comment by bluetianx** [comment]
> Are you seeing nodes write to the old database after all of them have been restarted?
yes,I see. 
PS: I run my app with IIS ,I restart my app by using a way that as shown in figure
![image](https://user-images.githubusercontent.com/29353661/57897043-357f5980-7886-11e9-8173-f330cd258977.png)

**Comment by anurse** [comment]
So there are absolutely no instances of the old server with the old configuration running? Can you provide more detail on how you are changing the config? If you are setting the database number, the new servers should be picking that up. If any requests are still being processed by the old processes you'll see this.

Does this only happen shortly after the restart? Do the servers eventually stop writing to DB 1? When you restart in IIS, the old site continues running for a period of time to allow it to finish processing requests that came in before the new process was started (to reduce downtime), so it is expected that for a few minutes after restart, some requests are still being processed by the previous process.

**Comment by bluetianx** [comment]
Sorry for not replying to you for a long time, because I am a little busy with work at this time.

> So there are absolutely no instances of the old server with the old configuration running?

Yes。

>Can you provide more detail on how you are changing the config? 

I modify the appsetting file of signalr app  directly。

> Does this only happen shortly after the restart? 

I will reproduce the problem,I'll tell you  as soon as reproduced the problem.
