### ISSUE TITLE
401 (Unauthorized) when installing `Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01`

### ISSUE THREAD

**Issue by itanex** [aspnet/AspNetCore#10248]
### Describe the bug
I am working on the [Get Started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio) guide. Step 2 says to run the following command:

> dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01

This should just install the templates, but I get the following message.

` Retrying 'FindPackagesByIdAsyncCore' for source 'https://microsoft.pkgs.visualstudio.com/DefaultCollection/_packaging/Universal.Store/nuget/v2/FindPackagesById()?id='Microsoft.AspNetCore.Blazor.Templates'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://microsoft.pkgs.visualstudio.com/DefaultCollection/_packaging/Universal.Store/nuget/v2/FindPackagesById()?id='Microsoft.AspNetCore.Blazor.Templates'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Restore completed in 801.87 ms for C:\Users\v-brwoo\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj.`

No matter how many times I ran the command I got this exact message. Why am/was I seeing this?

### Experiment
1. I checked what previews I had installed and uninstalled them all including 3.0Preview5
2. I downloaded new bits from the ASP.NET Core distro page
3. I checked my version in the console to verify that it `was3.0.100-preview5-011568`
4. I ran the command and got the following
`
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://microsoft.pkgs.visualstudio.com/DefaultCollection/_packaging/Universal.Store/nuget/v2/FindPackagesById()?id='Microsoft.AspNetCore.Blazor.Templates'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).
  Restore completed in 534.38 ms for C:\Users\v-brwoo\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj.
`

5. I ran the command again and got the following
`
  Restore completed in 457.27 ms for C:\Users\v-brwoo\.templateengine\dotnetcli\v3.0.100-preview5-011568\scratch\restore.csproj.
`

While I am now where I expected to be, the issue I encountered is odd.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.100-preview5-011568'
2. Run this code `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01` in a Console
3. See error

### Expected behavior
The project templates are installed and the command exits successfully

### Additional context
Reported Documentation Issue [Get Started with Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/12413)

**Comment by pranavkm** [comment]
Do you have a VSTS feed configured globally? You could use https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#package-sources to figure out if you have one set up.

**Comment by itanex** [comment]
I have not configured any specific NuGet Package Feeds for the system I am running this on. I am using VS 2019 Preview.

![image](https://user-images.githubusercontent.com/430586/57791570-e86a7e80-76f1-11e9-80eb-20c7a2892ce7.png)

This is the preset NuGet Package Feeds that I have currently in my configuration. As I have never seen the second one in this list, I would assume this is related to one of the Preview products (vs, core, etc).

![image](https://user-images.githubusercontent.com/430586/57791535-d7217200-76f1-11e9-968f-fe94df967bef.png)

Additionally, here is my current VS 2019 preview install. I have not done any "individual" settings, only the defaults for these that are displayed.

![image](https://user-images.githubusercontent.com/430586/57791800-6a5aa780-76f2-11e9-81ea-50beb252666b.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @itanex.
The failure you're getting is from NuGet feed authentication.
Please address the authentication issue and things should just work.
