### ISSUE TITLE
[2.1.x/2.2.x] Backport dev cert changes

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10246]
We need to backport the dev cert changes from https://github.com/aspnet/AspNetCore/pull/9293 to the 2.1 and 2.2 SDKs so that customers on Windows 10 1903 can fix https://github.com/aspnet/AspNetCore/issues/8952 when it occurs.

**Comment by anurse** [comment]
cc @shirhatti @DamianEdwards 
cc @javiercn @mkArtakMSFT

**Comment by javiercn** [comment]
I think per our discussion on the other thread, we don't need to do this anymore?

**Comment by anurse** [comment]
Yep, closing.

**Comment by mj1856** [comment]
Why?  Even if I clean and trust a new certificate, it still doesn't work if I enable HTTP/2 on asp.net core 2.2 with Kestrel.

**Comment by anurse** [comment]
The 3.0 **SDK** (releasing in September) will contain a fixed tool that you can use *without updating your app to 2.2*. The app can still run on 2.2 and be deployed to production servers without 3.0 installed, it's just the `dotnet dev-certs` tool that needs to be updated.

The latest 3.0 preview should contain this updated tool.

**Comment by mj1856** [comment]
Great.  Thanks. :)
