### ISSUE TITLE
What's the proper way to upgrade AspNetCore patch version?

### ISSUE THREAD

**Issue by Nothing-Works** [aspnet/AspNetCore#10249]
I've searched for this answer from some places and do not think I have a good answer for that.
so I have the latest SDK installed.
![222](https://user-images.githubusercontent.com/18606648/57737973-b6f9af00-7701-11e9-9c33-2bb944e29c98.jpg)

And I new up a brand new AspNetCore empty project (using CLI or VS 2019)
`
 dotnet new web
`
And now here is the screenshot from Nuget UI. 
![111](https://user-images.githubusercontent.com/18606648/57738185-8a926280-7702-11e9-9c76-5f6968baa0cf.jpg)

I can not select `v2.2.5` from the dropdown list (on the right hand side),  the dropdown is unselectable.
I am just wondering what's the proper way to update to the latest patch verison?
I know that I can edit the *.csproj file do this `<RuntimeFrameworkVersion>2.2.5</RuntimeFrameworkVersion>` manually.

Is there any other way to do this?
And I do not think manually change the patch version for the latest version is a good idea.

Another person had the same [problem](https://stackoverflow.com/questions/54842747/how-to-update-aspnetcore-from-2-2-0-to-2-2-2), without an answer either. 

Thanks

**Comment by anurse** [comment]
If you are using .NET Core, the only thing you need to do to update to the patch is install the latest patched runtime. .NET Core applications automatically roll forward to the highest patch version associated with the major/minor pair you target. This behavior can be disabled using [a setting in `[appname].runtimeconfig.json`](https://github.com/dotnet/core-setup/blob/92072fd9ea03740ea317b631d3894ff3c5d0854d/Documentation/design-docs/roll-forward-on-no-candidate-fx.md) but we strongly recommend you keep it to ensure you always run on the most up-to-date runtime (with all released security fixes).

While we do recommend you **run** on the latest patch, we recommend you **do not** update your app to target later patch versions as your app will *fail to start* if that patch doesn't exist on the target machine. Patches shouldn't be introducing APIs that you need to update to depend upon so there's no need to update the package reference.

**Comment by Nothing-Works** [comment]
Ah....I see, Thank you very much for the clarification. Will close this.

**Comment by spixy** [comment]
Should we update ([docs](https://docs.microsoft.com/en-gb/nuget/tools/package-manager-ui#updating-a-package)?
> You need to update your .NET Core installation to get new versions of the ASP.NET Core and .NET Core runtime.

So many people will upgrade .net core, but when they still see same old version in nuget window,
they are confused and will create issues here.

**Comment by anurse** [comment]
The doc you linked links through to our doc on [implicit versioning](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.2#implicit-versioning) (via "See this document for more details on .NET Core metapackages and versioning" and then "Microsoft.AspNetCore.App"). Do you have a suggestion for making this clearer?

**Comment by spixy** [comment]
I did not find that implicit versioning link there. It is OK then.

**Comment by anurse** [comment]
It's not the clearest path to follow :). I would certainly be interested in any thoughts you have on how it can be clearer. If you didn't find it, others might not either :)
