### ISSUE TITLE
[Blazor] Component is not rendered

### ISSUE THREAD

**Issue by mashbrno** [aspnet/AspNetCore#10242]
Simple razor component like this is not rendered:

```` html
<div>foo</div>
````

until `@inherits ComponentBase` is added to `.razor` file.

Next when I move this component to different directory than parent component which is using it, is not rendered even with `@inherits`. BUT it works if the other directory is called *Common*.

I'm using .NET Core 3.0 preview 5, Visual Studio 2019 1.0 preview 3

**Comment by mashbrno** [comment]
When I tried to prepare minimal working sample I was not able to reproduce the first problem. The second is related to namespaces of the components: I had *Common* namespace included in `_Imports.razor` but not *Charts* folder. Is it possible to include compile error when component not found?
(Changing from bug report to feature request)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mashbrno.
When moving your component to a new directory/namespace, you should make sure an appropriate `using` is included from where you're trying to use it.

Going forward, we're going to simplify this scenario by warning in situations described in the following issue: #9860
