### ISSUE TITLE
Add EnumeratorCancellation attribute to CancellationTokens in async iterators

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10250]
Anywhere we have an async iterator (see below) and take a `CancellationToken` as a parameter, we need to apply the `[EnumeratorCancellation]` attribute to the `CancellationToken` parameter to avoid `CS8425`.

```csharp
public async IAsyncEnumerable<string> GetStringsAsync(
		[EnumeratorCancellation] CancellationToken cancellationToken)
{
	yield break;
}
```

SignalR does this and it triggered an issue in CTI validation (specifically the tests that validate that the latest VS can build our stuff): https://devdiv.visualstudio.com/DevDiv/_workitems/edit/892482?src=WorkItemMention&src-action=artifact_link

It looks like [`EnumeratorCancellationAttribute`](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/src/System/Runtime/CompilerServices/EnumeratorCancellationAttribute.cs) was added 24 days ago so we should be able to depend on it now.

**NOTE** It appears the warning *only repros* in VS 16.2 pre-release builds.

**Comment by BrennanConroy** [comment]
The warning is a really annoying "feature" when someone writes an `IAsyncEnumerable<T>` hub method that accepts a `CancellationToken` (which means SignalR will create a CTS internally for the hub method and cancel it appropriately).

So now customers will be forced to add the attribute or ignore the warning.

**Comment by anurse** [comment]
Yep, that's more of a question on how the C# compiler wants to handle this though. I think our best way forward is to react and see how customers feel about it.

**Comment by BrennanConroy** [comment]
Done via https://github.com/aspnet/AspNetCore/pull/10411

**Comment by BrennanConroy** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [x] Relevant XML documentation comments for new public APIs are present.
    * [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
        * [x] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [3.0.100-preview6-012096]
            * ASP.NET Core Runtime: [3.0.0-preview6-19277-03]
            * .NET Core Runtime: [3.0.0-preview6-27727-02]
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
