### ISSUE TITLE
SignalR protobuf protocol

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/AspNetCore#10253]
I'd like to be able to use protobuf just by providing descriptions of everything that needs to be sent.

**Comment by anurse** [comment]
We looked in to this a while ago and found that it wasn't something we wanted to provide ourselves. ProtoBuf requires a lot of up-front definition whereas MessagePack is self-describing. The [Hub Protocol is extensible](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/common/SignalR.Common/src/Protocol/IHubProtocol.cs) and would allow the development of a ProtoBuf implementation, but we have no plans to add one.
