### ISSUE TITLE
Anti forgery token of razor page forms within folders not available automatically. 

### ISSUE THREAD

**Issue by solalem** [aspnet/AspNetCore#10254]

**Comment by solalem** [comment]
The default template of Razor Pages UI library creates a folder structure organized by Areas. After adding my Create.cshtml page into a feature folder and adding a form I was expecting the default anti-forgery token to be generated and sent to browsers automatically. Navigating to Feature/Create in a browser and submitting the form creates
`The required antiforgery cookie ".AspNetCore.Antiforgery.MsYT7wU3Kzg" is not present.`
 exception inside VS output window. The browser also shows no cookie with the specified name. I resolved my issue after manually adding `@Html.AntiForgeryToken()` inside my form. I think the default behavior of adding anti-forgery cookies should handle this case too. I can also see this is true for every pages inside child folders of Pages, folders inside Areas and any UI library folders.

**Comment by pranavkm** [comment]
You might be missing a `_ViewImports.cshtml` in the Feature area that sets up the form tag helper: `@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"`.

**Comment by solalem** [comment]
Yes that also did the trick, thank you. But I would expect the project template add that file in the first place. I think, sometimes, people may have the need to share form based pages in UI libraries as well.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
