### ISSUE TITLE
Blazor Question

### ISSUE THREAD

**Issue by PeterJD** [aspnet/AspNetCore#10255]
Hi
Using blazor Local client (or Host local)  libraries need to be downloaded

If I have business app where users repeatly use the Business application will the  down load be repeated.

Or can this be a one off ?

Peter

**Comment by conficient** [comment]
Yes the libraries can be cached by the browser just like any other downloadable content. Cacheing on the server depends on the server being used - Blazor client apps can use any type of server, not just IIS

There is a separate question of whether it would also be possible to use content delivery networks (CDNs) e.g. #9624 to distribute common Blazor libraries.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by PeterJD** [comment]
Hi
thanks for the info
