### ISSUE TITLE
Warnings in SignalR build due to invalid peer dependencies

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10251]
```
F:\workspace\_work\1\s\eng\targets\Npm.Common.targets(21,5): warning : " > ts-jest@22.4.6" has incorrect peer dependency "jest@^22.4.0 || ^22.5.0-alpha.1 || ^23.0.0-alpha.1". [F:\workspace\_work\1\s\src\SignalR\clients\ts\common\common.npmproj]
F:\workspace\_work\1\s\eng\targets\Npm.Common.targets(21,5): warning : " > karma-summary-reporter@1.5.0" has incorrect peer dependency "karma@^1.2.0 || 2.x". [F:\workspace\_work\1\s\src\SignalR\clients\ts\FunctionalTests\SignalR.Npm.FunctionalTests.npmproj]
```

Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=189015

We are seeing these warnings in our CI and in CTI testing (to validate that the latest VS can build our code): https://devdiv.visualstudio.com/DevDiv/_workitems/edit/892389?src=WorkItemMention&src-action=artifact_link

We should see if we can resolve these warnings since Warnings Are Bad:tm:

**Comment by BrennanConroy** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [X] The fix is tests-only.
* [ ] The fix contains product changes (**check all items below**).
	* [ ] Relevant XML documentation comments for new public APIs are present.
	* [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [ ] The change requires no docs changes.
	* [ ] Verification has been completed. (**check one item below**)
    	* [ ] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [VERSION]
			* ASP.NET Core Runtime: [VERSION]
			* .NET Core Runtime: [VERSION]
	    * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
