### ISSUE TITLE
Embed script support in Blazor server-side application

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#10263]
### Describe the bug
In blazor Client side, the .js files are referred automatically. Where as in server side its not working. Is there any configuration made for that in server side? Can any one please help me regard this? Thanks

### Additional context
i am Using VS2019 preview3
and .netcore preview5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kmuthukumar23.
We're revising how static content works in Blazor with https://github.com/aspnet/AspNetCore/issues/6349
