### ISSUE TITLE
How pass RenderFragment template=null to a Component

### ISSUE THREAD

**Issue by ray440** [aspnet/AspNetCore#10270]
The source of the issue can be found at [https://stackoverflow.com/questions/56118436/check-if-renderfragment-is-empty](https://stackoverflow.com/questions/56118436/check-if-renderfragment-is-empty) where I would like to check if `HeaderTitle` is empty or null. I thought it could use more discussion here.

```
    <MyComp Open="false">
        <HeaderTitle>
             @if (!String.IsNullOrEmpty(hdr)) {
                 ...
                <div class="flex-grow"> @hdr </div>
            }
        </HeaderTitle>
        <Detail>
            ...
        </Detail>
   </MyComp>
```

It seems that the root issue is that it is not simple to set `HeaderTitle=null`. The only way to do this is to **not** include it in `MyComp`. So you have to write something like:

```
@if (!String.IsNullOrEmpty(hdr)) {
    <MyComp Open="false">
        <HeaderTitle>... </HeaderTitle>
        <Detail>... </Detail>
   </MyComp>
} else {
    <MyComp Open="false">
        <!-- HeaderTitle=null --!>
        <Detail>... </Detail>
   </MyComp>
}
```

It may be useful to have a `RenderFragment.IsEmpty` function 
Or something like `<HeaderTitle ExcludeIf=true>... </HeaderTitle>`

**Comment by SteveSandersonMS** [comment]
@rynowak This would be a good example of when it would be useful to do inline Razor, e.g.

```cshtml
<MyComp Open="false" HeaderTitle="@MyHeaderTitle()">
    <Detail>...</Detail>
</MyComp>

@functions {
    RenderFragment MyHeaderTitle()
    {
        return hdr == null ? null : <h1>Hello</h1>;
    }
}
```

@ray440 This syntax isn't yet supported (AFAIK). In the meantime you might want to pass the `<HeaderTitle>` regardless, but also pass a bool flag to say whether it should be used, e.g.

```cshtml
    <MyComp Open="false" HasHeaderTitle="!String.IsNullOrEmpty(hdr)">
        <HeaderTitle>
             @if (!String.IsNullOrEmpty(hdr)) {
                 ...
                <div class="flex-grow"> @hdr </div>
            }
        </HeaderTitle>
        <Detail>
            ...
        </Detail>
   </MyComp>
```

Not ideal, but we're working on improving the flexibility as mentioned above.

**Comment by rynowak** [comment]
You can actually do it, it's just a little awkward. You have to define it inside a code block `@{ }`

```razor
@{
    var title = hdr == null ? null : @<h1>Hello</h1>
}
<MyComp Open="false" HeaderTitle="@title">
    <Detail>...</Detail>
</MyComp>
```

**Comment by ray440** [comment]
Currently, writing code like that makes VS crash... a lot :(

It's a better solution but it feels somewhat unnatural.  My first instinct was to try the code below, which doesn't work.  Would it be difficult to implement this?

```
<MyComp Open="false" HeaderTitle="@title">
    @if (!String.IsNullOrEmpty(hdr)) {
         <HeaderTitle>...</HeaderTitle>
     }
    <Detail>...</Detail>
</MyComp>
```

**Comment by rynowak** [comment]
We don't have anything like that on the roadmap, so it's not going to happen as part of this release.

**Comment by rynowak** [comment]
BTW, I am interested in your crash if you can point at which example caused it. We fixed something like that recently (pending release).

**Comment by ray440** [comment]
The crash was related to setting multi-line fragments (I think). Like this

```
var title = @<AComponent>...</AComponent>
             <div>...more stuff..</div>;
```

If I edited it slightly (or sneezed) VS would crash. It also completely messed up auto-formatting.

**Comment by rynowak** [comment]
@ajaybhargavb - can you try this out on latest bits? Something like:

```razor
@{
var title = @<AComponent>...</AComponent>
             <div>...more stuff..</div>;
}
```

**Comment by ajaybhargavb** [comment]
I tried this out and also tried a bunch of related things but couldn't get it to crash.
Also note, the `<div>...more stuff..</div>` in the above example will be parsed as C#. This is by design.

**Comment by ray440** [comment]
I'm using VS 16.1.0 Preview 3.0.  Is that the latest?

Your sample seems to be working a little better.  

But this sample is painful.  It might be related to `<OutcomeIcon>` . If I replace it with a `div` or a non-existant `<AComponent>`, it's better. 

```  
    RenderFragment MyHeaderTitle() {
        if (String.IsNullOrEmpty(Root.Group.Name)) {
            return null;
        } else {
            return @<OutcomeIcon Outcome="@Root.Outcome" />
                    <div class="flex-grow"> @hdr </div>;
        }
    }
```

**Comment by ajaybhargavb** [comment]
> I'm using VS 16.1.0 Preview 3.0. Is that the latest?

I tried this on pre-release bits. Preview 3 doesn't have this fix yet. It will be available in the next preview release.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
