### ISSUE TITLE
Blazor (client-side) template in .Net Core 3.0 x64 doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#10274]
VSF_TYPE_MARKDOWNinstall fresh visual studio 2019 preview
install 
.NET Core SDK 3.0.100-preview5-011568 x64 (ONLY) , then tried blazor (client-side) sample doesn't work

error : 
The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)

then install .NET Core SDK 3.0.100-preview5-011568 x86:
now both x64 and x86 is exist
then blazor (client-side)  is working
and got more templates compare to x64

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/565291/blazor-client-side-template-in-net-core-30-x64-doe.html
VSTS ticketId: 891792_
_These are the original issue comments:_

Visual Studio Feedback System on 5/12/2019, 09:04 PM (2 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 5/13/2019, 07:48 PM (43 hours ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We couldn't reproduce this issue on our end. We recommend you to reinstall your VS and .Net SDK to make sure you're in a good state.
