### ISSUE TITLE
The module at ClientApp/dist/server/main.js does not export a default function, and you have not specified which export to invoke

### ISSUE THREAD

**Issue by maurisa11** [aspnet/AspNetCore#10278]
I have the next problem when I run my asp .net core app:

NodeInvocationException: Prerendering failed because of error: Error: The module at ClientApp/dist/server/main.js does not export a default function, and you have not specified which export to invoke.

This is my startup.cs file:

` app.UseSpa(spa =>
{
// To learn more about options for serving an Angular SPA from ASP.NET Core,
// see https://go.microsoft.com/fwlink/?linkid=864501

        spa.Options.SourcePath = "ClientApp";

        spa.UseSpaPrerendering(options =>
        {
            options.BootModulePath = $"{spa.Options.SourcePath}/dist/server/main.js";
            options.BootModuleBuilder = env.IsDevelopment()
                ? new AngularCliBuilder(npmScript: "build:ssr")
                : null;
            options.ExcludeUrls = new[] { "/sockjs-node" };
        });

        if (env.IsDevelopment())
        {
            spa.Options.StartupTimeout = new System.TimeSpan(0,5,0);
            //spa.UseAngularCliServer(npmScript: "start");
            spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
        }
    });`
and if I did: node -e "console.log(require('./ClientApp/dist/server/main.js'))"
this is the result:

{ LAZY_MODULE_MAP: { './admin/admin.module#AdminModule': NgModuleFactory_ { moduleType: [Function: AdminModule], _bootstrapComponents: [], _ngModuleDefFactory: [Function] }, './investor/investor.module#InvestorModule': NgModuleFactory_ { moduleType: [Function: InvestorModule], _bootstrapComponents: [], _ngModuleDefFactory: [Function] }, './restaurant/restaurant.module#RestaurantModule': NgModuleFactory_ { moduleType: [Function: RestaurantModule], _bootstrapComponents: [], _ngModuleDefFactory: [Function] } }, AppServerModuleNgFactory: NgModuleFactory_ { moduleType: [Function: AppServerModule], _bootstrapComponents: [ [Function: AppComponent] ], _ngModuleDefFactory: [Function] }, AppServerModule: [Function: AppServerModule] }

Someone can help me?

I need to finish the implementation of angular universal on my app.

**Comment by natemcmaster** [comment]
Hi @maurisa11, can you share more details on how to reproduce this issue? See https://github.com/aspnet/AspNetCore/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#to-reproduce for an outline of the steps we are normally looking for.

cc @mkArtakMSFT - could be an issue with Node Services or templates...added to both areas.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
