### ISSUE TITLE
Azure Dev Spaces debugging exception

### ISSUE THREAD

**Issue by simonziegler** [aspnet/AspNetCore#10286]
### Describe the bug
After starting VS 2019 with an ASP.NET Core 3.0 (must be Core 3.0) project, the first time you debug a project on Azure Dev Spaces, everything is fine. Then stop the debug session and debug again. You now get this:

![image](https://user-images.githubusercontent.com/11708435/57839021-c1797e80-77bd-11e9-85df-5377316be3f3.png)

### To Reproduce
1. Open VS2019 and create a new ASP.NET Core 3.0 project - any type you like.
2. Add Kubernetes Container Support, and connect to Azure Dev Spaces.
3. Debug on Azure Dev Spaces - it works!
4. Stop the debugging session and debug on Azure Dev Spaces again - it fails
5. This continues until you close VS2019 and restart it - you get one more successful debug session until you have to close and open VS2019 again

### Expected behavior
Debugging should work repeatedly, as indeed it does with ASP.NET Core 2.2 and earlier

### Screenshots
![image](https://user-images.githubusercontent.com/11708435/57839209-2a60f680-77be-11e9-8e10-01d21d1633ca.png)

### Additional context
None

**Comment by Tratcher** [comment]
@simonziegler this appears to be a tooling bug where it fails to stop the prior instance of the application. Can you please provide this tooling feedback through the feedback tool in Visual Studio?

**Comment by simonziegler** [comment]
Thanks, I have reported this in VS feedback as requested.

**Comment by anurse** [comment]
Closing this since Dev Spaces is outside of our scope. If their investigation yields an issue in our logic, they'll reach out to us.
