### ISSUE TITLE
Defining a route with [HttpPut] and {action} url parameter doesn't work.

### ISSUE THREAD

**Issue by Mastermindzh** [aspnet/AspNetCore#10288]
### Describe the bug
When defining a route to a method using the `[HttpPut]` attribute it will return a 404 if I try to bind the `action` parameter.

### To Reproduce
1. Using this version of ASP.NET Core '2.3'
2. Run this code 

```csharp
[HttpPut("{id}/estimates/{index}/{action}")]
public async Task<ActionResult> name(string id, string index, string action)
```

3. With these arguments 'valid string values, doesn't even find the method'
4. See error -> produces 404 not found, not an actual error as expected

### Expected behavior
It should just accept the {action} parameter just like the {id} or {index} parameter. If that is impossible it should at least produce some kind of error.

### Screenshots
![https://imgur.com/o476OFJ](https://i.imgur.com/o476OFJ.png)

### Additional context
Renaming {action} to anything else (f.e test) will make this work:

```csharp
[HttpPut("{id}/estimates/{index}/{test}")]
public async Task<ActionResult> Test(string id, string index, string test)
```

![https://imgur.com/a/KEscI9C](https://i.imgur.com/fL7iM14.png)

**Comment by pranavkm** [comment]
`action` is a reserved keyword for routing and cannot be re-used by user code. See https://github.com/aspnet/Mvc/issues/7876 for past discussions on this. We're tracking adding an analyzer to produce a build warning as part of https://github.com/aspnet/AspNetCore/issues/4930

**Comment by Mastermindzh** [comment]
Thanks, @pranavkm, I didn't check the archived repo for similar issues :)

Glad it's going to be resolved!
