### ISSUE TITLE
Kubernetes Orchestration auto generated Dockerfile has errors

### ISSUE THREAD

**Issue by simonziegler** [aspnet/AspNetCore#10289]
### Describe the bug
The Dockerfile fails to copy the csproj file during Continuous Deployment on Azure Devops

### To Reproduce
1. Create a new ASP.NET Core web app (any type), suggest not Core 3,0 due to other issues that get in your way
2. Add Kubernetes Orchestration support and connect to an AKS cluster
3. Add the project to Git locally and Azure Devops, and commit.
4. Go to AKS on the Azure Portal and click "Deployment Center (preview)"
5. Set up deployment for the project you just committed to Azure Devops, using an Azure Contain Registry
6. See the csproj copy error in the build

### Expected behavior
The csproj file should copy successfully

### Screenshots
The screenshot below shows your standard Dockerfile on the left, and one that I modified (hacked) to get around the issue on the right, after having googled the issue.

![image](https://user-images.githubusercontent.com/11708435/57845636-479bc200-77ca-11e9-92a7-22f6312c074e.png)

### Additional context
None

**Comment by anurse** [comment]
Are you referring to the ["Add Container Orchestration Support" gesture](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-kubernetes-tools?view=vs-2019) in Visual Studio? If so, I'd suggest you also file a VS Feedback report using the button in the top-right corner of VS. That will ensure it is visible to the team responsible for that experience.

![The "Provide Feedback" button in Visual Studio](https://user-images.githubusercontent.com/7574/58360929-37c25480-7e40-11e9-910c-51c92ff4dc42.png)

@glennc as our resident Containerite, do you have any insight to add or suggestions on people who could look at this further?

**Comment by anurse** [comment]
Closing as this is part of the VS tooling, and not something controlled in ASP.NET Core. Please use the VS feedback tool to file this and let us know (provide a link) if you do! We can help put it in front of the right eyes.
