### ISSUE TITLE
Lazy-initialize MessagePackHubProtocolOptions

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10309]
We should lazy-init the formatter resolvers in MessagePackHubProtocolOptions. The default set of resolvers trigger a static constructor that throws on AOT environments (IL2CPP for Unity for example). If we lazy init it, an AOT-based app can call the setter to replace the list of formatters with an AOT-friendly set without risking an exception due to trying to initialize the non-AOT-friendly ones.

**Comment by mikaelm12** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [ ] This is a Docs issue.
* [x] The fix contains product changes (**check all items below**).
	* [x] Relevant XML documentation comments for new public APIs are present. - Not needed
	* [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [x] The change requires no docs changes.
	* [x] Verification has been completed. (**check one item below**)
    	* [x] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [3.0.100-preview7-012617]
			* ASP.NET Core Runtime: [3.0.0-preview7.19325.3]
			* .NET Core Runtime: 3.0.0-preview7-27825-05]
	    * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: 3.0.0-preview7.19325.8
