### ISSUE TITLE
Blazor: Azure Microsoft CDN needs support for HTTP to HTTPS forwarding

### ISSUE THREAD

**Issue by leftmostlane** [aspnet/AspNetCore#10305]
Title:
Azure Microsoft CDN needs support for HTTP to HTTPS forwarding in order to support Blazor Client-Side Applications

Example: 
Created a Blazor client-side application.  Deployed to Azure Static Websites and setup Azure Microsoft CDN in front of the static website in order to link a custom domain (domain CNAME points to Microsoft CDN address) and generate a free SSL certificate.  The domain is setup for forward mywebsite.com to www.mywebsite.com.  HTTPS is required everywhere of course (encrypt the web!).  Microsoft CDN just displays an error message about the site not supporting HTTP.  
http://www.mywebsite.com      broken
http://mywebsite.com      broken
https://mywebsite.com      broken
https://www.mywebsite.com      works

Solution:
Implement the following feature on Azure Microsoft CDN so we may write Blazor client-side applications and host them in Azure:
https://feedback.azure.com/forums/169397-cdn/suggestions/34712959-redirect-to-https

**Comment by Eilon** [comment]
@blowdart

**Comment by blowdart** [comment]
Why would I be responsible for Azure CDN features? If they don't support this, then it's an issue for thenm, not us.

Closing as this is not our area of responsibility, it's Azure's.

**Comment by Eilon** [comment]
Tagged you because it involved HTTPS redirect, which can have security implications.

**Comment by blowdart** [comment]
Ah, fair enough, still, not us, and nothing we can do here.

**Comment by leftmostlane** [comment]
@jeffhollan
