### ISSUE TITLE
Fix MessagePack JS package peer dependency

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10307]
The `@aspnet/signalr-protocol-msgpack` package has a peer dependency on `@aspnet/signalr`. This is good, but the value is static and [hasn't been updated since `1.0.0-preview3`](https://unpkg.com/@aspnet/signalr-protocol-msgpack@1.1.0/package.json). We should either add automation to update the peer dependency on every build, or just remove it, or maybe make it a real dependency.

**Comment by anurse** [comment]
It should almost definitely just be a real dependency, in which case we can use a path link and I think the build output will be correct.

**Comment by OzBob** [comment]
Confirmed.
It also, stops MessagePack messages between JavaScript client and server.

npm i @aspnet/signalr@next
//which installs v "^3.0.0-preview5-19227-01"
npm i @aspnet/signalr-protocol-msgpack@next
//which installs v "^3.0.0-preview5-19227-01"
BUT WARNS:

> "npm i @aspnet/signalr-protocol-msgpack@3.0.0-preview5-19227-01 requires a peer of @aspnet/signalr@^1.0.0-preview3 but none is installed. You must install peer dependencies yourself."

that version is NOT available on https://www.npmjs.com/package/@aspnet/signalr

**Comment by BrennanConroy** [comment]
The warning can be ignored for now, we'll be fixing it up soon.

Those 2 packages should be compatible. Could you share a repro app that shows the issue?

**Comment by anurse** [comment]
This is more complicated than I hoped. If you set it to `link:../signalr` or `file:../signalr`, that's exactly what goes in to the package.json, which isn't what we want.

To do this right I think we need to rewrite the package.json during build... I'll tinker with that.

**Comment by anurse** [comment]
@pranavkm is looking at fixing this as part of his send queue change.

**Comment by anurse** [comment]
Should be fixed in #10506. TODO: Verify in output build.

**Comment by BrennanConroy** [comment]
Reopening as the fix was reverted due to build issues

**Comment by anurse** [comment]
Assigning you to this @pranavkm but only because you've been looking at it in your PR. Let me know if you need help or someone to take this over!

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/aspnet/AspNetCore/commit/d935ea2d2553d48887b968638726470adf0c2b3c

**Comment by OzBob** [comment]
npm i @aspnet/signalr-protocol-msgpack@next

//still has similar warning about compatibility:

//"npm WARN @aspnet/signalr-protocol-msgpack@3.0.0-preview6.19307.2 requires a peer of @aspnet/signalr@^1.0.0-preview3 but none is installed. You must install peer dependencies yourself."

Ignoring for now - but I will test whether this MessagePack is compatible with:
https://github.com/aspnet/AspNetCore/blob/658b37d2bd3b0da2c07e25b53fa5c97ce8d656d3/src/SignalR/samples/SignalRSamples/Startup.cs#L32 and 
Nuget Microsoft.AspNetCore.SignalR.Protocols.MessagePack -Version 3.0.0-preview6.19307.2

**Comment by BrennanConroy** [comment]
This is fixed in the preview7 build

**Comment by mikaelm12** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [ ] This is a Docs issue.
* [x] The fix contains product changes (**check all items below**).
	* [x] Relevant XML documentation comments for new public APIs are present. - Not needed
	* [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [x] The change requires no docs changes.
	* [x] Verification has been completed. (**check one item below**)
    	* [ ] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [VERSION]
			* ASP.NET Core Runtime: [VERSION]
			* .NET Core Runtime: [VERSION]
	    * [x] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: aspnet-signalr-protocol-msgpack-3.0.0-preview7.19325.7
