### ISSUE TITLE
Microsoft.AspNetCore.Authentication.AzureAD.UI Broken

### ISSUE THREAD

**Issue by markti** [aspnet/AspNetCore#10313]
### If you believe you have an issue that affects the security of the platform please do NOT create an issue and instead email your issue details to secure@microsoft.com. Your report may be eligible for our [bug bounty](https://technet.microsoft.com/en-us/mt764065.aspx) but ONLY if it is reported through email.

https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/issues/45

### Describe the bug
The Azure AD extension method doesn't have a working example for a WebAPI and the official nuget package breaks when I attempt to update the available sample to use the official library.

### To Reproduce
1. Clone https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore
2. Upgrade to .NET Core 2.1
3. Upgrade to ASP.NET 2.1.1
4. Add nuget package Microsoft.AspNetCore.Authentication.AzureAD.UI
5. replace hacky extension method in the sample with the official one provided in above nuget.
6. Notice you get a "no authentication scheme available"

### Expected behavior
Azure AD Authentication should work

### Additional context
Include the output of `dotnet --info`

**Comment by Megasware128** [comment]
That is not really a lot of information. For me the package just works.

**Comment by blowdart** [comment]
As this is the bug template, rather than a bug, there's not a lot to go on here?

@markti do you mean to point us at the linked issue in Azure Samples? Are you saying this is what your bug is?

**Comment by Tratcher** [comment]
Can you please provide a complete project that reproduces the issue?

**Comment by markti** [comment]
@blowdart when i take the Azure Sample and replace the hacky AddAzureADBearer extension method with the official one provided by Microsoft.AspNetCore.Authentication.AzureAD.UI, it doesnt work. @Tratcher all you have to do is clone https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore upgrade to .net core 2.1 and asp.net core 2.1.1 add the Microsoft.AspNetCore.Authentication.AzureAD.UI, use that extension method and it won't work.

**Comment by markti** [comment]
> That is not really a lot of information. For me the package just works.

it doesnt work with the Azure Sample i referenced. I'm trying to replicate an Azure AD protected WebAPI and have a Azure AD authenticated WebApp / Postman talk to it.

**Comment by anurse** [comment]
The sample is using ASP.NET Core 2.0 which is out of support. Simply updating to 2.1 may not be sufficient here. The best fix is to get the sample updated to 2.1 (or higher). I notice you have filed https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/issues/46 to do this.

Closing as we don't have a specific change to take here. The sample should be updated we can work with the team who owns that sample to do that.
