### ISSUE TITLE
Microsoft.AspNetCore.Blazor.Http.WebAssemblyHttpMessageHandler.SendAsync throws on Server Side Blazor

### ISSUE THREAD

**Issue by AdmiralSnyder** [aspnet/AspNetCore#10329]
### Describe the bug
On Server-Side Blazor, calling Microsoft.AspNetCore.Blazor.Http.WebAssemblyHttpMessageHandler.SendAsync
throws an exception, because 
"Blazor._internal.http.sendAsync" is being invoked with Mono.WebAssembly.Interop.MonoWebAssemblyJSRuntime.InvokeUnmarshalled
giving the error "Generic method or method in generic class is internal call, PInvoke, or is defined in a COM Import class."

### To Reproduce

1. Using this version of ASP.NET Core 'Blazor 3.0.0-preview5-19224.8'
2. Invoke Microsoft.AspNetCore.Blazor.Http.WebAssemblyHttpMessageHandler.SendAsync

### Expected behavior
if WebAssemblyHttpMessageHandler isn't supposed to work on server-side, an exception should be thrown at instanciation time.
the xml comment only states:
    /// <summary>
    /// A browser-compatible implementation of <see cref="HttpMessageHandler"/>
    /// </summary>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AdmiralSnyder.
Feel free to send us a PR, and we'd happily consider it.
In the meantime this area is going to improve pretty soon as we move to the built-in Mono provided message handler.
