### ISSUE TITLE
Create a IStringLocalizer in IStringLocalizerFactory which has access to scoped services from the HTTP request

### ISSUE THREAD

**Issue by HansMusterWhatElse** [aspnet/AspNetCore#10324]
### Problem Description

Hi guys,

I currently face the following issue for which I am looking for a solution and maybe some best practices how this could be solved.

With our current setup **Localization** is implemented without any factories and we solely use the non-generic `IStringLocalizer`, `IHtmlLocalizer `and `IViewLocalizer` interfaces to provide our own implementation. 

The scoped lifecycle was needed in order to have access to some **HttpRequest** related information (e.g tenant).

```
services.AddScoped<IStringLocalizer, MyStringLocalizer>();
services.AddScoped<IHtmlLocalizer, MyHtmlLocalizer>();
services.AddScoped<IViewLocalizer, MyViewLocalizer>();
```

This all works fine and well until there was a requirement to also localize validation message within our implementation of `IValidationAttributeAdapterProvider` which is registered as a singleton.

```
public class CustomValidationAttributeAdapterProvider : IValidationAttributeAdapterProvider
{
	public IAttributeAdapter GetAttributeAdapter(ValidationAttribute attribute, IStringLocalizer stringLocalizer)
        {
	         // The IStringLocalizer instance which is passed in gets initialized by the IStringLocalizerFactory which was preregistered as part of the framework
	}
}   
```

Although I could implement my own implementation for the `IStringLocalizerFactory`, I don't seem to have a way to pass in some scoped services as part of the Create method to initialize an instance of our `MyStringLocalizer`.

### Troubleshooting

- Given the limitation of the `IStringLocalizerFactory` is it somehow possible to close this gap without re-implementing many of the parts of the Localization framework from Microsoft? 

Any input which would help me to solve this issue is very much appreciated.

Thank you in advance!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @HansMusterWhatElse.
You can register your implementations as `singleton` and refer to the `HttpContext` accessor to resolve it.
Other than that the current implementation of the framework for `IStringLocalizer` expects it to be `singleton` and when that changes, things don't work the way they should.
