### ISSUE TITLE
On-demand blazor server-side connection 

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#10320]
Blazor server-side rendering requires in-time communication between clients and servers.

Currently if connection drops, the client will try to re-connect to server immediately. I think it will be better if it can rebuild the connection when the next request starts.

Also, communicating with SignalR Core will cause a problem that once a client connect to a server, the connection will stick to a specific server which cannot make use of loading balancer if possible.

What's more, keeping a persistent connection will increase pressure of servers.

Therfore, I think blazor on server-side rendering should only build connection between client and server on-demand, and if there's a period of inactivity, the connection can be temporary disposed and it can re-connect to server when the next request from client starts. If connection dropped, it should delay re-connection to the next request and connect in the background but not showing a "connection dropped" screen.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hez2010.
This wont' work for Blazor, as the model Blazor uses allows the server to push data to clients, whenever necessary, which requires active connection all the time.
