### ISSUE TITLE
var is not local. (Blazor)

### ISSUE THREAD

**Issue by wrkettlitz** [aspnet/AspNetCore#10327]
### Describe the bug
` @for (var i = 1; i < int_amount_of_pages + 1; i++)
            {         
   var intpagenr = i;
                    <li class="page-item"><a class="page-link" value="@i" onclick="@(() => SetPageNR( intpagenr.ToString()))"> @i.ToString()</a></li>
}`

If 'int_amount_of_pages ' is 5, 'i' will always be 6 when given as an argument to 'SetPageNR', Only when you declare a local variable, equate it to 'i' and then give that as an argument is the expected behavior executed.
### To Reproduce
1. Using this version of ASP.NET Core '...'
3.0 preview-5
2. Run this code '....'
see above
3. With these arguments '....'
see above
unexpected behavior

### Expected behavior
i is not the max i was + 1, i is what it was when it went through that loop.
### Additional context
Include the output of `dotnet --info`

**Comment by campersau** [comment]
> The necessity to declare a variable inside your loop is just how C# lambdas work - they bind to a variable, not to the value that was in the variable when the lambda was constructed.

https://github.com/aspnet/Blazor/issues/275#issuecomment-373686979

This is documented here (at the end) https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#event-handling

Other issues:
https://github.com/aspnet/AspNetCore/issues/10138
https://github.com/aspnet/AspNetCore/issues/7134
https://github.com/aspnet/Blazor/issues/1562
https://github.com/aspnet/Blazor/issues/1402
https://github.com/aspnet/Blazor/issues/1422
https://github.com/aspnet/Blazor/issues/764
https://github.com/aspnet/Blazor/issues/447
https://github.com/aspnet/Blazor/issues/275

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
