### ISSUE TITLE
Custom claims is not persisting with ASP.NET Core Identity default claims

### ISSUE THREAD

**Issue by TanvirArjel** [aspnet/AspNetCore#10328]
I have added two custom claims in the following login code:

                
         if (model.ApplicationUser != null)
         {
                    SignInResult signInResult = await _signInManager.CheckPasswordSignInAsync(model.ApplicationUser, model.Password, lockoutOnFailure: false);

                    if (signInResult.Succeeded)
                    {
                        User userInfo = await _userService.GetUserInfoByEmailAsync(model.Email);

                        var customClaims = new[]
                        {
                            new Claim("UserId", userInfo.UserId.ToString()), // My custom claim
                            new Claim("ProfileName", userInfo.ProfileName) // My custom claim
                        };

                        var claimsPrincipal = await _signInManager.CreateUserPrincipalAsync(model.ApplicationUser);

                        if (claimsPrincipal?.Identity is ClaimsIdentity claimsIdentity)
                        {
                            claimsIdentity.AddClaims(customClaims);
                        }

                        await _signInManager.Context.SignInAsync(IdentityConstants.ApplicationScheme,
                            claimsPrincipal,
                            new AuthenticationProperties { IsPersistent = model.RememberMe });

                        return RedirectToAction("Profile", "Learner");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Either user name/email or password is invalid!");
                        return View(model);
                    }
                }

Problem is that initially everything works fine. After certain amount of time (Lets say 15 minutes) `UserId` and `ProfileName` are getting null although ASP.NET Core Identity default claims has value:

      
       var userId =  User.FindFirst("UserId").Value //  Getting null
       var profileName =  User.FindFirst("ProfileName").Value // Getting null

        var id =  User.FindFirst(ClaimTypes.NameIdentifier).Value // Has value
        var userName =  User.FindFirst(ClaimTypes.Name).Value // Has value

Is it a bug or am I missing something? Please help!

**Comment by blowdart** [comment]
Every 15-20 minutes makes sense, because that's when we refresh the cookie from the back end database, and as your changes don't come from there, your additional claims won't get refreshed.

So there are a couple of ways to approach this;

1. Put the claims in your identity database so they come out in the ApplicationUser
2. Use [claims transformation](https://brockallen.com/2017/08/30/beware-in-asp-net-core-2-0-claims-transformation-might-run-multiple-times/)

**Comment by TanvirArjel** [comment]
@blowdart Thank you so much! First approach has worked for me! I have question- Does second approach also use `AspNetUserClaims` table too?

**Comment by blowdart** [comment]
No, the second approach has no implementation at all, you'd source the claims from wherever you want and do everything manually

**Comment by blowdart** [comment]
As you have a working solution, I'm going to close this for now. If you have questions on the same topic please reopen the issue.
