### ISSUE TITLE
Styled File Upload buttons not working as expected

### ISSUE THREAD

**Issue by owaits** [aspnet/AspNetCore#10322]
I am not entirely sure if this is a blazor issue or not but I am using client side blazor and trying to create a styled file upload button using the code bellow. When you click on the aperture image it opens the file upload dialog and my C# code correctly puts the image data in the EditItem.EncodedPicture property. To all respects it works and when you click save the image data is pushed to the server and committed to the database. Then when you re-load the page the image appears.

```
<div class="form-group">
  <label for="uploadPhoto" class="form-control text-center" style="height:113px;width:125px">
  @if (EditItem.EncodedPicture != null)
   {
    <img src="@($"data:image/jpg;base64,{EditItem.EncodedPicture}")" width="100" height="100" />
   }
  else if (EditItem.PictureUrl != null)
   {
     <img src="@($"{EditItem.PictureUrl}")" width="100" height="100" />
  }
  else
  {
    <i style="font-size:76px;" class="oi oi-aperture" />
   }
  </label>
  <input id="uploadPhoto" ref="uploadPhoto" class="collapse" type="file" accept="image/*;capture=camera;.jpg" onchange="@UploadPhoto" />
</div>
```

What does not appear to work is that after I put the file in the local parameter EditItem.EncodedPicture I call StateHasChanged() so that the page re-renders and displays the image as a preview. This does not work and the page appears to not re-render with the Base64 encoded image. However if I remove the "collapse" class from input and click on the default input button to upload the file it all works perfectly. I am not sure why clicking on the label to start the file upload and clicking on the input button should be any different, but it is.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @owaits.
This doesn't sound like a Blazor issue so we recommend to post this question to `StackOverflow`, as that way you'd probably get faster answer to your question.
