### ISSUE TITLE
Array or List in query string does not get parsed

### ISSUE THREAD

**Issue by OculiViridi** [aspnet/AspNetCore#10323]
Referring to this previous [issue 7712](https://github.com/aspnet/Mvc/issues/7712), I'm still facing this problem when using complex objects as parameters of GET method in ApiController.
So, values inside my comlpex object with `List<>` parameter are not parsed.

I've also read #8881 but I'm not on POST.

I'm running .NET Core:
```
.NET Core SDK (che rispecchia un qualsiasi file global.json):
 Version:   2.1.603
 Commit:    ae71c68742

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.603\

Host (useful for support):
  Version: 2.1.10
  Commit:  9013a2af4b
```

**Note:** I cannot update now to .NET Core v2.2 or newer.

### Code sample

Controller with method

```csharp
[HttpGet]
public async Task<ActionResult<PagedResultTable>> Send([FromQuery] QueryRequest query, CancellationToken cancellationToken)
{
    IRequestCultureFeature rqf = Request.HttpContext.Features.Get<IRequestCultureFeature>();
    CultureInfo culture = rqf.RequestCulture.Culture;

    QueryResultTable result = await QueryManager.Send(query, StringLocalizerFactory, culture);

    return Ok(result);
}
```

Object models

```csharp
public class QueryRequest
{
    public string Key { get; set; }
    public List<QueryFilter> AppliedFilters { get; set; }
}

public class QueryFilter
{
    public string Key { get; set; }
    public List<object> Values { get; set; }
}
```

**Comment by pranavkm** [comment]
What is the value of the query string that's being bound?

**Comment by OculiViridi** [comment]
Everything is parsed, except for the `List` type values, so: `AppliedFilters` (that then contains a `List<object>`).

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
