### ISSUE TITLE
Change `ValuesController` to `WeatherController` in templates

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10333]
GET only (scaffolding covers the POST/PUT/DELETE scenarios)
Overload one, accepts two parameters: string location (returns Celsius)
Overload two, accepts two parameters: string location, TemperatureUnit unit
Enum TemperatureUnit defined in project: public enum { Celsius, Fahrenheit }
Returns: new WeatherResult { Location = location, Temperature = randomTemp, TemperatureUnit = unit }
If Swashbuckle opted in to then ensure wired up for enums correctly

**Comment by mkArtakMSFT** [comment]
Make sure the changes from #9226 are also applied as part of this work.

**Comment by isaac2004** [comment]
@mkArtakMSFT @ryanbrandenburg if this hasn't been started, I can take this, been wanting to contribute to Core for a bit.

**Comment by mkArtakMSFT** [comment]
We will happily consider your PR, @isaac2004!

**Comment by isaac2004** [comment]
Sweet, is there a particular branch this needs to go in since it is preview 7?

**Comment by ryanbrandenburg** [comment]
You should be fine to just put it into master. The milestone just tells our team-members when they should target working on an item, but for something like this which is self-contained work there's no reason it couldn't go in earlier (ie preview 6) if it happened to be finished. We'll just change the milestone once it's merged.

**Comment by isaac2004** [comment]
So is this dependent on #7639?

**Comment by ryanbrandenburg** [comment]
I would say it's not dependent, was there a particular reason you thought it might be? Perhaps I missed something.

**Comment by isaac2004** [comment]
The mention of swashbuckle made me think that

**Comment by ryanbrandenburg** [comment]
We'll do that work as part of the work to add the swashbuckle option, no worries.

**Comment by isaac2004** [comment]
Question on the API naming. Do you want both endpoints to be tested? Due to mismatching they need to be given unique routes

**Comment by ryanbrandenburg** [comment]
Hmm. @mkArtakMSFT, rather than have two routes, one which takes the unit and one that doesn't, can we just have one route and have the unit default to Celsius? Having two routes with the same path and different parameters is ambiguous to the routing engine:
![Ambiguous](https://user-images.githubusercontent.com/14987221/58360304-ea90b380-7e3c-11e9-8b05-8bc64173cba9.PNG)

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg , yes, let's remove the single-parameter overload and leave the one which takes the `unit` parameter.

**Comment by isaac2004** [comment]
So does location even matter? Might make sense to remove it

**Comment by ryanbrandenburg** [comment]
I think keeping the location makes sense given the weather API scenario, it just so happens that we don't do anything other than return it.

**Comment by ryanbrandenburg** [comment]
Thanks @isaac2004!

**Comment by isaac2004** [comment]
@ryanbrandenburg Will this make it to Preview 6?

**Comment by ryanbrandenburg** [comment]
Preview6 has already branched, but considering this was slated for 3.1 and will now go out with "Preview7" that makes it ahead of schedule. Thanks for knocking it out!
