### ISSUE TITLE
TestServer HttpClient SendAsync returns NOT_FOUND when api is in classLibrary

### ISSUE THREAD

**Issue by ghstahl** [aspnet/AspNetCore#10331]
### Describe the bug
The exact same controller works when it is in the main application OR in a class library.
i.e.
https://localhost:5001/api/SomeThing2/dog
 
However, when called from TestServer's HttpClient it returns a 404 when the SomeThing2 controller is in a class library.  Cut and paste the controller back to the main application results in TestServer's HttpClient returning a 200.

### To Reproduce
[minimal project](https://github.com/P7CoreOrg/TestServerExternalControllerProblem)  
or 
[AzurePipelinesDemoAspNetCore](https://github.com/P7CoreOrg/AzurePipelinesDemoAspNetCore)  

Currently, it is failing my tests when the Something2 is an external project
https://github.com/P7CoreOrg/AzurePipelinesDemoAspNetCore/blob/master/src/SomeThing2/Controllers/SomeThing2Controller.cs

Cut and Paste the SomeThing2Controller to the following location;
https://github.com/P7CoreOrg/AzurePipelinesDemoAspNetCore/tree/master/src/TheWebApp/Controllers
which is in the main app make everything work.

https://github.com/P7CoreOrg/AzurePipelinesDemoAspNetCore/blob/master/src/xUnit_TheWebAppTests/UnitTestSomeThing.cs  

 ```
        [Fact]
        public async Task Test_Get_SomeThing2_Success()
        {
            var client = _fixture.Client;
            var req = new HttpRequestMessage(HttpMethod.Get, "/api/SomeThing2/dog")
            {
                // Content = new FormUrlEncodedContent(dict)
            };
            var response = await client.SendAsync(req);
            response.StatusCode.ShouldBe(System.Net.HttpStatusCode.OK);
            var jsonString = await response.Content.ReadAsStringAsync();
            jsonString.ShouldNotBeNullOrWhiteSpace();

            var dogs = JsonConvert.DeserializeObject<List<string>>(jsonString);
            dogs.ShouldNotBeNull();
            dogs.Count.ShouldBeGreaterThan(0);

        }
```

### Expected behavior
Should not return a 404 when SomeThing2Controller is in a separate classlibrary.

**Comment by ghstahl** [comment]
The only clue I have so far from stepping symbols is EndpointDataSource contains only endpoints from the host app and not the referenced projects.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ghstahl.
This got fixed today: https://github.com/aspnet/AspNetCore/issues/4332
Closing this issue as a dupe.
