### ISSUE TITLE
Wrong creating project

### ISSUE THREAD

**Issue by UltWolf** [aspnet/AspNetCore#10338]
Get error, when run project after creating. (i`m trying creating by VS2019, and dotnet cli)
The error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4036	The "RazorGenerate" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin" directory.	ValueProduct	C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets	
```
Where this error:
```
<RazorGenerate
      Debug="$(_RazorDebugGenerateCodeTask)"
      DebugTool="$(_RazorDebugGenerateCodeTool)"
      ToolAssembly="$(_RazorToolAssembly)"
      UseServer="$(UseRazorBuildServer)"
      ForceServer="$(_RazorForceBuildServer)"
      PipeName="$(_RazorBuildServerPipeName)"
      Version="$(RazorLangVersion)"
      Configuration="@(ResolvedRazorConfiguration)"
      Extensions="@(ResolvedRazorExtension)"
      Sources="@(_RazorComponentDeclarationSources)"
      ProjectRoot="$(MSBuildProjectDirectory)"
      TagHelperManifest="$(_RazorComponentDeclarationManifest)"
      GenerateDeclaration="true" /> 
```
Versions : ASP.NET CORE 3.0.100
Blazor version: 3.0.0-preview5-19227-01
OS: Windows 10.

**Comment by schrose** [comment]
I am having the same issue. Any input would be helpful.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @UltWolf.
What exact project is failing for you? Which project have you created?

**Comment by schrose** [comment]
The above error was appearing for me on a project but I realized that I didn't have the correct .Net Core SDK preview version installed. Once that was done I was able to get passed the errors to proceed forward Thank you for your attention on this comment.

**Comment by UltWolf** [comment]
![изображение](https://user-images.githubusercontent.com/18503527/57967496-56b87680-7968-11e9-8e66-fbcda3a87747.png)
Just creating Blazor on ASP. NET CORE Hosted, and without ANY change, just build project, and i get this error in the Server side application.

**Comment by mkArtakMSFT** [comment]
Please make sure you have both the latest SDK as well as the latest VS 2019 preview installed on your machines.

**Comment by mkArtakMSFT** [comment]
Also, if you're having the issue still, please share the output from `dotnet --info` in here.

**Comment by mkArtakMSFT** [comment]
We're closing this issue as the original reported issue was resolved. @UltWolf, if you're still facing a problem, feel free to file a new issue.

**Comment by NovichikhinAlexey** [comment]
@UltWolf I solve this problem after i update SDK to 3.0.100-preview5-011568.
Please try update

**Comment by UltWolf** [comment]
@NovichikhinAlexey , Yeah, thanks, it`s resolve my issue.)
