### ISSUE TITLE
Remove Cookie Consent UI from all templates and move into docs

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10346]
The Cookie Consent UI should not be part of templates any more. We should, instead, turn the current state into docs for customers to enable, if you wish.

**Comment by brockallen** [comment]
will this mean it's gone from all asp.net core templates? mvc, etc?

**Comment by ryanbrandenburg** [comment]
Clarified the title. Thanks for the eagle eye @brockallen.

**Comment by brockallen** [comment]
So that's fuckin' awesome -- I can't tell you how many web apps I create from File->New Project and that's the first thing I have to delete. Wahoo!

**Comment by ryanbrandenburg** [comment]
Removing the cookie-consent is done, now we just have to include it in the docs.

**Comment by isaac2004** [comment]
@scottaddie do you need an issue to track the doc changes? I can probably add a section that shows the UI and Middleware if you point me to what doc it should go in

**Comment by scottaddie** [comment]
@isaac2004 Yes, please create an issue for this. The following doc would need to be updated for 3.0: https://docs.microsoft.com/en-us/aspnet/core/security/gdpr.

**Comment by isaac2004** [comment]
@scottaddie done!

**Comment by isaac2004** [comment]
@ryanbrandenburg just realized I forgot to remove Privacy views. Since Cookie consent loads these, should they be removed as well?

**Comment by ryanbrandenburg** [comment]
The Privacy page is also referenced in the footer (_Layout.cshtml), so we should keep that page.

**Comment by isaac2004** [comment]
@ryanbrandenburg FYI docs have been updated as well

**Comment by ryanbrandenburg** [comment]
Cool, once that PR is merged/approved we can close this out.

**Comment by isaac2004** [comment]
@ryanbrandenburg @mkArtakMSFT the doc has been updated
https://github.com/aspnet/AspNetCore.Docs/issues/12720

**Comment by mkArtakMSFT** [comment]
Thanks @isaac2004!

@ryanbrandenburg looks like nothing else left in here to do. If so, please move this back to `Preview7` and close as `Done`.
