### ISSUE TITLE
Simplify web project templates

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10347]
We should remove the CDN config as well as environment-based CSS/javascript references from web templates

**Comment by isaac2004** [comment]
I can grab this one

**Comment by isaac2004** [comment]
Should we remove the CDN tests as well in Templates.Test?

https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/test/CdnScriptTagTests.cs
