### ISSUE TITLE
System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by PeterJD** [aspnet/AspNetCore#10353]
Interesting error from Startup.cs line 43 from Hosting template you provided

System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=C:\Users\liudm\source\repos\BlazorSol\BlazorHost.Client\bin\Debug\netstandard2.0\dist\
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at BlazorHost.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\liudm\source\repos\BlazorSol\BlazorHost.Server\Startup.cs:line 43

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by DanTsion** [comment]
Hi, i had the same issue and I removed from my project this ItemGroup 
```
<!--<ItemGroup>
    <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
      <HintPath>..\..\..\..\..\..\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.0.0-preview5-19227-01\ref\netcoreapp3.0\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>-->
```

**Comment by PulaSivaPrasad** [comment]
i have updated the below things from stable version 4.0.1

Swashbuckle.AspNetCore rc4
Swashbuckle.AspNetCore.Swagger rc4
Swashbuckle.AspNetCore.SwaggerUI rc4

<img width="1920" alt="swagger error" src="https://user-images.githubusercontent.com/58215717/69632427-fd4aa600-1074-11ea-8842-830c7a2dfd4b.png">

i'm facing the issue while running the application. all the dll's are skipping loading symbols.

like :- "'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.AspNetCore.Components.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled."

any solution please let me know.
