### ISSUE TITLE
Add ability to disable client cert validation for Kestrel

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#10351]
As discussed in https://github.com/aspnet/AspNetCore/pull/9756 would be useful for Cert Auth.

**Comment by anurse** [comment]
All we need to do here is add a top-level option or extension method to Kestrel options to say `AllowAnyClientCert`. Some docs may need to be updated.

**Comment by patrikmolsson** [comment]
You can possibly use the [ClientCertificateValidation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.https.httpsconnectionadapteroptions.clientcertificatevalidation?view=aspnetcore-2.2) like so to disable client cert validation: 

```cs
HttpsConnectionAdapterOptions certOptions = new HttpsConnectionAdapterOptions
{
    ClientCertificateValidation  = (cert, chain, sslPolicyErrors) =>
    {
        return sslPolicyErrors == SslPolicyErrors.None || sslPolicyErrors == SslPolicyErrors.RemoteCertificateChainErrors; // or: return true;
    }
};
```

**Comment by anurse** [comment]
This would be great for a new contributor!

**Comment by bcisnero** [comment]
So I'm reviewing this and if I understand correctly the change is to give the option to the developer to use or not certificates, am I right? Or is it to give the capability to pass an specific certificate for Kestrel to use?

**Comment by anurse** [comment]
This is about **client** certificates and is just a simplification. We already have [`HttpsConnectionAdaptorOptions.ClientCertificateValidation`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.https.httpsconnectionadapteroptions.clientcertificatevalidation?view=aspnetcore-2.2) which gives you the ability to provide a function to validate the client certificate. All we're looking at here is to add a second `bool` option (`AllowAnyClientCertificate`) that, if set, has the same behavior as if you set that function to `(_) => true` (i.e. always allow any cert through Kestrel).

The idea being that the Client Certificate Auth handler will do the validation.

**Comment by bcisnero** [comment]
Ok, I think I understand

**Comment by anurse** [comment]
Are you asking because you're interested in a PR @bcisnero ? We're probably actually going to get this done ourselves now because we want to land this preview 7

**Comment by bcisnero** [comment]
Yeah, that was my intention but still having trouble understanding the whole flow of this but I'll be very interested in seeing the solution so I can understand better all this and be able to contribute in the future,

**Comment by anurse** [comment]
Ok, no problem! Just checking before we went ahead and did it :).
