### ISSUE TITLE
How to get the sample code to work with Firefox?

### ISSUE THREAD

**Issue by wcswanson** [aspnet/AspNetCore#10365]

**Comment by wcswanson** [comment]
Contact Manager sample:
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2
I was able to get the code to run but I had no access to the management pages. I found out that Firefox would not allow @if (SignInManager.IsSignedIn(User)) (_LoginPartial.cshtml) to return turn. Several cookie settings were tried. Finally I tried the Microsoft Edge browser and it works as expected.

How do we set up Firefox to work with Aspnet Core?

**Comment by wcswanson** [comment]
After a long break, I found the answer:
Clearing cookies in Firefox: 
https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences
To enable all cookies, do one of the following: 
    • Select Custom and clear the Cookies check mark. 
    • Alternatively, select Standard to restore the default settings. 
To learn more about these settings, see the Content blocking article.

**Comment by blowdart** [comment]
That's odd. The only thing I can think of here is that you were running the sample over HTTP, and there had already been a cookie dropped when on HTTPS, at which point browsers can get confused.

**Comment by blowdart** [comment]
Without being able to reproduce there there's nothing we can do, so closing
