### ISSUE TITLE
SignalR: IHubClients GroupExcept

### ISSUE THREAD

**Issue by cheng93** [aspnet/AspNetCore#10367]
### Is your feature request related to a problem? Please describe.
I require the equivalent to `IHubClients.GroupExcept()` except instead of `excludedConnectionIds` I want to use a userId

### Describe the solution you'd like
a method I can use?
`GroupExceptUserId(string groupName, IReadOnlyList<string> excludedUserId)`

### Describe alternatives you've considered
Attempted to get connectionId via userId, but I don't think `IHubContext<THub, T>` provides that.

### Additional context
Note this could apply to other methods on `IHubClients`

**Comment by anurse** [comment]
Adding new "addresses" (i.e. methods you can use to target specific sets of clients) like this has a high cost since it has to be implemented by each backplane. We don't have plans to add this right now.

**Comment by cheng93** [comment]
Any workaround I can do?

Is it possible to keep a map of userId and connectionId?

**Comment by anurse** [comment]
Sort of, you can look at `Context.UserIdentifier` in the `OnConnectedAsync` method to get the UserID for a particular connection.
