### ISSUE TITLE
[Blazor] System.MissingMethodException: Constructor on type 'System.ComponentModel.ReferenceConverter' not found

### ISSUE THREAD

**Issue by redradist** [aspnet/AspNetCore#10379]
### Describe the bug
During parsing the Json using custom JsonConverter I have got the exception:
`System.MissingMethodException: Constructor on type 'System.ComponentModel.ReferenceConverter' not found`

### To Reproduce
ASP.NET Core 3.0.0-preview5-19227-01
Use deserializer like in this question on stackoverflow https://stackoverflow.com/questions/20995865/deserializing-json-to-abstract-class

### Expected behavior
Proper parsing custom abstract class

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @redradist.
What's most probably happening here is that your custom converter is being wiped by the linker. You can make sure that doesn't happen by configuring it manually as described here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.0
