### ISSUE TITLE
Static Html Helper Not Working

### ISSUE THREAD

**Issue by akash3456** [aspnet/AspNetCore#10377]
Hi, 
Can someone please tell me how the HtmlHelper class in Net Core MVC can be extended?
What I have tried is the following :- 
Create HtmlHelper Static Class. 
method :- public static string CreateDate(this HtmlHelper,String Message){}

method is not accessible from within the Razor view when i do:

Html.

the ViewImports does have the helper namespace in as well.

Kind Regards

**Comment by pranavkm** [comment]
The injected `HtmlHelper` is an `IHtmlHelper<T>` instance. You should update the extension method to target this type: `public static string CreateDate<TValue>(this IHtmlHelper<TValue,String Message){}`
