### ISSUE TITLE
German float number is not transformed correct

### ISSUE THREAD

**Issue by mprattinger** [aspnet/AspNetCore#10372]
I have an asp.net core 3 mvc app with an form, where a decimal number 38,5 for example is entered. When submitting the form, the controller gets the value in the model as 385.

### To Reproduce
asp.ne core 3.0 mvc app, german localization, model with a decimal property
 
### Expected behavior
The value should be transformed to 38.5

Thank you in advance
r Michael

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mprattinger** [comment]
Hi,

i have created a similar project and published it to github:

https://github.com/mprattinger/WebApplication8

Thanks for checking,
r Michael

**Comment by hishamco** [comment]
@mprattinger seems your sample doesn't add localization service!!

**Comment by hishamco** [comment]
Seem @mprattinger doesn't respond from awhile. @mkArtakMSFT what's the action needed here?

**Comment by mprattinger** [comment]
Sorry for my late response. I have added the request culture as it is shown in the docs now but i get the same result:

app.UseRequestLocalization(options =>
            {
                options.DefaultRequestCulture = new RequestCulture("de-AT");
            });

entering 38,5:
![image](https://user-images.githubusercontent.com/3177738/63799020-7bc76880-c90b-11e9-8d32-db407a23139c.png)

results in the model;

![image](https://user-images.githubusercontent.com/3177738/63799113-add8ca80-c90b-11e9-918a-55f426470b50.png)

regards Michael

**Comment by hishamco** [comment]
Could you please add a repo to reproduce the bug, before that please refer to troubleshooting section in docs? Because we 're facing a lot of scenarios that main reason is localization setup

**Comment by mprattinger** [comment]
Hi, the repo is https://github.com/mprattinger/WebApplication8

i will check if i can find something in the docs

**Comment by hishamco** [comment]
@mprattinger I'm not able to enter `3,85` in the field, the browser recognize the number with comma as invalid number

**Comment by mkArtakMSFT** [comment]
Sounds like the behavior here is browser specific. Unfortunately, we have seen similar issues where using `number` fields produces unexpected results. We have a work item planned for 5.0 which will reduce the pain in this area.
