### ISSUE TITLE
Should we be resetting [SecurityStamp] on removal of external login provider?

### ISSUE THREAD

**Issue by LindaLawton** [aspnet/AspNetCore#10386]
### Describe the bug / Question

Currently if a user has an external login provider (Google / Facebook) set up to their account and you want to remove it you fire. 

     var result = await _userManager.RemoveLoginAsync(user, account.LoginProvider, account.ProviderKey);

All good right?  Well I was digging around in the source and i noticed this line [#L993](https://github.com/aspnet/AspNetCore/blob/394eb3ca13c662e1c2288372e05f46fbcb149c16/src/Identity/Extensions.Core/src/UserManager.cs#L993)

    await UpdateSecurityStampInternal(user);

I am wondering if its really necessary to force a sign out everywhere when a user removes an external login from their account.

### To Reproduce

Add third party login to an existing user.  Check the [SecurityStamp] then remove it and [SecurityStamp] again.

**Comment by blowdart** [comment]
Yes. We make the assumption that removing an external login may be because that login is no longer under your control, so we want to logout everywhere to force cookies issued through that login flow are no longer valid.
