### ISSUE TITLE
How to apply .Net core claim-base authorization when using Istio end-user authentication

### ISSUE THREAD

**Issue by tungphuong** [aspnet/AspNetCore#10388]
Currently, I am using Istio end-user authentication; it is fine, don't need to use any authentication middleware from code but we can still authenticate JWT token from request and reject that request if the token is invalid (return 401).

However, it is out side of the service (implemented by .Net core). So User.Identity will be null and authorization step (by role base or claim base) always be fail. Because JWT token is not analyzed.

So, how can we apply claim-base authorization without any UseAuthentication middleware.

Thanks,

**Comment by blowdart** [comment]
You can't. 

You need some sort of middleware to construct the User object for it to be usable by authorization. If Istio passes information along in headers you'd be able to write middleware to use those, but it's going to be very custom.

**Comment by tungphuong** [comment]
Thanks @blowdart, currently, do we have any available middleware to analyze JWT token and construct the User object in .Net Core without validate back IDP? Or could you please share me the source code to build it?

**Comment by blowdart** [comment]
If the [jwt middleware](https://github.com/aspnet/AspNetCore/tree/master/src/Security/Authentication/JwtBearer) doesn't allow you to disable the metadata retrieval for signing keys, and I don't think it does, then it's probably the best place to start.

**Comment by tungphuong** [comment]
Thanks, let me try; maybe this is what I want to find.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
