### ISSUE TITLE
Global IgnoreAntiforgeryTokenAttribute doesn't disable ValidateAntiForgeryToken

### ISSUE THREAD

**Issue by tester346** [aspnet/AspNetCore#10384]
Tech: ASP.NET Core 2.1

I have an endpoint with those attributes:

	[HttpPost]
	[ValidateAntiForgeryToken]
	[Route("[controller]/[action]")]

When I applied ``IgnoreAntiforgeryTokenAttribute`` globally

	.AddMvc(opts =>
	{
        opts.Filters.Add(new IgnoreAntiforgeryTokenAttribute());
         // or
        opts.Filters.Add(typeof(IgnoreAntiforgeryTokenAttribute));
	})

The result is: It didn't disable that ``[ValidateAntiForgeryToken]``, but when I did something like that:

	[HttpPost]
	[ValidateAntiForgeryToken]
    [IgnoreAntiforgeryToken]
	[Route("[controller]/[action]")]

then everything worked fine.

Shouldnt globally applied attribute also disable it?

**Comment by pranavkm** [comment]
Similar discussions about this: https://github.com/aspnet/Mvc/issues/5863, https://github.com/aspnet/Mvc/issues/7795. You could specify an explicit order value when adding the ignore attribute to make this scenario work.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
