### ISSUE TITLE
Hosting client-side and server-side within the same host and switch dynamically

### ISSUE THREAD

**Issue by AlseinX** [aspnet/AspNetCore#10387]
Client-side and server-side blazor have both their benefits, and it would be better if we can host them together and determining what hosting model to use during the request.

The client-side javascript should have the ability to determine whether the browser supports wasm (maybe even whether the download speed is enough for downloading the big size of wasm mono within acceptable time cost, or any other possible switching policies) and if so, download and use client-side blazor, otherwise use server-side blazor.

Additionally, if possible, it could use server-side blazor as a temp implementation while the client-side blazor is downloading, and switch to client-side blazor when completed, and possibly there could be a way to transfer the states context from the server-side blazor application to the client side if the application is under some pattern which enables it to transfer safely.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AlseinX.
This is not something we plan to do in the near future.
