### ISSUE TITLE
[Question] - Blazor - setting up HttpClient default request headers

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#10381]
Blazor registers a singleton `httpclient` instance.

I'd like to ensure that instance has some default request headers added on application startup. What is the recommended way to achieve that?

1. Should I re-register my own singleton instance (overriding the one blazor registers)
2. Should I run some code on application startup to resolve the singleton instance and add my request headers?
3. Third options?

If 1 then how do I ensure I register my instance to mimic blazor's registration, just with my additional headers?
if 2 then where is the recommended place to put this app startup / initialisation logic for my blazor client app?

Many Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
You can go with both options you've suggested above. As for where is the best place for initialization logic - DI system has comprehensive docs https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2 showing how to do that.
