### ISSUE TITLE
SendFileAsync: bufferSize parameter

### ISSUE THREAD

**Issue by rosenbjerg** [aspnet/AspNetCore#10380]
### Is your feature request related to a problem? Please describe.
I am trying to stream large mediafiles using the `SendFileResponseExtensions` and encounter quite high CPU usage

### Describe the solution you'd like
I would like to be able to set the buffer size to use, instead of the hardcoded 1024 * 16.
So I could set it to something like 1MB, to reduce CPU usage (and perhaps improve streaming performance also)

### Describe alternatives you've considered
Right now I am using a modified version of the `SendFileAsyncCore` where I have added an optional `bufferSize` parameter:
`private static Task SendFileAsyncCore(HttpResponse response, string fileName, long offset, long? count, int bufferSize = 1024 * 16, CancellationToken cancellationToken = default)`

**Comment by anurse** [comment]
The wrapper is pretty simple and designed to cover a core case. You can always re-implement this yourself if you have more specific needs.

Closing as we don't have plans to add this parameter to the method.
