### ISSUE TITLE
Making HTTP requests from Blazor apps

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#10397]
There are a number of rough edges with the current support in Blazor for making HTTP requests:
- How to configure the HttpClient provided from DI? To add custom headers, etc. (https://github.com/aspnet/AspNetCore/issues/10381)
- Should we be using IHttpClientFactory?
- HttpClient is provided as a service for client-side Blazor but not server-side Blazor. Lots of folks are jumping through hoops to setup the same HttpClient service for server-side Blazor. Wat is our guidance here?
- What's the plan for the JSON helpers for HttpClient?

**Comment by guardrex** [comment]
I took a stab at this (admittedly more client-side than server-side at this time) ... but it's 50-50 .... 50% chance I did some good work there and a 50% chance that *a lightening bolt from the gods is going to hit me any second!* :zap:

[Blazor call web API topic with sample (aspnet/AspNetCore.Docs #12477)](https://github.com/aspnet/AspNetCore.Docs/pull/12477)

**Comment by guardrex** [comment]
With the invalid cert allowance (which might be bad to even show in a preview topic) ...

```xml
<ItemGroup>
  <PackageReference Include="System.Net.Http" Version="4.3.4" />
</ItemGroup>
```

```csharp
services.AddScoped(s =>
{
    var uriHelper = s.GetRequiredService<IUriHelper>();
    return new HttpClient
    {
        BaseAddress = new Uri(uriHelper.GetBaseUri()),
    };
});
```

```cshtml
@using System.Net.Http

@functions {
    private async Task MakeHttpClientRequest()
    {
        using (var httpClientHandler = new HttpClientHandler())
        {
            httpClientHandler.ServerCertificateCustomValidationCallback = 
                (message, cert, chain, errors) => true;
    
            using (var client = new HttpClient(httpClientHandler))
            {
                // Use client
            }
        }
    }
}
```

**Comment by mkArtakMSFT** [comment]
So the most important piece of work we'll be doing here is the last item on the above list:
> What's the plan for the JSON helpers for HttpClient?

**Comment by mkArtakMSFT** [comment]
Closing this as the only item left here will be tracked as part of https://github.com/aspnet/AspNetCore/issues/16929
