### ISSUE TITLE
Identity: the token cannot be unprotected after a certain time / duration

### ISSUE THREAD

**Issue by ehouarn-perret** [aspnet/AspNetCore#10399]
We have an ASP.NET Core application using identity to deal with user identification. There is something wrong that happens when the user wants to confirm his /her email.

In the `Startup.ConfigureServices(IServiceCollection services)`, the setup is achieved following this configuration:

```csharp
services  
.AddIdentity<ApplicationUser, IdentityRole>(options =>
            {
                options.SignIn.RequireConfirmedEmail = true;
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 6;
                options.Password.RequireLowercase = true;
                options.Password.RequireNonAlphanumeric = true;
                options.Password.RequireUppercase = true;
                options.User.RequireUniqueEmail = true;
                options.User.AllowedUserNameCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ@-._0123456789";
                options.Lockout.MaxFailedAccessAttempts = 5;
                options.Lockout.AllowedForNewUsers = true;
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                options.Tokens.ProviderMap.Add("Default", new TokenProviderDescriptor(typeof(IUserTwoFactorTokenProvider<ApplicationUser>)));
            })
            .AddEntityFrameworkStores<OurDataContext>()
            .AddDefaultTokenProviders();

        services.Configure<DataProtectionTokenProviderOptions>(options =>
        {
            options.Name = "Default";
            var tokenDurationActivationLinkString = ConfigurationManager.Instance["TokenDurationInHoursOfActivationAccountLink"];
            var tokenDurationActivationLink = double.Parse(tokenDurationActivationLinkString);
            options.TokenLifespan = TimeSpan.FromHours(tokenDurationActivationLink);
        });

```

When sending the email with the link to confirm the user email, the token is fetched this way:

```csharp
var token = await userContext.GenerateEmailConfirmationTokenAsync(user);
```

The link works fine but even though the duration validation of the link is set to 72 hours in production. The link appeared invalid.

When confirming the email (following the user clicking on link), the controller in charge of doing that, is basically leveraging the `ConfirmEmailAsync` method:

```csharp
 var result = await UserManager.ConfirmEmailAsync(user, token);
```

Turns out that `result.Succeeded` is `true` during one or two hours (the duration is actually a bit random, sometimes it returns `false` after only 45 minutes without any change or modifications on the user) and then starts to return `false`.

I inspected what `ConfirmEmailAsync` was doing, in essence:

```csharp

public virtual async Task<IdentityResult> ConfirmEmailAsync(
  TUser user,
  string token)
{
  this.ThrowIfDisposed();
  IUserEmailStore<TUser> store = this.GetEmailStore(true);
  if ((object) user == null)
    throw new ArgumentNullException(nameof (user));
  if (!await this.VerifyUserTokenAsync(user, this.Options.Tokens.EmailConfirmationTokenProvider, "EmailConfirmation", token))
    return IdentityResult.Failed(this.ErrorDescriber.InvalidToken());
  await store.SetEmailConfirmedAsync(user, true, this.CancellationToken);
  return await this.UpdateUserAsync(user);
}
```

and `VerifyUserTokenAsync` is implemented as such:

```csharp
public virtual async Task<bool> VerifyUserTokenAsync(
  TUser user,
  string tokenProvider,
  string purpose,
  string token)
{
  UserManager<TUser> manager = this;
  manager.ThrowIfDisposed();
  if ((object) user == null)
    throw new ArgumentNullException(nameof (user));
  if (tokenProvider == null)
    throw new ArgumentNullException(nameof (tokenProvider));
  if (!manager._tokenProviders.ContainsKey(tokenProvider))
    throw new NotSupportedException(Microsoft.Extensions.Identity.Core.Resources.FormatNoTokenProvider((object) nameof (TUser), (object) tokenProvider));
  bool result = await manager._tokenProviders[tokenProvider].ValidateAsync(purpose, token, manager, user);
  if (!result)
  {
    ILogger logger = manager.Logger;
    EventId eventId = (EventId) 9;
    object obj = (object) purpose;
    string userIdAsync = await manager.GetUserIdAsync(user);
    logger.LogWarning(eventId, "VerifyUserTokenAsync() failed with purpose: {purpose} for user {userId}.", obj, (object) userIdAsync);
    logger = (ILogger) null;
    eventId = new EventId();
    obj = (object) null;
  }
  return result;
}
```

By reflection I inspected that the `manager._tokenProviders[tokenProvider]` is of the type `DataProtectorTokenProvider<ApplicationUser>` hence its implementation of `ValidateAsync` is almost the actual meat of our problem:

```csharp
    public virtual async Task<bool> ValidateAsync(
      string purpose,
      string token,
      UserManager<TUser> manager,
      TUser user)
    {
      try
      {
        using (BinaryReader reader = new MemoryStream(this.Protector.Unprotect(Convert.FromBase64String(token))).CreateReader())
        {
          if (reader.ReadDateTimeOffset() + this.Options.TokenLifespan < DateTimeOffset.UtcNow)
            return false;
          string userId = reader.ReadString();
          if (userId != await manager.GetUserIdAsync(user) || !string.Equals(reader.ReadString(), purpose))
            return false;
          string str1 = reader.ReadString();
          if (reader.PeekChar() != -1)
            return false;
          if (!manager.SupportsUserSecurityStamp)
            return str1 == "";
          string str = str1;
          return str == await manager.GetSecurityStampAsync(user);
        }
      }
      catch
      {
      }
      return false;
    }
```

After many trials it seems that the issue is that at some point for **the very same token**, the line:

```csharp
this.Protector.Unprotect(Convert.FromBase64String(token))
```

fails at some point in time.

And this is way before even checking that the token contains a date time offset which is expired or not in regard to `UtcNow`.

[The implementation of `Protector.Unprotect` is one provided by the `KeyRingBasedDataProtector` class](https://github.com/aspnet/AspNetCore/blob/416d8cd1ea098eb643b4258247af3448f5545c32/src/DataProtection/DataProtection/src/KeyManagement/KeyRingBasedDataProtector.cs#L182) and is a bit Voodoo to me.

However it seems that the error occurs precisely [here](https://github.com/aspnet/AspNetCore/blob/416d8cd1ea098eb643b4258247af3448f5545c32/src/DataProtection/DataProtection/src/KeyManagement/KeyRingBasedDataProtector.cs#L244):

```csharp
IAuthenticatedEncryptor encryptorByKeyId = currentKeyRing.GetAuthenticatedEncryptorByKeyId(guid, out isRevoked);
if (encryptorByKeyId == null)
{
    this._logger.KeyWasNotFoundInTheKeyRingUnprotectOperationCannotProceed(guid);
    throw Error.Common_KeyNotFound(guid);
}

```

Considering that this is something I am not supposed to touch (internal classes of Identity) I am wondering why the same token would sometimes fail to be unprotected after a certain duration. It seems really voodoo to me. The only thing that seems not deterministic is in the [`KeyRingProvider`](https://github.com/aspnet/AspNetCore/blob/416d8cd1ea098eb643b4258247af3448f5545c32/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs#L142) but I am too sure how this is related to my issue.

**Comment by blowdart** [comment]
- What is your hosting environment?
- Has the app restarted when the failures start to happen?
- How is data protection configured? (If you aren't configuring it then your startup logs will show some information from data protection about the configuration it's using)

**Comment by ehouarn-perret** [comment]
@blowdart 
> * What is your hosting environment?
The issue happens when hosted on Windows 2016 Server with IIS + ASP.NET Core Bundle Module

> * Has the app restarted when the failures start to happen?
No, it has not.

> * How is data protection configured? (If you aren't configuring it then your startup logs will show some information from data protection about the configuration it's using)
Didn't configure it and seems that nothing shows up in our logs on Kibana... nor does it show anything if I am trying to run our solution locally.

**Comment by blowdart** [comment]
Lack of logs is interesting, because the startup logs definitely contain config information.

Did you configure IIS for dataprotection, as detailed in the [hosting documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.2#data-protection)?

**Comment by ehouarn-perret** [comment]
> Lack of logs is interesting, because the startup logs definitely contain config information.

@blowdart I am actually taking over a pre-existing legacy app, it seems there is not much logging done through the app. I am adding some.

In the meantime I kinda managed to fix the issue by adding a dataprotection storage (following the documentation [here](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.2&tabs=visual-studio)File system:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo(@"our-secret-path-goes-here"));
}
```
The configuration of the application pool related to this app.
![image](https://user-images.githubusercontent.com/11332444/58105371-ae641580-7be6-11e9-9c82-8dd3d390724b.png)

---

> Did you configure IIS for dataprotection, as detailed in the hosting documentation?
Afaik. not much on this app has been done (hence the lack of logs and many other things), so I would say a big "No"

**Comment by blowdart** [comment]
Ah there's some config to save to disk so you don't need the IIS config.

OK, that's the basics out of the way, so @HaoK can you take a look? Data Protection seems to be ok.

**Comment by ehouarn-perret** [comment]
@blowdart well, there was nothing until I brought the config to save to the disk (just to make this clear, there was not data protection before my last post).
That may explain the behaviour we experienced =/
I guess we can close the thread now.

**Comment by blowdart** [comment]
Ah :) So when the app restarts, or the app pool recycles, unless it was persisting to disk, or IIS was configured to use disk and registry the keys used get thrown away, which would have explained your behaviour.

I'm glad you have it working.
