### ISSUE TITLE
Native events for custom components return null in the HTML DOM

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#10398]
### Describe the bug
When create native events to the custom components and doesn’t use it in the sample side, it will bind null value in the HTML DOM.

I have created two native events to the FormInput (custom UI component).

![Annotation](https://user-images.githubusercontent.com/31958591/58039914-ba51c800-7b51-11e9-896c-050316830d31.png)

The onclick event alone bound in the sample side, but the onchange event is not used.

![Annotation1](https://user-images.githubusercontent.com/31958591/58039889-aa39e880-7b51-11e9-976d-a0b5d3a2afeb.png)

The onchange event is now bind as null in the HTML DOM. The same null value added to the DOM, when we not bind onclick event in the sample side.

![image001](https://user-images.githubusercontent.com/31958591/58039722-38fa3580-7b51-11e9-8a35-ada602095631.png)

Is there a way to bind all native events to the custom components? Or is this an issue need to be resolved?

**Comment by rynowak** [comment]
Fixed in: https://github.com/aspnet/AspNetCore/pull/10357
