### ISSUE TITLE
Updated to latest Blazor version 3.0.0-preview4-19216-03 and everything is broken.

### ISSUE THREAD

**Issue by arivera12** [aspnet/AspNetCore#10392]
I followed the instructions of this blog [https://devblogs.microsoft.com/aspnet/blazor-now-in-official-preview/](https://devblogs.microsoft.com/aspnet/blazor-now-in-official-preview/)

My solution was runnning and clean of errors on version 0.0.9 of blazor client side but when I upgraded to version 3.0.0-preview4-19216-03 I had about 230 errors I fixed them 1 by 1 then when I compiled the code again I received 580 new errors. Its been very frustrating trying to migrate this. Please help!

One thing I opened a new clean client side blazor solution from visual studio wizard and the default template has errors but compiles. As you just open one razor file all error pops up.

My issue seems to be related to this one [#9851](https://github.com/aspnet/AspNetCore/issues/9851)
I even having errors on the event callbacks like oninput, onclick, onscroll, etc.

I could share my solution but its pretty big. Is there anything I am missing from the migration steps?

I think the migration steps are incomplete there have to be some other things that needs to be done to have successful migration.

No highlight on blazor components. He doesnt seem to understand @typeparam
![image](https://user-images.githubusercontent.com/5600102/58027698-3bc04080-7ae7-11e9-864d-bc341d54ecd4.png)

![image](https://user-images.githubusercontent.com/5600102/58027786-614d4a00-7ae7-11e9-9cef-527584423f92.png)

![image](https://user-images.githubusercontent.com/5600102/58027521-ceacab00-7ae6-11e9-9694-d31629d72f0f.png)

![image](https://user-images.githubusercontent.com/5600102/58027565-e71cc580-7ae6-11e9-8382-ab08e4f17faa.png)

![image](https://user-images.githubusercontent.com/5600102/58026690-04509480-7ae5-11e9-9243-40a11e73259b.png)

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by danrald** [comment]
You should update to  Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01 but even with that. I am still getting the error, The type of namespace name 'App' cold not be found.  The last stable release was done in November. I think it is all around broke and they are just pulling our leg.

**Comment by arivera12** [comment]
This have been very frustrating my vs studio doesn't even recognize components, @typeparam, throws errors on every event like onclick, oninput, everything is broken. HttpClient doesnt seem to recognize it at all. I have wasted 1 week trying to fix everything but seems to be something else I can't just even think I had to fix 580 errors for migration when I already fixed 230 of them and after that I got 580 new errors.... it seems to be something else...

**Comment by arivera12** [comment]
I was using version 0.0.9 and everything was running fine and smooth and after upgrade BOOM nothing works.

**Comment by arivera12** [comment]
Ok here is the solution. You need to download the last available net core SDK. Upgrade you visual studio to the last available preview version. Then upgrade you blazor nuget dependencies. Then migrate the components namespace as required. Please follow this links below for more details.
[https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/)
[https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-5/](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-5/)

**Comment by danrald** [comment]
Sounds good, I'll give it a try when I get a chance. Funny thing is that I just downloaded the new version of VS2019 the other week. Nothing that involved core 3.0 was installed, actually nothing revolving around vs2019 at all. Everything was fresh. Doesn't work. Thanks!

**Comment by danroth27** [comment]
@danrald The latest stable release of VS2019 is not sufficient to get Blazor tooling working. You need the latest Visual Studio Preview (https://visualstudio.com/preview).

**Comment by arivera12** [comment]
@danrald the problem is that you gotta watch carefully the visual studio installer. It has 2 versions for downloading and installing **(stable and preview)**. **The stable version has bugs** and doesn't work at all. **You need to download the latest preview available**. In my case I am using enterprise version but community or developer version should look like this as well.
![image](https://user-images.githubusercontent.com/5600102/58119491-1a3b8380-7bd1-11e9-92ec-aeddffd1dab2.png)

**Comment by danrald** [comment]
@danroth27 @arivera12  Thanks fellas, I'll check it out.
