### ISSUE TITLE
Add support for `@attribute` directive

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10393]
This will enable a syntax for using existing attributes in `.razor` files

**Comment by SteveSandersonMS** [comment]
Example usage:

```cshtml
@attribute [Authorize]
```

**Comment by rynowak** [comment]
@ajaybhargavb @NTaylorMullen this is a new kind of token for directives. Keep in mind we will need to support all of the things that the attribute syntax in C# supports.
