### ISSUE TITLE
Blazor - bind and EventHandler are exclusive. We should be able to use both.

### ISSUE THREAD

**Issue by krystofzacek** [aspnet/AspNetCore#10391]
For no obvious reason I cannot use bind-value-valuechanged and ValueChanged handler  at the same time.

Example:

<ListBox bind-selectedindex="@selectedIndex" SelectedIndexChanged="@OnSelectionChanged" />

This is currently impossible i Blazor. I can only have either bind or EventHandler. It should be possible to have both.

Regards.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @krystofzacek.
This is not supported at the moment. If you want to set event-handler directly, you can't use `bind-`.
