### ISSUE TITLE
Flurl not working, HttpClient working

### ISSUE THREAD

**Issue by imtrobin** [aspnet/AspNetCore#10417]
Hi , I added Flurl as a library dependency in a new hello world project. Httpclient works, but flurl does not. There is no error warning.

        public static async Task <string>   TestGetString ()
        {
            // This does not work Flurl
            // return await "https://www.mocky.io/v2/5185415ba171ea3a00704eed".GetStringAsync ();

          // this works fine.
            string URL = "https://www.mocky.io/v2/5185415ba171ea3a00704eed";
            HttpResponseMessage response = await client.GetAsync (URL);
            HttpContent content = response.Content;
            return await content.ReadAsStringAsync ();
        }

1. Run project. Go to Mocky Test page
2. Note "Status" is empty, no error in console. If switch NetworkSystem.TestGetString to Httpclient, "Status" will show "Hello World"

Project:
https://filedn.com/l3TGy7Y83c247u0RDYa9fkp/temp/blazor/testblazor.zip

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010067 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @imtrobin.
As pointed out in the referenced issue, there's a solution provided in `StackOverflow` already: https://stackoverflow.com/questions/52522004/blazor-0-6-0-wipes-flurl-compatibility/52526415#52526415

There is, unfortunately, nothing we can do at the moment to change this.

**Comment by imtrobin** [comment]
I applied the fix in the link, it works on simple mocky case , but not when I use azure api

     return await "https://www.mocky.io/v2/5ceb407f3300008c547c399e".GetStringAsync (); // this works

     return await  "https://XXX.azurewebsites.net:443/api/XXX/XXX"
                          .WithHeader ("x-functions-key", "XXX")
                        .GetStringAsync ();

     return await "https://XXX.azurewebsites.net:443/api/XXX/XXX?code=XXX"

I can run this in postman and webbrowser fine
https://XXX.azurewebsites.net:443/api/XXX/XXX?code=XXX

**Comment by imtrobin** [comment]
I think it is a COR issue with azure function setup, Flurl is working fine.
