### ISSUE TITLE
Not enough memory error on HubConnection.StartAsync()

### ISSUE THREAD

**Issue by alexiordan** [aspnet/AspNetCore#10418]
On a Windows 10 Iot Core, in UWP BackgroundTask app, using Microsoft.AspNetCore.SignalR.Client v.1.1.0

When trying to connect (` await HubConnection.StartAsync()`) I encounter following error.
It doesn't happen every time and I do not know how to reproduce it.
However when it happens, it makes the entire system useless.

Maybe some of you know about this... Is this a known issue or something?

  | LogMessageTemplate_s | Failed to start connection. Error getting negotiation response from '{Url}'.
-- | -- | --
  | LogProperties_Url_s | https://[myhub].service.signalr.net/client/?hub=[myhub]&asrs.op=%2F[myFunc]
  | LogException_ClassName_s | System.IO.InvalidDataException
  | LogException_RemoteStackIndex_d | 0
  | LogException_StackTraceString_s | at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(Stream content)    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger)    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri)    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat)    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat)    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)    at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)    at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)    
  | LogProperties_ClientConnectionId_s | 2cERwxyEIvOiZEvoWTTPgQ
  | LogException_Message_s | Invalid negotiation response received.
  | LogException_InnerException_ClassName_s | System.Exception
  | LogException_InnerException_Message_s | Not enough memory resources are available to process this command. (Exception from HRESULT: 0x80070008)
  | LogException_InnerException_StackTraceString_s | at Windows.Storage.Streams.IInputStream.ReadAsync(IBuffer buffer, UInt32 count, InputStreamOptions options)    at System.IO.WinRtToNetFxStreamAdapter.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state, Boolean usedByBlockingWrapper)    at System.IO.WinRtToNetFxStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count)    at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)    at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)    at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)    at System.IO.StreamReader.ReadSpan(Span`1 buffer)    at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)    at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)    at Newtonsoft.Json.JsonTextReader.ParseValue()    at Newtonsoft.Json.JsonTextReader.Read()    at Microsoft.AspNetCore.Internal.JsonUtils.CheckRead(JsonTextReader reader)    at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(Stream content)
  | LogException_InnerException_RemoteStackIndex_d | 0
  | LogException_InnerException_HResult_d | -2,147,024,888
  | LogException_InnerException_Source_s | Windows
  | LogException_Source_s | Microsoft.AspNetCore.Http.Connections.Common
  | LogException_HResult_d | -2,146,233,087
  | LogProperties_EventId_Id_d | 10
  | LogProperties_EventId_Name_s | ErrorWithNegotiation
  | Timestamp_t [UTC] | 2019-05-21T09:31:21.333Z
  | LogLevel_s | Error

**Comment by anurse** [comment]
I'm not familiar with a specific issue like this.

> Not enough memory resources are available to process this command. (Exception from HRESULT: 0x80070008)

Do you have any data about the memory usage of the process at the time this error occurs? If you are running low on memory this would occur and anything that allocates could throw. It could just be that SignalR is what happens to be allocating when you are in a low-memory situation.

**Comment by alexiordan** [comment]
Currently I don't have such information. I have some memory usage logging
for some scenarios but I didn't expect it here. I will log memory usage for
this scenario also and come back when it will happen again. Given memory
usage querying will not fail on exception handling.

mar., 21 mai 2019, 19:12 Andrew Stanton-Nurse <notifications@github.com> a
scris:

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by halter73** [comment]
@anurse I have a suspicion of what may have happened here. If the response to a long-polling/SSE connection is an error page that doesn't contain the record separator byte (0x1e) the client could OOM.

I think the action item here is at all the callers of [TextMessageParser.TryParseMessage()](https://github.com/aspnet/AspNetCore/blob/08ed1afbbc1d1e11115eafcf4bd2c771c00ffd90/src/SignalR/common/Shared/TextMessageParser.cs#L13) and ensure they are restricting the message size if and where it makes sense. It might be helpful to add an optional maxLength parameter to TryParseMessage itself and have it throw if the first record separator byte cannot be found after reading maxLength bytes.

**Comment by alexiordan** [comment]
I only use websockets on such clients. I haven't encountered again this issue. If it happens again I will post, but currently I have no news.

**Comment by anurse** [comment]
> If the response to a long-polling/SSE connection is an error page

But the status code would be `500` there right?

**Comment by halter73** [comment]
Good point. The server probably isn't returning an error page then.

**Comment by anurse** [comment]
Resolved some confusion offline. Closing for now and if @alexiordan or anyone else gets a further repro we can investigate further.
