### ISSUE TITLE
JwtBearerHandler IssuerSigningKeys

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#10419]
### Describe the bug
The JwtBearerHandler seems to attempt to validate issuer signing keys regardless of the JwtBearerOptions settings having no IssuerSigningKeys and the ValidateIssuerSigningKeys set to false. 

### To Reproduce
set the JwtBearerOptions.TokenValidationParameters
                ValidateActor = false,
                ValidateAudience = false,
                ValidateIssuerSigningKey = false,
                ValidateLifetime = false,
                ValidateTokenReplay = false,
                ValidateIssuer = false,

                RequireExpirationTime = false,
                RequireSignedTokens = false,

which results in the AuthenticateResult Fail 'No SecurityTokenValidator available for token:'

### Expected behavior
A token should be allowed regardless of signing key

**Comment by blowdart** [comment]
@brentschmaltz is this expected? It seems off, considering the disabling of validateissuersigningkey

**Comment by brentschmaltz** [comment]
@blowdart we fixed this issue in 5.5.0
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/972
However, the error message seems a bit off.

**Comment by grahamehorner** [comment]
@blowdart @brentschmaltz just to verify we have a requirement where the WebAPI will be receiving request with a JwtBearer token that has been signed, but **we don't wish to validate the issuers signing signature**, so in terms of the options I would expect the following behaviour : -

**1. ValidateIssuerSigningKey = false, RequiresSignedTokens = true**
A token must have been signed, however we **don't** care about validation of the signing key;
IssuerSigningKey(s) may be null

**2. ValidateIssuerSigningKey = false, RequiresSignedTokens = false**
A token may have been signed, however we **don't** care about validation of the signing key;
IssuerSigningKey(s) may be null

**3. ValidateIssuerSigningKey = true, RequiresSignedTokens = false**
A token **may have been signed** and **we do care** about validation of the signing key **if the 
IssuerSigningKey(s) are non-null**

**4. ValidateIssuerSigningKey = true, RequiresSignedTokens = true**
A token **must have been signed** and we do care about validation of the signing key, **IssuerSigningKey(s) must be non-null**

FYI, are use case is based around having a frontend API gateway that can offload some of the JWT validation with dynamic loading of keys etc. from secured gateway services etc.

however when we have configured the JwtBeareOptions as above authentication fails unless we populate the IssuerSigningKey(s) regardless of the ValidateIssuerSigninKey/RequireSignedTokens value.

Q: is this a use case that was considered, and/or you think should be considered given the JwtBearerOptions seems to that suggest that this can be a supported scenario?

**Comment by brentschmaltz** [comment]
@grahamehorner i think those 4 cases are how it should work. I believe that our 5.5.0 release will work as you described.

**Comment by anurse** [comment]
Closing, since the issue is in the IdentityModel library. Installing version 5.5.0 or higher of that library will resolve the issue. We are looking at updating the version we reference but not in the short-term.

**Comment by grahamehorner** [comment]
@anurse @brentschmaltz do have you a timescale to when v5.5.0 of the IdentityModel is to be release/published on nugget ?

**Comment by brentschmaltz** [comment]
@grahamehorner our scheduled 5.5.0 release was 5/31, it looks like we will delay a couple of days to finish up a couple of items.
