### ISSUE TITLE
Question - How to update Login form and other page from Angular SPA Auth Individual

### ISSUE THREAD

**Issue by bastienlemaitre** [aspnet/AspNetCore#10416]
Hi,
How to update Login form and other page from Angular SPA Auth Individual ?
I've tried to recreate same page in same folder  Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal.LoginModel but it doesn't override it.

Any idea ? 
Thanks

**Comment by blowdart** [comment]
@javiercn this should be overridable shouldn't it?

**Comment by javiercn** [comment]
Yep, you need to put the page on the same physical path as the view.
/Areas/Identity/Account/Login.cshtml for example.

**Comment by javiercn** [comment]
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio#override-views-partial-views-and-pages

**Comment by bastienlemaitre** [comment]
![image](https://user-images.githubusercontent.com/11610748/58104838-c1c2b100-7be5-11e9-84c1-916c8c48e1bb.png)

It does not seem to work...
I've to had V4, or anything else ?
Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal.LoginModel

**Comment by javiercn** [comment]
Just to make sure, you are trying to override the view on `/Identity/Account/Login`, are you?

**Comment by bastienlemaitre** [comment]
Yes, this one
![image](https://user-images.githubusercontent.com/11610748/58106177-f6d00300-7be7-11e9-9686-68972ccb240a.png)

**Comment by javiercn** [comment]
@bastienlemaitre Just to discard human error (this is tricky to do by hand) have you tried using the scaffolder to scaffold the specific view?

**Comment by bastienlemaitre** [comment]
![image](https://user-images.githubusercontent.com/11610748/58106756-e8361b80-7be8-11e9-8c5e-e6ad5fb7f02b.png)

Yes, and strangely I do not see my word in French ;)

**Comment by bastienlemaitre** [comment]
How can I do that ?

**Comment by javiercn** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio

**Comment by bastienlemaitre** [comment]
It works, thanks !
