### ISSUE TITLE
[Helix] enable Microsoft.AspNetCore.Blazor.Build.Test.FindsReferenceAssemblyGraph_ForStandaloneApp

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#10426]
src/Components/Blazor/Build/test/RuntimeDependenciesResolverTest.cs

Microsoft.AspNetCore.Blazor.Build.Test.FindsReferenceAssemblyGraph_ForStandaloneApp is currently disabled in Helix because it has a dependency on the organization of source code.

See https://github.com/aspnet/Extensions/issues/1697 for the recommended fix.

**Comment by mkArtakMSFT** [comment]
Closing this as there is a separate issue tracking the same thing.
