### ISSUE TITLE
Partial(string viewName, object model) not working when use in Razor Page

### ISSUE THREAD

**Issue by avalon1610** [aspnet/AspNetCore#10438]
### Describe the bug
Razor Page Code like below (reference to: [https://www.learnrazorpages.com/razor-pages/ajax/partial-update](https://www.learnrazorpages.com/razor-pages/ajax/partial-update))
```c# 
public class AjaxPartialModel : PageModel
{
    private ICarService _carService;
    public AjaxPartialModel(ICarService carService)
    {
        _carService = carService;
    }
    public List<Car> Cars { get; set; }
    public void OnGet()
    {
    }
    public PartialViewResult OnGetCarPartial()
    {
        Cars = _carService.GetAll();
        return Partial("_CarPartial", Cars);
    }
}
```
will not work. method `Partial` will throw an exception like:
> InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'List< Car >', but this ViewDictionary instance requires a model item of type 'AjaxPartialModel '.

so I checked the Partial's source code, found:
```c#
public virtual PartialViewResult Partial(string viewName, object model)
{
      ViewContext.ViewData.Model = model; 
// here ViewContext is member of AjaxPartialModel, so it accept only model of type AjaxPartialModel, 
// so I think here we need create a new ViewDataDictionary to accept model in parameter.

      return new PartialViewResult
      {
            ViewName = viewName,
            ViewData = ViewContext.ViewData
      };
}
```
maybe this method should change to:
```c#
public virtual PartialViewResult Partial<T>(string viewName, T model)
{
      return new PartialViewResult
      {
            ViewName = viewName,
            ViewData = new ViewDataDictionary<T>(ViewData, model);
      };
}
```
I had not check this implementation in depth, so maybe something is wrong above. 
Appreciate further details

### To Reproduce
1. Using this version of ASP.NET Core 2.2

**Comment by js6pak** [comment]
I have same problem (but on .net core 3.0)
For now i use this hacky solution:
```cs
// razor page (HelperGenerator from injection)
HelperGenerator.HtmlHelper(ViewData, TempData).Partial("_BuyModalPartial", selectedProduct).ToHtmlString()
```

```cs
// some static class
public static string ToHtmlString(this IHtmlContent htmlContent)
{
    using (var writer = new StringWriter())
    {
        htmlContent.WriteTo(writer, HtmlEncoder.Default);
        return writer.ToString();
    }
}
```
    
```cs
public class HelperGenerator
{
    private readonly IHtmlGenerator _htmlGenerator;
    private readonly ICompositeViewEngine _compositeViewEngine;
    private readonly IModelMetadataProvider _modelMetadataProvider;
    private readonly IViewBufferScope _viewBufferScope;
    private readonly IActionContextAccessor _actionContextAccessor;
    private readonly HtmlHelperOptions _htmlHelperOptions;

    public HelperGenerator(IHtmlGenerator htmlGenerator, ICompositeViewEngine compositeViewEngine, IModelMetadataProvider modelMetadataProvider, IViewBufferScope viewBufferScope, IActionContextAccessor actionContextAccessor, IOptions<MvcViewOptions> options)
    {
        _htmlGenerator = htmlGenerator;
        _compositeViewEngine = compositeViewEngine;
        _modelMetadataProvider = modelMetadataProvider;
        _viewBufferScope = viewBufferScope;
        _actionContextAccessor = actionContextAccessor;
        _htmlHelperOptions = options.Value.HtmlHelperOptions;
    }

    public IHtmlHelper HtmlHelper(ViewDataDictionary viewData, ITempDataDictionary tempData)
    {
        var helper = new HtmlHelper(_htmlGenerator, _compositeViewEngine, _modelMetadataProvider, _viewBufferScope, HtmlEncoder.Default, UrlEncoder.Default);
        var viewContext = new ViewContext(_actionContextAccessor.ActionContext,
            new FakeView(),
            viewData,
            tempData,
            TextWriter.Null,
            _htmlHelperOptions);
        helper.Contextualize(viewContext);
        return helper;
    }
    private class FakeView : IView
    {
        public string Path => "View";

        public Task RenderAsync(ViewContext context)
        {
            return Task.FromResult(0);
        }
    }
}
```

```cs
//Startup.cs
services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();
services.AddTransient<HelperGenerator>();
```

**Comment by js6pak** [comment]
The problem is [here](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.RazorPages/src/PageModel.cs#L1634), it should create new ViewData not edit current one

**Comment by jerriep** [comment]
I am also running into this one on 2.2

**Comment by devtalex** [comment]
I am facing the same problem using VS 2017 and Core 2.2.
As I understand it is fixed, so please let me know what should I do to use Partial Views with Razor pages. Currently my project is suspended.

**Comment by jerriep** [comment]
@devtalex The following works for me in 2.2

```
public async Task<IActionResult> OnPostAsync()
{
    var result = await someAsyncStuff();

    var modelMetadataProvider = new EmptyModelMetadataProvider();
    var viewData = new ViewDataDictionary(modelMetadataProvider, new ModelStateDictionary()) {Model = result};
    return new PartialViewResult {ViewName = "_YourPartialViewName", ViewData = viewData};
}
```

**Comment by devtalex** [comment]
> @devtalex The following works for me in 2.2
> 
> ```
> public async Task<IActionResult> OnPostAsync()
> {
>     var result = await someAsyncStuff();
> 
>     var modelMetadataProvider = new EmptyModelMetadataProvider();
>     var viewData = new ViewDataDictionary(modelMetadataProvider, new ModelStateDictionary()) {Model = result};
>     return new PartialViewResult {ViewName = "_YourPartialViewName", ViewData = viewData};
> }
> ```

Thank you for feedback, but it still does not work - the problem is that the whole main page (main Index page) is loaded into designated DIV tag, instead of Partial View page content.
See the details below, maybe you will find something wrong.

Razor Index.cshtml `<button type="button" id="testajaxcall">
    testajaxcall
</button>
<div id="containera"></div>

        $(function () {
            $('#testajaxcall').click(function () {
                console.log("testajaxcal = TEST");

                ///ajax call
                $.ajax({
                    url: '/Payments?handler=TestAjaxCal',
                    type: 'GET',
                    cache: false,
                }).done(function (result) {
                    $('#containera').html(result);
                });
                ////
            });            });
`
_Partial2.cshtml
`
@model List<Project.Models.Department>

<h1>List of Departments</h1>
<ul>
    @foreach (var item in Model)
    {
        <li>@item.DepartmentName</li>
    }
</ul>
`

Name Handler in Razor Model file:
`
        public PartialViewResult OnGetTestAjaxCall()
        {            
            var result = new List<Department>();
            long depid = 5;
            result = _context.Department.Where(o =>
                         o.DepartmentID == depid
                ).ToList();

            var modelMetadataProvider = new EmptyModelMetadataProvider();
            var viewData = new ViewDataDictionary(modelMetadataProvider, new ModelStateDictionary()) { Model = result };

            return new PartialViewResult { ViewName = "_Partial2", ViewData = viewData };
        }
`

**Comment by jerriep** [comment]
Seems you have a spelling error. In the AJAX call, you are calling the handler `TestAjaxCal`. But your handler in the C# code is named `OnGetTestAjaxCall` - in other words one `l` vs 2 'l`s

Fix the handler in the AJAX to be named `TestAjaxCall`

In either case, your problem is not related to this particular GitHub issue. If my suggestion above does not work for you, then I suggest you rather seek help at a place like StackOverflow.

**Comment by devtalex** [comment]
> Seems you have a spelling error. In the AJAX call, you are calling the handler `TestAjaxCal`. But your handler in the C# code is named `OnGetTestAjaxCall` - in other words one `l` vs 2 `l`s
> 
> Fix the handler in the AJAX to be named `TestAjaxCall`
> 
> In either case, your problem is not related to this particular GitHub issue. If my suggestion above does not work for you, then I suggest you rather seek help at a place like StackOverflow.

Thank you, https://github.com/jerriep Jerrie, now it works!
