### ISSUE TITLE
SignalR on docker issue

### ISSUE THREAD

**Issue by ArkadiuszNET** [aspnet/AspNetCore#10440]
Hi guys, I have a problem with signalR on docker containers placed at Kubernetes Rancher.
My configuration working well on local environment and also when I build up my containers locally, but when I push my containers to further environments, I get "Error during WebSocket handshake: Unexpected response code: 500" and "Error: Failed to start the connection: null". 

My client is angular app and using package "@aspnet/signalr" and backend working on 
"Microsoft.AspNetCore.SignalR" v1.1.0

Client send request to ocelot and then is redirected to notifier container where is signalR.

My configuration:
https://gist.github.com/ArkadiuszNET/da4112e1b90f65091da62f7486ecf648

**Comment by BrennanConroy** [comment]
500 is an internal server error. You should figure out if its the server returning the 500 (meaning its not running correctly), or if ocelot is returning the 500.

**Comment by davidfowl** [comment]
Assuming logging is configured, do you have server logs?

**Comment by ArkadiuszNET** [comment]
Logs from ocelot:
[Logs.txt](https://github.com/aspnet/AspNetCore/files/3211766/Logs.txt)

Ocelot config:
[ocelot.txt](https://github.com/aspnet/AspNetCore/files/3211782/ocelot.txt)

**Comment by BrennanConroy** [comment]
"Downstream url is ws://notifier/notify?accesstoken=[token]"
"Unable to connect to the remote server"

Looks like an issue with the server? Can you capture the servers logs and verify it can be connected to?

**Comment by ArkadiuszNET** [comment]
Logs from Gateway (where is ocelot) and notifier (where is signalR).
[LogsGatewayAndNotifier.txt](https://github.com/aspnet/AspNetCore/files/3215712/LogsGatewayAndNotifier.txt)

It's looks like that error was return from notifier and further in gateway we have "Unable to connect to the remote server".

**Comment by BrennanConroy** [comment]
It looks like your server returned a 403, which is the "Forbidden" status code.

That usually means you were successfully authenticated but then you weren't authorized to access the resource. So your token is valid, but you don't have permission to access the thing you want.

How are you handling auth in your app? Is it possible for you to share your app?

**Comment by ArkadiuszNET** [comment]
I also removed authentication and tried connect to signalR without success.
In that case logs looks the same without log about "token validation".

There is extension method which retrieve token from request:
[IdentityServerExtenstion.txt](https://github.com/aspnet/AspNetCore/files/3222451/IdentityServerExtenstion.txt)
[startup.txt](https://github.com/aspnet/AspNetCore/files/3222473/startup.txt)


I thoughts about whether it's necessary to enable websockets on docker containers?

**Comment by BrennanConroy** [comment]
>I also removed authentication and tried connect to signalR without success.

Did you still get a 403 in the server logs? Does your Hub have the `[Authorize]` attribute on it?

Could you change the server-side log level to at least Debug and provide the logs when the connection fails.

**Comment by ArkadiuszNET** [comment]
Hi guys! I finally resolved my problem when introduced additional traefik routing rules for my containers.
I introduced traefik.http.frontend.rule and traefik.wss.frontend.rule for my apiGateway and notifier containers, where that rules contains address where that containers are available.
Thank for your time and help!
