### ISSUE TITLE
Blazor in combination with Microsoft's Fluent Design

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/AspNetCore#10442]
[Fluent Design](https://www.microsoft.com/design/fluent/#/web) was all over the place at Build 2019. I'm wondering if Microsoft will port the Fabric Library to Blazor, to create a universal design system / component library for the web in C#. In a later stage we can wrap our Blazor clients in an elektron shell and have a universal way to create web AND native apps using a common design language and components. If Microsoft would start/back the community in this effort, the adoption of Blazor will drastically increase. 

Some people were already looking into Fabric @galvesribeiro for example. but the CSS-in-JS makes it pretty hard to share some styling from the React Fabric repository.

**Comment by galvesribeiro** [comment]
Yeah, the major issue we had in the past, was the fact that the license was really restrictive to MSFT internal use or (in case of Fabric) to Office-based apps.

Now that those restrictions were lifted, I'm going to port first all components from https://www.microsoft.com/design/fluent/#/web to Blazor. 

Would be awesome if we could have it on a aspnet/AspNetCore repo, but if that isn't possible no problem... We will keep them on BlazorExtensions like verything else...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vertonghenb.
This is really something community can own and do great job.

**Comment by KalyanChanumolu-MSFT** [comment]
Related Thread [here](https://github.com/aspnet/AspNetCore/issues/11229)
