### ISSUE TITLE
Authorize from controller is used instead from method

### ISSUE THREAD

**Issue by konradsikorski** [aspnet/AspNetCore#10443]
### Descriprion

We use two kind of authentications:

- Bearer
- Custom: ApiKey (we check in header some value)

We want to be able to mark action as following:

- Allow only users authenticated with Bearer
- Allow only users authenticated with ApiKey
- Allow users authenticated with Bearer or ApiKey

In general it works but if we mark Controller (like in the exampe below) with [Authorize(Policy=Bearer)] then methods marked with [Authorize(Policy=ApiKey)] can by called also by users authenticated with Bearer only.

### Sample code
Authentication and authorization configuration:

    services
    .AddAuthentication()
        .AddJwtBearer(AuthSchemas.Bearer, jwtOptions =>
        {
            jwtOptions.Authority = $"https://login.microsoftonline.com/tfp/{Configuration["AzureAdB2C:Tenant"]}/{Configuration["AzureAdB2C:Policy"]}/v2.0/";
            jwtOptions.Audience = Configuration["AzureAdB2C:ClientId"];
        })
     .AddScheme<ApiKeyOptions, ApiKeyHandler>(AuthSchemas.ApiKey, null);

    services.AddAuthorization(options =>
    {
        options.AddPolicy(AuthPolicies.ApiKey, new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .AddAuthenticationSchemes(AuthSchemas.ApiKey)
            .Build());

        options.AddPolicy(AuthPolicies.Bearer, new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .AddAuthenticationSchemes(AuthSchemas.Bearer)
            .Build());

        options.AddPolicy(AuthPolicies.BearerOrApiKey, new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .AddAuthenticationSchemes(AuthSchemas.Bearer, AuthSchemas.ApiKey)
            .Build());
    });

My ApiKeyHandler:

    public class ApiKeyHandler : AuthenticationHandler<ApiKeyOptions>
    {
        private readonly ApiKeyConfiguration _config;
        private readonly ILogger _log;

        public ApiKeyHandler(
            IOptionsMonitor<ApiKeyOptions> options, 
            ILoggerFactory logger, 
            UrlEncoder encoder, 
            ISystemClock clock,
            IOptions<ApiKeyConfiguration> config) 
            : base(options, logger, encoder, clock)
        {
            _config = config.Value;
            _log = logger.CreateLogger(GetType().FullName);
        }

        protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
        {
            const string header = "Authorization";
            
            if (!Request.Headers.ContainsKey(header))
            {
                return AuthenticateResult.NoResult();
            }

            if (!AuthenticationHeaderValue.TryParse(Request.Headers[header], out var headerValue))
            {
                return AuthenticateResult.NoResult();
            }

            if (!Scheme.Name.Equals(headerValue.Scheme, StringComparison.OrdinalIgnoreCase))
            {
                return AuthenticateResult.NoResult();
            }

            if (_config.Value != headerValue.Parameter)
            {
                _log.LogWarning("ApiKey authentication failed.");
                return AuthenticateResult.Fail("Invalid api key value.");
            }

            var claims = new[] 
            {
                new Claim(ClaimTypes.Name, "api-user"),
            };
            var identity = new ClaimsIdentity(claims, Scheme.Name);
            var principal = new ClaimsPrincipal(identity);
            var ticket = new AuthenticationTicket(principal, Scheme.Name);

            _log.LogDebug("ApiKey authorization suceed.");
            return AuthenticateResult.Success(ticket);
        }
    }

My Controller:

    [Authorize(Policy = AuthPolicies.Bearer)]
    [ApiController]
    public partial class MyController : Controller
    {		
        [HttpGet("GetOnlyBearer")]
        public async Task<IActionResult> GetOnlyBearer()
        {
            return Ok();
        }
		
        [Authorize(Policy = AuthPolicies.ApiKey)]
        [HttpGet("GetOnlyBearer")]
        public async Task<IActionResult> GetOnlyApiKey()
        {
            return Ok();
        }
		
        [Authorize(Policy = AuthPolicies.BearerOrApiKey)]
        [HttpGet("GetBearerOrApiKey")]
        public async Task<IActionResult> GetBearerOrApiKey()
        {
            return Ok();
        }
    }
### To Reproduce
Calling method "GetOnlyApiKey" by user authenticated only with Bearer is allowed

### Expected behavior
Calling method "GetOnlyApiKey" by user authenticated only with Bearer should not be allowed

**Comment by pranavkm** [comment]
cc @HaoK \ @blowdart

**Comment by HaoK** [comment]
This is most likely related to this https://github.com/aspnet/AspNetCore/issues/9779

**Comment by anurse** [comment]
Closing as we believe this is a duplicate of #9779. It is fixed in 3.0.0-preview6 (which is releasing soon) and we are backporting to an upcoming 2.1/2.2 patch.
