### ISSUE TITLE
Add response transformer to SPA middleware

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/AspNetCore#10446]
I am trying to inject data at runtime into the response body of the request that serves the `index.html` file as my SPA.

### Describe the solution you'd like
A callback function that the SpaServices middleware calls that allows processing/transformation of the response body **before** it has been written to the `HttpResponse` object.

```cs
services.AddSpaStaticFiles(configuration =>
{
    configuration.RootPath = "ClientApp/build";
    configuration.ResponseTransformers.Add((context, body) => {
        body.Replace("__SERVER_DATA__", "foo");
        body.Replace("__AUTHENTICATED__", context.User.Identity.IsAuthenticated);
        body.Replace("__RequestVerificationToken", /* ... */);
    });
});
```

### Describe alternatives you've considered
Using a `app.Use()` middleware that modifies the stream of `Response.Body` after it has been written, but modifying a `Stream` is rather clunky. 

### Additional context
https://facebook.github.io/create-react-app/docs/title-and-meta-tags#injecting-data-from-the-server-into-the-page
https://github.com/aspnet/Templating/issues/690
https://github.com/aspnet/Templating/issues/676

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vanillajonathan.
SpaServices is not a priority area for us at the moment so we plan to make no feature additions to that area in the near future.
