### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#10452]
In Blazor we don't currently have an equivalent to sections in MVC/Razor Pages. We should discuss what if anything we need to handle the relevant scenarios, like enabling a component to add scripts  to the bottom of the page.

**Comment by Andrzej-W** [comment]
Hopefully you will be able to resolve this issue #9128 which was closed as "problematic".

**Comment by AmarjeetBanwait** [comment]
It will be good if we implement similer to @code{ } directive
eg.
`@style{ }`
`@code{ }`
`@script{ }`

and for external files
`@styleUrl` and `@scriptUrl`

**Comment by Rauce** [comment]
> ...like enabling a component to add scripts to the bottom of the page.

Also applies to adding Bootstrap modals, which to work correctly need to be direct children of the <body> html tag.

Often the @Body of a layout component is nested in a hierarchy of tags below <body>, so including a modal in a Page (which is desired if the modal contains a form with binding/event hookups to the Page code) prevents it from working correctly.

**Comment by mkArtakMSFT** [comment]
We're going to provide some of this functionality as part of https://github.com/aspnet/AspNetCore/issues/10450
The rest doesn't seem to be much value-add.
