### ISSUE TITLE
Razor Pages and MapWhen

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#10469]
### Describe the bug
I'm trying to use two seperate instances of the `RazorPages` middleware, each instance is in it's own branch of the middleware pipeline, created using `Map`. I am getting 404's ~~and I am not sure why.~~ due to multiple seperate issues at play - which I have linked.

### To Reproduce
1. Repro here: https://github.com/dazinator/DemoRazorPagesMapped
2. Run the project with VS2019 preview. I've also included the `startup.cs` below.
3. When browsing the site, I just get 404's.

### Expected behavior
I would expect when browsing the site on path of `/t1` for the Razor Pages middleware in that branch to serve me razor pages from the /T1 directory - as this is how RazorPages is configured given the options in `HttpContext.RequestServices` at that time when the middleware executes. 

Same expectation when browsing for `/t2` - i.e that should serve from the the /T2 directory. However all I get are 404's.

Am I missing something?

### Additional context
This may not be a bug, it could be something I am not conceptually understanding about the framework.

Here is `startup.cs`

```csharp
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public IServiceProvider Tenant1ServiceProvider { get; set; }
        public IServiceProvider Tenant2ServiceProvider { get; set; }


        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
            });


            services.AddRazorPages((options) => { options.RootDirectory = "/T1"; })
                .AddNewtonsoftJson();

            Tenant1ServiceProvider = services.BuildServiceProvider();

            services.AddRazorPages((options) => { options.RootDirectory = "/T2"; })
                .AddNewtonsoftJson();

            Tenant2ServiceProvider = services.BuildServiceProvider();

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseCookiePolicy();

            app.MapWhen((c) =>
            {
                return c.Request.Path == "/t1";
            }, (branched) =>
            {
                branched.ApplicationServices = Tenant1ServiceProvider;
                branched.Use((con, next) =>
                {
                    var scope = Tenant1ServiceProvider.CreateScope();
                    con.RequestServices = scope.ServiceProvider;
                    con.Response.RegisterForDispose(scope);
                    return next.Invoke();
                });
                branched.Use((con, next) =>
                {
                    Console.WriteLine("Tenant 1 Request Services set..");
                    return next.Invoke();
                });
                branched.UseRouting();
                branched.UseAuthorization();
                branched.UseEndpoints(endpoints =>
                {
                    endpoints.MapRazorPages();
                });
            });

            app.MapWhen((c) =>
            {
                return c.Request.Path == "/t2";
            }, (branched) =>
            {
                branched.ApplicationServices = Tenant2ServiceProvider;
                branched.Use((con, next) =>
                {
                    var scope = Tenant2ServiceProvider.CreateScope();
                    con.RequestServices = scope.ServiceProvider;
                    con.Response.RegisterForDispose(scope);                    
                    return next.Invoke();
                });
                branched.Use((con, next) =>
                {
                    Console.WriteLine("Tenant 2 Request Services set..");
                    return next.Invoke();
                });
                branched.UseRouting();
                branched.UseAuthorization();
                branched.UseEndpoints(endpoints =>
                {
                    endpoints.MapRazorPages();
                });
            });
        }
    }
```
```

**Comment by dazinator** [comment]
More detail.

It looks like a problem with `ApplicationPart`s.

Normal usage:

```
                services.AddLogging();
                services.AddRouting();       
                services.AddRazorPages()
                .AddNewtonsoftJson();
```
and:
```
                app.UseRouting();          
                app.Use((con, next) =>
                {
                    var sp = con.RequestServices;
                    var partManager = sp.GetRequiredService<ApplicationPartManager>();
                    return next.Invoke();
                });
```

`ApplicationPartManager` correctly has 4 parts, the first 2 allow Razor pages to populate endpoint routing correctly.

![image](https://user-images.githubusercontent.com/3176632/58561708-9f511900-821f-11e9-9d3f-9f3abc189c53.png)

Issue is, if you create a new `ServiceCollection` - i.e for a Tenant, and perform the same `AddXYZ` calls to add Razor:

```
var tenantServices = new ServiceCollection();
tenantServices.AddLogging();
tenantServices.AddRouting();
tenantServices .AddRazorPages((options) => { options.RootDirectory = razorPath; })
                        .AddNewtonsoftJson();
var tenantSp = tenantServices.BuildServiceProvider();

```

Now resolving `ApplicationPartManager` and inspecting the parts - it's missing the 2 Razor parts.

![image](https://user-images.githubusercontent.com/3176632/58559133-58145980-821a-11e9-9f4e-d48da41c87e7.png)

**Comment by dazinator** [comment]
@Eilon should I close this issue and raise a seperate one with the root cause - ie Application Parts?

**Comment by dazinator** [comment]
It seems that there is a hidden dependency. You can't simply new up an IServiceCollection, and add Logging, AddRouting, and AddRazorPages, because ApplicationPartManager doesn't then populate application parts, and routes are then not populated.

To workaround this issue, I had to clone the `IServiceCollection` passed in to Configure which contains about 70ish services by default. I am not sure which ones it is that allow ApplicationPartManager and thus Razor to work correctly.. yuck!

**Comment by rynowak** [comment]
@davidfowl @Tratcher - this is really a question about how to add the services that hosting adds. 

@dazinator - did you look at OrchardCore? They already have a solution for this particular problem (@sebastienros)

**Comment by dazinator** [comment]
@ryonak whilst I agree that adding the services resolves the issue, I think it's an issue with the current design. Constructor injection is all about making dependencies known / discoverable / explicit in API's. What we have here is 60+ services registered by default with no way to tell which ones are relied upon for RazorPages to work. If there are dependencies surely they should be surfaced somewhere in the razor pages registration api so that adding razor pages to a new service collection results in every dependency also being present for it to work or an error being thrown.. what do you think?

**Comment by Tratcher** [comment]
@dazinator yes, there are a [list of services](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#framework-provided-services) that are provided by the host and that upstream components like razor pages take advantage of. The main reason is that upstream components only depend on the interfaces for a given service, they aren't able to provide an implementation. Also, if they all attempted to do so they would conflict with eachother.

**Comment by dazinator** [comment]
@Tratcher if AddRazorPages() requires an upstream service/s in order to serve pages, shouldn't it error if those services are not present and tell you what they are? At the moment, thinking about this situation where I've added razor pages to a new service collection - it results in no ApplicationParts being created for the razor page assembly itself / its compiled views. This results in a default state where it will never serve any pages. Now if the documentation for razor pages started from this default position / state and then went on to explain that you have to either add application parts yourself or ensure there was an upstream service present then I'd be a bit happier as the touch points with upstream services would atleast be documented. As it stands you have to guess which upstream things maybe needed and how they might impact behaviour and from my experience it wasnt trivial to get to the bottom of this issue!

**Comment by Tratcher** [comment]
> shouldn't it error if those services are not present and tell you what they are?

Yes. Most components throw a DI error at startup or when processing requests if their services are missing. I'm curious how razor pages is able to fail silently.

**Comment by rynowak** [comment]
MVC application part discovery is esoteric and weird, and breaks *the rules* for some scenario reasons. We need to know the set of assemblies/controllers **BEFORE** the service collection is baked.

Conceptually we could detect this case by checking for a hosting environment when we discover endpoints as and say "well we would not have found anything because there's no hosting environment".

I'd like to sort this out, but the best fix is to change how discovery works, and I'm not sure that we'd be able to do that.

**Comment by dazinator** [comment]
> Conceptually we could detect this case by checking for a hosting environment when we discover endpoints as and say "well we would not have found anything because there's no hosting environment".

I think that sounds logical and would be better than nothing. If due to lack of an upstream service you know things are not going to work by default, an exception explaining the problem will save someone a few hours of debugging through the internal namespace trying to figure out whats wrong and maybe even point them on the right path for a quick remedy.

**Comment by mkArtakMSFT** [comment]
@dazinator feel free to send us a PR and we'll happily consider it.

**Comment by dazinator** [comment]
Just to say I wont be able to send a PR for this, it would take me to long. Given the discussion above - I think there is an acknowledgement that some things aren't as nice as they should be, but - as I am able to workaround the issue, I'm happy to close this and just settle it as feedback- if your team wants to make any improvements in this area it would be welcomed but not critical. Cheers.
