### ISSUE TITLE
WebSocket Sample C# Asp.Net Core SignalR getting Handshake error

### ISSUE THREAD

**Issue by SaravananGajendran** [aspnet/AspNetCore#10468]
Hi,

I use Web socket sample (https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/samples/WebSocketSample/Program.cs) for consuming the asp.net core signalr service.

When I run the code, The web socket is connected and after 15 secs I get {"error":"Handshake was canceled."}

After some research, I added the below two lines code and it started working

On the RunWebSockets() method after web socket connection, I added the below code and the wss connection and handshake happened successfully.
 
var handshake = new List<byte>(Encoding.UTF8.GetBytes(@"{""protocol"":""json"", ""version"":1}")) { 0x1e };
            ws.SendAsync(new ArraySegment<byte>(handshake.ToArray()), WebSocketMessageType.Text, true, CancellationToken.None).Wait();

Is there any reasons why we need to add the two lines. 
For c# we are sending the handshake in a ArraySegment.
I planned to use web socket client for javascript and c. In this case how the handshake should be performed.

On the Server I have the configurations as below in my Startup.cs

services.AddSignalR(hubOptions =>
{
	hubOptions.EnableDetailedErrors = true;
	hubOptions.KeepAliveInterval = TimeSpan.FromSeconds(5);
})
.AddJsonProtocol(options =>
{
	options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver();
})
.AddRedis(Configuration[StringConstants.RedisConnectionString].ToString());

Thanks
Saravanan G

**Comment by halter73** [comment]
> Is there any reasons why we need to add the two lines.

Yep. This is the hub handshake. SignalR clients normally do this for you, but if you wan't to interact with SignalR hubs using raw SebSockets you have to handle the hub protocol itself.

This is documented at https://github.com/aspnet/AspNetCore/blob/v2.2.5/src/SignalR/docs/specs/HubProtocol.md#transport-requirements. Here's the start of the section about the hub handshake:

```
After opening a connection to the server the client must send a HandshakeRequest message to the server as its first message. The handshake message is always a JSON message and contains the name of the format (protocol) as well as the version of the protocol that will be used for the duration of the connection. The server will reply with a HandshakeResponse, also always JSON, containing an error if the server does not support the protocol.
```

If you continue reading, the doc provides more details about what the handshake JSON messages should contain.

If you don't want to use SignalR hubs or implement the hub protocol yourself in you client, you can map a raw connection endpoint. This isn't super well documented yet, but you can see the MapConnections/MapConnectionHandler API in [the SignalRSample](https://github.com/aspnet/AspNetCore/blob/7669cf0d036cc0cb3b481aba49253cd35d85c633/src/SignalR/server/SignalR/test/Startup.cs#L39) which is lower-level than MapHubs. You can see a simple echo ConnectionHandler [here](https://github.com/aspnet/AspNetCore/blob/7669cf0d036cc0cb3b481aba49253cd35d85c633/src/SignalR/server/SignalR/test/EchoConnectionHandler.cs).

**Comment by SaravananGajendran** [comment]
Thanks for input.
