### ISSUE TITLE
Should we support @attribute [OutputElementHint("select")] on Razor components?

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#10470]
### Is your feature request related to a problem? Please describe.
Today components such as `<InputSelect ...>....</InputSelect>` and other user-written components are not treated as their output elements. This means there are some oddities when writing snippets such as:

```
<InputSelect bind-Value="starship.Classification">
    <option>Select classification ...</option>
...
</InputSelect
```

The oddities include lacking HTML completion lists (no `option` entry) and potential schema validation issues.

### Describe the solution you'd like
We could consider re-using the TagHelper mechanism and the new `@attribute` support for addressing similar concerns and enable `@attribute [OutputElementHint("select")]` in components. It would make components function similar to TagHelpers and would be a limited amount of work since a lot of that infrastructure is already in place.

### Describe alternatives you've considered
Other alternatives would be fully owning completion inside of our component tags or providing other indicators to be specific on what types of tags are allowed inside.

/cc @danroth27

**Comment by rynowak** [comment]
We should not do this unless it's automatic and done by the compiler. We need to make sure our tooling experiences work well when components are written naively.

**Comment by NTaylorMullen** [comment]
> We should not do this unless it's automatic and done by the compiler.

Could you expand a bit more here?

> We need to make sure our tooling experiences work well when components are written naively.

When you say natively do you mean our built-in components?

**Comment by rynowak** [comment]
To use Blazor is to write LOTS of components. I don't think we should add more homework to the critical path for authoring components.

**Comment by danroth27** [comment]
> I don't think we should add more homework to the critical path for authoring components.

I thought this was an optional things for component authors to do. If you want to indicate that your component should be treated like a specific HTML tag then you can add this attribute. 

This probably only works for child content though. A component might have other templated parameters that have the semantics of different HTML tags.

**Comment by rynowak** [comment]
> We need to make sure our tooling experiences work well when components are written naively.

**Comment by danroth27** [comment]
We chatted a bit about this offline:
- Ideally we don't want component authors to have to add additional metadata like this to get a good tooling experience. Can tooling just do the right thing based on how the component was authored?
- If we can't do something smart *and* correct then the tooling should be permissive (e.g. allow for all tags instead of warning of potentially inappropriate usage)

**Comment by mkArtakMSFT** [comment]
After some further discussion on this we've decided that we won't be fixing this in the near future. If we realize this is going to become a big pain point for customers, we may reconsider then.
