### ISSUE TITLE
Cookie parsing is a breaking issue for porting to asp.net core

### ISSUE THREAD

**Issue by kshyju** [aspnet/AspNetCore#10478]
Cookie parsing logic is breaking!

### To Reproduce
1. Set a string as cookie value which has double quotes in it.
2. Try to read it using `HttpContext.Request.Cookies`
3. See cookie cannot be read in asp.net 2.2 while it works on a 4.7.2 app

Detailed repo.

I have some Javascript code which writes cookie value

    setCookie('a','{"m":"en-gb"}',1);
    setCookie('c','en|us',1);

Cookies are set and you can see in chrome dev tools.

![image](https://user-images.githubusercontent.com/144469/58215884-d750dd00-7cb0-11e9-8869-56f7ec2f47f2.png)

The first cookies value is a JSON string version of a JS object. Now try to read this in 4.7.2 app

`var allKeys = this.HttpContext.Request.Cookies.AllKeys;`

Here you will get both `a` and `c`

Now try the same in asp.net core 2.2 app
`var allKeys = this.HttpContext.Request.Cookies.Keys;`

You will get only `c`!

When you access `this.HttpContext.Request.Headers["Cookie"]`, you will see the below value

`{a={"m":"en-gb"}; c=en|us}`

This is a breaking issue as we have legacy app which has this cookie value and we are trying to port it to asp.net core 2.2 and we will not be able to read this cookie value using `HttpContext.Request.Cookies`. We will be running both versions of the app (4.72 and 2.2 and the proxy sends traffic to either one instance based on configured rules (ex: running A/B tests)

I see some strict character checking [here](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Headers/src/CookieHeaderValue.cs#L228). Is there a recommended solution to address this issue ?

**Comment by kshyju** [comment]
Let me know if you need a repro solution for the above.

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/AspNetCore/issues/5685#issuecomment-448763553

Summary: JSON syntax is not valid in cookies. In this example it's the quotes `"` that are prohibited.

**Comment by anurse** [comment]
Closing as this isn't something we plan to support. If you need to store cookies like this, you could try base64-encoding first.

**Comment by kshyju** [comment]
Thanks @Tratcher
