### ISSUE TITLE
Add platform manifest to ASP.NET Core runtime pack

### ISSUE THREAD

**Issue by dsplaisted** [aspnet/AspNetCore#10474]
We should add the same platform manifest (`data/PlatformManifest.txt`) that is in the targeting pack to the runtime packs.

This will help optimize conflict resolution for self-contained apps.

Some discussion of this is here: https://github.com/dotnet/sdk/issues/2933

@natemcmaster @pranavkm

**Comment by natemcmaster** [comment]
ACK. Putting in the P7 milestone
