### ISSUE TITLE
Restrict health check to GET HTTP method

### ISSUE THREAD

**Issue by APIWT** [aspnet/AspNetCore#10488]
Hello!

Is it possible to restrict all health checks to GET requests? We are seeing a warning in our security scans on these endpoints classified as HTTP method fuzzing.

If not, is it possible to work around this with the response writer?

Thanks!

**Comment by rynowak** [comment]
You should be able to do this on 2.1 using the `MapWhen` middleware and putting health checks in a branch of the pipeline.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2#create-a-middleware-pipeline-with-iapplicationbuilder


In 3.0 health checks is supported with routing as well which makes this much less difficult.

**Comment by APIWT** [comment]
@rynowak That works for me. Thank you! Feel free to mark this issue as closed. I'll pass this information along to the documentation team and see if they have any good ideas for adding this to the docs.

**Comment by APIWT** [comment]
@rynowak Okay, I actually spoke too soon. Adding `MapWhen` works for the health checks but it eliminates most of the routing for everything else. This is my `Configure` code:
```
app.MapWhen(
                context => context.Request.Method == HttpMethod.Get.Method,
                builder => builder.UseHealthChecks("/api/HealthCheck"));
app.UseSwaggerMiddleware(versionDescriptionProvider, appSettings?.Swagger);
app.UseMvc();
```

Any idea why `MapWhen` is trampling my API routes? It is causing all of them to 404.

**Comment by rynowak** [comment]
Try this:
```
app.MapWhen(
    context => context.Request.Method == HttpMethod.Get.Method && context.Request.Path.StartsWith("/api/HealthCheck"),
    builder => builder.UseHealthChecks());
app.UseSwaggerMiddleware(versionDescriptionProvider, appSettings?.Swagger);
app.UseMvc();
```

**Comment by APIWT** [comment]
@rynowak Aha! Brilliant. That did the trick. For reference to anyone else dealing with this issue, I had to use `context.Request.Path.StartsWithSegments` instead of `context.Request.Path.StartsWith`.
