### ISSUE TITLE
Read QueryString as stream

### ISSUE THREAD

**Issue by Hantse** [aspnet/AspNetCore#10485]
Actually we have some characters not correctely interpret by DotNet, to find unsupported characters we want to byte comparaison, for body we use the stream reader.

### Describe the solution you'd like
A solution to read query string as stream or clear before some escaping

### Describe alternatives you've considered
No solution found for the moment.

### Additional context
Some Deutch caracters (ß, ß)

**Comment by Eilon** [comment]
@Hantse can you please provide more information on how to reproduce this issue?

Tagging @GrabYourPitchforks

**Comment by davidfowl** [comment]
You can't get the query string as a stream, unlike headers, the HTTP spec is pretty clear about the request line being USASCII (which the query string is part of).

**Comment by Tratcher** [comment]
URIs also have a very strict encoding spec. Non-ascii MUST be percent encoded UTF-8. (%2F)

**Comment by Tratcher** [comment]
Can you give some examples of the raw query bytes?

**Comment by Hantse** [comment]
Hello,

We have a little project with concret sample, i provide it asap. Tahnk's for your first responses.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
