### ISSUE TITLE
Remove AMR and auth_time from the OIDC filter list

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#10494]
https://github.com/aspnet/AspNetCore/blob/2948c81aea2e5a947dc80fe4a62fa7150a9c6f94/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L51-L58

These are used to gauge the strength and freshness of the login.

They are also not large values so they don't contribute significantly to the cookie size.

@brockallen

**Comment by anurse** [comment]
Super small, we'll give it a go.

**Comment by anurse** [comment]
This just requires deleting the two claims (`amr` and `auth_time`) from the lines cited above and making sure the tests pass ;)

**Comment by brockallen** [comment]
great, thanks!
