### ISSUE TITLE
Missing symbols for Microsoft.Web.Xdt.Extensions.dll in 3.0 builds

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#10495]
Symcheck errors fail consistently when checking the AspNetCoreRuntime.3.0.x64 package. 

> Checking file E:\A\_work\r1\a\checkSymbols\c14973bc-38c2-4465-b39e-2027cbd88420\content\Microsoft.Web.Xdt.Extensions.dll ... No symbols found on MSDL or SymWeb!

This .dll is only found in AspNetCoreRuntime.3.0.x64, and it appears we are missing symbols for it.

**Comment by dougbu** [comment]
Once this and #10297 are done, will be able to remove an exclusion from our release pipeline's "Publish and verify symbols" deployment

**Comment by dougbu** [comment]
4f67ff921673 and a slight change in the release pipeline
