### ISSUE TITLE
Blazor: More flexible Router / layout display

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#10493]
Currently, we have a hardcoded set of assumptions about what you want to do with a router, i.e.,

 * You want to display the page inside its layouts
 * You want to authorize access to the page, but still show its layouts regardless

The logic for this is all internal to `Router` and `LayoutDisplay` (being renamed to `PageDisplay`). Instead of this, we could reduce `Router` to be a templated component that just finds a page and parameters for you. Then you could choose how to render that, and where authorization wrappers go, etc., yourself.

Example:

```cshtml
<Router AppAssembly="@typeof(App).Assembly" Context="routeContext">
    <NotFoundContent>
        <LayoutDisplay Layout="@typeof(MainLayout)">
            <h1>Not found</h1>
            Sorry, there's nothing here.
        </LayoutDisplay>
    </NotFoundContent>
    <FoundContent>
        <AttributeAuthorizeView Page="@routeContext.Page">
            <Authorized>
                <LayoutDisplay Page="@routeContext.Page" PageParameters="@routeContext.Parameters" />            
            </Authorized>
            <NotAuthorized>
                <LayoutDisplay Layout="@typeof(MainLayout)">
                    <h1>Access denied</h1>
                    Go away.
                </LayoutDisplay>
            </NotAuthorized>
            <Authorizing>
                <LayoutDisplay Layout="@typeof(MainLayout)">
                    <h1>Please wait</h1>
                    Checking authorization...
                </LayoutDisplay>
            </Authorizing>
        </AttributeAuthorizeView>
    </FoundContent>
</Router>
```

This would completely nuke issue #10445 in the most comprehensive manner.

One drawback is the amount of repetition of specifying `<LayoutDisplay Layout="@typeof(MainLayout)">` here, but doing this does eliminate any need for a `DefaultLayout` concept, and completely decouples `Router`, `AuthorizeView`, and `LayoutDisplay` from each other. They would no longer need to have any awareness of each others' existence.

@rynowak @danroth27 @javiercn What's your gut response to this? Does it look too complicated, or do you think the flexibility warrants all the explicit code?

### Plan

* [x] Implement `LayoutView`
* [x] Implement `RouteView`
* [x] Update `Router` to new factoring
* [x] Implement `AuthorizeRouteView`
* [x] ~~Remove `CascadingAuthenticationState`~~ No, keeping it.
* [x] Remove `PageDisplay`
* [x] Update E2E tests
* [x] Update project templates

**Comment by mkArtakMSFT** [comment]
Discussed this offline. We don't have clear picture regarding this adding value or not.

**Comment by rynowak** [comment]
Reactivating this based on API review discussions. This solve a bunch of hard layering problems that we think are worth taking on.

**Comment by javiercn** [comment]
How does this affect https://github.com/aspnet/AspNetCore/issues/10445. Should we fold this into here?

**Comment by javiercn** [comment]
If we are considering moving forms and authorization out of M.A.Components. Should we also consider move Routing support to Microsoft.AspnetCore.Components.Routing?
I think they are at the same "level" and would be worth considering. The main challenge would be the JS interop piece, but that would use standard swa infrastructure to be available from the package and we could do some magic to plug it in automatically.
* Router/NavLink/Location could invoke some JSInterop to load the script for interception magically.

Thoughts?

**Comment by rynowak** [comment]
> 
> 
> If we are considering moving forms and authorization out of M.A.Components. Should we also consider move Routing support to Microsoft.AspNetCore.Components.Routing?

We were talking about this today, and we don't have a really clear picture of what advantage this provides. If you want to make a case for it - what types would move there and what are the advantages of this?

**Comment by SteveSandersonMS** [comment]
Done in #12800
