### ISSUE TITLE
Json broken, there is a lack of Exception throw

### ISSUE THREAD

**Issue by DekInc** [aspnet/AspNetCore#10492]
Problem:
When you have a response with Json(total = 4, records = ListData) the json is cut like this:

```json
{"total":4,
"records":
[
{"recid":0,"existencia":235,
"reservado":0,"disponible":235,
"cantPedir":37,"dateProm":null,
"transporte":null,"id":0,"idPaylessProdPrioriM":0,
"oid":null,"barcode":null
```

So, the problem i found was inside of the property of the class i return:

```c#
public partial class PaylessProdPrioriDet
    {
        public int Id { get; set; }
        public int IdPaylessProdPrioriM { get; set; }
        public string Oid { get; set; }
        public string Barcode { get; set; }
        //public string Tienda { get { return (string.IsNullOrEmpty(Barcode)? string.Empty : Barcode.Substring(0, 4)); } }
public string Tienda { get { return Barcode.Substring(0, 4); } }
        public string Estado { get; set; }
```

So when the get from property "Tienda" is executed it should throw an Exception if the value 
Barcode is null, but in this case the Json is just cutted and there is no exception, so i can GUESS,
that something is wrong inside the function, maybe there is a try:catch inside that prevents to show this Exception when serializing...

```c#
namespace Microsoft.AspNetCore.Mvc {
        [NonAction]
        public virtual JsonResult Json(object data);
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @DekInc.
We've addressed this issue in the 3.0 release.
For your case (and it seems you're not on 3.0) consider buffering the response on the server, if you want to see a 500 instead.
