### ISSUE TITLE
Error if input tags are not closed in Blazor apps

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#10498]
![image](https://user-images.githubusercontent.com/1874516/58281371-dde65f80-7d57-11e9-8192-1bf6aa524ef3.png)

**Comment by NTaylorMullen** [comment]
In TagHelper land we can accomplish the fix for this by specifying a "WithoutEnd" TagStructure. When we generate components if they apply to `input` tags etc. we should generate them without end tag.

**Comment by GeertvanHorrik** [comment]
Same issue with this markup:

```
@if (IsSplitButton)
{
    <div class="@Class">
        @SplitButtonItems
}

        some content here

@if (IsSplitButton)
{
    </div>
}
```

**Comment by NTaylorMullen** [comment]
@GeertvanHorrik that code is by design. We don't allow having partial HTML tags split among different code blocks.

**Comment by JosKrause** [comment]
Does this new rule also apply to the `<option>` element?

**Comment by NTaylorMullen** [comment]
> Does this new rule also apply to the `<option>` element?

The rule also applies to the `option` element. Essentially any [Void Elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) as defined by the HTML spec are allowed to not have end tags in C# blocks. All others must. This rule behaves the same as non-Blazor apps/files.

**Comment by mkArtakMSFT** [comment]
@rynowak should this be closed as `fixed` ?

**Comment by rynowak** [comment]
Fixed!
