### ISSUE TITLE
WebClient not supported

### ISSUE THREAD

**Issue by avillarubia** [aspnet/AspNetCore#10507]
WebClient is not supported says

blazor.webassembly.js:1 WASM: System.Net.WebException: An exception occurred during a WebClient request. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.

image
![image](https://user-images.githubusercontent.com/37901895/58268233-a3141400-7db7-11e9-9cd3-be63e0bf623b.png)

can someone help?

Thank you.

**Comment by enetstudio** [comment]
See this: https://stackoverflow.com/questions/56284192/webclient-not-supported/56284289#56284289

**Comment by avillarubia** [comment]
thank you @enetstudio
