### ISSUE TITLE
Running startvs.cmd more than once causes my PATH environment variable to accumulate

### ISSUE THREAD

**Issue by cshung** [aspnet/AspNetCore#10501]
### Describe the bug
Running startvs.cmd more than once causes my PATH environment variable to accumulate.

### To Reproduce
1. `git clone git@github.com:aspnet/AspNetCore.git` on Windows.
2. Using powershell, run `cd src\http` and then `.\startvs.cmd`
3. Using powershell, run `cd src\http` and then `.\startvs.cmd` again
4. Observe (using a command prompt child process or otherwise) the PATH variable has two duplicated copies of the dotnet path.

### Expected behavior
Ideally, the script should not alter the environment at all.

### Screenshots
N/A

### Additional context
N/A

**Comment by dougbu** [comment]
405d8bbdc91b

Thanks @cshung !
