### ISSUE TITLE
Blazor Div OnScroll fired duplicated in server-side until saturates the server

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#10500]
I'm creating a ScrollViewer control, whose content can be virtualized. I'm attaching the onscroll event of a div to know when the user scrolls. 
In the client-side works perfectly, but in the server side the event is raised many times, much more times in comparison to the client-side (I'm pressing the button down of the scrollbar to compare, in Chrome). This looks as a bug to me, the number of times the event is raised should be the same.
On the other hand, the problem gets much worse when the users starts dragging the thumb constantly, it eventually saturates the server(depending on how big is the layout inside the scrollviewer) and it says to have losen connection. How are we supposed to handle this kind of scenarios? The rate this event is fired is expected to be smaller than the time Blazor can dispatch it to the server, so in many cases can cause a indefinite wait.

Here is the page I'm using to test

```
@page "/"

<p>Current count: @currentCount</p>

<div onscroll="@OnScroll" style="height:500px;overflow:auto;">
    <div style="width:100%;height:10000px;background-color:red">
        <button class="btn btn-primary" onclick="@IncrementCount">Click me</button>
    </div>
</div>

@functions
{
    private void OnScroll()
    {
        currentCount--;
    }

    int currentCount = 0;

    void IncrementCount()
    {
        currentCount++;
    }

}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @arivoir.
We're going to address this as part of https://github.com/aspnet/AspNetCore/issues/10522

**Comment by mkArtakMSFT** [comment]
As for now your only option would be to intercept the scroll event in JavaScript and filter out those so only few hit the service.

**Comment by arivoir** [comment]
I was considering this alternative, but I don't know how to get the ScrollViewer(.Net) instance from the JavaScript onscroll event handler. In the documentation it says it is possible, but the sample passes the reference from the server, which is not applicable in this case. Somehow I should pass the reference in the BuildRenderTree method. Any idea?
