### ISSUE TITLE
[Blazor] Accessibility and keyboard navigation for complex component

### ISSUE THREAD

**Issue by Madhust** [aspnet/AspNetCore#10516]
As far as i understood, the whole idea of Blazor is to reduce the usage of JavaScript and leverage C# to create components. 

When the JavaScript usage is limited, what is the recommended way to implement keyboard navigation in complex components like menu, slider, list, gridview etc?

https://www.w3.org/TR/wai-aria-practices/#kbd_general_within

The above link describes keyboard navigation standard for complex components, this involves listening to events and adding `tabIndex` to the elements. Is this possible in Blazor?  How the DOM can be accessed and focused?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Madhust.
It's easy in Blazor to set html attributes and listen to DOM events. Is there anything else specific you have in mind?
As for the need for focus, we'll track that work as part of https://github.com/aspnet/AspNetCore/issues/10521

**Comment by Madhust** [comment]
@mkArtakMSFT Thanks for the update. Details looks good. If i face any problems or questions during implementation, i will put a new issue.

**Comment by Madhust** [comment]
@mkArtakMSFT, What is the equivalent of querySelector in Blazor. What if i want to query the children of the element. Is this possible with Blazor?

**Comment by mkArtakMSFT** [comment]
@Madhust for querySelector you should still use JSInterop.
