### ISSUE TITLE
Validation doesn't automatically traverse members

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#10526]
Validation doesn't automatically traverse the members of something so you have to manually add validation support for any satellite objects you want validated.

Example: https://github.com/rynowak/ComponentFunTime/blob/master/Components/Shared/EmployeeEditor.razor#L85

**Comment by mrpmorris** [comment]
@danroth27 

Possible solution:
In `InputBase<T>.set_FieldIdentifier` execute `EditContext.GetFieldState(value, true)`

This will add the field state to the EditContext and ensure it is validated.

PS: Not sure any FieldIdentifiers ever get removed from EditContext._fieldStates - I think this *might* cause a memory leak when navigating to different URLs that point to the same component.

Navigate -> SetParametersAsync -> Creates a FieldIdentifier -> Adds it to EditContext_.fieldStates

**Comment by mrpmorris** [comment]
All you need to do is have InputBase<T> ensure it has an entry in the EditContext when its EditContext changes. That will ensure only the items being edited are validated. This should be a minimum requirement.

If you also want to provide the ability to validate a whole object regardless of which properties have associated edits, please put a parameter on the validator that allows the user to disable it.

Also, please make the traversal code part of EditContext and not DataAnnoticationsValidator - so other validation frameworks can use it too.

**Comment by mgolois** [comment]
@mrpmorris do you have sample code of your suggestion?

**Comment by mrpmorris** [comment]
The following code adds a hacky `_AccessGetFieldState` to EditContext. It's just a way to access EditContext.GetFieldState.

The "fixed" InputText (should be done in InputBase) simply calls EditContext.GetFieldState when its EditContext changes, this ensures EditContext._fieldStates has an entry for this input.

EditContext.Validate can then validate every FieldState it has a reference to.

This way we 
1: Have deep validation into complex types.
2: Only validate parts of the object we are letting the user modify. This is useful for wizard UIs where the user builds up the data over multiple pages.

```
	public class InputTextFixed : InputText
	{
		public async override Task SetParametersAsync(ParameterView parameters)
		{
			EditContext previousEditContext = EditContext;
			await base.SetParametersAsync(parameters);
			if (EditContext != previousEditContext)
				EditContext._AccessGetFieldState(FieldIdentifier);
		}
	}

	public static class HackGetFieldState
	{
		public static void _AccessGetFieldState(this EditContext editContext, FieldIdentifier fieldIdentifier)
		{
			var getFieldStateInfo = typeof(EditContext).GetMethod("GetFieldState", BindingFlags.NonPublic | BindingFlags.Instance);
			if (getFieldStateInfo == null)
				throw new NullReferenceException("GetFieldState not found");
			System.Diagnostics.Debug.WriteLine("Updating FieldState");
			getFieldStateInfo.Invoke(editContext, new object[] { fieldIdentifier, true });
		}
	}
```

**Comment by pranavkm** [comment]
> All you need to do is have InputBase ensure it has an entry in the EditContext when its EditContext changes. That will ensure only the items being edited are validated.

@mrpmorris I'm not sure how that works. Would each of these fields be the models passed in to data annotations? That would mean validation attributes decorated on properties wouldn't be discovered. In addition, the `EditForm` has already established the model to operate on. It would be surprising if validation did not apply to all the properties on the model the user declared was being edited.

**Comment by mrpmorris** [comment]
Sorry, can you elaborate? I'm not quite sure I am following what your concerns are.

**Comment by pranavkm** [comment]
@mrpmorris for your ask, we're going to use https://github.com/aspnet/AspNetCore/issues/14426 to track adding the API to the application. We'll use this issue to continue tracking the original goal of the issue which is to produce an experimental package based on the sample: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/Validation/Validation

**Comment by mrpmorris** [comment]
I work for the UK government Department for Education. A common approach is to allow the user to edit a large object over multiple steps, the experimental approach wouldn't work and would require us to create multiple classes that identically represent parts of the object being edited and map the properties across.

It's more work than it needs to be. If InputBase would just instruct EditContext to create FieldState for its FieldIndentifier whenever its EditContext changes then Blazor would ensure all input controls are validated.

**Comment by SteveSandersonMS** [comment]
Yes, I think hopefully the issue #14426 should cover your UI-based validation requirement (which is not exactly the same as this issue, i.e., traversal into child objects).

If you have any further comments about UI-based validation requirements, could you post them at #14426? Thanks!

**Comment by mkArtakMSFT** [comment]
@pranavkm please make sure this happens as the last thing in 3.1, as there is no time pressure.
