### ISSUE TITLE
Build automated conversion procedure for ASP.NET WebForms migration to .NET Core

### ISSUE THREAD

**Issue by sravansurabhi** [aspnet/AspNetCore#10531]
### Is your feature request related to a problem? Please describe.
We have huge Implementations of ASP.NET Web Forms.  Organization is under taking initiative to modernize the legacy applications. There is no equivalent of ASP.NET Web forms in .NET Core.

### Describe the solution you'd like
Build automated conversion procedure for ASP.NET Webforms migration to ASP.NET Core

**Comment by Eilon** [comment]
The two programming models are almost entirely different (ASP.NET Web Forms vs. ASP.NET Core Web Pages / MVC / Blazor), so automatic conversion is essentially impossible.

**Comment by Eilon** [comment]
The ASP.NET Core docs include some info on migration: https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.2

And I found a recent thread on Reddit where there is some discussion about migration: https://www.reddit.com/r/dotnet/comments/bt713i/whats_the_best_course_of_action_to_migrate_our/

But as for an automated tool, there are no plans from Microsoft to ship such a thing.

**Comment by anurse** [comment]
Automating this conversion is a huge amount of work and wouldn't be very reliable since WebForms is a very complicated product. Closing since we don't have plans to do this and @Eilon posted some resources.
