### ISSUE TITLE
Blazor Admin Layout

### ISSUE THREAD

**Issue by selimhur** [aspnet/AspNetCore#10537]
How can i create AdminLayout and Page in Blazor

**Comment by 3x0dv5** [comment]
What do you mean with AdminLayout and Page? Have you looked into the documentation yet? You should put some effort into adding an issue. You should not just put a sentence here and expect people to turn around and explain you everything. If you don't put the effort into creating a ticket do you honestly expect people to put their time looking at your problem? Come on, have some respect for other people's time!
