### ISSUE TITLE
Blazor error at Http.PutJsonAsync/PostJsonAsync

### ISSUE THREAD

**Issue by AmarjeetBanwait** [aspnet/AspNetCore#10538]
Getting error on Http Put/Post 

`protected async Task Update()`
  `  {`
       ` await Http.PutJsonAsync("api/student/" + Id, student);`
    `}`

A full page refresh is happning. However rest api is hitting before getting error.

![HttpRequest Error](https://user-images.githubusercontent.com/4598234/58372435-81a25c00-7f60-11e9-9476-351892a088ad.jpg)

**Comment by 3x0dv5** [comment]
Not enough info. In the API that you are hitting, in its logs, do you see anything happening? 
Any github repo?

**Comment by AmarjeetBanwait** [comment]
Thanks @3x0dv5 
I managed to fix it.

**Comment by 3x0dv5** [comment]
What was the problem?

**Comment by AmarjeetBanwait** [comment]
Actually I copied code from another app and I forgot to call method from "onclick" of  button to "onsubmit" of "form". Thats why it was causing the full page refresh.
Sorry my bad.
