### ISSUE TITLE
Consolidate Windows Auth config

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#10530]
There are now three  ways to enable Windows Authentication:
- The [Negotiate Auth handler](https://github.com/aspnet/AspNetCore.Docs/issues/12420#issuecomment-492446725)
- HttpSys
- IIS/Express (in proc and out of proc)

Every one of them is mutually exclusive. The Negotiate handler throws if you try to use it with HttpSys or IIS because it depends on Kestrel connection state features. This makes for a terrible user experience if you want to develop in one environment but deploy to another (see [Music Store](https://github.com/aspnet/AspNetCore/blob/49c01eefecf1dbd75e5536aa803d689390c6770a/src/MusicStore/samples/MusicStore/Program.cs#L30-L54)).

Proposal:
Make the Negotiate handler the primary mechanism, but have it detect the other scenarios and forward to the appropriate handler:
- IIS In-Proc - forward to IISServerDefaults.AuthenticationScheme "Windows"
- IIS out-of-proc - forward to IISDefaults.AuthenticationScheme "Windows"
- HttpSys - forward to HttpSysDefaults.AuthenticationScheme "Windows"
  - `Configure<HttpSysOptions>(options => options.Authentication.Schemes =
                            AuthenticationSchemes.Negotiate` (if not already set?)

You'd still have to enable Windows Auth in IIS, but the app could use the same portable code across servers.
```
            services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
                .AddNegotiate();
```

**Comment by anurse** [comment]
We'll look at having the new handler just no-op when it detects that the server supports negotiate directly.

Gonna try this in 3.0 :).

**Comment by Tratcher** [comment]
Verified with SDK 3.0.100-preview7-012742 for in-proc, out-of-proc, and kestrel.
