### ISSUE TITLE
[server-side blazor] Application is not responsive after closing and reopening the browser's tab

### ISSUE THREAD

**Issue by kjeske** [aspnet/AspNetCore#10546]
Server-side Blazor application is not responsive after closing and reopening the browser's tab. Seems like the SignalR connection is not set up correctly.

### To Reproduce
1. Make sure that the debugging session is not attached to the browser's tab session (when you close the tab, the application won't stop)
2. Create the sample server side blazor app: `dotnet new blazorserverside`
3. Run the app - app will open in a new tab
4. Close the tab with the application
5. Reopen the tab (feature exists for example in Chrome and Firefox - CTRL+SHIFT+T on Windows) 
6. The application will appear again in the recovered tab, but is not responsive anymore
### Expected behavior
Application is reinitialized and responsive

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kjeske.
We're handling this as part of https://github.com/aspnet/AspNetCore/issues/10842
