### ISSUE TITLE
How to convert EventCallback<T> to EventCallback<bool>

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#10544]
Blazor has a generic class named EventCallback

How can I cast a 
`
    protected EventCallback<T> ValueChanged { get; set; }
`
to 
`
    EventCallback<bool> BoolChanged
       {
         get
         {
           if (typeof(T) == typeof(bool))
             return ValueChanged; //<== Error needs cast some how?
         }
       }
`

**Comment by arivera12** [comment]
It seems you don't understand how generics works. When you call EventCallback based on your definition it should expect that you define a type for him. Example EventCallback<bool>?.Invoke();. The type T should be define somewhere else maybe on the class or in a method. Example MyClass<T>. When you call MyClass it should prompt you to define what is T. Let's say T is is bool so you should call your class like this MyClass<bool>(). Does this helps?

**Comment by enetstudio** [comment]
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp1.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}



@arivera12, suppose I've the following components
`
@*Parent.razor*@

@page "/Parent"

<div>
    <Child Data="@Data" ValueChanged="@ValueChanged">
    </Child>
</div>

@functions {
    List<Item> Data = new List<Item>();

    private void ValueChanged(Item item)
    {        
    }
}
`
And 

`
@*Child.razor*@

@typeparam TData

<div>
    @foreach (var item in Data)
    {
        <button onclick="@(() => ValueChanged.InvokeAsync(item))"></button>
    }
</div>

@functions {
    [Parameter]
    public IEnumerable<TData> Data { get; set; }

    [Parameter]
    protected EventCallback<TData> ValueChanged { get; set; }
}
`

`
// Item.cs
public class Item
{
     public Item()
     {

     }
}
`

As you can see I've two components, and am using generics(typeparam) with EventCallback...
Now, I want to define EventCallback<bool> property with a get accessor that checks if 
the type of TData is bool, and if it does, coverts the ValueChanged delegate to 
EventCallback<bool> 

EventCallback<bool> BoolChanged { 
    get 
    { 
       if (typeof(TData) == typeof(bool)) return ValueChanged; // Needs conversion, but how
    } 
 }

**Comment by enetstudio** [comment]
@arivera12, suppose I've the following components

@*Parent.razor*@

@page "/Parent"

<div>
    <Child Data="@Data" ValueChanged="@ValueChanged">
    </Child>
</div>

@functions {
    List<Item> Data = new List<Item>();

    private void ValueChanged(Item item)
    {        
    }
}

And 


@*Child.razor*@

@typeparam TData

<div>
    @foreach (var item in Data)
    {
        <button onclick="@(() => ValueChanged.InvokeAsync(item))"></button>
    }
</div>

@functions {
    [Parameter]
    public IEnumerable<TData> Data { get; set; }

    [Parameter]
    protected EventCallback<TData> ValueChanged { get; set; }
}



// Item.cs
public class Item
{
     public Item()
     {

     }
}


As you can see I've two components, and am using generics(typeparam) with EventCallback...
Now, I want to define EventCallback<bool> property with a get accessor that checks if 
the type of TData is bool, and if it does, coverts the ValueChanged delegate to 
EventCallback<bool> 

EventCallback<bool> BoolChanged { 
    get 
    { 
       if (typeof(TData) == typeof(bool)) return ValueChanged; // Needs conversion, but how
    } 
 }

**Comment by enetstudio** [comment]
@arivera12, suppose I've the following components
`
@*Parent.razor*@

@page "/Parent"

<div>
    <Child Data="@Data" ValueChanged="@ValueChanged">
    </Child>
</div>

@functions {
    List<Item> Data = new List<Item>();

    private void ValueChanged(Item item)
    {        
    }
}
`
And 

`
@*Child.razor*@

@typeparam TData

<div>
    @foreach (var item in Data)
    {
        <button onclick="@(() => ValueChanged.InvokeAsync(item))"></button>
    }
</div>

@functions {
    [Parameter]
    public IEnumerable<TData> Data { get; set; }

    [Parameter]
    protected EventCallback<TData> ValueChanged { get; set; }
}
`

`
// Item.cs
public class Item
{
     public Item()
     {

     }
}
`

As you can see I've two components, and am using generics(typeparam) with EventCallback...
Now, I want to define EventCallback<bool> property with a get accessor that checks if 
the type of TData is bool, and if it does, coverts the ValueChanged delegate to 
EventCallback<bool> 

EventCallback<bool> BoolChanged { 
    get 
    { 
       if (typeof(TData) == typeof(bool)) return ValueChanged; // Needs conversion, but how
    } 
 }

**Comment by enetstudio** [comment]
@arivera12, suppose I've the following components
```
@*Parent.razor*@

@page "/Parent"

<div>
    <Child Data="@Data" ValueChanged="@ValueChanged">
    </Child>
</div>

@functions {
    List<Item> Data = new List<Item>();

    private void ValueChanged(Item item)
    {        
    }
}
```
And 

`
@*Child.razor*@

@typeparam TData

<div>
    @foreach (var item in Data)
    {
        <button onclick="@(() => ValueChanged.InvokeAsync(item))"></button>
    }
</div>

@functions {
    [Parameter]
    public IEnumerable<TData> Data { get; set; }

    [Parameter]
    protected EventCallback<TData> ValueChanged { get; set; }
}
`

`
// Item.cs
public class Item
{
     public Item()
     {

     }
}
`

As you can see I've two components, and am using generics(typeparam) with EventCallback...
Now, I want to define EventCallback<bool> property with a get accessor that checks if 
the type of TData is bool, and if it does, coverts the ValueChanged delegate to 
EventCallback<bool> 

EventCallback<bool> BoolChanged { 
    get 
    { 
       if (typeof(TData) == typeof(bool)) return ValueChanged; // Needs conversion, but how
    } 
 }

**Comment by enetstudio** [comment]
@arivera12, suppose I've the following components
```
@*Parent.razor*@

@page "/Parent"

<div>
    <Child Data="@Data" ValueChanged="@ValueChanged">
    </Child>
</div>

@functions {
    List<Item> Data = new List<Item>();

    private void ValueChanged(Item item)
    {        
    }
}
```
And 

```
@*Child.razor*@

@typeparam TData

<div>
    @foreach (var item in Data)
    {
        <button onclick="@(() => ValueChanged.InvokeAsync(item))"></button>
    }
</div>

@functions {
    [Parameter]
    public IEnumerable<TData> Data { get; set; }

    [Parameter]
    protected EventCallback<TData> ValueChanged { get; set; }
}
```

```
// Item.cs
public class Item
{
     public Item()
     {

     }
}
```

As you can see I've two components, and am using generics(typeparam) with EventCallback...
Now, I want to define EventCallback<bool> property with a get accessor that checks if 
the type of TData is bool, and if it does, coverts the ValueChanged delegate to 
`EventCallback<bool>` 

```
EventCallback<bool> BoolChanged { 
    get 
    { 
       if (typeof(TData) == typeof(bool)) return ValueChanged; // Needs conversion, but how
    } 
 } 

```

**Comment by arivera12** [comment]
You can use Action instead of EventCallback take note that TData must be define on the child component call like this:
`<Child TData=bool Data="@Data" ValueChanged="@ValueChanged"></Child>`
Can you please explain what is exactly what are you trying to achieve?

**Comment by arivera12** [comment]
Please try the below code example and see if its works and achieve what you trying to do.
```
@page "/Parent"

<div>
    <Child TData=bool Data="@Data" ValueChanged="@((item) =>ValueChanged(item))">
    </Child>
</div>

@functions {
    List<Item> Data = new List<Item>();

    private void ValueChanged(bool item)
    {        
    }
}
```

```
@typeparam TData

<div>
    @foreach (var item in Data)
    {
        var currItem = item;
        <button onclick="@(() => ValueChanged?.Invoke(currItem))"></button>
    }
</div>

@functions {
    [Parameter]
    public IEnumerable<TData> Data { get; set; }

    [Parameter]
    protected Action<TData> ValueChanged { get; set; }
}
```

**Comment by enetstudio** [comment]
@arivera12
Thanks for your response
Your suggestion that I use an Action delegate is not compatible with the recommendation of the Blazor team to use EventCallback instead of the Action delegate. However, my question is still remains the same. The reasoning behind this is not entirely clear to me: I saw this question in stackoverflow and am trying to find out if it can be done at all

Anyhow thanks for your efforts...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by enetstudio** [comment]
The following is the answer to my question above. It is imported from StackOverflow:

protected EventCallback<bool> BoolChanged => (EventCallback<bool>)(object)ValueChanged;

Thank you...
