### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker log exception

### ISSUE THREAD

**Issue by coderuid** [aspnet/AspNetCore#10549]
### Describe the bug
On adding "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker" to log filter:
`loggingBuilder.AddFilter("Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker", LogLevel.Error);` got an exception:

> Object reference not set to an instance of an object.
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

### To Reproduce
1. Using this version of ASP.NET Core: 3.0.0-preview5-27626-15
2. Run this code:
`
app.UseRouting();
app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
`

`public class TokensController : ControllerBase
    {
        [HttpPost]
        public TokensSet IssueToken()
        {
            return new TokensSet();
        }
    }`
3. With application logLevel higher than "Debug"
4. See error:
> Object reference not set to an instance of an object.
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

### Expected behavior
No exception and no log records

### Additional context

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.2.106 [/usr/local/share/dotnet/sdk]
  3.0.100-preview5-011568 [/usr/local/share/dotnet/sdk]

**Comment by rynowak** [comment]
@danroth27 @mkArtakMSFT - we should fix this for the this preview. This blocks use of debug-level logging.

**Comment by coderuid** [comment]
Problem is here:
https://github.com/aspnet/AspNetCore/blob/0a148bfca4b9e26210242778a6d263d9b4b3d0a4/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs#L99

Some examples use this
`public IDisposable BeginScope<TState>(TState state)
  {
    return null;
  }`
to ignore scopes. `scope.Dispose();` causes exception.
