### ISSUE TITLE
Server-side Blazor, client UI update (push from server)

### ISSUE THREAD

**Issue by ulkaio** [aspnet/AspNetCore#10559]
I am wondering what is the best practice in server-side Blazor to update the client UI on some server side event. For example there is a background job running in the server and on some event it's want to update the connected client UI (without refresh from client), previously I was using SignalR for that, but I am not sure it's is the right approach for this on srever-side blazor.

**Comment by davidfowl** [comment]
Are you trying to push a UI update to all clients?

**Comment by mkArtakMSFT** [comment]
Blazor server-side execution context is bound to a single client. If there are two clients - there are two separate execution context. Each one of these can independently fire `StateHasChanged` and that would result the appropriate client to be updated.

**Comment by rynowak** [comment]
If your code is running on a background thread inside a component, it's pretty easy to update the UI.

`Invoke(() =>
{
     // Update properties and other state
     .....
    //
    StateHasChanged(); // Trigger UI update
});
