### ISSUE TITLE
MarkupString is not rendered inside of HTML tag in Razor components

### ISSUE THREAD

**Issue by ajruckman** [aspnet/AspNetCore#10555]
### Describe the bug
The `MarkupString` type (which, as I understand it, is meant to output raw HTML) does not output inside HTML tags.

### To Reproduce
1. Use ASP.NET Core 3.0 Preview 5
2. Create a Razor component with this code:
```c#
MarkupString outer = new MarkupString("class='test'");
MarkupString inner = new MarkupString("inner");
<td @outer>@inner</td>
```

3. View/render the Razor component somehow

### Expected behavior
The following is displayed:
```html
<td class='test'>inner</td>
```
This is the way `IHtmlString` works in ASP.NET.

### Actual  behavior
The following is displayed:
```html
<td>inner</td>
   ^
   | No space
```
This is weird because there isn't even a space between `<td` and `>` like you would expect. This makes me think there's a check somewhere to remove whitespace inside HTML tags and that it's removing the MarkupString too.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ajruckman.
There are some changes being done in this area in the upcoming release.
In Blazor we don't support C# expressions inside tags directly.
Going forward they will be treated as content.
For your example that would result in: `<td @outer>` being rendered. Of course, the normal `<td key="@outer">` would do the right thing and would treat @outer as a C# and evaluate it: `<td key="class='test'">`.
