### ISSUE TITLE
Reading Files in Client-side Blazor

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#10552]
### Describe the bug
In Client-side blazor, How to read the static files? . I am using 'System.IO' for file streaming. 

Can any one please help on this?

`object FileData = Json.Deserialize<object>(System.IO.File.ReadAllText(System.IO.Path.GetFullPath(path)));`

Is there alternate for reading static files in blazor client-side? 

### Additional context
![image](https://user-images.githubusercontent.com/31958591/58401611-f1f1d000-807b-11e9-993b-a409096c5e5e.png)

**Comment by RemiBou** [comment]
What do you mean by static file ? the result of an input t-file ? reading a file from the ressources ? reading a remote file in http ?

**Comment by kmuthukumar23** [comment]
Hi @remibou,

I need to read from local resources.

**Comment by RemiBou** [comment]
local disk ? or embedded ressource in assembly ?

Local disk is impossible client-side (AFAIK) as the browser prevent you from doing it. If you need to read a file located on the client side, you need to add an input type="file" and let the user choose the said file you can find more informations about it here https://github.com/aspnet/Blazor/issues/527#issuecomment-486647075

**Comment by 3x0dv5** [comment]
Don't you think it would be dangerous if browsers allowed websites to read the local filesystem? Check the docs, you'll find an explanation there.

**Comment by mkArtakMSFT** [comment]
@kmuthukumar23 there is no local content available. You should stream that data from server to client. You can use `HttpClient` to read it from the server and parse it to JSON.

**Comment by bharathm03** [comment]
@mkArtakMSFT we need to load [CLDR](https://github.com/unicode-cldr/cldr-json) data into our application for internalization purpose. This is needed at client-side during render time. How to read/send cldr files to browser.
