### ISSUE TITLE
SignalR exceptions aren't logged in 3.0 preview 5

### ISSUE THREAD

**Issue by irwiss** [aspnet/AspNetCore#10554]
Good time of day,

I've been trying the 3.0 preview and I'm not sure where the exception logging has gone to in SignalR, does it need additional config to appear in 3.0? To make a clean test i've started 2 projects that are basically the "new project" template and used the [signalr intro tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2).

One project runs on asp 2.2, click the chat button - observe the console outputs the exception
The other project runs on asp 3.0, click the chat button - you can see the exception message going across the web socket in browser dev console but nothing appears on server log

[exception-logging-issues.zip](https://github.com/aspnet/AspNetCore/files/3224146/exception-logging-issues.zip)

What configuration is needed to get server side logging for signalr action exceptions in 3.0?

**Comment by BrennanConroy** [comment]
Good catch, we did some refactoring in that area and accidentally removed the log.

**Comment by anurse** [comment]
As part of this we should make sure we have a test that asserts the log is present, to avoid regression in the future.

**Comment by mikaelm12** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [ ] This is a Docs issue.
* [x] The fix contains product changes (**check all items below**).
	* [x] Relevant XML documentation comments for new public APIs are present. - Not needed
	* [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [x] The change requires no docs changes.
	* [x] Verification has been completed. (**check one item below**)
    	* [x] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [3.0.100-preview7-012617]
			* ASP.NET Core Runtime: [3.0.0-preview7.19325.3]
			* .NET Core Runtime: 3.0.0-preview7-27825-05]
	    * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: 3.0.0-preview7.19325.8
