### ISSUE TITLE
Microsoft.AspNetCore.App framework should use rollForward=LatestPatch

### ISSUE THREAD

**Issue by vitek-karas** [aspnet/AspNetCore#10567]
The `Microsoft.AspNetCore.App` framework should correctly specify the compatibility version range for its dependency on `Microsoft.NETCore.App` framework. The expectation is that the same `major.minor` version will be used (with roll forward to latest patch applied). Currently the framework doesn't specify anything other than the minimum version. That means the defaults are used which are that any version with the same `major` is compatible. So for example `3.0.0` ASP.NET currently declares it's compatible with `3.1.0` NETCore.App.

As discussed offline that is not the intent. The framework should be changed to specify that it expects the same `major.minor`. To do that the `.runtimeconfig.json` of the framework should specify `rollForward: "LatestPatch"` - which means only the same `major.minor` version is compatible.

See https://github.com/dotnet/core-setup/issues/5870#issuecomment-496210183 for discussion of potential impact and what are the scenarios (component hosting being the major one).

**Comment by vitek-karas** [comment]
@natemcmaster @dagood

**Comment by JunTaoLuo** [comment]
@vitek-karas This is completed. How can we test this end to end?

**Comment by vitek-karas** [comment]
I usually "mock" this": xcopy install the version with the changes (the whole runtime, so NETCoreApp and ASPNetCore) into some folder. Then go to the shared folder and copy the NETCoreApp and make it a 3.1 version. Then write an app (ASP.NET) which prints out the location of corelib (to verify where the framework came from).
On its own it should report the lower 3.0 version.
Now manually edit the .runtimeconfig.json of the app and add `rollForward: LatestMinor` to it. And run it again. If your change is good, you should see it using 3.0 still. If it didn't work, you should get the 3.1 version (you can double check by manually removing the `rollForward: LatestPatch` from the ASP.NET runtimeconfig and rerun, you should get 3.1 now).

If there's a place I can get the ASP.NET framework with this change, I can give it a try myself if you want.
