### ISSUE TITLE
[Feature Request] Add UserManager.MaxFailedAccessAttempts

### ISSUE THREAD

**Issue by lonix1** [aspnet/AspNetCore#10568]
### Background
During app start, the maximum login attempts before user lockout is configured via `IdentityOptions.Lockout.MaxFailedAccessAttempts`.

### Problem
During runtime, it is often necessary to calculate the number of attempts remaining and take action, like send reset emails, warn the user he has `"x of n"` attempts remaining, log the failures, etc.

But that means dragging around the `MaxFailedAccessAttempts` as a config option, plugging it into DI / options, passing it into one class that passes it into another class, etc. What a mess.

### Solution
Please surface that value as `UserManager.MaxFailedAccessAttempts` or similar?

**Comment by blowdart** [comment]
It is under UserManager.Options.MaxFailedAccessAttempts

**Comment by lonix1** [comment]
>IdentityOptions' does not contain a definition for 'MaxFailedAccessAttempts' and no accessible extension method 'MaxFailedAccessAttempts' accepting a first argument of type 'IdentityOptions' could be found (are you missing a using directive or an assembly reference?)

?
