### ISSUE TITLE
Client-side Blazor nested Components performance

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#10563]
I'm researching to build a Blazor grid control. This control uses a lot of elements, so performance is very important. At some point I moved the "cells", which are div's, into a custom component. And I noticed a degradation of the performance.

I tried to isolate the problem and wrote the following code that shows the problem in a simpler way.

```
<button class="btn btn-primary" onclick="@IncrementNumberElements">Increment number of elements</button> @number_of_elements

@for (int i = 0; i < number_of_elements; i++)
{
    @*<div>@i</div>*@
    var _i = i;
    <Component1>@_i</Component1>
}

@functions {
    int number_of_elements = 0;

    public void IncrementNumberElements()
    {
        number_of_elements += 100;
    }
}

```

whereas Component1 is

```
<div>@ChildContent</div>

@functions {

    [Parameter]
    private RenderFragment ChildContent { get; set; }
}
```

In the first component, there is a commented code that produces the original div. When I changed it to use the component named "Component1" it reduces the performance in about 75%, and both generate the same html.

I performed a test where I ran the above code 10 times and got the following numbers from Chrome performance debugger

  | div(ms) | Component1(ms)
-- | -- | --
  | 529 | 675
  | 342 | 601
  | 351 | 478
  | 357 | 565
  | 360 | 621
  | 390 | 672
  | 384 | 711
  | 380 | 857
  | 430 | 824
  | 409 | 888
Avg | 393.2 | 689.2
  |   | 75%

![image](https://user-images.githubusercontent.com/17496741/58443280-5b4b0080-80c7-11e9-8fb0-afc36dcd7fff.png)

This doesn't seem an expected impact on the performance. I suppose just encapsulating some part of the ui into components shouldn't perform such degradation.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @arivoir and for the data you've provided.
@SteveSandersonMS this may be something you'd like to look into.

**Comment by SteveSandersonMS** [comment]
Components aren't expected to have zero overhead. Choosing to factor something out into a component will sometimes improve performance, and will sometimes worsen it. To make the ideal choice you'll have to think about which parts of the UI are going to update when.

Each component is a separate region for UI diffing purposes. As such, it involves some overhead versus just having inline Razor in some other component, because the framework has to instantiate various objects to track the state of the component, and sends a separate message to the JS side to supply the contents of the component. So you should expect some extra cost.

The payoff comes when the output of your factored-out component changes. Now *only* that component has to be diffed and updated in the DOM, so you may have greatly improved the perf of your app compared with having to diff a larger amount of content at the parent level.

The numbers you've posted line up with what I'd expect. It's a microbenchmark that shows probably the worst case where there are a large number of child components which themselves never update.

**Comment by SteveSandersonMS** [comment]
BTW we also have an idea for a way of factoring out Razor content *without* it being a child component, i.e., just putting Razor content into methods you can call. That would be a more suitable form of factoring-out for the case in your benchmark.

However we haven't finished making the tooling understand this fully yet, so it's best to stick with regular components for now.

**Comment by arivoir** [comment]
I understand there could be an overhead, or an extra cost, but 75% decrease in performance just because I put a div inside a component sounds tooo much. If this is normal, I should avoid using components everywhere, and say customers do not customize cells using components, only use html, it really makes the platform unusable.

**Comment by SteveSandersonMS** [comment]
As I was trying to explain, whether or not to factor out some content into a component depends on your use case. The 75% number doesn't really mean anything - you could equally well argue that it shows how amazingly extra-good the perf is in the inline case. What matters is whether people actually produce apps that perform well in their real scenarios.

**Comment by arivoir** [comment]
> As I was trying to explain, whether or not to factor out some content into a component depends on your use case. 

I would have bet this was the case where it worth creating components, because functionally speaking it worth it, but I didn't expect such drawback in the performance. If only wrapping a div in a component creates that expensive operation I can't even imagine what will happen when nesting multiple components one inside the other.
Indirectly you're saying, if you have a customizable component that repeats the template, do not use components inside the template. It's too strong, and makes the platform really weak. I think you should rise the bar.

>  The 75% number doesn't really mean anything - you could equally well argue that it shows how amazingly extra-good the perf is in the inline case, and how tiny is the amount of other overhead elsewhere in the framework. 

Let me be clear, the performance is horrible in all cases, with or without the component, the client-side Blazor runtime must improve or the platform is unusable. I'm trying to help and reported a case where it concretely shows a 75% degradation in a scenarios that shouldn't be that bad, nor even close. It's up to you ignore it or not.

> What matters is whether people actually produce apps that perform well in their real scenarios.

I agree, but developers should work with a platform that allows them to create apps that perform well. The good side of Blazor is that allow creating reusable components, but then they can't use components because the performance is horrible and they need to end up emitting just html.
