### ISSUE TITLE
Blazor JSRuntime.InvokeAsync cannot handle nullable type

### ISSUE THREAD

**Issue by Behnam-Emamian** [aspnet/AspNetCore#10565]
### Describe the bug
I have a js function which can return a number or null, I cannot receive the null in c# by using this:
return await JSRuntime.InvokeAsync<int?>("JS function name", arguments)

### Expected behavior
I like to receive null from js

**Comment by AbhiAgarwal192** [comment]
Hi @Behnam-Emamian 

I was checking your issue but i did not find anything related to the above function in the repository.  If you can share code snippet of how you are using it then that might help me.

**Comment by Behnam-Emamian** [comment]
I have a js code like this:

`public addRecordAsync = async (databaseStore: IDatabaseStore, record: any): Promise<number> => {
        await this.openDatabaseAsync(databaseStore);
        const objectStore = this.db.transaction(databaseStore.storeName, 'readwrite').store;
        let itemToSave = this.checkKeyPath(objectStore, record);
        var result = await objectStore.add(itemToSave);
        if (isNaN(result))
            return -1;
        return result;
    }`

and I call it in c# like this:
`internal async Task<int> AddRecordAsync<TModel>(DatabaseStore databaseStore, TModel record)
        {
            try
            {
                return await CallJavascriptAsync<int>(DbFunctions.AddRecordAsync, databaseStore, record);
            }
            catch (JSException e)
            {
                RaiseNotification(IndexDBActionOutCome.Failed, e.Message);
                return -1;
            }
        }`

`private async Task<TResult> CallJavascriptAsync<TResult>(string functionName, params object[] args)
        {
            return await _jsRuntime.InvokeAsync<TResult>($"{InteropPrefix}.{functionName}", args);
        }
`

I need to receive null instead of -1 (as null)

**Comment by AbhiAgarwal192** [comment]
Ok got it.

**Comment by AbhiAgarwal192** [comment]
@Behnam-Emamian Did you try returning null from your javascript code which is getting invoked from _jsRuntime.InvokeAsync<TResult>().

**Comment by Behnam-Emamian** [comment]
yes, I cannot return null

in js, I have set return as Promise<number | null>

in c#, I have set return as _jsRuntime.InvokeAsync<int?>

**Comment by Behnam-Emamian** [comment]
I can catch the js exception and return null in c# part like this

`internal async Task<TEntity> GetRecordByIndexAsync<TEntity, TEntityIndex>(DatabaseStore databaseStore, string indexName, TEntityIndex searchQuery)
        {
            try
            {
                return await CallJavascriptAsync<TEntity>(DbFunctions.GetRecordByIndexAsync, databaseStore, indexName, searchQuery);
            }
            catch (JSException jse)
            {
                RaiseNotification(IndexDBActionOutCome.Failed, jse.Message);
                return default;
            }
        }`

**Comment by Behnam-Emamian** [comment]
but I still received the error message in console like this:

![image](https://user-images.githubusercontent.com/9818491/59002477-e8bfea80-8855-11e9-8aa0-9f1905c7d06a.png)

**Comment by mkArtakMSFT** [comment]
This should already be fixed. @Behnam-Emamian can you please verify this?

**Comment by mkArtakMSFT** [comment]
We think this was fixed already by us taking the updated serializer.
