### ISSUE TITLE
Why is client-side Blazor using .NET Standard 2.0 and how to use .NET Core 3.0 with Blazor?

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#10579]
### Describe the bug
how can i use <TargetFramework>netcoreapp3.0</TargetFramework> in client-side blazor. For mine Client side contains the <TargetFramework>netstandard2.0</TargetFramework>. I changed this in to netcoreapp3.0. but it throws the errors.

Can any one help on this?

### Additional context
I am using VS2019 preview version and netcore 3.0 preview5

**Comment by vova-lantsov-dev** [comment]
@kmuthukumar23 client side project is just a library that is attached to server project. Client's startup file is added to request processing pipeline (Configure method of Server.Startup class). So server project controls both client and server request handling.

**Comment by janellesnowy** [comment]
Same bug here, the template creates a .net standard 2.0 target project even though I chose dotnet 3 core

**Comment by DlbSt** [comment]
I believe that from preview 5 you can't use .Net Core 3.0 (connected with this issue - [https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&tabs=visual-studio#razor-class-libraries-not-supported-for-client-side-apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&tabs=visual-studio#razor-class-libraries-not-supported-for-client-side-apps)). You have to use .net standard 2.0.

**Comment by janellesnowy** [comment]
Thanks, this is quite a big concern. It means for client blazor, I have to pack all every resource into a dll, which could be very big and before anything can be rendered? How do I do dynamic loading?

**Comment by DlbSt** [comment]
I believe that some of your issue will be solved, when AOT compilation will be available - more here: [https://visualstudiomagazine.com/articles/2019/01/01/whats-new-in-and-getting-started.aspx](https://visualstudiomagazine.com/articles/2019/01/01/whats-new-in-and-getting-started.aspx). It should save some loading time.

**Comment by enetstudio** [comment]
@janellesnowy, this is definitely not a bug. The reason for this discrepancy, I believe, is that .NET Standard 2.0 is used on Blazor client because the underlying runtime is mono (.Net and not .Net Core)

**Comment by wrkettlitz** [comment]
> The Blazor project is already using the Mono AOT. It will be one of the first projects to transition to .NET 5. We are using it as one of the scenarios to prove out this plan.


.....


>All .NET 5 applications will use the CoreFX framework. We will ensure that CoreFX works well in the places it is not used today, which is primarily the Xamarin and client-side Blazor workloads.

....


>We intend to release .NET 5 in November 2020, with the first preview available in the first half of 2020.



https://devblogs.microsoft.com/dotnet/introducing-net-5/

**Comment by danroth27** [comment]
Hi @kmuthukumar23,

Client-side Blazor for WebAssembly only supports .NET Standard 2.0 today. It doesn't support the entire API surface area of netcoreapp3.0.

Server-side Blazor runs on .NET Core 3.0, so it supports the full netcoreapp3.0 surface area.

As @wrkettlitz mentioned, as part of the [.NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/) wave we plan to align the .NET WebAssembly efforts with the alignment of .NET Core and Mono at which point we will hopefully be able to align on a single target framework.

I hope this helps!
