### ISSUE TITLE
StringHtmlContent omitting characters when encoding

### ISSUE THREAD

**Issue by jimmymasaru** [aspnet/AspNetCore#10573]
### Describe the bug
When a `StringHtmlContent` writes a string containing a surrogate pair, it omits the immediate following single non-supplementary character.

### To Reproduce
1. Using this version of ASP.NET Core 2.2.5
2. Run this code
```
    var tearsOfJoy2 = new StringHtmlContent("😂2");
    using (var stringWriter = new StringWriter())
    {
        tearsOfJoy2.WriteTo((TextWriter) stringWriter, HtmlEncoder.Default);
        var encoded = stringWriter.ToString();
    }
```

### Expected behaviour
`encoded == "&#x1F602;2"`

### Actual behaviour
`encoded == "&#x1F602;"`

### Additional context
I have a feeling that the issue is within `System.Text.Encodings.Web.TextEncoder`.
If the the emoji is followed by 2 characters, like `new StringHtmlContent("😂22")`, it seems to be working correctly.

**Comment by AbhiAgarwal192** [comment]
Looks like there is some problem with how StringHtmlContent treats special characters. For your code to work you can try with WebUtility.HtmlEncode()

**Comment by jimmymasaru** [comment]
> 
> 
> Looks like there is some problem with how StringHtmlContent treats special characters. For your code to work you can try with WebUtility.HtmlEncode()

Thanks for the suggestion. I can even use `@tearsOfJoy2` to get the correct escaped output.
Actually, I was using `@Html.EditorFor()` and `<input asp-for"" />` when I found this issue. Then I digged into the source code and saw that eventually Razor uses the code in my main thread to generate HTML.
The code is simply a copy of [StringHtmlContent.DebuggerToString()](https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.ViewFeatures/src/StringHtmlContent.cs)
So this means all Razor help functions that eventually calls `StringHtmlContent` are affected by this issue.

**Comment by AbhiAgarwal192** [comment]
@jimmymasaru Yes looks like all functions calling StringHtmlContent are affected by this.

**Comment by ryanbrandenburg** [comment]
As best I can tell this is a problem in either `HtmlEncoder` or `StringWriter`. I filed #38184 for them to look at and will leave this issue open to track it.

**Comment by AbhiAgarwal192** [comment]
@ryanbrandenburg I have found the actual issue. Will fix it.

**Comment by AbhiAgarwal192** [comment]
Submitted a PR for this. This will get fixed in the next release.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg please validate this and close, when we get new dependencies.

**Comment by jimmymasaru** [comment]
Thank you everyone!
