### ISSUE TITLE
Separate Model Validation and Model Binding into dedicated packages

### ISSUE THREAD

**Issue by Yves57** [aspnet/AspNetCore#10571]
It would be nice to separate the *model validation* processing of ASP.NET in a dedicated package. I would like to be able to use it to check Azure Function parameters (for any triggers).
In the same way, it would be nice to split the *model binding* for HTTP triggers.

**Comment by mkArtakMSFT** [comment]
We do have the long-term goal to make this happen, but it's not easy nor straight forward. Closing this issue, as we track that effort separately
