### ISSUE TITLE
Java SignalR client clears authorization header after reconnect

### ISSUE THREAD

**Issue by dimkname** [aspnet/AspNetCore#10575]
Hello. 
My signalr hubs uses authentication based on Authorization header value.
For some reasons I am not using bearer token authentication scheme, so I cant use HttpHubConnectionBuilder.withAccessTokenProvider() method for authentication. 
Instead of this I use something like HubConnectionBuilder.create("https...").withHeader("Authorization", "somestring")

When disconnect occurred I am trying to perform reconnect to the server:

    connection = HubConnectionBuilder.create("...")
        .shouldSkipNegotiate(true)
        .withHeader("Authorization", "...")
        .build()

    connection.onClosed {
        connect()
    }
    ...
    fun connect(){
        connection.start()
    }

After reconnect server cant authenticate this client because of empty Authorization header.
It looks like issue in [HubConnection.java#L496](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java#L496)
I think that there should be check about token source and clearing authorization header only if its value was populated via access token provider

**Comment by mikaelm12** [comment]
Hmm interesting. The solution here might be to create an option on the `withAccessTokenProvider` api to not use Bearer auth. I don't think conditionally clearing out the Authorization header based on if it came from the token provider or not is the correct solution.

**Comment by anurse** [comment]
This looks like a bug to me. We shouldn't be messing with headers we didn't set.

**Comment by mikaelm12** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [ ] This is a Docs issue.
* [x] The fix contains product changes (**check all items below**).
	* [x] Relevant XML documentation comments for new public APIs are present. - Not needed
	* [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [x] The change requires no docs changes.
	* [x] Verification has been completed. (**check one item below**)
    	* [ ] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [VERSION]
			* ASP.NET Core Runtime: [VERSION]
			* .NET Core Runtime: [VERSION]
	    * [x] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: 3.0.0-preview7.19325.8
