### ISSUE TITLE
Request: allow dependency injection in RouteConstraints and IRouter

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/AspNetCore#10574]
Hi,

### Problem
Currently, the registration of `IRoute` and `IRouteConstraint` implementations is not adapted for dependency injection. In order to add implementations of those, one needs to explicitly initialize them.
My request is that you allow registering them so that they are resolved by the container when required.

For instance, I'm working on a multi-tenant app, and I want to make sure tenant exists before we're routing to controller etc. There is a catalog database containing the tenant info, and I'd want to break the routing if the tenant doesn't exist in the catalog DB.

### Solution
My request is that allow 'registering' `IRouteContraint`s implementations so that they are resolved by the DI container, instead of registering their type in the dictionary.
For example:

```c#
// Startup.cs
public void ConfigureServices(IServiceCollection services)
{     
      services.Configure<RouteOptions>(options => {
        // suggested:
        options.ConstraintMap.Register<SubdomainConstraint>();
      });
}

// SubdomainConstraint.cs

public class SubdomainConstraint : IRouteConstraint
  {
    // this provider uses the CatalogDbContext to check if tenant exists
    readonly ITenantProvider _TenantProvider;

    public SubdomainConstraint(ITenantProvider tenantProvider)
    {
      _TenantProvider = tenantProvider;
    }

    public bool Match(HttpContext httpContext, IRouter route, string routeKey,
         RouteValueDictionary values, RouteDirection routeDirection)
    {
      return _TenantProvider.Tenant != null;
    }
}
```

The same applies to `IRouter`:

```c#
// Startup.cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{     
    app.UseMvc(routes =>
    {
        routes.Routes.Register<SubdomainRouter>();
    });
}

// SubdomainRouter.cs

public class SubdomainRouter : IRouter
{
  readonly IRouter _DefaultRouter;
  readonly ITenantProvider _TenantProvider;

  public SubdomainRouter(IRouter defaultRouter, ITenantProvider tenantProvider)
  {
    _DefaultRouter = defaultRouter;
    _TenantProvider = tenantProvider;
  }

  public VirtualPathData GetVirtualPath(VirtualPathContext context) => 
      _DefaultRouter.GetVirtualPath(context);

  public Task RouteAsync(RouteContext context)
  {
    if (_TenantProvider.Tenant == null)
      context.HttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;

    return _DefaultRouter.RouteAsync(context);
  }
}
```

**Comment by weitzhandler** [comment]
I ended up achieving this with a middleware:

```c#
public class SubdomainTenantMiddleware
{
  readonly RequestDelegate _Next;
  public SubdomainTenantMiddleware(RequestDelegate next)
  {
    _Next = next;
  }

  public async Task Invoke(HttpContext context, ITenantProvider tenantProvider)
  {
    if (await tenantProvider.GetTenantAsync() == null)
    {
      context.Response.StatusCode = (int)HttpStatusCode.BadRequest;
      return;
    }

    await _Next(context);
  }

}

public static class SubdomainTenantMiddlewareExtensions
{
  public static IApplicationBuilder UseSubdomainTenant(this IApplicationBuilder app) =>
    app.UseMiddleware<SubdomainTenantMiddleware>();

}
```

Then 
```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    ... 
    app.UseSubdomainTenant();
    ...
}
```

**Comment by rynowak** [comment]
A middleware - or [`IEndpointSelectorPolicy`](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/Matching/IEndpointSelectorPolicy.cs) is a better way to achieve this. Route constraints are synchronous and that won't change.

**Comment by weitzhandler** [comment]
My problem with route constraints is not that it's synchronous but rather because it doesn't support DI.
I'm definitely going to check on `IEndpointSelectorPolicy`! Thank you.

**Comment by rynowak** [comment]
There are some cases where constraints support DI.  For instance if you're using Endpoint Routing in 2.2+ you can DI things if you use the inline syntax (`{foo:myconstraint}`). Like many things however, constraints have an arbitrary lifetime, so you can only use singleton services. 

I assumed you needed async because of this line in your example:
```C#
// this provider uses the CatalogDbContext to check if tenant exists
    readonly ITenantProvider _TenantProvider;
```

**Comment by weitzhandler** [comment]
Yes, it is async, not my biggest issue for now tho lol.

Any article that shows how to implement the endpoint selection interface and register it with the app?
Tried googling and reading some articles and haven't found any info about it.

**Comment by rynowak** [comment]
Thanks for the feedback, I'm logging an issue to add this to docs. Reminder that this is an endpoint routing feature (I see `IRouter` in your example). 

There's an example here (author is another individual at Microsoft):

https://github.com/microsoft/aspnet-api-versioning/blob/8afc8f9ae41a1ff2420f2eb407f802c25ef64ecf/src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.Extensions.DependencyInjection/IServiceCollectionExtensions.cs#L71
https://github.com/microsoft/aspnet-api-versioning/blob/a494c2cd2d13a41adca938543c1e52eb3c088ea1/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs#L23

Basics:
1. Implement a class that derives from `MatcherPolicy` and implements `IEndpointSelectorPolicy`
2. Register in DI as a singleton of `MatcherPolicy` using `TryAddEnumerable`

To implement `IEndpointSelectorPolicy`:

You can use `AppliesToEndpoints` to determine whether you policy applies to all endpoints, or specific sets. This will be called for each *group* of endpoints, which lets you look at them and decide if the policy would do any meaningful work. In the example, his policy only applies if the endpoints have a version associated. If you want your policy to always run, just return true.

Use `ApplyAsync` to do your work. You'll get an candidate set - which tells you what endpoints are in the group and whether they are matches or not with the information processed so far. 

For your use case, it sounds like you want to check if you have a tenant (I'm not sure what logic you use), and if you do have a tenent, just return. If you don't have a tenant, you could do two things:
- You could create a "not found" endpoint and set that on the context to short circuit
- You could iterate through the candidates and set them all to false with `SetValidity`

Short circuiting will cause the request pipeline to immediately execute that endpoint without further processing, similar to what you're doing today. The example I linked does [this](https://github.com/microsoft/aspnet-api-versioning/blob/a494c2cd2d13a41adca938543c1e52eb3c088ea1/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs#L191).

**Comment by rynowak** [comment]
Another note: we changed the signature of the API in 3.0 to remove the `EndpointSelectorContext` parameter, but the use case and functionality is unchanged.

**Comment by weitzhandler** [comment]
Thanks for your input, you're a true hero!

I tried implementing per your instructions, but since `ITenantProvider` is scoped and is dependent on `CatalogDbContext` (which is scoped as well), I registered `MatcherPolicy` as scoped as well, which then leads to this exception:

>InvalidOperationException: Cannot resolve 'Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder' from root provider because it requires scoped service 'Microsoft.AspNetCore.Routing.MatcherPolicy'.

**Comment by rynowak** [comment]
Right. These have to be singletons. 

If you want to participate in the request scope, use `HttpContext.RequestServices` to retrieve what you need.
