### ISSUE TITLE
Cannot find bin/obj directory for blazor app.

### ISSUE THREAD

**Issue by Gander7** [aspnet/AspNetCore#10585]
### Description
Cannot find bin directory for Blazor app.
Neither 'C:/Users....BBGrid/bin/debug' nor 'C:/Users...BBGrid/bin/release' exists on disk.

### To Reproduce
1. Using `3.0.100-preview5-011568`
2. `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview5-19227-01` as per https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio
3. `dotnet new blazor -o BBGrid`
4. `cd BBGrid`
5. `dotnet run`

### Expected behavior
Project to run

### Screenshots
bin/obj folders: https://i.gyazo.com/5b97ca49c9f5458e47f4b3a187824c8e.png
`dotnet run` output: https://i.gyazo.com/86578b19107317796a7aaec3fc79c7b0.png
`dotnet --info` output: https://i.gyazo.com/8853b0bf140c35b10e731980a465a447.png
Workaround folder structure: https://i.gyazo.com/db42ca0b333322ef7df9942fb6eacdf3.png

### Additional context
There seems to be a manual workaround. Looking at the bin/obj folders, if I move the debug folder outside the MCD folder so it's direct parent is the bin and obj, it will run successfully.
See workaround folder structure in screenshots. Unfortunately this isn't feasible if I have to do this every time the project builds :(

`dotnet build` does not solve issue :(

Possible Duplicate of https://github.com/aspnet/Blazor/issues/487

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Gander7.
What OS are you running this on?

**Comment by mkArtakMSFT** [comment]
@javiercn this is the second report of this issue we're facing so we need to investigate this. Please work with @Gander7 to get the information necessary to investigate.

**Comment by Gander7** [comment]
@mkArtakMSFT 
Windows 10 Home x64, 10.0.17763 Build 17763

**Comment by javiercn** [comment]
I definitely don't repro this on windows 10

**Comment by javiercn** [comment]
Tried this on a Win-7 VM
![image](https://user-images.githubusercontent.com/6995051/58641481-22ba4b00-82b0-11e9-994c-a909bc2ecd86.png)

No repro

**Comment by javiercn** [comment]
I'm not sure how you even get an MCD folder. could you run dotnet build /bl and attach the msbuild.binlog file produced?

That way we will be able to take a look at it and might figure out whats going on. But seems to be very specific of your environment.

**Comment by javiercn** [comment]
Closing as @SteveSandersonMS in the other bug mentions that this is very specific to the environment and we aren't able to repro it.

If we get a binlog, we will reevaluate.

**Comment by SIkebe** [comment]
@Gander7 HP machine? Is there 'Platform' environment variable?
I think this is not specific to Blazor...
https://github.com/OmniSharp/omnisharp-vscode/issues/2426

**Comment by Gander7** [comment]
@SIkebe it is an HP machine. I'll check for Platform environment when I get a chance.
@javiercn  I'll get .binlog when I get a chance.
We were able to repro it on a different laptop (same model).
If it's an env issue, probably is, that would be great as long as I can fix it :)

**Comment by havenindustries** [comment]
I am experiencing the exact same problem on a razer notebook.  Essentially the default blazor client template will not even build.  However an old school asp.net web application does build just fine.  All I did was update Visual Studio and the bug appeared.  Darn upgrades ... Ha!  Did you ever get this one resolved?

**Comment by SIkebe** [comment]
@havenindustries Did you check the environment variable?
https://github.com/aspnet/AspNetCore/issues/10585#issuecomment-497370895

**Comment by longhornleads** [comment]
I was able to build the example template fine last week but it suddenly stopped.  I have made no changes to environment variables.

**Comment by havenindustries** [comment]
I checked and that environment variable is not set.

**Comment by javiercn** [comment]
@SteveSandersonMS I believe I have something that can help with this. I changed how the devserver works as part of adding support for static web asssets and pass the target path from MSBuild. I believe that has potentially the side-effect or fixing this

**Comment by havenindustries** [comment]
@javiercn that would be amazing!  It's super frustrating because I love blazor and I want to get further on my project with it but I'm totally stuck on this simple build problem.
