### ISSUE TITLE
JWT + SignalR on ASP Core 3 Authentication Failing

### ISSUE THREAD

**Issue by mariocatch** [aspnet/AspNetCore#10582]
Full source here: https://github.com/mariocatch/ChatApp/tree/26_add_jwt

If I use http calls outside of signalr, such as with postman or httpclient, I am able to have my token validated successfully on the server. It's when I try to connect through my signalr hub that the token is not passing authorization.

>Bearer was not authenticated. Failure message: No SecurityTokenValidator available for token: Bearer MyTokenFooBar

My service setup is:

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddRouting();
        services.AddControllers();
        services.AddHealthChecks();
        services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(builder => { builder.ConnectionString = _configuration.GetConnectionString("DefaultConnection"); }));
        services.AddIdentity<ApplicationUser, IdentityRole>(setup =>
        {
            // foo
        }).AddEntityFrameworkStores<ApplicationDbContext>().AddDefaultTokenProviders();

        services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(options =>
            {
                options.RequireHttpsMetadata = false;
                options.SaveToken = true;
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = _configuration["Jwt:Issuer"],
                    ValidAudience = _configuration["Jwt:Audience"],
                    ValidateIssuer = false,
                    ValidateAudience = false,
                    ValidateIssuerSigningKey = false,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Jwt:Key"])),
                    ValidateLifetime = false
                };

                options.Events = new JwtBearerEvents
                {
                    OnMessageReceived = context =>
                    {
                        var path = context.HttpContext.Request.Path;
                        if (!path.StartsWithSegments("/chat")) return Task.CompletedTask;
                        var accessToken = context.Request.Headers[HeaderNames.Authorization];
                        if (!string.IsNullOrWhiteSpace(accessToken) && context.Scheme.Name == JwtBearerDefaults.AuthenticationScheme)
                        {
                            context.Token = accessToken;
                        }

                        return Task.CompletedTask;
                    }
                };
            });

        services.AddAuthorization();

        services.AddSignalR(options => { options.EnableDetailedErrors = true; });
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseRouting();
        app.UseAuthentication();
        app.UseAuthorization();
        app.UseEndpoints(options =>
        {
            options.MapHealthChecks("/health");
            options.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
        });
        app.UseSignalR(options => { options.MapHub<ChatHub>("/chat"); });
    }

I use a basic http auth header for the initial connection, which will sign the user into identity and generate a jwt token as a response for use in future calls.

    [HttpPost]
    [AllowAnonymous]
    public async Task<IActionResult> Login()
    {
        var (headerUserName, headerPassword) = GetAuthLoginInformation(HttpContext);
    
        var signInResult = await _signInManager.PasswordSignInAsync(headerUserName, headerPassword, false, false);
        if (!signInResult.Succeeded)
        {
            return Unauthorized();
        }
    
        var signingKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("SuperTopSecretKeyThatYouDoNotGiveOutEver!"));
        var signingCredentials = new SigningCredentials(signingKey, SecurityAlgorithms.HmacSha256);
        var jwt = new JwtSecurityToken(signingCredentials: signingCredentials);
        var handler = new JwtSecurityTokenHandler();
        var token = handler.WriteToken(jwt);
        return new OkObjectResult(token);
    }

And my client (a console application) is setup to cache this token and use it in future signalr calls as such:

Get the token:

    _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(encoding.GetBytes($"{userName}:{password}")));
    var response = await _client.SendAsync(request); // this goes to the login action posted above
    _token = await response.Content.ReadAsStringAsync();

...

    _hubConnection = new HubConnectionBuilder()
        .WithUrl(new Uri(_baseAddress, "chat"),
            options => { options.AccessTokenProvider = () => Task.FromResult(_token); }) // send the cached token back with every request
        .Build();
    
    // here is where the error occurs. 401 unauthorized comes back from this call.
    await _hubConnection.StartAsync();

The new `UseEndpoints(...)` lets you map hubs directly inside... but `app.UseSignalR(...)` requires configuration in order to be called. So since the configuration is actually being setup through `UseEndpoints(...)` now, does this mean we need `UseSignalR()` anymore? Should there be an empty overload of `UseSignalR()`? Should it be implicitly called for you if you map a hub through the `IEndpointRouteBuilder`?

I'm currently on:
C:\Users\mario>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

**Comment by mariocatch** [comment]
Note that if I add this to my hub controller (`class ChatHub : Hub`), then I receive an http 500 stating no authorization policy named 'Bearer' was found...
```cs
[Authorize(JwtBearerDefaults.AuthenticationScheme)]
```
This can be alleviated and I can get back to an http 401 by configuring the authorization options on in the configure services startup:

```cs
services.AddAuthorization(options =>
{
    options.AddPolicy(JwtBearerDefaults.AuthenticationScheme, policy =>
    {
        policy.AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme);
        policy.RequireClaim(ClaimTypes.NameIdentifier);
    });
});
```

**Comment by BrennanConroy** [comment]
>The new UseEndpoints(...) lets you map hubs directly inside... but app.UseSignalR(...) requires configuration in order to be called. So since the configuration is actually being setup through UseEndpoints(...) now, does this mean we need UseSignalR() anymore? Should there be an empty overload of UseSignalR()? Should it be implicitly called for you if you map a hub through the IEndpointRouteBuilder?

You can move your hub mapping into `UseEndpoints` now and get rid of the `UseSignalR` call if you want.

I believe the issue you're observing is because you have overwritten `OnMessageReceived` incorrectly. If you know your token is going to be from the "Authorization" header then you should leave it be and let the `JwtBearerHandler` handle it. In this particular case you're setting `Token` to "Bearer somevalue" but it is expected to be "somevalue". The `JwtBearerHandler` already does this automatically unless you've already set the `Token` to some value.

**Comment by mariocatch** [comment]
That was exactly it. I wasn't aware of the default impl of `JwtBearerHandler`. Looking at the source for it now I see it's doing exactly what I was going for (without knowing I didn't need the `Bearer ` prefix. Thanks!
