### ISSUE TITLE
ASP.Net Core 2.1 SPA templates have duplicate items in ClientApp directory in VS for Mac Solution Explorer

### ISSUE THREAD

**Issue by iantoalms** [aspnet/AspNetCore#10584]
### Describe the bug
.Net Core 2.1 Angular, React.js and React.js & Redux SPA templates have duplicated items in the project lists in the Solution Explorer.

### To Reproduce
1. Using latest version of .Net Core 2.1 e.g. 2.1.700
2. run the dotnet new angular command
3. Open the project with the latest VS4Mac 8.1 preview.
4. Expand the project in the solution explorer to see the contents of the ClientApp folder.
5. Notice that many of the .ts files are duplicated in the view.

### Expected behavior
The .ts file entries in the solution explorer are not duplicated.

### Screenshots
![Screenshot 2019-05-28 at 15 04 20](https://user-images.githubusercontent.com/14179593/58484927-f6d98100-815a-11e9-9e86-a84fb957192b.png)

### Additional context
This has already been fixed in the 2.2 and above templates with this change: https://github.com/aspnet/Templating/pull/560/files It seems that it never got back ported to 2.1.

**Comment by mkArtakMSFT** [comment]
We're closing this issue as we have heard no much concerns from the community regarding this behavior.
