### ISSUE TITLE
Question - How to turn .razor page into a cs class (with rendertree builder instructions)

### ISSUE THREAD

**Issue by detachmode** [aspnet/AspNetCore#10580]
Could not find any hints in the docu, online or while digging through the source code, so I ask it here.
Which class is responsible for parsing the razor syntax and creating the cs class which ends with razor.g.cs. I would like to create something were it would be nice to trigger it manually without the need to build the whole project.

**Comment by enetstudio** [comment]
I guess you mean BaseComponent.BuildRenderTree, right ?

**Comment by mkArtakMSFT** [comment]
This is not something we provide support for out of the box. StackOverflow may give you some suggestion though.

**Comment by detachmode** [comment]
A pitty that I couldn't get more concret directions of the developers themself, as I mentioned I already took some effort finding it out before posting it here.

Meanwhile I found something promising here:
https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentDiagnosticRazorIntegrationTest.cs
