### ISSUE TITLE
Support new contributors to this project by creating a "Good first issue" or "Help wanted" label.

### ISSUE THREAD

**Issue by Quenty** [aspnet/AspNetCore#10588]
I'm trying to find out good ways to start contribute to AspNetCore but there are no issues that are marked as "Good first issue" or "Help Wanted". This makes it very difficult to find tasks to work on, and discourages outside developers from working on the project.

**User story:** As a programmer, it's difficult to find ways to start contributing to AspNetCore projects.

### Proposed solution: A new "Good first issue" label
Create a new label as per the [Github Guidelines](https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels) to help new contributors find new issues that they can work on. 

The label should either contain the words

* Good first issue
* Help wanted

In order to have GitHub pick up the label as something to promote. This is not necessary as part of this proposal, but it would be nice. 

After a preliminary search it seems no such label exists. If such a label does exist, please rename it. Of course, this also requires you to label good first time issues.

#### Notes
* You can learn more about this here: https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels
* Here's a Microsoft product that does this properly: https://github.com/OfficeDev/office-ui-fabric-react/issues
* Can help with on-boarding new team members and interns too, by making it easy to pick tasks for them
* GitHub will automatically promote the labels if named properly. It will look like this: 

![image](https://user-images.githubusercontent.com/1774409/58497975-eeb91b80-8131-11e9-9b9f-bd9403dc3510.png)

#### Updating contributing guidelines
Additionally, updating the contributing guidelines to be more clear where users can start would be useful. Updating instructions for building would be good.

I understand it's important that users start a dialog before starting any tasks. However, it's important to also on-board new contributors to the project. This label would be a good step in this direction. 

#### Participate in Google Summer of Code
Participating in [Google Summer of Code](https://summerofcode.withgoogle.com/) would also be a good idea. Not only would it get students interested in contributing, it would also get you good feedback about how open your project is to outside contributions.

**Comment by Eilon** [comment]
Hi @Quenty , this repo uses the `up-for-grabs` label: https://github.com/aspnet/AspNetCore/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs

That label is applied when it's a "good first issue" and requires relatively little context.

**Comment by Eilon** [comment]
But perhaps this label should be renamed. "Back in the day" the `up-for-grabs` label was quite common; only later did the other label names become more common.

**Comment by natemcmaster** [comment]
I'm in favor of following the new GitHub guidelines. As Eilon mentioned, those guidelines are newer than our repos. Renaming a label should be trivial. We should check the other @aspnet repos, too.

Cc @pilchie

**Comment by natemcmaster** [comment]
We talked about it with our team, and I'll be updating labels and contributing guid later today to use GitHub's "help wanted" and "good first issue" conventions. Thanks for the suggestion @Quenty!

As far as your other suggestions:

* re: "Updating instructions for building would be good.". We already have a doc for this that we keep up to date. I'll add a link to it from CONTRIBUTING.md to https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md.
* Re: Google's Summer of Code - it looks like we missed the cutoff for participating as an organization for Summer 2019. But I'll keep this in mind for next year.

**Comment by Quenty** [comment]
Thank you so much!
