### ISSUE TITLE
API Review 3.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#10597]
Starting a brainstorming thread:

We need a better process for reviewing the way we make API changes. A group of managers and devs started reviewing 2.2 -> 3.0 changes today. It became clear that the volume of API changes is too large for a small group to handle, and that there will be many action items as a result of the API changes we made. I think it should be possible to do our API review process in the open on GitHub, but we need some tools and a workflow to do this well. 

Here are some open questions. I'd like to learn what other repos in .NET do before we implement something new.

* How does an intentional break get 
	* documented? 
	* approved? 
	* reviewed for impact?
* How can we catch unintentional breaking changes in review?
* How should we handle the review process for _new_ API?

cc @anurse @Pilchie @mkArtakMSFT @davidfowl @rynowak @pranavkm

**Comment by natemcmaster** [comment]
One concrete suggestion: 

  * @Pilchie suggested we use Microsoft.CodeAnalysis.PublicApiAnalyzers (see https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysispublicapianalyzers)

**Comment by Pilchie** [comment]
The good things about the analyzer package is:

1. Developers are made aware that they are making API breaking changes at compile time, but have a way to override that to accept the break.
2. There are well known files per project to review to see all changes that affect public API.
3. It can distinguish between APIs that have shipped and ones that haven't, so that you can have a lower bar for API changes before shipping, but still be aware of changes (say between Previews).

Downsides:
1. The unshipped tracking can be a bit of a pain if you are rapidly iterating on an API, but there are at least VS Codefixes to update the file.
2. The syntax of the file is hard to read, and it isn't always clear *why* a change breaks the API.

**Comment by anurse** [comment]
I like the idea of the analyzer, especially given that there are code fixes. It's better than our current ref-asm generation which is a bit of a trap for external contributors :).

I do like the pattern corefx has taken for API reviews. They have a flow where public API changes are marked `api-ready-for-review` by the "owners" for an area and then an API review group can quickly query for ready-for-review APIs and look at them. PRs involving public API changes can't be merged until the corresponding API review issue has been labelled `api-approved` (they have `api-needs-work` for sending the API back to the owners to be updated). More details: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

I don't think we need to be as rigid in all places as corefx, but the *process* feels smooth to me. For small changes, this can be done relatively quickly offline, see https://github.com/dotnet/corefx/issues/37701 for an example. I'd even suggest we can just do them in-situ in the PR. The labels also provide a clear way to track API changes across releases (as long as PRs are properly milestoned, which I've been trying to do as much as possible). The API review group could also apply `breaking-change` (if it isn't already) and that can serve as additional tracking (though there are non-API changes that are also `breaking-change`s).

I presume we could also make contributions back to the analyzer with improvements, so I think adopting something that already exists is preferable to building our own solution.

**Comment by natemcmaster** [comment]
I'd like it if we could put a file named "BreakingChanges.3.0.txt" in the ref/ folders. This would make it easy to concat all of them, and it also gives us history on which release contained breaking changes.

Re: Microsoft.CodeAnalysis.PublicApiAnalyzers

How does one go about marking a breaking change as "allowed"?

**Comment by Pilchie** [comment]
> How does one go about marking a breaking change as "allowed"?

The file has a way of adding a special line for removed APIs like [this](https://github.com/dotnet/roslyn/blob/80e9d1b75199aa9caeea8606d490ad0396ff4799/src/Compilers/Core/Portable/PublicAPI.Unshipped.txt#L1), so they show up as an add + remove.

**Comment by anurse** [comment]
Dispatching this to `area-infrastructure` for now since it's cross-cutting. We're working through this in a series of meetings.

**Comment by natemcmaster** [comment]
Tentatively putting on @anurse's plate (feel free to redistribute) and making this 'PRI 2'. I think it would be good to make some progress on this soon while we finish reviewing 3.0 API, but obviously, I'm on leave so won't be able to help.

**Comment by Pilchie** [comment]
@anurse - bump to Preview 9?

**Comment by anurse** [comment]
This is another thing we'll need to work on post-3.0. API reviewing in general needs work.

**Comment by Pilchie** [comment]
@anurse should this be closed/moved to a new milestone?

**Comment by anurse** [comment]
I think we should close this and take it up as a broader action item to build an API review process moving forward. I know @rynowak and @davidfowl have talked about this before. I believe the thought was that we have an API review process for "mature areas" which is fairly iterative (based off the corefx model) and involves reviewing each change. For "developing areas" (like Blazor was during 3.0) we would have a different process around reviewing APIs prior to release (to allow rapid iteration during development).

We could continue to use this issue to track that process development I suppose.

**Comment by mkArtakMSFT** [comment]
I think this should close. I have the API process review written up and will be sharing it over the email with the team later today.

**Comment by anurse** [comment]
Yep, we're doing the API review process. Closing this.
