### ISSUE TITLE
Use ngrok for Blazor apps for testing

### ISSUE THREAD

**Issue by sowsan** [aspnet/AspNetCore#10592]
Anyone been able to succesfully access a blazor app using ngrok ?

I have created few helloworld samples , **http://localhost:51586/** 

used ngrok , **ngrok http 51586**

Getting bad request , I believe there some special consideration needed with blazor?

![image](https://user-images.githubusercontent.com/11544153/58505026-fab8d380-8159-11e9-8113-d98afbc51e32.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sowsan.
This is caused by the headers not being properly forwarded and we're tracking that work as part of https://github.com/aspnet/AspNetCore/issues/10136 issue

**Comment by sowsan** [comment]
all of sudden it started working though :)
