### ISSUE TITLE
Make ConventionBasedStartup internal

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10595]
ConventionBasedStartup was made pubternal because it depends upon a pubternal type. We think this should actually just be made `internal` if possible.

https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/Hosting/src/Startup/ConventionBasedStartup.cs

cc @davidfowl @Tratcher

**Comment by Tratcher** [comment]
Only if we're going to do the rest of Hosting.

**Comment by davidfowl** [comment]
Sure why not.

**Comment by anurse** [comment]
This was done in 3.0. We just missed the issue.

**Comment by anurse** [comment]
https://github.com/aspnet/AspNetCore/pull/11505
