### ISSUE TITLE
Update dotnet-sql-cache to use Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#10599]
Follow up to https://github.com/aspnet/AspNetCore/issues/10013

dotnet-sql-cache uses System.Data.SqlClient. If there is sufficient interest, we could update it to use the new client, Microsoft.Data.SqlClient. The impact of this on consumers should be negligible because this package is a console tool and which version of the client should be hidden from the user.

**Comment by anurse** [comment]
I'll see if I can get this done to remove the System.Data.SqlClient dependency.

**Comment by anurse** [comment]
The basic work is done. #12957 is the follow-up to get us on RTM when their RTM is available.

**Comment by dougbu** [comment]
Why is this issue still open @BrennanConroy? Isn't everything tracked in #12957?

**Comment by anurse** [comment]
This [happened](https://github.com/aspnet/AspNetCore/blob/master/src/Tools/dotnet-sql-cache/src/dotnet-sql-cache.csproj), issue is just out of date :). Closing.
