### ISSUE TITLE
Editable config file on server for client-side Blazor project?

### ISSUE THREAD

**Issue by datvm** [aspnet/AspNetCore#10603]
### Is your feature request related to a problem? Please describe.
I am trying to use something like ASP.NET Core appsettings.json for Blazor. There is [this issue](https://github.com/aspnet/Blazor/issues/1152) from the old repository.

The solution seem to be using either embedded resources or embed in some DOM element. However, as the nature of client-side Blazor, they are compiled and cannot be edited without re-compiling the code.

People also suggest using HTTP request for settings, but let say, Api Url to begin with, how can your app have the Url before it fetches such settings? Still come back to hard-string/not-editable config.

### Describe the solution you'd like
There should be some way to read a file from server and/or packing additional file from the server.

It may happen when the server serving Blazor files starts (so we can change the settings, restart the server and new content is served).

### Describe alternatives you've considered
Maybe an editable Razor file in case we want to embed such settings in .razor file instead of separated appsettings.json.

### Additional context
None

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @datvm.
This is a known gap and we track that work at https://github.com/aspnet/AspNetCore/issues/5531
