### ISSUE TITLE
Why Websocket with ssl is 20x times slower?(AspNetCore v2.2.3)

### ISSUE THREAD

**Issue by InJoins** [aspnet/AspNetCore#10601]
**WebSocket with Ssl Echo Benchmark
test case: client connent->client send hello->server accept->server echo hello->client close.
between tests, codes are almost the same, there's definitely no changes in server side code,
just one line of code changed in client side(changed the connect uri from "ws://" -> "wss://")**

Server side:
OS: CentOS 7(machine one with 8 core)
AspNetCore 2.2.3

Client side:
OS: CentOS 7(machine two with 8 core)
NodeJS 10.x + uws

WebSocket Without SSL(**times/sec**):
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:16309
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:18035
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:17010

WebSocket With SSL(**times/sec**):
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:898
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:890
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:899

**1) SSL version is 20x times slower, but the expectation is 2x times slower like HTTP and HTTPS!
2) If it is because the code related to SSL layer(encryption and decryption) is too slow, the result of HTTPS should be as slow as the result of WSS
3) Just can processing only 800 new WEBSOCKET connections per second is too slow and abnormal for an 8-core host with a 10GB eth**

BTW, below is addition benchmark between HTTP and HTTPS, everything is ok!

**Http with Ssl Echo Benchmark
test case: client request->server reponse hello.
just one line of code changed in client side(changed the connect uri from "http://" -> "https://")**

Server side:
OS: CentOS 7(machine one with 8 core)
AspNetCore 2.2.3

Client side:
OS: CentOS 7(machine two with 8 core)
./wrk -t15 -c2000 -d9999s "http://10.0.0.10:5555"
./wrk -t15 -c2000 -d9999s "https://10.0.0.10:6666"

Http Without SSL(**times/sec**):
warn: WebSocketEcho.EchoMiddleware[0]
      http:283974
warn: WebSocketEcho.EchoMiddleware[0]
      http:276753
warn: WebSocketEcho.EchoMiddleware[0]
      http:281591

Https With SSL(**times/sec**):
warn: WebSocketEcho.EchoMiddleware[0]
      http:164822
warn: WebSocketEcho.EchoMiddleware[0]
      http:158194
warn: WebSocketEcho.EchoMiddleware[0]
      http:156951

Http request with SSL version seems ok.

**WHY?**
Thank you for any help and guidance.

**Comment by InJoins** [comment]
Server side test code:
`private Stopwatch watch = new Stopwatch();
        private int cnt = 0;
        private Stopwatch watchWs = new Stopwatch();
        private int cntWs = 0;

        public async Task InvokeAsync(HttpContext context)
        {
            if (context.WebSockets.IsWebSocketRequest)
            {
                ++cntWs;

                var webSocket = await context.WebSockets.AcceptWebSocketAsync();

                ArraySegment<byte> buffer = new ArraySegment<byte>(new byte[1024 * 4]);
                string message;
                WebSocketReceiveResult result;
                MemoryStream ms = null;

                try
                {
                    while (true)
                    {
                        result = await webSocket.ReceiveAsync(buffer, CancellationToken.None);
                        if (!result.CloseStatus.HasValue)
                        {
                            if (ms == null)
                            {
                                ms = new MemoryStream();
                            }
                            ms.Write(buffer.Array, buffer.Offset, result.Count);

                            if (result.EndOfMessage)
                            {
                                ms.Seek(0, SeekOrigin.Begin);
                                using (var reader = new StreamReader(ms, Encoding.UTF8))
                                {
                                    message = await reader.ReadToEndAsync();
                                    ms = null;

                                    var encodedMessage = Encoding.UTF8.GetBytes(message);
                                    await webSocket.SendAsync(buffer: new ArraySegment<byte>(array: encodedMessage, 0, encodedMessage.Length), result.MessageType, true, CancellationToken.None);
                                }
                            }
                        }
                        else
                        {
                            await webSocket.CloseAsync(result.CloseStatus.Value, result.CloseStatusDescription, CancellationToken.None);
                            break;
                        }
                    }
                }
                catch (WebSocketException e)
                {
                    if (e.WebSocketErrorCode != WebSocketError.Success)
                    {
                        webSocket.Abort();
                    }
                }

                if (cntWs >= 10000)
                {
                    lock (watchWs)
                    {
                        if (cntWs >= 10000)
                        {
                            if (watchWs.Elapsed.TotalSeconds > 0.001)
                            {
                                logger.LogWarning("websocket:" + (cntWs / watchWs.Elapsed.TotalSeconds).ToString());
                            }
                            watchWs.Restart();
                            cntWs = 0;
                        }
                    }
                }
            }
            else
            {
                ++cnt;

                await context.Response.WriteAsync("Hello World!");

                if (cnt >= 10000)
                {
                    lock (watch)
                    {
                        if (cnt >= 10000)
                        {
                            if (watch.Elapsed.TotalSeconds > 0.001)
                            {
                                logger.LogWarning("http:" + (cnt / watch.Elapsed.TotalSeconds).ToString());
                            }
                            watch.Restart();
                            cnt = 0;
                        }
                    }
                }
            }
        }
    }`

Client side test code(nodejs):
import * as uws from "uws-ts";

function create() {
    // const ws = new uws.WebSocketClient("ws://" + "10.0.0.10" + ":5555/");
    const ws = new uws.WebSocketClient("wss://" + "10.0.0.10" + ":6666/");

    ws.on("open", () => {
        ws.send("Hello World");
    });

    ws.on("message", (message: any) => {
        ws.close();
    });

    ws.on("close", (code?: number, reason?: string) => {
        setTimeout(() => {
            create();
        }, 1);
    });

    ws.on("error", (arg1: any, arg2: any, arg3: any) => {
        setTimeout(() => {
            create();
        }, 1);
        console.log(arg1 + arg2 + arg3);
    });
}

const numUserPerInstance = 100;
for (let i = 0; i < numUserPerInstance; ++i) {
    create();
}

**Comment by InJoins** [comment]
Server side test code:
```
namespace WebSocketEcho
{
    public class EchoMiddleware
    {
        private readonly RequestDelegate next;
        private readonly ILogger logger;

        public EchoMiddleware(RequestDelegate next, ILoggerFactory loggerFactory)
        {
            this.next = next;
            logger = loggerFactory.CreateLogger<EchoMiddleware>();
        }

        private Stopwatch watch = new Stopwatch();
        private int cnt = 0;
        private Stopwatch watchWs = new Stopwatch();
        private int cntWs = 0;

        public async Task InvokeAsync(HttpContext context)
        {
            if (context.WebSockets.IsWebSocketRequest)
            {
                ++cntWs;

                var webSocket = await context.WebSockets.AcceptWebSocketAsync();

                ArraySegment<byte> buffer = new ArraySegment<byte>(new byte[1024 * 4]);
                string message;
                WebSocketReceiveResult result;
                MemoryStream ms = null;

                try
                {
                    while (true)
                    {
                        result = await webSocket.ReceiveAsync(buffer, CancellationToken.None);
                        if (!result.CloseStatus.HasValue)
                        {
                            if (ms == null)
                            {
                                ms = new MemoryStream();
                            }
                            ms.Write(buffer.Array, buffer.Offset, result.Count);

                            if (result.EndOfMessage)
                            {
                                ms.Seek(0, SeekOrigin.Begin);
                                using (var reader = new StreamReader(ms, Encoding.UTF8))
                                {
                                    message = await reader.ReadToEndAsync();
                                    ms = null;

                                    var encodedMessage = Encoding.UTF8.GetBytes(message);
                                    await webSocket.SendAsync(buffer: new ArraySegment<byte>(array: encodedMessage, 0, encodedMessage.Length), result.MessageType, true, CancellationToken.None);
                                }
                            }
                        }
                        else
                        {
                            await webSocket.CloseAsync(result.CloseStatus.Value, result.CloseStatusDescription, CancellationToken.None);
                            break;
                        }
                    }
                }
                catch (WebSocketException e)
                {
                    if (e.WebSocketErrorCode != WebSocketError.Success)
                    {
                        webSocket.Abort();
                    }
                }

                if (cntWs >= 10000)
                {
                    lock (watchWs)
                    {
                        if (cntWs >= 10000)
                        {
                            if (watchWs.Elapsed.TotalSeconds > 0.001)
                            {
                                logger.LogWarning("websocket:" + (cntWs / watchWs.Elapsed.TotalSeconds).ToString());
                            }
                            watchWs.Restart();
                            cntWs = 0;
                        }
                    }
                }
            }
            else
            {
                ++cnt;

                await context.Response.WriteAsync("Hello World!");

                if (cnt >= 10000)
                {
                    lock (watch)
                    {
                        if (cnt >= 10000)
                        {
                            if (watch.Elapsed.TotalSeconds > 0.001)
                            {
                                logger.LogWarning("http:" + (cnt / watch.Elapsed.TotalSeconds).ToString());
                            }
                            watch.Restart();
                            cnt = 0;
                        }
                    }
                }
            }
        }
    }

    public static class EchoMiddlewareExtensions
    {
        public static IApplicationBuilder UseEcho(this IApplicationBuilder builder)
        {
            builder.UseWebSockets();
            return builder.UseMiddleware<EchoMiddleware>();
        }
    }
}
```

Client side test code(nodejs):
```
import * as uws from "uws-ts";

function create() {
    // const ws = new uws.WebSocketClient("ws://" + "10.0.0.10" + ":5555/");
    const ws = new uws.WebSocketClient("wss://" + "10.0.0.10" + ":6666/");

    ws.on("open", () => {
        ws.send("Hello World");
    });

    ws.on("message", (message: any) => {
        ws.close();
    });

    ws.on("close", (code?: number, reason?: string) => {
        setTimeout(() => {
            create();
        }, 1);
    });

    ws.on("error", (arg1: any, arg2: any, arg3: any) => {
        setTimeout(() => {
            create();
        }, 1);
        console.log(arg1 + arg2 + arg3);
    });
}

const numUserPerInstance = 100;
for (let i = 0; i < numUserPerInstance; ++i) {
    create();
}
```

**Comment by jkotalik** [comment]
I think this issue is better suited for the dotnet/corefx repo. @anurse thoughts/ can you move this issue?

**Comment by anurse** [comment]
It is certainly possible that WebSockets could be more affected by TLS performance drops than plain HTTP since it is much chattier. @davidfowl @halter73 @sebastienros does this 20% number (for WebSockets specifically) seem dramatically high to you? I figure you've all had some experience here with the impact of TLS on benchmarks :).

> I think this issue is better suited for the dotnet/corefx repo. @anurse thoughts/ can you move this issue?

@jkotalik it depends. But I do think this is more likely to be in Kestrel or `SslStream`, since WebSockets doesn't really do anything different based on the scheme (TLS or non-TLS).

**Comment by anurse** [comment]
@InJoins can you provide a runnable sample benchmark that can be used to reproduce the issue? I tried looking at your nodejs code and it seems to depend on libraries I can't locate on NPM (`uws-ts`) and I don't see where it produces the actual benchmark data.

**Comment by InJoins** [comment]
Thanks for your reply.
It’s professional, and make this question more clearly.

Affected by 20% slower is reasonable and acceptable, but in this benchmark, is 20x times slower.

It must be something went “wrong “ here

**Comment by InJoins** [comment]
@anurse I will upload a runnable project as soon as I can.

But I am installing windows 10 now...because VS cpu profiler tools can’t run on my computer(so I can’t profiling this ssl issues)

**Comment by anurse** [comment]
> Affected by 20% slower is reasonable and acceptable, but in this benchmark, is 20x times slower.

Whoops! You're right, that's almost definitely an issue.

I'd also suggest trying against a public WebSocket server (such as https://www.websocket.org/echo.html) just to ensure it's not an issue in your client library.

> I will upload a runnable project as soon as I can.

Thanks! That will help us get some more detail. And if you are able to get profiler tools running that will help too!

**Comment by sebastienros** [comment]
SSL handshake is very slow on Linux before 3.0.0-preview7. It has been improved two weeks ago and it would be great if you could test a nightly build with your benchmark. If you look at our benchmarks on https://aka.ms/aspnet/benchmarks, in the "Custom" page, check the ConnectionClose scenario under https. It similates htts endshakes. 

I don't know websockets well-enough, but I assume it should keep the same connection open, in which case the performance should be similar to http requests.

The first thing that needs to be done on our side is create a benchmark measuring the common scenarios of websockets, which we don't have today. @anurse do you think someone could help from your team? Or at least define the scenarios to benchmark?

**Comment by anurse** [comment]
> SSL handshake is very slow on Linux before 3.0.0-preview7. It has been improved two weeks ago

Do you mean before preview 6? If the improvement is in master, it should be shipping in preview 6 :)

**Comment by anurse** [comment]
> The first thing that needs to be done on our side is create a benchmark measuring the common scenarios of websockets, which we don't have today. @anurse do you think someone could help from your team? Or at least define the scenarios to benchmark?

Yeah, I agree that we should have a benchmark and that we can (and should) help out :). I believe we do already have a SignalR scenario which would be sufficient for testing WebSockets here.

**Comment by sebastienros** [comment]
Yes preview6.

**Comment by sebastienros** [comment]
I think SignalR benchmarks are http only. I talked to @BrennanConroy and we could create a simple server with an optional echo endpoint, and use this client https://github.com/satori-com/tcpkali

Should be pretty easy. We can simulate new connections to find the rate of connection creation, or reuse  them to measure latencies.

**Comment by InJoins** [comment]
@anurse @jkotalik @sebastienros
I uploaded a simplest project to github include server and client, at:
https://github.com/InJoins/WebSocketEchoBenchSSL

and I removed uws in client codes, because it's c++ based.
now, client code just use npm 'ws' instead, is pure js and widely used.
but I got the same benchmark results, SSL version is 20x slower.

If someone here will play with this project, it must reproduce.
I have bad english, please try clone and play around.

**Thanks for your help.**

**Comment by InJoins** [comment]
> SSL handshake is very slow on Linux before 3.0.0-preview7. It has been improved two weeks ago and it would be great if you could test a nightly build with your benchmark. If you look at our benchmarks on https://aka.ms/aspnet/benchmarks, in the "Custom" page, check the ConnectionClose scenario under https. It similates htts endshakes. 

Yes, the rps ratio between http and https in "that custom page/connection&close" is the same as my bench.
Just or less than two times.

> I don't know websockets well-enough, but I assume it should keep the same connection open, in 
which case the performance should be similar to http requests.

No, in my bench results on a linux server with 8cores, the rps ratio between websocket with and without SSL is 20x times.

> The first thing that needs to be done on our side is create a benchmark measuring the common scenarios of websockets, which we don't have today. @anurse do you think someone could help from your team? Or at least define the scenarios to benchmark?

Yes, definityely. especially the **connection&close rps** bench case **for websockets with/without SSL**. same as "that custom page/connection&close" case for http/https.

The great new .Net Core Framwork's vertical scalability is targets for millions rps(7-millions now exactly).
In my opnion this the most inportance key-feature, and we programmers care.

In my bench https://github.com/InJoins/WebSocketEchoBenchSSL
when do websocket with ssl, rps is just 8-hundreds with a 8 core linux server, which http rps is about 300-thousands on the same server.

Http rps(net core's record nowadays with a optimized directly respone back) -> http rps(my 8 core server with a normal framework-friendly http respone type) -> websocket with ssl(same as prev)
7,000,000 -> 300,000 -> 800

The first two test cases make sense, and 300,000 is very very good indeed, I can finally return to the arms of .net, whom I loved so long ago.

We develop games, now using node.js as the server, but its vertical scaling ability is too poor.
Game server is all about complex logicals and all about stateful any-where, vertical scaling ability is very important. If we use nodejs's single-thread pattern who can't do vertical scaling to scale-out,  plus its js/ts typeless language, I choose to die(joke).

Nowadays, so many programmers like me comes back, choosing .net core.
Very high performance with a multi-thread + async programming pattern, very strong c# language, and the best one of universe IDE visual studio.

It is very suitable for complex server project, especially for games server. If we make webs, I dont care .net or node or php or any others, its all can scaled out easily with tons of wheels.

Also, a short burst of new connections is important for game servers because users flood in at the same time when the service is first launched, so an ECHO DEMO with 800 RPS is not enough.

It's all about personal ideas. :)
I really hope the authorities of .net core can consider it. Pay more attention on this.
I really love .net. my first semi-commerce project was using .net when I was a student and young.

@sebastienros It seems that you are in charge of this matter, please.

**Comment by InJoins** [comment]
> @jkotalik it depends. But I do think this is more likely to be in Kestrel or SslStream, since WebSockets doesn't really do anything different based on the scheme (TLS or non-TLS).

It's a useful assert.
I'm a beginner to net core, just a little bit of a look at the source code, I think it should be as you said.

**Comment by InJoins** [comment]
I tried 3.0.preview6
CentOS 7.6
8core 10GB-eth

Websocket with SSL:
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:1121.1802028921745/sec
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:1461.692628381807/sec
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:1225.8078629891452/sec

WebSocket without SSL:
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:14147.833542249675/sec
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:16158.110823354114/sec
warn: WebSocketEcho.EchoMiddleware[0]
      websocket:14057.01446426064/sec

Almost same to v2.2.3, SSL version is 10x slower than without SSL.

BTW: 3.0.preview6 was slower than 2.2.3 without SSL (20000rps->15000rps) and faster than 2.2.3 with SSL (800rps->1200rps)
@sebastienros @anurse

**Comment by halter73** [comment]
> Based on the 'assert', why do the effects of TLS differ so much between HTTP and WEBSOCKET.

This is because HTTP clients can and do reuse underlying TLS connections which amortizes the cost of the TLS handshake across *many* requests. WebSocket requests cannot reuse the underlying TCP/TLS connection by spec, so they have to redo the handshake each time. TCP fast open only helps so much, and TLS session resumption isn't supported due security concerns. This is why TLS affects the performance of WebSocket requests far more than HTTP requests.

Comparing HTTP requests to similarly-sized WebSocket *messages* would be a **much more** apples-to-apples comparison than comparing HTTP requests to WebSocket requests.

Another way to make the comparison more fair would be to set the "Connection: close" header on the benchmarked HTTP responses which would force the HTTP client to renegotiate the TLS connection just like WebSocket clients are forced to do. This is the HTTPS ConnectionClose scenario @sebastienroswas referring to earlier.

**Comment by InJoins** [comment]
> This is because HTTP clients can and do reuse underlying TLS connections which amortizes the cost of the TLS handshake across many requests. WebSocket requests cannot reuse the underlying TCP/TLS connection by spec, so they have to redo the handshake each time. TCP fast open only helps so much, and TLS session resumption isn't supported due security concerns. This is why TLS affects the performance of WebSocket requests far more than HTTP requests.

thanks. very clear. you saved my life :-)

> Another way to make the comparison more fair would be to set the "Connection: close" header on the benchmarked HTTPS responses which would force the HTTP client to renegotiate the TLS connection just like WebSocket clients are forced to do. This is the HTTPS ConnectionClose scenario @sebastienroswas referring to earlier.

I tried this.
confirmed.
now https with "Connection: close" header has a 800 rps same to websocket with SSL.

One more question:
The rps with TLS handshake is 10 to 20 times slower. Is that normal? Is there room for improvement and optimization? If there is no or the priority is not high, then I will close this ISSUE.
@halter73 

BTW, My current solution is to add a load balancing server in front of the back-end server that offloads SSL from HTTPS to HTTP, so the back-end server doesn't need to think about SSL and has the same performance as without SSL.

Thanks for all your help.

**Comment by sebastienros** [comment]
@InJoins It's much better in 3.0.0-preview6 that will ship soon. The CoreFX team improved it on Linux by a factor of 3. It's still slower than on Windows though so there is room for improvement.

Your solution is the correct way to do it for now.
