### ISSUE TITLE
Consider adding metadata about exceptions thrown inside methods to method signatures

### ISSUE THREAD

**Issue by daoqiang** [aspnet/AspNetCore#10604]

**Comment by Eilon** [comment]
Hi @daoqiang , can you please provide more info about what you're looking for? Do you have an example you can share?

**Comment by daoqiang** [comment]
Referring to Java method signature, there is throws xxxException at the end of the method. I think it's a good design. After all, it's part of the grammar. net can only use method annotation to let the caller know what exception the current method will throw. Method annotation is often ignored.

**Comment by Eilon** [comment]
There's no such concept in .NET, and there's an old article by some of the original designers of .NET about why that is:

* https://www.artima.com/intv/handcuffs.html

**Comment by anurse** [comment]
It's possible to list these in XML doc comments (`<exception>` node) but nothing enforces it. I don't think this has value given that .NET has no mechanism to support it (and as @Eilon says, this is a an intentional decision and generally something we agree with).
