### ISSUE TITLE
Add ability to link a IAsyncEnumerable  to a SignalR Group

### ISSUE THREAD

**Issue by theduffmtl** [aspnet/AspNetCore#10606]
### Is your feature request related to a problem? Please describe.
We need to stream prices to a group of users base on their belonging to a group

### Describe the solution you'd like
My understanding is that right now the only way to stream thru IAsyncEnumerable  is to return  it to the  user thru the hub , . It would be great if I could bind a channel to a group so i get the power and performance and simplicity of it 

### Describe alternatives you've considered
right now we plan to use the group.sendasync 
### Additional context
we are using Azure SignalR

**Comment by davidfowl** [comment]
When you say bind a channel to a group, what do you mean exactly? What code do you want to write?

**Comment by tebeco** [comment]
I'm not really sure but does it would mean that on the `Hub` side pseudo code would look like
somewhere in the ioc a channel factory
```
if(NotExist(channelName)) // concurrent dictionary ?
{
var channel = Channel.CreateBounded<Poco>(....)
}
return channel
```

Somewhere else in a Service (can be done after a controller route being hit for example)
```
var channelFactory = serviceProvider.GetService<IFooChannelFactory>();
var hubContext = serviceProvider.GetService<IHubContext<StreamingHub>>();

var group = hubContext.Group("groupName")
var channel = channelFactory.Reader
group.Bind(channel.Reader) // that would fan put just like SendAsync already does
```

A background service could be in charge of only writing to a channel, thus decorelate it completely from any notion of Hub/client/group
```
var channelFactory = serviceProvider.GetService<IFooChannelFactory>();
var writer = channelFactory.GetOrCreate("myStreamFromWhatEver");
while(var data DataPolling()) // IAsyncEnumerable here ?
{
 writer.TryWrite(data);
}
```

**Comment by davidfowl** [comment]
Seems like it could be done today though right?

**Comment by tebeco** [comment]
well i think the question is about getting the same Api for both Client and Group
today the Client needs to subscribe to a stream

it look like the question is more about driving that logic from the hubContext itself

the result could be done kinda like `streamr` sample does but avoiding the round trip
on the client side it would look like a mix between `.on("eventName")` and `.stream("name").subscribe()`
this issue with that is ...
if the client have no idea of the group strategy (he really should not know), is there a way to stream from the `hubContext` to a `group` directly

**Comment by anurse** [comment]
You could definitely build this today by writing to a channel and having a background service read out of that channel and send messages using `IHubContext`. We don't have plans to make something built-in like that.

**Comment by theduffmtl** [comment]
ok I get it I thought that there was an advantage by using the IAsyncE but at the end everything end up on the connection.writeAsync. so using a channel in a background service like @anurse  said should do it

thks you guys
