### ISSUE TITLE
Make JsonArrayPool a public class (it is internal now)

### ISSUE THREAD

**Issue by mblataric** [aspnet/AspNetCore#10605]
I have some code from 2.2 relying on JsonArrayPool class which is internal in .NET 3.0 and can not be used any more. 
Any chance to make it public again?

**Comment by davidfowl** [comment]
I recommend copying the code into your project, it's like ~40 lines:

https://github.com/aspnet/AspNetCore/blob/2e8ae438633d5b0008bf531e9fe3291257990e95/src/Mvc/Mvc.NewtonsoftJson/src/JsonArrayPool.cs
