### ISSUE TITLE
Update all of the TagHelper's to support the RouteValueDictionary type

### ISSUE THREAD

**Issue by nickalbrecht** [aspnet/AspNetCore#10619]
I'm trying to compartmentalize all of the fields required for doing paging into a `RouteValueDictionary` that I can include in my view model(s), since that's what all of the underlying routing uses. This works fine for any of the `HtmlHelper` and `UrlHelper` methods that I've tried. But `RouteValueDictionary` is based off of keyvalue pair of `<string, object>` and all of the tag helpers will only accept <string,string> to their `asp-all-route-data` attribute. In spite of the underlying property property being called `RouteValuesDictionaryName`, it will not in fact accept a `RouteValuesDictionary`.

I'd like to see the tag helpers included in ASPNETCore updated so that their `RouteValuesDictionaryName` actually expects the name of a `RouteValueDictionary`. Or at the very least a collection that supports the same  underlying collection of `<string, object>`

Currently the only way I've gotten around this is every time I use a taghelper, I have to create a new collection that implements an enumerable of `<string,string>` instead of `<string,object>`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nickalbrecht.
This is not something we plan to change in the near future as we believe this is not a pain point for the community overall.
