### ISSUE TITLE
EndPoint routing and MapRazorPages and Map()

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#10612]
### Describe the bug
When EndPoint routing and Razor Pages are used within a mapped pipeline i.e `app.Map("/t1`
MapRazorPages() generates Endpoints for each of the Razor pages, but those generated routes do not take into account the mapped path i.e "/t1" and therefore do not match - for example if you have a page in Pages\Home.cshtml then the route will match "Home" but browsing the site on `/t1/Home` results in a 404. Browsing the site on /Home also results in a 404 because this means the mapped pipeline containing razor pages doesn't execute.

Here is a sample showing the issue: https://github.com/dazinator/DemoRazorPagesMapped

### To Reproduce
Run this sample: https://github.com/dazinator/DemoRazorPagesMapped

### Expected behavior
Should be able to run RazorPages and EndpointRouting in a Map()'d pipeline.

### Additional context
Include the output of `dotnet --info`

Stems from debugging an issue here: https://github.com/aspnet/AspNetCore/issues/10469

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
What are you trying to achieve? What is your goal? There is probably a better way to do what you want.

**Comment by dazinator** [comment]
My goal is for:

1. Razor pages to operate completely independently from one tenant to another. For example tenant T1 might have its razor pages /foo.cshtml in /T1 subfolder. Tenant T2 has its razor pages /bar.cshtml in its /T2 subfolder. When tenant T1 access the site through its URL www mysite.com/t1 then T2 razor pages should not be routable and vice versa. 

I've kind of achieved this goal by giving each tenant their own IServiceProvider and middleware pipeline. This means services are registered for each tenant rather than at application level and so can be configured for the specific tenant. With AddRazorPages that's great because you can specify the location on disk that contains that tenants pages. However when EndPoint routing middleware is executing in a mapped pipeline such as "/t1" and razor routes are generated, the generated routes don't take into account the current mapped path they are being generated on it seems instead that go from the sites root path "/". I don't foresee this being a problem when using different domain names to identify tenants for example www.t1.com and www.t2.com it just appears to be a problem when having to use Map().

**Comment by mkArtakMSFT** [comment]
@rynowak is the solution @dazinator achieved good for his scenario, or would we recommend something different?

**Comment by rynowak** [comment]
> I've kind of achieved this goal by giving each tenant their own IServiceProvider and middleware pipeline. This means services are registered for each tenant rather than at application level and so can be configured 

You will have to do this. MVC doesn't provide features oriented around doing things *per-tenant*. I'd strongly suggest looking at Orchard.Core and least copying the design/code where appropriate. It's not to build multi-tenant systems.

The other approach you could do would be to write an `IEndpointSelectorPolicy` that looks at the base-path. I'm not confident that this will meet all of your needs though.

Are you still stuck here? It sounds like you fount a solution.

**Comment by dazinator** [comment]
Thanks, yep I found a solution, I have a working multitenancy razor pages sample. I am pretty certain razor pages adds incorrect routes to endpoint routing though if you are using endpoint routing within a mapped path.. but luckily in my scenario as each tenant has it's own domain I dont need to use a mapped path to seperate tenants so if there is indeed a problem it's now a non issue.

**Comment by rynowak** [comment]
> I am pretty certain razor pages adds incorrect routes to endpoint routing though if you are using endpoint routing within a mapped path.. but luckily in my scenario as each tenant has it's own domain I dont need to use a mapped path to seperate tenants so if there is indeed a problem it's now a non issue

Map and routing don't interact at all. It's something that happens before routing runs - and removes the mapped segment from consideration:

Ex:
```
**Before Map**
Path: /map1/Foo/Bar
PathBase: /

**After Map (map1)**
Path: /Foo/Bar
PathBase: /map1
```

Routing looks at the Path and ignores PathBase
