### ISSUE TITLE
Question: 404 error for static files, AddSpaStaticFiles roothpath, SPA Template

### ISSUE THREAD

**Issue by vejandla** [aspnet/AspNetCore#10628]
I've created a react project using asp.net core react spa template. Everything seems to be fine, but when I deployed the application in IIS, it is deployed as an application under the default website. When I try to access the site, the index file is coming, but static files are giving 404.

One solution I found is setting PUBLIC_URL to application name in iis and building the application and then deploy. But, Is there any other alternative solution from asp.net core side? like setting rootPath

`// In production, the React files will be served from this directory
        services.AddSpaStaticFiles(configuration =>
        {
            configuration.RootPath = "ClientApp/Build";
        });`

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by scottaddie** [comment]
@SteveSandersonMS See the linked issue for more detail on the problem. Any ideas?

**Comment by Johnillo2411** [comment]
> I've created a react project using asp.net core react spa template. Everything seems to be fine, but when I deployed the application in IIS, it is deployed as an application under the default website. When I try to access the site, the index file is coming, but static files are giving 404.
> 
> One solution I found is setting PUBLIC_URL to application name in iis and building the application and then deploy. But, Is there any other alternative solution from asp.net core side? like setting rootPath
> 
> `// In production, the React files will be served from this directory services.AddSpaStaticFiles(configuration => { configuration.RootPath = "ClientApp/Build"; });`

I have the same situation, you can explainme exactly the solution you found.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg do you have any suggestion regarding this? Thanks!

**Comment by ryanbrandenburg** [comment]
I don't have a suggestion offhand, if this is something we want to look into lets put it in a milestone.

**Comment by vejandla** [comment]
> > I've created a react project using asp.net core react spa template. Everything seems to be fine, but when I deployed the application in IIS, it is deployed as an application under the default website. When I try to access the site, the index file is coming, but static files are giving 404.
> > One solution I found is setting PUBLIC_URL to application name in iis and building the application and then deploy. But, Is there any other alternative solution from asp.net core side? like setting rootPath
> > `// In production, the React files will be served from this directory services.AddSpaStaticFiles(configuration => { configuration.RootPath = "ClientApp/Build"; });`
> 
> I have the same situation, you can explainme exactly the solution you found.

There are two options and I guess this is nothing related to MVC, but it is more related to how create react webpack packages the bundle. 

**Solution 1**
if your website is hosting under a folder in IIS, use that folder name in the homepage property of package.json

"homepage": "/youriisappname/",

**Solution 2**
You can set public url before you build

```js
"scripts": {
    "start": "set PUBLIC_URL=/youriisappname/&&react-scripts start",
}
```
or (if the app name keeps changing between environments
```js
"scripts": {
    "start": "set PUBLIC_URL="entirewebsite url"&&react-scripts start",
}
```
