### ISSUE TITLE
Blazor and IOS Simulator

### ISSUE THREAD

**Issue by sowsan** [aspnet/AspNetCore#10624]
First, I'm not sure if this questions should be asked here :) 

I'm testing the blazor app and testing it mobile rendering using the safari browser in IOS Macbook pro latest with xcode simulator (XR). Server side blazor apps is rendering well within the browser but not web assembly based. Both client as well as asp.net core hosted not working. Its just showing the loading from the index.html not the actual app. If anyone want to test it, can use the blazor pizza app here : https://blazingpizzaapp1.azurewebsites.net/ and try it in the ios simulator.

**Comment by SteveSandersonMS** [comment]
Yes, the iOS simulator doesn’t support WebAssembly, though real iOS devices do support it. https://bugs.webkit.org/show_bug.cgi?id=191064

If you want this to change, please consider making your request to Apple.
