### ISSUE TITLE
Blazor Service-Side App Counter Page Does Not Work

### ISSUE THREAD

**Issue by mjhillman** [aspnet/AspNetCore#10622]
I created a new Blazor (server-side) web app using VS2019 Preview (16.2.0) Preview(1.0) and Core 3.0 Preview 5

The counter in the Counter.razor page does not increment.  No changes to the code, just the way it is out-of-the-box.  Seems the onchange event is not wired up. (This is a problem in IE 11, works as expected in FireFox)

**Comment by chrdlx** [comment]
IE11 is not supported at the moment

https://github.com/aspnet/AspNetCore/issues/9436
