### ISSUE TITLE
Ugly url in SPA template

### ISSUE THREAD

**Issue by Pilchie** [aspnet/AspNetCore#10627]
_From @Amine-Smahi on Tuesday, May 28, 2019 4:14:07 PM_

When requesting the fetch data component in any of the angular or react template without being authenticated we get back an ugly url

`https://localhost:5001/Identity/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DASP.NETCoreWebApplication2%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%253A5001%252Fauthentication%252Flogin-callback%26response_type%3Did_token%2520token%26scope%3DASP.NETCoreWebApplication2API%2520openid%2520profile%26state%3D2a2c1f381b274a06a09c836c6d63a33c%26nonce%3Dae2559be95624fb980b8cdfe41341cb7`

dotnet version 3.0 preview 5

_Copied from original issue: dotnet/core#2804_

**Comment by Pilchie** [comment]
_From @Pilchie on Tuesday, May 28, 2019 11:53:01 PM_

@ryanbrandenburg - any idea where this should be moved?

**Comment by Pilchie** [comment]
_From @ryanbrandenburg on Wednesday, May 29, 2019 8:48:10 PM_

https://github.com/aspnet/AspNetCore, with the tag "area-identity".

**Comment by blowdart** [comment]
@Amine-Smahi Is this an actual problem, or just one you feel looks horrible?

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
