### ISSUE TITLE
Question: Blazor client side prerendering - when?

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#10626]
I have just noticed here https://github.com/aspnet/AspNetCore.Docs/issues/11366 that a few days ago milestone for this issue was changed from 3.0.0-preview5 to Backlog. Does that mean that prerendering for Blazor client side is not planed in the near future?

**Comment by mkArtakMSFT** [comment]
@javiercn do we have all the pieces in place to do this in an app? If so, we should re-prioritize the documentation work for this.

**Comment by Andrzej-W** [comment]
Good news for all people interested in Blazor client side prerendering!
### We don't have to wait - it already works in Preview5!!!
Read here #10750, download sample code from @danroth27 and be happy.

And because it already works I'm closing this issue.
