### ISSUE TITLE
EndpointMiddleware will not work if SuppressCheckForUnhandledSecurityMetadata is true

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/AspNetCore#10649]
When `RouteOptions.SuppressCheckForUnhandledSecurityMetadata` is set to true, `EndpointMiddleware` would not execute any Endpoint.

I think the reason is `EndpointMiddleware` must skip checking for Auth and Cors Middleware, instead of return a CompletedTask.

This is the current code
```
if (_routeOptions.SuppressCheckForUnhandledSecurityMetadata)
{
    // User opted out of this check.
    return Task.CompletedTask;
}

if (endpoint.Metadata.GetMetadata<IAuthorizeData>() != null &&
!httpContext.Items.ContainsKey(AuthorizationMiddlewareInvokedKey))
{
    ThrowMissingAuthMiddlewareException(endpoint);
}

if (endpoint.Metadata.GetMetadata<ICorsMetadata>() != null &&
!httpContext.Items.ContainsKey(CorsMiddlewareInvokedKey))
{
    ThrowMissingCorsMiddlewareException(endpoint);
}
```

I think change it to this would solve the issue
```
if (!_routeOptions.SuppressCheckForUnhandledSecurityMetadata)
{
    if (endpoint.Metadata.GetMetadata<IAuthorizeData>() != null &&
    !httpContext.Items.ContainsKey(AuthorizationMiddlewareInvokedKey))
    {
        ThrowMissingAuthMiddlewareException(endpoint);
    }

    if (endpoint.Metadata.GetMetadata<ICorsMetadata>() != null &&
    !httpContext.Items.ContainsKey(CorsMiddlewareInvokedKey))
    {
        ThrowMissingCorsMiddlewareException(endpoint);
    }
}
```

**Comment by rynowak** [comment]
Thanks for reporting this. This indeed looks like a bug.

**Comment by rynowak** [comment]
Would you be willing to give us a little more information about why you needed to `SuppressCheckForUnhandledSecurityMetadata`? We included this so that users have a workaround for scenarios we didn't anticipate. If you're able to share, it would help us to know why you had to disable the security checks.

**Comment by Kahbazi** [comment]
To be honest I don't use 'SuppressCheckForUnhandledSecurityMetadata'. I was just studying the code for 'EndpointMiddleware' and found this bug.

**Comment by rynowak** [comment]
ok awesome! Apparently we missed a test for this 😢

**Comment by rynowak** [comment]
Thanks @Kahbazi
