### ISSUE TITLE
VS 2019 Preview + Blazor Asp.NET hosted not refreshing to reflect the changes

### ISSUE THREAD

**Issue by sowsan** [aspnet/AspNetCore#10657]
Latest VS 2019 Preview + Blazor extensions + ASP.NET core preview 5.

When I debug the application using VS 2019 and once I make any changes on the HTML I was expecting the already running UI will get updated without re running the application but its not. Do I need to make any settings to get this capability ?

**Comment by guidevnet** [comment]
This is not yet supported. Please see [this issue](https://github.com/aspnet/AspNetCore/issues/8071) for more details.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sowsan.
This behavior is going to be fixed in Preview6 / VS 16.2 Preview2 release.

**Comment by los93sol** [comment]
Did the fix make it in?  On preview 3 now and it doesn't seem to be working for me

**Comment by mkArtakMSFT** [comment]
@pranavkm FYI
