### ISSUE TITLE
Cannot rename properties/variables/methods referenced in blazor files in VS 2019

### ISSUE THREAD

**Issue by ErikApption** [aspnet/AspNetCore#10658]
### Describe the bug
Cannot rename any C# property/method/variable referenced in Blazor (.razor) files
Error happens with 3.0.0-preview5, VS 2019 preview and non preview.

### To Reproduce
1. Select a public property in a class used in blazor components
2. Right click and select rename
3. VS2019 will find all the right references
4. Apply 
5. "Changing document <blazor project>/Component1.g.cs is not supported"

### Expected behavior
All references renamed

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ErikApption.
Thanks for trying out Blazor.
@rynowak do you think this will be resolved when we enable `Partial Class` -es, or is this a pure tooling issue?

**Comment by rynowak** [comment]
This is a known feature gap in tooling. Razor does not have refactoring/rename support when initiated from another file.
