### ISSUE TITLE
Blazor app takes a long time to start up on phones, should I expect this time to greatly decrease in the future?

### ISSUE THREAD

**Issue by rxelizondo** [aspnet/AspNetCore#10666]
We just published a client side Blazor app to Azure. On average, it takes about 7 to 8 seconds to start the app on a Google Pixel 2 phone (this is a fairly new phone) and about 3 to 4 seconds on an iPhone 6s. This is not the first load by the way, this is every time the app is started.

Based on my research, this load time appears to be the time that is taking WebAssembly to load the .NET framework so that the .NET framework in turn can run the Blazor app. Is this the case?

I am a little concerned because this is just taking way too long. This app was supposed to be used by everyday people using everyday phones, but I just don’t see people being ok with waiting that long for the app to start.

So, my question is… are things expected to get a lot better in the future when it comes to startup times?

Note: We don’t want to use a server side Blazor app, our main motivation was to use a client side Blazor app because of the advantages it has over a server side Blazor app.

Have there been any benchmark studies that show how long it takes different phones to launch a client side Blazor app? Could it be that my Pixel phone is screwed up?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rxelizondo.
Thanks for trying out Blazor!
Blazor on WebAssembly is a new technology and has a lot of areas pending for further improvement. We are working closely with the folks from `https://github.com/mono/mono` to improve the performance.

As of today, we have no perf benchmarks available to share. These are things we would love to do, but we're quite a small team, and we choose the features in a way to add best value to our customers.

/cc @danroth27, @SteveSandersonMS, @rynowak

**Comment by McHeff** [comment]
Yeah running a hosted blazor app, off IIS, and accessing it through a phone, takes very long. 

On the initial load, first time running the app I mean, it took so long, all I saw was my spinner kit's loading gif, and because it took so long I assumed it didn't work, but when I looked at my phone a while later, there was my login page... Hope this gets better...

PS: The phone I'm using is an iPhone 7 plus, so should be able to load it fine?

**Comment by danroth27** [comment]
@McHeff Any chance it was a slow network issue?

**Comment by McHeff** [comment]
Hi @danroth27 , I don't think so, we have a 30mb fibre line at the office and off the touch screen and laptops we have, the web app opens and runs smoothly like it should, it's just off the initial load from a phone that takes quite long

**Comment by McHeff** [comment]
I will post some videos on my discord server for you @danroth27
