### ISSUE TITLE
Asp.net core 2.0 Razor Pages doesn't search RootDir\Shared for layout.

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#10665]
### Describe the bug
I have a new vanilla asp.net core 2.0 application (asp.net core 2.1 doesn't seem to exhibit this behaviour). 
I have some Razor pages under the /Pages directory. When I move them all (including the Shared folder) to live under a new sub directory, and then set the Razor Options "RootDirectory" to be this new location, MVC no longer searches in the "Shared" folder under this new root directory when finding the layout. 

The error is:
```
The layout view '_Layout' could not be located. The following locations were searched:
/Pages/Moogle/_Layout.cshtml
/Views/Shared/_Layout.cshtml
```

### To Reproduce
1. Create a new asp.net core 2.0 project
2. Create this razor pages structure:

```
/Pages/Shared/_Layout.cshtml
/Pages/Index.cshtml

```
3. Make sure Index.cshtml uses _Layout.
4. Verify everything works as expected.
5. Move the Shared folder and Index.cshtml into a new parent directory so you end up with this structure:
```
/Pages/Moogle/Shared/_Layout.cshtml
/Pages/Moogle/Index.cshtml

```
6. Configure Razor Pages options with the new root directory:

```
                                   .AddRazorPagesOptions((o) =>
                                   {
                                       o.RootDirectory = $"/Pages/Moogle";                                       
                                   });
```

7. Run the application. You'll get the error - it no longer searches the "Shared" folder in the new root location when resolving _Layout.

### Expected behavior
Using a new root directory should still resolve layouts as before.

### Additional context
Include the output of `dotnet --info`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
ASP.NET Core 2.0 is out of support. You have the option to move to a later version of ASP.NET Core where it's fixed or contact Microsoft support for other support options.

**Comment by dazinator** [comment]
Ah apologies. I commonly mis-remember which versions are on long term support, for some reason I always thing 2.0 is the long term support one!
