### ISSUE TITLE
Blazor Client app Debugging uses wrong url when using /BasePath

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#10685]
### Describe the bug
My blazor client app has a base href in index.html:
```
<base href="/Setup/" />
```
and I serve it from an asp.net core host using `app.Map("/Setup"`

```
            app.UseResponseCompression();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBlazorDebugging();
            }

            app.UseRouting();
            app.UseStaticFiles();
            app.UseAuthentication();
    
                app.Map("/Setup", (setupBranch) =>
                {                 
                    setupBranch.UseRouting();
                    setupBranch.UseEndpoints(endpoints =>
                    {
                        endpoints.MapDefaultControllerRoute();
                    });                   
                    setupBranch.UseBlazor<Client.Startup>();
                });

            app.UseEndpoints(endpoints =>
            {               
                endpoints.MapDefaultControllerRoute();
            });

```

This serves up the razor app on /Setup correctly.
However in chrome, when I press ctrl+shift+d it launches a tab with the following url:

http://localhost:62030/Setup/_framework/debug?url=http%3A%2F%2Flocalhost%3A62030%2FSetup

This results in a 404 due to the /Setup in the basepath. When removing /Setup from the URL the debugger launches.. 

### To Reproduce
As described above:
1. Host a Razor Client on a path using Map(), and put the correspoinding `<base href=` in index.html. 
2.  Navigate to the app in chrome and then launch the debugger using ctrl+shift+d

### Expected behavior
Debugger launches.

### Additional context
Include the output of `dotnet --info`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
@SteveSandersonMS can you please look at this.  Thanks!

**Comment by dazinator** [comment]
@SteveSandersonMS - hopefully before you waste any time dissecting this - I managed to solve it by including the RazorDebugging middleware in the same Map()'d middleware pipeline as the app. I assume this means if hosting several different blazor client apps on several different map()'d paths you have to add the razor debugging on each path.

**Comment by dazinator** [comment]
Closing for now. I'll reopen this if necessary, I have a way forward with debugging on a mapped path for now, and I am sure this will improve naturally anyway as the framework matures.
