### ISSUE TITLE
Identity Security Stamp mismatch during ConfirmEmailDataProtectorTokenProvider validation

### ISSUE THREAD

**Issue by CodingKobold** [aspnet/AspNetCore#10689]
Hello, it’s my first issue ever so I hope that I am posting this in the right place. I have a question regarding ASP.NET Core Identity Security Stamp. In our project we have an issue that happens occasionally. We are using ASP.NET Core 2.1.

We have following sign up procedure:
1.	Admin creates a user manually, under the hood `userManager.CreateAsync` method is called. Password is generated but is not used in the process whatsoever.
2.	Admin sends user an activation email, providing it with the token for resetting password (which includes security stamp value). When user enters the link, he must enter new password which will be further used in login. If during the validation in `ConfirmEmailDataProtectorTokenProvider.ValidateAsync` there is a mismatch on the user security stamp, password change fails. If it succeeds, the `userManager.ResetPasswordAsync` is called.

After research we’ve concluded that we do not use any UserManager methods which could change the Security Stamp value besides two used in above process, that is `userManager.CreateAsync` and `userManager.ResetPasswordAsync`. By our understanding, seeing different security stamps in the second step should never occur (by normal application usage), because there are no methods called that would potentially change the value. But for some reason it happens occasionally. We’ve set the logging in the reset password procedure, on the `ConfirmEmailDataProtectorTokenProvider` level, `ValidateAsync ` method:

```
Email stamp: 7bd27900-6720-4d5e-8601-e3c62d2a23bf
Database stamp: R6HSK7TRWZXC4Z7DJKVHA6YPQMLIQO5U
```

We noticed that one of the stamps was GUID and the other one is Base32 (which is used in our ASP.NET Core version – `UserManager.NewSecurityStamp`). After checking the DB, we’ve seen that there is no easily noticeable rule what type of security stamp is set on the user entity, but only about 6% was in Base32 notation.

Can you provide us with some guidance why that behaviour occurs? Could that be the case in the mismatch or maybe you have some other clue?

We’ve also checked that GUID was generated for security stamp in earlier version of .NET Core (2.0). We host our application as an Azure Web App, maybe something could go wrong while updating version of .NET Core on remote server? The project was started at 1.X (unfortunately I’m not sure about exact version) and was updated regularly so there were few such updates.
I’d be grateful for any help.

With regards,
Jacek

**Comment by blowdart** [comment]
Could we get a repo? Even a private repo would help, we'd like to look at how you're doing an email stamp.

**Comment by rolnikrolnik** [comment]
Hi, as I am working on the same project with @CodingKobold, I'll be probably able to provide you with some details. Unfortunately we can't share a repo for various reasons, however I don't think we are doing anything fancy. 

One application (let's call it admin panel) calls Web API that is exposed by another app (let's call it account app) in order to get a link for email confirmation. The admin app renders an email and sends it to the user with that link embedded. 

Account API where we create the token looks like this:
```c#
[HttpPost]
[Route("activationmail/send")]
public async Task<IActionResult> SendActivationAsync([FromBody] UsernameAndEmailWebModel usernameWebModel, [FromQuery] string languageCode)
{
    var user = await _userManager.FindByNameAsync(usernameWebModel.Username);

    if (user == null)
    {
        return BadRequest();
    }

    var activationUrl = await CreateActivationUrlAsync(usernameWebModel, languageCode);

    if (activationUrl.IsNullOrEmpty())
    {
        return BadRequest();
    }

    return Ok(activationUrl);
}

private async Task<string> CreateActivationUrlAsync(UsernameAndEmailWebModel usernameWebModel, string languageCode)
{
    var user = await _userManager.FindByNameAsync(usernameWebModel.Username);

    if (user == null)
    {
        return string.Empty;
    }

    var token = await _userManager.GenerateUserTokenAsync(user, TokenProviderType.ConfirmEmailTokenProvider, TokenPurpose.Confirmation);

    var baseUri = _serverSelfUriProvider.GetServerBaseUri();
    var relativeUri =
        $"Account/ActivateAccountLanguageChange?token={WebUtility.UrlEncode(token)}&languageCode={languageCode}";

    var uri = new Uri(new Uri(baseUri), relativeUri).ToString();

    return uri;
}
```

Please let me know if you need any other code from our side.

There is also another question. Why format of SecurityStamp in our DB differs? One time it is guid, another something that looks like Base64 ? Question out of curiosity I guess. We don't operate directly on IdentityDbContext so there is a slim chance we are actually the ones modifing it.

**Comment by blowdart** [comment]
We really can't progress this without a repo. Usually it's a data protection configuration mismatch. The stamp formats don't affect tokens in any meaningful way. I have to close this unless we get a small repro.
