### ISSUE TITLE
Blazor Client Side Project Razor tag InputNumber Visual Studio syntax error

### ISSUE THREAD

**Issue by zzhang2001** [aspnet/AspNetCore#10697]
In a Blazor Client Side project, the following InputNumber tag causes Visual Studio to display an error.

`<InputNumber id="todoPriorityNumber" bind-value="@newTodo.PriorityNumber" class="form-control" />`

This is the error message.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0411	The type arguments for method 'TypeInference.CreateInputNumber_0(RenderTreeBuilder, int, int, string, int, string, int, object, int, object)' cannot be inferred from the usage. Try specifying the type arguments explicitly.	BlazorClient1 C:\Users\vmtest\source\repos\BlazorClient1\BlazorClient1\Pages\Todo.razor	1	Active
```

However, the project can be compiled without error.

Changing attibute `bind-value` to `bind-Value` (uppercase V) seems make the error going away. However, the bind attribute should not be case sensitive.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @zzhang2001.
The problem you're facing is because component attributes are case-sensitive. This is by design.
