### ISSUE TITLE
Multiple Routes For a Razor Page

### ISSUE THREAD

**Issue by mxmissile** [aspnet/AspNetCore#10691]
### Razor Pages Feature Request
Asp.Net MVC supports multiple routes per action:
```
[Route("something/{id}")]
[Route("somethingelse/{id}")]
public ActionResult Index(int id)
```
I would love the ability for Razor Pages to support something like this at the page level. Something like:

`@page {"something/{id}","somethingelse/{id}"}`

Or support adding Route attributes to PageModels?

**Comment by pranavkm** [comment]
You could use a convention to do this: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-2.2#configure-a-page-route

**Comment by mxmissile** [comment]
Are you referring to using this?

` options.Conventions.AddPageRoute()`

**Comment by pranavkm** [comment]
Yup. You'd do something along the lines of: `options.Conventions.AddPageRoute("/MyPage", "/somethingelse/{id}")`

**Comment by mxmissile** [comment]
I have a scenario where I cannot get that to work:

Page: `Pages/Production/details.cshtml` `@page` directive is blank

Added this convention:  `options.Conventions.AddPageRoute("/production/details", "production/{id}/details");`

In the browser:
"/production/details" works
"/production/100/details" works

The issue is with tag helpers:

`<a asp-page="/production/details" asp-route-id="100">` works
`<a asp-page="/production/details">` **blank href**

**Comment by pranavkm** [comment]
Using `AddPageRoute` makes it the default route for link generation. Essentially any other route associated with that page do not participate in link generation. There's a bug in MVC where calling `AddPageRoute` multiple times prevents previously added route from being used for link generation. That said, you could write a convention that configures the routes for the page. Here's what the `AddPageRoute` does under the hood:

https://github.com/aspnet/AspNetCore/blob/b93bc433db66175d2b07b128ec9990f7a4dd7e1b/src/Mvc/Mvc.RazorPages/src/DependencyInjection/PageConventionCollectionExtensions.cs#L470-L490
