### ISSUE TITLE
Unknown disconnect happened and "ThrowInvalidOperationException_BackpressureDeadlock"

### ISSUE THREAD

**Issue by hours10000** [aspnet/AspNetCore#10701]
[coordserver.log](https://github.com/aspnet/AspNetCore/files/3242387/coordserver.log)
### Describe the bug
When I send several small message from signalr client to signalr hub，sometimes will raise a disconnect event. Message package is very small: 40B more or less ， one per millisecond . The hub side do some time-consuming operations, 2 second in one message process operation。

When disconnect happened, the exception is null:**`2019-05-31 22:06:36,494 [6] DEBUG (null) CoordServer.Hubs.ServerHub >>> OnDisconnectedAsync Start, exception: (null)`**

or **`:2019-05-31 22:13:40,699 [23] ERROR (null) Microsoft.AspNetCore.SignalR.HubConnectionHandler >>> Error when processing requests.
System.InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_BackpressureDeadlock()
   at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection).`**

From these links , I thought it maybe something about the size of ApplicationMaxBufferSize ,
but 

> Today SignalR needs to buffer the entire message before it calls your hub and it doesn't start consuming the buffer until it seems an entire message.

In my program, the message size is so small, why I still met this error？
Any helps? Thanks!

[2266](https://github.com/aspnet/SignalR/issues/2266)
[8142](https://github.com/aspnet/AspNetCore/issues/8142)
[2322](https://github.com/aspnet/SignalR/issues/2322)
[5307](https://github.com/aspnet/AspNetCore/issues/5307)

### Additional context
Microsoft.AspNetCore.SignalR.Client 1.1.0
Microsoft.NETCore.App 2.2.0

**Comment by hours10000** [comment]
[ChatSample.zip](https://github.com/aspnet/AspNetCore/files/3245547/ChatSample.zip)

Hi,
I tried with the sample in [SignalR-samples](https://github.com/aspnet/SignalR-samples),It's has the same problem。

**Comment by hours10000** [comment]
Hi,
I checked the source code, the disconnect:
`2019-05-31 22:06:36,494 [6] DEBUG (null) CoordServer.Hubs.ServerHub >>> OnDisconnectedAsync Start, exception: (null)`
comes from RunHubAsync function(in the right part of runasync.png ), 
Why the exception is null ?Maybe because the result.IsCanceled or result.IsCompleted (in the right part of dispatchMessageAsync.png).
But , my client is sending messages all the time when the server met the disconnect event.

Thanks.

![runasync](https://user-images.githubusercontent.com/4188708/58775300-65a15900-85f7-11e9-8e61-e8027f9cd3cd.png)
![dispatchMessageAsync](https://user-images.githubusercontent.com/4188708/58775301-65a15900-85f7-11e9-88ac-5a05169d9a82.png)

**Comment by davidfowl** [comment]
How big are the messages you are sending?

**Comment by hours10000** [comment]
Thanks for your response。

> How big are the messages you are sending?

About 40B, every messsage just contains a string ,like this "test:index:9-timestramp:1559313957345" .

**Comment by hours10000** [comment]
This is the definition of the message：

`   public interface IApiMessage { }
    public class W2CMsgGetListReq : IApiMessage
    {
        public string account;
    }`

**Comment by hours10000** [comment]
Hi , I know, the reason of the first disconnect exception:
`Client timeout (30021ms) elapsed without receiving a message from the client. Closing connection.`
Then, I will get this exception:
`DEBUG (null) CoordServer.Hubs.ServerHub >>> OnDisconnectedAsync Start, exception: (null)`

This is because the Hub function "MessageBoxGetList" is a time-consuming function， the DefaultClientTimeoutInterval is 30 seconds, So  If my Hub got 16 message (every message cost 2s) in one time , this exception will appear.

**Comment by hours10000** [comment]
But I still did not find out the reason why this happened:

`2019-06-06 19:39:34,256 [6] ERROR (null) Microsoft.AspNetCore.SignalR.HubConnectionHandler >>> Error when processing requests.
System.InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_BackpressureDeadlock()
   at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)`

I really did not send a huge message, and every message I send to Hub just in 40B more or less.

**Comment by BrennanConroy** [comment]
Took a look at this and your analysis is correct
>This is because the Hub function "MessageBoxGetList" is a time-consuming function, the DefaultClientTimeoutInterval is 30 seconds, So If my Hub got 16 message (every message cost 2s) in one time , this exception will appear.

The team will discuss this and decide on whether we can do anything here.

On a side-note, it's probably not a good idea to have your client send a message every millisecond if it takes the server 2 seconds to process the message.

**Comment by anurse** [comment]
Based on the investigation I don't think we have a clear idea on how to prevent this kind of overload in 3.0. Moving to the backlog.

> On a side-note, it's probably not a good idea to have your client send a message every millisecond if it takes the server 2 seconds to process the message.

@hours10000 This really is the source of the problem. If you take 2 seconds to process a message but messages are arriving consistently faster than that, you're creating an ever-growing queue. The ping timeout is a symptom of this, but I think you need some kind of batching on the client side to avoid overloading the server like this. As I said above, we do think we could do better at protecting you from this, but it's still a bit of a design problem to be sending messages much faster than you can process them.

**Comment by davidfowl** [comment]
In 3.0 the error won't happen, you'll just get throttled.

**Comment by hours10000** [comment]
Thanks for all your response about this disconnect event "OnDisconnectedAsync Start, exception: (null)"。
@BrennanConroy @davidfowl @anurse 
Yes,  I have done something on my client to avoid overloading the server like this 。

But I really want to know why I met this error "Error when processing requests. System.InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting" when I send message faster than server process,  all my message are 40B more or less.

**Comment by hours10000** [comment]
> In 3.0 the error won't happen, you'll just get throttled.
Hi, @davidfowl 
Allow me to confirm: Is your answer to this error : "Error when processing requests. System.InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting"  ?

**Comment by davidfowl** [comment]
> Allow me to confirm: Is your answer to this error : "Error when processing requests. System.InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting" ?Thanks.

Yes, this exception has been removed completely from 3.0.

**Comment by halter73** [comment]
I will add that in 3.0, you will only get throttled if you don't advance the "examined" position. If you "examine" untrusted data that arrives without bounds (maybe you're scanning for a separator token before parsing a message for example), you've just opened yourself up to a big memory leak.

**Comment by davidfowl** [comment]
That’s not exposed to SignalR users. We also have a max message limit in SignalR itself

**Comment by anurse** [comment]
We no longer throw this error in 3.0. There **is** still a maximum message size, but it is configurable (and docs will be updated).
