### ISSUE TITLE
Allow setting RenderFragments in .razor files

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#10700]
I created a component that has a property "MyTemplate" (Parameter) of type RenderFragment&lt;T&gt;. It works pretty well to customize the component.

```
<MyComponent>
    <MyTemplate>
        Some template
    </MyTemplate>
</MyComponent>
```

But I'd like to assign the template to a predefined icons I created in a separate library

```
<MyComponent>
    <MyTemplate>
        @C1IconTemplate.TriangleEast
    </MyTemplate>
</MyComponent>
```

Despite this "C1IconTemplate.TriangleEast" is of the same type RenderFragment&lt;T&gt;, the name of the class is printed in the html, because Blazor doesn't realize the variable has an actual render fragment and end up calling ToString().

I know I can workaround this to invoke the icon explicitly.

```
<MyComponent>
    <MyTemplate>
        @C1IconTemplate.TriangleEast.Invoke(...)
    </MyTemplate>
</MyComponent>

```
I think Blazor should check the type and avoid creating an extra fragment in this case. It would be better in terms of simplicity of the razor file as well as the performance.

**Comment by mkArtakMSFT** [comment]
Thank you for your feature request. We'll consider this feature during the next release planning period and update the status of this issue accordingly. To help us prioritize this feature correctly, please make sure you provide as much information as possible about the scenarios and their importance.

**Comment by mkArtakMSFT** [comment]
Looks like this is already implemented.

**Comment by SteveSandersonMS** [comment]
Try:

```
<MyComponent MyTemplate="@C1IconTemplate.TriangleEast">
</MyComponent>
```

**Comment by arivoir** [comment]
@SteveSandersonMS This is working. Thank you very much.

PS: The use of the "@" is unnecessary, because the attribute is interpreted as c# code directly, without needing the "@". I discovered this recently when trying to assign a string to a property whose type implemented the cast string operator and it didn't work. So, not needing the "@" looks as an advantage on the one hand, but a pain in the other. What do you think about this?
