### ISSUE TITLE
Fix MusicStore query tests once EF queries are working

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/AspNetCore#10714]
Collection Include in `StoreController.cs`:

```C#
var genreModel = await DbContext.Genres
                .Include(g => g.Albums)	
                .Where(g => g.Name == genre)
                .FirstOrDefaultAsync();
```

`SumAsync` in `ShoppingCart.cs`:
```C#
 return _dbContext
                .CartItems
                .Where(c => c.CartId == _shoppingCartId)
                .Select(c => c.Album.Price * c.Count)
                .SumAsync();
```

**Comment by smitpatel** [comment]
Collection Include is working. Sum is client eval due to decimal column and EF chokes while translating.  I will update EF to fail gracefully.

**Comment by anurse** [comment]
MikLabeller wants to put this in `area-mvc` :). Not sure where "MusicStore" belongs, but 🤷‍♂. Also sounds like @smitpatel is on the case, so maybe it doesn't matter as long as we know what the fix is.
