### ISSUE TITLE
Blazor - No element is currently associated with component XXXX

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#10715]
I'm having this exception when developing a component, and have no clue what's the problem.

> No element is currently associated with component 14

What does 14 mean? And why does this happen?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by arivoir** [comment]
I identified the problem and fixed it, but I had to comment code to "debug" and see where was the problem. 

This exception is pretty difficult to track, maybe there is a way to help to identify what is happening and where.
