### ISSUE TITLE
allow the connection logging to be configured via configuration

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#10720]
at present kestrel endpoints/listeners can be configured via configuration sources, however no option exists for the configuration of connection logging for the endpoints configuration section. please consider adding a boolean configuration value for the enpoint section 'EnableConnectionLogging' with a default of false.

**Comment by davidfowl** [comment]
Why do you need this?

**Comment by grahamehorner** [comment]
We would like to turn on/off additional listener logging to help diagnosis of issues using configuration rather the implementation of code switching

**Comment by davidfowl** [comment]
Can you explain the full scenario? I’m not against it but I want to understand what lead you to asking for this specific feature.

**Comment by grahamehorner** [comment]
We have a code where we have experienced issues with a badly behaved client causing network issues that impacted the service, we identified the issues using tools and by enabling listener logging, however these required deployment of code with listener logging enabled.  It would have been helpful to have these features enabled via configuration and  would have avoided delays in diagnosis and blocked the poorly written client from impacting others

**Comment by grahamehorner** [comment]
and could feed back to the aspnetcore team if/when appropriate

**Comment by davidfowl** [comment]
What was the client sending and what issues was it causing?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
