### ISSUE TITLE
How to add AspNetCore 3.0 packages to a standard library

### ISSUE THREAD

**Issue by SeriaWei** [aspnet/AspNetCore#10726]
I am trying to update my asp.net core application from runtime 2.2 to 3.0. But i found that, the packages about AspNetCore is also 2.2 in nuget.org and there are no preview packages. 

I have update my **library** from standard 2.0 to 2.1, but the `Routing` is also reference to 2.0 package
![image](https://user-images.githubusercontent.com/6006218/58744027-b8033e00-846e-11e9-82be-a780ce53a1b2.png)

And the application is reference to `netcoreapp3.0` Routing package so this is a mix reference, i cannot build my project.
![image](https://user-images.githubusercontent.com/6006218/58744046-2cd67800-846f-11e9-9eca-1a9779168dbb.png)

Is there any way to add the `AspNetCore 3.0` packages to a standard library project?

**Comment by davidfowl** [comment]
ASP.NET Core 3.0 doesn’t support netstandard it’s netcoreapp3.0 only. You need to add a FrameworkReference instead of a package dependency.

**Comment by SeriaWei** [comment]
@davidfowl Thanks for your replay!
But witch Framework should i reference to?

I have change my library `TargetFramework` to `netcoreapp3.0`,
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
</Project>
```
But it seems does not work, there are cannot find `Microsoft.AspNetCore.Routing` reference errors
![image](https://user-images.githubusercontent.com/6006218/58744960-8a24f600-847c-11e9-9e42-3d6f75c55b07.png)

**Comment by davidfowl** [comment]
This is how it should look in your project https://github.com/grpc/grpc-dotnet/blob/a0f0c915e5ddc351b54f396f7fab475973ac899c/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj#L26-L27

**Comment by SeriaWei** [comment]
@davidfowl Thanks, it works now!
