### ISSUE TITLE
Server Side Blazor - Links to razor pages don't work correctly

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#10732]
I was testing the issue fixed here

https://github.com/aspnet/AspNetCore/issues/9834

In the latest Preview6-012152,  and found out that while now the `<a href> `pointing to razor pages work fine....  when you arrive to the destination,  you cannot go back using the browser navigation controls.

I attach the gif showing what happens..
![ubg](https://user-images.githubusercontent.com/20750172/58750390-2e507200-8468-11e9-8c97-6353955df510.gif)

You can reproduce this with the default server side blazor template, just creating a .cshtml razor page, and inserting an `<a href="razorpageyoucreated"> `link inside the _host.cshtml page or any blazor component.  The result is the same, you cannot browse back using the browser navigation buttons.

Regards

**Comment by enetstudio** [comment]
I'm confused... I guess you're referring to Razor Components, right ? No Razor page concept in Blazor. The file extension in Blazor is .razor

Language is the source of misunderstanding ...

**Comment by chrdlx** [comment]
Another related issue with navigation:

Again, default ServerSide Blazor template.
If you go to the "counter" component... make some clicks in the button,  then navigate to "microsoft.com" or any website you want...  then go back with the browser navigation buttons,  the counter component doesn't work anymore until you 
1) Refresh the page F5  or  2) Go to the "fetch data" component and go back to the counter component.

![bug2](https://user-images.githubusercontent.com/20750172/58753674-7cca3480-8499-11e9-8512-61589cfd5b6a.gif)

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. I've created a fix for your top issue at #10839.

For the second issue you reported, I also think that's a valid bug, but it works best for us if each one is tracked in a separate issue, so I've re-filed your report at https://github.com/aspnet/AspNetCore/issues/10842
