### ISSUE TITLE
REST API Session pass session id from HTTP Header

### ISSUE THREAD

**Issue by elgunhuseynli** [aspnet/AspNetCore#10731]
I'm writing a mobile app which uses ASP.NET Core for it's backend. For authentication, i'm using sessions. But current implementation of sessions in ASP.NET Core only support getting session id from cookie which i'm not able to use cookies in mobile app.

There are some other ways to do authentication, like JWT. But JWT is not ideal for my app because users can login from different devices (multiple sessions) and there is an option like "log out from all devices" which i must invalidate all sessions (tokens in JWT) of user. Also I need to invalidate other sessions when user change it password.

So, I came up with an idea to use sessions and redis server for session storage. With this way I can delete sessions when needed.

Can we customize session middleware to read session id from http header?

**Comment by elgunhuseynli** [comment]
For example PHP's session is flexible enough to read session-id from request headers

```php
if ($request->headers->has('session-id')) {
    $session = new Session();
    $session->start();

    $sess = $session->get('session-id');
    $session->set('session-id', $sess);
    ...
}
```

I can't find anything about this in docs, it seems like ASP.NET Core's sessions are heavily depend on cookies.

**Comment by Kahbazi** [comment]
You can't change the way Session Middleware get the session id. What you can do is to add a Middleware before Session Middleware, which get session id from header and add it to cookie. You probably also need to add a session id if there's no header, so Session Middleware won't add any cookie

**Comment by elgunhuseynli** [comment]
> You can't change the way Session Middleware get the session id. What you can do is to add a Middleware before Session Middleware, which get session id from header and add it to cookie using 'Cookie protection.Protect()' . You probably also need to add a session id if there's no header, so Session Middleware won't add any cookie

Hmm... nice trick. But how can I generate session id to give it to the client when he login?

**Comment by Kahbazi** [comment]
You need to generate them exactly as it's done in `SessionMiddleware`. Take a look at this code

https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/Session/src/SessionMiddleware.cs#L96

**Comment by elgunhuseynli** [comment]
@Kahbazi thanks for your help. Your recommendation is the only workaround currently we can use.

Also my friend offered to use bearer tokens for authentication. Manually generate tokens and store them in redis server (Distributed Cache) and when needed to verify token, check if it's exist on redis server or not. With this way we can invalidate user's all sessions when wants to log out from all devices. But it seems like asp.net core only have `UseJwtBearerAuthentication()`. There is no something like `UsePlainBearerAuthentication()` to manually handle generation and verification of tokens.

Also there is a nice article about why not use JWT for sessions:
http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/

I searched docs for token based authentication but couldn't find anything about Digest, Basic or Bearer authentication. There is only `UseJwtBearerAuthentication`.

**Comment by elgunhuseynli** [comment]
Finally I find the solution in [this](https://joonasw.net/view/creating-auth-scheme-in-aspnet-core-2) blog. It is sad to see writing custom authentication scheme is not documented in docs.

Here is the example of custom authentication scheme read bearer token from request header.
```csharp
services.AddAuthentication("Basic")
    .AddScheme<MyAuthenticationOptions, MyAuthenticationHandler>("Basic", null);

public class MyAuthenticationOptions : AuthenticationSchemeOptions
{
    public string Realm { get; set; }
}

public class MyAuthenticationHandler : AuthenticationHandler<MyAuthenticationOptions>
{
    public MyAuthenticationHandler(IOptionsMonitor<MyAuthenticationOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock) : base(options, logger, encoder, clock)
    {
    }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        if (!Request.Headers.ContainsKey("Authorization"))
        {
            // Authorization header not in request
            return AuthenticateResult.NoResult();
        }

        if (!AuthenticationHeaderValue.TryParse(Request.Headers["Authorization"], out AuthenticationHeaderValue headerValue))
        {
            // Invalid Authorization header
            return AuthenticateResult.NoResult();
        }

        if (!"Bearer".Equals(headerValue.Scheme, StringComparison.OrdinalIgnoreCase))
        {
            // Not Bearer authentication header
            return AuthenticateResult.NoResult();
        }

        if (headerValue.Parameter == "1234")
        {
            var claims = new[] { /* user's claims */ };
            var identity = new ClaimsIdentity(claims, Scheme.Name);
            var principal = new ClaimsPrincipal(identity);
            var ticket = new AuthenticationTicket(principal, Scheme.Name);
            return AuthenticateResult.Success(ticket);
        }
        else
        {
            return AuthenticateResult.Fail("your token is invalid");
        }

    }
}
```

I am closing issue because problem solved. But we need to add this to docs.
And here is the releated issue in docs: https://github.com/aspnet/AspNetCore.Docs/issues/12656

**Comment by Tratcher** [comment]
Side note: Session should never be used for Auth data.

**Comment by blowdart** [comment]
Note that we don't use JWT for sessions, because, as Chris says we don't store authentication or authorization data in any type of session in asp.net. In fact it's deliberately decoupled from session, both for security and to allow for ease of scaling.
