### ISSUE TITLE
Possible regression with UseStatusCodePagesWithReExecute between 2.1 and 2.2

### ISSUE THREAD

**Issue by GitMonkey007** [aspnet/AspNetCore#10744]
If you use middleware UseStatusCodePagesWithReExecute in ASP.Net Core 2.2 you get different behaviour to that in 2.1. To verify this just change the CompatibilityVersion and observe different responses returned...

I've included all the necessary code to reproduce below...

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStatusCodePagesWithReExecute("/api/error/{0}");

            app.UseMvc();
        }
    }

    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            return new string[] { "value1", "value2" };
        }

        [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            return StatusCode(401); // any old error to cause re-execute
        }
    }

    [Route("api/error")]
    [ApiController]
    public class ErrorController : ControllerBase
    {
        [Route("{statusCode}")]
        public IActionResult Error(int statusCode)
        {
            if (statusCode == 401)
            {
                return new ObjectResult(new { StatusCode = statusCode, ErrorMessage = "NOT_AUTHORIZED" });
            }

            return new StatusCodeResult(200); // presume success for anything else for example purposes.
        }
    }

**Expected behavior**

With a url like:

http://localhost:1499/api/values/1

_**When using**_

`services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);`

The error controller correctly returns a custom response, like this:

`{"statusCode":401,"errorMessage":"NOT_AUTHORIZED"}`

_**When using**_ 

`services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);`

The error controller returns a response, like this:
`{"type":"https://tools.ietf.org/html/rfc7235#section-3.1","title":"Unauthorized","status":401,"traceId":"80000013-0001-fd00-b63f-84710c7967bb"}`

Expected the same result in 2_1 and 2_2.

From the debugging that I've done, I believe the problem is in StatusCodePagesMiddleware, where (in compatibility version 2_1) context.Response.HasStarted  is false

![image](https://user-images.githubusercontent.com/1216730/58762109-34b41c00-8544-11e9-86ac-71c082a06830.png)

However, with compatibility 2_2, context.Response.HasStarted is true...

![image](https://user-images.githubusercontent.com/1216730/58762134-92486880-8544-11e9-80a5-1b78f37e7682.png)

Not sure where to go with my debugging from here... any ideas on what the problem is with 2_2?

**dotnet --info**

.NET Core SDK (reflecting any global.json):
 Version:   2.2.107
 Commit:    2212cac826

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.107\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.2.100-preview2-009404 [C:\Program Files\dotnet\sdk]
  2.2.100-preview3-009430 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.107 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview2-35157 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview2-35157 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview2-26905-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27014-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by GitMonkey007** [comment]
Not sure how relevant this is, with a fuller solution using Api Versioning (and CompatibilityVersion 2_1), I need to set EnableEndpointRouting, as follows for this to work as expected.

            services
                .AddMvc(options =>
                {
                    options.EnableEndpointRouting = true;
                }).SetCompatibilityVersion(CompatibilityVersion.Version_2_1)

**Comment by Tratcher** [comment]
@mkArtakMSFT @rynowak What' behaviors are linked to CompatibilityVersion.Version_2_2?

**Comment by rynowak** [comment]
The complete list of changes that have compat switches is here: https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.Core/src/CompatibilityVersion.cs#L84

You can turn off this behavior by setting https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.Core/src/ApiBehaviorOptions.cs#L112 to true

**Comment by GitMonkey007** [comment]
@rynowak @Tratcher - Thanks both for your input, consider this solved.

For anyone else following...

With CompatibilityVersion.Version_2_2 and 

    services.ConfigureApiBehaviorOptions(options => options.SuppressMapClientErrors = true);

I return the result as expected.

Alternatively I can just do .SetCompatibilityVersion(CompatibilityVersion.Version_2_2); and implement IClientErrorFactory, replacing the ProblemDetailsClientErrorFactory as follows:

    services.Replace(ServiceDescriptor.Describe(typeof(IClientErrorFactory), typeof(MyCustomClientErrorFactory), ServiceLifetime.Singleton));

For validation failures I then implement InvalidModelStateResponseFactory.

I still have the following for status code pages and the exception handler:

            app.UseStatusCodePagesWithReExecute("/api/error/{0}");

            var exceptionHandlerOptions = new ExceptionHandlerOptions
            {
                ExceptionHandlingPath = "/api/error/500",
                ExceptionHandler = async (context) =>
                {
                    context.Response.StatusCode = StatusCodes.Status500InternalServerError;

                    var contextFeature = context.Features.Get<IExceptionHandlerFeature>();
                    if (contextFeature != null)
                    {
                        Logger.LogError(contextFeature.Error, $"Unhandled exception: {contextFeature.Error.Message}");
                    }

                    await Task.CompletedTask;
                }
            };
