### ISSUE TITLE
Microsoft.AspNetCore.Routing.RouteOptions.LowercaseQueryStrings = true not changing query string to lowercase

### ISSUE THREAD

**Issue by GodsWithin** [aspnet/AspNetCore#10746]
I'm trying to make it so that my application uses lowercase strings in the query section of a url. I've asked arond and looked at several stackoverflow questions. They all seem to suggest to set `LowercaseUrls` to `true` and `LowercaseQueryStrings` to `true` in the `ConfigureServices` method in `Startup.cs`. I've done so but my query section in the url still starts with an uppercase.

I'm using ASP.NET Core 2.2

The code where I add the RouteOptions to my services.
```cs
services.Configure<RouteOptions>(options =>
{
    options.LowercaseUrls = true;
    options.LowercaseQueryStrings = true;
});
```

The block of html where I link the input to a property in my `IndexModel`
```html
<form id="dateform">
    <div class="control-section">
        <div class="control_wrapper accordion-control-section">
            <div class="e-input-group">
                <input class="e-input" type="text" placeholder="Enter Date" asp-for="Date" />
                <span class="e-input-group-icon e-input-popup-date"></span>
            </div>
        </div>
    </div>
</form>
```

In my `IndexModel` class:
```cs
[BindProperty(SupportsGet = true)]
public string Date { get; set; }
```

`Date` does get filled with the value submitted in the form and my data is filtered just fine. But the url that is generated through this filtering has the query string `?Date=(value)`.

Perhaps it's also worth mentioning that I'm using Razor Pages.

**Comment by Kahbazi** [comment]
The reason is that this url is generated by browser and since input name is `Date`, it generates the url as it is but `LowercaseUrls` and `LowercaseQueryStrings` are used for generating links on the server.

**Comment by GodsWithin** [comment]
Then why does `LowercaseUrls` actually have the effect that it changes the name of my page to lowercase?
Example:
`LowercaseUrls = true` -> `https://localhost:5001/videos`
`LowercaseUrls = false` -> `https://localhost:5001/Videos`

**Comment by Kahbazi** [comment]
The reason is that link is generated on server

**Comment by GodsWithin** [comment]
So is there a way so the query string is in lowercase that is not changing the bindproperty's name to lowercase as well? (Date -> date)

**Comment by Kahbazi** [comment]
well you can set the name attribute yourself for input tag helper

`<input class="e-input" type="text" placeholder="Enter Date" asp-for="Date" name="date" />`

**Comment by GodsWithin** [comment]
I see, thank you for the explaination @Kahbazi
