### ISSUE TITLE
Dot Net core get null string when pass a empty string from action

### ISSUE THREAD

**Issue by amira133** [aspnet/AspNetCore#10742]
in asp.net we pass an empty string throws Action and get as an empty string. But in asp.net core when passing an empty string throws Action, we get a null string.

my question is why this happen and how to prevent from this in asp.net core?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
