### ISSUE TITLE
Blazor high performance - add option to serve cached static content

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#10748]
We are still waiting for prerendering in the Blazor client side but I suppose that we will have something like this:
1. Browser sends first request.
2. Server prerenders the page. In a typical application server will make a few database queries to prerender this page.
3. Browser loads prerendered page, CSS and JS files.
4. JS runs and loads Blazor application.
5. Blazor app makes a call to the server to read some data it needs to render the page. Server will make exactly the same database queries as in step 2.

Of course we can try to cache query results from step 2 and then use those cached values in step 5.

I would like to optimize step 2. Although almost all web pages today are build dynamically they are usually almost static when we look at their content. This content is sometimes changed once a day and sometimes only once a year or never. It makes sense to pregenerate this content and then serve it from static files. This idea is implemented in static site generators like Jekyll or Hugo.

Someone can say: Blazor is designed to create highly interactive applications - why do you want to use it to serve static files?

Answer is simple. In a typical e-commerce site you can have a lot of "almost static" content where you display information about products. You can sell highly customizable products and you want to implement this customization and shopping cart in Blazor. Of course all three elements (description, customization and shopping cart) are available on every product page. Web pages are used by real people but they are also scanned by different bots which are often interested only in static content. We don't want to loose precious server resources to dynamically generate these pages each time. We also want to return complete HTML page as fast as possible. This is good for search bots and of course for real people.

In Blazor clinet side in server project I would like to have an option to use prerendering as is (when super high performance is not critical) or add something like this:
```c#
if (DontCacheThisPage())
{
  return PrerenderPage();
}
else if (CachedContentAvailable())
{
  return CachedContent();
}
else
{
  string buffer = PrerenderPage();
  buffer = AddMetadata(buffer);
  StoreInCache(buffer);
  return buffer;
}
```
Of course all functions except `PrerenderPage` I want to implement myself. In those function I have to have access to HttpContext. As you can see I have `AddMetadata` function. I would like to use it to add some useful metadata in `<head>` section which is necessary for SEO and social media integration. Not cacheable pages are usually not intended for search bots and they don't have to have elements like `<description>`, `<meta>`, etc.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Andrzej-W.
We'll consider this in the future release.

**Comment by mkArtakMSFT** [comment]
@Andrzej-W can't this already be done using `CacheTagHelper` ?

**Comment by Andrzej-W** [comment]
I have just found a good example of prerendering for Blazor Wasm and checked `<cache>` tag helper. It looks that it works as expected, so I'm closing this. For reference see #14828
