### ISSUE TITLE
[Blazor server side] stop propagation of the event onclick/oncontextmenu

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#10761]
Hello !

This issue following this one which is old and seem have no really answer
https://github.com/aspnet/Blazor/issues/715

I wanted to know if there is a way to stop propagation of the event now. 

In my context, i want to stop it on the event contextMenu to prevent browser showing his context menu (and show mine instead)

the only way to do this actually seem attach the event in javascript and then call c# code, but it's a little complex and maybe there is better to do with blazor now.

Thanks for your responses !

**Comment by SteveSandersonMS** [comment]
This is tracked by https://github.com/aspnet/AspNetCore/issues/5545
