### ISSUE TITLE
[SignalR] (Hub)Exception in OnConnectedAsync sporadically not propagated to .NetClient

### ISSUE THREAD

**Issue by ddweber** [aspnet/AspNetCore#10766]
### Describe the bug
I want to conditionally block some .NET-Client from connecting with my Hub in the `OnConnectedAsync` overide method by throwing an (hub)exception so that in the client-code the exceptional state gets raised too.
Sporadically the (hub)exception does not get propagated to the client.

### To Reproduce
1. Using this version of ASP.NET Core '2.2.0', Microsoft.AspNetCore.SignalR.Client '1.1.0'
2. Using this code:

#### Server/Hub
```cs
namespace Server
{
    public class ChatHub : Hub
    {
        public Task SendMessage(string user, string message)
        {
            return Clients.All.SendAsync("ReceiveMessage", user, message);
        }

        public override async Task OnConnectedAsync()
        {
            await base.OnConnectedAsync();
            throw new HubException("Denied");
        }
    }
}
```

#### Client
```cs
namespace Client
{
    class Program
    {
        static async Task Main(string[] args)
        {
            try
            {
                HubConnection connection = new HubConnectionBuilder()
                .WithUrl("http://localhost:5000/ChatHub")
                .Build();

                await connection.StartAsync();
                await connection.InvokeAsync("SendMessage", "Me", "Hello");
            }
            catch (HubException hubEx)
            {
                Console.WriteLine(hubEx.Message);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }
}
```
3. Run the server and then the client (in my case an console app) multiple times (one at a time).
4. See that the exception is not raised on the second try
5. After server-restart the (hub)exception is working again (one more time)

### Expected behavior
 (Hub)Exception gets propagated to client properly every time.

### Screenshot
![image](https://user-images.githubusercontent.com/33422037/58801352-92ab3700-860a-11e9-9289-41b557e7d4d7.png)

### Additional context
.NET Core SDK
 Version:   2.2.106
 Commit:    aa79b139a8

Windows 7 - x64

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

**Comment by BrennanConroy** [comment]
`StartAsync` doesn't observe the hub method `OnConnectedAsync` before completing. If you change the try catch to be around `InvokeAsync` you'll see that the exception is actually coming from that call.
There is an implicit race between the connection closing from the server and the `InvokeAsync` call starting.

If you want to always observe the `HubException` then you need to wire up the `connection.Closed` handler

```csharp
connection.Closed += (ex) =>
{
    if (ex is HubException hubEx)
    {
        Console.WriteLine(hubEx.Message);
    }
    else
    {
        Console.WriteLine(ex);
    }
    return Task.CompletedTask;
};
```

**Comment by ddweber** [comment]
Thanks for your suggestion. I tried it but the race condition still remains.
`InvokeAsync` is called before the `connection.Closed` handler fires.

My demo client now looks like this:
```csharp
static async Task Main(string[] args)
{
    try
    {
        HubConnection connection = new HubConnectionBuilder()
        .WithUrl("http://localhost:5000/ChatHub")
        .Build();

        connection.Closed += (ex) =>
        {
            if (ex is HubException hubEx)
            {
                Console.WriteLine(hubEx.Message);
            }
            else
            {
                Console.WriteLine(ex);
            }
            return Task.CompletedTask;
        };

        await connection.StartAsync();
        await connection.InvokeAsync("SendMessage", "Me", "Hello");
    }
    catch (HubException hubEx)
    {
        Console.WriteLine(hubEx.Message);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
    }
    Console.ReadKey();
}  
```

**Comment by BrennanConroy** [comment]
>I tried it but the race condition still remains.

Correct, that will always be the case.

What are you trying to do exactly? Is observing the `HubException` twice an issue?

**Comment by ddweber** [comment]
> Correct, that will always be the case.

Ok then my initial idea:
> I want to conditionally block some .NET-Client from connecting with my Hub in the OnConnectedAsync overide method by throwing an (hub)exception so that in the client-code the exceptional state gets raised too.

will not work.

**Comment by ddweber** [comment]
I´m still confused why this is by design:

> StartAsync doesn't observe the hub method OnConnectedAsync before completing.


Because `OnConnectedAsync` is the suggested/only hook to [_Handle events for a connection_](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2#handle-events-for-a-connection). For me it sounds like if it is completed before the clients could invoke any further methods on the server.

Imagine the following usecase:

1. Client calls `StartAsync();`
2. Server does some connection mapping in `OnConnectedAsync() `
3. `StartAsync() `completes before mapping is completed
4. Client invokes Server method which relies on mapping-completition
5. Crash?

This usecase is pretty similiar to that what im going to do.

**Comment by BrennanConroy** [comment]
> 5. Crash?

The server will wait for `StartAsync` to finish before starting to process invokes from the client.

If you really want to wait for some mapping to finish before doing an invoke on the client you could set up a client handler that `StartAsync` calls.

```csharp
var tcs = new TaskCompletionSource<object>(TaskCreationOptions.RunContinuationsAsynchronously);
connection.On("Finished", () =>
{
    tcs.TrySetResult(null);
});
connection.Closed += (ex) =>
{
    tcs.TrySetCanceled();
};
await connection.StartAsync();
await tcs.Task;
await connection.InvokeAsync(...);
```

```csharp
public class ChatHub : Hub
{
    public override async Task OnConnectedAsync()
    {
        // mapping etc.
        await Clients.Client(Context.ConnectionId).SendAsync("Finished");
    }
}
```

**Comment by ddweber** [comment]
Thanks for the suggestion. I´ ll give it a try.
