### ISSUE TITLE
Apache mod_rewrite query string matches from RewriteCond not available in RewriteRule substitution when QSD flag used 

### ISSUE THREAD

**Issue by mikevh** [aspnet/AspNetCore#10768]
Using the rewrite rule below, read in from the mod_rewrites.txt. The resulting redirect does not have the report id value as expected at the end of the url. The %1 should have the value matched from the backreference to the RewriteCond line. This rule works as I expect on Apache

### To Reproduce
1. Using ASP.NET Core 2.2

2. Add mod_rewrites.txt with this rewrite rule in it
RewriteCond %{REQUEST_URI} /home
RewriteCond %{QUERY_STRING} report_id=(.+)
RewriteRule (.*) http://localhost:64782/home/report/%1 [R=301,L,QSD]

3. Add this call in Startup.cs
```
using (var sr = File.OpenText("mod_rewrites.txt")) {
    var rwo = new RewriteOptions().AddApacheModRewrite(sr);
    app.UseRewriter(rwo);
}
```
4. Add HomeController action
```
[HttpGet("/home/report/{id}")]
        public IActionResult Report(int id)
        {
            return Content("rewritten id = " + id);
        }
```
5. Run and navigate to http://localhost:64782/home?report_id=123

### Expected behavior
Rewritten URL is http://localhost:64782/home/report/123

### Actual behavior
Rewritten URL is http://localhost:64782/home/report/

### Additional context
This rewrite rule works as expected in Apache

Issue previously submitted as doc bug [here](https://github.com/aspnet/AspNetCore.Docs/issues/12613)

**Comment by jkotalik** [comment]
I confirmed this repro'd and have a fix in a PR.

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] Verified against ASP.NET Core App Version 3.0.0-preview7.19351.2
