### ISSUE TITLE
Rectify package.json file:// reference hacks

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#10775]
In preview6 I made changes to the SignalR and Blazor package.json files to use `file://` references. 

1) On Windows, `yarn install` causes the path specified in the `file://` directory to get copied in to the `node_modules` directory. Once `Restore` runs, Arcade ends up discovering the `npmproj` files in these directories and attempts to build them. We really don't want this to happen. Morever it's missing the closure of other files required to build (e.g. `../build/embed-version.js` that SignalR uses), so stuff just fails. I hacked around this for the time being here:

https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/ts/signalr/signalr.npmproj#L9

2) `npm pack` keeps the `file` references during pack. These need to be replaced by package reference to be correct. I made a change to use MSBuild's `ReadLinesFromFile` \ `WriteLinesToFile`, but as @natemcmaster pointed out, this has issues on xplat (slashes don't get preserved) as also formatting is affected.

**Comment by pranavkm** [comment]
cc @anurse \ @natemcmaster \ @BrennanConroy

**Comment by pranavkm** [comment]
cc @SteveSandersonMS

**Comment by anurse** [comment]
> 1. (slashes don't get preserved)

Is this a concern here since we're writing a version number, not a path?

**Comment by natemcmaster** [comment]
> > 1. (slashes don't get preserved)
> 
> Is this a concern here since we're writing a version number, not a path?

Yes, this is a legit concern. `WriteLinesToFile` is not x-plat friendly and would break any package.json file that has a backslash in it. e.g.
https://github.com/aspnet/AspNetCore/blob/34a68d5f4860e1e5767839695e45f1eeda4c9f2d/src/SignalR/clients/ts/signalr/package.json#L24-L25

**Comment by pranavkm** [comment]
Huh, I thought I wrote a comment here earlier. 
Specifically this line of code in `signalr-msgpack` fails today: https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/ts/signalr-protocol-msgpack/package.json#L24

The `\"` -> "/"` which results in an incorrect json file and prevents pack from working.

**Comment by anurse** [comment]
Now that this was punted from preview6, I'm going to close this since the hacks aren't there yet. We reopened #10307 to track the actual change (fixing the dependency to not suck).
