### ISSUE TITLE
Make SignalR JSON protocol case-insensitive by default

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10774]
In https://github.com/aspnet/AspNetCore/issues/10723 MVC changed it's default deserialization behavior to be case-insensitive, to match prior behavior in Newtonsoft.Json. We should do the same in SignalR.

Should be a simple matter of changing https://github.com/aspnet/AspNetCore/blob/670865d2a8997602ca2733cf15a9b74fbea399f9/src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs#L779

And, of course, updating any tests ;).

**Comment by BrennanConroy** [comment]
You want us to do this in preview6? Especially since I'm already messing around in that area.

**Comment by anurse** [comment]
Can we get it in by noon? :). If so, yes.

**Comment by BrennanConroy** [comment]
Well our build isn't fast enough to get it in by noon :/

**Comment by anurse** [comment]
:(

**Comment by BrennanConroy** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [x] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [3.0.100-preview7-012687]
            * ASP.NET Core Runtime: [3.0.0-preview7.19326.10]
            * .NET Core Runtime: [3.0.0-preview7-27826-04]
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
