### ISSUE TITLE
Validate Razor VSCode directive attributes tooling.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#10785]
Directive attributes are available from a tooling persepective in VisualStudio windows and VSCode. We need to verify they get appropriate completions, descriptions etc.

**Comment by ajaybhargavb** [comment]
@NTaylorMullen can we close this and have #10798 co-assigned to us? I created a [checklist](https://github.com/aspnet/AspNetCore/issues/10798#issuecomment-498460348) there we can both share.

**Comment by NTaylorMullen** [comment]
Ah, I see. Ok ya we can do that.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, @ajaybhargavb so is this a dupe? If so, please apply `duplicate` label
