### ISSUE TITLE
How to access a component instance from a javascript event? 

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#10783]
I created a component whose _BuildRenderTree_ method emits a "div" element. I need that div "onscroll" event to execute some JavaScript and call to the component after it. How can I achieve that?
According to the documentation, to call a method of the component from JavaScript it is necessary to have a reference

> Pass the .NET instance to JavaScript by wrapping it in a DotNetObjectRef instance. The .NET instance is passed by reference to JavaScript.

In the sample shown, it passes the reference from the server
```
    public Task CallHelloHelperSayHello(string name)
    {
        // sayHello is implemented in wwwroot/exampleJsInterop.js
        return _jsRuntime.InvokeAsync<object>(
            "exampleJsFunctions.sayHello",
            new DotNetObjectRef(new HelloHelper(name)));
    }
```
But in my case, I need the call to the component to be invoked directly from JavaScript (specifically from a function called onscroll event of div)
So I'm wondering whether there is a way to get the dotnet component reference from JavaScript?
Maybe I could pass the reference on the OnAfterRenderAsync method on the component and save it somewhere so when the onscroll event is raised I can use it, but this will need a separate call from server to the client every time the component is rendered. I bet this will be bad design. If I could somehow pass the reference in the BuildRenderTree, that would avoid the extra call.
Do you see my point?

**Comment by SteveSandersonMS** [comment]
> So I'm wondering whether there is a way to get the dotnet component reference from JavaScript?

Yes, that is exactly what the docs are describing when they talk about "wrapping it in a DotNetObjectRef instance".

> Maybe I could pass the reference on the OnAfterRenderAsync method on the component and save it somewhere so when the onscroll event is raised I can use it

Yes, that is precisely the correct way to do it! Looks like you're on the right lines :)

> If I could somehow pass the reference in the BuildRenderTree, that would avoid the extra call.

That's not applicable. The render tree is a structure that exists to be diffed, so the framework can issue a minimal set of UI update instructions. It's not a general bag of data that gets passed as a whole to JavaScript.

There's nothing wrong with having an extra call from .NET to JS in the first `OnAfterRenderAsync` invocation of your component. This only has to happen on the first render of each component, so no matter how many times the component re-renders, the JS-side code only has to be called once to receive the reference.

**Comment by arivoir** [comment]
It worked. Thanks for te answer. It really gives confidence on the direction of the development.
