### ISSUE TITLE
Changes needed to microsoft.extensions.apidescription.client targets and props files to work in Visual Studio

### ISSUE THREAD

**Issue by BillHiebert** [aspnet/AspNetCore#10789]
### Describe the bug
1.	Add AvailableItemName Items for OpenApiReference and OpenApiReferenceProject. Without these CPS doesn’t allow me to add items with this type. I manually modified the Microsoft.Extensions.ApiDescription.Client.props file with:
```
 <!--
    Well-known metadata of the code generator item groups.
  -->
  <ItemGroup>
    <AvailableItemName Include="OpenApiReference" />
    <AvailableItemName Include="OpenApiProjectReference" />
  </ItemGroup>
```

2.  We really need xaml rules defined for these item types. This provides a mechamism to be notified when a property on one of these items changes,  and provides F4 (property grid) support for defined properties. CPS auto-generates properties from the rules files and makes them available in the property gird – this  allows the customer to change values we don’t specifically have UI for. I created a placeholder file to test it out and wired it in by add a “tools” target file (see attached files, renamed with .txt). I imported the “tools” targets from the *.client.targets as follows:
```
  <!-- OpenApiProjectReference support. -->

  <Import Project ="$(MSBuildThisFileDirectory)Microsoft.Extensions.ApiDescription.Client.Tools.targets" Condition="Exists('$(MSBuildThisFileDirectory)Microsoft.Extensions.ApiDescription.Client.Tools.targets')" />
  <ItemGroup>
    <!--
```
[Microsoft.Extensions.ApiDescription.Client.Tools.targets.txt](https://github.com/aspnet/AspNetCore/files/3249026/Microsoft.Extensions.ApiDescription.Client.Tools.targets.txt)
[OpenApiItemsSchema.xaml.txt](https://github.com/aspnet/AspNetCore/files/3249027/OpenApiItemsSchema.xaml.txt)

**Comment by dougbu** [comment]
@BillHiebert is there a typo in your .targets change? Looks like it should be `Include="$(MSBuildThisFileDirectory)OpenApiItemsSchema.xaml"` rather than importing itself. The attached .targets.txt file looks closer though the condition isn't necessary if I'm understanding correctly. That is, we should ship the .xaml file in the Microsoft.Extensions.ApiDescription.Client package, thereby ensuring it exists. Or, should we look for the .xaml file somewhere else?

**Comment by BillHiebert** [comment]
@dougbu - you can certainly do that. I created a separate tools target which imports the xaml, and that line imports the tools target. This keeps tooling related functionality in a separate file but certainly not necessary or required.

**Comment by mkArtakMSFT** [comment]
@dougbu please prepare the fix, and we'll try to take this through QB approval process.

**Comment by dougbu** [comment]
2ea746f37d71
