### ISSUE TITLE
Directive Attributes validation

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10798]

**Comment by ajaybhargavb** [comment]
Checklist:

- [ ] Verify `@bind`, `@bind-*`, `@bind:...` and `@bind-*:...`
- [ ] Verify `@onclick` and friends
- [ ] Verify `@key`
- [ ] Verify `@ref`
- [ ] Mix it up with generic, child content, fully qualified components etc
- [ ] Verify diagnostics for old `bind-value-onchange` syntax
- [ ] Repeat the above steps for,
  - [ ] Runtime
  - [ ] VS
  - [ ] VS Code

**Comment by NTaylorMullen** [comment]
Extremely minor: https://github.com/aspnet/AspNetCore-Tooling/pull/662

**Comment by ajaybhargavb** [comment]
Verified runtime and VS

**Comment by NTaylorMullen** [comment]
Yup, and I had verified in VS Code
