### ISSUE TITLE
Validate LinkParser

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#10792]
## Summary

`LinkParser` is a new singleton service that can be used with endpoint routing to parse URL paths and extract route values.

The common use case for this is when you have URLs as part of your domain model. You want some way to parse these URLs using a well-known template and get route values (usually the id).

Example:

```C#
[HttpPut]
[Route("/Products/{id}", Name = "ProductsRoute")]
public async Task<IActionResult> AddRelatedProduct(int projectId, string path)
{
   var values = parser.ParsePathByEndpointName("ProductsRoute", path);
   var relatedId = (string)values["id"];

   // Do something with this information
}
```

## Checklist:

- [x] Can parse a path successfully with a known route (routename)
- [x] Fails for an unknown route (returns null)
- [x] Fails for a path that doesn't match
- [x] Includes default values from the route
- [x] Runs route constraints (use a route constraint that doesn't match)
- [x] Look at the logging for success and failure cases - is it good?

## References
 - PR: https://github.com/aspnet/AspNetCore/pull/9728
 - Issue: https://github.com/aspnet/AspNetCore/issues/4597

**Comment by ryanbrandenburg** [comment]
Everything behaved as expected and the console logging seems reasonable. At first glance the wording of the log seemed weird (endpoints vs address vs URI) but looking at it again I think you were just trying to be precise.
