### ISSUE TITLE
Single line C# in Razor

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10794]
This item encompasses the runtime and tooling support for single line C# control flow statements in Razor codeblocks.

I.e.:

```
@{
    if (true) Html.RenderPartial(...);
}

@functions {
    public void Foo()
    {
        if (false) return;
    }
}
```

Copied from: https://github.com/aspnet/Release/issues/349

**Comment by NTaylorMullen** [comment]
Verified
