### ISSUE TITLE
Verify TagHelpers in codeblocks result in useful diagnostics.

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10793]
We added an analyzer to notify users of invalid TagHelper usage in non-compliant codeblocks. Aka doing:
```
@{
    void Foo()
    {
        <a asp-action="..." ...>SomeTagHelper Link</a>
    }
}
```

Is technically invalid because `Foo` does not return `Task` and is not `async`

Copied from: https://github.com/aspnet/Release/issues/348

**Comment by mkArtakMSFT** [comment]
So I can confirm that this results in an error: 
![image](https://user-images.githubusercontent.com/34246760/58992731-74773f80-87a0-11e9-8827-123768c45fa2.png)

and the below fixed code is fine:
![image](https://user-images.githubusercontent.com/34246760/58992852-c28c4300-87a0-11e9-9a1b-c47894354264.png)

**Comment by NTaylorMullen** [comment]
Thanks @mkArtakMSFT looks great!
