### ISSUE TITLE
[Tooling] Verify C# 8 in Razor

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10795]
We added support for C# 8.0 in Razor. The various C# 8 features should be validated they work end-to-end in web apps.
- This should include runtime-compilation

Copied from: https://github.com/aspnet/Release/issues/336

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/AspNetCore/issues/10919

**Comment by NTaylorMullen** [comment]
Wasn't in Razor but in general for templates: https://github.com/aspnet/AspNetCore/issues/10921

**Comment by NTaylorMullen** [comment]
Verified
