### ISSUE TITLE
Runtime compilation & file watching

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10802]
We introduced a package in 3.0-preview4, but this was marred by requiring a flag to make it work in the project - https://github.com/aspnet/AspNetCore/issues/7966. In preview4, runtime compilation should just work for F# projects created from the template, and referencing the package should result in compilation of views and Pages.

This wasn't super well verified in preview4. There's also some changes around file watching that is going in preview6. I'll use this work item to do a verification for both of these.

**Comment by pranavkm** [comment]
There are some template cleanup we might want to consider: https://github.com/aspnet/AspNetCore/issues/10935, but the feature seems to work well.
