### ISSUE TITLE
Verify markup in local functions and @functions codeblocks

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#10803]
We added the ability to provide markup in local functions i.e.
```
@{
    void Foo()
    {
        <p>The time is @DateTime.Now</p>
    }
}

@{ Foo(); }
```
and in `@functions` blocks:
```
@functions {
    void Foo()
    {
        <p>The time is @DateTime.Now</p>
    }
}

@{ Foo(); }
```

This feature set should be functionally validated for Razor views. To make this set of features work in Components is a little more time consuming and not fully designed. i.e. you need to pass in extra parameters into your methods in order to utilize markup in the `@functions` block. Despite it not being fully designed it should still work in Components as well.

Copied from: https://github.com/aspnet/Release/issues/335
Please see referenced issue fore more details.

**Comment by Andrzej-W** [comment]
@mkArtakMSFT  is this a real syntax?
```c#
void Foo()
{
    <p>The time is @DateTime.Now</p>
}
```
Can we simply write HTML code in C# function? Can we use function parameters and full razor syntax in the function body, for example:
```c#
void Foo(bool useDiv)
{
    @if (useDiv)
    {
        <div>I'm DIV</div>
    }
    else
    {
        <p>I'm P</p>
    }
}
```
Will it be supported in `*.cs` files where we can create a definition for base Blazor compoment?

**Comment by mkArtakMSFT** [comment]
@Andrzej-W, yes, this is the new way of mixing code and markup and it's supported in .cshtml files. Unfortunately, not in `.cs` files.
@NTaylorMullen I assume this is also the case for `.razor` files, correct?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen I assume this is also the case for `.razor` files, correct?

Yes, however that experience is less fleshed out so in order to have markup in local functions/codeblocks in .razor files you must pass in a `RenderTreeBuilder builder` parameter.

**Comment by javiercn** [comment]
I remember validating this on preview5. @NTaylorMullen @ajaybhargavb what is new here to validate?

**Comment by NTaylorMullen** [comment]
Combine this with more complex C# like in lambdas, around single line C# expressions etc. We did work here to make C# in code blocks more C# compliant. Basically several bug fixes 😄

**Comment by Andrzej-W** [comment]
@NTaylorMullen
> in order to have markup in local functions/codeblocks in .razor files you must pass in a RenderTreeBuilder builder parameter.

Is it enough to have this parameter in a function as a marker or we have to use it to actually build render tree?

**Comment by javiercn** [comment]
Tried a bunch of stuff. Everything seems to be working just fine.
