### ISSUE TITLE
Override Blazor hub onconnect/ondisconnect/onreconnect

### ISSUE THREAD

**Issue by astecenko** [aspnet/AspNetCore#10835]
In the Server-side Blazor, I want to set up a reaction to the client connection, disconnection and reconnection. As I understand it, this can be done by overriding the corresponding hub blazor methods. But I can not figure out how to implement it. Is it possible to override the blazor hub (OnConnected/OnDisconnected/OnReconnected) methods? Maybe there are some events or callbacks for these (OnConnected/OnDisconnected/OnReconnected) purposes?

I need this to correctly handle client shutdown (destroy or re-create objects, etc.)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @astecenko.
This is possible today. You can implement a custom `CircuitHandler` and register it.
