### ISSUE TITLE
Razor silently fails if it expects IList model, but receives ICollection

### ISSUE THREAD

**Issue by achobanov** [aspnet/AspNetCore#10834]
I listed this as a bug, because Razor usually throws when it receives unexpected model.

### Describe the bug
I changed an existing editor template's model from `ICollection<int>` to `IList<int>` and then forgot to update the respective view models. The result is naturally flawed, but I would expect and Exception to be thrown in this case, because `IList<T>` is more specific then `ICollection<T>`.

### To Reproduce
1. Using this version of ASP.NET Core '2.2.0'
2. Pass `ICollection<int>` to a Razor view expecting `IList<int>`
3. Observe how the `Model` object and `ViewData` are default instances (or at least very close to)

### Expected behavior
In my opinion it should throw and Exception.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @achobanov.
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
@achobanov could you provide a repro application? I've tried reproducing what you're seeing but I'm seein an error (as expected) be thrown.
![image](https://user-images.githubusercontent.com/2008729/65450676-8aae1780-ddf2-11e9-8a19-0d598c01c8b7.png)

**Comment by achobanov** [comment]
Sadly, I cannot provide a code sample now - simply I can't remember exactly where I encountered the issue. If I am not mistaken, the view was editor template, specified with UiHint. When changing the view model to `ILIst` I forgot to update the model. The property value on the model is assigned via **AutoMapper** mapping from data model. I doubt this is going to help you a lot. What further information would have been useful in my original post?

**Comment by NTaylorMullen** [comment]
> What further information would have been useful in my original post?

You did a great job providing specific details in the original post. Only thing that would have helped would be a small repro project for us to try out.

**Comment by achobanov** [comment]
Alright. If you can't reproduce using editor template, I don't think I can me of more help. Thanks, keep up the good work ;)
