### ISSUE TITLE
Review and update THIRD-PARTY-NOTICES.TXT for 3.0

### ISSUE THREAD

**Issue by leecow** [aspnet/AspNetCore#10840]
Review and update repo THIRD-PARTY-NOTICES.TXT as appropriate. Work should be completed for Preview 7.

**Comment by mkArtakMSFT** [comment]
@anurse I was about to close then but then realised that there may be something here you'd like to add. Do you? If not, simply closed this issue please.

**Comment by anurse** [comment]
I believe everything we have is in the SignalR THIRD-PARTY-NOTICES file (https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/THIRD-PARTY-NOTICES) but I'm not sure if it should be moved forward to the repo-root one (they haven't been as of this comment).

**Comment by BrennanConroy** [comment]
I believe there are some additional updates needed, for example removing SimpleJson https://github.com/aspnet/AspNetCore/blob/077df0e3ca6849df8173ca818693dbf1d99fa512/src/Components/THIRD-PARTY-NOTICES.txt#L346 and @pranavkm noticed something we might need to add
