### ISSUE TITLE
JSON Deserialization of Derived types with $type not working in Blazor

### ISSUE THREAD

**Issue by RE-Butler** [aspnet/AspNetCore#10845]
I am trying to consume a WebAPI from Blazor. The WebAPI returns an object with a List of Base types. I configured Newtonsoft to include the $type value to that this can be deserialized on the client side in Blazor. I am using .Net Core 3.0 preview 5 with Blazor 0.9.0

This isn't working, so I set up the following demonstration:

```
    public class TestBase
    {
        public string BaseValue { get; set; }
    }
   public class TestDerived : TestBase
    {
        public string DerivedValue { get; set; }
    }
    public class TestList
    {
        public List<TestBase> TestListValue { get; set; }
    }
```

Here is the test deserializsation/serialization code:

```
public void SerializationTest()
        {
            string json;
            string json2;
            MemoryTraceWriter traceWriter = new MemoryTraceWriter();
            JsonSerializerSettings settings = new JsonSerializerSettings();
            settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            settings.StringEscapeHandling = StringEscapeHandling.Default;
            settings.NullValueHandling = NullValueHandling.Ignore;
            settings.TypeNameHandling = TypeNameHandling.All;
            settings.TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Full;
            settings.ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor;
            settings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            settings.TraceWriter = traceWriter;

            Console.WriteLine("Creating Objects...");
            try
            {
                json = "{\"$type\":\"TestNamespace.Models.TestList, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\",\"testListValue\":{\"$type\":\"System.Collections.Generic.List`1[[TestNamespace.Models.TestBase, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e\",\"$values\":[{\"$type\":\"TestNamespace.Models.TestDerived, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\",\"derivedValue\":\"DerivedValue\",\"baseValue\":\"BaseValue\"}]}}";
                TestList testList = JsonConvert.DeserializeObject<TestList>(json, settings);
                Console.WriteLine("Looping back to JSON:");
                json2 = JsonConvert.SerializeObject(testList, settings);
                Console.WriteLine(json2);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error:");
                Console.WriteLine(ex.Message);

            }
            Console.WriteLine("Trace:");
            Console.WriteLine(traceWriter.ToString());
        }
```

When I run that on the server, it works properly and the output of the traceWriter is:

> {2019-06-04T09:26:44.873 Verbose Resolved type 'TestNamespace.Models.TestList, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' to TestNamespace.Models.TestList. Path '$type', line 1, position 146.
> 2019-06-04T09:26:44.880 Info Started deserializing TestNamespace.Models.TestList. Path 'testListValue', line 1, position 163.
> 2019-06-04T09:26:44.893 Verbose Resolved type 'System.Collections.Generic.List`1[[TestNamespace.Models.TestBase, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' to System.Collections.Generic.List`1[TestNamespace.Models.TestBase]. Path 'testListValue.$type', line 1, position 435.
> 2019-06-04T09:26:44.897 Info Started deserializing System.Collections.Generic.List`1[TestNamespace.Models.TestBase]. Path 'testListValue.$values', line 1, position 447.
> 2019-06-04T09:26:44.898 Verbose Resolved type 'TestNamespace.Models.TestDerived, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' to TestNamespace.Models.TestDerived. Path 'testListValue.$values[0].$type', line 1, position 596.
> 2019-06-04T09:26:44.902 Info Started deserializing TestNamespace.Models.TestDerived. Path 'testListValue.$values[0].derivedValue', line 1, position 612.
> 2019-06-04T09:26:44.925 Info Finished deserializing TestNamespace.Models.TestDerived. Path 'testListValue.$values[0]', line 1, position 651.
> 2019-06-04T09:26:44.926 Info Finished deserializing System.Collections.Generic.List`1[TestNamespace.Models.TestBase]. Path 'testListValue.$values', line 1, position 652.
> 2019-06-04T09:26:44.927 Info Finished deserializing TestNamespace.Models Path '', line 1, position 654.
> 2019-06-04T09:26:44.927 Verbose Deserialized JSON: 
> {
>   "$type": "TestNamespace.Models.TestList, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
>   "testListValue": {
>     "$type": "System.Collections.Generic.List`1[[TestNamespace.Models.TestBase, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
>     "$values": [
>       {
>         "$type": "TestNamespace.Models.TestDerived, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
>         "derivedValue": "DerivedValue",
>         "baseValue": "BaseValue"
>       }
>     ]
>   }
> }
> 2019-06-04T09:26:44.938 Info Started serializing TestNamespace.Models.TestList. Path ''.
> 2019-06-04T09:26:44.941 Verbose Writing type name 'TestNamespace.Models.TestList, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' for TestNamespace.Models.TestList. Path ''.
> 2019-06-04T09:26:44.947 Info Started serializing System.Collections.Generic.List`1[TestNamespace.Models.TestBase]. Path 'testListValue'.
> 2019-06-04T09:26:44.947 Verbose Writing type name 'System.Collections.Generic.List`1[[TestNamespace.Models.TestBase, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' for System.Collections.Generic.List`1[TestNamespace.Models.TestBase]. Path 'testListValue'.
> 2019-06-04T09:26:44.947 Info Started serializing TestNamespace.Models.TestDerived. Path 'testListValue.$values'.
> 2019-06-04T09:26:44.947 Verbose Writing type name 'TestNamespace.Models.TestDerived, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' for TestNamespace.Models.TestDerived. Path 'testListValue.$values[0]'.
> 2019-06-04T09:26:44.952 Info Finished serializing TestNamespace.Models.TestDerived. Path 'testListValue.$values[0]'.
> 2019-06-04T09:26:44.953 Info Finished serializing System.Collections.Generic.List`1[TestNamespace.Models.TestBase]. Path 'testListValue'.
> 2019-06-04T09:26:44.953 Info Finished serializing TestNamespace.Models.TestList. Path ''.
> 2019-06-04T09:26:44.953 Verbose Serialized JSON: 
> {
>   "$type": "TestNamespace.Models.TestList, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
>   "testListValue": {
>     "$type": "System.Collections.Generic.List`1[[TestNamespace.Models.TestBase, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
>     "$values": [
>       {
>         "$type": "TestNamespace.Models.TestDerived, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
>         "derivedValue": "DerivedValue",
>         "baseValue": "BaseValue"
>       }
>     ]
>   }
> }}

When I run the same code in client-side Blazor, I get this output from the traceWriter:

> WASM: ﻿Creating Objects...
> blazor.webassembly.js:1 WASM: Error:
> blazor.webassembly.js:1 WASM: Error resolving type specified in JSON 'System.Collections.Generic.List`1[[TestNamespace.Models.TestBase, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Path 'testListValue.$type', line 1, position 435.
> blazor.webassembly.js:1 WASM: Trace:
> blazor.webassembly.js:1 WASM: 2019-06-04T15:24:55.579 Verbose Resolved type 'TestNamespace.Models.TestList, TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' to TestNamespace.Models.TestList. Path '$type', line 1, position 146.
> blazor.webassembly.js:1 WASM: 2019-06-04T15:24:55.585 Info Started deserializing TestNamespace.Models.TestList. Path 'testListValue', line 1, position 163.
> blazor.webassembly.js:1 WASM: 2019-06-04T15:24:55.601 Error Error deserializing TestNamespace.Models.TestList. Error resolving type specified in JSON 'System.Collections.Generic.List`1[[TestNamespace.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Path 'testListValue.$type', line 1, position 435.

The fact that the code is the same running in two places makes me think this might be a bug with the Newtonsoft implementation in Blazor, but I could be doing something wrong or maybe there are additional settings I need to implement?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RE-Butler.
This looks like a linker issue. Consider filing it in the `https://github.com/mono/mono` repo.
