### ISSUE TITLE
2.x Backport ConnectionId property to C# SignalR client

### ISSUE THREAD

**Issue by doctorpangloss** [aspnet/AspNetCore#10849]
https://github.com/aspnet/AspNetCore/blob/b6d8c96a98c9e5673cd10162616ed98799c60d88/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L164

This property should be backported to whatever release you plan to do next on NuGet for the AspNetCore 2 series.

### Describe alternatives you've considered
Forking or reflection.

**Comment by doctorpangloss** [comment]
Also, in general, making even simple changes like this myself is crazy complicated because of `InternalsVisibleTo`. If X needs code Y, just reference it, don't make it needlessly complicated.

**Comment by mikaelm12** [comment]
Are you asking that we also make the connectionId property public on ASP.NET SignalR? If so it already is. It's inherited through `Connection`
https://docs.microsoft.com/en-us/previous-versions/aspnet/jj889727(v%3Dvs.111)

**Comment by mikaelm12** [comment]
In general we usually only backport changes for bug fixes. We initially designed around not exposing the connection id so I'm not sure this is something we'd consider for a backport.

**Comment by doctorpangloss** [comment]
Alright, here's a workaround using Reflection if anyone needs it:

```
public static class HubConnectionExtensions
{
    public static string GetConnectionId(this HubConnection hubConnection)
    {
        const string connectionStateField = "_connectionState";
        const string connectionStateConnectionProperty = "Connection";
        const string connectionStateFieldType = "ConnectionState";
        var connectionState = typeof(HubConnection).GetField(connectionStateField,
                BindingFlags.Instance | BindingFlags.NonPublic)
            .GetValue(hubConnection);
        var connectionStateClass = typeof(HubConnection)
            .GetNestedType(connectionStateFieldType, BindingFlags.NonPublic);
        var connectionContext = connectionStateClass.GetProperty(connectionStateConnectionProperty,
                    BindingFlags.Instance | BindingFlags.Public)
                .GetValue(connectionState)
            as ConnectionContext;
        return connectionContext.ConnectionId;
    }
}
```
