### ISSUE TITLE
AzureAD B2C does not honor Environment=Development for error handling

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#10848]
AzureAdB2C has an error page at /AzureADB2C/Account/Error that talks about Development mode (presumably because it's a copy from the template), but it does not honor that setting, there's no way to get to the dev exception page. OnRemoteFailure redirects here for any unknown error:
https://github.com/aspnet/AspNetCore/blob/b6d8c96a98c9e5673cd10162616ed98799c60d88/src/Azure/AzureAD/Authentication.AzureADB2C.UI/src/AzureAdB2COpenIDConnectEventHandlers.cs#L82

Proposal:
In development mode it would be more appropriate for OnRemoteError to rethrow the original exception and let the dev exception page handle it.

Note I triggered this code path by using the "Run User Flow" feature in the portal which fails because it doesn't send a State field. I'm not sure how they ever expect that feature to work.

Tested using SDK 3.0.100-preview6-012234.

**Comment by anurse** [comment]
Duplicate of https://github.com/aspnet/AspNetCore/issues/11365 (and that issue is prettier and followed the template :trollface:)
