### ISSUE TITLE
Issue implementing Swashbuckle OpenApi on BlazorHosted App

### ISSUE THREAD

**Issue by PirasannaRavi** [aspnet/AspNetCore#10850]
I'm trying to implement [Swagger](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio) OpenApi Documentation on my app which is created using blazorhosted template on core 3.0 preview.

When I compile the code there is no issue.
But when I try to navigate to [http://localhost:5000/swagger](http://localhost:5000/swagger) I see the below error in console window. Any help to fix it will be much appreciated.

`WASM: System.InvalidOperationException: 'Router' cannot find any component with a route for '/swagger', and no fallback is defined.`

Startup.cs code:
`        
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddNewtonsoftJson();

            services.AddResponseCompression(opts =>
            {
                opts.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(
                    new[] { "application/octet-stream" });
            });

            // Register the Swagger generator, defining 1 or more Swagger documents
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseResponseCompression();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBlazorDebugging();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
            });

            app.UseBlazor<Client.Startup>();

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.), 
            // specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
                c.RoutePrefix = string.Empty;
            });
        }
`

**Comment by rxelizondo** [comment]
Not sure if this will help you or not but I would try moving `app.UseBlazor<Client.Startup>();` to the end of the pipeline. I am wondering if `app.UseBlazor<Client.Startup>(); `terminates the flow and the Swagger stuff does not even get a chance to execute.... just a theory.

**Comment by PirasannaRavi** [comment]
Thanks for your help rxelizondo... But unfortunately it did not work.

**Comment by PirasannaRavi** [comment]
Sorry, I was able to fix the issue myself. I had missed to add [FromBody] for a Post method hoping it will be implicitly taken care as [FromQuery]. But that seem to have fixed the issue.
