### ISSUE TITLE
asp.net core runtime for rhel 7 

### ISSUE THREAD

**Issue by balarvs2002** [aspnet/AspNetCore#10861]
Where do I download asp.net core runtime for rhel 6 ?

**Comment by Eilon** [comment]
Hi @balarvs2002 , you can find info on RHEL downloads for .NET Core (which includes ASP.NET Core) at this page: https://dotnet.microsoft.com/download/linux-package-manager/rhel/runtime-current

**Comment by balarvs2002** [comment]
Thanks @Eilon for your solution. Is it possible to get as tar file ?

**Comment by Eilon** [comment]
@natemcmaster / @leecow - any idea on this?

**Comment by natemcmaster** [comment]
The binaries inside the .rpm for RHEL are the same bits that can be downloaded from this link: https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.2.5-linux-x64-asp.net-core-runtime-binaries.

https://dotnet.microsoft.com/download/dotnet-core/2.2
![image](https://user-images.githubusercontent.com/2696087/58977279-3f59f580-877e-11e9-99df-de83c71d6b8a.png)

**Comment by balarvs2002** [comment]
@natemcmaster : Thanks , I will try out.
