### ISSUE TITLE
[Blazor server side] Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#10877]
Hello guys,

I meet some problems on some views with a lot of data (complex view, table with lot of rows, etc). 
What's happening is I lost the signalR connection.

Typically, the first time i land on the page is OK.
After i go to anoter page => still OK
After i come back to my page with lot of data and that's now the problem happen

The actions on my page have no effect, on the console output of visual studio i can see a lot of 
The thread xxxx has exited with code 0 (0x0) 

after maybe 10 seconds, I can see in the chrome console 
Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.
and signalR connection is come back and i can use again application.

I don't know whats happen, there is no Exception, I wanted to know if there is a way to investigate and understand what's happen (application consume too many resources ? memory leak ? blazor bug ?).

Unfortunately, i'm not able to reproduce the case, my app is definitively too complex too reproduce the same environment. I try with the starter project and two view with each a table of 5000 rows and it's not reproduce the problem (it's very slow of course, but the signalR connection is not lost).

I'm pretty sure is a performance problem, because for the same view, if i have 10 rows in my grid the problem not happen and if i have 100 rows the problem happen.
But impossible to know what's happening really

thanks for your help !

Julien

**Comment by BrennanConroy** [comment]
This sounds very similar to https://github.com/aspnet/AspNetCore/issues/9683.

We fixed a bug that caused the connection to hang with large payloads. Can you try out the daily bits and see if the issue still reproduces? https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md

**Comment by julienGrd** [comment]
Yes it can be the same problem !

I try to use the daily build
- I installed the last build (preview7)
- I added a Nuget.config with the configuration as expected

But my projects is still on preview5, I think i miss something to switch the nuget of my projects from preview5 -> preview 7

It seem the new Nuget.config in my project is not read/use.

**Comment by danroth27** [comment]
@julienGrd Do you have a simple project that reproduces the issue that we could take a look at? That way we can help up with the required migrations steps to move to preview6 builds.

**Comment by julienGrd** [comment]
@danroth27 Unfortunately no, my app is definitively too complex, it's a migration from a big silverlight application where I load existing ViewModel and I let existing code drive the application.

I try to reproduce on a simple project, with two views with table with 5000 rows each and move from view to another but no way, on a simple project can be slow but still working.

What I can say more about this bug 
- it produce on only two views of my app, the two big views for the moment. These two views contains a table
- the bug depending of the data contain by the view, because if i Have only 20 rows on my table, the bug not appear. With 80 rows, it appear each time.
- My app load lots of modals containing large data on table, but on these modal  it seem there is no problem like this, so maybe the bug can be related to the router because my two views with problem are loaded with router
- When the bug appear, I can continue debug the app, it's "just" the browser UI wich is not refresh. for example if i put a button with a onclick event, and on the click i change some data to have my button blue for example, i reach the onclick with no problem, but the button not become blue (but the browser is not frozen, there is just no effect). after some second, the SignalR reconnect and my button become finally blue.

So i think for the moment just wait for the preview6 see what' happen. It's really strange because I just see this bug few days ago, but i'm on the preview5 since the beginnning, So maybe i do something wrong. But impossible to investigate by myself and impossible to give you reproduce steps

**Comment by julienGrd** [comment]
Hello, since the preview 6, i'm unable to reproduce the problem on my app.

so I close this issue
