### ISSUE TITLE
NullReferenceException when api return null result.

### ISSUE THREAD

**Issue by lovelangy** [aspnet/AspNetCore#10876]
### To Reproduce
1. create an asp.net api project with version 2.2
2.  add code
 ```csharp
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
      [Route("test")]
        public Task<string> Testapi()
        {           
                return null;
        }
      }
```
3. test the api with browser
4. it returns error
```csharp

NullReferenceException: Object reference not set to an instance of an object.
lambda_method(Closure , object )
Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.GetAwaiter()
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
```

### Expected behavior
NullReferenceException should be handled propertly and return some useful information.

**Comment by dpr-dev** [comment]
we can return some message, for example: "an action from MyGreatController returns zero"

**Comment by dpr-dev** [comment]
in netcore 3.0 i can't reproduce this. the action returns 404 and make redirect from 'localhost/url' to 'localhost'

**Comment by mkArtakMSFT** [comment]
What you see is actually by-design. What's happening is the method return type is `Task<string>` and when you return null, it's the same as:
```csharp
Task<string> result = null;
return result;
```

When the `ActionMethodExecutor` is trying to evaluate the result of the action being called it tries to await for that `Task<string>` result, which is obviously `null`. Hence the `NullReferenceException` you observe.

You can instead return `Task.FromResult<string>(null)` and that would properly return.

As for the behavior in 3.0, we did add additional logic to treat null returns as `404` results.

**Comment by rynowak** [comment]
> As for the behavior in 3.0, we did add additional logic to treat null returns as 404 results.

This is news to me, is there an issue tracking that?

**Comment by dpr-dev** [comment]
> Thanks for contacting us, @lovelangy.
> What you see is actually by-design. What's happening is the method return type is `Task<string>` and when you return null, it's the same as:
> 
> ```cs
> Task<string> result = null;
> return result;
> ```
> 
> When the `ActionMethodExecutor` is trying to evaluate the result of the action being called it tries to await for that `Task<string>` result, which is obviously `null`. Hence the `NullReferenceException` you observe.
> 
> You can instead return `Task.FromResult<string>(null)` and that would properly return.
> 
> As for the behavior in 3.0, we did add additional logic to treat null returns as `404` results.
> 
> //cc @pranavkm

but why asp net core make redirect ?

**Comment by mkArtakMSFT** [comment]
@pranavkm didn't we made a change to treat `null` results in API controllers as `NotFound` -s ?

**Comment by dpr-dev** [comment]
> @pranavkm didn't we made a change to treat `null` results in API controllers as `NotFound` -s ?

the server returns 404, but the URL changes from "https: // localhost: 44379 / api / SampleData / test2" to "https: // localhost: 44379"

**Comment by rynowak** [comment]
I suspect that what's happening here is the action is throwing and your error handler is what's returning a 404.

**Comment by mkArtakMSFT** [comment]
So looks like I referred to something which we never did. So I'm removing my statement above regarding 3.0 to avoid spreading wrong information out.
I had a chat with @rynowak  regarding this and what is most probably happening in your case is you're hitting the same exception as you do in 2.2, but... (and @rynowak just responded :) )
