### ISSUE TITLE
Adopt Bedrock Client abstractions in SignalR client

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10872]
Epic #10869

SignalR currently uses the "Bedrock" abstractions on the server side (`ConnectionContext`, etc.) but has a custom client-side abstraction (`IConnectionFactory`). Bedrock has evolved to support a client-side abstraction now so SignalR should update to use it (since it would be a breaking change).

The new client abstraction shape is:

```csharp
public interface IConnectionFactory
{
    ValueTask<ConnectionContext> ConnectAsync(System.Net.EndPoint endpoint, CancellationToken cancellationToken = default);
}
```

Some elements to this:
* Add `IConnectionFactory` (as above) somewhere ([Connections.Abstractions](https://github.com/aspnet/AspNetCore/tree/master/src/Servers/Connections.Abstractions/src)? or a new library?)
* Add `HttpEndpont` sub-class of `System.Net.Endpoint` (for use in the `IConnectionFactory.ConnectAsync` method).
* Configure the `TransferFormat` in the constructor instead of in the `ConnectAsync` method?
* Delete existing connection factory and change to use the new abstraction.

**Comment by anurse** [comment]
TBH, this is another thing making me nervous :).

cc @davidfowl to review my assessment of the elements needed to finish this.

**Comment by davidfowl** [comment]
This looks good. We need to rename the interface to something that says client.

**Comment by anurse** [comment]
![A man standing in a mirror, we see his reflection. He raises his hand in a thumbs-up gesture and says "We did it"](https://www.bing.com/th?id=OGC.3b320d1565afaa59c6451a91399e5156&pid=1.7&rurl=https%3a%2f%2fmedia.giphy.com%2fmedia%2f3ornkf4SAQutQCpLgc%2fgiphy.gif&ehk=0DOxbah74IMCJkssihcvGw)
