### ISSUE TITLE
Wrong Summary for constructor in AuthenticationService.cs

### ISSUE THREAD

**Issue by pobisw** [aspnet/AspNetCore#10885]
The summary for the constructor method in AuthenticationService says it takes IAuthenticationRequestHandler as a parameter, but actually it takes IAuthenticationHandlerProvider as an argument. So the summary should match the actual method

### Screenshots
![image](https://user-images.githubusercontent.com/28534218/58937970-800f3a00-8791-11e9-994a-9f7ac68cd7b5.png)

**Comment by blowdart** [comment]
Would you like to create a PR?

**Comment by blowdart** [comment]
As this was merged, I'm closing the issue. Thanks @Kahbazi
