### ISSUE TITLE
System.Text.Json based Javascript interop fails silently

### ISSUE THREAD

**Issue by glent1** [aspnet/AspNetCore#10882]
### Details

Since the move to System.Text.Json for serializing and deserializing objects sent to and received from javascript, any deserialization errors cause a silent failure with no exception and the thread of execution just disappearing into a parallel universe.

This can easily be triggered because it also appears DateTimes do not currently work with the serialisation.  

I also have experienced another such failure with byte arrays that then work fine if the class is converted to use List<byte> instead, but reproduction is too complex for here.

### To Reproduce
1. Installl current daily of 3.0 (details below)
2. dotnet new blazorserverside
3. Add the following to _Host.cshtml

```
<script>
    function Echo(a) {
        return a;
    }
</script>
```

4. Change Counter.razor as follows...

```
@page "/counter"
@inject IJSRuntime j

<button @onclick="@DTTest">Test</button>
@dtStatus

@code {

    string dtStatus="";

    async void DTTest()
    {
        dtStatus="Starting";
        DTWrapper1 dtw1=await j.InvokeAsync<DTWrapper1>("Echo",new DTWrapper1());
        dtStatus="Success 1";
        StateHasChanged();
        DTWrapper2 dtw2=await j.InvokeAsync<DTWrapper2>("Echo",new DTWrapper2());
        dtStatus="Success 2";
        StateHasChanged();
    }
    public class DTWrapper1
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public DateTime dt { get; set; }
        public string s {get;set;}
    }
    public class DTWrapper2
    {
        public DateTime dt { get; set; }
        public string s {get;set;}
    }
}
```
4. dotnet run
5. Navigate to the counter page
5. Click the "Test" button

### Expected behavior
The message "Success 2" should be displayed

### Actual behaviour
The message "Success 1" is displayed, and no exception is logged.

### Environment 
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012258
 Commit:    c41cd1ba7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012258\

Host (useful for support):
  Version: 3.0.0-preview7-27803-11
  Commit:  c113140681

.NET Core SDKs installed:
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012258 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19304.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27803-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27803-11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by rynowak** [comment]
@pranavkm

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Extensions/pull/1802
