### ISSUE TITLE
[Blazor server side] Any way to "cancel" a click on checkbox

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#10881]
Hello guys,

I want to try implement a click on a checkbox which can be cancellable
for example, on a checkbox unchecked, when user want to check :
- if condition, OK the checkbox is checked
- if not, the checkbox stay unchecked

I try to implement this with bind (don't set the value on the setter), and the events onChanged and Onclick (find option on the args to cancel), but it seem there is nothing.

there is actually any way to accomplish this (without javascript) ?

thanks !

**Comment by guidevnet** [comment]
I usually implement this as a one way binding, and then I use the onclick event to change the value. Something like:

    <input type="checkbox" checked="@isChecked" onclick="@checkboxClick"/>`

    @functions {
        bool isChecked = false;
        void checkboxClick()
        {
            if (isChecked == true)
            {
                isChecked = false;
            }
            else if (condition)
            {
                isChecked = true;
            }
        }
    }

Not sure if its the best way.

**Comment by julienGrd** [comment]
Yes i try something like that but it's not the behavior expected
With your code, the value of variable is OK but on the browser the checkbox is really check, event if the variable stay false; (with chrome last version at least)

**Comment by astecenko** [comment]
It may be necessary to call StateHasChanged() at the end of a handler method.

**Comment by julienGrd** [comment]
Hum i add the StateHasChanged to be sure but no effect, the checkbox stay checked.

**Comment by danroth27** [comment]
You need prevent default support for this, which is tracked by #5545.
