### ISSUE TITLE
Blazor Server: Deadlock when JavaScript-Interop is called directly after StateHasChanged()

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/AspNetCore#10889]
Consider the following code-snippet:

```
this.StateHasChanged(); // [1]
this.Logger.Debug("after StateHasChanged()"); // [2]
// [2/3]
using (var fileReaderStream = await fileRef.OpenReadAsync()) // [3] JS-Interop is behind this call
{ ... }

```
Running the code in this order (first StateHasChanged() then something with JS-Interop) causes Blazor Server to deadlock pretty often. 
Looking at the log-output, the order is different than the code.
If Task.Delay(2000) is added at position [2/3], everything is fine.
(sorry for the vague description, but it's really hard to get grip on this issue and to explain it precisely)

```
[2] [11:54:16 DBG] after StateHasChanged() - OnFileSelectedAsync @ Uploader.razor:249
[1] [11:54:16 DBG] Received hub invocation: InvocationMessage { InvocationId: "", Target: "OnRenderCompleted", Arguments: [ 5,  ], StreamIds: [  ] }.
[11:54:16 DBG] Received confirmation for batch 5.
[11:54:16 DBG] Completing batch 5 without error.
[3] [11:54:16 DBG] Received hub invocation: InvocationMessage { InvocationId: "", Target: "BeginInvokeDotNetFromJS",
```

Is this a known problem (maybe related to #9901 ) / already filed issue?

**Comment by pranavkm** [comment]
@DNF-SaS any chance you could share a minimal repro application for us to investigte?

**Comment by springy76** [comment]
@DNF-SaS : @KP-WhatEver made a repro for this? Where?

**Comment by DNF-SaS** [comment]
It's here: https://github.com/DNF-SaS/BlazorServerDeadlock
But I'm not able to provocate the described deadlock from the OP using the repo. :-(

**Comment by DNF-SaS** [comment]
> @DNF-SaS any chance you could share a minimal repro application for us to investigte?

Sorry for the late reply.
Please clone https://github.com/DNF-SaS/BlazorServerDeadlock, launch und click the red "Start"-Button.
The code counts until 1000 - but this value never gets reached.
It stops somewhere between 300 and 400 with a complete deadlock.

**Comment by pranavkm** [comment]
Trying this out with our latest preview7 bits, this seems to be working fine:

![image](https://user-images.githubusercontent.com/174281/59954190-4cdad500-9438-11e9-98bb-aafed43532bc.png)
