### ISSUE TITLE
[Feature request] Sign In with Apple Authentication Handler

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/AspNetCore#10891]
Apple announces its new **Sign In with Apple** for authenticating. Do you have plans to add a `AuthenticationHandler` for it?

**Comment by blowdart** [comment]
Right now they're pushing javascript as the only way to sign-in with websites, rather than the more standard oauth/oidc flows.  

Until they officially support a standards based login it is unlikely that we would, or could support it in the same way we support Facebook, Google et al.

**Comment by Kahbazi** [comment]
It seems they support both javascript and rest api

[Sign In with Apple JS](https://developer.apple.com/documentation/signinwithapplejs)
[Sign In with Apple REST API](https://developer.apple.com/documentation/signinwithapplerestapi)

**Comment by PinpointTownes** [comment]
@blowdart it's based on OIDC. We posted more details there: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/314

The JS script is just a way to trigger the OIDC authentication dance, using the hybrid flow.

**Comment by blowdart** [comment]
Oh I'm well aware, but no discovery document, no documentation, no "official" support. We're not about to "hack" it in.

**Comment by PinpointTownes** [comment]
Can't deny discovery is nice to have, but it's not part of the core OIDC spec, and thus not mandatory.

The good news is that ASP.NET Core's OIDC handler can work even without discovery, so those who want to use Apple Sign-in can give it a try. The tricky part will mostly consist in using the `AuthorizationCodeReceived` event to replace the `client_secret` before the token request is sent.

**Comment by blowdart** [comment]
No, but discovery is part of being well behaved, and indicates a level of support beyond a custom javascript client.

We're waiting for now.

**Comment by PinpointTownes** [comment]
My point is that there's nothing to wait for: one should be able to use the OIDC handler as-is with Apple Sign-in, without requiring any change to the handler itself 😄

**Comment by Tratcher** [comment]
Walkthrough:
https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple

That said, since the generic OIDC handler should work there's little reason to add a custom handler.

**Comment by blowdart** [comment]
Closing as we feel a community effort would be best
