### ISSUE TITLE
Compose Api Conventions & Individual Action Attributes

### ISSUE THREAD

**Issue by DrakeLambert** [aspnet/AspNetCore#10899]
This issue is in the context of asp net core web api development.

### Is your feature request related to a problem? Please describe.
[Api conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-2.2) are not applied to any action that also specifies its own `[ProducesResponse...]` attributes. I understand that documentation states that multiple conventions don't compose, that's another story, but I would like to see individual attributes applied to actions compose with conventions. This would allow us to easily extend our api documentation to include things like response model types that aren't consistent across controllers and actions, and therefore couldn't be included in api conventions.

### Describe the solution you'd like
I would like to use conventions to specify broadly common error response types. e.g.
```csharp
public static class ApiControllerConventions
{
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Prefix)]
    public static void Find([ApiConventionNameMatch(ApiConventionNameMatchBehavior.Suffix)] string id)
    { }
}
```
BUT, I would also like to be able to specify more specific success response types on individual actions. e.g.
```csharp
public class FoldersController : ApiControllerBase
{
    [HttpGet("{id}")]
    [ProducesResponseType(typeof(FolderDto), StatusCodes.Status200OK)]
    [ApiConventionMethod(typeof(ApiControllerConventions), nameof(ApiControllerConventions.Find))]
    public async Task<IActionResult> FindFolderAsync([FromRoute] string id)
    {
        ...
    }
}
```

Instead of the composition resulting in all attributes being applied to the action, only the attributes specified directly on the action are included.

### Describe alternatives you've considered
The alternative I am currently using is to not use api conventions. This stinks because api conventions really clean up the code.

### Additional context
I am especially interested in this because we are using Swagger to document our API.

**Comment by pranavkm** [comment]
@DrakeLambert ApiConvention will use the action's returned type for 200 \ 201 status code if it's able to infer it. If your convention and action were changed to look like so:

```C#
public static class ApiControllerConventions
{
    [ProducesResponseType(StatusCodes.Status200Ok)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
    [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Prefix)]
    public static void Find([ApiConventionNameMatch(ApiConventionNameMatchBehavior.Suffix)] string id)
    { }
}
...
public class FoldersController : ApiControllerBase
{
    [HttpGet("{id}")]
    [ApiConventionMethod(typeof(ApiControllerConventions), nameof(ApiControllerConventions.Find))]
    public async Task<ActionResult<FolderDto>> FindFolderAsync([FromRoute] string id)
    {
        ...
    }
}
````

things should just work. 

Ideally we want attributes to specifically apply only if you're doing something unconventional and have the conventions work for you in all other cases. The analyzer \ codefixes in the Api.Analyzers package are there to reduce the manual boiler plate work in the event you have an unconventional action to document.

**Comment by DrakeLambert** [comment]
Thanks @pranavkm! This solution worked perfectly. Is this behavior documented?

**Comment by pranavkm** [comment]
@DrakeLambert doesn't look like it: https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-2.2. I'd be happy to review a PR if you'd like to contribute a doc update.

**Comment by DrakeLambert** [comment]
@pranavkm That was exactly what I was thinking. I'll give it a shot soon.

**Comment by pranavkm** [comment]
Closing since there's a resolution to the question.
