### ISSUE TITLE
@bind:event not working on input element

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#10893]
I thought the following would work:

```razor
<input @bind="@someText" @bind:event="oninput" />
```

... but it does not (it only updates on change, not on input).

To update on each keystroke, you have to use the following less obvious syntax instead:

```razor
<input @bind-value="@someText" @bind-value:event="oninput" />
```

Also I think we should drop`on` from these event names, as it feels less obvious than `@bind:event="input"`. The `on` prefix is a bit of a historical oddity in HTML/JS generally, e.g., more recent APIs like [`addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) don't use `on` prefixes for event types.

**Comment by danroth27** [comment]
I expected `<input @bind="someText" @bind:event="oninput" />` to work (see https://github.com/aspnet/AspNetCore/issues/10909)

**Comment by ajaybhargavb** [comment]
To add more info, this is not a regression. This just was never supported. 
In the past we could either do `<input bind="someText" />` or `<input bind-value-oninput="someText" />`. There was no way to infer the `value` part but specify the event.

**Comment by rynowak** [comment]
Not a regression, but we should support it 👍

**Comment by ajaybhargavb** [comment]
I started working on this but I realized supporting this goes against our current design,
Consider, 
```cs
    [BindElement(""div"", ""value"", ""myvalue"", ""myevent"")]
    public static class BindAttributes
    {
    }
```
`<div @bind-value=""ParentValue"" />`
This gets resolved as follows,
valueAttributeName = `myvalue`
changeAttributeName = `myevent`

Now if we add a `@bind:event` attribute,

`<div @bind-value=""ParentValue"" @bind-value:event=""anothervalue"" />`
Should it now resolve to,
valueAttributeName = `myvalue`
changeAttributeName = `anothervalue`
?

Supporting that goes against the intended design as mentioned in the [comment here](https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentBindLoweringPass.cs#L530).

@SteveSandersonMS @rynowak can you clarify more on the requirements? Also the change in design works with custom `BindAttributes` specifications?

**Comment by ajaybhargavb** [comment]
I have a [PR](https://github.com/aspnet/AspNetCore-Tooling/pull/687) with changes that make sense to me.

**Comment by ajaybhargavb** [comment]
Spoke to @SteveSandersonMS. What I have in the PR is the behavior we want.
