### ISSUE TITLE
[blazor]: feature "change current url"

### ISSUE THREAD

**Issue by ichensky** [aspnet/AspNetCore#10894]
Sometimes it is easier develop pages 
not like:
1. User at page `/page`
2. User click `<a href="/page/123"` or button, that navigate user with `UriHelper.NavigateTo("/page/123")` to same page but with additional params. 
3. Blazor app page handle "SetParametersAsync", "OnParametersSet","OnInit" methods and update page state. 
(Now it is anyway needed to override "SetParametersAsync" method for clearing params see #7419)

but like: 
1. User at page /page
2. User click at button. 
3. Button onclick event change page state. 
4. Button onclick event just change browser url to the "/page/123"

So, it is request for the method, that will just change browser url without raising those events.

**Comment by danroth27** [comment]
@ichensky We do plan to address #7419. Given that we plan to do that, is there anything else that you are requesting here?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
