### ISSUE TITLE
Data-* attribute throws "Attributes may only be added immediately after frames of type Element or Component"

### ISSUE THREAD

**Issue by ZergZe** [aspnet/AspNetCore#10897]
### Describe the bug
Getting "InvalidOperationException: Attributes may only be added immediately after frames of type Element or Component" when add data-* attribute together with onclick handler on the same element:

### To Reproduce

```
@page "/counter"

<p>Current count: @currentCount</p>

<button data-test=@("test") onclick="@IncrementCount">Click me</button>

@functions {
int currentCount = 0;

    void IncrementCount()
    {
        currentCount++;
    }
}
```

### Expected behavior

```
...
<button data-test="test" ...
...
```

Hope [this](https://github.com/aspnet/AspNetCore/issues/5071) will help when release, but not sure.

**Comment by danroth27** [comment]
@ZergZe Could you please confirm what version of Blazor you are using?

**Comment by ZergZe** [comment]
@danroth27 

Thank you for the response!
I'm using 3.0.100-preview5-011568.
Blazor (server-side).

**Comment by ZergZe** [comment]
Hi,

I'm happy to say that the issue does not reproduce on the Blazor Preview 6.

Thank you for the fix!
