### ISSUE TITLE
Blazor non-functional in current daily (Preview 7 012261) - apparent SignalR/System.Text.Json compatibility problem

### ISSUE THREAD

**Issue by glent1** [aspnet/AspNetCore#10892]
### Describe the bug

Browser does not successfully connect to signalr on the server.  The server throws the following ...

Microsoft.AspNetCore.SignalR.HubConnectionContext: Error: Failed connection handshake.

System.MissingMethodException: Method not found: 'Boolean System.Text.Json.Utf8JsonReader.TextEquals(System.ReadOnlySpan`1<Byte>)'.
   at Microsoft.AspNetCore.SignalR.Protocol.HandshakeProtocol.TryParseRequestMessage(ReadOnlySequence`1& buffer, HandshakeRequestMessage& requestMessage)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.HandshakeAsync(TimeSpan timeout, IReadOnlyList`1 supportedProtocols, IHubProtocolResolver protocolResolver, IUserIdProvider userIdProvider, Boolean enableDetailedErrors)

### To Reproduce

1. Install current preview 7 daily (012261)
2. dotnet new blazorserverside
3. dotnet run
4. browse to site

### Environment

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012261
 Commit:    89cc67c6bb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012261\

Host (useful for support):
  Version: 3.0.0-preview7-27804-02
  Commit:  fdc2a215b0

.NET Core SDKs installed:
  3.0.100-preview7-012261 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview7.19304.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27804-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27804-02 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by BrennanConroy** [comment]
This is a temporary point in time issue, you're using a newer SDK than AspNetCore has consumed which means we haven't been able to react to any breaking changes yet (in this case a method rename).

We'll probably fix this today or tomorrow.
