### ISSUE TITLE
Clean up which directive attributes expect HTML vs C#

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#10909]
Currently you need to specify a leading @ character for event handler values. For example:

```html
<button @onclick="@IncrementCount">Count</button>
```

However, the leading @ character in the attribute value should not be required:

```html
<button @onclick="IncrementCount">Count</button>
```

See the design notes in https://github.com/aspnet/AspNetCore/issues/6364

**Comment by danroth27** [comment]
@NTaylorMullen

**Comment by danroth27** [comment]
@rynowak It looks like this was the intended design for event handlers and bind, but what about directive attributes like `@key` and `@bind:format`?

**Comment by ajaybhargavb** [comment]
As of now,
- `@ref`, `@bind`, `@bind:event`, `@bind-*` etc all expect CSharp
- `@bind:format`, `@key`, and `@onclick`(and friends) all expect HTML

I understand we should fix `@onclick` to expect CSharp. Should anything else be different in the above list?

**Comment by NTaylorMullen** [comment]
Ehhh, I thought in Blazor this was all intentional. @rynowak / @SteveSandersonMS would know better though.

**Comment by rynowak** [comment]
I would expect `bind:event` and `bind:format` to expect HTML.

Key I'm not sure.

Others should be C#.

**Comment by ajaybhargavb** [comment]
I edited the list. I meant to put `bind:event` along with `bind:format`.
