### ISSUE TITLE
Blazor Dynamic content generation

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#10912]
I have a scenario where the content of a component is dynamic (A data grid), so I need to pass the RenderTreeBuilder to the model (rows and columns) to allow it to create the content of the cells dynamically. In order to allow the model to have "safe" sequence numbers I need the Open/CloseRegion to be public.

I also considered using razor components inside the cells but it's terrible slow. In my opinion this is a major performance problem of the platform that should be fixed https://github.com/aspnet/AspNetCore/issues/10563.

Meanwhile the Open/CloseRegion could be handy to at least dodge nested components in some scenarios.

**Comment by arivoir** [comment]
Another possibility is the sequence numbers inside a render fragment to be independent

```
builder.AddContent(0, new RenderFragment(b =>
{
     b.AddContent(0, .... )
     b.AddContent(1, .... )
     b.AddContent(2, .... )
 }));
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @arivoir.
Your second suggestion is already the case:
> Another possibility is the sequence numbers inside a render fragment to be independent

**Comment by arivoir** [comment]
Hi @mkArtakMSFT 

In that case I am probably facing a bug, or design problem. Let me explain it in detail.

Every cell of the grid will return a RenderFragment. What's inside the fragment will depend on the kind of cell, it could be provided by the grid itself, or by a customer that provided a different render fragment for a specific cell, for instance normal cells will return just a text, headers can have a sort icon, other cells can have just an icon, etc. 

Obviously all the cell fragments are added to the render tree with the same sequence number. Because there is no possible way of having a different sequence number depending on the kind of cells, this is a dynamic scenario. 

The BuildRenderTree of the panel of cells looks like this

```
protected override void BuildRenderTree(RenderTreeBuilder builder)
{
    builder.OpenElement(0, "div");
    builder.AddAttribute(1, XXX);

    foreach (var row in EnumerateRows())
    {
        foreach (var column in EnumerateColumns())
        {
            builder.OpenElement(2, "div");
            builder.AddAttribute(3, XXX);
            builder.AddAttribute(4, XXX);
            builder.AddAttribute(5, XXX);
            builder.AddContent(6, CellFactory.GetCellContentRenderFragment(....));
            builder.CloseElement();
        }
    }
    builder.CloseElement();
}
```

So far so good, the problem is when the render tree is updated, the diff algorithm ends up messing the interface badly.

I tried assigning different arbitrary sequence numbers inside the render fragments and the problem doesn't appear. It looks the diff algorithm doesn't realize the fragment is different and end up messing it.

Is this a bug, or a design limitation of Blazor?

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @arivoir.
We'll review this after we're done the work for 3.0 release.

**Comment by arivoir** [comment]
Thanks for replying @mkArtakMSFT.

For anyone having the same problem, until this is fixed I applied a workaround by using the GetHashCode of the fragment method

```
protected override void BuildRenderTree(RenderTreeBuilder builder)
{
    builder.OpenElement(0, "div");
    builder.AddAttribute(1, XXX);

    foreach (var row in EnumerateRows())
    {
        foreach (var column in EnumerateColumns())
        {
            builder.OpenElement(2, "div");
            builder.AddAttribute(3, XXX);
            builder.AddAttribute(4, XXX);
            builder.AddAttribute(5, XXX);
            //builder.AddContent(6, CellFactory.GetCellContentRenderFragment(....));
            var renderFragment = CellFactory.GetCellContentRenderFragment(...);
            if (renderFragment != null)
            {
                //This is a workaround for a Blazor bug which doesn't detect the fragments are different. 
                var hashCode = renderFragment.Method.GetHashCode();
                builder.AddContent(6 + hashCode, renderFragment);
            }
            builder.CloseElement();
        }
    }
    builder.CloseElement();
}
```

Notice it is setting the hash code of the fragment as if it were the sequence number. This is not a solution, but it allows me to continue the development without having to set arbitrary sequence numbers everywhere.

In the code generated by razor files, there is always a correspondence between the generated sequence number and the fragment. In other words, the same render fragment will have always the same sequence number, and different fragments will have always a different sequence numbers. the point is that in dynamic scenarios this can not be guaranteed.

The real solution would be the diff algorithm to consider both the sequence number and the identity of the fragment, if the same sequence number is used but the fragment is different they should be treated as different cases.

**Comment by mkArtakMSFT** [comment]
Looks like the work required to enable this has already been done during Preview 9.
`OpenRegion` and `CloseRegion` APIs are now public.

**Comment by arivoir** [comment]
@mkArtakMSFT The bug looks fixed. I can call AddContent passing a RenderFragment, and the diff algorithm seems recognizing different kinds of fragments. I could remove the workaround. Thanks.

PS: OpenRegion and CloseRegion doesn't seem to be public, and they aren´t related to this apparently.
