### ISSUE TITLE
[Tooling] Razor C# 8 nullability enforcement warns for @model XYZ at design time

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#10919]
![image](https://user-images.githubusercontent.com/2008729/58986726-e21c6f00-8792-11e9-9732-ab8d1a8707f7.png)

This does not happen in runtime (dotnet build) scenarios.

**Comment by rynowak** [comment]
We need to replace the `__value = null` with `__value = !default` for nnrt
