### ISSUE TITLE
[Perf] Regression on JsonInput2K

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#10925]
![image](https://user-images.githubusercontent.com/1165805/58991269-b900dc00-879c-11e9-9013-ce8dfccf8fc5.png)

Here comparing System.Text.Json to Newtonsoft.

/cc @pranavkm who will explain why

**Comment by pranavkm** [comment]
This is likely due to the casing change @rynowak made: https://github.com/aspnet/AspNetCore/pull/10727

FYI @davidfowl

**Comment by davidfowl** [comment]
Wow, no bueno

**Comment by anurse** [comment]
Assigning to `area-mvc` then, since that's what the casing change was in. Feel free to ping me to re-evaluate.

**Comment by mkArtakMSFT** [comment]
@rynowak what's the plan here? What can we do to improve the perf?

**Comment by pranavkm** [comment]
I brought this up during the sync up this week. I don't think there's any work that's immediately actionable at this point, (3.0), but I think it would be reasonable if we file an issue in CoreFx to track improving the performance of this scenario.

cc @ahsonkhan \ @JeremyKuhne \ @steveharter, does this seem like a reasonable plan of action for now?

**Comment by ahsonkhan** [comment]
> does this seem like a reasonable plan of action for now?

That sounds good to me. Thanks @pranavkm

**Comment by pranavkm** [comment]
Filed https://github.com/dotnet/corefx/issues/38510 to track further work here.
