### ISSUE TITLE
Remove Razor Pages specific things from the MVC (Model-View-Controller) template

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#10935]
* Remove https://github.com/aspnet/AspNetCore/blob/a86a811f7b55c03f815b7ac37413a179e6459ba7/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L123
* Remove https://github.com/aspnet/AspNetCore/blob/a86a811f7b55c03f815b7ac37413a179e6459ba7/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L163

These should only appear in the Razor Pages template

**Comment by pranavkm** [comment]
@rynowak pointed out these are probably required for IdentityUI

**Comment by rynowak** [comment]
^^^^

**Comment by isaac2004** [comment]
@rynowak does it make sense to wrap these extensions in an (Auth) check?

**Comment by rynowak** [comment]
Sounds like it could be.
