### ISSUE TITLE
APIs on IMvcBuilder common to Razor Pages and MVC might be misleading

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#10933]
Consider

```C#
services.AddControllersWithViews();
services.AddRazorPages();
```

APIs such as configuring `RazorViewEngineOptions` or `AddRazorRuntimeCompilation` apply to both controllers and Razor Pages, but the actual API usage has to be on one or the other:

```C#
services.AddControllersWithViews()
 .AddRazorRuntimeCompilation(); // This also causes Razor Pages to be runtime compiled.
services.AddRazorPages();
```

One option might be to have the top level APIs also be extensions off of `IMvcBuilder` so it looks less awkward:

```C#
services.AddControllersWithViews()
  .AddRazorPages()
 .AddRazorRuntimeCompilation();
````

**Comment by rynowak** [comment]
We considered this design and rejected it. It didn't feel good to see things like `AddMvc().AddControllerWithViews().AddRazorPages()`.

If you're in a place where you're registering `AddControllersWithViews` and `AddRazorPages` you can use `AddMvc`

**Comment by pranavkm** [comment]
> If you're in a place where you're registering AddControllersWithViews and AddRazorPages you can use AddMvc

The MVC templates currently have this pattern. Is that unintented?

**Comment by rynowak** [comment]
Which templates?
