### ISSUE TITLE
Remove System.Threading.Channels from the shared framework

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#10938]
System.Threading.Channels has been moved into Microsoft.NETCore.App (https://github.com/dotnet/corefx/pull/38207) so we can remove it from the ASP.NET Core shared framework.

cc @natemcmaster @anurse

**Comment by natemcmaster** [comment]
Thanks for the heads up. I expect the dependency flow PR that has this change will break in PR validation until we react

**Comment by davidfowl** [comment]
This is done.
