### ISSUE TITLE
[Blazor] Simplified state change for specific properties

### ISSUE THREAD

**Issue by GeertvanHorrik** [aspnet/AspNetCore#10947]
### Is your feature request related to a problem? Please describe.

I am trying to update a *single* value from child => parent in Blazor. However, it's not picking up the change notification *unless* I call `StateHasChanged`. Unfortunately this causes the child component to be re-rendered as well, which is too much if I simply want to set the `IsDisabled` state.

### Describe the solution you'd like

For example, StateHasChanged with a single property parameter, only causing that part of the component to be re-rendered. If this feature gets implemented, it could even support `INotifyPropertyChanged` out of the box to watch for properties that really matter.

### Describe alternatives you've considered

Calling `StateHasChanged`

### Additional context

Here is an example:

*Parent component* (using @ChildContent to keep the content as flexible as possible, but this way we can't directly bind via the component via parent-child bindings):

```
<button type="button"
        disabled="@IsDisabled">
    <CascadingValue Value=this>
        @ChildContent
    </CascadingValue>
</button>

@functions
{
        [Parameter]
        public bool IsDisabled { get; set; }

        [Parameter]
        public RenderFragment ChildContent { get; set; }
}
```

*Child component*

```
<span>dummy content</span>

@functions
{
        [CascadingParameter]
        public Parent ParentContainer { get; set; }

        [Parameter]
        public bool IsDisabled { get; set; }

        protected override void OnInit()
        {
            base.OnInit();

            ParentContainer.IsDisabled = IsDisabled;
        }
}
```

*Example code*

```
<Parent>
  <Child IsDisabled="true" />
</Parent>
```

**Comment by GeertvanHorrik** [comment]
The examples in the documentation use `OnInit`, so I assumed that would be the first moment I would have access to the parent. But it looks like the `CascadeParameter` is already available in the `OnParametersSet` method. This way I can still set the parent values from the child without re-rendering. It would be nice though to have smart updates (if possible).

**Comment by egil** [comment]
Geert, nicely spottet. I had a similar issue and was using OnInit as well.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GeertvanHorrik.
This is not something we recommend our customers to do. Each component should manage its own state and rerendering so we recommend that the child component calls a method on the parent which then can update the state and call the `StateHasChanged`.
To guide our customers with this approach we may come up with an analyzer to prevent these type of usages in the future.

**Comment by GeertvanHorrik** [comment]
@mkArtakMSFT But the `StateHasChanged` redraws everything including the children, right? What if we are not talking parent-child relations, but just a simple counter. Why do a total rerender of the tree if you know that only a single property has changed. Or does `StateHasChanged` do something smart under the hood to only reflect changed stuff?
