### ISSUE TITLE
Razor component item template uses wrong extension

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#10945]
Steps:

1. In VS solution explorer, right-click on a folder inside a Blazor project (e.g., the `Pages` folder) and choose *Add* -> *Item*
2. From the dialog, choose *Razor Component*

Expected: Prompted file extension should be `.razor`
Actual: It's `.cshtml`

Sidenote: It would be great if the *Razor Component* item template also appeared in the initial context menu alongside *Razor Page* and *Controller*

![image](https://user-images.githubusercontent.com/1101362/59019953-e7d08e00-8840-11e9-8a7e-77be6ee070ea.png)

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg do we control this?

**Comment by ryanbrandenburg** [comment]
No clue. I thought it might be controlled by something in https://github.com/aspnet/Scaffolding but I don't see any evidence of that. You'll have to find someone on the VS tooling team.

**Comment by NTaylorMullen** [comment]
@seancpeters Do you happen to know who controls this?

**Comment by phenning** [comment]
As to the first question about the incorrect default filename for Razor Component, I checked in a fix to the vstemplate file stub for that template yesterday. It should flow into Visual Studio builds in the next few days.

In regards to the sidenote, this is something that would need to be implemented in the VS Web Tools component.

**Comment by mkArtakMSFT** [comment]
Thanks @phenning!
