### ISSUE TITLE
Ending a line with a semicolon in an `@code` block results in loss of indentation

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#10942]
![code-indentation](https://user-images.githubusercontent.com/1874516/59008621-eae76200-87df-11e9-8685-26e35f9cc287.gif)

This doesn't happen if change `@code` to `@function`.

@rynowak @NTaylorMullen @ajaybhargavb

**Comment by ajaybhargavb** [comment]
I can reproduce this as well. This is so weird. @NTaylorMullen do we special case `functions` anywhere in our tooling? Or maybe WTE special cases it?

**Comment by rynowak** [comment]
I wonder if Roslyn special cases it.... @heejaechang - does Roslyn have knowledge or special case formatting logic for `@functions`?

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen please follow up on this - as this is most probably external. If we happen to get the fix earlier, that's great!

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen please follow up on this - as this is most probably external. If we happen to get the fix earlier, that's great!

Yup, already have an email thread where @bhsubra / @ToddGrun are taking a look.

**Comment by heejaechang** [comment]
how can I repro this ? which VS should I use?

**Comment by danroth27** [comment]
@heejaechang You'll need VS 16.2 P2 and .NET Core 3.0 Preview 6 (latest public previews of both). See https://blazor.net -> Get Started for full setup instructions.

**Comment by NTaylorMullen** [comment]
I've verified @heejaechang's fix for this locally and all works as expected. Talked with @jinujoseph and she mentioned that the change should be merged soon. 

Expected delivery of the fix is 16.2-preview4.

**Comment by NTaylorMullen** [comment]
@heejaechang and @jinujoseph thank you for the quick turnaround on this!
