### ISSUE TITLE
Microsoft.Extensions.ApiDescription.Server contains a runtimeconfig.dev.json 

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#10958]
Was reviewing build output and found an unexpected file type.

```
│           ├── Microsoft.Extensions.ApiDescription.Server.0.3.0-preview7.19306.12
│           │   └── tools
│           │       ├── netcoreapp2.1
│           │       │   ├── GetDocument.Insider.deps.json
│           │       │   ├── GetDocument.Insider.runtimeconfig.dev.json
│           │       │   └── GetDocument.Insider.runtimeconfig.json
```

This file shouldn't be in the .nupkg. It is only supposed to use in local development because it will contain file paths that are machine-specific. 

![image](https://user-images.githubusercontent.com/2696087/59057677-c7f49680-884f-11e9-80b6-d6fd3455f996.png)

cc @dougbu

**Comment by dougbu** [comment]
Shoot. Missed this addition to the .nupkg. Same also don't need the dotnet-getdocument.runtimeconfig.dev.json file. But, both *.runtimeconfig.json files are needed for 3.0 compatibility.

**Comment by dougbu** [comment]
Do you happen to know if there's a switch somewhere to disable *.runtimeconfig.dev.json generation? If not, I'll have to do a weirdo exclusion in the .csproj files.

**Comment by natemcmaster** [comment]
There is no knob to suppress runtimeconfig.dev.json generation. The better fix here is to package dotnet-publish output instead of dotnet-build output:

https://github.com/aspnet/AspNetCore/blob/b6d8c96a98c9e5673cd10162616ed98799c60d88/src/Mvc/Extensions.ApiDescription.Server/src/Microsoft.Extensions.ApiDescription.Server.nuspec#L25

**Comment by dougbu** [comment]
0049c5899ca7
