### ISSUE TITLE
Missing completions for Router parameters

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#10954]
I'm not getting completions for some of the new templated parameters on the Router component, like [NotAuthorizedContent](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Routing/Router.cs#L46):

![image](https://user-images.githubusercontent.com/1874516/59047499-da170a80-8838-11e9-8a2e-9a5ab956e3eb.png)

**Comment by danroth27** [comment]
@rynowak looked into this and thinks the ref assemblies weren't updated for these new properties.

**Comment by pranavkm** [comment]
> @rynowak looked into this and thinks the ref assemblies weren't updated for these new properties.

Yup, looks like it: https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/ref/Microsoft.AspNetCore.Components.netstandard2.0.Manual.cs#L266-L277

**Comment by SteveSandersonMS** [comment]
I definitely agree we want this to work, but what I don't understand is this: why is it working fine for me anyway?

![image](https://user-images.githubusercontent.com/1101362/59067521-bd66eb00-88a9-11e9-9cd3-9c677f24c433.png)

It compiles, and it works correctly at runtime. I'm on SDK 3.0.100-preview6-012254, using packages version 3.0.0-preview6.19304.11, and VS 29004.115.d16.2, all of which are very recent.

Does it become broken on an *even newer* version of one of these?

**Comment by pranavkm** [comment]
@SteveSandersonMS the difference might be serverside-blazor. Client side blazor uses the "runtime" binary, serverside uses the ref assembly which is out of date.

**Comment by rynowak** [comment]
Ah. Well that's a good explanation at least. At least it work for the workshop! I was just reviewing the code and came here to see if there was an explanation.
