### ISSUE TITLE
[blazor]: closures in `for`, `while`

### ISSUE THREAD

**Issue by ichensky** [aspnet/AspNetCore#10979]
1. Create page
```
@page "/counter"
@for (int i = 0; i < 10; i++){
    <button onclick="@(e=> Console.WriteLine(i))">@i</button>
}
```
2. Click on any button as a result you'll see always `10`

Maybe it is better for `for` statement generate c# class, that will looks like 
```csharp
...
for (int i = 0; i < 10; i++){
    var tmp = i;
...
(this, e=> Console.WriteLine(tmp)));
...
}
```
to avoid closures?

**Comment by SteveSandersonMS** [comment]
I'm afraid this is just how the C# compiler works, which is outside the scope of what the `.razor` compiler controls. Quite a few people have run into it, but we don't have a better solution than to say you need to understand what the C# compiler does with closures.
