### ISSUE TITLE
ComponentBase Async Methods aren't Async by Default

### ISSUE THREAD

**Issue by kevinjpetersen** [aspnet/AspNetCore#10973]
### Describe the bug
In the "@Functions" section of a Blazor Component, when using the auto complete of the virtual async methods (That can be overriden), the generated code from the auto complete doesn't have an "async" tag on the method.

### To Reproduce
1. Using ASP.NET Core 3.0 Preview 5
2. Add a "@functions" section to a Blazor Component
3. Auto complete a virtual method to override it (Example: OnAfterRenderAsync)

### Expected behavior
The auto completed method would include the "async" tag on the method.

### Code Details
```
// Produced
protected override Task OnAfterRenderAsync()
{
	return base.OnAfterRenderAsync();
}

// Expected
protected override async Task OnAfterRenderAsync()
{
	await base.OnAfterRenderAsync();
}
```

**Comment by rynowak** [comment]
This is the same as the behavior of all C#. I'd suggest reporting this suggestion at https://github.com/dotnet/Roslyn
