### ISSUE TITLE
[SignalR] Access HubContext in Ctor of strongly typed Hub

### ISSUE THREAD

**Issue by ddweber** [aspnet/AspNetCore#10980]
Is it/should it be possible to access the `HubContext `in the constructor of a strongly typed hub?
I´m trying to initialize some members of my hub in the ctor with values from `context.items` but the context is null at that time. Is this intended by design?

**Comment by anurse** [comment]
Can you post sample code that reproduces the issue? The `Context` property *should* be accessible in `OnConnectedAsync`, but it **would** be null in the constructor.

**Comment by ddweber** [comment]
> The Context property should be accessible in OnConnectedAsync, but it would be null in the constructor.

Okay, thats the case in my application and all I wanted to clarify :)
Thanks for the answer.
