### ISSUE TITLE
Static content from libraries not working with Blazor dev server or default hosted project

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#10986]
The new "static content from libraries and projects" feature works great if you have a `app.UseStaticFiles()` call in your `Startup.cs`. However:

 * The Blazor DevServer (for the standalone template) doesn't contain such a call, and developers have no way to add one. So static content just doesn't work with this project type.
 * The Blazor hosted-on-ASP.NET-Core template also doesn't contain such a call, although developers can easily add one to their `Startup.cs`.

Both fixes could be trivial one-liners.

**Better fix:** Also delete the now-obsolete embedded content feature from Blazor, and update the E2E tests to use the new feature.

**Comment by Stamo-Gochev** [comment]
@SteveSandersonMS I am not able to fix the problem in a client-side Blazor app using the hosted-on-ASP.NET-Core template even after the call to `app.UseStaticFiles()`. Here is a repo with the project: https://github.com/Stamo-Gochev/blazor-wasm-static-assets
Am I missing something here? The same test works with a server-side Blazor app that contains the call to `app.UseStaticFiles()`.

**Comment by javiercn** [comment]
@Stamo-Gochev I'm investigating. I'll keep this issue posted.
