### ISSUE TITLE
Directive attributes dominate completion lists

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#10981]
This is just a suggestion about how we might improve the usability of the code completion prompt now we are polishing directive attributes.

Currently, because of alphabetical ordering, directive attributes appear before other component parameters. This makes it harder to explore the features that a component offers. For example, here I'm trying to discover what parameters I can pass to a `MatAppBar` from the [MatBlazor (Material Design) library](https://www.matblazor.com/):

![capture](https://user-images.githubusercontent.com/1101362/59090379-8f62c480-8904-11e9-84b8-35a5a1761621.gif)

We could avoid scrolling past all the boilerplate entries and emphasise what's unique about each component by either:

 * Putting the directive-attribute entries at the end of the list
 * Or, by not showing the directive-attribute entries until you've typed `@` (perhaps having a single autocomplete entry for `@...` at the top until then)

Are either of these possible within the constraints of the editor? If there was a choice, I'd prefer the second option.

Obviously this is not super high priority!

**Sidenote** I'm not a fan of having the "at"-like logo on the left of all the entries. For one thing, it looks weird for directive attributes (you have two "at"-like symbols next to each other), and it's distracting for non-directive attributes (it makes them look as if they *are* directive attributes). If we could drop that symbol entirely I think that would be better!

**Comment by rynowak** [comment]
/cc @NTaylorMullen - I think he already addressed this for VS code and wanted to do the same fix for VS.

@SteveSandersonMS - another idea that I had to address this with syntax is to change how event handlers are described (like Vue.js). I think that this has some problems so I'm not actually proposing we do it. 

```razor
<button @on-click="Click">Click me!</button>
```

Then completion would show a breadcrumb to "@on-..." - which is the real value of the change.

What I don't like is that it's sufficiently different from JS event handlers. Is this really confusing?

```razor
<button @on-click:preventDefault>Click me!</button>
```

**Comment by NTaylorMullen** [comment]
> Then completion would show a breadcrumb to "@on-..." - which is the real value of the change.

@ToddGrun is already taking care of this part in VS without the `on-` change. He's going to group `@on...` together.

**Comment by NTaylorMullen** [comment]
> * Or, by not showing the directive-attribute entries until you've typed `@` (perhaps having a single autocomplete entry for `@...` at the top until then)

As Ryan said, I made it work this way in VSCode for the preview6 release. @rchande does there happen to be a beta build out that Steve can try?

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen is this fixed for VS? If yes, simply close please.

**Comment by NTaylorMullen** [comment]
Fixed

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen are you missing the `Done` label? Or was this fixed as part of some other issue?

**Comment by NTaylorMullen** [comment]
It was fixed eternally (Todd fixed it). I can mark it as done.
