### ISSUE TITLE
[Asp.Net Core 2.1] Decimal ToString with Specific Culture not working...

### ISSUE THREAD

**Issue by BlueBird67** [aspnet/AspNetCore#10984]
I had a lot of problems with Culture in Asp.Net Core... I have a web app that need to force a "fr-CH" culture, nothing else. Very difficult to do, nothing has worked, and I tried a lot : the browser culture have priority always...

So finally, I decided to force it on my own line of codes:
`Decimal rawValue = 45000;`
`string convertedValue = rawValue.ToString("C0", CultureInfo.CreateSpecificCulture("fr-CH"));`

On my french browser and Windows 10, I got what I want : "45 000 CHF"
On an english Windows and browser, I got "45'000 fr."

How that can be??

The problem here is not to check what is the correct result, but that the result change on different systems.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @BlueBird67.
Are you using request localization middleware? If so, by removing it you will ignore the culture info passed from the browser and you can enforce what you have on the server.

**Comment by hishamco** [comment]
@BlueBird67 is this still happen on the latest bits?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
