### ISSUE TITLE
ConfigureTestServices and ConfigureTestContainer is never called when using TestServer

### ISSUE THREAD

**Issue by mmiller678** [aspnet/AspNetCore#11001]
I am can't get any of the Test extension method on WebHostBuilder to work.  I looked thru the source and have tried a bunch of difference configurations but I can't get the ConfigureTestContainer or ConfigureTestServices actions to ever run when creating a TestServer instance.  I am using Aufofac (not in the below example as I tried to keep this as simple as possible) but even the exact code from #6522 didn't work for me.

Below is a simple unit test to reproduce the issue:

```
[Fact]
public void TestConfigureTestServices()
{
    var webHostBuilder = new WebHostBuilder()
        .ConfigureTestServices(services =>
            {
                services.AddScoped((provider) => new object());
            })
            .UseStartup<Startup>();

    var server = new TestServer(webHostBuilder);
    var client = server.CreateClient();
    Assert.NotNull(server.Host.Services.GetService<object>());
}

public class Startup : StartupBase
{
    public override void Configure(IApplicationBuilder app)
    {

    }
}
```
If I change ConfigureTestServices to ConfigureServices the test completes. 

I am using .NET Core 2.2 and my dependencies are:
```
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.1.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
```

**Comment by Tratcher** [comment]
Remove StartupBase, I don't think these work with StartupBase or IStartup.

**Comment by jzabroski** [comment]
So, remove the canonical way to actually build an ASP.NET application, and your integration tests work? Makes sense to me... 😱 

I guess @Tratcher you are advocating for something like this StackOverflow answeR: https://stackoverflow.com/a/44755108/1040437

**Comment by Tratcher** [comment]
Yes, this is the pattern we have given in templates since v1.
```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
    }

    public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
    {
    }
}
```

IStartup and StartupBase were added later for DI reasons and in hindsight are too rigid. I've filed https://github.com/aspnet/AspNetCore/issues/11050 to obsolete IStartup since it won't work in 3.0 anyways.

**Comment by javiercn** [comment]
Yeah, if you are using startup base you can simply further override from it and configure it for tests. ConfigureTestServices is only meant to make the convention based startup work. If you extend startup base or implement IStartup you can simply mark methods virtual and override them in your tests.

In 3.0 there is only one DI container and ConfigureTestServices is not required as configure methods are applied in order (which was the issue ConfigureTestServices was trying to solve).

ConfigureTestServices is meant for the common case, which is a Startup class without extending/implementing any inferface

**Comment by jzabroski** [comment]
@Tratcher Then maybe the StartupBase documentation should have a `[!WARNING]` DocFX tag applied to it so that people understand this stuff.  Seems like a fairly simple way to educate people.  That, plus `[Obsolete("http://aka.ms/mvcstartup/")]` on the StartupBase class, or whatever

I recently (in the last 30 minutes) read through a helpful article that explained how the baked in StartupBase conventions caused one developer tons of issues, and the practices they came up with to avoid the problems: http://stevetalkscode.co.uk/separating-aspnetcore-startup

**Comment by jzabroski** [comment]
I also see your point; I looked at what the ASP.NET Boilerplate logic does, and see in their main demo, Startup.cs is quite simple POCO: https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dbda53e6b31e13c3c786ba3c869f1cac580d21c5/test/aspnet-core-demo/AbpAspNetCoreDemo/Startup.cs 

And found: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.2

**Comment by mmiller678** [comment]
That worked - thanks.  I don't like the idea of convention based vs contract based.  Its fine to use conventions but give a contract for those conventions so I don't have to go read the documentation about what magic strings are needed to build an application vs an interface I can implement.  I don't think the two need to be mutually exclusive.

**Comment by mmiller678** [comment]
Even with the above change this still doesn't work with the WithWebHostBuilder syntax

**Comment by mmiller678** [comment]
Ah - my fault it actually does.  .WithWebHostBuilder creates a NEW factory - it doesn't modify the underlying factory.  Once I read the documentation and used the newly generated factory to create the client it works as expected.

**Comment by robinNode** [comment]
> Ah - my fault it actually does. .WithWebHostBuilder creates a NEW factory - it doesn't modify the underlying factory. Once I read the documentation and used the newly generated factory to create the client it works as expected.

I tried in asp.net core 2.2, both ConfigureTestServices and ConfigureTestContainer are never called. Is there any other settings i missed out?

**Comment by jzabroski** [comment]
Don't use IStartup. It doesn't work with test magics.

**Comment by robinNode** [comment]
> Don't use IStartup. It doesn't work with test magics.

I am not using IStartup interface. Just a normal startup class.  Could you share you sample codes to me?   thanks
