### ISSUE TITLE
Runtime compilation of Blazor Components 

### ISSUE THREAD

**Issue by JosephGarrone** [aspnet/AspNetCore#11017]
Similar to the `XamlReader.Load` method for WPF applications, it would be handy to be able to build Blazor Components on the fly.

A simple solution would be allowing `RenderTreeBuilder` to be passed a Blazor Component as string via a `Load` method or similar.

Given the ability for `RenderTreeBuilder` to currently render dynamic HTML via opening/closing tags etc and also render Blazor Components [as so](https://stackoverflow.com/questions/50117932):
```
builder.OpenComponent(0, typeof(SurveyPrompt));
builder.AddAttribute(1, "Title", "Some title");
builder.CloseComponent();
```
It would be possible to jerry-rig a dynamic renderer that would parse the Blazor file and call the required `builder.<method>` methods, however I feel that such an implementation should be part of the standard rather than in third party libraries.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JosephGarrone.
This is not something we plan to support in the near future.
