### ISSUE TITLE
Non-directive attribute event handler shows error during design time

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#11011]
Passing in a void method to a regular `onclick` attribute shows an error during design time,
![image](https://user-images.githubusercontent.com/1579269/59140305-99aab000-8950-11e9-91d6-3d55433398a2.png)
![image](https://user-images.githubusercontent.com/1579269/59140309-a7f8cc00-8950-11e9-9457-5e57aad07c9b.png)

It works in runtime.

Also using a directive attribute works,
`<button @onclick="@Activate">Activate</button>`

@rynowak @SteveSandersonMS, is this the expected behavior?

**Comment by rynowak** [comment]
I think there's an interesting question about whether we want to remove the support to do *raw* event handlers without using `EventCallback`. 

We didn't do any work to block this, and it was there in the past. @SteveSandersonMS thoughts? This would entail removing a bunch of overloads/extensions on RenderTreeBuilder. 

I'm tempted to leave it because it doesn't seem harmful. @ajaybhargavb what's the difference between the generated code for designtime and runtime for this case? Is this failing at design time because of an explicit type check?

**Comment by Andrzej-W** [comment]
@rynowak Does *raw* event handler mean *call JavaScript code directly*? If yes, we need this. Look here https://github.com/aspnet/AspNetCore/issues/5545#issuecomment-469748054 "Design" section , example with `conditionallyStopPropagation` function and example with `blockDigits` function.

**Comment by rynowak** [comment]
@Andrzej-W - what I meant in this context is whether you can use `Action<UIMouseEventArgs>` and other delegate types with the render tree builder directly. We currently have a bunch of different overloads of `AddAttribute` that made these things possible before we implemented `EventCallback`.

We're at the part of the product cycle where we're doing a lot of API cleanup.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, let's make the non-directive attribute version of event handlers not to work.

**Comment by ajaybhargavb** [comment]
I looked more deeply into this. The reason for this error in design time is because of,
```c#
__o = 
#nullable restore
#line 1 "x:\dir\subdir\Test\TestComponent.cshtml"
               Activate

#line default
#line hidden
```

This is not specific to javascript event handler attributes like `onclick`. It happens for pretty much any attribute where we pass in a method group as the attribute value.

`<button random="@Activate">Activate</button>` will have the same error. This is the behavior we've always had. And now javascript event handler attributes also behave like normal attributes. 

I think this is ok and we should leave it as is. @rynowak @SteveSandersonMS @mkArtakMSFT  thoughts?

**Comment by rynowak** [comment]
Yes, I think this is fine.
