### ISSUE TITLE
Constructor in Razor components wrongly recognized as a method - results in design time error

### ISSUE THREAD

**Issue by egil** [aspnet/AspNetCore#11015]
### Describe the bug
When a constructor is added to `@functions{}` the Razor editor thinks its supposed to be a method and reports an error, even though the code compiles without problems and runs correctly.

### To Reproduce
1. Using 3.0-preview5 and Visual Studio 16.2.0 Preview 1.0
2. Create Razor file named "ErrorWithConstructor.razor"
3. Add the following code to the file:
```
@functions {
    public ErrorWithConstructor()
    {
    }
}
<div />
```
4. See error in Error List: "Method must have a return type"

### Expected behavior
No error to be shown.

### Screenshots
![constructor-not-recognized-in-razor-components](https://user-images.githubusercontent.com/105649/59147980-de3a5800-89f1-11e9-994b-1cdaba4167e0.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @egil.
This will get addressed as part of https://github.com/aspnet/AspNetCore/issues/5487 work, which we plan to do in the near future.
As an alternative to using the constructor, you could use the `OnInit` method.
