### ISSUE TITLE
Application Hangs when querying Roles or Userroles

### ISSUE THREAD

**Issue by DCCoder90** [aspnet/AspNetCore#11019]
### Describe the bug
Querying for UserRoles or Roles then enumerating the results causes the application to hang.  No exceptions are thrown.

### To Reproduce
1. Running Asp.net Core 2.2
2. Add the following to the ConfigureServices method in Startup.cs

```
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseMySql(Configuration.GetConnectionString("DefaultConnection"), mysqlOptions =>
                {
                    mysqlOptions.ServerVersion(new Version(5, 6), ServerType.MySql)
                        .DisableBackslashEscaping();
                }));
            services.AddIdentity<ApplicationUser,IdentityRole>()
                .AddDefaultUI(UIFramework.Bootstrap4)
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
```
3. Seed database with roles, users, and userroles
4. Run the following elsewhere in the application

```
            var roles = applicationContext.UserRoles;
            var cnt = roles.Count();
```
### Expected behavior
Print out a count of the total UserRoles

### Additional context
This doesn't only apply to count but any point in where the collection would be enumerated.  This also applies when querying "Roles"

**Comment by DCCoder90** [comment]
Related SO question: https://stackoverflow.com/questions/56511457/requesting-userroles-or-roles-hangs

**Comment by blowdart** [comment]
Does the SO comment not help? You should be using the stores rather than querying through context, although I would have expected context to work.

Is it only roles? Does the claims enumeration work?
Where is "elsewhere" in your application?

**Comment by DCCoder90** [comment]
The SO comment didn't help any.  I may need to update this.  After a LOT of research, it turns out that the first query would be successful and any queries after that would result in a deadlock.  I'm not sure if this is EF Core, Pomelo, or AWS RDS.  Seemed like an EF issue at the time.

**Comment by blowdart** [comment]
Tagging @ajcvickers for EF, but you'll need to prove it with logs :)

**Comment by DCCoder90** [comment]
Sorry so late to respond back.  I wound up rewriting the project from scratch and it started working again.  Never was able to determine the issue but I'll play around when I get some free time to try and get it to happen again.
