### ISSUE TITLE
An exception occurred: application never completed

### ISSUE THREAD

**Issue by zengqinglei** [aspnet/AspNetCore#11025]
### Describe the bug
When I run the application using the framework [Creekdream.AspNetCore](https://github.com/zengqinglei/Creekdream.AspNetCore), when I request the interface, I get an exception: application never completed, but I don't know what caused this problem!

**exception :**
``` bash
2019-06-04 16:29:27.5943|FATAL|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HLN8MABF2BM1" application never completed
```

**I hope that you can give me a few comments to locate the problem and solve it?**

**Comment by anurse** [comment]
This generally occurs if you have code in your middleware pipeline that isn't properly returning or forwarding on to the next middleware.

Can you post a runnable sample project that reproduces the issue? If you can't reduce it to a simple project to reproduce the issue, please post your complete `Startup.cs` class and more of the logs surrounding this error, so we have the full context.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
