### ISSUE TITLE
MicrosoftAccount to take parameters

### ISSUE THREAD

**Issue by Worthy7** [aspnet/AspNetCore#11026]
### Is your feature request related to a problem? Please describe.
I am trying to using MicrosoftAccount authentication but I need to force the user to select their account using the `prompt=select_account` parameters.

### Describe the solution you'd like
When issuing a `Challenge` from the server, allow parameters to be added:
`properties.Parameters.Add("prompt", "select_account");`
This works with the google provider, it should also work with the Microsoft provider.

### Describe alternatives you've considered
1. Appending directly to the url, but I can't find a way to do this with the challenge object.
2. making the option permanent in the startup config - but I only need it sometimes, so this isn't a good idea.

### Additional context
I'm pretty confused why the Google provider is more comprehensive than the Microsoft one, Considering dot net is made by Microsoft...

**Comment by Tratcher** [comment]
> I'm pretty confused why the Google provider is more comprehensive than the Microsoft one

Because that feature was added to the Google provider by an external contributor.

Note you can do this with the OpenIdConnect handler.

**Comment by Worthy7** [comment]
I haven't looked into the OpenIdConnect handler, but is it the same/an upgraded version of the MSAccount one?

**Comment by Tratcher** [comment]
Yes, it's a bigger, more powerful, more generic, OAuth/OIDC handler.

**Comment by Worthy7** [comment]
OK, I'll give it a try. Perhaps this MSAccount one should inherit that then
so it can take advantage of all it's features.

**Comment by blowdart** [comment]
That wouldn't be a bad approach at all :)

**Comment by Tratcher** [comment]
It wouldn't be a derivation, it would be a replacement. We've considered obsoleting the OAuth providers that also have OIDC support like Google and MSA. We hadn't decided if we'd need a replacement or just a doc/sample using raw OIDC.

**Comment by Worthy7** [comment]
Obsoleting the google and MS one's just means causing extra work for devs
+1 the idea of just replacing them, to avoid any breaking changes
