### ISSUE TITLE
rzc discover exited with code 1

### ISSUE THREAD

**Issue by VaclavElias** [aspnet/AspNetCore#11036]
This is just for a reference, not sure if it is an issue or cross referencing. My application build started to fail when I added my TagHelper class library. This is working in 2.2.

### Describe the bug
Build fails on this error: **rzc discover exited with code 1**

### Other Info
Error: rzc discover exited with code 1.	
C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.CodeGeneration.targets	99	

## Error is pointing here
![image](https://user-images.githubusercontent.com/4528464/59205565-10d38480-8b9b-11e9-892e-4ee71ee612d2.png)

## My project
```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
```

## My TagHelper class library
```
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.2;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
```

### To Reproduce
```cs
[HtmlAttributeName(DictionaryAttributePrefix = AspClassPrefix)]
public IDictionary<string, bool> Condition { get; } = new Dictionary<string, bool>();
```

### Expected behavior
Not failing on build

### Fix
Not easy to figure out from the error what the problem was but I have added `set;` and all is working ok.

```cs
[HtmlAttributeName(DictionaryAttributePrefix = AspClassPrefix)]
public IDictionary<string, bool> Condition { get; set; } = new Dictionary<string, bool>();
```

**Comment by ajaybhargavb** [comment]
@NTaylorMullen, do we required tag helper properties to be settable?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen, do we required tag helper properties to be settable?

Yes

**Comment by ajaybhargavb** [comment]
@VaclavElias this is by design. Tag helper properties are required to have a `set;`.

**Comment by pranavkm** [comment]
@ajaybhargavb does the IDE provide correct guidance when this fails? Requiring the setter is fine, but I think the primary complaint was that there was no indication that this was broken.

**Comment by VaclavElias** [comment]
I was lucky to find the problem as the error "rzc discover exited with code 1" didn't really tell me what the problem was and that I had to dig in TagHelper :) If IDE could suggest it, that would be great but not sure how rare is this issue..

**Comment by ajaybhargavb** [comment]
Got it. Yes, I agree rzc shouldn't hide the actual error message. I am going to track this work as part of https://github.com/aspnet/AspNetCore/issues/12661 as they both have the same underlying issue.

**Comment by ajaybhargavb** [comment]
@VaclavElias I was able to repro your issue. But when I do it, I see a null-ref displayed in the output in white before `rzc exited with code 1` in red. Do you see this as well? If not, I might need to dig more into why that wasn't printed for you.
If you do see the error, this was a bug we fixed later and I've confirmed it is no longer happening on the latest SDK.

```
Object reference not set to an instance of an object.
     at Microsoft.CodeAnalysis.Razor.BindTagHelperDescriptorProvider.CreateComponentBindTagHelpers(ICollection`1 tagHelpers)
     at Microsoft.CodeAnalysis.Razor.BindTagHelperDescriptorProvider.Execute(TagHelperDescriptorProviderContext context)
     at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
     at Microsoft.AspNetCore.Razor.Tools.DiscoverCommand.ExecuteCore(RazorConfiguration configuration, String projectDirectory, String outputFilePath, String[] assemblies)
     at Microsoft.AspNetCore.Razor.Tools.DiscoverCommand.ExecuteCoreAsync()
     at Microsoft.AspNetCore.Razor.Tools.CommandBase.ExecuteAsync()
C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.CodeGeneration.targets(99,5): error : rzc discover exited with code 1. [C:\GitHub\temp\RazorPagesApp\RazorPagesApp\RazorPagesApp.csproj]
```

**Comment by NTaylorMullen** [comment]
@ajaybhargavb does it show up in VS?

**Comment by ajaybhargavb** [comment]
@NTaylorMullen, not the error list but it is in the `Output` window

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen, not the error list but it is in the `Output` window

Hmm, is there anything we can do to also include the error in the output window? I know MSBuild looks over the output window meticulously to find logs of a certain format.

**Comment by NTaylorMullen** [comment]
Talked offline, things work as I expect already. I was confused 😄

**Comment by VaclavElias** [comment]
Yes, I get the same error but it doesn't tell me where it is 😶
Output Window:
```
Object reference not set to an instance of an object.
4>   at Microsoft.CodeAnalysis.Razor.BindTagHelperDescriptorProvider.CreateComponentBindTagHelpers(ICollection`1 tagHelpers)
4>   at Microsoft.CodeAnalysis.Razor.BindTagHelperDescriptorProvider.Execute(TagHelperDescriptorProviderContext context)
4>   at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
4>   at Microsoft.AspNetCore.Razor.Tools.DiscoverCommand.ExecuteCore(RazorConfiguration configuration, String projectDirectory, String outputFilePath, String[] assemblies)
4>   at Microsoft.AspNetCore.Razor.Tools.DiscoverCommand.ExecuteCoreAsync()
4>   at Microsoft.AspNetCore.Razor.Tools.CommandBase.ExecuteAsync()
4>C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.CodeGeneration.targets(99,5): error : rzc discover exited with code 1.
```
Error List:
![image](https://user-images.githubusercontent.com/4528464/62887046-5c89e200-bd34-11e9-8a36-88c28b6014cb.png)

You have to have Sherlock Holmes skills to find it 😂🔎.

**Comment by StanislavPrusac** [comment]
In my case I solved this error: "rzc discover exited with code 1.", by turning of "Real-time protection" in in Windows Security.
I exclude "dotnet.exe" from "Windows Defender Antivirus" scan and/or allow it through "Controlled folder access".
