### ISSUE TITLE
Unable to create custom SignInManager in class library

### ISSUE THREAD

**Issue by saluce65** [aspnet/AspNetCore#11037]
I'm trying to create a custom `SignInManager` in a class library, where I'm overriding the `CheckPasswordSignInAsync` method to use LDAP password check rather than using the database (however, otherwise user information and claims are stored in the database by default).  

In .NET Core 2.2, this was a trivial task: all I needed to do was add `Microsoft.AspNetCore.Identity 2.2.0` to the library and derive from `SignInManager`.  

Unfortunately, it looks like the `SignInManager` class has been moved to `Microsoft.AspNetCore.App.Ref` library.  Because it is classified as a DotNetPlatform package type, I cannot bring it into a netstandard2.0 or netcoreapp3.0 class library.  The only way to get the `SignInManager` to show up correctly is by changing the `.csproj` file to target `Sdk="Microsoft.NET.Sdk.Web"`. Except, now I'm no longer creating a class library, I'm creating a new .NET Core 3.0 project, which is not what I want (nor will it compile without having a `Startup.cs` file).

`SignInManager` and `UserManager` should be accessible in a class library so that they can be inherited from for use in multiple projects.

**Comment by blowdart** [comment]
@DamianEdwards another side effect of 3.0.  

@HaoK is it feasible to move identity targetting?

**Comment by HaoK** [comment]
not really, sign in manager is heavily coupled to the Http Authentication stack (its basically some sugar on top of a series of cookies)

**Comment by saluce65** [comment]
I've just submitted a feature request (#11043) for a change that I think will make what I'm trying to do easier, without having to create a custom `SignInManager`.  It looks like the `UserManager` is actually available in `Microsoft.Extensions.Identity.Core version 3.0.0-preview-18579-0056`, but there's no preview5 version of the package.

**Comment by blowdart** [comment]
Closing as discussion will move to #11043
