### ISSUE TITLE
[blazor] json deserialisation takes too much time 

### ISSUE THREAD

**Issue by ichensky** [aspnet/AspNetCore#11031]
Simple client side blazor application, that should work offline:
1. After starting blazor client app loads `json` with data from server/cache. 
2. Blazor client app begin deserialize this `json`.
And the bigger this `json` the longer it will take to deserilize it. 

The idea: provide set of methods for marshalization C# objects between  server and client. 
For ex. server read data(for ex. from `json` file) deserialize it to the object and then send set of msil instructions with this object to the client and blazor client app just load them to the memory.

Also, in `web application`, json is popural, because it is easy to work with it from js. But in blazor there is no need to use and support it at all. In the asp.net core Controllers json serialization of objects can be replaced by default with more efficient binary protocol of transferring data between server and client `blazor` app.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ichensky.
This is not something we plan to do.
