### ISSUE TITLE
Fallback support for unsupported api version in asp.net core

### ISSUE THREAD

**Issue by pamedasa** [aspnet/AspNetCore#11039]
I am looking for feature to fallback to last recent api version when request made through un-supported api version. Let's say web layer is expsosing V1, V3 & V4 versions. If request was made through V2 version, then how to redirect request to V1 instead of throwing error message saying "Unsupported api version."

**Comment by davidfowl** [comment]
Gave you looked at https://github.com/microsoft/aspnet-api-versioning/wiki/New-Services-Quick-Start#aspnet-core

**Comment by pamedasa** [comment]
Yes, I looked at https://github.com/microsoft/aspnet-api-versioning/wiki/API-Version-Selector. Here configuration options are available to pick either maximum version (or) minimum available version. Instead of is there to fall back to nearest lower version through http request re-routing?

**Comment by pamedasa** [comment]
Any update on this? Currently I am blocked on this. Is there any way to route to different controller if specified route with api-version doesn't exist?

**Comment by pamedasa** [comment]
I have explored and implemented IActionSelector provided by asp.net core through which added fallback support. Closing the issue
