### ISSUE TITLE
WASM Libraries

### ISSUE THREAD

**Issue by Bartolomeus-649** [aspnet/AspNetCore#11041]
# WASM DLLs
It should be possible to write a C#/WASM library for  the web/http/html environment in the same way you write a dll for windows.
The WASM library should not only be available in the  WASM wold, but also be accessible form plain JavaScript, in a similar way other packages and modules are accessible. Som form of proxy/lib should be generated along with the WASM Library to bridge the gap between the plain JavaScript world and the WASM environment. Calling/using the stub/proxy from JavaScript should be like using any other package or module.

## All that glitters is not GUI
Today there's no really a good straight forward way to write a non GUI library in C#/WASM.
And if we in the future are planing on writing more and more sophisticated applications running in the browser we are going to need all the libraries we use all the time in our "normal" projects.

## A .NET Core/Mono DLL is a WASM library
Since we don't compile neither C# nor IL to WASM, so any DLL who does not need direct hardware access or depend on the Win32/native API is practically already a WASM library. All that needs to be done is to generate a stub/proxy for it so it can  appear and work like any other package or module in the browser.

## A central GDPR certified repository for libraries
Ideally a client should download a library one and only one time per version.
The way it's done today with many CDNs owned and operated by ad-revenue powered companies makes them impossible to use if you are to fully comply with GDPR (you can'd do anything that negatively impacts a persons privacy or integrity if you can avoid it with a reasonable cost/effort. And copying some files from a CDN and putting them on your own servers will never be considered unreasonable.).
So some kind of central GDPR certified repository would be great.

## Server side libraries
It should be possible to create a Server Side library which is exposed on the client side just like any other WASM library. Some kind of strongly typed proxy/lib should be automatically generated for both the normal -Net world and the WASM world (would be strange if we could call the Server Side library from WASM but not from Windows, or any other non-WASM .NET Core environment).

## Support Enterprise LoB applications
If you compare all the settings, tools, methods, technologies and so on that's available in an Enterprise Windows Environment just to manage,support and maintain their LoB applications. Everything from making sure that all dates in the Enterprise is entered, formatted and handled in the same way regardless of the different devices OS language, the clients regional settings, the system local and so on, to security features that ensure that nay client connecting to the network is an authorized fully patched client, with an authorized user.
Some how applications in the browser need to be "Enterprise Aware", they, for example, need a complete and a fully functional "[System.Globalization.CultureInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=netframework-4.8)", which reflects either the current Ent. device, the current Ent. user or the Global/Generic/Default Enterprise settings (and no, none of the current available "language" features does even come close to what's needed for this "simple" thing, every single property in CultureInfo is under the user/enterprise control, the Name property could be "de-DE", while have every other setting changed to match "en-US", absolutely no conclusions what so ever can be done by the Name property alone.).
Without this it will be a huge step for an Enterprise to start using SaS systems, they need to conform and march together with everything else.

/X

PS Lob system prints stuff in ways most people don't even realize, this needs to work too.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not an area we control.
If you still have this problem, feel free to report it on the https://github.com/mono/mono repo.

**Comment by Bartolomeus-649** [comment]
Well, who else produce WASM stuff?
Who else control the run time environment for dotNet code running in a browser?
