### ISSUE TITLE
Generating resx files is broken 

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#11054]
As a result of https://github.com/aspnet/AspNetCore/pull/10674, the `/t:Resx` target is missing from projects. 

To fix this, we need to set `<GenerateResxSource>true</GenerateResxSource>` to take advantage of Arcade's RESX feature, and delete the .Designer.cs files from source.

**Comment by natemcmaster** [comment]
See https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#generateresxsource-bool

We should probably also set `<GenerateResxSourceEmitFormatMethods>true</GenerateResxSourceEmitFormatMethods>`

**Comment by JunTaoLuo** [comment]
FYI, some repos won't be able to convert due to: https://github.com/dotnet/arcade/issues/3244.
