### ISSUE TITLE
Separate Components and Html-tags at syntax level Blazor

### ISSUE THREAD

**Issue by SamProf** [aspnet/AspNetCore#11055]
When we use another Blazor component we use component-tag, For example:
```
<Component1 SomeParameter="parameter value">Some ChildContent</Component>
```

On syntax level RazorCompiler don't know is it html-tag or component-tag. That's why we need 2-times compilation. And at second compilation Blazor will find Class with same name - Component1 will be component and if not - he will be html-tag.

Second problem, If  use component Component1 and then for-example change or remove namespace, you maybe will not have any error, Component1 become html-tag.

I propose t syntax level separate Components and Html-tags.
For example:
```
<@Component1 SomeParameter="parameter value">Some ChildContent</@Component>
```

This will have benefits
- We will not need in 2-time compilation. Compilation time will be reduced and perfomance increased.
- We will have much more Compile-Time errors if something will be wrong.
- We will have easier IntelliSense  for VS.

That;s all.

Also I propose separate Component Defined Parameters and forwarded html-attributes to component. For example:
```
<@Component1 @SomeParameter="parameter value" class="my-class" id="my Id">Some ChildContent</@Component>
```
Component1.razor
```
<div @Attributes>@ChildContent</div>
```

**Comment by SteveSandersonMS** [comment]
We're already planning to do this: https://github.com/aspnet/AspNetCore/issues/9860

Rather than using the `@` prefix, we're simply making the distinction by enforcing the existing convention about casing. `<PascalCase>` things are components, and `<kebab-case>` things are HTML elements.
