### ISSUE TITLE
Fail on startup for Http/2 HTTPS on Mac

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#11061]
Mac doesn't support ALPN: https://github.com/dotnet/corefx/issues/33016

In 3.0 HTTPS and HTTP/2 (and HTTP/1) are enabled by default. The GRPC template is going to disable HTTP/1. HTTP/2 per spec requires ALPN when used over HTTPS. Today this fails per request and you have to dig into the server logs for the error.

Proposal: Check for HTTPS + HTTP/2-only on Mac at startup and fail early.

@shirhatti @JunTaoLuo

**Comment by JunTaoLuo** [comment]
FYI @JamesNK

**Comment by Tratcher** [comment]
@JunTaoLuo for verification.

**Comment by JunTaoLuo** [comment]
Partly verified in https://github.com/aspnet/AspNetCore/pull/11473#issuecomment-505287505. I'll try it out on a preview 7 SDK.
