### ISSUE TITLE
[Discussion] NullReferenceException at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Query()

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/AspNetCore#11069]
This topic came from several other:
#2806
#3219
#3219

They all a bit different, but the reason (I think) the same: concurent access to HttpContext from different threads.

Our story is pretty similar: we have project on asp.net 1.1, and we widely using HttpContext and HttpContextContextAccessor for different things (mainly for custom authorization and access to Session info), and I'm not sure if all what we're doing is really safe.

My first question is: there was a several mentions in issues above that middleware is kind of safe place, but what about ActionFilters? 
We have a pretty easy one like this:
```
public class PartialViewFilter : IActionFilter
    {
        public void OnActionExecuted(ActionExecutedContext context)
        {
            
        }

        public void OnActionExecuting(ActionExecutingContext context)
        {
            context.HttpContext.Items["_partial"] = context.HttpContext.Request.Query.Keys.Contains("partial");
        }
    }
```
and catches NullReferenceException sometimes (not very often, less than 5% requests aprox).
Exception:

> System.NullReferenceException: Object reference not set to an instance of an object.
> at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Query()
> at ****.PartialViewFilter.OnActionExecuting
> …

The most interesting part is that problem start to be occurs only when we moved from 1.0 to 1.1 (no other changes at all). 

And now my second question: is any Best Practices how to avoid this? Or at least how to detect such things?

And the last one; what about to generate more accurate error? NullReferenceException is not really nice.

**Comment by davidfowl** [comment]
`IHttpContextContextAccessor` is usually where this sort of issue shows up and it's because of usage *after* the middleware has ended or because of multi threaded access.

The above code shouldn't have any problems unless you were also accessing the same request from another thread and that resulted in some corruption. 

Audit your IHttpContextContextAccessor usage and look for places (like logging or telemetry initializers) where you access the HttpContext or store it in a field or anything like that.

**Comment by antonGritsenko** [comment]
Thank you for the reply

> Audit your IHttpContextContextAccessor usage and look for places (like logging or telemetry initializers) where you access the HttpContext or store it in a field or anything like that.

I meant this part exactly when wrote about a best practice. If I quite understand the issue, this is not just a common thread-safe issue (where lock and other technique could help), but more about some "damage" of data during accessing from different threads. Am I right or this is something else?

Next question is about accessing itself. What is best practice for most common cases: logging and authentication? Could you please provide some sample snippet when this issue may occur?

**Comment by davidfowl** [comment]
> I meant this part exactly when wrote about a best practice. If I quite understand the issue, this is not just a common thread-safe issue (where lock and other technique could help), but more about some "damage" of data during accessing from different threads. Am I right or this is something else?

https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md

There's some stuff in there:
- Don't store the IHttpContextAccesor.HttpContext property in a field 
- The HttpContext isn't thread safe, so avoid using it from multiple threads
- Accessing the HttpContext after a requests ends is bad (as HttpContext are pooled, so you may mess with the next request in flight)

- I would avoid it for logging, though it is used there commonly, scopes are a decent alternative. You would make a scope with the appropriate data from the request that you want to capture and it would be attached to every log within that scope.
- For getting the current user, just make sure you access IHttpContextAccessor.HttpContext?.User everytime and it should be fine. We did some work to make sure HttpContext is null when the request is over so it should be hard to store a stale context if you access the property every time you need it.

**Comment by antonGritsenko** [comment]
@davidfowl the link is just brilliant! Thank you!

**Comment by antonGritsenko** [comment]
One last question: how can we troubleshoot cases like this one? Is any inner tools or something?

**Comment by davidfowl** [comment]
There are no tools today

**Comment by benaadams** [comment]
It should throw `ObjectDisposedException("Request has finished and HttpContext disposed.")` after https://github.com/aspnet/AspNetCore/pull/10319 rather than null ref
