### ISSUE TITLE
how can I share my layout cshtml by dll

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/AspNetCore#11060]
how can I complie the layout.cshtml file into dll file ,to reuse and share between project?
when i use asp.net mvc ,I use the RazorGenerator Custom Tool to complie cshtml ,,but is there any way to use in asp.net core 2.1??

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kugarliyifan.
You can define layout files in a Razor Class Library and reference it from the main application by path.
I've put together a sample project for you to see how this is done: https://github.com/mkArtakMSFT/Samples/tree/master/SharedLayoutInRCL

Look for the `SamplePage.cshtml` page, which is referencing the layout from the RCL.

**Comment by kugarliyifan** [comment]
> Thanks for contacting us, @kugarliyifan.
> You can define layout files in a Razor Class Library and reference it from the main application by path.
> I've put together a sample project for you to see how this is done: https://github.com/mkArtakMSFT/Samples/tree/master/SharedLayoutInRCL
> 
> Look for the `SamplePage.cshtml` page, which is referencing the layout from the RCL.

thank you very much!!!!!!!
