### ISSUE TITLE
Problem with getting client IP address in ASP.NET CORE web Api ?

### ISSUE THREAD

**Issue by Balirezaei** [aspnet/AspNetCore#11078]
I get server IP Address instead of client IP by using below method in ASP.NET CORE Web API .
Please tell me where I'm going wrong. I have used ServerVariables["HTTP_X_FORWARDED_FOR"] in asp mvc before and that has worked correctly.

```c#
private string DetectIPAddress(HttpRequest request)
        {
            var _IP = "RemoteIp:" + request.HttpContext.Connection.RemoteIpAddress.ToString() + " - LocalIpAddress:" +
                          request.HttpContext.Connection.LocalIpAddress;
            try
            {
                _IP += " IP.AddressFamily:" + Dns.GetHostEntry(Dns.GetHostName()).AddressList[1].ToString();
                _IP += " HostName:" + Dns.GetHostEntry(Dns.GetHostName()).HostName;
            }
            catch (Exception e)
            {
            }
            return _IP;
        }
```

**Comment by Balirezaei** [comment]
https://stackoverflow.com/questions/56525043/problem-with-getting-client-ip-address-in-asp-net-core-web-api

**Comment by Tratcher** [comment]
FYI here's the doc: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2

Also, you don't need `ForwardedHeaders.All` in that code.
