### ISSUE TITLE
Generate .nupkg files that contain aspnetcore-runtime MSI for insertion into Visual Studio

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#11071]
We are working with the SDK team to simplifying the insertion of the .NET Core SDK into Visual Studio. https://github.com/dotnet/core-sdk/issues/2166 Today, the ASP.NET Core runtime is inserted into VS via the .NET Core SDK. As a part of breaking the SDK into smaller pieces, we need to add a new build step to 2.1/2.2 and 3.0 builds which produce the following NuGet packages.

* AspNetCore.SharedFramework.$(Arch).$(MajorVersion).$(MinorVersion)
	* ID = VS.Redist.Common.AspNetCore.SharedFramework.$(Arch).$(MajorVersion).$(MinorVersion)
    * Contents 
		* $pkgRoot/aspnetcore-runtime-$(version)-win-$(Arch).msi
        * $pkgRoot/sfx_$(Arch).cab
	* Versions:
		* 2.1
		* 2.2
		* 3.0
    * Arch
		* x86
		* x64
* AspNetCore.TargetingPack.$(Arch).$(MajorVersion).$(MinorVersion)
	* ID = VS.Redist.Common.AspNetCore.TargetingPack.$(Arch).$(MajorVersion).$(MinorVersion)
    * Contents 
		* $pkgRoot/aspnetcore-targetingpack-$(version)-win-$(Arch).msi
	* Versions:
		* 3.0
    * Arch
		* x86
		* x64

### Implementation suggestions

The simplest implementation can use `nuget.exe` and a .nuspec file to wrap the files in a nupkg. We don't need to code-sign the nupkg or ship it to nuget.org

Example: https://github.com/dotnet/core-sdk/blob/844978f4c2a042abf5fc924729466a4dce3c047d/src/redist/targets/packaging/windows/clisdk/VS.Redist.Common.NetCore.Toolset.nuspec

/cc @mmitche @johnbeisner

**Comment by natemcmaster** [comment]
@johnbeisner can you confirm the IDs and layout of files in the nupkg in the description above 👆?

**Comment by natemcmaster** [comment]
Confirmed over email and updated the description above. Package ID should include major.minor, example VS.Redist.Common.AspNetCore.SharedFramework.x64.2.1

**Comment by natemcmaster** [comment]
cc @Pilchie - would be good to have someone from @anurse's team help out here. @johnbeisner has manually crafted the first round of .nupkgs to bootstrap the changes in VS, but we should add this to our build outputs soon so he doesn't have to keep doing that.

**Comment by jkotalik** [comment]
This should be done in 2.1, will merge into 2.2. Closing for now
