### ISSUE TITLE
AuthorizationFilterContext is no longer available in HandleRequirementAsync()

### ISSUE THREAD

**Issue by FeodorFitsner** [aspnet/AspNetCore#11075]
In ASP.NET Core 3.0 `AuthorizationFilterContext` is no longer available inside `AuthorizationHandler.HandleRequirementAsync()` method.

In 2.2 this method is used to work:

```csharp
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, CookieOrTokenAuthorizationRequirement requirement)
{
	if (context.Resource is AuthorizationFilterContext mvcContext)
	{
		if (mvcContext.Filters.Any(filter => filter is MyFilter))
		{
			context.Succeed(requirement);
			return Task.CompletedTask;
		}
	}
}
```

However, in 3.0 `context.Resource` is no longer `AuthorizationFilterContext`, but instead `Microsoft.AspNetCore.Routing.RouteEndpoint`.

What's recommended way of accessing action filters in 3.0 inside AuthorizationHandler?

**Comment by wu-yafeng** [comment]
``` csharp
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, CookieOrTokenAuthorizationRequirement requirement)
{
	if (context.Resource is Endpoint endpoint)
	{
		if (endpoint.Metadata.OfType<IFilterMetadata>().Any(filter => filter is MyFilter))
		{
			context.Succeed(requirement);
			return Task.CompletedTask;
		}
	}
}
```

In ASP.NET Core 3.0:

When using endpoint routing, 
Mvc will add all Filter as metadata to endpoint.Metadata and the `AuthorizeAsync` will called by `AuthorizationMiddleware`

**Comment by FeodorFitsner** [comment]
Worked like a charm, thanks for the fast response!

**Comment by rybkov** [comment]
As it is breaking change for Preview 8 - will we have workaround or suggested solution on how to redirect to custom URL when authorization failed?
