### ISSUE TITLE
Blazor (client): Support value converters or similar for binding

### ISSUE THREAD

**Issue by LaughingJohn** [aspnet/AspNetCore#11084]
Hi,

I'm new to Blazor and have been experimenting with porting an existing application (which is implemented in both WPF & SL). 

WPF and SL have ways of formatting values as they pass back and forth in a binding. Notably value converters (IValueConverter), but also StringFormat, TargetNullValue  and FallbackValue.

I wondered if there was anything like this available for Blazor (client side) or whether there was any plan to implement something.

I noticed it while trying to bind a nullable type to a Telerik control. The control doesn't support nullable types, although I hope it will. I thought I could have used a converter or possibly a TargetNullValue. I'm sure there are other circumstances where this could be useful.

Thanks.

**Comment by LaughingJohn** [comment]
I've just spotted format-value which I guess goes some of the way but a value converter can deal with bi-directional bindings.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @LaughingJohn.
This has been done as part of https://github.com/aspnet/AspNetCore/issues/8493

**Comment by LaughingJohn** [comment]
Thank you!
