### ISSUE TITLE
Blazor: EventCallback versus Action usage

### ISSUE THREAD

**Issue by chanan** [aspnet/AspNetCore#11090]
More of a question than a bug report.

I have a component that has this in it:

```
[Parameter] private Action OnDismiss { get; set; }

void onclick()
{
     OnDismiss?.Invoke();
     StateHasChanged();
 }
```

Based on the docs, I thought I should change to use `EventCallback` - the problem is that it won't compile `OnDismiss?Invoke();` once `OnDismiss` is of type `EventCallback`.

Is keeping `OnDissmiss` type of `Action` correct?

**Comment by egil** [comment]
In the docs they use `await callback.InvokeAsync(arg);` to invoke an `EventCallback`. I can confirm that works in my code with Preview-5 as well.

**Comment by chanan** [comment]
So:

```
if (OnDismiss != null) await OnDismiss.InvokeAsync(arg);
```

is correct?

**Comment by egil** [comment]
Since `EventCallback` is a struct it cannot be null, thus I think it should be safe to just call `OnDismiss.InvokeAsync(args)` directly.

**Comment by egil** [comment]
Unless you declare it as nullable, e.g. `[Parameter] public EventCallback<some type>? OnDismiss { get; set; }`. Then you can do a `OnDismiss?.InvokeAsync(args)`. 

I am not sure if declaring your events as nullable is recommended though.

**Comment by chanan** [comment]
I am not sure, but the way I am thinking about it, the user of the library can either provide an OnDismiss or not.

Another small gripe is that `Action.Invoke()` could be called with no args, while `EventCallback.InvokeAsync()` requires an arg. I can supply a "fake" arg, but then the developer using the library needs to do something like:

```
void OnDismiss(object someFakeArg)
{
    Console.WriteLine("OnDismiss");
    StateHasChanged();
}
```
which isn't great

**Comment by julienGrd** [comment]
I use Action also (and Func) rather than EventCallback. it can be a problem ? it's a performance issue ?

thanks !

**Comment by vertonghenb** [comment]
@julienGrd 
`EventCallback<T>` can be used for async and non-async functions without having to use 2 properties to link the functions to. For me this is the most interesting part.

**Comment by egil** [comment]
@chanan I dont think its bad at all.

With this syntax, you can, as @vertonghenb says, get two-way binding with less typing just by naming your parameters correctly (`Year` and `YearChanged` - see example at the bottom of the [data binding section in the docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#data-binding)).

Also, if you do not want to pass a parameter, you can use the `OnDismiss.InvokeAsync(EventCallback.Empty)`. It's there for that purpose. The subscribing function can then skip the argument, e.g. `private void Dismissed() { ... }`, and there should not be a need to call `StateHasChanged()` according to the docs (and my experience).

**Comment by chanan** [comment]
Using preview6

The nullable type is not needed and everything works even when not method is supplied. Closing this. Thanks @egil and @vertonghenb
