### ISSUE TITLE
UriHelper cannot be used to navigate to non-Blazor URIs in server-side

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#11099]
# Repro

Create a new server-side Blazor app (with auth).

Try to use `IUriHelper.NavigateTo("Identity/Account/Login")` (make a button).

It will go to the Not Found page instead of doing an actual navigation. However, making an `<a href>` with the same URL will navigate to the login page.

Using preview 6

**Comment by pranavkm** [comment]
Does the Router have a `NotFoundContent` set? We specifically choose to show you the NotFoundContent if the navigation was started programatically (via `NavigateTo`) and the route that could not be addressed. 

The pivot here is that `NavigateTo` is meant for navigating within the component route-space. You could use `NavigateTo("...", force)` to force a browser redirect without the router being involved.

**Comment by rynowak** [comment]
Ah sorry. I'm a blazor noob. Thanks for the help.
