### ISSUE TITLE
Template blazorserverside not found

### ISSUE THREAD

**Issue by UrielMhezzek** [aspnet/AspNetCore#11105]
I follow this commands. 

But if i want to run 
dotnet new blazorserverside -o WebApplication1

i get the Message: 

> dotnet : No templates matched the input template name: blazorserverside.

**Comment by anurse** [comment]
Can you post the output of `dotnet --info` please?

**Comment by UrielMhezzek** [comment]
Hello, here the output

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  No SDKs were found.

> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
> 

But i don't understand this, i have installed the Microsoft .Net Core SDK 3.0.100 - preview5 at this moment.

**Comment by anurse** [comment]
A couple more useful questions to answer

* What directories do you have in the `C:\Program Files\dotnet\sdk` folder?
* Do you have multiple `dotnet.exe`s in your `PATH`?
* Have you only installed the installers, or have you installed SDKs from the dotnet-install script or one of our own repo `build.cmd` scripts?

**Comment by UrielMhezzek** [comment]
> What directories do you have in the C:\Program Files\dotnet\sdk folder?


Yeah. That gave me the right clue. I actually installed (multiple) 32bit version. Shame on my head. Thank you.

**Comment by anurse** [comment]
No problem! Happy to help and glad you found the solutioN!
