### ISSUE TITLE
Compat testing of popular libraries for 3.0

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCore#11108]
As part of 3.0, there have been a [number of changes](https://github.com/aspnet/announcements/issues?q=is%3Aopen+is%3Aissue+label%3A%22Breaking+change%22+label%3A3.0.0) that may impact existing libraries that customers are using today. There of course also could be unintentional changes that end up breaking some of these libraries. It would be good to know about these sooner rather than later in order to help address the issues (e.g. fix the unintended break, send a PR to the library to make it work in 3.0, log an issue with the library with details, etc.).

To that end, we've compiled a list of popular libraries used by ASP.NET Core projects in (somewhat) descending popularity order. The list was constructed using a number of data sources including [NuGet package download counts](https://www.nuget.org/stats/packages), VS telemetry, [Twitter interactions](https://twitter.com/DamianEdwards/status/1133886079843495936), and team assumptions/knowledge. Any library that was determined to have usage by less than approx. 1% of the ASP.NET Core user base was excluded. *Note that the library names used here are actually the assembly names which in some cases do not match the NuGet package name.*

## Work description
For each library in this list, the idea is to complete a basic "Hello World" scenario applicable for that library using the latest available version, and record one of the following outcomes:
1. No issue found, library works in an ASP.NET Core 3.0 project
1. Library needs to react to 3.0 change, issue logged on library project
1. Library needs to react to 3.0 change, PR sent to library project
1. Unintended ASP.NET Core change causes library issues, issue logged/PR sent to ASP.NET Core to fix the issue and restore compatibility with library

## Library list
1. [ ] Swashbuckle.AspNetCore
1. [ ] AutoMapper
1. [ ] Serilog
1. [ ] Dapper
1. [ ] MessagePack
1. [ ] IdentityModel
1. [ ] NLog
1. [ ] Autofac
1. [ ] IdentityServer4
1. [ ] log4net
1. [ ] Polly
1. [ ] FluentValidation.AspNetCore
1. [ ] Npgsql
1. [ ] StackExchange.Redis
1. [ ] Microsoft.AspNetCore.Mvc.Versioning
1. [ ] RabbitMQ.Client
1. [ ] MongoDB.Driver
1. [ ] RestSharp
1. [ ] MySQL.Data
1. [ ] AWSSDK.Core
1. [ ] Hangfire.Core
1. [ ] MySQLConnector
1. [ ] MediatR
1. [ ] Npgsql.EntityFrameworkCore.PostgreSQL
1. [ ] Pomelo.EntityFrameworkCore.MySQL
1. [ ] Elasticsearch.Net
1. [ ] CsvHelper
1. [ ] Microsoft.Azure.ServiceBus
1. [ ] Oracle.ManagedDataAccess
1. [ ] NSwag.AspNetCore
1. [ ] protobuf-net
1. [ ] Microsoft.OData.Core
1. [ ] nodatime
1. [ ] MiniProfiler.AspNetCore
1. [ ] Ocelot
1. [ ] MySQL.Data.EntityFrameworkCore
1. [ ] Microsoft.AspNetCore.OData
1. [ ] Consul
1. [ ] ServiceStack.Text
1. [ ] Microsoft.Azure.Storage.Common
1. [ ] Microsoft.Azure.EventHubs
1. [ ] NWebsec.AspNetCore.Middleware
1. [ ] Confluent.Kakfa
1. [ ] SimpleInjector
1. [ ] MassTransit

**Comment by anurse** [comment]
Putting in `area-infrastructure` I guess? One problem we have in our "dispatching" logic is we don't have a great "cross-cutting" bucket to get it off the dispatch queue.

**Comment by rynowak** [comment]
I hereby certify this as good.

**Comment by Pilchie** [comment]
@davidfowl I know you did a bunch of work here - should this issue be closed now?

**Comment by davidfowl** [comment]
Yes, actually @glennc modified the spread sheet and we ended up chasing down a bunch of deps.
