### ISSUE TITLE
RemoteRenderer.OnRenderCompleted doesn't run on renderer sync context

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#11107]
This is more of a question than a bug report, but while investigating a different reliability issue, I noticed that `OnRenderCompleted` (the thing that can throw the *Received a notification for a rendered batch when not expecting it* exception) doesn't run on the renderer sync context.

I've been trying to use this knowledge to create some failure scenario I can report, but have been unable to objectively prove this can lead to any problem. So, this is really more of a question for people who've been working in this area: did we *expect* calls to this method to be serialized, or is it expected that the calls are unsynchronized?

For a while I thought this might explain any possible *Received a notification for a rendered batch when not expecting it* error, since if it runs in parallel on separate threads for the same circuit, then we might expect to find batch B before batch A, and hence throw. However, even adding random `Thread.Sleep` calls didn't allow me to create a repro. My remaining theory is that SignalR itself is ensuring no two calls occur in parallel for the same hub, which would alleviate any possible bug, although it would be a bit awkward for us to rely on this implicitly without even a comment about that.

@pranavkm @rynowak Do we believe it's safe for `RemoteRenderer.OnRenderCompleted` calls to be unsynchronized?

**Comment by pranavkm** [comment]
> My remaining theory is that SignalR itself is ensuring no two calls occur in parallel for the same 

From what I gathered, with a `send`, the client waits until the hub method is invoked, but does not wait for a response. This should mean that you could have concurrency in the body of the Hub method unless SignalR uses synchronization primitives on the server. @anurse \ @davidfowl would certainly know best.

That said, the body of `RemoteRenderer.OnRenderCompleted` doesn't look like it needs to be synchronized. The completed render task that would get processed further should run in the sync context. Here's the method for reference: 

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Server/src/Circuits/RemoteRenderer.cs#L196-L217

**Comment by BrennanConroy** [comment]
>with a send, the client waits until the hub method is invoked

Send waits for the bytes to be taken by the OS. Inside SignalR we accept bytes and consume them synchronously.

> Received a notification for a rendered batch when not expecting it

This should be fixed by @pranavkm because blazer wasn't awaiting sends and there is now an internal queue for sends.

**Comment by anurse** [comment]
> My remaining theory is that SignalR itself is ensuring no two calls occur in parallel for the same hub, which would alleviate any possible bug, although it would be a bit awkward for us to rely on this implicitly without even a comment about that.

SignalR **does** currently ensure that no two invocations for the same connection occur on a hub on the server, but this is something we are thinking about changing post-3.0 (#5351). However, we'd do so in an *opt-in* manner because there may be users depending on the serialized behavior. I think you can safely rely on the fact that for any given connection, no two invocations will be executing(*) at once.

(* - i.e. we won't process the next message until the `Task` returned by the Hub method is completed)

**Comment by SteveSandersonMS** [comment]
Thanks everyone! Andrew’s last post explains why I can’t observe any buggy behaviour then. 

The remaining question is whether we want to be more explicit about this inside Blazor by dispatching to the renderer sync context. If not we should at least add a comment to explain why it’s safe to assume correct ordering of this: https://github.com/aspnet/AspNetCore/blob/master/src/Components/Server/src/Circuits/RemoteRenderer.cs#L204

**Comment by anurse** [comment]
One thing, that doesn't really apply to you now but may later: This does **not** quite hold for Streaming (i.e. returning `IAsyncEnumerable<T>` from a Hub method). In that case we move on to the next message after starting the stream, and don't wait for all the items to be yielded.

Blazor isn't using streaming so it's not directly relevant, but useful context to have :).

**Comment by SteveSandersonMS** [comment]
Added comment in https://github.com/aspnet/AspNetCore/pull/11141
