### ISSUE TITLE
PlatformBenchmark broken

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#11100]
Due to this change:
https://github.com/aspnet/AspNetCore/commit/f10680a37ab34c2b92829bc5135dde253260614a#diff-d6a9ae754775b6cb72445c3b8db610c2

At this line:
https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/perf/PlatformBenchmarks/BenchmarkApplication.HttpConnection.cs#L102

@benaadams @davidfowl

**Comment by benaadams** [comment]
Ah

**Comment by davidfowl** [comment]
This is what happens when PR checks pass.

**Comment by benaadams** [comment]
Can probably add it back to the .sln now it uses a Framework Json

**Comment by sebastienros** [comment]
The issue is the `<Reference>` that depends on custom .props files, but these will break `dotnet build` that is required for the benchmark services.

**Comment by benaadams** [comment]
https://github.com/aspnet/AspNetCore/pull/11110

**Comment by benaadams** [comment]
Though now am wondering if ParseRequestLine should also be using the same sequence reader
