### ISSUE TITLE
Blazor: Support prerendering for static sites

### ISSUE THREAD

**Issue by ericwj** [aspnet/AspNetCore#11115]
### Is your feature request related to a problem? Please describe.
There is prerendering for server-side Blazor and for client-side using `Index.cshtml` (#8842, #10626), but this requires a web server (Razor Page). I hope there is a way to also perform some sort of prerendering for sites that are served completely statically from Azure Storage, `dotnet serve` or similar.

### Describe the solution you'd like
The basic premise would be that there is a way to prepopulate the `<app>` component(s) in `index.html` replacing the default `Loading...` text either at build or publish time (msbuild) or through a gesture from the CLI or tooling.

Since there can be only one `index.html` to be served as *the* `index.html` on a static site, there are a number of ways to let the code run to prerender `index.html` with some basic presumptions or perhaps static configuration and save it in the appropriate place in `index.html`.

### Describe alternatives you've considered
There is no suitable way to do this today afaik besides hacking it through manually opening a client-side blazor web page and then copying say the content of the `<app>` element from the browser developer tools after loading the `/` page into `index.html` or to do this (semi-automanually) with a browser control in e.g. WinForms, but this is troublesome to keep updated and/or to integrate into an automatic build/deploy.

### Additional context
It would be great to serve a default pre-populated `index.html`, especially for simple sites.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ericwj.
This is not something we plan to do in the near future.
