### ISSUE TITLE
Remove inline scripts from project templates

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#11111]
We should move all the inline scripts (if any) to separate js files.

**Comment by ryanbrandenburg** [comment]
I'm not aware of any instances of that offhand, was there an inciting incident for this?

**Comment by rynowak** [comment]
I believe `<script ...>` tag helper uses inline scripts.

**Comment by isaac2004** [comment]
@mkArtakMSFT do you have an example? I just searched the repo and didn't see any

**Comment by mkArtakMSFT** [comment]
Looks like indeed the current templates don't have a `<script>` tag in the content. At least not at the moment. As for the tag-helper, that's right, it does produce the tag so that may be something we will revisit during 3.1.

**Comment by ryanbrandenburg** [comment]
It's still not clear to me what the work item is here. The only instance I see of a `<script` tag having tag-helpery attributes still results in a script tag pointing to the file rather than an inlined script.

**Comment by mkArtakMSFT** [comment]
I'm closing this in that case. Thanks for confirming, @ryanbrandenburg

**Comment by blowdart** [comment]
OK bringing this back up for https://github.com/aspnet/AspNetCore/issues/14104#issuecomment-538153444

@rynowak says "We already have this, it isn't new", and the suggested fix, fallback is an inline script, specifically

```<script>!function(a,b,c,d){var e,f=document,g=f.getElementsByTagName("SCRIPT"),h=g[g.length-1].previousElementSibling,i=f.defaultView&&f.defaultView.getComputedStyle?f.defaultView.getComputedStyle(h):h.currentStyle;if(i&&i[a]!==b)for(e=0;e<c.length;e++)f.write('<link href="'+c[e]+'" '+d+"/>")}("display","none",["\/lib\/normalize.min.css"], "rel=\u0022stylesheet\u0022 ");</script>```

If this is unique to the LinkTagHelper then it only needs fixed there, but if it's a tag helper wide feature then we need to look at every tag helper and change them to use a different approach, like script registration and an output of all the registered scripts in a virtual .js file.
