### ISSUE TITLE
Give Blazor File a Proper Extension Name

### ISSUE THREAD

**Issue by Timothy-Liu** [aspnet/AspNetCore#11126]
When I introduce Blazor to students, I have to tell them - "The extension name of a Blazor file is Razor, and the extension name of a Razor page is cshtml." - which is very weird. Can we fix this issue and give the Blazor file a appropriate extension :)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Timothy-Liu.
Both `.cshtml` and `.razor` files are Razor files, but they're being compiled in different ways. We don't want to use `.blazor` extension because we may use `.razor` files for other application models too.
