### ISSUE TITLE
[Blazor Server Side] KeyPress/KeyDown event not working on div element

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#11137]
hello, these two events seem not fire when they are used on div element.
```
<div id="test-container-keydown" style="width: 100px;height:100px;background-color: red" onkeydown="@OnKeyDown">
    test container key down
</div>`
```

`async Task OnKeyDown(UIKeyboardEventArgs e)
    {
        //breakpoint never reach
    }`

I try to focus element before with a $("#test-container-keydown").focus() but still not working.

Thanks !

**Comment by SteveSandersonMS** [comment]
Does it work on an `<input>` element for you? Is this problem specific to a `<div>` somehow?

**Comment by julienGrd** [comment]
yes it working on input perfectly !

And i make another test, if i do something like this
```
<div id="test-container-keydown" style="height:100px;background-color: red"  onkeydown="@OnKeyDown" >
    test container key down
    <input type="text" bind="@Test"  placeholder="Enter text to fire OnKeyDown of the container" />
</div>
```
It works if i put the focus on the input and i begin write text (but it's not what i want to do)

**Comment by Andrzej-W** [comment]
`<div>` element is not fucusable and if there is no focus you will not receive `KeyPress/KeyDown` events. Here is a simple example in HTML (save it in html file and open in any browser):
```HTML
<!DOCTYPE html>
<html>
  <body>
    <div onkeydown="alert('Div KeyDown')">
      Sample text in div
    </div>
  </body>
</html>
```
You have to add tabindex attribute. Now you can use your mouse to click on text in `<div>` and then press any key:
```HTML
<!DOCTYPE html>
<html>
  <body>
    <div tabindex="0" onkeydown="alert('Div KeyDown')">
      Sample text in div
    </div>
  </body>
</html>
```

**Comment by Andrzej-W** [comment]
Before you add `tabindex` to `<div>` element you should read various remarks here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by SteveSandersonMS** [comment]
Thanks for explaining this, Andrzej!

**Comment by julienGrd** [comment]
thanks for the explanation guys, it works !
