### ISSUE TITLE
Add support for non-numeric LangVersion in Razor code generation

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/AspNetCore#11139]
I have a Preview5 project with `<LangVersion>latest</LangVersion>` currently corresponding to C# 7.3 and Razor code generation handles that as if it was C# 8 adding `#nullable` annotations to the .g.cs files which then result in compilation error CS8652 "The feature 'nullable reference types' is currently in Preview".

https://github.com/aspnet/AspNetCore-Tooling/blob/c9e0d2a60f7287d14c282555669b67a1000fef20/src/Razor/src/Microsoft.CodeAnalysis.Razor/RazorProjectEngineBuilderExtensions.cs#L53

The `LanguageVersion.Latest` enum member is `int.MaxValue` and thus numerically larger than C# 8 while meaning something below. The other two named members `LatestMajor` and `Preview` should probably be handled specifically as well.

As a workaround, I'm running with `<LangVersion>7.3</LangVersion>`, which fixes the code generation

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Tragetaschen.
@NTaylorMullen thoughts?

**Comment by NTaylorMullen** [comment]
Just verified, this is a bug on our side where we're interpreting C#'s latest version as 8.0 but in reality it's not. I wonder if this was missed from the get-go or if this was changed after-the-fact, that will take more investigation.

**Comment by Tragetaschen** [comment]
I was curious about what Roslyn provides in terms of LangVersion helpers. At worst, this is old news :)

https://github.com/gafter/roslyn/blob/master/src/Compilers/CSharp/Portable/LanguageVersion.cs#L352

**Comment by NTaylorMullen** [comment]
Ooo @Tragetaschen that's awesome! Thank you for the code link, we'll definitely use that.
