### ISSUE TITLE
How to change resource path dynamically based on the tenant(we are determining tenant based on host name)?

### ISSUE THREAD

**Issue by saiteja-y** [aspnet/AspNetCore#11138]
I'm trying to set up multi-tenancy with different set of resource files for each tenant separated in different folders. Where should I set the resource path to pick the folder based on tenant(By the way I'm identifying tenant based on hostname)?

Here is the folder structure I'm having - 

![Folder Structure](https://i.ibb.co/hC4L41R/Capture.png)

As of Now I hardcoded the value to Tenant1 in ConfigureServices section of startup.cs as shown below
```c#
services.AddLocalization(options => options.ResourcesPath = "Resources/Tenant1");
```
Where can I reset this path based on the Host name and how to do it?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by saiteja-y** [comment]
@mkArtakMSFT Thanks for responding, I have posted this on StackOverflow as well. Unfortunately, I didn't receive any response from the community. I'm kind of helpless on this scenario. Here is the link for the same question from stackoverflow - [Question](https://stackoverflow.com/questions/56555649/how-to-change-resource-path-dynamically-based-on-the-tenantwe-are-determining-t ), Any help is appreciated. Thanks in advance.

**Comment by mkArtakMSFT** [comment]
@saiteja-y check out how something similar is done here: https://github.com/aspnet/AspNetCore/issues/10612#issuecomment-497421265

**Comment by saiteja-y** [comment]
I'm able to achieve this for Razor views but not for Resource files. Both the tenants support multiple languages.

**Comment by mkArtakMSFT** [comment]
@javiercn, @rynowak  do you have any recommendation here?

**Comment by javiercn** [comment]
I'm not very familiar with our localization support. Maybe @DamianEdwards knows better?

**Comment by hishamco** [comment]
This is very interesting, I can think of this in two ways:

1- Add new localization option such as `ResourcesPaths` which allow to add multiple resources paths, one per tenant

2- Use `ResourceLocationAttribute` to specify the resource path for each tenant, this can be doable for multiple assemblies

**Comment by saiteja-y** [comment]
@hishamco Can you provide any working sample for the same?
 Is the solution provided by you is specific to any .net core version?

**Comment by hishamco** [comment]
>  Can you provide any working sample for the same?

I 'll try if I got a time, but you could have a try

> Is the solution provided by you is specific to any .net core version?

Nope

**Comment by hishamco** [comment]
@saiteja-y checkout this sample https://github.com/aspnet/Entropy/tree/master/samples/Localization.CustomResourceManager it may useful for you
