### ISSUE TITLE
Errors when prerendering a client-side Blazor component with an injected HttpClient

### ISSUE THREAD

**Issue by chrissainty** [aspnet/AspNetCore#11142]
### Describe the bug
When prerendering a client-side Blazor component which has an injected `HttpClient` the following error is thrown.

```
InvalidOperationException: Cannot provide a value for property 'Http' on type 'BlazorPrerendering.Client.Pages.FetchData'. There is no registered service of type 'System.Net.Http.HttpClient'.
```

I can add a `HttpClient` to the server projects DI container which gets over this initial error. But this leads to another error...

```
InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
```

I have also tried injecting `IComponentContext` then wrapping both the `@Inject HttpClient Http` statement and the call in `OnInitAsync` with a `IsConnected` check. But this gives me another error.

```
InvalidOperationException: Cannot provide a value for property 'componentContext' on type 'BlazorPrerendering.Client.Pages.FetchData'. There is no registered service of type 'Microsoft.AspNetCore.Components.IComponentContext'.
```

It seems something is not quite right here. 

### To Reproduce
Using the standard Blazor (ASP.NET Core Hosted) template, with detached prerendering enabled. This can be seen when trying to load the /fetchdata route.

### Expected behavior
Either ignore the need for an injected HttpClient when prerendering or allow the injection of `IComponentContext` so we can wrap the necessary lines, if that's the correct way to manage this.

### Additional context
This is present on Preview 5 of .NET Core 3

**Comment by iAmBipinPaul** [comment]
@chrissainty After registering HttpClinet on Server project also, Injecting client on index page also works.
but it does not work when calling another URL than root URL which also injects HttpClinet directly. 
`(curl localhost:[pror]:fetchdata)` does not work.

```csharp
  services.AddScoped<HttpClient>(s =>
            {
                var uriHelper = s.GetRequiredService<IUriHelper>();
                return new HttpClient
                {
                    BaseAddress = new Uri(uriHelper.GetBaseUri())
                };
            });
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrissainty.
As pointed out by @iAmBipinPaul, you should make you configure the `HttpClient` you register in the server project DI container (by setting up the `BaseAddress`.

Having said this, if you intend to call into the backend, you shouldn't use HttpClient directly. Instead, consider using a pattern demonstrated in the sample @danroth27 has created: https://github.com/danroth27/blazordualmode
