### ISSUE TITLE
Blazor GetJsonAsync returns an empty object

### ISSUE THREAD

**Issue by aguacongas** [aspnet/AspNetCore#11144]
In version 3.0.0-preview6.19307.2 the GetJsonAsync extension method returns an empty object 

### To Reproduce
1. Using this version of ASP.NET Core '3.0.0-preview6.19307.2'
2. Run this code `var response = await _httpClient.GetJsonAsync<SomeComplexeGenericType<SomeType>>("http://api")`
The object return is empty

### Expected behavior
Before version '3.0.0-preview6.19307.2' the object was successfully deserialized

### Additional context
I can workaround with : 

``` csharp
var message = await _client.GetAsync("http://api");
var content = await message.Content.ReadAsStringAsync();
var response = JsonSerializer.Parse<SomeComplexeGenericType<SomeType>>(content);
```

**Comment by pranavkm** [comment]
The JsonSerializer is case insensitive here and assumes camel case. We should change it to be case insensitive for deserialization. cc @rynowak

**Comment by aguacongas** [comment]
@pakrym if I tried to parse this :
``` json
{
	"data": {
		"listCompetitions": {
			"items": [
				{
					"id": "103/278513",
					"title": "FIFA Women's World Cup™",
					"localizedNames": [
						{
							"locale": "en-GB",
							"value": "FIFA Women's World Cup™"
						},
						{
							"locale": "fr-FR",
							"value": "Coupe du Monde Féminine de la FIFA™"
						},
						{
							"locale": "de-DE",
							"value": "FIFA Frauen-Weltmeisterschaft™"
						}
					],
					"from": "2019-06-07",
					"to": "2019-07-07"
				}
			],
			"nextToken": null
		}
	}
}
```

with this code :

``` csharp
var result = JsonSerializer.Parse<GraphQlData<TResponse>>(content);
Console.WriteLine(JsonSerializer.ToString(result));
```
 I received an empty object as well.

> WASM: {"Data":null}

Can you tell what JsonSerializerOptions I should use ?

**Comment by mkArtakMSFT** [comment]
This is already fixed!

**Comment by tsmccartan** [comment]
How do I get this fix for all my calls?  Do I need to wait till preview 7?

**Comment by mkArtakMSFT** [comment]
Yes @tsmccartan. this will be part of preview 7 release.

**Comment by ichensky** [comment]
@tsmccartan  You, can also add  `[JsonPropertyName("Id")] to all properties in serializable class, this can help with solving issue now.
