### ISSUE TITLE
Live Reload for Client Side Blazor

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/AspNetCore#11168]
### Describe the bug
There appears to be no support for Live Reload for Client Side Razor files. Making a change currently requires shutting down and restarting the application. For pure client side application that doesn't appear to be a good way to even run dotnet watch. For mixed client and Core project the process of shutting down and restarting is excruciatingly slow resulting in close to 10 seconds of cycle time which is not really conducive to live updates.

I'm trying to figure out whether this is supported or not and can't find any current documentation. Only references are old version bugs that don't seem to be resolved.

This seems a detrimental feature for a client side framework. Unless I'm missing some way to make this work it would seem pretty important to quickly see UI changes reflected in real time. With the current compile everything into a single assembly model it seems this would be difficult to accomplish, but a solution is needed. At minimum an easy way to cycle the app on changes - even if dreadfully slow as it is now - would be better than manual cycling at this point.

### To Reproduce

* Create a new Blazor Client Side Only project
* Run application with Ctrl-F5 (no debug)
* Make a change to a `.razor`  file
* See no auto-refresh
* Unable to manually refresh page
* Only way to  see change is shut down and restart Blazor app

### Expected behavior
A quicker way to see client side Razor page modifications.

### Additional context

Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by matthewblott** [comment]
I'm having this problem with a standard MVC project. If I include the ```AddRazorRuntimeCompilation``` extension method when adding the MVC components the project fails at runtime.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RickStrahl.
We're tracking the Live Reload work for Blazor as part of https://github.com/aspnet/AspNetCore/issues/5456
