### ISSUE TITLE
Validating JWT tokens and supporting multiple issuers

### ISSUE THREAD

**Issue by dluc** [aspnet/AspNetCore#11163]
### Is your feature request related to a problem? Please describe.

I'm using OpenID Connect (`Microsoft.IdentityModel.Protocols.OpenIdConnect` 5.4.0 nuget) in my C# web API, and I'd like to support and validate JWT tokens issued by multiple identity providers (MSA, LinkedIn, GitHub, Google, etc.), and I appreciate the fact that `Microsoft.IdentityModel.Tokens.TokenValidationParameters` supports multiple issuers (via `ValidIssuers`). 

On the other hand `Microsoft.IdentityModel.Protocols.ConfigurationManager<OpenIdConnectConfiguration>` ctor requires and allows only one `metadataAddress` (`.../.well-known/openid-configuration` URL) so I assume it's possible to download public keys only from one provider, is that correct?

Would it be possible to remove the required `metadataAddress` param, and use the trusted issuer URL to construct that URL instead? In fact that's what I'm currently doing for MSA, using the trusted issuer (e.g. `https://login.microsoftonline.com/<GUID>/v2.0`) and appending `/.well-known/openid-configuration`. In other words, the library allows multiple trusted issuers, but only one metadata address.

### Describe the solution you'd like
Could you provide guidance about supporting multiple identity providers, e.g. sample code or tutorial showing how that works?

### Describe alternatives you've considered
I considered creating multiple instances of the OpenID Connect manager, one per provider.

**Comment by blowdart** [comment]
We wrap the AAD JWT parser, so this is a question for them I'm afraid.

Your question would be better asked at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues

Or you add multiple instances of our JWT handler, and go through them one by one.

**Comment by dluc** [comment]
Thanks, I'll move the request to that repo, with a link here
