### ISSUE TITLE
[SignalR] Avoid over-negotiating in client

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#11160]
There are 2 cases where we might over-negotiate in the Typescript client (should audit the other clients too).

1. Client specifies a transport and server sends a larger list of supported transports, the client will still evaluate transports higher in the list if there are any, and cause a re-negotiate to happen
1. Client doesn't support WebSockets or EventSource and we evaluate that too late and cause a re-negotiate

**Comment by mikaelm12** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [ ] This is a Docs issue.
* [x] The fix contains product changes (**check all items below**).
	* [x] Relevant XML documentation comments for new public APIs are present. - Not needed
	* [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [x] The change requires no docs changes.
	* [x] Verification has been completed. (**check one item below**)
    	* [ ] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [VERSION]
			* ASP.NET Core Runtime: [VERSION]
			* .NET Core Runtime: [VERSION]
	    * [x] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: aspnet-signalr-3.0.0-preview7.19325.3
