### ISSUE TITLE
Razor components: What is the proper way to split up manual RenderTreeBuilder logic without breaking the diffing algorithm?

### ISSUE THREAD

**Issue by egil** [aspnet/AspNetCore#11177]
Hi all,

In the example provided below, where I use `builder.AddContent(int sequence, RenderFragment fragment)` method to compose a bunch of render fragments together, will the diffing algorithm break, when each render fragment in the example is using a number sequence starting from different positions?

This comment in [RenderTreeBuilder.AddContent](https://github.com/aspnet/AspNetCore/blob/release/3.0-preview6/src/Components/Components/src/RenderTree/RenderTreeBuilder.cs#L114-L117) suggests not, but I an not sure I am interpreting what I am reading in the docs and in the source code correctly. 

```csharp
public class Test : ComponentBase
{
    public bool SomeFlag { get; set; }

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.AddContent(0, RenderFragment1);
        builder.AddContent(1, RenderFragment2);
    }

    private void RenderFragment1(RenderTreeBuilder builder)
    {
        if (SomeFlag)
        {
            builder.OpenElement(0, "div");
            builder.AddContent(1, "HELLO WORLD SOME FLAG IS TRUE");
            builder.CloseElement();
        }
    }

    private void RenderFragment2(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "div");
        builder.AddContent(1, SubRenderFragment);
        builder.CloseElement();
    }

    private void SubRenderFragment(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "span");
        builder.CloseElement();
    }
}
```

Many thanks, Egil.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @egil.
@SteveSandersonMS any recommendations? Thanks!

**Comment by SteveSandersonMS** [comment]
For now, you can wrap different parts of your logic into different `RenderFragment` delegates, and insert them into each other, e.g.:

```
builder.AddContent(123, SomeOtherRenderFragmentMethod);
```

The builder will take care of wrapping the fragments in such a way that their sequence numbers can be independent.

Longer term we make make `AddRegion` public.
