### ISSUE TITLE
NoFormatter log message does not include ContentTypes from result

### ISSUE THREAD

**Issue by khellang** [aspnet/AspNetCore#11173]
When MVC fails to select an output formatter based on `ObjectResult.ContentTypes` (`Response.ContentType` has not been set), it logs the following warning:

> No output formatter was found for content type '' to write the response.

This is pretty unhelpful and confusing. I suggest the warning also includes the content types considered from the `ObjectResult`.

**Comment by rynowak** [comment]
This seems like a good thing to have. Wanna send a PR?

**Comment by khellang** [comment]
> Wanna send a PR?

Yup 👍

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg please look for a PR to review.
