### ISSUE TITLE
[Blazor] Input Component 

### ISSUE THREAD

**Issue by ostorc** [aspnet/AspNetCore#11176]
In preview 6 I get this error at build:

RZ10001	The type of component 'InputDate' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes: 'T'.	

The fix is easy as error says, just adding T attribute to control in razor file. However this wasn't necessary till this version. 

I get same error also for InputSelect.

**Comment by RemiBou** [comment]
I got the same error. Read the update blog post https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/ you need to change your "bind" by "@bind"

**Comment by matthewpetch** [comment]
So changing bind to @bind works, but I've still got loads of onclicks etc. that aren't @onclick that still work, which contradicts the release notes?

**Comment by RemiBou** [comment]
Maybe they are still supported but you should change it as there is a big change that the support will be removed in future version. If you don't replace ref by "@ref" you'll have an error like "No element is currently associated with component".

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us folks.
We've actually left the support for `onclick` without the `@` prefix for back compatibility for now. We don't plan to support it long term, so the prefix will be required long term.
