### ISSUE TITLE
Bind error @bind-value, @bind-value:event="oninput" with @oninput="@SomeMethod"

### ISSUE THREAD

**Issue by AmarjeetBanwait** [aspnet/AspNetCore#11178]
In asp.net core preview 6 doesn't allow following to use together on input element

`@bind-value="@SomeValue"`
`@bind-value:event="oninput"`
`@oninput="@SomeMethod"`

![bind error](https://user-images.githubusercontent.com/4598234/59433008-f2d08300-8e2b-11e9-9206-30e20148b66c.png)

**Error:**
Attribute 'oninput' is used two or more times for this element

**Comment by rynowak** [comment]
This is specifically not supported, as the error message indicates. We don't currently have the plumbing to attach multiple event handlers to a single event. For now I'd suggest just not using bind for this use case.

```razor
<input type="text" value="@SearchCriteria" @oninput="SearchHeroes" />

...
@code {
    void SearchHeroes(UIChangeEventArgs e)
    {
        SearchCriteria = (string)e.Value;

        // Do whatever processing you need to.
    }
}
```

**Comment by AmarjeetBanwait** [comment]
Thanks @rynowak  for reply. Do we have plans to support this in future?

**Comment by danroth27** [comment]
> Do we have plans to support this in future?

Not at this time.

**Comment by potudopotudo** [comment]
Hi, I had this code that worked before:

 `    <div>
            <input type="password" id="exampleInputPassword1"
                   class="password-input"
                   bind-value-oninput="@User.Password" @onkeyup="@CheckLoginButtonEnabled"
                   placeholder="Password" />
        </div>
`

But since I updated to the latest version of Blazor it the `bin-value-oninput` has stoped working. Do we have to handle all two-way-bindings with events for now?

**Comment by danroth27** [comment]
@potudopotudo We standardized the syntax for all Blazor directive attributes in preview 6. See https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/ for details.

Your example should now look something like this:

```html
<div>
    <input type="password" id="exampleInputPassword1"
        class="password-input"
        @bind-value="User.Password" @bind-value:event="oninput" @onkeyup="@CheckLoginButtonEnabled"
        placeholder="Password" />
</div>
```

**Comment by potudopotudo** [comment]
Thanks for the quick response, got it working now!

**Comment by springy76** [comment]
Why does `@bind="User.Password" @bind:event="oninput"` neither work nor throw any compile time or runtime error? (at least it binds attached to `onchange` event)

**Comment by danroth27** [comment]
@springy76 I think this got cleaned up as part of https://github.com/aspnet/AspNetCore/issues/10893.
