### ISSUE TITLE
SiteExtensions do not build with Arcade

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#11186]
While attempting to adopt Arcade, I ran into issues getting the src/SiteExtensions/ projects to build. In the latest draft of my PR, I have disabled the build of these projects because they might require a bigger refactor than I could fit into #11122.

Source of the problems:
* The hosting startup targets need to run a restore during build. The packages it needs to restore against might not exist or might not be in the correct format yet (haven't been code signed). https://github.com/aspnet/AspNetCore/blob/874050f1ddfa80f5fbba7ac87eaaa442de7e0f71/src/SiteExtensions/Sdk/SiteExtension.targets#L75-L85 Leads to errors like this: 
![image](https://user-images.githubusercontent.com/2696087/59453867-b702d280-8dc5-11e9-9adb-fe8b5257aaf5.png)
 
* The targets attempt to restore from the artifacts/ folder. Arcade is currently working on a plan to forbid the use of the 'RestoreSources' property in favor of nuGet.config (so we can use private restore feeds) https://github.com/aspnet/AspNetCore/blob/874050f1ddfa80f5fbba7ac87eaaa442de7e0f71/src/SiteExtensions/Sdk/SiteExtension.targets#L17-L21
* Lots of race conditions in the `ComposeStore` target causes MSBuild errors/warnings about files locked by another process. External issue, nguerrera is working on fixing for 3.0. dotnet/sdk#1211, dotnet/sdk#1072

**Comment by JunTaoLuo** [comment]
Follow up in #11534
