### ISSUE TITLE
Reconnects from pre-rendering are not reliable

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#11187]
Pre-rendering uses the same queue as disconnected circuits. The two have different requirements for caching, disconnected is best effort, versus pre-rendering needs to be more reliable. Using the two together result in clients attempting to reconnect failing.

-----------------------------------------------------
## Old text
The client does not inspect the result of the `reconnect` task during initial connection:

https://github.com/aspnet/AspNetCore/blob/b0be780f1b98db4c7d468f5167b6a439abf2f1b5/src/Components/Browser.JS/src/Boot.Server.ts#L98

This may return false when pre-rendering when the server no longer has any state: 

https://github.com/aspnet/AspNetCore/blob/b0be780f1b98db4c7d468f5167b6a439abf2f1b5/src/Components/Browser.JS/src/Boot.Server.ts#L82-L84

See here for an example:

![img](https://user-images.githubusercontent.com/174281/59394817-07caea80-8d36-11e9-8d4c-b496a589283a.gif)

**Comment by pranavkm** [comment]
I'm also running in to the same error with Ignitor + perf labs. Benchmarks starts off 256 clients (connections) by default, but the server maxes out at 100 retained connections. The initial `ConnnectCircuit` call for over half of these 256 gets rejected. Adding retries in `ConnectCircuit` works, but it's really iffy.

**Comment by mkArtakMSFT** [comment]
Closing this for now, as we are removing the stateful prerendering for 3.0.
