### ISSUE TITLE
[Blazor] Preview 6 blazorhosted project publish is broken

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#11185]
### Describe the bug
Using preview 6 sdk/templates, when publishing a blazor hosted project, publish output seems broken and trying to run the published app does not work

### To Reproduce
1. `dotnet new blazorhosted -o HostedTest`
2. `cd HostedTest\HostedTest.Server`
3. `dotnet publish -c Release -o bin\release\publish`
4. `cd bin\release\publish`
5. `dotnet HostedTest.Server.dll`
6. Navigate to `http://localhost:5000` => 404

### Additional context
It seems that the publish output folder is not right. For example the `index.html` file is missing from the `HostedTest.Client\dist` folder.
Here is the kestrel log of the request
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 27.119500000000002ms 404
```

**Comment by conficient** [comment]
Perhaps this is the same as/related to  #10878 and #11088 ?

**Comment by danroth27** [comment]
@mkArtakMSFT Please assign

**Comment by stsrki** [comment]
I can confirm the same problem has happened to me. To fix the error I had to manually copy all of the files in the **wwwroot** to my production server.

**Comment by kant2002** [comment]
Workaround for that for me was following
```
#if DEBUG
                endpoints.MapFallbackToClientSideBlazor<Client.Startup>("index.html");
#else
                endpoints.MapFallbackToClientSideBlazor<Client.Startup>("_content/client_project_name/index.html");
#endif
```

**Comment by smartprogrammer93** [comment]
Is there a work around to fix this. even though i made the site work on kestral. i cant make the iis version work

**Comment by mkArtakMSFT** [comment]
@smartprogrammer93, have you tried the workaround provided by @kant2002 above?

**Comment by smartprogrammer93** [comment]
@mkArtakMSFT yes. It only worked with kestral but not with IIS. I even copied the content of the folder to the wwroot. And that made kestral work but not IIS

**Comment by mkArtakMSFT** [comment]
Not really sure this is the same, but have you tried the workaround described here: https://github.com/aspnet/websdk/issues/604

**Comment by mkArtakMSFT** [comment]
@danroth27, I moved this out to 3.1, as the other related/similar issues are in there already and we can't fit this in current milestone.

**Comment by smartprogrammer93** [comment]
@mkArtakMSFT i will try this workaround when i have the time. Please note that moving this issue to to 3.1 milestone means that client blazor apps will never be able to be hosted in IIS which a lot of us use. I argue guys to reconsider.

**Comment by acorrow** [comment]
> @mkArtakMSFT i will try this workaround when i have the time. Please note that moving this issue to to 3.1 milestone means that client blazor apps will never be able to be hosted in IIS which a lot of us use. I argue guys to reconsider.

I could not agree more. It seems like it would be a huge miss to move this to 3.1, it's not like this is a feature request to get publishing into IIS, this is a regression bug. Preview 5 worked just fine with IIS publishing.

**Comment by javiercn** [comment]
I believe this is actually fixed as per my changes in https://github.com/aspnet/AspNetCore/commit/0a4f42a7e2030697ecf2c35b5de8b524b8bbf42f.

**Comment by acorrow** [comment]
Should note too, that while researching today at work, I found a bug with Blazor Publishing using the Preview 6 .NET Core runtime.

Essentially you have to use self-contained mode if you want to push up to Azure. A few bugs aside with that process, I found that pushing out the default template (no changes at all) to an Azure App service in Self-Contained mode, yielded a similar 404. I used Kudu to view the file structure and sure enough, there is an _ (underscore) in the wwwroot content name.

So just as a note to anyone researching 404 with Blazor and the 3.0.0-preview6 FW publishing to an Azure App service... this will happen there too ;)

I however have not a clue how to manually rename the files out in Azure. Anyone wanna fill me in there? Admittedly i haven't researched yet, as I'm at work, but if someone want's to point me in the right direction for when I'm home later.... ;) Cheers

**Comment by FluentGuru** [comment]
> Workaround for that for me was following
> 
> ```
> #if DEBUG
> endpoints.MapFallbackToClientSideBlazor<Client.Startup>("index.html");
> #else
> endpoints.MapFallbackToClientSideBlazor<Client.Startup>("_content/client_project_name/index.html");
> #endif
> ```

This works but you also need to do the same for the static files

**Comment by dustinlacewell** [comment]
@FluentGuru Hey, I'm just starting out with all of this. I got the `MapFallbackToClientSideBlazor` `DEBUG` snippet above working for me. But my site has no static files. Where and what do I change in order to do the same for static files as you say?

**Comment by FluentGuru** [comment]
> @FluentGuru Hey, I'm just starting out with all of this. I got the `MapFallbackToClientSideBlazor` `DEBUG` snippet above working for me. But my site has no static files. Where and what do I change in order to do the same for static files as you say?

@DustinCampbell you must add this part too if you are using static files found inside your blazor project folder
```
app.UseStaticFiles(new StaticFileOptions()
            {
                FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/_content/{blazorprojectname}")),
                RequestPath = new PathString("")
            }); 
```
