### ISSUE TITLE
Coding in @code block acts completely random

### ISSUE THREAD

**Issue by kevinjpetersen** [aspnet/AspNetCore#11189]
### Describe the bug
After replacing the old ``@functions`` block with the new ``@code`` block, coding in this has somehow ruined the development experience when it comes to indenting, unindenting, lists with initial values etc. Whenever you enter a new line in say a method, it defaults the cursor to the very start of the left side, instead of where the next code line should usually begin.

Switching ``@code`` to ``@functions`` makes the coding experience act as normal, prior to the ``@code`` (Preview 6)

### To Reproduce
1. Use a ``@code`` block inside a .razor page
2. Try to code a few things like if-statements and linebreaks, or a few variables. Most things inside the ``@code`` block unindents and your cursor is position is going wild.

### Expected behavior
Normal IDE editor behavior prior to the ``@code`` block

### Screenshots
![image](https://user-images.githubusercontent.com/1038017/59457801-6b7a1400-8e19-11e9-94a9-c5c93734f38a.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kevinjpetersen.
@ajaybhargavb can you please look into this? Thanks!

**Comment by ajaybhargavb** [comment]
This is a known issue. A partner team is working on fixing this. Duplicate of https://github.com/aspnet/AspNetCore/issues/10942.
