### ISSUE TITLE
Implement IHttpResponseCompletionFeature.CompleteAsync for response compression

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#11194]
https://github.com/aspnet/AspNetCore/pull/11193 added IHttpResponseCompletionFeature.CompleteAsync for gRPC scenarios, allowing the response to be completed without waiting for the request delegate to unwind.

ResponseCompression needs to wrap this feature in order to close and flush the compression buffer. Otherwise the response will be corrupt and an exception will be thrown when the compression middleware tries to flush on unwind.

@anurse recommend for preview7 or 8. ~~gRPC isn't relying on compression, but someone could add it and break.~~ Nevermind, response compression wouldn't ever interop with gRPC because A) HTTPS and B) Content-Types. We still need to implement this, but gRPC isn't a relevant scenario.

**Comment by anurse** [comment]
As this is labelled 'enhancement', I'm moving to the backlong. @Tratcher if you'd like us to get this done for 3.0, we could put @jkotalik on it :).

**Comment by Tratcher** [comment]
This will be covered by https://github.com/aspnet/AspNetCore/pull/12328
