### ISSUE TITLE
Blazor @ref should codegen a backing field

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#11197]
We already discussed and agreed we wanted to do this, but I don’t remember there being an issue for it. 

To keep it simple, we could do this for 3.0, then separately add @ref:assign as a future enhancement.

**Comment by Andrzej-W** [comment]
Are you going to automatically add this field to original source code (for example index.razor) or to index.razor.g.cs file?

**Comment by xclud** [comment]
#11370

**Comment by rynowak** [comment]
@Andrzej-W - it will be in the generated code. PR is here in case you are curious: https://github.com/aspnet/AspNetCore-Tooling/pull/707

**Comment by Andrzej-W** [comment]
Which code is used for intellisense? I'm afraid that without field in `@code` section we will not have intellisense.

**Comment by Andrzej-W** [comment]
There some more questions:
- Hopefully intellisense will be smart enough but if not, we will have errors in every place we use our "automatic" field. I think about errors displayed by intellisense in VS, not compilation errors.
- Will it somehow work with current "code behind" method which is based on inheritance?
- Will it work in the future when you implement partial classes for "code behind" experience?

**Comment by SteveSandersonMS** [comment]
> Hopefully intellisense will be smart enough

Intellisense is driven by the generated code, so this will work properly.

> Will it somehow work with current "code behind" method which is based on inheritance?

If you want the backing field to be in your base class, you'll need to use `@ref:suppressField` and put the field in your base class manually like you do today.

> Will it work in the future when you implement partial classes for "code behind" experience?

Yes, once these are partial classes, it will just work without needing `@ref:suppressField` or any other extra steps.

**Comment by Andrzej-W** [comment]
Thank you @SteveSandersonMS for explanation.

**Comment by springy76** [comment]
Due to that (breaking) change existing projects fail on compilation with a stack trace in build output: 

> rzc generate exited with code 1

VS (16.3preview2) crashes on most files which used @ref before.

**Comment by dodyg** [comment]
It doesn't work

![error-blazor](https://user-images.githubusercontent.com/1761249/63032403-08a70680-beb6-11e9-8aed-c4265eae0c76.png)

**Comment by dodyg** [comment]
Not sure what's wrong but this feature doesn't work

![blazor-error-2](https://user-images.githubusercontent.com/1761249/63032582-620f3580-beb6-11e9-809e-ee3a1ef658b7.png)

**Comment by springy76** [comment]
Indeed, my first step was to introduce `@ref:suppressField` everywhere (using Notepad++) to be able to open any of such files in VS again. While the VS editor understands this new codegen backing field, the compiler does not.

**Comment by rynowak** [comment]
Can one of your provide a complete file that has this problem? I need something to investigate.

**Comment by springy76** [comment]
Modified RazorClassLibrary.Component1.razor:

```
<div class="my-component">
    This Blazor component is defined in the <strong>RazorClassLibrary-CSharp</strong> package.

    @if ( false )
    {
        <Component1 @ref="recursion" />
    }
</div>

@code
{
    protected override void OnAfterRender()
    {
        _ = recursion.ToString();
    }
}
```

Looks fine in VS 16.3.0-Preview-2.0 : Intellisense works. But compiler says:

> Component1.razor(14,13,14,22): error CS0103: The name 'recursion' does not exist in the current context

**Comment by rynowak** [comment]
OK thanks, I'll try this out.

**Comment by campersau** [comment]
@rynowak I have opened a separate issue for it here https://github.com/aspnet/AspNetCore/issues/13099

**Comment by NTaylorMullen** [comment]
@rynowak looks like we nuke the backing field from the declaration files so any usage in the `@code` block can't compile because the corresponding directive attribute that's responsible for creating the backing field is gone. Did you want totake on #13099? If so I can re-assign

**Comment by rynowak** [comment]
Assigned to you. Thanks.
