### ISSUE TITLE
[API Review]: ListenOptions exposes both Endpoint and IPEndPoint

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#11209]
Do we need both? IPEndPoint just casts EndPoint as IPEndPoint (it's a shortcut).

cc @anurse @halter73 @jkotalik

**Comment by anurse** [comment]
Nah, I don't think we need both. Especially with the pattern matching stuff:

```csharp
if(options.EndPoint is IPEndPoint ip)
{
	// Party on dude...
}
```

**Comment by halter73** [comment]
I agree, but if we're removing the IPEndpoint property we should remove SocketPath and FileHandle properties as well since they also do little more than cast the EndPoint to a well-known derived type.

**Comment by davidfowl** [comment]
Do we make EndPoint internal then? When I made the change I didn't add support for listening on arbitrary endpoints either.

**Comment by halter73** [comment]
> Do we make EndPoint internal then?

I'm saying we should remove all the EndPoint-derived properties on ListenOptions if we're going to remove IPEndPoint. If we were to make EndPoint internal in addition to that, we would break every IConnectionListenerFactory not in Kestrel.Core which is all of them.

Of course the problem with only using EndPoint derived classes is that it's not very discoverable. Anyone can add a new EndPoint type, so how do developers discover which endpoint types each transport supports other than trial and error? How do they even know what to try?

We cannot have our cake and eat it too. I think we need to accept either redundancy or a lack of discoverability outside of docs/blogs/etc...

**Comment by davidfowl** [comment]
I’m not arguing that. I asked if we should remove the EndPoint property given that we cannot instantiate a ListenOptions with arbitrary endpoints.

**Comment by davidfowl** [comment]
Removed Endpoint
