### ISSUE TITLE
"Writing is not allowed after writer was completed" SignalR 1.1.0

### ISSUE THREAD

**Issue by keesdewit82** [aspnet/AspNetCore#11219]
### Describe the bug
Our logging shows many error (Error level) messages that we think are bugs in SignalR. The following log events appear:

> Microsoft.AspNetCore.SignalR.HubConnectionContext
> Failed writing message. Aborting connection.
> 
> System.InvalidOperationException: Writing is not allowed after writer was completed.
>    at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
>    at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
>    at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetSpan(Int32 sizeHint)
>    at System.Buffers.BuffersExtensions.Write[T](IBufferWriter`1 writer, ReadOnlySpan`1 value)
>    at System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.SignalR.HubConnectionContext.TryWritePingSlowAsync()

### To Reproduce
We cannot reproduce the issue, but the log files on our production servers are filled with the above messages.

### Expected behavior
We would not expect this to happen

### Screenshots
![image](https://user-images.githubusercontent.com/14981641/59503787-9ad46380-8ea1-11e9-8ac3-9f775f2a6634.png)

### Additional context
We use version 1.1.5 of the Microsoft.AspNetCore.SignalR.Redis nuget package, version 1.1.0 of the Microsoft.AspNetCore.SignalR.Core nuget package and version 1.1.4 of the javascript SignalR client. The web application is running on core 2.2.5

**Comment by BrennanConroy** [comment]
You can hit this error if the client sends large messages (over 32KB by default). If you want to allow larger messages you can configure your own limits using the options in `MapHub`. See https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.2&tabs=dotnet#advanced-http-configuration-options for how to set options. You're looking for `ApplicationMaxBufferSize` specifically.

In 3.0 we've cleaned up this message so it's more obvious what is going on.

**Comment by BrennanConroy** [comment]
Apologies I misread this.

You're hitting the same issue as https://github.com/aspnet/AspNetCore/issues/6701

This is an error you can ignore when `TryWritePingSlowAsync` is in the stack trace. We've fixed this in 3.0 to no longer throw this error unless there is actually an issue.

**Comment by keesdewit82** [comment]
Hi @BrennanConroy Thank you very much for your reply. I will close the issue.
