### ISSUE TITLE
Blazor addin can't updated

### ISSUE THREAD

**Issue by chrgraefe** [aspnet/AspNetCore#11214]
### Describe the bug
The update of the Blazor addin in Visual Studio 2019 16.2 Preview fails

### To Reproduce
1. Install via Gallery or VSIX fails

### Expected behavior
No Error

### Output of error
14.06.2019 10:30:05 - Microsoft VSIX Installer
14.06.2019 10:30:05 - -------------------------------------------
14.06.2019 10:30:05 - vsixinstaller.exe version:
14.06.2019 10:30:05 - 16.2.1045
14.06.2019 10:30:05 - -------------------------------------------
14.06.2019 10:30:05 - Command line parameters:
14.06.2019 10:30:05 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\ENTWICKLUNG\INSTALL\Microsoft.VisualStudio.BlazorExtension.16.0.19307.2.vsix,/callingprocessid:18032,/installas:3852
14.06.2019 10:30:05 - -------------------------------------------
14.06.2019 10:30:05 - Microsoft VSIX Installer
14.06.2019 10:30:05 - -------------------------------------------
14.06.2019 10:30:06 - System.ComponentModel.Win32Exception (0x80004005): Dem Aufrufer wurden nicht alle angegebenen Berechtigungen und Gruppen zugewiesen
   bei System.Diagnostics.Process.SetPrivilege(String privilegeName, Int32 attrib)
   bei System.Diagnostics.Process.EnterDebugMode()
   bei VSIXInstaller.UserImpersonationHelper.DuplicateSuppliedToken(IntPtr token, UInt32 callingProcessId)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by danroth27** [comment]
Blazor and .NET Core 3.0 require the latest release from the Visual Studio Preview channel: https://visualstudio.com/preview. Once you've installed that you should be able to install the Blazor VSIX.
