### ISSUE TITLE
Published application is not working for preview 6

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#11223]
I have published an app to **IIS** on my VPS server and I get the following error:

```
It was not possible to find any compatible framework version

The specified framework 'Microsoft.AspNetCore.App', version '3.0.0-preview6.19307.2' was not found.

  - The following frameworks were found:

      2.1.6 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

      2.2.0 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

      2.2.1 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

      3.0.0-preview5-19227-01 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]



You can resolve the problem by installing the specified framework and/or SDK.



The .NET Core frameworks can be found at:

  - https://aka.ms/dotnet-download


```

I have installed **Runtime 3.0.0-preview6-27804-01** from [this link](https://dotnet.microsoft.com/download/dotnet-core/3.0) but it is not working. 

![image](https://user-images.githubusercontent.com/900302/59516485-bd767480-8ec1-11e9-984c-21a534b8cdeb.png)

It seems the **Runtime & Hosting Bundle** is missing for preview 6. It was available for previous version. As it is marked in the picture above.

**Comment by kevinjpetersen** [comment]
Hey! I had the exact same issue. Turns out Microsoft haven't updated their download page with the latest Preview 6 links.

You can find them on this page: https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview6.md#notable-changes-in-300-preview-6

And a direct download link to Preview 6 Runtime & Hosting Bundle (ASP.NET Core) can be found here: https://download.visualstudio.microsoft.com/download/pr/82fe6f83-3212-4401-9d71-d48bbc9bb69b/e003304de24a434a0a27c24131a2cb9f/dotnet-hosting-3.0.0-preview6.19307.2-win.exe

**Comment by anurse** [comment]
@leecow @rowanmiller What's the situation with the preview6 hosting bundle on the download page? Looks like it's missing (https://dotnet.microsoft.com/download/dotnet-core/3.0).

@kevinjpetersen Thanks for posting that workaround link! We'll see if we can get the page fixed :).

**Comment by rowanmiller** [comment]
Looks like an issue in the metadata that drives the download page. I will get it fixed.

**Comment by rowanmiller** [comment]
Looks like there are a few other downloads missing from the page too. I'm working on getting it resolved now.

**Comment by kevinjpetersen** [comment]
It would be cool if the Download Page was a GitHub Document so when it's changed one place, it will be changed there aswell :) Just like Documentation works. Not sure if that's how it works already, but at an error was just discovered :)

**Comment by rowanmiller** [comment]
It is centrally managed as json files in https://github.com/dotnet/core. Those json files are consumed by the website and a bunch of other things.

**Comment by stsrki** [comment]
@kevinjpetersen I have installed Hosting Bundle but now I have another problem. It seems it is the same problem as in #11185. The client-side applications are not working, but server-side is working

**Client-side not working**: [link](https://bootstrapdemo.blazorise.com/)
**Server-side working**: [link](https://rcbootstrapdemo.blazorise.com/)

**Logs**:

```
Now listening on: http://bootstrapdemo.blazorise.com:80/

Now listening on: https://bootstrapdemo.blazorise.com:443/

Application started. Press Ctrl+C to shut down.

info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

      Request starting HTTP/1.1 GET http://bootstrapdemo.blazorise.com/  

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]

      Executing endpoint 'Fallback {*path:nonfile}'

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]

      Executed endpoint 'Fallback {*path:nonfile}'

info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

      Request finished in 57.303000000000004ms 404 
```

**Comment by rowanmiller** [comment]
FYI the issue with the files not being surfaced on the downloads page is now fixed.

**Comment by stsrki** [comment]
Everything is working now. After installing the Bundle I also had to manually copy files from **wwwroot**, including **index.html**. For some reason they were not published.

Closing now because that is another issue. tnx
