### ISSUE TITLE
npm package documentation for aspnet-prerendering outdated

### ISSUE THREAD

**Issue by flyrev** [aspnet/AspNetCore#11221]
https://www.npmjs.com/package/aspnet-prerendering links to an repository.

The page also states that "You should not use this package directly in your own applications, because it is not supported, and there are no guarantees about how its APIs will change in the future.".

It also states that "This NPM package is an internal implementation detail of the Microsoft.AspNetCore.SpaServices NuGet package." - so I suppose that that means that some version of Microsoft.AspNetCore.SpaServices will be compatible with some version of aspnet-prerendering, and should be used in conjunction with that but not otherwise. Could this be clarified, maybe?

I also note that the last release was 2 years ago - is there, or will there be, a new package one should use here?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @flyrev.
We're in process of prioritizing our efforts and identifying focus areas for the upcoming releases.
I'll get back to you in about a week.

**Comment by mkArtakMSFT** [comment]
@flyrev, I haven't forgotten about this. This is something we're working actively and I'll update this thread soon.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
