### ISSUE TITLE
Razor Generate Failed

### ISSUE THREAD

**Issue by Css-IanM** [aspnet/AspNetCore#11222]
Environment
Windows 10 Enterprise N 1809    17763.503
3.0.100-preview6-012264

### To Reproduce

1. `dotnet new blazorhosted -n projectname -o ./src`
2. `cd src`
3. `dotnet build`

### Expected behavior
Default project template should build.

In VSCode Omnisharp cannot load the client project. 
Output is as follows from rzc
```
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Titan\src\Titan.Client\Titan.Client.csproj'.
d:\Titan\src\Titan.Client\Titan.Client.csproj
C:\Users\%user%\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\RazorCompilation.targets(184,5): Error: rzc generate exited with code 1.
```

**Comment by danroth27** [comment]
@Css-IanM It looks like you are still using Blazor 0.7.0. Please update your project to 3.0.0-preview6. If this doesn't resolve your issue let us know and we'll take another look.

**Comment by Css-IanM** [comment]
@danroth27 So the templates for blazor [here](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new) are no longer valid or required with preview 6? I installed the `Microsoft.AspNetCore.Blazor.Templates::*` templates to get the `blazorhosted` project template of which i was want to work with. I am already running `3.0.100-preview6-012264` which only provides `blazorserverside`.
With all that said it appears to be more a template problem targeting the new preview, does that sound right?

**Comment by Css-IanM** [comment]
I found the issue. The command `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::*` installs 0.7.0 still. I had to specifically target the version `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview6.19307.2` This was a product of assumption and not entirely apparent. If you leave off the version and dont supply `*` for the version it will tell you the latest version and you can specify that.

**Comment by danroth27** [comment]
@Css-IanM Correct, the `*` means "use the latest *stable* version", where stable means the version doesn't have a preview moniker, like "-preview6".  Since we started versioning Blazor with preview monikers you now need to explicitly specify the version. You can find the exact command you need to run in the Blazor docs: https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started.
