### ISSUE TITLE
[SignalR][JavaClient] HubConnection.invoke() without return value

### ISSUE THREAD

**Issue by ddweber** [aspnet/AspNetCore#11220]
### Is your feature request related to a problem? Please describe.
I´m using the .NET Client and Java Client for SignalR.
I implemented some of my **server** methods without a explicit returnvalue like so:
```csharp
public async Task SendMessage(string user, string message)
```

The **.NET Client** calls these methods like so:
```csharp
await connection.InvokeAsync("SendMessage", "UserName", "Message");
```

The **Java Client** does not offer such a function to call a hubmethod without expecting an return value (but wait for the completition).
There is only this method available:
```java
HubConnection.invoke(Class<T> returnType, String method, Object... args)
```
which is not suitable for this purpose.

### Describe the solution you'd like
The java client offers a invoke function that does not expect a returnvalue but waits for completition.

**Comment by mikaelm12** [comment]
That's a good observation. Thanks.
A current work around would be to have your hub method return a bool indicating the if the hub method ran successfully but yeah, this is definitely a gap between the clients that we should look at.

**Comment by anurse** [comment]
Yeah, we should just have an overload that doesn't take a return type. We can confirm in triage but I suspect this meets the bar for preview7.

**Comment by mikaelm12** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [ ] This is a Docs issue.
* [ ] The fix contains product changes (**check all items below**).
	* [x] Relevant XML documentation comments for new public APIs are present.
	* [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [x] The change requires no docs changes.
	* [x] Verification has been completed. (**check one item below**)
    	* [ ] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [VERSION]
			* ASP.NET Core Runtime: [VERSION]
			* .NET Core Runtime: [VERSION]
	    * [x] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: com.microsoft.signalr:signalr the current version isn't actually valid. Since we just match it up with the final build version when we release.
