### ISSUE TITLE
SignalR Core 3.0 - TypeError: Cannot read property 'subscribe' of null

### ISSUE THREAD

**Issue by FeodorFitsner** [aspnet/AspNetCore#11234]
After migrating the app from .NET Core 2.2 to .NET Core 3.0 Preview 6 every call to SignalR hub produces JS error:

```
angular.js:15018 TypeError: Cannot read property 'subscribe' of null
    at HubConnection.isObservable (HandshakeProtocol.ts:47)
    at HubConnection.replaceStreamingParams (HandshakeProtocol.ts:42)
    at HubConnection.invoke (HubConnection.ts:251)
```

While checking different `3.0.0-*` versions of SignalR JavaScript library (https://www.npmjs.com/package/@aspnet/signalr) we determined that the error starts from `3.0.0-preview-19075-0444`. Previous version `3.0.0-preview-18579-0056` works fine. Looks like something related to streaming which is not explicitly used/enabled in our app.

Could it be something misconfigured on our side or perhaps conflict with some other lib?

**Comment by BrennanConroy** [comment]
This has been fixed in preview7 with https://github.com/aspnet/AspNetCore/pull/10780

**Comment by FeodorFitsner** [comment]
Thank you, looking forward to work with Preview 7!

**Comment by BrennanConroy** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [x] Relevant XML documentation comments for new public APIs are present.
    * [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [x] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [ ] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [VERSION]
            * ASP.NET Core Runtime: [VERSION]
            * .NET Core Runtime: [VERSION]
        * [x] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [@aspnet/signalr] [3.0.0-preview7.19326.7]
