### ISSUE TITLE
In the server-side Blazor template the exception handler points to a endpoint that is not defined

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#11243]
In the server-side Blazor template the exception handler points to a endpoint that is not defined. There is no endpoint for `/Home/Error`.

```csharp
app.UseExceptionHandler("/Home/Error");
```

**Comment by ryanbrandenburg** [comment]
I feel like it ought to be easier to notice when this happens, could we produce a warning? Or is it harder to tell when the endpoint is undefined than I'm thinking?

**Comment by mkArtakMSFT** [comment]
Seems like this has been fixed already. After a review with @SteveSandersonMS the fix doesn't seem reasonable so he's going to file a new issue to address this properly.
