### ISSUE TITLE
[Server Side Blazor] Trying to pass Uint8Array from JS to C# with JSInterop 

### ISSUE THREAD

**Issue by Mercurial** [aspnet/AspNetCore#11244]
### Describe the bug
Basically, in the javascript world, I am invoking a [JSInvokable] C# Method and passing a Uint8Array as the parameter.

```C#
let buffer = new Uint8Array([1,2,3,4]);
componentRef.invokeMethodAsync("ReceiveData", buffer);
```
then in the C# world you would have something like this
```C#
[JSInvokable]
public async void ReceiveData(byte[] data)
{
// do something with the bytes
}
```

### To Reproduce
To Reproduce simply create a C# Class with [JSInvokable] method and a javascript function that takes a componentRef and invoke the C# method as stated above.

### Expected behavior
I expect it to just pass the binary data byte[] to be just received, I believe its a problem with the SignalR JSON Serialization

### Screenshots
![image](https://user-images.githubusercontent.com/585569/59548163-6c2bbb00-8f7d-11e9-92db-994c2a86f8a1.png)

![image](https://user-images.githubusercontent.com/585569/59548176-9b422c80-8f7d-11e9-95ae-a63e3d655ba8.png)

**Comment by Mercurial** [comment]
To work around this at the moment what I am doing is basically passing a number[] from the javascript side and receiving it as an int[] in the C# side and converting it to a byte[] instead. Which might be very bad for performance 

```C#
[JSInvokable]
        public async void ReceiveData(int[] data)
        {
            /// @TODO: C# Blazor wont accept ArrayUint8 from JS so we pass the binary data as int[] and convert to byte[]
            byte[] buffer = data.Cast<int>().Select(i => (byte)i).ToArray();
            if (OnDataReceived.HasDelegate)
                await OnDataReceived.InvokeAsync(buffer);
        }
```

**Comment by anurse** [comment]
SignalR can't send binary data through the JSON protocol, but Blazor uses the binary MessagePack format so this *could* work. Having said that, it's very likely it doesn't work right now as it hasn't been implemented.

What happens if you try sending the underlying `ArrayBuffer` using the following code?

```javascript
let array = new Uint8Array([1,2,3,4]);
componentRef.invokeMethodAsync("ReceiveData", array.buffer);
```

**Comment by mkArtakMSFT** [comment]
@pranavkm is there something for us to do here, or should this move to the `System.Text.Json` owners?

**Comment by mkArtakMSFT** [comment]
@pranavkm parking this in preview7 assuming this will require no much work from us and will turn our to be System.Text.Json issue.
If, however, that's not the case, let's sync up - we may need to push this out.

**Comment by pranavkm** [comment]
Need to investigate it a bit. The worrying part is the `EndOfStreamException`. Just want to make sure there aren't any latent bugs in BlazorPack.

**Comment by Mercurial** [comment]
> SignalR can't send binary data through the JSON protocol, but Blazor uses the binary MessagePack format so this _could_ work. Having said that, it's very likely it doesn't work right now as it's not a scenario that we've focused on. I think we do support sending `ArrayBuffer` (the underlying storage type for typed arrays) though.
> 
> What happens if you try sending the underlying `ArrayBuffer` using the following code?
> 
> ```js
> let array = new Uint8Array([1,2,3,4]);
> componentRef.invokeMethodAsync("ReceiveData", array.buffer);
> ```
> 
> (Tagging in `area-blazor` for now, but if this is indeed a limitation in SignalR we're happy to re-route!)

that's weird because this worked on preview-5

**Comment by mwinkler** [comment]
I tried to pass a `ArrayBuffer` back to the server, no exception is fired, but the `Js.InvokeAsync` gets not resolved.

Simple example:

```
protected override async Task OnAfterRenderAsync()
{
    var r = await Js.InvokeAsync<int[]>("test");
}
```

Client code:

`window.test = () => new Uint8Array([1, 2, 3, 4]).buffer;`

**Comment by pranavkm** [comment]
@Mercurial we switched the JSON serializer used on the server around that release which might explain the behavior change you're seeing. System.Text.Json requires `byte[]` to be transmitted as a base64-encoded string to deserialize. I filed an issue for it https://github.com/dotnet/corefx/issues/39961, in the meanwhile, encoding it would be the way to go. https://stackoverflow.com/questions/12710001/how-to-convert-uint8-array-to-base64-encoded-string has some solutions for how to go about this.

As for the actual investigation, I'm not seeing the `EndOfStreamException` any longer so we're good there.

**Comment by Mercurial** [comment]
> @Mercurial we switched the JSON serializer used on the server around that release which might explain the behavior change you're seeing. System.Text.Json requires `byte[]` to be transmitted as a base64-encoded string to deserialize. I filed an issue for it [dotnet/corefx#39961](https://github.com/dotnet/corefx/issues/39961), in the meanwhile, encoding it would be the way to go. https://stackoverflow.com/questions/12710001/how-to-convert-uint8-array-to-base64-encoded-string has some solutions for how to go about this.
> 
> As for the actual investigation, I'm not seeing the `EndOfStreamException` any longer so we're good there.

how come it can receive an int[] but not a byte[] array without base64 encoding though? just a thought! 

I kinda need a very efficient way to send the bytes without the overhead of the encoding because Im sending video camera binary data to the function
