### ISSUE TITLE
No matching start tag

### ISSUE THREAD

**Issue by sbuchok** [aspnet/AspNetCore#11251]
The following code gives an error of "Encountered end tag 'div' with no matching start tag. Are your start/end tags properly balanced?" on "</div>

```
@for (var i = 1; i < 32; i++)
{
    @if (i % 7 == 0)
    {
        <div class="daysOfTheMonth">
    }

    <button @onclick="@(() => RandomEventName(i))" class="@IsSelected(i)">@i</button>
            
    @if (i % 7 == 0)
    {
        </div>
    }
}
````

This also then causes issues with the } brackets for the rest of the page, almost like it's missing the brackets aftert </div>. I'm sure there is a better way I can be doing this. I don't really like the way I did this anyways, so I'm going to change it, however, this is an issue. There will be circumstances where the opening and closing tags will be within seperate "if" blocks which is what seems to be causing this issue.

**Comment by anurse** [comment]
You can't split open/close tags between Razor code blocks like `@if`. Razor needs to be able to understand where the markup ends and the code begins and it does that by balancing markup tags.

Consider the markup in a Razor page just like any other C# block construct. You couldn't write code like this for example:

```csharp
if(i % 7 == 0) {
    try {
}
Console.WriteLine("Foo");
if(i % 7 == 0) {
    }
}
```

Razor is the same, but the tags are **part** of the code and have the same impact on the parsing of the document.

Razor does provide an "escape-hatch" here though, in the form of the `@:` command. This tells Razor to consider the rest of the line as HTML markup, but ignore all the tags on it. Just that one line is considered markup. So for example, you could write your sample like this:

```razor
@for (var i = 1; i < 32; i++)
{
    @if (i % 7 == 0)
    {
        @:<div class="daysOfTheMonth">
    }

    <button @onclick="@(() => RandomEventName(i))" class="@IsSelected(i)">@i</button>
            
    @if (i % 7 == 0)
    {
        @:</div>
    }
}
```

The docs on [Razor code blocks](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.2#razor-code-blocks) does a pretty good job of covering all this and has a bunch of useful examples. If there are some things missing there that would help you understand better, please feel free to comment on the doc or even send a PR!

Hope that helps!

**Comment by sbuchok** [comment]
I hate logging a bug only to find out that you didn't read the documentation ;)

Thanks, that makes sense.

**Comment by anurse** [comment]
Hey, it also means our docs may not be as easy-to-find as we want :). Let us know if there are places you looked for docs about this and didn't find them!

**Comment by git-net** [comment]
html tags wrong. only `.razor `,
code  
```
@for (var i = 0; i < 4; i++)
{
    @if (i % 2 == 0)
    {
       @: <div class="row">
     }  
    <button  >@i</button>

    @if (i % 2 == 1)
    {
         
      @:  </div>
    }
 
}
```
expect:
` <div class="row"> cells</div> `  `<div class="row">cells</div>`

**BUT** i got this:(RenderMode.ServerPrerendered or RenderMode.Server) 
`<div class="row"></div> cells `  `<div class="row"></div> cells`
bug?

**Comment by git-net** [comment]
@anurse

**Comment by sbuchok** [comment]
I think your issue is the i % 2 == 1 in the second if. I believe it should be the same as the first. Also, where is the word "cell" coming from? Your expected and your code you posted don't match up.

**Comment by anurse** [comment]
Please file a new issue if there is a problem/question here. Closed issues are not monitored during our regular triage process.
