### ISSUE TITLE
[API Review]: HubConnectionContext should take an options object

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#11258]
We already have 2 constructors and this release adds a 3rd:

https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.SignalR.md

Might make sense to pass an options object through.

**Comment by anurse** [comment]
Meh, I'm not that worried but I guess we could. We can talk in triage.

**Comment by davidfowl** [comment]
I am, and we should do it. I'm super concerned about constructor explosion on public types. Especially when there's no sign of that explosion getting smaller.

**Comment by anurse** [comment]
Ok, let's just do this.

**Comment by BrennanConroy** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [x] Relevant XML documentation comments for new public APIs are present.
    * [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [x] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [3.0.100-preview7-012628]
            * ASP.NET Core Runtime: [3.0.0-preview7.19325.7]
            * .NET Core Runtime: [3.0.0-preview7-27826-04]
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
