### ISSUE TITLE
Blazor - Add JsonSerializerOptions as parameter to HttpClient.GetJsonAsync<T>  

### ISSUE THREAD

**Issue by GoranHalvarsson** [aspnet/AspNetCore#11266]
I suggest you add JsonSerializerOptions as a parameter(could be optional) to the HttpClient.GetJsonAsync<T> method. For the deserialization of json you are using `JsonSerializer.Parse<T>(await httpClient.GetStringAsync(requestUri), JsonSerializerOptionsProvider.Options)`. 

The  parameter `JsonSerializerOptionsProvider.Options`  should be accessible.

This should probably be added to all extension methods in `Microsoft.AspNetCore.Components.HttpClientJsonExtensions`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GoranHalvarsson.
This is something we've been thinking about for quite some time. Parking in the next milestone for now to discuss what we're going to do here.

**Comment by GoranHalvarsson** [comment]
Im glad you will do this 😄

**Comment by mkArtakMSFT** [comment]
This issue was moved to dotnet/corefx#42688
