### ISSUE TITLE
IFormFile on List property never ends the request

### ISSUE THREAD

**Issue by rsuzumura** [aspnet/AspNetCore#11273]
When I upload a complex type with a list of IFormFile using .NET Core 2.1, the request works. But when I use .NET Core 2.2, the request never ends.

### To Reproduce
1. Using any version of ASP.NET Core 2.2
2. Run this code:
```
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Test.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TestingController : ControllerBase
    {
        [HttpPost]
        public IActionResult Post([FromForm]Parent model)
        {
            return Ok();
        }
    }

    public class Parent
    {
        public string Name { get; set; }
        public List<Child> Children { get; set; }
    }

    public class Child
    {
        public string Name { get; set; }
        public IFormFile File { get; set; }
    }
}
```
3. Test with Postman:
![image](https://user-images.githubusercontent.com/7788548/59577032-519a3480-9098-11e9-8ea1-f5aa517ef617.png)

### Expected behavior
Bind form values to model and end the request.

### Screenshots
Debugging the ASP.NET Source Code, I checked that collection grows, and the request never ends.
![image](https://user-images.githubusercontent.com/7788548/59577222-2b28c900-9099-11e9-8fe6-95ef43a8d9b6.png)

This bug is happening in all versions of .net core 2.2.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rsuzumura.
We know about this issue and we track the resolution as part of https://github.com/aspnet/AspNetCore/issues/4802

**Comment by rsuzumura** [comment]
Ok, sorry, I cannot found that issue. Thanks, @mkArtakMSFT.
