### ISSUE TITLE
Unexpected character encountered while parsing value: <. when authenticating using AzureAD

### ISSUE THREAD

**Issue by akousmata** [aspnet/AspNetCore#11274]
### Describe
I am seeing the error in the title on the .Net Client when it tries to connect and send a message but only after I have published it to our Azure App Service.  The App Service contains both an MVC app which acts as a .Net Client and the Hub itself.  In the .Net Client's HubConnection call I am using `options.UseDefaultCredentials = true;` which I'm not sure if that works using AzureAD default authentication.  It was difficult to find supporting documentation other than explicit OpenID implementations.  The Hub itself has the `[Authorize]` tag decorating it, but when I remove that, everything works fine.  I had previously posted about issues in the JS client and have since been able to resolve those.

### To Reproduce
1. ASP.NET Core 2.2.3
2. Code Samples
**Startup.cs**
```
// ConfigureServices
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => _configuration.Bind("AzureAd", options));
services.AddMvc(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            // SignalR
            services.AddSignalR(
                s => 
                {
                    s.EnableDetailedErrors = true;                    
                });
// More code.....
//         public void Configure(IApplicationBuilder app, IHostingEnvironment env)
// Configure
app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Sprints}/{action=Index}/{id?}");
            });

            app.UseSignalR(routes =>
            {
                routes.MapHub<HealthCheckHub>("/Hubs/HealthCheck");                
            });
```
**HubClass.cs**
```
    [Authorize] // Removing this tag allows everything to work correctly.
    public class BaseNotificationHub : Hub
    {
        private readonly BasicUserService _basicUserService;
        private readonly IUserIdMapper _userIdMapper;
        private readonly ILogger<BaseNotificationHub> _logger;

        public BaseNotificationHub(BasicUserService basicUserService, IUserIdMapper userIdMapper, ILogger<BaseNotificationHub> logger)
        {
            _basicUserService = basicUserService;
            _userIdMapper = userIdMapper;
            _logger = logger;
        }

        public virtual async Task SendMessageToAllAsync(string notificationType, object data)
        {
            try {
                await Clients.All.SendAsync(notificationType, data);
            }
            catch(Exception e)
            {
                throw;
            }
        }
        public virtual async Task SendMessageToUserAsync(Guid userId, string notificationType, object data)
        {
            try
            {
                var hubClientId = _userIdMapper.GetContextId(userId);
                await Clients.User(hubClientId).SendAsync(notificationType, data);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public virtual async Task MessageAcknowledged(Guid userId, Guid notificationId)
        {
            try
            {
                var hubClientId = _userIdMapper.GetContextId(userId);
                await Clients.User(hubClientId).SendAsync("MessageAcknowledged", notificationId);
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public override async Task OnConnectedAsync()
        {
            try
            {
                _logger.LogInformation($"Mapping user for id {Context.UserIdentifier}");
                var hubContextId = Context.UserIdentifier;
                var user = await _basicUserService.GetByUsername(hubContextId);
                var userId = user?.Id;

                if (userId.HasValue)
                {
                    _logger.LogInformation($"User ID {userId.Value} mapped to {Context.UserIdentifier}");
                    _userIdMapper.Add(userId.Value, hubContextId);
                }   
            }
            catch (Exception e)
            {
                throw;
            }

            await base.OnConnectedAsync();
        }
    }
```
**.Net Client Client connection**
```
hubConnection = new HubConnectionBuilder()
                    .WithUrl(BaseUrl + url.ToString(), 
                        options => 
                        {
                            options.UseDefaultCredentials = true; // Do I need to do something different here?
                        })
                    .Build();
```
3. With these arguments
4.
Server side (.Net Client) errors
```
Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.1 POST http://appname.azurewebsites.net/Hubs/HealthCheck/negotiate  0
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Authorization failed.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: AuthenticationScheme: AzureADOpenID was challenged.
Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 162.0716ms 302 
ADAMM.Services.Notifications.NotificationService: Attempt number 0 to reconnect hub failed. Retrying...
System.IO.InvalidDataException: Invalid negotiation response received. ---> 
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Microsoft.AspNetCore.Internal.JsonUtils.CheckRead(JsonTextReader reader)
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(Stream content)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(Stream content)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at App.Services.Notifications.NotificationService.ReconnectHubAsync(HubConnection hubConnection, Int32 attempts, Exception cause) in ...
```

### Expected behavior
When running this locally in VS 2017, I don't have the same issue, it connects to the hub and sends the message correctly in the .Net client even with the `[Authorize]` decoration present.

**Comment by anurse** [comment]
> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

This usually indicates that the server responded with HTML, such as perhaps a login page

> I am using `options.UseDefaultCredentials = true;` which I'm not sure if that works using AzureAD default authentication

I don't believe this works by default. Instead you'll need to use the Azure AD client libraries to get an authentication token and then pass that token in via SignalR's support for [Bearer tokens](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.2&tabs=dotnet#configure-bearer-authentication).

**Comment by akousmata** [comment]
Yes, the server is returning a 302  so I'm assuming it is redirecting to a login page which can be seen in the logs I provided here:
```
Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 162.0716ms 302
```
which explains the error, but I still don't understand why this works for me locally, but not when deployed to Azure.  Perhaps this is a better question for the Azure AD team, was just hoping I wouldn't have to write up the code that retrieves the access token.  This works out of the box with the javascript client without needing to retrieve an access token, but not the .Net client so I'm trying to understand the differences there and also why the client can successfully communicate with the hub when running locally without retrieving an access token.

**Comment by anurse** [comment]
> This works out of the box with the javascript client without needing to retrieve an access token

I believe this is because the Azure AD provider is dropping a local cookie that works.

> I still don't understand why this works for me locally

Using `UseDefaultCredentials` works locally? I'm not familiar enough with how that auth works to know why it would be different unfortunately. That setting is designed to enable the more traditional "Windows Authentication" mode (where Windows negotiates auth credentials for you automatically) which generally only works when you're communicating between Domain Joined machines **or when connecting to localhost** (because Windows just authenticates you as your local user).

I don't believe that model works for Azure AD unless you are in a hybrid-mode where you have a local domain syncing to Azure AD and your local machine (and the server) are both joined to the local domain rather than the Azure AD tenant. Perhaps your local machine is domain joined but the Azure server you are deploying to is not.

> Perhaps this is a better question for the Azure AD team

It may be worth checking in with them. You should view your SignalR connection like a REST API. When connecting from the .NET Client, you are basically doing the same thing that you'd do when calling a REST API on your server that is secured with Azure AD. When you configure the `options.AccessTokenProvider` setting in the SignalR client, the string you return is provided as a Bearer token in the HTTP `Authorization` header, which is the same mechanism you'd use to call a REST API on your site that was secured by AAD. Getting the token itself is done by the Microsoft Identity libraries.

**Comment by anurse** [comment]
Closing as I don't think there's anything actionable here for SignalR, the Azure AD authentication logic is external to SignalR. Feel free to let us know if there's additional context that will help identify an issue to resolve in SignalR!
