### ISSUE TITLE
For a ASP .NET Core (.net core 3.0 preview7)  Web API project via CLI, get the error "HTTP 404 error That’s odd... Microsoft Edge can’t find this page".

### ISSUE THREAD

**Issue by YunWeiaa** [aspnet/AspNetCore#11278]
### Describe the bug
For a ASP .NET Core (.net core 3.0 preview7)  Web API project via CLI, get the error "HTTP 404 error That’s odd... Microsoft Edge can’t find this page".

### To Reproduce
1. Install .NET core sdk 3.0.100-preview7-012424
2.  Create a new .net core ASP .NET Core Web App API project via CLI, dotnet restore and build succeeded.
3. Dotnet run succeeded, and display two listening ports. . Run [https://localhost:5001/api/values](https://localhost:5001/api/values), get the error "HTTP 404 error That’s odd... Microsoft Edge can’t find this page."
![image](https://user-images.githubusercontent.com/33921754/59586671-06266b80-9116-11e9-8740-0fa8fc95db8f.png)

### Expected behavior
Run [https://localhost:5001/api/values](https://localhost:5001/api/values ) succeeded with no errors.
![image](https://user-images.githubusercontent.com/33921754/59586822-5bfb1380-9116-11e9-9bd5-1b434a55c3c7.png)

### Environment data
dotnet --info output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012424
 Commit:    aafcce302b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012424\

Host (useful for support):
  Version: 3.0.0-preview7-27816-04
  Commit:  c36106d9b5

.NET Core SDKs installed:
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.400-preview-010219 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012424 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19315.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27816-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27816-04 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Note: For a ASP .NET Core(.net core 3.0 preview7) Empty web/Web App (Model-View-Controller) project can work well.

**Comment by Fax3D** [comment]
Same issue here (with preview 6): I need to perform a clean before launch debug, otherwise i got a 404.

**Comment by pranavkm** [comment]
@YunWeiaa does doing a clean either `git clean` or `dotnet clean` help?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem. We can't repro this issue.

**Comment by YunWeiaa** [comment]
Here is the repro project - [cs30webapi.zip](https://github.com/aspnet/AspNetCore/files/3300242/cs30webapi.zip)， hope to help you.

**Comment by mkArtakMSFT** [comment]
Thanks @YunWeiaa.
Looks like this was an intentional change on our end and the `ValuesController` is not there any more. We're going to fix this in the next update for the templates, which we hopefully squeeze into preview7 milestone (tracked elsewhere).

**Comment by mkArtakMSFT** [comment]
https://github.com/aspnet/AspNetCore/issues/11699
