### ISSUE TITLE
Value is invalid for target location when working with abstract classes

### ISSUE THREAD

**Issue by basslagter** [aspnet/AspNetCore#11280]
I have a structure like:

```
public class FilterSet {
  public string Id { get; set; }
  public List<BaseFilter> Filters { get; set; }
}

public abstract class BaseFilter {
    public string Id {get; set;}
    public string Name {get; set;}
    public abstract FilterType Type { get; }
}

public class Level1Filter {
   public override FilterType Type { get; } = FilterType.Level1;
   // contains some specific fields for this filter type like:
   public string FilterValue { get; set; }
}

public class Level2Filter {
   public override FilterType Type { get; } = FilterType.Level2;
   // contains some specific fields for this filter type like:
  public bool ShouldInclude {get; set;}
}
```

Now I want to add a filter and use :

```
{
 op: 'add',
 path: '/filters/-',
 value: {
     Name: 'My new filter'
 }
}
```

Now I get "The value is invalid for the target location". When I remove the abstract keysword on the BaseFilter, evything works fine.

So that seems to be an issue to begin with. But to make it somewhat more complex I actually want to add a specific filter, like:

```
{
 op: 'add',
 path: '/filters/-',
 value: {
     Name: 'My new filter',
     FilterValue : 'Filter on me'
 }
}
```

Is this even possible?

**Comment by basslagter** [comment]
Looking any further I guess the error is because one cannot create an instance of an abstract class of course. Maybe a more descriptive error message would be nice here.

But still...how can I get this to work? I guess I need to create an adapter or such?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @basslagter.
It's not clear what you're trying to do and what is the context here. If it's a general question about how to use ASP.NET Core, please
