### ISSUE TITLE
Blazor component property binding not working in NET Core 3.0 Preview 6?

### ISSUE THREAD

**Issue by mohankumar91** [aspnet/AspNetCore#11288]
I have bind value, click property to button element. And try to change the value when click the button to check "Property Binding". But it is not working as expected due to **OnAfterRender()** which is not triggered when click the button.

![propertyBinding](https://user-images.githubusercontent.com/18420823/59610693-7b566880-9137-11e9-9509-9851cda0921c.png)

` <input type="button" value="@buttonContent" onclick="@onToggleClick" />`

`@code {
    private void onToggleClick(UIMouseEventArgs args)
    {
        this.buttonContent = "False";
    }`

**Comment by guidevnet** [comment]
The error says that you have `something.ownerDocument` in somewhere (in the markup, probably), and `something` is null.

**Comment by campersau** [comment]
.NET event listeners now have to be prefixed with `@`.
```razor
<input type="button" value="@buttonContent" @onclick="@onToggleClick" />
```
See https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mohankumar91.
In preview 6 we've updated the way you register event handlers. Can you please confirm @campersau's suggestion solves your issues?

**Comment by karthickthangasamy** [comment]
It's working as expected while creating application with `Preview 6` package references and using `@` prefix with events.

**Comment by abhisheksiddhu** [comment]
@mkArtakMSFT 

I was earlier creating a new issue, but stumbled on this and this seems pretty close to the issue i am facing. 

VS seems to not recognize the new bind syntax.

![2019-06-18](https://user-images.githubusercontent.com/17928903/59706831-f3e42480-921e-11e9-9542-681cdcfaa4c9.png)

I am running VS 2019 v16.1.3 on Windows 10 Enterprise 1903 Build 18362.175

Also it seems to not recognize the new `@code` keyword instead of `@functions`

**Comment by mkArtakMSFT** [comment]
@abhisheksiddhu make sure you use the latest VS preview (16.2) with the latest Blazor Extensions and .Net Core 3.0 preivew (preview 6).

**Comment by abhisheksiddhu** [comment]
@mkArtakMSFT tried on 16.2 and it works fine on it. For now, I am sticking to the old syntax and will migrate later. I am assuming 3.0 final release will work out of the box in VS stable channel as well.

**Comment by mkArtakMSFT** [comment]
Yes, it will, @abhisheksiddhu.
