### ISSUE TITLE
Please can we have Javascript callback with parameter ?

### ISSUE THREAD

**Issue by samtax01** [aspnet/AspNetCore#11281]
Is there a way to add callback to Javascript and get the result in Blazor? Apart from JS Promises.

for example, let say i want to load a file

Javascript Code

```javascript
window.readFile = function(filePath, callBack) {
    var reader = new FileReader();
    reader.onload = function (evt) {
        callBack(evt.target.result);
    };
    reader.readAsText(filePath);
}
```

Can i have something like this in Blazor C#
```c#
    // read file content and output result to console
    void GetFileContent() {
        JsRuntime.InvokeAsync<object>("readFile", "file.txt", (string text) => {
            Console.Write(text);
        });
    }
```

Or Maybe something like this
```c#
    // read with javascript
    void ReadFileContent() {
        JsRuntime.InvokeAsync<object>("readFile", "file.txt", "resultCallbackMethod");
    }

    // output result callback to console
    void resultCallbackMethod(string text) {
        Console.Write(text);
    }
```#
Thanks

**Comment by guidevnet** [comment]
Yes, it is possible. It is covered on the [documentation.](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#invoke-net-methods-from-javascript-functions)

In your example, you are trying to send a file. Please be careful to not send something huge, because this communication will happen through SignalR.

**Comment by samtax01** [comment]
@guidevnet Please check my question very well. It is not in the documentation. I wanted a callback

**Comment by smartprogrammer93** [comment]
@samtax01 you can pass the instance of the object that you want the javascript to calllback and the method name to call through parameters as workaround. but no there is no support for passing an action to javascript to callback in the moment.

**Comment by SteveSandersonMS** [comment]
Anything that can be expressed as a callback (that gets called exactly once) can also be expressed as a promise, so I'd recommend wrapping your callback in a promise and returning that.

**Comment by samtax01** [comment]
Thank for the reply. I will do that
