### ISSUE TITLE
Covert IFormFile to MultipartFormDataContent

### ISSUE THREAD

**Issue by anilchaulagain25** [aspnet/AspNetCore#11287]
We are trying to implement Microservices in our project. Where we have to post IFormFile from ASP.NET core (2.2) MVC to ASP.NET core Web API (2.2).
So, we have to prepare MultipartFormDataContent from IFormFile, to push the file from MVC app to 
API.
So, extensions methods that converts IFormFile to MultipartFormDataContent will be helpful.
Form data may contain any type.
Or, are there any already solution for the above problem?
Thank you.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
