### ISSUE TITLE
ValidationProblemDetails issue with inheritance and xml response

### ISSUE THREAD

**Issue by neman** [aspnet/AspNetCore#11282]
### Describe the bug

When using inherited ValidationProblemDetails object, validation errors does not show for xml serialization (SuppressModelStateInvalidFilter is set to true).

Default ValidationProblemDetails and xml serialization works fine.

### To Reproduce
1. Using VS 2019 and SDK 2.2.203 of .NET Core
2. Create new web api project
3. This is ConfigureServices method content
```C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
            .AddXmlSerializerFormatters()                    
            .AddJsonOptions(options =>
    {
        options.UseCamelCasing(true);
    });

    services.Configure<ApiBehaviorOptions>(options =>
    {
        options.SuppressModelStateInvalidFilter = true;                
    });
}
```
4. Content of SamplesController
```c#
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace ValidationProblemDetailsSample.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SamplesController : ControllerBase
    {

        [HttpGet("NoInheritance")]
        public IActionResult NoInheritance([FromQuery]SampleModel model)
        {
            if (!ModelState.IsValid)
            {
                var validationProblem = new ValidationProblemDetails(ModelState)
                {
                    Title = "Test for default ValidationProblemDetails with validation errors",
                    Instance = HttpContext.Request.Path
                };

                return ValidationProblem(validationProblem);
            }

            return Ok();
        }


        [HttpGet("Inheritance")]
        public IActionResult Inheritance([FromQuery]SampleModel model)
        {
            if (!ModelState.IsValid)
            {
                var customValidationProblem = new CustomProblemDetails(ModelState)
                {
                    Title = "Test for inherited ValidationProblemDetails with validation errors",
                    Instance = HttpContext.Request.Path,
                    ErrorCode = 1
                };

                return ValidationProblem(customValidationProblem);
            }

            return Ok();
        }
    }

    public class CustomProblemDetails : ValidationProblemDetails
    {
        public CustomProblemDetails() { }

        public CustomProblemDetails(ModelStateDictionary modelState) : base(modelState) { }

        public int ErrorCode { get; set; }
    }

    public class SampleModel
    {
        [Required()]
        public string Email { get; set; }

        [Required()]
        public string Phone { get; set; }
    }
}

```
5. Run application and following request (example with Postman)
![image](https://user-images.githubusercontent.com/350314/59593027-7bcc1080-90f1-11e9-9b5b-cfe787b9a404.png)

6. There a re no validation errors

### Expected behavior
The expected behavior should be the same as when requesting `NoInheritance` method

![image](https://user-images.githubusercontent.com/350314/59592802-0b24f400-90f1-11e9-87dc-91fea21fa32d.png)

### Additional context
`dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.203\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524
```
The issue is simillar to https://github.com/aspnet/Mvc/issues/8221 but not the same

Code Example
[ValidationProblemDetailsSample.zip](https://github.com/aspnet/AspNetCore/files/3296134/ValidationProblemDetailsSample.zip)

**Comment by pranavkm** [comment]
For XML serializers, you'd have to perform custom serialization to do this. It's how `ProblemDetails` or `ValidationProblemDetails` work. Here's the relevant pieces of code:

* https://github.com/aspnet/AspNetCore/blob/b47b3e5ac6a6ef75f5bd5965d2db2fd49110ebf1/src/Mvc/Mvc.Formatters.Xml/src/ValidationProblemDetailsWrapper.cs

* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Formatters.Xml/src/ProblemDetailsWrapperProviderFactory.cs

* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Formatters.Xml/src/DependencyInjection/XmlDataContractSerializerMvcOptionsSetup.cs#L44-L46
