### ISSUE TITLE
Blazor: Debugging broken if project folder path contains spaces

### ISSUE THREAD

**Issue by amewsaj** [aspnet/AspNetCore#11285]
### Describe the bug
When attempting to add breakpoints in the browser debug tools, the breakpoint immediately disappears if the project folder path contains spaces (like the Users folder). 

### To Reproduce
Create a Blazor project in a folder with a path containing spaces.
Enable Blazor debugging
Start debugging in the browser (Alt+Shift+D)
Go to Blazor code in the browser debugging tools
Attempt to add breakpoint
Breakpoint is instantly removed again

### Expected behavior
Debugging should work as usual, even if a path contains spaces,

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @amewsaj.
We're going to handle this issue post 3.0 release as we're focused on most critical issues for that release only.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#17764
