### ISSUE TITLE
Mechanism to create an Inner HtmlHelper in MVC Core 3.0

### ISSUE THREAD

**Issue by ibasin** [aspnet/AspNetCore#11291]
This is not necessarily a bug.

I need to create an inner HtmlHelper for processing a property of my model such that the property is a root model under the new HtmlHelper. 

In the old MVC (pre .Net Core) I used the following code (_html in the code below is the current (outer) HtmlHelper):

        public HtmlHelper MakeInnerHtmlHelper(ModelMetadata metadata, string htmlFieldName)
        {
            new HtmlHelper<string>()

            var viewData = new ViewDataDictionary(Html.ViewDataContainer.ViewData)
            {
                Model = metadata.Model,
                ModelMetadata = metadata,
                TemplateInfo = new TemplateInfo
                {
                    FormattedModelValue = metadata.Model,
                    HtmlFieldPrefix = _html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName(htmlFieldName),
                }
            };
            return new HtmlHelper(new ViewContext(_html.ViewContext, _html.ViewContext.View, viewData, _html.ViewContext.TempData, _html.ViewContext.Writer), new ViewDataContainer(viewData));
        }

Could you please point me in the right direction on how to do this under .Net Core 3.0.

Thank you so much in advance.

Ilya

**Comment by ibasin** [comment]
I think it would be helpful to expose a public API to easily and correctly create an inner HtmlHelper.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by ibasin** [comment]
I ended up doing this (below). Not sure if this is 100% kosher but it served my purpose. I would welcome any comments/feedback.

        public IHtmlHelper<dynamic> MakeInnerHtmlHelper(ModelExpression modelExpression)
        {
            var innerHtml = NotTypedHtml.ViewContext.HttpContext.RequestServices.GetRequiredService<IHtmlHelper<dynamic>>();
            var viewData = new ViewDataDictionary<dynamic>(NotTypedHtml.ViewData, modelExpression.Model);
            var viewDataDictionary = new ViewDataDictionary(viewData) 
            { 
                Model = modelExpression.Model, 
                TemplateInfo = 
                { 
                    FormattedModelValue = modelExpression.Model, 
                    HtmlFieldPrefix = NotTypedHtml.ViewData.TemplateInfo.GetFullHtmlFieldName(modelExpression.Name)
                }
            };
            var viewContext = new ViewContext(NotTypedHtml.ViewContext, NotTypedHtml.ViewContext.View, viewDataDictionary, NotTypedHtml.ViewContext.Writer);
            (innerHtml as IViewContextAware)?.Contextualize(viewContext);
            innerHtml.ViewContext.ViewData["OuterHtml"] = NotTypedHtml;

            return innerHtml;
        }
