### ISSUE TITLE
Combine attributes specified on a Razor Page with attributes on model 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#11296]
3.0 adds supports for attributes being specified on Razor Page using `@attribute`. But if a model's present, these get ignored. We should instead consider combining attributes.

**Comment by pranavkm** [comment]
cc @mkArtakMSFT \ @rynowak

**Comment by pranavkm** [comment]
We should consider doing this prior to 3.0

**Comment by mkArtakMSFT** [comment]
parking in preview8 to check the bar during our planning meeting.
