### ISSUE TITLE
In Razor, conditional SVG <text> element doesn't contain content

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/AspNetCore#11316]
The following code is running as a server-side Blazor component in 3.0 Preview 6
```razor
<svg width="200" height="200">
    <text x="50" y="50" fill="green">@text</text>
    @if (test)
    {
        @:<text x="50" y="100" fill="red">@text</text>
    }
</svg>

@code {
    string text = "Text";
    bool test = true;
}
```
I have added the `@:` before the text element, so it's not handled as Razor's own `<text>` syntax.
However, the web browser doesn't show the second @&#8203;text content. According to its DOM in Edge Dev, the text string is outside the text element.

I can see from the generated C# code, that the first text is rendered as `OpenElement`, `AddAttribute` etc., while the conditional text is just a verbatim string. As a workaround, I have wrapped the SVG text element in additional gs: `<g><text... /text></g>`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Tragetaschen.
@ajaybhargavb any thoughts here?

**Comment by ajaybhargavb** [comment]
@Tragetaschen thanks for reporting this. This looks to be happening because of an underlying issue with Blazor tag rendering. I filed a separate issue to track that here https://github.com/aspnet/AspNetCore/issues/11612.

**Comment by ajaybhargavb** [comment]
@Tragetaschen, `@:` currently has some weird behavior with blazor rendering. You can workaround it by wrapping your second `text` tag in another `text` tag. So,

```razor
<svg width="200" height="200">
    <text x="50" y="50" fill="green">@text</text>
    @if (test)
    {
        <text><text x="50" y="100" fill="red">@text</text></text>
    }
</svg>

@code {
    string text = "Text";
    bool test = true;
}
```
