### ISSUE TITLE
Script Tag Helper no longer working

### ISSUE THREAD

**Issue by blue-hedgehog** [aspnet/AspNetCore#11314]
Using ASP.NET Core 3.0 Preview 6

The tag helper **asp-src-include** no longer works as with previous versions

This is implemented as follows:

**<script asp-src-include="~/dist/**/*.js"></script>**

This should return a list of script tags for all js files in the wwwroot/dist/ folder and its child folders

Instead the following error results:

ArgumentException: The path in 'value' must start with '/'. Parameter name: value
in Microsoft.AspNetCore.Http.PathString..ctor(string value)

This problem did not occur up to preview 5 and is new.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @blue-hedgehog.
@NTaylorMullen, can you please look into this? We need to understand what has changed between 2.2 and 3.0 and whether this was an intentional breaking change or not.

**Comment by NTaylorMullen** [comment]
@blue-hedgehog could you provide a minimal repro? I was unable to reproduce what you're seeing:

![image](https://user-images.githubusercontent.com/2008729/59868284-69e2ab80-9345-11e9-9715-1ef9f6a15145.png)

**Comment by blue-hedgehog** [comment]
Hi,

I am away on annual leave so it's difficult to provide more information right now.

Very basically the asp-src-include tag was working as expected on .Net Core 3 Preview 5, and then stopped working after upgrade to .Net Core Preview 6 with the aforementioned error message at runtime.

This is common across all developers on our project and across all uses of the asp-src-include tag helper and we have had to add every js file in a folder tree manually as a work around. Hence we have reported it as a breaking change.

Commenting out lines using the tag helper remove the runtime error for each instance, however (dozens of) js scripts used now need to be manually referenced.

Kind regards

Jeff

Get Outlook for Android<https://aka.ms/ghei36>





Managing Director
Jatech Ltd


[Jatech Logo]

Tel: 01278 588672

[Jatech Partner Logos]

Any opinions expressed in this email are those of the individual and not necessarily those of Jatech Ltd. This email and any files transmitted with it, including replies and forwarded copies (which may contain alterations), is intended solely for the addressee, is strictly confidential and may also be legally privileged. If you are not the addressee please do not print, re-transmit, store or act in reliance on it or any attachments. Instead, please email it back to the sender or contact Jatech on +44 (0) 1278 588672. Please then delete this email and destroy any copies of it. This email has been scanned for viruses, however we highly recommend that you virus scan any attached files using your own antivirus software.
JATECH LTD, The Forge Enterprise Centre, West Huntspill, Highbridge, Somerset.TA9 3RN. Registered in England No. 3292083



On Thu, Jun 20, 2019 at 6:25 PM +0100, "N. Taylor Mullen" <notifications@github.com<mailto:notifications@github.com>> wrote:


@blue-hedgehog<https://github.com/blue-hedgehog> could you provide a minimal repro? I was unable to reproduce what you're seeing:

[image]<https://user-images.githubusercontent.com/2008729/59868284-69e2ab80-9345-11e9-9715-1ef9f6a15145.png>

**Comment by mkArtakMSFT** [comment]
Hi @blue-hedgehog.
Unfortunately, we couldn't reproduce this issue. So it would really help if one of your team members could share a repro with us, so we can try to help.
