### ISSUE TITLE
[unit test request]WSFederation set Configuration programmatically without metadata.

### ISSUE THREAD

**Issue by lovelangy** [aspnet/AspNetCore#11311]
https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/WsFederation/src/WsFederationOptions.cs#L62

In above code,  it says:

> Configuration provided directly by the developer. If provided, then MetadataAddress and the Backchannel properties will not be used. This information should not be updated during request processing.

However, I cannot find any doc or sample talking about it .  Can you pelase add a unit test in WsFederationTest.cs to cover this senario ?

**Comment by blowdart** [comment]
@Tratcher

**Comment by Tratcher** [comment]
Here's one:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/1995f2c72911734a4ba08c6da1709c6e3e08a47b/test/Microsoft.IdentityModel.TestUtils/ReferenceMetadata.cs#L145-L180

**Comment by lovelangy** [comment]
@Tratcher  thanks, that is exactly what i am looking for.
