### ISSUE TITLE
Remaining pubternal APIs in the shared framework

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#11312]
We still have to look at packages but I haven't done that yet: I want to make sure these were intentional and not forgotten. If they were intentional I'd like to understand why they weren't made public APIs

- [x] - [Microsoft.AspNetCore.Authentication.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Authentication.Internal.md) (@HaoK @Tratcher, @Pilchie)
- [x] - [Microsoft.AspNetCore.Builder.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Builder.Internal.md) (@Tratcher @davidfowl, @anurse)
- [x] - [Microsoft.AspNetCore.DataProtection.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.DataProtection.Internal.md) (@natemcmaster @blowdart)
- [x] - [Microsoft.AspNetCore.DataProtection.Cng.Internal](https://github.com/aspnet/AspNetCore/blob/ab7f1caaf21630f500837224a3fd8a1fc53448d1/api-diffs/api-diffs_Microsoft.AspNetCore.DataProtection.Cng.Internal.md) (@blowdart )
- [x] - [Microsoft.AspNetCore.Hosting.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Hosting.Internal.md) (@Tratcher @davidfowl @anurse )
- [x] - [Microsoft.AspNetCore.Http.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Http.Internal.md) (@Tratcher @davidfowl @anurse)
- [x] - [Microsoft.AspNetCore.Mvc.Core.Infrastructure](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Mvc.Core.Infrastructure.md) (@rynowak @mkArtakMSFT )
- [x] - [Microsoft.AspNetCore.Mvc.Razor.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Mvc.Razor.Internal.md) (@rynowak @NTaylorMullen @pranavkm @mkArtakMSFT )
- [x] - [Microsoft.AspNetCore.Rewrite.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Rewrite.Internal.md) (@jkotalik @anurse )
- [x] - [Microsoft.AspNetCore.Routing.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Routing.Internal.md) (@rynowak @JamesNK)
- [x] - [Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.md) (@halter73 @davidfowl  @anurse)
- [x] - [Microsoft.AspNetCore.Server.Kestrel.Https.Internal](https://github.com/aspnet/AspNetCore/blob/9662a5bf542654b1ed1f8007efe068bb7063afcf/api-diffs/api-diffs_Microsoft.AspNetCore.Server.Kestrel.Https.Internal.md) (@anurse , @halter73 @Tratcher )
- [ ] - [Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http](https://github.com/aspnet/AspNetCore/blob/4ce7e8429385d19a286f7984ed98b00fd099de1a/api-diffs/api-diffs_Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.md) (@halter73, @davidfowl  @anurse )
- [x] - [Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure](https://github.com/aspnet/AspNetCore/blob/4ce7e8429385d19a286f7984ed98b00fd099de1a/api-diffs/api-diffs_Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.md) (@davidfowl, @halter73 , @anurse )

**Comment by natemcmaster** [comment]
For DataProtection, see https://github.com/aspnet/AspNetCore/issues/6975#issuecomment-457280598. It's the only context I have on that one.

**Comment by pranavkm** [comment]
- All of the Razor.Internal ones are runtime compilation specific. We made specific announcements for it.
- The Mvc.Core.Infrastructure is rather unfortunate. It's still there in 3.0: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/IAntiforgeryValidationFailedResult.cs

**Comment by HaoK** [comment]
For auth, it looks like we only have one RequestPathBaseCookieBuilder which seems harmless enough to make public and with the rest of the Authentication Core code, its shared between Cookies, OpenIdConnect and the base RemoteAuthentication classes.

@Tratcher any opposition to just making this regular public?  This class hasn't been touched since @natemcmaster added this 2 years ago when he introduced the cookie builder stuff.

**Comment by davidfowl** [comment]
> The Mvc.Core.Infrastructure is rather unfortunate. It's still there in 3.0: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/IAntiforgeryValidationFailedResult.cs

@pranavkm Why not move it out of the internal namespace?

**Comment by davidfowl** [comment]
> For DataProtection, see #6975 (comment). It's the only context I have on that one.

@blowdart besides "leave DataProtection alone", do you know if we can make this type internal now or make it properly public? There are 2 types:

```C#
public class DataProtectionBuilder : IDataProtectionBuilder {
         public DataProtectionBuilder(IServiceCollection services);
         public IServiceCollection Services { get; }
     }
```

This could be public or internal.

```
public interface IActivator {
    object CreateInstance(Type expectedBaseType, string implementationTypeName);
}
```

This should be internal.

**Comment by blowdart** [comment]
Why should it be internal?

@GrabYourPitchforks can you remember why this was written in this way?

**Comment by Tratcher** [comment]
@HaoK Yes, RequestPathBaseCookieBuilder can be public.

**Comment by Tratcher** [comment]
For sanity sake, let there only be one breaking change announcement that we add a few comments to.

**Comment by davidfowl** [comment]
> Why should it be internal?

It's a utility interface that's an internal implementation detail that doesn't need to be exposed to external users. We're doing mass clean up of pubternal types in ASP.NET Core 3.0, data protection is part of that clean up.

**Comment by davidfowl** [comment]
> @pranavkm All of the Razor.Internal ones are runtime compilation specific. We made specific announcements for it.

Can we move the code gen helpers to a CompilerServices namespace?

**Comment by pranavkm** [comment]
> Can we move the code gen helpers to a CompilerServices namespace?

Not super sure I follow. Are you talking about `CSharpCompiler`? For a lot of the others, the actual interface types are still public, as a rule MVC does not expose the actual implementation type.

**Comment by davidfowl** [comment]
> Not super sure I follow. Are you talking about CSharpCompiler? For a lot of the others, the actual interface types are still public, as a rule MVC does not expose the actual implementation type.

No, the types in Razor.Internal, like RazorInject attribute and the other things you said are required for code generation.

**Comment by pranavkm** [comment]
We decided to leave `RazorInject` in the pubinternal namespace. We wanted to avoid breaking 2.2 RCLs with generated content. We're treating it as part of our public API surface even though it's in the `.Internal` namespace.

**Comment by davidfowl** [comment]
We're making great progress on this!

**Comment by davidfowl** [comment]
@Tratcher can you look at **Microsoft.AspNetCore.Server.Kestrel.Https.Internal**?
@rynowak can you make a call on the types in ** Microsoft.AspNetCore.Routing.Internal** - You can leave make DfaWriter as public API with a comment about the fact it can break (similar to how EF has the warning on pubternal types)
I'll take **Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http**, this is the http parser we use in the platform benchmark.
@blowdart **Microsoft.AspNetCore.DataProtection.Internal** - I'm going to look at making things internal.

**Comment by rynowak** [comment]
https://github.com/aspnet/AspNetCore/pull/11752

**Comment by davidfowl** [comment]
Spoke to @GrabYourPitchforks and he says make them internal!

**Comment by NicolasDorier** [comment]
`EnableRewind` is quite useful, why was it removed?

**Comment by Tratcher** [comment]
@NicolasDorier because we made a properly public version named EnableBuffering.

**Comment by NicolasDorier** [comment]
Just another feedback:

I was using `AnsiLogConsole/WindowsLogConsole/IConsole` directly in the past as I did a custom `CustomConsoleLogger`, which is almost the same as the official one but with little adjustment. I have a bad memory about the initial reason, I think it is because I only wanted `[Info]` and nothing more in my logs. (No timestamp) and some custom stuff with log padding.

Since Internal namespace is now internal, my code broke. 

I don't think it is a big deal really, as I can just copy/paste those classes directly in my project. It is quite corner case and does not require me too much maintenance. Just wanted to share feedback.

**Comment by Samirat** [comment]
@Tratcher @davidfowl Can RequestCookieCollection be public? If implementing a custom IRequestCookieCollection or IRequestCookieFeature, there's not much reason to reimplement this vs inherit or wrap it.

I think you can get an instance of one anyway like this:
(new RequestCookiesFeature(new FeatureCollection())).Cookies;

**Comment by anurse** [comment]
@Samirat can you file a new issue for API requests like this?

I'm going to close this as we've finished the work on removing pubternal APIs. Feel free to open new issues to discuss particular APIs. We can triage those as appropriate.
