### ISSUE TITLE
Installing on Vs studio 2019 preview Enterprise 16.13

### ISSUE THREAD

**Issue by tridexanders** [aspnet/AspNetCore#11317]
18/06/2019 11:12:12 - Microsoft VSIX Installer
18/06/2019 11:12:12 - -------------------------------------------
18/06/2019 11:12:12 - vsixinstaller.exe version:
18/06/2019 11:12:12 - 16.1.3132
18/06/2019 11:12:12 - -------------------------------------------
18/06/2019 11:12:12 - Command line parameters:
18/06/2019 11:12:12 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,Z:\Temp\Microsoft.VisualStudio.BlazorExtension.16.0.19307.2.vsix
18/06/2019 11:12:12 - -------------------------------------------
18/06/2019 11:12:12 - Microsoft VSIX Installer
18/06/2019 11:12:12 - -------------------------------------------
18/06/2019 11:12:14 - Initializing Install...
18/06/2019 11:12:15 - Extension Details...
18/06/2019 11:12:15 - 	Identifier         : Microsoft.VisualStudio.BlazorExtension
18/06/2019 11:12:15 - 	Name               : Blazor
18/06/2019 11:12:15 - 	Author             : Microsoft
18/06/2019 11:12:15 - 	Version            : 16.0.19307.2
18/06/2019 11:12:15 - 	Description        : Provides Visual Studio support for Blazor
18/06/2019 11:12:15 - 	Locale             : en-US
18/06/2019 11:12:15 - 	MoreInfoURL        : 
18/06/2019 11:12:15 - 	InstalledByMSI     : False
18/06/2019 11:12:15 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
18/06/2019 11:12:15 - 
18/06/2019 11:12:15 - 	SignatureState     : ValidSignature
18/06/2019 11:12:15 - 	SignedBy           : Microsoft Corporation
18/06/2019 11:12:15 - 	Certificate Info   : 
18/06/2019 11:12:15 - 		-------------------------------------------------------
18/06/2019 11:12:15 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
18/06/2019 11:12:15 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
18/06/2019 11:12:15 - 		[Serial Number] : 330000026ECE6AE5984BFC96A900000000026E
18/06/2019 11:12:15 - 		[Not Before]    : 06/09/2018 22:00:30
18/06/2019 11:12:15 - 		[Not After]     : 06/09/2019 22:00:30
18/06/2019 11:12:15 - 		[Thumbprint]    : 99B6246883B4B32EA59AE18B36945D205A876800
18/06/2019 11:12:15 - 
18/06/2019 11:12:15 - 	Supported Products : 
18/06/2019 11:12:15 - 		Microsoft.VisualStudio.Community
18/06/2019 11:12:15 - 			Version : [16.2,)
18/06/2019 11:12:15 - 
18/06/2019 11:12:15 - 	References         : 
18/06/2019 11:12:15 - 	Prerequisites      : 
18/06/2019 11:12:15 - 		-------------------------------------------------------
18/06/2019 11:12:15 - 		Identifier   : Microsoft.VisualStudio.Component.Web
18/06/2019 11:12:15 - 		Name         : ASP.NET and web development tools
18/06/2019 11:12:15 - 		Version      : [16.0,)
18/06/2019 11:12:15 - 
18/06/2019 11:12:15 - Signature Details...
18/06/2019 11:12:15 - 	Extension is signed with a valid signature.
18/06/2019 11:12:15 - 
18/06/2019 11:12:15 - Searching for applicable products...
18/06/2019 11:12:15 - Found installed product - Global Location
****18/06/2019 11:12:15 - Found installed product - Visual Studio Enterprise 2019
18/06/2019 11:12:15 - VSIXInstaller.NoApplicableSKUsException: This extension is not** installable** on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by mkArtakMSFT** [comment]
Hi. Looks like you were trying to install Blazor extension on VS 16.13!
The minimum required version for the latest Blazor extension is VS 16.2 Preview: https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

**Comment by tridexanders** [comment]
1. thanks for that update... so i guess for now just wait a bit?

2. or is there a way around it at the moment ..

thanks for your help. ----> mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
@tridexanders you should simply update your VS to the latest preview release - VS 16.2 Preview 2 is already released.
