### ISSUE TITLE
Blank Page with Electron.NET using Blazor (ASP.NET Core) Preview 6

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/AspNetCore#11323]
**Description**
I created a vanilla Blazor (ASP.NET Core hosted) Preview 6. Then, I tried to transform it into a Desktop App using Electron.NET (version 5.22.12). But, I got a blank page.

### To Reproduce
1. Created a vanilla Blazor (ASP.NET Core hosted)
2. Added ElectronNET.API to the Server project
3. Setup Electron.NET stuff as described here https://maherjendoubi.io/blazor-electron/
4. electonize init
5. electronize start 

### Expected behavior
A vanilla Blazor (ASP.NET Core hosted) Preview 6 running as a Desktop App.

### Screenshots

![image](https://user-images.githubusercontent.com/1798510/59561991-f714c000-9026-11e9-8200-c5849be60d75.png)

### Logs
electronize start
Start Electron Desktop Application...
Microsoft Windows [version 10.0.18362.175]
(c) 2019 Microsoft Corporation. Tous droits réservés.
C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server>dotnet publish -r win-x64 --output "C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\bin"
Microsoft (R) Build Engine version 16.2.0-preview-19278-01+d635043bd pour .NET Core
Copyright (C) Microsoft Corporation. Tous droits réservés.
Restauration effectuée dans 19,34 ms pour C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Client\WebApplication20.Client.csproj.
Restauration effectuée dans 19,21 ms pour C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Shared\WebApplication20.Shared.csproj.
Restauration effectuée dans 23,89 ms pour C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\WebApplication20.Server.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message : NETSDK1057 : Vous utilisez une préversion de .NET Core. Voir : https://aka.ms/dotnet-core-preview [C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\WebApplication20.Server.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message : NETSDK1057 : Vous utilisez une préversion de .NET Core. Voir : https://aka.ms/dotnet-core-preview [C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Shared\WebApplication20.Shared.csproj]
WebApplication20.Shared -> C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Shared\bin\Debug\netstandard2.0\WebApplication20.Shared.dll
WebApplication20.Client -> C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Client\bin\Debug\netstandard2.0\WebApplication20.Client.dll
Blazor Build result -> 33 files in C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Client\bin\Debug\netstandard2.0\dist
WebApplication20.Server -> C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\bin\Debug\netcoreapp3.0\win-x64\WebApplication20.Server.dll
WebApplication20.Server -> C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\bin
C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server>
Skip npm install, because node_modules directory exists in: C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\node_modules
Invoke electron.cmd - in dir: C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\node_modules.bin
Microsoft Windows [version 10.0.18362.175]
(c) 2019 Microsoft Corporation. Tous droits réservés.
C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\node_modules.bin>electron.cmd "....\main.js"
stdout: Use Electron Port: 8000
stdout: info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
User profile is available. Using 'C:\Users\Maher\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
ASP.NET Core Application connected... global.electronsocket GLstc8UetcSP0PiFAAAA 2019-06-17T22:08:12.520Z
stdout: Hosting environment: Production
Content root path: C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\bin
Now listening on: http://localhost:8001
Application started. Press Ctrl+C to shut down.
stdout: BridgeConnector connected!
stdout: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
Request starting HTTP/1.1 GET http://localhost:8001/
stdout: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
Executing endpoint 'Fallback {*path:nonfile}'
stdout: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
Executed endpoint 'Fallback {*path:nonfile}'
stdout: info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
Request finished in 29.200300000000002ms 404
C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\node_modules.bin>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MaherJendoubi.
We don't currently support using Blazor with Electron.Net. Consider contacting folks @ https://github.com/ElectronNET/Electron.NET for help on this.

**Comment by MaherJendoubi** [comment]
@mkArtakMSFT I already did (https://github.com/ElectronNET/Electron.NET/issues/277). But the folks of Electron.NET need your support.

**Comment by mkArtakMSFT** [comment]
We're happy to help them out, but I can't see any response from them on the referenced issue.

**Comment by MaherJendoubi** [comment]
We run a discussion here https://gitter.im/ElectronNET/community

**Comment by juho-hanhimaki** [comment]
I find this issue important because Blazor client side no longer supports IE11. Offering electron app download for IE11 users would be nice workaround.

**Comment by danroth27** [comment]
@MaherJendoubi We'd love to help out, but with the upcoming .NET Core 3.0 release supporting Electron + Blazor isn't something we are focused on right now. If you have specific questions about Blazor then we can try to answer them.

**Comment by MaherJendoubi** [comment]
@mkArtakMSFT @danroth27 Thank you both.

**Comment by MaherJendoubi** [comment]
@danroth27 This is proof that the issue is related to an ASP.NET Core routing issue: https://github.com/ElectronNET/Electron.NET/issues/277#issuecomment-509022066

**Comment by robertmclaws** [comment]
I would argue that it's not _necessarily_ a **bug**, but the system got tighter about how it serves up resources, and the side effect is that Electron.NET doesn't work out of the box. I think it actually does a really good job of illustrating how flexible the new routing system is, because I was actually able to [leverage it to implement the fix](https://github.com/CloudNimble/ElectronNET.Blazor/blob/master/src/ElectronNET.Blazor/Extensions/IEndpointRouteBuilderExtensions.cs), once I figured out where all the files were.

I'm actually pretty happy with my solution, except for the fact that you have to add an environment variable to detect in the Electron version. Will maybe see if the Electron.NET team can automatically add something like it as part of the build process, so the end developer doesn't have to.

Keep up the great work on shipping 3.0, 'Softies! I know the schedule is tight, but the end is near. 👊🏻
