### ISSUE TITLE
Blazor - Inject script via C# during build

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore#11325]
Please consider adding a feature where we can use C# in a razor page to inject javascript code when the user is on the page, then it removes the javascript code when they leave the page. Ideally, this inject would create the required code to handle this during the build.

Currently, I am putting all of my custom javascript on the index.html page so it can get quite long and I lose track of why a method was added in support of some razor page. I am using the Blazor ASP Hosted framework.

Thanks

**Comment by Mercurial** [comment]
Couldn't you do it yourself in each page / component?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @VR-Architect.
@SteveSandersonMS what do you think about this? Do you think [Sections](https://github.com/aspnet/AspNetCore/issues/10452) work would cover this?

**Comment by SteveSandersonMS** [comment]
> it removes the javascript code when they leave the page

Unfortunately, unloading is not possible. A `<script>` tag is just a way of executing some JS within the context of the document. You can't "un-execute" it later.

For now I'd recommend using JS interop as a way to inject extra `<script>` tags into your document when a component loads. I'm sure it's possible to wrap this in a nice API to make it easy to reuse.

I'm not sure whether we'd make a built-in feature of this kind in the long run. In most cases I'd expect people to want to build complex JS assets using something like Webpack, which contains its own lazy-loading mechanism.

@mkArtakMSFT I suggest backlog or close.

**Comment by mkArtakMSFT** [comment]
Thanks @SteveSandersonMS.
Closing for now. If we hear more feedback in this area in the future, we'll reconsider.
