### ISSUE TITLE
[Blasor preview 6] any way to bind primitive parameter with ref ?

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#11328]
Hello Guys, i don't find any way to bind a primitive type to a child component and make the property updatable. My goal is to create a kind of toogle button bind to a bool property

Actually, it seem my only way to do this is something like that
```
<ToogleButton @bind-Value="@MyBoolProperty" OnChange="@((value) => MyBoolProperty = value)"  />
```
and call manually the OnChange on my toogleButton component

If I dont put the onchange, MyBoolProperty is never updated on the parent

I think it's because bool is a primitive type and it's a copy given to the child component , so original value never updated

There is better to do actually ?

Thanks !

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @julienGrd.
Your component (`ToggleButton`) should define a `ValueChanged` handler, as described in the `Component Parameter` section at https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#data-binding

**Comment by julienGrd** [comment]
Ok I finally understand it.

I did not understand I have to call explicitely my ValueChanged Callback in my child component, 
if i add it everything work.
`await this.ValueChanged.InvokeAsync(this.Value);`

I think it can be nice to add this on documentation because was not really clear (for me and certainly others)

thanks !
