### ISSUE TITLE
ViewImports don't work in Razor precompiled views across projects

### ISSUE THREAD

**Issue by glitch100** [aspnet/AspNetCore#11322]
### Describe the bug
I am having issues with a solution that comprises of a library and a web application. The library defines the `_Layout.cshtml`, and the `_ViewImports.cshtml`. I have it add the content files to the nuget package, so when the web application consumes the package it creates a `link` for the files. I can also see them in the `obj` directory once built, however none of the `@inject` calls are hit, or the `_ViewImports` which houses those statements isn't being hit. I can see the `*.Views.dll` and inspecting it does show the views, and on build inspecting the `.g.cshtml.cs` file I can see inject statements.

### To Reproduce
1. Set up two projects, a library and a webapp, with the library using view compilation to provide views. (Check https://github.com/glitch100/TestRazorViews)
2. Reference the library from the webapp, and remove all the associated layout files and viewimports
3. Fail to load the page when referencing something that should be injected

### Additional context
So there was another issue which got me closer to what I thought was the solution:
https://github.com/aspnet/Razor/issues/2481 

I basically used the following to ensure my files mapped correctly:
```xml
<ItemGroup>
  <RazorGenerate Include="$(NuGetPackageRoot)\{somepath}\_ViewImports.cshtml" Link="Views/_ViewImports.cshtml" />
  <RazorGenerate Include="$(NuGetPackageRoot)\{somepath}\Admin\_ViewImports.cshtml" Link="Areas/Admin/Views/_ViewImports.cshtml" />
</ItemGroup>
```

That places the linked files in the correct locations where I would expect them to be applied.
In addition I added a `IViewLocationExpander` which would also check the other locations just in case. To be honest I am just struggling around using the view compilation with explicit reference 
to ViewImports. 

My understanding was that they can't be compiled and must be added as `.cshtml` files because they are necessary for the compilation of other views.

**Comment by glitch100** [comment]
Here is a test repo with the same setup, bar the `<RazorGenerate>` additions

https://github.com/glitch100/TestRazorViews

**Comment by pranavkm** [comment]
`_ViewImports` are a Razor parse time feature. The parser has to discover these files at the time they're being parsed \ code generated. 
With the setup you've described, using `RazorGenerate` to map would well if you specifically care about build time compilation. To additionally make it work with runtime compilation you would need to add an `IFileProvider` to `RazorViewEngineOptions` pointing to `TestRazorWeb.Platform`.

**Comment by glitch100** [comment]
@pranavkm So I use the `RazorGenerate` to map, however the parser doesn't seem to take notice of them. Is the `IFileProvider` component necessary to ensure the `*.Views.dll` get's pulled in?

Using that repository as an example, can you confirm specifically what `RazorGenerate` settings would be required? The documentation _seems_ sparse, but I might be wrong

**Comment by mkArtakMSFT** [comment]
@pranavkm moving this to the `Discussions` milestone. If it turns out to be an issue on our end, please clean the milestone and we'll triage it.

**Comment by glitch100** [comment]
@pranavkm It does feel like the documentation just doesn't quite cover this scenario. It would be appreciated if you could point me to a sample or documentation that explains the use of the `IFileProvider` in tandem with the `RazorGenerate` statements
