### ISSUE TITLE
Post not working in Razor Pages in a Blazor Server Side Project

### ISSUE THREAD

**Issue by vdandrade** [aspnet/AspNetCore#11326]
### Describe the bug
A post does not work in a Razor Page inside a Blazor project! Is that by design?

### To Reproduce
Simply create a Razor page inside Blazor server side project:
```
    <form method="post" enctype="multipart/form-data">
        <input type="file" asp-for="Upload" />
        <input type="submit" value="Enviar" />
    </form>
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
