### ISSUE TITLE
Blazor client side template is missing.

### ISSUE THREAD

**Issue by ddabrahim** [aspnet/AspNetCore#11344]
Hi.

I have installed dotnet-sdk 3.0.100-preview6-012264 on Linux and there is no Blazor (client-side) template in the list when I try to create a new project.

![template-list](https://user-images.githubusercontent.com/24738433/59716377-cfcc1780-920d-11e9-83a9-f9575eaeaef1.png)

Could anyone help please how to create a Blazor client-side project on Linux or confirm if it a bug or known limitation on the platform or SDK I have installed?

Thanks.

**Comment by ghidello** [comment]
The blazor client-side templates are not added with the sdk. You should be able to install them with the command `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview6.19307.2`

**Comment by ddabrahim** [comment]
Thanks, it worked.
