### ISSUE TITLE
ASP.NET Core Modular

### ISSUE THREAD

**Issue by thanhnntq** [aspnet/AspNetCore#11357]
I'm trying to make a modular platform with .NET Core 3.0 like .NET Core 2.2 version with both Razor MVC and Razor Page but can't.

I would like to have a section to load the Assembly and other functions that work (MVC, Razor Page ...) and for Razor Page, there are more configurable root directories.

A sample folder struct i made with .NET Core version 2.2
```
|-- ROOT
|   |-- Core (Host)
|   |-- Modules
|   |   |-- Module A
|   |   |-- Module B   
|   |   |-- Module ...
|   |-- Libraries
|   |   |-- Lib A
|   |   |-- Lib B
|   |   |-- Lib ...
```

It's working but at .NET Core 3.0 Preview it's not working.

Please help me! Thank you so much!

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
Also, please be more specific about your problem. It's not clear what are the issues you're facing in the transition. Have you tried to follow to migration guidelines: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio

**Comment by thanhnntq** [comment]
> Also, please be more specific about your problem. It's not clear what are the issues you're facing in the transition. Have you tried to follow to migration guidelines: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio

I have followed the upgrade instructions fully, but unfortunately it still doesn't work. Do you do an example for me with the directory structure as sent. Sincerely thank!

**Comment by mkArtakMSFT** [comment]
We may be able to help if you provide us a sample repro project.
