### ISSUE TITLE
Implement SignCheck in Arcade

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#11359]
Tracking https://github.com/dotnet/arcade/issues/2888

**Comment by Pilchie** [comment]
@JunTaoLuo I didn't see this in the infrastructure project tracking - is this still on your radar?

**Comment by JunTaoLuo** [comment]
Sort of, this is tracking a specific item in https://github.com/aspnet/AspNetCore/issues/7280. I filed a separate tracking issue since this is tracking an external fix.

**Comment by JunTaoLuo** [comment]
Unassigning for now since this is blocked on the external fix. I'm not aware that this has caused any problems so far though.

**Comment by Pilchie** [comment]
@aspnet/build - still on the radar for Preview 9? It's not assigned?

**Comment by dougbu** [comment]
It's unclear whether converting to the Arcade post-build stages have given us (or, for AspNetCore, will give us) this for free. I don't feel we have time to react this week if not.

@Pilchie how 'bout we double-check the status after @wtgodbe and @JunTaoLuo wrap up the stages change -- likely early next week?

**Comment by dougbu** [comment]
Do see signing validation in the Arcade post-build stages. So, this will come for free once we get aspnet/AspNetCore#13040 in. No further action needed.
