### ISSUE TITLE
Reenable CORS tests after removing hanging builds.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#11354]
We made a fix to the CORS tests to not hardcode ports (as that was causing test flakiness). However, the commit I made caused builds to hang.  https://github.com/aspnet/AspNetCore/commit/213f6efd30f59edb864008e1f0235119ed9a45ba
https://github.com/aspnet/AspNetCore/commit/a4bd1308ca32fb735a895c9e834de3bb844c3e66 for the two commits. There is something that is causing jest not to exit (timeouts).

**Comment by ryanbrandenburg** [comment]
There's only one CORS test which references this issue, and the [problem it's blocked on](https://github.com/aspnet/AspNetCore-Internal/issues/1619) was [closed without resolution](https://github.com/aspnet/AspNetCore-Internal/issues/1619#issuecomment-464086351) in February. Given that it's unclear what exactly the work-item is here. @jkotalik and/or @mkArtakMSFT could you clarify what exactly this issue refers to? Is the idea that we should re-enable this test on OSX, even though @pranavkm's previous determination was that this coverage was unimportant? Or am I just not looking at the correct CORS tests?

**Comment by jkotalik** [comment]
Updated the description. Go ahead and assign me, I made a fix and there were issues with it.
