### ISSUE TITLE
Blazor Template Similar to JavaScriptServices

### ISSUE THREAD

**Issue by aherrick** [aspnet/AspNetCore#11366]
I'm looking to convert an Angular/JavaScriptServices App to Blazor.

When I look at the template structure, is it possible to do Server Side Blazor with MVC endpoints? 

My current App is a single App Service with Angular calling into MVC endpoints. All within a single App Service.

What would be the equivalent Blazor setup? I understand "Blazor (ASP.NET Core hosted)" but isn't that just a client side Blazor project with a corresponding web API project?

I want both Blazor and my MVC endpoints that Blazor is hitting in the same project.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @aherrick.
For Server-Side Blazor application, you don't even need to expose APIs. If, of course, you have them, you can simply call into them, as your C# code is going to execute on the server anyway.

**Comment by aherrick** [comment]
The reason I want to expose APIs is so I can keep the structure the same as I can easily move between Client and Server side Blazor if needed.

**Comment by aherrick** [comment]
Anymore thoughts here?

**Comment by mkArtakMSFT** [comment]
Well, you can always expose your APIs through controllers, but all the calls then will need to go through the web, even though you're essentially on the same server. So you'll end up making HttpClient calls all the times - even for Server hosted model. That seems like a waste of resources.

**Comment by aherrick** [comment]
But how do I setup myself to use an API for both a Client or a Server side Blazor then?

**Comment by mkArtakMSFT** [comment]
Here is a sample app which does exactly that: https://github.com/danroth27/BlazorDualMode
Look at how the `IWeatherForecastService` is implemented in server and client.

**Comment by aherrick** [comment]
This is closer to where I want to be... the problem here is it's still two different code paths for client and development.

In development mode, how do you realistically test the HTTP/API/Controller endpoints?

**Comment by mkArtakMSFT** [comment]
Check out the `WebApplicaitonFactory` - that should help: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2

**Comment by aherrick** [comment]
Hey @mkArtakMSFT thanks for the help. What exactly is your solution here? do you have an example with Blazor showing this off? thanks

**Comment by mkArtakMSFT** [comment]
Actually, I take that back. The WebApplicationFactory won't help here. For Blazor specifically, we don't have a good solution at the moment. However, we do have something in development, which we hope will turn into something similar to WebApplicationFactory but for Blazor.
