### ISSUE TITLE
Re-enable SignalR npm functional tests in Arcade.

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#11360]
These tests were disabled in https://github.com/aspnet/AspNetCore/pull/11122 due to test failures. Need to investigate how to re-enable these again.

**Comment by mikaelm12** [comment]
Checked the build logs and the functional tests seem to be running (and passing 😄) now

**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [x] The fix is tests-only. 
* [ ] This is a Docs issue.
* [ ] The fix contains product changes (**check all items below**).
	* [ ] Relevant XML documentation comments for new public APIs are present. - Not needed
	* [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [https://github.com/aspnet/AspNetCore.Docs/pull/12875]
		* [ ] The change requires no docs changes.
	* [ ] Verification has been completed. (**check one item below**)
    	* [ ] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [version]
			* ASP.NET Core Runtime: [version]
			* .NET Core Runtime: [version]
	    * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: aspnet-signalr-3.0.0-preview7.19325.3
