### ISSUE TITLE
Question-How to customize the Identity UI library in .NET Core 3.0 Preview 6?

### ISSUE THREAD

**Issue by SeppPenner** [aspnet/AspNetCore#11364]
Just a small question: How is it possible to customize the `Identity UI` library in the .Net Core 3.0 Preview 6 Blazor template?

I followed @danroth27's introduction on Blazor from https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/ and was wondering how the customization would work?

Maybe there is already some tutorial I have missed?

By the way, great job you all are doing with Blazor ;)

**Comment by blowdart** [comment]
You would do it as you would in any non-blazor project, you [scaffold](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio) it into your project and then make adjustments as you see fit,

**Comment by SeppPenner** [comment]
That was the reference I was searching for. Thanks.
