### ISSUE TITLE
Redirect to different login page on logout , unauthorize etc...

### ISSUE THREAD

**Issue by jfcaldeira** [aspnet/AspNetCore#11363]
I can't figure out how to work with 2 login pages in Asp .Net Core 2.2 RazorPages

I have 2 Areas, each has their own custom pages

{area}/Index (Login page)
{area}/AcessDenied

However with this code this does not work

>          services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
>                 .AddCookie(options =>
>                 {
>                     options.ExpireTimeSpan = TimeSpan.FromDays(1);
>                     options.LoginPath = new PathString("/Index");
>                     options.LogoutPath = new PathString("/Logout");
>                     options.AccessDeniedPath = new PathString("/AccessDenied/");
>                     options.SlidingExpiration = true;
>                 });

I tried this before

```
   services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie("ProductionAuth",options =>
                {                    
                    options.ExpireTimeSpan = TimeSpan.FromDays(1);
                    options.LoginPath = new PathString("/Production/Index");
                    options.LogoutPath = new PathString("/Production/Logout");
                    options.AccessDeniedPath = new PathString("/Production/AccessDenied/");
                    options.SlidingExpiration = true;
                })
               .AddCookie("AdministrationAuth",options =>
                {
                    options.ExpireTimeSpan = TimeSpan.FromDays(1);
                    options.LoginPath = new PathString("/Administration/Index");
                    options.LogoutPath = new PathString("/Administration/Logout");
                    options.AccessDeniedPath = new PathString("/Administration/AccessDenied/");
                    options.SlidingExpiration = true;
                });
```
and it only works for the Default Scheme only which is ProductionAuth.

If I use AdministrationAuth configuring the cookie authentication, it wont detect it nor it will have any claims like it is inexistent.
```
> 
>              await HttpContext.SignInAsync("AdministrationAuth",
>                     new ClaimsPrincipal(userIdentity),
>                     authProperties);

```

Reason i need to login pages separated is because one area has different form controls to input and must access only it's own pages

**Comment by Tratcher** [comment]
When using two cookies you can't rely on the default scheme, you must declare in your pages which scheme to use. You do that by setting the parameter on the Authorize attribute.
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.1#authorize-filter-attribute

**Comment by jfcaldeira** [comment]
This worked. There's only one problem which is having to apply to every page. Is there a way to do this at startup with conventions when authorizing a folder?

**Comment by Tratcher** [comment]
> when authorizing a folder

How are you doing that?

**Comment by jfcaldeira** [comment]
```
            services.AddMvc()
             .AddRazorPagesOptions(options =>
             {
                 options.AllowAreas = true;
                 options.Conventions.AuthorizeAreaFolder("Administration", "/Account");
                 options.Conventions.AuthorizeAreaFolder("Production", "/Account");


             })
```

i tried add another parameter but only asks for a policy and not authentication scheme

**Comment by Tratcher** [comment]
Where did you define your policies? They can specify auth schemes.

**Comment by jfcaldeira** [comment]
I haven't made a policy for this but i am using policies, here is one that i have atm for some database check

>            services.AddAuthorization(options =>
>             {
>                 options.AddPolicy("CheckArranqueActivo", policy =>
>                     policy.Requirements.Add(new CheckArranqueActivoRequirement()));
>             });

**Comment by Tratcher** [comment]
Ah, I mistook that first parameter for a policy. Yes, define a policy for these that specifies the auth scheme.

**Comment by anurse** [comment]
Closing as it sounds like the questions have been answered and there is no actionable work on our end. Let us know if that's not the case!
