### ISSUE TITLE
Blazor Preview6 - Client-side Routing Broken When Not Using Default Router

### ISSUE THREAD

**Issue by sbwalker** [aspnet/AspNetCore#11369]
### Describe the bug
 In ASP.NET Core 3 Preview6 the Blazor client-side routing is broken when you are not using the default router. Oqtane ( https://github.com/oqtane/oqtane.framework ) is a modular Blazor application which does not use the default Blazor router - it uses its own custom router so that it can resolve routes to components dynamically at run-time. The custom router being referenced in app.razor is simply a standard Blazor component and prior to Preview6 it worked fine. However in Preview6 it no longer behaves properly. In the server-side hosting model, every time you click a navigation link from the menu, it displays the message “Attempting to reconnect to the server” and it reloads the entire page ( and never retains any application state ). In the client-side model, when you click a navigation link it displays the initial splash page image for Oqtane and then renders the entire page ( and never retains any application state ).

### To Reproduce
1. Install standard requirements for Blazor Preview6
2. Clone or Download the code from https://github.com/oqtane/oqtane.framework
3. Choose the Debug/Release build configuration to build server-side OR choose the Wasm build configuration to build client-side
4. Run the application and click any link in the left-hand navigation menu

### Expected behavior
The application should not reload the entire page when you click a navigation link. It should load the application state on startup and use client-side routing in the browser.

### Screenshots
Server-side hosting video: https://1drv.ms/u/s!As9HhCjdL7lfhkYv3-obv_m_3mtT?e=zzvbPF
Client-side hosting video: https://1drv.ms/v/s!As9HhCjdL7lfhkUeTCB3A3F7fV-w?e=iQclvF

**Comment by pranavkm** [comment]
@sbwalker you have to explicitly tell Blazor to intercept navigation. Here are the relevant pieces of code in the default Router that you would have to replicate:

* https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Routing/Router.cs#L28

* https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Routing/Router.cs#L141-L151

`OnLocationChanged` also provides a flag that indicates if the navigation was initiated by a user action (clicking a link) versus an API call (`navigateTo`). `Router` uses this to determine what the behavior needs to be if the uri cannot be routed to:

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Routing/Router.cs#L118-L129

**Comment by sbwalker** [comment]
Just to be clear, this was not necessary in versions of Blazor prior to Preview6. Previous iterations only required a custom router to react to the OnLocationChanged event. It now appears that additional logic is required.

**Comment by pranavkm** [comment]
@sbwalker yup, this is new. It's meant to allow scenarios where you're mixing Blazor with regular ASP.NET Core content and don't have a router involved.

**Comment by pranavkm** [comment]
Closing since the issue has been resolved.
