### ISSUE TITLE
Client-side Blazor local time zone is always UTC

### ISSUE THREAD

**Issue by xJonathanLEI** [aspnet/AspNetCore#11367]
### Describe the bug
In client-side Blazor, the local TimeZoneInfo is always set to UTC, rending methods like `.ToLocalTime()` in `DateTime` useless.

### To Reproduce
1. Using this version of ASP.NET Core `3.0.0-preview6-27804-01`
2. Create a client-side Blazor project
3. Run the following code:

        Console.WriteLine(TimeZoneInfo.Local.BaseUtcOffset);

4. The output is always `00:00:00`

### Expected behavior
The output should reflect the machine timezone settings, retrieved from the [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions) api.

### Additional context
.NET Core SDK Version: `3.0.100-preview6-012264`

**Comment by xJonathanLEI** [comment]
Is this a Mono issue? I'm not sure. Submitting anyways.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#15260
