### ISSUE TITLE
UseExceptionHandler doesn't work in asp core preview 6

### ISSUE THREAD

**Issue by prince272** [aspnet/AspNetCore#11362]
UseExceptionHandler doesn't show the Error page.

**Comment by davidfowl** [comment]
@prince272 Can you fill out the issue template? We need more informtation before investigating the problem.

**Comment by prince272** [comment]
this method is the problem. app.UseExceptionHandler("/Home/Error");
It don't call the view (Error.cshtml).

ok. To produce the same problem simply create a new asp core preview 3 from the templates with authentication checked. Just throw an Exception like

        public IActionResult TestError()
        {
            throw new NotImplementedException();
        }

**Comment by prince272** [comment]
Hello again,

I think i have found a solution though i don't know why the template code doesn't work. Take a look.

just configure these in your Setup.Configure.

                app.UseWhen(context => !context.Request.Path.StartsWithSegments("/api"),
                    a =>
                    {
                        a.UseExceptionHandler("/home/error");
                        a.UseStatusCodePagesWithReExecute("/home/error", "?statusCode={0}");
                    }
                );

                app.UseWhen(context => context.Request.Path.StartsWithSegments("/api"),
                    a =>
                    {
                        a.UseExceptionHandler("/api/home/error");
                        a.UseStatusCodePagesWithReExecute("/api/home/error", "?statusCode={0}");
                    }
                );


now add this to your home controller.

        [Route("api/[controller]/[action]/{statusCode?}")]
        [Route("[controller]/[action]/{statusCode?}")]

        public IActionResult Error(int? statusCode)
        {
            bool isApiRequest = Request.Path.StartsWithSegments("/api");

            if (isApiRequest)
            {
                if (statusCode == (int)HttpStatusCode.NotFound)
                    return Json(new
                    {
                        errorMessage = "not found.",
                        errorStatusCode = statusCode
                    });

                return Json(new
                {
                    errorMessage = "internal server error.",
                    errorStatusCode = statusCode
                });
            }
            else
            {
                if (statusCode == (int)HttpStatusCode.NotFound)
                    return View("Error404");

                return View();
            }
        }

**Comment by davidfowl** [comment]
Looks like it might be related to this https://github.com/aspnet/AspNetCore/issues/11233

**Comment by mkArtakMSFT** [comment]
Closing this as a dupe, and we'll validate this as part of the other fix.
