### ISSUE TITLE
[Blazor] @name attribute ?

### ISSUE THREAD

**Issue by xclud** [aspnet/AspNetCore#11370]
### Is your feature request related to a problem? Please describe.
Currently we can access a component like this:

```
<SomeComponent @ref="@myComp" />

@code {
    SomeComponent myComp;
}
```

### Describe the solution you'd like
My suggestion is to use `@name` attribute. Just like id/name attributes used by Javascript/DOM (or even WinForms and WPF). So it will be:

`<SomeComponent @name="myComp" />`

And there is be no need to define `myComp` in `@code` section.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @xclud.
This is not something we plan to change.
