### ISSUE TITLE
Client-Side Blazor OrderByDescending

### ISSUE THREAD

**Issue by matheusjulio96** [aspnet/AspNetCore#11371]
The bug: Execute an OrderByDescending query throw the error 'Unhandled exception rendering component: System.NullReferenceException: Object reference not set to an instance of an object.'

1. Using this version of ASP.NET Core 3.0.0-preview6.19307.2 with Client-Side project
2. Run this code:
```
@code{
    class Pet
    {
        public string Name { get; set; }
        public int Age { get; set; }
    }

    protected override void OnInit()
    {
        Pet[] pets = { new Pet { Name="Barley", Age=8 },
                       new Pet { Name="Boots", Age=4 },
                       new Pet { Name="Whiskers", Age=1 } };

        var query = pets.AsQueryable().OrderByDescending(pet => pet.Age);

        foreach (Pet pet in query)
            Console.WriteLine("{0} - {1}", pet.Name, pet.Age);
    }
}
```
3. See error Screenshot
![image](https://user-images.githubusercontent.com/29152563/59771996-55d57600-9281-11e9-832c-100eba869c03.png)

Expected behavior: Execute the query and print the values.

Ps: OrderBy query works fine.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#15259
