### ISSUE TITLE
I am stuck with the DI_BasePageModel because I already used another base class for my dropdownlist and I cant use more than 1 base class

### ISSUE THREAD

**Issue by code2expert** [aspnet/AspNetCore#11388]
I am creating a web application with ASP.NET Razor pages. I am modelling the security aspect around this project but I'm stuck with the CreateModel page of the Contact Model. I had used a base class to populate a dropdown list which I am using in the CreateModel. 

Can you describe a way to use more than one base class in the create model? I am at intermediate skill level in C# and I have read that multiple base classes are not allowed in C# (also in Java). 

Please help.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @code2expert.
This is a C# limitation. You can't have multiple base classes. Consider re-structuring your code.
