### ISSUE TITLE
Compiler raises null reference warning for property injected using [Inject] attribute

### ISSUE THREAD

**Issue by tn-5** [aspnet/AspNetCore#11395]
When using nullable reference types and injecting a service using the `[Inject]` attribute the compiler does not recognise the property as non-nullable.

When using constructor based dependency injection the compiler does not give the warning.

*Reproduce*
Enable null reference types, use `[Inject]` attribute to inject a service into a component.

As an aside, it would be great if the default Blazor templates could be converted to have null reference types enabled.

I'm not sure if this can be fixed in the aspnet code or if this issue should rather be moved to another project.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tn-5.
For the changes in templaets, we're tracking that work as part of https://github.com/aspnet/AspNetCore/issues/10921.

**Comment by mkArtakMSFT** [comment]
Hi @cartermp. What should our guidance be here regarding nullability checks for traditional properties?

**Comment by cartermp** [comment]
I think this is a post-3.0 kind of thing. We need to expose certain APIs in CoreFX to allow ASP.NET and EF to have a sane way to represent nullability.

**Comment by rynowak** [comment]
This is not a question, this is a bug in the compiler - using an NNRT with `@inject` will always result in a warning right now.

The fix is to generate the property like so:
```C#
[Inject] IFoo Foo { get; set; } = default!;
```

This has to be contingent on whether nullability context is enabled at the project level, which we already flow into the compiler.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen is this done already? If so, please close this one.

**Comment by NTaylorMullen** [comment]
Yup, I fixed this in preview9.
