### ISSUE TITLE
Blazor: Input-Binding Syntax: bind vs @bind

### ISSUE THREAD

**Issue by Z3roCoder** [aspnet/AspNetCore#11392]
### Describe the bug
It is not a bug, but much rather a question.
Looking through all online available resources, the Binding-Syntax seems to have changed.
I need to do the following to get my Input-Field to bind to my Variable:
```<input type="number" @bind="currentCount" />```
Although everywhere else on the Internet, it is documented like this:
```<input type="number" bind="@currentCount" />```

Did this behavior change in any of the last versions? I haven't found anything that might indicate that.
### Versions 
I am currently using all the latest versions of ASP.NET Core and Blazor (All downloaded freshly today)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Z3roCoder.
This has changed in `Preview 6` release from `bind` to `@bind`. Here is our official announcement: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/
