### ISSUE TITLE
AuthenticationProperties not accessible via SignInManager

### ISSUE THREAD

**Issue by bchavez** [aspnet/AspNetCore#11405]
Hello,

The following problem has been bugging me for a long time ever since ASP.NET Identity has been released.

## Is your feature request related to a problem? Please describe.
I am trying to gain access to the `AuthenticationProperties` object that I get back from calling [`SignInManager.ConfigureExternalAuthenticationProperties(...)`][1] to set metadata about an external login. Currently, when an `ExternalLogin` is invoked on the sign-in page, the `SignInManager` offers the following API:

```csharp
public async Task<IActionResult> ExternalLogin(string provider, string returnUrl = null){
   var props = this.SignInManager.ConfigureExternalAuthenticationProperties(provider, returnUrl);
   props.Items[MyCustomThing] = "SomeValue"; //CUSTOM META DATA HERE
   return this.Challenge(props, provider);
}
```
[1]:https://github.com/aspnet/AspNetCore/blob/a4bd1308ca32fb735a895c9e834de3bb844c3e66/src/Identity/Core/src/SignInManager.cs#L715-L724

So, [`SignInManager.ConfigureExternalAuthenticationProperties(...)`][1] returns `AuthenticationProperties` that I use to set `MyCustomThing`. Then, I hand off the challenge to the external login middleware providers.

On the way back, after the user successfuly authenticates with the third-party social login, `ExternalLoginCallback` is invoked.

```csharp
public async Task<IActionResult> ExternalLoginCallback(string remoteError = null, string returnUrl = null)
{
   var info = await this.SignInManager.GetExternalLoginInfoAsync();
   if( info is null )
   {
      return this.BadRequest("Sign in info not found.");
   }
   
   // How to get MyCustomThing from `info` variable of type ExternalLoginInfo??
   // What I would like to do is:
   var props = info.AuthenticationProperties; //???
   var someValue = props.Items[MyCustomThing]; //???
   //Do something intresting with MyCustomThing:someValue, then finally:
   
   await this.SignInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false);
}
```

Currently, there is nothing in `SignInManager` that exposes the `AuthenticationProperties` that were exposed by [`SignInManager.ConfigureExternalAuthenticationProperties(...)`][1] back in the `ExternalLogin` method.

[2]:https://github.com/aspnet/AspNetCore/blob/a4bd1308ca32fb735a895c9e834de3bb844c3e66/src/Identity/Core/src/SignInManager.cs#L638-L672

## Describe the solution you'd like
I would like to call [`SignInManager.GetExternalLoginInfoAsync()`][2] one time and have access to the `AuthenticationProperties` that appear near the `ExternalLoginInfo` object that is returned here:

https://github.com/aspnet/AspNetCore/blob/a4bd1308ca32fb735a895c9e834de3bb844c3e66/src/Identity/Core/src/SignInManager.cs#L669-L672

Once I have access to `AuthenticationProperties` on `ExternalLoginInfo` I can access `MyCustomThing` and do something interesting.

[4]:https://github.com/aspnet/AspNetCore/blob/a4bd1308ca32fb735a895c9e834de3bb844c3e66/src/Identity/Core/src/SignInManager.cs#L640

## Describe alternatives you've considered
Currently, the only way I'm able to get back `AuthenticationProperties` from `SignInManager` that I originally set in `ExternalLogin` is to effectively call [`AuthenticateAsync(IdentityConstants.ExternalScheme)`][4] twice:
* Once, indirectly by calling [`SignInManager.GetExternalLoginInfoAsync()`][4]
* Twice, manually/independently to get the `auth` result from the underlying middleware.

In other words, my current hack is as follows:
```csharp
/// <summary>
/// Hack to get around not having access to AuthenticationProperties
/// exposed by SignInManager.
/// </summary>
public static async Task<ExtenralLoginInfo2> GetExternalLoginInfoAsync2(
   this SignInManager signInManager,
   string expectedXsrf = null)
{
   //First call to AuthenticateAsync.
   var info = await signInManager.GetExternalLoginInfoAsync(expectedXsrf);
   if( info is null ) return null;

   //Second call to AuthenticateAsync.
   var auth = await signInManager.Context.AuthenticateAsync(IdentityConstants.ExternalScheme);
   return new ExtenralLoginInfo2(info, auth.Properties);
}


public class ExtenralLoginInfo2
{
   public ExtenralLoginInfo2(
      ExternalLoginInfo externalLoginInfo, 
      AuthenticationProperties authenticationProperties)
   {
      this.ExternalLoginInfo = externalLoginInfo;
      this.AuthenticationProperties = authenticationProperties;
   }

   public ExternalLoginInfo ExternalLoginInfo { get; }
   public AuthenticationProperties AuthenticationProperties { get; }
}
```

### Additional context
I'd be happy to send a PR to resolve this issue to make the API for `SignInManager` more symmetrical.

A proper fix would probably include adding an `AuthenticationProperties` property on `ExternalLoginInfo` class here:

https://github.com/aspnet/AspNetCore/blob/a4bd1308ca32fb735a895c9e834de3bb844c3e66/src/Identity/Core/src/ExternalLoginInfo.cs#L13-L38

And storing a reference to `auth.Properties` in the newly created property here:

https://github.com/aspnet/AspNetCore/blob/a4bd1308ca32fb735a895c9e834de3bb844c3e66/src/Identity/Core/src/SignInManager.cs#L669-L672

//cc @HaoK 

Thanks,
Brian Chavez

:hourglass_flowing_sand: :mag: ***["But I still haven't found what I'm for..."](https://www.youtube.com/watch?v=wdCJRybAtso)***

**Comment by HaoK** [comment]
Feel free to submit a PR, I think its perfectly reasonable to add the AuthenticationProperties to ExternalLoginInfo as you suggest

**Comment by bchavez** [comment]
Fantastic, thank you. I'll have a PR ready for you soon.

**Comment by HaoK** [comment]
Also, the workaround of calling Authenticate on the external cookie directly is not that bad, that work is cached so a second call should be fast

**Comment by HaoK** [comment]
Thanks for reporting and taking care of this again @bchavez !

**Comment by bchavez** [comment]
No problem. Thank you @HaoK for your insights, guidance, and helping carry this PR over the finishing line. I really appreciate your work. Thanks so much!
