### ISSUE TITLE
AuthorizeView Roles tag does not work wiithin default ASP.NET Core Web for 3.0preview6

### ISSUE THREAD

**Issue by TomChalkerApption** [aspnet/AspNetCore#11419]
### Describe the bug
The following markup does not render inside AuthorizeView Roles="admin tag set: 
<AuthorizeView Roles="admin, superuser">
    [Admin]
</AuthorizeView>

&lt;AuthorizeView Roles="admin, superuser"&gt;
    [Admin]
&lt;/AuthorizeView&gt;

when authenticating with AAD user with the roles:
- Application administrator
- Authentication administrator
- Global administrator 
- User administrator
 and is a member of a custom group called 'admin'

### To Reproduce

1. Create a new project in the Visual Studio2019 Preview using default ASP.NET Core Web template
2. Enable Authentication for 'School or Work' 
3. Deploy to Azure
4. Enable AAD Authentication 
   (anonymous access when request is not authenticated,  
   Configured AAD access when request is authenticated)
5. Visit application.
6. All markup displays except that in AuthorizeView tag set.

### Expected behavior
The HTML text '[Admin]' should display next to the welcome message in LoginDisplay.razor

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @TomChalkerApption.
Please provide a pre-configured sample project for us to repro this, so we can investigate.
@SteveSandersonMS can you please look into this? Thanks!

**Comment by blowdart** [comment]
Did you configure the application in AAD to have [roles flow?](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles)

**Comment by TomChalkerApption** [comment]
Hello Barry:

I did add a custom role to the appRoles section of the manifest and confirmed that it was correctly assigned to a user.
However, I note that a http://schemas.microsoft.com/ws/2008/06/identity/claims/role claim does not show up in the ClaimsPrincipal context variable as suggested by the reference: https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#roles-using-an-application-role-manager

Is there yet another configuration step necessary?

Thanks for your quick response.

Tom Chalker
Senior Developer
Apption
1600 Scott Str, Suite 400, Ottawa
613 725 6268 Ext 612

**Comment by TomChalkerApption** [comment]
Hello Barry:

Update on the custom role:

The claims token for my custom role has suddenly started to appear in the ClaimsPrincipal.
There appears to be some sort of propagation delay to the change in the Axure Manifest that I made  yesterday afternoon.

The AuthorizeView roles tag is now working as expected.

I will close the bug.

Thanks again,

Tom Chalker
Senior Developer
Apption
1600 Scott Str, Suite 400, Ottawa
613 725 6268 Ext 612

From: Tom Chalker
Sent: June 21, 2019 9:13 AM
To: aspnet/AspNetCore; aspnet/AspNetCore
Cc: Mention
Subject: RE: [aspnet/AspNetCore] AuthorizeView Roles tag does not workwiithindefault ASP.NET Core Web for 3.0preview6 (#11419)

Hello Barry:

I did add a custom role to the appRoles section of the manifest and confirmed that it was correctly assigned to a user.
However, I note that a http://schemas.microsoft.com/ws/2008/06/identity/claims/role claim does not show up in the ClaimsPrincipal context variable as suggested by the reference: https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#roles-using-an-application-role-manager

Is there yet another configuration step necessary?

Thanks for your quick response.

Tom Chalker
Senior Developer
Apption
1600 Scott Str, Suite 400, Ottawa
613 725 6268 Ext 612

**Comment by TomChalkerApption** [comment]
**Solution:**

It is necessary to follow the instructions described in [roles-using-an-application-role-manager](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#roles-using-an-application-role-manager) to add a custom role and use its DisplayName in the AuthorizeView tag.
Note that changes to Azure manifest of an application may take considerable time to take effect.
