### ISSUE TITLE
Static assets in Razor libraries do not seem to work in Blazor server-side applications

### ISSUE THREAD

**Issue by akorchev** [aspnet/AspNetCore#11410]
### Describe the bug

The approach described [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&tabs=visual-studio#consume-content-from-a-referenced-razor-class-library) and [here](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/) does not seem to work in server-side Blazor applications.

### To Reproduce
1. `dotnet new blazorserverside -o BlazorWebApp1` (a change from the preview 6 announcement blog post)
2. `dotnet new razorclasslib -o RazorLib1` 
3. `dotnet add BlazorWebApp1 reference RazorLib1`
4. Add a CSS file in `RazorLib1/wwwroot/` e.g. `styles.css`
5. Reference that css style in BlazorWebApp1 by appending `<link rel="stylesheet" href="_content/RazorLib1/styles.css">` to _Host.cshtml
6. `dotnet run` 
7. The _content/RazorLib1/styles.css HTTP requests has 404 status.

My test application is available [here](https://github.com/akorchev/blazor-static-assets).

### Expected behavior

I would expect for this to work as it seems to should have been a supported scenario.

### Screenshots
<img width="652" alt="image" src="https://user-images.githubusercontent.com/454726/59823872-34839100-9338-11e9-80e9-26e16373a1c7.png">

### Additional context

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview6-012264/

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf
```

**Comment by huanbd** [comment]
I think, I have the same error
```
.NET Core SDK version: 3.0.100-preview6-012264
OS Name: Window 10
OS Version: 1903
```
I have a project Blazor client. It is configured as a page in a project Asp.net Core MVC
```
app.Map("/cms", appBuilder =>
{
     app.UseClientSideBlazorFiles<Admin.Startup>();
     app.UseEndpoints(endpoints =>
     {
           endpoints.MapFallbackToClientSideBlazor<Admin.Startup>("index.html");
     });
 });
```
In index.html file
`<base href="/cms/" />`

/cms/css/site.css  not found
...

It run without error in SDK version preview5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @akorchev.
@javiercn can you please look into this? Thanks!

**Comment by javiercn** [comment]
@huanbd Your issue is likely unrelated.

If you have a base path then you need to reference files relative to the root (starting with '/' or call `app.UseStaticFiles()` within the `app.Map("/cms", ...)` call before app.UseClientSideBlazorFiles

**Comment by huanbd** [comment]
Hi @javiercn , I've used `app.UseStaticFiles()` before that, this is my `Configure `method in `Startup.cs`

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseBlazorDebugging();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
    }
    app.UseStaticFiles();
    app.UseRouting();
    app.UseAuthentication();
    app.UseAuthorization();
    app.Map("/cms", appBuilder =>
    {
        app.UseClientSideBlazorFiles<NotifySignal.Admin.Startup>();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapFallbackToClientSideBlazor<NotifySignal.Admin.Startup>("index.html");
        });
    });
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=Home}/{action=Index}/{id?}");
    });
}
```
May I miss something about api change?

**Comment by javiercn** [comment]
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseBlazorDebugging();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
    }
    app.UseStaticFiles();
    app.UseRouting();
    app.UseAuthentication();
    app.UseAuthorization();
    app.Map("/cms", appBuilder =>
    {
        // You either add this call or reference the file as /css/site.css as the physical path on disk for the file I imagine is /css/site.css
        app.UseStaticFiles();
        app.UseClientSideBlazorFiles<Admin.Startup>();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapFallbackToClientSideBlazor<Admin.Startup>("index.html");
        });
    });
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=Home}/{action=Index}/{id?}");
    });
}
```

**Comment by huanbd** [comment]
I did that but still error, and note that Client side Blazor is a project, that's outside of project MVC, and static files are in project client side Blazor
and in version SDK preview 5 It run without error

![Capture](https://user-images.githubusercontent.com/5028941/60120637-82bae900-97ab-11e9-9ac8-f5f391b4f37e.PNG)

**Comment by javiercn** [comment]
@huanbd Your issue is unrelated to this issue. I believe it might have been related to an issue we fixed a couple of days ago. I would suggest you try out with the next preview release or file a separate issue and include a repro project.

**Comment by javiercn** [comment]
@akorchev I'm not able to repro the issue with your project and the latest sdk. Could you provide what sdk you are using? We have automation covering the scenario you describe, so I'm inclined to think that the razor sdk in use might be old.

Could you please try with the latest sdk from https://github.com/dotnet/core-sdk and see if you still have this issue?

Closing for now as no-repro

**Comment by akorchev** [comment]
@javiercn I think I am using the latest SDK:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview6-012264/

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf
```
