### ISSUE TITLE
Blazor: Unable to import .NET dll: Fatal error in IL Linker

### ISSUE THREAD

**Issue by Z3roCoder** [aspnet/AspNetCore#11439]
### Describe the bug
Deciding to try out what Client-Side Blazor with WASM is capable of, I tried to include one of our companies standalone DLLs and run some functions from it. However, instead I have been getting an IL Linker error at build time and could not get it to work.

```
1>Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.WasmRuntime (All).  Duplicate uses (All)
1>Fatal error in IL Linker
1>
1>Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve System.CodeDom.Compiler.CodeDomProvider
1>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkSecurityAttribute(SecurityAttribute sa)
1>   at Mono.Linker.Steps.MarkStep.MarkSecurityDeclaration(SecurityDeclaration sd)
1>   at Mono.Linker.Steps.MarkStep.MarkSecurityDeclarations(ISecurityDeclarationProvider provider)
1>   at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.MarkStep.Initialize()
1>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
```

The Target-DLL was built for .NET 4.5 and only references System, System.Data, System.Xml and Microsoft.VisualBasic.

Assuming that the WASM-Example loads a full Mono-Environment (as I understand it), it should be able to work with any DLL - But here, it seems that the Problem is the Linker.

Sadly, i am not able to provide the DLL in question, but maybe anyone has an Idea as to what is going on here.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Z3roCoder.
Can you try disabling the linker and see whether that works?
Simply set the `BlazorLinkOnBuild` property to `false` as shown below:
```xml
<PropertyGroup>
  <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
</PropertyGroup>
```

Please note that Blazor WebAssembly apps run within the browser security sandbox so you won't be able to do operations which require elevated privileges (access files on disk, connect to database, ...).

**Comment by Z3roCoder** [comment]
Hello, and thanks for you reply.
I've tried this by now and am now facing another issue.

My library uses CodeDom, which seems to not be supported by .NET Core - I think that might have been the issue in the first place as well.

Is there any way to get this to work, or do I need to rewrite the library to discard CodeDom in favor of, say, Roslyn?

**Comment by mkArtakMSFT** [comment]
@Z3roCoder have you tried to add a reference to the `System.CodeDom` NuGet package?

**Comment by Z3roCoder** [comment]
Hello,
yes, I have added it and am still receiving the same Error as before

**Comment by Z3roCoder** [comment]
In the end, I - for now - decided to drop the CodeDom and removed the parts that referenced it in my Library, and it seems to be working now. I don't know if that is a general issue, but if not, you can close the Ticket - If it is, I am happy to see it being resolved :)

**Comment by mkArtakMSFT** [comment]
Glad you could work around this, @Z3roCoder.
Given this is not an issue we have control of, we're moving it to the Mono folks.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#15404
