### ISSUE TITLE
Inconsistent IHostedService ordering between WebHost and Host

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#11437]
In WebHost IHostedServices run after IServer. We've had a lot of complaints about that and we're [considering](https://github.com/aspnet/AspNetCore/pull/11008#discussion_r295730057) reversing that in 3.0 to be more consistent with generic Host where they run in registration order.

In generic Host IServer is part of an IHostedService GenericWebHostService and gets registered before any IHostedServices from Startup, the user doesn't get to control that. They can only control the ordering of services registered directly with the Host in Program. 

Proposal: delay registering GenericWebHostService until after the app is done registering.

https://github.com/aspnet/AspNetCore/blob/56ffc6b58210292a18f548bf4eddff193f73a4d6/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs#L78
https://github.com/aspnet/AspNetCore/blob/56ffc6b58210292a18f548bf4eddff193f73a4d6/src/Hosting/Hosting/src/GenericHostWebHostBuilderExtensions.cs#L11-L13

@davidfowl

**Comment by davidfowl** [comment]
Sounds good to me. So this only affects things in Startup? That sounds like a good change.

**Comment by Tratcher** [comment]
> So this only affects things in Startup?

Primarily. It also affects calls to IWebHostBuilder.ConfigureServices in the call to the ConfigureWebHost lambda.

**Comment by davidfowl** [comment]
Sounds good

**Comment by davidfowl** [comment]
When do we want to do this change? Preview8 or 7? 

cc @anurse

**Comment by anurse** [comment]
If it's simple (looks like it would be) I'd prefer to cram this in to preview7. @Tratcher, we can sync today on prioritization if necessary.
