### ISSUE TITLE
Blazor template files(.razor) contains inconsistent UTF-8 BOM

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#11435]
From https://github.com/aspnet/AspNetCore/issues/11225#issuecomment-504253296,

I created a new project in command-line with `dotnet new blazorserverside` and inspected each of the `.razor` file for BOM. Here is what I found,

Contains BOM:
- MyApp/Pages/_Imports.razor
- MyApp/Pages/Index.razor
- MyApp/Shared/MainLayout.razor
- MyApp/App.razor

Does not contain BOM:
- MyApp/_Imports.razor
- MyApp/Pages/_Host.cshtml
- MyApp/Pages/Counter.razor
- MyApp/Pages/FetchData.razor
- MyApp/Shared/NavMenu.razor

On top of this,
- Creating a `.razor` file from `Razor Component` item template creates a file with no BOM
- Creating a `.razor` file from `Razor View` or `Class` item template creates a file with BOM

I am not sure where the fix for this goes in to but we should make sure all our files are consistent. We should also make sure all of our other templates are consistent as well.

@danroth27 @ryanbrandenburg @mkArtakMSFT

**Comment by xinyanmsft** [comment]
this is the cause of this bug https://github.com/Azure/dev-spaces/issues/118, which breaks Docker tools and DevSpaces scenarios. The proper way is to use UTF8 instead.

**Comment by Andrzej-W** [comment]
What do you think about adding .editorconfig file? https://github.com/aspnet/AspNetCore/issues/11225#issuecomment-504707787

**Comment by xinyanmsft** [comment]
do you mean generate a .editorconfig file when an item template is invoked? personally I dislike have such files laying around in sub-folders. And from what I read one of the main goal of .editorconfig is to have consistency among various tools / IDEs / team members. Using it here seems a little strange.

**Comment by Andrzej-W** [comment]
@xinyanmsft I was thinking about `.editorconfig` file in the main solution folder. This file should be created only when you create a new solution. Then every time you create or edit any file in any subdirectory in any editor/IDE with support for `.editorconfig` you can be sure that you have consistency in encoding, tab stops, etc.

**Comment by xinyanmsft** [comment]
I'd be Okay with .editorconfig file in the main solution folder.
