### ISSUE TITLE
How to change the view auto generator file location,when use AreaViewLocationFormats to change default options

### ISSUE THREAD

**Issue by HMoeGuo** [aspnet/AspNetCore#11436]
How to change the view auto generator file location,
when use AreaViewLocationFormats to change default options

When i Add

`services.AddMvc().AddRazorOptions(Options =>
            {
                Options.AreaViewLocationFormats.Clear();
                Options.AreaViewLocationFormats.Insert(0, "/views/{2}/{1}/{0}" + RazorViewEngine.ViewExtension);
                Options.AreaViewLocationFormats.Insert(0, "/views/{2}/{0}" + RazorViewEngine.ViewExtension);
                Options.AreaViewLocationFormats.Insert(0, "/views/Shared/{0}" + RazorViewEngine.ViewExtension);
                Options.AreaPageViewLocationFormats.Insert(0, "/views/{2}/{1}/{0}" + RazorViewEngine.ViewExtension);
                Options.AreaPageViewLocationFormats.Insert(0, "/views/{2}/{0}" + RazorViewEngine.ViewExtension);
                Options.AreaPageViewLocationFormats.Insert(0, "/views/Shared/{0}" + RazorViewEngine.ViewExtension);
            });`

the view file default location change,  can find the view file.

From:`/View/Dashboard/index.cshtml`
To:`/View/ManagePage/Dashboard/index.cshtml`

but when i use Visual Stdion In Controllers Class Action Function 'Ctrl+M and Ctrl+G' to Jump View File Windows Fail,
It's still Find the old location like 
`/View/Dashboard/index.cshtml` not `/View/ManagePage/Dashboard/index.cshtml`

So What i need do to make the visual stdio to find the proper view file.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @HMoeGuo.
This is a tooling issue (VS), but it most probably won't change, as tooling has no knowledge of the runtime configuration.
