### ISSUE TITLE
Hosting Blazor (client side) in IIS under Core 3 Preview 6 doesn't work

### ISSUE THREAD

**Issue by sdmaclea** [aspnet/AspNetCore#11449]
Manually transferred from dotnet/coreclr#25289

@joelw187 said
Hosting Blazor apps in IIS doesn't seem to work under Preview 6. I always get the message "This localhost page can’t be found" (Chrome). The app runs fine in Visual Studio 2019 Preview (16.2.0 Preview 2.0). It also works if I run the server executable from the command line (i.e., WebApplication1.Server.exe) and then navigate the browser to http://localhost:5000. But when I publish the code to an IIS website I get the error. I'm thinking it has something to do with the new MapFallbackToClientSideBlazor call in Startup.Configure (but that's just a guess). Wondering if anyone else is having the same problem OR if anyone else has successfully hosted a Preview 6 Blazor app in IIS (and, yes, I installed the Preview 6 Runtime & Hosting Bundle).

@jkotalik said
Also @JoelW187 can you give use either a repro or a sample application that is seeing this behavior?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JoelW187.
We're tracking this issue as part of https://github.com/aspnet/AspNetCore/issues/11185
