### ISSUE TITLE
[Blazor][Tooling] Incorrect formatting upon completion on code blocks

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#11442]
When adding an override for a method inside a code block, formatting gets messed up upon completion.

![DD0GLXcQok](https://user-images.githubusercontent.com/6995051/59915171-d8b91680-93d0-11e9-93d9-15db24b19088.gif)

@NTaylorMullen @ajaybhargavb

**Comment by campersau** [comment]
Also when not specifying `protected` it isn't added automatically. Only happens at the top of `@code` blocks for me.

**Comment by NTaylorMullen** [comment]
Yup 😄. Roslyn does some funky behaviors when formatting inside of `@code` (they special case `@functions`); however, we're tracking this issue here: https://github.com/aspnet/AspNetCore/issues/10942
