### ISSUE TITLE
Blazor Router interface is very inflexible

### ISSUE THREAD

**Issue by CornedBee** [aspnet/AspNetCore#11446]
Blazor's `Router` component has one discovery mode for eligible pages: take an assembly and search it, and all its referenced assemblies, for types implementing `IComponent`.

If that is not the way I want to discover types (e.g. maybe I want to grab them from service registrations, or filter them somehow in order to make some pages only available if certain configuration values are set), there's pretty much nothing I can do except copy a huge number of internal types out of the ASP.Net source to reimplement the class. (Also, I ran afoul of a loosely related bug doing that.)

Type discovery should be an extension point. Maybe have a `RouterBase` type that contains everything from router except the `AppAssembly` attribute, and have a virtual method wrapped around the `ComponentResolver.ResolveComponent` call from `SetParametersAsync`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @CornedBee.
@SteveSandersonMS what is the extensibility model for component router?

**Comment by SteveSandersonMS** [comment]
The extensibility model is either subclassing the router, or creating a parallel alternative. 

We will be open to changing the set of virtual methods on the router in the future if it helps to enable more scenarios.

**Comment by CornedBee** [comment]
The problem with subclassing `Router` is that it leaves the potentially-unused `AppAssembly` parameter around. I would recommend instead splitting out a `RouterBase` like this:

```
    public abstract class RouterBase : IComponent, IHandleAfterRender, IDisposable
    {
        static readonly char[] _queryOrHashStartChar = new[] { '?', '#' };

        RenderHandle _renderHandle;
        string _baseUri;
        string _locationAbsolute;
        bool _navigationInterceptionEnabled;

        [Inject] private IUriHelper UriHelper { get; set; }

        [Inject] private INavigationInterception NavigationInterception { get; set; }

        [Inject] private IComponentContext ComponentContext { get; set; }

// Remove AppAssembly here

        /// <summary>
        /// Gets or sets the type of the component that should be used as a fallback when no match is found for the requested route.
        /// </summary>
        [Parameter] public RenderFragment NotFoundContent { get; private set; }

        /// <summary>
        /// The content that will be displayed if the user is not authorized.
        /// </summary>
        [Parameter] public RenderFragment<AuthenticationState> NotAuthorizedContent { get; private set; }

        /// <summary>
        /// The content that will be displayed while asynchronous authorization is in progress.
        /// </summary>
        [Parameter] public RenderFragment AuthorizingContent { get; private set; }

        private RouteTable Routes { get; set; }

        /// <inheritdoc />
        public void Configure(RenderHandle renderHandle)
        {
            _renderHandle = renderHandle;
            _baseUri = UriHelper.GetBaseUri();
            _locationAbsolute = UriHelper.GetAbsoluteUri();
            UriHelper.OnLocationChanged += OnLocationChanged;
        }

// Adjust this method to call the extension point

        /// <inheritdoc />
        public async Task SetParametersAsync(ParameterCollection parameters)
        {
            parameters.SetParameterProperties(this);
            var types = await CollectTypes();
            Routes = RouteTable.Create(types);
            Refresh(isNavigationIntercepted: false);
        }

// Add this extension point to collect the pages to route over
        protected abstract Task<IEnumerable<Type>> CollectTypes();

// The rest of the file is basically the old Router.
```

And `Router just becomes`

```
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Microsoft.AspNetCore.Components.Routing
{
    /// <summary>
    /// A component that displays whichever other component corresponds to the
    /// current navigation location.
    /// </summary>
    public class Router : RouterBase
    {
        /// <summary>
        /// Gets or sets the assembly that should be searched, along with its referenced
        /// assemblies, for components matching the URI.
        /// </summary>
        [Parameter] public Assembly AppAssembly { get; private set; }

        protected override Task<IEnumerable<Type>> CollectTypes()
        {
            var types = ComponentResolver.ResolveComponents(AppAssembly);
            return Task.FromResult(types);
        }
    }
}
```

**Comment by ApocDev** [comment]
This is probably the best route to take to enable better routing, especially when assemblies don't have a direct dependency. (See: Assembly.Load())

This would also allow us to more easily split and nest routers via some cascading values.

**Comment by sbwalker** [comment]
If you are interested in seeing a parallel alternative in action, please see https://github.com/oqtane/oqtane.framework - it has a custom router which does not rely on route table, route template, etc... Obviously this approach is not appropriate for all scenarios but it does provide a working example.

**Comment by limefrogyank** [comment]
You can even wrap the current `Router` with your own class and capture the same events (`document.onclick` & `window.onpopstate`) do your own thing by calling `stopImmediatePropagation` or let it through to let the default router handle parsing for you.  That's what I've done.  The newest `Router` (preview9) is pretty good.
