### ISSUE TITLE
@inject Keyword

### ISSUE THREAD

**Issue by nolisj** [aspnet/AspNetCore#11447]
(sorry. i thought the template is not editable initially). please see actual concern below.

**Comment by nolisj** [comment]
Hi! The `@inject `keyword in Blazor can get really repetitive when you start to have a lot of items to inject. Example (from the BlazingPizza sample project):

```
@inject HttpClient HttpClient
@inject IUriHelper UriHelper
@inject OrderState OrderState
```

The more you want to use it, the more this can get really unwieldy. Also, it is not very clear to a new user (though one can deduce) that you are actually injecting a property.

I was thinking if it can be done this way:

```
@properties {
    inject {
        HttpClient HttpClient;
        IUriHelper UriHelper;
        OrderState OrderState;
    }
}

```
This has the following added benefits:
1. It is clear that you are actually creating a property.  
2. This also forces you to have the same mental model as when you are looking at the `@functions` keyword (which refers to, well, functions or methods in the class). This parallelism, especially in terms of structure, makes you think easily what the purpose of each ones are. This becomes even more apparent when they are placed close to each other (which will happen when you're actually coding)

```
@properties {
    inject {
        HttpClient HttpClient;
        IUriHelper UriHelper;
        OrderState OrderState;
    }
}

//UI code here

@functions {
    async Task PlaceOrder() { }
    protected override async Task OnInitAsync() {}
}

```
3. It looks cleaner and less repetitive.

For your consideration.

Noli San Jose

**Comment by nolisj** [comment]
As I work on this more and more, I'm starting to look at other areas for consistency.

Instead of:

```
//UI code here; 
// A bit weird: we are already using Order here but declaring it below!!!
// Whereas for @inject, we are declaring it on top; the inconsistency is a bit puzzling...
@foreach (var pizza in Order.Pizzas)
{
    <p>
        <strong>
            @(pizza.Size)"
            @pizza.Special.Name
            (£@pizza.GetFormattedTotalPrice())
        </strong>
    </p>
}

@functions {
    [Parameter] Order Order { get; set; }
}
```

Why not:

```
@properties {
    // from the suggestion above:
    inject {
        HttpClient HttpClient;
        IUriHelper UriHelper;
        OrderState OrderState;
    }
   parameters {
       Order Order { get; set; }
   }
}

//UI code here; Order already declared above; no surprise there
@foreach (var pizza in Order.Pizzas)
{
    <p>
        <strong>
            @(pizza.Size)"
            @pizza.Special.Name
            (£@pizza.GetFormattedTotalPrice())
        </strong>
    </p>
}

@functions {
   //no more properties in the functions section (although we know properties are functions but still)
    async Task PlaceOrder() { }
    protected override async Task OnInitAsync() {}
}
```

The added advantage is that we removed that puzzling situation where we are using a parameter (`Order `in this case) in the UI section before we even declare it in the `@functions` section. We therefore prevent the scenario where the sequence of compilation is leaking.

Noli

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nolisj.
`@inject` is an existing Razor directive, which we reuse here and we don't want to introduce a Blazor-specific variation of it to avoid confusion.
As for the second suggestion, we don't want to reinvent new ways of defining properties and prefer to stick with the C# language.

**Comment by nolisj** [comment]
ok.
