### ISSUE TITLE
[Blazor] Add caching attributes when prerendering interactive components

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#11445]
When prerendering blazor server-side applications, we should add no-cache no-store must-revalidate and pragma no-cache to avoid the response being cached an the wrong circuit id being sent on the second response.

I didn't actually ran into this (I thought I did) but this is a good idea to do.

**Comment by SteveSandersonMS** [comment]
I think this can just be closed due to removing stateful prerendering (#12245).

**Comment by javiercn** [comment]
Should we do this based on the current user identity even if we don't do interactive? (At least for authenticated users)

**Comment by mkArtakMSFT** [comment]
Closing this as as this is for interactive prerendering, which we're removing.
