### ISSUE TITLE
SignalR server sometime hang until Ctrl+C is pressed

### ISSUE THREAD

**Issue by binhlt0402** [aspnet/AspNetCore#11441]
### Describe the bug
SignalR Console Application sometime hang until Ctr+C is pressed. Because I'm not sure this is my code or not I decided to use the server in dotnet-client sample to test and I got the same bug. Note that it's not just the steps below cause the bug, it's just the easiest to reproduce.

### To Reproduce
1. Download and open the dotnet-client sample https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/signalr/dotnet-client/sample
2. Publish the chat server and hosted it on a remote server using "dotnet SignalRChat.dll"
3. Open the JavaScript client page (http://[Host]:[Port])
4. Disabled your network adapter for about 30 seconds
5. Re-enable your network adapter and refresh the client page
6. Check the console and you can see there is no new log on console no matter how many time you refresh the page and you also can't send any message on the JavaScript client.
7. Press Ctrl+C on the console application and you will see the message for every action you took after the console hang flooding in.
8. You don't always get the bug after trying the steps above. Try step 4~7 for at least 4,5 times.

**Comment by BrennanConroy** [comment]
>Download and open the dotnet-client sample

What sample is that?

>Press Ctrl+C on the console application and you will see the message for every action you took after the console hang flooding in.

Did you perhaps accidentally click on the console which causes it to freeze? And then ctrl-c will cause it to no longer freeze and free up all the queued messages?

**Comment by binhlt0402** [comment]
> What sample is that?
It's the sample from AspNetCore.Docs. I linked the sample in the post. Sorry for the confusion.
> Did you perhaps accidentally click on the console which causes it to freeze? And then ctrl-c will cause it to no longer freeze and free up all the queued messages?
You might be right. I didn't know clicking on the console causes it to freeze. I thought the only key it accepted is whatever key it's waiting for and the Ctrl+C to terminate the application. So I clicked on it and scroll the window frequently to see the message.

**Comment by BrennanConroy** [comment]
You can use a different terminal program that doesn't freeze the application when you click on it. Besides that there is no workaround except to not click on the window.

Have you confirmed that this is the issue you were seeing?

**Comment by binhlt0402** [comment]
> 
> 
> You can use a different terminal program that doesn't freeze the application when you click on it. Besides that there is no workaround except to not click on the window.
> 
> Have you confirmed that this is the issue you were seeing?

Yeah, it's indeed the issue. I fixed it by turning off Quick Edit mode. Using a different terminal is a great choice too. Thanks.

The issue is fixed so I will close this thread.
