### ISSUE TITLE
Http.PostJsonAsync(string, object) need to return the response

### ISSUE THREAD

**Issue by yan0lovesha** [aspnet/AspNetCore#11455]
### Describe the solution you'd like
Currently only Http.PostJsonAsync<T>() can deserialize the response body to type T. Most times we don't want to define a C# class to represent the response body. In this case people often call Http.PostJsonAsync() instead, but this one doesn't give any chance to access the response. I think either return a HttpResponseMessage or a string of the body are OK. A string body should be able to cover the most scenarios.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @yan0lovesha.
We're tracking this issue as part of https://github.com/aspnet/AspNetCore/issues/10397
