### ISSUE TITLE
The Blazor circuitId can contain two consecutive dashes

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/AspNetCore#11454]
The pre-rendered HTML of a server-side component contains a configuration string comment (`<!-- M.A.C.Component:{"circuitId":"...`) and the circuitId there can contain a double dash (`--`).
This is invalid HTML syntax: https://www.w3.org/TR/html51/syntax.html#sec-comments

Different browsers react differently. Chromium (for example Edge Dev) doesn't really care, but I have seen at least a warning in IE11.

### To Reproduce
Given how the circuitId is generated: Try often enough?

### Expected behavior
Valid HTML syntax

### Screenshots
![image](https://user-images.githubusercontent.com/1947968/59939491-6a1f9b80-9458-11e9-883a-4d3620ac4a6c.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Tragetaschen.
@javiercn do we still use this format?

**Comment by javiercn** [comment]
@mkArtakMSFT We Base64UrlEncode stuff, which apparently can cause issues i wasn't aware of. We might Base32 things instead, at the expense of extra size. I'll see if I can figure out a cheap alternative.

**Comment by SteveSandersonMS** [comment]
> I'll see if I can figure out a cheap alternative.

An incredibly trivial solution would be `id.Replace("-", "@")`, then the reverse on the receiving end. If the perf cost was a concern, we could do it only if `id.Contains("--")`.

**Comment by javiercn** [comment]
I was planning to add this to my inflight PR as its uber-cheap. I was simply going to HTML.Encode the request id on the way out and HTML.Decode it on the way in, both should work fine and produce no allocations if the string is a valid HTML encoded string (which in most cases is)

**Comment by javiercn** [comment]
I did send a separate PR for this, we replace '--' sequences with '..'
