### ISSUE TITLE
AzureADB2C.UI expose Events

### ISSUE THREAD

**Issue by fileman** [aspnet/AspNetCore#11456]
### Is your feature request related to a problem? Please describe.
Add claims like roles or permissions read from db to user identity after successful login.

### Describe the solution you'd like
Set OpenIdConnectEvents like OnTokenValidated without copy all AzureAdB2C.UI required class from the github repo and customize it.

### Describe alternatives you've considered
This is a place where the query to db was executed only once after login, not after every page refresh, etc.

### Additional context
nothing

**Comment by blowdart** [comment]
You can do this with claims transformation, which works for all login types, rather than just limiting yourself to Azure B2C. Have you tried this and found it unsuitable?

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-2.2#configure-the-underlying-openidconnectoptionsjwtbearercookie-options

**Comment by fileman** [comment]
Thanks to both, I searched for "azureadb2c openid event" but the @Tratcher page didn't come out.
Both solution was what I need to do, I'm going to read documentation about it and choice what is better for my project.
