### ISSUE TITLE
Blazor: Allow writing logic code in a single cs file

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#11464]
### Is your feature request related to a problem? 
Currently we need to write all codes including HTML and C# in .razor files which is too complex for a code file when both logic code and layout code is large. 

### Describe the solution you'd like
Introduce a ".razor.cs" file, which allows us to write the code under "@code { ... }" in a ".razor.cs" file, so we can write layout related code in ".razor" files and logic code in the corresponding ".razor.cs" files.

**Comment by mkArtak** [comment]
This will be covered as part of https://github.com/aspnet/AspNetCore/issues/5487 work.

**Comment by SteveSandersonMS** [comment]
Closing as duplicate of #5487, since that will indeed provide what's needed to make this convenient.
