### ISSUE TITLE
Forwarded authentication handlers always run ClaimsTransformation twice

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#11462]
If you configure one authentication handler to forward to another via ForwardAuthenticate, ForwardDefault or ForwardDefaultSelector it ends up running ClaimsTransformation twice, once for the original handler and once for the forwarded one.
https://github.com/aspnet/AspNetCore/blob/4ef204e13b88c0734e0e94a1cc4c0ef05f40849e/src/Http/Authentication.Core/src/AuthenticationService.cs#L77-L82
https://github.com/aspnet/AspNetCore/blob/4ef204e13b88c0734e0e94a1cc4c0ef05f40849e/src/Security/Authentication/Core/src/AuthenticationHandler.cs#L131-L135

Proposal: Find a way to suppress the redundant claims transformation when forwarding.

I found this because the Negotiate auth handler is going to forward to the server auth handler when possible: https://github.com/aspnet/AspNetCore/pull/11421

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
Yeah this has always been an issue https://github.com/aspnet/Security/issues/1399  We can finally try to add something that automatically prevents claims transformation from running more than once I guess.  We would just need to do bookkeeping per request.

**Comment by brockallen** [comment]
Generally claims transformation only makes sense for the main authN scheme. As such, why not make it part of the authN middleware, rather than the authN service.

**Comment by HaoK** [comment]
That's one main scenario, but there are definitely scenarios for claims transformation on a per scheme basis too.  My initial thoughts are we just add some simple sugar to streamline the run once per scheme per request scenario, something like this could 'do the right thing':

```
  // This would register a scoped IClaimsTransform that would do whatever bookkeeping needed 
  services.AdddlaimsTransformation("schemeName(omit for default scheme)", o => {
    o.OncePerRequest = false; 
  });
```

**Comment by Tratcher** [comment]
Even once per scheme would still hit the issue with forwarders I posted above.

**Comment by HaoK** [comment]
Right, I guess we don't really need to run the same transformation multiple times ever, so that flag could be implemented as something we store in the AuthenticationResult so its only ever run once (on the inner most handler, which is likely the ideal behavior most of the time)

https://github.com/aspnet/AspNetCore/blob/master/src/Http/Authentication.Core/src/AuthenticationService.cs#L77
```C#
            var result = await handler.AuthenticateAsync();
            // NeedsTransform/ApplyTransform just check/store a flag in the AuthenticationProperties 
            if (result != null && result.Succeeded && result.NeedsTransform(Options))
            {
                var transformed = await result.ApplyTransformAsync(Options, Transform);
                // var transformed = await Transform.TransformAsync(result.Principal);

                return AuthenticateResult.Success(new AuthenticationTicket(transformed, result.Properties, result.Ticket.AuthenticationScheme));
            }
            return result;
```

**Comment by Tratcher** [comment]
That sounds promising.

**Comment by anurse** [comment]
For 3.0 we don't think this is feasible. Current recommendation is to ensure transformations are resilient to multiple invocations.

**Comment by HaoK** [comment]
Bringing this into 5.0 so we can try and get this right early @Tratcher
