### ISSUE TITLE
Blazor Deserialization error

### ISSUE THREAD

**Issue by JulienM28** [aspnet/AspNetCore#11476]
With upgrade to .NEt core 3 review 6 I get a deserialization issue with date using HttpClient.GetJsonAsync<T>() in Blazor

Here is the json:

````json
{
    "id": 1,
    "priority": 2,
    "type": 1,
    "status": 3,
    "title": "Ralentissements importants lors de la consultation d'une fiche produit",
    "creationdate": "2019-06-11T00:00:00",
    "userId": 13
}
````
If I use this code:
````csharp
Ticket = await Http.GetJsonAsync<TicketDetailsDto>($"api/tickets/{TicketId}");
````
The date is not deserialized correctly an I get a January 1st date

If I use this code:
````csharp
HttpResponseMessage response = await Http.GetAsync($"api/tickets/{TicketId}");
string jsonString = await response.Content.ReadAsStringAsync();
Ticket = JsonConvert.DeserializeObject<TicketDetailsDto>(jsonString);
````
the date is correctly deserialized.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JulienM28.
We rely on System.Text.Json for deserializing data. You can read more about this at: https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/docs/SerializerProgrammingModel.md#date-support
