### ISSUE TITLE
Visual Studio error displaying .razor file

### ISSUE THREAD

**Issue by JerryMcMillan** [aspnet/AspNetCore#11486]
I get an invalid operation exception in Visual Studio 2019 Preview, .NET Core 3 preview 4 when opening a .razor file. VS renders the text as white only and intellisense does not work.

When I check the error log:

`System.InvalidOperationException: The file &apos;C:/Users/jerry/Desktop/vs/MetroLock/MetroLock/Pages/FetchData.razor&apos; is not a descendent of the base path &apos;C:/Users/jerry/desktop/vs/MetroLock/MetroLock&apos; ...`

In the two paths, one of the "Desktop" is capitalized, the other is not. This is fixed by moving my project to a lower case only directory. I looked really quick at the file DefaultRazorProjectFileSystem.cs and one possible fix would be on line 53

`if (!absolutePath.StartsWith(absoluteBasePath))`

could be changed to:

`if (!absolutePath.StartsWith(absoluteBasePath, StringComparison.OrdinalIgnoreCase))`

I hope this helps,

Thanks!

**Comment by anurse** [comment]
> I looked really quick at the file DefaultRazorProjectFileSystem.cs

Since this file is in aspnet/AspNetCore-Tooling, my feeling is this probably should be moved to that repo. Thoughts @NTaylorMullen @mkArtakMSFT ?

**Comment by NTaylorMullen** [comment]
This is definitely a tolling issue; however, we track issues here in AspNetCore 😄. That being said this is the first public report of this issue that we've had. We have another [internal report of this issue ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/899854/) tracking the work as well. I've marked the bug with the appropriate labels and will leave it to triage to decide when to tackle this.

**Comment by BrennanConroy** [comment]
I am getting this consistently when opening .razor files in Components.sln.

Version 16.2.0 Preview 4.0 [29018.194.d16.2stg]
VisualStudio.16.IntPreview/16.2.0-pre.4.0+29018.194.d16.2stg

SDK: 3.0.100-preview6-012264

**Comment by ajaybhargavb** [comment]
@BrennanConroy, can you also include the actual error message and stack trace?

**Comment by BrennanConroy** [comment]
Encountered an error during adding a Code Container: Some or all identity references could not be translated.

```System.InvalidOperationException: The file 'C:/GitHub/aspnetcore/src/Components/test/testassets/BasicTestApp/EventPreventDefaultComponent.razor' is not a descendent of the base path 'C:/github/aspnetcore/src/Components/test/testassets/BasicTestApp'.
at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectFileSystem.GetItem(String path, String fileKind)at Microsoft.VisualStudio.Editor.Razor.DefaultImportDocumentManager.GetImportItems(VisualStudioDocumentTracker tracker)
at Microsoft.VisualStudio.Editor.Razor.DefaultImportDocumentManager.OnSubscribed(VisualStudioDocumentTracker tracker)
at Microsoft.VisualStudio.Editor.Razor.DefaultVisualStudioDocumentTracker.Subscribe()
at Microsoft.VisualStudio.Editor.Razor.DefaultRazorDocumentManager.OnTextViewOpened(ITextView textView, IEnumerable`1 subjectBuffers)
at Microsoft.VisualStudio.Editor.Razor.RazorTextViewConnectionListener.SubjectBuffersConnected(ITextView textView, ConnectionReason reason, IReadOnlyCollection`1 subjectBuffers)
at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.NonWpfListener.SubjectBuffersConnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)
at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.<>c__DisplayClass7_3.<.ctor>b__3()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by NTaylorMullen** [comment]
> System.InvalidOperationException: The file 'C:/GitHub/aspnetcore/src/Components/test/testassets/BasicTestApp/EventPreventDefaultComponent.razor' is not a descendent of the base path 'C:/github/aspnetcore/src/Components/test/testassets/BasicTestApp'.

Interesting, so your casing is busted. How are you opening the solution so I can try and dial down on a more concrete repro?

**Comment by BrennanConroy** [comment]
From the command line (in the . .\activate.ps1 environment), cd to Components folder, then "./Components.sln"

**Comment by NTaylorMullen** [comment]
Ah, so if you do pwd do you see a lower case `github` at the start of your path?

**Comment by BrennanConroy** [comment]
Yeah

**Comment by ajaybhargavb** [comment]
> Yeah

Wait `pwd` shows you `github`? When we spoke offline I thought you said your actual casing for the folder in disk was `GitHub`.

**Comment by BrennanConroy** [comment]
Yes, those are both true

**Comment by jekawo** [comment]
I have the same problem, Stack trace:
```
System.InvalidOperationException: 
The file 'C:/Users/jwo/source/repos/Workmodel/Workmodel/Workmodel.Client/Pages/sales.razor'
is not a descendent of the base path 
C:/Users/jwo/Source/Repos/Workmodel/Workmodel/Workmodel.Client'. at 
Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectFileSystem.GetItem(String path, String fileKind)   at 
Microsoft.VisualStudio.Editor.Razor.DefaultImportDocumentManager.GetImportItems(VisualStudioDocumentTracker tracker)   at 
Microsoft.VisualStudio.Editor.Razor.DefaultImportDocumentManager.OnSubscribed(VisualStudioDocumentTracker tracker)   at 
Microsoft.VisualStudio.Editor.Razor.DefaultVisualStudioDocumentTracker.Subscribe()  at 
Microsoft.VisualStudio.Editor.Razor.DefaultRazorDocumentManager.OnTextViewOpened(ITextView textView, IEnumerable`1 subjectBuffers)   at Microsoft.VisualStudio.Editor.Razor.RazorTextViewConnectionListener.SubjectBuffersConnected(ITextView textView, ConnectionReason reason, IReadOnlyCollection`1 subjectBuffers)   at
Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.NonWpfListener.SubjectBuffersConnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)   at 
Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.<>c__DisplayClass7_3.<.ctor>b__3()   at 
Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) 
--- End of stack trace from previous location where exception was thrown ---    
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
