### ISSUE TITLE
AspNetCoreModuleV2  HTTP Error 500.21 with Hosting Bundle 2.2.5 Bundle Installed

### ISSUE THREAD

**Issue by gravidThoughts** [aspnet/AspNetCore#11499]
### Describe the bug
Receiving a 500.21 error when attempting to access ASP.NET Core 2.2 application configured to use In-Process hosting.

### Expected behavior
If ASP.NET Core 2.2 Hosting Bundle is installed, should be able to host using IIS in-process.
 
### Screenshots
I have screenshots showing the bundle is installed , but my corporate Netskope is blocking me from uploading images, lol.

### Additional context
Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by jkotalik** [comment]
This error usually occurs when the global applicationhost.config file doesn't contain the correct global modules. Can you check and see if the global module AspNetCoreModuleV2 is listed in your applicationhost.config file in C:\Windows\System32\inetsrv?

Also, can you send the steps you took to repro this? Did you have other hosting bundles already installed on your machine? We have heard issues of this happening to customers but from what I can tell, we never received a great repro.

**Comment by gravidThoughts** [comment]
@jkotalik Appreciate the quick response. This is the issue. 
We use a shared configuration file. We removed the share, installed the hosting bundle on both, and then reestablished the share.

I'm assuming in this instance we forgot to look at changes made by the installer in the local configuration files and get those into the shared file. I'll close this if that turns out to be the case.

Thanks again!

**Comment by jkotalik** [comment]
> We use a shared configuration file. We removed the share, installed the hosting bundle on both, and then reestablished the share.

That's most likely the issue. The installer probably does not have permissions to write to the shared configuration. Are you redirecting the applicationhost.config via the redirection.config file?

**Comment by gravidThoughts** [comment]
> That's most likely the issue. The installer probably does not have permissions to write to the shared configuration. Are you redirecting the applicationhost.config via the redirection.config file?

I don't know. Let me ask IT. Is this a best practice all things being equal?

**Comment by gravidThoughts** [comment]
@jkotalik This indeed was the issue. Perhaps the installer team could warn the user that the local `applicationhost.config` will be changed and these changes need to be placed in the shared config if it is being used..

I didn't get an intelligible answer as far as the `redirect.config`. Do you think this makes a difference?

**Comment by jkotalik** [comment]
The ANCM installer sometimes can't write to an applicationhost.config that is redirected. AFAIK, the redirection.config file is the main way to enable a shared configuration.'

I would need to recheck the logic for how ANCM handles redirected config. Glad you figured out the issue though!
