### ISSUE TITLE
error with "StaticWebAssets" when deployed to azure appservice

### ISSUE THREAD

**Issue by marcelgoldstein** [aspnet/AspNetCore#11511]
In my **server-side blazor app** I am referencing a nuget package which contains a statis asset. This asset is getting copied correctly on publish ("\wwwroot\\_content\telerikuiforblazor\js\telerik-blazor.js"). So the asset works when debugging from VS2019 (app and iis-express) and when publish to a local folder and started from there.

But when published (webdeploy) to azure this error happens:
> An error occurred while starting the application.
> DirectoryNotFoundException: C:\Users\marcel\.nuget\packages\telerik.ui.for.blazor\1.2.0\staticwebassets\
> Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)
> 
> DirectoryNotFoundException: C:\Users\marcel\.nuget\packages\telerik.ui.for.blazor\1.2.0\staticwebassets\
> Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)
> Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root)
> Microsoft.AspNetCore.StaticWebAssetsFileProvider..ctor(string pathPrefix, string contentRoot)
> Microsoft.AspNetCore.StaticWebAssetsLoader+<>c.<UseStaticWebAssetsCore>b__2_0(ContentRootMapping cr)
> System.Linq.Enumerable+SelectEnumerableIterator<TSource, TResult>.MoveNext()
> System.Linq.Enumerable.OfTypeIterator<TResult>(IEnumerable source)+MoveNext()
> System.Collections.Generic.List<T>..ctor(IEnumerable<T> collection)
> System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
> Microsoft.AspNetCore.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
> Microsoft.AspNetCore.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment)
> Microsoft.AspNetCore.WebHost+<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
> Microsoft.AspNetCore.Hosting.Internal.GenericWebHostBuilder+<>c__DisplayClass8_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
> Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
> Microsoft.Extensions.Hosting.HostBuilder.Build()
> MiniatureGolf.Program.Main(string[] args) in Program.cs
> 
> Show raw exception details
> System.IO.DirectoryNotFoundException: C:\Users\marcel\.nuget\packages\telerik.ui.for.blazor\1.2.0\staticwebassets\
>    at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
>    at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
>    at Microsoft.AspNetCore.StaticWebAssetsFileProvider..ctor(String pathPrefix, String contentRoot)
>    at Microsoft.AspNetCore.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__2_0(ContentRootMapping cr)
>    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at Microsoft.AspNetCore.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
>    at Microsoft.AspNetCore.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment)
>    at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
>    at Microsoft.AspNetCore.Hosting.Internal.GenericWebHostBuilder.<>c__DisplayClass8_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
>    at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
>    at Microsoft.Extensions.Hosting.HostBuilder.Build()
>    at MiniatureGolf.Program.Main(String[] args) in D:\repos\MiniatureGolf\MiniatureGolf\Program.cs:line 13
> .NET Core 3.0.0-preview6-27804-01 X86 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 3.0.0-preview6.19307.2    |    Microsoft Windows 10.0.14393    |   Need help?

After a little bit of searching through the assemblies I found that the path that is used at runtime is set in the "Microsoft.AspNetCore.StaticWebAssets.xml" baked into the Applications DLL (MiniatureGolf.dll). It seems very strange to me that a local path from the build-maschine gets hard coded into the compiled assembly. So this might be a hint. 
![grafik](https://user-images.githubusercontent.com/32980128/60051038-5da67780-96d2-11e9-9b87-379df31a7d61.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @marcelgoldstein.
This is a known issue we're tracking the fix as part of https://github.com/aspnet/AspNetCore/issues/11185

/cc @javiercn
