### ISSUE TITLE
Identity/Account/Manage/Index.cshtml: Incomplete form after failed validation

### ISSUE THREAD

**Issue by aureole82** [aspnet/AspNetCore#11519]
## Steps to reproduce:
1. Create new ASP.NET Core web application: MVC + Authentication by "storing user accounts in-app" (Visual Studio 2019, .NET Core 2.2).
2. Run (register, apply migration, register again, ...)
3. Click on "Hello {username}": Razor page /Identity/Account/Manage opens
4. Enter invalid phone number (so that validation will fail)

## Expected behavior:
Complete form with validation messages.

## Actual behavior:
Incomplete form with validation messages.
![aspnetScaffolding-FalseValidationCausesIncompleteForms](https://user-images.githubusercontent.com/4819891/59977514-5304b900-95d2-11e9-9bab-c94ac017a8f8.gif)

Error:
**`Username` ist not part of `[BindProperty]` model so it got lost on the request.**

## Additional information about the project being scaffolded, such as:
```xml
<PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <UserSecretsId>aspnet-WebApplication7-0CD551B7-7495-448B-9BCC-E1D9464D4585</UserSecretsId>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
</PropertyGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
</ItemGroup>
```

**Comment by HaoK** [comment]
Fixed by https://github.com/aspnet/AspNetCore/pull/11768
