### ISSUE TITLE
Static assets result in IdentityUI project to fail publish, when the root is not very short

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#11529]
As the IdentityUI has been updated to avail of the new `Static Assets` feature, the publishing of a project referencing it results in quite long paths being used, which fails the publishing. See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935535 for more details

**REPRO STEPS**

File > New Preject > ASP.NET Core Web Application > Next > Give a name "Anc30_RazorWithRCL_Core_Ind", browse a new localtion "C:\Users\***\source\repos\OpenExisting\30_preview7_0621" > ASP.NET Core 3.0 ~ .NET Core ~ Web Application with IndAuth > Create
Right click the projrect > Publish > Create New > Select exisitgg group/plan > Create a Database with new or exisitng SQL Server > Publish

**RESULT**

Error Message:
Unable to copy file "C:\Users\***\.nuget\packages\microsoft.aspnetcore.identity.ui\3.0.0-preview7.19320.1\staticwebassets\V4\Identity\lib\jquery-validation\dist\jquery.validate.min.js" to "C:\Users\***\source\repos\OpenExisting\30_preview7_0621\Anc30_RazorWithRCLib_Core_Ind\Anc30_RazorWithRCLib_Core_Ind\obj\Release\netcoreapp3.0\PubTmp\Out\wwwroot\_content\microsoftaspnetcoreidentityui\V4\Identity\lib\jquery-validation\dist\jquery.validate.min.js". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

**Comment by javiercn** [comment]
We need to disable static web assets completely on the Identity UI package completely or take in https://github.com/aspnet/AspNetCore/pull/11029 which properly moves Identity UI into the static web assets model. (Which we either do now or not do until 5.0)

Also, from what I can see the publish output folder might be wrong in this case, as its pointing out to wwwroot_content, which suggests we are missing a path separator there.

**Comment by javiercn** [comment]
More generally, users might run into path too long exceptions in nuget packages, I'm not sure if ultimately the only solution is to enable long paths on the windows registry to allow paths longer than 260 chars.

**Comment by javiercn** [comment]
I did the work of migrating this and I have a PR out, I only need to fix helix tests for it and get a review from either Pranav or Haok.

**Comment by mkArtakMSFT** [comment]
@javiercn, please link the PR here.

**Comment by mkArtakMSFT** [comment]
Looks like the long file-path support will eventually become standard:
![image](https://user-images.githubusercontent.com/34246760/60115617-2ca66100-972b-11e9-9fb3-77e62b35d370.png)
Source: https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file

Unfortunately, we can't rely on this and require developers to switch to that version of windows. So fixing this is the right thing to do.

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/pull/11029

**Comment by javiercn** [comment]
@mkArtakMSFT Ultimately we can't do anything if the package path exceeds 260 chars for any given path on the package, as this depends on the user nuget package root path. We can try and have short paths, but that's it.

**Comment by mkArtakMSFT** [comment]
Agree, our abilities are completely limited here.

**Comment by javiercn** [comment]
Fixed in https://github.com/aspnet/AspNetCore/commit/143c10169326ea3972fc90950a938c33640777e2
