### ISSUE TITLE
Build does not complete after adding reference to System.ServiceModel.Http

### ISSUE THREAD

**Issue by dhebbler** [aspnet/AspNetCore#11525]
### Describe the bug
I am having trouble building a Blazor (client-side) project that has a reference to the WCF Libraries.  This issue occurs right after creating a new project and adding the reference.  Prior to adding the reference the project will compile correctly.  After adding a reference to the System.ServiceModel.Http package and attempting to compile the build starts, but never finishes.

### Environment Versions
```
dotnet --version
3.0.100-preview6-012264

dotnet msbuild -version
16.200.19.27801

```
### To Reproduce
```
dotnet new blazor
dotnet add package System.ServiceModel.Http --framework netstandard2.0 --version 4.5.3
dotnet build --verbosity detailed
```

### Expected behavior
Successful compile, or error indicating failure reason.

### Current behavior

```
Microsoft (R) Build Engine version 16.2.0-preview-19278-01+d635043bd for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Restore completed in 30.54 ms for C:\blazor\wcfReference\wcfReference.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\blazor\wcfReference\wcfReference.csproj]
wcfReference -> C:\blazor\wcfReference\bin\Debug\netstandard2.0\wcfReference.dll
```

The build is stuck here and never completes.

### Additional context

This is the last entry from the build log.  I've attached a complete log also.

```
Task "Exec"
dotnet "C:\Users\dhebbler\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview6.19303.4\build\netstandard1.0\../../tools/illink/illink.dll" -l none --disable-opt unreachablebodies --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\Users\ …  .0\System.Threading.Tasks.Extensions.dll" -a "C:\blazor\wcfReference\obj\Debug\netstandard2.0\wcfReference.dll"
```

[buildlog.txt](https://github.com/aspnet/AspNetCore/files/3322923/buildlog.txt)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not an area we control.
If you still have this problem, feel free to report it on the https://github.com/mono/mono repo.
