### ISSUE TITLE
Identity/Account/Manage/Index.cshtml: Form has 2 submit buttons?

### ISSUE THREAD

**Issue by aureole82** [aspnet/AspNetCore#11524]
## Steps to reproduce:
1. Create new ASP.NET Core web application: MVC + Authentication by "storing user accounts in-app" (Visual Studio 2019, .NET Core 2.2).
2. Run (register, apply migration, register again, ...)
3. Click on "Hello {username}": Razor page /Identity/Account/Manage opens
4. Enter phone number and hit Enter.

## Expected behavior:
Phone number is saved.

## Actual behavior:
![aspnetScaffolding-EnterTriggersWrongSubmitButton](https://user-images.githubusercontent.com/4819891/59976525-f26f7f00-95c5-11e9-90f0-955e74a346ea.gif)

Phone number is NOT saved. Message "Verification email sent. Please check your email." pops up.

**This happens because of the not quite clean form design: There are 2 submit buttons. The main submit button AND the `asp-page-handler="SendVerificationEmail"` button.** Unfortunately the `SendVerificationEmail` button comes first and therefore will be triggered on EACH Enter key stroke!

Is there any chance to push SendVerificationEmail action into an extra form/razor page?

## Additional information about the project being scaffolded, such as:
```xml
<PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <UserSecretsId>aspnet-WebApplication7-0CD551B7-7495-448B-9BCC-E1D9464D4585</UserSecretsId>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
</PropertyGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
</ItemGroup>
```

**Comment by HaoK** [comment]
https://github.com/aspnet/AspNetCore/pull/11768
