### ISSUE TITLE
Identity/Account/Manage/Index.cshtml: Glyphicons are outdated.

### ISSUE THREAD

**Issue by aureole82** [aspnet/AspNetCore#11523]
## Steps to reproduce:
1. Create new ASP.NET Core web application: MVC + Authentication by "storing user accounts in-app" (Visual Studio 2019, .NET Core 2.2).
2. Run (register, apply migration, register again, ...)
3. Confirm email (e.g. by just opening `AspNetUsers` table set `EmailConfirmed` to `True`)
3. Click on "Hello {username}": Razor page /Identity/Account/Manage opens

## Expected behavior:
![aspnetScaffolding-GlyphiconsOkReplacement](https://user-images.githubusercontent.com/4819891/59977113-ad4f4b00-95cd-11e9-8f1b-ddd933d48346.png)

## Actual behavior:
![aspnetScaffolding-NoGlyphiconsOkAvailable](https://user-images.githubusercontent.com/4819891/59977114-b213ff00-95cd-11e9-9588-44134ddee181.png)

The scaffolded markup is wrong:
```html
<div class="input-group">
    <input asp-for="Input.Email" class="form-control" />
    <span class="input-group-addon" aria-hidden="true"><span class="glyphicon glyphicon-ok text-success"></span></span>
</div>
```
The errors:
1. There's NO glyphicons referenced anywhere in the web application template. Why do you use it?
2. Bootstrap 4 doesn't support `.input-group-addon` anymore! https://getbootstrap.com/docs/4.3/migration/#input-groups 

## Additional information about the project being scaffolded, such as:
```xml
<PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <UserSecretsId>aspnet-WebApplication7-0CD551B7-7495-448B-9BCC-E1D9464D4585</UserSecretsId>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
</PropertyGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
</ItemGroup>
```

## Solution:
```html
<div class="input-group">
    <input asp-for="Input.Email" class="form-control">
    @if (Model.IsEmailConfirmed)
    {
        <div class="input-group-append">
            <span class="input-group-text text-success font-weight-bold">✓</span>
        </div>
    }
</div>
```

**Comment by HaoK** [comment]
Thanks for the suggestion @aureole82 we are removing the other glyphicon warnings from the other pages

**Comment by HaoK** [comment]
Fixed by https://github.com/aspnet/AspNetCore/pull/11768
