### ISSUE TITLE
Host Asp.net Core Api as an Application in IIS?

### ISSUE THREAD

**Issue by chobo2** [aspnet/AspNetCore#11527]
I have a react site and an asp.net core api(2.2).

I want them on the exact same domains ie

www.example.com --> reactjs code
www.example.com/api --? core api

that way I can do

www.example.com/api/values/get

I created a "application" on iis but when I tr to do the above line I get 403 forbidden (so I am not sure if it is trying to access the file directly as I have no authorization on this "Values api controller")

**Comment by anurse** [comment]
Have you taken a look at the [documentation on running ASP.NET Core apps as IIS sub-applications](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#sub-applications)? Assuming that documentation doesn't help, can you provide a runnable sample project that reproduces your issue, including relevant IIS configuration information?

**Comment by chobo2** [comment]
@anurse - thanks, will check it out and get back.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
