### ISSUE TITLE
Site extension build optimizations

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#11534]
A few of the suggestions in https://github.com/aspnet/AspNetCore/pull/11409#pullrequestreview-253738185. Also fix the typo

**Comment by Pilchie** [comment]
Assigning, since you are working on this now.

**Comment by JunTaoLuo** [comment]
This isn't too important for 3.0.0. Moving it out to 5.0 as a QoL improvement.
