### ISSUE TITLE
Build dashboard

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#11532]
We might want to keep track of a few metrics such as:
- Last successful build date (p0)
- Time since last dependency updates or out of date dependencies (p0)
- Build success rate
- Test success rate
- Flaky test hit counts

Right now these data are available through AzDO and Maestro++ but it'll be easier to monitor if we can organize this information in a centralized dashboard.

**Comment by Pilchie** [comment]
If I get some time on vacation next week I might take a look at this, as part of trying to update https://github.com/Pilchie/GitHubDashboard

**Comment by Pilchie** [comment]
Tagging @davidfowl here too.  Been slowly putting https://dev.azure.com/devdiv/DevDiv/_dashboards/dashboard/78282af7-5134-4be0-aa8e-a06e6b41acf1 together.

**Comment by JunTaoLuo** [comment]
Thanks @Pilchie for building one!
