### ISSUE TITLE
Unable to start any Blazor project

### ISSUE THREAD

**Issue by rcimpean** [aspnet/AspNetCore#11547]
### Describe the bug
I try to open a Blazor (Asp.net core hosted) app after update .net core, blazor extension and visual studio, and the app is blocked in "loading..." view and in browser console i got an error: "unable to found blazor.boot.json", and i have the same problem with new Blazor projects.

### Envirement
Visual Studio 2019 16.2 Preview 2.0
Visual Studio 2019 Professional 16.1.3
Visual Studio Code 1.35.1

### To Reproduce
1. Using this version of ASP.NET Core 3.0.0-preview6.19307.2
2. Create a new Blazor app (client-side or ASP.Net hosted) in VisualStudio or VsCode (dotnet new blazor)
3.Run app
4.Receive following error
![image](https://user-images.githubusercontent.com/15787876/60104529-53d05300-976a-11e9-8531-c3f81ed95488.png)

###My Project
https://github.com/rcimpean/TestBlazor/
### Expected behavior
Expected Blazor template start page.

### Additional context

Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27014-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by SteveSandersonMS** [comment]
I think you don't have the current version of the client-side Blazor templates.

 * If you want to create these projects in VS, install the latest VSIX: https://marketplace.visualstudio.com/items?itemName=aspnet.blazor
 * If you want to create them on the command line, install the latest templates package (`dotnet new --install Microsoft.AspNetCore.Blazor.Templates::*`)

Closing because it's known to work given the correct dependencies, and I think these steps will fix it. Please let us know if you think these steps aren't sufficient!

**Comment by rcimpean** [comment]
Thanks for your time, i reinstall the Blazor extension and the visual studio and i have the same problem
