### ISSUE TITLE
[Validation][ApiAuth] Validate angular and react templates after moving them to use code

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#11557]
Validate that you can log-in and fetch data on both templates.

**Comment by mkArtakMSFT** [comment]
Seems this didn't happen, so punting to the future to be handled during Preview 8 validation period

**Comment by javiercn** [comment]
Validation done with 3.0.100-preview8-013393

I ran the angular and react templates with dotnet run
* Click on fetch data
* Registered a new user
* Saw the data show on the page.
* Logged out
* Clicked login
* Entered credentials
* Successfully authenticated

I was able to get all the validations done.
