### ISSUE TITLE
Rename '@aspnet/signalr' and '@aspnet/signalr-protocol-msgpack' to '@microsoft/...'

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#11568]
We have [the name reserved on NPM](https://www.npmjs.com/package/@microsoft/signalr) and want to do this rename to help clarify that the SignalR client can be used in scenarios with the Azure SignalR Service where there is no ASP.NET :). We need to rename our `package.json` files and update dependencies to do this.

@pranavkm @rynowak This shouldn't affect Blazor as you embed the client, right? We'll have to update the build logic to make sure it works (we'll do the needful) but there shouldn't be a runtime impact from my understanding

fyi @DamianEdwards @bradygaster @davidfowl

**Comment by anurse** [comment]
Part of labelling this `accepted` includes getting docs all updated, so we'll make sure to do that and get appropriate PRs out ASAP (cc @guardrex @Rick-Anderson).

**Comment by anurse** [comment]
fyi @anthonychu @scottaddie

**Comment by anurse** [comment]
At RTM we'll also publish a version to `@aspnet/signalr:latest` that is marked deprecated and indicates that you should swap to `@microsoft/signalr`

**Comment by pranavkm** [comment]
+ @SteveSandersonMS 

> This shouldn't affect Blazor as you embed the client, right? We'll have to update the build logic to make sure it works (we'll do the needful) but there shouldn't be a runtime impact from my understanding

Yup, that sounds right.
