### ISSUE TITLE
ASP.NET Runtime pack manifest should have relative path in package to files

### ISSUE THREAD

**Issue by dsplaisted** [aspnet/AspNetCore#11577]
In the RuntimeList.xml of the ASP.NET runtime packs, the `Path` attribute currently only includes the file name:

```xml
<File Type="Managed" Path="Microsoft.AspNetCore.Antiforgery.dll" AssemblyName="Microsoft.AspNetCore.Antiforgery" PublicKeyToken="adb9793829ddae60" AssemblyVersion="3.0.0.0" FileVersion="3.0.19.32405" />
```

For the SDK to resolve these files, the `Path` needs to be the full path relative to the root of the package, for example:

```xml
<File Type="Managed" Path="runtimes/win-x86/lib/netcoreapp3.0/Microsoft.AspNetCore.Antiforgery.dll" AssemblyName="Microsoft.AspNetCore.Antiforgery" PublicKeyToken="adb9793829ddae60" AssemblyVersion="3.0.0.0" FileVersion="3.0.19.32405" />
```

Note that the relative path will be different for native assets too.

We didn't catch this because the SDK was looking for the wrong filename for the manifest: [RuntimeListList.xml](https://github.com/dotnet/sdk/blob/d72a57f27e8d8d5a3bf8376599346d325a6a2491/src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs#L71) instead of RuntimeList.xml. (Oops 🙃).  We can't fix the typo in the SDK until the ASP.NET runtime packs are fixed, otherwise the SDK will look for the runtime pack assets in the root of the runtime pack and fail to find them.

**Comment by JunTaoLuo** [comment]
Oh boy. Yea we'll need to fix this right away. I should be able to look at it tomorrow. If not, I'll voluntell someone.

**Comment by JunTaoLuo** [comment]
since @jkotalik volunteered.
