### ISSUE TITLE
Using Microsoft.AspNetCore.Mvc.NewtonsoftJson in Blazor preview 6

### ISSUE THREAD

**Issue by roboriaan** [aspnet/AspNetCore#11579]
I'm trying to figure out how to get NewtonsoftJson to work in Blazor preview 6

After adding the reference and running a dotnet restore I'm getting the following error :

**error NU1202: Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 3.0.0-preview6.19307.2 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 3.0.0-preview6.19307.2 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)**

Package references :

```
<PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0cpreview6.19307.2"/>
<PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview6.19307.2" PrivateAssets="all"/>
<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview6.19307.2"/>
```

I'm following this upgrade routine that explains how to add newtonsoft json   :
https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

To reproduce, just create a starter project using sdk : 3.0.100-preview6-012264 and add Microsoft.AspNetCore.Mvc.NewtonsoftJson Version="3.0.0-preview6.19307.2" 

TIA

**Comment by rynowak** [comment]
If this is for a client-side blazor project then the package you want is `Newtonsoft.Json`

**Comment by roboriaan** [comment]
Thanks Ryan. That did it! Yes it's client-side. Thanks for the great job you guys are doing on .net core and blazor.
