### ISSUE TITLE
ASP.NET Core 2.1 Razor - Ubuntu : error : rzc generate exited with code 1.

### ISSUE THREAD

**Issue by spboyer** [aspnet/AspNetCore#11570]
Error message: 
```console
microsoft.aspnetcore.razor.design/2.1.2/build/netstandard2.0/Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(121,5): error : rzc generate exited with code 1.
```

Application builds on macOS and Windows with no errors, fails on Ubuntu 16.04

### Cause 
Two folders named the same with different casing.

* .../Themes/DasBlog
* .../Themes/dasblog

### Resolution

Rename the folder to match.

### Notes

When Windows and MacOs pulls the two folders, they are combined and seen as a single folder. Only in Github and on Linux are they separate which would make sense why the compiler fails on Ubuntu. 
 
Github View
![image](https://user-images.githubusercontent.com/7681382/60136539-4e1e4180-9759-11e9-8c98-00548eda85e3.png)
 
VS Code on MacOS – Same on Visual Studio in Windows.
![image](https://user-images.githubusercontent.com/7681382/60136543-51193200-9759-11e9-92f1-fc488d84f570.png)

**Comment by danroth27** [comment]
The main issue here is that we don't print the actual error message.

We also want to investigate why the folder casing here matters.

**Comment by shanselman** [comment]
Likely it matters because the Layout happened to be in another folder, and when rcz goes to get the leaf nodes, it can't find the root Layout.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @spboyer.
This is not something we plan to fix. Given the simplicity of how this can be worked around, this won't meet the bar for servicing.
