### ISSUE TITLE
Check if user is authenticated on login page by authenticatio scheme

### ISSUE THREAD

**Issue by jfcaldeira** [aspnet/AspNetCore#11573]
I'm using 2 authentication schemes

```
    services.AddAuthentication()
             .AddCookie("ProductionAuth", options =>
             {
                 options.ExpireTimeSpan = TimeSpan.FromDays(1);
                 options.LoginPath = new PathString("/Production/Index");
                 options.LogoutPath = new PathString("/Production/Logout");
                 options.AccessDeniedPath = new PathString("/Production/AccessDenied/");
                 options.SlidingExpiration = true;
             })
            .AddCookie("AdministrationAuth", options =>
            {
                options.ExpireTimeSpan = TimeSpan.FromDays(1);
                options.LoginPath = new PathString("/Administration/Index");
                options.LogoutPath = new PathString("/Administration/Logout");
                options.AccessDeniedPath = new PathString("/Administration/AccessDenied/");
                options.SlidingExpiration = true;
            });
```

So to be able to access claims i have to decorate my pages with 

`  [Authorize(AuthenticationSchemes = "ProductionAuth")`

Now there is a problem,

on login page I cannot do this because users need to authenticate first, but I also need to redirect them if they are already logged in and i cannot do this because i don't have the scheme

```
        public IActionResult OnGet()
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                    return RedirectToPage("/Account/Index");
            }
            catch (Exception ex)
            {
                Console.Write(ex);
            }

            return Page();
        }
```

it returns false

**Comment by blowdart** [comment]
Is the login page for ProductionAuth or AdministrationAuth? Or do you want to do this on both login pages?

**Comment by jfcaldeira** [comment]
> Is the login page for ProductionAuth or AdministrationAuth? Or do you want to do this on both login pages?

On both but i cannot access claims on any of them because i'm not using authorize attribute, nor i can or they can't log in at all

**Comment by blowdart** [comment]
You can't do it on both. You might be able to do it on one by making one scheme the default, because that will run on every request regardless.

**Comment by Tratcher** [comment]
If you have seperate pages then you can call AuthenticateAsync with the expected scheme for that page.

**Comment by jfcaldeira** [comment]
> If you have seperate pages then you can call AuthenticateAsync with the expected scheme for that page.

Can you show me an example ? I don't recognize this function

**Comment by Tratcher** [comment]
`var result = await HttpContext.AuthenticateAsync("AdministrationAuth");`

I suppose even if you only had one page, you could call AuthenticateAsync for each scheme in turn.

**Comment by jfcaldeira** [comment]
> `var result = await HttpContext.AuthenticateAsync("AdministrationAuth");`
> 
> I suppose even if you only had one page, you could call AuthenticateAsync for each scheme in turn.

Yes! I can see my claims through this. Thanks a lot, this is exactly what i needed!
