### ISSUE TITLE
Redirection during prerendering doesn't work well

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#11591]
We have some logic that detects a `UriHelper.NavigateTo` call during prerendering, and is meant to turn it into a 302 redirection. However, trying to use this surfaced several problems:

 * It doesn't work if you try to redirect to the homepage (i.e., the base-relative URL is the empty string). I guess it's because the server-side ASP.NET Core APIs don't work in terms of base-relative URLs. Our code already knows the `_baseUriString` at that point in the flow, so we could fix this by calling `ToAbsoluteUri` and passing the result to the `NavigationException`.
 * For some reason, it logs the `NavigationException` to the console, even though our own code handles this and isn't meant to treat it as an error
 * For some reason, there's an almost 1 second delay before the redirection occurs. I determined this by disabling JS in my browser and trying to navigate to a component whose OnInit looks like this:

```cs
    protected override void OnInit()
    {
        UriHelper.NavigateTo("greeter");
    }
```

The browser's network tab shows the response time as ~ 1 second, even though it would be near instant if I was not redirecting to another place.

**Comment by katiep23** [comment]
Is this issue actually resolved?  I'm having very similar issue.

I have `uriHelper.NavigateTo("/Account/Login");` within "OnInitialized."  It actually works fine for me, but creates build error for other people on my team.  Workaround was to move it to "OnAfterRender" instead.

**Comment by javiercn** [comment]
Hi @katiep23. 
 
**It looks like you are posting on a closed issue!**

We're very likely to lose track of your bug/feedback/question unless you: 
1. Open a new issue 
2. Explain very clearly what you need help with 
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
