### ISSUE TITLE
Exception handling for multiple Areas in RazorPages

### ISSUE THREAD

**Issue by jfcaldeira** [aspnet/AspNetCore#11604]
so i noticed i was unable to hit the Error page in the default Pages directory from an area. I 

       if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }
            
Problem is If i add the area name to the path only one area can access it. How can i handle this ? Either 2 error pages or manage a route so both hit the same page? I each area also has a different authentication scheme

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
