### ISSUE TITLE
Consider adding .editorconfig file to templates used to create a new solution

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#11617]
Read this issue #11225 and especially these two comments: https://github.com/aspnet/AspNetCore/issues/11225#issuecomment-504253296 and https://github.com/aspnet/AspNetCore/issues/11225#issuecomment-504707787

Probably it is a good idea to have .editorconfig file in root solution folder.  This file should be created only when you create a new solution. Then every time you create or edit any file in any subdirectory in any editor/IDE with support for .editorconfig you can be sure that you have consistency in encoding, tab stops, etc.

**Comment by mikaelm12** [comment]
This is something that I've been meaning to do. It would save a number of pr comments and just help ensure consistency. We'll look into this 👍

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Andrzej-W.
@Andrzej-W, we don't think it's a good idea to add an .editorconfig because we don't want to start telling people what their editor config should be. As for the BOM issue, we plan to address it in a better way - by making BOM tolerable in the Razor Compiler.

@mikaelm12, we already have an editor config in the root of the repo.

**Comment by Andrzej-W** [comment]
@mkArtakMSFT there are probably thousands of programmers around the world who don't even know that VS supports .editorconfig. It is not bad to promote this wonderful feature.
> we don't think it's a good idea to add an .editorconfig because we don't want to start telling people what their editor config should be

In my opinion it is not a good argument because:
1. When you install VS it has some defaults for tab stops, indentation rules, etc. You can suggest the same settings in the .editorconfig file. I have no experience in VS templates but I suppose that it is possible to create .editorconfig file dynamically with settings consistent with current VS settings.
2. If someone uses .editorconfig file in other projects he probably copies it from old repository to the new one. In that case it doesn't matter if there is some file created when you create a new solution from scratch.
3. You can create a minimal .editorconfig file which only contains these lines:
```ini
# http://EditorConfig.org
root = true
[*]
charset = utf-8-bom
```
I think that it is better than nothing and doesn't hurt anybody. Please remember that if you don't have .editorconfig file with `charset` configuration and you edit file which doesn't have BOM, VS will save it in ANSI and this often has catastrophic consequences.

**Comment by Andrzej-W** [comment]
Maybe this minimal .editorconfig file shouldn't have `root=true`. This will solve the problem when people have one .editorconfig file in some folder and all solutions in subfolders.
```
d:\src
d:\src\.editorconfig
d:\src\solution1
d:\src\solution2
...
```
