### ISSUE TITLE
Web Application template has two *cool* blank lines in ConfiguresServices

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#11619]
![image](https://user-images.githubusercontent.com/1430011/60213353-2a6e0080-9818-11e9-8a7a-b9da151b4ae9.png)

Repo: 
- Create a new project using the Web Application template
- Open Startup.cs

**Comment by cjaliaga** [comment]
I can do a PR fixing this if you didn't start already.

**Comment by rynowak** [comment]
sure, we'd be happy for the help.
