### ISSUE TITLE
Remove Microsoft.AspNetCore.SpaServices.Extensions dependency on Microsoft.AspNetCore.SpaServices

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#11627]
Most of the functionality in [Microsoft.AspNetCore.SpaServices](https://nuget.org/packages/Microsoft.AspNetCore.SpaServices) is superseded by the functionality in [Microsoft.AspNetCore.SpaServices.Extensions](https://nuget.org/packages/Microsoft.AspNetCore.SpaServices.Extensions). We'd like to obsolete the bulk of the functionality in Microsoft.AspNetCore.SpaServices, but currently Microsoft.AspNetCore.SpaServices.Extensions has a dependency on it. We should look into breaking his dependency.

**Comment by ryanbrandenburg** [comment]
Fixed by #12892.

**Comment by schmitch** [comment]
actually I didn't want to hijack the thread, but after trying out rc1 I came across this issue. Basically we have an application that used the webpack dev middleware and there is no replacement from `SpaServices`. I'm not sure what `SpaServices.Extensions` does replace, but definitv there is no way to have a simple webpack script that works as nicely as before (scss only or scss and custom js, no react, angular, etc...)

in no way is `SpaServices.Extensions` a replacement or better than the simple `WebpackDevMiddleware`.

**Comment by ElanHasson** [comment]
I've run into this also @schmitch. 

How'd you proceed?
