### ISSUE TITLE
Dotnet publish is not working with -c Release AspNetCore 3.0 Preview 6

### ISSUE THREAD

**Issue by kdcllc** [aspnet/AspNetCore#11636]
Can't execute `dotnet publish Project.csproj -c Release` without exceptions on Web App.
###Output

````
3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets(53,5): error MSB4018: The "FindAssembliesWithReferencesTo" task failed unexpectedly.
````
### Expected behavior
To successful publish.

### Additional context
Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by anurse** [comment]
I can't repro this on `3.0.100-preview6-012264` with the following commands:

```
> dotnet new razor --name release-test
The template "ASP.NET Core Web App" was created successfully.                                                                                                                   
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.                                                                                                                                                                                                                              

Processing post-creation actions...
Running 'dotnet restore' on release-test\release-test.csproj...                                                                                                                   
  Restore completed in 49.87 ms for C:\Code\anurse\Scratch\release-test\release-test.csproj.

Restore succeeded. 

> dotnet publish .\release-test.csproj -c Release
                                                                                                                                        
Microsoft (R) Build Engine version 16.2.0-preview-19278-01+d635043bd for .NET Core                                                                                                           
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 13.41 ms for C:\Code\anurse\Scratch\release-test\release-test.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Code\anurse\Scratch\release-test\release-test.csproj]
  release-test -> C:\Code\anurse\Scratch\release-test\bin\Release\netcoreapp3.0\release-test.dll
  release-test -> C:\Code\anurse\Scratch\release-test\bin\Release\netcoreapp3.0\release-test.Views.dll
  release-test -> C:\Code\anurse\Scratch\release-test\bin\Release\netcoreapp3.0\publish\
```

I also tried the Razor Class Library and Empty templates. @kdcllc can you provide a sample project that reproduces the issue?

**Comment by kdcllc** [comment]
@anurse I am working on this https://github.com/kdcllc/Bet.AspNetCore/tree/feature/letsencrypt/src/Bet.AspNetCore.Sample project. The latest update is that when I use docker locally without `-c Release` it builds perfect image but when I use the same docker file in the Azure DevOps pipeline I get the same error.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kdcllc.
The action we're going to take here is to make the build failure error message more helpful.

**Comment by kdcllc** [comment]
@mkArtakMSFT I am still not able to build Docker file inside Azure DevOps pipeline. What is the underline issue here?

**Comment by pranavkm** [comment]
@kdcllc the issue seems to be the `GeneratePackageOnBuild` that you have here: https://github.com/kdcllc/Bet.AspNetCore/blob/feature/letsencrypt/build/settings.props#L29. Setting this to false in the sample fixes the issue.

I've filed https://github.com/dotnet/sdk/issues/3365 to track addressing the underlying issue.

**Comment by pranavkm** [comment]
@mkArtakMSFT using https://github.com/aspnet/AspNetCore/issues/11226 to track further work with the Razor SDK.
