### ISSUE TITLE
ASP.NET Core 2.2 Angular- Failed to start NPM when published to IIS

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#11631]
<p>I'm publishing my asp.net core 2.2 Angular 7 web application to IIS and I get below errors:</p><ol>
<li>Ensure that 'npm' is installed and can be found in one of the PATH directories.</li><li>InvalidOperationException: Failed to start 'npm'.</li><li>AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to start 'npm'. To resolve this:. [1] Ensure that 'npm' is installed and can be found in one of the PATH directories).</li></ol><p>This is for a Asp.Net core web application on Windows 2012 R2 server running IIS 8. My local machine with IIS 8 has same errors.</p><p></p><p>My launchsettings.json profile:</p><pre><code>   &quot;Test.IIS&quot;: {
        &quot;commandName&quot;: &quot;IIS&quot;,
        &quot;launchBrowser&quot;: true,
        &quot;environmentVariables&quot;: {
        &quot;ASPNETCORE_ENVIRONMENT&quot;: &quot;Development&quot;
   },
   &quot;ancmHostingModel&quot;: &quot;InProcess&quot;,
   &quot;applicationUrl&quot;: &quot;ttps://localhost:5002&quot;
   }</code></pre><pre><code>Below is my startup.cs file:

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

        // In production, the Angular files will be served from this directory
        services.AddSpaStaticFiles(configuration =&gt;
        {
            configuration.RootPath = &quot;ClientApp/dist&quot;;
        });
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseExceptionHandler(&quot;/Error&quot;);
            // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
            app.UseHsts();
        }

        //To check which process is runing the application
        //app.Run(async (contenxt) =&gt; {
        //    await contenxt.Response.WriteAsync(System.Diagnostics.Process.GetCurrentProcess().ProcessName);
        //});

        app.UseHttpsRedirection();
        app.UseStaticFiles();
        app.UseSpaStaticFiles();

        app.UseMvc(routes =&gt;
        {
            routes.MapRoute(
                name: &quot;default&quot;,
                template: &quot;{controller}/{action=Index}/{id?}&quot;);
        });

        app.UseSpa(spa =&gt;
        {
            // To learn more about options for serving an Angular SPA from ASP.NET Core,
            // see https://go.microsoft.com/fwlink/?linkid=864501

            spa.Options.SourcePath = &quot;ClientApp&quot;;

            if (env.IsDevelopment())
            {
                spa.UseAngularCliServer(npmScript: &quot;start&quot;);
            }
        });
    }
The code compiles successfully but throws the errors in run time.
<br></code></pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/436721/aspnet-core-22-angular-failed-to-start-npm-when-pu.html
VSTS ticketId: 778573_
_These are the original issue comments:_

Ling Yan [MSFT] on 1/28/2019, 08:57 PM (148 days ago): <p>I have the same problem for react project. Only happened on VS 2019 preview 2.</p>

Daniel Neuweiler on 1/30/2019, 04:06 AM (147 days ago): <p>If the problem only occurs in VS2019 P2, then maybe the following issue is the right for you:
</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/436395/visual-studio-2019-preview-2-failed-to-start-npm.html" target="_blank">https://developercommunity.visualstudio.com/content/problem/436395/visual-studio-2019-preview-2-failed-to-start-npm.html</a></p>

Shiva Shankar Naru on 1/29/2019, 08:26 AM (148 days ago): <p>My environment was Visual Studio 2017. Hope this information helps.</p>

Craig Avison-Maher on 3/21/2019, 09:36 AM (97 days ago): <p>Your applicationUrl in the launch settings doesn't start it https...<br><br>However! I am also getting this problem, any suggestions?</p>

ATOM Tech Indonesia on 5/13/2019, 08:53 AM (44 days ago): <p>Got this problem too<br>I'm using visual studio code<br>And only happened on react web only<br>Back end API works normal</p><p>Any suggestions?</p>

Visual Studio Feedback System on 6/18/2019, 04:44 AM (8 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

Andrew Stanton-Nurse [MSFT] on 6/19/2019, 09:43 AM (7 days ago): <p>Are you using Full IIS? If so, it's possible nodejs is in your local user's PATH but not in the PATH for the user that runs the IIS worker process. The default installer <strong>should</strong> put nodejs in the system PATH variable, but perhaps it hasn't in your scenario. Can you check your system PATH environment variable and see if nodejs is there? Specifically you need to check the <b>System</b> environment variables not the <b>User</b> environment variables. IIS worker processes run under a separate user, so even if "node" is on your local PATH in a command window, it's possible IIS still can't access it.</p>

_These are the original issue solutions:_

ATOM Tech Indonesia solved on 5/13/2019, 09:29 AM (44 days ago), 0 votes: <p>Reinstalling nodejs fix this problem =="</p>

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg can you please look into this and see how we can help? Thanks!

**Comment by ryanbrandenburg** [comment]
There could be a couple things going on here:
1. NPM is not on the path for the user which is running IIS (see Andrew Stanton-Nurse's response for more details). 
2. You could be running into https://github.com/aspnet/AspNetCore/issues/6342 (check the inner exception on the error page to see if that's the case).
3. Very unlikely to be the cause of this particular issue, but I notice that you have `"applicationUrl": "ttps://localhost:5002"` which isn't a valid URL.

If none of the above items solve your problem what we'll need to diagnose further is
- a minimal reproduction app
- The complete error you're seeing (if your seeing it an your websites DeveloperExceptionPage please take a screenshot (with the "Inner exception" field expanded)).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by evaleirasclapps** [comment]
Same problem here!

**Comment by tawani** [comment]
Has this issue been resolved in .NET Core 2.2?
