### ISSUE TITLE
MapControllerRoute throwing TypeLoadException: '... 'System.Text.Json.Serialization.JsonSerializerOptions' ...

### ISSUE THREAD

**Issue by fuocor** [aspnet/AspNetCore#11644]
### Describe the bug
MapControllerRoute throwing System.TypeLoadException: 'Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.'

### To Reproduce
Microsoft.AspNetCore.App: 3.0.0-preview6.19307.2
System.Text.Json: 4.6.0-preview7.19326.2

```
public void Configure(IApplicationBuilder app)
{
    app.UseCors(builder => builder
                .SetIsOriginAllowed(IsOriginAllowed)
                .AllowCredentials()
                .AllowAnyHeader()
                .AllowAnyMethod());

    app.UseAuthentication();
    void SetEndPointOptions(HttpConnectionDispatcherOptions options)
    {
        options.Transports = HttpTransportType.WebSockets;
    }

    app.UseRouting();
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapConnectionHandler<ApplicationConnectionHandler>("application/{id}", SetEndPointOptions);
        endpoints.MapConnectionHandler<SiteCollectionConnectionHandler>("sitecollection/{id}", SetEndPointOptions);
        endpoints.MapConnectionHandler<SiteConnectionHandler>("site/{id}", SetEndPointOptions);
        endpoints.MapConnectionHandler<TenantConnectionHandler>("tenant/{id}", SetEndPointOptions);
        endpoints.MapConnectionHandler<UserConnectionHandler>("user/{id}", SetEndPointOptions);
        endpoints.MapControllerRoute("default", "{controller=Runtime}/{action=Get}/{id?}");
    });
}
```
All the other connection handlers work.

### Expected behavior
No exception

### Additional context
Include the output of `dotnet --info`

**Comment by fuocor** [comment]
commenting out the line allows the code to get a little further but then it explodes creating ```Microsoft.AspNetCore.Mvc.JsonOptions```

**Comment by davidfowl** [comment]
> System.Text.Json: 4.6.0-preview7.19326.2

Remove this package. Preview7 is System.Text.Json isn't compatible with preview6 ASP.NET Core

**Comment by fuocor** [comment]
Downgraded to Preview6 and all runs. Thanks
