### ISSUE TITLE
after VS update (16.2.0 Preview 3.0) all methods reference show as error but compiles well.

### ISSUE THREAD

**Issue by HelvioBlazor** [aspnet/AspNetCore#11650]
![image](https://user-images.githubusercontent.com/52270697/60275189-880d5600-98c7-11e9-8219-fee4fa3f00f9.png)
![image](https://user-images.githubusercontent.com/52270697/60275223-95c2db80-98c7-11e9-8864-6f45d26f5dc9.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @HelvioBlazor.
@ajaybhargavb can you please look into this? Thanks!

**Comment by ajaybhargavb** [comment]
@HelvioBlazor what is the error you see when you hover over the red squiggly?

**Comment by rynowak** [comment]
@HelvioBlazor - the syntax for event handlers has changed. These should be updated to use directive attributes - event handlers in C# now start with `@`.

Ex:
```razor
<button @onclick="@MyMethod">
```

If you're using the latest VS, make sure you also have the latest .NET Core SDK preview (currently 3.0 preview 6). The tools will continue to change to keep pace with the latest SDK until we get to the 3.0 release.

**Comment by ajaybhargavb** [comment]
Oh duh. I didn't notice the lack of `@`. I agree with what @rynowak said 😄

**Comment by HelvioBlazor** [comment]
All methods call have the "@" look row 195 to 198. the SDK is Preview 5, I will update it.

**Comment by HelvioBlazor** [comment]
I just updated to Preview 6 I have the @ but still show Fake error.
![image](https://user-images.githubusercontent.com/52270697/60293906-40e68b80-98ee-11e9-9150-2a65365d8536.png)

**Comment by HelvioBlazor** [comment]
Another view
![image](https://user-images.githubusercontent.com/52270697/60294864-5bb9ff80-98f0-11e9-8127-ebabc3c34352.png)

**Comment by HelvioBlazor** [comment]
Ohhh Sorry I got!!!!! Thank you
