### ISSUE TITLE
Do not compile resx files

### ISSUE THREAD

**Issue by alfred-zaki** [aspnet/AspNetCore#11659]
Referring to this
https://github.com/aspnet/Localization/issues/251 

please consider re-adding the option to leave resx files un-compiled, customers for a webs app or even other apps i would say require different message langue for the same error or information message a web app pops.

think about this as an added value to allow customers to sort of customize their web app after delivery.
which doesn't mean a new language.

there should be option to load from psychical files (resx or else).

**Comment by Eilon** [comment]
RESX files are really meant to be compiled - they're not a great format for editing at runtime (it might *seem* like they are, but they aren't).

This might be better solved by something like with Orchard CMS does with PO files. Pinging @sebastienros

**Comment by sebastienros** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-2.2
