### ISSUE TITLE
Update MessagePack dependency

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#11664]
It's been a while since we've updated the submodule.

**Comment by pranavkm** [comment]
FYI @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
Adding this to the Preview 8, given the cost.

**Comment by anurse** [comment]
We don't use the submodule, we have a binary reference. What's the SignalR ask here? Or is that just @Eilon mistagging 😝

**Comment by pranavkm** [comment]
This one's on me.
