### ISSUE TITLE
InvokeAsync: Method not found "System.Runtime.CompilerServices.Unsafe.Unbox"

### ISSUE THREAD

**Issue by ZergZe** [aspnet/AspNetCore#11677]
### Describe the bug

Call **InvokeAsync** method passing **ElementRef** as argument crashes client-side Blazor if "**\<BlazorLinkOnBuild\>false\<\/BlazorLinkOnBuild\>**" in project.

### To Reproduce

Have components razor markup:

```
@inherits MyComponentBase
...
<input @ref="@InputElement" >
```

with c# code:

```
public partial class MyComponentBase<T> : ...
{
        protected ElementRef InputElement;

        protected override Task OnAfterRenderAsync()
        {
            JsRuntime.InvokeAsync<string>("MyClientSideMethod", InputElement);
            ...
        }
}
```

Works fine in server blazor and in client-side blazor if there is no "\<BlazorLinkOnBuild\>false\<\/BlazorLinkOnBuild\>" in project.

if i set "\<BlazorLinkOnBuild\>false\<\/BlazorLinkOnBuild\>" to the project, I see the error:

```
WASM: System.MissingMethodException: Method not found: !!0& System.Runtime.CompilerServices.Unsafe.Unbox<!0>(object)
...
WASM:   at System.Text.Json.Serialization.JsonSerializer.ToString[TValue] (TValue value, System.Text.Json.Serialization.JsonSerializerOptions options)
WASM:   at Microsoft.JSInterop.JSRuntimeBase.InvokeAsync[T] (System.String identifier, System.Obj
```

### Expected behavior
Works in client-side Blazor with "<BlazorLinkOnBuild>false</BlazorLinkOnBuild>" too.

### Additional Info

1. Have to use \<BlazorLinkOnBuild\>false\<\/BlazorLinkOnBuild\>
due to [EntityFrameworkCore.SqlServer issue in mono](https://github.com/mono/mono/issues/12916)

2. Add following does not help:

```
<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.6.0-preview6.19303.8" /> 
```

**Comment by ZergZe** [comment]
Found [this](https://github.com/mono/mono/issues/14871).
Seems to be the same.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ZergZe.
We've updated the mono bits days ago: https://github.com/aspnet/AspNetCore/issues/11448
So most probably that's in.

**Comment by SteveSandersonMS** [comment]
Yes, this is fixed in the upcoming preview 7 release.

**Comment by laurence73** [comment]
Great to hear! this has been causing untold nightmares as we have referenced projects using Microsoft.CodeAnalysis.CSharp which requires <BlazorLinkOnBuild>false<<BlazorLinkOnBuild> :-)

**Comment by BaranOzdemir** [comment]
When is preview 7 release coming?

**Comment by chucker** [comment]
@BaranOzdemir it's scheduled for tomorrow (the 23rd)
