### ISSUE TITLE
RenderFragment is not recognized in Visual Studio when its name matches a html tag

### ISSUE THREAD

**Issue by jivanova** [aspnet/AspNetCore#11674]
### Describe the bug
RenderFragment within a component is not recognized in VS and is not shown in the intellisence.

### To Reproduce
``` 
<!-- Child Component -->
<span>@Template</span>

@code {
    [Parameter] RenderFragment Template { get; set; }
}
```
``` Usage
    <ChildComponent>
          @*only the html5 <template></template> tag is shown in the intellisence. If Template is written with capital letter, the code is successfully compiled but still the VS does not recongnize that it's a RenderFragment part of the childcomponent'*@
          <template></template>
    </ChildComponent>
```
### Expected behavior
`Template` to be recognized as a RenderFragment and to be present in the intellisence.

### Screenshots
![image](https://user-images.githubusercontent.com/7159157/60317346-4b993300-9977-11e9-80eb-6e251b626a6c.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jivanova.
This will be addressed as part of #9860 work.
