### ISSUE TITLE
Blazor templates: add `@using Microsoft.AspNetCore.Authorization`

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#11687]
We should add `@using Microsoft.AspNetCore.Authorization` to the top-level `_Imports.razor`, otherwise it's hard to write:

```
@attribute [Authorize]
```

**Comment by SteveSandersonMS** [comment]
It's an open question whether we do this unconditionally or only when one of the authentication mechanisms has been chosen.

**Comment by isaac2004** [comment]
Warpping in am Auth conditional is what the other templates do, so that makes most sense

**Comment by SteveSandersonMS** [comment]
Currently we're not using conditionals in `.razor` files due to a tooling limitation, so for now at least this will be added unconditionally. There isn't really any drawback to doing this, considering what other stuff is also there unconditionally.

**Comment by SteveSandersonMS** [comment]
Done inhttps://github.com/aspnet/AspNetCore/pull/11736

**Comment by isaac2004** [comment]
@SteveSandersonMS what do you mean there is a tooling limitation? Using this approach works just fine

```
@*#if (!Hosted)
	Stuff I want conditioned
#endif*@
```

**Comment by SteveSandersonMS** [comment]
It didn't used to work when the template was executed inside VS (though it did on the command line). Whether that's fixed or not yet in VS I don't know, and so it's safer to proceed assuming it hasn't been fixed, considering how close we are to the deadline for including this change. Also, it's done and merged now :)
