### ISSUE TITLE
[Build] Reenable components E2E tests on the CI

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#11698]
These tests got disabled by f76be64e5db2e7a3cc8d41b9055a7aa63c5f52b5 and further changes to the build infrastructure (likely due to 4fde84a7ad48c8265fe868650351c857bcf1bfc2) cause the tests to hang on the CI.

We should get to the bottom of this ASAP as it hurts our ability to deliver the product with confidence.

The change here is to replace
```
<SkipTests>true</SkipTests>
```

with
```
<SkipTests Condition="'$(SeleniumE2ETestsSupported)' != 'true'">true</SkipTests>                                                                                                                                                                               
```
 on `.\src\Components\test\E2ETest\Microsoft.AspNetCore.Components.E2ETests.csproj`

and figure out why the component tests don't finish, as they finish on local builds.

**Comment by mkArtakMSFT** [comment]
@JunTaoLuo can you please handle this as soon as possible, as this has been a pain point for us.

**Comment by JunTaoLuo** [comment]
This will require expertise from the product area. Will you be able to help @javiercn ? I'm not sure if I can prioritize this above source build work in the short term.

**Comment by dougbu** [comment]
Many thanks @rynowak
