### ISSUE TITLE
Vertical Scroll On All Pages In Default Razor Project Using .Net Core 2.2 and Visual Studio 2017 Professional Version 15.9.13

### ISSUE THREAD

**Issue by satbirbaidwan** [aspnet/AspNetCore#11694]
### Issue Description
**I just noticed that there is a vertical scroll (shown on the right side) on all pages. I checked this on another machine and new project thinking i may have changed something and it still shows on project created using Core 2.2.**

To confirm i created a another project on first machine this time using Core 2.1 and it does not shows the vertical scroll.

### To Reproduce
1. Using this version of ASP.NET Core '2.2' and VS 2017 15.9.13
2. Create a web project using Asp.Net Core 2.2 and default Razor Project 
3. Run the project

### Expected behavior
There should be no scroll bar on a default project (no code or css changes done !)

### Screenshots

![VscrollIssue](https://user-images.githubusercontent.com/24276254/60373481-90e05380-99bd-11e9-8540-607575076ffb.PNG)

**Comment by Eilon** [comment]
I think this was recently fixed. Some CSS style was too tall by 1px or something like that.

**Comment by Eilon** [comment]
Assuming this is the same issue:
* Original issue: https://github.com/aspnet/AspNetCore/issues/7305
* Fixed in https://github.com/aspnet/AspNetCore/pull/8870

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @satbirbaidwan.
This is fixed, as per @Eilon 's response above.

We won't be patching this for ASP.NET Core 2.2 release.
