### ISSUE TITLE
Blazor: Provide a better router.

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#11708]
### Is your feature request related to a problem? Please describe.
Feature request. Please provide a better router.

### Describe the solution you'd like
Original design see #11671.
I implemented it at https://github.com/hez2010/BlazorRouter. It provides router events, routing parameters, and enables state management for Blazor. I published it as a nuget package Hez2010.BlazorRouter.

I think it will solve #10445, #5467, #9438 and #10493.

For a live example, visit: https://hez2010.github.io/BlazorRouter.

I recommend Blazor to use Hez2010.BlazorRouter instead of the original Router.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. It's great to see you were able to implement and publish this!

> I recommend Blazor to use Hez2010.BlazorRouter instead of the original Router.

That's not something we can do in the short term, as we're far too close to shipping 3.0 to replace such a fundamental piece of infrastructure entirely with something that's not API-compatible and hasn't been battle-tested in thousands of projects already.

What we can do is suggest your package as an option for people looking for alternative router features. I'd recommend you continue figuring out what people want in a more advanced router and implement it, and perhaps your user base will grow over time. In the long term you may reach a point where a large proportion of Blazor app developers choose to switch over to your router. If there's enough proven success and demand in the long run, we'd consider making it a default choice in a future major release.

Hope that sounds OK!
