### ISSUE TITLE
appsettings.Development.json does not load properly

### ISSUE THREAD

**Issue by filunK** [aspnet/AspNetCore#11709]
I'm afraid of being that appsettings.Development.json does not load properly.

When I debug my aspnetcore application with ASPNETCORE_ENVIRONMENT set to Development I found that a value was set unexpectedly, which the value comes from appsettings.json, not appsettings.Development.json.

### Environment

| name | value  |
|---|---|
| OS  | Ubuntu Budgie 19.04  |
| dotnet | 2.2.204 |
| DevTool | Visual Studio Code 1.35.1 |

### Details

My appsetting.json is ;

``` JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "Jwt": {
    "Key" : "devKey_appsettng_noenv",
    "Issuer": "http://localhost:5000",
    "ExpireMinutes": 30
},
"ConnectionStrings": {
  },
  "AllowedHosts": "*"
}
```

and my appsetting.Development.json is;

``` JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    },
    "Jwt": {
      "Key" : "devKey12345678901234567890",
      "Issuer": "http://localhost:5000",
      "ExpireMinutes": 30
    },
    "ConnectionStrings": {
    }
    }
}
```

In my aspnetcore application, codes loading appsetting.*.json are below(generated by dotnet command, not changed);

``` C#
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) => 
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
```

Startup class is below;

``` C#
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            this.Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<AppSettings>(this.Configuration);

            // OTHER CONFIGURATIONS......
        }
    }
```

In a controller class, I load configurations using POCO AppSettings class.

``` C#
    public class LoginController : ControllerBase
    {
        private readonly AppSettings _config ;

        public LoginController(IOptions<AppSettings> configuration)
        {
            this._config = configuration.Value;
        }

        // OTHER METHODS......
    }
```

When I start debugging with Visual Studio Code , which launching configuration has ``"ASPNETCORE_ENVIRONMENT": "Development"`` in the env section ,I found the property LoginController._config.Jwt.Key has value ``devKey_appsettng_noenv``, not ``devKey12345678901234567890``.

**Comment by DAllanCarr** [comment]
There seems to be diffs between prod and dev files.

**Comment by filunK** [comment]
Oh, I got it......
