### ISSUE TITLE
Blazor library with Javascript interop fails server-side

### ISSUE THREAD

**Issue by haavamoa** [aspnet/AspNetCore#11714]
### Describe the bug
I have created a Blazor library package (using the `blazorlib` template). In that library I have only created a simple JavaScript interop that should set focus on a element.
Here is the source code for that library: https://github.com/haavamoa/BlazingFocus

When referencing this in a client-side Blazor project (`blazor` and `blazorhosted` templates), everything is working. 

When I reference this in a server-side project (`blazorserverside`) I will get an exception that tells me that my JavaScript can't be found:
`Message = "Could not find '<myjavascriptmethod>' in 'window'.\nError: Could not find '<thejavascriptmethod>' in 'window'.\n    at http://localhost:5000/_framework/<myproject>.server.js:8:20878\n    at Array.forEach (<anonymous>)\n    at d (http://localhost:5000/_framework/blazor.server.js...`

When I use the developer tools and go to `Sources` I can not locate my Javascript either. 

### To Reproduce
1. Using this version of ASP.NET Core : `3.0.100-preview6-012264`
2. Create a `blazorlib`
3. Create a JavaScript interop that runs a method that is defined in a JavaScript file inside `content` folder. Or you can just use the template as is.
4. Surround the calling interop method with a  `try-catch(Exception e)`.
5. Create a `blazorserverside` project.
6. Add reference to the `blazorlib` you just created
7. Try to use your interop class, in example in the `OnAfterRenderAsync` method in a page.
8. Breakpoint the interop call and observe the exception.

### Expected behavior
My JavaScript in the `blazorlib` should be called.

**Comment by SteveSandersonMS** [comment]
The server-side Blazor template has never supported the old-style static content feature you're using here (i.e., the default static content mechanism in `blazorlib`).

The server-side Blazor template supports only the new-style static content feature: see "Static assets in Razor class libraries" in [this blog post](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6).

To unify the situation across all scenarios, we're also migrating the new-style static content feature into the client-side templates and removing the old one. We will be retiring the `blazorlib` template entirely and making client-side and server-side Blazor share the same components class library template.

**Comment by haavamoa** [comment]
That guide worked perfectly. The only issue I have with this option is that the users of my package has to include the JavaScript file in their `index.cshtml`. This is not needed if I follow the guide and use my package in a client-side blazor project. So if you are migrating this style, I would appreciate the latter style for both scenarios.

**Comment by SteveSandersonMS** [comment]
Auto-adding `<script>` tags (etc) is something we've made a deliberate decision to exclude from the newer mechanism, because there are so many cases where this can't possibly work (e.g., if the developer needs to control the inclusion order, or if they have to select 1 out of N possible files (e.g., for localisation), or because they are going to do a custom Webpack build over all the files).

Package authors should document the suggested markup to be added to `index.html`, as well as any guidance on what order things should be put into. I know that feels less convenient, but it's the only approach that really scales up to real-world complexity in general.

**Comment by haavamoa** [comment]
Thank you so much for clarifying.
