### ISSUE TITLE
Blazor Client Side: Provide an Async startup method

### ISSUE THREAD

**Issue by ApocDev** [aspnet/AspNetCore#11711]
On server side, we have the ability to read files synchronously, and run web requests synchronously, so we can capture configuration, load extra data, etc, from remote places.

On client side however, anything not specifically hard-coded into the Blazor project assembly, must be retrieved via an async web request (or async JSInterop call).

Currently, there is no way to do this in a stable way, that also allows you to do all of this configuration gathering *before* Startup.ConfigureServices, to allow you to configure your DI services.

While I realize this would be slightly divergent from normal ASP.NET Core startup, considering the Browser is missing much of the available functionality, and this is a very, *very* common use case, there should be some built in mechanism to allow us to retrieve all this information, before we fully set up the DI services.

Ideally something such as `Task BeforeConfigureServicesAsync( IJSRuntime jsRuntime, HttpClient httpClient );` in IBlazorStartup could be added that is called before the service provider is built.

Obviously, being able to capture the major dependencies for executing web requests, and JS interop are probably going to be the most widely used.

**Comment by mkArtakMSFT** [comment]
This is essentially the same ask: https://github.com/aspnet/AspNetCore/issues/11716
