### ISSUE TITLE
Firefox 67.0.4 won't negotiate an SSL connection with localhost

### ISSUE THREAD

**Issue by voltagex** [aspnet/AspNetCore#11719]
### Describe the bug
Doing `dotnet new webapp` with .NET Core Preview 6, then opening the project in VS2019 16.2 Preview and running the app produces the following error in Firefox 67.0.4

```
Your connection is not secure

The website tried to negotiate an inadequate level of security.

localhost uses security technology that is outdated and vulnerable to attack. An attacker could easily reveal information which you thought to be safe. The website administrator will need to fix the server first before you can visit the site.

Error code: NS_ERROR_NET_INADEQUATE_SECURITY
```

I wasn't prompted to trust any kind of certificates by Visual Studio, but this doesn't look like a normal certificate error.

### To Reproduce
1. Using this version of ASP.NET Core `3.0.100-preview6-012264`
2. Run this code `mkdir some-path; cd some-path; dotnet new webapp; start some-path.csproj`
3. Switch to Kestrel in VS, not IIS Express
4. Debug app
5. See error

### Expected behavior
Page loads, or certificate error happens.

### Screenshots
![image](https://user-images.githubusercontent.com/159567/60396653-a86b3800-9b87-11e9-810d-4db285eafc90.png)

### Additional context
Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

**Comment by jkotalik** [comment]
This potentially could be the same issue as https://github.com/aspnet/AspNetCore/issues/8952. Can you try regenerating the https development cert by running:
`dotnet dev-certs https --clean` and `dotnet dev-certs https --trust`

**Comment by voltagex** [comment]
@jkotalik yes, that worked - I was presented with the normal Firefox self-signed cert warning and was able to proceed.

**Comment by anurse** [comment]
Closing as we believe this will be resolved in the next SDK release (preview 7) and the dev cert should be automatically updated. If anyone comes across this when running preview 7, let us know by filing a new issue!
