### ISSUE TITLE
Output format of TimeSpan changed in AspNetCore 3.0

### ISSUE THREAD

**Issue by yhvicey** [aspnet/AspNetCore#11724]
### Describe the bug

Output format of `TimeSpan` changed in AspNetCore 3.0. For example, if you have below function in both `2.2` and `3.0`:

```cs
[HttpGet("timespan")]
public TimeSpan Get()
{
    return TimeSpan.FromHours(1);
}
```

For `2.2` application, output would look like below:

```json
"01:00:00"
```

For `3.0` application, output would look like below:

```json
{
    "ticks": 36000000000,
    "days": 0,
    "hours": 1,
    "milliseconds": 0,
    "minutes": 0,
    "seconds": 0,
    "totalDays": 0.041666666666666664,
    "totalHours": 1,
    "totalMilliseconds": 3600000,
    "totalMinutes": 60,
    "totalSeconds": 3600
}
```

Is this change made by design? If so, is there any switch/options we can use to switch between two formats?

### To Reproduce
1. Create an AspNetCore 3.0 application
1. Return any `TimeSpan` object (directly or nested) in controller actions
1. See result

### Expected behavior
A string can be parsed to `TimeSpan` directly

**Comment by benaadams** [comment]
You may want to open an issue in https://github.com/dotnet/corefx about System.Json's serialization of `TimeSpan`

**Comment by yhvicey** [comment]
Seems this behavior still exists even if I called `.AddNewtonsoftJson()` while configuring services. Will try the result of `System.Text.Json`'s serialization.

**Comment by yhvicey** [comment]
Looks like it's caused by `System.Text.Json.Serialization.JsonSerializer`. Result of `JsonSerializer.ToString(TimeSpan.FromHours(1))` looks like what it like in 3.0 apps. But I'm still wondering why it's still been handled by `System.Text.Json.Serialization.JsonSerializer` rather than Json.Net's serializer after calling `.AddNewtonsoftJson()`, is there any additional step I missed?

**Comment by yhvicey** [comment]
Found one related issue: dotnet/corefx#38641. Maybe adding a customized JsonConverter will be the workaround.

**Comment by mkArtakMSFT** [comment]
@yhvicey, can you please share a repro project for this particular scenario:

> Seems this behavior still exists even if I called .AddNewtonsoftJson() while configuring services. Will try the result of System.Text.Json's serialization.

As for the main issue, please use the [referenced issue](https://github.com/dotnet/corefx/issues/38641) you've found as it's external to this repo.

**Comment by yhvicey** [comment]
Ok I know what happend. I forget to add `Microsoft.AspNetCore.Mvc.NewtonsoftJson` package to my API project, but it's introduced by `Swashbuckle.AspNetCore.SwaggerGen` with version `3.0.0-preview3-19153-02`. With this specific version, `.AddNewtonsoftJson()` call won't change anything and it will still use the `System.Text.Json`. The issue is fixed for me by install the latest version of this package.
