### ISSUE TITLE
BuildServiceProvider in ConfigureServices should raise a warning

### ISSUE THREAD

**Issue by csharpfritz** [aspnet/AspNetCore#11727]
### Is your feature request related to a problem? Please describe.
To encourage better practices, it would be helpful for an Analyzer to raise a warning if BuildServiceProvider is called in ConfigureServices.  This is an antipattern we should discourage

**Comment by rynowak** [comment]
👍 💯 - want to send a PR?

**Comment by csharpfritz** [comment]
Would LOVE to send some PRs for analyzers to help with this.

Where should we place those features?

**Comment by rynowak** [comment]
Here: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Analyzers/src/Startup/StartupAnalzyer.cs#L27

For now you can follow the pattern used by `UseMvcDiagnosticValidator`. I have [a PR out](https://github.com/aspnet/AspNetCore/pull/9488) that simplifies this a little bit, but I don't want you to block on that.

**Comment by rynowak** [comment]
Thanks @wu-yafeng
