### ISSUE TITLE
The host does not match an allowed host with signalRCore 1.1.0

### ISSUE THREAD

**Issue by butterngo** [aspnet/AspNetCore#11737]
### Startup.cs
1. services.AddCors();
2.  app.UseCors(builder => builder
                .WithOrigins("http://localhost:3000/")
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials());
3. const connection = new signalR.HubConnectionBuilder()
		.withUrl("http://localhost:7500/hub/chat", { 
//      skipNegotiation: true,
//    transport: signalR.HttpTransportType.WebSockets
     }).build();
    connection.start().then(function () {
        console.log("connected");
    });
**FE, I am using "@aspnet/signalr" version 1.1.4.
Any suggestions for me.
Thanks**

**Comment by BrennanConroy** [comment]
Where is `services.UseCors(...)` in relation to the other middleware? It should be before things like `services.UseSignalR(...)`.

Also, just to be sure could you try `.WithOrigins("http://localhost:3000")` (without the trailing slash) to see if that works?

**Comment by butterngo** [comment]
Hi, @BrennanConroy  I did but it still not work with me, My Repository https://github.com/butterngo/CSharpMessageQueue, Please help me review that.
Thank you

**Comment by BrennanConroy** [comment]
Take a look at https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.2#cross-origin-resource-sharing

I noticed you're missing `.AllowCredentials()` which is required

**Comment by butterngo** [comment]
Hi @BrennanConroy This old code and I tried with it before that, but it's not working.
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {

            app.UseCors(builder =>
            {
                builder.WithOrigins("http://localhost:3000")
                    .AllowAnyHeader()
                    .WithMethods("GET", "POST")
                    .AllowCredentials();
            });

            app.UseSignalR(routes => 
            {
                routes.MapHub<CSharpMessageHub>(Configuration.GetValue<string>("EndPoint"),
                    options => 
                    {
                        options.ApplicationMaxBufferSize = 2048 * 1024;
                    });
            });

        }

**Comment by BrennanConroy** [comment]
@butterngo I downloaded your app and changed the CORS snippet to:
```csharp
app.UseCors(builder => builder
    .WithOrigins("http://localhost:3000")
    .AllowAnyMethod()
    .AllowAnyHeader()
    .AllowCredentials());
```

And fixed the "AllowedHosts" configuration in "appsettings.Development.json" and the app now works.

**Comment by butterngo** [comment]
@BrennanConroy Thank you, it's working with me.
