### ISSUE TITLE
[Question] - Owin Authentication Middleware for ASP.NET Core 3.0

### ISSUE THREAD

**Issue by sujayvsarma** [aspnet/AspNetCore#11735]
This is a multi-part question/request.

1. Where is all the Owin authentication middleware (stuff that used to live in `Microsoft.Owin.Security.*` packages) for ASP.NET Core 3.0 ? The `Microsoft.Owin.Security` stuff seems to be targeted at Framework -- multiple packages fly down targeted to Framework !

2. When is the documentation going to be updated to use the (hopefully updated) ASP.NET Core 3.0 (+ .NET Core 3.0) equivalents to these libraries ?

**Comment by blowdart** [comment]
There is _nothing_ Owin for Core. There never has been. They're all in `Microsoft.AspNetCore.Authentication`

There's no functional or namespace changes to any authentication middleware in 3.0, so the [2.x documentation](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-2.2) should work as is.

**Comment by sujayvsarma** [comment]
Ah, thank you. Closing the issue!
