### ISSUE TITLE
IdentityUser could not be found

### ISSUE THREAD

**Issue by lailaDev** [aspnet/AspNetCore#11746]
I installed 
 <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0-preview6.19307.2" /> to use IdentityUser, but i get the following error: IdentityUser could not be found, is it normal in this version?

**Comment by blowdart** [comment]
Where do you get this error? Can you show us some code?

**Comment by lailaDev** [comment]
![Capture](https://user-images.githubusercontent.com/50982899/60498473-efa41680-9cb6-11e9-92e5-428203ad9a22.PNG)


You can see my attached file.

**Comment by neoffer** [comment]
same problem
