### ISSUE TITLE
Blazor VSIX regression - now contains no project templates

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#11743]
The current `Microsoft.VisualStudio.BlazorExtension.vsix` coming out of CI no longer contains any project templates, so it's not very useful!

I *think* this regression was introduced in this PR: https://github.com/aspnet/AspNetCore/pull/11116. Apparently, that PR was a step towards migrating to Arcade.

I found that it can be fixed by removing the newly-introduced `'$(IsPackable)' == 'true'` condition, as I have done [in this branch](https://github.com/aspnet/AspNetCore/compare/stevesa/attempt-fix-for-blazor-vsix). The [resulting build artifact](https://dev.azure.com/dnceng/public/_build/results?buildId=245328) is correct.

However that fix on its own isn't sufficient, because then the Windows ARM build fails. I don't know how these builds interact with Nate's new `'$(IsPackable)' == 'true'` condition, or what the true fix is meant to be, so this needs to be handled by the build team.

@dougbu @JunTaoLuo Can you make whatever change is needed to fix this build regression in the way you want it to be fixed?

**Comment by SteveSandersonMS** [comment]
Also cc @danroth27 @mkArtakMSFT since this is likely to impact pre7 verification work this week.

**Comment by dougbu** [comment]
How exactly is the resulting package broken? Feel free to open a PR and confirm it fixes the problem you're seeing.

FYI one of the comments in #11116 mentions removing a "dummy" Microsoft.AspNetCore.Blazor.Templates.dll file from the VSIX.

**Comment by SteveSandersonMS** [comment]
> How exactly is the resulting package broken

It's broken in that it contains no project templates.

> Feel free to open a PR and confirm it fixes the problem you're seeing.

As described above, I've made a suggested change that does indeed fix the problem, while also causing a different build problem. So now I need the build team to determine what the right fix is.

I don't think that removing `Microsoft.AspNetCore.Blazor.Templates.dll` from the VSIX affects this either way.

**Comment by dougbu** [comment]
Probably need to add `Condition=" '$(TargetOsName)' == 'win' AND '$(TargetArchitecture)' != 'arm' "`. Haven't looked deep enough to see if the first part of the condition is needed; suspect the project is already built only on Windows.

**Comment by SteveSandersonMS** [comment]
OK thanks. Trying that out in https://github.com/aspnet/AspNetCore/pull/11748

**Comment by danroth27** [comment]
@phenning Could this have been broken by the removal of the package GUIDs from the templates?: https://github.com/aspnet/AspNetCore/pull/11707

**Comment by phenning** [comment]
No, that removal should have nothing to do with your build system.

**Comment by SteveSandersonMS** [comment]
Fixed in https://github.com/aspnet/AspNetCore/pull/11748
