### ISSUE TITLE
[Question] - Blazor - How to auto recompile on save to .razor file

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#11745]
For a Blazor client project (served up to the browser from an asp.net core host) opened in Visual Studio 2019 Preview, how do I make it so that when I save changes to a `razor` file in the client project, it automatically builds an updated `dll` - so that all I have to do is then reload the page to see the change?

Thank you.

**Comment by RemiBou** [comment]
I do it using "dotnet watch build" for this and I added razor extension to the watch list like here : 

https://github.com/RemiBou/Toss.Blazor/blob/master/Toss.Client/Toss.Client.csproj

```xml

  <ItemGroup>
    <!-- extends watching group to include *.razor files -->
    <Watch Include="**\*.razor" />
  </ItemGroup>
```

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @RemiBou!

Also, I think `.razor` might be in the default list of watched extensions these days.

**Comment by dazinator** [comment]
Thanks - this may work, but it completely bypasses VS in terms of how one would typically launch a project. So coming back to VS 2019 - how would one launch a solution, containing 2 projects (one for the asp.net core host, and the other for the blazor client), where the host is the startup project, but as you make changes to the client `.razor` files the client project is rebuilding?

**Comment by SteveSandersonMS** [comment]
I agree it would be a good feature.

However, it's not a feature that currently exists when launching from VS. It's something we're considering for the future.

**Comment by dazinator** [comment]
Ok thanks.

I've created a sample that you can run in VS [here](https://github.com/dazinator/NetPack.Samples/tree/blazor-reload/src) which has hot reload of a hosted blazor client application.

It reloads almost instantly when changes to static files are made (i.e in the client projects wwwroot folder). If you change `.razor` files though, it takes a bit longer for the page to reload as it must wait for a `dotnet build` to complete.

This sample will be useful for anyone that just wants to run from VS (with or without debugger attached) and have things reloading without having to have a seperate terminal do `dotnet watch`.

**Comment by dazinator** [comment]
One thing I have noticed - which can be seen with `dotnet watch build` - if you change a .razor file, the subsequent build takes approx 10 seconds to complete. This seems a long time to wait to see some categories of changes- for example a purely static html tweak.

**Comment by SPWwj** [comment]
> I do it using "dotnet watch build" for this and I added razor extension to the watch list like here :
> 
> https://github.com/RemiBou/Toss.Blazor/blob/master/Toss.Client/Toss.Client.csproj
> 
> ```
>   <ItemGroup>
>     
>     <Watch Include="**\*.razor" />
>   </ItemGroup>
> ```

this approach dont work for blazorhosted template.

**Comment by dazinator** [comment]
@SPWwj what do you think about the "wait time" it takes to rebuild after making a minor html change? Is blazor productive for you in that regard?

**Comment by SPWwj** [comment]
> @SPWwj what do you think about the "wait time" it takes to rebuild after making a minor html change? Is blazor productive for you in that regard?

thanks for response
I have try 'wait time' but waited for few minutes see nothing happen. Watcher reponses to normal blazor and blazorserverside template instantaneously by default.(not need to add include to csproj file).
blazor definitely a great thing for .net developer as it elimated the need for us to learn new spa framework.
