### ISSUE TITLE
Launch url in webapi incorrect

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#11750]
### Describe the bug
The new API template now serves WeatherForcasts, which doesn't seem intentional. Also, the launch URL when F5'ing on the project serves the incorrect URL instead of the API.
### To Reproduce
1. Using this version of ASP.NET Core 3.0.0-preview7.19351.2
2. File...new...webapi

### Expected behavior
The api launches and we receive a 404.

### Screenshots
![image](https://user-images.githubusercontent.com/8302101/60446824-096e2c80-9bd7-11e9-9bf4-e68cb5fc8e3d.png)
![image](https://user-images.githubusercontent.com/8302101/60446863-1854df00-9bd7-11e9-896a-d9f15700febf.png)
![image](https://user-images.githubusercontent.com/8302101/60446885-23a80a80-9bd7-11e9-8ffc-832be874d37a.png)

cc @pranavkm @danroth27 for changes.

**Comment by mkArtakMSFT** [comment]
Thanks @jkotalik.
The change to have `WeatherForecast` in this template was intentional. As for the start url is incorrect, that's a valid issue.

**Comment by mkArtakMSFT** [comment]
So looks like we have already an issue for the launchSettings part https://github.com/aspnet/AspNetCore/issues/11699, which will be addressed during preview9.

Thanks!

**Comment by jkotalik** [comment]
@DamianEdwards @davidfowl are we cool with changing the webapi in 3.0?

**Comment by DamianEdwards** [comment]
@jkotalik changing to weather controller was the plan, yes.
