### ISSUE TITLE
401 on OPTIONS xhr call when Windows Authenication is Enabled

### ISSUE THREAD

**Issue by michaelschmit** [aspnet/AspNetCore#11764]
I've been battling through this issue for a few days now, and I seem to be running into various road blocks. First, it seems as though with windows authentication enabled OPTIONS http requests get 401'ed by the browser and negotiation doesn't kick in which results in the CORS request failing (not SignalR's fault in anyway).  I've validated this fact by enabling anonymous authentication which results in a successful OPTIONS call (returns 204 with headers), but then no authentication occurs for the rest of the calls obviously.  It looks like in ASP.NET you can use system.web to set windows auth per verb, but I can't seem to find out how to do this in ASP.NET core.

In the old version of SignalR (pre-ASP.NET core) we would get around this issue using JSONP instead, but that doesn't seem to be an option anymore.

Any guidance would be appreciate.

### Additional context
ASP.NET Core 2.2 and 3.0 preview 5

**Comment by BrennanConroy** [comment]
CORS has to run before Windows Auth if you don't allow anonymous access.

In order to make this work with IIS you'll need to install and configure the [cors module](https://www.iis.net/downloads/microsoft/iis-cors-module).

**Comment by michaelschmit** [comment]
I wasn't aware of this IIS module.  With some fiddling I was able to make this work.  I appreciate the assistance.
