### ISSUE TITLE
Razor .mpack version generation for VSMac

### ISSUE THREAD

**Issue by KirillOsenkov** [aspnet/AspNetCore#11761]
Currently it seems that the .mpack for VSMac addin is produced with version 42424242. There used to be an MSBuild property `DotNetUseShippingVersions` which would generate a proper version such as `3.0.0.0`. 

Also we need the Razor assemblies inside the .mpack to have proper versions and not 42.42.42.42 otherwise they fail to load because we reference the wrong version.

cc @davidkarlas

**Comment by rynowak** [comment]
Are you looking at local builds or the official build?

**Comment by KirillOsenkov** [comment]
The CI that produces the .mpack, but it would be nice to know what to pass on the command line to emulate the official build locally as well. We need to be able to produce the right versions as 42 is useless to us.

**Comment by KirillOsenkov** [comment]
I'm guessing the logic somewhere here is relevant:
https://github.com/dotnet/arcade/blob/d71c43c7efee344c50724e8a94251f56b2a71194/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L18-L25

We probably need to somehow tie AddinVersion to this generated build number.

**Comment by rynowak** [comment]
Here's what I see from a recent build: https://dev.azure.com/dnceng/internal/_build/results?buildId=245555&view=results

![image](https://user-images.githubusercontent.com/1430011/60462810-2ae30e80-9bff-11e9-88c9-ca0333bb7c7e.png)

```xml
<Addin id="RazorAddin" namespace="Microsoft.VisualStudio.Mac" version="8.0.20190701.2" name="Razor Language Services" author="Microsoft" description="Language services for ASP.NET Core Razor" category="Web Development">
<Runtime>
<Import assembly="Microsoft.VisualStudio.Editor.Razor.dll" />
<Import assembly="Microsoft.CodeAnalysis.Razor.Workspaces.dll" />
<Import assembly="Microsoft.AspNetCore.Razor.Language.dll" />
<Import assembly="Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.dll" />
<Import assembly="Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.dll" />
<Import assembly="Microsoft.AspNetCore.Mvc.Razor.Extensions.dll" />
<Import assembly="Microsoft.CodeAnalysis.Razor.dll" />
<Import assembly="Microsoft.VisualStudio.Mac.LanguageServices.Razor.dll" />
<Import assembly="Microsoft.VisualStudio.Mac.RazorAddin.dll" />
</Runtime>
<Dependencies>
<Addin id="::MonoDevelop.Core" version="8.0" />
<Addin id="::MonoDevelop.Ide" version="8.0" />
</Dependencies>
</Addin>
```

![image](https://user-images.githubusercontent.com/1430011/60462866-5239db80-9bff-11e9-8626-5fe8d6fe06f5.png)

**Comment by KirillOsenkov** [comment]
Oh interesting! That's what I need. I was looking here: https://github.com/aspnet/AspNetCore-Tooling/pull/697/checks?check_run_id=155788066

**Comment by KirillOsenkov** [comment]
Now the question is: what did your build do right and what did my build do wrong? :)

**Comment by KirillOsenkov** [comment]
In other words, I need to produce an .mpack with the correct versions (as in your screenshots above) for this PR: https://github.com/aspnet/AspNetCore-Tooling/pull/697

and in the future in all other places of course.

**Comment by NTaylorMullen** [comment]
> In other words, I need to produce an .mpack with the correct versions (as in your screenshots above) for this PR: [aspnet/AspNetCore-Tooling#697](https://github.com/aspnet/AspNetCore-Tooling/pull/697)
> 
> and in the future in all other places of course.

O_o I must be missing something. Why do you need to produce the mpack separately? 😄

**Comment by KirillOsenkov** [comment]
For debugging purposes when making local changes :) It's not just for this PR. 

From trial and error we've found that `build.cmd /p:OfficialBuildId=20190702.01 /p:VersionSuffix=` seems to do what we want, but it fails the build after producing the .mpack, so it feels like it's not the right solution.

There's an e-mail thread with @tmat going on, I'll update the issue when we have a good solution.

**Comment by KirillOsenkov** [comment]
I've tried again and `build -binaryLog /p:DotNetUseShippingVersions=true` seems to be working fine. Not sure why it wasn't working before.

Apologies for the noise.

**Comment by NTaylorMullen** [comment]
> For debugging purposes when making local changes :) It's not just for this PR.

Ah, just so you know we publish all of the symbols to symweb with source link so unless you need debug optimized bits that should definitely get you 90% of the way.
