### ISSUE TITLE
Possible Bug with Razor Compiler regarding the RenderTreeBuilder

### ISSUE THREAD

**Issue by Puthranps** [aspnet/AspNetCore#11762]
### Describe the bug
Error relating to the generated .razor.g.cs file where the RenderTreeBuilder is throwing errors such as: "The name 'builder' does not exist in the current context"

### To Reproduce
For reproducing I'm not sure on the steps so I'll try my best to explain how the issue came about for me. 

From the default Blazor server side template

- Add a Components folder 
- Go to Shared/NavMenu.razor and remove weather page from the menu
- Add new NavLink and create a page for corresponding NavLink in the Pages directory
- Create a sample Component and use that for the new NavLink page and use BlazorStrap for this component. 
- Build and test the output

### Expected behavior
Build with the RenderTreeBuilder fully instantiated and displaying a web page.
### Screenshots
![image](https://user-images.githubusercontent.com/20980332/60464166-9ed2e600-9c02-11e9-8116-9b90d4070dbc.png)

### Additional context
Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/20980332/60464142-911d6080-9c02-11e9-95a7-908e0c25a89d.png)

- Additionally I am using some libraries for Blazor such as BlazorStrap and Microsoft.Azure.DocumentDB

https://chanan.github.io/BlazorStrap/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Puthranps.
Can you please provide a small repro, as it's not really clear the exact steps to get to this issue. Is it any component from BlazorStrap or a specific one?
It would be ideal, if you could share a project hosted as a repository in GitHub.

**Comment by danroth27** [comment]
@Puthranps shared the problematic code with me. It looks like this is an issue with HTML comments in `@functions` blocks.

```razor
@functions {
    const string AzureFuncTriggerUri = "";
    <!-- List<Release> infraRolling; -->
    Dictionary<string, List<Release>> _dict;

    protected override void OnInit()
    {
        var keyVault = new KeyVaultStore(false);
        string endPointUri = keyVault.GetSecretAsString("endpointurl");
        string primaryKey = keyVault.GetSecretAsString("cosmosdbprimarykey");
        var cosmosHelper = new CosmosDBHelper(endPointUri, primaryKey);
        _dict = new Dictionary<string, List<Release>>
                                        {
                                            {"Infrastructure", null},
                                            {"KeyDelivery", null},
                                            {"Telemetry", null},
                                            {"MediaProxy", null},
                                            {"RPv2", null},
                                            {"Streaming", null}
                                        };
        foreach (var key in _dict.Keys) 
        {
            _dict[key] = cosmosHelper.QueryReleaseEntries(key);
        }
    }
}
```

Results in this broken code gen:

```csharp
#line default
#line hidden
    [Microsoft.AspNetCore.Components.Layouts.LayoutAttribute(typeof(MainLayout))]
    [Microsoft.AspNetCore.Components.RouteAttribute("/releases")]
    public class Releases : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
        }
        #pragma warning restore 1998
#line 41 "C:\Users\daroth\Desktop\Frontend\Frontend\Pages\Releases.razor"
            
    const string AzureFuncTriggerUri = "";

#line default
#line hidden
        builder.AddMarkupContent(0, "    \r\n");
#line 44 "C:\Users\daroth\Desktop\Frontend\Frontend\Pages\Releases.razor"
    Dictionary<string, List<Release>> _dict;
```

**Comment by Puthranps** [comment]
@mkArtakMSFT If you want I can email or message you on teams for a zip file

**Comment by mkArtakMSFT** [comment]
Thanks @Puthranps. I have it now 👍

**Comment by Puthranps** [comment]
The bug seems to do with html comments being in the @functions block because now my project builds fine @mkArtakMSFT @danroth27

**Comment by mkArtakMSFT** [comment]
We're closing this as we simply should not support this.
