### ISSUE TITLE
VS Suggestion

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#11765]
Hello Team;

Within Visual Studio for Blazor apps, I'd like to suggest two different folders:
Pages
Components

Components would hold the individual blocks or components to represent an individual component.

Pages however represent the full size view or page that is made up of many components.

This separation and guideline helps organizing large number of components and pages.
Taking it one step further, is to bring Area into Blazor too.

Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @BenHayat.
This is not something we plan to do in the near future. We would like rather to observe the community feedback on the existing templates when they ship, to get a better idea how people are using it and what are the pain points. Then only we will be able to identify areas for future improvements in templates.
As for the areas, could you please file a separate issue, so we track things better? Thanks!
