### ISSUE TITLE
Razor class library and assembly name with points

### ISSUE THREAD

**Issue by alexandrereyes** [aspnet/AspNetCore#11763]
Since preview 6, static assets are supported in Razor Class library, but it doesn't work if you have point in assembly name, for example:
MyCompanyName.Components
In the browser, 404 is show f you try to referenced in the main page:
`<script src="_content/MyCompanyName.Components/hello.js"></script>`

**Comment by danroth27** [comment]
This should now be fixed by https://github.com/aspnet/aspnetcore-tooling/pull/700.
