### ISSUE TITLE
Core 2.2 - Integration tests -  Bearer Token length restriction (756 chars)

### ISSUE THREAD

**Issue by bluedog13** [aspnet/AspNetCore#11783]
Integration test fails when I have to supply a bearer token and the token length is greater that 756 characters. 

    _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", 
            _token.Text));

results in 
System.FormatException : The format of value 'Bearer S0.....  is invalid exception.

However, the below works (but the token is invalid at this point)

    _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", 
            _token.Text.Substring(0,756));

Is there anything extra that needs to be done in regards to token length for integration tests?

**Comment by Eilon** [comment]
@Tratcher - is this Security, HttpClientFactory, or something in CoreFX?

**Comment by Tratcher** [comment]
Can you give the full stack trace?

**Comment by Tratcher** [comment]
Are you sure it's a length issue and not a format issue? E.g. is the character at index 756 invalid? It's pretty strange a truncated token would be considered valid. Can you give a sample token without any personal information? Or send it to the e-mail in my profile?

AuthenticationHeaderValue doesn't verify the length or format of the token.
https://github.com/dotnet/corefx/blob/86ef1c507faa24ca4406b9e8ebfede2a2ae52100/src/System.Net.Http/src/System/Net/Http/Headers/AuthenticationHeaderValue.cs#L63

Servers care about header lengths, but their limits are much higher and you'd get a different error.

JwtBearer doesn't care.
https://github.com/aspnet/AspNetCore/blob/8a7508d8183968d1b96d259cf8bcc5bbb85981b5/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L74

There could be some limit in IdentityModel, but we don't pass them the "Bearer " piece of the header.

**Comment by bluedog13** [comment]
The 756th character is  "," and hence the error and not due to the length of the token.  

@Tratcher, thanks for your comment in regards to 756th character that made me look into it.  

Is there a way  to have this command ignored while running the integration test server WebApplicationFactory<T> ignore the comma? 

Below is the stack trace

----- Inner Stack Trace -----
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, IEnumerable`1 values)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, IEnumerable`1 values)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler.CopyRequestHeaders(HttpRequestHeaders originalRequestHeaders, HttpRequestHeaders newRequestHeaders)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

**Comment by Tratcher** [comment]
This is unrelated to WebApplicationFactory, it's an HttpClient error. Are you sure that token is valid?

You can bypass that check by calling TryAddWithoutValidation
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpheaders.tryaddwithoutvalidation?view=netframework-4.8#System_Net_Http_Headers_HttpHeaders_TryAddWithoutValidation_System_String_System_String_

**Comment by bluedog13** [comment]
The token is valid because it's a customized token as per our internal requirements.  I tried "TryAddWithoutValidation" but it does not seem to make the call to the controller and fails. 

Strange part is, when the request is made via POSTMAN or Swagger, the token works.  I suppose Integration test Http Client has extra checks for the token format.

**Comment by Tratcher** [comment]
Nevermind, I didn't read that stack trace correctly. `Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler.CopyRequestHeaders` should not be calling Add, it should be calling TryAddWithoutValidation. That's an MVC bug we'll need to address.

The trouble with comma is that it's the reserved separator between header values. Many header parsing libraries will split your token into two headers. You should re-think using comma.

https://tools.ietf.org/html/rfc2616#section-4.2
"   It MUST be possible to combine the multiple header fields into one
   "field-name: field-value" pair, without changing the semantics of the
   message, by appending each subsequent field-value to the first, each
   separated by a comma."

And the Authorization header only allows commas in a specific format:
https://tools.ietf.org/html/rfc7235#appendix-C
"   credentials = auth-scheme [ 1*SP ( token68 / [ ( "," / auth-param )
    *( OWS "," [ OWS auth-param ] ) ] ) ]"
(I'd have to stare at that BNF for a while to work out exactly where they're allowed...)
