### ISSUE TITLE
[JWT] [AudienceValidator] Needs Request details during token validation! 

### ISSUE THREAD

**Issue by Yeganloo** [aspnet/AspNetCore#11796]
### The "AudienceValidator" delegate need to pass the url referrer of current request!

In my case, there is no such a thing as trusted audience! all of them can be valid but no one may use the token that is generated for someone else! so plan to implement the AudienceValidator delegate and compare the token audience with current url referrer, but there is no official way to access current request or its referrer!

**Comment by blowdart** [comment]
Referrer is not a security mechanism, nor is it part of any standard JWT validation mechanism.

**Comment by Yeganloo** [comment]
It's not about standards, and i'm not talking about Token structure. You can look it as a user defined claim, instead of header part one!
There is a usage scenario and as i told, it's a restriction defined by project business. This time it is Url referrer for me but it seems to be useful if request details be accessible during all steps of Token validation process!

**Comment by blowdart** [comment]
This isn't something we're set up for, nor is [identity model](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet), which provides the validation functions. They'd have to provide a way to pass extra, random parameters before we could implement anything like this.

**Comment by Yeganloo** [comment]
## A new Scenario that needs Request detail, during Token validation

In a SPA application with comment functionality (or something like that), worst place to store a refresh toke is local storage! so you will store it in a http-only secure cookie. Now during the token validation, you find-out that token is expired! you already have the refresh-token in request but you force the client-app to resend a new request with that refresh-token, after getting a 401 error!
Finally you have process do 3 request and responses that can be handle by 2 (using 425 status code) or 1 (store token in cookie too! i do not recommend).

**Comment by blowdart** [comment]
We're closing this issue as the behaviour discussed seems to be by design.

**Comment by Yeganloo** [comment]
Dose it mean that you do not plan to support this kind of design?
And it is one of your rules that JWT validation should not be related to any request data except it self?
