### ISSUE TITLE
Angular SPA Template App served from dist in Dev mode

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#11797]
<p>I was wondering why my code changes weren't showing up when I modified the ClientApp code. Usually it refreshes the page. <br><br>No matter what change I made I was still getting old code.<br><br>After looking at the code, I determined it was serving the client app from the ClientApp/dist folder. This is while I was running in Development mode. I deleted the dist folder and everything started working again, reloading, etc.<br><br>The dist folder was there because I had done an ng build from a command window. Sometimes when I do a publish and it builds in production I can't see the errors so I run the client app build from a command line.<br><br>I expected the client side app would only be served from Dist when it was in production mode.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/344169/angular-spa-template-app-servicing-from-dist.html
VSTS ticketId: 691952_
_These are the original issue comments:_

Artak Mkrtchyan on 6/26/2019, 05:03 PM (5 days ago): <markdown><p>Thanks for contacting us. This is actually by-design. The Angular project templates are configured to serve client app content from the <code>ClientApp/dist</code> folder in production, and this is configured in the <code>Startup.ConfigureServices()</code> method. In Development environment these are compiled dynamically to enable Hot Reload.</p>
</markdown>
Bob Archer on 6/27/2019, 07:00 AM (5 days ago): <p>Ok, you totally didn't read what I wrote. I said it was pulling from /Dist in DEVELOPMENT mode. It wasn't getting my changes or hot reloading.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi Bob. We'll review the issue one more time and get back to you soon.

**Comment by darkflame0** [comment]
I have a same issue
if "./ClientApp/dist" exists ,the client app always run in production mode when I debug my program

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @darkflame0. We will hopefully get to this next week. I'm not certain that is the right thing to do, so can't comment at the moment. If you are, feel free to send us a PR, and we'll accept it, if our investigation confirms that is the right thing to do.

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT I was able to replicate this locally and the `if(env.IsProduction())` fix seems totally reasonable to me given the alternatives I could think of:
1. Putting a condition in `UseSpaStaticFiles` would take away peoples ability to serve static files in dev if they wanted to.
2. Write a `ISpaStaticFileProvider` which returns a null [IFileProvider](https://github.com/aspnet/AspNetCore/blob/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0/src/Middleware/SpaServices.Extensions/src/StaticFiles/DefaultSpaStaticFileProvider.cs) when in production. This again removes developer choice, and could be achieved by devs by writing their own ISpaStaticFileProvider.

This doesn't seem to reproduce for react.
