### ISSUE TITLE
Clear Unused Runtime Compiled Views

### ISSUE THREAD

**Issue by joetherod** [aspnet/AspNetCore#11800]
My app reads its razor views from the database. The database of these razor views are managed via a tenant based cms application. This is accomplished using the IFileProvider, IViewLocationExpander, IDirectoryContents when I configure the RazorViewEngineOptions at Startup.

Is there a way to clear these runtime compiled views on demand or if the virtual file view is not used after a certain amount of time?

It seems that the memory usage of the app goes up gradually due to changes made to these views. A change basically initiates a new view. The existing view is not used. This is done by change to the virtual path of the view dynamically when it is retrieved.

If I used the same path of the file, the changes of file are not retrieved. Unless there is way to force the recompilation of an existing path due to a change?

Please help.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by joetherod** [comment]
I tried implementing the ChangeToken, but it doesnt seem to get firedvia the Watch in the Custom FileProvider.
How do I get the Watch to fire?

**Comment by joetherod** [comment]
I was able to get the Watch method to work in the IFIleInfo class.
I needed this set:

options.AllowRecompilingViewsOnFileChange = true;
