### ISSUE TITLE
Update Offline support page for the templates

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#11811]
We've made a lot of changes to the templates during last several milestones.
It's time to update the https://github.com/aspnet/AspNetCore/wiki/Offline-execution-support-for-Web-templates page to reflect the up to date state of the templates and their dependencies.

**Comment by mkArtakMSFT** [comment]
This can happen after Preview8 Code Complete date.

**Comment by ryanbrandenburg** [comment]
That page is updated.
