### ISSUE TITLE
VS: Significant lag time on adding a new component file to an already loaded project.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#11816]
### Describe the bug
Trying to add a new Razor component results in a significant amount of time waiting for `@code` to highlight/the file to be recognized as a component file. This would be expected when the project is opened for the first time in the IDE but not on subsequent adds of a Razor component. It happens every time.

### To Reproduce
PreReqs:
1. Use latest internal VS (master branch)
2. Use preview7+ SDK

1. Create a new Blazor serverside project
2. Right click on the pages folder and click add new item
3. Select the Razor Component item template.
4. See `@code` not become yellow for several seconds.

### Expected behavior
The file should be recognized as a component file immediately on an already loaded project.

### Screenshots
![image](https://user-images.githubusercontent.com/2008729/60548757-b3cd7900-9cd7-11e9-9d9e-65c575155da2.png)

### Additional context
I investigated this and for some reason we're telling WTE that `@code` should be C# but we have a valid configuration of 3.0. Sooo, this shouldn't be happening.

**Comment by mkArtakMSFT** [comment]
If this will take a day to fix, we probably will take it. Otherwise - will do it later.
