### ISSUE TITLE
Update default project names for ASP.NET Core related project templates

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#11820]
Update the "defaultName" value in *template.json* for the ASP.NET Core templates as follows:

- “gRPC Service” -> GrpcService
- “Worker Service” -> WorkerService
- “Blazor Server App” -> WebApplication
- "Blazor WebAssembly App" -> WebApplication
- “Razor Class Library” -> RazorClassLibrary
- "Razor Pages" -> WebApplication
- "MVC" -> WebApplication
- "Empty" -> WebApplication
- "Web API" -> WebApplication

**Comment by JamesNK** [comment]
@JunTaoLuo will look at the gRPC template name.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg isn't the rename for Blazor and Razor projects in this list happening already?

**Comment by JunTaoLuo** [comment]
@danroth27 what's the recommendation for razor class library? The proposed name looks identical to the current one.

**Comment by danroth27** [comment]
@JunTaoLuo For some reason the Razor Class Library template starts with "RazorClassLibrary11" as the default project name instead of "RazorClassLibrary1".

**Comment by danroth27** [comment]
To give a bit more background here, VS is planning to make a change to honor the "defaultName" values in *template.json* for our templates. The "defaultName" values should *not* have a numerical suffix - VS will take care of adding that.

**Comment by JunTaoLuo** [comment]
Ah I see, I'll make the necessary changes
