### ISSUE TITLE
Delegates in directive attribute values still require @() for proper C# intellisense

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#11826]
Notice the difference in coloring between `@onclick` and `@onblur`. This code compiles and runs fine but the design time experience isn't good without the `@(...)`

![image](https://user-images.githubusercontent.com/1579269/60554835-36f9c980-9cee-11e9-86c8-586346036c10.png)

@NTaylorMullen and I investigated this a little bit. It is because of how Razor splits the delegate expression into multiple csharp expression tokens at the tag helper attribute rewriting layer. This is how it has always worked. We'll need to do work to properly support this in design time.

**Comment by mkArtakMSFT** [comment]
Let's see whether there is a simple solution we can come up with. If so, and it's trivial - we'll consider it as part of preview 9.
