### ISSUE TITLE
MVC: ViewBag, ViewData and Model cannot store Anonymous object

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#11838]
### Describe the bug
ViewBag, ViewData and Model cannot store Anonymous object

### To Reproduce
1. create a mvc project
2. create an anonymous object in ViewData/ViewBag or pass data via Model which has a dynamic type of property.
3. Access members in the object in Views
4. RuntimeBinderException: 'object' does not contain a definition for 'A'

For example:
In controller:
```csharp
public class MyModel
{
    dynamic Test;
}
public class HomeController : Controller
{
    public IActionResult Index()
    {
        var x = new { A = 444 };
        ViewData["X"] = x;
        ViewBag.X = x;
        var model = new MyModel() { Test = x };
        return View(model);
    }
}
```
In View:
```razor
@model MyModel

@Model.Test.A // exception was thrown
@ViewBag.X.A  // exception was thrown
@(((dynamic)ViewData["X"]).A) // exception was thrown
```

However, in debug session I can do see the type and member "A" of the anonymous object x.
![image](https://user-images.githubusercontent.com/14960345/60582920-5101dd80-9dbc-11e9-93c5-23210ce0922d.png)

Please fix this bug.

### Expected behavior
No exceptions were thrown.

**Comment by rynowak** [comment]
Your complaint is actually about the default behavior of `dynamic` in C# when applied to a normal .NET type. You could have this problem using dynamic even if MVC is not involved. See: https://stackoverflow.com/questions/16173378/complex-anonymous-objects-to-dynamic-public-properties

dynamic and anonymous types don't really work well together.
