### ISSUE TITLE
API call order matters but it shouldnt

### ISSUE THREAD

**Issue by Meai1** [aspnet/AspNetCore#11833]
dotnet 2.2

This is a hellish API, I have to experiment with the order of statements for options:

works:

```
listenOptions.Protocols = HttpProtocols.Http2;
listenOptions.UseHttps(...)
listenOptions.ConnectionAdapters.Add(new TlsFilterAdapter());
// Still one error: HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint
```

does not work:

```
listenOptions.UseHttps(...)
listenOptions.Protocols = HttpProtocols.Http2;
listenOptions.ConnectionAdapters.Add(new TlsFilterAdapter());
// Error: TlsHandshakeFeature inside OnConnectionAsync always null
```

does not work:

```
listenOptions.Protocols = HttpProtocols.Http2;
listenOptions.ConnectionAdapters.Add(new TlsFilterAdapter());
listenOptions.UseHttps(...)
// Error on everything: "HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint."
```

**Comment by Tratcher** [comment]
What is TlsFilterAdapter doing?

The ordering issue between Protocols and UseHttps is because UseHttps captures the protocols in order to do ALPN. We could address that by making it a lazy capture (e.g. Func).
https://github.com/aspnet/AspNetCore/blob/3c0fb1a3f8609aae3165d43cb61fed10d9e1bf4f/src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs#L220

**Comment by Meai1** [comment]
TlsFilterAdapter is the copy pasted thing floating around, I added another null check and check for Rc4 which dont seem to be doing anything btw (still getting Rc4 ciphers shown as accepted in ssllabs scan so I dont know what the point is then)
Also no idea what the IsHttps thing is doing, doesn't seem to be doing anything whether it's true or false. No docs on it exist.

```
private class TlsFilterAdapter : IConnectionAdapter
{
    public bool IsHttps => false;

    public Task<IAdaptedConnection> OnConnectionAsync(ConnectionAdapterContext context)
    {
        var tlsFeature = context.Features.Get<ITlsHandshakeFeature>();

        // Throw NotSupportedException for any cipher algorithm that you don't
        // wish to support. Alternatively, define and compare
        // ITlsHandshakeFeature.CipherAlgorithm to a list of acceptable cipher
        // suites.
        //
        // A ITlsHandshakeFeature.CipherAlgorithm of CipherAlgorithmType.Null
        // indicates that no cipher algorithm supported by Kestrel matches the
        // requested algorithm(s).
        if (tlsFeature == null || tlsFeature.KeyExchangeAlgorithm == ExchangeAlgorithmType.None || tlsFeature.CipherAlgorithm == CipherAlgorithmType.None || tlsFeature.CipherAlgorithm == CipherAlgorithmType.Null) 
        {
            throw new NotSupportedException("Prohibited cipher: " + tlsFeature.CipherAlgorithm);
        }

        return Task.FromResult<IAdaptedConnection>(new AdaptedConnection(context.ConnectionStream));
    }

    private class AdaptedConnection : IAdaptedConnection
    {
        public AdaptedConnection(Stream adaptedStream)
        {
            ConnectionStream = adaptedStream;
        }

        public Stream ConnectionStream { get; }

        public void Dispose()
        {
        }
    }
}
```

I mean I'm trying to get some of these errors removed in the ssllabs scan but it isnt working. All the uptime monitors report my server to be "down" even though it's up and browsers can access it, I tried 3 different services. They all show me a certificate validation error but it's working fine in visible browsers so clearly this is some kind of deeper issue. The only tool that shows these errors is the ssllabs .
I'm getting a big red 'F' on that site with aspnet core and I have no idea how to fix it. I have a standard certificate from gandi, I wouldnt know how this is my fault and none of the settings I can do in dotnet 2.2 improve anything. Yes I've read that in dotnet 3.0 I can finally possibly maybe customize the ciphersuites but somehow I doubt that it will be enough. Here are all the cipher suites that ssllabs show me that aspnet core is offering which are marked as RED and INSECURE:
```
TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA (0xc017)   INSECURE 
TLS_RSA_WITH_RC4_128_MD5 (0x4)   INSECURE 
TLS_RSA_WITH_RC4_128_SHA (0x5)   INSECURE 
TLS_ECDHE_RSA_WITH_RC4_128_SHA (0xc011)   ECDH secp521r1 (eq. 15360 bits RSA)   FS   INSECURE 
TLS_ECDH_anon_WITH_RC4_128_SHA (0xc016)   INSECURE 
TLS_ECDH_anon_WITH_AES_128_CBC_SHA (0xc018)   INSECURE 
TLS_ECDH_anon_WITH_AES_256_CBC_SHA (0xc019)   INSECURE 
TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA (0xc017)   INSECURE 
TLS_RSA_WITH_RC4_128_MD5 (0x4)   INSECURE 
TLS_RSA_WITH_RC4_128_SHA (0x5)   INSECURE 
TLS_ECDHE_RSA_WITH_RC4_128_SHA (0xc011)   ECDH secp521r1 (eq. 15360 bits RSA)   FS   INSECURE 
TLS_ECDH_anon_WITH_RC4_128_SHA (0xc016)   INSECURE 
TLS_ECDH_anon_WITH_AES_128_CBC_SHA (0xc018)   INSECURE 
TLS_ECDH_anon_WITH_AES_256_CBC_SHA (0xc019)   INSECURE 
```

There are a ton more that are considered weak but even Google's scan has weak ciphers so that would be fine I guess. As you can see, Google has vastly restricted the number of ciphers that the server offers:
https://www.ssllabs.com/ssltest/analyze.html?d=google.com&s=216.58.195.78&hideResults=on

**Comment by Tratcher** [comment]
The list of available ciphers is controlled by the OS, all you're doing here is rejecting connections after the fact.
https://docs.microsoft.com/en-us/windows-server/security/tls/manage-tls#configuring-tls-cipher-suite-order

Yes there's a 3.0 feature for managing this in the application, but it only works on Linux.

**Comment by Meai1** [comment]
I only use Linux for this stuff anyway but I cant switch to 3.0 now. On other C servers I remember that I was able to set the ciphers that I wanted to use directly through openssl calls.

**Comment by anurse** [comment]
To make this order independent, we think it's just a matter of moving the place where we read `listenOptions.Protocols` to *inside* the `.Use`, to avoid capturing the value early and making the API order-dependent: https://github.com/aspnet/AspNetCore/blob/3c0fb1a3f8609aae3165d43cb61fed10d9e1bf4f/src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs#L215-L229

**Comment by davidfowl** [comment]
FYI @Meai1 this API is completely change in 3.0 but the https adpater still has that bug.

**Comment by Tratcher** [comment]
This was fixed by https://github.com/aspnet/AspNetCore/pull/13202
