### ISSUE TITLE
Model Binding build in support for Trim or something like value transform

### ISSUE THREAD

**Issue by John0King** [aspnet/AspNetCore#11837]
### Is your feature request related to a problem? Please describe.
The  model binding feature of MVC is great , but not friendly for `string.Trim()`.
for example : we should trim the username when user input(paste) the username.
There are solution's on stackoverflow,  Create a custom Model Binder for `string`, but nomally this became a global configration.

### Describe the solution you'd like

I'm hoping there's a build in Attribute that can specify the trim options

```C#
using Microsoft.AspNetCore.DataAnnotations;

public class LoginViewModel
{
    //[Trim(TrimOption.TrimStart)]
    [Trim]
    public string UserName{get;set;}
    public string Password{get;set;}
}

```

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. After reviewing this we don't think this is something we plan to bake into the framework.
