### ISSUE TITLE
Clarify that ComponentHub.OnRenderCompleted's errorMessage is untrusted

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#11843]
From https://github.com/aspnet/AspNetCore/issues/11791

Currently, `ComponentHub.OnRenderCompleted` accepts an `errorMessage` from the client, and logs it.

We should clarify this by changing the string that gets logged to something like `Error message reported by untrusted client code: {errorMessage}` instead of just `{errorMessage}`.

**Comment by javiercn** [comment]
We didn't change the string message but we added it to the docs. Covered as part of https://github.com/aspnet/AspNetCore.Docs/pull/13962/files
