### ISSUE TITLE
Remove temporary logic from BindMethods.DispatchEventAsync

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#11846]
From https://github.com/aspnet/AspNetCore/issues/11791

BindMethods.DispatchEventAsync has a comment saying "this is a temporary polyfill that doesn't do proper error handling and will be removed".

Are we able to remove this now?

**Comment by rynowak** [comment]
> One place this is called from is BindMethods.DispatchEventAsync, which comes with a comment saying "this is a temporary polyfill that doesn't do proper error handling and will be removed". Can this be removed now

Yes, this can be removed along with all of the overloads of `SetValueHandler`
