### ISSUE TITLE
Typing @inject followed by a space completes to @injectInjectAttribute  

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#11859]
Typing @inject followed by a space completes to @injectInjectAttribute.

![QN98rH5un7](https://user-images.githubusercontent.com/1874516/60609508-af0bd200-9d76-11e9-9335-909fc9e73c52.gif)

**Comment by NTaylorMullen** [comment]
Seems like a variant of https://github.com/aspnet/AspNetCore/issues/10940

**Comment by ajaybhargavb** [comment]
@NTaylorMullen, seeing as how this is related to #10940, is this something WTE should handle or is the fix going to be on our side?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen, seeing as how this is related to #10940, is this something WTE should handle or is the fix going to be on our side?

It could be either, we'll have to investigate more. If we end up marking the span right after `@inject|` as C# then it'll be our issue, otherwise it'll be WTEs

**Comment by ajaybhargavb** [comment]
I investigated this. Looks like we add a marker token at the end of `@inject|` to provide CSharp intellisense for the upcoming token. We fix this by only adding the marker token if there is whitespace after `@inject`

**Comment by rynowak** [comment]
Is this just `@inject` or all directives?

**Comment by ajaybhargavb** [comment]
`@inject` was just an example. The fix is for all extensible directives.

**Comment by ajaybhargavb** [comment]
Fixed by d953ec40c30e3dbe876bd11ad03dc72350bcf03c
