### ISSUE TITLE
Current Microsoft.AspNetCore.Authentication.MicrosoftAccounts does not support setting **prompt** query parameter

### ISSUE THREAD

**Issue by bderveni** [aspnet/AspNetCore#11863]
### Is your feature request related to a problem? Please describe.
I am trying to add the **prompt** query parameter to the AuthenticationProperties when making an authentication request to Microsoft Accounts. Version 2.2.0 - the current non-preview version of the package - does not parse this parameter when it is added to the AuthenticationProperties.Parameters dictionary. 

We need to set this parameter to prevent the authentication flow from automatically logging in when there is only one user cookie.  We want to allow our customers to select/add another account to log in with.

Behavior without a **prompt** parameter:
![image](https://user-images.githubusercontent.com/46972442/60616397-37de3a00-9d86-11e9-861b-4f49bc994a0d.png)

Behavior with a **prompt** parameter
![image](https://user-images.githubusercontent.com/46972442/60616452-5cd2ad00-9d86-11e9-8999-7c95b02002db.png)

### Describe the solution you'd like
Microsoft.AspNetCore.Authentication.MicrosoftAccounts supports adding **prompt** query parameter, for .netcore 2.2.

### Additional context
I am aware that there was [work](https://github.com/aspnet/AspNetCore/pull/11059) done to support parameters for Microsoft Accounts, and that there is a preview version of the package on [nuget](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.MicrosoftAccount/3.0.0-preview6.19307.2). However, this package has dotnet 3.0 as a dependency, which is is scheduled for GA on September. Is it possible to have a 2.2.* version of the package that support Microsoft Accounts?

**Comment by blowdart** [comment]
We generally don't back port new features, only bug or security fixes, unless there's a great demand.

**Comment by bderveni** [comment]
I am assuming this was the only request for this feature and that we have to wait until September. 

Thanks for the quick reply.

**Comment by blowdart** [comment]
I'm afraid so.

**Comment by bderveni** [comment]
@blowdart do you want me to close this, or do you guys do it?

**Comment by blowdart** [comment]
it always seems mean to have someone close their own issue :)
