### ISSUE TITLE
Blazor Client Side : iOS (Preview 6)

### ISSUE THREAD

**Issue by smjltd** [aspnet/AspNetCore#11862]
### Describe the bug
Unable to browse same Blazor Client Side app on iOS 13.0

### To Reproduce
1. Open Safari/Chrome  
2. browse the app
3. See error stuck starting animation 

### Screenshots
![IMG_2048](https://user-images.githubusercontent.com/8701960/60616347-e65f9a80-9dd9-11e9-8858-57ccb5dfd41c.PNG)
![Screenshot 2019-07-03 21 29 32](https://user-images.githubusercontent.com/8701960/60616350-e65f9a80-9dd9-11e9-99f0-9a231e2eea22.png)

Where as working fine on desktop and android

![Screenshot 2019-07-03 21 33 21](https://user-images.githubusercontent.com/8701960/60616523-55d58a00-9dda-11e9-9ca9-1190387ca626.png)

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#15588
