### ISSUE TITLE
Web app templates now require account confirmation but Blazor Server App template doesn't

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#11886]
It looks like the web app templates have been updated to require account confirmation:

```csharp
services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
```

This results in a different UI flow when registering a new user:

![image](https://user-images.githubusercontent.com/1874516/60637979-74835300-9dd1-11e9-9fbd-f304f415ca03.png)

The Blazor Server App template doesn't have this option set, so when you register a new user you are immediately logged in:

![image](https://user-images.githubusercontent.com/1874516/60638085-d6dc5380-9dd1-11e9-9eb6-946cfcc5dbd1.png)

@blowdart @HaoK Should the Blazor Server App template be updated to require account confirmation as well?

**Comment by blowdart** [comment]
Yes, be consistent

**Comment by mkArtakMSFT** [comment]
@HaoK can you handle this in 3.1 to make the auth flow consistent across all the templates?

**Comment by danroth27** [comment]
@blowdart @javiercn FYI

**Comment by HaoK** [comment]
Fixed via https://github.com/aspnet/AspNetCore/pull/13559
