### ISSUE TITLE
Layout generated by Identity scaffolder conflicts with the layout in Blazor Server Apps

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#11883]
The Identity scaffolder generates a layout if it doesn't detect one in the project. Blazor Server Apps have a layout, but it's implemented using components so the Identity scaffolder doesn't detect it. The layout added by the Identity scaffolder gets applied to the *_Host.cshtml* file used by the Blazor app:

![image](https://user-images.githubusercontent.com/1874516/60633263-ac34cf80-9dbe-11e9-82c7-b86d7fc6e7d6.png)

Can we update the Identity scaffolder to detect the *_Host.cshtml* file and not generate a layout?

**Comment by danroth27** [comment]
@HaoK

**Comment by HaoK** [comment]
@vijayrkn I think this is mostly a question for you as I think this logic would need to go in the scaffolder code side of things as opposed to something in the content.

**Comment by blowdart** [comment]
@danroth27 We can't do anything here. Is scaffolding for Blazor planned for 3.0? This falls to someone, anyone, in tools.

**Comment by vijayrkn** [comment]
We don't have any active devs on the Scaffolding feature since Sean left.  If there are Scaffolding asks, we will have to add them to the list & look at resourcing for this.

**Comment by danroth27** [comment]
I believe the Identity Scaffolder does some pretty sophisticated stuff depending on which files are already in the project. So presumably detecting *_Host.cshtml* is something that is already possible with the existing scaffolding engine. We just need to add the necessary logic/content to the Identity scaffolder. @vijayrkn Is that correct?

**Comment by vijayrkn** [comment]
@danroth27 - I would assume so but I haven't looked at the Scaffolding code base in a while so we will have to take a look at it to confirm.

**Comment by acorrow** [comment]
There seem to be multiple issues with Blazor and Identity Scaffolding, but I'm not able to track down any bugs on this. I've seen a few features around some redesign, but there doesn't seem to be any implementation of Identity Scaffolding I can do that doesn't result in some kind of error. Anyone have any insight into the overall status of "Blazor Identity Scaffolding" in general?

**Comment by acorrow** [comment]
Perhaps I spoke too soon. This seems to cover it:

Update styling of the Blazor templates to match the rest of the ASP.NET Core templates #10883

Can't seem to link to it... Not sure why.

**Comment by blowdart** [comment]
@danroth27 Was this fixed? It's a scaffolding issue not an identity one.

**Comment by glararan** [comment]
I just ran into this problem after generating Blazor server-side ExternalLogin view.
Is considered to rewrite Identity for Blazor as components? I have login modal with external authentications like facebook/twitter which I would like to not redirect to razor page like it does when you create project and then you click on "Login".

**Comment by Tristan-Stricker** [comment]
Is there a work-around for this issue? Would love to use blazor and identity scaffolding but this is frustrating my efforts.

**Comment by glararan** [comment]
@Tristan-Stricker workaround is to copy-edit already written code. I dont thing so there is any available workaround by MS Dev team. I had to copy code and edit it via custom made razor page. Works for now & future :))

**Comment by Tristan-Stricker** [comment]
@glararan Do you have any code you can share which demonstrates your work around?

**Comment by javiercn** [comment]
@danroth27 I fixed this, so I'm closing it
