### ISSUE TITLE
Identity scaffolder generates code that doesn't compile or is malformed

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#11880]
The Identity scaffolder generates code that doesn't compile.

Repro steps:

- Install .NET Core 3.0 Preview 7 and VS d16.3 Preview 1
- Create a new ASP.NET Core Web App using the Empty template
- Right click on the project and run the Identity scaffolder
- Build the project with the generated identity code

Expected result:

- Project builds successfully

Actual result:

- The generate *_Layout.cshtml* and *_LoginPartial.cshtml* files fail to compile.
  - In *_Layout.cshtml*:
    - The using statement for `Microsoft.AspNetCore.Hosting` is missing the `@using` directive
    - The `IHostingEnvironment` injected property generates a warning because it is obsolete. It also looks like this property isn't used and can be removed?
  - In *_LoginPartial.cshtml*:
    - The `SignInManager` injected value is missing the `@inject` directive
- In *_ViewImports.cshtml*:
  - The using statement for `WebApplication1.Pages` is missing the `@using` directive
- In *_ViewStart.cshtml*:
  - The indentation of the closing curl brace if off

    ```
    @{
        Layout = "_Layout";
        }
    ````

**Comment by danroth27** [comment]
@HaoK

**Comment by HaoK** [comment]
The two missing using issues are a razor bug: https://github.com/aspnet/AspNetCore/issues/10811 according to @seancpeters

**Comment by HaoK** [comment]
Fixed by https://github.com/aspnet/Scaffolding/pull/1028
