### ISSUE TITLE
Update readme generated by the identity scaffolder for .NET Core 3.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#11882]
The readme for the identity scaffolder has some outdated content. It currently says:

```
The generated UI requires MVC. To add MVC to your app:
1. Call services.AddMvc() from your ConfigureServices method
2. Call app.UseMvc() from your Configure method (after authentication)
```

In .NET Core 3.0 we've switched to the new endpoint routing system, so instead of adding `app.UseMvc()` you need to add a call to `endpoints.MapRazorPages()` (and maybe also `endpoints.MapControllers()`?) in the call to `app.UseEndpoints()`.

**Comment by danroth27** [comment]
@HaoK

**Comment by HaoK** [comment]
Fixed by https://github.com/aspnet/Scaffolding/pull/1028
