### ISSUE TITLE
How to return data from Blazor JSInvokable method to triggered JS method as synchronous action

### ISSUE THREAD

**Issue by gurunathancs1991** [aspnet/AspNetCore#11893]
Am wrapping some existing JS plugins to blazor components. when doing so, i faced below issue.
i have a callback method, which has triggered from JS to blazor using dotnet reference -> `invokeMethodAsync`

`  this.dotnet.invokeMethodAsync("Trigger", this.eventName, '');`

it's perfectly triggers the `JSinvokable ` method. but here, i need to return the data from blazor source to JS function handler where it has been raised.

Instead `invokeMethodAsync`, tried `invokeMethod`, getting the below error 

https://github.com/aspnet/Extensions/blob/master/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L65

**whether it is possible to return data from event call back to JS function from where it has been raised as synchronous action?**

C# code:

```

    public class ExampleJsInterop
    {
        private readonly IJSRuntime _jsRuntime;

        public ExampleJsInterop(IJSRuntime jsRuntime)
        {
            _jsRuntime = jsRuntime;
        }

        public object CallHelloHelperSayHello(string name)
        {
            // sayHello is implemented in wwwroot/exampleJsInterop.js
            return _jsRuntime.InvokeAsync<object>(
                "exampleJsFunctions.sayHello",
                new DotNetObjectRef(new HelloHelper(name)));
        }
    }

    public class HelloHelper
    {
        public HelloHelper(string name)
        {
            Name = name;
        }

        public string Name { get; set; }

        [JSInvokable]
        public string SayHello()
        {
            return $"Hello, {Name}!";
        }
    }
```

Razor code:

```
@inject IJSRuntime JSRuntime

<button type="button" class="btn btn-primary" onclick="@TriggerNetInstanceMethod">
    Trigger .NET instance method HelloHelper.SayHello
</button>

@functions {

 
    public void TriggerNetInstanceMethod()
    {

        var exampleJsInterop = new ExampleJsInterop(JSRuntime);
        exampleJsInterop.CallHelloHelperSayHello("Blazor");
    }
}

```
Js code: 
```

window.exampleJsFunctions = {
    showPrompt: function (text) {
        return prompt(text, 'Type your name here');
    },
    displayWelcome: function (welcomeMessage) {
        document.getElementById('welcome').innerText = welcomeMessage;
    },
    returnArrayAsyncJs: function () {
        DotNet.invokeMethodAsync('BlazorSample', 'ReturnArrayAsync')
            .then(data => {
                data.push(4);
                console.log(data);
            });
    },
    sayHello: function (dotnetHelper) {
        debugger;
        dotnetHelper.invokeMethod('SayHello')
            .then(r => {
                debugger;
                console.log(r);
            });

        console.log('function outside');
    }
};
```

Here HelloHelper class -> SayHello method is not triggered from JS to C# side when i particularly mapped via invokeMethod not invokeMethodAsync?

**Comment by SteveSandersonMS** [comment]
If you're using server-side Blazor (and it sounds like you are), then all JS-.NET calls have to be async, because they are carried out over the network. That's why it tells you that you must use `invokeMethodAsync` instead of `invokeMethod`. If you use client-side Blazor, you can use `invokeMethod`.

**Comment by karthickthangasamy** [comment]
@SteveSandersonMS : Is there any way to distinguish between `server-side` and `client-side` razor application from `interop.js`.? So, that we can invoke the method accordingly.

**Comment by SteveSandersonMS** [comment]
Mostly people know which environment their application runs in, but if you're unsure, you should always use async interop only, since that's the only kind that's available in all environments.

**Comment by gurunathancs1991** [comment]
Hi @SteveSandersonMS , 

How can we differentiate client side blazor app or server side blazor app inside of class library for some specific action?

-Gurunathan

**Comment by SteveSandersonMS** [comment]
See how it's done here: https://github.com/aspnet/AspNetCore/blob/master/src/Components/test/testassets/BasicTestApp/Startup.cs#L28
