### ISSUE TITLE
Cannot connect to Blazor after a few refresh on OSX

### ISSUE THREAD

**Issue by keeed** [aspnet/AspNetCore#11890]
### Describe the bug
After a few refresh, for some weird reasons, I cannot connect to blazor anymore. Basically browsers are saying that the site cannot be reached.

### To Reproduce
1. Create a component where a data is periodically being sent to a javascript via JsInterop.
2. Refresh the browser several times. Hard to know when this is exactly happening but after a few refresh, it will occur.
3.  Error should occur.

### Expected behavior
Site should still work even after several refresh attempts.

### Screenshots
Here's the last log:
![image](https://user-images.githubusercontent.com/11542472/60648643-e6f83f80-9e72-11e9-9ec5-3c0a12c7c029.png)

### Additional info
Running 3.0.100-preview6-012264 on OSX.

Logging settings:

![image](https://user-images.githubusercontent.com/11542472/60648728-17d87480-9e73-11e9-8a07-e9f3bc0cf91f.png)

**Comment by keeed** [comment]
Additional info:

This is happening even on the default application template. Just do a lot of actions and eventually it will stop working.

**Comment by keeed** [comment]
More Update:

It looks like that this is just an OSX issue. I tried it on Windows but got no problem at all :(

**Comment by rynowak** [comment]
Do you see an error in the browser console?

**Comment by keeed** [comment]
@rynowak no error in the browser console as well.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @keeed.
@ajaybhargavb can you please try this out and see whether you can repro this? Thanks!

**Comment by keeed** [comment]
@mkArtakMSFT welcome! If there's anything that you need from me, feel free to message me.

**Comment by ajaybhargavb** [comment]
I tried this on a Mac with the 3.0 sdk but couldn't reproduce this. I see an `Authorization failed` log in the provided screenshot so I tried both noauth and individual auth blazorserver template but still couldn't reproduce the issue. I suspect this was fixed because of other changes we did in the area. @keeed, please re-open/comment if you can still reproduce this with the latest 3.0 sdk.
