### ISSUE TITLE
SignalR: No websocket availability in supported transports during negotiation

### ISSUE THREAD

**Issue by mathiassiig** [aspnet/AspNetCore#11898]
**Server-side** 
I'm using ASP.NET Core 2.2 and SignalR 1.1.4
I followed this tutorial: https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio

**Client-side**
I'm using Unity 2017.3.2f1 and BestHTTP Pro which comes with a SignalRCore client.

When attempting to establish a connection, the `NegotiationResult` comes with two `Supported Transports`: ServerSideEvents and LongPolling. In this, I also expect WebSockets to be available.

In the SignalR (server-side) tutorial, it's mentioned you have to add this:
```
app.UseSignalR(routes =>
            {
                routes.MapHub<ChatHub>("/chatHub");
            });
```

which I did (except renaming the endpoint). Do I also have to configure it with app.UseWebsockets? Or am I missing something otherwise obvious?

**Comment by anurse** [comment]
How are you hosting the server-side application? Are you hosting in IIS? By default IIS doesn't support WebSockets, you have to a) be running on Windows Server 2012/Windows 8 or higher **and** b) enable the "WebSocket Protocol" feature in the Windows Features.

**Comment by BrennanConroy** [comment]
If you're using Azure Web Apps you'll also need to enable websockets through the portal.

**Comment by mathiassiig** [comment]
Thanks, that did the trick!
