### ISSUE TITLE
Question : How to delete a file after download ?

### ISSUE THREAD

**Issue by valeriob** [aspnet/AspNetCore#11902]
Hi,
we would like to generate a file on the fly on the file system Path.GetTempFileName(), then return  PhysicalFile(filePath) in the action controller and delete the file right after to avoid filling up the disk.
We created a custom Result to delete the file after it has been executed, look like it's working, but is this approach correct ?

   public class PhysicalFileDeleteFileResult : PhysicalFileResult
    {
        public override async Task ExecuteResultAsync(ActionContext context)
        {
            await base.ExecuteResultAsync(context);
            File.Delete(FileName);
        }
    }

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by valeriob** [comment]
Ok sorry i will.
