### ISSUE TITLE
SignalR issue with  '@' in path

### ISSUE THREAD

**Issue by WHumphreys** [aspnet/AspNetCore#11909]
Visual Studio 2019

When using 'Add Client-Side Library' within Visual Studio to add the SignalR JS Library's the following path is created by default:

"~/lib/@aspnet/signalr/dist/browser/signalr.js"

When this is used in a Razor Page (I guess all of them but I have not tested) Visual Studio will not compile.

Error: 'The name 'aspnet' does not exist in the current context'

It is the '@' that is the issue. I don't need a work around as its easy enough to fix but I don't see why its there in the first place. I also know I can change the install path in the 'Add Client-Side Library' (NOW) as well. 

We as programmers have enough to learn and remember with all the goal posts you keep changing but silly things like this are becoming to the point I'm seriously debating dropping everything .NET etc.

Why would you ever put a symbol in the path that your own products complain about. Do you not test this stuff?

**Comment by BrennanConroy** [comment]
@mkArtakMSFT This looks like a razor issue.

**Comment by anurse** [comment]
This is an NPM standard pattern, so SignalR is not unique here. For example, [all the Angular packages would have the same problem](https://www.npmjs.com/search?q=%40angular). Sounds like this is actually an issue in the "Add Client-Side Library" logic in VS, can you file a VS Feedback item about it (using the feedback button in the top-right corner of Visual Studio)

**Comment by mkArtakMSFT** [comment]
Agree with @anurse.
This looks like a VS tooling issue. Please use VS Feedback to report this issue.
