### ISSUE TITLE
SignalR - Send custom complex object from Custom client.

### ISSUE THREAD

**Issue by iniside** [aspnet/AspNetCore#11900]
I have working custom client for SignalR.
I can send simple messages (using primitive types), but now I want to send complex object.

On The server side I have object like this:

```
    public class MessageWrapper
    {
        public string MessageType { get; set; }

        public string MessageBody { get; set; }
    }
```

```
        public async Task HandleMessage(MessageWrapper message)
        {
            if (message.MessageBody != null)
            {
                if (message.MessageBody.Length > 0)
                {
                    if (message.MessageType.Length > 0)
                    {

                    }
                }
            }
        }
```

And on client the sample message I send look like this:

```
{
	"type": 1,
	"invocationId": "15CAC9A1446D4B22466FA6B842FE9D8F",
	"target": "HandleMessage",
	"arguments": [
		{
			"MessageType": "Spark.Events.MessageNameType",
			"MessageBody": "{\"TestProperty\":\"Test\"}"
		}
	]
}
```

The message is correctly received on server side, but the object fields are all null.

Is  there something special I need to do, to correctly encode complex parameter using json ?

**Comment by BrennanConroy** [comment]
The payload looks fine. Can you try this out with an official supported client to see if it works?

**Comment by iniside** [comment]
Hey

It seems like this:

```
{
	"MessageType": "Spark.Events.MessageNameType",
	"MessageBody": "{\"TestProperty\":\"Test\"}"
}
```

Should like this:
```
{
	"messageType": "Spark.Events.MessageNameType",
	"messageBody": "{\"TestProperty\":\"Test\"}"
}
```

Camel case. I don't know if this is intended behavior or (using latest preview), but changing capitalization worked.

**Comment by BrennanConroy** [comment]
I can't reproduce this behavior locally.

Do you have a minimal repro we can try out?

**Comment by noahmorrison** [comment]
@BrennanConroy Hey, I think I'm experiencing the same issue as @iniside 

I made an MVP (minimum viable problem) repo [here](https://github.com/noahmorrison/SignalRBug)

If you don't think this is the same issue I can open a new one.

Thanks

**Comment by BrennanConroy** [comment]
@noahmorrison You need to make `Type` and `Message` properties and not fields. See https://github.com/dotnet/corefx/issues/36505 for the missing feature.

**Comment by noahmorrison** [comment]
@BrennanConroy Thanks! [That does work] (https://github.com/noahmorrison/SignalRBug/commit/716c9019c64d0ca3a8daf3edeeaa317a172edc84)

I guess this wouldn't be the same issue as @iniside  than, as they seems to already be doing that.

I really appreciate the response time!

**Comment by iniside** [comment]
It is quite hard to provide minimal example here, because the code that serialize my messages is completely custom and tied to Unreal Engine. 

I can specify is the field names are capitalized or not (like "MyFieldName" vs "myFieldName"). The first one won't work even if it is defined like 

```
class MyMsg
{
  public MyFieldName {get; set;}
}
```
It seems like the code assume that json field names start from lower case letter.

**Comment by BrennanConroy** [comment]
We're going to need more info to be able to do anything here as we can't reproduce the issue you're seeing.

Could you collect a network trace (as described [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2#network-traces)) of the custom client talking to the server and the server getting null for the properties?

And providing a project the can show the issue would also be helpful.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
