### ISSUE TITLE
Response.Body streams do not get flushed

### ISSUE THREAD

**Issue by Emzi0767** [aspnet/AspNetCore#11904]
### Describe the bug
It appears that streams under `Context.Response.Body` do not get flushed, at least if they are replaced. I tested this with `GZipStream`, unsure whether that's the case for other stream types.

### To Reproduce
I am using ASP.NET Core 2.2 in this example, I am unsure whether this still applies to 3.0 as I am unable to test at this time.

Steps:
1. Create an empty ASP.NET Core Web API app
2. Create an action like this:
   ```cs
   [Route("/test/{arg?}")]
   public IActionResult Test(string arg = null)
   {
       if (arg == "gz")
       {
           Response.Headers.Add(HeaderNames.ContentEncoding, "gzip");
           Response.Body = new GZipStream(Response.Body, CompressionLevel.Optimal);
       }

       return Json(new { message = "Hello world!" });
   }
   ```
3. Navigate to `<your app url>/test`
4. Notice the response
5. Navigate to `<your app url>/test/gz`
6. Notice empty response

### Expected behavior
You get the following message as a response from the server in both cases:
```json
{
    "message": "Hello world!"
}
```

### Additional context
This issue can be mitigated by implementing a middleware that forcefully flushes streams, like so:
```cs
app.Use(async (ctx, next) => 
{
    await next();
    if (ctx.Response.Body is GZipStream gz)
        await gz.FlushAsync();
});
```

The middleware has to be inserted before MVC. Repeating steps 3 and 5 with the above inserted before MVC produces correct response in either case.

**Comment by davidfowl** [comment]
It’s your job to act on the stream and revert it if you replace it. How you’re replacing the stream also isn’t idiomatic in MVC. Either you do it all in a middleware and handle before calling next and after or you can write a custom action result to handle that in mvc itself. 
 

I either situation it’s your job to perform the operation.

**Comment by Emzi0767** [comment]
This raises a question about response stream, however. Are the flush and/or dispose methods called on them at any point?

**Comment by davidfowl** [comment]
> Are the flush and/or dispose methods called on them at any point?

Depends on the server implementation. The golden rule is, you are responsible for the objects you create. A middleware that's being a good citizen looks like this:

https://github.com/aspnet/AspNetCore/blob/1b6f721648a500f59eda475564238e787a1967d8/src/Middleware/ResponseCompression/src/ResponseCompressionMiddleware.cs#L46-L96

PS: You should just use the response compression middleware, it does what you want.

**Comment by Emzi0767** [comment]
> The golden rule is, you are responsible for the objects you create. 

Fair enough, I'll have to keep that in mind for the future.

> PS: You should just use the response compression middleware, it does what you want.

Unfortunately, it does not. Compression middleware, the way I see it, only wraps into a compression stream based on `Accept-Encoding` header, and does so globally.

In my use case, the client does not send such a header, it's mandated by a route (or route argument, depending on implementation), and only on 3 specific endpoints (i.e. the entire API does not, and should not support compression otherwise).

The response compression middleware was one of the first thing I looked into, and, if I could obtain route data prior to request hitting MVC, I would gladly use it in place of my solution.

Nonetheless, I appreciate the input and suggestions.

**Comment by benaadams** [comment]
I assume you can do something better with endpoint routing in 3.0; but you can use .MapWhen to only attach compression when a condition is matched
```csharp
app.MapWhen((ctx) =>
    {
        if (ctx.Request.Query["gz"] == "1")
        {
            return true;
        }
        return false;
    },
    (ap) => ap.UseResponseCompression());
```

**Comment by Emzi0767** [comment]
Good to know, but it still won't cut it (route data is not yet available at this point). I'll have to look into endpoint routing in the future, I guess.
