### ISSUE TITLE
Converting DateTime to localtime w/ ToLocalTime() always returns UTC

### ISSUE THREAD

**Issue by kewinbrand** [aspnet/AspNetCore#11906]
Not sure if this issue belongs here.

I created a simple console app in docker with the following code:

```
var localTime =  DateTime.UtcNow.ToLocalTime();
Console.WriteLine(localTime);
Console.WriteLine(TimeZoneInfo.Local.ToString());
```
The output is:
07/04/2019 13:13:50
GMT

Even tough my system local time is GMT-3 (with timedatectl):

Local time: Thu 2019-07-04 10:22:50 -03
  Universal time: Thu 2019-07-04 13:22:50 UTC
        RTC time: Thu 2019-07-04 15:22:45
       Time zone: America/Sao_Paulo (-03, -0300)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: no
 Last DST change: DST ended at
                  Sat 2019-02-16 23:59:59 -02
                  Sat 2019-02-16 23:00:00 -03
 Next DST change: DST begins (the clock jumps one hour forward) at
                  Sat 2019-11-02 23:59:59 -03
                  Sun 2019-11-03 01:00:00 -02

Info:
microsoft/dotnet:2.2-aspnetcore-runtime as base image for docker

OS:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Am I missing something?
Thank you so far

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kewinbrand.
Folks at the `https://github.com/dotnet/corefx` repo are better positioned to answer this question.
Please file a new issue in there.

**Comment by kewinbrand** [comment]
Ok thank you.
