### ISSUE TITLE
Integration tests always use development environment

### ISSUE THREAD

**Issue by lukos** [aspnet/AspNetCore#11916]
### Describe the bug
I want to refer back to issue https://github.com/aspnet/Mvc/issues/7976 which was closed with imho a somewhat dismissive manner for the original reported issue. Basically, the behaviour of `WebApplicationFactory` is not instinctive when used on other environments. 

### To Reproduce
1) Create a dnc project with more than one appsettings.Env.json file
2) Put different database connection strings in it which are used by an integration test

### Expected behavior
When run on another environment, the value of ASPNETCORE_ENVIRONMENT should be respected and the correct connections made via appsettings.Env.json.

### Actual behaviour
The environment is ignored and `WebApplicationFactory` forces "Development", which will use the wrong appsettings and not work. This is invisible and confusing. I should not have to Google for 20 minutes to work out why this wouldn't just work.

### Workaround
Issue 7976 told of a workaround to explicitly set the environment in your test if you need to but this is extra code to make things work as they should in the first place! The irony is that the workaround is more effort than the original bug (where Scott Hansellmann was complaining about having to explicitly set "Development" in his tests)

### Better way
Any code that blindly overrides something is code smell to me. All behaviour should be explicit.

The default behaviour should be to have no environment unless you set it in your OS environment - that is kind of the point. Visual Studio itself artificially overrides this with launchsettings.json, which is fine because it does not change what will happen when deployed, and the `WebApplicationFactory` could create or use this file if that helps. Otherwise. the docs for `WebApplicationFactory` should be explicit that you need to pass in an environment variable unless you are happy for it to be picked up from the environment automatically.

Please can we reconsider this?

**Comment by guardrex** [comment]
We have a cross-issue in docs for this, too, given that devs are asking for help on how to do it. https://github.com/aspnet/AspNetCore.Docs/issues/12303

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lukos.
We'll use the issue @guardrex has pointed out above to track the work to improve documentation and include a section about how to configure environment on the WebApplicationFactory.
