### ISSUE TITLE
Determine when .NET call dispatcher is initialised.

### ISSUE THREAD

**Issue by Avrohom** [aspnet/AspNetCore#11917]
### Is your feature request related to a problem? Please describe.
Yes, indeed. When calling a .Net method from javascript immediately after page load, the .Net call dispatcher seems to not yet been initialised. The web console shows following error: 

![image](https://user-images.githubusercontent.com/6719297/60723636-1323c700-9f2c-11e9-9f80-7943f48eb56a.png)

### Describe the solution you'd like
Some kind of trigger / event to indicate when the .Net dispatcher is ready. 

### Additional context
At the moment I setTimeout() to set a variable / flag 100 ms after page reload and the function checks that flag before calling the .Net method.

**Comment by Avrohom** [comment]
Found better solution.

In the razor page I am calling in the OnInit method the foolwing:
`    JsRuntime.InvokeAsync<object>("dotNetSetIsReady");
`

In the js file I declare following function:
`window.dotNetSetIsReady = function () {
    dotNetInitialised = true;
};
`
this is where and how I indicate a flag that DotNet is ready.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Avrohom.
What you've found is exactly what we'd suggest!
