### ISSUE TITLE
Connected Services workflow in VS2017 overrides entire 'StartUp.cs' file generated from React Redux SPA Template

### ISSUE THREAD

**Issue by brcaswell** [aspnet/AspNetCore#11912]
Greetings, I wanted to relay an issue I observed and experienced; Though, I don't think it's necessarily a bug; it's something worth triaging on and potentially a grooming consideration.

When creating a new .NET Core 2.1 ASP.NET Application Project using React Redux SPA Template **and** utilizing the 'Connected Services' to add 'Authentication with Azure Active Directory' (Configuring SSO using AAD) the SPA related configurations are overwritten.  

Running the application in this state results in a 404 response.

The issue is resolved by manually adding those configurations back in - reflecting on this repo 'StartUp.cs' file; but, it did pose an issue for me until I tracked down this repo for the proper configurations.

---

I suppose my suggestion here is to include a section in the 'README.MD' relating to Visual Studio Project Template and Connected Services Code Generation pitfalls\considerations.  

Also, any form of documentation on client-side support and handling of IdP and middleware would be appreciated.

---

In addition, I would like to request a feature to support Authentication configuration for middleware in Code Generation. 

![image](https://user-images.githubusercontent.com/967010/60700375-4e3ae180-9ebd-11e9-92d5-27cc9be7404b.png)

Essentially, supporting these options to 'Change Authentication' during the steps to create the project.  

---

Also note: Even after adding the configuration back into `StartUp.cs`, I've been experiencing issues with Client-Side handling for Unauthorized responses - support for redirecting using `redirectUrl` from the tenant 200 ok response in the attempt to request\fetch weather forecasts when `Authorize` is specified.   Note: changing this to `AllowAnonymous` does populate the list and demo the component

**Comment by brcaswell** [comment]
note that I initially posted this issue in [facebook/create-react-app](https://github.com/facebook/create-react-app) by mistake.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @brcaswell.
This is not something we have control over. Please use VS Feedback tool from VS to report this.
