### ISSUE TITLE
How to get FileStreamResult in blazor project with netstandard2.0 ?

### ISSUE THREAD

**Issue by kmkrish007** [aspnet/AspNetCore#11918]
### Describe the bug
I have developed blazor project with netstandard2.0, i want to use FileStreamResult in my project, and not able to install this packages, Microsoft.AspNetCore.Mvc.NewtonsoftJson version=3.0.0-preview6.19307.2. is there any way to use FileStreamResult in my project.

### Expected behavior
blazor project with netstandard2.0 and need to use FileStreamResult.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kmkrish007.
What are you trying to do? Please provide more details about your scenario.

**Comment by kmkrish007** [comment]
Hi @mkArtakMSFT ,

I have updated my project <TargetFramework>netstandard2.1</TargetFramework>
and i just want to install this nuget package on my project 
![image](https://user-images.githubusercontent.com/43262413/60866613-6b1d3f00-a246-11e9-9ed4-ea5517ccc61a.png)

I have used my controllers page "FileStreamResult" so, I need this nuget package.

Thanks.

**Comment by kmkrish007** [comment]
I didn't find any solution but i close this issue.
