### ISSUE TITLE
SignalR Self-Host does not support Console Application?

### ISSUE THREAD

**Issue by CenturionYun** [aspnet/AspNetCore#11915]
I built a console signalr server based on .net 4.5 before, now i'm trying to move to .net core, but i found that i cannot find a way to add latest signalr 3.0 preview-6 into console application.

**Comment by anurse** [comment]
Are you trying to host a server in a console application? ASP.NET Core applications **are just console applications**, unlike in ASP.NET 4.x.

**Comment by anurse** [comment]
You can configure ASP.NET Core hosting in **any application** using the `WebHost` class. See our documentation for details: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2

**Comment by CenturionYun** [comment]
> You can configure ASP.NET Core hosting in **any application** using the `WebHost` class. See our documentation for details: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2

Thanks, It solved my problem as" ASP.NET Core is console applications". I will close this thread.
