### ISSUE TITLE
Blazor Startup class does not find _Host or pages when mocked from different project

### ISSUE THREAD

**Issue by TheMightyMat** [aspnet/AspNetCore#11921]
### Description
If the `Startup` class is inherited by a `TestStartup` class in an integration test project, and used to launch the server, the following error is given, despite the content root being set to the main project:
```
System.InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area:  }.
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|6_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0-preview6.19307.2\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: Error: An exception was thrown attempting to execute the error handler.
```
It appears that the page routing is still performed relative to the TestStartup class, instead of to the content root set.

### To Reproduce
Steps to reproduce the behaviour:
1. Using ASP.NET Core 3.0.0-preview6-27804-01 with Blazor Template Project
2. Create another project ("the test project") in the solution
3. Create a class `TestStartup` that inherits from `Startup` in the test project
4. Run from the test project
```
Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<TestStartup>();
                }).UseContentRoot("MainProjectPath").Build().Run();
```
(replace `MainProjectPath` with the path to the root directory of the main project)
4. Observe that a 500 internal server error is returned on any page that should be mapped, and the error given in this issue's description is found in the console
5. Observe that if `TestStartup` is changed to `Startup` the above code runs correctly without errors.

### Expected behavior
The location of the Startup class should not affect the behaviour of the server, when UseContentRoot is set correctly.

### Additional context
Being able to substitute the Startup class from a test project is important as it allows to change the dependency injection configured in `ConfigureServices`, e.g. to use mock services.
Include the output of `dotnet --info`

dotnet --info output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @TheMightyMat.
We'll investigate this and get back to you as soon as we can. This may take some time, though.

**Comment by ajaybhargavb** [comment]
@TheMightyMat I am unable to reproduce this issue. I was able to successfully access referenced project's pages and static content while running from another test project.
- Can you try your scenario in the latest SDK and see if the issue persists?
- if it does, can you please share a repro project so I can make sure I didn't miss anything?

**Comment by TheMightyMat** [comment]
@ajaybhargavb [Here's a project that reproduces the issue](https://github.com/TheMightyMat/blazor-startup-class-error-demo). Change the contentRoot variable in the test project to point to the location of the main project after you clone. Run the unit test in debug mode to view the console output - you should see the same error stated above. This was run on 3.0.100-preview6-012264, will try on the latest SDK preview when I get a chance.

**Comment by ajaybhargavb** [comment]
@TheMightyMat thanks for that. I am now able to reproduce your issue. It happens even on the latest SDK. I'll look into it.

**Comment by ajaybhargavb** [comment]
@TheMightyMat it looks like this happens because of a mismatch in the `HostingEnviroment.ApplicationName`. Basically in addition to setting content root, you'll also need to set the application name to be the correct one instead of the test project.

You can do something like this. In your case, you'll pass in "MainProject" for appName
```C#
public static IHostBuilder CreateHostBuilderWithStartup<TStartup>(string[] args, string appName) where TStartup : class
{
    return Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<TStartup>();

            webBuilder.ConfigureAppConfiguration((b, c) =>
            {
                b.HostingEnvironment.ApplicationName = appName;
            });
        });
}
```

I've verified that this fix works.

You might also want to look into https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0#aspnet-core-integration-tests which is our recommended way of writing integration tests using the provided test server.
