### ISSUE TITLE
Convert to arcade YAML templates

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#11924]
Follow up to https://github.com/aspnet/AspNetCore/pull/11122 for the work item to use the Arcade YAML templates for CI definition.

Converting to the stages templates should also help with maestro publishing.

**Comment by dougbu** [comment]
- [ ] aspnet/AspNetCore-Tooling 
- [ ] aspnet/Blazor
- [ ] aspnet/EntityFramework6
- [ ] aspnet/EntityFrameworkCore
- [ ] aspnet/Extensions
- [ ] aspnet/AspNetCore

**Comment by dougbu** [comment]
@wtgodbe I think I've got Blazor working now. Why don't you have a look at the EF repos?

I'll jump to AspNetCore because I expect it to hit significant issues and I'm more familiar w/ our existing release pipeline for that one.

**Comment by wtgodbe** [comment]
@dougbu sounds good!

**Comment by dougbu** [comment]
This isn't closed yet. I'm still wrapping up w/ aspnet/AspNetCore

**Comment by dougbu** [comment]
04705ee4f1ae
