### ISSUE TITLE
[Blazor] HTML attributes set before @bind are ignored by code generation

### ISSUE THREAD

**Issue by matthensleyio** [aspnet/AspNetCore#11929]
### Describe the bug
Using the bind attribute on a Blazor form input element causes all following HTML attributes to be ignored during code generation.

### To Reproduce
1. Clone [this repository](https://github.com/matthensleyio/BlazorBindOrderBug)
2. Run run the Blazor project
3. Inspect the generated HTML
4. Notice all HTML attributes declared before a bind are not present in the rendered HTML

### Expected behavior
If any HTML attributes have been set before using the bind attribute, the HTML attributes & their values are present in the generated HTML.

### Screenshots
[Rendered Page](https://github.com/matthensleyio/BlazorBindOrderBug/blob/master/screenshots/rendered-page.png)

[Rendered HTML](https://github.com/matthensleyio/BlazorBindOrderBug/blob/master/screenshots/rendered-html.png)

**Comment by enetstudio** [comment]
It's a mere guess, as I have no proper software to run your app.

I think it is related to the type of the backing variables which should be string and not int. When the @bind directive comes first, and the compiler sees that you use a wrong data type, it just skip "rendering" the rest of the attributes (actually "rendering" space), but when the the @bind directive appears last, it's too late, and you've got your attributes created. 

Note: Once again, this is only a guess, and if I'm wrong, I apologize...

Did you try the select elements if the works at all ?

**Comment by matthensleyio** [comment]
I have tried using other input types/backing types as well.

I just updated the example repo to include a text input field that is being bound to a string property. The bug exists there as well.

**Comment by rynowak** [comment]
@matthensleyio - I can't reproduce this on dotnet `3.0.100-preview6-012264`

Can you share the generated code from inside `obj\Debug\netcoreapp3.0\Razor`

**Comment by matthensleyio** [comment]
@rynowak I have updated my example project to include the output of that directory.

[They can be found here.](https://github.com/matthensleyio/BlazorBindOrderBug/tree/master/src/BlazorBindingOrderBug/obj/Debug/netcoreapp3.0/Razor)

**Comment by rynowak** [comment]
What version of .net are you using? (`dotnet --version`)

This is a confusing result: 
- Your code [has `@bind` in it](https://github.com/matthensleyio/BlazorBindOrderBug/blob/master/src/BlazorBindingOrderBug/Pages/Index.razor#L6)
- The generated C# treats it [all as static markup](https://github.com/matthensleyio/BlazorBindOrderBug/blob/master/src/BlazorBindingOrderBug/obj/Debug/netcoreapp3.0/Razor/Pages/Index.razor.g.cs#L27)

**Comment by matthensleyio** [comment]
It looks like I am on `3.0.100-preview5-011568. `

I will update to `3.0.100-preview6-012264` & test again.

**Comment by matthensleyio** [comment]
Upgrading to `3.0.100-preview6-012264` appears to have corrected my issue.

Thanks for helping me out with this @rynowak.
