### ISSUE TITLE
why publiush a .net core web project will contain many Microsoft.VisualStudio.Web.CodeGeneration.xxx dll

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/AspNetCore#11935]
I found that when I publish a asp.net core 2.2 Web project ,in publish folder contain many startwith Microsoft.VisualStudio.Web.CodeGeneration.xxx.dll,like this:
![image](https://user-images.githubusercontent.com/18448413/60750252-7d924100-9fd8-11e9-9eed-c12be3b18127.png)

I think these dll is in VS 2019's  Analyzers,
![image](https://user-images.githubusercontent.com/18448413/60750247-6d7a6180-9fd8-11e9-80ba-6f97802755d6.png)

but is these dll need to use in runtime?How Can I pushlish the project don't contain they?because I like the pushlish less files to server

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kugarliyifan.
@pranavkm can you please confirm this is caused by https://github.com/dotnet/sdk/issues/1212, which is blocked on NuGet?
