### ISSUE TITLE
Angular Individual Auth Template Login/Register Route Error

### ISSUE THREAD

**Issue by gavdraper** [aspnet/AspNetCore#11938]
### Describe the bug
If I create a new angular project with auth using...

dotnet new angular -au Individual 

Then run it the app runs but Login and Register pages both error with...

"ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'Identity/Account/Register'
Error: Cannot match any routes. URL Segment: 'Identity/Account/Register'
    at ApplyRedirects.push../node_modules/@angular/router/fesm5/router.js.ApplyRedirects.noMatchError"

### To Reproduce
1. Make sure you're running 3.0.100-preview6-012264 
2. Run
   dotnet new angular -au individual
   dotnet run
4. Click register or run. Page will error in dev tools and you wont see a login or register screen.

### Expected behavior
see regisration/login screen.

### Screenshots

![image](https://user-images.githubusercontent.com/971016/60760093-89592400-a027-11e9-953a-04f3786b4c61.png)

### Additional context
![image](https://user-images.githubusercontent.com/971016/60760107-b73e6880-a027-11e9-8c84-c878e87dbbf5.png)

**Comment by blowdart** [comment]
@javiercn could you take a look please?

**Comment by javiercn** [comment]
I haven't been able to repro this with preview7. (I haven't tried preview6, but given that its not reproducible in preview7/master) I'm closing this as no repro.

**Comment by javiercn** [comment]
@blowdart for future reference, new issues filed get scheduled in the next milestone (not the current one). Please work with @mkArtakMSFT as otherwise its highly disruptive to our planning.
