### ISSUE TITLE
IHttpResponseCompletionFeature.CompleteAsync() should take a cancellation token

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#11931]
CompleteAsync is subject to backpressure, but does not currently take a cancellation token so you can't abort without calling `HttpContext.Abort()`.

**Comment by anurse** [comment]
Is this fairly straightforward? At a minimum we could take a token and just do nothing with it (to avoid a future API break)

**Comment by Tratcher** [comment]
Right, it's easy to add the token now and we can work out where to honor it as we go.

**Comment by anurse** [comment]
Though adding a token later would likely be non-breaking since we'd do it via an overload.

**Comment by Tratcher** [comment]
@JamesNK @JunTaoLuo FYI

**Comment by Tratcher** [comment]
Closing this as wont-fix per @davidfowl
