### ISSUE TITLE
Web deploy fail using Visual studio 2019 preview. Self contained deployment

### ISSUE THREAD

**Issue by roboriaan** [aspnet/AspNetCore#11941]
Not sure if this is the correct place to log this issue.

### Describe the bug

I'm getting the following error when I try to publish a **self contained deployment** :

`
Error : Assets file '{PathToClientFolder}\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project.	`

Some important info :

-  Project builds and runs fine. 
-  Deploys fine to a local folder.
- Web Deploy works fine using the framework dependent deployment mode.

### To Reproduce
1. Create a starter Blazor (ASP.net core hosted) project
2. Import .publishsettings file from hosting provider
3.  Validate connection
4. Change deployment mode to self contained and select correct target
5. Click publish

### Expected behavior
Should publish

### Screenshots
![Capture](https://user-images.githubusercontent.com/13508869/60769870-4786b700-a0d5-11e9-8fb6-545beef8c94b.PNG)

![Capture1](https://user-images.githubusercontent.com/13508869/60769875-553c3c80-a0d5-11e9-8402-07f26eca6550.PNG)

![Capture2](https://user-images.githubusercontent.com/13508869/60769881-5a00f080-a0d5-11e9-8a9a-2847493ffdfc.PNG)

### Additional context

**SDKS :**
2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
2.2.300 [C:\Program Files\dotnet\sdk]
**3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]**

**VS :**
Microsoft Visual Studio Community 2019 Preview
Version 16.2.0 Preview 3.0
VisualStudio.16.Preview/16.2.0-pre.3.0+29021.104
ASP.NET Core Blazor Language Services   16.0.19307.2

TIA! 👍

**Comment by Andrzej-W** [comment]
Read this https://github.com/aspnet/AspNetCore/issues/9285#issuecomment-502794472 and maybe this https://github.com/aspnet/websdk/issues/604#issuecomment-487328649

**Comment by roboriaan** [comment]
Thanks @Andrzej-W. #9285 did the trick. Removing `<TargetFramework>netcoreapp3.0</TargetFramework>` from the .pubxml is a good workaround for my issue. 😁 🤘
