### ISSUE TITLE
Blazor Server-Side Question & Discussion - # of server instants running...

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#11945]
Hi guys;
Looking at the pros & cons of server-side hosting model, one area that concerns us, is that, for every user that launches our app, a new copy of our app gets instantiated along with two other class libraries for Data Access and Business Domain.

The questions are:
1) Does every instance take up the same amount of resources as the first instance?

2) Since we don't know how many people come to the site, how do we know, when there are too many instances are alive?

3) When does an instance go away and resources are returned? Is there a session timeout if user is inactive?

4) What's the best strategy to keep an eye on this and not let the system crash?  

Thank you in advance!
..Ben

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @BenHayat.
We plan to resolve/provide answers to these questions as part of #10472 work.
