### ISSUE TITLE
[Feature Request] Register startup tasks via IStartupTask

### ISSUE THREAD

**Issue by NicolasDorier** [aspnet/AspNetCore#11946]
A recurring problem I get is how to run a task that need to run only once in ASP.NET Core?

This [blog post](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-1/) write about all the solution, and the shortcoming of each of them (@andrewlock).

He solved the problem elegantly in [the part 2](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-2/) by making a new interface `IStartupTask` that he registers in the DI in `Startup`, and an extension method `IWebHost.RunWithTasksAsync` to call instead of `RunAsync()`.

```csharp
public static async Task RunWithTasksAsync(this IWebHost webHost, CancellationToken cancellationToken = default)
{
	// Load all tasks from DI
	var startupTasks = webHost.Services.GetServices<IStartupTask>();

	// Execute all the tasks
	foreach (var startupTask in startupTasks)
	{
		await startupTask.ExecuteAsync(cancellationToken);
	}

	// Start the tasks as normal
	await webHost.RunAsync(cancellationToken);
}
```

This solution has no downside, but I feel that this is something that Aspnet Core should have out of the box as this is a very common problem.
Despite being a long time .NET guy, I was not finding a good enough solution until I stumbled up on his blog.

**Comment by davidfowl** [comment]
IHostedService should work for this in 3.0.

**Comment by NicolasDorier** [comment]
`StartAsync()` of `IHostedService` is running after the kestrel server start servicing the requests though.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/AspNetCore/issues/11437

**Comment by NicolasDorier** [comment]
Closing this then, happy to see it coming. I can't wait for 3.0.
