### ISSUE TITLE
Recursive TryValidate methods for deep object graphs

### ISSUE THREAD

**Issue by jeremycook** [aspnet/AspNetCore#11944]
### Is your feature request related to a problem? Please describe.
Recursive TryValidate methods for deep object graphs. This would be particularly helpful since EF Core does not provide data annotations validation like EF 6 and earlier.

### Describe the solution you'd like
Methods like ControllerBase.TryDeepValidate, and System.ComponentModel.DataAnnotations.Validator.TryDeepValidate would both be helpful. ControllerBase.TryDeepValidate could utilize System.ComponentModel.DataAnnotations.Validator.TryDeepValidate.

### Additional context
There are StackOverflow questions related to this:

* Question with solutions that go back to pre-.NET Core: https://stackoverflow.com/questions/7663501/dataannotations-recursively-validating-an-entire-object-graph
* The question I posted was specific to deep graph validation from a custom model binder: https://stackoverflow.com/questions/56914462/recursively-validating-a-complex-model-within-a-custom-model-binder

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jeremycook.
`TryValidateModel` in ASP.NET Core already does deep validation through the `ObjectValidator`: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ControllerBase.cs#L2693

**Comment by jeremycook** [comment]
@mkArtakMSFT thank you but my experience does not match your statement when it comes to collections. I've tried using Controller.TryValidateModel(model, prefix), and fetched an IObjectModelValidator service and used that directly in the JsonModelBinder I mention in my StackOverflow question. In both cases the top-most properties are validated, but properties of items in collections are not validated. 

**Are collections not recursively validated?**

Here is an example of what I am trying to validate.

```csharp
public class Foo
{
    // Validation failure of this required attribute shows up in ModelState
    [Required]
    public string Id { get; set; }

    [Required]
    public List<Bar> Bars { get; set; } = new List<Bar>();
}

public abstract class Bar
{
    // Validation failure of this required attribute does not show up in ModelState
    [Required]
    public string Id { get; set; }
}
```

My use in the model binder mimics the ControllerBase code you linked to.

```csharp
public Task BindModelAsync(ModelBindingContext bindingContext)
{
    try
    {
        var json = bindingContext.ValueProvider.GetValue(bindingContext.ModelName).Values;
        if (json.Count > 0)
        {
            var model = JsonConvert.DeserializeObject(json, bindingContext.ModelType, settings);
            bindingContext.Result = ModelBindingResult.Success(model);

            var objectValidator = bindingContext?.HttpContext?.RequestServices?.GetRequiredService<IObjectModelValidator>();
            objectValidator?.Validate(bindingContext.ActionContext, bindingContext.ValidationState, bindingContext.ModelName, model);
            // ...
```

I get the same outcome whether I use Controller.TryValidate without validating in my JsonModelBinder, and when validating in the JsonModelBinder and not in the controller. In both cases values of top-level properties are validated but deeper objects are not.

**Comment by mkArtakMSFT** [comment]
@jeremycook thanks for the info. Please provide a minimalistic repro project, so we can investigate this easily.

**Comment by jeremycook** [comment]
Here's a repro. As I made it I discovered that this issue is not with collections but with subclasses of abstract classes.

https://github.com/jeremycook/DeepValidationRepro

The Index action of Home looks like this:

![image](https://user-images.githubusercontent.com/452414/60927485-5dc47c80-a267-11e9-9bd9-00332ccc4c83.png)

Viewing the page you see this, but you should also see (in my opinion) "The BarField field is required." messages.

![image](https://user-images.githubusercontent.com/452414/60927441-35d51900-a267-11e9-8391-83cc5b0da87b.png)

The models are here:

https://github.com/jeremycook/DeepValidationRepro/tree/master/Models

**Comment by paul-michalik** [comment]
Given I am using data annotation attributes and ApiControllerAttribute in a Web API Asp.NET Core app, are annotated properties of complex type validated recursively by default?

**Comment by jeremycook** [comment]
@paul-michalik Yes annotated properties of complex type validated recursively by default, **BUT** what I ran into is that properties of subclasses like in the repro I provided are not being validated. Changing the name of this issue to something more specific may be a good idea, but I'm leaving that to @mkArtakMSFT and team.

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @jeremycook.
We'll look into this during our next milestone (preview 9).

**Comment by paul-michalik** [comment]
This is a similar situation I ran into, except that my "Bar" isn't abstract. I need to check whether this makes a difference.

**Comment by jeremycook** [comment]
@paul-michalik After some more testing, subclasses appear to be the crux of the issue and not abstract classes. I misspoke.

**Comment by jeremycook** [comment]
Thanks @mkArtakMSFT. Any thoughts about this being back-ported to 2.x?

**Comment by paul-michalik** [comment]
@jeremycook I debugged through the validation code and honestly I do not see why properties of sub-classed types aren't validated. My setup is even simpler, there's no collection of `Bar` I just got a property of type `BarBase` which has a run-time type of `Bar`. 
@mkArtakMSFT How do I test the validation without running the whole MVC pipeline? Assuming a type hierarchy as in Jeremy's example, I'd expect the requirement for 'int? Id' beeing validated: 
```
class Foo {
    [Required]
    BarBase Bar { get; set; }
}

class Bar : BarBase {
    [Required]
    int? Id { get; set; }
}

// later in a test case:
Assert.NoThrow(Validator.ValidateObject(new Foo() { 
     Bar = new Bar { Id = 15 }
}, new ValidationContext()))
```

**Comment by mkArtakMSFT** [comment]
We won't be able to backport this to 2.x, and we will be handling this only after 3.0, as it seems there are more critical things lined up to be handled for 3.0.

**Comment by pranavkm** [comment]
@paul-michalik you're describing the behavior of the `DataAnnotations` Validator. Please file an issue in https://github.com/dotnet/corefx for questions or discussions about it.

@jeremycook I recently got around to documenting this - https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.0#polymorphic-model-binding, but MVC uses 

a) the actual model type of parameters or top level models
b) the declared type of properties on the model unless model binding tells it's otherwise.

In the second case, model binding can update `ValidationState` to indicate the actual type of the model. This is useful in the abstract \ polymorphic binding case which is effectively what's happening in your sample. However, it doesn't work very well with `TryValidateModel`, since binding and validation occur independently of each other. 

For 3.0 and earlier, you could consider using `IObjectModelValidator` which is what [`TryValidateModel` uses under the covers:](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ControllerBase.cs#L2787-L2791) and pass in a appropriately configured `ValidationStateDictionary`.  For the next release, we're looking at ways to improve the experience around this scenario. We'll be using #13829 to track this work.
