### ISSUE TITLE
Allow relative url generation for Login redirects.

### ISSUE THREAD

**Issue by voroninp** [aspnet/AspNetCore#11949]
My problem is that location url for Login redirect is absolute. I had to enable and configure middleware to take `X-Forwarded-For`  and `X-Proto` headers into account. This also requires proper configuration of each proxy, otherwise chain of hosts may be broken.

[RFC7231](https://tools.ietf.org/html/rfc7231#section-7.1.2) allows locations to be relative, so it would be nice to have this option when [configuring redirection options](https://stackoverflow.com/q/56871058/921054) because in this case there wouldn't be any need in configuring headers middleware at all.

**Comment by blowdart** [comment]
We switched to absolute to avoid some security issues when people misconfigured host validation to listen to *, so I'm afraid we won't switch it back again.

**Comment by voroninp** [comment]
@blowdart why not to have an option for either-or? Documented with remark about possible security issues?

**Comment by blowdart** [comment]
Generally we don't do this for security issues because people simply don't read the docs and we'd rather everyone was as safe as possible.

**Comment by voroninp** [comment]
@blowdart  But you do allow to set `ForwardLimit` to `null` ,when `KnownHosts` is NOT set. No warnings, no exceptions ;-)

**Comment by blowdart** [comment]
Huh. If you want to open an issue I'll have that addressed :D

**Comment by voroninp** [comment]
@blowdart  Done =P
