### ISSUE TITLE
Blazor won't install

### ISSUE THREAD

**Issue by enewmen** [aspnet/AspNetCore#11953]
Error " This extension is not installable on any currently installed products."
Microsoft.VisualStudio.BlazorExtension.16.0.19307.2.vsix
Visual Studio 2019 - 16.1.5  --    with the ASP.NET and web development workload selected.
dotnet-sdk-3.0.100-preview6-012264-win-x64

I remember this working before. No idea what to try.  Please suggest.  thanks!

The Log:
8/7/2019 5:46:48 PM - Microsoft VSIX Installer
8/7/2019 5:46:48 PM - -------------------------------------------
8/7/2019 5:46:48 PM - vsixinstaller.exe version:
8/7/2019 5:46:48 PM - 16.1.3132
8/7/2019 5:46:48 PM - -------------------------------------------
8/7/2019 5:46:48 PM - Command line parameters:
8/7/2019 5:46:48 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Temp\Microsoft.VisualStudio.BlazorExtension.16.0.19307.2.vsix
8/7/2019 5:46:48 PM - -------------------------------------------
8/7/2019 5:46:48 PM - Microsoft VSIX Installer
8/7/2019 5:46:48 PM - -------------------------------------------
8/7/2019 5:46:49 PM - Initializing Install...
8/7/2019 5:46:50 PM - Extension Details...
8/7/2019 5:46:50 PM - 	Identifier         : Microsoft.VisualStudio.BlazorExtension
8/7/2019 5:46:50 PM - 	Name               : Blazor
8/7/2019 5:46:50 PM - 	Author             : Microsoft
8/7/2019 5:46:50 PM - 	Version            : 16.0.19307.2
8/7/2019 5:46:50 PM - 	Description        : Provides Visual Studio support for Blazor
8/7/2019 5:46:50 PM - 	Locale             : en-US
8/7/2019 5:46:50 PM - 	MoreInfoURL        : 
8/7/2019 5:46:50 PM - 	InstalledByMSI     : False
8/7/2019 5:46:50 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
8/7/2019 5:46:50 PM - 
8/7/2019 5:46:50 PM - 	SignatureState     : ValidSignature
8/7/2019 5:46:50 PM - 	SignedBy           : Microsoft Corporation
8/7/2019 5:46:50 PM - 	Certificate Info   : 
8/7/2019 5:46:50 PM - 		-------------------------------------------------------
8/7/2019 5:46:50 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
8/7/2019 5:46:50 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
8/7/2019 5:46:50 PM - 		[Serial Number] : 330000026ECE6AE5984BFC96A900000000026E
8/7/2019 5:46:50 PM - 		[Not Before]    : 7/9/2018 5:00:30 AM
8/7/2019 5:46:50 PM - 		[Not After]     : 7/9/2019 5:00:30 AM
8/7/2019 5:46:50 PM - 		[Thumbprint]    : 99B6246883B4B32EA59AE18B36945D205A876800
8/7/2019 5:46:50 PM - 
8/7/2019 5:46:50 PM - 	Supported Products : 
8/7/2019 5:46:50 PM - 		Microsoft.VisualStudio.Community
8/7/2019 5:46:50 PM - 			Version : [16.2,)
8/7/2019 5:46:50 PM - 
8/7/2019 5:46:50 PM - 	References         : 
8/7/2019 5:46:50 PM - 	Prerequisites      : 
8/7/2019 5:46:50 PM - 		-------------------------------------------------------
8/7/2019 5:46:50 PM - 		Identifier   : Microsoft.VisualStudio.Component.Web
8/7/2019 5:46:50 PM - 		Name         : ASP.NET and web development tools
8/7/2019 5:46:50 PM - 		Version      : [16.0,)
8/7/2019 5:46:50 PM - 
8/7/2019 5:46:50 PM - Signature Details...
8/7/2019 5:46:50 PM - 	Extension is signed with a valid signature.
8/7/2019 5:46:50 PM - 
8/7/2019 5:46:50 PM - Searching for applicable products...
8/7/2019 5:46:50 PM - Found installed product - Global Location
8/7/2019 5:46:50 PM - Found installed product - Visual Studio Community 2019
8/7/2019 5:46:50 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @enewmen.
The Blazor VSIX requires VS 16.2 preview version as minimum. Please make sure you install the latest preview release of VS to make it work.

**Comment by enewmen** [comment]
Thanks for the post!  I'm sure I installed the latest version - using the installer.  Next I'll make sure it's v16.2
