### ISSUE TITLE
AspNetCore 2.1 Concurrent test

### ISSUE THREAD

**Issue by SmartKarren** [aspnet/AspNetCore#11951]
Now we use AspNetCore 2.1 WebAPI to store image to aws s3 storage. works like
```csharp
    string inputBody = string.Empty;
    using (var reader = new System.IO.StreamReader(context.Request.Body, 
            System.Text.Encoding.UTF8))
     {
         inputBody = reader.ReadToEnd();
     }
    var imgData = Convert.FromBase64String(inputBody );
    var keyName = "generateKeyExamp";
    //s3Client use AWSSDK create
    var respFromS3 = await s3Client.PubObjectAsync(keyName, imgData);
   //response with s3 code
```
we use loadrunner test this api(300 concurrents),responses are very slow at the begin 3 minutes,then very fast.
![20190708172251](https://user-images.githubusercontent.com/17214944/60799095-0f4ea980-a1a5-11e9-9a8d-5aa5b2c5c495.png)

we deploy it based on docker
there are about 20 threads after process start, then incresed when loadrunner test begin.

please help us find out why it is slow at the first 3minustes.

**Comment by davidfowl** [comment]
I can't tell you why without looking at a profile, but that's something you should definitely do. Are you CPU bound or IO bound? On easy thing you can try is to make reading the body fully asynchronous:

```C#
using (var reader = new System.IO.StreamReader(context.Request.Body, 
        System.Text.Encoding.UTF8))
 {
     inputBody = await reader.ReadToEndAsync();
 }
```

How big is the body usually (number of bytes)?

**Comment by SmartKarren** [comment]
we use aws ec2 c3.large machine
we update .net core version from 2.1 to 2.2 and UseLibuv when build host startup.
then this question not show again. but i still not sure why this happen
