### ISSUE TITLE
Unable to connect the azure service from the java using AccessToken and get response "Unexpected status code returned from negotiate: 404 Not Found." from the 

### ISSUE THREAD

**Issue by r6h7b** [aspnet/AspNetCore#11962]
### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @r6h7b.
Please provide more details about your scenario and how you try to do it. Also, a repro project with the behavior you think is broken would help with investigation.

**Comment by r6h7b** [comment]
String url = "https://abc.service.signalr.net/client/?hub=chat";
        HubConnection hubConnection = HubConnectionBuilder.create(url)
                .withAccessTokenProvider(Single.defer(()->{
                    return Single.just("qwertyuiop/qwertyuiop");
                })).build();
 
        hubConnection.start().blockingAwait();
       
        hubConnection.on("Send", (message)->{
        },String.class);
        
        hubConnection.send("Send", "Hello form java");

I am doing with this first i got 404 issue but now i am facing authentication issue.
Unexpected status code returned from negotiate: 401 Unauthorized.
