### ISSUE TITLE
[Blazor] Guidance on limiting circuits per user

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#11966]
We don't have any mechanism that out of the box limits the number of circuits a user/ip can create, but this is achievable through current extensibility.

We should provide a sample that showcases this.

This can be achieved by keeping track of the endpoints that create circuits (for example through a handler on OnCircuitOpened) and capturing information (like the user principal or the client ip address) and using that to limit the connections per server instance.

**Comment by chrdlx** [comment]
What about clients that share the same internet IP ? Which is the typical case for companies that use NAT to give inside users internet access.

**Comment by javiercn** [comment]
Covered as part of https://github.com/aspnet/AspNetCore.Docs/pull/13962/files
