### ISSUE TITLE
Understanding metadata in aspnet core

### ISSUE THREAD

**Issue by TehWardy** [aspnet/AspNetCore#11963]
I'm in the process of converting a solution over from .Net 4.6 and i'm looking at metadata.
In the old solution I had a custom implementation of the data annotations metadata provider which I had extended like this ....

```
   public class ApiMetadataProvider : DataAnnotationsModelMetadataProvider, IDisposable
    {
        public IResourceProvider ResourceProvider { get; }

        public ICoreDataContext CoreDb { get; }

        public ApiMetadataProvider(IResourceProvider resourceProvider, ICoreDataContext core)
        {
            ResourceProvider = resourceProvider;
            CoreDb = core;
        }

        protected override ModelMetadata CreateMetadata(
                IEnumerable<Attribute> attributes,
                Type containerType,
                Func<object> modelAccessor,
                Type modelType,
                string propertyName)
        {
            ModelMetadata modelMetadata = base.CreateMetadata(
                attributes,
                containerType,
                modelAccessor,
                modelType,
                propertyName);

            Type serverType = (modelType == typeof(string))
                ? typeof(string) 
                : modelType.ImplementsGenericInterface(typeof(IEnumerable<>)) ?? modelType;
            
            if (serverType.IsGenericType && serverType.Name.StartsWith("Nullable") && typeof(Nullable<>).MakeGenericType(serverType.GenericTypeArguments) == serverType) { serverType = serverType.GenericTypeArguments[0]; }

            modelMetadata.AdditionalValues.Add("ServerType", serverType.AssemblyQualifiedName);

            SetTemplateHint(modelMetadata);
            SetCustomAttributes(attributes, modelMetadata, modelType, propertyName);
            SetResourceStrings(modelMetadata);

            return modelMetadata;
        }
       ....
}
```

... the key thing here is that I pull the base copy of the model meta for the given type and then manipulate it in my own custom ways (some of which is shown in the sample above).

I cut the rest out because there's quite a bit of it.

The net result is that from my own base generic controller I had an action that looked like this ...

```
protected MetadataContainer GetMetadataForType(Type type)
{
         return new MetadataContainer(MetaProvider.GetMetadataForType(null, type));
}
```

Controllers would then often make decisions based on this.

I am looking to reproduce this behaviour, the key thing being the ability to get a customised version of the "final meta" from the stack (I gather from this: https://github.com/aspnet/Mvc/issues/2522 ... that meta is now a "chain of providers" in some fashion).

So I have a couple of questions ....

  1. How can i add or remove / update custom "properties" / attributes in the meta information for a given type?
  2. How can I get an instance of the meta that the stack sees as being the "final result" after all providers have been executed?
  3. The existing solution often handed this meta information to client JS code to allow for "dynamic component construction" in the browser, is this a scenario that has any form of best practice that I can gather more advice from (perhaps you guys have a blog post or something to get me started)?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by TehWardy** [comment]
Sounds good, i'll repost to SO and link this, hopefully whoever answers over there might answer here too.

**Comment by TehWardy** [comment]
Link back to help keep everything in sync ...

https://stackoverflow.com/questions/56937393/understanding-metadata-in-aspnet-core
