### ISSUE TITLE
[Blazor] Add a timeout for idle circuits

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#11965]
When a circuit hasn't sent an event in a given period of time, close the circuit.

**Comment by darraghjones** [comment]
What was the outcome of this ticket? Is there an idle timeout?

**Comment by mkArtakMSFT** [comment]
We've decided not to do this as this won't add value.

**Comment by nagytam** [comment]
@mkArtakMSFT:
I would need also a timeout handling for the circuits ("sessions"). May I kindly ask why it was decided that this "won't add a value"? Thanks!
