### ISSUE TITLE
Log authentication failures in JWT Bearer handler

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#11973]
See https://github.com/aspnet/AspNetCore/issues/11920 for some background.

We should log the authentication failures that occur when processing a JWT token in the JWT bearer handler.

Per @blowdart suggestion: We should log a generic message, with perhaps information on how to get more detailed information (since the token may contain PII).

Perhaps something like (wordsmithing needed)

```
JWT validation failed. For more details, handle the OnAuthenticationFailed event and check the Exception property
```

Or we could use a more detailed logging level to include details.

The specific error that was occurring in https://github.com/aspnet/AspNetCore/issues/11920 was:

```
Audience validation failed. 
Audiences: 'https://xxx.xxxxx/'. 
Did not match: validationParameters.ValidAudience: 'https://yyy.yyyyy/' 
or validationParameters.ValidAudiences: 'null'
```

**Comment by Tratcher** [comment]
There are already multiple logs here.
https://github.com/aspnet/AspNetCore/blob/7a1b867d394040533d478e14d65d963248377d6b/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L114
https://github.com/aspnet/AspNetCore/blob/7a1b867d394040533d478e14d65d963248377d6b/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L178

And response details:
https://github.com/aspnet/AspNetCore/blob/7a1b867d394040533d478e14d65d963248377d6b/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L204

**Comment by Tratcher** [comment]
Note TokenValidationFailed defaults to Information level so the customer may have been filtering it out.

**Comment by anurse** [comment]
Agreed, we should have sufficient logs here already.
