### ISSUE TITLE
Fail on startup for Http/2 HTTPS on Windows 7

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#11970]
Following up on https://github.com/aspnet/AspNetCore/issues/11061. We should also fail fast on Windows 7 where there is no ALPN support. 

As a further consideration, is the platform the only way to determine ALPN support. How would this work on Linux?

**Comment by JunTaoLuo** [comment]
cc @shirhatti

**Comment by anurse** [comment]
We'll talk about this in triage, rather than assigning it to me :).
