### ISSUE TITLE
AuthenticationSchemeOptions.ForwardSignOut comment example is incorrect

### ISSUE THREAD

**Issue by serpent5** [aspnet/AspNetCore#11978]
The summary comment for `AuthenticationSchemeOptions.ForwardSignOut` states:

> For example Context.SignOutAsync("ThisScheme") => Context.SignInAsync("ForwardSignOutValue");

It should be `SignOutAsync` instead of `SignInAsync`.

This error is also present in the docs, which I've rasied an issue for at https://github.com/aspnet/AspNetCore.Docs/issues/13198.

**Comment by blowdart** [comment]
Would you like to open a PR for this?

**Comment by serpent5** [comment]
Sure - I'm just doing a PR for the docs issue so I'll do this straight after. Starting small... :smiley:

**Comment by blowdart** [comment]
@HaoK can you look at the PR when it pops up and merge as appropriate? :)
