### ISSUE TITLE
Restricting controller ports in Kestrel

### ISSUE THREAD

**Issue by msft-mw** [aspnet/AspNetCore#11985]
I'm investigating Kestrel and asp .net core, coming from a legacy stack, and I'm curious if something is possible.

I want my controllers to listen on `https:443`, and my health checks on `http:80` and`http:8080`. I know how to configure Kestrel to listen on all three ports, but what I don't know is how to restrict my controllers to only listen on `443`.

Some details:

- Kestrel, on the edge with no reverse proxy
-  This is a pure REST API with no pages or UI associated
- Currently using attribute-based routing

Is there a way to do this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @msft-mw.
@rynowak, @glennc can you please look into this? Thanks
