### ISSUE TITLE
Model binding of MVC doesn't work with c# fields.

### ISSUE THREAD

**Issue by GibbOne** [aspnet/AspNetCore#11998]
By using `FromForm` attribute, I am trying to bind a DTO like this.

``` c#
        public class Credentials
        {
            public string username;
            public string password;
            public string grant_type;
        }
```
But I can't because it owns c# fields and not properties.

It could be useful to allow binding also for fields.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GibbOne .
This is not something we've received many asks for. If, however, we hear many asks for this from the community, we may reconsider.
