### ISSUE TITLE
DotNet core 3.0 has crazy requestheader sizes due to .AspNetCore.Cookie

### ISSUE THREAD

**Issue by ibruynin** [aspnet/AspNetCore#11997]
### Describe the bug
We have a custom ASP.NET core 3.0 application with Azure AD authentication.
When I log into that application with my company AD account, the request header size goes over 32Kb (32.918 KB) due to the inclusion of 
* .AspNetCore.Cookies: chunks-9
* .AspNetCore.CookiesC1 
* ... 
* .AspNetCore.CookiesC9 

This causes AAG to fail with a bad request response:
```
400 Bad Request
Request Header Or Cookie Too Large
Microsoft-Azure-Application-Gateway/v2
```
and that value is non-configurable (cfr. references)

For the same AD account and an ASP.NET Core 2.1 application I see only one cookie:
* .AspNetCore.AzureADCookie

which results in a request header size of (4.984 KB) 

[Edit] 
This is because the "app registration" is not configured to send "securityGroup" "memberships" in the manifest. In order to do so
```
"groupMembershipClaims": null,
```
must be replaced with
```
"groupMembershipClaims": "SecurityGroup"
```
[EndEdit]

### To Reproduce
1. Using 3.0preview5 of ASP.NET Core
2. Create a web app
3. Add Azure AD auth (cfr. below)
4. Login with my account (sorry about this one, my colleagues don't have the issue)
5. Inspect request header (size)

```
services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
            .AddAzureAd(options => Configuration.Bind("AzureAd", options))
            .AddCookie();
```

### Expected behavior
I'd expect reasonable cookie size (as is the case - for the same AD account - in asp dotnet core 2.1)

[Edit]
When the app registration is configured to send "SecurityGroups" as part of the cookie(s), the request header size starts to grow - grow over the limits of Azure Application Gateway (which cannot be configured). This means that all apps in AKS cannot function properly anymore for users with large sets of Azure AD group memberships.
Apparently, there is a mechanism in place "groups overage claim" (described here: https://azure.microsoft.com/nb-no/resources/samples/active-directory-dotnet-webapp-groupclaims/) that should prevent this issue, but that's only activated as of 200 group memberships and the 32Kb limit (of AAG) is already exceeded way before hitting that number.
[EndEdit]

### Screenshots
n/a

### Additional context
n/a

### References
* https://social.msdn.microsoft.com/Forums/en-US/d4527164-f71a-4ba4-b427-1a0b6097ae04/is-there-a-maxrequestheaderstotalsize-setting-for-azure-application-gateway?forum=WAVirtualMachinesVirtualNetwork#7c7b4e50-fbf8-486f-89c8-a2b997c3eeb0
* https://twitter.com/IBruyninckx/status/1148255152157184001?s=20
[Edit]
* https://azure.microsoft.com/nb-no/resources/samples/active-directory-dotnet-webapp-groupclaims/
* https://www.red-gate.com/simple-talk/dotnet/net-development/using-auth-cookies-in-asp-net-core/
[EndEdit]

**Comment by blowdart** [comment]
How many roles/groups is your user in? It sounds like you've configured the AAD application to send them all.

**Comment by ibruynin** [comment]
I'm a member of 154 groups - so it appears
Is there a way to limit the number of groups you want in the app then?
It would make a lot of sense, but I haven't found that somewhere

**Comment by blowdart** [comment]
I'm not an AAD person, but there's a manifest for each app registration and that has a `groupMembershipClaims` settings which can be used to limit.

https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest has details

**Comment by los93sol** [comment]
@ibruynin I've run into similar with cookies auth against local AD when users are in a ton of groups.  I leverage the TicketStore to get around the issue.  This also gives you an easy scaleout advantage too since you can either just use a local memory cache based implementation, hook it to a db, or even to Redis.  When you use the TicketStore the data is kept server side and just an id goes back to the client so the whole giant cookie isn't being shipped to the server on each and every request which also lightens your network load a bit.

**Comment by ibruynin** [comment]
> 
> 
> I'm not an AAD person, but there's a manifest for each app registration and that has a `groupMembershipClaims` settings which can be used to limit.
> 
> https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest has details

I've configured this already to "groupMembershipClaims": "SecurityGroup"
But that does not really help, since the security groups are the issue.

Is it a strange idea to configure the groups you're interested in - and only those - in the application?
The cookies then would only contain the necessary information...

**Comment by blowdart** [comment]
It's kind of backwards to my mind, because it should be AD that enforces what an application sees, rather than have an app ask for "is this user in SuperSecretExtraSalaryGroup?"

**Comment by blowdart** [comment]
But also yes, as @los93sol says using reference cookies and a backend that is shared between instances of your app also works

**Comment by ibruynin** [comment]
> 
> 
> @ibruynin I've run into similar with cookies auth against local AD when users are in a ton of groups. I leverage the TicketStore to get around the issue. This also gives you an easy scaleout advantage too since you can either just use a local memory cache based implementation, hook it to a db, or even to Redis. When you use the TicketStore the data is kept server side and just an id goes back to the client so the whole giant cookie isn't being shipped to the server on each and every request which also lightens your network load a bit.

I found a link that explains ticketstore quite well: https://www.red-gate.com/simple-talk/dotnet/net-development/using-auth-cookies-in-asp-net-core/
That seems to circumvent the issue, but now the app is stateful and does not scale out anymore.
And that's a pity in an AKS cluster :/

A colleague also found out that Azure AD is doing something similar as of 200 groups.
So I need to define 46 more (😉) or try to force that "groups overage claim" behavior described here: https://azure.microsoft.com/nb-no/resources/samples/active-directory-dotnet-webapp-groupclaims/

Then you need to query the Graph API to retrieve the memberships.

**Comment by los93sol** [comment]
@ibruynin You can still scaleout just fine if you implement the ticketstore with any type of distributed cache or a db.

**Comment by ibruynin** [comment]
> 
> 
> @ibruynin You can still scaleout just fine if you implement the ticketstore with any type of distributed cache or a db.

true - I got that, but did not find a good example on that one. Must be out there somewhere, right?
And I'm not sure if we want to go that way. I'd expect that those security libs handle all those issues for you. But now AKS and AAG are around, those issues start to surface, since they cannot be configured for those ridiculously large request headers

**Comment by los93sol** [comment]
@Ibruyin  I think this article will help https://mikerussellnz.github.io/.NET-Core-Auth-Ticket-Redis/

**Comment by ibruynin** [comment]
> 
> 
> @Ibruyin I think this article will help https://mikerussellnz.github.io/.NET-Core-Auth-Ticket-Redis/

Thanks! will have a look into it tomorrow :)

**Comment by anurse** [comment]
There isn't anything actionable here since we just store all the claims provided by the identity provider.
