### ISSUE TITLE
How to set  ServerGarbageCollection by environment variables

### ISSUE THREAD

**Issue by dingsongjie** [aspnet/AspNetCore#11993]
How to set  ServerGarbageCollection by environment variables , Or Set ServerGarbageCollection in Runtime

**Comment by davidfowl** [comment]
It's set by default in ASP.NET Core projects. Are you trying to turn it off?

**Comment by dingsongjie** [comment]
> It's set by default in ASP.NET Core projects. Are you trying to turn it off?

Yes ,In some test environments ,I want to turn it off

**Comment by davidfowl** [comment]
cc @jkotas @maoni0

**Comment by gfoidl** [comment]
See https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md

So `COMPlus_gcServer=0`.

For completeness:

```xml
<!-- in csproj -->
<PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
</PropertyGroup>
```

or in `*.runtimeconfig.json`:
```json
{
  "runtimeOptions": {
    // ...
    "configProperties": { 
      "System.GC.Server": false 
    }
  }
}
```

**Comment by dingsongjie** [comment]
> COMPlus_gcServer=0

thank you for help!!
