### ISSUE TITLE
Custom validation attribute not firing when value is null (Razor Pages)

### ISSUE THREAD

**Issue by manuelsidler** [aspnet/AspNetCore#11994]
When you create a custom validation attribute and use it on a binded property directly on a Razor page, it won't get fired when the value of the property is null. On the other hand, when you use it on a property inside a class, the attribute will be triggered with a null value.

1. Use ASP.NET Core Version 2.2.300

2. Create a web project
`dotnet new webapp`

3. Create a custom validation attribute
``` csharp 
public class MyValidation : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            return ValidationResult.Success;
        }
    }
```

4. Bind a string property inside Index.cshtml.cs and use the custom validation attribute
``` csharp
public class IndexModel : PageModel
    {
        [MyValidation]
        [BindProperty]
        public string MyProperty { get; set; }

        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            return RedirectToPage("Index");
        }
    }
```

5. Add a simple form to Index.cshtml
``` html
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<form method="post">
    <input type="text" asp-for="MyProperty">
    <input type="submit" value="Click me">
    <span asp-validation-for="MyProperty"></span>
</form>
```

6. Set a break point inside the _IsValid_ method of the custom validation attribute

7. Run the application

8. Put a value into the input and press the submit button (break point hits)

9. Submit the button without an input value (break point doesn't hit)

10. Move the string property into a separate model class
``` csharp
public class MyModel
    {
        [MyValidation]
        public string MyProperty { get; set; }
    }
```

11. Use the model class as binded property in Index.cshtml.cs
``` csharp
public class IndexModel : PageModel
    {
        [BindProperty]
        public MyModel MyModel { get; set; }

        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            return RedirectToPage("Index");
        }
    }
```

12. Adjust the form in Index.cshtml
``` html
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<form method="post">
    <input type="text" asp-for="MyModel.MyProperty">
    <input type="submit" value="Click me">
    <span asp-validation-for="MyModel.MyProperty"></span>
</form>
```

13. Repeat step 7-9 (this time the break point hits also with an empty input)

Expected behavior:
The custom attribute will get fired whether the value is null or not.

Additional context:
One would ask why I need to handle null values. In our case a null value is valid if some conditions in the validation context are met.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @manuelsidler.
This is not how the current validation subsystem works. You must use the `RequiredAttribute` to validate the value is not null first, then only the Validation logic will kick in.
