### ISSUE TITLE
Unexpected status code returned from negotiate: 401 Unauthorized.

### ISSUE THREAD

**Issue by r6h7b** [aspnet/AspNetCore#12001]
String url = "https://example.service.signalr.net/client/?hub=myHub";
            HubConnection hubConnection = HubConnectionBuilder.create(url)
                    .withAccessTokenProvider(Single.defer(() -> {
                        return Single.just("5WZFiYkGOAtqj/asdassdasddfg123dsfv1egrBcAc=");
                    })).build();

            hubConnection.start().blockingAwait();

            hubConnection.on("Send", (message) -> {
            }, String.class);

            hubConnection.send("Send", "Hello form java");

i am working on azure signalr services but when i am going to connect response get against the request it says unauthorized but i don't know why token is correct.

**Comment by BrennanConroy** [comment]
Usually when connecting to the SignalR service your client points to the server and is redirected automatically to connect to the service.

You can see some of the details of how this works at: https://docs.microsoft.com/azure/azure-signalr/signalr-concept-internals#client-connections

Is there a reason you're trying to connect directly to the service?

**Comment by r6h7b** [comment]
i just want to communicate with the web that is why i am connecting to the server but i unable to connect to server or web that redirect me to the azure signalR service.
what i can do please give me code hint that i helps me to connect.

**Comment by BrennanConroy** [comment]
Change the url to your server instead of the service. So something like "https://www.aspnetcoreserver/myHub".

And make sure the access token you're passing is valid and expected by your web server.

A 401 means that you're not authorized and that makes sense in your case because the Azure SignalR Service won't know about a random access token unless it produced it and gave it to you. (And it hasn't expired).

**Comment by r6h7b** [comment]
HubConnection hubConnection = HubConnectionBuilder.create("http://testchat.testmyapp.com/ChatHub")
                    .withAccessTokenProvider(Single.defer(() -> {
                        // Your logic here.
                        return Single.just("abcdefghijklmnopqrstuvwxyz");
                    }))
                    .build();
            
            hubConnection.start();
            Thread.sleep(5000);
            hubConnection.send("Send", (Object) new String[]{"name", "success"});


Now i am getting this *The 'send' method cannot be called if the connection is not active*

**Comment by BrennanConroy** [comment]
You're not waiting on `hubConnection.start()` and it's probably failing with an error.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
