### ISSUE TITLE
Add the ability to configure timeout for UseAngularCliServer

### ISSUE THREAD

**Issue by marlon-tucker** [aspnet/AspNetCore#12004]
### Is your feature request related to a problem? Please describe.
We have a complex Angular application, which unfortunately goes over the 50 second timeout period, causing an exception to be thrown:

```
An unhandled exception has occurred while executing the request.
System.TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 50 seconds. Check the log output for error information.
```
I had a quick look over the Javascript Services code in github but couldn't find where that 50 second timeout was being defined.

Luckily once the `ng serve` command does complete, we can refresh the browser and it behaves as normal, so it's just a minor annoyance when developing. 

### Describe the solution you'd like

We would like the ability to extend / configure the period the Javascript Services code waits for the `ng serve` command to respond before timing out.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @marlon-tucker.
This is configurable via `SpaOptions.StartupTimeout` property, which defaults to 50 seconds, as you've noticed:  https://github.com/aspnet/AspNetCore/blob/7269dbb73f4aa0ebf5ebb8bc07a076ee181851be/src/Middleware/SpaServices.Extensions/src/SpaOptions.cs#L76

Trying to find out how would you pass it from the `Startup` class. Will share more findings soon.

**Comment by mkArtakMSFT** [comment]
So you can do this in the `Startup.Configure` method, as follows:

![image](https://user-images.githubusercontent.com/34246760/60911748-be889080-a238-11e9-89ec-2dce6c60333a.png)

**Comment by marlon-tucker** [comment]
oh, my apologies. Thank you for pointing this out.
