### ISSUE TITLE
ASP.Net Core 2.1 application cannot find appsettings.json when ran as a Windows service

### ISSUE THREAD

**Issue by dcadlereii** [aspnet/AspNetCore#12013]
I am trying to run my ASP.Net Core 2.1 application as a service on Windows 10. My application runs fine when ran using VS2017 or if I publish to a folder and then start it from within that published folder with the --console arg. However, if I use sc create to create the service, getting a Success result, and then try to run it, I get an error in the Windows Application log stating...

    System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\WINDOWS\system32\appsettings.json'.
    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)   

I have confirmed that my appsettings.json file exists in the published folder. 
The error message states that is is looking in the C:\WINDOWS\system32\ folder for the appsettings.json file rather than the published folder where the application .exe resides. This leads me to think the issue is with the way the current directory is being set when ran as a service, but I am having trouble identifying exactly why it is not working. 

I have set up my Program.cs by following the instructions in [this Microsoft document][1]. My program.cs is shown below;

    public class Program
    {

        public static IConfiguration Configuration { get; } = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
            .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", optional: true)
            .AddUserSecrets<Startup>()
            .Build();

        public static void Main(string[] args)
        {
            ConfigureSerilog();

            // Set up to run as a service if not in Debug mode or if a command line argument is not --console
            var isService = !(Debugger.IsAttached || args.Contains("--console"));
            if (isService)
            {
                var processModule = Process.GetCurrentProcess().MainModule;
                if (processModule != null)
                {
                    var pathToExe = processModule.FileName;
                    var pathToContentRoot = Path.GetDirectoryName(pathToExe);
                    Directory.SetCurrentDirectory(pathToContentRoot);
                }
            }

            var builder = CreateWebHostBuilder(args.Where(arg => arg != "--console").ToArray());
            var host = builder.Build();
            if (isService)
            {
                host.RunAsCustomService();
            }
            else
            {
                try
                {
                    Log.Information("Starting CAS API in Program.cs");
                    host.Run();
                }
                catch (Exception ex)
                {
                    Log.Fatal(ex, "CAS API Host terminated unexpectedly");
                }
                finally
                {
                    Log.CloseAndFlush();
                }
            }
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext, logging) => { logging.AddEventSourceLogger(); })
                .ConfigureAppConfiguration((context, config) =>
                {
                    // Configure the app here.
                })
                .UseStartup<Startup>()
                .UseSerilog()
                .UseUrls("https://localhost:60026"); //This is only used when ran as a stand-alone service. Not in VisualStudio
        
        private static void ConfigureSerilog()
        {
            // Set up Serilog
            var connectionString = Configuration.GetConnectionString("CasDbConnectionString");
            const string tableName = "Logs";

            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                .Filter.ByExcluding(Matching.FromSource("Microsoft.EntityFrameworkCore.Query"))
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .Enrich.WithThreadId()
                .Enrich.WithUtcTimeStamp()
                .Enrich.WithProperty("Application", $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}")
                .Enrich.FromLogContext()
                .CreateLogger();

        }

I have tried replacing the...

    host.RunAsCustomeService();

with ...

    host.RunAsService();

And I still had the same problem.

I am running the sc command as follows;

    sc create casapi start= auto binPath= c:\deployments\casapi\casapi.exe

And I see the casapi service listed in Windows Services. But if I run the sc command...

    sc start casapi 

I get the error indicated above. 

If I go to the published folder in an elevated command prompt and type...
    casapi.exe --console
The application runs as expected.

The casapi service is installed to Log On as a local system account.

 
**UPDATE 7/8/19 @ 5:41p EST** - If I follow the instructions on the [Microsoft page](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2&tabs=visual-studio) to create the local user account and run the Powershell script for installing the service, then start the service, I get the same error as described above.
 

  [1]: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2&tabs=visual-studio

**Comment by DAllanCarr** [comment]
`AppContext.BaseDirectory` worked in earlier versions.

**Comment by glennc** [comment]
I assume that the working directory, and as such `GetCurrentDirectory`, is `system32` and as such you want something like `System.AppDomain.CurrentDomain.BaseDirectory` or `System.Reflection.Assembly.GetEntryAssembly().Location` to give you where the actual executing binary is.

**Comment by anurse** [comment]
Perhaps `UseWindowsService` should change the content root to `AppContext.BaseDirectory`. As you said, the current directory isn't really useful in that context...

**Comment by dcadlereii** [comment]
Thanks to all who commented on this issue. As it turned out, the problem stemmed from that call to ConfigureSerilog() being before the Directory.SetCurrentDirectory(pathToContentRoot); When I moved ConfigureSerilog() after the Directory.SetCurrentDirectory(pathToContentRoot); it started working.
