### ISSUE TITLE
SignalR - HubConnection public static?

### ISSUE THREAD

**Issue by TinoMclaren** [aspnet/AspNetCore#12016]
With ref to SignalR core.

In a Wpf Client, is is ok to use the HubConnection as a public static property?

`public static HubConnection _hubConn { get; set; }`

So that it can be accessed globally within the App?

If not, whats to preferred way to use the HubConnection in a desktop client?

**Comment by davidfowl** [comment]
Yep, that works fine. The HubConnection is itself thread safe.

PS: A property with the name `_hubConn` triggers me. Call it `HubConnection` or `Connection` 😄

**Comment by TinoMclaren** [comment]
Thanks & thanks.

The name was remnants of a failed di attempt. 'triggers me' great turn of phrase  :smiley:

It was originally called ConMan he he
