### ISSUE TITLE
Bug on client's styling

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#12032]
Hi. I work with blazor 3. I have noticed that everything is related to style and it may not work. For example, in a font change project, it does not work in the other project. And this applies to different templates and components.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/587005/bug-on-clients-styling.html
VSTS ticketId: 900940_
_These are the original issue comments:_

Visual Studio Feedback System on 5/29/2019, 02:24 AM (41 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 5/30/2019, 02:09 AM (40 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi.

To be able to assist you, please provide us a small project which we can use to understand the problem you're facing as well as be able to repro it.

**Comment by mkArtakMSFT** [comment]
Closing as we heard no response here for quite a while.
