### ISSUE TITLE
Visual Studio 2019 SDK 2.2 Does not create ASP.NET Core Web Application with Angular Correctly

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#12038]
SDK 2.2 doesn't create a working web application with Angular. When I drop back to SDK 2.1, I get a working application.

Note: The screenshot or environment details can be misleading as I am not in the failing project while I'm reporting this issue.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/603105/visual-studio-2019-sdk-22-does-not-create-aspnet-c.html
VSTS ticketId: 916762_
_These are the original issue comments:_

Visual Studio Feedback System on 6/11/2019, 11:08 PM (27 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 6/12/2019, 11:12 PM (26 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please share more details about what is actually failing for you?

**Comment by ryanbrandenburg** [comment]
Specifically what are the error messages you're seeing and/or expected vs actual results.

**Comment by ryanbrandenburg** [comment]
Without more info we're unable to assist, so I'm going to close this issue. If you are still experiencing this issue please re-open and comment with the details requested above.
