### ISSUE TITLE
用netcoreapp2.1 搭建页面遇到 InvalidOperationException 问题-Encounter InvalidOperationException problems with netcoreapp2.1 building pages

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#12037]
<p>新手在学 ASP.NET Core</p><p>用 netcoreapp2.1 搭建不含model 的页面 在布局时 用 &lt;partial name=&quot;&quot; /&gt; 遇到个问题 用这个时一直报</p><p>“An unhandled exception occurred while processing the request.
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'CmsAspCore.Pages.IndexModel', but this ViewDataDictionary instance requires a model item of type 'CmsAspCore.Pages.NavigationModel'.
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(object value)”</p><p>不知道是哪里的问 求教 谢谢</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/77713-6.png"> Image:77713-6.png</a></p><p>index页面</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/77714-2.png"> Image:77714-2.png</a></p><p>_Layout页面</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/77715-3.png"> Image:77715-3.png</a></p><p>嵌套页面 Naviga</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/77716-5.png"> Image:77716-5.png</a></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/600820/用netcoreapp21-搭建页面遇到-invalidoperationexception-问题.html
VSTS ticketId: 915807_
_These are the original issue comments:_

Visual Studio Feedback System on 6/10/2019, 11:12 PM (28 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 6/11/2019, 01:48 AM (28 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

Jane Wu [MSFT] on 6/11/2019, 07:26 PM (28 days ago): <p>Translated from Bing:</p><p>Beginner is learning ASP.NET Core<br>Use netcoreapp2.1 to build pages that do not contain model in the &lt;partial name=""""&gt;&lt;/partial&gt; layout with a problem encountered when using this has been reported "An unhandled exception occurred while processing the request.  Invalidoperationexception:the model item passed into the ViewDataDictionary are of type ' CmsAspCore.Pages.IndexModel ', but This ViewDataDictionary instance requires a model item of type ' CmsAspCore.Pages.NavigationModel '.<br>Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible (object value) " I don't know where to ask for advice.</p><p>Index page</p><p>_Layout page</p><p>Nested pages Naviga</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
The error you're receiving actually tells exactly what the problem is. It indicates and error in your page, and you should make sure you pass a proper type parameter as an input. For questions like this, StackOverflow is a great place to start with, as you'll get your questions answered quickly.

**Comment by netken** [comment]
我也遇到同样的问题，不知道解决没有？
