### ISSUE TITLE
使用VS2019社区版创建的MVC项目，编辑cshtml文件时，需要重新生成，浏览器才能生效-Using the MVC project created by the VS2019 Community Edition, when editing the cshtml file, it needs to be regenerated for the browser to take effect.

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#12035]
<p>VSF_TYPE_MARKDOWNI have two versions of VS2017 and VS2019 on My Computer (WIN7), all of which are community versions,
I built a new asp.net Web core Application on two versions of VS,</p><p>Select the MVC template.
Then discover that the project created on VS2017, starting on 17 or 19,</p><p>Editing the Cshml file, F5 refreshing the browser, is normal.
And the project created on the VS2019, starting, on 17 or 19,
Edit the Cshml file, F5 refresh the browser, the interface is displayed or the previous interface is not edited.</p><p>The browser displays the edited interface only if the VS is restarted.
To prevent it from being a caching problem, I also did tests in browsers such as Firefox,chrome,
And, manually cleaning up the cache, refreshing the interface, or no effect. That's VS2019 's problem, isn't it? Or what do you need to set up?</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/595299/使用vs2019社区版创建的mvc项目编辑cshtml文件时需要重新生成浏览器才能生效.html
VSTS ticketId: 905445_
_These are the original issue comments:_

Visual Studio Feedback System on 6/4/2019, 11:34 PM (34 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 6/5/2019, 07:35 PM (34 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

Are you creating these two projects targeting the same .Net Core SDK version?

**Comment by mkArtakMSFT** [comment]
And what is the version.

**Comment by Homey-ka** [comment]
No, create the two projects simply,and then, start ,modified. Because I am a novice.

**Comment by mkArtakMSFT** [comment]
Thanks, @Homey-ka.
Please provide the result of `dotnet --version` and `dotnet --info` from within folders of both projects.
Also, here is an article about Runtime Compilation, in case it helps: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.2

**Comment by pranavkm** [comment]
Feel free to reopen once you have more details to share.
