### ISSUE TITLE
Bootstrap DateTime control failing in VS 2019

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#12036]
I recently updatd VS 2019 to 16.2.0 Preview 1.0 and noticed that the Bootstrap DateTime pickers no longer work when I debug my web applications. I deploy the web applications into kubernetes and the apps work fine. I tried starting a brand new application, no success. I can go to the author's demo page and everything works fine there as well. Sample code (taken off Index.cshtml):

@model IndexModel
@{
    ViewData[&quot;Title&quot;] = &quot;Home page&quot;;
}

&lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css&quot; crossorigin=&quot;anonymous&quot; /&gt;

&lt;div class=&quot;text-center&quot;&gt;
    &lt;h1 class=&quot;display-4&quot;&gt;Welcome&lt;/h1&gt;
    &lt;p&gt;Learn about &lt;a href=&quot;https://docs.microsoft.com/aspnet/core&quot;&gt;building Web apps with ASP.NET Core&lt;/a&gt;.&lt;/p&gt;
&lt;/div&gt;
&lt;div class=&quot;container-fluid&quot;&gt;
    &lt;div class=&quot;row margin-top-10&quot;&gt;
        &lt;div class=&quot;col-md-4&quot;&gt;
            &lt;div class=&quot;form-group&quot;&gt;
                &lt;div class=&quot;input-group date&quot; id=&quot;dateTimePicker1&quot;&gt;
                    &lt;input type=&quot;text&quot; class=&quot;form-control&quot; name=&quot;dateTimePicker1&quot; /&gt;
                    &lt;span class=&quot;input-group-append&quot;&gt;
                        &lt;span class=&quot;input-group-text border-radius-right&quot; id=&quot;basic-addon2&quot;&gt;
                            &lt;span class=&quot;glyphicon glyphicon-calendar&quot;&gt;&lt;/span&gt;
                        &lt;/span&gt;
                    &lt;/span&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;

@section Scripts
    {
    &lt;script type=&quot;text/javascript&quot; src=&quot;https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;
    &lt;script type=&quot;text/javascript&quot; src=&quot;https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;
    &lt;script type=&quot;text/javascript&quot;&gt;
        $(document).ready(function ($) {
            $('#dateTimePicker1').datetimepicker({
                format: 'LLL'
            });
            $('#dateTimePicker1').on('dp.change', function (e) {
                alert('changed');
            });
        });
    &lt;/script&gt;
}

Any thougths?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/583470/bootstrap-datetime-control-failing-in-vs-2019.html
VSTS ticketId: 899745_
_These are the original issue comments:_

Visual Studio Feedback System on 5/26/2019, 07:47 PM (44 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 6/6/2019, 00:27 AM (33 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
