### ISSUE TITLE
Improving dev workflow alignment with contributor guidelines for sub-areas with additional requirements

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#12030]
Currently our general contributor guidelines do not work in all sub-areas such as Components which have additional requirements. The proposal is to make these additional requirements more visible and the guidelines for working in these areas more explicit and reliable. To this end, some of the following suggestions and/or issues have been raised:

- [x] Create/Update the build.cmd/sh in the sub areas to ensure required dependencies are built and required tools are available.
- [ ] Stop checking in JS artifacts from Web.JS in Components and compile the artifacts at build time. This should make Components builds more in line with the rest of the repo https://github.com/aspnet/AspNetCore/issues/11592
- [ ] Add CI configurations to test a the often-broken developer workflows: https://github.com/aspnet/AspNetCore/issues/12029
- [x] Update our contribution guidelines to include the different requirements (Yarn, NodeJS, Java, etc) need to build the sub-areas and how to restore/build/test.

**Comment by rynowak** [comment]
@jkotalik

**Comment by JunTaoLuo** [comment]
Remaining work item tracked in #12029 but this issue is mostly addressed

**Comment by jkotalik** [comment]
@JunTaoLuo good stuff!

**Comment by JunTaoLuo** [comment]
Had to revert the change so I'm re-opening the issue

**Comment by JunTaoLuo** [comment]
An updated implementation is merged in https://github.com/aspnet/AspNetCore/pull/12744.
