### ISSUE TITLE
Blazor:  how to restrict the static files reference in client-side-blazor-app

### ISSUE THREAD

**Issue by gurunathancs1991** [aspnet/AspNetCore#12039]
**Goal**: 
We need to serve the static files in client-side-blazor-app based on user input on his application. Right now, it will serve all files which placed in `wwwroot` folder in user application.  
**Example**: we have different set of themes for my layout. but it required a theme alone as per user application input. 

For server-side-blazor-app, i can restrict and serve the files using [IapplicationBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.iapplicationbuilder?view=aspnetcore-2.2)  and [StaticFileOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.staticfileoptions?view=aspnetcore-2.2)

Why it could not done the same in client side means,  server-side-blazor app supports `.NETCore` app but `client-side-blazor` app doesn't support `.NetCore` app. since it is `.NetStandard` app

**Comment by SteveSandersonMS** [comment]
Client-side Blazor runs on the client, so it doesn't control anything about what your web server does.

However if you use the "Hosted in ASP.NET Core" version of the client-side Blazor template, then you also get an ASP.NET Core web server project that you can configure in whatever way you want.
