### ISSUE TITLE
Response de-serialisation broken in preview 6 for PostJsonAsync

### ISSUE THREAD

**Issue by owaits** [aspnet/AspNetCore#12041]
After upgrading my project from preview 5 to preview 6 I have discovered that the http helper extension PostJsonAsync<> no longer returns the de-serialized response and simply returns null. This code has worked fine up to preview 6 so seems to be something that has been broken.

```
var autheticationToken = await http.PostJsonAsync<LoginToken>(@"api/login", new LoginToken() { Email = email, Password = password});
```

```
    public class LoginToken
    {
        public string Email { get; set; }

        public string Password { get; set; }

        public string Token { get; set; }

        public bool IsSuccess() { return !string.IsNullOrEmpty(Token); }

        public bool IsDefault() { return Email == "admin" && Password == "admin"; }
    }
```

The value of authentication Token is always null.

If I now download the extension code from GitHub for SendJsonAsync and put this in my class it seems to work. I did have to modify it slightly to use the new ToString and Parse functions.

```
var autheticationToken = await HttpSecure.SendJsonAsync<LoginToken>(http, HttpMethod.Post, @"api/login", new LoginToken() { Email = email, Password = password });
```

```
public static async Task<T> SendJsonAsync<T>(HttpClient httpClient, HttpMethod method, string requestUri, object content)
        {
            var requestJson = JsonSerializer.ToString(content);
            var response = await httpClient.SendAsync(new HttpRequestMessage(method, requestUri)
            {
                Content = new StringContent(requestJson, Encoding.UTF8, "application/json")
            });

            // Make sure the call was successful before we
            // attempt to process the response content
            response.EnsureSuccessStatusCode();

            if (typeof(T) == typeof(IgnoreResponse))
            {
                return default;
            }
            else
            {
                var stringContent = await response.Content.ReadAsStringAsync();
                Console.WriteLine(stringContent);
                return JsonSerializer.Parse<T>(stringContent);
            }
        }
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by owaits** [comment]
I have tracked this issue down to the fact that I was using a custom contract resolver at the server end that was not set to use camel case naming. 

'''
            services.AddMvc(options => { options.OutputFormatters.Insert(0, new iCalFormatter()); })               
                .AddNewtonsoftJson(options =>
                {
                    var scopeFactory = services
                    .BuildServiceProvider()
                    .GetRequiredService<IServiceScopeFactory>();

                    using (var scope = scopeFactory.CreateScope())
                    {
                        var provider = scope.ServiceProvider;
                        using (var resolver = provider.GetRequiredService<MonicaRoleContractResolver>())
                        {
                            options.SerializerSettings.ContractResolver = resolver;
                        }
                    }

                });
'''

If I change the above code to use Camel case naming strategy then this fixes my issue with Post. 

'''
            services.AddMvc(options => { options.OutputFormatters.Insert(0, new iCalFormatter()); })               
                .AddNewtonsoftJson(options =>
                {
                    var scopeFactory = services
                    .BuildServiceProvider()
                    .GetRequiredService<IServiceScopeFactory>();

                    using (var scope = scopeFactory.CreateScope())
                    {
                        var provider = scope.ServiceProvider;
                        using (var resolver = provider.GetRequiredService<MonicaRoleContractResolver>())
                        {
                            resolver.NamingStrategy = new CamelCaseNamingStrategy();
                            options.SerializerSettings.ContractResolver = resolver;
                        }
                    }

                });
'''

I tried to investigate this further with the simplified example bellow. This shows that when PropertyNameCaseInsensitive is set to false it does not de-serialize when the case of the contract does not match the case used in JSON. Although strangely when I run this code it seems to show the reverse, I carnt get my head around that.

...
        public class TestData
        {
            public string Name { get; set; }
        }


        public async Task PostJsonTest()
        {
            var result1 = JsonSerializer.Parse<TestData>("{\"Name\":\"Oliver Waits\"}", new JsonSerializerOptions() { PropertyNameCaseInsensitive = false });

            if (string.IsNullOrEmpty(result1.Name))
                Console.WriteLine($"Fail 1: {result1.Name}");
            else
                Console.WriteLine($"Pass 1: {result1.Name}");

            var result2 = JsonSerializer.Parse<TestData>("{\"name\":\"Oliver Waits\"}", new JsonSerializerOptions() { PropertyNameCaseInsensitive = false });

            if (string.IsNullOrEmpty(result2.Name))
                Console.WriteLine($"Fail 2: {result2.Name}");
            else
                Console.WriteLine($"Pass 2: {result2.Name}");
        }
'''

If I change the above code to case insensitive then they both de-serialize.

'''
        public class TestData
        {
            public string Name { get; set; }
        }


        public async Task PostJsonTest()
        {
            var result1 = JsonSerializer.Parse<TestData>("{\"Name\":\"Oliver Waits\"}", new JsonSerializerOptions() { PropertyNameCaseInsensitive = false });

            if (string.IsNullOrEmpty(result1.Name))
                Console.WriteLine($"Fail 1: {result1.Name}");
            else
                Console.WriteLine($"Pass 1: {result1.Name}");

            var result2 = JsonSerializer.Parse<TestData>("{\"name\":\"Oliver Waits\"}", new JsonSerializerOptions() { PropertyNameCaseInsensitive = false });

            if (string.IsNullOrEmpty(result2.Name))
                Console.WriteLine($"Fail 2: {result2.Name}");
            else
                Console.WriteLine($"Pass 2: {result2.Name}");
        }
'''

So I think this issue boils down to the fact that in the previous preview PostJsonAsync was case insensitive on the JSON property names and now it is not. 

I think possibly there are two discussions to be had. Firstly should PostJsonAsync be case insensitive by default and secondly why does it fail silently with no explanation. I can imagine this could cause you hours of investigation as to why PostJsonAsync is returning an empty string. If it knows there is Json data but it cant de-serialise any of it I am wondering if this should throw an exception.

**Comment by pranavkm** [comment]
@owaits reading JSON is case insensitive as of preview7. This was addressed as part of https://github.com/aspnet/AspNetCore/pull/11254
