### ISSUE TITLE
Blazor is unable to deserialize date in the case of pre-rendering When the date is not set explicitly

### ISSUE THREAD

**Issue by iAmBipinPaul** [aspnet/AspNetCore#12046]
Blazor is unable to deserialize date in the case of pre-rendering When the date is not stated explicitly

After  configuring pre-rendering on ASP.NET Core hosted it works as expected but when I'm configuring the part of the code where the date is being set, it throws an exception 

```
JsonException: The JSON value could not be converted to System.DateTime. Path: $[0].date |
 LineNumber: 0 | BytePositionInLine: 30.
```

Works 

```csharp
 return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
               Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            });
```

Does not work 

```csharp
 return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                //Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            });
```
sample project
https://github.com/iAmBipinPaul/Prerendering

**Comment by iAmBipinPaul** [comment]
Same exception on corefx repo
https://github.com/dotnet/corefx/issues/38568#issuecomment-503405420

**Comment by javiercn** [comment]
I'm not able to repro this with the latest bits. This has likely been a temporary issue within System.Text.Json that must have already been addressed.
