### ISSUE TITLE
Html.PartialAsync is rendering name of input different with Partial Tag Helper

### ISSUE THREAD

**Issue by nthanhcong0** [aspnet/AspNetCore#12049]
### Describe the bug
Html.PartialAsync is rendering name of input different with ```<partial>``` Tag Helper

### To Reproduce
1. Action return a Parent View with Model as below:
    ```
    public class ParentDataViewModel
    {
        public ChildDataViewModel ChildData01 { get; set; }
        public ChildDataViewModel ChildData02 { get; set; }
        public ChildDataViewModel ChildData03 { get; set; }
    }
    ```

2. ChildDataViewModel structure
    ```
    public class ChildDataViewModel
    {
        public int Property01 { get; set; }
        public int Property02 { get; set; }
        public int Property03 { get; set; }
    }
    ```

3. In Parent View, use either one of below to render a partial with ChildDataViewModel as data:
    ```
    @await Html.PartialAsync("_ChildPartialView", Model.ChildData01)
    ```
    Or
    ```
    <partial name="_ChildPartialView" for="ChildData01" />
    ```

4. The Html.PartialAsync will render 3 inputs as below:
    ```
    <form>
        <input id="Property01" name="Property01" />
        <input id="Property02" name="Property02" />
        <input id="Property03" name="Property03" />
        <button type="submit">Submit</button>
    </form>
    ```

5. The <partial> Tag Helper will render 3 inputs as below:
    ```
    <form>
        <input id="Property01" name="ChildData01.Property01" />
        <input id="Property02" name="ChildData01.Property02" />
        <input id="Property03" name="ChildData01.Property03" />
        <button type="submit">Submit</button>
    </form>
    ```

### Expected behavior
The ```<partial>``` Tag Helper should render input with name of input as same as @Html.PartialAsync.

The difference causes changing from Html.PartialAsync to ```<partial>``` will make requested data lost.

### Additional context

dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.107
 Commit:    2212cac826
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nthanhcong0.
This is done by-design and the behavior you see in the `PartialTagHelper` is intended. Our recommendation is to favor `<partial>` tag helper over the `Html.PartialAsync`. If you are looking for the exact same behavior from the `<partial />` you can use the `model` property as follows:
```html
<partial model="Model.ChildData01" />
```
