### ISSUE TITLE
Blazor - client side debugging

### ISSUE THREAD

**Issue by alexiordan** [aspnet/AspNetCore#12043]
Visual Studio 2019 16.2.0 Preview 3
.NET Core SDK: 3.0.100-preview6-012264

Chrome ver. 75....

I am able to open the DevTools window and see the C# code in browser However when I try to set a breakpoint, it fails with following message in asp.net core console
```
BP request for 'BreakPointRequest Assembly: bapp.dll File: ~/Pages/Counter.razor Line: 13 Column: 8' runtime ready True location ''
Could not resolve breakpoint request: BreakPointRequest Assembly: bapp.dll File: ~/Pages/Counter.razor Line: 13 Column: 8
BP req {
  "lineNumber": 13,
  "url": "file:~/bapp/Pages/Counter.razor",
  "columnNumber": 8,
  "condition": ""
}
```

What am I doing wrong?

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#15649
