### ISSUE TITLE
[Blazor] StartCircuit should check for an existing circuit.

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#12054]
We should not allow StartCircuit to be called more than once and in case a circuit exists, simply render any non prerendered component and return.

Otherwise I can create multiple circuits by just spamming StartCircuit.

**Comment by rynowak** [comment]
What data do you have that helps us understand the priority of this?

**Comment by javiercn** [comment]
I invoked StartCircuit repeatedly with Ignitor and saw it create multiple circuits.

**Comment by javiercn** [comment]
![image](https://user-images.githubusercontent.com/6995051/60991285-1b4e7e80-a2ff-11e9-8a86-f0bbd45d7969.png)
