### ISSUE TITLE
ServerSide Blazor - Dispose method doesn't get called on App.razor (Preview 6)

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#12063]
### Describe the bug
-I'm using Preview6 default Server Side Blazor Template.

-I've found that if the App.razor component implements IDisposable, and you provide a Dispose() method, it doesn't get called at all **when you close the browser window**.

-This doesn't happen with other components, like index or counter, in which Dispose() method is called as expected when IDisposable is implemented and browser window is closed.

I'm not sure if this is by design or a bug indeed.  I guess if Dispose isn't called, this could lead to a potential memory leak.

---
-I've just tested again... this happens with any blazor component used from a razor page (probably from a mvc view too) with
@(await Html.RenderComponentAsync<TestComponent>())

Regards!!

**Comment by chrdlx** [comment]
After more testing I've discovered that refresing the browser with CTRL+F5,  eventually,  after approximately 50 refreshes   the Dispose method starts getting called.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrdlx.
There was a bug in Preview 6, where things wouldn't get disposed without further requests hitting the server. This has been fixed for preview 7. However, the `Dispose` method isn't called immediately when you close the browser, as the disconnection notification is not guaranteed to happen. What we do, is actually have a timeout after which the component will get disposed (if not more requests come in).
