### ISSUE TITLE
Compiled views don't get processed by the IL linker

### ISSUE THREAD

**Issue by sbomer** [aspnet/AspNetCore#12064]
### Describe the bug
https://github.com/mono/linker/issues/652

PublishTrimmed=true breaks ASP.NET Core applications, because the Razor SDK adds the Razor compiled view assembly to the itemgroup ResolvedFileToPublish, *after* the same itemgroup gets processed by the linker. The result is that the linker does not see the views assembly, and removes dependencies needed by it.

See the bug above for repro steps.

The Razor SDK adds to ResolvedFilesToPublish here: https://github.com/aspnet/AspNetCore-Tooling/blob/fbcd0c241675d7f346b3d233f2d7a5cb464fb3e4/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L785, which is too late for it to be input to the linker. The linker runs here: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L380.

### Additional context
Reproduced with version `3.0.100-preview7-012515` on macOS 10.14.

Relevant to https://github.com/dotnet/sdk/issues/3109. We should ensure that a solution to this continues to work even if we do work to formalize the linker inputs in the future. More broadly, this belongs to the class of ordering issues described in https://github.com/dotnet/sdk/issues/2583.

@rynowak

**Comment by rynowak** [comment]
I worked with @sbomer - to try and figure this out, basically we should fix this because without it the `.Views` assembly is not being considered properly, so stuff that's only used in views won't be rooted.

**Comment by nguerrera** [comment]
I'm looking at https://github.com/dotnet/sdk/issues/3109 now. Seems there is some potential for that to break this if we don't coordinate on this. Is anyone actively working on this part, and if so is there a proposed change I can test with?

**Comment by rynowak** [comment]
I haven't started looking at this yet, but you can coordinate with me and @pranavkm

**Comment by nguerrera** [comment]
OK, I will make an affordance to specify arbitrary additional managed assemblies to pass to linker and you can add to that extension point. I will put the details here if/when the dotnet/sdk#3109 fix goes in.

**Comment by rynowak** [comment]
Thanks @nguerrera
