### ISSUE TITLE
[Blazor] Support for wasm blazor integration with existing mvc app

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#12061]
### Is your feature request related to a problem? Please describe.
While I was experimenting on embedding blazor client side (wasm) in an existing mvc app, it seems that it is close enough to be easily implemented, however some changes are needed to have this scenario supported (in which I am very interested).

For example, the following scenario kinda works:

_**Having 2 projects, an mvc core app and a blazor clientside app**_

#### Mvc App (references the blazor client project)
```cs
//Startup.cs
app.UseClientSideBlazorFiles<Client.Startup>();
```
```html
<!-- Shared/_Layout.cshtml -->
<head>
  <!-- ... -->
  <base href="~/" />
  <!-- ... -->
</head>
<body>
   <!-- ... -->
   <script src="_framework/blazor.webassembly.js"></script>
</body>
```
```html
<!-- Home/Index.cshtml -->
<counter>Loading ...</counter>

@*Or using prerendering*@
@*<counter>@(await Html.RenderStaticComponentAsync<Counter>())</counter>*@
```

#### Blazor Client App
```cs
public class Startup
{
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IComponentsApplicationBuilder app)
        {
            app.AddComponent<Counter>("counter");
        }
}
```

This works fine for the Index.cshtml page however if you navigate to an other page (or add another component) you get an exception like this
```
WASM: Error: Could not find any element matching selector 'counter'.
```

### Describe the solution you'd like
Full support for embedding blazor client-side (wasm) in existing MVC applications. 

IMHO it will help with adoption tremendously and is a very nice alternative for people who do not want to use server-side blazor to do the same thing.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @stavroskasidis.
You're not supposed to reference the blazor script in a page, which isn't meant to host a `component`. That's what results in the error you see.
