### ISSUE TITLE
Blazor Server Side Localization not working

### ISSUE THREAD

**Issue by aherrick** [aspnet/AspNetCore#12088]
Trying to stand up a super simple example of Blazor Server Side with Localization/Translation support.

I posted the spike here: https://github.com/aherrick/BlazorServerSideLocalization

It appears in my `Index.razor` view `@inject IViewLocalizer L` is always null. I have a `Resources` folder with a `Pages.Index.en.resx`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @aherrick.
`IViewLocalizer` is an MVC feature and can't be used with Blazor. You can use the resource files directly yourself to read localized resources.

**Comment by aherrick** [comment]
@mkArtakMSFT do you have an example of this within the context of Blazor or the example I posted?

**Comment by mkArtakMSFT** [comment]
@aherrick not really. I'll leave this as a question for community members to help you out with.

**Comment by aherrick** [comment]
OK - it would be nice if there was some documentation or examples on how to do Localization with Blazor.

**Comment by christiansparre** [comment]
@aherrick 

I whipped together something very crude last week as I ran into the same problem and I needed a quick fix for it. I ended up with something along the lines of the following. Maybe it can send you on the right track for your needs.

See this gist: https://gist.github.com/christiansparre/5576907ad391b972581714f7564674b7

* There is a TextService class pulling strings from resource files
* There is a LocalizedText blazor component displaying the text in the currently selected culture
* There is a CultureChanger class that can be used to change the "current" culture, that also has an event the LocalizedText component listens for

**Comment by aherrick** [comment]
@christiansparre Awesome! Are you initializing TextService as a singleton?

**Comment by christiansparre** [comment]
Yes @aherrick it's registered as singleton

**Comment by SeppPenner** [comment]
What about `IStringLocalizer<>`? I already asked a similar question here: https://github.com/aspnet/AspNetCore/issues/12277.

**Comment by aaronhudon-ts** [comment]
I'd like to expand on @SeppPenner post, as I found the following to work based on the browser's preferred language.

**Startup.cs**
 ```
public void ConfigureServices(IServiceCollection services)
{
	services.AddRazorPages();
	services.AddServerSideBlazor();

	// localization
	services.AddLocalization(options => options.ResourcesPath = "Resources");
	var supportedCultures = new List<CultureInfo>{
		new CultureInfo("en-US"),
		new CultureInfo("fr")
	};
	services.Configure<RequestLocalizationOptions>(options =>
	{
		options.DefaultRequestCulture = new Microsoft.AspNetCore.Localization.RequestCulture("en");
		options.SupportedUICultures = supportedCultures;
		options.SupportedUICultures = supportedCultures;
	});
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}
	else
	{
		app.UseExceptionHandler("/Error");
		// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
		app.UseHsts();
	}

	// use the browser's preferred language for localization
	app.UseRequestLocalization();
	app.UseHttpsRedirection();
	app.UseStaticFiles();

	app.UseRouting();

	app.UseEndpoints(endpoints =>
	{
		endpoints.MapBlazorHub();
		endpoints.MapFallbackToPage("/_Host");
	});
}
```
**Pages/Index.razor**
```
@page "/"
@inject IStringLocalizer<Index> L

<h1>@L["App Home"]</h1>
```

**Resource files**

/Resources
......./Pages
.............Index.fr.resx
.............Index.resx

**Comment by GiroSA** [comment]
Localization is critical for us. I really hope MS comes up with official guidance on this soon. I also hope that the mechanism will be server/client side agnostic as well as not impact unit testing.

**Comment by SeppPenner** [comment]
@GiroSA I don't know where the problem is here exactly, but it works perfectly for server side in my projects...

**Comment by aaronhudon-ts** [comment]
@GiroSA did you try my example?

**Comment by endeffects** [comment]
I cannot get the StringLocalizer to work on a Blazor Client Side Application. The Resource Files are published to the Output Folder but the Loalizer allways reports no Manifest found for the current Culture, which do exist.

**Comment by SeppPenner** [comment]
@endeffects As far as I know, there is a seperate issue for that.

**Comment by Stamo-Gochev** [comment]
@aaronhudon-ts  Can you share a repo that demonstrates your approach in https://github.com/aspnet/AspNetCore/issues/12088#issuecomment-528499976? I am still not able to make it work.

**Comment by aaronhudon-ts** [comment]
@Stamo-Gochev Are your resource files in the same project, under the folder "Resources"?  This also assumes Server-Side Blazor.

**Comment by Stamo-Gochev** [comment]
@aaronhudon-ts They are, the problem seems to be that localization of blazor components is not currently supported https://github.com/aspnet/AspNetCore/issues/16687#issuecomment-548461295

**Comment by aaronhudon-ts** [comment]
@Stamo-Gochev I am only using `IStringLocalizer` as shown in my example above - and everything works fine.

**Comment by gwubunye** [comment]
I am finally back on this after a huge detour. I have implemented and am using a custom IStringLocalizer and it works as expected server side. I am not going to worry about client side for now. I am hoping that MS would have kept the infrastructure the same for both client and server side by the time they shipped the client side in May next year.

**Comment by GiroSA** [comment]
I am finally back on this after a huge detour. I have implemented and am using a custom IStringLocalizer and it works as expected server side. I am not going to worry about client side for now. I am hoping that MS would have kept the infrastructure the same for both client and server side by the time they shipped the client side in May next year.
