### ISSUE TITLE
webpack dev middlware

### ISSUE THREAD

**Issue by AminMatio** [aspnet/AspNetCore#12093]
I'm trying to use UseWebpackDevMiddleware in my project but having issue when using this middleware with Visual Studio which I reported the issue a few months ago and they evaluated the issue as "other products(Asp.Net) issue" [see this link to get more info about the report](https://developercommunity.visualstudio.com/content/problem/489866/nodeservice-not-working-correctly.html)

the problem  : Asp.Net NodeService does not compile the client side script files each time i save a file in Visual Studio an I have to stop and re run the project every time but in vs code everything works just great.

Please take a look at my [question in SO](https://stackoverflow.com/questions/54605028/asp-net-core-webpack-dev-middleware-issue-in-visual-studio) which i also asked a few months ago

**Comment by mkArtakMSFT** [comment]
We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
