### ISSUE TITLE
Blazor: Need to restrict the intellisense  for two way binding event callback 

### ISSUE THREAD

**Issue by gurunathancs1991** [aspnet/AspNetCore#12118]
As discussed in this [blazor two way binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#data-binding), we have used a property in two way with its event call back. 

We don't want to list out this event call back in intellisense in that component parameters.

Code:
`
    @code {
   
    [Parameter]
    private int Year { get; set; }

    [Parameter]
    private EventCallback<int> YearChanged { get; set; }
   }
`

The `YearChanged` Event dont need to be list out in intellisense in razor page.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gurunathancs1991.
This is not something we plan to change.
