### ISSUE TITLE
Blazor (server-side) navigating from javascript

### ISSUE THREAD

**Issue by audacity76** [aspnet/AspNetCore#12124]
### Feature request
I need to navigate to another component if something happens on my client side in javascript (click on a path in an embedded svg). If I navigate via `windows.location.href` I make a complete new request. 

### Describe the solution you'd like
I would like to have a javascript method to navigate to another component using blazor.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @audacity76.
This is already possible: you can use `Blazor.navigateTo`.
