### ISSUE TITLE
Error after a refresh

### ISSUE THREAD

**Issue by marcelovidigal** [aspnet/AspNetCore#12126]
After a refresh (F5) the application stops in loading message, and no UI rendered. After search in log I found two issues, whats are this? Some one knows how to resolve this two things?

HTTP/2 connection error.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Pseudo-header field found in request headers after regular header fields.

HPACK decoding error while decoding headers for stream ID 187.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecodingException: Index 69 is outside the bounds of the header field table. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.

The application works well, if no refresh (F5/CTRL+F5) is executed, no problem, if it is stopped after a refresh, a second refresh return to application.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @marcelovidigal.
This issue has been fixed as part of #11560.
