### ISSUE TITLE
Blazor (server-side) routing parameter with dot (.) not working

### ISSUE THREAD

**Issue by audacity76** [aspnet/AspNetCore#12122]
### Describe the bug
If you start a blazor server side razor component which includes a string parameter with a dot you get a 404. The parameter works/shows correctly if you navigate to that component from another component.

### To Reproduce
1. Using this version of ASP.NET Core 3.0.0-preview6.19307.2
2. Run this razor file
```
@page "/"
@page "/{Name}"

<h1>Hello, @(Name ?? "world")!</h1>

@code{ 
    [Parameter]
    public string Name { get; set; }
}
```
3. With these arguments: `/asp.net`
4. See error: `404`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @audacity76.
Has anyone else seen this, folks?

**Comment by mkArtakMSFT** [comment]
Looks like what's happening here is the fallback routing is treating this route as non-client route and hence the 404. The default route pattern we use will not match anything that looks like a filename. You can try to override the route pattern used by fallback-routing in the `MapFallbackToPage`.

We'll keep the issue to track the work of documenting this.
