### ISSUE TITLE
StreamId Map should be cleared when connection is stopped

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#12135]
Currently we don't clear the internal dictionary for mapping stream ids to active streams when the client disconnects. It's a silent issue because we will override any stale values with new streams, but regardless, we should be clearing out the map on connection close.

**Comment by BrennanConroy** [comment]
And removing on stream closes?

**Comment by mikaelm12** [comment]
We could. We'd have to have another map though correlating invocation ids to their stream ids. So we'd have to push the invocation id into the `checkUploadStream`logic where we allocate the stream Ids so we could group them together.  I don't feel to strongly about this tbh.

**Comment by BrennanConroy** [comment]
Sure, but it's technically a memory leak on the client.

**Comment by mikaelm12** [comment]
*sighs in agreement

**Comment by anurse** [comment]
Consider for preview 8, relatively low priority.
