### ISSUE TITLE
[Blazor] reCapcha in client blazor app how to?

### ISSUE THREAD

**Issue by dinonovak** [aspnet/AspNetCore#12149]
Any examples on how to implement reCapcha on user registration form in Client Side Blazor app?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by RemiBou** [comment]
here is how I did it https://remibou.github.io/Validate-request-with-reCaptcha-on-a-Blazor-app-and-MediatR/
