### ISSUE TITLE
Worker service event logging in preview 6 not working

### ISSUE THREAD

**Issue by kmadar75** [aspnet/AspNetCore#12159]
In preview 5 it was working like a charm but in 6 it just does not with the exact same code.
Maybe I missed something what I have to do additionally in pr6.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kmadar75.
@shirhatti which `area` should this be assigned to? Can you please apply the appropriate label? Thanks!

**Comment by shirhatti** [comment]
Not sure I follow what is meant by event logging.
@kmadar75 Are you referring to the `Microsoft.Extensions.Logging.EventSource` logger?

Can you please provide a snippet or repro to indicate what doesn't work as you expected?

**Comment by kmadar75** [comment]
I used the builtin worker service template and created the windows service with the service management app without any modification. As I experienced it logged the events to windows eventlog. I hope my explanation was clear.

**Comment by davidfowl** [comment]
Dupe of https://github.com/aspnet/Extensions/issues/1839. See this issue for the workaround.
