### ISSUE TITLE
[Blazor] Simplify passing enum values as attributes

### ISSUE THREAD

**Issue by montyclt** [aspnet/AspNetCore#12154]
### Is your feature request related to a problem? Please describe.
When passing enum values to Blazor components, that required specify the type and the value like this:

```
<KtButton State="State.Secondary" Border="Border.Square">Click me!</KtButton>
```
This is verbose.

### Describe the solution you'd like
In a razor view tag helper, is possible to pass the enum value using only its value, I propose use the same syntax in a Blazor component like this:
```
<KtButton State="Secondary" Border="Square">Click me!</KtButton>
```

### Additional context
It's important mark error when value is not in the enum and provide IntelliSense support.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @montyclt .
This is not something we plan to add support for.
