### ISSUE TITLE
What is the CheckAccess pattern in Blazor ?

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#12167]
Could you please describe this concept !

Thanks...

**Comment by rynowak** [comment]
Similar to other UI frameworks, Blazor requires you to be in the correct threading context to access UI and mutable state related to the UI.

If you have some work that triggers on a background thread, you'd normally use `InvokeAsync()` on `ComponentBase` to dispatch it to the correct context. 

If you need to start some work as a result of a Blazor lifecycle method, you are already in the correct context. If you need to start some work as a result of an event handler, you are already in the correct context.

If you're in client-side Blazor, there's one thread so you don't really have to think about this.

*The CheckAccess() pattern* - refers to writing code like the following:

```C#
if (Dispatcher.CheckAccess())
{
    // You already have access, do what you want
}
else
{
    // You don't have access, enqueue your work
    Dispatcher.InvokeAsync(() =>
    {
         // Write your code here
    });
}
```

This is an advanced optimization for the cases where you are starting work, and you *might not* be in the correct context. This probably isn't necessary for most developers on Blazor to ever think about.

**Comment by enetstudio** [comment]
Thanks so much for this, @rynowak!
