### ISSUE TITLE
Update Identity migrations to 3.0

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/AspNetCore#12168]
Currently the project templates still contain migrations generated for 2.2. They should be updated to migrations generated for 3.0.

/cc @HaoK @blowdart

**Comment by ajcvickers** [comment]
@HaoK @blowdart Putting this in preview 8.

**Comment by HaoK** [comment]
For posterity since it took me forever to find the batch file I used to generate this last time: https://github.com/aspnet/Templating/blob/master/migrations/updateMigrations.cmd
