### ISSUE TITLE
SignalRSamples route /deployment throw because of attempted SynchronousIO

### ISSUE THREAD

**Issue by tebeco** [aspnet/AspNetCore#12164]
### Describe the bug
The sample uses :
```
  using (var textWriter = new StreamWriter(context.Response.Body))
  using (var writer = new JsonTextWriter(textWriter))
```

when the `using` statement ends, it will call `Dipose()` then `Flush()` ... ending up attemping to do `Synchronous IO`, that will blow up because it's disabled by default now

### To Reproduce
1. checkout `release/3.0-preview7`
2. Run the `SignalRSamples` project
3. Hit the `/deployment` route

### Expected behavior
Not throwing ;)

### Fix
using `System.Json.Text.Utf8Writer` is an `IAsyncDisposable` so it would fit the `await using` statement from the sample

**Comment by anurse** [comment]
Good catch! We could possibly even just remove this endpoint. It was part of a plan to do functional testing (and we needed the test app to "report" the commit/version/etc. it was running on) and we found a different way to do it. Fixing it is fine too though :).

**Comment by tebeco** [comment]
@anurse the linked PR seems only fix it for Signalr samples
if the same route is used in other part i could try to fix others

i guessed it was for infra/internal check but did not dig deeper TBH

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/aspnet/AspNetCore/pull/12165

**Comment by anurse** [comment]
> if the same route is used in other part i could try to fix others

It should only be used in the SignalR samples. Thanks for the fix-up!
