### ISSUE TITLE
Nested ViewModel with IFormFile are being created automatically when it is sent by post

### ISSUE THREAD

**Issue by ramonscampos** [aspnet/AspNetCore#12175]
I have a create form to a specific viewmodel that contains another viewmodel that has an IFormFile property:

```
public class ViewModel1
{
     public ViewModel2 ViewModel2 { get; set; }
}
```

```
public class ViewModel2
{
     public IFormFile FormFile { get; set; }
}
```

When I submit the form, the ViewModel1 is instantiated automatically.
If I remove the FormFile property, this stops happening.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ramonscampos.
Are you experiencing this on .Net Core 2.2? If so, this is a known issue and you can find more details about it here: https://github.com/aspnet/AspNetCore/issues/4802

**Comment by SalehGladius** [comment]
Today I updated from Core 2.0 to Core 2.2.6, but my website got in trouble when uploading an image.

System.OutOfMemoryException

I used `IFromFile` in upload viewmodel.

**Comment by mkArtakMSFT** [comment]
@SalehGladius that seems suspicious and unrelated to this issue. If you're still facing it, please file a new issue and share a small repro project for us to investigate it.

**Comment by ramonscampos** [comment]
Hi @mkArtakMSFT, yeah.. I'm facing this with .Net Core 2.2.
I had seen this issue before.. So in the 2.2 version will happen this error forever?! o.O

Once it was fixed in 3.0 only, if I want to run this correctly I'll be forced to upgrade?

**Comment by mkArtakMSFT** [comment]
@ramonscampos, for 2.2 you'll have to use one of the workarounds provided here: https://github.com/aspnet/AspNetCore/issues/4802

**Comment by pranavkm** [comment]
Verified this is no longer true as of 3.0. The nested model is `null` unless the form file is posted.
