### ISSUE TITLE
Blazor threading support

### ISSUE THREAD

**Issue by KieranDevvs** [aspnet/AspNetCore#12172]
Whats the status on threading support in Blazor? 
As far as I'm aware, the WASM specification supports threading in the recent updates (as of chrome 70 etc), is there plans for Blazor/Mono to support this in the future as I personally believe threading is a core component of the .NET runtime?

**Comment by SteveSandersonMS** [comment]
Yes. Client-side Blazor runs on Mono, and the Mono team is working towards enabling threading on WebAssembly. For more information please see https://github.com/mono/mono
