### ISSUE TITLE
.net create a windows service

### ISSUE THREAD

**Issue by lichen19951127** [aspnet/AspNetCore#12178]
I am using Visual Studio 2019 to create a windows service based on the .net framework. Add the installer. No display controls.

![image](https://user-images.githubusercontent.com/43132899/61204791-c2c51a00-a720-11e9-8daa-48870cf8d198.png)

![image](https://user-images.githubusercontent.com/43132899/61204803-cbb5eb80-a720-11e9-8332-6b58055e09d9.png)

![image](https://user-images.githubusercontent.com/43132899/61204818-d3759000-a720-11e9-9885-4f8f38531919.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lichen19951127.
This seems to be a request related to the VS tooling.
Please file an issue using VS Feedback tool in Visual Studio.
