### ISSUE TITLE
[Blazor Server-side] architecture question - handle existing code with static call

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#12188]
Hello guys,

I actually rewrite a silverlight app in blazor, and i met some problem with reusing ViewModels from the silverlight app in my app.

The existing ViewModels use a lot of a static acess as a repository, session-like system. In client-side version of blazor, it will not be a problem normally, but on the server side it's obviously a big problem, all clients whill shared same repository wich is not OK.

For the moment i develop only in server side, i need debugging to develop correctly. For the target, we actually don't know if we will use the client or server version, but we want keep possibility to use both.

Refactoring the existing ViewModels is a complicated task because the existing app depend of them and it will be a huge and complicated refactoring, including potential regression on the actual app. I can rewrite the entry point of the static class if needed but i can't really replace the calls to the static everywhere.

So the question, there is any way to manage a static class to "retrieve" for example an session-scoped service

1 - someting like that
````
//this is the existing repository class, i can rewrite it, but calls like Locator.UiParameter need stay valid
public static class Locator{
public static UiParameterViewModel UiParameter
{
get
{
       UiParameterService myScopedService = ?????;
       return myScopedService.UiParameter;
}
}
}
````
2 - If i cant, it is possible with a singleton system ? (and i replace all calls to Locator by Locator.Instance for example ?

Thanks for your help !

Julien Gourdon

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
