### ISSUE TITLE
JsonSerializerOptions.DictionaryKeyPolicy ignores JsonNamingPolicy.CamelCase

### ISSUE THREAD

**Issue by dodyg** [aspnet/AspNetCore#12180]
### Describe the bug
`JsonSerializer.ToString()` ignores does not convert PascalCase dictionary keys into camelCase although `JsonSerializerOptions.DictionaryKeyPolicy` is set to ` JsonNamingPolicy.CamelCase`

### To Reproduce
ASP.NET Core 3 Preview 6

### Expected behavior
Dictionary Keys converted to camelCase on serialization

![json-serializer-bug](https://user-images.githubusercontent.com/1761249/61206391-b75afa00-a6f2-11e9-8474-0d85cdabbe0c.png)

**Comment by campersau** [comment]
Looks like you are hitting this bug: https://github.com/dotnet/corefx/issues/38840

**Comment by pranavkm** [comment]
As @campersau pointed out, this is dup of the CoreFx bug.
