### ISSUE TITLE
If only blazor could be lighter

### ISSUE THREAD

**Issue by maarofkamel** [aspnet/AspNetCore#12189]
If only blazor could be smaller then 2.1 mo , i like blazor and i want to use it for production but i cant let my clients download and wait for that big size app to load.

I know its hard to shrink it but please and please make that on top of priorities.

Another thing is hot reloading, it would be a dream also.

You guys are working on new features and thats awesome. But adding new features for clients that wont adopt it is a big problem.

I hate to admit this but google is always one step ahead of Microsoft because they focus on clients before the product for them gaining a lot of users for a simple product is better then few clients for a complex project

I want to see and i wish to see blazor becoming the most famous and the n1 spa framework and the n1 on demande frontend framework.

Its a long way . But work smarter not harder ! 

Thank you guys for delivering this amazing product and thank you for all the good work . We love you guys and keep up

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback. We know about these pain points and are actively working on resolving those. Thanks for using Blazor!
