### ISSUE TITLE
Unable to use FileStreamResult class in blazor project targetted to .netstandard 2.0

### ISSUE THREAD

**Issue by Shameer-Ali** [aspnet/AspNetCore#12186]
Bug Description: 

I am working on blazor project, to create an application which is majorly focused on file operations. To write the file response, i use fileStreamResult class in my project. To use this class, i have tried to install the NuGet package Microsoft.AspNetCore.Mvc.NewtonsoftJson version=3.0.0-preview6.19307.2 in my project. On searching in web, i found this class available within this package, only.

But, this package is not getting installed. Anyhow, this package is installing successfully with blazor project targetted .netstandard 3.0.

Could anyone, help me to find the solution to use the fileStreamResult class within project targetted to .netstandard 2.0 ? or let me know any other possible solution available ( any other way to use the fileStreamResult class through other NuGet package in blazor project).

Hope, i described my issue, precisely.!

Waiting, for the solution from experts ..!

Thanks in Advance.

**Comment by davidfowl** [comment]
Why are you using FileStreamRest in a Blazor application? Can you post the code?

**Comment by Shameer-Ali** [comment]
> Why are you using FileStreamRest in a Blazor application? Can you post the code?

I am building a application which simply do file operations like read, create, delete, download, update. For this, i am using blazor's shared application which comprise of both client-side and server-side project. I build a client-side UI which access files and folders from server-side using ajax calls(i.e, i call server side method to perform file operation like downloading a specific folder). For achieving this case, i need to return a filestream from physical path to the client-side. 

This is the reason why i use FileStreamResult class in my project. 



public FileStreamResult GettingImageResult(string path, string id, bool allowCompress, ImageSize size, params FileManagerContent[] data)
        {
            try
            {
                AccessPermission PathPermission = GetFilePermission(path);
                if (PathPermission != null && !PathPermission.Read)
                    return null;
                String fullPath = (contentRootPath + path);
                FileStream fileStreamInput = new FileStream(fullPath, FileMode.Open, FileAccess.Read);
                FileStreamResult fileStreamResult = new FileStreamResult(fileStreamInput, "APPLICATION/octet-stream");
                return fileStreamResult;
            }
            catch (Exception)
            {
                return null;
            }
        }

**Comment by Shameer-Ali** [comment]
Hi @davidfowl ,

I am waiting for your update. mistakenly closed the thread last time.

**Comment by danroth27** [comment]
Hi @Shameer-Ali. The `FileStreamResult` type is specifically for returning a file stream from an MVC action. It is not intended for client-side use in Blazor apps. Starting with .NET Core 3.0, you can only use `FileStreamResult` from an ASP.NET Core project targeting netcoreapp3.0. In your server project you can use `FileStreamResult` to return a file to the Blazor client app in response to an HTTP request, but you can't use `FileStreamResult` directly from the Blazor client app.
