### ISSUE TITLE
ASP.NET core 2.2 cookie authentication: is it completely safe to have large cookies and rely on asp.net core cookie chunks ?

### ISSUE THREAD

**Issue by EnricoMassoneDeltatre** [aspnet/AspNetCore#12192]
Hi, 

we are converting an old ASP.NET 5 web application to ASP.NET core 2.2. Our application uses cookie authentication (we have implemented cookie authentication without using ASP.NET core identity, by following [this guide](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.2)). 

In our implementation **we decided to store the user permissions as claims inside the `ClaimsIdentity` that we use to build the request principal**, which is an instance of the `ClaimsPrincipal` class. What I have called *user permissions* is basically a set of strings (provided by an identity management system we must integrate with) representing the action that the user is allowed to do in our application. Unfortunately these permissions are very granular, so **we ended up having a lot of permissions for each user** (I know that this is not the best way to model such a scenario, we should probably avoid granular permissions from the beginning, but we can't modify this part of the system). 

As a consequence of what I explained above, the authentication cookie generated by asp.net core is huge and asp.net core decides to divide it in chunks, as you can see from the following picture: 

![image](https://user-images.githubusercontent.com/29275408/61226392-a1652d80-a722-11e9-8da2-658a72427e30.png)

So far so good: based on my understanding the cookie is obtained by serializing the request principal, which contains a lot of claims due to the huge number of permissions. [This github issue](https://github.com/aspnet/Security/issues/1536) confirms that splitting the cookie in chunks is done by ASP.NET core in order to avoid having cookies with a dimension greater than 4KB. 

By looking at the Google chrome console while browsing my application I noticed the following warnings: 

![image](https://user-images.githubusercontent.com/29275408/61226761-539cf500-a723-11e9-87d6-870b93dd2acf.png)

Some of these warnings are raised by angular-js `$http` service and some others are raised by HTTP calls made with `XMLHttpRequest` objects from inside polymer 1 web components. Put another way, it seems that some of our client side javascript code doesn't work well with the ASP.NET core authentication cookie chunks.

We are not concerned with the interaction between client side javascript and cookies, because **we don't need to access cookies from javascript code**, but we would like to know if relying on the chunk strategy adopted by ASP.NET core for large cookies is completely safe.

Are we going to have issues with the large cookies if, for instance, we put proxies (such as load balancers or traffic managers) in front of our application  ?

Is there any known issue for applications deployed inside kubernetes when cookies are splitted up in chunks (due to the kubernetes ingress for instance) ?
 
Put another way, we would like to know if you suggest to change our implementation in order to get smaller cookies and avoid the chunks at all.  

Thanks for helping

**Comment by blowdart** [comment]
Even with chunks there's a limit on how many cookies can be set per site, and that limit is browser specific.

While I've not seen load balancers or traffic managers object to this, it is a pretty common approach, [others have](https://hajekj.net/2017/03/20/cookie-size-and-cookie-authentication-in-asp-net-core/). You could try the approach of a [reference cookie](https://github.com/aspnet/Security/blob/22d2fe99c6fd9806b36025399a217a3a8b4e50f4/samples/CookieSessionSample/MemoryCacheTicketStore.cs), where the auth information is stored in an in-memory cache, and retrieved from that on every request.

**Comment by githubfanster** [comment]
would using enums / integers instead of permission strings work for you?

jon smith, author of Entity Framework Core in Action, has a series of articles on this. here's one of them:
(the link below points to the section where he discusses why he used enum for permissions since he was using cookies)

https://www.thereformedprogrammer.net/a-better-way-to-handle-authorization-in-asp-net-core/#why-i-used-enums-for-the-permissions

**Comment by brockallen** [comment]
This is what claims transformation is for.

**Comment by EnricoMassoneDeltatre** [comment]
> Even with chunks there's a limit on how many cookies can be set per site, and that limit is browser specific.
> 
> While I've not seen load balancers or traffic managers object to this, it is a pretty common approach, [others have](https://hajekj.net/2017/03/20/cookie-size-and-cookie-authentication-in-asp-net-core/). You could try the approach of a [reference cookie](https://github.com/aspnet/Security/blob/22d2fe99c6fd9806b36025399a217a3a8b4e50f4/samples/CookieSessionSample/MemoryCacheTicketStore.cs), where the auth information is stored in an in-memory cache, and retrieved from that on every request.

Hi, 

thanks for helping, this seems to be the right way to go. I'll give it a try to see if everything is clear to me and works as expected. 

While I was thinking about this cookie issue a more general problem, which is somewhat related to your suggestion, popped out to me. Sometimes we have the need to share **request specific data** between the various framework components (I mean classes like middlewares, authorization handlers and so on), so I asked myself whether ASP.NET offers any built in infrastructure to do so in a safe way. In order to avoid confusion, I'm not looking for some sort of session state to be maintained between **different requests of the same user**, I just want to put some data in a bag accessible to all the framework classes involved in the request handling and discard these data when the request handling finishes.  

There are two patterns that seems obvious to me:
 
 - use a custom service registered with a scoped lifetime on the DI container. This service should offer a public interface designed to save and retrieve request specific data of some sort. The scoped lifetime guarantees that the service lifetime is bound to the http request. 
 - the `HttpContext` offers the property `HttpContext.Items` which is documented as a safe place where storing reqeust specific data

Are there any other ways to do so ? Is it safe to use the class AsyncLocal<T> to do so (I used it in the past, but in the context of console applications. I can't find any official documentation about its behavior inside ASP.NET core) ?

Thanks for helping.

**Comment by EnricoMassoneDeltatre** [comment]
> This is what claims transformation is for.

Thanks for the suggestion. I'll investigate this tool too. I would like to understand whether or not this relates to the other solution suggested (the reference cookie approach) and what are the differences between the two.

**Comment by EnricoMassoneDeltatre** [comment]
> This is what claims transformation is for.

Hi @brockallen, 

thanks for the suggestion. We tried out the claims transformation solution and it seems to work well. Moreover, based on our understanding, it should work equally well in the case of a scaled out service (while the ticket store solution suggested by @blowdart requires to implement a centralized persistent ticket store in the case of a scaled out application). 

I don't fully understand how the claims transformation works, actually it seems like magic to me. This is our sample implementation: 

```
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace WebApplication2
{
  public class Startup
  {
    public void ConfigureServices(IServiceCollection services)
    {
      services.AddTransient<IClaimsTransformation, ClaimsTransformer>();

      services
        .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
        .AddCookie();
    }

    public void Configure(IApplicationBuilder app)
    {
      app.UseAuthentication();

      app.Run(async context =>
      {
        if (!context.User.Identities.Any(identity => identity.IsAuthenticated))
        {

          var claims = new List<Claim>(1)
          {
            new Claim("Foo", "Bar")
          };

          await context.SignInAsync(
              CookieAuthenticationDefaults.AuthenticationScheme,
              new ClaimsPrincipal(new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme)));

          context.Response.ContentType = "text/plain";
          await context.Response.WriteAsync("Hello First timer");
          return;
        }

        context.Response.ContentType = "text/plain";
        await context.Response.WriteAsync("Hello old timer");
      });
    }
  }

  public class ClaimsTransformer : IClaimsTransformation
  {
    public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
    {
      var identity = new ClaimsIdentity(
        principal.Claims,
        CookieAuthenticationDefaults.AuthenticationScheme);

      // Make a large identity
      var claims = new List<Claim>(1001);
      claims.Add(new Claim(ClaimTypes.Name, "bob"));
      for (int i = 0; i < 1000; i++)
      {
        claims.Add(new Claim(ClaimTypes.Role, "SomeRandomGroup" + i, ClaimValueTypes.String, "IssuedByBob", "OriginalIssuerJoe"));
      }

      identity.AddClaims(claims);

      return Task.FromResult(new ClaimsPrincipal(identity));
    }
  }
}
```

I noticed that, before the response is returned to the client, the request principal is somewhat cleaned of all the claims added by the method `ClaimsTransformer.TransformAsync`. This way the cookie sent along with the response is small and, when the user performs another request, the deserialized identity contains only the claim having type `Foo` and value `Bar` (of course this is true only before `ClaimsTransformer.TransformAsync` is called again for the second request). 

Our question is: who is doing the claims cleanup operation on the request principal before the response is returned to the client ? Is the authentication middleware the piece of code doing this cleanup operation (when the server response is processed by the middlewares placed before the one generating the response) ?   

Thanks for helping
