### ISSUE TITLE
SignalR Client sometimes crashing UWP app

### ISSUE THREAD

**Issue by stefangavrilasengage** [aspnet/AspNetCore#12193]
### Describe the bug
Using Microsoft.AspNetCore.SignalR.Client, version 1.1.0 within a UWP app (targetting Windows 1803) unexpectedly and intermittently our app crashes due to one of the following 3 exceptions that we cannot catch (but are sent to HockeyApp, from where they are pasted below).

#### 1. System.Net.WebSockets.WinRTWebSocket.ReceiveAsync
``System.Net.WebSockets.WinRTWebSocket.ReceiveAsync
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The remote party closed the WebSocket connection without completing the close handshake.)``

Exception Stack:
- unknown location
- System.Net.WebSockets.WinRTWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
- Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
- System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
- System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
- System.IO.Pipelines.Pipe.GetReadAsyncResult()
- Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)
- Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()
- System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)

#### 2. Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving 
``Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Websocket closed with error: 1006.)``

Exception Stack:
- unknown location
- Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)

#### 3. System.Net.WebSockets.WinRTWebSocket.ReceiveAsync 
``System.Net.WebSockets.WinRTWebSocket.ReceiveAsync
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.)``

Exception Stack:
- unknown location
- System.Net.WebSockets.WinRTWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
- Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
- System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
- System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
- System.IO.Pipelines.Pipe.GetReadAsyncResult()
- Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)
- Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()
- System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)

### To Reproduce
Unfortunately this issue cannot be reproduced on demand.

### Expected behavior
UWP app should not crash. At most, SignalR client should disconnect and throw a Closed event but not rethrow where it cannot be caught.

### Screenshots
This is how we initialize the hub connection : 
![image](https://user-images.githubusercontent.com/39733750/61227406-226cf680-a71c-11e9-9881-722109771431.png)
An exempt from RegisterUserHandlers (the others look pretty much the same):
![image](https://user-images.githubusercontent.com/39733750/61227483-4cbeb400-a71c-11e9-87bb-bf9042235839.png)

### Additional context
Initially we believed it was from the size of the message (as we are using the MessagePack protocol) however this did happen with very small message sizes as well and we never managed to reproduce it in debug mode.

If there's any other information you need I will most happily provide it as I would like to get to the bottom of it and at least find out why it's happening.

Output of `dotnet --info` : 
 .NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.106\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.603 [C:\Program Files\dotnet\sdk]
  2.2.106 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by anurse** [comment]
Yeah, we shouldn't be crashing here. At a minimum we should "observe" these exceptions and report them in a way that doesn't crash the app. The main gap here in our understanding is that standard .NET Core/.NET Framework apps don't crash in this situation (unobserved background exceptions) but it seems UWP ones do. Thanks @stefangavrilasengage for the report, we'll look at improving this handling.

**Comment by BrennanConroy** [comment]
There are a couple tasks we aren't explicitly observing in WebSockets that we can fix up and we can look for others while doing this:
https://github.com/aspnet/AspNetCore/blob/76408c97295739512721eedb3696bc31bbe1a731/src/SignalR/clients/csharp/Http.Connections.Client/src/Internal/WebSocketsTransport.cs#L151-L152
