### ISSUE TITLE
Blazor on Azure and Google OAuth2 not working 

### ISSUE THREAD

**Issue by agonzalezm** [aspnet/AspNetCore#12195]
I am trying to create a Blazor app that uses Googles API to connect to Google and retrieves information about their people API, but it happens for all the APIs.

I am using this code bellow when i run in local it works and i get a new browser tab with google request for permission that i can accept and it works.

But when I upload to azure it doesnt work and the applications hangs and i dont get the new google tab request for permissions, any idea what is wrong?

```

@using Google.Apis.People.v1;
@using Google.Apis.Auth.OAuth2;
@using System.Threading;
@page "/"

<h1>Hello, world!</h1>


<button class="btn btn-primary" onclick="@Connect">Connect</button>

@functions {

    void Connect()
    {
         ClientSecrets cs = new ClientSecrets
            {
                ClientId = "xxxxxxxxx-xxxx.apps.googleusercontent.com",
                ClientSecret = "xxxxx"
            };  
        var userCredential = GoogleWebAuthorizationBroker.AuthorizeAsync(cs, new[] { PeopleService.Scope.ContactsReadonly, PeopleService.Scope.UserEmailsRead }, "TEST", CancellationToken.None).Result;
    }
}

```

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by agonzalezm** [comment]
Ok, I posted question also in StackOverflow (https://stackoverflow.com/questions/57045662/server-side-blazor-on-azure-and-google-oauth-2-0-not-working) but as this only happens with Blazor and Azure (not local) i though was more a blazor problem. Thanks

**Comment by DAllanCarr** [comment]
https://github.com/googleapis/google-api-dotnet-client/issues/888#issuecomment-289040034

**Comment by agonzalezm** [comment]
@DAllanCarr I checked that link but the what is recommended there to use GoogleAuthorizationCodeFlow (instead GoogleWebAuthorizationBroker ) it  is for  MVC and it doesnt work on normal server-side blazor project, so i am bit lost how to make it work on server-side blazor as everything i tried didnt work.

If anyone is successful or have sample and can comment here it will be helpful for me and maybe other persons in future.

**Comment by DAllanCarr** [comment]
@agonzalezm  Server blazor should allow integration using openid connect similar to how a normal api server app negotiates that auth flow. The client is just session cookie.

https://developers.google.com/identity/protocols/OpenIDConnect

I'm not sure what external providers are supported with Blazor. Maybe ask for feedback. I am assuming everything asp.net core supports out the box.
