### ISSUE TITLE
How to increase the file uploading size in Blazor server side hosted application?

### ISSUE THREAD

**Issue by BerlyChristopher** [aspnet/AspNetCore#12203]
In ASP.NET Core, we can increase the uploading file size limit by defining the size in maxAllowedContentLength. But how to achieve this in ASP.NET Blazor server-side hosted application?

Can anyone suggest a possible solution?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @BerlyChristopher.
As of now we haven't defined a story around file-uploads in Blazor Server side apps. We'll do that as part of #12205 

For now you can do two things:
1. Use native JavaScript capabilities to upload files to a web service endpoint directly (using fetch, XmlHttpRequest, etc....)
2. Do what has been discussed #11643 - increase the buffer size in `Startup.cs`
