### ISSUE TITLE
Add search to ASP.NET Core Razor Pages does not work

### ISSUE THREAD

**Issue by duncanspeidel** [aspnet/AspNetCore#12201]
Hi,

I'm working with the code shown on https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.2 (Git = https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovieSearch/Pages/Movies/Index.cshtml.cs) when I test the app I expect https://localhost:5001/Movies?searchString=Ghost or https://localhost:5001/Movies/Ghost to return just the two ghostbuster movies in the DB.  It does not, it returns all movies.  

Here's the code:
```
            if (!string.IsNullOrEmpty(SearchString))
            {
                movies = movies.Where(s => s.Title.Contains(SearchString));
            }
            if (!String.IsNullOrEmpty(MovieGenre))
            {
                movies = movies.Where(x => x.Genre == MovieGenre);
                
            }
            Genres = new SelectList(await genreQuery.Distinct().ToListAsync());
            Movie = await _context.Movie.ToListAsync();  //Here's the line that breaks it
```
When I debug I get the results I expect from:
```
`            if (!string.IsNullOrEmpty(SearchString))
            {
                movies = movies.Where(s => s.Title.Contains(SearchString));
            }`
```
Later when it calls Movie = await _context.Movie.ToListAsync(); the filtered list is lost.  Not sure what needs to change to make the await _context.Movie.ToListAsync() call work.

Thank you,
Duncan

**Comment by pranavkm** [comment]
You need to call `ToListAsync()` on the filtered results not on the entire DB table:

`Movie = await movie.ToListAsync();`
