### ISSUE TITLE
Ship Microsoft.DotNet.Web.ProjectTemplates.2.1 in servicing builds

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#12208]
We need to ensure this package is pushed to NuGet for the template search functionality. The change will be on the line: https://github.com/aspnet/AspNetCore/blob/6ed7bf85b198a22a3cdd5b61c4eca5657959dadc/build/artifacts.props#L147

**Comment by JunTaoLuo** [comment]
cc @mkArtakMSFT 

I see that in 2.2 we ship all of the template packages:
    <PackageArtifact Include="Microsoft.DotNet.Web.Client.ItemTemplates" Category="ship" />
    <PackageArtifact Include="Microsoft.DotNet.Web.ItemTemplates" Category="ship" />
    <PackageArtifact Include="Microsoft.DotNet.Web.ProjectTemplates.2.2" Category="ship" />
    <PackageArtifact Include="Microsoft.DotNet.Web.Spa.ProjectTemplates.2.2" Category="ship" />

Should we just do that in 2.1 as well and ship all 4 template packages?

**Comment by mkArtakMSFT** [comment]
For 2.2 we've updated the Spa.ProjectTemplates just recently.
We need to make these two in 2.1:
```xml
<PackageArtifact Include="Microsoft.DotNet.Web.ProjectTemplates.2.2" Category="ship" />
<PackageArtifact Include="Microsoft.DotNet.Web.Spa.ProjectTemplates.2.2" Category="ship" />
```

**Comment by JunTaoLuo** [comment]
I'll keep an eye out for merging 2.1=>2.2=>master PRs.
