### ISSUE TITLE
Should MapHubConnections return a strongly-typed builder?

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#12218]
See: https://github.com/aspnet/AspNetCore/blob/a9a9298d4f2ae06b373090a0a0dacb1f0911fe93/src/SignalR/common/Http.Connections/ref/Microsoft.AspNetCore.Http.Connections.netcoreapp3.0.cs#L6

Generally we want `IEndpointRouteBuilder` extensions to return a specific type (more specific than `IEndpointConventionBuilder`). This way it can be targeted by framework-specific extension methods.

/cc @anurse @BrennanConroy @JamesNK

**Comment by anurse** [comment]
Let's do this. I guess an empty interface that inherits from `IEndpointConventionBuilder`?

**Comment by JamesNK** [comment]
It's basically a sealed type: https://github.com/aspnet/AspNetCore/blob/cf3c2ba02b3c6b7a6ef1b268491a2b45c5f5772c/src/SignalR/server/SignalR/src/HubEndpointConventionBuilder.cs

It's not a breaking change because the API is new in 3.0?

**Comment by rynowak** [comment]
Yep. make it a concrete type

**Comment by anurse** [comment]
> It's not a breaking change because the API is new in 3.0?

Yes, but it breaks users updating from preview to preview.
