### ISSUE TITLE
Should IEndpointConventionBuilder-derived types live in M.A.Builder?

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#12219]
See: https://github.com/aspnet/AspNetCore/blob/a9a9298d4f2ae06b373090a0a0dacb1f0911fe93/src/SignalR/server/SignalR/src/HubEndpointConventionBuilder.cs#L7

In MVC we put these in the `Microsoft.AspNetCore.Builder` namespace. It probably doesn't super matter because you wouldn't usually refer to one of these by type, but we should try to follow a convention.

I came across this during API review for components, which isn't in the `M.A.Builder` namespace.

**Comment by anurse** [comment]
To be clear, it's the interface **and** the class that need to be moved, right? Do we even need the class to be public?

Anyway, let's do the needful.

**Comment by anurse** [comment]
Even though this was added in 3.0, we should do a quick announcement with the breaking change label.

**Comment by rynowak** [comment]
#Beans

**Comment by rynowak** [comment]
yes, these types are supposed to be public sealed types.

**Comment by JamesNK** [comment]
> we should try to follow a convention

@rynowak Do you think `Microsoft.AspNetCore.Builder` is a convention that third-party frameworks should follow? e.g. gRPC

**Comment by rynowak** [comment]
https://www.youtube.com/watch?v=GxBSyx85Kp8
