### ISSUE TITLE
Trying to load mscorlib.dll from some unexpected path

### ISSUE THREAD

**Issue by akshita31** [aspnet/AspNetCore#12210]
### To Reproduce
1. Using this version of ASP.NET Core: 3.0.100-preview6-012264
2. Clone the repository: https://github.com/dotnet/try/tree/541fa72354cfa8e8db91892e97c2118441157b04
3. cd MLS.Agent
4. dotnet run --port 4242 hosted
When I am trying to load a blazor project, I am seeing paths to the CI server in the console log and it says that "mscorlib.dll" could not be found
5. Navigate to the url - https://localhost:4242/LocalCodeRunner/blazor-nodatime.api

Strange errors in console. Looking for mscorelib.dll in some random path.

### Expected behavior
All the dlls should load

### Screenshots
![image](https://user-images.githubusercontent.com/12554141/61255089-08331880-a71c-11e9-9965-da99141f2240.png)

The error is here in blazor-webassembly.js
![image](https://user-images.githubusercontent.com/12554141/61255689-77117100-a71e-11e9-988d-7b4ab6c5e8c2.png)

### Additional context
Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview7-27902-19
  Commit:  fbe9466ddd

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012802 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19353.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27902-19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27902-19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by rynowak** [comment]
We discussed this in person this week. It looks like what's happening here is that trying to call into some Mono api that's unsupported on wasm might result in attempting to load `mscorlib`. 

I'm not sure that there's anything we can do about this, and if persists mono/mono is the right place to report it.
