### ISSUE TITLE
feat: Blazor - UriHelper NavigateToComponent / NavigateToPage

### ISSUE THREAD

**Issue by buehler** [aspnet/AspNetCore#12224]
### Is your feature request related to a problem? Please describe.
The default implementation of `IUriHelper` does implement the method of `NavigateTo` which is nice to manually add the urls. From MVC and the backend implementations with controllers, we new some tag helpers like `asp-controller` and `asp-action`.

Could it be possible to have something like `NavigateToComponent(IComponent component)` ?

### Describe the solution you'd like
An implementation of `NavigateToComponent(IComponent component)` in the `IUriHelper` that throws, when the `IComponent` does not have a `RouteAttribute` but if it does, it gets the url and navigates to that url.

On terms of routing params, I'd suggest the same mechanisms as in MVC, use an anonymous object that contains the needed named data.

Regards

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion! This is covered by issue #6352, which is something we have on the backlog to design in the future.
