### ISSUE TITLE
Collection model binding in mvc and upload file using ajax (dotnet core 3.preview-6)

### ISSUE THREAD

**Issue by bahmansh** [aspnet/AspNetCore#12223]
I have one form with some fields and one collection of another fields that contains some input files.

So I need to post form using ajax and bind data collection to class (Model) in server side.

My main issue is that files of sub collections will pass null.

My file is type of IFormFile and posted data is (form data of browser network):
![image](https://user-images.githubusercontent.com/19801131/61268667-5e05d000-a7b1-11e9-841d-d8b1abe07ade.png)

Earlier I was working with .net core 2.2, that it had big issue with sub collections files, so when I was using such sub collection it was throwing exception, I upgraded it to dot net core 3.preview-6 and now it's resolved.

How can I resolve this issue?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by bahmansh** [comment]
Here is my sample code.

https://github.com/bahmansh/ModelBinding

@mkArtakMSFT

**Comment by pranavkm** [comment]
@bahmansh I don't think the array notation you use to post files ever worked for file, so this doesn't seem like a regression. Regardless, specifying the form file as a property works:

```diff
- formData.append("Attachments[0][AttachFile]",$("form").find("#Attach1_File")[0].files[0]);
+ formData.append("Attachments[0].AttachFile",$("form").find("#Attach1_File")[0].files[0]);
```

I'd go further and let MVC generate the names for you. Something along the lines of:

```HTML
<div class="row form-group pt-3">
    <input id="Attach1_Title" asp-for="@Model.Attachments[0].Title" class="form-control" placeholder="Attach Title" />
</div>
<div class="row form-group">
    <input id="Attach1_File" asp-for="@Model.Attachments[0].AttachFile" class="form-control" placeholder="Attach Title" />
</div>
...

const title1 = $("form").find("#Attach1_Title");
const file1 = $("form").find("#Attach1_File");

formData.append(title1.attr('name'), title1.val());
formData.append(file1.attr('name'), file1[0].files[0]);
```

**Comment by bahmansh** [comment]
Is this issue done in dotnet core 3.preview 9 release?

**Comment by bahmansh** [comment]
I have got dotnet core 3.1, but this issue is not resolved yet.
@mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
Hi.

**It looks like you are posting on a closed issue!**
We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
