### ISSUE TITLE
Blazor (Server-Side) component not refreshing on navigation with multiple routes

### ISSUE THREAD

**Issue by audacity76** [aspnet/AspNetCore#12232]
### Describe the bug
If a razor component has optional parameters (multiple routes) it does not refresh if navigating from the component with parameter to the component without parameter.

### To Reproduce
1. Using this version of ASP.NET Core ASP.NET Core 3.0.0-preview6.19307.2
2. Run this razor component
```
@page "/about"
@page "/about/{Who}"

<h1>About @(Who ?? "us")</h1>

<a href="/about">about us</a> | <a href="/about/you">about you</a> | <a href="/about/me">about me</a>

@code {
    [Parameter]
    public string Who { get; set; }
}
```
3. With these arguments `/about`. Click on _about you_. Click on _about us_.
4. No refresh when navigating to _about us_

### Expected behavior
It should refresh.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @audacity76.
We plan to address this issue as part of #7419

**Comment by RemiBou** [comment]
This was fixed then reverted because it caused default property value to be ignored ("public int myprop {get;set;} = 2"). 

There is a workaround on this

```cs
 public override async Task SetParametersAsync(ParameterCollection parameters)
    {

        if (string.IsNullOrEmpty(parameters.GetValueOrDefault<string>("Who")))
        {
            Who = null;
        }

        await base.SetParametersAsync(parameters);
    }
```
