### ISSUE TITLE
Stopping API method—iterator on HTTP disconnection

### ISSUE THREAD

**Issue by progalgo** [aspnet/AspNetCore#12234]
Consider API controller. Its `Get` method return type is IEnumerable<>. Method 
written as a C# iterator. When connection is closed by browser, iterator
continues to yield values and holds a thread busy.

### To Reproduce

Using ASP.NET Core 2.2.0

1. Use this method in controller:
```
public IEnumerable<int> Get()
{
    for (int i = 0; i < 1000000; i++)
    {
        yield return i;
    }
}
```

2. Make HTTP request for this method.
3. Abort HTTP request.
4. See thread still running method

### Expected behavior
Since method is iterator, I expected control be in ASP.NET to terminate handling of
aborted HTTP request. There is no use in running the rest of iterator, not in my case
at least.

### Additional context
I am running this ASP.NET Core app on .NET Framework 4.7.2, not .NET Core.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @progalgo.
It's the developer's choice to make whether an execution can be terminated or not.
You can update your action method to accept a `CancellationToken cancellationToken` and check for cancellation yourself, as necessary. Here is an article detailing this out: https://andrewlock.net/using-cancellationtokens-in-asp-net-core-mvc-controllers/
