### ISSUE TITLE
BlazorWasm-CSharp.Client.csproj is invalid XML

### ISSUE THREAD

**Issue by danmosemsft** [aspnet/AspNetCore#12249]
This is currently breaking the build for https://source.dot.net because it cannot parse all C# project files in the tree.
@isaac2004 
```
C:\git\aspnetcore>\t\ppxml src\Components\Blazor\Templates\src\content\BlazorWasm-CSharp\Client\BlazorWasm-CSharp.Client.csproj | \t\tail -3
#### End tag 'ItemGroup' does not match the start tag 'Project'.
Line 0016:   </ItemGroup>
Pos  0005: ----^
```
```
C:\git\aspnetcore>git log src\Components\Blazor\Templates\src\content\BlazorWasm-CSharp\Client\BlazorWasm-CSharp.Client.csproj
commit 900c6adff91a13825406fda6a062c666f5e606c6
Author: Isaac Levin <isaac.r.levin@gmail.com>
Date:   Mon Jul 8 14:46:07 2019 -0400

    changes to wasm template per Dan Roth
```
fyi @stephentoub

**Comment by isaac2004** [comment]
Thanks @danmosemsft! This must have been a rebase conflict that wasn't resolved, no idea how it passed CI @ryanbrandenburg I opened a PR to fix this

**Comment by danmosemsft** [comment]
Might be worth adding a validation step into the build perhaps.

**Comment by rynowak** [comment]
We're tracking the test gap here: https://github.com/aspnet/AspNetCore/issues/10269

The Blazor client side templates don't ship in the SDK, so they aren't built/tested in the same way right now 😞

**Comment by rynowak** [comment]
Fixed by: https://github.com/aspnet/AspNetCore/pull/12247
