### ISSUE TITLE
MVC DiagnosticListener changes break Intellitrace

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#12263]
Our recent change to the casing of some properties in our DiagnosticListener events breaks Intellitrace. This will cause things like unit test failures tried to debug tests.

**Comment by davidfowl** [comment]
I think we should just add the older properties as lower case to the new types and obsolete them.

**Comment by rynowak** [comment]
Yeah my plan is to review their code and then do that.

**Comment by rynowak** [comment]
https://github.com/aspnet/AspNetCore/pull/12323
