### ISSUE TITLE
[BUILD]Typo : InstallDotNet call twice GetDotNetInstallScript

### ISSUE THREAD

**Issue by tebeco** [aspnet/AspNetCore#12275]
### Describe the bug
At the end of the line, it seems that an manual indent or reformat ended up in a duplicate call to `GetDotNetInstallScript` : 

Scroll to the right of this code block :
```powershell
function InstallDotNet([string] $dotnetRoot, [string] $version, [string] $architecture = "", [string] $runtime = "", [bool] $skipNonVersionedFiles = $false) {  $installScript = GetDotNetInstallScript $dotnetRoot
  $installScript = GetDotNetInstallScript $dotnetRoot
  $installParameters = @{
```
### Expected behavior
only one call should be made to `GetDotNetInstallScript` in `InstallDotNet`

#### Side notes 
It's like this from the very first commit,
it looks like it was created by either an automation or from an already existing script, so this may be existing in another repo somewhere publicly or internaly
https://github.com/aspnet/AspNetCore/commit/347ddcb6e20a5ef291972604407894baf5f14526#diff-58d6d2c2760628d9551cc8b40461ce53

**Comment by tebeco** [comment]
Sorry for pinging you like this, it seems this time github did not auto assigned anyone, just saw you were involved in other build issues
@natemcmaster 
@aspnet/build
@mkArtakMSFT
@anurse 

After investigating weird behaior on my box i found this.

**Comment by rynowak** [comment]
@aspnet/build

**Comment by anurse** [comment]
This is actually an arcade issue, as this content comes from dotnet/arcade. Moving.

**Comment by anurse** [comment]
This issue was moved to dotnet/arcade#3304
