### ISSUE TITLE
Question: Can I add localization of Razor components to a Blazor project without using MVC?

### ISSUE THREAD

**Issue by SeppPenner** [aspnet/AspNetCore#12277]
### Question
Not actually a bug, but a question. The new Blazor project template uses `EndpointRouting` by default. Can I add localization of Razor components to this without using MVC? If not, how can I configure the project to work with MVC correctly? Or do I just have a problem with understanding something here?

I'm trying to follow  https://docs.microsoft.com/en-US/aspnet/core/fundamentals/localization?view=aspnetcore-3.0 to add localization support to some razor component.

My `Startup.cs` class (and the component code and `_Host.cshtml`) can be found here: https://gist.github.com/SeppPenner/4e3d909a16a53cfab8e701d293344356

If I add the commented code:

```csharp
services.AddMvc(options => options.EnableEndpointRouting = false).AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix).AddDataAnnotationsLocalization();
```

and

```csharp
app.UseMvc();
```

I get the a null reference exception in the `_Host.cshtml` in the line

```cshtml
<app>@(await Html.RenderComponentAsync<App>())</app>
```

If I comment the both lines, it cannot work, of course and it throws the exception:

```log
InvalidOperationException: Cannot provide a value for property 'Localizer' on type 'TestComponent'. There is no registered service of type 'Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer'.
```

### To Reproduce
1. Using NET Core 3.0.100.12264 (preview-6).
2. Visual Studio 2019 Preview 16.2.29021.104.
3. Create a default app.
4. Scaffold the identity pages (Don't know if this is relevant, but I did it.
5. Adjust the `Startup.cs` and `_Host.cshtml` file as described and create the component.

### Resource files
The resource files are named `TestComponent.en.resx` and `TestComponent.de.resx` and located under the `Translations` folder in the main

**Comment by rynowak** [comment]
Have you tried using `IStringLocalizer<>`? `IViewLocalizer` is an MVC feature, and I expect that it won't work inside Blazor.

**Comment by SeppPenner** [comment]
@rynowak Thanks for the information. That's what I was searching for. Works as expected.

**Comment by SeppPenner** [comment]
Just another thing. Do you have an example on how I can localize e.g. a `DateTime` format in the same setup?

**Comment by rynowak** [comment]
That will just generally work by default since .NET's formatting uses `CultureInfo.CurrentCulture` by default.

We're making some changes in preview 8 that will make this work correctly with `@bind`. If you have a specific scenario in mind, I'd suggest trying it out in preview 8 and logging an issue if its not to your satisfaction.
