### ISSUE TITLE
[Feature Request] UserManager should generate shorter tokens

### ISSUE THREAD

**Issue by lonix1** [aspnet/AspNetCore#12272]
Similar to problem already [mentioned here](https://stackoverflow.com/questions/27420532/asp-net-indentity-confirmation-token-ridiculously-long-any-way-to-shorten-this).

## Problem
`UserManager.GenerateEmailConfirmationTokenAsync()` (and related methods) generates very very long tokens.

For example:
`http://example.com:9999/de-DE/Account.aspx/ConfirmEmail?userId=1f4f605a-1be5-4b79-9fb0-139687fe8edc&code=0AjkI5qK917WkZw%2Bz0nXf1uK%2BK9bvYAK6BNEVM2l%2Fc%2BlBYOIiitrQ0gMUrB96CCNYc11hnpNpp2Wg2buC548mAb8l9JwzcwfuOiMAXiwJ%2F3iDH1LlXWgiLW%2FXxcVqLEs2hIhvmye2%2FJxQZD3RcODyNyGD%2FnWjrJRoFK%2B16FtyrtimfNRL%2F1L9vgrk5HiWENn`

This mangles emails, and often leads to copy-paste errors by the user.

## Solution
Please allow us to generate shorter tokens.

## Additional info
That linked StackOverflow question has an interesting idea, which is to generate the token, hash it to a shorter string, store the hash, and send the hash. Then reverse the process when the user clicks the confirmation link in his email. This works but:
- it's an ugly workaround
- it's masking the problem
- the token is secure, I don't want to take the chance of weakening security... I trust the framework

**Comment by blowdart** [comment]
You can have shorter tokens by implementing your own token generator. However this is not something we're planning to provide.

**Comment by lonix1** [comment]
Ok thanks.

But note that the token generated right now is crazy long, and leads to many user problems.
