### ISSUE TITLE
Change [Parameter] warning (BL0005) to be an error - External [Parameter] usage

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#12293]
In preview8 we [added a warning](https://github.com/aspnet/AspNetCore/blob/7bed5df4d02740dc7143af9c43a6cbc5ce5bcd8e/src/Components/Analyzers/src/DiagnosticDescriptors.cs#L50) for external `[Parameter]` usages. In preview9 we need to make this an error.

This is tracking work initially mentioned [here](https://github.com/aspnet/AspNetCore/issues/8825).

**Comment by NTaylorMullen** [comment]
Actually, just to clarify, @rynowak / @SteveSandersonMS  was updating diagnostics to errors inclusive for the external parameter usage case? Is that what you meant in your statement `Change from warning to error in the analyzer`? Or were you only referring to https://github.com/aspnet/AspNetCore/issues/12294 ?

**Comment by rynowak** [comment]
I hadn't thought about it but I don't have a  super duper strong feeling.

I generally like the idea of keeping the diagnostic for setting a property as a warning forever. We're telling you that you *probably shouldn't*.

Contrast this to defining a parameter property as non-public. We're telling you that it *definitely will not work*.

**Comment by NTaylorMullen** [comment]
> I generally like the idea of keeping the diagnostic for setting a property as a warning forever. We're telling you that you _probably shouldn't_.
> 
> Contrast this to defining a parameter property as non-public. We're telling you that it _definitely will not work_.

Definitely agree. Glad  I clarified 😄

**Comment by rynowak** [comment]
@SteveSandersonMS any thoughts?

**Comment by SteveSandersonMS** [comment]
I agree with your comments above
