### ISSUE TITLE
Deadlock for calling sync method inside an async method

### ISSUE THREAD

**Issue by peteryangthinkgeo** [aspnet/AspNetCore#12299]
Hi Supported Team,

I found that it runs into deadlock issue if I invoke a sync method inside an aysnc method.

Thanks,
Peter

**Comment by davidfowl** [comment]
Do you have some code you can share? Even better would be a working sample demonstrating what you're running into.

**Comment by peteryangthinkgeo** [comment]
<button class="btn btn-primary" @onclick="@GetResponse">Sync</button>
<button class="btn btn-primary" @onclick="@GetResponseAsync">Async</button>

@code {
    void GetResponse()
    {
        Task.Delay(1000).ConfigureAwait(false).GetAwaiter().GetResult();
    }
    async void GetResponseAsync()
    {
        await Task.Delay(1000);
    }
}

If you click the "Sync" button, you will see the UI is blocked.

Thansk,
Peter

**Comment by davidfowl** [comment]
Ah so this is a blazor issue. I have a few questions:

- Why are you calling `GetAwaiter().GetResult()` instead of just awaiting the task?
- Why are you using async void?

You should read this https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by peteryangthinkgeo** [comment]
Yeah, this is an issue for Blazor, and I know how to fix this, the code I provided just used to simuate the scenario. The same code can work well on Blazor Server Side, but can't work on the Blazor Client Side. 

Thanks,
Peter

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @peteryangthinkgeo.
This is not supported at the moment, and this is a Mono-limitation.
