### ISSUE TITLE
Change [Parameter] warning (BL0004) to be an error - Non-public parameters

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#12294]
In preview8 we [added a warning](https://github.com/aspnet/AspNetCore/blob/7bed5df4d02740dc7143af9c43a6cbc5ce5bcd8e/src/Components/Analyzers/src/DiagnosticDescriptors.cs#L41) for non-public `[Parameter]`s. In preview9 we need to make this an error.

This is tracking work initially mentioned [here](https://github.com/aspnet/AspNetCore/issues/8825).

**Comment by Joe4evr** [comment]
Just to note, there are apparently people who want to have internal `[Parameter]`s: #12271.
