### ISSUE TITLE
Add User-Agent Header to identify client types

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#12295]
We had this at some point and removed it, but I think it would be valuable to be able to tell what type of clients are connecting. We'd do this by setting the User-Agent header. This could definitely be a point of interest for customers/ASRS.

**Comment by anurse** [comment]
Post 3.0 but this is awesomesauce.

**Comment by anurse** [comment]
@bradygaster can you follow up on possible justification for taking this in 3.1.

**Comment by bradygaster** [comment]
Will do in the team room.

**Comment by mikaelm12** [comment]
These changes have been merged into master fyi. We still need to port into 3.1

**Comment by anurse** [comment]
Let's do this in 3.1, it's really useful for LTS.

**Comment by anurse** [comment]
Unfortunately we're still missing a few things to align with the original spec (below) so I don't think this will land in 3.1. We'll get it in and if there's time we can check it against the bar (and customer/partner interest) and see where we are.

For example:
* [ ] Support in TypeScript (using `UserAgent` in Node, and a custom header `X-SignalR-UserAgent` in the browser)
* [ ] Normalizing OS names
* [ ] Clear tests showing input values (OS names, versions, etc.) and the resulting User Agent (to compare against the examples below).

---

Let's make the user agent values consistent across as many clients as we can. Right now, the .NET client's user agent is `Microsoft.AspNetCore.Http.Connections.Client/[version]`. Yuck. The layering makes sense, but I don't like it. My vote would be to just compromise the layering a bit here and call it "Microsoft SignalR". It's just a string, nothing actually couples the layers by doing this. A huge majority of people using the lower layer will be using "SignalR" as we know it.

My proposed format for the User-Agent string is something like this:

```
Microsoft SignalR/[Version] ([Detailed Version]; [Operating System]; [Runtime]; [Runtime Version])
```

Where:
* `[Version]` is the major/minor of the SignalR client itself.
  * For .NET client, we can just use the major and minor components of the Assembly version.
  * For JS we have a `VERSION` constant which is the full version. We can parse it, or add a new `SHORT_VERSION` constant or something with just the major/minor component.
  * For Java I don't know, we'll have to find out.
* `[Detailed Version]` is the really detailed version (including full build number). In .NET we store this in the `AssemblyInformationalVersionAttribute`. TBD for Java/JS
* `[Operating System]` is an OS type, just based on [`RuntimeInformation.IsOSPlatform`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform?view=netframework-4.8) in .NET, `process.platform` in JS.
	* `Windows NT` for Windows
	* `macOS` for macOS
	* `Linux` for Linux
* `[Runtime]` is a simple name defining the kind of runtime the client is on (`.NET`, `Java`, `NodeJS` would be the three options we have right now)
* `[Runtime Version]` is a version of the runtime (.NET, Java, NodeJS, etc.):
	* .NET: [`RuntimeInformation.FrameworkDescription`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.frameworkdescription?view=netframework-4.8) is probably best
	* Java: Probably the [`java.version` system property](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html), maybe with `java.vendor` prepended?
	* NodeJS: `process.versions.node`

Examples:

* .NET Core: `Microsoft SignalR/3.0 (3.0.0-preview9.12345.1; Windows NT; .NET; .NET Core 4.6.27317.03)` (the version number FrameworkDescription spits out is a bit odd but we can back-trace it to the "marketing" version)
* Java: `Microsoft SignalR/3.0 (3.0.0-preview9.12345.1; macOS; Java; 1.5.0)`
* NodeJS: `Microsoft SignalR/3.0 (3.0.0-preview9.12345.1; Linux; NodeJS; 11.11.0)`

So there are two work items here I think:

1. Figure out how to properly get the version of the Java client from **within the Java client itself*. We may actually have to just generate a Java class with it as a constant, if there's no built-in way (like our attributes in .NET).

1. Update all the user agents to have this data.

And of course, a user-specified `User-Agent` value should always override.

Thoughts?
