### ISSUE TITLE
Blazor: Pre-rendering + Auth + Redirect

### ISSUE THREAD

**Issue by ctrl-alt-d** [aspnet/AspNetCore#12309]
### Problem description

The usual pattern (on mvc) is: _if user is not authenticated, redirect to login_. Like this:

```
@page "/"

<button @onclick="@LogUsername">Log username</button>

@code {
    [CascadingParameter]
    private Task<AuthenticationState> authenticationStateTask { get; set; }

    protected override async Task OnInitAsync()
    {
        var authState = await authenticationStateTask;
        var user = authState.User;
        if (!user.Identity.IsAuthenticated)
        {
            var redirect = Url.ToBaseRelativePath( Url.GetBaseUri(), Url.GetAbsoluteUri() );
            Url.NavigateTo($"/login?redirect={redirect}");
            return;
        }
    }
}
```

But, on serverside, **with prerendering,  `NavigateTo` raises error if is invoked from `OnInitAsync`.**

### Describe the solution you'd like

I would like to apply the pattern _no login then redirect_ on default server side configuration (with pre-render)

### Additional context:

I know It is possible to show an anchor or button in the page with a link to login url, but it is not so elegant.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ctrl-alt-d.
This seems to be caused by #11591

**Comment by MarvynHarry** [comment]
What do I have to do to be able to use these methods since in my project it says "no suitable method found to override"
![image](https://user-images.githubusercontent.com/44927942/61802499-ec5c0080-ae06-11e9-9603-d8251013b81f.png)

**Comment by MarvynHarry** [comment]
hepl me @mkArtakMSFT

**Comment by ctrl-alt-d** [comment]
Post detailed question on StackOverflow and send the link here ;)
