### ISSUE TITLE
net::ERR_SPDY_PROTOCOL_ERROR 200

### ISSUE THREAD

**Issue by TehWardy** [aspnet/AspNetCore#12301]
I have these entity types ...

```
[Table("Packages", Schema = "Packaging")]
public class Package
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    [Required]
    [StringLength(100)]
    public string Category { get; set; }

    [Required]
    [StringLength(200)]
    public string SourceApi { get; set; }

    public virtual ICollection<PackageItem> Items { get; set; }

    public Package() { }

    public Package(string name) { Name = name; }
}

[Table("PackageItems", Schema = "Packaging")]
public class PackageItem
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    [ForeignKey("Package")]
    public Guid PackageId { get; set; }

    // used to determine T for data
    public string Type { get; set; }

    // JSON of the object being imported
    public string Data { get; set; }

    public virtual Package Package { get; set; }

    public T Unpack<T>() { return JsonConvert.DeserializeObject<T>(Data); }
}
```

And this method in my OData controller ...

```
[HttpGet]
[EnableQuery]
public IActionResult Export([FromODataUri]int key)
{
    var result = Service.Export(key);
    return Ok(result);
}
```

When I request it with ...

> HTTP GET ~/Api/Controller/Export()?$expand=Items

I get the response ...

> net::ERR_SPDY_PROTOCOL_ERROR 200

... The response body appears to be empty.

In the older .Net 4.6 implementation of this same request the response comes back fine.
I'd like some guidance on debugging or fixing this.

I'm using the latest "not preview" builds from github for  netcore 2.2 for the aspnet stack and the OData libs and has the following using directives (on top of my own internal dependencies) ...

using Microsoft.AspNet.OData;
using Microsoft.AspNet.OData.Query;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

...

Which have come from Nuget packages ...

```
Microsoft.NetCore.App 2.2.0
Microsoft.AspNetCore.App 2.2.0
Microsoft.AspNetCore.Razor.Design 2.2.0
Microsoft.AspNetCore.OData 7.1.0
```

Hopefully this is relevant here as opposed to the OData side but happy to repost there or reference if you guys think this is an OData specific issue.

From the API tester tool in our platform (does what postman does using ajax calls) this is what the .Net 4.6 version does for comparison and ultimately what I would expect form the same code in netcore ...

![image](https://user-images.githubusercontent.com/6891030/61440869-70f8db80-a93c-11e9-999e-733e92551675.png)

... Interestingly i notice that there is a response coming back but it appears to be incomplete ...

`{"@odata.context":"https://mydomain/Core/$metadata#packages","value":[{"Id":"00000000-0000-0000-0000-000000000000","Name":"Roles"`

... It appears to be cutting the response short for some reason (presumably due to some sort of serialization failure and the frameworks resulting behavior from the framework must then be to just end the response.

Is there any way I can catch internal exceptions / issues in the framework to help with this?

I do already have this in my startup ...

```
app.UseExceptionHandler(errorApp =>
{
    errorApp.Run(async context =>
    {
        var ex = context.Features.Get<IExceptionHandlerPathFeature>();
        log.Error(ex.Error.Message + "\n" + ex.Error.StackTrace);

        context.Response.StatusCode = ex.Error.GetType() == typeof(SecurityException) ? 401 : 500;
        context.Response.ContentType = "application/json";
        await context.Response.WriteAsync("{ \"error\": \"" + ex.Error.Message.Replace("\"", "\'") + "\" }");
    });
});
```
... but it's not logging anything which suggests that this might be intended behavior for some reason.

Further information ....

- I have discounted it being a client issue as this happens from multiple browsers.
- I have discounted this as being an EF / ORM issue as the data is computed and contains no actual entities managed by the EF context (although the data has come from EF).
- The code runs completely right through to beyond the Ok() call in the controller which returns a Package[] (see type data above).

**Comment by TehWardy** [comment]
From the API tester tool in our platform (does what postman does using ajax calls) this is what the .Net 4.6 version does for comparison and ultimately what I would expect form the same code in netcore ...

![image](https://user-images.githubusercontent.com/6891030/61440869-70f8db80-a93c-11e9-999e-733e92551675.png)

**Comment by TehWardy** [comment]
So I have an extension method in my web stack that I can use to call in to newtonsofts json serializer for any object, it turns out when I do this ....

```
[HttpGet]
[EnableQuery]
public IActionResult Export([FromODataUri]int key)
{
    var result = Service.Export(key);
    return Ok(result.ToJson());
}
```

And change this in the OData model builder to ...

```
Builder.EntityType<App>().Function("Export").Returns<string>();
```

... it works.
This is essentially pointing to an issue in the serialization process employed by the framework from what i can tell.

Some hints (as i can't really share the data) as to what the issue might be ....

The package items can contain objects in the Data field serialized to a block of json already but those items in a few cases could contain blocks of HTML or javascript which in turn could contain json.

I think this is an issue with nested serialization in json that contains json.

**Comment by jkotalik** [comment]
In your webhost, are you using Kestrel or IIS? If you are using Kestrel, do you have Http2 enabled?

**Comment by TehWardy** [comment]
Is Http2 not enabled by default ? 
Seems like an odd thing to not do for new framework.

I'm using Kestrel.

**Comment by jkotalik** [comment]
it isn't enabled by default in 2.2. Will be on by default in 3.0.

**Comment by anurse** [comment]
@TehWardy is it possible an exception is being thrown in your response? If an exception is raised **after** headers have been sent, you can get something like this since ASP.NET Core can't change the response into a 500 at that point. Server logs should show an error if one is occurring.

Can you provide a runnable sample project that reproduces the issue?

**Comment by TehWardy** [comment]
@anurse No it's not possible the issue is in my response.
If I use the newtonsoft json serializer to serialize the response object and tell the framework that it's returning a string it works, the whole request and response.

This issue is in the frameworks response handling for complex data.
I can't provide you the full details of the request because it's corporate secure data but I have found the issue is in a response object that contains string properties on either the object or child objects returned.

In my case I have a page object that contains a collection of content objects which are literally containers for some html and some javascript (separate string properties.

The issue I hit was when the javascript / html blocks in the content object contained blocks of json.
It seems to confuse the serializer but the newtonsoft one is able to solve it.

**Comment by anurse** [comment]
So are you getting an exception or not? It's not clear from your description if there is an exception being emitted when rendering your object. Even if that exception is coming from the framework, we would need to know what is being thrown so that we can get a clear idea of what's going on.

> I can't provide you the full details of the request because it's corporate secure data but I have found the issue is in a response object that contains string properties on either the object or child objects returned.

Can you share a sample object that reproduces the issue with secure data removed/renamed/replaced? What happens if you serialize this object in a simple Console application? If we can isolate a repro like that, we can report it to the corefx team that owns System.Text.Json.

> It seems to confuse the serializer but the newtonsoft one is able to solve it.

There are definitely limitations with the System.Text.Json serializer. Newtonsoft.Json has a number of features that System.Text.Json *does not have*. If Newtonsoft works for your scenario, you can certainly continue using it.

**Comment by TehWardy** [comment]
if I do ...

```
var result = DoSomeBusinesLogic();
return Ok(result);
```

... then it begins responding and stops about 100 characters in to the json response. 
The server literally just ends the response there.

If I do ...

```
var result = DoSomeBusinesLogic();
return Ok(result.ToJson());
```

... it returns normally as i would expect but i need it to work without the .ToJson() call.

My business logic runs perfectly fine on both occasions the failure is happening in the framework code after the return of the controller action.

**Comment by anurse** [comment]
That's exactly what I'd expect from a serialization problem. `ToJson` is provided by Newtonsoft.Json I believe, so it would be using a different serializer. What is the structure of the object you are sending?

Also, I'm still not clear on if an exception is thrown in the first case. I'd expect an exception if the response is being ended abruptly. That exception would have details. Is anything showing up in the logs (either Console if you're using Kestrel or in the "ASP.NET Core Web Server" tab of the Output Window in VS if you're using IIS).

**Comment by TehWardy** [comment]
@anurse object structure is in the first post of the thread.
As I have said repeatedly ... the response simply stops as if it's done ... i get nothing beyond those first few chars from the json response.

I got married on sunday and i'm about to go off on my honeymoon so i will likely be a bit unresponsive for a bit ... honestly I think this is an issue with encoding complex responses, just make an object that has a string property and put a block of javascript in it or something that deserialzes a block of json (like you might do on a web page) and try that. 

If you really can't reproduce it i'll see if i can get you the sample I've had issues with on my return to the office.

**Comment by anurse** [comment]
I built a possible repro and see an exception on the server logs exactly as I'd expect in this circumstance:

```
System.Text.Json.JsonException: CurrentDepth (32) is equal to or larger than the maximum allowed depth of 32. Cannot write the next JSON object or array.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DepthTooLarge(Int32 currentDepth, WriteStack& writeStack, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type type, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

The issue I see is that you have a recursive structure where the package item contains a back-reference.

> ```csharp
>   public virtual Package Package { get; set; }
> ```

This is not supported automatically by System.Text.Json (which is why Newtonsoft.Json works). The problem even repros trivially with a sample in a Console application.

You either need to remove this recursive reference, or tell the serializer not to serialize this value by applying the `JsonIgnore` attribute:

```csharp
  [JsonIgnore]
  public virtual Package Package { get; set; }
```

Unless I'm missing something in my repro, that seems to be the source of the problem. I'm surprised you see no exceptions **in the server log** as it's very clear in my repro. The **response** will not show an exception because of the issue I mentioned above (the exception occurs *after* parts of the response have been written). However, there should have been something in the server console logs. Can you share the full server console output/logs as I described above to help investigate why the exception isn't appearing?

**Comment by TehWardy** [comment]
Not possible in this particular request, the object being returned is being constructed from values not entities connected to something like an EF context.
This was sone of the first things I checked, what's actually constructed is a collection of package objects that contain package items, all package items have the package property set to null (checked at runtime).

That said ... To EF + AspNet Core + Odata to work correctly I had to add this to my startup ...

```
services.AddMvcCore(options =>
{
    options.EnableEndpointRouting = false; // TODO: Remove when OData does not causes exceptions anymore
})
.AddDataAnnotations()
.AddJsonFormatters(options => options.ReferenceLoopHandling = ReferenceLoopHandling.Ignore)
```

Note the last line there ... I figure that's the point to that line, so if this was the case in my request that should have already been handled somewhere in the framework.

Does that line work if you add it to your example in solving the problem example you have?
It makes no difference to my problem.

I should also note that where I'm using OData here I have on the majority of my endpoints literally returned ... `Ok(EF.Context.Set<T>())` and it works perfectly so this call should be no different. 

 In case it helps though this screenshot of the code that produces my result should help you understand why i don't think this is a recursion / EF related problem ... 

![image](https://user-images.githubusercontent.com/6891030/62453697-c1f53600-b76a-11e9-9265-687a1c5acfeb.png)

**Comment by anurse** [comment]
> I think the issue is that the DB content can contain anything from html fragments to javascript, to javascript that contains json to html that contains javascript that iin turn contains json which is why i suspect a serialization issue.

The serializer is definitely resilient to this. If the DB content contains HTML/JavaScript fragments, they will be escaped.

> Personally i prefer the newtonsoft json stuff to the one the framework uses ... is it possible to replace the framework one with the newtonsoft one that seems to be getting this right already?

Absolutely, you can install the package `Microsoft.AspNetCore.Mvc.NewtonsoftJson` and then call `services.AddMvc().AddNewtonsoftJson()` to `ConfigureServices`.

Can you please attach server console logs from your application (as [requested above](https://github.com/aspnet/AspNetCore/issues/12301#issuecomment-516054063))? Without that, it's not possible to identify the specific serialization issue. In this context, a serialization error isn't rendered to the response, but **will be logged to the console**. I'd like to see the full server console logs to understand what's going on. Even if you don't see any errors, please attach the logs and we can investigate further from that.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by TehWardy** [comment]
Hmmm ... I wasn't notified of your last reply @anurse ... here's the server console log you asked for ...

```
Api> fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
Api>       An unhandled exception has occurred while executing the request.
Api> Microsoft.OData.ODataException: The property 'Description[Nullable=False]' of type 'Edm.String' has a null value, which is not allowed.
Api>    at Microsoft.OData.WriterValidationUtils.ValidateNullPropertyValue(IEdmTypeReference expectedPropertyTypeReference, String propertyName, IEdmModel model)
Api>    at Microsoft.OData.WriterValidator.ValidateNullPropertyValue(IEdmTypeReference expectedPropertyTypeReference, String propertyName, Boolean isTopLevel, IEdmModel model)
Api>    at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteNullProperty(ODataProperty property)
Api>    at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, IDuplicatePropertyNameChecker duplicatePropertyNameChecker)
Api>    at Microsoft.OData.JsonLight.ODataJsonLightWriter.StartResource(ODataResource resource)
Api>    at Microsoft.OData.ODataWriterCore.InterceptException(Action action)
Api>    at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
Api>    at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
Api>    at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
Api>    at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
Api> --- End of stack trace from previous location where exception was thrown ---
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Api>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Api>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Api>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Api>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Api>    at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
Api>    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
Api>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
Api> warn: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[2]
Api>       The response has already started, the error handler will not be executed.
Api> fail: Microsoft.AspNetCore.Server.Kestrel[13]
Api>       Connection id "0HLP1AOEVG4SO", Request id "0HLP1AOEVG4SO:00000004": An unhandled exception was thrown by the application.
Api> Microsoft.OData.ODataException: The property 'Description[Nullable=False]' of type 'Edm.String' has a null value, which is not allowed.
Api>    at Microsoft.OData.WriterValidationUtils.ValidateNullPropertyValue(IEdmTypeReference expectedPropertyTypeReference, String propertyName, IEdmModel model)
Api>    at Microsoft.OData.WriterValidator.ValidateNullPropertyValue(IEdmTypeReference expectedPropertyTypeReference, String propertyName, Boolean isTopLevel, IEdmModel model)
Api>    at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteNullProperty(ODataProperty property)
Api>    at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, IDuplicatePropertyNameChecker duplicatePropertyNameChecker)
Api>    at Microsoft.OData.JsonLight.ODataJsonLightWriter.StartResource(ODataResource resource)
Api>    at Microsoft.OData.ODataWriterCore.InterceptException(Action action)
Api>    at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
Api>    at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
Api>    at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
Api>    at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
Api> --- End of stack trace from previous location where exception was thrown ---
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Api>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Api>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Api>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Api>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Api>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Api>    at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
Api>    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
Api>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
Api>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
Api>    at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
Api>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
If i'm understanding this right it's like the framework is refusing to export the entity collection for some validation reason ...

> The property 'Description[Nullable=False]' of type 'Edm.String' has a null value, which is not allowed.

This sounds like an OData issue at this point but it's strange that it begins responding before it trips up.

**Comment by TehWardy** [comment]
Ok i've fixed it by ensuring that the returned results are valid according to the metadata and it now seems to be responding as expected (just a minor issue with the odata expand not working for some reason).

Is there any reason why exceptions thrown out to the server console can't be given to the configured exception handler in startup?
I only ask because identifying this on a production box is effectively impossible unless the server console information can be captured in some way.

**Comment by anurse** [comment]
> Is there any reason why exceptions thrown out to the server console can't be given to the configured exception handler in startup?

The `ExceptionHandlerMiddleware` [exits early if the response has already started](https://github.com/aspnet/AspNetCore/blob/057ec9cfae1831f91f1a0e01397059b20431db7b/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L92). I think this is somewhat an artifact of the original behavior of the middleware. Originally, the middleware just wrote a generic error page to the response, which it can't do if the response has already started.

Since then, it has expanded to do things like call a user-provided delegate. It may be worth re-examining this logic and having it call the user-provided delegate even if the request has already started. I'll file a bug for exploring that.

You can also add your own middleware above the Exception Handler middleware, since the middleware *does* re-throw the exception if it can't handle it. So you'd see the exception in your outer middleware.

> I only ask because identifying this on a production box is effectively impossible unless the server console information can be captured in some way.

I'd strongly recommend using a system to capture log information in production. This is definitely a key element in diagnosing failures in production apps. There are many alternatives to capturing console output, some are [built-in](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#built-in-logging-providers) and there are a lot of [third-party logging solutions](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#third-party-logging-providers) that are very powerful.

**Comment by anurse** [comment]
Created https://github.com/aspnet/AspNetCore/issues/13170

**Comment by guedouarimohamed2** [comment]
@TehWardy can you axplain more how you resolved this probleme ?

**Comment by TehWardy** [comment]
In my case it was caused by the odata framework validating the entities after my controller action executed , in short ensure that your returned set is valid (data annotations).
