### ISSUE TITLE
IPv4 addresses are formatted in IPv6 format

### ISSUE THREAD

**Issue by YevhenLukomskyi** [aspnet/AspNetCore#12304]
### Describe the bug
`httpContext.Connection.RemoteIpAddress.ToString()` formats IPv4 addresses in IPv6 format.

### To Reproduce
1. Using this version of ASP.NET Core '2.2.6'
2. Add this code somewhere into the request pipeline  `httpContext.Connection.RemoteIpAddress.ToString()`
3. Generate a request from IPv4 host
4. `.ToString()` returns the address in IPv6 format. For example: ::ffff:192.168.1.1

### Expected behavior
`.ToString()` for IPv4 addresses returns string formatted in IPv4 format - 192.168.1.1

**Comment by samsosa** [comment]
As far as I know, this is intended, because the OS use an IP-Dual Network Stack (unified IPv4 and IPv6 processing).

Some info of this behavior and maybe a solution here: [System.Net.IPAddress MapToIPv4()](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.maptoipv4?view=netframework-4.8)

**Comment by YevhenLukomskyi** [comment]
ASP.NET Core 2.0.3 returns IPv4 in the same circumstances. Is it an intentional change that was made in the recent releases? I haven't found anything related to it in the release notes.

**Comment by samsosa** [comment]
ASP.NET Core 2.0.3 runs in top of libuv an used a slim shim "libuv_socket". Starting with ASP.NET Core 2.1.0, "real managed sockets" replaced libuv as ASP.NET Core default transport.

https://github.com/aspnet/Announcements/issues/296

**Comment by jkotalik** [comment]
Do you know which server you are using (Kestrel or IIS)? In 2.2, we also added an IIS based server which could have different behavior too.

**Comment by YevhenLukomskyi** [comment]
@jkotalik I'm using Kestrel

**Comment by Tratcher** [comment]
Yes this is expected because the server is using an IPv6 dual mode socket. The mitigation given above is the recomendation. https://github.com/aspnet/AspNetCore/issues/12304#issuecomment-512767090

**Comment by YevhenLukomskyi** [comment]
Thanks everyone for explanation! I'm closing the issue
