### ISSUE TITLE
Blazor: DLLs being flagged by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by chanan** [aspnet/AspNetCore#12308]
I haven't seen this till now. When I browsed to a CSB (https://blazorstyled.io) I got a warning from Symantec regarding:

* One of my blazor dlls (BlazorPrettyCode.dll)
* and System.Net.Http.dll

![image](https://user-images.githubusercontent.com/472554/61462315-a77c2980-a92f-11e9-9cab-e23ffbf37ad5.png)

**Comment by blowdart** [comment]
This isn't a virus present warning, but rather a "I don't know enough about this file, so I'm going to assume it's risky and strop access".

There's not we can do about this. If you can adjust the "Download Insight sensitivity level" then that would be how to address it.

**Comment by RemiBou** [comment]
I found a hack for adressing this https://remibou.github.io/Change-Blazor-DLL-extension-with-ASPNET-Core/ maybe it'll work if symantec only checks extensions.

**Comment by chanan** [comment]
Both good ideas, but won't work for me.

1. I can't change Symantec Endpoint settings as it is controlled by our IT department
2. Looks good, but since my site is a CSB hosted on github pages, I don't think I can change the server rules like that

I am aware that this is not a code problem per say and that CSB is not releasing yet, but I think Blazor CSB is going to  be successful, these types of issues need to be addressed *somehow* - not sure what that "how" needs to be though.

**Comment by RemiBou** [comment]
You can do the server part at deploy time and rename your file when copying to your static server. I am not sure what is CSB though.

**Comment by chanan** [comment]
Client Side Blazor vs Server Side Blazor

**Comment by RemiBou** [comment]
So you can rename the file in github page (with .blazor extension), then use the (dirty) hack with the fetch override.

**Comment by chanan** [comment]
I will check it out

**Comment by danroth27** [comment]
Broader issue tracked by https://github.com/aspnet/AspNetCore/issues/5477
