### ISSUE TITLE
Resolve removing OnReaderCompleted and OnWriterCompleted from SignalR

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#12312]
We recently deprecated OnReaderCompleted and OnWriterCompleted in System.IO.Pipelines. SignalR still uses it in a few places, which will need to be resolved: https://github.com/aspnet/AspNetCore/pull/12250/commits/3a8c5f51f283af77ff87ea02d028883a8d27d5ac#diff-b83fe5e05ee04ad736b9aacc8d40cc35R58 and https://github.com/aspnet/AspNetCore/pull/12250/commits/9718b0a05a2d7432b51ff482906be80f822d0112#diff-92cbe1dd0853764039db2a0f4fefa802R4 were the two I saw.

**Comment by davidfowl** [comment]
These are mostly in tests.

**Comment by anurse** [comment]
Since this is test code, we can probably squeeze this in to preview9. If not, we'll do it in `master` after branching.

**Comment by mikaelm12** [comment]
Done here:https://github.com/aspnet/AspNetCore/pull/13018
