### ISSUE TITLE
Make TagHelperOutput and TagBuilder indent html when rendering

### ISSUE THREAD

**Issue by 00george** [aspnet/AspNetCore#12311]
I know it isn't an important  feature but I am using TagHelpers and TagBuilder to build a few components such as setting the innerhtml of TagHelperOutput to be TagBuilders but when they render their html in the browser it comes out quite ugly. 

For example:
![image](https://user-images.githubusercontent.com/2363489/61468378-12038880-a975-11e9-83b7-40f530bdabe2.png)

Is there anyway you can make it so it renders it nicely?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @00george.
The reason behind TagHelpers not format the content is to save no all the extra characters. Besides, it'll be a relatively big amount of work to enable this and we can't justify such an investment.
