### ISSUE TITLE
RefreshOnIssuerKeyNotFound for  SecurityTokenInvalidSignatureException 

### ISSUE THREAD

**Issue by 99littlebugs** [aspnet/AspNetCore#12310]
Our environment swapped ADFS token signing keys for OIDC. The exception we received was `SecurityTokenInvalidSignatureException: IDX10503: Signature Validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey'...`
We looked into this situation and found that there is a `RefreshOnIssuerKeyNotFound` property which defaults to `true` but is triggered on `SecurityTokenSignatureKeyNotFoundException` which is not the exception we got. 

1. Using ASP.NET Core 2.0
2. setting up Open ID Connect with `AddOpenIdConnect`
3. and `TokenValidationParameters` with `IssuerSigningKey`
4. When the key was swapped, we saw exception above. 
5. restarting the app, pulled the new key and fixed everything. 

I would have expected to receive `SecurityTokenSignatureKeyNotFoundException` or for the ` RefreshOnIssuerKeyNotFound` property to be based off exception I did get.

**Comment by blowdart** [comment]
@jmprieur this appears to be from Wilson. Can you explain what's going on?

**Comment by Tratcher** [comment]
@brentschmaltz

**Comment by brentschmaltz** [comment]
@Tratcher @blowdart
The logic for the SecurityTokenSignatureKeyNotFoundException is there is a 'kid' in the JwtHeader AND it matches the keys that are available.

I could deduce that the JWT kid matched both times.

**Comment by 99littlebugs** [comment]
`kid` is not specified in our current token because we are on ADFS 2016. The [ADFS 2019 release notes ](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server) indicates that it was just added as a bug fix.

**Comment by 99littlebugs** [comment]
Is there a way to make this work even when the `kid` is not specified? The developer rarely has a choice whether it will be sent. Additionally, can the `RefreshOnKeyIssuerNotFound` documentation be updated with more information on when it should be expected?

**Comment by blowdart** [comment]
@brentschmaltz this is an unanswered question for you

**Comment by brentschmaltz** [comment]
@99littlebugs you can use extensibility in TokenValidationParameters to find keys: see
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d4d6d3598952410ff96ef8f38c9ca9ce74bca8bf/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L53
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d4d6d3598952410ff96ef8f38c9ca9ce74bca8bf/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L400

**Comment by 99littlebugs** [comment]
I meant, 
Is there a way to make the refresh work even when `kid` is not specified?
Is that what you are answering?

**Comment by brentschmaltz** [comment]
@99littlebugs there is stale metadata that has keys with kid empty?

**Comment by 99littlebugs** [comment]
The situation we are trying to avoid is having to restart our app when the ADFS token signing keys are swapped. We can not rely on the `RefreshOnIssuerKeyNotFound` property since we do not have a `kid`. Do we have other options?

**Comment by brentschmaltz** [comment]
@99littlebugs it may make sense to throw SecurityTokenSignatureKeyNotFoundException when there are keys in tokenvalidationparameters AND none of them resulted in valid signature.
Questioning why it seems significant that a kid existed in the jwt.

**Comment by brentschmaltz** [comment]
@Tratcher @99littlebugs I think we can handle this in IdentityModel.
see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1268

Please reopen if you don't think 1268 will fix this.
