### ISSUE TITLE
RazorSDK needs to define its own property for `ErrorLog` that gets passed to CSC

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#12322]
Currently Razor SDK will pass the value of `ErrorLog` in MSBuild to CSC - this is the same property that's used by the main invocation of CSC, and so the result is that the log file is overwritten.

This makes it much harder to troubleshoot problems with CSC since the error log gets clobbered.

**Comment by nguerrera** [comment]
Just for clarity, /errorlog isn't about problems with csc, it's a structured JSON rendering of all diagnostics in a standard format called SARIF. This integrates with various code analysis reporting systems, etc. Overwriting this file on View compilation makes the feature unusable together with razor sdk.

**Comment by novogeek** [comment]
+1. We are facing this issue currently for Asp.net core 2.2 projects wherein the code analysis results of Roslyn analyzers are being overwritten. The msbuild.log file has the code analysis warnings, but the sarif files doesn't. Looking forward for the fix.
