### ISSUE TITLE
 Unable to get request.body value

### ISSUE THREAD

**Issue by JeromeKen** [aspnet/AspNetCore#12347]
When using.net MVC's route to match route
A request. Body. Length of a post request whose header is application/x-www-form-urlencoded is 0
There is a value if routing is not used to match request.body.length

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JeromeKen. It's not clear what are the expectations here as well as what's going wrong. Can you please be more specific about what is the scenario and the issue you're seeing?

**Comment by pranavkm** [comment]
Feel free to reopen once you have more details to share.
