### ISSUE TITLE
Blazor Client-Side DI issue on Program.Main

### ISSUE THREAD

**Issue by RoroTiti** [aspnet/AspNetCore#12349]
### Describe the bug

Blazor Client-Side DI issue on Program.Main.

I would like to use services before the Blazor app is ready to listen requests. When I try the method described here : [Call services from main](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0#call-services-from-main), I obtain a sort of deadlock with high CPU and RAM usage (symptomatic of infinite loop).

If I run the same experiment on Chrome instead of on Firefox, I obtain the following message on console : **Uncaught (in promise) RangeError: Maximum call stack size exceeded**.

### To Reproduce
1. Using this version of ASP.NET Core : .NET Core 3 Preview 6
2. Run this code (Replace the Program.Main content by the following) :

```
        public static void Main(string[] args)
        {
            IWebAssemblyHost hostBuilder = CreateHostBuilder(args).Build();

            using (IServiceScope serviceScope = hostBuilder.Services.CreateScope())
            {
                IServiceProvider services = serviceScope.ServiceProvider;

                HttpClient httpClient = services.GetRequiredService<HttpClient>();
                httpClient.Timeout = TimeSpan.FromSeconds(10);

                // It's not the only thing expected to be done here, but that part is reproducible by everyone. 
                // I also tested with my own services, and I obtain the exact same result, so it's not from the HttpClient specific service.
            }

            hostBuilder.Run();
        }
```

3. See error when you run the app on your browser

### Expected behavior

I would expect the app to start correctly, with the ability to manipulate in Program.Main the services I need.

### Screenshots

Firefow complaining about web page slowing down browser.
![](https://i.imgur.com/Dnqw1Eb.png)

High CPU and RAM usage.
![](https://i.imgur.com/T3Mmb6B.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RoroTiti .
We suspect that the `WebHostBuilder.Run()` has a blocking `Wait` call, which doesn't work well with WebAssembly.

**Comment by RoroTiti** [comment]
Okay, thanks for the answer @mkArtakMSFT :) ! Is there anything I can do to help you to further debug the issue ?

**Comment by mkArtakMSFT** [comment]
We're currently focused on the upcoming 3.0 release. We'll be able to look into this after that.

**Comment by LiHRaM** [comment]
It seems to me that the service is never acquired. Running the following code:
```csharp
public static async Task Main(string[] args)
{
    var host = CreateHostBuilder(args).Build();

    using (var scope = host.Services.CreateScope())
    {
        Console.WriteLine("Acquiring service...");
        var state = scope.ServiceProvider.GetRequiredService<HttpClient>();
        Console.WriteLine("Service acquired...");
    }
}
```

I get the following log:
```
WASM: Acquiring service...
wasm-0070d5c2:161 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at :5000/wasm-function[160]:0
    ...
```
Initially, I tried running with `host.StartAsync()`, etc, but I am able to reproduce without calling _any_ method on `host` after trying to acquire the service.

**Comment by ApocDev** [comment]
Just FYI, I reported a bug related to exactly what you're attempting; https://github.com/aspnet/AspNetCore/issues/11716

Even if you could get a reference to the service (which you can), you will end up deadlocking in JSRuntime shortly after app startup.

Currently, you can't do any dynamic pre-startup DI inclusions with Blazor. Which sucks, considering it's a major requirement for most enterprise applications.

**Comment by acoop133** [comment]
I just updated my blazor packages to `3.0.0-preview9.19465.2` and httpclient DI client side injection is now working for me :D

**Comment by mkArtakMSFT** [comment]
There are multiple issues which we plan to work on, which will eliminate this issue. One is the HttpClient work, where we will switch to using the Mono-provided HttpClient, and the second is the API Review for the Blazor WASM startup experience.
