### ISSUE TITLE
Blazor server-side project hosted on far away server suffers latency problem

### ISSUE THREAD

**Issue by howardgod** [aspnet/AspNetCore#12342]
### Describe the bug
I deploy my Blazor server-side project to IIS on Windows Server 2012. The server is kindly of far distance from my laptop, average delay would be around 150 ms~200 ms.  So when I access the web app, it suffers latency problem seriously. Is this the limitation of deploy on server which is far away from client? If so, the only solution is to use Blazor client-side project instead?

### To Reproduce
1. dotnet core 3.0.100-preview6-012264 + Visual studio 2019 preview 3
2. if deploy to IIS server, create input as below code
```
<input type="text" @bind-value="@filterString" @bind-value:event="oninput" />
```
3. if try to simulate the same symptom in local machine, create input as below code, and add 150ms delay for it's oninput event.
```
<input type="text" value="@firstValue" @oninput="@OnInput1" />
code {
    string firstValue = "";
    void OnInput1(UIChangeEventArgs e)
    {
        System.Threading.Thread.Sleep(150);
        firstValue = e?.Value.ToString();
    }
}
```

### Expected behavior
The user input text should be smooth and without lag.

### Actual behavior, Screenshots
![sc1](https://user-images.githubusercontent.com/10459637/61511186-81868000-aa28-11e9-88ba-30ec35add300.gif)

**Comment by davidfowl** [comment]
>  Is this the limitation of deploy on server which is far away from client? If so, the only solution is to use Blazor client-side project instead?

Yes, it's pretty fundamental problem. Unfortunately we can't render faster than the speed of light 😄. Watch this for a more in-depth explanation of the pros/cons of each https://youtu.be/uW-Kk7Qpv5U?t=2857.

**Comment by howardgod** [comment]
As I watch one of video on NDC conference which introduce the Blazor, the lecture said if you are using enterprise network, then you could use Blazor server-side because Enterprise network can overcome the latency. I guess because my enterprise network across global, it didn't fit to this assumption.

**Comment by benaadams** [comment]
Do you need to modify the user input on each keystroke? That's bringing latency to the forefront. (example Google or Bing search round trips to the server while you are typing, however it doesn't modify the data input field based on the keystrokes but changes the list below what you are typing)

Could you have a server nearer the users location?

If you do need to interact immediately with user input; you could interop with JS just for that bit?

**Comment by howardgod** [comment]
I incline to have the user input immediately along with every keystroke for better user experience. If I understand you correctly, I can invoke JS interop only for altering user input part?

**Comment by mkArtakMSFT** [comment]
We've made some changes in this area and improved it. That said, the latency is expected when you have over-the network interactions. So there is nothing else we can do here.

**Comment by chrdlx** [comment]
@howardgod 

Man, you don't need that `firstValue = e?.Value.ToString();` line if you only wanna read the user input....  of course if you overwrite the textbox with what comes from the server at each keystroke, that's gonna make your typing a mess...
