### ISSUE TITLE
asp.net core + blazor + visual studio code + build error

### ISSUE THREAD

**Issue by Dharmrajj** [aspnet/AspNetCore#12345]
Hi,
I can see the future, it would be the new era of web development by this amazing feature and invention of Blazor. Its really nice and i am sure most of i.t. proffessionals will move to use Blazor for making SPA.

Also please solve my prob,
Using: visual studio code + latest C# extension. 
OS: windows 10 - 64bit
i have made .net core app wit blazor, this throws error while i build the app [appname: CodeCoreBlazor]:
Error:

C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Microsoft.Common.CurrentVersion.targets(4552,5): error MSB3027: Could not copy "D:\TestProjects\New folder\CodeCoreBlazor\obj\Debug\netcoreapp3.0\CodeCoreBlazor.exe" to "bin\Debug\netcoreapp3.0\CodeCoreBlazor.exe". Exceeded retry count
of 10. Failed. [D:\TestProjects\New folder\CodeCoreBlazor\CodeCoreBlazor.csproj]

C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Microsoft.Common.CurrentVersion.targets(4552,5): error MSB3021: Unable to copy file "D:\TestProjects\New folder\CodeCoreBlazor\obj\Debug\netcoreapp3.0\CodeCoreBlazor.exe" to "bin\Debug\netcoreapp3.0\CodeCoreBlazor.exe". The process cannot access the file 'D:\TestProjects\New folder\CodeCoreBlazor\bin\Debug\netcoreapp3.0\CodeCoreBlazor.exe' because it is being used by another process. [D:\TestProjects\New folder\CodeCoreBlazor\CodeCoreBlazor.csproj]

The build failed. Fix the build errors and run again.

Please solve my prob, i have done much r&d on internet, not getting the solution. Thanks.

**Comment by jdvoges** [comment]
It looks like there is a lock on the file. Have you tried restarting Visual studio code? Failing that restarting your computer

**Comment by Dharmrajj** [comment]
Yes, i have tried restarting the vs code, it works whenever i restart the vs code, but again and again error occurs when i ctrl + shift + build the app.
So is it only solution that i have to restart vs code everytime when i build the app???

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Dharmrajj.
It seems like you end up in a situation where you app is running when you're trying to run the build again.Can you please share a a short video showcasing your scenario from the beginning.

**Comment by Dharmrajj** [comment]
Thanks @jdvoges, @mkArtakMSFT  for replying,

 Yes definitely i will try to upload a short video, as well i am describing here a whole scenario here.

 I open up my blazor app in vs code, then run the command 'dotnet run', it works fine, app runs nicely on browser. 

 After that i want to build the app, so just ctrl+shift+build the app, but in terminal it shows these two build error, and yes the app still running in the browser, but it doesnt show any html changes i made on page.

  So it means that build is Unsucceded, so i choose to restart the vs code, then after run command dotnet run, it works again fine and run the app in browser, but when i tried to build an app which again throws these two build error which i mention above.
Thanks
