### ISSUE TITLE
Scaffolder issue in razor client

### ISSUE THREAD

**Issue by urskiran** [aspnet/AspNetCore#12358]
Getting error "There are no scaffolders supported for this item."

### To Reproduce
1. Using this version of ASP.NET Core '16.2.0' Preview 4.0
2. while trying to 'add razor page' by using context menu on Pages folder I am getting above mentioned error.
3. Which is not getting in another machine which is older version of this.

If I am going to add this by using new item I am getting another errors.
### Expected behavior
Able to add razor page by using context menu 

### Screenshots
![scaffolders-issue](https://user-images.githubusercontent.com/53088980/61542649-9fbba280-aa5f-11e9-8ec6-97ff33bfb873.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @urskiran.
@vijayrkn is this a known issue? Is it being tracked somewhere else?

@urskiran this is a tooling issue. Please use VS Feedback to report this, and the right people will look into it.
