### ISSUE TITLE
3PN link with templates is wrong

### ISSUE THREAD

**Issue by richlander** [aspnet/AspNetCore#12369]
Here is my experience:

```console
Richs-MacBook-Pro:~ rich$ dotnet --version
3.0.100-preview7-012821
Richs-MacBook-Pro:~ rich$ dotnet new webapp -o webapp
Getting ready...
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.

Processing post-creation actions...
Running 'dotnet restore' on webapp/webapp.csproj...
  Restore completed in 53.99 ms for /Users/rich/webapp/webapp.csproj.

Restore succeeded.
```

The 3PN link: https://aka.ms/aspnetcore-template-3pn-210

The link seems to be 2.1 specific. This is where it goes to:

<img width="814" alt="Screen Shot 2019-07-19 at 10 09 56 AM" src="https://user-images.githubusercontent.com/2608468/61552705-678b7400-aa0d-11e9-82fd-322a1afc692c.png">

Ouch. I would rather see a non version-specific link and for it to go to a place that lists TPNs for all of our templates. If folks agree with this, then this repo is probably the wrong one, but I’m starting here, since it is an ASP.NET template at issue.

**Comment by mkArtakMSFT** [comment]
Thanks @richlander.
I'll see whether I can fit this in preview 8.

**Comment by mkArtakMSFT** [comment]
@richlander, thinking about your suggestion more
>  I would rather see a non version-specific link and for it to go to a place that lists TPNs for all of our templates.

I feel like that'll be work for a scenario, which has no real functional impact. Who, at all, is actually looking into these? I think we'll be spending time doing this for not a good reason. So for now I'm simply updating the link to be 3.0 specific.
@danroth27 this is your decision really, so if you'd like us to change this and stick with more user-friendly approach, we can come back to this again.
