### ISSUE TITLE
Why does asp-apiauth-parameters exist? What purpose does it serve?

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/AspNetCore#12370]
Definition: https://github.com/aspnet/AspNetCore/blob/master/src/Identity/ApiAuthorization.IdentityServer/src/TagHelpers/ClientParametersTagHelper.cs

Usage: https://github.com/aspnet/AspNetCore/blob/master/src/Identity/ApiAuthorization.IdentityServer/samples/ApiAuthSample/Pages/Index.cshtml#L23

What benefit does setting the `data-*` tags on the `<script` tag do for us?

The only thing I can possibly come up with is that this makes search engine indexers not able to snag the client id?

**Comment by blowdart** [comment]
Using data parameters on tags is a safer way to pass things to javascript than just writing them into a script tag. If we stick with data parameters we can use a single encoder, if we try to write out javascript we can end up with multiple encoders, where the order of encoding matters, and it's easy to get wrong, so as a matter of course we take the safer approach.

**Comment by VictorioBerra** [comment]
Encoding in this context meaning this line? https://github.com/aspnet/AspNetCore/blob/master/src/Identity/ApiAuthorization.IdentityServer/src/TagHelpers/ClientParametersTagHelper.cs#L51

**Comment by blowdart** [comment]
No encoding as in the way all tag helpers will encode their output.

It has nothing to do with search engines, and all to do with preventing XSS. Now while the client IDs etc are controlled by the developer and arguably we could do down another route this is the standard route we use for passing data into scripts, and the overhead of doing it a different way in a single case, and having to review that for security isn't worth the effort.

Is it causing you a problem in any way?

**Comment by VictorioBerra** [comment]
No I was purely curious, I was very confused when I saw this method and it seemed like it was mixing too many technologies for a simple problem.

Now that I see that its a standard way of doing thing you guys adopted, I can see it makes a lot more sense.

I am mainly reading the codebase for ApiAuthorization.IdentityServer to understand what you guys have built and what its relationship to IdentityServer is to prepare for the Core 3 release.

I hope you guys have some thorough docs for this stuff during the release, for example I am trying to understand the `ApplicationProfile` stuff right now.
