### ISSUE TITLE
SignalR Errors when some Chrome Extensions Enabled

### ISSUE THREAD

**Issue by zanate4019** [aspnet/AspNetCore#12378]
### Describe the bug
We have an application that is nearing completion and is the final user acceptance phase.  We've noticed that on some of our testers systems SignalR has connection errors.  On both machines, reseting Chrome to default corrected the issue, but we're concerned that when the application moves to production this will be a support issue.  On one of the systems we were able to consistently track the issue to this extension https://chrome.google.com/webstore/detail/auto-refresh/ifooldnmmcmlbdennkpdnlnbgbmfalko.  The other system that was having the issue never had that extension installed. 

### To Reproduce
1. Using this version of ASP.NET Core '2.2.6'
2. Run this code  
   2a. on server
```
            app.UseSignalR(routes => routes.MapHub<ExamHub>(srConfig.ExamHubUrl, o =>
            {
                o.ApplicationMaxBufferSize = 0;
                o.TransportMaxBufferSize = 0;
            }));
```
  2b. on client
```
  private _initiateHubConnection = (): void => {
    this._debugService.logDebug(this, ["Exam Hub Connection Initializing"], null, true, "_initiateHubConnection");
    // create connection to  signalR
    let builder = new HubConnectionBuilder();
    //if(navigator.userAgent.indexOf("Chrome") !== -1 )
    //  this.hubConnection = builder
    //    .withUrl(this._bwf.examUpdateUrl, {
    //      transport: signalR.HttpTransportType.ServerSentEvents,
    //    })
    //    .configureLogging(this._signalrLogger)
    //    // .withHubProtocol(new JsonHubProtocol())
    //    //.withHubProtocol(new MessagePackHubProtocol())
    //    .build();
    //else
      this.hubConnection = builder
        .withUrl(this._bwf.examUpdateUrl)
        // .configureLogging(this._signalrLogger)
        // .withHubProtocol(new JsonHubProtocol())
        //.withHubProtocol(new MessagePackHubProtocol())
        .build();

    // handle communication from signalR
    this.hubConnection.on("AddExams", async(notification: INotificationViewModel) => await this._onNotificationAddExams(notification));
    this.hubConnection.on("UpdateExams", async(notification: INotificationViewModel) => await this._onNotificationUpdateExams(notification));
    this.hubConnection.onclose((err) => {
      this.state = DataServiceState.disconnected;
      if (err) {
        this._debugService.logWarning(this, [err, 'Connection Restarting'], 'Error in Exams Connection',true,"_initiateHubConnection");
        toastr.warning(`Error in Exam Update Connection: ${err}`, "Error in Exam Update Connection",true,"_initiateHubConnection");
      }
      this.state = DataServiceState.connecting;
      this.hubConnection.start().then(() => this._onHubConnectionStart());
    });

    // start the connection
    this.hubConnection.start().then(() => this._onHubConnectionStart());

    this._debugService.logSuccess(this, ["Exam Hub Connection Initialized"], null, true, "_initiateHubConnection");
  };
```
4. Errors in client

### Expected behavior
Would like the the signalr connections to stay up reliably

### Additional context
I know this is light on information.  I'm really just looking for general guidelines to prevent extensions from causing issues.

**Comment by BrennanConroy** [comment]
> I'm really just looking for general guidelines to prevent extensions from causing issues.

This is the first time I'm hearing of an issue with extensions, so we wont really have any guidelines...

The extension you linked automatically refreshes the tab, so I hope the issue you're seeing isn't that the connection is closed and opened when the page refreshes, as that would be 100% expected behavior.

**Comment by anurse** [comment]
We'd need to see specific information about the errors you're getting on the client to know more. I'd suggest following our [logging and diagnostics guide](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2) to gather client logs and a network trace during the issue.

As @BrennanConroy said, this is the first we've heard of extensions causing problems.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
