### ISSUE TITLE
Blazor Feature Request: Support for Pipes formatters

### ISSUE THREAD

**Issue by punjabier** [aspnet/AspNetCore#12389]
It will be good if there is Pipes feature as in Angular

`<p>The hero's birthday is {{ birthday | date }}</p>`

This feature will also be beneficial in Globalization/ Localisation
#9386  Globalisation and Converters
`@bind-globalization` is specific to input element. It will not go too far with other elements like (eg.)div 
```
<input type="text" @bind="coolnessLevel" @bind:culture="CultureInfo.InvariantCulture">
  Rate the coolness of Blazor (in a non-locale-specific way)
</input>
```

Other Pros of Pipes syntax

- Chainable
- Will work anywhere 
    `@value | date: 'MMM dd, yyyy' | uppercase`
     `@value | culture:'en-us'`
      `@value | converter:'default'`
List goes on ...

**Comment by RemiBou** [comment]
There is already method and extension method in C#. What would be the added value of another syntax ?

```c#
@value.ToString("MMM dd, yyyy", CultureInfo.InvariantCulture).ToUpper()
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
