### ISSUE TITLE
[Templating] Auth for SPA templates remaining work

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#12392]
- [x] Update Identity Server oidc-client to a released version.
- [x] Use the new simpler APIs if possible.
- [x] Update the identity server versions.
- [x] Explicitly reference ASP.NET Core Identity Server dependencies outside of the shared framework in the templates.

**Comment by mkArtakMSFT** [comment]
The only thing left here, @javiercn, is to reference the final IS4 package when it's released post Preview 9, correct?

**Comment by javiercn** [comment]
Yes, there's one thing that I didn't pursue, but it's an enchantment, so yeah. Updating IS4 and oidc-client to their final versions is the last thing to do.
