### ISSUE TITLE
Xamarin and Blazor

### ISSUE THREAD

**Issue by genifycom** [aspnet/AspNetCore#12399]
### Is your feature request related to a problem? Please describe.
It is not productive to have both Xamarin UI and Blazor UI. Will they be combined?

### Describe the solution you'd like
Moving an app from Desktop to Mobile device is not helped by Blazor, but it should be.

### Additional context
Xamarin UI is a holdover from a failed UI system. Instead of continuing it, move the Xamarin UI to Blazor (server side especially) so that we can move more freely across devices.

**Comment by mkArtakMSFT** [comment]
@danroth27 this is all yours!

**Comment by danroth27** [comment]
Hi @genifycom. Thanks for this feedback! We've had some discussions with the Xamarin folks about the possibility of building mobile apps with Xamarin + Blazor. We don't have anything concrete planned yet, but we'll let you know once we do!
