### ISSUE TITLE
MatTable page size not working

### ISSUE THREAD

**Issue by novfal** [aspnet/AspNetCore#12429]
<MatTable Items="project"  PageSize="12">

Page size = 12 mentioned but in the defaultly 5 only displaying

**Comment by mkArtakMSFT** [comment]
We're closing this issue as there is no enough details provided.
If this is a valid issue with ASP.NET Core, please reopen and provide details about your scenario, what you're trying to do, and how and what's going wrong. If this is a bug report, please attach a small repro project, so we can investigate this further.
