### ISSUE TITLE
Blazor (Client-Side) Template is missing in visual studio

### ISSUE THREAD

**Issue by ppatel514** [aspnet/AspNetCore#12427]
Blazor (Client-Side) Template is missing in visual studio even after following steps 1,2 & 3 on link below.

https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

However, I am able to create new Blazor (Client-Side) project using .Net Core CLI.

Please let me know if any additional details are needed. Any help much appreciated.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ppatel514.
You most probably got some error during your setup, which may have been somewhat silent and you didn't notice it. Leaving this here for you to provide more details and the community members may be able to help you out with identifying it.

**Comment by LarryWMSN** [comment]
I have the same issue on 2 computers with preview 7 of the sdk with the current vs2019 preview and after installing the templates. The template install said:  Restore completed in 1.14 sec for C:\Users\xxx\.templateengine\dotnetcli\v3.0.100-preview7-012821\scratch\restore.csproj. The client side project (Web Assembly App) does not show in the project list for asp.net core web application but dotnet new blazor will create a project that runs with no errors.

**Comment by isaac2004** [comment]
@mkArtakMSFT is there a log file they can provide from when they install the blazor extension/templates

**Comment by LarryWMSN** [comment]
Is there any update? Also I noticed that .UseWindowsService() isn't available as an extension method in the Worker Template in the CreateHostBuilder method, perhaps these may be related?

**Comment by mkArtakMSFT** [comment]
Folks, please make sure you uninstall the Blazor Extension and reinstall the latest templates.

**Comment by LarryWMSN** [comment]
As far as I remember I had uninstalled the extension on both machines. I also tried to find any remnant of the install but couldn't locate any. However; it is working properly after installing the VS 2019 16.3.0 Preview 1.0 on both machines.

**Comment by mkArtakMSFT** [comment]
Glad that you've got it working. Closing as there seems to be no action pending from our end here.

**Comment by AqlaSolutions** [comment]
Same issue for me

**Comment by RehmakNatiq** [comment]
Blazor (Client-Side) Template is missing in visual studio 2019 Preview 4
How can is add Blazor client side project Template ?

**Comment by LarryWMSN** [comment]
> Blazor (Client-Side) Template is missing in visual studio 2019 Preview 4
> How can is add Blazor client side project Template ?

It's no longer a template under the ASP.NET Core Web Application project. It has its' own top level project type. Just search for Blazor.
