### ISSUE TITLE
Blazor server side component input Url Parameter not converting from Base 64

### ISSUE THREAD

**Issue by mg1357** [aspnet/AspNetCore#12434]
I use Blazor Server Side Preview 6,

I had problems with Identity ConfirmEmailAsync and always it returns Invalid Token. So I write a custom TokenProvider. at one side I have this Code:

```
`//string confirmationToken = await userManager.GenerateEmailConfirmationTokenAsync(user);
string confirmationToken = await tokenProvider.GenerateAsyncEmail("mzpurposes", userManager, user);

string confirmationLink =
            $"{httpContext.HttpContext.Request.Scheme}://{httpContext.HttpContext.Request.Host}" +
            $"/account/confirmemail/{System.Web.HttpUtility.UrlEncode(user.Id)}" +
            $"/{System.Web.HttpUtility.UrlEncode(confirmationToken)}";`
```
and at the other side in the ConfirmEmail page that Recieves UserID and Token as input Route parameters:

```
//IdentityResult result = await userManager.ConfirmEmailAsync(user, System.Web.HttpUtility.UrlDecode(Token));
    bool result =
        await tokenProvider.ValidateAsyncEmail("mzpurposes", System.Web.HttpUtility.UrlDecode(Token), userManager, user);
    if (result)   //.Succeeded)
    {
        Model = new UserConfirmModel() { Success = true };
    }
    else
    {
        Model = new UserConfirmModel() { Success = false };
    }

```
In the custom TokenProvider at the end of the method that creates the token I have:

```
var protectedBytes = protector.Protect(ms.ToArray());
        return Convert.ToBase64String(protectedBytes);

```
and at the begining of Validate Method there is:

`
var unprotectedData = protector.Unprotect(Convert.FromBase64String(token));
`

every time I click the confirmation link and code reaches to this line I get this error:

**The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."}**

Why do I recieve this error when I convert the bytes at the end of the method GenerateAsyncEmail to base64string? also in the startup class I have: services.AddDataProtection(); and I inject it to tokenprovider class.

When I validate the user in the same page of Register the validation succeeds but when I navigate to ConfirmEmail page the token is Invalid and I get the above bolded error.
`
@page "/account/confirmemail/{UserId}/{Token}"`

I am Sure this is a bug in Blazor Serverside Component's input parameters.

EDIT: If in the ConfirmEmail page I remove System.Web.HttpUtility.UrlDecode(Token) and directly use input parameter Token without decoding, There is a small chance that validation succeed, but must of the time I get the bolded error above.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by mg1357** [comment]
You didn't bother reading the Issue carefully, Maybe this is a bug in your system.

**Comment by mg1357** [comment]
OK, I created a test page and sent a base64 string as a parameter to another page and compared it with a property that I set in a singleton service, It seems that everything works fine, But I don't know why I get the error, because the Input parameter is definitely a base64 string but the unprotect mehod says that it is not.

**Comment by mg1357** [comment]
I reversed the order of parameters from:

`@page "/account/confirmemail/{UserId}/{Token}"`

to

`@page "/account/confirmemail/{Token}/{UserId}"`

and now the Token converts from Base64 string.
