### ISSUE TITLE
Question: How to use sessions correctly in Blazor?

### ISSUE THREAD

**Issue by SeppPenner** [aspnet/AspNetCore#12432]
### Question
How can I use sessions in Blazor correctly? The answers I found:

* Use a scoped service: I don't think that this is the correct way to go, described here: https://stackoverflow.com/questions/53913396/how-to-store-session-data-in-server-side-blazor
* Use `cloudcrate/BlazorStorage` from https://github.com/cloudcrate/BlazorStorage (@SteveSandersonMS did this on the NDC 2018, check https://www.youtube.com/watch?v=JU-6pAxqAa4&feature=youtu.be&t=2875). However, I don't want to do this on the client side...
* Use `HttpContext.Session` from `Microsoft.AspNetCore.Http` as described here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.0. There, I fell over https://github.com/aspnet/AspNetCore.Docs/issues/13328, where it's requested to `update app session and app state to 3.0`.

My question now: What's the way to go with Blazor?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SeppPenner .
We don't have a blazor-native way for interacting with Session.
@anurse does SignalR provide any guidance regarding using sessions?

**Comment by anurse** [comment]
No, we don't have specific guidance. The `HttpContext.Session` object is certainly not guaranteed to work properly.

**Comment by SeppPenner** [comment]
> The HttpContext.Session object is certainly not guaranteed to work properly.

I already experienced that 😄

**Comment by guardrex** [comment]
This isn't directly related to your, @SeppPenner, question here, but I just wanted to note that we just published Steve's state persistence doc at https://docs.microsoft.com/aspnet/core/blazor/state-management?view=aspnetcore-3.0 today. It won't help you with session, but it does clarify the current guidance on state persistence. If engineering rolls out new state persistence scenarios, we/they will cover the new bits in that topic going forward.

**Comment by mv10-work** [comment]
Related: https://github.com/aspnet/AspNetCore/issues/5330

**Comment by javiercn** [comment]
https://docs.microsoft.com/aspnet/core/blazor/state-management?view=aspnetcore-3.0 is definitely the way to go for Blazor. 

As @anurse mentions there's no guarantee that the HttpContext.Session is available in SignalR (and hence neither in Blazor).
