### ISSUE TITLE
Blazor Preview 6 Client - System.Convert.FromBase64String

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#12438]
### Describe the bug
`System.Convert.FromBase64String` throws an exception when running on blazor client with a seemingly valid base64 string. I have validated the base64 string shown below over here: https://base64.guru/tools/validator

`System.Convert.FromBase64String` works for other base 64 strings that I have tested with, so something must be special about this particular one. Have included simple repro below.

### To Reproduce
Create a blazor preview 6 client side app, and run the following code:

```
            var base64TestString = "eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZm9vQGJhci5jb20iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IkVQQ0Y0RjZYV1JWVFZSVUZaM1dCR1VSV0s1QllOQTJYIiwianRpIjoiM2VhYjY2OTQtOWE2YS00YTgyLWFkMWEtODFkYjkxOWFhN2EwIiwiaWF0IjoxNTYzNzk4Nzk5LCJuYmYiOjE1NjM3OTg3OTksImV4cCI6MTU2MzgwMjM5OSwiaXNzIjoiUGxhdGZvcm0iLCJhdWQiOiIqIn0";

            Console.WriteLine("decoding test string: " + base64TestString);
            var testDecoded = System.Convert.FromBase64String(base64TestString);
            Console.WriteLine("test passed");

```

Output:

> WASM: decoding test string: eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZm9vQGJhci5jb20iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IkVQQ0Y0RjZYV1JWVFZSVUZaM1dCR1VSV0s1QllOQTJYIiwianRpIjoiM2VhYjY2OTQtOWE2YS00YTgyLWFkMWEtODFkYjkxOWFhN2EwIiwiaWF0IjoxNTYzNzk4Nzk5LCJuYmYiOjE1NjM3OTg3OTksImV4cCI6MTU2MzgwMjM5OSwiaXNzIjoiUGxhdGZvcm0iLCJhdWQiOiIqIn0
blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Convert.FromBase64CharPtr (System.Char* inputPtr, System.Int32 inputLength) <0x27cb578 + 0x000c8> in <a9086d2bd3664bb38d4f53d3177d1caf>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Convert.FromBase64String (System.String s) <0x27cb380 + 0x00048> in <a9086d2bd3664bb38d4f53d3177d1caf>:0 

### Expected behavior
I would expect to be able to decode this base 64 string.

### Additional context
preview 6, running blazor in the browser (client side, not server side)

**Comment by campersau** [comment]
Looks like .NET requires a padding sign (`=`) at the end for this string so it has a proper length.

Demo: https://dotnetfiddle.net/AqzFtn
Info: https://stackoverflow.com/a/6916831

**Comment by dazinator** [comment]
@campersau thanks for this, I was just fiddling around along those lines - it looks like you are correct sir.

For the full info behind this, I'm returning a JWT token from asp.net core, to my blazor client app - and its generated like so:

```
var jwt = new JwtSecurityTokenHandler().WriteToken(token);
```

The format of a JWT token is actually 3 base 64 encoded strings concatenated together, using a "." as the seperator: i.e [header].[claims].[signature]

In my case, on the blazor client side, I split that string by "." and get the "claims" section - this a base64 encoded string that represents the JWT claims.
It's this string I am trying to use `System.Convert.FromBase64String` with - and suffers from the padding issues. If I add in padding on that string then I can convert it correctly.

Here is the working method to get claims from a jwt token (Note this was only by chance happening to work for me for a while without the padding code, just because by jwt's that i was using happened to work out at he correct number of characters to not need additional padding characters, as soon as another user tried logging in, it blew up!)



```
            string[] jwtEncodedSegments = jwt.Split('.');
            var payloadSegment = jwtEncodedSegments[1].Trim();

            Console.WriteLine("encoded jwt segment: " + payloadSegment);           
            payloadSegment = payloadSegment.PadRight(payloadSegment.Length + (4 - payloadSegment.Length % 4) % 4, '=');         

            var decodePayload = System.Convert.FromBase64String(payloadSegment);         
            var decodedUtf8Payload = Encoding.UTF8.GetString(decodePayload);       

            var result = System.Text.Json.Serialization.JsonSerializer.Parse<Dictionary<string, JsonElement>>(decodedUtf8Payload);

            Claim[] claims = ToClaims(result);
```

Perhaps this will help somebody else.

I'll close this because it's apparantly well known that .NET base 64 decoding requires an input string length that is divisible by 4 (and thus padded) - and I guess it's not desirable to pad each JWT segment because that inflates its size, so this is just an unhappy meeting of the two.
