### ISSUE TITLE
Credentials and impersonalize

### ISSUE THREAD

**Issue by asleeguilez** [aspnet/AspNetCore#12443]
Hi.
I have problems assigning the Suppressed credentials.

`

                WindowsIdentity identity = (WindowsIdentity)HttpContext.User.Identity;
                WindowsIdentity.RunImpersonated(identity.AccessToken, () =>
                {

                    Uri uri = new Uri(@"\\SVWSIOPRDAPP01\colibri$\Agente\AgenteColibri.config");
                    FileWebRequest fw = (FileWebRequest)FileWebRequest.Create(uri);
                    fw.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;
                    FileWebResponse fr = (FileWebResponse)fw.GetResponse();
                    Stream reader = fr.GetResponseStream();
                });`

they can guide me

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please provide more details about your scenario, what you're trying to do and what's you're having trouble with.

**Comment by asleeguilez** [comment]
A netcore WebApi. with integrated authentication. What other information do you need?

**Comment by asleeguilez** [comment]
![Sin título](https://user-images.githubusercontent.com/36541371/61650189-84cc7680-ac89-11e9-968e-8299eef096af.png)

**Comment by asleeguilez** [comment]
![Sin título](https://user-images.githubusercontent.com/36541371/61650312-c9f0a880-ac89-11e9-82a7-433caae869a0.png)

**Comment by mkArtakMSFT** [comment]
@shirhatti is this something you can provide guidance on?

**Comment by blowdart** [comment]
What trouble are you actually seeing? Are you getting errors?
Why are you attempting to use a webrequest to write to a UNC share?

**Comment by asleeguilez** [comment]
It is a system with windows authentication and I want to modify a file that is in a share that only certain users have access to.
That's why I need to log in with the credentials of the logged in user.
but these credentials go blank.

**Comment by asleeguilez** [comment]
For example, when I execute this command outside the impersonation it creates a file where the owner is usrdelegadesa.
`FileStream fileStream = new FileStream(@"\\PC161835\colibri$\Agente\file.xml", FileMode.Create);`

but when I run it inside the impersonalization I don't have access.
`
                WindowsIdentity identity = (WindowsIdentity)HttpContext.User.Identity;
                WindowsIdentity.RunImpersonated(identity.AccessToken, () =>
                {
                    FileStream fileStream = new FileStream(@"\\PC161835\colibri$\Agente\file.xml", FileMode.Create);
                });`
and what I want is to take the credentials of the user loguedo to execute this command
