### ISSUE TITLE
Port remaining components to "Microsoft.Data.SqlClient"

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#12445]
* `dotnet-sql-cache` tool
* ~~`SqlConnectionHealthCheck` (cc @rynowak)~~ Not a shipping thing, a sample. Never mind.

cc @ajcvickers @divega

**Comment by Pilchie** [comment]
Assigning since you're looking at this already.

**Comment by anurse** [comment]
Merged #12447 to update to the latest. Leaving this open because we need to update to the RTM build when it's available.

**Comment by anurse** [comment]
#12957 is tracking this now.
