### ISSUE TITLE
@bind:event not honoured for type="range"

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#12448]
Clone: https://github.com/JeremyLikness/SliderExample

This slider should update in realtime instead of just when you release the thumb. This is a bug in the codegen where it's ignoring the `@bind:event`.

Changing the code like the following fixes it.

```razor
<input type="range" min="0" max="99" @bind-value="value" @bind-value:event="oninput"/>
```

**Comment by ajaybhargavb** [comment]
I tried this out and can no longer reproduce with the latest sdk. I looked at the example and it used preview6 and I think we fixed bugs in this area after that.

**Comment by ajaybhargavb** [comment]
Am I missing something @rynowak?

**Comment by ajaybhargavb** [comment]
Closing as I'm unable to reproduce this on latest bits.
