### ISSUE TITLE
Script innertext is mangled when type="text/html"

### ISSUE THREAD

**Issue by Buildstarted** [aspnet/AspNetCore#12455]
### Describe the bug
When having a script tag with the attribute `type="text/html"` the parser breaks whatever is contained within when `<%` and `==` can be found

### To Reproduce
1. Using this version of ASP.NET Core 3.0.100-preview6-012264
2. Run this code inside any .cshtml file

```
<script type="text/html">
    <%var x = window == null;%>
</script>
```

3. With these arguments: none necessary
4. Result:
```
<script type="text/html">
    <%var x = window =>
</script>
```

### Expected behavior
Expected behavior is for the value within the script tag to not be altered.

**Comment by davidfowl** [comment]
@Buildstarted! Where have you been!?

**Comment by Buildstarted** [comment]
I've been on the jabbr slack. I tried to connect to the asp slack a few times but always got errors so I gave up.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb can you please look into this?
