### ISSUE TITLE
Adding system.drawing.common to a Blazor app causes the linker to fail.

### ISSUE THREAD

**Issue by PhilPJL** [aspnet/AspNetCore#12457]
### Description
Adding system.drawing.common to a Blazor app causes the linker to fail.
system.drawing.common is advertised as supporting .NET Standard 2 with no other dependencies.  system.drawing.common is a dependency of other Nuget packages such as ClosedXml which then have the same linker error.

### To Reproduce
Dotnet core 3.0.100-preview6-012264
Visual Studio 16.2.0 Preview 4.0
Create new ASP.NET Core Web Application - specify 'Blazor WebAssembly App'.
Build succeeds.

Add Nuget package system.drawing.common.  Build now results in this error message: 
[linker_error.txt](https://github.com/aspnet/AspNetCore/files/3419398/linker_error.txt)

Demo app: [WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3419400/WebApplication1.zip)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not an area we control.
If you still have this problem, feel free to report it on the https://github.com/mono/mono repo.

**Comment by PhilPJL** [comment]
@mkArtakMSFT, @SteveSandersonMS 
I'm not sure it's my job to chase disparate teams regarding an issue with Visual Studio and Blazor integration.  If you don't consider this issue important then so be it.  I guess I'll wait for Blazor 3.1 and try again.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#15806
