### ISSUE TITLE
Adding a Blazor UserSpecifiedDisplay within a other file than _Host.cshtml does not work

### ISSUE THREAD

**Issue by erwindevreugd** [aspnet/AspNetCore#12462]
### Describe the bug
When adding a Blazor UserSpecifiedDisplay to _Host.cshtml everything works as expected. When adding the UserSpecifiedDisplay into a Blazor component and adding that component into the App.razor file, the resulting HTML is added to the DOM but the element classes are no longer being added when the connection state changes.
(Adding the Blazor component to *_Host.cshtml* does not render the component)

DisconnectedDialog Component:

```html
<div id="components-reconnect-modal" class="components-reconnect">
    <div class="container">
        <div class="reconnect-wait">
            <span class="message">Connection lost -- please wait, attempting to reconnect</span>
        </div>
        <div class="reconnect-button">
            <span class="message">Unable to reconnect</span>
            <br />
            <a href="javascript: void(0);" onclick="Reconnect()" class="btn">
                <i class="fa fa-sync-alt"></i><span>Reconnect</span>
            </a>
        </div>
    </div>
</div>
```

App.razor:

```html
<CascadingAuthenticationState>
    <DisconnectedDialog></DisconnectedDialog>
    <Router AppAssembly="typeof(Startup).Assembly">
        <NotFoundContent>
            <p>Sorry, there's nothing at this address.</p>
        </NotFoundContent>
    </Router>
</CascadingAuthenticationState>
```

Using the browser console to add or remove the required classes does work

```javascript
document.getElementById('components-reconnect-modal').classList.add('components-reconnect-show')
document.getElementById('components-reconnect-modal').classList.remove('components-reconnect-show')
```

With the default ReconnectionDisplay the following works

```javascript
window['Blazor'].circuitHandlers[0].reconnectDisplay.failed()
```

When using a UserSpecifiedDisplay the following does not work

```javascript
window['Blazor'].circuitHandlers[0].reconnectDisplay.failed()
```

### To Reproduce
1. Using Server-side Blazor create a Blazor Component *DisconnectedDialog.razor*
2. Add the default html and css styles as given on the Blazor docs
3. Add the *DisconnectedDialog* component to *App.razor*
4. Interupt the server connection

### Expected behavior
Updating the element with id *components-reconnect-modal* should work anywhere in the DOM

### Additional information
When using the Firefox 'DOM' viewer, ```Blazor.circuitHandlers[0].reconnectDisplay.dialog``` is being updated with the correct classes however the 'Inspector' does not show the same classes.

### Additional context
Microsoft.NETCore.App 3.0.0-preview6-27804-01
Tested on Chrome and Firefox

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @erwindevreugd.
The reconnection UI is applicable on the top page only, and not on component level. What you're trying to do is not a supported scenario.
