### ISSUE TITLE
value=@model.foo is not initialized correctly

### ISSUE THREAD

**Issue by Trolldemorted** [aspnet/AspNetCore#12468]
### Describe the bug
I have a set of objects which can be updated either by user interaction and a signalr handler. Since we cannot have onchange and bind at the same time, I resorted to using `value=@model.foo` as a workaround. Event handling works fine, but the initial value is not set correctly.

### To Reproduce
Take this blazor page:
```razor
@page "/"
<div>
    @foreach (var cat in Cats) {
        <input type="checkbox" value=@cat.Marked @onclick="@( () => HandleCatboxClick(cat) )" />
        @cat.Name
    }
</div>

@functions {
    public class Cat
    {
        public string Name { get; set; }
        public bool Marked { get; set; }
    }
    public List<Cat> Cats = new List<Cat>()
    {
        new Cat() { Name = "Bob", Marked = false },
        new Cat() { Name = "Mrs. Norris", Marked = true}
    };

    public void HandleCatboxClick(Cat cat)
    {
        cat.Marked = !cat.Marked;
        Console.WriteLine($"{cat.Name} was clicked, new value is {cat.Marked}");
    }
}
```
When the page loads, both checkboxes are unchecked. Checking Mrs. Norris' checkbox prints
>WASM: Mrs. Norris was clicked, new value is False

and unchecking it prints
>WASM: Mrs. Norris was clicked, new value is True

Bob's box behaves as expected, I guess because false is the default state of the checkbox.

### Expected behavior
One expects that Mrs. Norris' checkbox is initially checked, and its state is bound to the model's value, not the inverted value.

**Comment by campersau** [comment]
For boolean values and checkboxes use the `checked` attribute instead of `value` or use the [`InputCheckbox`](https://github.com/aspnet/AspNetCore/blob/8f87e482513ecf363d9d3cffec14b6200a939c27/src/Components/Web/src/Forms/InputCheckbox.cs) component.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by Trolldemorted** [comment]
This is still a bug, isn't it? There is a workaround, but to me this is not expected behaviour.

**Comment by SteveSandersonMS** [comment]
It's not a bug. The HTML attribute for the value of a checkbox is `checked`, so that's what you use to set the value on a checkbox element. Or did you mean something else was a bug?

> Since we cannot have onchange and bind at the same time

*That* is a bug, or at least a feature we haven't implemented yet. Is that what you meant?

**Comment by Trolldemorted** [comment]
Ah now I got it - I thought checked was a secondary thingy and value should work too. Sorry for bothering you! :)
