### ISSUE TITLE
IServiceCollection.ConfigureApiBehaviorOptions overload for IServiceProvider

### ISSUE THREAD

**Issue by JoshKeegan** [aspnet/AspNetCore#12470]
### Is your feature request related to a problem? Please describe.
I am trying to use `IServiceCollection.ConfigureApiBehaviorOptions` to set an `InvalidModelStateResponseFactory`, but my factory has a number of dependencies so I want to resolve this via dependency injection.

Currently I am having to build a service provider just for this:
```cs
IInvalidModelStateResponseFactory invalidModelStateResponseFactory =
	services.BuildServiceProvider().GetService<IInvalidModelStateResponseFactory>();

services.ConfigureApiBehaviorOptions(options =>
		options.InvalidModelStateResponseFactory = invalidModelStateResponseFactory.Create);
```

### Describe the solution you'd like
An overload of the `IServiceCollection.ConfigureApiBehaviorOptions(...)` method that can provide an `IServiceProvider` for you to get a service from, this could be used like:
```cs
services.ConfigureApiBehaviorOptions(options, provider =>
	options.InvalidModelStateResponseFactory =
		provider.GetService<IInvalidModelStateResponseFactory>.Create);
```

### Additional context
Lack of this functionality also means that you must call `ConfigureApiBehaviorOptions` after you have registered any dependencies required. Ideally the order in which dependencies are registered should not matter.

Apologies if there is already a way of solving this problem, I couldn't see one.

**Comment by serpent5** [comment]
You can already achieve this without building an `IServiceProvider`, using `AddOptions` and `Configure`:

```cs
services.AddOptions<ApiBehaviorOptions>()
    .Configure<IInvalidModelStateResponseFactory>((o, invalidModelStateResponseFactory) =>
    {
        o.InvalidModelStateResponseFactory = invalidModelStateResponseFactory.Create;
    });
```

See [Use DI services to configure options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2#use-di-services-to-configure-options) in the docs for more.

**Comment by JoshKeegan** [comment]
Fantastic, thanks! I didn't know about that :)
