### ISSUE TITLE
Net.Core webForms 

### ISSUE THREAD

**Issue by gokmenerdem** [aspnet/AspNetCore#12471]
Is there any future planning about supporting WebForms for Net. Core ?

**Comment by danroth27** [comment]
No, we have no plans to port Web Forms to .NET Core. Please see https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/ for additional details. If you're looking for a component-based web UI framework for .NET Core we would suggest looking at [Blazor](https://blazor.net). 

The [reference source](https://github.com/Microsoft/referencesource) for ASP.NET Web Forms is available though with an open source friendly license if folks in the Web Forms community are interested in taking this on as a community based project similar to what is being done for [WF](https://github.com/UiPath/corewf) and [WCF](https://github.com/CoreWCF/CoreWCF). I believe @hishamco had started work on one at one point: https://github.com/hishamco/WebForms.
