### ISSUE TITLE
ResponseCachingMiddleware is logging a warning on valid HEAD responses

### ISSUE THREAD

**Issue by skolmer** [aspnet/AspNetCore#12491]
1. Using this version of ASP.NET Core: '2.2'
2. Create a controller action with `HttpHead` attribute
3. Return content length header but no body
4. See warning `The response could not be cached for this request because the 'Content-Length' did not match the body length.`, logged by `Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware`

As described in MDN it is correct to return the Content-Length header without a body:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD
> A response to a HEAD method should not have a body. If so, it must be ignored. Even so, entity headers describing the content of the body, like Content-Length may be included in the response. They don't relate to the body of the HEAD response, which should be empty, but to the body of similar request using the GET method would have returned as a response.

Is there any good reason why `ResponseCachingMiddleware` is logging this warning on HTTP HEAD requests? https://github.com/aspnet/AspNetCore/blob/3c0fb1a3f8609aae3165d43cb61fed10d9e1bf4f/src/Middleware/ResponseCaching/src/ResponseCachingMiddleware.cs#L372

**Comment by anurse** [comment]
I don't think there's an intentional reason we are logging that warning. You are correct that it doesn't seem appropriate to log it on a HEAD request since there is intentionally no body. I think we could add an `else if` branch to this that avoids the warning if and only if `Method == HEAD && Body.Length == 0 && ContentLength != 0`, since that's the case allowed by the spec.

Thoughts @Tratcher @davidfowl ?

**Comment by alefranz** [comment]
Hi Andrew,
I had a look at this and the issue is not the warning per se.
I believe the middleware should not skip the caching in this scenario, as the response is still valid to be cached similar to a `HEAD` with no `Content-Length`.
I'm working on a PR for this right now.

Thanks,
 Alessio

**Comment by skolmer** [comment]
That was fast. Thanks @alefranz 👍

**Comment by JunTaoLuo** [comment]
Thanks @alefranz for the fix!
