### ISSUE TITLE
Consider turning off restore as part of Razor SDK tests

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#12494]
Follow up to https://github.com/aspnet/AspNetCore-Tooling/pull/867

@pranavkm suggested that the recent flakiness could be due to us turning on restore as part of these tests. We should just turn them off.

**Comment by JunTaoLuo** [comment]
Should this be in the AspNetCore-Tooling repo?

**Comment by ajaybhargavb** [comment]
We track issues for `AspNetCore-Tooling` repo here.
