### ISSUE TITLE
Angular Like Constructor Dependency Injection

### ISSUE THREAD

**Issue by sebastienlabine** [aspnet/AspNetCore#12492]
### Is your feature request related to a problem? Please describe.
I've been working with .net core for several years right now and I find it annoyingly repetitive and long to inject services. Here's why: 

In order to inject a service, you need to :

1. Register the service in Startup.cs. (which doesn't bother me)
2. Create a propriety in the class that you are injecting the service into
3. Assigning the proprety to the service

```csharp
public class Controller : ControllerBase
{
        private readonly InjectedService _injectedService;

        public Controller(InjectedService injectedService)
        {
                _injectedService = injectedService;
        }
       
        public void SomeMethod() 
        {
            _injectedService.doSomething();
        } 
}
```
### Describe the solution you'd like
From previous experience with Angular, I really loved their dependency injection that required only to inject the service as a private property in the constructor.([Angular Documentation](https://angular.io/guide/dependency-injection))

It was quicker for the programmer to do so and less painfull in projects with multiple services injected per class.

Proposed Changes:
It would be appreciated if we could inject a service like this:

```csharp
public class Controller : ControllerBase
{
        public Controller(private readonly InjectedService _injectedService)
        {
        }

        // OR with default readonly

        public Controller(private InjectedService _injectedService)
        {
        }

        public void SomeMethod() 
        {
            _injectedService.doSomething();
        } 
}
```

**Comment by outring** [comment]
It's a language feature (in your Angular case, it's a TypeScript feature), not framework. There are some similar proposals in compiler repo, like this one: https://github.com/dotnet/roslyn/issues/14853
But if you're planning on adding a new proposition, note that it must be posted to language repo itself: https://github.com/dotnet/csharplang

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sebastienlabine.
This is not something we have control over so we're closing this issue.
