### ISSUE TITLE
Stream's method EnableRewind in preview7.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [aspnet/AspNetCore#12508]
NetCore Preview7 not have stream.EnableRewind() method, Have any replacement method?

**Comment by mkArtakMSFT** [comment]
Potentially related: https://github.com/aspnet/AspNetCore/issues/12505

**Comment by anurse** [comment]
`EnableRewind` has been made `internal` (it was always in an `Internal` namespace or "pubternal" as we've called it, which means it is not supported).

In 2.x we added native support for buffering via `HttpContext.Request.EnableBuffering`. It works exactly the same (it just calls the now-internal API).
