### ISSUE TITLE
Customized health check options

### ISSUE THREAD

**Issue by jeran-urban** [aspnet/AspNetCore#12507]
Hello,

I have a registered customized health check and a singleton registered service associated::
```
**startup.cs**
  services.AddSingleton<ICustomApiHealthCheckSingleton, CustomHealthChecker>();

Configure(....) {
services.AddHealthChecks()
               .AddCheck<CustomApiHealthCheckValue>("CustomApiHealthCheckValue");
}
```
```
**CustomApiHealthCheckValue.cs**
 public class CustomRegisteredToHealthCheckApiHealthCheckValue : IHealthCheck
    {
        private readonly ICustomApiHealthCheckSingleton _healthChecker;
        public CustomApiHealthCheckValue(ICustomApiHealthCheckSingleton checker)
        {
            Startup.IsHcRunning = true;
            _healthChecker = checker;
        }
        public Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default(CancellationToken))
        {
            bool isHealthy = _healthChecker.IsApiCheckHealthy();
            
            if (!isHealthy)
            {
                return Task.FromResult(new HealthCheckResult(
                    status: context.Registration.FailureStatus,
                    description: "He is dead Jim"));
            }
            return Task.FromResult(HealthCheckResult.Healthy("Healthy as a horse"));
        }
    } 
```
```
**ICustomApiHealthCheckSingleton.cs**
public interface ICustomApiHealthCheckSingleton
    {
        bool IsApiCheckHealthy();
    }
    public class CustomHealthChecker : ICustomApiHealthCheck
    {
        public IConfiguration Configuration { get; }

        public CustomHealthChecker(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        
        public bool IsApiCheckHealthy()
        {
            using (var webClient = new WebClient())
            {
                IConfigurationSection configurationSection = Configuration.GetSection("hCInfo").GetSection("api").GetSection("siteSuccess");
                
                string rawJson = webClient.DownloadString(configurationSection.Value);
              
                AppCls app = JsonConvert.DeserializeObject<AppCls>(rawJson);

                if (app.HealthCheckResults.Status == StatusEnum.Up)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
        }
    }
```
My question: is there a way that I could add multiple customized singleton checks and configure all them to go through the same registered customized health check?

Since the registered health check is returning true or false, I do not see a way to configure all customized health checks(singleton services) to run through the one registered custom health check, without having them return as a single healthy/unhealthy status as an end result, rather than a series of results.

Do I need to register a separate custom health check for each of the singleton services I am registering? If so, this would lead to a fair amount of duplicate code.

Also, Is there an argument / best practice to follow for registering a singleton service separate from the registered health check vs. only registering a custom health check that returns the healthCheckStatus as well? Thank you.

**Comment by rynowak** [comment]
Can you be a little more concrete about your example? The code that's in `ICustomApiHealthCheckSingleton` is what I would expect to see in your health check implementation.

If you want to register a single check or multiple checks, that's up to you - choose based on how you want the results to be reported. Do you want to an individual pass/fail for each item or not?

**Comment by jeran-urban** [comment]
Thank you.
