### ISSUE TITLE
How to manually set the Context.connectionId

### ISSUE THREAD

**Issue by fdevGit** [aspnet/AspNetCore#12510]
I have multiple unique keys for one user. I want to synchronize my key with xy so there are no more unique keys

**Comment by mikaelm12** [comment]
This field is not settable on the client. It's allocated on the server via negotiate to be able to differentiate different connections. I think what you want to refer to is a `UserId `or `UserName`, not `connectionId`

**Comment by fdevGit** [comment]
I need to text users. I don't want any more unique keys. I want to send messages to users with my keys

**Comment by anurse** [comment]
I'd suggest you check out the documentation on [Users and Groups](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.2). With that you can set a user ID and send messages to connections based on that. The connection ID is controlled entirely by SignalR and not settable in your application.

**Comment by fdevGit** [comment]
Can I add a unique key to the user and send a message, except for ConnectionId? the method you type will create more redis channels.

**Comment by anurse** [comment]
No, this is not possible. Only the existing Connection ID, a User ID and any Groups you add the connection to can be used.

**Comment by anurse** [comment]
You mention you already have a user ID. Is it not ever possible for a user to be connected from multiple devices in your application? The multiple-device scenario is why Users work the way they do (a separate Redis channel since there could be multiple connections for the specific user).

**Comment by fdevGit** [comment]
When the user connects, a channel is created. When we create a group, a different channel is created. That's right. Can be connected with multiple devices.I may only need to send messages to 1 device. for this I have to match my identity to your identity. this requires an operation. If we give you an identity, we will avoid unnecessary procedures.

**Comment by fdevGit** [comment]
will a **development** be made in this regard?

**Comment by anurse** [comment]
We have no plans to make Connection ID settable. Using a group, user ID or your own connection ID mapping is recommended.
