### ISSUE TITLE
Runtime error page leaks information about the hosting environment

### ISSUE THREAD

**Issue by mattbrooks2010** [aspnet/AspNetCore#12516]
### Is your feature request related to a problem? Please describe.
The runtime error page, such as the one displayed when start-up errors are captured by the generic host, [displays information about the hosting environment](https://github.com/aspnet/AspNetCore/blob/b9823ed41c8ff23b6dbd233f5cc2a8e5078d2339/src/Shared/ErrorPage/ErrorPage.cshtml#L152-L154).

The information includes the OS version and CLR version.

This information is displayed in local development and production environments. This doesn't seem necessary in the latter — at least not by default.

### Describe the solution you'd like
It would be beneficial if there was an option to suppress this information in the error page response, without needing to [disable the capturing of start-up errors entirely](https://github.com/aspnet/AspNetCore/blob/b9823ed41c8ff23b6dbd233f5cc2a8e5078d2339/src/Hosting/Hosting/src/GenericHost/GenericWebHostedService.cs#L110-L113).

### Additional context
It is common for web application security penetration test providers to declare the leakage of information about the hosting environment as a security vulnerability. 

![anc_startup_error_page](https://user-images.githubusercontent.com/2045274/61808156-c9474600-ae32-11e9-91d0-f2494b6e772f.png)

**Comment by blowdart** [comment]
@pranavkm @Tratcher 

If I look at the code for the error page it can be quite detailed. Am I missing something here in thinking this is wired up, by default, for GenericWebHostService without taking the environment into account?

**Comment by anurse** [comment]
> Am I missing something here in thinking this is wired up, by default, for GenericWebHostService without taking the environment into account?

The page itself doesn't make this determination, the code rendering it does it when it decides what to put in the model object.

It does make sense to suppress runtime version info when not rendering detailed error messages. I opened a PR to fix the page to do this.

**Comment by anurse** [comment]
Validation Notes:
* [ ] Use WebHost with CaptureStartupErrors
* [ ] Use GenericHost with CaptureStartupErrors
* [ ] Verify IIS in-proc StartupHook doesn't render this info.

**Comment by mattbrooks2010** [comment]
Thanks for taking a look at this. Please would you consider applying any final changes to ASP.NET Core 2.x?
