### ISSUE TITLE
how to use te override OnInitializedAsync on my pages

### ISSUE THREAD

**Issue by MarvynHarry** [aspnet/AspNetCore#12512]
What do I have to do to be able to use these methods since in my project it says "no suitable method found to override"
![image](https://user-images.githubusercontent.com/44927942/61804734-d3ede500-ae0a-11e9-9fc5-afacb02e83c2.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MarvynHarry.
We've changed the name of this method in Preview8. Unless you're running the nightly builds, you will not see it and should use the documented `OnInitAsync()` instead.

**Comment by MarvynHarry** [comment]
@mkArtakMSFT  Preview 8 has already been released, where can I download it?

**Comment by mkArtakMSFT** [comment]
No, it hasn't. It's only available through the nightly builds.

**Comment by MarvynHarry** [comment]
> No, it hasn't. It's only available through the nightly builds.

@mkArtakMSFT  Does the preview 8 have a release date?

**Comment by mkArtakMSFT** [comment]
It'll be sometime mid-August.
