### ISSUE TITLE
Verification for globalization and localization for server-side Blazor

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#12520]
Testing with server-side-Blazor (in Azure):
- [x] Can use ASP.NET localization middleware to configure a locale
- [x] Resource files work
- [x] Numbers are formatted according to the locale
- [x] type="number" fields work

**Comment by SteveSandersonMS** [comment]
Should this be in the preview 8 milestone, not 9?

**Comment by rynowak** [comment]
Done.

**Comment by rynowak** [comment]
Found and sent PR to fix: https://github.com/aspnet/AspNetCore/issues/12631
