### ISSUE TITLE
MissingMethodException at SignInManager ctor after update

### ISSUE THREAD

**Issue by LaterStart** [aspnet/AspNetCore#12536]
Hi,

I've updated to .NET Core preview 7 and updated all dependencies accordingly. Missing method exception bellow occurs on DI of ISiginInManager service at controllers constructor. The project is cleaned and rebuilt.

```
An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Identity.SignInManager`1..ctor(Microsoft.AspNetCore.Identity.UserManager`1<!0>, Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1<!0>, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Identity.IdentityOptions>, Microsoft.Extensions.Logging.ILogger`1<Microsoft.AspNetCore.Identity.SignInManager`1<!0>>, Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider)'.

Vigab.Infrastructure.IdentityService.Infrastructure.SignInManager..ctor(UserManager<ApplicationUser> userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory<ApplicationUser> claimsFactory, IOptions<IdentityOptions> optionsAccessor, ILogger<SignInManager<ApplicationUser>> logger, IAuthenticationSchemeProvider schemes)
```

I've noticed I had to change implementation of the SignInManager constructor, because the new version is receiving one parameter less.
```

    public partial class SignInManager : SignInManager<ApplicationUser>, ISignInManager
    {
        public SignInManager(
            UserManager<ApplicationUser> userManager,
            IHttpContextAccessor contextAccessor,
            IUserClaimsPrincipalFactory<ApplicationUser> claimsFactory,
            IOptions<IdentityOptions> optionsAccessor,
            ILogger<SignInManager<ApplicationUser>> logger,
            IAuthenticationSchemeProvider schemes)
            : base(userManager, contextAccessor, claimsFactory, optionsAccessor, logger, schemes)
        {
        }
     }
```

Here is the service registration.

```
public void RegisterService(IServiceCollection services, string connectionString)
        {
            services.AddDbContext<IdentityDbContext>(options =>
                options.UseSqlServer(connectionString));

            services.AddIdentity<ApplicationUser, IdentityRole>(options =>
                {
                    options.User.RequireUniqueEmail = true;
                    options.Password.RequireNonAlphanumeric = false;
                    options.SignIn.RequireConfirmedEmail = true;
                })
                .AddUserStore<UserStore>()
                .AddUserManager<UserManager>()
                .AddRoleStore<RoleStore>()
                .AddRoleManager<RoleManager>()
                .AddSignInManager<SignInManager>()
                .AddDefaultTokenProviders();

            services.AddTransient<IUserManager, UserManager>();
            services.AddTransient<ISignInManager, SignInManager>();
            services.AddTransient(x =>
            {
                var userManager = x.GetService<IUserManager>();
                var contextAccessor = x.GetService<IHttpContextAccessor>();
                return userManager.GetUserAsync(contextAccessor.HttpContext.User).Result;
            });
        }
```

**Stack trace:**
```

MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Identity.SignInManager`1..ctor(Microsoft.AspNetCore.Identity.UserManager`1<!0>, Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1<!0>, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Identity.IdentityOptions>, Microsoft.Extensions.Logging.ILogger`1<Microsoft.AspNetCore.Identity.SignInManager`1<!0>>, Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider)'.

    Vigab.Infrastructure.IdentityService.Infrastructure.SignInManager..ctor(UserManager<ApplicationUser> userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory<ApplicationUser> claimsFactory, IOptions<IdentityOptions> optionsAccessor, ILogger<SignInManager<ApplicationUser>> logger, IAuthenticationSchemeProvider schemes)
    System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
    System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
    Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
    lambda_method(Closure , IServiceProvider , object[] )
    Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider+<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
    Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider+<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by mikaelm12** [comment]
Was there a breaking change here that we didn't announce? cc @HaoK @anurse

**Comment by HaoK** [comment]
Yes as part of adding the user confirmation flows, we added a new ctor `IUserConfirmation<TUser>` parameter

https://github.com/aspnet/AspNetCore/commit/555b506a97a188583df2872913cc40b59e563da6#diff-9a3a4da09ce42b77457c5f3f23ced7fa

**Comment by anurse** [comment]
I don't see anything on aspnet/Announcements (https://github.com/aspnet/Announcements/search?q=IUserConfirmation+is%3Aissue&type=Issues) 😦 

We should announce it appropriately. I know @davidfowl has been working on reviewing breaking changes and bulk-announcing things.

**Comment by HaoK** [comment]
Filed https://github.com/aspnet/Announcements/issues/374

**Comment by mikaelm12** [comment]
Sorry about the miscommunication @LaterStart!

**Comment by LaterStart** [comment]
OK, this sounds like I am missing additional parameter to constructor, but I think it isn't the case here as it is not being recognized.

![Untitled](https://user-images.githubusercontent.com/39437117/61902463-764cbc00-af22-11e9-942b-291369d1ba9b.png)

**Comment by HaoK** [comment]
You might have mixed packages perhaps?  https://github.com/aspnet/AspNetCore/blob/v3.0.0-preview7.19365.7/src/Identity/Core/src/SignInManager.cs#L35

**Comment by LaterStart** [comment]
Hmm I'm not sure what I might be missing here.
I am using Microsoft.AspNetCore.Identity 2.2.0-preview3-35497

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

**Comment by HaoK** [comment]
You should be using Identity 3.0.0-preview7 no?

**Comment by HaoK** [comment]
There is no breaking change in the 2.2 version

**Comment by LaterStart** [comment]
Oh I see.. As it isn't available over Nuget, I've been using the 2.2.0 version, which broke after 3.0.0-preview 7 SDK update. Didn't think it was related.

**Comment by HaoK** [comment]
Yeah so you are building against preview 6 and running against preview 7, hence the missing method exception

**Comment by LaterStart** [comment]
Ok that is logical, but not sure why it could be built on preview 6 with 7 parameters. 
Never mind I have downloaded the binaries manually and added the .dll references. 

Maybe identity 3.0 previews could be shipped as Nuget package too?

**Comment by anurse** [comment]
> Anyways.. I have downloaded the binaries manually and added the .dll references, which fixed the issue in the end.

That is definitely not a good solution :S.

Can you clarify a few things?
* What exact target framework are you using? `netcoreapp3.0`?
* What specific Identity packages are you referencing (IDs **and** version numbers)?

**Comment by LaterStart** [comment]
Target framework is netcoreapp3.0, yes.

Ok, for now I am using these assembly references:
Microsoft.AspNetCore.Authentication.Abstractions, Version=3.0.0.0
Microsoft.AspNetCore.Identity, Version=3.0.0.0
Microsoft.AspNetCore.Http.Abstractions, Version=3.0.0.0

**Before the update I've been using Microsoft.AspNetCore.Identity version 2.2.0 nuget package.**

Also I am using these related nuget packages
Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.0.0-preview7.19365.7
Microsoft.Extensions.Identity.Core 3.0.0-preview7.19365.7
Microsoft.Extensions.Identity.Stores 3.0.0-preview7.19365.7

Before the updated all nuget packages were preview6xxx accordingly.

**Comment by anurse** [comment]
> **Before the update I've been using Microsoft.AspNetCore.Identity version 2.2.0 nuget package.**

Ok, that definitely won't work. Using `2.2.0` packages in `netcoreapp3.0` is exactly what would bring you in to this missing method situation.

> For now I am using these assembly references:
> Microsoft.AspNetCore.Authentication.Abstractions, Version=3.0.0.0
> Microsoft.AspNetCore.Identity, Version=3.0.0.0
> Microsoft.AspNetCore.Http.Abstractions, Version=3.0.0.0

You shouldn't need references to these, they should come automatically when using the Web SDK (`<Project Sdk="Microsoft.NET.Sdk.Web">` at the top of your `csproj`). They're just part of the ASP.NET Core framework.

> Also I am using these related nuget packages
> Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.0.0-preview7.19365.7
> Microsoft.Extensions.Identity.Core 3.0.0-preview7.19365.7
> Microsoft.Extensions.Identity.Stores 3.0.0-preview7.19365.7

These are indeed the most up-to-date version of these packages. As long as you're using a preview7 build of the runtime it should work.

**Comment by LaterStart** [comment]
Thank you I wasn't familiar with this information. My intention was to use identity project as library plugin service. In that case, I will need to add references manually?

**Comment by anurse** [comment]
If you're writing a library, you can either use the Web SDK or the new `FrameworkReference` node in your `csproj` instead of referencing individual DLLs.

**Using the Web SDK**:
Change the `Sdk` attribute on the `<Project>` element in your `csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
	<!-- project content ... -->
</Project>
```

**Using Framework Reference**:
Add an MSBuild Item using `FrameworkReference` referring to the `Microsoft.AspNetCore.App` framework.
```xml
<Project ...>
	<!-- other project content ... -->
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<!-- other project content ... -->
</Project>
```

**Comment by atresnjo** [comment]
@anurse 

I'm having the same issue, but that doesn't seem to work for me.

Installed dotnet version:

`3.0.100-preview8-013656`

My library project:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="3.0.0-preview8.19405.7" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="3.0.0-preview8.19405.7" />
  </ItemGroup>

</Project>

```

It seems that it only references Microsoft.AspNetCore.Identity and Microsoft.AspNetCore.Cryptography but nothing else. 

When I use the FrameworkReference I get

`The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets`



Any Idea what I am doing wrong? Thanks!

![grafik](https://user-images.githubusercontent.com/41112852/64160515-5f13bf00-ce3c-11e9-9579-7d7748516a89.png)

**Comment by Looooooka** [comment]
Just updated to net core 3 and I have the exact same problem.
Worked fine in 2.2

{"Method not found: 'Void Microsoft.AspNetCore.Identity.SignInManager`1..ctor(Microsoft.AspNetCore.Identity.UserManager`1<!0>, Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1<!0>, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Identity.IdentityOptions>, Microsoft.Extensions.Logging.ILogger`1<Microsoft.AspNetCore.Identity.SignInManager`1<!0>>, Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider)'."}

**Comment by Looooooka** [comment]
As far as I can tell the problem seems to be that Microsoft.AspnetCore.Identity 3.0.0 nuget package hasn't been published yet.
Last one I'm seeing ins preview6
When is this going to be published? :)
