### ISSUE TITLE
Cookie authentication some browsers cannot logout

### ISSUE THREAD

**Issue by csc414** [aspnet/AspNetCore#12546]
Cookie authentication, some browsers cannot logout, like UC mobile browser.
I think these browsers more strict, because the cookie created by HttpContext.SignInAsync defaults HttpOnly=true, so if you want to delete cookie, you must bring HttpOnly=true.
like HttpContext.Response.Cookies.Delete(CookieName, new Microsoft.AspNetCore.Http.CookieOptions { HttpOnly = true }); 
If you set up Cookie Domain in Startup, you must bring Domain too.
like HttpContext.Response.Cookies.Delete(CookieName, new Microsoft.AspNetCore.Http.CookieOptions { HttpOnly = true, Doamin = "Your Cookie Domain" }); 

1. Using this version of ASP.NET Core 2.2
2. Run this code Normal HttpContext.SignInAsync And HttpContext.SignOutAsync

**Comment by blowdart** [comment]
Do you see this behaviour in any other browser, on your phone or desktop?

**Comment by Tratcher** [comment]
HttpOnly is missing here:
https://github.com/aspnet/AspNetCore/blob/c76cb9248de8966b25bc08b098b88d6734b96d09/src/Shared/ChunkingCookieManager/ChunkingCookieManager.cs#L280-L308
The Domain is included.

**Comment by blowdart** [comment]
It seems somewhat over jealous of UC browser to want http only on a delete, but, it's not like there's any real harm in adding it to the delete function I suppose. 

@anurse  A one link bug fix. Can this make it into 3.0?

**Comment by anurse** [comment]
Seems reasonable for me. The fix seems trivial but we should probably smoke-test that other browsers (at least the core desktop ones, non-Chromium Edge, Chrome/"Edgium" and Firefox) don't blow up and not delete the cookie for some reason when you do this.

Getting it in to 3.0 depends on one of two things:

* @Tratcher being able to do it today or tomorrow
* OR, being able to get it through ask mode

Otherwise, it can go in to 3.1 when `master` switches over next week.

**Comment by Tratcher** [comment]
I don't have bandwidth, but anybody could take this one.

**Comment by anurse** [comment]
I'll see if someone can spare some bandwidth, but otherwise this might have to knock forward to 3.1. The change is 1-liner but I do think there's some smoke testing needs here that make it more than just a 5-10 minute fix-up.

**Comment by anurse** [comment]
Hrm, this is all still based on a hunch that adding HttpOnly is necessary here right? I'd love to know exactly which browser has this problem (@csc414 you mentioned UC Browser, do you mean this browser: http://www.ucweb.com/ , and is it only on mobile or does it repro on desktop?)

@BrennanConroy can you take a quick look for preview8? I can see us doing this simple change for p8: Add `HttpOnly` to the cookie deletion logic referenced by @Tratcher above and make sure that doesn't break login/logout on the main browsers. As long as that's the case, it's harmless to take this change. If it doesn't end up fixing the UC Browser, we can continue investigating post-3.0.

**Comment by csc414** [comment]
@anurse  yes it is, i make some tests, the problem is only in ios uc browser, my test phone is iphone 7 plus and iphone x.

**Comment by csc414** [comment]
@blowdart For now, the problem is only in iOS uc browser.

**Comment by anurse** [comment]
Ok, @BrennanConroy made the change recommended by @Tratcher. It should be available in 3.0-preview8 (exact release date is not announced but we're branching to start work on final stabilization on Monday).

We don't know for sure that this will fix the issue but if it doesn't, come on back and let us know and we'll keep looking!
