### ISSUE TITLE
Blazor directive attribute parameters coloring doesn't respect case sensitivity

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#12541]
![image](https://user-images.githubusercontent.com/1579269/61833567-8df44980-ae29-11e9-8aed-c5d92564f5ff.png)

In the above image, I expect "@bind-value:EVENT" to not be colored because it is no longer a valid directive attribute.

@NTaylorMullen, I assume the fix for this should be from WTE?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen, I assume the fix for this should be from WTE?

Hmmm, do we understand that attribute as a directive attribute? If we do it might be on our side. If not then on WTEs side.

**Comment by ajaybhargavb** [comment]
Yeah we don't match that as a directive attribute anymore.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb is somebody following up on this? Are they aware this is a problem? If there is a separate bug tracking this, we should close this.

**Comment by mkArtakMSFT** [comment]
Moving this to 3.1 as this is tracking-only change

**Comment by ajaybhargavb** [comment]
Here is the [PR](https://devdiv.visualstudio.com/DevDiv/_git/WebTools/pullrequest/199954) with the fix.

**Comment by ajaybhargavb** [comment]
The fix has been merged.
