### ISSUE TITLE
How to map a complex return type in .net Core client

### ISSUE THREAD

**Issue by AnReZa** [aspnet/AspNetCore#12563]
I'm using the .net Core client inside my C# app. My service method returns an IEnumerable of a class, which contains three different properties. In JavaScript, this works fine. In C#, however, I have no idea, how I should format my invoke call. Right now, I tried it with an IEnumerable of a Tupel, which doesn't work:

```C#
var ret = await connection.InvokeAsync<IEnumerable<(Guid guid, DateTime timestamp, string sender, string message)>>("GetLastNMessages", count);
```

In this case, ret is a list of two, objects, but all four properties are nulled. How would I correctly write this down, so that the client would map everything correctly?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by AnReZa** [comment]
Here's the server method:

```C#
public IEnumerable<MessageItem> GetLastNMessages(int count) {
    return msgStore.GetLastN(count);
}

public IEnumerable<MessageItem> GetLastN(int count) {
    return msgStore.TakeLast(count);
}

public class MessageItem {
    public Guid Guid { get; set; }
    public DateTime Timestamp { get; set; }
    public string Sender { get; set; }
    public string Message { get; set; }
}
```

At the moment, I worked around the problem by adding a project link to the MessageItem class file from my server project into the client project. But what would be the best practice, if the client is developed by a thirs party? Do I always need to provide a proper class description, or is there an easier way?

**Comment by mkArtakMSFT** [comment]
Glad you've found a solution for your problem.
As for your question, no, there is no easier way.

**Comment by AnReZa** [comment]
Thank you!
