### ISSUE TITLE
Is changed convention of generating path of Razor class library static assets?

### ISSUE THREAD

**Issue by qw-34** [aspnet/AspNetCore#12561]
According to the documentation https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#create-an-rcl-with-static-assets

> The files included in the wwwroot folder of the RCL are exposed to the consuming app under the prefix _content/{LIBRARY NAME}/. {LIBRARY NAME} is the library project name **converted to lowercase with periods (.) removed**. For example, a library named Razor.Class.Lib results in a path to static content at _content/razorclasslib/.

In Preview 6 it works as expected, but in Preview 7 generated path differs. {LIBRARY NAME} is **NOT converted to lowercase and periods (.) NOT removed**. For example, a library named Razor.Class.Lib results in a path to static content at _content/Razor.Class.Lib/.

**Comment by AlseinX** [comment]
#11174

**Comment by pranavkm** [comment]
@qw-34 the docs have been updated as part of https://github.com/aspnet/AspNetCore.Docs/pull/13501. (thanks @mikes-gh!). As you noted, the path is the package name without any transformation.
