### ISSUE TITLE
Strange InvalidCastException of System.Text.Json for 3.0 preview7 only

### ISSUE THREAD

**Issue by iron9light** [aspnet/AspNetCore#12569]
### Describe the bug
```csharp
        [HttpGet]
        public ActionResult<IEnumerable<ValueB>> Get()
        {
            var valueAs = Enumerable.Range(0, 10).Select(x => new ValueA { Value = x }).ToList();
            return new ActionResult<IEnumerable<ValueB>>(valueAs.Select(x => new ValueB { Value = x.Value }));
        }
```
It will throw `InvalidCastException: Unable to cast object of type 'aspnetcorebug.Controllers.ValueB' to type 'aspnetcorebug.Controllers.ValueA'.`
by `System.Text.Json.JsonPropertyInfoNotNullable<TClass, TDeclaredProperty, TRuntimeProperty, TConverter>.OnWrite(ref WriteStackFrame current, Utf8JsonWriter writer)`

### To Reproduce
Sample code:
https://github.com/iron9light/aspnetcore_issue12569

### Expected behavior
It should return serialized json list.
It works with preview6 and works with NewtonsoftJson.

### Additional context
Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450
```

**Comment by pranavkm** [comment]
@iron9light looks like a bug in the JsonSerializer. I tried running your app using a preview8 (`Microsoft.NETCore.App v3.0.0-preview8-28373-17`) build and it looks like this issue has been resolved - it prints the serialized output.

/cc @ahsonkhan \ @layomia \ @steveharter \ @ericstj in case you'd like to link this to a CoreFx issue.
