### ISSUE TITLE
Blazor Preview 7 not building???

### ISSUE THREAD

**Issue by moritz-mm** [aspnet/AspNetCore#12577]
My Blazor Preview 7 is not Building im missing the namespace App..
i using the newest Blazor Templates and Blazor Version

Here is my .csproj maybe has anyone here an idea whats wrong 

```
> <Project Sdk="Microsoft.NET.Sdk.Web">
> 
>   <PropertyGroup>
>     <TargetFramework>netstandard2.0</TargetFramework>
>     <LangVersion>7.3</LangVersion>
>     <RazorLangVersion>3.0</RazorLangVersion>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview6.19307.2" />
>     <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview6.19307.2" PrivateAssets="all" />
>     <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview6.19307.2" PrivateAssets="all" />
>   </ItemGroup>
> 
> </Project>
```

**Comment by moritz-mm** [comment]
I reolved my issue by myself. I forgot to activate use .NET 3.0 Previews in the Visual Studio settings please include that the "Blazor getting started" article.

**Comment by Pilchie** [comment]
Just a note that I would highly recommend using the VS *Preview* channel when using .NET Core Previews.  The tooling for Blazor, Razor, C# 8, etc, all matches much more closely there than in the Release channel.
