### ISSUE TITLE
How to get “Display name” on the label of in Blazor's razor page?

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#12572]
I have following model:
```
class User
{
    [Display(Name = "Display Name")]
    public string Name { get; set; }
}
```

I have following model:

class User
{
    [Display(Name = "Display Name")]
    public string Name { get; set; }
}
In standard Razor I would do something like that to get "Display name"

```
<label asp-for="Model.Name"></label>
```
but that doesn't seem to work in Blazor. Dose anyone know how to get display name in Blazor page without using reflection?

Thanks in advance...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @enetstudio.
This is not a feature we currently have. We will put this issue in the Backlog to reevaluate in the future.

**Comment by enetstudio** [comment]
Got it, thanks...
