### ISSUE TITLE
DefaultReconnectionHandler "invokes failed if reconnect fails" test fails on macOS

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#12578]
As part of https://github.com/aspnet/AspNetCore/pull/12145, I found that "invokes failed if reconnect fails" fails on macOS consistently. I've disabled it (commented it out) for now but the failure should be investigated.

**Comment by JunTaoLuo** [comment]
cc @rynowak @SteveSandersonMS @javiercn @pranavkm

**Comment by SteveSandersonMS** [comment]
Thanks @JunTaoLuo!

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen here is another one for you to tackle.

**Comment by NTaylorMullen** [comment]
I can't reproduce the failure on MacOS. Going to relax some of the test parameters and see if it passes on the CI.
