### ISSUE TITLE
Asp.net Core (Hosted in IIS) SSL Redirection Not Working

### ISSUE THREAD

**Issue by zanate4019** [aspnet/AspNetCore#12570]
### Describe the bug
I have configured SSL redirection as described in https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#configure-permanent-redirects-in-production, but it's not working.  Connections on HTTP stay on HTTP.

### To Reproduce
ASP.NET configured as in attached startup.cs
[Startup.cs.txt](https://github.com/aspnet/AspNetCore/files/3432121/Startup.cs.txt).
IIS Bindings: 
![image](https://user-images.githubusercontent.com/10452739/61885065-d3188a00-aec2-11e9-800a-36fd46e6c4dc.png)

### Expected behavior
I would like any HTTP connection to be redirected to https://boxwebtest.ausrad.com

### Additional context
[dotnetinfo.txt](https://github.com/aspnet/AspNetCore/files/3432133/dotnetinfo.txt)

**Comment by anurse** [comment]
We believe this is fixed in 3.0. Please try the RC1 release (or the imminent final release) and let us know if you're still hitting this issue.
