### ISSUE TITLE
StartupAnalyzer spelling

### ISSUE THREAD

**Issue by martinstenhoff** [aspnet/AspNetCore#12574]
I'm half expecting this to be done on purpose since no one picked up on it in code review
#9100, but Analzyer should most likely be Analyzer

I can open a pull request with the fix from [Changing Analzyer to Analyzer](https://github.com/martinstenhoff/AspNetCore/commit/cefa28dbec70226e9272afb1c47064888383a117) but unsure if other areas also need to be updated.

**Comment by mkArtakMSFT** [comment]
Thanks @martinstenhoff.
If you happen to send a PR during the day, we'll take it. If not, we'll simply do it 👍

**Comment by rynowak** [comment]
Thanks @martinstenhoff
