### ISSUE TITLE
Publishing a 'Blazor Webassembly App' to Azure still not working. 

### ISSUE THREAD

**Issue by rxelizondo** [aspnet/AspNetCore#12575]
Using the latest release of Visual Studio (16.3.0 Preview 1) and .NET core (3.0.0-preview7-27912-14). If you try to publish a brand new `Blazor Webassembly App` project, you wont get an error, however, when you try to access the app all you get is a page can't found error:

```
This xyz.azurewebsites.net page can’t be found No webpage was found 
for the web address: https://xyz.azurewebsites.net/

HTTP ERROR 404
```

This was mentioned here a couple of days ago: https://github.com/aspnet/AspNetCore/issues/10509#issuecomment-511143569

To reproduce, simply create a brand new `Blazor Webassembly App`  and then deploy it to a brand new app service.

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rxelizondo.
Are you creating a Blazor Hosted or standalone client app?

**Comment by rxelizondo** [comment]
It used to be called `Blazor (ASP.NET Core hosted)`, but now is called `Blazor Webassembly App` as far as I can see.

So to answer your question, its a hosted project (webassembly on the browser and ASP.NET Core on the server side).

**Comment by rxelizondo** [comment]
@mkArtakMSFT :  My apologies, it looks like when I upgraded to preview 7 I forgot to update to the latest client-side Blazor templates by running:

`dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview7.19365.7`

After I updated the templates, everything started working fine, sorry about that.

Thank you.
