### ISSUE TITLE
Cannot load static resources while using PublishSingleFile

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#12582]
### Describe the bug
Cannot load static resources while using PublishSingleFile
### To Reproduce
1. Using .NET Core 3.0 preview 7
2. dotnet new mvc
3. dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true
4. run the published executable file
5. all attemps to load resourses in wwwroot result in 404

### Expected behavior
The program ran as what it should be

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hez2010.
@javiercn I think this is being tracked somehere else. Can you please dupe this with that exisitng issue? I couldn't find it. Thanks!

**Comment by davidfowl** [comment]
https://github.com/aspnet/AspNetCore/issues/12020
