### ISSUE TITLE
npm install won't install dependencies even when specifying package file

### ISSUE THREAD

**Issue by jdescelliers** [aspnet/AspNetCore#12586]
### Describe the bug
NPM install doesn't install any dependencies even when specifying package.json as arg.

### To Reproduce
- create a new ASP .NET Core 2.2 project
- add this package.json in the root dir: 
```javascript
{
    "name": "something",
    "description": "something",
    "author": {
        "name": "JD",
        "email": "my@email.com"
    },
    "version": "0.1",
    "keywords": [
        "bla",
        "bla"
    ],
    "repository": {
        "type": "git",
        "url": "https://github.com/arepo"
    },
    "dependencies": {
        "clean-webpack-plugin": "^3.0.0",
        "css-loader": "^3.1.0",
        "mini-css-extract-plugin": "^0.8.0",
        "node-sass": "^4.12.0",
        "package.json": "^2.0.1",
        "sass-loader": "^7.1.0",
        "stylelint": "^10.1.0",
        "ts-loader": "^6.0.4",
        "typescript": "^3.5.3",
        "webpack": "^4.36.1",
        "eslint": "^6.1.0",
        "webpack-cli": "^3.3.6"
    }
}
```
- install NodeJS 10 along with NPM 
- in project root, run npm install package.json
![npm-packages](https://user-images.githubusercontent.com/30500043/61901024-1f91b300-af1f-11e9-8cc9-956cb78556e8.png)

The screenshot above shows installed dependencies.

Tested on both WIndows 10 with VS 2019 (which has an awful built in Git client by the way) on OS X 10.14 with the exact same behaviour
### Expected behavior
- install dependencies from package.json

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

Why are those packages installed? Because a .Net core app with TS support requires it?

I can install the dependencies if I do this:
`npm install my-package-name`
if I do them one by one it works fine.

I've spent hours on this, please don't close this issue without relevant information.

**Comment by serpent5** [comment]
You’re just installing the package called `package.json` (and it’s dependencies). You meant to just run `npm install`.

**Comment by jdescelliers** [comment]
@serpent5 yep but I tried variations to isolate the problem.

Here's the answer to my own problem: 
- multiple warning are shown **including an incorrect version number** (no other info),
- version number (as of 2018-07-25) MUST respect semantic versioning otherwize packages won't install see [semver](https://semver.org/), under Semantic Versioning 2.0.0 > Summary >
1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3.  PATCH version when you make backwards-compatible bug fixes.

Or for human beings:
- incorrect : 1.0, 1.0.0, v1.0, v1.2 (the column is just a serator)
- correct: 1.0.0.0, 1.0.10, 2.3.1-ALPHA.

**Comment by isaacs** [comment]
@jdescelliers I think you made a typo there. You listed `1.0.0` as incorrect, and `1.0.0.0` as correct. Those should be flipped.

**Comment by jdescelliers** [comment]
@isaacs and it seems I was correct for versions numbers, have a look at the link semver, note that it is actually a preblem with npm.

Here's the NPM issue I created: https://npm.community/t/npm-install-only-partial-if-versioning-isnt-semantic/9106

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This seems to be unrelated to ASP.NET Core framework. Feel free to follow up on this in the appropriate issue-tracker.
