### ISSUE TITLE
Blazor (client side) hosted on IIS not serving static assets from libraries

### ISSUE THREAD

**Issue by tn-5** [aspnet/AspNetCore#12583]
We have a component library which has some static assets. Following the instructions for the preview 6 release we put the js and css content in a `wwwroot` folder. This works 100% for server side blazor and on client side blazor when running directly using kestrel. 

However, when publishing the client side blazor project to IIS the resources are not found. 

We fixed this by modifying the generated `web.config` to include a rewrite rule like:
`        <rule name="wwwroot-static" stopProcessing="true">
          <match url="_content/(.*)" />
          <action type="Rewrite" url="wwwroot/{R:0}" />
        </rule>`

Is this supposed to be required or did we miss something? Normally the generated web.config includes all that is required.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tn-5.
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
