### ISSUE TITLE
Blazor: Use of @ with value instead of Attribute Key at all places

### ISSUE THREAD

**Issue by AmarjeetBanwait** [aspnet/AspNetCore#12602]
Using `@` with value instead of attribute key makes more sense. It is now very much irritating using it at someplaces with Key( c# attributes) and at someplaces with value (in case of html attributes)
```
<li class="@cssClass">
<li key="@value">
```
is much consistent and best practice than
```
<li class="@cssClass">
<li @key="value">
```
using `@` with value means we are using something from code makes more sense instead of using it with key.

c# attributes can be very much distinguished with different color as of now blue for html attributes and green for c# attributes.

also previously double quotes in double quotes was pretty much working

`onclick=@"(() => UriHelper.NavigateTo("/user/create"))"`
but now this gives error and outer double quotes need to be changed with single quotes to make it working

`@onclick='(() => UriHelper.NavigateTo("/user/create"))'`
Also removing `@` from value making it White in appearance and there is no hover effect.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AmarjeetBanwait.
This is not something we plan to go back to - there were a set of issues with that approach. Specifically, removing `@` would result in collisions with html attributes.

As for the other problem you're reporting , please file a separate issue:
> but now this gives error and outer double quotes need to be changed with single quotes to make it working

**Comment by AmarjeetBanwait** [comment]
Thanks @mkArtakMSFT  Why do we got need for c# event attributes instead of html native event attributes?
