### ISSUE TITLE
SignalR Custom Protocol

### ISSUE THREAD

**Issue by alarco-l** [aspnet/AspNetCore#12605]
Hi,

I'm trying to write my own `SignalR Hub Protocol` based on `protobuf`.
I'm struggling with the streaming part, streaming from client to hub.

According to the signalR documentation, to stream from client to hub, I should do something like that:
```C#
var channel = Channel.CreateBounded<string>(10);
await hubConnection.SendAsync("Stream", channel);
await channel.Writer.WriteAsync("Some data");
await channel.Writer.WriteAsync("Some other data");
channel.Writer.Complete();
```

From my understanding of the protocol based on the [spec](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md)
and what I saw in `MessagePackHubProtocol.cs` I should be receiving:
* A `StreamingInvocationMessage` with a unique `InvocationId`
* A `StreamingItemMessage` with the same `InvocationId` and an `item` with "Some data" value
* A `StreamingItemMessage` with the same `InvocationId` and an `item` with "Some other data" value
* A `CompletionMessage` with the same `InvocationId` (maybe a `result` too)

But 
```C#
await hubConnection.SendAsync("Stream", channel);
```
Sends me a `MethodInvocationMessage`. Is it normal or have I missed or misunderstood something ?

Furthermore, because I got a `MethodInvocationMessage`, It seems that I need to serialized the `Channel.Reader` to be able to pass it to the `Hub`. But serializing it feels weird to me.

Could you enlighten me with what I should do with the `Channel.Reader` to be able to achieve that with my protocol ?

I'm currently using aspnet core 3 preview 6, before struggling more with this do you think I should upgrade to preview 7 ?

**Comment by BrennanConroy** [comment]
The specific section of the spec you want is [upload streaming](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md#upload-streaming).

`connection.SendAsync` should make a `InvocationMessage` and attach a "StreamIds" property to the message and it will remove any streams from the sent args. And when sending the `StreamItem`s you'll set the ID to the stream id you used as part of the `InvocationMessage`.

**Comment by alarco-l** [comment]
Thanks for your answer, I will dig into it.

**Comment by alarco-l** [comment]
After more reading, some debug in signalR sources and more tests I finally understand it and found where was my mistake. 

I had a typo when I passed my arguments, instead of passing the `channel.reader`, I passed the `channel`.

Thanks for your time.
