### ISSUE TITLE
[ApiController] Complex type definition for inference rules for data source

### ISSUE THREAD

**Issue by MarkStega** [aspnet/AspNetCore#12608]
### Describe the bug
I have a controller that has a method handling a post with a parameter of type 'EventStoreItem_DD'. The documentation states that [FromBody] is inferred for a complex type. However, I don't understand what defines a complex type. See below for details.

### To Reproduce
1. Using this version of ASP.NET Core '3.0P7'
2. Run this code
`        [HttpPost]
        [Route("CreateEventStoreItem")]
        public async Task<ServiceResult<string>> CreateEventStoreItemAsyncAsync([FromBody] EventStoreItem_DD esi)
        {
`
`
/******************************************************************************
Generated file - Created on 4/2/2019; Do not edit!
******************************************************************************/

using System;

namespace Optimiser.DataTier.DataDefinitions
{
	public class EventStoreItem_DD
	{
		#region Fields

		public int EventStoreItemIdentity;
		public bool IsCommitted;
		public int ItemIdentifier;
		public string ProcessIdentifier;
		public DateTime RecordTime;
		public string SerializedValue;
		public string UserID;

		#endregion

		#region Constructors

		/// <summary>
		/// Initializes a new instance of the EventStoreItem_DD class.
		/// </summary>
		public EventStoreItem_DD()
		{
		}

		/// <summary>
		/// Initializes a new instance of the EventStoreItem_DD class.
		/// </summary>
		public EventStoreItem_DD(bool isCommitted, int itemIdentifier, string processIdentifier, DateTime recordTime, string serializedValue, string userID)
		{
			this.IsCommitted = isCommitted;
			this.ItemIdentifier = itemIdentifier;
			this.ProcessIdentifier = processIdentifier;
			this.RecordTime = recordTime;
			this.SerializedValue = serializedValue;
			this.UserID = userID;
		}

		/// <summary>
		/// Initializes a new instance of the EventStoreItem_DD class.
		/// </summary>
		public EventStoreItem_DD(int eventStoreItemIdentity, bool isCommitted, int itemIdentifier, string processIdentifier, DateTime recordTime, string serializedValue, string userID)
		{
			this.EventStoreItemIdentity = eventStoreItemIdentity;
			this.IsCommitted = isCommitted;
			this.ItemIdentifier = itemIdentifier;
			this.ProcessIdentifier = processIdentifier;
			this.RecordTime = recordTime;
			this.SerializedValue = serializedValue;
			this.UserID = userID;
		}

		#endregion

	}
}
`
3. If the [FromBody] modifier is left off of the method then the EventStoreItem is not properly resolved.

### Expected behavior
I expected that the [FromBody] would not be needed since the item type was a class with multiple public members and constructors. At this point I don't know if the inference is incorrect or if this class somehow doesn't meet the definition of a complex type.

### Additional context
C:\Solutions\TemporarySolutions\LocalStorage>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.400 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Solutions\TemporarySolutions\LocalStorage>

**Comment by pranavkm** [comment]
@MarkStega inference specifically applies if you don't specify the `FromBodyAttribute`. What's more likely is that you're defaulting to `System.Text.Json` based formatters which does not support deserializing to fields as yet. See https://github.com/dotnet/corefx/issues/36505.

You could consider updating your model to use properties instead of fields, or continue using the Newtonsoft.Json based formatters: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support

**Comment by MarkStega** [comment]
I was already using Newtonsoft on both the client & the server side. My issue was that without the [FromBody] being specified that the object was not getting properly deserialized and I believe that the object should have [FromBody] inferred.
