### ISSUE TITLE
Blazor: A SSB BlazorComponent without a surranding tag causes an error

### ISSUE THREAD

**Issue by chanan** [aspnet/AspNetCore#12611]
Using preview7, Creating a SSB tag like this:

```
html {
    color: red;
}
```
**NOTE**: No surrounding tag.

And using it like so in `_Host.cshtml`:
```
<style>@(await Html.RenderComponentAsync<TempStyle>())</style>
```

Then in the console I see the exception:

```
blazor.server.js:15 [2019-07-26T14:43:18.806Z] Error: There was an error applying batch 2.
e.log @ blazor.server.js:15
blazor.server.js:15 [2019-07-26T14:43:18.930Z] Error: System.AggregateException: One or more errors occurred. (Error: No element is currently associated with component 0)
 ---> Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRendererException: Error: No element is currently associated with component 0
   at Microsoft.AspNetCore.Components.Rendering.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
```

And in the DOM:

```
<style><!-- M.A.C.Component:{"circuitId":"CfDJ8J9-PZZd8S9FlzTyQJlGcyCiHmcuninZxWSgnPld91ydhB_D_Sc6sVXfcscoDcuYJVkaipe2vLdEVtr-2zIyzlUfVWkayedHS06-PiNId0sejALo3hyTSzR_fU35S57whK4EUE1lvcAWQUlqcLvFjwD7awJnHvje8v6j75AoME3L","rendererId":"0","componentId":"0"} -->html {
    color: red;
}<!-- M.A.C.Component: 0 --></style>
```

PS: The reason I need to place the tag in the `style` instead of placing the `style in the tag, is that so I can use the tag both in SSB and CSB (for now I will create two tags to fix this problem). I am going to open a feature request regarding the CSB issue and update this one with that link

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chanan.
This is not a scenario we've been trying to support. You may be able to achieve what you want by replacing the `RenderComponentAsync` with `RenderStaticComponentAsync` method.

**Comment by chanan** [comment]
Doing that disables the websocket it looks like.

Are you saying that Blazor won't support two "blazor" apps on the same page? (Like you can with React for example)? (PS it does work in CSB just not SSB)
