### ISSUE TITLE
.NET Core 2.0 in Docker not running on port 8080 as specified

### ISSUE THREAD

**Issue by mleneveut** [aspnet/AspNetCore#12610]
### Describe the bug
I have a Docker image containing a .NET Core 2.0 application, and I try to run it as non root user on port 8080 instead of root on port 80.

I set the `ENV ASPNETCORE_URLS=http://+:8080` (before dotnet-runtime install or after to test its impact) variable but it still starts on port 80 : `Now listening on: http://[::]:80` and as non root user it throws a Permission denied error.

### To Reproduce
Dockerfile : 

```
FROM ubuntu:latest

# Configure web servers to bind to port 8080 when present for non root user
ENV ASPNETCORE_URLS=http://+:8080 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Enable correct mode for dotnet watch (only mode supported in a container)
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    # Skip extraction of XML docs - generally not useful within an image/container - helps performance
    NUGET_XMLDOC_MODE=skip

##### Create user #####
RUN set -x \
 # create dotnet user/group first, to be consistent throughout docker variants
 && addgroup --system --gid 102 dotnet \
 && adduser --system --disabled-login --ingroup dotnet --no-create-home --gecos "dotnet user" --shell /bin/false --uid 102 dotnet 

##### Apt first pass #####

RUN apt-get update \
    && apt-get install -y --no-install-recommends --no-install-suggests \
        curl \
        libc6 \
        libgcc1 \
        libgssapi-krb5-2 \
        libicu60 \
        liblttng-ust0 \
        libssl1.0.0 \
        libstdc++6 \
        zlib1g \
        apt-transport-https \
        wget

##### Install dotnet runtime using APT #####

RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install dotnet-runtime-2.0.7 -y --no-install-recommends --no-install-suggests

COPY ./ app/

WORKDIR app

#USER 102

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

CMD [ "sh", "-c", "dotnet myapp.dll" ]
```

### Expected behavior
An application running on port 8080.

### Additional context
We deploy this app on Azure AKS (Kubernetes 1.12.8).

It works as non root but starts on port 80 instead of 8080.
As non root user with port 80 I get a `Unable to start Kestrel. Permission denied` (normal)

**Comment by mleneveut** [comment]
I tried with `dotnet myapp.dll --server.urls http://0.0.0.0:8080` and it still starts on port 80

**Comment by jkotalik** [comment]
As a first recommendation, 2.0.x went out of support over a year ago. We recommend upgrading to 2.1 where you have long term support. I remember fixing issues related to this between 2.0 and 2.1, so 

To clarify, when you say it starts on port 80, do you mean Kestrel is starting on port 80 inside of the container. From what I can tell, you are exposing port 8080 on the docker container. I guess my question is why do you care which port Kestrel is listening on when you can just map the external port of 8080 to the internal port of 80 that kestrel is listening on.

**Comment by blowdart** [comment]
@jkotalik If you can run it on different ports you don't need to run as an admin users to bind to a low port, so it's a security measure

**Comment by anurse** [comment]
Can you provide a runnable sample that reproduces the issue? If you're manually configuring Kestrel endpoints anywhere the environment variable may be overridden by that.

And I do second @jkotalik 's comment. In general, 2.0 is _out of support_  so I'd strongly recommend updating to 2.1. Unless this issue reproduces on 2.1, we won't be fixing this issue.

**Comment by mleneveut** [comment]
I have the same problem with SDK 2.1.801 and runtime 2.1.12.

I will try to do a sample demo from first-web-api tutorial and reproduce the problem.

**Comment by mleneveut** [comment]
We found a component overwritting the port of our ServiceLauncher, so you were right it is a code problem.

Sorry for the time wasted.

**Comment by anurse** [comment]
@mleneveut No problem! It's not a waste of our time to solve customer problems ;). Any thoughts on what might have helped you diagnose this quicker?

**Comment by mleneveut** [comment]
it's just that the dev team couldn't find what could overwrite the port. So it's just a lack of knowledge on our own code...

**Comment by anurse** [comment]
Ok. If you do think there's something the framework could do to help diagnose this, please let us know!
