### ISSUE TITLE
Blazor: More control on AddComponent

### ISSUE THREAD

**Issue by chanan** [aspnet/AspNetCore#12613]
Using preview7.

Currently, CSB uses:

```
app.AddComponent<App>("app");
```
to insert the `App` control *into* the dom element `app`. This works in almost all cases. However I would like to control a `style` in the head or add a `link` tag in the head.

The way it is now it is very difficult (and in the case of adding `link` it might not possible without `jsInterop`).

For the `style` it is possible to do something like:

```
<style id="myid"></style>
```
and
```
 app.AddComponent<App>("#myid");
```
and in the component not output the `style`. Although, then if the same tag is used in SSB you run into the bug: https://github.com/aspnet/AspNetCore/issues/12611

It would be really great to be able to choose to "overwrite" the dom element instead of insert into the element.

Something like:

```
 app.AddComponent<App>("#myid", overwrite: true); //default to false of course
```

If this is acceptable, I can try to submit a PR

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chanan .
You can have a style-rendering component and simply use that component, to achieve what you want. This is actually applicable to any other section, so it's quite flexible. Given that, we won't be doing the feature you're proposing here.

**Comment by chanan** [comment]
I dont think this works in every case.

For example, lets say I want to add a `link` to the head everytime (unknown how many) the user of my library does: `Library.AddFont("some font name")`

The way it is now it is impossible because this wont work:

```
<head>
<some random tag name><!-- add links here</some random tag name>
</head>
```
Chrome doesnt like that. With `style` it happens to work because `style` is a valid tag
