### ISSUE TITLE
Kestrel doesn't decrement active stream count soon enough

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#12628]
Stress report from HttpClient:

"We seem to not be in agreement with ASP.NET about the number of active streams. We think we are under the MAX_CONCURRENT_STREAMS limit (which is 100), but ASP.NET does not, and it first sends a RST_STREAM with error = REFUSED_STREAM, and then sends a GOAWAY, which eventually leads to the error.

This seems to happen once cancellation starts happening. Previously, we’ve bounced up and down at the limit with no apparent problem. But once a stream is cancelled, and we send a RST_STREAM, things quickly go bad. We remove these streams from our stream count, enabling us to create more streams and send more HEADERS frames. But ASP.NET is sending a RST_STREAM with error REFUSED_STREAM anyway – as if it were not removing these reset streams from the stream count. We send 4 RST_STREAMs (on different streams), and the stream that ends up getting reset from ASP.NET is the stream that would be the 101st open stream if the streams we had reset weren’t getting removed from the count properly. That is, we think it’s the 97th stream, ASP.NET apparently thinks it is the 101st."

Kestrel doesn’t decrement _activeStreamCount immediately upon receiving a reset frame, it waits for the app func to finish.

https://github.com/aspnet/AspNetCore/blob/922fd9cb0dba1196d9ffddaff60963508fd093c7/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L900-L903
https://github.com/aspnet/AspNetCore/blob/922fd9cb0dba1196d9ffddaff60963508fd093c7/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L962-L986

Logically I think CompleteAsync would cause a similar issue where we send EndStream and delay the decrement until the app func unwound.

**Comment by anurse** [comment]
Stress bug. Definitely meets the bar for p9.

**Comment by Tratcher** [comment]
This may come in handy:
ENHANCE_YOUR_CALM (0xb):  The endpoint detected that its peer is
      exhibiting a behavior that might be generating excessive load.

**Comment by geoffkizer** [comment]
Additional info:

After we (HttpClient) receive the RST_STREAM with REFUSED_STREAM, we very quickly also receive GOAWAY with error = STREAM_CLOSED. We don’t appear to be sending any frames on a closed stream, so I’m assuming this is related to the RST_STREAM that ASP.NET is sending. It looks like ASP.NET is treating a DATA frame on the stream that it reset as a protocol error, when it should just be ignored.

**Comment by halter73** [comment]
@geoffkizer That is a known issue with Kestrel's current implementation. I think this is the first time someones complained about it though. I file another issue so we can track it separately.

https://github.com/aspnet/AspNetCore/blob/4aebd29abca80242f5ff9e89e07d4f1b28788a44/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L457-L468
