### ISSUE TITLE
Make it easy to transition from stateful prerendering to -> non-stateful prerendering

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#12630]
I think we need to come up with a strategy or some diagnostics to help people migrate from the preview 7 template to the preview 8 one.

Since we're removing stateful prerendering, there are two changes you need to make in your app:
- In `_Host.cshtml` use `RenderStaticComponentAsync` 
- In `Startup.cs` add a mapping for the component to the `<app>` element

**Before**

```C#
app.UseEndpoints(endpoints =>
{
    endpoints.MapBlazorHub();
    endpoints.MapFallbackToPage("/_Host");
});
```

**After**

```C#
app.UseEndpoints(endpoints =>
{
    endpoints.MapBlazorHub<App>("app");
    endpoints.MapFallbackToPage("/_Host");
});
```

---

The problem is that it's really easy to get the first one of these right - but once you do, the app stops responding. You'll prerender just fine, but no websocket will be opened. There are literally NO diagnostics telling you that you forgot to do the second part of this.

We need to consider whether we have any good ideas to help people understand how to update preview 4->preview 8

**Comment by egil** [comment]
Isnt that a job for [Obsolete Attribute](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=netcore-3.0)? I.e. add it to the non-generic `MapBlazorHub` method.

**Comment by chrdlx** [comment]
And what happens if we don't want to map Blazorhub to a specific component like App inside an app html tag?

Given the current Blazor's limitation of not being able to use <script> tags inside components I had to make several razor pages with specific <head>/<script> since I need different CSS/JS in each one.

In this scenario, I don't have a specific and unique <App> component which the app starts from, 

I guess this is a typical scenario for legacy MVC/Razor pages apps that want to embed interactive Blazor components,  so how we should configure this scenario?

I tried using RenderStaticComponentAsync method and the interactivity inside my razor pages stop working. (Using Preview7)

Regards!!

**Comment by rynowak** [comment]
> d it to the non-generic `MapBlazorHub` method.

Yup. That's an option. At this point we'd just remove the no-args method wholesale.

**Comment by egil** [comment]
Even better @rynowak. Let the compiler error out is a very clear signal to users something's needs changing 😎

**Comment by stavroskasidis** [comment]
Doesn't this break the embeding of components in existing MVC/RazorPages projects? 
How will these be registered in preview-8 ?

**Comment by stavroskasidis** [comment]
You must also consider multiple "entry point" components for existing MVC/Razor pages projects.
For example:

I have a razor page Index.cshtml, and I want to render a component in there
```html
<counter>@(await Html.RenderStaticComponentAsync<Counter>())</counter>
```
while having a second page called Whatever.cshtml, and I want to render a different component in there, like:

```html
<whatever-component>@(await Html.RenderStaticComponentAsync<WhateverComponent>())</whatever-component>
```

Currently in preview 7 everithing works fine when using 
```endpoints.MapBlazorHub

**Comment by rynowak** [comment]
Yes. that will still work.

**Comment by stavroskasidis** [comment]
That is good to hear, because in preview-7 it doesn't work. 

If you try to add multiple entry points in an MVC/Razor Pages app, when you navigate to a page that do not contain one of the custom tags (e.g. `<counter>`), then you get "not found" errors in `blazor.server.js` and it blows up.

**Comment by rynowak** [comment]
OK, we should fix that then. Is there an existing issue for that?

**Comment by stavroskasidis** [comment]
I didn't find anything searching in the repo's issues. I will create an issue, if you want, tomorrow morning (GMT +3 timezone ) ☺

**Comment by rynowak** [comment]
Thanks!

**Comment by stavroskasidis** [comment]
Issue created: https://github.com/aspnet/AspNetCore/issues/12795

😀
