### ISSUE TITLE
Kestrel HTTP/2: Provide grace period to allow client stop sending frames to a stream reset by the server

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#12634]
~~Currently if you call HttpContext.Abort() on a Kestrel HTTP/2 request while the client is in the middle of sending the request body, it will likely cause the entire HTTP/2 connection to be aborted rather than just the stream. This is because there will still likely be unprocessed data frames from the client for that stream, and when Kestrel processes those frames post-stream-abort, it will treat it as a protocol violation.~~

We already have a drain timeout for most streams closed by the server. There could still be some exceptions for streams that we reject early (e.g. b/c we think the client hit the active stream limit)

See:

https://github.com/aspnet/AspNetCore/issues/12628#issuecomment-515606569

**Comment by Tratcher** [comment]
I was looking through the Http2Connection and didn't see an obvious cause for this. Most of the STREAM_CLOSED errors were only sent if we had received a RST or END_STREAM from the client. Calling Abort on the server should not be enough to cause this.

Maybe if you call Abort, let the app func unwind, it gets removed from the collection, and then the new frame comes in?

**Comment by geoffkizer** [comment]
What causes ASP.NET to send RST_STREAM, aside from Abort? Will an exception from a user handler do this?

In particular, will GRPC do something that will cause RST_STREAM, e.g. cancelling a request etc?

cc @marklio

**Comment by halter73** [comment]
> Maybe if you call Abort, let the app func unwind, it gets removed from the collection, and then the new frame comes in?

I was thinking something like this could be the cause.

@geoffkizer debug level server logs from your repro should help us find the proximate cause pretty quickly.

**Comment by geoffkizer** [comment]
Failing the connection here seems pretty bad. With duplex, when you send RST_STREAM, it's quite likely that the client has other frames in flight.

I saw the comment in the original issue re:

```
 // If we couldn't find the stream, it was either alive previously but closed with 
 // END_STREAM or RST_STREAM, or it was implicitly closed when the client opened 
 // a new stream with a higher ID. Per the spec, we should send RST_STREAM if 
 // the stream was closed with RST_STREAM or implicitly, but the spec also says 
 // in http://httpwg.org/specs/rfc7540.html#rfc.section.5.4.1 that 
 //  
 // An endpoint can end a connection at any time. In particular, an endpoint MAY 
 // choose to treat a stream error as a connection error. 
 // 
 // We choose to do that here so we don't have to keep state to track implicitly closed 
 // streams vs. streams closed with END_STREAM or RST_STREAM. 
```

However, this situation isn't a stream error. Per the RFC, section 6.4:

```
   However, after sending the
   RST_STREAM, the sending endpoint MUST be prepared to receive and
   process additional frames sent on the stream that might have been
   sent by the peer prior to the arrival of the RST_STREAM.
```

I understand the desire to not keep track of state for closed streams. In HttpClient, we deal with this by simply ignoring frames on closed (but not idle) streams. This means we don't report some errors that we should, but that's better than reporting errors we shouldn't.

**Comment by geoffkizer** [comment]
The server logs show errors like this:

```
      Connection id "0HLOHLKABK927": HTTP/2 connection error.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (STREAM_CLOSED): The client sent a DATA frame to closed stream ID 213.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessDataFrameAsync(ReadOnlySequence`1& payload)
```

**Comment by halter73** [comment]
> Failing the connection here seems pretty bad. With duplex, when you send RST_STREAM, it's quite likely that the client has other frames in flight.

Completely agreed. The comment that it's OK to treat a stream error as a connection error was a total cop out. I didn't link to that code as an endorsement of the current behavior, just to point out that it had been (somewhat) considered and we chose to do the easy thing initially.

As for the logs, I would to see everything prior to the connection error associated with Connection id "0HLOHLKABK927". If you could link to the full log text, that'd be great.

**Comment by geoffkizer** [comment]
Are you looking to figure out why RST_STREAM was sent? It's getting sent because of #12628.

I can post the logs if you still need them, but it's just in a console window and I'm not sure how much I actually have.

**Comment by halter73** [comment]
Nope. Don't need the logs. That definitely explains the behavior. Thanks.

**Comment by halter73** [comment]
Everything I wanted to address as part of this issue has been addressed surrounding the active stream limit with @jkotalik's PR https://github.com/aspnet/AspNetCore/pull/12704. The only remaining open related issue that I know of is https://github.com/aspnet/AspNetCore/issues/13097.
