### ISSUE TITLE
Adding asp-route-id to a submit button deactivates the asp-action of a form 

### ISSUE THREAD

**Issue by pstricks-fans** [aspnet/AspNetCore#12649]
The working example below

```
<form  asp-action="DeleteConfirmed">
     <input type="submit"  value="Delete"  />                    
</form>

public async Task<IActionResult> Delete(int id)
{
  // intentionally removed for simplicity 
}

[HttpPost]
public async Task<IActionResult> DeleteConfirmed(int id)
{
  // intentionally removed for simplicity 
}
```

no longer works if I add `asp-route-id="1"` as follows.

```
<form asp-action="DeleteConfirmed">
     <input type="submit" asp-route-id="1"  value="Delete"  />                    
</form>

public async Task<IActionResult> Delete(int id)
{
  // intentionally removed for simplicity 
}

[HttpPost]
public async Task<IActionResult> DeleteConfirmed(int id)
{
  // intentionally removed for simplicity 
}
```

To make it work again, I have to explicitly specify `asp-action=DeleteConfirmed` in the submit button as follows

```
<form asp-action="AnyTrivialString">
     <input type="submit" asp-route-id="1"  value="Delete"  asp-action="DeleteConfirmed" />                    
</form>
```
Note: A string assigned to `asp-action` of the form will be overridden by the submit button. As a result, the form `asp-action` becomes trivial.

# Question

Is it a bug or a known feature?

# Minimal Working Example

[See my repo here](https://github.com/pstricks-fans/XYZ)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by pstricks-fans** [comment]
@mkArtakMSFT : Visit [https://github.com/pstricks-fans/XYZ](the minimal example).

**Comment by mkArtakMSFT** [comment]
Thanks @pstricks-fans.
@pranavkm can you please have a look at this? Thanks!

**Comment by pstricks-fans** [comment]
@mkArtakMSFT  and @pranavkm :

I have simplified the project and I found that the presence of `asp-route-id` causes this issue.

**Comment by pstricks-fans** [comment]
I remove the area to shrink the surface area on which you have to probe.

**Comment by pranavkm** [comment]
@pstricks-fans the scenarios you listed make sense:

```
<!-- Working -->
@*<form asp-action="AnyTrivialString">
    <input type="submit" asp-route-id="1" asp-action="DeleteConfirmed" />
</form>*@


<!-- Not Working -->
<form asp-action="DeleteConfirmed">
    <input type="submit" asp-route-id="1" />
</form>
```

When you add an `asp-route-id` on a `submit` button, it independently determines the Action it would route to. It does not work in tandem with the values you specified in `form`. If you're attempting to post to two different actions from a single form, using the "working" sample would be the way go. Alternatively, specifying all the route values on the `form` tag would be the way to go:

```
<form asp-action="DeleteConfirmed" asp-route-id="1">
    <input type="submit" />
</form>
```
