### ISSUE TITLE
Extend InputBase/EditContextFieldClassExtensions to support custom classes

### ISSUE THREAD

**Issue by tstivers1990** [aspnet/AspNetCore#12641]
### Is your feature request related to a problem? Please describe.
I would like to use custom classes for valid/invalid fields in my form.

### Describe the solution you'd like
Components such as `InputText` should accept `ValidClass`, `InvalidClass` and, potentially, `ModifiedClass` parameters.

### Additional context
The default classes don't work with BlazorStrap and require modifying css to add an alias for the default classes.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tstivers1990 .
We plan to address this as part of #8695.
