### ISSUE TITLE
Asp.Net Core 3 Preview 7 Web Api is not working and always returns 404

### ISSUE THREAD

**Issue by whizkidwwe1217** [aspnet/AspNetCore#12648]
**Steps to Reproduce:**

**Prerequisite**: ASP.NET Core 3 Preview 7

1. Run `dotnet new webapi`. This creates a default web api template with WeatherForecastController.
2. Run `dotnet run` or press F5 in VS Code to run in debugger.
![image](https://user-images.githubusercontent.com/1977391/61994973-eb4ffb00-b0b4-11e9-926e-0abf5dfee89d.png)
3. Browse https://localhost:5001 or https://localhost:5001/api/weatherforecast
**Issue**: Returns 404.
![image](https://user-images.githubusercontent.com/1977391/61994940-78468480-b0b4-11e9-87c0-e106d297b05c.png)
![image](https://user-images.githubusercontent.com/1977391/61995043-9660b480-b0b5-11e9-892a-50dec50f8ac3.png)

**Comment by pranavkm** [comment]
Try `https://localhost:5001/weatherforecast` Unless you've configured it, that should be the route for the WeatherForecastController.

**Comment by damienbod** [comment]
The launchUrl in the template is pointing to api/values, maybe this could be corrected.
 
"launchUrl": "api/values",

**Comment by whizkidwwe1217** [comment]
@pranavkm @damienbod  I didn't configure anything. It's a new project so it should work on the first run. I also added a ValuesController and still returning 404. Now, I've decided to send request to a combination of routes and here the result:

`GET http://localhost:5001/api/values` - socket hung up
`GET http://localhost:5000/api/values` - 404 not found
`GET https://localhost:5001/api/values` - 404 not found
`GET https://localhost:5000/api/values` - Produces error **Connection id "0HLOIV3G5PO6N" bad request data: "Invalid request line: '\x16\x03\x01\x00\x94\x01**

So I was thinking that the correct url is `https://localhost:5000` and just having a problem with SSL.
But why does the `https://localhost/5001` returning 404 when it's the one that's been listened to?
![image](https://user-images.githubusercontent.com/1977391/62001047-44ea1100-b119-11e9-831f-6918a21f33ea.png)

Meanwhile, regarding the **Invalid request line** error, I'm 100% sure that I have a development certificate installed. I already ran `dotnet dev-certs https --trust`. I also tried disabling the HTTPS redirection in the Startup class but it still giving me same errors.

Here's my `launchSettings.json`:
```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:23226",
      "sslPort": 44320
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Infrastructure": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}

```
Here's my `Startup` class:
```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
```

ASP.NET Core SDK & Runtime:
```
.NET Core SDK (reflecting any global.json): Version:   3.0.100-preview7-012821
 Commit:    6348f1068a
Runtime Environment: OS Name:     Windows
 OS Version:  10.0.18362 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @whizkidwwe1217.
This has been fixed as part of https://github.com/aspnet/AspNetCore/pull/11753 for the upcoming Preview8 release.
