### ISSUE TITLE
Blazor Issue: parsing double quotes in double quotes after removing @ from attribute value

### ISSUE THREAD

**Issue by AmarjeetBanwait** [aspnet/AspNetCore#12642]
Previously we were using `@` in attribute value and value was pretty colorful, showing information on mouse over and correctly parsing double quotes in double quotes

`@onclick="@(() => UriHelper.NavigateTo("/students/create"))"`

![image 1](https://user-images.githubusercontent.com/4598234/61990992-87660c00-b08d-11e9-85ac-3f7758a201c1.png)

Now after removing `@` from value in Preview 7 it makes complete value white, No mouse over information showing and also error in parsing double quotes in double quotes

![image 2](https://user-images.githubusercontent.com/4598234/61991005-9d73cc80-b08d-11e9-991f-03fdb13e368a.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AmarjeetBanwait .
We're going to address this as part of #11826 .
