### ISSUE TITLE
OnKeyDown event can pass UIKeyboardEventArgs with a null Key property

### ISSUE THREAD

**Issue by jucchytil** [aspnet/AspNetCore#12644]
### Blazor Client Side Preview 7
I have a DynamicElement with an onkeydown event handler. Typing a password into a password input correctly fires the event on each key press and the UIKeyboardEventArgs Key property contains the key pressed. 
**All good there.**

Due to it being a password field, Chrome pops up and allows me to select a previously saved password.  Selecting the password from the list enters the password in the field, but it will fire the OnKeyDown event and pass it a UIKeyboardEventArgs that has a Key property containing a null value. 
**Not so good.** 

- Is this acceptable behavior and we need to test for the Key property containing null or
- Should this event not fire since no keyboard interactions occurred (I clicked a pop-down with my mouse).

Here is the DynamicElement. The Password field is in the @ChildContent RenderFragment.

`<DynamicElement Attributes="@UnknownParameters" style="@styles" TagName="div" class="@classname" tabindex="-1" role="dialog" @onclick="@onclick" @onkeydown="@onEscape">
    <div class="@innerClassname" role="document" @ref="Me" tabindex="-2" style="outline-color:transparent;" >
        <div class="modal-content" @onclick="@dontclick">
            @ChildContent
        </div>
    </div>
</DynamicElement>`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jucchytil.
We simply get the data browser gives us and pass it down. This is not something we have control over.
