### ISSUE TITLE
Build order issue with RCL static assets and TSC generated JS files in wwwroot

### ISSUE THREAD

**Issue by MarkStega** [aspnet/AspNetCore#12646]
### Describe the bug
A build of a Razor Class Library that has static assets in wwwroot may or may not include a JS file that is generated from a Typescript source.

### To Reproduce
1. Using this version of ASP.NET Core '3.0P7'
2. Create a RazorClassLib
3. Add the current Microsoft.Typescript.MSBuild nuget package to the project
4. Place a TS file in wwwroot
5. Build the library
6. There are 3 individuals with identical repositories (@chrissainty, @sql-mistermagoo, and @markStega). On two of the three environments the DLL does not contain the JS content. On the third it does. We have a work-around in place that adds an explicit embedded resource by name in the fashion of a BlazorLib project. The repository is found at https://github.com/Blazored/LocalStorage 

### Expected behavior
I expect the build to be consistent from one developer system to the next given the same version of VS, .NetCore, etc.

### Screenshots
n/a.

### Additional context
VS 16.3.0 Preview 1.0

C:\Solutions\TemporarySolutions\Typeahead>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.400 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Solutions\TemporarySolutions\Typeahead>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MarkStega .
This is quite interesting and unexpected. @javiercn can you please look into this? Thanks!

**Comment by javiercn** [comment]
@MarkStega Could you clarify something real quick?

Seems like you are referring to the old blazor support for static assets (which embedded them into the assembly) we are moving from that model to the new model where the static assets are just part of the package as content.

Which one are you using?

**Comment by MarkStega** [comment]
We are trying to use the new model without the ItemGroup with EmbeddedResources being called out (If you look at the repository the csproj for LocalStorage has those, that is the workaround for the build issue). The problem occurs when that ItemGroup is removed and we are trying to build the dll as a 'new style' RCL.

**Comment by javiercn** [comment]
Ok, just to be clear.

We don't/won't be supporting embedded resources going forward. The content is just a file that we include in the package under staticwebassets and that we copy to the output folder of consuming apps during publish.

Apps need to manually reference the file in their HTML/Razor file through a script tag with `src="_content/{libraryname}/{filepathunderwwwroot}`.

Provided those things, it might be that the TS compilation happens after we compute the static web assets. You can add the following to your project to force typescript compilation to happen before we compute the static web assets.

```xml
  <PropertyGroup>
    <ResolveStaticWebAssetsInputsDependsOn>
      CompileTypeScript;
      $(ResolveStaticWebAssetsInputsDependsOn)
    </ResolveStaticWebAssetsInputsDependsOn>
  </PropertyGroup>
```

**Comment by javiercn** [comment]
I haven't seen this be an issue while packing the project, but I filed an issue for further improvements. My current recommendation is that you use the snippet above and avoid putting the ts file directly in the wwwroot and instead, set the ts output folder to wwwroot.

Closing this as there's no further action to be performed here.

https://github.com/aspnet/AspNetCore/issues/12727 for the mentioned improvements.

**Comment by MarkStega** [comment]
I added the suggested snippet and now the build fails:
`
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\bin\Debug\netstandard2.0\Blazored.LocalStorage.dll' could not be found	BlazorClientSide	C:\Solutions\OHI\LocalStorage\samples\BlazorClientSide\CSC	1	Active
Error	TS1005	Build:'(' expected.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	30	
Error	TS1005	Build:'(' expected.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	31	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	31	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	32	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	32	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	32	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	33	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	34	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	35	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	36	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	37	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	37	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	37	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	38	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	39	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	40	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	41	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	42	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	42	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	42	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	43	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	44	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	45	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	46	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	47	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	47	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	47	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	48	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	49	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	50	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	51	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	52	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	52	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	52	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	53	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	54	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	55	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	56	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	57	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	57	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	57	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	58	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	59	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	60	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	61	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	62	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	62	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	62	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	63	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	64	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	65	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	66	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	67	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	67	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	67	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	68	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	69	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	70	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	71	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	72	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	72	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	72	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	73	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	74	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	75	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	76	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	77	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	77	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	77	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	78	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	79	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	80	
Error	TS2304	Build:Cannot find name 'CompileTypeScript'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	81	
Error	TS2581	Build:Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	82	
Error	TS2365	Build:Operator '<' cannot be applied to types 'boolean' and 'RegExp'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	82	
Error	TS2304	Build:Cannot find name 'ResolveStaticWebAssetsInputsDependsOn'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	82	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	83	
Error	TS1161	Build:Unterminated regular expression literal.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	84	
Error	TS2693	Build:'any' only refers to a type, but is being used as a value here.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	86	
Error	TS2741	Build:Property 'LocalStorage' is missing in type '{}' but required in type 'typeof Blazored'.	Blazored.LocalStorage	C:\Solutions\OHI\LocalStorage\src\Blazored.LocalStorage\wwwroot\blazored-localstorage.ts	96	
`

**Comment by MarkStega** [comment]
If I move the TS file out of wwwroot and add this to the project file
```
  <PropertyGroup>
    <TypeScriptOutDir>wwwroot</TypeScriptOutDir>
  </PropertyGroup>
```
I indeed have the wwwroot directory created during the build and the JS file within. The bad news is that the fancy ResolveStaticWebAssetsInputsDependsOn no longer works and the JS is no longer included in the DLL.

**Comment by javiercn** [comment]
That's likely because you need a target to declare the embedded file that happens after the typescript build.

**Comment by ghidello** [comment]
I have a blazorlib project and a blazor client-side project consuming it. In the blazorlib I
- removed the "old" EmbeddedResouces ItemGroups
- renamed the content folder to wwwroot
- created a msbuild target that calls webpack creating a js file in the wwwroot folder
- added the `ResolveStaticWebAssetsInputsDependsOn` calling the webpack target
- manually added the script tag to the index.html file

The application runs and the nupkg contains the staticwebassets folder with my js file. 
The problem I'm having now is publishing the client-side project: the _content folder is missing. Is it intended to be added automatically or should I configure something?

**Comment by MarkStega** [comment]
> 
> 
> That's likely because you need a target to declare the embedded file that happens after the typescript build.

But I thought that was the point of the 'ResolveStaticAssetsDependOn'? Are you saying I have to explicitly have another msbuild target?
