### ISSUE TITLE
"Microsoft.AspNetCore.Mvc.ViewFeatures.Internal" can not find in dotnet core 3.0.0-preview7-27912-14 

### ISSUE THREAD

**Issue by Benknightdark** [aspnet/AspNetCore#12643]
After I upgrade my dotnet core 2.2 MVC application to 3.0.0-preview7-27912-14, my custom razor html extesion can not find "Microsoft.AspNetCore.Mvc.ViewFeatures.Internal".

![image](https://user-images.githubusercontent.com/5799487/61991167-ee2ff900-b07e-11e9-8362-637908a5b1ed.png)

And, after "Microsoft.AspNetCore.Mvc.ViewFeatures.Internal" can not find , here is some function I can not use , such as ExpressionHelper and ExpressionMetadataProvider.

![image](https://user-images.githubusercontent.com/5799487/61991170-f25c1680-b07e-11e9-85e2-abe50e041360.png)

Here is my example github url : https://github.com/Benknightdark/dotnetcore3v7

**Comment by davidfowl** [comment]
We've moved all pubternal APIs to be truly internal. https://github.com/aspnet/AspNetCore/issues/4932

You'll need to copy that code over to your project from MVC.

cc @pranavkm @rynowak

**Comment by rynowak** [comment]
@pranavkm - did we create a public version of these APIs?

**Comment by pranavkm** [comment]
From https://github.com/aspnet/AspNetCore/issues/8678#issuecomment-475000503

We addressed this particular gap as part of https://github.com/aspnet/Mvc/issues/8724. 3.0 offers a `ModelExpressionProvider` type that's available from DI and combines the 3 APIs that were previously available:

* `ModelExpressionProvider.GetExpressionText<TModel, TValue>(Expression<Func<TModel, TValue>>)`
* `ModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel>, string expression)`
* `ModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel>, Expression<Func<TModel, TValue>> expression)`

The latter two return an instance of `ModelExpression` which is a superset for `ModelExplorer` that `ExpressionMetadataProvider` returns. https://github.com/aspnet/Mvc/issues/8724#issuecomment-439285912 has a suggestion for libraries that need to support different versions of AspNetCore.

**Comment by Benknightdark** [comment]
OK, thanks for your help
