### ISSUE TITLE
Question: How do I make an InputText component use oninput event instead of "onchange" event ?

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#12657]
I have an InputText Component within an EditForm Component, and I want to change the event handlers from "onchange" to "oninput" so that I can display the changes as I type text into the input element. I've tried something like this, but it seems not to be working:

```
<InputText Id="name" Class="form-control" @bind-Value="Model.Name" @bind-Value:event="oninput"></InputText >
```  

Thanks in advance...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @enetstudio .
This is not supported. We'll try to add more clarity here and show how this can be done as part of the following issue: https://github.com/aspnet/AspNetCore.Docs/issues/13541

**Comment by SteveSandersonMS** [comment]
For anyone wondering, you can subclass `InputText` to change how it renders. For example, to make it use the `oninput` event, create `MyInputText.razor` containing:

```razor
@inherits Microsoft.AspNetCore.Components.Forms.InputText
<input @attributes="@AdditionalAttributes" class="@CssClass" @bind="@CurrentValueAsString" @bind:event="oninput" />
```

Now when you use `<MyInputText @bind-Value="@someval" />` it will behave just like `InputText` except it updates on each keystroke.

**Comment by enetstudio** [comment]
Thanks so much for this, maestro!
