### ISSUE TITLE
Unable Resolve Could not Load Type "xxxx " from assembly " xxx"

### ISSUE THREAD

**Issue by Rahulalluri** [aspnet/AspNetCore#12658]
Hi,

I am trying to build a console Application which try's to get the details from tfs, while in my process i am unable to solve below error. Could anyone help me with this.

Thanks In Advance...!!

Error:

**System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.TeamFoundation.Common.UriUtility' from assembly 'Microsoft.TeamFoundation.Common, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Source=Microsoft.TeamFoundation.Client
  StackTrace:   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollectionFactory.GetTeamProjectCollection(String featureRegistryKeyword, Uri uri)
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollectionFactory.GetTeamProjectCollection(Uri uri)
   at Reports.TFSEntity.GetDetails() in C:\Users\xxxx\source\repos\ConnectTfsNew\Program.cs:line 40
   at Reports.Program.Main(String[] args) in C:\Users\xxxx\source\repos\ConnectTfsNew\Program.cs:line 24**

![package](https://user-images.githubusercontent.com/21019767/62000114-646b4480-b0ed-11e9-9198-1df3aa588141.PNG)

**Comment by davidfowl** [comment]
That doesn't look related to ASP.NET Core, maybe try asking on stackoverflow with more appropriate tags? (like tfs)
