### ISSUE TITLE
UriEndpoint should override ToString

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#12656]
It's ToString() should return Uri.ToString()

**Comment by attrib75** [comment]
Hi, first timer here looking at first issues.  Where exactly is the ToString that should be converted?  How do you see?

**Comment by davidfowl** [comment]
This is already done (see https://github.com/aspnet/AspNetCore/pull/12668), @halter73 forgot to close the issue 😄

**Comment by attrib75** [comment]
ok thanks.  Just wondering, how did they see where the code was to change?

**Comment by halter73** [comment]
> ok thanks. Just wondering, how did they see where the code was to change?

You could search the codebase for UriEndPoint.cs. In this particular case, #12668 and #14384 were both earlier attempts to address this issue, so you can take a look for how this was fixed.

**Comment by attrib75** [comment]
Good point.  Thank you!
