### ISSUE TITLE
[Question] How to access a service before building the WebHost?

### ISSUE THREAD

**Issue by TheBlueSky** [aspnet/AspNetCore#12665]
First on all, this is how I am thinking about the solution. I might be completely wrong; if so, please point me to the right direction.

I am building an ASP.NET Core 2.2 application that requires a license to enable certain feature; e.g., logging to Elasticsearch or Splunk, connecting to SQL Server or Postgres, or limiting the number of users. This means that the "Licensing" service should be initialised and ready to be used (resolvable through the container) before registering more logging providers or deciding which database provider to register; moreover, it should be available (through the container) for the rest of the application to use.

The license is a digitally signed text file; i.e., requires some processing to extract the license properties; hence, I do not want to do the work in the constructor. This is what makes it not-straightforward to implement.

Here is an example that demonstrate how I though about it:

Let's assume that we have the following `Program.cs`:

```csharp
public static class Program
{
    public static async Task Main(string[] args)
    {
        await CreateWebHostBuilder(args).Build().RunAsync();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args)
    {
        return WebHost
            .CreateDefaultBuilder(args)
            .ConfigureKestrel(options => { options.AllowSynchronousIO = false; })
            .ConfigureLicensing()
            .ConfigureLogging(ConfigureApplicationLogging)
            .UseStartup<Startup>();
    }

    private static IWebHostBuilder ConfigureLicensing(this IWebHostBuilder hostBuilder)
    {
        return hostBuilder.ConfigureServices(delegate (WebHostBuilderContext context, IServiceCollection services)
        {
            var licensingConfiguration = context.Configuration.GetSection("Licensing");
            services.Configure<LicensingSettings>(licensingConfiguration);
            services.AddSingleton<ILicensingService, LicensingService>();

            // var licensingService = SomehowGet<ILicensingService>();
            // licensingService.Initialize();
        });
    }

    private static void ConfigureApplicationLogging(WebHostBuilderContext context, ILoggingBuilder loggingBuilder)
    {
        var loggingConfiguration = context.Configuration.GetSection("Logging");

        loggingBuilder.AddConfiguration(loggingConfiguration);

        // var licensingService = SomehowGet<ILicensingService>();
        // if (licensingService.EnableAdvancedLogging)
        //     loggingBuilder.AddElasticsearch(loggingConfiguration);
    }
}
```

And the following `LicensingService.cs`:

```csharp
public sealed class LicensingService : ILicensingService
{
    private readonly ILogger<LicensingService> logger;
    private readonly IOptions<LicensingSettings> settings;

    public LicensingService(ILogger<LicensingService> logger, IOptions<LicensingSettings> settings)
    {
        this.logger = logger;
        this.settings = settings;
    }

    public bool EnableAdvancedLogging { get; private set; }
    
    public void Initialize()
    {
        // read and process the license file and set EnableAdvancedLogging to some value
        // if something went wrong; e.g., license file is not available, use logger to log the error
    }
}

```

As demonstrated in the example files, `loggingBuilder.AddElasticsearch(loggingConfiguration)` depends on `ILicensingService.EnableAdvancedLogging` that is set when `ILicensingService.Initialize()` is called.

The main issue is I cannot leave `LicensingService` initialisation to the container, because calling `ILicensingService.Initialize()` is required to make the service ready.

The other issue is, I still need and `ILogger<>` in `LicensingService`, but I will use `LicensingService` to add more logging options later.

**Comment by davidfowl** [comment]
If you need serviced to configure your services then you need 2 dependency injection containers, there's no magic that will allow you to do what you want.

**Comment by TheBlueSky** [comment]
Thanks a lot, @davidfowl.  Could you kindly point me to the documentation/sample that helps me do this?

**Comment by TheBlueSky** [comment]
Anyone else who can point me to the documentation/sample about how to configure and use 2 dependency injection containers?
