### ISSUE TITLE
 How to viewed SSRS Report with .NET Core

### ISSUE THREAD

**Issue by activeAntz** [aspnet/AspNetCore#12666]
I want to make use of the Reporting Services **ReportViewer** control in a .NET Core webAPI. I can't find the good solution for displaying SSRS reports, So how it's implement with .Net core ?

**Comment by davidfowl** [comment]
I suggest following this issue https://github.com/aspnet/AspNetCore/issues/1528

**Comment by blowdart** [comment]
Closing as dupe
