### ISSUE TITLE
[Blazor] How to Moq an InjectAttribute() ?

### ISSUE THREAD

**Issue by turboignited** [aspnet/AspNetCore#12673]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: Here is how I am using InjectAttribute() in a ComponentBase class
```
public class DMSUrlsComponent : ComponentBase
{
        [Inject]
        private DMSDbContext Context { get; set; }
}
```
_The blazor app is server-side_

### Describe the solution you'd like
Per the usual testing of controllers where the dependency is provided on construction. How then would I provide a DMSDbContext dependency to the InjectAttribute above within my unit tests? I have tried a constructor as per the controller way but it complains upon usual startup.

Maybe I could bypass this infrastructure altogether by injecting the DMSDbContext straight into the razor page. However I wish to test the DAL without the concern of razor. Hence the unittests will be solid enough to prevent any misuse.

### Additional context
Maybe I am doing this wrong but I have found soo far that this method works really well for accessing the ef database inside my razor components when it @inherits.

**Comment by rynowak** [comment]
You could make the property public and just set it 😁

**Comment by turboignited** [comment]
> You could make the property public and just set it 😁

But it won't get the injection from my service collecting. Only during unit testing would it work. Thanks for the suggestion, I don't know how I didn't think of that lol

**Comment by turboignited** [comment]
It appears razor is a second class citizen when requesting dependencies be injected. Its not mvc anymore...

**Comment by turboignited** [comment]
> You could make the property public and just set it 😁
> 
> But it won't get the injection from my service collecting. Only during unit testing would it work. Thanks for the suggestion, I don't know how I didn't think of that lol

Following your suggestion my unittest throws out this message
 Message: 
    Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: DMS.Data.DMSDbContext.
    Could not find a parameterless constructor.
  Stack Trace: 
    at ProxyGenerator.CreateClassProxyInstance(Type proxyType, List`1 proxyArguments, Type classToProxy, Object[] constructorArguments)
    at ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
    at CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments)
    at Mock`1.InitializeInstance()
    at Mock`1.OnGetObject()
    at Mock.get_Object()
    at Mock`1.get_Object()

**Comment by turboignited** [comment]
Nevermind, I figured I needed to provide the dbcontext options.
