### ISSUE TITLE
asp.net core 3.0 preview 7 tempdata httpcontext exception

### ISSUE THREAD

**Issue by dotnetshadow** [aspnet/AspNetCore#12675]
When using kestrel `dotnet run` I get a tempdata / httpcontext exception, yet if I use IISExpress it seems to work after upgrading to asp.net core 3.0 preview7

I'm just wondering if I'm missing something?

The project can be run from NToastNotify, samples.
Run  WebApplication1 in IISExpress and it works correctly.
Run WebApplication1 using dotnet cli and it causes an exception after first run 

Issue outlined here
https://github.com/nabinked/NToastNotify/issues/79

Test project to check
Created a branch for .net core 3.0 which you can check out
https://github.com/dotnetshadow/NToastNotify/tree/netcore3.0

Run **samples/WebApplication1**, `use dotnet watch run`
The first time the index page is loaded you will see the toastr, if you F5 (refresh) an exception occurs
If you run the same application under IISExpress it seems to work correctly

**Comment by davidfowl** [comment]
There's a bug in the library. `ITempDataWrapper` is registered as a singleton which means there's a singleton HttpContext for the entire application (https://github.com/nabinked/NToastNotify/blob/a809e8c707e1f31aa6a9d62a1acd33f15246cc92/src/TempDataWrapper.cs#L18). I'm not sure how this ever worked... It's likely something to do with using the first HttpContext captured ever and reusing that object for all subsequent request. That's super dangerous. 

Here's how it fails in the preview8:

![image](https://user-images.githubusercontent.com/95136/62030453-f3ce3180-b199-11e9-8bbe-2adde0c47d33.png)

The HttpContext is re-used for all requests on that exception so it's been disposed... We should look at poisoning the `HttpContext` on the other servers as well.

**Comment by davidfowl** [comment]
Closing

**Comment by dotnetshadow** [comment]
@davidfowl
Cheers for looking into that so it should be registered as a transient?

**Comment by davidfowl** [comment]
@dotnetshadow or do what I did in the PR, store the accessor and access the HttpContext when you need it, see https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md#do-not-store-ihttpcontextaccessorhttpcontext-in-a-field

**Comment by dotnetshadow** [comment]
Great that makes so much sense appreciate your effort
