### ISSUE TITLE
Is it possible to pass value to Blazor page that was called by tag?

### ISSUE THREAD

**Issue by Harardin** [aspnet/AspNetCore#12674]
Is it possible to send a value from Blazor page to page that loads inside of it page.

Something like that:
```
@page "/"
@code
{
 public string value = "some value";
}
<div>
   <Component passvalue="@value"/>
</div>
```
`<Component passvalue="@value"/>` is the another Blazor page that is going to accept the value.

Is it actually possible to do something like this I didn't find info how to do it in the docs.

**Comment by mihaimyh** [comment]
Yes, it is possible using [cascading parameters](https://chrissainty.com/understanding-cascading-values-and-cascading-parameters/).

**Comment by Harardin** [comment]
> Yes, it is possible using [cascading parameters](https://chrissainty.com/understanding-cascading-values-and-cascading-parameters/).

Thanks a lot for your help!!!
