### ISSUE TITLE
"OnAfterRender" is not trigger when clicking browser back button

### ISSUE THREAD

**Issue by mohankumar91** [aspnet/AspNetCore#12688]
#### I have an anchor tag in my razor page to navigate to 'google.com' in the same tab. I have written 'OnAfterRender' in home page for some processing. This event is not fired when click the browser back button after navigating to google page. I have attached my code blocks here

<a href="https://google.com">Google</a>

@code {

    protected override void OnAfterRender()  
    {  
      // Did some Stuff here
    }  
}

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by pranavkm** [comment]
This is effectively a dup of https://github.com/aspnet/AspNetCore/issues/10842. For preview8, we're removing stateful pre-rendering which is the only scenario this appears in.

@mohankumar91 you could remove stateful pre-rendering in your app.

```diff
// Startup.cs
- endpoints.MapBlazorHub();
+ endpoints.MapBlazorHub<App>("app");

// _Host.cshtml
-    <app>@(await Html.RenderComponentAsync<App>())</app>
+    <app></app>
```
