### ISSUE TITLE
Preview 7 Blazor ServerSide Input's @Bind doesn't call the EventCallback<T> 

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#12690]
I've created this simple input generic component

```
@typeparam T

<input @bind="val" />

@code {

    [Parameter]
    public T val { get; set; }

    [Parameter]
    public EventCallback<T> valChanged { get; set; }
}

```

but when used from another parent component like this:
```

@page "/"

<Inp T="@decimal" @bind-val="@val"></Inp>
<div>@val</div>

@code
{
    public decimal val { get; set; }
}
```

The value in the parent UI component doesn't get updated when you update the input textbox,  it seems that the `EventCallback<T> valChanged` is not being called at all.

Regards!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrdlx.
Rather than using the `@bind` on the input element, you should instead directly set the `value` and add the event handler explicitly for `onchange`.

We're going to document how to do this as part of  https://github.com/aspnet/AspNetCore.Docs/issues/13539
