### ISSUE TITLE
SignalR Client TS/JS - Custom Auth Scheme

### ISSUE THREAD

**Issue by benpolinsky** [aspnet/AspNetCore#12696]
### Is your feature request related to a problem? Please describe.
I'm trying to override the authorization header scheme in the JS SignalR client from 'Bearer' to 'SAML'

### Describe the solution you'd like
The ability to specify custom headers, or at the least, a custom scheme when supplying an auth token.

### Additional context
[Seems like this is being requested for the C# Client as well](https://github.com/aspnet/AspNetCore/issues/10576) .

**Comment by anurse** [comment]
We don't have a similar "headers" dictionary in the JS client options because of limitations in WebSockets/Server-Sent Events. In a browser, it is *not possible* to set custom headers on WebSocket or Server-Sent Events connections. This is a limitation in browser APIs. For Bearer auth we do some hacking and put it in the query string, but this has limitations as well (and is not ideal since query strings can be logged on servers).

**Comment by Misiu** [comment]
@benpolinsky @anurse There is a feature request for custom headers: https://github.com/whatwg/html/issues/3062
Please up-vote and comment on this issue so we will get browser developers attention (Microsoft started using Chrome, so there is a chance 🙂)

**Comment by benpolinsky** [comment]
@anurse That makes sense and is well documented. 

I'm suppose I'm referring to the initial handshake that occurs. If I patch the library to send SAML on the initial POST call to /negotiate, I can authenticate with my application. This call returns a bearer token and everything seems to work fine after that. 

Attempting to connect without the bearer token appended to the query string fails as expected, so the route is indeed authenticated.

**Comment by anurse** [comment]
> There is a feature request for custom headers: [whatwg/html#3062](https://github.com/whatwg/html/issues/3062)
> Please up-vote and comment on this issue so we will get browser developers attention

Yep, we're aware of that and working to improve that support. The timeline is vague and even when it's in the spec it will take time to get in to the browsers.

> I'm suppose I'm referring to the initial handshake that occurs. If I patch the library to send SAML on the initial POST call to /negotiate, I can authenticate with my application.

Right, this would work but in SignalR **all requests** must be authenticated, so you'd still hit the issue when doing the follow-up WebSocket request.

> Attempting to connect without the bearer token appended to the query string fails as expected, so the route is indeed authenticated.

If you're using bearer token auth with the query string you need to change your server to accept the token in the query string. See [our docs on the subject](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2#bearer-token-authentication) for more information.

**Comment by benpolinsky** [comment]
@anurse Thanks for this. 

Hopefully one last question can clear things up for me. 

Does the **Azure SignalR service** handle the query string finagling on its own? Because the WS request is going straight to Azure - so I can't imagine I'd have any opportunity to manipulate it.

**Comment by anurse** [comment]
> Does the **Azure SignalR service** handle the query string finagling on its own?

The SignalR client puts the token in the query string. What Azure SignalR **will** do is take the auth claims you sent to your app server in the `/negotiate` request and bundle them up in a token so that come back through when the connection comes through from the SignalR Service.

**Comment by benpolinsky** [comment]
Right, I've noticed that. Okay - thanks,
