### ISSUE TITLE
Publish process not working

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#12709]
I have upgraded to preview 7 and now I'm trying to publish Blazor project but I keep getting this error:

>  Fatal error in IL Linker
> 
>   Unhandled Exception: Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: <unspecified> --->
>   Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0,
>   Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve asse
>   mbly: 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>      at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
>      at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
>      at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
>      at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
>      at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
>      at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies(LinkContext context, XPathNodeIterator iterator)
>      at Mono.Linker.Steps.ResolveFromXmlStep.Process()
>      --- End of inner exception stack trace ---
>      at Mono.Linker.Steps.ResolveFromXmlStep.Process()
>      at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
>      at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
>      at Mono.Linker.Pipeline.Process(LinkContext context)
>      at Mono.Linker.Driver.Run(ILogger customLogger)
>      at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
>      at Mono.Linker.Driver.Main(String[] args)
> 

The publish process was working fine with previous versions of Blazor just fine.

Is there any workaround I can do to make it work for now?

PS. I found this:
1: https://github.com/mono/linker/issues/604
2: https://github.com/dotnet/core/issues/2637

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @stsrki.
You can only reference .Net Standard libraries from your Blazor app. The fact that you see `...MVC.Core` in here is surprising. Why do you have that dependency. Would help to see your project file.

**Comment by stsrki** [comment]
I had it only because I wanted to have the same setup for both **client-side** and for **server-side** Blazor projects. The thing is they both have different applications builder so I had to include both frameworks to make it to work.

```
#if NETSTANDARD2_0

        public static IComponentsApplicationBuilder UseBootstrapProviders( this IComponentsApplicationBuilder app )
        {
            var componentMapper = app.Services.GetRequiredService<IComponentMapper>();

            RegisterComponents( componentMapper );

            return app;
        }

#elif NETCORE3_0

        public static IApplicationBuilder UseBootstrapProviders( this IApplicationBuilder app )
        {
            var componentMapper = app.ApplicationServices.GetRequiredService<IComponentMapper>();

            RegisterComponents( componentMapper );

            return app;
        }

#endif
```

So that later in **Startup.cs** I could do this:

```
app.
    .UseBootstrapProviders()
    .UseFontAwesomeIcons();
```

It worked until preview 7. So now I have removed all of that and added interface to `IServiceProvider` instead.

```
public static IServiceProvider UseBootstrapProviders( this IServiceProvider serviceProvider )
{
    var componentMapper = serviceProvider.GetRequiredService<IComponentMapper>();

    RegisterComponents( componentMapper );

    return serviceProvider;
}
```

But the "problem" is now I have different API for client-side and for server-side projects. Notice the **app.Services** and **app.ApplicationServices**!

**Client-side:**

```
public void Configure( IComponentsApplicationBuilder app )
{
    app.Services
        .UseBootstrapProviders()
        .UseFontAwesomeIcons();

    app.AddComponent<App>( "app" );
}
```

**Server-side:**

```
public void Configure( IApplicationBuilder app, IWebHostEnvironment env )
{
    ...

    app.ApplicationServices
        .UseBootstrapProviders()
        .UseFontAwesomeIcons();

    ...
}
```

It would be great if both `IComponentsApplicationBuilder` and `IApplicationBuilder` could have the same base interface.

If you want to have better look you can see the project files at https://github.com/stsrki/Blazorise

**Comment by mkArtakMSFT** [comment]
That's not going to work. Referencing .Net Core 3.0 app from Blazor client-side project is not a supported scenario.

**Comment by bluntcoder** [comment]
> That's not going to work. Referencing .Net Core 3.0 app from Blazor client-side project is not a supported scenario.

Hi @mkArtakMSFT can you clarify? Isn't the whole point of Blazor is to run on the client, compiled to web assembly and run in the browser? @SteveSandersonMS clearly shows this in his NDC lectures.

**Comment by mkArtakMSFT** [comment]
Sure. But there is difference between Blazor client-side and server-side. For client-side runtime supports .Net Standard 2.0. This will probably change when it will RTM.
