### ISSUE TITLE
Remove IVT from Components.Web to Blazor/Components.Server

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#12713]
Currently, the ComponentsElectron prototype is very hacky, fragile, and extremely hard to upgrade from one version of Blazor to the next. One key reason is that it doesn't have access to some of the internals of `M.A.Components`, so it gets what it wants by private reflection. It doesn't follow the correct integration patterns because it can't, so it just cheats and relies on implementation details of a specific version.

To make it possible to build alternate hosting models for `M.A.Components`, we need to expose the necessary APIs publicly. To prove we are doing this, we should remove the IVT that we currently have from `M.A.Components` to `M.A.Blazor` and `M.A.Components.Server`, and make the relevant hosting APIs public and supported.

There are only a few `internal` APIs used this way by `M.A.Blazor` and `M.A.Components.Server` (e.g., `RenderRegistry.Current.Add` and `Interop.EnableNavigationInterception`).

Or, if we decide we really can't do this right now, we should add an additional IVT to `M.A.Components.Electron` so that hosting model at least can be done cleanly.

**Comment by rynowak** [comment]
Agreed, it would be ideal to get rid of this. I wasn't even aware we had it.

**Comment by NTaylorMullen** [comment]
Hmm, @SteveSandersonMS did this work already happen? `Microsoft.AspNetCore.Components` [doesn't IVT](https://github.com/aspnet/AspNetCore/blob/060d35cd04db1ce06dc816a8ec0faf9fd88d7a29/src/Components/Components/src/Properties/AssemblyInfo.cs) to any product assembly. 

Also `RenderRegistry` is in `Microsoft.AspnetCore.Components.Web` and it utilizes only public types from `Microsoft.AspNetCore.Components` (`Renderer`).

**Comment by SteveSandersonMS** [comment]
@NTaylorMullen Ah, sorry - I misidentified the place where the IVT is. It's in `M.A.Components.Web`, not `M.A.Components`. We still want to eliminate this.

Have you started work on this yet? If not, I have some specific proposals for how we amend the APIs to avoid the IVTs. I'd be happy to take this issue.

**Comment by NTaylorMullen** [comment]
> If not, I have some specific proposals for how we amend the APIs to avoid the IVTs. I'd be happy to take this issue.

I have not gotten past the investigat stage. Re-assigned to you.

**Comment by rynowak** [comment]
If possible/reasonable we should do the same for Ignitor. All of the things we do in ignitor are similar to what another host would do if it were implemented in C#.
