### ISSUE TITLE
The server responded with a status of 405” + “Access to fetch… from origin … has been blocked by CORS policy

### ISSUE THREAD

**Issue by Arash-Sabet** [aspnet/AspNetCore#12715]
### Describe the bug
We have two different asp.net core web api applications employing the following C# code snippet.
```csharp
public static IServiceCollection AddUniversalCORS(this IServiceCollection services)
            => services.AddCors(setupAction => setupAction.AddPolicy("myPolicy", builder =>
                builder
                    .AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()));
```

Also, we have an Angular app that calls both web apis. Making the call to the first web api goes through flawlessly and successfully but the 2nd one fails due to the following error message:

> const url = 'https://localhost:44317/api/logic/save';
>      const request = {
>        method: 'POST',
>        headers: {
>          'Content-Type': 'application/json',
>          Authorization: `Bearer ${this.authService.getToken()}`
>        },
>        body: JSON.stringify(this.myPayload)
>      };

So, why one of the web api calls is successful but the other one fails due to the CORS error message? Really running out of reasons to justify this issue which made us get stuck for quite a while!

We also consulted StackOverflow to find an answer for this issue but none of the answers helped, unfortunately. As a side note, Submitting the same failed POST request in Angular by POSTMAN goes through successfully.

### To Reproduce
1. Using this version of ASP.NET Core 2.2

### Expected behavior
The CORS should not fail and the angular app should be able to succeed in terms of placing the POST request.

**Comment by pranavkm** [comment]
For the client to send a `Authorization` header, your Cors policy must allow it: `builder.AllowCredentials()` . Note that you cannot use `AllowAnyOrigin()` in combination with `AllowCredentials()`. You must specify the client URIs using `WithOrigins`

**Comment by Arash-Sabet** [comment]
@pranavkm Thanks for the reply. If we have to specify the client URIs using ```WithOrigins``` then what happens when the application is deployed to production where clients are connected from unknown URIs. Am I missing a point? Also, why one of the web api's works fine with the said CORS configuration but the other one fails?

/cc @miladghafoori

**Comment by DAllanCarr** [comment]
You can set ``SetIsOriginAllowed()`` if you require open api access from any origin. This will set the required headers. There is an issue outstanding on the Vary header so some suggest WithOrigins is still required as part of CORS setup.

**Comment by Arash-Sabet** [comment]
@DAllanCarr I made the following change but the issue still persists!

```
services.AddCors(setupAction => setupAction.AddPolicy("myPolicy", builder =>
				builder
					.SetIsOriginAllowed(host => true)
					.AllowAnyOrigin()
					.AllowAnyMethod()
					.AllowAnyHeader()));
```

/cc @miladghafoori

**Comment by DAllanCarr** [comment]
You can not use `AllowAnyOrigin`. This has already been mentioned.

**Comment by Arash-Sabet** [comment]
Removed ```AllowAnyOrigin``` but the issue still persists. This is what the server logs:

> Executed endpoint '405 HTTP Method Not Supported'

**Comment by DAllanCarr** [comment]
You will still need set the allowed origin through some mechanism. You can mirror the origin sent on the request but you should be verifying the origin.

`context.Request.Headers.TryGetValue(CorsConstants.Origin, out var origin)`

**Comment by Arash-Sabet** [comment]
@DAllanCarr Are you suggesting to compose a middleware similar to this one https://github.com/aspnet/AspNetCore/issues/4457#issuecomment-465664720 ?

/cc @miladghafoori

**Comment by DAllanCarr** [comment]
@Arash-Sabet I'm thinking check outgoing headers from existing cors policy and adjust through some scheme. But if you want hard code headers then it's a solution.

**Comment by Arash-Sabet** [comment]
@DAllanCarr Not 100% following you. Any examples on your recent comment?

/cc @miladghafoori

**Comment by DAllanCarr** [comment]
The operation is supported. 

https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/CORS/src/Infrastructure/CorsService.cs#L120

Just check the outgoing headers to see if anything else needs to be overridden.
