### ISSUE TITLE
Html select reset [value] if options are async loaded

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/AspNetCore#12719]
select element will always set its value to the first available option if options are loaded async.

`<select class="custom-select" value="@Value" @onchange="OnChange" @attributes="Attributes">
            @foreach (var item in _items)
            {
                <option @key="item.Id" value="@item.Id">@($"{item.Department} ({item.Responsible})")</option>
            }
    }
</select>
@code 
{
    [Parameter] int Value { get; set; }
    [Parameter] EventCallback<int> ValueChanged { get; set; }
    [Parameter(CaptureUnmatchedValues = true)] Dictionary<string, object> Attributes { get; set; } = new Dictionary<string, object>();
   IEnumerable<CostCenterDTO> _items = Enumerable.Empty<CostCenterDTO>();

    protected override async Task OnInitAsync()
    {
        string requestUri = "/api/costcenters";
        _items = await Http.GetJsonAsync<IEnumerable<CostCenterDTO>>(requestUri);
    }

    Task OnChange(UIChangeEventArgs e)
    {
        if (int.TryParse((string)e.Value, out int result) && result > 0)
        {
            return ValueChanged.InvokeAsync(result);
        }
        else
        {
            return Task.CompletedTask;
        }
    }
}
`

select will always set its value back to the first option event the [Value] property is set to another one.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kennywangjin.
This is actually by-design as the loading happens asynchronousely. You can simply wrap the whole `select` block in an if to execute only after the data is loaded.
