### ISSUE TITLE
Solution containing two F# projects, add a new F# file VS crashed.

### ISSUE THREAD

**Issue by YunWeiaa** [aspnet/AspNetCore#12718]
**Version Used**: 
D16.3/29124.183.master(16.3.0) 
**Steps to Reproduce**:
1. Install d16.3 master-29124.183([Release Channel](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/f0b000713df89d96bab19761ec9d911cd7920bfa/dc1fd1d9-1623-61a7-7728-b1a93385ca25%3bchannels/internal/Release/bootstrappers/fixed/Enterprise/vs_Enterprise.exe))
2. Create a new F#  ASP.NET Core web app(Web API) project
3. Add a new f# console app project
4. After the project loads, add a new F# file 

**Expected Behavior**:
After the project loads, add a new F# file Vs can work well.
**Actual Behavior**:
After the project loads, add a new F# file VS crashed.
![image](https://user-images.githubusercontent.com/33921754/61943492-1f042580-afce-11e9-8c0f-80a42ae4a002.png)

Dump file:  "[\\bvtsrv2\Team\Docshare\FsharpWebAPICrashDump\devenv.zip](\\bvtsrv2\Team\Docshare\FsharpWebAPICrashDump\devenv.zip)"

Note: When Solution containing F# and C# projects, add a new F# file VS also crashed.
dotnet --info:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013437​
 Commit:    37fe062a9e​
​
Runtime Environment:​
 OS Name:     Windows​
 OS Version:  10.0.17763​
 OS Platform: Windows​
 RID:         win10-x64​
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013437\​
​
Host (useful for support):​
  Version: 3.0.0-preview8-28373-17​
  Commit:  5d8d5e8661​
​
.NET Core SDKs installed:​
  3.0.100-preview8-013437 [C:\Program Files\dotnet\sdk]​
​
.NET Core runtimes installed:​
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]​
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]​
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]​
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]​
  Microsoft.AspNetCore.App 3.0.0-preview8.19374.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]​
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]​
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]​
  Microsoft.NETCore.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]​
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]​
​
To install additional .NET Core runtimes or SDKs:​
  https://aka.ms/dotnet-download

**Comment by Tratcher** [comment]
Please provide tooling feedback via the feedback too inside visual studio.

**Comment by Pilchie** [comment]
@YunWeiaa is a vendor, and actually https://github.com/dotnet/fsharp would be a good home for this.

**Comment by Pilchie** [comment]
This issue was moved to dotnet/fsharp#7299
