### ISSUE TITLE
Default Blazor Client App fails throwing the build error[Blazor][Appbuilding]

### ISSUE THREAD

**Issue by Anipik** [aspnet/AspNetCore#12712]
I am trying to create an ClientSide Blazor app but I am not even able to build the default blazor app present in the VS

```
C:\Users\anagniho\source\repos\BlazorApp8>dotnet build
Microsoft (R) Build Engine version 16.3.0-preview-19375-05+42c4c1370 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 30.65 ms for C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
obj\Debug\netstandard2.0\RazorDeclaration\Pages\_Imports.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\_Imports.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\FetchData.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\FetchData.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Counter.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Counter.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]

Build FAILED.

obj\Debug\netstandard2.0\RazorDeclaration\Pages\_Imports.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\_Imports.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\FetchData.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\FetchData.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Counter.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Counter.razor.g.cs(51,38): error CS0234: The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [C:\Users\anagniho\source\repos\BlazorApp8\BlazorApp8.csproj]
    0 Warning(s)
    8 Error(s)

Time Elapsed 00:00:01.21

```

Selecting the server app question resolves the issue though. is there anything else that needs to be installed for making it work ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Anipik .
Looks like you have outdated client-side templates. Please reinstall the templates as specified at: https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

**Comment by Anipik** [comment]
@mkArtakMSFT I followed the instructions specified in the linked webpage but I get the same error.
When I create the clientside blazor app the Source shown by VS is ```CLI v5.0.100-alpha-01013627```

**Comment by sukeshchand** [comment]
any update on this issue?

**Comment by PSharp93** [comment]
I am getting the same error using the latest Visual Studio Enterprise Preview with the latest templates preview 8 and latest .Net Core 3.0 preview 8.

**Comment by mkArtakMSFT** [comment]
@Anipik, seems like you've got some nighly builds where the build of the SDK was from `master` branch, which is for .Net Core 5 release. Have you tried uninstalling all the 3.0 SDKs you have and reinstall the official .Net Core 3.0 Preview 8 SDK?

**Comment by lifeisattrip** [comment]
@PSharp93 
I remove all template folders except  
v3.0.100-preview8-013656/
in
C:/Users/xx/.templateengine/dotnetcli/  and it works fine now

**Comment by erikbra** [comment]
Can't get it to work using any of the things mentioned here.
Running on preview 8

**Comment by mkArtakMSFT** [comment]
@erikbra the package `Microsoft.AspNetCore.Components.Browser` was renamed to ``Microsoft.AspNetCore.Components.Web`.

**Comment by PSharp93** [comment]
> @PSharp93
> I remove all template folders except
> v3.0.100-preview8-013656/
> in
> C:/Users/xx/.templateengine/dotnetcli/ and it works fine now

Unfortunately did not work for me, still getting the errors using:
- VS 2019 16.3.0 Preview 2.0
- .NET Core SDK 3.0.100 - preview 8 (x64)
- Blazor Templates v3.0.100-preview8-013656

Visual Studio shows updates for 4 Nuget packages but updating them causes new build errors.

**Comment by PSharp93** [comment]
> > @PSharp93
> > I remove all template folders except
> > v3.0.100-preview8-013656/
> > in
> > C:/Users/xx/.templateengine/dotnetcli/ and it works fine now
> 
> Unfortunately did not work for me, still getting the errors using:
> 
> * VS 2019 16.3.0 Preview 2.0
> * .NET Core SDK 3.0.100 - preview 8 (x64)
> * Blazor Templates v3.0.100-preview8-013656
> 
> Visual Studio shows updates for 4 Nuget packages but updating them causes new build errors.

After deleting all templates and reinstalling the v3.0.100-preview8-013656 template, now only "Blazor Server App" and "Blazor WebAssembly App" is available as project type and those work. Was the mixed project type with client + server side removed?

**Comment by mkArtakMSFT** [comment]
Yes, the templates have been renamed. You can read more about that change in the 'Blazor templates renamed and simplified' section in the [Preview 8 Release Blog Post](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/)

> After deleting all templates and reinstalling the v3.0.100-preview8-013656 template, now only "Blazor Server App" and "Blazor WebAssembly App" is available as project type and those work. Was the mixed project type with client + server side removed?

**Comment by erikbra** [comment]
Created a PR in the blazor-workshop repo to upgrade to 3.0.0-preview8 https://github.com/dotnet-presentations/blazor-workshop/pull/133

**Comment by dazinator** [comment]
I hit this issue when VS 2019 preview 2 was building my solution (dotnet sdk preview 8) which was pinned via a global.json to preview 7 sdk but I didn't actuaally have sdk 7 installed (this 8 was used) and I had blazor preview 7 dependencies in my dependency graph.

Rather than upgrade everything to preview 8 (some dependencies I use aren't compiled and released for preview 8 yet and are still on preview 7) I did this to resolve:

1. Install preview 7 sdk
2. Ensure all dependencies in my application that target blazor are referencing preview 7 (not 6 or less)
3. Add a global.json to my solution to pin to preview 7.
4. run a `dotnet build` - success.
5. I had VS open throughout this, a rebuild doesn't seem to detect sdk 7 was installed and continues to use sdk 8 and fail - restarting VS, and reloading the solution, and then rebuilding - then correctly used sdk 7 and the build succeeded.

I assume this exact same thing can occur each time we go from preview x to preview y - lot of breaking changes at the moment - the build system seems to be very fragile - a bit like goldilocks porridge - everything has to be be "just right" :-)

**Comment by alialiyari** [comment]
replace it with

`Microsoft.AspNetCore.Components.Layouts.LayoutAttribute`

**Comment by GaryTuttle1** [comment]
Every time I replace Microsoft.AspNetCore.Components.LayoutAttribute in my classes with Microsoft.AspNetCore.Components.Layouts.LayoutAttribute, it reverts back to the original code.  How do I stop that?  What am I missing?

**Comment by dazinator** [comment]
Install dotnet sdk 3.0.0 preview 8 and make sure you build with that (check your global.json if you are using one, and do `dotnet --list-sdks` to make sure you have preview 8). I also uninstalled sdk preview 7. Restarted vs. Made sure all my blazor dependencies were targeted against preview 8. ..Once I did all of that my issue with layout attribute went away.

**Comment by Tirumalesh8686** [comment]
The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)

Been getting this error countinously
I have installed dotnet sdk 3.0.0 preview 8 and i also uninstalled sdk preview 7.
But still I have the same problem....

What am I missing??

**Comment by DFPercush** [comment]
Open a Powershell
``` dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview8.19405.7 ```
The current version can be obtained from https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.Templates
 - substitute the latest version after the ``` :: ```
Credit to Tim Corey https://www.youtube.com/watch?v=CaxR4_fP-FA

I don't think this is necessary, but as part of my troubleshooting I'll include it: You may also need to get the latest .net 3.0 SDK from https://dotnet.microsoft.com/download/visual-studio-sdks
However, if you look in project properties in your Blazor app, Application > Target framework, you will see .NET standard 2.0. Other example projects I've seen on github also have this target framework in the .csproj file.
