### ISSUE TITLE
How can I get route attributes dotnet core 3?

### ISSUE THREAD

**Issue by bahmansh** [aspnet/AspNetCore#12725]
I have upgraded dotnet core 2.2 to 3.preview 7. So after that, I can not get custom attributes. context.Resource in version 2.2 was type of AuthorizationFilterContext but in version 3 is type of Microsoft.AspNetCore.Http.Endpoint. Now I couldn't get attributes from endpoint.

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc.Controllers;
    using Microsoft.AspNetCore.Mvc.Filters;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Threading.Tasks;
    
    namespace Gamma.Core.Security
    {
        public abstract class AttributeAuthorizationHandler<TRequirement, TAttribute>
        : AuthorizationHandler<TRequirement> where TRequirement
        : IAuthorizationRequirement where TAttribute : Attribute
        {
            Microsoft.AspNetCore.Http.IHttpContextAccessor _httpContextAccessor = null;
            public AttributeAuthorizationHandler(Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAccessor)
            {
                _httpContextAccessor = httpContextAccessor;
            }
            protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, TRequirement requirement)
            {
                var attributes = new List<TAttribute>();

                var action = (context.Resource as AuthorizationFilterContext)?.ActionDescriptor as ControllerActionDescriptor;
                if (context.Resource is Microsoft.AspNetCore.Http.Endpoint endpoint)
                {
                    //endpoint.
                }

                if (action != null)
                {
                    //attributes.AddRange(GetAttributes(action.ControllerTypeInfo.UnderlyingSystemType));
                    attributes.AddRange(GetAttributes(action.MethodInfo));
                }

                return HandleRequirementAsync(context, requirement, attributes);
            }

            protected abstract Task HandleRequirementAsync(AuthorizationHandlerContext context, TRequirement requirement, IEnumerable<TAttribute> attributes);

            private static IEnumerable<TAttribute> GetAttributes(MemberInfo memberInfo)
            {
                return memberInfo.GetCustomAttributes(typeof(TAttribute), false).Cast<TAttribute>();
            }
        }
    }

**Comment by pranavkm** [comment]
The response here: https://github.com/aspnet/AspNetCore/issues/11075 might likely help.

**Comment by bahmansh** [comment]
I saw it already, But I couldn't use this approach.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @bahmansh.
What specifically didn't work with the referenced approach?

**Comment by bahmansh** [comment]
They didn't get attributes, And attributes aren't available in endpoint.

**Comment by pranavkm** [comment]
@bahmansh as the linked comment suggests, attributes from the action should be available as metadata on the `EndPoint` instance. The `ActionDescriptor` instance is also added metadata to the endpoint. You could get to it if you really must do reflection.

**Comment by bahmansh** [comment]
Can you give me sample code here?

**Comment by pranavkm** [comment]
@bahmansh, doing something like this would likely suffice:

```C#
var endpoint = (Endpoint)context.Resource;
var attributes = endpoint.GetOrderedMetadata<TAttribute>();
```

If you really must get to the `ActionDescriptor`, you could do this:

```C#
var endpoint = (Endpoint)context.Resource;
var action = endpoint.GetMetadata<ControllerActionDescriptor>();
```

**Comment by pranavkm** [comment]
Feel free to reopen if you have further questions.

**Comment by Sebazzz** [comment]
That still does not solve the issue that the routing attributes are not available. `ControllerActionDescriptor` is a singleton shared over the entire application.
