### ISSUE TITLE
Can't disable Intellisense (snippets) for .razor files

### ISSUE THREAD

**Issue by oliversturm** [aspnet/AspNetCore#12726]
When editing a `.razor` file, typing `@c` brings up a list of code snippets in a popup. I want to switch this off for purposes of automated text entry during video recording - I don't want any popups to appear. 

I have disabled all available settings in VS, to no avail. I can't find any settings pertaining to this language editor specifically.

I'm using Visual Studio 16.3.0 preview 1.0 with .NET Core 3.0 Preview 7, working in the context of a Blazor (client-side) project.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @oliversturm.
This is VS tooling issue which you can report using VS Feedback tool from within the VS. Please use that instead and it will land to the right team who owns the area.
