### ISSUE TITLE
[Static web assets] Improve support for typescript

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#12727]
We should better integrate with the existing typescript support in the web SDK by:
* Including the default TS compile target as a dependency of ResolveStaticWebAssetsInputs so that TS files get compiled into JS before computing the inputs.
* Avoid copying TS files inside the wwwroot to the package/app output by default or leaving them in the package but skip copying them to the app oputput.
* We could consider in the future copying the TS files to a different folder inside the package if we have a mechanism to expose the typings to the compiler for proper intellisense in VS.
  * We could simply copy the typings into the right folder for TS to pick them up.

For 3.0 we should likely do 1, so that we ensure the proper output when using typescript, everything else are just enhancements that can be done later if at all.
The recommendation to not include TS files is to not put them in the wwwroot and place them there as a build step performed included in ResolveStaticWebAssetsInputsDependsOn

**Comment by mkArtakMSFT** [comment]
We're meeting with TS folks today to find out what's the right thing to do there.

**Comment by mkArtakMSFT** [comment]
We've met with TS folks today and the decision is the following:
- They will create a new capability for lighting-up the desired VS experience
- We'll add that capability to the RCL project template
//cc @pranavkm, @danroth27

**Comment by mkArtakMSFT** [comment]
@javiercn I've dumped this summary here but am not sure this is what you've filed this bug for.

**Comment by mkArtakMSFT** [comment]
We've decided to enable support for TypeScript compilation for RCL in 3.1.

**Comment by rynowak** [comment]
What does this actually entail? Are we creating a build system for `.ts` in C# projects?

This sounds like a major feature addition that needs to be thought through.

**Comment by javiercn** [comment]
No,

It only means that we'll make sure TypeScriptCompile is a dependency of ResolveStaticWebAssetInputs so that your TS files get compiled before we resolve static web assets inputs.

It's a 1 liner.

Anything else are just questions about how nice we want the experience to be. Like, do we want to do extra things when you are authoring your RCL package with TS or consuming a package that was authored in that way? For example:
* Not copy the .ts files as static web assets when we pack them.
* Produce a d.ts file to include in the package.
* Have the typescript tooling automatically pick-up the definition files from static web assets.

**To be clear, we not doing any of these things above.**

The only thing we are doing is including a capability in the Razor SDK so that when you create a TS file it asks you to install the typescript build package, which brings in everything required to compile typescript at build time and makes the experience on par with the one in Web application projects.

We might also be able to get rid of a couple of imports that we brought in from the web sdk. This experience I'm describing is their recommended approach as per the meeting @mkArtakMSFT and @danroth27 had with the TS folks.

**Comment by rynowak** [comment]
> Anything else are just questions about how nice we want the experience to be. Like, do we want to do extra things when you are authoring your RCL package with TS or consuming a package that was authored in that way? For example:

Right - I don't care about amount of code changes. I care deeply about the set of scenarios it enables and what guidance we're giving people.

If we're getting to parity with the WebSDK then that's important and we have to do it. 

If it's **anything** else at all it needs much more discussion.

**Comment by javiercn** [comment]
We did the appropriate fixes here and the rest is covered by documentation, so I'm closing this issue.
