### ISSUE TITLE
Looking for guidance on copyright for referencing archived project

### ISSUE THREAD

**Issue by BasHamer** [aspnet/AspNetCore#12739]
I'm using the Microsoft.AspNetCore.Proxy project in https://github.com/BasHamer/Slipka 

Initially, I just copied the project I wanted and waited for a package, I kind of missed when the whole thing went away and is now archived. What kind of copyright information should I include for referencing this sort of code?

The only form that the code is distributed is through GitHub (as source) and Docker (as an image); I do not believe I've had to make any changes, but the odds of that are higher as I might have to update it as I update framework versions.

**Comment by Eilon** [comment]
Hi @BasHamer , the Proxy prototype is still available here: https://github.com/aspnet/AspLabs/tree/master/src/Proxy

However, whether it is archived or not does not affect anything regarding licenses, attribution, or copyright. In general with such situations following [the license](https://github.com/aspnet/AspLabs/blob/master/LICENSE.txt), which is the Apache 2.0 license, is fairly easy and straightforward.

Unfortunately, we cannot give out specific advice regarding those matters.

**Comment by BasHamer** [comment]
Thanks, I'll check w/ them

**Comment by Pilchie** [comment]
Closing, as this seems done.
