### ISSUE TITLE
Build with preview 7 SDK while preview 8 installed

### ISSUE THREAD

**Issue by adverst** [aspnet/AspNetCore#12741]
### Describe the bug

Issues building a blazor project when preview 8 SDK installed

Question could be changed to any particular SDK version, that's just my current issue.

I have preview 8 for the SDK installed to work with nightly builds of efcore. For a blazor app I'm tinkering with I'm using some packages that only support to preview 7. So, I have the blazor app referencing preview 7 packages.

When building the blazor project now I have a lot of errors, specifically things like:

```
Error	CS0234	The type or namespace name 'LayoutAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)	
```

The generated razor.g.s files include:

```
    [Microsoft.AspNetCore.Components.LayoutAttribute(typeof(MainLayout))]
```

As opposed to Microsoft.AspNetCore.Components.**Layouts**.LayoutAttribute

I think recent changes have moved layoutattribute back to M.AC.Components (mentioned [here](https://github.com/aspnet/AspNetCore/issues/11610))

What I can't figure out is why it's generating the code that way. I've tried adding global.json to specify which SDK version to use, it's not referencing any preview 8 packages directly. 

### To Reproduce
1. Install preview 7 SDK
2. Install [preview 8 SDK ](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe)
3. create a new blazor app from template (dotnet new blazor)
4. build
4. See error - type or namespace name 'layoutattribute' does not exist in namespace 'Microsoft.AspNetCore.Components'

### Expected behavior
Be able to build with specific version of SDK

### Additional context
Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013601
 Commit:    3f24b9a135

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013601\

Host (useful for support):
  Version: 3.0.0-preview8-28379-02
  Commit:  3a87ac0079

.NET Core SDKs installed:
  2.0.3-servicing-007156 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013601 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19377.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28379-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28379-02 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by rynowak** [comment]
You can use ` global.json` to pin the version of the SDK for a solution. Unfortunately we don't offer compatibility between SDK and runtimes of different previews. This won't be stable until the 3.0 release.

**Comment by adverst** [comment]
> You can use global.json to pin the version of the SDK for a solution

Ah I'd added global.json for the project, not the solution - will retry.

> Unfortunately we don't offer compatibility between SDK and runtimes of different previews

Understood - don't need them working together, just coexisting without issues

**Comment by adverst** [comment]
This works with global.json properly applied at the project level. 

For anyone else that stumbles on this - this didn't work via VS with global.json at the project level (I think VS looks for global.json at the solution level and applies for the entire solution.)

Dotnet build works though - If you have one project in a solution that you want to target a different SDK version you can put a global.json at the project level, then build using dotnet build. This applies it at the project level.
