### ISSUE TITLE
How to route with nested sub-areas in razor pages

### ISSUE THREAD

**Issue by jfcaldeira** [aspnet/AspNetCore#12757]
My structure is

Areas
- Area1
- Area2
  - SubArea1
      - Models
      - Controllers
      - Pages
  - SubArea2
      - Models
      - Controllers
      - Pages

i can't access the sub area pages files if i type /Area/SubArea/Index

**Comment by pranavkm** [comment]
This is not a feature Razor Pages supports out of the box. Area Pages are specifically discovered under paths that look like `/Areas/{AreaName}/Pages/` and changing this to look at additional directories and construct routes from them is non-trivial.

**Comment by jfcaldeira** [comment]
Surely there must be a way to structure a project with a workaround in asp.net-core

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jfcaldeira.
You can do this by implementing your own `IPageRouteModelProvider`. Here how MVC does that for area path: https://github.com/aspnet/AspNetCore/blob/8d46b3a64ea784c95dddeb9d421c7cda6de993a2/src/Mvc/Mvc.RazorPages/src/ApplicationModels/CompiledPageRouteModelProvider.cs#L97
