### ISSUE TITLE
Zscaler blocks some dlls

### ISSUE THREAD

**Issue by jucchytil** [aspnet/AspNetCore#12759]
**Client Side Blazor, Preview 7**
My client slide Blazor app works fine from home.
When testing it from work, some of the dlls download fine but others fail with a 403 Forbidden error. In Chrome Dev Tools, clicking on the dll with the 403, the preview shows a web page generated by Zscaler.
```
We're checking this file for a potential security risk.
The file you attempted to download is being analyzed for your protection. It is not blocked.
The analysis can take up to 10 minutes, depending on the size and type of the file. 
If safe, your file downloads automatically.
Your organization has selected Zscaler to protect you from internet threats.
```
Today there are three dlls being blocked but yesterday there were probably ten so most of the dlls seem to be passing the Zscaler inspection so far.  The ones currently being blocked are 
- mscorlib.dll
- System.Numerics.dll
- System.Web.Services.dll

I will check later today or tomorrow to see if they finally get approved.

**_Unfortunately, this problem makes for a very challenging user and developer experience that is completely outside their control._**

- Can the decision to download dlls be reviewed in light of this problem? I suspect I will not be the only one to experience this as we progress to .Net 5 in November 2020.
- Should some thought be invested in tree-shaking out the unused .net code from all the dlls and compiling what is actually used **_into a single wasm file_**?  

I am guessing that the Javascript communities (Angular, React, Vue) will be transpiling their typescript to wasm soon now that AssemblyScript https://github.com/AssemblyScript/assemblyscript is underway. 

Your thoughts?

**Comment by jucchytil** [comment]
**Update**
All the dlls were able to download later in the day from work and my app loaded and executed fine.

My concern remains as one now must wonder how many customers will encounter similar behavior. This will need to be tracked possibly by application insights to see how much of a problem this is.

This idea
- Should some thought be invested in tree-shaking out the unused .net code from all the dlls and compiling what is actually used into a single wasm file?

was of course to be done during the CI/CD process and only needing to download the single wasm file once.  

Other ideas for .Net 5.0
- after tree-shaking out all the unused code from the dlls and compiling it into a single app.wasm file, minify the mono.wasm file by tree-shaking out its unused code paths. Combine both the app.wasm and minified mono.wasm file into a single wasm file and download that to the browser.
- All CSS files -> single tree-shaken and minified css file
- All JS files-> single tree-shaken and minified js file (if there are any)
- Access browser internals without needing to go through Javascript interop

Sorry if I am stating the obvious. Please ignore if so.

**Newbie Question:** Should these ideas be posted somewhere if they have any value?

**Comment by conficient** [comment]
This problem has occurred before in the early days of client-side Blazor, the issue was migrated to this repo as #5477 

I think the long-term plan is to add AOT pre-compilation of Blazor DLLs to WASM as part of the 'publish' process, so anti-virus products see them as benign.

The short term fix is to create exceptions on the firewall if you can. Server-side Blazor won't suffer this problem of course since no code is ever transferred.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jucchytil.
Glad you've got this working. We will track any further work in this area as part of the referenced issue.
