### ISSUE TITLE
(VS 2019 + Blazor ServerSide + IIS Express) Issues

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#12751]
I've found several issues related to VS 2019 (Release and preview editions), which I'll enumerate:

1) Using VS 2019 with Blazor ServerSide behaves different when debugging the app, compared to Razor Pages & MVC.
   With Razor Pages & MVC,  when you start debugging the APP (F5) , and then you stop...  IIS Express keeps working,  so you can keep browsing your app.
   This doesn't happen with Blazor (Preview 7).
   When you stop debugging,  IIS Express closes so you cannot keep browsing your app.
   I tried disabling "Edit & Continue, ",   also tried disabling "Stop debugger when browser window is closed, close browser when debugging stops".
  But nothing changed that IIS Express stopped working when I stopped the debugger..

1.b)  I've found that changing the Hosting Model to Out Of Process keeps IIS Express running
![image](https://user-images.githubusercontent.com/20750172/62174292-cacfad00-b30f-11e9-86ff-f8487d2c6c55.png)

2) If I use "Out of process" hosting model,  now IIS Express keeps working when I stop debugging but now, I randomly get file locks when trying to compile my project:

![image](https://user-images.githubusercontent.com/20750172/62174332-f18de380-b30f-11e9-917b-f2303b1c5c05.png)

So I haven't found a way to get the same working experience as Razor Pages or MVC, which is:

1) I'm programming my app.
2) I press F5 in VS so the app starts in debug mode, browser opens.
3) I stop debugging, but the browser stays open, and IIS Express doesn't stop.
4) I can now browse my app in the browser because IIS Express is still working.
5) If I want to make a change to my code, I do it, then press F5 in the browser and VS recompiles automatically the just modified project.
6) If I want to debug again, I press F5 launching another browser window (the new browser window is optional, I can reuse the existing one)

Regards!!!!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrdlx.
All the details here are things we don't have control over and are related to VS Tooling. Please use VS Feedback to provide this feedback and it'll be directed to the right team.
