### ISSUE TITLE
How to display related table in blazor using entity frame work

### ISSUE THREAD

**Issue by novfal** [aspnet/AspNetCore#12761]
//Entity framewor core include statement
proj = pron.Proj.Include(p => p.Mod.Select(x => x.ModId)).AsNoTracking().SingleOrDefault(p => p.ProjId == id);
//pron - dbcontext
//client code

<div class="row">
          <div class="col-md-12">
            <div class="form-group">@proj.ProjName</div>
          </div>
<div class="col-md-12">
            <div class="form-group">@proj.Mod.ModName</div>
          </div>
</div>

Value get it from DB (while check in VS through break point) but not displaying

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
