### ISSUE TITLE
What is a valid configuration for hosting an ASP.NET Core SignalR server in an ASP.NET Web Application (.NET Framework) ?

### ISSUE THREAD

**Issue by Legoel** [aspnet/AspNetCore#12767]
Can you provide a valid OWIN configuration sample for hosting an ASP.NET Core SignalR server on an ASP.NET Web Application (.NET Framework) ?

This [documentation page](https://docs.microsoft.com/fr-fr/aspnet/core/signalr/version-differences?view=aspnetcore-2.2) suggests that it is possible.

1. Create an empty ASP.NET Web Application (.NET Framework) in Visual Studio
2. Target the .NET Framework 4.7.2
3. Install the [Microsoft.AspNetCore.SignalR NuGet Package](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR/) 
3. Follow the [ChatHub tutorial](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio)
7. Run the application
8. You get a 'Failed to complete negotiation with the server'

It happens that the route is never applied to the server because the methods of Startup.cs class are never called.

When installing the [Microsoft.Owin.Host.SystemWeb NuGet package](https://www.nuget.org/packages/Microsoft.Owin.Host.SystemWeb/), you have to implement a Configure method with different parameter.

Is that scenario supported and if so what is the right implementation of the Configure method ?

**Comment by anurse** [comment]
> Can you provide a valid OWIN configuration sample for hosting an ASP.NET Core SignalR server on an ASP.NET Web Application (.NET Framework)

This isn't possible. All ASP.NET Core SignalR servers must use ASP.NET Core. Using ASP.NET Core SignalR is not supported with OWIN-based servers.

The table in the linked document refers to the fact that **ASP.NET Core itself** can run on .NET Framework (though in 3.0 this support is no longer present). You still have to create an ASP.NET Core application though.

**Comment by anurse** [comment]
> 1. Create an empty ASP.NET Web Application (.NET Framework) in Visual Studio

This template is creating an ASP.NET 4.x application. The template you need to use is "ASP.NET Core Web Application":

![image](https://user-images.githubusercontent.com/7574/62498538-6f307400-b794-11e9-991d-ff615145ef62.png)

After choosing that you can select ".NET Framework" from the dropdown:

![image](https://user-images.githubusercontent.com/7574/62498551-7ce5f980-b794-11e9-9f3c-bafad9c32d38.png)
