### ISSUE TITLE
Add option to use alternative package managers like Yarn

### ISSUE THREAD

**Issue by Reptarsrage** [aspnet/AspNetCore#12772]
[Original issue here](https://github.com/aspnet/JavaScriptServices/pull/1776)

[Currently npm is hard-coded as the package manager](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/SpaServices.Extensions/src/Npm/NpmScriptRunner.cs#L38). I would like to see this be a configurable option so developers can use alternative package managers such as Yarn.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by Reptarsrage** [comment]
💔

**Comment by ryanbrandenburg** [comment]
Fixed by #12775.
