### ISSUE TITLE
Blazor - make parameters forced public

### ISSUE THREAD

**Issue by harleydk** [aspnet/AspNetCore#12776]
I would like to suggest component parameters with getter and setter qualifications, as per https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lifecycle-methods  should be public, as opposed to:

```
@code {
    [Parameter]
    private bool IsCompleted { get; set; }
}
```

Or ditch the getter and setter altogether. I fully realize it's a matter of my personal preference and this likely won't go further, yet would like to state a case for the 'public' encapsulation referring to a front-facing element, such as these kind of Blazor parameters. The above feels and looks odd, IMPO.

**Comment by stsrki** [comment]
This is going to be covered by #8825

**Comment by harleydk** [comment]
Thank you @stsrki , I did look for a similar topic but not good enough.
