### ISSUE TITLE
OnKeyDownEvent behaving differently from expected for InputText

### ISSUE THREAD

**Issue by Anipik** [aspnet/AspNetCore#12787]
I am trying to print the value of InputText element using onKeyDown event. The code is

```C#
@page "/Key"
@using BlazorApp16.Data;

<EditForm Model="model">   
    <InputText id="name" @bind-Value="@temp" @onkeydown="@printInput" />
    <p2>@nameSubmit</p2>
</EditForm>

@code {
    private ExampleModel model = new ExampleModel();
    private string nameSubmit;
    private string temp;

    private void printInput()
    {
        nameSubmit = temp;
    }

}
```
![temp](https://user-images.githubusercontent.com/10516582/62256408-fd33e580-b3b5-11e9-8017-97a95b59f147.JPG)

The 12 value got printed when I clicked elsewhere on the screen and then typed 1 in the box.

Expected value should be 121

**Comment by SteveSandersonMS** [comment]
See https://github.com/aspnet/AspNetCore/issues/12657#issuecomment-517652423
