### ISSUE TITLE
Issue with migrating from aspnet core 2.0 to 2.2.

### ISSUE THREAD

**Issue by cszczotka** [aspnet/AspNetCore#12797]
In my project based on aspnet core 2.0 is used Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseHeaders. I don't see it in  aspnet core 2.2.  Is it still available in aspnet core 2.2 ? If not what can I use to replace this class ?
Thanks,

**Comment by Eilon** [comment]
BTW all the types in `.Internal` namespaces, such as `Microsoft.AspNetCore.Server.Kestrel.Core.Internal`, are not supported.

**Comment by Tratcher** [comment]
Here's the 2.0 code:
https://github.com/aspnet/KestrelHttpServer/blob/1ca85c72a6970fd63518f003c263fa1bafb8c04b/src/Microsoft.AspNetCore.Server.Kestrel.Core/Internal/Http/FrameResponseHeaders.cs
What part were you using?

**Comment by cszczotka** [comment]
Hi,
In legacy code I have such hack:

PropertyInfo cookiesProperities = responseCookies.GetType().GetProperties(BindingFlags.NonPublic | BindingFlags.Instance).Single(pi => pi.Name == "Headers");

 if (cookiesWithValues is Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseHeaders)
                            {
                                var castedCookies = (Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseHeaders)cookiesWithValues;
...
}

**Comment by Tratcher** [comment]
Why was that ever necessary? The headers can be manipulated directly via HttpContext.Response.Headers.

**Comment by anurse** [comment]
This isn't a supported API so we don't plan to make any changes here.

**Comment by cszczotka** [comment]
Ok. I have rewrited this crappy code using HttpContext.Response.Headers.
