### ISSUE TITLE
Allow (Api)Controllers to be marked internal

### ISSUE THREAD

**Issue by huysentruitw** [aspnet/AspNetCore#12796]
Very often we need to expose a lot more types than needed.

F.e. when a controller requires a service or repository injected through the constructor, the service/repository or at least their interface needs to be marked as `public`. The interface itself being public is not such a big problem, but the need to make things `public` cascades down through every type used in the interface (models, entities, etc.), which you don't want to make public. Even when an API controller returns a mapped viewmodel, you still have to inject a public interface and expose your internal models. Especially, in modular applications or public/shared libraries, this is a nightmare.

Therefore, it would be a good idea if controllers could be made `internal` and just work. Currently, there's no reason why anyone would make a controller internal (except if they do it by accident or because it feels logical), so removing this restriction should not be a breaking change.

I have a prototype working by overriding `ControllerFeatureProvider` by a class where the `IsController` also considers non-public types. While it is working, this causes additional maintenance that one doesn't want in an application.

**Comment by Eilon** [comment]
I think that the current extensibility points, which work for exactly this scenario, are exactly what people should use if they have this requirement. I haven't seen this come up frequently, so I think that MVC has struck the right balance between default behaviors vs. extensibility.

**Comment by huysentruitw** [comment]
The problem is that, if we ship modules with internal controllers, we need to tell the consumer to use a custom `ControllerFeatureProvider`, otherwise the endpoints won't work. If, on the other hand, everything is public, the consumer can start using services that are not intended to be used. Which means, if we change the interface of the service, we can potentially break the unwanted API contract.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @huysentruitw.
The well-established pattern for working with DI is to explose an extension method in your library, which will be the only thing called by consumers, and that'll take care of registering all the necessary services in the DI container. This will also register the `ControllerFeatureProvider`.
Given this, there is not really anything we will change.

**Comment by huysentruitw** [comment]
Fair enough. Injecting `IServiceProvider` in the constructor of the controller might be a better option then.
