### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.SignalR.Client.Core' on .NetFramework 4.7.2

### ISSUE THREAD

**Issue by sankalan** [aspnet/AspNetCore#12804]
I have built a library on .NetStandard 2.0.3 using AspNetCore.SignalR.Client 1.1.0 to communicate with my .Net Core signalR server. While I consume it from a .Net Core console app things run smoothly.
However when I tried to consume that project from a .Net Framework console app it throws this error before building HubConnectionBuilder - "Could not load file or assembly 'Microsoft.AspNetCore.SignalR.Client.Core, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified."
I tried with .NetFramework 4.6.1 and 4.7.2.
Can anyone help me on this?

**Comment by anurse** [comment]
Can you post a runnable sample project that reproduces the issue? That would give us the full context on what dependencies you have and how they are being resolved.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
