### ISSUE TITLE
[Blazor Server Side] Redirecting from /Customers/123ABC to /Customers/456DEF using anchor doesn't work.

### ISSUE THREAD

**Issue by baartho** [aspnet/AspNetCore#12817]
### Describe the bug
If user is on the page `/Customers/123ABC` and he clicks on an anchor on the website that redirects him to  `/Customers/456DEF` - the redirect doesn't work.

The URL changes on the browser but the page doesn't reload, as in: it stays on the `/Customers/123ABC` page.

### To Reproduce
1. Create a page with url /Customers/{userId} - userId being a `string`
`@page "/Customers/{userId}"`

`[Parameter]`
`public string userId{ get; set; }`

2. Add an anchor on the Customers page referencing `/Customers/456DEF`
3. Access `/Customers/123ABC` and click on the anchor
4. You'll see that the redirect didn't work.

### Additional context
Blazor Server Side preview 7
VS 16.3.0 preview 1.0

**Comment by GhostOfTheWind** [comment]
```
@page "/Customers/{userId}"
<hr />
<h3>@name</h3>
<hr />
<a href="Customers/123ABC">123ABC</a>
<hr />
<a href="Customers/456DEF">456DEF</a>

@code {
    [Parameter]
    public string userId { get; set; }
    string name;
    protected override void OnParametersSet()
    {
        if (userId == "123ABC")
        {
            name = "Jon";
        }
        else if (userId == "456DEF")
        {
            name = "Fred";
        }
    }
}
```

**Comment by GhostOfTheWind** [comment]
sort of that?

```
@page "/Customers/{userId}"
<hr />
<h3>@name</h3>
<hr />
<a href="Customers/123ABC">123ABC</a>
<hr />
<a href="Customers/456DEF">456DEF</a>

@code {
    [Parameter]
    public string userId { get; set; }
    string name;
    protected override void OnParametersSet()
    {
        if (userId == "123ABC")
        {
            name = "Jon";
        }
        else if (userId == "456DEF")
        {
            name = "Fred";
        }
    }
}
```

**Comment by baartho** [comment]
Yes. Precisely. Thank you! 

Although I still feel that OnInit / OnInitAsync should be called because this is a page redirect.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @GhostOfTheWind.

Note that we retain the page instance (and hence don't re-invoke OnInit) so that you can do things like animated transitions between the old and new states.
