### ISSUE TITLE
Question: Blazor-How to use localization in the @code section?

### ISSUE THREAD

**Issue by SeppPenner** [aspnet/AspNetCore#12827]
### Question
How can I use the `IStringLocalizer<>` in the `@code` section?

### To Reproduce
1. Using this version of ASP.NET Core '3.0-preview7'
2. Use the example code below in a newly created project, e.g. on the Index.razor page.

### Example code

Index.razor:
```razor
@page "/"
@using  Microsoft.Extensions.Localization;
@inject IStringLocalizer<NavMenu> localizer

<h1>Hello, world!</h1>

Welcome to your new app.

<h1>@L["Hello"]</h1>

@code {
    protected override async Task OnParametersSetAsync()
    {
        var x = localizer["SomeText"];
    }
}
```

Index.de.resx:
https://gist.github.com/SeppPenner/5e8f31f7be7aeb3d3e62defd90f551ff

Or is this a problem with the async Task in general? (Meaning that the dependency injection is only valid after the Task is run?)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SeppPenner .
We've made some improvements in this area in preview8 and this covers using localization in Blazor. Here is the doc article which will be relevant after Preview8 ships: https://github.com/aspnet/AspNetCore.Docs/issues/13436
