### ISSUE TITLE
Is there any way to prevent changing [Parameter] values inside component itself

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/AspNetCore#12824]
Currently, [Parameter] property must be public and read-writable for passing values into component from parent component.

While it's really dangerous to change these [parameter] values inside component itself because these are external-determined and could cause many unexpected behaviors hard to debug.

Is it possible to provide some analysis service that could check that these [parameter] values are readonly inside component and settable outside component.

**Comment by SeppPenner** [comment]
> Currently, [Parameter] property must be public and read-writable for passing values into component from parent component.

Really? I'm using parameters as `private` properties successfully, e.g.:

```razor
@page "/sample/{someId}/"

@code {
[Parameter]
    private string someId { get; set; }
}
```

**Comment by kennywangjin** [comment]
> > Currently, [Parameter] property must be public and read-writable for passing values into component from parent component.
> 
> Really? I'm using parameters as `private` properties successfully, e.g.:
> 
> ```
> @page "/sample/{someId}/"
> 
> @code {
> [Parameter]
>     private string someId { get; set; }
> }
> ```

I haven't tested with private modifier. but event private modifier could not prevent changes from component inside.

**Comment by SeppPenner** [comment]
> I haven't tested with private modifier. but even private modifier could not prevent changes from component inside.

That's true 😄

**Comment by Joe4evr** [comment]
@SeppPenner: That is going to change, though: #12294

**Comment by SeppPenner** [comment]
> @SeppPenner: That is going to change, though: #12294 

Good to know 👍

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
There is nothing preventing one from modifying the parameter values.
