### ISSUE TITLE
Make CheckBox Hidden Input Render Behavior Configurable

### ISSUE THREAD

**Issue by mgbbs** [aspnet/AspNetCore#12833]
Consider forms containing collection editors with rows of data where initial state is generated server-side and rows are dynamically added/removed client-side.  In legacy Mvc, the associated hidden inputs for checkboxes were rendered with each checkbox.  The result in the described scenario is that each row contains all elements associated with the object in the collection.  In Mvc Core, the associated hidden inputs along with the anti-forgery token are generated at the end of the containing form.  Because of this, you have to manually handle the hidden inputs with each row addition/removal.

We can set the option to generate hidden inputs inline with their associated checkboxes:

```
<form>
    ViewContext.FormContext.CanRenderAtEndOfForm = false;
    ...
</form>
```

For a large application, this is tedious to set on every form and clutters the markup.  It would be nice to have this as a configurable option.  I recommend adding it to `Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelperOptions` so that it can be configured in Startup.cs via `services.Configure<MvcViewOptions>()`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mgbbs.
Would you like to send us a PR for this? We'll happily consider it.

**Comment by mgbbs** [comment]
Thanks @mkArtakMSFT, sure I'll work on this.  I have a few possible approaches in mind:

1. Simple `bool` in `HtmlHelperOptions` that will carry over to `FormContext.CanRenderAtEndOfForm`
  **Pros**: Simplest and least number of changes.
  **Cons**: From a user perspective, it's not really clear or self-explanatory what this option does.  Also, this could impact more than just checkboxes if future items depend on the flag.

2. Enum `CheckBoxHiddenRenderMode`: `EndOfForm` (default), `Inline`.
  **Pros**: More granular control of checkbox behavior and it becomes clear to the user what the option is for.
  **Cons**: Bit more code change required, but not much.  Will not affect the `FormContext.CanRenderAtEndOfForm` flag, so we would need to rename this issue.

3. Enum `CheckBoxHiddenRenderMode`: `EndOfForm` (default), `Inline`, or `None`.
  Same pros/cons as option (2) but adds the ability to completely turn off the rendering of hidden inputs for checkboxes.  I know this has been in MVC since the beginning so it may require significantly more due diligence.  I think there's a valid reason for not wanting the additional input fields and removing them won't affect model binding or validation since the key simply won't be there and the model value will default to false (unless otherwise specified).

Personally I like option (3) but I'd like to hear your thoughts on it.

**Comment by mkArtakMSFT** [comment]
@pranavkm can you please advice on the best approach here? Thanks.

**Comment by mgbbs** [comment]
@pranavkm this is what I had in mind https://github.com/mgbbs/AspNetCore/commit/53933233b6744a1e9424092040b66d343a476247

If you agree with the approach I'll commit unit tests and create a pull request.  Thanks.

**Comment by pranavkm** [comment]
@mgbbs seems reasonable. I'm ok with it being an enum type, but is there a reason to have the `None` option? Also /cc @dougbu in case you have some thoughts or suggestions.

**Comment by mgbbs** [comment]
@pranavkm This will give users the option to generate a lone checkbox input without having to write a custom helper.  Over the years, many people have had the question of how to "turn off" the feature of generating a hidden input that ensures a value is always posted.  Here are just a few random posts where people explain the reasoning behind the feature and other people are giving workarounds.

https://stackoverflow.com/questions/2697299/asp-net-mvc-why-is-html-checkbox-generating-an-additional-hidden-input/2697311

https://stackoverflow.com/questions/2860940/why-does-the-checkboxfor-render-an-additional-input-tag-and-how-can-i-get-the-v

https://stackoverflow.com/questions/26837272/how-to-avoid-html-checkboxfor-generating-hidden-field

**Comment by pranavkm** [comment]
Thanks, this is really useful information. Your code changes look like they're on the right track. @dougbu ping in case you'd like to suggest changes before @mgbbs starts working on a PR.
