### ISSUE TITLE
Blazor simulate back button

### ISSUE THREAD

**Issue by Yen** [aspnet/AspNetCore#12838]
I am trying to build a "confirm action" page and would to have a cancel button that _goes back_ in the navigation stack rather than pushing a new redirect to the previous page. This is because if someone was to then go back in the browser it will redirect them back to the confirm.

I don't understand how, if possible, to use IUriHelper to perform this action.

I would like some way of using the IUriHelper to "navigate back" rather than forwards to a new page, this is how to have correct back button semantics with native back buttons. Thanks.

_(I am using blazor server side)_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Yen .
You can use JSInterop to directly call the `window.back()` method.

**Comment by Yen** [comment]
Thanks for responding. I understand I can manually call the browser history API to perform this action, but this is not really correct due to this being a work around for an implementation detail. (IUriHelper is the interface for which the implementation could or could not use the browser history API.)

Is there no intent to support popping the navigation stack in blazor?

**Comment by mkArtakMSFT** [comment]
We don't have any immediate plans for that:
> Is there no intent to support popping the navigation stack in blazor?
