### ISSUE TITLE
Increase the value of cancelTimeoutInMinutes in AZDO

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#12848]
See: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops#timeouts

Right now when a build hits a timeout ([like this one](https://dev.azure.com/dnceng/public/_build/results?buildId=292924)) - you get a limited amount of time to upload all of the build artifacts until things are **really** cancelled.

Upping this time to something larger than 5 minutes would give us a chance to see logs, results, and artifacts from a build that times out.

**Comment by JunTaoLuo** [comment]
Thanks for taking care of this one!
