### ISSUE TITLE
Enable TypeScript gold-bar experience in Razor Class Libraries

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#12840]
Today, if you add a new .ts file to an ASp.NET Core web project, a popup bar shows up in VS suggesting to add support for TypeScript. This experience is missing for Razor Class Library projects, as these reference Razor SDK.

We will get a new capability defined by the TypeScript folks and we will then apply that to the Razor SDK.

** marking this as `blocked` as we're waiting for the new capability to be defined.

**Comment by rynowak** [comment]
How/why is this a problem today? Do they have hardcoded logic based on the web sdk?

**Comment by pranavkm** [comment]
They base it off the AspNetCoreWeb capability. The plan was to introduce a new capability on their end and for us to light it up via the RazorSDK.
