### ISSUE TITLE
Model Binding in controller methods is case insensitive.

### ISSUE THREAD

**Issue by fiseni** [aspnet/AspNetCore#12844]
Platform: ASP.NET Core 2.2.0

Matching the parameters case insensitively in controller methods, leads to unexpected results, especially in POST requests. Let's have example model as following

```
public class Customer
{
	public int ID { get; set; }
	public string Name { get; set; }
}
```
In order to simplify the example, if we scaffold CustomersController, we will get the following content for Edit[Post] method

```
// POST: Customers/Edit/5
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] Customer customer)
{
	if (id != customer.ID)
	{
		return NotFound();
	}

	if (ModelState.IsValid)
	{
		// Some code here
	}
	return View(customer);
}
```
Presumably  the "id" value should be filled from "Route data", while "ID" from "Form fields". But both values are filled with the value from "Form fields" (I assume there is a match since it's case insensitive). In this scenario the following code portion has no meaning.
```
if (id != customer.ID)
{
	return NotFound();
}
```
Quick workaround would be never to name properties in models as "ID", or to change the "id" variable name in route mapping definition  "{controller=Home}/{action=Index}/{id?}"

PS. If this is by design (for whatever reasons), I apologize for my ignorance.

**Comment by pranavkm** [comment]
The docs for model binding briefly states this: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2#sources. In the absence of any indication from the user, properties and fields are bound in case-insensitive manner over the following sources in order:

* Form POST
* Route
* Query string

You can restrict the sources a property or field is bound from using `From*` attributes. In this case, applying `[FromRoute]` on the `int id` parameter should get it to bind from the route as you'd expected.

**Comment by fiseni** [comment]
Thank you @pranavkm for your answer.

I'm aware of the corresponding rules, but the above code is not production code. I just posted it as an example, and it's generated/scaffolded code. 
I totally agree, bounding properties in case-insensitive manner is probably the right choice, otherwise we would have even more issues with API requests (I assume in .net Core model binding infrastructure is common for MVC and API controllers).
I just think it would be great if we are more explicit in the documentation regarding the possible downsides of this rule in MVC controllers. There are cases where this can lead to over-posting issues. Let's imagine the following case
```
public class Order
{
	public int ID { get; set; }
	public decimal Price { get; set; }
	public decimal price { get; set; }
}

public async Task<IActionResult> Edit([Bind("ID,Price,price")] Order order)
{
}
```
Even though I can't think of a reason why somebody would name the properties this way, in the context of c# language there is no any constraint for not doing so. If we test it, we would get really surprising results.

**Comment by pranavkm** [comment]
You can use view models to bind a subset of properties. It's certainly our recommendation to avoid over-posting. 

> I just think it would be great if we are more explicit in the documentation regarding the possible downsides of this rule in MVC controllers.

I'm not entirely sure what you mean by this. [The documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2#example) already points out that model binding in MVC is case-insensitive. But if you'd like to add to the document, we'd be happy to accept it.
