### ISSUE TITLE
WebAssemblyConsoleLogger doesn't honor the IsEnabled check

### ISSUE THREAD

**Issue by ghidello** [aspnet/AspNetCore#12859]
### Describe the bug
Using the default logger for Blazor client-side projects (WebAssemblyConsoleLogger) the logs with every Level are shown even if the IsEnabled method is true only for Warning and Error

### To Reproduce
1. Create a Blazor client-side project
2. Inject an ILogger in a component
3. Add a log using the LogDebug extension method
4. The log appears in the console

### Expected behavior
Only the logs with a Level that satisfies the IsEnabled method should be shown

### Additional context
I guess that the `Log` method in the `WebAssemblyConsoleLogger` should be changed from

```c#
public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
	var formattedMessage = formatter(state, exception);
	Console.WriteLine($"[{logLevel}] {formattedMessage}");
}
```
to

```c#
public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
	if (!IsEnabled(logLevel)) return;
	var formattedMessage = formatter(state, exception);
	Console.WriteLine($"[{logLevel}] {formattedMessage}");
}
```

On a side note, do you think it would be worth to add a way for configuring the minimum log level during the service configuration and maybe at runtime or do you recommend to use a third party implementation for these features?

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ghidello.
Would you like to send us a PR for this? We'll happily consider it.

**Comment by ghidello** [comment]
@mkArtakMSFT sure! I'll use this issue for the easy fix and make a pull request for it. I'll open a new issue for the LogLevel configuration if I figure out a good solution.

**Comment by SteveSandersonMS** [comment]
Fixed with https://github.com/aspnet/AspNetCore/pull/12928
