### ISSUE TITLE
Cannot connect to mssql 2014, 2016 from docker, only 2017

### ISSUE THREAD

**Issue by concretor91** [aspnet/AspNetCore#12858]
I create empty web api project and try run it in docker container and connect to mssql server.

```c#
using (var connection = new SqlConnection("Server=ip,port;Database=master;User=test;Password=test"))
{
       connection.Open();
}
```
 When connecting to the sql server 2014,2016, the application hangs endlessly. If i run without docker its works fine. If i install sql express 2017 connection from docker works fine. Why? How to fix it?

**Comment by Pilchie** [comment]
@ajcvickers ?

**Comment by ajcvickers** [comment]
@concretor91 Looks like you could be hitting https://github.com/dotnet/SqlClient/issues/43 If not, then please file a new issue at https://github.com/dotnet/SqlClient/issues and include a small, runnable project/solution or complete code listing.

**Comment by concretor91** [comment]
@ajcvickers 
Perhaps this is the same problem. I keep experimenting. I install last service pack on sql 2014(sql 2014 installed long ago), but no effect, still endless hangs. I completely remove sql 2014 and install. Now instead of freezing it gives an error: 
OpenSslCryptographicException: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol

Again, this is a clean template. I only change method of controller. I try .net core 2.2, 3.9 preview 7.
```c#
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            using (var connection = new SqlConnection("Server=ip,port;Database=master;User=user;Password=password"))
            {
                connection.Open();
            }

            return new string[] { "value1", "value2" };
        }
```
