### ISSUE TITLE
Razor Component "Retry" UI is hidden behind Bootstrap fixed-top navbar when connection is lost

### ISSUE THREAD

**Issue by smadgerano** [aspnet/AspNetCore#12867]
I am running a mix of Razor Pages and Razor Components.
I have set my Bootstrap 4 Navbar css class as "fixed-top".
When the SignalR connection to the server is lost, the "Retry" UI is partially hidden behind the Navbar making it difficult, if not impossible to read.
Suggested fix, center the UI on both vertical and horizontal axes.
I would have a go at this myslef, or even just add a custom class in for it but I'm still a noob and trying to figure it out :)

**Comment by smadgerano** [comment]
So I found the css tag to change it if anybody needs it #components-reconnect-modal

I've added some padding to the top which has helped, but I feel this will be a problem for other people too so I think the default should be changed.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @smadgerano.
Would you like to send us a PR with the proposed fix? We'll happily consider it.

**Comment by smadgerano** [comment]
I've never done a pull request, and have no idea about running tests or creating them. I can try to pick some stuff up, but might take a while lol

**Comment by mkArtakMSFT** [comment]
Absolutely no problem - there is no urgency in regards to this issue, as it doesn't meet the bar for us to tackle immediately. We'll consider it for the 5.0 release.

**Comment by scrossen** [comment]
this code creates a modal box using css to handle reconnect / reload


    <div class="modal fadecomponents-reconnect-hide " id="components-reconnect-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">

        
        <div class="modal-dialog modal-lg" role="document">


            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title w-100" id="myModalLabel">Lost Connection</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="reconnect-wait">
                        Connection lost -- please wait, attempting to reconnect
                    </div>
                    
                </div>
                <div class="modal-footer reconnect-button">
                    <input type="button" value="Reconnect" onclick="Reconnect()" />
                    <button type="button" class="btn btn-secondary btn-sm" onclick="location.reload()" >Refresh Page</button>
                </div>
            </div>
        </div>
    </div>
