### ISSUE TITLE
System.Management does not work with .net core 3.0 prev 7

### ISSUE THREAD

**Issue by HolyOne** [aspnet/AspNetCore#12860]
I have an existing class using System.Management code which works.

I created a .net core 3 web app (I run on visual studio with Administrator permisions)
I get marshal error when I try to connect WMI at the first line.

This is the line I call
`   DNS = new ManagementScope (@"\\localhost\root\MicrosoftDNS") ;`

This is the error I get
**System.Runtime.InteropServices.MarshalDirectiveException:** 'Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attribute.'

I do not use any win32 dll call or out parameter in my code so I thought it must be an internal error on System.Management or .net core 3 preview

![image](https://user-images.githubusercontent.com/293601/62422290-bf3a0880-b6b8-11e9-9680-fca506719139.png)

Thank you

**Comment by HolyOne** [comment]
I just tried latest prerelease ( 4.6.0-preview7.19362.9) and it seems it passes this line

**Comment by Pilchie** [comment]
This issue was moved to dotnet/corefx#40048
