### ISSUE TITLE
installation package failing 

### ISSUE THREAD

**Issue by Prog-ss** [aspnet/AspNetCore#12861]

**Comment by Prog-ss** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/16938#issue-476542533
![XmlFormatter issue](https://user-images.githubusercontent.com/40576690/62423012-5c0c9e00-b6d9-11e9-8a36-e91f8c7bfbca.png)

**Comment by Pilchie** [comment]
How is this issue different than the one above?  Can you include a description of the issue you are seeing?

**Comment by Pilchie** [comment]
Closing due to lack of response.
