### ISSUE TITLE
JsRuntime is too restrictive

### ISSUE THREAD

**Issue by genifycom** [aspnet/AspNetCore#12865]
### Is your feature request related to a problem? Please describe.
.razor file allow view and code to be wrapped in a component but not the JavaScript part.
In addition, only one method exists for JsRuntime and this presumes calling a global JS function

### Describe the solution you'd like
Since we cannot touch the DOM directly in server side Blazor, we have to continue to use CSS and JavaScript. We can add <style> tags to the .razor file but we cannot add <script> tags.

This means that we cannot access everything on one razor page. Several possible solutions exist.
1. Allow us to put <script> tags in the @code or an additional static section in this page
2. Allow us to pass JavaScript to JsRuntime e.g. await JsRuntime.InvokeJSAsync<string>(@"console.log('Hello'); console.log('I am here');");
3. Allow us to indicate what DOM items to change in C# and then pass the appropriate instructions (tricky I know).

The idea of a component means being able to specify all elements of the component. JavaScript in server-side Blazor breaks this by requiring us to create with global JS functions that are not part of the .razor definition. This is a regression even on .cshtml where we can specify <style> tags and <script> tags.

**Comment by glararan** [comment]
I had not exactly same issue but there is shared idea.

Look at my issue: #12604 

Also in some issue is mentioned that `<script>` is not allowed in .razor by design.

**Comment by genifycom** [comment]
Excellent. JS injection would be great.

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @genifycom.
This question comes up from time to time and this is not an area that we planned to implement anything for. We will tackle the documenting work as part of https://github.com/aspnet/AspNetCore/issues/12880

**Comment by genifycom** [comment]
I am not happy about this. I believe that Server Side Blazor will be much bigger than you expect.

I have long regarded that being able to run a headless web browser on a server, determine the changes necessary to broadcast and then broadcasting the diff is a very effective way to manage dynamic web sites for a large number of users.

This is very much inline with the Server Side Blazor approach.

**Comment by genifycom** [comment]
The problem here is that since a script cannot be inserted in a .razor page, we have to go back to a .cshtml page.

This means that we have to put ALL script references in something like _Host.cshtml

You cannot use the shared razor layouts, so that whole component structure seems to be compromised.

Having being building out an app now, even with a dozen pages this quickly becomes extremely difficult. I am just trying something simple e.g. changing css variables in the razor page.

Maybe I am missing something?

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @genifycom.
/cc @danroth27, here is more feedback on this topic.
