### ISSUE TITLE
Blazor Server Side .NET Core publishing issues

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#12876]
I've publishing different server side Blazor apps in Windows Server 2008 R2 servers with random dll/pdb file locks that even stay after stopping the application pools.

I publish with these settings to a local folder, and then copy the files to the server:

![image](https://user-images.githubusercontent.com/20750172/62470483-e9e79800-b770-11e9-9675-ccd9f212f895.png)

The **ONLY** method that worked so far is to enter the servers and stop the pools before overwriting the files with the updated blazor solution.

If I go to the recommended **app_offline.htm** route....  file locks happen randomly and can stay locked for minutes,  in the worst case having to shutdown the server instance to unlock the files and be able to copy the new ones.

I'm using latest Blazor Preview7, but this has been happening since the first preview.

I come from the old asp.net world, and this was an easy copy/paste procedure, no file locks or similar issues.  Am I missing something?  Thanks & regards!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrdlx.
@shirhatti can you please look into this? Seems like this is app_offline related.

**Comment by shirhatti** [comment]
> I publish with these settings to a local folder, and then copy the files to the server

This approach will not work as files are expected to be locked by .NET Core.

> If I go to the recommended app_offline.htm route.... file locks happen randomly and can stay locked for minutes, in the worst case having to shutdown the server instance to unlock the files and be able to copy the new ones.

That is not the expected behavior. Can you provide more details on how this is failing? What dll/pdb files are locked? Can you share your deploy logs?

The best way for us to diagnose this issue is if you can share your MSBuild bin logs.
You can use this [VS extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) to capture logs.

Or if you're running from the commandline, try invoking MSBuild as shown below

```powershell
msbuild /restore /p:RuntimeIdentifier=win-x86 /p:DeployOnBuild=true /p:PublishProfile=publish.pubxml /bl
```

cc @vijayrkn @jkotalik

**Comment by chrdlx** [comment]
Hello @shirhatti , I don't publish using VisualStudio.  this is my workflow:

1) Publish to folder C:\Solution
2) Stop AppPool in web server 
3) Copy files from C:\Solution to \\publish\Solution (Server path)
4) Start AppPool in web server 

This works fine everytime....   if I don't stop AppPools and instead I put the app_offline.htm in the server path,  then the issues start....

So I don't have deploy logs,  and using msbuild or visualstudio to deploy is not an option sadly... but I don't think it will change much since its a file copying procedure too... isn't it?

**---**
This can be reproduced with the preview 7 blazor server side default template,  try to publish it with the 4 steps I described before.  It's a Windows Server 2008 R2.  
Sadly, I don't know if I can add more details to the issue since I'm new to .NET Core....  and I just migrated from .net framework.

Is there a way to start/stop application pools remotely, maybe a doc you can point to?
 So in the meanwhile if this is not fixed, I don't have to connect via remote desktop to manage the app pools... 

Thanks & regards!

**Comment by anurse** [comment]
Are all the files in your app locked or are there specific files that are locked? Also, have you modified any IIS settings like shutdown timeout? Also, I assume you're using the IIS in-proc deployment model (which is the default)?

**Comment by chrdlx** [comment]
@anurse  
-Just the .dll and the .pdb files.
-The IIS's application pool has been created with default settings.
-InProc hosting

Tomorrow I'll talk with the IT department since they're copying the files.... maybe they're producing this issue somehow....  I'll keep you posted...

Thanks & Regards

**Comment by anurse** [comment]
> -Just the .dll and the .pdb files.

**All** DLLs and PDBs?

**Comment by chrdlx** [comment]
> > -Just the .dll and the .pdb files.
> 
> **All** DLLs and PDBs?

After searching for this issue I've found

https://github.com/aspnet/AspNetCore/issues/3793

Which is my same issue as mine, experienced by many people, and not fixed from 2016.

**Comment by shirhatti** [comment]
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open the issue.
