### ISSUE TITLE
3.0 preview7 Can't get UseExceptionHandler middleware to work

### ISSUE THREAD

**Issue by miezis** [aspnet/AspNetCore#12870]
### Describe the bug
When using 3.0 preview7 and using UseExceptionHandler middleware - Exception is rethrown and 500 with empty body is returned (doesn't enter the code defined by errorHandlingPath). Tested locally with template project. Also tested with 2.2 - this works fine (thought maybe I don't follow documentation correctly).

### To Reproduce
1. .NET SDK `3.0.100-preview7-012821`
2. Using this version of ASP.NET Core `3.0.0-preview7.19365.7`
3. Add `app.UseExceptionHandler("/Home/Error");` to your Startup.cs.
4. Implement simple view under `/Home/Error`
5. Throw exception from some endpoint to test this.
6. See that 500 with empty response body is returned and your error handling endpoint is not called at all.

### Expected behavior
`/Home/Error` should be called and defined view should be returned when unhandled exception is thrown in code.

### Additional context
`dotnet --info`
```.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Also, this middleware is only documented for 2.2 in official docs, but code for it exists in 3.0 preview, so maybe the usage differs?

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/AspNetCore/issues/11233 which has been fixed for preview8

**Comment by Tratcher** [comment]
Mitigation:
https://github.com/aspnet/AspNetCore/issues/11233#issuecomment-514023799

**Comment by miezis** [comment]
It works, thanks. Will use the proposed code until preview8 is released.
