### ISSUE TITLE
Requests with Encoded headers are not forwarding to kestrel listener.

### ISSUE THREAD

**Issue by pamedasa** [aspnet/AspNetCore#12878]
### Describe the bug
We are working in migrating web project from ASP.Net to ASP.Net core. Post the migration, sorted out all the issues and reached to a good state where all the code path is working like before except Non-ASCII support in the request headers. Client is passing request with request headers contains special characters (Non-ASCII) and requests are landing into IIS on server side which acts as proxy server. But from IIS, request is not forwarding to kestrel and in logs found that 400 status code was written. Why even after IIS encoded the non-ASCII characters, kestrel is rejecting the requests.

Actual Request Header (Referer) sent client:
https://sea-bvtd2-rrp1-t56tl.backup.ext.trafficmanager.net/subscriptions/160f30fd-a1ad-4cca-b710-914d79a18787/resourceGroups/RegionalRPResourceGroupネットワーク ABC (xyz)_.,-/validateMoveResources?api-version=2018-12-01

Request header (Referer) reached to IIS:
https://sea-bvtd2-rrp1-t56tl.backup.ext.trafficmanager.net/subscriptions/23f0d3b9-0272-4533-a37f-eac1e597e755/resourceGroups/RegionalRPResourceGroup%20kaneta%C3%8D%C3%83%C3%88%C3%AF%C3%BC%C2%AF%20ABC%20(xyz)_.,-/validateMoveResources?api-version=2018-12-01 

**Listener Creation Code:**
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            var builder = WebHost.CreateDefaultBuilder(args)
                .UseContentRoot(Directory.GetCurrentDirectory());
            builder.UseKestrel(options =>
            {
                options.Limits.MinRequestBodyDataRate = null;
                options.Limits.MinResponseDataRate = null;
                options.Limits.MaxRequestBodySize = 268435456;
                options.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(5);
            })
            .UseIISIntegration()
            .UseStartup<Startup>();
            return builder;
        }
### Expected behavior
Requests should reach to kestrel for processing. If there is not support, then there should a way to drop the encoded characters.

### Additional context
PS C:\> dotnet --info

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [D:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [D:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [D:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Tratcher** [comment]
This is a known issue with IIS out-of-proc mode. It doesn't properly encode the headers when forwarding them.

Can you use IIS in-proc mode? It doesn't have this limitation.

**Comment by pamedasa** [comment]
IIS In-proc won’t work for us because we are using asp.net core application targeting .net full framework. We are migrating from asp.net to asp.net core. To enable in-proc, application should target >.Net core 2.0 and it involves lot of code re-factoring across lot of code bases . Our idea is that refactor web role to host behind IIS for PaaS v1( Cloud services) and use the same code for SF.

Could you please suggest is there any way to achieve this?

~Pavan

**Comment by Tratcher** [comment]
Looking closer at your example, are you sure your Referer header is the problem?
`https://sea-bvtd2-rrp1-t56tl.backup.ext.trafficmanager.net/subscriptions/23f0d3b9-0272-4533-a37f-eac1e597e755/resourceGroups/RegionalRPResourceGroup%20kaneta%C3%8D%C3%83%C3%88%C3%AF%C3%BC%C2%AF%20ABC%20(xyz)_.,-/validateMoveResources?api-version=2018-12-01`
is a correctly encoded value.

You can confirm what bytes are being received by Kestrel using the connection logger:
https://github.com/aspnet/AspNetCore/blob/c809b669b98a559bb2aea5fdf0b455652a834e2d/src/Servers/Kestrel/samples/SampleApp/Startup.cs#L108-L112
Make sure to turn your log levels up to Trace.

**Comment by pamedasa** [comment]
Small correction. Traces found in the IIS logs is the response returned by kestrel. I have tried the way you suggested but getting byte data when we make a call directly to kestrel. if we host behind IIS, byte data traces are not logging into logs. I am trying out to get as much data as I can to debug this further. Will update the thread.

**Comment by pamedasa** [comment]
I followed the step you suggested but didn't log much information (about data received). If we poll to kestrel directly then only we are getting data.If I pass the request to kestrel listener with the same encoded header, request is passing through. 

One finding is that, client is already encoding with UTF-8 charset and sending the request. I am clueless about why kestrel is returning 400 (Bad Request). what's the recommendation you are suggesting for the folks who are facing similar issue?

**Comment by Tratcher** [comment]
`EF FC` in that sequence is not utf-8, it is a bad request. HttpWebRequest doesn't encode request headers, it truncates all chars to bytes.

**Comment by pamedasa** [comment]
What would be the next steps to workaround this? this means other clients like HTTP client dropping these characters while encoding before sending the request. Any suggestion/workaround will be a very grateful help to us as this is the last leg blocking us :)

**Comment by Tratcher** [comment]
Honestly you don't have a lot of good options, Unicode and HTTP don't mix well, it's never been supported by the spec. If you control the client then you need to make sure they pre-encode all values. If corrupt data reaches the server it's already too late.

**Comment by pamedasa** [comment]
We don't have option to control the clients. Currently we are hosting the asp.net core/kestrel behind IIS. Request will be reached to kestrel through IIS. Is it possible to pre-encode at IIS level and then forward to kestrel?

**Comment by Tratcher** [comment]
No, there's no known workaround for this in the IIS reverse proxy scenario. You'd need to move to IIS in-proc.

**Comment by pamedasa** [comment]
Oops. As ours is a migration scenario and moving to In-Proc is a months effort  because we should re-write all our code base to support .Net core to leverage In-Proc hosting model.
From the MSDN docus, projects targeting .net full framework should use Out-of-Process only. Just to know, what's the big difference in kestrel in In-Proc vs Out-of-Proc to support request with non-ascii characters.

**Comment by Tratcher** [comment]
In-proc doesn't use kestrel or a reverse proxy, so it bypasses the proxy component that has the encoding problems.

**Comment by pamedasa** [comment]
Thanks. 
Are the any plans to support In-proc for applications targeting full framework?
Also, any plans from kestrel side to add support for non-ascii?

**Comment by Tratcher** [comment]
> Thanks.
> Are the any plans to support In-proc for applications targeting full framework?

No, and ASP.NET Core 3.0 and later will no longer support full framework at all.

> Also, any plans from kestrel side to add support for non-ascii?

Kestrel already supports UTF-8. We don't plan to support other encodings. Nor have we found a way to address the encoding issue in the reverse proxy.

**Comment by anurse** [comment]
Using the in-proc model in 2.2 and 3.0 or using Kestrel directly (with no IIS proxy in front) is the suggested solution here, when you are able to migrate to it. We don't have plans to revisit this encoding logic in the out-of-proc mode for IIS.

**Comment by pamedasa** [comment]
" **using Kestrel directly (with no IIS proxy in front) is the suggested solution here**"
this will be the issue right now having right? Traces which reported earlier in this thread were captured when Kestrel used directly.

using Kestrel directly is not also not the right one because it's clearly called out that Kestrel don't support non-ascii characters.

**Comment by Tratcher** [comment]
Kestrel supports Utf-8 encoded headers. It blocks requests with corrupted encodings.

The trace in https://github.com/aspnet/AspNetCore/issues/12878#issuecomment-518641829 shows corrupted encoding, HttpWebRequest isn't generating a valid encoding as explained in https://github.com/aspnet/AspNetCore/issues/12878#issuecomment-518711029.

**Comment by pamedasa** [comment]
Yes exactly. Until client doesn't generate valid encoded headers it will continue fail even though kestrel is public facing to accept the requests. So can I say - "Kestrel would be the suggested solution if headers generated with UTF-8 format."
