### ISSUE TITLE
Installation Package failing - Microsoft.AspNetCore.Formatter.XML - version 2.2.0 For Microsoft.ASPNetCore.App2.1.1 

### ISSUE THREAD

**Issue by Prog-ss** [aspnet/AspNetCore#12881]
Installation Package failing - Microsoft.AspNetCore.Formatter.XML  - version 2.2.0 

Error Message - 

Microsoft.ASPNetCore.App2.1.1 requires Microsoft.AspNetCore.Mvc.Formatter.Xml

![XmlFormatter issue](https://user-images.githubusercontent.com/40576690/62422972-bbb67980-b6d8-11e9-9549-e3d9682bcb8f.png)

**Comment by pranavkm** [comment]
You likely need the the 2.1.3 version for a 2.1 targeting application - https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Formatters.Xml/2.1.3
