### ISSUE TITLE
"[BindNever] attribute Can only be applied to model properties, not to method parameters. Prevents model binding from setting a model's property." Serious warning not said.

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore#12884]
**[Hard translation]**

@1257960069 commented on [Sat Aug 03 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/170)

If the client submits data in Json format, the BindRequiredAttribute and BindNeverAttribute attribute classes will not play any role. This is because the model is created directly by Json.Net deserialization. The MVC framework does not know where the value of the attribute comes from. .

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [ASP.NET Core 中的模型绑定](https://docs.microsoft.com/zh-cn/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---

@srvbpigh commented on [Mon Aug 05 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/170#issuecomment-517914014)

你好，@1257960069
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Moved by mistake, please ignore

**Comment by CeciAc** [comment]
Hi team, 
I'm reopening the issue after checking with our linguist. 
The user is reporting missing important information in the documentation about that element
best regards

**Comment by tdykstra** [comment]
This information is already made clear in the doc, in a Note box in the **Attributes for complex type targets** section:

> These attributes affect model binding when posted form data is the source of values. They do not affect input formatters, which process posted JSON and XML request bodies. Input formatters are explained later in this article.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
