### ISSUE TITLE
AspNetCore.Authentication.Certificate only available for version 3.0.0

### ISSUE THREAD

**Issue by hforeste** [aspnet/AspNetCore#12888]
I noticed that the `Microsoft.AspNetCore.Authentication.Certificate` is only available for 3.0.0 and I was wondering if there is any plan to have it on older versions of .NET Core.

**Comment by blowdart** [comment]
No. You can get the code it was based on as a [third party package](https://github.com/blowdart/idunno.Authentication), although there are some differences in events

**Comment by blowdart** [comment]
Closing as answered
