### ISSUE TITLE
Need ability to disable ProblemDetails from being defined as the return type

### ISSUE THREAD

**Issue by CreepyGnome** [aspnet/AspNetCore#12893]
The problem is that ProblemDetails seems to be defined as the default type to SOME not all error response codes, and seems to be related to ProducesResponseType and that telling Swagger that the return type is ProblemDetails which it is not.  It's a lie and I don't want it to be true either.

An error code with option string in the body has been good enough and still is, not sure why we are being forced (inconsistently) to use ProblemDetails. I want a way to disable it or have it disabled by default.

I will take even a hacky way right now to disable this as it is polluting my Swagger documentation and lying to a consumer who may want to implement a call to an API and expect something to be returned on SOME errors status codes (not all which is odd) and it will not and they will get a JSON serialization error when they try to convert a plain string to an instance of ProblemDetails.

### Describe the solution you'd like
Well, something like this would be fine if enabled by default:
services.DisableProblemDetails();

OR if disabled by default:
services.AddProblemDetails();
...
app.UseProblemDetails();

**Comment by pranavkm** [comment]
There are two features that cause MVC to auto-generate `ProblemDetails` when using an `ApiController`. The docs have examples for configuring these features along with turning them off:

* Bad error responses: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#disable-automatic-400
* Client errors: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#disable-problemdetails-response

These features are specifically targeted at controllers attributed with `ApiController` attribute which is meant to be a more opinionated way of writing controllers. You could consider removing the attribute it to stop these features from lighting up.

**Comment by CreepyGnome** [comment]
Those are really bad docs, which is why I probably couldn't find them.

The first one "Disable automatic 400" doesn't sound like anything to do with disabling ProblemDetails being set as the default type for 4xx errors. Setting SuppressModelStateInvalidFilter  to true seems very counter-intuitive to this issue.

The second one "Disable ProblemDetails response" while the title and sentence following maps disabling ProblemDetails with the counter-intuitive flag SuppressMapClientErrors.

I did just the second one that specifically called out disabling ProblemDetails responses, and it worked. 

My initial Google searches were around ProblemDetails asp.net core and combined with Swagger and or ProducesResponseType. I find an issue in Swagger that said ASP.net core 2.2 added this functionality and refers people to the what's new in ASP.net core 2.2 which explains the changes but not how to disable ProblemDetails.  Even after knowing more and just searching for Disable  ProblemDetails that page with the answer is the 5th suggestion, not the first. 

Just feels like this is a breaking change based on some of the other research on people complaining about this, none of which though talk about disabling it, unfortunately. Surprised this would be forced as enabled with the method to disable it being obscured behind odd option property name in an area that moves may not have used before.

I am very grateful for the quick response to the doc about this issue, as it has worked around the problem with the Swagger docs.

I am just said that I wasted some much time trying to figure out why this is happening, then how to stop it from happening, and eventually having to ask for a feature to disable it to get an answer that it already exists basically to something that should either not be enabled by default or should be more clear how to disable using the same terms that a person would use when they first encounter the issue.

**Comment by CreepyGnome** [comment]
One minor issue to the fix/workaround I just realized is that this is a FLAG that I have to set on all my microservices now. All of which have been generalized Addxxx and Usexxx extension methods to make sure they all get the basics setups consistent. This one since it is based off adding to the IMvcBuilder makes that generalization more difficult, but not impossible, just not standard to how things are typically done in this area for Startup.

**Comment by khellang** [comment]
> Those are really bad docs, which is why I probably couldn't find them.

This is just a reminder that the docs are open source and that you can propose additional information to make it easier for the next person to find 😄

**Comment by CreepyGnome** [comment]
@khellang I am fully aware of that point about the docs. Here is why I am sick of hearing stuff like that in relation to open source maintained by large corporations like Microsoft.  This isn't an issue with that comment for small projects or projects that are not created or maintained by a large corporation or collective of corporations.

- It is in Microsoft's best interest to have the best docs they can, they are doing better than they ever have but still fall short of being where they need to be
- The docs have to be good enough to be found via Google in order to know they are bad to know where to update them If they are bad and cannot be found or don't even exist you don't know where they go or what to fix
- It is not my job to fix Microsoft's issues, as I have a day job that keeps me pretty busy and if I took on all of Microsoft's issues that impacted me I would never get any sleep
