### ISSUE TITLE
[Perf] Endpoint routing allocations

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#12897]
Since the fix handling the exceptions, the allocations are much more important.

![image](https://user-images.githubusercontent.com/1165805/62499466-a9e7db80-b797-11e9-8aae-228fdc1d887b.png)

/cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
Definitely curious as to why things are making it onto the loh...

**Comment by davidfowl** [comment]
State machines...

**Comment by NTaylorMullen** [comment]
> State machines...

Into the loh though?

**Comment by davidfowl** [comment]
I didn't look at that. I'm just looking at the allocation rate.

**Comment by DamianEdwards** [comment]
5.0.0? Shouldn't we aiming to fix (or at least understand) this before 3.0 final, or at least for 3.1?

**Comment by rynowak** [comment]
The fix would be to revert the recent change that introduced the state machine and add `Endpoint` to the list of things that we unset in `HttpContext.Clear()`

**Comment by davidfowl** [comment]
I would support that change.

**Comment by DamianEdwards** [comment]
Great. Is that a change we can look to make for 3.0 or 3.1? This regression was pretty severe.

**Comment by NTaylorMullen** [comment]
> Great. Is that a change we can look to make for 3.0 or 3.1? This regression was pretty severe.

I have time, i'll just take this on for this release.

**Comment by NTaylorMullen** [comment]
@mkArtakMSFT this impacts all scenarios, Mvc, Blazor etc. I imagine I still need to go through ask mode though? Yay nay?

**Comment by rynowak** [comment]
Yes.

**Comment by sebastienros** [comment]
Tagging @Pilchie

**Comment by Pilchie** [comment]
Yes, fill out the ask mode template and add the ask-mode label when a fix is ready.

**Comment by NTaylorMullen** [comment]
kk will do
