### ISSUE TITLE
Fatal error in IL Linker:Failed to resolve Microsoft.Extensions.Logging.Abstractions.Internal.NullScope

### ISSUE THREAD

**Issue by ar0311** [aspnet/AspNetCore#12894]
### Describe the bug
Possibly related to #10651 

When compiling a Blazor Client app in a Hosted Blazor solution with references to Identity in the Shared project, compilation fails. In my case, using RavenDB.Identity in the Shared project (referenced by the Client project) pulls in the Identity references.

Manually adding a PackageReference in the Client project csproj to Microsoft.Extensions.Logging results in successful compilation

### To Reproduce
1. Using preview 7
2. Repro git repository [here](https://github.com/ar0311/blazor_IL_error) 
3. Run dotnet restore && dotnet run (server project)
4. See error output

Example: 

_Fatal error in IL Linker
  Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.IDisposable Microsoft.Extensions.Logging.Logger::BeginScope(TState)' in assembly: 'Microsoft.Extensions.Logging.dll'
   ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.Extensions.Logging.Abstractions.Internal.NullScope Microsoft.Extensions.Logging.Abstractions.Internal.NullScope::get_Instance()
     at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
     at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
     at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()_

### Expected behavior
Successful compilation.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not an area we control.
If you still have this problem, feel free to report it on the https://github.com/mono/mono repo.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#16063
