### ISSUE TITLE
Razor components static assets is casesentive when served by docker (linux)

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/AspNetCore#12906]
I am building a Razor Component library with name OfficeAutomation.Components and i reference its static assets in my main project via link **__content/officeautomation.components/components.js**.
It works when I debug projects on local IIS Express. But it failed when I published projects to docker with nginx reverse proxy. 
Only when I changed link to **__content/OfficeAutomation.Components/components.js** (casesensitive), then link works again.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kennywangjin.
The behavior you're observing is by-design. This depends on the behavior of the underlying file system.
