### ISSUE TITLE
Blazor - @font-face not valid in script tab on razor page

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore#12904]
The @font-face CSS command doesn't work on a razor page inside a script tag.

```
<style>
    @font-face {
         font-family: myFirstFont;
         src: url(sansation_light.woff);
    }
</style>
```

**Comment by campersau** [comment]
You can try to escape the `@` with `@@font-face` as described here: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0#razor-syntax

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @campersau!

**Comment by VR-Architect** [comment]
That worked. Thanks @campersau
