### ISSUE TITLE
[Blazor] switch easily between client and server side - possibility - roadmap

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#12916]
Hi Guys, i actually develop a server side blazor app but i want to release client side of my app (because i reuse a lot of existing code containing static access on repository class, so i can't use the server-side on production. And i really need debug my app, so i keep the server-side for development)

i find old article on this, but nothing with the actual version. (actually i'm on preview 7)

Event if it's not possible now, it is something planned by the team in the roadmap ? (i will not release before beginning 2020 so i have the time, but it's really a functionnalty i need)

thanks for your help !

Julien

**Comment by matheusjulio96** [comment]
What do you mean by 'old article'? There's BlazorDualMode project by Dan Roth [https://github.com/danroth27/BlazorDualMode](url) which use Preview6, and seems to work with Preview7 too.

**Comment by julienGrd** [comment]
great ! I wasn't find this project when i looked for something like that.

I will try it, thanks !
