### ISSUE TITLE
Can't find IHttpContextAccessor

### ISSUE THREAD

**Issue by brunosantosrhsenso** [aspnet/AspNetCore#12912]
The interface IHttpContextAccessor seems to have been removed from 3.0-Preview and I cant find out what's been replaced by. Can someone point me to the right way to keep up to date with this kind of breaking change? I'm currently upgrading a 2.2 app to 3.0.

Thanks.

**Comment by Eilon** [comment]
The `IHttpContextAccessor` type should be alive and well: https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Abstractions/src/IHttpContextAccessor.cs

Can you show what code you have, what your project file looks like, and what error you're seeing?

**Comment by ryhled** [comment]
@Eilon This package only seems available up to v2.2. Not 3.0 preview. So unable to reference this from a class library for example.

**Comment by davidfowl** [comment]
It’s no longer in a package but is part of the ASP.NET Core shared framework.

**Comment by nportelli** [comment]
So now we have to add the ASP.NET Core to projects that need IHttpContextAccessor?  Or change those projects to be <Project Sdk="Microsoft.NET.Sdk.Web"> instead of <Project Sdk="Microsoft.NET.Sdk">?

**Comment by davidfowl** [comment]
Yes you need to add a framework reference to asp.net core to get the IHttpContextAccessor

**Comment by nportelli** [comment]
Well I thought it would be easy to figure out what was meant by "add a framework reference to asp.net core", but I'm afraid I failed at finding anything helpful.  Could you explain for nimwits like myself?

**Comment by pranavkm** [comment]
@nportelli see https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#framework-reference
