### ISSUE TITLE
Blazor doesn't DisposeAsync DI scope

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#12918]
Blazor doesn't call `DisposeAsync` on the DI scope, which leads to the following exception being logged during Circuit disposal:

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitRegistry[100]
      Unhandled exception disposing circuit host: 'blazor_async_dispose.MyScopedDisposableService' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
System.InvalidOperationException: 'blazor_async_dispose.MyScopedDisposableService' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<DisposeAsync>b__51_0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.DisposeAsync()
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitRegistry.DisposeCircuitEntry(DisconnectedCircuitEntry entry)
```

The DI scope/container is rigid about which kind of disposal you use depending on the services you have. This matrix lays out what happens. Across the top are the kinds of services you have, down the left is how you dispose the scope:

| How you dispose the scope | Implement `IDisposable` only | Implement **both** `IAsyncDisposable` **and** `IDisposable` | Implement `IAsyncDisposable` only |
| - | - | - | - |
| `DisposeAsync` | OK (calls `Dispose`) | OK (calls `DisposeAsync`) | OK (calls `DisposeAsync`) |
| `Dispose` | OK (calls `Dispose`) | OK (calls `Dispose`) | **❌Throws❌** |

It's definitely arguable that throwing this exception in DI isn't appropriate. I just want to open the discussion somewhere.

## Repro Steps

1. `dotnet new blazorserver`
2. Add file `MyScopedDisposableService.cs`:

```csharp
public class MyScopedDisposableService : IAsyncDisposable
{
    public MyScopedDisposableService()
    {
        Console.WriteLine("Scoped Service Constructed");
    }

    public ValueTask DisposeAsync()
    {
        Console.WriteLine("Scoped Service Disposed async!");
        return default;
    }
}
```

3. Register in `ConfigureServices`:

```csharp
services.AddScoped<MyScopedDisposableService>();
```

4. Inject into `Pages/Index.razor`:

```razor
@inject MyScopedDisposableService Service
```

5. Launch the app.
6. Navigate to the index page.
7. Close the tab.
8. Wait about ~5 minutes for the circuit to get disposed.

## Expected Behavior

No error is logged

## Actual Behavior

The following error is logged:

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitRegistry[100]
      Unhandled exception disposing circuit host: 'blazor_async_dispose.MyScopedDisposableService' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
System.InvalidOperationException: 'blazor_async_dispose.MyScopedDisposableService' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<DisposeAsync>b__51_0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.DisposeAsync()
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitRegistry.DisposeCircuitEntry(DisconnectedCircuitEntry entry)
```

**Comment by anurse** [comment]
If we don't fix this in Blazor, we also need to look at other places we create scopes and change to dispose them async.

**Comment by anurse** [comment]
My initial feeling is that throwing in `Dispose` is bad (for example: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1065-do-not-raise-exceptions-in-unexpected-locations?view=vs-2019)

**Comment by anurse** [comment]
+ @rynowak @davidfowl @Tratcher

**Comment by davidfowl** [comment]
As part of our sync over async awareness, we need to throw by default and have switches for not throwing.

**Comment by pranavkm** [comment]
What about things that aren't in DI scope? For instance, Controller or Hub instances: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Controllers/DefaultControllerActivator.cs#L72-L75

**Comment by davidfowl** [comment]
Should have been updated during the 3.x milestone but we missed those places.

**Comment by rynowak** [comment]
I've made a change for 3.0 to support disposing the scope created by `CircuitHost` asynchronously. We still need to do work in Blazor to support async disposal of **components** - tracked by https://github.com/aspnet/AspNetCore/issues/9960

**Comment by davidfowl** [comment]
Do we have something tracking mvc as well?

**Comment by rynowak** [comment]
I just https://github.com/aspnet/AspNetCore/issues/13150 created for it.

I don't think it's really time-sensitive that we have this in MVC, it's more about completeness.
- The components programming model is stateful, so you **frequently** write disposable components
- We don't really encourage writing disposable controllers in MVC (supported for completeness and legacy). Relying on DI for disposal us usually easier and better.
- Blazor creates scopes (server side)
- MVC doesn't create scopes
