### ISSUE TITLE
Connect to MySQL using named pipe

### ISSUE THREAD

**Issue by vigotecnologia** [aspnet/AspNetCore#12920]
I would like to connect my ASP.NET Core 2.2 app to MySQL using named pipe, is there a way to do this ?

I´m using Linux CentOS 7.6, MySQL 5.5 and .NET Connector 8.0.17 but setting "localhost" in the ConnectionString, parameter "server", doesn´t work.

**Comment by blowdart** [comment]
Named pipes are a Windows OS feature.  They are [not supported](https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_enable-named-pipe) on MySQL on linux.

**Comment by vigotecnologia** [comment]
Humm, ok, then, is it possible to connect to MySQL on Linux using SOCKETS ?

**Comment by blowdart** [comment]
That would depend on the mysql client library. 

EF folks might know, @ajcvickers ?

**Comment by ajcvickers** [comment]
@vigotecnologia I believe it is. Try using https://github.com/mysql-net/MySqlConnector I have seen people good luck with this provider even when the official provider runs into problems.
