### ISSUE TITLE
Accept button doesn't work on VS Internal Web Browser

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#12922]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/960955

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  given we removed 

```
services.Configure<CookiePolicyOptions>(options =>
{
    // This lambda determines whether user consent for non-essential cookies is needed for a given request.
    options.CheckConsentNeeded = context => true;
    options.MinimumSameSitePolicy = SameSiteMode.None;
});
```

From 2.2 and higher, can we close this issue? The fix would be in the internal web browser.

Should I open an issue suggesting we remove the internal web browser? I don't think it's heavily used.

**Comment by ryanbrandenburg** [comment]
I don't think there's any reason to ask them to remove the Internal Browser, it's just not a scenario we care about for these templates. So I'll close this issue.
