### ISSUE TITLE
Linux GC not collect

### ISSUE THREAD

**Issue by virtualcca** [aspnet/AspNetCore#12937]
### Describe the bug
In Linux (running on supervisor), my web app will continue to rise, and then stay close to 100% for a long time.
Recycling will only be triggered after a while (the program will produce a perceptible click) 

First of all, we can make sure that there are no memory leaks on our program. We suspect that it may be a problem on Linux.
Then I compiled a windows version and put it on 2008r2 to run with iis. It is found that when it reaches about 80%, it will trigger the recycling.

We have tried to modify the GC configuration to use the Workstation mode and still will not recycle in linux ( add  ServerGarbageCollection false in csproj)

In Linux
![image](https://user-images.githubusercontent.com/5656078/62598540-476c1800-b91c-11e9-91d7-2c6576a66e9d.png)

In Windows
![image](https://user-images.githubusercontent.com/5656078/62598683-cbbe9b00-b91c-11e9-8a38-c1d9e55701ce.png)

The exact same procedure except compiling the platform and the machines are hung behind load balancing, the flow pressure is similar.
We found that when the memory usage under Windows is higher than 80, it will trigger recycling, but Linux will not, but it will remain close to 100%.

Using .Net Core runtime 2.2.4

Linux Info
![image](https://user-images.githubusercontent.com/5656078/62599329-83a07800-b91e-11e9-84d3-59abc1f06452.png)

Windows Info 
![image](https://user-images.githubusercontent.com/5656078/62598922-6dde8300-b91d-11e9-940e-b220930b085f.png)

**Comment by anurse** [comment]
> Recycling will only be triggered after a while (the program will produce a perceptible click)

So the GC will eventually kick in? Is that what you mean by recycling? Or are you restarting the process?

> We found that when the memory usage under Windows is higher than 80, it will trigger recycling, but Linux will not, but it will remain close to 100%.

So is Linux not garbage collecting at all? Or is it just that Windows is garbage collecting earlier.

What, if any, profiling have you done to investigate what objects are causing the memory pressure?

**Comment by virtualcca** [comment]
@anurse 

We didn't do anything, just let it run for a while to observe its memory situation

After the memory usage in Linux is 100% and lasts for a long time (as in the previous screenshot), memory recovery will be triggered. Of course, we don't know if this is the actual GC collect or let Linux restart the process.


At present, we still don't know what is causing the memory pressure. We will try to analyze it. But if the program continues to run (regardless of memory leaks), if there is no garbage collection, then it should be normal for the memory to rise.

**Comment by anurse** [comment]
> Of course, we don't know if this is the actual GC collect or let Linux restart the process.

This information is pretty important. If the GC is eventually happening, it's not likely to be a leak. If the process is being restarted then that's a different story.

> if there is no garbage collection, then it should be normal for the memory to rise.

If garbage collection isn't happening *at all* that's not likely to be an ASP.NET Core issue.

Doing some memory profiling or dump analysis (we have some new tools for this in .NET Core 3.0: https://devblogs.microsoft.com/dotnet/introducing-diagnostics-improvements-in-net-core-3-0/) would be a good next step as well.

**Comment by virtualcca** [comment]
i use dotnet sdk to createDump 3 times and view with lldb 
Numbered 3 dumps 1, 2, 3

i use "dumpheap -state" to view

![Snipaste_2019-09-03_16-35-37](https://user-images.githubusercontent.com/5656078/64157869-1672fa80-ce6a-11e9-99c3-f98357ba5525.png)
![Snipaste_2019-09-03_16-36-05](https://user-images.githubusercontent.com/5656078/64157886-1d9a0880-ce6a-11e9-88eb-95d23e7c5124.png)
![WXWorkCapture_15675000429663](https://user-images.githubusercontent.com/5656078/64157892-212d8f80-ce6a-11e9-91fb-e8a9dee408f8.png)

The number of objects that can be seen will increase significantly over time

but i use "dumpheap -state -min 1024"
![Snipaste_2019-09-03_16-47-17](https://user-images.githubusercontent.com/5656078/64158154-913c1580-ce6a-11e9-912e-1a9006c8a808.png)
It seems that objects larger than 1k are not growing much.

Then I will try to use netcore3's diagnostic tool to see again.

**Comment by jamiegs** [comment]
For people with this issue, do you have `COMPlus_PerfMapEnabled=1` or `COMPlus_EnableEventLog=1`?  I was seeing sawtooth wave looking memory usage graphs with these enabled and disabling them fixed it.  I think it's actually `COMPlus_EnableEventLog` doing it, but I disabled both so I'm not 100% sure on which.

**Comment by virtualcca** [comment]
i found i use serviceProvider resolve object will make memoryLeak...
sorry, is my wrong
