### ISSUE TITLE
SignalR connection.close() not working

### ISSUE THREAD

**Issue by murugaratham** [aspnet/AspNetCore#12945]
### To Reproduce
1. Using this version of ASP.NET Core '2.2.300'
```js 
const connection = new HubConnectionBuilder()
    .withUrl(connectionHub, options)
    .withAutomaticReconnect([1000, 2000, 4000, 8000, 16000])
    .withHubProtocol(protocol)
    .build();
...
// on log in success
connection.start();
...
// on log out success
connection.stop();
```
Do login/logout a couple of times
```
// on server side
_hubContext.Clients.All // <-- inspect "All", connection count only increases, doesn't decrease despite client calling connection.stop()
```
Can be confirmed by inspecting chrome network tab, there's still connected websockets.

### Expected behavior
When i call `connection.stop()`, the websocket connection should be terminated, or else, i'm leaking websocket connections.

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by BrennanConroy** [comment]
Could you enable logs on the client and share them? You can so by following the instructions at https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2#javascript-client-logging

`Trace` level will show "(WebSockets transport) socket closed." but `Debug` is probably sufficient enough for now.

**Comment by murugaratham** [comment]
> [2019-08-09T02:49:05.483Z] Debug: Starting connection with transfer format 'Text'.
10:49:05.485 Utils.js:358 [2019-08-09T02:49:05.485Z] Debug: Sending negotiation request: http://localhost:3000/_ws/negotiate.
10:49:05.541 Utils.js:358 [2019-08-09T02:49:05.541Z] Debug: Selecting transport 'WebSockets'.
10:49:05.567 Utils.js:353 [2019-08-09T02:49:05.567Z] Information: WebSocket connected to ws://localhost:3000/_ws?id=AkZEKRdttahGOqU53eVSSA.
10:49:05.568 Utils.js:358 [2019-08-09T02:49:05.568Z] Debug: The HttpConnection connected successfully.
10:49:19.282 Utils.js:353 [2019-08-09T02:49:19.282Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:19.455 Utils.js:353 [2019-08-09T02:49:19.455Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:19.483 Utils.js:353 [2019-08-09T02:49:19.483Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:19.765 Utils.js:353 [2019-08-09T02:49:19.765Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:19.780 Utils.js:353 [2019-08-09T02:49:19.780Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:20.488 Utils.js:358 [2019-08-09T02:49:20.488Z] Debug: Starting connection with transfer format 'Text'.
10:49:20.496 Utils.js:358 [2019-08-09T02:49:20.496Z] Debug: Sending negotiation request: http://localhost:3000/_ws/negotiate.
10:49:20.540 Utils.js:358 [2019-08-09T02:49:20.540Z] Debug: Selecting transport 'WebSockets'.
10:49:20.645 Utils.js:353 [2019-08-09T02:49:20.645Z] Information: WebSocket connected to ws://localhost:3000/_ws?id=dm24Lq-akGembUWh--j05Q&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YzZhNGQ3ZTAxYzc0M2E0ODgxZjQyYTBhYjVlMDBkMCIsInVuaXF1ZV9uYW1lIjoiNGM2YTRkN2UwMWM3NDNhNDg4MWY0MmEwYWI1ZTAwZDAiLCJqdGkiOiJiNGE3YTAyNC01OGVmLTQzOTYtOWRkYi02ZTZkYTIxMTE3NDUiLCJpYXQiOiIxNTY1MzE4OTU5NDI5IiwiZW1haWwiOiJhZG1pbkBpY29ubmVjdC5jYXJlIiwiZ2l2ZW5fbmFtZSI6IlN5c3RlbSBBZG1pbiIsIk9yZ2FuaXphdGlvbiI6IklDT05ORUNUIiwiUm9sZSI6ImFkbWluIiwibmJmIjoxNTY1MzE4OTU5LCJleHAiOjE1NjUzMjA3NTksImlzcyI6ImlDb25uZWN0LWlkZW50aXR5LXNlcnZpY2UifQ.PE5HFmMEQ9pQo-BW47yatYUS3rd32ksC-gw5Pd0FCfk.
10:49:20.646 Utils.js:358 [2019-08-09T02:49:20.646Z] Debug: The HttpConnection connected successfully.
10:49:25.295 Utils.js:353 [2019-08-09T02:49:25.295Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:25.545 Utils.js:353 [2019-08-09T02:49:25.545Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:25.546 signalRMiddleware.ts:113 connection.stop() here
10:49:25.585 Utils.js:353 [2019-08-09T02:49:25.585Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:39.810 Utils.js:353 [2019-08-09T02:49:39.810Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:40.058 Utils.js:353 [2019-08-09T02:49:40.058Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:40.077 Utils.js:353 [2019-08-09T02:49:40.077Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:40.235 Utils.js:353 [2019-08-09T02:49:40.235Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:40.264 Utils.js:353 [2019-08-09T02:49:40.264Z] Information: Normalizing '/_ws' to 'http://localhost:3000/_ws'.
10:49:41.061 Utils.js:358 [2019-08-09T02:49:41.061Z] Debug: Starting connection with transfer format 'Text'.
10:49:41.061 Utils.js:358 [2019-08-09T02:49:41.061Z] Debug: Sending negotiation request: http://localhost:3000/_ws/negotiate.
10:49:41.094 Utils.js:358 [2019-08-09T02:49:41.094Z] Debug: Selecting transport 'WebSockets'.
10:49:41.132 Utils.js:353 [2019-08-09T02:49:41.132Z] Information: WebSocket connected to ws://localhost:3000/_ws?id=VD69wTBSqqLo_n0JlKiiag&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YzZhNGQ3ZTAxYzc0M2E0ODgxZjQyYTBhYjVlMDBkMCIsInVuaXF1ZV9uYW1lIjoiNGM2YTRkN2UwMWM3NDNhNDg4MWY0MmEwYWI1ZTAwZDAiLCJqdGkiOiJjODVlYjQ5Yy0xYzBlLTQ2N2ItOTM4Zi03MzNkM2E5NTk2YjEiLCJpYXQiOiIxNTY1MzE4OTgwMDM1IiwiZW1haWwiOiJhZG1pbkBpY29ubmVjdC5jYXJlIiwiZ2l2ZW5fbmFtZSI6IlN5c3RlbSBBZG1pbiIsIk9yZ2FuaXphdGlvbiI6IklDT05ORUNUIiwiUm9sZSI6ImFkbWluIiwibmJmIjoxNTY1MzE4OTgwLCJleHAiOjE1NjUzMjA3ODAsImlzcyI6ImlDb25uZWN0LWlkZW50aXR5LXNlcnZpY2UifQ.1TB0QqbHyhKjCQugvnpsNDxfVeauGBc63DK6QUNX2Ok.
10:49:41.133 Utils.js:358 [2019-08-09T02:49:41.133Z] Debug: The HttpConnection connected successfully.

You can search `signalRMiddleware.ts:113 connection.stop() here`, i called connection.stop() but the connection wasn't terminated and when i call connection.start(), there's now 2 connections

**Comment by BrennanConroy** [comment]
It doesn't look like you're actually calling `connection.stop()`. If you did there should be a log with "Stopping HubConnection." in it.

Can you share `signalRMiddleware`?

**Comment by murugaratham** [comment]
Sure, here it is [gist](https://gist.github.com/murugaratham/04ca48ea37a3bddd61bc359bd12060f9)

**Comment by BrennanConroy** [comment]
Ok, it looks like you create a new connection every time your middleware runs, which means when you get `action.type === getType(logoutAction.success)` you create a new connection, don't start it, and then call stop on a not started connection.

**Comment by murugaratham** [comment]
Yeah, you're right, i'm adding `if (!connection || connection.state === HubConnectionState.Disconnected) {` before i build the connection.

Another tip for anyone else facing the same issue, i planted `console.log(connection.connectionId);` at several initialization and exit points, and confirmed @BrennanConroy is correct, the connection id was different and i attempted to stop a new connection rather than the active one.

Thanks for your help!
