### ISSUE TITLE
Update dotnet-sql-cache tool to RTM build of Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#12957]
The `MicrosoftDataSqlClientPackageVersion` value in https://github.com/aspnet/AspNetCore/blob/c79002bf38f2a08f496c645ee04e0a9084601f31/eng/Versions.props needs to be updated to the RTM build when one is available.

The `dotnet-sql-cache` tool should also be tested (manually, we don't have automation here). To do so, you just need to create a blank SQL Server database and run the tool pointing at it.

We have an expected date for this package (@divega @ajcvickers have detail).

fyi @Pilchie this is critical to shipping as we currently depend on a pre-release package.

I'll assign this out before I go on leave and give full context on the date we'll have a package.

**Comment by dougbu** [comment]
@BrennanConroy is this fix coming in the next day or so?

**Comment by BrennanConroy** [comment]
In a few days, this is for RTM not preview9.

**Comment by dougbu** [comment]
RTM changes should get into 'release/3.0' ASAP.

**Comment by BrennanConroy** [comment]
Fixed by #13530
