### ISSUE TITLE
[CTI] Open the RevalidatingAuthenticationStateProvider.cs in Blazor Server App with IndAuth project, there is a message in Error List

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#12956]
**Title**: Open the RevalidatingAuthenticationStateProvider.cs in Blazor Server App with IndAuth project, there is a message in Error List: "A type that implements System.IDisposable declares...unmanaged resources held by the field"

#### Error
A type that implements System.IDisposable declares fields that are of types that also implement IDisposable. The Dispose method of the field is not called by the Dispose method of the declaring type. To fix a violation of this rule, call Dispose on fields that are of types that implement IDisposable if you are responsible for allocating and releasing the unmanaged resources held by the field.

Copied from: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/945201

**Comment by rynowak** [comment]
FxCop is a scourge upon the earth for readability and simplicity - are we really requiring out templates and scaffolded code to be clean for FxCop?

**Comment by mkArtakMSFT** [comment]
We are trying to be in a place, where a newly created project has no warnings. While that's the case, it's case by case basis. If we believe this state is fine, and we want to leave with that warning and there is nothing to do for us here, then we're good to leave with this warning.

**Comment by rynowak** [comment]
Many of the FxCop rules specifically have a high false-positive rate (this is one of those, the one about double-dispose is another). 

Given that all ASP.NET Core applications use DI so heavily, this warning will lead to the incorrect guidance 99% of the time.

**Comment by mkArtakMSFT** [comment]
Closing as there is nothing to be done here.
