### ISSUE TITLE
Blazor - Adding to a list does not work

### ISSUE THREAD

**Issue by salmanmkc** [aspnet/AspNetCore#12960]
### Describe the bug
So, I was having fun with Blazor, just started it and I decided to make a portfolio using it. I thought I would have a collection of all the names of my projects, but thought better than that, I'd make a custom type for my projects, so I can have properties and such. I ended up making the class, a separate class and then tried to create a list of that type, that worked, however failed when trying to add that type T to the list of type T. Upon testing, just a list generic type string fails as well, on the stage of adding to the list, have tested the code just to check my sanity in a normal .net project and works fine
![image](https://user-images.githubusercontent.com/32169182/62664300-fd625100-b972-11e9-9ce6-b51e2bf074d3.png)

### To Reproduce
1. Using this version of .NET Core '3.0.100-preview7-012821'
2. Run this code 'https://github.com/salmanmkc/blazorWOO'
3. See error

or if you want to test it yourself

1. Create a Blazor project
2. Use a code block to create a list and then add to that list
3. See the error

### Expected behavior
Should be able to add objects of type T to list of type T without errors

### Additional context
My whole history of trialing and going through steps to try remedy the problem are commits in the repository, have a look through
There was a case where it did compile without errors, I used the @functions code block instead of the @code block and it happened to work, however haven't been able to replicate it, it's in commit e6ca2f40b03c4b4dc87b63a6cb4e99205a8323d0
There was also another scenario where it compiled, if I put it in a method block in commit 3a5fe933930ded57010d24aa95a1125b77ca89eb however couldnt' call the method as seen in commit 8b0b0aa44c0fa2409f8cc7b61da90f072ea941a5

Any help would be appreciated, I may be doing something wrong on my end as well, for example using statements, etc. namespaces, quite new to using Blazor

**Comment by ghidello** [comment]
Try to call to StateHasChanged method after updating the items list: my guess is that the component doesn’t know that the bound list has been updated

**Comment by salmanmkc** [comment]
just realised I was adding to the list outside of a method, which is why it was working before when I put it inside a method, just need to figure out how to invoke that method, since making it static doesn't work

**Comment by salmanmkc** [comment]
> Try to call to StateHasChanged method after updating the items list: my guess is that the component doesn’t know that the bound list has been updated

I've invoked the method with the button click, it automatically updates the UI now that I've put the adding to the list in a method, just need to figure out how to invoke the method on a page load

**Comment by salmanmkc** [comment]
Have now created a class which creates a list and adds projects to the list in the constructor, which I instantiate from the projects razor page, all sorted. And thanks for trying to help before @ghidello 
![image](https://user-images.githubusercontent.com/32169182/62701939-6da5bc80-b9dd-11e9-8694-182bbcd407db.png)
