### ISSUE TITLE
[Blazor][Question] OnDestroy or OnDestroyAsync 

### ISSUE THREAD

**Issue by skordesign** [aspnet/AspNetCore#12965]
### Does Blazor ComponentBase have any lifecycle method when it's destroyed? I can't see it.
This it my situation:
OnInit: I subscribe an event
I want to unsub when component destroy

### Idea
Add OnDestroy or OnDestroyAsync to lifecycle of component.

**Comment by campersau** [comment]
You can implement the `IDisposable` interface which is called when the component is removed. https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#component-disposal-with-idisposable
Async disposal is tracked here https://github.com/aspnet/AspNetCore/issues/9960

**Comment by skordesign** [comment]
Thanks fyi, I close it now.
