### ISSUE TITLE
[Blazor dual mode] inject IHostEnvironment in the client project

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#12964]
hi guys, I actually have an architecture like the dual mode of daniel roth (https://github.com/danroth27/BlazorDualMode). In the server project, we can see he inject an IHostEnvironment in the startup to read the current environnement.

I need to do the same thing on the client project. But when i try to inject an IHostEnvironment, on the startup constructor, in the configure Method, or in a component, I have this following error "No service for type 'Microsoft.Extensions.Hosting.IHostEnvironment' has been registered"  (when i launch as client side)

So, how i can achieve this ? (just retrieve the current environment in my client project) ideally, it would be better to only change the environment variable in the server project, rather than have to change also the environment variable in the client project.

thanks !

Julien

**Comment by SteveSandersonMS** [comment]
There's no equivalent to the "host environment" concept for client-side Blazor. It's possible we might add something like it in the future, but currently it doesn't exist.

One of the reasons is that in general, client-side Blazor is only a set of static files served by the server (which doesn't have to be running .NET at all), so it's not really meaningful to talk about it being launched in different modes.

If you want, you can use the compilation configuration to switch between different behaviors, e.g.,

```cs
#if DEBUG
    Console.WriteLine("Debug version");
#else
    Console.WriteLine("Release version");
#endif
```

When compiling normally in development, the `DEBUG` flag should be set, whereas when publishing for production deployment it should not.
