### ISSUE TITLE
Blazor - Client-Side - Download only required DLLs

### ISSUE THREAD

**Issue by chassq** [aspnet/AspNetCore#12968]
I was just trying to understand better if Blazor (Client-Side) will be "smart" enough to only download the DLLs that are required to run a currently viewed portion of the Blazor app. If so was wondering how that effects the project structure. For example should we think about creating a project of components for the various areas of our application?

If not already, I guess what we would like is for Blazor to only download and load the DLLs required to do the current work so that we can keep the download size small. I guess conceptually like how require.js might only download what modules it needs to run an operation.

If there is any documentation on this currently a link would be appreciated.

Thank you!!

**Comment by SteveSandersonMS** [comment]
Please see https://github.com/aspnet/AspNetCore/issues/5465

**Comment by chassq** [comment]
Thank you!!
