### ISSUE TITLE
Add opposites of AddRedirectToWww / AddRedirectToWwwPermanent

### ISSUE THREAD

**Issue by kendaleiv** [aspnet/AspNetCore#12978]
Currently there are built in redirects for these: https://github.com/aspnet/AspNetCore/blob/cc1f23c5f8afb7d2a00405f19811d2372c4fcec2/src/Middleware/Rewrite/src/RewriteOptionsExtensions.cs#L145 https://github.com/aspnet/AspNetCore/blob/cc1f23c5f8afb7d2a00405f19811d2372c4fcec2/src/Middleware/Rewrite/src/RewriteOptionsExtensions.cs#L125

It would be nice if there was built-in support for doing the opposite, redirecting from `www.example.com` to `example.com`.

**Comment by jkotalik** [comment]
Sounds like a decent addition. We would consider taking a PR to add this behavior if you are interested.

**Comment by jkotalik** [comment]
Need to add docs for this new feature 😄
