### ISSUE TITLE
[Build] Support dependencies referencing Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#12975]
* We currently have a package (Microsoft.AspNetCore.Identity.ApiAuthorization) that has a dependency to IdentityServer4.
* IdentityServer4 has a dependency on Microsoft.AspNetCore.App
* As a result, we get an error when we try to build Microsoft.AspNetCore.Identity.ApiAuthorization.
* Adding `<UseAspNetCoreSharedRuntime>true</UseAspNetCoreSharedRuntime>` helps here. After doing that and building the shared framework it is possible to get a successful and working build.

There are a couple of ways we could potentially solve this chicken an egg problem:
* Figure out a way to allow the package to reference a previous version of Microsoft.AspNetCore.App.
  * We've tried this by adding an explicit frameworkreference entry and we haven't been able to get it to work.
  * We tried with the version in the .net package and without it.
  * With and without `<UseAspNetCoreSharedRuntime>true</UseAspNetCoreSharedRuntime>`
* We can build this package after building the shared framework and the templates.
  * That way, the expected framework version for building the package will be available inside the local .dotnet folder.

**Comment by mkArtakMSFT** [comment]
@dougbu tenatively assigning to you to tackle in Preview9. Actually, we should try to tackle this this week, so we can unblock the integration with IdentityServer.
Feel free to reassign to someone else, who will be handling this.

**Comment by dougbu** [comment]
@mkArtakMSFT I definitely will not be able to take this any time soon given non-build responsibilities and doubt @JunTaoLuo or @wtgodbe will have time within our abridged preview 9 either.

More generally, I made two suggestions on this topic but I have trouble justifying actually reordering our build (the second suggestion) in an ask mode change.

**Comment by javiercn** [comment]
My understanding is that infrastructure changes are tell-mode

**Comment by dougbu** [comment]
Try _not_ using a specific Microsoft.AspNetCore.App version and addressing any issues that causes first.

While infrastructure changes are tell mode, this is a big change for a small dependency version bump. We don't have much time to do this, deal with any fall out, and make other mandatory build changes for preview 9. For example, I'm in the middle of rewriting the YAML in this repo to use the correct templates.

**Comment by javiercn** [comment]
> Try _not_ using a specific Microsoft.AspNetCore.App version and addressing any issues that causes first.

I already tried this as described in the bullet point above without success.

**Comment by javiercn** [comment]
Pranav an I figured out a way to do this.

**Comment by JunTaoLuo** [comment]
Curious how did you solve this?

**Comment by javiercn** [comment]
Fake it until you make it.

https://github.com/aspnet/AspNetCore/pull/12687/commits/f066d9eceaf5a11bb1eeea9aac7c5668e07fd954#diff-a3b18a47d780c43e206227bfb9d342f0

I removed the reference, disabled errors and added all the stuff in manually needed for this to build/compile/run.

@pranavkm helped me with the last bit. I was missing how we hack thing around in the absence of a shared framework.

**Comment by mkArtakMSFT** [comment]
@javiercn should this be `Done`?
