### ISSUE TITLE
System.Linq.Dynamic.Core OrderBy not working in Blazor

### ISSUE THREAD

**Issue by JoelW187** [aspnet/AspNetCore#12972]
### Describe the bug
Calling System.Linq.Dynamic.Core.OrderBy(string) in a client-side Blazor component throws an exception (see attached image).

### To Reproduce
This code works on the server (Projects is a simple POCO class with a Description string field):

Projects.AsQueryable().OrderBy("Description")

In a Blazor component it throws the exception.

### Screenshots
![DynamicOrderBy](https://user-images.githubusercontent.com/15229643/62714763-2dd6d900-b9cd-11e9-8d3e-d0ba1b9e159d.png)

### Additional context
I'm using Core 3 Preview 7. This used to work (way back in Blazor 3 or 4) and broke sometime around 5, I beleive.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#16148
