### ISSUE TITLE
Blazor: CSB randomly does not work on iOS

### ISSUE THREAD

**Issue by chanan** [aspnet/AspNetCore#12992]
Preivew7. Tried on Safari, Edge ios, and Chrome.

I have several CSB sites hosted on github pages (some with DNS some without). When I push changes sometimes one works and sometimes it doesn't.

For example right now: 

* https://chanan.github.io/BlazorTypography/ - works
* https://blazorstyled.io/ - does not work

I fired up xcode to see if I can figure out why, however in **both** of them do not work in xcode and give the error:

```
Unhandled Promise Rejection: Error: Failed to start platform. Reason: Error: This browser does not support WebAssembly.
```

My xcode is update: Version 10.3 (10G8)

**Comment by SteveSandersonMS** [comment]
> both of them do not work in xcode and give the error:

That is expected, since the iOS simulator doesn't support WebAssembly. 

@mkArtakMSFT We should move this issue to the `mono` repo.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#16144
