### ISSUE TITLE
Razor TagHelper duplication Property Complie Error

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/AspNetCore#12993]
I use Vs2019 + asp.net core 2.1,I found that when two class contain same name property, on cshtml use the property and complie ,it will show a error msgbox,but the error list is empty
my code like this:
```  
    [HtmlTargetElement("auth")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public class AuthTagHelper : TagHelper
    {
        /// <summary>
        /// 权限项Code,,使用逗号分隔
        /// </summary>
        public string Codes { set; get; }

        [ViewContext]
        public ViewContext ViewContext { get; set; }
    }

    [HtmlTargetElement("auth")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public class AuthTagHelper2 : TagHelper
    {
        public string[] Codes { set; get; }

        [ViewContext]
        public ViewContext ViewContext { get; set; }
    }
```

cshtml:
`<auth codes="str,str2" t="@(new []{"dddd","ssss"})"></auth>`

when i run the web project,it show:
![image](https://user-images.githubusercontent.com/18448413/62751005-b9676d00-ba94-11e9-8875-d83987fe7ed2.png)
but in error list window not contain this error:
![image](https://user-images.githubusercontent.com/18448413/62751040-d2701e00-ba94-11e9-8b8b-59bdf7ebd1b4.png)

**my question is how can i find this error,when i import third-party ui library**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kugarliyifan.
@NTaylorMullen what's our guidance here?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen what's our guidance here?

oh geez. My bet to why this is happening is because of how we support `[EditorBrowsable(EditorBrowsableState.Never)]`. @kugarliyifan if you remove `[EditorBrowsable(EditorBrowsableState.Never)]` from both of your auth TagHelpers do you see the issue?

**Comment by kugarliyifan** [comment]
> > @NTaylorMullen what's our guidance here?
> 
> oh geez. My bet to why this is happening is because of how we support `[EditorBrowsable(EditorBrowsableState.Never)]`. @kugarliyifan if you remove `[EditorBrowsable(EditorBrowsableState.Never)]` from both of your auth TagHelpers do you see the issue?

thk,,,i try to remove [EditorBrowsable(EditorBrowsableState.Never)],it work!!

**Comment by kugarliyifan** [comment]
but i suggest , when complete the code ignore this attrubte,,because,taghelper class usually not need to new instance manual
