### ISSUE TITLE
[CTI] Create Blazor Server App with Individual project, then F5 and zoom out your browser, these buttons(register, login, About) will disappear.

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#13003]
**REPRO STEPS**
1.  File > New Project > ASP.NET Core Web Application > .Net Core - ASP.Net Core 3.0 - Blazor Server App with Individual > Create
2. F5

**ACTUAL**
zoom out your browser,this buttons(register, login, About) will disappear

Source: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/946150

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/aspnet/AspNetCore/pull/14941
