### ISSUE TITLE
[Blazor:Server side] iOS WebClip hangs after server restart. 

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/AspNetCore#13001]
## Description
When a Blazor Server-Side app is deployed it is possible to add the Website as a Homescreen shortcut on iOS. This can be achieved by the following steps: [add website as App Icon on iOS](https://ipadacademy.com/how-to-set-up-web-clips-for-your-favorite-websites-in-safari-on-ipad-or-iphone/). The website can then be started as an App. However, if you're supporting fullscreen by adding the following line of code to the `_host.cshtml` head:
```html
    <meta name="apple-mobile-web-app-capable" content="yes">
```
The browser navigation bar and refresh capabilities are gone. Thus you cannot refresh the app:
### Full Screen Blazor Server Side App:
<a href="https://ibb.co/rkDnFWS"><img src="https://i.ibb.co/rkDnFWS/IMG-2764.jpg" alt="IMG-2764" border="0"></a>

### Full Screen Blazor Server Side App when the connection to the circuit is lost:
It's rather impossible to refresh the App.
 <a href="https://ibb.co/hm1pPpN"><img src="https://i.ibb.co/hm1pPpN/IMG-2765.png" alt="IMG-2765" border="0"></a>

### To Reproduce
1. Create a new simple Blazor Server-Side Project (Preview-7)
2. Add the following line of code to the `head` of the `_host.cshtml` page
  `<meta name="apple-mobile-web-app-capable" content="yes">` to the 
3. Deploy the App on Azure
4. Use safari on any iOS device to browse the website
5. Add the website to the home screen using [this tutorial](https://ipadacademy.com/how-to-set-up-web-clips-for-your-favorite-websites-in-safari-on-ipad-or-iphone/)
6. Restart the app to trigger a circuit connection loss.
7. You're unable to refresh the app.

### Expected behavior
Add a possibility to refresh the app on a circuit connection loss.

**Comment by vertonghenb** [comment]
I guess this will be fixed by https://github.com/aspnet/AspNetCore/issues/12442, just logging the issue so it's tracable.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vertonghenb.
You're right, the fix in the referenced issue will improve the experience here too.
