### ISSUE TITLE
[Blazor] Client side : enable Brotli compression

### ISSUE THREAD

**Issue by RemiBou** [aspnet/AspNetCore#13002]
### Is your feature request related to a problem? Please describe.
When enabling brotli compression, you can decrease mscorlib.dll from 1,4MB to 647Kb (-54%) and System.Core from 310Kb to 145Kb. This kind of improvement can be seen on many other dll. Given the fact that load time is very important for client side app, this seems like an easy win.

### Describe the solution you'd like
Maybe when calling MapFallbackToClientSideBlazor setup brotli and enable compression on "application/octet-stream"

### Additional context
On my project [Toss](https://github.com/RemiBou/Toss.Blazor) the first load went from 4,7MB to 2,7MB.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RemiBou.
@Tratcher is there anything we need to do here, or is the compression enabled by default?

**Comment by Tratcher** [comment]
The blazor [template](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Startup.cs) doesn't include the response compression middleware by default.

Brotli support was added back in 2.2 (https://github.com/aspnet/BasicMiddleware/issues/217), and we added `application/wasm` to the compression list (https://github.com/aspnet/AspNetCore/commit/2d3ad1cb0f9872da40c6d143ce4554563971ae04).

How is `mscorlib.dll` being served? Dll's aren't on static file's default [list](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs).

`application/octet-stream` isn't on the default compression [list](https://github.com/aspnet/AspNetCore/blob/69a703748026b4890db2e6ce683c05f5f3fffe1c/src/Middleware/ResponseCompression/src/ResponseCompressionDefaults.cs#L19-L31).

**Comment by rynowak** [comment]
That's the server template - the relevant stuff for client is here:
- https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Templates/src/content/BlazorWasm-CSharp/Server/Startup.cs
- https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Server/src/Builder/BlazorHostingApplicationBuilderExtensions.cs#L72

**Comment by Tratcher** [comment]
Ok, that should be everything you need.

@RemiBou you should already be seeing dynamic compression here.

**Comment by RemiBou** [comment]
Yes indeed you got it covered already ! Thanks for your time, sorry for the
issue.
