### ISSUE TITLE
Consider whether we expose a different concept than CircuitId as part of Server-Side Blazor

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#13012]
SignalR is current doing some design work to make server-side code less likely to use a connection id for application-level concerns.

The Circuit ID has similar usage and meaning (used to identify a client and handshake with the server). We might want to define a different unique ID to use for circuit identification purposes in `CircuitHandlers` so that these IDs don't leak outside of their original purpose.

**Comment by javiercn** [comment]
@mkArtakMSFT I don't have bandwith to handle this

**Comment by mkArtakMSFT** [comment]
@rynowak do you have bandwidth to take this over? Or should we simply push it out of 3.0?
