### ISSUE TITLE
Blazor Call method

### ISSUE THREAD

**Issue by JulienM28** [aspnet/AspNetCore#13023]
Hello,

before preview 7 I used to call my methods as this:

````
<button class="btn btn-default btn-ok" onclick="@ShowCloseTicket">Clôturer le ticket</button>
````
But now I have an error message in Visual Studio:
Cannot convert method group to non delagte type. Did you inted to invoke the method ?

Yes I do.

So I Changed to 
````
<button class="btn btn-default btn-ok" onclick="@ShowCloseTicket()">Clôturer le ticket</button>
````
But I still get an error message: 
Cannot implicitly convert void to object.
Damn Async Tasks with a Task return dont have this issue, they have another one : executing even if the event isn't fired

So what is the new correct way to call a method in preview 7 ?

Thanks.

**Comment by hez2010** [comment]
You need to use @onclick="ShowCloseTicket" after preview 7.
Details were written in https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-7/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
