### ISSUE TITLE
Blazor Server-Side not re-rendering component after event is fired !

### ISSUE THREAD

**Issue by moataz1991** [aspnet/AspNetCore#13039]
As described in the title,i can't see any re-rendering after 'onclick' is fired

### To Reproduce
1. Using this version of ASP.NET Core '3 preview 7'
2. Run this code
```
protected virtual void BuildCompnent(RenderTreeBuilder builder)
{
...

builder.AddContent(seq, _viewProperty.PropertyValue ?? "--SELECT--");

...

     foreach (var item in SelectionDictionary)
                    {                   
                        builder.OpenElement(++seq, "a");
                        builder.AddAttribute(seq, "class", "font-weight-light btn-sm dropdown-item " + (item.Value == _viewProperty.PropertyValue ? "active" : ""));
                        builder.AddAttribute(seq, "onclick", () => ItemClicked?.Invoke(item.Key)); 
                        //builder.SetUpdatesAttributeName("onclick"); --> tried it but no help
                        builder.AddContent(seq, item.Value.ToString());
                        builder.CloseElement();
                   }
...
}
```
3.  The Action 'ItemClicked' is reached by the debugger , but component not showing "re-rendering" the selected item

### Expected behavior
It should re-render the component by default when 'onclick' event is fired

### Additional context
BTW this code was working like a charm in blazor 0.7 server-side
but after updating to latest version..things got crackly

**Comment by moataz1991** [comment]
it looks like all events does not Re-Render , therefore i should pass `StateHasChanged` from the beginning to every single component


anyway to set it by default that any event rising will call root `StateHasChanged` ?

**Comment by conficient** [comment]
You need to remove the `seq` variable and use constant integers in the calls to `builder` - don't use variables or loops.

[Chris Sainty's blog](https://chrissainty.com/building-components-via-rendertreebuilder/) has good help in this area, along with [an explanation by @SteveSandersonMS](https://gist.github.com/SteveSandersonMS/ec232992c2446ab9a0059dd0fbc5d0c3) as to why this is the case.

**Comment by moataz1991** [comment]
Impossible !
how could i know the future ?! like how many `item `in `SelectionDictionary` ?!
[Chris Sainty's blog](https://chrissainty.com/building-components-via-rendertreebuilder/) does not really help in this case specially the numbering issue , anyway I'm only increasing the `seq` when opening an element tag not when adding attributes
plus, this was working in 0.7 version

something not 'popping up' after an event is rising 
this is possibly due to difference between `onclick` and `@onclick` there is something must be missing because `@onclick` does not exist in 0.7
i don't know how is the Renderer working but what ever is capturing `@onclick` and rise `StateHasChanged` automatically **DOES NOT** do it to `onclick` and goes with other events too
like `mousein` , `oninput` etc...

> Please notice the '@'

again , the previous code was working in Blazor 0.7 server-side

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @moataz1991.
You need to use the `EventCallback()`, as described at https://chrissainty.com/3-ways-to-communicate-between-components-in-blazor/
Please give it a try and let us know if you're still having any issues.

**Comment by SteveSandersonMS** [comment]
> how could i know the future ?! like how many item in SelectionDictionary ?!

In the [linked blog post](https://chrissainty.com/building-components-via-rendertreebuilder/), it explains how you should handle this to avoid the `seq++` code.

**Comment by conficient** [comment]
@moataz1991  Read Steve's explanations, specifically the **Q&A** at the end. You _can_ create a loop in the code but **you don't need to increment the line count for each row**.  

The sequence number isn't an _element pointer_, think of it as a _"line of code"_ pointer, that helps the Blazor renderer figure out which bits of the razor code relate to which items.

To help visualise this I re-wrote your code as a simple Razor component (with a few changes):
```
<h1>Demo</h1>
<div class="dropdown">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @(ViewProperty ?? "SELECT")
    </a>
    <div class="dropdown-menu">
        @foreach (var item in SelectionDictionary)
        {
            <a class="font-weight-light btn-sm dropdown-item @(item.Value == ViewProperty ? "active" : "")" @onclick="(() => ItemClicked(item.Key))">@item.Value</a>
        }
    </div>
</div>
<p>You clicked: @ViewProperty</p>
@code
{
    //
    string ViewProperty = null;

    Dictionary<string, string> SelectionDictionary;

    protected override void OnInit()
    {
        SelectionDictionary = new Dictionary<string, string>();
        SelectionDictionary.Add("a", "A");
        SelectionDictionary.Add("b", "B");
    }

    void ItemClicked(string key)
    {
        ViewProperty = key;
    }
}
```
Now look at how the Razor compiler generates the code:
```cs
 protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
            builder.AddMarkupContent(0, "<h1>Demo</h1>\r\n\r\n");
            builder.OpenElement(1, "div");
            builder.AddAttribute(2, "class", "dropdown");
            builder.AddMarkupContent(3, "\r\n    ");
            builder.OpenElement(4, "a");
            builder.AddAttribute(5, "class", "btn btn-secondary dropdown-toggle");
            builder.AddAttribute(6, "href", "#");
            builder.AddAttribute(7, "role", "button");
            builder.AddAttribute(8, "id", "dropdownMenuLink");
            builder.AddAttribute(9, "data-toggle", "dropdown");
            builder.AddAttribute(10, "aria-haspopup", "true");
            builder.AddAttribute(11, "aria-expanded", "false");
            builder.AddMarkupContent(12, "\r\n        ");
            builder.AddContent(13, 
#line 7 "C:\Users\Howard\Source\Repos\EMSweb\EMSweb\Pages\Index.razor"
          ViewProperty ?? "SELECT"

#line default
#line hidden
            );
            builder.AddMarkupContent(14, "\r\n    ");
            builder.CloseElement();
            builder.AddMarkupContent(15, "\r\n    ");
            builder.OpenElement(16, "div");
            builder.AddAttribute(17, "class", "dropdown-menu");
            builder.AddMarkupContent(18, "\r\n");
#line 10 "C:\Users\Howard\Source\Repos\EMSweb\EMSweb\Pages\Index.razor"
         foreach (var item in SelectionDictionary)
        {

#line default
#line hidden
            builder.AddContent(19, "            ");
            builder.OpenElement(20, "a");
            builder.AddAttribute(21, "class", "font-weight-light" + " btn-sm" + " dropdown-item" + " " + (
#line 12 "C:\Users\Howard\Source\Repos\EMSweb\EMSweb\Pages\Index.razor"
                                                               item.Value == ViewProperty ? "active" : ""

#line default
#line hidden
            ));
            builder.AddAttribute(22, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.UIMouseEventArgs>(this, 
#line 12 "C:\Users\Howard\Source\Repos\EMSweb\EMSweb\Pages\Index.razor"
                                                                                                                      (() => ItemClicked(item.Key))

#line default
#line hidden
            ));
            builder.AddContent(23, 
#line 12 "C:\Users\Howard\Source\Repos\EMSweb\EMSweb\Pages\Index.razor"
                                                                                                                                                      item.Value

#line default
#line hidden
            );
            builder.CloseElement();
            builder.AddMarkupContent(24, "\r\n");
#line 13 "C:\Users\Howard\Source\Repos\EMSweb\EMSweb\Pages\Index.razor"
        }

#line default
#line hidden
            builder.AddContent(25, "    ");
            builder.CloseElement();
            builder.AddMarkupContent(26, "\r\n");
            builder.CloseElement();
            builder.AddMarkupContent(27, "\r\n");
            builder.OpenElement(28, "p");
            builder.AddContent(29, "You clicked: ");
            builder.AddContent(30, 
#line 16 "C:\Users\Howard\Source\Repos\EMSweb\EMSweb\Pages\Index.razor"
                 ViewProperty

#line default
#line hidden
            );
            builder.CloseElement();
        }
```
Note the loop in there: the sequence number _does not increment within the loop_ - it's pointing the to the code generation, not the output.

**Comment by moataz1991** [comment]
Thanks guys for replying back

to be honest I'm using components differently
my components are not really of type `IComponent` or `ComponentBase` 
they are just of this interface
` public interface IViewComponent
    {
        RenderFragment RenderFragment { get; }
 }`
and then...
```
public interface IInputComponent : IViewComponent
{
     IViewProperty ViewProperty {get;}
     IStyle Style{get;set;}
     ....
     string ComponentHeader {get;set;}
} 

class InputComponent : IInputComponent
{
 //Implementation goes here
 RenderFragment RenderFragment => BuildCompnent;
protected virtual void BuildCompnent(RenderTreeBuilder builder)
}
```

could this be the issue why events within my component are not calling `StateHasChanged` ?

also i tried this..
here i made my TestComponent of type ComponentBase
```
class TestComponent : ComponentBase,IViewComponent
    {
        private IViewProperty _viewProperty;

        public TestComponent(IViewProperty viewProperty)
            => _viewProperty = viewProperty;

        public RenderFragment RenderFragment => BuildRenderTree; // IViewComponent

        protected override void BuildRenderTree(RenderTreeBuilder builder) //ComponentBase
        {
            builder.OpenElement(0, "div");
            builder.AddAttribute(1, "style","min-width:300px");

            builder.OpenElement(2, "input");
            builder.AddAttribute(3, "style", "min-width:300px");
            builder.AddAttribute(4, "onchange", Changed);
            builder.CloseElement();

            builder.OpenElement(5, "label");
            builder.AddContent(6, _viewProperty.PropertyValue ?? "NONE");
            builder.CloseElement();

            builder.CloseElement();
        }

        private void Changed(UIChangeEventArgs e)
        {
            _viewProperty.PropertyValue = e.Value.ToString();
            //StateHasChanged();  => no rendering happens and if uncomment exception rises 'The render handle is not yet assigned'
        }
    }
```

at this point i'm left with nothing but passing `StateHasChanged` from `MainLayout.razor` to all my components and call it manually wherever needed to re-render unless there is a solution to my problem .. maybe a direct way to force render a component ?
