### ISSUE TITLE
MapBlazorHub crashing Blazor Web project

### ISSUE THREAD

**Issue by N0tAI** [aspnet/AspNetCore#13037]
### Describe the bug
Using a Default Blazor Server template in the app.UseEndpoints function in the Configure method of the Startup class
endpoints.MapBlazorHub() throws a exception on app startup
### To Reproduce
1. Using AspNetCore 3 preview 8
2. Run this code IApplicationBuilder#UseEndpoints(endpoints =>
{
     endpoints.MapBlazorHub();
});
3. With these arguments '....'
4. See error:
System.TypeInitializationException: 'The type initializer for 'Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol' threw an exception.'
With the Inner Exception:
MissingMethodException: Method not found: 'System.Text.Json.JsonEncodedText System.Text.Json.JsonEncodedText.Encode(System.String)'.

### Expected behaviour
The Blazor Application starts on the browser with the default pages

### Additional context
I have the latest version of Visual studio preview with Preview Builds enabled, Visual studio has not a problem with me using Core 3 preview 8 before.

[dotnet --info dump.txt](https://github.com/aspnet/AspNetCore/files/3490440/dotnet.--info.dump.txt)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @N0tAI.
It seems you have a binary mismatch in your project. Please share a repro project so we can have a look.

**Comment by N0tAI** [comment]
Here is the Blazor template that Visual Studio makes https://github.com/N0tAI/BlazorTest

**Comment by mkArtakMSFT** [comment]
Thanks @N0tAI.
We aren't able to reproduce this issue. Seems you've got in some weird state with your setup.
Preview8 will be released soon. Can you please remove all your runtime and SDK installs and get the official release and try that out.

**Comment by N0tAI** [comment]
Removing the SDKs and reinstalling them worked! Thanks very much.
