### ISSUE TITLE
DefaultHubLifetimeManager.AddToGroupAsync has backward null check

### ISSUE THREAD

**Issue by crasshacker** [aspnet/AspNetCore#13038]
I was looking through the ASP.NET Core SignalR code to understand what might be causing a bug I'm running into (presumably in my own code, although I'm not yet sure), and found what looks like a bug in DefaultHubLifetimeManager.AddToGroupAsync.  This check appears to be backward:

            var connection = _connections[connectionId];
            if (connection == null)  // ********* I ASSUME THIS SHOULD BE !=
            {
                return Task.CompletedTask;
            }
            _groups.Add(connection, groupName);

I haven't done any testing to verify that this is a bug, but it surely is, right?  Or perhaps this code never actually gets used, as it seems that this would prevent a connection from ever being added to the group.

**Comment by BrennanConroy** [comment]
The check is correct. If a connection is null, return (i.e. does not exist). If a connection is not null (i.e. does exist) add it to the group.

**Comment by BrennanConroy** [comment]
Closing as there doesn't seem to be an issue here. Feel free to reopen if you find a bug!
