### ISSUE TITLE
Enable ` --trust` for `dotnet dev-certs https`

### ISSUE THREAD

**Issue by jinhale** [aspnet/AspNetCore#13048]
I'm trying to complete the tutorial for [VS Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio-code). The instructions instruct to use `dotnet dev-certs https --trust` but that will not yield what is expected. Instead I see: `Specify --help for a list of available options and commands.` 

Ideally, this should work as the tutorial explains it does - the popup should appear giving the option to add the certificate. 

Here is some additional context: 

```
$ uname -a
Linux localhost.localdomain 5.2.5-200.fc30.x86_64 #1 SMP Wed Jul 31 14:37:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     fedora
 OS Version:  30
 OS Platform: Linux
 RID:         fedora.30-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

![image](https://user-images.githubusercontent.com/2700346/62858717-0f245b00-bcc9-11e9-839c-a51ccdaa0455.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jinhale.
@javiercn can you please look into this? Thanks!

**Comment by javiercn** [comment]
Trust is only supported on windows and mac, there's no central trust root on Linux. It's all distro specific. We should add a disclaimer in whatever doc/tutorial we use with Linux, and maybe provide instructions for popular distros, but this falls out of the scope of the tool.

**Comment by mkArtakMSFT** [comment]
@javiercn do we have a separate issue tracking this:
> We should add a disclaimer in whatever doc/tutorial we use with Linux, and maybe provide instructions for popular distros, but this falls out of the scope of the tool.

**Comment by javiercn** [comment]
I'm not even aware this is possible. But we should have a disclaimer for the trust piece on linux.

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore.Docs/issues/13774

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/13781
