### ISSUE TITLE
[Razor] Add error code to application part discovery error

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#13049]
Add an error code to the error created by application part discovery when it can't find an assembly so that it can be filtered properly in visual studio.

![image](https://user-images.githubusercontent.com/6995051/62860187-358bcb80-bcb4-11e9-85d4-747c1c3a20be.png)

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/11226.

/cc @ajaybhargavb
