### ISSUE TITLE
Don't ship .Blazor.* as 3.0.0 (rtm)

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#13054]
Hey build people - this may well already be done or tracked somewhere else, but I just want to make sure.

When we set up for publishing the final 3.0.0 versions of packages, could you please be sure that we **continue using prerelease version numbers** for the client-side Blazor packages? This is because client-side Blazor doesn't ship a final RTM version in 3.0.0.

For example:

 * `Microsoft.AspNetCore.Blazor`, `Microsoft.AspNetCore.Blazor.Build` and siblings in the `aspnetcore` repo
 * `Microsoft.AspNetCore.Blazor.Mono` in the https://github.com/aspnet/Blazor repo

If this is already being taken case of, please feel free just to close.

**Comment by dougbu** [comment]
Adding @danroth27 and @mkArtakMSFT who asked us to rebrand all and sundry as 3.0.0. IIRC the only thing we needed to change was Microsoft.AspNetCore.Blazor.Mono.

Are you asking for the -previewN naming to continue in the otherwise-RTM release? If so, please provide more than examples of packages to special-case. Is it literally Microsoft.AspNetCore.Blazor.*?

**Comment by mkArtakMSFT** [comment]
@dougbu, this is specifically about `client-side Blazor packages`. This is not RTM-ing with 3.0. The server-side Blazor will RTM.

**Comment by dougbu** [comment]
@mkArtakMSFT what does that mean w.r.t. my questions?

I'm asking the second question because going back to 0.{some number}.0 versions would confuse users because everything will be 3.0.0-preview8-{blah} in our next preview.

**Comment by PinpointTownes** [comment]
On a related note, have you ever considered moving the common and client-side packages to a more "neutral" namespace like `Microsoft.Extensions.Components` or `Microsoft.Blazor`?

I started playing with Blazor recently and I must admit the distinction between server-side and client-side Blazor is not as clear as it could be. It's hard to know what world a components/Blazor package belongs to without having a look at the source code 😅

**Comment by mkArtakMSFT** [comment]
@dougbu can we go with `3.0.0-preview8{higher-blah}`? That way we will keep the the versions properly ordered as well as we won't confuse anybody (at least majority of them)?

**Comment by dougbu** [comment]
@mkArtakMSFT as we're locking down for RTM, we could create a couple of variables e.g. `$(BlazorPreReleaseVersionLabel)` and `$(BlazorVersionPrefix)` to keep things separate.
