### ISSUE TITLE
Performance under load is degraded with 3.0 preview7 compared to 2.2

### ISSUE THREAD

**Issue by markvincze** [aspnet/AspNetCore#13058]
### Describe the bug
I have an API which executes a CPU-intensive operation in relatively long-running (500-1000ms) requests. It's implemented in ASP.NET Core 2.2, and running pretty smoothly.

I've upgraded it to ASP.NET Core 3.0 (preview7), mainly to see if the many perf improvements in the framework will bring benefits to our throughput and response times.

The response times of the application, when it's idle and I just send some test requests to it is similar to the 2.2 version.
On the other hand, if I put considerable load on it, the response times start becoming much worse, even though the CPU-load of the machine running the application is only reaching ~40%.
I have a health endpoint (used for the Kubernetes liveness probe) which has the following implementation:
```
IActionResult Get()
{
    return Ok("Healthy");
}
```
Which normally responds in a couple of milliseconds. And even this endpoint slows down by a huge degree, sometimes it takes more than 60 seconds to reply. (I could understand this behavior if the API was severely overloaded, but I'm not putting more load on it than what the 2.2 version could easily handle, and the CPU-load is not even reaching 50%.)

I was wondering if what I'm experiencing is due to thread starvation, but I'm not seeing the `"Microsoft.AspNetCore.Server.Kestrel[22] Heartbeat took longer"` warnings I have seen previously in that situation.

Now I understand that this is very vague, and probably it can be caused by several things.  
What I'm looking for is any kind of suggestion about how I could troubleshoot/investigate this problem to find the root cause. So if you could recommend how I should profile, or what metrics I should monitor to pinpoint the bottleneck, that'd be great!

### Additional context
Nothing was changed in the application code besides adjusting the `Startup.cs` to the 3.0 changes. I'm still using Json.NET for the serialization, and I have `AllowSynchronousIO` set to `true` in the Kestrel options to be able to use `JsonConvert`.
There are no `Wait()`, `.Result` or similar calls on any `Task`s in the application.

The application is running in the Google Kubernetes Engine, the container is based on `mcr.microsoft.com/dotnet/core/runtime-deps:3.0.0-preview7`.
The server nodes are 14-core machines, and the application pods are getting 3 cores each.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @markvincze.
@sebastienros  can you please look into this? Thanks!

**Comment by jkotalik** [comment]
If I were debugging this kind of issue, I would try to verify this performance issue by setting up two images, one running 2.2 and one running 3.0. I'd then use a load client like [wrk](https://github.com/wg/wrk) to hit the healthcheck endpoint. I'd then see if the performance regressed between 2.2 and 3.0.

**Comment by markvincze** [comment]
Hi @jkotalik,

I pretty much have that already, because our production traffic is still served by the 2.2 version, next to which I have the 3.0 version deployed on identical nodes, and I'm shadow mirroring all the traffic to the 3.0 version. This way I can compare the perf of the two versions with identical input.  
But I'll try to repeat this test in a more controlled fashion to double-check my findings.

**Comment by markvincze** [comment]
Since then I found something interesting: we have a custom Prometheus metric (a gauge) which shows how many requests are being executed currently. (The implementation of this metric is pretty straightforward: it's a middleware which increments the metric when a request comes in, and decreases it when the request is done.)  
In the 2.2 version, this metric for an instance of the application looks like this, it fluctuates up and down, its around ~2 on average:

![image](https://user-images.githubusercontent.com/1122274/62921169-343bcb00-bda8-11e9-907d-fb54c66977a5.png)

Now on the 3.0 version the same metric looks like this:

![image](https://user-images.githubusercontent.com/1122274/62921729-d4462400-bda9-11e9-8041-fc694469852e.png)

So it seems that the number of parallel requests being executed is capped at 1. Which suggests that the application is not willing to execute more than 1 request in parallel. This would explain the slowness of the health endpoints too, if somehow the incoming requests are queued, and are only executed in sequence.

I looked over our code base again, but we don't use `lock` or `Monitor` or other synchronization mechanisms, nor do we synchronously wait for `Task`s anywhere.

Is there anything that changed either in the ASP.NET Core pipeline, or in Kestrel, which might explain why the application is not willing to process requests in parallel?

**Comment by markvincze** [comment]
Update: I tried to find the cause by eliminating certain parts of the request execution by commenting them out part by part.  
And if I comment out the main processing done by this API (which is calling into a third party rule engine to do some CPU-intensive processing) and replace it with `await Task.Delay(3000);`, then the concurrency issue is gone, and the number of parallel requests goes up.  
So there is a good chance that this is not related to ASP.NET Core and Kestrel at all. It's probably still related to .NET Core 3.0 vs 2.2, because the same code in 2.2 doesn't have this problem.

**Comment by jkotalik** [comment]
Interesting. Is there a way to can post a snippet of what the main processing API is doing (or a minimal repro)?

**Comment by sebastienros** [comment]
Please take a dump while you are sending many concurrent requests using a tool like Bombardier (https://github.com/codesenberg/bombardier). This way we should see what is blocking in your third party library. And maybe you'll find it by yourself. If the library is public and you can share how you are calling it, or even better provide us with a small app reproducing the issue we can take a look at it.

Waht you could also do locally is use this middleware that will probably show you what part of the code in library is blocking: https://github.com/benaadams/Ben.BlockingDetector

But there it's definitely an issue with your library, not Kestrel.  Having 2.2 handle only 5 requests at the same time is not "a non issue" because 3.0 would only get 1.

**Comment by markvincze** [comment]
@jkotalik @sebastienros,

Thanks for the suggestions!
I haven't had time to do the test with BlockingDetector yet.

But since the `preview8` came out, so I upgraded to that, and with that the issue is suddenly gone, the requests are properly processed in parallel.  
Also, the performance of 3.0 preview8 seems to be significantly better now than 2.2, both in terms of the response times and CPU-utilization. (I'm still doing the analysis, but on first sight the improvement in both aspects seems to be around 20%.)

I'd be curious to know what was causing the blocking in `preview7`, but I'm not sure I'll have time to investigate it, so I'll close this issue.
