### ISSUE TITLE
Enum model binding [FromRoute] behaves differently than [FromBody]

### ISSUE THREAD

**Issue by Tolitech** [aspnet/AspNetCore#13075]
I am getting different behaviors in the bindind model with enum and I can't get the correct value when passing information that is out of the enumeration limit.

What I meant is that when I call Get, Id gets 3 when: http://localhost/test/3 (inside the enum list)
but Id gets 0 when http://localhost/test/5 (outside from the enum list).

I have a TestEnum enumeration containing Test1 = 1, Test2 = 2, Test3 = 3.

In [HttpPost] or [HttpPut] using [FromBody], my object correctly receives the enumeration value, even when I pass a different value like 5 for example.

However, in a Get/Put using [FromRoute], my object correctly receives enumeration when the entered values are within the enumeration limit (1, 2, or 3).

If I pass 5, the value of the enumerator becomes zero, unlike [FromBody] which can receive the value 5 normally even though it is outside of the coded Test1, Test2, and Test3.

```
public enum TestEnum
{
   Test1 = 1,
   Test2 = 2,
   Test3 = 3
}

```

```
public class TestCommand
{
    public TestEnum Id {get; set; }
    public string Name {get; set; }
}

```

It perfectly receives the values even being outside the enumeration limit.

```
[HttpPost]
public async Task<ActionResult<NotificationResult>> Post([FromBody]TestCommand command)
```

Here, in `[FromRoute]` and `[FromBody]` values are perfectly received when they are within the enumeration boundary.

When out of range, `[FromRoute]` gets zero and `[FromBody]` gets 5.

```
[HttpPut("{id:int}")]
public async Task<ActionResult<NotificationResult>> Put([FromRoute]TestEnum id, [FromBody]TestCommand command)
```

Here, in `[FromRoute]` values are perfectly received when they are within the enumeration boundary.

When out of range, `[FromRoute]` gets zero.

```
[HttpGet("{id:int}")]
public async Task<ActionResult<TestQueryResult>> GetById([FromRoute]TestEnum id)

```

I would like to receive the value even if it is outside the encoded limit in enumeration.

**Comment by pranavkm** [comment]
The enum binding in MVC does work to determine if the enum value is a valid value. You should likely see a validation error in `ModelStateDictionary` in the `FromRoute` case. Formatters (likely Json.NET) do not perform this check which is why you see this discrepancy with `FromBody`.

If you really must accept arbitrary values, you could consider accepting an int value and casting it enum. That's just as effective as binding it to an enum that accepts arbitrary values, no?

**Comment by Tolitech** [comment]
The default value of options SuppressBindingUndefinedValueToEnumType is true after .net core 2.1. 

I had to configure as:

services.AddMvc(opt=>
          opt.SuppressBindingUndefinedValueToEnumType=false)
.SetCompatibilityVersion(CompatibilityVersion.Version_2_2); 

Thank you guys.
Problem solved.

**Comment by Tolitech** [comment]
With the upgrade to Core 3.0 it seems that this setting does not exist.

How could I configure asp.net core 3 to enable this feature?
