### ISSUE TITLE
AuthenticatorTokenProvider throws on null key

### ISSUE THREAD

**Issue by brockallen** [aspnet/AspNetCore#13080]
In `AuthenticatorTokenProvider.ValidateAsync` if the `key` returned from the `UserManager` is `null`, then it throws in the call to `Base32.FromBase32`:

https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/Extensions.Core/src/AuthenticatorTokenProvider.cs#L49

Perhaps it should bail out early if `key` is `null`.

**Comment by HaoK** [comment]
Fixed via https://github.com/aspnet/AspNetCore/pull/14037
