### ISSUE TITLE
The layout referenced by _Layout created by Identity Scaffolding is missing

### ISSUE THREAD

**Issue by pstricks-fans** [aspnet/AspNetCore#13088]
I have a brand new Asp.Net Core MVC project named `WebApplication1`. And I added a scaffold identity via `Add|New Scaffolded Items` to this project.

Now I open the `_Layout.cshtml` in `Areas/Identity/Pages/Account/Manage` (see the tree below).

[![enter image description here][1]][1]

Its contents is as follows.

    @{
        Layout = "/Areas/Identity/Pages/_Layout.cshtml";
    }
    
    <h1>Manage your account</h1>
    
    <div>
        <h4>Change your account settings</h4>
        <hr />
        <div class="row">
            <div class="col-md-3">
                <partial name="_ManageNav" />
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
    
    @section Scripts {
        @RenderSection("Scripts", required: false)
    }

# Question

As we can see this layout is referencing another layout `/Areas/Identity/Pages/_Layout.cshtml`. However, I cannot find the referenced layout. Where is it?

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/6N45R.png
  [2]: https://i.stack.imgur.com/wLxkS.png

**Comment by blowdart** [comment]
@HaoK

**Comment by HaoK** [comment]
Its in the identity UI package

**Comment by HaoK** [comment]
You can scaffold out that layout page as well if you want to edit it
