### ISSUE TITLE
Best practice to dispose SignalR HubConnection in .NET Core

### ISSUE THREAD

**Issue by jasonycw** [aspnet/AspNetCore#13082]
Is there a best practice or suggestion for how to stop/dispose `HubConnection`?

Since `HubConnection` is not `IDisposable`, we cannot use `using`, any suggestion if we need to use `StopAsync` and `DisposeAsync` explicitly?

Any performance impact to use or not to use `StopAsync` and `DisposeAsync`?

From the [doc](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2), there is no mention of whether we need or should dispose the `HubConnection`

**Comment by BrennanConroy** [comment]
If you don't call `StopAsync` then your connection will still be active which will have a minor performance impact as it will have network traffic and possible message processing.

As far as disposing, it isn't necessary, but it's always a best practice to dispose disposable objects when you're done with them.

**Comment by anurse** [comment]
The plan is to implement `IAsyncDisposable` on `HubConnection` where possible. Once we do that, you'll be able to use `await using` (or `using await`? I never remember which it is) to do things cleanly. We haven't done that yet, but we'll look at it. That stuff landed a bit late and we haven't reacted to it yet.

Calling `StopAsync` is definitely preferred, but not required. `DisposeAsync` should do it for you if you haven't already stopped.

Until there's `IAsyncDisposable` support, I'd recommend using the `try..finally` pattern (which is what `await using` expands out to anyway), like this:

```csharp
var connection = new HubConnectionBuilder()
	.WithUrl(...)
	.Build();
try
{
	await connection.StartAsync();
	// Do your stuff
	await connection.StopAsync();
}
finally
{
	await connection.DisposeAsync();
}

**Comment by anurse** [comment]
We'll add `IAsyncDisposable` to the `HubConnection` in the `netstandard2.1` target (so that .NET Core 3.0 consumers get the new syntax). `netstandard2.0` consumers will have to continue with the `try...finally` syntax.

**Comment by springy76** [comment]
Ok, version 3.0.0 is out, where is IAsyncDisposable on HubConnection?

**Comment by BrennanConroy** [comment]
The change was made in the 5.0.0 branch.

In 3.0 you can still use `await using` because `HubConnection` has the `DisposeAsync` method.
