### ISSUE TITLE
InteropReliabilityTests are still flaky

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#13086]
We hoped that some of the [recent changes](https://github.com/aspnet/AspNetCore/commit/ab006e10b0e1271fc5e78a031dc880b11fe64edf) would have stabilised them, but since then most of the `release/3.0` builds are still failing, and 3 out of the last 5 `release/3.0` build failures had test failures from `InteropReliabilityTests`.

Here are the last 5 failures:

Commit | Failures
-- | --
[ApiAuthorization] Update to latest oidc-client and   IdentityServer4 | `RegisterAddresses_IPv6Port5000Default_Success`,   `EventHandlerThrowsSyncExceptionTerminatesTheCircuit`
Complete upload streams on connection close (#13065) | `JSInteropThrowsInUserCode`,   `ContinuesWorkingAfterInvalidAsyncReturnCallback`
Add 'firstTime' parameter to OnAfterRender | `ContinuesWorkingAfterInvalidAsyncReturnCallback`
Factor out auth and forms. Fixes #12950 (#12999) | `Linux-Release.ShutdownTestRun`
Update Mono debug proxy code (#13053) | Unclear – no test failures listed

@javiercn and I spoke and we think that `InteropReliabilityTests` is missing some necessarily logic to wait for its assertions to become true.

**Comment by mkArtakMSFT** [comment]
@rynowak would you like to tackle this?

**Comment by javiercn** [comment]
We need to wrap the calls that use HubConnection directly with ExpectX where X is either a renderbatch, JSError or similar.

The tests are not waiting for that, so the assertions on the result might happen before the side effect occurs.

It should be easy and mechanical.
