### ISSUE TITLE
EXEC : error : Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#13093]
_From @vikramtamboli on Monday, August 12, 2019 5:30:09 AM_

Hi Team,

We are trying to compile source from https://github.com/SteveSandersonMS/presentation-2019-06-NDCOslo/tree/master/demos/MissionControl

**When we run below command we get exception
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server>dotnet build**

Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj]
Restore completed in 108.36 ms for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj.
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
Restore completed in 505.88 ms for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj.
Restore completed in 1.03 sec for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\PinMapLibrary\PinMapLibrary.csproj.
Restore completed in 35.97 ms for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Shared\MissionControl.Shared.csproj.
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
MissionControl.Shared -> D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Shared\bin\Debug\netstandard2.0\MissionControl.Shared.dll
PinMapLibrary -> D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\PinMapLibrary\bin\Debug\netstandard2.0\PinMapLibrary.dll
MissionControl.Client -> D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\bin\Debug\netstandard2.0\MissionControl.Client.dll
_**EXEC : error : Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]
at Microsoft.AspNetCore.Blazor.Build.BootJsonWriter.GetBootJsonContent(String assemblyFileName, String entryPoint, String[] assemblyReferences, IEnumerable`1 embeddedContent, Boolean linkerEnabled)
at Microsoft.AspNetCore.Blazor.Build.BootJsonWriter.WriteFile(String assemblyPath, String[] assemblyReferences, String[] embeddedResourcesSources, Boolean linkerEnabled, String outputPath)
at Microsoft.AspNetCore.Blazor.Build.DevServer.Commands.WriteBootJsonCommand.<>c__DisplayClass0_0.b__0()
C:\Users\349185.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets\Blazor.MonoRuntime.targets(633,5): error MSB3073: The command "dotnet "C:\Users\349185.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json "obj\Debug\netstandard2.0\MissionControl.Client.dll" --references "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\bootjson-references.txt" --embedded-resources "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\embedded.resources.txt" --linker-enabled --output "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\blazor.boot.json"" exited with code 1. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]**_

Build FAILED.

D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj]
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
EXEC : error : Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]
C:\Users\349185.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets\Blazor.MonoRuntime.targets(633,5): error MSB3073: The command "dotnet "C:\Users\349185.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json "obj\Debug\netstandard2.0\MissionControl.Client.dll" --references "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\bootjson-references.txt" --embedded-resources "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\embedded.resources.txt" --linker-enabled --output "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\blazor.boot.json"" exited with code 1. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]
4 Warning(s)
2 Error(s)

Time Elapsed 00:00:13.34

_Copied from original issue: dotnet/corefx#40241_

**Comment by pranavkm** [comment]
_From @aeastham67 on Monday, August 12, 2019 11:21:44 AM_

I just saw this too. Is there a workround for this? Thanks

**Comment by pranavkm** [comment]
_From @aeastham67 on Monday, August 12, 2019 11:54:11 AM_

For info, I just updated Microsoft.AspNetCore.Blazor and Microsoft.AspNetCore.Blazor.Build to Latest Prerelease 3.0.0-preview-7.193365.7 which fixed this.

**Comment by pranavkm** [comment]
_From @steveharter on Monday, August 12, 2019 8:52:31 PM_

@pranavkm @rynowak PTAL. Some versioning issues? Looks like upgrading to latest addresses the issue.

**Comment by pranavkm** [comment]
_From @pranavkm on Monday, August 12, 2019 10:13:34 PM_

@vikramtamboli, it's likely that you have a preview7 SDK \ runtime installed which had a couple of API breaking changes. As @aeastham67 pointed out, upgrading to preview7 should resolve the issue. Feel free to file a new issue in https://github.com/aspnet/AspNetCore/issues if you're still seeing this after you upgrade.

**Comment by pranavkm** [comment]
_From @vikramtamboli on Tuesday, August 13, 2019 5:00:07 AM_

Thanks for the help 

**My dotnet version is 3.0.100-preview7-012821**

@aeastham67  - I already upgraded to latest preview packages available in nuget for all projects still not able to compile
tried with visual studio 2019 preview version as well
also tried adding System.Text.Json to MissionControl.Client

![image](https://user-images.githubusercontent.com/16055034/62916128-f3ae6400-bd4b-11e9-9b47-07e80df701cd.png)

![image](https://user-images.githubusercontent.com/16055034/62916173-1f314e80-bd4c-11e9-936d-5242df68ddf9.png)


little more help needed here to get this working

**Comment by pranavkm** [comment]
_From @pranavkm on Tuesday, August 13, 2019 12:36:39 PM_

@vikramtamboli could you include the output from `dotnet --info`?

**Comment by pranavkm** [comment]
_From @vikramtamboli on Tuesday, August 13, 2019 2:07:10 PM_

C:\Users>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by ahsonkhan** [comment]
Is there an update on this issue?

@vikramtamboli, is this still reproducible for you with 3.0-preview9 bits?

**Comment by carlocardella** [comment]
I'm getting this error even with 3.0 GA:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.505 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by gabrielfreire** [comment]
im also having this issue

**Comment by carlocardella** [comment]
In my scenario I was writing a Powershell cmdlet for PSCore and while I was running dotnet3 I had imported the nuget package `System.Management.Automation` v. `6.2.x`; the error went away after I switched to `7.0.0-preview.4`

**Comment by TulyOpt** [comment]
im also having this issue using Identityserver4.


Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 
  Microsoft.NETCore.App 3.0.0-preview-27324-5
`

**Comment by markgr** [comment]
I'm getting this by trying to use the Microsoft.AspNetCore.ProtectedBrowserStorage library which I know is in Alpha - damn annoying as it seemed a great way to use SessionStorage :(

I have the following SDKS installed

3.0.100-preview7-012821 [/usr/local/share/dotnet/sdk]
3.0.100-preview8-013656 [/usr/local/share/dotnet/sdk]
3.0.100-preview9-014004 [/usr/local/share/dotnet/sdk]
3.0.100-rc1-014190 [/usr/local/share/dotnet/sdk]
3.0.100 [/usr/local/share/dotnet/sdk]

And runtimes
Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0-preview9-19423-09 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0-rc1-19456-20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

I'm building and running on a Mac - maybe that's the issue?

**Comment by TulyOpt** [comment]
Hi @markgr , i solved my problem using the  .NET Core 3.0 GA  instead of the preview one. See https://github.com/dotnet/corefx/issues/41591

**Comment by dtate22** [comment]
On 10/15/2019 @ 5:54 pm - I spent 2 hours trying everything in this thread.
- I tried the simplest solutions including just switching my versions of Microsoft.NetCore
- I also attempted to use different methods to parse
- Because I'm on a timeline, I had to drop back and punt because my code has to be production ready and I cannot afford to take too many changes and break my release cycle

The System.Text.Json is just not mature enough.
- I had to drop back from
OpportunityChangesLastXMins oBody = JsonSerializer.Deserialize<OpportunityChangesLastXMins>(sJSON);

- To:
OpportunityChangesLastXMins oBody = JsonConvert.DeserializeObject<OpportunityChangesLastXMins>(sJSON);

I tried almost everything in this chain.

**Comment by markgr** [comment]
@TulyOpt I created a basic server webapp and even with the GA release can still repo the problem....

Pull https://github.com/markgr/BlazorJson

Then run it (dotnet run)

Open Index page and click the 'Test Storage' button - you'll get the exception in the Console....

dotnet --list-sdks
2.1.505 [/usr/local/share/dotnet/sdk]
2.2.104 [/usr/local/share/dotnet/sdk]
2.2.105 [/usr/local/share/dotnet/sdk]
2.2.401 [/usr/local/share/dotnet/sdk]
3.0.100 [/usr/local/share/dotnet/sdk]


dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by pranavkm** [comment]
@markgr your project's referencing a package that's likely compiled against a preview release of .NET Core.

@dtate22 it's not clear what's causing the issue, but it's most likely an out-of-date reference. I may be mistaken, but I don't think .NET Core 3.0 is supported on Azure Functions as yet, I'm not sure if using ASP.NET Core 3.0 with it is going to ultimately succeed at this point.

Generally you should only see this error if you're referencing a package \ library that was compiled against a preview build of .NET Core or the System.Text.Json package. Since 3.0 is now RTM, we anticipate library authors to rebuild against the RTM versions of the framework which should resolve this issue.

If you're still seeing this issue, please file separate issues possibly with a minimal repro app.

**Comment by ahsonkhan** [comment]
> Also, I will say this, I'm using Azure functions to code my solution and the code ONLY breaks in the Visual Studio Azure functions testing harness.

@dtate22, The Azure Functions host pins the assembly version it loads and since it generally lags behind the latest releases, you'd see type mismatch/missing issue until AF catches to the latest version of .NET Core - this is a known issue specific to AF - feel free to follow up on https://github.com/Azure/azure-functions-host

See related issues: https://github.com/Azure/azure-functions-host/issues/4906 / https://github.com/Azure/azure-functions-host/issues/5031

**Comment by dtate22** [comment]
@ahsonkhan  - Hey man, thanks for the information... (Thanks for the information - I will go to the URL listed above)
- It's crazy how many different places you have to look to solve a problem.

@pranavkm - I used the following tested versions before posting to the blog.  I didn't want to mis-lead people because I hadn't done my research
- .netCore 2.0 - failed (nuget System.Text.Json version)
- .netCore 2.1 - failed (nuget System.Text.Json version)
- .netCore 2.2 - failed (nuget System.Text.Json version)
- .netCore 3.0 - failed (for this version, I had to uninstall the packages because the JSON is native)
- .netCore 3.1 - failed - would not compile my Azure Function

You guys are great - thanks for helping me out by posting the information above - appreciate it!

Later
