### ISSUE TITLE
[Blazor] preview8 @ref codegen field does work in intellisense but not on build

### ISSUE THREAD

**Issue by campersau** [aspnet/AspNetCore#13099]
### Describe the bug
The automatic field generation for `@ref` does work inside visual studio intellisense but not when building the project.

### To Reproduce
1. Using dotnet `3.0.100-preview8-013656` and VS `16.3.0 Preview 2.0`
2. Create new blazor server-side project.
3. Add `@ref="ele"` to an element inside of the `Counter` component
4. Reference the field inside of `@code`. E.g. `ele.ToString();`
5. Intellisense is working fine.
6. Build results in error: `Pages\Counter.razor(14,9,14,12): error CS0103: Der Name "ele" ist im aktuellen Kontext nicht vorhanden.`

### Expected behavior
Code should compile.

### Screenshots
![image](https://user-images.githubusercontent.com/4009570/62976934-042f0f00-be1e-11e9-9967-e82a28377595.png)

### Additional context
Workaround is to `@ref:suppressField="ele"` and add the field manually.

```
.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mkArtakMSFT** [comment]
@javiercn can you please look into this? Thanks!

**Comment by divinci** [comment]
Yes I can confirm the issue.  A workaround is needed as this will break a lot of projects.

**Comment by KrystofZacek** [comment]
Same here. Serious bug.

**Comment by stavroskasidis** [comment]
As a workaround you can add the `@ref:suppressField` to revert to the old behaviour

**Comment by dodyg** [comment]
Yup. The feature doesn't work.

![blazor-error-2](https://user-images.githubusercontent.com/1761249/63033892-ab608480-beb8-11e9-99d7-7ed66bf6d290.png)

**Comment by julienGrd** [comment]
the workaround not work for (but i'm not really how to use it)
I precise i have a separate cs file for the controller of my razor components
````
<input type="password" class="form-control" @bind-value="this.Model.Password" @bind-value:event="oninput" @onkeydown="@OnKeyDownPassword" @ref:suppressField="@inputPassword" />
protected ElementReference inputPassword { get; set; }
````

It build, but when i launch it i have this error in the chrome console
Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '@ref:suppressfield' is not a valid attribute name.

anybody success tu use the workaround ?

thanks !

**Comment by dodyg** [comment]
@julienGrd 
Use it like this

```
<Show @ref="_showRef"  @ref:suppressField Number="Number" />```

**Comment by julienGrd** [comment]
> @julienGrd
> Use it like this
> 
> ```
> <Show @ref="_showRef"  @ref:suppressField Number="Number" />
> ```

thanks it works ! i was pretty sure i was not using the good syntax :-)

**Comment by NTaylorMullen** [comment]
Ya I can reproduce this, working on a fix. @shirhatti @danroth27 we should update the blog post (and anywhere else relevant) to mention that this feature does not work as intended.

**Comment by rynowak** [comment]
Does anyone have a repro that causes a compiler crash?

**Comment by stavroskasidis** [comment]
Any chance for a patch/hotfix/new build ?

**Comment by NTaylorMullen** [comment]
Sorry folks to do this, but here's the latest: https://github.com/aspnet/Announcements/issues/381

**Comment by springy76** [comment]
Lol, so no one tested this new feature before releasing it?
