### ISSUE TITLE
Why do the templates not use the async method for rendering sections (RenderSectionAsync)?

### ISSUE THREAD

**Issue by poke** [aspnet/AspNetCore#13091]
When looking at the Razor layouts that are included in the [standard templates](https://github.com/aspnet/AspNetCore/blob/v3.0.0-preview8.19405.7/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Views/Shared/_Layout.cshtml), why do they use the synchronous method `RenderSection` instead of the asynchronous `RenderSectionAsync`?

Looking at the [implementation of `RenderSection`](https://github.com/aspnet/AspNetCore/blob/v3.0.0-preview8.19405.7/src/Mvc/Mvc.Razor/src/RazorPage.cs#L129-L130), it will actually block using an awaiter:

```c#
var task = RenderSectionAsyncCore(name, required);
return task.GetAwaiter().GetResult();
```

That seems to be an odd preference to make in the default templates.

I understand that it may look somewhat verbose to do `@await RenderSectionAsync("foo")` instead of just `@RenderSection("foo")` but if there was no difference, then what would be the point of the async method? And while the `Script` sections probably won’t contain that much content, showing users how to do it “properly” would probably still be a good thing to do.

**Comment by mkArtakMSFT** [comment]
Thanks @poke. We'll address that for the 5.0 release.

**Comment by poke** [comment]
Cool, good to know that it wasn’t a deliberate choice then!

If you want, then I could submit a PR to update the templates later.

**Comment by mkArtakMSFT** [comment]
That would be great.
> If you want, then I could submit a PR to update the templates later.

**Comment by poke** [comment]
My PR was merged so this can be closed 😊

**Comment by NTaylorMullen** [comment]
Thanks @poke!
