### ISSUE TITLE
[Blazor] Add #region to razor pages

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore#13109]
Please add #region support to html tag area on razor pages. One of my components is over 1000 lines and not really optimal to breakout to other sub-components. And that's with the c# code behind in another page

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @VR-Architect.
This is not something we would support.
However, having that much content in a component is surprising. What prevents you from splitting it out?
Also, you can use the folding of html tags in the editor.

**Comment by VR-Architect** [comment]
I have a a properties table (th:label, th:UiControl) with about 100 properties which all act on the same object. I could break them up to smaller components, but it really is a single component. 

I use the html folding method now. The issue with using the html folding tags is when you fold a <tr> tag we can't see some reference to whats inside that tr tag. So I end up open and closing the tags constantly to find the one I want. OK, so let's put a name inside the <tr> tag, well  when folded it doesn't show the name.

So I used a <div name="mySection"> around a group of <tr> tags; however, VS complains "The element div cannot be nested inside <tbody>". 

Thus my request for #region

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @VR-Architect. Sounds like the tag wrapping would satisfy your needs, if those two concerns are resolved. I suggest reporting these asks through VS Feedback so the team responsible for HTML element folding can see and potentially improve.

**Comment by Augmensis** [comment]
@VR-Architect Actually, you can use Html regions in all of your razor pages and components:

```
<!-- #region SomeOptionalName -->
<div>
<p>Foo</p>
...
</div>
<!-- #endregion SomeOptionalName -->
```


You can also use the standard #region syntax within the @code{ } block of your razor page:
```
@code {
    #region anotherOptionalName
    public string Foo { get; set; }
    ...
    #endregion anotherOptionalName
}
```
