### ISSUE TITLE
Platform Manifest in ASP.NET Core targeting pack should use the targeting pack package name

### ISSUE THREAD

**Issue by dsplaisted** [aspnet/AspNetCore#13108]
In the ASP.NET Core targeting pack (Microsoft.AspNetCore.App.Ref), there is a `data/PlatformManifest.txt` file which includes assembly and file versions for the contents of the targeting pack.  This is an optimization so that the files don't need to be read from disk to get these versions for conflict resolution.  The format looks like this:

```
aspnetcorev2_inprocess.dll|Microsoft.AspNetCore.App||13.0.19219.0
Microsoft.AspNetCore.Antiforgery.dll|Microsoft.AspNetCore.App|3.0.0.0|3.0.19.40702
Microsoft.AspNetCore.Authentication.Abstractions.dll|Microsoft.AspNetCore.App|3.0.0.0|3.0.19.40702
```

The second element is interpreted as the package name.  This should be updated to match the targeting pack package name, or Microsoft.AspNetCore.App.Ref.  As it is currently, the versions from the platform manifest aren't being used by conflict resolution, as it thinks they apply to files from a different package name.

**Comment by dsplaisted** [comment]
@jkotalik @JunTaoLuo I think this should be a simple fix.  We'd like to take it through ask mode (for Preview 9) this week if possible.

**Comment by anurse** [comment]
I'm not entirely clear on why this issue is arising now. I presume things are *working* today or we'd have encountered an issue in our testing. Is this mostly a missed optimization?

**Comment by JunTaoLuo** [comment]
@jkotalik fixed this, closing
