### ISSUE TITLE
[RazorSDK] Cleanup references to LangVersion in RazorSDK

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#13114]
We need to update RazorSDK to no longer specify a `LangVersion` for `netcoreapp3.0` \ `ns2.1` targeting projects:

•	https://github.com/aspnet/AspNetCore-Tooling/blob/21fcd9c2f59296a7e38e1f5ff056281a16166d52/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets#L115-L117 
•	https://github.com/aspnet/AspNetCore-Tooling/blob/21fcd9c2f59296a7e38e1f5ff056281a16166d52/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets#L183-L187

**Comment by ajaybhargavb** [comment]
@pranavkm why do we want to do this?

**Comment by pranavkm** [comment]
Our build targets need to mirror what's in Roslyn's targets: https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets. My guess is that we need to effectively replace the highlighted sections with https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L6-L10 in the Razor.Compilation.targets and remove the highligted section from Component.targets.
