### ISSUE TITLE
SecurityStampValidatorOptions.ValidationInterval re-issue cookie and expiry extended

### ISSUE THREAD

**Issue by arisliang** [aspnet/AspNetCore#13117]
### Describe the bug
When security stamp validator validates true, it re-issues the cookie and auth cookie expiry date.

### To Reproduce
1. Using this version of ASP.NET Core '2.1'
2. Code:
>services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie();
services.Configure<SecurityStampValidatorOptions>(options =>
            {
                options.ValidationInterval = new TimeSpan(0, 0, 0);
}
services.ConfigureApplicationCookie(options =>
            {
                options.ExpireTimeSpan = new TimeSpan(1, 0, 0);
                options.SlidingExpiration = false;
            });

### Expected behavior
To my understanding, when security stamp validator validates true, it should do nothing, not re-issue cookie.
![Capture](https://user-images.githubusercontent.com/1115503/63007570-79005880-beb3-11e9-9031-5cb26fc3b194.PNG)

**Comment by blowdart** [comment]
This is by design, for sliding expiration. It's not happening within the validator, it's happening as part of the overall cookie refresh handling
