### ISSUE TITLE
.AddDefaultUI(UIFramework.Bootstrap4) - 'UIFramework' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by dotnetshadow** [aspnet/AspNetCore#13111]
### Describe the bug
'UIFramework' is inaccessible due to its protection level

### To Reproduce
1. Using this version of ASP.NET Core 3.0 preview 8
2. `services.AddDefaultIdentity<IdentityUser>().AddDefaultUI(UIFramework.Bootstrap3)`

### Expected behavior
Issue #9516 suggests that it should still be available?

**Comment by blowdart** [comment]
@javiercn is this connected to the removal work you did?

**Comment by javiercn** [comment]
Yes,

You don't need to call `AddDefaultUI(UIFramework.Bootstrap3)` anymore. Simply add `<IdentityUIFrameworkVersion>Bootstrap3</IdentityUIFrameworkVersion>` to your project file instead and you should be good.

See the announcement here. https://github.com/aspnet/Announcements/issues/380
