### ISSUE TITLE
[Blazor] Can not stop Blazor to re-render on events

### ISSUE THREAD

**Issue by syedqutub** [aspnet/AspNetCore#13118]
In Blazor an event (such as onclick) triggers blazor to re-render the page. but i can not stop this.
fpr eg if i want to capture the value of the input bpx on "onkeypress" event but do not want the state to re-render on every key but only on "Enter" key. the StateHasChanged will always be triggerd even if i haven't  reassigned a field. how to stop events from state re-render but rather have option to manually re-render.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @syedqutub.
You can implement `IHandleEvents` interface for your component to do this.
