### ISSUE TITLE
File validation issues

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#13113]
This issue will be used to collect all info related to the verification data for **3.0.0-Preview 9** release:

Build to use: daily build from https://github.com/dotnet/core-sdk#installers-and-binaries
If you plan to create any Azure resources specifically for the verification work, please create those in the **3.0-p9-validation** resource group, in the **ASP.NET Core Test** subscription.

Make sure to create the issues in aspnet/AspNetCore repo and apply the proper area label and `Validation` label. Put the issue in `3.0.0-preview9` milestone.

The project to use to assign issues to: 

After you create the issues, add them to the https://github.com/aspnet/AspNetCore/projects/4 project and unassign yourself from this issue.

**Comment by ajaybhargavb** [comment]
Filed https://github.com/aspnet/AspNetCore/issues/13199

**Comment by dougbu** [comment]
Is this about validation work our team does or something else?

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/issues/13254
https://github.com/aspnet/AspNetCore/issues/13255
https://github.com/aspnet/AspNetCore/issues/13256
https://github.com/aspnet/AspNetCore/issues/13257

**Comment by javiercn** [comment]
@dougbu This is about our team's validation.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/AspNetCore/issues/13178
https://github.com/aspnet/AspNetCore/issues/13076
https://github.com/aspnet/AspNetCore/issues/13074
https://github.com/aspnet/AspNetCore/issues/13073
https://github.com/aspnet/AspNetCore/issues/13072
https://github.com/aspnet/AspNetCore/issues/13071

**Comment by rynowak** [comment]
https://github.com/aspnet/AspNetCore/issues/13282

**Comment by pranavkm** [comment]
Unassigning @SteveSandersonMS since he's out most of validation week.

**Comment by NTaylorMullen** [comment]
My validation is done.

**Comment by SteveSandersonMS** [comment]
https://github.com/aspnet/AspNetCore/issues/13334
https://github.com/aspnet/AspNetCore/issues/13335
https://github.com/aspnet/AspNetCore/issues/13336
https://github.com/aspnet/AspNetCore/issues/13337

**Comment by ryanbrandenburg** [comment]
https://github.com/aspnet/AspNetCore/issues/13387
