### ISSUE TITLE
After updating visual studio 2019 preview getting error

### ISSUE THREAD

**Issue by ajai1109** [aspnet/AspNetCore#13123]
The type or namespace name 'Layouts' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)

**Comment by sven5** [comment]
@ajai1109 

In the [release notes](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/) we can read:

> Remove use of namespace `Microsoft.AspNetCore.Components.Layouts`.

So you'll have to remove this reference.

**Comment by ajai1109** [comment]
> @ajai1109
> 
> In the [release notes](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/) we can read:
> 
> > Remove use of namespace `Microsoft.AspNetCore.Components.Layouts`.
> 
> So you'll have to remove this reference.

Thanks! I am getting some other errors like

**Comment by salmanmkc** [comment]
yeah had this same issue, thanks for pointing out that it needed to be removed, fixed now, also there was an overriding method from the template which no longer needs to be marked overrieded and will compile with errors if marked as overrided
