### ISSUE TITLE
@onclick No Longer Functions After Upgrade

### ISSUE THREAD

**Issue by kevingates** [aspnet/AspNetCore#13127]
### Describe the bug
The method is never called when using the `@onclick` attribute.

### To Reproduce
1. Using this version of ASP.NET Core : 3.0.100 Preview 8 (8/13/2019)
2. Run this code : Create Server-Side Blazor app via template
3. With these arguments: Click the Counter's page "button" to increment count
4. See error: nothing happens

### Expected behavior
I expect my method to be called when a button with `@onclick="methodName"` is pressed. 

### Additional context
Include the output of `dotnet --info`

I first realized this on my custom Blazor Page Component, then went back and tested this on the default template Counter page -- error persists.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by kevingates** [comment]
This ended up being a change I didn't realize I made while debugging. 
```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub<App>(selector: "app");
                endpoints.MapFallbackToPage("/_Host");
            });
```
The MapBlazorHub had a modification and this was a crucial piece.
