### ISSUE TITLE
Extend PasswordHasherOptions to include SubKey Length

### ISSUE THREAD

**Issue by MarkLie** [aspnet/AspNetCore#13131]
### Problem Description
I would like to use the [PasswordHasher](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Core/src/PasswordHasher.cs) class in a Keycloak compatible way. The only thing that hinders me to do so, is the hard coded subkey length of 256 bit (parameter `numBytesRequested`).

```
private byte[] HashPasswordV3(string password, RandomNumberGenerator rng)
{
	return HashPasswordV3(password, rng,
		prf: KeyDerivationPrf.HMACSHA256,
		iterCount: _iterCount,
		saltSize: 128 / 8,
		numBytesRequested: 256 / 8);
}
```

Keycloak uses a length of 512 bit (also hard coded).

### Solution Proposal
From my point of view a desired solution would be to include the subkey length in the [PasswordHasherOptions ](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Core/src/PasswordHasherOptions.cs) class (similar to IterationCount) and to initialize PasswordHasher in its constructor appropriately.

**Comment by blowdart** [comment]
The password hasher is meant for identity's standard formats. It's not mean as an extensiblity point and adding a new format to support an external product isn't on the cards,
