### ISSUE TITLE
HttpSys cannot support listener with support for NTLM, Negotiate and Bearer authentication

### ISSUE THREAD

**Issue by tornie2** [aspnet/AspNetCore#13135]
We are migrating our http-services from .net 461 to .net core. However we cannot see how we can implement support for authentication through NTLM, Negotiate and JWT in the same listener.

In .net 461 we were able to do this using the AuthenticationSchemeSelectorDelegate in the Configure method

                var listener = (HttpListener)appBuilder.Properties[typeof(HttpListener).FullName];
                listener.AuthenticationSchemeSelectorDelegate = _authFlow.EvaluateAuthentication;

The EvaluateAuthentication was implemented something like this (The bearer token was validated later in the pipeline

        public AuthenticationSchemes EvaluateAuthentication(HttpListenerRequest request)
        {
            if (request.HttpMethod == "OPTIONS")
                return AuthenticationSchemes.Anonymous;

            if (request.Headers["Authorization"] != null && request.Headers["Authorization"].Contains("Bearer "))
                return AuthenticationSchemes.Anonymous;

            return AuthenticationSchemes.IntegratedWindowsAuthentication;
        }

We have not been able to find a simlar exit to select authentication in AspNetCore. Our latest approach is to create the HttpSys with NTLM and Negotiate

            var host = new WebHostBuilder()
                .UseHttpSys(options =>
                {
                    options.Authentication.Schemes = AuthenticationSchemes.NTLM | AuthenticationSchemes.Negotiate;
                    options.Authentication.AllowAnonymous = false;
                })
                .UseUrls($"http://+:{portNo}/")
                .UseStartup<StartUp>()
                .ConfigureLogging((hostingContext, logging) => { logging.AddConsole(); })
                .Build();

and then add Jwt support in the ConfigureServices in StartUp

            services.AddAuthentication(o =>
            {
                o.DefaultAuthenticateScheme = HttpSysDefaults.AuthenticationScheme;
                o.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(o => { o.Events = new JwtBearerEvents { OnTokenValidated = JwtAuthentication.VerifyJwt }; });

However it does not seem to have any effect. A request with Bearer token will never be forwarded to the pipeline by HttpSys

Full reproduce is here
[HttpHost.zip](https://github.com/aspnet/AspNetCore/files/3502804/HttpHost.zip)

Is it possible to support all these three authentication methods with AspNetCore ?

**Comment by blowdart** [comment]
@Tratcher any pointers?

**Comment by Tratcher** [comment]
I'm out at the moment but here are some things to try.

Are these all required on the same endpoints or do you need Bearer for some and Windows for others?

AllowAnonymous must be `true` for the Bearer tokens to get through.

The code you have in EvaluateAuthentication can move to a custom middleware that calls AuthenticateAsync or ChallengeAsync with the appropriate scheme. You may also be able to implement a virtual auth scheme that delegates as needed.

Not sure about DefaultAuthenticate/ChallengeScheme yet, it depends on how the other steps work out for you.

**Comment by tornie2** [comment]
We need these three authentication methods on the same endpoint

Thanks for the pointers. We will try AllowAnonymous = true.
I suppose we could just validate later in the pipeline and return 407 if neither of the three are given.

I have one concern though.
If I change AllowAnonymous to true, won't that be reflected in a response to an OPTIONS request?
Can I remove anonymous from the response to OPTIONS ?

Thanks

**Comment by tornie2** [comment]
We have this working now. 
Thanks for pointing us in the right direction.

For anyone else struggling with the same issue, basically this is not a supported scenario.
So the trick is to get the message out of HttpSys and in to the pipeline, where you can do your own authentication.

And you do that by using AllowAnonymous = true, as Tatcher correctly pointed out.

**Comment by blowdart** [comment]
Closing as by design as you say you have it working.
