### ISSUE TITLE
HttpClient cant authenticate when site is published Blazor Core hosted .Net 3.0 Preview7

### ISSUE THREAD

**Issue by Pilchie** [aspnet/AspNetCore#13139]
_From @Garderoben on Thursday, August 8, 2019 8:18:52 AM_

# Issue Title

HttpClient cant authenticate with Bearer when site is published and running in IIS works fine from visual studio.

# General

Maybe im missing something new but i tried the token thats given from both my machine and the publised server in Postman and it works. But from the application it throws "Response status code does not indicate success: 401 (Unauthorized)."

This code was working fine in .net core 2.2 but i made a new project and moving over to .Net Core 3.0 Preview 7 (**Both projects are Blazor ASP.NET Core hosted project**)
![Dotnetproblem](https://user-images.githubusercontent.com/10367109/62686635-64105a80-b9c5-11e9-826e-ecad01e3631c.png)

# .NET Core version on developing machine
![DotnetDevelopComputer](https://user-images.githubusercontent.com/10367109/62686739-928e3580-b9c5-11e9-886b-38107555a26e.png)
# .NET Core version on published machine
![DotnetServerProblem](https://user-images.githubusercontent.com/10367109/62686767-a33eab80-b9c5-11e9-8f3e-eb4ff8f38ee4.png)

_Copied from original issue: dotnet/core#3162_

**Comment by Pilchie** [comment]
_From @carlossanlop on Monday, August 12, 2019 6:04:10 PM_

@Pilchie is this something your team can help with?

**Comment by Pilchie** [comment]
_From @Pilchie on Wednesday, August 14, 2019 5:58:24 PM_

@mkArtakMSFT @danroth27 @blowdart ?

**Comment by Pilchie** [comment]
_From @blowdart on Wednesday, August 14, 2019 8:13:56 PM_

Move it to our repo?

There's no enough to go on here.

- Where are tokens issued from?
- What authentication and authorization services are configured and how?
- Contents of startup.cs, with any secrets removed.

All of the above is needed.

**Comment by Pilchie** [comment]
@Garderoben - can you answer some of the questions above?

**Comment by Garderoben** [comment]
> _From @blowdart on Wednesday, August 14, 2019 8:13:56 PM_
> 
> Move it to our repo?
> 
> There's no enough to go on here.
> 
> * Where are tokens issued from?
> * What authentication and authorization services are configured and how?
> * Contents of startup.cs, with any secrets removed.
> 
> All of the above is needed.

3rd party API
I do a PostJsonAsync where i authenticate with username and password and get a token in return.
Thats the token im using in the print screens in the original post.
![githubreply1](https://user-images.githubusercontent.com/10367109/63076492-bc9ba680-bf35-11e9-923e-18331b46405a.png)

I just realized i authenticate to the api with token from one of the client side pages and that works fine in production. But not when the server does it. In development it works from both.

I will upgrade my project to latest .Net 3.0 Preview 8 today and check if theres any differences. If it still dosent work im gonna try the same thing in a new blank project see if i can replicate it.

Startup.cs from the Server project that calls the API
![githubreply2](https://user-images.githubusercontent.com/10367109/63076830-c540ac80-bf36-11e9-8b08-67a682b7e038.png)

**Comment by blowdart** [comment]
You don't have any bearer authentication in your configuration.

Is the problem not inbound authentication, but outbound authentication via HttpClient to somewhere else other than your app?

**Comment by Garderoben** [comment]
> You don't have any bearer authentication in your configuration.
> 
> Is the problem not inbound authentication, but outbound authentication via HttpClient to somewhere else other than your app?

Correct, but it seems to work fine from the client in my project when publiced to production but not when called from the server. Both works in development running from Visual studio.
I'm moving all API calls like this to the server side since i dont want them running on the client.

**Comment by blowdart** [comment]
Ah, ok, not the security code then :) I'll leave it for blazor or httpclient folks to pick up

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by Garderoben** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

Sure i will set it up with different scenarios, should i upload it to github?
I will check with the external API provider if they have a test API i cant give out auth to the production one, maybe i can build a mockup and publish it. I will try get this done withing the next 10 hours from this post.

**Comment by Garderoben** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

I'm still working on the test application but i just got some more information from the 3rd party API owner. See the difference in the request. I have no idea why...

![GithubResponse](https://user-images.githubusercontent.com/10367109/63160832-07451d80-c01f-11e9-80fe-011d307aa549.png)

**Comment by Garderoben** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

Okay.. Problem solved we can close this. After exporting data from the prod database and the dev database i notice that "\r\n" was present in the prod one and since i just checked the data in SSMS before it dident show.

Sorry for taking your time.

**Comment by rynowak** [comment]
Glad you figured it out !
