### ISSUE TITLE
VS 16.3.0 Preview 2 and preview6 build failure

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#13142]
### Describe the bug
I have updated VS TO 16.3.0 Preview 2 and when I build my preview6 asp.net core + blazor solution, the blazor project now fails to build with the same error reported previously as fixed here:

https://github.com/aspnet/AspNetCore/issues/10218

Error Output from build:

> Severity	Code	Description	Project	File	Suppression State	Line
Error	MSB4064	The "NullableContextOptions" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.	Hub.Platform.Client	C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets		224
Error	MSB4063	The "Csc" task could not be initialized with its input parameters. 	Hub.Platform.Client	C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets		189

### To Reproduce
1. Using this version of ASP.NET Core '3 preview 6)
2. Add a blazor client project targeting netstandard 2.
2. Build the solution using vs 16.3.0 preview 2

### Expected behavior
Should build.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
We don't really support previous preview releases. If you have the same issue with the latest preview, we can look into it.

**Comment by dazinator** [comment]
I've upgraded to preview 7 and am experiencing the same thing, even with all my dependencies on preview 7 and using latest vs 2019 preview. However now preview 8 has just been released it seems I am one behind again. Trouble is it takes a while for dependencies to be upgraded by which time once I reach preview 8 you will probably have released preview 9! :-)

**Comment by dazinator** [comment]
I've got a repro for preview 8, i'll open a new issue.
