### ISSUE TITLE
AddAttribute onclick no longer accepts lambda expressions

### ISSUE THREAD

**Issue by billybillyjim** [aspnet/AspNetCore#13151]
I've been working on a project without updating for a while, but it seems like no one else can contribute with my current setup so I decided to try setting it up with the latest version of Blazor. It's almost working, but I make extensive use of 

`builder.AddAttribute()`

especially with buttons. It seems that now the AddAttribute function no longer accepts actions, and when I try to do something like 

`builder.AddAttribute(2, "onclick", () => ToggleNavMenu());`

I get a an error:

>Error	CS1660	Cannot convert lambda expression to type bool because it is not a delegate type	

It seems like there is a different way to do it now, but in my searching I couldn't find any examples.

**Comment by rynowak** [comment]
This is intentional. 

Can you give us a little more information about what you're trying to do?

**Comment by billybillyjim** [comment]
This was just the method I used for implementing all the buttons in my app. So for example button I am currently using in preview5 looks like this:

```
            builder.OpenElement(7, "button");
            builder.AddAttribute(8, "class", "btn btn-primary");
            builder.AddAttribute(9, "style", "margin:2px;height:2rem;line-height: initial;");
            builder.AddAttribute(10, "onclick", () => Deposit(item, 1));
            builder.AddContent(11, "1");
            builder.CloseElement();
```

I am looking for some way to still be able to call `Depost(item.Key, 1)`  on a button click with a RenderTreeBuilder.

**Comment by rynowak** [comment]
Sure, so you can still do that, it just requires a little more code.

```
builder.AddAttribute(10, "onclick", new Action(() => Deposit(item, 1)));
```

We took away some overloads of these methods because we don't think they are getting much usage. No functionality was removed.

**Comment by billybillyjim** [comment]
Ah, that's exactly what I was looking for. Thank you!
