### ISSUE TITLE
Child Component State is not changed

### ISSUE THREAD

**Issue by mg1357** [aspnet/AspNetCore#13158]
In Blazor server side, I have a child component on a page that has a LoadComponent method inside it, It loads the component data and I call it from the parent component. Before calling LoadComponent I set the ID property of the child component since the LoadComponent uses this ID to load data. The following is the first lines of the Child component:

```
`[Parameter]
 public int DepartmentID { get; set; }

public void LoadComponent()
    {        
        GetDepartment(); // uses DepartmentID
        GetAdditionalMeta(); // uses DepartmentID
        GetImage(); // uses DepartmentID
    }
`
```
I call this method from parent component like this:

```
`public BlazorStore.Pages.Admin.TreePageComponents.AddEditDepartment addEditDepartmentComponent;
public void NodeChanged(TreeItem item)
    {
        if (item.DepartmentID == 0 && item.CategoryID == 0)
        {
            DepartmentAddMode = true; 
            DepartmentEditMode = false; 
            DepartmentIDForAddEditComponent = 0; // set DepartmentID of the child component
            StateHasChanged();
            addEditDepartmentComponent.LoadComponent(); // 0
        }
        else if (item.DepartmentID > 0 && item.CategoryID == 0)
        {
            DepartmentEditMode = true;
            DepartmentAddMode = false;
            DepartmentIDForAddEditComponent = item.DepartmentID; // set DepartmentID of the child component
            StateHasChanged();
            addEditDepartmentComponent.LoadComponent();
        }
    }

`

```

while the child component's DepartmentID is set, But it reflects after two or more interactions with the component so it is not take effect immediately. 
The component markup in parent is:

```
`@if  (DepartmentAddMode == true || DepartmentEditMode == true)
        {
            <BlazorStore.Pages.Admin.TreePageComponents.AddEditDepartment @ref="@addEditDepartmentComponent"  DepartmentID="@DepartmentIDForAddEditComponent"
                          DepartmentChanged="@(() => { GetTree(); ExpandNodes(); StateHasChanged(); })">

            </BlazorStore.Pages.Admin.TreePageComponents.AddEditDepartment>
        }`
```
The other problem is that I set two boolean variables that are responsible for visibility of the child component before calling the LoadComponent, But when I set them to true and call LoadComponent the addEditDepartmentComponent is still null so I get NullReference exception.

```
DepartmentEditMode = true; // still component is null
DepartmentAddMode = false;
DepartmentIDForAddEditComponent = item.DepartmentID; 
StateHasChanged();
addEditDepartmentComponent.LoadComponent(); // component is null so LoadComponent fails
```

so I have to comment out the if that shows or hides the component like this:

```
`@*@if  (DepartmentAddMode == true || DepartmentEditMode == true)
        {*@
            <BlazorStore.Pages.Admin.TreePageComponents.AddEditDepartment @ref="@addEditDepartmentComponent"
                          DepartmentChanged="@(() => { GetTree(); ExpandNodes(); StateHasChanged(); })" DepartmentID="@DepartmentIDForAddEditComponent">

            </BlazorStore.Pages.Admin.TreePageComponents.AddEditDepartment>
        @*}*@`
```

So is it a problem with blazor or there is a way to correct it?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mg1357.
The backing fields mapped through the `@ref` are initialized after the component is rendered. You can use the `OnAfterRender` lifecycle event for your custom logic.

**Comment by mg1357** [comment]
Exactly what do I do? My custom logic is inside the SelectedNodeChanged of a tree control and inside the parent component. Of course it is not possible to move it to OnAfterRender, If it is possible please inform me how to do this.

**Comment by mg1357** [comment]
I think the better way to solve this problem is, Child component's OnParametersSet that I use now,  But the other way is LoadComponent inside OnAfterRender. But I noticed that when using this method the OnAfterRender is called many times that is also solved with a boolean field that is set to false when LoadComponent is called.
