### ISSUE TITLE
[Blazor] Consider adding an option to Router that allows specifying more than one assembly to scan for routeable components

### ISSUE THREAD

**Issue by srowan** [aspnet/AspNetCore#13156]
### Describe the bug
Consider a simple component:

```
@page "/foo"
<div>Foo!</div>
```

Previously if this component was in a component library that was referenced, you could navigate to `/foo` and it would work / be picked up just as if it was in the blazor server project.

After Preview 8 this no longer seems to be working.  Was this a purposeful change?  Is there a new way to route to components in a library?

**Comment by ghidello** [comment]
Appearently it is by design: https://github.com/aspnet/AspNetCore/pull/11810#discussion_r302487079
I would like to know if there is another way too.

**Comment by ar0311** [comment]
Ditto

**Comment by stsrki** [comment]
The same thing happened to me. As a workaround I have removed page attribute from the referenced project and added it to the client-side project. Then I used the previous page as a component. see here:
reference project: https://github.com/stsrki/Blazorise/blob/dev082/Tests/Blazorise.Demo/Pages/Tests/ButtonsPage.razor
client-side project: https://github.com/stsrki/Blazorise/blob/dev082/Tests/Blazorise.Demo.Bootstrap/Pages/Tests/ButtonsPage.razor

**Comment by srowan** [comment]
My emergency hack in case anyone needs to just get this working in the short term while working on a better solution:

```
    public class AppBase : ComponentBase
    {
        protected override void OnInitialized()
        {
            HackRoutingTable(typeof(App).Assembly, typeof(SomeComponentLibraryType).Assembly);
        }


        // Hack the blazor Router to include types from component library when routing
        // TODO - remove when this issue is fixed or a better workaround is found https://github.com/aspnet/AspNetCore/issues/13156
        private void HackRoutingTable(params Assembly[] componentAssemblies)
        {
            var components = componentAssemblies.SelectMany(a => a.ExportedTypes.Where(t => typeof(IComponent).IsAssignableFrom(t)));
            var routeTableFactoryType = typeof(Router).Assembly.GetType("Microsoft.AspNetCore.Components.RouteTableFactory");
            var createTableMethod = routeTableFactoryType.GetMethod("Create", BindingFlags.Static | BindingFlags.NonPublic, null, new Type[] { typeof(IEnumerable<Type>) }, null);
            var routeTable = createTableMethod.Invoke(null, new object[] { components });
            var cacheMemberInfo = routeTableFactoryType.GetField("Cache", BindingFlags.Static | BindingFlags.NonPublic);
            var cache = cacheMemberInfo.GetValue(null);
            var tryAddMethod = cache.GetType().GetMethod("TryAdd");
            tryAddMethod.Invoke(cache, new object[] { componentAssemblies[0], routeTable });
        }

    }
```

**Comment by mkArtakMSFT** [comment]
As per @ghidello 's response, this change is by-design. We will try to bring back support for this in a future milestone.

**Comment by ar0311** [comment]
Any further material available on why this change was necessary? TIA

**Comment by rynowak** [comment]
We want the choice to include an assembly's components for routing to be explicit on the part of the app developer. We want Blazor to grow a healthy library ecosystem, and the idea that a library could include routable content without your knowledge hurts trust. Also, it's somewhat complex and adds overhead we don't want people to pay who aren't using it.

I realize that some of you may have strong feelings in favor of other kinds of rules for deciding how your apps behave, we'll work with you to make subclassing/extending the router easy to do.

**Comment by ar0311** [comment]
Thanks for the concise and prompt answer! I didn't even consider the security aspects of it. Makes sense now, cheers @rynowak

**Comment by rynowak** [comment]
Added here for preview 9: https://github.com/aspnet/AspNetCore/pull/13241
