### ISSUE TITLE
Loss HttpClientJsonExtensions in blazor server app

### ISSUE THREAD

**Issue by kevinjhang** [aspnet/AspNetCore#13163]
### Describe the bug
Error CS1061 'HttpClient' does not contain the definition of 'GetJsonAsync', nor can it find the accessible extension method 'GetJsonAsync' that accepts the first argument of type 'HttpClient' 

### To Reproduce
1.Create a blazor server app 
2.Try use the extension methods in page code

**Comment by ar0311** [comment]
Read [here](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/)

You need to add a PackageReference to `Microsoft.AspNetCore.Blazor.HttpClient` as of preview 8.

**Comment by kevinjhang** [comment]
> [在這裡](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/)閱讀[](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/)
> 
> 您需要在`Microsoft.AspNetCore.Blazor.HttpClient`預覽8中添加PackageReference 。

Thanks! Its work!
