### ISSUE TITLE
Blazor app on custom route

### ISSUE THREAD

**Issue by jerriep** [aspnet/AspNetCore#13167]
I am not sure whether this is a bug or my lack of understanding.

What I want to find out is whether it is possible to host a server-side blazor app on a custom route as I want to mix a Blazor app with a normal Razor pages app. So I want Razor pages with their normal routes, and then I want my Blazor app, for example, on the route `/spa`.

I tried setting the route for the `_Hosts.cshtml` page to `/spa` but that does not affect anything.

Is there any sample anywhere that shows how to achieve this sort of behaviour?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jerriep.
You can achieve what you want by passing the path (`/spa/{**path:nonfile}`) to the `MapFallbackToPage` call.

**Comment by jerriep** [comment]
Thank you @mkArtakMSFT, that works.

The only problem with that is that it requires the Blazor page components to also have a URL that includes `/spa/*`. For example, in the default Blazor template, I need to change the URL of the counter page from `/counter` to `/spa/counter`

Is there any way yo specify the URL of the Blazor pages to be relative to the root `/spa` path?
