### ISSUE TITLE
Does the `IHttpRequestBodyFeature` interface exist?

### ISSUE THREAD

**Issue by Taritsyn** [aspnet/AspNetCore#13165]
After updating ASP.NET Core to version 3.0 Preview 8 in my project, that using the `IHttpBufferingFeature` interface, I received the following compilation error:

```
Error	CS0619	'IHttpBufferingFeature' is obsolete: 'See IHttpRequestBodyFeature or IHttpResponseBodyFeature DisableBuffering'
```
It is clear that I should refuse to use the obsolete interface, but it is completely unclear where the `IHttpRequestBodyFeature` interface is defined and whether it exists at all?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Taritsyn.
@Tratcher what's the alternative here?

**Comment by Tratcher** [comment]
Not yet: https://github.com/aspnet/AspNetCore/issues/12620

Were you using DisableRequestBuffering? How/why?

Honestly we hadn't seen any reported usages of that API, it's not hooked up to anything by default.

**Comment by Taritsyn** [comment]
Hello, Chris!

> Were you using DisableRequestBuffering? How/why?

I use it for implementing ASP.NET Core middleware, which produce a markup minification and HTTP compression (see source code of the [stream wrapper](https://github.com/Taritsyn/WebMarkupMin/blob/332c7a7bc7d510f4c2e9e707b5faa496e47d983b/src/WebMarkupMin.AspNetCore1/BodyWrapperStream.cs#L579-L582)).

> Honestly we hadn't seen any reported usages of that API, it's not hooked up to anything by default.

This API is mentioned [here](https://github.com/aspnet/AspNetCore/blob/4a42afc5aea63750638e118560d43db04bd9ccc2/src/Http/Http.Features/src/IHttpBufferingFeature.cs#L8).

**Comment by Tratcher** [comment]
That's only using response buffering. It only called request buffering as passthrough because they were combine on the old interface. You can remove that call.

**Comment by Taritsyn** [comment]
ОК. Thank you!
