### ISSUE TITLE
Blazor Preview8

### ISSUE THREAD

**Issue by MarkTMcp** [aspnet/AspNetCore#13172]
Old way of mapping (prior to Preview8):    **endpoints.MapBlazorHub();**
New way on generated sample Server Side App (since Preview8):     **endpoints.MapBlazorHub<App>(selector: "app");**
    

New way creates the index page via MainLayout.razor twice.
You can confirm by placing breakpoint  on OnInitialized() in MainLayout file.

The app appears to work normally, but all code on the default page is executed twice. This includes DI objects used by the default page (such as DBContexts)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MarkTMcp.
The behavior you're observing is by-design. You can disable pre-rendering and the `OnInitialized` will be called once only.
