### ISSUE TITLE
WASM: System.TypeLoadException: Could not load file or assembly 'netstandard, Version=2.0.0.0

### ISSUE THREAD

**Issue by sbwalker** [aspnet/AspNetCore#13171]
### Describe the bug
My application uses dynamic loading of components to add functionality. For client-side Blazor my code uses the following logic to download component assemblies from the server and load them into the client's app domain:

// download assembly from server and load
var bytes = await http.GetByteArrayAsync("_framework/_bin/" + moduledefinition.AssemblyName + ".dll");
Assembly.Load(bytes);

This works fine - I can see the browser make a request and download the assembly. And for simple "Hello World" components they can then be dynamically injected into the UI and they render fine. However for more complex components which need to make HTTP service calls to the server to retrieve data, they throw an error when they are dynamically injected:

WASM: ﻿Unhandled exception rendering component:
WASM: System.TypeLoadException: Could not load type of field 'Oqtane.Module.Blogs.Client.Index:blogs' (1) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
WASM:   at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
WASM:   at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) <0x1a42bf0 + 0x00008> in <ca8db92053fd4e67b86c2c733157275a>:0 
WASM:   at System.RuntimeType.IsAssignableFrom (System.Type c) <0x1a42a50 + 0x00056> in <ca8db92053fd4e67b86c2c733157275a>:0 
WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.OpenComponent (System.Int32 sequence, System.Type componentType) <0x2441dc8 + 0x0000c> in <100f02d5db4143bd88f7ce610be59116>:0
WASM:   at Oqtane.Client.Shared.ModuleInstance.<OnInitialized>b__13_0 (Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder) <0x256a7e0 + 0x000bc> in <6f1d83c9dca944e3aae0d07c251ee223>:0 

### To Reproduce
1. Using ASP.NET Core 3.0 Preview 8 on the latest version of VS 2019 Preview
2. Download the code from https://github.com/oqtane/oqtane.framework and select the "Wasm" Build configuration and build it
3. Download the code from https://github.com/oqtane/oqtane.module.blogs and build it ( make sure the post build event XCOPY paths are correct
4. Run the Oqtane framework, login, add Blog module to page. The error above will be displayed in your browser console.

### Expected behavior
The component should be displayed without throwing an error

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sbwalker.
@SteveSandersonMS should this go to the Mono team?

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Yes. TBH I don't know whether this is a bug or something incorrect in usage. But the Mono team would be best placed to decide.

**Comment by sbwalker** [comment]
I will try to create a simpler repro to demonstrate the issue

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#16600
