### ISSUE TITLE
preferred_username claim from Azure AD v2 endpoint not available in the HttpContext.User.Identity.Claims collection 

### ISSUE THREAD

**Issue by TiagoBrenck** [aspnet/AspNetCore#13180]
### Describe the bug
This is regarding the assembly https://github.com/aspnet/AspNetCore/tree/master/src/Security/Authentication/JwtBearer/src

I have tried to set the default claim mapping off using the following line of code, and this shows all the other claims that AAD sends in the id_token, but preferred_username is still not there.

`JwtSecurityTokenHandler.DefaultMapInboundClaims = false;`

How can I get the value of **preferred_username** in the claims collection?

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Run this code '....'

In startup.cs, please the following line before the OpenIdConnectOptions starts getting configured.

`JwtSecurityTokenHandler.DefaultMapInboundClaims = false;`

3. With these arguments '....'

Once the user signs in, examine the HttpContext.User.Identity.Claims collection. The **preferred_username** is not present.

### Expected behavior
If you capture the id_token sent by Azure AD, an example provided below, the claim is present in it. The [Microsoft identity platform ID tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens) advises using this claim as the primary username that represents the user. The absence of this claim in the claims collection makes it hard to do so.

_eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCJ9.eyJhdWQiOiJhMjk5NGM2Zi1hYTY3LTQxZjgtYWM1Yy1kYmY1YzdmOTI5NzciLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vMTYxMzM1YjktOWUxYi00Mzg2LWJiNTgtMTYwYTYyZTZjODg5L3YyLjAiLCJpYXQiOjE1NjU5MDY1MjEsIm5iZiI6MTU2NTkwNjUyMSwiZXhwIjoxNTY1OTEwNDIxLCJhaW8iOiJBVFFBeS84TUFBQUFGUzhHT1hHNUtMWE55NjRYZWV3N1FPdkJDYlhyQjRua1FOelZrRjN2eWdIUmppL3VPQ2ZzNXRKY0NodGdZUFJvIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJub25jZSI6IjYzNzAxNTAzNjE0MDQ2OTg1OC5ZV1ZrTmpFMU5EUXRabUZoWlMwMFkyUTBMVGt3T1RBdE5UQTFNV0UzTW1WbVpqa3pPR1EzTXpKallqWXROR1kzTkMwME5tTXdMVGxpWWpRdE5XSmxPR1E0WVdZelpERm0iLCJvaWQiOiJiYWUzMzJmYS05NGJjLTQyNmUtOGU5ZC1hYWNiYmNjNWZiZWQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbmlzdHJhdG9yQHRpYWdvYnJlbmNrZ21haWwub25taWNyb3NvZnQuY29tIiwic3ViIjoiU1FyVnBPQjN5N1o5YzlLSzcyY3pPbFJTUkRJeHltc1hlOUZ1TDlJRkE4QSIsInRpZCI6IjE2MTMzNWI5LTllMWItNDM4Ni1iYjU4LTE2MGE2MmU2Yzg4OSIsInV0aSI6IkhXdDdxNWpjNzBxbDBQUHZVVEVtQUEiLCJ2ZXIiOiIyLjAifQ.IPAFaUPKQowKVHmJy32wip3c0HKYKv1cIaA9rn38eLdvNPZPj-jd0PjqchYTcwbx213X-Ai3vhzVEwLkr_H_QzJX7dfbsaM2GFOdlbkROg22lo0RIbL8He92LpI6BC3LSxuu5KtHGJY9PeOzIOtOryyKGiUWJM2EEO-kwk6EFnKKEGATO_3Q1wAKGzQPUl3DLm0e2l6nvLwguGDveWSa_kQvApGEHkhiFzvb6CuLF5U5TU3Jh7LqgbfZX2F2E2JiVHJk1k4e3BSqZa8wpRzjVDkn_c-BbZc-NtgrnKCZ11TZR3Gb9E24xGZlFvmXth4vIfa5i9JgE9wgsN5wQ9EIBA_

### Additional context
Include the output of `dotnet --info`

**Comment by blowdart** [comment]
This is a question for @jmprieur, but you're right, the claims names changed. Their documentation addresses it I believe and we have a work item to make this easier next major version when we will default to the v2 endpoints.

**Comment by jmprieur** [comment]
@TiagoBrenck : were you targetting the v2.0 endpoint?

**Comment by TiagoBrenck** [comment]
Yes @jmprieur 
I found this while testing something else in this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API

**Comment by TiagoBrenck** [comment]
It was my mistake. The *preferred_username* claim is present on id_token not access_token. The code is working as expected.
