### ISSUE TITLE
[Preview 8] static assets not found when launchSettings.json is missing

### ISSUE THREAD

**Issue by akorchev** [aspnet/AspNetCore#13190]
### Describe the bug

If the Properties/launchSettings.json file is missing static assets from Razor class libraries no longer seem to work. They all lead to HTTP 404 status.

### To Reproduce
1. Create a blazorserver application using Preview 8: `dotnet new blazorserver`
2. Install a third party library that has static assets e.g. Blazored.Toast: `dotnet add package Blazored.Toast`
3. Include its CSS file by adding this line to _Host.cshtml: `<link href="_content/Blazored.Toast/blazored-toast.css" rel="stylesheet" />`
4. Run the application `dotnet run` and open the asset by loading `https://localhost:5001/_content/Blazored.Toast/blazored-toast.css`. You should see the file content. 
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/454726/63176598-e3013500-c04e-11e9-9a4f-ce51bc57c247.png">

5. Stop the application and delete the launchSettings.json file from the Properties directory `rm -rf Properties/launchSettings.json`
6. Run the application `dotnet run` and open the asset by loading `https://localhost:5001/_content/Blazored.Toast/blazored-toast.css`. It is no longer found.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/454726/63176828-54d97e80-c04f-11e9-8df3-f4179ea4a4bd.png">

### Expected behavior
The assets should work with or without launchSettings.json.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @akorchev.
The `StaticWebAssets` feature works only in `Development` by default. You can turn on the feature unconditionally by calling `UseStaticWebAssets` in the `Program.CreateHostBuilder`.

**Comment by akorchev** [comment]
FWIW static assets seem to work just fine in production without calling `UseStaticWebAssets` or having launchSettings.json. It is probably something else that is causing `UseStaticWebAssets` to be invoked.
