### ISSUE TITLE
Is that any way to support razor's taghelper in winform 

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/AspNetCore#13206]
my project is Winform .net 4.7 and I want to use razor + cef/miniblink to build UI,,so I already Implement to build cshtml file on runtime and cef load the file to show the UI,,,I already reference Microsoft.AspNetCore.Razor.Language 2.2 package

now I want to support the tagHelper ,,but in Vs2019/17 when I create the winform project and create a cshtml file,the IDE can't use the @model and @addTaghelper and @inject keyword...

the @model keyword I use the @inherits keyword instead,
but @addTagHelper or @inject ,not anyother keyword can instead ..how can I make the IDE support these keyword???Is that anyother package need to reference

**Comment by NTaylorMullen** [comment]
Hey @kugarliyifan, latest Razor does not work in winform projects sadly. This is why you don't get proper Razor directives in your Razor file (the project is treating your files as classic ASP.NET Razor). Sadly there isn't a great way to workaround this limitation without writing your own Visual Studio extension.

**Comment by kugarliyifan** [comment]
> Hey @kugarliyifan, latest Razor does not work in winform projects sadly. This is why you don't get proper Razor directives in your Razor file (the project is treating your files as classic ASP.NET Razor). Sadly there isn't a great way to workaround this limitation without writing your own Visual Studio extension.

thank you ! may be I need to write some extension for vs,,
