### ISSUE TITLE
Implementing permanent/persistent cookies in MSAL

### ISSUE THREAD

**Issue by youdhbir** [aspnet/AspNetCore#13207]
Unable to set persistent/permanent cookie in MSAL 4.x

### To Reproduce
1. Using this version of ASP.NET Core '2.2' and MSAL 4.2.1
2. Run this code 
'services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
  .AddAzureAD(options => configuration.Bind("AzureAd", options))
  .AddCookie(options =>
  {
    options.Events.OnSigningIn = (context) =>
    {
    context.CookieOptions.Expires = 
    DateTimeOffset.UtcNow.AddDays(10);
    return Task.CompletedTask;
    };
});'
3. Application generates session cookie for authentication

### Expected behavior
Permanent/persistent should be generated instead of session cookie

### Screenshots
NA

### Additional context
We are in the process of upgrading ADAL to MSAL for stability reasons. We could set persistent cookie in ADAL using below code:
services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
            .AddAzureAd()
            .AddCookie(options =>
            {
                options.Events.OnSigningIn = (context) =>
                   {
                       context.CookieOptions.Expires = DateTimeOffset.UtcNow.AddDays(_settings.CookieExpiryInDays);
                       return Task.CompletedTask;
                   };
            });

Created an issue under MSAL repo as well (link below) but MS identity team suggested issue inside cookie middleware and asked to create issue here as well.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1340

**Comment by blowdart** [comment]
We don't use MSAL so you're in the right place. You can't set the cookie options like this, it doesn't work as you've discovered. Instead you need to [set the options on the Cookie middleware](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.2#create-an-authentication-cookie), with those you can either do sliding expiration or have a fixed timespan after which it vanishes, which appears to be what you want. By default it's 14 days.

**Comment by youdhbir** [comment]
Thanks @blowdart...will check and revert back

**Comment by dennisbappert** [comment]
The referenced article explains on how to set the cookie options by implementing SignInAsync which is part of the [RemoteAuthenticationHandler ](https://github.com/aspnet/AspNetCore/blob/d8381656429addead2e5eb22ba1356abfb419d86/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs) class (line 140). You can modify the passed AuthenticationProperties by implementing the OnTicketReceivedHandler:

```csharp
OnTicketReceived = context =>
{
    context.Properties.IsPersistent = true;
    context.Properties.ExpiresUtc = DateTimeOffset.UtcNow.AddDays(7);

    return Task.FromResult(0);
}
```

**Comment by youdhbir** [comment]
Thanks a lot @dennisbappert. It worked.
