### ISSUE TITLE
[Blazor client-side preview 8] memory issue wich cause code terminated

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#13218]
Hello guys, I actually develop an app with blazor, in server side for development and client side on production.

My app consist of rewriting a silverlight app and reuse all the existing viewModel and suscribe to the event launched by the viewModel to update my views (essentially things like propertyChanged, collectionChanged, and eventHandler).

In server-side, it works perfectly.

Now i trying to make the app working on client side and i meet some trouble with that.
Indeed, i felt not all the code was executed sometimes. (and the app definitively not working as expected).

I also see some "debug" message in the chrome console like this :
````
WASM: GC_MINOR: (Nursery full) time 3.63ms, stw 3.70ms promoted 508K major size: 9408K in use: 5635K los size: 1024K in use: 229K
````
when i put some console.writeline in the code to see whats happen, i begin to understand my code is shutdown when these message appear. (for example i put 5 console.writeline in the code, i see the first three appear in the console, then the wasm debug message, and don't see the two other)

so it seem definitively a memory problem.

So the question are :
- is it for you a memory problem ?
- if yes, how i can solve it ? assuming i can't change the code of the existing viewModels runing in my app. there is any way to increase the memory limit?

it's really a big deal for me, i work on this app since 6 month, and i can't use the server-side on production because there is a lot of static access in the existing viewModels.

The complexity of my app make i can't propose a reproduction scenario.  

there is some other wasm message in the console, if it can help you
````
WASM: GC_MINOR: (Nursery full) time 4.11ms, stw 4.13ms promoted 742K major size: 1824K in use: 1123K los size: 1024K in use: 149K
WASM: GC_MAJOR_SWEEP: major size: 9168K in use: 23867K
WASM: GC_MAJOR: (LOS overflow) time 12.42ms, stw 12.47ms los size: 1024K in use: 63K
````

thanks for your help !

**Comment by pranavkm** [comment]
This issue was moved to mono/mono#16365
