### ISSUE TITLE
Namespace RuntimeHelpers not found

### ISSUE THREAD

**Issue by endeffects** [aspnet/AspNetCore#13211]
I have base classes for each of my components, with preview8 i'm getting the following error:

```
Error	CS0234	The type or namespace name 'RuntimeHelpers' does not exist in the 
namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)
```

**View: MyView.razor**

```
@inherits MyViewBase

<h1>Test</h1>
```

**Base: MyView.razor.cs**

```
    public abstract class MyViewBase : ComponentBase
    {
    }
```

**Comment by endeffects** [comment]
Seems to be related to an 3rd party component.

**Comment by Ratomir** [comment]
I had the same issue. I was migrating from 3.0.0-preview7 to 3.0.0-preview8 and I had to update my Visual Studio to the latest version. That resolved this issue. More details are here on the blog page: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/

Also, I had an error with the Layout in AspNetCore.Components https://github.com/aspnet/AspNetCore/issues/13123 .

Someone who migrating from preview7 to preview8 could get these two issues together.

**Comment by saqw3r** [comment]
I had the same issue after upgrading from preview 6 to preview 8. Update of Blazor's plugin in VS didn't help, VS is up-to-date.

**Comment by endeffects** [comment]
My problem was related to some click events, the syntax changed with the preview7 and preview8. So you need to check your bindings with the upgrade guidlines.

` @onclick="@(async () => await this.DoSomething())"`
