### ISSUE TITLE
Blazor app templates - why does two _Imports.razor files as separately, need to be stay?

### ISSUE THREAD

**Issue by mrscript21** [aspnet/AspNetCore#13212]
Dear ASP.NET Core Blazor team.
I have a question about current Blazor app templates which has two _Imports.razor files during a few preview releases till now.
Blazor app features should keep two _Imports.razor files in coming release too?
I think it could be just one single _Imports.razor file and adjust blazor app structures.

One more question about _Host.cshtml file under Pages folder which is now represented about common html 5 page as part of SPA structure as I see, but why only that .cshtml file should be, why not a .razor file in newest Blazor app template till now?
That is also I was wondering.

I would like to understand more and keep trying to make Blazor app with each preview releases.
But I have such questions to know more or wish to see some changes which could be more clear to learn and adopt Blazor app.
Thanks and hope to hear some guides or answers about these topics soon.

**Comment by vertonghenb** [comment]
Related to https://github.com/aspnet/AspNetCore/issues/8498

**Comment by mrscript21** [comment]
@vertonghenb, thanks for that link.

**Comment by pranavkm** [comment]
With the recent changes to Router, it's likely we don't need two separate _Imports.razor. We could look at consolidating the two.

**Comment by pranavkm** [comment]
I re-read your question. Our templates currently have a single `_Imports` since we're leveraging a new feature in the router. You may have any number of `_Imports.razor` if your app requires it.

> One more question about _Host.cshtml file under Pages folder which is now represented about common html 5 page as part of SPA structure as I see, but why only that .cshtml file should be, why not a .razor file in newest Blazor app template till now?

`.razor` files are used exclusively to define components. The `_Host.cshtml` files is used to bootstrap the Blazor application.
