### ISSUE TITLE
[Blazor] Issue running Blazor app in iOS.

### ISSUE THREAD

**Issue by rxelizondo** [aspnet/AspNetCore#13225]
I have spent hours trying to figure out why a Blazor app that works perfectly fine in Edge, Chrome and even Safari (running from a Mac) does not work on iOS (in iPhone or iPad).

After a lot of fiddling around, I believe I found the cause of the problem and it has to do with calling `GetJsonAsync` from the `Index.razor` page.

To reproduce, simply create a Blazor app (ASP.NET Core hosted) and add the following code to the `Index.razor` page.

```
@code {

    protected override async Task OnInitializedAsync()
    {
        try
        {
            WeatherForecast[] forecasts = await HttpClient.GetJsonAsync<WeatherForecast[]>("WeatherForecast");
        }
        catch
        {
            // Do nothing.
        }
    }
}
```

If you then publish the app and run it from say Edge or Chrome things work without a problem, but if you try to run this from an iPhone or an iPad the application hangs.

Since in order to debug issues with the iPhone or iPad browser you need a Mac, I am unable to troubleshot anything since I don't own a Mac.

I have publish an app that exhibits the behaviors here::

https://ioese.azurewebsites.net

Could someone with mad Apple development skills take a shot at trying to figure out why the iOS devices browser is hanging?

Thanks.

**Comment by pranavkm** [comment]
This issue was moved to mono/mono#16364
