### ISSUE TITLE
[Blazor] JsInterop Invoke after each promise resolves

### ISSUE THREAD

**Issue by QadiymStewart** [aspnet/AspNetCore#13222]
Trying to get things working correctly in Blazor Server Side App. I have an Uploader Component but it doesn't InvokeAsync after each promise is resolved on client side. It waits for all Images to load then Invokes the C# method. How would I get it to Invoke the C# method after each image is loaded?

I know JavaScript is single threaded but also tried with web workers and still does the same thing.

It should be able to invoke the C# method async in parallel from js file if my thinking is correct.  

![Up3](https://user-images.githubusercontent.com/28968495/63217702-055f8500-c119-11e9-9664-71ffeef889eb.gif)
![Up2](https://user-images.githubusercontent.com/28968495/63217703-055f8500-c119-11e9-8f65-d9fa3d49a8ef.gif)

### Additional context
Sample repo can be found here 
https://dev.azure.com/twinnaz/BlazorUploader

**Comment by pranavkm** [comment]
Thanks for contacting us, @QadiymStewart .
This sounds like a question about authoring application code, and not specifically a Blazor issue. We recommend posting this question to StackOverflow.
