### ISSUE TITLE
Microsoft.AspNetCore.Components.Browser is outdated and broken with Preview 8

### ISSUE THREAD

**Issue by OnurGumus** [aspnet/AspNetCore#13228]
The file
https://github.com/aspnet/AspNetCore/blob/b0524058c3e35a2768de34ea56b5ee6afcc968b4/src/Components/src/Microsoft.AspNetCore.Components.Browser/RendererRegistryEventDispatcher.cs

Uses things like **UIEventArgs** from **Microsoft.AspNetCore.Components**, however these classes are moved to **Microsoft.AspNetCore.Components.Web** with preview 8. And there is no new nuget for **Microsoft.AspNetCore.Components.Browser** package since then. This package seems broken since then.

Actually the real problem is the nuget package for **Microsoft.AspNetCore.Components.Browser** is still on Preview 7.

**Comment by githubfanster** [comment]
i believe  Microsoft.AspNetCore.Components.Browser has been renamed  Microsoft.AspNetCore.Components.Web

**Comment by OnurGumus** [comment]
Ah ok, you are right. I was so confused about this. Thanks for the clarification.
