### ISSUE TITLE
Blazor bind value on event causing exception

### ISSUE THREAD

**Issue by GAMP** [aspnet/AspNetCore#13238]
I have this simple input and bind it to a view model, when adding the @bind-Value:event attribute the binding stop functioning and instead i get this exception in browser console

blazor.webassembly.js:1 WASM: System.ArgumentException: Object of type 'Microsoft.AspNetCore.Components.UIChangeEventArgs' cannot be converted to type 'System.String'.

Here is the whole html i use for binding 

`  <InputText type="password" class="form-control" id="AuthorizePassword" placeholder="Password" @bind-Value="@Model.Password" @bind-Value:event="oninput" />`

I am currently using Preview 8.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GAMP.
InputText doesn't currently support `oninput` event. We track enabling it as part of #11960.
