### ISSUE TITLE
Using RobinHerbots inputmask in ClientSideBlazor

### ISSUE THREAD

**Issue by toto-tech** [aspnet/AspNetCore#13236]
I want to use inpunmask in clientside blazor.  Problem is that two way binding not work.
My code is folllowing:
I include this js libs:

    <script src="script/jquery-3.4.1.min.js"></script>
    <script src="script/jquery.inputmask.min.js"></script>
    <script src="script/inputmask.binding.js"></script>
    <script src="script/InitMask.js"></script>

My js code:
window.datetimeinput =
    {

    initjs: function () {
            
                //$("#phone").inputmask();
            $("#phone").inputmask("99-9999999");
            
    }
    };

My blazor code:
<EditForm Model="@model" OnValidSubmit="@(()=>submit(model))">
<input @bind="model.phone" data-inputmask="'mask': '99-9999999'" />
</EditForm>

@code{
public Model model = new Model();

    public class Model
    {
       
        public string phone { get; set; }
    }

  

    protected override async Task OnAfterRenderAsync()
    {
        await js.InvokeAsync<object>("datetimeinput.initjs");

    }
}

**Comment by hetis** [comment]
Please help

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @toto-tech.
If that library directly manipulates the DOM, you're going to have problem with integrating it with Blazor.

**Comment by toto-tech** [comment]
Ok , what can be best practise to mask inputs generally
