### ISSUE TITLE
Shared variables

### ISSUE THREAD

**Issue by desalbres** [aspnet/AspNetCore#13234]
Hello, I have added a server-side Blazor project a class named AppState, in which I have a public boolean property in it...
I've registered the class as Singleton...
And, for test, I have bound it to a <input="checkbox" >...
Then I ran the project, and checked the box.
The problem is when I open another window in another browser I still see the input tag checked!
My question is: how set a variable **ONLY** on the current app, like in session for example ? 
Can I do this without using a controller ?
Thanks,
Raphaël

**Comment by rynowak** [comment]
If you want to share state within a single browser tab, register the service as Scoped (using `AddScoped`).

**Comment by desalbres** [comment]
Hello, I have the following problem.

I need to implement server-side blazor authentication with user/password.

So my CustomAuthStateProvider:

public class CustomAuthStateProvider : AuthenticationStateProvider
    {        
        private AppState appState;
        public CustomAuthStateProvider(AppState _appState)
        {
            appState = _appState;
        }
        public override Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            var identity = new ClaimsIdentity();

            if (appState.isAuthenticated)
            {
                identity = new ClaimsIdentity(new[]
                {
                new Claim(ClaimTypes.Name, "Admin"),
            }, "Auth");
            }

            var user = new ClaimsPrincipal(identity);

            return Task.FromResult(new AuthenticationState(user));
        }
    }


public class AppState
    {
        public bool isAuthenticated { get; set; }
        
    }

In startup.cs:

services.AddAuthorizationCore();            
            services.AddScoped<AuthenticationStateProvider, CustomAuthStateProvider>();
            services.AddScoped<AppState>();

In login component:

@inject AppState appState
...
if (await webSiteService.Login(login, password))
        {            
            appState.isAuthenticated = true;
            UriHelper.NavigateTo("dashboard", true);
        }

I also have an App.Razor.

But the above code only works if I set:
    services.AddSingleton<AppState>();
But then if I open another browser tab it is also authenticated!

Could you please advice the right pattern/method to use ?

Thanks very much!

Raphaël

**Comment by desalbres** [comment]
Hello, I have posted my question on StackOverflow!
https://stackoverflow.com/questions/57555274/where-and-how-to-store-authentication-data
Thanks anyhow!
