### ISSUE TITLE
How to Play videos in Blazor way?

### ISSUE THREAD

**Issue by sukeshchand** [aspnet/AspNetCore#13233]
Thanks to the Blazor team and the community. Its looks amazing. Looking forwarding the see how Blazor will change the web development market.

I have a question, How do I play a video using HTML5 video, I can able to bind the src by using the property @VideoUrl, but to play need to call the load() and play() method. I can able to do this using Javascript inside Blazor, 
```

<video >
        <source src="@VideoUrl" type="video/mp4">
</video>

window.playVideo = function (url) {
            var video = document.getElementById('video');
            var mp4 = document.getElementById('mp4');
            mp4.src = url;
            video.load();
            video.play();
        }

```
Is there any way I can play in the Blazor way. 
Thank you.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sukeshchand.
You can do anything possible through JavaScript by doing JSInterop. If you want to invoke that functionality from your Blazor App through C#, you will need to write the interop code. Here is the guidance for doing that: https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0
