### ISSUE TITLE
IWebHostEnvironment not in netstandard2.2

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/AspNetCore#13231]
### Describe the bug
There are open source libs that use the IWebHostEnvironment (IHostingEnvironment previously) so we could build upon .netstandard instead of separate builds.  Is this going to be in .netstandard2.2 when 3.0 ships?

### To Reproduce
1. Create a new library project with 3.0 Preview 8
2. Set it to use .NET Standard 2.2
3. Try and create a call that used IWebHostEnvironment
4. Compilation error

### Expected behavior
Should be available  in .NET Standard 2.2 or 3.0 (whichever will be shipped with 3.0)

**Comment by Tratcher** [comment]
No, none of aspnet core is part of netstandard.

**Comment by shawnwildermuth** [comment]
Of course it isn't. D'oh.

**Comment by anurse** [comment]
Closing, as ASP.NET Core 3.0 is .NET Core 3.0 only now.

**Comment by shawnwildermuth** [comment]
Yup...went with the SDK and we were all good. Thanks.
