### ISSUE TITLE
Blazor: [Authorize] Attribute

### ISSUE THREAD

**Issue by endeffects** [aspnet/AspNetCore#13240]
Please conside to allow the Authorization Attribute for Components too. It would be also great if it would be possible to specify the fallback scenarios within the Attribute.

```
[Authorize(Policy = MyPolicy, Authorizing = MyAuthorizingView, NotAuthorized = MyNotAuthorizedView)]
public class HelloWorldBase : ComponentBase
{
    public const string Title = "Hello World - Code Behind";
}
```

or

```
[Authorize(Policy = MyPolicy)]
[Authorizing(View = MyAuthorizingView)]
[NotAuthorized(View = MyNotAuthorizedView)]
public class HelloWorldBase : ComponentBase
{
    public const string Title = "Hello World - Code Behind";
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @endeffects.
Using the `Authorize` attribute on component definition in code is already supported. However, defining the routing behavior is not something we will consider supporting in the near future.
