### ISSUE TITLE
Css occasionally not loading with kestrel

### ISSUE THREAD

**Issue by Yuzal** [aspnet/AspNetCore#13248]
I got a ServerSideBlazor Project.
While debugging with kestrel my application occasionally doesn't load some random css files.

My link to the css file:
`<link href="~/css/Components.css" rel="stylesheet" />`

My css file:
` @import "first.css";`
` @import "second.css";`

Using kestrel to debug.

Usually it should load all css classes as with ISS or Scriptdebug.

![image](https://user-images.githubusercontent.com/54112036/63254200-98accd80-c273-11e9-8b3c-ed308b2bb57a.png)

![image](https://user-images.githubusercontent.com/54112036/63254301-cdb92000-c273-11e9-9990-601d3a711ebd.png)

I don't have this problem with ISS or while scriptdebug is active.
i disabled the cache with the same results.
Current .net core version: 3.0.100-preview8-013656

**Comment by davidfowl** [comment]
What version?

**Comment by Yuzal** [comment]
> What version?

Current .net core version: 3.0.100-preview8-013656

**Comment by jkotalik** [comment]
Can you try running on the latest core-sdk (preview9 bits) and see if this repros? https://github.com/dotnet/core-sdk

What logs do you see on the server? Is there an exception being thrown? If you don't see anything, if you could increase the LogLevel for whatever logger you are adding to a higher verbosity (information/debug), we can get a better idea what is happening on the server.

**Comment by halter73** [comment]
It is interesting to see the "(canceled)" and "CAUTION: provisional headers are shown" for the failed requests. This implies the requests were never in fact made https://stackoverflow.com/a/21179105/719967

**Comment by Rick-Anderson** [comment]
@Yuzal is this still a problemm? Can we close this issue?

**Comment by Rick-Anderson** [comment]
@jkotalik  @halter73  recommend closing.

**Comment by halter73** [comment]
@Yuzal Is this still a problem? If so, can you provide a repro? A bot will close this issue if there's no author feedback within a week.
