### ISSUE TITLE
[Blazor] When injecting into layout values are not in service/state.

### ISSUE THREAD

**Issue by kyurthich** [aspnet/AspNetCore#13243]
Sorry if this is working as intended. I am at a loss.

### Describe the bug
I have created a singleton in the client project.
![image](https://user-images.githubusercontent.com/3331097/63232992-ea654180-c1fa-11e9-806e-a3ee68f95353.png)

I am able to access this in a linked component inside of any page after MainLayout.
I am however not able to access it in a linked component inside MainLayout.

This is in my MainLayout

![image](https://user-images.githubusercontent.com/3331097/63233016-20a2c100-c1fb-11e9-92e9-ee2869ac89a6.png)

This is the ClientEnvironment component:

![image](https://user-images.githubusercontent.com/3331097/63233040-6069a880-c1fb-11e9-9f69-804beeeda159.png)

Now if I use ClientEnvironment in a normal razor page it will load fine.

If I use it in the main layout the values in appCache are empty.

### Expected behavior
appCache should be the same whether it is injected in MainLayout or a RazorPage.

**Comment by rynowak** [comment]
> If I use it in the main layout the values in appCache are empty.

`AppCache` is your own code. Can you describe how you're using it it - and why you think Blazor is responsible for your problem?

Also, if `AppCache` is meant to contain per-user data, you will really want it to be registered as a scoped server.

**Comment by kyurthich** [comment]
Yes correct on the scoped mention! Thanks for that.

I am utilizing it for storing a couple properties that need to persist through out the whole session.

I think it was weird that when the code is used either in a linked component outside the main layout or even just used in the main layout without a component it populates the properties in AppCache.

If I reference the component directly into the main layout the properties of AppCache do not populate

Maybe I am just not understanding something about the lifecycle. 

Here is a visual that may help get my question across.

![image](https://user-images.githubusercontent.com/3331097/63318316-1c9e9e00-c2e4-11e9-9fd7-b5a86cab7da0.png)

**Comment by rynowak** [comment]
The Layout is going to render for the first time before you

**Comment by kyurthich** [comment]
So here is my injected class.
`using Surgere.Web.Console.Client.Services.Contracts;
using Surgere.Web.Console.Shared.Surgere.Client;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Surgere.Web.Console.Client.Cache
{
    public class AppCache
    {
        private readonly IClientApi _clientApi;
        public List<ClientInfo> ClientInfo { get; private set; }
        public List<Environments> Environments { get; private set; }

        public AppCache(IClientApi clientApi)
        {
            _clientApi = clientApi;
            GetClientInfo();
        }

        public async void GetClientInfo()
        {
            ClientInfo = await _clientApi.GetClientInfo();
            Environments = await _clientApi.GetEnvironments();
        }
    }
}
`

Ok so from what you are saying it sounds like my DI scope will get populated and then the component should render itself again with the newly populated properties.

Which makes sense and I see how that is working in the two scenarios where the dropdowns have data.

What I don't understand is why the first scenario does not seem to be rendering the component again after the DI scope is created.

Maybe it has to do with the clientapi I am injecting into my component?
