### ISSUE TITLE
Translated value is not returned from a bit flag enum

### ISSUE THREAD

**Issue by nino-s** [aspnet/AspNetCore#13252]
### Describe the bug
Get translated values of a bit flag enum does not work. It always returns name of the fields, not the translated value.

I did some research for example in [ModelExplorerExtensions#L53](https://github.com/aspnet/AspNetCore/blob/v2.2.5/src/Mvc/Mvc.ViewFeatures/src/ViewFeatures/ModelExplorerExtensions.cs#L53). There it tries to check if the object value is equal to a field of the enum. For example a bitflag enum with value 3 (a combination of 1 and 2) cannot find a match at all. 

### To Reproduce
1. Using this version of ASP.NET Core 2.2.5
2. Run this code
```csharp
[Flags]
public enum ETestEnum
{
    [Display(Name = "TestEnum.None")]
    None = 0,

    [Display(Name = "TestEnum.FieldOne")] // in a resource file is written: "This is field one"
    FieldOne = 1 << 0,

    [Display(Name = "TestEnum.FieldTwo")] // in a resource file is written: "This is field two"
    FieldTwo = 1 << 1
}
```

On a razor view display for a test object containing the enum.
```chsarp
@{
  var testObject = new
  {
    TestEnum = ETestEnum.FieldOne | ETestEnum.FieldTwo
  };
}

@Html.DisplayFor(m => testObject.TestEnum)
```

Output is: `FieldOne, FieldTwo`

### Expected behavior
Output should be `This is field one, This is field two`

**Comment by pranavkm** [comment]
@nino-s thanks for your issue report. Unfortunately this is a nor a feature we have or plan on adding to MVC at this point.
