### ISSUE TITLE
Lost trying to get this working

### ISSUE THREAD

**Issue by TehWardy** [aspnet/AspNetCore#13258]
I'm trying to make SignalR work between a web app (that hosts the hub), a web client (in the browser) and an azure function. I've hit a constant stream of exceptions that seems to be never ending so I figured I'd come here and ask for advice since i'm just seemingly going around in circles.

I have ...
  - 1 Brand spanking new aspnet core 2.2 web app.
  - 1 Azure Function that connects to hub in the aspnet web app.
  - Javascript on a web page that connects to the hub in the web app.

**Lifecycle / usage scenario of this code** 

I have a web based UI for designing a workflow and submitting that to the back end. Once the back ned has a stored copy of the flow the client can from the same UI trigger an instance of the flow to be executed (which the azure function handles).

An OData call is made to a controller (omitted here to keep the code as small as possible as you can see there's already quite a bit of it). 

When The call is made the "FlowRunner" code (shown below as the javascript client code) is run to connect to the hub and begin waiting for console receives from the engine running inside the azure function.

The azure function deserializes the request information from the OData controller send and constructs a "WorkflowInstance" which it then attaches a hub call to the "ConsoleSend" method when a logging call is made inside the flow instance.

This in turn should be fed back to the client running in the browser to allow the user to get real time feedback from the flow instance via the hub.

**The problem**

Right now both the javascript client and the Azure function client are giving the following exception when trying to call the "ConsoleSend" method on a WorkflowHub but the server is not reporting / logging any exception information at all ...

> System.Private.CoreLib: Exception while executing function: Execute. System.Private.CoreLib: Failed to invoke 'ConsoleSend' due to an error on the server.

**The web app** 

The system is primarily OData based and uses M$ OData sat on top of the Core MVC framework in the same app.

So I have this setup as follows (any not related code has been omitted)...

**Startup.cs > ConfigureServices**

```
services.AddMvcCore(options =>
            {
                options.EnableEndpointRouting = false; // TODO: Remove when OData does not causes exceptions anymore
            })
            .AddDataAnnotations()
            .AddJsonFormatters(options => options.ReferenceLoopHandling = ReferenceLoopHandling.Ignore)
            .AddCors(options => options.AddDefaultPolicy(builder => {
                builder.AllowAnyHeader();
                builder.AllowAnyMethod();
                builder.SetIsOriginAllowed(origin => true);
                builder.AllowCredentials();
            }))
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddOData();
            services.AddSignalR();
```

**Startup.cs > Configure** 

```
log.Info("  Cors");
app.UseCors(builder =>
{
    builder.AllowAnyHeader();
    builder.AllowAnyMethod();
    builder.SetIsOriginAllowed(origin => true);
    builder.AllowCredentials();
});

log.Info("  SignalR");
app.UseSignalR(routeBuilder => {
    routeBuilder.MapHub<WorkflowHub>("/Hubs/Workflow");
});

log.Info("  WebApi & Odata");
app.UseMvc(routeBuilder =>
{
    routeBuilder.EnableDependencyInjection();
    routeBuilder.MapRoute("default", "{controller=Home}/{action=Get}");
});
```

**Hubs** 

```
public abstract class CoreHub : Hub
{
    ILog log = LogManager.GetLogger(typeof(WorkflowHub));

    public override Task OnConnectedAsync()
    {
        log.Debug($"New Client connected to {this.GetType().Name}");
        return base.OnConnectedAsync();
    }

    public override Task OnDisconnectedAsync(Exception exception)
    {
        log.Debug($"Client disconnected from {this.GetType().Name}");
        return base.OnDisconnectedAsync(exception);
    }

    public async Task Join(string thread)
    {
        log.Debug($"User joining {thread}");
        await Groups.AddToGroupAsync(Context.ConnectionId, thread);
        await Clients.Caller.SendAsync("info", "Listening to messages for " + thread);
        await Clients.Group(thread).SendAsync("info", "User Connected.");
    }

    public async Task Leave(string thread)
    {
        log.Debug($"User leaving {thread}");
        await Groups.RemoveFromGroupAsync(Context.ConnectionId, thread);
        await Clients.Caller.SendAsync("info", "Stopped listening to messages for " + thread);
        await Clients.Group(thread).SendAsync("info", "User Left.");
    }
}

public class WorkflowHub : CoreHub
{
    ILog log = LogManager.GetLogger(typeof(WorkflowHub));

    public async Task ConsoleSend(string level, string message, string thread)
    {
        log.Debug($"{thread}: {level} {message}");
        await Clients.Group(thread).SendAsync("ConsoleReceive", level, message, thread);
    }
}
```

**In the client (Javascript)**

```
var FlowRunner = {
	init: function(app, container, flow) {
        app = app || session.app;
        container = container || $(".component[name=FlowRunner]");
       
        var connection = new signalR.HubConnectionBuilder().withUrl(session.apiRoot + "Hubs/Workflow").build();
        connection.subs = new Array();
        connection.on("ConsoleReceive", function(level, message, instance) {
            var subs = connection.subs;
        	for (var i in subs) {
            	if(subs[i].instance == instance) {
                	subs[i].handle(subs[i], level, message);
                }
            }
        });
       
        connection.start()
           .then(function() { 
                 $("button[name=executeFlow]", container).off().on("click", function() { FlowRunner.execute(connection, app, container, flow); });
                 notification.info("Connected to workflow hub.");
           		 connection.invoke("ConsoleSend", "info", "test - success"); 
           })
           .catch(function(err) { debugger; error(err.toString()); });
    },
   
    setupConsoleForInstance: function() {
      var execNum = $(".execConsole").length + 1;
      $("body").append("<div class='execConsole' name='execConsole_" + execNum + "'><div name='flowConsole'></div></div>");
       var  dialog = $("[name=execConsole_" + execNum + "]");
       dialog.kendoWindow({
				title: "Console",
				modal: false,
				visible:false,
				close: function(){ this.destroy(); },
				resizable: true,
          		width: 800,
          		height: 350 
		});
       
       return dialog;
    },
   
    execute: function(connection, app, container, flow, instance, bookmark) {
		var dialog = FlowRunner.setupConsoleForInstance();
        var requestJson = $("textarea[name=data]", container).val();
		var request = requestJson.length > 0 ? JSON.parse(requestJson) : null;
       
		if(instance && bookmark) {
			api.call("Core/FlowDefinition(" + instance + ")/Resume()?bookmark=" + bookmark, request, function(r) { 
               FlowRunner.subscribeTo(connection, r.value, dialog); 
               connection.invoke("ConsoleSend", "info", "Client Connected to instance " + r.value, r.value); 
            });
		}
		else {
			api.call("Core/FlowDefinition(" + flow.Id + ")/Execute()", request, function(r) { 
               FlowRunner.subscribeTo(connection, r.value, dialog); 
               connection.invoke("ConsoleSend", "info", "Client Connected to instance " + r.value, r.value); 
            });
		}
        dialog.data("kendoWindow").center().open();
	},
         
    subscribeTo: function(connection, instanceId, dialog) {
		var endMessages = ["Execution failed.", "Execution awaiting further input.", "Execution Complete."];
		var subscription = {
		   instance: instanceId, 
		   console: dialog,
		   handle: function(sub, level, message) { 
			   if(level == "info" && endMessages.filter(function(m) { m == message }).length > 0) {
                    connection.invoke("leave", sub.instance);
					connection.subs.pop(sub);
			   }
			   
			   $("[name=flowConsole]", sub.console).append(FlowRunner.buildMessage(level, message));
		   }
		};
       
       connection.subs.push(subscription);
       connection.invoke("join", subscription.instance);
	},
		 
	buildMessage: function(level, message) {
		var d = new Date();
		var time = d.getHours() + ":" +  d.getMinutes() + ":" +  d.getSeconds();
		
		return $("<div class='message " + level + "'>" +
				 "<span class='time'>" + time + "</span>" +
				  "<span class='message'>" + message + "</span>" +
		 "</div>");
	}
}
```

**In the Azure Function** 

```
public static class Execute
{
    [FunctionName("Execute")]
    public static async Task Run([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "Execute")]HttpRequestMessage req)
    {
        // read the message
        var rawRequest = await req.Content.ReadAsStringAsync();
        Console.WriteLine("Request: \n" + rawRequest);
        var msg = (rawRequest.Contains("$type")
            ? JsonConvert.DeserializeObject(rawRequest, ObjectExtensions.JSONSettings)
            : JsonConvert.DeserializeObject<WorkflowRequest<object>>(rawRequest, ObjectExtensions.JSONSettings)) as WorkflowRequest;

        // connect to the signalr hub on the source API
        var con = new HubConnectionBuilder().WithUrl(msg.Api + "Hubs/Workflow").Build();
        con.On<Exception>("error", (ex) => Console.WriteLine(ex.Message + "\n" + ex.StackTrace));
        await con.StartAsync();

        try
        {
            // construct the flow instance
            var instance = msg.ResumeFrom == null
                ? await FlowHelper.Get(msg.FlowId, msg.Api, msg.AuthToken)
                : await FlowHelper.GetInstance(msg.InstanceId, msg.Api, msg.AuthToken);

            instance.OnLog += (level, message) => con.InvokeAsync("ConsoleSend", level.ToString().ToLower(), message, msg.InstanceId);

            // execute the flow 
            var result = await (Task<FlowInstanceData>)instance
                .GetType()
                .GetMethod("Execute")
                .MakeGenericMethod(msg.GetType().GenericTypeArguments)
                .Invoke(instance, new[] { msg });

            await FlowHelper.SaveResult(result, msg.Api, msg.AuthToken);
        }
        catch (Exception ex)
        {
            await con.InvokeAsync("ConsoleSend", "fatal", $"Failed to process request, abandoning execution\n{ex.Message}\n{ex.StackTrace}");
        }
        finally
        {
            await con.InvokeAsync("ConsoleSend", "info", "", msg.InstanceId);
        }
    }
}
```

**Comment by TehWardy** [comment]
I'm just working on getting this all running locally, from previous tickets I have raised here I have noted the value in the server console logs from VS. 

I'd like to add a note here that my (like many others) infrastructure is quite complex and hard to run all parts on a single workstation machine so ideally a solution to dump the server console logs in to the configured exception handler would really help here.

I'm already doing this ...

```
app.UseExceptionHandler(errorApp =>
            {
                errorApp.Run(async context =>
                {
                    var ex = context.Features.Get<IExceptionHandlerPathFeature>();
                    log.Error(ex.Error.Message + "\n" + ex.Error.StackTrace);
                     ....
```
... but the dependence on the VS console on a server makes some situations hard to see so an option to push that here would help no end allowing me to pick that information out my own logs.

**Comment by TehWardy** [comment]
Locally I'm getting a different exception with the same code and DB backups from the dev box I was previously testing on, the key changes are that all config based url's ect now point to "https://localhost:{some port}/{path}" for everything.

With the debugger on the azure function ...

var con = new HubConnectionBuilder().WithUrl(msg.Api + "Hubs/Workflow").Build();
con.On<Exception>("error", (ex) => Console.WriteLine(ex.Message + "\n" + ex.StackTrace));
await con.StartAsync();

... on the StartAsync call i'm getting the exception ...

> System.Private.CoreLib: Exception while executing function: Execute. System.Net.Http: No such host is known. System.Private.CoreLib: No such host is known.

... reported on the command line console window and the server console in VS just says ...

>  Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll

... having examined the values at runtime this code / exception must be in relation to the domain from `msg.Api` which is correctly pointing to localhost on the right port for my API app which hosts the hub.

**Comment by TehWardy** [comment]
Ok found a typo in 1 config file ... gonna try and get back to the state it's in on the dev servers.

**Comment by BrennanConroy** [comment]
Looking through your calls to "ConsoleSend" I see that a few of them are sending 2 strings instead of the required 3 strings.

This will give you "Failed to invoke 'ConsoleSend' due to an error on the server."

**Comment by TehWardy** [comment]
Yeh I just fixed a couple of those as the server console in VS pointed that out to me.
It looks like now i'm getting this on the server console ...

```
Exception thrown: 'System.ObjectDisposedException' in System.Net.Http.dll
Exception thrown: 'System.ObjectDisposedException' in Core.Objets.dll
Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll
Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll
```

... after the finally block on the function app.

Using the server console has revealed a ton of tiny little tweaks or mistakes that I just needed to clean up, frustrating that the logs couldn't be setup to pick this up so I didn't have to pull everything off the servers and on to my local machine.

Is there any disposal behaviour / concerns I need to be aware of for SignalR client types ?
I thought HubConnection instances were disposable but they don't appear to be any more?

**Comment by TehWardy** [comment]
Thinking i might have logged this ticket an hour or two too early ... 

The underlying issue I seem to be having with NetCore is access to the output of the Server Console that's piped in to VS ... This really needs to be subscribe-able somehow on a non-workstation machine.

**Comment by TehWardy** [comment]
Ok i'm still not getting the calls back through to the web client ... i'm only receiving the "Connected to Instance {instanceId}" message. 
It's like messages are being lost somewhere ... could be another typo though.

**Comment by TehWardy** [comment]
Ok I think i have it working (mostly) now ... i'm dealing with un-related bugs due to the upgrade from .Net 4.x at this point.

My take away from this if anything is that I feel like i just need more visibility on remote machines of what NetCore 2.2 in general is up to (the server console being the information i'm missing).

**Comment by BrennanConroy** [comment]
Is there any SignalR related issue left here?

**Comment by TehWardy** [comment]
I will close this ticket and raise another one if I get stuck again ... I feel like I just used you guys as my rubber duck :)
I'm sill having issues but nothing that I can specifically point at and state "this is signalr".

Thanks all for your patience (hopefully this thread will help make aspnet core better in some way :)
