### ISSUE TITLE
Razor View - Parsing Razor Syntax error when inside a TagHelper Tag

### ISSUE THREAD

**Issue by joe88ds** [aspnet/AspNetCore#13267]
### **Describe the bug**

Razor Syntax not properly parsed when inside the opening tag of a TagHelper tag (netcore2.1)

**### To Reproduce**

1. Create a Razor View (.cshtml) file: _TestView.cshtml
2. Copy the code into the file:
```
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@functions {
	Microsoft.AspNetCore.Html.HtmlString RenderAttribute(string name, string value)
	{
		return new Microsoft.AspNetCore.Html.HtmlString($"{name}=\"{value}\"");
	}
}
<form asp-page="/" @RenderAttribute("class", "hidden")>
</form>
```
**### Expected behavior**
@RenderAttribute should not be parsed as HTML

**Comment by NTaylorMullen** [comment]
This is by design. You cannot utilize C# in TagHelper declarations.
