### ISSUE TITLE
Feature request : Allow configure TCP backlog

### ISSUE THREAD

**Issue by wangjia184** [aspnet/AspNetCore#13270]
### My feature request is related to a problem

I have ~20 machines and each of them keeps sending HTTP requests to my web server and client encounters following exception in rare(< 0.01%) case. 

>No connection could be made because the target machine actively refused it

### The solution is to increase TCP backlog

I believe the issue is because TCP backlog is full in a short period and it couldn't accept new connections.  but it seems there is no way to customize TCP backlog in kestrel server.

```
var builder = WebHost.CreateDefaultBuilder()
    .UseConfiguration(AppConfig.Root);

_host = builder.UseKestrel(options =>
    {
        options.ListenAnyIP(listeningPort, (listenOptions) =>
        {
            listenOptions.TcpBacklog = 1000; // <-- no such option 
        });
    })
    .UseStartup<Startup>()
    .Build();
```

Is it feasible to allow customizing TCP backlog on listen()?

### Additional context

.NET Core SDK 2.2
Default transport used in Kestrel.

**Comment by halter73** [comment]
This might be too esoteric, but it's something we should consider as we want to be a more general-purpose TCP server stack. I would make the Tcp/ListenBacklog a transport option if we do this. I would hope the default backlog of 512 is sufficient for most scenarios where servers aren't completely overloaded.

**Comment by davidfowl** [comment]
This would be a transport option not a Kestrel option.
