### ISSUE TITLE
Async Tasks - JsonSerializationException: Self referencing loop detected for property 'task' with type

### ISSUE THREAD

**Issue by ghhv** [aspnet/AspNetCore#13272]
### Describe the bug
The following error now occurred for me in Core 3 Preview 8 when calling an async task from a non-async call in a Controller. The error message sent me down the rabbit hole of trying to get JsonSerialization to globally ignore self referencing loops in Core 3 which I still could not work out how to do since Core 3 no longer uses .AddMVC() in Startup. 

I was passing my data back to the browser for preview via `Return Ok(objectVar);` but since I had inadvertently not set the controller task as async, I was getting this error. 

`An unhandled exception occurred while processing the request.JsonSerializationException: Self referencing loop detected for property 'task' with type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder 1+AsyncStateMachineBox 1 [System.Collections.Generic.List 1[XXXX.Models.YYY],System.Runtime.CompilerServices.IAsyncStateMachine]'. Path 'stateMachine.<>t__builder'.
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)`

### To Reproduce
1. Using this version of ASP.NET Core 3 Preview 8'
2. Run this code:
Controller Code:
```
public IActionResult TodaysEvents()
        {
            CalService calService = new CalService(_context);

            return Ok(calService.GetTodaysEvents());
        }
```
This fails as above. 

```
public async Task<IActionResult> TodaysEvents()
        {
            CalService calService = new CalService(_context);

            return Ok(await calService.GetTodaysEvents());
        }
```
This works as expected. 

### Expected behavior
I would not expect this obscure message which is seemingly unrelated to the problem. Missing `awaits` are handled well in the reverse situation with warnings that it will run synchronously. 

I tested this behaviour in Core 2.1 and it does not fail but returns a weird stateMachine object instead which I interpreted as an empty object - such as 
```{"stateMachine":{"<>1__state":0,"<>t__builder":{},"<>4__this":{}},"context":{},"moveNextAction":{"method":{"name":"MoveNext","declaringType":"System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],```...

I'm not sure if this should be considered a bug and it is low priority but hopefully helps someone else. Can this error be improved otherwise?

**Comment by pranavkm** [comment]
@ahsonkhan \ @steveharter would it make sense to throw if the value to `Serialize` is a `Task` type? It's almost never useful to try and serialize one of these and indicates a bug in user code.

**Comment by ghhv** [comment]
I know returning an object like this is not something you would do in a production environment but if the `Ok` was replaced with `Json`, then that would be reasonable and I guess has the same issues.

**Comment by pranavkm** [comment]
As @steveharter pointed out in the linked issue, this actually works with System.Text.Json. We haven't had much feedback for this with Json.NET, so doing nothing here seems like a reasonable course of action.
