### ISSUE TITLE
No templates matched the input template name: blazorwasm.

### ISSUE THREAD

**Issue by JavaPaulFox** [aspnet/AspNetCore#13278]
### Describe the bug
No blazorwasm template. I have tried to create new project blazorwasm but via Visual Studio I have only one option - Blazor Server App. Via console I have the same situation. 

> No templates matched the input template name: blazorwasm

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Expected behavior
Create new project

### Screenshots
![image](https://user-images.githubusercontent.com/11604767/63353566-3a5f1800-c363-11e9-9f64-482b14b33ca6.png)

![image](https://user-images.githubusercontent.com/11604767/63354045-059f9080-c364-11e9-9bca-7ae941fb3cc7.png)

**Comment by thomasclaudiushuber** [comment]
You need to run the following command on the command line to get the _blazorwasm_ template:

```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview8.19405.7
```

After that you should see it when you run
```
dotnet new --help
```

From the command-line, use the --hosted param to create a WebAssembly project with Server project and Shared-Project like this
```
dotnet new blazorwasm -o MyFirstWasmApp --hosted
```

**Comment by pranavkm** [comment]
Closing as answered by @thomasclaudiushuber

**Comment by malachib** [comment]
When I attempt to do `dotnet new -i` part, I get `bash: $'\302\226dotnet': command not found`

Running Windows 10 , preview8 and latest VS preview on git-bash

**Comment by nickwri** [comment]
Latest template version can be checked here:
https://docs.microsoft.com/en-gb/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

Still in preview for now:
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview9.19465.2

**Comment by fengerzh** [comment]
When will formal release published?
