### ISSUE TITLE
[Blazor] Tags for custom elements / components should contain a dash

### ISSUE THREAD

**Issue by thomasclaudiushuber** [aspnet/AspNetCore#13274]
### Is your feature request related to a problem? Please describe.
The HTML specification says that new standard HTML elements won't contain a dash. When you create custom elements - in Blazor: components - you might want to ensure forward compatibility, so that your component still works when HTML introduces a new element. To ensure that forward compatibility, your component tag should contain at least one dash. Then you can be sure that your component tag will never collide with any future HTML tag.

In addition, a dash also allows the HTML Parser to notice directly custom elements. 

### Describe the solution you'd like
Currently the app component in the blazor project template has the tag _app_ in the index.html page. Maybe it should be something like _app-root_. Other frameworks like Angular use dashes too. Firefox describes custom elements here: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements, dashes are required.

Also components like _SurveyPrompt_ might require a dash. What if HTML introduces a _SurveyPrompt_ HTML element. If you have a _Survey-Prompt_ tag, the custom Blazor component would still work if HTML would introduce a _SurveyPrompt_ tag.

I'm aware that there's the generated razor.g.cs file that maps the used SurveyPrompt tag to the SurveyPrompt class. But maybe this needs more abstraction. Maybe there should be an attribute for a component that allows you to define a tag. 

For example, in Angular a component has a selector/tag, that is completely independent from the class of the component. Maybe we need a similar approach in Blazor. Maybe something like this on the SurveyPrompt component:

```
@tagName  "Survey-Prompt"
```

You would use the SurveyPrompt component with the specified tag name like you use it today.

```
<Survey-Prompt Title="How is Blazor working for you?" />
```

From the code generation, the @tagName could result in an attribute on the generated class, or in a read-only property set. The generated code where the component is used should look the same.

If something like this for custom tag names exists already, I'm sorry, I didn't find it. I decided to write down my thoughts here, and maybe we can have a discussion. :-)

**Comment by pranavkm** [comment]
@thomasclaudiushuber thanks for the suggestion. This is not an area we plan on investing in at this point.
