### ISSUE TITLE
Apache SignalR Secure Websocket Error: 200

### ISSUE THREAD

**Issue by BrianTheStangLover** [aspnet/AspNetCore#13287]
I'm currently running a .Net Core application with SignalR on an Ubuntu Apache web server. This .Net Core app is reachable by the https://example.com/api path which directs it to the localhost:5000.

I also have a Vue JS app running on the webserver as well. When I attempt to establish a websocket connection to the the SignalR application, the following error occurs:

>wss://example.com/api/mainHub?id=ipmk3vW1E1-ZzLBjqV9oMQ' failed: Error during WebSocket handshake: Unexpected response code: 200

>Error: Failed to start the transport 'WebSockets': null

The client then falls back and establishes a SSE connection. 
>Information: SSE connected to https://example.com/api/mainHub?id=E4ljyZmPwDAsnsngu5EAuA

Below is my apache config, where I route the /api request and attempt to "upgrade" the websockets.
```
#Main/Desired Path - https://example.com
<VirtualHost *:443>
        DocumentRoot /var/www/example.com/dist/spa
        ServerName example.com

#SSL Certs
        SSLEngine on
        SSLProtocol all -SSLv2
        SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:!RC4+RSA:+HIGH:+MEDIUM:!LOW:!RC4
        SSLCertificateFile /etc/apache2/ssl/example.crt
        SSLCertificateKeyFile /etc/apache2/ssl/server.key
        SSLCertificateChainFile /etc/apache2/ssl/example.ca-bundle

#Upgrade Websockets
        RewriteEngine on
        RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
        RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
        RewriteRule /(.*) ws://localhost:5000/$1 [P]

#Other specific directories
        ProxyPreserveHost On
        ProxyPass "/api" http://localhost:5000
        ProxyPassReverse "/api" http://localhost:5000

</VirtualHost>
```

Since this is a secure connection, I also tried changing the virtualhost config to route the websocket request to `wss://localhost:5001/` but that returned a 500 error.

Currently, the client makes the request to the path: `https://example.com/api/{hub}`. By the looks of the error, do I need to setup an additional virtualhost ProxyPass to route the wss://example.com request? Or should all of this be handled by the existing websocket upgrade?

**Comment by BrianTheStangLover** [comment]
Looks like the same issue is also posted here with no solution: https://github.com/aspnet/SignalR/issues/376

**Comment by BrennanConroy** [comment]
What endpoint is your hub on?

From my untrained eye it looks like for normal http requests "http://xyz/api" would go to "http://localhost:5000/" but for websockets "http://xyz/api" would go to "http://localhost:5000/api".

If that's not it and doesn't help, could you gather [server-side logs](https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2) to see what the server is doing with the websockets request?

**Comment by BrianTheStangLover** [comment]
> What endpoint is your hub on?
> 
> From my untrained eye it looks like for normal http requests "http://xyz/api" would go to "http://localhost:5000/" but for websockets "http://xyz/api" would go to "http://localhost:5000/api".
> 
> If that's not it and doesn't help, could you gather [server-side logs](https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2) to see what the server is doing with the websockets request?

Thank you very much for the reply,

The SignalR application runs on `localhost:5000`. I have another application running on this server as well, so I use the Apache config to route any requests with the `/api` at the end to the SignalR app at port 5000. So to reach the SignalR app all requests go to https://xyz/api

I'm trying to understand how the websocket requests would go to the http://localhost:5000/api path?

The RewriteRule for websockets is `RewriteRule /(.*) ws://localhost:5000/$1 [P]` If I'm understanding this correctly, this rule should send it right to http://localhost:5000 and not http://localhost:5000/api?

Should this RewriteRule only be called when a user sends a request to the https://xyz/api?

**Comment by BrennanConroy** [comment]
>The SignalR application runs on localhost:5000

So the hub is at `http://localhost:5000/mainHub`?

> The RewriteRule for websockets is `RewriteRule /(.*) ws://localhost:5000/$1 [P]` If I'm understanding this correctly, this rule should send it right to http://localhost:5000 and not http://localhost:5000/api?

Wouldn't `/(.*)` capture `/api/mainHub` and place that at `$1`? So you would end up with `ws://localhost:5000/api/mainHub` when you want `ws://localhost:5000/mainHub`?

**Comment by BrianTheStangLover** [comment]
> So the hub is at `http://localhost:5000/mainHub`?

Correct, the hub is at `http://localhost:5000/mainHub`

> Wouldn't `/(.*)` capture `/api/mainHub` and place that at `$1`? So you would end up with `ws://localhost:5000/api/mainHub` when you want `ws://localhost:5000/mainHub`?

Ah, yes this makes sense. I've tried changing the rewrite rule to `RewriteRule /api ws://localhost:5000/$1 [P]` I'm trying a few other combinations, but I believe my syntax still may be off? I'm a bit new to Apache...

**Comment by BrianTheStangLover** [comment]
I've got it! Went trough some of the Apache RewriteRule documentation and set my rewrite rule to the following: `RewriteRule ^/api/(.*) ws://localhost:5000/$1`

Thank you very much for the help!

**Comment by fmartinez88** [comment]
thanks you save my day, i have 3 days with this problem and can't resolve it until now.
