### ISSUE TITLE
Can't change dotnet run configuration to Release

### ISSUE THREAD

**Issue by thepok** [aspnet/AspNetCore#13289]
If i run 

dotnet run -c Release on my Windowsmachine it works fine

if i run 
dotnet run
 on my linux machine it works to, but if i run
dotnet run -c Release
on Ubunto i get a Cryptic error:

 brainboostbreak@v22019078670492584:~/repos/BrainBoostBreak$ $HOME/dotnet/dotnet run -c Release --project ~/repos/BrainBoostBreak/BrainBoostBreak.Server
/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.blazor.build/3.0.0-preview8.19405.7/targets/Blazor.MonoRuntime.targets(441,5): error MSB3073: The command "dotnet "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.blazor.mono/3.0.0-preview8.19380.1/build/netstandard1.0/../../tools/illink/illink.dll" -l none --disable-opt unreachablebodies --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.blazor.mono/3.0.0-preview8.19380.1/build/netstandard1.0/../../tools/mono/bcl/" -d "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.blazor.mono/3.0.0-preview8.19380.1/build/netstandard1.0/../../tools/mono/bcl/Facades/" -o "/home/brainboostbreak/repos/BrainBoostBreak/BrainBoostBreak.Client/obj/Release/netstandard2.0/blazor/linker/" -x "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.blazor.build/3.0.0-preview8.19405.7/targets/BuiltInBclLinkerDescriptor.xml" -x "/home/brainboostbreak/repos/BrainBoostBreak/BrainBoostBreak.Client/obj/Release/netstandard2.0/blazor/linker.descriptor.xml" -a "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.authorization/3.0.0-preview8.19405.7/lib/netstandard2.0/Microsoft.AspNetCore.Authorization.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.blazor/3.0.0-preview8.19405.7/lib/netstandard2.0/Microsoft.AspNetCore.Blazor.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.blazor.httpclient/3.0.0-preview8.19405.7/lib/netstandard2.0/Microsoft.AspNetCore.Blazor.HttpClient.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.components/3.0.0-preview8.19405.7/lib/netstandard2.0/Microsoft.AspNetCore.Components.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.components.web/3.0.0-preview8.19405.7/lib/netstandard2.0/Microsoft.AspNetCore.Components.Web.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.aspnetcore.metadata/3.0.0-preview8.19405.7/lib/netstandard2.0/Microsoft.AspNetCore.Metadata.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.bcl.asyncinterfaces/1.0.0-preview8.19405.3/lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.extensions.dependencyinjection/3.0.0-preview8.19405.4/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/3.0.0-preview8.19405.4/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.extensions.logging.abstractions/3.0.0-preview8.19405.4/lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.extensions.options/3.0.0-preview8.19405.4/lib/netstandard2.0/Microsoft.Extensions.Options.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.extensions.primitives/3.0.0-preview8.19405.4/lib/netstandard2.0/Microsoft.Extensions.Primitives.dll" -a "/home/brainboostbreak/.nuget/packages/microsoft.jsinterop/3.0.0-preview8.19405.4/lib/netstandard2.0/Microsoft.JSInterop.dll" -a "/home/brainboostbreak/.nuget/packages/mono.webassembly.interop/3.0.0-preview8.19405.4/lib/netstandard2.0/Mono.WebAssembly.Interop.dll" -a "/home/brainboostbreak/.nuget/packages/system.buffers/4.5.0/lib/netstandard2.0/System.Buffers.dll" -a "/home/brainboostbreak/.nuget/packages/system.componentmodel.annotations/4.6.0-preview8.19405.3/lib/netstandard2.0/System.ComponentModel.Annotations.dll" -a "/home/brainboostbreak/.nuget/packages/system.memory/4.5.3/lib/netstandard2.0/System.Memory.dll" -a "/home/brainboostbreak/.nuget/packages/system.numerics.vectors/4.5.0/lib/netstandard2.0/System.Numerics.Vectors.dll" -a "/home/brainboostbreak/.nuget/packages/system.runtime.compilerservices.unsafe/4.6.0-preview8.19405.3/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll" -a "/home/brainboostbreak/.nuget/packages/system.text.encodings.web/4.6.0-preview8.19405.3/lib/netstandard2.0/System.Text.Encodings.Web.dll" -a "/home/brainboostbreak/.nuget/packages/system.text.json/4.6.0-preview8.19405.3/lib/netstandard2.0/System.Text.Json.dll" -a "/home/brainboostbreak/.nuget/packages/system.threading.tasks.extensions/4.5.2/lib/netstandard2.0/System.Threading.Tasks.Extensions.dll" -a "/home/brainboostbreak/repos/BrainBoostBreak/BrainBoostBreak.Shared/bin/Release/netstandard2.0/BrainBoostBreak.Shared.dll" -a "/home/brainboostbreak/repos/BrainBoostBreak/BrainBoostBreak.Client/obj/Release/netstandard2.0/BrainBoostBreak.Client.dll"" exited with code 127. [/home/brainboostbreak/repos/BrainBoostBreak/BrainBoostBreak.Client/BrainBoostBreak.Client.csproj]

The build failed. Fix the build errors and run again.

### DOTNET INFO
brainboostbreak@v22019078670492584:~/repos/BrainBoostBreak$ ~/dotnet/dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/brainboostbreak/dotnet/sdk/3.0.100-preview8-013656/

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  3.0.100-preview8-013656 [/home/brainboostbreak/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/home/brainboostbreak/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/home/brainboostbreak/dotnet/shared/Microsoft.NETCore.App]

**Comment by thepok** [comment]
The ode is public : https://github.com/thepok/BrainBoostBreak

**Comment by danroth27** [comment]
This issue was moved to mono/mono#16385
