### ISSUE TITLE
With .NET Core 3.0, instances become unresponsive, seems to be stuck with only doing gen2 GC

### ISSUE THREAD

**Issue by markvincze** [aspnet/AspNetCore#13299]
### Describe the bug
After upgrading to ASP.NET Core 3.0, sometimes our API instances (it doesn't happen to every instance, and sometimes it starts happening only after hours of normal operation) become unresponsive, all their endpoints slow down by a huge margin, they reply after hundreds of seconds instead of the normal response time (which is around a second on average).

I started using [prometheus-net.DotNetRuntime](https://github.com/djluck/prometheus-net.DotNetRuntime) to get some detailed metrics about the .NET runtime. If I look at the metrics of one of these unresponsive instances, I always see the following symptoms:

 - The ratio of CPU time spent with GC is highly increased. (From the ~5% during normal operation, it increases to over 50%).
 - The duration of GC increases from being between 100ms-500ms to between 1-10 seconds.
 - The degraded instance is only doing gen2 collections, and it's not doing any gen0 and gen1 collections any more at all.

Here is a screenshot of what the metrics look like for a degraded instance (the service degradation started at around 21:15):

![image](https://user-images.githubusercontent.com/1122274/63383451-1b7d7780-c39d-11e9-9dd9-b9d61074e933.png)

Once this issue starts happening, the instance does not recover by itself, it has to be deleted manually.

I've never seen this happening with 2.2. In the new version of the application nothing was changed besides the framework upgrade and the 3.0-related changes in the `Startup.cs`.

I imagine that issues like this can be caused by many reasons, but if anyone has advice on how this can be further investigated, or if anyone has encountered anything similar specifically with .NET Core 3.0, that'd be greatly appreciated.

(Also, please tell if I should move this issue from `aspnet` to `coreclr`.)

### Additional context
In contrast of the above screenshot, here are the stats of a normally operating instance:

![image](https://user-images.githubusercontent.com/1122274/63383502-35b75580-c39d-11e9-96ec-a61619c2b92a.png)

The application is running on Kubernetes (in the Google Kubernetes Engine) on Linux nodes.  
We are using version `mcr.microsoft.com/dotnet/core/runtime-deps:3.0.0-preview8` as the base Docker image.

**Comment by sebastienros** [comment]
/cc @Maoni0 for visibility

This is not something we have experienced so far, so we'll need more information to diagnose the issue. Even better if we can repro it locally, even if it means running it for a long time.

Would you be able to take a memory dump using https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md at least to know what kinds of objects are the gc heaps.

Maybe also grab a trace (dotnet-trace) when this happens on a node.

Would you be able to describe what a typical api call does? What libraries you are using (EF for instance).

**Comment by markvincze** [comment]
@sebastienros thanks for the reply!

The API is pretty much a wrapper for a third-party, proprietary business rule engine called [InRule](https://www.inrule.com/), with which it evaluates certain business rules. On every request, the API executes some business rules using InRule's .NET SDK, which is CPU-intensive operation, happening in the same process.  
Due to the runtime of this rule engine being closed source (and obfuscated 🙂), I don't know much about how it works, what we know is that every execution runs on a single thread, so it's not starting extra background threads.

We are using some extra libraries for things like logging, metrics, tracing, etc., and we also call out to some other services via HTTP, but the main thing the API does is the rule engine execution described above. It's not using any data store, nor EF.

Unfortunately I don't think I can provide a self-contained runnable repro, there are just too many proprietary bits and pieces that would be needed to get this service up and running (for example the license for the InRule runtime to begin with).

But I'll try to collect the memory dump and the trace from one of the failing instances.

**Comment by sebastienros** [comment]
Apparently we are back to the recent issue you filed: https://github.com/aspnet/AspNetCore/issues/13058

At the end of the thread you mentioned you had isolated the issue to be in InRule as removing the call was fixing your issues. 

Only traces and dump will help us identity the issue otherwise.

**Comment by Maoni0** [comment]
it'd be best to [collect GC events](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-trace-instructions.md) to help diagnose this:

dotnet-trace collect --process-id <PID> --profile gc-collect

**Comment by markvincze** [comment]
@sebastienros Yeah the main thing the API does is executing InRule (which is doing a lot of CPU-intensive logic, and probably also allocating a lot of objects). With that call removed, the API is not really doing anything, so I guess it's expected that the performance problems only come to light if the call is there.  
If there will be concrete questions about what the library does and how, I can ask the vendor to chime in.  
I'll try to reproduce the issue today and collect the memory dump.

Thanks @Maoni0, I'll collect the trace too.

**Comment by markvincze** [comment]
Hi @Maoni0,

I installed `dotnet-trace` with
```
$ dotnet tool install --global dotnet-trace --version 3.0.0-preview8.19412.1
```
But if I try to run the `collect` command with the `gc-collect` profile, I get the following error.
```
$ dotnet-trace collect --process-id 1 --profile gc-collect
Invalid profile name: gc-collect
```
It happens both on my Windows dev machine, and on Linux in Kubernetes.  
I see in the [source](https://github.com/dotnet/diagnostics/blob/master/src/Tools/dotnet-trace/CommandLine/Commands/ListProfilesCommandHandler.cs#L70) that this profiles seems to be hidden behind an `#if DEBUG` flag at the moment. Do you know if there is an easy way to get it working?

Or should I configure the equivalent setup with `--providers`? Do I interpret the flag correctly that it should be this?
```
--providers Microsoft-DotNETCore-SampleProfiler,Microsoft-Windows-DotNETRuntime:32769:4
```

**Comment by Maoni0** [comment]
that definitely should not be DEBUG only. @sywhang, would you please take a look?

**Comment by sywhang** [comment]
> Or should I configure the equivalent setup with --providers? Do I interpret the flag correctly that it should be this?

Yes, you can configure the equivalent setup with --providers. 
`--providers Microsoft-Windows-DotNETRuntime:8001:4` should turn on the GC/Exception keywords only.

> that definitely should not be DEBUG only

I agree. I will bring this up in the next release of dotnet-trace.

**Comment by markvincze** [comment]
@Maoni0 I've collected a trace while the issue was happening to one of the instances, I've uploaded it here: https://drive.google.com/file/d/1Sz4y9ugRxmV43eu3aWW2dc87twE3wUnm/view?usp=sharing

I haven't used PerfView before, so if you could give me some pointers about what to check, or if you'd have some spare time to take a look at the trace, that'd be greatly appreciated!

**Comment by markvincze** [comment]
Hey all,

So far I couldn't find the root cause of the issue. I'll post a new graph of the runtime metrics, which illustrates the issue more clearly on a longer time period. Before the time period on the screenshot, the API has been properly operating for some hours, and during this whole time period there was no change in either the environment (the API is running in a dedicated docker container), nor in the volume or nature of the incoming traffic.

![image](https://user-images.githubusercontent.com/1122274/63839501-b66ae880-c97f-11e9-882a-f5560c593b35.png)

The behavior changes in 4 distinct phases:

 - Phase 1: This is normal operation. The memory usage keeps going up and down. Mostly Gen0 (non-concurrent) collections are happening, Gen1 (non-concurrent) is happening less often, and Gen2 happens only occasionally. (Based on my understanding, this is the normal way how GC should operate, right?)
 - Phase 2: Suddenly the Gen0 collections almost disappear, and the app is doing almost exclusively Gen1 non-concurrent collections.
 - Phase 3: Suddenly the Gen1 collections completely disappear, and the app is doing Gen1 **foreground** collections, and also a high rate of Gen2 collections.
 - Phase 4: This is when the app becomes unresponsive, and also it doesn't seem to recover from this, even after many hours. The process is only doing Gen2 collections, nothing else.

I still don't know how to interpret this behavior. I collected two traces  in the Phase 4 state, one a couple of minutes long, and another one for 20 seconds, I've uploaded them here:
 - Long trace: https://drive.google.com/file/d/1j720ZWSpyfZ2CZHgueKq-l8eOahyG2kx/view?usp=sharing
 - Short trace: https://drive.google.com/file/d/1S-UCDcU0E5fp72diRQgiycpE1DA9wWQv/view?usp=sharing

**Comment by markvincze** [comment]
I'm shooting in the dark, but is it possible that this is caused by the [fragmentation of the large object heap](https://blogs.msdn.microsoft.com/mariohewardt/2013/06/26/no-more-memory-fragmentation-on-the-net-large-object-heap/), and that I should occasionally set `GCSettings.LargeObjectHeapCompactionMode` to `CompactOnce`?

**Comment by markvincze** [comment]
Hi @Maoni0,

Thanks a lot for looking into this, it's really appreciated!

It's running in a docker container, in Kubernetes (on the Google Kubernetes Engine).  
The memory limit is set to 5GB, and I'm not setting `System.GC.HeapHardLimit`.

Since then this particular container has been stopped, so I cannot capture a dump on it, but a couple of days ago I collected a dump on another container producing the same behavior, I've uploaded it here: https://drive.google.com/file/d/11FshTwCQmo57zGbJTkRXn9UMwyZ4Odhr/view?usp=sharing

Tell if there is any more info I should collect.

**Comment by Maoni0** [comment]
hi @markvincze is there a way that you could verify a fix? how easy is it to repro? if you can't easily replace coreclr what if I share a commit/PR would that help?

**Comment by sebastienros** [comment]
@markvincze if you can publish the app as self-contained, then you could just replace the files with the ones @Maoni0 would share.

**Comment by Maoni0** [comment]
I'm not sure what files I would need to share other than the standard coreclr/clrjit/privatelib and I'm building this from the master branch. 
I could just submit a PR which would build more..not sure if that would help.

**Comment by Maoni0** [comment]
[coreclr 26457](https://github.com/dotnet/coreclr/pull/26457)

**Comment by markvincze** [comment]
Hey all,

In the last couple of days I've been testing running our API with the patched CLR binaries provided by @Maoni0.

The behavior changed, but after a while our instances still become unresponsive. Before Maoni's patch, the failing process was constantly doing gen2 collections, which is not happening any more, but what I see is that the process is not doing any collections at all. And then after a while (anything between 5-20 minutes) process crashes due to OOM, or Kubernetes kills it because its liveness health check times out.

Here are the GC stats for such an instance, which was running for ~12 hours before starting to fail.

![image](https://user-images.githubusercontent.com/1122274/64323117-1f77df00-cfc4-11e9-82da-030e00da211a.png)

I also plotted the response times of the actual API on the top left hand corner, you can see it increases from ~1 second to multiple minutes when the collections stop.

![image](https://user-images.githubusercontent.com/1122274/64323124-23a3fc80-cfc4-11e9-8917-706b516a3415.png)

And here are the stats of the same instance, zoomed in on its last hour. (You can see that some of the graphs are spotty, probably because the Prometheus metrics endpoint was also timing out occasionally.)

I'll try to grab a new trace and memory dump from one of the failing instances. (And I'll also try to test with `preview9` to see if that changes anything.)

**Comment by markvincze** [comment]
I've collected the trace and the memory drump from one of the failing instances.

 - Trace: https://drive.google.com/open?id=1Nb9lmKAJKGNvNV1BJEvoOHEbrh0jsDgi
 - Memory dump: https://drive.google.com/open?id=1uSAugwh4le2IJb6RzHE1zO7zuBAjIWc0

**Comment by markvincze** [comment]
Hey all,

It turns out there was a bit of a mishap, so on the previous screenshot and trace/dump I was still using a binary which didn't have Maoni's fix yet.

I made a new test run with the actual patched binaries. After running for some hours, the application still ends up being stuck in the degraded state, and it doesn't get OOM killed.

These are the metrics of the service over a long, ~20-hour period. (You can see that the performance of the service suddenly degrades at ~06:10.)

![image](https://user-images.githubusercontent.com/1122274/64486601-3b32ed80-d22f-11e9-9a88-7b6211404922.png)

These are the metrics if I zoom in on the part when the degradation happens.

![image](https://user-images.githubusercontent.com/1122274/64486602-42f29200-d22f-11e9-9d62-a30c7112160a.png)

And these are the metrics for the last hour, during which it's continuously degraded.

![image](https://user-images.githubusercontent.com/1122274/64486604-471eaf80-d22f-11e9-9fbd-405e52b7b30b.png)

I've also recorded a trace and a memory dump (approximately at the same time when I took the screenshots of the dashboard).

Trace: https://drive.google.com/open?id=1Ci5ocFRfpvmLpUn3E6ydBbfASyqfPLGu
Memory dump: (I'll upload this one as well a bit later once I'm at home.)

cc @Maoni0

**Comment by Maoni0** [comment]
ok, this trace definitely has a different behavior from the last one where I failed to give you the build actually with the fix. when you were running the last build you didn't actually allocate anything which was consistently with my diagnosis (because we incorrectly kept retrying). in this trace you are allocating (you allocated 7.9GB during the ~60s the trace recorded and 3.8GB were on the LOH). the reason why it ran so slow is you keep hitting the limit set on the container. everything is already very compacted - your gen2's fragmentation ratio is 0% and LOH's is 5%. so the fix is working but your heap size kept growing as you can see in your heap size graph. 

note that if you don't manually set [System.GC.HeapHardLimit or System.GC.HeapHardLimitPercent](https://github.com/dotnet/coreclr/pull/25574) in runtimeconfig.json, by default GC will take 75% of the memory limit set on the container. this is also consistent with the memory load that I'm seeing in the trace. now, you could set this to be say 100% of the limit but since your heap size is slowly going up, this indicates a managed memory leak which means at some point that limit will be hit and you'll be getting OOM eventually anyway.

**Comment by Maoni0** [comment]
thank you very much! this trace definitely has a different behavior from the last one where I failed to give you the build actually with the fix. when you were running the last build you didn't actually allocate anything which was consistently with my diagnosis (because we incorrectly kept retrying). in this trace you are allocating (you allocated 7.9GB during the ~60s the trace recorded and 3.8GB were on the LOH). the reason why it ran so slow is you keep hitting the limit set on the container. everything is already very compacted - your gen2's fragmentation ratio is 0% and LOH's is 5%. so the fix is working but your heap size kept growing as you can see in your heap size graph. 

note that if you don't manually set [System.GC.HeapHardLimit or System.GC.HeapHardLimitPercent](https://github.com/dotnet/coreclr/pull/25574) in runtimeconfig.json, by default GC will take 75% of the memory limit set on the container. this is also consistent with the memory load that I'm seeing in the trace. now, you could set this to be say 100% of the limit but since your heap size is slowly going up, this indicates a managed memory leak which means at some point that limit will be hit and you'll be getting OOM eventually anyway.

**Comment by markvincze** [comment]
@Maoni0 Did something change in the GC in 3.0 compared to 2.0 which explains this behavior? Because in 2.0 we've never encountered this degraded performance for an extended time period. We've occasionally seen some containers being restarted with `OOMKilled`, but that always happened suddenly, without the performance of the application being degraded first.

Maybe 3.0 is doing a better job at respecting the container's memory limit, so it's trying to keep the application "alive" as long as it can? If that's the case, then is there a way to fall back on the previous behavior to fail faster with OOM?

**Comment by Maoni0** [comment]
between 2.0 and 3.0, many things have changed including the GC. it's impossible to say what caused the memory leak without more data. 

one thing I mentioned above was by default we do set a limit that's only 75% of the memory limit (which you can change). however seeing from your chart for 2.0 you were using between 4 and 5gb but for your 3.0 you are clearing using > 5GB. so something is already different there.

**Comment by markvincze** [comment]
Thanks @benaadams, that sounds like a really reasonable thing to do, I feel bad for not thinking about it earlier. (We actually have a concurrent request limit middleware already in this service, but that doesn't do queuing, it just rejects the requests if we're already processing more than N.)

I'll definitely give it a try.

**Comment by markvincze** [comment]
Hi @Maoni0,

I've upgraded to the final 3.0 version, but I'm still struggling to solve this issue.  
I tried setting `HeapHardLimitPercent` to `100`, but that didn't improve the situation, pods still get stuck unresponsive for hours before they eventually get OOMKilled.  
I guess this whole issue comes down to the improvements around the "Docker and cgroup Limits", right? Do you think there is a way to somehow achieve the old 2.2 behavior of applications getting OOMKilled immediately in this situation? Because in our main production cluster still running 2.2 we get a handful of OOMKilled pods every day, which is something we can live with, but pods becoming unresponsive for hours is not.  
(Of course the ideal solution would be to fix the memory leak, but at the moment we don't have any ideas about it, and it might even be happening inside obfuscated vendor code, so fixing it might not happen for a long time. On the other hand, we're very eager to update to 3.0 to get the benefits of the general perf improvements.)

So if you have any suggestions about how the old 2.2 behavior can still be achieved on 3.0, that'd be greatly appreciated. (For example, is it maybe possible to set `HeapHardLimitPercent` to something larger than `100`? Or that wouldn't help at all?)

Thanks!

**Comment by Maoni0** [comment]
> I guess this whole issue comes down to the improvements around the "Docker and cgroup Limits", right?

no, this comes to down the framework memory usage changes between 2.2 and 3.0. when you upgrade from one version of the framework to another, MANY things have changed, not just the GC. the fact that you are already doing full blocking GCs and are still seeing larger memory usage most likely points to whatever code you are using in the framework simply uses more memory. 

I would suggest to treat this as a normal memory leak investigation. 

> For example, is it maybe possible to set HeapHardLimitPercent to something larger than 100?

that would not help at all because we can't use more memory than what you specified as the limit on the container (that would completely defeat the purpose of specifying a memory limit on the container).

**Comment by Pilchie** [comment]
I'm going to close this, seeing as it doesn't look like there is anything for AspNetCore to do here.

**Comment by brianrob** [comment]
@markvincze, you're definitely on the right track with the strategy that you're using here.  The fact that `gcroot` is hanging is interesting, but could be expected depending upon the size of the heap.  The algorithm for finding roots is fairly intensive and so this sort of thing does happen.

We can go about this in a couple of different ways, but probably the easiest is to create heap snapshots that can be viewed with PerfView.  This avoids the `gcroot` issue but will give you exactly what you want - the path to the root.  It does this by walking the from the roots rather than to the roots.  If you take a couple of heap snapshots instead of dumps in the same way that you described above, you can then open them up in PerfView and diff them.

@josalem, can `dotnet-trace` capture eventpipe-based heap snapshots that can be opened in PerfView?  I'd like to have @markvincze use the same strategy that he's using above to capture heap snapshots instead of dumps, so that he can then open them up in PerfView and diff them.

**Comment by Maoni0** [comment]
is there something special about the dumps taken with dotnet-dump that makes them not viewable in perfview?

**Comment by brianrob** [comment]
I don’t think there is anything specific about the dumps that makes them not openable in PerfView other than that the work hasn’t been done to teach PerfView how to open them. I imagine this could/should be done.

**Comment by josalem** [comment]
@brianrob dotnet-trace can’t create gcdumps by itself but the new tool (https://github.com/dotnet/diagnostics/pull/581) dotnet-gcdump can.  Unfortunately, there were some runtime changes required so gcdumps over EventPipe only work in 3.1-preview2 and newer.  @markvincze, if you’re willing to run on a nightly build of the release/3.1 branch, you could use the tool in that PR to take several gcdumps and open them in VS or PerfView to compare the count of various types and what is rooting them.

That being said, I believe that PerfView ships with a command line tool called HeapDump that can convert a mini dump into a gcdump.  I’ve never used it, but the PerfView repo has the code for it.

**Comment by markvincze** [comment]
Hey folks,

Thanks a lot for the replies!

@josalem I think I'll try the `dotnet-gcdump` approach. Is there now an easy way to install `dotnet-gcdump`, or do I have to build it from your branch, and copy the binary to `~/.dotnet/tools`?

**Comment by josalem** [comment]
The latter.  Until that PR has been merged and we push an official build to nuget.org, you'll have to build it from source unfortunately.  It's a bit "hot off the press" so to speak.  Please leave some feedback about the experience once you've used it and let me know if you need help wiring things up!

**Comment by markvincze** [comment]
@josalem,

I managed to upgrade to `3.1.100-preview2`, built `dotnet-gcdump`, and ran a `collect`.

But when I try to open the `.gcdump` file in PerfView, it fails with this error.

```
Started with command line: "C:\Tools\PerfView.exe" 
PerfView Version: 2.0.43  BuildDate: Tue, 18 Jun 2019 19:39:46 GMT
PerfView Start Time 2019-10-25 2:10:35 AM
Started: View
Warning: PdbScope not found at C:\Tools\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at C:\Tools\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Completed: View   (Elapsed Time: 0.288 sec)
Started: Opening 20191025_015241_1.gcdump
Completed: Opening 20191025_015241_1.gcdump   (Elapsed Time: 0.008 sec)
Started: Opening  Stacks
Completed: Opening  Stacks   (Elapsed Time: 0.023 sec)
Error: Error opening file C:\Workspaces\Local\RulesApiDumps\20191025_015241_1\20191025_015241_1.gcdump Message: Could not find type Microsoft.Diagnostics.Tools.GCDump.DotNetHeapDump.GCHeapDump
```

Do you know what might be the reason for this? I have the latest 2.0.46 version of PerfView.

**Comment by josalem** [comment]
Ah, that is unfortunate.  I think I know what is going on there.  Seems like the file format has some hardcoded names in it and when I added namespaces to these classes in the tool it made deserializing the data incompatible.  Let me undo that before that PR goes through.  Since you're building from my branch, just undo the top commit to get rid of that change.  I'll fix it in the final PR.

**Comment by markvincze** [comment]
@josalem Thanks, that way it worked.

I managed to open the dumps in PerfView, and check the diffs as well. The objects which keep accumulating are coming from the third-party library we're using, which is also obfuscated, thus can't even see the real type names, so I'll reach out to the vendor for some help.

**Comment by josalem** [comment]
@markvincze I'm glad it helped (for the most part)!
