### ISSUE TITLE
Define redirect location on sign in

### ISSUE THREAD

**Issue by T3charmy** [aspnet/AspNetCore#13294]
### Is your feature request related to a problem? Please describe.
I would like to be able to define what happens after user logs in. 

### Describe the solution you'd like
My suggestion is to change [this line](https://github.com/aspnet/AspNetCore/blob/5b2f3fb5f7f24ac3e91c5150a55cc411b2b36b76/src/Azure/AzureAD/Authentication.AzureAD.UI/src/Areas/AzureAD/Controllers/AccountController.cs#L27), similar to [this line](https://github.com/aspnet/AspNetCore/blob/5b2f3fb5f7f24ac3e91c5150a55cc411b2b36b76/src/Azure/AzureAD/Authentication.AzureAD.UI/src/Areas/AzureAD/Controllers/AccountController.cs#L38). Doing this would allow something like this

```cs
namespace MyProject.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult SignedIn()
        {
            return RedirectToAction("Index", "Home"); // Would also allow for more specific 
            // logic after user signs in
            // For example if you wanted users in specific role or group to be redirected to
            // a specific page on login
        }
    }
}
```

### Additional context
I tried to research and see if another user has had a similar request, but I have not seen one. If there is already a way to do this let me know. 

Edit:
Actually in my testing the method I mentioned may not work as intended as, testing the logic of the sign out I end up with a URL like
`https://localhost:44325/Account/SignOut?page=%2FAccount%2FSignedOut` I'm not sure if this is by accident or by design. is the expected result here supposed to be `https://localhost:44325/Account/SignedOut` ?

**Comment by blowdart** [comment]
I'm interested in why scaffolding the page out and changing it to do what you want isn't the approach you want to take. Could you go a little further in your description please?

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
