### ISSUE TITLE
Blazor + PowerBI Embedding

### ISSUE THREAD

**Issue by tsmccartan** [aspnet/AspNetCore#13297]
I have a Blazor App and am trying to Embed a Power BI Report within a component.  I have the following sample: https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers

And this sample uses ASP.NET Core and it is working great, after configuring it to our Dedicated Power BI Server in Azure.

I have basic reports embedded in my blazor app and it works fine, I am able to load the report and render it.  But now I am trying to pass in Roles, to do Row Level Filtering in Power BI, and to do that, I followed the article here: https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security

This same code works in the sample .NET core ASP.NET app, (Downloaded from MS Git)

But the same line of code to get the Token is not compiling in the Blazor app, with an error I don't know how to resolve.  So I am wondering if this is some bug in Blazor?

Code Lines:  Also from the Microsoft Docs here: https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security

var tokenResponse = await client.Reports.GenerateTokenInGroupAsync(ConfigSettings.GroupId, ConfigSettings.ReportId, generateTokenRequestParameters);

This same line of code in my Blazor App, in a c# class (With all proper references, NuGet packages, etc.) does not compile with the following error:

'IReportsOperations' does not contain a definition for 'GenerateTokenInGroupAsync' and the best extension method overload 'DashboardsOperationsExtensions.GenerateTokenInGroupAsync(IDashboardsOperations, Guid, Guid, GenerateTokenRequest, CancellationToken)' requires a receiver of type 'IDashboardsOperations'

Any thoughts on why this would now work in the Blazor app, but normal embedding works fine, and these lines work in the .NET Core ASP.NET sample app?

Thanks,
Tom

**Comment by danroth27** [comment]
@tsmccartan Possibly a missing `using` statement for the namespace of the extension method?

**Comment by tsmccartan** [comment]
This issue has been resolved.  I downgraded the Microsoft.PowerBI.API Nuget Package from v3.4.0-beta to v2.10.0.  After this it compiled and resolved the method and works appropriately.  I believe there may be something with the 3.4 version of the PowerBI.API package.
