### ISSUE TITLE
3.0.0-preview9-19419-03 errors

### ISSUE THREAD

**Issue by phillipbritain** [aspnet/AspNetCore#13308]
After installing the latest Preview 9 SDK and updating all of my Microsoft packages to 3.0.0-preview9-19419-03 I am getting the following errors and warnings:

The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft'
The type or namespace name 'IHttpContextAccessor' could not be found
The type or namespace name 'Logging' does not exist in the namespace 'Microsoft.Extensions'
The type or namespace name 'ILogger<>' could not be found
Could not locate the assembly "Microsoft.Extensions.Logging.Abstractions". Check to make sure the assembly exists on disk.

Everything was working fine in Preview 8.

**Comment by Rick-Anderson** [comment]
@phillipbritain  if this is resolved can you close this issue?

**Comment by Rick-Anderson** [comment]
@pranavkm no repo, recommend closing this.  cc @mkArtakMSFT
