### ISSUE TITLE
IFormFile file returns null in ASP Core 3

### ISSUE THREAD

**Issue by simon617** [aspnet/AspNetCore#13307]
I have problem binding a IFormFile field in ASP.NET Core 3. It always return null value. Any idea ?

Thx
[Add.cshtml.cs.txt](https://github.com/aspnet/AspNetCore/files/3523276/Add.cshtml.cs.txt)
[Add.cshtml.txt](https://github.com/aspnet/AspNetCore/files/3523277/Add.cshtml.txt)
[AddItemModel.cs.txt](https://github.com/aspnet/AspNetCore/files/3523278/AddItemModel.cs.txt)

**Comment by pranavkm** [comment]
Looks like you have a typo in your code:

`<form method="post" enctyp="multipart/form-data">`

This needs to be:

`<form method="post" enctype="multipart/form-data">`

**Comment by simon617** [comment]
Yes, works perfect. Thx
