### ISSUE TITLE
Blazor: Failed to compare two elements in the array

### ISSUE THREAD

**Issue by alexandrereyes** [aspnet/AspNetCore#13313]
Looks like I reached the limit of pages on Blazor lol, here is a project to reproduces the issue `Failed to compare two elements in the array`:
[bug-repro.zip](https://github.com/aspnet/AspNetCore/files/3525650/bug-repro.zip)

[related issue](https://github.com/aspnet/AspNetCore/issues/5548)

**Comment by danroth27** [comment]
@alexandrereyes Thank you for reporting this issue! We are able to reproduce it and we are working on a fix.

**Comment by pranavkm** [comment]
@alexandrereyes in the meantime you could workaround this issue by tweaking the order in which `@page` attributes are defined in `ClienteEndereco.razor`:

```C#
@page "/cliente/{IdCliente:guid}/enderecos/"
@page "/cliente/{IdCliente:guid}/enderecos/{IdEndereco:guid}"
```

That worked for me.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/aspnet/AspNetCore/commit/7bb56a8dba0716a528136fa69853615eb5f46793

**Comment by peteralbanese** [comment]
Is this fix part of .NET Core 3 Preview 8 ?

**Comment by danroth27** [comment]
@peteralbanese Nope, it's coming in Preview 9.

**Comment by peteralbanese** [comment]
Oddly enough I updated all the references packages for my project to the latest versions and updated to .NET Core 3.0 Preview 7 (from .NET Core 3.0 Preview 6) and this solved my problem. (fingers crossed). Thanks Dan
