### ISSUE TITLE
Entity not getting to controller during HttpPut request

### ISSUE THREAD

**Issue by TehWardy** [aspnet/AspNetCore#13314]
I don't know if this is a binding issue or something, between 2 AspNetCore 2.2 applications so i'm looking for some advice on how to pinpoint this ...

**On the client** 

![image](https://user-images.githubusercontent.com/6891030/63439629-4fe94600-c426-11e9-9caf-d14e5e139bd7.png)

**On the server** 

![image](https://user-images.githubusercontent.com/6891030/63439639-57a8ea80-c426-11e9-813f-ef49bf405d41.png)

... is there some reason this wouldn't work?

On this occasion i'm getting nothing on the server console except for a thread exit message shortly after the request is handled on the server.

**Comment by davidfowl** [comment]
Got any logs?

**Comment by TehWardy** [comment]
The server logs churned out nothing (as stated previously) ...
I have my own logging for when requests are received / handled but it just shows the request URL and method and the fact that it was an authorised call.

The body I'm nott currently reading / logging in an way but given this code I figured as it's all framework essentially i'm not sure what else would be relevant to provide.

Is there something specific I can add logging for that might help here?

**Comment by danroth27** [comment]
Are there any errors in the model state? Inspect `this.ModelState` in the debugger and see if anything is there.

It looks like you're also using OData, so I'd recommend following up with them to see if they have any additional thoughts.

**Comment by TehWardy** [comment]
ah good shout !!! Why did I not think of that!!
