### ISSUE TITLE
IClientRequestParametersProvider not registered

### ISSUE THREAD

**Issue by ryan-motive** [aspnet/AspNetCore#13321]
I'm trying to get Identity Server up & running without EF. I've currently set up the server to run in-memory stores just to get it off the ground, but I'm hitting the problem that `IClientRequestParametersProvider` is never registered for DI which means that the `OidcConfigurationController` class can't be initialized.

There's no documentation for how and where this interface needs to be used. The only place it's registered in the code is in `IdentityServerBuilderConfigurationExtensions.ConfigureReplacedServices`. This is called from a number of places, but all of those require a config object which the demo doesn't have--calling the defaults of any of the calls (e.g. `AddApiResources`) throws a NPE later because the config object is null.

At this stage I have no idea if this is a bug or intended behavior and we're expected to add our own implementation (the default implementation is internal and can't be registered externally). In short, it seems like the only path that's currently supported by this integration is EF, which we can't use for a number of reasons.

**Comment by blowdart** [comment]
This is definitely not what our templates are aimed at. You'd have to not use our opinionated templates, and ask the [Identity Server](https://github.com/IdentityServer) folks how to proceed.
