### ISSUE TITLE
Error on running Integration Test on ASP.Core 2.1

### ISSUE THREAD

**Issue by simon617** [aspnet/AspNetCore#13326]
Follow a exercise to run a integration test on ASP Core 2.1 but returns the attached error. Any idea ? 
![IntegrationTest](https://user-images.githubusercontent.com/42394945/63490282-e7ae6900-c4e6-11e9-82d1-4be918dd9687.png)

[DigitalLibraryApplication.zip](https://github.com/aspnet/AspNetCore/files/3528548/DigitalLibraryApplication.zip)

**Comment by pranavkm** [comment]
@simon617 we'd recommend using the testing infrastructure as described in https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#basic-tests-with-the-default-webapplicationfactory. Using `TestServer` \ `WebHostBuilder` requires quite a few setup pieces to be in place which is non-trivial.

Feel free to reopen this issue if you still see issues once you've tried the integration testing package.
