### ISSUE TITLE
Add Uri to 'Request finished' log entry

### ISSUE THREAD

**Issue by punppis** [aspnet/AspNetCore#13330]
When starting to process the request, you get a log entry such as
`Request starting HTTP/1.1 POST http://localhost:5000/path/to/api application/json; charset=utf-8 433`

When requests is processed, log entry does not include the Uri, like this
`Request finished in 28.674ms 200 application/json; charset=utf-8`

Due to volume of the logs even with one concurrent user it is hard to understand what is going on based on the 'request finished' log entry alone. For example if I see a unusually large processing time I have to somehow figure out what was the Uri of this request in order to solve the problem.

With multiple concurrent users it is practically impossible or very hard to analyze the log files; you have no way of knowing which of the 'request finished' entries was connected to 'request started' entry.

For example, if I want to analyze request times from logs the current system is unusable.

Please add Uri to 'request finished' and/or include a some kind of identifier for each request.

**Comment by anurse** [comment]
It seems reasonable to do this since the Console Logger doesn't really have enough info to correlate the finished message with the started message.

**Comment by khellang** [comment]
This should've been closed with https://github.com/aspnet/AspNetCore/pull/10102.

**Comment by khellang** [comment]
Oh, wait, this issue was created after #10102 was merged. Anyway, it's fixed in 3.0.

**Comment by anurse** [comment]
Oop, you're right. We did talk about Ben's PR in triage in relation to a different issue but missed that it contained the URL and covered this case as well :). Thanks for catching this!
