### ISSUE TITLE
[Preview 8] Microsoft.AspNetCore.Identity.EntityFrameworkCore does not support netstandard 2.1

### ISSUE THREAD

**Issue by failfmi** [aspnet/AspNetCore#13340]
### Describe the bug
When trying to install  **Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.0.0-preview8.19405.7** in a Class Library (netstandard 2.1)  it says it only supports netcoreapp3.0

**Note**: In SDK 2.2, Microsoft.AspNetCore.Identity.EntityFrameworkCore supports netstandard 2.0

### To Reproduce
1. Using this version of ASP.NET Core 'SDK 3.0.100-preview8-013656'
2. Create a .NET Core Class Library (netstandard 2.1)
3. dotnet add package Microsoft.AspNetCore.Identity.EntityFrameworkCore --version 3.0.0-preview8.19405.7
4. See error: **'error: Package Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.0.0-preview8.19405.7 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1) Package Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.0.0-preview8.19405.7 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)
error: Package 'Microsoft.AspNetCore.Identity.EntityFrameworkCore' is incompatible with 'all' frameworks in project'**

### Expected behavior
Microsoft.AspNetCore.Identity.EntityFrameworkCore supports netstandard 2.1

**Comment by pranavkm** [comment]
See this announcement - https://github.com/aspnet/Announcements/issues/324. As of 3.0, most packages in ASP.NET Core will only target .NET Core.

**Comment by PinpointTownes** [comment]
@pranavkm this one really looks like an oversight, tho', since the rest of Identity was updated to stay `netstandard2.0`-compatible. While it can't target `netstandard2.0` because EF is no longer compatible, this package could easily target `netstandard2.1`.

@HaoK probably knows why it was done this way 😄

**Comment by HaoK** [comment]
Yeah this was just an oversight, we made the change fairly late to Identity.Extensions in June to target netstandard 2.0, since we did that, we can now have this package target netstandard2.1

cc @ajcvickers @blowdart I'm assuming this is too late for preview9, so maybe this is something for 3.1?

**Comment by ajcvickers** [comment]
@Pilchie @glennc @DamianEdwards This might be something we want to take post preview 9. It should be safe (.NET Core 3.0 -> .NET Standard 2.1) and the story is pretty inconsistent as it is.

**Comment by Pilchie** [comment]
Agreed.

**Comment by Pilchie** [comment]
(As long as it doesn't cause problematic source build implications)

@HaoK can you put together a fix?

**Comment by ajcvickers** [comment]
@JunTaoLuo -- any source build implications here?

**Comment by HaoK** [comment]
PR here: https://github.com/aspnet/AspNetCore/pull/13381

**Comment by JunTaoLuo** [comment]
No source build implications. This package is not built in source build.

**Comment by vankooch** [comment]
Would be great to have it before preview 9. Simple demo projects can't upgrade to dotnet core 3, as it breaks having stuff in a class lib.
