### ISSUE TITLE
Implement HTTP_SEND_RESPONSE_FLAG_GOAWAY

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#13356]
// HTTP_SEND_RESPONSE_FLAG_GOAWAY - A flag that must always be specified with
// HTTP_SEND_RESPONSE_FLAG_DISCONNECT. For pure HTTP/1.x connections, that is
// connections that don't do HTTP/2 and HTTP/3, this behaves the same as
// HTTP_SEND_RESPONSE_FLAG_DISCONNECT. For HTTP/2 and HTTP/3, this results in
// sending a GOAWAY frame and will cause the client to move to a different
// connection.

#define HTTP_SEND_RESPONSE_FLAG_GOAWAY              0x00000100

We'll probably add this flag to any response with a `Connection: close` header to restore the HTTP/1.1 functionality.
https://github.com/aspnet/AspNetCore/blob/5c05b9288a1250261a53f0d39559639ec77b5764/src/Servers/HttpSys/src/RequestProcessing/ResponseBody.cs#L432-L435

Should we also do the same thing in IIS?

What about Kestrel? It sounds like Kestrel already supports IConnectionLifetimeNotificationFeature.RequestClose() for a graceful GoAway?

**Comment by Tratcher** [comment]
Testing: Confirm that this doesn't break anything on older windows, and that it works as expected on new versions (which version?).

**Comment by jkotalik** [comment]
@Tratcher please share whatever channel you are using to get new HttpSys bits s.t. we can test this.

**Comment by Tratcher** [comment]
I don't have a new channel yet. @shirhatti?

**Comment by anurse** [comment]
We have a partner requesting this.

**Comment by Tratcher** [comment]
Done and merged for 3.1.0-preview1.

Leaving this open to track adding a helix queue for testing later windows versions. Right now this is only covered by negative tests.
