### ISSUE TITLE
input type="time" reseting value

### ISSUE THREAD

**Issue by sbuchok** [aspnet/AspNetCore#13357]
Here is a BlazorFiddle that shows the issue:

https://blazorfiddle.com/s/u8qkq9li

As soon as you change the last value, the input resets. 
You'll also notice that on initialization that the control doesn't get set with a value.

**Comment by Postlagerkarte** [comment]
You can not bind input type="time" to DateTime but you can bind it to Timespan.

**Comment by sbuchok** [comment]
TimeSpan however works:
https://blazorfiddle.com/s/uk47jfsz

However according to this ticket: 
https://github.com/aspnet/AspNetCore/issues/13322

TimeSpan isn't supported.

**Comment by Postlagerkarte** [comment]
Indeed this is very confusing.

**Comment by sbuchok** [comment]
Glad I'm not the only one. ;)

**Comment by sbuchok** [comment]
@javiercn Still an issue as the seconds don't allow for being changed. Also, making a component has nothing to do with the issue at hand. 

https://blazorfiddle.com/s/qnr24exy

**Comment by javiercn** [comment]
@sbuchok This is not an area where I'm super familiar with, I've chatted with someone else on the team and there seems to be a way we can do this, so I'll see if we can make the framework handle it automatically.

**Comment by sbuchok** [comment]
It would be nice if input type=time would work with:
DateTime
TimeSpan
there are offset time types, but honestly, I've never used them but would probably want to work with those types as well.

**Comment by sbuchok** [comment]
@javiercn Thanks, I keep an eye on this. Once things are done, I will help to confirm with my use cases.

**Comment by javiercn** [comment]
I have a PR for this, although I have my reservations about supporting input type=time as it has drawbacks described in https://github.com/aspnet/AspNetCore/pull/14379#issuecomment-534605155

**Comment by sbuchok** [comment]
Why is it that input type="time" only supports DateTime now and not also TimeSpan? It makes more sense to support TimeSpan than it does to support DateTime.
