### ISSUE TITLE
RedirectResult support for 303 (See Other)

### ISSUE THREAD

**Issue by Davilink** [aspnet/AspNetCore#13359]
### Is your feature request related to a problem?
Hi, i was reading the RedirectResult class : https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.redirectresult?view=aspnetcore-2.2
and the HTTP Code "See Other (303)" is not mention here.

### Describe the solution you'd like
Add the HTTP Code status in RedirectResult

**Comment by pranavkm** [comment]
Is there a specific scenario where it's useful to you? This is the first we've been asked about this status code and I'm trying to understand why you'd use 303 over 302 or 307.

**Comment by Davilink** [comment]
303 is to indicate to the user agent to do a GET to a different location, when a 302 is to indicate the user agent to go to a different location but doesn't force to use the GET method.

**Comment by Davilink** [comment]
We have kind of a workaround for that redirect an http:// to a app:// scheme to by pass an email problem and the user agent has to do a GET on that app://scheme to work.

**Comment by rmja** [comment]
@pranavkm 

A use case is for the Put-Redirect-Get pattern equivalent of the Post-Redirect-Get pattern.

302: A post request is followed by a GET to the location header
302: A put request is followed by PUT to the location header

303: A post request is followed by a GET to the location header
303: A put request is followed by GET to the location header

The last is of cause the desired in this case

**Comment by pranavkm** [comment]
@Tratcher can `HttpResponse.Redirect` use 303 by default: https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http/src/Internal/DefaultHttpResponse.cs#L159? It sounds like they're almost interchangeable (assuming the client understands HTTP 1/1).

**Comment by SARAVANA1501** [comment]
A 302 redirect is a temporary redirect. It is not cacheable by default and should be re-requested every time (but you can override this with caching headers). The follow-up request should use the same method (POST, GET, CONNECT, PUT, DELETE, etc.) as the original request and for anything other than GET and HEAD requests, the client should prompt the user before making the request. This is the part that the clients got wrong and most of them change the method for the follow-up request to GET, regardless of the original method.

A 303 redirect is the same as a 302 except that the follow-up request is now explicitly changed to a GET request and no confirmation is required.

**Comment by Tratcher** [comment]
> @Tratcher can HttpResponse.Redirect use 303 by default: 

Breaking change. I don't recommend it, 303 is not used or supported as broadly as 302.

**Comment by mkArtakMSFT** [comment]
After reviewing this issue one more time we believe that using the `StatusCodeResult` with `303` argument is sufficient here. We're closing this issue as no more action is pending here.

**Comment by MikeWasson** [comment]
What's the right way to set the Location header using StatusCodeResult?
