### ISSUE TITLE
[Blazor client-side] Handle large upload

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#13353]
Hi guys, I actually develop an upload system in my blazor app with dropzone (https://www.dropzonejs.com/), and i meet some problems to handle large data.

I manage file selection with dropzone, retrieve the base64 of the file and then upload the base64 string by invoking c#.

I precise i make my app working both in client and server side.

In server side i don't really have problem, i can upload 10Mo file easily, but in client-side i have a js error with file started at 1Mo/2Mo.

I see différent topic on this but i don't really find the answer on how i can handle this.

For the moment, the only idea i have is to "chunk" my base64 in différents parts (like 500ko parts) and make multiple c# call (with chaining promise), and at the end reconstruct the entire base64, but it's really ugly, if i can avoid this it's better.

so, there is something planned in a short future to handle that ?

I precise the solution i found to handle that was to make a direct http call in js to controller, but with these solution i lost the compatibility with server side and anyway, i have to stay in the blazor context because my views have to react to this upload.

If nothing is planned, do you have better solutions ?

thanks !

**Comment by danroth27** [comment]
@julienGrd Thanks for reporting this issue! We'll need to investigate to understand why this is happening. If you could provide a minimal repro project that demonstrates the problem that would help. We will most likely investigate this after .NET Core 3.0 has shipped later this year.

**Comment by julienGrd** [comment]
Hi @danroth27  ! You will find a repro project here ! : https://github.com/julienGrd/DemoBlazorDropZone
- launch the project, you will see a drop area in the home page
- add a "small" file in the drop area (in my test <500 kb) : the upload is OK, the base64 of the file is shown
- add a "big" file in the drop area (in my test >4000kb) : you will have the error RuntimeError: memory access out of bounds

thanks for your help ! and good luck for the release, blazor is amazing !

**Comment by SteveSandersonMS** [comment]
There are now existing OSS libraries for handling large uploads, so hopefully your requirement should be covered :) Example: https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/
