### ISSUE TITLE
Websockets connection fails for random users, Fallback to SSE works for them

### ISSUE THREAD

**Issue by swAucxis** [aspnet/AspNetCore#13369]
### Describe the bug

Some “random” users doesn’t seem to be able to connect with Websockets.
Once the random user is “selected” as unable to connect with Websockets retrying the websocket connection won’t work in the near future.
The day after that user is able to connect to the signalr server through Websockets and other “random” users aren’t able to connect.

What SignalR does automatically is trying to reconnect with different technology and on pc’s where websockets aren’t working SSE is working.

This issue seems similar to https://github.com/aspnet/SignalR/issues/2333
But the proposed solution there has been tested and didn’t work. 
We only have one server so the solution provided there was to use sticky sessions but that’s not the case here.

### To Reproduce
The problem is hard to reproduce because it might be related to the amount of users connected through websockets.

### Expected behavior
We expect that all users (100-1000) are able to connect through websockets. Since low latency expectations are priority.

### Screenshots
https://i.imgur.com/94QZh8O.png

### Additional context

Technology
-	SignalR Javascript client: 1.0.0
-	SignalR Server Side: 1.0.1.0 (.net Core)
-	SignalR Server is running on Kubernetes cluster: 1 instance
-	Kubernetes using ingress with nginx
-	Operating System Server: Linux
-	Operating System Client: Windows
-	Host: Azure
-	Browser on client: Chrome

**Comment by BrennanConroy** [comment]
First off, you should definitely be using the latest patch version as there could be bug fixes. 1.0.4 is the latest for 1.0.X currently.

Can you gather logs when the "random" user is unable to connect with websockets? There isn't really any actionable info here without some logs. https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2

**Comment by swAucxis** [comment]
We will update SignalR to the newest version and add logging. Since it's hard to reproduce it might take a couple of days to give an update.

**Comment by halter73** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
