### ISSUE TITLE
Mapping Subdomains to Areas

### ISSUE THREAD

**Issue by TwentyFourMinutes** [aspnet/AspNetCore#13361]
### Is your feature request related to a problem? Please describe.
I would like to be able to map a subdomain e.g. `blog.example.com` to an area. Lets say someone would be hitting `blog.example.com/Posts/LatestPost`, it would be hitting the action called `LatestPost` in the `Posts` controller which is in the `Blog` area.

### Describe the solution you'd like
In my opinion it would be really handy if you could just map these in the `IApplicationBuilder.UseEndpoints` method. 

### Additional context
I used to create a custom Router which would implement the `IRouter` interface or similar, with the use of `IApplicationBuilder.UseRouter`. Since [this article on the asp.net core pre-release 4 version](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/) mentions the following:

> (....) In ASP.NET Core 2.2 we introduced a new routing implementation called Endpoint Routing which replaces IRouter-based routing for ASP.NET Core MVC.  (...)

> (...) While it’s still possible to use the old UseMvc() or UseRouter() middleware in a 3.0 application, we recommend that every application migrate to Endpoint Routing if possible. (...)

So I do not really know what I should use currently.

**Comment by JamesNK** [comment]
It is in 3.0 - https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/HostAttribute.cs

I don't think there is documentation for it yet though.

**Comment by TwentyFourMinutes** [comment]
@JamesNK Well there is also the `.RequireHost` method on the `ControllerActionEndpointConventionBuilder`, but I can't see how you would map a subdomain to an area then.

**Comment by TwentyFourMinutes** [comment]
It actually is easier then I thought, you can define all the Hosts that are allowed for a specified route, in my case I could do that by `.RequireHost("blog.localhost")`.
