### ISSUE TITLE
[Blazor] Usings in _Imports.Razor are marked as unused

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#13373]
Not sure there's anything we can do about it, but felt worth discussing.
* The usings are marked as unused on the _Imports.Razor file
* If you hover them there is a message that tells you they aren't being used.
* The IDE will color them in light gray which makes them hard to read.

![image](https://user-images.githubusercontent.com/6995051/63589498-2f240c00-c55e-11e9-9a20-4c8d268c236c.png)

Could we somehow teach the IDE which ones are being used?

If that's not possible, could we affect the coloring so that it is more readable?

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/5009?
