### ISSUE TITLE
Question about ASPNET Core 3 SPA templates and built-in Identity Server support for integration testing (TestServer).

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/AspNetCore#13388]
[Some of the new templates come with IS4 built in already for development.](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Startup.cs#L50-L51)

But will they work for Integration Testing (TestServer)?

Example: In Core 2.2 if you add a development IS4 instance, if you try to use `AddJwtBearer()` in your Startup and you target `http://localhost` (the in-memory TestServer) it will error the first time you try and hit an [Authorize] endpoint. This is because deep inside the handler registered by `AddJwtBearer` an HttpClient is created via `new HttpClient` to hit the discovery endpoint for the public encryption keys to validate the JWT. However, a client not created from the `TestServer.CreateClient` will not be able to hit the TestServer.

So, all that said, I am hoping that if I dotnet new up a SPA, I can also new up an xunit test, slap in `WebApplicationFactory` and start fetching tokens from the development.in-mem IS4 server and use them to hit my protected API endpoints.

**Comment by blowdart** [comment]
Oof, yea I doubt this is going to work as is. You'd probably have to end up adding the test hardness as an application, get the test via a credential flow of some sort, and you're not testing the application configuration any more.

@javiercn do you have any advice here?

**Comment by javiercn** [comment]
You won't be able to without overriding all the required pieces for testing, like replacing the HttpClientHandlers with ones that are created from WAF/TestServer.

This is doable, but it is not trivial.

**Comment by VictorioBerra** [comment]
I have actually solved this in my current project with the following solution:

```csharp
protected override TestServer CreateServer(IWebHostBuilder webHostBuilder)
{
    webHostBuilder
        .ConfigureAppConfiguration(config => 
            config.Add(new MemoryConfigurationSource() { InitialData = new Dictionary<string, string>
                {
                    { $"{nameof(AuthOptions)}:{nameof(AuthOptions.Authority)}", "http://localhost" },
                    { $"{nameof(AuthOptions)}:{nameof(AuthOptions.ProtectedResourceName)}", IntegrationTestConstants.IntegrationTestProtectedResourceName },
                }
            }));

    webHostBuilder
        .ConfigureServices(
        services =>
        {
            IdentityModelEventSource.ShowPII = true;
        })
        .ConfigureTestServices(
        services =>
        {

            var keyFile = File.ReadAllText("./tempkey.rsa");
            var tempKey = JsonConvert.DeserializeObject<TemporaryRsaKey>(keyFile, new JsonSerializerSettings { ContractResolver = new RsaKeyContractResolver() });

            var tokenValidationParams = new TokenValidationParameters()
            {
                ValidIssuer = "http://localhost",
                IssuerSigningKey = IdentityServerBuilderExtensionsCrypto.CreateRsaSecurityKey(tempKey.Parameters, tempKey.KeyId),
                ValidAudience = IntegrationTestConstants.IntegrationTestProtectedResourceName,
                ValidateLifetime = true
            };

            services
            // Set the new default to Integration for testing.
            .AddAuthentication(IntegrationTestConstants.IntegrationTestDefaultAuthenticationScheme)
            // Register a new handler for Integration
            .AddJwtBearer(IntegrationTestConstants.IntegrationTestDefaultAuthenticationScheme, "Integration Testing Auth Scheme", options =>
                {
                    options.TokenValidationParameters = tokenValidationParams;
                });

            // This is required to initialize the StaticRolling singleton
            Log.Logger = new LoggerConfiguration()
                .WriteTo.StaticRolling()
                .CreateLogger();
        });

    var testServer = base.CreateServer(webHostBuilder);

    return testServer;
}
```

But I think this is going to be a big issue since now adding integration tests to a fresh SPA template will require the developer to add the above boilerplate (which is not one-size fits all), or one of your solutions @javiercn @blowdart 

I think that we should consider the fact that these templates and this issue exposes a big gap we have right now regarding `WebApplicationFactory` and integration testing and try to find a solution. maybe in the form of modifications to the WAF, or extensions to aid us with this.

**Comment by javiercn** [comment]
We don't offer integrations with every possible component in the framework. Instead we offer extensibility points so that you can configure your application for testing purposes.

For testing purposes you don't need to do this, you can simply update/replace the JWT bearer middleware and generate your own JWT token for testing purposes.

Alternatively, use E2E tests instead with something like Selenium.

Hope this helps.

**Comment by VictorioBerra** [comment]
@javiercn 

> For testing purposes you don't need to do this, you can simply update/replace the JWT bearer middleware and generate your own JWT token for testing purposes.

I started down this road but I didn't have much luck finding the middleware. Are you referring to the ConfigurationManager? https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L88

Can you link me to some code to review or some documentation on what you mean? If there is a better way I would like to learn.

**Comment by JasonGT** [comment]
> For testing purposes you don't need to do this, you can simply update/replace the JWT bearer middleware and generate your own JWT token for testing purposes.

Hi @javiercn - any further information available? I'd love to see an example.

**Comment by VictorioBerra** [comment]
I am guessing maybe he meant to [register your own JwtBearerOptions](https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L26) and override stuff like the ConfigurationManager.

Maybe he means for us to replace [the post configure](https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerPostConfigureOptions.cs)?

Maybe he means this? https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L52

But I have no idea how to load that up with a token.

**Comment by VictorioBerra** [comment]
> For testing purposes you don't need to do this, you can simply update/replace the JWT bearer middleware and generate your own JWT token for testing purposes.

Also in my code snippet, I thought by adding a whole new `AddJwtBearer` in `ConfigureTestServices` was literally "update/replace the JWT bearer middleware". Unless you meant what i did with TokenValidationParameters was overkill?

**Comment by javiercn** [comment]
> I am guessing maybe he meant to [register your own JwtBearerOptions](https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L26) and override stuff like the ConfigurationManager.

This is the approach that I would take.

@Tratcher can provide more details on how to replace the JWT Bearer configuration for integration testing.

**Comment by Tratcher** [comment]
"update/replace the JWT bearer middleware" isn't a thing, `AddJwtBearer` adds a second one. Adding a second `AddJwtBearer` only works if it uses a unique scheme like you've done and you update the default scheme to match.

You seem to have gotten it working, what's the remaining issue?

**Comment by VictorioBerra** [comment]
@Tratcher Thanks. I suppose there is no remaining issue, we assumed by Javier's comment that either our solution was incorrect/poor or that there was a much simpler way we did not know about (speaking for @JasonGT here a bit too).
