### ISSUE TITLE
HTTP/2: Rare data corruption when stress testing against Kestrel

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#13384]
So we found one instance of data corruption and it's definitely occurring on the server (Kestrel). Our current working hypothesis is there is an off by one error when leasing memory out in our ConcurrentPipeWriter. What we see happening is a request with a large response is getting its first byte corrupted with a value that was previously written. There is a test that is running which sends 1-byte data frames from the client to the server and vice versa. Because these tests are running in parallel, we believe one byte is corrupting the memory of the other response before we write it to the StreamPipeWriter.

I'm bashing my head against this code trying to figure out how this can happen. I may try writing a test which tries to have two streams writing to the response at the same time, making sure their responses are in order. However, consider this repros once in every 3 hours when running a stress suite, I doubt that will really help. My current plan is to custom build kestrel and add more logging to the ConcurrentPipeWriter.
cc @halter73 @Tratcher

**Comment by jkotalik** [comment]
Copied from https://github.com/dotnet/corefx/issues/40194

**Comment by benaadams** [comment]
Might be unrelated but

`ConcurrentPipeWriter` does await the same `ValueTask` multiple times:
https://github.com/aspnet/AspNetCore/blob/f0029227cf5ed4f13e2b5ce41c44cbfa763f79a5/src/Servers/Kestrel/Core/src/Internal/Infrastructure/PipeWriterHelpers/ConcurrentPipeWriter.cs#L137-L145

It also does `.GetAwaiter().GetResult()` and then returns it for something else to await it:
https://github.com/aspnet/AspNetCore/blob/f0029227cf5ed4f13e2b5ce41c44cbfa763f79a5/src/Servers/Kestrel/Core/src/Internal/Infrastructure/PipeWriterHelpers/ConcurrentPipeWriter.cs#L119-L124

Not sure that's valid?

`Http2OutputProducer` stores a `ValueTask<FlushResult>`
https://github.com/aspnet/AspNetCore/blob/f0029227cf5ed4f13e2b5ce41c44cbfa763f79a5/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L35

Which is created from the `async` ValueTask method `async ValueTask<FlushResult> ProcessDataWrites()`
https://github.com/aspnet/AspNetCore/blob/f0029227cf5ed4f13e2b5ce41c44cbfa763f79a5/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L67

and then returned by `WriteStreamSuffixAsync`
https://github.com/aspnet/AspNetCore/blob/f0029227cf5ed4f13e2b5ce41c44cbfa763f79a5/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L204-L219

Can this method be called once and only once per class and is its result only awaited once?

/cc @halter73 @stephentoub

**Comment by benaadams** [comment]
Added PR for the `Http2OutputProducer` part https://github.com/aspnet/AspNetCore/pull/13398

**Comment by benaadams** [comment]
Added PR for the `ConcurrentPipeWriter` part https://github.com/aspnet/AspNetCore/pull/13399

**Comment by benaadams** [comment]
Also do the `XxxUnsynchronized` methods in `ConcurrentPipeWriter.FlushAsync` need to be in a lock?

**Comment by stephentoub** [comment]
> Not sure that's valid?

It's not.  It's possible depending on the implementation of `_innerPipeWriter.FlushAsync` that it might happen to work, but it's not guaranteed to.

**Comment by benaadams** [comment]
Closed the `ConcurrentPipeWriter` PR as not entirely sure what its doing.

These two identical `_currentFlushTcs != null` tests are a bit weird though. Is it for some data race?

https://github.com/aspnet/AspNetCore/blob/f0029227cf5ed4f13e2b5ce41c44cbfa763f79a5/src/Servers/Kestrel/Core/src/Internal/Infrastructure/PipeWriterHelpers/ConcurrentPipeWriter.cs#L105-L119

**Comment by eiriktsarpalis** [comment]
> There is a test that is running which sends data frames a single byte at a time (Post Duplex Slow)

FWIW I'm able to reproduce data corruptions in absence of "Slow" operations:
```
$ dotnet run -c Release -- -xops 4 8 9 13 14 -cancelRate 0 -serverUri http://localhost:5001

 0: GET                       Success: 15,538,202       Canceled: 0     Fail: 0
 1: GET Partial               Success: 15,538,203       Canceled: 0     Fail: 0
 2: GET Headers               Success: 15,538,186       Canceled: 1     Fail: 17
 3: GET Parameters            Success: 15,538,201       Canceled: 1     Fail: 2
 5: POST                      Success: 15,538,191       Canceled: 0     Fail: 12
 6: POST Multipart Data       Success: 15,538,193       Canceled: 0     Fail: 10
 7: POST Duplex               Success: 15,538,198       Canceled: 0     Fail: 4
10: POST ExpectContinue       Success: 15,538,199       Canceled: 1     Fail: 2
11: HEAD                      Success: 15,538,201       Canceled: 0     Fail: 0
12: PUT                       Success: 15,538,201       Canceled: 0     Fail: 0
```
In this case, I'm seeing corruptions in the `POST`,  `POST Duplex` and `POST Multipart Data`  operations. Note that these operations don't do checksum validations, so I'm rerunning the suite with checksums added to diagnose where the corruption happens. I also want to investigate whether presence of Duplex operations are contributing to the corruptions.

**Comment by eiriktsarpalis** [comment]
FYI https://github.com/dotnet/corefx/issues/40194#issuecomment-527261739

**Comment by Pilchie** [comment]
@jkotalik Should be closed now, right?
