### ISSUE TITLE
Hosting.WindowsServices IHost support is missing

### ISSUE THREAD

**Issue by Tanhe** [aspnet/AspNetCore#13383]
The extension method `RunAsService()` does not exist for the new `IHost` interface.

**Comment by Tratcher** [comment]
IHost support is available in 3.0 as documented here:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.0&tabs=visual-studio
See UseWindowsService().

**Comment by anurse** [comment]
Closing as the question has been answered.
