### ISSUE TITLE
IHubContext AddToGroupAsync Not Working

### ISSUE THREAD

**Issue by HashemGo** [aspnet/AspNetCore#13395]
Hi i created Api For SignalR but AddToGroupAsync Not Add any users ... groups is 0 after AddToGroupAsync

The same code working fine in Hub class

Microsoft.AspNetCore.SignalR.Core 1.1.0

**Comment by BrennanConroy** [comment]
>but AddToGroupAsync Not Add any users

To be clear, `AddToGroupAsync` accepts "ConnectionID" not "User".

Can you show how you're using `IHubContext<THub>.AddToGroupAsync`?

**Comment by mishmish30** [comment]
yes i know that , but i mean User = ConnectionId

**Comment by mishmish30** [comment]
private  IHubContext<FlashGo> _hubContext;
        public CpanelApiController( IHubContext<FlashGo> hubContext)
        {
            _hubContext = hubContext;
        }


        public async Task JoinGroup(string ConnectionId)
        {
                await _hubContext.Groups.AddToGroupAsync(ConnectionId, "Admin");

        }

**Comment by BrennanConroy** [comment]
How are you getting the `ConnectionId` to the controller?

How are you verifying that groups has no connections added to it?

**Comment by mishmish30** [comment]
I have Tow Project ,
first one have base THub and Api Controller

second project connect with the first project after OnConnectedAsync send api ruqest JoinGroup(Context.ConnectionId) for add ConnectionId in agroup

all  that working fine but _hubContext.Groups.AddToGroupAsync not add any ConnectionId in Api Controller , for now SendAsync working fine in ApiController 
but AddToGroupAsync not working

**Comment by HashemGo** [comment]
Hi , this is my test projects
- please change url in project SignalRSide https://localhost:44314 to new url project SignalRApi in all files and class

- run SignalRApi then run SignalRSide
- after SignalRSide connected with FlashGo SignalRApi 
- OnConnectedAsync in FlashSide will send api request with ConnectionId to CpanelApiController
- CpanelApiController has AdminAddApi to AddToGroupAsync
 
i hope this helpful and answer you questions

[SignalRApi.zip](https://github.com/aspnet/AspNetCore/files/3549338/SignalRApi.zip)

**Comment by HashemGo** [comment]
ConnectionId not found in THub1 , so AddToGroupAsync can't add ConnectionId from another THub
sorry about that, and thanks for reply ♥
