### ISSUE TITLE
Cannot bind nullable value FromBody 

### ISSUE THREAD

**Issue by bdiaby** [aspnet/AspNetCore#13412]
This issue is supposed to be fixed but I am still not able to bind nullable values from my .Net Core MVC controller.
this issue #5541 is closed but I still have the same issue

**Comment by pranavkm** [comment]
@bdiaby that's a completely unrelated issue. There's a flag to allow empty bodies in MVC: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.mvcoptions.allowemptyinputinbodymodelbinding?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_MvcOptions_AllowEmptyInputInBodyModelBinding. There's also a separate issue tracking allowing this on a per action basis: https://github.com/aspnet/AspNetCore/issues/6878

**Comment by bdiaby** [comment]
@pranavkm thanks I will delete this one
