### ISSUE TITLE
Incorrect namespace and component content for new Razor Class Library

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#13418]
The namespace of the generated `ExampleJsInterop` class should match the library name, but is instead always `RazorClassLibrary-CSharp`.

Also, the content of *Component1.razor* is always "This Blazor component is defined in the <strong>RazorClassLibrary-CSharp</strong> package." when it should reflect the actually library/package name.

Repro steps:

- Using .NET Core SDK 3.0.100-preview9-013996 or later
- `dotnet new razorclasslibrary -o RazorClassLib1`
- Inspect generated *ExampleJsInterop.cs* and *Component1.razor* files

Actual result:

- Namespace of `ExampleJsInterop` is always `RazorClassLibrary-CSharp`
- Content of `Component1` is always "This Blazor component is defined in the <strong>RazorClassLibrary-CSharp</strong> package."

Expect result:

- Namespace of `ExampleJsInterop` matches the name of the library/packages
- Content of `Component` uses the correct library/package name

**Comment by mkArtakMSFT** [comment]
This has been resolved.
