### ISSUE TITLE
Blazor generated onclick events on loop do not work

### ISSUE THREAD

**Issue by huto1** [aspnet/AspNetCore#13427]
the bellow one works perfectly.

`        <p><button onclick="@(new Action(() => tstmethod("tt")))">test method</button></p>`

 And this one does not work, which is a big issue. If this does not work, there is no way to do any kind of list output.
```
        @for (int i = 0; i < 5; i++)
        {
            <p><button onclick="@(new Action(() => tstmethod(i.ToString())))">test method</button></p>
        }
```

method being used:

```
void tstmethod(string tst1)
    {
        tst = tst1;
    }
```

Is there any way to accomplish this? Or will it only be fixed in the next version?

**Comment by vertonghenb** [comment]
You're not using the correct syntax, mind the "**@**" sign**s**:
```cs
<p><button @onclick="@(_ => tstmethod("tt"))">test method</button></p>
```

**Comment by campersau** [comment]
In addition to @vertonghenb comment you also need to capture the variable inside the loop.

> The necessity to declare a variable inside your loop is just how C# lambdas work - they bind to a variable, not to the value that was in the variable when the lambda was constructed.

https://github.com/aspnet/Blazor/issues/275#issuecomment-373686979

This is documented here: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lambda-expressions

Other issues:
https://github.com/aspnet/AspNetCore/issues/12235
https://github.com/aspnet/AspNetCore/issues/10327
https://github.com/aspnet/AspNetCore/issues/10138
https://github.com/aspnet/AspNetCore/issues/7134
https://github.com/aspnet/Blazor/issues/1562
https://github.com/aspnet/Blazor/issues/1402
https://github.com/aspnet/Blazor/issues/1422
https://github.com/aspnet/Blazor/issues/764
https://github.com/aspnet/Blazor/issues/447
https://github.com/aspnet/Blazor/issues/275

**Comment by huto1** [comment]
@vertonghenb  your solution solved the problem. @vertonghenb yes, we do need to assign the loop value to another variable:
```
 @for (int i = 0; i < 5; i++)
        {
            var a = i;
            <p><button @onclick="@(new Action(() => tstmethod(a.ToString())))">test method</button></p>
        }
```

There was probably some change in the later version, it would be useful if the at sign had some additional coloring to it.

**Comment by vertonghenb** [comment]
@huto1 there is a coloring see the following test:
![coloring](https://user-images.githubusercontent.com/10981553/63654256-60782400-c778-11e9-95e6-13ea4c814dad.gif)

**Comment by huto1** [comment]
@vertonghenb  It used to be green like that, but not anymore.
