### ISSUE TITLE
[Blazor] Cannot bind to  HTML5 <Progress> value or max attributes.

### ISSUE THREAD

**Issue by QadiymStewart** [aspnet/AspNetCore#13429]
Unable to bind a values to the HTML5 Progress element. Value or max attributes specifically.

> Error - 'progressValue' is not a valid value of attribute 'value'.

```cs
@page "/counter"

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
<progress max="100" value="progressValue"></progress>

@code {
    int currentCount = 0;
    int progressValue = 0;

    void IncrementCount()
    {
        currentCount = currentCount + 10;
        progressValue = currentCount;
    }
}
```

Test Repo
https://twinnaz.visualstudio.com/ProgressBug/_git/ProgressBug

**Comment by campersau** [comment]
Try `value="@progressValue"`. Also I needed to reload the project afterwards to make this warning to go away.
![image](https://user-images.githubusercontent.com/4009570/63652163-8217e200-c75d-11e9-809b-d5983df8c38d.png)

**Comment by QadiymStewart** [comment]
thanks

**Comment by QadiymStewart** [comment]
don't know why we need the "@" thought they were getting rid of it

**Comment by campersau** [comment]
Yes, but not everywhere. Only where they can infer the type e.g. for attributes starting with `@` like event handlers `@onclick`, or custom component attributes which are not from type `string`.

**Comment by QadiymStewart** [comment]
Good to know. Thanks
