### ISSUE TITLE
IdentityServer4 AddNativeApp offline_access misconfiguration

### ISSUE THREAD

**Issue by totht91** [aspnet/AspNetCore#13434]
### Describe the bug
Using the new out-of-the-box IdentityServer4 integration, the `AddNativeApp` API call adds the `offline_access` scope but does **not** set the `AllowOfflineAccess` property to `true` on the `IdentityServer4.Models.Client` object. This should be true of the `offline_access` scope is allowed. Without this flag the client cannot get a refresh token.

### Example

```C#
services.AddIdentityServer()
    .AddApiAuthorization<User, MyDbContext>(options =>
    {
        options.Clients.AddNativeApp("xamarin", cfg =>
        {
            var builder = cfg
                .WithScopes("openid", "profile", "myAPI")
                .WithRedirectUri("xamarinformsclients://callback");
        });
    });
```

### Expected behavior
`AddNativeApp` should set the `AllowOfflineAccess` property to `true` by default.

### Workaround with current codebase
Search for the newly added `Client` object from the `ClientCollection` and set the `AllowOfflineAccess` property to `true` by hand.

```C#
options.Clients.AddNativeApp("nativeapp", cfg =>
{
    var builder = cfg
        .WithScopes("openid", "profile", "myAPI")
        .WithRedirectUri("mycallback://callback");
});
options.Clients.Single(c => c.ClientId == "nativeapp").AllowOfflineAccess = true;
```

## Info
* ASP.NET Core 3.0 preview7

**Comment by totht91** [comment]
@blowdart @javiercn Then why is the `offline_access` scope added to the native client's scopes? Also I want to support a xamarin client with this method with refresh token support. Not related to SPAs.

**Comment by blowdart** [comment]
As this is out of scope for our identity service use, closing
