### ISSUE TITLE
aspnet app should provide help for cli argument

### ISSUE THREAD

**Issue by netroby** [aspnet/AspNetCore#13441]
I built an aspnet core app, i wan to know the support cli argument to run my app. but see nothing

```$ ./WebApplication1 --help
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/huzhifeng/tmp/publish
^Cinfo: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...


```

actually, it support some cli argument, like `--urls`

```
 $ ./WebApplication1 --urls http://0.0.0.0:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://0.0.0.0:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/huzhifeng/tmp/publish

```

how could we know the supported argument  ?

**Comment by anurse** [comment]
By default, we register the "Command-Line Configuration Provider" which pulls command-line arguments into the ASP.NET Core configuration system (`IConfiguration` and friends). You can see more information in the docs here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#command-line-configuration-provider

That doc also includes information about how to define your own switches/arguments and map them to config settings.

Closing this as the question has been answered.
