### ISSUE TITLE
Incorrect folder structure when creating a hosted Blazor WebAssembly app in VS

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#13449]
When you create a ASP.NET Core hosted Blazor WebAssembly app in VS you got an extra directory layer that isn't needed or expected. This was tested with 16.3 Preview 3 and .NET Core 3.0 Preview 9.

Repro steps:

- File -> New Project -> Blazor App -> Blazor WebAssembly with "ASP.NET Core hosted" checked

Expected result:

- BlazorApp1
  - Client
  - Server
  - Shared
  - BlazorApp1.sln

Actual result:

- BlazorApp1
  - BlazorApp1
    - Client
    - Server
    - Shared
  - BlazorApp1.sln

**Comment by mkArtakMSFT** [comment]
This is already resolved.
