### ISSUE TITLE
Error start the app.dll

### ISSUE THREAD

**Issue by Pilchie** [aspnet/AspNetCore#13460]
_From @Mhm0ud on Monday, August 26, 2019 8:19:21 AM_

Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/runtime-2.2.1
Operating System: Linux Debian 9 - x64

dotnet --info:

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

$dotnet app.dll
it reduce an error:
 dotnet ./meshop/MEShop.dll

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MEShop.Startup.ConfigureServices(IServiceCollection services) in d:\a\1\s\MEShop\Startup.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MEShop.Program.Main(String[] args) in d:\a\1\s\MEShop\Program.cs:line 17
Aborted

when I download the code to my local machine and start the app, the app works normally, but when start this app on the server, I face the above error.

This app published throw azure pipeline.

I tried to publish the app throw my local machine, and upload to the server, it's also working.

_Copied from original issue: dotnet/core#3252_

**Comment by anurse** [comment]
Closing as the issue has been resolved.
