### ISSUE TITLE
Pass in queue name as HTTP.SYS option to ASP.Net Core HTTP.SYS server.

### ISSUE THREAD

**Issue by bkatms** [aspnet/AspNetCore#13461]
Currently the HTTP.SYS server in ASP.NET Core creates an unnamed queue.

var statusCode = HttpApi.HttpCreateRequestQueue(HttpApi.Version, null, null, 0, out requestQueueHandle);

We will need the ability for an ASP.NET Core service to pass in the name of queue as a parameter on Http.Sys options.

A second HTTP.SYS option would be to have an option to control the behavior of HTTP_CREATE_REQUEST_QUEUE_FLAG_OPEN_EXISTING  with a default of create.

**Comment by bkatms** [comment]
Thanks.  I am not sure what you are saying – are you saying that you are willing to merge #5866 into master deliver this capability?  I have no objection (I looked briefly at the code but I look more closely at it if that is your intent).

The partner would be Office 365, unless you mean something else by that.

Cheers, Brian
[he/him]

**Comment by anurse** [comment]
This is done right, @shirhatti?

**Comment by shirhatti** [comment]
Docs and verification pending. Leaving this open to track that.
I'll close once I've sent a docs PR

**Comment by Tratcher** [comment]
@shirhatti you can use the Accepted label to track that.
