### ISSUE TITLE
Blazor Server-side doesn't start with Windows Authentication on Chrome

### ISSUE THREAD

**Issue by GerardSmit** [aspnet/AspNetCore#13478]
### Describe the bug
The server-side Blazor application doesn't start when the authentication is set to Windows Authentication in Google Chrome. Creating an application without authentication works fine.

### To Reproduce
1. Create a new Blazor server-side application with Windows Authentication
2. Start the application in IIS Express and open the application in Chrome.
3. You'll see the pre-rendered page and in the top-right the username of the current Windows user is shown: `Hello, DOMAIN\user!`.
4. Go to the page 'Counter'.
5. When you try to click the button 'Click me', nothing happens.

### Additional context
I've tested in the following browsers with Windows Authentication enabled:

| Browser | Is working? |
|-------------------|-------------|
| Chrome | No |
| Internet Explorer | Yes<sup>1</sup> |
| Edge | Yes |
| FireFox | Yes |

<sup>1</sup> IE only works with https://github.com/Daddoon/Blazor.Polyfill added.

---

Some points that I found that might be handy:

1. By removing the line `Html.RenderStaticComponentAsync<App>()` in `_Host.cshtml` you'll notice that the page is white. The content that you see is pre-rendered.
2. Chrome and Internet Explorer does authenticate automatically but FireFox and Edge does not  
  (I need to provide my username and password).
3. In Chrome, the WebSocket connection is established:
![image](https://user-images.githubusercontent.com/2109929/63790391-75c88c00-c8f9-11e9-843f-ffde686ea665.png)
   but no data was sent:
![image](https://user-images.githubusercontent.com/2109929/63790426-837e1180-c8f9-11e9-850f-4309c6f0af10.png)
4. In FireFox everything works fine:
![image](https://user-images.githubusercontent.com/2109929/63791492-e5d81180-c8fb-11e9-8b3f-171496b7380c.png)

---

```
> dotnet --info:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07

> Visual Studio:
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.3.0 Preview 2.0

> IIS
IIS Express 10.0.18362.1

> Google Chrome
Version 76.0.3809.132 (Official Build) (64-bit)
```

**Comment by GerardSmit** [comment]
I've checked the console but there is no error:

![image](https://user-images.githubusercontent.com/2109929/63878454-ec34bf00-c9c9-11e9-8788-9810c2e9725c.png)

I cleared my cookies, site cache, local/session storage with no success. I tried the application in Incognito (so extensions wont load) but it still doesn't work. However when I open Chrome in the Guest mode the application works fine:

![image](https://user-images.githubusercontent.com/2109929/63878985-f6a38880-c9ca-11e9-9b49-0b9dfd0e4560.png)

It seems there is something wrong with my account in Chrome, which is weird because it shouldn't affect the application at all.

That being said the issue isn't coming from Blazor. I thought I tried everything before creating this issue but I never expected it to be something like this. I'm sorry for the false report.

**Comment by GerardSmit** [comment]
Alright, found the problem.

After resetting Chrome (removing all settings and extensions) the application works. After re-enabling the extensions the application stopped working. It seems the extension "Tampermonkey" is causing problems, even in Incognito while it doesn't have access to Incognito.

**Comment by GerardSmit** [comment]
Reported in the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=998693

**Comment by mkArtakMSFT** [comment]
Thanks for information, @GerardSmit. Good to know. Hope this will help others in community too.

**Comment by martshep** [comment]
While I understand that this failure is a chrome issue and not a blazor issue, the user experience when this occurs is very confusing. Would it be possible for Blazor to put up a warning when the SignalR connection to the server can't be established or is taking a really long time to establish, similar to the way that it displays an overlay if the connection is lost? 

By the way, there are a few chrome extensions that cause this issue including, Requestly and  Tampermonkey. 

As a workaround for now, it is possible to change the RenderMode to Server to switch off pre-rendering and add something like the following to _Host.cshtml so that at least a user experiencing this issue gets a sensible error message rather than an application that doesn't respond to anything:

    <div id="loading" style="position:absolute; visibility: hidden">
        <p>Error connecting to server....</p>
        <p>NOTE: If you are using Chrome and are seeing this then try a different browser or disable your plugins.</p>
    </div>
    <script type="text/javascript">
    function showLoadingDiv() {
      document.getElementById("loading").style.visibility = "visible";
    }
    setTimeout("showLoadingDiv()", 10000); 
    </script>

    <app>
        @(await Html.RenderComponentAsync<App>(RenderMode.Server))
    </app>

**Comment by GerardSmit** [comment]
Information for the participants: This issue has been fixed in Chrome 79, which is the next version of Chrome which will be stable tomorrow (10 December).
