### ISSUE TITLE
Blazor preview 8 client crashes with target framework .netstandard 2.1

### ISSUE THREAD

**Issue by JvSSD** [aspnet/AspNetCore#13489]
### Describe the bug
The Blazor preview 8 (version 3.0.0-preview8.19405.7) client crashes with target framework .netstandard 2.1 with a System.TypeLoadException: VTable setup of type System.Text.Json.Utf8JsonWriter failed. See the screenshot for additional details from the stacktrace logged by WASM.

I discovered this while updating my Blazor project from preview 6 to preview 8 and then trying to reproduce the crash from a clean Blazor solution.

### To Reproduce
1. Create a new 'Blazor app' project
2. Choose template 'Blazor WebAssembly App' and check 'ASP.NET Core hosted'
3. Edit the solution's client project's .csproj file and set the target framework .netstandard 2.1
4. Rebuild the solution
5. Run the app and open the console to see the error

### Expected behavior
No crash. Same behavior as when target framework .netstandard 2.0 is selected.

### Screenshots
![image](https://user-images.githubusercontent.com/54601698/63807286-afab8980-c91d-11e9-996c-815c28e29823.png)

**Comment by ar0311** [comment]
Mono's WASM implementation only supports netstandard2.0

**Comment by JvSSD** [comment]
Was it just fortuitous that it used to work on netstandard 2.1 with preview 6?

**Comment by shadow-cs** [comment]
See #12568 dotnet/corefx#39767

**Comment by mkArtakMSFT** [comment]
This is now in PR: https://github.com/aspnet/AspNetCore/pull/16808
