### ISSUE TITLE
Retrieve detailed metrics from HTTP.SYS

### ISSUE THREAD

**Issue by bkatms** [aspnet/AspNetCore#13482]
HTTP.SYS provides detailed metrics that are required for successful management of large datacenter scale service implementations.

This is the documentation from HTTP.SYS: 

https://docs.microsoft.com/en-us/windows/win32/api/http/ne-http-http_request_info_type 

Note a newer HttpRequestInfoTypeTcpInfoV1 is coming along which supersedes HttpRequestInfoTypeTcpInfoV0.  

It is acceptable to return the information in a manner that minimizes the memory management issues for managed code.

Some design input:

-	Some of the info will not be present on previous versions of Windows.
-	Some of the info will not be present depending on the transport used. 
o	For example, TCP vs. QUIC, HttpRequestInfoTypeTcpInfoV1 and HttpRequestInfoTypeQuicStats.
-	If you expose the timings you should expose the sizes, they go together.
-	The sizes info has flags and request index, which should be exposed as well.
-	In the variable length arrays (RequestSizing and  RequestTiming) the caller must be prepared the size can be smaller or bigger than what it knows. RequestSizingCount and RequestTimingCount must be obeyed.
-	Even if the index for a given timing or size is present in the array, the value can be zero, as it does not apply to the request. 
o	For example, HttpRequestSizingTypeTlsHandshakeLeg1ClientData is zero HTTP and HttpRequestTimingTypeHttp2StreamStart is 0 for HTTP/1.x.
-	You should not expose HttpRequestInfoTypeSslTokenBinding or HttpRequestInfoTypeSslTokenBindingDraft.
-	You should expose only HttpRequestInfoTypeTcpInfoV1, which includes HttpRequestInfoTypeTcpInfoV0, when it is available.
o	HttpRequestInfoTypeTcpInfoV0 is the foster child for instant legacy.

**Comment by anurse** [comment]
Let's try to prioritize a PR for this ASAP so I can run it through Tactics ASAP.

**Comment by Tratcher** [comment]
Design notes:
- This is a moving target, new extensions are frequently added. There are also undocumented prototype extensions that it would be useful to access for experiments.
- The main units are an enum identifier and a byte blob.
- Expose a new feature interface that allows requesting blobs by enum identifier (int). What about enumerating?
- The request blob is a pinned data buffer, but it gets unpinned before dispatching to the app. Can we safely read data lazily from the buffer after it has been unpinned, or do we need to greedily copy the data first? Elsewhere in the structure there are relative address pointers that don't work well after unpinning. We do store the original pinned address just in case.
