### ISSUE TITLE
Merge aspnet/Razor.VSCode into AspNetCore-Tooling

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#13494]
aspnet/Razor.VSCode is its own repo with its own build infrastructure. We need to merge that into our AspNetCore-Tooling repo.

**Comment by NTaylorMullen** [comment]
This is 97% done. @dougbu and I are meeting on Monday to complete the migration (ensure assets we build are published to blob feeds).

**Comment by NTaylorMullen** [comment]
Done, 💪

**Comment by rynowak** [comment]
![image](https://user-images.githubusercontent.com/1430011/65641582-069a9200-dfa2-11e9-977a-15b0d197d375.png)
