### ISSUE TITLE
Custom policy evaluator to enforce multiple authentication schemes

### ISSUE THREAD

**Issue by fruitraccoon** [aspnet/AspNetCore#13498]
### Is your feature request related to a problem? Please describe.

I have recently had a situation where I had set up multiple Authorization Policies, and they were being applied to Controllers using a Convention.  Some policies had multiple Authentication Schemes added.  While the default behaviour is that these schemes are OR-ed together (ie. only one is needed to "pass"), the behaviour I was after was that they be AND-ed (ie. all are needed to "pass").  This is the same situation as decribed in these previously raised issues: #6733, #5154

After digging into the code, I found that this OR logic is contained within the [`PolicyEvaluator`](https://github.com/aspnet/AspNetCore/blob/16a47948f80fede807fabe3c291d793590e8fd17/src/Security/Authorization/Policy/src/PolicyEvaluator.cs#L38-L51).  The `AuthorizeFilter` gets an instance of the `IPolicyEvaluator` [by service locating it within `OnAuthorizationAsync`](https://github.com/aspnet/AspNetCore/blob/f45250ce5e423dad083fe99967a4d65782c5301e/src/Mvc/Mvc.Core/src/Authorization/AuthorizeFilter.cs#L186).

Basically, For _some_ policies, I wanted to use my own `IPolicyEvaluator`.

Once my custom evaluator was created, the options for using it that I could think of were:

1. Register it with the DI container.  As all `AuthorizeFilter`s would use the same evaluator, I'd have to make it handle ALL the various different ways I wanted my various Policies to work.
2. Create my own `AuthorizeFilter`s and override which evaluator they use (which would then allow me to have multiple simpler `IPolicyEvaluator`s).  However `AuthorizeFilter` is currently not friendly to override just the evaluator it uses, and would require copy/pasting a large amount of its logic that I didn't want to change.

I wasn't keen on either of these approaches. :)

### Describe the solution you'd like

Below are the possible enhancements that I thought might be useful to others trying to do what I was trying to do (ordered by simplest first).

#### Option 1:

Move location of `IPolicyEvaluator` resolution in `AuthorizeFilter` to a protected virtual method so that it can be more easily overridden.

#### Option 2:

Option 1 +
Add a new constructor to `AuthorizeFilter` that accepts an `IPolicyEvaluator`. The explicit `IPolicyEvaluator` would override using the service location.

#### Option 3:

Option 2 +
Add a new function to `AuthorizationPolicyBuilder` to allow an `IPolicyEvaluator` to be set. The `AuthorizationPolicy` would expose the `IPolicyEvaluator` as a readonly property. The resolution of `IPolicyEvaluator` in `AuthorizeFilter` would then be:
- Use the explicitly defined one from the constructor (if set)
- Use the policy's one (if set)
- Use service location to get the default one

**Would any/all of these options be viable for inclusion in AspNetCore?**  (Option 3 is mostly a nice-to-have, but I think it makes sense to me that when I define a policy, I can also define how that policy should be evaluated)

### Additional context

In my situation, in the end I decided that the solutions I could think of were not ideal.  So I updated the policies to require a unique claim from each relevant scheme (luckily I was able to be in control of the contained claims).  I then just had to deal with the error being a 403 rather than a 401.

**Comment by blowdart** [comment]
@HaoK thoughts please

**Comment by HaoK** [comment]
Authorization and Authentication are two different things, authentication is what determines what user is passed into the authorization apis.  If you want to enforce logic where multiple authentication schemes exist, you can do that explicitly as well, but you would need to represent them like requirements and have an authorization handler enforce that, the build in authentication schemes logic is doing what it's expected to do which is authenticate against each scheme and merge them into a single claims principal.

You can write custom RequireSchemeRequirement and have policies which require whatever schemes you desire, and have a RequireSchemeHandler that calls AuthenticateAsync with the required scheme for that policy and have it fail if authentication fails.

**Comment by fruitraccoon** [comment]
Thanks for your thoughts @HaoK.  I think I see what you're saying, and looking again I certainly could enforce that multiple schemes had been authenticated using a custom Requirement.

However, due to the logic within [`PolicyEvaluator`](https://github.com/aspnet/AspNetCore/blob/16a47948f80fede807fabe3c291d793590e8fd17/src/Security/Authorization/Policy/src/PolicyEvaluator.cs#L91-L93) and [`AuthorizeFilter`](https://github.com/aspnet/AspNetCore/blob/f45250ce5e423dad083fe99967a4d65782c5301e/src/Mvc/Mvc.Core/src/Authorization/AuthorizeFilter.cs#L196-L205), using a Requirement will seemingly always result in a `ForbidResult` (403) when it is not satisfied.  I was wanting to issue a `ChallengeResult` (401).

The reason for wanting it this way is because I consider it to be an Authentication failure, not an Authorization failure, when a required scheme is missing (as we don't fully know who the client is).  Effectively, it's fine for the client to try again if they include the appropriate authentication details.  As I understand it [a 403 is more like a "I know who you are but go away unless you get an admin to give you more permissions")](http://www.dirv.me/blog/2011/07/18/understanding-403-forbidden/index.html).

I thought that the most appropriate way to get this to happen would be to have my own custom PolicyEvaluator inheriting from the default `PolicyEvaluator`, overriding the `AuthenticateAsync` method to return `AuthenticateResult.NoResult` when any schemes were missing.  This would then cause the default `AuthorizeFilter` to return a `ChallengeResult`.  So it then just became a matter of getting the system to use my custom PolicyEvaluator for the appropriate policies.

Please let me know if anything above doesn't make sense or needs more explanation.

**Comment by HaoK** [comment]
Sure you can do something like that in the authentication layer by writing a custom virtual/composite scheme by deriving from AuthenticationHandler and implementing authenticate to only return a principal composed of the required other schemes.  That should result in a challenge result when this schemes fails to authenticate (whenever the other underlying schemes are not found)

**Comment by fruitraccoon** [comment]
I hadn't thought to create nested Schemes like that - it sounds like an idea that should work well.  I'll give it a try when I next get a chance. Thanks very much @HaoK!

As it should give me the result that I'm after, and should also be relatively straight-forward for developers coming after me to understand, I'll close this issue.
