### ISSUE TITLE
RenderTreeFrame.AttributeEventHandlerId type mismatch between reference and published assemblies

### ISSUE THREAD

**Issue by sanosdole** [aspnet/AspNetCore#13504]
I am not sure if this is a bug or just a lack of understanding on my part.
It seems like the reference assemblies used during compilation have different type information compared to the real assemblies being deployed when publishing the dotnet app.

I could attempt to create a small reproduction sample, but using ILSpy it was quite obvious.

### Describe the bug

When publishing a `netcoreapp3.0` project as self-contained and running it through the hosting API it throws a `MethodNotFoundException` at runtime when the JIT attempts to compile a method using `Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame.AttributeEventHandlerId`.

During debugging it was clear that the type of the Field was `ulong` instead of `int` (which was shown from metadata by visual studio code).

After some attempts I simply replaced the `C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.0.0-preview8.19405.7\ref\netcoreapp3.0\Microsoft.AspNetCore.Components.dll` with the version from `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0-preview8.19405.7` and it worked.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.100-preview8-013656'
2. Use IlSpy to view the type information of `Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame.AttributeEventHandlerId` from the mentioned assemblies.

=> They have different values

### Expected behavior
Reference Assemblies provide the same Type Information as the ones used when publishing the project.

### Screenshots
![AssemblyMismatch](https://user-images.githubusercontent.com/477101/63844048-bff84e80-c987-11e9-88ba-23e09770ee3e.png)

### Additional context

This happend during prototyping an open source project for hosting .Net core inside node.
It was found while hosting a Blazor App in an Electron Renderer Process.
If it helps access to the Repository on GitHub could be granted.

The output of `dotnet --info`:
```
.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/AspNetCore/commit/c3af33a023663fe515f8b8942eab67d9e0442ff9
