### ISSUE TITLE
Microsoft.DotNet.Arcade.Sdk not found

### ISSUE THREAD

**Issue by zeinali0** [aspnet/AspNetCore#13506]
### Describe the bug
Hi
I clone the source code and try to build it with build.cmd command and i get this error
```
F:\Zeinali\AspNetCoreSource\AspNetCore\Directory.Build.props(27,3): error : F:\Zeinali\AspNetCoreSource\AspNetCore\.dot
net\sdk\3.0.100-preview8-013656\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk not found. Check that a recent enough .NET Core SD
K is installed and/or increase the version specified in global.json.
F:\Zeinali\AspNetCoreSource\AspNetCore\Directory.Build.props(27,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sd
k' specified could not be found. [F:\Zeinali\AspNetCoreSource\AspNetCore\src\SignalR\clients\csharp\Client.Core\ref\Mic
rosoft.AspNetCore.SignalR.Client.Core.csproj]
```
i tried download different version of .net core 3 but there is no `Microsoft.DotNet.Arcade.Sdk ` with them. 
how can we get arcade sdk?
is it only install with visual studio 2019? (i didn't install visual studio 2019 i tried to use `build.cmd`)
is there any way to build without installing visual studio 2019?

### To Reproduce
1. clone source code
2. try to build with `build.cmd` (without installing visual studio 2019)
3. See error

### Additional context
`dotnet --info`
<details>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

**Comment by zeinali0** [comment]
I remove all files and clone the source again (it's using .net 5 now) and change the sdk to `3.0.100-preview8-013656` and build SignalR solution successfully with `build.cmd` but when I open solution in Visual Studio Code the `OmniSharp `fail to load project with same error ( `Microsoft.DotNet.Arcade.Sdk` not found).

**Comment by zeinali0** [comment]
Actually as i said i **didn't install** **Visual Studio 2019** i tried to use visual studio code.
and i also asked is visual studio 2019 preview required?
My problem is that OmniSharp in **Visual Studio Code** cant find Arcade SDK so it can't load project.

**Comment by dougbu** [comment]
@zeinali0 please have a look at https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md and make sure you're following all of the steps. For example, are you executing `. .\activate.ps1` or `source ./activate.sh` and `.\restore.cmd` or `./restore.sh` before opening VS Code?

**Comment by zeinali0** [comment]
Yes I did them as same as documentation. it seems OmniSharp try to use Visual Studio MsBuild instance or Use its own instance. so if Visual Studio 2019 not installed on system the Visual Studio Code wouldn't work too.

**OmniSharp Logs**
```
Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.5.27130.2010 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 16.0 - "C:\Users\ALI\.vscode\extensions\ms-vscode.csharp-1.21.1\.omnisharp\1.34.2\.msbuild\Current\Bin"
```

**Comment by dougbu** [comment]
Hmm, I'm wondering if the problem is something else entirely. Does your NuGet.config file contain the package sources listed in https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md#how-to-get-daily-builds-of-aspnet-core ?

**Comment by dougbu** [comment]
FYI the Arcade SDK is found in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

**Comment by zeinali0** [comment]
This is my NuGet.config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="aspnet-blazor" value="https://dotnetfeed.blob.core.windows.net/aspnet-blazor/index.json" />
    <add key="aspnet-extensions" value="https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json" />
    <add key="aspnet-entityframeworkcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json" />
    <add key="aspnet-aspnetcore-tooling" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json" />
    <add key="grpc-nuget-dev" value="https://grpc.jfrog.io/grpc/api/nuget/v3/grpc-nuget-dev" />
    <add key="roslyn" value="https://dotnet.myget.org/F/roslyn/api/v3/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnetcore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
    <add key="aspnetcore-tools" value="https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json" />
    <add key="roslyn-tools" value="https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json" />
  </packageSources>
</configuration>
```

And these are what i found in `.dotnet\sdk\3.0.100-preview8-013656\Sdks` folder
![image](https://user-images.githubusercontent.com/28354390/64063095-0e665100-cc05-11e9-8d54-fb32b86ecac0.png)
