### ISSUE TITLE
ANCM : Two instances of same application started simultaneously

### ISSUE THREAD

**Issue by yashwanthreddyg** [aspnet/AspNetCore#13517]
### To Reproduce
Unable to reproduce reliably

We have an aspnetcore app of which two instances are being started simultaneously. This is not happening always though and I'm yet to reproduce this.

### Screenshots
![image](https://user-images.githubusercontent.com/7929962/63871771-20b07700-c9da-11e9-8073-1f430e480792.png)

### Additional context
These are the lines in the event details:
Application 'MACHINE/WEBROOT/APPHOST/MYWEBSITE/MYAPP' started process '3512' successfully and is listening on port '40907'.
Application 'MACHINE/WEBROOT/APPHOST/MYWEBSITE/MYAPP' started process '9740' successfully and is listening on port '19189'.

The process 3512 was seemingly shutdown immediately in a second at 3:00:03 AM
Sent shutdown HTTP message to process '3512' and received http status '202'.

Is this behaviour expected?

**Comment by shirhatti** [comment]
I believe this is expected behavior observed when `web.config` is modified shortly after publishing and/or starting your site. The second process is started and the first is allowed a period to gracefully drain pending requests.

Do you know if you're modifying your web.config as described here?

**Comment by yashwanthreddyg** [comment]
@shirhatti While we modify the web.config from time to time, no modification happened when the incident occurred.

**Comment by Rick-Anderson** [comment]
@yashwanthreddyg do you have more information on this?

**Comment by yashwanthreddyg** [comment]
We are unable to reproduce this currently. I'm closing the issue.
