### ISSUE TITLE
Blazor MissingMethodException in published/release mode

### ISSUE THREAD

**Issue by lertoo** [aspnet/AspNetCore#13529]
.NET 3.0 Preview 8 for Blazor (Client) aap.

### To Reproduce
1. Use any of the following method in code:
- System.Net.Http.HttpClient.GetByteArrayAsync()
- List<T>.ForEach()
- Enum.GetValues()
2. Publish the Blazor app then run it. Calling those methods cause MissingMethodException.

### Expected behavior
It should be working as in debug mode.

### Additional context
It seems that Blazor release runtime (wasm) miss some .NET Standard methods.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not an area we control.
If you still have this problem, feel free to report it on the https://github.com/mono/mono repo.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#16565
