### ISSUE TITLE
Program structure on Visual Studio 2019 ( ASP Core 2.1)

### ISSUE THREAD

**Issue by simon617** [aspnet/AspNetCore#13539]
I try to move the code originally designed on VS 2017 into VS 2019. However, the structure is completely different. Any hint to embedded the original code into VS 2019 ?

Code in 2017 :
```
        public static void Main(string[] args)
        {
            **var host = BuildWebHost(args);**

            using (var scope = host.Services.CreateScope())
            {
                var services = scope.ServiceProvider;
                try
                {
                    var context = services.GetRequiredService<DigitalLibraryContext>();
                    DbInitializer.Initialize(context);
                }
                catch (Exception ex)
                {
                    var logger = services.GetRequiredService<ILogger<Program>>();
                    logger.LogError(ex, "An error occurred while seeding the database.");
                }
            }

            host.Run();
        }
```
initial code in 2019 
```
        public static void Main(string[] args)
        {
            **CreateWebHostBuilder(args).Build().Run();**
        }
```

**Comment by Tratcher** [comment]
This isn't about VS 2017 versus 2019, it's about older and newer versions of the templates for different versions of ASP.NET Core.

Here's the full code for the 2.2 templates:
https://github.com/aspnet/AspNetCore/blob/2217be28261ee2df07dd5d293d92a05a458f5a6b/src/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/content/EmptyWeb-CSharp/Program.cs#L13-L23

The only difference between CreateWebHostBuilder and BuildWebHost is that the call to `Build()` moved from inside BuildWebHost to outside CreateWebHostBuilder. So `var host = BuildWebHost(args);` becomes `var host = CreateWebHostBuilder(args).Build()`.

**Comment by simon617** [comment]
Thx, but it seems that some method doesn't support... as see in the attachment

![program](https://user-images.githubusercontent.com/42394945/63986825-48056200-cb08-11e9-9f26-6111dc099283.png)

**Comment by Tratcher** [comment]
`var host = CreateWebHostBuilder(args).Build()`

**Comment by simon617** [comment]
Thx for your prompt reply, it works perfect now.
