### ISSUE TITLE
EF Health Check does not honor the failureStatus 

### ISSUE THREAD

**Issue by tomkerkhove** [aspnet/AspNetCore#13538]
EF Health Check will always return `Unhealthy` regardless of the configured `failureStatus`.

https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/HealthChecks.EntityFrameworkCore/src/DbContextHealthCheck.cs#L53

### Describe the solution you'd like
Return the configured `failureStatus` rather than always `Unhealthy`

### Additional context
This issue is a follow-up from https://github.com/aspnet/Extensions/issues/2212.

**Comment by tomkerkhove** [comment]
Paging @rynowak as FYI.

Happy to give this a try if you want.

**Comment by rynowak** [comment]
Yeah that would be great!

**Comment by rynowak** [comment]
Thanks @tomkerkhove

**Comment by tomkerkhove** [comment]
My pleasure Ryan!
