### ISSUE TITLE
Maybe PhysicalFile will be memory leak in dotnet core 3.0 preview 8

### ISSUE THREAD

**Issue by lindexi** [aspnet/AspNetCore#13535]
### Describe the bug

Using the PhysicalFile method to return IActionResult that will never gc the memory.

### To Reproduce
1. Using this version of ASP.NET Core  3.0.0-preview8-28405-07
2. Run this code https://github.com/lindexi/lindexi_gd/tree/dev/Gaaweeealjrdwrebiny in project mode
3. Using the postman to get the http://localhost:5000/api/Resource

Then you can see the Visual Studio debug windows show the memory number.

The core code is 

```
    [Route("api/[controller]")]
    [ApiController]
    public class ResourceController : ControllerBase
    {
        [HttpGet]
        public IActionResult Get()
        {
            var folder = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var file = Path.Combine(folder, "big file");
            const string mime = "application/octet-stream";

            return PhysicalFile(file, mime);
        }
    }
```

### Expected behavior

Seem the PhysicalFile will be memory leak

### Screenshots

![图片](https://user-images.githubusercontent.com/16054566/63905494-06f94900-ca47-11e9-8288-2f455ec3242a.png)

### Additional context

```
.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by RemiBou** [comment]
Did you try to force a gc (I think there is a button in vs) ? Memory will only be released on garbage collector execution which happens only for some condition (memory pressure mostly). If there is no gc executed you will not see any drop in memory.

**Comment by lindexi** [comment]
@RemiBou I wait for 10 minutes.

**Comment by davidfowl** [comment]
Waiting won't matter if you haven't hit the memory threshold. The GC doesn't just run on a timer. How many requests did you try sending and how big is the file (though it shouldn't ever really be all in memory at once)

**Comment by lindexi** [comment]
@davidfowl Could you help me to create a new application and use PhysicalFile method in your computer and do many requests? 

I want to know whether it can find in other computer.

**Comment by piratetiger** [comment]
It seems I have the same issue.
I am using Ubuntu 18.04 with docker mcr.microsoft.com/dotnet/core/aspnet:2.2
The VIRT in htop continue growing when calling PhysicalFile.
