### ISSUE TITLE
Build looking for Core Preview8 since VS update

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#13531]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/694142/build-looking-for-core-preview8-since-vs-update.html)._

---
[regression] [worked-in:16.3.0 Preview 1.0]
After i update to VS2019 16.3 Preview2 I cannot build my Asp.Net/Blazor solution anymore.

We are on Core Preview 7 SDK (also the NuGet packages). We have a global.json which also specifies the Preview 7.

Before the VS update it all worked.

```
2&gt;obj\Debug\netstandard2.0\RazorDeclaration\Pages\Api.razor.g.cs(56,38,56,53): error CS0234: The type or namespace name 'LayoutAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Components'...
...
3&gt;------ Rebuild All started: Project: xxxxxxxxx, Configuration: Debug Any CPU ------
3&gt;C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets(54,5):...
```

---
#### dominik.gallus on 8/14/2019, 05:53 AM: 

<p>Ok. I figured that the Preview 2.0 also automatically installed Core Preview 8 which replace the Preview 7 on my machine.</p><p>Which is a bad thing because now i also have to update all used NuGet packages to Preview 8 and then update all my CI machines to Preview 8 yada yada yada.</p><p>I don't think this is a good way to do it.</p>

#### Visual Studio Feedback System on 8/15/2019, 00:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/16/2019, 01:44 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is because VS 16.3 Preview 2 comes with .Net Core 3.0 Preview 8 SDK as part of it. Even when you pin the version in global.json, that pins only the SDK, yet the runtime rolls forward.
To make sure you keep the runtime you were targeting you can set the `RollFoward` property in your project file as follows:

```
<RollForward>false</RollForward>
```
