### ISSUE TITLE
Endpoints equivalent of RespectBrowserAcceptHeader

### ISSUE THREAD

**Issue by helloserve** [aspnet/AspNetCore#13547]
I was reading up on formatters, and while for 2.2 and before it's well defined in the documentation, what is the equivalent using endpoints to do this:

```
services.AddMvc(options =>
{
    options.RespectBrowserAcceptHeader = true; // false by default
});
```

I can't use `[Produces]` since my API may not be opinionated on this - the client should decide.

I mean, we now have 

```
app.UseEndpoints(config =>
{
    config.MapControllers();
});
```

I can't find any `IEndpointRouteBuilder` extension method that provides me the ability to set that flag. Or, should we still use `app.UseMvc(..)` in this case? I'm building a pure API, no views. So I would have expected the `MapControllers()` extension to have this ability.

**Comment by khellang** [comment]
I don't think anything needs to change here. `app.UseEndpoints(c => c.MapControllers())` is equivalent to `app.UseMvc()` from before. The options you're talking about should still be configured when doing `services.AddMvc()`.

**Comment by helloserve** [comment]
Oh dear. I got the services and middleware mixed up. Sorry for wasting your time.
