### ISSUE TITLE
Razor component - unclear exceptions when RenderFragment property isn't named ChildContent

### ISSUE THREAD

**Issue by mv10-work** [aspnet/AspNetCore#13543]
Changing this issue to the following:

Apparently Razor components with a `[Parameter] RenderFragment` property only allows `ChildContent` as the property name. While that odd decision probably deserves tracking until it's fixed (I can't recall ever seeing such a thing in .NET over the past 20 years), I changed this issue because the exceptions that result don't give any indication of the real problem.

I also opened a documentation issue, I found [this](https://github.com/aspnet/Blazor/issues/1378#issuecomment-417904030) which purports to explain the limitation, but the redirect to the official doc site no longer mentions the requirement.

Original issue:

After renaming a `[Parameter]` in a Razor component, the code builds properly but exceptions are logged at runtime referencing to the old property name. Surprisingly, the errors persist even after closing VS, deleting the obj and bin folders, and clearing the browser cache. This is in a Blazor server-side app. It happens under debug or stand-alone (including fully stand-alone, VS not running).

The rename was with Ctrl+R Ctrl+R which in general seems a little flaky in .razor files. I saw this several days ago with another component, same scenario, Ctrl+R Ctrl+R rename of a `[Parameter]` property, and in that case deleting the .razor file and re-creating it fixed it. Surprisingly, this time even that does not work. But that makes me suspect it's specific to `[Parameter]`.

After removing bin, obj, and browser cache, the solution builds normally, but at runtime there are exceptions like this in the log, where `ChildContent` is the old name -- that property was renamed to `HeaderControls`. I did run the solution multiple times prior to renaming the property.

> Microsoft.AspNetCore.Components.Web.Rendering.RemoteRenderer: Warning: Unhandled exception rendering component: Object of type 'PortalMockup2019Q3.Shared.AppModuleHeader' does not have a property matching the name 'ChildContent'.

This error is logged further down, which is the reason I also tried clearing the browser cache, wondering if the old reference was somehow coming from the client side. I was in "wild guess" territory by that point.

> Microsoft.AspNetCore.Components.Server.ComponentHub: Warning: Unhandled exception in circuit xxxxxxx

> System.InvalidOperationException: Object of type 'PortalMockup2019Q3.Shared.AppModuleHeader' does not have a property matching the name 'ChildContent'.

The AppModuleHeader.razor component with the renamed property is very simple:
```razor
<div class="...">
    <div class="row">
        <div class="col ...">
            <span class="...">@Title</span> @HeaderControls
        </div>
        <div class="col-auto">
            <img ... />
        </div>
    </div>
</div>

@code {
    [Parameter]
    public string Title { get; set; }

    [Parameter]
    public RenderFragment HeaderControls { get; set; }
}
```

And here's a component using it: 
```razor
<AppModuleHeader Title="Test" >
    <Header />
</AppModuleHeader>
```

I also tried replacing `<Header />` with the straight HTML markup, guessing maybe the parent (consuming) component had to change to be recompiled -- which wouldn't really make sense given I deleted bin/obj -- but that also had no effect.

Header.razor is just a couple of placeholder buttons for now:
```razor
<span>
    <button class="btn btn-light">Import Excel</button>
    <button class="btn btn-light">Export Excel</button>
</span>
```

The fact that it survives removal of the bin and obj folders is very puzzling to me. I checked the .g.cs files and they're correct (unsurprising since it builds correctly). If I rename `HeaderControls` back to `ChildContent` the errors stop after a simple rebuild (no bin/obj/cache deletion necessary). 

Apparently there are compiled or parsed bits cached elsewhere... but where?

I'm using VS 2019 16.3.0 Preview 2 and dotnet --info yields the following (with 2.x stuff removed). Yes, Win7, the Corporate Overlords are cruel and uncaring.

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mv10-work** [comment]
Turns out it isn't Ctrl+R renaming. Changing the property name in both places one by one also has the same effect.

**Comment by mv10-work** [comment]
#1378 ... egads, seriously? Forcing a property name?

This secret-handshake "by convention" stuff is out of control.

**Comment by mv10-work** [comment]
Actually, I'll reopen this to change the title to propose that the exceptions do not adequately describe the problem.

**Comment by SteveSandersonMS** [comment]
You're not required to use the name `ChildContent`. You can have templated parameters with any name, and doing so lets callers use that name when supplying values, e.g.:

```razor
<MyComponent>
    <MyCustomTemplateParameterName>... some markup ...</MyCustomTemplateParameterName>.
</MyComponent>
```

What's special about the name `ChildContent` is that, if you use that name, then callers can optionally omit the wrapper. That is, they *could* call your component like this:

```razor
<MyComponent>
    <ChildContent>... some markup ...</ChildContent>.
</MyComponent>
```

... or they can omit it, with this shorthand:

```razor
<MyComponent>
    ... some markup ...
</MyComponent>
```

In order for the compiler to allow this latter syntax with no wrapper, there has to be some indication about which of your parameters that markup should map to. That's why there has to be some built-in recognized name for this "default" content, for which we've chosen the name `ChildContent`. If you don't want to have a default content parameter, just avoid declaring a parameter named `ChildContent` and use any other name instead.

Hope that makes sense!
