### ISSUE TITLE
Blazor routing @virtpage "{page:int}"

### ISSUE THREAD

**Issue by ichensky** [aspnet/AspNetCore#13544]
Now in blazor for routing used attribute `@page "/path/next/{page:int}"`
which takes as a parameter full path of page: `"/path/next/{page:int}"`. 

It would be nice to have a similar attribute `@virtpage "/{page:int}"`
which just takes as a parameter last changeable part of the url
and another data for mapping to the url `"/path/next/"` 
will be taken from the virtual directory path.

This attribute will simplify scenario when we have several pages: 
```
.
├── Admin
│   ├── Admin.razor
│   └── Content
│       └── Category
│           ├── View.razor     |  @virtpage "/{id}"     |  @page "/admin/category/view/{id}
│           └── List.razor     |  @virtpage             |  @page "/admin/category/list
├── Counter.razor              |  @virtpage             |  @page "/counter"
├── Error.razor                |  @virtpath             |  @page "/error"
├── FetchData.razor            |  @virtpage             |  @page "/FetchData"
└── Index.razor
```
and just want that routing of pages will be mapped directly to the *razor files in directories.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ichensky.
We plan to handle this as part of https://github.com/aspnet/AspNetCore/issues/8787
