### ISSUE TITLE
NuGet package source code URLs should be updated to point to non-archived repo

### ISSUE THREAD

**Issue by IanKemp** [aspnet/AspNetCore#13540]
E.g. https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting.Abstractions/ - points to archived https://github.com/aspnet/Hosting/tree/0724e6cde1149ee1a19bfec9c13a2c9327b71213 but should actually point to https://github.com/aspnet/AspNetCore/tree/0724e6cde1149ee1a19bfec9c13a2c9327b71213

**Comment by pranavkm** [comment]
@IanKemp thanks for the issue report. While the state of things may not be ideal,

a) the package does correctly point to commit \ repo that it was built
b) archived repos point back to the current set of active repos - `aspnet/AspNetCore` and `aspnet/Extensions`
c) it will be incredibly onerous to manually update the metadata for 100+ packages. In particular considering there's yet another planned move: https://github.com/dotnet/announcements/issues/119.

I'm closing this as won't fix.
