### ISSUE TITLE
ASP.CoreApp / Blazor Crash on OnAfterRenderAsync()

### ISSUE THREAD

**Issue by oiBio** [aspnet/AspNetCore#13554]
### Describe the bug
I tried to override the OnAfterRenderAsync() methode in one of my pages and tried to call the `await base.OnAfterRenderAsync()`
Unfortunatly i forgot the `base.` and since then every time i call this page the i got an 'Access violation' and the program stopped completely. 
The first time i encoutered this problem, my whole VS stopped working and i could not reopen my project. I restarted the computer and deleted the bin / obj-folders - then it worked again.

```
Das Programm "[7944] Artemis.WebUI.exe: Programmablaufverfolgung" wurde mit Code 0 (0x0) beendet.
Das Programm "[7944] Artemis.WebUI.exe" wurde mit Code -1073741819 (0xc0000005) 'Access violation' beendet.
```

### To Reproduce
1. Using this version of ASP.NET Core 'SDK 3.0.100-preview8-013656' and the latest Preview of VS 
2. Run this code / override any page with this 
```
        protected override async Task OnAfterRenderAsync()
        {
            await OnAfterRenderAsync();
        }
```
3. See error when call the page

### Expected behavior
Maybe a "normal" exception with some more details why it crashed...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @oiBio.
Given this is caused by a wrong code, we don't think there is any action here for us.
