### ISSUE TITLE
Unable to start Kestrel - Unable to configure HTTPS endpoint

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#13565]
_From @kofifus on Wednesday, August 28, 2019 3:24:55 AM_

When starting my deployment server (as a windows service using RunAsCustomService) I get:

> Unable to start Kestrel.
> System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
> To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.

I tried the following:
- used certmgr to remove all localhost certs
- dotnet dev-certs https --clean
- dotnet dev-certs https --trust
- dotnet dev-certs https --check

I get "A valid certificate was found."

Still the error is there and the server service does not start.

Any ideas how to solve this ?

_Copied from original issue: dotnet/core#3267_

**Comment by Tratcher** [comment]
The dev certificate is only available for the current active user. Windows Services run as a different user and the development certificate is not supported in that environment. You'll need to provide your own certificate via code or config.

**Comment by jkotalik** [comment]
@kofifus did that fix your issue?

**Comment by kofifus** [comment]
No, but I ended up getting Apache to forward https to kestrel http which works. I guess this can be closed thanks.

**Comment by Shizzlak** [comment]
@Tratcher I know this issue is closed but would you be able to give an example of how to create the certificate in code or is it something I can easily find online?

**Comment by Tratcher** [comment]
Here's how we create the dev cert:
https://github.com/aspnet/AspNetCore/blob/87bd1bec5b65b3dd9dbdbb5a9906486840d4d0cb/src/Shared/CertificateGeneration/CertificateManager.cs#L180
