### ISSUE TITLE
Increase concurrent requests from HttpSys

### ISSUE THREAD

**Issue by tornie2** [aspnet/AspNetCore#13575]
There obviously is a limit of how many concurrent requests HttpSys will send in to the pipeline. However we have not been able to find and increase this limit.

The documentation appears very sketchy on this. We have tried adjusting MaxAccepts, but it does not appear to have any effect.

            _host = new WebHostBuilder()
                .UseHttpSys(options =>
                {
                    options.Authentication.Schemes = AuthenticationSchemes.NTLM | AuthenticationSchemes.Negotiate;
                    options.Authentication.AllowAnonymous = true;
                    options.MaxConnections = -1;
                    options.MaxAccepts = 200;
                })

On my developer machine it looks like the limit is 28 concurrent requests. How can we increase that?

**Comment by Tratcher** [comment]
No, there's not a concurrent request limit. MaxAccepts deals with how many threads are dedicated to pulling requests from Http.Sys and dispatching them to Asp.Net, but the requests are processed asynchronously once dispatched. MaxConnections is the only other limit.

How did you observe your 28 figure? How are you generating load on the client, and with what client?

**Comment by tornie2** [comment]
> the requests are processed asynchronously once dispatched.

Ok. So I have 200 threads pulling requests of the request queue. How is the actual work started then? Is that ThreadPool.QueueUserWorkItem(request) ?

> How are you generating load on the client, and with what client?

Well in production, we have all kinds of clients, From Excel and SAS scripts to different client systems in C#, C++, Python or Java, I believe we even have a few clients in COBOL :-)

> How did you observe your 28 figure?

That was observed in our test-system, I wrote a small C# program which submitted a few hundred requests to the service in less than a millilsecond; Each of them takes about 10 seconds to process. I could see that after the service had started processing 28 requests it did not start processing new ones.

Anyway from you description it sounds like http.sys is not my limitation. We should be able to start plenty of concurrent requests.  Could be our pool of SQL-Connections or another ressource is exhausted.

Before you close this thread, I would appreciate if you could elaborate on how requests are processed asynchronously?

My original confusion about limit on concurrent requests was nicely answered. Thanks

**Comment by Tratcher** [comment]
200 is likely overkill for MaxAccepts. 3-5 per CPU is usually adequate.

> How is the actual work started then? Is that ThreadPool.QueueUserWorkItem(request) 

Yes.

FYI the C# client (HttpClient or HttpWebRequest) does have concurrent request limits that you have to disable.

> Each of them takes about 10 seconds to process.

That's pretty expensive. Are they ever blocked synchronously during this time? If so your real bottleneck might be threadpool starvation. If you block existing threads no more work can be scheduled, and new threads are injected slowly.

**Comment by tornie2** [comment]
> 200 is likely overkill for MaxAccepts. 3-5 per CPU is usually adequate.

Yes got it. I thought it was concurrent requests. You could consider improving your [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.httpsysoptions.maxaccepts?view=aspnetcore-2.2). It is a little sketchy....

> FYI the C# client (HttpClient or HttpWebRequest) does have concurrent request limits that you have to disable.

We are using the HttpClient, and I did not know that. Thanks.

> That's pretty expensive. Are they ever blocked synchronously during this time?

Yes. They are bulk-requests. So there are actually 50.000 transactions in one request.
We try to use Task and async everywhere. But I will comb our code for any synchronous work.

Thanks. I now understand that there is no limit (at least no obvious limit) on concurrent requests.

**Comment by tornie2** [comment]
We can adjust total number of allowed connection with the MaxConnections property
Is it also possible to adjust the number of connections allowed for a single client?

To mitigate a Slowloris attack
https://en.wikipedia.org/wiki/Slowloris_(computer_security)#Mitigating_the_Slowloris_attack

"While there are no reliable configurations of the affected web servers that will prevent the Slowloris attack, there are ways to mitigate or reduce the impact of such an attack. In general, these involve increasing the maximum number of clients the server will allow, limiting the number of connections a single IP address is allowed to make"

**Comment by Tratcher** [comment]
> Is it also possible to adjust the number of connections allowed for a single client?

Nothing built in, you'd have to do that manually in middleware. Nor do I see how that's much of a mitigation. 

The built in mitigation for slowloris is to ensure the client sends and receives at a minimum data rate.

**Comment by tornie2** [comment]
The concurrent request limits you mentioned, must be on the servicepoint manager, right ?

[DefaultConnectionLimit](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit?view=netframework-4.8)

**Comment by Tratcher** [comment]
On .NET 4.x yes. Core has a different implementation.

**Comment by tornie2** [comment]
To anyone struggling with the same issue of not enough concurrency in request processing, I finally figured this one out.

The problem is easily visualized. Just add middleware something like this to your pipeline:

    public class CountRequests : IMiddleware
    {
        private static long _count = 0;
        private static long _totalCount = 0;

        public async Task InvokeAsync(HttpContext context, RequestDelegate next)
        {
            Console.WriteLine($"Started new request. Running requests: {Interlocked.Increment(ref _count)}");
            await next(context);
            Console.WriteLine($"Ended request. Running requests {Interlocked.Decrement(ref _count)} Finished {Interlocked.Increment(ref _totalCount)}");
        }
    }

Add a longing running controller to your api. Could be something like this:

    [Route("api/[controller]")]
    [ApiController]
    public class WaitController : ControllerBase
    {
        [HttpGet]
        public void Get()
        {
            Thread.Sleep(10 * 1000);
        }
    }

Then flood your WaitController with 1000 requests, and watch how they are only started very slowly one by one. That was the problem I was struggling with.

The key to a solution is @Tratcher's confirmation that HttpSys will start request processing using ThreadPool.QueueUserWorkItem. So concurrent requests are limited by the threadpools algorithm for starting threads.

Adding this statement will dramatically increase concurrent requests:

          ThreadPool.SetMinThreads(1000, 100);

**Comment by tornie2** [comment]
Another solution is to return Tasks from your controller.

Your controllers are propably long running because they are I/O bound. So propably a better solution is to release the threadpool threads by changing your controller to return Tasks.

Something like this

    [Route("api/[controller]")]
    [ApiController]
    public class WaitController : ControllerBase
    {
        [HttpGet]
        public async Task<string> Get()
        {
            await Task.Delay(10_000);
            return "Hello";
        }
    }

**Comment by Tratcher** [comment]
> Another solution is to return Tasks from your controller.

Absolutely. AspNetCore is a fully async stack so your actions should all be async as well. Blocking thread pool thread will cause starvation. Raising your threadpool limit is only a temporary mitigation.
