### ISSUE TITLE
Why there is no InternalServerErrorObjectResult or ConflictObjectResult?

### ISSUE THREAD

**Issue by Rychu-Pawel** [aspnet/AspNetCore#13579]
I'm trying to return 500 HTTP error with a body from azure function on an external dependency failure I can catch.

I'm wondering why there are no `InternalServerErrorObjectResult` or `ConflictObjectResult` equivalents for classes in `System.Web.Http` similar to the ones that result classes in `Microsoft.AspNetCore.Mvc` have (e.g. there is `OkResult` and `OkObjectResult`). Is it on purpose? 

For now, I had to create my own implementation as below:
```
public class InternalServerErrorObjectResult : ObjectResult
{
    private const int DefaultStatusCode = StatusCodes.Status500InternalServerError;

    public InternalServerErrorObjectResult(object value)
        : base(value)
    {
        StatusCode = DefaultStatusCode;
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Rychu-Pawel.
We have never seen strong ask from community about these adding much value. Writing these classes on your own is definitely the way to go, given it's quite straight forward.

**Comment by mkArtakMSFT** [comment]
However, it seems there is `ConflictResult` available already, and that would result in 409.
