### ISSUE TITLE
Add Helix tests to public & internal rolling builds

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#13587]

**Comment by JunTaoLuo** [comment]
@HaoK I believe you're tracking this work item?

**Comment by HaoK** [comment]
Yep, just need to setup the triggers

**Comment by HaoK** [comment]
@JunTaoLuo could you clone the helix-test pipeline for me?  I don't seem to have permissions to do that.  I just need a new pipeline(s) to point at the daily-helix-tests yaml and setup the triggers

**Comment by dougbu** [comment]
Huh? Why not add these tests just to public rolling builds of AspNetCore-ci? That'll avoid the internal / external duplication, complexities of managing another pipeline, and so on. (We don't use rolling builds for much except reporting build stats to the CI council and getting a sense of the overall health of the pipelines.)

**Comment by dougbu** [comment]
Put another way, I'd rather _not_ add another YAML to the mix unless we absolutely must. The difference between at most 4 and 1 build per day isn't enough in my estimation.

/cc @Pilchie

**Comment by HaoK** [comment]
I'm not that familiar with the pipeline stuff honestly, at the end of the day, we just need some mechanism to set `/p:IsHelixDaily=true`  If you have a preferred way to do this instead of setting up another daily build, that's fine

**Comment by JunTaoLuo** [comment]
If I'm understanding it correctly, I think we want to just move the content of https://github.com/aspnet/AspNetCore/blob/master/.azure/pipelines/helix-daily.yml into https://github.com/aspnet/AspNetCore/blob/master/.azure/pipelines/ci.yml instead and add a condition so that it doesn't run on PRs. Is that correct @dougbu ?

**Comment by HaoK** [comment]
Alternatively we could just use the AspNetCore-helix-test pipeline to set this flag appropriately (and make it also rolling).  But flipping that flag to true should run the larger set of helix tests, but we do need two helix jobs (x64 and arm64)

**Comment by dougbu** [comment]
I prefer using AspNetCore-ci w/ the "rolling builds only" condition (public but not for a PR) because that has more watchers
