### ISSUE TITLE
Trouble with NavigateTo within OnInitialized

### ISSUE THREAD

**Issue by katiep23** [aspnet/AspNetCore#13582]
Have following code in my MainLayout.Razor page:

```
@inject UserState User
@inject IUriHelper uriHelper

@code {
 protected override void OnInitialized()
    {
        base.OnInitialized();
        State.PropertyChanged += OnPropertyChanged;

        if (!User.isLoggedIn)
        {
            User.redirectUrl = uriHelper.GetAbsoluteUri();
            uriHelper.NavigateTo("/Account/Login");
        }
}
}
```
It worked fine for me, but for others on my team, it gave them "Microsoft.AspNetCore.Components.NavigationException: 'Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown.'" on the uriHelper.NavigateTo line when building.

I think this is related to https://github.com/aspnet/AspNetCore/issues/11591. It shows it resolved.  Is there possibly an update the rest of my team does not have?  Everybody is using latest version of Visual Studio 2019 Preview & .Net Core 3.0 Preview 8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @katiep23.
Is the first-chance exception configuration the same? That is probably the cause here.

**Comment by mkArtakMSFT** [comment]
You can try to turn the `NavigationException` off in the Exceptions dialog (Debug => Windows => Exception Settings) by adding that exception type manually.

**Comment by katiep23** [comment]
Nobody has "NavigationException" in their exception settings.

**Comment by mkArtakMSFT** [comment]
Go ahead and add the above exception type in the Exception Settings as follows:
![image](https://user-images.githubusercontent.com/34246760/64040377-bdc1fb80-cb11-11e9-908c-c31acb852dc3.png)

That will make sure they don't see the exception.

**Comment by mkArtakMSFT** [comment]
If you don't add it, the default behavior is to break on the first chance exception and that's what your colleagues are experiencing.

**Comment by katiep23** [comment]
So I added it to mine to "break when thrown" & it's still not catching that exception.  Is there any reason the exception is being thrown in the first place? If we move "uriHelper.NavigateTo("/Account/Login");" to "OnAfterRender' instead, nobody has the issue.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS thoughts?

**Comment by SteveSandersonMS** [comment]
I was able to use the exception config to control whether or not this causes the debugger to break. Here's my config. Notice that the checkbox is checked, unlike in the screenshot in an earlier comment:

![image](https://user-images.githubusercontent.com/1101362/64161981-6fc13680-ce36-11e9-8a77-5d243305cf7c.png)

With the checkbox checked, the debugger does stop when the redirection occurs. **This is probably not the config you want.** Everyone on the team should ensure this checkbox is **unchecked** (and that VS is not configured to break for *all* Common Language Runtime exceptions), so that it doesn't interfere with page loading all the time.

**Comment by SteveSandersonMS** [comment]
> Is there any reason the exception is being thrown in the first place?

Yes. When you tell the navigation manager to navigate, the system needs to know to stop the whole prerendering process that is taking place. This is a normal part of the redirect-during-prerendering behavior.
