### ISSUE TITLE
Option to Pass Controller Action output as SupplyData in UseSpaPrerendering of .Net Core

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/AspNetCore#13593]
### Is your feature request related to a problem? Please describe.

I know that below is how we pass data using `SupplyData `option of `UseSpaPrerendering` when using `UseSpa` middleware:

```
options.SupplyData = (context, data) =>
{
    // Creates a new value called isHttpsRequest that's passed to TypeScript code
    data["isHttpsRequest"] = context.Request.IsHttps;
};
```

Since I am using Angular so quoting it here, but I believe this should apply to other frameworks as well. 

There are pages in my Angular application which makes http requests to fetch data. Since these requests are made to the same .net core application. I see a potential of optimization i.e. if we could just call the corresponding Controller Action method and supply its data to Angular, so that we don't have to make a http request from our Angular App for SSR.

I initially posted a question related to this on Stackoverflow (https://stackoverflow.com/questions/57740453/passing-controller-action-output-as-supplydata-in-usespaprerendering-of-net-cor) but I believe this could also be added as a feature in .Net Core.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @naveedahmed1.
Spa pre-rendering is deprecated as part of https://github.com/aspnet/AspNetCore/issues/12890

**Comment by naveedahmed1** [comment]
Thanks for the update @mkArtakMSFT then what's the recommended solution for SSR for Angular applications?

**Comment by mkArtakMSFT** [comment]
The recommendation is to rely on the SPA framework provided SSR capabilities. For Angular, SSR support is now integrated into Angular CLI. Here is a good article about it: https://medium.com/@MarkPieszak/angular-universal-server-side-rendering-deep-dive-dc442a6be7b7

**Comment by MusicDemons** [comment]
I wrote a package to determine the currently activated SPA route from the supplydata delegate.

https://github.com/MusicDemons/AspNetSpaPrerendering

You have to define all your SPA routes using the SpaRouteBuilder and then you can check which route was activatie and get the route data (like an id). Based on that you get data from your database through your repositories and add this data to the array. A complete example is included.
