### ISSUE TITLE
_blazor/negotiate call fails from controller actions using Blazor Server Side

### ISSUE THREAD

**Issue by helloserve** [aspnet/AspNetCore#13594]
When adding a component into a vanilla `cshtml` and serving the latest view through the controller, the Blazor code fails after initial prerendering with the following message:

```
blazor.server.js:1 POST https://<some host>/<controller>/_blazor/negotiate 400
Error: Failed to complete negotiation with the server: Error
Cannot send data if the connection is not in the 'Connected' State.
```

The `<controller>` route item in that message changes depending on the name of the controller/view. This has the effect of the page abandoning the page rendering and so never applies `@media` or other CSS bits that the page might need to work correctly (regardless of whether the Blazor component has to actually do something or not).

This issue was also raised by another person on SO: https://stackoverflow.com/questions/56077391/include-blazor-component-into-mvc-view-net-core-3-preview-5

On a side note, the `_framework/blazor.server.js` location reference suffers from the same problem, but it is easily fixable by changing the reference to it in the MVC's `_Layout.cshtml` page by prefixing it with a `/`:

```
<script src="/_framework/blazor.server.js"></script>
```

Unfortunately, there is no obvious way to configure the Blazor hub to change this route for negotiating.

### To Reproduce
1. Setup a new ASPNETCore project using the Blazor Server App
2. Add the `Controllers` and `Views` folders, and all the normal MVC convention things like `_Layout.cshtml` and so on.
3. Add a controller action and view to render.
3. Drop the NavMenu into your view template.
4. Browse to that controller action to see the view and check the JS console.

### Expected behavior
Expected the Blazor engine to not be sensitive to the route of the controller, but to always refer to the root of the host.

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @helloserve .
@javiercn can you please investigate this to see whether there is anything to be fixed for 3.1? Thanks.

**Comment by javiercn** [comment]
This is by design. You need to set the base path for the document using `<base href="~/" />` inside the `head` tag of your html page. Alternatively you can manually start blazor as in
```
    <script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        Blazor.start({
            configureSignalR: function (builder) {
                builder.useUrl(@("/"))
            }
        });
    </script>
```
although this second solution might prevent links from working properly.

**Comment by javiercn** [comment]
Filed an issue to track improving the docs https://github.com/aspnet/AspNetCore.Docs/issues/14134
