### ISSUE TITLE
No Feature Request - Notify ChildComponent that its parameter value has changed - not intuitive

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore#13596]
### Is your feature request related to a problem? Please describe.

I cannot deep link the relevant asp.net core docs section, so here is the general link:
https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0
Search for "_The following child component (ChildComponent) has a Year component parameter and YearChanged callback_" and you will find the piece of code below that caught my attention.

`...

    [Parameter]
    public EventCallback<int> YearChanged { get; set; }
}`

This `EventCallback` is necessary to be present in the ChildComponent in order to change a parameter value triggered by a onchange event, which occurs in a parent component. 

The thing is, that this `EventCallback YearChanged` sitting in `ChildComponent` has no obvious reference/relation to the parent component, it just sits there like a lost dog. No eventhandler/callback is visible.

For me as a developer, this is not intuitive. Of course, there is some background magic going on which then makes sense under the hood.

I hope this won't be part of the official 3.0 release, because it would be hard for a developer to remember this kind of ugly convention, something logical I would prefer.

### Describe the solution you'd like
I would prefer something more intuitive, this is a bit too much magic.

**Comment by SQL-MisterMagoo** [comment]
The docs are misleading here - the `YearChanged` parameter is only needed because of the decision to use @bind-Value, which is the syntax for two-way binding, but the child control - in this example - cannot update the value, so using two-way binding is nonsense.

The example should either show how the child component uses `YearChanged` to **inform the parent component that the value has been changed by the child component** 
OR
The example should use one-way binding, which doesn't require the `YearChanged` parameter and would remove the feeling of "magic" happening.

**Comment by Legends** [comment]
In this example ```<ChildComponent Year="ParentYear" />``` would make more sense.
<hr/>
When using ` @bind-Year="ParentYear"`
Regarding this example, we have a ChildComponent with Parameter/Property named Year, we then also have to implement a YearChanged EventCallback.

I don't know why this is a must? If it is a must, then throw an adequate error stating: 
If you use `bind-Year` you also need to implement a `YearChanged` eventcallback (with convention `ParameternameChanged`).

Rather pass the callback down to the child as a parameter, it would be more obvious then.
You see, it confuses me...

If I remove the `YearChanged` callback, it compiles fine and I get the error in the browser:

> System.InvalidOperationException: Object of type 'BlazorServerApp.Components.ChildYears' does not have a property matching the name 'YearChanged'.

The error would be nice at compile time, not at runtime.
And I also wouldn't know what kind of property is needed, it only says `YearChanged`.
A bit more explanation could be added to the error like: when using bind-value, you have to implement this kind of callback property in your ChildComponent.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Legends.
We will look up for more customer feedback regarding this and if we see confusion by more people we will try to update docs accordingly.

**Comment by Legends** [comment]
At least adapt the docs if everything else is too much work. Thanks
