### ISSUE TITLE
The installation path for x64 SDK installations: "" cannot be the same as for x86 SDK installations: ""

### ISSUE THREAD

**Issue by E1adi** [aspnet/AspNetCore#13604]
Hey guys,

I can't install nor uninstall .NET Core SDK v3.0 prev 8.
The Error I get is as the title:
**_The installation path for x64 SDK installations: "" cannot be the same as for x86 SDK installations: ""_**

I used Revo uninstaller to delete it once and can't install it since than.

Attached the log file of the installer.

P.S. I can't find .Net Core SDK v3.0 prev8 on the installed programs on the machine.

[Microsoft_.NET_Core_SDK_3.0.100_-_preview8_(x64)_20190901145432.log]
(https://github.com/aspnet/AspNetCore/files/3563436/Microsoft_.NET_Core_SDK_3.0.100_-_preview8_.x64._20190901145432.log)

**Comment by blowdart** [comment]
This would be better asked in the .NET core repo - https://github.com/dotnet

**Comment by E1adi** [comment]
@blowdart, Thank you for your response. 
Is there a way to transfer this issue without openning a new one?
Also, iust to make sure, it should be asked in the corefx?

**Comment by blowdart** [comment]
https://github.com/dotnet/core-sdk probably

**Comment by dseferlis** [comment]
@E1adi try this one. I was trying to find a solution for several days...
https://github.com/shanselman/RemoveDotNetCoreSDKInstallers
This just worked for me. Had to install sdks again but seems ok now.

**Comment by E1adi** [comment]
Hey @dseferlis,
I asked the same question in the proper place and got answer that solved my problem. 
Link for the issue with solution:
https://github.com/dotnet/core-sdk/issues/4524
