### ISSUE TITLE
Issue with dynamic loaded RCL razorpages

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore#13602]
### Describe the bug
I've got a netcore 2.2 app which uses dynamically loaded RCL plugins. While the controllers seem to work just fine, razor pages don't seem to be working. I'm getting file not found exceptions.

Another weird bug i have noticed is that while i tried to prepare the repo for reproducing this issue i also noticed another weird behavior. Merely adding an anchor tag which maps to the razor page makes the index page break.

**Curiously enough RazorPages which are declared in the Views folder and are related to a matching controller work.**

**Is this perhaps an issue to the default scaffolding placing a standalone razor page in Areas/MyFeature/Pages without a corresponding controller? I suspect no, because a direct reference to the plugin assembly makes the Page work just fine.**

### Related
https://github.com/aspnet/Mvc/issues/8084

### To Reproduce
1. checkout https://github.com/taori/Sandbox.git
2. switch to branch "razorPagesFileNotFound"
3. build solution
4. startup ComposableWebApplication
5. navigate to /MyFeature/Page1

### Expected behavior
I would expect the page to show up with no exceptions, since controllers + views seem to work fine. (See /feature1 or /feature1/sub)

If you add a direct reference to Plugin3 navigating to /MyFeature/Page1 works just fine, so something seems to be wrong here.

### Screenshots
![grafik](https://user-images.githubusercontent.com/5545184/64072633-a2cac500-cc92-11e9-9293-52c389e5c2fd.png)

### Additional context

Include the output of `dotnet --info`

dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by taori** [comment]
Digging into this just makes it more and more weird.

Scaffolding Identity into RCL and dynamically loading it like this also works for the razorpages - but if i drop selfmade pages in there it stops working as well.

Is there some hidden code to register the razor pages for identity which makes it work?

**Comment by taori** [comment]
Finally found out what is wrong here. 

The controller calls i placed did work because there were no dependencies required to resolve the calls, as soon as any call ran into dependency issues the call would fail.

I suppose under the hood scaffolded identity is included through AssemblyLoaderContext instead of using Assembly.Load (like i did in my plugin loader base) which is why identity worked fine, while my code did not. Therefore this is neither related to constructor injection, RCL nor razor pages. 

What might be useful in this place however might be an analyzer in .netcore sdk applications which points out the dangers of using Assembly.Load to load plugins. If the articles i have found on this topic is correct this issue is the result of a more slick framework, whereas this would have worked with default .NET.

Perhaps an analyzer goes a bit far to provide developer safety here, but finding the root of the issue took quite a while because the exceptions i got were misleading me in the context of my code, while a warning might have been an early indicator that i'm not using the framework correctly at this point.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @taori. Glad that you've found a solution. We don't have plans for providing such an analyzer in the near future.
