### ISSUE TITLE
Hosting Startup Not Executed

### ISSUE THREAD

**Issue by nfplee** [aspnet/AspNetCore#13608]
I've got a class library with a hosting startup class. When running the application the first time it did not pickup my hosting startup class. Therefore I added the following in my program.cs file:

`.UseSetting(WebHostDefaults.HostingStartupAssembliesKey, "MyClassLibrary");`

Now it executes fine. However from reading the documentation I don't get why it did not pick it up the first time? What's the point in having a  WebHostDefaults.HostingStartupExcludeAssembliesKey option if you have to include the assemblies manually anyway?

Also is this behaviour likely to change in v3?

**Comment by davidfowl** [comment]
> Now it executes fine. However from reading the documentation I don't get why it did not pick it up the first time? What's the point in having a WebHostDefaults.HostingStartupExcludeAssembliesKey option if you have to include the assemblies manually anyway?

It needs to be turned on. It can be done via an environment variable or via code (like your code above). There's nothing that will scan all of your assemblies an light up all `IHostingStartup` derived types by default (see the other issue you filed for reasons why).


> Also is this behaviour likely to change in v3?

No v3 is done and the behavior isn't changing.

**Comment by nfplee** [comment]
Thanks, I meant has this changed between v2.2 or v3?

**Comment by nfplee** [comment]
Thanks
