### ISSUE TITLE
External Login: cannot find AddGoogle  in services.AddAuthentication()

### ISSUE THREAD

**Issue by hemanth2** [aspnet/AspNetCore#13603]
### To Reproduce
1. Using this version of ASP.NET Core 3.0.100-preview7-012821
2. MVC Project Template using Authentication
3. Tried services.AddAuthentication().AddGoogle and services.AddAuthentication().AddOpenIdConnect, both are throwing errors

### Screenshots
![image](https://user-images.githubusercontent.com/28334218/64075938-5f954400-ccdc-11e9-8b06-1f2da105f8fe.png)
![image](https://user-images.githubusercontent.com/28334218/64075955-88b5d480-ccdc-11e9-9e9d-2ec802121453.png)

**Comment by datvm** [comment]
They haven't updated the [docs content](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-3.0&tabs=visual-studio) to 3.0 yet. Related issue: https://github.com/aspnet/AspNetCore.Docs/issues/13234

**Comment by Tratcher** [comment]
These libraries are no longer in the default set, you need to install the associated nuget packages.
