### ISSUE TITLE
[Blazor p8] OnInitializedAsync is executed for twice on pre-render

### ISSUE THREAD

**Issue by ctrl-alt-d** [aspnet/AspNetCore#13607]
# Issue

`OnInitializedAsync` is executed for twice when page has been served as  "pre-render".

# Version

```
[dani@localhost tw]$ dotnet --version
3.0.100-preview8-013656
```

# Steps to reproduce and screen shots:

```
@page "/"
@inject IUriHelper UriHelper

<h1>Hello, world!</h1>

Welcome to your new app.

@code{

    protected async override Task OnInitializedAsync()
    {
        System.Console.WriteLine("_*   ");
        System.Console.WriteLine("_**************************");
        System.Console.WriteLine("_***** Pre render ******");
        System.Console.WriteLine("_**************************");
        System.Console.WriteLine("_   ");
        return;
    }
}
```

And I see is executed for twice only on pre-render:

![63875371-9fe68080-c9c3-11e9-9537-41924ef83401](https://user-images.githubusercontent.com/3105983/64079051-e0573e80-cce2-11e9-8f87-b878ebcea236.gif)

Has it some explanation?

The question on stackoverfow: [Blazor UriHelper.NavigateTo is calling the page twice](https://stackoverflow.com/questions/57680784/blazor-urihelper-navigateto-is-calling-the-page-twice/57696602)

**Comment by ctrl-alt-d** [comment]
Related: https://github.com/aspnet/AspNetCore/issues/13172

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ctrl-alt-d.
We did change the behavior in this area in Preview9.

**Comment by gitskab** [comment]
Hi,

I'm having the same issue but only as I publish my app to Azure App Services. If I switch RenderMode to Server then it gets called only once but then contextAccessor.HttpContext is null when injected into my service class. 

On my localhost it works fine in both cases..

Am I doing something wrong here?
