### ISSUE TITLE
Using Result instead of GetAwaiter().GetResult()

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/AspNetCore#13611]
In [CorsMiddleware](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/CORS/src/Infrastructure/CorsMiddleware.cs#L184) there's a `GetAwaiter().GetResult()` call on a task. Since the task is completed successfully isn't it better to call `Result`?
```
var policyTask = corsPolicyProvider.GetPolicyAsync(context, policyName);
if (!policyTask.IsCompletedSuccessfully)
{
    return InvokeCoreAwaited(context, policyTask);
}
corsPolicy = policyTask.GetAwaiter().GetResult();
```

**Comment by Eilon** [comment]
It seems like the notable difference is about how the exception is thrown, but perhaps in this case it doesn't matter if it's guaranteed that the task didn't fail (due to the `if()` check): https://stackoverflow.com/questions/17284517/is-task-result-the-same-as-getawaiter-getresult

**Comment by RemiBou** [comment]
Why not make this method async ? It already returns a Task, the public interface won't have to change.

**Comment by Kahbazi** [comment]
If A method is async, compiler will generate some code to handle its state machine. The idea is to keep this way for performance improvement.

**Comment by vertonghenb** [comment]
@Kahbazi this might shed some light on the issue:
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md

**Comment by Kahbazi** [comment]
@vertonghenb 

> 💡NOTE: There are performance considerations when using an async state machine over directly returning the Task. It's always faster to directly return the Task since it does less work but you end up changing the behavior and potentially losing some of the benefits of the async state machine.

**Comment by pranavkm** [comment]
Closing as the question has been answered.

**Comment by Eilon** [comment]
@pranavkm there's also a PR for this: https://github.com/aspnet/AspNetCore/pull/13614
