### ISSUE TITLE
[Blazor] Default type for @typeparam

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#13619]
Creating generic components, it would be helpful to allow a default type for `@typeparam` for components that have optional generic params, or the typeparam is not being using for parameters (therefore no way to infer).

### Describe the solution you'd like

Allowing something like this
#### TestComponent.razor
```xml
@typeparam TValue = string

<h3>Has Value: @(OptionalParameter != null)</h3>

@code {
    [Parameter] public TValue OptionalParameter { get; set; }
}
```

#### Usage

```xml
@* TValue is int *@
<TestComponent OptionalParameter="5" /> 

@* TValue is string (instead of compilation error)*@
<TestComponent />  
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @stavroskasidis.
This is not something we can support.

**Comment by stavroskasidis** [comment]
May I ask why? Is this a technical reason ? It seems to me that it should't be that hard to implement.
From the top of my head, and sorry if this is completely nonsensical, what about this approach:

This line here
```
@typeparam TValue = string
```
would generate an attribute on the generated class, something like

```cs
[DefaultTypeParam("TValue", typeof(string))]
public class TestComponent<TValue> : BlazorComponent
```

And then in the context of a `.razor` file, the razor compiler would generate an automatic inference based on the attribute.

Is what I am proposing completelly non-feasible?
