### ISSUE TITLE
Use fluent api to confiure the metadata(DisplayMetaData, ValidationMetaData and BindingMetaData)

### ISSUE THREAD

**Issue by TonyWoo** [aspnet/AspNetCore#13616]
Entity framework has the fluent api to Configue and Map Properties and Types, but the default Model metadata provider in asp.net mvc core is using the DataAnnotation only. 

Can you provide a fluent api to allow us to configure the meta data? We want to keep the view model clean, so no any attribures in the ViewModel. If you don't have this plan, can you please advise how to do this as well? Thank you.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @TonyWoo.
This is not something we've heard community ask for in the past. So we don't have plans to do this.
This would make a great community project.
