### ISSUE TITLE
Execute Hosting Startups to Lookup by Type Instead of an Attribute

### ISSUE THREAD

**Issue by nfplee** [aspnet/AspNetCore#13622]
Looking at the source code of the GenericWebHostBuilder I can see it says:

```
foreach (var attribute in assembly.GetCustomAttributes<HostingStartupAttribute>())
{
    var hostingStartup = (IHostingStartup)Activator.CreateInstance(attribute.HostingStartupType);
    hostingStartup.Configure(_hostingStartupWebHostBuilder);
}
```

Why can't it simply say?:

```
foreach (var type in assembly.ExportedTypes.Where(t => t.IsDefined(typeof(IHostingStartup), false))) {
    var hostingStartup = (IHostingStartup)Activator.CreateInstance(type);
    hostingStartup.Configure(_hostingStartupWebHostBuilder);
}
```

This way it no longer has to have a HostingStartupAttribute and also allows you to have multiple IHostingStartup files in the same assembly.

I considered whether the reason was for performance but after doing a few tests, I did not notice much difference. Although I'm sure you have done more thorough research.

**Comment by davidfowl** [comment]
- Scanning all types in the assembly can slow down startup time so doing it all the time means everyone has to pay that cost and it's not pay for play.
- It's no longer opt-in. If there's an `IHostingStartup` type defined in the assembly, it's going to be discovered and activated. That means we now need a way to turn it off.

**Comment by nfplee** [comment]
- Thanks I assumed that was the case.
- When you say it's "no longer opt-in", is this a change in v3?

**Comment by davidfowl** [comment]
That was about describing changes that would need to be made to the current model if we went that path (right now it's opt-in you suggestion makes it opt-out).

**Comment by nfplee** [comment]
Thanks for clearing this up, I'll close this and my current issue.
