### ISSUE TITLE
Add additional claims on successful login with Google authentication

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/AspNetCore#13626]
I use the following code to sign in users using Google authentication.

```c#
services.AddDataProtection()
    .PersistKeysToFileSystem(new System.IO.DirectoryInfo("/Users/marcus/Temp/App/KeyStorage"))
    .SetApplicationName("SharedCookieApp");

services
    .AddAuthentication(options =>
    {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
        options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    })
    .AddGoogle(options =>
    {
        options.ClientId = "xxx.apps.googleusercontent.com";
        options.ClientSecret = "xxx";
        options.Scope.Add("https://www.googleapis.com/auth/userinfo.profile");
    })
    .AddIdentityCookies(options =>
    {
        options.ApplicationCookie.Configure(a => a.Cookie.Name = ".AspNet.SharedCookie");
    });
```

How can I add additional claims when a user is successfully logged in? I tried using the event `OnTicketCreating` but the new claim is not added to to the cookie so it can be read using the following code.

```html
@foreach (var claim in User.Claims)
{
    <dt>@claim.Type</dt>
    <dd>@claim.Value</dd>
}
```

This is how I use the `OnTicketCreating` event.

```c#
options.Events.OnCreatingTicket = ctx =>
{
    var identity = (ClaimsIdentity)ctx.Principal.Identity;
    identity.AddClaim(new Claim("FullName", ctx.Principal.FindFirst(ClaimTypes.Name).Value));
    return Task.CompletedTask;
};
```

So is it possible to add additional claims to the authentication cookie using this or any other approach?

**Comment by Tratcher** [comment]
It's a two stage process:
1) persist the claims from Google into the temp External cookie.
2) Transfer the claims to the long term Identity cookie.
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-2.2

**Comment by marcuslindblom** [comment]
I don't really understand what you mean by temp external cookie and long term cookie. The docs suggest using `ClaimActionCollectionMapExtensions`
? Are there any real example in the docs or can you provide me with one?

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.0#creating-and-adding-claims

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-2.2#map-user-data-keys-and-create-claims gives examples for setting up which external fields you want to save as claims (MapJsonKey).  These are stored in a temporary cookie usually named IdentityConstants.ExternalScheme. 

The second example in that section covers OnPostConfirmationAsync and shows how to persist those extra claims long term via _userManager.AddClaimAsync.

**Comment by marcuslindblom** [comment]
Ok, I see. So the claim must be stored in the storage provider I use by adding it with `_userManager.AddClaimAsync`? I thought it was possible to only send a custom claim without saving it to the database but if I understand correctly that is not possible?

**Comment by Tratcher** [comment]
@HaoK ?

**Comment by HaoK** [comment]
We added a new method `SignInManager.SignInWithClaimsAsync` in 3.0 for this:

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Core/src/SignInManager.cs#L231

**Comment by marcuslindblom** [comment]
Ok, cool! I use the preview bits so I'll give it a try. Thanks!
