### ISSUE TITLE
Antiforgery token validation failed. The antiforgery cookie token and request token do not match.

### ISSUE THREAD

**Issue by roberthannon** [aspnet/AspNetCore#13632]
Hi, there's a weird situation where antiforgery validation errors seem to occur in .Net Core 2.2.

This project demonstrates the issue: https://github.com/roberthannon/AspNetCoreAntiforgeryIssue

The logged error message is:
> Antiforgery token validation failed. The antiforgery cookie token and request token do not match.

I can only reproduce it when opening a link to a form from an email in two tabs (e.g. a reset password link). When the form on the first tab is submitted a 400 response is returned and the error message above is logged.

What's strange is that it ONLY occurs when opening the link from an email. These methods do NOT produce the error:
* Opening two tabs and pasting the link in the address bar manually
* Opening two tabs from a link in website itself
* Right clicking the email link and opening two tabs with "Open link in new tab"
* Right clicking the email link and opening two tabs with "Open link in incognito window".

### To Reproduce
1. Create a new Asp.Net Core MVC website from template (VS 2019)
2. Create a new page which has a simple form which is validated with `[ValidateAntiForgeryToken]` on post.
3. Email yourself a link to that page (I've used Gmail & Mailtrap)
4. Open the link in two tabs by clicking on it normally
5. Submit both forms in any order
6. The form which was opened FIRST should produce a 400 error

### Expected behavior
I'm not sure what's expected. We're upgrading a .Net Core 1.1 website and the problem does not occur in the old version.

I would expect no error, or at least a way to show the user a better error message such as "You've opened this page in another window"... see https://github.com/aspnet/AspNetCore/issues/4847

### Additional context
* I'm using .Net Core 2.2.106
* Have updated nuget packages to latest (Microsoft.AspNetCore.App 2.2.6).
* Can reproduce the issue in both Chrome & Edge.
* Can reproduce with both Gmail and Mailtrap.io.
* Occurs locally and on all our test environments... HTTP, HTTPS, Debug, Release...

May be related to these issues:
* https://github.com/aspnet/AspNetCore/issues/11485
* https://github.com/aspnet/AspNetCore/issues/2882

Output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.106\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.106 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by blowdart** [comment]
This is expected (somewhat). In 2.0 we introduced support for SameSite cookies, which allows you to mark cookies to only flow when the previous request is from the same site. For example,, if I drop a cookie in page 1, then click to page 2 on the same site, the cookie will flow.

What is happening is your reset page drops an anti-forgery cookie. These are marked with the same site attribute, because it's a CSRF protection. When you open page a second time from a 3rd party site, such as gmail we can't see any previously dropped CSRF token because of same site. And that's a good thing security wise. So we create a new one, and the one used in the first page is now gone, there's a different value, and thus the error.

There's no way for us to give a friendly error, because we can't tell at the back end what is happening and why we can't see the cookie. It might not be there, it might be there but same site hid it, or even the secure flag hid it because it was initially created in HTTPS and now you're on HTTP. We just can't know.

You could turn the SameSite protection off for CSRF cookies, but that is, in my opinion, a bad idea, you're removing security to avoid an error, without knowing how many end users actually encounter it, and whether you can justify the drop in protection.

**Comment by roberthannon** [comment]
Thanks for clarifying!

It's kind of weird behavior in my opinion, but I think we can live with it for now.

As for the error message: the antiforgery validation returns a 400 status code and as far as I can tell there's no way to determine that the token validation was the cause. This is what https://github.com/aspnet/AspNetCore/issues/4847 is about. If we could determine that then we could at least return the user a slightly more informative error like "Opps something went wrong - have you opened this link twice?".

**Comment by roberthannon** [comment]
Also (as you mentioned) I can solve the issue by adding:

```csharp
services.AddAntiforgery(options =>
{
	options.Cookie.SameSite = SameSiteMode.None;
});
```

This may be a naive question, but for antiforgery why is this insecure? Wouldn't an attacker still need to guess a valid `__RequestVerificationToken` which validates with the cookie they cannot read?

And if any authentication cookies are set to `SameSiteMode.Lax` or above then an attacker should only be able to attack anonymous routes... which they could do via other means?

**Comment by hempels** [comment]
"why is this insecure?"
It's not insecure - it's less secure. In the same way having one lock is less secure than having two locks; that doesn't mean having one lock is insecure.

I think samesite on these antiforgery cookies is pretty much guaranteed to cause real problems for any reasonably complex application. We run it set to "None" - but we do require HTTPS (SecurePolicy = Always) so it can't be snatched from a wayward POST.
