### ISSUE TITLE
2 Blazor WebAssembly App templates

### ISSUE THREAD

**Issue by pappasa** [aspnet/AspNetCore#13636]
When I create a Blazor App, it prompts me to choose the template, but it shows me 2 "Blazor WebAssembly App" templates as shown in this screenshot:

![CreateNewBlazorApp](https://user-images.githubusercontent.com/23055341/64152159-b150e200-ce34-11e9-8a0f-17876cc2cff8.jpg)

There is no option to delete them.

```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by SIkebe** [comment]
@pappasa This might help you :-)
https://github.com/aspnet/AspNetCore/issues/12618#issuecomment-515545058

**Comment by pappasa** [comment]
That comment says:

> Make sure you uninstall the Blazor VSIX extension.

But how do I do that?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pappasa.
In the VS go to the `Extensions => ManageExtensions`, navigate to the `Installed` tab, locate the `Blazor` extension and select `Uninstall`:
![image](https://user-images.githubusercontent.com/34246760/64195892-6d131100-ce37-11e9-8f36-3c13e9055673.png)
