### ISSUE TITLE
Kestrel http/2 problems with Kaspersky enabled

### ISSUE THREAD

**Issue by mrgleba** [aspnet/AspNetCore#13639]
### Describe the bug
After switching from running Kestrel behind an naginx reverse proxy to standalone
we've started experiencing some page load problems. We've been able to narrow it down
to Kaspersky antivirus software.

Kestrel is configured to serve
```cs
Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1AndHttp2
```

```
$dotnet --info

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Application is run within a docker container using a current ``` microsoft/dotnet:2.2-aspnetcore-runtime``` image

The page won't load reporting a protocol error. This happens in all available browsers (Chrome,
Firefox, Edge).

We've found that disabling secure connections scanning in kaspersky:
https://help.kaspersky.com/KESWin/11.1.0/en-US/175124.htm
solves the issue.

The page in question is https://e-adm.pl

I'm aware that this report is rather vague, but I wasn't able to collect any
additional information (browser consoles show no informaciton).
Is there any possible additional info I could provide to help resolve this issue?

**Comment by khellang** [comment]
> We've been able to narrow it down to Kaspersky antivirus software.
> We've found that disabling secure connections scanning in kaspersky solves the issue.

Doesn't that mean you've solved the issue? I'm not sure what could be done in Kestrel to avoid this?

**Comment by blowdart** [comment]
This sounds like an issue with Kaspersky. Which isn't unsurprising, if they're trying to intercept HTTPS.

There is nothing we can do here, HTTP/2 needs to run over HTTPS. If Kaspersky stops the use of HTTPS then the solution is to uninstall Kaspersky.
