### ISSUE TITLE
MapJsonKey for nested structure

### ISSUE THREAD

**Issue by balaji-rajan** [aspnet/AspNetCore#13647]
I am trying to map nested json claims during my authentication, I'm using **OpenIdConnect** as my authentication builder to connect with IdentityServer4

https://github.com/aspnet/AspNetCore/blob/c39fbb8f12002f61df6c093b0c11e6bd585ee202/src/Security/Authentication/OAuth/src/JsonKeyClaimAction.cs#L46

Along with JArray, I would like include JObject as another mapping option to map Nested JSON claims

Eg:
```
{
    "name": "test_name",
    "given_name": "test_given_name",
    "email": "test@test.com",
    "address": {
        "street_address": "test_street_address",
        "locality": "test_locality",
        "postal_code": test_postal_code,
        "country": "test_country"
    }
}
```

**Comment by blowdart** [comment]
You can't. This isn't how [JWT](https://tools.ietf.org/html/rfc7519) works. Claims are name value pairs, nothing more. You can't nest.

**Comment by Tratcher** [comment]
Is that data coming from the JWT or from the UserInfoEndpoint?

**Comment by balaji-rajan** [comment]
@Tratcher Its from UserInfoEndpoint, Alternatively i can map it to a claim using **JsonSubKeyClaimAction** but cant group nicely

**Comment by Tratcher** [comment]
Well, there's always `MapCustomJson`

**Comment by blowdart** [comment]
Closing as there are no more questions
