### ISSUE TITLE
[Blazor] Masked TextBox with Regex

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#13645]
Hello guys, i mett actually problem to use a mask on some of my inputs.

I don't really find a pure blazor way so i decide to use this Js library : https://github.com/RobinHerbots/Inputmask

when i use it, it seem the binding is broken (the original binding if a provide value seem OK, but when i try to modify value of my input i never enter in the setter of my property binded).

So the questions :
- do you have other solution to do that ? especially without js dependency
- if not, do you know whats happen with the binding ? (i can make a simple project to reproduce that if needed)

Thanks !

Julien

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @julienGrd.
Blazor listens to the `onchange` event, which seems is not the case for this library.
Feel free to contact the author of that library to enable integration with Blazor.

**Comment by julienGrd** [comment]
I understand, but the change event seem to be fired
````
$(selector).inputmask(mask);
        $(selector).change(function () {
            alert("Handler for .change() called.");
        });
````

I receive the alert, but the setter of my property is not called

**Comment by julienGrd** [comment]
this is my way to resolve this problem, in case someone have the same
````
$(selector).on("input", function () {
            this.dispatchEvent(new Event('change'));
        });
````
