### ISSUE TITLE
After upgrading my blazor solution from .net Core 3 Preview 6 to Preview 8 I'm getting Intellisense errors

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#13654]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/716175/after-upgrading-my-blazor-solution-from-net-core-3.html)._

---
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Layouts' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)	BlazorChatDemo.Client	D:\Sources\BlazorChatSample.Client\Pages\Index.razor	1	Active
Error	CS0234	The type or namespace name 'Layouts' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)	BlazorChatDemo.Client	D:\Sources\BlazorChatSample.Client\Pages\_Imports.razor	1	Active
Error	CS0234	The type or namespace name 'RuntimeHelpers' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)	BlazorChatDemo.Client	D:\Sources\BlazorChatSample.Client\Shared\NavMenu.razor	1	Active

Sometimes some of them dissapear for a while, but then they return back and can do nothing with them.

---
#### Visual Studio Feedback System on 8/30/2019, 00:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vsfeedback.
There were some API changes made between these two releases, which require projects created using earlier previews to be adjusted. This comment summarizes the changes necessary to make your project work again: https://github.com/aspnet/AspNetCore/issues/13133#issuecomment-521508803
