### ISSUE TITLE
Lost HTTP Header Attribute

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#13650]
_From @gaborposz on Friday, August 30, 2019 8:02:30 AM_

Hello,
During development we have encountered a very strange issue regarding HTTP Headers.

We use [WinHttpHandler](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/4.5.2) on the client, and [Kester](https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel.Core/2.2.0) (with self-hosting) on the backend for HTTP/2 communication, and we put some custom attributes into the HTTP header to transfer data together with the HTTP requests.

We noticed that occasionally -after several requests with specific header sizes- our custom header attribute is completely missing on the server side, although it was seemingly sent successfully by the client. It’s still unclear whether the error is on client side (WinHttpHandler) or on server side (Kestrel), but it only happens if HTTP 2.0 protocol is used with secure communication (HTTPS).

I have created a simple project to reproduce this error, the code is pretty straightforward, but let me know if you have any question.
Please have a look, and give us feedback if it can be fixed, or workaround is possible.

[MissingCustomHeaderReproduce.zip](https://github.com/dotnet/corefx/files/3558893/MissingCustomHeaderReproduce.zip)

Thanks and Best Regards,
Gabor Posz

_Copied from original issue: dotnet/corefx#40700_

**Comment by Tratcher** [comment]
_From @davidsh on Friday, August 30, 2019 1:21:19 PM_

What version of .NET Core are you using?  Output of "dotnet --info" ?

Why are you using WinHttpHandler?  You should consider using .NET Core.  As of .NET Core 3.0, HttpClientHandler (which uses SocketsHttpHandler) supports HTTP/2 protocol.

**Comment by Tratcher** [comment]
_From @gaborposz on Friday, August 30, 2019 2:32:11 PM_

We are using WinHttpHandler because our client is .NET Framework 4.7 based (it must be, because it is used by other .NET Framework components), and this is the only way to support HTTP/2 with .NET Framework.

Only our backend service is .NET Core based. We use the [.NET Core 2.2.3 Runtime](https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.2.3-windows-x64-installer) (Microsoft.NETCore.App 2.2.3) in production environment, and [.NET Core 2.2.105 SDK](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.2.105-windows-x64-installer) for development.

**Comment by Tratcher** [comment]
_From @davidsh on Friday, August 30, 2019 3:56:22 PM_

>our custom header attribute is completely missing on the server side, although it was seemingly sent successfully by the client. 

How do you know this?  Did you do a Wireshark trace? Although with HTTP/2 normally over TLS that would be difficult.

>It’s still unclear whether the error is on client side (WinHttpHandler) or on server side (Kestrel)

Can you try another server (such as IIS) to determine whether it is really a client-side or server-side problem?

**Comment by Tratcher** [comment]
_From @gaborposz on Friday, August 30, 2019 4:20:38 PM_

I tried with Wireshark, but with secure communication it is not visible, and with disabled HTTPS the error is not reproducible.

I might try with IIS, but I'm not familiar with that, so it would take more time.

Isn't there an easier way to find out whether it's the client or the server? E.g.: Dump out the raw data by WinHttpHandler or Kester before/after the encryption?

**Comment by Tratcher** [comment]
_From @gaborposz on Monday, September 2, 2019 2:38:28 PM_

Hi,
After some struggle I eventually managed to try it with IIS. I tested it with an ASP.NET (.NET Framework) as well as an ASP.NET Core handler, and both of them was working fine. It indicates that the problem is most probably in the self hosted Kestrel.

**Comment by Tratcher** [comment]
_From @davidsh on Tuesday, September 3, 2019 4:21:12 PM_

Seems like this issue should be moved to one of the ASP.NET repos.

cc: @Tratcher

**Comment by Tratcher** [comment]
Can you re-test against 3.0 preivew9 (out soon). This may be the same issue as https://github.com/aspnet/AspNetCore/pull/12782.

Another way to get a trace for this is using Kestrel's connection logger.
https://github.com/aspnet/AspNetCore/blob/2217be28261ee2df07dd5d293d92a05a458f5a6b/src/Servers/Kestrel/samples/SampleApp/Startup.cs#L108-L112
Be sure to turn your log levels up to Trace.

**Comment by gaborposz** [comment]
Hi,
I managed to try it with .NET Core 3 preview 9 and the error is gone, so it seems to be indeed the same as #12782.
However, we would need the solution in .NET Core 2.2, because upgrading to 3.0 is not feasible within the available time frame. Can you merge it back to 2.2?

**Comment by Tratcher** [comment]
@shirhatti can you check on this 2.2 patch request? I know 2.2 will go out of support by the end of the year. https://dotnet.microsoft.com/platform/support/policy/dotnet-core

A workaround I haven't tested would be to reduce kestrelOptions.Limits.Http2.HeaderTableSize to 1 to effectively disable request header compression.
https://github.com/aspnet/AspNetCore/blob/ac9a6f331e3976e6ea170bec5a6964d080400c16/src/Servers/Kestrel/Core/src/Http2Limits.cs#L47

**Comment by gaborposz** [comment]
Hi,
The workaround seems to be working, but we would rather upgrade to new 2.2 patch version if possible.

Could you please give me feedback if the back merge to 2.2 is possible?

Thanks,
Gabor

**Comment by Tratcher** [comment]
@gaborposz We'll check, but having a simple workaround usually disqualifies issuing a patch. Even more so when the fix is available in a later release (3.0).

**Comment by anurse** [comment]
Agreed with @Tratcher here. We won't be backporting this change to 2.2 as it has a viable workaround and is fixed in the (imminent) 3.0 release.

**Comment by gaborposz** [comment]
@anurse I'm sad to hear it :( 
We will use the workaround then until we can upgrade to 3.0 (or the 3.1 LTS).

@Tratcher: What is the impact of the workaround? Can we expect e.g. decreased performance, or is it negligible?

**Comment by Tratcher** [comment]
The client won't be able to use dynamic header compression making requests slightly larger, but you would only see a performance difference at extreme loads.

**Comment by anurse** [comment]
@gaborposz Sounds good, we're happy to help get the workaround in place. Backporting always comes with a bunch of known risks and some unknown ones too, and at the moment we don't believe the impact to be worth those risks given that it's fixed in 3.0. Thanks for your understanding here! Feel free to let us know if there are issues that block adoption of 3.0 (to get the fix) or implementation of the workaround!

We [just released a release candidate of 3.0](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-release-candidate-1/) which is extremely close to the final shipping version if you'd like to start investigating an upgrade now.
