### ISSUE TITLE
VS 2019 16.2.2   and .Net core .2.2.6 SDK 2.2.401

### ISSUE THREAD

**Issue by wli3** [aspnet/AspNetCore#13665]
_From @vsfeedback on Tuesday, September 3, 2019 10:25:22 PM_

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/697682/vs-2019-1622-and-net-core-226-sdk-22401.html)._

---
Hi ,
I have updated VS 2019 to 16.2.2.  Installed .net core 2.2.6 (sdk 2.2.401)
I can't upgdate my asp.net core  project to use .net core 2.2.6. 

C:\&gt;dotnet --list-sdks
2.2.401 [C:\Program Files\dotnet\sdk]

---
#### Visual Studio Feedback System on 8/19/2019, 03:54 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/19/2019, 10:28 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

_Copied from original issue: dotnet/cli#12478_

**Comment by wli3** [comment]
_From @mkArtakMSFT on Tuesday, September 3, 2019 10:28:07 PM_

@livarcocc can you please move this over to aspnet/AspNetCore repo? Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

Please provide details about what's the issue you're facing so we can better understand the problem.

**Comment by wli3** [comment]
I moved it from CLI to aspnet/AspNetCore per your request. @mkArtakMSFT https://github.com/dotnet/cli/issues/12478#issuecomment-527666186

**Comment by mkArtakMSFT** [comment]
Thanks @wli3. I know, just waiting for the original author of the issue to get to us.

**Comment by pranavkm** [comment]
There isn't enough details here to figure out what to do. Closing this.
