### ISSUE TITLE
blazor .netcore 3 Razor Task and void Param without async/await

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#13661]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/711224/blazor-netcore-3-razor-task-and-void-param-without.html)._

---
[regression] [worked-in:16.3.0 Preview 2.0]
What steps will reproduce the problem?
1.Make a Blazor Componnent . Razor
2. Using @onclick=&quot;Method(Param)&quot;
3.It will work on Method without Param only

What is the expected output? What do you see instead?
I expect it to read the Param I sent it from clint side to server side when calling the Method
and what I see is it refuses To take work with param but it works fine without it I had to use public Variablies to send from clint to server insted

Please provide any additional information below.
Point of blazor is to run C# on clint side without the need of JS.
What if it is possable to use C# to animate HTML objects and create HTML tables and bring back the DataGridView to LIFE in blazor.
I think we have all the tecnology we need right?

---
#### Visual Studio Feedback System on 8/26/2019, 00:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/26/2019, 10:59 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
To pass arguments to event handlers, you can use lambda expressions, as it is shown below:
![image](https://user-images.githubusercontent.com/34246760/64212061-030d6280-ce5d-11e9-8697-735280375b26.png)

Alternatively you can use pure JSInterop-based approach, as documented here: https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0
