### ISSUE TITLE
UserManager cannot verify email verification tokens generated by identical UserManager in another process

### ISSUE THREAD

**Issue by SidShetye** [aspnet/AspNetCore#13667]
### Describe the bug

ASP.NET Core Identity's `UserManager` class is unable to validate email verification tokens if those tokens are created in an identically configured `UserManager` instance in another process. This happens even if the services, EF models and the underlying databases are identical. 

### To Reproduce

Issue is reproduced at this repo: https://github.com/SidShetye/UserManagerTokenValidationIssue

### Expected behavior

The token generated by [`GenerateEmailConfirmationTokenAsync`](https://github.com/SidShetye/UserManagerTokenValidationIssue/blob/master/Client/TestUserRegisterEmailVerify.cs#L124) should be accepted at [`ConfirmEmailAsync`](https://github.com/SidShetye/UserManagerTokenValidationIssue/blob/master/API/Controllers/AccountsController.cs#L74). 

### Comments

If email verification tokens are created and consumed in the same monolith, they are validated just fine. See [`AutoTestRegisterAndEmailVerify`](https://github.com/SidShetye/UserManagerTokenValidationIssue/blob/master/API/Controllers/AccountsController.cs#L90) in the API or [`RegisterVerifyEmailLocallyAsync`](https://github.com/SidShetye/UserManagerTokenValidationIssue/blob/master/Client/TestUserRegisterEmailVerify.cs#L153) in the Client for these scenarios. But if they are generated and consumed separately (e.g. micro-services or integration testing scenarios) it's broken. 

We haven't gone too deep into the ID framework but seems like something 'extra' is being mixed into the tokens. Something that's per process and really shouldn't be there.

**Comment by blowdart** [comment]
In this case you need to configure data protection to use the same application name and keyring because apps are isolated by default.

See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2#setapplicationname

**Comment by SidShetye** [comment]
Ok, that adds up and I can confirm that using the same app name makes it work across processes.
