### ISSUE TITLE
Avoid calling StateHasChanged in EventCallback

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#13664]
I know the documentation says this

> There's no need to manually call StateHasChanged()
https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0

But I actually need all the contrary. I need the ability to listen to a EventCallback and do not recreate all ui of the parent just because an event was listened. Is there any way to do this?

**Comment by SteveSandersonMS** [comment]
Could you give more information about your scenario? For example, I'm interested in whether it's a child causing an event on a parent, or vice versa, or something else. Would you be able to post some kind of really short code sample that characterises your scenario? I might be able to suggest ways to achieve what you want.

The other thing you can look at is overriding the `ShouldRender` method on whichever component you don't want to re-render. You can put in arbitrary custom logic to control whether or not a given render takes place.

**Comment by Andrzej-W** [comment]
Simply use `Action` instead of `EventCallback`. Read this: https://github.com/SQL-MisterMagoo/BlazorEventsDemo

**Comment by arivoir** [comment]
I have a couple scenarios.

The first is a component which renders a grid of cells, to create a data-grid control. I'm listening to the onclick html event

> builder.AddAttribute(5, "onclick", EventCallback.Factory.Create<UIMouseEventArgs>(this, ...));

The logic of the code invoked by this event is dynamic, it can depend on the kind of cells, or can even be customized by the customer using the grid.
There is no way to say before hand whether the event will do something or not.
The problem is only listening to the event causes the whole grid of cells to be rebuilt.

Secondly, A text-box control that supports auto-complete. It has a Text property and a TextChanged callback. The latter allows the parent to set the "auto-completed text" (The part that appears selected when typing). The problem is when the parent listen to the TextChanged event, the parent is re-rendered and causes the Text property of the text-box to set again, conflicting with the code executed in the TextChanged event.

Using an Action can work in some situation, internal component, but I don't imagine having duplicated events like in the TextChanged event.

I was trying the ShouldRender and it can helps in the text-box scenario, but honestly looks weird. It's like the parent is repeatedly updating the child, and the child is continuously ignoring it.

**Comment by SteveSandersonMS** [comment]
> The first is a component which renders a grid of cells, to create a data-grid control. I'm listening to the onclick html event
> builder.AddAttribute(5, "onclick", EventCallback.Factory.Create(this, ...));

Not sure if that means you're writing your own RenderTreeBuilder logic by hand, as in the code snippet you posted. If you are, then when you call `EventCallback.Factory.Create`, just don't pass `this` as the first parameter. That controls which component gets notified to re-render. Instead pass some other object (not sure whether `null` is allowed).

> I was trying the ShouldRender and it can helps in the text-box scenario, but honestly looks weird. It's like the parent is repeatedly updating the child, and the child is continuously ignoring it.

That doesn't sound too weird to me. If your components are wired up in such a way that the parent thinks the child may need to update, then it will tell the child. It's up to the child whether it really does want to update, which is what `ShouldRender` is for. It sounds like you're using this API correctly.

**Comment by SteveSandersonMS** [comment]
Sounds like this is answered, so closing. Hope that's right!

**Comment by arivoir** [comment]
@SteveSandersonMS I finally tried your proposed workaround. Sorry for the delay.

> when you call EventCallback.Factory.Create, just don't pass this as the first parameter. That controls which component gets notified to re-render. Instead pass some other object (not sure whether null is allowed).

Unfortunately, neither of the workarounds worked, passing null throws an exception, and passing a dummy component doesn't work either, the framework ends up calling the BuildRenderTree method anyway. The parameter of the Create method is ignored apparently.

Any other idea to dodge this problem?

**Comment by arivoir** [comment]
@SteveSandersonMS 

- Why does calling StateHasChanged in a parent doesn't update the children? How does this work?

- Why does calling StateHasChanged in 2 sibling components, in the same call, causes one of them to be rendered firstly? There is a visible delay, even running locally. Is there any way I can ensure the 2 components will be updated together?

**Comment by SteveSandersonMS** [comment]
I meant passing some other object, e.g., `new object()`.
