### ISSUE TITLE
Create Blazor Server App with IndAuth > F5 and register > Click the user name > Click Logout, it doesn't work.

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#13679]
_From @v-yuyul on Tuesday, September 3, 2019 9:18:42 AM_

**Repro Configuration**: Win10 x64 19H1 ENU + Dev16.4 preview 1 (Preview channel : pre-release-build)VSC + Feed
**.NET Core SDK (CLI) Version**: 3.0.100-preview9-014004
**.NET Core runtime Version**: 3.0.0-preview9-19423-09

**Testcases Affected:** [[3.0] SimpleWebAppWithServerSideBlazorIndAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.3/E2EWalkthroughs/VS/AspNetCore30/30_SimpleWebAppWithServerSideBlazorIndAuth.md) 

**Regression Info:** It doesn't repro with 3.0 preview 6 but repro with 3.0 preview 8.

**Install Steps**

1. Clean machine: Win10 x64 ENU 19H1
2. Install Dev16.4 preview 1(master-29302.5)VSC 

   - Run preinstall.cmd: \\\vspreinstall\preinstall\preinstall.cmd
   - Install from [here](https://aka.ms/vs/16/int.master/vs_community.exe)
   - Select NET Core + .NET Desktop workload
   - Check .NetCore 2.2 Runtime under IC tab
   - Add feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/3.0.0-preview9-014004/nuget/v3/index.json

**Repro Steps**

1. File > Create a new project > Blazor App > **Blazor Server App with IndAuth** > Create
2. F5 > Register a new user> Click the user name on the top-right corner of browser> Click Logout, it doesn't work.

**Note:** It works fine in Home page, if you don't click the user name.

**ACTUAL:** 
After clicking Logout:
![图片](https://user-images.githubusercontent.com/31497677/64158682-82a22e00-ce6b-11e9-9ffd-29b3677a42fe.png)

_Copied from original issue: aspnet/AspNetCore-ManualTests#16_

**Comment by danroth27** [comment]
_From @mkArtakMSFT on Tuesday, September 3, 2019 3:20:57 PM_

@javiercn can you please investigate this? Thanks!

**Comment by danroth27** [comment]
_From @javiercn on Tuesday, September 3, 2019 4:15:17 PM_

This is a bug on the template.

/Areas/Identity/Shared/_LoginPartial.cshtml should have the content below. (With a form instead of a link)

```
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<ul class="navbar-nav">
@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a  class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
    </li>
    <li class="nav-item">
        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/" method="post">
            <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
    </li>
}
</ul>
```

This is the piece we need to change
```
        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/" method="post">
            <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
```

**Comment by danroth27** [comment]
_From @javiercn on Tuesday, September 3, 2019 4:16:41 PM_

@mkArtakMSFT @danroth27 We can fix this in 3.1, the workaround is described above. We can add it to the list of known issues.

Can you move it to the asp.net core repo?

**Comment by mkArtakMSFT** [comment]
@javiercn how is this not impacting non-blazor scenarios? Or does it?

**Comment by mkArtakMSFT** [comment]
Also, @javiercn if this is pure Identity change - you can hand it off to @HaoK to handle as part of the other Idenitty related changes for 3.1.

**Comment by javiercn** [comment]
@mkArtakMSFT This is a template change. The _LoginPartial.cshtml is incorrect in the Blazor server-side template.
