### ISSUE TITLE
Form Components throw error on Blazor with Preview 8 build

### ISSUE THREAD

**Issue by dmarsh12** [aspnet/AspNetCore#13674]
### Describe the bug
Since updating to Preview 8, the form components Intellisense is showing that the <Input...> for <InputNumber>, <InputDate>, and <InputSelect> as an error. However, the project is able to build and run without any issues. The exact error message is: "The type of component <InputSelect> cannot be inferred based on the values provided. Consider specifying the the type arguments directly using the following attributes: 'T'". It also makes the project display a huge list of errors.

![image](https://user-images.githubusercontent.com/6718658/64260944-b88df380-cef9-11e9-9fde-0ea0aaf97cc0.png)

![image](https://user-images.githubusercontent.com/6718658/64261072-f0953680-cef9-11e9-8eba-73d046ab2bf2.png)

### To Reproduce
1. Create new preview 8 blazor server application using dotnet new blazorserver.
2. Add an InputSelect, InputNumber, or InputDate component
3. Errors will appear but project will be able to build and run as normal.

### Expected behavior
Inputs will be mapped without any issue/errors. 

### Additional context
![image](https://user-images.githubusercontent.com/6718658/64260612-2e458f80-cef9-11e9-97a6-93c7699be6b1.png)

![image](https://user-images.githubusercontent.com/6718658/64260798-85e3fb00-cef9-11e9-8a4b-8ef579a2e3d3.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dmarsh12.
Please make sure you're using the latest VS 2019 Preview release.
