### ISSUE TITLE
Razor Pages - Anchor tag helper not finding named page 

### ISSUE THREAD

**Issue by adexios** [aspnet/AspNetCore#13684]
I have a page with the path "Orders/Dashboard" which I have shortened to "/dashboard" using the @page directive.

I tried putting in a link <a asp-page="dashboard">Dashboard</a> but the tag helper isn't resolving the page. However, if I put in <a asp-page="/Orders/Dashboard">Dashboard</a> it'll work fine.

I noticed that two pages in the same folder will recognize each other using the @page name, but if they are in different folders it no longer works.

I could be mistaken, but I believe that tag helpers should recognize custom @page names, because then the anchor tag helpers wouldn't need updated when the folder structure of a project changes.

Thanks in advance!
- Paul

**Comment by pranavkm** [comment]
I'm assuming you're talking about the value for `asp-page` property of the anchor TagHelper. 

`asp-page` takes either an absolute page name such as `/Orders/Dashboard` or a relative name such as `Dashboard` or `../DifferentDirectory/Dashboard`. Note that the value is always a page name (derived from the path relative to the `/Pages` directory) and not the route which is the value you can optionally specify in `@page "{route}"`.
