### ISSUE TITLE
how to call an ASP.NET c# method using javascript

### ISSUE THREAD

**Issue by alimuzzaman** [aspnet/AspNetCore#13683]
https://stackoverflow.com/questions/7089760/how-to-call-an-asp-net-c-sharp-method-using-javascript#answer-7089956

Is what they did is doable in ASP.NET Core?

> [WebMethod]
public static string RegisterUser(string email, string password){}

>         PageMethods.RegisterUser(email, password, onSucess, onError);

Is there any extension/something available for something similar?

I just don't want to mingle with AJAX myself.
I just want to call a C# method from JS and expect it to return a value or promise at least.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @alimuzzaman .
The suggested approach there is fine. You will need to expose an API and call it from JavaScript using some http library yourself.
