### ISSUE TITLE
Preview-9 where is AddComponent? Disable server side pre-rendering

### ISSUE THREAD

**Issue by alexandrereyes** [aspnet/AspNetCore#13685]
I'm trying to disable server side pre-rendering on preview-9: https://github.com/aspnet/AspNetCore/issues/9584 
but AddComponent doesn't exists anymore, what should I do ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @alexandrereyes.
This is documented in https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/#multiple-components-in-views-or-pages
You should now call the `Html.RenderComponentAsync<TComponent>` with `RenderMode.Server` flag.

**Comment by srowan** [comment]
Does this mean there is no longer any support for interactive components on a static page? (as laid out by @javiercn as the last scenario in #8911)

**Comment by srowan** [comment]
@mkArtakMSFT i.e. can you please comment on whether there is still a way to do this without `cshtml` ?

**Comment by javiercn** [comment]
There is no support for using html pages as an entry point for server-side blazor. A razor view/page is required as the entry point for the app.
