### ISSUE TITLE
Can't build from source on Windows

### ISSUE THREAD

**Issue by kg** [aspnet/AspNetCore#13686]
### Describe the bug
I followed the steps in https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md to build from source but can't get past the SDK requirement.

### Screenshots
![image](https://user-images.githubusercontent.com/198130/64294053-cc9a1b00-cf22-11e9-9545-d10b4726dfbc.png)

### Additional context
I've tried a few additional troubleshooting steps:
* A full update of VS2019
* Installed the latest 3.x and 5.x netcore SDKs (for the latter, 5.0.100-alpha1-014044)
* Ran ```./eng/scripts/InstallVisualStudio.ps1``` and ```./eng/scripts/InstallJdk.ps1```. I should note the former only tried to install the 2.0 and 2.1 netcore SDKs (????)
* Installed latest nodejs and confirmed that it works
* Ran ```build.cmd -restore```

Do I specifically need sdk rev 13788?

### dotnet info
```
Host (useful for support):
  Version: 5.0.0-alpha1.19454.5
  Commit:  33d05af6ff

.NET Core SDKs installed:
  1.0.3 [c:\program files\dotnet\sdk]
  1.0.4 [c:\program files\dotnet\sdk]
  1.1.0 [c:\program files\dotnet\sdk]
  2.1.3 [c:\program files\dotnet\sdk]
  2.1.4 [c:\program files\dotnet\sdk]
  2.1.200-preview-007474 [c:\program files\dotnet\sdk]
  2.1.201 [c:\program files\dotnet\sdk]
  2.1.300-preview2-008324 [c:\program files\dotnet\sdk]
  2.1.401 [c:\program files\dotnet\sdk]
  2.1.507 [c:\program files\dotnet\sdk]
  2.1.508 [c:\program files\dotnet\sdk]
  2.1.800-preview-009696 [c:\program files\dotnet\sdk]
  2.2.400-preview-010219 [c:\program files\dotnet\sdk]
  3.0.100-preview9-014004 [c:\program files\dotnet\sdk]
  5.0.100-alpha1-014044 [c:\program files\dotnet\sdk]
```

**Comment by kg** [comment]
I should also note that the VS2019 option to enable preview SDKs is missing for me.
![image](https://user-images.githubusercontent.com/198130/64294336-64980480-cf23-11e9-921c-573f1062c400.png)

**Comment by pranavkm** [comment]
This issue was moved to dotnet/arcade#4196
