### ISSUE TITLE
Blazor .NET Core 3 preview 9: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering'

### ISSUE THREAD

**Issue by mclean25** [aspnet/AspNetCore#13695]
Following [the guide here](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli), I immediately get an error when trying to run the app.

```
dotnet --version
3.0.100-preview9-014004  

dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview8.19405.7
dotnet new blazorwasm -o WebApplication1
dotnet run

obj\Debug\netstandard2.0\RazorDeclaration\Shared\MainLayout.razor.g.cs(49,91): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?) [C:\Users\AlexMcLean\git\WebApplication1\WebApplication1.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\App.razor.g.cs(49,91): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?) [C:\Users\AlexMcLean\git\WebApplication1\WebApplication1.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Shared\NavMenu.razor.g.cs(49,91): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?) [C:\Users\AlexMcLean\git\WebApplication1\WebApplication1.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Shared\SurveyPrompt.razor.g.cs(49,91): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?) [C:\Users\AlexMcLean\git\WebApplication1\WebApplication1.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Index.razor.g.cs(51,91): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?) [C:\Users\AlexMcLean\git\WebApplication1\WebApplication1.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\FetchData.razor.g.cs(51,91): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?) [C:\Users\AlexMcLean\git\WebApplication1\WebApplication1.csproj]
obj\Debug\netstandard2.0\RazorDeclaration\Pages\Counter.razor.g.cs(51,91): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?) [C:\Users\AlexMcLean\git\WebApplication1\WebApplication1.csproj]

The build failed. Fix the build errors and run again.
```

Is it because  the link to the templates should be updated?

**Comment by unencode** [comment]
The breaking changes announced here https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/ are the likely cause.

I'm working through some similar issues and updating a few existing projects.

**Comment by Eilon** [comment]
You need to update Visual Studio to the latest preview release that came out today. I ran into this exact thing and was assisted by the friendly Blazor engineers. Once I updated, everything worked!

**Comment by mclean25** [comment]
I guess this might have been going through the pipeline while I posted this, as I had suspected the templates needed to be updated to reflect that .NET Core 3.0 preview 9 was out now (and what I had installed).

`dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview9.19424.4`

Thus, you _do not_ need to update to the latest Visual Studio (for anyone like me who's trying to move away from VS and towards VS Code).

**Comment by AdamBorg** [comment]
Im still getting this issue when upgrading any other suggestions ?

**Comment by RealTadango** [comment]
Strange. I updated VS to 16.3 Preview 3, updated the template but still the error remains. Even a new clean Blazor app has the same issue. What am i missing?

**Comment by Adam-Miettinen** [comment]
I was in the same boat as RealTadango, but running the command that mclean25 posted to update the templates fixed it for me.

**Comment by frablaser** [comment]
The easy way is to update the Packages via NuGet

**Comment by RealTadango** [comment]
The issue is that a Preview 8 project will not work with VS 16.3.0 Preview 3.0 no matter what you install. Sadly i cannot use Preview 9 and am now stuck.

**Comment by Eilon** [comment]
@RealTadango why can't you use Preview 9?

**Comment by RealTadango** [comment]
> @RealTadango why can't you use Preview 9?

Incompatibel library (is on Preview 8)

**Comment by mclean25** [comment]
@RealTadango have you tried just using the `dotnet` cli to instantiate your project instead of VS? I did that for preview 8 (with the preview 8 templates) and it worked fine for me the other day.

**Comment by RealTadango** [comment]
No, i only used the template through VS. Should that make a difference? My existing project is the issue :)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Using a version of SDk with a different version of the Blazor templates is not supported. Make sure you use the latest version of the SDK, runtime and the VS 2019 Preview.

**Comment by RealTadango** [comment]
@mkArtakMSFT But i hade installed finally:
 - Core SDK Preview 8
 - Template versie Preview 8
 - VS 16.3.0 Preview 3.0
 - Project with references to Preview 8 packages

This does not work.

**Comment by Eilon** [comment]
Right, I think you need to stack with the older VS, or newer Blazor.

**Comment by mkArtakMSFT** [comment]
> Right, I think you need to stack with the older VS, or newer Blazor.

Correct. You should use all the new stack. Using the latest VS with a version older SDK is also not supported.

**Comment by DataJuggler** [comment]
I read the upgrade docs, but after many failed attempts I upgraded my Preview 8 to Preview 9 project by creating a new Blazor project, and added all my pages, css,images and other changes manually was the only way I could get it to work.

**Comment by Eastop** [comment]
I had similar issues. I had to replace Microsoft.AspNetCore.Components.Rendering with Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder and it worked for me

**Comment by DataJuggler** [comment]
Thanks. I already rebuilt manually, but that is good to know. Hopefully once the full version comes out this won't be a problem any more.

**Comment by msollicito** [comment]
So I am using dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview9.19424.4
and this sdk 
![image](https://user-images.githubusercontent.com/187311/66662400-bca6e280-ec16-11e9-865b-8aa9c2a19646.png)
with the latest version of visual studio preview that I just downloaded 
still got this problem with a newly created project
Help!

**Comment by DataJuggler** [comment]
Visual Studio is not in Preview at the moment, so if you just got it you installed the right place.

Here is the Visual Studio I installed yesterday in Help > About:
16.3.4

Is this the same version you are using? If not click the menu item Help > Check For Updates.

When I create a new Blazor project, I just use Visual Studio and select new project > Blazor App.

Not sure if that helps any, here is a video I made creating a Blazor project if you want to watch: 

(I think the Blazor create project part is in the second half, but I don't have time to watch right now.)
https://www.youtube.com/watch?v=sowTLLeAfm8

**Comment by MarkusRodler** [comment]
Maybe I can help with that issue (or I have a similiar one).
I am trying to build my app within a docker container. I developed it with my Win 10 x64 PC on the command line.
No issues so far.
But with this simple dockerfile i get the same Errors as in the first post.
```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS dotnet

WORKDIR /app
COPY /src /app
RUN dotnet publish -c Release

Failing part of the log output:
```shell
Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 6.02 sec for /app/Dark.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
/build/obj/Release/netstandard2.0/RazorDeclaration/App.razor.g.cs(61,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [/app/Dark.csproj]
/build/obj/Release/netstandard2.0/RazorDeclaration/Component/Index/Index.razor.g.cs(62,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [/app/Dark.csproj]  
```

This is Happening with the alpine version of the sdk. If I use the "normal" one everything works as expected:
```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS dotnet
```

**Comment by pranavkm** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
