### ISSUE TITLE
Expose WebAssemblyHost services to startup

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#13694]
The Blazor WebAssembly host sets up a bunch of services that we should make available in `Startup` (ex `IJSRuntime`).

**Comment by danroth27** [comment]
An example customer request for this is wanting to get access to the browser URL in ConfigureServices to setup different configurations for different environments.

**Comment by RemiBou** [comment]
I was able to setup configuration using url using service and app builder (https://remibou.github.io/Configuring-a-Blazor-app/) and deferring the singleton initialization, but it might help if I could init everything in ConfigureService.

**Comment by ghidello** [comment]
@RemiBou thanks! Using the app builder did the trick and I have access to the NavigationManager.
In my specific case I need the app URL for configuring the callback URLs for an OpenId connect client. 

More in general, though, having a way for performing some environment sensitive configurations in blazor wasm, like the server api URL or the logging level, will be very important and using the current URI was a quick way to achieve it. So, probably, now what I'm actually asking is: do we have any way for configuring a blazor wasm application other than inspecting the current URL?

**Comment by RemiBou** [comment]
Well if you ask me no : the uri is like the command line that run the app. In aspnet coee you can use environment variable or command line param but in blazor client side you can't do anything on the environment.

You could deploy different artifact in your environments but IMHO this is not a good practice.

**Comment by arivera12** [comment]
I just got into this issue I tried using IJSRuntime on startup.cs and the app freezes with no error message. Without this there is no way to use configuration files on blazor client side.

**Comment by arivera12** [comment]
@RemiBou maybe (Haven't tested) your approach works for the version you are using on the link provided. But once you upgrade to preview 9. IUriHelper is gone. It was replace with NavigationManager, I still tried to inject NavigationManager on startup but it gaves me the same result. It seems that NavigationManager is not available on application startup.

**Comment by arivera12** [comment]
@ghidello can you share a snip of code how to make the navigation manager work with the app builder on startup.cs?

**Comment by arivera12** [comment]
@ghidello I found the solution.
@RemiBou you should updte your article with this change to make it work with preview 9.
```
//Where s is type of IServiceProvider.
var baseUri = s.GetService<NavigationManager>().BaseUri; 
```

**Comment by ghidello** [comment]
@arivera12 that’s how I got the url

**Comment by mkArtakMSFT** [comment]
We're going to handle this as part of https://github.com/aspnet/AspNetCore/issues/16874
