### ISSUE TITLE
DataProtection Package is unusable in 3.0

### ISSUE THREAD

**Issue by smitpatel** [aspnet/AspNetCore#13696]
https://github.com/aspnet/AspNetCore/blob/3dee6782c3f8d611b3cda871b97778a34121df83/src/DataProtection/EntityFrameworkCore/src/EntityFrameworkCoreXmlRepository.cs#L41-L48

Query above uses a client method in projection
Client method is instance method, hence the object of enclosing class would end up in EF Core query cache.
https://github.com/aspnet/AspNetCore/blob/3dee6782c3f8d611b3cda871b97778a34121df83/src/DataProtection/EntityFrameworkCore/src/EntityFrameworkCoreXmlRepository.cs#L68-L79

The repository contains IServiceProvider & ILogger which will cause memory leak.

In 3.0, EF Core started throwing exception for potential code which can cause such leak. Which generated https://github.com/aspnet/EntityFrameworkCore/issues/17623#issuecomment-528133045 from customer.
So currently, this code path is unusable and there is no way for customers to work-around it.

**Comment by smitpatel** [comment]
Also given that it was not captured in any tests in the repo, there is lacking test coverage on this code path.

**Comment by blowdart** [comment]
@Pilchie / @anurse  no-one is a data protection dev right now. Can you assign someone?

**Comment by jkotalik** [comment]
The data protection package doesn't seem to have any true "functional" tests with EF. We use a test DataProtectionKeyContext https://github.com/aspnet/AspNetCore/blob/master/src/DataProtection/EntityFrameworkCore/test/DataProtectionKeyContext.cs#L8-L13. 

As this issue seems high priority, I can look at it.
