### ISSUE TITLE
Issues with generated layout after using Identity scaffolder in Blazor Server app project

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#13699]
Repro steps:
- Create a new Blazor Server app with authentication using individual user account
- Run the Identity scaffolder
  - Override all files
  - Select the existing DB context
- Build the app

Expected result:
- Builds successfully
- Layout matches layout from default ASP.NET Core Web App

Actual result:

In *_Layout.cshtml*:

The type or namespace name 'IWebHostEnvironment' could not be found (are you missing a using directive or an assembly reference?)

Layout hasn't been updated yet to remove the use of CDNs and environment tag helper as was done in the default ASP.NET Core Web App

**Comment by danroth27** [comment]
@vijayrkn @HaoK

**Comment by danroth27** [comment]
Also the cookie consent UI is still being generated.

**Comment by HaoK** [comment]
Looks like there's special code in the scaffolding code for the cookie consent stuff @vijayrkn 

https://github.com/aspnet/Scaffolding/blob/167a8b5c626db13896e1e4fad65b5695be37da20/src/VS.Web.CG.Mvc/Identity/IdentityGeneratorFilesConfig.cs#L281

But the pr removes the explicit partial

**Comment by digitalsigi** [comment]
Same with me, but found reason.
Scaffolding inserts incomplete line in ~\Pages\Shared\_Layout.cshtml:
```
Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine

....
```
but should  read

```
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
```

**Comment by amir6mehrabi** [comment]
> Same with me, but found reason.
> Scaffolding inserts incomplete line in ~\Pages\Shared_Layout.cshtml:
> 
> ```
> Microsoft.AspNetCore.Hosting
> @using Microsoft.AspNetCore.Mvc.ViewEngines
> @inject IWebHostEnvironment Environment
> @inject ICompositeViewEngine Engine
> 
> ....
> ```
> 
> but should read
> 
> ```
> @using Microsoft.AspNetCore.Hosting
> @using Microsoft.AspNetCore.Mvc.ViewEngines
> @inject IWebHostEnvironment Environment
> @inject ICompositeViewEngine Engine
> ```

tnx a lot.
u saved my day.

**Comment by ichensky** [comment]
Will Identity scaffolder generate Blazor pages instead of RazorPages in the future?
