### ISSUE TITLE
ServerSideBlazor's component inside razor page (Route data) Preview 9

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#13697]
Before Preview 9 we could pass a blazor component, the parameters needed for it to work from a razor page.

For example, a razor page with the following URL: test.com/{param1} could read the param1 value and pass it to the embedded blazor component for it to work.

Now with stateful prerendering discarded, what would be the recommended way for a blazor component inside a razor page to read route data?

Thanks & Regards!!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrdlx.
You can use NavigationManager inside your component to read URL and make it available to the component. However, we don't have a mechanism to pass parameters to components from pages directly.
