### ISSUE TITLE
Blazor AOT WASM Compilation 

### ISSUE THREAD

**Issue by legistek** [aspnet/AspNetCore#13690]
I hope I'm not duplicating an existing issue but I couldn't find any standing open issue on this.

Where do things stand with client-side Blazor and ahead of time (AOT) compilation to WASM? I feel like this has not been mentioned by anyone in a very long time. Is it even in the roadmap?

Blazor server-hosted (SignalR) performance is very good, but client-side is still unacceptable unfortunately.

Thanks for any info.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is actually something we do track https://github.com/aspnet/AspNetCore/issues/5466

**Comment by legistek** [comment]
Sorry, I don't know how I missed that! Thank you
