### ISSUE TITLE
Preview 9 - Cannot find `IComponentContext` anymore

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore#13703]
Has it been removed from the api?

**Comment by akorchev** [comment]
Yes, they removed it. Not sure how one can detect prerendering mode now. Some features such as IUriHelper.Navigate don't work in prerendering mode.

**Comment by Legends** [comment]
Ah ok, thanks.
AFAIK IUrihelper is now replaced by NavigationManager
