### ISSUE TITLE
cannot convert lambda expression to type 'EventCallback' because it is not a delegate type

### ISSUE THREAD

**Issue by schmitch** [aspnet/AspNetCore#13704]
currently preview9 EventCallbacks for onclick handlers do not work as expected:

```
<ul class="list-group">
@foreach (var project in _projects)
{
    <li class="list-group-item @(_activeProject?.Id == project.Id ? "active" : string.Empty)" @onclick="@(() => SelectProject(project))"> <!-- @(e => doesn't work, too, or trying to use an async variant: @(async => await SelectProject)
       @project.Name
    </li>
}
</ul>

@code
{
    private async Task SelectProject(GitlabProject project)
    {
    }
}
```

will raise
`cannot convert lambda expression to type 'EventCallback' because it is not a delegate type`
(https://docs.microsoft.com/de-de/aspnet/core/blazor/components?view=aspnetcore-3.0#lambda-expressions)

**Comment by royzhang2016** [comment]
To fix this migration issue, you may need to add below line to the _Imports.razor file

@using Microsoft.AspNetCore.Components.Web;

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @schmitch.
@royzhang2016 's proposal should fix your issue.

**Comment by Grauenwolf** [comment]
I'm still seeing that error message despite having that using statement. Are there any other possible causes?

**Comment by Grauenwolf** [comment]
I'm still seeing that error message despite having that using statement. Are there any other possible causes?

Error	CS1660	Cannot convert lambda expression to type 'object' because it is not a delegate type

**Comment by hieu-n** [comment]
@Grauenwolf I had the same error. It turned out, I missed "@" before the "onclick". So it must have two "@": `...@onclick="@( ... )..`
