### ISSUE TITLE
dotnet core doesn't let me set the processPath in published web.config

### ISSUE THREAD

**Issue by Launster** [aspnet/AspNetCore#13708]
# A little context 
I develop in local and test on a personnal VM, so I publish my project to this VM when I test (which use IIS, with the full hosting bundle).
We need to use the x86 dotnet, but we doesn't want to touch the path of the production server. So we need to set the process path to the x86 dotnet. We did that by removing the generating of the web.config and we set the processpath. It works. (we do a "dotnet publish" of the project in a folder)

# The problem
Now my problem is for the development configuration. Since we desactivated the generation of the web.config, I can't set the development var in the web.config 
```<environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />```
And I need to def the processpath like this : 
```<aspNetCore processPath="%ProgramFiles(x86)%\dotnet\dotnet" arguments=".\MyApp.dll"/>```

# Here what I tried
* Reactivate the generating of the web.config and fixing the dotnet core to use the x86 one --> this would be the best in my opinion
* Use different web.config according to the configuration --> didn't succeed but I am not a pro of the msbuild tool

### Additionnal info/thougth
* launchSettings.json seems to be useless since I need to publish on my dev VM 
* Not a regular of creating issues, if you have feedback on how to format/ask question, let share your advices :slightly_smiling_face:

**Comment by shirhatti** [comment]
If you have all the correct settings in the local web.config, then you can disable the web.config transform  during publish by setting this property in csproj/profile.
 
<IsWebConfigTransformDisabled>true</ IsWebConfigTransformDisabled>

**Comment by shirhatti** [comment]
Feel free to re-open if you have more questions

**Comment by Launster** [comment]
Well, I don't have all good settings. I need to have 
```<environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />```
in the web.config when I am in debug (and only in debug) and *I can not commit this in my repo*.
So, I need to generate the web.config as it is different in debug and release.
**But** I need to use the 32bits dotnet core. And generating the web.config use 
```processPath="dotnet"```
instead of 
```processPath="%ProgramFiles(x86)%\dotnet\dotnet"```
Maybe there isn't any solution and I should do a feature request ? (I can not modify the path var)

**Comment by shirhatti** [comment]
I'm assuming the naive solution of just ensuring the 32-bit dotnet appears first on your PATH and hence is used isn't a viable solution for you?

You can still achieve whatever you're trying to do via a web.config XDT transforms.
@vijayrkn Is this still the best [link](https://github.com/vijayrkn/webconfigtransform/blob/master/README.md) or do the docs live elsewhere now?

As for your specific ask of preserving one property but transforming the rest of the `web.config` won't meet the bar for a new feature request.

**Comment by Launster** [comment]
So, some news : 
Settings the 32 bits path first was not my wish as it make my VM different than the production (and would create problem if I will need a new .Netcore 64 bits website). 

Using XDT transforms perfectly meet my needs ! Thank you for your reponses. 😃
