### ISSUE TITLE
KeyLengthLimit does not support int.MaxValue in Preview 9

### ISSUE THREAD

**Issue by rybkov** [aspnet/AspNetCore#13719]
### Describe the bug
After update to Preview 9 cannot submit form if KeyLengthLimit set to int.MaxValue 

### To Reproduce
1. Using this version of ASP.NET Core '3.0.0-preview9.19424.4'
2. Create Default MVC application
3. Create form
4. In services setup 
`Services.Configure<FormOptions>( Options => Options.ValueLengthLimit = int.MaxValue );
            Services.Configure<FormOptions>( Options => Options.ValueCountLimit = int.MaxValue );
            Services.Configure<FormOptions>( Options => Options.KeyLengthLimit = int.MaxValue );`
3. Submit a form
4. See error Form key length limit 2147483647 or value length limit 2147483647 exceeded.

### Workaround
Setup values to 1_009_100_000 (they might be bigger, but 1_090_000_000 does not work already)

### Expected behavior
Preview 8 did not have that issues

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
The preview9 change is here: https://github.com/aspnet/AspNetCore/pull/12749/files

You may be hitting an issue [here](https://github.com/aspnet/AspNetCore/pull/12749/files#diff-f44d0d010602be96c8821603bcd529ccR170) or [here](https://github.com/aspnet/AspNetCore/pull/12749/files#diff-f44d0d010602be96c8821603bcd529ccR239) were the parser isn't sure yet if it's a measuring a key or value so it adds the limits together. When the limits are both set to int.MaxValue it would overflow and become negative, causing the length check to fail.

Mitigation: Set the limits so their combine size is less than or equal to int.MaxValue.

Did you set int.MaxValue in an attempt to disable the limits? Disabling the limits is strongly discouraged.

**Comment by rybkov** [comment]
Thank you @Tratcher!
We did not disable it - just in process of migrating 4.7 to Core 3 and setup as it was before.
The limits are pretty high, so we are good and can close the issue.

**Comment by Tratcher** [comment]
I'll leave it open so we can confirm and address the overflow issue.

**Comment by shirhatti** [comment]
Given that there's a  trivial workaround for this, we're targeting 5.0 for this

**Comment by davidfowl** [comment]
This should have been nullable.

**Comment by Tratcher** [comment]
*shrug* turning it off is a pretty bad idea.

**Comment by davidfowl** [comment]
And setting it to int.MaxValue isn’t 😆

**Comment by Tratcher** [comment]
@anurse, this is a regression that should be addressed in 3.1.

**Comment by anurse** [comment]
Clearing milestone so we hit it in triage.
