### ISSUE TITLE
Question: How to upgrade JSRuntime.SetCurrentJSRuntime(Js); to preview9?

### ISSUE THREAD

**Issue by SeppPenner** [aspnet/AspNetCore#13714]
How do we upgrade `JSRuntime.SetCurrentJSRuntime(Js);` from preview8 to preview9? Or is this something that is not needed anymore?

**Comment by pranavkm** [comment]
>  Or is this something that is not needed anymore?

If you were using the API as a workaround for #11159, you should no longer need it since we addressed the issue. If that wasn't the case, could you elaborate what you were trying to do?

**Comment by SeppPenner** [comment]
I was just curious to help updating https://github.com/SamProf/MatBlazor to preview9, where this code was used, but @SamProf has already done that, so the issue is not relevant anymore :)
