### ISSUE TITLE
CascadingParameter not working with AddAttribute() in p9

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#13712]
I have upgraded my project to preview 9 and now I'm stuck on this. Some of my component have custom implementation that will override default _html/razor_ implementation.

An example of razor syntax that can override default html:

```
@inherits BaseBarToggler
@if ( !HasCustomRegistration )
{
    <a role="button" class="@ClassMapper.Class" @onclick="@ClickHandler">
        @ChildContent
    </a>
}
else
{
    @RenderCustomComponent()
}
```

The problem occurs when I build the render tree manually where I need to pass cascade parameter. It is not injected or recognized by the tree builder.

This is the part that is responsible for building the custom component. One of those IS actually a cascaded value. The same code can be found [here](https://github.com/stsrki/Blazorise/blob/3b83e061655190209c0ea3f576f4f99f07eeb266/Source/Blazorise/BaseComponent.cs#L129)

```
protected RenderFragment RenderCustomComponent() => builder =>
{
	builder.OpenComponent( 0, ComponentMapper.GetImplementation( this ) );

	foreach ( var parameter in parameters )
	{
		builder.AddAttribute( 1, parameter.Name, parameter.Value );
	}

	builder.CloseComponent();
};
```

The component I want to render **DOES** have cascade parameter specified:

` [CascadingParameter] public BaseBar ParentBar { get; set; }`

**Actual error:**

> blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM: System.InvalidOperationException: Object of type 'Blazorise.Bootstrap.BarToggler' has a property matching the name 'ParentBar', but it does not have [ParameterAttribute] applied.
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForSettingCascadingParameterWithNonCascadingValue (System.Type targetType, System.String parameterName) <0x2488820 + 0x00050> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties (Microsoft.AspNetCore.Components.ParameterView& parameters, System.Object target) <0x20f2970 + 0x0012c> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties (System.Object target) <0x20f2028 + 0x0001e> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync (Microsoft.AspNetCore.Components.ParameterView parameters) <0x20f1f48 + 0x00008> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Blazorise.BaseComponent.SetParametersAsync (Microsoft.AspNetCore.Components.ParameterView parameters) [0x00021] in D:\Projects\Other\Blazorise\Source\Blazorise\BaseComponent.cs:122 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters (Microsoft.AspNetCore.Components.ParameterView parameters) <0x20f1c88 + 0x0008e> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame (Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x2115988 + 0x00082> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree (Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x2115798 + 0x00082> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame (Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 newFrameIndex) <0x2115488 + 0x000c2> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame (Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 newFrameIndex) <0x2115488 + 0x0015c> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange (Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 oldStartIndex, System.Int32 oldEndIndexExcl, System.Int32 newStartIndex, System.Int32 newEndIndexExcl) <0x21147e0 + 0x00490> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff (Microsoft.AspNetCore.Components.RenderTree.Renderer renderer, Microsoft.AspNetCore.Components.Rendering.RenderBatchBuilder batchBuilder, System.Int32 componentId, Microsoft.AspNetCore.Components.RenderTree.ArrayRange`1[T] oldTree, Microsoft.AspNetCore.Components.RenderTree.ArrayRange`1[T] newTree) <0x2110b28 + 0x0009e> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Components.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Components.RenderFragment renderFragment) <0x2106410 + 0x000ea> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Components.Rendering.RenderQueueEntry renderQueueEntry) <0x2101d48 + 0x0004e> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1
> blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue () <0x21013b8 + 0x000b2> in <cc81133ac6304aada69282c517e2b811>:0 
> d.printErr @ blazor.webassembly.js:1

**Edit***
If anyone want's to try it, the example is on the [dev084 branch of Blazorise](https://github.com/stsrki/Blazorise/tree/dev084)

**Comment by stsrki** [comment]
I have tried to skip the cascading parameters and it seems now everything works. 

```diff
protected RenderFragment RenderCustomComponent() => builder =>
{
    builder.OpenComponent( 0, ComponentMapper.GetImplementation( this ) );

    foreach ( var parameter in parameters )
    {
+        if ( parameter.Cascading )
+            continue;

        builder.AddAttribute( 1, parameter.Name, parameter.Value );
    }

    builder.CloseComponent();
};
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @stsrki.
You actually found a workaround which solved your problem, that's great. For context, this was an intentional change as we no more allow parameters to be passed to child components be named exactly as the cascading parameters these components accept.

**Comment by stsrki** [comment]
Just FYI. It would be great if there is a release notes for these kind of stuff that are changed and that can affect us in some way.

I know we can track issues but it's not very user-friendly to understand everything by checking them. 

So some kind of release notes or change log would be great and would make our lives easier.

For example I find these kind of release notes fascinating: https://docs.unrealengine.com/en-US/Support/Builds/ReleaseNotes/4_23/index.html
