### ISSUE TITLE
Question: How to replace IComponentContext when upgrading from preview8 to preview9?

### ISSUE THREAD

**Issue by SeppPenner** [aspnet/AspNetCore#13711]
Not actually a bug report, but a question. What are the suggested changes to upgrade usages of `IComponentContext`  from preview8 to preview9?

It's not present in `Microsoft.AspNetCore.Components` anymore.

**Comment by SeppPenner** [comment]
I just found out from https://github.com/SamProf/MatBlazor/issues/232#issuecomment-528362115 that this isn't needed anymore and can be removed? Am I right?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SeppPenner .
We no longer call `OnAfterRender` during prerendering, so yes, that check is not needed any more.

**Comment by SeppPenner** [comment]
Ok, thanks for the fast reply :)
