### ISSUE TITLE
Event based state changes of hub connection

### ISSUE THREAD

**Issue by daimoonis** [aspnet/AspNetCore#13717]
### Is your feature request related to a problem? Please describe.
Hello, I am trying to monitor HubConnection state changes (https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/ts/signalr/src/HubConnection.ts) and trigger some actions based on it. I am using rxjs library, but i was not successful to monitor all changes correctly.

**For example trying to monitor initial start sequence is not easy task for me:**
```
import { HubConnection, HubConnectionState } from '@microsoft/signalr';
hubConnection: HubConnection; // just typed example, imagine an instance
hubConnection.start();
// it goes through these states (happy path): 
// HubConnectionState.Connecting
// HubConnectionState.Connected
```

### Describe the solution you'd like
I would like if the library would emit state change events or allow to register handles for such changes, see examples below.

At the end i would like to end up with something like this or something similar:
```
import { Subject } from 'rxjs';
import { HubConnection, HubConnectionState } from '@microsoft/signalr';
hubConnection: HubConnection; // just typed example, imagine an instance
myConnectionStateSubject = new Subject<HubConnectionState>();
hubConnection.stateChanges(myConnectionStateSubject);
```
or
```
import { Subject } from 'rxjs';
import { HubConnection, HubConnectionState } from '@microsoft/signalr';
hubConnection: HubConnection; // just typed example, imagine an instance
myConnectionStateSubject = new Subject<HubConnectionState>();
hubConnection.stateChanged((state: HubConnectionState) => {
            myConnectionStateSubject.next(state);
});
```
I have tried to use some methods on connection:
```
connection.onclose((error?: Error) => {
    // some action
});
connection.onreconnected((connectionId?: string) => {
    // some action
});
connection.onreconnecting((error?: Error) => {
    // some action
});
// but i am missing callbacks based on all hub connection statuses like "onconnected", ondisconnected etc.
```
I have tried some dirty solutions such this:
```
import { timer } from 'rxjs';
import { map, distinctUntilChanged } from 'rxjs/operators';
timer(0, 100).pipe(
            map(() => {
                return this.connection.state;
            }),
            distinctUntilChanged()
        ).subscribe((state) => {
            console.log(state);
        });
```
But it does not seem right to me as it is based on some time/non relevant assumption.

### Additional context
I am using npm client package: "@microsoft/signalr": "3.0.0-preview8.19405.7".

**Comment by BrennanConroy** [comment]
Could you please describe your scenario and why you care about the internal state changes?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
