### ISSUE TITLE
Question: How to update EditContext.FieldClass from preview8 to preview9?

### ISSUE THREAD

**Issue by SeppPenner** [aspnet/AspNetCore#13713]
How can we update `EditContext?.FieldClass(FieldIdentifier)` from preview8 to preview9? Is `EditContext?.FieldCssClass(FieldIdentifier)` the equivalent?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SeppPenner .
Yes, this was renamed to `FieldCssClass`.

**Comment by SeppPenner** [comment]
Ok, thanks for the fast reply :)
