### ISSUE TITLE
understand the onchange listener to trigger the setter on javascript

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#13732]
Hi guys, i need some explanation about how blazor listen the value change to then execute binding

This question is related to another issue i open https://github.com/aspnet/AspNetCore/issues/13645, mark as closed but definitively not solved (see my last comment)

im facing this same kind of issue with another library, medium editor : https://github.com/yabwe/medium-editor

i will not put all the detail beacause its not important, but i'm unable to trigger the setter of the property bind on a textarea

for example : 
````
<textarea class="editable" id="txtTextePublic" maxlength="3000" rows="8" @bind="Model.EnfNote.TextePublic" />
````

in js, if i'm doing something like that, it's not work, the setter of my property in c# is never called
````
$("#txtTextePublic").val("test").trigger("onchange");
or
$("#txtTextePublic").val("test").trigger("change");
````

so, what i have missed ?

thanks for your help !

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @julienGrd.
Triggering events via jQuery is not the same as triggering via pure JavaScript, and that's what's causing this behavior. Consider using `dispatchEvent` instead from pure JavaScript.

**Comment by julienGrd** [comment]
yeah perfect it works !

so my previous code begin
````
$("#txtTextePublic").val("test")
var event = new Event('change');
$("#txtTextePublic").get(0).dispatchEvent(event);
````

thanks mkArtakMSFT !
