### ISSUE TITLE
Accessing content of PartialView in a Controller

### ISSUE THREAD

**Issue by TwentyFourMinutes** [aspnet/AspNetCore#13736]
### Is your feature request related to a problem? Please describe.
I am sending Emails in my ASP.Net Core MVC (pre-release 9) application. I thought it would be handy to use the Razer Engine since it is already in place and I could really benefit from the razer syntax.

### Describe the solution you'd like
It would be cool if you could use it similar like in a View e.g. `@Html.PartialAsync("")` and having something similar in an Controller.

### Additional context
I already searched for workarounds, but they are all deprecated or for ASP.Net.

**Comment by pranavkm** [comment]
https://github.com/aspnet/Entropy/blob/7a53120c620bbcfd7b54f147c16fa7da1e38d1d4/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs has a sample of using an `IViewEngine` outside of MVC's execution to find and render a view. Perhaps that would help.

**Comment by TwentyFourMinutes** [comment]
Thanks a lot @pranavkm, but it does not work for areas e.g. in the searched locations it does not show the paths from within the area e.g. `Areas/[AreaName]/Views/TheView`

**Comment by pranavkm** [comment]
You'd have to pass it your controller's `ActionContext`: https://github.com/aspnet/Entropy/blob/7a53120c620bbcfd7b54f147c16fa7da1e38d1d4/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs#L38 if you want it do the exact search `ViewResult` would do. Passing an exact path `/Areas/MyArea/Views/TheView.cshtml` should also work.

**Comment by TwentyFourMinutes** [comment]
I already thought it would be something like that, I passed it my `HttpContext`, how would I get the current `ActionContext` from an action then?

**Comment by TwentyFourMinutes** [comment]
Ah, I just used my ControllerContext since it inherits `ActionContext` and it works just fine. Thanks a lot for the help!
