### ISSUE TITLE
Blazor Validation not working on model with over 15 properties

### ISSUE THREAD

**Issue by mgolois** [aspnet/AspNetCore#13735]
I'm currently working  a form in Blazor which needs to be validated and display errors if the form is not valid. My contact(https://blazorconference.azurewebsites.net/contact) page works well validating name, phone, and email. However, the "test" page has a form with over 15 fields; when the user clicks on the submit button, it posts the form skipping all 

Razor Page source code: https://github.com/mgolois/BlazorConference/blob/master/Pages/Test.razor

Class of the model to be validated:
https://github.com/mgolois/BlazorConference/blob/master/Models/BillingInformation.cs 

Web page:
https://blazorconference.azurewebsites.net/test

is it a bug or am I missing something?

**Comment by pranavkm** [comment]
You're likely running in to this issue: https://github.com/aspnet/AspNetCore/issues/10526. https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0#validation-of-complex-or-collection-type-properties has a sample for working around this for 3.0.

**Comment by mgolois** [comment]
@pranavkm I added the RecursiveDataAnnotationsValidator code, but still not working.
I updated my repro with the changes, but it is not validating the form: 
code: https://github.com/mgolois/BlazorConference/blob/master/Pages/Test.razor
webpage: https://blazorconference.azurewebsites.net/test

**Comment by pranavkm** [comment]
@mgolois you'll need to explicitly annotate any property that needs to be recursively validated using the `ValidateRecursive` attribute. For instance, in your case, both these properties https://github.com/mgolois/BlazorConference/blob/master/Models/Registration.cs#L9-L10 would need to be annotated with this attribute.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by mgolois** [comment]
Thank you, @pranavkm & @mkArtakMSFT 
It's working now!!
