### ISSUE TITLE
Preview 8 code broken with newest Visual Studio 2019 16.3 Preview 3

### ISSUE THREAD

**Issue by jonmiller1** [aspnet/AspNetCore#13730]
I just went through the pain of upgrading my project to Preview 8 and everything is working.  I'm trying to get a co-worker to run it as well.  Now that Preview 9 is out when he updates his visual studio 2019 preview he gets the new 16.3 Preview 3 which works with Preview 9 but not Preview 8 projects.  How can I download VS 2019 16.3 Preview 2?!?  I need to get my co-worker up and running.  Any help would be greatly appreciated.

**Comment by Eilon** [comment]
The Visual Studio _preview update_ should be offered automatically within Visual Studio _preview_, or you can manually update by running the Visual Studio Installer.

Is your co-worker already running a preview? If not, they can install the preview side-by-side with the non-preview version. Go to https://visualstudio.microsoft.com/vs/preview/ to get the preview channel of Visual Studio.

**Comment by jonmiller1** [comment]
They have an old preview of 2019.  I need them to update to 16.3 Preview 2, the version that works with .NET Core 3 Preview 8.  It is only offering to update to 16.3 Preview 3, which is incompatible with Preview 8, it is for Preview 9.  Is there any way to download old VS 2019 Preview versions?

**Comment by mkArtakMSFT** [comment]
I'm not even sure whether you'll be able to find the earlier VS preview installer. Why not update to Preview9 (although there were a lot of breaking changes there from Preview8)? https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/

In general, our support policy for Blazor is that you have to be on the latest 3.0 Preview SDK and the compatible VS Preview release, which is the latest one.
