### ISSUE TITLE
Add support for some additional lifecycle hooks

### ISSUE THREAD

**Issue by dijitalmunky** [aspnet/AspNetCore#13734]
We are writing a new application using signalR to perform updates and disperse updates on all of the business objects in our application.  We were hoping to that like Mvc Controllers we could hook into before and after a method is invoked (i.e. `OnActionExecuting()` and `OnActionExecuted()`).  However, there seems to be no way to do this in signalR.

Our use case for this is varied.  The biggest 2 that come to mind are:
1. Setting custom properties in a logging (or other) context.  For example, the adding parameter values that were used to invoke the  method.
2. Audit logging.  Are application has requirements for audit logging.  We have implemented this in an "old school" way before by having a centralized class/method that can be injected/invoked.

Being able to hook into these two events would give us the advantage that the developer does not need to remember to call a central method every time an action is taken.  This is something that we have had issues with before.

Ideally, 2 (or 3, if you want to support async) methods would be added to the base `Hub` class.  The default implementation would do nothing, but they could be overridden to perform what we need:

- `OnActionExecuting(HubActionContext ctx)` - invoked before a Hub method is invoked by the client.
- `OnActionExecuted(HubActionContext ctx)` - invoked after a Hub method is invoked by the client.
- `OnActionExecutionAsync((HubActionContext ctx, ActionDelegate delegate)` - invoked before the hub method is called.  `delegate` that is called to continue execution.

`HubActionContext` would be similar to the current `HubCallerContext` with the following additional values:
- `Action` - the `Method` for the action that is being invoked.
- `ActionArguments` - the parameters for the action being invoked (similar to `ActionExecutingContext.ActionArguments` in the `Microsoft.AspNetCore.Mvc.Filters` namespace.

**Comment by BrennanConroy** [comment]
Looks like you want the Hub Pipeline feature that we're considering for 5.0
See issue https://github.com/aspnet/AspNetCore/issues/5353

**Comment by dijitalmunky** [comment]
Perfect, thanks.

**Comment by dijitalmunky** [comment]
Perfect, Thanks!
