### ISSUE TITLE
IComponentContext.IsConnected usage clarification

### ISSUE THREAD

**Issue by kevinjpetersen** [aspnet/AspNetCore#13741]
### Is your feature request related to a problem? Please describe.
It seems something hasn't been clarified in the latest blog post with Preview 9. The removal of `IComponentContext` means you can no longer check if the Client is connected on the server side. Currently I use `IComponentContext.IsConnected` on a new `Task ` that I create, and I want to stop this `Task` if the client is no longer connected.

```
protected override async Task OnInitializedAsync()
{
	await Task.Factory.StartNew(async () =>
	{
		while(true) {
			if (!ComponentContext.IsConnected)
			{
				Console.WriteLine("Client is no longer connected, stop task!");
				break;
			}
			Task.Delay(5000);
		}
	});
}
```
How can I replicate this functionality now that this is removed? Is it simply not possible anymore? If this cannot be replicated anymore, how would I be able to have a background task for a client that automatically stops/destroys itself when the client disconnects/closes their browser?

### Describe the solution you'd like
Add a way to still use this functionality to check if the client is connected on the server side, or maybe create a new class of type Task, that automatically destroys itself when the client is no longer connected/disconnected etc.

### Additional context
No further info.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kevinjpetersen.
Can you please tell us why do you want to do that? I mean, the actual cancellation: do you want to know that to decide whether your background task should be temporarily paused, or just abandoned completely? How quickly do you want to know about disconnection?
FYI: components will get disposed when the circuit gets terminated, which should happen when the user closes the tab.

**Comment by kevinjpetersen** [comment]
Hi @mkArtakMSFT, thanks for taking your time to help me out!

The use case is that I want to do continuous refresh _(every x seconds)_ on some of my data _(for example a list of strings from a database)_ in the component itself, by having a function being ran and populating my data just like I would do in the Initialization method of the Component. Right now I don't see a way to do that except by creating a `Task` and having an infinite while loop.

Creating this `Task` in the component doesn't destroy the `Task` itself when the component is destroyed or the user disconnects, since it doesn't have any relationship at all to the component or the user, since it's created on the server itself and not in the context of a component. If there's a way to map this `Task` to the component or the user itself that would be amazing and solve my issue.

**All in all:** I basically just want to complete destroy/stop/abandon the background `Task`, either if the user disconnects or the component itself is destroyed. I currently use the now renamed `UriHelper` and the now deprecated `IComponentContext.IsConnected` to solve that.

**Comment by mkArtakMSFT** [comment]
@rynowak do you have any recommendations here?

**Comment by kevinjpetersen** [comment]
Any update on this one?

**Comment by mkArtakMSFT** [comment]
we are planning to cover this as part of #13584.

**Comment by egil** [comment]
@kevinjpetersen interesting scenario.

One option I can think of is to pass a cancellation token to your Task that a disposable component holds on to. When the client disconnect and the component is disposed, you trigger the cancellation token, which them stops the task. 

Would that work for you?
