### ISSUE TITLE
Hosting bundle for 3.0.0-preview9-19423-09 kills .NET Core 2.0.9

### ISSUE THREAD

**Issue by RagingRudolf** [aspnet/AspNetCore#13758]
### Describe the bug
I have just installed hosting bundle for 3.0.0-preview9-19423-09 on a test server. After installation it seems that our AspNetCore 2.0.9 website is not working anymore.

We are hosting using Out-Of-Process with IIS 7.5

Server info: 
- Windows Server 2008 R2
- .NET Core 1.0.1 Hosting Bundle
- .NET Core 2.0.9 Hosting Bundle
- .NET Core 3.0.0-preview9-19423-09

After a restart of the server our AspNetCore 2.0.9 website gives an 502.5 error.

### To Reproduce
1. Install .NET Core 3.0.0-preview9-19423-09 Hosting Bundle
2. Restart server
3. AspNetCore 2.0.9 website won't startup

### Expected behavior
I expects after a server restart that both my AspNetCore 2.0.9 and AspNetCore 3.0.0-preview-9 website will startup.

### Additional context
Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files (x86)\dotnet
\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NE
TCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.NE
TCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files (x86)\dotnet\shared\Microsoft.NE
TCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files (x86)\dotnet\s
hared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### Temp fix (not working anyway)
It seems that after restarting server if I "repair" my .NET Core 2.0.9 hosting bundle installation and restarts the server again it then my AspNetCore 2.0.9 website will startup properly.

**EDIT:** But this seems then to break .NET Core 3.0.0 :(

**Comment by John0King** [comment]
check your web.config file , make sure you use  AspNetCoreModuleV2

**Comment by Tratcher** [comment]
2.0.9 has been out of support for some time. Does 2.1 work?

**Comment by Tratcher** [comment]
Also check https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-2.2#5025-process-failure and the event logs for error details.

**Comment by RagingRudolf** [comment]
@Tratcher 

The problem is that it is not only an issue when running through IIS with AspNetCore Module but also when I try to run my website with dotnet <assembly>. It just aborts the program right away without throwing an exception. 

Nothing is logged in EventViewer even when running in development/debug mode.

I had to uninstall my .NET Core 3.0 preview 9 and .NET Core 2.0.9 and then reinstall my 2.0.9 to make my website start up again.

**Comment by John0King** [comment]
@RagingRudolf   Are u using `AspNetCoreModule (v1)`  ,  I belive now both older and newer should use `ANCMV2` . ps: this is just some thought  not install 3.0 on production yet

**Comment by RagingRudolf** [comment]
@John0King 

I made it work - it was quite frustrating because after uninstalling .NET Core 3.0 preview 9 again my .NET Core 2.0.9 did not work as well and reinstalling did not work.

So I ended up uninstall .NET Core 2.0.9 - restart server then install .NET Core 2.0.9 again and afterwards install .NET Core 3.0 Preview 9. Restarting machine and afterwards it actually works.

I not sure why it did not work in the first place :|

**Comment by anurse** [comment]
It sounds like it could have been something corrupted about the `dotnet.exe` host installation. @RagingRudolf is your machine still in this broken state? You indicated it was fixed so I'm presuming it isn't. I don't think we can do much further investigation if you can no longer reproduce the issue.

Let us know if you still have a machine in this state, or if it falls back in to it again!

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
