### ISSUE TITLE
3.0 IHostBuilder and IWebHostBuilder same methods confusion

### ISSUE THREAD

**Issue by mrgleba** [aspnet/AspNetCore#13765]
As far as I understand the new way to launch a ewb host in 3.0 is:
```cs
            Host.CreateDefaultBuilder()
                .ConfigureWebHost(whb =>
                {
                    whb
                    .ConfigureLogging((context, ilb) => [...])
                    .ConfigureServices((context, services) => [...])
                    .Configure(app => [...])
                    .UseKestrel(options => [...]);
                })
                .UseConsoleLifetime()
                .Build()
                .Run();

```
ie running all the ```Configure*``` methods on the ```IWebHostBuilder```. But the ```IHostBuilder``` also has some of the ```Configure*``` methods. As far as I was able to test they are not interchangeable - moving ```ConfigureServices``` from ```IWebHostBuilder``` to ```IHostBuilder``` actually causes MVC not to start (no exception is thrown, but the endpoints are not there).  What is the difference and when each of them should be used?

**Comment by Tratcher** [comment]
ConfigureServices should be interchangeable. Can you give a more complete example?

Note UseConsoleLifetime is already enabled by default, you can remove this.

**Comment by mrgleba** [comment]
I was able to produce a simple repro.

In this exampe everything works fine:
```cs
    public class Program
    {
        public static void Main(string[] args)
        {
            Host
            .CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder
                .ConfigureServices(svc =>
                {
                    svc.AddControllers();
                })
                .Configure(app =>
                {
                    app.UseHttpsRedirection();

                    app.UseRouting();

                    app.UseAuthorization();

                    app.UseEndpoints(endpoints =>
                    {
                        endpoints.MapControllers();
                    });

                });
            }).Build().Run();
        }
    }

    [Route("/api/{action}")]
    [ApiController]
    public class FooController
    {
        public IActionResult Foo()
        {
            return new ContentResult()
            {
                Content = "Foo",
                ContentType = "text/plain",
                StatusCode = 200
            };
        }
    }
```
but if you move ```ConfigureServices``` to IHostBuilder:
```cs
    public class Program
    {
        public static void Main(string[] args)
        {
            Host
            .CreateDefaultBuilder(args)
            .ConfigureServices(svc =>
            {
                svc.AddControllers();
            })
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder
                .Configure(app =>
                {
                    app.UseHttpsRedirection();

                    app.UseRouting();

                    app.UseAuthorization();

                    app.UseEndpoints(endpoints =>
                    {
                        endpoints.MapControllers();
                    });

                });
            }).Build().Run();
        }
    }

    [Route("/api/{action}")]
    [ApiController]
    public class FooController
    {
        public IActionResult Foo()
        {
            return new ContentResult()
            {
                Content = "Foo",
                ContentType = "text/plain",
                StatusCode = 200
            };
        }
    }
```

then a GET https://localhost:50001/api/Foo returns a 404.

**Comment by Tratcher** [comment]
Weird. It really should be pass through. https://github.com/aspnet/AspNetCore/blob/e7016bc67ab9195db5741d03a03c754891919f7d/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs#L170-L184

Maybe it's an ordering issue? What happens if you put ConfigureServices after ConfigureWebHostDefaults?

Maybe this AddRouting calls is overriding something critical from AddControllers?
https://github.com/aspnet/AspNetCore/blob/e7016bc67ab9195db5741d03a03c754891919f7d/src/DefaultBuilder/src/WebHost.cs#L254

@mkArtakMSFT can you have someone check what's wrong with the MVC services in the second example above?

**Comment by davidfowl** [comment]
This is preview9?

**Comment by mrgleba** [comment]
This is preview9.

**Comment by pranavkm** [comment]
> It’s likely an issue with the assembly name and application part discovery

`IWebHostEnvironment.ApplicationName` is null in the first case, which causes MVC to no-op: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L82-L88. Re-ordering it sets this up, which explains why things work. I'm not sure if there's anything more to do here.

**Comment by davidfowl** [comment]
Right that was my guess. @pranavkm can you try changing that logic to look for `IHostEnvironment` instead?
