### ISSUE TITLE
ASP.NET Core and Blazor updates in .NET Core 3.0 Preview 9.19424.4

### ISSUE THREAD

**Issue by srg1204** [aspnet/AspNetCore#13769]
Error CS1503
```razor
<select @onchange=DoStuffP>
@foreach (var templateP in templatesP)
{
@templateP
}
    <p>Votre choix: @habiletéP</p>

    @functions {
        List<string> templatesP = new List<string>() {
    "Faites votre choix",
    "HABILETÉ 1",
    "HABILETÉ 2",
    "HABILETÉ 3",
    "HABILETÉ 4" };
        string habiletéP = "Faites votre choix";

        void DoStuffP(Microsoft.AspNetCore.Components.Web.ChangeEventArgs e)
        {
            habiletéP = e.Value.ToString();
        }
    }
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. 
Please refer to the release notes in here showing you the migration steps to Preview9, which includes multiple preview breaking changes.
In this particular case, you're missing a `using` for `Microsoft.AspNetCore.Components.Web`: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/#blazor-web-attributes-moved

**Comment by mkArtakMSFT** [comment]
Also, as a side note, `@functions` is now `@code` and you should simply have it in the top level, rather than embedded in any scope.
