### ISSUE TITLE
Migration 2.2 -> 3.0 document Authorization using IAuthorizationPolicyProvider

### ISSUE THREAD

**Issue by mrgleba** [aspnet/AspNetCore#13762]
I didn't find anyhting in the migration docs for doing Authorization using ```IAuthorizationPolicyProvider```. This interface has a new member now:
```cs
public Task<AuthorizationPolicy> GetFallbackPolicyAsync()
```

I'd be nice to provide a default implementation in the docs that would mimic the 2.2 behaviour of
allowing requests that haven't been matched by MVC or static files:
```cs
public Task<AuthorizationPolicy> GetFallbackPolicyAsync()
{
  var bp = new AuthorizationPolicyBuilder();
  bp.RequireAssertion(_ => true);
  return Task.FromResult(bp.Build());
}
```

**Comment by Pilchie** [comment]
Moving to P3, since it's too late for P2.

**Comment by HaoK** [comment]
@blowdart we should move this to a different milestone since this is a doc issue, and not tied to a release

**Comment by HaoK** [comment]
Actually we should probably just close this, since there's a docs issue tracking: https://github.com/aspnet/AspNetCore.Docs/issues/14232
