### ISSUE TITLE
Signalr Client UWP does not connect to Signalr on the server ASP.NET CORE 3 preview 8

### ISSUE THREAD

**Issue by Pibe93** [aspnet/AspNetCore#13767]
Hi, I need to use UWP as client and use Signalr Messagepack but it doesn't work !!
It can't connect to the Server but I don't understand why!
On WPF client or .net core console it works!

public HubConnection connection { get; set; }
public string groupName { get; set; }

    public MainPage()
    {
        this.InitializeComponent();

        connection = new HubConnectionBuilder()
                   .WithUrl("https://localhost:44368/messagehub")
                   .AddMessagePackProtocol()
                   .Build();

        connection.On<string, string>("ReceiveMessage", (title, message) =>
        {
            messagelist.Items.Add(string.Format("{0} {1}", title, message));
        });

        connection.StartAsync();
        messagelist.Items.Add(connection.State);

        groupName = "test";

        JoinGroup();
    }

    public async void JoinGroup()
    {
        await connection.InvokeAsync("JoinGroup", groupName);
    }

UWP the HTTP / 1.0 protocol is used and the user-agent is not set while for the WPF client / Console the HTTP / 1.1 protocol is used and the user-agent is set: Microsoft.AspNetCore.Http.Connections.Client / 1.1.0-rtm-35687.

Here what I saw with Fiddler:
UWP client:

CONNECT localhost:44368 HTTP/1.0
Host: localhost:44368
Content-Length: 0
Connection: Keep-Alive
Pragma: no-cache

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Version: 3.3 (TLS/1.2)
Random: 5D 72 0A A8 79 5B DC 12 50 9D AB 35 73 4D 31 9B 5E 9E F0 13 FE 4C 4F 3C 9D CE BB 86 B1 45 FE 38
"Time": 04/05/2059 08:55:25
SessionID: empty
Extensions: 
server_namelocalhost
status_requestOCSP - Implicit Responder
elliptic_curvesunknown [0x1D), secp256r1 [0x17], secp384r1 [0x18]
ec_point_formatsuncompressed [0x0]
signature_algssha256_rsa, sha384_rsa, sha1_rsa, sha256_ecdsa, sha384_ecdsa, sha1_ecdsa, sha1_dsa, sha512_rsa, sha512_ecdsa
SessionTicketempty
ALPN h2, http/1.1
extended_master_secretempty
0x0018 00 10 03 02 01 00
renegotiation_info00
Ciphers: 
[C02C]TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
[C02B]TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
[C030]TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
[C02F]TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[009F]TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
[009E]TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
[C024]TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
[C023]TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
[C028]TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
[C027]TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
[C00A]TLS1_CK_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
[C009]TLS1_CK_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
[C014]TLS1_CK_ECDHE_RSA_WITH_AES_256_CBC_SHA
[C013]TLS1_CK_ECDHE_RSA_WITH_AES_128_CBC_SHA
[009D]TLS_RSA_WITH_AES_256_GCM_SHA384
[009C]TLS_RSA_WITH_AES_128_GCM_SHA256
[003D]TLS_RSA_WITH_AES_256_CBC_SHA256
[003C]TLS_RSA_WITH_AES_128_CBC_SHA256
[0035]TLS_RSA_AES_256_SHA
[002F]TLS_RSA_AES_128_SHA
[000A]SSL_RSA_WITH_3DES_EDE_SHA

Compression: 
[00]NO_COMPRESSION

-----------------------------------------------------------------

POST https://localhost:44368/messagehub/negotiate HTTP/1.1
X-Requested-With: XMLHttpRequest
User-Agent: Microsoft.AspNetCore.Http.Connections.Client/1.1.0-rtm-35687
Host: localhost:44368
Content-Length: 0
Connection: Keep-Alive
Cache-Control: no-cache

Client WPF / Console :

CONNECT localhost:44368 HTTP/1.1
Host: localhost:44368
User-Agent: Microsoft.AspNetCore.Http.Connections.Client/1.1.0-rtm-35687

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Version: 3.3 (TLS/1.2)
Random: 5D 72 0D D1 71 A6 7C 90 73 A5 A4 5F 2F 61 1F D8 68 65 DD 61 C9 84 B9 01 3F BC 9F 2D 3C 5A 9E 11
"Time": 21/02/2081 00:23:09
SessionID: empty
Extensions: 
server_namelocalhost
elliptic_curvesunknown [0x1D), secp256r1 [0x17], secp384r1 [0x18]
ec_point_formatsuncompressed [0x0]
signature_algssha256_rsa, sha384_rsa, sha1_rsa, sha256_ecdsa, sha384_ecdsa, sha1_ecdsa, sha1_dsa, sha512_rsa, sha512_ecdsa
SessionTicketempty
extended_master_secretempty
renegotiation_info00
Ciphers: 
[C02C]TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
[C02B]TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
[C030]TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
[C02F]TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[009F]TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
[009E]TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
[C024]TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
[C023]TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
[C028]TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
[C027]TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
[C00A]TLS1_CK_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
[C009]TLS1_CK_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
[C014]TLS1_CK_ECDHE_RSA_WITH_AES_256_CBC_SHA
[C013]TLS1_CK_ECDHE_RSA_WITH_AES_128_CBC_SHA
[009D]TLS_RSA_WITH_AES_256_GCM_SHA384
[009C]TLS_RSA_WITH_AES_128_GCM_SHA256
[003D]TLS_RSA_WITH_AES_256_CBC_SHA256
[003C]TLS_RSA_WITH_AES_128_CBC_SHA256
[0035]TLS_RSA_AES_256_SHA
[002F]TLS_RSA_AES_128_SHA
[000A]SSL_RSA_WITH_3DES_EDE_SHA

Compression: 
[00]NO_COMPRESSION

Thanks for your help.

**Comment by BrennanConroy** [comment]
What is the actual issue you are observing? Are you seeing exceptions on the server and or client? Can you provide the logs? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2#server-side-logging

Could you provide the fiddler trace file if you think it will help diagnose the issue? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2#collect-a-network-trace-with-fiddler-preferred-option

**Comment by Pibe93** [comment]
There is no exception, the client just remains on the disconnected state.
This occurs only with the UWP client because with a core WPF / Console client it connects.
In both cases the method I use to collect myself from the signalr client to server is the same.
Exactly I tried to put under the fiddler to see what the differences were and I posted what I saw.

Thanks for the advice, now I try to use the log to see what I see and update the issue

**Comment by Pibe93** [comment]
Hi, this is the error that is written to the UWP signalr client log :
`Microsoft.AspNetCore.Http.Connections.Client.HttpConnection:Error: Failed to start connection. Error getting negotiation response from 'https://localhost:44368/messagehub'.

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Exception: Impossibile trovare il testo associato a questo codice di errore.

L'autorità del certificato non è valida o errata

   at System.Net.Http.HttpHandlerToFilter.SendAsync(HttpRequestMessage request, CancellationToken cancel)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger)
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection:Debug: Skipping dispose, connection is already disposed.
Eccezione generata: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Eccezione di tipo 'System.InvalidOperationException' in System.Private.CoreLib.dll non gestita nel codice utente
The 'InvokeCoreAsync' method cannot be called if the connection is not active`

I therefore deduced that the problem is the certificate.
Removing HTTPS and using HTTP the UWP client can connect!
But it is not clear to me why there are no such problems with the .net core WPF / Console client.

**Comment by BrennanConroy** [comment]
Could you enable server side logs at the Debug level?

Kestrel will log any certificate issues if there are some.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
