### ISSUE TITLE
Configuration of openid connect authentication scheme. 

### ISSUE THREAD

**Issue by EnricoMassoneDeltatre** [aspnet/AspNetCore#13775]
Hi, 

I have a question related to the proper way of configuring an open id connect authentication scheme for an ASP.NET core 2.2 application. 

I know that the proper way to do is the following: 

```
public void ConfigureServices(IServiceCollection services)
{
	services.
		.AddMvc();
		
	services
		.AddAuthentication()
		.AddOpenIdConnect("oidc", "OpenID Connect", options =>
		{
			// configuration goes here
		});
}
```

We have already verified that when multiple open id connect schemes are provided we have to set different values for the scheme name and for both the properties `CallbackPath` and `SignedOutCallbackPath` of the option class `OpenIdConnectOptions`. 

Can we really set any value for these two properties with the only constraint that it is a formally valid URL path ? Is there any validation applied to the values assigned to these two properties ? 

We have another doubt about the two properties  `Authority` and `MetadataAddress` of the option class `OpenIdConnectOptions`. 

Is it really necessary to provide both of them or is it possible to provide the `MetadataAddress` property only (avoiding to specify the `Authority` property) ? It seems to work by just specifying the  `MetadataAddress`  property, at least when using Azure Active Directory B2C as the identity provider. 

Thanks for helping

**Comment by Tratcher** [comment]
> Can we really set any value for these two properties with the only constraint that it is a formally valid URL path ? Is there any validation applied to the values assigned to these two properties ?

Correct, any unique valid url path is allowed. The fields are a PathString type that will encode characters that aren't allowed.

> Is it really necessary to provide both of them or is it possible to provide the `MetadataAddress` property only (avoiding to specify the `Authority` property) ? It seems to work by just specifying the `MetadataAddress` property, at least when using Azure Active Directory B2C as the identity provider.

Yes that's fine. Authority is used to construct MetadataAddress if it's not provided.

**Comment by EnricoMassoneDeltatre** [comment]
> > Can we really set any value for these two properties with the only constraint that it is a formally valid URL path ? Is there any validation applied to the values assigned to these two properties ?
> 
> Correct, any unique valid url path is allowed. The fields are a PathString type that will encode characters that aren't allowed.
> 
> > Is it really necessary to provide both of them or is it possible to provide the `MetadataAddress` property only (avoiding to specify the `Authority` property) ? It seems to work by just specifying the `MetadataAddress` property, at least when using Azure Active Directory B2C as the identity provider.
> 
> Yes that's fine. Authority is used to construct MetadataAddress if it's not provided.

Thanks for the explanation !
