### ISSUE TITLE
.Net Core 3.0 Preview Signalr client method not called

### ISSUE THREAD

**Issue by NathanSidoliMorris** [aspnet/AspNetCore#13786]
### Describe the bug

Signalr hub connection starts successfully, hub method (named Test) is called (breakpoints hit succesfully) but the client method is not called.

Im using ```ASP.NET Core 3.0``` sdk version ```3.0.100-preview9-014004``` with ```React.JS Individual accounts template```, and am running locally. My signalr client version is ```3.0.0-preview6.19307.2```

### Expected behavior
The client method "Test" to be called, outputting a message to the console.

### Screenshots

C# Hub method:

 ```csharp
   public async Task Test(string arg)
   {
       await Clients.All.SendAsync("Test", arg);
   }
```
I've also tried the send core async method, but to no avail.

```csharp
  public async Task Test(string arg)
  {
      await Clients.All.SendCoreAsync("Test", new object[] { arg });
  }
 ```

Redux middleware:

```javascript
import * as signalrActionTypes from "./actionTypes";
import { USER_AUTHENTICATED } from "../actionTypes";
import authService from "../../components/api-authorization/AuthorizeService";
import * as signalR from "@aspnet/signalr";
import { UpdateActiveStatusEvent, TestEvent } from "./eventHandlers";

const transport = signalR.HttpTransportType.WebSockets | signalR.HttpTransportType.LongPolling;

const options = {
    transport,
    logMessageContent: true,
    logger: signalR.LogLevel.Trace,
};

let hubConnection = new signalR.HubConnectionBuilder()
    .withUrl(`/dashboardRoute`, options)
    .withAutomaticReconnect()
    .configureLogging(signalR.LogLevel.Trace)
    .build();

export default function signalRMiddleware(store) {
    return (next) => async (action) => {
        if (action.type === USER_AUTHENTICATED) {
            hubConnection.on("Test", (args) => console.log("HIT", args));
            startSignalR(hubConnection);
        } else {
            if (action.isSignalr) {
                switch (action.type) {
                    case signalrActionTypes.UPDATE_ACTIVE_STATUS_SIGNALR:
                        {
                            //const signalrPayload = toSignalrPayload(action.payload, store);
                            //await hubConnection.send(UpdateActiveStatusEvent.name, signalrPayload);
                        }
                        break;
                    case signalrActionTypes.TEST_SIGNALR:
                        {
                            //const signalrPayload = toSignalrPayload(action.payload, store);
                            await hubConnection.send("Test", "testing");
                        }
                        break;
                    default:
                        break;
                }
            }
        }
        return next(action);
    }
}

function startSignalR(connection) {
    connection.start()
        .then(() => console.log('SignalR Connected'))
        .catch(err => console.error('SignalR Connection Error: ', err));
}
```

Startup.cs snippet:

```csharp
   app.UseSignalR(options =>
   {
       options.MapHub<DashboardHub>("/dashboardRoute");
   });
   ```
Some snippets from trace logs: 
```csharp
[2019-09-06T23:40:35.173Z] Debug: Starting connection with transfer format 'Text'.
1.chunk.js:4663:11
[2019-09-06T23:40:35.175Z] Debug: Sending negotiation request: https://localhost:44353/dashboardRoute/negotiate.
1.chunk.js:4663:11
[2019-09-06T23:40:35.353Z] Debug: Selecting transport 'WebSockets'.
1.chunk.js:4663:11
[2019-09-06T23:40:35.357Z] Trace: (WebSockets transport) Connecting.
1.chunk.js:4663:11
[2019-09-06T23:40:37.208Z] Information: WebSocket connected to wss://localhost:44353/dashboardRoute?id=Nh7xTckW7OyF8cSPD43u4A.
1.chunk.js:4658:11
[2019-09-06T22:37:19.654Z] Debug: The HttpConnection connected successfully.
Utils.js:358
[2019-09-06T23:40:40.735Z] Trace: (WebSockets transport) sending data. String data of length 66. Content: '{"arguments":["testing"],"streamIds":[],"target":"Test","type":1}�'.
1.chunk.js:4663:11
[2019-09-06T23:40:40.742Z] Trace: (WebSockets transport) data received. String data of length 206. Content: '{"type":1,"target":"SendCoreAsync","arguments":["Test",["testing"],{"isCancellationRequested":false,"canBeCanceled":false,"waitHandle":{"handle":{},"safeWaitHandle":{"isInvalid":false,"isClosed":false}}}]}�'.
```

### Additional context

I've followed the advice suggested on [signalr trouble shooting docs](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/troubleshooting), relating to silent client/server failure. I've been searching for a solution to this for a week now.

Apologies in advance if this issue is user error; cheers for any feedback :)

#### Dotnet info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by BrennanConroy** [comment]
If you look at the last line of your client-side logs you'll see
`[2019-09-06T23:40:40.742Z] Trace: (WebSockets transport) data received. String data of length 206. Content: '{"type":1,"target":"SendCoreAsync","arguments":["Test",["testing"],{"isCancellationRequested":false,"canBeCanceled":false,"waitHandle":{"handle":{},"safeWaitHandle":{"isInvalid":false,"isClosed":false}}}]}�'.`

This is the reason you're not seeing method "Test" being called on the client, because the server is trying to invoke "SendCoreAsync" on the client.

Could you share your Hub? Specifically, is it a Typed Hub or Dynamic Hub? And if it's Typed, what does the interface look like?

I could reproduce a similar issue if I used a Dynamic Hub the wrong way.

**Comment by NathanSidoliMorris** [comment]
My hub is typed. The interface is as follows:

    public interface IDashboardHub : IClientProxy
    {
        Task UpdateActiveStatus(NotificationToOne<ActiveStatusPayload> notification);
    }

While the method “Test” does not feature on this interface, I didn’t experience any issues calling a method not featured on the hub interface from the Javascript client (on a previous Asp Net Core 2.2 project)

My intention was to only define the methods that would be called on ```IHubContext``` instances injected into other Hubs.

And just to clarify, the method “UpdateActiveStatus” also does not get invoked on the client-side either.

**Comment by BrennanConroy** [comment]
Ah, I see what's wrong.
Your interface should not inherit from `IClientProxy`.

The name of the interface methods is the name of the client function you're calling. So in the case of the client Test method, you'll need to add a Test method to your interface.

**Comment by NathanSidoliMorris** [comment]
What is the reason for this interface not inheriting ```IClientProxy``` in this case?

Thankyou for your help :)

**Comment by BrennanConroy** [comment]
The interface isn't supposed to inherit from `IClientProxy`. The interface represents the client methods that can be called.

And `IClientProxy` represents a way of calling methods without the interface.

**Comment by NathanSidoliMorris** [comment]
Okay, thanks for the clarification. 

Just for a sanity check, are you be able to reproduce the exact same behaviour I was experiencing? 

Given a similar setup (I.e with the interface implementing ```IClientProxy``` and not having a method defined on it and an attempted call from the JS client.

**Comment by BrennanConroy** [comment]
Yes, once I saw `IClientProxy` being used I could repro the same issue.

**Comment by NathanSidoliMorris** [comment]
Okay , cheers. I’ll close the issue now :)

**Comment by NathanSidoliMorris** [comment]
Okay , cheers. I’ll close the issue now
