### ISSUE TITLE
AuthorizeView tag in Blazor component throws if Roles param included

### ISSUE THREAD

**Issue by intiharj** [aspnet/AspNetCore#13789]
### Describe the bug
In preview 9, I'm seeing a problem with AuthorizeView when using Windows Authentication. If I just use `<AuthorizeView><Authorized>OK</Authorized></AuthorizeView>` it works, but if I add the Roles parameter, I get: Win32Exception: The trust relationship between this workstation and the primary domain failed. Here's the changed markup: `<AuthorizeView Roles="XXX"><Authorized>OK</Authorized></AuthorizeView>` The call stack is listed below. 

### To Reproduce
I can repro this with a new prev9 blazor serverside app, add windows authentication, and add the above AuthorizeView markup to the bottom of the index.razor page and run.

### Expected behavior
I'd expect the contents of the AuthorizeView to not display or at least see an error indicating that the XXX role is unknown.

### Error displayed in browser...
An unhandled exception occurred while processing the request.
Win32Exception: The trust relationship between this workstation and the primary domain failed.
System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, out bool someFailed)

Stack Query Cookies Headers Routing
Win32Exception: The trust relationship between this workstation and the primary domain failed.
System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, out bool someFailed)
System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, out bool someFailed)
System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, bool forceSuccess)
System.Security.Principal.WindowsPrincipal.IsInRole(string role)
Microsoft.AspNetCore.Authorization.Infrastructure.RolesAuthorizationRequirement+<>c__DisplayClass4_0.<HandleRequirementAsync>b__0(string r)
System.Linq.Enumerable.Any<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
Microsoft.AspNetCore.Authorization.Infrastructure.RolesAuthorizationRequirement.HandleRequirementAsync(AuthorizationHandlerContext context, RolesAuthorizationRequirement requirement)
Microsoft.AspNetCore.Authorization.AuthorizationHandler<TRequirement>.HandleAsync(AuthorizationHandlerContext context)
Microsoft.AspNetCore.Authorization.Infrastructure.PassThroughAuthorizationHandler.HandleAsync(AuthorizationHandlerContext context)
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, object resource, IEnumerable<IAuthorizationRequirement> requirements)
Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.IsAuthorizedAsync(ClaimsPrincipal user)
Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(ref DiffContext diffContext, int frameIndex)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(ref DiffContext diffContext, int frameIndex)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(ref DiffContext diffContext, int newFrameIndex)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(ref DiffContext diffContext, int newFrameIndex)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(ref DiffContext diffContext, int oldStartIndex, int oldEndIndexExcl, int newStartIndex, int newEndIndexExcl)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, int componentId, ArrayRange<RenderTreeFrame> oldTree, ArrayRange<RenderTreeFrame> newTree)
Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(int componentId, RenderFragment renderFragment)
Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(int componentId, ParameterView initialParameters)
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c__11<TResult>+<<InvokeAsync>b__11_0>d.MoveNext()
Microsoft.AspNetCore.Mvc.ViewFeatures.RazorComponents.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperComponentExtensions.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperComponentExtensions.RenderComponentAsync<TComponent>(IHtmlHelper htmlHelper, RenderMode renderMode, object parameters)
BlazorApp3.Pages.Pages__Host.<ExecuteAsync>b__10_1() in _Host.cshtml
+
        @(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
BlazorApp3.Pages.Pages__Host.ExecuteAsync()
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by intiharj** [comment]
Sorry, I just realized that I need to format the code from my original post so that you can see it.  Here are the snippets...

working:   `<AuthorizeView><Authorized>OK</Authorized><AuthorizeView>`

not working:  `<AuthorizeView Roles="XXX"><Authorized>OK</Authorized><AuthorizeView> `

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @intiharj.
We are unable to reproduce this issue. Can you try to share with us as many details about your environment, as possible in a hope that there will be something to follow up on.

**Comment by intiharj** [comment]
Hopefully it's my environment :).  I'll test on another machine to see if I can repro it there.  Will write back later today.  Thank you.

**Comment by intiharj** [comment]
OK, I have more information.
I've tried this on 2 environments, both running preview 9

**ENV_A:**
1. the original environment mentioned above
2. windows 10 v1803 (OS Build 17134.590)
3. corporate image
4. VPN to corporate network with Active Directory

**ENV_B:**
1. personal (non-corporate) machine
2. windows 10 v1903 (OS Build 18362.329)

Notes:
I still see the original error on ENV_A if I use a role that is not a security group in Active Directory.  When I do use an actual security group that I am a member of, I no longer see the above trust relationship error, but the authorized content still does not display.  In the debug console in visual studio, I see the following two lines:
"Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization was 
successful."
"Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed."

When I run the code with Roles="XXX" on ENV_B, the content is not displayed as expected because there is no "XXX" role on that environment.  If I change it to Roles="Administrator"  (which I am a member of), I see the same results as ENV_A, that is, no error message displayed, no content displayed, and the same two messages in the debug output in VS:  ("Authorization was successful"  followed by "Authorization failed" )

**Comment by intiharj** [comment]
also, in both environments, I'm running debug builds in IIS Express

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @intiharj.
So to confirm I understood your correctly: when the `Roles=...` is added to the `AuthorizeView`, even though the role exists and the user is a member of that role, nothing gets rendered, however you see the logs like the following in this case: 
```
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization was
successful.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed.
```

**Comment by intiharj** [comment]
correct

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS this looks like a bug. Can you please look into this for 3.1?

**Comment by SteveSandersonMS** [comment]
I've investigated, and it doesn't look like this is something we control inside Blazor (or even ASP.NET Core).

I verified that Blazor's Windows Authentication template can successfully authorize visitors based on `<AuthorizeView Roles="some-group-name">...</AuthorizeView>`, where `some-group-name` is a group that you may or may not be a member of. So the basic scenario does work.

For the scenario reported here, i.e., a particular corporate Windows image on a particular domain triggering the error *The trust relationship between this workstation and the primary domain failed*, this is not something I have been able to reproduce. However:

1. Searching for that error message yields a lot of results suggesting it's something that happens internally to Windows if the machine is not adequately synced with the domain. I have personally experienced this in the past in a non-Blazor-related scenario (I was unable to log into a domain account) and had to rejoin the domain to fix it. As such it might be specific to the one machine being tested, and totally unrelated to .NET as a whole.
2. The auth implementation in Blazor simply uses the common authorization code from ASP.NET Core and isn't doing anything unique of its own. We rely on Windows authentication returning a yes/no response and not throwing. If the underlying Windows auth APIs do throw then I believe we are correct to surface the exception. As far as I'm aware, the same exception would occur if doing authorization in the same way on server-side ASP.NET Core (e.g., MVC/Razor Pages), since it's the same code paths.

As such I don't see that there's anything else we can do here. If @intiharj is able to provide steps for configuring a new Windows machine such that the problem is reproducible, we may be able to pass this on to a team that could confirm whether it's a bug or a misconfiguration. If anyone else is able to reproduce it too, please let us know in case we can identify something common to your scenario.

Given all this I'm going to close it as an external issue in the Windows configuration. I'm sorry that doesn't give you a clear solution @intiharj but it really does appear to be something happening inside your domain/auth setup and possibly even specific to one machine or the particular image used to join to the domain.

cc @blowdart in case he has seen this particular error before (*"The trust relationship between this workstation and the primary domain failed"*) and has suggestions on diagnosis or resolution steps, or knows someone who might.

**Comment by intiharj** [comment]
Thanks, @SteveSandersonMS.  I just tried to repro this on ENV_A (see above) upgraded to ASP.NET Core 3.0.0, and I no longer see the problem.  I'm on the road this week, but will try it on ENV_B this weekend with 3.0.0.  @blowdart, please let me know if you need any more info from me on preview 9.

**Comment by blowdart** [comment]
None, that is a windows error from when a machine hasn’t been online and talking to a DC for ages. Not our error.

________________________________
