### ISSUE TITLE
Issues with RenderTree after trying to update from preview8 to preview9

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#13784]
_From @justindude521 on Thursday, September 5, 2019 7:39:11 PM_

Edit: Am using server-sided blazor if that matters

> Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
> Error	CS1503	Argument 1: cannot convert from 'Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder' to 'Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder'

Also getting 

> Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
> Error	CS0234	The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?)

Using Statements on .razor pages
```
@using System.Threading
@using Microsoft.EntityFrameworkCore
@using BlazorApp1.Data
@using BlazorApp1.Data.Models
@using Microsoft.AspNetCore.Components.Web;
@using Microsoft.AspNetCore.Components.Authorization;
@inject AuthenticationStateProvider AuthenticationStateProvider
```

I've tried following the instructions for migration at https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/ to no success

Root __Imports.razor
```
@using System.Net.Http
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.Authorization
@using Microsoft.JSInterop
@using BlazorApp1
@using BlazorApp1.Shared
```

.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.6" />
    <PackageReference Include="HangFire.Core" Version="1.7.6" />
    <PackageReference Include="HangFire.SqlServer" Version="1.7.6" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.0.0-preview9.19424.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0-preview9.19424.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0-preview9.19424.4" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.1.0-preview1-10442" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview9.19424.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0-preview9.19424.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0-preview9.19424.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0-preview9.19424.4" />
    <PackageReference Include="Microsoft.WebSockets" Version="0.2.3.1" />
  </ItemGroup>

</Project>
```

_Copied from original issue: dotnet/core#3315_

**Comment by Eilon** [comment]
@justindude521 can you confirm that you updated to the latest preview of Visual Studio? Can you indicate exactly which version you're running?

**Comment by justindude521** [comment]
@Eilon Seems like I was still on Visual Studio 2019 Preview 2. I must have accidentally cancelled the update when doing so. 
**Updating to Visual Studio 2019 16.3 Preview 3 fixed the issue!**

**Comment by justindude521** [comment]
> @justindude521 can you confirm that you updated to the latest preview of Visual Studio? Can you indicate exactly which version you're running?

@Eilon Seems like I was still on Visual Studio 2019 Preview 2. I must have accidentally cancelled the update when doing so.
**Updating to Visual Studio 2019 16.3 Preview 3 fixed the issue!**
