### ISSUE TITLE
IApplicationBuilder IApplicatoinBuilder.UseIdentity() This method is obsolete 

### ISSUE THREAD

**Issue by simon617** [aspnet/AspNetCore#13792]
I got the message "IApplicationBuilder IApplicatoinBuilder.UseIdentity() This method is obsolete" when configuring the User Identity. I have no idea how to fix it. Any idea ?  Thx

app.UseIdentity();

![UseIdentity](https://user-images.githubusercontent.com/42394945/64472150-847e3100-d18c-11e9-9f8a-e0cfd6e4aaaa.png)

**Comment by blowdart** [comment]
Everything [moved to services](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio#create-a-web-app-with-authentication)

If you want the default UI, it's

```c#
    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));
    services.AddDefaultIdentity<IdentityUser>()
        .AddDefaultUI(UIFramework.Bootstrap4)
        .AddEntityFrameworkStores<ApplicationDbContext>();

```

**Comment by simon617** [comment]
Already included this in ConfigureServices  :

 public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services.AddDbContext<IdentityDbContext>(options =>
                options.UseSqlite("Data Source=users.sqlite",
                optionsBuilder => optionsBuilder.MigrationsAssembly("ShoppingAPI")));
            services.AddIdentity<IdentityUser, IdentityRole>()
                .AddEntityFrameworkStores<IdentityDbContext>()
                .AddDefaultTokenProviders();
        }

Do you mean I don't need app.UseIdentity() ?

Thx

**Comment by blowdart** [comment]
Oh I missed it was .AddIdentity(). 

You shouldn't need it, just app.UseAuthentication();
