### ISSUE TITLE
Register TagHelpers in DI

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/AspNetCore#13794]
I'm trying to register a `TagHelper` using the DI instead of adding it using `_ViewImports.cshtml` but it does not seem to work in preview 9?

This is my tag helper

```c#
[HtmlTargetElement("*", Attributes = "is")]
    public class TestTagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output) {
            output.Attributes.RemoveAll("is");
        }
    }
```

And this is how I register the tag helper in the DI

```c#
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddTransient<ITagHelper, TagHelpers.TestTagHelper>();

        services.AddControllersWithViews();        
    }
```

**Comment by marcuslindblom** [comment]
Maybe I have misunderstood the concept of registering the tag helper in the DI and not via the `_ViewImports.cshtml` view? https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/th-components?view=aspnetcore-3.0#registration-via-services-container

**Comment by pranavkm** [comment]
The documentation is about `TagHelperComponents` which aren't the same as regular tag helpers. Could you elaborate on what it is that you're trying to do? Why do you need TagHelpers to be in DI?

**Comment by marcuslindblom** [comment]
@pranavkm Actually I do not need the tag helper to be in the DI. I thought that it was possible to register the tag helper in the DI instead of adding them to `_ViewImports.cshtml`.

The reason why is that I'm developing a nuget package that contains some functionality that I often use. I register the package in the `Startup` class by using `services.Add...` and `app.Use...` and thats very clean I think. So, now I created some tag helpers and if it is possible I would like to register them into the "pipeline" without having to mess with the views and keep the configuration of my package small and clean.

**Comment by pranavkm** [comment]
> I thought that it was possible to register the tag helper in the DI instead of adding them to _ViewImports.cshtml.

TagHelpers are a Razor parser feature. There's a way to register them in DI and use the service container to initialize them, but you'll need to add them to `_ViewImports.cshtml` to be used in Razor files.

**Comment by marcuslindblom** [comment]
@pranavkm Ok, I see. Does the same applies to `TagHelperComponents`?
