### ISSUE TITLE
Deploying and Hosting Blazor App on Ubuntu Server

### ISSUE THREAD

**Issue by ahmeddawood88** [aspnet/AspNetCore#13795]
Hi, I have tried to find a proper documentation listing steps to deploy and host a simple Blazor App on ubuntu but with no luck. 

Is there any documentation anyone could recommend for me to follow please? 

Any advice is appreciated.

**Comment by odin88** [comment]
You can try https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/client-side?view=aspnetcore-3.0#standalone-deployment for Nginx

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
