### ISSUE TITLE
Error -The type 'Shared' does not exist  in the type 'Namespace' - when modifiyng the _Import.razor file.

### ISSUE THREAD

**Issue by FelicianoEJ** [aspnet/AspNetCore#13799]
The following **error** came up:
CS0426	The type name 'Shared' does not exist in the type 'NeighborHub'

Origin:
C:\user\me\Docs\project\NeighborHub\obj\Debug\netcoreapp3.0\Razor\Shared\MainLayout.razor.g.cs	85	Active

To Reproduce the behavior:
1. Using this version of ASP.NET Blazor Core 3.0 (in my case preview 8 and 9 when I upgraded the error persisted)

2. Run this code in the **top-level** file  _Imports.razor:
`//Some others using statements`
`@using Microsoft.AspNetCore.Components.Web`
`@using Microsoft.JSInterop`
`@using Namespace`
`@using Namespace.Shared`
`@using Namespace.Data //Here is the issue`

I'm not entirely sure if I'm not supposed to add another using statement with the same namespace but once I erased `@using Namespace.Data` from the _Imports.razor it resolved the error.

[Image of the IDE + the Error](https://i.ibb.co/QMRrNfm/Blazor-Issue2.png)

Additional context:
Inside the Namespace.Data I have the DbContext file and my models.

**Comment by pranavkm** [comment]
Do you have a type named `NeighbourHub` in your project file? The files in the shared folder are generated in the `NeighbourHub.Shared` namespace which would conflict with the type name.

**Comment by FelicianoEJ** [comment]
I do have a class named NeighborHub. 
Does this conflict with the namespace being the same?

NeighborHub.Data
    |
    --- AppModels.cs
            |
            --- public class NeighborHub
