### ISSUE TITLE
Creating an Razor Class Library with Framework Reference to Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by TwentyFourMinutes** [aspnet/AspNetCore#13801]
### Describe the bug
I am trying to put some of my Controllers and Views of my ASP.Net Core 3 pre-release 9 MVC Project in a different Project. Therefor I went with an Razor Class Library since as the [documentation](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio) says:

> Razor views, pages, controllers, page models, Razor components, View components, and data models can be built into a Razor class library (RCL).

So I went ahead and created a RCL Project which looks something like the following:

```cs
<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
``` 

I included the FrameworkReference instead of a PackageReference for the `Microsoft.AspNetCore.App` since the following issue tells me so. [#3756](https://github.com/aspnet/AspNetCore/issues/3756#issue-375242027)

But this leaves me with the following error:

> The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized

**Comment by pranavkm** [comment]
You'll need a `TargetFramework` of `netcoreapp3.0`. Does changing the tfm fix the issue?

**Comment by TwentyFourMinutes** [comment]
Well if I use `netcoreapp3.0` it resolves the dependency issues, but other errors occur.

```
![image](https://user-images.githubusercontent.com/36015290/64487053-c4e5b980-d235-11e9-8fa9-5f76ee4dff57.png)

```

I am not sure what the reason for this is...

**Comment by TwentyFourMinutes** [comment]
Also if it is the case that `netcoreapp3.0` is the only possible TargetFramework, the template for RazorClassLibraries should be updated. They currently use `netstandard2.0`.

**Comment by TwentyFourMinutes** [comment]
For anyone else interested and having the same issue, you need to add this attribute `<AddRazorSupportForMvc>true</AddRazorSupportForMvc>` to your .csproj of the RCL.
