### ISSUE TITLE
blazor causing visual studio 2019 preview crash

### ISSUE THREAD

**Issue by davidmather** [aspnet/AspNetCore#13803]
### Describe the bug
Visual Studio crash using blazor framework
Hi, I was trying out the blazor framework and noticed that if I navigate to a url that doesn't exist then visual studio creates thousands of "script documents" and crashes

### To Reproduce
Create a new Blazor web assembly app in visual studio 2019. Open the app in chrome and wait for it to load.
Navigate to a url that doesn't exist.

### Expected behavior
Visual studio crash

### Screenshots
![image](https://user-images.githubusercontent.com/13389155/64480863-5a4a6480-d1c8-11e9-85f0-ec70e2bb34dd.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @davidmather.
We don't support F5 debugging for Blazor WASM projects at the moment. We are going to enable support in the future.
