### ISSUE TITLE
How do I implement Office 365 Authentication in ASP.NET Core and Blazor (Server-Client app)

### ISSUE THREAD

**Issue by Sharafudeen** [aspnet/AspNetCore#13808]
Hi,

I have downloaded and installed "ASP.NET Core and Blazor updates in .NET Core 3.0 Preview 9".

I wanted to implement Office 365 Authentication in ASP.NET Core and Blazor (Server-Client app)?

- I have used two layout pages for login and admin panel. When user start the application then it reaches the login page (its layout name is LandingLayout) and once user successful office 365 logged in then it redirects to admin panel (its layout name is MainLayout)

- I need to show/hide menus based on user groups (from office 365 after successful login)

- How do I setup startup Razor Page instead of using index.html (in wwwroot Client app)?

Any help greatly appreciated!!

Thanks and regards,
Sharafudeen

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
