### ISSUE TITLE
Claims / Roles TagHelper

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore#13802]
### Is your feature request related to a problem? Please describe.
I want to make certain features visible depending on roles/claims.

### Describe the solution you'd like
 It would be useful if importing AspNetCore.Identity included taghelpers for that purpose so i can do cshtml like this:

```
<identityRole name="Administrator">
    <a href="linktosomewhere">Administration</>
</claim>
<identityClaim key="somekey" value="someValue">
    <a href="linktosomewhere">Administration</>
</claim>
```

The environment tag helper works similarly, which is very useful at times.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/3785? https://www.davepaquette.com/archive/2017/11/05/authorize-tag-helper.aspx was the answer that the issue recommends.

**Comment by taori** [comment]
Duplicate of https://github.com/aspnet/Mvc/issues/3785 indeed - though i like the attribute based solution better.

**Comment by taori** [comment]
Duplicate of https://github.com/aspnet/Mvc/issues/3785 indeed - though i like the attribute based solution better.

and reopened again... not sure why this wasn't implemented and why the ticket is closed instead. This really should be a thing.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Per @pranavkm 's suggestion, such functionality is already provided by the community and there is no point in us doing the same. We recommend using it as it's has been around for some time now.
