### ISSUE TITLE
Reconnection - components-reconnect-modal

### ISSUE THREAD

**Issue by Legends** [aspnet/AspNetCore#13813]
**Docs says:**
_When the client detects that the connection has been lost, a default UI is displayed to the user while the client attempts to reconnect. If reconnection fails, the user is provided the option to retry. To customize the UI, define an element with `components-reconnect-modal` as its `id` in the _Host.cshtml Razor page. The client updates this element with one of the following CSS classes based on the state of the connection:

`components-reconnect-show` – Show the UI to indicate the connection was lost and the client is attempting to reconnect.
`components-reconnect-hide` – The client has an active connection, hide the UI.
`components-reconnect-failed` – Reconnection failed. To attempt reconnection again, call `window.Blazor.reconnect()`._

### To Reproduce
- Latest .net core preview, lastest VS Preview
- Blazor Server App

Putting an `<p>` element with `components-reconnect-modal` as its **id** in the _Host.cshtml doesn't seem to get updated with those css classes above.
So when I switch to `offline` in chrome, I expect the `components-reconnect-show` class to be applied tho this element, but it doesn't.

### Additional context
Include the output of `dotnet --info`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Legends .
Switching Chrome to `offline` doesn't terminate the connection.
You can try to close shut down the server to simulate this.
