### ISSUE TITLE
[Preview9][Blazor server-side] Service injected in multiple components results into db exception

### ISSUE THREAD

**Issue by glararan** [aspnet/AspNetCore#13825]
### Describe the bug
Class `DataService` registered as `AddTransient` is injected by following components:

- MainLayout (layout)
- Partners (component)
- Index (page)

All of them calls service in `protected override async Task OnInitializedAsync()`
via e.g.
`await DataService.GetData();`

One of method looks like
`public async Task<PartnerSettingModel> GetPartnerSettingAsync()
        {
            return new PartnerSettingModel
            {
                Links = (await db.Settings.Where(x => x.Key == "Partners" && x.Name == "Links").SingleOrDefaultAsync())?.Value,
                Images = (await db.Settings.Where(x => x.Key == "Partners" && x.Name == "Images").SingleOrDefaultAsync())?.Value.Replace("\r\n", ""),
                Alt = (await db.Settings.Where(x => x.Key == "Partners" && x.Name == "Alts").SingleOrDefaultAsync())?.Value
            };
        }`

I suppose somehow `OnInitializedAsync` is not called async? If I comment everything out except MainLayout it works. When I add <Partners> component calling method above I get exception.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.0-preview9-19423-09'
2. Create class DataService injecting DbContext with method using async
3. Call DataService from each component using `OnInitializedAsync`
`An unhandled exception occurred while processing the request.
InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.`

### Expected behavior
No exception

### Additional context
Just upgraded from Blazor preview 8.

Anything I missed from migration documentation?

**Comment by glararan** [comment]
Okay figured it out by using inside components following code
`@inherits OwningComponentBase<DataService>`

but there is question... what if I need to use two services using database?
inherits is allowed just single time? How to access second inherit?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

On the base class there is a property called `ScopedServices`, which should be used to access other services.
