### ISSUE TITLE
The nuget version is not v3.

### ISSUE THREAD

**Issue by MonkSoul** [aspnet/AspNetCore#13823]
https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Core/

**Comment by pranavkm** [comment]
@MonkSoul if you're asking about the package - part of this announcement states that this package will no longer be produced starting with v3. The recommendation is to target framework instead. Our migration guide - https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#update-the-project-file - has steps for upgrading which includes removing this package.

**Comment by MonkSoul** [comment]
This problem have now been sorted
