### ISSUE TITLE
Is launchSettings.json required in NuGet package?

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#13822]
I have a bunch of Blazor(Razor) class libraries. One of the users of my component library is having an issue when he tries to add a NuGet package. details here https://github.com/stsrki/Blazorise/issues/248

What I wan't to know, can I safely remove a `launchSettings.json` from NuGet packages? Is it really needed to be packaged?
I tried to look around to find out how other people are packing their NuGet(s) and as I can see almost all of them are also including this file.

**Comment by Pilchie** [comment]
NuGet packages should generally *not* contain `launchSettings.json`.  NuGet packages generally provide *libraries*, and `launchSettings.json` instructs VS about how to launch *apps*.
