### ISSUE TITLE
Can not add a .razor file as a link to a Blazor project

### ISSUE THREAD

**Issue by KoenVanExem** [aspnet/AspNetCore#13828]
### Describe the bug
Adding a linked .razor file to a Blazor project (app or library) does not work.

### To Reproduce
1. Using .NET Core SDK (3.0.100-preview9-014004)
2. Create a Blazor Server App
3. Create the file "Linked.razor" outside of the project folder (e.g. in the solution folder)
4. Add the file as a link in visual studio or directly to the the .csproj file
5. Start the application and change the url to "/linked"

BlazorApp.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Linked.razor" Link="Linked.razor" />
  </ItemGroup>

</Project>
```

Linked.razor
```
@page "/linked"

Hi, I'm a linked Blazor page!
```

### Expected behavior
The linked page should be shown.

### Additional context
Generated code from linked razor files in Razor Class Libraries have compile errors.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please try to change the `None` node with `Content` and see whether that fixes the issue.

**Comment by KoenVanExem** [comment]
Yes, that fixed it.
Thanks.
