### ISSUE TITLE
ScaffoldingReadMe.txt

### ISSUE THREAD

**Issue by ice19942335** [aspnet/AspNetCore#13831]
Hello. Right-click on project -> Add -> Area
result hire https://c2n.me/43uZzjj.png

Core 3 has to use the endpoint.
ScaffoldingReadMe.txt says me to use "app.UseMvc(routes => {///})"

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ice19942335.
@ajaybhargavb can you please look into this? Thanks!

**Comment by ice19942335** [comment]
Thanks.
