### ISSUE TITLE
Large number of duplicate strings related to Regex use in RouteAttributes when profiling memory

### ISSUE THREAD

**Issue by nickalbrecht** [aspnet/AspNetCore#13839]
This isn't as pronounced in a new application, but in larger projects with complex routing, the problem grows. 

**Summary**
I'm seeing a large number of duplicate strings related to regular expressions (5000+ in the worst single instance for a string) when doing some memory profiling (dotMemory by Jetbrains). I originally noticed this on ASPNETCore 2.2 since that's the current runtime I'm using, however I'm seeing it on 3.0 Preview 9 too. It's not as pronounced in a brand new application as the number of occurrences seems to be connected to the complexity of the routing.

**Steps to reproduce the behaviour:**
1. Using ASP.NET Core 3.0 Preview 9
2. Create a new MVC Web application
4. Add a new route to the home controller with the following. I'm using the same regex expression as my app has on a single action, since they are distinct and easy to spot in the memory profiler. But really the symptom is there with any regex
```
        [Route(@"/{argOne:regex(^\w{{4}}\d{{2,3}}$)}/{argTwo:regex(^\d{{2}}-\d{{6,10}}$)}/{actionName?}")]
        [Route(@"/Home/{argTwo:regex(^\d{{2}}-\d{{6,10}}$)}/{actionName?}")]
        public IActionResult Test()
        {
            return View("Index");
        }
```
This is meant to capture routes like "ABCD20/10-12345678" or "Home/10-12345678"

5. I'm using dotMemory by JetBrains, but I'm assuming the same or similar behaviour would be visible in other tools. Navigate to any page in the program, then request a snapshot from dotMemory, and I see the regex expression "^\d{2}-\d{6,10$}" appears 6 times and "^\w{4}\d{2,3}$" appears 4 times.

6. Now if you stop the app, and add some new `RouteAttribute` usages in your application, and repeat the steps above , the number of regular expression occurrences have gone up. Adding a few other actions using `RouteAttribute`s that use similar routes with the same `:regex()` and it will go up further, this seems to be multiplicative between the number of `RouteAttribute`s that use `:regex()` and the ones that don't (in my main app where I first noticed it anyways)

**Notes:**
Because of the multiplicative nature of the problem, it grows larger in more complex projects. I've counted 10 `RouteAttribute`s in my app that are using the  `:regex()` to help provide user friendly URLs that validate against the known format of the business identifiers; and many explicit RouteAttributes that don't use `:regex()` at all. If I simply comment out the 10 definitions using regex, and repeat my profiling, the duplicate strings disappear from the profiling snapshot.

The original symptom in my app that made me investigate this, using the better part of a MB over thousands of occurrences, that as far as I can tell, aren't needed?

**Expectation**
Ideally the impact/occurrences count of regex strings used in `regex:()` for `RouteAttribute`s should be more reasonable in applications that have many routes defined

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nickalbrecht.
@rynowak can you please look into this? Thanks!

**Comment by rynowak** [comment]
Would it be possible to share the dump? I'm interested to know if there's something going wrong in your case.

I would kinda expect what you're seeing to be the case, we don't have any infrastructure in place that tries to cache strings across route template instances.  This is probably something we can improve.

---

If you want to low-tech solution for this, you can write your own constraints that subclass [RegexRouteConstraint](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/Constraints/RegexRouteConstraint.cs#L25) https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#custom-route-constraints - create one of these for each of your flavours of regex and give it its own name in the constraint map.

This will make your code a little nicer/more maintainable to look at as well, by giving you semantic names to work with.

```C#
        [Route(@"/{argOne:postalcode}/{argTwo:accountid}/{actionName?}")]
        public IActionResult Test()
        {
            return View("Index");
        }
```

**Comment by nickalbrecht** [comment]
I'm not sure I can provide the dump, it's not an app with our own information, but a client's with their customer information in it. That and the sucker was a gig and a half because of native memory usage. If I remember, the actual managed memory footprint was only like 200MB.
I will definitely look at your suggestion of an subclass. If I get some time, I will try to isolate out their private information so that it's just the app information left.

**Comment by rynowak** [comment]
I'll put together something based on your ideas and look at the memory myself. If you're tryign to bring down the managed memory usage, I'll bet that it will be much more impactful to share the Regex object than to share the strings that begat them - subclassing `RegexRouteConstraint` would allow you to do that.

**Comment by nickalbrecht** [comment]
So question then about route attributes/route constraints. Even though I have only 10 routes that have _any_ regex route constraints on them at all, why over 5000 instances of the regex string in memory for the app? I'm entirely speculating here, maybe I have ~500 endpoints in my app (I've never counted), I but I don't understand why it would have so many instances of the regex (and by hypothesis, instances of `RegexRouteConstraint`) versus having it match the number of usages in routes?

If I subclass `RegexRouteConstraint` to try and reduce the number of regex strings/objects created internally via some sort of cache/dictionary, is it still going to create 5000 instances of my subclassed `RegexRouteConstraint`?

**Comment by rynowak** [comment]
> If I subclass RegexRouteConstraint to try and reduce the number of regex strings/objects created internally via some sort of cache/dictionary, is it still going to create 5000 instances of my subclassed RegexRouteConstraint?

Yes that's what I would expect. 

> Even though I have only 10 routes that have any regex route constraints on them at all, why over 5000 instances of the regex string in memory for the app?

I'm not sure why that is, you'd be able to figure that out by looking at a memory dump. What I can tell you is that we don't create constraints per-request, they are always created up front and cached.

**Comment by nickalbrecht** [comment]
Not quite ready to close this one Mr Bot. :-P I'm still trying to find time to investigate this.
