### ISSUE TITLE
TimeSpan property not bound

### ISSUE THREAD

**Issue by thanuja89** [aspnet/AspNetCore#13844]
We recently tried migrating to .NET Core preview 9.

We had a TimeSpan property in the model that we used in an Web Api Controller POST method. When we ran our integration tests, we noticed that the model would not be bound, but if we commented out the property, it works. 

### Expected behavior
The model to be bound successfully

### Additional context
We use Microsoft.AspNet.WebApi.Client 5.2.7 on integration tests project and for POST requests, we use the PostAsJsonAsync extension method.

output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @thanuja89.
Are there any errors in the `ModelState` in your action, when model binding fails?
Can you please share these errors, if any?

**Comment by thanuja89** [comment]
Yes @mkArtakMSFT

There is one error in the model state.

"The JSON value could not be converted to System.TimeSpan. Path: $.Leads[0].PreferredContactTime | LineNumber: 0 | BytePositionInLine: 565."

**Comment by mkArtakMSFT** [comment]
This issue was moved to dotnet/corefx#41031
