### ISSUE TITLE
.Net Core 3.0 Preview 9 Blazor Logging Issue

### ISSUE THREAD

**Issue by mfitconsultants** [aspnet/AspNetCore#13849]
After upgrading my `preview 8` project o `preview 9`, at runtime I am getting the following error (initially after the page has loaded and redirected and if I call for example `logger.LogDebug()`;

> WASM: ﻿Unhandled exception rendering component:
> 
> WASM: System.MissingMethodException: Method not found: System.Threading.Tasks.Task`1<!!0> Microsoft.JSInterop.IJSRuntime.InvokeAsync<!0>(string,object[])
> 
> WASM:   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) <0x2df6998 + 0x0003e> in <d9c16b0fee7344919775df5988c885d0>:0 
> 
> WASM:   at Blazor.Extensions.Logging.BrowserConsoleLogger.Log[TState] (Microsoft.Extensions.Logging.LogLevel logLevel, Microsoft.Extensions.Logging.EventId eventId, TState state, System.Exception exception, System.Func`3[T1,T2,TResult] formatter) <0x2df64b0 + 0x00094> in <3eb34b93cd4a47bf804fb0648b089edf>:0 
> 
> WASM:   at Microsoft.Extensions.Logging.LoggerMessage+<>c__DisplayClass4_0.<Define>b__0 (Microsoft.Extensions.Logging.ILogger logger, System.Exception exception) <0x2df4fd8 + 0x00058> in <c98f99c825e44b82bb41cc6b7ff3d612>:0 
> 
> WASM:   at (wrapper delegate-invoke) System.Action`2[Microsoft.Extensions.Logging.ILogger,System.Exception].invoke_void_T1_T2(Microsoft.Extensions.Logging.ILogger,System.Exception)
> 
> WASM:   at Microsoft.Extensions.Logging.LoggingExtensions.UserAuthorizationFailed (Microsoft.Extensions.Logging.ILogger logger) <0x2df4c08 + 0x00014> in <85acc2b572f448f39259eac9936732f8>:0 
> 
> WASM:   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync (System.Security.Claims.ClaimsPrincipal user, System.Object resource, System.Collections.Generic.IEnumerable`1[T] requirements) <0x2de4180 + 0x00338> in <85acc2b572f448f39259eac9936732f8>:0 
> 
> WASM:   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.IsAuthorizedAsync (System.Security.Claims.ClaimsPrincipal user) <0x2d54958 + 0x00228> in <5266bbb196bb40a89b886a09631725e6>:0 
> 
> WASM:   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync () <0x2d53398 + 0x0026c> in <5266bbb196bb40a89b886a09631725e6>:0 
> 
> WASM:   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion (System.Threading.Tasks.Task task) <0x2e0df30 + 0x00118> in <cc81133ac6304aada69282c517e2b811>:0 
> 
> WASM:   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2bbb2e8 + 0x00248> in <cc81133ac6304aada69282c517e2b811>:0 
> 
> WASM: Unhandled exception rendering component:
> 
> WASM: System.MissingMethodException: Method not found: System.Threading.Tasks.Task`1<!!0> Microsoft.JSInterop.IJSRuntime.InvokeAsync<!0>(string,object[])
> 
> WASM:   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) <0x2df6998 + 0x0003e> in <d9c16b0fee7344919775df5988c885d0>:0 
> 
> WASM:   at Blazor.Extensions.Logging.BrowserConsoleLogger.Log[TState] (Microsoft.Extensions.Logging.LogLevel logLevel, Microsoft.Extensions.Logging.EventId eventId, TState state, System.Exception exception, System.Func`3[T1,T2,TResult] formatter) <0x2df64b0 + 0x00094> in <3eb34b93cd4a47bf804fb0648b089edf>:0 
> 
> WASM:   at Microsoft.Extensions.Logging.LoggerMessage+<>c__DisplayClass4_0.<Define>b__0 (Microsoft.Extensions.Logging.ILogger logger, System.Exception exception) <0x2df4fd8 + 0x00058> in <c98f99c825e44b82bb41cc6b7ff3d612>:0 
> 
> WASM:   at (wrapper delegate-invoke) System.Action`2[Microsoft.Extensions.Logging.ILogger,System.Exception].invoke_void_T1_T2(Microsoft.Extensions.Logging.ILogger,System.Exception)
> 
> WASM:   at Microsoft.Extensions.Logging.LoggingExtensions.UserAuthorizationFailed (Microsoft.Extensions.Logging.ILogger logger) <0x2df4c08 + 0x00014> in <85acc2b572f448f39259eac9936732f8>:0 
> 
> WASM:   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync (System.Security.Claims.ClaimsPrincipal user, System.Object resource, System.Collections.Generic.IEnumerable`1[T] requirements) <0x2de4180 + 0x00338> in <85acc2b572f448f39259eac9936732f8>:0 
> 
> WASM:   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.IsAuthorizedAsync (System.Security.Claims.ClaimsPrincipal user) <0x2d54958 + 0x00228> in <5266bbb196bb40a89b886a09631725e6>:0 
> 
> WASM:   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync () <0x2d53398 + 0x0026c> in <5266bbb196bb40a89b886a09631725e6>:0 
> 
> WASM:   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion (System.Threading.Tasks.Task task) <0x2e0df30 + 0x00118> in <cc81133ac6304aada69282c517e2b811>:0 
> 

Which seems to relate to my Logger being injected. now I have followed Dan Roths blog post here;

[asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/)

In my `startup.cs` I add the logger to `ConfigureServices` as follows;

            services.AddLogging(builder => builder
               .AddBrowserConsole() 
               .SetMinimumLevel(LogLevel.Trace)
           );

My `_Imports.Razor` is as follows (I have removed local namespaces);

```
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.Authorization
@using System.Net.Http
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.JSInterop
@using Microsoft.Extensions.Logging
@using Blazored.LocalStorage
@using Blazorise
@using Blazorise.Sidebar
```

I then inject the logger to my `Login.Razor` page;

    @inject ILogger<Login> logger

The project is currently set to redirect any unauthorized users to the login page to login. As of `preview 8` this worked, after upgrading to `preview 9` could this be due to the decoupling of the authorization from the routing?

In my `App.Razor` I have updated to use the `AuthorizeRouteView`;

```
<Router AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
        <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
            <NotAuthorized>
                <p>Nope, nope!</p>
            </NotAuthorized>
        </AuthorizeRouteView>
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
```

And then in my `MainLayout.Razor`;

```
@inject NavigationManager UriHelper
@inherits LayoutComponentBase

<div class="sidebar">
    <NavMenu />
</div>

<div class="main">
    <div class="top-row px-4">
        <LoginDisplay />
    </div>

    <div class="content px-4">
        @Body
    </div>
</div>


@functions
{
    [CascadingParameter] 
    private Task<AuthenticationState> authenticationStateTask { get; set; }

    protected override async Task OnInitializedAsync()
    {
        var authState = await authenticationStateTask;
        var user = authState.User;

        if (!user.Identity.IsAuthenticated)
        {
            UriHelper.NavigateTo(@"\login");
        }
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Seems like you're still running into a package-incompatibility problem. Seems like the Browser.Console.Logger pacakage hasn't been updated and is still referencing Preview8 bits.

**Comment by mfitconsultants** [comment]
@mkArtakMSFT All the packages seem to be present and correct and at preview 9.

If I inject the logger in the `@code` element it works just fine

```
@code {

    [Inject]
    protected ILogger<Login> logger {get;set;}

    private async Task HandleLogin()
    {
        logger.LogDebug("HandleLogin");
       /*...*/
    }
```

The error disappears, and the issue is only there if I inject at the top of the Razor page?

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @mfitconsultants.
Would be great if you could provide us with a minimalistic sample project, so we can easily reproduce this.
