### ISSUE TITLE
Question: Dynamic title tag for Blazor app

### ISSUE THREAD

**Issue by sven5** [aspnet/AspNetCore#13857]
### Is your feature request related to a problem? Please describe.
Hi, I'd like to dynamically change the `<title>` tag for a Blazor app.
Since the title is normally defined in a static asset, like `index.html` or `index.cshtml` this seems impossible so far. However, with the help of `LayoutComponentBase` this would work when defining all `head` information there. Then the `script` tags would also be defined there - but this is not recommended.

Today, is there any solution for this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sven5. We're tracking this ask as part of #10450
