### ISSUE TITLE
High TCP connection count on Azure App Services - investigate stale loopback connections

### ISSUE THREAD

**Issue by tweek82** [aspnet/AspNetCore#13866]
ASP.Net Core 2.1 WebAPI
+ Azure SQL Server
+ Azure REDIS Premium

We have a webapi hosted on Azure App Services on a two instance P2V2 plan. At it highest load it currently will take up 7000 requests per minute. This runs fine most of the time. 
But, when Azure swaps the instances in the background, or when we publish a new version from Visual Studio into this app service, the TCP count piles up and doesn't decrease, most of the times causing TCP exhaustion.

Things we checked using the metrics, Profiler Trace and Network trace tooling from Azure:
- Redis (client)connections are stable
- SQL Connections are stable

Sample 1: a new instance is started
![hightcp1](https://user-images.githubusercontent.com/4486709/64643862-a4725680-d411-11e9-9d74-a259b1d15290.jpg)

Sample 2, after we deployed to a staging-deploymentslot. Warmed it up, and swapped it to production:
![hightcp2](https://user-images.githubusercontent.com/4486709/64643908-c10e8e80-d411-11e9-8bc7-2c4426efef3b.jpg)

High TCP isn't particularly a bad thing I guess, but it should decrease quickly.

I've run many Network traces. Opened them in MS Message Analyzer and Wireshark, but I can't seem to find out which process is taking up these connections.

Any ideas? Many thanks in advance!

**Comment by shirhatti** [comment]
> most of the times causing TCP exhaustion

How is the exhaustion manifesting? Are you seeing request failures.
In ASP.NET Core 2.1 applications the native IIS modules reverse proxies requests to Kestrel via the loopback adapter and as such high TCP port usage is expected.

> the TCP count piles up and doesn't decrease

This is unexpected. Can you share more information on what kind of requests are being sent to the server? Are you using WebSockets?

**Comment by tweek82** [comment]
Hi @shirhatti , 

> How is the exhaustion manifesting? Are you seeing request failures.

In the situation below (occurred yesterday) a new instance was started by Azure self, and the TCP piled up until 6000. This is beyond the TCP limits for the P2V2 plan and so any outgoing request fails. We get failing requests and some requests take up to 5 minutes.
![6000tcp](https://user-images.githubusercontent.com/4486709/64694719-9fa5b500-d49a-11e9-83f7-080c5caeaa37.jpg)


> Can you share more information on what kind of requests are being sent to the server? Are you using WebSockets?

The kind of requests are all from an iOS and Android app and a ReactJS web application. We don't use websockets and this option is disabled on the app service configuration.

I find it hard relating all information Azure has available to me to these incidents (metrics, TCP statistics, Application Insights etc).

**Comment by shirhatti** [comment]
Just from a quick glance at the graph, an interesting observation is that the loopback connections don't seem to grow rapidly, but rather show an instantaneous spike.

@jkotalik Is that indicative of anything to you?

**Comment by tweek82** [comment]
> Just from a quick glance at the graph, an interesting observation is that the loopback connections don't seem to grow rapidly, but rather show an instantaneous spike.

I would expect this to occur when a .NET Core webapplication gets started (reboot, or Azure instance swap) without warming up, perhaps a http-queue piles up. But then I would also expect that after warmup, these requests are handled and that the connection(s) are closed. Or at least timed out. And so this graph will decrease quickly and not slowly over a timespan of 7 hours.

**Comment by ronpal** [comment]
@tweek82 we are having the same issue, and I'm curious: are you also seeing a great deal of 'ClientConnectionFailure' exceptions? Just wondering if they are related, although these posts suggest otherwise: 

https://stackoverflow.com/questions/56862256/api-management-service-clientconnectionfailure-at-forward-request
https://stackoverflow.com/questions/58006974/whats-the-difference-between-transfer-response-and-forward-request-errors-in-ap/58020277

**Comment by anurse** [comment]
When requests from ANCM to the back-end ASP.NET Core server finish, the connections aren't necessarily released (in case other requests need to be made). They *should* be timing out after a relatively short period though (and it looks like you're seeing these connections hang around for multiple hours).

We'll take a look and see what we can find in ANCM here.

**Comment by anurse** [comment]
> I've run many Network traces. Opened them in MS Message Analyzer and Wireshark, but I can't seem to find out which process is taking up these connections.

@tweek82 are you able to provide one of these network traces? I presume these are from **on the server itself**? If something is still processing the requests then the idle timeout won't trigger. If you can provide them, send them to me by email at `[my github username]@microsoft.com`

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

If you sent the traces, let me know. I don't believe I've received them.
