### ISSUE TITLE
No DefaultChallengeScheme found from preview8 to preview9

### ISSUE THREAD

**Issue by Hantse** [aspnet/AspNetCore#13862]
Hello,

I just update my application to preview9 and i have a exception working with preview8.

> System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).

I change nothing except update to preview9 and asp package update. And i hacve already configure a auth.

`            services.AddAuthentication(options =>
            {
                options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            });
`

Kind regards,

**Comment by blowdart** [comment]
@HaoK

**Comment by HaoK** [comment]
Can we see the rest of your startup?

**Comment by Hantse** [comment]
Sure

`
public void ConfigureServices(IServiceCollection services){
 services.AddAuthentication(
               options =>
               {
                   options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                   options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                   options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
               })
               .AddJwtBearer(configuration.SchemeName, cfg =>
               {
                   cfg.RequireHttpsMetadata = configuration.Metadata;
                   cfg.SaveToken = configuration.SaveToken;

                   cfg.TokenValidationParameters = new TokenValidationParameters()
                   {
                       ValidIssuer = configuration.Issuer,
                       ValidAudience = configuration.Audience,
                       IssuerSigningKey = _signingKey
                   };

                   cfg.Events = new JwtBearerEvents()
            {
                OnMessageReceived = context =>
                {
                    StringValues accessToken = context.Request.Query["access_token"];

                    if (!string.IsNullOrEmpty(accessToken))
                    {
                        context.Token = context.Request.Query["access_token"];
                    }

                    return Task.CompletedTask;
                }
            };
 });
}
`
`
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory){
    app.UseHsts()
                .UseCorrelationId()
                .UseHealthCheck()
                .UseRouting()
                .UseAuthentication()
                .UseAuthorization();
}
`

I try, and remove  cfg.Events = new JwtBearerEvents() and finally work, something bad with my implementation of events ?

**Comment by HaoK** [comment]
You need to add a jwtbearer scheme with the name you set as the default, you shouldn't be passing in the .AddJwtBearer(configuration.SchemeName), unless you are registering that as the default as well.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
