### ISSUE TITLE
Use an embedded CAB for the Asp.NET SharedFramework MSI

### ISSUE THREAD

**Issue by johnbeisner** [aspnet/AspNetCore#13875]
Some modifications will be necessary to ASP.NET to accommodate the new installer. Most notably is the requirement to embedded CAB files in the MSIs.

1. Use an embedded CAB for the Asp.NET sharedframework MSI

2. Keep the MSI naming convention the same as it is versioned and unique
aspnetcore-runtime-3.0.0-rc2.19459.5-win-x64.msi
aspnetcore-runtime-3.0.0-rc2.19459.5-win-x86.msi

3. Continue to drop the MSI at blob storage

**Comment by joeloff** [comment]
Effectively, we need to change the Media element in the MSI and then update the Package fragment we compile for the wixlib that allows the MSIs to be shared between the SDK, ASP.NET and Windows Hosting bundle.

**Comment by jkotalik** [comment]
@joeloff can this be closed?
