### ISSUE TITLE
WASM Blazor Error: RAZORGENERATE : error RZ3008: Tag helpers cannot target tag name '<global namespace>.

### ISSUE THREAD

**Issue by mylifelineio** [aspnet/AspNetCore#13881]
Version: 3.0.0-preview9.19424.4

### Describe the bug
Getting the following error separating View from Model inheriting from ComponentBase. This is a WASM Blazor project.

RAZORGENERATE : error RZ3008: Tag helpers cannot target tag name '<global namespace>.ViewCustomerModel' because it contains a '<' character.

### To Reproduce
```
public class ViewCustomerModel: ComponentBase
{
    [Inject]
    protected IDataService Data {get;set;}

    [Parameter] 
    public Guid CustomerId {get;set;}
    public Customer Customer {get;set;}

    protected override async Task OnInitializedAsync() 
    {
        await Load();
    }

    private async Task Cancel() => await Load();

    private async Task Load()
    {
        Customer = await Data.Load<Customer>(CustomerId);
    }

    private async Task Save(EditContext editContext)
    {
        if (editContext.Validate())
        {
            await Data.Save<Customer>(Customer);
        }
    }
}
```

### Expected behavior
No compile error.

### Additional context
Build FAILED.

RAZORGENERATE : error RZ3008: Tag helpers cannot target tag name '<global namespace>.ViewCustomerModel' because it contains a '<' character. [/Users/antonswanevelder/_mor/mor.customer/app/mor.customer.app.csproj]
.
.

### Works as @code on View

```
@page "/viewcustomer"
@page "/viewcustomer/{customerId}"
@using mor.customer.Models;
@using mor.Services;
@inject IDataService Data;
.
.
.
@code {
    [Parameter] 
    public Guid CustomerId {get;set;}
    public Customer Customer {get;set;}

    protected override async Task OnInitializedAsync() 
    {
        await Load();
    }

    private async Task Cancel() => await Load();

    private async Task Load()
    {
        Customer = await Data.Load<Customer>(CustomerId);
    }

    private async Task Save(EditContext editContext)
    {
        if (editContext.Validate())
        {
            await Data.Save<Customer>(Customer);
        }
    }

    private async Task OnKeyAction(KeyboardEventArgs e)
    {
        if (e.Key == "Escape") 
        {
            await Cancel();
        }
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Is `ViewCustomerModel` in a global namespace? Does this issue repro, if you move the class into a namespace?

If not, please provide a minimalistic repro project so we can investigate.

**Comment by mylifelineio** [comment]
Dear Artak, thanks so much, that was indeed the issue, once wrapped in a namespace the error is gone. Thanks for your assistance and creating us such a great product.
