### ISSUE TITLE
Accessing SignInManager from class libraries

### ISSUE THREAD

**Issue by jlnostr** [aspnet/AspNetCore#13887]
## Describe the bug
In ASP.NET Core 2.x it was possible to access the `SignInManager` inside class libraries. The dependencies were resolved using DI, so I could write classes that access both the `UserManager` and the `SignInManager`. With ASP.NET Core 3 this is not working anymore.

Through the `Microsoft.Extensions.Identity.Core` package I can still reference the `UserManager`, but the `SignInManager` is not in there. If I change the project SDK to `Microsoft.NET.Sdk.Web`, everything is working as expected. But now a static Main method is required, something that I don't want in a class library.

### To Reproduce
1. Use ASP.NET Core 3.0 preview 9
2. Create a new empty app
3. Create a new class library in the same solution
4. Try to create a class that references the `SignInManager`

### Expected behavior
I've expected to see the `SignInManager` as well inside the `Microsoft.Extensions.Identity.Core` package, so using it from class libraries is still possible.

### Additional context
Output of `dotnet --info`:

```
▶ dotnet --info                 
.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Laufzeitumgebung:
 OS Name:     antergos
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/3.0.100-preview9-014004/

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  2.2.108 [/opt/dotnet/sdk]
  3.0.100-preview9-014004 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.6 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by blowdart** [comment]
UserManager lives on because it targets netstandard. Signin manager is tightly coupled to asp.net, cookies, http and so on, so it's not meant for class libraries. This is by design.

@davidfowl do you have any suggestions?

**Comment by ryhled** [comment]
Me too, noticed this when i upgraded to newest preview (this broke the code). Also have a separation in which an extended signinmanager resides in class library. And if one would for example have handlers taking a signinmanager as injected dependency, i guess this means you are locked into having all these handlers reside only in the main project.

Is this something that might be changed or it is set in stone?

**Comment by davidfowl** [comment]
Your class library needs to target both .NET Core 3.0 and it needs a FrameworkReference to Microsoft.AspNetCore.App.

**Comment by jlnostr** [comment]
Thanks, that solved the issue.
