### ISSUE TITLE
Oninput is not working with bind in Blazor preview9

### ISSUE THREAD

**Issue by Manishbtech** [aspnet/AspNetCore#13883]
The syntax onkeyup="(this.dispatchEvent(new CustomEvent('change', { bubbles: true })))" is not working in Blazor preview9. Can anyone suggest the solution?

**Comment by rynowak** [comment]
This should be `@onkeyup="..."`

**Comment by Manishbtech** [comment]
@rynowak...I have tried the same but still facing the same issue. I am able to use tgis syntax in preview6 but not in preview9

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by Manishbtech** [comment]
public string SearhText { get; set; } = string.Empty;

<InputText @onkeypress="@(e => OnKeyPress(e, writtenObj))" @onchange="@(e =>OnKeyChange(e, writtenObj))" @bind-Value="@SearhText" />

 public void OnKeyChange(ChangeEventArgs args)
        {
           
         Console.WriteLine(SearhText);
       
        }

I want the updated value of SearchText field on every onkeypress event in order to implement the auto search functionality.

**Comment by Manishbtech** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

Hi @mkArtakMSFT 

public string SearhText { get; set; } = string.Empty;

<InputText @onkeypress="@(e => OnKeyPress(e, writtenObj))" @onchange="@(e =>OnKeyChange(e, writtenObj))" @bind-Value="@SearhText" />

public void OnKeyChange(ChangeEventArgs args)
{

     Console.WriteLine(SearhText);
   
    }
I want the updated value of SearchText field on every onkeypress event in order to implement the auto search functionality.

**Comment by pranavkm** [comment]
@Manishbtech `InputText` does not support `oninput` today. You might have more success using `input` rather than `InputText`. I'd recommend using StackOverflow if you need more help with figuring this out.
