### ISSUE TITLE
Razor components: error using await in Razor expressions (Preview 9)

### ISSUE THREAD

**Issue by mv10-work** [aspnet/AspNetCore#13888]
Both [implicit](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0#implicit-razor-expressions) and [explicit](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0#explicit-razor-expressions) Razor expressions result in the following error if `await` is used in a Razor component:

> The 'await' operator can only be used within an async method.

```razor
<p>@await Test()</p>
<p>@(await Test())</p>

@code {
    private async Task<string> Test() => "foo";
}
```

This only happens in .razor files, whether they're in a Blazor project or a Razor library. It is working normally in .cshtml files in the same Blazor project. Is this a limitation of Razor components? (Why?) It isn't mentioned in the [component docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0) or the general Razor syntax doc linked earlier, so I just assumed normal Razor syntax should work.

VS 2019 16.3.0 Preview 3 and Core 3.0 Preview 9

![image](https://user-images.githubusercontent.com/54578900/64702459-973c8280-d478-11e9-8cb2-c825984563f2.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mv10-work.
Support for asynchronous work in UI related contexts is not supported. We are going to provide guidance about how to do asynchronous work in Blazor as part of : https://github.com/aspnet/AspNetCore.Docs/issues/14260
