### ISSUE TITLE
Prompt user to install .Net Core Runtime

### ISSUE THREAD

**Issue by Safirion** [aspnet/AspNetCore#13898]
### Is your feature request related to a problem? Please describe.

When a user tries to run a non-autonomous .Net Core Desktop application (WPF) without having the .Net Core runtime (+ .NET Core Desktop Runtime) installed, nothing happens. The only thing that happens is the creation of a log in the windows event viewer.

### Describe the solution you'd like

Like in .Net Framework, a pop-up prompt the user to install the required version of .Net Core Runtime by redirect him to https://dot.net or, in a perfect world, the required version of .Net Core Runtime is automatically downloaded and installed after asking the users :

![image](https://user-images.githubusercontent.com/11511729/64717839-53239f00-d4c5-11e9-8d8a-bf8c722992b4.png)

At least, an error pop-up would be fine for .Net Core 3.0 release.

**Comment by blowdart** [comment]
This is the asp.net core repo, not the dotnet core repo which is over at https://github.com/dotnet/

@mkArtakMSFT can you move this?

**Comment by mkArtakMSFT** [comment]
This issue was moved to dotnet/corefx#41043
