### ISSUE TITLE
Editor for Blazor razor pages does not provide "Show Potential Fixes"

### ISSUE THREAD

**Issue by rpskelton2** [aspnet/AspNetCore#13892]
When editing a razor page it provides red underlines for issues the editor has detected.  When you hover over this in a c# file you get a "Show Potential Fixes" option.  Blazor does not have this.

c#
![image](https://user-images.githubusercontent.com/7995579/64711003-cac5df80-d46d-11e9-85d9-6efe2983b246.png)

razor
![image](https://user-images.githubusercontent.com/7995579/64711043-dd401900-d46d-11e9-8373-e176c84a6733.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rpskelton2.
This is not yet enabled for Blazor.
