### ISSUE TITLE
context.Features.Get<IHttpMaxRequestBodySizeFeature>() is null during test

### ISSUE THREAD

**Issue by rezvanf** [aspnet/AspNetCore#13895]
### Describe the bug
When writing a XUNIT test for testing for max body sizes, the line

```C#
context.Features.Get<IHttpMaxRequestBodySizeFeature>()
```
throws a error of 

```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
```

```C#
private readonly WebApplicationFactory<XXXX.Startup> _webAppFactory;

 var webAppClient = _webAppFactory
                .WithWebHostBuilder(
                builder =>
                {
                    builder.UseSolutionRelativeContentRoot(@"..\..\", "XXXX.sln");              
                    builder.Configure(app =>
                    {
                        app.Run(async context =>
                        {
                            context.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = 100_000_000;
                        });

                    });
                }
            )
            .CreateClient(clientOptions);
````

### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Expected behavior
`context.Features.Get<IHttpMaxRequestBodySizeFeature>()` not to be and be able to set the value of MaxRequestBodySize to a given value

### Additional context
Include the output of `dotnet --info`
 dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100
 Commit:    b9f2fa0ca8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by davidfowl** [comment]
That’s fine, check for null and noop if it’s null. Features are optional and this one does not need to be in the test server

**Comment by rezvanf** [comment]
.

**Comment by rezvanf** [comment]
Ok I agree about null checking, that makes sense.
In this particular case the unit test is testing a middleware that set value of the  Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize . We have had to provide a *Test* Startup which overrides the Configure and Configure services.

**Comment by anurse** [comment]
> In this particular case the unit test is testing a middleware that set value of the Get().MaxRequestBodySize . We have had to provide a _Test_ Startup which overrides the Configure and Configure services.

Yep, that's the expected way to test a component like this. The test server doesn't provide the feature but you are welcome to register one yourself prior to testing your code.

Closing this as I don't believe there is any actionable work on our end at this time.
