### ISSUE TITLE
Create standard Dictionary class that doesn't throw a KeyNotFoundException

### ISSUE THREAD

**Issue by AdamHess** [aspnet/AspNetCore#13905]
### Is your feature request related to a problem? Please describe.

Dictionaries make a missing element an "KeyNotFoundException" event when in reality is quite common place and can be better managed by a null check when an item in the dictionary. 

This leads to clunky code like 

```
if (dict.TryGetValue(key, out var value))
{
  //do work here
}
```

### Describe the solution you'd like

A standard Dictionary-like class that does not throw KeyNotFoundExeption when key is missing, just returns null. 

### Additional context

This increases the level of complexity for newcomers to the language or coming from another language where the expected behavior when a dictionary is missing a key to return null. 

Additionally, in MANY cases it completely eliminates the  `[ ]` operator being used at all. 

Often developers have to create a custom implementation for accessing dictionaries such can be found here: 

https://stackoverflow.com/questions/14150508/how-to-get-null-instead-of-the-keynotfoundexception-accessing-dictionary-value-b

leading to managing a utility project and duplicate code in the .net ecosystem

**Comment by blowdart** [comment]
This is the asp.net core repo, but your question should be asked in the dotnet core repo which is over at https://github.com/dotnet/

**Comment by AdamHess** [comment]
Whoops my mistake.

**Comment by pranavkm** [comment]
This issue was moved to dotnet/corefx#41044
