### ISSUE TITLE
Blazor - SSB iOS and Windows Authentication issue

### ISSUE THREAD

**Issue by rkone** [aspnet/AspNetCore#13901]
### Describe the bug
When logging into a Blazor SSB Project with Windows Authentication enabled using iOS, the page is unresponsive to input.

### To Reproduce
1. Using ASP.NET Core 3.0 preview 9
2. Create a project using the Blazor Server App template with Windows Authentication option selected.
3. Connect to the created website using an iOS device. After logging in the hamburger control does not open.

**Comment by rkone** [comment]
Here's the log:

> [Info] [2019-09-13T13:03:07.510Z] Information: Normalizing '_blazor' to 'http://user:58219/_blazor'. (blazor.server.js, line 1)
[Error] WebSocket connection to 'ws://user:58219/_blazor?id=a9_65NTKLSIg1jh3OZbp6Q' failed: Unexpected response code: 401
[Error] [2019-09-13T13:03:07.575Z] Error: Failed to start the transport 'WebSockets': Error: There was an error with the transport.
log (blazor.server.js:1:5021)
(anonymous function) (blazor.server.js:1:47994)
(anonymous function) (blazor.server.js:1:40129)
a (blazor.server.js:1:39051)
promiseReactionJob
[Warning] [2019-09-13T13:03:07.578Z] Warning: Call to HttpConnection.stopConnection(Error: WebSocket closed with status code: 1006 ().) was ignored because the connection hasn't yet left the in the connecting state. (blazor.server.js, line 1)
[Error] [2019-09-13T13:03:07.616Z] Error: Failed to start the transport 'LongPolling': TypeError: undefined is not an object (evaluating 'this.transport.onreceive=this.onreceive')
log (blazor.server.js:1:5021)
(anonymous function) (blazor.server.js:1:47994)
(anonymous function) (blazor.server.js:1:40129)
s (blazor.server.js:1:39004)
promiseReactionJob
[Error] [2019-09-13T13:03:07.616Z] Error: Failed to start the connection: Error: Unable to connect to the server with any of the available transports. WebSockets failed: Error: There was an error with the transport. ServerSentEvents failed: Error: 'ServerSentEvents' does not support Binary. LongPolling failed: TypeError: undefined is not an object (evaluating 'this.transport.onreceive=this.onreceive')
log (blazor.server.js:1:5021)
(anonymous function) (blazor.server.js:1:45885)
(anonymous function) (blazor.server.js:1:40129)
a (blazor.server.js:1:39051)
promiseReactionJob
[Error] [2019-09-13T13:03:07.616Z] Error: Error: Unable to connect to the server with any of the available transports. WebSockets failed: Error: There was an error with the transport. ServerSentEvents failed: Error: 'ServerSentEvents' does not support Binary. LongPolling failed: TypeError: undefined is not an object (evaluating 'this.transport.onreceive=this.onreceive')
log (blazor.server.js:15:27319)
S (blazor.server.js:8:104321)
(anonymous function) (blazor.server.js:8:104045)
(anonymous function) (blazor.server.js:8:100600)
a (blazor.server.js:8:99498)
promiseReactionJob
[Error] Unhandled Promise Rejection: Error: Cannot send data if the connection is not in the 'Connected' State.
(anonymous function) (blazor.server.js:8:100661)
a (blazor.server.js:8:99498)
promiseReactionJob

**Comment by pranavkm** [comment]
@BrennanConroy would you know what might cause this error?

**Comment by BrennanConroy** [comment]
Well a 401 is the unauthorized http code.

Could you gather server side logs so we can see why auth might have failed?

**Comment by rkone** [comment]
Sure, here's the log.
[ex190913.log](https://github.com/aspnet/AspNetCore/files/3611077/ex190913.log)

**Comment by BrennanConroy** [comment]
Not sure where you got those logs. But we need the logs from ASP.NET Core, see https://docs.microsoft.com/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2 for details on the logging.

**Comment by rkone** [comment]
Sorry, is this what you were looking for?

> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://user:58219/_framework/blazor.server.js  
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://user:58219/css/bootstrap/bootstrap.min.css  
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://user:58219/  
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://user:58219/css/open-iconic/font/css/open-iconic-bootstrap.min.css  
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint '/_Host'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://user:58219/css/site.css  
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Route matched with {page = "/_Host"}. Executing page /_Host
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executing an implicit handler method - ModelState is Valid
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /css/open-iconic/font/css/open-iconic-bootstrap.min.css was not modified
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /css/bootstrap/bootstrap.min.css was not modified
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /_framework/blazor.server.js was not modified
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /css/site.css was not modified
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 21.8805ms 304 text/css
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 27.352400000000003ms 304 text/css
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 30.258300000000002ms 304 application/javascript
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 24.803700000000003ms 304 text/css
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization was successful.
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executed page /_Host in 28.050600000000003ms
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/_Host'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 38.257200000000005ms 200 text/html; charset=utf-8
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://user:58219/_framework/blazor.server.js  
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://user:58219/css/bootstrap/bootstrap.min.css  
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://user:58219/css/site.css  
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /_framework/blazor.server.js was not modified
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /css/bootstrap/bootstrap.min.css was not modified
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /css/site.css was not modified
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 10.2482ms 304 application/javascript
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 8.0576ms 304 text/css
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 9.4864ms 304 text/css
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://user:58219/css/open-iconic/font/css/open-iconic-bootstrap.min.css  
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: The file /css/open-iconic/font/css/open-iconic-bootstrap.min.css was not modified
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 5.477ms 304 text/css
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 POST http://user:58219/_blazor/negotiate text/plain;charset=UTF-8 0
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint '/_blazor/negotiate'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/_blazor/negotiate'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 20.950300000000002ms 200 application/json
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 POST http://user:58219/_blazor/negotiate text/plain;charset=UTF-8 0
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint '/_blazor/negotiate'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/_blazor/negotiate'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 6.2174000000000005ms 200 application/json

**Comment by pranavkm** [comment]
@rkone those look like the right logs. Could you bump up the application's log level to `Debug`? It should have more details as to what's going on.

**Comment by rkone** [comment]
I was already looking through it (but still not seeing anything):
[BlazorAppDebugLog.txt](https://github.com/aspnet/AspNetCore/files/3611221/BlazorAppDebugLog.txt)

**Comment by BrennanConroy** [comment]
It looks like you're using Chrome, could you try a different browser and see if you get the same results.

There have been issues in the past (and maybe the present) with chrome not working well with websockets and windows auth. https://bugs.chromium.org/p/chromium/issues/detail?id=423609

**Comment by rkone** [comment]
Oh, and Android Chrome works too.

**Comment by BrennanConroy** [comment]
Took a look at this and it looks like Safari does not support authentication over websockets. Edge and Chrome on iOS are really using Safari under the covers which explains why they also aren't working.

You can see the bug on Safari here: https://bugs.webkit.org/show_bug.cgi?id=80362

If you want to workaround the issue you can try to use Cookie Auth in combination with Windows Auth. For example the negotiate will do Windows Auth and the server will return a cookie which will be set on the WebSocket automatically by the browser and when the WebSocket connects the server will see the cookie and know the Windows Identity based on that.

**Comment by SteveSandersonMS** [comment]
@BrennanConroy Thanks very much for looking into that!

I see in fact this is (technically) covered in the docs at https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2#windows-authentication:

> Windows Authentication is only supported by the browser client when using Microsoft Internet Explorer or Microsoft Edge.

This will confuse people because in fact it does work in Chrome on Windows as well, even if we don't "support" that.

@danroth27 We should consider changing the "file new" dialog in VS so that, when you choose Windows Authentication, it also displays a warning saying something like *Windows Authentication is only supported for clients running Microsoft Edge on Windows. Mobile browsers are not supported.*.
