### ISSUE TITLE
JsonPatchDocument Error The JSON value could not be converted to Microsoft.AspNetCore.JsonPatch.JsonPatchDocument

### ISSUE THREAD

**Issue by ebizupnorth** [aspnet/AspNetCore#13938]
### Describe the bug
Web API using JsonPatchDocument returns an error "The JSON value could not be converted to Microsoft.AspNetCore.JsonPatch.JsonPatchDocument"

### To Reproduce
1. Using this version of ASP.NET Core 3.0 Preview 9
2. Run the project attached
3. With these arguments 

[
	{
		"op" : "replace",
		"path" : "/Summary",
		"value" : "new value"
	}
]

### Expected behavior
The model should be converted to JsonPatchDocument

### Screenshots
![postmanpatch](https://user-images.githubusercontent.com/22266547/64829237-2a52f500-d5fe-11e9-900e-01e19f324058.png)
![endpoint](https://user-images.githubusercontent.com/22266547/64829324-6b4b0980-d5fe-11e9-9557-faeae9c3ed7b.png)

### Sample Project
[WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3607876/WebApplication1.zip)

**Comment by pranavkm** [comment]
@ebizupnorth you'll need to update your application to reference `Microsoft.AspNetCore.Mvc.Newtonsoft.Json` package:

* Install the [Microsoft.AspNetCore.Mvc.NewtonsoftJson](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/) NuGet package.
* Update the project's `Startup.ConfigureServices` method to include a call to `AddRazorRuntimeCompilation`:

  ```csharp
  services
      .AddControllersWithViews()
      .AddNewtonsoftJson();
  ```

**Comment by ebizupnorth** [comment]
Thanks a lot. It works like a charm!

It would be better if Microsoft.AspNetCore.Mvc.NewtonsoftJson will be added as dependency of Microsoft.AspNetCore.JsonPatch.JsonPatchDocument in the nuget package.

**Comment by ebizupnorth** [comment]
Any plan when Microsoft.AspNetCore.JsonPatch.JsonPatchDocument will use the new System.Text.Json as the default JSON serializer?

**Comment by pranavkm** [comment]
@ebizupnorth it's unlikely in the short term. `JsonPatch` extensively uses Json.NET types and features that are current not available in System.Text.Json (primarily `IContractResolver`). It would be a fairly large amount of work to get it to use the new serializer.

**Comment by sass777** [comment]
fantastic stuff... so now I'll have to downgrade everything back to Newtonsoft. Why did you guys even create your own JSON library, if nothing is supported (JsonPatch, Dictionary<string,..>), etc.??

**Comment by sass777** [comment]
@pranavkm also, why has this ticket been closed? This issue hasn't been resolved. Telling people to "use another library" doesn't resolve the problem, now does it?

**Comment by keenjus** [comment]
> 
> 
> @pranavkm also, why has this ticket been closed? This issue hasn't been resolved. Telling people to "use another library" doesn't resolve the problem, now does it?

Especially when the NewtonsoftJson library is broken too :)
https://github.com/aspnet/AspNetCore/issues/14396

**Comment by NoahStahl** [comment]
Should anyone else stumble on this, there is[ this documentation ](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.0#jsonpatch-addnewtonsoftjson-and-systemtextjson)for using Newtonsoft selectively for Patch purposes alongside System.Text.Json. It's not pretty but seems to do the job until this library gets the newer JSON treatment.

And don't forget to use the JSON-Patch specific content type, or use this more lenient setup which allows application/json too;

[https://github.com/aspnet/AspNetCore.Docs/issues/15566#issuecomment-550572394](url)
