### ISSUE TITLE
Change the MSI asset name of aspnetcoremodule V2 MSI

### ISSUE THREAD

**Issue by johnbeisner** [aspnet/AspNetCore#13935]
The .NET Core Unified Installer will replace the Server Hosting bundle along with other installers. However, there are 2 MSIs that are part of the Server Hosting bundle that have MSI asset names that are non-unique build-over-build:

- 	aspnetcoremodule_x64_en_v2.msi
- 	aspnetcoremodule_x86_en_v2.msi

This breaks the upgrade scenario in the .NET Core unified installer.

@joeloff can give more details.

Target branch = release/3.1

https://github.com/aspnet/AspNetCore/blob/95d7f23e2873b2bb43b226f153912fb136664dc2/src/Installers/Windows/AspNetCoreModule-Setup/ANCMV2/AncmV2.wixproj#L10

**Comment by Pilchie** [comment]
@jkotalik - is this something you could take a look at?
