### ISSUE TITLE
Load balanced SignalR hub connection issue

### ISSUE THREAD

**Issue by jasonycw** [aspnet/AspNetCore#13944]
### Describe the bug
We got a SignalR hub server on AWS, with multiple instances under a load balancer. Load balancer stickiness is enabled on that target group of instances and redis backplane is setup.

However, we think that the stickiness is controlled by the cookie from AWS Load balancer, when cookie is disabled from the browser, the initiation of the SignalR connection will be failed.

### To Reproduce
1. Setup the SignalR to have `AddStackExchangeRedis` and CORS properly to the client site
2. Create SignalR Hub server under AWS load balance
3. Create a SignalR client site
4. Disable the browser's cookie for the SignalR hub 
![image](https://user-images.githubusercontent.com/4518597/64838060-0bfff000-d624-11e9-92f1-746477db2d6f.png)
5. Connection after`negotiate` and the actual connection failed with 404 ![image](https://user-images.githubusercontent.com/4518597/64837711-626c2f00-d622-11e9-999f-0b1525a56ba3.png) ![image](https://user-images.githubusercontent.com/4518597/64837686-45cff700-d622-11e9-8c73-eb0575afafff.png) 
![image](https://user-images.githubusercontent.com/4518597/64838322-2dada700-d625-11e9-89a3-c84b927f1b56.png)
![image](https://user-images.githubusercontent.com/4518597/64838289-0d7de800-d625-11e9-8f1f-cda634a91627.png) 
![image](https://user-images.githubusercontent.com/4518597/64838346-546bdd80-d625-11e9-8476-09a296645bc2.png) 
![image](https://user-images.githubusercontent.com/4518597/64838407-9a28a600-d625-11e9-98cc-7da96f62cf67.png) ![image](https://user-images.githubusercontent.com/4518597/64838361-68afda80-d625-11e9-9bd2-5fdf52834ae8.png)

### Expected behavior
The browser should able to connect to the hub after the `negotiate` call

### Additional context
We sure if cookie is enabled, the 404 issue never happen

This issue was found because when we were trying our web portal on iOS 12, it didn't work by default when we pointed to our load balanced multi instances hub server.
![image](https://user-images.githubusercontent.com/4518597/64838194-a19b7f80-d624-11e9-9ee9-eb08c6e73315.png)
Turn out if we disable this setting, the issue will be gone.

We are not sure if the clientId is properly loaded to the Redis backplane right after the `negotiate` call so other instance can start the connection properly.

**Comment by jasonycw** [comment]
I see, so `clientId` is never shared between difference instance even if I use Redis backplane.

That's better be in the doc so everyone know

**Comment by davidfowl** [comment]
The docs say sticky sessions are required. https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-2.2#redis-backplane

**Comment by jasonycw** [comment]
Yes, we thought the sticky session is for the continue connection(e.g. long polling) only, didn't think that will also be needed between `negotiate` and **start** of connection

**Comment by anurse** [comment]
> We need to put this in the docs:

We do have it in the docs @davidfowl. Do you have a specific thought on what is missing for the docs?

**Comment by davidfowl** [comment]
Something in bold that sticky sessions are *ALWAYS* required!

**Comment by anurse** [comment]
https://github.com/aspnet/AspNetCore.Docs/pull/14392

**Comment by anurse** [comment]
Closing as the docs PR has been merged.
