### ISSUE TITLE
Using ASP.NET Core 2.2 Identity LockoutEnabled always set to true using UserManager CreateAsync

### ISSUE THREAD

**Issue by xshiiiidev** [aspnet/AspNetCore#13940]
Hello I am having a problem with the ASP.NET Core 2.2 Identity

![image](https://user-images.githubusercontent.com/19402130/64836428-6f861f80-d61c-11e9-86e2-c37495941f27.png)

I am creating a new user using the IdentityUser. I set the new user class LockoutEnabled = false; 
But the UserManager CreateAsync method always set it to true and it overrides the value
I set for the LockoutEnabled property. Is this normal ?

![image](https://user-images.githubusercontent.com/19402130/64835211-b0c80080-d617-11e9-9347-4a0ca2f44f7c.png)

Hello I think I found the code that have the issue here it is set to a static true value

https://github.com/aspnet/AspNetCore/blob/9e788650b091875e4bf15eb7ae7f05283845c5b0/src/Identity/Extensions.Core/src/UserManager.cs#L477

@HaoK Hi bro could you please help me thanks.

**Comment by HaoK** [comment]
Did you try turning off `IdentityOptions.Lockout.AllowedForNewUsers = false`?  That is what determines whether identity turns it on within a Create

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Core/src/LockoutOptions.cs#L19
