### ISSUE TITLE
Uri not updated after NavigateTo complete

### ISSUE THREAD

**Issue by katiep23** [aspnet/AspNetCore#13942]
After I get a success status code from creating a project, I do

`uriHelper.NavigateTo($"/Project/View/{projResponse.ID.ToString()}");`

This actually works:
![image](https://user-images.githubusercontent.com/51712098/64838470-f7d2d900-d5b8-11e9-833d-3c4744109b1d.png)

But at the same time the above is present, the uriHelper.Uri value has not changed at all:
![image](https://user-images.githubusercontent.com/51712098/64838499-133de400-d5b9-11e9-9732-104ac1614547.png)

Is this by design? If so, can I force the Uri value to update somehow? Or force a page refresh? I use the same base page for Project/View & Project/Create, so it's not actually refreshing when I redirect.

**Comment by pranavkm** [comment]
Thanks for the issue report @katiep23. `NavigationManager.NavigateTo` sends a message to the browser which then navigates asynchronously. The `Uri` isn't updated until the navigation has completed in the browser. What you're seeing is likely because you're accessing the property prior to navigation having occurred.

**Comment by katiep23** [comment]
Well when NavigationManager.NavigateTo completes & it's within same page, OnInitialized is not called again.  Is there a way to force this?

**Comment by pranavkm** [comment]
You could use `NavigationManager.LocationChanged` to be notified of when the navigation completes:

``C#
string uri;
void UpdateUri(LocationChangedEventArgs args)
{
   uri = args.Location;
   uriHelper.LocationChanged -= UpdateUri;
}

...


uriHelper.LocationChanged += UpdateUri;
uriHelper.NavigateTo($"/Project/View/{projResponse.ID.ToString()}"); 
```

You might need to do more to make sure the event handler is removed when the component is disposed.
