### ISSUE TITLE
Performance regression: DbMultiUpdateRaw, PlaintextNonPipelinedLoggingNoScopes, HttpClientParallel, HttpClient, MvcDbFortunesEf ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#13955]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbFortunesDapper | Linux, http, KestrelSockets | 2019-09-13 08:37:44Z | 219578 | 4 | -100 % | -118.77 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbFortunesEf | Linux, http, KestrelSockets | 2019-09-13 08:41:07Z | 166200 | 3 | -100 % | -35.37 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbFortunesRaw | Linux, http, KestrelSockets | 2019-09-13 08:34:22Z | 255771 | 5 | -100 % | -116.96 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbMultiQueryDapper | Linux, http, KestrelSockets | 2019-09-13 07:50:12Z | 18593 | 4 | -99.98 % | -298.41 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbMultiQueryEf | Linux, http, KestrelSockets | 2019-09-10 07:03:44Z | 14477 | 14083 | -2.72 % | -3.68 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19458.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.3__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/03ba5738b3184e9227cd944670fcf3dd49007f74...e15ea5563073273ee1aaa2cd7324d3fcf4002aba

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbMultiQueryRaw | Linux, http, KestrelSockets | 2019-09-13 07:43:17Z | 18824 | 6 | -99.97 % | -6.72 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbMultiUpdateDapper | Linux, http, KestrelSockets | 2019-09-13 08:17:28Z | 11817 | 6 | -99.95 % | -133.84 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbMultiUpdateRaw | Linux, http, KestrelSockets | 2019-09-13 08:14:06Z | 11320 | 8 | -99.93 % | -81.68 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbMultiUpdateRaw | Windows, http, KestrelSockets | 2019-09-13 15:56:43Z | 11163 | 10389 | -6.93 % | -9.6 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.12__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...04f37e59d54af63cdd1d2d196f0f4970e7b8818a

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbSingleQueryEf | Linux, http, KestrelSockets | 2019-09-13 07:15:42Z | 175945 | 3 | -100 % | -35.42 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbSingleQueryRaw | Linux, http, KestrelSockets | 2019-09-13 07:01:55Z | 290073 | 4 | -100 % | -164.01 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| EndpointPlaintext | Linux, http, KestrelSockets | 2019-09-13 06:17:51Z | 3662066 | 3017570 | -17.6 % | -21.76 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| HttpClient | Linux, http, KestrelSockets | 2019-09-13 08:53:53Z | 210268 | 0 | -100 % | -27.8 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| HttpClientParallel | Linux, http, KestrelSockets | 2019-09-13 08:56:18Z | 33422 | 0 | -100 % | -70.12 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, http, KestrelSockets | 2019-09-13 06:25:45Z | 754585 | 642388 | -14.87 % | -9.4 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, https, KestrelSockets | 2019-09-13 06:38:09Z | 512534 | 432247 | -15.66 % | -21.39 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbFortunesDapper | Linux, http, KestrelSockets | 2019-09-13 08:47:52Z | 120785 | 3 | -100 % | -76.19 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbFortunesEf | Windows, http, KestrelSockets | 2019-09-10 08:53:18Z | 126144 | 122768 | -2.68 % | -3.4 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19458.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.3__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/03ba5738b3184e9227cd944670fcf3dd49007f74...e15ea5563073273ee1aaa2cd7324d3fcf4002aba

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbFortunesEf | Linux, http, KestrelSockets | 2019-09-13 08:51:13Z | 101821 | 2 | -100 % | -60.88 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbMultiQueryEf | Linux, http, KestrelSockets | 2019-09-10 07:05:52Z | 13958 | 13406 | -3.95 % | -3.33 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19458.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.3__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/03ba5738b3184e9227cd944670fcf3dd49007f74...e15ea5563073273ee1aaa2cd7324d3fcf4002aba

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbMultiUpdateDapper | Linux, http, KestrelSockets | 2019-09-13 08:27:37Z | 11566 | 2 | -99.98 % | -134.86 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbMultiUpdateEf | Linux, http, KestrelSockets | 2019-09-13 08:30:59Z | 6894 | 1 | -99.99 % | -109.27 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbSingleQueryDapper | Linux, http, KestrelSockets | 2019-09-13 07:29:30Z | 191507 | 3 | -100 % | -138.29 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbSingleQueryEf | Linux, http, KestrelSockets | 2019-09-13 07:36:23Z | 134075 | 2 | -100 % | -56.3 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbSingleQueryRaw | Linux, http, KestrelSockets | 2019-09-13 07:22:37Z | 200787 | 3 | -100 % | -157.96 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcJson | Linux, http, KestrelSockets | 2019-09-13 06:27:17Z | 408428 | 371614 | -9.01 % | -6.16 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcJsonNet | Linux, http, KestrelSockets | 2019-09-13 06:28:51Z | 411637 | 358477 | -12.91 % | -18.31 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcJsonNet2k | Linux, http, KestrelSockets | 2019-09-13 06:31:55Z | 185245 | 162584 | -12.23 % | -10.3 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcPlaintext | Linux, http, KestrelSockets | 2019-09-13 06:13:13Z | 1882531 | 1685257 | -10.48 % | -10.99 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Plaintext | Linux, https, KestrelSockets | 2019-09-13 06:36:35Z | 2086844 | 1873719 | -10.21 % | -4.55 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| PlaintextNonPipelined | Linux, http, KestrelSockets | 2019-09-13 06:08:38Z | 813736 | 698059 | -14.22 % | -4.33 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| PlaintextNonPipelinedLoggingNoScopes | Linux, http, KestrelSockets | 2019-09-13 09:16:23Z | 775553 | 643207 | -17.06 % | -12.19 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| ResponseCachingPlaintextCached | Linux, http, KestrelSockets | 2019-09-13 06:50:28Z | 1846076 | 1692721 | -8.31 % | -6.55 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| StaticFiles | Linux, http, KestrelSockets | 2019-09-13 06:22:28Z | 3871720 | 3177463 | -17.93 % | -20.61 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by anurse** [comment]
Seems like something completely broke rather than a perf regression, with deltas like -100% :).

Any thoughts @sebastienros ?

**Comment by anurse** [comment]
@sebastienros says these are fixed :)
