### ISSUE TITLE
Allow access to ParameterInfo on ModelMetadata

### ISSUE THREAD

**Issue by calebdoise** [aspnet/AspNetCore#13951]
### Problem
I need to be able to assign an IModelBinder to a parameter based on a custom attribute assigned to the action's method.

```csharp
public class MyController : Controller
{
    [MyCustomService]
    public MyCustomServiceResult Add(int x, int y)
    {
        return new MyCustomServiceResult(x + y);
    }
}
```
Within my IModelBinderProvider, for parameters x and y, I want to be able to provide a custom IModelBinder based on the fact that "Add" method has the MyCustomServiceAttribute applied.

If I had access to the ParameterInfo for x/y, I could retrieve the custom attributes for the Add method within my IModelBinderProvider.GetBinder implementation.

### Proposed Solution
Please add a public property to Microsoft.AspNetCore.Mvc.ModelBinding.ModelMetadata that provides the ParameterInfo when MetadataKind is Parameter.

The Identity property of ModelMetadata has the PropertyInfo, but it is protected.

Alternatively, ModelMetadata.Identity could be changed from protected to public.

### Additional context
This would allow us to maintain source code compatibility with a large full .NET Framework project that we are planning on porting to .NET Core.

**Comment by calebdoise** [comment]
Here is what I could do as a workaround in IModelBinderProvider implementation, but I would obviously want to be able to remove the dependency on reflection to get to a production-ready .NET Core version of our application.

```csharp
public IModelBinder GetBinder(ModelBinderProviderContext context)
{
    if (context == null)
    {
        throw new ArgumentNullException(nameof(context));
    }

    // NOTICE:  "options.AllowValidatingTopLevelNodes = true;" must be set in .NET Core 2.2 or context won't have ParameterInfo.
    //   This looks like it will be fixed in .NET Core 3.0. See ControllerBinderDelegateProvider.GetParameterBindingInfo.

    bool hasMyCustomServiceAttr = false;

    // NOTE: Outstanding change request to .NET Core project.
    //https://github.com/aspnet/AspNetCore/issues/13951
    var identityProp = typeof(ModelMetadata).GetProperty("Identity", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic);
    var modelMetadataIdentity = (ModelMetadataIdentity)identityProp.GetValue(context.Metadata);
    var paramInfo = modelMetadataIdentity.ParameterInfo;
    var myCustomServiceAttrs = paramInfo?.Member?.GetCustomAttributes(typeof(MyCustomServiceAttribute), true);
    if (myCustomServiceAttrs != null && myCustomServiceAttrs.Length > 0)
    {
        hasMyCustomServiceAttr = true;
    }

    if (hasMyCustomServiceAttr)
    {
        return this.myCustomModelBinder;
    }
    else
    {
        return null;
    }
}
```

**Comment by pranavkm** [comment]
You could make the attribute a convention that configures a parameter's binder. It'd be a lot simpler than trying to write a provider:

```C#
[MyCustomService]
public MyCustomServiceResult Add(int x, int y)
{
    return new MyCustomServiceResult(x + y);
}

public class MyCustomServiceAttribute : Attribute, IActionModelConvention
{
    public void Apply(ActionModel action)
    {
        foreach (var parameter in action.Parameters)
        {
            parameter.BindingInfo ??= new BindingInfo();
            parameter.BindingInfo.BinderType = typeof(MyBinder);
        }
    }
}
```

**Comment by calebdoise** [comment]
Using IActionModelConvention works for my scenario.

I still think it would be useful for people to have access to ParameterInfo inside of IModelBinderProvider.GetBinder, but I am able to achieve my goal using your suggestion. Feel free to close issue if you all do not want to add that.

**Comment by pranavkm** [comment]
@calebdoise we'd like to better understand scenarios where this is useful in before we make it public. Given that your case was better solved using a convention, we wouldn't consider it a great candidate. Closing this.
