### ISSUE TITLE
Update TFM for ASP.NET Core Web project templates to `netcoreapp3.1`

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#13960]

**Comment by mkArtakMSFT** [comment]
@JunTaoLuo I believe you've completed this already, haven't you?

**Comment by JunTaoLuo** [comment]
Yes

**Comment by mkArtakMSFT** [comment]
Thanks! Can you please also link the PR here for future reference?

**Comment by mkArtakMSFT** [comment]
https://github.com/aspnet/AspNetCore/pull/13571
