### ISSUE TITLE
Performance regression: ResponseCachingPlaintextResponseNoCache, PlaintextNonPipelined

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#13964]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| PlaintextNonPipelined | Linux, h2, KestrelSockets | 2019-09-13 06:41:15Z | 423053 | 376786 | -10.94 % | -2.49 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| ResponseCachingPlaintextResponseNoCache | Linux, http, KestrelSockets | 2019-09-13 06:52:01Z | 1980528 | 1729504 | -12.67 % | -5.81 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by anurse** [comment]
More CentOS regressions.
