### ISSUE TITLE
Performance regression: HttpClientParallel

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#13967]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| HttpClientParallel | Windows, http, KestrelSockets | 2019-09-13 20:33:33Z | 47279 | 39939 | -15.52 % | -5.04 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.12__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...04f37e59d54af63cdd1d2d196f0f4970e7b8818a

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by anurse** [comment]
@sebastienros do you have context on what this benchmark is/does?

**Comment by anurse** [comment]
This is mostly an HttpClient benchmark. Not sure how we should categorize/process these.

**Comment by sebastienros** [comment]
I fixed the project and tested it was working now.

**Comment by sebastienros** [comment]
Sorry, this one is about perf regression, reopening

**Comment by sebastienros** [comment]
CentOS update on the client
