### ISSUE TITLE
cannot get Auth code flow working with preview 9

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#13963]
_From @murbanowicz on Monday, September 9, 2019 5:20:40 PM_

hi,
I am struggling to set up the identity server with 3.0. 
I provided detailed description on SO: https://stackoverflow.com/questions/57857813/identity-server-4-unauthorized-client

Client is now recognized when I added client to configuration json,.but cannot get it working with e.g. postman while the same postman working with the same flow on e.g. demo.identityserver.io 

I will really appreciate any help

_Copied from original issue: dotnet/core#3338_

**Comment by scalablecory** [comment]
_From @murbanowicz on Monday, September 9, 2019 6:24:15 PM_

Giving more details:
It is for sure NOT LOADING clients added by: `.AddInMemoryClients(Config.GetClients())`
It is ignoring e.g. `"RequirePkce": false` in client section in `appsettings.development.json` and still requiring code challange...

**Comment by scalablecory** [comment]
_From @scalablecory on Monday, September 9, 2019 8:25:27 PM_

Hi @murbanowicz,

Identity Server is a 3rd party software, not part of the .NET Core project. You will need to reach out to them through one of their [support channels](https://identityserver4.readthedocs.io/en/latest/intro/support.html).

**Comment by scalablecory** [comment]
_From @blowdart on Monday, September 9, 2019 8:26:46 PM_

Wait a minute :)

Is this the build in identity server pieces in the SPA templates? Or is it in other app types?

**Comment by scalablecory** [comment]
_From @murbanowicz on Monday, September 9, 2019 8:32:56 PM_

exactly, built in in the SPA templates

pon., 9 wrz 2019, 22:28 użytkownik Barry Dorrans <notifications@github.com>
napisał:

**Comment by scalablecory** [comment]
_From @blowdart on Monday, September 9, 2019 8:35:58 PM_

Can someone move this to the asp.net repo please?

(Or @murbanowicz please ask this again in https://github.com/aspnet/AspNetCore/issues and close this one yourself)

**Comment by scalablecory** [comment]
_From @murbanowicz on Monday, September 9, 2019 8:48:46 PM_

Damn it! sorry, i am always confused where the issues should go.

pon., 9 wrz 2019, 22:36 użytkownik Barry Dorrans <notifications@github.com>
napisał:

**Comment by scalablecory** [comment]
_From @blowdart on Monday, September 9, 2019 8:50:08 PM_

You and me both :)

**Comment by scalablecory** [comment]
_From @murbanowicz on Tuesday, September 10, 2019 12:14:40 PM_

Further investigation shows that in any way I cannot make IdentityServer integration load my client.
I the logs, it is showing creating the client named as my project, nothing about my client, but this projectName client is also not available at all.
This is really strange.
I have tried to add it by `AddInMemoryClients` and also as:
```
.AddApiAuthorization<ApplicationUser, ApplicationDbContext>(c =>
                {
                    c.Clients = new ClientCollection(GetClients());
                });
```

**Comment by blowdart** [comment]
@javiercn could you take a look or explain what we're doing here?

**Comment by javiercn** [comment]
additional clients can be configured/updated by adding/modifying the clients in the client collection.
