### ISSUE TITLE
Provide a way to inspect the DOM using an ElementReference

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#13979]
Currently an `ElementReference` is an opaque value intended for JS interop purposes only. We generally don't want users to mutate the DOM using an `ElementReference` because that would interfere with the Blazor diffing algorithm.

However, I've run into a case where I want to be able to inspect the state of the DOM, which seems like should be a safe operation. In my scenario I have an input text box and a button. When the user clicks the button I want to display a message using the value from the text box.  Something like this:

```razor
<div>
    What is your name?
    <input />
    <button @onclick="OnClick">Submit</button>
</div>
<div>
    if (name != null)
    {
        Hello @name
    }
</div>

@code {
    string name;

    void OnClick() {
        // Set name to the value of the text box here
    }
}
```

I could implement this by binding the value of the text box to a different string field and then set the name field when the button is clicked, but that seems excessive. The only event I really care about is the click event and it seems unnecessary to require me to bind whatever state I want from the DOM into component state in order to read it given that the DOM state is there to be read.

**Comment by mkArtakMSFT** [comment]
Closing this as we don't want to expose a second way of accessing data. Anyone can come up with a package with a lot of helper methods exposing DOM to Blazor.
