### ISSUE TITLE
Scenarios are not running: LinkAThonTrimmedAndR2R, LinkAThonTrimmedAndR2RSingleFile, LinkAThonTrimmedAndR2RSingleFileCustomHost, LinkAThonTrimmedAndR2RSingleFileNoMvc

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#13972]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| LinkAThonTrimmedAndR2R | Linux, Physical, http, KestrelSockets | 9/12/19 3:04:30 AM +00:00 |
| LinkAThonTrimmedAndR2RSingleFile | Linux, Physical, http, KestrelSockets | 9/12/19 3:06:08 AM +00:00 |
| LinkAThonTrimmedAndR2RSingleFileCustomHost | Linux, Physical, http, KestrelSockets | 9/12/19 3:09:17 AM +00:00 |
| LinkAThonTrimmedAndR2RSingleFileNoMvc | Linux, Physical, http, KestrelSockets | 9/12/19 3:07:44 AM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Temporary malfunction
