### ISSUE TITLE
What is the valid value for `Range` in header?

### ISSUE THREAD

**Issue by yukozh** [aspnet/AspNetCore#13982]
There is no description about the up-limits: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

But when invoke it in .NET Core, it throw an error if set the value like this:
```
HttpClient.DefaultRequestHeaders.Add("Range", "bytes=1759182848‬-1759182880");
```

![image](https://user-images.githubusercontent.com/2216750/64905950-f9fc7b00-d711-11e9-8c8e-58fc1010fc04.png)

**Comment by samsosa** [comment]
You have an invalid and maybe invisible Unicode symbol between the first range number and the dash.


HttpClient.DefaultRequestHeaders.Add("Range", "bytes=1759182848 **\(\&#\8236);** -1759182880");


<img width="467" alt="markdown_escape_hell" src="https://user-images.githubusercontent.com/32570890/64929117-243d5e00-d822-11e9-9f8a-a860fa9d14a1.png">

**Comment by anurse** [comment]
I see the same as @samsosa. Your sample includes an invalid character. I see the unicode character `0x202C` immediately before your `-` character, which isn't valid. The ranges must be separately only by a single `-` (the Unicode character `0x002D`).

If it still doesn't work after fixing that, please provide a runnable sample project that reproduces the problem and we can investigate further.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
