### ISSUE TITLE
Scenarios are not running: GrpcServerStreamingAspNetCore-GrpcCore

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#13985]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| GrpcServerStreamingAspNetCore-GrpcCore | Windows, Cloud, http, KestrelSockets | 9/13/19 2:12:40 PM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Fixed
