### ISSUE TITLE
[Blazor] Dynamic Editor Generation For Model

### ISSUE THREAD

**Issue by smartprogrammer93** [aspnet/AspNetCore#14006]
### Is your feature request related to a problem? Please describe.
It would save me so much time if i can generate forms based on the model like how it used to be in Normal Asp.net core views. 

If we can have something like this :
`@Html.Editor("StudentId")`
and its overloads
Or something like this : 
```
var propertyName = "FirstName"
<InputText @bind-Value-propertyName="propertyName " @bind-Value-object="Model" />
```

**Comment by smartprogrammer93** [comment]
So I noticed that there is a property called ValueExpression inside of ComponentBase

Can That be used instead of Bind-Value?

**Comment by smartprogrammer93** [comment]
Alright update 3,
I realized i can implement this functionality myself
Sharing it if anyone is interested

```
@using System.Linq.Expressions;
@typeparam TModel
<InputText class="form-control"
           ValueChanged="Microsoft.AspNetCore
                            .Components.EventCallback
                            .Factory.Create<string>
                            (this, UpdateValue)"
           Value="@PropertyValue" ValueExpression="exp" />
@code{

    [Parameter]
    public TModel Model { get; set; }

    [Parameter]
    public string PropertyName { get; set; }

    public Type ModelType => Model.GetType();

    public System.Reflection.PropertyInfo Property =>
        ModelType.GetProperty(PropertyName);

    public Expression<Func<string>> exp
    {
        get
        {
            var memberExpression = Expression.Constant(Model);
            var propertyExpression = Expression.Property(memberExpression, PropertyName);
            var expression = Expression.Lambda<Func<string>>(propertyExpression);
            return expression;
        }
    }

    public string PropertyValue
    {
        get
        {
            return (string)Property.GetValue(Model);
        }
    }

    public void UpdateValue(String value)
    {
        Property.SetValue(Model, value);
    }

}
```

I don't understand the importance of ValueExpression Though. What functionality does ValueExpression provide?

**Comment by mkArtakMSFT** [comment]
Thanks for your feature request. This is not something we plan to add support for in the near future.

**Comment by SteveSandersonMS** [comment]
> What functionality does ValueExpression provide?

It's the mechanism by which the receiver can obtain metadata about the value you're supplying. For example, the `Input` components all use it to attach themselves into the validation system, showing the validation status of the associated field.
