### ISSUE TITLE
Oneway binding of an input element typed datetime-local not working

### ISSUE THREAD

**Issue by EuroEager2008** [aspnet/AspNetCore#14008]
`<input type="datetime-local" value="@MyDate" />
@code { DateTime MyDate = DateTime.Now;}
`
Doesn't work, input element is uninitialized.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @EuroEager2008.
We don't support the `datetime-local` input type at the moment. You can use `ToString` method with explicit format parameter to get the desired outcome.
