### ISSUE TITLE
JSRuntime call from js to blazor breaks after use at least one binding in page

### ISSUE THREAD

**Issue by zefir01** [aspnet/AspNetCore#14011]
### Describe the bug
Call JSInvokable method of instance or static class, from js event, dont work after i change value of any html element with binding to field or property.

### To Reproduce
1. Using this version of ASP.NET Core NET Core 3.0 Preview 9
2. **create helper class:**
```
public class JsHelper
    {
        [JSInvokable]
        public static Task ReturnArrayAsync()
        {
            return Task.FromResult(0);
        }
    }
```
**create any blazor page with elements:**
```
<select class="select form-control" onchange="{alert('Hello 10'); DotNet.invokeMethodAsync('WebApplication3', 'ReturnArrayAsync'); return; }">                           
    <option value="1">1</option>
    <option value="2">2</option>
</select>

<div class="form-check">
    <input class="form-check-input" type="radio" name="typeRadios" id="sellCheck" @onchange="(e=> { IsSale = true; })" />
    <label class="form-check-label" for="sellCheck">
            sell online
     </label>
</div>
<div class="form-check">
    <input class="form-check-input" type="radio" name="typeRadios" id="buyCheck" @onchange="(e=> { IsSale = false; })" />
    <label class="form-check-label" for="buyCheck">
        buy online
     </label>
</div>
```

**create code:**
`
private bool? IsSale = null;`

### Expected behavior
After loading the page to change the radio value, the 'Hello 10' alert will work and the ReturnArrayAsync method will be called. This is normal. 
But if you first change the values of select or any other element with binding, then after changing the value of select, 'Hello 10' will be called, but ReturnArrayAsync will not be called.

### Additional context
c:\Users\Coding\source\repos\WebApplication3>dotnet --info
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @zefir01.
@javiercn can you please look into this? Thanks!

**Comment by javiercn** [comment]
@zefir01 Can you provide a minimal repro project we can use to investigate the issue?

**Comment by zefir01** [comment]
very strange, but in a minimal project there is no such bug. send you the whole project?

**Comment by javiercn** [comment]
@zefir01 I would suggest you start adding things back from the minimal repro to your project until you find out what is causing it.

You can also turn on more detailed logging to get insights on how the app is working.
Replace `<script src="_framework/blazor.server.js"></script>` with the snippet below in _Host.cshtml
```
<script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        function start() {
            Blazor.start({
                logLevel: 1, // LogLevel.Debug
                configureSignalR: build => builder.configureLogging("debug")
            });
        }
    </script>
```

This turns debug logging on the server. (replace it in appSettings.development.json)
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "Debug"
    }
  }
}
```

**Comment by zefir01** [comment]
I turned on debugging as you recommended. now I get the error:
```
createAdvertisement:183 [Violation] 'change' handler took 1384ms
blazor.server.js:8 Uncaught (in promise) Error: No .NET call dispatcher has been set.
    at u (blazor.server.js:8)
    at c (blazor.server.js:8)
    at Object.e.invokeMethodAsync (blazor.server.js:8)
    at HTMLSelectElement.onchange (createAdvertisement:183)
u @ blazor.server.js:8
c @ blazor.server.js:8
e.invokeMethodAsync @ blazor.server.js:8
onchange @ createAdvertisement:183 
```

**Comment by javiercn** [comment]
@zefir01 From the error it seems like you are invoking the change event before blazor is fully initialized.

Instead of attaching the event handler inline, define a function you can call through JS interop in (OnAfterRender(firstRender)) and call that function to programatically attach the event handler there. That should solve your problem.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
