### ISSUE TITLE
rzc generate exited with code 1

### ISSUE THREAD

**Issue by Joebeazelman** [aspnet/AspNetCore#14016]
Just installed the latest version of .NET Core 3 (see below for details) and I receive the following error after immediately after building my blazor project:

rzc generate exited with code 1.

.nuget/packages/microsoft.aspnetcore.blazor.build/0.7.0/targets/RazorCompilation.targets(5,5): Error: rzc generate exited with code 1. (sdfds.App)

```
NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview9-014004/

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  2.1.505 [/usr/local/share/dotnet/sdk]
  2.2.107 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]
  3.0.100-preview9-014004 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by pranavkm** [comment]
@Joebeazelman the Blazor.Build package you're targeting is fairly old and is unsupported. Please try upgrading to the latest (3.0-preview9) builds. Migration guides to upgrading between previews are available as part of the release notes: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by Joebeazelman** [comment]
> @Joebeazelman the Blazor.Build package you're targeting is fairly old and is unsupported. Please try upgrading to the latest (3.0-preview9) builds. Migration guides to upgrading between previews are available as part of the release notes: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/


Interesting. I had just wiped out my installation and downloaded the VS installers as well as the necessary packages and it grabbed the wrong one. VS told me it was the latest.  Microsoft needs to get their releases in order.
