### ISSUE TITLE
Implement AreaRegistration.RegisterAllAreas in ASP.NET Core

### ISSUE THREAD

**Issue by jez9999** [aspnet/AspNetCore#14013]
In traditional ASP.NET, you could simply call `AreaRegistration.RegisterAllAreas()` on startup and for each area, you could crease a class inheriting from `AreaRegistration` that allowed you to register controllers against that area.  You didn't need to decorate each controller with an `AreaAttribute`.  This doesn't seem to be possible in ASP.NET Core.  Could it be implemented?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jez9999.
This has been discussed at https://github.com/aspnet/Mvc/issues/7599#issuecomment-379061813
