### ISSUE TITLE
Add support for signed and/or encrypted UserInfo to OpenIdConnectHandler

### ISSUE THREAD

**Issue by StevenLiekens** [aspnet/AspNetCore#14029]
### Is your feature request related to a problem? Please describe.
An OpenID Connect provider may sign and/or encrypt claims from the UserInfo endpoint before returning them to the client. This is not currently supported by the _Microsoft.AspNetCore.Authentication.OpenIdConnect_ package.

The problematic code uses the `JwtSecurityToken` constructor to parse the UserInfo response. That constructor doesn't decrypt the response or validate its signature.
https://github.com/aspnet/AspNetCore/blob/7b0b2980dc6ffb860f2bcd71868d98d85c7d35b6/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L884-L888

### Describe the solution you'd like

Implement the algorithm for response validation that is described in OpenID Connect Core: https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponseValidation

> The Client MUST validate the UserInfo Response as follows:
> 
> 1. Verify that the OP that responded was the intended OP through a TLS server certificate check, per RFC 6125.
> 2. If the Client has provided a userinfo_encrypted_response_alg parameter during Registration, decrypt the UserInfo Response using the keys specified during Registration.
> 3. If the response was signed, the Client SHOULD validate the signature according to JWS.

**Comment by StevenLiekens** [comment]
FYI this is the same issue as #4650.

**Comment by blowdart** [comment]
Closing as dupe of #4650.
