### ISSUE TITLE
Performance regression: PlaintextPlatform

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14026]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| PlaintextPlatform | Linux, http, KestrelSockets | 2019-09-13 06:02:23Z | 6863434 | 6117593 | -10.87 % | -2.6 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19459.5__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc2.19461.7__
Microsoft.NetCore.App __5.0.0-alpha1.19404.5__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/e090a0ff33f6aa4721c0678358075515dabe08ab...33120b6093eb5ee9ecf603f56e80a6a7d5a25f07

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by anurse** [comment]
Seems suspicious, we didn't change any Kestrel in here and there doesn't seem to be a runtime change. Perhaps noise? We'll see if it shakes out.

**Comment by anurse** [comment]
This is a drop due to moving from Ubuntu to CentOS. We don't have a clear idea as to why, but it's an underlying platform thing. There are some pending CentOS patches that we believe will restore this perf.
