### ISSUE TITLE
Reenable OpenApi_Add_NSwagTypeScript tests

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#14021]
I disabled the tests as part of the 3.1 TFM update. https://github.com/aspnet/AspNetCore/blob/release/3.1/src/Tools/Microsoft.dotnet-openapi/test/OpenApiAddFileTests.cs#L137.

The problem is that the KnownFrameworkReferences right now only contains AspNetCore.App 3.0 since they have not ingested our 3.1 build. If we want to enable this test immediately we need to hack the itemgroup to mock a AspNetCore.App 3.1 reference as is done in the Template tests: https://github.com/aspnet/AspNetCore/blob/release/3.1/src/ProjectTemplates/test/Infrastructure/TemplateTests.props.in#L19-L25. However, I think at this point, we can wait and re-enable this test when a new SDK is available.

**Comment by mkArtakMSFT** [comment]
Thanks @JunTaoLuo.

@ryanbrandenburg can you please re-enable these tests when we get an updated SDK dependency.
