### ISSUE TITLE
Custom validation inside OnCertificateValidated getting ignored by Kestrel (3.0Preview9)

### ISSUE THREAD

**Issue by brrusino** [aspnet/AspNetCore#14033]
We're trying to only allow certificates associated with a specific root cert to access our API. When debugging with a cert from another CA that is valid, I can confirm that the validation check (VerifyChainAndRequiredRoot) is behaving as expected and failing (context.Fail is being set) but authentication is still passing.

```
services.AddAuthentication(
            CertificateAuthenticationDefaults.AuthenticationScheme)
            .AddCertificate(options =>
            {
               options.AllowedCertificateTypes = CertificateTypes.All;
               options.Events = new CertificateAuthenticationEvents
               {
                   OnCertificateValidated = context =>
                   {
                       var cert = context.ClientCertificate;
                       if (AMEValidationService.VerifyChainAndRequiredRoot(cert))
                       {
                           var claims = new[]
                                                   {
                            new Claim(ClaimTypes.NameIdentifier, context.ClientCertificate.Subject, ClaimValueTypes.String, context.Options.ClaimsIssuer),
                            new Claim(ClaimTypes.Name, context.ClientCertificate.Subject, ClaimValueTypes.String, context.Options.ClaimsIssuer)
                        };

                           context.Principal = new ClaimsPrincipal(new ClaimsIdentity(claims, context.Scheme.Name));
                           context.Success();
                       }
                       else
                       {
                           context.Fail("invalid cert");
                       }
                       return Task.CompletedTask;
                   }
               };
            });
```
Inside the configuration for Kestrel, my understanding is that CertificateValidation would need to be disabled here in order to not use the default configuration:
```
WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureKestrel(options =>
                {
                    options.ConfigureHttpsDefaults(opt =>
                    {
                        opt.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
                        opt.ClientCertificateValidation = (cert, chain, policyErrors) =>
                        {
                            return true;
                        };
                    });
                });
```
Any insight would be much appreciated.

**Comment by Tratcher** [comment]
Kestrel doesn't participate in authentication/authorization beyond the ClientCertificateValidation check you disabled.

> but authentication is still passing

This sounds more like an authorization problem. What authorization policies have you set up for the endpoint?

**Comment by blowdart** [comment]
context.Fail("invalid cert") should have it end up with no user so authorize should be barfing?

**Comment by HaoK** [comment]
Only if you require authenticated user

**Comment by brrusino** [comment]
I haven't implemented the authorization middleware yet - my understanding was that if OnCertificateValidated() fails, any API access would be rejected (which is the intended/expected behavior).

**Comment by HaoK** [comment]
If you don't do anything and are just using `[Authorize]` that just requires authenticated user, so it should block things if authentication fails

**Comment by blowdart** [comment]
@brrusino it'll only fail if you have an authorize attribute on them, or if you've made authorization mandatory on every route via configuration.

**Comment by brrusino** [comment]
@HaoK @blowdart Good to know, I didn't realize there was an implicit connection between the Authentication and Authorization middlewares. Seems to be working now!
