### ISSUE TITLE
Wrong type param when passing `this` from blazor component

### ISSUE THREAD

**Issue by erinnmclaughlin** [aspnet/AspNetCore#14031]
### Describe the bug
When passing `this` from a blazor component, the type is `__generated__ClassName` instead of `ClassName`.

### To Reproduce
1. Using ASP.NET Core 3.0 Preview 9 and Visual Studio 2019 Preview
2. Create two new blazor components with the following code:

##### Accordion.razor
```csharp
public void ToggleItem(AccordionItem item)
{
   ...
}
```

##### AccordionItem.razor
```csharp
[CascadingParameter]
public Accordion Accordion { get; set; }

public void RandomMethod()
{
   Accordion.ToggleItem(this);
}
```

3. See error

### Expected behavior
Calling `Accordion.ToggleItem(this)` should pass this instance of class `AccordionItem` to the `Accordion.ToggleItem` method.

### Actual behavior
Getting error message: cannot convert from '__generated__AccordionItem' to 'AccordionItem'

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We expect this to be handled as part of #5487.
For now you can do this:

```razor
[CascadingParameter]
public Accordion Accordion { get; set; }

public void RandomMethod()
{
   Accordion.ToggleItem((AccordionItem)(object)this);
}
```
