### ISSUE TITLE
Microsoft.AspNetCore.JsonPatch.JsonPatchDocument should use System.Text.Json as the default JSON formatter

### ISSUE THREAD

**Issue by ebizupnorth** [aspnet/AspNetCore#14035]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to use Microsoft.AspNetCore.JsonPatch.JsonPatchDocument but it requires Newtonsoft.Json

### Describe the solution you'd like
Since, NET Core is moving away from Newtonsoft.Json dependency as default JSON formatter, it is logical to upgrade JsonPatchDocument. Yes, we can simply add AddNewtonsoftJson() on the service collection instance, but it replaces the default System.Text.Json formatter for all JSON which is very unfortunate and defeat the purpose of moving away from using Newtonsoft.JSON. 

Is there any workaround to configure JsonPatchDocument to use Newtonsoft.Json without calling .AddNewtonsftJson()?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ebizupnorth.
This is not something we plan to do in the near future.

**Comment by pranavkm** [comment]
@eakoning https://github.com/aspnet/AspNetCore/issues/12994#issuecomment-519855922 has an example of configuring the JsonPatchInputFormatter and the System.Text based formatter.

**Comment by Paul-Dempsey** [comment]
(originally from https://github.com/aspnet/AspNetCore.Docs/issues/15332 asked to move here by Rick Anderson)

I really appreciate the followup.

The key point in https://github.com/aspnet/AspNetCore/issues/14035 is this:

> Yes, we can simply add AddNewtonsoftJson() on the service collection instance, but it replaces the default System.Text.Json formatter for all JSON which is very unfortunate and defeat the purpose of moving away from using Newtonsoft.JSON.

Which is disappointing. I’m hoping there are coherent plans to move to a full utf-8 string / json stack and avoid much of the transcoding and allocation in the pipeline (see Utf8Json benchmarks).

---

Please reconsider this, as requiring the older package and bringing legacy forward is not moving in the right direction.

**Comment by RehanSaeed** [comment]
Please consider re-opening this for 3.1.

**Comment by mkArtakMSFT** [comment]
@RehanSaeed we won't be changing this in 3.1. Feel free to file a new issue and we can re-evaluate this ask for 5.0 release.

**Comment by RehanSaeed** [comment]
New issue raised in https://github.com/aspnet/AspNetCore/issues/16968
