### ISSUE TITLE
Warnings running an ASP.NET Core hosted Blazor WebAssembly app with RC1 bits

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#14039]
Repro steps:

- `dotnet new blazorwasm -ho`
- `cd Server`
- `dotnet run`

Expected result: Builds and runs cleanly.

Actual output: 

```
warning NU1603: BlazorWasmApp1.Server depends on Microsoft.AspNetCore.Mvc.NewtonsoftJson (>= 3.0.0-preview9.19457.4) but Microsoft.AspNetCore.Mvc.NewtonsoftJson 3.0.0-preview9.19457.4 was not found. An approximate best match of Microsoft.AspNetCore.Mvc.NewtonsoftJson 3.0.0-rc1.19422.2 was resolved.
```

Looks like the Server project has a bad package reference to the wrong version of Microsoft.AspNetCore.Mvc.NewtonsoftJson. We should remove the reference to this package as it isn't used or needed (#13422):

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Server" Version="3.0.0-preview9.19457.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview9.19457.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client\BlazorWasmApp1.Client.csproj" />
    <ProjectReference Include="..\Shared\BlazorWasmApp1.Shared.csproj" />
  </ItemGroup>

</Project>
```

**Comment by adrianwright109** [comment]
There is an issue that you filed @danroth27 #13422 that says to remove `Microsoft.AspNetCore.Mvc.NewtonsoftJson` as its no longer required as the Blazor WASM template works fine with the default `System.Text.Json` support.  I have submitted PR #14028 which removes the `Microsoft.AspNetCore.Mvc.NewtonsoftJson` dependency from the Blazor WASM Server project template.
