### ISSUE TITLE
Ignore asp-append-version during Development

### ISSUE THREAD

**Issue by datvm** [aspnet/AspNetCore#14044]
### Is your feature request related to a problem? Please describe.

During development, `asp-append-version` will cause browsers to severe all the Javascript breakpoints because a changed query string is considered a total different file. Most browsers provide us "Disable cache" option so caching during development should not be a problem.

The alternative is very long and causes repetition:

    <environment names="Development">
        <script defer src="~/js/blah/something.js"></script>
        
    </environment>

    <environment names="Production">
        <script defer src="~/js/blah/something.js" asp-append-version="true"></script>
        
    </environment>

### Describe the solution you'd like

`asp-append-version` should be ignored if it's in Development, or set an option in `Startup.cs` like others:

```
            if (env.IsDevelopment())
            {
                app.IgnoreAppendVersion();
            }
```

### Additional context

None.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @datvm.
This is not something we plan to do as many people find this useful even in Development environment.
