### ISSUE TITLE
AddJsonFile in ConfigureAppConfiguration with reloadOnChange not firing

### ISSUE THREAD

**Issue by jjxtra** [aspnet/AspNetCore#14050]
### Describe the bug
Attempting to use change tokens to listen for configuration changes. The change token never calls back even if I hand-edit the appsettings.json file. I have to manually monitor files myself and call

```csharp
(Configuration as IConfigurationRoot)?.Reload();
```
to get it to call back.

### To Reproduce
```csharp

builder.ConfigureAppConfiguration((hostingContext, configurationBuilder) =>
{
    configurationBuilder.AddJsonFile("appsettings.json", true, true);
});

/// <summary>
/// Constructor
/// </summary>
/// <param name="config">Configuration</param>
public MyClass(IConfiguration config)
{
    this.config = config;
    this.configChange = config.GetReloadToken();

    // this never calls back even when hand-editing the appsettings json file...
    this.configChangeListener = this.configChange.RegisterChangeCallback(async (obj) =>
    {
        try
        {
            await ReloadConfiguration();
        }
        catch (Exception ex)
        {
            Logger.Error(ex);
        }
    }, null);
}
```

### Expected behavior
Change token should callback when file changes.

**Comment by jjxtra** [comment]
This resolved my issue:

```csharp
builder.ConfigureServices(services =>
{
    services.AddSingleton<IStartup>((provider) =>
    {
        Configuration = provider.GetService<IConfiguration>();
        return this;
    });
});
```

**Comment by jjxtra** [comment]
It appears that the json file by default is not the one in the bin/debug/netcoreapp2.2 folder, it is in the project folder. That was the first thing that tripped me up.

The second thing is that the change token must be re-registered every time it changes. Is this by design or a bug?

```csharp
private async Task ConfigChanged()
{
	try
	{
		this.configChangeListener.Dispose();
		this.configChange = config.GetReloadToken();
		this.configChangeListener = this.configChange.RegisterChangeCallback(async (state) => await ConfigChanged(), null);
		await ParseConfiguration();
	}
	catch (Exception ex)
	{
		Logger.Error(ex);
	}
}
```

**Comment by davidfowl** [comment]
> The second thing is that the change token must be re-registered every time it changes. Is this by design or a bug?

By design, there's a helper method to handle re-registration [ChangeToken.OnChange](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.primitives.changetoken.onchange?view=aspnetcore-2.2#Microsoft_Extensions_Primitives_ChangeToken_OnChange_System_Func_Microsoft_Extensions_Primitives_IChangeToken__System_Action_)

**Comment by jjxtra** [comment]
Same behavior with helper

**Comment by jjxtra** [comment]
How does one dispose of a call to this OnChange method so that it unregisters?
