### ISSUE TITLE
Scenarios are not running: EndpointPlaintext, Json, Json, JsonPlatform, MvcJson ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14059]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| EndpointPlaintext | Linux, Physical, http, KestrelSockets | 9/16/19 6:18:05 AM +00:00 |
| Json | Linux, Physical, http, KestrelSockets | 9/16/19 6:25:58 AM +00:00 |
| Json | Linux, Physical, https, KestrelSockets | 9/16/19 6:38:22 AM +00:00 |
| JsonPlatform | Linux, Physical, http, KestrelSockets | 9/16/19 6:24:21 AM +00:00 |
| MvcJson | Linux, Physical, http, KestrelSockets | 9/16/19 6:27:29 AM +00:00 |
| MvcJson2k | Linux, Physical, http, KestrelSockets | 9/16/19 6:30:36 AM +00:00 |
| MvcJsonInput2k | Linux, Physical, http, KestrelSockets | 9/16/19 6:33:43 AM +00:00 |
| MvcJsonNet | Linux, Physical, http, KestrelSockets | 9/16/19 6:29:01 AM +00:00 |
| MvcJsonNet2k | Linux, Physical, http, KestrelSockets | 9/16/19 6:32:10 AM +00:00 |
| MvcJsonNetInput2k | Linux, Physical, http, KestrelSockets | 9/16/19 6:35:16 AM +00:00 |
| MvcPlaintext | Linux, Physical, http, KestrelSockets | 9/16/19 6:13:24 AM +00:00 |
| Plaintext | Linux, Physical, http, KestrelSockets | 9/16/19 6:07:18 AM +00:00 |
| Plaintext | Linux, Physical, https, KestrelSockets | 9/16/19 6:36:48 AM +00:00 |
| PlaintextNonPipelined | Linux, Physical, http, KestrelSockets | 9/16/19 6:08:51 AM +00:00 |
| PlaintextNonPipelinedLogging | Windows, Cloud, http, KestrelSockets | 9/16/19 5:51:24 AM +00:00 |
| PlaintextNonPipelinedLoggingNoScopes | Windows, Cloud, http, KestrelSockets | 9/16/19 5:52:08 AM +00:00 |
| PlaintextPlatform | Linux, Physical, http, KestrelSockets | 9/16/19 6:02:34 AM +00:00 |
| StaticFiles | Linux, Physical, http, KestrelSockets | 9/16/19 6:22:46 AM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Temporary malfunction
