### ISSUE TITLE
[Blazor] Launch from non-startup project

### ISSUE THREAD

**Issue by Joe-houghton** [aspnet/AspNetCore#14060]
Hi,

We have "Project A" which is a plug-in for CAD applications, when a user types a command or pushes a button on the ribbon, we launch a WPF window where the user can interact with the UI, then we look at the objects that the user created from the dialog and draw in CAD. Alternatively they can double click a CAD object and we pass that object into the ViewModel used by the WPF window to edit it.
A bit of example code:
```
var viewModel = new FeatureEditViewModel(clickedFeature);
var editWindow = new FeatureEditWindow(viewModel);
var result = editWindow.ShowDialog().GetValueOrDefault();
```

Is there a similar way to do this with Blazor? 

I have looked into CefSharp and can launch a browser window to a specific URL so that the Blazor page seems a part of our application, but I can't work out how to get Blazor started from Project A.

Many Thanks,

Joe

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
