### ISSUE TITLE
Angular and Asp.net core 3 - Microsoft.AspNetCore.Mvc.Components.Prerendering not found (preview9 and rc)

### ISSUE THREAD

**Issue by stephaneworkspace** [aspnet/AspNetCore#14068]
Since the update of the preview 9 and RC on my linux (debian) server, it is impossible to get my. application work on preview 9 or RC version.

When the sdk version preview 8 was installed, everything works.

When the sdk preview 9 is installed and my dll of the application is old dll version 8 (compiled by the pipeline azure ubuntu) it doesn't work.

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Components.Prerendering, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

It is the same for the version rc.

When I update the library nuget in the preview 9 or rc, it is the same problem.

(however, on my computer with windows 10, it works)

Link to stackoverflow where there is the same problem ::

https://stackoverflow.com/questions/57718946/exist-a-nugget-package-or-assembly-called-microsoft-aspnetcore-mvc-components-pr/57795396#57795396

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @stephaneworkspace.
There is some overlap between Blazor and MVC, and we had some late API Review changes in Blazor, which impacted MVC too post Preview7.
You will have to update your application to target the latest .NET Core 3.0 preview release to make your application work with the latest .NET Core SDK.

**Comment by stephaneworkspace** [comment]
It was my fault. 

I forgot to change the sdk on my pipeline azure.
