### ISSUE TITLE
Error: Invocation canceled due to the underlying connection being closed.

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#14065]
### Describe the bug
As i am deployed and hosted the blazor server application in azure. And then i have re-direct the custom domain via AWS. For initial time the application runs properly. 

But after some time like 5-10mins, the application throws the following script error.
![image](https://user-images.githubusercontent.com/31958591/65050635-56b39c00-d985-11e9-9787-e2fdc7f15cf8.png)

This is only occurred in server side application only. Client side app working properly. 

### To Reproduce
1. Create blazor server App
2. Published and host the azure site
3. Redirect the custom Domain using AWS
4. See error after couple of mins like '
![image](https://user-images.githubusercontent.com/31958591/65050876-bf027d80-d985-11e9-9333-c93043f60440.png)
'

### Screenshots
![image](https://user-images.githubusercontent.com/31958591/65050962-dfcad300-d985-11e9-941f-daec45b14c53.png)

### Additional context

I have followed the same steps for client side Blazor App. It works fine. But the error only throws randomly in server application only. 

I have used latest .net SDK RC 1 / preview 9 and vs 2019 16.3preview 4 

Can any one please help me to resolve this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kmuthukumar23.
This looks like an issue with the actual load-balancer/gateway you're using, which ends up dropping the connection. If this is the case, Azure SignalR service would definitely help. Can you give this a try? Is that a viable option for you?

@anurse do you have any guidance for these types of situations?

**Comment by mkArtakMSFT** [comment]
Actually, after a closer look to the logs you've shared, it looks more like the load-balancer doesn't preserve the route to forward the requests to, and the requests from the app end up hitting random servers. Is there a way you can configure sticky sessions? That should help.

**Comment by anurse** [comment]
I agree with @mkArtakMSFT, it looks like a load-balancer configuration issue. Can you confirm that you have [configured the site as specified in the SignalR docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-2.2#configure-the-app-in-azure-app-service)? Specifically, that "ARR Affinity" and "WebSockets" are both enabled.

**Comment by kmuthukumar23** [comment]
Hi @mkArtakMSFT / @anurse , thanks for your thoughts. But i have already tried this. But still it does not work.

![image](https://user-images.githubusercontent.com/31958591/65119214-9de37080-da09-11e9-8097-dbf01b8d0213.png)

**Comment by mkArtakMSFT** [comment]
We need more information about your setup. Can you please provide details about your network and service topology? Also, the server logs would help.

**Comment by anurse** [comment]
@kmuthukumar23 FYI, we have a doc that shows how to get diagnostic logs from SignalR as well as how to attach them in the GitHub issue so we can review them: https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
