### ISSUE TITLE
AspNetCore 3.0 Web API GET yields 415 Unsupported Media type

### ISSUE THREAD

**Issue by vintzl** [aspnet/AspNetCore#14069]
If I try a GET request with complex type as parameter (from Blazor here), AspNetCore 3.0 Web API yields 415 Unsupported Media type. If I am not mistaken, it did work with 2.2.

For example:

        [HttpGet]
        public List<Customer> Get([FromQuery] Request request)
        {
            List<Customer> customers = _query.Get(request);
            return customers;
        }

Request headers:

        Host: localhost:5004
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:64.0) Gecko/20100101 Firefox/64.0
        Accept: */*
        Accept-Language: en-US,en;q=0.5
        Accept-Encoding: gzip, deflate
        Referer: http://localhost:5000/customers
        origin: http://localhost:5000
        DNT: 1
        Connection: keep-alive
        Pragma: no-cache
        Cache-Control: no-cache

Response headers:

        HTTP/1.1 415 Unsupported Media Type
        Date: Tue, 17 Sep 2019 13:25:29 GMT
        Content-Type: application/json; charset=utf-8
        Transfer-Encoding: chunked

Seems `Content-Type: application/json` is missing in the Get Request.

Is there something I am missing? A setup? Or something wrong with json serialization?

**Comment by pranavkm** [comment]
Could you share a minimal repro sample?

**Comment by vintzl** [comment]
Sorry, it was caused by a bad server configuration.
