### ISSUE TITLE
Razor page generator generates unexpected lines 

### ISSUE THREAD

**Issue by arkadiuszwojcik** [aspnet/AspNetCore#14071]
### Describe the bug
I'm struggling with this issue recently but I'm not sure if this is a bug or I have wrong assumption about how Razor Pages works. I created simple Razor Page that derives from `RazorPage<TModel> `  Everythings is ok until Razor generates page code. Two bottom lines (shown on screenshot) imply compilation error. Why there are even generated? Looks like `PageContext` is used by AspNetCore `PageModel `class, but my model is not deriving such class. Can someone explain it?

### To Reproduce
Create Razor Page likeshown on the screenshot

### Expected behavior
Razor compiler should not (?) generate code lines showed on screenshot

### Screenshots
![razor_error](https://user-images.githubusercontent.com/2368976/65063408-7d220900-d97e-11e9-9896-7a29493213f4.png)

### Additional context
```
C:\Users\Arek>dotnet --info
Zestaw .NET Core SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   3.0.100-rc1-014190
 Commit:    c4d43f672d

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-rc1-014190\

Host (useful for support):
  Version: 3.0.0-rc1-19456-20
  Commit:  8f5d7b1ba4

.NET Core SDKs installed:
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pranavkm** [comment]
> created simple Razor Page that derives from `RazorPage<TModel>`

Razor Pages are meant to derive from `Microsoft.AspNetCore.Mvc.RazorPages.Page`. Picking a different base type is going to involve a fair bit of work. What is it that you're trying to do?

**Comment by arkadiuszwojcik** [comment]
@pranavkm I read a bit more about Razor Pages design and I think I have much cleaner picture now. What was confusing for me and other people aswell was two existing classes: `RazorPage` and `Page` but in separate namespaces. You are right I should use `Microsoft.AspNetCore.Mvc.RazorPages.Page` instead `RazorPage<TModel>`. Thanks for help.
