### ISSUE TITLE
[TS Client] Close handler on transports can cause issues with fallback

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#14075]
If a transport starts connecting and fails we will try to fallback to another transport. Unfortunately there is a race where we set `this.transport` for the next transport attempt and the previous failed transport calling its `onclose` handler which will set `this.transport` to `undefined`.

Setting `this.transport` for next transport attempt:
https://github.com/aspnet/AspNetCore/blob/2de6c732d1f410460a627cb75aca91ae2c741fd5/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L357

Setting `onclose` handler which can be triggered by previous failed transport:
https://github.com/aspnet/AspNetCore/blob/2de6c732d1f410460a627cb75aca91ae2c741fd5/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L410

This is a regression in 3.0 caused by https://github.com/aspnet/AspNetCore/pull/12524 😢

**Comment by anurse** [comment]
This would be a patch candidate. Let's consider this for the next 3.0 patch. Sketch up a PR that fixes it targeting `release/3.0` (DO NOT MERGE) and we'll run it through once the branch is open for servicing changes.

**Comment by springy76** [comment]
3.0 never should have been released with the knowledge of such regression more than 1 week earlier.

**Comment by DNF-SaS** [comment]
> 
> 
> 3.0 never should have been released with the knowledge of such regression more than 1 week earlier.

Full ack. We're having real issues with an important piece of software behind a firewall which does not support WebSockets.

**Comment by anurse** [comment]
This is queued for an upcoming patch. That's as fast as we can get this out. The regression was caught too late to stop the entire 3.0 product from shipping. If you're blocked by this, our suggestion would be to wait for the patch to be released before updating.

**Comment by BrennanConroy** [comment]
Fixed by #14114
