### ISSUE TITLE
Need a way to access a layout from a page

### ISSUE THREAD

**Issue by Yen** [aspnet/AspNetCore#14077]
[From my previous issue comment on aspnet/Blazor](https://github.com/aspnet/Blazor/issues/857#issuecomment-530776523)

### Is your feature request related to a problem? Please describe.
The feature that alterted me to this issue was trying to implement a generic breadcrumb system where the pages could provide context aware breadcrumbs (custom names and paths) without the breadcrumb component in the layout needing to know about each page.

### Describe the solution you'd like
I quote my response in the previous issue:

> I think this is a big oversight from how we structure pages in a traditional MVC application. With Blazor we have a way to pass state down the stack, but no way to pass it back up. The example of passing state back up in MVC is both ViewBag and sections.

>This functionality made it very complex to implement a breadcrumbs style component outside of using shared services to manually propagate the component initialisation. Even then, this is not really a good solution, there is no real guarantee from a page, with pages just being components, that there wont be multiple instances of it. I see this causing more serious issues on systems that need to ensure their state is maintained for the duration of the page, not just breadcrumbs where if they are wrong, in general everything else behaves.

>In the JS ecosystem we would be using state management tools like redux to pass state back up the "stack" so that the changes can be propagated back down. This is 100% possible to implement yourself at the moment, even in a generic way, but it's not a clean solution nor is it consistent with any form of library components. I think blazor needs to be opinionated on this, or at least how it functions at a lower level and we can build neater interfaces on top.

>Having something that serves as the reverse of a CascadingParameter would be a good start, something where I can have an output variable in the layout and multiple input variables throughout my view. Throw in some resolving logic to take the deepest instance of the input variable to update the output variable along with an option to have the output be an IEnumerable of your variables for things like breadcrumbs and I think many cases are covered.

>The above is ofc my own quick thoughts and not meant to be a proposal, just an idea of the kind of functionality that I think needs to be present in the framework at a centeralised level.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Yen.
You can do this by extracting all the common knowledge into a service, which you can register in DI and then getting it injected in both your components and layouts. Make sure you do not register it as `Transient`.

**Comment by Yen** [comment]
@mkArtakMSFT This was not a question, it's a feature request. Saying it's possible to implement something myself using DI is asp.net core is not really an answer to anything, I am aware I can implmenent whatever needed myself as I have done for this problem.

What I am asking for is an actual supported way to do something even as simple as setting the title on a different page. At the moment I know of now way blazor supports to do such thing which is as trivial as using the ViewBag in MVC.
(Again, I am aware here I can implement the slew of services and event listeners required to implement this, but I do not see this as a real solution so much as a workaround)

This is a major feature that is missing.

If you could change this so as to not disregard it as a question, and instead consider it as a real feature request for a feature that is needed to fulfill an incredible common need in web development. 

Thanks
