### ISSUE TITLE
IIS Benchmarks don't run

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#14085]
/cc @jkotalik @shirhatti 

Needs investigation on the server as even the windows log is useless in this case .

**Comment by anurse** [comment]
All that's remaining here is to make sure the benchmark is running (since @jkotalik couldn't do that until merging).

**Comment by jkotalik** [comment]
Looks like it started working, but it's now returning bad status codes: https://msit.powerbi.com/groups/b5743765-ec44-4dfc-91df-e32401023530/reports/10265790-7e2e-41d3-9388-86ab72be3fe9/ReportSection30725cd056a647733762?bookmarkGuid=Bookmark59bc684b6462276292bc

See: cloud, IISInProcess, windows, http.

**Comment by sebastienros** [comment]
I upgraded to 5.0.x all the things, which must have broken something. Can you check the logs to see what's failing (take it as an exercise, but I am still here to help you if you are blocked more than 30 seconds)

**Comment by jkotalik** [comment]
Missing TFM switch: https://github.com/aspnet/Benchmarks/commit/915ae66d5474b0d76a468545cf5c30780210a920. 

This is now working 😄
