### ISSUE TITLE
[Templates] Inconsistent log configuration between regular and SPA templates

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#14099]
We are using different logging settings for different templates. I don't believe this is on purpose. We should determine which one is the most correct/current recommendation and apply it to all templates.

**React**
https://github.com/aspnet/AspNetCore/blob/e46d376731605d8e64d00fb9be6bde5485a80005/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/React-CSharp/appsettings.json#L11-L15

**Razor pages**
https://github.com/aspnet/AspNetCore/blob/e46d376731605d8e64d00fb9be6bde5485a80005/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/appsettings.json#L34-L39

**React development**
https://github.com/aspnet/AspNetCore/blob/e46d376731605d8e64d00fb9be6bde5485a80005/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/React-CSharp/appsettings.Development.json#L2-L7

**Razor pages development**
https://github.com/aspnet/AspNetCore/blob/e46d376731605d8e64d00fb9be6bde5485a80005/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/appsettings.Development.json#L1-L9

**Comment by ryanbrandenburg** [comment]
Fixed by https://github.com/aspnet/AspNetCore/pull/14748
