### ISSUE TITLE
Unsubscribing from events in Blazor

### ISSUE THREAD

**Issue by aL3891** [aspnet/AspNetCore#14093]
Hello, i'm fairly new to blazor so i'm sorry if this is an obvious question. 
I'm wondering what the best practice if subscribing and unsubscribing to events from an injected service in a blazor component.

i have a `ILogger` service and a `LogView` component, in the component i subscribe to the event like this: 

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            Logger.NotifyLog += OnNotify;
        }
     ...
    }

First of all, is that the "right" way to do it? (it seems to be from the examples i've seen), but secondly, where should i unsubscribe from the event? There is no `Hide` or `Stop` type method that i've seen that's called when the component should stop updating itself.

Or are the event subscriptions cleaned up some other way? i have a custom proxy thing that's using weakreferences for this purpose, but if i remember correctly from netFX, regular events do not work like that right?

**Comment by campersau** [comment]
You can implement the `IDisposable` interface and unsubscribe there. It is called when the component is removed. https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#component-disposal-with-idisposable
Async disposal is tracked here https://github.com/aspnet/AspNetCore/issues/9960

**Comment by aL3891** [comment]
aha, great, thanks!
