### ISSUE TITLE
 In BLAZOR ! How to get the selected range of the content.

### ISSUE THREAD

**Issue by indrajjith** [aspnet/AspNetCore#14094]
### Describe the solution you'd like
Getting the range of the selected content from the defined set of contents.

### Additional context
Can anyone suggest a solution for it ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @indrajjith.
You will need to use JSInterop for this. There is no abstraction available in Blazor for doing this at the moment.

**Comment by indrajjith** [comment]
Thanks  @mkArtakMSFT  will try with the JsInterop.
