### ISSUE TITLE
Are you planning to remove HttpStatusCode 418?

### ISSUE THREAD

**Issue by IshamMohamed** [aspnet/AspNetCore#14097]
I saw in this [issue](https://github.com/aspnet/HttpAbstractions/issues/915), @glennc says they can revisit the issue for version 3.0 release. Just curious to know the status of that.

**Comment by khellang** [comment]
It won't happen for 3.0, that's for sure. The release is only 5 days away :smile:

TBH, I doubt it'll happen at all. [Node, Python (requests) and Go have all opted to keep it](http://save418.com/) and [the IETF draft for reserving 418](https://datatracker.ietf.org/doc/draft-nottingham-thanks-larry/) has expired a long time ago.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We have no plans doing this in the near future as this will be a breaking change.
