### ISSUE TITLE
How to retrieve the HttpContext from Blazor server-side ?

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#14090]
Well, I knew that after reading an article by Steve Anderson, but seems to have forgotten that... Thanks in advance.

**Comment by MV10** [comment]
Since Blazor server-side runs over SignalR, there is no HttpContext because HTTP is (usually) not involved.

https://github.com/aspnet/AspNetCore/issues/12432#issuecomment-513865287

**Comment by mkArtakMSFT** [comment]
Closing this as per @MV10 's answer.

**Comment by enetstudio** [comment]
Thanks @MV10 , I actually wanted to know how I can arrive at code like this:

var cookies = Context.GetHttpContext().Request.Cookies;

Context is ConnectionContext , I believe.
And this is a link to the a SignalR class that is supposed to return the HttpClient : https://github.com/aspnet/AspNetCore/blob/3cd5054eb5d8851b25881cd05cccb931aaa022e6/src/SignalR/server/SignalR/src/GetHttpContextExtensions.cs

What I looking for is a way to get client information such as IP address and browser name/version in Blazor server-side?

Thanks...

**Comment by MV10** [comment]
@enetstudio are you maybe thinking of this discussion? You said you saw something from @SteveSandersonMS about this, I happened across this recently while trying to discover whether the SignalR circuit info was exposed.

https://github.com/aspnet/AspNetCore/issues/5330

**Comment by enetstudio** [comment]
Thanks @MV10, I've seen the thread you linked to as well as this one: https://github.com/aspnet/SignalR/issues/1114

As I've said above, I am looking for a way to get client information such as IP address and browser name/version in Blazor server-side... I want to do something like: `var cookies = Context.GetHttpContext().Request.Cookies;` in my Blazor code. Note that Context is ConnectionContext, but how do I access the ConnectionContext ? This is what I'm trying to find out...
