### ISSUE TITLE
CORS - PATCH method is not being included in Access-Control-Allow-Methods

### ISSUE THREAD

**Issue by fazalWahid56** [aspnet/AspNetCore#14091]
I have been trying to enable cors for a patch method in dotnet core webapi.

I tried the following code:

```
services.AddCors(o => o.AddPolicy("CorsPolicy", builder =>
        {              
            builder
                .AllowAnyOrigin()
                .AllowAnyHeader()
                .AllowAnyMethod();
        }));
```
also tried `.WithMethods("PATCH","GET")`
and adding it to pipeline as 
```
app.UseCors("CorsPolicy"); 
app.UseMvc()
```

My Options call request header:

```
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: PUT
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Mode: no-cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
```

It returns 204-No-Content with following headers.

```
Access-Control-Allow-Headers: content-type
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, HEAD, OPTIONS
Access-Control-Allow-Origin: *
Date: Tue, 17 Sep 2019 10:59:23 GMT
Request-Context: appId=cid-v1:46d7928d-c15f-4a2f-bded-4035f2eaba1f
Server: Kestrel
```

The value of Access-Control-Allow-Methods in response header is always "GET, PUT, POST, DELETE, HEAD, OPTIONS". There would be no PATCH whatever I try.

**Comment by pranavkm** [comment]
@fazalWahid56 what version of ASP.NET Core are you using, we made a fair bit of changes to the middleware in 2.2. Could you share a minimal repro sample? The behavior you describe isn't what the CORS middleware or MVC's CORS filter do.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
