### ISSUE TITLE
Blazor - Support @Page static value directive

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#14098]
### Is your feature request related to a problem? Please describe.
In a .razor file, the @page directive must currently be used with a double quoted string literal

```
@page "/Foo/Bar"
```

This is problematic for code maintenance, as when you want to redirect to this page (from both client or server side code) you must again specify the same string literal, and then keep them in sync any time a the @route value is amended.

```
RedirectTo("/Foo/Bar"); // what if we change the @page route to /Foo/Baz in future we will have to correct this.

```

### Describe the solution you'd like
This feature proposes that you extend the @page directive so that it will also support a static value:

```
@page MyRoutes.HomePageRoute
```

or even:

```
@page $"{MyRoutes.HomePageRoute}"
```

This way, anywhere in client side code (or even on the server side if you share the same reference to `MyRoutes` between server and client) a redirect to that client side page can be performed and the route value itself can be maintained in one location.

**Comment by pranavkm** [comment]
Dup of this: https://github.com/aspnet/AspNetCore/issues/13453?

**Comment by mkArtakMSFT** [comment]
Thanks @pranavkm. Yes, this is dupe, so closing.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
Per the comment in the referenced issue, there is already a mechanism for doing this using the `@attribute` directive. We don't want to build different approaches for the same thing.

**Comment by dazinator** [comment]
Thanks I wasnt aware you could use the attribute directive, that works for me!
