### ISSUE TITLE
Blazor - Casting error on InputText binding

### ISSUE THREAD

**Issue by FluentGuru** [aspnet/AspNetCore#14109]
Given the following component definition:
```
<InputText 
                id="title"
                @bind-Value="testValue"
                @bind-Value:event="oninput"
                placeholder="Test value" />
```
When I write something on the text input I get the following error on the console:
```
blazor.webassembly.js:1 WASM: System.ArgumentException: Object of type 'Microsoft.AspNetCore.Components.ChangeEventArgs' cannot be converted to type 'System.String'.
```
I'm using blazor rc1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @FluentGuru.
Please have a look at https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0#inputtext-based-on-the-input-event
