### ISSUE TITLE
JWT Middleware parses "group" claim as "http://schemas.xmlsoap.org/claims/Group"

### ISSUE THREAD

**Issue by nibblesnbits** [aspnet/AspNetCore#14125]
### Issue
When ASP.NET Core 2.2 parses a JWT into a ClaimsIdentity, a claim named "group" gets converted to a claim with a type of "http://schemas.xmlsoap.org/claims/Group".  This causes unexpected behavior in code expecting the claim type to remain "group".

### Reproduce
Run this project: https://github.com/nibblesnbits/AspNetCore-Jwt-Issue

Hit the `GET /Token` endpoint, and then pass that token to the `GET /claims` endpoint.  You'll see the "group" claim show up with a type of "http://schemas.xmlsoap.org/claims/Group", whereas parsing the JWT by simply decoding the body shows it as "group", as intended.

**Comment by blowdart** [comment]
You can [turn off all mapping](https://mderriey.com/2019/06/23/where-are-my-jwt-claims/). Just make sure this doesn't break IsInRole checks if you're using them.

**Comment by nibblesnbits** [comment]
Is this covered in any official documentation?  Seems like an important thing to know when setting up that authentication method.  If not, could you direct me to the docs I could do a PR for?

**Comment by blowdart** [comment]
It's probably not, because the JWT configuration isn't really ours, but yes, a PR would be great, but I can't see JWT documentation at all, because it falls under ADAL. @Rick-Anderson what do you think we should do here?

**Comment by leastprivilege** [comment]
turn off all the mapping by default ;)

**Comment by blowdart** [comment]
Closing as there's no more questions

**Comment by leastprivilege** [comment]
Oldie but goldie

https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/
