### ISSUE TITLE
Scenarios are not running: ConnectionClose, ConnectionClose, DbMultiQueryDapper, DbMultiQueryEf, DbMultiQueryRaw ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14127]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| ConnectionClose | Linux, Physical, http, KestrelSockets | 9/18/19 12:46:54 AM +00:00 |
| ConnectionClose | Linux, Physical, https, KestrelSockets | 9/18/19 12:47:13 AM +00:00 |
| DbMultiQueryDapper | Linux, Cloud, http, KestrelSockets | 9/18/19 12:33:46 AM +00:00 |
| DbMultiQueryEf | Linux, Cloud, http, KestrelSockets | 9/18/19 12:34:30 AM +00:00 |
| DbMultiQueryRaw | Linux, Cloud, http, KestrelSockets | 9/18/19 12:33:01 AM +00:00 |
| DbMultiUpdateDapper | Linux, Cloud, http, KestrelSockets | 9/18/19 12:38:14 AM +00:00 |
| DbMultiUpdateEf | Linux, Cloud, http, KestrelSockets | 9/18/19 12:39:00 AM +00:00 |
| DbMultiUpdateRaw | Linux, Cloud, http, KestrelSockets | 9/18/19 12:37:29 AM +00:00 |
| EndpointPlaintext | Linux, Cloud, http, KestrelSockets | 9/18/19 12:10:04 AM +00:00 |
| HttpClient | Linux, Physical, http, KestrelSockets | 9/18/19 12:45:12 AM +00:00 |
| HttpClientFactory | Linux, Physical, http, KestrelSockets | 9/18/19 12:46:36 AM +00:00 |
| HttpClientParallel | Linux, Physical, http, KestrelSockets | 9/18/19 12:45:51 AM +00:00 |
| Json | Linux, Cloud, http, KestrelSockets | 9/18/19 12:13:54 AM +00:00 |
| Json | Linux, Cloud, https, KestrelSockets | 9/18/19 12:19:49 AM +00:00 |
| Json | Linux, Cloud, h2, KestrelSockets | 9/18/19 12:22:43 AM +00:00 |
| Json | Linux, Cloud, h2c, KestrelSockets | 9/18/19 12:23:27 AM +00:00 |
| JsonPlatform | Linux, Cloud, http, KestrelSockets | 9/18/19 12:13:05 AM +00:00 |
| MemoryCachePlaintext | Linux, Cloud, http, KestrelSockets | 9/18/19 12:24:10 AM +00:00 |
| MemoryCachePlaintextSetRemove | Linux, Cloud, http, KestrelSockets | 9/18/19 12:24:54 AM +00:00 |
| MvcDbMultiQueryDapper | Linux, Cloud, http, KestrelSockets | 9/18/19 12:35:58 AM +00:00 |
| MvcDbMultiQueryEf | Linux, Cloud, http, KestrelSockets | 9/18/19 12:36:43 AM +00:00 |
| MvcDbMultiQueryRaw | Linux, Cloud, http, KestrelSockets | 9/18/19 12:35:13 AM +00:00 |
| MvcDbSingleQueryEf | Linux, Cloud, http, KestrelSockets | 9/18/19 12:32:17 AM +00:00 |
| MvcJson | Linux, Cloud, http, KestrelSockets | 9/18/19 12:14:38 AM +00:00 |
| MvcJson2k | Linux, Cloud, http, KestrelSockets | 9/18/19 12:16:07 AM +00:00 |
| MvcJsonInput2k | Linux, Cloud, http, KestrelSockets | 9/18/19 12:17:35 AM +00:00 |
| MvcJsonNet | Linux, Cloud, http, KestrelSockets | 9/18/19 12:15:23 AM +00:00 |
| MvcJsonNet2k | Linux, Cloud, http, KestrelSockets | 9/18/19 12:16:52 AM +00:00 |
| MvcJsonNetInput2k | Linux, Cloud, http, KestrelSockets | 9/18/19 12:18:19 AM +00:00 |
| MvcPlaintext | Linux, Cloud, http, KestrelSockets | 9/18/19 12:07:54 AM +00:00 |
| Plaintext | Linux, Cloud, http, KestrelSockets | 9/18/19 12:04:57 AM +00:00 |
| Plaintext | Linux, Cloud, https, KestrelSockets | 9/18/19 12:19:04 AM +00:00 |
| PlaintextNonPipelined | Linux, Cloud, http, KestrelSockets | 9/18/19 12:05:43 AM +00:00 |
| PlaintextNonPipelined | Linux, Cloud, https, KestrelSockets | 9/18/19 12:20:34 AM +00:00 |
| PlaintextNonPipelined | Linux, Cloud, h2, KestrelSockets | 9/18/19 12:21:17 AM +00:00 |
| PlaintextNonPipelined | Linux, Cloud, h2c, KestrelSockets | 9/18/19 12:22:00 AM +00:00 |
| PlaintextNonPipelinedLogging | Linux, Physical, http, KestrelSockets | 9/18/19 12:49:53 AM +00:00 |
| PlaintextPlatform | Linux, Cloud, http, KestrelSockets | 9/18/19 12:02:35 AM +00:00 |
| ResponseCachingPlaintextCached | Linux, Cloud, http, KestrelSockets | 9/18/19 12:25:37 AM +00:00 |
| ResponseCachingPlaintextResponseNoCache | Linux, Cloud, http, KestrelSockets | 9/18/19 12:26:21 AM +00:00 |
| StaticFiles | Linux, Cloud, http, KestrelSockets | 9/18/19 12:12:15 AM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by anurse** [comment]
@sebastienros says these are fixed :)
