### ISSUE TITLE
ValidationVisitor.AllowShortCircuitingValidationWhenNoValidatorsArePresent does not get used

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#14126]
Looks like a check was missed when cleaning up the compat flags: https://github.com/aspnet/AspNetCore/commit/f113a20dfd9d0c7c991e425fd8000ed6b64d19a5#diff-b1a4bc63011cf639945db6b9023e76cd

**Comment by pranavkm** [comment]
@JeremySkinner I checked, and it doesn't look like FluentValidation uses this particular API on `ValidationVisitor`. Our current plan was to mark it as obsolete in 3.1 since setting it no longer does anything useful.

**Comment by JeremySkinner** [comment]
@pranavkm thanks, this shouldn't affect me
