### ISSUE TITLE
Scenarios are not running: ConnectionClose, ConnectionClose, ConnectionClose, ConnectionClose, DbFortunesDapper ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14122]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| ConnectionClose | Windows, Cloud, http, KestrelSockets | 9/17/19 9:47:19 PM +00:00 |
| ConnectionClose | Windows, Cloud, https, KestrelSockets | 9/17/19 9:47:41 PM +00:00 |
| ConnectionClose | Windows, Physical, http, KestrelSockets | 9/17/19 10:16:43 PM +00:00 |
| ConnectionClose | Windows, Physical, https, KestrelSockets | 9/17/19 10:17:04 PM +00:00 |
| DbFortunesDapper | Windows, Cloud, http, KestrelSockets | 9/17/19 9:39:55 PM +00:00 |
| DbFortunesDapper | Windows, Physical, http, KestrelSockets | 9/17/19 10:09:44 PM +00:00 |
| DbFortunesEf | Windows, Cloud, http, KestrelSockets | 9/17/19 9:40:42 PM +00:00 |
| DbFortunesEf | Windows, Physical, http, KestrelSockets | 9/17/19 10:10:28 PM +00:00 |
| DbFortunesRaw | Windows, Cloud, http, KestrelSockets | 9/17/19 9:39:10 PM +00:00 |
| DbFortunesRaw | Windows, Physical, http, KestrelSockets | 9/17/19 10:09:01 PM +00:00 |
| DbMultiQueryDapper | Windows, Cloud, http, KestrelSockets | 9/17/19 9:30:46 PM +00:00 |
| DbMultiQueryDapper | Windows, Physical, http, KestrelSockets | 9/17/19 10:01:03 PM +00:00 |
| DbMultiQueryEf | Windows, Cloud, http, KestrelSockets | 9/17/19 9:31:33 PM +00:00 |
| DbMultiQueryEf | Windows, Physical, http, KestrelSockets | 9/17/19 10:01:47 PM +00:00 |
| DbMultiQueryRaw | Windows, Cloud, http, KestrelSockets | 9/17/19 9:30:02 PM +00:00 |
| DbMultiQueryRaw | Windows, Physical, http, KestrelSockets | 9/17/19 10:00:20 PM +00:00 |
| DbMultiUpdateDapper | Windows, Cloud, http, KestrelSockets | 9/17/19 9:35:23 PM +00:00 |
| DbMultiUpdateDapper | Windows, Physical, http, KestrelSockets | 9/17/19 10:05:24 PM +00:00 |
| DbMultiUpdateEf | Windows, Cloud, http, KestrelSockets | 9/17/19 9:36:08 PM +00:00 |
| DbMultiUpdateEf | Windows, Physical, http, KestrelSockets | 9/17/19 10:06:08 PM +00:00 |
| DbMultiUpdateRaw | Windows, Cloud, http, KestrelSockets | 9/17/19 9:34:37 PM +00:00 |
| DbMultiUpdateRaw | Windows, Physical, http, KestrelSockets | 9/17/19 10:04:42 PM +00:00 |
| DbSingleQueryDapper | Windows, Cloud, http, KestrelSockets | 9/17/19 9:26:13 PM +00:00 |
| DbSingleQueryDapper | Windows, Physical, http, KestrelSockets | 9/17/19 9:56:41 PM +00:00 |
| DbSingleQueryEf | Windows, Cloud, http, KestrelSockets | 9/17/19 9:26:59 PM +00:00 |
| DbSingleQueryEf | Windows, Physical, http, KestrelSockets | 9/17/19 9:57:25 PM +00:00 |
| DbSingleQueryRaw | Windows, Cloud, http, KestrelSockets | 9/17/19 9:25:28 PM +00:00 |
| DbSingleQueryRaw | Windows, Physical, http, KestrelSockets | 9/17/19 9:55:57 PM +00:00 |
| EndpointPlaintext | Windows, Cloud, http, KestrelSockets | 9/17/19 9:04:18 PM +00:00 |
| EndpointPlaintext | Windows, Physical, http, KestrelSockets | 9/17/19 9:36:52 PM +00:00 |
| FortunesPostgreSql-Actix | Linux, Physical, http, KestrelSockets | 9/17/19 8:51:22 PM +00:00 |
| FortunesPostgreSql-NodeJs | Linux, Physical, http, KestrelSockets | 9/17/19 8:48:39 PM +00:00 |
| HttpClient | Windows, Cloud, http, KestrelSockets | 9/17/19 9:45:10 PM +00:00 |
| HttpClient | Windows, Physical, http, KestrelSockets | 9/17/19 10:14:40 PM +00:00 |
| HttpClientFactory | Windows, Cloud, http, KestrelSockets | 9/17/19 9:46:51 PM +00:00 |
| HttpClientFactory | Windows, Physical, http, KestrelSockets | 9/17/19 10:16:17 PM +00:00 |
| HttpClientParallel | Windows, Cloud, http, KestrelSockets | 9/17/19 9:45:57 PM +00:00 |
| HttpClientParallel | Windows, Physical, http, KestrelSockets | 9/17/19 10:15:26 PM +00:00 |
| Json | Windows, Cloud, http, KestrelSockets | 9/17/19 9:09:02 PM +00:00 |
| Json | Windows, Cloud, https, KestrelSockets | 9/17/19 9:15:46 PM +00:00 |
| Json | Windows, Cloud, https, HttpSys | 9/17/19 9:16:30 PM +00:00 |
| Json | Windows, Cloud, h2, KestrelSockets | 9/17/19 9:19:29 PM +00:00 |
| Json | Windows, Cloud, h2c, KestrelSockets | 9/17/19 9:20:14 PM +00:00 |
| Json | Windows, Physical, http, KestrelSockets | 9/17/19 9:40:40 PM +00:00 |
| Json | Windows, Physical, https, KestrelSockets | 9/17/19 9:46:55 PM +00:00 |
| Json | Windows, Physical, https, HttpSys | 9/17/19 9:47:24 PM +00:00 |
| Json | Windows, Physical, h2, KestrelSockets | 9/17/19 9:50:12 PM +00:00 |
| Json | Windows, Physical, h2c, KestrelSockets | 9/17/19 9:50:54 PM +00:00 |
| Json-Actix | Linux, Physical, http, KestrelSockets | 9/17/19 8:50:29 PM +00:00 |
| Json-FastHttp | Linux, Physical, http, KestrelSockets | 9/17/19 8:53:05 PM +00:00 |
| Json-NodeJs | Linux, Physical, http, KestrelSockets | 9/17/19 8:47:48 PM +00:00 |
| MemoryCachePlaintext | Windows, Cloud, http, KestrelSockets | 9/17/19 9:21:00 PM +00:00 |
| MemoryCachePlaintext | Windows, Physical, http, KestrelSockets | 9/17/19 9:51:37 PM +00:00 |
| MemoryCachePlaintextSetRemove | Windows, Cloud, http, KestrelSockets | 9/17/19 9:21:44 PM +00:00 |
| MemoryCachePlaintextSetRemove | Windows, Physical, http, KestrelSockets | 9/17/19 9:52:19 PM +00:00 |
| MvcDbFortunesDapper | Windows, Cloud, http, KestrelSockets | 9/17/19 9:42:11 PM +00:00 |
| MvcDbFortunesDapper | Windows, Physical, http, KestrelSockets | 9/17/19 10:11:55 PM +00:00 |
| MvcDbFortunesEf | Windows, Cloud, http, KestrelSockets | 9/17/19 9:42:58 PM +00:00 |
| MvcDbFortunesEf | Windows, Physical, http, KestrelSockets | 9/17/19 10:12:39 PM +00:00 |
| MvcDbFortunesRaw | Windows, Cloud, http, KestrelSockets | 9/17/19 9:41:26 PM +00:00 |
| MvcDbFortunesRaw | Windows, Physical, http, KestrelSockets | 9/17/19 10:11:12 PM +00:00 |
| MvcDbMultiQueryDapper | Windows, Cloud, http, KestrelSockets | 9/17/19 9:33:06 PM +00:00 |
| MvcDbMultiQueryDapper | Windows, Physical, http, KestrelSockets | 9/17/19 10:03:15 PM +00:00 |
| MvcDbMultiQueryEf | Windows, Cloud, http, KestrelSockets | 9/17/19 9:33:51 PM +00:00 |
| MvcDbMultiQueryEf | Windows, Physical, http, KestrelSockets | 9/17/19 10:03:59 PM +00:00 |
| MvcDbMultiQueryRaw | Windows, Cloud, http, KestrelSockets | 9/17/19 9:32:19 PM +00:00 |
| MvcDbMultiQueryRaw | Windows, Physical, http, KestrelSockets | 9/17/19 10:02:31 PM +00:00 |
| MvcDbMultiUpdateDapper | Windows, Cloud, http, KestrelSockets | 9/17/19 9:37:39 PM +00:00 |
| MvcDbMultiUpdateDapper | Windows, Physical, http, KestrelSockets | 9/17/19 10:07:34 PM +00:00 |
| MvcDbMultiUpdateEf | Windows, Cloud, http, KestrelSockets | 9/17/19 9:38:26 PM +00:00 |
| MvcDbMultiUpdateEf | Windows, Physical, http, KestrelSockets | 9/17/19 10:08:18 PM +00:00 |
| MvcDbSingleQueryDapper | Windows, Cloud, http, KestrelSockets | 9/17/19 9:28:30 PM +00:00 |
| MvcDbSingleQueryDapper | Windows, Physical, http, KestrelSockets | 9/17/19 9:58:52 PM +00:00 |
| MvcDbSingleQueryEf | Windows, Cloud, http, KestrelSockets | 9/17/19 9:29:16 PM +00:00 |
| MvcDbSingleQueryEf | Windows, Physical, http, KestrelSockets | 9/17/19 9:59:36 PM +00:00 |
| MvcDbSingleQueryRaw | Windows, Cloud, http, KestrelSockets | 9/17/19 9:27:45 PM +00:00 |
| MvcDbSingleQueryRaw | Windows, Physical, http, KestrelSockets | 9/17/19 9:58:08 PM +00:00 |
| MvcJson | Windows, Cloud, http, KestrelSockets | 9/17/19 9:09:46 PM +00:00 |
| MvcJson | Windows, Physical, http, KestrelSockets | 9/17/19 9:41:23 PM +00:00 |
| MvcJson2k | Windows, Cloud, http, KestrelSockets | 9/17/19 9:11:16 PM +00:00 |
| MvcJson2k | Windows, Physical, http, KestrelSockets | 9/17/19 9:42:49 PM +00:00 |
| MvcJsonInput2k | Windows, Cloud, http, KestrelSockets | 9/17/19 9:12:47 PM +00:00 |
| MvcJsonInput2k | Windows, Physical, http, KestrelSockets | 9/17/19 9:44:15 PM +00:00 |
| MvcJsonNet | Windows, Cloud, http, KestrelSockets | 9/17/19 9:10:31 PM +00:00 |
| MvcJsonNet | Windows, Physical, http, KestrelSockets | 9/17/19 9:42:06 PM +00:00 |
| MvcJsonNet2k | Windows, Cloud, http, KestrelSockets | 9/17/19 9:12:02 PM +00:00 |
| MvcJsonNet2k | Windows, Physical, http, KestrelSockets | 9/17/19 9:43:32 PM +00:00 |
| MvcJsonNetInput2k | Windows, Cloud, http, KestrelSockets | 9/17/19 9:13:32 PM +00:00 |
| MvcJsonNetInput2k | Windows, Physical, http, KestrelSockets | 9/17/19 9:44:58 PM +00:00 |
| MvcPlaintext | Windows, Cloud, http, KestrelSockets | 9/17/19 9:02:03 PM +00:00 |
| MvcPlaintext | Windows, Physical, http, KestrelSockets | 9/17/19 9:34:44 PM +00:00 |
| Plaintext | Windows, Cloud, http, KestrelSockets | 9/17/19 8:59:01 PM +00:00 |
| Plaintext | Windows, Cloud, http, HttpSys | 9/17/19 9:05:03 PM +00:00 |
| Plaintext | Windows, Cloud, https, KestrelSockets | 9/17/19 9:14:17 PM +00:00 |
| Plaintext | Windows, Cloud, https, HttpSys | 9/17/19 9:15:02 PM +00:00 |
| Plaintext | Windows, Physical, http, KestrelSockets | 9/17/19 9:31:54 PM +00:00 |
| Plaintext | Windows, Physical, http, HttpSys | 9/17/19 9:37:34 PM +00:00 |
| Plaintext | Windows, Physical, https, KestrelSockets | 9/17/19 9:45:43 PM +00:00 |
| Plaintext | Windows, Physical, https, HttpSys | 9/17/19 9:46:11 PM +00:00 |
| Plaintext-Actix | Linux, Physical, http, KestrelSockets | 9/17/19 8:49:33 PM +00:00 |
| Plaintext-FastHttp | Linux, Physical, http, KestrelSockets | 9/17/19 8:52:14 PM +00:00 |
| Plaintext-NodeJs | Linux, Physical, http, KestrelSockets | 9/17/19 8:46:57 PM +00:00 |
| PlaintextNonPipelined | Windows, Cloud, http, KestrelSockets | 9/17/19 8:59:49 PM +00:00 |
| PlaintextNonPipelined | Windows, Cloud, https, KestrelSockets | 9/17/19 9:17:15 PM +00:00 |
| PlaintextNonPipelined | Windows, Cloud, h2, KestrelSockets | 9/17/19 9:17:59 PM +00:00 |
| PlaintextNonPipelined | Windows, Cloud, h2c, KestrelSockets | 9/17/19 9:18:44 PM +00:00 |
| PlaintextNonPipelined | Windows, Physical, http, KestrelSockets | 9/17/19 9:32:37 PM +00:00 |
| PlaintextNonPipelined | Windows, Physical, https, KestrelSockets | 9/17/19 9:48:06 PM +00:00 |
| PlaintextNonPipelined | Windows, Physical, h2, KestrelSockets | 9/17/19 9:48:49 PM +00:00 |
| PlaintextNonPipelined | Windows, Physical, h2c, KestrelSockets | 9/17/19 9:49:30 PM +00:00 |
| PlaintextNonPipelinedLogging | Windows, Cloud, http, KestrelSockets | 9/17/19 9:51:28 PM +00:00 |
| PlaintextNonPipelinedLogging | Windows, Physical, http, KestrelSockets | 9/17/19 10:19:45 PM +00:00 |
| PlaintextNonPipelinedLoggingNoScopes | Windows, Cloud, http, KestrelSockets | 9/17/19 9:52:13 PM +00:00 |
| PlaintextNonPipelinedLoggingNoScopes | Windows, Physical, http, KestrelSockets | 9/17/19 10:20:28 PM +00:00 |
| ResponseCachingPlaintextCached | Windows, Cloud, http, KestrelSockets | 9/17/19 9:22:29 PM +00:00 |
| ResponseCachingPlaintextCached | Windows, Physical, http, KestrelSockets | 9/17/19 9:53:02 PM +00:00 |
| ResponseCachingPlaintextRequestNoCache | Windows, Cloud, http, KestrelSockets | 9/17/19 9:23:59 PM +00:00 |
| ResponseCachingPlaintextRequestNoCache | Windows, Physical, http, KestrelSockets | 9/17/19 9:54:30 PM +00:00 |
| ResponseCachingPlaintextResponseNoCache | Windows, Cloud, http, KestrelSockets | 9/17/19 9:23:14 PM +00:00 |
| ResponseCachingPlaintextResponseNoCache | Windows, Physical, http, KestrelSockets | 9/17/19 9:53:46 PM +00:00 |
| ResponseCachingPlaintextVaryByCached | Windows, Cloud, http, KestrelSockets | 9/17/19 9:24:43 PM +00:00 |
| ResponseCachingPlaintextVaryByCached | Windows, Physical, http, KestrelSockets | 9/17/19 9:55:14 PM +00:00 |
| StaticFiles | Windows, Cloud, http, KestrelSockets | 9/17/19 9:07:16 PM +00:00 |
| StaticFiles | Windows, Physical, http, KestrelSockets | 9/17/19 9:39:40 PM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by anurse** [comment]
@sebastienros says these are fixed :)
