### ISSUE TITLE
Is Blazor development is possible (on linux) or someone have worked with Blazor on linux

### ISSUE THREAD

**Issue by anirugu** [aspnet/AspNetCore#14131]
Yesterday I tried Blazor on my windows machine and it's look good. I am interested to use my linux machine for programming web-app using Blazor.

Do someone have successfully used Blazor on Mac and linux. Most of time I seen demos using VS on Windows machine.

Did someone tried it practically.

**Comment by Eilon** [comment]
It works great on Windows, Mac, and Linux. There is nothing OS-specific about developing with it or where it can run.

**Comment by javiercn** [comment]
@anirugu Thanks for contacting us.

@Eilon answer is correct. 

If you find something is not working on either Mac or Linux, please file an issue with a repro project and detailed repro steps and we'll investigate.

Thanks!
