### ISSUE TITLE
The Input was not valid

### ISSUE THREAD

**Issue by TehWardy** [aspnet/AspNetCore#14143]
I'm not sure if this is a bug or more of a feature request.

I keep getting "bug reports" telling me that HTTP POST's are not being accepted with this error and it's near impossible to track down exactly what the issue is.

Whilst the exception is valid, this in the body ...

```
{
	"error": {
		"code": "",
		"message": "The input was not valid.",
		"details": [
			{
				"code": "",
				"message": "The input was not valid."
			}
		]
	}
}
```

... doesn't give us any hints as to how to fix this.

Is there any way M$ can improve this and perhaps tell us where / at what point in the parsing process of the data it encountered invalid input?

Ideally, still call the controller action and pass the details in to model state so that the response can be properly handled.

**Comment by pranavkm** [comment]
@TehWardy this doesn't look like an error payload MVC produces so it's hard to tell what could be done to improve this. Can you share a minimal repro for this?

**Comment by TehWardy** [comment]
I get this response as an out of the box behaviour from an OData controller request in the event that the POST'ed data is somehow not conforming to the type metadata during parsing (at least that's my suspicion as to where the issue is.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by TehWardy** [comment]
The issue here is  that the information the framework provides is not helpful.
I know how to debug the issue from previous feedback which seems to be "attach the debugger and look in the VS console window".

By default, my existing code does something like this in the controller ...

```
            if (ModelState.IsValid)
            {
                var result= SomeInternalCall(args);
                return Ok(result);
            }
            else
                return BadRequest(ModelState);
```

... in .Net 4 this used to returned the actual problem, in the .Net Core version of the same functionality I simply get back the json blob above which tells the caller literally nothing.

Whilst the issue is debug-able in a dev environment, as soon as this hits a production server the issues become a black hole and there's often no way to hook the additional information since AspNet Core logs key information to only the VS console and nowhere else (another issue i've raised).

In this instance, it would be nice to have the actual reason as to why the framework felt the provides was invalid rather than just "nope, you did a wrong thing".

**Comment by TehWardy** [comment]
Here's an example of the logging issue that I think this is related to ...
https://github.com/aspnet/AspNetCore/issues/12301#issuecomment-521686032
...
specifically the end of that trail where it references ...
https://github.com/aspnet/AspNetCore/issues/13170
