### ISSUE TITLE
Blazor String Parameters in event handlers in the new Preview 9, rc.

### ISSUE THREAD

**Issue by MichaelPeter** [aspnet/AspNetCore#14144]
### Is your feature request related to a problem? Please describe.

Hi I just updated from AspNetCore 3.0 Preview 7 to AspNetCore 3.0 RC1 and there the event handler syntax changed significantly.

The old version was this:
onclick=@(async ()=> SetPagerSize("forward"))

I havent found something yet, but is there a way to pass strings as parameters.

There passing string parameters was possible 

How can I pass strings to functions in RC1?

<button class="btn pagebutton btn-secondary" @onclick="(async ()=> NavigateToPage("next"))">Next</button>

since the content of @onclick= needs to be inside "", the string "next" will end this string. Is there already a syntax to fix this? When I use '' like in javascript 

### Describe the solution you'd like
Not shure what would be the best soltion, now I extract all my strings to constants. In javascript you can always use '' inside the "", but that would violate the C# syntax.

**Comment by MV10** [comment]
Enclose it with apostrophes:

`@onclick='(async () => await Foo("bar"))'`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MichaelPeter .
The parser is smart enough to still parse `"`, even when it seems it's wrapped twice:
```razor 
@OnClick="@(async ()=> NavigateToPage("next"))"
```

**Comment by mkArtakMSFT** [comment]
If this is not working for you, please let us know and we'll look into this further.

**Comment by MichaelPeter** [comment]
Thanks that solved my problem :)
