### ISSUE TITLE
Blazor - NavLink should also be able to navigate outside of app (i.e full page reload)

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#14149]
### Is your feature request related to a problem? Please describe.
I am trying to use `NavLink` in a blazor app, to navigate to a URL outside of the SPA. In my case I want to redirect the user to the same spa but served up on a different subdomain. This should therefore bypass routing and do a full page reload (i.e request to the server).

However it seems when using NavLink (and I assume a plain `<a>` tag) the router intercepts the navigation and doesn't allow the request through to the server.

Ofcourse I can choose not to use NavLink or an anchor tag, and instead handle my Navigation click and use NavigationManager to do the redirect - but this is a lot more effort for rendering a simple link that it should be.

I thought that perhaps adding `target="_blank"` to the NavLink in order to open the url in a new tab would be enough to force a reload / request to the server - but that doesn't work, the router still intercepts the navigation.

```
<NavLink href="foo.localhost:5001" target="_blank"></NavLink> // opens in new tab but router still intercepts the route
```

### Describe the solution you'd like
Perhaps allow an additional attribute to be specified that will indicate that the router should allow the request through to the server?

```
<NavLink href="foo.localhost:5001" target="_blank" skip-router="true"></NavLink></td>

```

**Comment by javiercn** [comment]
Thanks for contacting us @dazinator.

You can use a plain `a` tag an set the `target` attribute to `_self` and that should prevent the link from being intercepted. I believe it should also work with NavLink

Let us know if that doesn't work.

**Comment by dazinator** [comment]
@javiercn but I actually want to open the link in a new tab - therefore target = _blank is mandatory for that. There is no other way I can see of opening a link in a new tab with blazor - even navigation manager only does a redirect in the current tab?

**Comment by javiercn** [comment]
@dazinator I'm not sure I understand. Adding "target=_blank" to your link/navlink should be the right thing to do. Are you saying that adding 'target=_blank' doesn't work?

**Comment by dazinator** [comment]
@javiercn 
Thank you and apologies. Yes it does indeed work - I thought you meant you had to use "target=_self" in order to bypass routing but "target=_blank" works equally as well and is the bahaviour I need. I had actually attempted this before opening this issue but the reason it wasn't working was a mistake in my `href` - the I was using `href="foo.bar:5000"` which was missing the scheme. Once I added the scheme to the href everything now works. Thanks for clarifying the bahaviour!

**Comment by simonziegler** [comment]
I would like to add my voice to this. It would be good to have a switch in NavLink that allows me to force an external link rather than an internal relative one. Would be nice if I could set the target too if I wanted.

My specific use case is to allow NavLinks to make use of external credentials managers such as Azure B2C, where the link must be external, even though it is to the same site.

**Comment by javiercn** [comment]
Hi @simonziegler . 
 
**It looks like you are posting on a closed issue!**

We're very likely to lose track of your bug/feedback/question unless you: 
1. Open a new issue 
2. Explain very clearly what you need help with 
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
