### ISSUE TITLE
Blazor Web Assembly - Allow arguments/parameters to be passed in on creation.

### ISSUE THREAD

**Issue by daveh101** [aspnet/AspNetCore#14147]
I am new to this, so forgive me if not structured in the right way, or if it is not possible/irrelevant.

### Describe the solution you'd like
I am playing around with the hosted version of client side Blazor.  I see that it is possible to access the route parameters, query string, and even cookies from the client side Blazor deployment.

However, I am keen to explore the idea of being able to pass in a number of 'startup' parameters to the app that is deployed.

Because the client app is deployed through an asp.netcore server I like the idea of having the server do a bit of work - for example, maybe calculate the theme that the client app should be using.

Passing some of these startup settings through the route parameter, or a query string  could feel messy to the end user, and utilising cookies I imagine would also create their own issues.  

Passing it into the startup (I assume the router tag) feels like a good idea, if these were then available through the DI of the client that would be even better.

Hopefully that makes sense.  Would be interested to know if it is a possibility, would others benefit from this.  Also, are there any drawbacks, or security issues that would mean this is a bad idea?

Happy to answer any quesitons on my thoughts of this if more info is needed

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dnfclas.
We're going to make some changes in the startup area of the application in the near future. We will see how this feedback fits into these future discussions.
