### ISSUE TITLE
Diference between Components and Blazor package?

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#14142]
In my component library [Blazorise](https://github.com/stsrki/Blazorise) I'm trying to add support for static files for server-side applications without the need for copying js and css files manually to _wwwroot_ folder. So far, I referenced `Microsoft.AspNetCore.Blazor` in all my library projects. It's working just fine for client-side applications and all js and css files are included automatically.

But when using that package for server-side it's not working. When I add reference to `Microsoft.AspNetCore.Components` package instead of `Microsoft.AspNetCore.Blazor` it works for server-side by adding  `"_content/Lib.Name/file.js"`. The problem is now I must include `"_content/Lib.Name/file.js"` to both client-side and server-side applications to make it work.

I remember a few months ago reading that  `Microsoft.AspNetCore.Blazor` is the right thing to use but I cannot find the source now.

My question is, what is the right way to do this? And what is the right package to use? Is it `Microsoft.AspNetCore.Components` or `Microsoft.AspNetCore.Blazor`?

**Comment by javiercn** [comment]
@stsrki The right thing to do is to create a razor class library and use the static web assets feature. See https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#create-an-rcl-with-static-assets for details.

We have an ongoing issue with the feature when used on blazor wasm standalone apps. But if your class library is being referenced from an asp.net core host, everything should work fine.

**Comment by stsrki** [comment]
@javiercn So that means `Microsoft.AspNetCore.Components` is prefered over `Microsoft.AspNetCore.Blazor`. What is the difference between these two?

My demo apps are using _asp.net core host_ model but I do not know what the users of my library are using. I want them to have the easiest setup as possible. That's why I'm asking these questions.

**Comment by javiercn** [comment]
@stsrki If you are writing a library you should use the razor class library. 

Microsoft.AspNetCore.Blazor is specific for writing Blazor WebAssembly applications. Using a Razor Class Library is the way to go. 

The other model is a prototype that is going away in favor of the production version of the feature. (Static Web Assets).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
