### ISSUE TITLE
DataMember/JsonProperty Attribute is not honored in dotnet core 3.0

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14158]
_From @jikuma on Wednesday, September 18, 2019 5:04:06 PM_

I created a sample dotnet core 3.0 web api project and did the following changes,

1. Create a Model class TestData

```
using System.Runtime.Serialization;
namespace WebApplication17.Models
{
    [DataContract]
    public class TestData
    {
        [DataMember(Name = "testaction")]
        public string Action { get; set; }
    }
}
```

Then I made changes in controller WeatherForecastController, to add a post endpoint

```
[HttpPost("package/{packageName}/version/{version}")]
public void Post(string packageName, string version, [FromBody] TestData activityPayload)
        {
            Console.WriteLine(activityPayload.Action);
        }
```

Now I made a call from postman or curl with body 

```
{	
	"testaction": "action"	
}
```

Still in Post method of WeatherForecastController activityPayload.Action is null. I was expecting it to be 'action'

_Copied from original issue: dotnet/core#3400_

**Comment by scalablecory** [comment]
@jikuma Was this working in 2.2? I thought `DataContract` was purely a WCF thing -- wasn't aware `DataContract` was ever supported in ASP.NET.

**Comment by antonioortizpola** [comment]
It could not be because Net core is using [Newtonsoft](https://www.newtonsoft.com/json)?

I have been achieving the same with [`JsonProperty`](https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm)

```
internal class IvrCardOperationRegistryResponseWrapper
{
    [SuppressMessage("ReSharper", "StringLiteralTypo")]
    [JsonProperty("registroOperacionTarjetaResponse")]
    public IvrResponseInfo IvrResponseInfo { get; set; }
}
```

**Comment by pranavkm** [comment]
@jikuma ASP.NET Core 3.0 uses System.Text.Json for JSON serialization by default which does not support using `DataMemberAttribute`. You could switch to using `Newtonsoft.Json` which does support these attributes. See the migration guides for switching: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support
