### ISSUE TITLE
Blazor & ASP.NET Core 3.0 3.0.100-preview9-014004-1 Custom PaginatedList<T>

### ISSUE THREAD

**Issue by vintzl** [aspnet/AspNetCore#14153]
How to deal with `System.Text.Json`'s JsonSerializer with custom "list", like the one here:

- https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.2#add-paging-to-students-index

Cause, with something like `Http.GetJsonAsync<PaginatedList<ViewModel>>`, I get this:

        WASM: ﻿System.NullReferenceException: Object reference not set to an instance of an object.
        blazor.webassembly.js:formatted:2033
        WASM:   at System.Text.Json.ReadStackFrame.CreateEnumerableValue (System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& state) <0x3145038 + 0x001be> in <81e9245ca982431695a55cc67ffb3b86>:0 
        blazor.webassembly.js:formatted:2033
        WASM:   at System.Text.Json.JsonSerializer.HandleStartArray (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& state) <0x3144d10 + 0x0018a> in <81e9245ca982431695a55cc67ffb3b86>:0 
        blazor.webassembly.js:formatted:2033
        WASM:   at System.Text.Json.JsonSerializer.ReadCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x2eaabf0 + 0x00220> in <81e9245ca982431695a55cc67ffb3b86>:0 
        blazor.webassembly.js:formatted:2033
        WASM:   at System.Text.Json.JsonSerializer.ReadCore (System.Type returnType, System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader) <0x2ea9f18 + 0x0003e> in <81e9245ca982431695a55cc67ffb3b86>:0 
        blazor.webassembly.js:formatted:2033
        WASM:   at System.Text.Json.JsonSerializer.ParseCore (System.String json, System.Type returnType, System.Text.Json.JsonSerializerOptions options) <0x2ea3810 + 0x00086> in <81e9245ca982431695a55cc67ffb3b86>:0 
        blazor.webassembly.js:formatted:2033
        WASM:   at System.Text.Json.JsonSerializer.Deserialize[TValue] (System.String json, System.Text.Json.JsonSerializerOptions options) <0x319c5f8 + 0x00022> in <81e9245ca982431695a55cc67ffb3b86>:0 
        blazor.webassembly.js:formatted:2033
        WASM:   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T] (System.Net.Http.HttpClient httpClient, System.String requestUri) <0x2fb35e8 + 0x000f6> in <900d091618e14952821fd2fc9b26598c>:0 
        blazor.webassembly.js:formatted:2033

**Comment by pranavkm** [comment]
@vintzl could you share the model type that you're trying to read? A minimal repro would be great.

**Comment by vintzl** [comment]
Try with the PaginateList link

- https://github.com/vintzl/405-Method-Not-Allowed-AND-Custom-PaginatedList

And, please, take a look at the `WeatherForecastController.cs`, and test the commented action (rise `System.NullReferenceException: Object reference not set to an instance of an object`.)

**Comment by pranavkm** [comment]
Thanks for the repro app @vintzl. I've filed an issue here - https://github.com/dotnet/corefx/issues/41242 - make the error reporting nicer. In the meanwhile, you have to provide a parameterless constructor on your derived type for the serializer to be able to instantiate your type:

```
 public PaginatedList() {}
```

More importantly though, the serializer doesn't have a way to represent to a sequence that also has arbitrary properties. The serialized content is effectively going to be a JSON array. Consider using containment instead of inheritance to solve this.

**Comment by vintzl** [comment]
@pranavkm 
Thanks for your reply.

Unfortunately, I have not given enough attention to your answer, [and I have got trapped twice by the same "inheritance issue"](https://github.com/aspnet/AspNetCore/issues/14254)…
