### ISSUE TITLE
Blazor - NavigationManager.Uri is a string not a uri?

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#14151]
### Is your feature request related to a problem? Please describe.
Not really a feature.. more of an api consideration.
In my blazor wasm application,  I need to get the current port from the current url.
I was expecting to be able to do something like `NavigationManager.Uri.Port` however NavigationManager.Uri is a string not Uri.

Of course I can parse a URI myself from that string but I would rather it was a URI to begin with to avoid having to do this. At the moment I abuse the `ToAbsoluteUri` to get a typed URI rather than string:

```
NavigationManager.ToAbsoluteUri("/").Port
```

### Describe the solution you'd like
Why not change NavigationManager.Uri to a System.Uri ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
We usually try to avoid exposing `Uri` in APIs.
