### ISSUE TITLE
CookieConsent does not exist in MVC template

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14159]
_From @neoffer on Tuesday, September 17, 2019 9:04:32 PM_

# CookieConsent does not exist in MVC template 

Using .NET Core 3.0 rc1 with VS 2019 Preview MVC template, the project does not contains CookieConsent.

# Also...

I’ve tried to add CookieConsent partial view, added Startup config for CookieConsent and added partial tag helper to the _Layout but the consent still did not appear.

_Copied from original issue: dotnet/core#3392_

**Comment by HaoK** [comment]
@danroth27 @blowdart this was intentional per https://github.com/aspnet/Scaffolding/pull/1066

**Comment by blowdart** [comment]
We're closing this issue as the behaviour discussed seems to be by design.

**Comment by danroth27** [comment]
@scalablecory See https://docs.microsoft.com/aspnet/core/security/gdpr?view=aspnetcore-3.0 for instructions on how to add cookie consent back if you still want it.
