### ISSUE TITLE
blazor localStorage F5 Refresh “Object reference not set to an instance of an object.”

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14162]
_From @azbo on Wednesday, September 18, 2019 6:31:28 AM_

# Issue Title
blazor localStorage F5 Refresh “Object reference not set to an instance of an object.”

# General

visual studio version:
![image](https://user-images.githubusercontent.com/5110699/65121580-0b9b9680-da22-11e9-8aba-13419b6fe644.png)

sdk version:.net core sdk 3.0 rc1

localStorage get set js: 
![image](https://user-images.githubusercontent.com/5110699/65120060-a181f200-da1f-11e9-8e80-d8211e46aba7.png)

Index.razor set localStorage:
![image](https://user-images.githubusercontent.com/5110699/65120150-c4aca180-da1f-11e9-8f5c-79c9ff9ee394.png)

Counter.razor get localStorage:
![image](https://user-images.githubusercontent.com/5110699/65120249-e86fe780-da1f-11e9-9103-f9306a779ad0.png)

Reiteration steps：
step1: ![image](https://user-images.githubusercontent.com/5110699/65120326-063d4c80-da20-11e9-9545-633e0ac4c409.png)

step2:
![image](https://user-images.githubusercontent.com/5110699/65120407-28cf6580-da20-11e9-8f46-d3719b60ae26.png)

step3:
F5 Refresh or
![image](https://user-images.githubusercontent.com/5110699/65120463-443a7080-da20-11e9-8573-d290c21ebcb6.png)

step4 except:
![image](https://user-images.githubusercontent.com/5110699/65120905-f8d49200-da20-11e9-8ebb-14db66c937d2.png)

_Copied from original issue: dotnet/core#3394_

**Comment by javiercn** [comment]
@scalablecory You are trying to perform JS interop during OnInitializedAsync which is not supported and might not work well in all scenarios. The right place to do JS interop (where is safe to do so) is inside OnAfterRenderAsync

**Comment by pranavkm** [comment]
@azbo this is a dup of https://github.com/aspnet/AspNetCore/issues/13396. We'll use the other issue to track fixing this in 3.1. In the meanwhile, @javiercn's recommendation is correct.
