### ISSUE TITLE
Unable to reach deployed service with external IP address

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14163]
_From @TehAbyss on Monday, September 16, 2019 7:04:36 PM_

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

I followed the tutorial and had deployed my service to Azure and I was able to retrieve the external IP address. However, I am unable to reach the page http://[YOUR EXTERNAL IP ADDRESS]/api/Values. And I did replace [YOUR EXTERNAL IP ADDRESS] with the external IP address provided to me by the "kubectl get service mymicroservice --watch" command. I got the error "Hmmm...can't reach this page".

_Copied from original issue: dotnet/core#3382_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @scalablecory.
@glennc any suggestions regarding this? Should this issue be moved somewhere else?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
