### ISSUE TITLE
identityserver4 mvc client must support https

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14164]
_From @zdp120 on Wednesday, September 18, 2019 4:50:25 AM_

I have use identityserver4 with asp.net core 2.2, mvc client not must support https, but after update asp.net core 3.0 ,the client must support https . This is a bug or not.

_Copied from original issue: dotnet/core#3393_

**Comment by blowdart** [comment]
This is a question best asked of [Identity Server](https://github.com/IdentityServer).
