### ISSUE TITLE
Class-level validation not performed if property-level validation is invalid

### ISSUE THREAD

**Issue by snappyfoo** [aspnet/AspNetCore#14166]
### Describe the bug
I have a class with various validation attributes on its properties, e.g. StringLength. I also have a custom validation attribute applied on the class. What I'm finding is that if a property on the class fails validation, the class validation is not run. This means not all errors are reported at once. This isn't the case for property validation, where it can pick up multiple properties in error, i.e. it doesn't stop at the first. But if there is an invalid property, it shortcuts the class validation. Is it possible to class validation under all circumstances?

### To Reproduce
1. Using ASP.NET Core 2.2...
2. Have a controller tagged as [ApiController] so you get the automatic validation and response
3. Configure an InvalidModelStateResponseFactory on the ApiBehaviourOptions
4. Create a model with class and property validation attributes
5. Set up a controller endpoint that takes this model from the request body
5. Violate the class level validation and observe in the InvalidModelStateResponseFactory that the error appears in the ModelState
6. Now additionally violate a property level validation
7. Notice that only the property error is in the ModelState

### Expected behavior
Both errors should appear in the ModelState

**Comment by pranavkm** [comment]
@snappyfoo by default, MVC attempts to emulate DataAnnotation's validation behavior where type-level validation is only applied if property validation completes without producing validation errors. However, you could change this behavior by setting `MvcOptions.ValidateComplexTypesIfChildValidationFails`:

```C#
services.AddMvc(o => o.ValidateComplexTypesIfChildValidationFails = true)
```

**Comment by pranavkm** [comment]
@snappyfoo the property was added as part of the 3.0 release: https://github.com/aspnet/AspNetCore/issues/8519

**Comment by pranavkm** [comment]
@snappyfoo the property exists in 2.2 as part of `ValidationVisitor` which is the type that does the validation, but isn't easily configurable outside of it. However, you could configure one by injecting a custom instance of `IObjectModelValidator` that configures the `ValidationVisitor` correctly. Here's the one that MVC injects: https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.Core/src/DefaultObjectValidator.cs.

```C#
services.TryAddSingleton<IObjectModelValidator, CustomObjectValidator>
```

Modify https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.Core/src/DefaultObjectValidator.cs#L48 in your `CustomObjectValidator` to set `visitor.ValidateComplexTypesIfChildValidationFails = true`
