### ISSUE TITLE
Identity -> DownloadPersonalData.cshtml.cs Remove dependencies on Newtonsoft.Json

### ISSUE THREAD

**Issue by Honjoy** [aspnet/AspNetCore#14178]
now only dependencies Newtonsoft.Json in DownloadPersonalData.cshtml.cs.
maybe remove is better.

**Comment by blowdart** [comment]
@hoak we should use whatever json formatter is configured

**Comment by HaoK** [comment]
Breaking change to remove refs, so we can't do this in 3.1, moving to 5.0
