### ISSUE TITLE
signalr.js connected callback called multiple times

### ISSUE THREAD

**Issue by kofifus** [aspnet/AspNetCore#14175]
Monitoring my SignalR js client I often get multiple connected callbacks  (of `start()`) without the disconnected callback being called before them or at all.

This seems to me to be buggy behavior as my code does various inits in the connected callback that only make sense if the connection was _not_ connected before.

Any help with this ?

**Comment by BrennanConroy** [comment]
Are you using ASP.NET Core SignalR or ASP.NET SignalR?

**Comment by kofifus** [comment]
.NET core latest preview

**Comment by BrennanConroy** [comment]
Could you share your code?

I don't understand what you mean by multiple connected callbacks as the only "callback" for start is the start promise returning.

**Comment by kofifus** [comment]
yeah sure, my code looks like this:

```
connection
        .start().then(
            () => fconnected()
            , err => {
                fdisconnected(err);
                setTimeout(connectToHub(fconnected, fdisconnected), 100);
            });
```

What I get is multiple calls to `fconnected` (once every few minutes) without a single call to `fdisconnected`

**Comment by kofifus** [comment]
I may be confused about this, closing this now.
