### ISSUE TITLE
Add NotAcceptable (406) response to AspNetCore controller

### ISSUE THREAD

**Issue by coderuid** [aspnet/AspNetCore#14171]
### Is your feature request related to a problem? Please describe.
No problem at all :) But we have a lot of different responses at https://github.com/aspnet/AspNetCore/tree/release/3.1/src/Mvc/Mvc.Core/src but no HTTP 406.

### Describe the solution you'd like
1. Add [NotAcceptableObjectResult.cs.zip] (decompressed)(https://github.com/aspnet/AspNetCore/files/3633374/NotAcceptableObjectResult.cs.zip)
 to /src
2. Add
`public NotAcceptableObjectResult NotAcceptable([ActionResultObjectValue] object error) => new NotAcceptableObjectResult(error);
`
to ControllerBase.cs

**Comment by coderuid** [comment]
I tried to push PR, but 
> remote: Permission to aspnet/AspNetCore.git denied to coderuid.

If someone could give me permissions, I would send PR.

**Comment by javiercn** [comment]
@coderuid Thanks for contacting us.

This behavior is already present in all results that perform content negotiation, before we add more action results we would like to understand what scenario you have that requires to have an explicit action result for this.

ControllerBase offers helpers for most common HTTP responses but in general we don't try to be exhaustive as that makes the already big API surface to increase, decreasing the UX for the most common cases.

Alternatively you can create your own base class and add the helper methods there.

See https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/ObjectResultExecutor.cs#L153 for details.
