### ISSUE TITLE
how to run web , dotnet core 3.0.100-rc1 ，CentOS 7  , error It was not possible to find any compatible framework version

### ISSUE THREAD

**Issue by 0CrazyGuy9** [aspnet/AspNetCore#14185]
dotnet /app/WebSite.exe
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      3.0.0-rc1.19457.4 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
-----------------------------------------------------------------------------------------------
dotnet --list-sdks
3.0.100-rc1-014190 [/usr/share/dotnet/sdk]

**Comment by blowdart** [comment]
You need to install a [2.2 runtime or SDK](https://dotnet.microsoft.com/download)

**Comment by 0CrazyGuy9** [comment]
Thank you

I'm sorry for that. It's my own problem
