### ISSUE TITLE
Automagical @page directive

### ISSUE THREAD

**Issue by HughPH** [aspnet/AspNetCore#14186]
### Is your feature request related to a problem? Please describe.
Sometimes people forget to put `@page` on their pages, but this information can be derived from the pre-build directory structure anyway.

### Describe the solution you'd like
Pre-build, .razor pages could have `@page` added to them, with the lowercase version of the filename without its extension. The path would come from the project's folders, and the root would be the location of the App.razor file.

For example, App.razor is in the *razor* folder. There are pages in *pages* and *components* folders under the *razor* folder. The *Counter.razor* file in the *pages* directory would automatically - if one has not been provided - get prepended with *`@page("/pages/counter")`* while the *DataView.razor* file in the *components* folder would be prepended with *`@page("/components/dataview")`*

**Comment by jbomhold3** [comment]
It would be nice to have a feature in Blazor and razor pages that created its routes based on **namespace** location and component name. Examples

| Namespace | Class Name | Router output |
| ------------- | ------------- |----------------|
| Sample | Index | /index |
| Sample | Login| /login|
| Sample.Admin | Users | /admin/users|
| Sample.Admin | UsersPage | /admin/users
| Sample.Admin.Users | Manager | /admin/users |

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @HughPH.
This is being tracked as part of #8787.
