### ISSUE TITLE
Issue with AzureAD UI with PageViewLocationFormats

### ISSUE THREAD

**Issue by dmc91** [aspnet/AspNetCore#14184]
### Describe the bug
When using the AzureAD UI library to handle sign out my layout throws an exception due to not being able to find my Partials which are located in /Pages/Partials rather than /Pages/Shared/. This works fine normally when using the below code.

```
services.AddMvc(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            })
            .AddRazorOptions(options =>
            {
                options.PageViewLocationFormats.Add("/Pages/Partials/{0}.cshtml");
            })
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
```

I'm unsure if the cause is the RazorOptions not persisting after sign out.

### Expected behavior
Settings to persist after sign out which would allow the partials to be found within the layout.

### Additional context
The solution is utilising the Microsoft.Identity.Web project.

**Comment by javiercn** [comment]
@dmc91 Thanks for contacting us.

Could you provide a github repo with a minimal repro project and detailed repro steps so that we can investigate?

Thanks.

**Comment by dmc91** [comment]
Hi,

I've created a minimal repro at https://github.com/dmc91/DotNetRazorPagesSignoutIssue

I have removed the details of our Azure domain etc which will need to be replaced for the application to work.

After adding these details, the application should prompt for a login then display a blank index page. Top right on the header is a dropdown with a sign out option, the problem occurs after signing out the application will no longer find the partial views which are defined on startup using AddRazorOptions.

Thanks

**Comment by javiercn** [comment]
@dmc91 Thanks for the repro project. 

The Azure AD UI uses the layout from the app, and that layout uses the _SideBar partial. The PageViewLocationFormats defines how to find views for pages without areas, given that the Azure AD UI is within an area, you need to add it to AreaPageViewLocationFormats.

Based on your repro I changed the code to and used my own tenant and that fixed the logout issue.
```csharp
            .AddRazorOptions(options =>
            {
                options.PageViewLocationFormats.Add("/Pages/Partials/{0}.cshtml");
                options.AreaPageViewLocationFormats.Add("/Pages/Partials/{0}.cshtml");
            })
```

If after performing the changes mentioned here you still experience the problem please reopen the issue.
