### ISSUE TITLE
Views not changed after save&refresh in Visual Studio 2019 preview 4 with asp.net core rc1 and MVC project

### ISSUE THREAD

**Issue by urza** [aspnet/AspNetCore#14194]
I created new asp.net core rc1 MVC project from VS2019 preview 4. I started the project from Visual Studio with debugger (F5), I then modify and save some View (cshtml file), I save the file and hit refresh in the browser.

### Expected behavior
I expect the browser to reload with new content of the View, instead it has the old View

I can run without debugger (CTRL+F5) but then I can't debug.
In VS2017 and asp.net core 2.0 this setup (debugger + ability to modify views) was working.
Is it not possible in VS2019 and asp.net core3?

**Comment by pranavkm** [comment]
Without [runtime compilation](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#runtime-compilation) enabled, the update behavior for changes to cshtml files is identical to other C# files in the project. When not debugging, VS will rebuild the project when it detects changes to the project and you'd see the view update.

**Comment by urza** [comment]
Thanks, after following instructions in your link it works. 
I expected it to be default like this in VS 2019 as well.
