### ISSUE TITLE
ApplicationStarted variant that is consistent between WebHost/GenericHost

### ISSUE THREAD

**Issue by Timovzl** [aspnet/AspNetCore#14213]
When @AceHack [asked](https://github.com/aspnet/Hosting/issues/1538) about a hook for `GenericHost` _after_ the server has started (as is `WebHost`'s default behavior, but not `GenericHost`'s), David Fowler [mentioned](https://github.com/aspnet/Hosting/issues/1538#issuecomment-417122396):

> We can look at changing the web host to fire the event after hosted services but that’s a breaking change. We’ll see what it looks like and decide if it’s ok for 2.2 or 3.0.

The documentation was updated in https://github.com/aspnet/AspNetCore.Docs/pull/8354, but I have found no ticket that actually mentions doing something about the discrepancy (although 2.2 and 3.0 were mentioned as the options originally).

**Can we get a variant of `ApplicationStarted` that is consistent between WebHost and GenericHost?**

If changing the current behavior is not an option (particularly now that the window for changing this in 3.0 has closed), perhaps we could introduce a new token that _is_ consistent across hosts?

**Comment by Tratcher** [comment]
The long term plan is to transition everyone to GenericHost and obsolete WebHost. At that point consistency will irrelevant.

**Comment by Timovzl** [comment]
@Tratcher That is good to know. Thank you. Is this planned for a particular version yet, such as 5.0?

**Comment by Tratcher** [comment]
5.0 is the soonest it could happen, but we haven't made firm plans.
