### ISSUE TITLE
FileProviders  MvcRazorRuntimeCompilationOptions vs RazorViewEngineOptions  

### ISSUE THREAD

**Issue by DiegoStefanon** [aspnet/AspNetCore#14221]
### Describe the bug

in core 3.rc1  is not working anymore  ->
  services.Configure<**MvcRazorRuntimeCompilationOptions**>(opts =>
                           opts.FileProviders.Add(fp) 
                        );

in core 2.2 was good ->
RazorViewEngineOptions FileProviders.Add    was working 

### Expected behavior
In asp.net core 3 rc1 
RazorViewEngineOptions  has no more FileProviders property 
so using the new one MvcRazorRuntimeCompilationOptions is not working anymore

Thanks

**Comment by DiegoStefanon** [comment]
I have discovered that in order to work I have to deactivate other services, ok

**Comment by dn32** [comment]
> I have discovered that in order to work I have to deactivate other services, ok

I'm experiencing the same problem and couldn't understand your solution. Can it be any clearer?

**Comment by DiegoStefanon** [comment]
Yes, it does not work anymore like last net core
in core 2.2 was good ->
**RazorViewEngineOptions FileProviders.Add (was working)**

In asp.net core 3 
RazorViewEngineOptions has no more FileProviders property
so using the new one **MvcRazorRuntimeCompilationOptions** is not working anymore

In order to work you have to add the CompileOnRuntime and deactivate some functionalities
and activates some tricks..

In past version 2.2 it was working
I'm not understanding why they changed or may be it's a bug ?

**Comment by geotinc** [comment]
Same problem for me after migrating to asp.net core 3.0.
Embedded views not found...

Any workaround ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @DiegoStefanon.
This is an intentional breaking change in 3.0, and is documented here: https://github.com/aspnet/Announcements/issues/343

**Comment by mkArtakMSFT** [comment]
@geotinc we have a separate issue tracking the `Embedded Views` issue you're facing: #14374

**Comment by nfplee** [comment]
It looks like AddMvcRazorRuntimeCompilation has been renamed to AddRazorRuntimeCompilation. I cannot comment on https://github.com/aspnet/Announcements/issues/343.

**Comment by mkArtakMSFT** [comment]
@nfplee as stated in the announcement:
> Please use aspnet/AspNetCore#7647 for further discussions or questions.

**Comment by constructor** [comment]
Also same problem after migrating from core 2.2 to asp.net core 3.0.
RazorViewEngineOptions has no options.FileProviders property and using MvcRazorRuntimeCompilationOptions results in embedded views not being found.

**Comment by dario-l** [comment]
We use FileProviders to pointing out views in different modules. When Project is compiled in Release mode views are copied to the main project. **We do not use compilation.**

In 3.0 it is not working. **Why?**
