### ISSUE TITLE
No forwarded headers from the load balancer

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore#14229]
### Describe the bug
Is there any requirement for the header forwarding to work? I used to receive header values but I believe after I change the backend of the load balancer to use HTTPS, all headers are gone. No forwarded headers from the load balancer to the app at all.

I have the following code in startup.cs:
```
services.Configure<ForwardedHeadersOptions>(options => options.ForwardedHeaders = ForwardedHeaders.All);
```
```
            app.Use(async (context, next) =>
            {
                // Request method, scheme, and path
                _logger.LogInformation(JsonConvert.SerializeObject(new RequestLog(context?.Request?.Method, 
                                    context?.Request?.Scheme, 
                                    context?.Request?.PathBase, 
                                    context?.Request?.Path, 
                                    context?.Request?.Host.ToString(), 
                                    context?.Request?.ContentLength, 
                                    context?.Connection?.RemoteIpAddress?.ToString(), 
                                    context?.Request?.QueryString.ToString(), 
                                    context?.Request?.ContentType,
                                    context?.Request?.Protocol,
                                    context?.Request?.Headers
                                    )));
                await next();
            });
```
I extract the headers in RequestLog:
```
            if (headers != null)
                foreach (var header in headers)
                    if (header.Key.Equals("X-Forwarded-For") || header.Key.Equals("X-Original-For"))
                        IP = header.Value;
                    else if (header.Key.Equals("X-Forwarded-Proto") || header.Key.Equals("X-Original-Proto"))
                        X_Forwarded_Proto = header.Value;
                    else if (header.Key.Equals("X-Forwarded-Host") || header.Key.Equals("X-Original-Host"))
                        X_Forwarded_Host = header.Value;
```
But I never get any value in all 3 headers. Any advice and insight is appreciated.

### To Reproduce
1. Using this version of ASP.NET Core '...': 2.2
2. Run this code '....'
3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`
```
# dotnet --info

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
Please share the output from the troubleshooting instructions here:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#troubleshoot

What proxy are you using, and how did you configure it?

**Comment by khteh** [comment]
Log shown in Kibana that there is no X-Forwarded-<foo> received:
![Screenshot from 2019-09-23 09-32-33](https://user-images.githubusercontent.com/3871483/65397794-92b38a80-dde5-11e9-925b-6936a976228b.png)

Bash console showing no CORS header from the ASP.Net Core 2.2 app:
![Screenshot from 2019-09-23 09-34-16](https://user-images.githubusercontent.com/3871483/65397811-ab23a500-dde5-11e9-9068-996d37814a91.png)

I have added KnownNetworks but to no avail:
```
options.KnownNetworks.Add(new IPNetwork(IPAddress.Parse("10.0.0.0"), 16));
```

**Comment by Tratcher** [comment]
Why is "X_Forwarded_Host" showing up in that screen shot. That's not the same as "X-Fowarded-Host".

Log all of the headers, not selected fields.

**Comment by khteh** [comment]
That's the property names defined in my POCO class serialized and logged by Serilog.
```
                _logger.LogInformation(JsonConvert.SerializeObject(new RequestLog(context?.Request?.Method, 
                                    context?.Request?.Scheme, 
                                    context?.Request?.PathBase, 
                                    context?.Request?.Path, 
                                    context?.Request?.Host.ToString(), 
                                    context?.Request?.ContentLength, 
                                    context?.Connection?.RemoteIpAddress?.ToString(), 
                                    context?.Request?.QueryString.ToString(), 
                                    context?.Request?.ContentType,
                                    context?.Request?.Protocol,
                                    context?.Request?.Headers
                                    )));
```

**Comment by khteh** [comment]
OK. I am rebuilding and redeploying with logging ALL headers now...

**Comment by khteh** [comment]
I notice that the X-Forwarded-For is recording the LB's IP and `HttpRequest.Connection.RemoteIpAddress` records the *original* client's IP. Shouldn't it be the other way round? The `LocalIP` in the attached picture is `HttpRequest.Connection.RemoteIpAddress` while `IP` is `X-Forwarded-For`:

![Screenshot from 2019-09-23 11-21-01](https://user-images.githubusercontent.com/3871483/65400422-b16d4d80-ddf4-11e9-91af-197a2a0ff408.png)

**Comment by Tratcher** [comment]
> `IP` is `X-Forwarded-For`

Or is it X-Original-For? 
```
                    if (header.Key.Equals("X-Forwarded-For") || header.Key.Equals("X-Original-For"))
                        IP = header.Value;
```
The forwarded headers middleware removes X-Forwarded-For, sets RemoteIpAddress , and saves the old values of RemoteIpAddress in  X-Original-For.

**Comment by khteh** [comment]
So X-Original-For / X-Forwarded-For is the origin of the request, the client's IP address (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For). However, what happen now with the middleware is the opposite of this expected behaviour?

**Comment by khteh** [comment]
After going through the logs collected, I have also observed that the X-Forwarded- / X-Original- only appears when `Host` equals the destination domain in the format of `www.domain.com`. It doesn't work if the `Host` is IP address of the domain. Not sure if this is due to the LB ingress matching rules or some other reasons..?

**Comment by anurse** [comment]
> But I never get any value in all 3 headers. Any advice and insight is appreciated.

The whole point of forwarded headers is to **remove** the `X-Forwarded-For` header and update the properties (Scheme, Host, etc.) with the values, so that's expected.

> So X-Original-For / X-Forwarded-For is the origin of the request, the client's IP address

`X-Original-For` is the origin of the request, which in a proxy situation **is not the browser client**, it is **the proxy**.

Can you walk back to what you are actually seeing and what you *expect* to see, but don't see? We're having trouble assessing if there's an issue or just a misunderstanding about how the middleware works (possibly docs need to be improved).

**Comment by khteh** [comment]
Thanks for your explanation. I will just use RemoteIpAddress as the *browser client*'s IP address and `X-Original-For` as the immediate hop's IP address.

I have updated my application to capture all `X-<foo>` headers in my logger's properties and this is what I get:
![Screenshot from 2019-09-25 09-54-41](https://user-images.githubusercontent.com/3871483/65562963-ad6b3800-df7a-11e9-9991-4f62e0248c44.png)

As seen, all `X-Forwarded-<foo>` are null. `X-Original-<foo>` captures the LB's information but why is the `X-Original-Host` null?

**Comment by anurse** [comment]
> I will just use RemoteIpAddress as the _browser client_'s IP address and `X-Original-For` as the immediate hop's IP address.

Yep, when the forwarded headers middleware is in place, that's the correct behavior. That middleware configures the HttpContext to look like it came from the original client, so `RemoteIpAddress` should be the browser client (as long as you are **after** the forwarded headers middleware in the pipeline).

> `X-Original-<foo>` captures the LB's information but why is the `X-Original-Host` null?

My _assumption_ (though @Tratcher would know better) is that since `X-Original` is supposed to be capturing the original data from the request the load-balancer made, the load balancer *may not have provided a `Host` header value* (or perhaps provided an empty value). You could check the headers provided by the original request using a middleware **before** the Forwarded Headers middleware to see what the original request provided. Is it possible the load balancer is making `HTTP/1.0` requests?

**Comment by khteh** [comment]
Yes AWS LB is terminating HTTP/2 and only using HTTP/1.1 with the backend.

**Comment by anurse** [comment]
> only using HTTP/1.1 with the backend.

HTTP/1.1 is not HTTP/1.0 ;). If using HTTP/1.1 the `Host` header is generally *required*. Can you capture the original headers sent by the load balancer (**before** the forwarded headers middleware runs)? That might help us identify why `X-Original-Host` is showing as empty.
