### ISSUE TITLE
Question about Microsoft.AspNetCore.Hosting.Server.Abstractions

### ISSUE THREAD

**Issue by catcherwong** [aspnet/AspNetCore#14227]
Can not find out the 3.0 RC version of  `Microsoft.AspNetCore.Hosting.Server.Abstractions` in [nuget](https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting.Server.Abstractions/).

Is this package unavailable in dot net core 3.0?

**Comment by davidfowl** [comment]
@catcherwong You need to add a FrameworkReference in .NET Core 3.0 to use those APIs now, the package no longer exists. See https://github.com/aspnet/Announcements/issues/325 and https://github.com/aspnet/Announcements/issues/324

@DamianEdwards we really need that library guidance.

**Comment by catcherwong** [comment]
@davidfowl Thank you vary much!  

Solved with the following code.

```
<FrameworkReference Include="Microsoft.AspNetCore.App" />
```
