### ISSUE TITLE
Suggestion - change events declaration syntax

### ISSUE THREAD

**Issue by dmitryuck** [aspnet/AspNetCore#14230]
We have now this syntax:

```
<p>CurrentCount: @currentCount</p>
<button class="btn btn-primary" @onclick="IncrementCount">Increment</button>

@code {
  int currentCount = 0;
 
  void IncrementCount()
  {
    currentCount++;
  }
}
```

Change syntax to:

```
<button class="btn btn-primary" onclick="@IncrementCount">Increment</button>
```

To use @ symbol before name of the function which is in the code block like we use it before variable @currentCount.

And left attribute onclick= as original HTML declaration

**Comment by javiercn** [comment]
@dmitryuck Thanks for contacting us.

We deliberately switched from 
```
<button class="btn btn-primary" onclick="@IncrementCount">Increment</button>
```
to
```
<button class="btn btn-primary" @onclick="IncrementCount">Increment</button>
```
to clearly separate JavaScript events from Blazor events.

We don't plan to change the syntax again as we believe the current syntax makes thing clearer and changing it in the future would break existing apps.
