### ISSUE TITLE
Latest preview (.NET Core SDK (3.0.100-rc1-014190), React Templates Broken

### ISSUE THREAD

**Issue by pkellner** [aspnet/AspNetCore#14233]
Running the RC listed in subject, React template fails with both auth no auth.

macOS 10.14.6

Steps:

create empty directory,
dotnet new react
dotnet build
dotnet run

npm: 6.11.2
node: 10.14.2

Gives the result below:

dotnet new react 
The template "ASP.NET Core with React.js" was created successfully.
 
Processing post-creation actions...
Running 'dotnet restore' on /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/xx.csproj...
  Restore completed in 194.95 ms for /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/xx.csproj.
 
Restore succeeded.
 
MBPro15-i9:xx peterkellner$ dotnet build
Microsoft (R) Build Engine version 16.3.0-preview-19455-02+4a2d77107 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
 
  Restore completed in 22.31 ms for /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/xx.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  xx -> /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/bin/Debug/netcoreapp3.0/xx.dll
  xx -> /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/bin/Debug/netcoreapp3.0/xx.Views.dll
  v10.14.2
  Restoring dependencies using 'npm'. This may take several minutes...
  
  > fsevents@1.2.9 install /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/ClientApp/node_modules/chokidar/node_modules/fsevents
  > node install
  
  node-pre-gyp WARN Using request for node-pre-gyp https download 
  [fsevents] Success: "/Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/ClientApp/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
  
  > fsevents@1.2.9 install /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/ClientApp/node_modules/jest-haste-map/node_modules/fsevents
  > node install
  
  node-pre-gyp WARN Using request for node-pre-gyp https download 
  [fsevents] Success: "/Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/ClientApp/node_modules/jest-haste-map/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
  
  > core-js@2.6.9 postinstall /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/ClientApp/node_modules/babel-runtime/node_modules/core-js
  > node scripts/postinstall || echo "ignore"
  
  Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
  
  The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
  > https://opencollective.com/core-js 
  > https://www.patreon.com/zloirock 
  
  Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
  
  
  > core-js-pure@3.1.4 postinstall /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/ClientApp/node_modules/core-js-pure
  > node scripts/postinstall || echo "ignore"
  
  Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
  
  The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
  > https://opencollective.com/core-js 
  > https://www.patreon.com/zloirock 
  
  Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
  
  
  > core-js@2.6.9 postinstall /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx/ClientApp/node_modules/oidc-client/node_modules/core-js
  > node scripts/postinstall || echo "ignore"
  
  Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
  
  The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
  > https://opencollective.com/core-js 
  > https://www.patreon.com/zloirock 
  
  Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
  
  added 1555 packages from 755 contributors and audited 902686 packages in 22.46s
  found 2 critical severity vulnerabilities
    run `npm audit fix` to fix them, or `npm audit` for details
 
Build succeeded.
    0 Warning(s)
    0 Error(s)
 
Time Elapsed 00:00:28.35
MBPro15-i9:xx peterkellner$ dotnet run
info: Microsoft.AspNetCore.SpaServices[0]
      Starting create-react-app server on port 53437...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/Users/peterkellner/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Development
Content root path: /Users/peterkellner/Documents/svcc-pwa2/aspnetcore/xx
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
npmfail: Microsoft.AspNetCore.SpaServices[0]
      There might be a problem with the project dependency tree.
      It is likely not a bug in Create React App, but something you need to fix locally.
      
      The react-scripts package provided by Create React App requires a dependency:
      
        "babel-eslint": "10.0.1"
      
      Don't try to install it manually: your package manager does it automatically.
      However, a different version of babel-eslint was detected higher up in the tree:
      
        /Users/peterkellner/Documents/svcc-pwa2/node_modules/babel-eslint (version: 10.0.3) 
      
      Manually installing incompatible versions is known to cause hard-to-debug issues.
      
      If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
      That will permanently disable this message but you might encounter other issues.
      
      To fix the dependency tree, try following the steps below in the exact order:
      
        1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
        2. Delete node_modules in your project folder.
        3. Remove "babel-eslint" from dependencies and/or devDependencies in the package.json file in your project folder.
        4. Run npm install or yarn, depending on the package manager you use.
      
      In most cases, this should be enough to fix the problem.
      If this has not helped, there are a few other things you can try:
      
        5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
           This may help because npm has known issues with package hoisting which may get resolved in future versions.
      
        6. Check if /Users/peterkellner/Documents/svcc-pwa2/node_modules/babel-eslint is outside your project directory.
           For example, you might have accidentally installed something in your home folder.
      
        7. Try running npm ls babel-eslint in your project folder.
           This will tell you which other package (apart from the expected react-scripts) installed babel-eslint.
      
      If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
      That would permanently disable this preflight check in case you want to proceed anyway.
      
      P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!
      
      npm ERR! code ELIFECYCLE
      
fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! errno 1
      
fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! xx@0.1.0 start: `rimraf ./build && react-scripts start`
      npm ERR! Exit status 1
      npm ERR! 
      npm ERR! Failed at the xx@0.1.0 start script.
      npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
      
      
fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! A complete log of this run can be found in:
      
fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR!     /Users/peterkellner/.npm/_logs/2019-09-22T18_46_01_348Z-debug.log

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pkellner.
@javiercn can you please try this out?

**Comment by pkellner** [comment]
What is “this”?

**Comment by javiercn** [comment]
I can't repro the issue with .NET Core RTM. My machine had node11, but I believe our CI uses node10.

**Comment by pkellner** [comment]
What's the link to RTM? (or release). I can test that on my machine. BTW, got the same error on Angular. I thought maybe you guys just slipped on React.

**Comment by pkellner** [comment]
BTW, I did test on Windows and got the same error yesterday so it wasn't a funky build on my mac but something more serious.

**Comment by javiercn** [comment]
@pkellner We have automation for all these tests. RTM bits can be found in https://dot.net
I have v10.16.0 on my machine and I don't see this issue either. If you can capture more details it would help us help you.

**Comment by pkellner** [comment]
Just downloaded the release 3 and it worked with no errors including this: 
`dotnet new react --auth Individual --name WebAppAdmin `
which is what I started with.
