### ISSUE TITLE
Blazor Server should use absolute paths for blazor.server.js and for connecting to the Blazor hub

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#14246]
It looks like Blazor Server is using relative paths in a couple of places that limit when it can be used. This caused some issues when I tried to use Blazor components in an MVC app on any view other than the home page.

Repro steps:

- Create an MVC app
- Add `services.AddServerSideBlazor()` to `Startup.ConfigureServices` and `endpoints.MapBlazorHub()` in `Startup.Configure`.
- Add the *blazor.server.js* script to the layout using the script tag we use in the Blazor Server template: `<script src="_framework/blazor.server.js"></script>`
- Add a Razor component to the project with some sort of user interactivity support.
- Add the component to the *Privacy.cshtml* page: `@(await Html.RenderComponentAsync<MyComponent>(RenderMode.ServerPrerendered))`
- Run the app and browser to the Privacy page

Actual result:
- The component is not interactive, because the request for *blazor.server.js* goes to */Home/_framework/blazor.server.js*. 
- To work around this issue, update the script tag to use `~/`: `<script src="~/_framework/blazor.server.js"></script>`. **Should we do this everywhere?**
- The component is still not interactive because the SignalR client tries to connect to `/Home/_blazor/`. This seems like a bug we need to fix in *blazor.server.js*?

**Comment by javiercn** [comment]
Using base relative paths is deliberate. If you serve components from a different path you can add
```
<base href="~/" />
```
to set the base path correctly.

Alternatively, you can configure the url explicitly in the blazor signalr options using
```
Blazor.start({
                configureSignalR: builder.UseUrl('@Html.Content("/_blazor")'
            });
```

**Comment by SteveSandersonMS** [comment]
Yes, you **must** set `<base href>` correctly otherwise other things can't work either (routing). Given correct base href, the relative URLs are correct, so this is by design.

Leaving open just so it comes up in triage in case there's anything else to say.

**Comment by mkArtakMSFT** [comment]
Closing this as answered.

**Comment by danroth27** [comment]
Set the base URI where? On each page for whatever route?
