### ISSUE TITLE
Blazor ServerSide IE11 Router w/ parameters doesn't work 3.0 RC1

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#14256]
Create the default ServerSide Blazor's template application. Use the https://github.com/Daddoon/Blazor.Polyfill Polyfill to make it work in IE11.

It all works fine, unless you decide to use parameters in your routes, for example:

Change the counter component to receive a int parameter, 

`@page "/counter/{id:int}"`

Now that page won't be found,  showing the message "Sorry, there's nothing at this address."

If you access the counter's URL from Chrome or Edge, it works as expected.
I'm using http, not https in my localhost.

Regards

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrdlx.
In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.
