### ISSUE TITLE
[v3.0] When Newtonsoft will be dropped completely?

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14259]
_From @dehghani-mehdi on Sunday, September 22, 2019 9:53:41 AM_

Hi,

I used following command to generate single exe file for my project:
`dotnet publish -r win-x64 -c Release /p:PublishTrimmed=true`

In publish directory there are `Newtonsoft.Json.dll` and `Newtonsoft.Json.Bson.dll`. I didn't use `Newtonsoft` at all, so did you drop `Newtonsoft` in v3 or not?

Maybe `Newtonsoft` is referenced by other packages, am I right? if so, when Microsoft drop `Newtonsoft` from other packages (_`Microsoft.*` and `System.*`_)?

_Copied from original issue: dotnet/core#3420_

**Comment by scalablecory** [comment]
_From @nathan-alden on Monday, September 23, 2019 12:04:59 PM_

~~You're almost certainly going to need Json.NET now and in the future as Microsoft's own JSON implementation does not support the higher-level abstractions we're all used to (i.e., traversing and modifying a JSON document). Microsoft's implementation, from what I've read and experimented with, is really more about performance than usefulness.~~

See comment below.

**Comment by scalablecory** [comment]
_From @dasMulli on Monday, September 23, 2019 12:31:30 PM_

I think this particular issue is more about how the linker could do a better job breaking apart asp.net core to determine that no user path requires newtonsoft.json - or that the framework may need changes to enable to the linker to break it apart more easily.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dehghani-mehdi.
The NewtonSoft.Json library is not part of the shared framework. There should be some other package you reference, which potentially brings the library in. You can find that by examining `project.assets.json` file in the `obj` directory.

**Comment by dehghani-mehdi** [comment]
@mkArtakMSFT First of all, why you closed the issue? be professional please, this is a Microsoft repository.

I just used standard (if you may) packages, system.* and microsoft.*, so knowing which package use Json.Net how helps to resolve this issue?

p.s: If you don't open the issue, I'll open another one.

**Comment by SimonCropp** [comment]
@mkArtakMSFT if nothing uses any of the types in NewtonSoft, shouldnt it be trimmed when the publish occurs?

**Comment by mkArtakMSFT** [comment]
> @mkArtakMSFT if nothing uses any of the types in NewtonSoft, shouldn't it be trimmed when the publish occurs?

it's hard to know whether the app references it or not. You can definitely see whether you explicitly use it or not, but any other API you call (from libraries or the framework) can reference it internally, and that will result the library to be included in the final bits.

**Comment by SimonCropp** [comment]
> it's hard to know whether the app references it or not

why? you can walk through all the assemblies and check their references
