### ISSUE TITLE
UI project broken in .NET Core 3

### ISSUE THREAD

**Issue by freshe** [aspnet/AspNetCore#14266]
Hi,

I have a solution with multiple projects including a NET.Sdk.Razor project for shared UI.
Trying to follow the 2.2 to 3.0 migration from Microsoft Docs. From what i understand i should now remove the PackageReference and replace it with a FrameworkReference. 

The NET.Sdk.Web projects compiles just fine but getting a lot of errors in the Razor project.

<img width="998" alt="Screenshot 2019-09-23 at 20 42 18" src="https://user-images.githubusercontent.com/6495600/65453484-9249dc80-de43-11e9-84f9-96bc32215fc5.png">

**Comment by pranavkm** [comment]
@freshe I realized the migration notes weren't correct. What you need do to is to set `AddRazorSupportForMvc` in your project file:

```diff
- <RazorLangVersion>3.0</RazorLangVersion>
+ <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
```

Could you give this a try?

**Comment by freshe** [comment]
@pranavkm Worked like a charm, thank you!

**Comment by pranavkm** [comment]
The migration guides should update in a just a bit: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#razor-class-library.
