### ISSUE TITLE
Support basic and digest authentication

### ISSUE THREAD

**Issue by webczat** [aspnet/AspNetCore#14268]
I noticed that asp .net core does not support basic or digest authentication, and at least for Basic it seems to be by design.
However note that there are some scenarios where there is a need for it, for example because the client software used to access the app does not support any other method. Also these are standardized.
So what should we do in case we need to use basic or digest authentication? Say I am creating a git repository server that requires authentication? Is the solution to use third party addons or to write our own auth handlers?

**Comment by blowdart** [comment]
Either 3rd party ones, or write your own. It's not something we want to provide or support.

**Comment by webczat** [comment]
well just not quite understood why to make that path more difficult by not supporting it out of the box. Especially digest auth. I understand the motivation behind not recommending it, but not quite behind just outright refusing to support it even with a big warning. If someone needs it he will definitely provide it one way or another anyway.

**Comment by blowdart** [comment]
We have limited resources, and securing those auth types would simply take too much time better served on other features.

**Comment by webczat** [comment]
Does it require so much efford? basic is insecure always, use ssl. :) over basic, if you really need it. not sure how much efford you need to secure the normally insecure Basic.

**Comment by blowdart** [comment]
There's time in code, testing, security reviewing and documentation. Things like certificate and kerberos authentication take higher priority. Given there are community implementations this isn't something we feel is necessary for us to implement and support.

**Comment by webczat** [comment]
well, still these auth methods are also way simpler than both of them. Somehow it feels weird that the most basic as in, standardized and widely supported auth methods are the only ones not supported here. although it is mostly esthetic argument or something like this... or something about having to look for third party libraries for such stuff. But okay, understood.

**Comment by blowdart** [comment]
It's not the simplicity it's the support cost with the potential insecurity. I'm afraid third party packages are your only option, heck I even wrote one myself.
