### ISSUE TITLE
dotnet publish (3.0)

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#14262]
_From @zygimantas on Monday, September 23, 2019 5:46:20 PM_

[Enter feedback here]

.NET 3.0 breaking change - I had to change after upgrade from 2.2 to 3.0:

`dotnet publish --configuration=Release --no-restore --output=../../dist src/Website`

to

`dotnet publish --configuration=Release --no-restore --output=dist src/Website`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

_Copied from original issue: aspnet/AspNetCore.Docs#14494_

**Comment by pranavkm** [comment]
_From @Rick-Anderson on Monday, September 23, 2019 5:50:31 PM_

@pranavkm  who can review `dotnet publish --configuration=Release --no-restore --output=dist src/Website`

**Comment by pranavkm** [comment]
_From @zygimantas on Monday, September 23, 2019 5:55:09 PM_

Solution structure is:

```console
/src/Website/Website.csproj
App.sln
```

**Comment by pranavkm** [comment]
_From @zygimantas on Monday, September 23, 2019 5:56:23 PM_

Error in 3.0-alpine docker container was:

> COPY failed: stat /var/lib/docker/overlay2/e8eea87e7e5692f90bc8ae70e3cd6347a75dada2390362a1f1241445aab520be/merged/app/dist: no such file or directory

**Comment by pranavkm** [comment]
@vijayrkn does this seem familiar?

**Comment by vijayrkn** [comment]
No. This is just plain 'dotnet publish'. 

Adding @nguerrera

**Comment by zygimantas** [comment]
Probably it's unrelated, but I use 3.0-alpine SDK image, but I haven't upgraded the code yet, so `        <TargetFramework>netcoreapp2.2</TargetFramework>` is still in csproj

**Comment by nguerrera** [comment]
This was an intentional change and should be documented as such. 

There was some discussion of including it in docs/release notes on https://github.com/dotnet/cli/issues/4765, but seems not to have happened. It has been this way in every 3.0 preview.

I believe this would best be tracked as a docs issue. cc @kathleendollard @livarcocc

**Comment by mkArtakMSFT** [comment]
This issue was moved to dotnet/cli#12696
