### ISSUE TITLE
Add pathbase for blazor publish

### ISSUE THREAD

**Issue by chicagoairmailcc** [aspnet/AspNetCore#14264]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

I am trying to build sokcho.gitlab.io so I can serve it on my own machine in a sub dir. 

It isn't immediately obvious how I can do --pathbase 

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

I would like to be able to --pathbase in dotnet publish like I can with dotnet run 

### Additional context

Thank you for reading. 👋

**Comment by javiercn** [comment]
I believe you are talking about blazor wasm standalone. What are you trying to accomplish with `--pathbase`?

You shouldn't need that on a published app so long as you set the `<base href="..." />` tag in the head of your document correctly for your deployment.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
