### ISSUE TITLE
Rename support for Razor C#

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#14278]
Edit: This includes both local and global rename support for Razor C#

This will involve attaching to the rename provider support, forwarding requests to the C# or HTML virtual document and displaying the result.

To make this work more than just locally it depends on https://github.com/aspnet/Razor.VSCode/issues/61

**Comment by ajaybhargavb** [comment]
https://github.com/aspnet/AspNetCore-Tooling/pull/1336
