### ISSUE TITLE
Static URL picker for HTML elements

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#14272]
Right now the default HTML static URL picker resolves to the entire project. This means it prompts you for files such as `Index.cs`. We'll need to isolate the picker to the `wwwroot` folder if it exists.

**Comment by NTaylorMullen** [comment]
Thought: It's possible this will be handled by WTE.

@jodavis / @ToddGrun / @alexgav is your static URL picker piece Razor editor specific or also on in HTML editors?

**Comment by alexgav** [comment]
It's just HTML editor. I think Bill made some fixes recently that actually should've accounted for wwwroot folder. Did you guy try this in recent builds? Ping me offline and we can chat.

**Comment by NTaylorMullen** [comment]
> It's just HTML editor

Was just trying to see if we would need to re-implement that on the VS front when everything is powered by LSP. Sounds like we wont. Hooray!
