### ISSUE TITLE
Find references for C# + Html

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#14276]
This will involve attaching to the executeReferenceProvider provider support, forwarding C# requests to the virtual document, if the resulting location is in the same document then remap to host document.

**Comment by ryanbrandenburg** [comment]
#Stolen

**Comment by NTaylorMullen** [comment]
> #Stolen

Dopeness!!

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg marking this as working so no one else steals 😉

**Comment by ajaybhargavb** [comment]
@ryanbrandenburg close?
