### ISSUE TITLE
GoToImplementation for C# + Html

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#14275]
This will involve attaching to the go to implementation support, forwarding C# requests to the virtual document, if the resulting location is in the same document then remap to host document.

**Comment by NTaylorMullen** [comment]
Verify go to definition works if the class is in the same file.

**Comment by NTaylorMullen** [comment]
When you get this ^ far talk to me about hover work, i did the map ranges bit.

**Comment by ryanbrandenburg** [comment]
There's no "dropdown" for this, you have to do `Ctrl+F12`
