### ISSUE TITLE
Enable Omnisharp to invoke Razor language server for refactoring events

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#14282]
Right now if a VSCode IDE edit is requested on one of our virtual documents the IDE fails to perform the edit. From some offline talks we can enable this functionality by creating a virtual file provider.

Here's an example: https://github.com/Microsoft/vscode-extension-samples/tree/master/fsprovider-sample

**Comment by ajaybhargavb** [comment]
After a meeting with the Omnisharp team, we've decided to update Omnisharp to provide Razor with an interface that will be called during various refactoring event on .cs files. This will enable us to fully support features like renames, go-to implementation, find all references etc.

**Comment by ajaybhargavb** [comment]
Fixed by https://github.com/OmniSharp/omnisharp-vscode/pull/3427/ and https://github.com/aspnet/AspNetCore-Tooling/pull/1424
