### ISSUE TITLE
Strange method intellisense in Blazor app

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#14302]
_From @danroth27 on November 14, 2018 7:4_

![image](https://user-images.githubusercontent.com/1874516/48465643-675d1980-e798-11e8-973c-cf10758d2913.png)
![image](https://user-images.githubusercontent.com/1874516/48465671-7cd24380-e798-11e8-97b4-ba415f383657.png)

The type name for the Blazor component should just be `Index`.

_Copied from original issue: aspnet/Blazor#1676_

**Comment by NTaylorMullen** [comment]
Fixed in latest release.
