### ISSUE TITLE
 Remote - Containers : No HTML or RAZOR Intellisense in .cshtml file for ASP.NET Core projects

### ISSUE THREAD

**Issue by HoTKreeZy** [aspnet/AspNetCore#14331]
## Is this a Bug or Feature request?:
Feature request

## Environment data
- `dotnet --info` output: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App] 
```
- C# Extension version: 1.21.0
- VSCode Version: 1.37.0
- Local OS Version: macOs Mojave v10.14.6
- Remote OS Version: Linux debian 9
- Remote Extension/Connection Type: Docker

## Steps to reproduce
1. Create a folder on my local machine that will contains my project
2. Open this folder inside vs code
3. Use the remote-container extension : 
    - Add Development Configuration file : `C# (.NET Core Latest)`( mcr.microsoft.com/dotnet/core/sdk:latest )
    - Reopen folder in container
4. Create project inside the container : dotnet new mvc
5. Open any CS file and wait for Omnisharp installation
6. Open any CSHTML file and try to write some html but got no intellisense for both html or razor syntax

## Description of the problem: 
No intellisense inside `cshtml` files

### Expected behavior:
Want to have html and razor intellisense 

### Actual behavior:
Nothing

Edit: I was not sure so i tried with a simple Dotnet Core Razor WebApp and YES, it's not working.

**Comment by MRosari0** [comment]
I'm not able to get any Intellisense on .cshtml files. For HTML, CSS, and JS,  I get syntax highlighting but no intellisense. For Razor, it's shows default text color.

 Auto-detect has the language set to aspnetcorerazor and I tried switching to HTML (C#) and that didn't change anything.

**VSCode info**

Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Extensions related**

Name: C#
Id: ms-vscode.csharp
Description: C# for Visual Studio Code (powered by OmniSharp).
Version: 1.21.3
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

Name: ASP.NET Helper
Id: schneiderpat.aspnet-helper
Description: "Little helper to develop faster ASP.NET MVC apps"
Version: 0.6.4
Publisher: schneiderpat
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=schneiderpat.aspnet-helper

**Comment by HoTKreeZy** [comment]
I've changed a bit the title cause it's also not working for a 'simple' Dotnet Core Razor WebApp. So now, the issue title is more globaly.

**Comment by ofrades** [comment]
> More or less the same here. New ASP MVC project (net core 3 preview 8), remote Ubuntu 18.04 via SSH:
> 
> * `dotnet --info`:
> 
> ```
> .NET Core SDK (reflecting any global.json):
>  Version:   3.0.100-preview8-013656
>  Commit:    8bf06ffc8d
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  18.04
>  OS Platform: Linux
>  RID:         ubuntu.18.04-x64
>  Base Path:   /snap/dotnet-sdk/45/sdk/3.0.100-preview8-013656/
> 
> Host (useful for support):
>   Version: 3.0.0-preview8-28405-07
>   Commit:  d01b2fb7bc
> 
> .NET Core SDKs installed:
>   3.0.100-preview8-013656 [/snap/dotnet-sdk/45/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/snap/dotnet-sdk/45/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/snap/dotnet-sdk/45/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
> ```
> 
> * VSCode 1.37.1
> * C# Extension: 1.21.0
> * Local OS: Windows 10 1809
> * Remote OS: Ubuntu 18.04 64 bits via SSH
> 
> When I open a `.cshtml` file, I got no Intellisense. The same is for `.razor` files for a Blazor project. What I've observed is that the log of the Razor Log on VSCode shows a crash:
> 
> ```
> --------------------------------------------------------------------------------
> Razor.VSCode version 1.0.0-alpha3-20190627.5
> --------------------------------------------------------------------------------
> Razor's trace level is currently set to 'Off'
>  - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
>  - To report issues invoke the 'Report a Razor issue' command via the command palette.
> -----------------------------------------------------------------------------------------------------------------------------
> 
> [Client - 5:59:20 PM] (Error) Failed to read project config at location /home/peluko/devel/asptest1/obj/Debug/netcoreapp3.0/project.razor.json.
> Unexpected end of JSON input
> Stack Trace:
> SyntaxError: Unexpected end of JSON input
> 	at JSON.parse (<anonymous>)
> 	at t.RazorProjectManager.getProjectConfiguration (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:167240)
> 	at t.RazorProjectManager.updateProjectConfiguration (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:165797)
> 	at t.RazorProjectManager.<anonymous> (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:165489)
> 	at Generator.next (<anonymous>)
> 	at /home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:164457
> 	at new Promise (<anonymous>)
> 	at r (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:164234)
> 	at i.onDidCreate.e (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:165444)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:549:862)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at u.$onFileEvent (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:550:901)
> 	at d._doInvokeHandler (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:668:1006)
> 	at d._invokeHandler (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:668:698)
> 	at d._receiveRequest (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:667:346)
> 	at d._receiveOneMessage (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:666:141)
> 	at _protocol.onMessage.e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:664:400)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at a (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:179:815)
> 	at e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:179:861)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at e.onMessage.e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:775:104)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at a (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:179:815)
> 	at e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:179:861)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at y._receiveMessage (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:188:834)
> 	at _socketDisposables.push._socketReader.onMessage.e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:186:116)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at f.acceptChunk (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:182:588)
> 	at _register._socket.onData.e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:181:919)
> 	at Socket.t (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:190:329)
> 	at Socket.emit (events.js:182:13)
> 	at addChunk (_stream_readable.js:283:12)
> 	at readableAddChunk (_stream_readable.js:264:11)
> 	at Socket.Readable.push (_stream_readable.js:219:10)
> 	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> [Client - 5:59:27 PM] (Error) Failed to read project config at location /home/peluko/devel/asptest1/obj/Debug/netcoreapp3.0/project.razor.json.
> Unexpected end of JSON input
> Stack Trace:
> SyntaxError: Unexpected end of JSON input
> 	at JSON.parse (<anonymous>)
> 	at t.RazorProjectManager.getProjectConfiguration (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:167240)
> 	at t.RazorProjectManager.updateProjectConfiguration (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:165797)
> 	at t.RazorProjectManager.<anonymous> (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:165683)
> 	at Generator.next (<anonymous>)
> 	at /home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:164457
> 	at new Promise (<anonymous>)
> 	at r (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:164234)
> 	at i.onDidChange.e (/home/peluko/.vscode-server/extensions/ms-vscode.csharp-1.21.0/dist/extension.js:80:165638)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:549:955)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at u.$onFileEvent (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:550:901)
> 	at d._doInvokeHandler (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:668:1006)
> 	at d._invokeHandler (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:668:698)
> 	at d._receiveRequest (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:667:346)
> 	at d._receiveOneMessage (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:666:141)
> 	at _protocol.onMessage.e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:664:400)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at a (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:179:815)
> 	at e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:179:861)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at e.onMessage.e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:775:104)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at a (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:179:815)
> 	at e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:179:861)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at y._receiveMessage (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:188:834)
> 	at _socketDisposables.push._socketReader.onMessage.e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:186:116)
> 	at u.fire (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:50:207)
> 	at f.acceptChunk (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:182:588)
> 	at _register._socket.onData.e (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:181:919)
> 	at Socket.t (/home/peluko/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/out/vs/server/remoteExtensionHostProcess.js:190:329)
> 	at Socket.emit (events.js:182:13)
> 	at addChunk (_stream_readable.js:283:12)
> 	at readableAddChunk (_stream_readable.js:264:11)
> 	at Socket.Readable.push (_stream_readable.js:219:10)
> 	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> ```
> 
> I've checked the `obj/Debug/netcoreapp3.0/project.razor.json` file and it seems correct. The only peculiarity is that it shows some values containing a `\n` (`"Documentation"` keys). Attached is the full file.
> [project.razor.json.zip](https://github.com/aspnet/Razor.VSCode/files/3510342/project.razor.json.zip)

I have the same error in a macos.

**Comment by NTaylorMullen** [comment]
Hey all, thanks for the reports! We've yet to add full support for remote development but are hoping to get it done soon!

**Comment by ajaybhargavb** [comment]
One of the blockers for this was a bug on vscode https://github.com/microsoft/vscode/issues/86901 which will be fixed in the next release. I'm still investigating if there is any other work that needs to be done here.

**Comment by pheuter** [comment]
@ajaybhargavb Glad to hear that bug is getting squashed. There might be other work that needs to be done because even when the language is properly set it `aspnetcorerazor` instead of `Razor`, the syntax highlighting is still a bit off.

Take this razor component for example:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/92698/70851461-6c8d0c00-1e63-11ea-9ee8-9c28e26e4858.png">

Notice the closing `</p>` on line 10, or the C# code on lines 15 and 17.

Btw I generated the example above inside a vscode project that's not running inside remote containers, so Omnisharp used the host mono framework and had no issues switching to `aspnetcorerazor`:

```
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.3 - "/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.3 - "/Users/mark/.vscode/extensions/ms-vscode.csharp-1.21.8/.omnisharp/1.34.8/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.3 - "/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /Users/mark/.vscode/extensions/ms-vscode.csharp-1.21.8/.omnisharp/1.34.8/omnisharp/.msbuild/Current/Bin/Roslyn
```

**Comment by ajaybhargavb** [comment]
@pheuter, what you are referring to is already being worked on. Tracked here https://github.com/aspnet/AspNetCore/issues/14287.

**Comment by pheuter** [comment]
Got it, thanks for clarifying.

**Comment by ajaybhargavb** [comment]
This is now works with the latest VSCode-Insiders and the latest C# extension. 🎉
