### ISSUE TITLE
ArgumentException when typing Blazor directive attribute

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14338]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/627428/argumentexception-when-typing-blazor-directive-att.html)._

---
Repro steps
- Install .NET Core 3.0 Preview 7 SDK as described here: https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md
- Create a new ASP.NET Core Web App -&gt; Blazor Server App (or Blazor (server-side) app)
- Open *Counter.razor* and remove the `@onclick` attribute
- Try to add back the attribute: `@onclick=&quot;IncrementCount&quot;`

Actual result:

```
System.ArgumentException: An entry with the same key already exists. at System.Collections.Specialized.ListDictionary.Add(Object key, Object value) at System.Collections.Specialized.HybridDictionary.Add(Object key, Object value) at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(Object key , Object property) at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource. &lt;GetCompletionContextAsync&gt;d__22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Text.Utilities.GuardedOperations. &lt;CallExtensionPointAsync&gt;d__36`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Note: this doesn't reproduce reliably

---
#### Visual Studio Feedback System on 7/1/2019, 02:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/4/2019, 01:07 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
@danroth27 @javiercn @mkArtakMSFT are you able to still reproduce this (even if it's unreliable)? I just tried several different ways without luck on VSMaster

**Comment by mkArtakMSFT** [comment]
Thanks @NTaylorMullen 
Closing this issue as no repro. If anyone runs into the same issue with the 3.0 release bits, we'll look into this further.
