### ISSUE TITLE
Omnisharp plugin vs standalone server questions

### ISSUE THREAD

**Issue by jpfeiffer16** [aspnet/AspNetCore#14332]
I have a few questions about the Razor Language service. By looking at the contribution guide in ASP.net core repo that is linked, I think this is the best place for it. My apologies if that is not the case.

Firstly, awesome project. Glad I could find this as it will fill my needs nicely I think. I just have a few questions to get myself oriented. 

I'm attempting to add this into my vim setup via an lsp client. I'm a little unclear as to what the difference between the standalone server and the omnisharp plugin are or what the divisions of responsibility are there. Are they interchangeable or should I use one or the other for an lsp client?

Thanks again for all the work on this project and I hope I didn't miss anything in the docs.

**Comment by NTaylorMullen** [comment]
Closing this for now since question has been answered.
