### ISSUE TITLE
Provide a pattern for initialization code in Blazor WASM

### ISSUE THREAD

**Issue by chris579** [aspnet/AspNetCore#14340]
When developing a library for ASP.NET Core that needs to use `IApplicationBuilder` I can reference `Microsoft.AspNetCore.Http.Abstractions`.

When I want to use `IComponentsApplicationBuilder` I need to add an reference to `Microsoft.AspNetCore.Blazor` which not just contains the abstractions. 

Having an abstraction package for Blazor like `Microsoft.AspNetCore.Blazor.Abstractions` would allow to just reference the abstractions instead of needing to add a reference to blazor itself.

**Comment by javiercn** [comment]
@chris579 Thanks for contacting us.

Can you give us more details on why is it problematic to reference `Microsoft.AspNetCore.Blazor` and what you are trying to accomplish? 

This is an area that is likely to change in the future. What functionality of IComponentsApplicationBuilder are you trying to get access to?

**Comment by chris579** [comment]
I find it inconvenient to reference Blazor as a whole (especially because it will heavily change in the future). When there are new Blazor versions introducing breaking changes (that are not affecting my library) I would need to update my package even though it does not make use of Blazor at all. Plus, if creating a library that does target both Blazor and Blazor Serverside I would need to reference Blazor as a whole too. That means that if somebody uses Blazor Serverside and installs my library he will also install blazor, no matter if he even uses it.

**Comment by rynowak** [comment]
> Plus, if creating a library that does target both Blazor and Blazor Serverside I would need to reference Blazor as a whole too. 

Our recommendation would be to reference `Microsoft.AspNetCore.Components` and `Microsoft.AspNetCore.Components.Web` if you're building a library. Can you be specific about what else you need?

**Comment by chris579** [comment]
`IComponentsApplicationBuilder` is neither part of `Microsoft.AspNetCore.Components` nor `Microsoft.AspNetCore.Components.Web`.

**Comment by rynowak** [comment]
I think we need to know a little bit more about what you're doing then. Using `IComponentApplicationBuilder` isn't something I anticipated from a library. Is there a publicly accessible link I can look at?

**Comment by chris579** [comment]
I removed the relevant code from my library some days ago because I restructured it a bit. However, this kind of describes what I did:

```csharp
public class MyInitService
{
    public void DoInit() {}
}

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddTransient<MyInitService>();
    }

    public void Configure(IComponentsApplicationBuilder app)
    {
        app.UseInit();
        app.AddComponent<App>("app");
    }
}

public static class ComponentApplicationBuilderExtensions
{
    public static IComponentsApplicationBuilder UseInit(this IComponentsApplicationBuilder componentsApplicationBuilder)
    {
        componentsApplicationBuilder.Services.GetRequiredService<MyInitService>().DoInit();

        return componentsApplicationBuilder;
    }
}
```

For me, the purpose of the `Configure` method is similar to the one from AspNetCore server.

**Comment by rynowak** [comment]
Thanks @chris579 - we'll look for a solution to this kind of thing as part of the client release.

**Comment by mkArtakMSFT** [comment]
We will tackle this as part of https://github.com/aspnet/AspNetCore/issues/16874
