### ISSUE TITLE
Add HubName to HubInvocationContext

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#14344]
[HubInvocationContext](https://github.com/aspnet/AspNetCore/blob/15e408d4afbf4c87478f2b447c9751e23d28e759/src/SignalR/server/Core/src/HubInvocationContext.cs) already has a `HubMethodName` property. It only makes sense for it to have a `HubName` property as well.

**Comment by anurse** [comment]
It sure does!

**Comment by anurse** [comment]
We should strongly consider doing this in a non-breaking way by **adding** a constructor overload that takes `HubName`.

**Comment by anurse** [comment]
Or we can consider not adding more constructors and make the property interally settable

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/aspnet/AspNetCore/pull/14459
