### ISSUE TITLE
Datetime Conversions + ToList() Issues 

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14347]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/413237/datetime-conversions-tolist-issues.html)._

---
I have a MVC website (Data Base First) and I have many SQL procedures that I call from my Website. Yesterday I added a new one and the problems started, but after an entire day of Google searches and work nothing seems to work I simply couldn’t add &quot;ToList()&quot; to the end of the calling of my SQL procedure.

So my first code was like this:

var negatives = cxt.GetNegativeQuantities(Convert.ToDateTime(ViewBag.ExcelDate, cultureInfo), 2).ToList();

The first error that I got was:

&quot;.... does not contain a definition for 'ToList'&quot;

Then when I removed the &quot;ToList()&quot; I had the warning and then an error:

Warning: 
&quot;The result of a query cannot be enumerated more than once&quot;

Error:
&quot;Cannot implicitly convert type 'System.Data.Entity.Core.Objects.ObjectResult&lt;XPTO&gt;' to 'System.Collections.Generic.List&lt;XPTO&gt;'&quot;

Until I found out that for some reason, the problem was on the first input:

Convert.ToDateTime(ViewBag.ExcelDate, cultureInfo)

Then I tried changed the code to this:

DateTime dateToTest = Convert.ToDateTime(ViewBag.ExcelDate, cultureInfo);

var negatives = cxt.GetNegativeQuantities(dateToTest, 2).ToList();

And now everything is working ok. 
Why this error occur if I just simply try to put the “Convert” or even a “cast” to “Datetime” inside the call of the procedure? 
Remember that in my case the call of the procedure is auto-generated.

        public virtual ObjectResult&lt;NegativeQuantities&gt; GetNegativeQuantities(Nullable&lt;System.DateTime&gt; date, Nullable&lt;int&gt; query)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter(&quot;Date&quot;, date) :
                new ObjectParameter(&quot;Date&quot;, typeof(System.DateTime));
    
            var queryParameter = query.HasValue ?
                new ObjectParameter(&quot;query&quot;, query) :
                new ObjectParameter(&quot;query&quot;, typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction&lt;NegativeQuantities&gt;(&quot;GetNegativeQuantities&quot;, dateParameter, queryParameter);
        }

---
#### Bala Chirtsabesan [MSFT] on 2/6/2019, 11:56 PM: 

<p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET. Our focus at the moment is on ASP.NET Core. This particular issue looks like a question about your application specific scenario. We recommend using [StackOverflow](https://www.stackoverflow.com) using the **asp.net-mvc** tag for similar questions.
