### ISSUE TITLE
Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets ASP.NET Core 3.0

### ISSUE THREAD

**Issue by HashemGo** [aspnet/AspNetCore#14353]
version of ASP.NET Core '3.0'
i tried install Microsoft.AspNetCore" Version="2.2.0" in a class library core 3.0
rebulid successfully but this warning still exist .. i tried restart visual studio 16.3.0 warning didn't disappear.

![Capture](https://user-images.githubusercontent.com/42634137/65478542-6dc52300-de8a-11e9-9545-b5278a3e74b9.PNG)

i included this class library to my project , i get one error 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The project ... must provide a value for Configuration.	C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets	79	

in version of ASP.NET Core '2.2' everything working fine without this error

**Comment by javiercn** [comment]
@HashemGo Thanks for contacting us.

Why are you trying to install Microsoft.AspNetCore 2.2 in a netcoreapp3.0 class library? That might work, but I would suggest you use ASP.NET Core 3.0 and use a RazorCassLibrary if you are trying to build a library with UI components or add a framework reference to asp.net core.

@danroth27 Do we have docs for this?

**Comment by mkArtakMSFT** [comment]
To add to this, the Microsoft.AspNetCore.Razor.Design package is supposed to be removed from a 3.0 targeting project, as is stated https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#remove-obsolete-package-references.

Please follow the migration guide to 3.0 to help you out with migration. If you happen to face any other issues, please reach out to us.

**Comment by HashemGo** [comment]
@javiercn Thanks for reply

i used Microsoft.AspNetCore 2.2 to call 
 new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json")
                    .Build();
in my class library, because i used code first for my database, so this class library i used it for many projects in my my solution
i wish used Razor soon

thanks

**Comment by HashemGo** [comment]
@mkArtakMSFT 
thanks that is helpful
i used this
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

now everything is ok ,thanks
