### ISSUE TITLE
--grpc_out: protoc-gen-grpc: The system cannot find the file specified

### ISSUE THREAD

**Issue by stulzq** [aspnet/AspNetCore#14351]
I created a gRPC Service project using Visual Studio 2019（.NET Core 3.0 Release）, but I can't compile it.
![image](https://user-images.githubusercontent.com/13200155/65478093-f2c83080-deba-11e9-8579-0c68977f9f9f.png)
The "系统找不到指定的路径" means "The system cannot find the file specified."

When I send this project to my colleagues, he can compile successfully. How can I solve this problem?

Visual Studio 16.3.0
.NET Core 3.0.100
![image](https://user-images.githubusercontent.com/13200155/65478117-070c2d80-debb-11e9-913f-0b79a84c4043.png)

Windows 10

**Comment by davidfowl** [comment]
What does your project path look like

**Comment by stulzq** [comment]
I've solved this problem. I just change the name of my WIndows user directory to English.

**Comment by davidfowl** [comment]
cc @JamesNK @shirhatti

**Comment by stulzq** [comment]
My Windows User Directory used to be Chinese characters : "c:\users\李志强", I changed it to “c":\users\lzq”

**Comment by jtattermusch** [comment]
This might have well been instance of https://github.com/grpc/grpc/issues/17995.
