### ISSUE TITLE
ASP.NET Core 2.2 app stops working after nuget update

### ISSUE THREAD

**Issue by z-eh** [aspnet/AspNetCore#14362]
I updated my nuget packages for an ASP.NET Core 2.2 application and now it stopped working anymore.

In the startup.cs the following line throwing exception:
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

The exception is:
System.MissingMethodException: 'Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthorizationServiceCollectionExtensions.AddAuthorization(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.'

**Comment by javiercn** [comment]
@z-eh Thanks for contacting us.

You likely have a dependency mismatch in your project. 

Does compiling the project succeed?

Are you using `<PackageReference Include="Microsoft.AspNetCore.App" />` in your project?

@danroth27 Do we have docs about how to migrate?

**Comment by mkArtakMSFT** [comment]
@z-eh please follow the 2.1 to 2.2 migration guide: https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-3.0&tabs=visual-studio
If there are still issues after following the guide, feel free to reopen this issue.
