### ISSUE TITLE
NavigationManager not encoding url

### ISSUE THREAD

**Issue by chinookproject** [aspnet/AspNetCore#14366]
Normally when I navigate to a URL inside my app I would use something like `UriHelper` to encode the URL. But this has been replaced by the `NavigationManager`.

I am wondering if the `NavigationManager.NavigateTo` should do a `UrlEncode`? 

The following example code works fine:

```
NavigationManager.NavigateTo("/?search=some criteria | other criteria");
```
This will let the application navigate properly. The URL that comes out in the browser will look like this:

```
/?search=some%20criteria%20|%20other%20criteria
```

But, when I copy that URL from the browser and when I paste it into a new window, I then get the following error:

```
[2019-09-24T09:32:14.420Z] Error: The uris provided are invalid.
e.log @ blazor.server.js:15
blazor.server.js:1 [2019-09-24T09:32:14.421Z] Information: Connection disconnected.
blazor.server.js:1 Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.
    at e.connectionClosed (blazor.server.js:1)
    at e.connection.onclose (blazor.server.js:1)
    at e.stopConnection (blazor.server.js:1)
    at e.transport.onclose (blazor.server.js:1)
    at e.close (blazor.server.js:1)
    at e.stop (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:1)
    at blazor.server.js:1
    at Object.next (blazor.server.js:1)
    at s (blazor.server.js:1)
```

This is because the piped character is in the URL. This only fails when pasting the URL directly into the browser.

The same thing happends for a few other characters like curly brackets.

I am not sure if this is a bug? Or am I responsible to do a url encoding before passing the URL to the `NavigateTo`  method?

If so, what should I use, siince the `UriHelper` has been replaced?

Right now the behaviour is not very consistent when navigation through codes works fine, untill you copy paste the URL in the browser.

**Comment by javiercn** [comment]
@chinookproject Thanks for contacting us.

Navigation manager's responsibility is to perform browser navigation. If you have urls with characters that require encoding you should be responsible for encoding those characters. Navigation manager can't know if the url you gave it was already encoded or not, so if we were to do this, we could cause double-encoding issues.

What I'm trying to say is that NavigationManager can't know in the general case whether it needs to encode or not a given url, so it is up to the developer to do so.

That said, maybe this is something we can provide an overload for. @danroth27 @rynowak thoughts?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chinookproject.
This is not something we plan to expose additional API for. You can use `WebUtility.UrlDecode` method you can use to decode it yourself.
