### ISSUE TITLE
Question：Does IApplicationModelConvention.Apply execute only once?

### ISSUE THREAD

**Issue by ZhiqiangTao** [aspnet/AspNetCore#14364]
related post: [https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.1](url)

does the IApplicationModelConvention.Apply() execute only once by design when the app is listening for new requests?

**Comment by javiercn** [comment]
@ZhiqiangTao Thanks for contacting us.

Application model executes once every time the collection of action descriptors needs to be updated.

@rynowak can confirm.

**Comment by ZhiqiangTao** [comment]
@javiercn 
I found a phenomenon that had been bothering me for a long time, I'm not sure if it is by design

step1: create a new asp.net core mvc 2.1 project
step2: create class as below
`
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Exceptionless;
using Exceptionless.Logging;

namespace Test_IApplicationModelConvention
{
    public class MyApplicationModelConvention : IApplicationModelConvention
    {
        public void Apply(ApplicationModel application)
        {
            //mock long work
            Thread.Sleep(30 * 1000);

            Exceptionless.ExceptionlessClient.Default.CreateLog($"{DateTime.Now} hit....({Guid.NewGuid().ToString()})", LogLevel.Debug).Submit();
        }
    }
}

`
step3: add my convention in ConfigureServices

`
services.AddMvc(options =>
            {
                options.Conventions.Add(new MyApplicationModelConvention());
            }).SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
`

step4(key point):run the web app, and open **many** tab windows in the browser, and each window is located the same url "http://localhost:5000" (you can also other diff urls).

step5: in my log system, there are more than one log( hit ....) appeared after serval seconds

so, as you said above, "Application model executes once every time the collection of action descriptors needs to be updated."
i'm not sure if this phenomenon(first request after app run up) is right or by design, actually, only one log **I expect** in above steps

**Comment by ZhiqiangTao** [comment]
![image](https://user-images.githubusercontent.com/16182251/65590763-e5479f00-dfbd-11e9-8c91-00e181989987.png)

**Comment by ZhiqiangTao** [comment]
my debug trace：
![image](https://user-images.githubusercontent.com/16182251/65590939-35befc80-dfbe-11e9-8ac3-60e5ae8d794f.png)

**Comment by rynowak** [comment]
I wouldn't be surprised if this happens using the old routing system. The new routing system (default in 3.0) has a strong guarantee about this.

**Comment by ZhiqiangTao** [comment]
@rynowak 3q :)
