### ISSUE TITLE
ASP.Net core redirect to an action which return FileStreamResult

### ISSUE THREAD

**Issue by ioantoader** [aspnet/AspNetCore#14375]
I have to actions in a controller:
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {

        [HttpGet("redirect1")]
        public IActionResult Redirect1()
        {
            var r = RedirectToAction(nameof(GetStream));
            return r;
        }

        [HttpGet("stream")]
        public IActionResult GetStream()
        {
            var ms = new MemoryStream(Encoding.UTF8.GetBytes("Hello Word"));
            return File(ms, "application/octet-stream", "test.xyz", true);            
        }
    }

When I typed https://localhost:44352/api/values/redirect1, the save as dialog is open for download but the url in browser is not changed to  https://localhost:44352/api/values/stream. Is a way to change also the url. in case the GetStream action return a json the url is changed to https://localhost:44352/api/values/stream. How is possible also to change the url in case I return FileStreamResult.

Thanks
Ioan Toader

The sample project
[TestDocRedirect.zip](https://github.com/aspnet/AspNetCore/files/3647434/TestDocRedirect.zip)

**Comment by javiercn** [comment]
@ioantoader thanks for contacting us.

I don't think that's possible unless you return a 200 from the redirect and then trigger the download automatically.

This is more of a question about HTTP than ASP.NET Core specifically. I would suggest you post a question with your scenario in stackoverflow.
