### ISSUE TITLE
mvc and razor pages

### ISSUE THREAD

**Issue by azizkazdal** [aspnet/AspNetCore#14377]
Is some thing wrong with these code ? I can not access the controller using javascript.getting 404.  Need to use at the same time razor pages and mvc

        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddControllersWithViews();
            services.AddRazorPages();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");

            });
        }

**Comment by javiercn** [comment]
@azizkazdal Thanks for contacting us.

You need to call `services.AddControllers()` and `endpoints.MapControllers()` if you are using attribute routing.

**Comment by mkArtakMSFT** [comment]
@azizkazdal can you please confirm this fixes your issue?

**Comment by azizkazdal** [comment]
well,
            services.AddControllers();
            services.AddRazorPages(opt =>
            {
                opt.Conventions.AuthorizeAreaFolder("Corporate", "/");
                opt.Conventions.AuthorizeAreaFolder("Customer", "/");
                opt.Conventions.AuthorizeAreaFolder("Inventory", "/");
                opt.Conventions.AuthorizeAreaFolder("Item", "/");
                opt.Conventions.AuthorizeAreaFolder("Service", "/");
                opt.Conventions.AuthorizeAreaFolder("ServicePoint", "/");
                opt.Conventions.AuthorizeAreaFolder("User", "/");
                opt.Conventions.AuthorizeFolder("/");
                opt.Conventions.AllowAnonymousToPage("/Login");
            });

            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapRazorPages();
            });

these are my codes and still can not access to below URL
http://localhost:9011/Dashboards/GetAssetCategorySummaryAsync 404 (Not Found)

and controller

public class DashboardsController : BaseController, IDashboardsController
{
	[HttpGet]
	 public async Task<JsonResult> GetAssetCategorySummaryAsync(){
		-------
	}
}

**Comment by javiercn** [comment]
Seems like you are not using attribute Routing in your controller. You need to keep endpoints.MapControllerRoute in that case.

**Comment by javiercn** [comment]
If that doesn’t fix your issue, can you provide a link to a GitHub repository with a minimal repro project that showcases the issue so that we can investigate?

**Comment by azizkazdal** [comment]
ok ı have made some changes as below.

```
[ApiController]
[Route("[controller]")]
public class DashboardsController : BaseController, IDashboardsController
{
	[HttpGet("[action]")]
	 public async Task<JsonResult> GetAssetCategorySummaryAsync(){
		-------
	}
}
```

```
[ApiController]
[Route("[controller]")]
public class BaseController : Controller
{
 -----
}
```

above code does not work but below code work fine

```
    [ApiController]
    [Route("[controller]")]
    public class MevTestController : Controller
    {
        [HttpGet("[action]")]
        public JsonResult GetTestMessage()
        {
            return Json("asdsad");
        }
    }
```

only differences between codes are **BaseController** class.
I will retry it againg tomorrow If I could not manage to done it I will create a repo.

**Comment by pranavkm** [comment]
@azizkazdal you're likely running into this breaking change - https://github.com/aspnet/Announcements/issues/351.

**Comment by azizkazdal** [comment]
@pranavkm thank you. you saved me :)

**Comment by davidfowl** [comment]
```
app.UseAuthentication();
app.UseAuthorization();

app.UseRouting();
app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");

});
```

This should be:

```C#
app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");

});
```

**Comment by azizkazdal** [comment]
```
            services.AddControllers(opt => {
                opt.SuppressAsyncSuffixInActionNames = false;
            });
```

```
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });
```

this works. no need to change app.UseRouting() order. I am using both endpoints.MapControllers() and  endpoints.MapControllerRoute() because in some controller dont use attribute routing. just added **opt.SuppressAsyncSuffixInActionNames = false;** 

https://github.com/aspnet/Announcements/issues/351

**Comment by davidfowl** [comment]
> this works. no need to change app.UseRouting() order. I am using both endpoints.MapControllers() and endpoints.MapControllerRoute() because in some controller dont use attribute routing. just added opt.SuppressAsyncSuffixInActionNames = false;

If you want auth to work then you need to move that between UseRouting and UseEndpoints

**Comment by azizkazdal** [comment]
@davidfowl thanks :) did it.

**Comment by Ruard** [comment]
@davidfowl 

> If you want auth to work then you need to move that between UseRouting and UseEndpoints

That's not my experience, auth also works when placed before UseRouting. Why the need to place auth after UseRouting? Can you please explain what makes the difference or point me to a source?

**Comment by davidfowl** [comment]
A simplistic way to think about it

UseRouting() -> Will try to select a route to execute but doesn't actually execute the route. It will select the endpoint for the current request.

UseAuthentication() -> Populates the User (code that runs before this won't have a valid HttpContext.User property)

UseAuthorization() -> Will look at the populated user and the current endpoint to determine if an authorization policy needs to be applied.

UseEndpoints() -> Executes the current endpoint
