### ISSUE TITLE
Embedded views doesn't works after updating to .net core 3

### ISSUE THREAD

**Issue by geotinc** [aspnet/AspNetCore#14374]
In other to migrate from asp.net core 2.2 to asp.net core 3
I change the code for loading external views as the following :

```
services.Configure<MvcRazorRuntimeCompilationOptions>(options =>
            {
                options.FileProviders.Add(embeddedFileProvider);
            });
```

When running the project, I have the following error :
InvalidOperationException: The view 'Login' was not found. The following locations were searched: /Views/Account/Login.cshtml /Views/Shared/Login.cshtml /Pages/Shared/Login.cshtml

**Comment by javiercn** [comment]
@geotinc Thanks for contacting us.

Could you provide a link to a github repo with a small repro project and detailed repro steps so that we can investigate?

@pranavkm any idea?

**Comment by geotinc** [comment]
@javiercn I have push a sample here : https://github.com/geotinc/AspNetCore

Try to access /Test/Index => View not found

Thanks for helping

**Comment by geotinc** [comment]
Thanks adding **AddRazorRuntimeCompilation()** works in my sample but in my real app I have the following error, any aidea ?

![image](https://user-images.githubusercontent.com/20421571/65535269-5ecd8780-df01-11e9-84f4-c49b0fd9fe66.png)

Thanks

**Comment by taori** [comment]
#14359 has similar issues - perhaps this issue is not dependent on it being embedded views.

**Comment by taori** [comment]
@geotinc Have you tried adding your class library as a razor class library instead of making it a netcore app?

**Comment by geotinc** [comment]
@taori Yes, I try without success

**Comment by fpanaccia** [comment]
Hi, i have a library that transforms views to pdf, with the views in the fileprovider i have the same exception "Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll'", when using the "Physical" views i dont have the issue. I have tried some debugging, but the farthest i can go with out breaking was here 
`namespace Microsoft.AspNetCore.Mvc.Razor.Compilation`
`internal class DefaultRazorPageFactoryProvider : IRazorPageFactoryProvider`
`public RazorPageFactoryResult CreateFactory(string relativePath)`
`line 44 var viewDescriptor = compileTask.GetAwaiter().GetResult();`

The code is in this repo 

> https://github.com/fpanaccia/Wkhtmltopdf.NetCore.Example.git

And the branch

> feature/3.0

**Comment by javiercn** [comment]
@geotinc Seems like your project is not correctly setup.

Id recommend you follow the guidance from https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio

Is there any specific reason why you are trying to embed the pages in the assembly directly?

**Comment by javiercn** [comment]
@geotinc Our recommendation is that you use Razor Class Libraries instead of plain class libraries for razor, as they provide more features and a better experience.

If there's an scenario that you can't achieve with Razor Class Libraries feel free to open a new issue describing the requirement.

I'm closing this issue as there's nothing else for us to do here.

**Comment by fpanaccia** [comment]
@javiercn how would you solve my problem? https://github.com/aspnet/AspNetCore/issues/14374#issuecomment-534829990

I don't have any views in the library, but i need to process them dynamically

**Comment by javiercn** [comment]
@fpanaccia Could you please open a separate issue so that we can track and prioritize your issue appropriately?

Could you also include more details on what you are trying to accomplish and how? 
It's unclear from the description in your comment and the repro project you provided.

**Comment by geotinc** [comment]
@javiercn I just dont now that there is other way to do that.
I will try again migrating my referenced dll to razor class library 
thanks for helping

**Comment by geotinc** [comment]
@javiercn I confirm that everything seems to work well after migrating to RCL.
Thanks all for your help

**Comment by alextof** [comment]
@mkArtakMSFT , @javiercn, @geotinc I do also have some issues with the Embedded Views. Here I provide a solution with .NET Core 2.2 working and .NET Core 3.0 not working.

Could someone give me a hand please? I'm struggling to make my RazorViewToStringRenderer to find the View from the Embedded Razor Class Library.

Source Code: https://dev.azure.com/okyselov/_git/ConsoleAppEmbeddedRazorViews

**Comment by pranavkm** [comment]
@alextof could you please file a separate issue?
