### ISSUE TITLE
Adding a third-party community project to the official docs

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/AspNetCore#14381]
Hi, guys! I didn’t know where I can ask my question so I decided to open an issue here. Or maybe I should post it in the [Docs repository](https://github.com/aspnet/AspNetCore.Docs/issues)?

One of my projects have been referenced as a community project in the [Readme.md file in the old Mvc repository](https://github.com/aspnet/Mvc#aspnet-core-mvc-archived) and currently in the [Mvc folder for more than 2 years now](https://github.com/aspnet/AspNetCore/tree/master/src/Mvc#aspnet-core-mvc). It can be found here: https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc. The project is a testing library providing easy fluent API with strongly-type support for asserting controllers, models, services, routes, pipeline and more. A lot of built-in mocks are included out of the box - database, session, cache, options, authentication, etc. An example test looks like this:

```c#
// Tests a route for correct route values, 
// and validates whether the controller action 
// with an authenticated user and the provided data
// returns redirect result to a specific action,
// while resolving services from the `TestStartup` class.
MyMvc
    .Pipeline()
    .ShouldMap("/My/Action/1")
    .To<MyController>(c => c.Action(1))
    .Which(controller => controller
        .WithUser()
        .WithData(MyDataProvider.GetMyModels()))
    .ShouldReturn()
    .Redirect(redirect => redirect
        .To<AnotherController>(c => c.AnotherAction()));
```

However, ever since the ASP.NET Core team moved all repositories into one place, the link kind of got lost as it is not on the main page. I noticed quite a huge decrease of traffic coming from GitHub.

Yesterday, while I was reading your documentation pages, I saw you reference some third-party projects there, for example:

 - https://docs.microsoft.com/en-gb/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.0#prerequisites
- https://docs.microsoft.com/en-gb/aspnet/core/test/load-tests?view=aspnetcore-3.0#third-party-tools

Are there any requirements for adding a link to my GitHub repository, and a small sample code from it in there (with a visible alert that it’s a third party package and Microsoft does not support it)?

I can open a small pull-request in the documentation repository, if that’s OK for you.

My project is in very healthy state. It has two sponsor companies, and I am currently negotiating with two more. I am the only core contributor, but I have a team of 10 volunteers, who help a lot in their free time. Bits for version 3.0 are ready and working with the latest final release. I will publish them to NuGet in one-two weeks.

What are your thoughts on my question?

Thank you for reading! 

Kind regards!

**Comment by blowdart** [comment]
@Rick-Anderson Is there a suitable place in docs for this?

**Comment by Rick-Anderson** [comment]
@ivaylokenov copy/paste the issue to the docs repository.

**Comment by ivaylokenov** [comment]
@Rick-Anderson Done. Here is the new issue: https://github.com/aspnet/AspNetCore.Docs/issues/14541

**Comment by Pilchie** [comment]
Closing this as external, but @glennc might be interested in it too.
