### ISSUE TITLE
[Question]:how can I use `Microsoft.AspNetCore.Mvc.Core` in asp.net core3.0

### ISSUE THREAD

**Issue by WeihanLi** [aspnet/AspNetCore#14387]
``` csharp
C:\projects\sources\ActivityReservation\ActivityReservation.Helper\ActivityReservation.Helper.csproj : error NU1102: 找 不到版本为 (>= 3.0.0) 的包 Microsoft.AspNetCore.Mvc.Core
```

**Comment by pranavkm** [comment]
@WeihanLi the package was removed as part of the 3.0 release. See https://github.com/aspnet/Announcements/issues/325. Please follow our migration guide to update your application 
 to .NET Core 3.0: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio

**Comment by WeihanLi** [comment]
seemed the migration guide is not so useful for me
