### ISSUE TITLE
[Blazor] Components nuget packages

### ISSUE THREAD

**Issue by arivoir** [aspnet/AspNetCore#14385]
Is there any documentation explaining how the nuget packages containing Blazor components are composed?

I see there is a "staticwebassets" and others "build", "buildMultitargeting", "buildTransitive" folders. What is necessary so the static assets are including in the target project?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @arivoir .
We do not have any specific documentation about Blazor packages layout.
For the folders you're referring to, those are not Blazor specific and are documented here: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets
