### ISSUE TITLE
Microsoft.AspNetCore.Identity 3.0.0 not available on nuget yet referenced in net core 3 app

### ISSUE THREAD

**Issue by Looooooka** [aspnet/AspNetCore#14388]
Upgrading a net core 2 app to a net core 3 app I can see changes have been made to the SigninManager class from the Microsoft.AspNetCore.Identity assembly. You can see the new SDK is referencing Microsoft.AspNetCore.Identity 3.0.0.0
:

#region Assembly Microsoft.AspNetCore.Identity, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.0.0\ref\netcoreapp3.0\Microsoft.AspNetCore.Identity.dll
#endregion

Looking at the definition I can see the constructor has changed:

`namespace Microsoft.AspNetCore.Identity
{
 
    public class SignInManager<TUser> where TUser : class
    {
        public SignInManager(UserManager<TUser> userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory<TUser> claimsFactory, IOptions<IdentityOptions> optionsAccessor, ILogger<SignInManager<TUser>> logger, IAuthenticationSchemeProvider schemes, IUserConfirmation<TUser> confirmation);

}
`}``
however! you cannot add a reference to this version of Microsoft.AspNetCore.Identity to any class because as you noticed the latest version is 2.2.0
And its constructor is different(it's missing the confirmation parameter which is clearly an addition to this new 3.0.0 version)

#region Assembly Microsoft.AspNetCore.Identity, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.identity\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Identity.dll
#endregion
`
namespace Microsoft.AspNetCore.Identity
{
    public class SignInManager<TUser> where TUser : class
    {
        public SignInManager(UserManager<TUser> userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory<TUser> claimsFactory, IOptions<IdentityOptions> optionsAccessor, ILogger<SignInManager<TUser>> logger, IAuthenticationSchemeProvider schemes);
}
}
`
My SignInManager is implemented in it's own library project and thus relies on the latest Microsoft.AspNetCore.Identity nuget package and is now incompatible with the one the net core 3 SDK appears to be referencing.
So the only way around this is to create the SignInManager inside the dotnetcore 3 app(I hope this will fix it for the time being...will try tomorrow)...until somehow Microsoft.AspNetCore.Identity 3.0.0.0 appears on nuget. And it clearly should be there already seeing as how the SDK for net core was released and is in fact referencing this missing version.

Because right now you get a nice Exception:
`{"Method not found: 'Void Microsoft.AspNetCore.Identity.SignInManager`1..ctor(Microsoft.AspNetCore.Identity.UserManager`1<!0>, Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1<!0>, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Identity.IdentityOptions>, Microsoft.Extensions.Logging.ILogger`1<Microsoft.AspNetCore.Identity.SignInManager`1<!0>>, `Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider)'."}``

**Comment by blowdart** [comment]
It's part of the shared framework so you don't need to reference it. If you're seeing exceptions that's likely because you haven't updated all your references to 3.0 in your packages file.

**Comment by Looooooka** [comment]
Like I said all my packages have been updated l.
Creating the class in the dotnetcore app WORKS. 

The problem is my providers were coded inside a library project. Those have references to identity's nuget packages which had the signinmanager implementation. Those are still 2.x.x
Is there some other package that replaces them so I can still have my manager implementation in a separate library project?
Microsoft. AspNetCore.Identity.SigninManager class to be specific.
My library project just needed the 
Microsoft. AspNetCore.Identity nuget package reference and I could have a dll which could be shared amongst my project. 
Unfortunately that is stuck at 2.2.0.
So what nuget packet reference should be used in this scenario?

**Comment by leastprivilege** [comment]
use

`<FrameworkReference>Microsoft.AspNetCore.App</FrameworkReference>`

**Comment by Looooooka** [comment]
That only works when the project type is an aspnetcoreapp and even that is nownobsolete since it's apparently referenced implicitly. 

This is a net standard library with a custom implementation of that class which again...only available in 2.2.0 and incompatible with the one that's available if the class is implemented directly in a dotnetcoreapp project where it is clearly referencing a 3.0.0 version which does not appear to exist as a nuget package(yet?)

**Comment by Looooooka** [comment]
Unless I'm missing something I am unable to create a net standard library, implement a class which inherits SignInManager and then reference the library insode a net core 3.0.0 app and use that class ibsode the project.
The only way it works is if I create the class directly inside the dotnetcore app.
So if anyone has any idea what and how to reference inside the net standard library project to get the 3.0.0 version of the identity library with the new constructor signature inside the SignInManager...I am all ears.

**Comment by pranavkm** [comment]
@Looooooka you can produce a `netcoreapp3.0` targeting library. If you need to continue supporting older versions of ASP.NET Core, consider cross-compiling your library. See https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrating-libraries-via-multi-targeting

**Comment by Looooooka** [comment]
Oh TargetFrameworks was the key to getting Dominick Baier's answer working.
Thank you both.
Not pretty with all the if statements but I got it working and it's compatible with older projects that can't be migrated to 3.0 yet.
Closing issue.

**Comment by colindekker** [comment]
set the Project Sdk to `<Project Sdk="Microsoft.NET.Sdk.Web">`
