### ISSUE TITLE
Why some projects target netcore3.0 instead of netstandard2.1.

### ISSUE THREAD

**Issue by pavinan** [aspnet/AspNetCore#14383]
Microsoft.AspNetCore.Authentication.OpenIdConnect nuget package is targeted to netcore3.0. But old packages are targetting netstandard2.0. This is forcing me to use netcore3.0 as my target framework for my class libraries. But I want to target to netstandard2.1.

**Comment by pranavkm** [comment]
See these announcements - https://github.com/aspnet/Announcements/issues/324, https://github.com/aspnet/Announcements/issues/325. ASP.NET Core 3.0 and packages that rely on the framework only target netcoreapp3.0. Our migration notes cover topics on retargeting your libraries to .NET Core 3.0 as well as cross-compiling your library to target older releaes of ASP.NET Core:

* https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#update-the-project-file
* https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrating-libraries-via-multi-targeting

**Comment by pavinan** [comment]
So now I can't add a netcoreapp3.0 library to Xamarin and I can't host website in mobile app. Or is there any alternative?

**Comment by davidfowl** [comment]
@pavinan do you have a scenario for hosting an ASP.NET Core site in a Xamarin application? It's not something we've seen in the wild and definitely was no considered important to preserve.

**Comment by pavinan** [comment]
@davidfowl hosting a signalr in mobile and communicating without a central server. It is some fun experiment nothing important.

**Comment by davidfowl** [comment]
Well the mobile phone is the central server in this case right? What's the client?

**Comment by pavinan** [comment]
It is also a mobile phone.

**Comment by pavinan** [comment]
Actually one of my colleagues project is using TCP for sending commands (JSON) to each other and they wrote so much of logic. I thought it could be done with signalr which is very simple and mature.
