### ISSUE TITLE
Why does global.json use preview-8 on 3.0.0? 

### ISSUE THREAD

**Issue by effyteva** [aspnet/AspNetCore#14399]
## Describe the bug
The global.json of the 3.0.0 tag is using Sdk Preview 8, instead of using the final 3.0 release.
https://github.com/aspnet/AspNetCore/blob/v3.0.0/global.json

### To Reproduce
I don't believe it's needed.

### Expected behavior
Using the final release.

**Comment by pranavkm** [comment]
@effyteva there were a couple of last minute breaking changes in the 3.0 SDK that we didn't have enough time to react to prior to shipping 3.0 RTM. The @aspnet/build team is working on updating repositories to update the SDK to 3.0.0. We use `global.json` to ensure reproducible builds.
