### ISSUE TITLE
[ASP.NET Core 3.0] Implementation instance for IConfiguration missing from IServiceCollection (Breaking Change)

### ISSUE THREAD

**Issue by abhilasharora** [aspnet/AspNetCore#14400]
### Problem
In ASP.NET Core 3.0, the `IServiceCollection` instance in `ConfigureServices` method does not contain an implementation instance in the service descriptor for `IConfiguration`. This is a breaking change as compared to ASP.NET Core 2.x.

### Repro Steps

1. Create a new web application using ASP.NET Core 3.0
2. Update the `ConfigureServices` method in `Startup.cs` with the following code

```
public void ConfigureServices(IServiceCollection services)
{
    var configuration = services
        .Where(s => s.ServiceType == typeof(IConfiguration) && s.ImplementationInstance != null)
        .Select(s => s.ImplementationInstance)
        .FirstOrDefault();

    services.AddMvc(options => options.EnableEndpointRouting = false);
}
```

3. Debug the application and inspect the value of the variable `configuration`
4. Notice that the value of `configuration` is null

### Expected behavior
The `configuration` variable is not null and contains the resolved instance of IConfiguration injected by the framework.

**Comment by anurse** [comment]
This is part of the generic host refactoring. `IConfiguration` can be injected into the `Startup` class constructor and the `Startup.Configure`. In general, the order of registration in `IServiceCollection` isn't guaranteed, only the final content of the collection (and the `IServiceProvider` that will be built).

This behavior is by-design.

**Comment by abhilasharora** [comment]
@anurse In this case, the final contents of the service collection are **not** the same for .NET Core 2.x and .NET Core 3.0. The service descriptor for `IConfiguration` is present in the service collection for both versions of .NET Core. However, the `ImplementationInstance` property of the service descriptor is `null` in case of .NET Core 3.0, which means that the final contents of the service collection are **not** the same.

**Comment by anurse** [comment]
> However, the `ImplementationInstance` property of the service descriptor is `null` in case of .NET Core 3.0

Yes, because the service isn't registered as an **instance** any more, it's registered as a **factory** (https://github.com/aspnet/Extensions/blob/1540c1de4067870160e722e1fe661a4c131fb03c/src/Hosting/Hosting/src/HostBuilder.cs#L211). Depending on the `IServiceCollection` is a bad idea here. It's not intended for use to *activate* services (which is what you appear to be doing in your sample). It's designed to be used to add/remove service registrations and query which services have been registered.
