### ISSUE TITLE
Safari 13.0 and Blazor incompatibility

### ISSUE THREAD

**Issue by larsbj** [aspnet/AspNetCore#14413]
### Describe the bug

Using Safari Version 13.0 (14608.1.49) on Mac OS X 10.14.6 I'm unable to get any Blazor demo working. 

### To Reproduce

Go to (random example) https://blazorwithidentity.azurewebsites.net
The page is stuck at "Loading..."

The Javascript Console shows:

Unhandled Promise Rejection: TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context. https://blazorwithidentity.azurewebsites.net/_framework/wasm/mono.js 208786

This also applies to creating a new dotnet blazor locally.

### Expected behavior
I expected the page to load.

### Screenshots
<img width="1022" alt="safari_screenshot" src="https://user-images.githubusercontent.com/578147/65600518-8d4e6f80-dfa0-11e9-9765-256d1ecfd96c.png">

**Comment by javiercn** [comment]
I believe this is a known issue in safari with the current version of mono we are using. @SteveSandersonMS can confirm.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @larsbj.
This is a bug in the underlying Mono framework, which we hope will be fixed in the upcoming release.

**Comment by ricardodsanchez** [comment]
@mkArtakMSFT I'm getting the same error on Safari Version 13.0.1 (14608.2.11.1.11) with Mac OS Version 10.14.6 (18G95)

Do you have any idea when the next release with a fix will be out?

**Comment by paulallington** [comment]
Was this resolved at all?  I'm experiencing the same issue
