### ISSUE TITLE
Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' while using a FileProviders in net core 3

### ISSUE THREAD

**Issue by fpanaccia** [aspnet/AspNetCore#14418]
Hi, i have a library that render views and with the html makes a pdf.

When using the Physical Views (the ones that you have in the project) everything works fine.
But when using the fileprovider i get the following error, this was working fine in 2.1

![image](https://user-images.githubusercontent.com/5436904/65612873-6a659080-df8b-11e9-867a-5d4d49016dcc.png)

I have tried some debuggin of the  .net libraries and the farthest i can go without breaking was here.

The code is in this repo https://github.com/fpanaccia/Wkhtmltopdf.NetCore.Example.git and the branch is feature/3.0

`namespace Microsoft.AspNetCore.Mvc.Razor.Compilation`
`internal class DefaultRazorPageFactoryProvider : IRazorPageFactoryProvider`
`public RazorPageFactoryResult CreateFactory(string relativePath)`
`line 44 var viewDescriptor = compileTask.GetAwaiter().GetResult();`

### To Reproduce
1. Download the Repo and the branch
2. Open the Rotativa.sln
3. Run it and go to http://localhost:54460/TestDynamicViews/GetByteArray

### Expected behavior
Render the View and make the pdf (this is the result with the view in the project) it should have the same result
![image](https://user-images.githubusercontent.com/5436904/65613276-1ad39480-df8c-11e9-80da-67abfde6a7aa.png)

**Comment by pranavkm** [comment]
@fpanaccia with runtime compilation off by default, the 3.0 SDK avoids copying references to the build output that is needed for runtime compilation. To turn this back on, set these properties in your project file:

```xml
<PropertyGroup>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <PreserveCompilationContext>true</PreserveCompilationContext>
</PropertyGroup>
```

**Comment by fpanaccia** [comment]
@pranavkm Hi, thanks!, adding those parameters to the project that uses the library, it worked, but, everyone that uses the library will have to set these properties, there is another way to do it?

**Comment by pranavkm** [comment]
You could update the package to include build targets that specify these properties. That's essentially what the runtime compilation package does: 

https://github.com/aspnet/AspNetCore/blob/release/3.1/src/Mvc/Mvc.Razor.RuntimeCompilation/src/build/netcoreapp3.0/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.targets#L3-L4

**Comment by fpanaccia** [comment]
Thanks! i will try later!, i will close the issue, and if that doesn't work (i'm sure it will), i will re open the issue, thanks again!
