### ISSUE TITLE
Textarea does not display value when it has an asp-for parameter

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14428]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/607654/textarea-does-not-display-value-when-it-has-an-asp.html)._

---
The Textarea does not display a viewbag value when it has an asp-for parameter in it. 

Example:
No value displayed:
&lt;textarea class=&quot;form-control&quot; asp-for=&quot;TEST_UniquePart&quot;&gt;@ViewBag.TEST_UniquePart&lt;/textarea&gt;
Value displayed:
&lt;textarea class=&quot;form-control&quot;&gt;@ViewBag.TEST_UniquePart&lt;/textarea&gt;

Viewbag contains correct value of its last content. String array also does not work. The value comes from a model will be stored in a cookie and then is sent via ViewBag to the View. 

I am using ASP Core 3.0 Preview 5 MVC.

---
#### Visual Studio Feedback System on 6/14/2019, 02:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/16/2019, 11:56 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The behavior you're observing here is by-design.
`asp-for` purposefully overwrites the content of the text area.
