### ISSUE TITLE
Serialization of TimeZoneInfo (v3.0)

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#14422]
_From @avo-tgundhus on Wednesday, September 25, 2019 11:39:34 AM_

Serialization of TimeZoneInfo.Local fails and results in an incorrect json when sending over SignalR.

The Client uses version 3.0.
The Server is built on .NET core 2.2. 

Client code:
`HubConnection.SendAsync("Initialize", DateTime.UtcNow, TimeZoneInfo.Local);`

Server code:
`[public async Task Initialize(DateTime clientTimeInUTC, TimeZoneInfo clientTimeZone) { .. }]`

### Expected  behavior
How the TimeZoneInfo should be parsed, and is parsed if I use NewtonSoft serializer directly.
```
{
  "id": "W. Europe Standard Time",
  "displayName": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "standardName": "W. Europe Standard Time",
  "daylightName": "W. Europe Daylight Time",
  "baseUtcOffset": {
    "ticks": 36000000000,
    "days": 0,
    "hours": 1,
    "milliseconds": 0,
    "minutes": 0,
    "seconds": 0,
    "totalDays": 0.041666666666666664,
    "totalHours": 1,
    "totalMilliseconds": 3600000,
    "totalMinutes": 60,
    "totalSeconds": 3600
  },
  "supportsDaylightSavingTime": true
}
```

### Actual behavior
How it is sent via SignalR.  You can see an extra curly bracket on line 1 in the JSON. These are ONLY added if I sent through signalR. If I serialize TimeZoneInfo using NewtonSoft in either the server or the client, this works perfect and gives the json listed above. 
```
{{
  "id": "W. Europe Standard Time",
  "displayName": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "standardName": "W. Europe Standard Time",
  "daylightName": "W. Europe Daylight Time",
  "baseUtcOffset": {
    "ticks": 36000000000,
    "days": 0,
    "hours": 1,
    "milliseconds": 0,
    "minutes": 0,
    "seconds": 0,
    "totalDays": 0.041666666666666664,
    "totalHours": 1,
    "totalMilliseconds": 3600000,
    "totalMinutes": 60,
    "totalSeconds": 3600
  },
  "supportsDaylightSavingTime": true
}}
```

#### Exception
Exception message: _System.Runtime.Serialization.SerializationException: Member 'Id' was not found._
```
2019-09-25 10:41:37 Failed to invoke hub method '"Initialize"'.
System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked. ---> System.Runtime.Serialization.SerializationException: Member 'Id' was not found.
   at System.Runtime.Serialization.SerializationInfo.GetElement(String name, Type& foundType)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.TimeZoneInfo..ctor(SerializationInfo info, StreamingContext context)
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JsonTextReader reader, IReadOnlyList`1 paramTypes)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JsonTextReader reader, IReadOnlyList`1 paramTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(Utf8BufferTextReader textReader, IInvocationBinder binder)
```

_Copied from original issue: SignalR/SignalR#4409_

**Comment by BrennanConroy** [comment]
In 3.0, the client now uses System.Text.Json by default. You could try switching back to Newtonsoft.Json on the client to see if that resolves the issue https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#switch-to-newtonsoftjson

I tried this with the 2.1 client and was successfully sending the TimeZoneInfo.

**Comment by avo-tgundhus** [comment]
It worked perfectly for us before we updated as well. 
I'll try to switch back and see if it helps.

**Comment by anurse** [comment]
If switching to Newtonsoft fixes it, I'd suggest filing an issue in https://github.com/dotnet/corefx to consider making changes to System.Text.Json to change the serializer behavior.

**Comment by anurse** [comment]
The extra curly braces definitely seem weird. That's invalid JSON.

@avo-tgundhus could you isolate this to a console app that uses [`JsonSerializer`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=netcore-3.0) **directly**? If you can reproduce the issue there, I would **definitely** suggest filing a bug (including your repro code) on dotnet/corefx because there may be a bug in the serializer.

**Comment by avo-tgundhus** [comment]
@anurse @BrennanConroy Changing back to Newtonsoft solved the problem. During the last 24 hours we encountered multiple issues on the hubConnection, so it might be other serialization issues like this. I'll see if I can take a deep-dive in the logs and check. 

I have not yet created an isolated project for it, but I'll put it on my list.

**Comment by anurse** [comment]
I'm not able to repro an issue immediately in a Console app. This may be in how we interact with the serializer. @halter73 could you hack up a quick attempt to repro this and do a quick investigation?

**Comment by halter73** [comment]
I'm not seeing any double curly braces in my testing. I was able to reproduce the following error:

```
System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
 ---> System.Runtime.Serialization.SerializationException: Member 'Id' was not found...
```

The cause of the error wasn't an issue with `{{` (that wouldn't even be valid JSON), but because the System.Text.Json-based 3.0 client camelCases the property names, but the Newtonsoft-based 2.2 server does not accept it. You can workaround the camelCase issue, by forcing the System.Text.Json-based 3.0 client not to camelCase as follows:

```c#
await using var hubConnection = new HubConnectionBuilder()
    .WithUrl("http://localhost:5000/timezone")
    .AddJsonProtocol(options =>
    {
        options.PayloadSerializerOptions.PropertyNamingPolicy = new PassthroughJsonNamingPolicy();
    })
    .Build();

// ...

class PassthroughJsonNamingPolicy : JsonNamingPolicy
{
    public override string ConvertName(string name)
    {
        return name;
    }
}
```

This turns

```json
{
  "id": "Pacific Standard Time",
  "displayName": "(UTC-08:00) Pacific Time (US & Canada)",
  "standardName": "Pacific Standard Time",
  "daylightName": "Pacific Daylight Time",
  "baseUtcOffset": {
    "ticks": -288000000000,
    "days": 0,
    "hours": -8,
    "milliseconds": 0,
    "minutes": 0,
    "seconds": 0,
    "totalDays": -0.3333333333333333,
    "totalHours": -8,
    "totalMilliseconds": -28800000,
    "totalMinutes": -480,
    "totalSeconds": -28800
  },
  "supportsDaylightSavingTime": true
}
```

into

```json
{
  "Id": "Pacific Standard Time",
  "DisplayName": "(UTC-08:00) Pacific Time (US & Canada)",
  "StandardName": "Pacific Standard Time",
  "DaylightName": "Pacific Daylight Time",
  "BaseUtcOffset": {
    "Ticks": -288000000000,
    "Days": 0,
    "Hours": -8,
    "Milliseconds": 0,
    "Minutes": 0,
    "Seconds": 0,
    "TotalDays": -0.3333333333333333,
    "TotalHours": -8,
    "TotalMilliseconds": -28800000,
    "TotalMinutes": -480,
    "TotalSeconds": -28800
  },
  "SupportsDaylightSavingTime": true
}
```

Unfortunately, even this does completely fix the TimeZoneInfo serialization/deserialization problem, because Newtonsoft and System.Text.Json handle TimeSpans differently.

System.Text.Json serializes TimeSpans like BaseUtcOffset as an object as seen above whereas Newtonsoft expects the TimeSpan to be serialized into a string like the following: `"BaseUtcOffset": "-08:00:00"`.

The end result is even with all the properties properly PascalCased by System.Text.Json, the Newtensoft will refused to deserialize the `BaseUtcOffset` TimeSpan with the following error:

```
System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked. ---> Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.TimeSpan' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
```

That's where I stopped trying to make the System.Text.Json-based client work with the Newtonsoft-based server. If you want to upgrade the clients to 3.0 ahead of the server, I recommend just referencing the [Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson/) and using that as follows:

```C#
await using var hubConnection = new HubConnectionBuilder()
    .WithUrl("http://localhost:5000/timezone")
    .AddNewtonsoftJsonProtocol()
    .Build();
```

I've confirmed this fixes the TimeZoneInfo deserialization issue.

**Comment by halter73** [comment]
@BrennanConroy pointed out to me that SignalR 1.1 (which corresponds with ASP.NET Core 2.2) [already defaults to camelCase](https://github.com/aspnet/AspNetCore/blob/v2.2.7/src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs#L733). I confirmed that sending camelCased objects to the 1.1 server does indeed work with a custom type.

I'm not sure why the PassthroughJsonNamingPolicy changed the TimeZoneInfo deserialization error. Either way, setting things up so both the client and server using the same Json serialization/deserialization library is probably your best bet for fixing these kinds of issues.

**Comment by BrennanConroy** [comment]
Closing as this is an issue with System.Text.Json's support of `TimeZoneInfo`.

Our recommendation in these cases is to use the same serializer/deserializer on the server and client.
