### ISSUE TITLE
Timer count down does not work in 3.0 

### ISSUE THREAD

**Issue by zoinkydoink** [aspnet/AspNetCore#14421]
Initially reported here, https://github.com/aspnet/AspNetCore/issues/13488#event-2591166315

but the latest version of .NET Core (3.0) seem to throw the following exception for the code below

> System.ObjectDisposedException: 'Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.'

This is being thrown at `StateHasChanged()`

```
<span>@Time</span>
@code
{
    private string Time { get; set; }


    protected override void OnInitialized()
    {
        var timer = new System.Threading.Timer((_) =>
        {
            Time = DateTime.UtcNow.ToString();
            InvokeAsync(() =>
            {

                StateHasChanged();
            });
        }, null, 0, 1000);
        base.OnInitialized();
    }
}
```

**Comment by javiercn** [comment]
@zoinkydoink Thanks for contacting us.

I don't think we have enough information to detect what's happening here. You are not cancelling the time, so it's likely that if the Renderer or the component is being disposed you might try to trigger a render on a disposed renderer.

You should cancel your timer when the component gets disposed and that should avoid this issue.

**Comment by zoinkydoink** [comment]
> @zoinkydoink Thanks for contacting us.
> 
> I don't think we have enough information to detect what's happening here. You are not cancelling the time, so it's likely that if the Renderer or the component is being disposed you might try to trigger a render on a disposed renderer.
> 
> You should cancel your timer when the component gets disposed and that should avoid this issue.

Sorry, I am not sure what other information your looking for, simply dropping that component on a razor page and running it in IIS express results in that error, this same code worked in P8.
So I am not sure what changed between P8 to 3.0 Release

**Comment by javiercn** [comment]
@zoinkydoink The app is being prerendered. Once we finish generating the initial HTML we dispose the renderer. Your timer is trying to trigger a render on a disposed renderer. It's likely due to the fact that we took out connected prerendering.

**Comment by zoinkydoink** [comment]
So what would I have to do to get the above code working?


________________________________

**Comment by javiercn** [comment]
Implement IDisposable in your Component and cancel the timer when your component gets disposed.

**Comment by zoinkydoink** [comment]
updated to code below, but that still didnt solve my problem, even if it is suppose to, according to another thread i found, IDisposable is only for blazor client-side is that correct?
below is the code that still fails

```
<span>@Time</span>
@implements IDisposable
@code
{
    private string Time { get; set; }
    private System.Threading.Timer timer;

    protected override void OnInitialized()
    {
        timer = new System.Threading.Timer((_) =>
        {
            Time = DateTime.UtcNow.ToString();
            InvokeAsync(() =>
            {

                this.StateHasChanged();
            });
        }, null, 0, 1000);
        base.OnInitialized();
    }
    public void Dispose()
    {
        timer = null;
    }
}
```

**Comment by javiercn** [comment]
@zoinkydoink Setting the variable to null doesn't cancel the timer. See this SO answer https://stackoverflow.com/a/6379813

**Comment by zoinkydoink** [comment]
@javiercn i updated the code to change timer using
```
public void Dispose()
    {

        timer.Change(Timeout.Infinite, Timeout.Infinite);
        timer = null;
    }
```

Apparently `timer.Change(Timeout.Infinite, Timeout.Infinite);``` this is not reliable so i am at odds on what I need to actually fix the code above

**Comment by zoinkydoink** [comment]
FIXED by switching to System.Timer instead of Threading.Timer, is this the most efficient code though?

```
<span>@Time</span>
@implements IDisposable

@code
{
    private string Time { get; set; }


    private System.Timers.Timer timer = new System.Timers.Timer();

    private void OnTimerElapsed(object sender, System.Timers.ElapsedEventArgs e)
    {
        Time = DateTime.UtcNow.ToString();
        InvokeAsync(() =>
        {

            this.StateHasChanged();
        });
    }



    protected override void OnInitialized()
    {
        timer.Elapsed += OnTimerElapsed;
        timer.Start();
        base.OnInitialized();
    }
    public void Dispose()
    {

        timer.Stop();
        timer = null;
    }
}
```
