### ISSUE TITLE
blazor (client-side) template dissapeared from VS 2019 16.2.0 Preview 2

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14429]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/617906/blazor-client-side-template-dissapeared-from-vs-20.html)._

---
Hello,

This page (https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&amp;tabs=visual-studio) says that &quot;For a Blazor client-side experience, choose the Blazor (client-side) template.&quot; however I can see only Blazor ( serevr-side) templete in the list. I tested it with 2 different installation of VS 16.2.0 Preview 2 and the template is missng in both of them.

It seems that in the earlier versions of VS 2019 there was this template.

However, I can still create new blazor client-side project using command dotnet command line tool (.NET Core 3.0 Preview 6).

Would you mind clarify that dissapearance that template from VS is an intended change or a bug?

Thank you,
Alexander.

---
#### Visual Studio Feedback System on 6/24/2019, 02:52 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/26/2019, 01:40 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Marc W. George on 7/1/2019, 11:35 AM: 

I have the same issue in Preview 3.
#### Byrd, Joel on 7/25/2019, 05:16 AM: 

<p>Same issue in Visual Studio 16.3.0 Preview 1.0. I ran...</p><pre>dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview7.19365.7</pre><p>...in the console, and it lists all the Blazor templates, including both server-side and client-side, but when I go to create a new project and search for Blazor, only the server-side version shows up.</p>

#### Brad Wood on 8/14/2019, 04:56 PM: 

<p>Using VS2019 version 16.2.2, after running dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview8.19405.7 (as it reads in the current blazor doc), I don't get any templates at all.</p>

#### Matthew Tamm on 8/21/2019, 06:36 PM: 

<p>VS 16.3.0 Preview 2 and dotnet 3.0.100-preview8-013656</p>
<p>Template was also missing here ... installed preview 8 templates with the following:</p><pre>dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview8.19405.7</pre><p>Restarted VS, all good now.</p><p>Taken from the below.  There is a note in there about uninstalling any previous version templates, this might be affecting others, YMMV</p><p><a target='_blank' href="https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio">https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio</a></p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Seems this is resolved already.
