### ISSUE TITLE
MVC CheckBoxFor() intermittent failure

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14431]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/498449/mvc-checkboxfor-intermittent-failure.html)._

---
when using @HTML.CheckBoxFor() if it is not isolated in a div without any other markup &amp; U do not include the onchange event, then the bool value intermittently returns to the controller as false, when checked.

random failure..

&lt;div class=&quot;display-field&quot;&gt;
		@Html.DisplayNameFor(model =&gt; model.IAgree)
	    @Html.CheckBoxFor(m =&gt; Model.IAgree)
	    @Html.ValidationMessage(&quot;U have to Agree, Right?&quot;);
	    @Html.CheckBoxFor(m = model.TrueFalse)
&lt;/div&gt;

if U write it like this it works..

&lt;div class=&quot;display-field&quot;&gt;
		@Html.DisplayNameFor(model =&gt; model.IAgree)
	    @Html.CheckBoxFor(m =&gt; model.IAgree, new { onchange=&quot;this.value = this.checked;&quot; })
	    @Html.ValidationMessage(&quot;U have to Agree, Right?&quot;);
	    @Html.CheckBoxFor(m = model.TrueFalse, new { onchange=&quot;this.value = this.checked;&quot; })
&lt;/div&gt;

or like this it works..

&lt;div class=&quot;display-field&quot;&gt;
		@Html.DisplayNameFor(model =&gt; model.IAgree)
	    &lt;input type=&quot;checkbox&quot; id=&quot;IAgree&quot; name=&quot;IAgree&quot;
			   @(Model.TrueFalse ? &quot;checked value=\&quot;true\&quot;&quot; : &quot;value=\&quot;false\&quot;&quot;)
			   onchange=&quot;this.value = this.checked;&quot; /&gt;
	    @Html.ValidationMessage(&quot;U have to Agree, Right?&quot;);
            &lt;input type=&quot;checkbox&quot; id=&quot;TrueFalse&quot; name=&quot;TrueFalse&quot;
			   @(Model.TrueFalse ? &quot;checked value=\&quot;true\&quot;&quot; : &quot;value=\&quot;false\&quot;&quot;)
			   onchange=&quot;this.value = this.checked;&quot; /&gt;		
&lt;/div&gt;

---
#### Visual Studio Feedback System on 3/19/2019, 08:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/20/2019, 11:48 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please provide more information about what is the `failure` you're referring to?
