### ISSUE TITLE
file name was back to past by CTRL+S

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14439]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/693662/file-name-was-back-to-past-by-ctrls.html)._

---
1. In Visual Studio, Create File with lowercase file name (Example: page.razor)
2. Open the file in Visual Studio
3. change file name as uppercase (same name) in solution explorer (Example: Page.razor)
4. Type Ctrl+S
5. file name is changed to lowercase (Example: page.razor)

In case of razor, lower case file name is not allowed in Blazor.
Close Document, change file name, Re-Open Document is safe.

---
#### Visual Studio Feedback System on 8/14/2019, 00:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/15/2019, 11:11 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
This issue was moved to dotnet/project-system#5546
