### ISSUE TITLE
Microsoft.AspNetCore.Identity(.Core) v3 nuget package missing

### ISSUE THREAD

**Issue by njannink** [aspnet/AspNetCore#14441]
I'm trying to migrate my code to the v3 nuget packages and I run into issues with the v3 identity management. The nuget package for the core library seems to be missing and the only way how I can get it through nuget is by using either the Microsoft.AspNetCore.Identity.UI or the Microsoft.AspNetCore.ApiAuthorization.IdentityServer nuget package. But both these packages add a lot of additional unneeded dependencies.

Any suggestions how I can use the functionality from the core identity library without dragging in these bigger nugets?

There is a 2.2 nuget package: https://www.nuget.org/packages/Microsoft.AspNetCore.Identity/

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/14388. 

You'll need a `FrameworkReference` to `Microsoft.AspNetCore.App` to reference the API. 
Our migration guide - https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30 - has notes on updating to target ASP.NET Core 3.0 as well as ways to cross-compile to support multiple versions of ASP.NET Core.

**Comment by javiercn** [comment]
@blowdart Closing this as a dup of #14388
