### ISSUE TITLE
Access the route values in IAuthorizationRequirement with endpoint routing enabled

### ISSUE THREAD

**Issue by Sebazzz** [aspnet/AspNetCore#14442]
### Is your feature request related to a problem? Please describe.
I'm trying to access the routing values of the current request in the `IAuthorizationRequirement`. I need those to determine whether the request is authorized or not. 

Without Endpoint routing, you can cast the `AuthorizationHandlerContext.Resource` to `AuthorizationFilterContext` and from there on access the HTTP context.

With Endpoint routing, all you get is a `RouteEndpoint` which only contains app-wide static metadata, but nothing request-specific. 

### Describe the solution you'd like
I like to access the the routing information in my `IAuthorizationRequirement`. It is simply not possible now as it appears. 

I'd consider using `HttpContextAccessor` but even that is not possible because you cannot inject services into `IAuthorizationRequirement` because at the point of object creation you don't have a `IServiceProvider` yet (because ultimately you build the authorization policies in `ConfigureServices`). Still, it seems a bit cumbersome to use `HttpContextAccessor` when further up the call stack `HttpContext` is available (at the `IPolicyEvaluator` level).

Related: aspnet/AspNetCore.Docs/issues/12564

**Comment by rynowak** [comment]
Your workaround is probably the best thing to do for now. We got this feedback from 3-4 people once 3.0 shipped 😞 - but unfortunately providing a good solution to this going to take more API change than we're able to do in a 3.1 release.

We should consider more changes to address this in 5.0

**Comment by rynowak** [comment]
@blowdart @HaoK @Tratcher - we don't expose an easy way to get to the HttpContext in a requirement today. Users were doing it through one of MVC's contexts in 2.X, we should look at this API and see what we can do to make this possible without the `IHttpContextAccessor`.

**Comment by anurse** [comment]
I think we'd solve this through something like #16695 rather than specifically adding route values. The HttpContext would have that information. We're already planning to look at that in 5.0.

Closing this since we can track this in #16695 .
