### ISSUE TITLE
ASP.NET Core 3 and NuGet Packages

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/AspNetCore#14440]
Question concerning ASP.NET Core 3 and individual NuGet packages.

Since ASP.NET Core 3 only runs on .NET Core 3 and given that there are (currently) no individual NuGet packages ( MVC Core version 3.x for example ), does this mean that ASP.NET Core is updated on the server only when the target framework changes?

**Comment by ToddThomson** [comment]
OK. I now understand that the FrameworkReference to Microsoft.AspNetCore.App refers to a shared runtime. When using:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
</Project>
```
How do you specify a minimum version to the shared runtime?

**Comment by pranavkm** [comment]
@ToddThomson https://docs.microsoft.com/en-us/dotnet/core/versions/selection#framework-dependent-apps-roll-forward has a fairly detailed explanation about how the version of the shared runtime that gets used is calculated.
