### ISSUE TITLE
Blazor WASM template missing when building + using from source

### ISSUE THREAD

**Issue by kg** [aspnet/AspNetCore#14456]
### Describe the bug
When I build aspnetcore from source and then ```source activate.sh``` I get a dotnet that only has the blazor server template, not blazor wasm. If I follow the tutorial instructions from the official site I have both blazor server and wasm templates. As a result I can't 'dotnet new' a blazor wasm project when building from source.

If I try to use an existing blazor wasm project w/a from-source build of aspnetcore it doesn't work, but that seems expected.

### To Reproduce
1. Build from source with build.sh on a master checkout
2. ```source ./activate.sh```
3. ```cd .. ; mkdir blazortest ; cd blazortest ; dotnet new blazorwasm```

### Expected behavior
It works

### Actual behavior
```No templates matched the input template name: blazorwasm```

And the installed templates list contains blazorserver but not blazorwasm.

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version: 5.0.100-alpha1-013788
 Commit: 9df6ca668d

Runtime Environment:
 OS Name: Mac OS X
 OS Version: 10.15
 OS Platform: Darwin
 RID: osx.10.15-x64
 Base Path: /Users/katelyngadd/Projects/AspNetCore/.dotnet/sdk/5.0.100-alpha1-13788/
```

**Comment by chandrakantnaik789** [comment]
as per this docs https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

You need to run the following command to obtain blazor assembly
**`dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview2.19528.8`**
