### ISSUE TITLE
Compiling ASP.NET Core 2.x application while targeting .NET Core 3.0

### ISSUE THREAD

**Issue by jinhong-** [aspnet/AspNetCore#14458]
As the question says, is it possible to Target .NET Core 3.0 while still using ASP.NET Core 2.x? It looks like libraries in ASP.NET Core 2.x is compiled using .NET Standard 2.0. So far i cannot figure out how to get this to work. I have tried explicitly setting the version of "Microsoft.AspNetCore.App" package to 2.x but it still was using ASP.NET Core 3.0

**Comment by davidfowl** [comment]
Possible? Yes. Difficult? Yes. Tested? No. 

Why?

**Comment by jinhong-** [comment]
I read that there are a lot of performance improvements in .NET Core 3.0 + improved docker images for container workloads. For me, we have a dependency on OData, which is currently only available in ASP.NET Core 2.1, or 2.2 with backwards compatibility flag enabled.
From my understanding, several of the perf improvements are low level APIs, which means that we can reap those benefits by just moving to the .NET 3.0 runtime. Or would it be possible to run a .NET Core 2.x application in .NET Core 3.0 runtime and get those benefits?
