### ISSUE TITLE
RequestLocalizationMiddleware should use CultureInfo.Parent to walk down the hierarchy

### ISSUE THREAD

**Issue by kinosang** [aspnet/AspNetCore#14452]
As #2634 and [here](https://github.com/aspnet/Localization/issues/273#issuecomment-237983479), `RequestLocalizationMiddleware` should use `CultureInfo.Parent` to walk down the hierarchy (as @ryanbrandenburg commented).

But the `RequestLocalizationMiddleware` just uses a simple string manipulation (see codes below).

https://github.com/aspnet/AspNetCore/blob/23596349092f69890c3efe5b8b9005856cc83db2/src/Middleware/Localization/src/RequestLocalizationMiddleware.cs#L213-L224

@yufeih reported the same issue [here](https://github.com/aspnet/Localization/issues/273#issuecomment-329391447)

**Comment by javiercn** [comment]
@kinosang Thanks for contacting us.

@ryanbrandenburg Do you have any comments here?

**Comment by hishamco** [comment]
I think we already handle something similar to this on [OrchardCore](https://github.com/OrchardCMS/OrchardCore), let me handle this one

**Comment by ryanbrandenburg** [comment]
Given https://github.com/aspnet/AspNetCore/pull/14964#issuecomment-561772063 we're going to close this. For now our recommendation for anyone having trouble with this is that they include any descendent/more specific cultures explicitly in their SupportedCultures.

**Comment by hishamco** [comment]
Ok
