### ISSUE TITLE
dotnet pack doesn't work for static files and project reference

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#14467]
Original issue: https://github.com/stsrki/Blazorise/issues/282

I have this project structure

![00](https://user-images.githubusercontent.com/900302/65687390-97887080-e069-11e9-9a44-55e9742f456a.png)

I use `dotnet pack` to create nuget packages

```
dotnet pack ../Source/Blazorise/Blazorise.csproj --force -o . -c Release
dotnet pack ../Source/Blazorise.Bootstrap/Blazorise.Bootstrap.csproj --force -o . -c Release
```

For root project Blazorise everything is generated just fine. But for all other projects that have reference to the `Blazorise.csproj` **contentFiles** and static files are not working as expected. As you can see in the following image `contentFiles` is included in the `.nuspec`.

![01](https://user-images.githubusercontent.com/900302/65687791-39a85880-e06a-11e9-9319-9e826424144e.png)

When you navigate to that file you see that it is referencing wwwroot in the root project

![02](https://user-images.githubusercontent.com/900302/65687802-3dd47600-e06a-11e9-93bf-d94e53a07969.png)

Also the path goes to my local folder which it should not be there.

---

As a workaround I have fallback to `nuget pack` and I manually generate nupkg packages based on `dotnet pack`. To make it work I have removed `content` and `contentFiles` from nupkg.

Full code for a workaround can be found on branch **fix-nugets**
https://github.com/stsrki/Blazorise/tree/fix-nugets/NuGet

- `dotnet-pack.bat` is problematic
- `pack.bat` is used as a workaround

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by stsrki** [comment]
Hi @mkArtakMSFT 

I would like it to be a question but I think it's a bug in `dotnet pack`. What I try to accomplish is to pack Razor Static Libraries and create nuget packagea. As you can see in the previous example every project is RCL.

The problem is indicated for every project except for root project named Blazorise. Every project in a solution have a reference to Blazorise.

When I run `dotnet pack` the `content` and `contentFiles` are created in nupkg. Now I don't know if they should or should not be created. What I know and what you can see from example is that ContentRoot is pointing to local directory. And on top of that it's pointing to the root csproj.

If I remove those directories from nupkg it all works. Based on all of that I can assume it's a bug. If something can be done to disable that behavior I could not find it in the documentation. https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack

Also, I have provided a link to my repository so that you guys can reproduce the bug and see it for yourself. I can go and create a minimal project(s) if that is prefered.
