### ISSUE TITLE
Can't use Microsoft.AspNetCore.Http (3.0) from a Class Library

### ISSUE THREAD

**Issue by SnakyBeaky** [aspnet/AspNetCore#14462]
Let's suppose we have a class library that extends HttpContext/HttpRequest for AspNetCore 2.2, and has a NuGet package reference to `Microsoft.AspNetCore.Http 2.2.0`.

And just for context, let's suppose this class library used the `HttpRequest.EnableRewind()` method because the library needs to read the body stream and in AspNetCore 3.0, `HttpRequest.EnableRewind()` has been replaced by `HttpRequest.EnableBuffering()`.

It seems that the only way to access `Microsoft.AspNetCore.Http 3.0.0` is to reference the whole framework `Microsoft.AspNetCore.App 3.0.0`, but that can't be done in a Class Library, and neither `Microsoft.AspNetCore.App 3.0.0` or  `Microsoft.AspNetCore.Http 3.0.0` have NuGets available, and the release notes state that they won't produce NuGet packages for them:

 ```
ASP.NET Core no longer produces a large number of NuGet package features.
These package references should be removed from your project file.

To see the full list of packages that are no longer produced, see below:

...
Microsoft.AspNetCore.App
...
Microsoft.AspNetCore.Http
Microsoft.AspNetCore.Http.Abstractions
...
```

So, am I missing something, or starting at AspNetCore 3.0 there's no possible way to reference such package from a class library?

**Comment by javiercn** [comment]
@SnakyBeaky Thanks for contacting us.

You should be able to do this by adding `<FrameworkReference Include="Microsoft.AspNetCore.App" />` in your class library and targeting netcoreapp3.0

**Comment by SnakyBeaky** [comment]
That seems to work, thanks @javiercn .

I'm sure this will come up frequently when migrating libraries to 3.0, this piece of information should be somewhere visible.

**Comment by javiercn** [comment]
It's likely on the migration guide.

**Comment by scottaddie** [comment]
> I'm sure this will come up frequently when migrating libraries to 3.0, this piece of information should be somewhere visible.

@SnakyBeaky There's a related bit here: https://docs.microsoft.com/aspnet/core/migration/22-to-30?view=aspnetcore-3.0#framework-reference. @DamianEdwards and I are collaborating on some prescriptive guidance in the form of a larger doc. That work is being tracked at https://github.com/aspnet/AspNetCore.Docs/issues/14309.
