### ISSUE TITLE
string.Compare function does not work when deployed to linux (.Net Version 2.0)

### ISSUE THREAD

**Issue by ZackTech** [aspnet/AspNetCore#14461]
If you create a .Net Api project on a windows pc then use the following commands:

dotnet restore -r ubuntu.16.04-x64
dotnet build -r ubuntu.16.04-x64
dotnet publish -f netcoreapp2.0 -c Release -r ubuntu.16.04-x64

Then publish onto Ubuntu

Then do:

string myValue = "False";
var resultA = string.Compare(myValue , "false", false);
var resultB = string.Compare(myValue , "false", true);

Both resultA and resultB are equal to -1

I have a work around so this is for information only, so close the bug whenever you want to.
I have not yet got round to upgrading to ,Net Version 3, so I don't know if it is still an issue.

**Comment by javiercn** [comment]
@ZackTech Thanks for contacting us.

This is not an ASP.NET Core specific issue. It will be best if you report it in https://github.com/dotnet/corefx or https://github.com/dotnet/coreclr

**Comment by ZackTech** [comment]
Move to: https://github.com/dotnet/corefx/issues/41351
on advice from  javiercn
