### ISSUE TITLE
npm audit for .NET core

### ISSUE THREAD

**Issue by colotiline** [aspnet/AspNetCore#14460]
### Is your feature request related to a problem? Please describe.
I am trying to do audit NuGet packages in my project for vulnerabilities automatically but I can't. 

Ok, we trust NuGet packages by default, but when and how should I know that I need to update any of them? 

### Describe the solution you'd like
I want a solution that is a dotnet tool and looks like 'npm audit' (https://blog.npmjs.org/post/173719309445/npm-audit-identify-and-fix-insecure).

**Comment by khellang** [comment]
This work is already in progress. See [the issue](https://github.com/NuGet/Home/issues/8087) and [the spec](https://github.com/NuGet/Home/wiki/Flag-vulnerable-packages).

**Comment by javiercn** [comment]
@colotiline Thanks for contacting us.

We think this a question better asked to the NuGet folks at https://github.com/nuget/home

Hope that helps.
