### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Authentication.Internal.RequestPathBaseCookieBuilder'

### ISSUE THREAD

**Issue by MorenoJesus** [aspnet/AspNetCore#14476]
### Describe the bug
Created a new project with ASP.Net Core 3 with Angular template.  Configured authentication support with OpenIdConnect. Start application on local to test authentication and received an internal sever error:
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Authentication.Internal.RequestPathBaseCookieBuilder' from assembly 'Microsoft.AspNetCore.Authentication, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### To Reproduce
1. Using ASP.Net Core 3 with Angular template
2. Configure StartUp.cs  to use OpenIdConnect
3. Run application

### Expected behavior
Net core 3.0 should load Microsoft.AspNetCore.Authentication.Internal.RequestPathBaseCookieBuilder from Microsoft.AspNetCore.Authentication assembly version 3.0

### Screenshots
![TypeLoadException](https://user-images.githubusercontent.com/15218146/65707231-b67b0880-e051-11e9-8ab9-f3440970af30.PNG)

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by blowdart** [comment]
@HaoK @javiercn

**Comment by javiercn** [comment]
> 2\. onfigure StartUp.cs  to use OpenIdConnect

What does this mean. Can you provide more details?

**Comment by Tratcher** [comment]
It looks like you're mixing dependency versions. Please share all of your dependency versions from your csproj file.

**Comment by remy90** [comment]
@MorenoJesus  how did you fix this? I have an identical error

**Comment by MorenoJesus** [comment]
@remy90 to be honest, I did not fix it. Due to project timelines I had to go with .Net Core 2.2 which worked out well. I did not have enough time to continue to dig into this issue.

**Comment by Tratcher** [comment]
This happens if you try to use a 2.2 auth handler on 3.0. The auth handlers need to recompile for 3.0.

**Comment by remy90** [comment]
One project dependency (in my case) relies on Microsoft.AspNetCore.Authentication, which has been archived at 2.2.0 and simply refers to "[https://github.com/aspnet/AspNetCore](https://github.com/aspnet/AspNetCore)" for continued development. I've not managed to find any supporting documentation as to how this should be updated in [migration ](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)?

**Comment by Tratcher** [comment]
@remy90 Many package references have been replaced by `<FrameworkReference Include="Microsoft.AspNetCore.App" />`
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#framework-reference
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrate-libraries-via-multi-targeting
