### ISSUE TITLE
Blazor server SignalR disconnects when a component is included in both a razor page and a layout page

### ISSUE THREAD

**Issue by ACertainDeveloper** [aspnet/AspNetCore#14474]
### Describe the bug
Blazor server SignalR disconnects when a component is included in both a razor page and a layout page.

### To Reproduce
1. Using this version of ASP.NET Core '3.0'
2. Create a new asp.net core web application 
3. Add blazor.server.js to layout page.
4. Add MapBlazorHub() and AddServerSideBlazor() to Startup
5. Add a component to both the layout page and a razor page

### Expected behavior
Blazor components rendered on razor pages should function normally when a component is included in the layout.

### Example App
<a href="https://github.com/ACertainDeveloper/BlazorIssue">Example App</a>

**Comment by ACertainDeveloper** [comment]
<a href="https://i.stack.imgur.com/NOblJ.png">Screenshot of error</a>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ACertainDeveloper.
@pranavkm can you please look into this? Thanks!
