### ISSUE TITLE
Register page on Angular SPA Template

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14479]
_From @kwakuduahc1 on Thursday, September 26, 2019 3:02:48 PM_

Register page on Angular SPA Template

I cannot find the register page/view in the new Angular SPA template. I have looked into the pages and ClientApp folder but I can neither find the controller for authentication nor the view/page for it.

Clicking on register loads the page alright.

Thank you.

_Copied from original issue: dotnet/core#3484_

**Comment by kwakuduahc1** [comment]
Thank you @scalablecory, it is easily forgettable that netcore is not the same as aspnet netcore

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kwakuduahc1 .
Identity related pages are loaded from the DefaultIdentityUI package. If you want to modify those in any way, you can scaffold the necessary pages and modify as needed.

**Comment by mkArtakMSFT** [comment]
You can read more about this https://devblogs.microsoft.com/aspnet/aspnetcore-2-1-identity-ui/
