### ISSUE TITLE
Question: Blazor and converting Line of Business (LOB) desktop apps to web apps

### ISSUE THREAD

**Issue by githubfanster** [aspnet/AspNetCore#14470]
Question: Blazor and converting Line of Business (LOB) desktop apps to web apps

We would like to convert our Line of Business (LOB) desktop apps to web apps, hopefully with the help of Blazor.

One concern we have is that users of our desktop apps are used to using the keyboard for navigation (i.e., using the tab or the arrow keys) and selection (enter key).

For a list component, for example, they are used to using the TAB and SHIFT-TAB keys for navigating the list items in opposite directions, respectively.

Most of the Blazor components we've seen do not support such keyboard-based navigation.  Those that do tend to just be wrappers for the underlying javascript implementations that do support such keyboard-based navigation (so why not just use the javascript implementations directly? also, sometimes in order to use JSInterop, the underlying javascript code needs to be rewritten to make it easier to use with Blazor, something we are not keen on doing if we can avoid it).

While we know that there are situations where using JSInterops cannot be avoided, we're trying to investigate how far we can go creating garden variety UI components (that support keyboard navigation) in Blazor without having to use javascript ourselves.

We started by prototyping a List component assuming the list items only need to display simple text or strings (complete code below).

One reason why many Blazor components currently do not support keyboard navigation is the additional work required. Most implementations use the div and ul html elements for the list container, and li for a list item. All these html elements first need to be made "focusable" by adding tabindex="0" attribute settings to them, which we do in our prototype.

Javascript implementations that support the use of keys for item selection (say, pressing the "Enter" key, for example) and navigation then go on to listen for key events and performing other (sometimes tedious) housekeeping tasks (such as where the key is currently located etc.).

Our Blazor List prototype bypasses some of these tedious housekeeping tasks by just having each list item directly listen to key events themselves, and for "Enter"-key-is-down-events, identify themselves (by passing their own specific ItemId) to the EventCallback method of their list container as the newly selected list item.  That EventCallback would then trigger a list re-render which correctly updates the list items' css classes indicating whether a list item is the newly selected item or not.

My questions are: 

(1) Does this approach really work (or are there serious downsides i need to be aware of)?  

(2) Our list prototype creates "only" 10 event listeners, one for each list item.  Is there such a thing as having too many event listeners in a web document? Can we use the same approach to support keyboard navigation and selection of individual cells in a table or grid (i.e., one event listener for each table cell), or that might not be a good idea?

(3) what might be a better approach (that's hopefully also not labor-intensive)?

Thank you for helping!

--------------------------------------------
CODE:

ListTextItem.razor

```
<li tabindex="0" 
    class="@CssClass"
    @onkeydown="@(async (e)=> await DoKeyDown(e, ItemId))">@Text</li>

@code {
    [Parameter] public int TabIndex { get; set; } = 0;
    [Parameter] public string CssClass { get; set; } = null;
    [Parameter] public RenderFragment ChildContent { get; set; }
    [Parameter] public string Text { get; set; } = "";
    [CascadingParameter] public ListContainer ListContainer { get; set; }
    [Parameter] public int ItemId { get; set; }
    [Parameter] public EventCallback<int> OnSelectionChanged { get; set; }

    protected async Task DoKeyDown(KeyboardEventArgs evt, int itemId)
    {
        switch(evt.Code)
        {
            case "Enter":
                await OnSelectionChanged.InvokeAsync(itemId);
                break;
            default:
                return;
        }

    }
}
```

ListContainer.razor
```
<div class="my-list-container">
    <CascadingValue Value="this">
        <ul class="my-liststyle-no-bullet">
            @{ 
                int j = 0;
                @foreach (var str in StringItems)
                {
                    j += 1;
                    <ListTextItem ItemId="@j"
                          CssClass="@SetItemCssClass(@j)"
                          Text="@str"
                          OnSelectionChanged="@HandleSelectedItemChanged">@j</ListTextItem>
                }
            }
        </ul>
    </CascadingValue>
</div>

@code {
    [Parameter] public List<string> StringItems { get; set; } = new List<string>();
    protected string ItemSelectedCssClass = "my-list-item-selected";
    protected int SelectedItemId { get; set; } = -1;

    protected string SetItemCssClass(int itemId)
    {
        return (itemId == SelectedItemId) ? ItemSelectedCssClass : null;
    }

    public void HandleSelectedItemChanged(int _selectedItemId)
    {
        SelectedItemId=_selectedItemId;
    }
}
```

Index.razor
```
@page "/list1"
<h3>List Demo</h3>
<ListContainer StringItems="@StringList"></ListContainer>

@code {
    protected List<string> StringList = new List<string>();

    protected override void OnInitialized()
    {
        StringList.AddRange(new List<string>()
        {
            "string1",
            "string2",
            "string3",
            "string4",
            "string5",
      
      "string6",
            "string7",
            "string8",
            "string9"
        });
    }
}
```

mylist.css

```
.my-liststyle-no-bullet {
    list-style-type: none;
    margin: 0;
    padding: 0;
}

.my-list-container {
    display: flex;
    flex-direction: column;
    margin: 10px;
    padding: 10px;
    width: 100px;
    border-width: 2px;
    border-style: solid;
}

.my-list-item-selected {
    background: rgb(0, 0, 255);
    color: white;
}

.my-list-item-not-selected {
    background: rgb(0, 0, 0);
    color: black;
}
```

**Comment by SteveSandersonMS** [comment]
> (1) Does this approach really work (or are there serious downsides i need to be aware of)?

Yes, using events to respond to keyboard input sounds right to me.

> (2) Our list prototype creates "only" 10 event listeners, one for each list item. Is there such a thing as having too many event listeners in a web document? Can we use the same approach to support keyboard navigation and selection of individual cells in a table or grid (i.e., one event listener for each table cell), or that might not be a good idea?

You'll have to try it to verify for sure that your UI perf scales in the way you need. However Blazor automatically uses event delegation for all event handlers, so even if you have a million `@onkeypress` registrations, it will only register a single native JavaScript event for `keypress`, and deals with dispatching callbacks to the right place in .NET for you.

> (3) what might be a better approach (that's hopefully also not labor-intensive)?

Your approach sounds fine.
