### ISSUE TITLE
asp.net Error Page Shows Incorrect Line Number

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14482]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/683848/aspnet-error-page-shows-incorrect-line-number.html)._

---
When debugging am ASP.NET website, error pages are displaying incorrect line numbers.

---
#### Visual Studio Feedback System on 8/8/2019, 11:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/8/2019, 11:18 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by anurse** [comment]
Can you provide a runnable sample application that reproduces the problem?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
