### ISSUE TITLE
Project templates need to be updated for 3.1

### ISSUE THREAD

**Issue by phenning** [aspnet/AspNetCore#14486]
Project templates need to be updated in the release/3.1 branch.
* identities should be updated from 3.0 to 3.1 
* precedence should be incremented to 6000

Until this is done, the 3.0 templates will be superceded by the 3.1 templates in Visual Studio. Additionally, you won't be able to install the 3.0 templates into the 3.1 template hive via dotnet new -i  template.3.0::version

### To Reproduce
1. Install 3.1 with Visual Studio 2019 16.3
2. Apply workaround to enable 3.1 template packages to load (contact @phenning for details)
3. Create a new ASP. NET Web Application (.NET Core) - Notice 3.0 is missing from the list.

### Expected behavior
Both 3.0 and 3.1 templates should be available in Visual Studio

**Comment by mkArtakMSFT** [comment]
Thanks @phenning. @ryanbrandenburg can you please handle this? Thanks!

**Comment by ajaybhargavb** [comment]
@mkArtakMSFT reassigning this back to @ryanbrandenburg because he missed that this was assigned to me and already sent a PR.
