### ISSUE TITLE
Bad responses: LinkAThonGrpcTrimmedAndR2R, LinkAThonGrpcTrimmedAndR2RSingleFile

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14496]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| LinkAThonGrpcTrimmedAndR2R | Linux, Physical, http, KestrelSockets | 9/27/19 1:39:45 AM +00:00 | 54466 |
| LinkAThonGrpcTrimmedAndR2RSingleFile | Linux, Physical, http, KestrelSockets | 9/27/19 1:41:25 AM +00:00 | 400998 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
@rynowak took a look at these, and they just don't work, it's not an issue with the benchmarks. Right now I could just disable them if we don't want to get notified by the bot.
