### ISSUE TITLE
Visual Studio 2019 Preview miss Blazor Template

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetCore#14498]
Clean new INstall of Visual Studio 2019 Preivew- with all updates

Create Blazor Server App

.Razor files are uncolored in edtor

Visual Studio installer dialog comes up- is already running-

closing dialog- see nothing happen

Starting Project "Missing asp.net core-modul for hosting … iis express" 
2nd machine everything works fine

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hannespreishuber.
This is not something runtime related. Please use VS Feedback to report this issue so the appropriate team can investigate this further.
