### ISSUE TITLE
Scenarios are not running: FortunesPostgreSql-Actix, Json-Actix, Plaintext-Actix

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14495]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| FortunesPostgreSql-Actix | Linux, Physical, http, KestrelSockets | 9/26/19 1:22:22 AM +00:00 |
| Json-Actix | Linux, Physical, http, KestrelSockets | 9/26/19 1:21:28 AM +00:00 |
| Plaintext-Actix | Linux, Physical, http, KestrelSockets | 9/26/19 1:20:37 AM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by Pilchie** [comment]
@sebastienros - can you clean up some of these "Scenario not running" issues.

**Comment by sebastienros** [comment]
Failing on the TechEmpower site too

https://github.com/TechEmpower/FrameworkBenchmarks/issues/5107

**Comment by sebastienros** [comment]
Fixed
