### ISSUE TITLE
Question: Is it a bug that dotnet new razorclasslib -s true

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore#14499]
... results in TargetFramework `netcoreapp3.0` while -s false results in `netstandard2.0`?

That means one version can be targeted by other netstandard projects, while the other one can not. Seems weird. Is this intentional?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @taori.
This change has been announced in the `Razor Class Library template replaces the Blazor Class Library template` section here: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/

> The Razor Class Library template is now setup for Razor component development by default and the Blazor Class Library template has been removed. New Razor Class Library projects target .NET Standard so they can be used from both Blazor Server and Blazor WebAssembly apps. To create a new Razor Class Library template that targets .NET Core and supports Pages and Views instead, select the “Support pages and views” option in Visual Studio, or pass the --support-pages-and-views option on the command-line.

Please let us know if you have more questions.

**Comment by taori** [comment]
@mkArtakMSFT Thanks for your answer. I see - but is it necessary that one of the options turns it into a netcoreapp3.0? That limits the reference choices. Previously a RCL was a netstandard library too and now it turns into a netcoreapp3.0. That just seems odd to me.

**Comment by mkArtakMSFT** [comment]
I do not know all the details, but there are good reasons for this to be the way it is. @pranavkm may be able to share more about this.
