### ISSUE TITLE
Question: How Do You Add A New Blazor .razor page?

### ISSUE THREAD

**Issue by DataJuggler** [aspnet/AspNetCore#14491]
I know how to copy an existing Blazor page, but if I click on the Pages folder in a Blazor project, the Add New Razor page gives me an error. 

Is this a bug, or I am not aware of the proper way of doing this?

![Add Razor Page](https://user-images.githubusercontent.com/26331133/65732216-68d0c100-e08e-11e9-83a0-051d96b5e882.png)
![Add New Blazor Page](https://user-images.githubusercontent.com/26331133/65732220-6bcbb180-e08e-11e9-8913-e6f199462c6f.png)

![Error](https://user-images.githubusercontent.com/26331133/65732249-9a498c80-e08e-11e9-8cc4-67e04b0dbf49.png)

It looks like this is all for MVC.

I remember this working on another project, and a .cshtml file was created.

I am using 16.3.1 version.

Thanks, I am making a video and I feel stupid saying 'Copy an existing .razor page and change it', but that is the only way I have found so far.

I admit I am guilty of not reading this silly thing called documentation because I am too busy writing open source software instead of looking for a job like I should be.

Thanks,

**Comment by DataJuggler** [comment]
I just reread the Blazor To Do Tutorial I had followed, and I realize this is the source of my confusion:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#build-a-todo-list

Build a todo list
Add a new component to the app that implements a simple todo list.

Add an empty file named Todo.razor to the app in the Pages folder:

It would be really nice if there was a Scafolded Item for this.

Am I supposed to add a Text file and rename it?

When I read that the first time I just took an existing file and replaced the content.

It seems like the Add Razor page when you have an entire directory of .razor files this is the logical thing to click.

Maybe if this is more clear other people won't be as confused as I still am.

Thanks

**Comment by MV10** [comment]
I always go to Add -> New Item -> Razor Component ... but I realize that isn't quite the same thing.

**Comment by DataJuggler** [comment]
I have never noticed Razor Component. I will look for it.

Thanks

**Comment by MV10** [comment]
For Blazor the only difference between a .razor page and a Razor Component is the `@page` directive... so if you're actually wanting a page, it's not much of a hassle. But the UI is certainly inconsistent in a lot of ways right now.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @DataJuggler.
This is something we track already and we're working on it. Unfortunately can't provide any ETAs on this at the moment.
