### ISSUE TITLE
Complete beginner help Getting started

### ISSUE THREAD

**Issue by iangorse** [aspnet/AspNetCore#14508]
Hi,

I would like to download the asp.net core source, so I can browse the code, make changes and see how it works.

My goal is to be able to right click a method in Visual Studio 2019, Goto Definition, and see the code behind the function ( for example, app.UseRouting() ). I am aware I can see this on github but having the ability to directly browse the source in my project is a massive benefit for me.

So my first thought was to download the Daily Builds using this [How to get daily builds of ASP.NET Core](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md)

However, I am not sure what I am supposed to be doing.

The steps I have taken are:
1. Freshly installed Visual Studio 2019
2. Created a new ASP.NET Core MVC 3.0 application
3. Installed latest build of .NET Core SDK
4. Created a nuget.config file and placed it in my Solution directory
5. Add the XML from the [Guide](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md) to this nuget.config file

My question is.... what next?

I opened up my new project but it's just my project. I don't see any asp.net core source code at all.
I feel like I am doing something wrong

**Comment by Pilchie** [comment]
Hi, 

The instructions that you followed allow you to use the *binaries* from the daily builds that we produce in our CI runs.  It doesn't set up you to reference the source directly.  Unfortunately, there isn't a good way of doing that right now.  The only way would be to tie your project into our build system which would add a lot of extra complexity.

I know the Visual Studio IDE team is working on being able to fetch source for OSS projects when Go To Definition is invoked, but my understanding is that that work isn't completed yet.

My recommendation at the moment would be either:

1. Continue browsing on GitHub.
2. Open one of the existing sample applications that are already part of our build process like [Music Store](https://github.com/aspnet/AspNetCore/blob/master/src/MusicStore/MusicStore.sln) for example.   Note that if you follow this approach, you'll need to install enough dependencies to be able to build ASP.NET Core from source.  See the [docs](https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md) for more information about doing that.

**Comment by iangorse** [comment]
Thank you very much for the clarification. I will follow your recommendation.
