### ISSUE TITLE
[Blazor Server] Component doesn't update (re-renders) until method execution completes

### ISSUE THREAD

**Issue by aventus13** [aspnet/AspNetCore#14507]
**Problem Description**
I'm writing a search functionality where search logic executes upon clicking a button. In order to disable searching while the existing search runs, I'm using an `isSearching` boolean variable which determines whether disabled or enabled button is rendered. Changing `isSearching` to `true` doesn't however affect rendering of the component, as it doesn't re-render until the `FindClicked` method completes. I found a [workaround ](https://stackoverflow.com/a/56675814) however this seems hacky. Should Blazor not handle this automatically and/or is there a recommended approach to this scenario other than invoking `Task.Delay`?

**Code Example**
_Search.razor_
```
@if (isSearching)
    {
        <button @onclick="FindClicked" class="btn btn-outline-primary float-right w-25" disabled>FIND</button>
    }
    else
    {
        <button @onclick="FindClicked" class="btn btn-outline-primary float-right w-25">FIND</button>
    }`

@code {
    private SearchCategory searchCategory;
    private string keyword;
    private bool isSearching;

    [Parameter]
    public SearchResult SearchResult { get; set; } = new SearchResult(SearchCategory.LookupCode, string.Empty);
    [Parameter]
    public EventCallback<SearchResult> SearchResultChanged { get; set; }

    private async Task FindClicked()
    {
        if (string.IsNullOrWhiteSpace(keyword))
        {
            SearchResult = new SearchResult(searchCategory, string.Empty);
            return;
        }

        if (searchCategory == SearchResult.Category && keyword == SearchResult.Keyword)
            return;

        isSearching = true;
        //await Task.Delay(1); The workaround
        var searchService = SearchServiceFactory.Create(searchCategory);
        SearchResult = await searchService.Find(keyword);
        await SearchResultChanged.InvokeAsync(SearchResult);
        isSearching = false;
    }
}
```
**.Net Core version 3.0**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @aventus13.
This is actually by-design. This is because the methis is completing synchronously.
If you want to force a yielding await you can use `Task.Yield()` instead.
