### ISSUE TITLE
[FEATURE][QUESTION] AspNetCore server, choose port range and strategy for the host

### ISSUE THREAD

**Issue by tebeco** [aspnet/AspNetCore#14502]
Hello,

As i am trying to debug distrubed lock / cluster feature, i am trying to run the exact same `csproj` by running either :
* Multiple `dotnet run` in multiple host
* It could also be multiple `Services/Systemd` running on the same host 
* Vs2019 > `Sln Explorer` > right click > `Debug` > `Start new instance`
* A single `F5` would be amazing

The main issue here is that, i could not find a way in the `Kestrel/Listen/Http(s)Options` to handle a `Range` of `port` or a `PortSelectorStrategy` (Kinda like the `ReconnectBackoff` of `signalr` client)

#### Idea 1
In `launchSettings.json` / `"applicationUrl": "http://localhost:5000;https://localhost:5001"`
it's probably a bad design but it gives a small idea :
```
"applicationUrlBackOff":
  [
    "http://localhost:5000;https://localhost:5001",
    "http://localhost:5002;https://localhost:5003"
    "http://localhost:5004"
  ]
```

The idea here is that
* it will first try to bind `http:5000+https:5001`
* if at least one fail, it tries to bind to `http:5002+https:5003`
* if at least one fail, it tries to bind to `http:5004`
* Then classic fail

##### Additional context
Why ?
Because when running "Micro-service" this part is handled by an orchestrator for you like Fabric / Aks / Local Kub / ....
The issue is that when you try to debug it on a computer you have the choise to either :
* `dotnet publish` + run it (no debug)
* multiple `dotnet run` + injecting `Console Args` to attempt to override configuration (not easy)
Both scenario means that you often give up on the `IDE Debbugger`
* You can also use the `::0` port binding but then it's totally random (not always easy for complex scenario when you need to perform incoming `HttpClient request` (you now needs "service discovery" locally)
* Antoher possibility is to add a Huge `Try/Catch` arround the `CreateHostBuilder/build/Start/Run` and manually attempt the Fallback

#### Idea 2 :
In combination with the previous idea (or not, could work for console app too):
This idea is to press `F5` only once in order to run + Attach `Debugger` the same project `n` times
For example it could be an `integer` in the `launchSettings.json` like :
`"instanceCount" : 3`

It would allow an easy way to debug a small "distributed/cluster" like application (See Idea 1)

### Additionnal info
Here is a very fast draft i made in order to do that :
Pretty sure it's full of bug and weird scenario, still gives an idea ;)

```
using System;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;

namespace Foo
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var urlFallback = new UrlFallbackOptions
            {
                UrlsFallbacks = new[]
                {
                    ListeningUrls.Default,
                    new ListeningUrls { Urls = new []{ "http://localhost:5002", "https://localhost:5003" } }
                }
            };

            CreateWebHostBuilderWithFallback(args, urlFallback);
        }

        public static void CreateWebHostBuilderWithFallback(string[] args, UrlFallbackOptions urlFallbackOptions)
        {
            for (var i = 0; i < urlFallbackOptions.UrlsFallbacks.Length; i++)
            {
                try
                {
                    CreateWebHostBuilder(args, urlFallbackOptions.UrlsFallbacks[i]).Build().Run();
                    break;
                }
                catch
                {
                    if (i == urlFallbackOptions.UrlsFallbacks.Length - 1)
                    {
                        throw new Exception("you dead");
                    }
                }
            }
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args, ListeningUrls listeningUrls) =>
            WebHost.CreateDefaultBuilder(args)
                .UseUrls(listeningUrls.Urls)
                .UseStartup<Startup>();
    }

    public class UrlFallbackOptions
    {
        public ListeningUrls[] UrlsFallbacks { get; set; } = new[] { ListeningUrls.Default };
    }

    public class ListeningUrls
    {
        public static readonly string[] DefaultUrls = new[] { "http://localhost:5000", "https://localhost:5001" };

        public static readonly ListeningUrls Default = new ListeningUrls { Urls = DefaultUrls };

        public string[] Urls { get; set; } = DefaultUrls;
    }
}
```

**Comment by tebeco** [comment]
As you can see the code is still `netcoreapp2.2`, i wonder if it's easier now with the double stack of `IHostBuilder` containing `IWebHostBuilder`

**Comment by anurse** [comment]
This is a pretty major feature and I don't think we plan to add such a thing to Kestrel. There are some options available such as wrapping the `IServer`. We also support binding to port `0` which will select any free port and the actual chosen port will be available on the `IServerAddressesFeature` in the server features collection. You can access that collection via the `IApplicationBuilder` interface in your `Startup.Configure` method.

**Comment by tebeco** [comment]
Yep, it's a major one, i do understand ;)
I also use the binding to port 0 port resolution + `IServerAddressesFeature` in order to run E2E / IntegrationTest.

I just asked to know if it was planned or could have been planned.
The main "issue" i'm trying to solve is the fact that i have to attach multiple times the same "Host" to the same instance of Vs or VsCode, and so far it's either a hack, like the bind to `0` (not really optimal but kind of do the job)

I was just curious about such a feature (a proper "Cluster" notion)

Thx for your time ;)

**Comment by anurse** [comment]
It's certainly a viable feature to add to a server, but I closed it primarily because to be honest I don't see us being able to spend the time to do it. We could backlog it, but that wouldn't be particularly honest because I think it would just sit there never getting pulled up :).

> i have to attach multiple times the same "Host" to the same instance of Vs or VsCode, and so far it's either a hack, like the bind to `0` (not really optimal but kind of do the job)

I'm not sure I fully understand what you mean here by "Host" or attaching to VS/VSCode. Are you trying to run multiple instances of the same app?

**Comment by tebeco** [comment]
Don't worry, i'm totally fine with it closed, as said i was primarily looking for info

> I'm not sure I fully understand what you mean here by "Host" or attaching to VS/VSCode. Are you trying to run multiple instances of the same app?

Yup the exact same bit with "n" instance, like a "distributed service"
I think when i opened the issue i was trying to debug a custom `Polly` policy trying to get a `DistributedLock` over a `BlobStorage`

The consuming app need to be ran multiple time and multiple kill / restart to see how healthcheck behave, who retry and when etc ....
Tested code is in a `classlib` so it felt weird to just create a new (almost) empty host project (`dotnet new webapi`)

And now ... i even wonder how Vs would react if i kill one the instance like ... would it kill all debugger etc ...

i think i'll just create an empty host next time and use multiple startup project

**Comment by anurse** [comment]
It seems like this might be a useful suggestion for VS rather than trying to hack around it. You can do this today as you note in your original post, but it's a little complicated. Might be a good suggestion to propose to VS to add a feature for this (though I don't know exactly what that would look like).

**Comment by tebeco** [comment]
I think it would probably make sense as part of `launchSettings.json` as the `idea 2` suggest but it would required that other template have something equivalent
it's only part of `web` "things" for now

also i posted here because running instances ends up being linked to `port binding`
the only way possible then is ... either using 0 or have a fallback list policy (kinda like the signalr reconnect policy)
this still leaves a question here is you need specific port but it's really not much important i think

also i'm not sure where to raise the idea for Vs, feedback hub only ?
