### ISSUE TITLE
Question: Plans on migrating TestServer to use HostBuilder instead of WebHostBuilder?

### ISSUE THREAD

**Issue by johanhugg** [aspnet/AspNetCore#14506]
### Is your feature request related to a problem? Please describe.
We were upgrading our 2.2 template to 3.0 and we use both F# and C#. C# was pretty much painless. 

However we use F# in a way that is not reliant on classes in our startup and configuration.

In our tests we use the TestServer get an HttpClient, now when we've migrated to use HostBuilder, it doesn't work. Migrating to WebApplicationFactory<T> was the solution we found (since that is what we use in C# for the integrationtests as well).

### Describe the solution you'd like
I'd like to be able to use the TestServer with HostBuilder since that way we can use it in our tests without having to create classes (that is only used for WebApplicationFactory).

Would be nice to know if you guys have plans on keeping TestServer updated or abandoning it :).

**Comment by Tratcher** [comment]
What doesn't work? HostBuilder support was already added in 3.0, it was just structured differently:
https://github.com/aspnet/AspNetCore/commit/241d2c13df468d18149f2245efb0d6dbcfc7a60d#diff-b10e2dc62f53c21fa88d265eefe8a17cR46-R73

**Comment by johanhugg** [comment]
I'll add a code example

`let client = (new TestServer(configureBuilder())).CreateClient()`
Where configureBuilder is in the "main" project (and the above code is in the testproject)

Obviously that doesn't work anymore, I guess my question now is there a way to more functionally use TestServer and retrieve the HttpClient?

**Comment by johanhugg** [comment]
`let client = (configureBuilder().ConfigureWebHost(fun webHostBuilder -> webHostBuilder.UseTestServer() |> ignore)).Start().GetTestClient();`

This became the solution for us, thanks for the example!
