### ISSUE TITLE
Bind Nullable InputCheckbox

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetCore#14500]
<InputCheckbox @bind-Value="item.bAbo" />

bAbo is bool?

have read there have been a discussion about that topic, but lost the result

Should work - doesnt compile on my machine 
Blazor final

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hannespreishuber.
The `InputCheckbox` doesn't support `bool?` because `null` cannot be represented in an HTML checkbox element.
