### ISSUE TITLE
IHttpContextAccessor and IHttpContextFactory are missing a description

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14516]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/750471/ihttpcontextaccessor-and-ihttpcontextfactory-are-m.html)._

---
The interfaces **IHttpContextAccessor** and **IHttpContextFactory** are missing a description (as opposed to **IHttpClientFactory** which does have a description).

---
#### Visual Studio Feedback System on 9/27/2019, 00:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/27/2019, 01:26 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by anurse** [comment]
Yep, it looks like the [`IHttpContextAccessor`](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Abstractions/src/IHttpContextAccessor.cs) and [`IHttpContextFactory`](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Abstractions/src/IHttpContextFactory.cs) interfaces are indeed missing XML docs.
