### ISSUE TITLE
AllowedUserNameCharacters should use regex instead

### ISSUE THREAD

**Issue by Trojaner** [aspnet/AspNetCore#14511]
### Is your feature request related to a problem? Please describe.
For username constraints ASP.NET Core Identity provides AllowedUserNameCharacters which is a string consisting of the allowed characters. My problem is that I want to allow *any* valid unicode characters. It would be ridicilous to fill this string with all available unicode characters.

### Describe the solution you'd like
AllowedUserNameCharacters should have a regex equivalant or an option to allow anything.

Edit: it seems like that setting AllowedUserNameCharacters to `null` makes it accept any characters. However, this is not documented anywhere.

**Comment by blowdart** [comment]
We avoid regular expressions due to their security implications. You can of course write your own validator and configure it, but it's not one we're going to provide for you.
