### ISSUE TITLE
[Blazor] Adding a Blazor page named Task.razor breaks compilation

### ISSUE THREAD

**Issue by akorchev** [aspnet/AspNetCore#14510]
### Describe the bug

Blazor application created from the default blazorserver template fails to compile if it contains a page called Task.razor.

### To Reproduce

1. Using official .NET Core 3.0 create a new blazor server application by running `dotnet new blazorserver -o BlazorApp1`
2. Add a new page called `Task.razor`.
3. Try to run the application
4. See the following compilation error:

```
FetchData.razor(42,35): error CS1983: The return type of an async method must be void, Task, Task<T>, a task-like type, IAsyncEnumerable<T>, or IAsyncEnumerator<T>
FetchData.razor(42,35): error CS0508: 'FetchData.OnInitializedAsync()': return type must be 'Task' to match overridden member 'ComponentBase.OnInitializedAsync()'  
```

### Expected behavior
Should probably build without errors.

### Additional context

This compilation error occurs because `Task.razor` transforms to a class 

```
namespace BlazorApp1.Page
{
     public class Task : Microsoft.AspNetCore.Components.ComponentBase
     {
     }
}
```

This class in turn "shadows" `System.Threading.Tasks.Task` which is used in `FetchData.razor`. 

Similar error happens if one creates a page called `DateTime.razor`:

```
FetchData.razor(44,69): error CS0117: 'DateTime' does not contain a definition for 'Now' 
```

### Possible fixes:
1. Rename the file. Easy to do. Finding what causes the compilation error is not obvious though.
2. Use fully qualified types or alias them to avoid the conflict. Inconvenient.
3. Generate a backing class name that is less likely to clash with .NET framework classes or application defined types. Something like `TaskComponent`, `TaskRazor` etc.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @akorchev.
This is not Blazor specific. The issue will happen in other projects types too. Simply use a different name for the class/component and that will solve the problem.

**Comment by akorchev** [comment]
I am sorry but I think the issue is Blazor specific. I am creating a file called Task.razor and not a class called Task. The Blazor compiler creates a class that conflicts with System.Threading.Tasks.Task. Please reconsider.
