### ISSUE TITLE
Question - Open source ElectronBlazor prototype copied code legal implications

### ISSUE THREAD

**Issue by sanosdole** [aspnet/AspNetCore#14513]
I have a working protoype of a native node addon that hosts the core clr and enables bi-directional calls between node and dotnet.
This prototype also includes an implementation of hosting a Blazor application in a Electron renderer process, which required copying some internal c# and typescript code from the AspNetCore repository.

Now i want to publish the prototype on GitHub as an open source project.
I thought of using the MIT License, but I have no objection to switching to the Apache license used by AspNetCore.

_Are there any (especially legal) concerns from you regarding publishing the copied code?_
Would it be enough to add a note to the readme and the copied files?

I am aware that Microsoft is pursuing a similar implementation itself, and that this will probably make the Blazor hosting from my project obsolete. But its timeline conflicts with my clients schedule as we want to start migrating our projects to Electron/Blazor before you are able to publish your Version.

If you have any rejections i could also extract the Blazor hosting part and just publish the node hosting part as open source.

If you need some more details or access to the repository on GitHub just ask me.

In case that asking this using an Issue is the wrong approach to asking this, i`m sorry and would you please tell me where to ask this question instead.

**Comment by danroth27** [comment]
Hi @sanosdole,

I'll do my best to answer your question, but please note that this response should not be considered legal advice, as I am not a lawyer.

The code in the aspnetcore repository is open source under the [Apache v2.0 license](https://github.com/aspnet/AspNetCore/blob/master/LICENSE.txt). So you are welcome to use and redistribute the source code as part of your project under the conditions stated in that license (i.e. include a copy of the license, provide attribution, etc.).

Good luck!
