### ISSUE TITLE
gRpc error "stream removed"

### ISSUE THREAD

**Issue by carlossanlop** [aspnet/AspNetCore#14526]
_From @svdemir on Monday, July 29, 2019 8:01:48 PM_

# gRpc error "stream removed"

# General

Hi i am vscode netCore 3.0p7 use. grpc create template and project run.
client apps  "stream removed"  I get the error. 

![grpcError](https://user-images.githubusercontent.com/28478219/62078156-9b0f9f00-b254-11e9-9e1e-b333b83b271b.JPG)

I think there's a problem with the template.

because netCore30p7 does not manually get the error in the console application

_Copied from original issue: dotnet/core#3113_

**Comment by carlossanlop** [comment]
_From @carlossanlop on Monday, August 12, 2019 9:53:03 PM_

@dagood @livarcocc @nguerrera do you know who can help with this?

**Comment by carlossanlop** [comment]
_From @dagood on Monday, August 12, 2019 10:56:51 PM_

A quick search suggests this has to do with ASP.NET Core.

@svdemir, I'd suggest copying the text as text rather than posting a screenshot--makes it searchable, and much more readable.

**Comment by carlossanlop** [comment]
_From @carlossanlop on Tuesday, August 13, 2019 5:48:57 PM_

> 
>
> A quick search suggests this has to do with ASP.NET Core.

@Pilchie can you please help with this issue?

**Comment by carlossanlop** [comment]
_From @Pilchie on Tuesday, August 13, 2019 5:51:20 PM_

@JamesNK / @shirhatti / @JunTaoLuo - any ideas?

**Comment by carlossanlop** [comment]
_From @shirhatti on Tuesday, August 13, 2019 6:04:35 PM_

My naive guess is that your client isn't using TLS while your server is, but I can't be certain without looking at the offending code.

Can you share your client code?

**Comment by carlossanlop** [comment]
_From @dingzeng on Saturday, August 31, 2019 2:43:07 PM_

I also have this problem

see:[https://github.com/dingzeng/AspnetcoreGrpcDemo/tree/stream_removed](https://github.com/dingzeng/AspnetcoreGrpcDemo/tree/stream_removed)

**Comment by JamesNK** [comment]
1. You're using the Grpc.Core client. We recommend you use the Grpc.Net.Client when on .NET Core 3 - https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.0
2. You have a mismatch between client and server TLS configuration - https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#mismatch-between-client-and-service-ssltls-configuration

**Comment by JamesNK** [comment]
Closing this as answered. If you still have problems please add a comment with an update and we can reopen.
