### ISSUE TITLE
Bug Referencing Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation in Class Library

### ISSUE THREAD

**Issue by nfplee** [aspnet/AspNetCore#14525]
If you have a class library with the following package reference:

`<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.0.0" />`

This will throw the error:

> InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery

See the attached sample for an example. To fix it you need to add the above reference to the Sample.Web project.

[Sample.zip](https://github.com/aspnet/AspNetCore/files/3663979/Sample.zip)

**Comment by pranavkm** [comment]
I suspect this is causes by this - https://github.com/aspnet/AspNetCore/issues/12768. `PreserveCompilationReferences` that the runtime compilation package sets up isn't transitively available.

In the meanwhile, you could

a) set the property `<PreserveCompilationReferences>true</PreserveCompilationReferences>` in the primary project file
b) reference the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` in the main project (as you noted)

**Comment by pranavkm** [comment]
I'm going to close this since  #12768 is already tracking resolving this.

**Comment by nfplee** [comment]
Thanks. a didn't work but I'll stick with b for now.
