### ISSUE TITLE
CSRF token not regenerated on logout/login

### ISSUE THREAD

**Issue by collinsauve** [aspnet/AspNetCore#14520]
### Describe the bug
The CSRF antiforgery token is not regenerated automatically on logout or login.  

### To Reproduce
1. Using ASP.NET Core '2.2.0'
2. Decorate login controllers with `ValidateAntiForgeryToken`
3. Load login page, unauthenticated.
4. Note the `.AspNetCore.Antiforgery.*` cookie that is set
5. Login to application
6. Note that the antiforgery cookie is not changed
7. Logout of the application
8. Note that the antiforgery cookie is not changed.

### Expected behavior
Antiforgery cookie should be regenerated at login/logout.

### Screenshots
I can provide a fiddler capture is needed, but is a non-trivial amount of work to redact it properly.

### Additional context
Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by collinsauve** [comment]
Was originally filed on https://github.com/aspnet/AspNetCore/issues/2757 but was closed with "should work otherwise lots of people would be broken".  With issues like these most people won't notice.

**Comment by blowdart** [comment]
Where are you noting it's not regenerated? Where does your logout go - static page, or a page with a form? Is this a spa?

**Comment by collinsauve** [comment]
I am using Fiddler to capture the requests and token is the same from unauthed to authed to unauthed again.

Logout goes to an MVC controler with a View.  Login domain is not an SPA.

**Comment by blowdart** [comment]
That's odd, it should change when you login, and then change when you logout, because it uses the username in the value. What authentication are you using?

**Comment by collinsauve** [comment]
We use Identity, specifically ApplicationCookie auth using [ConfigureApplicationCookie](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Core/src/IdentityServiceCollectionExtensions.cs#L110).

In the test case I was I used password auth for one user and external (Google) auth for the second one.   

Perhaps I should attempt to reproduce with a sample repo somewhere?

**Comment by blowdart** [comment]
If you could that would be wonderful. It all seems pretty standard though.

**Comment by collinsauve** [comment]
Okay I repro'd with [this sample](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/security/authentication/identity/sample/src/ASPNETCore-IdentityDemoComplete/IdentityDemo)

1. Create 2 users (test1@test.com and test2@test.com)
2. Logout of both users, clear cookies, start capturing in Fiddler (this is where the below saz begins)
3. Refresh the login form (request 90)
4. Login to test1@test.com (request 121)
5. Logout (request 136)
6. Login to test2@test.com (request 171)

Note in below Fiddler capture the only `Set-Cookie: .AspNetCore.Antiforgery.*` response header is in request 90 when login form is loaded for the first time.  Cookie is never set again, and at the end when logged in to the second user the value is the same in request 172.

[AspNetCore-issue-14520.zip](https://github.com/aspnet/AspNetCore/files/3664227/AspNetCore-issue-14520.zip)

**Comment by blowdart** [comment]
@pranavkm does this fall to you?

**Comment by GrabYourPitchforks** [comment]
Possible dupe of https://github.com/aspnet/AspNetCore/issues/14521? If so this behavior is intentional, as the anti-CSRF token is split into two components: a cookie and a form field. The cookie is quite literally just a random value and is not tied to the user. The form field ties this random value to the current logged in user, and it is regenerated on every request.

**Comment by collinsauve** [comment]
Is there documentation somewhere on how this implementation works, or discussion of its robustness?  This seems to diverge from standard practices such as the [OWASP CSRF Prevention Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html).

We need to be able to both validate and justify to our customers and security researchers that this approach is robust.  Without an industry standard to point to this is difficult.

**Comment by GrabYourPitchforks** [comment]
The implementation is documented at https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/xsrfcsrf-prevention-in-aspnet-mvc-and-web-pages. That documentation also discusses configuration settings and ways that you can extend the system to embed further information into the CSRF prevention tokens.

That doc is for ASP.NET Web Pages for .NET Framework, but generally the same implementation is used in ASP.NET Core.

**Comment by collinsauve** [comment]
Thanks! I'll have a read over that.
