### ISSUE TITLE
WorkerService dependency injection DBContext, not working

### ISSUE THREAD

**Issue by Phylum123** [aspnet/AspNetCore#14532]
Hey guys, I wrote a worker service and the dependency injection is very similar to regular ASP core, thanks for that :). However, there is one piece that does not work for me. Below you will find code with a work around, however, if I uncomment the code (var ctx = r.GetRequiredService<MHedgeContext>();) and try to use the injected context, I am told that it is not found despite having registered it, using AddDbContext.:

```
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseWindowsService()
                .ConfigureLogging(loggerFactory => loggerFactory.AddEventLog())
                .ConfigureServices((hostContext, services) =>
                {
                    //TODO: figure out how to read appsettings.json and put it in here.
                    services.AddDbContext<MHedgeContext>(options =>
                        options.UseSqlServer("<ConnectionString>"));

                    services.AddTransient<IBondsRepository, BondsRepository>((r) =>
                    {
                        //var ctx = r.GetRequiredService<MHedgeContext>();

                        var optionsBuilder = new DbContextOptionsBuilder<MHedgeContext>();
                        optionsBuilder.UseSqlServer("<ConnectionString>");

                        return new BondsRepository(new MHedgeContext(optionsBuilder.Options));
                    });

                    services.AddTransient<IAdminRepository, AdminRepository>((r) =>
                    {
                        //var ctx = r.GetRequiredService<MHedgeContext>();
 
                        var optionsBuilder = new DbContextOptionsBuilder<MHedgeContext>();
                        optionsBuilder.UseSqlServer("<ConnectionString>");

                        return new AdminRepository(new MHedgeContext(optionsBuilder.Options));
                    });

                    services.AddHostedService<Worker>();
                });
    }
```

**Comment by Tratcher** [comment]
These services are all being injected into your Worker?

One problem you'll have is that AddDbContext registers services as scoped, but Worker is not created within a DI scope.

**Comment by anurse** [comment]
Yep, @Tratcher is right, since the DbContext is a scoped service, it's not trivial to resolve it. You have to create a DI scope and resolve out of this (we do that per-request for you but in a hosted service you have to do it).

We have docs on this here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task

If that doesn't fix the issue, let us know.

**Comment by anurse** [comment]
Closing as we believe the issue to be resolved. Let us know if you still encounter issues!

**Comment by MaximTs** [comment]
@Phylum123 

Thanks for workaround.
I tried hard to find a solution, but in vain.
