### ISSUE TITLE
Blazor component - no intellisense in the immediate window?

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#14533]
![image](https://user-images.githubusercontent.com/8482283/65796662-7dd05180-e16d-11e9-979b-4364b9cc9d61.png)

Once the breakpoint is hit - inside the immediate window I get no intellisense.

![image](https://user-images.githubusercontent.com/8482283/65796852-fe8f4d80-e16d-11e9-89fe-8992eae35d51.png)

( Using Visual Studio 2019 16.4 )

Is this supposed to work?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the VS Feedback to report this issue, so the team who owns the area can track the ask.
