### ISSUE TITLE
Client.Services.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14536]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/391474/clientservicesexe-framework-version-v4030319-descr.html)._

---
<p>While running our ClientService.exe(.net core) service stopped and error logged as below</p><p>Framework Version: v4.0.30319</p><p>Description: The process was terminated due to an
unhandled exception.</p><p>Exception Info: Newtonsoft.Json.JsonReaderException</p><p>  at Newtonsoft.Json.JsonTextReader.ParseValue()</p><p>  at
Newtonsoft.Json.JsonTextReader.Read()</p><p>  at
Newtonsoft.Json.Linq.JObject.Load(Newtonsoft.Json.JsonReader,
Newtonsoft.Json.Linq.JsonLoadSettings)</p><p>  at
Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(System.IO.Stream)</p><p>  at
Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(System.IO.Stream)</p><p>Exception Info: System.FormatException</p><p>  at
Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(System.IO.Stream)</p><p>  at
Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)</p><p>  at
Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()</p><p>  at
Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(System.Collections.Generic.IList`1&lt;Microsoft.Extensions.Configuration.IConfigurationProvider&gt;)</p><p>  at
Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()</p><p>  at
CST.Client.Services.Startup..ctor(Microsoft.AspNetCore.Hosting.IHostingEnvironment)</p><p>  at
Microsoft.Extensions.Internal.ActivatorUtilities+ConstructorMatcher.CreateInstance(System.IServiceProvider)</p><p>  at
Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(System.IServiceProvider,
System.Type, System.Object[])</p><p>  at
Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance(System.IServiceProvider,
System.Type)</p><p>  at
Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(System.IServiceProvider,
System.Type, System.String)</p><p>  at
Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions+&lt;&gt;c__DisplayClass1_0.&lt;UseStartup&gt;b__1(System.IServiceProvider)</p><p>  at
Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider)</p><p>  at
Microsoft.Extensions.DependencyInjection.ServiceProvider+ScopedCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider)</p><p>  at
Microsoft.Extensions.DependencyInjection.ServiceProvider+SingletonCallSite.Invoke(Microsoft.Extensions.DependencyInjection.ServiceProvider)</p><p>  at
Microsoft.Extensions.DependencyInjection.ServiceProvider+&lt;&gt;c__DisplayClass12_0.&lt;RealizeService&gt;b__0(Microsoft.Extensions.DependencyInjection.ServiceProvider)</p><p>  at
Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type)</p><p>  at
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider,
System.Type)</p><p>  at
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[[System.__Canon,
mscorlib, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]](System.IServiceProvider)</p><p>  at
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()</p><p>  at
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()</p><p>  at
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()</p><p>  at
Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()</p><p>at
CST.Client.Services.Program.Main(System.String[])</p>

---
#### Vidyadhar Daduwai on 11/26/2018, 04:51 AM: 

<p>Our web service is built using .net core and while running its .exe on Windows10 it stops service with unhandled excecption of Newtonsoft.json</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like this is exception is happening at application startup.
Your application configuration file seems to contain a malformed JSON content, which causes this error.
If this is still and issue and you don't believe that's the case, please share a minimalistic repro project with showcasing the problem, so that we can investigate this further.
