### ISSUE TITLE
Missing namespace: Microsoft.AspNetCore.Mvc.Razor.Extensions.NamespaceDirective

### ISSUE THREAD

**Issue by joetherod** [aspnet/AspNetCore#14537]
Missing namespace: Microsoft.AspNetCore.Mvc.Razor.Extensions.NamespaceDirective

Getting this error:
Could not load type 'Microsoft.AspNetCore.Mvc.Razor.Extensions.NamespaceDirective' from assembly 'Microsoft.AspNetCore.Mvc.Razor.Extensions, Version=3.0.0.0,

What is the alternative in 3.0 to get pass this error?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @joetherod.
@ajaybhargavb can you please look into this? Thanks!

**Comment by ajaybhargavb** [comment]
@joetherod `NamespaceDirective` was moved to `Microsoft.AspNetCore.Razor.Language.Extensions` namespace in 3.0.
