### ISSUE TITLE
Blazor renaming injected services is not working

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#14549]
Using the default template:

Navigate to FetchData.razor file and try to rename the injected service: Nothing is renamed.

![image](https://user-images.githubusercontent.com/8482283/65815616-1f998200-e1f2-11e9-968b-a0d0a9ab13f2.png)

( Using Visual Studio 2019 16.4 )

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Postlagerkarte.
We're tracking this work as part of #10480
