### ISSUE TITLE
asp.net core signalr client issue with xamarin.forms

### ISSUE THREAD

**Issue by azizkazdal** [aspnet/AspNetCore#14543]
Hi,
In my xamarin forms project using Asp.Net Core SignalR version 1.1.0.
When I try to update to version 3.0.0 I am getting white screen can not access to login page.
All package that using at project are below

```
<PackageReference Include="Microsoft.AspNetCore.SignalR.Client">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory">
      <Version>3.0.0</Version>
    </PackageReference>
    <PackageReference Include="NdefLibrary">
      <Version>4.1.0</Version>
    </PackageReference>
    <PackageReference Include="Prism.Core">
      <Version>7.2.0.1367</Version>
    </PackageReference>
    <PackageReference Include="Prism.Forms">
      <Version>7.2.0.1367</Version>
    </PackageReference>
    <PackageReference Include="Prism.Plugin.Popups">
      <Version>7.2.0.573</Version>
    </PackageReference>
    <PackageReference Include="Prism.Unity.Forms">
      <Version>7.2.0.1367</Version>
    </PackageReference>
    <PackageReference Include="Rg.Plugins.Popup">
      <Version>1.1.5.188</Version>
    </PackageReference>
    <PackageReference Include="System.Buffers">
      <Version>4.5.0</Version>
    </PackageReference>
    <PackageReference Include="System.Memory">
      <Version>4.5.3</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugins.Notifier">
      <Version>3.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.v4" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Essentials">
      <Version>1.3.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms" Version="4.2.0.815419" />
    <PackageReference Include="Xamarin.Forms.Visual.Material">
      <Version>4.2.0.815419</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.HotReload">
      <Version>1.4.19</Version>
    </PackageReference>
    <PackageReference Include="ZXing.Net.Mobile">
      <Version>2.4.1</Version>
    </PackageReference>
    <PackageReference Include="ZXing.Net.Mobile.Forms">
      <Version>2.4.1</Version>
    </PackageReference>
```

**Comment by Eilon** [comment]
Are you able to run the app with the debugger, set to catch all exceptions, and see if there's an exception being thrown?

There have been many API changes and probably various breaking changes between ASP.NET Core SignalR Core 1.1 and 3.0, so there could be some change in usage.

Also, can you show examples of how your app is using SignalR? That might help narrow down why you're seeing this problem.

**Comment by azizkazdal** [comment]
No I can not event run it with the debugger. So no exception thrown.

this is the code block where I connect SignalR API and I also made the changes at here [signalr]. (https://docs.microsoft.com/en-US/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#signalr-1) using NewtonJson 

```

async void RunInMainThread()
        {
            // Code to run on the main thread
            var ip = "localhost";
            if (Device.RuntimePlatform == Device.Android)
                ip = ApplicationSettings.ExternalApiCorporateConnection;

            if (ApplicationSettings.HubConnection == null || ApplicationSettings.HubConnection.State == HubConnectionState.Disconnected)
            {
                ApplicationSettings.HubConnection = new HubConnectionBuilder()
                            .WithUrl($"{ip}/notification", options =>
                            {
                                options.AccessTokenProvider = () => Task.FromResult(ApplicationSettings.SignalRToken);

                            }).AddNewtonsoftJsonProtocol()
                            .Build();
                await Connect();

                ApplicationSettings.HubConnection.On<string>("RequestAssignment", (message) =>
                {
                    try
                    {
                        var finalMessage = $"{message}";

                        Device.BeginInvokeOnMainThread(() =>
                        {
                            // Write your code here
                            DialogService.DisplayAlertAsync("BİLGİ", message, "TAMAM");
                            CrossLocalNotifications.Current.Show("BİLGİ",message,101,DateTime.Now.AddSeconds(3));
                            //DependencyService.Get<IToastMessageService>().LongAlert(message);
                        });
                    }
                    catch (Exception ex)
                    {
                        var tt = ex;
                        throw;
                    }
                });
            }
        }
```

**Comment by BrennanConroy** [comment]
Running with the debugger or at least getting the exception (if there is one) would be very helpful.

Could you also enable logs on the client and server and share them? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.0

**Comment by azizkazdal** [comment]
I added debug option both xamarin form and server but can not see any action on debug window. App even doest not make http call for SignalR connection. application does not fire up login page view model (using prism forms). On the startup app is entering only login page CTOR but login page viewmodel. If I get back the SignalR update its working fine. I am so confused so I removed SignalR for now.

**Comment by anurse** [comment]
I think we need to know more about what the actual error is. We're not aware of an issue here, though one may certainly exist.

Can you provide a simple runnable sample project that reproduces the problem?

**Comment by Eilon** [comment]
In general, in Xamarin, you should be able to catch _all_ exceptions if you set this setting:

![image](https://user-images.githubusercontent.com/202643/66007911-1e25bf00-e469-11e9-91a8-6bd422d67744.png)

Works fine for me on Windows in the Android emulator.

**Comment by azizkazdal** [comment]
Re-added signalr and got some error as below but there is no **Microsoft.AspNetCore.Http.Features, Version=2.2.0.0** reference project in any my projects

```
System.TypeLoadException: 'Could not load type of field 
'Microsoft.AspNetCore.Http.Features.Authentication.HttpAuthenticationFeature:<Handler>k__BackingField' (1) 
due to: Could not resolve type with token 01000080 from typeref (
expected class 'Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler' in assembly 
'Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') 
assembly:Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, 
PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler 
member:(null)'
```
and somes in the debug windows
```

**System.TypeLoadException:** 'Could not load type of field 'Microsoft.AspNetCore.Http.Features.Authentication.HttpAuthenticationFeature:<Handler>k__BackingField' (1) due to: Could not resolve type with token 01000080 from typeref (expected class 'Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler' in assembly 'Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler member:(null)'

**System.Reflection.TargetInvocationException:** 'Exception has been thrown by the target of an invocation.'

**Unity.ResolutionFailedException:** 'For more information add Diagnostic extension: Container.AddExtension(new Diagnostic())'

**Prism.Navigation.NavigationException:** 'An error occurred while resolving the page. This is most likely the result of invalid XAML or other type initialization exception'

**Prism.Navigation.NavigationException:** 'An error occurred while resolving the page. This is most likely the result of invalid XAML or other type initialization exception'
```
before adding signalr app was working.

**Comment by BrennanConroy** [comment]
>Unity.ResolutionFailedException

Are you using Unity?

If that's the case, then it's likely that Unity is removing a bunch of the binaries that it doesn't think you need. To workaround that you need to add a link.xml file with the binaries you want it to keep.

See https://docs.unity3d.com/Manual/IL2CPP-BytecodeStripping.html and and example of someone else doing this https://github.com/thorgeirk11/SignalR-IL2CPP-failure-example/blob/master/Unity%202018.4%20Client/Assets/link.xml

**Comment by azizkazdal** [comment]
I am using Prism for MVVM and Prism Unity forms for dependecy injection. It's not Unity3D

**Comment by davidfowl** [comment]
@azizkazdal That property was removed in 3.0 but I'm failing to understand what's referencing the older version of the assembly. Are you using the 3.0.0 SignalR client? Do you have any other dependencies that reference the older version of this dll?

**Comment by azizkazdal** [comment]
For now I am trying to use only version 3 and in entire solution nothing left to referencing any older version of net core. So that error I got it when I am using only version 3.

**Comment by davidfowl** [comment]
Looks like something in the project/solution/references is still referring to 2.2

**Comment by azizkazdal** [comment]
Yes it's but nothing shows up. I need to recheck every project again with clean head

**Comment by davidfowl** [comment]
You could use msbuild foo to capture a binlog and use the viewer to figure out who is pulling it in http://msbuildlog.com/

**Comment by azizkazdal** [comment]
@davidfowl thank you. clean all unnecessary references and it is working now.

**Comment by ScarlettCode** [comment]
I'm hitting the same problem. Using Prism with DryIoc. @davidfowl what am I looking for in msbuildlog exactly?

**Comment by azizkazdal** [comment]
@ScarlettCode Firstly I check all project reference which referenced older version of signalr and found one. So delete it and application worked fine.

**Comment by ScarlettCode** [comment]
@azizkazdal this is the first time I'm adding signalr to the solution so don't think it's that

**Comment by BrennanConroy** [comment]
@ScarlettCode please open a new issue with details about your scenario and the errors/issues you're hitting.
