### ISSUE TITLE
[v3.0] Unsafe code may only appear if compiling with /unsafe

### ISSUE THREAD

**Issue by dehghani-mehdi** [aspnet/AspNetCore#14546]
Hi,

I got mentioned error when I run:

> dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true

But I have this in my `.csproj` file:

```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
</PropertyGroup>
```

**Comment by blowdart** [comment]
This is a question for the [dotnet repo](https://github.com/dotnet), rather than the asp.net one.

**Comment by davidfowl** [comment]
Your property group is conditioned for Debug only. Change it to this:

```xml
<PropertyGroup>
  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
</PropertyGroup>
```
