### ISSUE TITLE
MainLayout.razor needs a 'fixed-top'

### ISSUE THREAD

**Issue by jasonshave** [aspnet/AspNetCore#14552]
### Describe the bug
Long content on the @Body of `MainLayout.razor` causes odd up/down scrolling over top of the navbar.

### To Reproduce
Create a long form and scroll to the bottom, some elements overlap the navbar and some go behind it

### Expected behavior
The top navbar should be fixed and allow the body to scroll behind it at the top

### Screenshots
Improper:
![image](https://user-images.githubusercontent.com/28457536/65821812-e3692000-e1f7-11e9-904e-b1e8efc21a51.png)

Proper:
![image](https://user-images.githubusercontent.com/28457536/65821803-c59bbb00-e1f7-11e9-8d50-169f010682eb.png)

I added the following `fixed-top` to the file:

`
    <div class="top-row px-4 fixed-top">
        <a href="https://docs.microsoft.com/en-us/aspnet/" target="_blank">About</a>
    </div>
`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jasonshave.
We plan to review the styling of the Blazor templates during 5.0 timeframe and this will be either fixed or obsolete then.
