### ISSUE TITLE
Issue regarding AddAuthenticationCore and cookies

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/AspNetCore#14555]
(Manually transferred from an issue filed by @ffMathy in the corefx repo.)

Before in my old code, I used to do:

```csharp
services
    .AddAuthentication(options =>
    {
        options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    })
    .AddCookie(options =>
    {
        options.LoginPath = "/Admin/Account/Login";
    });
```

To get auth with cookies working. 

Now, after migrating to .NET Core 3 while still using the above code, my identity showed as never authenticated. I found something referring to something being moved around, and concluded I needed to use `AddAuthenticationCore`.

I couldn't find any documentation on how to get the same working with that, so I ended up with the following code:

```csharp
services.AddAuthenticationCore(options =>
{
    options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;

    options.AddScheme<CookieAuthenticationHandler>(CookieAuthenticationDefaults.AuthenticationScheme, null);
});
```

But now I get the following error:

> Unable to resolve service for type 'Microsoft.AspNetCore.Authentication.ISystemClock' while attempting to activate 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler'.

The reason I tried using this approach, is that `AddCookie` no longer exists with the new method approach.

What can I do to get this working?

**Comment by blowdart** [comment]
Do you have UseAuthentication and UseAuthorization in your startup.cs? What order is your middleware in?

You shouldn't need the AddAuthenticationCore() call

**Comment by Tratcher** [comment]
Here's the simplified version:
```
services
    .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.LoginPath = "/Admin/Account/Login";
    });
```

**Comment by ffMathy** [comment]
I got it working now, it was just me messing around. I had to clear my browser cookies for it to work properly.

**Comment by ffMathy** [comment]
In other words, this issue can be closed I think 😄
