### ISSUE TITLE
Make the behavior of culture fallback consistent

### ISSUE THREAD

**Issue by kinosang** [aspnet/AspNetCore#14558]
### Is your feature request related to a problem? Please describe.
As aspnet/Localization#273, #2634 and dotnet/coreclr#23252, `zh-CN` and `zh-TW` will not fallback to correct culture on Linux and Mac even #14452 were fixed.

### Describe the solution you'd like
An ugly patch may solve this problem, see [here](https://github.com/aspnet/AspNetCore/pull/14550#issuecomment-536266841).

Or use middleware to modify the `Accept-Language` header before `app.UseRequestLocalization()` (not at AspNetCore side).

```csharp
app.Use((context, next) =>
{
    context.Request.Headers["Accept-Language"] = new StringValues(context.Request.Headers["Accept-Language"]
        .Select(lang => lang.ToLower()
            .Replace("zh-tw", "zh-hant-tw")
            .Replace("zh-cn", "zh-hans-cn")).ToArray());
    return next();
});
```

**Comment by ryanbrandenburg** [comment]
Given https://github.com/aspnet/AspNetCore/pull/14964#issuecomment-561772063 we're going to close this. For now our recommendation for anyone having trouble with this is that they include any descendent/more specific cultures explicitly in their SupportedCultures.
