### ISSUE TITLE
Razor Class Library - StaticWebAssetBasePath as wwwroot

### ISSUE THREAD

**Issue by soeleman** [aspnet/AspNetCore#14568]
Thank you for making _Razor Class Library_ exist.
It open possibility make component base on razor easy to distribute (as package).

For me the way _BasePath_ is not look _natural_ in web sense. 
So, I would like to make it as in picture.

![BasePath_as_wwwroot](https://user-images.githubusercontent.com/309413/65840441-68ad1b80-e343-11e9-8d4e-31f7f7534bc0.png)

To make it happen, i need change the way _Microsoft.NET.Sdk.Razor_ work.
By modify target __ResolveCurrentProjectStaticWebAssetsInputs__ on __Microsoft.NET.Sdk.Razor.StaticWebAssets.targets__ .

![ResolveCurrentProjectStaticWebAssetsInputs_Targets](https://user-images.githubusercontent.com/309413/65840472-db1dfb80-e343-11e9-9736-3119e82dfed8.png)

If you wanna to try, go to [StaticWebAssetBasePathAsWwwroot](https://github.com/soeleman/DotNetLab/tree/master/src/net3/3-0/aspnet/rcl/StaticWebAssetBasePathAsWwwroot).

The Question is how to override that target with out modification targets on SDK?
Try many way to override but without luck. When try add more target on pipelines, it make 'double asset' and it make not working.

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @soeleman.
@javiercn can you please look into this? Thanks!

**Comment by soeleman** [comment]
It is seem 'override' like this; __must__ touch the SDK target or there is another way?

Example we make a condition on __ResolveCurrentProjectStaticWebAssets__ as image bellow
![ResolveCurrentProjectStaticWebAssetsInputs_ConditionOverride](https://user-images.githubusercontent.com/309413/66265610-b8a84880-e843-11e9-8558-1251585895b7.png)

and the _Override_ on project file like this
![ResolveCurrentProjectStaticWebAssetsInputs_Project](https://user-images.githubusercontent.com/309413/66265618-e2fa0600-e843-11e9-8945-a2c619192373.png)

Anyway, If there is no other way doing this override. It is fine, just it not comfortable as user to doing this (modify the SDK).
Or maybe team ASP.NET would like to add this '_feature_' into SDK. For more info you could read [ReadMe](https://github.com/soeleman/DotNetLab/blob/master/src/net3/3-0/aspnet/rcl/StaticWebAssetBasePathAsWwwroot/ReadMe.md). Thx

**Comment by javiercn** [comment]
@soeleman You just need to put `<StaticWebAssetBasePath>say-hi</StaticWebAssetBasePath>` in your razor class library project file and that should work.

**Comment by soeleman** [comment]
@javiercn thank for the response.

When we using `<StaticWebAssetBasePath>say-hi</StaticWebAssetBasePath>` the  result is from __wwwroot\say-hi\sayhi.js__ to __wwwroot\say-hi\say-hi\sayhi.js__ (double say-hi folder).

That what custom target addressing. From __wwwroot\say-hi\sayhi.js__ to __wwwroot\say-hi\sayhi.js__ .
With current SDK, we can not override target (__ResolveCurrentProjectStaticWebAssetsInputs__). So, must modify the target on SDK.

You right this issue is closed since we must modify the SDK target. Thanks.

**Comment by javiercn** [comment]
[blazorserver.zip](https://github.com/aspnet/AspNetCore/files/3701796/blazorserver.zip)

@soeleman You shouldn't need to override any target nor change the SDK. Above is a project that does what you wanted. (either that or I'm missing something)

**Comment by soeleman** [comment]
@javiercn the purpose for custom target to make the static file consistent regarding the path.

the default will transform __wwwroot/pic.jpg__ to **wwwroot/_content/LibraryName/pic.jpg**
![BasePathAsDefault](https://user-images.githubusercontent.com/309413/66396196-69a91180-ea03-11e9-9dfc-b4e4354ee503.png)

The _StaticWebAssetBasePath_ will transform __wwwroot/pic.jpg__ to __wwwroot/StaticWebAssetBasePath/pic.jpg__
![BasePathAsRoot](https://user-images.githubusercontent.com/309413/66396359-ca384e80-ea03-11e9-9cd5-7c644ac0034f.png)

The override will transform __wwwroot/StaticWebAssetBasePath/pic.jpg__ to __wwwroot/StaticWebAssetBasePath/pic.jpg__. It might look nothing change but that behavior we want.
Why? The path will be same when we consume inside library and outside library.
E.g. _AsOverrideComponent_ using the image with __the path__ as is __on local__ and __on web-app__ who consume this library. 
It is make developer easy to predict the path on wwwroot since the transform not make change the path between __physical__ and __virtual__.
And somehow _visual studio_ pick-up __the path__ and make 'link visible' (this visual studio feature or something else here).
The only way to override (as a far I know) is touching the target SDK; the pipeline-target not design to be override easily.
![BasePathAsOverride](https://user-images.githubusercontent.com/309413/66396616-4c287780-ea04-11e9-97aa-1cc6664f81e0.png)

If you would like to try, here the file 
[BasePathAsWwwRoot.zip](https://github.com/aspnet/AspNetCore/files/3702401/BasePathAsWwwRoot.zip)

**Comment by javiercn** [comment]
@soeleman I think I know what you mean now. You want the physical path inside the project to be the same as the relative path from the project so that you can use Visual Studio intellisense to reference the files from within the project. Is my understanding correct?

We don't provide an easy way to do this, but you can write your own MSBuild extensibility to achieve it. There's no need to modify the SDK, simply add  a target that hooks into GetCurrentProjectStaticWebAssets and ResolveStaticWebAssetsInputs and modify the Contentroot on the static web asssets for the current project to something like `$([MSBuild]::NormalizeDirectory('$(MSBuildProjectDirectory)\wwwroot\$(StaticWebAssetBasePath)'))`

**Comment by soeleman** [comment]
@javiercn Yes, it is correct. physical path same as the relative path. It is more intuitive since we know where the assets inside or outside library.
Thank for the tips on MSBuild (I will try it) and response.
