### ISSUE TITLE
Using FileProviders without views compilation?

### ISSUE THREAD

**Issue by dario-l** [aspnet/AspNetCore#14572]
I have multi-modular asp net core application which is working perfectly in core 2.2. Unfortunately core 3.0 brings some braking changes and we have problem now.

We use `PhysicalFileProvider` for loading views from referenced mvc projects (where each is separated module). **We do not compile views.**
Thanks to that:
- in `Debug` mode I can modify views without recompilation of any project
- in `Release` mode we can copy views from referenced projects to proper structured folders in the main application and publish it

After upgrading to core 3.0 this solution doesn't work.

1. First of all - issue #7647 
2. I found that I can disable compilation setting `RazorCompileOnBuild` to false but that causes my ViewLocationExpander (we use Feature Folder structure) to stop working
3. Setting `MvcRazorRuntimeCompilationOptions` have no effect without calling `AddMvcRazorRuntimeCompilation`. Again: **We do not compile views**

```
services.Configure<MvcRazorRuntimeCompilationOptions>(opts =>  
    opts.FileProviders.Add( new myFileProvider() ) 
);
```

We want to use `PhysicalFileProvider` to indicate where the views are located but without compilation.

Is there any possibility to get it working again like in core 2.2?

**Comment by constructor** [comment]
I would like to add my weight to this issue.

I was previously using (and still do in the .net core 2.2 version of my project) the following approach:

```
services.Configure<RazorViewEngineOptions>(options =>
{
     InstallerProviderItem.RazorViewEngineFileProviders.ForEach(x => options.FileProviders.Add(x));
});
```
Here the RazorViewEngineFileProviders contains a DatabaseFileProvider and an EmbeddedFileProvider for each 'plugin' assembly, along with IChangeToken [similar to this article](https://www.mikesdotnetting.com/article/301/loading-asp-net-core-mvc-views-from-a-database-or-other-location) and all works fine. Views that are edited in the database are refreshed after being edited on next page load.

Using this approach:
```
services.Configure<MvcRazorRuntimeCompilationOptions>(options =>
{
     InstallerProviderItem.RazorViewEngineFileProviders.ForEach(x => options.FileProviders.Add(x));
});
```

It does not work the same. The documentation states that code has been 'moved', but it also does not function as previously. Also, the DatabaseChangeToken no longer works and any views edited in the database no longer refresh unless the app is restarted.

**Comment by pranavkm** [comment]
@dario-l, using `RazorViewEngineOptions.FileProviders` was a feature of runtime compilation. Configuring it effectively meant you were configuring the behavior of compiling views at runtime. To get the effective behavior in 3.0, you will need to call `AddMvcRazorRuntimeCompilation`.

I've added a sample that shows using runtime compilation in dev time using IFileProviders while using compiled views on publish: https://github.com/aspnet/samples/blob/master/samples/aspnetcore/mvc/runtimecompilation/. Here's the relevant bits to set up runtime compilation: https://github.com/aspnet/samples/blob/master/samples/aspnetcore/mvc/runtimecompilation/MyApp/Startup.cs#L32-L41 in Debug \ Development.

**Comment by dario-l** [comment]
@pranavkm So, I can not use FileProviders now without any kind of views compilation (like in core 2.2)?

**Comment by dario-l** [comment]
OK, I found it.

Adding `<MvcRazorCompileOnBuild>false</MvcRazorCompileOnBuild>` to the `MyApp.csproj` causes that compilation is not executed **but** view is refreshed.

I **hope** that behavior will be not removed (silently) in the future releases. :)
