### ISSUE TITLE
Blazor GetJsonAsync call returns html instead of json

### ISSUE THREAD

**Issue by CliffConway** [aspnet/AspNetCore#14573]
I am using VS 2019 preview with all updates applied and all necessary Nuget previews installed.

In my Blazor app I have a number of API calls in pages (called index.razor) where the calls are similar to:- 

sectors = await http.GetJsonAsync<ICBSector[]>("api/ICBSectors");

Instead of returning json they all return the index.html page from the 'wwwroot' and promptly cause a json exception for obvious reasons.

Error:-
WASM: System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

Any thoughts on possible causes and/or solutions?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @CliffConway.
Please share the server logs here.

**Comment by CliffConway** [comment]
Apologies for the late reply. I am executing this directly from VS. Where would the server logs be stored?

**Comment by CliffConway** [comment]
Are you referring to IIS logs or ?

**Comment by mkArtakMSFT** [comment]
You should see the logs in the Output windows of the VS.

**Comment by CliffConway** [comment]
Discovered my problem was related to using old class entities generated by non-core EF (the lazy option used to create my database table classes) . They were helping to generate extra column names in the EF Core Sql queries (due to artifacts related to foreign keys) that didn't exist. Now working ok. Thanks for your help with this.
