### ISSUE TITLE
Returning 2D arrays on API

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14577]
_From @btogkas on Monday, September 30, 2019 8:26:22 AM_

Trying to return two dimensional decimal array from Controller.

public ActionResult<decimal[,]> TwoDArray()

This does not work on .Net Core 3 but works on 2.2
(Other methods work normally)

The configuration instead of UseMVC is 

app.UseRouting();
app.UseEndpoints(x =>
{
    x.MapControllers();
});

Is there something missing or?

_Copied from original issue: dotnet/core#3510_

**Comment by pranavkm** [comment]
This sounds like a limitation of System.Text.Json, it does not support multi-dimensional arrays are not supported. (cc /@SteveHarter / @ahsonkhan ). You should be able to continue using Newtonsoft.Json-based formatters to get the 2.x behavior: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support
