### ISSUE TITLE
Bad responses: Json, Plaintext, PlaintextNonPipelined

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14598]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| Json | Windows, Cloud, http, IISInProcess | 10/1/19 1:49:05 AM +00:00 | 1088015 |
| Plaintext | Windows, Cloud, http, IISInProcess | 10/1/19 1:45:52 AM +00:00 | 1070845 |
| PlaintextNonPipelined | Windows, Cloud, http, IISInProcess | 10/1/19 1:47:28 AM +00:00 | 1091396 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by anurse** [comment]
@jkotalik just fixed this.
