### ISSUE TITLE
Need globalization, localization message "Attempting to reconnect to the server..."

### ISSUE THREAD

**Issue by donhuvy** [aspnet/AspNetCore#14604]
I am use 
- Microsoft Visual Studio Community 2019 Preview Version 16.4.0 Preview 1.0
- dotNET Core 3.0.0 (official release)
- Blazor server (official release)
- DevExpresss Blazor component 19.1.7
- Windows 10
- Google Chrome 77

### Is your feature request related to a problem? Please describe.
As a Vietnamese end-user, I don't understand these words 

- **"Attempting to reconnect to the server..."** (1)

- **"Reconnection failed. Try reloading the page if you're unable to reconnect."** (oh, suddenly, I see this sentence quite meaningless, why "reload if I am unable reconnect") (2)

- text lable of button **"Retry"** (3)

and maybe so on.

![a1](https://user-images.githubusercontent.com/1328316/65934836-13573400-e441-11e9-9716-7468e8a762dd.png)

### Describe the solution you'd like
I can see the alternative Vietnamese words: 

- **"Đang cố gắng kết nối đến server"** (1)

- **"Kết nối thất bại. Thử tải lại trang nếu bạn không thể kết nối trở lại"** (2)

- **"Thử lại"** (3)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @donhuvy.
We expose certain APIs to configure this. You can read more about this at https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#reconnection-to-the-same-server
