### ISSUE TITLE
Can I use the events from WebSocket/SignalR (javascript) on blazor?

### ISSUE THREAD

**Issue by jeanklann** [aspnet/AspNetCore#14600]
The Blazor is pretty fast for now.
I almost click on an element and I imediately get an answer from the server.
But this is an hypothethical scenario.

The demos on internet, or some UI (like devexpress components) has some lag.
This is normal, i will always has lag, but thinking in a large system using Blazor this lag can be more intensive.

Given this scenario, can I 'intercept' some events from WebSockets/SignalR (in client-side) and call something like the blockui (http://malsup.com/jquery/block/#page)?
Something like blocking page/component before send an message to the blazor server and unblock when receive it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jeanklann.
You should do whatever you can to reduce the latency. If however the final outcome is not satisfactory, you should consider switching to Blazor WASM.

SignalR Hub is an implementation detail for Blazor and we do not expose it for consumption directly.
We will, however, expose certain configuration options/events to enable certain scenarios. For this particular case, we haven't heard many asks to enable this. If we hear community asking for this a lot, we will consider doing something here.
