### ISSUE TITLE
Discussion: Binary breaking change in removal of Microsoft.AspNetCore.Mvc.Components.Prerendering

### ISSUE THREAD

**Issue by mahabirsingh-kis** [aspnet/AspNetCore#14608]
I have an application which was in .net core 2.2. Everything was working fine then I upgraded it to 3.0.100-preview9-014004 , till then the application was working fine. Now when I upgraded it to the stable version 3.0.100. I am getting issue: 

Error: FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Components.Prerendering, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

I have followed the link to upgrade : https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio

Whenever I tried to execute the application. I get an exception 

![Error](https://user-images.githubusercontent.com/16679896/65939852-a2b21680-e444-11e9-93be-25b565397980.png)

Thank you

**Comment by blowdart** [comment]
Generally this happens when you haven't updated all your dependencies to 3.x . Please share your dependencies.

**Comment by mahabirsingh-kis** [comment]
Hello @blowdart , Thank you for you response. Following are the dependencies I used and I have upgraded it to 3.0

<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.0.0" />
 <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="3.0.0" />
  <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="5.5.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocol.Extensions" Version="1.0.4.403061554" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="2.0.0-dev-00032" />
    <PackageReference Include="SqlTableDependency" Version="8.5.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0-rc2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="5.0.0-rc2" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="5.0.0-rc2" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUi" Version="5.0.0-rc2" />

Thanks

**Comment by davidfowl** [comment]
This was an intentional breaking change. See https://github.com/aspnet/Announcements/issues/388

cc @rynowak

**Comment by rynowak** [comment]
Swashbuckle has been updated to 5.0.0-rc4 - can you try updating?

**Comment by mahabirsingh-kis** [comment]
thanks @rynowak for your response. I will try to update it and will check.

**Comment by mahabirsingh-kis** [comment]
thanks @davidfowl for your response. Do you mean I have rebuild my application from scratch to migrate to .net core 3.0? Isn't there any other solution

**Comment by davidfowl** [comment]
Yes you need to recompile against 3.0

**Comment by mahabirsingh-kis** [comment]
thanks for the reply @davidfowl 

But it would be very cumbersome to build again. Isn't there any other solution

Thanks

**Comment by davidfowl** [comment]
@mahabirsingh-kis Didn't you re-compile against preview9? Why is it a pain to recompile against the final version?

**Comment by mahabirsingh-kis** [comment]
Hello @davidfowl 

I have updated the Visual Studio 2019 and the above error gone, but the AutomaticReconnect is not working work. Whenever there is connection timeout error (from SQL end), Signarl R stops working and it is not reconnecting.

const connection = new signalR.HubConnectionBuilder().withUrl("/Test").withAutomaticReconnect([0, 2000, 10000, 30000, null]).configureLogging(signalR.LogLevel.Information).build();

Thanks for your help

**Comment by davidfowl** [comment]
@mahabirsingh-kis can you open a new issue?

**Comment by mahabirsingh-kis** [comment]
@davidfowl created : https://github.com/aspnet/AspNetCore/issues/16730
Please have a look
