### ISSUE TITLE
Bad responses: Json, Plaintext, PlaintextNonPipelined

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14601]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| Json | Windows, Physical, http, IISInProcess | 10/1/19 3:19:21 AM +00:00 | 6917207 |
| Plaintext | Windows, Physical, http, IISInProcess | 10/1/19 3:16:14 AM +00:00 | 6909643 |
| PlaintextNonPipelined | Windows, Physical, http, IISInProcess | 10/1/19 3:17:47 AM +00:00 | 6917479 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by anurse** [comment]
@jkotalik just fixed this.
