### ISSUE TITLE
How to use Javascript.confirm() on client side blazor?

### ISSUE THREAD

**Issue by ChocolaDiGiCharat** [aspnet/AspNetCore#14611]
I try write javascript.confirm() wrapper method, but not work (dead-lock occurred?)...
Please advice.

```
      public static async Task<bool> YesNoAsync(IJSRuntime jsr, string message)
        {
            try
            {
                if (jsr == null)
                {
                    return false;
                }

                var v = await jsr.InvokeAsync<bool>("confirm", $"{message}").ConfigureAwait(false);
                return v;
            }
            catch
            {
                return false;
            }
        }

        public static bool YesNo(IJSRuntime jsr, string message)
        {
            return YesNoAsync(jsr, message).Result;
        }

```

**Comment by campersau** [comment]
Client side blazor only has a single "thread" so calling `.Result` will deadlock it. Calling your async version with `await` should work. See https://blazorfiddle.com/s/qwzc7k5l

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by ChocolaDiGiCharat** [comment]
Thank you very much! It was very helpful.
