### ISSUE TITLE
How can i set Layout null depending on Query parameters?

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore#14617]
### Is your feature request related to a problem? Please describe.
I want to update page sections through ajax and spare myself from always doing a full page reload.

If i manually add
Layout = Context.Request.Query.ContainsKey("nolayout") ? null : "path/to/layout";
to a file that will work, but i am looking for a generic approach to this? 

### Describe the solution you'd like
Is there some sort of injection point i can use to set the layout to null before a view is rendered?

**Comment by taori** [comment]
![grafik](https://user-images.githubusercontent.com/5545184/65959921-7f429800-e453-11e9-80db-a4d7759a504e.png)

Perhaps this can be abused to serve my purpose?

**Comment by taori** [comment]
this does not work either:


		/// <inheritdoc />
		public RazorPageResult FindPage(ActionContext context, string pageName)
		{
			var razorPageResult = _viewEngine.FindPage(context, pageName);
			if (_contextAccessor.HttpContext.Request.Query.ContainsKey("nolayout"))
			{
				razorPageResult.Page.Layout = null;
				razorPageResult.Page.IsLayoutBeingRendered = false;
			}
			return razorPageResult;
		}

**Comment by pranavkm** [comment]
> If i manually add
> Layout = Context.Request.Query.ContainsKey("nolayout") ? null : "path/to/layout";

You could put this in a `_ViewStart.cshtml` and that should apply to all layouts.

**Comment by taori** [comment]
@pranavkm Hm. That doesnt generally apply it to plugins, but that is the solution i went with now and it's a rare edge case scenario  (requiring layout overrides instead of static layouts) i guess, so i'll just live with it i guess
