### ISSUE TITLE
Make FormActionTagHelper link resolution method public so it can be utilized to inheriting classes

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore#14610]
### Is your feature request related to a problem? Please describe.
I want to write a TagHelper which wraps a `<button type="submit">` into a forms tag to enable a standalone post form. 

### Describe the solution you'd like
If the process method in https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.TagHelpers/src/FormActionTagHelper.cs would be refactored and made the method protected to obtain a route url from this TagHelper i could simply inherit from FormActionTagHelper and easily create my taghelper, instead of duplicating the code from source.

That way i could turn this:

	<form asp-page-handler="Delete" asp-route-id="@layout.Id" method="post">
		<button type="submit" class="btn btn-outline-danger">@StringLocalizer["Delete"]	</button>
	</form>
into this:

	<button type="submit" to-forms-method="post" asp-page-handler="Delete" asp-route-id="@layout.Id" class="btn btn-outline-danger">@StringLocalizer["Delete"]</button>

ps: I do know that i could get the value from .Attributes, but then i would depend on information "published" through a key contained on a private field.

**Comment by pranavkm** [comment]
Thanks @taori. We'd be happy to accept a PR for this.

**Comment by taori** [comment]
@pranavkm Np. What is the procedure for PR's? Does the person, who executes the PR merge, set the branch target or is this supposed to be done by the PR author?

**Comment by NTaylorMullen** [comment]
@taori would you mind sharing the TagHelper you're writing that inherits from our `FormTagHelper`? After looking at this issue further I regretfully don't feel like it's something we'd take; that being said, there's probably a cleaner way to accomplish what you're trying to do.

**Comment by taori** [comment]
@NTaylorMullen 


	public enum HttpMethod
	{
		Post,
		Get, 
		Delete,
		Patch,
		Options,
		Head,
		Put,
		Trace
	}

	[HtmlTargetElement("input", Attributes = "[type=submit],to-forms-method")]
	[HtmlTargetElement("button", Attributes = "[type=submit],to-forms-method")]
	public class FormsSubmitTagHelper : FormActionTagHelper
	{
		/// <inheritdoc />
		public FormsSubmitTagHelper(IUrlHelperFactory urlHelperFactory, IHtmlHelper htmlHelper) : base(urlHelperFactory)
		{
			_htmlHelper = htmlHelper;
		}

		private readonly IHtmlHelper _htmlHelper;

		[HtmlAttributeName("to-forms-method")]
		public HttpMethod Method { get; set; }

		/// <inheritdoc />
		public override void Process(TagHelperContext context, TagHelperOutput output)
		{
			if (context == null)
			{
				throw new ArgumentNullException(nameof(context));
			}

			if (output == null)
			{
				throw new ArgumentNullException(nameof(output));
			}
			
			if (output.Attributes.TryGetAttribute("formaction", out var attr))
			{
				output.PreElement.AppendHtml($@"<form method=""{Method.ToString().ToLower()}"" action=""{attr.Value}"">");
				if (Method != HttpMethod.Get)
				{
					((IViewContextAware)_htmlHelper).Contextualize(ViewContext);
					output.PreElement.AppendHtml(_htmlHelper.AntiForgeryToken());
				}
				output.PostElement.AppendHtml("</form>");
			}
		}
	}

it depends on a string provided by a private field right now.

**Comment by taori** [comment]
I see that perhaps this whole method logic should be refactored to a standalone helper or something, but i did not want affect the api more than necessary

**Comment by NTaylorMullen** [comment]
What you have seems quite fine. Is there any reason you need to inherit from `FormActionTagHelper` at all?

Also, I'd recommend doing a separate output.PreElement.Append for `attr.Value`. What you have now is `ToString`ing the value which isn't guaranteed to `ToString` properly.
