### ISSUE TITLE
Apply attributes to inline blazor html code block

### ISSUE THREAD

**Issue by Valks** [aspnet/AspNetCore#14616]
I am trying to use benchmark dotnet to find performance issues when updating the UI in blazor. I have a for loop which creates a lot of DOM elements that takes too long and I'd like to test a few things to find out if it's my foreach loop or the diff generation + sending that's the main issue.

### Describe the solution you'd like
Looking at the documentation I see you can create functions inside inline code blocks so I thought I could add attributes to those functions and call them as per the example below:
```
@{
            [BenchmarkDotNet.Attributes.Benchmark]
            void ShowItems()
            {
                  foreach(var item in ItemEnumerator())
                  {
                      <Item></Item>
                  }
            }
            ShowItems();
    }
```

### Additional context
To overcome the performance issues I've also been trying to find ways to split the rendering and only send the first few elements then let the rest of the loop continue after but I cannot find a way to interrupt the loop and trigger an update. At least I haven't found a solution I`m happy with yet.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Valks.
The `ShowItems` method you've defined is actually an inline method, and you can't call it from outside.
There are multiple reasons for this not to work as you expect, which are out of scope from us to discuss here. We recommend people to use `StackOverflow` instead for these type of questions, as it'll be faster to get a response there.
