### ISSUE TITLE
How to invalidate DefaultActionDescriptorCollectionProvider's cache

### ISSUE THREAD

**Issue by DmitrySikorsky** [aspnet/AspNetCore#14628]
Hi guys, thank you for your great work!

I'm working on the ExtCore modular framework project, updating it to .NET Core 3. One of the requested features is to be able to add (and remove) extension at runtime (https://github.com/ExtCore/ExtCore/issues/43).

I'm using application parts to manage extensions features. I was able to use something like

```
applicationPartManager.ApplicationParts.Add(
        new AssemblyPart(Assembly.LoadFrom(@"...\E1.dll"))
      );
```

to add a application part at runtime. But it doesn't work, because (as I found) of the DefaultActionDescriptorCollectionProvider cache. This class is internal, so I just tried to copy it, made UpdateCollection public (just quick and dirty for the test), replaced the existing implementation inside the DI and call UpdateCollection after new application part is added. And now everything works. Now I can add application part at any moment and controller, defined there, works.

But I really don't like this solution. Could you give me any information how to do that in a normal way?

Thank you very much.

**Comment by pranavkm** [comment]
This is the type you want - https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.infrastructure.iactiondescriptorchangeprovider. Here's an example of it being used - https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Mvc/Mvc.Razor.RuntimeCompilation/src/PageActionDescriptorChangeProvider.cs.

**Comment by rynowak** [comment]
I don't think we have guarantees about adding/removing application parts at runtime. I would be really surprised if `ApplicationPartManager` is threadsafe.

**Comment by DmitrySikorsky** [comment]
Thank you for the fast answer, @pranavkm. Now I realized that I need to do that from another side. I've created my own IActionDescriptorChangeProvider implementation and registered it inside the DI. Now I can see that _actionDescriptorChangeProviders contains 1 element inside the ActionDescriptorCollectionProvider. I understand that the only thing left to do is to create correct IChangeToken implementation and execute callback, registered using its RegisterChangeCallback. But I can't find any documentation how to do that. I need to be able to call some Changed method inside my IChangeToken implementation, which should call the callback. But for now I can't make it work.

**Comment by DmitrySikorsky** [comment]
> I don't think we have guarantees about adding/removing application parts at runtime. I would be really surprised if ApplicationPartManager is threadsafe.

I think we have 2 cases here:

1. Multiple executions of the parts adding/removing at the same time.
2. User requests while extensions are partially loaded.

The first can be easily managed. The second could be fixed with some middleware which returns some HTTP code (like 503) while the application parts reconfiguration (I think ~1 second of downtime is still much better than entire application restart).

What do you think? Is it good idea?

**Comment by DmitrySikorsky** [comment]
@pranavkm thank you very much, I have figured it out with your help, it works. Now will think about how to make it safe.
