### ISSUE TITLE
Bad responses: ConnectionClose, ConnectionClose, DbMultiUpdateDapper, DbMultiUpdateDapper, DbMultiUpdateEf ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14627]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| ConnectionClose | Linux, Cloud, http, KestrelSockets | 10/1/19 12:44:59 PM +00:00 | 341 |
| ConnectionClose | Linux, Cloud, https, KestrelSockets | 10/1/19 12:45:19 PM +00:00 | 16 |
| DbMultiUpdateDapper | Windows, Cloud, http, KestrelSockets | 10/1/19 1:30:12 PM +00:00 | 493 |
| DbMultiUpdateDapper | Linux, Cloud, http, KestrelSockets | 10/1/19 4:50:11 PM +00:00 | 365 |
| DbMultiUpdateEf | Linux, Cloud, http, KestrelSockets | 10/1/19 8:38:46 AM +00:00 | 482 |
| DbMultiUpdateEf | Windows, Cloud, http, KestrelSockets | 10/1/19 1:30:58 PM +00:00 | 552 |
| DbMultiUpdateRaw | Windows, Cloud, http, KestrelSockets | 10/1/19 1:29:26 PM +00:00 | 413 |
| DbMultiUpdateRaw | Linux, Cloud, http, KestrelSockets | 10/1/19 4:48:35 PM +00:00 | 509 |
| MvcDbMultiUpdateDapper | Linux, Cloud, http, KestrelSockets | 10/1/19 12:38:59 PM +00:00 | 252 |
| MvcDbMultiUpdateDapper | Windows, Cloud, http, KestrelSockets | 10/1/19 1:32:30 PM +00:00 | 537 |
| MvcDbMultiUpdateEf | Linux, Cloud, http, KestrelSockets | 10/1/19 12:39:43 PM +00:00 | 156 |
| MvcDbMultiUpdateEf | Windows, Cloud, http, KestrelSockets | 10/1/19 1:33:17 PM +00:00 | 480 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Confirmed that these scenarios have an abnormal rate of errors of the cloud instances.

**Comment by sebastienros** [comment]
Recovered
