### ISSUE TITLE
Scenarios are not running: LinkAThonBaseline, LinkAThonTrimmedAndR2RSingleFile, LinkAThonTrimmedAndR2RSingleFileNoMvc

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14632]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| LinkAThonBaseline | Linux, Physical, http, KestrelSockets | 9/30/19 7:29:45 PM +00:00 |
| LinkAThonTrimmedAndR2RSingleFile | Linux, Physical, http, KestrelSockets | 9/30/19 7:32:09 PM +00:00 |
| LinkAThonTrimmedAndR2RSingleFileNoMvc | Linux, Physical, http, KestrelSockets | 9/30/19 7:33:42 PM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by Pilchie** [comment]
@sebastienros ?

**Comment by sebastienros** [comment]
Closing, but LinkAThonTrimmedAndR2RSingleFile might be re-opened automatically as it's still not working, but it's being tracked with the diagnostics team who found the issue related to that one.
