### ISSUE TITLE
Serving static .properties file from wwwroot => 404

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#14634]
Hello guys, i try actually to use a worker (https://github.com/mozilla/pdf.js) in my blazor app, worker who need to read some .properties files.

It seem the file are not accessible by default, i always have a 404 error when i try to access it.

How to reproduce :
- create a blazor webAssembly app .net core hosted
- on the wwwroot of the client project, put one test.json and one test.properties file
- launch the app
- open the url https://localhost:xxxxx/test.json => OK
- open the url https://localhost:xxxxx/test.properties=> 404

I try to add a mapping to this extension on the startup as i see on internet
````
var provider = new FileExtensionContentTypeProvider();
provider.Mappings[".properties"] = "application/octet-stream";
app.UseStaticFiles(new StaticFileOptions { ContentTypeProvider = provider });
````
- on the startup of the server project : no effect
- on the startup of the client project : it seem i can't put this code here. I need a IApplicationBuilder on entry point, and on the client side i have a ComponentsApplicationBuilder.

Thanks for your help !

Julien

**Comment by soeleman** [comment]
Try to set on the file as __Content__.
__Build__ will escape it, if you do not set that.

![Properties__Build_Action](https://user-images.githubusercontent.com/309413/66010786-9e403900-e4ea-11e9-81cb-628fa6f9eb41.png)

**Comment by julienGrd** [comment]
i checked that, the file have have already a build action to content, so still not work.

**Comment by soeleman** [comment]
Try to simulate it ([ContentTypeCustom](https://github.com/soeleman/DotNetLab/tree/master/src/net3/3-0/aspnet/core/ContentTypeCustom)) and mapping as your code above

![TestProperties](https://user-images.githubusercontent.com/309413/66065752-536a0400-e572-11e9-891d-4f69f6814316.png)

**Comment by julienGrd** [comment]
I don't understand, it seem it work for you but i still have 404 and i have the same code...

can you confirm me :
- the FileExtensionContentTypeProvider code is on the startup of the Server project
- your .properties file is on the wwwroot of the client project
- you are in blazor web assembly .net core hosted

Anyone here have the same error than me ?

**Comment by soeleman** [comment]
I am sorry, my first solution is for web project.
Your is Blazor-Client (WASM).

After looking for awhile, i got workaround on adding new MIME.

![Blazor_Startup](https://user-images.githubusercontent.com/309413/66091655-d90da400-e5b2-11e9-96dc-ada03feb21d8.png)

The extensions is here [BlazorExtensions.cs](https://github.com/soeleman/DotNetLab/blob/master/src/net3/3-0/aspnet/blazor/wasm/ContentTypeCustom/Soeleman.Wasm/Server/BlazorExtensions.cs) on project [ContentTypeCustom](https://github.com/soeleman/DotNetLab/tree/master/src/net3/3-0/aspnet/blazor/wasm/ContentTypeCustom).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by julienGrd** [comment]
@mkArtakMSFT : it's not closed actually the solution provide seem not work for me

thanks for your help @soeleman 
unfortunately with your code my app stop working.
When i launch them, now i have 404 on all the .net dll
:44340/_framework/_bin/Microsoft.AspNetCore.Components.Web.dll:1 Failed to load resource: the server responded with a status of 404 () : 

Indeed it seem i don't have the _bin folder under the _framework folder. But was always like that. I don't know actually where my app take these dll but before was working.

Do you have a starter project working with this solution ?

Thanks for your help !

**Comment by soeleman** [comment]
You can try project on [link](https://github.com/soeleman/DotNetLab/tree/master/src/net3/3-0/aspnet/blazor/wasm/ContentTypeCustom) above.

**Comment by julienGrd** [comment]
oups i didn't see that sorry ! 

ok i found what's happen, i was thinking only your UseClientSideBlazorFile was needed but we really need the original one too. now it works.

thanks for your help, the problem is close for me !
