### ISSUE TITLE
Improve partial class support in Blazor

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#14646]
Follow up to https://github.com/aspnet/AspNetCore/issues/5487

- ~[ ] Remove support for `MangleClassName` (https://github.com/aspnet/AspNetCore-Tooling/pull/1182#discussion_r329827362)~ can't do this until VSCode partial class support has been added
- ~[ ] Target the support based on Razor version (https://github.com/aspnet/AspNetCore-Tooling/pull/1182#discussion_r329827077)~ Decided against this
- [x] Known bugs (https://github.com/aspnet/AspNetCore-Tooling/pull/1182#issuecomment-536074644)

**Comment by rpskelton2** [comment]
Does this cover inheriting from a generic base class?  Last I tried code like below resulted in compiler errors.  If I put everything in the .razor file and don't use partial classes it compiles fine.

`
PropertyComponentBase.cs
public abstract class PropertyComponentBase<T> : ComponentBase
{
   blah...
}

MyComponent.razor
@inherits PropertyComponentBase<sometype>

MyComponent.razor.cs
public partial class MyComponent : PropertyComponentBase<sometype>
{
}
`

**Comment by rpskelton2** [comment]
👍
