### ISSUE TITLE
Bad responses: Json, Json, Plaintext, Plaintext, PlaintextNonPipelined ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14650]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| Json | Windows, Physical, http, IISInProcess | 10/1/19 3:21:16 PM +00:00 | 6917207 |
| Json | Windows, Cloud, http, IISInProcess | 10/1/19 6:02:18 PM +00:00 | 1088015 |
| Plaintext | Windows, Physical, http, IISInProcess | 10/1/19 3:18:12 PM +00:00 | 6909643 |
| Plaintext | Windows, Cloud, http, IISInProcess | 10/1/19 5:59:05 PM +00:00 | 1090535 |
| PlaintextNonPipelined | Windows, Physical, http, IISInProcess | 10/1/19 3:19:45 PM +00:00 | 6917479 |
| PlaintextNonPipelined | Windows, Cloud, http, IISInProcess | 10/1/19 6:00:41 PM +00:00 | 1119087 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Fixed
