### ISSUE TITLE
Identity scaffold template missing encoding when verifying via login page

### ISSUE THREAD

**Issue by StickMick** [aspnet/AspNetCore#14659]
### Describe the bug
The Identity scaffold template has several ways to trigger the email verification, but one is missing encoding.  
.../V3/Account/Login.cshtml.cs 

`OnPostSendVerificationEmailAsync()`
` ... `
`var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);`
`//Missing`
`code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));`
`//End Missing`
`var callbackUrl = Url.Page(`

Verification process will always decode, so un-encoded links will fail.

### To Reproduce
1. Using this version of ASP.NET Core 3
2. Create project with local account storage
3. Scaffold Identity
4. Implement IEmailSender
5. Create Account
6. Logout
7. Use Resend Verification Email from login page
8. Follow link in second email - it will fail.
9. Follow link in first email - it will succeed.

### Expected behavior
All email verification links to be encoded for email, then decoded on submit.

**Comment by HaoK** [comment]
This is somewhat related to https://github.com/aspnet/AspNetCore/issues/13462, we can discuss at triage today

**Comment by HaoK** [comment]
Using this bug to track removing all vestiges of resend email in 3.1, it will be brought back in better form in 5.0

**Comment by HaoK** [comment]
Removed the feature in 3.1 https://github.com/aspnet/AspNetCore/pull/14901 scaffolding side of the removal is here https://github.com/aspnet/Scaffolding/pull/1117
