### ISSUE TITLE
Update of the nuget packages to the 3.0 version of .net core Signalr and MessagePack protocol has stopped working

### ISSUE THREAD

**Issue by Pibe93** [aspnet/AspNetCore#14664]
Good morning,
I updated the nuget Signalr packages to .net core version 3 (
**MessagePack 2.0.123 beta
Microsoft.AspNetCore.Signalr.Client 3.0
Microsoft.AspNetCore.Signalr.Client.Core 3.0
Microsoft.AspNetCore.Signalr.Client.Common 3.0
Microsoft.AspNetCore.Signalr.Protocols.Json 3.0
Microsoft.AspNetCore.Signalr.Protocols.MessagePack 3.0**
) 
and found this error when using the message pack protocol.
The screenshot of error : 

![Exception](https://user-images.githubusercontent.com/44985216/66033086-deadb000-e506-11e9-813f-96026e95552d.PNG)

Thanks for the help.

**Comment by BrennanConroy** [comment]
Microsoft.AspNetCore.Signalr.Protocols.MessagePack targets MessagePack 1.7.X.Y
If you pull in MessagePack 2.X manually you're going to cause these kinds of issues if there are breaking changes between those version (which there are).

**Comment by Pibe93** [comment]
I also updated that without looking at it, now I try to update only the other packages to version 3.
Meanwhile, thanks for the feedback and I will update you soon.

**Comment by Pibe93** [comment]
Ok the problem was simply that.
Thanks for the help.
