### ISSUE TITLE
Blazor onclick event in select does fire in Safari

### ISSUE THREAD

**Issue by blenke** [aspnet/AspNetCore#14669]
### Describe the bug
An onclick event in a dropdown select does not fire in Safari, works fine in Edge, Chrome or Firefox. 

### To Reproduce
Using Blazor with dotnet core 3.0 RTM with Safari browser. The myvar never gets set by the result function.

```
<select @onclick="@result">
    <option>one</option>
    <option>two</option>
    <option>three</option>
</select>
<label>@myvar</label>
@code {
    string myvar;
    void result() { myvar = "hello world"; }
}

```

**Comment by pranavkm** [comment]
Looks like this is a limitation in Safari - https://stackoverflow.com/a/11383005. Blazor does not provide any additional shims over the features the browser supports.
