### ISSUE TITLE
Issues Hosting ASP.Core 2.2 in IIS (inprocess)

### ISSUE THREAD

**Issue by Q-Tec90** [aspnet/AspNetCore#14661]
Hello,

I encountered some strange behavior and I am simply unable to find the source of the issue. So I was hoping to get some new ideas for approaching that issue.
First some informations:
The ASP Project is targeting the Core Framework 2.2.

I have tried [this](https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0) so far and [this](https://stackify.com/how-to-deploy-asp-net-core-to-iis/) one as well (on the application as well as a small scale test app.) and sadly non of those guides helped me out. It did not work and I got multiple different error which I will document later on.

I really do not understand this because the iis express which gets configurated by visual studio during debug session never had an issue. It is still working there.

Let me first show you my "Programm" class as well as my "Startup" class.

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }

And the startup look like this:

`
public class Startup
    {

        public Startup(ILogger<Startup> logger, IConfiguration configuration)
        {
            _logger = logger;
            Configuration = configuration;

            if (UserManagementCache.GetInstance().Count <= 0)
                UserManagementCache.GetInstance().InvalidateCache();
        }

        private readonly ILogger<Startup> _logger;
        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.Configure<RazorViewEngineOptions>(options => 
            {
                options.FileProviders.Add(new CompositeFileProvider(
                    new EmbeddedFileProvider(
                        typeof(CurrentUserInfoControl).GetTypeInfo().Assembly,
                        "Web.Common"
                        )
                    ));
            });

            services.AddMemoryCache();
            services.AddDistributedMemoryCache();
            services.AddSession();
            services.AddKendo();

            services.AddAuthentication(IISDefaults.AuthenticationScheme);

            ServiceRegistrator.ConfigureServices(services);
            //services.AddAntiforgery(options => options.HeaderName = "X-CSRF-TOKEN");
            
            services.TryAddSingleton<IMenuHelper, MenuHelperImpl>(); 
            services.TryAddSingleton<IPageStateHelper, PageStateHelperImpl>();
            services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.TryAddSingleton<IRoleEditStateHelper, RoleEditStateHelper>();
        
            services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
                .AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseStaticFiles();
            app.UseCookiePolicy();
            
            //enable session before MVC
            app.UseSession();

            app.Use(async (context, next) =>
            {
                if (context.User.Identity != null)
                {
                    var workContext = context.Session.GetSessionWorkContext();
                    var currentUserName = context.User.Identity.Name;
                    if (!string.IsNullOrEmpty(currentUserName))
                    {
                        if (workContext == null)
                        {
                            workContext = new WorkContext() { CurrentUser = new Core.Common.Business.UserToken(Guid.Empty, currentUserName) };
                            context.Session.SetSessionWorkContext(workContext);
                        }
                        else
                        {
                            if (workContext.CurrentUser != null)
                            {
                                //User did change!
                                workContext.CurrentUser = new Core.Common.Business.UserToken(Guid.Empty, currentUserName);
                            }
                        }
                    }
                    else
                    {
                        await context.Response.WriteAsync("Unable to identify the logged in user. Please try to login again via windows authentification.");
                    }
                }
                else
                {
                    await context.Response.WriteAsync("Unable to identify the logged in user. Please try to login again via windows authentification.");
                }
                await next();
            });

            app.UseMvc();

        }
    }
`

This is my current Web.Config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <!-- To customize the asp.net core module uncomment and edit the following section. 
  For more info see https://go.microsoft.com/fwlink/?linkid=838655 -->
    <system.webServer>
      <handlers>
        <remove name="aspNetCore" />
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore  processPath="dotnet" arguments=".\Web.Administration.dll"  stdoutLogEnabled="true" stdoutLogFile="W:\Logs\Log" hostingModel="inprocess" />
      <security>
        <authentication>
          <anonymousAuthentication enabled="false" />
          <windowsAuthentication enabled="true" />
        </authentication>
      </security>
	  </aspNetCore>
    </system.webServer>
  </location>
</configuration>
```

The IIS is configurated with:

- Win Auth => Enabled

- Anonym Login => Disabled

- App pool created and that app pool has "No managed code" assigned (as runtime).

The issues I got:

**1.** 
I published with Deployment Mode Self-Contained.
In that combination I got a Internal Server Error 500.19 ([screenshot](https://imgur.com/a/rdX3i8r)) which is telling me that my configuration file is wrong.
I the msdn article about the support of Windows Auth for the core framework which can be found [here](https://docs.microsoft.com/de-de/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio).
However I am unable to find the configuration issues.

**2.** 
After I **removed** the authentication part in the web.config I got a bit further ahead. (Still the self-contained package from before except the modified web.config)

Now I get a HTTP Error 500.31 - ANCM Failed to Find Native Dependencies (screenshot).

The logfile is giving me strange informations. It says:
______________________________________________________________________
Failed to load the dll from [C:\inetpub\WebAdmin\hostpolicy.dll], HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll from [C:\inetpub\WebAdmin\]
______________________________________________________________________
I double checked and the dll is existing withing the folder C:\inetpub\WebAdmin\

**3.** 
Now it gets tricky. I tried another approach and changed the Deployment Mode from Self-Contained to "Framework-Dependend".

The target Framework is still netcoreapp2.2.

Here I get a HTTP Error 500.30 - ANCM In-Process Start Failure with not much info (screenshot)

However the iis process is having a unhandled exception and thatfor the log which he should write has been created but no content is in there.

This is actually a new behavior which I just got by walking through each step I tried so far.

Before this behavior I got [this](https://github.com/dotnet/cli/issues/9941) error: Access to the path 'C:\WINDOWS\system32\config\systemprofile' is denied

I tried to solve the access issue by giving the iis user the permission for this folder. The exception disapeared but I did not get the site. I got a random html content which bascially says "hello new asp.core user".
______________________________________________________________________
All those things did not work and I am all out of ideas. Anyone has some ideas?

One last thing that confuses me. My Project is a ASP.NET Core mvc project.

But in the project property page the output it set to ConsoleApp (it actually generates the exe file as well as the equally named dll file). As I told you I have tried it on a smaller scale project. Which means I simply created an empy asp core app. In the project properties of this one it also had ConsoleApp set as output.
However after I build it the ouput directory only had the dll and never an additional exe file. I am telling you this because as far as I know the inprocess hosting of asp core within iis requires a dll as far as i know.
I allways refered in the web.config to the dll but I am confused why the one project generates the console app and the other one does not (even thought both have console app as output).

Additionally I of course have installed all the sdk (2.2-3.0) as well as the asp core hosting bundle (runtime & sdk 2.2-3.0)

I hope you have some ideas because I really am stuck here.

Best regards

Simon

**Comment by anurse** [comment]
> In that combination I got a Internal Server Error 500.19 ([screenshot](https://imgur.com/a/rdX3i8r)) which is telling me that my configuration file is wrong.

Looking at your config, the mostly likely cause here is that Windows Authentication is configured but not installed (via the Windows Features or Server Roles and Features UI). This is an IIS issue though, not really ASP.NET Core.

> Now I get a HTTP Error 500.31 - ANCM Failed to Find Native Dependencies (screenshot).

This is most commonly a bitness mismatch. For example, if you publish for 32-bit but run in a 64-bit IIS worker process (or vice-versa), you can get this error.

> I got a random html content which bascially says "hello new asp.core user".

Can you clarify exactly what you see here? The default template is basically that, so I'm not sure what you mean when you say that you don't get the site. The only thing that should be producing a page like this is the default site template.

> But in the project property page the output it set to ConsoleApp (it actually generates the exe file as well as the equally named dll file).

Yep, this is expected. All ASP.NET Core apps (even in-proc hosted) are Console apps.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
