### ISSUE TITLE
Plugin base application aproch

### ISSUE THREAD

**Issue by OmidID** [aspnet/AspNetCore#14678]
I found there is a new way exists in .Net Core 3 to resolve assembly and load dll 
https://github.com/dotnet/samples/tree/master/core/extensions/AppWithPlugin
I success to manage plugin structure for the application. The main problem i have there is no way exists to load view from the build output directory. `FileProviders` in `RazorViewEngineOptions` was removed and have `IFileProviders` implementation and register it in services is not helping to load razor files from embedded assembly.
 
Project structure:
```
MainPluginHostApp
 --> Controllers
 --> Views
 --> Plugins
 ----> Plugin1/Plugin1.dll
 ----> Plugin2/Plugin2.dll
```

The views and static files are embedded in assembly.
There are some limitation I found. 
1. I don't know how is it possible to load View for that specific plugin if plugin try to return `View();` in Actions.
2. Is it possible to map a path to specific assembly? This is possible in Blazor using `Map("/web-app1")` and `UseClientSideBlazorFiles<WebApp1>` and I cannot find something similar for Razor pages or MVC.
3. To have access to the Asp.Net Core references is to have `<Project Sdk="Microsoft.NET.Sdk.Web">` and the main question is what's will be happen to the class library?! How can I have shared library with Asp.Net references? Nuget packages are not updated for .Net Core 3

**Comment by Eilon** [comment]
@sebastienros

**Comment by sebastienros** [comment]
You can use the Orchard Core Framework that provides modularity to ASP.NET apps. Here is a Samples repository: https://github.com/OrchardCMS/OrchardCore.Samples

I presented the framework during dotnet conf which is recorded in this video: https://www.twitch.tv/videos/486001703

**Comment by OmidID** [comment]
I'll try to find out how OrchardCore is working.
How about Class Library with Asp.Net references?

**Comment by sebastienros** [comment]
This is how you use the framework. You create class libraries that act like micro applications, with controllers, views, middleware, static assets, and reference them from you app. The app and each module only require to reference a specific nuget package from Orchard Core.

**Comment by OmidID** [comment]
I found out this project it's really helpful
https://github.com/natemcmaster/DotNetCorePlugins

Actually, I found out the Views are compiled in another assembly that should be load separately 
https://github.com/natemcmaster/DotNetCorePlugins/blob/master/src/Plugins.Mvc/MvcPluginExtensions.cs

For item 2 I think it's not possible and for Item 3 the only way is to change SDK to `Microsoft.NET.Sdk.Web` and then change the output to class library
