### ISSUE TITLE
MVC + Endpoint routing is not passing custom metadata on fallback routes

### ISSUE THREAD

**Issue by Fraaankes** [aspnet/AspNetCore#14679]
### Describe the bug
The DisplayName and Metadata that is assigned in `app.UseEndpoints` is not available when inspecting the result from `Request.HttpContext.GetEndpoint()` when using the `MapFallbackToController` extension method.

### To Reproduce
Using ASP.NET Core 3.0.0 MVC

In Startup.cs
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}")
                    .WithDisplayName("Default Controller Route")
                    .WithMetadata("Custom.. but default metadata"); ;

                endpoints.MapFallbackToController("Fallback", "Home")
                    .WithDisplayName("Fallback route")
                    .WithMetadata("Custom metadata");
            });
        }
```
With the controller looking like this
```
public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var r = Request.HttpContext.GetEndpoint();
            return Ok(r.Metadata.Select(x => x.ToString()));
        }

        [Route("fallbackaction", Name = "fallback action")]
        public IActionResult Fallback()
        {
            var r = Request.HttpContext.GetEndpoint();
            return Ok(r.Metadata.Select(x => x.ToString()));
        }
    }
```

### Expected behavior
The DisplayName and Metadata added in the builder is assigned to the matched endpoint.

### Screenshots
When hitting the default endpoint the displayname + metadata is present:
![image](https://user-images.githubusercontent.com/15279743/66071150-ed21b900-e552-11e9-9c1e-b9f4c12f46e2.png)

When hitting the fallback endpoint it is missing:
![image](https://user-images.githubusercontent.com/15279743/66070302-586a8b80-e551-11e9-8cba-f2c5ae5d59c7.png)

**Comment by rynowak** [comment]
This is currently by design - the *fallback endpoint* that's matched originally will be discarded so that the *real endpoint* that represents your controller can be seen by middleware (like auth).

Is there something specific that you're trying to accomplish?

**Comment by Fraaankes** [comment]
What im trying to accomplish is the behaviour I had in 2.2 where it was possible to inject an `IRouter` instance into a custom middleware, and then using something like this:
```
var routeContext = new RouteContext(context);
await router.RouteAsync(routeContext);
if (routeContext.Handler == null)
    // No routes match this request
```
I would be able to detect if the request would ultimately result in a 404 and as such skip doing some API calls in the middleware running before ASP.NET.
With the new fallback route catching everything, I wanted to use the metadata to be able to recognize which route was selected, and based on that, skip or not.

As a workaround I am able to use the following `endpoint.Metadata.GetMetadata<RouteAttribute>()?.Name == "fallback action"`, but maybe it should be documented that those extension methods are not expected to work in all cases?

**Comment by rynowak** [comment]
> I would be able to detect if the request would ultimately result in a 404 and as such skip doing some API calls in the middleware running before ASP.NET.

You can do this by putting your middleware between `UseRouting` and `UseEndpoints`. You shouldn't need a fallback route to detect that nothing matched.

```C#
app.UseRouting();

app.Use(next => context =>
{
    if (context.GetEndpoint() == null)
    {
        // nothing matched this request
    }

    return next(context);
});

app.UseEndpoints(...);
```

Does this help?

**Comment by Fraaankes** [comment]
Yes, removing the fallback route and using that I can detect that nothing will match, but how do I go about showing anything to the user ?

`app.UseStatusCodePagesWithReExecute("/fallbackaction");` does not seem to do anything, no matter in which order it is added to the pipeline.

And transforming the 404 to a 302 using `app.UseStatusCodePagesWithRedirects("/fallbackaction")` is at least doing something, but not cool, as the second request would then be matching an endpoint causing the API lookup to happen anyway.

**Comment by rynowak** [comment]
Can you provide a more complete code sample as well as a description of what you're trying to happen? Sorry, I'm still confused about what you're trying to do.

If you want to execute some code, a fallback route is a good way to do that - it's unclear to me what you're trying to do beyond that.
