### ISSUE TITLE
How to use ASP .NET Core 3.0 without shared framework

### ISSUE THREAD

**Issue by jhudsoncedaron** [aspnet/AspNetCore#14686]
This is probably just a documentation problem.

Tried to upgrade everything to .NET Core 3. Got issues.

Instructions: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio

Actual root issue: we're in a place where trying to use the shared framework is a bad idea, but all the instructions try to use the shared framework. In any case, if given the choice, we'd rather not use the shared framework due to too many cases of being burnt by backwards-breaking changes when somebody else upgrades the framework.

We ship net core. We have seriously considered shipping hand-modified net core. We expect to ship all of our dependencies and install as one package on top of Windows Server core and be done. We don't want to add any dependencies we don't ship.

The last several security bugs in ASP .NET Core required us to take no action because they were in ASP .NET Core features we had turned off (and in most cases dyked out at compile time by not referencing the .All package).

So I want to reference Microsoft.AspNet.something, and ensure I get an actual NuGet package with actual references in *.deps.json and have the dlls actually appear in publish after dotnet publish so I can pick them up and ship them. Furthermore I expect to be able to snapshot the .nupkg out of .nuget on the build server, move them to cold storage, come back three decades later, install the archived build OS and SDK, and be able to build a patched binary.

**Comment by Pilchie** [comment]
I think you're conflating two things:

1. Shared framework versus individual packages.
2. Framework dependent deployment versus self-contained deployment.

In .NET Core 3, we no longer produce individual packages for every assembly, we *only* produce the shared framework.  There are numerous issues here and in aspnet/Announcements and dotnet/sdk and dotnet/corefx that discuss the reasoning for this.

However, `dotnet publish --self-contained` will still produce a single folder that has all the assets required to run the app.

As for snapshotting, the reference packs and targeting packs are available on nuget as a download mechanism, but they aren't regular NuGet packages.

**Comment by Pilchie** [comment]
@dsplaisted - have you got a pointer to public docs about how Framework References work and what happened here?

**Comment by dsplaisted** [comment]
Here is an overview: https://github.com/dotnet/designs/pull/50/files#diff-ebf265d0476041dd8cab82fa24ab5b0e

**Comment by jhudsoncedaron** [comment]
Looks like I've got a lot more to do. I've got a dynamic plugin-model where additional dlls that weren't there at compile time get loaded on site. If those dlls in turn have dependencies, the dependencies are in the host systems .nuget folder. (We thought this shouldn't occur but it turns out it does when the plugin dll loads a database driver...) The mapping between netcoreapp and netstandard is found in Microsoft.NetCore.App.nuspec so I actually read that file in to get it. Looks like it's somewhere else now.

(...and if we shipped a modified net core, the plugin gets it. hazards of being a plugin... we're not so insane as to break the ABI contract of netcore...)

**Comment by dsplaisted** [comment]
@jhudsoncedaron We've added some better plugin support for .NET Core 3.0 which may help you.

@jeffschwMSFT Is there documentation on plugin support in .NET Core?

**Comment by jeffschwMSFT** [comment]
Check out the samples here: https://github.com/dotnet/samples/tree/master/core/extensions/AppWithPlugin.  We do not currently have any automatic way to read dependencies from the nuget cache, your current solution coupled with some of these samples may offer what you are looking for.

cc @vitek-karas

**Comment by jhudsoncedaron** [comment]
lol; I just discovered something surprising about the build-time resolver. https://github.com/dotnet/buildtools/issues/2264

I seriously suspect my code's a lot more advanced than yours right now. I haven't started resolving dependencies of dependencies by tree yet (to load the highest dependent version in a diamond) but I will probably have to soon.

But loading Kestrel as a dynamic plugin just had a monkey wrench thrown into it. That planned feature's probably going to get canned now. (Some proposed plugin wanted to host a web server where the main program is different kind of TCP server that definitely isn't linked against .Web.)
