### ISSUE TITLE
CONTRIBUTING.md could use some additional information

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore#14688]
### Is your feature request related to a problem? Please describe.
I just asked this question on an issue where i am about to provide a PR:

> What is the procedure for PR's? Does the person, who executes the PR merge, set the branch target or is this supposed to be done by the PR author?
> 
> Also if it isn't the author - when creating a branch in my fork can i just checkout -b from master then?

Perhaps this information could be useful to anyone who is thinking about providing a PR? In another repo i was contributing to for example i was asked to rebase on a certain branch before providing the PR. (Might have been because you could not change the target branch back then)

### Describe the solution you'd like
Updated Docs by someone who can answer these questions, perhaps some FAQ by contributors section?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @taori.
We make decisions regarding where each change should go (which release) during our triage process. And that's what will determine the target branch. In majority of the cases we would accept PRs to the `master` branch, as that's our next big release (as of today it's for 5.0). As for merging, we merge all the PRs - community members can't do that.

To summarize - always start from master as that's the most generic case. In some cases, yes, we will ask authors to re-target their PRs so we can speed up the release process for certain changes.
Including this in the contributors guideline may be more misleading.
