### ISSUE TITLE
Windows authentication across untrusted domains

### ISSUE THREAD

**Issue by peval27** [aspnet/AspNetCore#14693]
I'm developing a web service based on ASP.NET Core 2.2 + IdentityServer4, supporting both credentials authentication (i.e. username+password) and Windows authentication. I am not able to login using a domain user from an untrusted domain.

1. Using this version of ASP.NET Core '2.2'
2. Write this code `HttpContext.AuthenticateAsync(Microsoft.AspNetCore.Server.IISIntegration.IISDefaults.AuthenticationScheme)` or `Challenge(Microsoft.AspNetCore.Server.IISIntegration.IISDefaults.AuthenticationScheme)`
3. Try to access the resource and when prompted for Windows credentials (i.e. Challenge), type untrusted domain credentials.

### Expected behavior
Domain user can log in. (Given I could specify the untrusted domain somewhere).

### Notes
The two untrusted domains have DNS stubs so they can 'know' each others.

The final goal is to use Http.Sys (instead of IIS) or even Kestrel 3.0, but for now I was thinking that using IIS would be the easier thing.

**Comment by blowdart** [comment]
This is more a windows configuration issue, but with no trust between the two domains I don't believe its going to work, the server isn't going to be able to validate the untrusted domain due to the lack of trust.

**Comment by peval27** [comment]
Hi @blowdart ,

thanks for your help. I was hoping that from the application I could specify the untrusted domain we want to authenticate against, but it may open up security concerns if the two domain aren't trusted each other. 

Looking forward to an answer re: windows configuration though.

Thanks,

**Comment by blowdart** [comment]
That's beyond us, it's a Windows AD configuration question and not one I'd feel comfortable even trying to answer.

**Comment by peval27** [comment]
@blowdart Any idea who can I ask it?

I tried on SO [here](https://stackoverflow.com/questions/58198967/windows-authentication-across-untrusted-domains) but still no luck 

Thanks again for your help, much appreciated!

**Comment by blowdart** [comment]
Honestly no. I can't even find AD documentation under the Windows server site.

**Comment by peval27** [comment]
Ok so you start feeling my pain! 😄

**Comment by blowdart** [comment]
Talked to some windows friends.

https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/forest-design-models is the overview, which you should read the forest trust sections to understand what you're going to do, then https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754626(v=ws.11) are the actual steps.

Please understand the security implications of forest trusts before implementing them :)

**Comment by blowdart** [comment]
Closing as answered, and also really a windows issue.
