### ISSUE TITLE
[Blazor] AuthorizeView Policy=<value> bug when <value> comes from variable

### ISSUE THREAD

**Issue by henkla** [aspnet/AspNetCore#14699]
### Description
In **Blazor**, When trying to use tag `AuthorizeView Policy=<some-value>` with property value being a string variable, it does not behave the same as if property value was a raw string.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.1'
2. Run this code 
```
<AuthorizeView Policy=ADMINS_ONLY >
    <Authorized>
        Authorized...
    </Authorized>
    <NotAuthorized>
        NotAuthorized
    </NotAuthorized>
</AuthorizeView>

@code {
    private string ADMINS_ONLY = "AdminsOnly";
}
```

3. Should work like this 
```
<AuthorizeView Policy="AdminsOnly">
    <Authorized>
        Authorized...
    </Authorized>
    <NotAuthorized>
        NotAuthorized
    </NotAuthorized>
</AuthorizeView>
```

`blazor.server.js:15 [2019-10-03T11:20:53.249Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions in 'CircuitOptions.DetailedErrors'.`

### Expected behavior
The AuthorizeView should call the AuthorizationHandler as provided by the policy setup (in this case: the policy named "AdminsOnly").

Update: clearifying area of effect

**Comment by rynowak** [comment]
String properties require the `@` to use variable/expressions. My guess is that this is passing the value `ADMINS_ONLY` into your `AuthorizeView` and not `AdminsOnly` as you expect.

Try:
```html
<AuthorizeView Policy="@ADMINS_ONLY">
```

**Comment by henkla** [comment]
Wow. That's pretty... dumb of me. Thanks.

**Comment by rynowak** [comment]
no worries 👍
