### ISSUE TITLE
Live Reload of Blazor Server Side

### ISSUE THREAD

**Issue by bansalankit2601** [aspnet/AspNetCore#14703]
Currently while running Blazor Server side,Live reload does not work out .

It requires building of application time and again to make a simple change in the html part.

Is there any way in which we can  make changes to html without stopping and building the application.

Also tried out some post which was regarding live reload.Does not work out so well.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is something we track as part of https://github.com/aspnet/AspNetCore/issues/5456
