### ISSUE TITLE
[Blazor-WebAssembly] Guidance: How to respond to SignalR events that require using the HttpClient object.

### ISSUE THREAD

**Issue by rxelizondo** [aspnet/AspNetCore#14710]
We have a PWA application that is built on top of Blazor (WebAssembly), the application uses SignalR. In the perfect world, we would like the following to ocurr:

1. Get the SignalR event from JavaScript.
2. From JavaScript we would like to call a .NET function.
3. From within the .NET function we would like to make web-api calls.

The problem occurs in point number 3, This is because in order to make the web-api calls we need to obtain a reference to the HttpClient object (as far as I know) and I am not sure how we are supposed to get that reference in this particular scenario.

 What would be the guidance to making this work? More specifically, how do we obtain reference to object managed by the DI infrastructure under this scenario?

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rxelizondo.
When you're initializing your object, you can pass HttpClient instance (from the component it's being initialized in) in and store it. Then use that as necessary. FYI: JSInterop can call into instance methods too.

**Comment by rxelizondo** [comment]
@mkArtakMSFT 

The thing is that the call is being initiated in **_JavaScript_** (from SignalR). At that point you can't call anything other than a **_static .NET method_** because no .NET instance object references exists on that scope.

So the question boils down to how do we obtain a reference to the HttpClient object from within the .NET static method call..... in a clean way, not a hacky way.

By the way, I realize there may be better ways to achieve what we are trying to do, we are simply exploring the different options at this time.

Thanks.
