### ISSUE TITLE
Does the method FilterHealthChecks in HealthCheckMiddleware have any use?

### ISSUE THREAD

**Issue by huysentruitw** [aspnet/AspNetCore#14711]
Talking about [this method](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/HealthChecks/src/HealthCheckMiddleware.cs#L89).

It's private and, as far as I can see, never called. Should it be removed?

**Comment by rynowak** [comment]
You're right. That's dead code. Want to send a PR to remove?

**Comment by huysentruitw** [comment]
Sure, which branch should I target?

**Comment by rynowak** [comment]
master
