### ISSUE TITLE
'unsafe-eval' required for .net core 2.2 POST to IssuerAddress (OIDC)

### ISSUE THREAD

**Issue by 99littlebugs** [aspnet/AspNetCore#14721]
We are using ADFS with OpenID Connect for an ASP.NET core application, which we just upgraded from 2.0 to 2.2. 

Once upgraded to 2.2, we found that the form POST to the ADFS server required our content security policy to have ['unsafe-eval'](https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval). The string in question is `window.setTimeout('document.forms[0].submit()', 0);`. 
In 2.0, the script just reads `document.form.submit()`, and therefore works fine even with our CSP. 

We managed to get around this and only relax the policy when the user has no claims, aka, is trying to login, but it still seems like we are missing something. 
* What is the point of setTimeout with a 0? 
* Why does the argument of setTimeout need to be a string? 

### To Reproduce
1. Setup OIDC
2. Set a content security policy
3. Run code
4. Note how 2.2 will get blocked by browser (Chrome) but 2.0 will not. 

### Expected behavior
To not need to have a more relaxed content security policy for page that has the authentication form that is submitted via JavaScript.

**Comment by blowdart** [comment]
This is strange, that string only appears in test code that I can find. 

What's the URL of that form?

**Comment by 99littlebugs** [comment]
The URL is the homepage of our app (or wherever the authentication flow is coming from). It _seems_ to be coming from [BuildFormPost()](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/58bd5959f6210771071f676e1b68a217666a48f1/src/Microsoft.IdentityModel.Protocols/AuthenticationProtocolMessage.cs#L60) in [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet). I'm not sure how that repository relates to the standard .net core ones, as we aren't using any additional nuget packages for authentication. It was also hard for me to tell how those versions relate to the .net core versions and what that code used to look like.

**Comment by Tratcher** [comment]
AspNetCore uses IdentityModel to handle the OIDC protocol, including the form post. You can open this issue in their repo.
