### ISSUE TITLE
How to bundle static assets from multiple razor library packages

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/AspNetCore#14726]
Is there an AspNetCore built-in design for this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ToddThomson.
It's not clear exactly what you're asking for. You can read about static assets at https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#create-an-rcl-with-static-assets.
If the docs don't have an answer to your question, please try to provide more details about what your'e trying to achieve and reopen this issue.

**Comment by ToddThomson** [comment]
Sorry, my post was a bit terse!

I am clear on how to package static assets within a RCL. However, if I have AspNetCore 3 Web project that consumes multiple RCLs, is there a mechanism to bundle assets from these multiple RCLs? I would be interested in development time and production time scenarios. Issue #6349 mentions different bundling scenarios, but I am not clear if the design(s) were implemented.

**Comment by ToddThomson** [comment]
I took a look at ```Microsoft.NET.Sdk.Razor.StaticWebAssets.targets``` and there does appear to be a mechanism to determine static assets resolved from packages and included projects. Is there any guidance on how to utilize this to perform bundling?

**Comment by ToddThomson** [comment]
@mkArtakMSFT please consider reopening this issue. It appears that I cannot do this myself.

**Comment by ToddThomson** [comment]
Perhaps [AspNetCore Tooling Tests](https://github.com/aspnet/AspNetCore-Tooling/tree/master/src/Razor/test/testapps/) will provide some insights...

**Comment by mkArtakMSFT** [comment]
I'm a bit uncertain about what `bundling` aspect of this. All the content from each reference RCL project 's `wwwroot` folder will be available to the consuming web application.  The `Multi-project development flow` section in the docs talks about this: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#multi-project-development-flow

**Comment by ToddThomson** [comment]
@mkArtakMSFT OK, it is the publish step where all the _content/libRCL/wwwroot directories are created that I want to get access to from my consuming MVC Web project. I should be able to use the runtime aspnetcore bundler or a gulp based bundler to reference the _content/ directory.

What I am attempting to do is compose single js and css bundles from a set of included RCL packages  or included projects. I feel the answer is in the access to the ```_content\``` build directory. I will write a bit of code to test this out.

**Comment by ToddThomson** [comment]
Ok. So the MS AspNetCore project does not include a built-in bundler/minifier for static assets. I assumed that the NuGet package, that used bundleconfig.json was from Microsoft (I am migrating to AspNetCore 3 from AspNetCore 2). That's OK with me as I have always used gulp tasks.

So my question comes down to this:

 When publishing the MVC Web App that consumes multiple RCL packages, a ```publish\wwwroot\_content\* ``` directory is create with each RCL's static assets being added as subdirectories. Is this ```wwwroot\_content\**\*``` directory resource somehow available to post build gulp tasks?

**Comment by mkArtakMSFT** [comment]
@javiercn I will need your expertise here. Can you please see whether this is possible and how (if yes)?

**Comment by javiercn** [comment]
@ToddThomson We don't offer a solution for this out of the box, but all the infrastructure is done through MSBuild and there are extensibility points that should make this scenarios possible.

In particular, you should be able to add your own targets to get the list of all the assets in the app, run any code you want, and produce an updated list of assets that the app will use.

For example, you can add your own task to `ResolveStaticWebAssetsInputsDependsOn` on your web app project to:
* Get a list of all the assets you are interested on.
* Invoke your favorite bundler/minifier tools to create the bundles.
* Update the list of static web assets to reflect the updated list of assets.

**Comment by ToddThomson** [comment]
@javiercn Thank-you. I've looked at the Razor Sdk StaticWebAssets.targets tasks and will likely use:

```
<Target
    Name="_StaticWebAssetsComputeFilesToPublish"
    AfterTargets="ComputeResolvedFilesToPublishList"
    DependsOnTargets="ResolveStaticWebAssetsInputs">
```
as a guide for my target.
