### ISSUE TITLE
WebApi Batch Handler support in AspNetCore 3.0

### ISSUE THREAD

**Issue by Venkat4655** [aspnet/AspNetCore#14722]
### Bug information
In AspnetCore 2.1 supports the Batch handler in WebApi service. Is the batch handler configuration supports in 3.0 version? or it already exists in 3.0. How we use that Batch handler in Blazor component? Could you please provide suggestion for this?

**Comment by rynowak** [comment]
I'm not sure what you're referring to from ASP.NET Core 2.1 - can you provide a link?

**Comment by Venkat4655** [comment]
Hi Ryan,

check the following link for batch handler support,
https://devblogs.microsoft.com/aspnet/introducing-batch-support-in-web-api-and-web-api-odata/ 

Is this available in ASPNetCore 3.0?

**Comment by mkArtakMSFT** [comment]
This is not available in ASP.NET Core.
