### ISSUE TITLE
Unsupported version of Microsoft.AspNetCore.Mvc.RazorPages

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14729]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/683590/unsupported-version-of-microsoftaspnetcoremvcrazor.html)._

---
I'm extendign the class PageModel from Microsoft.AspNetCore.Mvc.RazorPages in a library that i will use in an asp.net razor page project.
I've onstalled from nuget the package Microsoft.AspNetCore.Mvc.RazorPages version 2.2.5.0 then i've tried to create a new page in an aspnet core razor page project. I0ve installed the latest sdk of .net core 2.2.401 and also the runtime 2.2.6 but when I try to compile the project i receive this error:

Errore	CS1705	L'assembly 'EDK4Net' con identità 'EDK4Net, Version=3.0.3.14, Culture=neutral, PublicKeyToken=null' usa 'Microsoft.AspNetCore.Mvc.RazorPages, Version=2.2.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' la cui versione è successiva a quella dell'assembly 'Microsoft.AspNetCore.Mvc.RazorPages' a cui viene fatto riferimento con identità 'Microsoft.AspNetCore.Mvc.RazorPages, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	TestAspNetCore	C:\ Users\edika. VCI\Source\Repos\TestAspNetCore\TestAspNetCore\Pages\Login.cshtml.cs

In my asp.net core project, the SDK Microsoft.AspNetCore.App used is the 2.2.0 even if I've installed the latest version of the SDK. How can I force to use the 2.2.5 of Microsoft.AspNetCore.Mvc.RazorPages in the asp.net project? I've tried to manually install from nuget the  2.2.5 version but without success. The project still use th 2.2.0

---
#### Visual Studio Feedback System on 8/8/2019, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/8/2019, 11:32 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You can enforce the use of a specific version of the runtime by setting the `RuntimeFrameworkVersion` property in your project file.
You can read more about this at: https://docs.microsoft.com/en-us/dotnet/core/versions/selection#self-contained-deployments-include-the-selected-runtime
