### ISSUE TITLE
verbatim prefix error in razor page

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14728]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/689167/verbatim-prefix-error-in-razor-page.html)._

---
Hi,

I am trying to compare the current hour to another integer (e.g. 12). I'm getting a design time and compile time error. I figured out that it is due to an unnecessary verbatim prefix. Here is the code:

@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    var applicationName = @Assembly.GetEntryAssembly()?. GetName(). Name ?? &quot;(Unavailable)&quot;;          // Get the assembly name.
    var greeting = ( DateTime.Now.Hour &lt; 12 ) ? &quot;Good Morning&quot; : &quot;Good Afternoon&quot;;
}

I get a red squiggly under the ' &lt;' in the second line of code, with an error of '... ) expected ;expected'.

If I remove the @ from before @Assembly, the error goes away.

If I swap the 2 lines of code it compiles and runs fine.

---
#### Visual Studio Feedback System on 8/12/2019, 02:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/13/2019, 01:50 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You're already within the code scope (`@{ ... }`) where the context is C#. You should not use extra `@` transitions within that context.
