### ISSUE TITLE
New gRPC project with Docker

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#14738]
1. Create a new gRPC project
2. Select Docker
3. Run project in VS with Docker

Expected:
I can call my gRPC service with https

Actual:
Visual Studio launches Docker with only a http port

@shirhatti can you look into what we want to do here?

**Comment by JamesNK** [comment]
What `launchSettings.json` contains when a new gRPC project with Docker is created:

```json
{
  "profiles": {
    "Server": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001"
    },
    "Docker": {
      "commandName": "Docker",
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
      "environmentVariables": {},
      "httpPort": 55000
    }
  }
}
```

What is required to have a HTTPS port:

```json
{
  "profiles": {
    "Server": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001"
    },
    "Docker": {
      "commandName": "Docker",
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
      "environmentVariables": {
        "ASPNETCORE_URLS": "https://+:443",
        "ASPNETCORE_HTTPS_PORT": "44378"
      },
      "useSSL": true,
      "sslPort": 44378
    }
  }
}
```

**Comment by JamesNK** [comment]
ping @shirhatti

**Comment by shirhatti** [comment]
```diff
{
  "profiles": {
    "GrpcService6": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001"
    },
    "Docker": {
      "commandName": "Docker";
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
-      "publishAllPorts": true
+      "publishAllPorts": true,
+      "useSSL": true
    }
  }
}
```

@JamesNK I just tried this. I believe your workaround is not required. All that's missing is the useSSL property in launchSettings

**Comment by shirhatti** [comment]
I'll send a PR to fix the template

**Comment by shirhatti** [comment]
Pinging @pratiksanglikar to sanity check this as he's the most familiar with this

**Comment by pratiksanglikar** [comment]
We look for the `useSSL` flag followed by whether `https` is present in the `applicationUrl` to determine if https is supported.
In a new gRPC project I created, it looks like the https mapping was not created.
I will dig into it to see what the actual problem is.

**Comment by pratiksanglikar** [comment]
Hi @JamesNK , @shirhatti  this bug had been fixed in 16.3 but was regressed with one of our recent changes for port mappings.
It has been recently fixed and would be available in 16.5 P1.

**Comment by JamesNK** [comment]
Great, thanks.

Since it has been broken twice, is there additional testing to keep it working into the future?

**Comment by pratiksanglikar** [comment]
I'll add an OGF for our CTI to test gRPC apps in the full round of testing.

**Comment by JamesNK** [comment]
Great.

Nothing else to do here. Closing.
