### ISSUE TITLE
web.config pointing to wrong application path when running in VS

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/AspNetCore#14737]
When launching one of my ASP.NET Core 3 projects from Visual Studio 2019, I get a `HTTP Error 500.0 - ANCM In-Process Handler Load Failure` browser message when running the app through IIS Express (F5, to run in VS)

I checked the Windows event log and this is the error:

```
Application 'X:\GitSource\MySolution\PortalWeb\' failed to start. Exception message:
Executable was not found at 'X:\GitSource\MySolution\PortalWeb\.\PortalWeb.exe'

```
Not surprising, since the executable actually lives at `X:\GitSource\MySolution\PortalWeb\bin\Debug\netcoreapp3.0\PortalWeb.exe`

Any idea why the app has a bad path for the executable?

I have another Web application in the same solution that starts just fine.  

Thoughts?

**Comment by jkotalik** [comment]
Do you have a web.config file with your project? Does that have a path to the exe directly?

cc @BillHiebert

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
