### ISSUE TITLE
Deserialization of Arrays in Get Methods Fail to Parse Correctly

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14731]
_From @MikeAllen775 on Thursday, October 3, 2019 8:04:13 PM_

Just upgraded my API from .NET Core 2.2.3 to .NET Core 3.0.0.  For other reasons (using Swagger) I needed to downgrade JSON serialization back to Newtonsoft by using AddNewtonsoftJson in my startup.

Previous GET methods that accept an array argument were no longer parsing it correctly when passed JSON in JavaScript(which ends up defaulting to a comma-delimited string).

For example:

Sending the following JSON in JavaScript:

`{ values: ["a", "b", "c"] }`

Results in a querystring that looks like:

`?values=a,b,c`

In the C# method:

`[HttpGet]
public async Task<IActionResult<MyClass>> Get(string[] values) 
{
  // If .NET Core 3.0, values is an array with a single element of "a,b,c".
  // If .NET Core < 3.0 values is an array with 3 elements.
}
`

_Copied from original issue: dotnet/core#3543_

**Comment by scalablecory** [comment]
_From @carlossanlop on Thursday, October 3, 2019 8:43:20 PM_

@JamesNK should this issue be transferred to the [Newtonsoft repo](https://github.com/JamesNK/Newtonsoft.Json)?

**Comment by scalablecory** [comment]
_From @JamesNK on Thursday, October 3, 2019 8:48:12 PM_

It should be in aspnet/aspnetcore

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by MikeAllen775** [comment]
After some further testing, this appears to be a bug in swagger-client (version 3.9.4) code, not AspNetCore.  Swagger javascript client is producing a querystring of "values=a,b,c" when running under 3.0, instead of "values=a&values=b&values=c".

Please close this issue, and I apologize for the false alarm.

**Comment by scalablecory** [comment]
Thanks for the followup! Glad you found the problem.
