### ISSUE TITLE
Nullable with Razor and CS8632

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14732]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/583409/nullable-with-razor-and-cs8632.html)._

---
I've upgraded a solution from Core 3.0.0-preview3 to 3.0.0-preview5 and I have switched all my projects in my solution to use the `&lt;Nullable&gt;` and switching the language version to `preview` in order to benefit from the C# 8 nullable feature.

All my `*.razor` files which use the `?` nullability specifier product `CS8632` warnings:

&gt; The annotation for nullable reference types should only be used in code within a '#nullable' context.

I had to manually add `#nullable enable` in the `*.razor` files, and also in some `*.cs` files of the same project as a temporary fix:

```cs
@functions {
    #nullable enable
    // ...
}
```

Which now produces:

```cs
    // ...
    public class Dump : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 32 &quot;S:\git\foo\Components\Pages\Dump.razor&quot;

#nullable enable
```

Here is the project file I'm using:

```csproj
&lt;Project Sdk=&quot;Microsoft.NET.Sdk.Web&quot;&gt;

&lt;PropertyGroup&gt;
    &lt;TargetFramework&gt;netcoreapp3.0&lt;/TargetFramework&gt;
    &lt;LangVersion&gt;preview&lt;/LangVersion&gt;
    &lt;Nullable&gt;enable&lt;/Nullable&gt;
  &lt;/PropertyGroup&gt;

&lt;ItemGroup&gt;
    &lt;PackageReference Include=&quot;Microsoft.AspNetCore.Mvc.NewtonsoftJson&quot; Version=&quot;3.0.0-preview5-19227-01&quot; /&gt;
  &lt;/ItemGroup&gt;

&lt;ItemGroup&gt;
    &lt;ProjectReference Include=&quot;.. \Passport.Client\Passport.Client.csproj&quot; /&gt;
  &lt;/ItemGroup&gt;

&lt;/Project&gt;
```

---
#### Visual Studio Feedback System on 5/27/2019, 01:53 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/1/2019, 01:56 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This has been fixed sometimes about 3.0-preview8 timeframe. You should be able to switch to the RTM release and avoid this issue.
