### ISSUE TITLE
Bad responses: DbMultiUpdateEf, Json, Json, OrchardBlog, OrchardBlog ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14743]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| DbMultiUpdateEf | Linux, Physical, http, KestrelSockets | 10/3/19 7:14:11 AM +00:00 | 68 |
| Json | Windows, Physical, http, IISInProcess | 10/1/19 3:21:16 PM +00:00 | 6917207 |
| Json | Windows, Cloud, http, IISInProcess | 10/1/19 6:02:18 PM +00:00 | 1088015 |
| OrchardBlog | Linux, Cloud, http, KestrelSockets | 9/28/19 8:49:31 PM +00:00 | 48 |
| OrchardBlog | Windows, Cloud, http, KestrelSockets | 9/30/19 6:11:21 PM +00:00 | 120 |
| Plaintext | Windows, Physical, http, IISInProcess | 10/1/19 3:18:12 PM +00:00 | 6909643 |
| Plaintext | Windows, Cloud, http, IISInProcess | 10/1/19 5:59:05 PM +00:00 | 1090535 |
| PlaintextNonPipelined | Windows, Physical, http, IISInProcess | 10/1/19 3:19:45 PM +00:00 | 6917479 |
| PlaintextNonPipelined | Windows, Cloud, http, IISInProcess | 10/1/19 6:00:41 PM +00:00 | 1119087 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Fixed
