### ISSUE TITLE
Blazor 3.0 official release asyc function with parameter?

### ISSUE THREAD

**Issue by gxomin** [aspnet/AspNetCore#14753]
I am trying to create a async function in Blazor WebAssembly project, in preview 8, this worked:

```
  <th @onclick="@(async ()=> await Sort(column.Name))">@column.Name</th>

@code {
    async Task Sort(string column)
    {
        await Http.PostJsonAsync<SelectResult>("Data/Get");
        this.StateHasChanged();
    }
}
```
With 3.0 final release, it does not work anymore. Compiler complains:
Cannot convert lambda expression to type 'object' because it is not a delegate type	...\Pages\Table.razor

Can you please suggest how to do async event with parameters? Thanks very much.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gxomin.
You should be able to resolve this by adding  `@using Microsoft.AspNetCore.Components.Web` to your .razor file (or _Imports.razor, which is the preferred place for this particular namespace).

**Comment by mythrz** [comment]
mouse right click "quick actions" could be added in these type of errors? 
had the same problem, solved. ty
