### ISSUE TITLE
Set SameSite Cookies to None Based on Context

### ISSUE THREAD

**Issue by williamsglasgow** [aspnet/AspNetCore#14757]
### Describe the bug
Need to set SameSite Cookies to None based on the Context of the Request.  For example, if a request is coming in from sites.google.com, I want to turn SameSite Cookies to None, otherwise leave it to the default of Lax.  This doesn't seem possible.

### To Reproduce
1. Using version 2.2 .402 of ASP.NET Core AddAuthentication service in the ConfigureServices section of the Startup.cs.

2. Additionally, add multiple cookie settings as such:
            .AddCookie("Cookies", "Cookies", option1 =>
            {
                // config cookie1
                option1.Cookie.Name = "Cookies";
                option1.Cookie.SameSite = SameSiteMode.Lax;
            })
            .AddCookie("Cookie2", "Cookie2", option2 =>
            {
                // config cookie2
                option2.Cookie.Name = "Cookie2";
                option2.Cookie.SameSite = SameSiteMode.None;
            });

3. Attempt to switch to "Cookie2" based on the context of the Request:
            app.Use(next =>
            {
                return async ctx =>
                {
                    if (ctx.Request.Host.Host.Contains("google"))
                    {

4. There is no way to switch the context.  The SameSite cookie setting is always set to "Cookies", which is specified in the DefaultScheme:
            services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            });

### Expected behavior
Should be able to switch from "Cookies" to "Cookie2" based on the context of the request, but this doesn't seem possible.

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.402\

Host (useful for support):
  Version: 2.2.7
  Commit:  b1e29ae826

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.2.107 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by blowdart** [comment]
Even with the November update which will add support for the none value this isn't really possible, not should you need to. Google's upcoming changes affect browsers, not the referring site. You need to browser sniff and react accordingly. We'll be providing instructions for that when the first preview build including it arrives next week.

**Comment by Tratcher** [comment]
Rather than using two different cookies, here's the proposed mitigation for toggling SameSite on individual cookies (based on user agent for compat reasons):
https://github.com/aspnet/AspNetCore/blob/54fda389718986dee66a77de29eccad82cad1f32/src/Security/Authentication/OpenIdConnect/samples/OpenIdConnectSample/Startup.cs#L35-L60
Note this still relies on the upcoming Nov patch.

**Comment by anurse** [comment]
This should be resolved in the upcoming patch. As @Tratcher said, there is a mechanism (which will be detailed in the announcement blog posts) for making this decision on a per-request basis.
