### ISSUE TITLE
Cannot refresh views at runtime

### ISSUE THREAD

**Issue by geotinc** [aspnet/AspNetCore#14754]
Hi all,

I migrate a project to asp.net core 3.0 and I cannot change view at runtime anymore.

I have added AddRazorRuntimeCompilation :
(note that the following code is in RCL static class and call from the startup.cs of my app)
```            
IMvcBuilder builder = services.AddMvc(config =>
            {
                config.ModelBinderProviders.Insert(0, new InvariantDecimalModelBinderProvider());
            }).
            AddNewtonsoftJson(options =>
            {
                options.SerializerSettings.ContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver();
                options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
            })
#if DEBUG
            .AddRazorRuntimeCompilation()
#endif
            ;
```

At runtime when I changed cshtml file :

I have the following
![image](https://user-images.githubusercontent.com/20421571/66253062-eff2f880-e762-11e9-8262-d3272691d959.png)

How can I fix that ?
Thanks a lot

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @geotinc.
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by geotinc** [comment]
Sorry for late answer please find sample project on my github : https://github.com/geotinc/AspNetCore/tree/master/WebApplication6

This problems occurs in 3.0 and 3.1 preview

Step to reproduce the problem :

1. Run the application in debug
2. Go to view /Home/Index.cshtml
3. Update text "Test3" for example
![image](https://user-images.githubusercontent.com/20421571/67299193-9d4c6700-f4ec-11e9-81d4-7ce74d5ba4ee.png)
4. Refresh web browser 
![image](https://user-images.githubusercontent.com/20421571/67299246-afc6a080-f4ec-11e9-8e28-ee900c976ea2.png)


Thanks for helping !

**Comment by mkArtakMSFT** [comment]
@pranavkm can you please look into this? Thanks!

**Comment by pranavkm** [comment]
@geotinc there's a known issue in the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` package in 3.1.0-preview1. You may workaroudn this by following the instructions here: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#preview1. 

That said, this is limited to the 3.1.0-preview1 release and you shouldn't see this in a 3.0 project that references the 3.0 RTM version of the package. Do you happen to have a minimal repro at hand?

**Comment by geotinc** [comment]
@pranavkm, I have the problem in .net core 3.0 also.

But in a small project, I cannot reproduce the problem..
Is there a way to now which assembly cause that problem ?

**Comment by geotinc** [comment]
Your last answer help me a lot...

In fact, Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation was only refrencered in my RCL project (because I have an extension class that do .AddMvc().AddRazorRuntimeCompilation().

I thought that if the RCL library reference the dll, It's not needed to reference the DLL in main app too...

It should be great to add a better exception :-)

Thanks a lot ;-)

**Comment by pranavkm** [comment]
Great that it worked out. Starting in 3.1-preview2, this requirement is removed. Referencing the RuntimeCompilation package in the RCL should suffice. Your current setup should continue to work without issues.

**Comment by geotinc** [comment]
Last question about this topic...

Views of my main project can now be refreshed at runtime.

But is there a way to update views from RCL project at runtime too ?

Thanks for answer
