### ISSUE TITLE
Bad responses: DbFortunesDapper, DbFortunesEf, DbFortunesRaw, HttpClient, HttpClientFactory ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14750]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| DbFortunesDapper | Linux, Physical, http, KestrelSockets | 10/5/19 12:55:10 AM +00:00 | 640 |
| DbFortunesEf | Linux, Physical, http, KestrelSockets | 10/5/19 12:56:31 AM +00:00 | 457 |
| DbFortunesRaw | Linux, Physical, http, KestrelSockets | 10/5/19 12:53:49 AM +00:00 | 684 |
| HttpClient | Linux, Physical, http, KestrelSockets | 10/5/19 1:01:57 AM +00:00 | 500 |
| HttpClientFactory | Linux, Physical, http, KestrelSockets | 10/5/19 1:04:30 AM +00:00 | 600 |
| HttpClientParallel | Linux, Physical, http, KestrelSockets | 10/5/19 1:03:12 AM +00:00 | 6 |
| MvcDbFortunesDapper | Linux, Physical, http, KestrelSockets | 10/5/19 12:59:11 AM +00:00 | 570 |
| MvcDbFortunesEf | Linux, Physical, http, KestrelSockets | 10/5/19 1:00:32 AM +00:00 | 403 |
| MvcDbFortunesRaw | Linux, Physical, http, KestrelSockets | 10/5/19 12:57:51 AM +00:00 | 460 |
| MvcDbMultiUpdateDapper | Linux, Physical, http, KestrelSockets | 10/5/19 12:51:07 AM +00:00 | 634 |
| MvcDbMultiUpdateEf | Linux, Physical, http, KestrelSockets | 10/5/19 12:52:29 AM +00:00 | 493 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by mkArtakMSFT** [comment]
https://github.com/aspnet/AspNetCore/issues/14760
