### ISSUE TITLE
With Asp.net core 3.0 SignInManager.IsSignedIn(User) allways reuturn false?but in 2.2 it works fine.Is that a debug?

### ISSUE THREAD

**Issue by riyuexing** [aspnet/AspNetCore#14755]
### this is my code of SignIn
```
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model,string returnUrl=null)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await UserManager.FindByNameAsync(model.UserName);
            if (user!=null)
            {
                await SignInManager.SignOutAsync();
                var result = await SignInManager.PasswordSignInAsync(
                user, model.Password, model.RememberMe, true);
                if (result.Succeeded)
                {
                    //var userName = HttpContext.User.Identity.Name;
                    var userName = UserManager.GetUserName(HttpContext.User);
                    //return RedirectToAction("Index", "Note");
                    return Redirect("/");
                }
                else
                {
                    ModelState.AddModelError("", "用户名或密码错误");
                    return View(model);
                }
            }
            else
            {
                ModelState.AddModelError("", "用户名或密码错误");
                return View(model);
            }
            
        }


```
but SignInManager.IsSignedIn(User) allways return false.and HttpContext.User.Identity.Name return null? 
```
@if (SignInManager.IsSignedIn(User))
{
    <form asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
        <ul class="navbar-nav">
            <li>
                <a href="javascript:;">@UserManager.GetUserName(User)</a>
            </li>
            <li>
                <a href="javascript:document.getElementById('logoutForm').submit()">注销</a>
            </li>
        </ul>
    </form>
}
```
I tried to use scaffold to generate the Identity code. It works fine?
but if i replace the razor page with in my project, it doesn't work.
Could anybody help me?

**Comment by davidfowl** [comment]
Show you startup code (all of it)

**Comment by riyuexing** [comment]
the startup.cs:

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace IdentityMVC
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddControllersWithViews();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                //endpoints.MapControllers();
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });
        }
    }
}

**Comment by HaoK** [comment]
You seem to be missing a `UseAuthentication()` which should go before `UseAuthorization()`

**Comment by riyuexing** [comment]
OK,Thank you.I got it.
I am sorry, to bother you with this.
May God bless you!
May Gold bless AspNetCore!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hao Kung"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月8日(星期二) 下午3:45
收件人:&nbsp;"aspnet/AspNetCore"<AspNetCore@noreply.github.com&gt;;
抄送:&nbsp;"赵志刚"<1401527242@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aspnet/AspNetCore] With Asp.net core 3.0 SignInManager.IsSignedIn(User) allways reuturn false?but in 2.2 it works fine.Is that a debug? (#14755)




You seem to be missing a UseAuthentication() which should go before UseAuthorization()
