### ISSUE TITLE
Scenarios are not running: Json, MemoryCachePlaintext, MemoryCachePlaintextSetRemove

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14769]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| Json | Linux, Physical, h2c, KestrelSockets | 10/5/19 6:45:44 AM +00:00 |
| MemoryCachePlaintext | Linux, Physical, http, KestrelSockets | 10/5/19 6:47:18 AM +00:00 |
| MemoryCachePlaintextSetRemove | Linux, Physical, http, KestrelSockets | 10/5/19 6:48:51 AM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by jkotalik** [comment]
This seems to have self resolved. Jobs are running now. 

The failures were all:
`The specified client url 'URL' is invalid or not responsive.`

These jobs are running now.
