### ISSUE TITLE
Blazor server: Allow updating other connected circuits

### ISSUE THREAD

**Issue by Sebazzz** [aspnet/AspNetCore#14778]
### Is your feature request related to a problem? Please describe.
I would like to push updates in Blazor from the server based on, for example, database updates or a background job. I believe that in #10559 a StateChanged method was mentioned, but that would require a separate polling thread per running circuit and offers no framework level support for triggering or targeting a circuit.

Perhaps this is already possible, but it is not documented.

### Describe the solution you'd like
I'd imagine a CircuitManager api where you can simply force a render of the circuits registered with a identifier. In a component you can register the current circuit using a identifier, like you can do with the Groups option of a SignalR hub.

### Additional context
Use the already underlying power of SignalR  😀

The other current option I can imagine currently is running a separate SignalR client and hub which may invoke the rendering logic.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Sebazzz.
This is something SignalR team plans to add support for during 5.0 timeframe.
@anurse can you please link the issue here for tracking? Thanks!

**Comment by anurse** [comment]
> This is something SignalR team plans to add support for during 5.0 timeframe.

I'm not aware of the SignalR functionality you're referring to here, plus we haven't completed planning for 5.0.

I don't see any reason why a SignalR feature would be needed to support this scenario. We already have mechanisms for targeting specific clients. Could you provide more context on the change you're looking for here? (cc @rynowak)

**Comment by rynowak** [comment]
The proposal in this issue is that we duplicate groups with a concept specific to Blazor server. We'd suggest solving this with SignalR (once there's a client that's optimized for use in Blazor Server).

**Comment by anurse** [comment]
Ah, I see. So the feature you're talking about is an "official" SignalR client for Blazor scenarios. Cool, that's more clear (and a high priority item for 5.0 for us). I don't think there's an issue tracking it yet, but it's high up on our planning lists.

**Comment by Sebazzz** [comment]
I think it is a bit of a documentation issue and a change of mindset that was needed, I guess I was still stuck in the old request/response mindset while Blazor is a whole other kind of beast. 

It is indeed quite easy to target specific components with what is needed. Essentially the only thing I'd like to see in the framework is something that will help manage those references, to prevent memory leaks. I'm also curious how this currently, if at all, would work in a multi-server scenario.
