### ISSUE TITLE
Route default values set to empty string when pass null

### ISSUE THREAD

**Issue by AliDehghani** [aspnet/AspNetCore#14774]
I'm using .net core 2.2 and I created a new route with default values and add it to routes like following code: 
```
routeBuilder.Routes.Add(new Route(routeBuilder.DefaultHandler, "newRoute", "/login",
                new RouteValueDictionary(new
                {
                    controller = "Customer",
                    action = "Login",
                    area = 1 == 0 ? "Admin" : null
                }), new RouteValueDictionary(null), new RouteValueDictionary(null),
                inlineConstraintResolver));
```
But, when I request the registered route, the area value of ViewLocationExpanderContext object is an empty string isntead of null. I tried that on .net core 2.1 before and it works fine there and because of that I think there is an issue in 2.2.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AliDehghani .
In Routing empty string and `null` are equivalent. So this issue by-design.
