### ISSUE TITLE
Blazor:- How to remove a particular class from the list of classnames defined

### ISSUE THREAD

**Issue by Indrajith-Sync** [aspnet/AspNetCore#14785]
Removing the particular class from the list of class names in a div. 

For eg:-

`<div class="test1 test2">`

In the above div class i need to remove the "test2" alone.

Any suggestion for this?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by Indrajith-Sync** [comment]
OK @mkArtakMSFT
