### ISSUE TITLE
Microsoft.JSInterop.JSException is thrown when trying to access a JavaScript method in Internet Explorer

### ISSUE THREAD

**Issue by DanJBower** [aspnet/AspNetCore#14784]
### Describe the bug
`Microsoft.JSInterop.JSException` is thrown when trying to access a JavaScript method in Internet Explorer. Unfortunately, my deployment environment is restricted to this browser.

### To Reproduce
1. Using this version of ASP.NET Core 3.0.0
2. Run this code (In Internet Explorer):

Create a new Blazor App that runs on server side.

[Daddoon's Blazor.Polyfill](https://github.com/Daddoon/Blazor.Polyfill) can be found here and is required to get clicks working in Internet Explorer. Just drop it in wwwroot so that it works with the example below.

*_Host.cshtml*

    @page "/"
    @namespace JavascriptInteropExample.Pages
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>JavascriptInteropExample</title>
        <base href="~/" />
        <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
        <link href="css/site.css" rel="stylesheet" />
    </head>
    <body>
        <app>
            @(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))
        </app>

        <script type="text/javascript" src="blazor.polyfill.min.js"></script>
        <script src="_framework/blazor.server.js"></script>
        <script>
            window.debugOut = (content, userDir = true, prefix = "") => {
                if (userDir) {
                    if (prefix) {
                        console.log(prefix);
                    }
                    console.dir(content);
                } else {
                    console.log((prefix ? `${prefix}: ` : "") + JSON.stringify(content));
                }
                return true;
            }
        </script>
    </body>
    </html>

*Index.razor*

    @page "/"

    <h1>Hello, world!</h1>

    Welcome to your new app.

    @inject IJSRuntime JsRuntime

    <div class="card my-3">
        <h5 class="card-header">Debug Output</h5>
        <div class="card-body">
            <button @onclick="DebugOutString">Output Debug String</button>
        </div>
    </div>

    @code
    {
        private async void DebugOutString()
        {
            await JsRuntime.InvokeAsync<bool>("debugOut", "Test String", false, "Here's a string");
        }
    }

~~3. With these arguments '....'~~

	Microsoft.JSInterop.JSException: 'Could not find 'debugOut' in 'window'.
	Error: Could not find 'debugOut' in 'window'.
	   at Anonymous function (https://localhost:44385/_framework/blazor.server.js:8:28059)
	   at p (https://localhost:44385/_framework/blazor.server.js:8:28010)
	   at Anonymous function (https://localhost:44385/_framework/blazor.server.js:8:28731)
	   at B (https://localhost:44385/blazor.polyfill.min.js:1:81352)
	   at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:44385/_framework/blazor.server.js:8:28701)
	   at Anonymous function (https://localhost:44385/_framework/blazor.server.js:1:19139)
	   at e.prototype.invokeClientMethod (https://localhost:44385/_framework/blazor.server.js:1:19117)
	   at e.prototype.processIncomingData (https://localhost:44385/_framework/blazor.server.js:1:17160)
	   at connection.onreceive (https://localhost:44385/_framework/blazor.server.js:1:10267)
	   at i.onmessage (https://localhost:44385/_framework/blazor.server.js:1:38025)'

### Expected behavior
A log in the console saying `Here's a string: "Test String"`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @DanJBower.
There are certain gaps in the IE support which we are going to handle as part of https://github.com/aspnet/AspNetCore/issues/9436.

**Comment by Daddoon** [comment]
Hi @DanJBower !

Are you sure that your Javascript code is compliant with the ECMAScript version used on IE11 ?
I think all is failing because the closure you written is not compatible with IE11 that is pretty old.

You may write with recent Javascript and transpile at build time your javascript code to EcmaScript 5.

I think your code should work if you write this instead (as a proof of the source of the bug):

```javascript

window.debugOut = function (content, userDir, prefix) {
            
			if (userDir === undefined || userDir === null)
			{
				userDir = true;
			}
			
			if (prefix === undefined || prefix === null)
			{
				prefix = "";
			}
			
			if (userDir) {
                if (prefix) {
                    console.log(prefix);
                }
                console.dir(content);
            } else {
                console.log((prefix ? (prefix + " :") : "") + JSON.stringify(content));
            }
            return true;
        };
```

**Comment by DanJBower** [comment]
@Daddoon Oh, that's my bad. I still couldn't get it to work with your code but when I took it to the simplest level of

    window.testMethod = function (content) {
        console.log(content);
    };

it did work so I'm sure I can work the rest out from there when I get a little time later today.

Thanks for pointing it out :)
