### ISSUE TITLE
Please could someone provide a Blazor template that has a normal menu bar

### ISSUE THREAD

**Issue by robalexclark** [aspnet/AspNetCore#14788]
The Blazor template has a nav menu that is a side bar. Despite many multiple attempts I have not been able to get a normal top menu bar working satisfactorily (may be my unfamiliarity with Blazor). Can you provide an option to create a template with a top menu bar?

**Comment by danroth27** [comment]
Hi @robalexclark. We don't plan to provide an alternative version of the template with a top menu bar, but you should be able to update the template code to add your own menu bar with with normal HTML and CSS.  Can you share with us what issues you've been having getting a top menu bar to work in a Blazor app?

**Comment by soeleman** [comment]
@robalexclark If you mean template like in _ASP.NET Core_. You can take a look in [MenuHorizontal](https://github.com/soeleman/DotNetLab/tree/master/src/net3/3-0/aspnet/blazor/wasm/MenuHorizontal).
It used the _CSS_ and _layout_ from _ASP.NET Core_ template.

![Blazor_MenuHorizontal](https://user-images.githubusercontent.com/309413/66367081-e1078280-e9bc-11e9-8cb9-94f7a1fd5689.png)

**Comment by robalexclark** [comment]
I understand that the menu is just driven by bootstrap but being new to blazor I really struggled to unpick the sidebar and get it across the top. I probably spent 5-6 hours trying/crying to get it to work but hit issues (I know it shouldn't be this hard - right!?).

I think that there will be many folks that hit the same issue and struggle to get this working. Thank you @soeleman for the demo, it looks good and I've managed to copy it into a new app.

There is a bounty available at [https://stackoverflow.com/questions/58235005/blazor-template-with-menu-across-the-top](url) for you to answer with your demo if you want.

**Comment by robalexclark** [comment]
Thanks again to @soelman for his work which I built on and produced a repo with a top menu bar:
https://github.com/robalexclark/BlazorTopMenu
