### ISSUE TITLE
API and JSON code sample mismatch

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore#14797]
@cseguenot commented on [Sun Oct 06 2019](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/234)

Hi
There is an problem with the JSON code sample : it's about wheather forecast, and not about todo items...

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutoriel : Créer une API web avec ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Sun Oct 06 2019](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/234#issuecomment-538743488)

Hello, @cseguenot
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the reported issue is also present in the source
best

**Comment by Rick-Anderson** [comment]
See https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/234

It's correct

**Comment by Rick-Anderson** [comment]
@CeciAc  please close. I think you meant to open this issue in `https://github.com/aspnet/AspNetCore.Docs` not `https://github.com/aspnet/AspNetCore`
