### ISSUE TITLE
Blazor DataTransfer wrapper object 

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#14792]
Blazor 3.0:

I can use the `DragEventArgs` class as parameter to my methods however setting data on some properties has not effect.

e.g. nearly everything releated to the `DataTransfer` object inside the `DragEventArgs `is not working.

Is this supposed to work? 

If support for the DragEventArgs is not yet implemented then why are those properties read/write in the first place?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Postlagerkarte.
The properties of the `DragEventArgs` are writable only for enabling serialization to/from JSON.
These are not meant to alter state in any way.

**Comment by Postlagerkarte** [comment]
@mkArtakMSFT :  This fact should be documented somewhere. Is this the only EventArgs which is not meant to alter state or are there more?
