### ISSUE TITLE
Generator DevOps service extension in Blazor

### ISSUE THREAD

**Issue by tomview** [aspnet/AspNetCore#14794]
Currently [Azure DevOps extension development](https://docs.microsoft.com/en-us/azure/devops/extend/?toc=%2Fazure%2Fdevops%2Fextend%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fextend%2Fbreadcrumb%2Ftoc.json&view=azure-devops) has been limited to nodejs-based extension.

Requests ([Ref1](https://developercommunity.visualstudio.com/content/problem/704085/building-blazor-devops-extensions.html) & [Ref2](https://developercommunity.visualstudio.com/idea/425875/develop-azure-devops-extensions-using-blazor.html)) is currently being investigated to support the [DevOps extension written in Blazor.](https://github.com/MicrosoftDocs/vsts-docs/issues/5872)

["The fastest path to a new VSTS extension"](https://devblogs.microsoft.com/devops/fastest-path-new-team-services-extension/) exists for the nodejs-based extension using [Yeoman](https://github.com/mikaelkrief/generator-team-services-extension) 

**Request new feature 1:**
Is there *a vision* to bring the .NET Conf 2019 promise of Blazor for .NET Web developer to the DevOps extension development.

> apply our creativity to improve our DevOps experience and productivity by [**developing AND sharing DevOps extensions with greater efficiency using FULL .NET**](https://github.com/MicrosoftDocs/vsts-docs/issues/5872#issue-503465199)  instead of the recommended Javascript/NodeJs

**Request new feature 2:**
If there is interest and valid business use case, could *a generator DevOps service extension for Blazor* be incorporated as a new feature request.

**Comment by danroth27** [comment]
Hi @tomview. Thanks for your interest in using Blazor! I'm following up with the Azure DevOps folks to see what the status of this request is. Thanks for your patience!

**Comment by GeorgeS2019** [comment]
@danroth27  [ Blazor Everywhere!!!](https://visualstudiomagazine.com/articles/2019/09/26/blazor-future.aspx) The new kid => Blazor native.

Perhaps others may share my excitement here
## [Star Trek: Enterprise Theme Lyrics](https://www.lyricsondemand.com/tvthemes/startrekenterpriselyrics.html)

It's been a long road
Getting from there to here
It's been a long time
But my time is finally near

==> Democratizing modern project management using Azure DevOps through [Blazor] extension is the next big thing! In the next few months, we will hear more of Blazor Nativ, we will hear more excitement from the community regarding the future impact of Blazor! We need Blazor marks the beginning of more lead cloud developers engaging in delivering real world business values using .NET.Core and C# through the Azure DevOps platform!
