### ISSUE TITLE
Kestrel Heartbeat.OnHeartbeat error

### ISSUE THREAD

**Issue by philieu** [aspnet/AspNetCore#14808]
### Describe the bug
We are seeing the following error from Kestrel heartbeat:
Heartbeat.OnHeartbeat
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.TransportConnection.TickHeartbeat()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.ConnectionManager.Walk(Action`1 callback)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat()

When the above error happened, AWS decided that the EC2 instance is unhealthy and terminate it.
I was not able to get more information in the docs to understand what that error means.

### To Reproduce
We are using the following:
1. ASP.NET Core SDK 2.2 102 (2.2.1 runtime)
2. AWS Linux 2 AMI
3. SQL Server backend (not sure that matter)

### Expected behavior
Since the error is low level Kestrel error, there can't find any documentation on it as well as the approach to fix it.

Thanks.

**Comment by philieu** [comment]
We are seeing a lot of these errors, especially when the servers are under load. As a temporary mitigation / workaround, we just provision a little bit more instances than required. That seems to remove most of the errors.

**Comment by anurse** [comment]
Null-refing on the lock object is super sketchy here. It's a `readonly` field that's initialized in the constructor:

https://github.com/aspnet/AspNetCore/blob/7ab32c8411f40e63984c5963b79722c1f2fd9d8a/src/Servers/Kestrel/Transport.Abstractions/src/Internal/TransportConnection.cs#L19

This smells like memory corruption of some kind...

**Comment by anurse** [comment]
@davidfowl any thoughts on who could help investigate this kind of corruption?

**Comment by philieu** [comment]
Also, we are seeing the following in the log:
main process (3469) terminated with status **134**
main process (6549) terminated with status **139**

**Comment by davidfowl** [comment]
We're going to need a process dump to look into this.

@jkotas any ideas on who could look at this?

**Comment by jkotas** [comment]
Yes, we will need a dump to make a progress on it. I can route it once the dump is available.

> 2.2.1 runtime

You may want to update to latest 2.2.x or 3.0 to see whether it got fixed already.

**Comment by philieu** [comment]
Sure, I'll plan for the upgrade and report back here.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Let us know if the upgrade hasn't resolved the issue and we can reopen the issue to investigate further!
