### ISSUE TITLE
ElementReference causes "Invalid JSON" exception when returned to JavaScript

### ISSUE THREAD

**Issue by HughPH** [aspnet/AspNetCore#14800]
### Describe the bug
Calling C# from JavaScript, then JavaScript from C# to obtain ElementReferences, then returning those ElementReferences to C#, Blazor throws an exception:
```
blazor.webassembly.js:1 Uncaught (in promise) Error: System.Text.Json.JsonException: Invalid JSON
  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS (/Microsoft.JSInterop.JSRuntime jsRuntime, System.String arguments) <0x20ed888 + 0x000fc> in <4e424253df194e1299a1044d93a79164>:0 
  at Mono.WebAssembly.Interop.MonoWebAssemblyJSRuntime.EndInvokeJS (/System.String argsJson) <0x20e4a58 + 0x0000a> in <d0b620549c284928acbf6b89d371ca02>:0 
    at Object.callMethod (blazor.webassembly.js:1)
    at Object.endInvokeJSFromDotNet (blazor.webassembly.js:1)
    at blazor.webassembly.js:1
```

### To Reproduce
- .Net Core 3.0.0-100
- dotnet new blazorwasm

Create a JavaScript method that creates an element:
```javascript
window.CreateElement = (text) => {
  var element = document.createElement("span");
  element.innerText = text;
  return element;
}
```
Create a [JSInvokable] C# method:
```csharp
[JSInvokable]
public static async Task<List<ElementReference>> GetElements(){
  List<ElementReference> refs = new List<ElementReference>();
  refs.Add(await JSInterop.InvokeAsync<ElementReference>("CreateElement","first"));
  refs.Add(await JSInterop.InvokeAsync<ElementReference>("CreateElement","second"));
  return refs;
}
```
Create another JavaScript function that calls the C# method:
```javascript
window.Test = async () => {
  var refs = await DotNet.InvokeAsync("TestProject","GetElements");
}
```
Invoke window.Test.

### Expected behavior
Expect no exception to be thrown, and for the elements created by the CreateElement method to be returned to the Test method.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @HughPH.
`ElementReference` is a reference to a DOM element that Blazor has rendered. It cannot be used to refer an element rendered by JavaScript as Blazor has no knowledge of it. You can pass the element id from JavaScript to Blazor and then use it as string internally.

**Comment by HughPH** [comment]
@mkArtakMSFT Thanks for the reply, that makes sense. I had expected that Blazor would 'foster'  (temporarily adopt) unknown elements and create a new _internalId for them, keeping them immutable but referable, then 'translate' them back to their JavaScript object references when being passed back across the divide.
