### ISSUE TITLE
JsonIgnore Being Ignored in .NET Core 3.0 - Bug?

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/AspNetCore#14807]
In .NET Core it is possible to return an object as Json easily by returning as a JsonResult
```
return new JsonResult(Note);
```

Then to avoid related entities also being returned (in this case details of the user who wrote the note) adding `[JsonIgnore]` to the attributes of the entity stopped this related info from pulling through and leading to circular references.

However when switching a project from .NET Core 2.2 to .NET Core 3.0 this no longer works and `[JsonIgnore]` attributes are ignored. This would seem to be a bug from what I can tell given I can switch back to 2.2 and it works as expected.

This is the field contained in the model:
```
[JsonIgnore]
[Display(Name = "Created By")]
public ApplicationUser ApplicationUserCreatedBy { get; set; }
```

This is the correct output when project is targeting .NET Core 2.2:
```
[{"noteID":257,"customerID":4204,"noteText":"07.03.06  4pm","isAlert":false,"createdDate":"2008-01-01T00:00:00","createdBy":"e9483193-0ced-4b8c-9eb0-1faad74e9907","updatedDate":null,"updatedBy":null}]
```

This is the output if the project is switched to 3.0 (shortened as is very long until is cut halfway through):
```
[{"noteID":257,"customerID":4204,"noteText":"07.03.06  4pm","isAlert":false,"createdDate":"2008-01-01T00:00:00","createdBy":"e9483193-0ced-4b8c-9eb0-1faad74e9907","applicationUserCreatedBy":{"forename":"Robin","surname":"Wilson","id":"...
```

As you can see in .NET Core 3.0 the `[JsonIgnore]` attribute is having no effect.
This would appear to be a bug unless the functionality has changed but I can find nothing that relates to this changing.

**Comment by robinwilson16** [comment]
Ok found the solution.

Seems if I go to my model I need to replace this:
```
using Newtonsoft.Json;
```

With:
```
using System.Text.Json;
using System.Text.Json.Serialization;
```

Now it works.
Found at:
https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/

The question then I suppose is should it compile with the non-functional one?

**Comment by nmain** [comment]
> The question then I suppose is should it compile with the non-functional one?

`[Newtonsoft.Json.JsonIgnore]` is still valid though, and still has an effect: any time you use the Newtonsoft serializers to serialize and deserialize those objects, that attribute will be respected.  In general, attributes are just arbitrary metadata, and beyond `[AttributeUsage]`, the compiler has no way to know whether a particular attribute will actually "do" something at runtime.  You should probably remove all of the Newtonsoft packages from your project if you don't intend to use it anymore; then you won't accidentally reference the wrong `[JsonIgnore]`.

**Comment by davidfowl** [comment]
> The question then I suppose is should it compile with the non-functional one?

The compiler has no idea how you are going to use those types. You could have configured MVC to use the Newtonsoft.Json or any other serializer that does support those attributes.

The best that could be done here would be to have the serializer support attributes like this based on name. Can you file a suggestion on https://github.com/dotnet/corefx?

**Comment by robinwilson16** [comment]
> > The question then I suppose is should it compile with the non-functional one?
> 
> `[Newtonsoft.Json.JsonIgnore]` is still valid though, and still has an effect: any time you use the Newtonsoft serializers to serialize and deserialize those objects, that attribute will be respected. In general, attributes are just arbitrary metadata, and beyond `[AttributeUsage]`, the compiler has no way to know whether a particular attribute will actually "do" something at runtime. You should probably remove all of the Newtonsoft packages from your project if you don't intend to use it anymore; then you won't accidentally reference the wrong `[JsonIgnore]`.

Thanks @davidfowl, I have been through and updated all references and made a note to check my other projects so hopefully won't run into this again. In that case it makes sense for it not to complain at compile time.

**Comment by robinwilson16** [comment]
Posted suggestion as dotnet/corefx#41667 thanks
