### ISSUE TITLE
AspNetCore SignalR 3.0 with Jsonprotocol cannot handle the long type value in IDictionary<string, object>

### ISSUE THREAD

**Issue by ccic** [aspnet/AspNetCore#14810]
### Describe the bug
My hub method is:

```
public class BenchHub : Hub
{
     public void Echo(IDictionary<string, object> data)
     {
            Clients.Client(Context.ConnectionId).SendAsync("RecordLatency", data);
     }
}
```

My C# HubConnection is:
```
 public static async Task EchoTest(string url)
{
            string connectionId = null;
            var hubConnectionBuilder = new HubConnectionBuilder();
            var hubConnection = hubConnectionBuilder.WithUrl(url).WithAutomaticReconnect().Build();
            hubConnection.Closed += HubConnection_Closed;
            hubConnection.On<string>("OnConnected", async (cid) =>
            {
                connectionId = cid;
                var dictionary = new Dictionary<string, object>();
                dictionary["payload.Timestamp"] = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds().ToString();
                Console.WriteLine($"before sending the data: " + Convert.ToInt64(dictionary["payload.Timestamp"]));
                await hubConnection.SendAsync("Echo", dictionary);
            });
            hubConnection.On<IDictionary<string, object>>("RecordLatency", item =>
            {
                var d = item["payload.Timestamp"];
                Console.WriteLine(d.GetType().FullName);
                var f = d.ToString();
                Console.WriteLine(f.GetType().FullName);
                // do something with the stream item
                try
                {
                    var sendTimestamp = Convert.ToInt64(d); // <== Error occurs here
                    var recvTimestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
                    var latency = recvTimestamp - sendTimestamp;
                    Console.WriteLine(latency);
                }
                catch (Exception e)
                {
                    Console.WriteLine($"{e}");
                }
            });
            await hubConnection.StartAsync();
}
```

The output is:
```
C:\home\Work\DevDiv\OpenSource\SignalRStreamClient>dotnet run -- "http://localhost:5050/signalrbench"
before sending the data: 1570519638137
1570519638137
System.Text.Json.JsonElement
System.String
System.InvalidCastException: Unable to cast object of type 'System.Text.Json.JsonElement' to type 'System.IConvertible'.
   at System.Convert.ToInt64(Object value)
```

If I used Messagepack protocol
```
var hubConnection = hubConnectionBuilder.AddMessagePackProtocol().WithUrl(url).WithAutomaticReconnect().Build();
```
or using ToString() explicitly
```
                var d = item["payload.Timestamp"];
                Console.WriteLine(d.GetType().FullName);
                var f = d.ToString();
                Console.WriteLine(f.GetType().FullName);
                // do something with the stream item
                try
                {
                    var sendTimestamp = Convert.ToInt64(f);
```
It works fine. 
My question is what is the correct way to handle this? Why different protocol shows different behavior?

### To Reproduce
1. Using this version of ASP.NET Core '3.0'
2. Create a simple SignalR app server with the above "BenchHub"
3. With these arguments '....'

### Expected behavior
Both JsonProtocol and MessagepackProtocol should have the same behavior.

### Additional context
Include the output of `dotnet --info`

C:\home\Work\DevDiv\OpenSource\SignalRStreamClient>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by davidfowl** [comment]
> My question is what is the correct way to handle this? Why different protocol shows different behavior?

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#switch-to-newtonsoftjson

**Comment by ccic** [comment]
@davidfowl Yes, it fixed my issue. Thanks
