### ISSUE TITLE
ViewData

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14829]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/672484/viewdata.html)._

---
Hello
At first thanks becuse of your great services 
Recentlly I had a problem that was very interesting
When I resend several time request to controller to call action , for the first and second time I dident have any problem , but more than that I got error that seid 
&quot;Adding 'namespace' will prevent the debug session from continuing&quot;
and then closed all my session such as identity 
and redirect me to login
After try alot I underestand that this problem happend in viewdata[Title]
I change this to Viewbag.Title  and my problem solved 
I didnt know why this has happend so I thught its better to send report
 
Thanks

---
#### Visual Studio Feedback System on 8/2/2019, 00:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/2/2019, 01:37 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It seems what had happened here is that you have made a modification to your code during runtime. This resulted in VS to recompile your app which resulted in the state to be lost. Hence you've been logged-out from the app.
