### ISSUE TITLE
Question: Is this a correct way to cache prerendered Blazor response?

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#14828]
I have just forked this example from @danroth27 https://github.com/danroth27/BlazorWebAssemblyWithPrerendering

In my real application I would like to cache prerendered server response to minimize server workload. To do this I have changed _Host.cshtml, and now it looks like this (changes are marked with comments):
```html
@page "/"
@namespace BlazorWebAssemblyWithPrerendering.Pages
@using BlazorWebAssemblyWithPrerendering.Client
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!-- Added HttpContextAccessor -->
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor ctx

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BlazorWebAssemblyWithPrerendering</title>
    <base href="~/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />
</head>
<body>
    <!-- Added cache tag helper -->
    <cache expires-after="@TimeSpan.FromSeconds(60)" vary-by="@ctx.HttpContext.Request.Path">
        <app>
            <!-- Let's assume I don't wont to prerender everything -->
            @if (ctx.HttpContext.Request.Path.StartsWithSegments(new PathString("/counter")))
            {
                <h1>Loading app without prerendering - cached @DateTime.Now</h1>
            }
            else
            {
                @(await Html.RenderComponentAsync<App>(RenderMode.Static))
            }
        </app>
    </cache>

    <script src="_framework/blazor.webassembly.js"></script>
</body>
</html>
```
Here is a complete project: https://github.com/Andrzej-W/BlazorWebAssemblyWithPrerendering

I would like to ask if this method of cacheing is appropriate for Blazor, especially this attribute in `cache` tag helper: ` vary-by="@ctx.HttpContext.Request.Path"`

In my opinion it is necessary to correctly cache direct requests to different addresses which are all mapped to the same Razor page. It looks that it works correctly in my tests but I would like to be sure. If it is not correct (why?) are there any plans to make it possible?

For the sake of brevity let's assume that we are not interested in other `cache` tag helper attributes like `vary-by-cookie`, `vary-by-header`, etc.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Andrzej-W.
It fully depends on your specific application.
If your app produces the same content for each path (which is what you've specified as a `vary-by` parameter) then it sure is.

You can read more about the cache tag helper at: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/cache-tag-helper?view=aspnetcore-3.0

Hope this helps.
