### ISSUE TITLE
asp.net core 3 - Model bindind / MvcOptions.SuppressBindingUndefinedValueToEnumType

### ISSUE THREAD

**Issue by Tolitech** [aspnet/AspNetCore#14824]
Hi.

After the MvcOptions.SuppressBindingUndefinedValueToEnumType option has been removed in .NET Core 3, what would be the equivalent setting to be able to receive values in the [FromRoute] / [FromQuery] model binding even though they are out of range?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Tolitech.
The alternative approach is to use `int` values instead. There are no other settings controlling this behavior.
