### ISSUE TITLE
Visual Studio error when changing proto properties in gRPC template

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#14838]
1. Create a new gRPC service
2. View the `greet.proto` properties in Visual Studio
   
   ![image](https://user-images.githubusercontent.com/303201/66433319-99483000-ea7c-11e9-8f4b-c1869292e316.png)

3. Change `gRPC Stub Classes` from `Server only` to `Client only`.
4. Visual Studio errors

    ![image](https://user-images.githubusercontent.com/303201/66433509-f5ab4f80-ea7c-11e9-8127-f6746e795f8c.png)

Details in the error popup:

> An error has occurred while saving the edited properties listed below:
> 	gRPC Stub Classes
> One or more values are invalid. MSBuild returned the following error: The element <GrpcServices> beneath element <Protobuf> is invalid because a child element with that name already exists  C:\Users\James\source\repos\GrpcService11\GrpcService11\GrpcService11.csproj

Visual Studio 16.3.3 & 16.4 Preview 1

**Comment by devhl-labs** [comment]
As a work around you can edit the .csproj file manually.  `<Protobuf Include="Protos\greet.proto" GrpcServices="Client" />`

**Comment by Pilchie** [comment]
@jjmew Do you know what metadata needs to be present to support changing this in the property grid?

**Comment by JamesNK** [comment]
Some more detail:

It doesn't happen if VS was opened (or the project is unloaded and reloaded) with no value in XML. If there is no value in XML then the value can be modified successfully until VS is reopened.

Also, the same error happens with other properties on the `<Protobuf>` element: `Access`, `ProtoCompile`

**Comment by JamesNK** [comment]
This is either an error in the project system or in Grpc.Tools. Moving to https://github.com/dotnet/project-system/issues/5573

**Comment by davidwengier** [comment]
See my comment on https://github.com/dotnet/project-system/issues/5573#issuecomment-540857524, you probably want to change Grpc.Tools to fix this.
