### ISSUE TITLE
Attempting to set LoginPath on ApplicationCookie, but does not work

### ISSUE THREAD

**Issue by superdevguy** [aspnet/AspNetCore#14831]
I am attempting to set the LoginPath on the application cookie using the information located in this documentation:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-3.0

Under the Cookie Settings sub header it says I can set the login path there. It also puts a link to the CookieAuthenticationOptions object for more information under the section:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions?view=aspnetcore-3.0

When I go to this page, it tells me there is no page for ASP.NET Core 3.0. I am thinking that the LoginPath is not being setup the same way using identity. In ConfigureServices, I have it setup this way:
  services.AddDefaultIdentity<MyUser>(options => { options.SignIn.RequireConfirmedAccount = false; })
                    .AddRoles<IdentityRole>()
                    .AddEntityFrameworkStores<MyContext>();
services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.Name = "MyCookie";
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromMinutes(60);
                options.LoginPath = "/Account/Login";
            });

I am trying to redirect an unauthorized user to Account/Login instead of the built in Identity/Account/Login, since I do not want to use Razor pages and I am migrating all those Identity pages to razor views with controllers instead.

Is this functionality working in ASP.NET Core 3.0? Or is there some other way that I need to configure this LoginPath?

**Comment by HaoK** [comment]
If you don't want to use the default identity UI at all, have you tried replacing AddDefaultIdentity with AddIdentity?  That would be another way to get the login path set to /account/login by default, but what you are doing looks correct in terms of configuring that path

**Comment by MintPlayer** [comment]
Hi @superdevguy 
Can you please push a minimal repository with the project to github?
It's easier to follow up on your issue that way.

**Comment by HaoK** [comment]
Closing due to lack of response, feel free to reopen with a repro if this is still an issue
