### ISSUE TITLE
Disposed IFeatureCollection for subsequent API requests.

### ISSUE THREAD

**Issue by Andrew-Oliveira** [aspnet/AspNetCore#14841]
.NET Core 3.0   (Didn't experience this in version 2.2)

Requests made to my API endpoint work the first time but not for subsequent requests. This occurs in IIS Express and IIS proper. When it fails my controller is never reached and data isn't returned, but it still returns 200. Eventually it logs:

`
IFeatureCollection has been disposed.
Object name: 'Collection'.
`

Startup.cs Configure

`

            app.UseHttpsRedirection(); // Redirect HTTP -> HTTPS
            app.UseRouting();
            {
                app.UseCors(Config.Settings.Cors.PolicyName);
                app.UseAuthentication();
            }
            app.UseMiddleware<LoggingMiddleware>();
            app.UseMiddleware<OptionsVerbMiddleware>();
            app.UseEndpoints(x => x.MapControllers());
`

I did have a potentially related issue in regards to HttpContext being disposed when I was trying to use it, but that was in a different part of the application and wasn't necessary for the application to run.

When I stepped through with the debugger I didn't notice anything obvious. About to leave for the day, but I'll be continuing to debug tomorrow. Thank you.

**Comment by davidfowl** [comment]
Are you using `IHttpContextAccessor` anywhere?

**Comment by Andrew-Oliveira** [comment]
Yes, quite a few places, including the controller's constructor.

Startup.cs ConfigureServices
`services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

**Comment by davidfowl** [comment]
You never need it in a controller, why do you use it there? Where else are you using it and are you capturing the HttpContext in any singletons?


Some of these guidelines might help you audit your code https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md#do-not-store-ihttpcontextaccessorhttpcontext-in-a-field

**Comment by Andrew-Oliveira** [comment]
I commented out all of my references to HttpContext and subsequent requests are now working again! I was definitely setting the context to a field in some places, exactly how your link mentions _not_ to do. Thanks for the help!
