### ISSUE TITLE
How to access services in `Startup.ConfigureServices`

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/AspNetCore#14850]
### Describe the bug
For using `services.BuildServiceProvider()` in `Startup.ConfigureServices`, it will produce issue below

> 'BuildServiceProvider' from application code results in an additional copy of singleton services being created. Consider alternatives such as dependency injecting services as parameters to 'Configure'.

I got the suggestion from #2251, but not all library could not resolved by Service Interface.

Is there any safe way to get the service implementation in `Startup.ConfigureServices`?

### To Reproduce
1. Using this version of ASP.NET Core '3.0'
2. Run this code
```
services.AddMvc(options =>
{
    var serviceProvider = services.BuildServiceProvider();
    var customJsonInputFormatter = new IgnoreGuidErrorJsonInputFormatter(
                serviceProvider.GetRequiredService<ILoggerFactory>().CreateLogger<IgnoreGuidErrorJsonInputFormatter>(),
                serviceProvider.GetRequiredService<IOptions<MvcJsonOptions>>().Value.SerializerSettings,
                serviceProvider.GetRequiredService<ArrayPool<char>>(),
                serviceProvider.GetRequiredService<ObjectPoolProvider>(),
                options,
                serviceProvider.GetRequiredService<IOptions<MvcJsonOptions>>().Value
        );
    options.InputFormatters.Insert(0, customJsonInputFormatter);
});
```

### Expected behavior
A safe way to resovle service in `Startup.ConfigureServices`

**Comment by khellang** [comment]
You should create an implementation of `IConfigureOptions<MvcOptions>`, and add the input formatter in there:

https://github.com/aspnet/AspNetCore/blob/ff8363a638401c5602910553356bd7f98b8d2f98/src/Mvc/Mvc.NewtonsoftJson/src/DependencyInjection/NewtonsoftJsonMvcOptionsSetup.cs#L78-L85

This allows you to inject services from the container:

https://github.com/aspnet/AspNetCore/blob/ff8363a638401c5602910553356bd7f98b8d2f98/src/Mvc/Mvc.NewtonsoftJson/src/DependencyInjection/NewtonsoftJsonMvcOptionsSetup.cs#L28-L33

See https://github.com/aspnet/AspNetCore/blob/ff8363a638401c5602910553356bd7f98b8d2f98/src/Mvc/Mvc.NewtonsoftJson/src/DependencyInjection/NewtonsoftJsonMvcOptionsSetup.cs#L78-L85 for an example.

**Comment by javiercn** [comment]
@Edward-Zhou Thanks for contacting us.

@khellang answer is right, you should create your own  options setup class and register that in DI.
