### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Authentication.Internal.RequestPathBaseCookieBuilder' from assembly 'Microsoft.AspNetCore.Authentication, Version=3.0.0.0

### ISSUE THREAD

**Issue by GiridharanNair** [aspnet/AspNetCore#14861]
Created a ASP .Net core 3 project with web app MVC Template. I am using Okta for authentication.

public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OktaDefaults.MvcAuthenticationScheme;
            })
            .AddCookie()
            .AddOktaMvc(new OktaMvcOptions
            {
                // Replace these values with your Okta configuration
                OktaDomain = Configuration.GetValue<string>("Okta:OktaDomain"),
                ClientId = Configuration.GetValue<string>("Okta:ClientId"),
                ClientSecret = Configuration.GetValue<string>("Okta:ClientSecret"),
                Scope = new List<string> { "openid", "profile", "email" },
            });

            services.AddControllersWithViews();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseAuthentication();
            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }

![Error](https://user-images.githubusercontent.com/22915855/66515097-6cac0c80-eaac-11e9-9e79-45a810ac3593.png)

**Comment by blowdart** [comment]
This generally occurs when you haven't updated all your dependencies to 3.0.

Please post your project.json dependencies section

**Comment by blowdart** [comment]
Dupe of https://github.com/aspnet/AspNetCore/issues/14476

**Comment by GiridharanNair** [comment]
Hi Barry,

[image: image.png]

Please see that all my packages are updated to 3 and i still face the same
issue. Let me know if you need something else from my side.

**Comment by Tratcher** [comment]
The namespace for RequestPathBaseCookieBuilder changed from Microsoft.AspNetCore.Authentication.Internal to Microsoft.AspNetCore.Authentication. One of your dependencies was not recompiled against 3.0, probably AddOktaMvc?

**Comment by blowdart** [comment]
@GiridharanNair images don't come through emails I'm afraid.

Could you just use cut and pasted text?

**Comment by GiridharanNair** [comment]
There is no OktaMVC Nuget package. And that means i have no way to use Okta
on .Net Core 3 MVC??

**Comment by davidfowl** [comment]
https://www.nuget.org/packages/Okta.AspNetCore/ needs to be recompiled against .net core 3.0

**Comment by GiridharanNair** [comment]
@davidfowl  Thanks for replying. But unfortunately recompiling didnt help. I am still facing the same error. 

I guess the namespace of packages was change and that is causing this issue in 3.0. The same works in 2.2 .Net Core SDK

**Comment by GiridharanNair** [comment]
Hi David,

This is the latest version available version of  AspNetCore from Okta.

**Comment by Tratcher** [comment]
@GiridharanNair but it still [targets](https://www.nuget.org/packages/Okta.AspNetCore/) AspNetCore 2.2. You're blocked until they release one that targets AspNetCore 3.0.

**Comment by GiridharanNair** [comment]
@Tratcher Yeah Thats what i figured. Thanks for confirming!

**Comment by Pilchie** [comment]
I caught up with @Quorralyne, and she suggested that Okta is planning on having something out within a month or so.

**Comment by blowdart** [comment]
We're closing this issue as the behaviour discussed seems to be by design.
