### ISSUE TITLE
InProc hosting model drops X-Forwarded-Proto header

### ISSUE THREAD

**Issue by dchristensen** [aspnet/AspNetCore#14860]
### Describe the bug
When hosting an ASP.NET Core application using the IIS InProcess hosting model, if a X-Forwarded-Proto header is sent to the server it is not passed back to the ASP.NET Core application in either the `Request.Scheme` or the `Request.Headers` collection

### To Reproduce
1. Using this version of ASP.NET Core 3.0.100 (also tested on 2.2.301)
2. Using the default Empty ASP.NET Core Web Application template use the following `Configure` method:

```
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    string scheme = context.Request.Scheme;
                    var headers = new Dictionary<string, StringValues>(
                        context.Request.Headers
                            .OrderBy(h => h.Key));

                    context.Response.ContentType = "application/json";
                    await context.Response.WriteAsync(JsonSerializer.Serialize(new
                    {
                        Scheme = scheme,
                        Headers = headers
                    }));
                });
            });
        }
```
3. Deploy to IIS (in my case I'm deploying to Azure) using the default InProcess hosting model.
4. Send a request passing the value `http` in the `X-Forwarded-Proto` header:
```
curl -X GET https://<mywebsite>.azurewebsites.net/ -H 'X-Forwarded-Proto: http'
```
 and see the output:
```
{
	"Scheme": "https",
	"Headers": {
    // removing irrelevant headers
		"X-AppService-Proto": ["https"],
		"X-Forwarded-Proto": ["https"],
	}
}
```
### Expected behavior
I would expect either the `Request.Headers` collection to contain a header with the name "X-Forwarded-Proto" and the value "http"

### Additional context
I've been able to work around this issue by using the Out-of-Process hosting model, but it seems very unintuitive that there is a difference in behavior between the two models and that the header that is sent to the server is completely lost.

**Comment by blowdart** [comment]
Are you expecting to put a proxy in front of IIS that does termination? Is the protocol itself wrong when you browse? I view the current behaviour as the right one, because you're hitting IIS directly, so it would strip the header because it's probably an attacker trying a downgrade attack.

**Comment by Tratcher** [comment]
X-Original-Proto looks like you're using the ForwardedHeaders middleware. That takes the X-Forwarded-Proto value, applies to to the request, and stores the original value in X-Original-Proto.

I don't see UseForwardedHeaders in your Configure method, but there are a few other ways to add it. It's not enabled by default for IIS in-proc.

Do you have any other explanation for where X-Original-Proto is coming from?

**Comment by dchristensen** [comment]
@blowdart Yes, I'm wanting to put Azure Frontdoor in front of my application.  The actual use case I'm trying to achieve is I've got an application that only uses HTTPs right now.  I'm wanting to expose a couple endpoints over HTTP.  So, the ideas was to use Frontdoor to accept those connection, and the backend connection would be HTTPs back to my application.  These endpoints need to generate a URL using the same protocol as the original request which is where the problem arises.  Frontdoor will set the X-Forwarded-Proto header correctly, but I can't get it in my app.

The X-Forwarded-For & X-Forwarded-Host header come through just fine, its only X-Forwarded-Proto that gets overwritten.

@Tratcher  That was actually a copy/paste error on my end.  that header should be "X-Forwarded-Proto" (I've been doing several tests between in-proc and out-of-proc and grabbed the out of proc results, my apologies)

**Comment by Tratcher** [comment]
This does not reproduce locally, so I don't think the filtering is coming from AspNetCoreModule (ANCM). More likely this is an issue with the Azure Web Sites infrastructure (ARR?), or Azure Frontdoor itself.

**Comment by dchristensen** [comment]
@Tratcher I've done some testing with both IISExpress & IIS locally and haven't been able to reproduce, so yes, I guess this is likely something with Azure.  Thanks!
