### ISSUE TITLE
Chinese translation error code is translated

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore#14864]
**The comment below was machine translated:**

@yomunsam commented on [Tue Oct 08 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/203)

Chinese：

## Routing from multiple assemblies to components

Among them, Chinese text

> < 路由器 AppAssembly = "typeof （程序）。程序集 "AdditionalAssemblies =" new [] {typeof （Component1）。Assembly} > ...

Should not be translated, the original English text should be retained

> <Router AppAssembly="typeof(Program).Assembly" AdditionalAssemblies="new[] { typeof(Component1).Assembly }>

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor 路由](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/routing?view=aspnetcore-3.0#)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Tue Oct 08 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/203#issuecomment-539651925)

Hello, @yomunsam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
the user reports a line of code was translated. 
This may be and error in the source where the text was not correctly tagged?

**Comment by guardrex** [comment]
@CeciAc If the comment is just that code-fencing wasn't applied, I'm going to do that now. I think that's what the reader is calling out. I'll open an issue and take care of it on the docs repo.

**Comment by guardrex** [comment]
It will be addressed on https://github.com/aspnet/AspNetCore.Docs/issues/14953.

**Comment by guardrex** [comment]
... *and done!* https://github.com/aspnet/AspNetCore.Docs/pull/14954 @CeciAc ... you can close this if that's what they're calling out.

**Comment by CeciAc** [comment]
Thank you @guardrex 
This will solve the issue for this and other locales in the next localization rounds 
best regards!
