### ISSUE TITLE
Blazor IHttpContextAccessor not working on IIS server

### ISSUE THREAD

**Issue by blenke** [aspnet/AspNetCore#14878]
### Describe the bug
I need to access the server header variables for a Blazor application that is behind a Single Sign On and reverse proxy server. It provides some variables with the user identification. If I use the IHttpContextAccessor in my blazor page then this works fine on my development environment (Visual Studio 16.3) but if I publish this to my IIS server then the page gets stuck after the IHttpContextAccessor is used.

### To Reproduce
Create a default Blazor project in Visual Studio
In Startup.cs add this in the ConfigureServices:
`services.AddHttpContextAccessor();`

Make a Blazor page:
````
@page "/"

@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor hca

<button @onclick="@go">start</button>
<label>@mystr</label>
<br />

<label>@hca.HttpContext.Request.Headers["Host"]</label>

@code{
    string mystr = "Click start";

    void go()
    {
        mystr = "It works";
    }
}
````

### Expected behavior
When running the project from Visual Studio with IIS expres this all works fine. When running from IIS (Server 2016) the button does not respond, The 'host' label is displayed so that is working but the page hangs. The reverse proxy is not the issue here as I have tried this with and without the reverse proxy.
The IIS server has the latest dotnet core 3.0 RTM installed.

**Comment by javiercn** [comment]
@blankenbush Thanks for contacting us.

This behavior is by design, SignalR doesn't guarantee that the HttpContext is available, so the fact that you were able to access it at some point is a coincidence and our recommendation is that you don't rely on it.

Server-side blazor is built on top of SignalR, so the same restrictions and guidance offered for other SignalR apps apply to blazor server-side apps.

**Comment by blenke** [comment]
Is there another way to access the variables from the single sing on ? I need to access the userid that is passed by this system.

**Comment by javiercn** [comment]
@blenke There is no easy way to do this at the moment. 
One possible way to do this today is to put the headers you need into a protected cookie and use a custom authentication handler to authenticate the user using the cookie you generated the first time.

In 3.1 you can capture all the information you need and pass it as a parameter to the root component in your server-side blazor app when you render the component root component into the page.
