### ISSUE TITLE
[Blazor] Non-trivial UI best practices

### ISSUE THREAD

**Issue by DanielProgrammer007** [aspnet/AspNetCore#14875]
Here is a conceptual outline of my scenario.

On the left of the screen, user can enter search criteria identifying list of customers (SearchOptions component).
Next to it is a grid (Customers component) that displays list of customers based on the search criteria specified in the SearchOptions component. Search results (Customers component) will be updated whenever user clicks "Search" button inside the SearchOptions component.
User can then click on an individual customer listed in the grid (Customers component) - at that point, both CustomerDetail and Document components needed to be updated to display additional information on the selected customer.

```
ViewCustomers Component (parent container)
----------------------------------------
|SearchOptions|Customers|CustomerDetail|
|  Name       |         |--------------|
|  Type       |         |Document      |
|--------------------------------------|
```
I am trying to understand what is the best practice to implement this scenario. First (and simplest approach) that I tried was to capture a callback from child components in the parent ViewCustomers component and then issue a call to referenced child components as necessary. According to the (very sparse) documentation, this seems to be an anti-pattern.

```
<div ...>
    <SearchOptions OnSearch="Search" />
</div>
<div ...>
    <Customers @ref="m_customers" OnSelectedCustomerChanged="SetCustomer" />
</div>
<div ...>
    <div ...>
        <div ...>
            <CustomerDetail @ref="m_customerDetail" />
        </div>
        <div ...>
            <Document @ref="m_document" />
        </div>
     </div>
</div>

@code
{
    protected Customers m_customers;
    protected CustomerDetail m_customerDetail;
    protected Document m_document;

    public void Search(SearchOptions options)
    {
        m_customers.Search(options);
    }

    public void SetCustomer(Guid customerGuid)
    {
        m_customerDetail.SetCustomerDetail(customerGuid);
        m_document.LoadDocument(customerGuid);
    }
}
```
Second approach that I tried (which based on researching the very little information there is on Blazor) was to create a service (ComponentState) that various components subsribe to. Individual component can then trigger an event to notify a parent/sibling component that the other component will then handle. Since I am storing model (such as Search or CustomerGuid) inside each inidvidual component, I am using the service only as a notification mechanism. Is this the right pattern?

One problem using this approach that I ran into is limited types of scopes when registering service. In my real-world project, there can be multiple instances of the parent ViewCustomers component (think Visual Studio-like multi-tab UI) and I need to inject instance of ComponentState that will only notify child components within that instance. I cannot use singleton for obvious reasons, so I ended up registering the service using transient scope and then pass the injected ComponentState instance into child components using <CascadingValue> parameter. Is this the right approach?

```
@inject ComponentState State

<CascadingValue Value="State" Name="ComponentState">
    <div ...>
        <SearchOptions />
    </div>
    <div ...>
        <Customer />
    </div>
    <div ...>
        <div ...>
            <div ...>
                <CustomerDetail />
            </div>
            <div ...>
                <Document />
            </div>
         </div>
    </div>
</CascadingValue>
```
```
public class ComponentState
{
    public event Action<Options> OnSearchOptionsChanged;
    public event Action<Guid> OnCustomerGuidChanged;

    public void SetSearchOptions(SearchOptions options)
    {
        OnSearchOptionsChanged?.Invoke(options);
    }

    public void SetCustomerGuid(Guid filingGuid)
    {
        OnCustomerGuidChanged?.Invoke(filingGuid);
    }
}
```

```
public class SearchOptionsBase : ComponentBase
{
    [CascadingParameter(Name = "ComponentState")]
    public ComponentState State { get; set; }

    protected SearchOptions m_options = new SearchOptions();

    protected void Submit()
    {
        State.SetSearchOptions(m_options);
    }
}
```

```
public class CustomersBase : ComponentBase
{
    [CascadingParameter(Name="ComponentState")]
    public ComponentState State { get; set; }

    protected IEnumerable<CustomersLookup> m_customers = new CustomersLookup[] { };

    protected override void OnInitialized()
    {
        State.OnSearchOptionsChanged += State_OnSearchOptionsChanged;
    }

    private void State_OnSearchOptionsChanged(SearchOptions options)
    {
        // populate customers grid
        // ...
        StateHasChanged();
    }
}
```

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages();
    services.AddServerSideBlazor();

    services.AddTransient<Services.ComponentState>();
}
```

I would like to hear from someone on the Blazor team to answer the question. There are virtually no real-world examples of using Blazor, I think it would really help developers if Microsoft published several demo projects and ideally test this technology on creating an actual MS product - maybe this is already at works?

Anyway, I'm very excited for the first official release! Keep up the great work.

**Comment by javiercn** [comment]
@DanielProgrammer007 Thanks for contacting us.

It looks like this is a question about how to use Blazor. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

**Comment by DanielProgrammer007** [comment]
@javiercn thank you for responding. However, I'd rather have someone from Microsoft provide guidance, not a random developer on StackOverflow simply stating his/her opinion.

I've done my research (GitHub, StackOverflow, various Blazor articles I found on the Internet) on how sibling components should communicate, but there is very little information available outside of how to create a to-do list. There are other scenarios besides the one relevant to this post that I'm curious about, more on those maybe later.

If MS created a few sample "best practices" projects for more complex UI cases, it would save potential Blazor developers lot of time (and you as well, since you would not have to deal with questions like mine).

Thank you!

**Comment by javiercn** [comment]
@DanielProgrammer007 If you want to check a more complex sample you could take a look at the Blazzing Pizza app here https://github.com/dotnet-presentations/blazor-workshop/
