### ISSUE TITLE
Scenarios are not running: FortunesPostgreSql-FastHttp, FortunesPostgreSql-NodeJs, FortunesPostgreSql-Ulib, Json-FastHttp, Json-NodeJs ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14888]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| FortunesPostgreSql-FastHttp | Linux, Physical, http, KestrelSockets | 10/9/19 1:38:45 PM +00:00 |
| FortunesPostgreSql-NodeJs | Linux, Physical, http, KestrelSockets | 10/9/19 1:33:28 PM +00:00 |
| FortunesPostgreSql-Ulib | Linux, Physical, http, KestrelSockets | 10/9/19 1:41:25 PM +00:00 |
| Json-FastHttp | Linux, Physical, http, KestrelSockets | 10/9/19 1:37:51 PM +00:00 |
| Json-NodeJs | Linux, Physical, http, KestrelSockets | 10/9/19 1:32:36 PM +00:00 |
| Plaintext-FastHttp | Linux, Physical, http, KestrelSockets | 10/9/19 1:37:01 PM +00:00 |
| Plaintext-NodeJs | Linux, Physical, http, KestrelSockets | 10/9/19 1:31:41 PM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Fixed
