### ISSUE TITLE
Windows AuthenticationDisplayName always null

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/AspNetCore#14882]
Even when you do this:

```
services.Configure<IISOptions>(iis =>
{
    iis.AuthenticationDisplayName = "Windows";
    iis.AutomaticAuthentication = false;
});
```

The display name for Windows is always null when using `IAuthenticationSchemeProvider.GetAllSchemesAsync`.

**Comment by Tratcher** [comment]
IIS in-proc or out of proc? They use different options types, you might just be changing the wrong one. IISOptions is for out of proc, but most apps these days use in proc.

In proc:
https://github.com/aspnet/AspNetCore/blob/aaaaf572fdf11088ee0efd205ff6834e16a36804/src/Servers/IIS/IIS/src/IISServerOptions.cs#L31
https://github.com/aspnet/AspNetCore/blob/aaaaf572fdf11088ee0efd205ff6834e16a36804/src/Servers/IIS/IIS/src/Core/IISHttpServer.cs#L80

Out of proc:
https://github.com/aspnet/AspNetCore/blob/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Servers/IIS/IISIntegration/src/IISOptions.cs#L18
https://github.com/aspnet/AspNetCore/blob/f6c3f9e02ab7c4ae5c395245f2792ba18c33075a/src/Servers/IIS/IISIntegration/src/IISMiddleware.cs#L82

**Comment by leastprivilege** [comment]
Thanks - that's indeed the problem. Not sure I am happy that this is the solution though ;)
