### ISSUE TITLE
new api controller provides help link to add new view

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14898]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/659019/new-api-controller-provides-help-link-to-add-new-v.html)._

---
When I create a new controller in .net core 3.0, it creates a controller class with the following comment: 

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

the link points to an &quot;add view&quot; documentation.

---
#### Visual Studio Feedback System on 7/24/2019, 02:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/24/2019, 11:40 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by ryanbrandenburg** [comment]
What was the workflow you did to create the controller? I've looked in our templates but I only see the string you list in documentation and samples. Did you just copy from there (which would still need fixing) or did you use actual templating functionality?

**Comment by ryanbrandenburg** [comment]
Actually, I don't even see those visible publicly anywhere. I'm going to close this due to no response and  and lack of context. If someone sees this link out in the wild in the wrong context feel free to either reopen this or create a new issue.
