### ISSUE TITLE
.netcore web project, debugging when modifying the contents of the razor page does not take effect, only recompile to take effect...

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14896]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/750658/netcore-web项目调试时修改razor页面内容后不生效只能通过重新编译才能生效.html)._

---
(Regression)
(worked-in:16.1)
Start debugging by F5 Re-modifying the contents of the .cshmtl page The contents of the browser will not be updated... Previous versions don't have this problem...

---
#### Visual Studio Feedback System on 9/27/2019, 01:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/27/2019, 01:50 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please provide more details about what project are you using and share the project file?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by thepra** [comment]
I'm facing this issue too. My solution is based on .NET Core 3.x. In my case I found that the updates applied to .cshtml files work only on "Start Without Debugging", useful for now but not ideal for debugging. Both the Start(with debugging) from kestrel(console) and IIS have this issue.
Here's the Solution and Project file:
[collanon.zip](https://github.com/aspnet/AspNetCore/files/3773739/collanon.zip)

**Comment by mkArtakMSFT** [comment]
Thanks @thepra. Bringing this up for triage on monday. In the meantime, can you please host your projects as a github repo, as it's much simpler that way to look into the code and navigate

**Comment by thepra** [comment]
Mmmmm, it's more of a closed source web app(already running as [collAnon](https://collanon.app)) than an open source project. 
But still I could open up some non-business-core pieces like `Startup.cs` or `Program.cs`, etc. in a new project if it can help, just let me know.

**Comment by mkArtakMSFT** [comment]
To enable runtime-compilation it's now required to use a special NuGet package. You can read more about how to enable runtime-compilation here: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#runtime-compilation

**Comment by thepra** [comment]
> 
> 
> To enable runtime-compilation it's now required to use a special NuGet package. You can read more about how to enable runtime-compilation here: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#runtime-compilation

Ok... but should I isolate it like this?
```
#if DEBUG 
    .AddRazorRuntimeCompilation()
#endif
```
because adding runtime compilation in Release/Production doesn't make that much sense. 🤔

**Comment by javiercn** [comment]
@thepra That sounds like a valid solution.

**Comment by javiercn** [comment]
We are closing this issue as it has been handled.
