### ISSUE TITLE
SignalR Core typename handling

### ISSUE THREAD

**Issue by fleed** [aspnet/AspNetCore#14891]
How do I handle inherited classes for handlers of send operations? I'm trying to send messages of inherited types, but my handlers on the client side are not triggered. Example:

```csharp
public class Notification { }

public class NotificationA : Notification { }

public class NotificationB : Notification { }
```

I send them using the `SendAsync("Notify", notification)` method from a hub, passing either a `NotificationA` or a `NotificationB` object. On the client (.NET core implementation), I subscribe like this:

```csharp
connection.On("Notify", async (Notification notification) => { /* do something */ } );
```

With the above code the handler method is never called. If I change the handler to the expected concrete type:

```csharp
connection.On("Notify", async (NotificationA notification) => { /* do something */ } );
```

then it works.

I thought that I should change the typenamehandling setting in the `AddJsonProtocol` method of the SignalR builder, but there is no option for that.

I'm using `Microsoft.AspNetCore.SignalR (1.1.0)`

Might be related to [https://github.com/dotnet/corefx/issues/41347](https://github.com/dotnet/corefx/issues/41347)

**Comment by BrennanConroy** [comment]
TypeNameHandling is very dangerous and should be avoided at all costs. System.Text.Json explicitly did not add a similar API.

I would instead recommend that you register multiple handlers for each type, example:
```c#
connection.On("NotifyA", async (NotificationA notification) => { /* do something */ } );
connection.On("NotifyB", async (NotificationB notification) => { /* do something */ } );
```

**Comment by anurse** [comment]
Closing as we don't intend to add overload support, using different method names is our intended solution for this issue.
