### ISSUE TITLE
Blazor server side break on exception in Visual Studio

### ISSUE THREAD

**Issue by drinkwater99** [aspnet/AspNetCore#14906]
Is the Visual Studio debugger supposed to break in the code when an exception occurs ?
Currently, if an exception occurs, I see an error in the browser console but Visual Studio does not break on the error. I could swear that this used to work previously.

**Comment by javiercn** [comment]
@drinkwater99 Thanks for contacting us.

Either the exception is happening client-side or your debugger is misconfigured. See
https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2019 for details.

You can add `"detailedErrors": true `to your `appSettings.development.json` to see the full exception details in the browser console.
