### ISSUE TITLE
Creating assemblies with custom authentication middleware

### ISSUE THREAD

**Issue by luisabreu** [aspnet/AspNetCore#14900]
Hello guys.

I have an authentication middleware that was originally written for net core 2.0 (and which has been ported successfully to the 2.2 version). 

Today, I've started migrating the project to net core 3 and the first thing I've done was update the target to netcore30:

``` 
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
...
</Project>
```

After that, I've tried to update the nuget package the project was using. However, it seems that package (Microsoft.AspNetCore.Authentication) hasn't been updated yet to version 3.0 (it's still on version 2.2).  Unfortunately, that means I can't keep using it because net core 3.0 moved some of the types I was using (ex.: RequestPathBaseCookieBuilder is no longer defined in the internal namespace).

After searching for the aspnet core packages, I've noticed that only the OpenId Connect has been update to net core 3. As a workaround, I've ended replacing that package with the Microsoft.AspNetCore.Authentication.OpenIdConnect so that I can use the types defined in the Microsoft.AspNetCore.Authentication.Core et al (this was the only authentication package I've found that was updated to target net core 3.0):
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="3.0.0" />
  </ItemGroup>
</Project>
```
Any idea on when the other packages will be available for net core 3? The current workaround is a quick fix, but it makes no sense since my authentication middleware is using SAML (not oauth or openid connect) to perform the external authentication.

Thanks

**Comment by pranavkm** [comment]
Hi @luisabreu, you'll need a framework reference to `Microsoft.AspNetCore.App` to reference the contents that previously shipped as part of the Auth.Core package. Please follow our migration guide - https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio to migrate your project.

**Comment by luisabreu** [comment]
Ah...damn it...I was using <code>PackageReference</code> instead of <code>ReferencePackage</code>...Thanks!
