### ISSUE TITLE
Make "Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter" public again

### ISSUE THREAD

**Issue by sebnilsson** [aspnet/AspNetCore#14917]
After upgrading a project from ASP.NET Core 2.x and .NET Core 2.x to 3.x, I found that [`Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter`](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Filters/ResponseCacheFilter.cs) has become `internal`.

It previously used to be `public`, when it was [`Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter`](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.Core/src/Internal/ResponseCacheFilter.cs).

**This brakes existing code**, which relies on resolving this filter and modifying it.

**Comment by javiercn** [comment]
Thanks for contacting us @sebnilsson.

In ASP.NET Core, pubinternal types are types that are declared as public but put in an .Internal namespace. While these types are public they have no support policy and are subject to breaking changes. Unfortunately accidental use of these types has been common, resulting in breaking changes to these projects and limiting our ability to maintain the framework.

If you give us some information on what you were trying to with it, we can try and suggest alternative ways of achieving the same thing.

**Comment by pranavkm** [comment]
@sebnilsson is there a reason you are unable to use `ResposeCacheAttribute`? It's how we expect users to configure the filter on their endpoints.

**Comment by sebnilsson** [comment]
@pranavkm The current use, which might be done on completely wrong assumptions, is in a custom implementation of `ExceptionFilterAttribute`.

In the `OnException`-method, we use `context.Filters.OfType<ResponseCacheFilter>().FirstOrDefault()` to resolve the filter and reset all properties. This is done to ensure that nothing like storage, location or duration is set for the returned error page.

**Comment by pranavkm** [comment]
@sebnilsson using the attribute should work just as well here: `context.Filters.OfType<ResponseCacheAttribute>().FirstOrDefault()`

You could also indiscriminately clear out the cache headers. This is what the exception handling middleware does - https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L153-L161. The outcome should no different than what you get with your current check.

**Comment by sebnilsson** [comment]
I sort of expected that was the case :)
