### ISSUE TITLE
Build Failed ASP.NET Core from Source !

### ISSUE THREAD

**Issue by taomylife521** [aspnet/AspNetCore#14912]
### Describe the bug
Execute restore.cmd

### To Reproduce
1. Using this version of ASP.NET Core 3.0

### Expected behavior
build sucess

### Screenshots
![image](https://user-images.githubusercontent.com/9649318/66637310-5eddbf00-ec45-11e9-9c96-0a29ff0d07e4.png)
![image](https://user-images.githubusercontent.com/9649318/66637333-656c3680-ec45-11e9-8f79-6c7c7785d62a.png)

### Additional context
Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/9649318/66637376-7ddc5100-ec45-11e9-854e-057895b1c18b.png)

**Comment by javiercn** [comment]
@taomylife521 Thanks for contacting us.

I would recommend you do a `git clean -xdff` at the repo root (save any existing change you want to keep) and try again. If that doesn't solve your problem, @aspnet/build can have some suggestions for further things to try.

**Comment by pavinan** [comment]
@taomylife521 

RoslynTools.MSBuild.16.0.0-alpha.nupkg is not properly bundled so it is missing some files.
It is missing the "VC" folder and also the wrong name for python tools.

Do following:

Step 1:
Copy the "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC" into 
into "{{root of your project}}\.tools\msbuild\16.0.0-alpha\tools\MSBuild\Microsoft"

Step 2:
Rename "Python%20Tools" to "Python Tools" in {{root of your project}}.tools\msbuild\16.0.0-alpha\tools\MSBuild\Microsoft\VisualStudio\v16.0

**Comment by taomylife521** [comment]
> @taomylife521 Thanks for contacting us.
> 
> I would recommend you do a `git clean -xdff` at the repo root (save any existing change you want to keep) and try again. If that doesn't solve your problem, @aspnet/build can have some suggestions for further things to try.

It doesn't seem to work！
![image](https://user-images.githubusercontent.com/9649318/66692549-14eeea80-ecd2-11e9-997a-56a0791c3a50.png)
![image](https://user-images.githubusercontent.com/9649318/66692556-220bd980-ecd2-11e9-8aaf-5afaf2030482.png)
![image](https://user-images.githubusercontent.com/9649318/66692564-36e86d00-ecd2-11e9-8746-22dfd566156c.png)

![image](https://user-images.githubusercontent.com/9649318/66692558-2b954180-ecd2-11e9-8405-a165a6a97f1f.png)

**Comment by taomylife521** [comment]
> @taomylife521
> 
> RoslynTools.MSBuild.16.0.0-alpha.nupkg is not properly bundled so it is missing some files.
> It is missing the "VC" folder and also the wrong name for python tools.
> 
> Do following:
> 
> Step 1:
> Copy the "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC" into
> into "{{root of your project}}.tools\msbuild\16.0.0-alpha\tools\MSBuild\Microsoft"
> 
> Step 2:
> Rename "Python%20Tools" to "Python Tools" in {{root of your project}}.tools\msbuild\16.0.0-alpha\tools\MSBuild\Microsoft\VisualStudio\v16.0
> 
> Note:
> MSBuild version may be different for you but it is always 16.somenumber.somenumber-alpha.
> This issue still remains for 16.3.0-alpha also.
> Basically it is trying to download from https://dotnet.myget.org/feed/roslyn-tools/package/nuget/RoslynTools.MSBuild.

It doesn't seem to work！
![image](https://user-images.githubusercontent.com/9649318/66692577-554e6880-ecd2-11e9-81d1-e86dd8ce6db4.png)
![image](https://user-images.githubusercontent.com/9649318/66692579-5bdce000-ecd2-11e9-8156-3a7f8b474e34.png)
![image](https://user-images.githubusercontent.com/9649318/66692585-72833700-ecd2-11e9-8548-210550921b8c.png)

**Comment by taomylife521** [comment]
> > @taomylife521 Thanks for contacting us.
> > I would recommend you do a `git clean -xdff` at the repo root (save any existing change you want to keep) and try again. If that doesn't solve your problem, @aspnet/build can have some suggestions for further things to try.
> 
> It doesn't seem to work！
> ![image](https://user-images.githubusercontent.com/9649318/66692549-14eeea80-ecd2-11e9-997a-56a0791c3a50.png)
> ![image](https://user-images.githubusercontent.com/9649318/66692556-220bd980-ecd2-11e9-8aaf-5afaf2030482.png)
> ![image](https://user-images.githubusercontent.com/9649318/66692564-36e86d00-ecd2-11e9-8746-22dfd566156c.png)
> 
> ![image](https://user-images.githubusercontent.com/9649318/66692558-2b954180-ecd2-11e9-8405-a165a6a97f1f.png)

![image](https://user-images.githubusercontent.com/9649318/66692592-7a42db80-ecd2-11e9-9594-3b68f4eda707.png)

**Comment by dougbu** [comment]
@taomylife521 what are you trying to show us? Could you minimize things to a set of steps and their result in clear text please?

**Comment by taomylife521** [comment]
> @taomylife521 what are you trying to show us? Could you minimize things to a set of steps and their result in clear text please?

Read the comments above！I tried the above method but it still didn't work！I got a screenshot of what I was trying to do！
I sent you a build failure log！What is the problem that caused the build to fail, and is there a solution？
#--------------------------------------------------------------------------#
D:\myapp\ASPNETCORE3.0\AspNetCore>restore.cmd
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in D:\Program Files.
Detected JDK in D:\开发软件\openjdk-12.0.2_windows-x64_bin\jdk-12.0.2 (via JAVA_HOME)
  C:\Users\Administrator\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19462.4\tools\Tools.proj 的还原在 358.45 ms
   内完成。
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.0/dotnet-runtime-3.0.0-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.0/dotnet-runtime-3.0.0-win-x64.zip
dotnet-install: Adding to current process PATH: "D:\myapp\ASPNETCORE3.0\AspNetCore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.0/dotnet-runtime-3.0.0-win-x86.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.0/dotnet-runtime-3.0.0-win-x86.zip
dotnet-install: Adding to current process PATH: "D:\myapp\ASPNETCORE3.0\AspNetCore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : warning NU1603: RepoTasks 依赖于 Microsoft.Build
(>= 15.8.166)，但找不到 Microsoft.Build 15.8.166。 已解决 Microsoft.Build 16.0.443 的近似最佳匹配。  [D:\myapp\ASPNETCORE3.0\AspNetCore\
.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : warning NU1603: RepoTasks 依赖于 Microsoft.Source
Link.GitHub (>= 1.0.0-beta2-19367-01)，但找不到 Microsoft.SourceLink.GitHub 1.0.0-beta2-19367-01。 已解决 Microsoft.SourceLink.G
itHub 1.0.0-beta2-19380-04 的近似最佳匹配。  [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\C
ommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : warning NU1603: RepoTasks 依赖于 Microsoft.Source
Link.Vsts.Git (>= 1.0.0-beta2-19367-01)，但找不到 Microsoft.SourceLink.Vsts.Git 1.0.0-beta2-19367-01。 已解决 Microsoft.SourceLi
nk.Vsts.Git 1.0.0-beta2-19380-04 的近似最佳匹配。  [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7
\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102: 找不到版本为 (>= 1.16.30) 的包 Microsoft
.VisualStudio.Setup.Configuration.Interop [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\
IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 dotnet-core 中找到 16 个版本[ 最接
近版本: 1.11.2290 ] [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Micr
osoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnetcore-dev 中找到 0 个版本 [
D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.
targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnetcore-tools 中找到 0 个版本
 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGe
t.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 roslyn-tools 中找到 0 个版本 [D:
\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.ta
rgets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 roslyn 中找到 0 个版本 [D:\myapp
\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnet-aspnetcore-tooling
中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\N
uGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnet-blazor 中找到 0 个版本 [D
:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.t
argets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnet-entityframeworkcore 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\
NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnet-extensions 中找到 0 个版
本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 grpc-nuget-dev 中找到 0 个版本 [
D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.
targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-aspnet-AspNetCore-Tooling-16b0ca4 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExten
sions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-aspnet-EntityFrameworkCore-b403b17 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExte
nsions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-aspnet-Extensions-0b951c1 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Mi
crosoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-dotnet-core-setup-7d57652 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Mi
crosoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-dotnet-corefx-4ac4c03 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Micros
oft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1605: 检测到包降级: Microsoft.Build.Framewor
k 从 16.0.443 降级到 15.8.166。直接从项目引用包以选择不同版本。  [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common
7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1605:  RepoTasks -> Microsoft.Build 16
.0.443 -> Microsoft.Build.Framework (>= 16.0.443)  [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools
\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1605:  RepoTasks -> Microsoft.Build.Fr
amework (>= 15.8.166) [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions
\Microsoft\NuGet\NuGet.targets]
  D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj 的还原在 20.18 sec 内失败。
Build failed.

D:\myapp\ASPNETCORE3.0\AspNetCore>restore.cmd
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in D:\Program Files.
Detected JDK in D:\开发软件\openjdk-12.0.2_windows-x64_bin\jdk-12.0.2 (via JAVA_HOME)
  C:\Users\Administrator\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19462.4\tools\Tools.proj 的还原在 52.69 ms
  内完成。
dotnet-install: .NET Core Runtime version 3.0.0 is already installed.
dotnet-install: Adding to current process PATH: "D:\myapp\ASPNETCORE3.0\AspNetCore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: .NET Core Runtime version 3.0.0 is already installed.
dotnet-install: Adding to current process PATH: "D:\myapp\ASPNETCORE3.0\AspNetCore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : warning NU1603: RepoTasks 依赖于 Microsoft.Build
(>= 15.8.166)，但找不到 Microsoft.Build 15.8.166。 已解决 Microsoft.Build 16.0.443 的近似最佳匹配。  [D:\myapp\ASPNETCORE3.0\AspNetCore\
.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : warning NU1603: RepoTasks 依赖于 Microsoft.Source
Link.GitHub (>= 1.0.0-beta2-19367-01)，但找不到 Microsoft.SourceLink.GitHub 1.0.0-beta2-19367-01。 已解决 Microsoft.SourceLink.G
itHub 1.0.0-beta2-19380-04 的近似最佳匹配。  [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\C
ommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : warning NU1603: RepoTasks 依赖于 Microsoft.Source
Link.Vsts.Git (>= 1.0.0-beta2-19367-01)，但找不到 Microsoft.SourceLink.Vsts.Git 1.0.0-beta2-19367-01。 已解决 Microsoft.SourceLi
nk.Vsts.Git 1.0.0-beta2-19380-04 的近似最佳匹配。  [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7
\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102: 找不到版本为 (>= 1.16.30) 的包 Microsoft
.VisualStudio.Setup.Configuration.Interop [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\
IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 dotnet-core 中找到 16 个版本[ 最接
近版本: 1.11.2290 ] [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Micr
osoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnetcore-dev 中找到 0 个版本 [
D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.
targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnetcore-tools 中找到 0 个版本
 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGe
t.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 roslyn-tools 中找到 0 个版本 [D:
\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.ta
rgets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 roslyn 中找到 0 个版本 [D:\myapp
\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnet-aspnetcore-tooling
中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\N
uGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnet-blazor 中找到 0 个版本 [D
:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.t
argets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnet-entityframeworkcore 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\
NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 aspnet-extensions 中找到 0 个版
本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 grpc-nuget-dev 中找到 0 个版本 [
D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.
targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-aspnet-AspNetCore-Tooling-16b0ca4 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExten
sions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-aspnet-EntityFrameworkCore-b403b17 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExte
nsions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-aspnet-Extensions-0b951c1 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Mi
crosoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-dotnet-core-setup-7d57652 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Mi
crosoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1102:   - 在 darc-pub-dotnet-corefx-4ac4c03 中找到 0 个版本 [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Micros
oft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1605: 检测到包降级: Microsoft.Build.Framewor
k 从 16.0.443 降级到 15.8.166。直接从项目引用包以选择不同版本。  [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common
7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1605:  RepoTasks -> Microsoft.Build 16
.0.443 -> Microsoft.Build.Framework (>= 16.0.443)  [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools
\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets]
D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1605:  RepoTasks -> Microsoft.Build.Fr
amework (>= 15.8.166) [D:\myapp\ASPNETCORE3.0\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions
\Microsoft\NuGet\NuGet.targets]
  D:\myapp\ASPNETCORE3.0\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj 的还原在 2.04 sec 内失败。
Build failed.
#--------------------------------------------------------------------------#

**Comment by pavinan** [comment]
@taomylife521  What version .net framework do you have? Nuget needs >=4.7.

download from here if it isn't latest. https://dotnet.microsoft.com/download/dotnet-framework

**Comment by taomylife521** [comment]
> @taomylife521 What version .net framework do you have? Nuget needs >=4.7.
> 
> download from here if it isn't latest. https://dotnet.microsoft.com/download/dotnet-framework

![image](https://user-images.githubusercontent.com/9649318/66694543-20004580-ece7-11e9-9f97-d75cad77e253.png)
![image](https://user-images.githubusercontent.com/9649318/66694556-31e1e880-ece7-11e9-8d9b-949b39cbbf4a.png)

**Comment by dougbu** [comment]
@taomylife521 VS 2019 must be installed in order to build this repo. I'm actually surprised `restore.cmd` got as far as it did.

eng/scripts/InstallVisualStudio.ps1 can help with the installation. Use `help eng\scripts\InstallVisualStudio.ps1 -full` in PowerShell to see the supported options.

**Comment by taomylife521** [comment]
> @taomylife521 VS 2019 must be installed in order to build this repo. I'm actually surprised `restore.cmd` got as far as it did.
> 
> eng/scripts/InstallVisualStudio.ps1 can help with the installation. Use `help eng\scripts\InstallVisualStudio.ps1 -full` in PowerShell to see the supported options.

i have installed vs 2019

**Comment by taomylife521** [comment]
No one can answer my doubts？

**Comment by pavinan** [comment]
@taomylife521 delete ".tools" folder and try again.

**Comment by taomylife521** [comment]
> @taomylife521 delete ".tools" folder and try again.

Delete folder.tool. It still doesn't seem to work！
[BuildLogDetail.txt](https://github.com/aspnet/AspNetCore/files/3741893/BuildLogDetail.txt)

**Comment by taomylife521** [comment]
> > i have installed vs 2019
> 
> Your screen shot was from VS 2017.
> 
> > Using this version of ASP.NET Core 3.0
> 
> Do you mean you have checked out the 'release/3.0' branch?
> 
> What @pavinan said sounds like a good idea.
> 
> Another possibility is that you have a NuGet.config in your environment disabling some of the required sources. Check AppData\Roaming\NuGet\NuGet.Config in your user profile.

![image](https://user-images.githubusercontent.com/9649318/67059420-8d9aee80-f18b-11e9-840c-2df4261b4edb.png)

![image](https://user-images.githubusercontent.com/9649318/67059407-7bb94b80-f18b-11e9-85ba-cee7989b5f01.png)

![image](https://user-images.githubusercontent.com/9649318/67059432-9a1f4700-f18b-11e9-9547-ca1051f70d40.png)



[NuGetConfig.txt](https://github.com/aspnet/AspNetCore/files/3741937/NuGetConfig.txt)
[BuildLogDetail.txt](https://github.com/aspnet/AspNetCore/files/3741938/BuildLogDetail.txt)

Please Help me ! Thank you!
