### ISSUE TITLE
Change default controller based on user is authenticated or not

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/AspNetCore#14918]
What is the preferred way of dealing with default controller name. The idea I have is to route non authenticated users to the home controller and authenticated users to app controller. I want to serve the views using the default path `/` in both cases. Is a route constraint the preferred way? If so, can you point me to an example implementation?

**Comment by javiercn** [comment]
@marcuslindblom Thanks for contacting us.

I would suggest that you simply use separate urls and redirect incoming requests based on whether the user is authenticated or not.

If you still want to do this, the best way to achieve it IMO is using attribute routing, adding [HttpGet("/")] to both controllers and using an IActionConstraint to disambiguate the route.

Hope that helps.

**Comment by marcuslindblom** [comment]
@javiercn Ok, so I tried using the `IActionConstraint`like this. I created two constraints, `AnonymousConstraint` and `AuthenticatedConstraint`. This is how I implemented them.

```c#
  public class AuthenticatedConstraint : Attribute, IActionConstraint
  {
    public int Order => 1;
    public bool Accept(ActionConstraintContext context)
    {
        if (context.RouteContext.HttpContext.User.Identity.IsAuthenticated)
        {
            return true;
        }

        return false;
    }
  }
```

```c#
  public class AnonymousConstraint : Attribute, IActionConstraint
  {
    public int Order => 1;
    public bool Accept(ActionConstraintContext context)
    {
        if (context.RouteContext.HttpContext.User.Identity.IsAuthenticated)
        {
            return false;
        }

        return true;
    }
  }
```

And this is how my controllers use the attributes.

```c#
  public class HomeController : Controller
  {
    [AnonymousConstraint, HttpGet("/")]
    public IActionResult Index() {
      return View();
    }
  }
```

```c#
  public class AppController : Controller {
    [AuthenticatedConstraint, HttpGet("/")]
    public IActionResult Index() {
      return View();
    }
  }
```

But `context.RouteContext.HttpContext.User.Identity.IsAuthenticated` is always false?

**Comment by javiercn** [comment]
@marcuslindblom Is the user authenticated when it hits the action?

**Comment by marcuslindblom** [comment]
@javiercn Yes, in the `Index` action the user is authenticated. I use Google authentication is this app. Maybe it has something todo with that?

**Comment by javiercn** [comment]
Do you have `app.UseAuthentication()` in your Configure method? 

What might be happening is that the constaint is being evaluated before UseAuthentication establishes the user on the request.

If that's the case, I would go back to my original suggestion and use separate routes and simply redirect from "/" to the appropriate place.

**Comment by marcuslindblom** [comment]
@javiercn Ok, so the order of things matter for this to work.

This configuration works for me but I don't know if something else stopped working. Do you know if this breaks something else?

```c#
app.UseAuthentication();

app.UseRouting();

app.UseAuthorization();
```

**Comment by javiercn** [comment]
I'm not sure of the unintended consequences that might have, so I wouldn't do that before thinking it through. My recommendation is that you go back to my original suggestion.

@rynowak Any further recommendation here? This is an interesting case I think, because this would have worked in 2.1 if I'm not mistaken, but in 3.0 the constraint gets evaluated much earlier.

**Comment by marcuslindblom** [comment]
I forgot to say that I’m using 3.0.100

**Comment by marcuslindblom** [comment]
I ended up with this code. Feel free to comment or criticize :)

Using this order:

```c#
app.UseAuthentication();
app.UseRouting();
app.UseAuthorization();
```

With the default controller set to `App`:
```c#
endpoints.MapControllerRoute(
    name: "default",
    pattern: "{controller=App}/{action=Index}/{id?}");
```

Just adding the `HttpGet` to the `HomeController`:
```c#
public class HomeController : Controller
{
  [HttpGet("/")]
  public IActionResult Index() {
    return View();
  }
}
```
Adding the `IActionConstraint` only to the `AppController`:

```c#
[Authorize, AuthenticatedConstraint]
public class AppController : Controller {
  [HttpGet("/")]
  public IActionResult Index() {
    return View();
  }
}
public class AuthenticatedConstraint : Attribute, IActionConstraint
{
  public int Order => 1;
  public bool Accept(ActionConstraintContext context)
  {
      if (context.RouteContext.HttpContext.User.Identity.IsAuthenticated)
      {
          return true;
      }

      return false;
  }
}
```
