### ISSUE TITLE
What's the Url.Content way to convert virtual realtive path starting with ~ in 3.0 ?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/AspNetCore#14914]
I need to convert relative path to absolute path in a tag helper, so `~/some/path became => protocol://mydomain.tld/anyvirtualpath/some/path`

I used this code on 2.2:
```
var urlHelper = urlHelperFactory.GetUrlHelper(ViewContext);
var result = urlHelper.Content("~/some/path");
```

On 3.0, using endpoint routing, I get an exception if I add IUrlHelperFactory to IoC container because route data is empty. (or something like that)

But when trying to accomplish the same goal with LinkGeneration I cannot find a method/way to do what I want.

So what's the 3.0 way to convert virtual relative path to absolute paths?

**Comment by javiercn** [comment]
@Bartmax Thanks for contacting us.

You can use the `UriHelper.BuildAbsolute` static method to do this as follows
```csharp
            var r = context.Request;
            UriHelper.BuildAbsolute(
                r.Scheme,
                r.Host,
                r.PathBase,
                "/some/path");
```

Hope that helps.
