### ISSUE TITLE
Model Validation runs on byte[] causing significant slowdown.

### ISSUE THREAD

**Issue by jocco** [aspnet/AspNetCore#14913]
# Describe the bug

I have added a custom InputFormatter to allow me to bind the request body to a byte[], this results in the model validation running on this array (which is a file and thus can be quite big) causing significant slow downs.

The documentation for model validation claims that this should not happen as arrays of primitive types should be short circuited
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.0#automatic-short-circuit

### To Reproduce
Using Aspnet core 3

Add a RawRequestBodyFormatter InputFormatter (source attached)
[RawRequestBodyFormatter.txt](https://github.com/aspnet/AspNetCore/files/3716636/RawRequestBodyFormatter.txt)

`
            services.AddControllers()
                .AddMvcOptions(options =>
                {
                    options.InputFormatters.Insert(0, item: new RawRequestBodyFormatter());
`

Add a POST or PUT method that binds the body into a byte array
`
        [HttpPost("{bucket}")]
        [RequestSizeLimit(50_000_000)]
        public async Task<IActionResult> Post(
            [Required] string bucket,
            [FromBody] byte[] blob)
        {

        }
`

When posting a file of 30 MBs this takes about 4 seconds to do the model validation running locally under IIS Express.

### Expected behavior
The byte[] should not have validation applied to it as per the documentation. Even if the documentation is incorrect and enumerations of primitive types should have validation, there doesn't seem to be any point in validating a byte[]

### Screenshots
Screenshot of dotTrace showing the cpu spend in ValidationVisitor
![modelValidationProfile](https://user-images.githubusercontent.com/13694867/66639662-95044a00-ec17-11e9-86e4-8023d7b87c9b.png)

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@jocco Thanks for contacting us.

We don't recommend that approach to achieve what you are trying to accomplish.

Instead of implementing a custom InputFormatter you can implement a custom model binder to bind the body into a byte array. See https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.0 for details on how to do that.

If you still have issues after that, feel free to reopen the issue.
