### ISSUE TITLE
Just .NET Runtime for Javascript

### ISSUE THREAD

**Issue by sdyalor** [aspnet/AspNetCore#14910]
Blazor is awesome, but I need language features like LINQ or DataFrame.
Is there a way to wrap this on an already developed javascript project?

**Comment by javiercn** [comment]
@sdyalor Thanks for contacting us.

Can you clarify what you are trying to accomplish?

**Comment by danroth27** [comment]
Hi @sdyalor.  LINQ is already supported in Blazor apps. I don't know of any built-in support for DataFrames in .NET, but it looks like there are existing libraries from the .NET community that you should be able to use as long as they support .NET Standard.

If you have an existing JS project, you can add Blazor functionality to it as long as your JS code and Blazor code aren't trying to manipulate the same DOM elements. Blazor generally assumes it has fully control of the DOM it is manipulating. You can also call into JS from your Blazor app using [JS interop](https://docs.microsoft.com/aspnet/core/blazor/javascript-interop).

It sounds like you may also be asking about the ability to create a WebAssembly module from .NET that you can then call into from your existing JS code. That's not something we support today in any first-class way, but it is a scenario we hope to look at in the future.

@richlander @lewing
