### ISSUE TITLE
Library embeded JavaScript reference missing

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetCore#14911]
just start with teh default Razor library project in Visual studio 2019 
there is a examplejsinterop.js and examplejsinterop.cs
subquestion why is method "prompt" static and not injected?

as testcase 
make a call from a 2nd blazor type project and do not reference in _host.cshtml the javasricpt with 
<script src="_content/RazorClassLibrary1/exampleJsInterop.js"></script>

1) there is no warning nowhere- expected result- give me feedback that I forgot something
2) it would be great to automatic reference JS from components to reduce source of bugs

**Comment by javiercn** [comment]
@hannespreishuber Thanks for contacting us.

It might be tempting to try and inject scripts automatically, as it looks straightforward for simple cases like this, however, there are many challenges that arise from importing resources automatically in the general case. Importing assets automatically is a very complicated problem that has to deal with same of the similar concerns that package managers have to.
For an automatic "import system" you need to take into account:
* Order of the files within a given package/project.
* How to handle conflicts between packages importing different versions of the same library.
* Order of the files between packages/projects.
* How to handle when multiple assets are available as options in the package.
* etc.

Our approach is to simply make all the assets available to you at build and publish time and to give you control over what content you bring into your app and how.

**Comment by hannespreishuber** [comment]
ok- whats about some error messages for missing script?

**Comment by javiercn** [comment]
@hannespreishuber We can't difference between you not wanting to include a script of forgetting about it. 

As an example, Imagine that you include in your library two conflicting scripts for different configurations of the library. If we were to add an error, we would be producing warnings in many situations where not including a script is intentional.

We are looking into ways of improving the developer experience about using static web assets, but ultimately you need to include the appropriate tags in the right places.

**Comment by hannespreishuber** [comment]
my point is - calling a JS on runtime can be buggy without any notification for 
a) missing js file link
b) typo in function name

that is unexpected (Browser command window) 
both cases have a high probability

**Comment by danroth27** [comment]
Hi @hannespreishuber. We are doing some work in 3.1 to improve the error handling experience. I've filed https://github.com/aspnet/AspNetCore/issues/14938 to track improving the experience when an unhandled exception occurs (like when a JS interop call was attempted and the specific JS function doesn't exist). Thanks for this feedback!
