### ISSUE TITLE
Using 'UseMvc' to configure MVC is not supported while using Endpoint Routing. To continue using 'UseMvc', please set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices'. (Razor Pages)

### ISSUE THREAD

**Issue by jomeno** [aspnet/AspNetCore#14929]
### Scenario.
I just upgraded a .netcoreapp2.2 Razor Pages web app (also containing some controllers annotated as <code>[ApiController]</code>) to .netcoreapp3.3 using the docs at https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#update-routing-startup-code.

Afterwards, Javascript calls to the Api controllers started returning 404 until I included:
<code>app.UseMvc()</code> in Configure method in Startup.cs which led to this warning message: 

"Using 'UseMvc' to configure MVC is not supported while using Endpoint Routing. To continue using 'UseMvc', please set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices'"
Everything worked fine after adding <code>services.AddMvc(o => o.EnableEndpointRouting = false)</code> in ConfigureServices in Startup.cs.

### Question
Shouldn't <code>services.AddRazorPages()</code> provide out-of-the-box working support for Api controllers or accept an option config to enable it without the need to <code>UseMvc()</code>?

### What’s in AddRazorPages()
This updates in .NET Core 3.0 blog post by @danroth27 clearly mentions that <code>AddRazorPages()</code> excludes some API-focused feautures:
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/

**Comment by javiercn** [comment]
> Shouldn't `services.AddRazorPages()` provide out-of-the-box working support for Api controllers or accept an option config to enable it without the need to `UseMvc()`?

No, AddRazorPages just adds support for using RazorPages and no controllers. You can call AddControllers and then call app.MapRazorPages() and app.MapControllers() as below

```csharp
app.UseEndpoints(endpoints => 
{
    endpoints.MapRazorPages();
    endpoints.MapControllers();
});
```

**Comment by jomeno** [comment]
Oh perfect! Warning is gone now.
