### ISSUE TITLE
.NET Core 3.0 loggers not working after deployment in Azure

### ISSUE THREAD

**Issue by Masuzu** [aspnet/AspNetCore#14926]
I am running a basic Asp .NET Core application initialized with the default loggers
 ```
public sealed class Program
    {
        public static async Task Main(string[] args)
        {
            var host = BuildWebHost(args);
            await host.RunAsync();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }
```
and `appsettings.json`as follows:
```
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  },
```

The application logs information/warning/error details when run locally while calling `ILogger<MyClass>::LogInformation/Warning/Error`, however, no logs are displayed in the log streams when the application in deployed in Azure:

Below are the Azure configuration settings:
![image](https://user-images.githubusercontent.com/5464705/66664715-f55db080-ec44-11e9-8317-2c01f047ccbf.png)

With .NET Core 2.2 logging was working as intended in Azure. Did something change?

**Comment by davidfowl** [comment]
Did you deploy self contained?

**Comment by Masuzu** [comment]
I did deploy it as self contained indeed

**Comment by davidfowl** [comment]
It's currently being rolled out but the logging extension doesn't automatically work with self contained applications. It's a known gap we're going to need to address. The workaround is to add the dependency on https://www.nuget.org/packages/Microsoft.AspNetCore.AzureAppServicesIntegration/ and add the logger

**Comment by Masuzu** [comment]
Awesome, thank you. Just to make sure, do you mean that on top of adding `AzureAppServicesIntegration`, I would have to override the default loggers explicitly calling/
```
WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .ConfigureLogging(logging =>
        {
            logging.ClearProviders();
            logging.AddConsole();
            ...
        })
       .Build()
```
?

**Comment by davidfowl** [comment]
You don't have to clear. Just add this logger.

**Comment by jkotalik** [comment]
@Masuzu did that resolve your issue?

**Comment by Masuzu** [comment]
@jkotalik Yes it did, all good now.
