### ISSUE TITLE
Blazor missing reference by default

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#14927]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/761990/blazor-missing-reference-by-default.html)._

---
Hello, as you can see on screenshot the Blazor app missing reference by default, and resharper tell me to add reference.

---
#### Visual Studio Feedback System on 10/6/2019, 09:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/11/2019, 01:10 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
#### ice19942335 solved on 10/6/2019, 02:01 AM, 0 votes: 

<p>Add line in _Imports.razor</p><p>@using Microsoft.AspNetCore.Components</p>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The suggested `using` directive is already included in the `_Imports.razor` in the default template.
If you've manually created a razor component and your project doesn't contain _Imports.razor (the one the default templates comes with) - simply add it.
