### ISSUE TITLE
Blazor Authorize attribute and role claims in array format

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#14930]
## Describe the bug

The `System.IdentityModel.Tokens.Jwt` package (version 5.5.0) is used in my asp.net core web api, to produce a JWT token from a `ClaimsIdentity`  - which is then returned to my client blazor wasm application.

The issue, is that the `ClaimsIdentity` has multiple role claims added to it, and `JwtSecurityTokenHandler` seems to produce a `JWT` token that condenses those multiple role claims, into a single role claim, that has a string array value of the role names. I believe this must be an optimisation to decrease the payload size.

For example, when this JWT is decoded on the client side, rather than having these individual role claims:

```
http://schemas.microsoft.com/ws/2008/06/identity/claims/role: "Platform Administrator"
http://schemas.microsoft.com/ws/2008/06/identity/claims/role: "Administrator"
```

It has a single role claim, containing an array for all of the roles:

```
http://schemas.microsoft.com/ws/2008/06/identity/claims/role: ["Platform Administrator","Administrator"]: 
```

Having deserialised the this singular role claim, and then constructed a ClaimsPrincipal to perform the login on my blazor wasm client, it leads to the following problem. In Blazor you can add an `Authorize` attribute to a page, and specify roles:

```
@attribute [Authorize(Roles="Admin")]
```

However the `Authorize` attribute mechanism always fails in this case, as the Role claim is an array of role values. It expects individual role claims of ClaimValueType= string not array.

Of course, now that I have spent a lot of time debugging this issue the fix seems trivial - I can modify the way I deserialise the JWT, to transform the singular role claim into seperate claims. But I first had to experience this pain, and so might anyone else who attempts to use JWT so this seems like its something that should be addressed in the framework.

I'm not sure whether my issue should be considered a bug or a feature request, but the desire is that a JWT produced by `System.IdentityModel.Tokens.Jwt` and sent to a blazor wasm client, should be able to be consumed from blazor's authorization model. Perhaps the Authorize check could be extended to cater for a role claim that is an array of role name values? Or a helper package can be provided to deserialise JWT's in a way that transforms claims into the necessary format required by blazor.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.0' and latest blazor wasm project.
2. In the blazor.wasm project, create an `AuthenticationStateProvider` and have it return a ClaimsPrincipal that is constructed with these claims:

```
 var claims = new Claim[]
        {
        new Claim(ClaimTypes.Name, "Test User"),
        new Claim(ClaimTypes.Role, "[\"Admin\",\"Test\"]", "Array"), 
       //  new Claim(ClaimTypes.Role, "Admin"),
      };
```
Notice I have commented the bottom line for now.
2. Add an `@attribute [Authorize(Roles="Admin")]` to a page. Navigate to it, authoziation will fail.
3. Uncomment that line above, navigate to the page again - authorization succeeds.

### Expected behavior
As above, I expect that a JWT produced on the server by `System.IdentityModel.Tokens.Jwt` and deserialised on a blazor wasm client to a list of its claims, should work with blazor's authorization model. If claims need to be first transformed (i.e from a single claim containing an array of values back into multiple claims) then there should be a helper library to provide this compatibility on the client.  

### Additional context
Include the output of `dotnet --info`

**Comment by javiercn** [comment]
@dazinator thanks for contacting us.

I understand your pain, working with claims is not the easiest thing in the world. Unfortunately, we can't do anything at the framework level, we want to be consistent with the current server-side behavior and as you already mentioned, this is an issue with the way you are deserializing the token on the client-side.

I'm not sure how you are doing that, (are you using JwtSecurityTokenHandler to deserialize and validate the token or are you simply parsing the JSON payload? I believe JwtSecurityTokenHandler will do that array -> multiple claims transformation for you).

If we were to build something like this it would be troublesome as we would have to add additional data to the authorize attribute to account for example for the roles separator in the array claim. It is also important to understand that there is no defined format for representing roles in a JWT, so we don't plan to include support for this scenario out of the box.

On the server we would recommend you simply handle this with a claims transformer (if not done automatically) to transform the roles claim into a list of claims.
