### ISSUE TITLE
In a Blazor Server app Provide user feedback when an unhandled exception happens on the server

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#14938]
In a Blazor Server app if an unhandled exception happens on the server there is no user feedback other than a generic error message in the browser console:

```
Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions in 'CircuitOptions.DetailedErrors'. 
```

Typically if the app loses its connection with the server we display a default UI that lets the user know the connection was lost. If the server state is no longer available we tell the user to refresh the browser. Can we do something similar when an unhandled exception brings down the circuit? Can we provide a way to customize the UI when an unhandled exception happens?

When running in Development, the developer console should also provide the details about the exception instead of giving a generic error message.

**Comment by javiercn** [comment]
@danroth27 Isn't this fixed? @ryanbrandenburg did a thing for this and detailed errors are turned on by default. Is there anything else here? if not please close :)

**Comment by javiercn** [comment]
Actually, closing :)
