### ISSUE TITLE
Not Building a Release

### ISSUE THREAD

**Issue by Gobbeldygook** [aspnet/AspNetCore#14939]
For this SignalR3.0 .NET Core Tutorial, I am getting an 

"Insufficient number of arguments or no entry found." This is followed by 
"ERROR in Entry module not found: Error: Can't resolve ./src in [Solution Root Dir]. 

This makes no sense, because per the directions it is under the inner project directory as stated in the instructions. I assume that it goes [Solution Directory]\[Project Directory], & I am doing the release under the inner project directory. so there should not be a problem. The 'src' directory exists under that Project Directory & not the Solution Directory.  It does build from the Build pull-down on the top-menu ribbon, but will not do a 'npm run release' under the ProjectDirectory, & fails with above said error. My node.js is 10.16.3. I'm using VS Community 2019. I have the ASP.NET Core/.NET Core/ASP.NET Core 3.0.100.

**Comment by jkotalik** [comment]
@Gobbeldygook thanks for the issue. Can you link us to the tutorial you are trying to follow and the line it is failing at such that we can get a repro? I'm a bit uncertain which doc you are following?

**Comment by Gobbeldygook** [comment]
Hi,
It was the .Net Core 3.0 Tutorial for SignalR. One thing for sure missing from it is the @types/node. I'm still trying to do it again, but I have tons of "fires" at work.
Thanks, Bill Shurtleff

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 13, 2019 at 9:57 PM, Justin Kotalik<notifications@github.com> wrote:   
@Gobbeldygook thanks for the issue. Can you link us to the tutorial you are trying to follow and the line it is failing at such that we can get a repro? I'm a bit uncertain which doc you are following?

**Comment by anurse** [comment]
Can you post a runnable sample that reproduces the problem?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
