### ISSUE TITLE
GNU Gettext support

### ISSUE THREAD

**Issue by jdescelliers** [aspnet/AspNetCore#14947]
### Is your feature request related to a problem? Please describe.
Please add buit-in support for GNU Gettext on ASP .Net Core or .Net Core framework itself so it doesn't require any external dependencies.

### Describe the solution you'd like
Built-in implementation of GNU Gettext that can be used anywhere easily within a given codebase. `__("This is a translation")`, so that translations can be used transparently from with an app or test code, Ruby on Rails has a very short syntax to do that, either `t("some.translation.key")` or `I18n.t("some.key")`

### Additional context
The documentation uses Onchard library that while being functional, is an external dependency.

**Comment by javiercn** [comment]
@jdescelliers Thanks for contacting us.

We'll consider this feature during the next release planning period and update the status of this issue accordingly.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jdescelliers.
This is not something we plan to support. We recommend customers to use third-party packages for this purpose.
