### ISSUE TITLE
Saving state on the server Blazor Server app

### ISSUE THREAD

**Issue by mtranchi** [aspnet/AspNetCore#14940]
i reckon you guys know what you're doing light-years ahead of me, and believe me, i know how overwhelming code can be.
But i'm wondering, why on earth would you store State on the server in a Blazor Server app?
Couldn't you have pushed State down to the client in a JSON object? Why stress my server, why risk phones going into tunnels and whatnot?
Again, i'm not the brightest fella, will reckon pushing State down to the client with JSON via SignalR is somehow too complicated?
Love you guys on ASP.NET Community Standup, am always bummed when all three of ya don't show up. There's a chemistry between ya's and it's good. Plus Hanselman over there:  "The 2.2" train? To to!!
I know we're all talking about serious stuff, software that will run on... more than one website :P, but all of ya have occasionally exhibited a bit of ball buster in ya. It's a serious business we're in, personally, a little levity is always appreciated.

**Comment by javiercn** [comment]
@mtranchi Thanks for contacting us.

Pushing the state to the client would add a lot of latency and would significantly increase the bandwidth requirements for running Blazor server-side applications, not to mention other limitations like max message size, etc.

With the state being on the server we preserve bandwidth and offer better latency. You can read more about the topic here.

https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.0
