### ISSUE TITLE
File not Downloading from DB in blazor Using IformFile 

### ISSUE THREAD

**Issue by novfal** [aspnet/AspNetCore#14943]
###
Controller Code
 ** [HttpGet, Route("{requestId:int}")]
    public FileResult Download(int requestId)
    {
      LaborgDbContext laborgDbContext = new LaborgDbContext();
      try
      {
        FileUpload fileUpload = new FileUpload();
        fileUpload = laborgDbContext.FileUpload.Find(requestId);

        if (fileUpload != null)
        {
          
          return File(fileUpload.FileByte, fileUpload.ContentType, fileUpload.DocumentName);
        }
        else
        {
          return null;
        }
      }
      catch (Exception ex)
      {
        throw ex;
      }
    }**

### Describe the bug
File not downloading at the end no exception occur
### To Reproduce
1. Using this version of ASP.NET Core '3'

### Expected behavior
File download from DB

**Comment by javiercn** [comment]
@novfal thanks for contacting us.

In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
