### ISSUE TITLE
Cannot use static resources in Razor Component Library

### ISSUE THREAD

**Issue by moritz-mm** [aspnet/AspNetCore#14946]
CSS and the Image don't get used/displayed.. why???

![1](https://user-images.githubusercontent.com/47302595/66701333-898a4f00-ecfb-11e9-96f6-87f5929ab125.PNG)
![2](https://user-images.githubusercontent.com/47302595/66701334-898a4f00-ecfb-11e9-9c39-6739a3b0f735.PNG)

**Comment by moritz-mm** [comment]
I didn`t include anything in my main project i just created the project with the template and startet coding

**Comment by moritz-mm** [comment]
???

**Comment by javiercn** [comment]
@moritz-mm Thanks for contacting us.

The convention is to use `_content/<<LibraryName>>/<<pathfromwwwroot>>` when referencing static assets from libraries.

You can read about it here https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#create-an-rcl-with-static-assets

Let us know if you have more issues. 

Thanks!

**Comment by mythrz** [comment]
> The convention is to use `_content/<<LibraryName>>/<<pathfromwwwroot>>` 

If you try to reference the RCL static assets in the "site.css" of the **main project** do this instead: ../_content/"LibraryName"/"pathfromwwwroot"
or this to be more precise:
@import url('../_content/"RCLLibraryName"/"path+filename"');
Intellisense is not working yet, so make sure you write this properly.

To check if both projects were properly wired/referenced and have the requirements (Microsoft.AspNetCore.Components), during runtime, you can write this:
https://localhost:"nº"//_content/"RCLLibraryName"/"path+filename"

**NOTE:** Do not write the wwwroot!
