### ISSUE TITLE
Make ApiDescriptionActionData public

### ISSUE THREAD

**Issue by tebeco** [aspnet/AspNetCore#14954]
### Is your feature request related to a problem? Please describe.
I am trying to help migrate Swashbuckle.AspNetCore to cross target `netstandard2.0` (for AspNetCore2.x) and `netcoreapp3.0` (for AspNetCore 3.0) but a part of the IntegrationTest did used `Pubternal Api` (which were removed)

### Describe the solution you'd like
I would love to know if there's somewhere i could take a look at, as a suggestion, in order to replace previous behavior.

### Additional context
Here is the ongoing `Draft` PR :
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1316

I managed to make many Test pass, but 52 are still resisting.
From the error, it seems that the origin could be one of these  :
* [ApiDescriptionActionData => ApiDescription](https://github.com/tebeco/Swashbuckle.AspNetCore/blob/12f10fa285a0375927f1733fc87fe53d92741251/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/Fakes/FakeApiDescriptionGroupCollectionProvider.cs#L80-L85)
* [DefaultModelMetadataProvider => EmptyModelMetadataProvider](https://github.com/tebeco/Swashbuckle.AspNetCore/blob/12f10fa285a0375927f1733fc87fe53d92741251/test/Swashbuckle.AspNetCore.Annotations.Test/ModelMetadataHelper.cs)
* [DefaultModelMetadataProvider => EmptyModelMetadataProvider (again ^^)](https://github.com/tebeco/Swashbuckle.AspNetCore/blob/12f10fa285a0375927f1733fc87fe53d92741251/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/Fakes/FakeApiDescriptionGroupCollectionProvider.cs#L149-L190)
* [IActionResultTypeMapper => ???? no idea what to use here](https://github.com/tebeco/Swashbuckle.AspNetCore/blob/12f10fa285a0375927f1733fc87fe53d92741251/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/Fakes/FakeApiDescriptionGroupCollectionProvider.cs#L154)

If anybody got leads, or a fix, an idea where to look at, to be fair i'm kinda lost on this one

**Comment by javiercn** [comment]
@tebeco Thanks for contacting us.

@pranavkm can you help out here?

**Comment by pranavkm** [comment]
@tebeco, [`DefaultModelMetadataProvider`](https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Mvc/Mvc.Core/src/ModelBinding/Metadata/DefaultModelMetadataProvider.cs)  continues to be public in 3.0, you should be able to using it without changing things. Same goes for `IActionResultTypeMapper`. Could you share the error you see when you try using \ referencing these types?

Unfortunately there isn't a direct replacement for `ApiActionDescriptorData`, `ApiDescription` isn't the correct substitute. I'm going to use this issue to track adding a suitable substitute for it. In the meanwhile, I'd recommend using reflection to unblock the tests. It's a fairly critical piece for Swagger \ ApiExplorer, that one type alone might explain the multitude of errors you're seeing.

**Comment by tebeco** [comment]
As i see that the title changed i am curious, will it land for 3.1 ?
Also to be honest and sure, is there better Apis that `Swashbuckle` could use on `AspNetCore3` in order to run the same integration test ?

**Comment by tebeco** [comment]
so here is the next question regarding, probably another api.
This time there's a public `Empty` one, and i'm pretty sure this is my fault, just looking for idea from devs here since you have waaaay more insight on the proper fix
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1316#issuecomment-542279502

the 5 other remainings test also have related change of behavior around these classes (since they are all hitting the same `Fake` that uses `ApiDescriptionGroupCollection`

**Comment by pranavkm** [comment]
@tebeco I responded to your other issue here: https://github.com/tebeco/Swashbuckle.AspNetCore/pull/1.Do you happen to know why this does not work?

**Comment by pranavkm** [comment]
Closing this. I'll work with you on the PR to figure out what's going on.
