### ISSUE TITLE
Bad responses: DbMultiUpdateEf

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14957]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| DbMultiUpdateEf | Linux, Physical, http, KestrelSockets | 10/10/19 12:50:53 PM +00:00 | 31016 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Updated CentOS
