### ISSUE TITLE
Bad responses: FortunesPostgreSql-Actix

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14961]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| FortunesPostgreSql-Actix | Linux, Physical, http, KestrelSockets | 10/10/19 1:50:48 PM +00:00 | 1014373 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
CentOS update
