### ISSUE TITLE
The list of component records is not valid.

### ISSUE THREAD

**Issue by asdux** [aspnet/AspNetCore#14966]
I use two blazor components in _layout.cshtml as follows, but the components don't work.
```
// _layout.cshtml
@(await Html.RenderComponentAsync<Counter>(RenderMode.ServerPrerendered))
<div class="container body-content pt-3">
    @RenderBody()
</div>
```
```
// Test.cshtml
@page
@model Web.Pages.TestModel
@(await Html.RenderComponentAsync<Counter>(RenderMode.ServerPrerendered))
```
![image](https://user-images.githubusercontent.com/48398443/66717449-c180b780-ee0b-11e9-8d0f-e74bef2ad131.png)

But, It works if the component is used after @RenderBody() as follows.
```
<div class="container body-content pt-3">
    @RenderBody()
</div>
@(await Html.RenderComponentAsync<Counter>(RenderMode.ServerPrerendered))
```

**Comment by javiercn** [comment]
@asdux Thanks for contacting us.

This might be an issue in the way we store the component sequence numbers in the ViewContext. We'll have to check that the data in the ViewContext gets copied properly.

**Comment by pranavkm** [comment]
Closing as dup of https://github.com/aspnet/AspNetCore/issues/14474. We'll use the other issue to track resolving this.
