### ISSUE TITLE
Blazor: No .NET call dispatcher has been set

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/AspNetCore#14965]
### Describe the bug
When creating a Blazor server-side app, it is not possible to call DotNet.invokeMethodAsync from HTML JavaScript.

### To Reproduce
1: Create a new server-side Blazor app called `BlazorApp7`.
2: Add the following class
```
public static class SomeCallback
{
	public static string Status = "Failed";
	[JSInvokable("SayHello")]
	public static void SayHello() => Status = "Called";
}
```
3: Edit Pages/_Host.cshtml, and below `<script src="_framework/blazor.server.js"></script>` add the following script
```
<script>
	(function () {
		if (window.DotNet) {
			console.log("window.DotNet is set");
			if (window.DotNet.invokeMethodAsync) {
				console.log("window.DotNet.invokeMethodAsync is set");
				window.DotNet.invokeMethodAsync("BlazorApp7", "SayHello");
			}
		}
	})();
</script>
```

### Expected behaviour
As `window.DotNet` is not null, I expect the script to successfully execute the C# in the callback.

### Actual behaviour
An exception is thrown "No .NET call dispatcher has been set"

By the time `blazor.server.js` has executed, window.DotNet has been set but using it will cause the above exception.

This is preventing any start-up script from executing C# code.

The only solution to this at the moment is to use setTimeout, but this results in a laggy user experience when starting up the app (100ms delay succeeded, 50ms failed).

This problem happens when RenderMode is either Server or ServerPrerendered.

**Comment by soeleman** [comment]
This issue may be helping #14011

**Comment by javiercn** [comment]
@mrpmorris Thanks for contacting us.

@soeleman Is right. I would follow the same guidance I provided in here. https://github.com/aspnet/AspNetCore/issues/14011#issuecomment-534757093

It is likely Blazor is not yet fully initialized when you try to call into .NET. Instead of doing what you are doing, check the snippet for manually initializing Blazor.

It returns a promise, so you can chain a `then` call after it and perform the interop call at the time.

```razor
<script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        function start() {
            Blazor.start({ })
                .then(() => {...});
        }
    </script>
```

If that doesn't help, feel free to reopen this issue.

**Comment by mrpmorris** [comment]
@javiercn 

I have this
```
	<script src="~/index.js"></script>
	<script src="_framework/blazor.server.js" autostart="false"></script>
```

and in index.js I have this
```
alert('x');
if (window.Blazor) {
	alert('1');
	window.Blazor.start({})
		.then(() => { alert('z'); });
}
alert('y');
```

I only see alerts X and Y.
