### ISSUE TITLE
Add a way to completely disable framework's console output

### ISSUE THREAD

**Issue by hlubovac** [aspnet/AspNetCore#14960]
I would prefer if there is nothing printed out in the console. I tried few things that worked with previous versions, but to no avail. Please provide a way. Thank you.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

</Project>
```

![image](https://user-images.githubusercontent.com/3127736/66710218-d7697c00-ed28-11e9-850e-acaed0481e74.png)

**Comment by BrennanConroy** [comment]
Have you tried clearing the logging providers?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#add-providers

**Comment by hlubovac** [comment]
Thank you very much; that worked. I could swear that I saw this earlier and I somehow imagined it was for a previous version of dotnet. I had to add this package to make this compile:

<PackageReference Include="Microsoft.Extensions.Logging" Version="3.0.0" />
