### ISSUE TITLE
Embedded razor component work on /sub1 but not /sub1/index

### ISSUE THREAD

**Issue by pekspro** [aspnet/AspNetCore#14963]
On a razor page I have added a simple razor component with this code:

    @(await Html.RenderComponentAsync<Components.TestComponent>(RenderMode.ServerPrerendered))

The razor page is in subfolder named Sub1 with the file name Index. All the razor component do is to change a text after two seconds.

If I open the page in the browser with the URL https://localhost:44307/sub1 it works as expected. But if I instead use https://localhost:44307/sub1/index the text is never changed on the razor component. 

I have also added the same component on the index page on the root folder with the result that both https://localhost:44307/ and https://localhost:44307/index works but not https://localhost:44307/index/. The last URL is a bit strange, but everything else works when I’m debugging, but nothing works when I run this is Azure.

Here is a live demo: https://razorcomponenturltest20191013013624.azurewebsites.net/
Here is my test project: https://github.com/pekspro/RazorComponentUrlIssue

**Comment by soeleman** [comment]
Try add __tag base__.
![LayoutBase](https://user-images.githubusercontent.com/309413/66727731-4222d080-ee6b-11e9-99e2-d5d0c3fe89d1.png)

Testing with fall testing urls.
![SampleRun](https://user-images.githubusercontent.com/309413/66727760-67174380-ee6b-11e9-9078-fba3598e5fb4.png)

**Comment by pekspro** [comment]
Thank you @soeleman and @javiercn! I didn't even know that the base tag existed.
