### ISSUE TITLE
Define a deconstructor for the ActionResult<T> class

### ISSUE THREAD

**Issue by ofirgeller** [aspnet/AspNetCore#14967]
If ActionResult<T> (which is similar to an "Either<TValue,ActionResult>")  had a deconstructor that would make handling it (ex: pattern matching) easier.

### Describe the solution you'd like
`
   public void Deconstruct(out TValue value, out ActionResult result)
        {
            value = Value;
            result = Result;
        }
`
I can't do it myself since the class is sealed.

**Comment by davidfowl** [comment]
What’s the scenario? Unit testing?

**Comment by ofirgeller** [comment]
That would be one use case, but the one I run into more is one controller action calling another.
I like to let ActionResults that indicate errors be returned right away, and in cases of success do something with the value.

**Comment by davidfowl** [comment]
Oh that’s more rare as controllers are called by the framework not by users

**Comment by ofirgeller** [comment]
Yes, it is more rare, but I find value in doing it, should I advocate with examples?

**Comment by javiercn** [comment]
@ofirgeller Thanks for contacting us.

We don't recommend that you call controller methods from other controller methods, as there are many things in the ambient context that are not setup correctly in that case.

Our recommendation is that if you need to do something like that, you factor the common code into a shared method that all controller actions can call into.

**Comment by ofirgeller** [comment]
@javiercn @davidfowl , thank you guys for all the great work and for getting back to me.

I tried coming up with a case where the problem you bring up would be solved by factoring out the code but I can't. If the shared code uses the controller "Request.Method" property for example, that would still be set according to the method the framework invoked. which is what I would expect and consider the correct setup.

Can you please give me an example?

**Comment by mkArtakMSFT** [comment]
Closing as there is no action we plan to take from here.

**Comment by mkArtakMSFT** [comment]
@ofirgeller for your last question we recommend using `StackOverflow`.

**Comment by ofirgeller** [comment]
Even if I were to factor out the code into a shared method in order to avoid having one action call another, I would still like to return an Action<T> from that shared code. So my original requests stands and I thank you all for trying to understand. 

All the best.
