### ISSUE TITLE
`dotnet publish` produces executable specific to OS it's executed on

### ISSUE THREAD

**Issue by hlubovac** [aspnet/AspNetCore#14974]
I noticed that Windows hosting the `dotnet publish` gets an EXE file, while Linux (Ubuntu) gets an extensionless executable file named by the assembly. Under assumption that produced DLL and json-config files are actually exactly the same (regardless of where this process executes), shouldn't the process produce entrypoint binaries for all supported operating systems [at the same time]? Maybe I'm not noticing that the behavior that I'm after is actually present? The behavior that I'm noticing might complicate the build-process in certain scenarios. I just wanted to bring it to your attention. Thanks.

**Comment by davidfowl** [comment]
That's by design, executables are platform specific. The cross platform version of the binary is the .dll file which you can execute with `dotnet MyApp.dll`.

**Comment by hlubovac** [comment]
Thank you.

But then, what is their purpose - since the application is launched primarily as `dotnet [path-to-main-assembly]`?

While I do understand that these executables cannot be the same [for all platforms], I still think that the `dotnet build` should produce them all - or not produce any (since they are aliases, anyway). If they are there for some double-clicking convenience or some other purpose that I'm not seeing, then people that rely on them must compile their apps on multile platforms (the same number of times) - if they rely on having that convenience. Perhaps it's technically impossible for any supported platform to produce executables for other platforms, which I wouldn't know...

**Comment by davidfowl** [comment]
> But then, what is their purpose - since the application is launched primarily as dotnet [path-to-main-assembly]?

- Easy way to launch (double click)
- A way to distinguish processes when using (ps or task manager on windows)

> While I do understand that these executables cannot be the same [for all platforms], I still think that the dotnet build should produce them all - or not produce any (since they are aliases, anyway). If they are there for some double-clicking convenience or some other purpose that I'm not seeing, then people that rely on them must compile their apps on multile platforms (the same number of times) - if they rely on having that convenience. Perhaps it's technically impossible for any supported platform to produce executables for other platforms, which I wouldn't know...

I don't agree. That would be too much bloat, add to my build time and isn't the majority use case. Instead, you can pass the required RIDs you care about to get the executables for those platforms.

**Comment by hlubovac** [comment]
I see. You're likely referring to `--runtime` argument, which I didn't have a chance to learn about [until now]. Thank you. I'll read up on RID's.

**Comment by hlubovac** [comment]
Maybe a way to disable producing runtime-specific executables would be nice. :-)

I tried passing empty/null/false to `--runtime`, hoping to achieve this. It's not a big deal - just more confusing [to me] then without. There is `--self-contained` that relates also (which needs to be set to false, looks like, when `--runtime` is used to achieve equivalents to the default behavior described above, cross-platform).
