### ISSUE TITLE
BrowserHttpMessageHandler is using Json.Serialize

### ISSUE THREAD

**Issue by TJoshua** [aspnet/AspNetCore#14973]
### Describe the bug
BrowserHttpMessageHandler is still using the json helpers from Microsoft.JSInterop (Json.Serialize, Json.Deserialize). 

According to, https://github.com/aspnet/AspNetCore/issues/10810
It appears that the serialization must be updated to use something else. It suggests using the stuff in the System.Text.Json.Serialization namespace.

This causes an issue during runtime:
Could not load type 'Microsoft.JSInterop.Json' from assembly 'Microsoft.JSInterop, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

### To Reproduce
1. Using this version of ASP.NET Core '3'
2. Run this code 'new HttpClient(new BrowserHttpMessageHandler()).PostAsync(...)'
3. With these arguments '(any)'

### Expected behavior
No exception to be thrown

### Additional context
Include the output of `dotnet --info`

**Comment by jkotalik** [comment]
@pranavkm ?

**Comment by javiercn** [comment]
@TJoshua Thanks for contacting us.

I believe this was already addressed. What version are you using?

**Comment by TJoshua** [comment]
Here's the version info from my csproj file:
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview9.19465.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Browser" Version="0.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Browser.JS" Version="0.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.JSInterop" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
  </ItemGroup>
</Project>`

**Comment by pranavkm** [comment]
@TJoshua some of these packages look fairly old:

> `<PackageReference Include="Microsoft.AspNetCore.Blazor.Browser" Version="0.7.0" />`
> `<PackageReference Include="Microsoft.AspNetCore.Blazor.Browser.JS" Version="0.5.1" />`

The SqlServer package also makes little sense in a Blazor WASM project. I'd recommend trying to [creating an empty Blazor WASM project](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio) and having a look at what it references.

**Comment by TJoshua** [comment]
I see the issue. I was using Blazor Server, which doesn't appear to use BrowserHttpMessageHandler for HttpClient

**Comment by javiercn** [comment]
Closing as there’s no more action to be taken here.
