### ISSUE TITLE
SignalR clients cannot connect to SignalR server. Gets "SignalR Service is now in 'Default' service mode. Current mode works as a proxy that routes client traffic to the connected app servers. However app servers are not connected."

### ISSUE THREAD

**Issue by mibjg** [aspnet/AspNetCore#14979]
### Describe the bug
When we connect to SignalR through our app-service (We have exposed an endpoint with the SignalR Management SDK, which returns a url and accessToken to the Azure SignalR service)

       [HttpPost("{hub}/negotiate")]
        public ActionResult Index(string hub)
        {
            return new JsonResult(new Dictionary<string, string>()
            {
                {"url", _serviceManager.GetClientEndpoint(hub)},
                {"accessToken", _serviceManager.GenerateClientAccessToken(hub, User.ToString())}
            });
        }

This seems to work Ok, when we connect the client through here, the client receives the token, and calls the negotiate endpoint on the Azure SignalR service.

However when the client tries to switch to Websockets, we get the following message: 

`SignalR Service is now in 'Default' service mode. Current mode works as a proxy that routes client traffic to the connected app servers. However app servers are not connected`

This is even though we can see that servers are connected to the SignalR service

![image](https://user-images.githubusercontent.com/56539680/66744328-70f57280-ee7c-11e9-8127-30dd29528577.png)

The client is an Angular 7 app using the "@microsoft/signalr": "^3.0.0" npm package

### Expected behavior
Expected the client to connect to the SignalR server.

**Comment by BrennanConroy** [comment]
Why are you explicitly exposing a "{hub}/negotiate" endpoint and handcrafting the response?

Normally when you want to connect a client to your app server through the SignalR Service you use the `AddAzureSignalR` and `UseAzureSignalR` methods which will handle all of the tokens and redirect urls for you.

See the docs: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-dotnet-core

**Comment by mibjg** [comment]
The reason for the explicit negotiate is that we want to ensure that our users are logged in to get the signalR token

**Comment by BrennanConroy** [comment]
You should be able to do this by putting an [`[Authorize]` attribute](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.0#authorize-users-to-access-hubs-and-hub-methods) on your hub class(es) or if you're using Endpoint Routing, use `RequireAuthorization(...)` on your hub mapping.

```c#
app.UseEndpoints(endpoints =>
{
    endpoints.MapHub<Chat>("/chat").RequireAuthorization("policy");
});
```

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
