### ISSUE TITLE
Blazer: The lifecycle function in the page is activated twice on OnInitializedAsync

### ISSUE THREAD

**Issue by AutismPatient** [aspnet/AspNetCore#14977]
**I want to know why it activated twice to execute the twice load method, which confused me, I was using the official template code!**
`protected override async Task OnInitializedAsync()
    {
        forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
    }
`

**Comment by Postlagerkarte** [comment]
The behavior you're seeing is by-design. OnInitializedAsync is called once during pre-rendering and once during the rendering.

**Comment by AutismPatient** [comment]
I put a load mask on the page so that when I refresh the page, the mask doesn't appear for the first time, the data flashes before it appears, and I'm sure my logic is correct

**Comment by javiercn** [comment]
@AutismPatient Thanks for contacting us.

@Postlagerkarte answer is correct.

* Prerendering creates the component and produces an initial render that gets serialized into HTML.
* After that, the app gets bootstrapped from the client and produces one or more renders in case there's async work:
  * One render after the synchronous work in OnInitializeAsync is done.
  * One render after the asynchronous work in OnInitializeAsync is completed. 

That's likely why you see the data flashing. Prerendering waits until the async work is done before producing HTML to produce a meaninful result.
