### ISSUE TITLE
You cannot have Async after the action name-core3.0

### ISSUE THREAD

**Issue by ghd258** [aspnet/AspNetCore#14978]
There can be no Async after the action name if my action name is GetMenuByUserIdAsync and the actual route generated by GetMenuByUserId automatically removes the Async

**Comment by khellang** [comment]
This is an [announced breaking change](https://github.com/aspnet/Announcements/issues/351). It's also mentioned in the [migration guide from 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#async-suffix-removal-from-controller-action-names).

**Comment by javiercn** [comment]
@ghd258 Thanks for contacting us.

@khellang is right about the change.

Closing the issue as the behavior is by design.
