### ISSUE TITLE
Disable Session cookie key encryption

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14989]
_From @audriuiv on Monday, October 14, 2019 1:02:44 PM_

In my domain I have two subdomains. In the first subdomain is Nodejs app, in the second - will be .Net Core app.
Nodejs app with Passportjs, express-session modules authenticates users. Express-session creates singed cookie like 'sessionid.hash'.  A Session cache - MongoDb. If a cookie was founded .Net Core app has automatically login. Now it working, but it encrypts founded cookie key. When an user want to return to Nodejs app, he can't. Because Nodejs does not recognise encrypted key.  
I read about IDataProtector, but I don't understand how I can disable session key encryption?

Startup.cs
```
 services.AddSession(o =>
            {
                o.Cookie.Name = "my_session";
                o.Cookie.Path = "/";
                o.Cookie.IsEssential = true;
            });
            services.AddSingleton<ISessionStore, AppDistributedSessionStore>();
```

_Copied from original issue: dotnet/core#3617_

**Comment by blowdart** [comment]
You can't. We encrypt and sign it to avoid session hijacking. We don't have the ability to turn it off.

**Comment by audriuiv** [comment]
Thanks, I got it. Closed.
