### ISSUE TITLE
File Upload and Download

### ISSUE THREAD

**Issue by novfal** [aspnet/AspNetCore#14981]
### File Upload and Download not performing in Blazor

**Comment by javiercn** [comment]
@novfal Thanks for contacting us.

We are not sure what you are referring to. Blazor doesn't offer an upload or download feature. The closest thing is an experimental package @SteveSandersonMS published and that you can read about here https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/ and that is not part of ASP.NET Core.

Hope that helps.
