### ISSUE TITLE
Version 3.0 : Why not close

### ISSUE THREAD

**Issue by boukenka** [aspnet/AspNetCore#14987]
Hello,

I am following the different releases of ASP .NET CORE, especially on the Blazor side.
I can see the different milestones. Why is section 3.0.0 not closed and completed?
Is there a particular reason? There has already been an official version for version 3.0.

Thanks for any answer.

**Comment by Pilchie** [comment]
@mkArtakMSFT - you usually do this?  Any reason not to this time?

**Comment by danroth27** [comment]
The 3.0.0 milestone is now closed.
