### ISSUE TITLE
get IMvcBuilder from AssemblyLoadContext

### ISSUE THREAD

**Issue by j4587698** [aspnet/AspNetCore#14980]
Is there any way to get IMvcBuilder from AssemblyLoadContext ? I want to make a plugin system like Wordpress. When the plugin is enabled, I can automatically add my own page to the menu.
Is there any way to solve this problem or has another way to add Add or remove controllers outside of ConfigureServices?

**Comment by javiercn** [comment]
@j4587698 thanks for contacting us.

I'm not sure that's the best way to achieve what you want. Before you implement your own solution I would recommend you look into Orchard core, which has a bunch of facilities like these that can be used to build modular apps like the one it seems you are trying to build.
