### ISSUE TITLE
Startup Authentication with OpenId Connect not compatible with IdentityServer3

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14990]
_From @rcreynolds53 on Monday, October 14, 2019 5:01:19 PM_

When trying to update a project from .NET Core 2.2 to 3.0, the authentication that take place in the configure services method of the startup will not work with Identity Server 3. but will work with Identity Server 4. 
When pointing to our IdentityServer3, the OnTokenValidated never gets hit, additionally the following exception is thrown.

![IdentitySErver3](https://user-images.githubusercontent.com/26964362/66769248-3be82080-ee7a-11e9-9463-68abfbcb1965.PNG)

Is IdentityServer3 supported in .NET Core 3.0? 

_Copied from original issue: dotnet/core#3618_

**Comment by rcreynolds53** [comment]
It look like PR #10928 Add PKCE support in OIDC & OAuth set UsePkce to true by default, even though the flow for the response type is being set to 'code' I had to set the UsePkce property to false in order to get it to work properly.

**Comment by blowdart** [comment]
@Tratcher

**Comment by Tratcher** [comment]
https://github.com/aspnet/AspNetCore/pull/10928/files#diff-77dbc837ce88da9bcf6a630ae8969190R371
@brockallen?

**Comment by rcreynolds53** [comment]
Is this something that I can do a PR on?

**Comment by Tratcher** [comment]
@rcreynolds53 we haven't identified if there's anything wrong in AspNetCore yet.

**Comment by rcreynolds53** [comment]
@Tratcher okay thanks. For now my work around is having to set UsePkce to false even with the response type as `OpenIdConnectResponseType.Code`

**Comment by anurse** [comment]
Closing as we don't intend to take action here. Updating to IdentityServer4 is the recommended approach to using our defaults in 3.0. If you cannot update to IS4, then you'll have to disable `UsePkce`.

**Comment by brockallen** [comment]
Sorry -- I just saw this thread. PKCE is supported in IS3, you just need to enable it for that client (or disable it here in this library).

**Comment by anurse** [comment]
> PKCE is supported in IS3, you just need to enable it for that client

Ah excellent, sorry for misrepresenting you there 😄. Thanks for clarifying!
