### ISSUE TITLE
Razor Class Library Static Assets with spaces do not resolve.

### ISSUE THREAD

**Issue by gregfig** [aspnet/AspNetCore#14999]
If any files (images for example) contain a space.  When they are coded with %20 they are not resolved.

To reproduce.
   1.  Create a RCL with a wwwroot folder.
   2.  Add one image file without a space, Add one image file with a space.
   3.  Create a Web App and reference the RCL
   4.  Run the app.

In my test app.  https://localhost:44362/_content/RclTestCore3/MoneyBag.png resolves just fine.

However, https://localhost:44362/_content/RclTestCore3/Piggy Bank.png, which gets encoded as https://localhost:44362/_content/RclTestCore3/Piggy%20Bank.png, will return a 404 error.

I can workaround this by removing the spaces, but I happen to have a lot of images with spaces in their filenames.

Thanks

**Comment by javiercn** [comment]
@gregfig Thanks for contacting us.

I can repro this. We'll take a look at it.

**Comment by javiercn** [comment]
This is a 3.1 candidate
