### ISSUE TITLE
Creating anonymous object starting with @class creates compiler error

### ISSUE THREAD

**Issue by fehrm** [aspnet/AspNetCore#15004]
### Describe the bug
In a Razor page, creating an anonymous object (eg. for HtmlAttributes) starting with @class inside a @{} block creates these compiler errors

> **(void?):** class" is a reserved word and cannot be used in implicit expressions.  An explicit expression ("@()") must be used

and 

> **CS0746:** Invalid anonymous type member declarator. Anonymous type members must be declared with a member assignment, simple name or member access.

and 

> **CS1525:** Invalid expression term '='
![image](https://user-images.githubusercontent.com/8399245/66811395-4b767080-ef31-11e9-9026-7037a95a9205.png)

### To Reproduce
1. Using Razor in a ASP.NET Core 3.0 project
2. In Startup.cs, add `services.AddRazorPages().AddRazorRuntimeCompilation();`
3. Create a cshtml view

#### Code that creates error
`@{
    var htmlAttributes = new { @class = "form-control" };
}` 

#### Working code
`@{
    var htmlAttributes = new { foo = "bar", @class = "form-control" };
}`

**Comment by soeleman** [comment]
You can use double **@@**
![PreserveNameRazor](https://user-images.githubusercontent.com/309413/66813259-a4a8c900-ef5e-11e9-9683-5b64deb25ad3.png)

**Comment by javiercn** [comment]
@fehrm Thanks for contacting us.

@NTaylorMullen The double `@@` shouldn't be necessary as you are already inside a c# context, am I wrong? Otherwise @soeleman answer is correct.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @fehrm.
While this is a bug, it's super low pirority and we won't spend time fixing it, as the workaround is to simply use `@@` per @soeleman's suggestion.
