### ISSUE TITLE
jwt auth doesn't work on signalr js client

### ISSUE THREAD

**Issue by neville-nazerane** [aspnet/AspNetCore#15008]
I have a signalr server setup on 2.2 and type script using @microsoft/signalr. I am using the following straight out of the documentation:

        this.connection = new signalR.HubConnectionBuilder()
                              .withAutomaticReconnect()
                              .withUrl(myFullUrl + '/myHub', {
                                  accessTokenFactory: () => {
                                      console.log(this.auth.getAccessToken());
                                      return this.auth.getAccessToken();
                                  }
                              })
                              .build();

When I run the above code as it is, i get a 200 in the /negotiate end point. However get a 401 in the _wss://url/myhub?id=xyz&access_token=jwt_ endpoint. 

I have tried the following: 

1. I ran the same code on c# with a hard coded token from the console.log. **It works fine**. I have tried multiple on and invoke functions

2. I commented out the `[Authroize]` on the server side from myHub. Everything now **works fine** on type script with on and invokes. 

3. I undid the **2.** and commented out `return this.auth.getAccessToken();` from type script. I now get a 401 in the /negotiate, which is **expected behavior**. This means the above code does authorize. 

Additional info: 
Server runs on azure windows web apps and all the above are tried with and without azure signalr.

**Comment by BrennanConroy** [comment]
Have you taken a look at the Auth section of our docs? https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.0#bearer-token-authentication

Specifically the part where you need to read the "access_token" query string value and put that on the `context.Token` property.

In C# we can use headers for auth which is pulled in automatically by the auth system. But in the browser we are more limited in what we can do, so in some cases we have to put the token in the query string, which requires some manual work on the server side.

**Comment by neville-nazerane** [comment]
It works fine now, Thanks!
I had missed that part.
