### ISSUE TITLE
Is there an issue with unpkg deployment for signalr?

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore#15003]
### Describe the bug
A couple weeks back i installed signalR on a demo app which worked - however now when trying to do so it appears that installing no longer properly works. I've followed the official docs in both cases and reported it as VS bug as well, but even when going to unpkg.com (to bypass the VS issue) it appears that there is no aspnet/signalr package present.

https://docs.microsoft.com/de-de/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&tabs=visual-studio

### To Reproduce
1. try installing signalR javascript client through VS
2. try locating the package on https://unpkg.com/browse/aspnet (works for react: https://unpkg.com/browse/react)

### Expected behavior
I would expect this to be available on unpkg.com, but it appears that it isn't anymore.

**Comment by soeleman** [comment]
Maybe you can take a look on English version. It is difference and seem up to date.
![ClientLibraryUnpkgSignalrDocEn](https://user-images.githubusercontent.com/309413/66799658-2fc49780-ef3c-11e9-843f-b767ba7c46a1.png)

and this of add-client-library
![ClientLibraryUnpkgSignalr](https://user-images.githubusercontent.com/309413/66799681-4c60cf80-ef3c-11e9-9a1a-7ac4887df283.png)

**Comment by taori** [comment]
Thanks. Pretty odd that the images are different. But nice find. I'll have a look if it works

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by taori** [comment]
@soeleman You're right. The english reference makes it work just fine. i've suggested a docs update already. Thanks
