### ISSUE TITLE
Environment=ASPNETCORE_URLS=http://localhost:5001 - Not working

### ISSUE THREAD

**Issue by justlearntutors** [aspnet/AspNetCore#15011]
Environment=ASPNETCORE_URLS=http://localhost:5001
It is not working for ASP.NET CORE 3.0 on Linux. How to fix?

**Comment by javiercn** [comment]
@justlearntutors Thanks for contacting us.

Can you provide more details on what you are doing? 
Are you on plain Linux or inside a container?
Are you running the app with `dotnet run`? Check that you don't have a launchSettings.json file under /Properties if that's the case. It will override the ASPNETCORE_URLS environment variable.

@Tratcher can you assist here?

**Comment by justlearntutors** [comment]
Can you provide more details on what you are doing?
Running 2 websites on Linux Ubuntu 18

Are you on plain Linux or inside a container?
Plain Linux

Are you running the app with dotnet run?
No, we use .service file

Check that you don't have a launchSettings.json file under /Properties if that's the case. It will override the ASPNETCORE_URLS environment variable.
We have launchSettings.json file under /Properties.
"applicationUrl": "http://localhost:5001;http://localhost:5000",

**Comment by Tratcher** [comment]
`Environment=ASPNETCORE_URLS=http://localhost:5001` is invalid input, where did you see that?
The environment variables should be:
`ASPNETCORE_ENVIRONMENT=Development`
`ASPNETCORE_URLS=http://localhost:5000`

Also, why did you change port 5001 from https to http? If you don't plan to use https then remove the 5001 entry and use 5000 instead.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by skynet2** [comment]
Hi @Tratcher ,
That's how you can specify environment variables in systemd service definition.
Example configuration is 
```

    [Unit]
    Description=eventpublisher service
    After=network.target
    [Service]
    WorkingDirectory=/home/0.0.0.24
    User=build-integration
    Group=build-integration
    ExecStart=/home/0.0.0.24/Events.Api
    Restart=always
    RestartSec=10
    SyslogIdentifier=eventpublisher
    Environment=ASPNETCORE_ENVIRONMENT=qa
    Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
    Environment=ASPNETCORE_URLS=http://0.0.0.0:55471
    [Install]
    WantedBy=multi-user.target
```
The issue is that starting from NetCore 3.0 ASPNETCORE_URLS under linux are not picked up atumatically, and webservice always tries to start under localhost:5000
I have the same issue. Exactly same configuration, but for 2.1 works good.

Thanks,
Stas

**Comment by skynet2** [comment]
Update. Using NetCore 3.0 
Don't pickup ASPNETCORE_URLS : 
```
    public class Program
    {
        public static void Main(string[] args)
        {
             CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
```
Works
```    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }

**Comment by Tratcher** [comment]
That's interesting because the config is handled similarly between them.

First we need to confirm if the environment variables were never picked up or if they were overwritten by something else. Try this:
```
        public static void Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();

            var config = host.Services.GetRequiredService<IConfiguration>();

            foreach (var c in config.AsEnumerable())
            {
                Console.WriteLine(c.Key + " = " + c.Value);
            }
        }
```
You should get both "URLS" and "ASPNETCORE_URLS" with the same value. Similarly for ENVIRONMENT.

**Comment by skynet2** [comment]
Hi @Tratcher ,

I can reproduce that locally on my dev environment (Ubuntu 19)

![image](https://user-images.githubusercontent.com/3065048/68320108-0aa0f000-00c8-11ea-8c44-ea77b9684138.png)
But apphost still runs on localhost:5000

**Comment by skynet2** [comment]
I`ve also checked. I don't have any variables like "urls".
![image](https://user-images.githubusercontent.com/3065048/68320396-8dc24600-00c8-11ea-8f92-6dd73cee9d90.png)

**Comment by Tratcher** [comment]
If "ASPNETCORE_URLS" isn't being trimmed to "URLS" then your config setup has been replaced. Are you building a config in Startup?

(Text, not screen shots please).

**Comment by skynet2** [comment]
Hi @Tratcher ,
Yep, i have logic which builds IConfiguration from IConfigurationBuilder in my startup pipeline.

Thanks,
Stas

**Comment by Tratcher** [comment]
And then puts it into DI? That would explain the issue, you're replacing the host config. One change from 2.x to 3.0 is that the host resolves IConfiguration from DI. The recommendation if you want to modify config is to do it in Program.CreateHostBuilder by calling ConfigureAppConfiguration. That appends to the default config rather than replacing it.

**Comment by skynet2** [comment]
Yes, then i put it to DI.

```
serviceCollection.AddSingleton<IConfigurationBuilder>(serviceProvider => configBuilder);
serviceCollection.AddSingleton<IConfiguration>(serviceProvider => configBuilder.Build());
```
Thanks, i will check ConfigureAppConfiguration

**Comment by anurse** [comment]
Did `ConfigureAppConfiguration` resolve your issue?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by AgrawalAshishS** [comment]
I am not sure what is the final solution but 

`public class Program
    {
        public static void Main(string[] args)
        {
             CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }`

doesn't pickup ASPNETCORE_URLS from environment.

my batch file looks like this

`@ SET ASPNETCORE_ENVIRONMENT=development 
@ SET DOTNET_PRINT_TELEMETRY_MESSAGE=false 
@ SET ASPNETCORE_URLS=http://*:6003 
@ SET ASPNETCORE_SERVER_URLS=http://*:6003 
dotnet run 
`

**Comment by anurse** [comment]
@AgrawalAshishS that sounds like a different issue. Can you file a new bug with a runnable sample that reproduces the problem? If it ends up being the same root cause, that's fine, a new issue will help us ensure we triage this appropriately.

**Comment by AgrawalAshishS** [comment]
I got it resolved by updating my startup to take IConfiguration

	public IConfiguration Configuration { get; }
        private IWebHostEnvironment CurrentEnvironment { get; set; }

        public Startup(IWebHostEnvironment env, IConfiguration configuration)
        {
            CurrentEnvironment = env;
            Configuration = configuration;
        }

**Comment by SidShetye** [comment]
@Tratcher the original author here was most likely trying to setup the environment variable on linux as a systemd process monitor to watch for `dotnet` behind apache or nginx ([example](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#create-the-service-file))

@justlearntutors For environment variables, you need to escape the **value** `http://localhost:5001` so systemd can parse it. Use the linux tool `systemd-escape` which gives `http:--localhost:5001` 

```
groot@terminus:~$ systemd-escape http://localhost:5001
http:--localhost:5001
```

Note, this is different from the escaping the **name** on Linux to be compatible with .NET Core. 

e.g. .NET Core setting `appSettings:SuperSecretApiKey` = Linux environment **name** `appSettings__SuperSecretApiKey` (two underscores `__`)
