### ISSUE TITLE
How can I host AspNetCore in Windows Service with https url?

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#15016]
_From @chenyj796 on Tuesday, October 15, 2019 12:37:40 PM_

I have a AspNetCore which will host in Windows Service.
The CreateHostBuilder method as below.

``` csharp
public static IHostBuilder CreateHostBuilder(string[] args)
{
	return Host
		.CreateDefaultBuilder(args)
		.UseWindowsService()
		.ConfigureServices((context, services) =>
		{
			services.AddHostedService<Worker>();
		})
		.ConfigureWebHostDefaults(builder =>
		{
			builder.UseUrls("http://localhost:6000/", "https://localhost:6001/");
			builder.UseStartup<Startup>();
		});
}
```

When I run it in Console, everything works fine.
However, when I install it as Windows Service, and request the http://localhost:6000/ or https://localhost:6001/, there is nothing returned.
Seems the UseUrls only support one url with http scheme, like 
``` csharp
builder.UseUrls("http://localhost:6000/");
```

_Copied from original issue: dotnet/corefx#41782_

**Comment by Tratcher** [comment]
_From @davidsh on Tuesday, October 15, 2019 2:41:31 PM_

@Tratcher ASP.NET Core repo issue

**Comment by Tratcher** [comment]
It looks like you're trying to use the default developer certificate? That's not supported in a Windows Service, they run as a different user, you'll need to create your own certificate.

See [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0#endpoint-configuration) once you have a cert.

**Comment by anurse** [comment]
Closing as the question has been answered. You need to have a valid certificate in the Windows Service account.

You *could* export the dev cert using the `dotnet dev-certs` tool and re-import it into the Local Machine cert store or the cert store for the Windows Service user account.
