### ISSUE TITLE
could not find dlls in my chrome debugging window

### ISSUE THREAD

**Issue by baoshenyi** [aspnet/AspNetCore#15015]
### Describe the bug
could not debug balzor client side code.

### To Reproduce
I follow up the instructions in https://coderethinked.com/unable-to-find-debuggable-browser-tab-in-blazor/ and everything worked fine.

After click "Shift+Alt+D", I could not find the dlls in debug window. Any ideas?

### Expected behavior
![BlazorDebugShouldbe](https://user-images.githubusercontent.com/9803653/66841903-94292c00-ef27-11e9-92b6-d3f98edf5864.png)

### Screenshots
My screen shoot:
![BlazorDebug2](https://user-images.githubusercontent.com/9803653/66841933-a2774800-ef27-11e9-8cb1-f2b2e600b3f6.PNG)
![BlazorDebug1](https://user-images.githubusercontent.com/9803653/66841945-a60acf00-ef27-11e9-8697-adae708901c6.PNG)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @baoshenyi.
We have instructions on how to enable debugging for Blazor WASM available at: https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0.
Please make sure you close all browser tabs/windows before you enable remote debugging.
