### ISSUE TITLE
NetCore 3.0 HttpContext.Sessions Lost After Redirecting Payment ( Bank System ) And Returning Back

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#15021]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/773817/netcore-30-httpcontextsessions-lost-after-redirect.html)._

---
Startup.cs

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHttpContextAccessor();

            services.Configure&lt;CookiePolicyOptions&gt;(options =&gt;
            {
            
                options.CheckConsentNeeded = context =&gt; false;
                options.MinimumSameSitePolicy = SameSiteMode.None; 
            });

            services.AddDistributedMemoryCache();

            services.AddSession(options =&gt;
            {
                options.Cookie.HttpOnly = false;
                options.IdleTimeout = TimeSpan.FromMinutes(20);
                options.Cookie.IsEssential = true;
                options.Cookie.SameSite = SameSiteMode.None;
            });

            services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
                .AddSessionStateTempDataProvider(); 
}

        public void Configure(IApplicationBuilder app, IHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler(&quot;/Home/Error&quot;);
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseRouting();
            // For most applications, calls to UseAuthentication, UseAuthorization, 
            //and UseCors must appear between the calls to UseRouting and UseEndpoints to be effective.
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseSession();
            

            app.UseEndpoints(endpoints =&gt;
            {
                endpoints.MapControllerRoute(&quot;default&quot;, &quot;{controller=TicketSearch}/{action=Index}/{id?}&quot;);
            });

        }

---
#### Visual Studio Feedback System on 10/12/2019, 01:25 AM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it
#### Visual Studio Feedback System on 10/12/2019, 01:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/12/2019, 01:41 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Andrew Stanton-Nurse [MSFT] on 10/14/2019, 01:34 PM: 

<p>Do you have multiple server processes (i.e multiple server machines, multiple IIS app pools, etc.)? If so, it’s possible the client is being redirect back and going to a different server machine that doesn’t have the session in place. The “DistributedMemoryCache” you added is a simple memory cache that implements the distributed cache feature for a single server, so it doesn’t do anything to share data between servers. Also you need to have a system to sync the data protection keys used to secure the session cookie itself.</p>
<p>Take a look at our docs on hosting <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core apps in a web farm: <a target='_blank' href="https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-3.0">https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-3.0</a> , they have some details on what needs to be configured in order to for <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core features to work in a web farm scenario.</p>
<p>If you are seeing this issue when running a single-server application, or if you’ve followed that guide and still have issues, let us know and we can start investigating further.</p>

#### planyazilim on 10/15/2019, 04:46 AM: 

No I dont have mulitple server process. I am testing on my local computer. I have my own web services on Azure Pay-as-you go. I am not sure if it makes sense, but i just moved my application to Netcore 3.0 , on .NET Framework 4.7 my application works good. So I think it is a bug, or simply I am missing to add something to my startup.cs. But I tried every solution which works for Net Core 2.2 the ydidnt work for 3.0.
#### Andrew Stanton-Nurse on 10/15/2019, 09:26 AM: 

<p>Ok, we’ll need to investigate further. Since this is a runtime issue, not a Visual Studio issue, I’m going to move this to our GitHub repository for further discussion/investigation.</p>
<p>Thanks for the report!</p>

---
### Original Solutions
(no solutions)

**Comment by Tratcher** [comment]
Can you share a Fiddler trace and debug server logs showing the repro?

**Comment by planyazilim** [comment]
Tratcher I dont have Fiddler logs but reproducing is simple.
HttpContext.ession works good, but after redirecting to a third partner page ( here in my situation payment system, it may be a bank or paypal ), when it is redireceted back session is empty.

**Comment by Tratcher** [comment]
@planyazilim that's insufficient, we really need to know how the redirects are executed. E.g. if these are POST based redirects then you'll need to change the Session cookie's SameSite option to None.
https://github.com/aspnet/AspNetCore/blob/1189a2c294df55d7a67f1bc6ea74d74858f467bd/src/Middleware/Session/src/SessionOptions.cs#L23

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
