### ISSUE TITLE
Multiple Client Side Blazor 

### ISSUE THREAD

**Issue by pabloarthurrodger** [aspnet/AspNetCore#15026]
I have a Web solution with a WebCore 3.0 razor pages that its huge!. Lets call this the WebCoreAppDefault. I want to implement 3 Blazor projects with different pages. In my Start up files I have configure as this:

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseClientSideBlazorFiles<BlazorApp1.Startup>();
app.UseClientSideBlazorFiles<BlazorApp2.Startup>();
app.UseClientSideBlazorFiles<BlazorApp3.Startup>();
app.UseRouting();

app.UseAuthorization();`enter code here`

app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
    endpoints.MapFallbackToClientSideBlazor<BlazorApp1.Startup>("ReportGenerator.html");
     endpoints.MapFallbackToClientSideBlazor<BlazorApp2.Startup>("DashboardConfiguration.html");
     endpoints.MapFallbackToClientSideBlazor<BlazorApp3.Startup>("ClaimsManipulation.html");

I do have the startup html file in each project as this: 1.- in the BlazorApp1 I have the ReportGenerator.html file under the wwwroot 1.- in the BlazorApp2 I have the DashboardConfiguration.html file under the wwwroot 1.- in the BlazorApp3 I have the ClaimsManipulation.html file under the wwwroot

When I run my WebCoreAppDefault, I can get to each Blazor file by adding a /ReportGenerator.html, or DashboardConfiguration.html, or ClaimsManipulation.html, and Blazor will load the project, but that's it.

The router of the blazor will not load any page, It will said "Sorry there is nothing at this address" on the not found. If I can put a link tag to the /Counter page, I can run the counter page without any layouts.

I believe I have problems after the blazor loads the mono and the dll, to redirect to another page that is not the root or "/" page?

I am trying to redirect in each project to a page that is not page "/", How Can I do that?

I want to understand how I can redirect to a page that is not root? or how to configure the App.razor page to redirect to a ReportGenerator.razor page or DashboardConfiguration.razor page or ClaimsManipulation.razor page as a landing page instead of being force to /

**Comment by javiercn** [comment]
```csharp
endpoints.MapFallbackToClientSideBlazor<BlazorApp1.Startup>("ReportGenerator.html");
endpoints.MapFallbackToClientSideBlazor<BlazorApp2.Startup>("DashboardConfiguration.html");
endpoints.MapFallbackToClientSideBlazor<BlazorApp3.Startup>("ClaimsManipulation.html");
```

This is not going to work well. The reason is that each "MapFallbackToClientSideBlazor" captures all routes that are not paths, so the second and third "MapFallbackToClientSideBlazor" calls are not going to match any route.

You need to instead include some sort of prefix that acts as a discriminator, as follows:
```csharp
endpoints.MapFallbackToClientSideBlazor<BlazorApp1.Startup>("/reports/{*path:nonfile}", "ReportGenerator.html");
endpoints.MapFallbackToClientSideBlazor<BlazorApp2.Startup>("/dashboard/{*path:nonfile}","DashboardConfiguration.html");
endpoints.MapFallbackToClientSideBlazor<BlazorApp3.Startup>("/claims/{*path:nonfile}", "ClaimsManipulation.html");
```

Then on each page you load you can load a different blazor app.
