### ISSUE TITLE
.net core 3.0 upload big file faild

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#15025]
_From @1369521908 on Tuesday, October 15, 2019 5:22:12 PM_

1 IDE
![image](https://user-images.githubusercontent.com/32727597/66853046-f7ab6c00-efb0-11e9-83a0-d9df9a4d2fb5.png)

2 .net core version (my project version)
![image](https://user-images.githubusercontent.com/32727597/66853134-23c6ed00-efb1-11e9-8344-ac4b64d6fe3d.png)

3 controller & api
![image](https://user-images.githubusercontent.com/32727597/66853188-40632500-efb1-11e9-9187-c126b7048774.png)

4 startup config
![image](https://user-images.githubusercontent.com/32727597/66853234-5a9d0300-efb1-11e9-8694-6d9bc0877efd.png)

5 upload file 
![image](https://user-images.githubusercontent.com/32727597/66853743-92f11100-efb2-11e9-802e-94b120b4784a.png)

5 error stack (error file size is >16MB)
![image](https://user-images.githubusercontent.com/32727597/66853429-dbf49580-efb1-11e9-8927-037ce56da6d6.png)

6.success condition (file size is 1KB )
![image](https://user-images.githubusercontent.com/32727597/66853827-c2078280-efb2-11e9-87d9-b0f1edefeef3.png)

small file is success accepted
![image](https://user-images.githubusercontent.com/32727597/66854055-2f1b1800-efb3-11e9-8068-132c8d631e7d.png)

is this config not effect or i config wrong? 
when i use .net core 2.2 ,that file[5] was success uploaded...

here is my code on github 
https://github.com/1369521908/Obsidian.git

_Copied from original issue: dotnet/corefx#41792_

**Comment by Tratcher** [comment]
_From @davidsh on Tuesday, October 15, 2019 6:01:45 PM_

@Tratcher Looks like ASP.NET issue

**Comment by Tratcher** [comment]
Side note: When sharing error messages and stack traces please copy the text rather than a screenshot.

Can you share a minimal application that reproduces this?

**Comment by anurse** [comment]
The sample app is quite large. Can you reduce this to a simple runnable sample that reproduces the problem?

**Comment by 1369521908** [comment]
already slove it , see https://github.com/aspnet/AspNetCore/issues/15025#issue-507402932

**Comment by 1369521908** [comment]
hey everyone , first , thanks for your reply. and in morning ,i try to remove the old project add a new project just now , and i works success...
![image](https://user-images.githubusercontent.com/32727597/66885631-78955280-f007-11e9-9e87-17089e8e3d77.png)

i don`t konw where the problem is ,but already solve it is great. : )
