### ISSUE TITLE
EndpointRouteBuilderExtensions missing RequestDelegateRouteBuilderExtensions signatures

### ISSUE THREAD

**Issue by jchannon** [aspnet/AspNetCore#15027]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

I am moving [Carter](https://github.com/CarterCommunity/Carter) to ASP.NET Core but one of it's features is the signature of `MapGet("/", (req,res,routeData)=>{...})` which hooks into the same signatures found on [RequestDelegateRouteBuilderExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.routing.requestdelegateroutebuilderextensions.mapget?view=aspnetcore-3.0#Microsoft_AspNetCore_Routing_RequestDelegateRouteBuilderExtensions_MapGet_Microsoft_AspNetCore_Routing_IRouteBuilder_System_String_System_Func_Microsoft_AspNetCore_Http_HttpRequest_Microsoft_AspNetCore_Http_HttpResponse_Microsoft_AspNetCore_Routing_RouteData_System_Threading_Tasks_Task__).  These similar signatures for MapGet/Post/Delete/Put are missing the `(req,res,routeData)` arguments in `EndpointRouteBuilderExtensions` and only have the `RequestDelegate` argument 

### Describe the solution you'd like
I would like to have the `MapGet(RequestDelegate)` AND the `MapGet(Func<HttpRequest,HttpResponse,RouteData,Task>)` methods on `EndpointRouteBuilderExtensions` as we used to have on `RequestDelegateRouteBuilderExtensions` pre ASP.NET Core 3.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jchannon.
@rynowak can you please have a look at this ? Thanks!

**Comment by rynowak** [comment]
@jchannon - can you point me at some code samples? 

I don't want to add more overloads unless it's going to make things significantly more usable. For instance in previous versions it was not easy to get to the route values from the `HttpContext`, now that's an extension method. If this is *just* about back-compat for Carter, I'd suggest making these extensions.

One point to mention is that `RouteData` is a legacy type, it uses `IRouter` and eventually it will go away. Endpoint routing doesn't create a `RouteData` for instance.

/cc @davidfowl

**Comment by jchannon** [comment]
Carter on aspnetcore3 (not merged yet) has these signatures and we adapt the signature to a RequestDelegate however it would be nice to have these extension methods just for very small apps where Carter/MVC is not used.

https://github.com/CarterCommunity/Carter/blob/aspnetcore3/src/Carter/CarterModule.cs#L62

If RouteData is going away can you provide a link or sample on how to retrieve the route constraint information because I assume the extension methods GetRouteData will disappear too?

**Comment by rynowak** [comment]
> If RouteData is going away can you provide a link or sample on how to retrieve the route constraint information 

Can you tell me more about this? What is *route constraint information* and what do you do with it? Example of typical usage? Sorry for all the questions, I want to make sure I can understand what you're doing.

**Comment by jchannon** [comment]
Carter uses RouteData to pull the values out and also if we keep the `Get("/", (req,res,routeData))` we would need an object or something to read the constraint values and create the `RequestDelegate`.

We also have extensions so the user can get the constraint values out when in a module. https://github.com/CarterCommunity/Carter/blob/master/src/Request/RouteDataExtensions.cs

```
var id = routeData.As<int>("id");

userRepository.GetUser(id)
```

**Comment by khellang** [comment]
Are you talking about `HttpRequest.RouteValues`?

https://github.com/aspnet/AspNetCore/blob/e336f4010af69cfdaba8b79d95a527efeb7bd5da/src/Http/Http.Abstractions/src/HttpRequest.cs#L130-L134

**Comment by jchannon** [comment]
Looking at RouteData and that it uses RouteValueDictionary which is the
same as your link, then I guess yes :)

**Comment by khellang** [comment]
Yeah, `GetRouteData` tries to use the routing feature to pull the data directly (if present) and falls back to `RouteValues` otherwise:

**Comment by jchannon** [comment]
RouteValues on the HttpRequest is a new 3.0 feature? I can't see it on  a 2.1 app I have for example

**Comment by khellang** [comment]
I think it was added in 2.2; https://github.com/aspnet/HttpAbstractions/pull/1042.

**Comment by jchannon** [comment]
So what I think would be nice but obviously up to MS is to have signatures
such as Get(string path, Func<HttpRequest, HttpResponse, Task> handler)

foo.Get("/users/{id:int}",(req,res) =>
res.WriteAsync(userRepo.Get(req.RouteValues["id"]))

I will look to move Carter to that signature maybe and for its extension
methods on RouteData to be on RouteValueDictionary instead

Cheers

**Comment by rynowak** [comment]
So it sounds route values are all you need. It's really easy to get at those right now.

> So what I think would be nice but obviously up to MS is to have signatures such as `Get(string path, Func<HttpRequest, HttpResponse, Task> handler)`

We will probably not add something like that signature. I haven't seen examples to convince me that it's more usable than `Get(string path, Func<HttpContext, Task> handler)`. We don't want to have a large number of overloads if they are just different flavors of the same thing.

**Comment by jchannon** [comment]
OK 👍
