### ISSUE TITLE
WebApp template does not respect logging configuration

### ISSUE THREAD

**Issue by dradovic** [aspnet/AspNetCore#15031]
### Describe the bug
 The `webapp` template does not respect the logging configuration of the `appsettings.json`.

### To Reproduce
1. `dotnet new webapp`
2. Change the trace levels in the provided `appsettings.json` to `Error`:
```
    {
        "Logging": {
          "LogLevel": {
            "Default": "Error",
            "Microsoft": "Error",
            "Microsoft.Hosting.Lifetime": "Error"
          }
        },
      "AllowedHosts": "*"
    }
```
3. Launch the app.

### Expected behavior
No more `info` level message should appear on the console.

### Actual behavior
The console shows all the logs.

### Additional context
`dotnet --info` on my machine:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
...

**Comment by cremor** [comment]
You need to modify `appsettings.Development.json` to get a different logging configuration while developing. See https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#json-configuration-provider

**Comment by dradovic** [comment]
@cremor : I don't agree. Quoting the source you are referring to:

`appsettings.json – This file is read first. The environment version of the file _can_ override the values provided by the appsettings.json file.`

Emphasis by me.

**Comment by dradovic** [comment]
@cremor : Oh sorry, I didn't see that the template already provides a *.Development.json.
