### ISSUE TITLE
Visual Studio 2019 hangs with Angular 8

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#15037]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/661537/visual-studio-2019-hangs-with-angular-8.html)._

---
We've updated from Angular 7 to Angular 8 and since then, Visual Studio hangs 2019 and 2017 while running the application! We can not work like that.
The spa service does not work properly.

Is there a solution or do we have to wait another half year for a solution ??????????

We have an Angular template from Microsoft:
Client Angular
Server: net core 2.1 or 2.6 it does not matter -&gt; running does nothing!

It would be nice if you had a Visual Studio which runs without errors and does not always hang in one place and does not give a decent error message!

An angry customer

---
#### Visual Studio Feedback System on 7/26/2019, 04:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/28/2019, 10:49 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### daniel.ellegaard on 9/12/2019, 11:27 PM: 

<p>I keep having the same problem too.</p>

#### Dan Warren on 9/20/2019, 11:15 AM: 

<p>This is a constant problem for me also. Usually because VS 2019 has used up 2.2GB of memory (normally runs at 300-500k), with CPU at 26%. Additionally, it's usually a node.js service, causing this. If I 'end task' the highest consuming instance, visual studio will return functionality</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please provide a small repro project (ideally as a GitHub repo) so that we can investigate this further.

**Comment by mkArtakMSFT** [comment]
Also, you can have a look at how Angular 8 support is enabled in ASP.NET Core 3.0.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
