### ISSUE TITLE
SignOut Blocked By CORS

### ISSUE THREAD

**Issue by MaribelPC** [aspnet/AspNetCore#15032]
Hello,

I am using Microsoft.AspNetCore.Authentication.WsFederation to authenticate to ADFS. The login works perfect, but at the time of logout the call is blocked by CORs. Could you help me?

It is a web application of the ASP.NET CORE 2.1 template with SPA in Angular 7.

The error in the browser is as follows:

Access to XMLHttpRequest at 'https://fstest.itesm.mx/adfs/ls/?wtrealm=https%3A%2F%2Fformalizacionprestamoqa.tec.mx&wa=wsignout1.0' (redirected from 'https://formalizacionprestamoqa.tec.mx/home/signout') from origin 'https://formalizacionprestamoqa.tec.mx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The code I use to logout is as follows:

[HttpPost]
public async Task SignOut()
{
      HttpContext.Session.Clear();
      await HttpContext.SignOutAsync(WsFederationDefaults.AuthenticationScheme);
      await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
}

If I click on this link shown in the DevTools console: https://fstest.itesm.mx/adfs/ls/?wtrealm=https%3A%2F%2Fformalizacionprestamoqa.tec.mx&wa=wsignout1.0 'me open another tab in the browser where the session is closed. So I see that log out is working, I just don't know how to prevent the call from being blocked by he browser.
Try already adding the ADFS path in the application's CORS configuration, but it doesn't work.

Please help me.

**Comment by anurse** [comment]
> Try already adding the ADFS path in the application's CORS configuration, but it doesn't work.

To be clear. It's **ADFS** that needs to be configured to accept requests from your app, not the other way around. It sounds like what you did was add the ADFS endpoint to your app's CORS config, which won't actually help here.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
