### ISSUE TITLE
Publish a new version of Microsoft.AspNetCore.ProtectedBrowserStorage

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#15043]
As noted in https://github.com/aspnet/AspNetCore/issues/13093, using this package with 3.0 RTM results in an error due to binary breaking changes in late 3.0 previews. We should publish a newer build of it compiled against 3.0 RTM.

**Comment by kARmAEffect** [comment]
Hi, when will this be resolved? It's just a simple build process

**Comment by pranavkm** [comment]
A new version that's compiled against 3.0.0 RTM is available on NuGet.org now: https://www.nuget.org/packages/Microsoft.AspNetCore.ProtectedBrowserStorage/0.1.0-alpha.19521.1
