### ISSUE TITLE
Publishing Blazor Web Assembly app to Azure = 404 not found

### ISSUE THREAD

**Issue by daltskin** [aspnet/AspNetCore#15050]
### Describe the bug
When publishing from dotnet cli, a spurious web.config is created in the root folder which causes 404s if deployed to Azure.

### To Reproduce
1. In Visual Studio create new Blazor app - selected Blazor Webassembly App (if you publish this via Visual Studio to Azure this will work)
2. Drop to CLI and run: "dotnet publish -c Release myApp"
3. Alternatively, use dotnet publish within Github Actions eg: 

```
    - name: dotnet publish
          run: dotnet publish -c Release -o myApp
```
4. Check the myapp folder and you'll notice a web.config file has appeared.  If you are running the above command in your build pipeline ie. Github Actions ([azure/webapps-deploy@v1)](https://github.com/Azure/webapps-deploy) this web.config then gets deployed to the azure web app - which will case 404 errors

### Expected behavior
dotnet publish should create correct web.config output

### Workaround
My workaround has been to create a web.config within the Blazor Client application with the following contents, which prevents dotnet publish from creating it's own corrupt one.  If this is added to source control, then Github Actions - [Azure/Webapps](https://github.com/Azure/webapps-deploy) deployment will deploy this version and will work.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\myApp.Server.dll" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>
```

![blazor](https://user-images.githubusercontent.com/1678318/66902409-81caf300-eff8-11e9-8936-3faec0e9da89.png))

**Comment by mkArtakMSFT** [comment]
We're closing this issue as we plan to reimplement publishing for Blazor WASM.
