### ISSUE TITLE
connection timeout Signal R ASP.Net CORE

### ISSUE THREAD

**Issue by mahabirsingh-kis** [aspnet/AspNetCore#15054]
I am facing the below issue in the .netCore application. Initially the SignalR is working fine but after sometime I start getting this issue and Signal R stops working

SQL server issue, the SignalR is not able to reconnect. Below is the message:
Error: Cannot send data if the connection is not in the 'Connected' State.
    at HttpConnection.send (app.bundle.js?v=null:11009)
    at HubConnection.sendMessage (app.bundle.js?v=null:11009)
    at HubConnection.sendWithProtocol (app.bundle.js?v=null:11009)
    at app.bundle.js?v=null:11009
    at new Promise (<anonymous>)
    at HubConnection.invoke (app.bundle.js?v=null:11009)
    at app.bundle.js?v=null:63752

Thanks

**Comment by BrennanConroy** [comment]
>connection timeout

Are you observing a log that says there was a timeout? Could you grab logs on the server and client as described in https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.0

Can you describe how your app and client are setup?

> SQL server

How is SQL server related to the issue?

**Comment by mahabirsingh-kis** [comment]
Hello @BrennanConroy , thanks for your response. My application is developed in .netcore  and React. I have the logged errors. Please find the attachments for the error logs
![picturemessage_pqz3oh3s 4m5](https://user-images.githubusercontent.com/16679896/66981810-7a781800-f0d2-11e9-8950-db00cc0a07dd.png)
![picturemessage_rgo3nrbr tq5](https://user-images.githubusercontent.com/16679896/66981822-84018000-f0d2-11e9-8244-5471b16af034.png)
![picturemessage_sete5wrw eow](https://user-images.githubusercontent.com/16679896/66981834-8cf25180-f0d2-11e9-8cf5-f29602bbcc93.png)

**Comment by BrennanConroy** [comment]
That just looks like a regular sql issue, like not being able to connect to the database.

What issue are you seeing with SignalR?

**Comment by mahabirsingh-kis** [comment]
Thank you for your response @BrennanConroy 

The issue is SignalR is not auto/re-connecting back after a SQL timeout. The SQLTableDependency raises the trigger error as shown in the logs.

There could be many reasons SQL timeout can occur but it is temporary and now SQL response is restored however SignalR is not re-connecting back. It reconnects only after issuing IISReset on the webserver (even restarting of website does not help).

Thanks

**Comment by BrennanConroy** [comment]
SignalR clients do not automatically reconnect by default. Starting in 3.0 you can enable reconnect, see our docs https://docs.microsoft.com/aspnet/core/signalr/javascript-client?view=aspnetcore-3.0#automatically-reconnect

**Comment by mahabirsingh-kis** [comment]
Thanks for your reply @BrennanConroy .

I have tried the same but it was not successful. I have creates another discussion for the same.
https://github.com/aspnet/AspNetCore/issues/14608

They are suggesting me to recreate the application from scratch so I was looking for alternate solution as it would be very cumbersome to build the application again from scratch.

Thanks

**Comment by anurse** [comment]
> I have tried the same but it was not successful.

What do you mean here by "not successful"? When automatically reconnecting are you getting the same SQL error? Or is the client not reconnecting?

Can you collect logs from the client **and** server as described in our documentation on [Logging and Diagnostics](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.0)?

**Comment by halter73** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
