### ISSUE TITLE
[Hosting] Hosting output conflicts with logging output.

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#15060]
* Create a template.
* Set console logging to debug
* Run the app a few times.
* At some point, the Hosting log messages will be incorrectly interleaved with the logging output.

```console
dbugHosting environment: Development
Content root path: C:\work\validation\angularpublishdbg30
: Microsoft.AspNetCore.Hosting.Diagnostics[4]
      Hosting started
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Loaded hosting startup assembly angularpublishdbg30
```

We discovered this as we were capturing the console output and looking for `Now listening on: ` messages in the templates tests, and they were hanging when we couldn't find the message.

**Comment by anurse** [comment]
Is this 3.0? This happens if you use WebHost because the "Now listening on" is written with Console.WriteLine and interleaves with logging. If you use Generic Host it uses logging and shouldn't interleave.

**Comment by javiercn** [comment]
@anurse This happens with our templates. 

Awesome. That's good to know. Seems like the SPA templates didn't get updated to use generic host
