### ISSUE TITLE
Asp.net core 3.0 how read body from PipeWriter . 

### ISSUE THREAD

**Issue by mkris2003** [aspnet/AspNetCore#15063]
Hi,

Could you please help me i am writing middleware for request and response .

i was using  stream but need to convert  PipeWriter and PipeReader.

Could you please help me how read body from PipeWriter .

i have written code for PipeReader.

private  async Task<string> GetStringFromPipeReader(PipeReader reader)
        {
            StringBuilder stringBuilder = new StringBuilder();
            while (true)
            {
                // await some data being available
                ReadResult read = await reader.ReadAsync();
                ReadOnlySequence<byte> buffer = read.Buffer;
                // check whether we've reached the end
                // and processed everything
                if (buffer.IsEmpty && read.IsCompleted)
                    break; // exit loop
               
                // process what we received
                foreach (var segment in buffer)
                {
                    string asciString = Encoding.ASCII.GetString(
                        segment.Span);
                    stringBuilder.Append(asciString);
                }
                // tell the pipe that we used everything
               // reader.AdvanceTo(buffer.End);

                reader.AdvanceTo(buffer.Start, buffer.End);

                if (read.IsCompleted)
                {
                    break;
                }

            }
            return Convert.ToString(stringBuilder);
        }

       private  async Task  WriteSomeDataAsync(PipeWriter writer, string jsonValue)
        {
            // use an oversized size guess
            Memory<byte> workspace = writer.GetMemory();
            // write the data to the workspace
            int bytes = Encoding.ASCII.GetBytes(
               jsonValue, workspace.Span);
            // tell the pipe how much of the workspace
            // we actually want to commit
            writer.Advance(bytes);
            // this is **not** the same as Stream.Flush!
            await writer.FlushAsync();
        }

Thanks,
Konanki

**Comment by Tratcher** [comment]
Why do you need to switch to pipes? That's optional. You can continue to use Streams and only put a pipe adapter over them when needed. For an example look at how the response compression middleware works. Here are the changes we made in 3.0 to consolidate streams and pipes:
https://github.com/aspnet/AspNetCore/commit/080660967b6043f731d4b7163af9e9e6047ef0c4#diff-8e5e94fea052bcafa7a5167a9011e90d
https://github.com/aspnet/AspNetCore/commit/080660967b6043f731d4b7163af9e9e6047ef0c4#diff-5d4ce933ddf778f17e053750af25e703

**Comment by Tratcher** [comment]
This is not the place for a tutorial on Pipes. @davidfowl can you suggest any similar Pipe samples, doc, etc.?

**Comment by jkotalik** [comment]
We have some docs here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-3.0. I can't find the .NET ones.

**Comment by davidfowl** [comment]
@mkris2003 There's no point using the PipeReader if you're going to turn it all into a string. You won't save too much (though you can save on intermediate allocations). You're basically re-implementing StreamReader at that point.
