### ISSUE TITLE
disabled attribute and async method

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#15073]
Hello guys, i met a problem to bind the disabled attribute with an async method.

I don't know if it's possible or if i don't have the good syntax, but i have compilation error whatever i did

this is my code
````
<button type="button" class="btn btn-primary" @onclick="@Validate" disabled="@(async () => await CanValidate())">Validate</button>

protected async Task<bool> CanValidate()
        {
            ...
        }
````

thanks for your help !

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

In Blazor rendering is synchronous, you need to move your async logic to OnInitializeAsync.

Our recomendation is that you change your view to `disabled=@Property` where Property is true by default and set it to the appropriate value from `Property = await CanValidate()` inside OnInitializeAsync.

Hope that helps
