### ISSUE TITLE
Remove doc references to obsolete AuthenticationManager

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#15079]
HttpContext.AuthenticationManager was obsoleted and removed in prior releases, but there are still several references to it in the doc comments and API docs.
https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/ChallengeResult.cs#L14
https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/ForbidResult.cs#L14
https://github.com/aspnet/AspNetCore/blob/c18fc3d7ca468628c6bbb7030014ab94f15f83cf/src/Mvc/Mvc.Core/src/SignInResult.cs#L15
https://github.com/aspnet/AspNetCore/blob/c18fc3d7ca468628c6bbb7030014ab94f15f83cf/src/Mvc/Mvc.Core/src/SignOutResult.cs#L15
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.challengeresult?view=aspnetcore-3.0

The replacement for all of these are HttpContext extension methods with the same name. E.g. HttpContext.ChallengeAsync

**Comment by adrianwright109** [comment]
@Tratcher - Looks like this issue can be closed as the PR to fix it #15110 has already been merged into `release/3.1`.

**Comment by Tratcher** [comment]
@adrianwright109 Thanks for the reminder.
