### ISSUE TITLE
ASP.NET Core 3 React template - Refresh token usage

### ISSUE THREAD

**Issue by pkali18** [aspnet/AspNetCore#15080]
Is there any way whatsoever to trigger the usage/issuing of **refresh tokens** from Identity Server with the current **React template** provided in ASP.NET Core 3? I'd love to able to build on top of the current setup instead of starting from scratch in order to use token renewal.

**Comment by pranavkm** [comment]
@javiercn could you respond?

**Comment by brockallen** [comment]
Refresh tokens are not highly recommended for SPAs.

**Comment by javiercn** [comment]
@pkali18 Thanks for contacting us.

@brockallen is right. We don't recommend using refresh tokens and the templates should be already configured to perform silent access_token token refresh through a hidden iframe, which is the recommended way to support this scenario.
