### ISSUE TITLE
Reopening: EditForm: After you hit submit the first time, any new tabbing through fields tries to resubmit

### ISSUE THREAD

**Issue by kevingates** [aspnet/AspNetCore#15083]
I hate doing it this way, but  this issue is to reopen another Github issue. My UI didn't have an option to reopen the issue myself, so here's a link to the bug.
https://github.com/aspnet/AspNetCore/issues/14859

**Comment by pranavkm** [comment]
Thanks @kevingates. I'll reopen the other issue since it has more context.
