### ISSUE TITLE
Multipart body length limit 16384 exceeded

### ISSUE THREAD

**Issue by MyJimmyZhou** [aspnet/AspNetCore#15098]
### 
I encountered errors in the following situations：
code like this:
``` 
public UploadFileDto UploadFile(HttpRequest request)
        {
            var trustedFileNameForDisplay = string.Empty;
            //var untrustedFileNameForStorage = string.Empty;
            var streamedFileContent = new byte[0];
            var boundary = MultipartRequestHelper.GetBoundary(MediaTypeHeaderValue.Parse(request.ContentType), _formOptions.MultipartBoundaryLengthLimit);
            var reader = new MultipartReader(boundary, request.Body);
            var section = reader.ReadNextSectionAsync().Result;
            while (section != null)
            {
                var hasContentDispositionHeader = ContentDispositionHeaderValue.TryParse(section.ContentDisposition, out var contentDisposition);

                //untrustedFileNameForStorage = contentDisposition.FileName.Value;
                trustedFileNameForDisplay = WebUtility.HtmlEncode(contentDisposition.FileName.Value);
                var ext = Path.GetExtension(trustedFileNameForDisplay).ToLowerInvariant();
                if (string.IsNullOrEmpty(ext) || !_permittedExtensions.Contains(ext))
                {
                    throw new Exception("file is error");
                }

                if (hasContentDispositionHeader)
                {
                    if (MultipartRequestHelper.HasFileContentDisposition(contentDisposition))
                    {
                        streamedFileContent = FileHelpers.ProcessStreamedFile(section, _fileSizeLimit);
                    }
                }
                section = reader.ReadNextSectionAsync().Result;
            }
            return new UploadFileDto
            {
                FileContent = streamedFileContent,
                FileName = trustedFileNameForDisplay
            };
        }
```
1: this exception to be thrown when I use http and file size > 2MB
2: It works like this:
  http,file size < 2MB ;
  https ,no file size limit .

Another situation 
use async code ,It works too,
code like this:
```
 public async Task<UploadFileDto> UploadFile(HttpRequest request)
        {
            var trustedFileNameForDisplay = string.Empty;
            //var untrustedFileNameForStorage = string.Empty;
            var streamedFileContent = new byte[0];
            var boundary = MultipartRequestHelper.GetBoundary(MediaTypeHeaderValue.Parse(request.ContentType), _formOptions.MultipartBoundaryLengthLimit);
            var reader = new MultipartReader(boundary, request.Body);
            var section = await reader.ReadNextSectionAsync();
            while (section != null)
            {
                var hasContentDispositionHeader = ContentDispositionHeaderValue.TryParse(section.ContentDisposition, out var contentDisposition);

                //untrustedFileNameForStorage = contentDisposition.FileName.Value;
                trustedFileNameForDisplay = WebUtility.HtmlEncode(contentDisposition.FileName.Value);
                var ext = Path.GetExtension(trustedFileNameForDisplay).ToLowerInvariant();
                if (string.IsNullOrEmpty(ext) || !_permittedExtensions.Contains(ext))
                {
                    throw new Exception("file is error");
                }

                if (hasContentDispositionHeader)
                {
                    if (MultipartRequestHelper.HasFileContentDisposition(contentDisposition))
                    {
                        streamedFileContent = FileHelpers.ProcessStreamedFile(section, _fileSizeLimit);
                    }
                }
                section = await reader.ReadNextSectionAsync();
            }
            return new UploadFileDto
            {
                FileContent = streamedFileContent,
                FileName = trustedFileNameForDisplay
            };
        }
```
I don't know why there's an exception when I use http and file size > 2MB.
but other situation is working.

**Comment by Tratcher** [comment]
Can you share a fiddler trace? Also please share the full stack trace of the exception. This usually happens when the boundary is not correct.
https://github.com/aspnet/AspNetCore/blob/418e35c4396682aea6ee6e9833ff3bd3bfe624eb/src/Http/WebUtilities/src/MultipartReader.cs#L48-L50

**Comment by MyJimmyZhou** [comment]
![image](https://user-images.githubusercontent.com/13486578/67082970-d4f59f00-f1cc-11e9-8210-d5793af77083.png)

StackTrack:   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Best.FR.Service.FileProcess.FileProcess.UploadFile(HttpRequest request) in C:\Users\BG376210\source\repos\Best.FR\Best.FR.Service\FileProcess\FileProcess.cs:line 32
   at Best.FR.API.Controllers.ReportController.UploadCptFile() in C:\Users\BG376210\source\repos\Best.FR\Best.FR.API\Controllers\ReportController.cs:line 33
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
------InnerException 1------
Type:System.IO.InvalidDataException
Message:Multipart body length limit 16384 exceeded.

**Comment by Tratcher** [comment]
Please share the actual trace file rather than a screen shot.

There should be a stack trace on the InvalidDataException.

**Comment by MyJimmyZhou** [comment]
No problem on the other machine。thanks
