### ISSUE TITLE
How to use IServiceProvider in OnConnectedAsync method on AzureSignalR

### ISSUE THREAD

**Issue by bidianqing** [aspnet/AspNetCore#15095]
following code  
```
services.AddSignalR()
    .AddAzureSignalR(options =>
    {
        options.ConnectionString = connectionString;
    });
```
```
app.UseAzureSignalR(routes =>
{
    routes.MapHub<ChatHub>("/chatHub");
});
```
![image](https://user-images.githubusercontent.com/12196280/66972892-a1c9e780-f0c8-11e9-8510-f8b9ce8294d6.png)
In OnConnectedAsync method, services is null ,I want use this, Please tell me what to do ? Thanks

**Comment by bidianqing** [comment]
Unable to get cookies

**Comment by davidfowl** [comment]
You shouldn’t be using RequestServices, you should be resolving services in your Hub constructor

**Comment by bidianqing** [comment]
How to get Cookies in OnConnectedAsync method? Thanks

**Comment by bidianqing** [comment]
@davidfowl

**Comment by BrennanConroy** [comment]
Could you explain your scenario and why you want cookies in the `OnConnectedAsync` method?

**Comment by davidfowl** [comment]
They *should* be available on the `HttpContext`.

**Comment by halter73** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
