### ISSUE TITLE
determine what port asp.net core is listening to

### ISSUE THREAD

**Issue by sweetodev** [aspnet/AspNetCore#15090]
I'm trying to register my microservice with consul and it requires the address and the port it's listening to. 

I am able to retrieve address from `Dns.GetHostName()` but can't determine the port number which varies from dev to production.

Is there a programatic way to determine this value on startup, for instance within this code:

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration((host, config) =>
            {
                Environment.SetEnvironmentVariable("APPLICATION_NAME", host.HostingEnvironment.ApplicationName);
            })
            .UseStartup<Service>();

### Additional context
If there  can be singletons, then it's easy to access them anywhere in the application, right now Im storing Application Name in the environment for access later.

**Comment by davidfowl** [comment]
You can do it *after* the server starts, like in an IHostedService implementation.

```C#
public class ConsulHostedService : IHostedService
{
    public ConsulHostedService(IServer server)
    {
        ServerAddresses = server.Features.Get<IServerAddressesFeature>();
    }

    public IServerAddressesFeature ServerAddresses { get; }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        foreach (var address in ServerAddresses.Addresses)
        {
            RegisterAddressWithConsul(address);
        }

        return Task.CompletedTask;
    }

    private void RegisterAddressWithConsul(string address)
    {
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
```

```C#
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WebApplication366
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureServices(services =>
                {
                    services.AddHostedService<ConsulHostedService>();
                });
    }
}
```
