### ISSUE TITLE
Scenarios are not running: ConnectionClose, ConnectionClose, ConnectionClose, ConnectionClose, DbFortunesDapper ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#15108]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| ConnectionClose | Windows, Cloud, http, KestrelSockets | 10/16/19 10:08:40 AM +00:00 |
| ConnectionClose | Windows, Cloud, https, KestrelSockets | 10/16/19 10:09:04 AM +00:00 |
| ConnectionClose | Windows, Physical, http, KestrelSockets | 10/16/19 10:37:41 AM +00:00 |
| ConnectionClose | Windows, Physical, https, KestrelSockets | 10/16/19 10:38:01 AM +00:00 |
| DbFortunesDapper | Windows, Cloud, http, KestrelSockets | 10/16/19 9:57:29 AM +00:00 |
| DbFortunesDapper | Windows, Physical, http, KestrelSockets | 10/16/19 10:27:05 AM +00:00 |
| DbFortunesEf | Windows, Cloud, http, KestrelSockets | 10/16/19 9:58:16 AM +00:00 |
| DbFortunesEf | Windows, Physical, http, KestrelSockets | 10/16/19 10:27:48 AM +00:00 |
| DbFortunesRaw | Windows, Cloud, http, KestrelSockets | 10/16/19 9:56:42 AM +00:00 |
| DbFortunesRaw | Windows, Physical, http, KestrelSockets | 10/16/19 10:26:21 AM +00:00 |
| DbMultiQueryDapper | Windows, Physical, http, KestrelSockets | 10/16/19 10:18:18 AM +00:00 |
| DbMultiQueryEf | Windows, Physical, http, KestrelSockets | 10/16/19 10:19:02 AM +00:00 |
| DbMultiQueryRaw | Windows, Physical, http, KestrelSockets | 10/16/19 10:17:33 AM +00:00 |
| DbMultiUpdateDapper | Windows, Physical, http, KestrelSockets | 10/16/19 10:22:42 AM +00:00 |
| DbMultiUpdateEf | Windows, Physical, http, KestrelSockets | 10/16/19 10:23:26 AM +00:00 |
| DbMultiUpdateRaw | Windows, Physical, http, KestrelSockets | 10/16/19 10:21:58 AM +00:00 |
| DbSingleQueryDapper | Windows, Physical, http, KestrelSockets | 10/16/19 10:13:52 AM +00:00 |
| DbSingleQueryEf | Windows, Physical, http, KestrelSockets | 10/16/19 10:14:36 AM +00:00 |
| DbSingleQueryRaw | Windows, Physical, http, KestrelSockets | 10/16/19 10:13:08 AM +00:00 |
| EndpointPlaintext | Windows, Physical, http, KestrelSockets | 10/16/19 9:52:49 AM +00:00 |
| HttpClient | Windows, Cloud, http, KestrelSockets | 10/16/19 10:06:29 AM +00:00 |
| HttpClient | Windows, Physical, http, KestrelSockets | 10/16/19 10:35:36 AM +00:00 |
| HttpClientFactory | Windows, Cloud, http, KestrelSockets | 10/16/19 10:08:12 AM +00:00 |
| HttpClientFactory | Windows, Physical, http, KestrelSockets | 10/16/19 10:37:14 AM +00:00 |
| HttpClientParallel | Windows, Cloud, http, KestrelSockets | 10/16/19 10:07:17 AM +00:00 |
| HttpClientParallel | Windows, Physical, http, KestrelSockets | 10/16/19 10:36:23 AM +00:00 |
| Json | Windows, Physical, http, KestrelSockets | 10/16/19 9:57:26 AM +00:00 |
| Json | Windows, Physical, https, KestrelSockets | 10/16/19 10:03:45 AM +00:00 |
| Json | Windows, Cloud, http, IISInProcess | 10/16/19 10:04:50 AM +00:00 |
| Json | Windows, Cloud, http, IISOutOfProcess | 10/16/19 10:05:41 AM +00:00 |
| Json | Windows, Physical, h2, KestrelSockets | 10/16/19 10:07:02 AM +00:00 |
| Json | Windows, Physical, h2c, KestrelSockets | 10/16/19 10:07:45 AM +00:00 |
| Json | Windows, Physical, http, IISInProcess | 10/16/19 10:34:02 AM +00:00 |
| Json | Windows, Physical, http, IISOutOfProcess | 10/16/19 10:34:50 AM +00:00 |
| MemoryCachePlaintext | Windows, Physical, http, KestrelSockets | 10/16/19 10:08:27 AM +00:00 |
| MemoryCachePlaintextSetRemove | Windows, Physical, http, KestrelSockets | 10/16/19 10:09:12 AM +00:00 |
| MvcDbFortunesDapper | Windows, Cloud, http, KestrelSockets | 10/16/19 9:59:50 AM +00:00 |
| MvcDbFortunesDapper | Windows, Physical, http, KestrelSockets | 10/16/19 10:29:17 AM +00:00 |
| MvcDbFortunesEf | Windows, Cloud, http, KestrelSockets | 10/16/19 10:00:37 AM +00:00 |
| MvcDbFortunesEf | Windows, Physical, http, KestrelSockets | 10/16/19 10:30:01 AM +00:00 |
| MvcDbFortunesRaw | Windows, Cloud, http, KestrelSockets | 10/16/19 9:59:04 AM +00:00 |
| MvcDbFortunesRaw | Windows, Physical, http, KestrelSockets | 10/16/19 10:28:32 AM +00:00 |
| MvcDbMultiQueryDapper | Windows, Cloud, http, KestrelSockets | 10/16/19 9:50:20 AM +00:00 |
| MvcDbMultiQueryDapper | Windows, Physical, http, KestrelSockets | 10/16/19 10:20:30 AM +00:00 |
| MvcDbMultiQueryEf | Windows, Cloud, http, KestrelSockets | 10/16/19 9:51:08 AM +00:00 |
| MvcDbMultiQueryEf | Windows, Physical, http, KestrelSockets | 10/16/19 10:21:14 AM +00:00 |
| MvcDbMultiQueryRaw | Windows, Physical, http, KestrelSockets | 10/16/19 10:19:47 AM +00:00 |
| MvcDbMultiUpdateDapper | Windows, Physical, http, KestrelSockets | 10/16/19 10:24:54 AM +00:00 |
| MvcDbMultiUpdateEf | Windows, Physical, http, KestrelSockets | 10/16/19 10:25:37 AM +00:00 |
| MvcDbSingleQueryDapper | Windows, Physical, http, KestrelSockets | 10/16/19 10:16:04 AM +00:00 |
| MvcDbSingleQueryEf | Windows, Physical, http, KestrelSockets | 10/16/19 10:16:49 AM +00:00 |
| MvcDbSingleQueryRaw | Windows, Physical, http, KestrelSockets | 10/16/19 10:15:20 AM +00:00 |
| MvcJson | Windows, Physical, http, KestrelSockets | 10/16/19 9:58:10 AM +00:00 |
| MvcJson2k | Windows, Physical, http, KestrelSockets | 10/16/19 9:59:38 AM +00:00 |
| MvcJsonInput2k | Windows, Physical, http, KestrelSockets | 10/16/19 10:01:04 AM +00:00 |
| MvcJsonNet | Windows, Physical, http, KestrelSockets | 10/16/19 9:58:53 AM +00:00 |
| MvcJsonNet2k | Windows, Physical, http, KestrelSockets | 10/16/19 10:00:22 AM +00:00 |
| MvcJsonNetInput2k | Windows, Physical, http, KestrelSockets | 10/16/19 10:01:48 AM +00:00 |
| MvcPlaintext | Windows, Physical, http, KestrelSockets | 10/16/19 9:50:40 AM +00:00 |
| Plaintext | Windows, Physical, http, HttpSys | 10/16/19 9:53:33 AM +00:00 |
| Plaintext | Windows, Cloud, http, IISInProcess | 10/16/19 10:01:24 AM +00:00 |
| Plaintext | Windows, Cloud, http, IISOutOfProcess | 10/16/19 10:02:16 AM +00:00 |
| Plaintext | Windows, Physical, https, KestrelSockets | 10/16/19 10:02:32 AM +00:00 |
| Plaintext | Windows, Physical, http, IISInProcess | 10/16/19 10:30:45 AM +00:00 |
| Plaintext | Windows, Physical, http, IISOutOfProcess | 10/16/19 10:31:33 AM +00:00 |
| PlaintextNonPipelined | Windows, Cloud, http, IISInProcess | 10/16/19 10:03:07 AM +00:00 |
| PlaintextNonPipelined | Windows, Cloud, http, IISOutOfProcess | 10/16/19 10:03:58 AM +00:00 |
| PlaintextNonPipelined | Windows, Physical, https, KestrelSockets | 10/16/19 10:04:55 AM +00:00 |
| PlaintextNonPipelined | Windows, Physical, h2, KestrelSockets | 10/16/19 10:05:38 AM +00:00 |
| PlaintextNonPipelined | Windows, Physical, h2c, KestrelSockets | 10/16/19 10:06:20 AM +00:00 |
| PlaintextNonPipelined | Windows, Physical, http, IISInProcess | 10/16/19 10:32:23 AM +00:00 |
| PlaintextNonPipelined | Windows, Physical, http, IISOutOfProcess | 10/16/19 10:33:13 AM +00:00 |
| PlaintextNonPipelinedLogging | Windows, Cloud, http, KestrelSockets | 10/16/19 10:09:49 AM +00:00 |
| PlaintextNonPipelinedLogging | Windows, Physical, http, KestrelSockets | 10/16/19 10:38:45 AM +00:00 |
| PlaintextNonPipelinedLoggingNoScopes | Windows, Cloud, http, KestrelSockets | 10/16/19 10:10:34 AM +00:00 |
| PlaintextNonPipelinedLoggingNoScopes | Windows, Physical, http, KestrelSockets | 10/16/19 10:39:28 AM +00:00 |
| ResponseCachingPlaintextCached | Windows, Physical, http, KestrelSockets | 10/16/19 10:09:56 AM +00:00 |
| ResponseCachingPlaintextRequestNoCache | Windows, Physical, http, KestrelSockets | 10/16/19 10:11:41 AM +00:00 |
| ResponseCachingPlaintextResponseNoCache | Windows, Physical, http, KestrelSockets | 10/16/19 10:10:39 AM +00:00 |
| ResponseCachingPlaintextVaryByCached | Windows, Physical, http, KestrelSockets | 10/16/19 10:12:25 AM +00:00 |
| StaticFiles | Windows, Physical, http, KestrelSockets | 10/16/19 9:55:43 AM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Recovered
