### ISSUE TITLE
bind-* on ICollection not working for HashSet or List

### ISSUE THREAD

**Issue by oiBio** [aspnet/AspNetCore#15101]
We are working on an input element that binds to an ICollection<string>.  Its works fine when we bind an actual ICollection<string> variable to it. But not when the bouded variable is a HashSet<string> or a List<string>. 

We are using the binding with the EventcallBack. 
```
[Parameter] public ICollection<string> TagList { get; set; }
[Parameter] public EventCallback<ICollection<string>> TagListChanged { get; set; }
```
and we call it like this
```
<TagEditor @bind-TagList="Model.ICollectionList" /> // Working
<TagEditor @bind-TagList="Model.HashSet" /> // Not Working
```

### Describe the bug
The compiler throwes the following error
> Fehler CS1503 Argument "2": Konvertierung von "Microsoft.AspNetCore.Components.EventCallback<System.Collections.Generic.HashSet<string>>" in "Microsoft.AspNetCore.Components.EventCallback" nicht möglich.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @oiBio .
@pranavkm can you please look into this? Thanks!
