### ISSUE TITLE
AccessFailedCount on Master Slave cluster

### ISSUE THREAD

**Issue by phonglt7** [aspnet/AspNetCore#15100]
Hi, we have an issue happened after the database move to cluster.
We have a writer database and a reader database.

After moving to the cluster, the AccessFailedCount didn't increase anymore after a failed attempt.

Here is the debug output we got
<img width="1675" alt="66798013-d6a63500-ef36-11e9-9014-beac1bd97e93" src="https://user-images.githubusercontent.com/46190930/66979317-3f2c1800-f0d7-11e9-8c4b-10a7f79d1a1b.png">

As we observe, it happened when the CheckPasswordSignInAsync calls UserManager.AccessFailedAsync, it generated 2 SQL update statements, which are failed because of ConcurrencyStamp.

Please help me with this case.

Thanks,
Phong.

**Comment by blowdart** [comment]
What database is identity configured to use? The writer database? What is the actual database behind it? SQL? mySQL? Something else?
