### ISSUE TITLE
QueryStringMapping?

### ISSUE THREAD

**Issue by bertt** [aspnet/AspNetCore#15113]
In older versions of asp.net web api there was the QueryStringMapping object, a handy way to specify the mediatype in the querystring (like http://my-app/api/contacts/11/?format=vcard). Full example at https://weblogs.asp.net/gunnarpeipman/asp-net-web-api-query-string-based-content-formatting

Whats the equivalent way to specify the mediatype in  the querystring in asp.net web api core?

**Comment by pranavkm** [comment]
`FormatFilter` would be the equivalent - https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.0#response-format-url-mappings

**Comment by bertt** [comment]
thanks for the pointer. Got it working now doing some more customizations as described in https://www.strathweb.com/2016/07/customizing-formatfilter-behavior-in-asp-net-core-mvc-1-0/#more-5081
