### ISSUE TITLE
Scenarios are not running: EndpointPlaintext, Json, Json, MvcJson, MvcJson2k ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#15114]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| EndpointPlaintext | Windows, Cloud, http, KestrelSockets | 10/16/19 1:10:46 PM +00:00 |
| Json | Windows, Cloud, http, KestrelSockets | 10/16/19 1:26:23 PM +00:00 |
| Json | Windows, Cloud, https, KestrelSockets | 10/16/19 1:38:03 PM +00:00 |
| MvcJson | Windows, Cloud, http, KestrelSockets | 10/16/19 1:27:53 PM +00:00 |
| MvcJson2k | Windows, Cloud, http, KestrelSockets | 10/16/19 1:30:10 PM +00:00 |
| MvcJsonInput2k | Windows, Cloud, http, KestrelSockets | 10/16/19 1:32:22 PM +00:00 |
| MvcJsonNet | Windows, Cloud, http, KestrelSockets | 10/16/19 1:29:03 PM +00:00 |
| MvcJsonNet2k | Windows, Cloud, http, KestrelSockets | 10/16/19 1:31:16 PM +00:00 |
| MvcJsonNetInput2k | Windows, Cloud, http, KestrelSockets | 10/16/19 1:33:28 PM +00:00 |
| MvcPlaintext | Windows, Cloud, http, KestrelSockets | 10/16/19 1:06:08 PM +00:00 |
| Plaintext | Windows, Cloud, http, KestrelSockets | 10/16/19 12:57:17 PM +00:00 |
| Plaintext | Windows, Cloud, http, HttpSys | 10/16/19 1:12:08 PM +00:00 |
| Plaintext | Windows, Cloud, https, KestrelSockets | 10/16/19 1:34:56 PM +00:00 |
| Plaintext | Windows, Cloud, https, HttpSys | 10/16/19 1:36:24 PM +00:00 |
| StaticFiles | Windows, Cloud, http, KestrelSockets | 10/16/19 1:16:16 PM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Recovered
