### ISSUE TITLE
Blazor Relative URLs

### ISSUE THREAD

**Issue by carlowahlstedt** [aspnet/AspNetCore#15112]
Images in the wwwroot folder not loading when using a BasePath.

### To Reproduce
1. Using the initial release of ASP.NET Core 3
2. Host your site on IIS in an application under the main site. In my scenario: `http://valseg38/release_model_sample/`
3. On deployment the base URI is set to `/release_model_sample/` in _Host.cshtml
4. On the MainLayout.razor or Index.razor page insert an img tag pointing to an image in the wwwroot folder. In my specific scenario: `<img src="/img/logo-white-icon.png">`

### Expected behavior
The image should load because the base url is set and the image is pointed relative to the wwwroot folder

### Screenshots
![image](https://user-images.githubusercontent.com/2687687/67006757-ef882500-f0b3-11e9-9c2f-b1fbf1f51e81.png)

![image](https://user-images.githubusercontent.com/2687687/67006783-f7e06000-f0b3-11e9-9ef8-b7cab828b9e4.png)

![image](https://user-images.githubusercontent.com/2687687/67007319-1c890780-f0b5-11e9-8d42-22e643485c31.png)

### Additional context
[Docs still seem to mention index.html](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/?view=aspnetcore-3.0&tabs=visual-studio), which from my research is pre-core 3 release. @SteveSandersonMS seems to re-enforce the [expected behavior here](https://github.com/aspnet/AspNetCore/issues/12930#issuecomment-519673288).

**Comment by carlowahlstedt** [comment]
FYI, seeing the 3.1 tag reminded to test with preview1 just released. I did that with the same results. It is a self-contained release.

**Comment by javiercn** [comment]
@carlowahlstedt Thanks for contacting us.

I believe this is an issue in how you are referencing the image in your markup. If you have a url that starts with `/` it means its relative to the host.

If you remove the `/` from the image link, it should produce the expected result.

If that doesn't work, let us know.

**Comment by carlowahlstedt** [comment]
Oh wow, that was a simple enough fix. Never occurred to me to do that. Thanks!
