### ISSUE TITLE
Unable to update master branch on my fork of AspNetCore

### ISSUE THREAD

**Issue by adrianwright109** [aspnet/AspNetCore#15125]
I went to update the `master` branch on my GitHub fork of `aspnet/AspNetCore` and it failed with error:
```
 ! [remote rejected]       master -> master (refusing to allow an integration to create or update .github/workflows/labeler.yml)
error: failed to push some refs to 'https://github.com/adrianwright109/AspNetCore'
```

This usually works without issue.

The steps I did were:
1. Get latest commits from `aspnet/AspNetCore` 
`git pull upstream master`
2. Push those commits to my `master` branch on my fork
`git push origin master`

**N.B.**  It works fine if I update a different branch, e.g. `release/3.1` using the steps above but substituting the branch name.

Looks like a recent commit into the `master` branch is stopping forks from being updated.  Possibly something to do with `.github/workflows/labeler.yml`?

**Comment by javiercn** [comment]
@adrianwright109 Thanks for contacting us.

@aspnet/build Can someone help @adrianwright109  here?

**Comment by dougbu** [comment]
I believe GitHub actions need to be enabled in your fork repository.

@mkArtakMSFT do you have more context here? Another suggestion?

**Comment by mkArtakMSFT** [comment]
We've tried this out on a separate fork, and couldn't repro it. Though the account we tried this for had already enabled GitHub Actions. Maybe this is indeed the cause? @adrianwright109 can you try to sign up for GitHub Actions (it's in Beta currently) and see whether after it's enabled the issue is resolved?

**Comment by adrianwright109** [comment]
I have signed up to the GitHub Actions Beta programme using the following link: `https://github.com/features/actions`.

I tried pushing to the fork `master` branch again now that I'm on the Beta programme but I still get the same error message.

Do you know whether I need to change any settings on my forked repo to enable/configure GitHub Actions?

**Comment by mkArtakMSFT** [comment]
@adrianwright109 do the changes you're trying to push, by any chance, include anything from the `.github` folder?

**Comment by adrianwright109** [comment]
My fork is (at the time of writing this comment) 28 commits behind `aspnet:master`.  I'm trying to push those commits to my fork so that it is even with `aspnet:master`.

If I compare the changes that are pending to be pushed with the current status of the fork, there are new file(s) that have been added to the `.github` folder by yourself.
![image](https://user-images.githubusercontent.com/47532258/67188755-edd89d00-f3e4-11e9-9e74-34b3ba9fee1d.png)

**Comment by adrianwright109** [comment]
I have managed to work around the issue by deleting my `AspNetCore` fork and local git repo folder.

After deleting those I then re-forked `AspNetCore` and re-cloned it locally.

I can now push commits from `AspNetCore` `master` branch to my forked `master` branch.

Looks like GitHub has the permissions to create the `.github` folder when forking but not when the user tries to push commits to that folder.

This has worked for me - might not work for everyone especially if they have work in progress that they don't want to lose by deleting their fork and local git repo folder.

**Comment by mkArtakMSFT** [comment]
Glad that it worked out, @adrianwright109. Took some time but now we know how to help others who may be facing something similar in the future!
