### ISSUE TITLE
Angular SpaServices hosted in Docker container refresh at runtime

### ISSUE THREAD

**Issue by clintsinger** [aspnet/AspNetCore#15129]
I have a solution with a docker-compose project it in and a number of services.   One of the services is an Angular 8 project created via the SPA template for Angular and then Dockerfile support added afterwards.   

I am able to run the project and see that it is working by going to the URI that is published by Docker.  When I make a change to the Angular source in ClientApp/ I would expect that the change is detected and refreshed like it does when not in a Docker environment.  

The /app directory in the Container is mapped to the correct directory on the host machine.  So, I can verify that when I make a change I can run 'cat' on file from within the Container shell and see that there is a change. 

Even if I refresh the browser it doesn't get picked up.  I can only get the change if I stop the application and re-run it.

I would love to see this get some first class support.  

### Additional context
 dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by javiercn** [comment]
Thanks for contacting us @clintsinger 

Can you include your Dockerfile? If you are using the standard Dockerfile that our tooling generates, what happens is that the application is built and published into the container at which point there is no link between your development files and the files the app uses when running.

If you wanted to achieve your scenario, you would need to start an image of the SDK with paths and port mappings to your project and then, with that container running, attach to it to run your application in Development mode with `dotnet run`. (Which is somewhat similar to what the visual studio tooling does today).

There is nothing we can do in ASP.NET Core to support this.
