### ISSUE TITLE
SignalR connection fails over web sockets when access token is used

### ISSUE THREAD

**Issue by videege** [aspnet/AspNetCore#15132]
### Describe the bug
I am using ASP.NET Core 3 locally (hosted in IIS Express) and I am trying to use web sockets from a JS client to connect to my SignalR hub.  When I do not attach an access token to the request, the connection succeeds and my hub is functional.  When I specify an access token (via the `accessTokenFactory` option client-side), the connection to the hub fails with the error:

`WebSocket connection to 'wss://localhost:44351/hubs/sample?access_token=<token_here>' failed: Error during WebSocket handshake: Unexpected response code: 404`

I am following the guidance [in the documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.0#authorize-users-to-access-hubs-and-hub-methods) as to setup.

### To Reproduce
1. Using ASP.NET Core 3
2. Using this configuration server side:
```
// In ConfigureServices
services.AddSignalR(options => { options.EnableDetailedErrors = true; });
// In Configure (complete ordering shown)
app.UseForwardedHeaders(new ForwardedHeadersOptions()
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
if (!env.IsDevelopment())
{
    app.UseSpaStaticFiles();
}

app.UseRouting();
app.UseCors("CORSPolicy");

app.UseAuthentication();
app.UseAuthorization();

app.UseEndpoints(endpoints =>
{
    endpoints.MapHub<MyHub>("/hubs/sample");

    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller}/{action=Index}/{id?}");
});

app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint($"/swagger/v1/swagger.json", "API");
    c.OAuthClientId("clientapp");
    c.OAuthScopeSeparator(" ");
    c.ShowExtensions();
});

app.UseSpa(spa =>
{
    // To learn more about options for serving an Angular SPA from ASP.NET Core,
    // see https://go.microsoft.com/fwlink/?linkid=864501

    spa.Options.SourcePath = "ClientApp";

    if (env.EnvironmentName.Contains("Local"))
    {
        spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
    }
});
```
3. And this configuration client-side:
```
this.hubConnection = new HubConnectionBuilder()
  .withUrl('/hubs/sample',
    {
      skipNegotiation: true,
      transport: HttpTransportType.WebSockets,
      accessTokenFactory: () => accessToken
    }
  )
  .withAutomaticReconnect()
  .configureLogging(LogLevel.Information)
  .build();
```

### Expected behavior
I expect the connection to succeed.

### Additional context
Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by BrennanConroy** [comment]
In the documentation you referenced there is some custom auth logic needed in order to grab the "access_token" and make use of it. Could you share your custom auth logic? I'm assuming something in there is causing the 404.

**Comment by videege** [comment]
My server side handler is this, but it is never even executed when the auth token is passed from the client:

```
services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options =>
{
    options.Authority = Settings.AppSettings.Authentication.Authority;
    options.Audience = Settings.AppSettings.Authentication.Audience;
    options.RequireHttpsMetadata = false;
    options.Events = new JwtBearerEvents
    {
        OnMessageReceived = context =>
        {
            // Read the access token from the query string if the user is trying to
            // connect to a SignalR hub
            var accessToken = context.Request.Query["access_token"];
            var path = context.HttpContext.Request.Path;
            if (!string.IsNullOrWhiteSpace(accessToken) &&
                path.StartsWithSegments("/hubs"))
            {
                context.Token = accessToken;
            }
            return Task.CompletedTask;
        }
    };
});
```

**Comment by videege** [comment]
Also this only appears to happen with web sockets - if I loosen the restriction, I get the same 404 error on first attempt but then the fall back to long polling works fine and I receive the token properly.

**Comment by videege** [comment]
OK, I figured out the issue... the query string was too long for IIS Express to accept once the token was added in.  I needed to add a web.config increasing the max size past 2048.
