### ISSUE TITLE
Blazor WebAssembly not working in safari

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#15148]
### Describe the bug
Blazor webassembly samples are not working in latest safari browser v13.x. But it is working fine on safari v12.1.1. 

Any suggestions for this?

### To Reproduce
1. Create the blazor webAssembly sample
2. Run it 
3. Open it in safari browser v13.x

### Expected behavior
Needs to be working properly

### Additional context
I have used .net core sdk 3.0 and vs 2019 16.4 preview 1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kmuthukumar23.
This is a known mono issue which is being tracked at: https://github.com/mono/mono/issues/16986

**Comment by GoranHalvarsson** [comment]
How is the status on this one? Latest preview "3.1.0-preview3.19555.2" still not working on Safari
