### ISSUE TITLE
Can't get dynamic json data 

### ISSUE THREAD

**Issue by magicdict** [aspnet/AspNetCore#15141]
### Describe the bug
Can't get dynamic json data 

### To Reproduce
```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddDistributedMemoryCache();

            services.AddSession(options =>
            {
                // Set a short timeout for easy testing.
                options.IdleTimeout = TimeSpan.FromSeconds(600);
                options.Cookie.HttpOnly = true;
                // Make the session cookie essential
                options.Cookie.IsEssential = true;
            });

            services.AddMvc(MvcOptions =>
            {
                MvcOptions.EnableEndpointRouting = false;
            });
        }
```

```csharp
    public partial class DailyController : ControllerBase
    {
        [HttpPost("workloadSignature")]
        public string WorkloadSignature(dynamic data)
        {
            //var JSE = base.HttpContext.Session.GetString("JSE");
            var JSE = data.JSE;
            var client = new HttpClient();
            client.BaseAddress = new Uri(WebApiHelper.urlbase_Dev);
```

### Expected behavior
NetCore3.0-Preview Version: json string can direct use by data.xxx 
NetCore3.0 Version:

发生异常: CLR/Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
An exception of type 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' occurred in System.Linq.Expressions.dll but was not handled in user code: ''System.Text.Json.JsonElement' does not contain a definition for 'JSE''
<Cannot evaluate the exception stack trace>

### Screenshots
![image](https://user-images.githubusercontent.com/897796/67073087-dfa63900-f1b8-11e9-9d53-e83b794864fd.png)

![image](https://user-images.githubusercontent.com/897796/67073117-ec2a9180-f1b8-11e9-8c6d-aa3b4ce0bc09.png)

### Additional context
Include the output of `dotnet --info`

**Comment by msmolka** [comment]
Default json serializer in .net core 3 is System.Text.Json. This one is not supporting dynamic object yet
see: https://github.com/dotnet/corefx/issues/38007

switch to Json.Net

**Comment by pranavkm** [comment]
@magicdict I haven't verified, but it's likely that System.Text.Json would deserialize your `dynamic` parameter as a [`JsonElement`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement?view=netcore-3.0) instance. You might be able to modify your code to use it. If you continue needing the fidelity from 2.2, consider using Newtonsoft.Json based formatters: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support
