### ISSUE TITLE
Linking an authentication scheme to a different login page

### ISSUE THREAD

**Issue by Aaronmsv** [aspnet/AspNetCore#15143]
Hello,

I am working with multiple authentication schemes in my ASP.NET Core 2.2 application and I would like to use a different login page for one specific authentication scheme.  This authentication scheme is an external login provider.

The secondary login page is working fine, however the issue is that when the cookie expires, the user is should be redirected to this secondary login page if they used that one to login.

What I tried to do is setup a second cookie, with a different `LoginPath`:

```
            services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.Name = "main_cookie";
                options.LoginPath = new PathString("/MainLogin");
                options.AccessDeniedPath = new PathString(/MainLogin");
            });

            services.AddAuthentication().AddCookie("secondaryCookie", options =>
            {
                options.Cookie.Name = "secondary_cookie";
                options.LoginPath = new PathString("/SecondaryLogin");
                options.AccessDeniedPath = new PathString("/SecondaryLogin");
            });
```

Then when I'm registering the `AuthenticationSchemeOptions` of my authentication scheme, I'm using the second cookie as the `SignInScheme` to try and link it to the correct login page:

```
            var options = new CustomOAuthOptions()
            {
                ClientId = clientId,
                ClientSecret = clientSecret,
                SignInScheme = "secondaryCookie",
            };
```

However, when I now try to sign in, the `SignInManager.GetExternalLoginInfoAsync` returns `null`. It looks like this is hardcoded to use `IdentityConstants.ExternalScheme`.

What can I do to fix this, or is there a better way of achieving this?

**Comment by Tratcher** [comment]
> however the issue is that when the cookie expires, the user is should be redirected to this secondary login page if they used that one to login.

After the cookie expires the user becomes anonymous and there is no way to tell which login page they should be sent to. Unless that decision is linked to which pages they visit?

**Comment by Aaronmsv** [comment]
Hmm, no it is not related to the pages. I'll try to find another solution then.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
