### ISSUE TITLE
CheckPasswordSignInAsync raise an error when lockoutOnFailure is true

### ISSUE THREAD

**Issue by ste4net** [aspnet/AspNetCore#15153]
This error does not occur on 2.x releases.
I'm using Identity with custom TUser class
...
`public class MyContext : IdentityDbContext<ApplicationUser, UserRole, long>`
...
 
Calling CheckPasswordSignInAsync return an error if (and only if) lockoutOnFailure =true

_The instance of entity type 'ApplicationUser' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked._

Entries in my ChangeTracker are really two entry for same user.
This error does not occour passing false to lockoutOnFailure

**Comment by blowdart** [comment]
@HaoK

**Comment by HaoK** [comment]
Can you clarify what this means? "Entries in my ChangeTracker are really two entry for same user."

**Comment by ste4net** [comment]
@HaoK  Yes sorry. I mean this:

```
          try{
                ...
                var res = await _signinManager.CheckPasswordSignInAsync(usr, password, false);
                ...
            }
            catch (Exception ex)
            {
                //Debug here the content of MyDbContext.ChangeTracker.Entries()
            }
```
 
The reported error is raised calling CheckPasswordSignInAsync and If i check the content of Ef Core Context changeTracker i see two User entities with same key. There seems to be a procedure that loads two time the user entity and than try to do an update.

**Comment by HaoK** [comment]
Are you doing anything else with the user/multiple users in this request?  Why do you have two user entries with the same key is the main question?

**Comment by ste4net** [comment]
Yes but it seems that both entity has been loaded by signinmanager.
I reat that entty too at the beginning of request but i read it wth AsNotracking() ( avoiding to have it tracked by EFCore).
I made this test...
var res = await _signinManager.CheckPasswordSignInAsync(usr, password, false);
After this call there are no items in ChangeTracke.
var res = await _signinManager.CheckPasswordSignInAsync(usr, password, **true**);
Using this one there two entries (with same key) in ChangeTracker.

Calling

**Comment by HaoK** [comment]
Can you post the full contents of the relevant code running that's causing this error?

**Comment by HaoK** [comment]
Feel free to reopen this if this is still an issue and you have a repro for us to look at
