### ISSUE TITLE
Unable to read appsetttings.json files without explicitly specifying.

### ISSUE THREAD

**Issue by ezikialbasix** [aspnet/AspNetCore#15154]
Hi,

I'm trying to run a web api, migrated from 2.2 to 3.0.  I've made the requested changes.  However, I am unable to get the configuration to read the appsettings.json files unless i specifically use AddJsonFile.  Everything else is running smoothly.

**What should work:**
```
var host = new HostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseKestrel(options => 
                            { options.ListenAnyIP(5002); })
                        .UseStartup<Startup>();
                })
                .Build();
            
            host.Run();
```

**What I have to do to read the config:**
```
var host = new HostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseKestrel(options => 
                            { options.ListenAnyIP(5002); })
                        .UseStartup<Startup>();
                    webBuilder.ConfigureAppConfiguration((hostingContext, config) =>
                    {
                        config.SetBasePath(Directory.GetCurrentDirectory());
                        config.AddJsonFile(
                            "appsettings.Development.json", optional: true, reloadOnChange: true);
                    });
                })
                .Build();
            
            host.Run();
```

I have double checked the files are in the correct location.  I've tried just having SetBasePath, but to no avail, I can't get it to read it.

I have per-environment settings as well as the default appsettings as well.

Any ideas how to resolve this?

**Comment by ezikialbasix** [comment]
Sorry to be more clear, the environment based ones are not working.

**Comment by Tratcher** [comment]
Replace `new HostBuilder()` with `Host.CreateDefaultBuilder(args)`. The generic and web specific defaults were split, and config is part of the generic defaults.

**Comment by ezikialbasix** [comment]
Thanks! That worked.  I was following the following documentation, and it has both ways exampled:

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio
