### ISSUE TITLE
VS 2019 chrash in blazor/razor file when remove <div> statment without first removing </div>

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#15167]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/653871/vs-2019-chrash-in-blazorrazor-file-when-remove-sta.html)._

---
If I remove the  &lt;div class=&quot;checkbox&quot;&gt; statment without first removing the &lt;/div&gt; statment the vs2019 chrash and restart.
It does not happen in other razor files in the same project - only in this file - so I send the hole file. It also happen when I remove 
 other &lt;div......&gt; statment in same file.

&lt;div class=&quot;checkbox&quot;&gt;
                        &lt;input type=&quot;checkbox&quot; value=&quot;&quot; checked&gt;
                        &lt;label&gt;
                            @if (@felt. Required == true)
                            {
                                &lt;label style=&quot;color:red&quot;&gt;*&lt;/label&gt;
                            }
                            @felt. FieldHeading
                        &lt;/label&gt;
                    &lt;/div&gt;

---
#### Visual Studio Feedback System on 7/21/2019, 11:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/22/2019, 10:22 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
@NTaylorMullen I believe this is right up your alley.

**Comment by NTaylorMullen** [comment]
No longer reproduces. We had a lot of bugs back in 16.2 where one of them most likely fixed this.
