### ISSUE TITLE
Asp.net core 3 not compatible with NetStandard 2.0 libraries ?

### ISSUE THREAD

**Issue by anna-git** [aspnet/AspNetCore#15179]
### Asp.net 3.0 referencing a .net standard 2.0 library with a dependency on Microsoft.AspNetCore.Mvc.Core 2.2.5 is crashing. Not retrocompatible.
Unless I'm mistaken, according to [The .net implementation support](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), Asp.net Core 3 apps are supposed to work with netstandard 2.0 libraries.  
But for example, at runtime:
> TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Formatters.Internal.MediaTypeSegmentWithQuality' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Of course, the .net standard library is looking for a type that changed namespace in between asp.net core 2.. and 3. But how can it still compile though?

### To Reproduce
[https://github.com/anna-git/AspNetCore3NotCompatibleWithNetStandard2](https://github.com/anna-git/AspNetCore3NotCompatibleWithNetStandard2)

### Expected behavior
I don't even understand how it can still compile, because the type MediaTypeSegmentWithQuality has changed namespace in between... (not internal anymore)

**Comment by davidfowl** [comment]
This particular dependency is incompatible between asp.net core 2.2 and 3.0. It has nothing to do with netstandard

**Comment by pranavkm** [comment]
Thanks for the issue report @anna-git. As announced in https://github.com/aspnet/Announcements/issues/326, types in the `.Internal` namespace were shuffled around. This was a breaking change and requires library to be recompiled. 

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio has instructions on re-targeting your projects to `netcoreapp3.0` as well as cross-compiling libraries.
