### ISSUE TITLE
In server Blazor App, circuit gets broken when using Windows Authentication and a service is initiating the change.

### ISSUE THREAD

**Issue by MarcDavid2K** [aspnet/AspNetCore#15180]
### Describe the bug
When trying to have a service update a Blazor App state like in the Notifier example in the documentation, if I am using Windows Authentication the circuit get broken and the page does not update.  If I am using anonymous authentication the page works as expected.  This happens with IIS Express and IIS Profiles.

### To Reproduce
Steps to reproduce the behavior:  Using the attached BlazorApp2.zip file for source and screenshots
1. Using .Net Core 3.0, I built a Blazor Server App with Windows Authentication ( see attached zip )
2.  I added some logging to help debug, a Notifier Service, and a test.razor to illustrate
3.  Run the App under IISExpress or IIS configurations
3.  Go to the /Test page and notice that the page doesn't change.
4.  Stop the App and Enable Anonymous Authentication ( optionally disable windows authentication )
5.  Run the App under IISExpress or IIS configuraitons
6.  Go to the /Test page and notice that the page does change once a second as it should.

### Expected behavior
The NotifierService runs a task that will Update the state once a second and the Test.razor handles the notification and calls StateHasChanged which updates the page with **Last update: guid = count**.  I expect that under windows authentication that the App behave as described which is how it behaves under anonymous authentication.  My real App requires me to use Windows Authentication

### Screenshots
In zip I added a not_working.png that shows how the page remains and a working.png that shows the page with some data.  Note the working page changes once a second.

### Additional context
I'm using visual studio 16.3.5
and here's my dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
[BlazorApp2.zip](https://github.com/aspnet/AspNetCore/files/3746027/BlazorApp2.zip)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MarcDavid2K.
@SteveSandersonMS can you please look into this? Thanks!

**Comment by MarcDavid2K** [comment]
FWIW I tried the same code on 3.1 preview 1 and it behaved the same.  Let me know if I can provide any assistance.

**Comment by MarcDavid2K** [comment]
While looking into the issue I discovered an article where someone was having a similar issue.  In that case it turned out to be they were using the Brave Browser ( same as me ), in that case the work around was to modify the Brave Shields.  For my issue I tried disabling the Brave shields completely and that did not help.  I've tested the issue now with Edge, Chrome, and Firefox and they all work as expected.  Now that I know I can move forward with my actual project but it would be nice if Brave did not have this issue or if there was some indication as to what was happening.  From the article I discovered they claim the issue could come from ad blocker plugins as well, I did not test that.

**Comment by SteveSandersonMS** [comment]
@MarcDavid2K From what I can tell, the Brave browser simply doesn't support Windows authentication: https://github.com/brave/brave-browser/issues/3734

As such this doesn't seem like something we could take action on.

Do you have any reason to think there's some fault inside Blazor or ASP.NET Core here? If so, can you clarify what?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
