### ISSUE TITLE
Blazor: ElementReference cannot be passed as a Parameter

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/AspNetCore#15187]
### Describe the bug
When trying to pass an ElementReference as a parameter to a component, the Id of the reference is not set.

Because the parameter is passed before rendering, but the ElementReference is not valid until after the render, the Id passed is null.

The ElementReference Id changing should cause the child component's Parameters to be set again. 

### To Reproduce
Index.razor
```
@page "/"

<input value="A" class="form-control" />
<input value="B" class="form-control" @ref=PageOneFocusControl />
<input value="C" class="form-control"/>
<AutoFocus Control=PageOneFocusControl @ref=MyAutoFocus/></br/>
Reference = @PageOneFocusControl.Id
<button type="button" @onclick=@SetTheReferenceManually>Set the reference manually</button>

@code {
	ElementReference PageOneFocusControl;
	AutoFocus MyAutoFocus;

	private void SetTheReferenceManually()
	{
		MyAutoFocus.SetControl(PageOneFocusControl);
	}
}
```

AutoFocus.razor
```
@inject IJSRuntime JSRuntime
@code {
	[Parameter]
	public ElementReference Control { get; set; }

	public void SetControl(ElementReference control)
	{
		Control = control;
	}

	protected override void OnParametersSet()
	{
		System.Diagnostics.Debug.WriteLine("=============OnParametersSet===========");
		if (string.IsNullOrEmpty(Control.Id))
			System.Diagnostics.Debug.WriteLine("Control.Id is NULL");
		else
			System.Diagnostics.Debug.WriteLine("Control.Id is SET CORRECTLY!!!");
	}
}
```

1: Run the app (Client-side blazor app)
2: Note the Id displayed on screen has no value
3: Note the output in the browser console says Control.Id is NULL
4: Click the button to set the parameter manually
5: The Id now displays correctly and the output in the browser console says Control.Id is SET CORRECTLY

**Comment by javiercn** [comment]
@mrpmorris Thanks for contacting us.

I believe that's by design. ElementReference instances are only valid after the component in which they are defined has been rendered. If you pass them down to child component I believe there's no guarantee they'll work correctly, as in Blazor components render independently (A parent re-rendering doesn't mean a child re-renders) so you can't know from the child component whether the reference is correct or not.

To achieve your scenario, it would make more sense to simply perform a JS Interop call inside the OnAfterRenderAsync method of the parent component to set the focus to the desired form control.

**Comment by mrpmorris** [comment]
I know it is by design, the important part of my report was

"The ElementReference Id changing should cause the child component's Parameters to be set again."

**Comment by javiercn** [comment]
> "The ElementReference Id changing should cause the child component's Parameters to be set again."

That is not how the Blazor rendering model works. 

The component is responsible to tell Blazor when it needs to be rerendered. Blazor doesn't proactively look for changes in the component state/model to decide when a component needs to be re-rendered.

**Comment by mrpmorris** [comment]
I realise that, that's why I said the child component's Parameters should be set again.

Whatever the solution is, passing element references as parameters currently does not work.

If it is chosen to not be supported, then perhaps a compiler warning should be raised when a [Parameter] ElementReference is declared.
