### ISSUE TITLE
Blazor: Change a default binding via BindAttributes.cs 

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#15189]
According to BindAttributes.cs it is possible to extend it:

```
   /// <remarks>
    /// To extend the set of <c>bind</c> attributes, define a public class named
    /// <c>BindAttributes</c> and annotate it with the appropriate attributes.
    /// </remarks> 
```

I was looking for an easy way to change the default binding for text from onchange to oninput globally in my application.

So I did this:

```
    [BindInputElement("text", null, "value", "oninput", isInvariantCulture: false, format: null)]
    public static class BindAttributes
```

However, this is not working. Is it supposed to work?  

If not, what approach you suggest to change one of the default bindings globally?

**Comment by javiercn** [comment]
@Postlagerkarte Thanks for contacting us.

I believe using `BindAttributes` only allows adding additional bindings, but not modify existing ones.

@SteveSandersonMS or @rynowak can confirm.

**Comment by SteveSandersonMS** [comment]
Yes, we don't have a feature of changing the defaults. The recommended approach for this is to define your own "input" component that uses whatever conventions you want, and then use that instead of a plain `<input>` element.
