### ISSUE TITLE
dotnet new mvc does not work, because System.Collections.Immutable 1.6 cannot be found

### ISSUE THREAD

**Issue by mudrz** [aspnet/AspNetCore#15199]
### Describe the bug
Creating a new ASP.NET project with the built in template generator does not work, because `System.Collections.Immutable` version `1.6.0` cannot be found in nuget -> the project dependencies cannot be restored

### To Reproduce
1. Run
```
dotnet new mvc --auth individual --output zz
```
2. See error
```
The template "ASP.NET Core Web App (Model-View-Controller)" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/3.0-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on zz/zz.csproj...
/Users/mudrz/Projects/asptests/zz/zz.csproj : error NU1102: Unable to find package System.Collections.Immutable with version (>= 1.6.0)
/Users/mudrz/Projects/asptests/zz/zz.csproj : error NU1102:   - Found 26 version(s) in nuget.org [ Nearest version: 1.6.0-preview4.19212.13 ]
  Restore failed in 1.96 sec for /Users/mudrz/Projects/asptests/zz/zz.csproj.

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

### Expected behavior
I expect that project dependencies would install

### Additional context
Manually running `dotnet restore` results in the same error
<img width="671" alt="image" src="https://user-images.githubusercontent.com/9587050/67155271-701a8000-f357-11e9-983c-f8b324e60ddc.png">

Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@mudrz Thanks for contacting us.

This is likely an issue with your environment. I would try a few things:
* Check your nuget package restore sources.
* Clean your nuget package caches and run `dotnet restore`.
* If none of those things work, I would recommend you open an issue in https://github.com/nuget/home as they will be in a better position to help you.
* I can see the package available on nuget here https://www.nuget.org/packages/System.Collections.Immutable/1.6.0
