### ISSUE TITLE
since asp net core I can't publish my web application in iis

### ISSUE THREAD

**Issue by Richardsan77** [aspnet/AspNetCore#15197]
I have a web application developed in asp net core that works for me locally, I want to publish it in iis to be able to access it and develop an app in xamarin, but when I publish it I get an error that the web.config file has an xml that has no format, I hope can you help me, I use asp net core yc #, database in sql server

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Richardsan77.
Are you experiencing this with any application?
Please share a repro project as well as provide details about what error you're getting.

**Comment by javiercn** [comment]
We are closing this issue as there has been no community involvement in the past few days. If new information is provided we might be able to provide a resolution.
