### ISSUE TITLE
Hotreload with Mvc project

### ISSUE THREAD

**Issue by TangMonk** [aspnet/AspNetCore#15201]
Hotreload is necessary for development a web application for reduce wating the recompile time, using `dotnet watch run` is still slowly

**Comment by javiercn** [comment]
@TangMonk thanks for contacting us.

For C# code you can use `dotnet watch run`, for razor pages you can use runtime compilation as described in 
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0

**Comment by TangMonk** [comment]
@jodavis  is it works with asp.net mvc ?
