### ISSUE TITLE
Question: Apply Authorization by default in Blazor server-side

### ISSUE THREAD

**Issue by sven5** [aspnet/AspNetCore#15217]
Hi,

is there any way to configure Authorization by default in Blazor?
For MVC we used to use this:
```
 services.AddMvc(o =>
    {
        var policy = new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .Build();
        o.Filters.Add(new AuthorizeFilter(policy));
    });
```

Thanks
Sven

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sven5.
Here how you can achieve that:
```csharp
 app.UseEndpoints(endpoints =>
    {
        endpoints.MapBlazorHub().RequireAuthorization();
    });
```

Source: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#authorization
