### ISSUE TITLE
Several migration issues

### ISSUE THREAD

**Issue by maxmantz** [aspnet/AspNetCore#15216]
Hi,

after upgrading from 2.2 to 3.0, my Web API has several issues seemingly regarded to conventions changed in version 3.0 which I couldn't find a reference to in the migration docs.

General info:
All my controllers are based on a custom `ApiControllerBase` with this code:
```
    [ApiController]
    public abstract class ApiControllerBase : ControllerBase
    {
    }
```
My expectation is that all controllers which descend from this base controller have standard API controller behavior.

These are my issues:

### GET request routing returns status 400 `A non empty request body is required`

Source: 
```
        [HttpGet]
        [Route("{id}")]
        public async Task<TaskModel> GetByIdAsync(int id, IList<string> extend = null)
        {
            return await _service.GetByIdAsync(id, extend);
        }
```
This happens because the controller interprets the `extend` parameter to be contained in the request body. In version 2.2, this was correctly interpreted as a query parameter.
My question: This is a GET request. A GET request shouldn't have a body. Why does this error occur?

### Unauthorized users get redirected to the login page
On API controllers, unauthorized users get redirected to the login page when unauthorized, HTML markup is returned with a 200 code. Why aren't 401 responses sent instead?

Thanks for your help!

**Comment by blowdart** [comment]
_On API controllers, unauthorized users get redirected to the login page when unauthorized, HTML markup is returned with a 200 code. Why aren't 401 responses sent instead?_

What authorization are you using?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @maxmantz.
For the `ApiController` marked controllers the complex and collection type parameters are automatically expected to be coming `FromBody`. This behavior was behind a compat flag in 2.2, which in case if you haven't been using it, may come up as a breaking change for you.
You can force this to work the way you want by decorating these parameters with `[FromQuery]` attribute explicitly.

**Comment by maxmantz** [comment]
@blowdart I'm using IdentityServer4, so this could be related to the usage of that library and not to AspNetCore. I will investigate this further,

@mkArtakMSFT Thanks for your pointers to the solution. This will fix it for me.
