### ISSUE TITLE
In ie9 the console tell the problems: uint8array undefine

### ISSUE THREAD

**Issue by a14907** [aspnet/AspNetCore#15215]
### Describe the bug
As the signalr promise when wesocket is not enable,the longpolling may work. So I do a test. I use ie9 to visit my demo website. And the problems happen.

### To Reproduce
1. use ie9 to visit the demo visite
2. See error in console

### Expected behavior
I expect no err

what can I do for this problem! Any advice?

**Comment by blowdart** [comment]
IE9 is [out of support.](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support). We won't be doing anything to support it.

**Comment by a14907** [comment]
polyfills
can support uint8array in ie9

**Comment by a14907** [comment]
I think if uint8array is not support in browser ,websocket may not support too.Signal may choose longpolling. But signalr.js will not work, because uint8array is undefine... so signalr is not support longpolling...Weird!!!
