### ISSUE TITLE
RefreshSignInAsync in Blazor throws headers related exception

### ISSUE THREAD

**Issue by cesee** [aspnet/AspNetCore#15210]
### Describe the bug

After updating the user claims, I wanted to refresh the object through RefreshSignInAsync, however this throws an exception since it probably is trying to update the cookies.

> The response headers cannot be modified because the response has already started

### To Reproduce
In a  Blazor server app, call `SignInManager.RefreshSignInAsync` from any method after the app is loaded and the user has signed in.

### Expected behavior
To not throw an error and to refresh the the sign in data including claims.

**Comment by javiercn** [comment]
@cesee Thanks for contacting us.

@SteveSandersonMS @HaoK I believe this is because the method is being called outside the request context. Should RefreshSignInAsync work in that scenario?

**Comment by cesee** [comment]
The first time I encountered a similar problem (trying to write a culture cookie), I managed to work around this problem using JSInterop. Cookies seem to be a pain in blazor...

**Comment by javiercn** [comment]
@cesee You can't rely on HTTP features as a general rule in server-side Blazor. It is powered by SignalR and there's a reasonable chance you don't have access to a working HTTP context in many situations.

WRT to SignInManager.RefreshAsync I'll let @HaoK and @SteveSandersonMS comment.

**Comment by HaoK** [comment]
Yeah RefreshAsync is basically working against the http context, it calls authenticate and then sign in using the identity application cookie

**Comment by cesee** [comment]
> Yeah RefreshAsync is basically working against the http context, it calls authenticate and then sign in using the identity application cookie

Ok. So you confirmed the reason (I wrote it in the initial report). What is the fix/alternative ?
