### ISSUE TITLE
Razor Intellisense Issues In VS 2019 (v16.1.6 & .net core v3 Preview 7)

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#15226]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/661773/razor-intellisense-issues-in-vs-2019-v1616-net-cor.html)._

---
Hi,

I have a clean install of VS 2019 (16.1.6) and am using .net core 3 Preview 7, when i create a standard Blazor (Server-Side) project.  i can see all of the .razor files within &quot;Shared&quot; and &quot;Pages&quot;. I have also experianced this with v3 Preview 6, i have also tried to use VS 16.2 Preview 4 and have the exact same problem.  I am on a clean Windows 10 Enterprise build which is fully patched.

However when i open them up i am presented with a slew of errors within the &quot;Error List&quot; and Intellisense also refuses to work at all on any of the existing or new pages.  This is making life extreamly hard when trying to develop the UI since i cant use intellisense and its hard to tell when i write bad/wrong code since the entire editor is a sea of red skwiggly lines.

I should point out that the attached example page compiles and works.

---
#### Christopher.Thomas1 on 7/26/2019, 01:09 AM: 

I have also tried the following but the problem still persists:<br><br>+ Ensured all VS updates (including extensions have been applied)<br>+ Upgraded icrosoft.codeanalysis.analyzers Updated from 2.6.2 to 2.9.3<br>+ Installed the "Microsoft Code Analysis 2019" v 3.0.0.1925803 package<br>+ Upgraded Microsoft.Net.Compilers to v3.1.1<br>+ Installed/Upgraded Microsoft.CodeDom.Providers.DotNetCompilerPlatform to v2.0.1<br>+ Reset VS settings to defaults<br>+ deleted Obj & Bin from project folder<br>+ tried CTRL+SHIFT+R (refresh intellisense)<br><br>and the last exreame measure..<br><br>+ Uninstalled & Re-Installed VS 2019 v16.1.6 & .net core v3 Preview7
#### Visual Studio Feedback System on 7/26/2019, 05:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/28/2019, 10:27 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please update to the latest VS 2019 release as well as the .Net Core 3.0 RTM release. If you will still have the same issue, please provide us with a repro project, so we  can investigate it further.

**Comment by huzaynbolt** [comment]
@mkArtakMSFT the issue still exist as pointed out, In my own case the red skwiqlly lines disappers when I disable Resharper but no Intellisense whatsoever.

Visual Studio 2019 16.3.6
Dot Net 3.0.100

**Comment by NTaylorMullen** [comment]
Can't reproduce
