### ISSUE TITLE
File validation issues

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#15221]
This issue will be used to collect all info related to the verification data for **3.1.0-Preview 2** release:

Build to use: daily build from https://github.com/dotnet/core-sdk#installers-and-binaries
If you plan to create any Azure resources specifically for the verification work, please create those in the **3.1-p2-validation** resource group, in the **ASP.NET Core Test** subscription.

Make sure to create the issues in aspnet/AspNetCore repo and apply the proper area label and `Validation` label. Put the issue in `3.1.0-preview2` milestone.

After you create the issues, add them to the https://github.com/aspnet/AspNetCore/projects/4 project and unassign yourself from this issue.

**Comment by dougbu** [comment]
Nothing in build area should be user-visible and we didn't change OpenAPI glue in this release.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/AspNetCore/issues/15233
https://github.com/aspnet/AspNetCore/issues/15232
https://github.com/aspnet/AspNetCore/issues/15231
https://github.com/aspnet/AspNetCore/issues/15230
https://github.com/aspnet/AspNetCore/issues/15229

**Comment by ryanbrandenburg** [comment]
https://github.com/aspnet/AspNetCore/issues/15250
https://github.com/aspnet/AspNetCore/issues/15249

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/issues/15239
https://github.com/aspnet/AspNetCore/issues/15237
https://github.com/aspnet/AspNetCore/issues/15236
https://github.com/aspnet/AspNetCore/issues/15235
https://github.com/aspnet/AspNetCore/issues/15221

**Comment by pranavkm** [comment]
https://github.com/aspnet/AspNetCore/issues/13777
https://github.com/aspnet/AspNetCore/issues/14110
https://github.com/aspnet/AspNetCore/issues/14653
https://github.com/aspnet/AspNetCore/issues/14868
https://github.com/aspnet/AspNetCore/issues/14902
https://github.com/aspnet/AspNetCore/issues/15068
https://github.com/aspnet/AspNetCore/issues/15070
https://github.com/aspnet/AspNetCore/issues/15071
https://github.com/aspnet/AspNetCore/issues/15122
https://github.com/aspnet/AspNetCore/issues/15162
