### ISSUE TITLE
How to insert a new line into a string in Blazor

### ISSUE THREAD

**Issue by enet-blazor** [aspnet/AspNetCore#15246]
The only way I can think of is using Razor templates. \r\n, Envirnoment.Newline, and anything else cannot make the compiler budge.

Here is a working solution using Razor Template:

    <p>@resultString</p>
    
    @code {
        RenderFragment resultString =  @<p>Series not found <br />Error message</p>;
                              
    }

It is OK to use it like this. Do you know how to do it with using Razor Templates.

Thanks in advance...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @enet-blazor.
The way you're using is is correct.

@NTaylorMullen do you have anything else to add here?

**Comment by NTaylorMullen** [comment]
Blazor tries to maintain the functionality of HTML. Meaning anything that would alter the display of HTML Blazor attempts to maintain; anything else, it reserves the capability to modify the underlying code.

@enet-blazor I don't fully understand the question I think. Are you hoping that `\r\n` would translate into `<br />` automatically behind the scenes for you?

**Comment by enet-blazor** [comment]
I just thought that '\r\n' would be translated to <br /> as is done in the Razor generated classes.  

In my search, I've realized that I can also use Markup just like this:

`MarkupString  resultString = (MarkupString) $"Series not found <br />Error message";`

 Many thanks...
