### ISSUE TITLE
How it possible to build this project?

### ISSUE THREAD

**Issue by a14907** [aspnet/AspNetCore#15257]
I use the latest version of visual studio to build the solution:Hosting. And from the fiddler I see many items which response with 404!!!
Is it possible to build this project? If it is impossible! Please make it clear . And write it is impossible to build in the readme file.

**Comment by javiercn** [comment]
@a14907 thanks for contacting us.

Can someone from @aspnet/build help here?

**Comment by dougbu** [comment]
@a14907 please let us know
- what branch are you trying to build?
- what are the exact errors?
- did you run `.\restore.cmd` in the repo root before opening the solution?
- did you start Visual Studio with `.\startvs.cmd` in the Hosting folder?

See also https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#building-in-visual-studio

**Comment by a14907** [comment]
1.master branch
2.here is the err log:
```
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
Detected JDK in C:\Program Files\Java\jdk1.8.0_121 (via JAVA_HOME)
  C:\Users\admun\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19462.4\tools\Tools.proj 的还原在 92.13 ms 内完 成。
dotnet-install: .NET Core Runtime version 5.0.0-alpha1.19517.2 is already installed.
dotnet-install: Adding to current process PATH: "D:\code\TT\001_src\AspNetCore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha1.19517.2/dotnet-runtime-5.0.0-alpha1.19517.2-win-x86.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha1.19517.2/dotnet-runtime-5.0.0-alpha1.19517.2-win-x86.zip
dotnet-install: Adding to current process PATH: "D:\code\TT\001_src\AspNetCore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
  对源“https://dotnetmyget.blob.core.windows.net/artifacts/roslyn/nuget/v3/flatcontainer/microsoft.netcore.app.ref/index.
  json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (502) 错误的网关。
  未能从“https://dotnetmyget.blob.core.windows.net/artifacts/roslyn/nuget/v3/flatcontainer/microsoft.net.compilers.toolset
  /3.4.0-beta1-19456-03/microsoft.net.compilers.toolset.3.4.0-beta1-19456-03.nupkg”下载包“Microsoft.Net.Compilers.Toolset.
  3.4.0-beta1-19456-03”。
  对“GET https://dotnetmyget.blob.core.windows.net/artifacts/roslyn/nuget/v3/flatcontainer/microsoft.net.compilers.tools
  et/3.4.0-beta1-19456-03/microsoft.net.compilers.toolset.3.4.0-beta1-19456-03.nupkg”的 HTTP 请求在 100000 毫秒后超时。
  对源“https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-tools/nuget/v3/flatcontainer/nuget.versioning/index
  .json”重试“FindPackagesByIdAsync”。
  对“GET https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-tools/nuget/v3/flatcontainer/nuget.versioning/in
  dex.json”的 HTTP 请求在 100000 毫秒后超时。
  未能从“https://dotnetmyget.blob.core.windows.net/artifacts/roslyn/nuget/v3/flatcontainer/microsoft.net.compilers.toolset
  /3.4.0-beta1-19456-03/microsoft.net.compilers.toolset.3.4.0-beta1-19456-03.nupkg”下载包“Microsoft.Net.Compilers.Toolset.
  3.4.0-beta1-19456-03”。
  对“GET https://dotnetmyget.blob.core.windows.net/artifacts/roslyn/nuget/v3/flatcontainer/microsoft.net.compilers.tools
  et/3.4.0-beta1-19456-03/microsoft.net.compilers.toolset.3.4.0-beta1-19456-03.nupkg”的 HTTP 请求在 100000 毫秒后超时。
D:\code\TT\001_src\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targ
ets(119,5): error : 未能从“https://dotnetmyget.blob.core.windows.net/artifacts/roslyn/nuget/v3/flatcontainer/microsoft.net
.compilers.toolset/3.4.0-beta1-19456-03/microsoft.net.compilers.toolset.3.4.0-beta1-19456-03.nupkg”下载包“Microsoft.Net.Co
mpilers.Toolset.3.4.0-beta1-19456-03”。
D:\code\TT\001_src\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targ
ets(119,5): error : 对“GET https://dotnetmyget.blob.core.windows.net/artifacts/roslyn/nuget/v3/flatcontainer/microsoft.n
et.compilers.toolset/3.4.0-beta1-19456-03/microsoft.net.compilers.toolset.3.4.0-beta1-19456-03.nupkg”的 HTTP 请求在 100000
毫秒后超时。
```
3.Yes I run the restore.cmd before I open the solution file.
4.yes

here is the screenshots in fiddler:
![image](https://user-images.githubusercontent.com/13792421/67391375-20df8400-f5d1-11e9-8a7d-11bdca7d49e4.png)

The fiddler is not the problem.The console log show the same thing,when Fiddler is close.

**Comment by dougbu** [comment]
We've seen a few reports of connectivity issues in various locations. I suggest double-checking your system's proxy settings or trying again when connected to a faster network. Worst case, you may need to download some of the larger packages manually to another sources folder and update the NuGet.config file in the repo root e.g.
``` xml
  <add key="sources" value="{folder containing downloaded packages}" />
```

**Comment by a14907** [comment]
> We've seen a few reports of connectivity issues in various locations. I suggest double-checking your system's proxy settings or trying again when connected to a faster network. Worst case, you may need to download some of the larger packages manually to another sources folder and update the NuGet.config file in the repo root e.g.
>   <add key="sources" value="{folder containing downloaded packages}" />

There is no proxy setting in my conputer! If  I want to download these packages what should I download? Is there a list of the packages ?

**Comment by pranavkm** [comment]
@a14907 the 404s are perfectly fine, that just indicates that the package isn't on a particular feed. The underlying issue seems to be timeouts downloading https://dotnetmyget.blob.core.windows.net/artifacts/roslyn/nuget/v3/flatcontainer/microsoft.net
.compilers.toolset/3.4.0-beta1-19456-03/microsoft.net.compilers.toolset.3.4.0-beta1-19456-03.nupkg.

Are you able to download this file using a browser?

**Comment by a14907** [comment]
Yes, I can download it in my browser.
