### ISSUE TITLE
Web API Formatter for Google.Protobuf

### ISSUE THREAD

**Issue by lkishor** [aspnet/AspNetCore#15252]
I am trying to use Protobuf with the .Net Core Web API project. So instead of returning JSON or XML, I want to handle request/send response in ProtoBuf.

### A solution would be
A Nuget Package that provides Formatter for Protobuf depending on Google.Protobuf.
An alternative solution exists [https://www.nuget.org/packages/WebApiContrib.Core.Formatter.Protobuf/](url), but it takes a very different approach to implementing Protobuf Models, using ProtoContract and ProtoMember.

While it is great to see gRPC support in .Net Core 3.0, Though support on Mobile Platform is still very limited. Protocol Buffers with Web API can provide a second-option to do contract-based data access.

**Comment by javiercn** [comment]
@lkishor thanks for contacting us.

@JamesNK I believe GRPC is the right thing to use here?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lkishor.
We don't have plans to do this in the near future. We will, however, monitor for similar asks and when we realize there is enough need for this, we will re-consider this.

**Comment by lkishor** [comment]
I agree that not enough devs are asking for this, though It would be great If you can point me in the right direction so that I be able to author Such a Nuget Package..

Basically I am looking for Generic code to De-serialize from Byte Array and Serialise to Byte Array in Google's Protobuf format.

It must be somewhere within the gRPC codebase, just not sure where..
Any help would be highly appreciated..

**Comment by davidfowl** [comment]
From a quick google search https://github.com/damienbod/AspNetCoreWebApiContribProtobufSample

**Comment by lkishor** [comment]
@davidfowl above example is based on [https://github.com/protobuf-net/protobuf-net](url), Which uses ProtoContract & ProtoMember classes to identify Protobuf supported Models.

I am asking for code to Serialize and Deserialize IMessage types generated by **Google.Protobuf.Tools** or **Grpc.Tools**.

I am using Grpc.Tools to generate my .cs files as explained here [https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md](url).
Now I looking for Generic Logic to Serialize and Deserialize these Types.
