### ISSUE TITLE
Server Side Blazor g.cs files / component compiler optimization, minification

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#15251]
When compiling a Blazor solution, the components get compiled to files with extension g.cs.
Inside those files there're razor components converted to a rendertree, the problem I found is that the rendertree is polluted with lots and lots of lines like these:

```
__builder.AddMarkupContent(81, "\r\n                        ");
__builder.AddMarkupContent(18, "\r\n                        ");
__builder.AddContent(31, "                                ");

```

I've checked out some of my components,  and these lines add an extra of up to 50% more calls to the builder, which is a lot.
  One example which I copied these lines from, had 172 calls to the builder from which 58 were only blank spaces and \r\n that don't change anything but I presume consume RAM and CPU for nothing useful in the final html output.

  ```
__builder.AddContent(155, "    ");
      __builder.CloseElement();
      __builder.AddMarkupContent(156, "\r\n    ");
      __builder.OpenElement(157, "div");
      __builder.AddAttribute(158, "class", "col-4");
      __builder.AddMarkupContent(159, "\r\n        ");
      __builder.OpenElement(160, "div");
      __builder.AddAttribute(161, "class", "card");
      __builder.AddMarkupContent(162, "\r\n            ");
      __builder.AddMarkupContent(163, "<div class=\"card-header\">\r\n                <h4>Log</h4>\r\n            </div>\r\n            ");
      __builder.OpenElement(164, "div");
      __builder.AddAttribute(165, "class", "card-body");
      __builder.AddMarkupContent(166, "\r\n                ");
      __builder.OpenComponent<Logger>(167);
      __builder.CloseComponent();
      __builder.AddMarkupContent(168, "\r\n            ");
      __builder.CloseElement();
      __builder.AddMarkupContent(169, "\r\n        ");
      __builder.CloseElement();
      __builder.AddMarkupContent(170, "\r\n    ");
      __builder.CloseElement();
      __builder.AddMarkupContent(171, "\r\n");
      __builder.CloseElement();
```

This is an example,  where probably more cpu & ram is consumed for generating white spaces and indentation than actual useful HTML for the browser, and this is an server side scenario could be a big waste in resources.

Regards!!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chrdlx.
We intentionally avoid minification because in many situations customers need to preserve every space they add.
