### ISSUE TITLE
InputSelect is not binding for byte in Blazor 

### ISSUE THREAD

**Issue by embayyub** [aspnet/AspNetCore#15256]
I make like that html List in blazor client-side:
```
<InputSelect @bind-Value="model.ByCountryId" class="form-control">
       @if (model?.Countries != null)
        {
             @foreach (var cnt in model.Countries)
              {
                    <option value="@cnt.Id">@cnt.Name</option>
               }
          }
 </InputSelect>
```
The code block is like that:
```
@code {

BrandModel model = new BrandModel();

protected override async Task OnInitializedAsync()
{
    model = new BrandModel
    {
        Id = 19,
        ByCountryId = 1,
        Countries = new List<ent.Country>
            {
                new ent.Country { Id = 1, Name = "Azerbaijan" },
                new ent.Country { Id = 2, Name = "Turkey" }
            },
        IsActive = true,
        Name = "Brand"
    };
}
```
Model structure is like that:
```
public class BrandModel
    {
        public short Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public byte ByCountryId { get; set; }

        public bool IsActive { get; set; }

        public IEnumerable<Country> Countries { get; set; }
    }
```
So during the execution of this code, the binding is not working and I get an exception like that:

> WASM: System.InvalidOperationException: Microsoft.AspNetCore.Components.Forms.InputSelect 1[System.Byte] does not support the type 'System.Byte'

**Question is: How can I bind, byte value in blazor? Thanks in advance!**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @embayyub.
We don't support binding to `byte` type. Why do you need to use `byte`? Can you use an `int` instead?
We haven't heard much need for this so we don't have plans to support this at the moment. If we see this being something the community needs we will reconsider it in the future.

**Comment by embayyub** [comment]
@mkArtakMSFT , my entity models have byte property so that is why I want to bind them. What is the alternative way of doing it?

**Comment by mkArtakMSFT** [comment]
Well, you can use `int` instead

**Comment by MarkFl12** [comment]
I find myself in need of Byte binding on InputNumber. Like @embayyub I have Byte properties on my entity models, so having them be Byte all the way through seems rather sensible?
