### ISSUE TITLE
Unable to disable HTTP2 in Blazor Server

### ISSUE THREAD

**Issue by ajillepalli** [aspnet/AspNetCore#15268]
The proposed solution to my previous problem (#15123 ) was to disable HTTP2. To do so, I'm using the following Program.cs code:
```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Sel.Automate.WebAppServer
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureKestrel((context, options) =>
                {
                    // Disable HTTP/2
                    // If it's only your development machines that have this problem, you can wrap
                    // this in `if (context.HostingEnvironment.IsDevelopment())` or some other condition
                    // that is only true in development.
                        options.Listen(IPAddress.Loopback, 5001, listenOptions =>
                        {
                            listenOptions.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1;
                        });
                });
    }
}
```
Both FF/GC are still not able to load the Blazor Server example due to `ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY`. Any thoughts? Thanks!

OS: Windows 10.0.17763 Build 17763

**Comment by Tratcher** [comment]
@ajillepalli that code doesn't even enable HTTPS, so there's no way to get ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY. I suspect you did not rebuild and deploy after that change.

**Comment by Tratcher** [comment]
Wait, why do you have both CreateHostBuilder and CreateWebHostBuilder? You should combine those.

**Comment by ajillepalli** [comment]
@Tratcher Thanks for your suggestion. I tried combining both but the compiler isn't able to find some method names (ConfigureKestrel, Listen, Protocols) in the given context.

And yes, I did rebuild after adding in the code to disable HTTP2. Edge is able to load the Web App but not FF/GC.

**Comment by Tratcher** [comment]
Did you try the example I gave?

**Comment by Tratcher** [comment]
Or here's an easier option, update your appsettings.json like this:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http1"
    }
  }
}
```

**Comment by ajillepalli** [comment]
Trying out [https://github.com/aspnet/AspNetCore/issues/15268#issuecomment-545210364](#15268 (comment)) gives me `name not found in the current context` errors for `ConfigureKestrel`, `Listen`, and `Protocols`.

Editing the `appsettings.json` did the trick. The web app now loads in both FF and GC. Thanks a lot.

**Comment by javiercn** [comment]
Closing this issue as there's no more action for us to take here.
