### ISSUE TITLE
In Blazor:- To the particular component rendered in razor page need to add the attributes to the same component in different razor page.

### ISSUE THREAD

**Issue by Indrajith-Sync** [aspnet/AspNetCore#15262]
###Description
If a component is created a particular **.razor** file and i need the particular component in another razor file and add some attributes to the component. Is it possible in blazor ?

**##Page1**

**Test.razor**

`<div id="test"/>`

**##Page2**

**Newpage.razor**

{Existing **Test.razor** page i need to add class attribute to it}

Is there any solution for this case ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Indrajith-Sync.
You can use attribute [splatting](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#attribute-splatting-and-arbitrary-parameters) to apply multiple parameters to the component at once.
