### ISSUE TITLE
Cannot build aspnet core under Linux

### ISSUE THREAD

**Issue by Pilchie** [aspnet/AspNetCore#15275]
_From @mihaimyh on Monday, October 21, 2019 8:36:43 AM_

# 'Configuration' does not exist in the namespace 'Microsoft.Extensions'
Be as descriptive as you can with your title.

I am trying to build a new blazor wasm project under linux and also create a docker image from it but I am getting the following error:

`obj/Release/netstandard2.0/Codescu.Com.Wasm.AssemblyInfo.cs(10,33): error CS0234: The type or namespace name 'Configuration' does not exist in the namespace 'Microsoft.Extensions' (are you missing an assembly reference?) [/src/Codescu.Com.Wasm/Codescu.Com.Wasm.csproj]`

# General

Here is my Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["Codescu.Com.Wasm/Codescu.Com.Wasm.csproj", "Codescu.Com.Wasm/"]
RUN dotnet restore "Codescu.Com.Wasm/Codescu.Com.Wasm.csproj"
COPY . .
RUN dotnet build "Codescu.Com.Wasm/Codescu.Com.Wasm.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "Codescu.Com.Wasm/Codescu.Com.Wasm.csproj" -c Release -o /app/publish
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/Codescu.Com.Wasm/dist .
COPY ["Codescu.Com.Wasm/nginx.conf", "/etc/nginx/nginx.conf"]
```

And the .csproj:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>7.3</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
    <AssemblyVersion>1.0.4.19288</AssemblyVersion>
    <FileVersion>1.0.4.19288</FileVersion>
    <UserSecretsId>65b2ff8e-97d9-4f55-a85d-9d4f9cf5bf4a</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>False</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>True</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>True</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <AssemblyVersionSettings>None.None.None.None</AssemblyVersionSettings>
    <UpdatePackageVersion>False</UpdatePackageVersion>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
    <AssemblyFileVersionSettings>None.None.None.None</AssemblyFileVersionSettings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.dockerignore" Link=".dockerignore">
      <DependentUpon>$(DockerDefaultDockerfile)</DependentUpon>
    </None>
    <None Include="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview9.19465.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview9.19465.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.0.0-preview9.19465.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview9.19465.2" PrivateAssets="all" />
    <PackageReference Condition="'$(OS)' == 'Windows_NT'" Include="BuildWebCompiler" Version="1.12.405" />
  </ItemGroup>

</Project>
```

If I remove `<UserSecretsId>65b2ff8e-97d9-4f55-a85d-9d4f9cf5bf4a</UserSecretsId>` from .csproj build is successful.

_Copied from original issue: dotnet/core#3667_

**Comment by Pilchie** [comment]
_From @scalablecory on Monday, October 21, 2019 6:29:48 PM_

@Pilchie

**Comment by Pilchie** [comment]
Moved.  Not sure what UserSecretsId might have to do with the error you saw.  @anurse do you know how they could be related?

**Comment by anurse** [comment]
The presence of the UserSecretsId causes custom MSBuild logic in the Web SDK to run (to embed that ID in the assembly itself). The problem is the [attribute it generates](https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.UserSecrets/src/UserSecretsIdAttribute.cs) is defined in `Microsoft.Extensions.Configuration.UserSecrets` which isn't referenced in a Blazor app (and isn't auto-referenced by the Web SDK).

I wouldn't expect user secrets to work in Blazor WASM at all since you're dealing with a client-side browser app anyway. There may be a bug in the Web SDK here where it needs to avoid generating this attribute (and perhaps yield a warning) if the user secrets library isn't referenced.

**Comment by javiercn** [comment]
This is correct, user secrets doesn't work for blazor web assembly and will never do, as there is no way to protect secrets on the client.

The answer as stated is to remove the UserSecretsId piece from MSBuild

**Comment by Pilchie** [comment]
@vijayrkn Would it make sense for the WebSDK to warn or provide a clearer error if `UserSecretsId` is set in a Blazor Web Assembly project?

**Comment by vijayrkn** [comment]
The logic to act on usersecretsid is in netsdk.

https://github.com/dotnet/sdk/pull/3673

So this might be a good place to add warning too.

@dsplaisted

**Comment by anurse** [comment]
> The logic to act on usersecretsid is in netsdk.

Ah that's it :). I was having trouble finding it in websdk, thanks for clarifying.
