### ISSUE TITLE
Read RCL static file as text

### ISSUE THREAD

**Issue by geotinc** [aspnet/AspNetCore#15278]
Hi,

I try to read RCL static file as text from my controller.
I try the following without success :

`String body = System.IO.File.ReadAllText(Path.Combine(Directory.GetCurrentDirectory(), "_content", "MyRcl", "TestMail.html"));
                `

I try with IWebHostEnvironment too without success.

Thanks for help

**Comment by javiercn** [comment]
@geotinc Thanks for contacting us.

Static web assets are not copied during development, so their physical location remains the one in your class library wwwroot path.

During development, the framework remaps those paths at runtime inside the `IWebHostEnvironment.WebRootFileProvider`.

To access the files you can query the provider with `IWebHostEnvironment.WebRootFileProvider.GetFileInfo(string.Join("/", "", "_content", "MyRcl", "TestMail.html"))` and that should work.

**Comment by javiercn** [comment]
Closing the issue as there's no further action from us here.

Feel free to comment if this doesn't fix the issue.
