### ISSUE TITLE
AllowAnonymousAttribute not working as expected with CORS request.

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/AspNetCore#15285]
I'm Running ASP.NET Core 3 (Azure Web App) and have a CORS policy set up like so, in Startup.cs:

                    services.AddCors(options =>
                    {
                        options.AddPolicy("TestCors",
                            builder =>
                            builder.WithOrigins(allowedDomains.ToArray())
                            .AllowAnyHeader()
                            .AllowAnyMethod()
                            .AllowCredentials());
                    });

I have an AJAX endpoint in a controller defined as such:

    [EnableCors("TestCors")]
    [AllowAnonymous]
    public async Task<IActionResult> MyAjaxEndpoint(int parm1)
    {
    }

When I attempt to call this controller method using JQuery AJAX method like so:

                    $.ajax(
                    {
                        url: 'otherdomain.com/MyAjaxEndpoint',
                        cache: false,
                        type: "POST",
    			crossDomain: true,
                        data: {parm1: 0},
    			xhrFields:
                        {
                            withCredentials: true
                        },
                        async: false
                    });

, I get a 302 redirect to the login page.  This does not happen if I happen to be authenticated through the standard Identity cookie.  

I have some tokens (JWT) stored in a http-only cookie that I want sent with AJAX requests, and I was under the impression that requirement necessitated `withCredentials: true` in the AJAX options (is that correct?).  I'm not sure if that's what's causing the problem.

At any rate, I assumed that `[AllowAnonymous]` would have bypassed any authentication requirements by the ASP.NET pipeline.

Is there an issue with the AllowAnonymousAttribute or am I (ab)using it wrong?

**Comment by Kahbazi** [comment]
Could you also share Configure method in startup.cs?

**Comment by javiercn** [comment]
@SimonOrdo thanks for contacting us.

As @Kahbazi could you share your startup configuration with us?

**Comment by SimonOrdo** [comment]
Here, I believe, are the relevant bits:

```
services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => false;
                options.MinimumSameSitePolicy = Microsoft.AspNetCore.Http.SameSiteMode.None;
            });

  services.AddAuthorization();
  services.AddSession(o => // session resolves to use IDistributedCache
            {
                o.IdleTimeout = TimeSpan.FromMinutes(60);
            });

services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<AppContext>()
                .AddUserManager<UserManagerEx<ApplicationUser>>()
                .AddDefaultTokenProviders();

   // Add Custom Claims processor
            services.AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>, CustomClaimsPrincipalFactory>();

            services.Configure<IdentityOptions>(options =>
            {
                // Password settings
                options.Password.RequireDigit = false;
                options.Password.RequiredLength = 5;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireLowercase = false;

                // Lockout settings
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(30);
                options.Lockout.MaxFailedAccessAttempts = 20;
                options.Lockout.AllowedForNewUsers = true;

                // User settings
                options.User.RequireUniqueEmail = false;
            });


            services.ConfigureApplicationCookie(options =>
            {
                options.ExpireTimeSpan = TimeSpan.FromHours(4);
                // Cookie settings
                options.Cookie.SecurePolicy = Microsoft.AspNetCore.Http.CookieSecurePolicy.None;
                options.Cookie.HttpOnly = true;               
                // If the LoginPath isn't set, ASP.NET Core defaults 
                // the path to /Account/Login.
                options.LoginPath = "/Account/Login";
                // If the AccessDeniedPath isn't set, ASP.NET Core defaults 
                // the path to /Account/AccessDenied.
                options.AccessDeniedPath = "/Home/Index";
                options.SlidingExpiration = true;
                options.Events.OnRedirectToAccessDenied = context =>
                {
//---> Code Never reached, regarding this CORS issue
                    if (context.Request.IsAjaxRequest())
                    {
                        context.Response.StatusCode = StatusCodes.Status403Forbidden;
                        return Task.CompletedTask;
                    }
                    context.Response.Redirect(context.RedirectUri);
                    return Task.CompletedTask;
                };

                options.Events.OnRedirectToLogin = context =>
                {
//---> Code Never reached, regarding this CORS issue
                    if (context.Request.IsAjaxRequest())
                    {
                        context.Response.StatusCode = StatusCodes.Status401Unauthorized;
                        return Task.CompletedTask;
                    }
                    context.Response.Redirect(context.RedirectUri);
                    return Task.CompletedTask;
                };
            });

services.AddCors(options =>
                {
                    options.AddPolicy("TestCors",
                        builder =>
                        builder.WithOrigins(portalDomains.ToArray())                     
                        .AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowCredentials());
                });

 services.AddControllersWithViews()
                .AddNewtonsoftJson(options =>
            {
                options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            })
                .AddRazorRuntimeCompilation();

            services.AddRazorPages()
                .AddRazorRuntimeCompilation();
```
And the configure method looks like:
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseHttpsRedirection();
            var rwoptions = new RewriteOptions();
            rwoptions.Rules.Add(new RedirectToWwwRule());
            app.UseRewriter(rwoptions);

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error?statusCode=777");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }          
            app.UseCors("TestCors");
            app.UseFileServer();

            app.UseSession();
            app.UseStatusCodePagesWithReExecute("/Home/Error", "?statusCode={0}");

            // Kludge: https://github.com/aspnet/AspNetCore/issues/13715
            app.Use((context, next) => {
                context.SetEndpoint(null);
                return next();
            });

            app.UseRouting();            
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");

                endpoints.MapControllerRoute(
                  name: "areaRoute",
                  pattern: "{area:exists}/{controller=Home}/{action=Index}");

                endpoints.MapRazorPages();
            });
  }
```

**Comment by javiercn** [comment]
@SimonOrdo thanks for the details.

@HaoK I believe that the issue here is that the Identity cookie is set to SameSite=Strict and that would prevent it from being sent to the other domain. Can you take a look at it?

**Comment by blowdart** [comment]
Given that the same site changes are in 3.1 no, it's not related to that work.

**Comment by SimonOrdo** [comment]
>  I believe that the issue here is that the Identity cookie is set to SameSite=Strict and that would prevent it from being sent to the other domain. Can you take a look at it?

I believe SameSite is set to None here, not Strict, unless I'm not seeing something you are:

`options.MinimumSameSitePolicy = Microsoft.AspNetCore.Http.SameSiteMode.None;`

**Comment by SimonOrdo** [comment]
> Fiddler traces, plus the browser versions would be useful here.
> 
> Also if you are sending a JWT token in a cookie, and there's no identity cookie, because it's cross domain, that's simply not going to work.

@blowdart  I will gather the requested diagnostic data.  

To clarify, the JWT token isn't being used to authenticate against Identity.  It's passed for an unrelated reason.   Sorry if that was needlessly confusing things, but ultimately the root issue (I believe) is that the CORS AJAX request can't reach the controller due to the request not being authenticated even though I've set the `AllowAnonymous` attribute on the method.

Correct me if I'm wrong, please, but I thought that there being a JWT token (incidentally) stashed in a cookie should be irrelevant at that point, no? 

Diagnostic data to follow shortly.

**Comment by blowdart** [comment]
Ah in that case, yea JWT in a cookie isn't affecting anything.

**Comment by SimonOrdo** [comment]
I attempted to build a small project to repro the issue and was unable to do so, although I'm not seeing some other inconsistencies related to UseCors() now.  I'll close this issue for the time being and will re-open once I can describe the symptoms in an independently reproduceable manner.

**Comment by SimonOrdo** [comment]
@blowdart , I don't know why or how, but if I remove the following work-around ( https://github.com/aspnet/AspNetCore/issues/13715#issuecomment-528929683 ) suggested by @Tratcher , everything works as expected.  I won't re-open the issue at this time, frankly because I can't describe the problem beyond the symptoms.  

I just wanted to document the resolution I stumbled across.

Remove the following:

     ```
       // Kludge: https://github.com/aspnet/AspNetCore/issues/13715#issuecomment-528929683
            app.Use((context, next) => {
                context.SetEndpoint(null);
                return next();
            });
```

... and all is well (except, obviously, the problem that that the workaround is fixing).

**Comment by HaoK** [comment]
Just guessing, but perhaps nulling out the endpoint has the effect of getting rid of the endpoint metadata (aka the allowanonymous)
