### ISSUE TITLE
HttpContext.SignInAsync vs SignInMangerAsync

### ISSUE THREAD

**Issue by der-Daniel** [aspnet/AspNetCore#15307]
I am using the following code in a HTTPPost Controller to login.

    await this.HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                principal,
                new AuthenticationProperties { AllowRefresh = true, IsPersistent = true });
        
Then in a Blazor Component I can do this:

    <Authorized>
        Hello, @context.User.Identity.Name!
        <button @onclick="asd" class="nav-link btn btn-link">Sign Out</button>
    </Authorized>

I stumbled upon the `SignInManager` which seems more adequate for Signing in a user.
Chaning my code to

    await this.HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                principal,
                new AuthenticationProperties { AllowRefresh = true, IsPersistent = true })
            
in the controller, a cookie is still getting set.

But now the Blazor code from above is not working anymore i.e. no user gets recognized.

Also having something like

    @using Microsoft.AspNetCore.Identity
    @inject SignInManager<IdentityUser> SignInManager
    @inject UserManager<IdentityUser> UserManager
    ....
    <AuthorizeView>
        <Authorized>
            Hello @UserManager.GetUserAsync(context.User);
            <button @onclick="asd" class="nav-link btn btn-link">Sign Out</button>
        </Authorized>

is not working.
Digging around the docu I only found this [piece](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio) .

Is `SignInManager` only working for *razor* pages or am I missing something?

**Comment by TheRealLenon** [comment]
How did you solved this?.. I´m facing the same problem..

**Comment by der-Daniel** [comment]
Yes these are limitations to the blazor framework.

It it just not compatible yet.

**Comment by TheRealLenon** [comment]
I´m a bit confused. I only use .Net Core, but facing the same problem, when login via the SignInManager. Then I can't access the User within my .cshtml Files (are those even the same?)

I could made it working by using the following code:

`                await base.SignInAsync(user, isPersistent, Data.Constants.Constants.CookieScheme);
                await _contextAccessor.HttpContext.SignInAsync(Constants.CookieScheme, principal, new AuthenticationProperties
                {
                    IsPersistent = false
                });`

**Comment by der-Daniel** [comment]
A Blazor Component is annotated with `@page {url}`. I think it can be a `.cshtml` file, but usually it is a `.razor` file.

`SignInManager.SignInAsync(...)` internally just calls `HttpContext.SignInAsync(...)`. This is the part that confuses me.

The reason your code run is probably the `HttpContext.SignInAsync` command.

**Comment by TheRealLenon** [comment]
That was what I thought also at first. But when accessing the AuthorizationHandlerContext or the , and want to check if the User is authenticated, it's not working, when only signing in via SignInManager. Couldn't find anything on the internet. So I would guess it's not only an Blazor kind of "Bug"?
