### ISSUE TITLE
Blazor WebAssembly: Checkbox bind not working when value is changed on Codeside

### ISSUE THREAD

**Issue by Knarzi** [aspnet/AspNetCore#15306]
I have a Listbox with Items. This Items contains a checkbox. The Listbox ist binded on a List the following way:

```html
<div class="well" style="max-height: 500px;overflow: auto;">
    <ul class="list-group checked-list-box">
        @foreach (var adGroup in GroupManagementService.Groups)
        {
        <li class="list-group-item border-0">
            <label class="form-check-label">
                <input class="form-check-input"
                        @bind="@adGroup.IsSelected"
                        type=@(GroupManagementService.ADGroupViewMode != ADGroupViewMode.Securitygroups ? "radio" : "checkbox") />
                @adGroup.Gruppenname
            </label>
        </li>
        }
    </ul>
</div>
```

Now I want to put the Items that are selected with the Checkbox into the SelectedGroups-List and remove it from the Groups-List with the following function:

```c#
internal async void HandleSelectGroups()
{
    var selectedGroups = Groups.Where(g => g.IsSelected).ToArray();
    SelectedGroups.AddRange(selectedGroups);
    Groups.RemoveAll(g => g.IsSelected);
    
    await JsInteropService.WriteLogAsync(Groups);
    await JsInteropService.WriteLogAsync(SelectedGroups);
    
    OnSelectHandled?.Invoke();
}
```
Before i call the HandleSelectGroups the two Lists looks so:

![image](https://user-images.githubusercontent.com/21334413/67366680-3d010800-f574-11e9-9b94-e3485be32c92.png)

After it looks so:

![image](https://user-images.githubusercontent.com/21334413/67367122-2ad39980-f575-11e9-884e-05311a2e9b1b.png)

Now the checkboxes of the first two Items in the column "Suchergebnisse" are checked, but the IsSelected-Value of the Items are false:

![image](https://user-images.githubusercontent.com/21334413/67367465-d54bbc80-f575-11e9-9e90-e28515ef87f7.png)

And now the question, why do the first two checkboxes remain checked in the column "Suchergebisse", although the IsSelected-value of the two items is false.

**Comment by Andrzej-W** [comment]
Probably you have to use `@key`
https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#use-key-to-control-the-preservation-of-elements-and-components
You can also look here: https://github.com/aspnet/AspNetCore/issues/11908

**Comment by Knarzi** [comment]
Yeah, perfect. That was the problem. Added `@key="adGroup"` to the li element and now it works! Many thanks!
