### ISSUE TITLE
Cannot provide a value for property in Blazor Component

### ISSUE THREAD

**Issue by UltWolf** [aspnet/AspNetCore#15319]
### Describe the bug
When i  open Blazor Component that's doesn't render and return exception:

### To Reproduce
1. Using this version of ASP.NET Core '3.0.0'
2. Run this code 
Adding service in DI

 ` services.AddSingleton<IUserService, UserService>();`

and go to page with 
```
' @using Sensica.BLL.Contracts;
@inject UserService service'
```
with interfaces i'm trying do that's too.
3. With these arguments '....'
`InvalidOperationException: Cannot provide a value for property 'service' on type 'Sensica.AdminPanel.Pages.Users.Index'. There is no registered service of type 'Sensica.BLL.Contracts.IUserService'.`
### Expected behavior
That must render page and return collection of user

**Comment by UltWolf** [comment]
> 
> 
> @UltWolf thanks for contacting us.
> 
> You need to inject `IUserService` not UserService.
> 
> Hope that helps.

Sorry, but i`m writing :

> with interfaces i'm trying do that's too.

**Comment by javiercn** [comment]
@UltWolf Can you clarify what you are trying to accomplish and what is not working according to your expectations?

**Comment by UltWolf** [comment]
@javiercn 
I want just get my complete UserService from DI  and inject him into my BlazorComponent,  for creating entities without work with api,  but when i`m trying that`s, that`s return error.
