### ISSUE TITLE
[Templating] Update the SPA templates to use generic host

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#15349]
* The SPA templates are not using generic host.
* They should be updated as the old webhost is obsolete.

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/issues/15060

**Comment by javiercn** [comment]
We should do this for 3.1 I think.

https://github.com/aspnet/AspNetCore/blob/release/3.1/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/Program.cs#L19-L21
https://github.com/aspnet/AspNetCore/blob/release/3.1/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/React-CSharp/Program.cs#L19-L21
https://github.com/aspnet/AspNetCore/blob/release/3.1/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/Program.cs#L20-L22

/cc: @davidfowl thoughts?

**Comment by danroth27** [comment]
@javiercn Is there any reason we didn't do this in 3.0?

**Comment by danroth27** [comment]
Cool, if there's no technical reason *not* to do this then I agree we should just get this done in 3.1.

**Comment by javiercn** [comment]
It's already done. Waiting for someone to sign-off the PR.
