### ISSUE TITLE
configurable authorization header checking in ResponseCachingPolicyProvider

### ISSUE THREAD

**Issue by namnik** [aspnet/AspNetCore#15359]
I need to use response caching despite exist authorization key in request header!
I know security issues about authorization header when using response caching.
but can configurable and optional to use this validation in the response caching Middleware?

I notice that both class and interface for this validation: **ResponseCachingPolicyProvider** and **IResponseCachingPolicyProvider** is Internal.
<code>

            if (!StringValues.IsNullOrEmpty(request.Headers[HeaderNames.Authorization]))
            {
                context.Logger.RequestWithAuthorizationNotCacheable();
                return false;
            }
</code>

**Comment by jkotalik** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/14569
