### ISSUE TITLE
Custom Routing for a multi-tenant application

### ISSUE THREAD

**Issue by LaughingJohn** [aspnet/AspNetCore#15369]
### Is your feature request related to a problem? Please describe.
We have a multi tenant / multi system application. We can tell the tenant (user's AD) from the user who is signed in, but we need to distinguish the system they are accessing (org).
So I want to be able to do the following:
1. Have the org in the URL:
https://mydomain/org1/mypage
https://mydomain/org2/mypage
2. If the default url is chosen https://mydomain/ then we want to direct to a page that allows them to choose the org. I'm not too worried about this bit, but include it for completeness.

### Describe the solution you'd like
1. I don't want to include the org as a parameter in the page route itself. So I want to be able to use @page "/mypage".
2. Ideally, when I click a navlink I want it to go the linked page with the "org" part of the url intact, without supplying it. So /mylinkedpage would go to https://mydomain/org1/mylinkedpage
3. Ideally it would be good to be able to call GetJsonAsync etc. without having to supply the org in the path.

### Additional context
Is there any way of achieving this currently? 
Do I have to write a custom router to do it? 
If so, do you have any examples/advice on doing so?

Thank you!

**Comment by javiercn** [comment]
@LaughingJohn thanks for contacting us.

You could probably do this using the a path base per org or modifying the page routes to prepend the org parameter to them?

**Comment by LaughingJohn** [comment]
Hi @javiercn,
I think you may be right. I've updated a test page to `@page "/{org}/mypage"` on the Blazor client side and then changed the routing in the API to be:    `endpoints.MapControllerRoute("default", "{org}/{controller}/{action}");` and that seems to have done the trick (so far).

For anyone else who comes along I also had to remove the ApiController and Route attributes from the controller as well.

Thank you!

**Comment by LaughingJohn** [comment]
@javiercn, can you expand on the "base path per org" comment, is that a different alternative?

**Comment by LaughingJohn** [comment]
@javiercn, sorry another question, can I move the main layout (default page) to the {org}/ rather than just "/" ?

**Comment by LaughingJohn** [comment]
Sorry, this is becoming a bit of a diary! ;)

Regarding my previous point, I think the issue is this:

1. I navigate to https://mydomain/org/mypage1
2. mypage has a layout
3. The layout contains a navlink: <NavLink class="nav-link" href="mypage2">
2. Clicking that link goes to  https://mydomain/mypage1

In other words the org gets lost because the layout doesn't know where it is and doesn't have access to the parameter.

I think this is a similar issue to [https://github.com/aspnet/AspNetCore/issues/14077](https://github.com/aspnet/AspNetCore/issues/14077)

I guess the suggestion on there of dropping the layout altogether and using a "parent" page to act as the layout is the way to go. I will try that..

**Comment by javiercn** [comment]
@LaughingJohn Sorry, I thought this was an MVC question, not a Blazor question.

Is it a blazor question or are you trying to intermix Blazor and MVC, if you provide us with more details then I can probably offer you a better answer.

**Comment by LaughingJohn** [comment]
@javiercn, sorry I didn't make that clear, yes it's a Blazor Webassembly issue. Although we may end up with some server side razor pages as well.

I think I've got there (kind of). I was hoping that there would be some way to tell the whole application that I wanted to run under a pattern url like https://mydomain/org/... Where org is the client's system name (tenant).

I was hoping that links, NavLink etc. would somehow magically work, but I think I'm being a bit naive. Apologies I'm new to both Blazor as well as ASP.Net generally, so I've been experimenting with the best way to organise our application. In the end I had to create a helper extension method to pull the org out of the current url and then insert it into the path for a link. I guess I was expecting too much of the framework.

Just in case it helps someone, I have it running like this (FYI NavLink is in the Main Layout):

```
            <NavLink class="nav-link" href="@(NavigationManager.ToAbsoluteUriWithOrg("counter"))">
                <span class="oi oi-plus" aria-hidden="true"></span> Counter
            </NavLink>
```

   public static class NavigationManagerExtensions
    {
        public static string ToAbsoluteUriWithOrg(this NavigationManager navigationManager, string newPath)
        {
            var org = navigationManager.GetOrgFromUri();
            var path = GetPathPartOrEmpty(org) + GetPathPartOrEmpty(newPath);
            return navigationManager.ToAbsoluteUri(path).ToString();
        }

```
        public static string GetOrgFromUri(this NavigationManager navigationManager)
        {
            var uri = new Uri(navigationManager.Uri);
            var path = uri.AbsolutePath;
            var pathParts = path.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
            
            if (pathParts.Length > 0)
            {
                return pathParts[0];
            }
            
            return string.Empty;
        }

        private static string GetPathPartOrEmpty(string newPath)
        {
            return string.IsNullOrWhiteSpace(newPath)
                ? string.Empty
                : "/" + newPath;
        }
    }
```
