### ISSUE TITLE
Real Client IP address using X-Forwarded-For header issue

### ISSUE THREAD

**Issue by RaghuMasineni** [aspnet/AspNetCore#15370]
I am not able to get real client IP address using X-Forwarded-For header.  My application is built on Dot net core 1.1 not 3.0 which is latest. And we have load balancer set up to distribute the load.
And I have implemented code as mentioned in below MSDN article. 

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.0&viewFallbackFrom=aspnetcore-1.1#forwarded-headers-middleware-options 

sample code
--------------
1)Configure services with forward options
```
  public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddApplicationInsightsTelemetry(Configuration);
            services.Configure<AppSettings>(Configuration);
            services.AddMvc();
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders =
                    ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
                options.ForwardLimit = 2;
                options.KnownProxies.Add(System.Net.IPAddress.Parse("123.111.11.88"));
                //options.KnownProxies.Clear();
                //options.KnownNetworks.Clear();
            });
        }
```
here 123.111.11.88 is sample Load balancer IP address.

2)Configure method changes as below,
```
  public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
           --------
            app.UseForwardedHeaders();
           -------
      }
```
3)Code to read headers as below,
```
 string realClientIP = GetHeaderValueAs<string>("X-Cluster-Client-Ip");

 public T GetHeaderValueAs<T>(string headerName)
        {
            StringValues values;

            Request.Headers.TryGetValue(headerName, out values);
            if (!StringValues.IsNullOrEmpty(values))
            {
                var rawValues = values.ToString();

                if (!string.IsNullOrEmpty(rawValues))
                    return (T)Convert.ChangeType(values.ToString(), typeof(T));
            }

            return default(T);
        }
```
Old implementation
---------------------
Earlier we have below code to retrieve client IP but it is always returning Load balancer IP,

`string IP = Request.HttpContext.Connection.RemoteIpAddress.MapToIPv4().ToString( );`

Queries
--------
1) is this right way to get real client IP with dot net core 1.1 since I could see that MSDN article is for dot net core 3.0 and there is no reference article for core 1.0.
2)Is it possible to get result using custom headers and how it can be done if possible ?
3)Please let me know if there is any other way ?

**Comment by javiercn** [comment]
@RaghuMasineni thanks for contacting us.

@Tratcher Is there a way to do this?

@RaghuMasineni I would suggest that you update your application to a newer version of the framework. .NET Core 1.1 reached end of life on 06/27/2019. You can get more details https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by Tratcher** [comment]
UseForwardedHeaders also worked in 1.x but we have made usability improvements since then.

See the troubleshooting steps here:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer

Why `X-Cluster-Client-Ip`? That's not the header used by UseForwardedHeaders. I assume that's the header name defined by your proxy? Then you'll need to set ForwardedForHeaderName:
https://github.com/aspnet/AspNetCore/blob/dfba024c7888e9357ce40687e1771953074340fd/src/Middleware/HttpOverrides/src/ForwardedHeadersOptions.cs#L16

**Comment by RaghuMasineni** [comment]
@Tratcher - Sorry, I copied wrong statement . correct statement which I am using is below,

 string  realClientIP = GetHeaderValueAs<string>("X-Forwarded-For");

Actually I already followed the steps mentioned in below link but still not able to get the result

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer

I mentioned all the changes done as per this article  in my initial post .Please let me know If I am missing any specific code.

Also Do we need to make any configuration in Load Balancer or its server to make it forward these headers to IIS server ?

**Comment by Tratcher** [comment]
If UseForwardedHeaders is working then X-Forwarded-For will be removed and assigned to RemoteIpAddress.

You really need to move off 1.1 before we continue this investigation. We've addressed many issues in these scenarios since then.

**Comment by RaghuMasineni** [comment]
@Tratcher - Thanks for the details. We may be upgrading our application to 2.* next year (2020).So We would like to implement getting real client ip with 1.1 itself for now.

Actually I have hosted application in local machine with out load balancer and accessed the  site from some other machine. Following is the result,

1) string IP = Request.HttpContext.Connection.RemoteIpAddress.MapToIPv4().ToString( );  --> 127.0.0.1

string realClientIP = GetHeaderValueAs("X-Forwarded-For");  -->127.31.31.78 (Expected other machine IP)

So I am able to get the proper client IP in this scenario while reading X-Forwarded-For header but still getting default IP(127.0.0.1) for RemoteIPAddress.

1)Do we need to make any load balancer settings to allow XFF headers ?
2)Which should we read for client IP RemoteIPAddress or X-Forwarded-For header in httpcontext ?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
