### ISSUE TITLE
GCCollect does not clear WeakReferences

### ISSUE THREAD

**Issue by wvpm** [aspnet/AspNetCore#15386]
VS 2019
C# 8.0

var obj = new object();
var wRef = new WeakReference(obj);

GC.Collect(2, GCCollectionMode.Forced);
GC.WaitForPendingFinalizers();
obj = null;
GC.Collect();
Console.WriteLine(wRef.IsAlive); // Prints False for .Net Core 2.2 but True for .Net Core 3.0
Console.ReadKey();

**Comment by javiercn** [comment]
@wvpm thanks for contacting us.

This question is not specific to ASP.NET Core, you have a better chance of getting a better and faster response if you file the issue in the [core-clr](https://github.com/dotnet/coreclr) repository.

**Comment by wvpm** [comment]
@javiercn, you're right. I will move it. Sorry for misplacing it.
