### ISSUE TITLE
Problem executing startsvs.cmd

### ISSUE THREAD

**Issue by kiloeras** [aspnet/AspNetCore#15387]
### Describe the bug
Im trying to run the script startsvs.cmd located on
C:\Users\Miguel Morales\AspNetCore\src\Mvc
But im getting error that says
"C\Users\Miguel not found"
It must be because the " " character.
I tryied adding "" or '', but not working.
Also tryied to edit the script but I am not being able to make it work

### To Reproduce
I've cloned the version from the git.
Im following some tutorial on plutalsight to learn more about asp.net core.
So when I try the command  startvs the error happends

### Screenshots
![test11](https://user-images.githubusercontent.com/6236867/67523240-8eadad80-f6ae-11e9-9ed1-c8bf939896c7.png)

### Additional context
![script](https://user-images.githubusercontent.com/6236867/67523356-cf0d2b80-f6ae-11e9-9a18-d53d0ca593e0.png)

The error
![error](https://user-images.githubusercontent.com/6236867/67523422-f06e1780-f6ae-11e9-97b2-ef379a490446.png)

I still have lot to learn lol

**Comment by javiercn** [comment]
@kiloeras thanks for contacting us.

@aspnet/build can you help here?

**Comment by kiloeras** [comment]
@javiercn You're welcome :)
.net core is Awesome

@Kahbazi 
I will close the Issue, the #15392 pull should fix it.
