### ISSUE TITLE
JavaScript scheduler framework is not being displayed in a page.

### ISSUE THREAD

**Issue by jhunexjun** [aspnet/AspNetCore#15395]
There's no scheduler written in Blazor as of the moment that satisfy my requirement and open source or free of use. So I decided to use Syncfusion scheduler (JavaScript Essential 1) written in JavaScript. So now, when I load a certain Blazor component it doesn't load. However, if this is placed inside the _Host.cshtml

`<div style="float: left" id="Schedule1"></div>`

It just load everything. I know this is Blazor intended for Single Page Application and this JS scheduler is not for SPA. But is there a way a can still load or call the Scheduler when the component is loaded?

**Comment by javiercn** [comment]
We are closing this issue as we haven't seen community engagement in a while. If new information is provided we will re-evaluate it.
