### ISSUE TITLE
[question] Could we build blazor project into pure js library?

### ISSUE THREAD

**Issue by Thaina** [aspnet/AspNetCore#15396]
While I have seen js interop in blazor. I was wonder that, could we build some C# utility library with blazor but not use any blazor component, and instead build it into pure js/wasm then include it into normal HTML/JS project. Then using `DotNet.invokeMethod` to call it in js file

Is there a project template for this pattern?

**Comment by javiercn** [comment]
@Thaina thanks for contacting us.

This is a question better suited for the mono team. 

In general I don't think it would be practical given that you would need to bring along the runtime and other code for it to work. It would also not be possible to call it with DotNet.invokeMethod as that's not something we've explored.
