### ISSUE TITLE
IIS AspNetCore Module V2 stop while running

### ISSUE THREAD

**Issue by nolanjian** [aspnet/AspNetCore#15391]
Hi, Dear all,
I`m using .net core in iis with **IIS AspNetCore Module V2**, it works fine often.
But it stop with exception every two or three day.
Here is the event log:

`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="IIS AspNetCore Module V2" />
    <EventID Qualifiers="0">1035</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-10-24T13:29:37.000000000Z" />
    <EventRecordID>14876528</EventRecordID>
    <Channel>Application</Channel>
    <Computer>iZ86duorae53ouZ</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application '/LM/W3SVC/3/ROOT/DSMCallback' with physical root 'C:\inetpub\dscprod\DSMCallback\' has exited from Program.Main with exit code = '-2147450743'. First 30KB characters of captured stdout and stderr logs:
Failed to create CoreCLR, HRESULT: 0x8007000E
</Data>
    <Data>Process Id: 7512.</Data>
    <Data>File Version: 13.0.19258.0. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: aee5e4080331553ea9dfb7fb388b6d72f715bf6a</Data>
  </EventData>
</Event>`

`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="IIS AspNetCore Module V2" />
    <EventID Qualifiers="0">1007</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-10-24T13:29:37.000000000Z" />
    <EventRecordID>14876529</EventRecordID>
    <Channel>Application</Channel>
    <Computer>iZ86duorae53ouZ</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application '/LM/W3SVC/3/ROOT/DSMCallback' with physical root 'C:\inetpub\dscprod\DSMCallback\' failed to load coreclr. Exception message:
CLR worker thread exited prematurely</Data>
    <Data>Process Id: 7512.</Data>
    <Data>File Version: 13.0.19258.0. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: aee5e4080331553ea9dfb7fb388b6d72f715bf6a</Data>
  </EventData>
</Event>`

Do any users meet with the same problem with me?

by the way, I use a **BackgroundService** in my application, do it matter to my problem?
Thanks!

**Comment by jkotalik** [comment]
@nolanjian the HRESULT you are getting is OutOfMemory (E_OUTOFMEMORY). Can you make sure the target machine has enough available memory?

**Comment by nolanjian** [comment]
@jkotalik Yes, you are right! I have low down my SQL server memory on the target machine and let IIS get more, it works fine now.
Thanks!
