### ISSUE TITLE
Attribute Routing parameters containing an encoded slash - "/"

### ISSUE THREAD

**Issue by rsDevelopment1987** [aspnet/AspNetCore#15406]
Currently when an encoded / is part of the parameter the string is never decoded. For example:
http://myNewApi/Items/abd%2fefg/items.  The parameter should be abcd/efg but upon inspection of the code it appears as abd%2fefg.  Is this correct behaviour? 

**Steps to reproduce the behaviour:**
Create a WebAPI and a controller with the following method: 

```c#
    /// <summary>
    ///   Get a items.
    /// </summary>
    /// <param name="itemReference">Item Reference</param>    
    [HttpGet("{itemReference}/items", Name = "item-get")]
    [ProducesResponseType(typeof(ListResponse), 200)]
    public async Task<IActionResult> GetItemsAsync(string reference) {

      return NoContent();
    }
```
breakpoint on the NoContent line.
Debug and perform a Get against the endpoint.  You should see that the reference value is still abcd%2fefg

**Expected Behaviour:**
I would have expected when inspecting the reference value to be abcd%efg

**Additional information:**
Currently running aspnetcore 2.2

**Comment by javiercn** [comment]
@rsDevelopment1987 Thanks for contacting us.

Having '/' in your urls its a bad idea. I imagine it doesn't get decoded for security reasons at the host level (as it could cause internally an unexpected endpoint to be hit `(http://myNewApi/Items/abd/efg/items)`.

As I said, our recommendation is to avoid dangerous characters in the url (like '/'). Most servers have a setting to control this, but I would discourage you from fiddling with it.

I don't believe routing does any decoding of parameters (it's all the host behavior) so it is up to you to perform the decoding.

@rynowak can correct me if I'm wrong.

**Comment by rsDevelopment1987** [comment]
Hi Javiercn,

Thanks for the quick feedback.  Unfortunately the piece of functionality that I'm currently writing has dependency on support old data which does have slash (basically lists with items references which are catalogue ids - may include / or -). 

So unfortunately I have to support slashes :( -  So I may have to do the decoding myself then in the particular endpoints that have this dependency. 

Unless with the little info I provided there's a better way?  I am new to the WebAPI scene so I do take it the approach of:

(http://myNewApi/Items/{Itemreference} - to get info about a particular item
(http://myNewApi/Items/{Itemreference}/Items - to get children of a particular item

is correct or is there a different way of doing this?
