### ISSUE TITLE
Bad responses: HttpClientParallel

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#15407]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| HttpClientParallel | Windows, Physical, http, KestrelSockets | 10/25/19 3:22:21 PM +00:00 | 626 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Recovered
