### ISSUE TITLE
Asp.net core 3.0 Angular how to customize the identity server and config the events

### ISSUE THREAD

**Issue by collina2019** [aspnet/AspNetCore#15403]
o we have any Asp.net core 3.0 Angular identity server guide docs ? It is very simple :

`services.AddIdentityServer() .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();`

And for validating token :
`services.AddAuthentication() .AddIdentityServerJwt();`

But i don't know how to customize the ids related services . For example :

1.  how to customize IDS4 service , for example : how to extend the ProfileService to add claims .
2.  In AddIdentityServerJwt , how to add jwt events like OnTokenValidated ?

Thanks

**Comment by javiercn** [comment]
@collina2019 thanks for contacting us.

> 1. how to customize IDS4 service , for example : how to extend the ProfileService to add claims .

Unless we explicitly override an IS4 Service, you would customize in the standard way used to customize IS4.

If you have an example of some specific customization that is not working for you and that works in vanilla IS4 let us know.

> 2. In AddIdentityServerJwt , how to add jwt events like OnTokenValidated ?

This is no different than configuring any other auth handler. You can add after `AddIdentityServerJwt` to further configure the underlying JwtBearerHandler.

```csharp
services.ConfigureOptions<JwtBearerOptions>(IdentityServerJwtConstants.IdentityServerJwtBearerScheme, options => {
 ...
});
```

**Comment by javiercn** [comment]
This https://github.com/aspnet/AspNetCore.Docs/issues/15317 tracks adding a section to the docs.

I'm closing this issue as the questions have been answered.

**Comment by collina2019** [comment]
>Unless we explicitly override an IS4 Service, you would customize in the standard way used to customize IS4.

That means i would need to remove the `services.AddIdentityServer() .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();` and use the standard way to identity server with their conifg system ?

**Comment by collina2019** [comment]
and if yes, can I keep the asp.net identity style login page?

**Comment by javiercn** [comment]
> That means i would need to remove the `services.AddIdentityServer() .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();` and use the standard way to identity server with their conifg system ?

No, you simply replace whatever service you want with `services.Add<Lifetime><Interface,Implementation>()` as you would do when replacing any other service. Or use the same instructions IS4 provides to do so.

> and if yes, can I keep the asp.net identity style login page?

Not sure what you mean by this. The template already uses the default UI Identity login page. All the other code is in the template, and you can modify how you see fit, however, once you do that then you are on your own.

SPAs are different from traditional web applications and the authentication flow is different. See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0 for details

**Comment by collina2019** [comment]
Why i get below error on `ConfigureOptions<JwtBearerOptions>` :

`No overload of method ConfigureOptions take 2 arguments `

> services.ConfigureOptions<JwtBearerOptions>(
>    IdentityServerJwtConstants.IdentityServerJwtBearerScheme,
>    options =>
>    {
      
>    });

**Comment by javiercn** [comment]
@collina2019 Sorry, I got the wrong method in the snippet. (I always get this wrong). It's Configure not ConfigureOptions

```
services.Configure<JwtBearerOptions>(IdentityServerJwtConstants.IdentityServerJwtBearerScheme, options => {
 ...
});
```

**Comment by collina2019** [comment]
Ok , then you might need to update the docs 

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0

Another question , i have modify to add JwtBearerEvents 

    services.Configure<JwtBearerOptions>(
    IdentityServerJwtConstants.IdentityServerJwtBearerScheme,
    options =>
    {
        options.Events = new JwtBearerEvents
        {
            OnTokenValidated =  context =>
            {
                //find by the claims in token ,for example , if type is groups


                var claims = new List<Claim>
                {
                new Claim("groups", "ad")
                };
                var appIdentity = new ClaimsIdentity(claims);

                context.Principal.AddIdentity(appIdentity);


                return Task.CompletedTask;
            }
        };
    });

but when user is login , click `fetch data` button , it won't fire the event and reponse return 401 error 

    HttpErrorResponse {headers: HttpHeaders, status: 401, statusText: "OK", url: "https://localhost:44386/weatherforecast", ok: false, …}

The scope of access token confirm have `projectName+API` .

I only add resource ;

    "Resources": {
        "MyExternalApi": {
        "Profile": "API",
        "Scopes": "a b c"
        }
    }

And the token include scopes 

    {
        "nbf": 1572944925,
        "exp": 1572948525,
        "iss": "https://localhost:44386",
        "aud": [
        "https://localhost:44386/resources",
        "MyExternalApi",
        "angularTemplateAPI"
        ],
        "client_id": "angularTemplate",
        "sub": "f0460d2b-3916-4c3f-b760-794e8feeaab8",
        "auth_time": 1572944921,
        "idp": "local",
        "role": "Admin",
        "scope": [
        "openid",
        "profile",
        "a",
        "b",
        "c",
        "angularTemplateAPI"
        ],
        "amr": [
        "pwd"
        ]
    }

Any suggestion ?

**Comment by javiercn** [comment]
@collina2019 Can you provide a minimal repro project showcasing your issue so that I can help you?

**Comment by collina2019** [comment]
@javiercn  check the repo 

https://github.com/collina2019/angular

Just add the codes as i shown above .

Appreciate your help .
