### ISSUE TITLE
netcoreapp3.0 app got "Correlation failed" on iOS device.

### ISSUE THREAD

**Issue by Lukiya** [aspnet/AspNetCore#15416]
### Describe the bug
On iOS device, "Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.GenerateCorrelationId" method seems cannot append correlationid cookie to iOS browsers.
**Desktop browser doesn't this issue!**

### To Reproduce
1. Build IdentityServer4 environment.
2. Use iPhone6/7/8 to access pages that need login.
2. After login, there will be a post request send to xxxxxx.com/signin-oidc
3. Got errors:
- '".AspNetCore.Correlation.OpenIdConnect.xxxxxxxxxx"' cookie not found.
- System.Exception: Correlation failed.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Expected behavior
Should login success just like desktop browser.

### Screenshots
![image](https://user-images.githubusercontent.com/2961561/67601333-ef79cc00-f728-11e9-8d4d-0b34cdbec954.png)

### Additional context
WebServer: nginx
netcoreapp3.0
IdentityServer4 3.0.2
ForwardedHeaders_Enabled: true

**Comment by blowdart** [comment]
If this is Identity Server's standard setup, and not our templates you would be better off asking in [their repo](https://github.com/IdentityServer/IdentityServer4).

**Comment by leastprivilege** [comment]
This is happening in the MVC client. Not IdentityServer.

**Comment by Lukiya** [comment]
I figured out, this is a Safari cookie size limit issue.I stored too much claims. And the final authentication cookie exceed 4k its limit.
Chrome doesn't have this limit, that's why desktop works fine.

The interesting part is I dont' have this issue before I upgrade to core 3.0, I remember there's a cookie chunk mechanism, but somehow it doesn't work in Safari anymore.

**Comment by blowdart** [comment]
@Tratcher did chunking go away in 3.0 for cookies?

**Comment by anurse** [comment]
> The interesting part is I dont' have this issue before I upgrade to core 3.0

We did include a few more default claims in 3.0 which may have pushed your cookie above the 4K per-domain limit. If you want to remove some claims, you can use the `ClaimActions` option to remove some claims. See our docs for some details on how to do this: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.0#map-user-data-keys-and-create-claims

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
