### ISSUE TITLE
Make JsonPatchDocument Serializable

### ISSUE THREAD

**Issue by MattHartz** [aspnet/AspNetCore#15417]
### Is your feature request related to a problem? Please describe.
I am trying to call a .net core Service Fabric service to handle patching the data entity. I am calling this service from an ApiController. When trying to call the service, i am getting serialization issues.

### Describe the solution you'd like
Flag datacontract and datamember for all classes and subclasses.

### Additional context
Error:
Type 'Newtonsoft.Json.Serialization.DefaultContractResolver' with data contract name 
'DefaultContractResolver:http://schemas.datacontract.org/2004/07/Newtonsoft.Json.Serialization' is not expected. 
Add any types not known statically to the list of known types - for example, 
by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
