### ISSUE TITLE
DataAnnotations: Date is always out of range

### ISSUE THREAD

**Issue by VBAndCs** [aspnet/AspNetCore#15418]
VS.Net Community 2019 Ver 16.3.6
In Razor Pages app, I am tring to but a date range like this:
```
[Range(typeof(DateTime),"01/01/2019", "01/01/2020")]
public DateTime EnrollmentDate { get; set; }
```

but when testing this, any date I write is rejected, such as:
1/1/2019
Noting that this value is accepted by the server when I remove the Range attribute!
Even when I copy the date from the error message like:
01/01/2019 12:00:00 am
or 
01/01/2019 12:00:00 ص 
I still get the error message!
What is wrong here? How can I use the Range attribute with dates?
Note: 
my local culture is ar-EG

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @VBAndCs.
Please provide a minimalistic repro project (ideally hosted as a GitHub repo) so we can investigate this further.

**Comment by VBAndCs** [comment]
@mkArtakMSFT
Here is the repo:
https://github.com/VBAndCs/DateRangeSample/tree/master/DateRangeSample
Run the app, click the Add new student link, and try to enter a date in the EnrollmentDate input. All dates will be rejected even dates between 1/1/2019 and 1/1/2020! Try 1/1/2019.
If you commented out the ` [Range(typeof(DateTime),"01/01/2019", "01/01/2020")]` attribute in the Student class, you will be able to enter any date and add the student.
Note that my culture is ar-EG. If this app worked fine with en-US culture, please try it with ar-EG. There is a problem with the generated JavaScript validation code.

**Comment by VBAndCs** [comment]
Note: I tried the app in Google Chrome and chased the date from the dropdown calendar to eliminate any chance of a miss-formatted date, but I still get the same error message!
There is something wrong in the JQuery validation code.

**Comment by mkArtakMSFT** [comment]
Thanks for the info, @VBAndCs.
Actually, the `RangeAttribute` doesn't support `DateTime`-s. So this is by-design.
You can learn more about this on this thread: https://stackoverflow.com/questions/17321948/is-there-a-rangeattribute-for-datetime/17322252#17322252

**Comment by VBAndCs** [comment]
@mkArtakMSFT 
I looked at the link, and this is a bug not by design:
> jQuery validation does not work with RangeAttribute

And msdn says otherwise here: https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.rangeattribute?redirectedfrom=MSDN&view=netframework-4.8 :

> ◦Apply the attribute to a DateTime data field and define a custom validation error message.

```
[Range(typeof(DateTime), "1/2/2004", "3/4/2004",
        ErrorMessage = "Value for {0} must be between {1} and {2}")]
    public object SellEndDate;
```

You should fix the generated JQuery to solve this problem, so I advice you to reopen this issue and find a fix, or provide a decent alternative instead creating a custom class for each range.
And please, don't close any issue before hearing our response. You - the team - seem anxious to close issues as soon as possible, regardless of the quality of your product. I had an issue closed the last week because what so called the lack of response! What on earth is that!!
Please make your product better.
Thanks.

**Comment by VBAndCs** [comment]
@mkArtakMSFT
Another noteL
defining custom validator attribute will validate the date on the server (after posting the page). It is better to use the RangeAttribute to have client side validation. If there is a difficulty with dates, could it be done by a new DateRange attribute?
I wish you solve this issue.
