### ISSUE TITLE
Bidirectional streaming regression on TestServer

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#15415]
A customer attempted to use TestServer to test gRPC services. They weren't able to successfully test calls that use bidirectional streaming.

https://github.com/grpc/grpc-dotnet/pull/624

This functionality worked during 3.0 dev. grpc-dotnet functional tests were run with TestServer. At some point after grpc-dotnet switched to using a local Kestrel instance for functional tests, bidirectional streaming in TestServer stopped working.

### To Reproduce
1. `git clone https://github.com/JamesNK/grpc-dotnet/tree/jamesnk/bidirectionalstreaming-repro`
2. Run `SayHelloBidirectionStreamingTest` at https://github.com/JamesNK/grpc-dotnet/blob/c0a098ce8f44a751608ef1e9ef7ba1238d369aec/examples/Tester/Tests/FunctionalTests/GreeterServiceTests.cs#L101-L126
3. Test will hang on `ResponseStream.MoveNext()` (line 118)
4. Uncomment `RequestStream.CompleteAsync()` (line 116) and run test again
5. Test now passes

### Expected behavior
TestServer should be able to return response content while request is still in progress.

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26
```

**Comment by JamesNK** [comment]
The gRPC method on the server doesn't start at all until the request is completed.

**Comment by JamesNK** [comment]
Hmmm, I'm not sure this is a regression anymore. I was certain this use to work, but test server has called `ReadAsStreamAsync()` forever, and that blocks until the request content is complete.

**Comment by JunTaoLuo** [comment]
Looks like it's a 3.1 candidate.

**Comment by JamesNK** [comment]
Fixed https://github.com/aspnet/AspNetCore/pull/15591
