### ISSUE TITLE
[Blazor] Experience with incorrect parameters in ComponentTagHelper + RenderMode:Server is poor

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#15413]
A couple of scenarios that I discovered when I was doing my verification:

1) `dotnet new blazorserver`
2) In *Pages\_Host.cshtml* edit the `component` tag to use `render-mode="Server"`. Update the tag to also specify an additional parameter `param-value="1"`.
3) Run the page.

The gold bar does not show up, nothing appears in the console or the app's logs and no content appears on the page. You have to turn up the log level to `Debug` to see the actual error which is `value` is not the name of a component parameter. The experience is similarly poor if for instance there's a JSON conversion error (`[Parameter] public int Value { get; set;` <component ... param-value='@RouteData.Values["value"].ToString()' />`

**Comment by javiercn** [comment]
@pranavkm Don't you have a PR for this?

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/pull/15410

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/pull/16636
