### ISSUE TITLE
Blazor WebAssembly: A way to get progress of startup using JavaScript?

### ISSUE THREAD

**Issue by GerritBergen** [aspnet/AspNetCore#15411]
It'd be really nice to show some progress of where the app is in downloading dll or wasm files, and maybe where the app is in loading the whole application before the splash screen disappears.

Is this possible somehow using JavaScript or some other method?

**Comment by DamianEdwards** [comment]
Similar to #13933

I don't believe the required hooks on the JS side exist yet, but I agree it would be a great addition.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GerritBergen.
This is a dupe of the issue @DamianEdwards has reference, so closing this one.
