### ISSUE TITLE
Cannot Signin with Identity in Blazor Server Side Application

### ISSUE THREAD

**Issue by moritz-mm** [aspnet/AspNetCore#15429]
I wrote a simple Blazor Server Side Applicationt to test Blazor and I cannot signin' and signup with Identity, any ideas why this is so?

The Error:

![1](https://user-images.githubusercontent.com/47302595/67618672-9c6c4b80-f7f2-11e9-841c-91d35badebbd.PNG)

My SignIn Code:

![2](https://user-images.githubusercontent.com/47302595/67618673-9c6c4b80-f7f2-11e9-8858-a7ebe1c65000.PNG)

**Comment by moritz-mm** [comment]
Please update the label to area-blazor

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by moritz-mm** [comment]
Ok, here is my Blazor SignIn Component

![1](https://user-images.githubusercontent.com/47302595/67697895-97053180-f9a9-11e9-9097-5f0293ed9f4b.PNG)

And here is my SignIn Code:

![2](https://user-images.githubusercontent.com/47302595/67697920-9ec4d600-f9a9-11e9-86ed-a946f784db60.PNG)


The EditForm calls the SignIn Method, i use normal Identity no IdentityServer

**Comment by javiercn** [comment]
@moritz-mm Seems like you are trying to rewrite the Identity UI in Blazor.

You can't do what you are trying to accomplish as Blazor uses a stateful model and there is no HttpContext available for Identity to use for setting up its cookie.

I'm closing this issue as the recommended way to log-in is to perform a redirect and a form post as in the current default UI.

I'm tagging @blowdart in case he wants to provide guidance about how would someone would write a Blazor-compatible Identity UI.

**Comment by javiercn** [comment]
Filed https://github.com/aspnet/AspNetCore.Docs/issues/15374 so that the requirements for what is needed to log in a user with Identity are.
