### ISSUE TITLE
[Blazor] Frameless browser window

### ISSUE THREAD

**Issue by WillianGruber** [aspnet/AspNetCore#15420]
Is it possible to implement a feature in Blazor to make the browser window frameless as in Electron?

**Comment by javiercn** [comment]
@WillianGruber thanks for contacting us.

If you are talking of server-side blazor or client-side blazor, the short answer is no. They run inside a browser and hence the browser UI will always show up.

The best you can do is make the browser window/tab full screen with F11 to remove the browser frame.

I believe we have some ongoing experiments with blazor an electron, but we are still investigating that space.
