### ISSUE TITLE
dot net core 3.1 sdk installer (windows 10) not working 

### ISSUE THREAD

**Issue by NTiering** [aspnet/AspNetCore#15427]
### Describe the bug
dot net core 3.1 sdk installer (windows 10) not working 

### To Reproduce
1 .Downloaded and run **dotnet-sdk-3.1.100-preview1-014459-win-x86.exe**. No errors and runs to finish

### Expected behavior
dotnet sdk 3.1 should be listed in _dotnet --list-sdks_
dotnet sdk 3.1 should be listed in _C:\Program Files\dotnet\sdk_

### Additional context
Re running the installer offers a repair option, and runs without error, but does not install 3.1

**Comment by blowdart** [comment]
Please open an issue in https://github.com/dotnet/core-setup and then close this one once you have.

**Comment by Pilchie** [comment]
This issue was moved to dotnet/core-sdk#5377
