### ISSUE TITLE
Should Blazor WebAssembly be renamed?

### ISSUE THREAD

**Issue by Doan-Van-Tuan** [aspnet/AspNetCore#15425]
The Blazor name is used for both Client-side and Server-side stack, which are different technologies, leading to confusion and difficulties in searching for online resources.

In order to make things easier for the community, I think MS should find a new name for Blazor Wasm. Wazor anyone?

**Comment by MV10** [comment]
Using the same name for both is accurate. The plan is that Blazor implementations will differ only at the rendering layer and the rest of the stack really will be the same (within reason). There are more Blazor renderers being planned, this chart is from a presentation by Dan Roth last month:

![chart](https://visualstudiomagazine.com/articles/2019/09/26/~/media/ECG/visualstudiomagazine/Images/2019/09/blazor_spectrum2.asxh)

**Comment by Doan-Van-Tuan** [comment]
Thanks, make sense. Later on we will use the renderer name for this purpose.
