### ISSUE TITLE
Scenarios are not running: ConnectionClose, ConnectionClose, HttpClientFactory, PlaintextNonPipelinedLogging, PlaintextNonPipelinedLoggingNoScopes

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#15421]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| ConnectionClose | Windows, Cloud, http, KestrelSockets | 10/24/19 9:51:15 PM +00:00 |
| ConnectionClose | Windows, Cloud, https, KestrelSockets | 10/24/19 9:51:54 PM +00:00 |
| HttpClientFactory | Windows, Cloud, http, KestrelSockets | 10/24/19 9:50:45 PM +00:00 |
| PlaintextNonPipelinedLogging | Windows, Cloud, http, KestrelSockets | 10/24/19 9:52:39 PM +00:00 |
| PlaintextNonPipelinedLoggingNoScopes | Windows, Cloud, http, KestrelSockets | 10/24/19 9:53:24 PM +00:00 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by anurse** [comment]
Seem to be running now.
