### ISSUE TITLE
Use JsonProperty

### ISSUE THREAD

**Issue by NevTheDevsCodeLab** [aspnet/AspNetCore#15433]
I've been trying to get Blazor to use custom property names using the Newtonsoft.Json 'JsonProperty' attribute but so far cannot find a way to make it work. If I create an initial Blazor WebAssembly using the template and modify the 'WeatherForecast' class to...

`public class WeatherForecast
{
    public DateTime Date { get; set; }

    public int TemperatureC { get; set; }

    [JsonProperty("sum")] 
    public string Summary { get; set; }

    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}`

The summary is no longer displayed in the grid even though I can see the data with a 'sum' field in the response. Is this not supported, a bug or have I failed to configure it correctly?

**Comment by Berrysoft** [comment]
Well, you have to use `JsonProperty` attribute in `System.Text.Json`.

**Comment by NevTheDevsCodeLab** [comment]
Thanks Berrysoft, but when I use the attribute '[JsonPropertyName("sum")]' the response json uses "summary" and not "sum", and the UI fails to load the summary details.

**Comment by Berrysoft** [comment]
Sorry, but I cannot reproduce it. I'm using Blazor Client-side 3.1 preview.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by NevTheDevsCodeLab** [comment]
I've just pushed a basic project to: [https://github.com/NevTheDevsCodeLab/JsonPropertIssue](url).
You will notice the 'Summary' column of the grid is blank and yet in the response the 'sum' field is present, so for some reason the client's view model's summary field isn't being bound.

**Comment by Berrysoft** [comment]
@NevTheDevsCodeLab I delete the `Newtonsoft.Json` dependency, install `System.Text.Json` to `BlazorApp_JsonPropertyIssue.Shared`, change `JsonProperty` to `JsonPropertyName`, and delete `AddNewtonsoftJson` in Startup.cs. Then it works.

Note that blazor only uses `System.Text.Json`, therefore you cannot use `Newtonsoft.Json` in the server project.

**Comment by NevTheDevsCodeLab** [comment]
Thank you for the information Berrysoft. I'm pleased to say I now have it working as expected.
