### ISSUE TITLE
model binding IFromFile

### ISSUE THREAD

**Issue by bahmansh** [aspnet/AspNetCore#15430]
I have sent details of this issue in #12223, but my problem is not resolved yet.

thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @bahmansh.
Please provide details about what you are trying to do and what is failing for you. Please also provide a minimalistic repro (ideally as a GitHub repo).

**Comment by mkArtakMSFT** [comment]
@bahmansh also, did you look into @pranavkm 's response in the referenced issue? Didn't that resolve your concerns?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
