### ISSUE TITLE
NetCore 2.2 to 3.0 Migration guide - IsDevelopment wrongly included

### ISSUE THREAD

**Issue by jorgeolive** [aspnet/AspNetCore#15438]
https://docs.microsoft.com/es-es/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio

Hello,

The migration guide from 2.2 to 3.0 has an error. The screenshot with Startup.cs changes related to IWebHostEnvironment is wrong as it still includes IsDevelopment() which is not part of the interface definition. 

Should we check now against a hardcoded environment string such as "Development" against the EnvironmentName property?

Regards,
Jorge

**Comment by marcelstuder** [comment]
The call to IsDevelopment() still works in 3.0 if you add the using statement as stated in the migration documentation:

> Replace IHostingEnvironment with IWebHostEnvironment and add a using statement for the Microsoft.Extensions.Hosting namespace.

see: [Methods](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostingenvironmentextensions?view=dotnet-plat-ext-3.0)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
