### ISSUE TITLE
Blazor Components: Remove ParameterAttribute and allow fields.

### ISSUE THREAD

**Issue by demigor** [aspnet/AspNetCore#15515]
Hi,

Started to port some React components to play with Blazor. 
First thing is stumbled upon is Parameter attribute.

Here is a current snippet from my code:

@functions {
[Parameter]
double? left { get; set; }

[Parameter]
double? top { get; set; }

[Parameter]
double? right { get; set; }

[Parameter]
double? bottom { get; set; }

[Parameter]
double? width { get; set; }

[Parameter]
double? height { get; set; }

[Parameter]
double? star { get; set; }

[Parameter]
double? basis { get; set; }

[Parameter]
bool auto { get; set; }

[Parameter]
bool column { get; set; }

[Parameter]
bool absolute { get; set; }

[Parameter]
bool absoluteLeft { get; set; }

[Parameter]
bool absoluteRight { get; set; }

[Parameter]
bool relative { get; set; }

[Parameter]
bool @static { get; set; }

[Parameter]
bool @fixed { get; set; }

[Parameter]
bool fixedLeft { get; set; }

[Parameter]
bool fixedRight { get; set; }

[Parameter]
bool hidden { get; set; }

[Parameter]
bool wrap { get; set; }

[Parameter]
bool autoScroll { get; set; }

[Parameter]
bool crop { get; set; }

[Parameter]
RenderFragment ChildContent { get; set; }
}

I imagine that ParameterAttribute indicates properties (and only properties) which could be specified from outside. Exactly for the same reason C# has **public** property and field modifiers.
So why couldn't we for the sake of simplicity indicate parameters with public properties and fields? Each public property and field should be a parameter by default.

So the code above could look much simpler and take less time to type:

@functions {
public double? left, top, right, bottom, width, height, star, basis;
public bool auto, column, absolute, absoluteLeft, absoluteRight, relative, @static, @fixed, fixedLeft, fixedRight, hidden, wrap, autoScroll, crop;
public RenderFragment ChildContent;
}

If we want internal fields for state, just use private or protected members like we normally do.

**Comment by rabberbock** [comment]
> Parameters also should not be mutated outside of the normal component life cycle. Parameters should be set through the `IComponent.SetParameters` method. That's why we recommend that parameters not be public. This guidance is implemented as an analyzer, but you can disable it if you want.
> 
> We prefer properties to using fields because it gives component authors the opportunity to insert some code when the parameter is set. Ex you want to do some conversion logic.

@danroth27 Now that Parameters need to be public would you still advise against mutating them outside the component lifecycle, e.g. in a button handler in the child?

**Comment by demigor** [comment]
One has to understand that public properties and fields are set by parent component. So you may mutate them if you need, but next render cycle will set them again. 

I still not get this ceremonial approach for Razor components, looks like MS ppl just get paid for lines of code, not for the end result.
So the more characters you type, the better approach it is.

I miss simplicity of JavaScript React components, where you just define incoming data as props or fields. But Razor went rogue from good ideas and headed the LOC way. And this is just one more obstacle towards the adoption.

**Comment by danroth27** [comment]
> Now that Parameters need to be public would you still advise against mutating them outside the component lifecycle, e.g. in a button handler in the child?

@rabberbock In general, yes, that's still our recommendation. We think of component parameters like parameters to a constructor or method.
