### ISSUE TITLE
Unable to use Microsoft.AspNetCore.Identity.SignInManager with Blazor Server Side

### ISSUE THREAD

**Issue by simonziegler** [aspnet/AspNetCore#15720]
Hi,

I have a Client/Server Blazor project that, among other things, authenticates users using Microsoft.AspNetCore.Identity. The relevant controller uses the SignInManager class from identity.

I am experimenting with migrating this project to Blazor Server Side so that I can improve performance. Calls to a SignInManager object fail however. What I have (unsuccessfully) attempted to do is to make the pre-existing controller a service that is consumed by the App project. Referencing it is fine however I get an exception on calling SignInManager.PasswordSignInAsync. Is this because there is no HttpClient access from the App project, and if so is there a way that I can make this work?

Thank you.

**Comment by Alienroid** [comment]
Trying to get Blazor server-side login to work like rest of the blazor app, to have consistent SPA experience. Currently, the supplied identity sample uses razor page for identity.

I've successfully ported most of the pages. However, I am running into issue on login. The error is 

> System.InvalidOperationException: The response headers cannot be modified because the response has already started. 
It originated from this call: 

> var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: true);

My implementation is have server side page to handle the UI and created a service that does the back-end identity. This design pattern works most of the time, except in the call above, it seems that it is trying to set cookie for the response. On blazor, to set cookie, we need to use jsinterop. So there's no directly way for PasswordSignInAsync to set cookie. 

Update: I experimented by calling PasswordSignInAsync  directly from server side page. It also failed. So technically there's a limitation here that Microsoft needs to address to enable server side login (for cookie authentication from the default identity sample).

**Comment by WillianGruber** [comment]
> I think what we need here is a method to handle signinasync, create the cookie without adding it directly. and the developer can use jsinterop to update the cookie.

@danroth27 any thoughts about this suggestion?

**Comment by Alienroid** [comment]
I like what William suggested. By the way, I posted this on a closed issue. I wonder if people will follow up on this. Or should we open a new one?

Also, SignOutAsync have similar issue as SigninAsync.

For anyone running into similar issue, temporary I use razor page for Login, logoff/logOut, Relogin.

**Comment by thuijzer** [comment]
I ran into the same issue. But it makes sense why you should use Razor pages for login and logout.
When you set a cookie with Javascript (jsinterop) the cookie will always be visible via any Javascript. This creates a XSS safety issue. That's why you want to use HttpOnly cookies only.

**Comment by Alienroid** [comment]
Thomas is correct! I forgot the httpOnly part.
