### ISSUE TITLE
Detect Component Unload Event - OnUnloadAsync()?

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/AspNetCore#15744]
I think there needs to be some way to detect when a component is unloaded so that any code that's running in the background can appropriately check whether the components exists.

As it is in experimenting with a background timer, I ended up creating a component that never releases due to a circular reference and there's no way to check to see whether resources should be released when the component unloads.

**Comment by OmidID** [comment]
> [Dispose component](https://blazor.net/docs/components/index.html#component-disposal-with-idisposable)
I think this is the new link:
https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#component-disposal-with-idisposable
