### ISSUE TITLE
DOM Content ready

### ISSUE THREAD

**Issue by brunohbrito** [aspnet/AspNetCore#15831]
When the DOM Content  is ready for javascript code, the content from Blazor is still loading.

There is any kinda feature to monitor when the Blazor content was loaded from Javascript or from Blazor itself? 

For better compatibility with js api's.

I made a Workaround to create an example:

```
protected override void OnAfterRender()
{
      RegisteredFunction.Invoke<bool>("DocumentReady");
}
```

at a js file:
```
Blazor.registerFunction("DocumentReady", function () {
    if (document.getElementById('someItem') == null)
        return;
   ......
});
```

**Comment by Postlagerkarte** [comment]
@SteveSandersonMS : 

>   Longer term we're tracking this as aspnet/Blazor#674.

Where can find that issue? Or can you tell if the above workaround is still necessary?
