### ISSUE TITLE
Is it currently possible to use Rx.NET in Blazor?

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#15955]
I'm trying to implement the Angular tutorial Tour of Heroes (HTTP) section in our dear Blazor. Here is the Angular sample: https://stackblitz.com/angular/xkyalvboyrj

As you can see, there is an input textbox to enter a search term. The search is performed whenever the user changes the content of the text box. To make the search efficient, rxjs is used. Now I want to emulate this functionality in Blazor, and I wondered if this can be done employing Rx.NET...

God Blazor you!

**Comment by gbukauskas** [comment]
It is possible. Working example is on GitHub: https://github.com/bmsantos/RxBlazor
