### ISSUE TITLE
where does blazor stand with web components?

### ISSUE THREAD

**Issue by touseefbsb** [aspnet/AspNetCore#16033]
reference : https://www.youtube.com/watch?v=7CUO7PyD5zA

web components aim to standardize the UI for web irrespective of how we do web development I just want to know whether brazor will be in sync to that so we can take advantage of that standardized web components and widges at one place, instead of being over whelmed by a lot of ways to build ui widgets.

**Comment by veikkoeeva** [comment]
I'll cross-reference https://github.com/aspnet/AspNetCore/issues/10170 and https://github.com/aspnet/AspNetCore/issues/6218 as discussion (towards the end) touches web components in popular frameworks, their publishing and also design systems built using `lit-html`, `StencilJS` etc. to be consumed as web components in thes popular libraries amongst other cases that are closely related and could perhaps be solved without components. I'll note here explicitly though it's visible in the other threads that I'd like to see a good integration with [Web APIs](https://developer.mozilla.org/en-US/docs/Web/API) and abstractions built on top of those.

I take the opportunity to note [WebAssembly Reference Types](https://www.chromestatus.com/feature/5166497248837632) and along with them WASM access to DOM is coming.

As for my DOM notes, I was thinking offloading operations to web workers. A couple of good examples: https://davidea.st/articles/comlink-simple-web-worker, https://dassur.ma/things/react-redux-comlink/. It appears Google is cracking down (maybe too strong an expression) on performance and bundle sizes and it appears these techniques help. As far as I understand the WASM threading system will be built on web workers and seen from .NET perspective, it's like `ThreadPool`.
