### ISSUE TITLE
Unable to run your project. the "RunCommand" property is not defined.

### ISSUE THREAD

**Issue by uopeydel** [aspnet/AspNetCore#16102]
I do follow this guid.
=> https://blazor.net/docs/get-started.html

![image](https://user-images.githubusercontent.com/12793024/39457191-43a96ce0-4d16-11e8-99c0-3f1383d0d822.png)

At step 4 > Press Ctrl-F5 to run the app without the debugger. Running with the debugger (F5) isn't supported at this time.

When i do it , then dialog pop.

-------

When try "dotnet run"
result is 

![image](https://user-images.githubusercontent.com/12793024/39457699-ef24670c-4d19-11e8-984d-8f422f1ffbb5.png)

How can i do for run blazor?

**Comment by yomiorcas** [comment]
I experienced the same issue but turned out that I didn't add reference to Microsoft.AspNetCore.Blazor.DevServer
