### ISSUE TITLE
Uploading/Reading files?

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/AspNetCore#16231]
Hi,

does any best practice for uploading files into a Blazor-Application exist?
I guess, using the IFormFile Interface from AspNetCore.Http will not work?

Regards, Sascha

**Comment by River39** [comment]
How would this be done with blazor serverside (with out a page load)? the interop doesn't like the file size. all i can come up with for now is do a httppost from javascript (and return an id with interop to query the file to continue the process of the application.)
