### ISSUE TITLE
Provide support for more event types

### ISSUE THREAD

**Issue by aguacongas** [aspnet/AspNetCore#16332]
Set RenderTreeFrame.Attribute public so we can add any event handlers we want, or provide a way to add event handler in BlazorComponent.  
At the moment we cannot bind event on onkeyup for exemple, so we cannot implement autocomplete component.  
I tried to add event like this :  

``` html
<input type="text" @bind(value) onkeyup={ Search(); } />
``` 

but it doesn't work because the binding is done on change.  
I tried with onkeypress binded to an UIEventHandler, it doesn't work because back key or del key events are not raised

**Comment by daniatic** [comment]
I landed here looking for a way to add the *transitionend* event to an element, but I only could find the list of "natively"supported events and that "arbitrary events" are being worked on. How is the state on this? Is the only way to bind to unsupported events by using JSInterop?
