### ISSUE TITLE
Suggestion - Make Blazor MVVM Friendly

### ISSUE THREAD

**Issue by legistek** [aspnet/AspNetCore#16331]
I know that code re-use between desktop/mobile and web is not necessarily the top priority for this project, but there seems to be tremendous opportunity here for just that and I don't think it would detract much - if any - from the main vision.

The most obvious addition would be to have an `ICommand Command` property in `BlazorComponent`s and tie it to `onclick`. This is already doable by making my own `MVVMButton` component and it really works great:

```
<button @onclick(() =>
        {
            this.Command?.Execute(null);
        })>
    @Label
</button>

@functions {
    private ICommand _command;
    public ICommand Command
    {
        get => _command;
        set => _command = value;
    }

    public string Label { get; set; }
}
```

Even this one step is a huge leap toward re-using view models between Blazor and WPF/UWP/Xamarin.Forms apps. 

Wondering if this is an idea the team would be interested in exploring and if so I'd be interested in starting a fork and contributing.

**Comment by DanJBower** [comment]
@legistek Was there any furter discussion on implementing these? I'm just starting out with Blazor and was looking for the best way of implementing MVVM within my blazor web app.

**Comment by legistek** [comment]
> @legistek Was there any furter discussion on implementing these? I'm just starting out with Blazor and was looking for the best way of implementing MVVM within my blazor web app.

Unfortunately no, I've not been able to drum up interest in this among the project maintainers.

Having worked on this extensively myself (on a proprietary project, I'm afraid), the other key item you really need besides use of `INotifyPropertyChanged` is data binding and something equivalent to dependency properties. The main problem is knowing when to trigger render tree refresh based on view model property updates. You can do something simple like define a `ViewModel` property on all your components and subscribe to `PropertyChanged` if the view model implements INPC, and if so call `StateHasCHanged()` in the handler, but this only gets you one level of property change detection - for example, you could bind to `Person.Name` if your `ViewModel` was set to a `Person`, but you couldn't bind to `Person.Father.Name` easily unless your view models already accounted for this issue.

Also the Razor syntax is not particularly friendly to a property binding mechanism. All you can do is assign values directly to component properties, so you can't really do something like:

`<MVVMButton Command=@Binding("MyCommand")>`

unless you defined the `Command` property with a `Binding` data type rather than an `ICommand`, which then makes it awkward to access in C# code.

Sadly my [suggestion that Blazor support markup extensions](https://github.com/aspnet/AspNetCore/issues/7897) to permit this kind of syntax was pretty much immediately shot down.

If we want MVVM in Blazor I think the best bet is to build out a Xamarin Forms backend such as I did in my [prototype](https://github.com/legistek/Xamarin.Forms.Platforms.Blazor). I wish I had more time to work on it.

**Comment by richbryant** [comment]
I don't know if anyone's still interested but [this sort-of works using ReactiveUI](https://github.com/richbryant/Blazor.Reactive), which I admit is not to everyone's taste but it's still a decent example.

I'd like a nicer way to execute ReactiveCommand but luckily, Mladen has allowed me to fork Blazorise, which would provide a beautiful set of components implementing RxUI binding and ReactiveCommands.

**Comment by legistek** [comment]
The problem is change detection. As far as I can tell, Blazor refreshes components if they are subject to some kind of user input event. That works great until you want a component to update in response to action taken on another component (for example, you have two independent components bound to the same view model). To support that you have to either manually rig up property change subscriptions (a disaster waiting to happen) or implement a true data binding mechanism.

**Comment by richbryant** [comment]
RxUI does this by simply having both components subscribe to an observable - it's never been a disaster waiting to happen on any other platform yet.

**Comment by legistek** [comment]
> RxUI does this by simply having both components subscribe to an observable

Well ok but that's completely antithetical to the MVVM pattern.

>  it's never been a disaster waiting to happen on any other platform yet.

Then you're more fortunate than I am. I inherited an Angular project with observables up the ying yang and calling it spaghetti code would have been an insult to spaghetti.

**Comment by richbryant** [comment]
Rx.js can be a pain.  Rx.Net (and especially ReactiveUI) much less so.  What's nice about RxUI is that it's truly, truly cross-platform.  WPF?  Sure.  Winforms?  Totally.  Xamarin?  Absolutely. Avalonia? Yup.   Cool new stuff like Uno?  Right there, because why not?

I also disagree that it's antithetical to the MVVM pattern.  An observable in this case is merely a property of a ViewModel.  Multiple bindings of a single property are common as all hell, otherwise nothing would work.
