### ISSUE TITLE
Blazor with Identity Scaffolding does not work

### ISSUE THREAD

**Issue by RasmusWesterlundh** [aspnet/AspNetCore#16569]
### Describe the bug
I've tried various ways of scaffolding Identity into a Blazor project, none really work.
If you create a new Blazor project and add "Authentication - Individual Accounts" and then add a Identiy-Scaffold, your project no longer complies. This issue is mentioned here also: https://github.com/aspnet/Scaffolding/issues/1094

Upon fixing the build issue by adding the missing "@using", the project builds, but the scaffolding breaks the CSS of the project; creating padding and margins that messes up the application view. [See screenshot here](https://puu.sh/Exu9W/80c7458b17.png).

-----
Not adding Authentication when creating a new project and instead scaffold Identity into a "clean" project also does not work. The project builds, but the application throws an "NotSupportedException".  [Screenshot of error message here](https://puu.sh/ExtX2/000abe9bd1.png)

### To Reproduce
1. Using dotnet Core Version:   3.0.100
2. Creating new Blazor project with Identity ("Authentication - Individual User Accounts")
3. Add new scaffolded Identity to the generated "Identity"-folder and overwrite existing pages
4. Attempt to build. **First Issue appears here!**
5. Fix the build issue on line 3 in "~/Pages/Shared/_Layout.cshtml" (add "@using").
6. Build and launch. The paddings and margins is now messed up for all views.

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@RasmusWesterlundh thanks for contacting us.

@danroth27 Can this be related to the layout being applied?

**Comment by javiercn** [comment]
@danroth27 I fixes the layout issue. Can you retrieve the list of known issues so that we can determine which ones apply and which ones don't?
