### ISSUE TITLE
Blazor Server Show if websockets are not available

### ISSUE THREAD

**Issue by mihaimyh** [aspnet/AspNetCore#16573]
It will be nice to display a message to the user if websockets are not enabled or if SignalR connection cannot be established. 

It will be also nice to redirect the user to another url where Blazor WebAssembly is running.

**Comment by javiercn** [comment]
@mihaimyh thanks for contacting us.

You can do all these things yourself.
```html
<script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        (function start() {
            Blazor.start({
                logLevel: 1, // LogLevel.Debug
                configureSignalR: builder => builder.configureLogging("debug") // LogLevel.Debug
            });
        }).then(() => ... )()
```
1. You can configure logging/signalr to know the transport (I believe).
2. If blazor fails to start it will return a failed promise.
3. From the failed promise you can redirect.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
