### ISSUE TITLE
.Net Core 3 - no CORS headers returned by JWT bearer middleware. Inconsistent with 401 API behaviour

### ISSUE THREAD

**Issue by aford22** [aspnet/AspNetCore#16584]
### Describe the bug
.Net Core 3 - no CORS headers returned by JWT bearer middleware with 401 response. Inconsistent with 401 API behaviour

### To Reproduce
1) Create a .Net Core 3 Web Application with a single API endpoint that performs one action:
```     
        [HttpGet]
        public IActionResult Get()
        {
            return Unauthorized();
        }
```
2) Configure CORS and JWT bearer authentication
3) Call the API with a valid bearer token. The correct headers are returned including the CORS headers:
> HTTP/1.1 401 Unauthorized
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Origin: https://app.opticloud.app
> Access-Control-Expose-Headers: Access-Control-Allow-Origin
4) Call the API with an invalid (i.e. expired or missing) bearer token. The CORS headers are missing:

> AuthenticationScheme: Bearer was not authenticated (from the .Net log)
> HTTP/1.1 401 Unauthorized
> WWW-Authenticate: Bearer error="invalid_token", error_description="The token expired at '10/27/2019 07:01:07'"

### Expected behavior
When the authentication middleware rejects an API call due to failed bearer authentication, the CORS headers should be returned, for two reasons:

1) Keep behaviour consistent whenever .Net returns 401
2) Client applications (Angular in this case) need the CORS headers to be able to properly process the 401 responses. Without them, many modern app frameworks will refuse to process the http response properly

**Comment by javiercn** [comment]
@aford22 thanks for contacting us.

Is the CORS middleware before the authorization middleware in your pipeline?
Can you copy your Startup.cs here?

**Comment by aford22** [comment]
```
public void ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddAuthentication(options =>
            { ... })
            .AddJwtBearer(cfg =>
            { ... }; });

            services.AddCors(c =>
            {
                c.AddPolicy("AllowSpecified", options => options.WithOrigins("https://localhost:4200", "http://localhost:4200", "https://*.opticloud.app").AllowAnyMethod().AllowCredentials().AllowAnyHeader().SetIsOriginAllowedToAllowWildcardSubdomains().WithExposedHeaders("Access-Control-Allow-Origin"));
            });
            services.AddControllers();
        }
```

and

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            ...
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseCors("AllowSpecified");
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers().RequireCors("AllowSpecified");
            });
        }
```

**Comment by javiercn** [comment]
@aford22 I believe app.UseCors needs to be in front of app.UseAuthorization, otherwise the authorization middleware shortcircuits the response.

If you switch it to this, does everything work?
```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            ...
            app.UseCors("AllowSpecified");
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers().RequireCors("AllowSpecified");
            });
        }
```

**Comment by aford22** [comment]
Javier you are absolutely right. Switching the order does indeed ensure the CORS headers are always issued. You fixed the problem!

Now the challenge is, how should MS document this or enforce it in code to make sure others don't hit this same issue?

**Comment by javiercn** [comment]
@aford22 We have documentation here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0#order and I believe we have an analyzer too.

**Comment by javiercn** [comment]
I'm closing this issue as the question has been answered.
