### ISSUE TITLE
UseAngularCliServer: optionally disable dynamic port

### ISSUE THREAD

**Issue by flensrocker** [aspnet/AspNetCore#16582]
See #8162

My usecase for a specific port for `UseAngularCliServer`:

I have one multi-tenant Angular-app which is served on different base-urls, so each tenant has its own url like http://localhost/tenant-1 and http://localhost/tenant-2.

Since the `index.html` is generated by `ng` I have to read it from the ng-server to serve it with a MVC controller on the different routes. I can't use the from a `ng build` pre-generated `ClientApp/dist/tenant/index.html` because on `ng serve` there are only script tags like `runtime.js` instead of `runtime-es5.js` and `runtime-es2015.js`.

The `index.html` contains no base href, it is generated at runtime by the angular app with `{ provide: APP_BASE_HREF, useValue: "/" + (window.location.pathname.split("/")[1] || "") }`

The correct urls for the script-tags are ensured with a `"deployUrl": "/tenant/"` in `angular.json` and there's also the port-setting in `serve:options`.

```
routes.MapRoute(
   name: "tenantapp",
   template: "{urlprefix}/{*urlargs}",
   defaults: new { controller = "View", action = "Index" });

...

private IHostingEnvironment _env;

public async Task<IActionResult> Index(string urlprefix, string urlargs)
{
  if (_env.IsDevelopment())
  {
    var proxy = new System.Net.Http.HttpClient();
    var index = await proxy.GetAsync("http://localhost:4302/tenant/index.html");
    var indexStream = await index.Content.ReadAsStreamAsync();
    return File(indexStream, "text/html");
  }
  return PhysicalFile(System.IO.Path.Combine(_env.ContentRootPath, "ClientApp", "dist", "tenant", "index.html"), "text/html");
}
```
Currently this only works with `UseProxyToSpaDevelopmentServer` where I can define the specific port in `angular.json`.

Additionally there are more Angular apps in this project, which are all served on there own ports.

It would be nice to disable this behaviour either via the `SpaOption` or an additional argument of `UseAngularCliServer`.

**Comment by flensrocker** [comment]
Since the same logic is used at the `ReactDevelopmentServerMiddleware`, an extension of the `SpaOption` may be the better solution.

Something like:
```
public class SpaOptions
{
    ...
    public int ProxyPort { get; set; } = 0;
    ...
}

...

private static async Task<AngularCliServerInfo> StartAngularCliServerAsync(
            string sourcePath, int portNumber, string scriptName, string pkgManagerCommand, ILogger logger)
{
    var nodeArguments = "";
    if (portNumber == 0)
    {
        portNumber = TcpPortFinder.FindAvailablePort();
        nodeArguments = $"--port {portNumber}";
    }
    logger.LogInformation($"Starting @angular/cli on port {portNumber}...");

    var scriptRunner = new NodeScriptRunner(
        sourcePath, scriptName, nodeArguments, null, pkgManagerCommand);
    ...
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for the issue and the PR, @flensrocker.
We'll look into this soon.
