### ISSUE TITLE
Cross platform inconsistency

### ISSUE THREAD

**Issue by a20081860** [aspnet/AspNetCore#16603]
Hellow
"Microsoft.Extensions.DependencyModel.dll" Cross platform issues exist.

int num = DependencyContext.Default.CompileLibraries.Count     ;
num  in   Windows                   value is not 0  .
num  in   Linux（centos7）      value is 0
Microsoft.Extensions.DependencyModel.dll  version  2.1.0   and  3.0.0

What's the reason

**Comment by mkArtakMSFT** [comment]
This issue was moved to dotnet/core-setup#8681
