### ISSUE TITLE
SignalR not connecting on Asp.Net Core 3.0, (app upgraded from 2.2)

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#16606]
_From @mikedcooper on Sunday, October 27, 2019 7:51:40 PM_

I have followed the upgrade guide to upgrade my 2.2 app to 3.0.  Seems to work fine... I have added Blazor Server Side, this seems to work just fine.  I have added SignalR and I can't get it to connect.  When I create a new 3.0 web application and follow the chat sample guide it works fine.  I can't seem to figure out what is causing signalR to fail in my upgraded 2.2 to 3.0 app.  Any help would be great!.  I am using the JS example.  Everything is as it is in the sirgnalR signalR .Net core example.

Startup Configuration
`services.AddDbContext<ApplicationDbContext>(options =>
                {
                    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"),
                        providerOptions => providerOptions.EnableRetryOnFailure());
                });

            services.AddIdentity<ApplicationUser, ApplicationRole>(config => config.SignIn.RequireConfirmedEmail = false)
                .AddRoles<ApplicationRole>()
                .AddRoleManager<RoleManager<ApplicationRole>>()
                .AddSignInManager<SignInManager<ApplicationUser>>()
                .AddDefaultTokenProviders()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultUI();

            services.AddTransient<IEmailSender, EmailSender>();
            services.Configure<AuthMessageSenderOptions>(Configuration);

            services.AddAutoMapper(typeof(Startup).Assembly);

            //services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddControllersWithViews().AddRazorRuntimeCompilation();
            services.AddRazorPages().AddRazorRuntimeCompilation();
            services.AddServerSideBlazor();
            services.AddSignalR(hubOptions =>
            {
                hubOptions.EnableDetailedErrors = true;
                hubOptions.KeepAliveInterval = System.TimeSpan.FromMinutes(1);
            });`

Startup Configure
`loggerFactory.AddSerilog();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                //app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapBlazorHub();
                endpoints.MapHub<ChatHub>("/chatHub");
            });
`
Logs on server
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 POST https://localhost:44353/_blazor/negotiate text/plain;charset=UTF-8 0
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint '/_blazor/negotiate'
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager: Debug: New connection OBDDQEpKfNHaUi04o64sqA created.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Sending negotiation response.
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/_blazor/negotiate'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 15.3832ms 200 application/json
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET https://localhost:44353/_blazor?id=OBDDQEpKfNHaUi04o64sqA  
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint '/_blazor'
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Establishing new connection.
Microsoft.AspNetCore.SignalR.HubConnectionHandler: Debug: OnConnectedAsync started.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Debug: Socket opened using Sub-Protocol: '(null)'.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Debug: Waiting for the application to finish sending data.
Microsoft.AspNetCore.SignalR.HubConnectionContext: Debug: Failed connection handshake.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Debug: Socket closed.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager: Debug: Removing connection OBDDQEpKfNHaUi04o64sqA from the list of connections.
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/_blazor'

Logs on Client
[2019-10-27T19:48:46.612Z] Information: Normalizing '_blazor' to 'https://localhost:44353/_blazor'. blazor.server.js:1:5212
[2019-10-27T19:48:46.714Z] Information: Normalizing '/chatHub' to 'https://localhost:44353/chatHub'. Utils.ts:174:39
[2019-10-27T19:48:46.716Z] Debug: Starting HubConnection. Utils.ts:178:39
[2019-10-27T19:48:46.719Z] Debug: Starting connection with transfer format 'Text'. Utils.ts:178:39
[2019-10-27T19:48:46.721Z] Debug: Sending negotiation request: https://localhost:44353/chatHub/negotiate. Utils.ts:178:39
[2019-10-27T19:48:47.062Z] Debug: Selecting transport 'WebSockets'. Utils.ts:178:39
[2019-10-27T19:48:47.075Z] Information: WebSocket connected to wss://localhost:44353/_blazor?id=LqpMgrUL9r5KYKJRkl0PKA. blazor.server.js:1:5212
[2019-10-27T19:48:47.160Z] Information: WebSocket connected to wss://localhost:44353/chatHub?id=mSpchMXV7nrcreV12c0sRQ. Utils.ts:174:39
[2019-10-27T19:48:47.161Z] Debug: The HttpConnection connected successfully. Utils.ts:178:39
[2019-10-27T19:48:47.162Z] Debug: Sending handshake request. Utils.ts:178:39
[2019-10-27T19:48:47.164Z] Debug: Hub handshake failed with error 'WebSocket is not in the OPEN state' during start(). Stopping HubConnection. Utils.ts:178:39
[2019-10-27T19:48:47.167Z] Debug: HttpConnection.stopConnection(undefined) called while in state Disconnecting. Utils.ts:178:39
[2019-10-27T19:48:47.167Z] Error: Connection disconnected with error 'WebSocket is not in the OPEN state'. Utils.ts:168:39
[2019-10-27T19:48:47.168Z] Debug: HubConnection.connectionClosed(WebSocket is not in the OPEN state) called while in state Connecting. Utils.ts:178:39
[2019-10-27T19:48:47.168Z] Debug: HubConnection failed to start successfully because of error 'WebSocket is not in the OPEN state'. Utils.ts:178:39
WebSocket is not in the OPEN state

### Expected  behavior
I expect it should work as it does when creating a new project and in the sample

### Actual behavior
The connection fails as the web socket is not in the open state

_Copied from original issue: SignalR/SignalR#4425_

**Comment by BrennanConroy** [comment]
_From @mikedcooper on Monday, October 28, 2019 1:46:14 AM_

I have found that forcing the connection to long polling seems to alow the connection to work.  Any ideas as to why websockets will not work?  Or troublshooting ideas, I am a little new :)  Thank you

`
endpoints.MapHub<ChatHub>("/chatHub", options =>
                {
                    options.Transports = AspNetCore.Http.Connections.HttpTransportType.LongPolling;
});
`

**Comment by mikedcooper** [comment]
Not sure why this was closed, the I still can not use websockets.  Thanks

**Comment by BrennanConroy** [comment]
@mikedcooper There is an issue in 3.0 with the JS client that makes fallback from WebSockets to other transports not work correctly. This will be fixed when 3.0.1 is released.

How are you hosting your app currently? What OS are you on?

> When I create a new 3.0 web application and follow the chat sample guide it works fine.

Are you saying the WebSockets is working in that case?

**Comment by mikedcooper** [comment]
I am on windows 10, I am developing in VS2019(16.3.6).  I am just using IIS Express.  
Yes when I create a new 3.0 web app and follow the signalR chat example it workes and connects on websockets without issue.  Also I do noitce that blazer takes 2 or 3 tries to get a successful connection as well.

**Comment by BrennanConroy** [comment]
I'm a bit stumped on this one. The connection is "connected", but then looks like it immediately gets disconnected as it is trying to send the handshake.

Is there anyway you can provide a simple github repo that reproduces the issue?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
