### ISSUE TITLE
Update to Azure Asp.Net Core Logging Extension/Integration Breaks Net Core Blob Logging

### ISSUE THREAD

**Issue by DanielStout5** [aspnet/AspNetCore#16604]
### Describe the bug

We have a .Net Core app running on Azure App services and it's configured to log to the Azure Blob.

It's running .Net Core 2.2 and previously the logs were written to the Blob storage correctly. At some point the site extension got updated and now the logs aren't working - only the "applicationLog.csv" file is created in the Blob, not the .txt file that actually contains the application logs.

The app service for which logging has stopped working is using ASP.NET Core Logging Integration version "3.1.0-preview1-19508-20".

Some of our other app services (also running on .Net Core 2.2, and some on 2.1) are using these site extensions:

ASP.NET Core Logging Extensions version "2.2.0"

ASP.NET Core Extensions version "2.1.0-preview2-final"

Is it possible the 3.x versions of the extension are not compatible with 2.x app services?

**Comment by Pilchie** [comment]
@anurse  thoughts?

**Comment by anurse** [comment]
Something does seem to be messed up with the site extension. It seems to be missing 3.0 content as well. cc @davidfowl

**Comment by jkotalik** [comment]
Yeah both the 3.0 and 3.1 are missing content. They only have ones for 2.1 and 2.2.

@DanielStout5 I don't see why a 2.x application would stop logging though; the only thing that seems weird is that you are targeting 2.1-preview2

**Comment by anurse** [comment]
Going to dupe this over to https://github.com/aspnet/AspNetCore/issues/15381 . It's a very similar issue. We need to crack open the site extension and figure out what's going on.
