### ISSUE TITLE
PreventDefault and StopPropagation don't work at runtime

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#16611]
Trying to use either of these new features breaks at runtime: https://github.com/aspnet/AspNetCore/issues/14517

The issue seems to be that the Blazor runtime doesn't support adding attributes after an element has had content frames added? @SteveSandersonMS / @rynowak is that true?

Next because the Razor compiler outputs the prevent default/stop propagation in the order in which it does the runtime barfs.

The reason why this was missed is because it involved several moving parts of which required Runtime, Tooling and SDK. 

![image](https://user-images.githubusercontent.com/2008729/67706160-7ae79d00-f975-11e9-92a8-633029b5d81d.png)

![image](https://user-images.githubusercontent.com/2008729/67706133-6c998100-f975-11e9-9ab1-2ba14a0f6201.png)

Generated C#:
```C#
            __builder.OpenElement(5, "button");
            __builder.AddAttribute(6, "class", "btn btn-primary");
            __builder.AddAttribute(7, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 7 "C:\Users\nimullen\source\repos\BlazorApp4\BlazorApp4\Pages\Counter.razor"
                                          IncrementCount

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(8, "Click me");
            __builder.AddEventStopPropagationAttribute(9, "onclick", 
#nullable restore
#line 7 "C:\Users\nimullen\source\repos\BlazorApp4\BlazorApp4\Pages\Counter.razor"
                                                                                    true

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
```

@danroth27 @mkArtakMSFT I'll work on figuring out the fix so we can understand which release makes the most sense.

**Comment by SteveSandersonMS** [comment]
Yes, attribute frames must be added as part of a continuous sequence of attribute frames directly after the element is opened. This is part of what makes tree traversal much faster and simpler at runtime.
