### ISSUE TITLE
Scenarios are not running: SignalRBroadcast, SignalREcho

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#16613]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| SignalRBroadcast | Linux, Physical, http, KestrelSockets | 2019-10-27 19:43:37Z |
| SignalREcho | Linux, Physical, http, KestrelSockets | 2019-10-27 19:49:41Z |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by jkotalik** [comment]
These are running.
