### ISSUE TITLE
[Blazor] WASM Extension for 2D Vector drawing

### ISSUE THREAD

**Issue by GeorgeS2019** [aspnet/AspNetCore#16612]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Currently there are two ways to create Web 2D Vector graphics using C# 

- [Blazor Canvas Extension ](https://github.com/BlazorExtensions/Canvas/issues/49#issue-513201616)
- UNO UWP XAML running as WASM on the web through [SkiaSharp (WASM)](https://github.com/mono/SkiaSharp/issues/750)

The feature request would be to combine the above two possibilities in ONE Single Blazor Extension using Skia CanvasKit (WebGL). I would like community to evaluate the need for native WASM skiaSharp as a Blazor Extension that by pass the need for JSInterop.

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

Native WASM **skiaSharp as a Blazor Extension** that **by pass the need for JSInterop.**

Propose a new label "**Area-Blazor-Canvas**" to focus users on the need to make 2D vector graphics drawing through Blazor good performance.

### Additional context

- Many different users are attempting to address the slow performance through JSInterop for 2D Vector drawings for Blazor. 

-  [Blazor-Canvas](https://github.com/isc30/blazor-canvas/issues/1#issue-513502222) 
- [Official ](https://github.com/BlazorExtensions/Canvas)[Blazor Extension/Canvas] 
- [BlazorUnmarshalledCanvas](https://github.com/jhwcn/BlazorUnmarshalledCanvas)

The seem promising way to by pass JSInterop is to have [native SkiaSharp WASM](https://github.com/mono/SkiaSharp/issues/750#issuecomment-519989810)

Currently it is possible using Javascript to use Skia Canvaskit Webgl

**Comment by javiercn** [comment]
This sounds like a great feature, but unfortunately this is not something that we would include in the core framework.
