### ISSUE TITLE
*.pubxml files contain outdated link

### ISSUE THREAD

**Issue by bdcoder2** [aspnet/AspNetCore#16624]
### Describe the bug

The link included in {projectname}.pubxml files is out-dated.

### To Reproduce
1. Using Visual Studio 2019 Community 16.3.6
2. Create a new project - I created an EMPTY ASP.Net Core 3.0 web application.
3. Right-click on project name -> Publish...
4. Pick a publish target -> Click on Folder
5. Click the Browse... button to choose a folder (not really relevant, but let say D:\ws0 - then click Open
6. Click the down arrow to the right of the "Publish" button and select "Create profile"
7. In the solution explorer, open the file file: {projectname}.pubxml
8. The file will contain the following comments:

```
<?xml version="1.0" encoding="utf-8"?>
<!--
This file is used by the publish/package process of your Web project. You can customize the behavior of this process
by editing this MSBuild file. In order to learn more about this please visit https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
```

Referencing the link in the comments, i.e.:
[https://go.microsoft.com/fwlink/?LinkID=208121](https://go.microsoft.com/fwlink/?LinkID=208121)

Brings you to a page that states:

> We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported.

### Expected behavior
I would expect two links to be present in the comments section of the .pubxml file:

1.  A link to a page that describes the publish command (or the utility that reads this file), I ASSUME it would be: [https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)  (applicable for ASP.Net Core 3.0, I assume so Dr. Watson!)

2. More importantly - **A link to the entire schema for a .pubxml file** - which contains a full description of every node and attribute that is valid within a .pubxml file.  Where is that gem hidden?  I have yet to find a complete spec within a single page or article !!  (apologies in advance if it does exists).

### Screenshots
I was going to include one, but it was too late as I could not reach my camera after I put my head through the wall!

**Comment by javiercn** [comment]
@bdcoder2 thanks for contacting us.

We've routed the issue to the right team, however, in order for them to see it, it is best if you also report it through the right top corner "Send feedback" button in Visual Studio.

@vijayrkn This is VS Publish, isn't it?
