### ISSUE TITLE
AspNetCore 3.0 Does not set Identity Cookie

### ISSUE THREAD

**Issue by buehler** [aspnet/AspNetCore#16626]
### Describe the bug
The http response after a `signInManager.PasswordSignInAsync` does not set the identity cookie. The cookie is (as I'm aware of) sent over the wire, but it is not stored. 

It worked a while ago, but now, even though the cookie is sent, it is not stored. Could this relate to any changes made to chrome?

### To Reproduce
- Create a new web application project with individual accounts (so that default identity is used)
- Try to login.

### Expected behavior
I can login :-)

### Screenshots
![image](https://user-images.githubusercontent.com/1067213/67746050-fa34a980-fa25-11e9-943d-e61b77a47679.png)

### Additional context
Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

**Comment by buehler** [comment]
Note: Anti-Forgery cookies are set. 🤔

**Comment by buehler** [comment]
Another addition:
When I change the name of the cookie, it seem to work:
![image](https://user-images.githubusercontent.com/1067213/67747359-d161e380-fa28-11e9-8393-39390c61e948.png)

This does not make any sense to me :-(
Is the size limited? If so (in chrome) is there any chance to clamp the size of an identity cookie?

**Comment by javiercn** [comment]
@buehler thanks for contacting us.

@blowdart Can this be the cookie change in Chrome?

**Comment by blowdart** [comment]
No it can't. Those changes are only in 3.1 previews, and chrome won't have them until Feb

**Comment by javiercn** [comment]
@blowdart Ok, then I'll let this go through your regular triage process.

**Comment by blowdart** [comment]
@buehler Does this happen in all browsers?

**Comment by buehler** [comment]
@blowdart Let me check...

**Comment by buehler** [comment]
So:
- Brave (Version 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)): Cookie not stored when default name (`.AspNetCore.Identity.Application`)
- Chrome (Version 78.0.3904.70 (Official Build) (64-bit)): Works
- Edge (Microsoft Edge 44.18362.10024.0): Works
- Chromium (Version 78.0.3904.70 (Official Build) (64-bit)): Works
- FireFox (70.0 (64-bit)): Works

Ok. So my guess is, this is a Brave browser issue.
Well.. I thought it could not be because beneath Brave is chromium.
I guess I'm going to report it there :-)

Thanks for your help!
