### ISSUE TITLE
Dependency Injection in Hubs

### ISSUE THREAD

**Issue by bidianqing** [aspnet/AspNetCore#16623]
I want use SignglR，Created a `NotificationHub` derived `Hub`
![image](https://user-images.githubusercontent.com/12196280/67732703-2d336900-fa37-11e9-9ba4-2736f65fc5e9.png)
How can i set up `IUserService` dependency injection in `NotificationHub` constructor? Transient? Scoped? or Singleton? thanks

**Comment by bidianqing** [comment]
```
public class NotificationHub : Hub
{
    private readonly IUserService _userService;
    public NotificationHub(IUserService userService)
    {
        _userService = userService;
    }

    public override Task OnConnectedAsync()
    {
        return base.OnConnectedAsync();
    }

    public override Task OnDisconnectedAsync(Exception exception)
    {
        return base.OnDisconnectedAsync(exception);
    }
}

```

**Comment by davidfowl** [comment]
Either works. The lifetime is up to you and what level of statefulness your service needs.

**Comment by jkotalik** [comment]
Seems like your question has been answered. Feel free to reopen if you have more questions.
