### ISSUE TITLE
In Blazor- Using Tvalue for <CascadingValue> tag to get the component instance in other page.

### ISSUE THREAD

**Issue by Indrajith-Sync** [aspnet/AspNetCore#16630]
##Description 
Is there any possibility of getting the instances of the component to another razor page using the Tvalue in <CascadingValue> Tag.

For eg:- 
> Page 1
`<CascadingValue TValue="test" />`

> Page 2
I need to get like the page instance like below.

`this.test`

Is this possible in blazor ?

**Comment by SteveSandersonMS** [comment]
I'm not sure why you're trying to specify `TValue`. You only need to use `Value`, e.g.:

```razor
<CascadingValue Value="test">...</CascadingValue>
```
