### ISSUE TITLE
dotnetcore web app and blazorwasm client side together

### ISSUE THREAD

**Issue by alikarooni** [aspnet/AspNetCore#16635]
which one of the following scenarios I am able to implement?

publishing blazorwasm client-side into exe file( instead of using IIS or apache or Nginx) so I can run it as a windows service
OR
Embedding a dot net core app and blazorwasm client-side (not server side which I know about it already) into the same project

Any idea ???

**Comment by alikarooni** [comment]
publishing blazorwasm client-side into exe  => instead of using IIS or apache or Nginx !!!

**Comment by alikarooni** [comment]
Thanks, fo comment.
In the client-side blazor, we have to register App.razor using "app.AddComponent<App>("app");" in the startup file which means we have to inject IComponentApplicationBuilder which we don't have this interface in the dot net core web applications. I have tried to import blazor dependencies in the project file. which leads to a conflict between blazor and aspnetcore dependencies.

As you said, I can go for option 2 and load .razor pages inside .cshtml pages. but by doing so, then _ won't have blazorwasm routing(e.g. I have to use asp routing) which means it's not SPA anymore..

What I really like to have is to be able to host boazorwasm in the windows services (the same as aspnetcore web application)by executing as exe file instead of using apache or IIS.

Do you think I am able to do that?

**Comment by javiercn** [comment]
@alikarooni that is possible by setting up the hosted app as a windows service.

Create a Blazor hosted app and follow the steps in here:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.0&tabs=visual-studio

**Comment by alikarooni** [comment]
I have looked at it already.
I am going to describe the situation a bit in more detail if you bare with me.
first, Check this out https://hackernoon.com/aspnet-core-blazor-hosting-models-2c35330qz.
This guy explains all possible types of blazor. There is NO way to create a windows server to host blazorwasm client-side, the same way that we can create dotnetcore application in the link you have provided (just client side. No signal-R connection. No server-side blazor. something the same as react). I am talking about Razor Components and App.razor. not .cshtml, who can host .razor pages and not server-side blazor.

**Comment by alikarooni** [comment]
I also create a blazorwasm project template and have put these lines :
<RazorLangVersion>3.0</RazorLangVersion>
    <OutputType>Exe</OutputType>
    <LangVersion>preview</LangVersion>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>

into the project file. As you can predict, no exe file would create.

**Comment by alikarooni** [comment]
https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables

The link that you have sent to me just works for .netcoreapp. but when you run "dotnet new blazorwasm" the template framework is netstandard2.0.
that's why it raises an error while publishing. and that's why I said you cannot make an .exe file from blazorwasm client-side.

Do you have any more idea?

**Comment by alikarooni** [comment]
After all, this could help a bit.

dotnet new blazorwasm -ho and publish single-file executable for the host is the closest you are going to get. You need an HTTP server to serve the files.

You can run the web app as a windows service. See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.0&tabs=visual-studio


I've read somewhere that blasorwasm is kind of in-process (the same as all .netcore3.0) and that's why you can only create a template using CLI and it is not in the visual studio new project dialog yet, but I think they would implement the part to creating an exe file from blasorwasm client-side without any requirement of combination, or I think they should think about implementing it.
