### ISSUE TITLE
Cannot find the AspNetCore Nuget packages for 3.0 (specifically routing)

### ISSUE THREAD

**Issue by redshiftz** [aspnet/AspNetCore#16638]
While developing a large number of microservices, I would like to standardize the heath check middleware calls into a package for reuse.

But I cannot find a nuget package for this .net standard 2.1 project to use that will allow me access to IEndpointRouteBuilder. (Microsoft.AspNetCore.Routing.dll)

The version i need appears to be embedded in Microsoft.AspNetCore.App but not available by itself as a nuget package (at least not on nuget.org). Other 3.0 assemblies are needed as standalone nuget packages as well. 

Is my answer to create and host my own 3.0 nuget package for Microsoft.AspNetCore.Routing? 

Any help is appriciated.

**Comment by pranavkm** [comment]
@redshiftz the package was removed as part of the 3.0 release. See https://github.com/aspnet/Announcements/issues/325. To reference the feature, you'll need to add a framework reference to `Microsoft.AspNetCore.App`. Our migration guide - https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio - has details about adding a framework reference as also [cross-compiling your library](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrate-libraries-via-multi-targeting) in case you need to support ASP.NET Core 2.x and earlier as well as ASP.NET Core 3.0 in your library.

**Comment by redshiftz** [comment]
I tried the migration by adding 
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
to my extension project which is netstandard2.1
It throws the error NETSDK1 "The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized."

**Comment by pranavkm** [comment]
@redshiftz you'll need a 3.0 compatible SDK (https://dotnet.microsoft.com/download). In addition, you have to target `netcoreapp3.0` or later. Please follow the migration guide I linked earlier.
