### ISSUE TITLE
Problem Deserialize JsonException with Newtonsoft

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#16633]
Hello guys, i met a problem to deserialize JsonException (from System.Text.Json) with newtonSoft.

I can have this kind of exception when for example there is an error in a Js call supposed to return data. 

I have a really surprised exception : Error: System.Runtime.Serialization.SerializationException: Member 'HelpURL' was not found.
It's surprising because i have no idea what is this property (not in my code, and the only reference i find on this HelpUrl on the .net core is on the class WarningException)

I create a really simple reproduction exemple here : https://github.com/julienGrd/BlazorBugSerializationJsonException

to reproduce :
- launch the app
- click on the button
-- the methode call a js code with error, it return an incompatible object with what exepcted, so a JsonException is thrown
-- On the catch, i try to serialise then deserialise exception, the error is here 

I feel there is a lack of Serializable attribute on the JsonException class.

Thanks for your help !

Julien

**Comment by javiercn** [comment]
Thanks for contacting us @julienGrd.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

**Comment by julienGrd** [comment]
Hello Javier, its not a question but definitively à bug. With this behavior im unable To send the exception To my controller when i run my app in client side and this type of exception happen (i want To send it To controller To log it)
There is no reason this class cant be serialised.

**Comment by javiercn** [comment]
@julienGrd There's nothing involving Blazor here.

JsonException is a type from `https://docs.microsoft.com/es-es/dotnet/api/system.text.json.jsonexception?view=netcore-3.0` and you are trying to serialize it with JSON.NET which is a third party library too.

I suggest you either ask the corefx folks or the JSON.NET folks, but ultimately you can write a JsonConverter for it as in https://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm
