### ISSUE TITLE
Blazor - StateHasChanged throw "the render handle is not yet assigned"

### ISSUE THREAD

**Issue by jesusquintanilla** [aspnet/AspNetCore#16646]
### I'm trying update de UI using StateHasChanged() method, but this throw 

> System.InvalidOperationException: The render handle is not yet assigned.

### Describe the bug
I use de JSInterop, first call a JS function, this function call a C# method, in this point all see good, but when add item at list, and try update, it not working

```
<h3>Count @Folders.Count()</h3>

@code {
    private List<string> Folders = new List<scring>();
    [JSInvokableAttribute("GetAsync")]
    public static async Task GetAsync()
    {
        Console.WriteLine("Group");
        Pages.Index inss = new Pages.Index();
        await inss.GetFolders();
    }
    private async Task GetFolders()
    {
        Folders.Add("12" );
        Console.WriteLine("Call StateHasChanged");
        StateHasChanged();
        Console.WriteLine("StateHasChanged");
    }
}
```

Started show Count 0, but not change to 1.

Console browser.

```
blazor.webassembly.js:1 Uncaught (in promise) Error: System.InvalidOperationException: The render handle is not yet assigned.
  at Microsoft.AspNetCore.Components.RenderHandle.ThrowNotInitialized () <0x2b0b458 + 0x0000c> in <79f1a91c13df4c50b01e437f9a5bf79e>:0 
  at Microsoft.AspNetCore.Components.RenderHandle.Render (Microsoft.AspNetCore.Components.RenderFragment renderFragment) <0x1f98bb8 + 0x0000c> in <79f1a91c13df4c50b01e437f9a5bf79e>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged () <0x1f989f8 + 0x0005c> in <79f1a91c13df4c50b01e437f9a5bf79e>:0 
    at Object.endInvokeDotNetFromJS (blazor.webassembly.js:1)
    at Object.invokeJSFromDotNet (blazor.webassembly.js:1)
    at _mono_wasm_invoke_js_marshalled (mono.js:1)
    at wasm-function[6322]:0x129810
    at wasm-function[1962]:0x6063e
    at wasm-function[565]:0x12891
    at wasm-function[565]:0x12eca
    at wasm-function[565]:0x12c35
    at wasm-function[565]:0x12c35
    at wasm-function[565]:0x127a3
```

**Comment by javiercn** [comment]
@jesusquintanilla Thanks for contacting us.

You are instantiating the component yourself, hence so it's not initialized by the framework and hence you are seeing that error.

That is not a supported scenario as the framework controls the lifecycle of the components.

https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0

**Comment by jesusquintanilla** [comment]
> @jesusquintanilla Thanks for contacting us.
> 
> You are instantiating the component yourself, hence so it's not initialized by the framework and hence you are seeing that error.
> 
> That is not a supported scenario as the framework controls the lifecycle of the components.
> 
> https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0

Ok, i understand the lifecycle, (i believe), but how can i update the count? i try everything and not working.

Or another way to resolve this?

**Comment by javiercn** [comment]
I would perform a JS interop call to the JS side to pass in a DotNetObjectReference with a reference to the current component and I would have an instance method that is JSInvokable and that does Invoke(() => StateHasChanged())
