### ISSUE TITLE
QueryHelpers.AddQueryString throws ArgumentNullException when providing a dictionary with null values

### ISSUE THREAD

**Issue by andre-ss6** [aspnet/AspNetCore#16647]
```cs
QueryHelpers.AddQueryString("foo", new Dictionary<string, string> { ["bar"] = "bar", ["baz"] = null })
```

This throws an `ArgumentNullException` at
```
  + System.Text.Encodings.Web.TextEncoder.Encode(string)
  + Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString(string, IEnumerable<KeyValuePair<string, string>>)
```

There are 3 issues with this:

1 - The [docs ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.queryhelpers.addquerystring?view=aspnetcore-3.0#Microsoft_AspNetCore_WebUtilities_QueryHelpers_AddQueryString_System_String_System_Collections_Generic_IDictionary_System_String_System_String__) for this method mention no exception.
2 - The exception comes from another code deep in the call chain. Should this be the normal behavior (not accepting nulls), there should be validation in the method itself.
3 - I think this should accept nulls anyway. Just return `foo?bar=bar&baz=`

### To Reproduce
1. Using Microsoft.AspNetCore.WebUtilities 2.2.0
2. Run the mentioned code
3. See error

### Expected behavior
`foo?bar=bar&baz=` is returned

**Comment by javiercn** [comment]
@andre-ss6 thanks for contacting us.

@Tratcher this is in Http abstractions isn't it?

**Comment by andre-ss6** [comment]
I would like to fix this if it's simple enough for a first PR 😊

**Comment by attrib75** [comment]
> I would like to fix this if it's simple enough for a first PR

@andre-ss6 are you still planning to do this? If not I'd take a stab at it

**Comment by andre-ss6** [comment]
> > I would like to fix this if it's simple enough for a first PR
> 
> @andre-ss6 are you still planning to do this? If not I'd take a stab at it

Yes! Please :( Hehe.

I've been really busy these last weeks so I haven't managed to get some time to start this, but I'm planning to do it in the next days.

Btw, I don't think this is a big priority for the team, but if it is, I can try to quicken up.

**Comment by attrib75** [comment]
No worries.  I'll keep an eye out for another good one

**Comment by andre-ss6** [comment]
@Tratcher I've just submitted a PR for this. I've remembered, though, that as I had mentioned these methods are missing docs for the exceptions that they throw. Should I add that as well?

**Comment by Tratcher** [comment]
Feel free.
