### ISSUE TITLE
Visual Studio 2019 Preview 4, wont compile a particular cshtml file.

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#16641]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/651648/visual-studio-2019-preview-4-wont-compile-a-partic.html)._

---
When compiled VS reports several errors on particular index.cshtml file. Other cshtml file compile with no problem. Several different error types are thrown To get a minimal case I removed all lines except the following line, 

`@using Connect.Security.Claims`

It throws 2 errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1002	; expected	ConnectV2	D:\shlamb2\Source\Repos\ConnectV2\ConnectV2\Areas\Facilities\Views\Buildings\Index.cshtml	61	Active
Error	CS1002	; expected	ConnectV2	D:\shlamb2\Source\Repos\ConnectV2\ConnectV2\Areas\Facilities\Views\Buildings\Index.cshtml	61	Active

Other pages have the same include line and but don't have any problems, also Visual Studio 2019 16.1.1 compiles the full page as well as the minimal version with the using statement with no problems.

I have deleted the index.cshtml file and recreating it from scratch, but that doesn't help.

Thanks,

Scott

---
#### Visual Studio Feedback System on 7/18/2019, 11:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/19/2019, 01:44 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
We don't have enough information to troubleshoot this issue.

We would need a minimalistic repro so that we can troubleshoot the problem.

**Comment by javiercn** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and we will re-evaluate the issue.
