### ISSUE TITLE
How to dynamically switch child content in blazor pages

### ISSUE THREAD

**Issue by SariDev** [aspnet/AspNetCore#16653]
Hi everyone,

I have a **question** regarding dynamic swtiching of child content in a blazor page.

I already asked my question and my observations over at StackOverflow 
[StackOverflow Question](https://stackoverflow.com/questions/58198638/how-to-dynamically-switch-child-content-in-blazor-pages)
but I had no luck getting an answer.

I also tried to ask @danroth27 directly via E-Mail but he's probably busy with all his work and therefore I open this discussion here.

Just to be clear this is not a blocking problem for me right now, I can work around it...
I just want to know what the "correct" way would be to tackle this issue or if I'm just doing it completly wrong :D

---

**Below you can read the details that I copied over from the StackOverflow issue**

---

I have built a Master / Detail page and that page uses a master component (the list of employees) and 2 different detail component (employee readonly detail view and employee edit view).

The master detail page uses the following routes:

- `https://localhost:44344/masterdetail`
- `https://localhost:44344/masterdetail/{id:int}`
- `https://localhost:44344/masterdetail/{id:int}/edit`

I tried to accomplish these goals:

1. When a user clicks a list entry from the master component, this should be shown in the URL like `https://localhost:44344/masterdetail/2` and than load the employee readonly detail view into the detail area

2. When a user clicks the edit button located on the employee readonly detail view, the master detail page should switch to the employee edit view inside the detail area and show this in the URL like `https://localhost:44344/masterdetail/2/edit`

3. When a user clicks the save button located on the employee edit view, the master detail page should switch to the employee readonly detail view inside the detail area and show this in the URL like `https://localhost:44344/masterdetail/2`

The problems that I have faced:
When the user is in the readonly view and than clicks the edit button, my code is calling `NavigationManager.NavigateTo($"/masterdetail/{Id}/edit");` which switches the URL in the address bar of the browser but does not invoke the `OnParametersSet()` lifecycle method of the master detail page.
**Blazor seems to reuse the instance if the [Parameter] Id has not changed it's value.**

The same happens when the user is on /masterdetail/{Id}/edit route (entered via browser address bar) and than clicks the save button.

What I learned while researching the problem:

 - I know that I could use the forceLoad parameter of the
   `NavigationManager.NavigateTo($"/masterdetail/{Id}/edit", true);`
   call like this, **but this would lead to a complete page refresh**
   and I'm not sure if this is necessary.
 - I know that I could use `EventCallback<T>` in my child components and
   react on these events in the parent master detail page but this seems
   like a workaround.
 - I looked for a way to "**route inside a blazor page**" and stumbled
   across topics like "**Areas**" and "**Partial Views**" but it looks
   like these are MVC concepts.
 - I also found something called the "**RouteView**"
   (https://github.com/aspnet/AspNetCore/blob/2e4274cb67c049055e321c18cc9e64562da52dcf/src/Components/Components/src/RouteView.cs)
   which is a Blazor component but I had no luck using it for my
   purposes.

Here is a simplified sample that shows the problem:

1. Create a new "Blazor App" project in Visual Studio
2. Choose "Blazor Server App"
3. Add a new .razor file and paste the code snippet in
4. Have a look at the comments and the code
5. Navigate to `https://localhost:44344/masterdetail/` and try it yourself

 
```
@*Default route for this page when no entry is selected in the master list*@
@page "/masterdetail"
@*Route for this page when an entry is selected in the master list. The detail area should show a readonly view / component*@
@page "/masterdetail/{id:int}"
@*Route for this page when an entry is selected in the master list and the user clicked the edit button in the readonly view / component. The detail area should show a edit view / component*@
@page "/masterdetail/{id:int}/edit"
@using Microsoft.AspNetCore.Components

@inject NavigationManager NavigationManager

<h1>MyMasterDetailPage</h1>

<br />
<br />
<br />

<div>
    <h1>Master Area</h1>

    <ul class="nav flex-column">
        <li class="nav-item px-3">
            <button @onclick=@(mouseEventArgs => ShowListItemDetails(1))>Item 1</button>
        </li>
        <li class="nav-item px-3">
            <button @onclick=@(mouseEventArgs => ShowListItemDetails(2))>Item 2</button>
        </li>
        <li class="nav-item px-3">
            <button @onclick=@(mouseEventArgs => ShowListItemDetails(3))>Item 3</button>
        </li>
    </ul>
</div>

<br />
<br />
<br />

<div>
    <h1>Detail Area</h1>
    @{
        if (_isInEditMode)
        {
            // In the real project a <EmployeeEditComponent></EmployeeEditComponent> is being used here instead of the h2
            <h2>Edit view for item no. @Id</h2>
            <h3>Imagine lots of editable fields here e.g. TextBoxes, DatePickers and so on...</h3>
            <button @onclick=@SaveChanges> save...</button>
        }
        else
        {
            // In the real project a <EmployeeDetailComponent></EmployeeDetailComponent> is being used here instead of the h2
            <h2>ReadOnly view for item no. @Id</h2>
            <h3>Imagine lots of NON editable fields here. Probably only labels...</h3>
            <button @onclick=@SwitchToEditMode> edit...</button>
        }
    }
</div>

@code {
    private bool _isInEditMode;

    [Parameter]
    public int Id { get; set; }

    protected override void OnParametersSet()
    {
        // This lifecycle method is not called if the [Parameter] has already been set as Blazor seems to reuse the instance if the [Parameter] Id has not changed it's value.
        // For example this method is not being called when navigating from /masterdetail/1 to /masterdetail/1/edit

        Console.WriteLine($"Navigation parameters have been set for URI: {NavigationManager.Uri}");
        _isInEditMode = NavigationManager.Uri.EndsWith("edit");
        base.OnParametersSet();
    }

    private void ShowListItemDetails(int id)
    {
        Console.WriteLine($"Showing readonly details of item no. {id}");
        NavigationManager.NavigateTo($"/masterdetail/{id}");
    }

    private void SwitchToEditMode()
    {
        Console.WriteLine("Switching to edit mode...");
        NavigationManager.NavigateTo($"/masterdetail/{Id}/edit");

        // Setting _isInEditMode = true here would work and update the UI correctly.
        // In the real project this method is part of the <EmployeeEditComponent></EmployeeEditComponent> and therefore has no access to _isInEditMode as it belongs to the <MyMasterDetailPage> component.
        // I know that I could create a public EventCallback<MouseEventArgs> OnClick { get; set; } in the <EmployeeEditComponent> and react to that event here in the <MyMasterDetailPage> component but is that really the right way to do this?

        //_isInEditMode = true;
    }

    private void SaveChanges()
    {
        Console.WriteLine("Saving changes made in edit mode and switching back to readonly mode...");
        NavigationManager.NavigateTo($"/masterdetail/{Id}");

        // Setting _isInEditMode = false here would work and update the UI correctly.
        // In the real project this method is part of the <EmployeeDetailComponent></EmployeeDetailComponent> and therefore has no access to _isInEditMode as it belongs to the <MyMasterDetailPage> component
        // I know that I could create a public EventCallback<MouseEventArgs> OnClick { get; set; } in the <EmployeeDetailComponent> and react to that event here in the <MyMasterDetailPage> component but is that really the right way to do this?

        //_isInEditMode = false;
    }
}
```

My setup:

- Visual Studio 2019 16.3.1
- .NET Core 3.0 SDK - Windows x64 Installer (v3.0.100)

**What is the best practice / recommendation on how to switch child content inside a blazor page?**

**Comment by mrpmorris** [comment]
Make the "edit" part of your URL a string parameter named "displayMode" and display your content according to the value of that

**Comment by SariDev** [comment]
Hi @mrpmorris,

thank you for your response.

Your suggestion is indeed a solution 😊 
Doing it like this didn't even came into my mind 😞 

As you said, I changed the following lines

| Before  |After   |  
|---|---|
|@page "/masterdetail/{id:int}/edit"   |@page "/masterdetail/{id:int}/{displayMode}"   |
| -  |  [Parameter]<br> public string DisplayMode { get; set; }  | 
| _isInEditMode = NavigationManager.Uri.EndsWith("edit");  | _isInEditMode = string.Equals(DisplayMode, "edit", StringComparison.InvariantCultureIgnoreCase); |

and the website behaves as intended and that solves my problem :thumbsup:

---

Just some open questions from my point of view:

Swtiching the static "edit" part of the URL to a Parameter avoids that blazor reuses the instance.

1) Is this behavior how it's supposed to be? 😕 
@page "/masterdetail/{id:int}/edit" BAD  
@page "/masterdetail/{id:int}/{displayMode}" GOOD

2) Is it documented somewhere that Blazor behaves like this and why it does this?

3) Is switching child content in a blazor page like this the best practice / recommendation on how to do it?

**Comment by mrpmorris** [comment]
You should really be checking the parameter, not the URL
`private bool _isInEditMode = string.Compare("Edit", DisplayMode, true) == 0;`

I think the same component instance is supposed to be reused when switching to a different URL that results in the same component type being required, and the parameters are changed. Isn't that what you are seeing?

**Comment by javiercn** [comment]
@SariDev Not sure what your question is without running the code, but @mrpmorris is right in this case, that is how it should be.

**Comment by javiercn** [comment]
@mrpmorris proposed solution is also acceptable.

**Comment by javiercn** [comment]
I'm closing the issue as the question has been answered.
