### ISSUE TITLE
Counter in default Blazor Server template doesn't increment when using Edge on macOS Mojave

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/AspNetCore#16651]
### Steps to repro

 1. On a mac create a new blazor server project with `dotnet new blazorserver`
 1. `dotnet run`
 1. Open browser to url (https://localhost:5001) in Microsoft Edge
 1. Navigate to the Counter page (`/counter`)
 1. Try the `Click Me` button to increment counter

Expected: Counter is incremented on each click of `Click Me`
Actual: You have to do a SHIFT + Refresh on the page to get the `Click Me` button to work

Note: it's working fine in Chrome & Safari on Mac

**dotnet info**
```
> dotnet --version
3.0.100

> dotnet --list-sdks
2.1.802 [/usr/local/share/dotnet/sdk]
2.2.402 [/usr/local/share/dotnet/sdk]
3.0.100 [/usr/local/share/dotnet/sdk]

> dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

```

**Edge Info:**

![image](https://user-images.githubusercontent.com/1283154/67815501-760e1080-fa7d-11e9-985c-cc81278b7737.png)

**OS Info:**

![image](https://user-images.githubusercontent.com/1283154/67815477-68588b00-fa7d-11e9-8516-2934a3eb4dcc.png)

cc @danroth27

**Comment by danroth27** [comment]
@sayedihashimi Could you please share the full output from the browser console, as well as the ASP.NET Core logs for the app?

**Comment by sayedihashimi** [comment]
@danroth27 sure, where can I find ASP.NET Core logs?

**Comment by javiercn** [comment]
Replace `    <script src="_framework/blazor.server.js"></script>` with
```html
    <script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        (function start() {
            Blazor.start({
                logLevel: 1, // LogLevel.Debug
                configureSignalR: builder => builder.configureLogging("debug") // LogLevel.Debug
            });
        })()
    </script>
```
Browser logs are on F12

Set this in appSettings.json
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "Debug"
    }
  }
```
Server logs are on the console output

**Comment by javiercn** [comment]
For the record, I don't repro this on Catalina. I don't have a Mojave machine available.

**Comment by mkArtakMSFT** [comment]
Let's park this on the backlog and if there is more user feedback similar to this we will investigate this then.

**Comment by sayedihashimi** [comment]
Closing after discussing more with Dan Roth.
