### ISSUE TITLE
Unable to make XFBML work in a blazor app

### ISSUE THREAD

**Issue by softlion** [aspnet/AspNetCore#16657]
### Describe the bug
XFBML parsing using the facebook SDK does not work with a Blazor app. It never detects the tags.

![image](https://user-images.githubusercontent.com/190756/67855151-2f1e2a80-fb12-11e9-9ae6-29499f6de55a.png)

![image](https://user-images.githubusercontent.com/190756/67855245-5d9c0580-fb12-11e9-8145-2e5177b5bc7b.png)

I specifically tried the same facebook custom chat code on both a .NetCore 2.2 app and a .NetCore 3 Blazor App

### To Reproduce
1. Create a default Blazor app using the template
2. Follow the instructions there to add the FB SDK https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk#install
3. Use the ngrok tool to create a public url for this localhost website, and add the domain to the whitelist of the facebook page (in advanced messenger / whitelisted domains)
4. Browse the page

The plugin never appears, because the XFBML parser never finds the tag with fb-customerchat class. See javascript log above.
I tried to call the parser in the browser console (F12), and also get the dom element. It is found.

I tried the same facebook javascript code in a normal mvc app, and it works fine!

### Expected behavior
The XFBML parser should work with blazor apps.

**Comment by javiercn** [comment]
Thanks for contacting us @softlion.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

It is likely that you need to perform the initialization after the component has rendered on the page. See for details https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0

**Comment by softlion** [comment]
I found the issue. Its not related to Blazor.

**Comment by softlion** [comment]
The FB SDK must NOT be included on the page with a code like this:

```
<environment include="Development">
    <script async defer src="https://connect.facebook.net/en_US/sdk/debug.js"></script>
</environment>
<environment exclude="Development">
    <script async defer src="https://connect.facebook.net/en_US/sdk.js"></script>
</environment>
```

It must NOT be included at all.
