### ISSUE TITLE
Host grpc service in asp.net core 3?

### ISSUE THREAD

**Issue by IbrahimMaaty** [aspnet/AspNetCore#16661]
When Microsoft will be able to host Grpc service in asp.net core 3?

**Comment by JamesNK** [comment]
You can do that today. There is a gRPC service template in .NET Core 3.0.

Getting started tutorial: https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio

**Comment by IbrahimMaaty** [comment]
Dear James,
I already deploy grpc service on visual studio 2019, but I can't publish it
in iis or azure, and I quote
"
gRPC not supported on Azure App Service
<https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio#grpc-not-supported-on-azure-app-service>

 Warning

ASP.NET Core gRPC
<https://docs.microsoft.com/en-us/aspnet/core/grpc/index?view=aspnetcore-3.0>
is
not currently supported on Azure App Service or IIS. The HTTP/2
implementation of Http.Sys does not support HTTP response trailing headers
which gRPC relies on. For more information, see this GitHub issue
<https://github.com/aspnet/AspNetCore/issues/9020>.

This is Microsoft warning.
Ibrahim

**Comment by JamesNK** [comment]
There is an issue about that here - https://github.com/aspnet/AspNetCore/issues/9020

Date is unknown.
