### ISSUE TITLE
How to request custom resource which protected by identity server in angular identity template 

### ISSUE THREAD

**Issue by collina2019** [aspnet/AspNetCore#16660]
In asp.net core 3.0 angular , i can register a new resource like :
`"Resources": {
      "MyExternalApi": {
        "Profile": "IdentityServerJwt",
        "Scopes": "user.read"
      }
    }`

1.  how to make the angular application to require authorize the new resource (MyExternalApi).

2.  The default scope will add `xxxxAPI` , but why i haven't find the consent page ? Can i manally consent the api permission ?

3. when i config the client , only few options enabled like `WithRedirectUri` , how i can config others like `AllowedScopes `,`RequireConsent` ?

Thanks .

**Comment by javiercn** [comment]
@collina2019 thanks for contacting us.

Consent is not a feature we include in our integration, as its geared for "first party" scenarios where you trust all the clients to access all the resources.

If you want to have consent, then you need to configure identity server manually.
