### ISSUE TITLE
Crankier error : A compatible installed .NET Core SDK for global.json version [5.0.100-alpha1-014696] from [global.json] was not found

### ISSUE THREAD

**Issue by Pibe93** [aspnet/AspNetCore#16664]
Good evening, I'm trying to run a stress test here in local development (dotnet run -- local --target-url https://localhost:44368/echo --workers 10)  to see how it works because then I'll have to run a stress test on the server on which to install my server project with Asp.net core 3 with Signalr to see how many connections I can keep connected but I get this error: 
A compatible installed .NET Core SDK for global.json version [5.0.100-alpha1-014696] from [C:\Users\MarcoG\Downloads\AspNetCore-master\global.json] was not found
Install the [5.0.100-alpha1-014696] .NET Core SDK or update [C:\Users\MarcoG\Downloads\AspNetCore-master\global.json] with an installed .NET Core SDK:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk].

Thanks for support.

**Comment by BrennanConroy** [comment]
1. You first need to get the SDK for the repo, run "restore.cmd" in the root of the repository
1. Follow the instructions for using dotnet from the command line in the repo https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#using-dotnet-on-command-line-in-this-repo

**Comment by Pibe93** [comment]
Buoansera,
after cloning the project and executing the ./restore.cmd command I have the following error:

C:\Users\MarcoG\source\repos\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj :  error: Version 5.0.100-alpha1-015536 of the .NET Core SDK requires at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831. Change the version of the .NET Core SDK specified in global.json to an older one that requires the currently available MSBuild version.
C: Username Marco G o rep netNetCore en tools RepoTasks RepoTasks.csproj: error MSB4236: the SDK 'Microsoft.NET.Sdk' specified was not found.

**Comment by BrennanConroy** [comment]
You probably need to update Visual Studio to version 16.3.

**Comment by Pibe93** [comment]
The version I'm using is as follows:
Visual Studio Community 2019 Preview
16.3.0 Preview 3.0

**Comment by Pibe93** [comment]
I need to use the Visual Studio Community version 16.3.8?

**Comment by BrennanConroy** [comment]
I'm not sure, it probably doesn't hurt to update.

**Comment by Pibe93** [comment]
I used visual studio enterprise latest version, the restore was successful but when I go to the Crankier folder and execute the command I always get an error on the SDK version:
**A compatible installed .NET Core SDK for global.json version [5.0.100-alpha1-015536] from [C:\Users\MarcoG\source\repos\AspNetCore\global.json] was not found
Install the [5.0.100-alpha1-015536] .NET Core SDK or update [C:\Users\MarcoG\source\repos\AspNetCore\global.json] with an installed .NET Core SDK:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]**

**Comment by BrennanConroy** [comment]
restore.cmd will install the appropriate SDK for the repo in a local folder. In order to then use it on the command line as if it was installed globally you need to follow the instructions on [using dotnet on the command line](https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#using-dotnet-on-command-line-in-this-repo)

**Comment by pakrym** [comment]
I can't build the repo using buid.ps1 either.

```
(AspNetCore) D:\github\aspnet\AspNetCore [master ≡]> .\build
WARNING: No default group of projects was specified, so building the 'managed' and its dependent subsets of projects.   Run `build.cmd -help` for more details.
Building of NodeJS projects is disabled since node is not detected on Path and no BuildNodeJs or NoBuildNodeJs setting is set explicitly.
WARNING: Some managed projects depend on NodeJS projects. Building NodeJS is disabled so the managed projects will      fallback to using the output from previous builds. The output may not be correct or up to date.
  Restore completed in 66.18 ms for C:\Users\pakrym\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19558.11\too   ls\Tools.proj.
dotnet-install: .NET Core Runtime version 5.0.0-alpha1.19521.2 is already installed.
dotnet-install: Adding to current process PATH: "D:\github\aspnet\AspNetCore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: .NET Core Runtime version 5.0.0-alpha1.19521.2 is already installed.
dotnet-install: Adding to current process PATH: "D:\github\aspnet\AspNetCore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
D:\github\aspnet\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error : Version 5.0.100-alpha1-015536 of the .NET Co re SDK requires at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831. Change  the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.   D:\github\aspnet\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified  could not be found.
Build failed.
```

**Comment by BrennanConroy** [comment]
@aspnet/build have any ideas why this error would be see with VS 16.3 or higher installed?

`D:\github\aspnet\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error : Version 5.0.100-alpha1-015536 of the .NET Core SDK requires at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831. Change  the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.   D:\github\aspnet\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified  could not be found.`

**Comment by dougbu** [comment]
See common errors:
- https://github.com/aspnet/AspNetCore/blob/master/docs/BuildErrors.md#error-msb4236--unable-to-locate-the-net-core-sdk
- https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#common-error-unable-to-locate-the-net-core-sdk

**Comment by BrennanConroy** [comment]
@dougbu Those don't help with this issue.

And there is no "Use previews of the .NET Core SDK" in VS anymore (at least for internal previews)

**Comment by dougbu** [comment]
> Those don't help with this issue.

Note the following from the error messages above. 16.0.x is too old. @Pibe93 if you have something more recent installed too, make sure that has the MSBuild individual component installed.
> `The current available version of MSBuild is 16.0.461.62831`

> there is no "Use previews of the .NET Core SDK" in VS anymore (at least for internal previews)

That choice is available only in _non_-preview builds of VS e.g.
![image](https://user-images.githubusercontent.com/6431421/68796441-b5a13480-0607-11ea-9b36-94ffaf2bfc60.png)

**Comment by pakrym** [comment]
@dougbu please read the https://github.com/aspnet/AspNetCore/issues/16664#issuecomment-553093953 

I have the latest dogfood vs and dotnet sdk 5.0 on the path.

> That choice is available only in non-preview builds of VS e.g.

This is not helpful.

**Comment by dougbu** [comment]
> dotnet sdk 5.0

This is usually not sufficient since `global.json` requires an exact SDK as well as at least one additional runtime.
> This is not helpful.

@pakrym your error message is the same as @Pibe93's:
> `The current available version of MSBuild is 16.0.461.62831.`

I'm not sure why MSBuild is finding an earlier copy of VS. I guess it's possible `restore.cmd` didn't complete quite right or `build.cmd` and the scripts it calls aren't working as expected.

I don't usually recommend restarting from scratch but perhaps that's needed here i.e.
1. `git clean -dfx
2. `./eng/scripts/InstallJdk.ps1`
3. `./restore.cmd`
4. `./build.cmd`

**Comment by pakrym** [comment]
> This is usually not sufficient since global.json requires an exact SDK as well as at least one additional runtime.

Yes, and the comment I've posted shows that that I have exact SDK and runtime the build requires because `.\build.ps1` is the one installing them.

> I don't usually recommend restarting from scratch but perhaps that's needed here i.e.


```
(AspNetCore) D:\github\aspnet\AspNetCore [pakrym/dp-kv-keys ≡]> git clean -dfx
Removing .dotnet/
Removing .tools/
Removing artifacts/
Removing src/DataProtection/.vs/
(AspNetCore) D:\github\aspnet\AspNetCore [pakrym/dp-kv-keys ≡]> ./eng/scripts/InstallJdk.ps1
Starting download of JDK 11.0.3
Done downloading JDK 11.0.3
Expanded JDK to D:\github\aspnet\AspNetCore\obj
Installing JDK to D:\github\aspnet\AspNetCore\.tools\jdk\win-x64\
Done installing JDK to D:\github\aspnet\AspNetCore\.tools\jdk\win-x64\
(AspNetCore) D:\github\aspnet\AspNetCore [pakrym/dp-kv-keys ≡]> ./restore.cmd
Building of NodeJS projects is disabled since node is not detected on Path and no BuildNodeJs or NoBuildNodeJs setting is set explicitly.
WARNING: Some managed projects depend on NodeJS projects. Building NodeJS is disabled so the managed projects will fallback
to using the output from previous builds. The output may not be correct or up to date.
Detected JDK in D:\github\aspnet\AspNetCore\.tools\jdk\win-x64\ (via local repo convention)
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha1-015536/dotnet-sdk-5.0.100-alpha1-015536-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha1-015536/dotnet-sdk-5.0.100-alpha1-015536-win-x64.zip
dotnet-install: Adding to current process PATH: "D:\github\aspnet\AspNetCore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
Downloading vswhere
Downloading RoslynTools.MSBuild 16.0.0-alpha
  Restore completed in 357.63 ms for C:\Users\pakrym\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19558.11\tools\To
  ols.proj.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha1.19521.2/dotnet-runtime-5.0.0-alpha1.19521.2-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha1.19521.2/dotnet-runtime-5.0.0-alpha1.19521.2-win-x64.zip
dotnet-install: Installation finished
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha1.19521.2/dotnet-runtime-5.0.0-alpha1.19521.2-win-x86.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha1.19521.2/dotnet-runtime-5.0.0-alpha1.19521.2-win-x86.zip
dotnet-install: Adding to current process PATH: "D:\github\aspnet\AspNetCore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
D:\github\aspnet\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error : Version 5.0.100-alpha1-015536 of the .NET Core SDK  requires at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831. Change the .NET Cor e SDK specified in global.json to an older version that requires the MSBuild version currently available.
D:\github\aspnet\AspNetCore\eng\tools\RepoTasks\RepoTasks.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could  not be found.
Build failed.
```

**Comment by dougbu** [comment]
@pakrym new guess: Run `eng/scripts/InstallVisualStudio.ps1` with whatever parameters are needed for your latest VS installation (check `help eng/scripts/InstallVisualStudio.ps1 -full`).

**Comment by pakrym** [comment]
Sorry but I don't need a new 16.3.9 installation.

**Comment by dougbu** [comment]
My point wasn't to install a new version of VS. Instead, I was suggesting some mandatory option might be missing.

**Comment by pakrym** [comment]
Installing additional options didn't help.

**Comment by pranavkm** [comment]
The second error is a dup of https://github.com/aspnet/AspNetCore/issues/17083. Closing since we have a resolution for 5.0. For older branches, https://github.com/aspnet/AspNetCore/issues/17083#issuecomment-562348724 has a workaround.
