### ISSUE TITLE
Blazor EditForm element behavior

### ISSUE THREAD

**Issue by bootcom-uk** [aspnet/AspNetCore#16666]
### Describe the bug
Behavior of an html input inside a Blazor EditForm behaves differently to that in a normal html form.

### To Reproduce
Create an EditForm with 1 text box and 1 submit button. 
Create an html form with 1 text box and 1 submit button.  

### Expected behavior
I would expect pressing enter on both text inputs to elicit the same response

### Actual behavior
The HTML form when pressing the enter key on the textbox submits the form.
The EditForm when pressing the enter key on the textbox does nothing.

**Comment by javiercn** [comment]
@bootcom-uk thanks for contacting us.

@SteveSandersonMS thoughts?

**Comment by SteveSandersonMS** [comment]
@bootcom-uk What do you mean by "submits the form"? Do you mean "issues an HTTP GET/POST request and loads the response as a new page"?

If so, that's not what `<EditForm>` is for. `<EditForm>`, when submitted, triggers .NET event handlers, i.e., whatever you've configured as the `OnSubmit`/`OnValidSubmit`/`OnInvalidSubmit` callback parameters for the `<EditForm>`.

It *does* trigger those callbacks when you press enter inside one of its inputs.

**Comment by bootcom-uk** [comment]
Thank you for your response @SteveSandersonMS
