### ISSUE TITLE
Template razorclasslib is no longer named correctly in the .Net Core 3 SDK.

### ISSUE THREAD

**Issue by anewton** [aspnet/AspNetCore#16675]
### Bug/Issue
The default template for **razorclasslib** when using .Net Core 3 only, and when attempting to add Asp .Net Core Razor pages (.cshtml not .razor) to a Pages folder in the generated project, will not build because a reference to Microsoft.AspNetCore.Mvc v2.2.0 is not included.  The template is incorrectly named **razorclasslib**.  The **razorclasslib** template only supports Blazor pages by default. It should be renamed to **blazorclasslib**. A new template for generating Razor class library projects should be added and called **razorclasslib**. This **razorclasslib** template should allow using cshtml pages (ASP .NET Core Razor Pages) in a "Pages" folder.

### To Reproduce
Please refer to a repository I created for specific repro steps: https://github.com/anewton/razorBuildIssue

### Expected behavior
When using the CLI command, "dotnet new razorclasslib", and when targeting .Net Core 3, the generated template code should compile with Asp.Net Core Razor pages included.  The generated project should not be a Blazor project template.  A separate **blazorclasslib** template should be created for Blazor projects.

### Additional context
This issue presented itself when upgrading from .Net Core 2.2 to .Net Core 3.0 and caused a CI build using Azure Dev Ops to fail unexpectedly.  The build pipeline yml correctly included .Net Core 3, but the Razor page class library project, the csproj file, needed significant alteration to compile correctly.

**Comment by pranavkm** [comment]
@anewton you can pass in the `-s|--support-pages-and-views` switch to `dotnet new` to produce a class library that's equivalent to the RCL produced from 2.2. From the help for the `dotnet new razorclasslib`

```
  -s|--support-pages-and-views  Whether to support adding traditional Razor pages and Views in addition to components to this library.
                                bool - Optional
                                Default: false / (*) true
```

Out of curiosity, why is your CI automating creating new project files?

**Comment by anewton** [comment]
@pranavkm  Thanks, I'm just seeing that now.  I missed that now in .Net Core 3, the flag is needed when using razorclasslib to get the RCL produced from 2.2.

My CI is not creating new project files.  The upgrade from .Net Core SDK 2.2 to 3.0 broke my build when I changed the version of the .Net Core SDK used in the yml file.  It was unclear what needed to change in the csproj for the RCL based on the error messaging I was seeing from the build output.

So now I understand that by default, the project generated with `dotnet new razorclasslib` is a Razor Components library.  And it generates .razor files.  But that project does not support cshtml files.  As posted on Scott Hanselman's blog: "Blazor is the client-side hosting model for Razor Components" [here](https://www.hanselman.com/blog/WhatIsBlazorAndWhatIsRazorComponents.aspx).  And so I associate .razor files with Blazor.  Perhaps incorrectly.

Using `dotnet new razorclasslib -s` gives you a project set up with Asp .Net Core Razor pages.  I did confirm that was posted in a blog [here](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/).  And in the docs here: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=netcore-cli#rcl-pages-layout.

I still believe this razorclasslib template should be split into two different ones instead of using this flag approach.  I would settle for a template named **razorcomponentslib** and **razorclasslib**.  Where **razorclasslib** is the same as if the -s flag were used, and **razorcomponentslib** did not use the flag.  There are significant differences between the projects generated with and without the flag.

I'm interested in the likelihood of this template change happening along with any reasoning behind why a flag was deemed sufficient.  So I'll leave this open for additional comments.

**Comment by anewton** [comment]
Related issue:  [Rename Razor Components back to server-side Blazor](https://github.com/aspnet/AspNetCore/issues/8931?WT.mc_id=-blog-scottha)

**Comment by anewton** [comment]
Specific commit that implemented razorclasslib -s flag: [[Templating] Razor class library for components](https://github.com/aspnet/AspNetCore/commit/6827bb74436760aa3bb20934a1a1da4933062acb)

**Comment by danroth27** [comment]
Hi @anewton. 

We added a flag instead of a new template for Razor component libraries because both scenarios involve setting up a class library to compile Razor files, and we didn't want to create confusion about which template you should use when working with Razor. If you're looking to build some Razor components and you see a Razor Class Library template should you use it or not? Keeping one template avoids that ambiguity.

We also switched the Razor Class Library template to be setup for Blazor component library development by default because we expected that this would be a more common scenario than creating Razor Class Libraries for pages and views. We knew this was potentially a breaking change, but the prior usage of the template for pages and views was light enough that it seemed the impact would be small. 

Regardless of the reasoning, we understand it's still painful when you get impacted by a breaking change. We do our best to avoid making breaking changes, except in the cases where we think the benefit out weights the cost for our customers.

**Comment by anewton** [comment]
Thanks @danroth27 for the response.  I went the long way around to figure out what my build issue was during upgrading.  But it did come back to this area of change.  

I really disagree with the push to Blazor as a replacement for Razor Pages.  That is what it seems like from your comment that, "we expected that this would be a more common scenario".  It seems to me that a Razor Class Library project template is going to be useful for a while longer.  Until Blazor is fully supported on the client and server at least.  Migrating .Net Framework MVC web applications to .Net Core Razor Pages is a task that I think will be easier for many projects than rewriting to Blazor when .Net Core 5 is released.  Also, the scaffolding for Microsoft Identity currently generates Razor Pages and not Razor Components at all.  That will have to change as well.

Thanks again for reviewing this question.

**Comment by danroth27** [comment]
> I really disagree with the push to Blazor as a replacement for Razor Pages

I agree! Blazor is not a replacement for MVC or Razor Pages. Blazor is specifically for client web UI development, the kind of stuff that you used to have to use JavaScript for. Blazor works together with MVC and Razor Pages. You can add Blazor components to your existing pages and views. You use MVC and Razor Pages to handle prerendering in Blazor apps. They're built to be used together.  While  we changed the Razor Class Library template to support Razor components by default, the option to build libraries for pages and views is still fully supported, and there are no plans to remove that.

**Comment by anewton** [comment]
I guess if the direction we are headed in is to combine Razor Components, Razor Pages, and View Components in a Blazor app, then it feels like it should be a separate template and razorclasslib should have been left alone.  But then again, I can probably build my own template if I really want to.  Anyway, good to know Blazor is not a replacement for MVC or Razor Pages.  Btw, I updated the repro steps above so I don't have to keep my repository link on this thread.
