### ISSUE TITLE
Why are ASP.net Core auth cookies bigger than MVC5 cookies?

### ISSUE THREAD

**Issue by PaulParker** [aspnet/AspNetCore#16699]
Adding a certain json user data claim and calling `HttpContext.SignInAsync()` on ASP.net Core V3 leads to multiple chunked cookies of size 4k each.

However, adding the same json string and calling `IOwinContext.Authentication.SignIn()` on MVC5 / Microsoft.Owin V3.0.1 generates only one cookie that's much smaller than the 4k limit.

Is this the expected behavior? If so, why is the new cookie so much larger?

**Comment by blowdart** [comment]
We encrypt then sign using a different method now.

**Comment by GrabYourPitchforks** [comment]
The ASP.NET Core DataProtection stack shouldn't add _that_ much overhead per signature. The payload format is documented at https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/authenticated-encryption-details. It's only a few dozen bytes per invocation.

Did the contents of the auth cookie also change between MVC 5 and ASP.NET Core v3?

**Comment by blowdart** [comment]
It's taking the user principal, but we now save more properties than we used to, issuer of claims and other stuff to make it hydrate better

**Comment by GrabYourPitchforks** [comment]
Ah, that'd explain it. Thanks for the info. :)

**Comment by anurse** [comment]
Closing as the question has been answered.
