### ISSUE TITLE
GC is too Aggressive in Blazor WASM, Degrading Performance

### ISSUE THREAD

**Issue by legistek** [aspnet/AspNetCore#16692]
I'm not sure if this is a Mono issue, a Blazor issue, or both, but I suspect a lot of the performance problems I've been having with interpreted WASM are the result of the GC being too aggressive. My test application experiences long (maybe 0.5-1s) pauses periodically during significant DOM updates and the browser console reveals that these always correspond to GC events:

![image](https://user-images.githubusercontent.com/13384523/67947018-a4403d00-fbb0-11e9-92ba-c1c35820a7f3.png)

According to the log my memory usage is well under 100MB which doesn't seem like it would justify so many forced GCs. In fact you can see just during the initial DOM build there was a Large Object Space (LOS) overflow suggesting I was basically out of memory. 

(Incidentally, almost all memory usage is `RenderTreeFrame`s, according to the profiler when run on the same app using server-side Blazor, and my DOM is not any more complex than a typical Angular app).

My understanding was that WASM could use GBs of memory so I don't quite understand why the limits are so low. Is it possible to make these parameters tweakable at design or runtime or is this burned into mono.wasm?

**Comment by legistek** [comment]
Maybe related to https://github.com/aspnet/AspNetCore/issues/5617?

**Comment by javiercn** [comment]
@legistek thanks for contacting us.

We will be focusing on blazor wasm in the coming weeks/months and will take a look at this.

**Comment by javiercn** [comment]
I'm closing this issue in favor of https://github.com/aspnet/AspNetCore/issues/16692
