### ISSUE TITLE
CORS not working properly after 2.2 -> 3.0 migration

### ISSUE THREAD

**Issue by phsamudev** [aspnet/AspNetCore#16701]
My team has an .NET Core API solution that communicates with an Angular project.

We migrated our .NET Core solution from 2.2 to 3.0 recently. Everything is working as it should in our local environment (localhost ports), we had a few minor issues that were easily solved.

However when pushed our code to a remote server we started getting the following CORS error:

**Access to XMLHttpRequest at 'http://foo.com:5000/api/User/GetUser' from origin 'http://foo.com:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

Our Startup.cs is configured like that (ConfigureServices method):

```
services.AddCors(c =>
  {
   c.AddPolicy("AllowOrigin", options =>
   {
     options.AllowAnyOrigin();
     options.AllowAnyHeader();
   });
 });
```

And (Configure method):

```
app.UseCors(options =>
     {
         options.AllowAnyOrigin();
         options.AllowAnyHeader();
         options.AllowAnyMethod();
     });
```

**This only happens on routes that are protected by Bearer Authorization.** All other routes are working perfectly fine (GET, POST, any method).

I can't seem to find the root of the error, I've already tried following Microsoft docs https://docs.microsoft.com/pt-br/aspnet/core/security/cors?view=aspnetcore-3.0 and https://docs.microsoft.com/pt-br/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio but none of them could solve the problem.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by phsamudev** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

We've found what was causing the error, it seems that Azure CI was building the solution using .NET Core 2.2. The CORS error message was masking the real error.

Thanks for the reply.
