### ISSUE TITLE
Blazor Razor issue

### ISSUE THREAD

**Issue by tim241** [aspnet/AspNetCore#16705]
### Describe the bug
It seems like hooking up a C# function with html inside it to a button `OnClick` event breaks

it displays this when clicking the button:
```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: TypeError: i is undefined
System.InvalidOperationException: TypeError: i is undefined
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'hB3P9v7NnJnaLuydVoQycIVyJXMkZ0d4GXHPLLC5TZI'.
System.AggregateException: One or more errors occurred. (TypeError: i is undefined)
 ---> System.InvalidOperationException: TypeError: i is undefined
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
```
### To Reproduce
* install `Microsoft.AspNetCore.App 3.0.0`
* create a `blazorserver` project
* try this code:
```csharp
@{
    void OnClick()
    {
        <p>The Button Was Clicked!</p>
    }
}
<button class="btn btn-primary" @onclick="OnClick">Click me!</button>
```
* run the `blazorserver`
* click the `Click me!` button

### Expected behavior
I wasn't sure what to expect, if this is legal usage of razor I'd expect it to work but if this is illegal usage of razor I'd expect the compiler to throw either a warning or an error regarding this.

### Additional context
```
tim@laptop:~/blazor_test$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mrpmorris** [comment]
Does it work if you change `@{` to `@code {`

**Comment by tim241** [comment]
@mrpmorris if I replace `@{` with `@code {` I get
```
tim@laptop:~/dev/blazor_test$ dotnet run
obj/Debug/netcoreapp3.0/RazorDeclaration/Pages/Index.razor.g.cs(96,9): error CS0103: The name '__builder' does not exist in the current context [/home/tim/dev/blazor_test/blazor_test.csproj]
obj/Debug/netcoreapp3.0/RazorDeclaration/Pages/Index.razor.g.cs(97,9): error CS0103: The name '__builder' does not exist in the current context [/home/tim/dev/blazor_test/blazor_test.csproj]

The build failed. Fix the build errors and run again.
tim@laptop:~/dev/blazor_test$ 
```

**Comment by mrpmorris** [comment]
Sorry, I've only just realised what you are doing.

A method cannot execute html, so you should not put html in there. 

Instead do something like this

```
@if (ShouldShow)
{
  <p>Button was clicked</p>
} 
<button @onclick=ButtonClicked>Click me</button>

@code 
{
  void ButtonClicked() 
  {
    ShouldShow = treue;
  } 
} 
```

**Comment by tim241** [comment]
[the docs state otherwise?](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0#razor-code-blocks) (scroll down until the example with `RenderName`)

i.e this works fine, it only breaks when hooking it up to a button's `OnClick` event
```csharp
@{
    void OnClick()
    {
        <p>The Button Was Clicked!</p>
    }

    OnClick();
}
```

**Comment by mrpmorris** [comment]
That's because the button click is actually executed in response to an event, the code you have above is run as part of the rendering process. You cannot "execute" HTML (which is what an event does).

**Comment by tim241** [comment]
that makes sense, however I think the compiler should warn/error out when something like this is attempted just to make it clear it's illegal use of razor instead of crashing and showing a vague `TypeError: i is undefined` error.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tim241.
Markup in functions is not supported in .razor files at the moment. We will look into improving this experience in the future given more user feedback in this area.
