### ISSUE TITLE
Why is DynamicViewData internal?

### ISSUE THREAD

**Issue by oferns** [aspnet/AspNetCore#16709]
is there any reason this class is internal? I want to write a custom base class to replace the abstract ViewComponent class. I want to return a different ViewViewComponent result, one that is localized and opinionated about the view location in a different way to the embedded convention, so the code is a copy/paste job, but this class is internal and I cant understand why. 

https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.ViewFeatures/src/DynamicViewData.cs

**Comment by javiercn** [comment]
@oferns thanks for contacting us.

We normally don't make any type public if we can avoid it unless we determine there is useful in some common scenario, as it increases our maintenance cost and prevents us from making changes in the future.
