### ISSUE TITLE
Attribute value missing warning in Blazor Server template

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#16723]
In *_Host.cshtml*:

```html
<a href class="reload">Reload</a>
```

Which results in an "Attribute value missing" warning for new Blazor Server projects.

![image](https://user-images.githubusercontent.com/1874516/67993695-3e2ed680-fbff-11e9-8298-b62ca3e9fe3a.png)

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore-ManualTests/issues/39. This is being fixed by https://github.com/aspnet/AspNetCore/pull/16719
