### ISSUE TITLE
Build Core Angular Application Failed

### ISSUE THREAD

**Issue by Pilchie** [aspnet/AspNetCore#16722]
_From @adarsuma on Thursday, October 31, 2019 2:42:34 PM_

I am creating  new .NETCORE 3 ASP.NET Web application with Angular template. No code changes yet, and tried to build the solution.

Error that comes up:
network request to https://registry.npmjs.org/core-js/-/core-js-3.0.1.tgz failed

Tried to run the solution for the second time and it was unable to load the page with the following message:

An unhandled exception occurred while processing the request.
TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.

Here is the Output Log.
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 GET https://localhost:44386/  
Microsoft.AspNetCore.SpaServices: Error: 'ng' is not recognized as an internal or external command,
Microsoft.AspNetCore.SpaServices: Error: operable program or batch file.
npm ERR! code ELIFECYCLE
Microsoft.AspNetCore.SpaServices: Error: npm ERR! errno 1
npm ERR! vtcui@0.0.0 start: `ng serve "--port" "32385"`
Microsoft.AspNetCore.SpaServices: Error: npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vtcui@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Microsoft.AspNetCore.SpaServices: Error: npm ERR! A complete log of this run can be found in:
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.
System.TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 120309.3183ms 500 text/html; charset=utf-8
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Security.Principal.Windows.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 GET https://localhost:44386/favicon.ico  
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Information: Sending file. Request path: '/favicon.ico'. Physical path: 'C:\Users\adarsum\TFS\IT_Business\VTC\VtcUI\VtcUI\wwwroot\favicon.ico'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 64.7217ms 200 image/x-icon

_Copied from original issue: dotnet/core#3724_

**Comment by Pilchie** [comment]
_From @scalablecory on Thursday, October 31, 2019 11:06:01 PM_

@Pilchie is this one of yours?

**Comment by javiercn** [comment]
@adarsuma thanks for contacting us.

What you see looks a lot like a (potentially transient) network error while restoring the packages for the templates. I would try a few things to see if any of them improves the situation.
* Navigate to /ClientApp and run `npm install` one or more times (if it fails the first time). Once it runs fine the first time you should be good to go.
* If `npm install` fails repeatedly it is likely an issue with either your network configuration (corporate proxy or similar, potential ISP restrictions (very rare) or an unreliable connection) or an issue with your node/npm configuration.
  * I would check the node documentation to make sure your node version is up to date and that your node config doesn't have any customization that might get in the way.
 * You could also try cleaning up your package cache (this is a destructive operation that will force all the npm packages to download from the internet from scratch).

If none of those things help, I would ask in the node/npm forums about your issue as npm restore works fine for this template for all configurations we've tried.
