### ISSUE TITLE
AddJsonFormatters missing in AddMvcCore

### ISSUE THREAD

**Issue by j0nimost** [aspnet/AspNetCore#16734]
### Is your feature request related to a problem? Please describe.
I am trying to do Access `AddJsonFormatters();`  from `AddMvcCore();`but the method is missing.

### Describe the solution you'd like
In previous versions of ASP.NET prior to Asp.Net 3.0 had support to add `AddJsonFormatters();` as shown below;
```
       public void ConfigureServices(IServiceCollection services)
       {
	      // ...

	     // Add framework services.
	     services.AddMvcCore().AddJsonFormatters();
       }
```
This allowed a developer to utilize the lightweight core package(`ASP.NetCore.MvcCore`) this was highly beneficial when working with Worker Services as we needed them as light and fast as possible.
### Additional context

```
public static IMvcCoreBuilder AddMvcCore(this IServiceCollection services)
{
    if (services == null)
    {
        throw new ArgumentNullException(nameof(services));
    }

    var partManager = GetApplicationPartManager(services);
    services.TryAddSingleton(partManager);

    ConfigureDefaultFeatureProviders(partManager);
    ConfigureDefaultServices(services);
    AddMvcCoreServices(services);

    var builder = new MvcCoreBuilder(services, partManager);

    return builder;
}
```

**Comment by javiercn** [comment]
@j0nimost thanks for contacting us.

This is an announced breaking change. See the following announcement for details and instructions. https://github.com/aspnet/Announcements/issues/49

@rynowak can confirm.

I'm closing this issue as the question has been answered.

**Comment by j0nimost** [comment]
Thank you
