### ISSUE TITLE
Remove null check for logger in HttpsConnectionMiddleware

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/AspNetCore#16735]
There's a null check for `_logger` in `HttpsConnectionMiddleware` 

https://github.com/aspnet/AspNetCore/blob/0a61879cf75c4be2185587bc22ef778a2b8c9291/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L203

and since `HttpsConnectionMiddleware` is internal and nowhere in the code a null `ILoggerFactory` is passed to its constructor, the null check could be removed.

**Comment by javiercn** [comment]
@Kahbazi thanks for contacting us.

@Tratcher @halter73 Up to you.
