### ISSUE TITLE
Debugging Core 3.0 ASP.NET MVC API very slow response

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#16744]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/802114/debugging-core-30-aspnet-mvc-api-very-slow-respons.html)._

---
I just migrated one of our ASP.NET MVC Rest APIs from .NET Core 2.0 to .NET Core 3.0.  When debugging in Visual Studio 2019 and using Postman to call the end points it is taking well over 4 or 5 seconds to return a response.  When running in release mode or when deployed to IIS the service returns in less than 400ms in most cases sometimes as low as 45ms.  This only started when I upgraded the project to Core 3.0.  The Core 2.0 version still runs very fast in debug mode in VS2019. I am not sure if this is a Core 3.0 issue or a VS2019 issue but since it runs fine in release I am going to assume it is something in VS2019 when running in debug mode.  Perhaps a problem with Diagnostic Tools or such.

---
#### Visual Studio Feedback System on 11/1/2019, 02:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by javiercn** [comment]
We're closing this issue as we haven't seen community involvement and we need more information to reproduce the problem. If you have more details about the issue add a reply here with the new information and we'll re-evaluate the issue.
