### ISSUE TITLE
Add an extension method to allow WebHostBuilder to config IIS

### ISSUE THREAD

**Issue by changhuixu** [aspnet/AspNetCore#16747]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

I am trying to remove the "Server" HTTP header, but there's no intuitive way to configure it in code. Please read this StackOverflow question and answers.
https://stackoverflow.com/questions/56102228/how-to-remove-server-header-in-asp-net-core-2-2-1-web-app

Currently, there's a method to configure Kestrel. I do things like below
```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureKestrel(c => c.AddServerHeader = false)
                .UseStartup<Startup>();
```
The `ConfigureKestrel` doesn't eliminate `Server` header, at least in the default Hosting Model.

### Describe the solution you'd like

It would be better to have a similar extension method to `ConfigureKestrel`. The method name could be `ConfigureIIS` or `ConfigureIISIntegration` etc. Then in the method, we can specify configurations, such as `c.AddServerHeader = false`.

**Comment by Tratcher** [comment]
In the IIS scenario AspNetCore does not add the Server header, IIS does. It's not clear that we could remove it from within the application.

Here's how to remove it using the IIS config:
https://techcommunity.microsoft.com/t5/IIS-Support-Blog/Remove-Unwanted-HTTP-Response-Headers/ba-p/369710

Also, the value of removing the server header is dubious.

**Comment by anurse** [comment]
There *is* an options type for IIS that we could expose in a `ConfigureIIS` method, but it would only have the options on [IISServerOptions](https://github.com/aspnet/AspNetCore/blob/master/src/Servers/IIS/IIS/src/IISServerOptions.cs). We can't control IIS configuration settings like suppressing the Server header, you have to do that from the IIS configuration layers (web.config, etc.).

Closing as I don't think the options we have are valuable enough to warrant a top-level method. You can always do:

```csharp
.ConfigureServices(services => services.Configure<IISServerOptions>(options => {...}))
```
