### ISSUE TITLE
ASP.NET Core 2.2 Razor Pages: InvalidOperationException: Multiple constructors accepting all given argument types have been found in type System.Collections.Generic.List

### ISSUE THREAD

**Issue by travisrroy** [aspnet/AspNetCore#16749]
### Describe the bug
Loading a Partial View with a List using Ajax throws `Multiple constructors accepting all given argument types have been found in type System.Collections.Generic.List`

### To Reproduce
Using ASP.NET Core 2.2 Razor Pages, make an Ajax call to a Partial View with a List being displayed

### Expected behavior
The list is displayed on the main page through the Partial View

### Screenshots
**Main Page (DisplayCountries.cshtml)**
```
<h2>Simple Countries</h2>

<p><button class="btn btn-primary" id="load">Load</button></p>
<div id="grid"></div>
@section scripts{
    <script>
        document.getElementById('load').addEventListener('click', () => {
            fetch('/shared/ajaxpartial?handler=CountriesPartial')
                .then((response) => {
                    return response.text();
                })
                .then((result) => {
                    document.getElementById('grid').innerHTML = result;
                });
        });
    </script>
}
```

**Partial View (AjaxPartial.cshtml)**
```
@page
@model List<string>

@foreach (var item in Model)
{
    <h2>@item</h2>
}
```

**Code behind Partial View (AjaxPartial.cshtml.cs)**
```
   public class AjaxPartialModel : PageModel
    {
        public void OnGet()
        {
        }

        public PartialViewResult GetPartial()
        {
            List<string> countries = new List<string>();
            countries.Add("USA");
            countries.Add("UK");
            countries.Add("India");

            return Partial("_CountriesPartial", countries);
        }
    }
```

**Error page**
![image](https://user-images.githubusercontent.com/24424190/68044873-9ec91c80-fcae-11e9-91aa-34bdb4950d77.png)

**Comment by pranavkm** [comment]
@travisrroy the `model` for your `AjaxPartial.cshtml` is listed as `@model List<string>`. Did you mean for it to be `@model AjaxPartialModel` since that's where you initialize the list?

Page models in Razor Pages are type activated just as controllers are. The framework looks for a way to construct it from services in DI. It requires that types have a single constructor that can be unambiguously created from DI. `List<string>` fails this requirement which would explain the error you're seeing.

**Comment by travisrroy** [comment]
Well thanks for responding. I went back through my code, only to find out that I copied the tutorial wrong and that's why I was getting this error. I did end up figuring it out afterwards. Thanks for your help!
