### ISSUE TITLE
Scenarios are not running: DbFortunesDapper, DbFortunesEf, DbFortunesRaw, DbMultiQueryDapper, DbMultiQueryEf ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#16754]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| DbFortunesDapper | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:44:02Z |
| DbFortunesEf | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:44:56Z |
| DbFortunesRaw | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:43:16Z |
| DbMultiQueryDapper | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:33:12Z |
| DbMultiQueryEf | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:33:58Z |
| DbMultiQueryRaw | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:32:27Z |
| DbMultiUpdateDapper | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:39:26Z |
| DbMultiUpdateEf | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:40:13Z |
| DbMultiUpdateRaw | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:36:59Z |
| DbSingleQueryDapper | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:28:42Z |
| DbSingleQueryEf | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:29:27Z |
| DbSingleQueryRaw | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:27:57Z |
| EndpointPlaintext | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:08:52Z |
| HttpClient | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:48:10Z |
| HttpClientFactory | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:49:42Z |
| HttpClientParallel | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:48:52Z |
| Json | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:12:46Z |
| Json | Linux, Cloud, https, KestrelSockets | 2019-10-31 20:18:54Z |
| Json | Linux, Cloud, h2, KestrelSockets | 2019-10-31 20:21:56Z |
| Json | Linux, Cloud, h2c, KestrelSockets | 2019-10-31 20:22:40Z |
| JsonPlatform | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:11:56Z |
| MemoryCachePlaintext | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:23:24Z |
| MemoryCachePlaintextSetRemove | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:24:09Z |
| MvcDbFortunesDapper | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:46:26Z |
| MvcDbFortunesEf | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:47:11Z |
| MvcDbFortunesRaw | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:45:41Z |
| MvcDbMultiQueryDapper | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:35:28Z |
| MvcDbMultiQueryEf | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:36:13Z |
| MvcDbMultiQueryRaw | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:34:42Z |
| MvcDbMultiUpdateDapper | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:41:44Z |
| MvcDbMultiUpdateEf | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:42:31Z |
| MvcDbSingleQueryDapper | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:30:57Z |
| MvcDbSingleQueryEf | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:31:42Z |
| MvcDbSingleQueryRaw | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:30:11Z |
| MvcJson | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:13:36Z |
| MvcJson2k | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:15:04Z |
| MvcJsonInput2k | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:16:38Z |
| MvcJsonNet | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:14:20Z |
| MvcJsonNet2k | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:15:48Z |
| MvcJsonNetInput2k | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:17:24Z |
| MvcPlaintext | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:06:37Z |
| Plaintext | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:03:22Z |
| Plaintext | Linux, Cloud, https, KestrelSockets | 2019-10-31 20:18:08Z |
| PlaintextNonPipelined | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:04:07Z |
| PlaintextNonPipelined | Linux, Cloud, https, KestrelSockets | 2019-10-31 20:19:40Z |
| PlaintextNonPipelined | Linux, Cloud, h2, KestrelSockets | 2019-10-31 20:20:25Z |
| PlaintextNonPipelined | Linux, Cloud, h2c, KestrelSockets | 2019-10-31 20:21:11Z |
| PlaintextPlatform | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:00:56Z |
| ResponseCachingPlaintextCached | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:24:53Z |
| ResponseCachingPlaintextRequestNoCache | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:26:27Z |
| ResponseCachingPlaintextResponseNoCache | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:25:42Z |
| ResponseCachingPlaintextVaryByCached | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:27:11Z |
| StaticFiles | Linux, Cloud, http, KestrelSockets | 2019-10-31 20:11:06Z |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by javiercn** [comment]
@sebastienros can you take a look?
