### ISSUE TITLE
caniuse-lite outdated error in Angular template

### ISSUE THREAD

**Issue by RLashofRegas** [aspnet/AspNetCore#16767]
### Describe the bug
After creating a new project with the angular template (`dotnet new angular`) I get an error when trying to run it saying that caniuse-lite is outdated.

### To Reproduce
1. Run `dotnet new angular` to create a new project.
2. Run `dotnet run`.
3. You will see an error in the console complaining about SPAServices: "Browserslist: caniuse-lite is outdated"

### Expected behavior
No errors when creating a new project with a dotnet template.

### Additional context
I have tried all the fixes in [this issue](https://github.com/postcss/autoprefixer/issues/1184) with the autoprefixer package that depends on browserslist and caniuse-lite. `npm ls` shows that autoprefixer is the only package dependent on browserslist and caniuse-lite. `npm update` does nothing. Removing these packages from package-lock.json (they appear there by default) or removing package-lock.json from the project entirely and then running npm update also does not fix.

What does fix: 
1. Run `dotnet new angular`
2. delete the ClientApp folder
3. make a new ClientApp folder and run ng new "ClientApp"
4. run dotnet run on the project.

I am using latest dotnet core 3.0. When using the dotnet project template angular version ends up as 8.0.something. When manually deleting and regenerating the Angular project the version is 8.2.13.

**Comment by javiercn** [comment]
@RLashofRegas thanks for contacting us.

We updated the npm dependencies on the templates last week and this will be fixed in the next preview release for 3.1.
