### ISSUE TITLE
ApacheModRewrite capturing value from %{QUERY_STRING} not resulting as expected

### ISSUE THREAD

**Issue by cihanuygun** [aspnet/AspNetCore#16774]
There is an issue about the ApacheModRewrite rule parsing in .Net Core web project. The subjected ApacheModRewrite rule is something like below. The expected result of executing that rule is receiving a value from %{QUERY_STRING} but, it looks like the matched pattern results the %1 param to an empty string.

**The Rule**
RewriteCond %{REQUEST_URI} ^/old-path[/]?$ [NC]
RewriteCond %{QUERY_STRING} key=([a-z]+) [NC]
RewriteRule (.*) /new-path/%1 [R=301,NC,L,QSD]

**Result:** Requesting /old-path/?key=A redirects to /new-path
**Expected Result:** Requesting /old-path/?key=A should redirect to /new-path/A
**Project SDK:** .NET Core 2.2

**dotnet --info output:**
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

**Comment by cihanuygun** [comment]
I noticed that this issue is fixed for .NET Core 3.x SDK. Is there any way to keep 2.2 as project SDK and fix that issue?

Previous issue: #10768

**Comment by jkotalik** [comment]
I don't think we would patch this in 2.2 as 2.2 will be end of life/support in a couple of months. 

What is preventing you from upgrading your project from 2.2 to 3.0?

**Comment by cihanuygun** [comment]
Hey @jkotalik thank you for your comment. We decided to move our application from 2.2 to 3.0 as you compose your comment, and today we moved it to 3.0. There was some minor problems when we moved our project to 3.0 but all of them was solvable things and we solved now our project running on 3.0. According to this information, i am closing this issue. Thanks.
