### ISSUE TITLE
React template still use IWebHostBuilder under .netcore 3.0

### ISSUE THREAD

**Issue by heku** [aspnet/AspNetCore#16771]
Since .netcore 3.0, `HostBuilder` is a recommended way for build all kinds host, include the web host, I think all web templates should be updated as below already.

```csharp
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

But actually, I found the asp.net core react template still initializes code in old way.

```csharp
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
```

### To Reproduce
Create a asp.net core react project with `dotnet new react` or by Visual Studio 2019 16.3.7, 

### Expected behavior
In the `Program.cs` file, the host should be created use the new HostBuilder rather than WebHostBuilder.

**Comment by javiercn** [comment]
@heku thanks for contacting us.

We've fixed this and will be available in the next preview release for asp.net core 3.1.

**Comment by heku** [comment]
Good, thx.
