### ISSUE TITLE
Blazor WebAssembly Layout file import CSS files

### ISSUE THREAD

**Issue by jingzheshan** [aspnet/AspNetCore#16779]
### Is your feature request related to a problem? Please describe.
As a developer, I want to import a style file or multiple style files (css) at the Blazor WebAssembly Layout file

### Describe the solution you'd like
In a Layout.razor I can import multiple css files.
For example: 
```
@inherits LayoutComponentBase
<head>
   <link href="~/css/layout1.css" rel="stylesheet"/>
   <link href="~/css/layout2.css" rel="stylesheet"/>
</head>
```
Or other equivalent syntax.

At the moment, we can put those styles in the <style> tag or use JS interop to dynamic insert into the DOM, however either way feels not so nature. 

### Additional context
None

**Comment by javiercn** [comment]
@jingzheshan thanks for contacting us.

This is a duplicate of https://github.com/aspnet/AspNetCore/issues/10450
