### ISSUE TITLE
Is it possible to host Kestrel at 127.0.0.2:80?

### ISSUE THREAD

**Issue by WhiteKarma** [aspnet/AspNetCore#16785]
I get a sockets security exception trying, but i do not know if it is firewall related.

Thank you in advance

**Comment by davidfowl** [comment]
See 

- https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux . 

The question is about java but the same answer applies.

**Comment by Tratcher** [comment]
It's also possible something else is already using that port. netstat might help.

**Comment by anurse** [comment]
Closing as this is a configuration issue (you need to elevate to root, or check if something else is using the port). We just pass the address and port through to the OS to bind.

**Comment by WhiteKarma** [comment]
Thank you all very much, 

I am using aspnet core since 2015 integrating with long time existing joomla website. This issue here came as an option, to solve breaking changes after several upgrades on the other side of the integration.
 
We solved it without needing to go on this direction. So all is well and now much much faster using aspnet core 3 improvements ( including precompiled deployment ) and blazzzing fast JSON lib below ( brilliant code! You should hire this guy!!! ) 

    <PackageReference Include="Swifter.Extensions.AspNetCore" Version="1.2.9.6" />
    <PackageReference Include="Swifter.Json" Version="1.2.9.6" />

Please check the source, he implements IL in the core honestly, i've never seen anything like this... Crazy fast... Really really cool...

All the best!!!
