### ISSUE TITLE
The component layout does not override the default layout

### ISSUE THREAD

**Issue by jingzheshan** [aspnet/AspNetCore#16782]
### Describe the bug
The component layout does not override the default layout

### To Reproduce
Put a MainLayout as the DefaultLayout
![image](https://user-images.githubusercontent.com/2770401/68079235-9ce89000-fe4b-11e9-8330-5d465d6d8c3b.png)

Go to the RedirectToLogin.razor, add a component level layout
![image](https://user-images.githubusercontent.com/2770401/68079263-1da78c00-fe4c-11e9-98af-d4cee78fa155.png)

### Expected behavior
The RedirectToLogin.razor should pick up LoginLayout instead of MainLayout

### Additional context
Temp solution for myself:
We can override OnInitAsync in the App.razor to check the identity is authenticated or not to alter the @layout. (Not ideal I guess)

**Comment by mrpmorris** [comment]
Given the component name is RedirectToLogin and it depends on NavigationManager, does this component render anything or just navigate to a different page to force sign in?

**Comment by jingzheshan** [comment]
This component is for displaying the login page. AuthorizeRouteView should take in charge the redirect.

Aside from this topic, I like the current routing design, however still have few questions 🙃

- How to get an overview of the sitemap from a single point?
- How to reuse a component page with a different model but for a different route?
- How to handle nested route? For example:

> user/XXX/posts
> user/XXX/settings
> ```
> +------------------+                  +-----------------+
> | User             |                  | User            |
> | +--------------+ |                  | +-------------+ |
> | | posts        | |  +------------>  | | settings    | |
> | |              | |                  | |             | |
> | +--------------+ |                  | +-------------+ |
> +------------------+                  +-----------------+
> ```

Here is a very rough idea 💡
```
<Routes AppAssembly="@typeof(Program).Assembly">
   <Guards>
      <Guard from="" to="" do=""></Guard>
   </Guards>
   <Route path="user/:id" component="@typeof(User)" >
      <Route path="" component="@typeof(UserHome)" />
      <Route path="posts" component="@typeof(UserPosts)"/>
      <Route path="settings" component="@typeof(UserSettings)" />
   </Route>
</Routes>
```

We are composing our application with components, I ❤ it, if we can achieve more with this architect, I believe many developers will buy you a ☕ when meet.

**Comment by javiercn** [comment]
@jingzheshan thanks for contacting us.

This behavior is by design. Layouts are just components and for that reason a child component can't override the layout from a parent component unless both components explicitly cooperate to do so.

In your case you could choose to use the raw primitive types instead of authorizerouteview and routeview to achieve the behavior you expect.

**Comment by jingzheshan** [comment]
@javiercn thanks for the clarification it matches my assumption. 😄
I think the main problem I want to dig it out is with current design how it can end up with a naive developer got confused.
