### ISSUE TITLE
Update Blazor validation sample to use Microsoft.AspNetCore.Blazor.DataAnnotations.Validation

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#16784]
Update https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/Validation to use Microsoft.AspNetCore.Blazor.DataAnnotations.Validation.

**Comment by mrpmorris** [comment]
@danroth27 
I'm hoping this ticket indicates you'll be getting rid of that class in favour of something like the generic approach I suggested. Did you read my feedback on the Recursive validator PR?

**Comment by javiercn** [comment]
@pranavkm already did this.
