### ISSUE TITLE
Blazor: Default template unable to change .cs to .razor

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#16786]
Using the default template:

1) Add a file MyItem.cs under /Pages
2) Rename MyItem.cs to MyItem.razor
3) Take the content from Counter.razor and paste it into MyItem.razor

Result: Unable to build the project.

The  .csproj contains these entries:

```
  <ItemGroup>
    <Content Remove="Pages\MyItem.razor" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Pages\MyItem.razor" />
  </ItemGroup>
```

Removing those and the project builds again.

**Comment by javiercn** [comment]
@Postlagerkarte thanks for contacting us.

@NTaylorMullen this seems to be a project system issue I believe. VS adds the two item groups above, which makes the file be treated as C#. If you remove the two of them and re-open the document it correctly parses it as razor. Can you follow up with the right people?
