### ISSUE TITLE
UseProxyToSpaDevelopmentServer slow when passing 'Connection' header

### ISSUE THREAD

**Issue by ChristopherHaws** [aspnet/AspNetCore#16797]
### Describe the bug
When using `UseProxyToSpaDevelopmentServer` I noticed that all requests to the proxy were taking over 1 second to complete. When I access the resource directly (not via the SPA proxy) it takes about 2ms. After some debugging, I found that the cause is the `Connection` header being passed to the proxied server. When I remove the `Connection` header, the request now takes about 40ms.

https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/SpaServices.Extensions/src/Proxying/SpaProxy.cs#L133

### To Reproduce
1. Create an ASP.NET Core 3.0 app that uses `UseProxyToSpaDevelopmentServer`
2. I am using webpack-dev-server as the dev server (not sure if this matters or not)
3. Notice that every proxied request takes 1+ seconds

### Expected behavior
The request should respond with similar times as the dev server. I can understand some overhead since it is copying the request and response, but not 500x slower.

### Additional notes
I'm not sure if I should make a separate bug for this, but I also ran into an issue with the cookie header getting copied which causes requests to fail. I had to add a pretty hacky solution to our project that removes the cookie header before calling the proxy middleware. I believe the cause of the error is specifically when there is a `SameSite=strict` cookie since it happens when i have a CSRF cookie.

Perhaps one mitigation could be to add the ability to disable copying headers or add an allowed/disallowed headers as an option on `UseProxyToSpaDevelopmentServer`.

**Comment by javiercn** [comment]
@ChristopherHaws thanks for contacting us.

Would you like to provide a PR to improve this behavior?

**Comment by mkArtakMSFT** [comment]
Thanks for your contribution, @ChristopherHaws 👍
