### ISSUE TITLE
Blazor: Tooltip icon wrong size?

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#16792]
I am well aware that this a minor detail:

![image](https://user-images.githubusercontent.com/8482283/68089905-eba72180-fe6d-11e9-9058-f7d5666bc560.png)

but isn't the size of the tooltip item wrong?

Compare it with this:

![image](https://user-images.githubusercontent.com/8482283/68091357-fcac5e80-fe7e-11e9-842e-565e840ce6c4.png)

**Comment by javiercn** [comment]
@Postlagerkarte thanks for contacting us.

Could you report this issue through the send feedback button on the top right corner of visual studio? We'll route the issue to the right team, but that way it will get looked at sooner.

@vijayrkn I believe this is a tooling issue. Can you have someone look at it?

**Comment by vijayrkn** [comment]
@jodavis

**Comment by jodavis** [comment]
@Postlagerkarte, did you open a feedback ticket on VS? We have a fix for the glitch that will appear in a future update to Visual Studio.

**Comment by Postlagerkarte** [comment]
@jodavis : great! very happy that the took care of it - the icon looked so strange :) I created no feedback ticket.
