### ISSUE TITLE
[SS Blazor] Hotreload for 3.1?

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#16791]
Hello Team;
Will V3.1 have a Hot Reload for SS Blazor? If not, can we request it as a feature please?

Thanks!
..Ben

**Comment by Postlagerkarte** [comment]
I believe it is tracked at #5456

**Comment by BenHayat** [comment]
@Postlagerkarte 
Looking at the history, I'm still not clear, where we are for the release of 3.1
Or do we have to wait till May next year.

**Comment by Postlagerkarte** [comment]
I don't think so -  #5456 is scheduled for the 5.0 milestone : https://github.com/aspnet/AspNetCore/milestone/61

**Comment by javiercn** [comment]
@BenHayat thanks for contacting us.

As @Postlagerkarte mentions this feature is scheduled for 5.0. For server-side blazor you could probably use dotnet watch directly with some tweaks.
