### ISSUE TITLE
Provide implementation of Tokio.rs as an alternative to Libuv Transport in Kestrel

### ISSUE THREAD

**Issue by jadhavajay** [aspnet/AspNetCore#16795]
Provide an alternative transport of tokio.rs (https://tokio.rs/) to Libuv. Tokio.rs is an async runtime for Rust.

### Example:
Deno (https://deno.land) makes use of tokio.rs intead of libuv.

**Comment by davidfowl** [comment]
That's something that should be done as a community project. We're not going to ship that out of the box or as a package. If you or somebody else start the implementation we'd love to review it!

**Comment by jadhavajay** [comment]
I though this project is now a community project. Is there any other community repo where I should report this issue into?

**Comment by anurse** [comment]
@davidfowl meant a Tokio transport would be a good candidate for it's own separate community project. We don't intend to include or support an alternate transport in the main product at this time. Introducing a new transport into the main repo is quite a significant amount of work for us as we'd be signing up to maintain it fully ourselves.

Feel free to start up such a project and we'd be happy to help review it and provide guidance.
