### ISSUE TITLE
Razor Pages AddRazorRuntimeCompilation Options and opt.AdditionalReferencePaths failing to load types

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/AspNetCore#16798]
I have an standalone tool that dynamically lets the user run a Web site out of an Arbitrary folder they provide at runtime. I want to allow them to add additional assemblies that they can reference in the arbtrary folder (or rather a `./PrivateBin` folder below it).

I'm using code like the following to add the dlls in the folder (note WebRoot could be an arbitrary folder like `/temp/MyLocalSite`:

In ConfigureServices:

```cs
if (UseRazor)
{
    services.AddRazorPages(opt => { opt.RootDirectory = "/"; })
        .AddRazorRuntimeCompilation(
            opt =>
            {                
                opt.FileProviders.Add(new PhysicalFileProvider(WebRoot));
                LoadPrivateBinAssemblies(opt);
            });
}
```
And to actually load the refs:

```cs
private void LoadPrivateBinAssemblies(MvcRazorRuntimeCompilationOptions opt)
{
    var binPath = Path.Combine(WebRoot, "PrivateBin");
    if (Directory.Exists(binPath))
    {
        var files = Directory.GetFiles(binPath);
        foreach (var file in files)
        {
            if (!file.EndsWith(".dll", StringComparison.CurrentCultureIgnoreCase) &&
               !file.EndsWith(".exe", StringComparison.InvariantCultureIgnoreCase))
                continue;

             opt.AdditionalReferencePaths.Add(file);
        }
    }
}
```

However when I then try to reference a type from these added assemblies I get the following error:

![image](https://user-images.githubusercontent.com/1374013/68095567-9f001e00-fe4e-11e9-8917-57effdb35250.png)

It looks like the assemblies and types are found (notice the version number is correct), but razor is not resolving the path?

### Expected behavior
Load assemblies out of additionally specified arbtitrary folder.

### Info
* DotnetCore 3.0 RTM
* Kestrel
* Windows Console/Dotnet Tool app

### Repo
The code and project for this can be found here if anybody wants to try this out:

https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload/blob/master/LiveReloadServer/Startup.cs

To run this:

* Set the runtime `--WebRootPath`  to a folder where Web or Razor Files exist
* Add a `PrivateBin` folder and an assembly of your choice 
* Create a Razor Page that references some type in that assembly

I use Markdig.dll  (Markdig package since it's self-contained) like this:

```cs
 @Markdig.Markdown.ToHtml("**bold** Text",null)
```

**Comment by javiercn** [comment]
@RickStrahl thanks for contacting us.

@pranavkm can you take a look?

**Comment by pranavkm** [comment]
@RickStrahl adding things as additional compilation references doesn't really add them to the load context at runtime. This would explain why the view \ Razor Page compiles correctly, but you get a runtime error since the type isn't present. Uncommenting this line of code: https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload/blob/master/LiveReloadServer/Startup.cs#L228 got things working. 

Would you expect adding additional compilation references to also make the assembly available at runtime?

**Comment by RickStrahl** [comment]
Arrghhh - out of all the combinations I tried that was one I didn't. Sure enough that works!

Now, I'll say this: This is very counter intuitive. If you allow to add reference paths (which BTW, sounds like folder names, not actual assemblies) I would assume you also load those for me. I see no reason to reference assemblies, and then not have them loaded or accessible in your code. If there is some good reason for not loading may be an additional parameter to allow loading. 

This would remove the logic for having to decide which load context might have to be used to actually load the assemblies from because the framework knows where it should load into.

**Comment by RickStrahl** [comment]
Giving this a little more thought what I would like to see is rather than adding individual assemblies, is be able to specify a folder where additional references live and then have the startup code load all the assemblies stored there. I'm doing this in the simplistic code right now, but there are a number of tricky issues there when dependencies can't be found or they are loaded out of order. It would be nice if that could be handled at the framework level.

Edge case I know, but if you dynamically point at a disk location to serve content from then this would be the expected behavior - like AppDomain private bin startup specification, but delayed to do at runtime.

It's a possible security issue for assembly injection, but so is the code I'm running above that's already working, so making this easier won't really make the problem any worse.

**Comment by pranavkm** [comment]
I hadn't noticed your most recent comment before I created this PR - https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload/pull/18 - but using an `ApplicationPart` gets you all the way, adding it both as a runtime and compile time component and additionally setting it up so MVC will perform, among other things, controller discovery on additional references.

> I'm doing this in the simplistic code right now, but there are a number of tricky issues there when dependencies can't be found or they are loaded out of order. It would be nice if that could be handled at the framework level.

The framework has a pattern using load context for doing things like this - https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support. Unfortunately, using a custom load context currently doesn't work well with MVC views \ Razor Pages since they're loaded in to the default load context. We haven't seen a lot of interest in making this work, which is primarily why we haven't prioritized it.

**Comment by RickStrahl** [comment]
Yeah as I mentioned most of this is an edge case scenario. The ApplicationParts bit makes it even more relevant to preload the assemblies, because it's explicitly meant to bring in additional content and it looks like even with that you still need to load the assembly explicitly if you want to access it (which seems weird - wouldn't the framework probe for the Application Part interfaces it looks like, like controllers, views etc.)?

IAC, I think we have a solution here to close this issue. 

The rest of my comments were more of an enhancement request related to expectations that I would have for the functionality based on the naming and for Application Parts at least its feature set.

Thanks for your @pranavkm!
