### ISSUE TITLE
Blazor: Go To Implementation not working

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#16793]
Using a Blazor Component in .cs file -> the "Go To Implemention" command has no effect.

Example:

![sample](https://user-images.githubusercontent.com/8482283/68090681-eac6bd80-fe76-11e9-9bab-9f8703239711.gif)

**Comment by javiercn** [comment]
@Postlagerkarte thanks for contacting us.

@NTaylorMullen @rynowak @ajaybhargavb thoughts?

**Comment by javiercn** [comment]
This is likely a dupe of #9731
