### ISSUE TITLE
Scaffolding Identity on visual studio 2019 core 3.0 issue

### ISSUE THREAD

**Issue by MohammadElKhatib** [aspnet/AspNetCore#16802]
I just installed visual studio 2019 and core 3.0 is included with the installation.

Then i created new project without authentication after that i scaffolded the identity with custom user and run the application but not able to reach register and login page it is redirecting me to home page with url:

https://localhost:44391/?area=Identity&page=%2FAccount%2FLogin

also
using Microsoft.AspNetCore.Identity;
is missing in RegisterConfirmation Page

**Comment by javiercn** [comment]
@MohammadElKhatib thanks for contacting us.

That likely means you are missing `endpoints.MaPages()` and `services.AddRazoPages or services.AddMvc()` in your Startup.cs

@HaoK I believe the scaffolder readme might need changes here, if not the scaffolder itself.

**Comment by MohammadElKhatib** [comment]
@javiercn that's not the case  here is the startup class:


```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddRazorPages();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
```

**Comment by HaoK** [comment]
I think you just need to add  `endpoints.MapRazorPages();` to the Configure for the identity areas to get picked up.

**Comment by HaoK** [comment]
But yeah this looks like a scaffolding issue as well

**Comment by MohammadElKhatib** [comment]
> endpoints.MapRazorPages()

@HaoK  you are right that makes it work but it is a scaffolding issue because I tested the same case on windows and mac.

on windows when running a project with authentication it is working normally but once scaffolding identity with custom user it is not working!

Thank you

**Comment by HaoK** [comment]
The scaffolder never added these lines before, the readme does mention that MapRazorPages needs to be manually added:

https://github.com/aspnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/ScaffoldingReadme.cshtml#L27

I guess we can update the readme to also mention 
```
            services.AddControllersWithViews();
            services.AddRazorPages();
```

instead of `AddMvc()` as well

**Comment by MohammadElKhatib** [comment]
@HaoK yeah it might not been added before in core 2.2 but it was working without need to add any lines after scaffolding identity

I am sorry if i thought this as issue in core 3.0 but this was the first experience for me with core 3.0

Thanks for support and regards.

**Comment by HaoK** [comment]
Updated the readme in scaffolding thanks for reporting this issue @MohammadElKhatib
