### ISSUE TITLE
Blazor WebAssembly Routing ❓ and 💡

### ISSUE THREAD

**Issue by jingzheshan** [aspnet/AspNetCore#16801]
I like the current routing design, however still have few questions 🙃

- How to get an overview of the sitemap from a single point?
- How to reuse a component page with a different model but for a different route?
- How to handle nested route? For example:

user/XXX/posts
user/XXX/settings

```
+------------------+                  +-----------------+
| User             |                  | User            |
| +--------------+ |                  | +-------------+ |
| | posts        | |  +------------>  | | settings    | |
| |              | |                  | |             | |
| +--------------+ |                  | +-------------+ |
+------------------+                  +-----------------+
```
Here is a very rough idea 💡

```
<Routes AppAssembly="@typeof(Program).Assembly">
   <Guards>
      <Guard from="" to="" do=""></Guard>
   </Guards>
   <Route path="user/:id" component="@typeof(User)" >
      <Route path="" component="@typeof(UserHome)" />
      <Route path="posts" component="@typeof(UserPosts)"/>
      <Route path="settings" component="@typeof(UserSettings)" />
   </Route>
</Routes>
```
We are composing our application with components, I ❤ it, if we can achieve more with this architect, I believe many developers will buy you a ☕ when meet.

**Comment by javiercn** [comment]
@jingzheshan thanks for contacting us.

Those are not features that our current routing system supports. The best you could do right now/today is to factor your components in a way where its easy to create a routable page with each of the combinations you need.

**Comment by javiercn** [comment]
> * How to get an overview of the sitemap from a single point?

You could write a component that reflects over all component types on your assembly that have a [Route] attribute to build a site map for your app.

> * How to reuse a component page with a different model but for a different route?

You could have more than one page directive to define different routes.

> * How to handle nested route? For example:

This is not a current feature we support. We have a separate bug tracking it.

**Comment by jingzheshan** [comment]
@javiercn thanks for the answer. 
I am very excited to see the progress of the Blazor WebAssembly made so far, impressive stuff 👏
Let's push it to next level and I can not wait to see it in production next year 😄
