### ISSUE TITLE
ITlsHandshakeFeature is null in iis

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [aspnet/AspNetCore#16803]
Hi,

We are planning to validate the cipher using ITlsHandshakeFeature in IIS and azure web app as well.

I tried below code, but it returning null in iis 

`HttpContext.Features.Get<ITlsHandshakeFeature>()`

Please consider this issue as high priority and resolve the issue.

**Comment by Tratcher** [comment]
Please don't open duplicate issues. https://github.com/aspnet/AspNetCore/issues/15397
