### ISSUE TITLE
Missing UseWindowsService in IWebHostBuilder

### ISSUE THREAD

**Issue by j0nimost** [aspnet/AspNetCore#16804]
### IWebHostBuilder missing UseWindowsService
I am using the new `.NET 3.0` and I am having a hard time deploying a worker service which in it I have hosted an ASP.NET Core API. 

When deploying am getting this error;
```
[SC] StartService FAILED 1053:

The service did not respond to the start or control request in a timely fashion.
```

### To Reproduce
My Worker service `Program class` is as shown below;

```
 public static void Main(string[] args)
 {
      CreateWebHostBuilder(args).Build().Run();
 }

       
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
    .UseStartup<Startup>()
    .UseKestrel((context, serverOptions) =>
    {
           serverOptions.ListenAnyIP(1000);
           serverOptions.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(1.5);
     });
```
From the above sample I cannot specify the environment runtime that is `Windows Service`(.UseWindowsService()) because the IWebHostBuilder doesn't have this defition. 
Ideally, I expected both `IHostBuilder` and `IWebHostBuilder` to share the definition of `UseWindowsService()`. Can you kindly assist with this missing feature for I am stuck and can't deploy the Worker Service.

**Comment by djinnet** [comment]
Do you have **Microsoft.Extensions.Hosting.WindowsServices** in the nuget packages?

I would suggest to take a look at the link as it explained everything from the start of the project to deploy project as windows service: https://devblogs.microsoft.com/aspnet/net-core-workers-as-windows-services/

**Comment by javiercn** [comment]
@Tratcher Is this the right area for it?

**Comment by j0nimost** [comment]
I have it already installed for some reason; `IWebHostBuilder` doesn't pick it up.

**Comment by Tratcher** [comment]
Microsoft.Extensions.Hosting.WindowsServices is for IHostBuilder, which is what new 3.0 apps use now.
Microsoft.AspNetCore.Hosting.WindowsServices is for IWebHostBuilder.

**Comment by j0nimost** [comment]
I see that's what I was missing then; had a hard time combing through the documentation;

```
public static void Main(string[] args)
        {
           
            CreateWebHostBuilder(args).Build().RunAsService();

        }
        
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseContentRoot(Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName))
                .UseStartup<Startup>()
                .UseKestrel((context, serverOptions) =>
                {
                    serverOptions.ListenAnyIP(1000);
                    serverOptions.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(1.5);
                });
```
