### ISSUE TITLE
Where is ValidationHelpers.GetModelStateList gone in aspnetcore 3.0?

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/AspNetCore#16814]
Where is ValidationHelpers.GetModelStateList gone in aspnetcore 3.0?
What can I use instead of it? I didn't found any mentions about this change.

I had this code.

  ```
          var modelStates = ValidationHelpers.GetModelStateList(viewData, excludePropertyErrors);

            var htmlSummary = new TagBuilder("ul");
            foreach (var modelState in modelStates)
            {
                // Perf: Avoid allocations
                for (var i = 0; i < modelState.Errors.Count; i++)
                {
                    var modelError = modelState.Errors[i];
                    var errorText = ValidationHelpers.GetModelErrorMessageOrDefault(modelError);

                    if (!string.IsNullOrEmpty(errorText))
                    {
                        var listItem = new TagBuilder("li");
                        listItem.InnerHtml.SetHtmlContent(errorText);
                        htmlSummary.InnerHtml.AppendLine(listItem);
                        isHtmlSummaryModified = true;
                    }
                }
            }
```

**Comment by pranavkm** [comment]
@xrkolovos we made an announcement here - https://github.com/aspnet/Announcements/issues/326 - about making formerly pub-internal types (types in the `.Internal` namespace) non-public as part of the 3.0 release. For 3.0, copying the code in to your app https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Mvc/Mvc.ViewFeatures/src/ValidationHelpers.cs#L46-L112 would be the way to go. It does look fairly involved, so this might be something we may consider making public in the future if there are legitimate use cases.

Out of curiosity, why are you unable to use `ValidationSummaryTagHelper`?
