### ISSUE TITLE
Microsoft.AspNetCore.Authentication.JwtBearer 3.0.0 is not compatible with netstandard2.1

### ISSUE THREAD

**Issue by chassq** [aspnet/AspNetCore#16813]
### Describe the bug
We get an error when trying to add the Microsoft.AspNetCore.Authentication.OpenIdConnect 3.0.0 pkg to a netstandard 2.1 lib. Why would thei be? We are trying to use the TokenValidatedContext object in the netstandard 2.1 lib. Can this be done?

### Further technical details
- ASP.NET Core SDK 3.0.100
- Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014459
 Commit:    ac3b59712d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview1-014459\

Host (useful for support):
  Version: 3.1.0-preview1.19506.1
  Commit:  bbf5542781

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE VS 16.4.0 Preview 2

**Comment by blowdart** [comment]
You cannot mix and match major versions like this.

**Comment by blowdart** [comment]
ASP.NET Core 3 packages target netcoreapp3.1 not netstandard

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#framework-reference

**Comment by chassq** [comment]
OK, so if we have a Razor Class Lib, which is setup as netstandard 2.1, then we cannot reference the pkg Microsoft.AspNetCore.Authentication.OpenIdConnect 3.0.0. Is that correct? Is there a way around this? Would we need to have the RCL target netcoreapp3.0?

Thanks!

**Comment by Tratcher** [comment]
You'd need to target or cross target netcoreapp3.0 and add `<FrameworkReference Include="Microsoft.AspNetCore.App" />`.

**Comment by chassq** [comment]
Ok. Think we got it. Most appreciated!
