### ISSUE TITLE
AspNetCore 3.0 Blazor Server inconsistent rendering between server and client of authorized components 

### ISSUE THREAD

**Issue by pheuter** [aspnet/AspNetCore#16823]
I am seeing a weird issue during the runtime of my ASP.NET Core 3.0 Blazor Server app where the prerendered page properly renders HTML inside of an `<AuthorizeView Policy="Admin">` but quickly gets updated to render the `<NotAuthorized>` version once the browser client loads. I've attached a video demo below as well as the relevant source code. You can see the view flicker from the properly authorized view to the unauthorized one, even though the user remains logged in with the appropriate claims.

### Demo
![Demo](https://media.giphy.com/media/jQc1TLkQKzxYxkLoeh/giphy.gif)

### Source

In `Startup.cs`:
```csharp
services.AddAuthorization(options =>
{
    options.AddPolicy("Admin", policy =>
    {
        policy.RequireAssertion(context => context.User.HasClaim(c => c.Issuer == "Microsoft"));
    });
});
```

In `NavMenu.razor`:
```razor
<AuthorizeView Policy="Admin">
    <Authorized>
        <NavLink href="/admin">Admin</NavLink>
    </Authorized>
</AuthorizeView>
```

In `Admin.razor`:
```razor
@page "/admin"
@attribute [Authorize(Policy = "Admin")]

<h3>Admin</h3>
```

**Comment by pheuter** [comment]
I should add that the same exact app works just fine in development. Can this have something to do with the fact that the production app uses Azure SignalR and for some reason that fails to read claims on the user session? Interesting enough, Azure SignalR is still able to tell that my user is logged in.

**Comment by pheuter** [comment]
I've added some debug output to the Razor page to enumerate over all user claims using the code below. Something weird is happening where the initial server render contains the proper set of claims and the right issuer, and then when the client loads it switches all the issuers to LOCAL AUTHORITY and duplicates the claims.

`Page.razor`:
```razor
<AuthorizeView>
    <Authorized>
        @foreach (var claim in context.User.Claims)
        {
            <p>@claim.Type - @claim.Value Issued By @claim.Issuer</p>
        }
    </Authorized>
</AuthorizeView>
```

Server rendered:
![Server_rendered](https://user-images.githubusercontent.com/92698/68161368-c2e16380-ff23-11e9-824a-7eed398db71b.jpg)

Client rendered:
![Client_rendered](https://user-images.githubusercontent.com/92698/68161376-c7a61780-ff23-11e9-98f4-fcbf0fbb5855.png)

**Comment by javiercn** [comment]
@pheuter thanks for contacting us.

@pheuter The signalr service captures the identity of the current user before redirecting and as part of that the set of claims might be different.

If the user identity varies for prerendered requests vs for requests with signalr service, that's likely to cause the issue.

I'm not sure if the claims can be normalized when the signalr service captures them, but you can probably apply a claims transformer on the non-signalr service case to standarize them.

**Comment by pheuter** [comment]
@javiercn Can you point me to an example of "apply a claims transformer"?

**Comment by pheuter** [comment]
This current discrepancy between local dev and prod is affecting the deployment of our application. Is there a reasonable workaround you can suggest, ideally with some code example that applies to this particular case?

I'm using [Microsoft auth](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-3.0) which automatically handles setting the claims for me, so I'm not exactly sure what you mean by applying transformers.
