### ISSUE TITLE
This is still broken on 16.4.0 Preview 2 :: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' #15282

### ISSUE THREAD

**Issue by MichaelLant** [aspnet/AspNetCore#16826]
It looks like #15282  [](https://github.com/aspnet/AspNetCore/issues/15282)  issue was closed, but I have been adding comments to that thread and not receiving any response. This issue was closed, but it is far from resolved. Should I open a new issue here?

**Comment by javiercn** [comment]
@MichaelLant Let's continue the discussion in the other issue. I've already answered there.
