### ISSUE TITLE
Shutdown Event

### ISSUE THREAD

**Issue by ChristopherJTrent** [aspnet/AspNetCore#16824]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]
It'd be great if an event was fired when the server received a shutdown command, what so we can, you know, propagate changes to local files, and save changes made during run-time
### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by javiercn** [comment]
@ChristopherJTrent thanks for contacting us.

This is already possible by registering a callback to the appropriate event in `IHostApplicationLifetime`. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0#ihostapplicationlifetime for details
