### ISSUE TITLE
MVC 3.0 HTML Updates While Debugging

### ISSUE THREAD

**Issue by clockwiseq** [aspnet/AspNetCore#16837]
In all previous versions of ASP.NET Core (MVC or Razor Pages), one could make modifications to HTML in a view while debugging, save it, and refresh the browser and your changes would be visible.  This is not the case any longer.  

To reproduce this issue, all you have to do is open Visual Studio, create a new 3.0 web project, use MVC, start debugging.  Next, open the Index.cshtml view under the Home folder under Views and modify the HTML is some manner.  Save the changes, refresh the browser window and you'll see that the changes are not present.

**Comment by javiercn** [comment]
@clockwiseq Thanks for contacting us.

This is an intentional change in 3.0. See the announcement https://github.com/aspnet/Announcements/issues/343 and how to enable the functionality.

**Comment by clockwiseq** [comment]
Thank you for the response.  I added the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package using the package manager and the call to AddMvcRazorRuntimeCompilation is bad:

```'IMvcBuilder' does not contain a definition for 'AddMvcRazorRuntimeCompilation' and no accessible extension method 'AddMvcRazorRuntimeCompilation' accepting a first argument of type 'IMvcBuilder' could be found (are you missing a using directive or an assembly reference?)```

**Comment by clockwiseq** [comment]
Aaah, looks like it's now `.AddRazorRuntimeCompilation();`.  Although I am appreciative of this fix, I am quite concerned about this change.  Others have expressed their concern as well regarding the excessive files added to the project via that package reference.  Is there a path to undoing whatever was done that broke this functionality in the first place?  The speed difference is horrendous.
