### ISSUE TITLE
How to setup integration tests so that Program.Main gets tested

### ISSUE THREAD

**Issue by nxtx** [aspnet/AspNetCore#16839]
The gist of my question is: how to setup integration tests so that Program.Main gets tested, or how to move most of the logic that are generally found in Program.Main to start up so to make Program.Main smaller, hence not so critical if not covered by integration tests. 

Description:
I can setup an integration test as the following: 

```csharp
public class WebAPITest : IClassFixture<WebApplicationFactory<Startup>>
{
    private readonly WebApplicationFactory<Startup> _factory;

    public WebAPITest(WebApplicationFactory<Startup> factory)
    {
        _factory = factory;
    }

    [Fact]
    public async Task IfConsumerReceives()
    {
        var client = _factory.CreateClient();
        var response = await client.GetAsync("/api/v1/items");
        response.EnsureSuccessStatusCode();
    }
}
```

where I define `Startup` and `Program.Main` as the following: 

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        var host = HostBuilder(configuration, args).Build();
        host.Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) => 
        Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(builder =>
        {
            builder.UseStartup<Startup>();
        });

    private static IHostBuilder HostBuilder(IConfiguration configuration, string[] args) =>
        Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(builder =>
        {
            builder.UseConfiguration(configuration);
            builder.UseStartup<Startup>();
            builder.CaptureStartupErrors(false);
            builder.UseContentRoot(Directory.GetCurrentDirectory());
        }).
        UseServiceProviderFactory(new AutofacServiceProviderFactory());
}

public class Startup
{
    public IConfiguration Configuration { get; }
    public ILifetimeScope AutofacContainer { get; private set; }
    public IWebHostEnvironment WebHostingEnvironment { get; private set; }

    public Startup(IConfiguration configuration, IWebHostEnvironment env)
    {
        Configuration = configuration;
        WebHostingEnvironment = env;
    }

    public void ConfigureServices(IServiceCollection services)
    {
        services
            .AddMvc(options => options.EnableEndpointRouting = false)
            .SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
        services.AddOptions();
    }

    public void ConfigureContainer(ContainerBuilder builder)
    {
        //some configs such as: builder.RegisterModule(new AutofacModule());
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseHsts();
        app.UseHttpsRedirection();
        app.UseMvc();;
    }
}
```

I guess `Program.Main` and `Startup` as pretty much how they are commonly setup. 

My concerns are: 

1. with this setup, integration tests start from `Startup` and `Program.Main` and all the `Host` setup/config is not tested. 

2. Some `Startup` logic may not work without the configs in `Program.Main`. For instance, `autofac` will fail with the following error without `UseServiceProviderFactory(new AutofacServiceProviderFactory()` set in the `Program.Main`, which is not executed when running the integration tests as the given example. 

> Unable to cast object of type 'Microsoft.Extensions.DependencyInjection.ServiceCollection' to type 'Autofac.ContainerBuilder'.

What is the recommended way to setup `Startup`, `Program.Main`, or the integration tests so that `Program.Main` gets in the integration test execution path?

PS: I generally end up creating a custom `WebApplicationFactory` where I mostly repeat what is in `Program.Main`, as the following, however, I guess this approach is not super exciting as it does not test the actual `Program.Main`: 

```csharp
public class WebAPITestApplicationFactory : WebApplicationFactory<Startup>
{
    protected override IHostBuilder CreateHostBuilder()
    {
        return Host.CreateDefaultBuilder()
        .ConfigureWebHostDefaults(builder =>
        {
            builder.UseStartup<Startup>();
        }).
        UseServiceProviderFactory(new AutofacServiceProviderFactory());
    }
}
```

**Comment by javiercn** [comment]
@nxtx thanks for contacting us.

I'm not sure I understand your question. 

WebApplicationFactory will call into your CreateHostBuilder method by default. If you need something else, then you need to override CreateHostBuilder and call it yourself.

**Comment by nxtx** [comment]
@javiercn visual studio fails on the following without any error message; so I am not sure how to set up `Program` as Entry point: 

```
public class WebAPITest : IClassFixture<WebApplicationFactory<Program>>
```

**Comment by nxtx** [comment]
Two points: 
- instead of `Startup`, I want to use `Program`, hence get it covered with the integration testss;
- Chancing access modifier from `protected` to `public` causes compile-time error:
   > cannot change access modifier when overriding `protected` inherited member `WebApplicationFactory<Startup>.CreateHostBuilder()`.

**Comment by kle622** [comment]
Is there any more specific reason why you want to include Program as part of the tests? 
The way it helps me to see it is, "Startup" class is the encapsulation of your application and "Program" class is simply a driver in the same way your integration test is a driver.

**Comment by nxtx** [comment]
I would like any possible issues with `Program` (e.g., when my colleagues make PRs) be caught by integration tests. More specifically, recently we forgot to include `UseServiceProviderFactory(new AutofacServiceProviderFactory())` in `HostBuilder` in `Program`, and we mainly rely on tests to capture issues, we noticed the problem long after.  Hence, we're would like to add integration tests that start test from `Program`.

**Comment by nxtx** [comment]
A clarification; even with the following `Program` is not tested (e.g., `HostBuilder` is not called): 

```csharp
public class WebAPITest : IClassFixture<WebAPITestApplicationFactory>
{
    private readonly WebAPITestApplicationFactory _factory;
    public WebAPITest(WebAPITestApplicationFactory factory)
    {
        _factory = factory;
    }
}

public class WebAPITestApplicationFactory : WebApplicationFactory<Program>
{
    public WebAPITestApplicationFactory() : base()
    { }
}
```

**Comment by javiercn** [comment]
We don’t run your program.Main, the convention is to look for CreateHostBuilder as we need access to the host.

Our recommendation is that you don’t put any logic within the program main itself other than the calls present during project creation.

As an alternative add an additional test that doesn’t use WAF and that simply calls your program main to start the app and verify it works.

**Comment by javiercn** [comment]
I'm closing this issue as the question has been answered.

**Comment by nxtx** [comment]
Thanks for the clarification.
