### ISSUE TITLE
[Blazor] Consider bringing Navigation bar to razor files

### ISSUE THREAD

**Issue by Postlagerkarte** [aspnet/AspNetCore#16830]
This is a request to improve the tooling for razor files:

Singe-file component are great but they current do not show a Navigation Bar.  

You can use the navigation bar (the drop-down boxes at the top of the code window) to navigate to code in a codebase. You can choose a type or member to go directly to it. The navigation bar appears when you edit code in a Visual Basic, C#, or C++ code base

Please consider bringing the Navigation bar to .razor files as well!

**Comment by javiercn** [comment]
@Postlagerkarte Thanks for contacting us.

This is a feature request for visual studio, not ASP.NET Core specifically. While we do our best to answer all questions you'll get a better and faster response if you report this issue through the "send feedback button on the top right corner" in Visual Studio.

**Comment by javiercn** [comment]
@vijayrkn Can you route this to the appropriate people?

**Comment by vijayrkn** [comment]
As you mentioned, it is better to have a vs feedback suggestion ticket so that we can route to the appropriate team. Thanks!

**Comment by Postlagerkarte** [comment]
No problem - I created a vs feedback item - https://developercommunity.visualstudio.com/idea/807694/blazor-consider-bringing-navigation-bar-to-razor-f.html
