### ISSUE TITLE
Blazor templates generate incorrect html for the new blazor-error-ui in preview2

### ISSUE THREAD

**Issue by MarkStega** [aspnet/AspNetCore#16843]
### Describe the bug
When you use the Blazor template in VS2019 to create a new app (either CSB or SSB) the html generated in the index.html or _host.cshtml has an error in the 'reload' option. What is generated is
` 
       <a href class="reload">Reload</a>
`
instead of the correct
`
        <a href="" class="reload">Reload</a>
`

### To Reproduce
Generate a new Blazor app in VS2019

### Further technical details
C:\Users\ms>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview2-014569
 Commit:    4bd5d24d87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview2-014569\

Host (useful for support):
  Version: 3.1.0-preview2.19525.6
  Commit:  5672978d91

.NET Core SDKs installed:
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@MarkStega thanks for contacting us.

@ryanbrandenburg Can you take a look?

**Comment by javiercn** [comment]
This was already fixed https://github.com/aspnet/AspNetCore/pull/16719
