### ISSUE TITLE
HttpMethod becomes empty when request hit the server

### ISSUE THREAD

**Issue by prabalk** [aspnet/AspNetCore#16842]
Updated .net core service from _2.1.7_ to _2.1.11_, after upgrade we are seeing random tests failure. Reason for failures is _HttpMethod_ becomes empty string after request hits the server.

Verified with proxy server, _HttpMethod_ is correctly sent from the tests. However, when the request hits the server we receive _HttpMethod_ as empty string, **RANDOMLY**. Sometime all the tests pass, sometime we see failures.

This issue only occurs when we deploy service on AWS, when service and tests are run locally all the test case passes.

On AWS we are running service over .net core _2.1.11_ docker image.

what could be the cause of this issue? what can we do to fix it?

**More details regarding the issue.**

We have a middleware which executes before the request hits the controller class. This middleware perform various operation one of them is to do authentication.

For authentication purpose we require to fetch _HttpMethod_ from the incoming request.

We fetch _httpMethod by below line of code

    HttpContext.HttpRequest.Method

It is not blocked by http.sys, However, when the middleware find out _httpMethod_ == "", it throws exception. Please follow below code snippet

    switch (request.GetMethod())
    {
        case "POST":
        case "PATCH":
        case "PUT":
            isValidHttpMethod = true;
            break;
        default:
            throw new InvalidOperationException("Invalid HttpMethod");
    }

**Comment by jeanpoelie** [comment]
Can you reproduce this in a repository? The issue seems very vague.

**Comment by anurse** [comment]
Are you accessing `HttpContext` from outside of the middleware pipeline (or an MVC controller action, etc.)? That's generally what causes this kind of issue.

Please provide a runnable sample application so we can get the full context on the issue.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by davidfowl** [comment]
@prabalk this sounds like an old issue where a user was accessing the HttpContext after the request was complete via IHttpContextAccessor.
