### ISSUE TITLE
Set timeout on time it takes to read request body?

### ISSUE THREAD

**Issue by chandimar001** [aspnet/AspNetCore#16855]
We are in the process of migrating our code from ASP .NET Core 1.1 to ASP .NET Core 2.1.

I am seeing a lot of the following exceptions in the new version:
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.<ReadAsync>d__35.MoveNext()

According to the following [thread](https://github.com/aspnet/AspNetCore/issues/4733), this is expected as its caused by the client closing the connection.

We stumbled across this in the older service because we had a middleware that would try to parse the body (using StreamReader(context.Request.Body)) so that we could log it, and we noticed that sometimes it would be stuck on this method for up to 30 seconds. We worked around this by enforcing a 500ms timeout on the Task that did this.

The new service doesn't have this middleware - yet. Does ASP .NET 2.x have a way of setting a timeout on this request body parsing operation?

**Comment by Tratcher** [comment]
Using CancellationTokens on the read operations is your best bet. Also, all of the servers have minimum data rate limits. Which server are you using?

**Comment by chandimar001** [comment]
We are using HttpSys 2.1. 

By using CancellationTokens on the read operation, do you mean implementing it in the middleware like we do in the old service? Here is the code snippet we use the in the old service middleware.

```
try
{
       var cts = new CancellationTokenSource(RequestBodyReadTimeout);
       var readBodyTask = this.TryReadRequestBody(context);
       var body = await readBodyTask.WithCancellation(cts.Token);
}
catch (Exception ex)
{
}
```

**Comment by Tratcher** [comment]
No, the CancellationToken should be passed directly to the Stream.ReadAsync calls.

**Comment by anurse** [comment]
As @Tratcher said, the `CancellationToken` on `ReadAsync` calls is the recommended approach for timing out a read. HttpSys lets you configure minimum data rates to ensure that slow clients are terminated.

Closing as this isn't a new feature we plan to add. If the `CancellationToken` aproach isn't usable in your scenario, let us know and we can explore further.
