### ISSUE TITLE
[Blazor] Server app The generated html tag is incorrect

### ISSUE THREAD

**Issue by git-net** [aspnet/AspNetCore#16860]
### Describe the bug
RenderMode.Server or RenderMode.ServerPrerendered
component .razor file use ‘@：’ ,
 generated html tag is incorrect .

### To Reproduce
 
``` razor
 @for (var i = 0; i < 4; i++)
        {
            @if (i % 2 == 0)
            {
                @: <div class="row"  >
                }
            <button>@i</button>

            @if (i % 2 == 1)
            {

            @:  </div>
        }

        }
```

expect  output: 
```
<div class="row">
            <button>0</button>
            <button>1</button>
              </div>
                 <div class="row">
            <button>2</button>
            <button>3</button>
              </div>
```
but i got 
```
<!--!-->
        <!--!--><!--!--><!--!-->            
<div class="row">
</div>      
 <button>0</button>
<!--!-->
  <button>1</button>
<!--!-->
<!--!-->          
<!--!-->             
<div class="row">
</div>  
 <button>2</button>
<!--!-->
<button>3</button>
<!--!-->
<!--!-->          
<!--!-->
```
the div tag closed early.
when i change rendermode to` RenderMode.Static `   or use code in .cshtml it work fine.
 
 ### Further technical details
- ASP.NET Core version 3.0.0
- Include the output of `dotnet --info`
- The IDE  vs2019

**Comment by git-net** [comment]
.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100
 Commit:    04339c3a26

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by git-net** [comment]
is some temporary solution？

**Comment by adrianwright109** [comment]
This might be the same issue as #16809 

Try capturing a local variable inside the for loop for `i`
e.g.
`var localVar = i;`

Then replace all instances of `i` inside the loop with `localVar`

**Comment by javiercn** [comment]
@git-net thanks for contacting us.

@adrian109 I don't think it's the for loop. Here is the generated code
```
namespace BlazorServerApp.Pages
{ 
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    using System.Net.Http;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Components.Authorization;
    using Microsoft.AspNetCore.Components.Forms;
    using Microsoft.AspNetCore.Components.Routing;
    using Microsoft.AspNetCore.Components.Web;
    using Microsoft.JSInterop;
    using BlazorServerApp;
    using BlazorServerApp.Shared; 

    [Microsoft.AspNetCore.Components.RouteAttribute("/")]
    public partial class Index : Microsoft.AspNetCore.Components.ComponentBase
    { 
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            for (var i = 0; i < 4; i++)
            {
                if (i % 2 == 0)
                {   
                   __builder.AddMarkupContent(1, " <div class=\"row\">\r\n");
                }   
                __builder.AddContent(2, " ");
                __builder.OpenElement(3, "button");
                __builder.AddContent(4,    i                );
                __builder.CloseElement();
                __builder.AddMarkupContent(5, "\r\n");
                if (i % 2 == 1)
                {
                    __builder.AddMarkupContent(6, "      </div>\r\n");
                }
            }
        }
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @git-net.
`@: ` is not a supported markup in Blazor.
@NTaylorMullen can we make sure we throw a reasonable error for this situation?

**Comment by mkArtakMSFT** [comment]
Looks like the dupe is #11612

**Comment by git-net** [comment]
not #16809 
seems because rendertreebuilder dont support open tag.
i try use addmarkupcontent (0,'<div>'), it auto closed,and '</div>' ignored.
so problem is razor has a different behavior with cshtml , i have some code need migration.
now i use i++ in loop and add some duplicate code。

**Comment by git-net** [comment]
when i open browser  i just see 3 messages.:)
now i know i will refactoring old code ,not only ctrl c,v.
