### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly.

### ISSUE THREAD

**Issue by Nareshchintakunta** [aspnet/AspNetCore#16861]
.net Core 2.1 app running Azure App service, Recently we started getting the following error,

Any suggestions how to solve this issue?

Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate. at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync() at System.IO.Pipelines.PipeCompletion.ThrowLatchedException() at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result) at System.IO.Pipelines.Pipe.TryRead(ReadResult& result) at System.IO.Pipelines.Pipe.DefaultPipeReader.TryRead(ReadResult& result) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()

**Comment by Tratcher** [comment]
It looks like you're experiencing a bandwidth or client issue. Are you able to investigate this from the client side?

**Comment by Nareshchintakunta** [comment]
Thank you for responding to the issue, and  sorry for replying very late, Tratcher investigate from client side, can you help to higlight what kind of things I can check at client side. Thank you

**Comment by Tratcher** [comment]
What kind of client is it? Does it experience an error before this happens? If you capture a fiddler or wireshark trace does it show data being sent at the expected rate? Is there a lot of network latency between the client and server?

**Comment by Nareshchintakunta** [comment]
Not sure how to simulate this issue, which is causing this issue could not resproduce. But I suspect Mobile client android device is having this issue.

@Tratcher plz find below your questions.

What kind of client is it?
Looks like client is Mobile Android device, 
Does it experience an error before this happens? 
No Error.
If you capture a fiddler or wireshark trace does it show data being sent at the expected rate?
plz guide, how to capture such info.
Is there a lot of network latency between the client and server?
How to find out this info. plz guide.

**Comment by Tratcher** [comment]
If this is a mobile client on a slow or flaky connection then this error is expected. You can use the emulator to reproduce the network conditions: https://stackoverflow.com/questions/7026251/simulate-low-network-connectivity-for-android
