### ISSUE TITLE
version incompatibility

### ISSUE THREAD

**Issue by diego81b** [aspnet/AspNetCore#16869]
Hi,
after updating version Microsoft.AspNetCore.All from 2.2.6 to 2.2.7 I noticed that efcore is still using version 2.2.6. 
Even looking at the EFMigrationsHistory table, the ProductVersion column shows: 2.2.6-servicing-10079

is it that possible ?

best regards
Diego

**Comment by javiercn** [comment]
@diego81b thanks for contacting us.

@anurse Any ideas? Can you route this appropriately?

**Comment by anurse** [comment]
This is expected. We don't ship a new version of *every package*. EF Core didn't take any fixes in 2.2.7 so it's still at version 2.2.6.
