### ISSUE TITLE
Angular authentication/authorization template customize issue 

### ISSUE THREAD

**Issue by collina2019** [aspnet/AspNetCore#16865]
After create an app with API authorization support as shown in doc  :

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0

I add jwt bearer events to customize the logic :

    services.Configure<JwtBearerOptions>(
        IdentityServerJwtConstants.IdentityServerJwtBearerScheme,
        options =>
        {
            options.Events = new JwtBearerEvents
            {
                OnTokenValidated =  context =>
                {
                    //find by the claims in token ,for example , if type is groups
        
        
                    var claims = new List<Claim>
                    {
                    new Claim("groups", "ad")
                    };
                    var appIdentity = new ClaimsIdentity(claims);
        
                    context.Principal.AddIdentity(appIdentity);
        
        
                    return Task.CompletedTask;
                }
            };
        });

After user login , click` fetch data` button , it won't fire the event and reponse return 401 error ;

     WWW-Authenticate: Bearer error="invalid_token", error_description="The signature key was not found"

Any suggestion ?

**Comment by javiercn** [comment]
@collina2019 thanks for contacting us.

@Tratcher any ideas?

**Comment by Tratcher** [comment]
OnTokenValidated is only going to run after a successful authentication. Something in your auth configuration is not setup correctly so you get `error_description="The signature key was not found"` instead.

Does it work if you remove that entire `services.Configure<JwtBearerOptions>` code block? I don't expect so, but it's worth confirming.

Enable the application logs and see if they have more details.

**Comment by collina2019** [comment]
if I remove that entire services.Configure<JwtBearerOptions> code block, it works . I didn’t change anything from default authentication template. Just add the event

**Comment by Tratcher** [comment]
Ah, I see the issue.
https://github.com/aspnet/AspNetCore/blob/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0/src/Identity/ApiAuthorization.IdentityServer/src/Authentication/IdentityServerJwtBearerOptionsConfiguration.cs#L44
AddIdentityServerJwt is using events to get the keys, but you're replacing the events handler. It should work if you modify the existing Events object rather than creating a new one.

**Comment by collina2019** [comment]
How may I use the exist event? Any code sample?

**Comment by Tratcher** [comment]
Just like AddIdentityServerJwt does. https://github.com/aspnet/AspNetCore/blob/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0/src/Identity/ApiAuthorization.IdentityServer/src/Authentication/IdentityServerJwtBearerOptionsConfiguration.cs#L43-L44

**Comment by collina2019** [comment]
Ok , I will try it and let you know

**Comment by collina2019** [comment]
It works , thanks everyone :)

**Comment by Tratcher** [comment]
@javiercn the use of OnMessageReceived here is really fragile and should be revisited. Why can't the keys be resolved during configuration?

**Comment by javiercn** [comment]
@Tratcher I can't remember the details, but it had to do with 'IHttpContextAccessor'. I believe there was a circular DI dependency and we couldn't do it in config/setup for that reason.

I don't feel it's too bad, this is the first time we see it. We just need to document it. I'll file a separate issue to track that.

**Comment by javiercn** [comment]
Filed https://github.com/aspnet/AspNetCore.Docs/issues/15572 to cover the doc update. Closing this as there's no further action to be taken.
