### ISSUE TITLE
UserManager.ResetPasswordAsync(...) returns "Invalid Token" error on password validation errors

### ISSUE THREAD

**Issue by cirocorvino** [aspnet/AspNetCore#16868]
As title states, UserManager.ResetPasswordAsync(...) methods returns "Invalid Token" error on password validation errors.

If password respects validation policies, operation is successful (and so the token is valid...), but otherwise it returns invalid token error.

### Further technical details
- ASP.NET Core version: 2.1
- The IDE is VS 2017

**Comment by cirocorvino** [comment]
Sorry for the insistence but could someone give some feedback, please?
Thank you very much, regards
Ciro C.

**Comment by HaoK** [comment]
The token is verified before the password is attempted to be updated, why is this a problem?

**Comment by cirocorvino** [comment]
It is a roblem because if with a given valid token I call reset-password
with a new password that violates pwd policies then I got an invalid token
error instead a password policy error.
If with the same valid token I execute the call with a new valid password
the reset-password is successful.

Il gio 14 nov 2019, 18:19 Hao Kung <notifications@github.com> ha scritto:

**Comment by HaoK** [comment]
That's not the behavior I see, using the 3.0 templates after going through the forgot password flow, and in the debugger changing the password to something that doesn't have alphanumerics or numbers, I see the proper error message returned.  Perhaps you have customized something?

**Comment by cirocorvino** [comment]
What do you mean for "3.0 templates"? I'm using ASP.NET Core version: 2.1 to implement an Identity Server host application. 

There isn't any customization about password validation in the project .

The method that returns the "invalid token" error on password policy violation is:
`Task<IdentityResult>  Microsoft.AspNetCore.Identity.UserManager<TUser>.ResetPasswordAsync(TUser user, string token, string newPassword);`

The assembly that implements this method is:
`Assembly Microsoft.Extensions.Identity.Core, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60`

More below you find a screenshot that shows the library set and relative versions used in the project (right side) and the source code that executes the call. 

Thanks a lot for your help


![immagine](https://user-images.githubusercontent.com/11599607/69133332-05737600-0ab6-11ea-8a89-b245c6c90394.png)

**Comment by HaoK** [comment]
I mean the method is correctly returning password validation errors as far as I can tell, it will only return a token error if the token is invalid, if you can provide a simplified repro app with the steps you did to encounter the incorrect error you are seeing, we can take a further look.

**Comment by cirocorvino** [comment]
Sorry for my English, I likely expressed myself not so well.. I would know what is it "3.0 templates" with which you have done your tests.

For reproduce my issue you should use the library Microsoft.Extensions.Identity.Core, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
