### ISSUE TITLE
AttributeRoute internal class is not accessible in asp.net core 3.0

### ISSUE THREAD

**Issue by ileve** [aspnet/AspNetCore#16872]
I need to use the `AttributeRoute` class in some asp.net core 3.0 unit tests, but it is not possible because the latest version of nuget package `microsoft.aspnetcore.mvc.core` is less than 3.0. I tried to use `3.0.0-preview4-19123-01` from [here](https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.Mvc.Core), but it didn't work either. Is there any other way ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ileve.
We've changed a lot of pub-ternal types to internal per https://github.com/aspnet/Announcements/issues/326. 
//cc @rynowak

**Comment by pranavkm** [comment]
@ileve, constructing the attribute route in a unit test sounds like testing the behavior of the framework. For scenarios like this, you would be much more successful authoring integration tests - https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0
