### ISSUE TITLE
Throw exception if an infinite component tree is detected

### ISSUE THREAD

**Issue by guidevnet** [aspnet/AspNetCore#16881]
Some days ago I was refactoring the code of a healthy server-side blazor app. After some adjustments here and there, I hit debug. To my surprise, this happens:

![image](https://user-images.githubusercontent.com/10619761/68355565-67170600-00ee-11ea-871a-6fa19f8d6760.png)

The process continued to grow until it froze my operating system and crashed with 31 of my 32GB of RAM consumed.

After two days of digging, I finally found out what was causing the issue: a simple `@layout MainLayout` inside the global _imports.razor file. This caused a recursive and endless component tree. 

Of course, it is my fault: I copied some repeated `@using` and `@inject` and put together in one _imports file, and this `@layout` come along. However, this was extremely hard to debug. No breakpoints getting hit; except if I put on the `Html.RenderComponentAsync<App>` in the _Host file. After hitting F11, the next thing that happens is an OutOfMemoryException. The stack trace showed just the same line of code, and a bunch of framework calls. After two days of frustration, I was starting to think that I was facing [this issue](https://github.com/aspnet/AspNetCore/issues/13676).

### Describe the solution you'd like
Would be nice if the runtime is somewhat capable of throwing an exception (with a friendly and helpful message) if it detects a overly-deep and recursive tree of components (before the OutOfMemoryException). I can see this problem occurring with more people, in several ways.

**Comment by javiercn** [comment]
@guidevnet Thanks for contacting us.

We don't plan to do this as Blazor doesn't check for circular dependencies the same way the C# compiler doesn't check that recursive methods converge, it is in general too expensive or directly intractable.
