### ISSUE TITLE
Migration from 2.2 to 3.0 external dll return null

### ISSUE THREAD

**Issue by Razgort** [aspnet/AspNetCore#16888]
Hello guys,

I'm trying to upgrade my project from asp core 2.2 to asp core 3.0. I resolved all compilation issue with braking change during the migration. So now i run my project in debug mode. And i try to login to my api with postman like i always did. But the fact is that with the new version 3.0 every method that i call from external dll return null... And i can't figure why ... If i call all of these method as of version asp core 2.2 they all work fine ...

Would someone has any idea why ?

**Comment by javiercn** [comment]
@Razgort thanks for contacting us.

Could you provide a minimal repro project that shows the problem you are running into so that we can further investigate?

**Comment by javiercn** [comment]
We're closing this issue as we haven't seen community involvement and we need more information to reproduce the problem. If you have more details about the issue add a reply here with the new information and we'll re-evaluate the issue.
