### ISSUE TITLE
Large PDF base64string not loading embed in Blazor app

### ISSUE THREAD

**Issue by ajai1109** [aspnet/AspNetCore#16896]
### Describe the bug
Large PDF base64string not loading in embed tag inside Blazor application. Small size PDF showing perfectly. If the pdf size is 10 MB or more it is not showing.

### To Reproduce
1. Convert large pdf to bytes,
Byte[] bytes = File.ReadAllBytes("specify large pdf path");
2. Convert bytes to base64string
base64Str = Convert.ToBase64String(bytes, 0, bytes.Length);
base64Pdf = "data:application/pdf;base64," + base64Str;
3. Update base64string in embed tag
embed style="width: 700px; height: 700px;" src="@base64Pdf" type="application/pdf"

### Further technical details
Small size PDF showing perfectly. If the pdf size is 10 MB or more it is not showing.
I have checked with 10 MB pdf it is not showing. Are there any settings like maxRequestLength?

**Comment by javiercn** [comment]
@ajai1109 Thanks for contacting us.

I think you might be running into limitations with how big data-urls can be in the browser?

**Comment by ajai1109** [comment]
@javiercn I have added a sample project in the below link for your reference. Please let me know if any more info needed.
https://github.com/ajai1109/blazorpdfupload.git

**Comment by javiercn** [comment]
@ajai1109 thanks for the repro.

At the very least, this is a very bad idea, as its allocating a huge string in memory. When I tried this on plain HTML this doesn't work on most browsers, so I'm concluding this is a browser limitation and not a Blazor specific issue.

See below how firefox is the only one capable of producing some output.
![notLoading](https://user-images.githubusercontent.com/6995051/68479564-775edc00-01e7-11ea-9a13-24217d598ba9.png)
