### ISSUE TITLE
.NET Core 3 Worker unable write to EventLog in Windows Services

### ISSUE THREAD

**Issue by doggy8088** [aspnet/AspNetCore#16891]
### Describe the bug
I can't see any message been logged in EventLog when I using .NET Core 3 Worker and installed in Windows Services. I was expected write all the log messages in `Information` level to the EventLog.

### To Reproduce
Here is a simple .NET Core 3 Worker project can reproduce this problem:
https://github.com/doggy8088/NETCore3WorkerLogToEventLogProblem

There is no exception at all.

Here are my steps to reproduce this issue:

```sh
dotnet new worker -n w1
cd w1
dotnet add package Microsoft.Extensions.Hosting.WindowsServices
dotnet add package Microsoft.Extensions.Logging.EventLog
```

change the `Program.cs` as below:

```cs
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace w1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(loggerFactory => loggerFactory.AddEventLog())
                .UseWindowsService()
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                });
    }
}
```

Build and publish to a folder:

```sh
dotnet publish -o g:\dist\w1
```

Register and run Windows Service:

```sh
sc create w1 binPath=g:\dist\w1\w1.exe
sc start w1
```

Then I check for the logs in `EventLog Viewer`, I can't see any log information about my Worker app.

### Further technical details
- ASP.NET Core version: `3.0`
- Include the output of `dotnet --info`

    ```txt
    .NET Core SDK (reflecting any global.json):
    Version:   3.0.100
    Commit:    04339c3a26

    Runtime Environment:
    OS Name:     Windows
    OS Version:  10.0.18362
    OS Platform: Windows
    RID:         win10-x64
    Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

    Host (useful for support):
    Version: 3.0.0
    Commit:  7d57652f33
    ```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

    ```txt
    Version: 1.39.2 (user setup)
    Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
    Date: 2019-10-15T15:35:18.241Z
    Electron: 4.2.10
    Chrome: 69.0.3497.128
    Node.js: 10.11.0
    V8: 6.9.427.31-electron.0
    OS: Windows_NT x64 10.0.18362
    ```

**Comment by adrianwright109** [comment]
I think your `appsettings.json` is missing logging configuration for the `EventLog`.

My `appsettings.json` has a section for `EventLog` and my WorkerService is successfully logging to the Application EventLog:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "EventLog": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    }
  }
}
```

**Comment by johnwu1114** [comment]
```
// Default the EventLogLoggerProvider to warning or above
logging.AddFilter<EventLogLoggerProvider>(level => level >= LogLevel.Warning);
```
Ref: https://github.com/aspnet/Extensions/blob/master/src/Hosting/Hosting/src/Host.cs#L102

**Comment by doggy8088** [comment]
@adrianwright109 @johnwu1114  It because any log provider should have a default minimum level defined that should be `Information` level by the docs said. Can I just skip the specific definition for `EventLog` for logging?

**Comment by doggy8088** [comment]
@johnwu1114 Oh, you've got the point. Thanks! 😃 👍
