### ISSUE TITLE
Is 'Synchronous Invoke' possible in server-side blazor?

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#16893]
Hi Team,
 
In blazor server-side, we have used 'invokeAsync' and invokemethodasync' for invoking methods and operation asynchronously. is this possible to make operations synchronously in blazor server-side? If it is possible, then it will affect any server-side blazor behaviours? 

Can any one suggest me on this?

### Further technical details
- ASP.NET Core version sdk 3.1 preview1

**Comment by javiercn** [comment]
@kmuthukumar23 thanks for contacting us.

No, it's not possible as the call needs to be sent through the SignalR connection and there's no way to make that synchronous.
