### ISSUE TITLE
HTTPS Error using IIS Express

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/AspNetCore#16892]
### Describe the bug
I run a vanilla asp.net core web app by checking the checkbox for configuring HTTPS. The application doesn't run correctly.

### To Reproduce
I opened VS, then I chose ASP.NET Core Web Application. The HTTPS configuration was enabled by default. After creating the app, I run it with F5 using IIS Express and the web app is not loading.

### Further technical details
- ASP.NET Core version: 3.1 Preview 2
- Include the output of `dotnet --info`:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview2-014569
 Commit:    4bd5d24d87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview2-014569\

Host (useful for support):
  Version: 3.1.0-preview2.19525.6
  Commit:  5672978d91

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual Studio  2019 version 16.4.0 Preview 4.0

**Comment by Tratcher** [comment]
> The application doesn't run correctly.

Please clarify what does happen.

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/68413796-418e0900-018f-11ea-9e96-e8ceecbf956d.png)

**Comment by MaherJendoubi** [comment]
@Tratcher The secure connection failed. It happened in different browsers : Firefox, Chrome, Edge and IE.

**Comment by blowdart** [comment]
From the earlier tweet thread on this connection resets in all browsers.

https://twitter.com/maherjend/status/1192426810014871552?s=20

![EIxZ2dRWwAcUSqU](https://user-images.githubusercontent.com/796298/68414386-f2bb8180-0144-11ea-98b1-c5c6f922af10.jpg)

**Comment by Tratcher** [comment]
Anything in the VS output window?
If you put a breakpoint in Program.cs does it get hit?

**Comment by blowdart** [comment]
I'm wondering if IIS Express isn't serving up HTTPS

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/68414453-81092500-0190-11ea-8564-918bd89f0da5.png)

This happens only with IIS Express. It works if I use Kestrel.

**Comment by Tratcher** [comment]
Ok, how about the windows event viewer?

**Comment by MaherJendoubi** [comment]
I put breakpoints in the Startup.cs and in the Program.cs. It is not hitten.

**Comment by MaherJendoubi** [comment]
> Ok, how about the windows event viewer?

![image](https://user-images.githubusercontent.com/1798510/68414934-7bf8a580-0191-11ea-9b8c-0ad6dcb6f021.png)

**Comment by blowdart** [comment]
Aha 

ID: 15021, Description: "An error occurred while using SSL configuration for endpoint 0.0.0.0:44300. The error status code is contained within the returned data."

If you open a command prompt and run `netsh http show sslcert > certconfig.txt` you'll get a nice text file with configuration information in it. Open that file in your favourite text editor and search for `0.0.0.0:44300`

If the config is correct you'll see something like

```
    IP:port                : 0.0.0.0:44300
    Certificate Hash       : a774dd1f4944a95baa94f9a143095a90b1b437ab
    Application ID         : {214124cd-d05b-4309-9af9-9caa44b2b74a}
```

If it's not found then the certificate is missing.

**Comment by MaherJendoubi** [comment]
I find the following : 
![image](https://user-images.githubusercontent.com/1798510/68415619-0d1c4c00-0193-11ea-8edb-4b0bd16b6862.png)

**Comment by blowdart** [comment]
OK. Now we need to figure out if that certificate exists.

In a powershell prompt type the following

```
cd cert:\\
Get-ChildItem -Path '****' -Recurse
```
replacing **** with the thumbprint/hacage you have in your screenshot.

**Comment by MaherJendoubi** [comment]
Apologies for my late reply.
![image](https://user-images.githubusercontent.com/1798510/68418725-114b6800-0199-11ea-85c6-e8bdcf11cac6.png)

**Comment by blowdart** [comment]
Is there one on LocalMachine\My too?

**Comment by MaherJendoubi** [comment]
No! 
![image](https://user-images.githubusercontent.com/1798510/68419292-37253c80-019a-11ea-9d06-4444de907f9a.png)

**Comment by blowdart** [comment]
Hmm. There is on mine, but I don't know if it matters. @shirhatti any ideas?

**Comment by Tratcher** [comment]
Sounds like it needs an install repair.

**Comment by MaherJendoubi** [comment]
install repair of VS? Did you succeed to reproduce it or it is only local to my machine?
BTW, I am using the following Windows 10 version :
![image](https://user-images.githubusercontent.com/1798510/68431877-888df580-01b3-11ea-8cfb-db8fa5115dd8.png)

**Comment by MaherJendoubi** [comment]
@Tratcher What you said is totally true. After an install repair, I get this popup
![image](https://user-images.githubusercontent.com/1798510/68434715-f2110280-01b9-11ea-87b3-de98e3acbe17.png)
It works like a charm now. Thanks a lot for your help.

**Comment by shirhatti** [comment]
Shoot. I was just about to ask you share your cert. I'm curious as to why it was invalid 🤷‍♂

**Comment by MaherJendoubi** [comment]
Sorry for that, I was too fast! I did many VS Preview updates maybe that corrupted the SSL tooling.

**Comment by MaherJendoubi** [comment]
@shirhatti how can I help you even after this install repair? Are there some specific logs or files you need to investigate? Or it's too late?

**Comment by MaherJendoubi** [comment]
@shirhatti Unfortunately, I cannot reproduce it again and the cert is valid now:
![image](https://user-images.githubusercontent.com/1798510/68436558-a14fd880-01be-11ea-943a-7a533de08149.png)

**Comment by shirhatti** [comment]
@MaherJendoubi Thanks for offering to help! Unfortunately, I was interested in the bad certificate which is irrecoverable.

**Comment by MaherJendoubi** [comment]
@shirhatti This issue happens again. I will be available for any valuable feedback.

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/68979522-13976d00-07fe-11ea-9b4f-1303271bf6f7.png)

**Comment by shirhatti** [comment]
Can you export the self-signed certificate with private keys and share it? (I'm assuming it should be safe to share the private key here since it's only a self-signed certificate, but please ensure it is safe before you share it)

**Comment by MaherJendoubi** [comment]
How can I export it?

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/68992124-76711e80-0867-11ea-95d7-97f8771132c4.png)

**Comment by MaherJendoubi** [comment]
Is it safe to share the certificate hash like I did before here?

**Comment by Rick-Anderson** [comment]
Other than the interesting academic exercise,  [Troubleshoot certificate problems](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#troubleshoot-certificate-problems) has the solution

```
dotnet dev-certs https --clean
dotnet dev-certs https --trust
```

**Comment by MaherJendoubi** [comment]
@Rick-Anderson FYI, I used the 2 commands but the problem persists.

**Comment by Tratcher** [comment]
> Other than the interesting academic exercise, [Troubleshoot certificate problems](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#troubleshoot-certificate-problems) has the solution
> 
> ```
> dotnet dev-certs https --clean
> dotnet dev-certs https --trust
> ```

That does not apply to IIS Express, only Kestrel. IIS Express sets up its own certificate at install time and the only repair mechanism is to run the installer repair. The interesting question here is how did the cert get broken?

**Comment by anurse** [comment]
@MaherJendoubi you can run this PowerShell command to export the cert (does not work in PowerShell Core, you have to use `powershell.exe`): `Export-Certificate -Cert (dir Cert:\LocalMachine\My\ | where { $_.FriendlyName.StartsWith("IIS") }) -FilePath cert.crt`. Then send us `cert.crt`. The private key is not included but I think that might be enough for this.

The cert should have the friendly name "IIS Express Development Certificate" and be in the Local Machine store. If it's not there, that would cause this problem as well :). The cert IIS uses is **different** from the ASP.NET Core Development Certificate.
