### ISSUE TITLE
RegularExpression validation does not handle \p{L} properly

### ISSUE THREAD

**Issue by jasonleenaylor** [aspnet/AspNetCore#16904]
### Describe the bug
We are using the RegularExpressionAttribute to validate a Name field and want to handle more than ASCII characters. Using the regular expression @"[\p{L}\s-'\.]+" works to match the strings we need. Example: "François O'Brian-McKay Jr."

This works fine in a C# unit test but when deployed on the server it only validates the 'L' character and the punctuation.

### To Reproduce

``` C#
public class TestModel : PageModel
{
        [RegularExpression(@"^[\p{L}\s-'\.]+$", ErrorMessage = "Invalid characters in name.")]
        public string Name { get; set; }
}
```

### Further technical details
- ASP.NET Core 2.1

.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Unit test and work done in Microsoft Visual Studio Community 2017 Version 15.8.1

**Comment by jasonleenaylor** [comment]
I suspect that ASP.Net Core is using ECMAScript compliant matching options on the attribute with no way for a developer to override that.

**Comment by javiercn** [comment]
@jasonleenaylor thanks for contacting us.

I believe this is the behavior in System.ComponentModel.DataAnnotations which we don't alter. I suggest you file an issue in the [dotnet/corefx](https://github.com/dotnet/corefx) repo to follow up with them and see if there is a solution.
