### ISSUE TITLE
OnAfterRenderAsync Component method  is not called when it is used on AspNetCore  Razor Page

### ISSUE THREAD

**Issue by ricardoromaobr** [aspnet/AspNetCore#16900]
### Describe the bug
I create a simple component on RCL to be reuseable, but when I use the component on Razor Page 
application the OnAfterRenderAsync or OnAfterRender is called.

### To Reproduce

Just create an component on RCL and and create an Razor Page application and use that component on any Page. And put a break point on the override method and you will see that the 
method is not called.

But if I create Blazor Application and use the same camponent on that project the method will be called. Here is the code: 

RCL componente:

Label.razor: 
```razor
@inject  IJSRuntime  JSRuntime
<h3>Label</h3>

@code {

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
           await JSRuntime.InvokeVoidAsync("exampleJsFunctions.writeToConsole", "Teste afterRender");
        }
    }
}

```
In the Razor Page application: 
Index.cshtml:
```cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<component type="typeof(Label)" 
           render-mode="ServerPrerendered" />


```

On Blazor component the method is called
Index.razor: 
```razor
@page "/"

<h1>Template inicial</h1>

Teste de componente em outro projeto.

<Label/>
```

Got Exceptions? Include both the message and the stack trace
--> No exception, just the method is not called.

### Further technical details
- ASP.NET Core 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@ricardoromaobr thanks for contacting us.

The current behavior is by design. OnAfterRender only gets called when the Browser notifies the server that it has rendered the app. With static rendering (razor pages) that never happens, so the method never gets called.
