### ISSUE TITLE
Unable to increase concurrent requests in ASP.NET Core

### ISSUE THREAD

**Issue by mklvcm** [aspnet/AspNetCore#16909]
I have a file upload method in ASP.NET Core 2.2, based on HttpSys self-hosted. I have a load-testing utility that starts 10 concurrent connections and uploads big files. It works fine on my workstation (24 CPU cores) - all 10 requests are executed in parallel.

When I put it on a small VM (2 cores, Win Server 2012R2) it queues 10 request and then executes them 2 at a time.

My question: how to increase the number of requests being processed concurrently?

I tried `ThreadPool.SetMinThreads(10, 10)` but it makes no difference.

This is my code (simplified):

	[HttpPut]
	public async Task<ActionResult> Put(string partition, string guid)
	{
		var path = GetPath(partition, guid);

		if (System.IO.File.Exists(path)) 
			return Status(409, "File already exists");

		using (var file = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.Read, 4096, true))
		{
			await Request.Body.CopyToAsync(file);
			return Status(200, "");
		}
	}

**Comment by benaadams** [comment]
Is your load tester a .NET Framework app? You may need to increase the `ServicePointManager.DefaultConnectionLimit`

https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit

> The default connection limit is 10 for ASP.NET hosted applications and 2 for all others.

**Comment by Tratcher** [comment]
The server doesn't have a parallelism limit. What client are you using and how?

**Comment by Tratcher** [comment]
> it queues 10 request

Where do you see this queue?

**Comment by benaadams** [comment]
Note the .NET Framework `ServicePointManager.DefaultConnectionLimit` is for **outbound** connections to a single server, which is why I suggested looking at the load-tester settings; not sure if/how its used in .NET Core.

ASP.NET Core should be happy with as many inbound connections as you give it. (Though you can use the [ConcurrencyLimiter middleware](https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/ConcurrencyLimiter) if you do want to throttle it)

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
