### ISSUE TITLE
How can I remove a child component dynamically

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#16918]
I'm adapting the [TabSet sample by Steve Anderson](https://gist.github.com/SteveSandersonMS/f10a552e1761ff759b1631d81a4428c3)  to display a collection of child components ( Tab objects that display a small window with some content, and a click button to remove the clicked window Tab). I've made some changes to the app sample by the maestro and this works great, but alas, I'm not able to devise a way to remove a clicked Tab. 
Could you please suggest a way to achieve this

Thank you...

**Comment by mrpmorris** [comment]
Sounds like your trans are data driven, in which case you'd remove the item from the data and then you won't render a tab for it.

If they are hard coded, then you'd need a boolean starting whether you should render it or not, and then wrap it with `@if`

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
