### ISSUE TITLE
How to setup integration tests so that RabbitMQ service is discover-able? 

### ISSUE THREAD

**Issue by nxtx** [aspnet/AspNetCore#16913]
I have a very basic API test, defined as it follows. 

```csharp
public class WebAPITest : IClassFixture<WebApplicationFactory<Program>>
{
    private readonly WebApplicationFactory<Program> _factory;

    public WebAPITest(WebApplicationFactory<Program> factory)
    {
        _factory = factory;
    }

    [Fact]
    public async Task IfConsumerReceives()
    {
        var client = _factory.CreateClient();
        var response = await client.GetAsync("/api/requestitems");

        // assert
        response.EnsureSuccessStatusCode();
    }
}
```

The application has a RabbitMQ service, defined as it follows in the `Startup` class: 

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddMvc(options => options.EnableEndpointRouting = false)
        .SetCompatibilityVersion(CompatibilityVersion.Version_3_0);

    RegisterEventBus(services);
    services.AddOptions();
}

private void RegisterEventBus(IServiceCollection services)
{
    services.AddSingleton<IRabbitMQPersistentConnection>(sp =>
    {
        var factory = new ConnectionFactory()
        {
            HostName = Configuration["RabbitMQConnection:HostName"],
            Port = Configuration.GetValue<int>("RabbitMQConnection:Port"),
            DispatchConsumersAsync = true
        };

        factory.UserName = Configuration["RabbitMQConnection:UserName"];
        factory.Password = Configuration["RabbitMQConnection:Password"];
        var retryCount = int.Parse(Configuration["RabbitMQConnection:RetryCount"]);
        return new DefaultRabbitMQPersistentConnection(factory, logger, retryCount);
    });

    var queueName = Configuration["QueueName"];
    services.AddSingleton<IEventBus, EventBusRabbitMQ>(sp =>
    {
        var rabbitMQPersistentConnection = sp.GetRequiredService<IRabbitMQPersistentConnection>();
        var iLifetimeScope = sp.GetRequiredService<ILifetimeScope>();
        var logger = sp.GetRequiredService<ILogger<EventBusRabbitMQ>>();
        var eventBusSubcriptionsManager = sp.GetRequiredService<IEventBusSubscriptionsManager>();

        var retryCount = int.Parse(Configuration["RabbitMQConnection:RetryCount"]);

        return new EventBusRabbitMQ(rabbitMQPersistentConnection, logger, iLifetimeScope, eventBusSubcriptionsManager, queueName, retryCount);
    });

    services.AddSingleton<IEventBusSubscriptionsManager, InMemoryEventBusSubscriptionsManager>();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseHttpsRedirection();
    app.UseMvc();
    ConfigureEventBus(app);
}

private void ConfigureEventBus(IApplicationBuilder app)
{
    // The following fails to establish connection to RabbitMQ when running integration tests.
    var eventBus = app.ApplicationServices.GetRequiredService<IEventBus>();
    eventBus.Subscribe<CollectionCompletedIntegrationEvent, CollectionCompletedIntegrationEventHandler>();
}
```

Whole application is dockerized, i.e., I have a `docker-compose` that starts the services (including `RabbitMQ`).

When I debug the application (via hitting the `docker-compose` button on the VisualStudio 2019), it can connect and communicate with the `RabbitMQ` service. However, when I run the integration test, it fails establishing connection to RabbitMQ (see marked line above). 

I am very new to the dockerized tests world, so I am not sure what I am missing.

**Comment by javiercn** [comment]
@nxtx thanks for contacting us.

Integration tests run completely in memory, and don't open ports or anything similar. If you want to test that type of behavior, a full E2E test where you launch all the services is more appropriate.

If you want to write integration tests with WAF for this scenario, I would suggest you mock the pieces regarding RabbitMQ so that you can simply provide a replacement for test that simulates the expected behavior.

**Comment by nxtx** [comment]
I am under the impression that integration tests (unlike functional and unit tests) are supposed to use the actual services; hence, I would like to use the RabbitMQ service rather than a mock object.

**Comment by nxtx** [comment]
@javiercn any suggestions?

**Comment by javiercn** [comment]
@nxtx Integration tests are supposed to test the code in your app, not necessarily external dependencies. For example, in many cases you swap the database or the auth as those are external dependencies.

If you want to test the system whole, you write an E2E test, which is slightly different than an integration test, in the sense that in that case you test all elements of the system as a whole.

Now, that said, you can have integration tests that use external services if that's feasible for you, but in cases like using a message bus like RabbitMQ it might be hard or impossible to write a test using the real bus and other services.

In that scenario, I would suggest replacing your bus abstraction with a test one, and setting it up to receive and send the messages you expect for each scenario from the main unit that you are testing. That way you achieve two things, you validate that the unit you are testing works the way you defined and you set expectation about what the communications with other systems look like.

**Comment by nxtx** [comment]
@javiercn Thanks for the suggestion. Obviously I am not familiar with E2E tests for such scenarios. I did some research but came across blogs such as [this one](https://docs.microsoft.com/en-us/archive/msdn-magazine/2015/may/modern-apps-end-to-end-testing-in-modern-web-sites-and-apps), which unfortunately does not provide me with clues on how to implement E2E test. For instance, I am not sure if, e.g., similar to XUnit for unit tests, there is any framework features for E2E tests; should I write a bash script to start the project and run a bash-based test?!

**Comment by javiercn** [comment]
@nxtx You can start your app with Process.Start, that's what we do in our own E2E tests. This is not a super thoroughly explored area, but having an xUnit fixture or similar start and tear down the process(es) works well here.

**Comment by nxtx** [comment]
@javiercn Thank you.
