### ISSUE TITLE
IdentityServerJwt is not supported error

### ISSUE THREAD

**Issue by wsimf** [aspnet/AspNetCore#16916]
When I try to use the application profile 'IdentityServerJwt', the app exits on startup complaining that the application profile 'IdentityServerJwt' is not supported. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#application-profiles)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by javiercn** [comment]
@wsimf thanks for contacting us. 

Can you provide more details about your environment so that we can help you troubleshoot this? Ideally a minimal repro project that illustrates the issue you are having.

**Comment by javiercn** [comment]
We're closing this issue as we haven't seen community involvement and we need more information to reproduce the problem. If you have more details about the issue add a reply here with the new information and we'll re-evaluate the issue.
