### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by bobbytreed** [aspnet/AspNetCore#16917]
Building an Azure Function v3 with .netcoreapp3.0 causes an error in microsoft.net.sdk.functions\1.0.30-beta2\build\Microsoft.NET.Sdk.Functions.Build.targets(41,5)

**Comment by javiercn** [comment]
@bobbytreed thanks for contacting us.

@bradygaster @danroth27 @anurse Do you know what folks to loop into this?

**Comment by paulbatum** [comment]
Its a functions tooling issue tracked here:
https://github.com/Azure/azure-functions-core-tools/issues/1642

**Comment by javiercn** [comment]
Thanks @paulbatum. I will be closing this issue since it is already being tracked there.
