### ISSUE TITLE
void controller method returns status 200 instead of 204

### ISSUE THREAD

**Issue by syndicatedshannon** [aspnet/AspNetCore#16925]
In ASP.NET Core 3.0, Controller methods with a void return produce an HTTP status code 200. That is probably imprecise, and may also be a defect or undocumented breaking change if different than prior versions.

@cremor [stated on a related thread](https://github.com/aspnet/AspNetCore/issues/8847#issuecomment-551403850) that this is a change from prior versions of ASP.NET.

[RFC 2616 on Status Code Definitions](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) does not specify that 204 *must* be used for empty bodies. However, it does make clear that 204 *most specifically* designates the status of a response where the body does not represent an entity. That's almost certainly the best interpretation of a void response. It states by example that a 200 response includes an entity/body.

Other guidance, such as [MDN documents](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) on [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) and [204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204), are more explicit, and also state the inverse in [some places](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE); that without a body a 204 is then appropriate:

> A 204 (No Content) status code if the action has been enacted and no further information is to be supplied.
> A 200 (OK) status code if the action has been enacted and the response message includes a representation describing the status.

[RFC 7231 on HTTP/1.1](https://tools.ietf.org/html/rfc7231#section-6.3.1) is perhaps most relevant. It states (note "ought", rather than "must", but also "always"):
> 6.3.1.  200 OK
>    Aside from responses to CONNECT, a 200 response always has a payload,
>    though an origin server MAY generate a payload body of zero length.
>    If no payload is desired, an origin server ought to send 204 (No
>    Content) instead.

**Comment by javiercn** [comment]
@syndicatedshannon thanks for contacting us.

I don't think this is different from previous versions of ASP.NET Core, but I'm happy to be corrected. The default behavior in ASP.NET Core (and many other servers) is to return 200 by default, which is what a void returning action does.

Unless we get a report that indicates that this was a change between a previous version and the current one, we are likely not going to change this behavior, as doing so would break many applications.

There are easy alternatives to this, like simply returning an action result from your action to obtain the exact behavior you want.

I'm closing this issue as we don't plan to change the current behavior. If you can provide an example that shows that this was indeed a behavior change between 3.0 and a previous version, we will re-evaluate this issue.

I hope you understand that we value not breaking other developers existing apps over the correctness of a specific choice, specially when there are alternatives and the impact is reduced.

**Comment by syndicatedshannon** [comment]
@javiercn Our API surface returns `T`, not `IHttpActionResult<T>`, as in our opinion this supported usage clarifies the surface and dependents (including tests). What alternative would you recommend in this case?

**Comment by syndicatedshannon** [comment]
@cremor Can you comment? I see the [Microsoft documentation](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/action-results) that you referenced:

Return type | How Web API creates the response
-- | --
void | Return empty 204 (No Content)

However, I do not know offhand about your mention prior versions. Do you have easy access to this?

**Comment by syndicatedshannon** [comment]
@javiercn I disagree with the close based solely upon a breaking change. I believe following RFC standards is sufficiently important to fix the issue in *addition* to preventing breaking changes, even if an options flag is required. Does that make sense?

**Comment by javiercn** [comment]
> Separately, I do understand your recommend to close based on alternatives/workarounds. Would you please take a moment to refer me to a workaround when not returning `IHttpActionResult`?

@syndicatedshannon I believe you could tweak things here with a global filter. That gives you control over the final result.

**Comment by syndicatedshannon** [comment]
> I believe you could tweak things here with a global filter. 

@javiercn I did find that option; I commented on a similar [stackoverflow answer](https://stackoverflow.com/a/50327800/608220) yesterday. Note the answer mentions cons of that approach.

I'm still willing to do it, but do you think perhaps supporting this RFC guidance I mentioned in the issue report deserves built-in functionality, without custom filter implementation/insertion?

**Comment by cremor** [comment]
> @cremor Can you comment? I see the [Microsoft documentation](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/action-results) that you referenced:

Note that the linked documentation is for ASP.NET Web API 2 (that is the version of ASP.NET on the full .NET Framework, which was released before .NET Core was a thing). @javiercn said that no older version of ASP.NET **Core** ever returned 204 for `void`. I haven't checked if this is true, but I'll believe him.

So the breaking change is between ASP.NET (from the full framework) and ASP.NET Core. That's no problem because those are completely different frameworks with many breaking changes.

While I agree that void/Task returning action methods should optimally return a 204, I also see the reasoning that introducing a breaking change in ASP.NET Core for a change that is not really required is not something Microsoft wants to do.

**Comment by syndicatedshannon** [comment]
@cremor Thanks for the feedback. I'll wait to hear if @javiercn replies to the value of addressing this (which IMO is required for providing core support for RFC). If no reply, I'll open a separate feature request, clarifying that I'm not requesting the default functionality changed (breaking changes). Personally, I do believe this is a defect, but I appreciate the plausibility of addressing may be clearer when presenting as a feature.
