### ISSUE TITLE
Running dotnet-watch on a new project based on SPA template causes corrupt node_modules directory

### ISSUE THREAD

**Issue by nphmuller** [aspnet/AspNetCore#16923]
It seems `dotnet watch` corrupts the `node_modules` folder when ran on a freshly created project based on a SPA template. `dotnet watch` aborts abruptly because it observes too many changed files, which probably causes the current `npm install` command to be aborted abruptly. This in turn causes a corrupt `node_modules` folder, making many `npm` commands fail:
- `npm start`: `'rimraf' is not recognized as an internal or external command`
- `npm run build`: `'react-scripts' is not recognized as an internal or external command`
- etc.

Repro:
```
dotnet new react
dotnet watch run
```

A possible solution would be to make the SPA templates add a `dotnet watch` opt-out for the `ClientApp` folder in the csproj file.

### Further technical details
```
>dotnet  --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
@nphmuller thanks for contacting us.

You can decide what files to watch. See https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/dotnet-watch.md#customize-files-list-to-watch and add the appropriate element to your csproj file

**Comment by nphmuller** [comment]
Hi @javiercn 
Thanks for the quick response, but shouldn't the default behaviour for the SPA templates be changed to be compatible with dotnet watch?

**Comment by javiercn** [comment]
@nphmuller This is the first time we receive such request. In general we can't make sure that every possible combination works with everything out of the box. We need to balance having a readable project file with one that includes all the knobs for all the features that a user might choose to use. 

What I'm trying to say with this is that in general, templates are a starting point and trade simplicity for functionality.

Hope that makes sense.

**Comment by nphmuller** [comment]
Makes sense, thanks!
