### ISSUE TITLE
Analyzer processing of generated code causes significant slowdown in build

### ISSUE THREAD

**Issue by roji** [aspnet/AspNetCore#16922]
After investigating the slow build times of an EF Core sample project (https://github.com/aspnet/EntityFrameworkCore/issues/18618), it turned out the slowdown is coming from the ASP.NET analyzers. EF Core migrations are generated code which particularly affect analysis time - as a general rule it seems that analyzers should opt out of generated code analysis (via [ConfigureGeneratedCodeAnalysis](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.analysiscontext.configuregeneratedcodeanalysis?view=roslyn-dotnet#Microsoft_CodeAnalysis_Diagnostics_AnalysisContext_ConfigureGeneratedCodeAnalysis_Microsoft_CodeAnalysis_Diagnostics_GeneratedCodeAnalysisFlags_)) unless they have a good reason.

To repro, clone https://github.com/roji/AnalyzerBuildPerf. On my machine, building this project with `Microsoft.NET.Sdk` takes about 6s, while building it with `Microsoft.NET.Sdk.Web` takes about 16s. While this repro project is somewhat heavy, it does seem realistic, and various other generated code scenarios may be even much, much worse.

Analyzer packages being brought in by `Microsoft.NET.Sdk.Web` are Microsoft.AspNetCore.Analyzers, Microsoft.AspNetCore.Mvc.Analyzers and Microsoft.AspNetCore.Components.Analyzers.

Area | Analyzer  | Status
-- | -- | --
Analyzers (top-level) | All |  Opts out of generated code analysis
MVC | AttributesShouldNotBeAppliedToPageModelAnalyzer | Opts out of generated code analysis
MVC | AvoidHtmlPartialAnalyzer (extends ViewFeatureAnalyzerBase) | **Does not contain any setting**
MVC | TagHelpersInCodeBlocksAnalyzer | *Explicitly opts into generated code analysis*
MVC | TopLevelParameterNameAnalyzer | Opts out of generated code analysis
Components | ComponentParameterAnalyzer | **Does not contain any setting**
Components | ComponentParameterUsageAnalyzer | *Explicitly opts into generated code analysis*
Components | ComponentInternalUsageDiagnosticAnalyzer (uses InternalUsageAnalyzer) | **Does not contain any setting**

Note that generated code analysis is on by default. Seems like a pass should be done and at least some (if not all?) of these should opt out (although am not aware of the status of code-generated Razor code and what you want to analyze there).

**Comment by Pilchie** [comment]
Thanks for the analysis @roji.  I know for some of these, the need to analyze the C# parts of razor code means they *do* need to analyze generated code, but you're right that at least the ones with no setting should be reviewed.

**Comment by rynowak** [comment]
All of the bolded ones **specifically** target Razor. 

There's a way to get a [breakdown of individual analyzer times as well](https://m0sa.net/posts/2019-08-roslyn-analyzer-runtime-performance/). I'm sure we can figure out a way to optimize this more.

**Comment by rynowak** [comment]
How it be and what it do:
![image](https://user-images.githubusercontent.com/1430011/68493514-7175f480-0201-11ea-9bfa-472285035e28.png)

**Comment by roji** [comment]
Ideally Roslyn would support a finer-grained "tag" that would allow analyzers to process Razor files but not EF migrations, or vice versa. Just a blanket "is it code-generated" seems like it may not be enough.

**Comment by roji** [comment]
Cool, @rynowak I wish I knew about that analyzer breakdown option when I started looking at this :)

Note the recommendation in https://github.com/aspnet/EntityFrameworkCore/issues/18618#issuecomment-547043966, to move away from SyntaxNode/GetSymbolInfo to an IOperation-based analyzer. Could help if you really need those analyzers to run.

**Comment by rynowak** [comment]
Yup. Agreed.

Profiles confirm that what's expensive here is doing syntax-driven analysis but then asking for symbols. Both of these were written pre-operations I think - the component one is a clone of the EF internal usage analyzer but with generated code analysis on. Compare with [this](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Analyzers/src/ComponentParameterUsageAnalyzer.cs) which runs on generated code and uses operations to do a pretty similar task to `ComponentInternalUsageDiagnosticAnalyzer`,

![image](https://user-images.githubusercontent.com/1430011/68494569-818ed380-0203-11ea-8405-08b2dc6fbcf8.png)

**Comment by roji** [comment]
Oh, nice. We already have https://github.com/aspnet/EntityFrameworkCore/issues/18637 tracking rewriting our own analyzer with operations, but it's much less urgent since it simply skips generated code. If you do it on your side I'll be happy to copy-paste though :)

**Comment by roji** [comment]
FYI opened https://github.com/dotnet/roslyn/issues/39758 for Roslyn support selective generated code analysis.

**Comment by rynowak** [comment]
Here's an update with the results of https://github.com/aspnet/AspNetCore/pull/17001

![image](https://user-images.githubusercontent.com/1430011/68725827-737ae300-0574-11ea-9dda-f9b573ac9a79.png)

I'm still not super thrilled with that, and digging deeper.

**Comment by rynowak** [comment]
@mavasani - any advice on a non-allocating way to get the containing namespace of a symbol and compare to a known value?

![image](https://user-images.githubusercontent.com/1430011/68726963-edf93200-0577-11ea-96e9-07dfbc9b184b.png)

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Analyzers/src/ComponentInternalUsageDiagnosticAnalzyer.cs#L35

I guess I could start with `.RenderTree` and then walk up.

**Comment by mavasani** [comment]
You shouldn't compare symbols by their fully qualified names or display strings. Your approach of comparing each namespace name and walking up the containing namespace chain seems correct.

**Comment by roji** [comment]
@rynowak it might be good to also implement [@mavasani's suggestion](https://github.com/dotnet/roslyn/issues/39758#issuecomment-553155652) to programmatically ignore generated code unless it's Razor (the question would be how to identify them - extension?). This would cut out all the EF migrations.
