### ISSUE TITLE
How to Asp.net Core 3.0 User Identity can reproduce

### ISSUE THREAD

**Issue by borahanarslan** [aspnet/AspNetCore#16926]
How to reproduce user manager without using dependency injection Asp.net Core User İdentity. Gives error when generated as follows

`public UserManager<ApplicationUser> _userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new DatabaseContext()),null,null, null, null, null, null, null, null);
`
![Hata](https://user-images.githubusercontent.com/14363652/68486483-33ed8780-0252-11ea-8477-01b2fe62a012.png)

but, No problem when I reproduce Identity Role
`public RoleManager<IdentityRole> _roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new DatabaseContext()), null, null, null, null);
`
![rol](https://user-images.githubusercontent.com/14363652/68486545-54b5dd00-0252-11ea-8eb7-d6795210f7f1.png)

How should I proceed? I couldn't find the sample code.Thanks for reply
Thank you in advance to everyone who replies

**Comment by blowdart** [comment]
You would new up all the other classes required, rather than pass in null. You're heading deep into unsupported territory, and really you'll need to look through the [source code](https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/Core/src/AspNetRoleManager.cs) to see what is needed.

**Comment by borahanarslan** [comment]
> You would new up all the other classes required, rather than pass in null. You're heading deep into unsupported territory, and really you'll need to look through the [source code](https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/Core/src/AspNetRoleManager.cs) to see what is needed.

Hello blowdart,
I solved the problem, thank you for your comment
`  static IUserStore<ApplicationUser> _store = new UserStore<ApplicationUser>(new DatabaseContext());
       static UserManager<ApplicationUser> _userManager = new UserManager<ApplicationUser>(_store, null, new PasswordHasher<ApplicationUser>(), null, null, null, null, null, null);`

**Comment by borahanarslan** [comment]
I solved the problem, thank you for your comment
static IUserStore<ApplicationUser> _store = new UserStore<ApplicationUser>(new DatabaseContext()); static UserManager<ApplicationUser> _userManager = new UserManager<ApplicationUser>(_store, null, new PasswordHasher<ApplicationUser>(), null, null, null, null, null, null);
