### ISSUE TITLE
OIDC Authentication, using absolute redirect (callback) uri or changing request scheme

### ISSUE THREAD

**Issue by HoundThe** [aspnet/AspNetCore#16924]
Hi, I am trying to use Authentication.OpenIdConnect lib to authenticate with oidc protocol in my webapplication, the application runs in http, because the https, ssl part is handled by the provider that is the middle man between my server and users. But, when I do have my server running in http, the redirect url that is used in the requests starts with http and not https, so I cannot use it.

Example
```cs
 services..AddOpenIdConnect(o =>
                {
                    o.ClientId =  ...;
                    o.ClientSecret = ...;
                    o.CallbackPath = "/signin-oidc"; // <-- this, this gets appended to http + :// + host (if I run it on http)
                    // resulting in **http://myweb.com/signin-oidc** but I want **https://myweb.com/signin-oidc**
                    o.CorrelationCookie.IsEssential = true;
                    o.GetClaimsFromUserInfoEndpoint = true;
                })
```

If I try to set CallbackPath as absolute path, it doesn't let me resulting in:

```
System.ArgumentException: The path in 'value' must start with '/'.
```
Maybe there is an option to do that? But I can't find it yet. If there is already one, please point me to it. Otherwise I would like an option to set absolute value of the redirect url or set the request scheme.

If there isn't such option I can try to implement it and send PR, in that case any directions to what everything has to be changed would be awesome!

So far I found:

In the handler:

```cs
 RedirectUri = BuildRedirectUri(Options.CallbackPath),
```
Where  BuildRedirectUri looks like:
```cs
protected string BuildRedirectUri(string targetPath)
            => Request.Scheme + "://" + Request.Host + OriginalPathBase + targetPath;
```

Thanks!

**Comment by Tratcher** [comment]
It's better to handle https termination concerns centrally in the app than to try to customize individual components. Please read https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.0.

**Comment by RheaAyase** [comment]
Kind of going off of some other things - wouldn't it still be best to support both types of value here? I mean, io.file supports relative and absolute path for example. Speaking of path - I think that this has a Path type mixed in? Seems like that could also be an issue.

**Comment by Tratcher** [comment]
Having absolute uri's scattered throughout your application makes it very brittle. E.g. you need different values in development and production, and would have to change it in several places. It's better to configure things like the host, port, scheme, and path base centrally so the app components only needs to worry about paths and queries.

**Comment by HoundThe** [comment]
Thanks for the docs! Somehow I couldn't find that.
