### ISSUE TITLE
Microsoft.AspNetCore.ApiAuthorization.IdentityServer is unable to take custom Client configuration

### ISSUE THREAD

**Issue by superman-lopez** [aspnet/AspNetCore#16939]
### Describe the bug
In `Microsoft.AspNetCore.ApiAuthorization.IdentityServer` there is the ability to configure IdentityServer clients by using the `AddApiAuthorization` configuration method.  This method has a configuration called `Add` which takes a `IdentityServer4.Models.Client` object.  During runtime there is an error from IdentityServer which states 

> Can't determine the type for the client 'authAngular'

I suspect this type is one of the Application Profiles (https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#application-profiles), however the _Add_ method does not seem to have the ability to take any other parameters than the Client object, and the Type is not a property of that object.

### To Reproduce
Create an authAngular template (or similar) with 
`dotnet new angular -o <output_directory_name> -au Individual`
Change configuration in Startup.cs and remove the configuration from `appsettings.json`
```
services.AddIdentityServer()
	.AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options => 
		options.Clients.Add(new IdentityServer4.Models.Client() {
			ClientId = "authAngular",
			ClientName = "authAngular",
			AccessTokenType = AccessTokenType.Jwt,
			RequireClientSecret = false,
			AllowedGrantTypes = GrantTypes.Code,
			AllowAccessTokensViaBrowser = true,
			AllowedScopes = { "AppAPI", "openid", "profile", "roles" },
			RedirectUris = {"https://localhost:5001/authentication/login-callback"},
			PostLogoutRedirectUris = {"https://localhost:5001/authentication/logout-callback"}}));
```
Attempt to retrieve client configuration from `http://localhost:5000/_configuration/authAngular`

**Comment by javiercn** [comment]
@superman-lopez thanks for contacting us.

That's by design. Our extensions only work on clients defined through our API as we don't support the full scope of options provided by Identity Server. 

If you want to support retrieving the client configuration directly you can add that to the scaffolded controller in the template.

Hope that helps.
