### ISSUE TITLE
multiple scheme support of authentication

### ISSUE THREAD

**Issue by saravanakj** [aspnet/AspNetCore#16946]
Hi,

.Net Core 2.2

We would like to authenticate request carrying token with either of the multiple schemes supported (Bearer, Id, Token). Also, we don't want to add schemes in Authorize decorator.

Configure authentication in Startup.cs.
- Bearer
- Id
- Token

**In ConfigureServices,**
services
.AddAuthentication("Bearer") //fallback default scheme
.AddIdentityServerAuthentication("Bearer", jwtOptions => { 
  var scopedTokenValidationParameters = services.BuildServiceProvider().GetService<ScopedTokenValidationParameters>();

   // to validate based on the requested tenant (having tenant's issue signing key)
   jwtOptions.TokenValidationParameters = ScopedTokenValidationParameters;
})
.AddScheme<CustomJwtOptions, CustomJwtHandler>("Id", opts => {})
.AddScheme<CustomTokenOptions, CustomTokenHandler>("Token", opts => {})

**In Configure,**
app.UseAuthentication();

On any request, only the default scheme is getting invoked, the other registered scheme (Id, Token) handler was not invoked based on the request's authorization scheme.

Are we missing anything? Would like to get help here.

Thanks.

**Comment by javiercn** [comment]
@saravanakj thanks for contacting us.

I think you are looking for Policy Schemes. See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/policyschemes?view=aspnetcore-3.0 and see if that helps you.

@Tratcher or @HaoK can confirm here.

**Comment by saravanakj** [comment]
@javiercn thank you for recommending. 

would like to wet with you the below snippet. Have overridden the GetDefaultAuthenticateSchemeAsync. AuthenticationSchemeProvider has been DI in singleton scope and used IHttpContextAccessor to retrieve the current request. Kindly let's know your review points as well. 

Let me try applying the ForwardAuthenticate using options.ForwardDefaultSchemeSelector, this seems to be called from any of the default scheme options. Say, have registered with two schemes Bearer (JwtBearerHandler)(defaultScheme) and Token (CustomJwtHandler), then have to add options.ForwardDefaultSelector with the logic below in Bearer (since its default). Kindly correct our understanding.

Thanks.

```
// class CustomAuthenticationSchemeProvider: AuthenticationSchemeProvider
/// <summary>
        /// Retrieves the scheme on per-request basis
        /// </summary>
        /// <returns></returns>
        public override Task<AuthenticationScheme> GetDefaultAuthenticateSchemeAsync()
        {
            try
            {
                var ctxt = _httpContextAccessor.HttpContext;

                var authHeader = ctxt.Request.Headers[HeaderNames.Authorization];
                var incomingScheme = authHeader.FirstOrDefault().Split(' ').FirstOrDefault();

                return GetSchemeAsync(incomingScheme);
            }
            catch (Exception ex)
            {
                _logger.LogError($"@@@@ GetDefaultAuthenticateSchemeAsync Error: {ex}");
                return base.GetDefaultAuthenticateSchemeAsync();
            }
        }
```

Thanks.

**Comment by Tratcher** [comment]
You can do this with Authorization policies, even modifying the default policy to add multiple authentication schemes.
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.0#use-multiple-authentication-schemes

**Comment by saravanakj** [comment]
Thanks, @Tratcher. shall try with the default policy.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
