### ISSUE TITLE
Blazor fire onchange event when Chosen drop down value changes

### ISSUE THREAD

**Issue by abdulqayyum** [aspnet/AspNetCore#16942]
I have following html in razor component that works but when I render drop down with Chosen it stops working. because chosen do not update actual drop down value it creates its own element that holds selected value. but i can not access that so how to trigger the onchange event then?

```
<select id="search" single class="chosen-select" @onchange="UpdateValue" bind="@searchValue">
        ...
</select>
...In @Code
void UpdateValue(ChangeEventArgs e)
{
    searchValue = e.Value.ToString();
    ... 
}
```
Now if I initialize drop down with chosen then I can not detect on change but can other wise. I am using Blazor GL - Server Side with .net core 3.0.1

I do not know what is the fast method reporting here or asking stackoverflow so I did asked here too
https://stackoverflow.com/questions/58777642/blazor-fire-onchange-event-when-chosen-drop-down-value-changes

**Comment by javiercn** [comment]
@abdulqayyum thanks for contacting us.

In principle, if you are using `@bind` you don't need to use `@onchange`.

I'm not sure based on your description what you are trying to achieve. If you give us a minimal repro project ilustrating your problem then we might be able to help you.

**Comment by nguyenvanbien95** [comment]
Hi, i answered your question in StackOverflow for temporary fix [Here](https://stackoverflow.com/a/58795843/6708387).
I am waitting for offical support.

**Comment by mkArtakMSFT** [comment]
We tried this out and there's a compiler error in this case already showing up. And the scenario is not supported.
