### ISSUE TITLE
Configuration flag to produce 204 from void return

### ISSUE THREAD

**Issue by syndicatedshannon** [aspnet/AspNetCore#16944]
In ASP.NET Core, Controller methods with a void or Task return type produce an HTTP status code 200. IETF recommends instead returning 204 to indicate no payload (while 200 includes payload). No out-of-box ASP.NET Core configuration is available to act according to this guidance. This is a change from ASP.NET, though unchanged in ASP.NET Core.

The workarounds include, writing boilerplate global filter code, or using `ActionResult<T>` instead of `T`. One could argue the latter requires no code, but it instead defeats a supported pattern.

**Comment by syndicatedshannon** [comment]
See also https://tools.ietf.org/html/rfc7231#section-6.3.1

**Comment by syndicatedshannon** [comment]
Note this is very similar to another issue I opened, https://github.com/aspnet/AspNetCore/issues/16925, which was closed for two reasons:
 - breaking change
 - alternatives available

I opened this as a feature to clarify I did not mean to request a breaking change. Regarding the alternative, I believe @javiercn may have overlooked those of us who return T from our controller methods.

I apologize if that's incorrect.

**Comment by javiercn** [comment]
Thanks for contacting us @syndicatedshannon.

We've discussed this within the team and we believe that returning 200 is not incorrect and we aren't likely to add a knob to support returning 204 in these situations. When we build the framework in many cases we have to trade-off simplicity with offering all the possible configurations out of the box, and this is one of such cases.

We believe there is enough extensibility to implement this on top of the current primitives and that the approach proposed in the mentioned issue is what we expect customers to do in these situations.

We know this might not be the answer you would expect, but we need to trade-off other concerns like added complexity, maintainability, testing, etc. and as mentioned, in this case we believe there is enough extensibility to adapt the framework to your needs in a reasonable way.

**Comment by syndicatedshannon** [comment]
Thanks for the follow-up. As you already know, I do disagree on the "correctness" given my read of the specifications, but the impact is low. I also appreciate the respect you showed me by reconsidering my request. Send my best to your team!
