### ISSUE TITLE
Session cookie not being set in Production, but working fine on localhost?

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/AspNetCore#16950]
SDK: ASP.NET **Core 3.0** 
Env: **IISExpress** (**https** _localhost_) and **Azure WebApp** (**https** _www.domain.com_)
Browser: Chrome

I have a WebApp wherein the session cookie gets set fine when running on localhost but does not work at all when running on WebApp in Azure (behind **FrontDoor** with header forwarding enabled, if it matters).

Is this due to a configuration problem or an API bug?  Essentially, with every request to the Azure Web App, a new session ID is generated.  

Here is the sessions setup:
```
 services.AddSession(o => 
            {               
                o.Cookie.Name = ".DivSeshCookie";
                o.Cookie.IsEssential = true;
                o.Cookie.SameSite = SameSiteMode.None;
                o.Cookie.SecurePolicy = Microsoft.AspNetCore.Http.CookieSecurePolicy.SameAsRequest;
                o.IdleTimeout = TimeSpan.FromMinutes(60);
            });
```

When running on localhost, Fiddler shows the session cookie being sent as expected.  When running on Azure, no session cookies are being exchanged, although the Identity and Anti-Forgery cookies seem to be working just fine.

Both localhost and Production use the same IDistributedCache store (Azure Redis).

I've tried modifying the SameSiteMode settings as well as changing and removing the SecurePolicy settings.

Under what circumstances would the session middleware not send the cookie? Or, is the browser ignoring it?  I'm not even sure how to trouble shoot this.

**Comment by Tratcher** [comment]
What do the application logs say?

**Comment by SimonOrdo** [comment]
@Tratcher Didn't see anything in the logs, however, further testing would imply that this is related to caching on Azure FrontDoor (possibly any Reverse Proxy?).  If FrontDoor caching is turned off, everything works as expected.

I'm inclined to close this issue, but first I want to make sure this isn't due to a weird interaction with the AspNet Core Cache-Control headers and that there isn't something I can do to control caching inside AspNet.

Best I can tell, FD is caching the HTML responses based on absolute paths.  

For the most part AspNet seems to be setting _Cache-Control_ headers to "no-cache" for HTML responses, which I thought should prevent caching of the HTML, but according to Mozilla it only instructs the cache to "verify the content before releasing a cached version".  Does "content" in this context include headers like "Set-Cookie" or just the body?   According to the AspNet caching docs, when a cookie is set, the response shouldn't be cached, but if that particular URL was previously cached by the proxy, wouldn't the AspNet Cache-Control headers be be moot?

I wanted to test if cookies could be received with proxy caching enabled if the _Cache-Control_ response was set to "no-store" instead of/in addition to "no-cache".

I tried setting _Cache-Control_ = "no-store" to see if that would make a difference with this code (last item in my `Configure` pipeline setup):

```
 app.Use(async (context, next) =>
            {
                // Maybe? Tell FrontDoor not to cache, unless it's a static file
                if (!context.Request.Path.ToString().Contains(".") || context.Request.IsAjaxRequest())
                {                   
                    context.Response.GetTypedHeaders().CacheControl =
                        new Microsoft.Net.Http.Headers.CacheControlHeaderValue()
                        {
                            NoStore = true,
                            NoCache = true,
                            MaxAge = TimeSpan.Zero
                        };
                }

                await next();
            });
```
... but that didn't seem to have consistent results.  Still getting "Cache-Control: no-cache" headers in the HTTP response.

Here is what my HTTP responses look like, with the above code in place:

Localhost connection:
![image](https://user-images.githubusercontent.com/15930167/68549071-b2186e00-03b9-11ea-9545-bdcc18615439.png)

Subsequent requests exchange session cookie (_.DivSeshCookie_) as expected.

Direct connection to Azure WebApp (bypassing FrontDoor proxy):
![image](https://user-images.githubusercontent.com/15930167/68549570-17bb2900-03bf-11ea-89ae-07a6e6641390.png)

Session cookies work as expected.

Connect through FrontDoor proxy with **Caching DISABLED**:
![image](https://user-images.githubusercontent.com/15930167/68549579-37525180-03bf-11ea-99ce-6afe3076f142.png)

Session cookies work as expected.

Connect through FrontDoor proxy with **Caching ENABLED**:
![image](https://user-images.githubusercontent.com/15930167/68549658-57cedb80-03c0-11ea-87d7-d00907ad6fcb.png)

No session cookie received. Login cookie seems to come trough.

Thoughts?

**Comment by Tratcher** [comment]
> According to the AspNet caching docs

Those are for the optional caching middleware in your application. Azure Front Door likely has different behavior.

**Comment by Tratcher** [comment]
Why do you get an auth cookie set on every response?

**Comment by SimonOrdo** [comment]
> > According to the AspNet caching docs
> 
> Those are for the optional caching middleware in your application. Azure Front Door likely has different behavior.

Yeah, but I thought there was some implication there that Cache-Control response headers are set based on that.  I probably misread it.

**Comment by SimonOrdo** [comment]
> Why do you get an auth cookie set on every response? That should only happen once at login.

Yeah, sorry.  That was the login reply.  Interesting enough, however, I can't seem to log out once I log in unless I manually delete the cookie fro the browser.  Code:

```
  public async Task<IActionResult> LogOff()
        {            
            await _signInManager.SignOutAsync();
            HttpContext.Session.Clear();
            Log.Information("User logged out.");
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

```
This is what an Ajax calls returns (which does set a session value):
![image](https://user-images.githubusercontent.com/15930167/68563179-53331300-0412-11ea-95f0-c2211e2351ab.png)

This is what a standard HTTP request looks like:
![image](https://user-images.githubusercontent.com/15930167/68563200-6645e300-0412-11ea-8f94-54ac9e5bb07b.png)

Is there a reliable way (and is it advisable?) that I can set the Cache-Control header?  FrontDoor docs claim that it respects those headers.  It's definitely a proxy caching related problem, but I can't believe I'm the first person that would have run into this issue.  Seems like a fairly common use-case.

**Comment by Tratcher** [comment]
Honestly this is the first report I recall seeing. I expect most complaints would go to Front Door.

Clarification: The cookie auth handler sets all of the no-cache headers due to the sensitive nature of auth cookies, other components that issue cookies do not set no-cache headers. https://github.com/aspnet/AspNetCore/issues/14795#issuecomment-539131375 includes a proposal to update the headers added to include no-store.

**Comment by SimonOrdo** [comment]
@Tratcher Alrighty.  Thanks for looking into it with me.  I don't have high hopes because of how specific of a problem it is, but I'll give it the old college try to get it past the outsourced level 1 mind tree support folks at Azure.  I know they have caching control enhancements planned for Front Door, so maybe once I can tell FD to only cache static content, that will fix it.  

In the meantime, I'll turn caching off and just eat the 2x bandwidth costs.
