### ISSUE TITLE
Razor component catch-all route throws

### ISSUE THREAD

**Issue by MV10** [aspnet/AspNetCore#16953]
Running on 3.0.0.100, I've created a razor component (.razor file) with a route using a catch-all template (the same happens with a single-asterisk catch-all):

```razor
@page "/foo/{**data}"
```

An exception is thrown at runtime:

> System.InvalidOperationException:
> Invalid template 'foo/{\*\*data}'. The character '\*' in parameter segment '{**data}' is not allowed.

Nothing in the [routing docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#routing) for RC's mentions catch-all parameters being unsupported, only optional parameters.

**Comment by javiercn** [comment]
@MV10 thanks for contacting us.

Razor components don't support that type of catch-all routes. I believe you can still use `"/foo?{*data}"`.
