### ISSUE TITLE
Error installing Microsoft .Net Core 2.2.7 Windows Server Hosting

### ISSUE THREAD

**Issue by whizkidwwe1217** [aspnet/AspNetCore#16966]
### Describe the bug

I tried installing Microsoft .NET Core 2.2.7 Windows Server Hosting on Windows Server 2008 R2 (Hyper-V) but an error has ocurred:

![image](https://user-images.githubusercontent.com/1977391/68572561-ab185b00-04a0-11ea-999a-e7ce82017bd6.png)
I also tried ```dotnet --info``` but an error is thrown:
![image](https://user-images.githubusercontent.com/1977391/68572940-9e483700-04a1-11ea-8405-a055ad1614e7.png)

### OS Info
![image](https://user-images.githubusercontent.com/1977391/68572799-4a3d5280-04a1-11ea-95c1-de5766de7dab.png)

### Installation Logs
![image](https://user-images.githubusercontent.com/1977391/68572667-fcc0e580-04a0-11ea-929f-83a8334e0cb1.png)
![image](https://user-images.githubusercontent.com/1977391/68572711-16fac380-04a1-11ea-8c05-01b9f9e612c2.png)
![image](https://user-images.githubusercontent.com/1977391/68572726-211cc200-04a1-11ea-9d0d-bf2d6ab367f4.png)
![image](https://user-images.githubusercontent.com/1977391/68572739-2712a300-04a1-11ea-85a2-cdb30677ede8.png)

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@whizkidwwe1217 thanks for contacting us.

@jkotalik @shirhatti Can you help route this to the appropriate folks?

**Comment by jkotalik** [comment]
@joeloff ? 

@whizkidwwe1217 if you could post the log file with the failure rather than screenshots, that would be useful. My guess is there may be a component that needs to be installed on WinServer 2008 that is available on Win8+.

**Comment by whizkidwwe1217** [comment]
@javiercn @jkotalik Okay I just figured out what's causing the issue. It throws an error when installing the hosting bundle because it needs an internet connection and regarding the other error, "failed to load hostfxr.dll", I need to install KB2533623 Windows Server update.

**Comment by joeloff** [comment]
Yup, there are KBs required for the runtimes on certain OS versions. I'm curious what required the internet connection. The runtime in 1.x used to have a C++ redist dependency that it would download, but that was removed during 2.x development AFAIK

**Comment by joeloff** [comment]
The CABs are definitely signed, so the theory about needing to download the cert to verify the signature would make sense. When the signature is verified it will usually walk the complete chain of issues up to the root authority and any intermediate certificates would need to be downloaded AFAIK. I don't see a good mitigation for this inside environments that are locked down, e.g. internal servers with no outside connection.
