### ISSUE TITLE
Blazor + RCL + AssemblyLoadContext.Unload crashes VS debug

### ISSUE THREAD

**Issue by MV10** [aspnet/AspNetCore#16974]
I have a scenario that causes VS2019 16.3.6 with Core 3.0 to crash with HRESULT 0x80070057 (e_invalidarg) in debug, but the same program runs stand-alone indefinitely without problems. Since this involves Blazor, Razor Components in a Razor Class Library, AssemblyLoadContext, and VS, I'm not really sure if it belongs here, or CoreFX, or as a VS issue. Also, I realize I'm way off the map using ALC, reflection against private members, and so on.

Repository here: https://github.com/MV10/BlazorDynamicRCL

To use the repo you'll need to edit the path to the DLL in BlazorApp's `NavMenu.razor` file (explained below).

The goal was on-demand runtime loading and unloading of Razor Components from Razor Class Libraries into a Blazor server-side app. As occasionally mentioned by [others](https://github.com/aspnet/AspNetCore/issues/11734), for large portal-style enterprise apps this is practically a requirement to avoid building and deploying unwieldy "one big compile" monoliths.

The idea was to grab the `RenderFragment` of a library component to dump content into an otherwise-blank component that was compiled into the Blazor app. Unfortunately the `RenderFragment` inside `ComponentBase` is private so I used reflection to get it, but it does work, and from what I can see from diagnostics snapshots I don't have any suspicious references hanging around after unload. But in debug mode VS will crash randomly on the `Unload` -- sometimes only the 2nd or 3rd time, but occasionally it'll survive 6 or 7 unloads.

The repository contains three simple projects:

"RazorComponentManager" handles the AssemblyLoadContext stuff and is hard-coded to look for a component called `RazorComponent.Component`. The other two projects reference this one. It's a netcoreapp3.0 library and I had to add a `FrameworkReference` for ASP.NET Core libs.

"BlazorApp" is just the off-the-shelf Blazor template project with two changes. A new component `DynamicLoader.razor` was added which takes a path to an assembly to load, `NavMenu.razor` was updated with a link to the loader component (with a hard-coded path matching the debug build location on my local machine). (I have to mangle up the path since catch-all isn't supported for .razor files, so I just switch slashes to carets, obviously no real project would take any DLL pathname this way!)

"RazorComponent" started out as a Razor Class Library, but I had to change it from netstandard2.0 to netcoreapp3.0 and also added the ASP.NET Core `FrameworkReference` tag. It contains `Component.razor` which is just the Razor Component template and nothing more.

Reproducing the crash is simple. Run it, click the "Dynamic RCL" link, click "Home" or one of the other links, alternate a few times, and VS crashes.

![image](https://user-images.githubusercontent.com/794270/68587682-a37f9480-0455-11ea-9762-b04636cecc6c.png)

![image](https://user-images.githubusercontent.com/794270/68587717-b5f9ce00-0455-11ea-9784-40d91f9f2bf1.png)

Reference counts seem to look good when I look at diagnostic snapshots after an unload, and memory consumption is rock-steady across many load/unload iterations.

![image](https://user-images.githubusercontent.com/794270/68587783-eb062080-0455-11ea-9068-9e2e990758fc.png)

**Comment by javiercn** [comment]
@MV10 Thanks for contacting us.

I don't think this has anything specifically to do with Blazor and I suggest you file an issue either in CoreCLR or on stackoverflow to get help with this.

This is not something that we have tested/tried out and it might be that the framework is keeping a reference to some of your own code and that that is causing the ALC to crash the app, but as I said, this is not an area of expertise for us nor an scenario we claim to support.

**Comment by MV10** [comment]
Thanks. Kind of figured it would be too left-field.
