### ISSUE TITLE
HttpSys trailers OS version detection

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#16988]
HttpSys supports HTTP/2 response trailers for gRPC, but only on a preview version of Win10. Currently it uses `Environment.OSVersion.Version` to check this which works for unit tests but not for applications. Apps need to add an app.manifest declaring support for Win10 before the OSVersion will report those versions correctly. See https://stackoverflow.com/questions/33328739/system-environment-osversion-returns-wrong-version.

Proposals:
A) Add the app.manifest to new ASP.NET Core projects by default, or at least to the gRPC template?
B) Use alternate ways to sniff the OS version such as reading it directly from the registry. This is highly discouraged by the Windows team.
C) Feature detect trailers support. As far as we know this isn't possible due to the minimal nature of the new API (it expanded an existing struct, there are no new exports).

@shirhatti @JamesNK

**Comment by JamesNK** [comment]
D) Documentation. Running in HttpSys/IIS will probably be a minority of devs. Could just expect them to jump through more hoops

Is there a way to detect this situation? Someone is:
* Hosting in HttpSys
* On a supported OS
* No app.manafest

And then give them a clearer error message.

**Comment by Tratcher** [comment]
Not without implementing B.

**Comment by Tratcher** [comment]
IIS shouldn't have this issue, IIS has better feature detection mechanics.

**Comment by GrabYourPitchforks** [comment]
One kinda hacky way to detect if you're on Win10 would be to instantiate a `FileVersionInfo` around "kernel32.dll", then query the `FileVersionInfo.ProductMajorPart` property. Since this reads raw metadata from the file I don't think it's subject to OS version lies.

I wouldn't use the file version for OS feature detection, but it would be feasible to say "if the file version major part is \>= 10, and if `Environment.OSVersion` major part is /< 10, then the app likely isn't manifested properly" and show a better error message.

**Comment by JamesNK** [comment]
If trailers are missing then they'll be on HttpSys/IIS. Kestrel and TestServer will always have trailers.

There problem is either an old OS or no app.manafest. Should be able to create an error message that can guide them from that starting point to success. Could either include a doc link in the error message, or the error message on the docs page to drive search hits.

**Comment by shirhatti** [comment]
@OliaG I'm assuming WinForms has similar issues where certain APIs don't work unless you have an app.manifest, but you are on a supported OS. Do y'all do anything to detect this scenario?

**Comment by Tratcher** [comment]
Actually, if it's an Http/2 request then you know you're on Win10, you just don't know what version.

Note the error would be thrown by gRPC, not HttpSys. HttpSys doesn't know if a scenario requires trailers.

**Comment by Tratcher** [comment]
One more option: Detect the new API added for Reset (https://github.com/aspnet/AspNetCore/issues/17276)
