### ISSUE TITLE
Publish includes all "*.config" and "*.json" files

### ISSUE THREAD

**Issue by mikeharder** [aspnet/AspNetCore#16981]
When publishing a web application, all `*.config` and `*.json` files in any subdirectory are copied to the publish folder:

https://github.com/aspnet/websdk/blob/9e0bcbae34d4686e6a545b21c5d3c7862ca54266/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L31-L32

This may end up copying unnecessary files like:

* `NuGet.config`
* `*.config` and `*.json` files from a previous publish
  1. `dotnet publish -o pub1`
  1. `dotnet publish -o pub2`
  1. Folder `pub2` will contain a folder `pub1` with `*.config` and `*.json` files

We may want to consider restricting the publish to only well-known `*.config` and `*.json` files (like `web.config`), but it may be too late since this would be a breaking change.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
