### ISSUE TITLE
Role based Authorization using on-premise AD Security Groups

### ISSUE THREAD

**Issue by gregfig** [aspnet/AspNetCore#16995]
Hello folks,

I've looked all over for a week trying to find any kind of documentation on this, and cannot find any.  In ASP.NET Core 2.2, I can do the following without issue to use On-Premise Active Directory security groups for Role based Authorization:

_appsettings.json_:  (abbreviated)
```json
{
"Administrator": "MYDOMAIN\\Domain Admins",  
"Warehouse": "MYDOMAIN\\Warehouse Module",
}
```
_startup.cs_  (abbreviated)
```csharp
services.AddAuthentication(IISDefaults.AuthenticationScheme);

services.AddAuthorization(options =>
{
    options.AddPolicy("Warehouse", policy => policy.RequireRole(
        Con.GetSection("Administrator").Value,
        Con.GetSection("Warehouse").Value));
});
...
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
...
```
_Controller_ (Just the class)
```csharp
    [Authorize(Policy = "Warehouse")]
    public class WarehouseController 
```
However, trying to accomplish this in ASP.NET Core 3.0 fails.  It cannot find the group names.  I can get it to work by using the Groups SID, but that creates some weird circumstances too.  For example, for some reason, my Domain Admin group is set as a denyonlysid claim, but I've done nothing (that I know of) for that claim to be created.

The only difference I can see is that in 2.2, the authentication type is NTLM on the identity, but in 3.0 it is Negotiate.  I'm not advocating for NTLM here, I'm just trying to find out how to accomplish this type of role authorization in 3.0.  The only documentation I can find is on Azure, but that doesn't apply.

If the documentation exists somewhere and/or the way it's done has changed, I certainly cannot find it.  I'd appreciate any help you could provide.

Thanks

**Comment by blowdart** [comment]
What OS combinations are you using, for hosting and for the clients?

And does IsInRole() work on the principle?

**Comment by gregfig** [comment]
No, IsInRole() does not work on the principal (returns false).

Regarding OS Combinations.  All clients (currently) are Windows 10 Enterprise.  

2 separate production environments (2 different domains) are Windows Server 2016 (all servers).  The Web Servers implement IIS.

Also, in development, on a Windows 10 Enterprise machine on a domain, and using IIS Express, the same thing also happens.

**Comment by gregfig** [comment]
Ok, so I knew something like this would happen the minute I posted on here, but I have more information...

The problem seems to stem from using Claims Transformation.  I use it to do some things specific to my application (I don't add or remove any claims).  That, however, is irrelevant.  Doing the following causes the issue (without even modifying the principal):

This line is in startup.cs:
```csharp
services.AddTransient<IClaimsTransformation, ClaimsTransformer>();
```
In the Claims Transformation, don't even do anything, just return the _new_ principal.
```csharp
public class ClaimsTransformer : IClaimsTransformation
{
    private readonly IHttpContextAccessor _webCtx;

    public ClaimsTransformer(IHttpContextAccessor webCtx)
    {
        _webCtx = webCtx;
    }

    public async Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
    {
        var pUser = ((ClaimsIdentity)principal.Identity);
        var claimsIdentity = new ClaimsIdentity(pUser.Claims, pUser.AuthenticationType, pUser.NameClaimType, pUser.RoleClaimType);

        return new ClaimsPrincipal(claimsIdentity);
    }
}
```
The above works without issue in ASP.NET Core 2.2.

This would be a problem for anyone wanting to add claims to the identity (I would think).  Since I am not (at this time) actually adding claims, I can do the following and it seems to work:
```csharp
public class ClaimsTransformer : IClaimsTransformation
{
    private readonly IHttpContextAccessor _webCtx;

    public ClaimsTransformer(IHttpContextAccessor webCtx)
    {
        _webCtx = webCtx;
    }

    public async Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
    {
        var pUser = ((ClaimsIdentity)principal.Identity);

        //... do my stuff

        return principal;
    }
}
```
So it seems I shot myself in the foot, but it also seems to me that this is a problem... am I wrong on this?

Thanks.

**Comment by blowdart** [comment]
So WindowsPrincipal is special. You don't get the roles populated, it resolves the SIDs when you call IsInRole(). But as soon as you claims transform you don't have a WindowsPrincipal any more, so this resolution doesn't work.

**Comment by gregfig** [comment]
I am closing this issue, as it seems the problem is with Claims Transformation, not with the identity itself.  I still can't find any clear information regarding why Claims Transformation causes the issue, but this particular issue I opened is not the place for it.  Thank you.

**Comment by Tratcher** [comment]
The passed in value is actually a WindowsPrincipal (derives from ClaimsPrincipal) containing a WindowsIdentity (derives from ClaimsIdentity). You transformed a WindowsIdentity and a WindowsPrincipal into a ClaimsIdentity and a ClaimsPrincipal. That results in a loss of functionality.
