### ISSUE TITLE
Allow using a custom handler for OpenId

### ISSUE THREAD

**Issue by gcbenjamin** [aspnet/AspNetCore#16998]
I am trying to run some code that will run when ever a challenge is made to any OpenId Connect authentication provider. However even though the methods in src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs can be overridden, it doesn't look like you can use a custom handler. The handler to use is set and can't be changed in the following code in src/Security/Authentication/OpenIdConnect/src/OpenIdConnectExtensions.cs

    public static AuthenticationBuilder AddOpenIdConnect(
      this AuthenticationBuilder builder,
      string authenticationScheme,
      string displayName,
      Action<OpenIdConnectOptions> configureOptions
    {
        builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<IPostConfigureOptions<OpenIdConnectOptions>, OpenIdConnectPostConfigureOptions>());
        return builder.AddRemoteScheme<OpenIdConnectOptions, OpenIdConnectHandler>(authenticationScheme, displayName, configureOptions);
    }

Can we do something similar like is done for OAuth and allow using a custom handler? src/Security/Authentication/OAuth/src/OAuthExtensions.cs

**Comment by Tratcher** [comment]
OpenIdConnectHandler is quite complicated and not factored well for derivation. The Events are the recommended extensibility point.

OnRedirectToIdentityProvider is the event invoked for challenges. Have you tried it?
https://github.com/aspnet/AspNetCore/blob/e336f4010af69cfdaba8b79d95a527efeb7bd5da/src/Security/Authentication/OpenIdConnect/src/Events/OpenIdConnectEvents.cs#L29-L34

**Comment by gcbenjamin** [comment]
Since the code base already had a handler for OAuth I was hoping to follow the same pattern but won't be an issue to go this way. Thanks.

**Comment by gcbenjamin** [comment]
As a guide, if I create my own extension and use my handler which inherits from OpenIdConnectHandler, would that be acceptable or should I just not go there?

    public static AuthenticationBuilder AddOpenIdConnect(
      this AuthenticationBuilder builder,
      string authenticationScheme,
      string displayName,
      Action<OpenIdConnectOptions> configureOptions)
    {
        builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<IPostConfigureOptions<OpenIdConnectOptions>, OpenIdConnectPostConfigureOptions>());
        return builder.AddRemoteScheme<OpenIdConnectOptions, MYHANDLER>(authenticationScheme, displayName, configureOptions);
    }

**Comment by Tratcher** [comment]
I don't recommend that. The derivation scenario has never been tested and is likely to break.
