### ISSUE TITLE
Blazor's Individual Identity does not display login page after changing from defaultUI

### ISSUE THREAD

**Issue by bhrugen** [aspnet/AspNetCore#16990]
### Describe the bug
On a new blazor project if you change services.AddDefaultIdentity to services.AddIdentity,
the link to login/register page does not work

### To Reproduce
Create a new Blazor Server Project with Authentication as Individual USer Account
Go to startup.cs
change the adddefaultidentity to 
services.AddIdentity<IdentityUser,IdentityRole>()

Run application and navigate to login page.

**Comment by javiercn** [comment]
@bhrugen thanks for contacting us.

That's by design. 
You are removing the UI, so unless you scaffold it there's no UI for the links to go to.

**Comment by bhrugen** [comment]
Even after scaffolding the UI it gives the same error.

**Comment by javiercn** [comment]
@HaoK can you take a look? Maybe there's a step missing we need to add to the docs?
