### ISSUE TITLE
Wrong Login parameter ASP.NET Core 3.1 Identity

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#16991]
_From @AlexNek on Friday, November 8, 2019 10:54:50 AM_

# Issue Title

Why _signInManager.PasswordSignInAsync received as 1st parameter email value? It must be user name.

# General
By the user registering you fill username field with email value. If I test it immediate after register  with email then login work but when I change user name then login doesn't work. In addition invalid model "Cleared" all fields. My facebook login button on the right side will disappear.

_Copied from original issue: dotnet/core#3779_

**Comment by blowdart** [comment]
See https://github.com/aspnet/AspNetCore/issues/16979
