### ISSUE TITLE
System.Text.Encoding.Default.GetBytes() is different on the .net framework and .net core

### ISSUE THREAD

**Issue by wangpengzong** [aspnet/AspNetCore#17003]
I created two console applications, .net framework and .net core, and also wrote the following code.

`    class Program
    {
        static void Main(string[] args)
        {
            long iCnChar;
            var CnChar = "上海,日本 大阪,日本 神户,日本 东京";

            byte[] ZW_utf32 = System.Text.Encoding.UTF32.GetBytes(CnChar);

            // get the array of byte from the single char 
            int i1 = (short)(ZW_utf32[0]);
            int i2 = (short)(ZW_utf32[1]);
            iCnChar = i1 * 256 + i2;
            Console.WriteLine("UTF32.iCnChar={0}", iCnChar);

            byte[] ZW_utf7 = System.Text.Encoding.UTF7.GetBytes(CnChar);

            // get the array of byte from the single char 
            i1 = (short)(ZW_utf7[0]);
            i2 = (short)(ZW_utf7[1]);
            iCnChar = i1 * 256 + i2;
            Console.WriteLine("UTF7.iCnChar={0}", iCnChar);

            byte[] ZW_utf8 = System.Text.Encoding.UTF8.GetBytes(CnChar);

            // get the array of byte from the single char 
            i1 = (short)(ZW_utf8[0]);
            i2 = (short)(ZW_utf8[1]);
            iCnChar = i1 * 256 + i2;
            Console.WriteLine("UTF8.iCnChar={0}", iCnChar);

            byte[] ZW_default = System.Text.Encoding.Default.GetBytes(CnChar);

            // get the array of byte from the single char 
            i1 = (short)(ZW_default[0]);
            i2 = (short)(ZW_default[1]);
            iCnChar = i1 * 256 + i2;
            Console.WriteLine("Default.iCnChar={0}", iCnChar);

            Console.WriteLine("MD5={0}", MD5(CnChar));

            Console.ReadLine();

        }

        /// <summary>
        /// MD5函数
        /// </summary>
        /// <param name="str">原始字符串</param>
        /// <returns>MD5结果</returns>
        public static string MD5(string str)
        {
            byte[] b = Encoding.Default.GetBytes(str);
            b = new MD5CryptoServiceProvider().ComputeHash(b);
            string ret = "";
            for (int i = 0; i < b.Length; i++)
                ret += b[i].ToString("x").PadLeft(2, '0');
            return ret;
        }
    }`

.net framework
![image](https://user-images.githubusercontent.com/29770198/68638115-832a0580-053b-11ea-9720-5de67b84754e.png)

.net core
![image](https://user-images.githubusercontent.com/29770198/68638137-8e7d3100-053b-11ea-857d-e248d23b8c95.png)

In my .net framework project, I use the MD5 encryption (System.Text.Encoding.Default.GetBytes) in the city list string in the database, and then use the encrypted string as the file name to save the corresponding image. Server, which reduces the extra memory waste caused by duplicate strings. However, because "Default" is used, when the project is transferred to the .net core, there is a situation that cannot be found after MD5 encryption.

I compared System.Text.Encoding.Default.GetBytes

.net framework
![image](https://user-images.githubusercontent.com/29770198/68638527-d05aa700-053c-11ea-9e50-3075ee1bf36d.png)
![image](https://user-images.githubusercontent.com/29770198/68638538-d81a4b80-053c-11ea-884e-7a10d8943792.png)

.net core
![image](https://user-images.githubusercontent.com/29770198/68638579-fd0ebe80-053c-11ea-8153-40c5036ba78b.png)

emmmmm......

Is there any solution?

**Comment by benaadams** [comment]
System.Text.Encoding.CodePages has extra encodings? https://www.nuget.org/packages/System.Text.Encoding.CodePages/4.6.0

**Comment by wangpengzong** [comment]
> System.Text.Encoding.CodePages has extra encodings? https://www.nuget.org/packages/System.Text.Encoding.CodePages/4.6.0

My version of the .net framework is 4.7.2. Is it because of the Chinese version?

**Comment by wangpengzong** [comment]
.net framework      
Console.WriteLine("UTF8.CodePage={0}", System.Text.Encoding.UTF8.CodePage);
Console.WriteLine("Default.CodePage={0}", System.Text.Encoding.Default.CodePage);

UTF8.CodePage=65001
Default.CodePage=936

**Comment by benaadams** [comment]
Add a static property somewhere:
```csharp
public static Encoding ChineseHZEncoding { get; } =
    CodePagesEncodingProvider.Instance.GetEncoding(936);
```

Then that should work for both .NET Framework and .NET Core and change the MD5 to use it instead of default:

```csharp
/// <summary>
/// MD5函数
/// </summary>
/// <param name="str">原始字符串</param>
/// <returns>MD5结果</returns>
public static string MD5(string str)
{
    byte[] b = ChineseHZEncoding.GetBytes(str);
    b = new MD5CryptoServiceProvider().ComputeHash(b);
    string ret = "";
    for (int i = 0; i < b.Length; i++)
        ret += b[i].ToString("x").PadLeft(2, '0');
    return ret;
}
```

![image](https://user-images.githubusercontent.com/1142958/68643121-2f51f900-0508-11ea-903d-5ed7702a38db.png)

**Comment by benaadams** [comment]
Could allocate less intermediate strings by for example:
```csharp
public static string MD5(string str)
{
    byte[] b = ChineseHZEncoding.GetBytes(str);
    b = new MD5CryptoServiceProvider().ComputeHash(b);
    return ConvertToHex(b);
}

private static readonly uint[] s_lookup32 = Enumerable.Range(0, 255)
    .Select(i => {
    string s = i.ToString("x2");
    return ((uint)s[0]) + ((uint)s[1] << 16);
}).ToArray();

private static string ConvertToHex(byte[] bytes)
{
    var result = new char[bytes.Length * 2];
    for (int i = 0; i < bytes.Length; i++)
    {
        var val = s_lookup32[bytes[i]];
        result[2 * i] = (char)val;
        result[2 * i + 1] = (char)(val >> 16);
    }
    return new string(result);
}
```

**Comment by wangpengzong** [comment]
> Add a static property somewhere:
> 
> ```cs
> public static Encoding ChineseHZEncoding { get; } =
>     CodePagesEncodingProvider.Instance.GetEncoding(936);
> ```
> 
> Then that should work for both .NET Framework and .NET Core and change the MD5 to use it instead of default:
> 
> ```cs
> /// <summary>
> /// MD5函数
> /// </summary>
> /// <param name="str">原始字符串</param>
> /// <returns>MD5结果</returns>
> public static string MD5(string str)
> {
>     byte[] b = ChineseHZEncoding.GetBytes(str);
>     b = new MD5CryptoServiceProvider().ComputeHash(b);
>     string ret = "";
>     for (int i = 0; i < b.Length; i++)
>         ret += b[i].ToString("x").PadLeft(2, '0');
>     return ret;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/1142958/68643121-2f51f900-0508-11ea-903d-5ed7702a38db.png)

Xièxiè nǐ,
4/5000
thank you,

> Add a static property somewhere:
> 
> ```cs
> public static Encoding ChineseHZEncoding { get; } =
>     CodePagesEncodingProvider.Instance.GetEncoding(936);
> ```
> 
> Then that should work for both .NET Framework and .NET Core and change the MD5 to use it instead of default:
> 
> ```cs
> /// <summary>
> /// MD5函数
> /// </summary>
> /// <param name="str">原始字符串</param>
> /// <returns>MD5结果</returns>
> public static string MD5(string str)
> {
>     byte[] b = ChineseHZEncoding.GetBytes(str);
>     b = new MD5CryptoServiceProvider().ComputeHash(b);
>     string ret = "";
>     for (int i = 0; i < b.Length; i++)
>         ret += b[i].ToString("x").PadLeft(2, '0');
>     return ret;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/1142958/68643121-2f51f900-0508-11ea-903d-5ed7702a38db.png)

thank you, It is work for me.

**Comment by wangpengzong** [comment]
> Add a static property somewhere:
> 
> ```cs
> public static Encoding ChineseHZEncoding { get; } =
>     CodePagesEncodingProvider.Instance.GetEncoding(936);
> ```
> 
> Then that should work for both .NET Framework and .NET Core and change the MD5 to use it instead of default:
> 
> ```cs
> /// <summary>
> /// MD5函数
> /// </summary>
> /// <param name="str">原始字符串</param>
> /// <returns>MD5结果</returns>
> public static string MD5(string str)
> {
>     byte[] b = ChineseHZEncoding.GetBytes(str);
>     b = new MD5CryptoServiceProvider().ComputeHash(b);
>     string ret = "";
>     for (int i = 0; i < b.Length; i++)
>         ret += b[i].ToString("x").PadLeft(2, '0');
>     return ret;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/1142958/68643121-2f51f900-0508-11ea-903d-5ed7702a38db.png)



> Could allocate less intermediate strings by for example:
> 
> ```cs
> public static string MD5(string str)
> {
>     byte[] b = ChineseHZEncoding.GetBytes(str);
>     b = new MD5CryptoServiceProvider().ComputeHash(b);
>     return ConvertToHex(b);
> }
> 
> private static readonly uint[] s_lookup32 = Enumerable.Range(0, 255)
>     .Select(i => {
>     string s = i.ToString("x2");
>     return ((uint)s[0]) + ((uint)s[1] << 16);
> }).ToArray();
> 
> private static string ConvertToHex(byte[] bytes)
> {
>     var result = new char[bytes.Length * 2];
>     for (int i = 0; i < bytes.Length; i++)
>     {
>         var val = s_lookup32[bytes[i]];
>         result[2 * i] = (char)val;
>         result[2 * i + 1] = (char)(val >> 16);
>     }
>     return new string(result);
> }
> ```
thank you,It is work for me.
