### ISSUE TITLE
chained bind and @bind:format

### ISSUE THREAD

**Issue by niconico49** [aspnet/AspNetCore#17023]
In the docs https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0
inside the topic "Chained Bind" was explained the necessity to separate the event handler and the value:
"A chained bind can't be implemented with @bind syntax in the page's element. The event handler and value must be specified separately. A parent component, however, can use @bind syntax with the component's parameter."
But there aren't any example in substitution for @bind:format
For instance, if you try to do some child component ChildComponent.razor as
<input type"=date" value="DateValue"
           @onchange="@OnChange" />
@code {
    [Parameter] public DateTime DateValue { get; set; }
    [Parameter] public EventCallback<DateTime> DateValueChanged { get; set; }
}
and a parent component ParentComponent.razor as

<ChildComponent @bind-DateValue="ParentDateValue"/>

@code {
   private DateTime ParentDateValue { get; set; }
}

what happen is that that you can open the datetime snippet form html 5 but, when you select some day , by debug the parameter DateValue ParentDateValue are correctly two-binded, but the input tag at last remain empty (at last because during debugging, at first became correctly setted, but then will become empty and I don't know why).

I suppose this is linked with date formatting (bind:format) because without "chained bind" as 
<input type="date" @bind="ValueDate" @bind:format="yyyy-MM-dd" />

@code {
  private DateTime ValueDate { get; set; }
}

everything works correctly and, for me, the only difference is a lacking of explanation (or a bug) about how to convert the @bind:format in "chained bind" case.

Somebody can helps about this problem????

Thanks!!!!

**Comment by javiercn** [comment]
@niconico49 thanks for contacting us.

@rynowak Can you explain what the right way to do this is? (If possible).
