### ISSUE TITLE
HTTP Error 502.5 Process Failure error when running asp.net core website on iis

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17033]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/812622/http-error-5025-process-failure-error-when-running.html)._

---
<p>I have developed an asp.net core website and it runs fine on local machine. When I deploy to my server, it gives HTTP Error 502.5 Process Failure </p><p>the asp.net core process is not starting. Why?</p><p>I have installed the correct .net runtime and hosting bundle also.</p><p>Still why is it not running?</p><p><br></p>

---
#### Visual Studio Feedback System on 11/7/2019, 11:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Parthasarathy C Mandayam on 11/8/2019, 00:30 AM: 

<p>Thanks. I will await their response.</p>

#### Andrew Stanton-Nurse [MSFT] on 11/8/2019, 10:13 AM: 

<p>The <a target='_blank' href="https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.0#5025-process-failure">502.5 error</a> often indicates some start-up error in your application. It could be the runtime, something your installation, or it could just be a crash in your application. There are a few ways to get more information that can help us diagnose this issue:</p>
<ul>
<li>Try running the app from the command-line using <code>dotnet run</code></li>
<li>Check the Windows Event Log for any errors from “.NET Runtime” or “<a target='_blank' href="https://ASP.NET">ASP.NET</a> Core Module”</li>
<li>Enable the <a target='_blank' href="https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.0#aspnet-core-module-stdout-log-iis">stdout log</a> and take a look at the console output from your application</li>
</ul>
<p>If you can figure the problem out from those, awesome! If not, please attach the stdout log and any errors you found in the Event Log to this ticket and let us know. We can investigate further from there!</p>

#### Parthasarathy C Mandayam on 11/8/2019, 10:49 PM: 

<p>I updated to .net core 2.2 because many people said that's better than .net core 2.1.</p><p>My server also has .net core 2.2 installed</p><p>But now I get </p><h3>HTTP Error 500.0 - Internal Server Error</h3><p>This is giving error on the server so I cannot use dotnet run because that needs the csproj file</p><p>Here is what I got from the windows event log</p><strong>System</strong>
<strong>-</strong><strong>Provider</strong>
[ <strong>Name</strong>]IIS AspNetCore Module V2
<strong>-</strong><strong>EventID</strong>
[ <strong>Qualifiers</strong>]
<strong>Level</strong>
<strong>Task</strong>
<strong>Keywords</strong>
<strong>-</strong><strong>TimeCreated</strong>
[ <strong>SystemTime</strong>]
<strong>EventRecordID</strong>
<strong>Channel</strong>Application
<strong>Computer</strong>WIN-6PEER3JJ29I
<strong>Security</strong>
<strong>-</strong><strong>EventData</strong>
Could not load configuration. Exception message: Attribute 'processPath' is required.
Process Id: 7048.
File Version: 12.2.19169.6. Description: IIS <a target='_blank' href="https://asp.net/">ASP.NET</a> Core Module V2. Commit: e7f262e33108e92fc8805b925cc04b07d254118b<br><br><br>I enabled stdout but it's not writing anything in the logs folder<br>Why???

#### Parthasarathy C Mandayam on 11/10/2019, 08:34 PM: 

<p>Do you have any updates?</p>

#### Parthasarathy C Mandayam on 11/10/2019, 11:00 PM: 

<p>I put a plain html file in my application directory and even that is giving the same error. </p><p>Why?</p>

#### Andrew Stanton-Nurse [MSFT] on 11/11/2019, 08:20 AM: 

<p>The error message in the event log (“Attribute ‘processPath’ is required.”) indicates something is wrong with your web.config file. Could you attach the web.config file for your published app to the ticket? You should have an `&lt;aspnetcore&gt;` element and it should have a “processPath” attribute pointing to “dotnet.exe” or your application (depending on how you’ve deployed it). Are you deploying a framework-dependent app (where only your app binaries are deployed) or a self-contained deployment (which contains all the .NET Core binaries as well)?</p>

#### Parthasarathy C Mandayam on 11/11/2019, 09:58 PM: 

<p>yes. processpath="dotnet" is there. I even tried making processpath="c:\program files\dotnet" giving it the full path because some articles suggested that</p><p>Mine is a framework dependant app</p><p>What else could be the problem?</p>

#### Parthasarathy C Mandayam on 11/11/2019, 11:00 PM: 

<p>This article says adding the full path helps</p><p><a target='_blank' href="https://github.com/aspnet/AspNetCore/issues/9021">https://github.com/aspnet/AspNetCore/issues/9021</a></p>

#### Andrew Stanton-Nurse [MSFT] on 11/12/2019, 08:15 AM: 

<p>I’m going too move this over to GitHub now, so we can get the whole team involved. The comment after this one will include a link to the new GitHub issue, we should move discussion there.</p>

---
### Original Solutions
(no solutions)

**Comment by jkotalik** [comment]
I think we need more diagnostics for this issue. Can you check the windows event log and share them here?

**Comment by mcp111** [comment]
So is this abnormal behavior?
What do you want from the windows log?

**Comment by anurse** [comment]
> Could not load configuration. Exception message: Attribute 'processPath' is required. Process Id: 7048. File Version: 12.2.19169.6. Description: IIS ASP.NET Core Module V2. Commit: e7f262e

This is the key error here, I think. The `processPath` attribute appears to be missing.

@mcp111 can you share the web.config **from the deployment** (not the one in the project directory, but the one that is actually deployed on the server)?

**Comment by mcp111** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\UpdateClassboatFromZoho.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
</configuration>

**Comment by mcp111** [comment]
I already told you on 11/11 that processpath="dotnet" is there
Later I also told you that I tried giving the full path "c:\Program Files\dotnet" and it still didn't work
So web.config is fine

**Comment by anurse** [comment]
> I already told you on 11/11 that processpath="dotnet" is there
> Later I also told you that I tried giving the full path "c:\Program Files\dotnet" and it still didn't work
> So web.config is fine

Yes, I know that. We need to see the **full content** of the deployed web.config to understand the problem. I believe you that the `processPath` is there, it's the rest of the content that is important for us to understand the issue.

**Comment by mcp111** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\UpdateClassboatFromZoho.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
</configuration>

**Comment by mcp111** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\UpdateClassboatFromZoho.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
</configuration>

**Comment by mcp111** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\UpdateClassboatFromZoho.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
</configuration>

**Comment by mcp111** [comment]
web.config is attached
[webconfig.txt](https://github.com/aspnet/AspNetCore/files/3857638/webconfig.txt)

**Comment by mikebrind** [comment]
According to your webconfig, you have not enabled logging output. First, change `stdoutLogEnabled="false"` to "`true`".

**Comment by anurse** [comment]
Thank you for the full content, that helps a lot in our diagnostic process. You indicated earlier that enabling stdout logging didn't produce any output, so I don't think that's the root cause here.

Could you try enabling the debug log (see [our Troubleshooting article for information on how to do this](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.0#aspnet-core-module-debug-log-iis))? That may provide more insight in to what is happening here. This is *different* from the stdout log, which only produces useful input if the module is able to start the process.

Also, if you are able to provide more detail on the deployment environment you have that would help. Do you have other applications running in IIS or is this the only one?

**Comment by mcp111** [comment]
There are several other websites running on that server but none are on .net core

**Comment by anurse** [comment]
> Could you try enabling the debug log (see [our Troubleshooting article for information on how to do this](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.0#aspnet-core-module-debug-log-iis))?

Were you able to enable the debug log? That should provide more detail on what's going on here.
