### ISSUE TITLE
Startup hooks do not work on IIS hosted ASP.NET Core 3.0 applications

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#17039]
ASP.NET Core 3.0 introduced a custom startup hook to improve error handling for IIS scenarios. As a side effect this breaks custom startup hooks that users/platforms may provide. This is a regression from 2.2.

We should patch this because we’re currently thinking about using this for application insights 

cc @anurse @jkotalik

**Comment by jkotalik** [comment]
The fix is easy, do we need this in 3.0, 3.1, and 5.0? Or just 5.0.

**Comment by anurse** [comment]
You can freely make the change in 5.0. We'll need to have a quick chat about the others. (cc @Pilchie)

**Comment by davidfowl** [comment]
I think 3.1 definitely, not sure about 3.0

**Comment by Pilchie** [comment]
Let's consider this for 3.1.1 servicing rather than resetting GA builds for it at this point.  Once 3.1 ships, our policy is not to patch 3.0 except for security issues, so we would NOT take it there.

**Comment by jkotalik** [comment]
IMO let's just start with 3.1; no rush to get this into 5.0 and if we decide not to take it for 3.1, I'll just change the branch.
