### ISSUE TITLE
CompareInfo not available in Blazor WASM

### ISSUE THREAD

**Issue by Peter-Juhasz** [aspnet/AspNetCore#17058]
### Describe the bug
We are trying to implement filtering items on the web UI by a filter text being typed into a text box. For convenience, we want to ignore casing and diacritics/accents as well.

Ignoring case works fine with specifying `StringComparison`, but ignoring diacritics doesn't.

One of the most popular solution for this problem is this: https://stackoverflow.com/a/249126 It uses normalization and Unicode categories, but even though it works, in the end it creates a new string which is not cost effective, especially if you want to use it for real-time typing and filtering of data.

So, the optimal way would be to use the built-in `CompareInfo` class with the `IgnoreNonSpace` option, that really only compares two strings, without having to create new ones during the search. The `IndexOf` method gives back no results, even though there are. But there are is exception either, like it is not supported, or culture data is missing to perform that operation.

### To Reproduce
```razor
@(CultureInfo.InvariantCulture.CompareInfo.IndexOf("Elemzések", "elemze", CompareOptions.IgnoreCase | CompareOptions.IgnoreNonSpace))
```

Gives `-1` instead of `0`. If I run the same in a .NET Core Console Application, it works fine.

I've also tried it with `CurrentCulture` or specifying the culture by its name or id.

### Further technical details
- ASP.NET Core version: 3.0
- Include the output of `dotnet --info`: 3.1.100-preview2-014569
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual Studio 19.4 Preview 4

**Comment by javiercn** [comment]
@Peter-Juhasz thanks for contacting us.

We can see there might be a problem here, but this is likely an issue with mono. We will route the issue to them appropriately.

**Comment by javiercn** [comment]
This issue was moved to mono/mono#17780
