### ISSUE TITLE
Clean up Blazor.Build package

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#17072]
* [x] Review the contents of the package and remove and refactor content
* [x] Replace exes launched by the process with MSBuild tasks 
* [x] Replace using custom build of ILLink with the one in the SDK
* [ ] Any further work based on the SDK team's feedback

**Comment by mkArtakMSFT** [comment]
Moving this to `Preview 5` as there is some follow-up work left here with the SDK team.

**Comment by pranavkm** [comment]
We can use https://github.com/aspnet/AspNetCore/issues/17644 to track figuring out what to do with the task that's in our build. There's an offline discussion about the PR:  https://github.com/aspnet/AspNetCore/pull/17874 that has an overlap with that issue.
