### ISSUE TITLE
Localization Resx With Custom IViewLocationExpander Local vs Published error

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/AspNetCore#17076]
I have an app that uses a custom `IViewLocationExpander `(multi-tenant application).  **When running locally**, language resource files (.resx) referenced using ViewLocalization via `IViewLocalizer` works fine.  

Once published to server using WebPublish method, none of the tenant specific shared views are being localized (standard View localization continues to work on server after WebPublish).

- Resx files are set as "Embedded Resource"

Startup.cs:
```
           // localization
            services.AddLocalization(opts =>
            {
                opts.ResourcesPath = "Resources";
            });

            services.AddMvc()
                .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix, opts => { opts.ResourcesPath = "Resources"; })
                .AddDataAnnotationsLocalization();
```

View Expander:
```
    public class TenantViewLocationExpander : IViewLocationExpander
    {
        private string _tenant;

        public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (viewLocations == null)
            {
                throw new ArgumentNullException(nameof(viewLocations));
            }

            context.Values.TryGetValue("tenanttag", out string tag);

            if (!string.IsNullOrEmpty(tag))
            {
                return ExpandViewLocationsCore(viewLocations, tag);
            }

            return viewLocations;
        }

        private IEnumerable<string> ExpandViewLocationsCore(IEnumerable<string> viewLocations, string value)
        {
            foreach (var location in viewLocations)
            {
                yield return location.Replace("{0}", value + "/{0}");
                yield return location;
            }
        }

        public void PopulateValues(ViewLocationExpanderContext context)
        {
            _tenant = AppUtil.GetRequestTenant(context.ActionContext.HttpContext).Tag;
            context.Values["tenanttag"] = _tenant;
        }
    }
```

"Tag" in the above code is a string that will be "local" or "tenant1" or "tenant2".

Resource file organization:
![image](https://user-images.githubusercontent.com/15930167/68801419-af1fb680-0621-11ea-94d6-4b969a88c39e.png)

![image](https://user-images.githubusercontent.com/15930167/68801684-2c4b2b80-0622-11ea-9ef6-d774479ed020.png)

I'm calling __FrontPageContent.cshtml_ from _/Views/Home/Index.cshtml_  via 
`
  @await Html.PartialAsync("_FrontPageContent")`

**Comment by javiercn** [comment]
@SimonOrdo thanks for contacting us.

@pranavkm Is there anything here you see might be caused by the runtime or does this seem like a publish issue to you?

/cc: @ryanbrandenburg

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
