### ISSUE TITLE
Late Binding Models from the Controller

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#17075]
_From @GrantHoffman on Wednesday, November 13, 2019 3:41:27 PM_

I'm trying to figure out a way to leverage the existing model binding in the project.  To Bind to an entity at run time.

I have a stackoverflow question for it [here](https://stackoverflow.com/questions/58828401/resolve-models-dynamically-from-httpcontext)

Basically I'm trying to resolve a type from a controller. e.g

    public T ResolveType<T>(HttpContext httpContext, string parameterName)
    {
          //How can I resolve the Type from the query string with the parameterName?
    }  

_Copied from original issue: dotnet/core#3799_

**Comment by javiercn** [comment]
@GrantHoffman thanks for contacting us.

In order for us to help you, could you do something like this https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/ModelBindingHelper.cs, but this is not something we support outside of the context of MVC or outside of the controller action. If you are within a controller, it's best if you use Controllerbase.TryUpdateModel.

Hope this helps.

**Comment by GrantHoffman** [comment]
I have a controller (Web-API). Which I won't know what parameters are needed until runtime.  Its hard to depict, simply but imagine something similar to this:

        [HttpGet]
        public object Get(string filterName)
        {
            var argFromFilter = this.GetArgumentOptions(filterName);
            var func = this.GetFuncFromFilterName(filter);
            var arg = this.Resolve(argFromFilter)
            return func(arg)
        }

The Class you've provided `ModelBindingHelper` is static internal.  So I cannot invoke it.   I just want to do something like.

     ModelBinderFactory modelBinderFactory;
     //Obtains the proper binder from the registration
     var binder = this._modelBinderFactory.CreateBinder(context);
     return binder.Resolve<MyModel>(paramName: "MyModel");

This should be seemingly simple, but I don't see a way to do this
