### ISSUE TITLE
IHubProtocol.ts imports 'Buffer' type make it incompatible with angular and typescript 3.7.2

### ISSUE THREAD

**Issue by chenlcacentury** [aspnet/AspNetCore#17070]
After upgrading to TS 3.7, the ts compiler complains:
```
ERROR in node_modules/@types/node/index.d.ts:73:11 - error TS2300: Duplicate identifier 'IteratorResult'.
73 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;

```
I finally found the `@aspnet/signalr` imports `@types/node` in its `@aspnet\signalr\dist\esm\IHubProtocol.d.ts` which causes conflict with TypeScript's lib definitions. 

For angular, I prefer to use the typed library rather than only embed it by <script> tag. It is not very clear if the typed signalr client library support node only or support browser as well. 

To workaround,  I removed the `Buffer` type from the IHubProtocol.d.ts and removed the node reference too.

**Comment by BrennanConroy** [comment]
Looks like a dupe of https://github.com/aspnet/AspNetCore/issues/13805

**Comment by halter73** [comment]
We want see if removing the `@types/node` import causes problems with old TS compilers or scenarios. If we need the import for older TS versions, maybe we can look into using different types that don't conflict.

**Comment by chenlcacentury** [comment]
Yes, this issue is duplicated, close it and track #13805
