### ISSUE TITLE
Blazor Project -- Add item menu is missing "Razor Component"

### ISSUE THREAD

**Issue by BrainSlugs83** [aspnet/AspNetCore#17077]
### Describe the bug
There's no option to add a `Razor Component` when you right click on a folder in a Blazor project.  But there is a misleading `Add Razor Page` which is not relevant to the current project type (and it adds a bunch of unwanted NuGet packages as screws up your project as well).

It seems everyone on my team has made the mistake of clicking on that at least once, and "learned the hard way" not to do this.  But it's definitely misleading, and provides a bad experience.  (Also it's super inconvenient to have to go through the wizard to add a new component every time.) 

![image](https://user-images.githubusercontent.com/5217366/68803355-6f9e9d80-0614-11ea-99fd-e7436e76282b.png)

### To Reproduce
 1. Create a new Blazor server project. 
 2. Right click on the pages folder, and notice that while there is an option to add a `Razor Page`, there is no option to add a `Razor Component`.  
    (And if you do click on add a `Razor Page` it will mess up your project adding in a bunch of unnecessary NuGet packages and eventually an unusable `.cshtml` file.)

### Further technical details
- ASP.NET Core version 3.0.100
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual Studio 2019 -- Version 16.3.8

**Comment by javiercn** [comment]
@BrainSlugs83 thanks for contacting us.

Thank you for your feature request. We'll consider this feature during the next release planning period and update the status of this issue accordingly.

This is a tooling request, so it is best if you file it from the send VS Feedback dialog on the top right corner of visual studio. See https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019#make-a-suggestion

@vijayrkn This is a tooling feature request, just so that it doesn't get lost.
