### ISSUE TITLE
Validator regression for property with exceptions thrown out from getter

### ISSUE THREAD

**Issue by GoneWithWind** [aspnet/AspNetCore#17087]
We are in the progress of migrating code from asp.net to asp.net core and found some regression regarding model validation.

Our original .net code use DefaultBodyModelValidator, which will swallow the exceptions if it is unable to retrieve a property:
https://github.com/aspnet/AspNetWebStack/blob/ebef5b7d821b64ed5c48765d0caf6ce8a9bcfaf5/src/System.Web.Http/Validation/DefaultBodyModelValidator.cs#L113-L123
![image](https://user-images.githubusercontent.com/5491882/68848224-ea49e480-070a-11ea-980b-da9fc9df9fa0.png)

But asp.net core has different behaviors, it did not have the same logic to swallow the exception and validation will fail:
https://github.com/aspnet/AspNetCore/blob/602cb1dea59751a1297d674cddf7f0729c23e6ca/src/Mvc/Mvc.Core/src/ModelBinding/Validation/ValidationVisitor.cs#L361

It this by design?

### Further technical details
- ASP.NET Core 2.2

**Comment by javiercn** [comment]
@GoneWithWind thanks for contacting us.

Just to be clear, are you migrating from ASP.NET to ASP.NET Core? If that's the case, those types of behavior changes can happen.

Can you tell us more about your scenario so that we can provide further advice/guidance?

**Comment by GoneWithWind** [comment]
@javiercn , thanks a lot for your reply. 

What we want to do is to exclude some properties from model validation in ASP.NET Core. I tried to reproduce the behavior in my toy project but failed. I guess it has something to do with OData, we used OData a lot in our projects. My toy project without OData works as expected.

But I was able to solve the problem using the ValidateNeverAttribute: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.validation.validateneverattribute?view=aspnetcore-3.0

Thanks again.

**Comment by javiercn** [comment]
@GoneWithWind I'm glad to hear that you found an answer. I believe using ValidateNever is the right solution. With regards to OData, it is build on top of ASP.NET Core, but its developed by an independent team at Microsoft.

If you are using OData and have more migration issues I would suggest you start with them at https://github.com/OData/WebApi

I'm closing this issue as there's no action for us to take here.
