### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/AspNetCore#17083]
When I run `restore.cmd` (I followed all instructions from the readme) - I get

```
C:\Users\dominick\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\Tools.proj : error : Version 3.0.100 of the .NET Core SDK requires at least v ersion 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831. Change the .NET Core SDK specified in global.json to an older version that req uires the MSBuild version currently available.
C:\Users\dominick\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\Tools.proj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not b e found.
Build failed.
```

I am using the `release/3.0` tag.

Any idea?

**Comment by javiercn** [comment]
Hi Dominic!

Not sure what's going on, but I recommend you start with a `git clean -xdff` after switching branches and then try again. The build scripts should be self-contained, but switching branches leaves left-over that breaks things sometimes.

@aspnet/build can you help here?

**Comment by dougbu** [comment]
@leastprivilege please see
- https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#common-error-unable-to-locate-the-net-core-sdk
- https://github.com/aspnet/AspNetCore/blob/master/docs/BuildErrors.md#error-msb4236--unable-to-locate-the-net-core-sdk

**Comment by leastprivilege** [comment]
Hey

thanks - but this doesn't help.

It is also a slightly different error message as linked by @dougbu

**Comment by leastprivilege** [comment]
I just did a fresh clone - same result - does the full output help?

```
C:\local\ms\AspNetCore [release/3.0 ≡]> .\restore.cmd
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100/dotnet-sdk-3.0.100-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100/dotnet-sdk-3.0.100-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\local\ms\AspNetCore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
Downloading vswhere
Downloading RoslynTools.MSBuild 16.0.0-alpha
C:\Users\dominick\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\Tools.proj : error : Version 3.0.100 of the .NET Core SDK requires at least v ersion 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831. Change the .NET Core SDK specified in global.json to an older version that req uires the MSBuild version currently available.
C:\Users\dominick\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\Tools.proj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not b e found.
Build failed.
```

**Comment by javiercn** [comment]
@leastprivilege I think is might not be finding your VS (or VS tools).

We have an InstallVisualStudio.ps1 script under eng\scripts. If you run it, it should make sure you have all the required components from visual studio installed. You can try that and see if it helps (disclaimer, I'm no expert in this area).

**Comment by dougbu** [comment]
@leastprivilege it may also help to look at detailed logs to find which `msbuild` installation your build actually uses. The `The current available version of MSBuild is 16.0.461.62831` part of the message indicates something unexpectedly old was found.

**Comment by leastprivilege** [comment]
Is that maybe related to

`Downloading RoslynTools.MSBuild 16.0.0-alpha` ?

**Comment by leastprivilege** [comment]
> it may also help to look at detailed logs

@dougbu how do I do that?

**Comment by dougbu** [comment]
@leastprivilege you can enable logging on the `.\restore.cmd` the same way you'd do it on the `msbuild` command line e.g. `-bl` or `/fl /flp:Verbosity=detailed`

@aspnet/build for additional questions since I'm on vacation for the next few days

**Comment by SteveSandersonMS** [comment]
This problem happened to me when I only had VS Preview installed. The problem went away when I also installed regular VS (non-preview channel).

**Comment by OdeToCode** [comment]
I had the same experience as @SteveSandersonMS. Once I had non-preview VS installed the build got a bit further, anyway.

**Comment by leastprivilege** [comment]
Here's the output when I run with the `-bl` switch - it seems it deliberately uses this msbuild version

```
C:\local\ms\AspNetCore [release/3.0 ≡]> .\restore.cmd -bl
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.101/dotnet-sdk-3.0.101-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.101/dotnet-sdk-3.0.101-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\local\ms\AspNetCore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
Downloading vswhere
Downloading RoslynTools.MSBuild 16.0.0-alpha
C:\local\ms\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\MSBuild\Current\Bin\msbuild.exe /nologo /bl:C:\local\ms\AspNetCore\artifacts\log\Debug\ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /m /nr:False /p:ContinuousIntegrationBuild=False /p:TreatWarningsAsErrors=false /p:__ToolsetLocationOutputFile=C:\local\ms\AspNetCore\artifacts\toolset\1.0.0-beta.19577.5.txt /t:__WriteToolsetLocation /v:minimal C:\local\ms\AspNetCore\artifacts\toolset\restore.proj
C:\Users\dominick\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19577.5\tools\Tools.proj : error : Version 3.0.101 of the .NET Core SDK require s at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831. Change the .NET Core SDK specified in global.json to a n older version that requires the MSBuild version currently available.
C:\Users\dominick\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19577.5\tools\Tools.proj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified  could not be found.
Build failed.
```

**Comment by leastprivilege** [comment]
..I don't have VS preview installed at all.

**Comment by dougbu** [comment]
@leastprivilege exactly what _do_ you have installed? The logs you shared implied it's something older
```
Version 3.0.101 of the .NET Core SDK require s at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831
```

----
FYI I'm hitting some issues on a new machine with these steps but the behaviour is completely different&hellip; (Probably an error on my part.)

**Comment by leastprivilege** [comment]
I have the latest non-preview VS installed - what looks weird to me is that the script first installs MSBuild

`Downloading RoslynTools.MSBuild 16.0.0-alpha`

and then explicitly invokes it via the tools folder

`C:\local\ms\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\MSBuild\Current\Bin\msbuild.exe /nologo /bl:C:\local\ms\AspNetCore\artifacts\log\Debug\ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /m /nr:False /p:ContinuousIntegrationBuild=False /p:TreatWarningsAsErrors=false /p:__ToolsetLocationOutputFile=C:\local\ms\AspNetCore\artifacts\toolset\1.0.0-beta.19577.5.txt /t:__WriteToolsetLocation /v:minimal C:\local\ms\AspNetCore\artifacts\toolset\restore.proj
`

and this fails. I will try again with .NET Core 3.1 tomorrow and see if that makes any difference.

**Comment by leastprivilege** [comment]
I tried it again with the `release/3.1` tag. Same problem. I have the latest RTM of VS installed.

```
C:\local\ms\AspNetCore [release/3.1 ≡]> .\restore.cmd -bl
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.100-preview1-014400/dotnet-sdk-3.1.100-preview1-014400-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.100-preview1-014400/dotnet-sdk-3.1.100-preview1-014400-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\local\ms\AspNetCore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
Downloading vswhere
Downloading RoslynTools.MSBuild 16.0.0-alpha
C:\local\ms\AspNetCore\.tools\msbuild\16.0.0-alpha\tools\MSBuild\Current\Bin\msbuild.exe /nologo /bl:C:\local\ms\AspNetCore\artifacts\log\Debug\ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /m /nr:False /p:ContinuousIntegrationBuild=False /p:TreatWarningsAsErrors=false /p:__ToolsetLocationOutputFile=C:\local\ms\AspNetCore\artifacts\toolset\1.0.0-beta.19517.3.txt /t:__WriteToolsetLocation /v:minimal C:\local\ms\AspNetCore\artifacts\toolset\restore.proj
C:\Users\dominick\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19517.3\tools\Tools.proj : error : Version 3.1.100-preview1-014400 of the .NET
Core SDK requires at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461.62831. Change the .NET Core SDK specified in
global.json to an older version that requires the MSBuild version currently available.
C:\Users\dominick\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19517.3\tools\Tools.proj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified  could not be found.
Build failed.
```

**Comment by dougbu** [comment]
Thanks to @pranavkm for figuring this one out. See #17633.

**Comment by pranavkm** [comment]
@leastprivilege this is a result of 

a) Not having VS with the correct pre-reqs installed
b) AspNetCore's `global.json` having an incorrect min requirement.

You could workaround this by installing VS with the min pre-reqs to build the repository by running `.\eng\scripts\InstallVisualStudio.ps1`.

**Comment by leastprivilege** [comment]
Thanks! It is working now!
