### ISSUE TITLE
JSRuntime.InvokeAsync limited to ~32000 byte length

### ISSUE THREAD

**Issue by baer999** [aspnet/AspNetCore#17084]
Hello,

I got  some limitations in terms of using InvokeAsync with return value.

In my sample project attached you can see that after some clicks in COUNTER.razor the loading takes long time and stops with Timeout exception...

Is it a known limitation and will it be increased (or can be increased from my side?)

Thx!

[BlazorApp2.zip](https://github.com/aspnet/AspNetCore/files/3845232/BlazorApp2.zip)

**Comment by javiercn** [comment]
@baer999 thanks for contacting us.

You are hitting the SignalR message size limit. We don't recommend you change that, so to workaround that limitation you can instead divide your JS Interop response into multiple chunks, retrieve it chunk by chunk and then compose the final response.

Hope that helps.
