### ISSUE TITLE
Hosting Bundle 3.0 don't install IIS modules

### ISSUE THREAD

**Issue by WebDucer** [aspnet/AspNetCore#17086]
### Describe the bug
We installed the new Hosting Bundle 3.0 on some new installed servers. The Asp.Net Core applications was always responding with 500.21 or 500.19. After dee analysis we figured out, that AspNetCore modules was not registeren (and not installed) in IIS. Repair and deinstallation/installation doesn't solve the problem.

None of the expeced module folders / files was there:

- `%ProgramFiles%\IIS\Asp.Net Core Module\V2`
- `%SystemRoot%\system32\inetsrv\aspnetcore.dll`

### To Reproduce

- Use new installed MS Server with IIS
- Install Hosting Bundle 3.0
- Try to host an Asp.Net Core application (we have Core 2.2 apps)

### Further technical details

- ASP.NET Core version 2.2

### Workaround

- Install Hosting Bundle 2.2.7 first, then
- Install Hosting Bundle 3.0

**Comment by Tratcher** [comment]
@joeloff ?

**Comment by joeloff** [comment]
Are all the required IIS features enabled? When you run the installer it should display a message if it thinks ANCM cannot be installed. Typically it requires a number of features to be present. If you use DISM, you need to enable the following features: IIS-ASPNET45, IIS-WebServerRole, IIS-WebServer, IIS-WebSockets and IIS-WindowsAuthentication.

I noticed your work-around mentions that installing 2.2.7 first worked. I don't recall that we made any changes around the conditions we check for IIS. Do you have a log from the 3.0 installation?
