### ISSUE TITLE
What is needed to run a custom model binder?

### ISSUE THREAD

**Issue by Joe4evr** [aspnet/AspNetCore#17091]
I want to use my custom type:
```cs
public readonly struct Optional<T>
{
    public Optional(T value);

    public bool IsSpecified(out T value);
}
```
as part of request models for updating a data entity, something like this:
```cs
public sealed class UpdateObjectModel
{
    [Required]
    public Guid ObjectId { get; set; }

    public Optional<string> Title { get; set; }
    public Optional<string?> Description { get; set; }
}
```
The reason for this wrapper type is to be able to tell the difference between the following two example payloads:
```json
{
  "objectId": "ad9c08e0-b07c-4407-9253-bea27aff755d",
  "title": "New title"
}

{
  "objectId": "ad9c08e0-b07c-4407-9253-bea27aff755d",
  "description": null
}
```
where absence of a field means that the corresponding property value should stay the same. If `Description` was simply typed as `string?`, then in both cases `model.Description` would be `null` when the action method executes, and then there's no way to figure out if the requester meant "leave the description as-is" or "update the description to be blank".

So I've written a custom model binder, `OptionalBinder`, with *what I hope* is the appropriate logic to handle binding to these properties, but I can't verify that logic because nothing that I do makes the custom binder run. The most common response I get when sending a payload is (more-or-less):
```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "|538dbc75-48a12f5e84f35ebb.",
  "errors": {
    "model": [
      "The model field is required."
    ],
    "$.Description": [
      "The JSON value could not be converted to MyApp.Models.Optional`1[System.String]. Path: $.Description | LineNumber: # | BytePositionInLine: ##."
    ]
  }
}
```

Things I've tried:
* Decorating the properties with `[ModelBinder(typeof(OptionalBinder))]`: The binder does not get called
* Decorating the properties with `[BindProperty(BinderType = typeof(OptionalBinder))]`: The binder does not get called
* Decorating the properties with a derived `ModelBinderAttribute`: The binder does not get called
* Decorating the properties with a derived `BindPropertyAttribute`: The binder does not get called
* All of the above in combination with the presence|absence of `[FromBody]`: Still nothin'
* Registering a custom `IModelBinderProvider`: This gets called, but only for the main object and not for any of the properties, so that doesn't work to automatically redirect to the custom binder when it encounters them :unamused: :-1:

The severe lack of guidance from the framework itself or even docs doesn't help matters and really only serves to frustrate.

**Comment by javiercn** [comment]
@Joe4evr thanks for contacting us.

Modelbinders are used in conjunction with FromQuery, FromForm, etc. 

I believe based on your sample that you are binding a JSON payload using [FromBody]. In that case, the JsonInputFormatter is responsible for performing the binding of the incoming data. See https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0#frombody-attribute for the relevant documentation

That is powered by Sytem.Text.Json or Newtonsoft.Json depending on what you have configured (by default is System.Text.Json). 

See this doc on how to do this https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to

If you still have problems after following the suggested approach described in the link above, feel free to comment here and we'll try and help you further.

> The severe lack of guidance from the framework itself or even docs doesn't help matters and really only serves to frustrate.

I understand sometimes things can be hard to find on the docs, do you have any suggestion so that we can make this better?

**Comment by Joe4evr** [comment]
> I understand sometimes things can be hard to find on the docs, do you have any suggestion so that we can make this better?

1. The input limitations should probably be repeated on the page about making a custom model binder, *AND* somewhere in the doc-comments, since that detail is *ridiculously* easy to miss.
2. Why isn't there a way I can accomplish this kind of thing mostly agnostic of how the data can come in over the wire?
3. `InputFormatter` is a pretty terrible name that doesn't convey anything about that it handles binding. There's the single paragraph in the page about Model Binding, but no dedicated page that goes into detail about how to make a custom one.
4. Now that I *have* made an input formatter, I'm not seeing this get run either, which puts me back at square 1. :roll_eyes:

**Comment by javiercn** [comment]
@Joe4evr You shouldn't need to write an input formatter, just a converter.

I've filed https://github.com/aspnet/AspNetCore.Docs/issues/15704 and https://github.com/aspnet/AspNetCore.Docs/issues/15705 to improve the docs.

Here is a sample that shows how to do what you are trying with system.text.json I suspect that you will want to also avoid serializing optional values when they don't have a value. That's not part of this sample, as it's more involved, but you should be able to implement it yourself or switch to json.net that has that feature built-in.

[CustomJsonSerialization.zip](https://github.com/aspnet/AspNetCore/files/3851377/CustomJsonSerialization.zip)

Hope that helps.
