### ISSUE TITLE
Url.Action in Asp.Net Controller is adding a double slash

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17100]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/756834/urlaction-in-aspnet-controller-is-adding-a-double.html)._

---
Given the following line of code as an example:

var callbackUrl = Url.Action(&quot;Action&quot;, &quot;Controller&quot;, new { Id = id, code = code }, Request.Scheme);

I would expect the following output:

https://localhost:5000/Controller/Action?Id=&lt;id&gt;&amp;code=&lt;code&gt;

What I get is:

https://localhost:5000//Controller/Action?Id=&lt;id&gt;&amp;code=&lt;code&gt;

Notice the double slash after the host.  I am using MvcWithDefaultRoute in my startup.

---
#### Visual Studio Feedback System on 10/3/2019, 02:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jeffrey.Rutt on 10/10/2019, 05:33 AM: 

<p>I want to add some more information to this as the source of the problem has been located.  We are using Identity Server 4 and when setting the public origin, we had a trailing slash.  Once the trailing slash was removed, the urls generated no longer had a double slash after the host.</p><p>I still believe there is a bug for this issue as the host portion of the request was allowed to get into an invalid state and thus using Url.Action() built an invalid Url, but the work around is to not set a host with a trailing slash.</p>

#### Visual Studio Feedback System on 10/24/2019, 11:49 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
@rynowak Any idea why you would get a double-slash? Can it be the host having a double slash on it?

**Comment by javiercn** [comment]
In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem?

**Comment by javiercn** [comment]
We're closing this issue as we haven't seen community involvement and we need more information to reproduce the problem. If you have more details about the issue add a reply here with the new information and we'll re-evaluate the issue.
