### ISSUE TITLE
Question: Runing aspnetcore2.2 in netcore3

### ISSUE THREAD

**Issue by generik0** [aspnet/AspNetCore#17108]
Hi. This is a simple (maybe stupid) question.

I would like to upgrade to netcoreapp3.0 so I can run efcore3.0. EFCore runs NETStandard 2.1 that requires netcoreapp3.0. We would need to upgrade to use netvoreapp3.0.

But we are not ready to upgrade to aspnetcore3, because of our "special" stuff and also the ioc we use (maybe in 3 months or so we can do it).

I have not been able to run aspnetcore2.2 in netcoreapp3.0. Even with CompatibilityVersion.Version_2_2 on the mvc. Should i be able to do so. I.e. run "pure" 2.2 in netappcore3.0?

Thanks for you time. Br RIk

**Comment by blowdart** [comment]
No you can't. You need a 2.2 runtime for 2.2 to work.

**Comment by generik0** [comment]
@blowdart, oh. Maybe I am thinking to much like .net framework, where the nuget packages you installed loaded the app.net version.

This is unfortunate as the IoC dudes (simple, castle and prob others) are having issues with the new setup for aspnetcore...
Thanks for your time :-)
