### ISSUE TITLE
Blazor Wasm, Provide fetch options per message

### ISSUE THREAD

**Issue by aguacongas** [aspnet/AspNetCore#17127]
This functionality has been removed in 3.1-preview3.

### Is your feature request related to a problem? Please describe.
I use an IdentityServer4 but if I set the global option `WebAssemblyHttpMessageHandlerOptions.DefaultCredentials = FetchCredentialsOption.Include;` before authentication, requests to the IS4 server fail be cause responses don't include CORS credentials header.  
I can set the global option after authentication, but token renewal will be hard to implement.

### Describe the solution you'd like
Add a properties in HttpRequestMessage to set fetch options.

**Comment by javiercn** [comment]
@aguacongas thanks for contacting us.

I think this is likely a request for https://github.com/mono/mono we are now using their out-of-the-box client and those properties seem to be static as in https://github.com/mono/mono/blob/master/sdks/wasm/framework/src/WebAssembly.Net.Http/WasmHttpMessageHandler.cs

@SteveSandersonMS in case he has any further comments.

**Comment by aguacongas** [comment]
I opened the issue [17808](https://github.com/mono/mono/issues/17808) on moni repo

**Comment by javiercn** [comment]
@aguacongas thanks. 

Closing this issue as the underlying issue is tracked in the mono repo.
