### ISSUE TITLE
Blazor Wasm, application doesn't launch if WebAssembly.Net.Http is a dependencies

### ISSUE THREAD

**Issue by aguacongas** [aspnet/AspNetCore#17128]
### Describe the bug
The application fail to launch with error : 
> Uncaught (in promise) Can't find method WebAssembly.Runtime:GetDateValue

### To Reproduce
* Add the package **WebAssembly.Net.Http 3.0.2** as depency in your project.
* Create a custom `HttpMessageHandler` deriving from `WasmHttpMessageHandler`

```cs
public class CustomHttpHandler: WasmHttpMessageHandler
{
}
```

* Set up the DI to create a custom `HttpClient` using this custom `HttpMessageHandler`

```cs
services.AddTransient(p => new HttpClient(new CustomHttpHandler()));
```

* Inject an `HttpClient` in the MainLayout.razor

```
@inject HttpClient _httpClient
```

* Start the application

### Further technical details
- ASP.NET Core version 3.1-preview3
- 
``` bash
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview3-014645
 Commit:    b32d27f4b3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview3-014645\

Host (useful for support):
  Version: 3.1.0-preview3.19553.2
  Commit:  13f35c3d86

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- Microsoft Visual Studio Community 2019 Preview
Version 16.4.0 Preview 5.0

**Comment by javiercn** [comment]
@aguacongas thanks for contacting us.

We'll take a look at this issue and get back to you.

**Comment by javiercn** [comment]
@SteveSandersonMS can you take a look?

**Comment by javiercn** [comment]
@aguacongas I don't think this is an issue in Blazor but an issue with that package and Mono. I suggest you follow up with the mono folks for help.

**Comment by aguacongas** [comment]
Hum, I don't totaly agree as the error is throw in *_framework/blazor.webassembly.js*. Is this file come from mono ?

**Comment by javiercn** [comment]
The API is from Mono and the last time that package was built was 6 months ago. I imagine it _blazor.webassembly.js shows there as it's the script that boots mono, but that has nothing to do iwth us afaik.

It is very likely we picked up a new version of mono that might not be compatible with that package. I don't know who builds or what its github repo is, but it is not something related to Blazor itself, but about the package being incompatible with the latest mono bits.

**Comment by aguacongas** [comment]
@javiercn, mono's guys respond this not their side. IMO it's an incompatibility issue between the public package and the last build package you use in blazor and it could be fixed by itself when a new version of mono wasm framework will be released. However it had to be tracked somewhere.
