### ISSUE TITLE
Web API engine doesn't handle IAsyncEnumerable<int> type as expected.

### ISSUE THREAD

**Issue by ravimpatel** [aspnet/AspNetCore#17139]
I encountered an interesting behavior while exploring IAsyncEnumerable in an ASP.NET Web API project. Consider the following code samples:
Sample 1 (int array) returns {} as JSON result.

### To Reproduce
```

    // Code Sample 1
    [HttpGet]
    public async IAsyncEnumerable<int> GetAsync()
    {
        for (int i = 0; i < 10; i++)
        {
            await Task.Delay(1000);
            yield return i;
        }
    }


    // Code Sample 2
    [HttpGet]
    public async IAsyncEnumerable<string> GetAsync()
    {
        for (int i = 0; i < 10; i++)
        {
            await Task.Delay(1000);
            yield return i.ToString();
        }
    }


```
### Further technical details
- ASP.NET Core version : 3.0.0
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

- The IDE : VS 2019 Community

**Comment by SelvinPL** [comment]
I've tracked down the problem to 

https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/SystemTextJsonResultExecutor.cs#L79

if (value is IAsyncEnumerable<object> asyncEnumerable)


it's obviously because `IAsyncEnumerable<T>` where T is not a reference class is not `IAsyncEnumerable<object>`

**Comment by javiercn** [comment]
@ravimpatel thanks for contacting us.

We'll take a look and get back to you.

**Comment by javiercn** [comment]
> `if (value is IAsyncEnumerable<object> asyncEnumerable)`
> 
> it's obviously because `IAsyncEnumerable<T>` where `T` is **not a reference type** is not `IAsyncEnumerable<object>`

It's not about whether its a reference type or a value type. All types inherit from System.Object.

The issue might be, in any case that you can't cast IAsyncEnumerable<T> to IAsyncEnumerable<object> as they are not co-variant.

**Comment by SelvinPL** [comment]
> > `if (value is IAsyncEnumerable<object> asyncEnumerable)`
> > it's obviously because `IAsyncEnumerable<T>` where `T` is **not a reference type** is not `IAsyncEnumerable<object>`
> 
> It's not about whether its a reference type or a value type. All types inherit from System.Object.
> 
> The issue might be, in any case that you can't cast IAsyncEnumerable to IAsyncEnumerable as they are not co-variant.

it's about reference type ... covariance is not working for them

>Variance applies only to reference types; if you specify a value type for a variant type parameter, that type parameter is invariant for the resulting constructed type.

https://docs.microsoft.com/en-us/dotnet/standard/generics/covariance-and-contravariance

**Comment by javiercn** [comment]
I just verified that this is a bug.

**Comment by pranavkm** [comment]
This needs a feature in the underlying serializer: https://github.com/dotnet/corefx/issues/41358. The behavior is as expected for 3.x

**Comment by oliverjanik** [comment]
This needs to land ASAP, this is such a violation of principle of least surprise. I got bitten by using `IAsynEnumerable<JsonElement>` which is a struct.
