### ISSUE TITLE
Consider extra hints in scaffolded Identity MVC Logout template 

### ISSUE THREAD

**Issue by jeroenheijmans** [aspnet/AspNetCore#17132]
We are combining these tools:

- ASP.NET Core MVC Application
- Scaffolded Identity pages, at least `Logout.cshtml`
- IdentityServer4 for OAuth2 and OIDC

Our typical scenario:

1. Suppose user is logged in with Implicit Flow in a client app
2. User logs out, our Angular library directs the user to `/connect/endsession` with a proper `id_token_hint` and `post_logout_redirect_uri`
3. IdentityServer4 neatly ends the session and redirects the user to `GET /identity/Account/Logout` with a `logoutId` query string parameter

- Result: scaffolded identity page says "You're logged out!" but also you're still logged in, seeing your username top-right in the scaffolded Identity page. You're also not redirected to the client again.
- Expected: unsure, see below.

In the end, I expect that all the proper sign-out handling is done (actual signout and clearing cookie, and other stuff). There's [a good IdentityServer4 doc](https://identityserver4.readthedocs.io/en/latest/topics/signout.html) about what can/should happen.

Equally important info is the (completely different) way [IdentityServer4's quickstart/template handles logout](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/d847cd75cae53cc2d31fb5d2ff4a943f9befc739/Quickstart/Account/AccountController.cs#L171-L222), as well as that they differentiate between [LoggedOut view](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/master/Views/Account/LoggedOut.cshtml) and a [LogOut view](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/master/Views/Account/Logout.cshtml).

However, I understand that's possibly beyond the goal of the Identity Template? So I guess I expect from the templates:

1. differentiation between a _logout_ view, and a _loggedout_ view
2. hints and guidance in comments in the template about what else you might need in your `Logout` GET/POST methods and views if you'd be using OIDC, probably a rather common scenario

Hope this makes sense, and that I grasped the right problem. If I need to clarify anything let me know.

**Comment by blowdart** [comment]
You're mixing both asp.net login and angular based logins? Considering the identity template has no concept of your angular duplication it's not unsurprising this is happening. This does feel beyond the scope of identity at this point.

**Comment by jeroenheijmans** [comment]
Hmm, they're not so much "Angular logins", but ASP.NET Core Identity users via the suggested [IDS4 and ASP.NET Core Identity bridge](http://docs.identityserver.io/en/latest/quickstarts/8_aspnet_identity.html). Since I was using that approach, it made some sense to me to also use the Identity Scaffolding for identity related views. 

Nearly all the views and flows for users that I got from the scaffolded identity page models were working, the only point of confusion so far occurred at the log(ged)out view(s), as they were giving some trouble in my flows.

From your comment I gather this is not a recommended approach? That would be a shame, because as mentioned all the scaffolded views (registering accounts, external logins, profile page, password resets, etc, etc) all work _perfectly well_ with IdentityServer4.

If it would help I could set up a sample repo to demonstrate the approach I'm talking about, but if you feel like this issue isn't in the right place or worthwhile, we could also close it.

PS. Regardless of the above, I'd still be curious about the missing distinction between "LogOut" and "LoggedOut" views in the templates. The cshtml in the template will show a text "You have successfully logged out" regardless of whether you _are_ logged out, which seems like a mistake to me?

**Comment by blowdart** [comment]
The identity "forms" (can't think of a better way to describe them) aren't angular aware, even in our own SPA templates they're still classic MVC.

Did you try forcing the logout in the controller endpoint?

**Comment by jeroenheijmans** [comment]
Thanks again for the reply! I have a feeling I'm not explaining myself correctly, but presume that most likely means that _I_ am not _understanding_ the templates too well. Since there's no real other activity I'll go ahead and close this issue, and look for my solution by reading the source and docs some more (or perhaps by resorting to the IDS4 UI Quickstart instead).

Thanks for the interaction 👍
