### ISSUE TITLE
Error while setting CI pipeline with ASPNETCore 3.0

### ISSUE THREAD

**Issue by aksh-h** [aspnet/AspNetCore#17133]
##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
```
##[debug]Processed: ##vso[task.issue type=error;]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
##[debug]task result: Failed
##[error]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\src\AzureDevOpsDemoBuilder\AzureDevOpsDemoBuilder.csproj
##[debug]Processed: ##vso[task.issue type=error;]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\src\AzureDevOpsDemoBuilder\AzureDevOpsDemoBuilder.csproj
```

You can see the pipeline here
[AzureDevOps Demo Generator](https://vstsdemodata.visualstudio.com/AzureDevOpsDemoGenerator/_build?definitionId=99&_a=summary)

**Comment by javiercn** [comment]
@aksh-h thanks for contacting us.

This issue is not specific to ASP.NET Core. You would get a better and faster response in the SDK repository at https://github.com/dotnet/core-sdk

**Comment by aksh-h** [comment]
@javiercn  Thanks
