### ISSUE TITLE
Best way to catch whenever a user has signed in successfully then do some custom logic

### ISSUE THREAD

**Issue by thiennn** [aspnet/AspNetCore#17147]
There are commons need to hook into the SignedIn event to do some extra custom logic, for example handle shopping cart, audit log ...

Previously I create a custom SignInManager and override SignInAsync, it worked as expected. But recently on ASP.NET Core 3  I discover that the SignInAsync is not being called when users login with username and password. Look at the SignInManager source code https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Core/src/SignInManager.cs, I see there are a lot of  signin methods: SignInWithClaimsAsync, ExternalLoginSignInAsync, DoTwoFactorSignInAsync.

What is the best way to catch whenever a user has signed in successfully then do some custom logic? Regardless what method they signing in

**Comment by lkubis** [comment]
@thiennn If you look at the SignInManager again, you can see, that all of these methods (SignInAsync, ExternalLoginAsignInAsync, PasswordSignInAsync, and SignInOrTwoFactorAsync) end with a call to **SignInWithClaimsAsync**. So I guess this would be good place to override and handle your custom logic.

**Comment by thiennn** [comment]
Yes, actually it is. Thanks @lkubis
