### ISSUE TITLE
How can I host multiple Blazor(WebAssembly) clients in one AspNetCore site

### ISSUE THREAD

**Issue by liyanjie8712** [aspnet/AspNetCore#17165]
I am trying to host two Blazor(WebAssembly) clients with different route in one AspNetCore site,is there any way to do this?

Could I embed the blazor client files (include blazor dlls) in to different dll,then use EmbeddedFileProvider to provide it. Is this the best way?

**Comment by javiercn** [comment]
@liyanjie8712 thanks for contacting us.

This is not something that we currently support but something that we might look to support in the future.

Thanks.
