### ISSUE TITLE
How to invalidate precompiled views cache after adding application part at runtime

### ISSUE THREAD

**Issue by DmitrySikorsky** [aspnet/AspNetCore#17171]
Hi,

I'm trying to implement loading/unloading extensions at runtime. Currently, I can load/unload the assemblies containing controllers with no problems, I'm using IActionDescriptorChangeProvider to invalidate corresponding cache.

Could you help me to find a way to invalidate the views cache? Because, if I add the application parts on startup views are resolved. But if I do that later, views can't be found.

I hope there should be something similar.

Thank you very much.

**Comment by javiercn** [comment]
@DmitrySikorsky thanks for contacting us.

`IActionDescriptorChangeProvider` should be the wait to go, you can look in the source-code at pageactiondescriptor provider, they are just actiondescriptor providers.

**Comment by javiercn** [comment]
We've discussed this within the team. This is not something that you can do easily, as application parts need to be loaded before DI gets configured. This is not something that we plan to change in the near future, as it requires a big investment.
