### ISSUE TITLE
Question: Blazor NavigationManager.LocationChanged Async

### ISSUE THREAD

**Issue by chassq** [aspnet/AspNetCore#17178]
In general what would be the best method (if any) to call awaitable methods from NavigationManager.LocationChanged, since NavigationManager.LocationChanged is not async? 

Is wrapping the awaitable Task call into Task.Run/Task.WaitAll acceptable? For example something like:

```
var task = Task<bool>.Run(async () =>
{
   //Call await method here 
    return false;
});

Task.WaitAll(task);
var retVal = task.Result;
```

**Comment by mrpmorris** [comment]
You can declare your handler method as `async Task`. DotNet won't await the result, but your method will be able to `await` other calls.

```
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var p = new Parent();
            p.SomeEvent += (s, e) => Console.WriteLine("Observer 1");
            p.SomeEvent += AsyncHandler;
            p.SomeEvent += (s, e) => Console.WriteLine("Observer 2");

            p.TriggerSomeEvent();
            Console.ReadLine();
        }

        public static async void AsyncHandler(object sender, EventArgs e)
        {
            await Task.Delay(1000);
            Console.WriteLine("Async observer");
        }
    }

    public class Parent
    {
        public event EventHandler<EventArgs> SomeEvent;

        public void TriggerSomeEvent()
        {
            SomeEvent?.Invoke(this, EventArgs.Empty);
        }
    }
```

Output

1. Hello world!

**Comment by javiercn** [comment]
@chassq thanks for contacting us.

There are patterns around this. The best option you have is to encapsulate everything with in a task returning method that takes in a cancellation token as a parameter. Then register a handle in your LocationChange method and do something like this

```charp
if(_currentTask != null && !_currentTask.IsCompleted){
   _currentCancellation.Cancel();
}
_ currentCancellationToken = new ...
_currentTask = InvokeMyAsyncHandler(_currentCancellationToken)
```

In general, do not use async void, and instead capture the existing task within your component and use the cancellation token to stop the work if for example another navigation gets triggered in between.

I hope this helps.

**Comment by chassq** [comment]
Thank you very much!
