### ISSUE TITLE
cshtml support

### ISSUE THREAD

**Issue by JulienM28** [aspnet/AspNetCore#17188]
Using Visual Studio 2019 and ASP .Net core 3.0,
I have a cshtml view containing this code:

````html
  <input asp-for="LastName" class="form-control activable" placeholder="Nom" @(Model?.LicenseId= =null ? "disabled" : string.Empty) />
````

this part  
````csharp
@(Model?.LicenseId= =null ? "disabled" : string.Empty)
````

produces an error in visual studio
The tag helper 'input' must not have C# in the element's attribute declaration area.

but it compiles and work perfectly.

notice the = = whiwh is a == but visual studio if modifying it when i use format.

**Comment by javiercn** [comment]
@JulienM28 thanks for contacting us.

I believe the space between = and = is significant, so seems like formatting is altering the semantics here?

@NTaylorMullen @ajaybhargavb any ideas?

**Comment by NTaylorMullen** [comment]
Hey @JulienM28, C# in the attribute / tag declaration is unsupported for TagHelpers. However, I believe you can get the same functionality by changing your code to the following:

```CSHTML
  <input asp-for="LastName" class="form-control activable" placeholder="Nom" disabled="@(Model?.LicenseId == null)" />
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
