### ISSUE TITLE
[Blazor] Creating a new class puts it in a namespace with an invalid name

### ISSUE THREAD

**Issue by Quickz** [aspnet/AspNetCore#17186]
### Issue
When a new class is created and it's put inside a namespace, the generated namespace name doesn't replace the spaces in it's name. Instead of having a namespace with a name "Memory_Card_Game" it has a namespace of "Memory Card Game" which causes a compile time error unless fixed manually.

### Reproduction steps
 - Create a new Blazor WebAssembly app with a name "Memory Card Game"
 - Add a new .CS file

The newly created file should be in a namespace equal to the project name without the spaces replaced with underscores.

![bug-report](https://user-images.githubusercontent.com/17292064/69017683-446bd380-09b1-11ea-9a22-d299e3ac585b.gif)

### Further technical details
 - Visual Studio version: 16.3.9
 - Project I encountered the issue in https://github.com/Quickz/Memory-Card-Game

**Comment by javiercn** [comment]
@Quickz thanks for contacting us.

We'll take a look and get back to you. This is either an issue in the item template or a tooling issue.

**Comment by pranavkm** [comment]
This likely looks like a tooling issue. If you generate a new project with a whitespace in it, `dotnet new` produces a `RootNamespace` node with the name transformed. I'd recommend using the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) to report this.
