### ISSUE TITLE
Failed to load coreclr

### ISSUE THREAD

**Issue by skyridder** [aspnet/AspNetCore#17187]
Hi, Dear all,
I`m using .net core 3 in iis with IIS AspNetCore Module V2, it works fine until last Saturday.

Here is the event log:
[error event log.txt](https://github.com/aspnet/AspNetCore/files/3856919/error.event.log.txt)

It seems that application failed to shutdown and failed to start later. Does this issue happen due to uncatched internal error?

**Comment by Tratcher** [comment]
Possibly related to https://github.com/aspnet/AspNetCore/issues/17063 @jkotalik

**Comment by skyridder** [comment]
Laterly I find out that server cpu and memory is full. Sql takes up a lot of resource. So I think something wrong with SQL. Thanks
