### ISSUE TITLE
IFormFile not load type Microsoft.AspNetCore.Http.Internal.FormFile' from assembly 'Microsoft.AspNetCore.Http 3.0'

### ISSUE THREAD

**Issue by barfootCBarragan** [aspnet/AspNetCore#17185]
When using IFormFile I am getting this error at running time:

Could not load type 'Microsoft.AspNetCore.Http.Internal.FormFile' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

```C#
<ItemGroup>
<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="3.0.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0" />
<PackageReference Include="Microsoft.Extensions.Http" Version="3.0.0" />
<PackageReference Include="Microsoft.Net.Http.Headers" Version="2.2.0" />
</ItemGroup>

using Microsoft.AspNetCore.Http.Internal;
IFormFile f = new FormFile(memoryStream, 0, memoryStream.Length, "test", "test.pdf");

IFormFile not load type Microsoft.AspNetCore.Http.Internal.FormFile' from assembly 'Microsoft.AspNetCore.Http 3.0'
   at AgencyAgreementExpiryService.Pipeline.Agreement.Process.GetPdfProcess.<ExecuteAsync>d__3.MoveNext() in C:\AgencyAgreementExpiryService\AgencyAgreementExpiryService\AgencyAgreementExpiryService.Pipeline\Agreement\Process\GetPdfProcess.cs:line 62
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at AgencyAgreementExpiryService.Pipeline.Agreement.Process.GetPdfProcess.ExecuteAsync(AgreementParameters parameters)
   at BT.AgencyAgreementExpiryService.Pipeline.LogicPipeline`1.<ExecuteAsync>d__2.MoveNext() in C:\AgencyAgreementExpiryService\AgencyAgreementExpiryService\AgencyAgreementExpiryService.Pipeline\LogicPipeline.cs:line 29

When exploring the class, it is pointing to SDK 2.2 which is the latest available version of microsoft.aspnet.core

`#region Assembly Microsoft.AspNetCore.Http, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.http\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.dll
#endregion

using System.IO;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;

namespace Microsoft.AspNetCore.Http.Internal
{
    public class FormFile : IFormFile
}
```
Is there any other library that I am missing?

- ASP.NET Core version 3.0
- VS 2019

**Comment by pranavkm** [comment]
@barfootCBarragan mixing versions of ASP.NET Core isn't supported and would explain this specific error you're seeing:

```xml
<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="3.0.0" />
```

Is there a reason you're targeting the 3.0 version of the `Microsoft.AspNetCore.Http.Features` package?

**Comment by barfootCBarragan** [comment]
I have deleted Microsoft.AspNetCore.Http.Features and still having the problem:

Library class where I am using IFormFile:
<ItemGroup>
    <PackageReference Include="GraphQL.Client" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.0.0" />
  </ItemGroup>

Main Web Application
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.0.0" />
    <PackageReference Include="Microsoft.Net.Http.Headers" Version="2.2.0" />
    <PackageReference Include="Seq.Extensions.Logging" Version="4.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
  </ItemGroup>

**Comment by pranavkm** [comment]
@barfootCBarragan again, is there a reason you're mixing 2.2 versions of packages with 3.0? If you're attempting to upgrade to 3.0, please follow the migration guide: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio.

**Comment by jkotalik** [comment]
As @pranavkm mentioned, mixing 2.2 and 3.0 dependencies like this isn't supported. Closing.
