### ISSUE TITLE
Extending Microsoft.AspNetCore.Mvc.RazorPages.Page makes conflict with Layout and Partial views

### ISSUE THREAD

**Issue by houmamwazzeh** [aspnet/AspNetCore#17189]
I am trying to extend `Microsoft.AspNetCore.Mvc.RazorPages.Page` to add more functionalities to  `.cshtml` files in a razor pages web project. However, I get compile errors related to `_Layout` and partial views, when using `@inherits` in `_ViewImport`.

### Reproduction steps
**(1.)** Create new ASP.NET Core Web Application with Razor Pages. Then create the class `CustomRazorPage` as follows:
```c#
public abstract class CustomRazorPage : Microsoft.AspNetCore.Mvc.RazorPages.Page
{
    // ....
}
```
**(2.)** Add `@inherits` to `_ViewImport`:
```c#
@inherits WebApplication1.Razor.CustomRazorPage
```
**(3.)** As a result, we get the following compile errors:
```c#
1>Pages\Shared\_Layout.cshtml(6,13,6,21): error CS0103: The name 'ViewData' does not exist in the current context
1>Pages\Shared\_Layout.cshtml(35,14,35,24): error CS0103: The name 'RenderBody' does not exist in the current context
1>Pages\Shared\_Layout.cshtml(49,7,49,20): error CS0103: The name 'RenderSection' does not exist in the current context
```
**(4.)** To fix the previous errors, add the following to the top of `_Layout.cshtml`
```c#
@inherits Microsoft.AspNetCore.Mvc.Razor.RazorPage<TModel>
```
**(5.)** Despite of step (4), partial views produce compiler errors:
```c#
Error	CS0103	The name 'Model' does not exist in the current context	.......
```

I'd already created the repository [aspcore-extend-razor-page-issue](https://github.com/houmamwazzeh/aspcore-extend-razor-page-issue) which describes the issue.

**Comment by javiercn** [comment]
@houmamwazzeh thanks for contacting us.

We'll take a look and get back to you.

**Comment by pranavkm** [comment]
@houmamwazzeh, a Razor view, which is a cshtml file that does not have an `@page` directive, must derive from `RazorPage<T>` (as you noted for the `_Layout`.). The generated code expects this. 

Placing an `@inherits` in a folder that contains Razor Pages and Views is going to result in the compiler error that you're seeing. One way to proceed would be to refactor your application to move all of the views, likely everything in https://github.com/houmamwazzeh/aspcore-extend-razor-page-issue/tree/master/WebApplication1/Pages/Shared, to a */Views/Shared* folder. This should ensure views are discovered but they do not pick up the `@inherit` from */Pages/_ViewImports.cshtml*.

**Comment by javiercn** [comment]
We are closing this issue as the question has been answered. If you still run into issues after following the guidance, feel free to comment on this issue and we will re-evaluate it.

**Comment by houmamwazzeh** [comment]
Thanks @pranavkm, @javiercn , that was helpful. 

My goal was to:
- Use a partial view file `_CategoryForm` for 2 razor pages (Create.cshtml and Edit.cshtml). And
- Extend the functionality of `Microsoft.AspNetCore.Mvc.RazorPages.Page`.

But, it turns out that we have 2 options to overcome this issue:
1. Either by moving the partial views to `/Views/Shared` folder to isolate them (as mentioned above).
2. Or explicitly add `@inherits RazorPage<T>` at the top of partial views.

But I am still wondering if this issue is a limitation that we cannot overcome! Or there might be a better solution in the future. Because in my case, it is better to keep the partial view near the pages.
