### ISSUE TITLE
Adding a navigation list of property (with composite id) to identity user cause an error

### ISSUE THREAD

**Issue by MohammadElKhatib** [aspnet/AspNetCore#17196]
I am creating an application with ASP.Net Core 3.0 and I am facing an issue when creating an object with composite keys, where I have one of these keys as UserId foreign key for the identity user.

but once trying to login an error appears as:

> InvalidOperationException: The entity type 'ManOfTheMatchPrediction' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'.

Here is my object class:

```
public class ManOfTheMatchPrediction
    {
        public int ManOfTheMatchId { get; set; }
        public string UserId { get; set; }
        public int PlayerId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime LastModifiedDate { get; set; }

        [ForeignKey("UserId")]
        public virtual FBPredictorUser User { get; set; }

        [ForeignKey("PlayerId")]
        public virtual Player Player { get; set; }
    }
```

and here is my identity user class:

```
public class FBPredictorUser : IdentityUser
    {

        public virtual ICollection<ManOfTheMatchPrediction> ManOfTheMatchPredictions { get; set; }
    }
```

and here is the DBContext configurations

```
public DbSet<ManOfTheMatchPrediction> ManOfTheMatchPredictions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ManOfTheMatchPrediction>().ToTable("ManOfTheMatch_Prediction");
            modelBuilder.Entity<ManOfTheMatchPrediction>().HasKey(e => new { e.ManOfTheMatchId, e.UserId });
        }
```

note that the relationship with the player is almost the same and is not causing any errors.

once I remove ICollection<ManOfTheMatchPrediction>  from the identity user the error disappear 

Any Ideas?!

**Comment by blowdart** [comment]
Have you checked the [schema customisation documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.0)? Does it cover your case?

**Comment by MohammadElKhatib** [comment]
@blowdart I did check that documentation and I made some changes to my code but also the same issue.

find below a repo of the project:

https://github.com/MohammadElKhatib/FBPredictor

**Comment by blowdart** [comment]
@ajcvickers One for you

**Comment by MohammadElKhatib** [comment]
@ajcvickers I tested the same on Core 3.0.1 the recently released version on windows and i am getting the same issue.
please, can you confirm if it is a bug?
or am I am configuring something wrong?

**Comment by ajcvickers** [comment]
@MohammadElKhatib Looks like the code has two different `DbContext` types with two different models. You'll need to override `OnModelCreating` in your `ApplicationDbContext` and configure the Identity model to understand or ignore the `ManOfTheMatchPredictions` navigation, as described in the documentation linked above.
