### ISSUE TITLE
“#” character in the csproj/sln path name cases a "The partial view not found" in Razor class library!

### ISSUE THREAD

**Issue by SamTheDev** [aspnet/AspNetCore#17192]
### Describe the bug
This was initially raised [here](https://stackoverflow.com/questions/58827705/sign-cannot-be-in-csproj-sln-pathname-when-debugging-razor-class-library-in). Basically, if your asp.net core project reference an RCL project, and the solution path has a "#" character somewhere in it, then the partial views from the RCL won't be resolved!

### To Reproduce
Source :[ @Zoka question on #SO](https://stackoverflow.com/questions/58827705/sign-cannot-be-in-csproj-sln-pathname-when-debugging-razor-class-library-in)

- Clone this sample repo https://github.com/zoka-cz/CSharpDirNameProblem.git into any directory you want (iteration 1 - ensure '#' is not anywhere in the pathname like **c:\tmp\CSharpDirNameProblem\** -- iteration 2 - ensure the '#' is in the directory name e.g. **c:\tmp\C#\CSharpDirNameProblem\**).
- Open solution **src\CSharpDirNameProblem.sln** 
- Set **WebApplication1** as the startup project and run the solution.
- Click on the About.
- Iteration 1 will run whithout issues 
- Iteration 2 will raise an exception in the browser.

### Further technical details
- Stack 
> InvalidOperationException: The partial view 'Text' was not found. The following locations were searched: /Views/Home/Text.cshtml /Views/Shared/Text.cshtml /Pages/Shared/Text.cshtml
> Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, object model)
> Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
> Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
> AspNetCore.Views_Home_About.ExecuteAsync() in About.cshtml
> +
> <h3>@ViewData["Message"]</h3>
> Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
> Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
> Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
> Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
> Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
> Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
> Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync<TFilter, TFilterAsync>()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
> Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

- ASP.NET Core version
3.0.100
Visual studio 2019 community 
Windows 10 1903

**Comment by pranavkm** [comment]
Thanks for the issue report @SamTheDev. This is a dup of https://github.com/aspnet/AspNetCore/issues/14501 that is being tracked to be fixed in the next major release.
