### ISSUE TITLE
Async in Razor Page @functions

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17203]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/811540/async-in-razor-page.html)._

---
I'm getting the following error in my Razor Page.

[! [enter image description here] [1]] [1]

So I changed it.

[! [enter image description here] [2]] [2]

Now the code will run but I get warnings.

&gt;1&gt;obj\Debug\netcoreapp3.0\Razor\Pages\Areas.cshtml.g.cs(256,200,256,202): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.  
&gt;1&gt;obj\Debug\netcoreapp3.0\Razor\Pages\Areas.cshtml.g.cs(282,200,282,202): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

At this point, I have no idea what Razor Pages are expecting from me.

Here is my complete `@functions` section.
```
@functions
    {
        async System.Threading.Tasks.Task RenderArea(Area area)
        {
            <tr>
                <td class="@area.CssClass">
                    <p class="compact">
                        <a href="/Area/@area.Id" class="font-weight-bold">@area. Title</a>
                        @if (!string. IsNullOrWhiteSpace(area. Description))
                        {
                            <br />@area. Description
                        }
                    </p>
                </td>
                <td class="@area.CssClass">
                    <img src="~/images/Edit.png" class="edit-area button-img" data-id="@area.Id" title="Edit" />
                    <img src="~/images/Delete.png" class="delete-area button-img" data-id="@area.Id" title="Delete" />
                </td>
            </tr>
        }
    }
```

[1]: https://i.stack.imgur.com/p6SPa.png
  [2]: https://i.stack.imgur.com/eVdnF.png

---
#### Visual Studio Feedback System on 11/7/2019, 10:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 11/8/2019, 02:00 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Hello, my bet is that where you're calling `RenderArea` you're not doing `@await RenderArea(...)`.

**Comment by javiercn** [comment]
@NTaylorMullen can this simply be because there is no await in his code? I believe that's the reason and the only thing to do here is to remove 'async' and return Task.CompletedTask.

That will fix the warnings and respect the signature.

**Comment by NTaylorMullen** [comment]
Ehh the ~/ in the image tags should resulted in awaits because those are backed by TagHelpers. I'd need to see more of the project to be certain
