### ISSUE TITLE
Putting open parenthesis '(' next to an at symbol '@' crashes visual studio

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17206]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/589293/putting-open-parenthesis-next-to-an-at-symbol.html)._

---
Like the title says visual studio completely crashes when I put these symbols together '@(' I am working in a .razor file.

---
#### dalankelsch on 5/30/2019, 09:38 AM: 

I took a windows update an it fixed this problem
#### Visual Studio Feedback System on 5/30/2019, 08:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### dalankelsch on 5/31/2019, 10:33 AM: 

The issue came back even though I had taken that update, so I don't know why it went away for a little bit there.
#### Visual Studio Feedback System on 7/19/2019, 00:11 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem? Ideally also indicate at what line and column to insert the characters to trigger the VS crash.

@NTaylorMullen the internal ticket has attachments with additional information that will likely help you troubleshoot the issue. I can assist a bit if you need help into looking at it.

**Comment by Rick-Anderson** [comment]
I can't repo with VS community 20019 Version 16.3.9

```
(@page
(@model PrivacyModel
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>(@ViewData["Title"]</h1>

<p> (@__o) Use this page to detail your site's privacy policy.</p>

```

**Comment by NTaylorMullen** [comment]
I believe this was fixed because I can no longer reproduce either
