### ISSUE TITLE
Numerous missing class descriptions

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17204]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/750476/numerous-missing-class-descriptions.html)._

---
I noticed that numerous classes are missing a description:

- **DefaultHttpContext**
- **HttpContextAccessor**
- **HttpContextFactory**
- **HttpMethodOverrideExtension**
- **HttpMethodOverrideOptions**
- **HttpMethods**
- **HttpRequestExtensions**
- **HttpResponse**
- **HttpsRedirectionMiddleware**
- **WebHostBuilderHttpSysExtensions**

I also noticed that there is no period at the end of the description for the **HttpsRedirectionOptions** class; I recommend being consistent.

---
#### Visual Studio Feedback System on 9/27/2019, 00:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/27/2019, 01:30 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Dairai** [comment]
I am willing to work on this if it's still available.

**Comment by Rick-Anderson** [comment]
Related #17205
@Dairai looks like it's available.

**Comment by anurse** [comment]
@Dairai we'd love a PR for this!

**Comment by Dairai** [comment]
I will take it then. You can assign me to it.

**Comment by Mika-net** [comment]
This issue looks like it should be closed
