### ISSUE TITLE
Blazor OnInitAsync method not rendering asynchronously when page called by GET

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17207]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/676312/blazor-oninitasync-method-not-rendering-asynchrono.html)._

---
Blazor Preview 7

Consider the bellow attached Server-side Blazor page.
When accessing the page by GET (e.g. by enetring  URL  localhost://foo:5000 in the browser or pressing F5 when on foo page) then I would expect seeing immediately the &quot;Loading...&quot; text (first rendering called) and after 3 secs the &quot;Done&quot; text (second render called). Instead the browser waits for completing the asynchronous task and only then it displayes the page already with the &quot;Done&quot; text.

@page &quot;/foo&quot;
&lt;p&gt;Status: @m_status&lt;/p&gt;

@code {
    private string m_status = &quot;&quot;;

protected async override Task OnInitAsync()
    {
        m_status = &quot;Loading...&quot;;
        await Task.Delay(3000);

m_status = &quot;Done&quot;;
        await base. OnInitAsync();
    }
}

---
#### Visual Studio Feedback System on 8/5/2019, 01:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/5/2019, 01:56 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
It's fairly likely that you have pre-rendering on. Blazor will wait for the pre-rendering to timeout or complete before it initiates rendering. If that's not the case, could you share a minimal repro app and we could investigate this further.

**Comment by javiercn** [comment]
The behavior here is by design. Blazor waits until all asynchronous code is rendered to produce a menaingful render of the page.
