### ISSUE TITLE
Modal popup not showing in first click in razor page

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#17202]
_From @prasanthjayaprakash on Monday, November 18, 2019 5:29:57 PM_

Please help me  , when page is loading i can see the all list  items. But i am clicking  the more button on the first time or any the popup is not showing in  the first time.  Again will click it is working. it is  need a double click.
<button @onclick="(e=> SelectProduct(product.Id))" data-toggle="modal" data-target="#productModal"
                            class="btn btn-primary">

@if (selectedProduct != null)
{
    <div class="modal fade" id="productModal" tabindex="-1" role="dialog" aria-labelledby="productTitle" aria-hidden="true">

_Copied from original issue: dotnet/core#3832_

**Comment by javiercn** [comment]
@prasanthjayaprakash thanks for contacting us.

In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem?

**Comment by javiercn** [comment]
We're closing this issue as we haven't seen community involvement and we need more information to reproduce the problem. If you have more details about the issue add a reply here with the new information and we'll re-evaluate the issue.
