### ISSUE TITLE
[Razor Pages] String interpolation for @page directive override routes

### ISSUE THREAD

**Issue by cbrit** [aspnet/AspNetCore#17216]
I had the idea to save all of my routes in a static class of constants like so:

```
static class Routes
{
    public const string Index = "/index";
    public const string Login = "/account/login";
    public const string Logout = "/account/logout";
    public const string Register = "/account/register";

    // etc. 
}
```

The idea was to have the route defined in one place and then if I even need to change a route, I will only have to change it in one place. For example, if I have multiple handlers that redirect to the login page, changing the login route would require me to change it at the `@page` directive, and in any IActionResult-returning methods that redirect to the login route (which could exist in many authentication-required pages). 

First, let me know if that's just a stupid idea. I'm pretty new to ASP .NET Core.

If not, the feature I am requesting is that *string interpolation or some other kind of value passing mechanism would be possible with a page directive*. Visual Studio tells me this syntax is correct but when I try to compile it says "the 'page' directive expects a string surrounded by double quotes.".

```
@page @Routes.Index
```

I also tried the following and it does not work:

```
@page $"{Routes.Index}"
```

Could this be a useful feature for code-maintainability? 

EDIT: Typos.

**Comment by javiercn** [comment]
@cbrit thanks for contacting us.

Unfortunately what you are trying to achieve is not possible. Routes are backed by .NET Attributes, which require all parameters to be compile time constants. For that reason, you can't use things like string interpolation in them, as that would require the information for the attribute to be defined at runtime, which is not possible in .NET.
