### ISSUE TITLE
Blazor Server prerendering with parameters support

### ISSUE THREAD

**Issue by YoanaDimitrova-kpmg** [aspnet/AspNetCore#17226]
@mkArtakMSFT @pranavkm @rynowak I have an existing ASP.NET Core 3 project and I am trying to incorporate Razor components using Server-side Blazor. Components with no parameters work but obviously they are of limited use (dare I say completely useless). 

I get an exception when incorporate a component, e.g.:
```
 <Status>@(await Html.RenderComponentAsync<StatusComponent>(
                       RenderMode.ServerPrerendered,
                       new { AssignedName = @Model.AssignedToName }))
</Status>
```

This is an existing [issue ](https://github.com/aspnet/AspNetCore/issues/14433) that is marked as resolved but I still get 'System.InvalidOperationException: Server components with parameters are not supported.' I am on .NET `Version: 3.1.100-preview3-014645`, Win x64, VS latest preview.

Is this going to be resolved soon (e.g. official 3.1.0 release) or it might not be supported at all? We don't want to migrate a whole ASP.NET app to Blazor directly but would rather migrate our JS components to Blazor at first.

Am I correct thinking that currently the only way to use Blazor is to migrate an ASP.NET app to Blazor server-side and convert all Razor pages to Blazor pages? Presumably this will allow using Blazor components with parameters?

**Comment by javiercn** [comment]
@YoanaDimitrova-kpmg thanks for contacting us.

This is a 3.1 feature, here is a working sample on how to use it, you can run it with the latest preview.
Make sure you lock in the SDK version by adding a global.json file with `dotnet new globaljson --sdk-version 3.1.100-preview3-014645`

[ComponentWithParametersSample.zip](https://github.com/aspnet/AspNetCore/files/3864356/ComponentWithParametersSample.zip)

If you still have problems, please comment on this issue and we will re-evaluate it.

**Comment by YoanaDimitrova-kpmg** [comment]
@javiercn Thanks for the response but that's not what I need unfortunately. So, your sample looks a lot like an instance of the Razor template for a server-side app, I think that worked even without upgrading to the latest preview. 
What I need however, is to be able to add a Razor component to an existing MVC app with a call to RenderComponent (see my previous comment). This still does _not_ work even with the preview version you suggested (I was already on that version). If you look at the issue I linked you will see that that is why the previous issue was opened as well. I am guessing a lot of people are trying to add Razor components to their existing apps without migrating their whole solution to a Blazor app. 

If you need further info on what I am doing I can provide a cut down version of our app?

**Comment by javiercn** [comment]
@YoanaDimitrova-kpmg there is no funcional difference between adding a single component or multiple ones.

Both things should work. I used the top level one because it’s simple.

If you provide a minimal repro that would help.
