### ISSUE TITLE
AddMethhods programmatically

### ISSUE THREAD

**Issue by BolatovAlau** [aspnet/AspNetCore#17222]
Can we create methods programmatically:
Example:
```
for(int i=0;i<10;i++)
{
   [Route("test"+i)]
   public int Method{i} (int i)
   {
        return i;
   }
}
```

**Comment by javiercn** [comment]
@BolatovAlau thanks for contacting us.

It looks like this is a general question that has nothing to do with ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow.

You can probably look into some templating language like https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019
