### ISSUE TITLE
Remove ViewBag feature completely

### ISSUE THREAD

**Issue by sefacan** [aspnet/AspNetCore#17225]
Developers use ViewBag for convenience, but I think it contributes greatly to unwanted performance issues. Force us to use ViewData and Model if necessary.

Thanks.

**Comment by javiercn** [comment]
@sefacan thanks for contacting us.

Unfortunately we aren't likely to do this ever. When we write frameworks we need to make trade-offs and sometimes we build features (like ViewBag) that improve the experience at the cost of performance.

We understand your concerns, but at the same time we value the ease of use ViewBag provides. If you have problems with it in your specific scenario, we would love to see some data on how much it affects performance.

If its significant in any of your scenarios, you could write your own Analyzer to prevent its usage.

I understand this is not probably the answer you expect, but we value more not breaking existing customers than taking out features, even if they are not as good as other alternatives with regards to some specific trait.

Hope that helps.
