### ISSUE TITLE
Threads stuck on HttpRequestStream.Read

### ISSUE THREAD

**Issue by kevingosse** [aspnet/AspNetCore#17235]
We're running into an issue in a Kestrel web application (using Microsoft.AspNetCore.Server.Kestrel 2.2.0) where some threads are stuck on the callstack:

```
[HelperMethodFrame_1OBJ: 00007f8357234f30] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[], Int32, Int32)
**user code**
```

We have our own handling for timeouts. The task returned to aspnetcore is roughly:

```C#
await Task.WhenAny(TimeoutLogic(), RequestProcessingLogic());
```

All the stuck threads are in the "RequestProcessingLogic" part, for requests that timed out. Not all timeouts result in a stuck thread, this is a random occurrence.

I've captured a memory dump and tried to dig further to understand why those threads are stuck:
 - The pipe `Http1Connection.RequestBodyPipe` keeps a reference to the stuck task awaiter callback in its `_readerAwaitable` field. So it seems that the pipe wasn't completed/reset. 
 - The `_body` field of the `HttpRequestStream` instance on which the read operation is performed is null, so `StopAcceptingReads` was called
 - `HttpProtocol._requestAborted` is true, `Http1Connection._requestAborted` is 0
 - It seems that `Http1Connection.Reset` was called (`_requestProcessingStatus` is RequestPending, `Method` is None, etc...)

I'm not sure where to look next. I've tried reproducing the issue locally but couldn't, for now it only happens on our production servers. I assume `MessageBody.StopAsync` hasn't been called (otherwise it should have called `RequestBodyPipe.Reset` which would have completed the task), but `HttpRequestStream._body` being null shows that `HttpProtocol.StopStreams` has been called. This could happen if `HasStartedConsumingRequestBody` was false, but I don't see how that would be possible (and I can't check what value it had because it has been overwritten when `Http1Connection.Reset` was called).

Does it ring a bell?

**Comment by terrajobst** [comment]
@stephentoub, any idea on how to diagnose this further?

**Comment by kevingosse** [comment]
Just in case, I'd like to add that I'm 100% sure that the threads are stuck:
 - I've removed all the traffic from the application and waited for a while
 - I checked that the local and global threadpool queues are empty

**Comment by davidfowl** [comment]
@kevingosse where is that timeout code? Is it in the middleware pipeline? Can you show the bottom of the stack? Are you spawning a task in order to make that timeout logic work? (I'm wondering how you can have a stuck thread on Read outside of the middleware pipeline)

**Comment by kevingosse** [comment]
Full callstack is:

```
[HelperMethodFrame_1OBJ: 00007f8357234f30] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[], Int32, Int32)
LZ4.LZ4Stream.TryReadVarInt(UInt64 ByRef)
LZ4.LZ4Stream.AcquireNextChunk()
LZ4.LZ4Stream.Read(Byte[], Int32, Int32)
ProtoBuf.ProtoReader.Ensure(Int32, Boolean) [c:\code\protobuf-net\src\protobuf-net\ProtoReader.cs @ 267]
ProtoBuf.ProtoReader.TryReadUInt32VariantWithoutMoving(Boolean, UInt32 ByRef) [c:\code\protobuf-net\src\protobuf-net\ProtoReader.cs @ 142]
ProtoBuf.ProtoReader.TryReadUInt32Variant(UInt32 ByRef) [c:\code\protobuf-net\src\protobuf-net\ProtoReader.cs @ 201]
ProtoBuf.ProtoReader.ReadFieldHeader() [c:\code\protobuf-net\src\protobuf-net\ProtoReader.cs @ 702]
DynamicClass.proto_2(System.Object, ProtoBuf.ProtoReader)
ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoBuf.ProtoReader, System.Type, System.Object, Boolean) [c:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs @ 754]
ProtoBuf.Meta.TypeModel.Deserialize(System.IO.Stream, System.Object, System.Type, ProtoBuf.SerializationContext) [c:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs @ 609]
ProtoBuf.Serializer.Deserialize[[System.__Canon, System.Private.CoreLib]](System.IO.Stream) [c:\code\protobuf-net\src\protobuf-net\Serializer.cs @ 77]
Criteo.Web.Serialization.ProtobufRequestReader`1[[System.__Canon, System.Private.CoreLib]].Read(Ghost.Transports.Http.Contract.IHttpRequest, System.Threading.CancellationToken)
Criteo.Web.Serialization.DataTypeRequestReader`1[[System.__Canon, System.Private.CoreLib]].Read(Ghost.Transports.Http.Contract.IHttpRequest, System.Threading.CancellationToken)
Ghost.Core.ComponentMiddleware`4+<>c__DisplayClass6_0+<<Invoke>g__ProcessRequest|0>d[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].MoveNext()
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Ghost.Core.ComponentMiddleware`4+<>c__DisplayClass6_0+<<Invoke>g__ProcessRequest|0>d[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]], Ghost.Core.netcore]](<<Invoke>g__ProcessRequest|0>d<System.__Canon,System.__Canon,System.__Canon,System.__Canon> ByRef)
Ghost.Core.ComponentMiddleware`4+<>c__DisplayClass6_0[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].<Invoke>g__ProcessRequest|0()
System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].InnerInvoke()
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
System.Threading.ThreadPoolWorkQueue.Dispatch()
```

The task that was returned to the middleware is already complete at that point.

In short, when our middleware is called:
 - We start a Task.Delay. When it completes, we set an error status code on the response
 - We start processing the request on a separate thread (that's the above callstack)
 - We return `Task.WhenAny` of all this

**Comment by davidfowl** [comment]
@kevingosse That's super sketchy. You can't return from the middleware pipeline and still have code that is touching the http request. Just so I get the picture, you effectively doing this

```C#
app.Use((context, next) =>
{
    var timeout = Task.Delay(1000);
    await Task.WhenAny(timeout,  Task.Run(next))
});
```

That code will never be reliable, my guess is (looking at your clues) the state of the request gets reset while your deserialize is still running. Can you [buffer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequestrewindextensions.enablebuffering?view=aspnetcore-2.2#Microsoft_AspNetCore_Http_HttpRequestRewindExtensions_EnableBuffering_Microsoft_AspNetCore_Http_HttpRequest_System_Int32_System_Int64_) the request body instead?

```C#
app.Use(async (context, next) =>
{
    context.Request.EnableBuffering();
    await context.Request.Body.DrainAsync(context.RequestAborted);
    context.Request.Body.Position = 0;

    // Do synchronous protobuf deserialize here operation
});
```

**Comment by kevingosse** [comment]
I was kind of expecting to receive an exception if trying to read the request after the connection is closed. We have synchronization to make sure we don't write a response concurrently with the timeout, but we assumed that reading would be safe. In hindsight, since aspnetcore recycles a lot of objects under the hood, it doesn't sound so safe anymore.

I'll check if I can rework our logic the way you suggested. Thanks for the hint!

**Comment by davidfowl** [comment]
> I was kind of expecting to receive an exception if trying to read the request after the connection is closed

Are you aborting the request? Here's what the bad version looks like:

```C#
app.Use(async (context, next) =>
{
    void ProcessBody()
    {
        // Do synchronous operation
        context.Request.Body.Read(new byte[4096]);
    }

    var delay = Task.Delay(1000);
    var doWork = Task.Run(ProcessBody);
    var ret = await Task.WhenAny(delay, doWork);

    if (ret == delay)
    {
        context.Abort();
    }

    await doWork;
});
```

**Comment by kevingosse** [comment]
We're not aborting the request. We do nothing fancy in case of timeout, from Kestrel perspective it's processed like any normal request. 
I'm a bit surprised that we've noticed this behavior in only one application, even though we use the exact same timeout logic everywhere. There's still something missing in the equation. I'll try digging some more, while rewriting the timeout handling the way you suggested.

**Comment by davidfowl** [comment]
I think you're right that there's something else going on, it might be a race somewhere. I'm looking/

**Comment by davidfowl** [comment]
@kevingosse in the simplest repro I see several behaviors but haven't caught a hang condition yet:
- ObjectDisposedException
- RequestAbortedException

**Comment by davidfowl** [comment]
cc @halter73

**Comment by kevingosse** [comment]
I found something else that looks fishy in the memory dump. 

For various reasons, we make a copy of the HTTP headers at the beginning of the processing of the request. In a small number of stuck threads (12 out of 3253), I found a mismatch between the Content-Length header that we copied and the value of `_contentLength` in the `Http1MessageBody.ForContentLength` object. Are you aware of a scenario where those two values could mismatch?

**Comment by kevingosse** [comment]
The only scenario I can think of for the content-length mismatch is:

 - Thread1 starts processing request1. Processing times out so kestrel believes we're done with the request
 - Thread2 starts processing request2, reusing the HttpProtocol object. `Streams.Start` is called, resulting in a new MessageBody being assigned to the HttpRequestStream
 - Thread1 finally gets to the point where it tried to read from the stream, and ends up reading from the MessageBody of request2

It confirms that we have to rethink our timeout logic. Those threads getting stuck are likely a variation of this scenario, where we end up manipulating the wrong objects because of the recycling.

**Comment by halter73** [comment]
I agree with your final analysis @kevingosse. Applications are responsible for ensuring they are done using the HttpContext and related objects prior to completing their Tasks. As soon as the app middleware Task completes, Kestrel will reuse those objects for the next request, so all bets are off if you're still using them.

`Http1ContentLengthMessageBody. _contentLength` is a readonly field populated directly from the Content-Length request header, so if it's not matching what you expect, that's a pretty good sign that you're referencing an object after it's been reused for another request.

**Comment by davidfowl** [comment]
Glad you got a deterministic repro!

**Comment by kevingosse** [comment]
I couldn't reproduce the hang, but at this point I believe it's safe to conclude that it's another consequence of using the HttpContext past the end of the request. To fix this in our code we'll need to prefetch the content of the request (equivalent to what `DrainAsync` does). On the plus side it means we won't have to worry anymore about Protobuf accessing the stream synchronously, so that's killing two birds with one stone. On the minus side, it means that in the off chance that the issue was actually unrelated to our usage of the HttpContext, it won't be detectable anymore (since our reads won't block). 

That aside, I think you should consider making HttpContext recycling opt-in. It's a great feature performance-wise, but it's easy to misuse if you're not aware of it. Given that it paves the way to the worst possible kind of bug for a web app (replying a request with the content of another), you should make sure that the developers know what they're dealing with.
