### ISSUE TITLE
Blazor - 3.1 Preview 3 HTTP exception – Failed to execute 'arrayBuffer' on 'Response': body stream is locked

### ISSUE THREAD

**Issue by Rauce** [aspnet/AspNetCore#17231]
I'm developing a Blazor WebAssembly app.

After upgrading all my solution Nuget packages to `3.1.0-preview3.19555.2`, all `HttpClient.SendAsync()` calls to a REST/JSON API (with a subsequent `await JsonSerializer.DeserializeAsync<T>(await response.Content.ReadAsStreamAsync(), null, cancellationToken)` to read the response) fail with the following error:

```
TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream is locked
WebAssembly.JSException, Unix 1.0.0.0
  at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler+WasmHttpContent.GetResponseData () <0x25d7888 + 0x000fc> in <6bbb4038c01647e69451296d84123d1f>:0 
  at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler+WasmHttpContent.CreateContentReadStreamAsync () <0x25d7150 + 0x000c8> in <6bbb4038c01647e69451296d84123d1f>:0 
  at MyApp.MyApiClient.SendAndReceive[T] (System.Net.Http.HttpMethod method, System.String uri, System.Object obj, System.Threading.CancellationToken cancellationToken) 
```

I'm using the latest Visual Studio Preview (16.4.0 Preview 5) with the `3.1.100-preview3-014645` runtime installed.

Simply reverting my solution Nuget packages to use `3.1.0-preview2.19528.8` versions makes the problems go away – everything works again (even with keeping the latest VS + .NET Core runtime versions).

Is this a known issue? Or is there something else I need to update?

I've tried cleaning the VS solution and and clearing browser caches, etc. – no luck. No matter what I try, Preview 2 works fine, but Preview 3 doesn't.

**Comment by javiercn** [comment]
This issue was moved to mono/mono#17845

**Comment by javiercn** [comment]
@Rauce thanks for contacting us.

We believe this is an issue in the new httpclient handler we upgraded to in the latest version. We've moved the issue to the mono repo so that it can be tracked there.
