### ISSUE TITLE
too many .AspNetCore.OpenIdConnect.Nonce cause Nginx Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by wulaiwei** [aspnet/AspNetCore#17247]
Steps to reproduce:

1.)
Go to some page that has authorization required (get redirected to IdenityServer login screen)
Notice that an OpenId.nonce cookie ending with some random suffix is created in browser (so far so good)

2.) Use the browser button to go back

3.) Click again on a link that requires authorization (get redirected to login screen again)
Now an additional OpenId.nonce cookie is being created with different random suffix

4.) Do that 20-30 times until there are too many cookies for the domain and the request is being rejected with "Bad Request - Request Too Long"

By viewing issue, I found some solutions eg:OpenIdConnectAuthenticationHandler ,But it doesn't apply to me.
My project environment version is：
.net core 2.2 identityserver4
I tried the sample project and the problem can be reproduced.
Is there any solution to deal with this problem?
![image](https://user-images.githubusercontent.com/16910820/69199775-01a62900-0b74-11ea-9c2f-0b3428dd955a.png)

**Comment by Tratcher** [comment]
> 4.) Do that 20-30 times until there are too many cookies for the domain and the request is being rejected with "Bad Request - Request Too Long"

That's well outside the expected behavior of a user logging in. Can you give a realistic scenario where this would come up?

Keep in mind that those cookies have a short, configurable lifetime (15m by default?), they'll clean themselves up. The last cookie is also removed as soon as the user successfully logs in.

**Comment by wulaiwei** [comment]
> > 4.）进行20到30次，直到该域的Cookie过多并且该请求被拒绝，并显示“错误请求-请求太长”
> 
> 这远远超出了用户登录的预期行为。您能给出一个现实的情况吗？
> 
> 请记住，这些Cookie的生存期很短，可配置（默认情况下为15m？），它们会自行清理。用户成功登录后，也会删除最后一个cookie。

**Comment by wulaiwei** [comment]
I am very sorry to reply you now. Unfortunately, I can't provide a specific scene here.
In my test environment, this situation may happen several times a day during login, I can't reproduce it.

**Comment by wulaiwei** [comment]
> > 4.) Do that 20-30 times until there are too many cookies for the domain and the request is being rejected with "Bad Request - Request Too Long"
> 
> That's well outside the expected behavior of a user logging in. Can you give a realistic scenario where this would come up?
> 
> Keep in mind that those cookies have a short, configurable lifetime (15m by default?), they'll clean themselves up. The last cookie is also removed as soon as the user successfully logs in.

I am very sorry to reply you now. Unfortunately, I can't provide a specific scene here.
In my test environment, this situation may happen several times a day during login, I can't reproduce it.

**Comment by Tratcher** [comment]
Getting into a loop between the identity provider and your application can look similar to what you've described (without hitting the back button). Usually it's caused by a misconfiguration. The best option is to capture and share a network trace (Fiddler or Wireshark) and we can help identify why it's stuck in a loop.

**Comment by wulaiwei** [comment]
> Getting into a redirect loop between the identity provider and your application can look similar to what you've described (without hitting the back button). Usually it's caused by a misconfiguration. The best option is to capture and share a network trace (Fiddler or Wireshark) and we can help identify why it's stuck in a loop.

 services.AddAuthentication(options =>
                {
                    options.DefaultScheme = "Cookies";
                    options.DefaultChallengeScheme = "oidc";
                })
                .AddCookie("Cookies", x =>
                {
                    x.ExpireTimeSpan = TimeSpan.FromSeconds(ssoCookieLifetime);
                    x.SlidingExpiration = false;
                    x.EventsType = typeof(CookieEventHandler);
                })
                .AddOpenIdConnect("oidc", options =>
                {
//                    options.CorrelationCookie.Path = "/";
//                    options.NonceCookie.Path = "/";
                    if (Environment.IsDevelopment())
                    {
                        options.BackchannelHttpHandler = new HttpClientHandler()
                        {
                            ServerCertificateCustomValidationCallback =
                                HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
                        };
                    }

                    options.ProtocolValidator.RequireTimeStampInNonce = true;
                    options.UseTokenLifetime = true;
                    options.SignInScheme = mvcRemoteAuthenticationOptions.SignInScheme;
                    options.Authority = mvcRemoteAuthenticationOptions.Authority;
                    options.RequireHttpsMetadata = mvcRemoteAuthenticationOptions.RequireHttpsMetadata;
                    options.ClientId = mvcRemoteAuthenticationOptions.ClientId;
                    options.ClientSecret = mvcRemoteAuthenticationOptions.ClientSecret;
                    options.ResponseType = mvcRemoteAuthenticationOptions.ResponseType;
                    options.SaveTokens = mvcRemoteAuthenticationOptions.SaveTokens;
                    options.GetClaimsFromUserInfoEndpoint =
                        mvcRemoteAuthenticationOptions.GetClaimsFromUserInfoEndpoint;
                    foreach (var item in mvcRemoteAuthenticationOptions.AddClaimMapActions)
                    {
                        options.ClaimActions.MapJsonKey(item.ClaimType, item.JsonKey);
                    }

                    if (mvcRemoteAuthenticationOptions.DeleteClaimMapActions != null)
                    {
                        options.ClaimActions.DeleteClaims(
                            mvcRemoteAuthenticationOptions.DeleteClaimMapActions.ToArray());
                    }

                    options.Scope.Add("ecommerceApi");
                    options.Scope.Add("gtBuyerApi");
                    options.Events.OnRedirectToIdentityProvider = contextToIdentityProvider =>
                    {
                        var oldNonces = contextToIdentityProvider.Request.Cookies.Where(kvp => kvp.Key.StartsWith(".AspNetCore.OpenIdConnect.Nonce"));
                        var keyValuePairs = oldNonces as KeyValuePair<string, string>[] ?? oldNonces.ToArray();
                        if (!keyValuePairs.Any()) return Task.CompletedTask;
                        
                        var cookieOptions = new  CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(-1),
                            HttpOnly = true
                        };
                        foreach (var oldNonce in keyValuePairs)
                        {
                            Console.WriteLine($"oldNonce:{oldNonce.Key}{oldNonce.Value}");
                            contextToIdentityProvider.Response.Cookies.Delete(oldNonce.Key, cookieOptions);
                        }
                        return Task.CompletedTask;
                    };
                    options.Events.OnRemoteFailure = context =>
                    {
                        try
                        {
                            var data = context;
                            byte[] bytes;
                            using (var stream = new MemoryStream())
                            {
                                var formatter = new BinaryFormatter();

                                formatter.Serialize(stream, data.Failure);
                                bytes = stream.GetBuffer();
                            }

                            var db = redis.GetDatabase();
                            db.SetAdd($"{DateTime.Now.ToString("o")}:Failure.Message", data.Failure.Message);
                            db.SetAdd($"{DateTime.Now.ToString("o")}:Failure.Message.bytes", bytes);
                            if (context.Failure.Message.Contains("Correlation failed"))
                                context.Response.Redirect(
                                    $"/JwellAuthorize/CreateAuthorize?callbackUrl={Configuration["PlatformHosts:Home"] ?? "/"}");
                            else
                                throw new Exception(context.Failure.Message);
                            context.HandleResponse();

                            return Task.CompletedTask;
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($"OnRemoteFailure:{ex.Message}");
                            return Task.CompletedTask;
                        }
                    };
                });

this is my configuration,I just triggered the RemoteFailure event and the error message contained Correlation failed Perform login redirection，but  The last time this problem occurred, redis only recorded a record of RemoteFailure event.

**Comment by Tratcher** [comment]
And the Fiddler trace?

**Comment by wulaiwei** [comment]
> And the Fiddler trace?
Sorry, this problem did not occur yesterday. I cannot provide Fiddler trace.

**Comment by Tratcher** [comment]
We won't be able to help further without a trace. Let us know when you can get one.
