### ISSUE TITLE
Blazor - GetJsonAsync doesn't accept null in the json from API

### ISSUE THREAD

**Issue by shinhf** [aspnet/AspNetCore#17240]
### Describe the bug

httpClient.GetJsonAsync is unable to parse JSON downloaded from API that contain null value

### To Reproduce
```
@shipList

@code
{
    private List<Ship> shipList;
    HttpClient httpClient = new HttpClient() { BaseAddress = new Uri("https://api.spacexdata.com") };

    protected override async Task OnInitializedAsync()
    {
        shipList = await httpClient.GetJsonAsync<List<Ship>>("/v3/ships");

    }

```

### Error value

InvalidOperationException: Cannot get the value of a token type 'Null' as a number.

### Further technical details
- ASP.NET Core version 3.0

PS
I've tried setting addJsonOptions in Startup.cs (https://stackoverflow.com/questions/44595027/net-core-remove-null-fields-from-api-json-response ) but it didn't work.

**Comment by pranavkm** [comment]
@shinhf could you share the JSON payload you're attempting to read and the `Ship` model that it's being bound to? The exception message makes it sound like you have a number type (such as an `int`) that is attempted to be bound to the `null` JSON token which sounds like a legitimate exception. Perhaps it needs to be bound to a nullable value?

**Comment by shinhf** [comment]
@pranavkm 
this is based on the open SpaceX API. The JSON file can be downloaded from the address in the code: https://api.spacexdata.com/v3/ships

**Comment by pranavkm** [comment]
Could you share the `Ship` type that's being deserialized?

**Comment by shinhf** [comment]
`    public class Mission
    {
        public string mission_name { get; set; }
        public string mission_id { get; set; }
        public List<string> manufacturers { get; set; }
        public List<string> payload_ids { get; set; }
        public string wikipedia { get; set; }
        public string website { get; set; }
        public string twitter { get; set; }
        public string description { get; set; }
    }

    public class Position
    {
        public double latitude { get; set; }
        public double longitude { get; set; }
    }

    public class Ship
    {
        public string ship_id { get; set; }
        public string ship_name { get; set; }
        public object ship_model { get; set; }
        public string ship_type { get; set; }
        public List<string> roles { get; set; }
        public bool active { get; set; }
        public int imo { get; set; }
        public int mmsi { get; set; }
        public int abs { get; set; }
        public int @class { get; set; }
        public int weight_lbs { get; set; }
        public int weight_kg { get; set; }
        public int year_built { get; set; }
        public string home_port { get; set; }
        public string status { get; set; }
        public float speed_kn { get; set; }
        public object course_deg { get; set; }
        public Position position { get; set; }
        public object successful_landings { get; set; }
        public object attempted_landings { get; set; }
        public List<Mission> missions { get; set; }
        public string url { get; set; }
        public string image { get; set; }
    }`

**Comment by pranavkm** [comment]
@shinhf as I said earlier, the JSON payload has null values for nearly all the numeric values in your types. Changing these to nullable values should resolve this error. The error message should describe the JSON path that produced the error. For instance, here's what I get:

```
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $[1].imo | LineNumber: 0 | BytePositionInLine: 829.
```
which indicates that the `imo` property would need to be marked as nullable:

```diff
- public int imo { get; set; }
+ public int? imo { get; set; }
```
