### ISSUE TITLE
IdentityServer4 for Blazor

### ISSUE THREAD

**Issue by rysep2** [aspnet/AspNetCore#17256]
I'm trying to fit my Blazor Server Side application into our existing IdentityServer4 process. At the moment there is no official documentation concerning this topic and I'm forced to use hacky workarounds that in turn produce uncommon errors. In [this github issue](https://github.com/aspnet/AspNetCore/issues/12601) I already addressed one of those errors that I still can't solve.

On stackoverflow I see a lot of people try to accomplish the same thing but I haven't found an issue here on github that plans to support IdentityServer4 for Blazor. Correct me if I'm wrong.

The perfect solution for me would include documentation and a template, like with the other authentication possibilities in Blazor.

**Comment by javiercn** [comment]
@rysep2 thanks for contacting us.

I'm not sure what flow you are trying to use, but you should use the same flow available in a traditional server-side application. Meaning you do an OIDC flow using the asp.net core OIDC authentication handler and then you stamp a cookie out of it. 

At which point your server-side blazor application uses that cookie. You might need to do an additional step to pass the access tokens (if any) to the app during startup.

That is something you can do in 3.1 by passing them as parameters to the root component.

**Comment by rysep2** [comment]
I'm using the OIDC flow and my main problem is that I can't get the access token in the HttpMessageHandler before calling the API. I described this problem in the linked github issue.

And I already used the following workarounds:

- I have a .cshtml logout page only for the command `HttpContext.SignOutAsync();`, since the HttpContext is not available in blazor (.razor pages).

- I have a .cshtml start page to get the access token, which once again relies on the HttpContext.

That's why I asked myself if there isn't a plan for an official OIDC flow in blazor.

Can you elaborate what you mean by:

> You might need to do an additional step to pass the access tokens (if any) to the app during startup. That is something you can do in 3.1 by passing them as parameters to the root component.

How would I do that and what could I do with the access token in the root component?

**Comment by diblaze** [comment]
@rysep2 I encountered the same issue today. I needed the access token to talk to the backend, also using OIDC.
However, I do not use HttpMessageHandler - instead I just inject the HttpContext and use it when needed.
In ConfigureServices, I added the following code:
```
services.AddHttpContextAccessor();
```
Then in my service constructor I simply used DI to get access to the context.
`public Service(IHttpContextAccessor httpContextAccessor)`

When I want to use my HttpClient, I simply use the following code. ( I use HttpClientFactory, so clientFactory will be the regular HttpClient create instead.)
```
var token = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token").ConfigureAwait(false);
var httpClient = _clientFactory.CreateClient("rest");
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
```

Maybe this will be of use for you - if not, I hope you find a solution to your problem. 😄

**Comment by rysep2** [comment]
@diblaze Using the HttpContextAccessor was my first solution too and it worked locally. The problems came when I released to our test server. `_httpContextAccessor.HttpContext` was always `null` on there. I didn't pursue this solution further because I was told not to use HttpContextAccessor in Blazor but now that I think of it - maybe this could be solved by changing the configuration on my server IIS. Have you released your application to a server environment? Does it work for you?
