### ISSUE TITLE
Project build operation

### ISSUE THREAD

**Issue by tttttvf** [aspnet/AspNetCore#17255]
### Is your feature request related to a problem? Please describe.
I tried to generate the XML of the. Net standard class library project to the webapi project generation directory, but it seems that I just copied the DLL file,The XML file does not seem to have been copied

### Describe the solution you'd like
The XML file of. Net standard class library should be included in the generated directory of webapi project

### Additional context
![image](https://user-images.githubusercontent.com/23305591/69216166-709c7580-0ba6-11ea-8ef3-8dc0b20b0207.png)

![image](https://user-images.githubusercontent.com/23305591/69216217-9c1f6000-0ba6-11ea-8099-30f7863e3d5f.png)

![image](https://user-images.githubusercontent.com/23305591/69216267-c3762d00-0ba6-11ea-98e2-0fd02a5980fa.png)

**Comment by tttttvf** [comment]
This seems to be related to my changing the name of the generated XML file. I have specified the name and relative path of the XML file. If I just open the XML file, I can copy it to the generated directory normally

**Comment by javiercn** [comment]
@tttttvf thanks for contacting us.

We believe this issue has nothing to do with ASP.NET Core and should be reported elsewhere. You could try reporting it through the send VS feedback dialog to get a better answer.

You can follow instructions https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019#report-a-problem

@Pilchie do you know who the right team to route this issue to is?

**Comment by Pilchie** [comment]
I think this is either `dotnet\sdk` or `dotnet-project-system`.  @nguerrera or @tmeschter to you know which?

**Comment by tttttvf** [comment]
Thank you. I will go to other teams to give feedback on this problem
