### ISSUE TITLE
BuildManager.GetCompiledType in ASP.NET Core

### ISSUE THREAD

**Issue by sh0uzama** [aspnet/AspNetCore#17262]
Is there a way in **ASP.NET Core** to get the compiled type of a razor view?

In the "old" **ASP.NET MVC** this was possible by invoking:

`var compiledType = System.Web.Compilation.BuildManager.GetCompiledType(fullPath);`

where `fullPath` is the path to the cshtml razor view.

**Comment by javiercn** [comment]
@sh0uzama thanks for contacting us.

We emit attributes in the Views assembly that could be used to find the types. 

@pranavkm any thoughts?

**Comment by pranavkm** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.compilation.iviewcompiler.compileasync?view=aspnetcore-3.0#Microsoft_AspNetCore_Mvc_Razor_Compilation_IViewCompiler_CompileAsync_System_String_ would be the closest approximation. Can you share more specifics about why you're attempting to get the compiled type?

**Comment by sh0uzama** [comment]
@javiercn - I wasn't aware of the "Views" assembly - exploring that did the trick, thank you very much for the fast answer.

@pranavkm - I wanted to get the compiled type of a given view to determine which properties are exposed inside that view (it's a project migration from asp.net mvc to asp.net core); now I'm struggling with assigning values to these properties at runtime, but that's a different topic ;)
