### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by kevingkday** [aspnet/AspNetCore#17263]
A server side Blazor app that I created in VS 2019 Preview works fine locally, and it also works fine on the production server without SSL.  However, when I added SSL certificate (through load balancer on AWS) Blazor no longer connects.  If I change from https to http, then Blazor connects ok, so it is definitely an issue with the SSL.  It is a purchased store certificate that validates on SSL checkers, and all other features of site work fine with SSL, it is just Blazor connection.  Any idea how this can be fixed?  I've attached a screenshot.

![blazor](https://user-images.githubusercontent.com/7671505/69260412-b3455a00-0b74-11ea-95a4-3f393c18bbc0.jpg)

**Comment by javiercn** [comment]
@kevingkday thanks for contacting us.

@kevingkday Seems like the client is trying to use long-polling, you might need to do additional work to enable websockets in your site.

@BrennanConroy @anurse do you have any idea of what can be happening here?

**Comment by BrennanConroy** [comment]
The errors with LongPolling should be fixed in 3.0.1 and 3.1.0 previews. The 200 with websockets is likely an issue with your proxy/server not supporting websockets.

**Comment by javiercn** [comment]
Closing this issue as there's no further action for us to take here.
