### ISSUE TITLE
OnDisconnectedAsync has null exception when user lost signal

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#17260]
_From @kienit on Wednesday, November 20, 2019 3:50:33 AM_

I have SignalR hub which has OnDisconnectedAsync() override the base method.
I expected when user lost signal, I must have some reason. However, it always return null

### Expected  behavior
Exception must has some message instead null

### Actual behavior
null exception

### Steps to reproduce

 public override async Task OnDisconnectedAsync(Exception exception)
        {
            var key = Context.GetHttpContext().User.Identity.Name;
            var connectionID = Context.ConnectionId;

            // Disconnect by intention
            if (exception == null)
            {} e;se { }
            await TryStopBroadcast();
            await base.OnDisconnectedAsync(exception);
        }

_Copied from original issue: SignalR/SignalR#4432_

**Comment by halter73** [comment]
Why are you getting the current user from `Context.GetHttpContext().User` instead of using [Context.User](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-3.0#the-context-object) directly?

**Comment by anurse** [comment]
> I expected when user lost signal, I must have some reason. However, it always return null

What do you mean by "lost signal"? Can you collect debug logs from SignalR? See https://aka.ms/aspnet/signalr/troubleshoot for guidance on how to do this.
