### ISSUE TITLE
Alternative access token query key for SignalR bearer authentication

### ISSUE THREAD

**Issue by mikeChatsky** [aspnet/AspNetCore#17271]
I have a custom authentication flow that involves attaching an access token to the headers/query string using a "token" key (`url: ...?token={my-token}`). I was able to set query strings on the **old** signalr ASP.NET JS client as the documentation states:

`var connection = $.hubConnection();
connection.qs = { 'version' : '1.0' };`
https://github.com/SignalR/bower-signalr/blob/bdc7cb4b255e41acf09a18f646a14732c163fcbb/jquery.signalR.js#L146-L153

However, the ASP.NET Core package version restricts (or rather standardizes) access tokens to be passed only through a "access_token" key:

https://github.com/aspnet/AspNetCore/blob/6cc99ea04f8254da4963740e627fc2e61b446063/src/SignalR/clients/ts/signalr/src/WebSocketTransport.ts#L41-L46

I believe it is due to the standard, but being able to set the key through IHttpConnectionOptions of the builder would be nice.
something like:

`HubConnectionBuilder().withUrl("/hubs/chat", { accessTokenFactory: () => this.loginToken, accessTokenKey: 'my-key' })`

Alternatively, being able to set query string parameters (as in the old package) would be a great too.

Any thoughts on the idea? I would be glad to make a PR for this feature.

**Comment by anurse** [comment]
Couldn't you also just do this by setting a query string token in the URL or using a header? Like this:

```
new HubConnectionBuilder().withUrl(`/hubs/chat?token=${this.loginToken}`)
```

If you need to "refresh" it with new values, you could also provide a custom `HttpClient` implementation by setting the [`httpClient`](https://docs.microsoft.com/javascript/api/%40microsoft/signalr/ihttpconnectionoptions?view=signalr-js-latest#httpclient) property.

**Comment by mikeChatsky** [comment]
@anurse I did try to add a custom httpClient that attaches a token to the query, however, the WS request (after negotiate) doesn't seem to go through the custom httpClient.

**Comment by anurse** [comment]
> the WS request (after negotiate) doesn't seem to go through the custom httpClient.

Ah yeah, that is true. The browser API for WebSockets is completely separate from the HTTP APIs.

My big concern with this is that we chose that query string value [based on the OAuth spec](https://tools.ietf.org/html/rfc6750#section-2.3) and we always want to be cautious when adding new config options since they are new public API and can't really be changed once we add them :).

> I have a custom authentication flow that involves attaching an access token to the headers/query string using a "token" key (`url: ...?token={my-token}`)

Can you provide more information on this flow? Is there a reason this flow can't accept the `access_token` value?

**Comment by mikeChatsky** [comment]
> My big concern with this is that we chose that query string value [based on the OAuth spec](https://tools.ietf.org/html/rfc6750#section-2.3) and we always want to be cautious when adding new config options since they are new public API and can't really be changed once we add them :).

Yes I guessed an alternative key option might provide a way to deviate from the Oauth specs in an unrecommended manner. I just figured maybe this option might interest other developers or provide help for those struggling to get their access tokens across WS requests. 

> Can you provide more information on this flow? Is there a reason this flow can't accept the `access_token` value?

I digged around my project and it's definitely something a small refactor (to accept `acces_token`) can fix. 

Thanks for the help! @anurse

**Comment by anurse** [comment]
@mikeChatsky That sounds like the best approach for now. I do recognize the value of being able to change the query string option but I'm not yet sure it's worth the overhead of new public options APIs. We can keep an eye out for other cases where users can't refactor quite so easily and revisit this in the future.
