### ISSUE TITLE
Blazor - Is any page lifecycle method available to do a some action, when user clicks the browser back or refresh?

### ISSUE THREAD

**Issue by pandiyarajm93** [aspnet/AspNetCore#17289]
### Describe the bug
Perform some logic, when the user clicks the browser back or refresh

### To Reproduce
I want to perform some logic operation, when user clicks the  browser back or refresh while editing the form

In javascript, we can achieve this by **window.onbeforeunload** method. Is any possibility available to achieve this same usecase in Blazor ?

``` C#
        window.onbeforeunload = function () {
               // Do some logics
        };
```

### Further technical details
- Blazor - .NET Core 3.1 preview 1 on Windows 10

**Comment by javiercn** [comment]
@pandiyarajm93 thanks for contacting us.

That's not something you can do directly in Blazor. You need to use JavaScript to achieve it.

**Comment by mobinseven** [comment]
`onbeforeunload` is not triggered when surfing razor pages. There must be a substitute lifecycle event for razor components which **surprisingly** doesn't exist.
You may use Dispose() method and it may do the job for you. But it didn't work for me as I needed the unloaded component Uri (Dispose() is triggered when Uri is changed).
