### ISSUE TITLE
Blazor - How to render dynamic content with variables

### ISSUE THREAD

**Issue by mischa71lab** [aspnet/AspNetCore#17297]
I have a page and would like to insert some dynamic content from a string and also need to add some variables to it. when i do this:

```
@DynamicContent

@code
{
  protected override void OnInitialized()
    {
        var dto = new dto();
        dto.Id = 6;
        dto.Name = "This is the name of the Dto";

        RawHtml = "<h1> @dto.Id / @dto.Name</h1>";
        DynamicContent = builder =>
        {
            builder.OpenElement(0, "rawhtmlname");
            builder.AddContent(1, RawHtml);
            builder.CloseElement();
        };    
    }
}
```

i end up with '@dto.Id / @dto.Name' as literal strings instead of the values '6 / This is the name of the Dto'  Is there a way to accomplish this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear what is the complexity in your scenario, as pure razor would suffice in this case:

```razor
<h1> @dto.Id / @dto.Name</h1>

@code{
...
}
```

If there is something more to this please reply with more details.

**Comment by mischa71lab** [comment]
Hello Artak,

I have a salesorder and am looking for a way to show this with different layouts.
So i wanted to load and render part of the page from a string from a database.
This way i can store multiple layouts in a database and change them with a textarea control.
Hopes this clearifies things.
Thanks
