### ISSUE TITLE
Add HEIF/HEIC mime types in FileExtensionContentTypeProvider

### ISSUE THREAD

**Issue by bgarel** [aspnet/AspNetCore#17290]
HEIF is the new image format that is now preferred and official in iOS and macOS. 

Please add

    image/heif => .heif
    image/heic => .heic

https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by Tratcher** [comment]
It's not clear that this meets the criteria: https://github.com/aspnet/AspNetCore/blob/e2def80a0ad5143fdbd72f2051a86b2082ca92ce/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs#L15-L17

**Comment by bgarel** [comment]
It is too bad that there is not a mime types provider that can be improved in ASP.NET Core.
I will have to use an external MimeTypes mapping library to handle file extensions.

**Comment by Tratcher** [comment]
? You can add your own mappings to the existing provider.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.0#fileextensioncontenttypeprovider

**Comment by bgarel** [comment]
Thank you for the link. It solves my issue.

**Comment by JohnnyFun** [comment]
fwiw, yar:

```
var fileExtensionContentTypeProvider = new FileExtensionContentTypeProvider();
fileExtensionContentTypeProvider.Mappings[".heic"] = "image/heic";
fileExtensionContentTypeProvider.Mappings[".heif"] = "image/heif";
fileExtensionContentTypeProvider.TryGetContentType(fileName, out var contentType);
```
