### ISSUE TITLE
Set value to @functions defined properties inside Razor views

### ISSUE THREAD

**Issue by sh0uzama** [aspnet/AspNetCore#17299]
I am trying to render a Razor view at runting using the RenderAsync method

`ViewEngineResult.View.RenderAsync(viewContext)`

The view that I am trying to render contains variables defined in a `@functions` block

	@{
	  Layout = null;
	}

	@functions
	{
	  public string test { get; set; }
	}

	<!DOCTYPE html>

	<html>
	<head>
	  <meta name="viewport" content="width=device-width" />
	  <title>Razor</title>
	</head>
	<body>
	  <h2>WITH VARIABLE</h2>
	  <strong>VALUE: @test</strong>
	</body>
	</html>

Previousy, with ASP.NET MVC, I would populate the ViewData with a `key` with the same name of the property and "under the hood" the mvc engine did the assignment for me.

Is this still somehow possible in ASP.NET CORE?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sh0uzama.
You can achieve what you want by decorating the `test` property with `ViewDataAttribute` attribute, to enable mapping.

**Comment by sh0uzama** [comment]
Thank you for your quick answer @mkArtakMSFT - but unfortunately this isn't giving the expected result =(

With a view like this:

	@{
	  Layout = null;
	}

	@functions
	{
	  [ViewData]
	  public string test { get; set; }
	}

	<!DOCTYPE html>
	<html>
	<head>
	  <meta name="viewport" content="width=device-width" />
	  <title>Test</title>
	</head>
	<body>
	  <h2>VIEWDATA INJECTION TEST</h2>
	  <pre>public string test: @test</pre>
	  <pre>ViewData["test"]: @ViewData["test"]</pre>
	</body>
	</html>

I can get the ViewData["test"] to output the correct result, but unfortunately the property still remains non-populated.

I guess I can workaround this with a little rewrite of the views, but still I'm curious to understand if there's a way to do it like the old ASP.NET MVC

If you have some more info I'll be glad to know them, but in any case thank you for your help!
