### ISSUE TITLE
WsFederation wrong wreply url for web applications not in the host root

### ISSUE THREAD

**Issue by valeriob** [aspnet/AspNetCore#17298]
1) Create a web application with authentication and add WsFederation middlewhare (AddWsFederation)
2) deploy it in a subdirectory under iis for example mydomain.com/mywebapp
3) Execute login via domain
4) Execute logout => you get redirrected in the wrong url and get a 404 in my case the url is
Https://mydomain.com/mywebapp/mywebapp/Account/Logout (i'm using aspnetcore identity)

Looking at the code i can see that WsFederationHandler.cs https://github.com/aspnet/AspNetCore/blob/33eb8ba552c7452f441e2a223457d39f271d01b7/src/Security/Authentication/WsFederation/src/WsFederationHandler.cs#L343

calls for BuildRedirectUriIfRelative with parameter "/mywebapp/Account/Logout"
then BuildRedirectUri(string targetPath)=> Request.Scheme + "://" + Request.Host + OriginalPathBase + targetPath;
but OriginalPathBase is already "/mywebapp" so the resulting url is wrong ( https://mydomain.com/mywebapp/mywebapp/Account/Logout )

**Comment by Tratcher** [comment]
Please show the options you used to configure WsFed. Where is "/mywebapp/Account/Logout" coming from?

**Comment by valeriob** [comment]
Hi @Tratcher,
i'm setting only MetadataAddress, and Wtrealm.
/Account/Logout is an action that does this : 

                string url = Url.Action("Logout");

                // this triggers a redirect to the external provider for sign-out
                return SignOut(new AuthenticationProperties { RedirectUri = url }, vm.ExternalAuthenticationScheme);

**Comment by valeriob** [comment]
I was able to work around the problem with this code : 

                authBuilder.AddWsFederation(wsfed.Scheme, wsfed.DisplayName, options =>
                {
                    options.MetadataAddress = wsfed.MetadataAddress;
                    options.Wtrealm = wsfed.Wtrealm;

                    options.Events.OnRedirectToIdentityProvider = evnt =>
                    {
                        if (evnt.ProtocolMessage.IsSignOutMessage)
                        {
                            evnt.ProtocolMessage.Wreply = evnt.HttpContext.Request.Scheme + "://" + evnt.HttpContext.Request.Host + evnt.Properties.RedirectUri;
                        }

                        return Task.CompletedTask;
                    };
             }

**Comment by Tratcher** [comment]
A simpler workaround would be:
```
return SignOut(new AuthenticationProperties { RedirectUri = "/Account/Logout" }, vm.ExternalAuthenticationScheme);
```

**Comment by valeriob** [comment]
Yes indeed, but i do not know if it will break other auth mechanisms

**Comment by Tratcher** [comment]
It shouldn't. What other mechanisms are you using? SignOut is only supported by Cookies, WsFed, and OpenIdConnect.

**Comment by valeriob** [comment]
Thanks @Tratcher i use all of those. Howeve now i have a work around, i will track this issue to check when to remove it :D

**Comment by Tratcher** [comment]
I don't anticipate making any product changes here. The urls are expected to be relative to PathBase.

**Comment by valeriob** [comment]
Ok thanks, i hope all of them behave the same
