### ISSUE TITLE
Getting a value from the object type collection in Blazor

### ISSUE THREAD

**Issue by Indrajith-Sync** [aspnet/AspNetCore#17305]
I am trying to get the value form the object collection in blazor.

The line of code returns the following
`this.buttons[i].model ` => `{{
  "content": "Close"
}}`

In the above code i need to get the value of "content". I have tried this it doesn't work any other solution for this ?

`this.buttons[i].model.GetType().GetProperty("content").GetValue(this.buttons[i].model)`

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
