### ISSUE TITLE
Provide Better Opportunity for Http Status Code Handling on HubConnection failures

### ISSUE THREAD

**Issue by rpriest1260** [aspnet/AspNetCore#17304]
### Is your feature request related to a problem? Please describe.
When a HubConnection failure happens (and the connection is closed) due to an HTTP error, an HttpRequestException is thrown. However, as the HTTP status code is only presented in the Message string property,  proper and discrete handling of status code is difficult. The consumer must resort to string parsing of the Message property to obtain the status. This is not optimal.

### Describe the solution you'd like
Provide a mechanism to retrieve the [HTTP Status Code](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=netcore-2.0)  from the exception. This will supply the consumer with an opportunity to handle the status codes on a case-by-case basis (a 401 may be handled differently than a 404). 

Please review the pull request below, to satisfy this feature:
              https://github.com/aspnet/AspNetCore/pull/17302

**Comment by BrennanConroy** [comment]
A possible better alternative would be for this to be handled at a lower level, see the proposal for adding a new exception with a status code at https://github.com/dotnet/corefx/issues/26477

**Comment by anurse** [comment]
Fixing this through dotnet/corefx#26477 is definitely our preferred option. Closing this as external. If that issue doesn't go anywhere we can revisit this.
