### ISSUE TITLE
centos7 yum install dotnet-sdk-2.2 or dotnet-sdk-3.0

### ISSUE THREAD

**Issue by redochenzhen** [aspnet/AspNetCore#17301]
I followed [instructions here](https://dotnet.microsoft.com/download/linux-package-manager/sdk-2.2.207) to install dotnet-sdk, but got error message as below:
Error downloading packages:
  aspnetcore-runtime-2.2-2.2.8-1.x86_64: [Errno 256] No more mirrors to try.
Actually package aspnetcore-runtime-2.2-2.2.8-1.x86_64 is not listing in [this index](https://packages.microsoft.com/rhel/7/prod/).
Is there something wrong with the rpm seed?

**Comment by javiercn** [comment]
@redochenzhen thanks for contacting us.

This issue is not specific to ASP.NET Core. To get a better and faster response we suggest you file the issue in https://github.com/dotnet/core-sdk/

**Comment by Pilchie** [comment]
Actually, I think this is https://github.com/dotnet/core/issues/3886.
