### ISSUE TITLE
SwaggerDoc extension method requires a Swashbuckle.AspNetCore.Swagger.Info parameter

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore#17309]
@DudePascalou commented on [Thu Nov 21 2019](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/236)

Before version 5.0.0 (which is not yet released, on november 2019), SwaggerDoc extension method requires a Swashbuckle.AspNetCore.Swagger.Info parameter. So, on "Add and configure Swagger middleware" section, you have to write :
```
    // Register the Swagger generator, defining 1 or more Swagger documents
    services.AddSwaggerGen(c =&gt;
    {
        c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
    });
```
Beginning with version 5.0.0, SwaggerDoc extension method now requires a Microsoft.OpenApi.Models.OpenApiInfo parameter.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Bien démarrer avec Swashbuckle et ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

---

@srvbpigh commented on [Thu Nov 21 2019](https://github.com/aspnet/AspNetCore.Docs.fr-fr/issues/236#issuecomment-557064088)

Hello, @DudePascalou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This seems to be question for the `Swashbuckle` owners at: https://github.com/domaindrivendev/Swashbuckle

**Comment by DudePascalou** [comment]
Well, you can close the issue and wait for version 5 to be released, so as the doc will be up to date.
I just wanted to add a comment on the doc page for those who will have the same problem I had.
