### ISSUE TITLE
Why can't I open Blazor WebAssembly App in Safari on iOS?

### ISSUE THREAD

**Issue by liyanjie8712** [aspnet/AspNetCore#17318]
[https://docs.microsoft.com/zh-cn/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.0](url)

This doc says that Blazor WebAssembly supported Safari on iOS and Chrome on Android,but I could't open the Blazor WebAssembly App in those browsers.
Both Safari and Chrome are latest.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This issue is being tracked at https://github.com/mono/mono/issues/16986
