### ISSUE TITLE
Allow manual start of TestHost over implicit start in constructor. 

### ISSUE THREAD

**Issue by Danielku15** [aspnet/AspNetCore#17329]
### Is your feature request related to a problem? Please describe.
I am having a small integration test class in my project based on the TestServer. For my tests I need to perform some actions on components **before** the application is started. The starting in the constructor will already trigger some IHostedServices to begin their logic before I can maybe interact with them or related changes required for testing. 

### Describe the solution you'd like
It would be good if there is a parameter for the TestServer that tells it NOT to trigger a direct start in the constructor. Instead a `StartAsync` method is offered and allows manual start. This way I can construct the TestServer, resolve services to interact with them, then start the application. 

### Additional context
The test server does a synchronous start of the IWebHost in the constructor: 
https://github.com/aspnet/AspNetCore/blob/88cda2751a4412b7d837ebe601c726ec1937538c/src/Hosting/TestHost/src/TestServer.cs#L55-L66

My main use case all come from the fact that I have some IHostedServices which are starting logic on startup: I have some IHostedService instance which will attempt a database access. I want to resolve a DbContext and call EnsureCreated to setup my test database before anything in the application starts. 

In my real application I get the chance to setup the IWebHost, resolve services for database setup and seeding, and then only start the rest of the application.

**Comment by Tratcher** [comment]
This work was already done in 3.0 for integration with IHostBuilder (but it should also work with IWebHostBuilder). See this example:
https://github.com/aspnet/AspNetCore/blob/6f2b107b88cfbc7d4293103a74162f9075257ce9/src/Hosting/TestHost/test/TestServerTests.cs#L53-L62

**Comment by Danielku15** [comment]
Great to hear that "will be" possible. Unfortunately I'm currently stuck to 2.x due to OData hence no migration is possible for me. But with knowing this is available there is no need for another change/feature.
