### ISSUE TITLE
Unable to set breakpoint on Blazor WebAssembly in Chrome

### ISSUE THREAD

**Issue by brice-fromentin** [aspnet/AspNetCore#17331]
I launch my application using VS with Chrome and the right flag "--remote-debugging-port=9222". I am able to Shift+Alt+D and see the source but when I try to set the breakpoint, I have an error and no breakpoint.

### To Reproduce

1. Create the default default Blazor Web Assembly
2. Make a browser configuration using chrome and setting argument "--remote-debugging-port=9222"
3. Launch the application in debug with VS using dotnet or IIS Express
4. On chrome page, Shift+Alt+D
5. Select source "Pages/FetchData.razor" in file:// section
6. Try to set a breakpoint on line 42
7. The breakpoint is appearing and disappears immediately with the error message in the dotnet window.

``` C# - The Line 42 is 
        forecasts = await Http.GetJsonAsync<WeatherForecast[]>("sample-data/weather.json");
```

The error message is :

BP request for 'BreakPointRequest Assembly: kairos.ui.dll File: C/Users/brice/Documents/Visual%20Studio%202019/R&D/Kairos.Ui/Kairos.Ui/Pages/FetchData.razor Line: 54 Column: 0' runtime ready True location ''
Could not resolve breakpoint request: BreakPointRequest Assembly: kairos.ui.dll File: C/Users/brice/Documents/Visual%20Studio%202019/R&D/Kairos.Ui/Kairos.Ui/Pages/FetchData.razor Line: 54 Column: 0
BP req {
  "lineNumber": 13,
  "url": "file:///C:/Users/brice/Documents/Visual Studio 2019/R&D/Kairos.Ui/Kairos.Ui/Pages/Counter.razor",
  "columnNumber": 8,
  "condition": ""
}

### Further technical details
- Chrome 78.0.3904.108
- ASP.NET Core version -> 3.1 Preview 3
- Blazor -> `Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview3.19555.2`
- Include the output of `dotnet --info`

> SDK .NET Core (reflétant tous les global.json) :
 Version:   3.1.100-preview3-014645
 Commit:    b32d27f4b3

> Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview3-014645\

> Host (useful for support):
  Version: 3.1.0-preview3.19553.2
  Commit:  13f35c3d86

> .NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]

> .NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]     

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
> Windows 10 Enterprise
Version 109
OS Version 18363.476
> Visual Studio Entreprise 2019 - 16.4.0 Preview 6.0

**Comment by brice-fromentin** [comment]
FYI

I tried the same thing but with a path for the project without any spaces, and it works.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#17879
