### ISSUE TITLE
Blazor WebAssembly debugging only works with HTTP, not HTTPS

### ISSUE THREAD

**Issue by rbeauchamp** [aspnet/AspNetCore#17338]
FYI, I'm observing that you can't debug while using SSL. When using SSL the file:// subsection does not show in the Sources tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by javiercn** [comment]
@rbeauchamp thanks for contacting us.

@SteveSandersonMS I believe this is an issue in the mono debug support, isn't it?

**Comment by SteveSandersonMS** [comment]
@javiercn I'm not sure. Were you able to repro this? Could you track it down to a specific error?

**Comment by javiercn** [comment]
@SteveSandersonMS I didn't try. I would imagine there's an issue with the mapping and that likely belongs to mono. @ryanbrandenburg or @ajaybhargavb might also know or could give this a try, since they've been working on the area.

**Comment by SteveSandersonMS** [comment]
I just experimented, and the fix is extremely trivial. The bug is in this line:

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Server/src/MonoDebugProxy/BlazorMonoDebugProxyAppBuilderExtensions.cs#L150

Notice how it hardcodes the querystring parameter name as `ws`. Simply replacing this name with `wss` if you're running on HTTPS fixes it.

**Comment by SteveSandersonMS** [comment]
cc @danroth27 FYI

**Comment by SteveSandersonMS** [comment]
Fixed in https://github.com/aspnet/AspNetCore/pull/17430

**Comment by rbeauchamp** [comment]
Awesome. Thank you for the fix!
