### ISSUE TITLE
'RenderTreeBuilder' does not exist in the namespace

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17339]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/829110/rendertreebuilder-does-not-exist-in-the-namespace.html)._

---
Hi 
Have tried to resolve  below error by searching the internet, without success any one have any idea how to resolve

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering' (are you missing an assembly reference?)	BlazorMVVM.Client	C:\ADiscover\Blazor Z2\BlazorMVVM-master\BlazorMVVM.Client\obj\Debug\netstandard2.0\RazorDeclaration\App.razor.g.cs	54	Active

Kind regards
Peter

---
#### Visual Studio Feedback System on 11/21/2019, 11:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It seems you're using either old tooling or old runtime bits. Please make sure you have installed the latest release of .NET Core 3.0 with the latest VS 2019. That should fix it.
If you still are facing issues, share some more details to help us investigate it.
- the output of `dotnet --info`
- screenshot of the the VS 2019 about page
