### ISSUE TITLE
Debug blazor application

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17341]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/830035/debug-blazor-application.html)._

---
Edit and continue does'nt work in pages.

---
#### Visual Studio Feedback System on 11/22/2019, 01:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're going to enable the `Live reload` feature for Blazor as part of https://github.com/aspnet/AspNetCore/issues/5456
