### ISSUE TITLE
Blazor @onclick event not firing when using Windows Authentication

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17347]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/819718/blazor-2.html)._

---
Hi 

Without changing a thing, I:

Creating a new Blazor App with default temple works great thank you.

Creating a new Blazor App changing the Authentication to **Windows Authentication**, I discovered that:

`<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>`  onclick event **does not fire**?

Is this a bug or am I missing something?

Using VS Community 2019 Version 16.3.9

Best regards

---
#### Johannes denToom on 11/13/2019, 09:17 PM: 

Changing the launchsetting.json file:<br><br> &quot;iisSettings&quot;: {<br>   &quot;windowsAuthentication&quot;: true,<br>   &quot;anonymousAuthentication&quot;: true,<br><br>onclick event fires again, however Windows Authentication doesn&#39;t<br><br>   &quot;anonymousAuthentication&quot;: false,<br><br>onclick event does not fire.<br><br><br><br>
#### Visual Studio Feedback System on 11/14/2019, 02:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Referencing this in case this is related: https://github.com/aspnet/AspNetCore/issues/14373

**Comment by javiercn** [comment]
Could you provide us with the browser and server logs?

Add this to your _Host.cshtml
```razor
    <script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        (function start() {
            Blazor.start({
                logLevel: 1, // LogLevel.Debug
                configureSignalR: builder => builder.configureLogging("debug") // LogLevel.Debug
            });
        })()
    </script>
```

Replace the logging section with this in your appSettings.json
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "Debug"
    }
  }
}
```

**Comment by ghidello** [comment]
I had the same issue using google chrome with the "Avast Online Security" extension. These are the console logs after loading the Counter page:
```
Information: Starting up blazor server-side application.
Information: Normalizing '_blazor' to 'https://localhost:44304/_blazor'.
Debug: Starting HubConnection.
Debug: Starting connection with transfer format 'Binary'.
Debug: Sending negotiation request: https://localhost:44304/_blazor/negotiate?negotiateVersion=1.
Debug: Selecting transport 'WebSockets'.
```
It looks like it stopped before logging the web socket connection. 

If I disable the Avast extension the application starts working normally and these are the console logs:
```
Information: Starting up blazor server-side application.
Information: Normalizing '_blazor' to 'https://localhost:44304/_blazor'.
Debug: Starting HubConnection.
Debug: Starting connection with transfer format 'Binary'.
Debug: Sending negotiation request: https://localhost:44304/_blazor/negotiate?negotiateVersion=1.
Debug: Selecting transport 'WebSockets'.
Information: WebSocket connected to wss://localhost:44304/_blazor?id=gB2WiOanTuJCjQvWyicSgQ.
Debug: The HttpConnection connected successfully.
Debug: Sending handshake request.
Information: Using HubProtocol 'blazorpack'.
Debug: Server handshake complete.
Debug: HubConnection connected successfully.
Debug: Received render batch with id 2 and 4592 bytes.
Debug: Applying batch 2.
Information: Blazor server-side application started.
Debug: Received render batch with id 3 and 122 bytes.
Debug: Applying batch 3.
```

These are the server logs: 
[server_logs_with_avast_plugin.log](https://github.com/aspnet/AspNetCore/files/3884003/server_logs_with_avast_plugin.log)
[server_logs_without_avast_plugin.log](https://github.com/aspnet/AspNetCore/files/3884002/server_logs_without_avast_plugin.log)

Before enabling the windows authentication I've never had a problem with this browser extensions.

**Comment by ant-blue-butterfly** [comment]
Thanks Everyone.

I've turned OFF the "Avast Online Security" extension as @ghidello suggested.  Fix the issue for me too.

Best regards

**Comment by javiercn** [comment]
@danroth27 @blowdart we had several reports about this issue.

Do we know of anyone we can follow up with?

I’m closing this issue as external.

**Comment by IgorKonicek** [comment]
Hi @ant-blue-butterfly @ghidello 
Can you please provide me more information about used AOS extension?
1) What version were you running when turn-off solved issue? - visible in `chrome://extensions/` and next to the extension name
2) If you open AOS UI (by clicking its icon near address bar) and you navigate yourself to settings. In section Privacy, Do you have any of following checkboxes on?
![dnt](https://user-images.githubusercontent.com/48209124/69857574-87228b00-1290-11ea-9829-a198423a64b5.png)

Thank you for answer

**Comment by ghidello** [comment]
Avast Online Security version 19.2.289
The extension icon appears greyed out on my blazor application but I'm testing on localhost and I don't know if that's the reason. If I press the icon while writing this message on github, none of the checkboxes in the "Automatically block all trackers" section is selected.
