### ISSUE TITLE
Blazor bootstrap css nav-item broken

### ISSUE THREAD

**Issue by rwolejko** [aspnet/AspNetCore#17357]
When I create bootstrap nav-item in my project, it looks different than an original bootstrap (first nav-item moves down a little bit).
It is because you have overwritten nav-item in site.css (template Blazor-Server, ver. 3.1.0-preview-3).
The NavMenu looks like you intended, however, creating custom navs becomes complicated and confusing.
Could you please fix the project template?
You can customize NavMenu using custom tags, keeping original bootstrap elements intact.
Regards,
Roman

**Comment by javiercn** [comment]
@rwolejko thanks for contacting us.

We will take a look at this. If you have a concrete suggestion we will also accept a PR with a fix if you are willing to make one.

**Comment by rwolejko** [comment]
Sorry for taking your time. I just figured out that I had outdated site.css (I created my project when 
3.1.0.preview2 was the actual version). After update, it looks that it has already been fixed.
You can close my issue.

Roman
