### ISSUE TITLE
Target microsoft.aspnetcore.mvc.newtonsoftjson to netstandard2.1

### ISSUE THREAD

**Issue by d1mnewz** [aspnet/AspNetCore#17368]
`microsoft.aspnetcore.mvc.newtonsoftjson` targets only .NET Core App 3.0 or 3.1.

### Describe the solution you'd like
Can we anyhow target that to .NET Standard 2.1 so it can be usable in class libraries?

cc: @BrennanConroy

**Comment by javiercn** [comment]
@d1mnewz thanks for contacting us.

`microsoft.aspnetcore.mvc.newtonsoftjson` only provides integration for Newtonsoft.Json in MVC. We are unlikely to change the target framework at this point. The netcoreapp target shouldn't prevent you from writing a library that references it. (You will just change the library target to 3.0-3.1).

Is there any reason why you need to target netstandard2.1? As an alternative you should be able to cross-compile and reference it in your 3.0-3.1 target framework.

**Comment by d1mnewz** [comment]
Right, however we were using some shared `MvcJsonOptions` between projects.

![image](https://user-images.githubusercontent.com/11834902/69560978-4dfaca00-0fb5-11ea-94ea-a07e1b566ab5.png)

but when migrating to .NET Core 3.1, `MvcNewtonsoftJsonOptions` turned out to be a part of `microsoft.aspnetcore.mvc.newtonsoftjson` which targets only .NET Core App.

![image](https://user-images.githubusercontent.com/11834902/69561134-84d0e000-0fb5-11ea-88f0-341a79fcbcdb.png)

Which leads us to the only conclusion that is here - just target .NET Core App 3.1 directly for library using `microsoft.aspnetcore.mvc.newtonsoftjson`. 
If that's anyhow a plan to make it a part of netstandard2.1, then I would not even bother and wait for it. 
If not, then I can just extract that into a separate library targeting netcoreapp3.1 and share it separately however still keep netstandard lib there.

**Comment by pranavkm** [comment]
> but when migrating to .NET Core 3.1, MvcNewtonsoftJsonOptions turned out to be a part of microsoft.aspnetcore.mvc.newtonsoftjson which targets only .NET Core App.

This was a breaking change between 2.2 and 3.0. 

> If that's anyhow a plan to make it a part of netstandard2.1

Unlike some extension packages, `Microsoft.AspNetCore.Mvc.NewtonsoftJson` is a feature of ASP.NET Core and consequently must target netcoreapp3.x. See https://github.com/aspnet/Announcements/issues/324. If you'd like to to continue supporting older versions of ASP.NET Core, you could consider cross-compiling: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#migrate-libraries-via-multi-targeting

**Comment by d1mnewz** [comment]
Alright, thanks for clarifying it!
