### ISSUE TITLE
Regression with Blazor 3.1.0-preview3

### ISSUE THREAD

**Issue by joshcomley** [aspnet/AspNetCore#17365]
(apologies for the vague title, I don't really know how to title this)

### Describe the bug
I have been successfully using Roslyn in Blazor for quite some time, now. However, going from `3.1.0-preview2` to `3.1.0-preview3` it has stopped working, blowing up internally within `CodeAnalysis`. When getting symbol info for certain things, this happens (identical code running anywhere else works, including `3.1.0-preview2`):

	blazor.webassembly.js:1 WASM: ?Unhandled exception rendering component:
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM: System.NullReferenceException: Object reference not set to an instance of an object.
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.SmallDictionary`2[K,V].Insert (System.Int32 hashCode, K key, V value, System.Boolean add) [0x00097] in /_/src/Compilers/Core/Portable/Collections/SmallDictionary.cs:316 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.SmallDictionary`2[K,V].Add (K key, V value) [0x00000] in /_/src/Compilers/Core/Portable/Collections/SmallDictionary.cs:78 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeMap..ctor (Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol containingType, System.Collections.Immutable.ImmutableArray`1[T] typeParameters, System.Collections.Immutable.ImmutableArray`1[T] typeArguments) [0x0002c] in /_/src/Compilers/CSharp/Portable/Symbols/TypeMap.cs:69 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Symbols.ConstructedNamedTypeSymbol..ctor (Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol constructedFrom, System.Collections.Immutable.ImmutableArray`1[T] typeArgumentsWithAnnotations, System.Boolean unbound) [0x00000] in /_/src/Compilers/CSharp/Portable/Symbols/ConstructedNamedTypeSymbol.cs:45 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.ConstructCore (System.Collections.Immutable.ImmutableArray`1[T] typeArguments, System.Boolean unbound) [0x00000] in /_/src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs:1074 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Construct (System.Collections.Immutable.ImmutableArray`1[T] typeArguments, System.Boolean unbound) [0x00087] in /_/src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs:1069 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Construct (System.Collections.Immutable.ImmutableArray`1[T] typeArguments) [0x00000] in /_/src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs:1032 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.ConstructNamedType (Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, Microsoft.CodeAnalysis.SyntaxNode typeSyntax, Microsoft.CodeAnalysis.SeparatedSyntaxList`1[TNode] typeArgumentsSyntax, System.Collections.Immutable.ImmutableArray`1[T] typeArguments, Roslyn.Utilities.ConsList`1[T] basesBeingResolved, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x00000] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1267 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindGenericSimpleNamespaceOrTypeOrAliasSymbol (Microsoft.CodeAnalysis.CSharp.Syntax.GenericNameSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Roslyn.Utilities.ConsList`1[T] basesBeingResolved, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt) [0x0008a] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1055 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol (Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Roslyn.Utilities.ConsList`1[T] basesBeingResolved, System.Boolean suppressUseSiteDiagnostics) [0x000d7] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:409 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias (Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Roslyn.Utilities.ConsList`1[T] basesBeingResolved) [0x00000] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:312 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindType (Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol& alias, Roslyn.Utilities.ConsList`1[T] basesBeingResolved) [0x00000] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:301 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOf (Microsoft.CodeAnalysis.CSharp.Syntax.TypeOfExpressionSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x0000e] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1199 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal (Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Boolean invoked, System.Boolean indexed) [0x0052f] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:581 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression (Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Boolean invoked, System.Boolean indexed) [0x00000] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:408 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindValue (Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Binder+BindValueKind valueKind) [0x00000] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:228 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindInferredVariableInitializer (Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax initializer, Microsoft.CodeAnalysis.CSharp.Binder+BindValueKind valueKind, Microsoft.CodeAnalysis.RefKind refKind, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode errorSyntax) [0x00047] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:844 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration (Microsoft.CodeAnalysis.CSharp.Symbols.SourceLocalSymbol localSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.LocalDeclarationKind kind, System.Boolean isVar, Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax declarator, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax typeSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations declTypeOpt, Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol aliasOpt, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Boolean includeBoundType, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode associatedSyntaxNode) [0x0007b] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:977 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration (Microsoft.CodeAnalysis.CSharp.Symbols.LocalDeclarationKind kind, System.Boolean isVar, Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax declarator, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax typeSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations declTypeOpt, Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol aliasOpt, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Boolean includeBoundType, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode associatedSyntaxNode) [0x00000] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:920 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts (Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x00054] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:674 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement (Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x0001f] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:649 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement (Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x000d2] in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:48 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel+IncrementalBinder.BindStatement (Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x0001d] in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:2337 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind (Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x00044] in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:2249 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind (Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x00076] in /_/src/Compilers/CSharp/Portable/Compilation/MethodBodySemanticModel.cs:97 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes (Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node) [0x00072] in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:2046 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode (Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node) [0x00000] in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:535 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes (Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode& bindableNode, Microsoft.CodeAnalysis.CSharp.BoundNode& lowestBoundNode, Microsoft.CodeAnalysis.CSharp.BoundNode& highestBoundNode, Microsoft.CodeAnalysis.CSharp.BoundNode& boundParent) [0x00039] in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:1330 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker (Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel+SymbolInfoOptions options, System.Threading.CancellationToken cancellationToken) [0x00006] in /_/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:1208 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker (Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel+SymbolInfoOptions options, System.Threading.CancellationToken cancellationToken) [0x0001c] in /_/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:211 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo (Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression, System.Threading.CancellationToken cancellationToken) [0x000e8] in /_/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:569 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo (Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression, System.Threading.CancellationToken cancellationToken) [0x0000a] in /_/src/Compilers/CSharp/Portable/CSharpExtensions.cs:449 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at BlazorApp3.Class.Boot () [0x0023c] in C:\Users\Josh Comley\source\repos\BlazorApp3\BlazorApp3\Class.cs:107 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at BlazorApp3.Shared.MainLayout.OnInitializedAsync () [0x0001a] in C:\Users\Josh Comley\source\repos\BlazorApp3\BlazorApp3\Shared\MainLayout.razor:19 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x302bb88 + 0x0013e> in <44d78cab266c4647aa96aadd4455da2c>:0 
	p.printErr @ blazor.webassembly.js:1
	blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x3ca5460 + 0x000be> in <44d78cab266c4647aa96aadd4455da2c>:0 

### To Reproduce
Clone: https://github.com/joshcomley/BlazorRegression1

Run as-is, with `3.1.0-preview2`. Once it boots, the symbol name should be logged to the console and no errors.

Update to `3.1.0-preview3`, run again, and it crashes out.

### Further technical details
VS2019 Version 16.4.0 Preview 6.0

.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview3-014645
 Commit:    b32d27f4b3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview3-014645\

Host (useful for support):
  Version: 3.1.0-preview3.19553.2
  Commit:  13f35c3d86

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009648 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009748 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009804 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@joshcomley thanks for contacting us.

This might be a linker issue. Have you tried disabling the linker?

**Comment by joshcomley** [comment]
Thanks for the suggestion! I'm out at the moment, but I will try as soon as I get home... But how do I disable the linker? :)

**Comment by javiercn** [comment]
```
<PropertyGroup>
  <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
</PropertyGroup>
```

**Comment by joshcomley** [comment]
Wonderful, thank you. I'll give it a go

**Comment by joshcomley** [comment]
Disabling the linker did not fix the issue, unfortunately

**Comment by benjamin-hodgson** [comment]
I'm experiencing this issue too. Is there anything I can do to help?

**Comment by javiercn** [comment]
This issue was moved to mono/mono#18119
