### ISSUE TITLE
Blazor @ref for dynamically generated elements

### ISSUE THREAD

**Issue by MV10** [aspnet/AspNetCore#17361]
I have a scenario where an `@foreach` loop iterates over an externally-provided `List<>` parameter to generate a series of Razor components from a third-party library. After the content is rendered, other interactions trigger certain methods on those components, but I don't see a clean way to use `@ref` to address them.

I'm going try pointing the `@ref` to a property setter and use that to store `value` in a dictionary but it feels pretty hacky, and I suspect that could leak those references if the component is re-rendered (maybe this calls for `WeakReference<T>`?)

**Comment by javiercn** [comment]
@MV10 thanks for contacting us.

@SteveSandersonMS Will an array of element references work here?

**Comment by SteveSandersonMS** [comment]
This isn't something we specifically set out to support, but yes, you can use a dictionary. For example:

```razor
@foreach (var id in identifiers)
{
    <Index @ref="myComponents[id]" />
}

@code {
    private List<string> identifiers = new List<string> { "Alpha", "Beta", "Gamma" };
    private Dictionary<string, Index> myComponents = new Dictionary<string, Index>();
}
```

This will initally populate `myComponents` with three entries (for keys alpha/beta/gamma). If you add new items to `identifiers` later and re-render, it will add new entries to `myComponents`.

The tricky bit is that it doesn't give any obvious way to *remove* items from `myComponents` if they are removed from the UI. Presumably you can handle that in application code though. If you know you're removing something from `identifiers`, then also delete the corresponding keyed item from `myComponents`.
