### ISSUE TITLE
SignalR Core Client fail to connect with SignalR Core Hub behind the Load Balancer

### ISSUE THREAD

**Issue by ereadersworld** [aspnet/AspNetCore#17369]
The SignalR Service is built with Asp.Net Core 2.2 and hosted on two nodes behind the Load Balancer.

SignalR client is able to establish the connection with Individual nodes. But when SignalR client points to Load Balancer then it is not able to establish the connection with the Hub.
I have captured the Event Logs from both the nodes. It is observed that the HTTP request to establish SignalR connection is going to different nodes which is causing connection handshake failure.

**Node 1 event logs:**
Microsoft.AspNetCore.Hosting.Internal.WebHost
Request starting HTTP/1.1 POST https://myserver/api/v1/rt/negotiate 0
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler
Successfully validated the token.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService
Authorization was successful.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager
New connection EzD87fWpmWpiuAc8SExNUA created.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher
Sending negotiation response.
Microsoft.AspNetCore.Hosting.Internal.WebHost
Request starting HTTP/1.1 GET https://myserver/api/v1/rt?id=EzD87fWpmWpiuAc8SExNUA
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler
Successfully validated the token.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService
Authorization was successful.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher
Establishing new connection.
Microsoft.AspNetCore.SignalR.HubConnectionHandler
OnConnectedAsync started.
Microsoft.AspNetCore.SignalR.HubConnectionContext
Failed connection handshake.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager
Removing connection EzD87fWpmWpiuAc8SExNUA from the list of connections.

**Node 2 event logs:**
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService
Authorization was successful.
Microsoft.AspNetCore.Hosting.Internal.WebHost
Request starting HTTP/1.1 POST https://myserver/api/v1/rt?id=EzD87fWpmWpiuAc8SExNUA 32

One available solution is to enable “Client Affinity” on Load Balancer where the connection is established.

But in .Net framework 4.6.1 we had used `machinekey` to resolve the similar issue without using Client Affinity on Load Balancer. 

Do we have any similar solution in .Net core 2.2 SignalR i.e. we do not have to use Client Affinity?

Please Help!

**Comment by BrennanConroy** [comment]
Sticky Sessions are **required** for ASP.NET Core SignalR.

You can read some details in the docs https://docs.microsoft.com/aspnet/core/signalr/scale?view=aspnetcore-3.0#sticky-sessions
