### ISSUE TITLE
Consider adding a library for Blazor UI components to the "aspnet" org

### ISSUE THREAD

**Issue by chrgraefe** [aspnet/AspNetCore#17363]
As Balzor is growing very fast it is useful to concentrate the effort into a major repository to build simple controls that are needed for SPA's.

I think of a library like winforms, which is also open source and maintained in a Microsoft repository.

There are already many controls available in different libraries in different qualities.
With this basement is it possible to build apps faster and more reliable.

Possible controols:
- Modal dialog
- Toasts
- FileUpload
- Table/Grid (Sortable/Filterable/Groupable)
- Menu
- IndexedDB
- etc.

**Comment by javiercn** [comment]
@chrgraefe Thanks for contacting us.

We are currently focusing on efforts on building the framework and it is unlikely we will tackle this in the immediate future. There are many 3rd party component libraries out there already with Blazor controls that can be used to accelerate application development.

I'll leave this issue open for now until it gets properly triaged.

**Comment by stsrki** [comment]
@chrgraefe There is already a bunch of components library that you can choose from: [MatBlazor](https://github.com/SamProf/MatBlazor), [BlazorStrap](https://github.com/chanan/BlazorStrap) or [Blazorise](https://github.com/stsrki/Blazorise). You can also visit an [awesome list](https://github.com/AdrienTorris/awesome-blazor) of Blazor resources to find more of them.

PS I'm a creator of Blazorise.

**Comment by mkArtakMSFT** [comment]
We have no plans to do this, so please refer to @stsrki 's suggestions.
