### ISSUE TITLE
RequestSizeLimit doesn't prevent the action from executing

### ISSUE THREAD

**Issue by thomaslevesque** [aspnet/AspNetCore#17376]
### Describe the bug
Setting a request size limit on a controller action doesn't prevent the action from executing when the body is larger than the specified size.

### To Reproduce
Write this code in a controller

```csharp
[HttpPost("test")]
[RequestSizeLimit(1024)]
public async Task<IActionResult> Test()
{
    using var reader = new StreamReader(Request.Body);
    string text = await reader.ReadToEndAsync();
    return Ok();
}
```

Send a request with a body larger than 1024 bytes.

**Expected:** the action isn't executed, and a 413 response is returned
**Actual:** the action is executed. The call to `reader.ReadToEndAsync()` throws `BadHttpRequestException: Request body too large`

Is my expectation incorrect? Am I using `RequestSizeLimit` incorrectly?

### Further technical details
- ASP.NET Core version: 2.1

- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS 2019 16.3.9

Server: Kestrel

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@Tratcher is this by-design?

**Comment by Tratcher** [comment]
Correct, the limit is only enforced when actually reading the body. If you're using model binding then that will happen before the action is executed. If you're not then it will only be enforced when you try to read the body directly.

Keep in mind that declaring a Content-Length on requests is optional, in many cases (Chunked, Http/2, etc.) the only way to know how long the body is is to read it.

Note Kestrel will catch that BadHttpRequestException and convert it to a 413 response by default.

**Comment by thomaslevesque** [comment]
@Tratcher thanks. Indeed, the Content-Length might not be known in advance. For me a response with status code 500 was returned, but that's probably because of my custom exception handling middleware. I should probably let Kestrel exceptions bubble up instead of handling them.

**Comment by thomaslevesque** [comment]
> Note Kestrel will catch that BadHttpRequestException and convert it to a 413 response by default.

Are you sure about this? I just tried it in a fresh project with no custom middleware, and I still got a 500.

**Comment by thomaslevesque** [comment]
Ah, if I remove the DeveloperExceptionPage middleware, I get a 413.
