### ISSUE TITLE
Possible to set client validation on class level using IClientModelValidator interface

### ISSUE THREAD

**Issue by shantrendz** [aspnet/AspNetCore#17371]
Currently, IClientModelValidator interface gets implemented when validation attributes are set at property level. What if we set validation attributes at Class level? Server side validation works fine for this scenario. But Client side validation not getting fired.

The below lines not getting executed on runtime when we use [AttributeUsage(AttributeTargets.Class)].

public void AddValidation(ClientModelValidationContext context)
{
           MergeAttribute(context.Attributes, "data-val", "true");
            var errorMessage = FormatErrorMessage(context.ModelMetadata.GetDisplayName());
            MergeAttribute(context.Attributes, "data-val-required", errorMessage);
}

Will iterate all properties using System.Reflection namespace.

Is it attach client side attribute at class level ?

**Comment by pranavkm** [comment]
@shantrendz could you share a minimal app with the setup that you have? It's not entirely clear how you have configured things and what isn't working.

**Comment by shantrendz** [comment]
Will provide the sample coding for this scenario in next two days

**Comment by pranavkm** [comment]
Feel free to reopen this issue once you have a minimal app to share.
