### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation refers to incompatible packages

### ISSUE THREAD

**Issue by gthvidsten** [aspnet/AspNetCore#17374]
### Description
The `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` NuGet package references other packages which will cause errors and warnings from the compiler (on new ASP.NET Core 3.0 projects).

### Reproduce
When trying to add the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` NuGet package to a new ASP.NET Core 3.0 project an error occurs complaining about version mismatch.
> Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.3.0 directly to project MyProject to resolve this issue.
> MyProject -> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 3.0.0 -> Microsoft.CodeAnalysis.Razor 3.0.0 -> Microsoft.CodeAnalysis.Common (>= 3.3.0)

The next natural step would be to install `Microsoft.CodeAnalysis.Common 3.3.1` (3.3.0 doesn't exist). Now you can install `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation`, but then other warnings show up about version mismatches:

> Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp 3.3.0 requires Microsoft.CodeAnalysis.Common (= 3.3.0) but version Microsoft.CodeAnalysis.Common 3.3.1 was resolved`
> Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Workspaces 2.8.0 requires Microsoft.CodeAnalysis.CSharp (= 2.8.0) but version Microsoft.CodeAnalysis.CSharp 3.3.0 was resolved
> Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Workspaces.Common 2.8.0 requires Microsoft.CodeAnalysis.Common (= 2.8.0) but version Microsoft.CodeAnalysis.Common 3.3.1 was resolved

Now, these are strictly speaking only warnings and everything should continue to work, but they do point at some major inconsistencies when it comes to NuGet packages and their references.

### Expected

`Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` should be installed in new ASP.NET Core 3.0 projects without any package version conflicts.

### Technical details
- ASP.NET Core 3.0
- Visual Studio 2019 16.3.9 (16.3.10 does not list this as fixed)
```
C:\>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please share with us the project file you're observing this issue with.

**Comment by gthvidsten** [comment]
Here's the project file (anonymized):

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RootNamespace>MyNamespace</RootNamespace>
    <AssemblyName>MyAssembly</AssemblyName>
    <Configurations>Debug;Release</Configurations>
    <Version>0.0.1-prealpha</Version>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="appsettings.Debug.json" />
    <Content Remove="appsettings.Development.json" />
    <Content Remove="appsettings.json" />
    <Content Remove="appsettings.Release.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Some\Other\Library.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\fonts\" />
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.Debug.json">
      <IsTransformFile>true</IsTransformFile>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Include="appsettings.json">
      <TransformOnBuild>true</TransformOnBuild>
    </None>
    <None Include="appsettings.Release.json">
      <IsTransformFile>true</IsTransformFile>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Views\SomeView.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SomeView.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Views\SomeOtherView.de-DE.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\SomeOtherView.nb-NO.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\SomeOtherView.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SomeOtherView.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\SomeOtherView.fr-FR.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JSONSchema="" /></VisualStudio></ProjectExtensions>

</Project>
```

**Comment by pranavkm** [comment]
@gthvidsten can you include the entire message when you see a conflict? I trimmed down the project to:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
  </ItemGroup>
```

Note that the `Microsoft.CodeAnalysis.Common` is removed and it restores fine without an error. What would help is a minimal project that reproduces the build warning. 

> The next natural step would be to install Microsoft.CodeAnalysis.Common 3.3.1 (3.3.0 doesn't exist)

You generally shouldn't need to reference it manually, but the 3.3.0 version exists on nuget.org: https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/3.3.0

**Comment by gthvidsten** [comment]
These are the full warnings in the output window in Visual Studio:

> C:\My\Solution\MyProject\MyProject.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp 3.3.0 requires Microsoft.CodeAnalysis.Common (= 3.3.0) but version Microsoft.CodeAnalysis.Common 3.3.1 was resolved.
> C:\My\Solution\MyProject\MyProject.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Workspaces 3.3.0 requires Microsoft.CodeAnalysis.Common (= 3.3.0) but version Microsoft.CodeAnalysis.Common 3.3.1 was resolved.
> C:\My\Solution\MyProject\MyProject.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Workspaces.Common 3.3.0 requires Microsoft.CodeAnalysis.Common (= 3.3.0) but version Microsoft.CodeAnalysis.Common 3.3.1 was resolved.

Also, even if 3.3.0 exists on nuget.org, it can't be installed because it is not visible:

![Image of nuget.org version list](https://i.imgur.com/DzG9udp.jpg)

If it helps, this was originally an ASP.Net Core 2.2 project that has been upgraded to 3.0, it wasn't a brand new 3.0 project as the original post might have implied.

**Comment by gthvidsten** [comment]
I just removed reference to the `Microsoft.CodeAnalysis.Common` package from my project, and the project still has the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` referenced, and for some reason the warnings disappeared! Why the warnings disappeared, though, I don't know. 

The original issue still remains, though, that installing `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` failed because of version mismatch of packages. Maybe it is only an issue on projects that have been upgraded from `netcoreapp22` to `netcoreapp30` and not on brand new projects.

**Comment by pranavkm** [comment]
> The original issue still remains, though, that installing Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation failed because of version mismatch of packages.

Could you specify the error in this case? A minimal repro app would really help investigating this.

**Comment by gthvidsten** [comment]
The error is stated in the original post, but I can paste it again here for brevity:

> Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.3.0 directly to project MyProject to resolve this issue.
MyProject -> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 3.0.0 -> Microsoft.CodeAnalysis.Razor 3.0.0 -> Microsoft.CodeAnalysis.Common (>= 3.3.0)

**Comment by pranavkm** [comment]
@gthvidsten is there any more to the conflict message? It looks like it's missing the other edge that it's conflicting with.

**Comment by gthvidsten** [comment]
That was the only error message that appeared in the output window when I tried to install the package.

**Comment by kinetiq** [comment]
I'm getting this too. 

Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.3.0 directly to project Keystone.Web to resolve this issue. 
 Keystone.Web -> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 3.1.0 -> Microsoft.CodeAnalysis.Razor 3.1.0 -> Microsoft.CodeAnalysis.Common (>= 3.3.0) 
 Keystone.Web -> Telerik.UI.for.AspNet.Core 2019.2.619 -> Microsoft.CodeAnalysis 3.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 3.0.0 -> Microsoft.CodeAnalysis.Common (= 3.0.0).

**Comment by pranavkm** [comment]
@gthvidsten there isn't much for us to investigate here unless you can share an app that reproduces this error. As @kinetiq pointed out, perhaps there are other outdated dependencies in your project reference graph.
