### ISSUE TITLE
Typo in the Create a new Project window. Blazor App

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17384]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/832375/typo-in-the-create-a-new-project-window-blazor-app.html)._

---
- Project templates for creating Blazor apps _that that_ run on the server in ASP.NET Core app or in the browser on WebAssembly. These templates can be used to build web apps with rich dynamic user interfaces (UIs)

---
#### Visual Studio Feedback System on 11/25/2019, 02:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@vijayrkn isn't this something your have control of?

**Comment by vijayrkn** [comment]
Ya, This is in our internal repo. Will get this fixed. 

+ @phenning

**Comment by mkArtakMSFT** [comment]
Thanks @vijayrkn! Closing this as external.
