### ISSUE TITLE
How can install preview version of SDKs in linux using CLI

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#17381]
I want to install the .net core 3.1 preview 3 in linux machine using command line

Is there any ways to install the preview versions of .Net Core SDKs in linux machine using command line?

For example,

> sudo apt-get update

> sudo apt-get install apt-transport-https

> sudo apt-get update

> sudo apt-get install dotnet-sdk-3.0

Above Command used to install the SDK 3.0 in linux. Now i want to install latest .net core 3.1 preview 3 by the same way.

Is this possible?  Please help me on this?

**Comment by pranavkm** [comment]
This might be of help: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script. If you have specific questions about using the script, I'll recommend filing an issue in https://github.com/dotnet/core-sdk
