### ISSUE TITLE
Razor Class Library Model Conflict Causes Invalid Operation Exception

### ISSUE THREAD

**Issue by jmnorville** [aspnet/AspNetCore#17388]
### Describe the bug
When running an ASP.NET Core MVC application with references to two or more Razor Class Libraries that contain Models with the same name, an Invalid Operation Exception occurs:
Exact error message:

> InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'TestRCL2.Models.GeneralModel', but this ViewDataDictionary instance requires a model item of type 'TestRCL1.Models.GeneralModel'.

### To Reproduce
A sample application is attached that will allow you to recreate the error.   This application references two simple Razor Class Libraries.  Each RCL has a model named "GeneralModel".  In our real solution, these two models are two totally different animals.
1) Run application and click the "Load RCL 1 Content" button.
2) The click the "Load RCL 2 Content" button.
3) Open the Browser's development tools and click on error in the console.

``` C#
Sample project is attached.

Exception and stack trace:

An unhandled exception occurred while processing the request.
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'TestRCL2.Models.GeneralModel', but this ViewDataDictionary instance requires a model item of type 'TestRCL1.Models.GeneralModel'.
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(object value)

Stack Query Cookies Headers
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'TestRCL2.Models.GeneralModel', but this ViewDataDictionary instance requires a model item of type 'TestRCL1.Models.GeneralModel'.
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(object value)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, object model, Type declaredModelType)
lambda_method(Closure , ViewDataDictionary )
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.CreateViewDataDictionary(ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.Activate(object page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.ExecuteAsync(ActionContext context, PartialViewResult result)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync<TFilter, TFilterAsync>()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Further technical details
- ASP.NET Core version **2.2**
- Include the output of `dotnet --info` **see attached
![DotnetInfo](https://user-images.githubusercontent.com/48520113/69574377-f5680480-0f95-11ea-8cfc-6fe6ebfe41ff.JPG)
[TestRCLApp.zip](https://github.com/aspnet/AspNetCore/files/3888528/TestRCLApp.zip)

**
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version **Visual Studio 2017**

**Comment by javiercn** [comment]
@jmnorville thanks for contacting us.

I've edited the post for clarity.

What is happening is that you have two views in the same path and RCLs only allow the main app to override views in the same path. Having class libraries with views on the same path is not supported. The behavior in that case is undefined.

@pranavkm don't we throw here? Are we missing a check?

**Comment by pranavkm** [comment]
> @pranavkm don't we throw here? Are we missing a check?

Views are treated like a set, there aren't any rules about having views with the same name. 

Razor Class Libraries do not provide any special scoping mechanism. When you say `Partial("SomeView")`, the view is looked up across all available views. The closest you could get is adding views to areas that differ by name to isolate them to an extent.

**Comment by jmnorville** [comment]
Thank you for the quick response.  We have already uniquely re-named the Model and View in both RCLs to work around the issue.  But, we have several developers working on RCLs and one is not going to know what the other developers are naming their Model and Views.  If the Dictionary the CLR is building is keyed by Namespace in addition to it's current Keys, the issue should be resolvable.  Can you look into?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@jmnorville there is nothing more except the above two proposals we can do. And we don't plan to change this logic going forward.

**Comment by jmnorville** [comment]
I added the Views that are for exclusive use by the RCL out of the ...Views/Shared directory into the Views/MyControllerName folder.  This alleviated the conflict I was having.
