### ISSUE TITLE
Endpoint Routing: Find The matching route endpoint

### ISSUE THREAD

**Issue by mgolois** [aspnet/AspNetCore#17391]
@rynowak while upgrading from .net core 2.2 to 3.0 these lines of code are no longer working. Am I missing anything? Perhaps, the way we are doing template matching have surely changed to a pattern matching. Let me know your thoughts:

```
    public RouteEndpoint GetRouteEndpoint(string path)
        {
                      
            var routeEndpoints = _endpointDataSource.Endpoints.Cast<RouteEndpoint>();
          
            var matchedEndpoint = routeEndpoints.Where(e => new TemplateMatcher(
                                                                        TemplateParser.Parse(e.RoutePattern.RawText),
                                                                        new RouteValueDictionary())
                                                                .TryMatch(path, new RouteValueDictionary()))
                                                .OrderBy(c => c.Order)
                                                .FirstOrDefault();            
            return matchedEndpoint;        
        }
```

**Comment by rynowak** [comment]
Can you be more specific about what's not working in your scenario?

**Comment by mgolois** [comment]
@rynowak given a path "/Home/Contact", I would like to return the matched route endpoint. I have a total of over 100 `routeEndpoints` , but currently for "/" path, the `matchedEndpoint` is null. This code used to work on .net core 2.2, but when I upgraded 3.0, seems like the TemplateMatcher is not quite working as before, unless there is another way to find the matching out without going thru the httpContext.

**Comment by mgolois** [comment]
@rynowak I found the issue, Default route values are now located on routeEndpoint.RoutePattern.Default
