### ISSUE TITLE
Blazor: Add IHandleBeforeRender

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/AspNetCore#17392]
With reference to this ticket https://github.com/aspnet/AspNetCore/issues/17361 (Blazor @ref for dynamically generated elements) and specifically this proposed solution https://github.com/aspnet/AspNetCore/issues/17361#issuecomment-558138782

It would be useful if we could implement a new IHandleBeforeRender on our components so we can clear down a collection of ElementReference before the IHandleAfterRender re-populates.

At the moment we have to try to determine which items in the dictionary to remove based on the data we are rendering, but if this is a list of values (such as integers) then it is not possible to determine which items to remove. Having an IHandleBeforeRender interface would give us the ability to completely clear down the dictionary before its values are reassigned by IHandleAfterRender.

AND/OR

Have a new type ElementReferences which Blazor will clear down at the start of a render, and add every new element to when it sees @ref="ThePropertyOfTypeElementReferences"

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

You can do this with a code fragment at the beginning of the component file.
```razor
@{
    _dictionary.Clear();
}
```

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.
