### ISSUE TITLE
Cannot Run Integration Tests on Linux

### ISSUE THREAD

**Issue by luhis** [aspnet/AspNetCore#17390]
### Describe the bug
I am attempting to use WebApplicationFactory to run some integration tests against my project.  They work fine in Windows, but if i run them in Linux (through CircleCI or on my Ubuntu machine) it tries to launch Kestrel

### To Reproduce
- Checkout https://github.com/luhis/CodeGolf/tree/integration_tests
- Move to ./test/CodeGolf.Integration.Test/
- run `dotnet test`

Linux Example:
```
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {d57571d0-d43b-497c-8a7a-320fe81987d1} may be persisted to storage in unencrypted form.
```
link: https://circleci.com/gh/luhis/CodeGolf/1616?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
The Linux example is outputting some config complaints, but I think that's unrelated to my issues.

Windows Output:
```
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.


Test Run Successful.
Total tests: 3
     Passed: 3
 Total time: 9.2560 Seconds
```

### Further technical details
- DotNetCore 3.0.101

**Comment by javiercn** [comment]
@luhis thanks for contacting us.

I don't see how the example is trying to start kestrel. The logs that you mention come from data protection as it is warning that the keys will be stored unencrypted and that's expected.

Unless you see an output indicating that it is listening on port XXXX it is not starting any real server.

I'm closing this issue as there is no bug here.

**Comment by luhis** [comment]
you are right. kestrel is not running, but the test was continuing to run until it timed out on the test server.  the issue really was related to the missing settings, correcting that made the test pass in Linux the same as Windows
