### ISSUE TITLE
A way to change IFileProvider that FileVersionProvider (asp-append-version) is using?

### ISSUE THREAD

**Issue by datvm** [aspnet/AspNetCore#17409]
### Is your feature request related to a problem? Please describe.
I want to be able to serve files with a custom file path (`js/v1/foo.js` can be mapped to a real file at `wwwroot/js/foo.js`). I created `VersionedFileProvider` which could map that already. I set it like this:

        app.UseStaticFiles(new StaticFileOptions()
        {
            FileProvider = new CompositeFileProvider(
                new VersionedFileProvider(env.WebRootPath),
                env.WebRootFileProvider),
        });

All files are working. However, if I use that custom path, `asp-append-version` does not work. When I check the [source code](https://github.com/aspnet/AspNetCore/blob/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0/src/Mvc/Mvc.Razor/src/Infrastructure/DefaultFileVersionProvider.cs), they are taking `WebRootFileProvider` instead of the one I am setting in `UseStaticFiles`.

Luckily, `env.WebRootFileProvider` is settable, so I can resolve the problem with:

        env.WebRootFileProvider = new CompositeFileProvider(
            new VersionedFileProvider(env.WebRootPath),
            env.WebRootFileProvider);
        app.UseStaticFiles();

For now I have not seen any problem yet. However, I have to admit I do not know what else is using `WebRootFileProvider` and what side-effect can possibly happen. Please help me confirm this is a proper way to resolve my issue.

### Describe the solution you'd like
Can we have a way to set `IFileProvider` that `FileVersionProvider` is using? Or at least a documentation text that confirms setting `env.WebRootFileProvider` is okay? Thank you.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The way you've configured it is what we would also recommend.
