### ISSUE TITLE
How to obtain IEnumerable<ValidationResult> from ValidationAttribute in Asp Core

### ISSUE THREAD

**Issue by shantrendz** [aspnet/AspNetCore#17406]
In Asp Mvc version, it was possible to get IEnumerable<ValidationResult> on IsValid method by using IValidatableObject interface.

 **public IEnumerable<ValidationResult> Validate(ValidationContext validationContext) {
// yield collection of validation results here
}**

But in Asp Core version, we intended to use ValidationAttribute to achieve custom validations. But, available method return only single ValidationResult.

**protected override ValidationResult IsValid(object value, ValidationContext validationContext) {
// custom validation
}**

What if, we need to throw multiple ValidationResult in single event?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by shantrendz** [comment]
> 
> 
> Hi. It looks like this is a question about how to use .NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com).

Is there any class or interface available in .Net Core Packages to get IEnumerable<ValidationResult>? It is really needed, when we do dynamic validation at class level.
Would appreciate for quick reply.
