### ISSUE TITLE
LinkParser: endpoints with a duplicate endpoint name were found

### ISSUE THREAD

**Issue by mgolois** [aspnet/AspNetCore#17417]
@rynowak Thanks for the `LinkParser`. I'm having an exception with the code below. I'm trying to get the route values from a given route endpoint and path string.

```var routeValue = _linkParser.ParsePathByEndpointName(routeEndpoint.DisplayName, path);```

```
System.InvalidOperationException: 'The following endpoints with a duplicate endpoint name were found.

Endpoints with endpoint name 'C':
Route: C/{cId}/A/{vId}/{controller}/{action}/{id}
Route: C/{cId}/A/{vId}/{controller}/{action}/{id}

Endpoints with endpoint name 'CDefault':
Route: C/{cId}/{controller}/{action}/{id?}
Route: C/{cId}/{controller}/{action}/{id?}

...
...
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
