### ISSUE TITLE
Set response Content-length to prevent 'Transfer-Encoding: chunked'

### ISSUE THREAD

**Issue by Superllb93** [aspnet/AspNetCore#17413]
Recently, I tried to use docker for linux to run my ASP .NET Core project based on .net core 3.0, but, some problems blocked me all day.

After published the application on docker successfully for the first time,  error appeared when I visited the home page

![image](https://user-images.githubusercontent.com/49815294/69633438-2ece6c00-108b-11ea-9ecf-ea3c5ae02d83.png)

![image](https://user-images.githubusercontent.com/49815294/69633364-05addb80-108b-11ea-925f-139be6f2f0f6.png)

I run `curl http://localhost:5001/Account/Login` on server

![image](https://user-images.githubusercontent.com/49815294/69633778-d2b81780-108b-11ea-8183-d78ffa7a423b.png)

> https://github.com/aspnet/KestrelHttpServer/issues/2417 told me that Kestrel always add transfer-encoding: "chunked" response header by design

So, one workaround is to add Content-Length to response header to prevent Transfer-Encoding: chunked

I customized a middleware like this:
```
public class CustomMiddleware
{
    private readonly RequestDelegate _next;

    public CustomMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext context)
    {
        var originalBody = context.Response.Body;
        using (var ms = new MemoryStream()) 
        {
            context.Response.Body = ms;
            long length = 0;
            context.Response.OnStarting((state) =>
            {
                context.Response.Headers.ContentLength = length;
                return Task.FromResult(0);
            }, context);
            await _next(context);
            length = context.Response.Body.Length;
            context.Response.Body.Position = 0;
            await ms.CopyToAsync(originalBody);
        }
    }
}
```

Middleware order:

```
app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.UseMiddleware<CustomMiddleware>();

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");
});
```

Unfortunately, it still doesn't work. I tried to access `/User/Index` while it would redrict to the login page due to the `Authorize` attribute on `UserController`. After login, I accessed the page again, it shows this

![image](https://user-images.githubusercontent.com/49815294/69635221-e5801b80-108e-11ea-802e-fdee0e02654e.png)

the docker logs as follows

![image](https://user-images.githubusercontent.com/49815294/69635151-bcf82180-108e-11ea-8744-ebaece27d6d9.png)

At last, I create MemoryStream directly instead of using `using`.  

```
public async Task Invoke(HttpContext context)
{
    var originalBody = context.Response.Body;
    var ms = new MemoryStream();
    context.Response.Body = ms;
    long length = 0;
    context.Response.OnStarting((state) =>
    {
        context.Response.Headers.ContentLength = length;
        return Task.FromResult(0);
    }, context);
    await _next(context);
    length = context.Response.Body.Length;
    context.Response.Body.Position = 0;
    await ms.CopyToAsync(originalBody);
}

```

Amazing, everything is OK, what happeded? Is there a better solution?

**Comment by Tratcher** [comment]
Your original incomplete chunked encoding error implies there was an exception after the response started and the response had to be aborted by closing the connection. Check the app logs for that original scenario.

Buffering the response adds memory and latency overhead and should be avoided.

**Comment by Superllb93** [comment]
it's my fault, thanks
