### ISSUE TITLE
Hosting bundle IIS reset / application pool recycle question

### ISSUE THREAD

**Issue by WalterEbbers** [aspnet/AspNetCore#17416]
Hi,
I'm currently working on expanding a setup application that downloads applications and puts them in a IIS folder. Some of the applications are asp. net core which require the hosting bundle to be installed. The setup module will install the bundle if it not found on the found on the target machine(which runs the setup application). When i was testing the bundle installer i saw in the eventlog all the application pools where recycled. 

- Why is this recycle started? 
    - Is this due to a IIS reset?  

The only thing i could think of was for the environment path that is added for the dotnet.exe location but we install everything in the default folders(C:\Program Files\dotnet).  

The web.configs for our asp.net core application all have a full path to the dotnet exe path. 

- Is the recycle necessary? 
    - Is there a way to turn this recycle off if it not necessary?

I'm asking this because the customers where the applications are being installed can also have other application running on IIS and we don't want to disturb there process. 

Kind regards,

Walter

**Comment by jkotalik** [comment]
> Why is this recycle started?

I don't think we explicitly restart IIS/WAS via the hosting bundle. From what I thought, we update the applicationhost.config file, which could trigger restarts based on the application itself. 

> The web.configs for our asp.net core application all have a full path to the dotnet exe path.

Can you elaborate more on this?

In general, we don't recommend installing the hosting bundle while sites are running at the same time. Maybe do red green deployment or something like that instead to installing the bundle while the app isn't running.

**Comment by WalterEbbers** [comment]
> > Why is this recycle started?
> 
> I don't think we explicitly restart IIS/WAS via the hosting bundle. From what I thought, we update the applicationhost.config file, which could trigger restarts based on the application itself.
> 
> > The web.configs for our asp.net core application all have a full path to the dotnet exe path.
> 
> Can you elaborate more on this?
> 
> In general, we don't recommend installing the hosting bundle while sites are running at the same time. Maybe do red green deployment or something like that instead to installing the bundle while the app isn't running.

Thnx for the response!

What i meant by the config was the following tag:
` <aspNetCore processPath="C:\Program Files\dotnet\dotnet.exe" arguments=".\API.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" shutdownTimeLimit="1" />`

But if the change to the applicationhost.config is necessary, we can give our customers who run the software the chance to perform the install at a moment when its suitable for them, but it would helpfull to us to know that this happens for certain.

**Comment by anurse** [comment]
The hosting bundle installs an IIS module (ANCM) so IIS *has* to restart in order to load it. This is the expected behavior at this time.

**Comment by WalterEbbers** [comment]
> ANCM

Thank you for the clarification!
