### ISSUE TITLE
Blazor WebAssembly apps throw on start with latest Mono

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#17419]
The latest builds of Mono are now stricter about the args passed to `mono_call_assembly_entry_point`. Up until now, we're calling it like this:

```ts
  callEntryPoint: function callEntryPoint(assemblyName: string): System_Object {
    return mono_call_assembly_entry_point(assemblyName, []);
  },
```

That is, we're passing an empty array, indicating that there are no args to pass. However, the actual startup method in typical apps (and the template) looks like this:

```cs
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }
```

... i.e., it takes one argument - a `string[]`. It used to be lenient and call the method anyway, but now it throws saying there is an argument count mismatch.

To fix this, we need to pass the correct number of args, even if they are null, e.g.:

```ts
  callEntryPoint: function callEntryPoint(assemblyName: string): System_Object {
    return mono_call_assembly_entry_point(assemblyName, [null]);
  },
```

This is still a bit weird because the application will now receive `null` for `args`, rather than an empty array. It would be better still to build an actual managed array. You can see an example of building a managed array in `MonoPlatform.ts`'s `callMethod`. However that allocates it on the stack, which is safe only because we're passing it to `invoke_method` which never exposes it to user code. Since we're passing an array instance that is exposed to user code, it really needs to be on the heap. I'm sure this can be done too but I don't know of a specific example.

**Update**: On further thoughts, maybe it's OK if it was allocated on the stack, since the thing we're calling here is literally the application entrypoint, so this part of the stack will never be exited during the application's lifetime. Doing it on the heap would still be more normal for .NET though, and maybe there are more subtle reasons why it has to be there.

I recommend for now we just pass `null`, since there's no useful way to pass in actual args anyway. As a future enhancement we could have some way of passing real args.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/aspnet/AspNetCore/commit/0dbc5731daecd3041a38da81ff3efb300dbb7f00
