### ISSUE TITLE
Can't issue HTTP requests during app startup on iOS 13

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#17424]
***Triage proposal**: I think we should do this in the preview 5 milestone. We don't need to rush this in for preview 4.*

Now we've got the non-recursive interpreter change, this is the last remaining known incompatibility for Catalina/iOS 13.

If you start up a Blazor WebAssembly app on iOS 13 and it doesn't do any `HttpClient` calls during the first initialization and rendering cycle, all is OK. But if you do try to use `HttpClient` on the first cycle, it dies.

We've known about this for a while and @kjpou1 provided a suggested fix in https://github.com/aspnet/AspNetCore/pull/14605. We now need to merge that fix, though we have to figure out how to do so without negatively impacting Blazor Server, since it doesn't need this change. Possibly a more cut-down change would also be sufficient on Blazor WebAssembly.

@rynowak If you get a few minutes, I'd appreciate any feedback or insight you might have on whether any less-impactful version of https://github.com/aspnet/AspNetCore/pull/14605 might be possible. I know you have more familiarity with the lower-level async primitives and our sync context, and what's safe to change about it. It might be fine to take the change exactly as-is, since `ProcessAsynchronousWork` only executes on the first run, so we're not actually adding the overhead of `Task.Factory.StartNew` on every render. Maybe we could even reduce the `Task.Factory.StartNew` to an `await Task.Yield();` call prior to its contents.

**Comment by kjpou1** [comment]
There may need to be change on the mono side to incorporate this into the WebAssembly HttpMessageHandler.

```
            // There is a race condition on Safari as a result of using TaskCompletionSource that
            // causes a stack exceeded error being thrown.  More information can be found here:
            // https://devblogs.microsoft.com/premier-developer/the-danger-of-taskcompletionsourcet-class/
            var tcs = new TaskCompletionSource<HttpResponseMessage>(TaskCreationOptions.RunContinuationsAsynchronously);
```

Please let me know if that is the case.

**Comment by SteveSandersonMS** [comment]
@kjpou1 That may be worth trying to see if it improves anything, but it looks like there is still a separate problem independently of that. I've posted more details at https://github.com/mono/mono/issues/17938

**Comment by SteveSandersonMS** [comment]
This is now fixed with https://github.com/aspnet/Blazor/pull/1954 (which includes the underlying fix in Mono, https://github.com/mono/mono/pull/17953).
