### ISSUE TITLE
Tolerate unexpanded wildcards in items in Razor language service

### ISSUE THREAD

**Issue by rainersigwald** [aspnet/AspNetCore#17423]
This was reported as https://developercommunity.visualstudio.com/content/problem/564524/vs-2019-netcore-project-path-too-long-exception-re.html

### Describe the bug

microsoft/msbuild#406 means that some wildcard patterns can fail to expand and then be represented as literal `*` in items. Ideally that would be fixed at the MSBuild level, but a) [fully supporting long paths in Visual Studio is under consideration but very difficult](https://developercommunity.visualstudio.com/idea/351628/allow-building-running-and-debugging-a-net-applica.html) and b) the "fix" might be failure to load the project when wildcards fail to expand, which might be worse than the current behavior.

In addition, it would be legal at the MSBuild level for a user to put escaped wildcards into an item include (items aren't _necessarily_ files).

If an item with `**` in it is loaded in the Razor language service, it throws

```
===================
11/26/2019 9:52:04 AM
Recoverable
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectFileSystem.GetItem(String path, String fileKind)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.ProjectState.GetImportDocumentTargetPaths(HostDocument hostDocument)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.ProjectState.WithAddedHostDocument(HostDocument hostDocument, Func`1 loader)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.DocumentAdded(HostProject hostProject, HostDocument document, TextLoader textLoader)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.RazorProjectHostBase.AddDocumentUnsafe(HostDocument document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultRazorProjectHost.<>c__DisplayClass7_1.<OnProjectChanged>b__2()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.RazorProjectHostBase.<UpdateAsync>d__17.MoveNext()
```

### To Reproduce

Create a very-deeply-nested folder structure with a file or two in it under an ASP.NET project that _is not_ excluded (so not just `$(SPARoot)node_modules`). Open the project in VS.

Note: this should not happen if the files with long paths are excluded, so the default `dotnet new angular` experience with its nested `node_modules` should not experience this.

### Further technical details
VS 16.3.10 with .NET Core SDK 3.0.100.

**Comment by mkArtakMSFT** [comment]
Thanks @rainersigwald.
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
@rainersigwald how does anything work in Visual Studio when file paths get too long? I imagine C# or C++ etc. wouldn't understand ** as part of file paths and also end up exploding.

I understand how this issue is on the MSBuild backlog but doing this work on our end would be quite large and potentially throw away given the amount of places we read/look at file paths.

**Comment by rainersigwald** [comment]
Things generally fall apart if important project files exceed MAX_PATH. In the case in the original bug, the files in question generally weren't important to design-time scenarios, so failing to load the project because they were globbed in was a bigger problem: if the failed-glob files just failed to expand, the project would be mostly usable, but instead it just blew up.

The ideal thing here would be to manifest `devenv.exe` as supporting long paths--that's what we did for `MSBuild.exe`. That's tracked by a feedback item I linked but is a fairly scary change since it affects all VS extensions and workloads _and_ it requires a Windows-level opt-in. If Razor uses any external helper processes that are running on full .NET Framework (.NET Core already does reasonable things) it might be worth considering manifesting them.

Since NPM no longer creates super-deeply-nested folders by default (they moved to flattening the dependency tree years ago) I wouldn't object to won't fixing this or duplicating this against https://developercommunity.visualstudio.com/idea/351628/allow-building-running-and-debugging-a-net-applica.html.

**Comment by NTaylorMullen** [comment]
> Since NPM no longer creates super-deeply-nested folders by default (they moved to flattening the dependency tree years ago) I wouldn't object to won't fixing this or duplicating this against https://developercommunity.visualstudio.com/idea/351628/allow-building-running-and-debugging-a-net-applica.html.

Love it!

------------

Closing as external: https://developercommunity.visualstudio.com/idea/351628/allow-building-running-and-debugging-a-net-applica.html
