### ISSUE TITLE
Provide a posibility to change the URL 

### ISSUE THREAD

**Issue by tschissler** [aspnet/AspNetCore#17421]
This is pretty much the same as requested here: #10894

I have a page with some sub navigations. Let's imagine it is a page with 5 products and for each product you can click a button to show the details. Each product can be opened with an optional URL parameter.

www.myproducts.com/        -> This will open the overview page
www.myproducts.com/2      -> This will open the page with details of product 2 opened.

If one opens the overview page and then navigates to a product and now want's to share this with someone else, they might just copy & paste the URL into an eMail. It would be niche if after clicking the button for product 2 the URL could be updated to www.myproducts.com/2.

//Thomas//

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
 It's unclear what is the actual question here. Can you share more details about your scenario and potentially share even a small repro project (ideally hosted as a GitHub repo)?

**Comment by tschissler** [comment]
Sure thing.
I have created the demo here:
https://github.com/tschissler/BlazorURLDemo

If you open the base URL and then click on Product 2. You see this:
![image](https://user-images.githubusercontent.com/11467601/69804815-a8776e80-11df-11ea-927d-23d5e2a6002e.png)
If you now want to bookmark or send the details about product 2, you will just use the base URL so when returning, you will see no product information.
Expected behavior: URL changes to https://localhost:44307/2

If you open product details for a specific product for example https://localhost:44307/3, you will see the correct product. But if you change to a different product using the buttons, then you still have the original URL. If you bookmark or share this, it will point to a different product than you actually see.
Expected behavior: URL changes to new product.

So it would be great if I could manipulate the current URL for example in the click event of a button to make sure it reflects the correct parameters.

Does that help? Let me know, if you need more details.

**Comment by javiercn** [comment]
@tschissler thanks for contacting us.

We would recommend you use routes for each individual product. That way they can be bookmarked. There's no difference between a button and a link, so you can use links on your elements to point to the right route.

Here are some docs that might help clarify the approach https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.0
