### ISSUE TITLE
namespace Microsoft.AspNetCore.Routing / public class RouteOptions / LowercaseUrls() method / Summary text

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17445]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/733436/namespace-microsoftaspnetcorerouting-public-class-4.html)._

---
The Summary text for **namespace Microsoft.AspNetCore.Routing / public class RouteOptions / LowercaseUrls()** method reads as follows:

//     Gets or sets a value indicating whether all generated paths URLs are lower-case.
        //     Use Microsoft.AspNetCore.Routing.RouteOptions.LowercaseQueryStrings to configure
        //     the behavior for query strings.
        public bool LowercaseUrls { get; set; }

"lower-case" needs to be replaced with "lowercase" (it's best to do a global search-and-replace of "lower-case" because I found at least one other occurrence of that text).

---
#### Visual Studio Feedback System on 9/16/2019, 01:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/24/2019, 02:12 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

We would accept a PR for this anyone is willing to make one.

**Comment by Marusyk** [comment]
Please assign it to me. I'll prepare PR
