### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Filters.FilterCollection.Add() method descriptions

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17446]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/742119/microsoftaspnetcoremvcfiltersfiltercollectionadd-m.html)._

---
The **Microsoft.AspNetCore.Mvc.Filters.FilterCollection.Add()** method descriptions for overloads 2-5 are incorrect; they currently read as follows:

`Adds a type representing an Microsoft.AspNetCore.Mvc.Filters.IFilterMetadata`

In overloads 2-5 of that method, "an" needs to be replaced with "a"; the corrected description reads as follows:

`Adds a type representing a Microsoft.AspNetCore.Mvc.Filters.IFilterMetadata`

Overloads 2 and 3 have an extra occurrence of "an" that needs to be replaced with "a".

---
#### Visual Studio Feedback System on 9/23/2019, 00:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/23/2019, 10:56 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

We would accept a PR for this anyone is willing to make one.

**Comment by ravikank** [comment]
I am willing to work on this one.

**Comment by uzairashraf** [comment]
What is PR? I want to contribute, I am a C# developer.

**Comment by javiercn** [comment]
Pull Request

**Comment by adrianwright109** [comment]
PR #17505 submitted.
