### ISSUE TITLE
Multipart body length limit 16384 exceeded

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17441]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/760834/multipart-body-length-limit-16384-exceeded.html)._

---
[regression] [worked-in:16.2.2]
After updating visual studio version 16.3.2. when  using Request.Form  to get formdata from client side to API, I am getting error as 'Multipart body length limit 16384 exceeded.'  Earlier it was working fine with Visual studio version 16.2.2. but after updating it fails on new version i.e. on 16.3.2.   
I am calling web api using http post along with FormData and binding in webApi httppost method as code given below and getting error on the given line below
var data= Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());

I am using angular 5.0 version as client side and Web API .net core. 2.2 on server side.

I have also used the  
services. Configure<FormOptions>(x => x.ValueCountLimit = 50000);
in startup file.

---
#### Visual Studio Feedback System on 10/6/2019, 09:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/10/2019, 11:00 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Could you share a minimal app that reproduces the problem?

**Comment by Tratcher** [comment]
I'd expect this kind of error if there was a problem with the multipart format or boundary. A Fiddler trace of the repro would help.
