### ISSUE TITLE
Microsoft.AspNetCore.Localization.RequestCulture() method descriptions

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17447]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/742118/microsoftaspnetcorelocalizationrequestculture-meth.html)._

---
Microsoft.AspNetCore.Localization  RequestCulture() method descriptions

The description for each overload of the Microsoft.AspNetCore.Localization.RequestCulture() method is not grammatically correct:

```
RequestCulture(CultureInfo) 
Creates a new RequestCulture object has its Culture and UICulture properties set to the same CultureInfo value.

RequestCulture(String) 
Creates a new RequestCulture object has its Culture and UICulture properties set to the same CultureInfo value.

RequestCulture(CultureInfo, CultureInfo) 
Creates a new RequestCulture object has its Culture and UICulture properties set to the respective CultureInfo values provided.

RequestCulture(String, String) 
Creates a new RequestCulture object has its Culture and UICulture properties set to the respective CultureInfo values provided.
```
I believe that replacing "object" in each description with "object;" is what you're trying to convey; here is how that would look:
```
RequestCulture(CultureInfo) 
Creates a new RequestCulture object; has its Culture and UICulture properties set to the same CultureInfo value.

RequestCulture(String) 
Creates a new RequestCulture object; has its Culture and UICulture properties set to the same CultureInfo value.

RequestCulture(CultureInfo, CultureInfo) 
Creates a new RequestCulture object; has its Culture and UICulture properties set to the respective CultureInfo values provided.

RequestCulture(String, String) 
Creates a new RequestCulture object; has its Culture and UICulture properties set to the respective CultureInfo values provided.
```
Alternatively, you could replace "has" in each description with "with"; here is how that would look:
```
RequestCulture(CultureInfo) 
Creates a new RequestCulture object with its Culture and UICulture properties set to the same CultureInfo value.

RequestCulture(String) 
Creates a new RequestCulture object with its Culture and UICulture properties set to the same CultureInfo value.

RequestCulture(CultureInfo, CultureInfo) 
Creates a new RequestCulture object with its Culture and UICulture properties set to the respective CultureInfo values provided.

RequestCulture(String, String) 
Creates a new RequestCulture object with its Culture and UICulture properties set to the respective CultureInfo values provided.
```

---
#### Visual Studio Feedback System on 9/23/2019, 01:21 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/23/2019, 10:55 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@ryanbrandenburg can you please go through the comments and fix those, if needed? Thanks!
