### ISSUE TITLE
Add new parameter to StatusCode() extension method to set status code description

### ISSUE THREAD

**Issue by bgillet** [aspnet/AspNetCore#17450]
In some case, HTTP status code are a bit too generic.
So we add sometimes a custome code (ex: ALREADY_RECEIVED) in the HTTP status code's description to give more details about the reason of the returned status code.
It is possible to set the status code description in .NET but not in .NET Core.

We would like to be able to set the status code description as a string when calling the `StatusCode()` extension method.

For example : `StatusCode(211, "ALREADY_RECEIVED", value)`

**Comment by javiercn** [comment]
@bgillet thanks for contacting us.

The status code description is deprecated in HTTP/2 and is not something we recommend changing. Based on that, we are unlikely to make a change like this.
