### ISSUE TITLE
Incorrect operation of components contained in a list

### ISSUE THREAD

**Issue by rperazzolli** [aspnet/AspNetCore#17465]
I'm keeping a list of floating components on a page contained in a list of components.
When I want to remove one of them, if I remove it from the list and invoke StateHasChanged, it always removes the last component from the page, regardless of which one I have effectively deleted.
The only way it works as expected is to put the remaining components in a backup list, remove all components from the list, invoke StateHasChanged (all components are deleted from page), and then, in OnAfterRenderAsync, copy the components from the backup list and invoke StateHasChanged again.

The code to add the components in razor is:

        foreach (TableroBlazor.Componentes.CLinkFiltros Link in ComponenteFiltros.Links)
        {
          if (Link.PosicionEnPantalla >= 0)
          {
          <div id="@IdFiltro(Link.PosicionUnica)" class="ui-widget-content"
               style="@EstiloFiltro(Link)">
            <TableroBlazor.Componentes.FiltroTextos @ref="@Link.Componente"
                                                          Ancho="@Link.Ancho" Alto="@AltoFiltro"
                                                          CodigoUnico="@Link.PosicionUnica" />
          </div>
          }
        }

I use VS Community 2019 V 16.3.9.

**Comment by javiercn** [comment]
@rperazzolli thanks for contacting us.

You should use the key attribute:
https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#use-key-to-control-the-preservation-of-elements-and-components

**Comment by rperazzolli** [comment]
Thank you very much.

________________________________
De: Javier Calvarro Nelson <notifications@github.com>
Enviado: viernes, 29 de noviembre de 2019 15:23
Para: aspnet/AspNetCore <AspNetCore@noreply.github.com>
Cc: rperazzolli <rperazzolli@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [aspnet/AspNetCore] Incorrect operation of components contained in a list (#17465)


Closed #17465<https://github.com/aspnet/AspNetCore/issues/17465>.
