### ISSUE TITLE
ConsoleLifetime being executed after HostedService

### ISSUE THREAD

**Issue by barahonajm** [aspnet/AspNetCore#17483]
### Describe the bug
Hi, 

Not sure if I am using the generic host correctly but doing some playing with it I found when using RunConsoleAsync() is the HostedService whose methods are executed first, so I was wondering shouldn't  ConsoleLifetime be executed first?

That way I am able to end application before any work on HostedServices happens

### To Reproduce
Program.cs
``` C#
static async Task Main(string[] args)
{
    await Host
        .CreateDefaultBuilder()
        .ConfigureServices((hostContext, services) => {
            services.AddHostedService<ConsoleApplication>();
        })
        .RunConsoleAsync();
}
```
ConsoleApplication.cs

``` C#
public class ConsoleApplication : IHostedService
{
    private readonly ILogger<ConsoleApplication> logger;

    public ConsoleApplication(ILogger<ConsoleApplication> logger)
    {
        this.logger = logger;
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        logger.LogInformation("Starting application");

        Task.Run(() => {
            bool quit = false;
            while (!quit) {
                Console.WriteLine("Enter your action: ");
                string action = Console.ReadLine();
                quit = action == "quit";
            }

        });

        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        logger.LogInformation("Ending the application");

        return Task.CompletedTask;
    }
}
```

![image](https://user-images.githubusercontent.com/15148088/69820048-980ec600-11d6-11ea-9f17-640f64ad83db.png)

### Further technical details
- .NET Core  3.1.0-preview3
- Microsoft.Extension.Hosting  3.1.0-preview3.19553.2
- VS Code

**Comment by Tratcher** [comment]
I don't quite follow. That Task.Run makes the order indeterminate. The main conflict here seems to be trying to use both the console logger and console input at the same time. You'd be better off disabling the console logger and using some other kind of logging if you want to write an interactive console application.

**Comment by barahonajm** [comment]
Thanks for the answer, yeah I am probably not using generic host in the correct way to make a interactive console a doc on this could be great! but my main concern is about the order of logs which could not be a big deal.

For example here:
https://github.com/aspnet/Extensions/blob/master/src/Hosting/samples/GenericHostSample/ProgramHelloWorld.cs

There is two hosted services and the host is executing with `RunConsoleAsync ` but when checking logs we can see the following:
![image](https://user-images.githubusercontent.com/15148088/70163743-5b3f4500-1696-11ea-86c4-ec6fd35b8d4b.png)

Logs from services are at the beginning while the RunConsoleAsync logs are after that, I was expecting the `RunConsoleAsync` to execute at the beginning at all but I could wrong, could you please confirm me this?

**Comment by Tratcher** [comment]
RunConsoleAsync is effectively just an alias for Host.RunAsync(). That starts all of the services and then the ConsoleLifetime logs that everything has successfully started. This is the expected behavior.

I could see re-ordering these lines so that the CTL+C log was last.
https://github.com/aspnet/Extensions/blob/cda774390962745f07baa11069f46aec489f4c61/src/Hosting/Hosting/src/Internal/ConsoleLifetime.cs#L69-L71

**Comment by barahonajm** [comment]
Got it, so ConsoleLifetime makes sure all services are started correctly and only then logs that success. Now it make sense for me thank you!!
