### ISSUE TITLE
How to Razor engine phase compilation hook

### ISSUE THREAD

**Issue by KLuuKer** [aspnet/AspNetCore#17482]
### Is your feature request related to a problem? Please describe.
I want to write a custom html minifier that runs during the cshtml view **compilation** phase.
So **NOT at runtime**, i could write a middleware for that instead.
But why pay for all those extra bytes that i need to strip off again while they shouldn't be there in the first place....

### Describe the solution you'd like
I have tried using the `IRazorEnginePhase` but i have no idea on how to actually get it to work.
And i believe that should give me enough access to the raw html to trim off any excess html i don't want.

mvc core 2.2.x if possible, or just tell it for 3.x and i will just have even more reasons to upgrade 😄

**Comment by javiercn** [comment]
@KLuuKer thanks for contacting us.

@NTaylorMullen Is this possible? Can you provide any pointers?

**Comment by NTaylorMullen** [comment]
Not officially supported to extend our Razor parsing at build time sorry 😢.

**Comment by KLuuKer** [comment]
What about unsupported then?..... if possible with 3.x because that would work the longest

i don't mind hooking up a bunch of stuff during build, i'm replacing a bunch of routing and container stuff anyway 😄 

or having some weird build step that i can run during our CI step

**Comment by NTaylorMullen** [comment]
> What about unsupported then?

If you're up to do some reverse engineering i'd recommend downloading MSBuild structured log viewer and then start checking out how [our MSBuild configurations](https://github.com/aspnet/AspNetCore-Tooling/blob/c3e80e0b46b06c1c7cf35800556213eb3c9636b8/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Configuration.targets#L68-L93) influence Razor parsing during `dotnet build /bl`. We use those properties/itemgroups to configure how we parse Razor files for different versions of Razor (i.e. 1.0, 2.1, 3.0 etc.).
