### ISSUE TITLE
Blazor: Blazor Hub Does not Connect Across Entire MVC App

### ISSUE THREAD

**Issue by kacey90** [aspnet/AspNetCore#17489]
I upgraded a 2.2 netcore mvc project to 3.0 in order to use a blazor component in one of the views of the application. After setting up blazor on the MVC project and running it, the blazor hub connects just fine as shown in the browser console screenshot below;

![image](https://user-images.githubusercontent.com/26015234/69865225-eab4b480-12a0-11ea-91f8-e7d0299603dc.png)

but when I navigate to the page that contains the blazor component or another page besides the index page for that matter, I get this;

![image](https://user-images.githubusercontent.com/26015234/69865323-2b143280-12a1-11ea-9e65-1a6accfe13cb.png)

As shown in the screenshot, it includes the name of the controller the url that negotiates for a websocket connection and throws a 404. If this is not a bug, how can I fix this to work on every view of the application?

**Comment by javiercn** [comment]
@kacey90 thanks for contacting us.

You need to set the app base path in your HTML so that the app works correctly. See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/?view=aspnetcore-3.0&tabs=visual-studio#app-base-path for details.
