### ISSUE TITLE
When I Deploy the asp.net core 3.0 App to windows server 2012 R2，the all of IIS website are stopped？

### ISSUE THREAD

**Issue by Pilchie** [aspnet/AspNetCore#17498]
_From @jesen20160925 on Monday, November 25, 2019 9:58:53 AM_

as the title says，anybody can help me ? thanks!

_Copied from original issue: dotnet/core#3904_

**Comment by Pilchie** [comment]
_From @Pilchie on Monday, November 25, 2019 9:33:38 PM_

How are you doing the deployment?

**Comment by Pilchie** [comment]
_From @jesen20160925 on Tuesday, November 26, 2019 1:24:52 AM_

I installed dotnet-hosting-3.0.1-win.exe on Windows Server 2012 R2, and publish the website on IIS, and set the application pool without managed code.  and then the .net core website can run,but all of the asp.net website are can not be running,when I start them and access , they are stopped.

**Comment by Pilchie** [comment]
_From @Pilchie on Tuesday, November 26, 2019 1:27:17 AM_

@anurse @jkotalik @joeloff ideas on where this should be?

**Comment by Pilchie** [comment]
_From @joeloff on Tuesday, November 26, 2019 5:50:46 PM_

This sounds like an IIS/ANCM issue to me, but it's possible it could just be a configuration issue causing the app pools to maybe become disabled. I'm not an IIS expert, so I'd defer to @jkotalik to ask the right questions.

**Comment by Pilchie** [comment]
_From @jesen20160925 on Wednesday, November 27, 2019 12:27:38 AM_

OK,Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jacques Eloff"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 凌晨1:50
收件人:&nbsp;"dotnet/core"<core@noreply.github.com&gt;;
抄送:&nbsp;"jesen"<237745378@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnet/core] When I Deploy the asp.net core 3.0 App to windows server 2012 R2，the all of IIS website are stopped？ (#3904)




This sounds like an IIS/ANCM issue to me, but it's possible it could just be a configuration issue causing the app pools to maybe become disabled. I'm not an IIS expert, so I'd defer to @jkotalik to ask the right questions.

**Comment by Pilchie** [comment]
_From @jesen20160925 on Thursday, November 28, 2019 10:00:19 AM_

I uninstalled dotnet-hosting-3.0.1-win.exe and installed the dotnet-hosting-3.0.0-win.exe on my server,it runs well,does the 3.0.1 version not support the windows server 2012 R2?

**Comment by joeloff** [comment]
There are some additional requirements listed for .NET Core: https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore30&pivots=os-windows

But those apply to any runtime/SDK installation on 2012R2. I'm not aware of anything that's changed recently or any additional requirements

**Comment by anurse** [comment]
> and set the application pool without managed code

Are you using a single application pool for both ASP.NET 4.x and ASP.NET Core apps? If you've disabled managed code, ASP.NET 4.x apps won't work.
