### ISSUE TITLE
Blazor NavigationManager.NagivateTo throwing totally useless error message.

### ISSUE THREAD

**Issue by NetTecture** [aspnet/AspNetCore#17497]
3.0.

The following code in a component:

    protected override void OnInitialized ()
    {
        NavigationManager.NavigateTo("/login", forceLoad: true);
    }

results in:

  | Name | Value | Type
-- | -- | -- | --
▶ | $exception | {"Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown."} | Microsoft.AspNetCore.Components.NavigationException

There is no inner exception, no debug information at all. It makes simply no sense because 

  | Name | Value | Type
-- | -- | -- | --
  | Location | "https://localhost:44342/login" | string

actually IS valid. I can go to this location and get a login mask.

THe error message is exactly one thing: not helpfull at all. It does not provide any context information which is bad given that in the browser AFTER this error message - I get the /login window nicely displaying the login form.

**Comment by javiercn** [comment]
@NetTecture thanks for contacting us.

Are you seeing this during pre-rendering? 

If that's the case, this is a first chance exception that is thrown to cause a redirect to happen during pre-rendering and that is caught by MVC. If you turn off first-chance exceptions you won't see this happen.

If this is not the case, let us know and we will re-evaluate.
