### ISSUE TITLE
Auth Policy Provider Problem - Multiple Providers

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#17493]
### Is your feature request related to a problem? Please describe.
In my application I use several libraries.
They each ship custom `IAuthorizationPolicyProvider` implementations that must be registered on startup.
ASP.NET Core only uses a single `IAuthorizationPolicyProvider`.
I'd like to use them all - in a composite manner - conceptually the same as how a `CompositeFileProvider` works - i.e each file provider in the composite is checked in order for a file - well I'd like each `IAuthorizationPolicyProvider` to be checked in order to resolve a policy.

The trouble is, if each library authors follow the given example of the custom `IAuthorizationPolicyProvider` - they have to explicitly create the "backup" policy provider in their constructor: https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Security/samples/CustomPolicyProvider/Authorization/MinimumAgePolicyProvider.cs#L25

This won't work for me because the libraries that I use that supply custom `IAuthorizationPolicyProvider's` are not aware of each other. They have no way to know ahead of time what concrete provider they should construct in order to form the chain required. If they both just  create the default provider as the backup (as shown in the example) then it means my application can only use one auth policy provider from one library or the other, and not chain them both together. 

In my application, I need someway of wiring these different providers up to form a composite.
What would be the recommended way to achieve this? Can the example be updated to demonstrate this?

### Describe the solution you'd like
I'm thinking something conceptually similar to `FileProviders` i.e something like: 
`CompositeAuthorizationPolicyProvider` provided out of the box, so I could do something like:

```csharp
          
   services.AddCompositeAuthorizationPolicyProvider((builder)=>{
       builder.Add<FooAuthProvider>();
       builder.Add<BarAuthProvider>();
       builder.Add<DefaultAuthorizationPolicyProvider>();
   });

```
The composite would, I guess, loop through the inner providers to obtain the policy and if a NULL policy was returned, then it would continue to the next inner provider, until eventually either returning a policy, or returning NULL.

One other benefit of this approach is that you can optionally enable caching of policies for particular providers, by wrapping it in a CachingProvider - as explained here: https://github.com/dazinator/Dazinator.AspNetCore.Authorization/issues/1

**Comment by dazinator** [comment]
I've created my suggested solution here with tests: https://github.com/dazinator/Dazinator.AspNetCore.Authorization

I'd appreciate if you would consider implementing this pattern as part of the framework to make it easier to achieve without having to pull in third party libraries - like mine!

**Comment by blowdart** [comment]
Frankly we've not considered the idea of multiple providers, it's rather odd to my mind. A provider for policy is the last fallback for someone who can't get what they want out of what we implemented. Are these your libraries? What are they doing that they need to override everything?

**Comment by dazinator** [comment]
@blowdart 
So, just a recap from [the docs](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.0):

> Typically when using policy-based authorization, policies are registered by calling AuthorizationOptions.AddPolicy as part of authorization service configuration. In some scenarios, it may not be possible (or desirable) to register all authorization policies in this way. In those cases, you can use a custom IAuthorizationPolicyProvider to control how authorization policies are supplied.

In my case I have a library that allows you to add user permission based authorisation to your app. To repeat the docs, it wasnt desirable to register individually every possible permission combination as it's own policy ahead of time. Therefore my library provides an IAuthorizationPolicyProvider implementation that looks at the policy name, and from that works out which permissions it needs to check for  and builds the appropriate policy dynamically.

This is one library that allows you to integrate policies into your app based on user permissions. All you have to do to realise this problem is accept that may be more than one library wanting to do the same. It talks about examples of such cases in the docs above - Therefore it's quite possible to end up with multiple providers - and it seems thats by design. 

In my specific case, I hit this when I created a second library that allows you to dynamically create hierarchical menu's in your app - basically menu items that can have parent menu item, and child menu items. However it also let's you associate each menu item with an authorisation policy name. When displaying a menu to a user, only the menu items whose "View" authorization policies succeed, will be presented to the user. This works fine and no need for any custom authorization policy provider so far..  however then I discovered that at certain places in my app, I only want to authorize something if the user is at least authorized for one menu item in a given menu. For example if I have created a menu with 10 menu items, and user A has access to view 5 of those menu items on that menu, then I want to Authorize them access to the entire page where that menu is presented. For user B who isnt authorised for any items on that dynamic menu, I also want to prevent them from accessing the page as they aren't authorised for any of it's related content. So enter a custom AuthorizationPolicyProvider that can integrate my menu system. It will dynamically build and return a policy that succeeds if the user had atleast authorisation for one menu item in a menu with a given name.

**Comment by blowdart** [comment]
I'm honestly not sure that was the intention. Multiple sources could run in any order. What happens if multiple sources want to handle the same policy name? You can't know which one will resolve it.

**Comment by blowdart** [comment]
@HaoK do you have any advice here? Am I way off base?

**Comment by dazinator** [comment]
> Multiple sources could run in any order. What happens if multiple sources want to handle the same policy name? You can't know which one will resolve it

1. Why is it important to know which provider sourced the policy?
2. Conflicts can be avoided by making sure each provider has a unique policy name prefix. The author of a provider could make this prefix a sensible default but it could also be configurable so that no application need have conflicts.
3. You can say exactly the same about CompositeFileProvider, where two different IFileProviders might both resolve the same file path from different sources. Providers have an order if precedence in the composite which the developer is aware of when building the composite.

**Comment by anurse** [comment]
Triage: This isn't something we're interested in adding at this time. You can use a custom policy provider to achieve whatever composition model you want in your scenario.
