### ISSUE TITLE
Blazor Obfuscation

### ISSUE THREAD

**Issue by GerritBergen** [aspnet/AspNetCore#17494]
### Describe the bug
I read that obfuscation is technically possible, because the blazor files are just .dll files. So I built a project, and obfuscated the `Client/dist/_framework/_bin/client.dll` file, but running it just crashes:

> WASM: ﻿System.AggregateException: One or more errors occurred. (Method not found: int System.BitConverter.ToInt32(byte[],int)) ---> System.MissingMethodException: Method not found: int System.BitConverter.ToInt32(byte[],int) blazor_web.js:2046:68

And:

> WASM: Unknown heap type: #YoCUQ blazor_web.js:2046:68

Any ideas?

**Comment by javiercn** [comment]
@GerritBergen thanks for contacting us.

We believe you'll get a better response in the mono repository as this is not blazor specific. 

I'm not sure why you are trying to obfuscate the assembly but in my personal experience that's not something that helps or provides any security whatsoever, if anything, it provides a false sense of security, so I would stay away from it.

**Comment by GerritBergen** [comment]
@javiercn It's not for security purposes, because I'm well aware that if an attacker wants to see the code, he'll see it. It's more about deterring the average joe.
