### ISSUE TITLE
The view 'Login' was not found

### ISSUE THREAD

**Issue by malballah** [aspnet/AspNetCore#17490]
I have just migrated my app from asp.net core 2.2 into 3.0 and published to azure, when I publish the project with compile razor views it gives me the error, it cannot find the file xxx.views.dll although the file is there, and if I published without compile razor views it gives me this error
"The view 'Login' was not found" although the file is there under the corresponding folder.
The project running very well locally but it run this error at azure
here is my project file
`<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <RazorCompileOnBuild>false</RazorCompileOnBuild>    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <UserSecretsId>1feaff78-ac4f-45ea-8f71-fbc880a86303</UserSecretsId>
    <TypeScriptToolsVersion>3.0</TypeScriptToolsVersion>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>`

I tried this configuration also and it gives the same errors
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
<UserSecretsId>1feaff78-ac4f-45ea-8f71-fbc880a86303</UserSecretsId>
  </PropertyGroup>`

I tried Self contained and Framework-dependent without any success
Any idea what is the problem?

**Comment by javiercn** [comment]
@malballah thanks for contacting us.

@pranavkm  can you take a look at this?

**Comment by malballah** [comment]
It turned out it was an issue from Automapper, thank you for your interest.
