### ISSUE TITLE
App stuck loading dlls

### ISSUE THREAD

**Issue by massimilianokraus** [aspnet/AspNetCore#17492]
## Environment data

dotnet --info output: Version: 3.0.101; Commit: bc5f8df0f5
OS: macOS Catalina, version: 10.15.1
(less important:)
VS Code version: 1.40.2
C# Extension version: 1.21.8

## Steps to reproduce
Create a new web app with `dotnet new mvc -n MyApp`, or use any already created web app, of type "web" or "mvc".
Debug the application with VS Code or run it with `dotnet run`.

## Expected behavior
All the dlls load and the app runs.

## Actual behavior

The dll loading process stops after loading System.Threading.Timer.dll, and it remains stuck forever.
If I stop the debug session in VS Code, one or more "dotnet" processes remain dead in the background, and I have to stop them via Activity Monitor.
Sometimes it unblocks after some minutes.
Sometimes it just works as expected.
Sometimes it's freezing not after the Timer.dll but right after the UserSecrets.dll is loaded.

## Additional Infos

This had never happened until a month ago.
This started to happen while I had .NET Core 2.2, and keeps happening with .NET Core 3.0.1.

If I execute with more verbosity, like `dotnet run -v d`, the logs stop on this line:
"Using launch settings from /Users/mk/Desktop/Boh2/Properties/launchSettings.json..."
I have such a file, with the default configuration, which works with non-web apps.
The problem is present only for web/mvc apps. Simple console apps are runnable and debuggable without any issue.

I didn't configure particular paths in the launch.json file.

"Just my code" is enabled.

**Comment by javiercn** [comment]
@massimilianokraus thanks for contacting us.

This seems like a machine specific behavior. Can you try and see if you reproduce it in a separate machine? This doesn't seem to be specific to ASP.NET Core, so I would recommend you follow up in the dotnet repository https://github.com/dotnet/coreclr as they'll be able to help you better.
