### ISSUE TITLE
Mention your good ideas front and center: Azync > Async Controller actions.

### ISSUE THREAD

**Issue by aubergemediale** [aspnet/AspNetCore#17501]
A new feature of AspNetCore 3 is that a controller action, where the method name ends with 'Async' will now return a 404 to the caller. It took me almost a day to find out, why the endpoint did not work any more after updating from 2x.

My solution was then to rename the method to DoItA**z**ync, which enabled everything again, and after updating all clients with the new Urls, all was good again.

It's certainly a great idea not to leak implementation details, like async or not, which makes us all feel much more secure.

But really, inventions like this one should be shouted out in caps on the front pages, and not be so modestly hidden. And this is what this feature request is about.

Kind regards!

**Comment by Kahbazi** [comment]
I think this change has been announced in Announcement repository.
https://github.com/aspnet/Announcements/issues/351

**Comment by aubergemediale** [comment]
Indeed!
