### ISSUE TITLE
Publishing Pdbs as assets to debug with SourceLink

### ISSUE THREAD

**Issue by TulyOpt** [aspnet/AspNetCore#17515]
Hi, I am trying to debug a dotnetcore 3.0 OpenId Server (using IdentityServer which itself uses the AspnetCore librairies that I am trying to debug) . I tried to compile the libraries and add the pdb to my project directory but the process is really tedious : 

- I  have to rename all the dependencies with the correct tags
- I have to modify the Nuget.config to point to local directory
- I have to copy pdbs in various locations

For the moment, I couldn't succeed because of various problems of dependencies.

I recently discovered SourceLink ( which is recently GA) and if had the pdbs of AspNetcore it would so simple to debug this app.

Would it be possible to publish the pdbs of AspNetCore for windows/linux as an asset of a github release ?

**Comment by javiercn** [comment]
@TulyOpt thanks for contacting us.

ASP.NET Core already supports sourcelink and publishes PDBs to the appropriate symbol servers for all the releases.

I suggest you look into https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink and also turn off "Just my code" in visual studio if its not working for you at the moment.

We use it ourselves many times to debug/troubleshoot customers issues, so you shouldn't have a problem getting it to work.

**Comment by TulyOpt** [comment]
Hi @javiercn , thanks for your quick answer. However, I still can't find the pdbs for the debugging process : is there a public url where I can't them ( i am using Linux) ? Is this : http://srv.symbolsource.org/pdb/Public that I should request ?
