### ISSUE TITLE
Blazor Server authorization fails with Microsoft.AspNetCore.Authentication.Negotiate 

### ISSUE THREAD

**Issue by akorchev** [aspnet/AspNetCore#17527]
### Describe the bug

It seems that the `Authorize` attribute does not work with Microsoft.AspNetCore.Authentication.Negotiate authentication and roles. 

### To Reproduce
1. Create a server-side blazor application with Windows Authentication.
2. Add the Microsoft.AspNetCore.Authentication.Negotiate package.
3. Enable it
```
services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate();
```
4. Use middleware to challenge the authentication scheme:
```
 services.AddScoped<ValidateAuthentication>();
```

```
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseMiddleware<ValidateAuthentication>();
```

```
    internal class ValidateAuthentication : IMiddleware
    {
        public async Task InvokeAsync(HttpContext context, RequestDelegate next)
        {
            if (context.User.Identity.IsAuthenticated)
                await next(context);
            else
                await context.ChallengeAsync();
        }
    }
```
5. Add authorize attribute to Index.razor with some group that your windows user is a member of.
```
@attribute [Authorize(Policy = "TestGroup")]
```
6. **Important !!! Run with the default profile from launch settings and not IIS Express!!!** (it works with IIS Express).  After logging in the app would show you that you are not authorized even though you are a member of the group. 
![image](https://user-images.githubusercontent.com/454726/69987242-b9a9dd80-1547-11ea-83a3-867174e170af.png)

Strangely enough if you debug `IsInRole("TestGroup")` returns true.
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/454726/69987340-f70e6b00-1547-11ea-8306-b1eff30f895b.png">

I suspect it is related to the authentication scheme which one normally could pass to the Authorize attribute. However Blazor doesn't allow setting the AuthenticationSchemes property of the Authorize attribute:

```
NotSupportedException: The authorization data specifies an authentication scheme. Authentication schemes cannot be specified for components.
Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.EnsureNoAuthenticationSchemeSpecified(IAuthorizeData[] authorizeData)
```
### Further technical details
- ASP.NET Core version:  3.1.100-preview3-014645
- Visual Studio 2019 Preview 6, Windows 10 Pro

**Comment by blowdart** [comment]
This isn't blazor related, but an actual limitation of our kerberos middleware. We're tracking [adding group/role support](https://github.com/aspnet/AspNetCore/issues/12938) but right now it simply isn't there, because you don't get enough information in a kerberos ticket.

**Comment by akorchev** [comment]
@blowdart why does IsInRole work then? I also see all groups added as claims. Another thing that works is this:

```
 endpoints.MapBlazorHub()
      .RequireAuthorization( new AuthorizeAttribute { 
        AuthenticationSchemes =  NegotiateDefaults.AuthenticationScheme, 
        Roles="TestGroup" 
});             
```

Obviously I can't use it as makes all pages require that role but still.

**Comment by akorchev** [comment]
The linked issue gave me an idea - to test with the group id:

```
@attribute [Authorize( Roles = "S-1-5-21-193572532-2712524652-3721290085-1001")]
```

which worked!

**Comment by blowdart** [comment]
Oh I see. Luck kind of. WindowsIdentity is special, it doesn't bring the roles names with it, role name resolution is done through the WindowsIdentity class, which makes a call out to the server. IIS and IIS Express resolve WindowsIdentity, but "plain" kerberos auth, using the negotiate middleware does not as yet.

**Comment by akorchev** [comment]
I ended up using a claims transformation which somewhat works:

```
    public class CustomClaimsTransformation : IClaimsTransformation
    {
        public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
        {
            var identity = principal.Identity as WindowsIdentity;
            foreach (var groupId in identity.Groups)
             {
                var group = groupId.Translate(typeof(NTAccount));
                var c = new Claim(identity.RoleClaimType, group.Value.Split("\\").Last());
                identity.AddClaim(c);
            }

            return Task.FromResult(principal);
        }
    }
```

**Comment by blowdart** [comment]
That works, but if you're thinking about cross platform you'd need a null check in there after the cast, in case you're not running under Windows.
