### ISSUE TITLE
Unable to find debuggable browser tab for new ASP.NET Core hosted Blazor WebAssembly app

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#17537]
Repro steps:

- Create a new ASP.NET Core Hosted Blazor WebAssembly app (3.1.0-preview4) from Visual Studio
- Run the app (Ctrl-F5) and browse use Edge Beta (79.0.309.40)
- Hit Shift-Alt-D

Expected:

- Instructions shown on how to run the browser with remote debugging enabled

Actual result:

![image](https://user-images.githubusercontent.com/1874516/70023215-89fcd480-154b-11ea-9247-5bb9304c9099.png)

Workaround:

- Run and debug the client project instead of the server project, or close and reopen the solution and try again
- Subsequently created apps don't appear to have the same problem

**Comment by SteveSandersonMS** [comment]
> Subsequently created apps don't appear to have the same problem

Are you saying this happens just once (ever) per installation of Windows / VS? Or are you saying it just happens randomly and with low probability?

**Comment by danroth27** [comment]
I'm saying it happened the first time I created an app with preview4, and I haven't been able to reproduce it again.

**Comment by mkArtakMSFT** [comment]
I'm closing this for now. We'll reopen if any other reports come in.
