### ISSUE TITLE
Error 500.0 when deploying asp core 3.0 to iis windows server 2016

### ISSUE THREAD

**Issue by Razgort** [aspnet/AspNetCore#17543]
hi guys,
I'm trying to deploy my asp core api on iis.
Its all working fine when deploying to azure web app.
But on iis i have the following error :
(see screen shot)
![image](https://user-images.githubusercontent.com/9212658/70043143-4a240480-15c0-11ea-8ac0-5740e2974276.png)

Has anyone encountered this issue already ? i could not found any information about it ....

**Comment by Tratcher** [comment]
What did you get by following the given troubleshooting steps?

**Comment by Razgort** [comment]
I followed stepped from here
https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-3.0&tabs=visual-studio
I looked for all troubleshooting since yesterday ...
Got me nowhere ...

**Comment by Razgort** [comment]
this is resolved using hosting bundle 3.1 instead of 3.0 dont know why ...
