### ISSUE TITLE
How can i use IJSRuntime before ConfigureServices in startup

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/AspNetCore#17545]
How can i use IJSRuntime before ConfigureServices?

this was asked in #5664, but it wasn't answered.

**Comment by SteveSandersonMS** [comment]
I don't think we have a way to do that, since the JS runtime instance is created as part of the startup flow that calls `ConfigureServices`. There would have to be some totally different APIs for instantiating a JS runtime.

**Comment by xrkolovos** [comment]
Is this tracked in an other issue? Why ypu closed it?

thank you
