### ISSUE TITLE
System.Text.Json Serializer uses declared array item type rather that runtime type

### ISSUE THREAD

**Issue by y-lobau** [aspnet/AspNetCore#17542]
I'm not sure is it a bug or a feature, but i'm getting unexpected result when performing object-json serialization on asp.net core 3.0:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26
```
```
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\
```

```
Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199
```

Consider the following class structure:

   ```C#
public class ClassA
    {
        public string BasePropA { get; set; } = "value A";
    }
    public class ClassB: ClassA
    {
        public string ChildPropB { get; set; } = "value B";
    }
    public class ArrayContainer
    {
        public ClassA[] Items { get; set; } =
        {
            new ClassB()
        };
    }
```

When using `System.Text.Json.JsonSerializer.Serialize()` resulting json includes only BasePropA value, but when serializing it with Newtonsoft.Json.JsonConvert.SerializeObject() it contains both - parent and child fields, which is expected (see img bellow):

![image](https://user-images.githubusercontent.com/52859087/70042020-40ee6400-15cf-11ea-944c-0a074b5079de.png)

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/corefx/issues/38650.
