### ISSUE TITLE
Razor “cshtml.g.cs” files not being generated

### ISSUE THREAD

**Issue by AlissonRS** [aspnet/AspNetCore#17554]
### Describe the bug
Any .net core 2.2 web application projects with razor gives this error when building:

![image](https://user-images.githubusercontent.com/4753901/70077587-fa156400-15f8-11ea-82f5-1b0a864e2171.png)

### To Reproduce
I just have to create a brand new .net core 2.2 web application (as per the image above).

I already reinstalled VS 2019 (16.3.10) and the .Net Core SDKs. Same project builds fine on other machines. Seems like razor has some global configuration for generating these cshtml.g.cs files, but reinstalling VS was not enough to fix it, these files are not being generated inside obj\Debug\netcoreapp2.2\Razor\Views subfolders.

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by NTaylorMullen** [comment]
@AlissonRS is that `dotnet --info` output from inside of package manager console in VS or at the command line?

**Comment by AlissonRS** [comment]
@NTaylorMullen package manager console in VS. Should I get it from cmd directly?

**Comment by NTaylorMullen** [comment]
@AlissonRS getting it from package manager console was preferable because I was curious if that's what your VS was using 😄.

**Comment by AlissonRS** [comment]
@NTaylorMullen quick update. I uninstalled VS 2019 and SDKs again, then I deleted these folders:

- C:\Program Files\dotnet
- %USERPROFILE%\AppData\Local\Microsoft\dotnet
- %USERPROFILE%\AppData\Local\Microsoft\MSBuild
- %USERPROFILE%\AppData\Local\Microsoft\VisualStudio
- %USERPROFILE%\AppData\Local\Microsoft\VisualStudio Services
- %USERPROFILE%\AppData\Local\Microsoft\VSApplicationInsights
- %USERPROFILE%\AppData\Local\Microsoft\VSCommon
- %USERPROFILE%\.nuget
- %USERPROFILE%\Visual Studio 2019

Then I installed VS 2019 again, and now it works. Do you want me to share these folders and their content here, or can we just close this?

**Comment by NTaylorMullen** [comment]
> Then I installed VS 2019 again, and now it works. Do you want me to share these folders and their content here, or should we just close this?

Ah, no that's ok. So occasionally the .NET SDK fails to install or uninstall everything for a variety of reasons (one example being Antivirus) and you get into borked states like the one you provided. I'm glad it's fixed on your end now though!
