### ISSUE TITLE
Setting ApplicationKey Name after UseStartup causes reflection exception

### ISSUE THREAD

**Issue by joshpearce** [aspnet/AspNetCore#17557]
### Describe the bug
Setting ApplicationKey Name after UseStartup causes a reflection exception because the string passed for the value is attempted to be loaded as an assembly via reflection.

Setting is before does not.

You can try this on any app by just adding a UseSetting call after UseStartUp.

### To Reproduce

``` C#
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>().
                .UseSetting(WebHostDefaults.ApplicationKey, "My App")
                .UseSerilog();
```

Exception has occurred: CLR/System.IO.FileNotFoundException
An exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Could not load file or assembly 'My App, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.WebHost.<>c__DisplayClass8_0.<CreateDefaultBuilder>b__0(WebHostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at webapp.Program.<Main>d__3.MoveNext() in /Users/joshuapearce/Code/captainproton2/webapp/Program.cs:line 30

### Further technical details
- netcoreapp3.0
- Microsoft.AspNetCore.* 3.0.0
- VS Code for Mac

.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.101/

Host (useful for support):
  Version: 3.0.1
  Commit:  32085cbc72

.NET Core SDKs installed:
  2.2.401 [/usr/local/share/dotnet/sdk]
  3.0.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by joshpearce** [comment]
Let me give a little more background. I'm using the build in IdentityServer authentication. In the nav bar for the Identity area, @Environment.ApplicationName is used for the name of the application, which led me to believe that, it's just a name, not necessarily an assembly name that would be used all over the place, MVC engine, etc.

It's natural, that I would want to change that text in the Identity UI, and this is the only way to do it. I suggest to just change that _layout.cshtml to be a little smarter (like pull the name from the appsettings.json and change the project template) since the gap between just changing the name, and using your own IdentityServer rather than this bundled one, is huge.

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/_Layout.cshtml

**Comment by javiercn** [comment]
@joshpearce thanks for contacting us.

It's likely that having a different application name is confusing the Static Web Assets runtime piece, as it tries to load the assembly based on the application name to figure out the location of the static assets manifest on disk.

Many things on the framework use the ApplicationName as a way to find the entry point assembly for the app, as the application name is set correctly in many contexts where Assembly.GetEntryPointAssembly is not (for example during tests).

Based on your scenario. I suggest you scaffold the layout for the identity UI inside `/Areas/Identity/Pages/Shared/_Layout.cshtml` and modify the contents in it to better suit your app needs.

**Comment by joshpearce** [comment]
Hi @javiercn 

Your explanation of the use of the application name makes sense to me. But I'm not sure I follow this:

> Based on your scenario. I suggest you scaffold the layout for the identity UI inside /Areas/Identity/Pages/Shared/_Layout.cshtml and modify the contents in it to better suit your app needs.

Are you saying that the Razor Pages area that is built into Microsoft.AspNetCore.Identity.UI can be selectively overridden? Or are you suggesting to completely implement a new UI like this: https://github.com/IdentityServer/IdentityServer4.Quickstart.UI

**Comment by javiercn** [comment]
@joshpearce Yes. Overriding the UI for Identity should be orthogonal to using Identity Server with our integration package.
