### ISSUE TITLE
SignInManager.PasswordSignInAsync should return provide more details on failure

### ISSUE THREAD

**Issue by AhmedMKamal** [aspnet/AspNetCore#17555]
### Is your feature request related to a problem? Please describe.
No, it's not a problem.

for now the default behavior of `Microsoft.AspNetCore.Identity.SignInManager.PasswordSignInAsync` method is that it returns a `SignInResult` object that describes the result of the sign-in process and it's working just fine, but the `SignInResult` object doesn't describe the result in detail, for instance, it doesn't describe if the sign-in failed because of the wrong credentials or the user's account is not confirmed.

### Describe the solution you'd like
The solution that I can think of is that the `SignInResult` class may have additional properties that provide more details about the sign-in result.

for example:
```c#
public class SignInResult
{
    public bool IsLockedOut { get; protected set; }
    public bool IsNotAllowed { get; protected set; } // non-specific reason
    public bool RequiresTwoFactor { get; protected set; }
    public bool Succeeded { get; protected set; }

    // additional properties (just as an example).
    public bool EmailNotConfirmed { get; protected set; }
    public bool PhoneNotConfirmed { get; protected set; }
}
```

### Additional context

The current use-case is as following (simplified)
```c#
public async Task<IActionResult> SignInAsync([Bind("Email,Password,RememberMe")]SignInCredentials credentials)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = await _signInManager
                .PasswordSignInAsync(credentials.Email, credentials.Password, credentials.RememberMe)
                .ConfigureAwait(false);

            if (result.Succeeded)
            {
                var user = await _userManager.FindByEmailAsync(credentials.Email)
                    .ConfigureAwait(false);

                return Ok(user);
            }
            else if (result.IsLockedOut)
            {
                ModelState.AddModelError("LockedOut", "This account is locked out");
                return BadRequest(ModelState);
            }
            else
            {
                ModelState.AddModelError("IncorrectCredentials", "Email or Password is incorrect.");
                return BadRequest(ModelState);
            }
        }
```

The use-case that I'm thinking of is as following (simplified)
```c#
public async Task<IActionResult> SignInAsync([Bind("Email,Password,RememberMe")]SignInCredentials credentials)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = await _signInManager
                .PasswordSignInAsync(credentials.Email, credentials.Password, credentials.RememberMe)
                .ConfigureAwait(false);

            if (result.Succeeded)
            {
                var user = await _userManager.FindByEmailAsync(credentials.Email)
                    .ConfigureAwait(false);

                return Ok(user);
            }
            else if (result.EmailNotConfirmed)
            {
                // more specific/user-friendly error :)
                ModelState.AddModelError("EmailNotConfirmed", "The email address is not confirmed");
                return BadRequest(ModelState);
            }
            else if (result.IsLockedOut)
            {
                ModelState.AddModelError("LockedOut", "This account is locked out");
                return BadRequest(ModelState);
            }
            else
            {
                ModelState.AddModelError("IncorrectCredentials", "Email or Password is incorrect.");
                return BadRequest(ModelState);
            }
        }
```

**Comment by blowdart** [comment]
This is a deliberate choice to avoid giving information to an attacker.

**Comment by AhmedMKamal** [comment]
@blowdart I see, and I agree that it's a valid choice for some use-cases but, in other use-cases where the app's design requires you to provide this kind of error message it will be better to have that option in the framework that you're using.

I think it'll be better to provide this feature (may be disabled by default) and let the developer design if they want to use it or not instead of enforcing all developers to follow the same design, or what do you think?

**Comment by blowdart** [comment]
We try to design APIs that are successful by default and can't be made insecure. The option could rather violate this. 

We can consider it for v5, but it's a change I'm uncomfortable with from a security point of view.

**Comment by AhmedMKamal** [comment]
From a security point of view I agree :+1:

So, let's close this issue and not consider this feature since the developers can work around it and find out the specific reason for the sign-in failure if they want to :slightly_smiling_face:

Please let me know if you agree to close it.

**Comment by blowdart** [comment]
Thank you for understanding.
