### ISSUE TITLE
How to Log Controller/Handler Name From Middleware

### ISSUE THREAD

**Issue by zachwieja** [aspnet/AspNetCore#17551]
I want to log (along with other things) the name of the controller that is ultimately invoked.  That seems to require that controllers make an explicit call or use an ActionFilter.  I don't want to encumber controller writers with that.   How can I do this in middleware?   Essentially I want to insert middleware between the endpoints and the controllers.

Any recommendations?

**Comment by Kahbazi** [comment]
You can add a middleware after `UseRouting()` and before `UseEndpoints()` and use the endpoint metadata to get the controller name.

```
app.UseRouting();

app.Use((context, next) =>
{
    var endpoint = context.GetEndpoint();
    if (endpoint != null)
    {
        var controllerActionDescriptor = endpoint.Metadata.GetMetadata<ControllerActionDescriptor>();
        if (controllerActionDescriptor != null)
        {
            var controllerName = controllerActionDescriptor.ControllerName;
           // you can log controllerName here
        }
    }

    return next();
});

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");
});
```

**Comment by javiercn** [comment]
@zachwieja thanks for contacting us.

@Kahbazi answer is correct, that's the appropriate approach.

**Comment by zachwieja** [comment]
Verified.  Thank you.
