### ISSUE TITLE
Improve docs about IdentityServer configuration

### ISSUE THREAD

**Issue by hodzanassredin** [aspnet/AspNetCore#17559]
I'm tried to create a SPA application(asp net core 3) from the template and add custom console client, unfortunately, it took to much time to find a solution.

`dotnet new react -o Test -au Individual`

After that, I found that there is a section IdentityServer in appsettings.json.

`  "IdentityServer": {
    "Clients": {
      "Test.Web": {
        "Profile": "IdentityServerSPA"
      }
    }
  },`

I tried to add the custom client as described in docs from IdentityServer. After several hours I found that this is not the same config as IS has. You have to define Profile(and there is no profile for console app with ClientCredentials grant) or you will get "System.InvalidOperationException: 'Type '' is not supported.'". And you don't need to set ClientId and use the dictionary key as an id of a client. After that, I tried to create my own console client in code and added it.

```
 services.AddIdentityServer()
            .AddApiAuthorization<ApplicationUser, ApplicationDbContext>()
            .AddInMemoryClients(GetClients())
            .AddInMemoryApiResources(Apis);

```
```
                new IdentityServer4.Models.Client
                {
                    ClientId = "console",

                    // no interactive user, use the clientid/secret for authentication
                    AllowedGrantTypes = GrantTypes.ClientCredentials,

                    // secret for authentication
                    ClientSecrets =
                    {
                        new IdentityServer4.Models.Secret(s)
                    },
                    
                    // scopes that client has access to
                    AllowedScopes = { "Test.WebAPI" },
                    Enabled = true
                },
```
Unfortunately, this code removes SPA client defined in appsettings. If I change the order of the lines then SPA client overwrites my own client.

After some investigation, I found two ways to resolve that. Add SPA client manually
```
                new IdentityServer4.Models.Client
                {
                    Enabled = true,
                    ClientId = "Test.Web",
                    ClientName = "Test.Web",
                    RequireConsent = false,
                    AllowedGrantTypes = {GrantType.AuthorizationCode },
                    AllowedCorsOrigins = { },
                    AllowAccessTokensViaBrowser = true,
                    //ClientUri = "https://localhost:44336",
                    RedirectUris =           { "https://localhost:44336/authentication/login-callback" },
                    PostLogoutRedirectUris = { "https://localhost:44336/authentication/logout-callback" },
                    RequireClientSecret = false,
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,

                        "Test.WebAPI"
                    }
                }
```

Or use this code(I didn't tried it):
```
            services.AddSingleton<IEnumerable<IdentityServer4.Models.Client>>(sp =>
            {
                var options = sp.GetRequiredService<IOptions<ApiAuthorizationOptions>>();
                options.Value.Clients.AddRange(GetClients().ToArray());
                return options.Value.Clients;
            });
```

It would be great to describe these moments in docs. Thanks.

**Comment by javiercn** [comment]
@hodzanassredin thanks for contacting us.

We do have some documentation about this already. Is there something you think is missing? This is described https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#other-configuration-options

Keep in mind that our support is focused on SPA applications so for something like a console client you will have to do it manually, but that can be done by adding it to `ApiAuthorizationOptions.Clients`

**Comment by hodzanassredin** [comment]
I think it is good enough. Unfortunately, I was not able to find it. Probably my miss.

**Comment by hodzanassredin** [comment]
Probably "Identity with SPA" is not the place where you are expecting to find information about clients configuration.
