### ISSUE TITLE
Blazor FR: Graceful Degradation on 5xx errors

### ISSUE THREAD

**Issue by HughPH** [aspnet/AspNetCore#17569]
When loading a BlazorWASM app, and a server or service returns a 5xx error, Blazor will _ignore_ the error and then fail (quietly, in the console) when trying to load the affected assembly.

I appreciate that BlazorWASM has not reached GA at this time, but I do feel strongly that this is something that needs to be considered.

### The solution as I envisage it:

Actually having given this some thought, I don't need Blazor to degrade gracefully. I just need it to tell me what's going on so my app can degrade however gracefully or gracelessly is appropriate.

In my personal project, I have a splash screen with an Ajax Loader GIF. It's just HTML until Blazor loads. When a 5xx occurs, the effect is that the app just stays on that splash screen - there is no feedback. What would work well in that circumstance is some kind of JavaScript hooks or Well-Known Methods that could be called by Blazor to communicate download progress & state. I could then communicate to the user with something 'friendly' like "Oops, it looks like there's a problem loading the app. We'll keep trying..."

Alternatively I might count the retries (communicated in the status) and after 3 failures (or an expired time), I might just redirect the user to a page that says "Everything's borked. Try again later."

**Comment by javiercn** [comment]
@HughPH thanks for contacting us.

You could do this by using Blazor.start. I'm linking you to the server docs for a sample, but it works the same way for blazor wasm. https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#configure-the-signalr-client-for-blazor-server-apps

**Comment by HughPH** [comment]
Thanks for your attention to this Javier!

The "guts" of my index.html boils down to two lines:

```html
<div style="position:absolute;top:0;left:0;right:0;bottom:0;opacity:0;transition-timing-function: ease-in-out;transition-property: opacity;transition-duration: 1s;">
    <app></app>
</div>

<script src="_framework/blazor.webassembly.js"></script>
```

The "splash screen" is another div before this one.
Once my app is loaded, I set its div's opacity to 1 with jsinterop, and it smoothly fades in. I could equally put the "splash screen" over the top and fade it out.

I _imagine_ your proposal is to add `autostart="false"` to the the blazor.webassembly.js script tag, and add the following after that script tag:

```html
<script>
  Blazor.start(
    {
      myStartThing: function(builder) {
        // do something with builder here?
      }
    }
  );
</script>
```

Am I on the right track?

The next question I'm going to have is what builder will do for me, and whether I can capture and deal with errors at that point?

**Comment by HughPH** [comment]
https://gist.github.com/SQL-MisterMagoo/5d857941f884eb1a2d80e72b1044e292

Another approach may be to use a Service Worker
