### ISSUE TITLE
Support Model Binding to JsonDocument and Response Serialisation from JsonDocument

### ISSUE THREAD

**Issue by oliverjanik** [aspnet/AspNetCore#17564]
AspNetCore version 3.0

Model Binding currently throws:
```csharp
        [HttpPost]
        public IActionResult Post([FromBody] JsonDocument doc)
        {
            /// snip
        }
```

Response serialization does not treat JsonDocument well:
```csharp
        [HttpGet]
        public IActionResult GetStuff()
        {
            JsonDocument doc = /// ... get data;

            Ok(doc);
        }
```
It outputs
```json
{
    "RootElement": ...
}
```

Quite unexpected, this worked well with JObject.

Apologies, if this has been discussed previously.

**Comment by javiercn** [comment]
@oliverjanik thanks for contacting us.

We believe this is a feature missing on the JSON Serializer. It will be better if you file this issue in the https://github.com/dotnet/corefx repository.

@ahsonkhan This might interest you.

**Comment by pranavkm** [comment]
You should be able to serialize \ deserialize a `JsonElement` instance:

```
[HttpPost]
public IActionResult Post([FromBody] JsonElement element)

..

return Ok(doc.RootElement);
```

**Comment by ahsonkhan** [comment]
> We believe this is a feature missing on the JSON Serializer. 

Yep, this is a known issue: https://github.com/dotnet/corefx/issues/42056

However, what @pranavkm mentioned (i.e. pass in `doc.RootElement`) will work as a workaround, since the JSON serializer does support `JsonElement`.

> It will be better if you file this issue in the https://github.com/dotnet/corefx repository.

FYI, it should be filed in the https://github.com/dotnet/runtime repo now (see https://github.com/dotnet/corefx/issues/42733).

**Comment by oliverjanik** [comment]
Thanks for all the pointers. It's bloody hard to find what repo to file issues in, unfortunately. It would be good if maintainers could "move" the issue instead of closing it.

**Comment by ahsonkhan** [comment]
> It would be good if maintainers could "move" the issue instead of closing it.

I would have considered moving it if we didn't already have an existing issue.
