### ISSUE TITLE
Visual studio 16.4.0 update of 2019/12/04

### ISSUE THREAD

**Issue by niconico49** [aspnet/AspNetCore#17578]
### Describe the bug
After the upgrade of visual studio 16.4.0 of 2019/12/04
In every razor page for every components included and correctly reference by the @using syntax the intellisense doesn't recognize this situation!!! Despite this the visual studio compiles correctly

But this other problem is more critical!!!!!!!!!!!!!!!!!!

"Every breakpoint debugger" in a "vb.net" project shows the window with stop / edit choice despite the compilation runs correctly, but obviously my work is blocked because the debugger is unusable...

What's happening??????

### To Reproduce
Open a vb.net project in visual studio and add a breakpoint debugging and then try to go next by F10 or to jump to another instruction by the "set next statement" debugging utlility.

### Further technical details
Visual Studio Community 16.4.0 of 2019/12/04

**Comment by adrianwright109** [comment]
The debugging issue with Edit and Continue when no changes have been made to the code is an on going issue that doesn't seem to have been resolved as yet.

It has been raised in the Developer Community via the VS Feedback tool.

See the 3 page thread here: [https://developercommunity.visualstudio.com/content/problem/705494/without-any-changes-to-source-files-edits-were-mad.html](https://developercommunity.visualstudio.com/content/problem/705494/without-any-changes-to-source-files-edits-were-mad.html)

**Comment by niconico49** [comment]
Now I've, in some sense solved the problem of edit and continue by disabled that option from visual studio (from the tools => options => debugging

But the other problem about the intellisense remains.... and now become critical too, because now the visual studio doesn't show the correct highlight in the component razor!!!
The debugging in that .razor component is not active (in every breakpoint visual studio claims that wasn't possible to load the symbol of that razor components and so the breakpoint will be disabled)

The visual studio doesn't recognize the component made externally (the previous version of visual studio didn't have this bug) and

over the top now the components razor made in other projects doesn't take the last modify: in some sense seems that the visual studio takes in consideration an old compiled razor and not the last currently modified!!!!!

**Comment by javiercn** [comment]
@niconico49 thanks for contacting us.

In order for us to better troubleshoot this issue, could you file it through the Send feedback dialog in Visual Studio and include the ticket link in this issue? https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

@NTaylorMullen Can you take a look?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Can you take a look?

@niconico49 Could you provide a simple repro project and steps with expected/actual on how to reproduce?
