### ISSUE TITLE
razor page changes compiled automatically

### ISSUE THREAD

**Issue by FrancisFYK** [aspnet/AspNetCore#17574]
Razor Page multiple Areas are separated in different projects, and each change requires manual recompilation. Is there any configuration that can be automatically compiled with the same changes as MVC?

**Comment by javiercn** [comment]
@FrancisFYK thanks for contacting us.

@pranavkm can you answer this?

**Comment by pranavkm** [comment]
There's a tracking issue to add support for this in VS: https://github.com/dotnet/project-system/issues/3163. In the meanwhile, you could consider using runtime compilation to make this amenable today. The sample here - https://github.com/aspnet/samples/blob/master/samples/aspnetcore/mvc/runtimecompilation/MyApp/Startup.cs#L35-L39 - demonstrates using runtime compilation to watch for file changes in class libraries.

**Comment by FrancisFYK** [comment]
@pranavkm thanks this method is ok
