### ISSUE TITLE
Codeowners not working for aspnet/http2

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#17587]
We added CODEOWNERS entries for the shared HTTP2 code for the aspnet/http2 group:
https://github.com/aspnet/AspNetCore/blob/3b7cdc166aa3c9733fa60b56d91fc0fff9b11652/.github/CODEOWNERS#L22-L23

But it still isn't requesting PR reviews when those files are changed:
https://github.com/aspnet/AspNetCore/pull/17573

Apparently that group needs write access to the AspNetCore repo, not just read access.
https://github.community/t5/How-to-use-Git-and-GitHub/CODEOWNERS-works-with-users-but-not-teams/td-p/4986

That lines up with the CODEOWNERS group that we do know works, aspnet/build, which has write access to the repo.

We'd need to make the same changes for aspnet/http3, and for the matching groups in dotnet/runtime.

@anurse is this viable?

**Comment by anurse** [comment]
Done.
