### ISSUE TITLE
Accessing HttpContext.Items fails on WebKit browsers

### ISSUE THREAD

**Issue by sven5** [aspnet/AspNetCore#17585]
We're developing a .NET Core 3.1 Blazor application.
In short, we use custom middleware to authenticate the User and store the `IdentityUser` object in the `HttpContext.Items` collection to retrieve it later in a scoped service. This works fine for most scenarios. However, there seems to be a problem when using a WebKit device (Apple iPad). The `HttpContext.Items` is always null. It seems that the behavior is different than with other browsers.

The following code is throwing:
`public IntranetUser User => _httpContextAccessor.HttpContext?.Items["IntranetUser"] as IntranetUser;
`

StackTrace:
```
System.ObjectDisposedException: IFeatureCollection has been disposed.
Object name: 'Collection'.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Items()
```

### Describe the bug
Access to HttpContext.Items is impossible on Apple devices.

### Further technical details
- ASP.NET Core 3.1
- dotnet.info
```
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.100
 Commit:    cd82f021f4

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- VS 2019 16.5.0 Preview 1

**Comment by javiercn** [comment]
@sven5 thanks for contacting us. 

Is that callstack inside the Blazor App? In general we don't recommend using the IHttpContextAccessor anywhere and it is not something that works with Signalr apps or Blazor apps for that matter.

I recommend you take a look at https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio#authenticationstateprovider-service for tips on how to implement authentication/authorization in Blazor.

**Comment by sven5** [comment]
@javiercn 
Thanks for your support. I think that was the missing piece. I must've missed the `AuthenticationStateProvider`

Regards
Sven
