### ISSUE TITLE
"Preview 3" still part of some strings in Hosting Bundle

### ISSUE THREAD

**Issue by stesee** [aspnet/AspNetCore#17591]
Some strings in RTM Hosting Bundle Installer missed a update:
![image](https://user-images.githubusercontent.com/168659/70179233-f576ab80-16dd-11ea-97e0-5e143b027e1a.png)

### To Reproduce

- Grab https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.0-windows-hosting-bundle-installer
- Run it.
- Look into "Settings" -> "Apps & features" -> Look up "Microsoft .NET Core Runtime - 3.1.0...."
- Display name of Package and Texts used in Installer seems to be wrong

### Further technical details
- ASP.NET Core version 3.1

```powershell
PS C:\Windows\system32> . "C:\Program Files\dotnet\dotnet.exe" --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\Windows\system32>
```

**Comment by javiercn** [comment]
@stesee thanks for contacting us.

We believe this is an issue best filed in https://github.com/dotnet/sdk. You will get a better and faster response there.

/cc: @livarcocc I believe this is your area?

**Comment by stesee** [comment]
Someone else found the same issue and documented it here: https://github.com/dotnet/sdk/issues/4029
