### ISSUE TITLE
AuthorizeAttribute on Blazor pages

### ISSUE THREAD

**Issue by rockfordlhotka** [aspnet/AspNetCore#17597]
I have a client-side Blazor project and am able to use `@attribute [Authorize()]` on a .razor page to prevent display of that page if the user isn't authorized.

I am trying the same thing on server-side Blazor and the attribute appears to be ignored entirely.

In my server-side Blazor pages I am able to access the principal/identity information via the `AuthorizeView` element, a `context.User`, and `HttpContext`. So I'm quite confident that the correct principal is maintained in memory and is available to the UI.

Yet for some reason the `Authorize` attribute is entirely non-functional.

**Comment by rynowak** [comment]
> I have a client-side Blazor project and am able to use @attribute [Authorize()] on a .razor page to prevent display of that page if the user isn't authorized.

This behavior is a feature of the routing system, and depends on the code you have in `App.razor`. Could you share that?

**Comment by rockfordlhotka** [comment]
Sure, here it is

```
<CascadingAuthenticationState>
  <Router AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
      <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    </Found>
    <NotFound>
      <LayoutView Layout="@typeof(MainLayout)">
        <p>Sorry, there's nothing at this address.</p>
      </LayoutView>
    </NotFound>
  </Router>
</CascadingAuthenticationState>
```

**Comment by rockfordlhotka** [comment]
The issue is that I was missing `app.AddAuthorization();` in `Startup.cs`.
