### ISSUE TITLE
Visual Studio UI ambiguous when creating a new ASP.NET Core project

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore#17598]
I was directed here to open the bug. Let me know if I should open it from **Help > Send Feedback > Report a Problem**

![image](https://user-images.githubusercontent.com/3605364/52737321-27145f80-2f70-11e9-8eb0-828478541672.png)

Create a new project in VS2019

Search for `asp.net`

![image](https://user-images.githubusercontent.com/3605364/70193733-276b1c00-16a4-11ea-93eb-834e423fa0e3.png)

It's very hard to distinguish C#/F#/VB - this was fixed in class lib's by changing the icon

![image](https://user-images.githubusercontent.com/3605364/70193795-5e413200-16a4-11ea-9595-28ef2132e7a4.png)

**Comment by TheFanatr** [comment]
There are tags in rounded boxes underneath each element, the first of which will indicate the target language.

**Comment by javiercn** [comment]
@Rick-Anderson Yes. Using the send feedback dialog in VS is the right way.

I'm closing this issue in favor of your ticket.

**Comment by Rick-Anderson** [comment]
https://developercommunity.visualstudio.com/content/problem/846046/create-a-new-aspnet-project-difficult-to-different.html

**Comment by Rick-Anderson** [comment]
@TheFanatr 
>There are tags in rounded boxes underneath each element, the first of which will indicate the target language.

That's a very poor differentiator. I complained about the Class libs and they fixed the class libs.
