### ISSUE TITLE
Render the specific component via blazor service

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#17604]
### Is your feature request related to a problem? Please describe.

I want to render the specific component via the services. Is this possible in blazor? please suggest me on this.

### Describe the solution you'd like

Actual requirement,

I have two components, namely 'Index.razor' and 'Comp1.razor'.

In default the blazor render the 'Index.razor' at initial load. But in that initial load, i want to show the 'Comp1.razor' component over the 'Index.razor'. 

Need 'Comp1.razor' component overlayed on the 'Index.razor'.

How can i implement this ?

### Additional context
I have used latest Core SDK 3.1 preview3 and blazor server application

**Comment by javiercn** [comment]
@kmuthukumar23 thanks for contacting us.

We are not sure we understand your scenario. Could you provide more details on what you are trying to accomplish and how? A sketch of the code you would write and what you would like/expect to happen would help us understand your scenario.

**Comment by kmuthukumar23** [comment]
Hi @javiercn thanks for your update. 

I will create the sample regarding this and update you. 

i have an one doubt regerding blazor component rendering.

is possible to render the component from .cs file.

exact need is render the razor component from .cs file.

Thanks
