### ISSUE TITLE
VS 2019 doesn't recognize custom blazor-components in c#code

### ISSUE THREAD

**Issue by TobiasKoller** [aspnet/AspNetCore#17603]
I've created several small blazor-components.

One is called **Dialog** inside the **Shared**-folder (also tried other names).

When I try to use this component inside another component like
```
<mynamespace.Shared.Dialog @ref="_dialog">..

@code {
...
private mynamespace.Shared.Dialog _dialog;
...
}
```

the tag itself gets recognized but the property `private mynamespace.Shared.Dialog _dialog;`
doesn't.

I get an error "the type or namespace Dialog could not be found (are you missing....)"

sometimes I still can compile even with this error, sometimes I can't.

just updated to latest VS2019 preview which seems to work...

**Comment by javiercn** [comment]
@TobiasKoller thanks for contacting us.

Can you provide details about the Visual Studio version you are using where this is not working?

**Comment by TobiasKoller** [comment]
sure, the current Version is 16.3.10 VS Professional 2019

**Comment by TobiasKoller** [comment]
v 16.4.0 fix this issue
