### ISSUE TITLE
TestServer.CreateClient and setting HttpHandlers

### ISSUE THREAD

**Issue by johnkors** [aspnet/AspNetCore#17616]
### Is your feature request related to a problem? Please describe.
This regarding TestServer and creating httpclients. Today it's not possible (or is there a way? I could not find it) to set the HttpClientHandler.

For example, I would have liked to set a `HttpClientHandler` , for example for ignore the ssl cert validation:

### Describe the solution you'd like
```
var httpClientHandler = new HttpClientHandler
{
    ServerCertificateCustomValidationCallback = (h, a, c, k) => true
};
var testServer = new TestServer(webHostBuilder);
var client = testServer.CreateClient(handler);
```

**Comment by Tratcher** [comment]
HttpClientHandler and ServerCertificateCustomValidationCallback don't apply to the TestServer scenario, it uses a fake in-memory transport. There is no SSL, and thus no cert validation to override.

**Comment by johnkors** [comment]
Ah, ok - maybe the error was further downstream? 

I got errors when integration testing auth setup for my app using TestServer. My my app under test is protected by our internal identityserver instance (where identityserver is using a self-signed SSL cert, not trusted from where I run the integration tests). So the JWT bearer middleware fails to get the discovery document.

```
System.InvalidOperationException : IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
- System.IO.IOException : IDX20804: Unable to retrieve document from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
----- System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
--------- System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure.
tack Trace:
  at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d.MoveNext()
 End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

Maybe what I have to do is disable SSL cert in the JWTBearer handler instead..?

**Comment by Tratcher** [comment]
Correct. Here's how that's set up, several parts are replaceable via the JwtBearerOptions.
https://github.com/aspnet/AspNetCore/blob/0fd9f27d60f727ad9b769f72de5dfae8f840a456/src/Security/Authentication/JwtBearer/src/JwtBearerPostConfigureOptions.cs#L29-L65

**Comment by johnkors** [comment]
Thanks, @Tratcher . I was a bit surprised by this, but creating a static empty oidc configuration made the test pass. I would have expected it to fail with "no configuration error", perhaps. Is an empty OIDC configuration a valid scenario? It looks like an empty OIDC config will be treated as all issues/authorites/signers are valid?

```csharp
var webHostBuilder = new WebHostBuilder()
    .UseStartup<Startup>()
    .ConfigureTestServices(s =>
    {
        s.Configure<JwtBearerOptions>(o =>
        {
            o.Configuration = OpenIdConnectConfiguration.Create("");
        });
    });
```

**Comment by Tratcher** [comment]
That is surprising. That might be worth asking the OpenIdConnectConfiguration owners about at:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

**Comment by johnkors** [comment]
Ok, thanks. Created a ticket: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1307
