### ISSUE TITLE
Render Charts - Could not load file or assembly "System.Windows.Forms, Version=4.0.0.0

### ISSUE THREAD

**Issue by TechAspirant** [aspnet/AspNetCore#17610]
Hello,

I am getting Could not load file or assembly "System.Windows.Forms, Version=4.0.0.0 Error when I have charts in my rdlc file. How can I show charts in my rdlc with AspNetCore.Reporting nuget package ?

**Comment by blowdart** [comment]
That is a third party package, so that would be best asked of them.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something related to this repository. We recommend using [StackOverflow](https://stackoverflow.com) for these types of general questions or raising this concern with the owners of the library/framework you're referring to.
