### ISSUE TITLE
After upgrading to .NET Standard 2.1 and Blazor v3.1.0-preview4.19579.2, Blazor WebAssembly projects no longer work.

### ISSUE THREAD

**Issue by Rauce** [aspnet/AspNetCore#17619]
To rule out any project-specific issues, I followed the instructions at https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio to create a new clean Blazor WebAssembly project.

I can confirm the new project is created targeting .NET Standard 2.1, with Nuget Blazor package versions v3.1.0-preview4.19579.2.

After the project is created, without modifying any of the project files, I simply hit 'Start Debugging' in Visual Studio (2019 v16.4).

In the first build attempt I get the following single error:

```
Code: <blank>
Description: ILLink failed with exited code 1
Project: BlazorApp1
File: Blazor.MonoRuntime.targets
Line: 201
```

If I then immediately immediately try 'Start Debugging' again, it builds without this error, but in the launched browser window the following error appears instead:

```
An error occurred while starting the application.
System.IO.DirectoryNotFoundException: C:\Users\<My Name>\source\repos\BlazorApp1\BlazorApp1\bin\Debug\netstandard2.1\dist\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles(IApplicationBuilder app, String clientAssemblyFilePath)
   at Microsoft.AspNetCore.Blazor.DevServer.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment environment, IConfiguration configuration)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

If I revert this project back to .NET Standard 2.0 and Blazor v3.1.0-preview3.19555.2, it builds and runs without any issues.

Here's the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Any ideas?

**Comment by simonpbond** [comment]
Also having the same issue.

`5>Could not execute because the specified command or file was not found.
5>Possible reasons for this include:
5>  * You misspelled a built-in dotnet command.
5>  * You intended to execute a .NET Core program, but dotnet-C:\Users\Simon does not exist.
5>  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
5>C:\Users\Simon Bond\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets(204,5): error : ILLink failed with exited code 1.`

**Comment by javiercn** [comment]
@Rauce thanks for contacting us.

I'm not sure what can be going on. I would suggest you first try to update to the latest released blazor version, which is preview4 and is built on top of the .NET Core 3.1.0 RTM

**Comment by Rauce** [comment]
@javiercn 

I can confirm the new project I tested with is created targeting .NET Standard 2.1, with Nuget Blazor package versions v3.1.0-preview4.19579.2.

.NET Core 3.1.0 RTM is installed.

**Comment by javiercn** [comment]
@pranavkm Based on this, this seems to be missing the application name, is that correct?
`C:\Users\<My Name>\source\repos\BlazorApp1\BlazorApp1\bin\Debug\netstandard2.1\dist\`

**Comment by Rauce** [comment]
FYI.

If I revert my projects back to .NET Standard 2.0 and Blazor v3.1.0-preview3.19555.2 (while keeping VS2019 16.4.0 and .NET Core 3.1.0 RTM), they build and run without any issues.

**Comment by simonpbond** [comment]
I think you can reproduce this by creating a new Blazor WebAssembly (ASP.NET Core Hosted) project (VS16.4, Latest Templates), and try to rebuild the Client project.

**Comment by GerritBergen** [comment]
Having issues too. Anyone got a workaround?

**Comment by GerritBergen** [comment]
Disabling linking on build seems to work right now.

```
  <PropertyGroup>
    <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
  </PropertyGroup>
```

**Comment by pranavkm** [comment]
Could one of you share a minimal project that reproduces the build error? I tried @simonpbond's suggestion

> I think you can reproduce this by creating a new Blazor WebAssembly (ASP.NET Core Hosted) project (VS16.4, Latest Templates), via the VS UI, and try to rebuild the default generated Client project.

and haven't been able to reproduce the build error.

**Comment by simonpbond** [comment]
@pranavkm [Reproduced project](https://github.com/simonpbond/blazorrequestedrepo)
I try to rebuild the .Client project, it actually built on first try, then on second and third try it failed with IL Link error:

> ILLink failed with exited code 1.

**Comment by pranavkm** [comment]
Thanks!

**Comment by pranavkm** [comment]
Still no luck. I tried running rebuild a couple of times on the *BlazorRequestedRepo.Client* project, tried rebuilding with changes to file and regular builds. All of these succeeded. Is there a specific sequence you're running? Here are a couple of things that would help

* Could you grab the build logs from VS when this happens? To do this, you'll need to install this extension: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools. Once installed go to `View > Other Windows > Build Logging` and click on the ▶️ button (Start build logging). Attach the one from the failing build to this issue.

* Can you look at the Output window and see if it includes any additional content as to why the task failed?

**Comment by jspuij** [comment]
Possibly the same one as this one:
https://github.com/aspnet/AspNetCore/issues/17754

**Comment by simonpbond** [comment]
> 
> 
> Possibly the same one as this one:
> #17754

@jspuij @pranavkm Can confirm this has solved the issue for me.

**Comment by Rauce** [comment]
Woohoo!

@jspuij's solution in #17754 (https://github.com/aspnet/AspNetCore/issues/17754#issuecomment-564431825) fixed this error - my project is working again.

**Comment by pranavkm** [comment]
We'll use the other to track fixing this for the next release.
