### ISSUE TITLE
CORS not working with 2.2, worked well with 2.1, same code

### ISSUE THREAD

**Issue by dcolakchile** [aspnet/AspNetCore#17622]
Describe the bug
The application has been working flawlessly in .net core 2.1. The signalR server's configuration looks like the following code snippet in public void ConfigureServices(IServiceCollection services) method:

services.AddCors(setupAction =>
  setupAction.AddPolicy("MyPolicy",
                    builder => builder
                    .AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials()))
And in Configuration method I have the following code snippet:

 app.UseCors("MyPolicy")
The angular client app's code starts the connection like the following code snippet:

this._connection = this._connection || new HubConnectionBuilder()
        .withUrl('https://localhost:44314/xyz/test?abc=123', options)
        .build();
The signalR client's version is 1.1.0 in both angular app and the C# client application.

To Reproduce
As I said, this setup has always been working fine. I upgraded the .net core application (signalR server) from 2.1 to 2.2 (dotnetcore SDK ver 2.2.101) and I upgraded the signalR client package to 1.1.0. The signalR server serves an angular app and another C# application. The C# application connects to the signalR server perfectly and it does whatever it's supposed to do but the angular app produces the following error message:

Access to XMLHttpRequest at 'https://localhost:44314/xyz/test/negotiate?abc=123' from origin 'https://localhost:44303' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Expected behavior
The application should still keep working after migration from .net core 2.1 to 2.2

Additional context
dotnet version is 2.2.101

**Comment by dcolakchile** [comment]
Same issue was already reported as closed, no idea why, it is still not working.

Tried everything, once it is deployed on IIS, it is no longer working with 2.2.8, 2.1 worked just fine.

Cannot go back to 2.1.

**Comment by BrennanConroy** [comment]
CORS was updated in 2.2 to conform to the CORS standard with regards to `AllowCredentials`. You cannot use `AllowAnyOrigin` and `AllowCredentials` togther, you need to explicitly specify the origins that you want to allow using `WithOrigins`.
