### ISSUE TITLE
_ViewStart not found after upgrading to .Net Core 3.1

### ISSUE THREAD

**Issue by joetherod** [aspnet/AspNetCore#17625]
My app renders its views from the database using all of the provided extensions of razor, fileprovider, locationexpander, etc. All worked fine with 2.0, 2.1, 2.2, 3.0. It doesnt work with 3.1. In debug mode it works. In release mode it doesnt. And my production environment uses release mode. When it parses the razor for my virtual provider, the layout is not set. Request of ViewStart is not called.
My viewstart file is in the root as it always been. Nothing changed except upgrading all packages to 3.1. On the initial load of the site, it calls the for the layout, It doenst afterwards. Since this is a tenant based app, hosted many sites with their own layouts, I need this viewstart called everytime.

Please help. This was working fine in previous versions. Do I need some location expander for the viewstart file now?

**Comment by joetherod** [comment]
For some reason this ViewStart is not called everytime. I have to treat it as a virtual file now. Something was changed in 3.1. This will break any tenent based web application that has its views in the db. Unless there is another way to enforce setting the Layout. My Layout code in the ViewStart is this:

@using Tmp.TalentBrew.Client.Core.Controllers
@{
    Layout = BaseController.GetLayout(ViewContext);
}

**Comment by pranavkm** [comment]
@joetherod are you conditionally referencing the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` package in your project?

**Comment by joetherod** [comment]
@pranavkm Conditionally? I made all the changes to get to work when I migrated from 2.2 to 3.0. Is the something additional now for 3.1?
Its already referenced and I had these lines in the project file:

<PreserveCompilationContext>true</PreserveCompilationContext>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by joetherod** [comment]
Created a test project and wasnt able to reproduce it. So, it is some odd behavior based on the full code base. Just odd how it worked fine in 3.0 and not 3.1.
Either way, I found a work around to ensure ViewStart is processed as needed.
