### ISSUE TITLE
ASP.NET Core 3.1 - Dictionary<string, object> Model binding error

### ISSUE THREAD

**Issue by joseftw** [aspnet/AspNetCore#17649]
### Describe the bug
When using [FromBody]MyInput input where MyInput contains a Dictionary<string, object>, the model becomes really weird.

The bug happens when having a reference to ```Swashbuckle.AspNetCore``` but NOT having a direct reference to ```Microsoft.AspNetCore.Mvc.NewtonsoftJson```.

By having a reference to ```Swashbuckle.AspNetCore``` you get access to the ```AddNewtonsoftJson``` method so you will not get any compiler errors.
So when looking at the code, it SEEMS like Newtonsoft has been configured correctly but it will NOT use Newtonsoft, it will use System.Text.Json instead.

### To Reproduce
1. Clone [this repo](https://github.com/joseftw/JOS.DictionaryModelBindingBug)
2. Start it
3. Set Content-Type to application/json in postman or whatever then make a post to ```http://localhost:5000/weatherforecast``` with the following body
```
{
   "data": {
      "key1": "my value",
      "key2": 1
   }
}
```
4. Inspect the value with the debugger
5. Expected behaviour is that key1 should be object(string) and that key2 should be object (long)
6. Actual behaviour: the values are of type ```JsonElement```

### Images
**ASP.NET Core 3.1 - System.Text.Json**
![aspnetcore31](https://user-images.githubusercontent.com/1232096/70311390-df6a0780-1811-11ea-94dd-c1d775f5a76b.PNG)

**ASP.NET Core 3.1 - Newtonsoft**
![aspnetcore31Newtonsoft](https://user-images.githubusercontent.com/1232096/70311413-e98c0600-1811-11ea-9353-08a6c56b0961.PNG)

### Solution
Install the ```Microsoft.AspNetCore.Mvc.NewtonsoftJson``` nuget package.

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db
```

**Comment by joseftw** [comment]
Additional info:
We had a reference to ```<PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0-rc4" />``` in our csproj file, which gives us access to the ```AddNewtonsoftJson``` method.

When not having a reference to ```Microsoft.AspNetCore.Mvc.NewtonsoftJson```, System.Text.Json is used.
Im not sure if this is working as intended or not. Yes, we DONT have a direct reference to ```Microsoft.AspNetCore.Mvc.NewtonsoftJson``` but we are still able to call the ```AddNewtonsoftJson``` method because of Swashbuckle.

**Comment by pranavkm** [comment]
I'd recommend referencing a 3.0 RTM version of `Microsoft.AspNetCore.Mvc.NewtonsoftJson`. The package version that Swashbuckle references [is an early preview](https://www.nuget.org/packages/Swashbuckle.AspNetCore.SwaggerGen/5.0.0-rc4) and we wouldn't recommend using it in production. The Swashbuckle repo would be a better place to follow up on this to produce a package that is RTM versioned.

**Comment by joseftw** [comment]
Roger that. Just wanted to point out that your documentation for ASP.NET Core 3.1 suggests that one should use the RC version of swashbuckle.
So im thinking that maybe more people will run into this problem...
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio
