### ISSUE TITLE
Blazor Bootstrap 4.3.1 floating label some cases not working or different working with edge/chrome

### ISSUE THREAD

**Issue by Seestern99** [aspnet/AspNetCore#17652]
**Case 1**
Expected Result in Chrome:
![image](https://user-images.githubusercontent.com/16648824/70319887-b18dbe80-1823-11ea-8f81-212d0dd776e9.png)

In Edge grey x over green hook.
![image](https://user-images.githubusercontent.com/16648824/70319636-0b41b900-1823-11ea-8b79-a7686bca1dd1.png)

**Case 2**
In Chrome clear textbox with backspace and after writing text, we have this result.
![image](https://user-images.githubusercontent.com/16648824/70319685-32988600-1823-11ea-9221-df5fc43a6b89.png)

In Edge we see the overlapping result.
![image](https://user-images.githubusercontent.com/16648824/70319698-3926fd80-1823-11ea-8650-b38c357c05d0.png)

We have different behavior in different browsers. 

Why does the floating label behave differently in the browsers, how can you counteract this?

In the razor file we have this code:
        <div class="md-form">
            <label class="bmd-label-floating @CssActive" for="eingabe">Suche</label>
            <input type="text" class="form-control @CssEingabe" id="input" @bind="@SearchContent" @oninput="@(newValue => KeyChange(newValue))" @onkeyup="@KeyUpEvent" @onkeydown="@KeyDownEvent" />
            <div class="@CssEingabe-feedback">@SearchError</div>
        </div>

Do you have any tips to circumvent this behavior?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This seems to be a question about how to use Bootstrap. If you believe this is a Blazor-specific issue, please provide a repro (which uses no Bootstrap) for us to investigate.

**Comment by RonaldGHempel** [comment]
Hi @mkArtakMSFT, I am not quite sure that this is not Blazor related. I think this is related to how Blazor handles events. And doing a repo without Bootstrap wouldn't show the point here. Where can I find deeper information on event handling? I searched blazor.net, of course, but this didn't answer our questions.

**Comment by mkArtakMSFT** [comment]
@RonaldGHempel have you seen this: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#event-handling ?

**Comment by RonaldGHempel** [comment]
@mkArtakMSFT thank you for following up here. Yes, I have seen this and used it as a starter. And it is working as expected in simple scenarios. But we are using https://mdbootstrap.com/docs/jquery/. For example with a select drop-down list when updating the list's content a call to StateHasChanged doesn't do the trick as you need to manually destroy the select box and re-initialize it. I was looking for a way to combine these two parts in a more convenient way.
