### ISSUE TITLE
Reload goes to the wrong page

### ISSUE THREAD

**Issue by Grauenwolf** [aspnet/AspNetCore#17659]
When the browser is idle for too long or the computer wakes up from sleep, we see this message:

> Could not reconnect to the server. **Reload** the page to restore functionality.

### Describe the bug

The **Reload** link takes the user to the home page of the website instead of reloading the current page.

### To Reproduce

1. Go to any page in a server-side Blazor website other than the home page.
2. Wait for connection to break.
3. Press **Reload**. Browser is redirected to home page

### Further technical details

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0-rc4" />
  </ItemGroup>

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
