### ISSUE TITLE
Embed Blazor in Razor Pages

### ISSUE THREAD

**Issue by VBAndCs** [aspnet/AspNetCore#17664]
Embed Blazor in Razor Pages

I hope you allow us to use Balzer easily in Razor pages, simply be marking some methods with a `[Blazor]` or `[RunAtClient]` attribute un the Razor Page code behind file, such as:

```C#
public class IndexModel : PageModel
{
   public void OnGet()
   {

   }

   [Blazor] public void Foo1()
   {

   }
   
   public void Foo2()
   {

   }

}
```
Foo1 is a blazor code that should be compiled to web assembly and run at the client. C# can gave errors about any unsupported code in this method.
Foo2 is a server code,
Both Foo1 and Foo2 can be use in the cshtml file as normal.
Is this possible?

**Comment by Joe4evr** [comment]
Why don't you simply create a Blazor component and use the `<component>` taghelper to render that component?

**Comment by VBAndCs** [comment]
@Joe4evr
This is why from my point of view:
1. The code behind model of Blazor is not simple as the Razor Pages one.
2. Why creating a component to execute simple functions that need little or none html code? Blazor was JS alternative. JS function can crate the DOM without any static HTML.
3. Dispersing the page logic over 4 files kills the benefits of Razor Pages.
4. If the pages contains too much Blazor methods, I can use a partial class for them, so, I have one cshtml file and two C# files.
4. I didn't go deep into Blazor, but I expect it can somehow access the DOM elements in the page . It will be easier if the code behind file can directly access the html elements defined in the cshtml files by using there names or IDs as object names that return the DOM types (as defined in the mshtml library).
If this happens or already happening, the interaction between the server side and client side in Razor page will be very simple.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This ask is not aligned well with the Blazor programming model and we don't plan to provide such option.
