### ISSUE TITLE
[Blazor] Dynamic page title

### ISSUE THREAD

**Issue by ddieruf** [aspnet/AspNetCore#17667]
### Is your feature request related to a problem? Please describe.
For my client side app, I am using server static rendering
`<app>@(await Html.RenderComponentAsync<App>(RenderMode.Static))</app>`

How would I set the page title as the user navigates through the prerendered site?

### Describe the solution you'd like
 A way to set `@title` on each blazer page.

### Additional context
The conversation in issue #9897 loses track of the fact that the title lives in `<head>` and you can't put script tags in components. So the described example only works for things in the `<body>` tag.

**Comment by peterblazejewicz** [comment]
#16018
Is more relevant, hasjust been closed recently via bot

**Comment by ddieruf** [comment]
The [proposed solution](https://github.com/aspnet/AspNetCore/issues/16018#issuecomment-490671409) in the issue was from version 0.9. Today's current version is 3.1.0-preview4. The practices within look a little dated. @peterblazejewicz are you suggesting that this is still the best way to handle metadata in the `head`?

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by ddieruf** [comment]
I ended up creating a PageTitle component

`@inject IJSRuntime JSRuntime

@code {
	[Parameter]
	public string Title {get;set;}

	protected override async Task OnAfterRenderAsync(bool firstRender) {
		await SetPageTitle("Steeltoe " + Title);
	}
	private async Task SetPageTitle(string title = "") {
		await JSRuntime.InvokeAsync<string>("setPageTitle", title);
    StateHasChanged();
	}
}`

And call it from each page
`<PageTitle Title="Home" />`
