### ISSUE TITLE
OnAfterRenderAsync still called twice on 3.0.0-preview9.19465.2

### ISSUE THREAD

**Issue by Oninaig** [aspnet/AspNetCore#17661]
### Describe the bug
Using server-side prerendering, if you have the following `OnAfterRenderAsync`:

```
protected override async Task OnAfterRenderAsync(bool firstRender)
{
	if (firstRender)
	{
		await MyTask();
		Console.WriteLine("FirstRender");
	}

	Console.WriteLine("OnAfterRenderAsync");
}
```

Then "OnAfterRenderAsync" is still written to the console _twice_ even though previously it was stated that starting in preview 9 `OnAfterRenderAsync` would _not_ be called during the prerendering lifecycle at all.

### To Reproduce

Create a new blazor project with server-side prerendering enabled.

Create a component that overrides `OnAfterRenderAsync`

That override will be called twice during rendering.

### Further technical details
- ASP.NET Core version : 3.0.0-preview9.19465.2
- IDE: VS2019 Version 16.3.8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. 
This should be fixed in the 3.0 RTM release. Please upgrade.

**Comment by Oninaig** [comment]
@mkArtakMSFT Apologies, but what I meant to say was that the my website _is_ using Microsoft.AspNetCore.App version 3.0 and I had a reference to Microsoft.AspNetCore.Blazor 3.0.0-preview9.19465.2

I removed that reference and just kept AspNetCore 3.0, the components are still calling `OnAfterRenderAsync` twice.

**Comment by javiercn** [comment]
@Oninaig could you upgrade to 3.1.0 RTM and see if it happens there, and in that case, provide a repro project that illustrates the problem?

**Comment by Oninaig** [comment]
@javiercn I appreciate the quick response but I believe that @mkArtakMSFT is correct in that by default, a fresh out-of-the-box blazor server-side project will not call `OnAfterRenderAsync` twice on a component. 

After doing more digging, it appears my actual issue is due to the fact that any `@onclick=` actions (on buttons, for example) _automatically_ call `ShouldRefresh` and since `ShouldRefresh` doesn't have any parameters, its difficult to tell whether or not the call came from a button press or from some other event.

Consider the following code:

In my .razor file:
```
<button class="btn btn-primary fas fa-sync" @onclick="RefreshMessages" disabled="@_refreshing"></button>

<GridComponent T="Events" Grid="@_grid"></GridComponent>


```

And in my code-behind:
```
protected override bool ShouldRender()
{
	return base.ShouldRender();
}

protected async Task RefreshMessages()
{
	if (_grid != null)
	{
		_refreshing = true;
		await _grid.UpdateGrid();
		_refreshing = false;
	}
}
```

If the call to `_grid.UpdateGrid();` has its own call to `StateHasChanged()` somewhere in the call stack for itself, it means that I wind up with 2 calls to `ShouldRender` on my parent component and therefore 2 calls to `OnAfterRenderAsync`. I guess what I am really trying to do is to override `ShouldRender` in such a way that I can return `false` if the call to `ShouldRender` came from a simple button press when I know that I will be calling `StateHasChanged` at some point later in the call stack. However, since the `onclick` method finishes completely before `ShouldRender` is called, I currently can't think of something off the top of my head that would allow me to "detect" that a button press is whats causing the current request to re-render.

**Comment by javiercn** [comment]
> If the call to `_grid.UpdateGrid();` has its own call to `StateHasChanged()` somewhere in the call stack for itself, it means that I wind up with 2 calls to `ShouldRender` on my parent component and therefore 2 calls to `OnAfterRenderAsync`. One call comes from the button press itself, and another from the child component's own call to `StateHasChanged`.

That's not true if you are using ComponentBase.

ComponentBase will make sure that only one render gets triggered when multiple calls to StateHasChanged without a render in between, so there will only be a single render and a single OnAfterRender call
