### ISSUE TITLE
 .NET Core 3.1 - Kestrel HTTP/2 performance issue with FDD on Ubuntu 18.04

### ISSUE THREAD

**Issue by DenSmoke** [aspnet/AspNetCore#17676]
### Describe the bug
Download speed is too low when HTTP/2 is used with FDD.
I'm not sure but I think this happened after `dotnet-sdk-3.1` was installed - revert of `TargetFramework` to `netcoreapp3.0` didn't help. 
SCD publish works well.

### To Reproduce
`dotnet publish -c Release -r ubuntu.18.04-x64 --self-contained=false`
```C#
webBuilder.UseKestrel((host, options) =>
{
    var port = host.Configuration.GetValue<int>("KestrelSettings:port");
    var filename = host.Configuration.GetValue<string>("KestrelSettings:certfilename");
    var password = host.Configuration.GetValue<string>("KestrelSettings:certpassword");
    options.Listen(IPAddress.Any, port, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
        listenOptions.UseHttps(filename, password);
    });
});
```
``` C#
[HttpGet]
public IActionResult DownloadZipFile(string fileName)
{
    var path = Path.Combine("/home/user/files", fileName);
    return PhysicalFile(path, MediaTypeNames.Application.Zip, fileName, true);
}
```
### Further technical details
- ASP.NET Core 3.1
- Azure Pipelines build with .NET Core 3.1 SDK
- dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.101 [/usr/share/dotnet/sdk]
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.                                                                  All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.                                                                  App]
  Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.                                                                  App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.                                                                  App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```

**Comment by DenSmoke** [comment]
Haha classic... 

Problem suddenly gone after I played with ExecStart value of systemd unit.
I changed it from calling an executable to /usr/bin/dotnet dll call and download speed is restored to normal value.
But when I returned old value speed didn't decrease. Also it affected running production version of API which wasn't even restarted.

I have no clue what's going on.

**Comment by anurse** [comment]
Can you provide a runnable sample that repros the issue? We can't think of any issue that would cause the **download speed** to differ in these cases. The start-up time *might* change, but as long as you were specifically measuring the stable-state download speed I can't think of what would be different.

**Comment by DenSmoke** [comment]
@anurse I couldn't reproduce this behavior again and now everything works good. Most likely it was some problem with Ubuntu, because it was affecting all apps using HTTP/2, so I am closing this
