### ISSUE TITLE
#9020 was closed by bot.

### ISSUE THREAD

**Issue by thisisthekap** [aspnet/AspNetCore#17675]
The issue „Host grpc service in iis or as an app service? #9020“ was closed by bot. Imho this issue should be reopened because .NET Core features should be supported on Azure App Service instances. @davidfowl already mentioned, that work is in progress.

**Comment by mv10-work** [comment]
Auto-close is incredibly frustrating. I've stopped reporting bugs through VS because of it. I just saw another issue closed that I was watching that was opened barely two weeks ago. Ridiculous. I sure hope that script is mis-configured.

**Comment by thisisthekap** [comment]
Was reopened. Closing this one.
