### ISSUE TITLE
[Blazor] ReadJwtToken produces an error after preview4 and netstandard2.1

### ISSUE THREAD

**Issue by smartprogrammer93** [aspnet/AspNetCore#17683]
### Describe the bug
After upgrading to the latest preview of blazor (3.1 preview 4) and netstandard2.1 JwtSecurityTokenHandler.ReadJwtToken always produces an error 

### To Reproduce
Create a blazor project.

write the following:
`
var handler =  new JwtSecurityTokenHandler();
IdentityModelEventSource.ShowPII = true;
Jwt = handler.ReadJwtToken(token);
`
run code providing it with an HS256 JWT and get exception:

WASM: ﻿Fail: IDX12723: Unable to decode the payload 'eyJqdGkiOiI3YmMxMzlmMy05N2Q4LTRjODQtOGJlYS05ZjFhZTU0ZTNhZWUiLCJzdWIiOiIxIiwiYXBwaWNhdGlvbi9wZXJtaXNzaW9uIjpbIlVzZXIuTGlzdCIsIlVzZXIuUmVhZCIsIlVzZXIuUmVhZE93bmVkIiwiVXNlci5BZGQiLCJVc2VyLkVkaXQiLCJVc2VyLkVkaXQuUm9sZSIsIlVzZXIuRWRpdC5QYXNzd29yZCIsIlVzZXIuRWRpdE93bmVkIiwiVXNlci5FZGl0T3duZWQuUGFzc3dvcmQiLCJVc2VyLkRlbGV0ZSIsIlJvbGUuTGlzdCIsIlJvbGUuTGlzdE93bmVkIiwiUm9sZS5SZWFkIiwiUm9sZS5BZGQiLCJSb2xlLkVkaXQiLCJSb2xlLkRlbGV0ZSIsIlBlcm1pc3Npb24uTGlzdCIsIlBlcm1pc3Npb24uUmVhZCIsIlBlcm1pc3Npb24uQWRkIiwiUGVybWlzc2lvbi5FZGl0IiwiUGVybWlzc2lvbi5EZWxldGUiLCJGaWxlLkxpc3QiLCJGaWxlLlJlYWQiLCJGaWxlLkFkZCIsIkZpbGUuRWRpdCIsIkZpbGUuRGVsZXRlIiwiVmFsZXQuTGlzdCIsIlZhbGV0LlJlYWQiLCJWYWxldC5BZGQiLCJWYWxldC5FZGl0IiwiVmFsZXQuRGVsZXRlIiwiQ2xpZW50UHJvZmlsZS5MaXN0IiwiQ2xpZW50UHJvZmlsZS5SZWFkIiwiQ2xpZW50UHJvZmlsZS5BZGQiLCJDbGllbnRQcm9maWxlLkVkaXQiLCJDbGllbnRQcm9maWxlLkRlbGV0ZSIsIlZlaGljbGUuTGlzdCIsIlZlaGljbGUuUmVhZCIsIlZlaGljbGUuQWRkIiwiVmVoaWNsZS5FZGl0IiwiVmVoaWNsZS5EZWxldGUiLCJWZWhpY2xlSW1hZ2UuTGlzdCIsIlZlaGljbGVJbWFnZS5SZWFkIiwiVmVoaWNsZUltYWdlLkFkZCIsIlZlaGljbGVJbWFnZS5FZGl0IiwiVmVoaWNsZUltYWdlLkRlbGV0ZSIsIlNlcnZpY2VEZWZpbml0aW9uLkxpc3QiLCJTZXJ2aWNlRGVmaW5pdGlvbi5SZWFkIiwiU2VydmljZURlZmluaXRpb24uQWRkIiwiU2VydmljZURlZmluaXRpb24uRWRpdCIsIlNlcnZpY2VEZWZpbml0aW9uLkRlbGV0ZSIsIlZlaGljbGVTZXJ2aWNlQ29udHJhY3QuTGlzdCIsIlZlaGljbGVTZXJ2aWNlQ29udHJhY3QuTGlzdE93bmVkIiwiVmVoaWNsZVNlcnZpY2VDb250cmFjdC5SZWFkIiwiVmVoaWNsZVNlcnZpY2VDb250cmFjdC5SZWFkT3duZWQiLCJWZWhpY2xlU2VydmljZUNvbnRyYWN0LkFkZCIsIlZlaGljbGVTZXJ2aWNlQ29udHJhY3QuRWRpdCIsIlZlaGljbGVTZXJ2aWNlQ29udHJhY3QuRGVsZXRlIiwiQ29udHJhY3RSZW5ld2FsLkxpc3QiLCJDb250cmFjdFJlbmV3YWwuTGlzdE93bmVkIiwiQ29udHJhY3RSZW5ld2FsLlJlYWQiLCJDb250cmFjdFJlbmV3YWwuUmVhZE93bmVkIiwiQ29udHJhY3RSZW5ld2FsLkFkZCIsIkNvbnRyYWN0UmVuZXdhbC5FZGl0IiwiQ29udHJhY3RSZW5ld2FsLkRlbGV0ZSJdLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdXBlclVzZXIiLCJuYmYiOjE1NzU3ODQ1MDQsImV4cCI6MjIwNjkzNjUwNH0' as Base64Url encoded string. jwtEncodedString: ''.   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.DecodeJws (System.String[] tokenParts) <0x2b951f0 + 0x000a4> in <5c7f75fd521f4527ac36c46162cf3edc>:0 blazor.webassembly.js:1:35110

### Further technical details

3.1.0-preview4.19579.2

.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio 2019 Version 16.5.0 Preview 1.0

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#18094
