### ISSUE TITLE
Building resources file needs netfx sdk?

### ISSUE THREAD

**Issue by liuliang-wt** [aspnet/AspNetCore#17688]
When I build a .netcore app with resource files in VS on windows, it requires me to install netfxsdk 4.7.2 to use al.exe command. It is weird that .netcore depands on netfxsdk.

And when I try to publish a .netcore app with resource files on my mac, it failed with this error:

/usr/local/share/dotnet/sdk/3.0.100/Microsoft.Common.CurrentVersion.targets(3056,5): error MSB3552: Resource file "**/*.resx" cannot be found.

**Comment by Pilchie** [comment]
This issue was moved to dotnet/sdk#4032
