### ISSUE TITLE
Build error with code analyzer after upgrading to .net core 3.1 preview4

### ISSUE THREAD

**Issue by SantosRay** [aspnet/AspNetCore#17682]
After upgrading to .net core 3.1 I am having this same issue:

https://stackoverflow.com/questions/59180175/build-error-with-code-analyzer-after-upgrading-to-net-core-3-1-preview4

**Comment by pranavkm** [comment]
Thanks for the issue report. Please see https://github.com/aspnet/AspNetCore/issues/17644#issuecomment-563355603 for workarounds for 3.1-preview4. We'll use the other issue to track fixing this in the next release.

**Comment by SantosRay** [comment]
Thanks for the link ( https://github.com/aspnet/AspNetCore/issues/17644#issuecomment-563355603) workaround but when I enable linking I get the following error: 
Error ILLink failed with exited code 1. Settings.Client C:\Users\*\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets	204
