### ISSUE TITLE
ASP.Net Core with Bootstrap 4.4

### ISSUE THREAD

**Issue by peter1965p** [aspnet/AspNetCore#17689]
The before effect is already cool. Do I have to rewrite the whole layout now? How do I set up a normal bootstrap css on my site? As an example so https://colorlib.com/wp/template/loans2go/ but not as Wordpress ... but for ASP.net Core. I think that's enough for now, later I need a contact form.

Kind regards, Peter

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
