### ISSUE TITLE
Empty claims from JwtBearer middleware

### ISSUE THREAD

**Issue by flopes89** [aspnet/AspNetCore#17685]
# Describe the bug
I want to validate a JWT (and the roles in it).

### To Reproduce

**Startup**
```c#
public void ConfigureServices(IServiceCollection services)
{
	services.AddSingleton(Configuration);

	services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
		.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
		{
			options.MetadataAddress = "https://example.com/.well-known/openid-configuration";
		});

	services.AddScoped<IAuthorizationHandler, MyRoleHandler>();
}
```

**MyRoleHandler**
```c#
public class MyRoleHandler : IAuthorizationHandler
{
	public Task HandleAsync(AuthorizationHandlerContext context)
	{
		var claims = context.User.Claims;

		return Task.CompletedTask;
	}
}
```

**https://example.com/.well-known/openid-configuration**
```json
{
    "issuer": "https://example.com",
    "jwks_uri": "https://example.com/.well-known/openid-configuration/jwks",
    "authorization_endpoint": "https://example.com/connect/authorize",
    "token_endpoint": "https://example.com/connect/token",
    "end_session_endpoint": "https://example.com/connect/endsession",
    "check_session_iframe": "https://example.com/connect/checksession",
    "device_authorization_endpoint": "https://example.com/connect/deviceauthorization",
    "frontchannel_logout_supported": true,
    "frontchannel_logout_session_supported": true,
    "backchannel_logout_supported": true,
    "backchannel_logout_session_supported": true,
    "response_types_supported": ["code", "token", "id_token", "id_token token", "code id_token", "code token", "code id_token token"],
    "subject_types_supported": ["public"],
    "id_token_signing_alg_values_supported": ["RS256"],
    "code_challenge_methods_supported": ["plain", "S256"],
    "upgrade_endpoint": "https://example.com/connect/upgrade",
    "end_session_accesstoken_endpoint": "https://example.com/connect/endsession/accesstoken",
    "active_session_endpoint": "https://example.com/connect/activesession"
}
```

`claims` is empty. What am I doing wrong here? I was under the impression the `JwtBearer` middleware will configure itself when given the openid-configuration?

There are no errors or exceptions anywhere to be seen. Maybe it's because I'm behind a company proxy and `example.com` is outside our network? But even then I would expect some kind of error ... ?

### Further technical details
- ASP.NET Core 3.1
- Visual Studio 2019 on Windows 10 x64

**Comment by blowdart** [comment]
Does the token issued by example.com  have claims? I'm confused because example.com is supposed to be for documentation only, and I was unaware that it has an example jwt issuer. https://example.com/.well-known/openid-configuration doesn't return a valid json file for me.

**Comment by flopes89** [comment]
Yeah it had claims, but it's not actually from example.com - I substituted the real URL for privacy reasons.

**Comment by Tratcher** [comment]
A) Check the application logs to make sure JwtBearer auth was invoked.
B) Check context.User.IsAuthenticated == true and context.User.AuthenticationType == "Bearer".
C) How are you triggering Authorization? With an attribute?

**Comment by flopes89** [comment]
Well that's probably part of the problem: I don't see any logging from "inside" ASP.NET.

```
public class Program
{
	public static void Main(string[] args)
	{
		CreateWebHostBuilder(args).Build().Run();
	}

	private static IWebHostBuilder CreateWebHostBuilder(string[] args)
	{
		return WebHost.CreateDefaultBuilder(args)
			.ConfigureLogging((context, logging) =>
				{
					logging.AddConsole();
				}
			)
			.UseUrls(urls: "http://0.0.0.0:5000")
			.UseStartup<Startup>();
	}
}
```

But all I get from logging is:

```
Hosting environment: Development
Content root path: D:\Development\mysln\myprj
Now listening on: http://localhost:10459/
Application started. Press Ctrl+C to shut down.
info: myns.HostedServices.FileCacheHostedService[0]
      Reading the filesystem... done
dbug: myns.Policies.MyRoleHandler[0]
      Handling Auth...
```

`context.User.IsAuthenticated` and `...AuthenticationType` doesn't exist when I look into the debugger:

![2019-12-09 07-53-56](https://user-images.githubusercontent.com/1453127/70414075-488f8c00-1a59-11ea-9622-f958c84e031e.png)

**Comment by blowdart** [comment]
You need to have an Authorize attribute on your endpoint, or call the authorization service before it will kick in.

**Comment by flopes89** [comment]
I had the `[Authorize]` attribute in place. However, I figured out now that the error was in fact that the `TokenValidationParameters` must be set correctly. I don't exactly know why, but as soon as I add them in any capacity, the claims are correctly decoded.

So now I added them as follows:

```c#
services
	.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
	.AddJwtBearer(opts =>
	{
		opts.Authority = Env.Get("AUTHORITY_BASE_URL");

		opts.TokenValidationParameters = new TokenValidationParameters
		{
			ValidateLifetime = true,
			ValidateIssuerSigningKey = true,
			ValidateIssuer = true,
			ValidIssuer = Env.Get("ALLOWED_ISSUER"),
			ValidateAudience = true,
			ValidAudience = Env.Get("ALLOWED_AUDIENCE"),
			ClockSkew = TimeSpan.FromSeconds(Env.GetDouble("CLOCK_SKEW")),
			RoleClaimType = "authorities"
		};
	});
```

And now, in my `MyRoleHandler`, the claims are correctly decoded an I can check them.
