### ISSUE TITLE
[SPA] allow `dotnet publish` modify output folder for frontend project

### ISSUE THREAD

**Issue by jaqra** [aspnet/AspNetCore#17686]
When i publish my spa (react) project, file structure is:

* publish:
  * ClientApp
    * **build <======== THIS IS UGLY**
      * index.html
      * static
        * ...
  * *.dll

It should be:

* publish:
  * ClientApp
    * index.html
    * static
      * ...
  * *.dll

csproj file:

```xml
<ItemGroup>
  <DistFiles Include="$(SpaRoot)build\**; $(SpaRoot)build-ssr\**" />
  <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
    <RelativePath>%(DistFiles.Identity)</RelativePath>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
  </ResolvedFileToPublish>
</ItemGroup>
```

I should have to remove `build` folder path in this line or anywhere

```xml
<RelativePath>%(DistFiles.Identity)</RelativePath>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to change in the near future. Glad that you've got a workaround.
