### ISSUE TITLE
Global error gets request parameters

### ISSUE THREAD

**Issue by JHeLiu** [aspnet/AspNetCore#17697]
I want to implement something like this in.net CORE IExceptionFilter, the parameter fetch under the IActionFilter, after the implementation of the IActionFilter you can get the ActionArguments in the ActionExecutingContext and I can walk through it and get the request parameters, but now I want to get the parameters under global error capture, and I know it's a similar fetch under the.net framework,But how to get it under.NET CORE, because I'm reluctant to get it using httpcontext.request-body.It looks like it can only be read once. Is there a better way?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
