### ISSUE TITLE
Bundling and minification tooling for Blazor

### ISSUE THREAD

**Issue by chrissainty** [aspnet/AspNetCore#17699]
### Is your feature request related to a problem? Please describe.
With the recent removal of auto adding static assets in Blazor WebAsssembly, there has been a lot of discussion in the community about whether it is a good thing or not. But I think the real problem is being missed, bundling and minification.

Right now I believe most Blazor apps are just adding static file references from 3rd party libraries without considering this. Having lots of static file references isn't good for page performance and SEO can take a hit from this as well.

### Describe the solution you'd like
I would like to be able to configure how static assets are added to my application and in what order along with the ability to enable bundling and minification.

### Additional context
I understand that there are plenty of solutions from the JS world available such as WebPack. But I'm not sure this is the route people are looking for, mainly because JS is the world they are trying to move away from by choosing Blazor.

**Comment by SteveSandersonMS** [comment]
Totally agreed. We have an item on the backlog tracking this: #5459

It's likely that anything we do in this area would be ASP.NET-wide, not specific to Blazor. We don't yet know if it's realistic to build a new thing here, or whether anything we do would have to be build around WebPack somehow.

**Comment by chrissainty** [comment]
@SteveSandersonMS Thanks Steve, my apologies I missed that issue.
