### ISSUE TITLE
VSCommunity Version 16.3.10 Does Not Update CSHTML File

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17709]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/848024/vscommunity-version-16310-does-not-update-cshtml-f.html)._

---
[regression] [worked-in:16.3.10]
Hello, I am creating a .NET Core MVC in the latest version 3.0.0. I have a problem making changes to the CSHTML file and refreshing the page, my changes are not reflected in the browser. I have to restart the project to see my changes. Before updating everything worked fine. Visual Studio Community 2019 Version 16.3.10 VSCommunity Version 16.3.10

---
#### Visual Studio Feedback System on 12/8/2019, 10:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
With .NET Core 3.0 release the Runtime Compilation is not enabled by default any more. This was a breaking change announced at https://github.com/aspnet/Announcements/issues/343 .
The documentation here will help you enable Runtime Compilation for you project: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#runtime-compilation
