### ISSUE TITLE
Unnecessary yield in EphemeralXmlRepository

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/AspNetCore#17703]
Is there any reason `GetAllElementsCore` has yield return?
https://github.com/aspnet/AspNetCore/blob/416d8cd1ea098eb643b4258247af3448f5545c32/src/DataProtection/DataProtection/src/Repositories/EphemeralXmlRepository.cs#L26-L42

Could be replaced with this code?

```csharp
public virtual IReadOnlyCollection<XElement> GetAllElements()
{
    // force complete enumeration under lock for thread safety
    lock (_storedElements)
    {
        return _storedElements.Select(element => new XElement(element)).ToList().AsReadOnly();
    }
}
```

**Comment by blowdart** [comment]
Given that ephemeral is the last fall back position and shouldn't be used in production, and folks use it as a starting point to write their own stores I don't see why changing it gives any real gains.

**Comment by Kahbazi** [comment]
@blowdart fair enought. I didn't know the actual usage of `EphemeralXmlRepository`.

**Comment by blowdart** [comment]
It's used in two places, tests, and if you haven't configured any repository and we can't figure out what we should do. 

Also in all repositories GetAllElements is called very infrequently (once a day by default), so much so that optimising it over readability isn't worth it.
