### ISSUE TITLE
Shared resources (resx) does not work in .net core 3.1 and VS 16.4

### ISSUE THREAD

**Issue by Weboholics** [aspnet/AspNetCore#17701]
### Describe the bug
Shared resources has stopped working since .net core 3.1 / vs.16.4.
Works with vs 16.3.4 and .net core 3.0

### To Reproduce
examplecode: https://github.com/Weboholics/ResourceTest

Run this code in vs.16.4  and notice that the shared resources does not work. View resources does work. This is on the /home/index page.
Changing to 3.0 under vs 16.4 does not work either.

If you change visual studio to 16.3.4 and runtime to 3.0 it will work.

- ASP.NET Core version: 3.1
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: vs 16.4.0

**Comment by Pilchie** [comment]
@livarcocc Seems related to the MSBuild issue with resource paths?  Should we move this to `dotnet/sdk`?

**Comment by livarcocc** [comment]
Yes. Feel free to move it. I will ask Ben to take a look at it.

**Comment by Pilchie** [comment]
This issue was moved to dotnet/sdk#4033
