### ISSUE TITLE
EditForm in Generic component

### ISSUE THREAD

**Issue by JulienM28** [aspnet/AspNetCore#17715]
I made a generic component lie this:

````csharp

@typeparam T

... removed for clarity

    <EditForm Model="Entity" OnValidSubmit="Submit">
        <div class="input-group">
            <DataAnnotationsValidator />

            @foreach (PropertyInfo pi in typeof(T).GetProperties())
            {
                <InputText @bind-Value="pi.GetValue(Entity).ToString()" />
            }
        </div>

        <button class="btn btn-default btn-ok align-right">Valider</button>
    </EditForm>
</div>
````
But it's not working and I can't find a way for this:

````csharp
    <InputText @bind-Value="????????????????" />
````
Is it possible to do ? and how ?

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we currently support out of the box. You can try to ask this question in [StackOverflow](https://stackoverflow.com) and hopefully the community will point to some existing solutions.

**Comment by mkArtakMSFT** [comment]
FYI: this may also be useful: https://github.com/aspnet/aspnetcore/issues/16627
