### ISSUE TITLE
Blazor default project runs, But errors in .razor files in IDE

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17725]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/841472/blazor-default-project-runs-but-errors-in-razor-fi.html)._

---
When I Create **new Blazor app** (Either server or client models), the default solution **runs perfectly.** But when I open .razor files, there are errors both in **error lists and file (red lines)**
Ex: 
`<RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />`
This gives **The type or namespace name 'MainLayout' could not be found (are you missing a using directive or an assembly reference?)**

In MainLayout.razor

```
<div class="sidebar">
    <NavMenu />

</div>
```

gives **Found markup element with unexpected name 'NavMenu'. If this is intended to be a component, add a @using directive for its namespace**

I tried rebooting, Reinstalling .net sdk (Including previews) no luck. Intelli sense is not sugesing these default codes. It sugesses things like **generated_NaveMenu** which doesn't work

---
#### Edward Kagan on 12/3/2019, 09:40 PM: 

<p>I have the same exact issue.</p>

#### hlrathnayaka on 12/3/2019, 09:44 PM: 

<p>There is a update comming vs 16.4. May be that fixes the issue. Very fresh vs installation doesn't have this issue</p>

#### Visual Studio Feedback System on 12/3/2019, 11:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### hlrathnayaka solved on 12/4/2019, 07:53 PM, 0 votes: 

<p>I confirm that this error solves when you update to visual studio version 16.4</p><p>I have downloaded .net core 3.1 sdk externally. Not via visual studio installer. It caused the error.</p>

#### Edward Kagan solved on 12/4/2019, 10:43 PM, 0 votes: 

<p>I installed 16.4 and I am getting this problem, so it's gotta be something else.</p>

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by SoulSeekkor** [comment]
Have the exact same problem here, using VS 16.4.1 with .net core 3.1 (installed by VS).  I also deleted the project and re-created it adding an authorization type of windows to it, and now it displays this error on the <LoginDisplay /> element instead of <NavMenu />.

**Comment by mkArtakMSFT** [comment]
@SoulSeekkor did you get that the app working without auth?
