### ISSUE TITLE
The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.

### ISSUE THREAD

**Issue by Varorbc** [aspnet/AspNetCore#17727]
### Describe the bug

HTTP Error 500.31 - ANCM Failed to Find Native Dependencies

Common solutions to this issue:
The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.

Specific error detected by ANCM:
It was not possible to find any compatible framework version The framework 'Microsoft.NETCore.App', version '3.1.1-servicing.19572.8' was not found. 

The following frameworks were found: 
2.2.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
3.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
3.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
 The specified framework can be found at: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.1-servicing.19572.8&arch=x64&rid=win10-x64

Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028526

**Comment by Varorbc** [comment]
@pranavkm @JunTaoLuo can you help me look at this issue? This prevented me from working properly

**Comment by JunTaoLuo** [comment]
@Varorbc where did you install the ASP.NET Core shared framework from? It looks like you are installing a nightly aspnetcore shared framework without installing a nightly netcore shared framework.

I have double checked our released 3.1.0 release and there are no issues with the framework dependencies.

**Comment by Varorbc** [comment]
@JunTaoLuo By updating vs to 16.4
![image](https://user-images.githubusercontent.com/5714438/71049293-e6cbd200-217c-11ea-872b-bc2283536cb7.png)

**Comment by JunTaoLuo** [comment]
I suspect that an incorrect version of ASP.NET Core 3.1 was inserted into VS. I'll need to check our releases.

cc @leecow @mmitche

**Comment by Varorbc** [comment]
@JunTaoLuo finally I resolved the issue by reinstalling
