### ISSUE TITLE
Routing template: support catch-all not the last part

### ISSUE THREAD

**Issue by iron9light** [aspnet/AspNetCore#17726]
Original issue: #11170 

I wanna routing template like:
```
"{controller}/{**path}/{action}/{id?}"
```
or at least
```
"{controller}/{**path}/myaction1"
```
I just found the routing matching is all depends on this internal class:
https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/Patterns/RoutePatternMatcher.cs

It's really useful if this feature can be implemented.
In my project, we use `{controller}/{**path}/{action}` for all our API.
The path is kinda resource id and it's hierarchy.
In the previous version, the path has only one level. So routing looks like this:
`{controller}/{path}/{action}`
Then we wanna support 2 level path:
`{controller}/{path1}/{path2?}/{action}`
Now we are trying to support multi-level path, that's why we wanna:
`{controller}/{**path}/{action}`

How about we extends the routing template rule:

1. At most one catch-all segment.
2. All segment after catch-all segment must be required.

This should be implementable.
And I think we just need to modify RoutePatternMatcher class.

Or is it possible to make RoutePatternMatcher user controllerable?
e.g. Add a Type parameter for HttpGetAttribute
```
[HttpGet("{controller}/{**path}/{action}", typeof(MyRoutePatternMatcher)]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do in the near future.
