### ISSUE TITLE
System.Text.Json.JsonSerializer.Deserialize not working with class ProblemDetails

### ISSUE THREAD

**Issue by Kevweir** [aspnet/AspNetCore#17728]
Please refer to this CLOSED issue
https://github.com/aspnet/AspNetCore/issues/17250

Version of System.Text.Json I'm using

```
#region Assembly System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
// C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Text.Json.dll
#endregion

```
There still appears t be an issue with **System.Text.Json.JsonSerializer.Deserialize** deserializing what appears to be valid JSON. All the values for problemDetails are NULL when the code executes. Newtonsoft **JsonConvert.DeserializeObject** on the other hand works as expected.

`ProblemDetails problemDetails = System.Text.Json.JsonSerializer.Deserialize<ProblemDetails>(ex.Response);
`
ex.Response contains the following JSON:

`"{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.4\",\"title\":\"Not Found\",\"status\":404,\"traceId\":\"|2b127cb8-48a6a0aa0a2beaf9.\"}" `

**Comment by pranavkm** [comment]
@Kevweir this seems to work for me: https://github.com/pranavkm/repro/blob/17728/Program.cs#L11-L15.

Can you share a minimal app that reproduces the issue you're seeing? I suspect you're attempting to use the `ProblemDetails` type from MVC 2.x with System.Text.Json. If that's the case you'll need to copy these converters to your app and configure the serializer to use it:

* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/ProblemDetailsJsonConverter.cs
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/ValidationProblemDetailsJsonConverter.cs

**Comment by Kevweir** [comment]
Sorry I wasted your time.  I'm using NSwag to generate C# clients based on a OpenAPI 3.0 document and it code generates the ProblemDetails and ValidationProblemDetails you see below. I happen to be using those classes in my .NET Core 3,1 console application.  

There are obviously two problems here.  The case sensitivity issue of the properties and the fact your parser wouldn't recognize Newtonsoft attributes nor would I expect it to.   I think I need a mental break as something like this shouldn't have gotten past me. :)

Thanks for your time though as it took your sample to trigger what I should have tried during my troubleshooting.


```
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.28.0 (Newtonsoft.Json v12.0.0.0)")]
public partial class ProblemDetails
{
    [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Type { get; set; }

    [Newtonsoft.Json.JsonProperty("title", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Title { get; set; }

    [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public int? Status { get; set; }

    [Newtonsoft.Json.JsonProperty("detail", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Detail { get; set; }

    [Newtonsoft.Json.JsonProperty("instance", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Instance { get; set; }

    [Newtonsoft.Json.JsonProperty("extensions", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.IDictionary<string, object> Extensions { get; set; }
}

```

```
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.28.0 (Newtonsoft.Json v12.0.0.0)")]
public partial class ValidationProblemDetails : ProblemDetails
{
    [Newtonsoft.Json.JsonProperty("errors", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.IDictionary<string, System.Collections.Generic.ICollection<string>> Errors { get; set; }
}
```

**Comment by Kevweir** [comment]
I come from a Visual Basic.NET background and what a lovely language that is.  Its very expressive and not crptic like this C# and JSON stuff.  lol .  Case senstiveity and squirely brackets, and passing functions and methods as parameters just dont make sense to me.   The later of course being somewhat powerful but they're everywhere now in C#.  And I mean everywhere.
