### ISSUE TITLE
about name of area attribute case sensitive

### ISSUE THREAD

**Issue by hryh** [aspnet/AspNetCore#17731]
### Is your feature request related to a problem? Please describe.
I am using asp.net core 3.1，create a Area called Admin，I created a homecontroller with the area attribute name set to admin，when i debug with windows，it's ok，but i publish to linux,it's bad。
I know that Linux is case sensitive，but i am browser access case insensitive.

### Describe the solution you'd like
Whether area name should be case insensitive.

**Comment by javiercn** [comment]
@hryh thanks for contacting us.

What you are likely experiencing is an issue when trying to find the view. I would recommend you make the casing of the Area be the same as the one in the folder. Another possibility is that we are lowercasing all the file paths and that might require you to use lowercase letters for area names.

@pranavkm do you have any thoughts here?

**Comment by pranavkm** [comment]
As @javiercn noted, case sensitivity typically comes from the OS's file lookup. With runtime compilation, MVC relies on the operating system to perform view lookups. A mismatch in case would result in failure to lookup in a case sensitive OS like Linux. Preserving case consistency across controllers, actions and view file names would be the way to go.
