### ISSUE TITLE
Blazor preview 4 linker issue unhelpful error.

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#17738]
### Describe the bug
I have a blazor (wasm) preview 4 project.
I had not realised that one of the dependencies I was including was still compiled against preview 3, here is the offending package if you need to replicate:

```
    <PackageReference Include="NetPack.BrowserReload.BlazorClient" Version="0.3.0-alpha0144" Condition="$(DefineConstants.Contains(DEBUG))" />

```

When I build the application, the linker gives me an error on a particular assembly: `'Microsoft.AspNetCore.Http.Abstractions.dll'` here is the build output:

> Microsoft Windows [Version 10.0.18362.476]
(c) 2019 Microsoft Corporation. All rights reserved.

> C:\Users\DarrellTunnell\source\repos\HubCore\src\Hub.Client>dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

>   Restore completed in 33.99 ms for C:\Users\DarrellTunnell\source\repos\HubCore\src\Hub.Client\Hub.Client.csproj.
  Restore completed in 33.98 ms for C:\Users\DarrellTunnell\source\repos\HubCore\src\Hub.Shared\Hub.Shared.csproj.
  Hub.Shared -> C:\Users\DarrellTunnell\source\repos\HubCore\src\Hub.Shared\bin\Debug\netstandard2.1\Hub.Shared.dll
>  WebCompiler: Begin compiling compilerconfig.json
  WebCompiler: Done compiling compilerconfig.json
  Hub.Client -> C:\Users\DarrellTunnell\source\repos\HubCore\src\Hub.Client\bin\Debug\netstandard2.1\Hub.Client.dll
  Fatal error in Mono CIL Linker
C:\Users\DarrellTunnell\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets(204,5): error : Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task Microsoft.AspNetCore.Http.Authentication.AuthenticationManager::AuthenticateAsync(Microsoft.AspNetCore.Http.Features.Authentication.AuthenticateContext)' in assembly: 'Microsoft.AspNetCore.Http.Abstractions.dll' [C:\Users\DarrellTunnell\source\repos\HubCore\src\Hub.Client\Hub.Client.csproj]
   ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.AspNetCore.Http.Features.Authentication.AuthenticateContext
     at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
C:\Users\DarrellTunnell\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets(204,5): error : ILLink failed with exited code -532462766. [C:\Users\DarrellTunnell\source\repos\HubCore\src\Hub.Client\Hub.Client.csproj]

> Build FAILED.

> C:\Users\DarrellTunnell\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets(204,5): error : Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task Microsoft.AspNetCore.Http.Authentication.AuthenticationManager::AuthenticateAsync(Microsoft.AspNetCore.Http.Features.Authentication.AuthenticateContext)' in assembly: 'Microsoft.AspNetCore.Http.Abstractions.dll' [C:\Users\DarrellTunnell\source\repos\HubCore\src\Hub.Client\Hub.Client.csproj]
C:\Users\DarrellTunnell\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets(204,5): error : ILLink failed with exited code -532462766. [C:\Users\DarrellTunnell\source\repos\HubCore\src\Hub.Client\Hub.Client.csproj]

There is nothing in that error that really helped me track down the issue of the particular offending package. All I could tell was that the problem seems to be with 'Microsoft.AspNetCore.Http.Abstractions.dll' so the first thing I attempted was to add 'Microsoft.AspNetCore.Http.Abstractions.dll' to the linker file to ignore this assembly when linking:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  This file specifies which parts of the BCL or Blazor packages must not be
  stripped by the IL Linker even if they aren't referenced by user code.
  See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.0#control-linking-with-a-configuration-file
-->
<linker>
  <assembly fullname="mscorlib">
    <!--
      Preserve the methods in WasmRuntime because its methods are called by 
      JavaScript client-side code to implement timers.
      Fixes: https://github.com/aspnet/Blazor/issues/239
    -->
    <type fullname="System.Threading.WasmRuntime" />
  </assembly>
  <assembly fullname="System.Core">
    <!--
      System.Linq.Expressions* is required by Json.NET and any 
      expression.Compile caller. The assembly isn't stripped.
    -->
    <type fullname="System.Linq.Expressions*" />   
  </assembly>

  <!-- The problematic assembly  -->
  <assembly fullname="Microsoft.AspNetCore.Http.Abstractions" />  

  <!--
    In this example, the app's entry point assembly is listed. The assembly
    isn't stripped by the IL Linker.
  -->
  <assembly fullname="Hub.Client"/>
</linker>

```

But this does nothing. The linker config still processes the assembly and errors, even though I've asked it to be ignored. This is counter intuitive (unless you know the internals of how the linker works). The same error continues to occur. I finally got to the bottom of this, by removing one package reference on at a time to see if it made any difference. Low and behold when I remove the aformentioned one the linker no longer complained. 

### To Reproduce
1. Create a new blazor wasm project (preview 4)
2. Add a package reference for a package still compiled against preview 3 like this one:
```
    <PackageReference Include="NetPack.BrowserReload.BlazorClient" Version="0.3.0-alpha0144" Condition="$(DefineConstants.Contains(DEBUG))" />
```
3. Build (linker should be enabled).

```

### Further technical details
- 3.1.0
- Include the output of `dotnet --info`
> .NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

> To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Version 16.5.0 Preview 1.0

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#18118
