### ISSUE TITLE
Visual Studio 2019 .Net Core 3.1 Kestrel does not map default ControllerRoute

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17745]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/848341/visual-studio-2019-net-core-31-kestrel-does-not-ma.html)._

---
<p>I created a Core 3.1 MVC Web Application with VS2019. I changed nothing and tried different launcher options. IIS Express worked, Docker worked and the third option named like my project does not find the home controller. </p><p>When I start with IIS Express or Docker the start route looks like this:</p><p><a href="https://localhost:51346/">https://localhost:51346/</a></p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/108722-iis-express.jpg"> Image:108722-iis-express.jpg</a></p><p>When I start with, I think it is called Kestrel, please correct me if I´m wrong:</p><p><a href="https://localhost:5001/index.html">https://localhost:5001/index.html</a></p> <p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/108723-kestrel.jpg"> Image:108723-kestrel.jpg</a></p><p>the Startup.cs looks like this:</p><pre>app. UseEndpoints(endpoints =&gt;
{
   endpoints. MapControllerRoute(
     name: &quot;default&quot;,
     pattern: &quot;{controller=Home}/{action=Index}/{id?}&quot;);
   endpoints. MapRazorPages();
});

</pre><p>I search for a day now and even when I follow all the tutorials or create a new project it does not route to the home if not typed by hand. I tried different controller names, it`s the same, IIS and Docker work but not Kestrel.</p> <p>I reinstalled Visual Studio because I know that it worked a week before, where I tried it the first time.</p> <p>For me it looks like a bug, i´m not sure where to look elsewhere.</p> <p>

---
#### Visual Studio Feedback System on 12/9/2019, 03:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@Tratcher FYI

**Comment by Tratcher** [comment]
In the kestrel scenario why are you trying to navigate to `/index.html`? You didn't do that in your IIS Express example.

**Comment by truoss** [comment]
it does that by itself. I pressed the green arrow and this is what it shows

**Comment by Tratcher** [comment]
That's weird. What do you get if you navigate to `https://localhost:5001`?
Can you share your `launchsettings.json` file? Or the whole zipped up project?

**Comment by truoss** [comment]
This is the project. It is default except for a TestController.
[WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3951288/WebApplication1.zip)

**Comment by Tratcher** [comment]
That project works just fine for me with both IIS and Kestrel.
VS Enterprise 2019 16.4.0.
With Kestrel it launches to `https://localhost:5001/`. Your new test controller also works at `https://localhost:5001/test`.

`https://localhost:5001/index.html` as shown in your screen shots is not a valid url and I'm not sure how you ended up there. Have you recently used one of the SPA templates? It's possible you have a cached redirect from `https://localhost:5001/` to `https://localhost:5001/index.html`. Clearing your cache should clear that.

**Comment by truoss** [comment]
do you mean browser cache?

**Comment by truoss** [comment]
I made a 18 sec screen capture.
[2019-12-11 17-47-53.zip](https://github.com/aspnet/AspNetCore/files/3951542/2019-12-11.17-47-53.zip)

**Comment by Tratcher** [comment]
Yes, that looks like a browser redirect cache. Look at the details in the network tab when you do that.

**Comment by truoss** [comment]
I see it is working when I check "disable cache". But how do I fix that cached route? Where would the cache be? Because it affects every other project I want to use kestrel too.

And also thanks for your help ;)

**Comment by truoss** [comment]
Ok, I cleared the cookies and file cache from the last 7 days, and it is working now. Thanks you can close it.

**Comment by Tratcher** [comment]
I'm looking around to see what might have issued that permanent redirect. The only instance I can find is the DefaultFiles middleware, but it's not used in templates.
https://github.com/aspnet/AspNetCore/blob/efd765e970db256d968464aa6c24313880f2298c/src/Middleware/StaticFiles/src/Helpers.cs#L46
