### ISSUE TITLE
Blazor Server on IE11 doesn't deal with datetime validation with a polyfill.

### ISSUE THREAD

**Issue by StevenGranados** [aspnet/AspNetCore#17759]
### Describe the bug
Using Blazor on IE11 with this https://github.com/Daddoon/Blazor.Polyfill produces an error in validating datetime fields.
### To Reproduce
A datetime input in a form with validation produces this error after unfocusing the input:

Unhandled exception at line 8, column 53420 in https://localhost:44383/_framework/blazor.server.js
0x800a139e - JavaScript runtime error: Invalid element type 'text'.

A littlepiece of minified javascript from blazor.min.js:

o=function(e){var t=e.value,n=e.type;switch(n){case"date":case"datetime-local":case"month":return t;case"time":return 5===t.length?t+":00":t;case"week":return t}throw new Error("Invalid element type '"+n+"'.")}(n);

I believe it can be fixed by including a text case in addition to the other datetime cases or a default case.

I know IE11 isn't supported but any help would be appreciated.

### Further technical details
- ASP.NET Core version: 3.1
- The IDE (VS / VS Code/ VS4Mac): VS2019 16.4.1

**Comment by javiercn** [comment]
@StevenGranados thanks for contacting us.

Is this something that could be fixed in https://github.com/Daddoon/Blazor.Polyfill directly?

**Comment by mkArtakMSFT** [comment]
Closing this issue as this seems to be external to this repo. We recommend filing this issue in the reference repo.
