### ISSUE TITLE
How can I access from AuthorizeRouteView.NotAuthorized the url or name of a component .

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#17764]
How can I access from AuthorizeRouteView.NotAuthorized the url or name of a page component from which I'm being redirected to a Login component. In other words, when an unauthenticated user tries to access a page component with the Authorize attribute, he should be redirected to a Login component. The code to navigate to the  Login component resides within the AuthorizeRouteView.NotAuthorized property thus:

        <AuthorizeRouteView RouteData="@routeData" 
                                    DefaultLayout="@typeof(MainLayout)">
                <NotAuthorized>
                       NavigationManager.NavigateTo("Login");
                 </NotAuthorized>
                <Authorizing>
                    Wait...
                </Authorizing>
          </AuthorizeRouteView>

Now, what I want to pass with the login route is the return url; that is the url from which the user is redirected, so that if the login succeed, I can redirect the user to the the page he wanted to access. I could do it, but as shown below, but it smells as a workaround, and I want to know if Blazor has a dedicated feature for this purpose, which I believe many users will need without resorting to workarounds.  This is the code that is supposed to do the job:
    
     @{
          var returnUrl = routeData.PageType.Name.Equals("Index") ? null : routeData.PageType.Name;
                           
          var str = returnUrl == null ? $"Login/Index" : $"Login/{returnUrl}";

           NavigationManager.NavigateTo(str);
     }
 
Note: routeData.PageType.Name returns values such as Counter and FetchData, which is fine and I can use it as the return url. But it also returns Index, which is not so fine, because I can't use Index as a url...
This "Login/Counter" works, and this "Login/FetchData" aslo works, but this "Login/Index" does not exist.

Note also that in the Login component, I define a parameter Property which will accept the return url value passed to the Login component. 

This should be a common scenario, and that feature is much needed unless I've missed something. Thanks.

**Comment by javiercn** [comment]
@enetstudio thanks for contacting us.

You could write a "Redirect" component and use NavigaionManager.Uri to get the current URI, and then redirect appropriately.

**Comment by enetstudio** [comment]
Thank you very much for your quick and immensely  helpful response. I was well aware of NavigaionManager.Uri property, but I thought that I could not get the current uri as I wrongly believed that the page I was trying to access no longer exists, as a redirection to the App component has occurred. But I guess that  the App component ( and the Router embedded within) are not part of the routing. They are the routing agent themselves, and as long as no new routing (to a routable component)  has taken place, the current uri is that of the page I was trying to access (say, the FetchData page with the Authorize attribute. Am I write in my assumption ? Anyhow I did what you've suggested and it works great. Once again, many thanks...
