### ISSUE TITLE
Can't connect to SignalR hub when using Authorize and device is NOT on domain

### ISSUE THREAD

**Issue by Nicks182** [aspnet/AspNetCore#17762]
First, I'm new to signalR and mostly just messing around and trying to learn. I've been stuck for a few days now and my Stackoverflow question has gotten zero responses.

https://stackoverflow.com/questions/59261940/signalr-with-net-core-cookieauthentication-on-domain-issue

Issue:
If I have a ASPNETCORE app with signalR, hosted in IIS on Win10 Pro machine, and I have just very simple user authentication, any device that is NOT part of the domain, but on the same network, will get a 401 Unauthorized error in the console in browser Dev tools when trying to establish a signalr connection.

If a machine/device that IS on the domain connects to the app, you can log in and connect to the hub with no issue.

If I remove all user authentication and the Authorize attributes, ANY device on the network can connect to the signalr hub with no issue while hosted on the exact same Win10 Pro IIS.

It's like the Context is not being set when a machine or device that is NOT part of the domain connects to the app even though they can still log in 100% fine.

To reproduce:
All I did was follow the steps from:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio

In this state, any device can access the chat app regardless if it's on the domain or not while hosted in IIS on the same Win10 Pro machine.

I then added very basic authentication using this:
http://future-shock.net/blog/post/creating-a-simple-login-in-asp.net-core-2-using-authentication-and-authorization-not-identity

Once this, or something similar, is added, any machine that IS part of the domain can login and connect to the hub just fine. 
Any device NOT part of the domain can log in, but cannot connect to the hub and will get the 401 Unauthorized message.

I uploaded my code to Github... or more accurately, dumped it on github... (I've not really used Github like this before, sorry):
https://github.com/Nicks182/asp.netCoreSignalRTest

Like I said, I've been stuck on this for a few days now. I did try bearer tokens, but got stuck on that with the app not even wanting to run... HOWEVER, I've not spent any time trying to fix it yet. I wanted to figure out why my current setup is not working... the goal is to learn and know why something is not working. If it ends up a IIS issue then moving to something else might not work either.

I don't know if this is a actual bug or not... I'm to new to .net core and signalr to know. I'm hoping it's something simple so I don't waste anyone's time here, but I don't know where else to ask.

EDIT: I have 2 other standard asp.net sites hosted on the same machine I use for testing and they work fine regardless if a connecting device is on the domain or not. It's only this signalr app that's having this issue.

**Comment by Nicks182** [comment]
OK, so... now no one can connect to the signalR hub regardless if they are on the domain or not. If there is no Authorization, anyone can connect to the HUB. 

If I enable Authorization and no one on the network can connect to the hub. Only the Win10 machine where it's hosted can connect to hub with Authorization.

It must be an IIS issue?

**Comment by anurse** [comment]
> any device that is NOT part of the domain, but on the same network

Can you clarify what you mean here? Are you talking about Windows/Active Directory "Domains" or do you mean the app and client are running on different domain names?

**Comment by Nicks182** [comment]
Windows Domain, but like I said, it seems to not make a difference now. I was testing this yesterday morning, then moved on to some actual work for about 5 hours and when I had some time to take a look at this again it seems the Domain does not matter now... so frustrating...

If authorization is active, no one/device on the network is able to connect to the hub after login over the network. 

If I remove authorization, any one/device CAN connect to the hub just fine over the network.

If authorization is active, and I run the app on the Win10 machine the app is hosted, I can login and connect to the hub just fine. I can pull the user info, that was set during logon, from the hub context just fine.

Seems like if authorization is Active you CAN login, but you CANNOT connect to the hub over the network and you get a Unauthorized 401 error in the console in browser dev tools. It's like the Hub context does not get the info or has access to the info related to the login when running this over the network... this is just a guess though as my knowledge is rather limited still.

**Comment by Nicks182** [comment]
So... I was watching youtube vids, as you do, and I got a video recommended about publishing dotnetcore apps to IIS on Win10. In the video the guy create a new site in IIS... he did not use the default site.

Decided to give this a go and logged into the office PC and created a new site in IIS on the Win10 Pro machine and left everything on default settings. Added the app to it and it looks like it's working fine now. WTH?

Before I just added the app to the Default Site in IIS... like I've always done for years when doing testing, but with aspnetcore this seems to be an issue??

Something in the setup of the Default Site in IIS is breaking this. Just me or this machine?? Really don't know... 

I will try and test this on another Win10 machine. We have a Win10 laptop that I know does not even have IIS on it yet. So will do a new IIS setup and check if the same issue comes up if I use the Default Site again.

I'm working from home right now and I can launch the app, login, and connect to the hub just fine through our VPN from my personal rig. I can only do testing with my colleges tomorrow when I'm back in the office. 

I knew it was a IIS issue...

**Comment by halter73** [comment]
> I will try and test this on another Win10 machine. We have a Win10 laptop that I know does not even have IIS on it yet. So will do a new IIS setup and check if the same issue comes up if I use the Default Site again.

Please feel free to file a new issue or reopen this one if this indeed a problem with the default site on a fresh install.
