### ISSUE TITLE
Create HttpClient without Base URL when running from Electron

### ISSUE THREAD

**Issue by rabejens** [aspnet/AspNetCore#17767]
### Is your feature request related to a problem? Please describe.

I modified the Client-Side example to run in Electron which works fine, save for the injected `HttpClient`.

### Describe the solution you'd like

When I do

```csharp
@inject HttpClient http
```

I get an exception:

```
System.ArgumentException: Only 'http' and 'https' schemes are allowed.
```

This happens because Electron calls a local `index.html` file which makes the Base URL a `file://` URL which HttpClient is not happy with. It happens here in `WebAssemblyHostBuilder`:

```csharp
services.AddSingleton<HttpClient>(s =>
{
    // Creating the URI helper needs to wait until the JS Runtime is initialized, so defer it.
    var navigationManager = s.GetRequiredService<NavigationManager>();
    return new HttpClient
    {
        BaseAddress = new Uri(navigationManager.BaseUri) // <- boom!
    };
});
```

I suggest checking if the BaseUri is `http` or `https`, and if not, just returning a `new HttpClient();` and maybe issuing a warning to the log.

### Workaround

I discovered that you can add services which already exist in the `ConfigureServices` method of `Startup.cs` and they will override the old definition. So, if you add this to your `ConfigureServices` method, it works as I suggest:

```csharp
services.AddSingleton(delegate (IServiceProvider s) {
    var nm = s.GetRequiredService<NavigationManager>();
    var lf = s.GetRequiredService<ILoggerFactory>();
    var l = lf.CreateLogger(typeof(Startup));
    var baseUri = new Uri(nm.BaseUri);
    var scheme = baseUri.Scheme.ToLowerInvariant();
    switch(scheme) {
        case "http":
        case "https":
            l.LogInformation("Configuring HTTP Client with Base URI {0}", baseUri);
            return new HttpClient {
                BaseAddress = baseUri
            };
        default:
            l.LogWarning("Scheme is {0} instead of http or https, returning HTTP Client with default settings", scheme);
            return new HttpClient();
    }
});
```

So when the `HttpClient` is requested, it is first checked if the scheme of the base URI is `http` or `https`. If it is, the client is configured with the base URI, otherwise a client with the default settings is returned.

When now doing `@inject HttpClient http` there will be no crashes, but when running from Electron, you get a client which is not configured with a Base URI which can be used to query remote APIs.

**Comment by javiercn** [comment]
@rabejens thanks for contacting us.

We plan to move the registration of the HttpClient instance outside of the default configured services. We used to do this in the past due to the need to replace the default HttpClientHandler, but that's not the case anymore.

In the future this won't be an issue and users will get to register the HttpClient in DI in whatever way they want.

**Comment by javiercn** [comment]
@SteveSandersonMS in case he wants to add anything.
