### ISSUE TITLE
Html.RenderPartialAsync(ViewData["formUrl"].ToString());Partial view location is the same as the search location, the prompt is invalid

### ISSUE THREAD

**Issue by namelhp2000** [aspnet/AspNetCore#17763]
InvalidOperationException: The partial view '/wwwroot/RoadFlowResources/scripts/formDesigner/formpreview/9cba46ec-3768-40a8-bce4-907c933599e0.rfhtml' was not found. The following locations were searched: /wwwroot/RoadFlowResources/scripts/formDesigner/formpreview/9cba46ec-3768-40a8-bce4-907c933599e0.rfhtml

Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(string partialViewName, object model, ViewDataDictionary viewData, TextWriter writer)
AspNetCore.Areas_RoadFlowCore_Views_FormDesignerPlugin_PreView1.ExecuteAsync() in PreView1.cshtml

        await Html.RenderPartialAsync(ViewData["formUrl"].ToString());

Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by javiercn** [comment]
@namelhp2000 thanks for contacting us.

In order for us to help you. Could you provide more details on what you are trying to achieve and include a minimalistic repro project with detailed steps to illustrate the issue?

**Comment by namelhp2000** [comment]
During debugging, a new local view is created and the local view is called to report the buff on it

Or modify the local view, call the local view, call the result is not the modified view. The local view does not take effect until it is re-debugged.

**Comment by namelhp2000** [comment]
Html.RenderPartialAsync(ViewData["formUrl"].ToString()) This function works normally in Core2.2

**Comment by pranavkm** [comment]
This sounds the same issue as https://github.com/aspnet/AspNetCore/issues/17650. @namelhp2000 is renaming the file extension to cshtml an option?

**Comment by namelhp2000** [comment]
InvalidOperationException: The partial view '/wwwroot/RoadFlowResources/scripts/formDesigner/formpreview/d24c28d4-f64c-4114-8813-cfe3167a4d07.cshtml' was not found. The following locations were searched: /wwwroot/RoadFlowResources/scripts/formDesigner/formpreview/d24c28d4-f64c-4114-8813-cfe3167a4d07.cshtml

**Comment by namelhp2000** [comment]
Add reference  Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation is OK

**Comment by namelhp2000** [comment]
Reference to add  Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation  is OK！
