### ISSUE TITLE
Lost Support for .NET Standard IN Microsoft.AspNetCore.Authentication.JwtBearer 3.1.0

### ISSUE THREAD

**Issue by AbhiOnGithub** [aspnet/AspNetCore#17769]
### Describe the bug
Team, Nuget package named Microsoft.AspNetCore.Authentication.JwtBearer  has lost support for .NET Standard during recent version push. 3.1.0 (8 days ago).
It is now having support for .NET Core but not .NET Standard

If you see older version.
https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/2.2.0
It is having support for .NET Standard.

How One can create a .NET Standard library using this Nuget Pacakge, because it supports .NET Core but not .NET standard because of this reason , this is the only package in our solution which we can't upgrade(we are forced to use 2.2 version of it).

I am more interested in knowing that loosing support for .NET Standard is intentional or accidental.
Thanks.

<img width="913" alt="Screenshot 2019-12-11 at 4 29 53 PM" src="https://user-images.githubusercontent.com/12324923/70616017-88aa6680-1c33-11ea-97af-be6b13f4dc25.png">

<img width="870" alt="Screenshot 2019-12-11 at 4 30 09 PM" src="https://user-images.githubusercontent.com/12324923/70616019-88aa6680-1c33-11ea-9e12-813b1fe413f4.png">

**Comment by blowdart** [comment]
You "lost" it in 3.0

See https://github.com/aspnet/Announcements/issues/324 for the announcement last year explaining why,

**Comment by AbhiOnGithub** [comment]
Thanks @blowdart for he info.
