### ISSUE TITLE
HTML not updating after edit. VS 2019 16.4.1

### ISSUE THREAD

**Issue by garethdebruyn** [aspnet/AspNetCore#17776]
After building the solution and opening in the browser; if I edit and save HTML/javascript/css changes in VS, the changes are not been shown in the browser after a refresh.
This is not a simple browser caching issue. 

This functionality worked and still works fine in VS 2017. I can make a change to the HTML, save the changes and then refresh the browser and the changes will be displayed in the browser. 

In 2019 I need to rebuild the entire solution to see every HTML or js change. This is making dev extremely painful and time-consuming. Is there a setting that has been changed in 2019?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The feature you're referring to here is called Razor Runtime Compilation. In ASP.NET Core 3.0 release we've [announced a breaking change in that behavior](https://github.com/aspnet/Announcements/issues/343).
To enable Runtime Compilation for ASP.NET Core 3.0+ applications, you can follow the guidance provided at: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#runtime-compilation

**Comment by garethdebruyn** [comment]
Great, it worked. Thank you @mkArtakMSFT
