### ISSUE TITLE
How to access action metadata and custom attributes of an action inside middleware handler? (ASP.net core 3)

### ISSUE THREAD

**Issue by vasicvuk** [aspnet/AspNetCore#17772]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

I would like to access action metadata and custom attributes within middleware before MVC.

### Describe the solution you'd like

In issue https://github.com/aspnet/AspNetCore/issues/7795 it was said that this will change in ASP.Net 3.0 so that it can be accessed before Mvc so I am wondering if this is already possible or not yet?

**Comment by Kahbazi** [comment]
Each action is an Endpoint and you can get all custom attributes of the action from Endpoint metadata. Remember you need to place the middleware after `app.UseRouting()` and before `app.UseEndpoints()`.

```csharp
app.UseRouting();

app.Use((context, next) =>
{
    var endpoint = context.GetEndpoint();
    if (endpoint != null)
    {
        var metadata = endpoint.Metadata;
    }

    return next();
});

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");
});
```

**Comment by vasicvuk** [comment]
Thanks, closing issue.
