### ISSUE TITLE
404 loading icon

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17782]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/840303/404-loading-icon.html)._

---
I have the latest community edition of Visual Studio (16.3.10). I have two branches of code. the code was initialy generated from a ASP.NET MVC + Angular template. One branch has no problem loading the favicon.ico on debug (F5). The other branch gives out in text to the browser "Cannoy GET /". On refreshing the page with the Chrome debug tools active I see that the error is that favicon.ico violates "Content Security Policy". Between the two branches I cannot see any code that has anything to do with "Content Security Policy". Where do I look to see why one branch violates "Content Security Policy" and the other doesn't?

---
#### Visual Studio Feedback System on 12/3/2019, 02:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/3/2019, 07:08 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
