### ISSUE TITLE
[Blazor/Wasm] DiagnosticListener not called

### ISSUE THREAD

**Issue by RemiBou** [aspnet/AspNetCore#17790]
### Describe the bug
When we subscribe a diagnostic listener in client side Blazor app it is not calledwith event from httpclient
### To Reproduce
```bash
git checkout https://github.com/RemiBou/dotnet
cd samples/Samples.Blazor
dotnet run
```
The browser console does not show anything from "BlazorObserver".

Maybe this should be moved to the runtime repo ?

### Further technical details
- sdk 3.1

**Comment by javiercn** [comment]
@RemiBou thanks for contacting us.

We don't think this is a blazor specific issue and it is likely that you'll get a better and more accurate response if you file this issue directly in the mono repo at [mono/mono](https://github.com/mono/mono)
