### ISSUE TITLE
Blazor: Control how StateHasChanged batches updates to client

### ISSUE THREAD

**Issue by aaronhudon-ts** [aspnet/AspNetCore#17795]
Blazor server side - .NET Core 3.1 

I am receiving information in a background thread (socket), and am rendering the information through a Blazor component.  As the frequency of information from the background thread increases, and I issue `StateHasChanged` in my component to reflect the new state on the screen, the results are very "janky".  From a high-level, it really just seems like the Blazor internals is buffering a number of states before they get set out to the client.

Is there any way to force the Blazor/SignalR pipeline to force an update to the client, to avoid what appears to be batching?

**Comment by javiercn** [comment]
@aaronhudon-ts thanks for contacting us.

I'm not sure what you mean by "janky" as in it might not be updating often enough or it might be updating too often.

If it's the first case, we likely send the data as soon as the component gets rendered unless we are already in the middle of a render, in which case the update gets batched with other components update.

It might be that you are updating the client too fast and rendering gets paused until the client has acknowledged the render. For that situation you can set CircuitOptions.MaxBufferedUnacknowledgedRenderBatches to a higher value and check if that fixes your issue. 

Be aware that this implies a trade-off between security and responsiveness, so set it to the lowest value that meets your experience and be aware that a higher value means that more memory might be used potentially by individual circuits on peak loads.
