### ISSUE TITLE
Event binding broken in Blazor components in a Razor Class Library

### ISSUE THREAD

**Issue by XomegaNet** [aspnet/AspNetCore#17809]
### Describe the bug
I have created an RCL library for Blazor components as per [these docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&tabs=visual-studio).

When adding Blazor components with event binding, such as
`<select @onchange="@OnValueChanged">`

I am getting the following error message:
_error CS1503: Argument 3: cannot convert from 'method group' to 'EventCallback'_

### Analysis
This is because RCL projects use the Razor SDK
`<Project Sdk="Microsoft.NET.Sdk.Razor">`

and the code generated from the .razor file looks like this:
```
__builder.AddAttribute(4, "@onchange", 
		OnValueChanged
);
```
However, the same component works fine when it's in a Blazor project that uses Web SDK
`<Project Sdk="Microsoft.NET.Sdk.Web">`

In this case, the code generated from the .razor builds fine, and looks like this:
```
__builder.AddAttribute(4, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.ChangeEventArgs>(this, 
	   OnValueChanged
));
```
### Workaround

You can set the event handler without the @ in the RCL in your .razor file like this
`<select @onchange="OnValueChanged">`

which will build, and generate the following code:
`__builder.AddAttribute(4, "@onchange", "OnValueChanged");`

But this still prevents you from [using lambda expressions](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lambda-expressions) that allows closing over additional values , e.g.
`<select @onchange="@(e => OnValueChanged(e, localValue))">`

### Further technical details
- ASP.NET Core version 3.0
- The IDE is VS 2019 version 16.4.1

**Comment by javiercn** [comment]
@XomegaNet thanks for contacting us.

@rynowak can you take a look at this issue? You're likely the best suit for it.

**Comment by rynowak** [comment]
@XomegaNet  - can you check if your RCL project has `@using Microsoft.AspNetCore.Components.Web`?

**Comment by XomegaNet** [comment]
@rynowak I've added this import to my project, and that seem to have fixed the issue, so I'll go ahead and close it. Thanks for your advice, this was not at all obvious. Perhaps it is also worth mentioning this in the RCL documentation for Blazor.

**Comment by rynowak** [comment]
@XomegaNet this is part of the template https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/RazorClassLibrary-CSharp/_Imports.razor

but I think you're right. This kind of info (or any info about components) is not easy to find from the RCL doc. I'll log an issue.

**Comment by XomegaNet** [comment]
@rynowak I actually used that template for creating a new RCL project, but I checked the 'Support pages and views' checkbox in the configuration wizard, and it generated a project without the _Imports.razor. You may want to log it as another issue then.

**Comment by rynowak** [comment]
Ah! that's surprising. Ok I'll follow up, thanks for the extra info.
