### ISSUE TITLE
A simple way to add npm packages to a Blazor project

### ISSUE THREAD

**Issue by Roemer** [aspnet/AspNetCore#17813]
### Is your feature request related to a problem? Please describe.
There are a ton of npm packages with styles, javascript, images which are used in many projects. Most web project frameworks (Angular for example) are npm based, so it is straight forward to include any npm package in any project.
As blazor is not npm based, I haven't found a simple way to include npm packages into it easily. In my concrete example, I am trying to include the package https://www.npmjs.com/package/swiss-styleguide into the template project from visual studio. I fail on how to get the fonts, javascripts and scss files added correctly so they are usable.

### Describe the solution you'd like
I don't actually exactly know what I expect. Probably something like that npm can be used directly inside the wwwroot folder which will then create a node_modules folder inside it and that the modules inside there are automatically compiled (scss) and / or webpacked and such so that their assets are directly usable.
Probably an additional file like the `angular.json` is needed where one can specify, what scripts, assets or styles should be included.
An example for that section in `angular.json` would look like:
```json
"assets": [
	"src/favicon.ico",
	"src/assets"
],
"styles": [
	"node_modules/@clr/icons/clr-icons.min.css",
	"node_modules/@clr/ui/clr-ui.min.css",
	"node_modules/font-awesome/css/font-awesome.css",
	"src/styles.scss"
],
"scripts": [
	"node_modules/@webcomponents/custom-elements/custom-elements.min.js",
	"node_modules/@clr/icons/clr-icons.min.js"
]
```

**Comment by javiercn** [comment]
@Roemer thanks for contacting us.

You could try and use Libman to achieve this [See more details](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/?view=aspnetcore-3.1)

If that doesn't work, let us know. Otherwise you can have a package.json and use MSBuild extensibility to perform npm install and copy the assets to a suitable location to be referenced by the web app. (Which is essentially what Libman does I believe).

If you are building a library then you can simply pack it as static web assets to make it readily available to your consumers.

**Comment by Roemer** [comment]
The package I want to use is only on npm (https://www.npmjs.com/package/swiss-styleguide). I was unable to add this via libman.

**Comment by javiercn** [comment]
@Roemer 

I'm not expert on this area and you might get a better response on stackoverflow, but I would try a couple of things.

You could use https://www.nuget.org/packages/Yarn.MSBuild/ alongside a package.json and libman to set this up.

Then you could set it up with libman as a filesystem provider
```
{
  "provider": "filesystem",
  "library": "node_modules/...",
  "destination": "wwwroot/...",
  "files": [
    "..."
  ]
}
```

Or you could try unpkg that should expose anything available on npm.
