### ISSUE TITLE
Kestrel Parallel requests are missing to hit the server.is there any inbuilt queuing mechanism

### ISSUE THREAD

**Issue by KamranShahid** [aspnet/AspNetCore#17814]
Kestrel Parallel requests are missing to hit the server.is there any inbuilt queuing mechanism?

**Comment by davidfowl** [comment]
> Kestrel Parallel requests are missing to hit the server.is there any inbuilt queuing mechanism?

Can you clarify what you mean? There's a queuing middleware but I don't now what "missing to hit the server" means. Do you have more details?

**Comment by KamranShahid** [comment]
I am doing some load testing with my post web api's. What i am observing is if i send request in parallel (like 100) only 20 odd request lands on the server.
Same request when called with some delay like Thread.Sleep(25) they are entertained by the server

**Comment by davidfowl** [comment]
Don't sleep. Don't block threads and it'll scale better 😄.  You can try looking at the performance counters using the `dotnet counters` tool (see https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters).

**Comment by KamranShahid** [comment]
> Don't sleep. Don't block threads and it'll scale better 😄. You can try looking at the performance counters using the `dotnet counters` tool (see https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters).

this sleep is in my client project where i am trying with different criteria

**Comment by KamranShahid** [comment]
My Web api startup code is following		
		public static void Main(string[] args)
        {
			 StartupShutdownHandler.BuildWebHost(args).Build().Run();
		}
		

    public class StartupShutdownHandler
    {

        public static IWebHostBuilder BuildWebHost(string[] args) => WebHost.CreateDefaultBuilder(args).
            ConfigureKestrel(serverOptions => {
                serverOptions.Limits.MaxConcurrentConnections = long.MaxValue;
                serverOptions.Limits.MaxConcurrentUpgradedConnections = long.MaxValue;
            
            }).UseIISIntegration()
            .UseStartup<StartupShutdownHandler>();

     
        public StartupShutdownHandler(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();            
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
            });
        }        

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime)
        {
            
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseRouting();
            app.UseCors(MyAllowSpecificOrigins);
            app.UseHttpsRedirection();
            app.UseForwardedHeaders();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
            });
            //app.UseMvc(); //this is changed in 3.0
            applicationLifetime.ApplicationStarted.Register(StartedApplication);
            applicationLifetime.ApplicationStopping.Register(OnShutdown);
        }


        private void OnShutdown()
        {
            ...
        }

        private void StartedApplication()
        {
           ...
        }
    }

**Comment by Tratcher** [comment]
And what does your client look like? Clients usually have concurrency limits.

**Comment by KamranShahid** [comment]
we are running test from jemeter as well as my local .net form application client. same application is running in one windows server under iis is performing fine while same app running in ubuntu 18 machine looks like loosing requests.

**Comment by Tratcher** [comment]
> What i am observing is if i send request in parallel (like 100) only 20 odd request lands on the server.

What happen to the other 80? Does an error get reported on the client? What kind?

**Comment by KamranShahid** [comment]
Two changes i have done after which request is been at-least entertained now.
**<ServerGarbageCollection>false</ServerGarbageCollection>**

And socket related tweaks on my ubuntu 18 (AWS 2) server http://www.tweaked.io/guide/kernel/

Last problem i am facing is related to redis error (I am using StackExchange.Redis) on my server when there is a load. no problem on windows server with same code

**Comment by KamranShahid** [comment]
Good to close but this is only done by hit and try of various solution which i have searched on google.  It could be nice if someone atleast give some light on the solution i have tried
