### ISSUE TITLE
OOM on 3.1, AspNet Core 2.2 and 3.1 different behavior in GC

### ISSUE THREAD

**Issue by vasicvuk** [aspnet/AspNetCore#17815]
### Describe the bug

We started migrating our ASP.Net Core microservices from 2.2 to 3.1 after some testing we found out that Memory usage is higher on ASP.Net core 3.1 also under high load done with Apache Jmeter (25 threads continuously calling API) Asp.net core 2.2 have fix amount of memory usage (72mb) and Asp.Net core 3.1 gets OOM.

Both applications have **ServerGarbageCollection** disabled with;

```xml
    <ServerGarbageCollection>false</ServerGarbageCollection>
``` 

### To Reproduce
1. Create an simple API that gets data from database
2. Call the API from Apache JMeter (25 threads and infinite repeat) for both ASP.Net Core 2.2 and 3.1

### Further technical details
- ASP.NET Core version 3.1

**Dotnet info Dot net 2.2 runtime:**
```
Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Dotnet info Dot net 3.1 runtime:**
```
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Containers images used**:
- mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine
- mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine

**UPDATE**

When Apache JMeter is stopped before OOM container still uses 320mb of ram (limit 384) and no memory is freed up after that.

**UPDATE 2**

Tested setting CPU limit on Container to 900m (Idea was trigger Workstation gardbage collection because CPU limit is less then 1) but same behavior

**UPDATE 3**
It  seems that the issue is coming from the custom Middleware for authorization that we use. Memory behavior is normal when the middleware is disabled. I am now trying to where the issue is.

**Comment by javiercn** [comment]
@vasicvuk thanks for contacting us.

@davidfowl You probably know the right people to help here.

**Comment by vasicvuk** [comment]
I found that the issue is with Serilog and Serilog Graylog sink causing Out of memory issue. I am closing issue here.
