### ISSUE TITLE
Multipart file loaded into memory when controller method has parameter

### ISSUE THREAD

**Issue by Pilchie** [aspnet/AspNetCore#17837]
_From @matthiaslischka on Thursday, December 12, 2019 2:20:13 PM_

Multipart file upload will first load the file into memory and only then call the controller method as soon as the controller method as parameters. Even if the parameters are only url or query parameters.

## Background
We want to stream a large file directly from the frontend into azure storage and need to pass some ID in addition to the file (query parameter).

## Problem
Real streaming does only work when the controller method has no parameters. **This works correctly**, you can access the stream with the `MultipartReader`:
```csharp
[HttpPost]
public async Task<IActionResult> UploadFile()
```

**This does not work correctly** because the whole request is stored into memory before the controller method is called:

```csharp
[HttpPost]
public async Task<IActionResult> UploadFile([FromQuery] UploadDocumentProperties uploadDocumentProperties)
```

As soon as there is any parameter the whole request will be loaded into memory and only when this is done the controller method is called. This is even true when the parameter is only a url or query parameter.

We noticed this with big files. The UI control uploaded them to 100% and then the user had to wait about the same time again for the API to stream the file to azure. With debugging we could see that the controller is not called before the UI control uploaded the file completely. Now without the parameter the controller is called immediately and streams the file directly as expected.

## Workaround
We need some ID that is passed as query parameter. Since the controller method must not have any parameter for the streaming to work correctly we parse the query parameters by hand (`Request.Query`).

BR
Matthias

_Copied from original issue: dotnet/core#3986_

**Comment by Pilchie** [comment]
_From @ltouro on Thursday, December 12, 2019 4:13:04 PM_

Not related to the error you reporting, but I would suggest a different approach to uploading big files to Azure. 

Generate a SAS key on the server and send it to the client (with upload permission only). Then, the client upload the file directly to Azure. After the operation completes, the client notifies the server.

This way, the file is never sent to your server and you will have no memory problems. This is a common pattern and implemented by several upload controls libraries.

HTTP REQ 1 -> Client - Your server -> return upload URL with embedded SAS key
HTTP REQ 2 -> Client - Azure -> upload the file to Azure using the SAS key
HTTP REQ 3 -> Client - Your server -> notifies upload successful

See a better explanation here: https://docs.fineuploader.com/branch/master/features/azure.html

**Comment by Pilchie** [comment]
_From @carlossanlop on Thursday, December 12, 2019 5:43:18 PM_

@Pilchie can you please move to the asp repo?

**Comment by pranavkm** [comment]
We have documentation that shows how to stream a large file without MVC attempting to read the request body: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#upload-large-files-with-streaming.

**Comment by matthiaslischka** [comment]
I know, thanks. However, this is a bug nevertheless. Why should adding a query or url parameter read the complete stream into memory first - and only then call the controller method?

**Comment by pranavkm** [comment]
MVC does not determine what model binding sources to use based on the parameters. By defaullt, Form, Query, and Route and read by default. Using the filter in the doc article that was previously provided is the way to change this behavior.

**Comment by rynowak** [comment]
It's also possibly a bug that we **don't** have this behavior when you have no parameters. I'm not motivated to change it because no one has asked for it to change, and it would make performance worse.
