### ISSUE TITLE
Blazor - Services called inside OnInitializedAsync are called twice

### ISSUE THREAD

**Issue by Blackleones** [aspnet/AspNetCore#17849]
I observed that services called inside OnInitializedAsync methods are called twice. Is this an expected behaviour? 
I noticed that if I move my services from OnInitializedAsync to OnAfterRenderAsync then they will be called initially once.

Why I notice that: 

I notice OnInitializedAsync's behaviour because my service calls a dbContext query and it throw exception "a second operation ...", but if I move my service call inside OnAfterRenderAsync then it doesn't throw any exception.

I publish a sample about how many times my service is called: https://github.com/Blackleones/BlazorTest

**Comment by javiercn** [comment]
This behavior is by design. Read https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#stateful-reconnection-after-prerendering for details

**Comment by mrpmorris** [comment]
I still don't in understand why this is done considering the services never leave the server
