### ISSUE TITLE
Multiple external authentication providers of the same type conflict

### ISSUE THREAD

**Issue by Aaronmsv** [aspnet/AspNetCore#17855]
### Describe the bug

We have a use case where we want to have multiple external authentication providers of the same type, but with different configuration. For example two Microsoft, Google or SAML authentication providers.

Assume we configured Google two times, with different client ids, client secrets and authentication scheme names. The first scheme works perfectly, but when you try to use the second one (or any after that?) the following exception is thrown:

```
System.Exception: An error was encountered while handling the remote login. ---> System.Exception: The oauth state was missing or invalid.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### To Reproduce

This is a little bit related to issue #14250. We are configuring the external authentication providers at runtime ourselves, instead of using e.g. `AddGoogle` in the `Startup.cs`. I make sure that every authentication scheme is unique and the name is passed correctly down the chain, also when updating the options cache. (It is still on my todo-list to write that example!) However, I was able to reproduce this with the built-in methods as well, so I will show it like that to keep things simple.

So configure Startup.cs like this:
``` C#
            services.AddAuthentication().AddGoogle("googleScheme1", options =>
            {
                options.ClientId = "...";
                options.ClientSecret = "...";
            });

            services.AddAuthentication().AddGoogle("googleScheme2", options =>
            {
                options.ClientId = "...";
                options.ClientSecret = "...";
            });
```

And then try to use the second one to login, it fails on the callback to `/signin-google`, but I think the problem is on a lower level.

I notice that the correlation cookies are set correctly, with a prefix like `.AspNetCore.Correlation.%schemeName%.`, but I have the feeling that it is looking for the wrong cookie on the callback. I haven't debugged it at all, but I've taken a look at:

* AuthenticationHandler.cs
* RemoteAuthenticationHandler.cs
* OAuthHandler.cs

### Further technical details
- ASP.NET Core 2.2

**Comment by Kahbazi** [comment]
You should set different Callback path for each Google authentication scheme.

**Comment by Tratcher** [comment]
@Kahbazi is correct.

**Comment by Aaronmsv** [comment]
Okay, thanks @Kahbazi and @Tratcher, I will make sure they use a unique callback for each scheme.
