### ISSUE TITLE
Multiple <component> tag helpers in same element interfere with each other

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#17851]
It seems that when you use multiple `<component />` tag helpers side-by-side, e.g.,:

```cshtml
    <app style="display:block">
        <component type="typeof(Something)" render-mode="Server" />
        <component type="typeof(AnotherThing)" render-mode="Server" />
    </app>
```

... then they can disrupt each others' rendering and lead to corrupted UI updates. See the repro at https://github.com/aspnet/AspNetCore/issues/17570

My guess is that our JS-side code that converts the `<!--Blazor:...-->` comments into a `LogicalElement` isn't setting it up correctly, and perhaps has the logical elements both hooked up to the physical DOM parent as if they were its only child.

**Comment by rynowak** [comment]
@SteveSandersonMS is this something we should look into patching?

**Comment by SteveSandersonMS** [comment]
@rynowak I think we should be prepared to do so. We know this has to be fixed, so there's no reason to delay doing so. Once we know what the fix looks like, we can make a call about whether it's small and safe enough to release as a patch, or whether that would take additional investment and we would rather wait for customer demand before doing so.

The workaround is pretty simply (surround each `<component>` with its own `<div>`) so it's more about the risk of people unknowingly deploying buggy sites than about there not being a workaround.

**Comment by SteveSandersonMS** [comment]
Fixed in https://github.com/aspnet/AspNetCore/pull/17910
