### ISSUE TITLE
Implementing filters directly on a controller works only for some filters

### ISSUE THREAD

**Issue by thomaslevesque** [aspnet/AspNetCore#17858]
Not sure if it's a bug, it might be as designed. But in the latter case, it's a weird design, and I haven't seen it documented anywhere...

### Describe the bug
In some situations, I need a filter that is only applicable to a specific controller. In this case, making it as a standalone filter doesn't really make sense, so I implement the filter directly on the controller, as explained in [this article](https://www.strathweb.com/2018/06/controllers-as-action-filters-in-asp-net-core-mvc/).

It works fine for some filters (e.g. `IAsyncActionFilter`). But for others (e.g. `IAsyncExceptionFilter`), it doesn't: the filter is never invoked.

### To Reproduce

1. Implement a controller like this:
```csharp
    [ApiController]
    [Route("[controller]")]
    public class DummyController : ControllerBase, IAsyncActionFilter, IAsyncExceptionFilter
    {
        private readonly ILogger<DummyController> _logger;

        public DummyController(ILogger<DummyController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Dummy(bool @throw = false)
        {
            if (@throw)
                throw new Exception("Boom");
            return Ok(new { id = 123, value = "hello world" });
        }

        [NonAction]
        public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
        {
            _logger.LogInformation("OnActionExecutionAsync: before");
            await next();
            _logger.LogInformation("OnActionExecutionAsync: after");
        }

        [NonAction]
        public Task OnExceptionAsync(ExceptionContext context)
        {
            _logger.LogInformation("OnExceptionAsync: " + context.Exception.Message);
            return Task.CompletedTask;
        }
    }
```

2. Call the `Dummy` endpoint with `?throw=true`.
3. Notice that `OnActionExecutionAsync` is executed, but `OnExceptionAsync` is not.

### Further technical details
- ASP.NET Core version : 3.1
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version : VS 2019 16.4.1

**Comment by pranavkm** [comment]
Controllers specifically supports action filters, which would explain  why exception filters do not work. You could however annotate the controller with a filter attribute:

```C# 
[ApiController]
[Route("[controller]")]
[MyExceptionFilter]
public class DummyController : ControllerBase
{
   ...
}

public class MyExceptionFilterAttribute : Attribute, IAsyncExceptionFilter
{
    public Task OnExceptionAsync(ExceptionContext context)
    {
        _logger.LogInformation("OnExceptionAsync: " + context.Exception.Message);
        return Task.CompletedTask;
    }
}
```

**Comment by thomaslevesque** [comment]
@pranavkm thanks.

> Controllers specifically supports action filters

Is this documented somewhere?

> You could however annotate the controller with a filter attribute

Yes, that's what I did

**Comment by pranavkm** [comment]
The way we expect users to use it is by overriding methods on `Controller` which is documented to an extent- 
 https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controller.onactionexecutionasync?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_Controller_OnActionExecutionAsync_Microsoft_AspNetCore_Mvc_Filters_ActionExecutingContext_Microsoft_AspNetCore_Mvc_Filters_ActionExecutionDelegate_

The fact that implementing action filters on controllers works isn't specifically called out, but we'd be happy to accept an update to the documentation https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#action-filters if that's something you'd be interested in.

**Comment by thomaslevesque** [comment]
> The way we expect users to use it is by overriding methods on `Controller`

Yes, but if you use the `ControllerBase` class, there's no such method to override...

Anyway, since it's not a bug, I'll close this issue.

**Comment by rynowak** [comment]
A few details for anyone curious....

> Yes, but if you use the ControllerBase class, there's no such method to override...

These methods are present on `Controller` but not `ControllerBase` on purpose. There is overhead in the framework simply because these methods exist, we have to call them and allocate extra objects. For this reason we put them on `Controller` for compat, and elided them from` ControllerBase`.

> It works fine for some filters (e.g. IAsyncActionFilter). But for others (e.g. IAsyncExceptionFilter), it doesn't: the filter is never invoked.

We support action/result filters because they are the most commonly used filter types. Legacy MVC supports exception filters here, but we didn't do it because they are really rarely used in core (we recommend middleware).

 We also don't support resource filters here, because that wouldn't make sense. Resource filters execute **before** the controller is created.

**Comment by thomaslevesque** [comment]
@rynowak thanks for the explanations!
