### ISSUE TITLE
Razor VSCode tooling: Go to Definition on Injected property throws an exception

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#17867]
Repro:
1. Create an injected property in a .razor file.
1. Use the property later on in the file.
1. Go to Definition on the use of the property.
1. You'll get an error about failing to open a `__virtual` file.

CC @NTaylorMullen who found this.

**Comment by ajaybhargavb** [comment]
Taking this

**Comment by ajaybhargavb** [comment]
Fixed by https://github.com/OmniSharp/omnisharp-vscode/pull/3468
