### ISSUE TITLE
How to inject dependencies?

### ISSUE THREAD

**Issue by eavonius** [aspnet/AspNetCore#17868]
It appears there's no generic version of options.Conventions.AddFolderApplicationModelConvention or options.ConfigureFilter. Is there a way to get a hold of the service container within filters, or do we need to create a scope in Startup.cs (hack if you ask me) and pass dependencies in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-3.1#implement-razor-page-filters-globally)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rynowak** [comment]
@eavonius - you can use `TypeFilterAttribute` or `ServiceFilterAttribute` for this. Choose between these depending on whether your filter itself is registered in DI (service filter) or just wants to access DI (type filter)

- https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.servicefilterattribute?view=aspnetcore-3.1
- https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#servicefilterattribute
- https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.typefilterattribute?view=aspnetcore-3.1
- https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#typefilterattribute


`TypeFilterAttribute` is what `options.Filters.Add(Type)` from MVC does behind the scenes. https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Filters/FilterCollection.cs#L89
