### ISSUE TITLE
There is no -v switch

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore#17865]
@doggy8088 commented on [Thu Dec 12 2019](https://github.com/aspnet/AspNetCore.Docs.zh-tw/issues/132)

There is no `-v` switch in `Microsoft.dotnet-openapi 3.1.0`.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 653e14ef-227e-a165-0360-2f59259e16c6
* Version Independent ID: e4685d05-e874-76a3-9780-66b864eca6c1
* Content: [使用 OpenAPI 開發 ASP.NET Core 應用程式](https://docs.microsoft.com/zh-tw/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/Microsoft.dotnet-openapi.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/web-api/Microsoft.dotnet-openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ryanbrandenburg
* Microsoft Alias: **rybrande**

---

@srvbpigh commented on [Thu Dec 12 2019](https://github.com/aspnet/AspNetCore.Docs.zh-tw/issues/132#issuecomment-565067797)

Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is a mistake in the docs and we're fixing it as part of https://github.com/aspnet/AspNetCore/issues/17826 issue.
