### ISSUE TITLE
Static assets configuration in netstandard2.1

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#17879]
How to enable the static assets reference in .net standard 2.1 project file for blazor wasm project.

**Support for static assets in libraries when publishing
Standalone Blazor WebAssembly apps now support static assets from Razor class libraries both during development and when publishing. This applies to both standalone Blazor WebAssembly apps and ASP.NET Core hosted apps. Static assets are consumed from referenced libraries using the path prefix: _content/{LIBRARY NAME}/.**  -> how to achieve it. 

### Additional context

i am using latest 3.1 sdk with latest wasm cli

**Comment by kmuthukumar23** [comment]
Hi @pranavkm , 

Any updates?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear what you think doesn't work here. Please provide more details about your scenario, what you expect to happen and what doesn't work.
