### ISSUE TITLE
TryUpdateModelAsync not working in ASP․NET Core 3.1

### ISSUE THREAD

**Issue by doggy8088** [aspnet/AspNetCore#17876]
### Describe the bug
The `TryUpdateModelAsync` not working as expected in ASP․NET Core 3.1.

### To Reproduce

1. Setup demo project

    ```sh
    git clone https://github.com/doggy8088/TryUpdateModelAsyncProblem.git
    cd TryUpdateModelAsyncProblem
    dotnet run
    ```

2. Send HTTP request to the demo action

    ```sh
    curl --location --request POST 'https://localhost:5001/WeatherForecast' --header 'Content-Type: application/json' --data-raw '{"Date": "2019-12-01", "TemperatureC": 1, "Summary": "N/A"}' -k -D -
    ```

The `TryUpdateModelAsync` should do the manual model binding under the hood. If I use `[FromBody]` in the parameter of the Action, it works. I'm trying to do the manual model binding in the action, but failed.

Here is the code snippet of the demo code:

```cs
[HttpPost]
public async Task<IActionResult> PostAsync()
{
	var value = new WeatherForecast()
	{
		Date = DateTime.Parse("2019-12-14"),
		TemperatureC = 100,
		Summary = ""
	};

	if (await TryUpdateModelAsync(value, ""))
	{
		return CreatedAtAction("Get", value);
	}
	else
	{
		return BadRequest();
	}
}
```

The original `value`'s `Date` property is `2019-12-14`. When I do the request, I pass a new `Date` as `2019-12-01`. So the expected result should be: 

```txt
HTTP/2 201
date: Sat, 14 Dec 2019 11:19:38 GMT
content-type: application/json; charset=utf-8
location: https://localhost:5001/WeatherForecast
server: Kestrel

{"date":"2019-12-01T00:00:00+08:00","temperatureC":1,"temperatureF":33,"summary":"N/A"}
```

But the actual result is: ( The `TryUpdateModelAsync` is not working. )

```txt
HTTP/2 201
date: Sat, 14 Dec 2019 11:19:38 GMT
content-type: application/json; charset=utf-8
location: https://localhost:5001/WeatherForecast
server: Kestrel

{"date":"2019-12-14T00:00:00+08:00","temperatureC":100,"temperatureF":211,"summary":""}
```

### Further technical details
- ASP.NET Core version: `3.1`
- Include the output of `dotnet --info`: See below
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: `VSCode 1.39.2`

```txt
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  2.1.802 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by doggy8088** [comment]
It looks like ASP․NET Core missing a [JsonValueProviderFactory](https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.jsonvalueproviderfactory?view=aspnet-mvc-5.2) implementation.

**Comment by doggy8088** [comment]
If I use the following cURL request, then it works fine. It use `application/x-www-form-urlencoded` content-type in the HTTP request.

```sh
curl --location --request POST 'https://localhost:5001/WeatherForecast' --header 'Content-Type: application/x-www-form-urlencoded' --data-raw 'Date=2019-12-01&TemperatureC=1&Summary=N/A' -k -D -
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. @javiercn can you please look into this? Thanks!

**Comment by kishanAnem** [comment]
Hi @doggy8088 

I’ve tried to understand this bug.
As mentioned in the attached bug and post.
It is by design we aren’t  supporting application/Json content type for POST.

- TryUpdateModelAsync is using value providers and checking can we read from query or HasFormContentType

- [Frombody] using input formaters using JsonSerializer.DeserializeAsync binding the model.
Framework supported media types are application/json , text/json , and text/plain.

With these points I’m feeling it isn’t a bug...
Correct me if am wrong..

//cc @dougbu @mkArtakMSFT @pranavkm

**Comment by doggy8088** [comment]
@kishanAnem It works in ASP․NET MVC 5. So I expected it should works in ASP․NET Core.

**Comment by kishanAnem** [comment]
@doggy8088 yeah it’s right working MVC 5. In Asp.net community standup I think @DamianEdwards said “ removed that feature consciously”.

**Comment by pranavkm** [comment]
Thanks @kishanAnem for the investigation. This is not a feature ASP.NET Core MVC has. https://github.com/aspnet/Mvc/issues/5659#issuecomment-270717629 goes in to some details as to why along with possible solutions to this.

**Comment by denis-pujdak-adm-it** [comment]
I am not happy with the answer. Why cannot we do something like `TryUpdateModelAsync()` and read the Json?
Don't we have the ContentType = 'application/json'? And `POST` ??? What is going on with the AspNet? Should I look for different server side framework?
