### ISSUE TITLE
Asp.net core model binder gets objects as null

### ISSUE THREAD

**Issue by merkancam** [aspnet/AspNetCore#17884]
Hello, 

I am posting json data using angularJs and asp.net core gets it as null. Because i have an object that contains integer field. It is string on js side. When i post it without parsing to int, Asp.net core gets it as null. I have to convert all my fields according to type in c# on client side. I was not having this issue while i was using mvc 5.  It was converting string to int or just the opposite and getting the object properly.

Here is the object.

```
public class AddReportModel : BaseModel
    {
        public int BookId { get; set; }
        public byte PageCount { get; set; }
        public DateTime Date { get; set; }
        public string Note { get; set; }
      
    }
```

Here is the method. 

```
    [HttpPost]
        public IActionResult AddUserReport([FromBody]AddReportModel model)
        {
            //model.Validate();
            
            var response = _reportBusiness.AddReport(new AddReadingLogRequest()
            {
                BookId = model.BookId,
                Date = model.Date,
                Note = model.Note,
                PageCount = model.PageCount
            });

            return Json(response);
        }

```
Here is how I post my object to asp.net core application. 

```
  CreateReport: function (model) {
            return $http.post('/Report/AddUserReport', JSON.stringify(model), {
                headers: {
                    'Content-Type': 'application/json; charset=utf-8'
                },
             
        

            });
        },
```

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
