### ISSUE TITLE
Can I create a middleware in Blazor Server App in order to have access to the users claims ?

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#17895]
I'm asking this question since I've read that the HttpContext is not available in server-side applications.

Thanks...

**Comment by MV10** [comment]
You can access the claims by injecting `AuthenticationStateProvider` ... for [example](https://github.com/MV10/BlazorOIDC/blob/master/ClientSite/Pages/Index.razor)

The hard part is getting OIDC auth working (which isn't impossible, fortunately, although it requires a lot of DIY).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @enetstudio.
@MV10 's suggestion is one way to do this. Hope that helps.
In general, the statement you're referring to is correct, you shouldn't depend on HttpContext in Blazor Server apps.

**Comment by enetstudio** [comment]
@mkArtakMSFT,  I know perfectly well how to handle and manipulate AuthenticationStateProvider and all the related components. I also believe I know that I can access the HttpContext  in middleware and access the user's claims, but only once when the SignalR connection starts, and then the HttpConext is no longer available... I need the assurance that I'm right... that it is doable and proper to access the HttpContext that way. Thanks...
