### ISSUE TITLE
[Blazor] Saving circuit state

### ISSUE THREAD

**Issue by JohnKiller** [aspnet/AspNetCore#17899]
Every tutorial I've read on the topic saved the user session, not the circuit.

For example, imagine having an application for creating quotes and adding them to a shopping cart.

While the cart is easy to solve since is tied to the browser (or user, if logged in) session, the quote instead may be tied to the circuit. A user may wish to create multiple quotes on different tabs, and you need to handle reconnection.

There is the `CircuitHandler` class you can use to get the circuit id, but how do you access that inside a component?

Or if I'm using a central store class, how does the class know which circuit is currently handling?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We have documented State Management topic in detail, it should help to resolve your question: https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1

We recommend storing your quotes using one of the techniques listed in the docs above.

**Comment by JohnKiller** [comment]
Hi, thanks for answering me. I've read that document before opening this issue. It does answer how to store user data like a session would. But it doesn't cover handling circuit id.

How do you distinguish one circuit from another? How do you distinguish a quote opened on a tab and the other?

Hope it's more clear my request.
Thanks for your patience
