### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).

### ISSUE THREAD

**Issue by pandiyarajm93** [aspnet/AspNetCore#17893]
### Describe the bug
When making PostJsonAsync<T> call from blazor client app to server-side app controller logic completely executed while return data to client getting following error

System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).

### To Reproduce
1. Create Blazor ASP Core Hosted application
2. Make PostAsync<T> request from **client app** to execute **server app** **_controller_** method logic

Getting below-console error

System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).

### Further technical details
- ASP.NET Core version - 3.1

#### client - index.razor

`
      @inject HttpClient Http

     <button class="btn btn-primary" @onclick="@Export">Export as PDF</button>

     <EjsRichTextEditor @ref="RteObj" @bind-Value="@rteValue">
      </EjsRichTextEditor>

    private async Task Export()
    {
        try
        {
            ContentModel value = new ContentModel() { Value = this.Value };

            ResponseModel response = await Http.PostJsonAsync<ResponseModel>("api/Export/ExportFile", value);

            Console.WriteLine(response.ToString());

        }
        catch (Exception e)
        {
            ContentModel value = new ContentModel() { Value = this.Value };

            Console.WriteLine(e.ToString());

        }
    }
`

#### Server controller - ExportController.cs

`
         [HttpPost]

         [Route("ExportFile")]

         public JsonResult ExportFile(ContentModel content)

         {

            try

            {

                MemoryStream stream = new MemoryStream();

                JsonResult result = new JsonResult(new ResponseModel { Value = stream });

                result.StatusCode = 200;

                result.ContentType = "application/json";

                return result;

            }

            catch

            {

                MemoryStream stream = new MemoryStream();

                JsonResult result = new JsonResult(new ResponseModel { Value = stream });

                result.StatusCode = 200;

                result.ContentType = "application/json";

                return result;

            }

        }
`

#### Screenshot:

![image](https://user-images.githubusercontent.com/54373337/70862169-d1795c80-1f5e-11ea-87dc-6c8119924712.png)

**Comment by pandiyarajm93** [comment]
I can return int value from server controller to client page. If I return getting following console error in my application


`
WASM: ﻿---------------------------------------------------------- Error Log -----------------------------------------
blazor.webassembly.js:1 WASM: System.Text.Json.JsonException: 'S' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: 'S' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
blazor.webassembly.js:1 WASM:   at System.Text.Json.ThrowHelper.ThrowJsonReaderException (System.Text.Json.Utf8JsonReader& json, System.Text.Json.ExceptionResource resource, System.Byte nextByte, System.ReadOnlySpan`1[T] bytes) <0x21f16d8 + 0x00020> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at System.Text.Json.Utf8JsonReader.ConsumeValue (System.Byte marker) <0x1eb19f0 + 0x00260> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at System.Text.Json.Utf8JsonReader.ReadFirstToken (System.Byte first) <0x1eb1078 + 0x001ae> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at System.Text.Json.Utf8JsonReader.ReadSingleSegment () <0x1eb0a70 + 0x001fe> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at System.Text.Json.Utf8JsonReader.Read () <0x1eac5e8 + 0x0000e> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at System.Text.Json.JsonSerializer.ReadCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x1eabf70 + 0x0005e> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:    --- End of inner exception stack trace ---
blazor.webassembly.js:1 WASM:   at System.Text.Json.ThrowHelper.ReThrowWithPath (System.Text.Json.ReadStack& readStack, System.Text.Json.JsonReaderException ex) <0x2244198 + 0x00108> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at System.Text.Json.JsonSerializer.ReadCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x1eabf70 + 0x00292> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at System.Text.Json.JsonSerializer.ReadCore (System.Type returnType, System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader) <0x1eab340 + 0x0002e> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at System.Text.Json.JsonSerializer.Deserialize (System.String json, System.Type returnType, System.Text.Json.JsonSerializerOptions options) <0x1ea80a8 + 0x0017a> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at System.Text.Json.JsonSerializer.Deserialize[TValue] (System.String json, System.Text.Json.JsonSerializerOptions options) <0x1ea7e78 + 0x0000c> in <9216f7c6e32c4e449c022b46f111ee2d>:0 
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.SendJsonAsync[T] (System.Net.Http.HttpClient httpClient, System.Net.Http.HttpMethod method, System.String requestUri, System.Object content) <0x2105ae8 + 0x00208> in <393f0d2066e842d38b0e8ac688095cf7>:0 
blazor.webassembly.js:1 WASM:   at HostedSample.Client.Pages.Index.SubmitData () [0x00050] in C:\Users\PandiyarajMuniyandi\source\repos\HostedSample\Client\Pages\Index.razor:15 
`


![image](https://user-images.githubusercontent.com/54373337/70863148-160af500-1f6b-11ea-851f-bba23ff30dfd.png)



Here I attached the sample to reproduce the issue from your end.
[HostedSample.zip](https://github.com/aspnet/AspNetCore/files/3964944/HostedSample.zip)

_**Note:** i am new to use the http request concept_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@pranavkm can you please look into this? Thanks!

**Comment by pranavkm** [comment]
This looks like an issue with the data that you're posting. System.Text.Json is fairly strict about converting strings to other data types. In this case, it looks like you're posting a string value to a value that is read as a int. Consider modifying the JSON that is being posted or read the value as a string.
