### ISSUE TITLE
can not read body stream, Request.Body.length =0

### ISSUE THREAD

**Issue by gitlsl** [aspnet/AspNetCore#17902]
### Describe the bug
can not read body steam
### To Reproduce
 
``` C#
    [ApiController]
    [Route("[controller]/[action]")]
    public class WeatherForecastController : ControllerBase
    {
        [HttpPost]
        public async Task<string> Encode([FromBody]string xx)
        {
            var body = "test";
            Request.EnableBuffering();
            using (var reader = new StreamReader(Request.Body, encoding: Encoding.UTF8))
            {
                body = await  reader.ReadToEndAsync();
                Request.Body.Position = 0;
            }
            return body;
        }
    }
```
I want to read http body as string.
but in my test, Request.Body.length  always is  0;so it get empty result
may be you can give a method  like ` Request.BodyAsString` ,it is a useful feature

### Further technical details
- ASP.NET Core version  3.1.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gitlsl.
@pranavkm can you please look into this? Thanks!

**Comment by pranavkm** [comment]
@gitlsl you'll have to read the request body before MVC has had read it. Here's an example that shows this: https://github.com/aspnet/AspNetCore/issues/15009#issuecomment-542291956. https://github.com/aspnet/AspNetCore/issues/15009#issuecomment-542444635 has an explanation as to why this behavior changed between 2.x and 3.x.
