### ISSUE TITLE
ASP.NET Core integration test project template

### ISSUE THREAD

**Issue by leotsarev** [aspnet/AspNetCore#17906]
I am trying to follow https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests

It will be useful if VS contains project template for integration testing that correctly references everything. It could be non-buildable by default (you have to add SUT project reference), but other than that, it could be just:
- Create from template
- Reference SUT
- Some namespace fixing

and yes, you have "hello world test app". May be it could even have 1 test that tests "/healthcheck"

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We haven't heard enough feedback from the community regarding this.
However, it's possible for community members to publish project templates as NuGet packages on their own and this will be a perfect fit for that: https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates
