### ISSUE TITLE
[Blazor server side] Cannot open site more than ~10 times at the same time when deployed to IIS

### ISSUE THREAD

**Issue by jaryn-kubik** [aspnet/AspNetCore#17907]
### Describe the bug
I thought this was something in my app but I've tried it with the default .NET Core 3.1 Blazor server side template app (hello word/counter/fetch) and I'm getting the same behavior.

When I deploy the app to my local IIS and try opening it in multiple tabs in the browser at the same time at some point (10+tabs) a new tab just doesn't load. It just keeps loading, in dev tools network tab i can see it's waiting for a response from the server, but it never happens. If I close one of the previous tabs (that worked) the new one (that was stuck) now resumes and finishes loading just fine.

- the number of tabs it can handle at the same times is different with my app (8) a the default template (10).
- it's not browser related, i've tried it in various different ones, even on multiple pc's (open 5 on one pc, open 5 on another pc, 11th opened anywhere doesn't load)
- i've tried it in my colleague's IIS and now at home where i installed IIS from scratch, same behavior
- i've tried building it in debug/release, no difference
- when i run the app in VS (=IIS Express) or just by running the exe i can open hundreds of tabs no problem, it's just on IIS where it doesn't work
- i've read and followed stuff around https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1, fiddled with various IIS settings, no joy
- i'm nowhere near running out of memory

There seems to be something somewhere limiting the number of concurrent connections when deployed on IIS and 10 seems to be like an extremely low number, I feel like there has to be some step/setting i've missed or something because it cannot possibly be right.

I've added logging with serilog to the default template if that somehow helps:
- [test.log](https://github.com/aspnet/AspNetCore/files/3969271/test.log)
- 2019-12-16 17:36:51.507 is where i open the 11th tab that just hangs, it clearly starts doing something but never finishes
- 2019-12-16 17:38:12.970 is where i close some previous tab and the 11th now resumes and finishes loading

### To Reproduce
- build/publish/deploy default blazor server side template to IIS (10.0 on W10)
- start opening the app in new tabs (while keeping the old tabs open) until it stops loading

**Comment by pranavkm** [comment]
Might be the limitation that's described here: https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/supported-platforms#supported-server-iis-versions. What flavor of Windows 10 are you on?

/cc @jkotalik

**Comment by jaryn-kubik** [comment]
I see, thanks.
I'm running Windows 10 Pro 1903, I just tried it on our test server running Windows Server 2019 and it indeed works fine.

I kinda feel like it should be mentioned somewhere closer to blazor server side documentation as this makes it practically unusable on non-server Windows. Most (all?) of the SignalR mentions lead to the Core version and this limitation seems to be only listed on the non-Core version.
