### ISSUE TITLE
ASP.NET Core 3.0 deserialize datetime not like Newtonsoft.Json?

### ISSUE THREAD

**Issue by hueidou** [aspnet/AspNetCore#17903]
### Describe the bug
When the model have a datetime property and json-value '2019-1-1', ASP.NET Core 3.0 deserialize it to null.

### To Reproduce

``` C#
# action
public void Post([FromBody] Model1 model1)

public class Model1
{
    public DateTime? CreateTime { get; set; }
}
```

```json
{
    "createTime": "2019-1-1"
}
```

* By the code above, the model1 will be null. 
* When I change `services.AddControllers()` to `services.AddControllers().AddNewtonsoftJson()`, the model1 is correct.
* `"createTime": "2019-01-01"` works well both two way.

**Comment by khellang** [comment]
That's just how the new serializer works; it only accepts valid ISO8601-formatted dates, i.e. `YYYY-MM-DD` where `YYYY` indicates a four-digit year, 0000 through 9999. `MM` indicates a two-digit month of the year, 01 through 12 and `DD` indicates a two-digit day of that month, 01 through 31.

What you're passing is not a valid ISO8601 date and needs a custom converter to work. Here's an example of a converter for a custom date format; https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to#sample-basic-converter

**Comment by hueidou** [comment]
@khellang I See. Thank you.

**Comment by hueidou** [comment]
@khellang But why "2019-1-1" deserialize to `[FromQuery]DateTime createTime` is correct?

**Comment by khellang** [comment]
> But why "2019-1-1" deserialize to `[FromQuery]DateTime createTime` is correct?

That's because `DateTime` query values are converted using `DateTimeConverter`, [which uses `DateTime.Parse`](https://github.com/dotnet/runtime/blob/4359ebfc9943608b34f411366b1e544ac45702b7/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/DateTimeConverter.cs#L39-L75) and isn't as strict as the JSON serializer. If you want the same behavior, you need to do the same in your custom converter.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
