### ISSUE TITLE
Blazor/ServerRendering: Child Component does not render page property in the way I would expect.

### ISSUE THREAD

**Issue by RealOrko** [aspnet/AspNetCore#17913]
### Describe the bug

A child component in blazor is not rendering a property that is set from a parent page. It wont even compile in my sample and even then it does not work in my parent project when it does compile.

Why is this not simple?
Why dont the docs reflect the "right way"?

Not sure what I am doing wrong here but the docs are telling me I have done everything right. What have I done wrong? Any help here would be much appreciated. 

### To Reproduce

```
git clone git@github.com:RealOrko/aspnet-blazor-component-rendering-issue.git
cd aspnet-blazor-component-rendering-issue
dotnet restore
dotnet build
dotnet run
```

### Further technical details

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     fedora
 OS Version:  31
 OS Platform: Linux
 RID:         fedora.31-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

GHLink: https://github.com/RealOrko/aspnet-blazor-component-rendering-issue

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
