### ISSUE TITLE
Unable to delete assembly file after plugin uninstall

### ISSUE THREAD

**Issue by zengqinglei** [aspnet/AspNetCore#17916]
**Describe the bug**

When I use the sample code: https://github.com/dotnet/samples/tree/master/core/tutorials/Unloading
Then I want to remove the assembly file after the plugin is uninstalled and I get an exception:

![image](https://user-images.githubusercontent.com/7374317/70961451-cb998d80-20bc-11ea-837c-601b70c8e52a.png)

**Run Environment**
* .NET CORE 3.1
* Windows 10 
![image](https://user-images.githubusercontent.com/7374317/70961722-a8231280-20bd-11ea-852a-eb42a443ac45.png)

Thanks in advance to the .net core team for answering my questions. Thank you!

**Comment by javiercn** [comment]
@zengqinglei thanks for contacting us.

We believe this issue is not related to ASP.NET and you will get a faster and better response by filing an issue in [the dotnet runtime repository](https://github.com/dotnet/runtime).

/cc: @davidfowl as you were interested in knowing about these things.

**Comment by zengqinglei** [comment]
> @zengqinglei thanks for contacting us.
> 
> We believe this issue is not related to ASP.NET and you will get a faster and better response by filing an issue in [the dotnet runtime repository](https://github.com/dotnet/runtime).
> 
> /cc: @davidfowl as you were interested in knowing about these things.

ok,thank you !
