### ISSUE TITLE
Warning: The variable '__typeHelper' is assigned but its value is never used

### ISSUE THREAD

**Issue by caioproiete** [aspnet/AspNetCore#17911]
A Blazor Server app (default template) displays a warning that cannot be resolved by the user:

```
The variable '__typeHelper' is assigned but its value is never used
```

![image](https://user-images.githubusercontent.com/177608/70933566-9a648300-2012-11ea-95ff-9304a4ecd27a.png)

### To Reproduce

File -> New Project -> Blazor App -> Blazor Server App

Rebuild the app.

---

- ASP.NET Core version 3.1
- Visual Studio 219 16.4.1

![image](https://user-images.githubusercontent.com/177608/70933855-119a1700-2013-11ea-9a3b-329d786ba757.png)

- `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by NTaylorMullen** [comment]
Hmm, i'm unable to reproduce. @caioproiete do you happen to have any VS extensions installed or settings assigned related to C# warnings? I ask because I haven't seen that behavior of putting a green squiggle on the folder when warnings occur with a default VS install.

**Comment by caioproiete** [comment]
@NTaylorMullen Yes, the green squiggle on the screenshot was being shown by one of the [Power Commands for Visual Studio](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.PowerCommandsforVisualStudio) extensions, the [Solution Error Visualizer](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.SolutionErrorVisualizer).

It looks like it might be a bug in the extension as I cannot reproduce it on a clean install of Visual Studio, so closing for now. Thanks for checking and sorry to waste your time!
