### ISSUE TITLE
Explanation fails at the beginning

### ISSUE THREAD

**Issue by Ricardoaraujo00** [aspnet/AspNetCore#17928]
I've added the Microsoft.AspNetCore.Server.Kestrel.Core to the used libraries but in this code:
```
 public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<KestrelServerOptions>(Configuration.GetSection("Kestrel"));
            services.AddGrpc();
        }
```
"Configuration" gets undelined saying it does not exist in current context...

**Comment by javiercn** [comment]
@Ricardoaraujo00 thanks for contacting us.

You are likely missing the generic parameter on that method `services.Configure<KestrelServerOptions>(...)`

**Comment by Ricardoaraujo00** [comment]
> @Ricardoaraujo00 thanks for contacting us.
> 
> You are likely missing the generic parameter on that method `services.Configure<KestrelServerOptions>(...)`

Thanks Javier, if it misses me, it misses in the explanation. Where is that generic parameter missing in the explanation?

**Comment by javiercn** [comment]
@Ricardoaraujo00 what explanation are you referring to? Do you mean the XML doc comments?

**Comment by Tratcher** [comment]
> You are likely missing the generic parameter on that method `services.Configure<KestrelServerOptions>(...)`

@javiercn no, it's there, but the HTML ate it.

@Ricardoaraujo00 Where did you get that code sample? What are you tying to configure on KestrelServerOptions? The complete version would look something like:

```
public class Startup
{
  public Startup(IConfiguration configuration)
  {
    Configuration = configuration;
  }
  public void ConfigureServices(IServiceCollection services)
  {
    services.Configure<KestrelServerOptions>(Configuration.GetSection("Kestrel"));
    services.AddGrpc();
  }
}
```

**Comment by Ricardoaraujo00** [comment]
@javiercn @Tratcher  The explanation in this site:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1

points to this repository, at the bottom.

My version is a bit different

> public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services) 
        {

            services.AddGrpc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGrpcService<GreeterService>();

                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
                });
            });
            app.UseEndpoints(endpoints =>
            {
                

                endpoints.MapGet("/hello", async context =>
                {
                    await context.Response.WriteAsync("Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
                });
            });
        }
    }

**Comment by javiercn** [comment]
@Ricardoaraujo00 thanks for the information.

This is a doc bug it seems. It is best if you file it directly on the docs page itself (at the bottom) as that creates an issue that it is tied to the exact document and it is highly visible to our doc writers (which are the ones who update this content).

/cc: @Rick-Anderson

**Comment by Tratcher** [comment]
The kestrel doc with that code sample precedes it with a text description for setting up Configuration:
```
Configure Kestrel in Startup.ConfigureServices:

Inject an instance of IConfiguration into the Startup class. The following example assumes that the injected configuration is assigned to the Configuration property.

In Startup.ConfigureServices, load the Kestrel section of configuration into Kestrel's configuration.
```

The doc is accurate, but expanding the code sample might be clearer.

@Ricardoaraujo00 you should be able to add the code from that sample to your app if you follow the text instructions first. Those instructions match the sample I gave above.

**Comment by Ricardoaraujo00** [comment]
Certainly the problem is mine because i'm not pro enough. Sure you guys have no problems understanding where to place this and that, and how to use this code for this action, or another code for another action. I just think if this explanation where a lot simpler it would be understandable both by pro and beginners.

I just want to do a simple thing. Expose my aspnet core gRPC service to the outside(stuck on localhost). Isn't there a simple or understandable explanation on how to do just that?

**Comment by Tratcher** [comment]
Where you able to apply the sample code I gave above? https://github.com/aspnet/AspNetCore/issues/17928#issuecomment-566666011

What do you have in your appsettings.json file? (that's what Configuration reads).
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#configureiconfiguration

When exposed publicly, are you planning to use http or https? Using https will require creating your own certificate. 

appsettings.json with http exposed publicly:
```
{
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://*:5000"
      }
    }
  }
}
```

With https:
```
{
  "Kestrel": {
    "Endpoints": {
      "Https": {
        "Url": "https://*:5001",
        "Certificate": {
          "Path": "<path to .pfx file>",
          "Password": "<certificate password>"
        }
      }
    }
  }
}
```

**Comment by Ricardoaraujo00** [comment]
@Tratcher i have the standard settings. What you have there is very different from what Visual Studio made from the gRPC service template. What i have is this:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
}
```

So, i have to replace everything that i have in appsettings.json file(it is in the project root folder) with your https version.
Then have to publish and simply copy what is in the publish folder to some folder in c: due to permissions right? Then just execute the application .exe and it showld be acessible from a client on another pc, right?

**Comment by Tratcher** [comment]
Try it and see how far you get.

> Then have to publish and simply copy what is in the publish folder to some folder in c: due to permissions right?

What permissions issues? It shouldn't matter where you run the app from.

Additional steps:
- Create your own certificate. https://www.petri.com/create-self-signed-certificate-using-powershell
- Open firewall ports - https://www.tomshardware.com/news/how-to-open-firewall-ports-in-windows-10,36451.html

**Comment by Ricardoaraujo00** [comment]
Tank you for your time @Tratcher .
Unfortunately, that way to generate a certificate throws an error on the final command(yes, i've created the temp folder). Either way i generated a certificate with the IIS.

```
{
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    },
    "Endpoints": {
      "Https": {
        "Url": "https://*:5001",
        "Certificate": {
          "Path": "<G:\\iiscert.pfx>",
          "Password": "<sri>"
        }
      }
    }
  }
}
```
So i placed that code on the appsettings.json but when i run the application i always get an error that should be so obvious to fix that this is a bug or i'm really sleeping. The translated error is something like this "The name of the file sintaxt, name of folder or volume name are incorrect". Well, the name is well written, there are no doubts about the path, and for trouble shouting i even user the volume name instead the unit letter. I even copied the certificate to the publish folder so i dindn't use a path at all. Nothing works.
I remember  i used something like the following code in program.cs but i can's find the real code i used as it didin't worked.
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureKestrel((context, options) =>
                {      
                       serverOptions.Listen(IPAddress.Any, 8000, listenOptions =>
                        {
                                    listenOptions.UseHttps("testCert.pfx", "testPassword");
                         });
                 });             
                
```
Seems that was another way of configuring kestrel.
I've also opened the firewall ports, and even turned it completely down when trying the former solution.

Now my webBuilder is like this:
```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();

                });
```

Do you have any idea of what seems to throw that simple error?
Haven't anyone got this to work and has an example to show?

**Comment by Tratcher** [comment]
Try it without the angle brackets.
```
{
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    },
    "Endpoints": {
      "Https": {
        "Url": "https://*:5001",
        "Certificate": {
          "Path": "G:\\iiscert.pfx",
          "Password": "sri"
        }
      }
    }
  }
}
```

**Comment by Ricardoaraujo00** [comment]
Hi @Tratcher 
What a fail. Of course i can't use the anlge brackets. But it didn't work either. My internship tutor came on rescue and he used this:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    },
    "EndPoints": {
      "Https": {
        "Url": "https://192.168.5.49:5001",
        "Certificate": {
          "Path": "c:\\test.pfx",
          "Password": "password1234"
        }
      }
    }
  }
}
```
... and it works!!

But as i have only a powershell generated certificate i must use the following code on the client:
                ```
var httpClientHandler = new HttpClientHandler();
                // Return `true` to allow certificates that are untrusted/invalid
                httpClientHandler.ServerCertificateCustomValidationCallback =
                    HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
                var httpClient = new HttpClient(httpClientHandler);
                var channel = GrpcChannel.ForAddress("https://192.168.5.28:5001"
                    ,new GrpcChannelOptions { HttpClient = httpClient });

                var client = new QueueManagement.QueueManagementClient(channel);
```
