### ISSUE TITLE
MapAreaControllerRoute does not work with optional controller action

### ISSUE THREAD

**Issue by andrew-vdb** [aspnet/AspNetCore#17924]
```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapAreaControllerRoute("admin", "admin", "admin/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");               
               
            });


```
**Actual**
/admin ---> not working ! 
/admin/Home/Index ---> working

**Expected**
/admin ---> working
/admin/Home/Index ---> working

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by andrew-vdb** [comment]
[WebApplication2.zip](https://github.com/aspnet/AspNetCore/files/3977726/WebApplication2.zip)

**Comment by pranavkm** [comment]
The `IndexController` in your area is attribute routed - `[Route("Admin/[controller]")]` which explains why the default route from your Startup isn't used

**Comment by andrew-vdb** [comment]
thanks its working
