### ISSUE TITLE
Blazor client side Unable to find a default constructor to use for type System.IdentityModel.Tokens.Jwt.JwtPayload.

### ISSUE THREAD

**Issue by partyelite** [aspnet/AspNetCore#17920]
### Describe the bug
I'm using blazor client side and System.IdentityModel.Tokens.Jwt package v5.6.0.
When calling ReadJwtToken method on JwtSecurityTokenHandler I get the following exception

`Newtonsoft.Json.JsonSerializationException: Unable to find a default constructor to use for type System.IdentityModel.Tokens.Jwt.JwtPayload.`

I believe it has something to do with linker because if I add a redundant call to 
`new System.IdentityModel.Tokens.Jwt.JwtPayload()` 
in App.razor OnInitialized method it works.

I have tried adding 

 ` <assembly fullname="System.IdentityModel.Tokens.Jwt"/>`

to my Linker.xml file but that didn't help.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/linker#870
