### ISSUE TITLE
Web Application template has 15 analyzer issues (3.1)

### ISSUE THREAD

**Issue by MV10** [aspnet/AspNetCore#17931]
Creating a new project from the 3.1 Web Application template results in 15 analyzer warnings and errors in the Dependencies section of Solution Explorer. Configuration shown below (HTTPS, no Docker, no auth/identity), I didn't check other templates/configurations but I imagine results would be similar. Double-clicking them doesn't lead anywhere (I don't know for sure that would work) so I'm guessing it's something in the SDK rather than the template code itself.

VS 2019 16.4.1

![image](https://user-images.githubusercontent.com/794270/71020041-947da900-20c9-11ea-884f-d7925ab85018.png)

![image](https://user-images.githubusercontent.com/794270/71019990-6c8e4580-20c9-11ea-8902-22175269312a.png)

<details><summary>Expand for dotnet --info</summary><p><pre>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</pre></p></details>

**Comment by pranavkm** [comment]
That's the list of the analyzers \ code fixes being run on a project. Do you see errors on warning in the Error list as a result of running these analyzer rules?

**Comment by MV10** [comment]
I wondered if it might be, but I don't remember the yellow triangle showing, which seems to indicate something is wrong. (So perhaps my report focused on the wrong thing...)

**Comment by pranavkm** [comment]
I see the yellow triangle if I have NuGet restore in VS disabled:

![image](https://user-images.githubusercontent.com/174281/71032321-f5a57c80-20c9-11ea-9597-b1fe7b870464.png)

Do you happen to have it turned off in your VS too?

**Comment by willdean** [comment]
@pranavkm I almost always have the yellow triangles showing on all the analyzers, and I have all the Nuget stuff set to default options (Restore is certainly enabled).

I have a vague suspicion that when I create a new project, the analysers have 'nice' names (not just file paths) and no exclamations.  After a while they change to showing a file path with a yellow triangle.  That's just a feeling though.

I know this is the wrong place to complain about VS in, but it's maddening that VS can sprinkle yellow triangles all over the solution tree without any explanation of what problem they're supposed to be indicating.   It should be impossible/forbidden to add a yellow triangle without also having to supply some text somewhere to say what it's supposed to mean.  

Even just a hover tooltip would be a good start.

**Comment by MV10** [comment]
Package restore is on. I don't think I've ever had a reason to disable it, although I have a LOT of package sources (local drive, network drives, in-house servers, and public NuGet ... maybe 20 or so).

**Comment by pranavkm** [comment]
Sounds like this is a VS specific issue and not an issue with the analyzers we ship. This would be better handled as a VS feedback issue. Using the feedback tool - https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio - would include additional diagnostics that should help the relevant VS team to diagnose this.

**Comment by babarqb** [comment]
I face the above problem when I open a solution from a recent project and folder context menu and especially when a project or solution created by Rider but when I open a solution from double click then analyzer load correctly and no more analyzer issue.
