### ISSUE TITLE
Generic Parameter missing in explanation?

### ISSUE THREAD

**Issue by Ricardoaraujo00** [aspnet/AspNetCore#17930]
I've added the Microsoft.AspNetCore.Server.Kestrel.Core to the used libraries but in this code:

public void ConfigureServices(IServiceCollection services)
{
services.Configure(Configuration.GetSection("Kestrel"));
services.AddGrpc();
}

"Configuration" gets underlined saying it does not exist in the current context. 

Seems that in the explanation is missing a generic parameter. Wich generic parameter is that, and where should it be in explanation?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You're trying to reference a property (`Configuration`) which you haven't defined in your class (`Startup`).
This guide will help you with defining it: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.1
