### ISSUE TITLE
[SignalR] which one is the correct package

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17946]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/855685/signalr-which-one-is-the-correct-package.html)._

---
<p>Which one is the correct package for .net core class library project. </p> <p>and wt is the different between them, it is quite confuse.</p> <p>Microsoft.AspNetCore.SignalR</p><p>Microsoft.AspNetCore.SignalR.Core</p><p>Microsoft.AspNet.SignalR.Core</p><p>Microsoft.AspNet.SignalR</p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/109654-untitled.png">untitled.png</a></p>

---
#### Visual Studio Feedback System on 12/13/2019, 01:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Andrew Stanton-Nurse [MSFT] on 12/13/2019, 10:27 AM: 

<p>Do you want to reference the server or the client in your class library? And are you using <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core?</p>

#### Marcus Wong on 12/17/2019, 08:55 PM: 

<p>I am creating a .Net Standard 2.1 lib, and may reference both client and server side.</p>

---
### Original Solutions
(no solutions)

**Comment by anurse** [comment]
I think it would be helpful to understand your scenario here. How do you want to use SignalR in your library? The ASP.NET Core SignalR server components can't be used in a .NET Standard library, they require .NET Core. It is possible to use them from a library, but it requires .NET Core.

**Comment by halter73** [comment]
For a .net core class library project, you want the "Microsoft.AspNetCore.*" packages and not the "Microsoft.AspNet.*" packages which are for classic ASP.NET/OWIN on full framework. Beware as @anurse mentions that the 3.0 "Microsoft.AspNetCore" packages cannot be reference from libraries targeting netstandard*, but this should be a problem if you're targeting netcoreapp*

**Comment by BrennanConroy** [comment]
If are writing a class library for 3.0 or later and want to use ASP.NET Core SignalR Server libraries you can add a `FrameworkReference`. See the Microsoft.Azure.SignalR library that does this: https://github.com/Azure/azure-signalr/blob/53d2830e7dd9091af0b97113b2b843b9629d570c/src/Microsoft.Azure.SignalR/Microsoft.Azure.SignalR.csproj#L40

**Comment by leung85** [comment]
Thanks all for explanation. 
Visual Studio suggest me install Microsoft.AspNetCore.SignalR or Microsoft.AspNetCore.SignalR.Core
i try both, and both work, but wt is the different ?

**Comment by anurse** [comment]
If you're targeting .NET Core 3.0 or higher (the most recent releases of .NET Core), those packages are obsolete. They existed **only** to support ASP.NET Core 2.2 (and **earlier**) on .NET Framework.

The FrameworkReference is the only way to reference the server-side components in .NET Core 3.0 and above.

@leung85 What version of .NET Core are you intending to target?

**Comment by leung85** [comment]
@anurse  I am using .net core 3.1. 
I just create some demo projects for me to better understand the .net core , signalr and those package relationship.

I create :

- WebAPI  project which targeting .NET Core 3.1
- Class library project which targeting .standard 2.1

WebAPI  project  reference class library project. 
In that library project, i create a Hub which is used in WebAPI  project.

**Comment by anurse** [comment]
> * Class library project which targeting .standard 2.1

In this scenario you cannot reference the SignalR Server. The Server components **require** .NET Core 3.1, they do not work on .NET Standard. You can change your class library to target .NET Core 3.1 though and then add a *Framework Reference* to ASP.NET Core instead of any package references. The SignalR Server is **included** in the ASP.NET Core framework in 3.1 and **no longer available as a package**.

You can add a framework reference in your csproj file (there's no UI at the moment, as far as I'm aware). We have documentation on how to do this here: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#framework-reference

That should give you the ability to add Hubs in your class library.

**Comment by anurse** [comment]
Closing as the question has been answered.
