### ISSUE TITLE
Class Rename not process razor pages/components (VS 2019 V. 16.4.1)

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#17950]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/852664/class-rename-not-process-razor-pagescomponents-vs.html)._

---
The function that renames classes does not process the razor pages (razor components / blazor).
This problem also occurred in earlier versions of VS 2019.

---
#### Visual Studio Feedback System on 12/11/2019, 10:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
This is by design. We don't currently support refactorings on closed Razor files.
