### ISSUE TITLE
aspnetcore 3.1 SignalR invoke throw InvalidDataException

### ISSUE THREAD

**Issue by csc414** [aspnet/AspNetCore#17961]
```C#
public class LogRequest
    {
        public int Page { get; set; }

        public int Size { get; set; }

        public string KeyWords { get; set; }

        public DateTime? StartTime { get; set; }

        public DateTime? EndTime { get; set; }

        public bool? Complete { get; set; }
}

public async Task<object> GetLogs(LogRequest request)
{
}
```

Failed to invoke 'GetLogs' due to an error on the server. InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
no problem in aspnetcore 2.2.
why so simple structure not supported?

**Comment by BrennanConroy** [comment]
Could you please show the object that you are passing from the client?

One possible reason it doesn't work anymore is that you are actually passing a string for `Size` and System.Text.Json will not convert a string to an int for you, whereas Newtonsoft.Json will.

If you want to switch back to using Newtonsoft.Json you can do so by following the directions at https://docs.microsoft.com/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#switch-to-newtonsoftjson

**Comment by csc414** [comment]
I already changed Newtonsoft.Json.
I think the reason is probably i passing a string for bool.
I don't know System.Text.Json is so strict, thanks for your answer.
