### ISSUE TITLE
Blazor — Passing object to sibling component

### ISSUE THREAD

**Issue by vintzl** [aspnet/AspNetCore#17965]
I am not sure if this is due to a lack of documentation, or there is some missing feature, but I have found a not really related question here:
- https://github.com/dotnet/docs/issues/16001

and a similar unanswered question on SO:
- https://stackoverflow.com/questions/58276236/passing-object-between-siblings-components

and I am still looking for a solution. What fallows come from the above mentioned question in SO.

---

Say I have a first component like this:

    <EditForm Model="@forecasts" OnValidSubmit="@HandleValidSubmit">
        <DataAnnotationsValidator />
        <ValidationSummary />
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Date</th>
                    <th>Temp. (C)</th>
                    <th>Temp. (F)</th>
                    <th>Summary</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var forecast in forecasts)
                {
                    <tr>
                        <td><NavLink href="@($"/Edit/")">@forecast.Id</NavLink></td>
                        <td>@forecast.Date.ToShortDateString()</td>
                        <td>@forecast.TemperatureC</td>
                        <td>@forecast.TemperatureF</td>
                        <td><InputText @bind-Value="@forecast.Summary"/></td>
                    </tr>
                }
                    <button class="btn btn-primary" type="submit">Save</button>
            </tbody>
        </table>
    </EditForm>

    @code {
        List<WeatherForecast> forecasts;

        protected override async Task OnInitializedAsync()
        {
            forecasts = await Http.GetJsonAsync<List<WeatherForecast>>("https://localhost:5000/WeatherForecast/");
        }
        private async Task HandleValidSubmit()
        {
            // What should be put there???
        }
    }

Now, as I have already retrieved the list of forecast objects, I want to pass one of them to any other component, say an edit component like the following:

    @page "/WeatherForecast/Edit/"
    @inject HttpClient Http

    @code {
        [Parameter]
        WeatherForecast Forecast { get; set; }

        protected override async Task OnInitializedAsync()
        {
            forecast = // **How to pass the forecast object here from the previous one** //
        }
        private async Task HandleValidSubmit()
        {
            await Http.PostJsonAsync($@"https://localhost:5000/WeatherForecast/", Forecast);
        }
    }

(Indeed, it will be wasteful and useless to get again the object for edition…)

How to achieve this with Blazor? I know how to pass value and so on, but not how to pass custom object between siblings components, and for now, did not found how to do this…

**Comment by mrpmorris** [comment]
In the first component have a property, then bind the Forecast parameter of your second component to that.

`<Other Forecast=MyForecast/>`

You may wish to make the source property capable of two way binding. 

https://blazor-university.com/components/two-way-binding/

**Comment by pranavkm** [comment]
Thanks @mrpmorris for your recommendation. I've also found this blog post pretty useful: https://chrissainty.com/3-ways-to-communicate-between-components-in-blazor.
@vintzl I'll encourage you to continue pursuing this discussion on StackOverflow if you need further help.

**Comment by vintzl** [comment]
And what about adding these informations in https://docs.microsoft.com/?

**Comment by pranavkm** [comment]
@vintzl the docs typically don't cover application programming patterns. That said, we'd be happy to accept a PR that elaborates this or points to the blog post above.
