### ISSUE TITLE
Forms without an instance of model

### ISSUE THREAD

**Issue by tstivers1990** [aspnet/AspNetCore#17987]
How can I do this without declaring `RequestModel` in the Razor PageModel? It inevitably ends up going un-used. Its presence creates potential for confusion and mistakes.

https://gist.github.com/tstivers1990/a7bf2c604a9e16f5116fbcc866859e80

**Comment by pranavkm** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. We recommend posting your questions to StackOverflow using the asp.net-core-mvc tag for questions like these.
