### ISSUE TITLE
First Request too slow and delay in middleware on asp.net core 3.1 web api

### ISSUE THREAD

**Issue by KamranShahid** [aspnet/AspNetCore#17985]
I have asp.net core 3.1 web api project which i have deployed on ubuntu 18 AWS machine. I were recently doing load testing then found out that first request is always slow.
Please guide me how can i reduce first request time

**Comment by nminaya** [comment]
@KamranShahid Did you check if you have some lazy loading configuration that is initialized when the first request is received?

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by KamranShahid** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

Doesn't have code right now with me but i thought it's a general phenomena. In IIS days we use to do some IIS level tweaking like Always running in Start mode and Suspended in idel timeout action.
have even seen some hacks (but they are in old asp.net core version or missing some support in asp.net core 3.1) like
https://stackoverflow.com/questions/57679221/asp-net-core-2-2-site-warmup
https://andrewlock.net/reducing-latency-by-pre-building-singletons-in-asp-net-core/

**Comment by davidfowl** [comment]
@KamranShahid not really. If you can give more details about where the code is slow or if you have measurements that would be great.

**Comment by KamranShahid** [comment]
> @KamranShahid not really. If you can give more details about where the code is slow or if you have measurements that would be great.

Not have much detail at the moment. Doing more investigation to find out where exact the time is spent

**Comment by KamranShahid** [comment]
What i have done is added request logging middleware as mentioned in 
https://stackoverflow.com/questions/55124938/asp-net-core-middleware-routing-delay-between-request-and-action

Now what i observed it first request is taking around 0.350 after reaching on server and then reaching to my action.
After first request second request taking around 0.050 seconds on average.
so delay is in processing after reaching it our application then to action

**Comment by pranavkm** [comment]
Using https://github.com/aspnet/AspNetCore/issues/18005 for further discussions.
