### ISSUE TITLE
Anyway to get what time took at various filters/middlewares

### ISSUE THREAD

**Issue by KamranShahid** [aspnet/AspNetCore#18008]
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1
Is there a way i can get what time it took on various stage of my request life cycle
I have simple web api project which i am diagnosing where time is spent. my actual action take just merely 7 milliseconds while from some request trackign middle ware it seems to take quite a time before request land to server and till action method. 
surely after request completion there could be some other delay.

**Comment by pranavkm** [comment]
Closing this. We can use https://github.com/aspnet/AspNetCore/issues/18005 to track further discussion.

**Comment by KamranShahid** [comment]
ok.
hope i can get some help from other post
