### ISSUE TITLE
IJSRuntime strange behavior !

### ISSUE THREAD

**Issue by mRmEEeZ** [aspnet/AspNetCore#18000]
I found a strange behavior of IJSRuntime service
IJSRuntime showing toast messages that is being send to wrong connected client
for example:
there are 2 clients who is connected to the system if the first one did some operation and JSRuntime shows a toast 'Successfully Done' the toast appears in the last connected client who is in ideal state rather than the first connected client who DID and DESERVE the toast message
it looks like somehow the JSRuntime service is singleton ...

### To Reproduce
I have this view model
``` 
[Route("/helpdesk_model")]
    [Route("/helpdesk_model/{Id:long}")]
    public class HelpDeskViewModel : ViewModelBase<CorrectiveWorkOrder>
{
      [inject] IJSRuntime jsRuntime {get;set;}
      JsInterop _jsInterop;
     
protected override void OnInitialized()
{
 _jsInterop = new JsInterop(jsRuntime);
}
     void AddNewWorkOrder()
{
   ...
   _jsInterop.ShowToast('Successfully Done',Style.success);
}
}
```
which inherits from this base class
```
public interface IViewModel<TEntity> : IViewModelContainer where TEntity : DbModel
    {      
        TEntity Entity { get; set; }
        IDataAccessLayer<TEntity> DataAccessLayer { get; set; }
    }

    [Layout(typeof(LayoutComponent))]
    public class ViewModelBase<TEntity> : ComponentBase,IViewModel<TEntity> where TEntity : DbModel
    {
[Parameter]
        public TEntity Entity { get; set; }
        [Inject]
        public NavigationManager NavigationManager { get; set; }
...
```

The JsInterop class
```
public class JsInterop
    {
public JsInterop(IJSRuntime jSRuntime)
        {
            SetJsRuntime(jSRuntime);
        }
public async Task<bool> ShowToast(string message, ResponseStatus status)
        {
            JsRunTime.InvokeAsync<string>("Site.Toast", message, status.ToString());
            return false;
        }
}
```

The js code..
```
window.Site = {
 Toast: function (message, style) {
        var toast = new Toasty();

        if (style === "success") {
            toast.success(message);
        }
        else if (style === "info") {
            toast.info(message);
        }
        else if (style === "warning") {
            toast.warning(message);
        }
        else if (style === "error") {
            toast.error(message);
        }
    }
}
```

### Further technical details
- ASP.NET Core version: 3.1 Server-Side Blazor
- The IDE (VS / 16.4)

**Comment by mRmEEeZ** [comment]
Further more ..
this thing happens when both users on the same url 'Route'
probably the view models 'pages' are singleton type

**Comment by mRmEEeZ** [comment]
Further more 2...
even if the last connected client routes to different page
he is still receiving toasts
i think when last client routed to same page as first client
it overwrited the current IJSRuntime of the page so that is still receiving the toasts
also if the first client re-route to same page then he receive his toasts as expected as he overwrited yet again IJSRuntime...

this is a confirmation of the previous assumption
the pages are singletons...

any solution ?

**Comment by mRmEEeZ** [comment]
after further real investigation...
creating `JsInterop` object every time i want to use `javascript` works fine
but if i store the `JsInterop` object things start going messy tho the `JsInterop` is a simple class to call functions
anyway i converted these static methods inside `JsInterop` class to extention methods for `IJSRuntime` interface and it solved my problem

now my guess about what is going on with pages a.k.a view models in this case...
when we have `[inject] property` in a view model it sticks per user..
if we have normal property it is static to the view model ?! and therefore it gets overwritten each time users visit that page and it is there shared for everyone ?
i think this is what is going on..
everything in page is static or singleton but not anything decorated with `[parameter]` or `[inject]`

am i right ?

**Comment by pranavkm** [comment]
> everything in page is static or singleton but not anything decorated with [parameter] or [inject]

The Razor compiler does not change the scoping or visibility of code written inside a `code` block. You can inspect the generated code under the `obj\Debug\netcoreapp3.1\Razor` folder  to see what the generated code looks like. In Blazor Server, `IJSRuntime` instances are scoped per SignalR connection. I suspect the `SetJsRuntime` method in your `JSInterop` type is extending the lifetime of the IJSRuntime` instance across multiple scopes.

> anyway i converted these static methods inside JsInterop class to extention methods for IJSRuntime interface and it solved my problem

That sounds great and is the pattern we would encourage.
