### ISSUE TITLE
Upgrade Microsoft.ApplicationInsights.AspNetCore 2.7.1 to 2.12 makes custom event not written to app insight

### ISSUE THREAD

**Issue by andrew-vdb** [aspnet/AspNetCore#18012]
### Describe the bug
Custom event is not always written to app insight

### Further technical details
- ASP.NET Core version
3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
vs 2019 enterprise

I can see that custom event is being called but when i query it, it does not show the track event

**Comment by andrew-vdb** [comment]
Not sure if this is the correct repo to report

**Comment by Pilchie** [comment]
@davidfowl do you have an Application Insights contact?

**Comment by davidfowl** [comment]
Yes this should be filed on https://github.com/microsoft/ApplicationInsights-dotnet

**Comment by pranavkm** [comment]
This issue was moved to microsoft/ApplicationInsights-dotnet#1519
