### ISSUE TITLE
Blazor — System.Text.Json and JsonConverter<T>

### ISSUE THREAD

**Issue by vintzl** [aspnet/AspNetCore#18011]
I have found more or less related issue:
- https://github.com/aspnet/AspNetCore/issues/12685
- https://github.com/aspnet/AspNetCore/pull/10171
- https://github.com/aspnet/AspNetCore/issues/10404
- https://github.com/aspnet/AspNetCore/issues/14254

As Blazor should no more use `SimpleJSON` but `System.Text.Json`  by default, I should be able to use custom `JsonConverter<T>` by configuring Blazor But I find nothing on how to use custom `JsonConverter<T>` inside Blazor…

For now I use extensions methods, but I am looking for some configurations inside the `Startup` class:

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IComponentsApplicationBuilder app)
        {
            app.AddComponent<App>("app");
        }
    }

Where can I get any information about this? Is there any such configuration available through `services` ?

**Comment by pranavkm** [comment]
@vintzl at this point Blazor does not have any extensibility to configure serialization globally. The best you could do is to decorate types with `JsonConverterAttribute` and [author custom converters](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?view=netcore-3.0) to manage seriaization on a per-type basis.

https://github.com/aspnet/AspNetCore/issues/12685 tracks further improvements in this area.
