### ISSUE TITLE
Discussion for:Move Authorization to repo 'Extensions'

### ISSUE THREAD

**Issue by wu-yafeng** [aspnet/AspNetCore#18024]
Consider move `Microsoft.AspNetCore.Authorization` to Extensions repo https://github.com/aspnet/extensions with new name `Microsoft.Extensions.Authorization` and
move `Microsoft.AspNetCore.Authorization.Policy` to Middleware solution at current repo

Authorization seems to be a more general component, not just for aspnetcore.

I think design Authorization like healthcheck component should be great!

Bad English

**Comment by blowdart** [comment]
We've discussed this before and considered it hugely breaking for very little reward other than "purity", especially when things like cookie auth are quite aspnet specific.

What benefit do you think this would bring?

**Comment by wu-yafeng** [comment]
I have an application based CQRS pattern and solution like this:
- Solution
  - Api
  - Application
  - Infrastructure
  - Domain

Application-layer represent command handing and I would use resource-base authorization in application-layer.I hope application-layer don't use any packages in aspnetcore 、rpc、thrift、windows-service.
So I can move to any hosted without change application-layer.

Now,I add package 'Authorization' to application-layer.I can move application-layer to any host without change code,but the name of Authorization package makes people thinks its running under aspnetcore

**Comment by wu-yafeng** [comment]
> We've discussed this before and considered it hugely breaking for very little reward other than "purity", especially when things like cookie auth are quite aspnet specific.
> 
> What benefit do you think this would bring?

cookie authentication is aspnetcore specific,but not authorization?

**Comment by blowdart** [comment]
While authorization isn't core specific it's still a very big breaking change, as everyone will have to update namespaces and we'd have to deprecate the older ones. For a perception issue this probably isn't justified.

**Comment by wu-yafeng** [comment]
> While authorization isn't core specific it's still a very big breaking change, as everyone will have to update namespaces and we'd have to deprecate the older ones. For a perception issue this probably isn't justified.

I agree
