### ISSUE TITLE
CORS 3.0

### ISSUE THREAD

**Issue by jeanpoelie** [aspnet/AspNetCore#18021]
When will you release a Microsoft.AspNetCore.Cors v3.0?
All other packages seem to have been upgraded to 3.0 and 3.1 for the corresponding .net core version except this package.

https://www.nuget.org/packages/Microsoft.AspNetCore.Cors/

**Comment by pranavkm** [comment]
@jeanpoelie the package was removed as part of the 3.0 release. See https://github.com/aspnet/Announcements/issues/325. Please follow our migration guide to update your application to .NET Core 3.0 and later: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio
