### ISSUE TITLE
Is there any online live editor available for blazor platform.

### ISSUE THREAD

**Issue by Indrajith-Sync** [aspnet/AspNetCore#18027]
Like codesandbox or jsfiddle for JS platforms. Is there any online live editor available for Blazor platform. 

I could find the following, Is there anything else other than this ?

https://blazorfiddle.com/

**Comment by pranavkm** [comment]
I'm personally not aware of any outside of blazorfiddle. @danroth27?

**Comment by mrpmorris** [comment]
I believe it's the only one.

**Comment by danroth27** [comment]
I'm only aware of https://blazorfiddle.com, which is built by the community. Feel free to reach out to the owner, @samprof, if you think it could be improved in some way.
