### ISSUE TITLE
when Microsoft.AspNetCore will be update to latest version 3.1

### ISSUE THREAD

**Issue by ema2ooo** [aspnet/AspNetCore#18034]
when Microsoft.AspNetCore will be update to latest version 3.1, thanks

**Comment by pranavkm** [comment]
@ema2ooo the package was removed as part of the 3.0 release. See https://github.com/aspnet/Announcements/issues/325. Please follow our migration guide to update your application to .NET Core 3.0 and later: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio
