### ISSUE TITLE
Navigation between Inner published folder Applications

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#18038]
I have a one doubt about hosting the nested publish folders.

Now i have a one published(project A) folder. And then published(Project B) folder in to the project A 's published folder.

Then i hosted the project A's folder in IIS server.

Now how can i access the application for project B 's published folder from the hosted project A.

Is this possible? Can any one help me on this?

**Comment by pranavkm** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. We recommend posting your questions to StackOverflow using the asp.net-core-mvc tag to reach a wider audience.
