### ISSUE TITLE
Blazor,One refresh will cause the component to dispose twice

### ISSUE THREAD

**Issue by zxgamekingdom** [aspnet/AspNetCore#18033]
When I use blazor, I find that when I add an IDispose interface to a component, I can see in the log that when I click a browser refresh, there will be two dispose messages, and the dispose methods of two different objects of the same component will be called.

Project is a template produced by visual studio

Log:
info: BlazorApp4.Pages.Index[0]
      Dispose
info: BlazorApp4.Pages.Index[0]
      12/26/2019 11:51:52 22677740 Dispose 1
info: BlazorApp4.Pages.Index[0]
      12/26/2019 11:51:52 All Dispose 1
info: BlazorApp4.Pages.Index[0]
      Dispose
info: BlazorApp4.Pages.Index[0]
      12/26/2019 11:51:57 14421545 Dispose 1
info: BlazorApp4.Pages.Index[0]
      12/26/2019 11:51:57 All Dispose 2
info: BlazorApp4.Pages.Index[0]
      Dispose
info: BlazorApp4.Pages.Index[0]
      12/26/2019 11:51:57 5773521 Dispose 1
info: BlazorApp4.Pages.Index[0]
      12/26/2019 11:51:57 All Dispose 3

C# Code:
```
    public partial class Index : IDisposable
    {
        private int _i;
        public static int I;

        public void Dispose()
        {
            Logger.LogInformation(nameof(Dispose));
            Logger.LogInformation("{time} {hashCode} Dispose {count}",
                DateTime.Now.ToString(CultureInfo.InvariantCulture), GetHashCode(),
                ++_i);
            Logger.LogInformation("{time} All Dispose {count}",
                DateTime.Now.ToString(CultureInfo.InvariantCulture), ++I);
        }
    }
```
Visual Studio 2019 16.4.2
AspNetCore 3.1 
Blazor Server

**Comment by pranavkm** [comment]
@zxgamekingdom do you happen to have pre-rendering enabled in your app? With prerendering, you have two instances of the component which would explain why you see 3 of these - once during the initial pre-rendering, once when the component is disposed on disconnect and once again during the 2nd pre-rendering.

**Comment by zxgamekingdom** [comment]
@pranavkm Thank you,It's really because I can't understand render mode.
