### ISSUE TITLE
Asp.Net core WebAPI ModelState automatic validation

### ISSUE THREAD

**Issue by MapleWithoutWords** [aspnet/AspNetCore#18035]
### Describe the bug
    
I have an interface, and accept what is an entity class PersonModel object, the object of property I call them to verify the label Required, this want to controller performs ModelState. IsValid to verify the model, but seems to request, does not go to the controller, automatic validation for me directly, I think I manually control the validation, could you tell me what method? Thank you very much!

### Further technical details
- ASP.NET Core version：  2.2
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version： vs2019

**Comment by MapleWithoutWords** [comment]
![image](https://user-images.githubusercontent.com/38368335/71473144-d963b700-2810-11ea-9c49-459fc7105ea6.png)
this my  result image!

**Comment by MapleWithoutWords** [comment]
I will it is return {"status":1,"errorMsg":"The Name field is required.",data:null}

**Comment by MapleWithoutWords** [comment]
This is my controller code:
`
    [Route("api/[controller]")]
    [ApiController]
    public class PersonController : ControllerBase
    {
        [HttpPost]
        public IActionResult Post(PersonModel model)
        {
            if (ModelState.IsValid==false)
            {
                StringBuilder sb = new StringBuilder();
                foreach (var ms in ModelState.Values)
                {
                    foreach (var modelError in ms.Errors)
                    {
                        sb.AppendLine(modelError.ErrorMessage);
                    }
                }
                return new JsonResult(new { status=1,errorMsg= sb.ToString() });
            }
            return new JsonResult(new { status = 0, errorMsg = "",data=model });
        }
    }
`

**Comment by MapleWithoutWords** [comment]
This my controller code:


    [Route("api/[controller]")]
    [ApiController]
    public class PersonController : ControllerBase
    {
        [HttpPost]
        public IActionResult Post(PersonModel model)
        {
            if (ModelState.IsValid==false)
            {
                StringBuilder sb = new StringBuilder();
                foreach (var ms in ModelState.Values)
                {
                    foreach (var modelError in ms.Errors)
                    {
                        sb.AppendLine(modelError.ErrorMessage);
                    }
                }
                return new JsonResult(new { status=1,errorMsg= sb.ToString() });
            }
            return new JsonResult(new { status = 0, errorMsg = "",data=model });
        }
    }

**Comment by praveena-m** [comment]
@MapleWithoutWords  You can choose to disable automatic model state validation using below code in your startup.

```
services.Configure<ApiBehaviorOptions>(options =>
{
    options.SuppressModelStateInvalidFilter = true;
});
```

**Comment by pranavkm** [comment]
@praveena-m's repsonse is correct. Disabling the filter should allow you to manually handle the invalid model state filter. An alternative to disabling the filter is to change what it produces: https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1#validation-failure-error-response
