### ISSUE TITLE
Controller public override void OnActionExecuting() Order should not be int.MinValue;

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore#18044]
In [DefaultApplicationModelProvider](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ApplicationModels/DefaultApplicationModelProvider.cs#L194-L201)  you set the delegating filter. The source for [ControllerActionFilter](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Filters/ControllerActionFilter.cs#L15-L17) sets ` public int Order { get; set; } = int.MinValue;` putting it closest to the action. The comment "Controller-filter methods run farthest from the action by default." makes me think you meant to set it to `int.MaxValue;`

The problem with setting it to `int.MinValue;` , I can't get my action level filter `SampleActionFilter` to run before ` public override Task OnActionExecutionAsync`

```
public class Test3Controller : Controller
{
    [SampleActionFilter(Order = int.MinValue)]
    public IActionResult FilterTest2()
    {
        var m = MethodBase.GetCurrentMethod();
        MyDebug.Write(m, HttpContext.Request.Path);
        return Content(m.ReflectedType.Name + "." + m.Name);
    }

    public override Task OnActionExecutionAsync(ActionExecutingContext context, 
                                                ActionExecutionDelegate next)
    {
        MyDebug.Write(MethodBase.GetCurrentMethod(), HttpContext.Request.Path);
        return base.OnActionExecutionAsync(context, next);
    }

}
```

I'm forced to move the filter to class scope if I want `SampleActionFilter` to run first:

```
[SampleActionFilter(Order = int.MinValue)]
public class Test3Controller : Controller
```

I think [ControllerActionFilter](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Filters/ControllerActionFilter.cs#L15-L17) should set ` public int Order { get; set; } = 0;` 
for maximum flexibility. 

I realize this would be a breaking change.  Is there any way to set the order on controller filter overrides so I can make `public override Task OnActionExecutionAsync` or `public override void OnActionExecuting(` run **after** filters applied to a method?

**Comment by pranavkm** [comment]
> The comment "Controller-filter methods run farthest from the action by default." makes me think you meant to set it to int.MaxValue;

The order is correct, setting it to `int.MinValue` means it always runs first i.e. before any other filter and furthest from the action. 

Couldn't you write a controller filter instead? What is it that you're trying to do here that you couldn't already do with a controller filter instance?
