### ISSUE TITLE
Still iOS13 Problems with .NET Core 3.1 03.December 2019 Blazor update (WebAssembly)

### ISSUE THREAD

**Issue by Schoch85** [aspnet/AspNetCore#18041]
There is still a problem with iOS13, also with the latest Blazor update. 
Into my Blazor pages I inject around five singleton services.
When I open the browser on iOS13 and I load a page then it is working, but when I'm reload the page then it seems the stack problem returns and the page isn't loaded. 
When I remove from my five injecting services three services then it is also working during reloading.

It is a problem because I have the following scenario:
The user connects to the Blazor site, accept the terms and is then redirected to a SAML provider. After authentication the user is redirected back to Blazor, and because the user is then the second time on the blazor app the page hangs and isn't loaded.
What I have done as workaround is to redirect the user after authentication to a intermediate page without any services injected, only with the NavigationHelper. Then I use the method OnAfterRender to redirect the user to the target page. But this is also only working when I'm put a Thread.Sleep with around 1 second before the redirect.

In fact a Blazor page can only once loaded in a browser tab when there are a few injecting services.
So the timing problems on iOS13 seems still to exist. Can you confirm this?
Thanks for the feedback.

**Comment by pranavkm** [comment]
This issue was moved to mono/mono#18300
