### ISSUE TITLE
How can i host/deploy the blazor applications in GCP?

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#18054]
Hi Guys,

I want to host the blazor applications in google cloud plat form.

1. Is there any docs/ways to do this?

2. If it is possible then how can i install the latest version of sdks in it?

can anyone please update details regarding this?

**Comment by pranavkm** [comment]
Hi @kmuthukumar23, this sounds like a question for the platform that you're attempting to deploy to. I'll recommend following up with their forums on how to host and deploy ASP.NET Core applications.
