### ISSUE TITLE
Identity scaffolding as a Model View Controller

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/AspNetCore#18053]
### Is your feature request related to a problem? Please describe.
I suggest to make both options available. i.e. to scaffold identity as Razor Pages or Model View Controller.

### Describe the solution you'd like
To add a radio button to let the developer choose between RP and MVC for Identity scaffold result.

### Additional context
.Net core is based on freedom (freedom of platform choice) and it should apply freedom as well in choose between RP and MVC structures for scaffolding. Thank you.

**Comment by blowdart** [comment]
This gets brought up a lot. Unfortunately we simply don't have the resources to keep what would become 4 different scaffolding templates in sync and up to date. When I ran a survey the vast majority of respondents, while they wanted MVC scaffolding didn't want it enough to drop other features, and the wider community hasn't produced templates either, so the demand simply isn't there.
