### ISSUE TITLE
How to get the "large object heap" size using .net core 3 running on Ubuntu 18.04

### ISSUE THREAD

**Issue by ParisRoubaix** [aspnet/AspNetCore#18059]
How do I get the "large object heap" size? 

I'm using .net core 3 running on Ubuntu 18.04.

I posted this on StackOverflow and the only answer was to run dotnet-counters. How can I get this metric inside my running process?

Thanks.

**Comment by blowdart** [comment]
This isn't an asp.net question.

Please repost in https://github.com/dotnet/runtime as I don't have the ability to move it.

**Comment by pranavkm** [comment]
This issue was moved to dotnet/runtime#1217
