### ISSUE TITLE
Blazor Client - "Unable to render component 14" error with deferred .OrderByDescending evaluation 

### ISSUE THREAD

**Issue by borseno** [aspnet/AspNetCore#18056]
Consider this code:

`@foreach (var option in optionsVotes.OrderByDescending(i => i.Key))
            {
                <p>Option: @option.Key Votes: @option.Value</p>
            }`

optionVotes is a dictionary<string, int>

Here it doesn't work and says in console something like "unable to render component 14". Then I moved this code to @code section and looped through a ready to consume IEnumerable (i.e without calling any methods) like that:

`@foreach (var option in optionsVotes)
            {
                <p>Option: @option.Key Votes: @option.Value</p>
            }`

it started to work. However, it's not only about moving it to @code section. In @code section, I also added .ToArray() after .OrderByDescending. So maybe the problem lies in deferred evaluation.

For more details, you can compare there two versions of my .razor page file:

[version 1 - not working](https://pastebin.com/93aYJ6Ht)
[version 2 - working](https://pastebin.com/QfCJNbD9)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by borseno** [comment]
Unfortunately I couldn't attach the project as it is too big in terms of size. It also contains more than a hundred files, so I couldn't upload it as a new public repository either. However, you can find links to the page code in the issue description, with non-working and working versions, respectively. You can skip the api call in the code and mock it with ready-to-use values. It won't work that way either. You can also ignore all fields except for "optionVotes".

**Comment by pranavkm** [comment]
We tried using the first app and it works fine by default. Your suspicions about deferred evaluations being problematic might be it. If you still think this is specific to Blazor, feel free to reply here and we can try and help.

**Comment by borseno** [comment]
Hello @pranavkm 
here you have the github repo for the project this issue was spotted in: [Repo](https://github.com/borseno/TempRepoForBlazorIssue)

The file you should look for is located at this path: TempRepoForBlazorIssue/Votings/Votings/Client/Pages/VotingState.razor

**Comment by borseno** [comment]
Hello @pranavkm 
The issue doesn't cause any problems to me but still this bug is probably related to Blazor (in my opinion) because it gave blazor-specific error "Unable to render component 14". I found a workaround to the problem with loading large projects to github at once, and now you can view the repo [here](https://github.com/borseno/TempRepoForBlazorIssue)

The file you should look for is located at this path: TempRepoForBlazorIssue/Votings/Votings/Client/Pages/VotingState.razor

To launch the project with SQL Server as data store (that's what we used) write the following commands in Package Manager Console:

$env:DatabaseType='1'
Update-Database

To launch it with in-memory provider, you can run this:

$env:DatabaseType='0'
$env:ASPNETCORE_ENVIRONMENT='Development'

I know it's probably not a very important issue but who knows what this can cause. You know the butterfly effect and such things, right? Sometimes even such things can cause a crush of an airplane. 
Please feel free to ask any questions
