### ISSUE TITLE
how to update data in blazor pages automatically when db updates

### ISSUE THREAD

**Issue by Su-s** [aspnet/AspNetCore#18051]
Is there any way to update the Blazor UI in Blazor client App without manually reloading the Page.
In the below example we need to pull the data from the backend; ie the Blazor.server and display periodically.

```
@code{
    protected override async Task OnInitializedAsync()
    {
   while (true)
        {
            await GetLogs();
            StateHasChanged();
        }
    }
    async Task GetLogs()
    {
      var  modelList= await http.GetJsonAsync<Model[]>("api/model");
    }
}
```

Blazor is using Signal R internally for the connection to the client. Is there any method that we can use Signalr to pull the data when DB updates and can omit the usage of the REST API.

**Comment by pranavkm** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. We recommend posting your questions to StackOverflow using the asp.net-core-blazor tag to reach a wider audience.
