### ISSUE TITLE
IdentityServer4 OIDC for Blazor

### ISSUE THREAD

**Issue by rysep2** [aspnet/AspNetCore#18066]
I'm trying to fit my Blazor Server Side application into our existing IdentityServer4 OIDC process. At the moment there is no official documentation concerning this topic and I'm forced to use hacky workarounds that in turn produce uncommon errors. In [this github issue](https://github.com/aspnet/AspNetCore/issues/12601) I already addressed one of those errors that I still can't solve.

On stackoverflow I see a lot of people try to accomplish the same thing but there are no proper solutions. I opened this exact [issue](https://github.com/aspnet/AspNetCore/issues/17256) before but it got auto-closed even though it wasn't solved. Everything I find online concerning the topic IdentityServer4 OIDC in Blazor is incomplete and hacky. Security is a complex topic and should not be left to the developers to "find out themselves".

I'd expect documentation of the topic and a template, like with the other authentication possibilities in Blazor.

**Comment by pranavkm** [comment]
We'll use the linked issue to track further work.
