### ISSUE TITLE
Blazor dealing with cookie expiration

### ISSUE THREAD

**Issue by mihaimyh** [aspnet/AspNetCore#18079]
Happy New Year!

There was an older issue opened for this https://github.com/aspnet/AspNetCore/issues/6855 which was closed by the bot without a solution.

Is there a way to force the user back to login page when the cookie has expired?

Currently setting `options.ExpireTimeSpan = TimeSpan.FromSeconds(300)` still allows user to navigate inside the app and only a browser refresh will trigger the login process.

**Comment by pranavkm** [comment]
@mihaimyh have a look at the Blazor server templates. It has a component that revalidates at intervals and that should help here. Let us know if you need any further help.

**Comment by mihaimyh** [comment]
@pranavkm Are you talking about RevalidatingIdentityAuthenticationStateProvider?

**Comment by pranavkm** [comment]
Yup, that would be it.
