### ISSUE TITLE
Question - How to handle window or body onscroll in Blazor server side?

### ISSUE THREAD

**Issue by fingers10** [aspnet/AspNetCore#18072]
I'm developing my first blazor server side application. I need to capture `onscroll` event of `window` or `body` in my blazor server side application. Right now I implemented this using a script file where I capture the event and do my logics in there as shown below.

**For `window`:**

```js
window.onscroll = function() {myFunction()};

function myFunction() {
  //  ... my logics here
}
```

How to capture `onscroll` event of `body` tag? In blazor server side `body` is in `_Host.cshtml` file where I cannot use `@onscroll` since it is not a component

**For `body`:**

```html
<body onscroll="myFunction()">
```

The above one works but I'm not happy with this implementation while using blazor.

Please assist on how to implement this purely with C# or it is acceptable to use Javascript for this. I'm confused.

**Comment by pranavkm** [comment]
> or it is acceptable to use Javascript for this.

If this works for your scenario, it's perfectly reasonable.
