### ISSUE TITLE
I just want to verify through the Blazor team if using HttpContext is viable

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#18070]
in Blazor Server App, as I do. The code works perfectly fine. And I query the HttpContext only on the first connection which is an HTTP connection, that is when the user type a url in the browser's address bar and then press the enter button.

`1. Add a file to the Pages folder and name it _Host.cshtml.cs
2. Add this code to the file:
 

        public class HttpContextFeatureModel : PageModel
        {
        private readonly IHttpContextAccessor _httpContextAccssor;
    
        public HttpContextFeatureModel(IHttpContextAccessor httpContextAccssor)
        {
             _httpContextAccssor = httpContextAccssor;
            
        }
        public string UserAgent { get; set; }
        public string IPAddress { get; set; }
    
        
        // The following links may be useful for getting the IP Adress:
        // https://stackoverflow.com/questions/35441521/remoteipaddress-is-always-null
        // https://stackoverflow.com/questions/28664686/how-do-i-get-client-ip- 
        address-in-asp-net-core
    
        public void OnGet()
        {
            UserAgent = _httpContextAccssor.HttpContext.Request.Headers["User-Agent"];
            // Note that the RemoteIpAddress property returns an IPAdrress object 
            // which you can query to get required information. Here, however, we pass 
            // its string representation
            IPAddress = 
            _httpContextAccssor.HttpContext.Connection.RemoteIpAddress.ToString();
           
        }
    
       }`

3. Define in the App component two parameter properties which will get and store the User Agent and IP Address passed to it from the component tag in located in _Host.cshtml

App.Razor
-----------

   `<p>UserAgent: @UserAgent</p>
    <p>IPAddress: @IPAddress</p>
    @code{
        [Parameter]
        public string UserAgent { get; set; }
        [Parameter]
        public string IPAddress { get; set; }
    }`

4. In _Host.cshtml update the component tag like this:

   `<app>
        <component type="typeof(App)" render-mode="ServerPrerendered" param-UserAgent="@Model.UserAgent" param-IPAddress="@Model.IPAddress" />
    </app>`

5. Add `services.AddHttpContextAccessor();` to the Startup.ConfigureServices method to enable access to the HttpContext.

Thank you very much... God Blazor you.

**Comment by pranavkm** [comment]
Hi @enetstudio, using the `HttpContext` \ `HttpContextAccessor` inside a Razor Page as you've done should be fine. In fact, you should be able to access the `HttpContext` without injecting the accessor using this property: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razorpages.pagemodel.httpcontext?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_RazorPages_PageModel_HttpContext.

Accessing `HttpContext` from a Blazor component is problematic and isn't guaranteed to work. What you have here should work well.

**Comment by enetstudio** [comment]
Thanks so much for this, @pranavkm!

**Comment by anotherdeveloper** [comment]
@enetstudio 
Trying to follow your instructions, I'm getting '_Pages__Host' does not contain a definition for 'UserAgent'. Any tips?

**Comment by enetstudio** [comment]
Your code may be missing  `public string UserAgent { get; set; }`

**Comment by Orgbrat** [comment]
@enetstudio Followed you instructions and all seems to work as you described.  But how do you access those properties in _Host.cshtml.cs from other razor components and services within the Blazor SSA? Am I going to have to store the values in local-storage, session variables or something?

Orgbrat

**Comment by enetstudio** [comment]
Yes, you can store the values in local-storage...
