### ISSUE TITLE
DB Connection Pool Exhaustion

### ISSUE THREAD

**Issue by gurry** [aspnet/AspNetCore#18089]
I'm facing a problem with an Asp.Net Core app where database connections get exhausted  the application crashes with this exception: 

`System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.`

The action method in question is as below:

```c#
       [HttpPost]
        public async void Post(DeviceState state)
        {
            using (var connection =  new SqlConnection("Data Source=localhost;Integrated Security=True");) // Using the default max pool size of 100
            {
                await connection.OpenAsync();
                (var command = new SqlCommand(INTO test_db.dbo.DeviceState (fqdn, content_name, bytes_from_peer, bytes_from_source, total_size) VALUES(@fqdn, @content_name, @bytes_a, @bytes_b, @total_size)",
                    connection))
                {
                    AddParameter(command, "@fqdn", SqlDbType.VarChar, state.Fqdn + Guid.NewGuid());
                    AddParameter(command, "@content_name", SqlDbType.VarChar, state.ContentName);
                    AddParameter(command, "@bytes_a", SqlDbType.BigInt, state.BytesA);
                    AddParameter(command, "@bytes_b", SqlDbType.BigInt, state.BytesB);
                    AddParameter(command, "@total_size", SqlDbType.BigInt, state.TotalSize);

                    await command.ExecuteNonQueryAsync();
                }
            }
        }
```

And this is the `AddParamter()` helper method:

```C#
 private static void AddParameter(SqlCommand command, string name, SqlDbType type, object value)
        {
            var param = command.CreateParameter();
            param.ParameterName = name;
            param.SqlDbType = type;
            param.Value = value;
            command.Parameters.Add(param);
        }
```

What the `Post()` method is doing is INSERTing a row into a table called `DeviceState` every time it is called. `DeviceState` table was created with the below T-SQL snippet:

```SQL
  create table [cdc_test_db].[dbo].[DeviceState](
   fqdn varchar(255) primary key not null,
   content_name varchar(500) not null,
   bytes_a bigint,
   bytes_b bigint,
   total_size bigint
)
```

I'm using the default max pool size of 100. I'm seeing these exceptions at 20000 requests/s. But interestingly enough I see that the app starts to use all 100 connections even at very low request rates like 1000 requests/s. This is different from the behaviour of classic Asp.Net (4.8) which never goes beyond 10 connections even while delivering 4000-5000 requests/s. Is Asp.Net Core designed to be aggressive when opening DB connections?

I've also observed this problem occurs _only_ when my action method is async and uses  async versions of all data APIs. When I switch everything to synchronous code, the problem goes away. So I wonder if this is something caused by async tasks holding onto the DB connections for too long while waiting to be scheduled on the thread pool. What am I doing wrong? 

Or is it just a manifestation of this issue: https://github.com/dotnet/SqlClient/issues/18, which from what I know should've been fixed in the Microsoft.Data.SqlClient version I'm using (see below).

**Details:**
- Asp.Net Core version: 3.1
- OS: Windows Server 2016
- Database: SQL Server 2016 Standard Edition
- Microsoft.Data.SqlClient version: 1.0.19269.1

**Comment by jkotalik** [comment]
From what it sounds like, this issue is probably better filed in the SqlClient repo. cc @ajcvickers @smitpatel any thoughts?

**Comment by ajcvickers** [comment]
@gurry As @jkotalik says, this is a SqlClient issue. Are you 100% sure you're using `Microsoft.Data.SqlConnection` and not `System.Data.SqlConnection` in your code? If so, then this is likely the issue your linked since the fix has not yet been ported to `System.Data.SqlClient`. If not, please file a new issue on the SqlClient repo.

**Comment by gurry** [comment]
@ajcvickers  Yeah I'm certainly using `Microsoft.Data.SqlClient`. As per @cheenamalhotra the version I'm using, 1.0.19269.1, should contain the fix. Just to be sure, I tried with version 1.1.0 also just now, but the issue still occurred even with that version.

Arthur, if you can transfer the issue to SqlClient repo, please do. Otherwise I'll go and copy-paste it there. Thanks :).

**Comment by brockallen** [comment]
Can you provide the link to the new issue once it's created? I've been experiencing problems like this ever since async/await was introduced into ADO.NET. My solution has always been to use the sync APIs as they don't exhibit the problem.

**Comment by gurry** [comment]
Reported it under SqlClient as suggested: https://github.com/dotnet/SqlClient/issues/364

**Comment by gurry** [comment]
Turned out to be not an issue in SqlClient or AspNetCore. It was due to an error in my code. See my closing comment on dotnet/SqlClient#364.
