### ISSUE TITLE
Forward IIS client certificate to ASP.NET Core (without trust/validation checks by IIS)

### ISSUE THREAD

**Issue by drauch** [aspnet/AspNetCore#18086]
We are running our ASP.NET Core application (2.1.latest + .NET.Framework 4.7.2) behind an IIS web server.

We want to perform custom client certificate validation in our ASP.NET Core application. For the SSL certificate to be forwarded from IIS to our application, however, we need to enable the following in the IIS' configuration file (`applicationHost.config`):

```
<system.webServer>
  <security>
    <access sslFlags="SslNegotiateCert" />
```` 

If we use `sslFlags=None` instead, no certificate is forwarded to our application. Unfortunately, setting it to `SslNegotiateCert` enables IIS' validation and trust checks. If they don't succeed, IIS immedaitely returns error code 403.16.

How to overcome this? How to disable client cert validation + trust check in IIS? IIS should simply forward us the client certificate and do nothing else with it.

Which IISOptions do we have to set?

The following (partly taken from #7998) does not work:

```
      services.Configure<IISOptions>(options => 
      {
        options.ForwardClientCertificate = true;
      });

      services.Configure<HttpsConnectionAdapterOptions>(options =>
      {
        options.ClientCertificateMode = ClientCertificateMode.AllowCertificate;
        options.CheckCertificateRevocation = false;
        options.ClientCertificateValidation = (certificate2, chain, policyErrors) =>
        {
          Console.WriteLine("VALIDATE THE THUMBPRINT IS: " + certificate2?.Thumbprint);

          // [...] our custom validation logic in here

          return true;
        };
      });
```

**Comment by davidfowl** [comment]
When using IIS HttpsConnectionAdapterOptions doesn't work. That's kestrel specific and in this case it won't do anything.

> How to overcome this? How to disable client cert validation + trust check in IIS? IIS should simply forward us the client certificate and do nothing else with it.

I'm not sure of a way to do this but a quick search brought this up https://forums.iis.net/t/1191370.aspx?403+16+on+IIS+8+

**Comment by drauch** [comment]
> I'm not sure of a way to do this but a quick search brought this up

In this thread they are adding the root certificate to IIS so it trusts the client certificate. However, we don't want to do that. Users should be able to send arbitrary client certificates.

**Comment by jkotalik** [comment]
I believe David is correct, you won't be able to get the forwarded certificate in AspNetCore from IIS because ANCM reverse proxies HTTP to Kestrel. So you'd have to do do custom client certificate validation in IIS. I think https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/authentication/iisclientcertificatemappingauthentication/ could help? This seems to be the equivalent to client certificate validation in IIS.

**Comment by drauch** [comment]
> So you'd have to do do custom client certificate validation in IIS.

How to do that?

> I think https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/authentication/iisclientcertificatemappingauthentication/ could help?

This seems to be just an addition to SslNegotiateCert, it still performs the trust check in IIS. But then performs an additional mapping from a client certificate to a user.

**Comment by Tratcher** [comment]
@jkotalik I don't expect that to work, that's about creating a user after the cert validation.

**Comment by anurse** [comment]
If IIS doesn't have a way to bypass it's trust checks there's not much we can do. This is an IIS issue/request. @shirhatti to look in to this.

Closing as this is an external issue, not something we can solve in ASP.NET Core.

**Comment by brockallen** [comment]
@anurse and @shirhatti, once you confirm that IIS can't do that, can you update this thread just for the record?

**Comment by anurse** [comment]
Sure. Checking now :).
