### ISSUE TITLE
NavigationManager should handle when a user presses the browser Back button

### ISSUE THREAD

**Issue by rbfriedman** [aspnet/AspNetCore#18085]
### Is your feature request related to a problem? Please describe.
On my application I have created a back button on the screen. When clicking the back button, I use NavigationManager to navigate to the previousPage, which I set based on the params in the page.  If a page is the homepage of that section, instead of a back button, I display a menu.
For example:

TomatoSauce.razor
```

@page "/tomatoSauce"
@page "/tomatoSauce/{type}"
```
```

    protected override async Task OnParametersSetAsync()
    {
    //When AppInfo has a PreviousPage set, the top nav bar knows to display a back button. Without previous page set, a Menu button is displayed
        if(!string.IsNullOrWhiteSpace(type) {
            AppInfo.PreviousPage = "/tomatoSauce";
        } 
        else
        {
              AppInfo.PreviousPage = "";
        }
    }



```
### Describe the solution you'd like
I think it would be useful to have something from the NavigationManager to hook onto so that I could use the browser Back button to trigger the same behavior of the Back/Menu button on my screen. 

At the very least, I think we should have access to a RouteData cascading parameter so that we could iterate through pages of the App dynamically. This would enable us to see if the current route matches a base/home/menu page route and display a back/menu button accordingly.

Thank you in advance!

**Comment by pranavkm** [comment]
@rbfriedman you could use JSInterop to run `history.back` to integrate with the browser's real history.
