### ISSUE TITLE
MissingMethodException thrown when using JsonResult(object value, JsonSerializerSettings serializerSettings) constructor

### ISSUE THREAD

**Issue by gabog** [aspnet/AspNetCore#18098]
Hello, we have a BaseController class in a class library that has been compiled targeting the  .Net Standard 2.0 framework. Here is a simplified view of the a method in the base class:

```
        [HttpPut("v3/conversations/{conversationId}/activities/{activityId}")]
        public virtual async Task<IActionResult> UpdateActivityAsync(string conversationId, string activityId, [FromBody] Activity activity)
        {
            var result = await _handler.HandleUpdateActivityAsync(HttpContext.Request.Headers["Authorization"], conversationId, activityId, activity).ConfigureAwait(false);
            
            var serializerSettings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                Formatting = Formatting.Indented,
                DateFormatHandling = DateFormatHandling.IsoDateFormat,
                DateTimeZoneHandling = DateTimeZoneHandling.Utc,
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                ContractResolver = new ReadOnlyJsonContractResolver(),
                Converters = new List<JsonConverter> { new Iso8601TimeSpanConverter() }
            };

            return new JsonResult(result, serializerSettings);
        }
```

When we create a .Net 3.1 web api app with a controller that derives from the base class in the library we get a `MissingMethodException` when the `UpdateActivityAsync` method is called:

![image](https://user-images.githubusercontent.com/12264946/71691650-f13dbc80-2d75-11ea-98be-150fb72ea7f8.png)

From reading some other posts, it seems that JsonResult has moved to another assembly and the constructor signature has changed to take an `object` type instead of a Json.Net `JsonSerializerSettings` but the runtime doesn't seem to be able to find either method. 

We tried recompiling the library with the `BaseController` with .Net Standard 2.1 and we still see the same issue, our library with the BaseController needs to support .Net Core 2.1, 2.2 and 3.x, is there something we can set on the consuming WebApi project so JsonResult can be resolved correctly?

**Comment by davidfowl** [comment]
This method was removed in 3.0. Your library needs to cross compile to .net core 3.x to account for the breaking change

**Comment by pranavkm** [comment]
As @davidfowl pointed out, this was a binary breaking change in 3.0: https://github.com/aspnet/Announcements/issues/389. https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrate-libraries-via-multi-targeting has a guide for cross-compiling library projects to support multiple versions of ASP.NET Core.

**Comment by gabog** [comment]
Thank you @davidfowl & @pranavkm, the link you provided and [this article](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.0&tabs=visual-studio) helped me with updating my library to cross compile for NetCore 3.0 and Net Standard 2.0.
