### ISSUE TITLE
Redirect to location with umlaut is not encoded correctly on azure app service.

### ISSUE THREAD

**Issue by Thom3189-coder** [aspnet/AspNetCore#18090]
### Describe the bug
When performing a redirect to '/stenströms/', the resulting location header sent to the client is: '/stenstrÃ¶ms/', which looks like the wrong encoding is used when producing the response byte array. This only happens on the azure app service where our site is hosted. Locally on IIS (also in-proc hosting) this works fine.

### Further technical details
- ASP.NET Core version: 3.0.0

**Comment by blowdart** [comment]
Have you logged a bug with app service?

**Comment by Thom3189-coder** [comment]
Not yet as I assumed the aspnetcoremodulev2 or asp core directly before that are responsible for producing the response bytes which are from this repo. If that is not the case I can open a bug with app service, if you could direct me to where I can do that?

**Comment by jkotalik** [comment]
This seems like it could be an issue with the Azure Gateway between the client and ANCMv2 as well. In general, headers with non ascii characters can be fuzzy. 

cc @suwatch, where can I redirect this?

**Comment by Tratcher** [comment]
How did you generate the redirect?

**Comment by Thom3189-coder** [comment]
@Tratcher I perform the redirect using HttpResponse.Redirect(string, boolean) method. Do you mean that I should be encoding the string myself before passing it?

**Comment by Tratcher** [comment]
Yes. "This must be properly encoded for use in http headers where only ASCII characters are allowed."
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponse.redirect?view=aspnetcore-3.1

**Comment by anurse** [comment]
As @Tratcher indicated, this is by design. Response URLs must be URL encoded before passing them to `Response.Redirect`.
