### ISSUE TITLE
New URL parameter values are not accessible in NavigationManager.LocationChanged

### ISSUE THREAD

**Issue by miroslavp** [aspnet/AspNetCore#18097]
### Describe the bug
If I have a page component with the following page directive 
``` C#
@page "/mypage/{SomeID:int}"
```
and navigate to it in Blazor WASM with
``` C#
NavigationManager.NavigateTo("mypage/1")
```
, I should be able to get the id value from the SomeID parameter property in the LocationChanged event handler.
``` C#
[Parameter] public int SomeID { get; set; }
private async void NavigationManager_LocationChanged(object sender, Microsoft.AspNetCore.Components.Routing.LocationChangedEventArgs e)
{
  //the id in e.Location is not the same as in SomeID
}
```

 Unfortunately SomeID contains the old value from before the navigation. A possible workaround is to parse the id from e.Location. 
The event name "LocationChanged" suggests that the event is completed, so I guess we should be able to get the new value directly from the property .

### Further technical details
- ASP.NET Core version 3.1.100
- Blazor WASM 3.1.0-preview4.19579.2

**Comment by miroslavp** [comment]
Forgot to mention that the navigation is made from the same page. Basically I'm redirecting to the same page with different parameter

**Comment by pranavkm** [comment]
@miroslavp the recommendation would be to use `OnParametersSet` lifecycle event to track the navigation. `LocationChanged` is a fairly low-level primitive and Blazor has no guarantees about it's ordering with respect to the `Router`'s event handler.

**Comment by miroslavp** [comment]
@pranavkm How can I detect in `OnParametersSet` that there was a navigation from the same page component before that? 
The thing is, I need this to workaround the problem that when redirecting to the same page component, `OnInitialized`/`OnInitializedAsync` is not invoked. I want to execute the logic which would have been in `OnInitialized`/`OnInitializedAsync`.

**Comment by pranavkm** [comment]
Couldn't you execute the code again as part of `OnParametersSet` \ `OnParametersSetAsync`?

**Comment by miroslavp** [comment]
I could, but I want to execute it only if there was a navigation to the same page (only when `OnInitialized` was not invoked). Maybe a possible solution is to set a flag in `OnInitialized` and call my method in `OnParametersSet` only when the flag is not set. A little bit hacky, but I guess it should work.

**Comment by mrpmorris** [comment]
```
int valueBefore = SomeId;
base.OnParametersSet(..........);
if (SomeId != valueBefore)
  DoSomething() ;
```
