### ISSUE TITLE
WASM Blazor goes into infinite loop on Task.GetAwaiter().GetResult();

### ISSUE THREAD

**Issue by stanac** [aspnet/AspNetCore#18092]
### Describe the bug
I am working on a Blazor app, hosted on the client. In one of the services, on the client side, constructor is invoking JS interop to get a value from local storage, so I am calling ValueTask<T> synchronously with `ValueTask<T>.GetAwaiter().GetResult()` which break blazor with (I am guessing) infinite loop. Page is stuck, chrome is taking ~20% of CPU (on 4 cores/8 threads intel cpu). I have tried to change method to return `Task<T>` instead of `ValueTask<T>`, it didn't help.

(I know I shouldn't call dependencies in the ctor, however that was the quickest and easiest solution)

### To Reproduce
Create new ASP.NET hosted Blazor client side app, from template.

Change `Startup.cs` to look like this:
```csharp
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        Task.Delay(1).GetAwaiter().GetResult(); // this line breaks the app
    }

    public void Configure(IComponentsApplicationBuilder app)
    {
        app.AddComponent<App>("app");
    }
}
```

Client project csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.1.0-preview4.19579.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.1.0-preview4.19579.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.1.0-preview4.19579.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.1.0-preview4.19579.2" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\BlazorApp1.Shared.csproj" />
  </ItemGroup>

</Project>
```

### Further technical details
- ASP.NET Core version: 3.1.100
- Include the output of `dotnet --info`
```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
```
Microsoft Visual Studio Community 2019 Preview
Version 16.5.0 Preview 1.0
VisualStudio.16.Preview/16.5.0-pre.1.0+29521.150
Microsoft .NET Framework
Version 4.8.03752
```

### Workaround
Workaround is to simply don't block async tasks.

Is there another workaround that would allow us to block async tasks?

**Comment by pranavkm** [comment]
Blazor WASM runs in a single-threaded environment. Consequently any blocking calls will deadlock the application.  

> Workaround is to simply don't block async tasks.

That's effectively the only solution. I'd go further and say in general, [avoiding blocking calls](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) is the way to go.

**Comment by stanac** [comment]
@pranavkm thanks for prompt response.

It would be nice to have at least compiler warning or runtime exception when this happens.
