### ISSUE TITLE
Use linux sendfile for PhysicalFile response

### ISSUE THREAD

**Issue by maknapp** [aspnet/AspNetCore#18093]
### Is your feature request related to a problem? Please describe.
I was expecting PhysicalFile to use the sendfile system call in linux but all it does is stream the file using this fallback:

https://github.com/aspnet/AspNetCore/blob/7ae6d1e3791e09db1fe2b032044208b04d4cc3b1/src/Http/Http/src/SendFileFallback.cs

This fallback uses much more CPU and memory to serve files than using the sendfile system call.

### Describe the solution you'd like
I'd like an option to enable sendfile responses, either in setup or for each response.

**Comment by Tratcher** [comment]
Prior discussion here:
https://github.com/aspnet/KestrelHttpServer/issues/1593
https://github.com/aspnet/KestrelHttpServer/issues/1673

Summary:
- It wouldn't work with SSL
- The linux APIs are not async

**Comment by maknapp** [comment]
The linux kernel has TLS support: https://github.com/torvalds/linux/commit/3c4d7559159bfe1e3b94df3a657b2cda3a34e218

**Comment by Tratcher** [comment]
> For reference, the linux kernel has TLS support (for this purpose): [torvalds/linux@3c4d755](https://github.com/torvalds/linux/commit/3c4d7559159bfe1e3b94df3a657b2cda3a34e218) and
> https://www.kernel.org/doc/html/latest/networking/tls.html

That would require re-designing Kestrel's TLS support to take advantage of.

**Comment by anurse** [comment]
> For reference, the linux kernel has TLS support (for this purpose)

This would require a change in the runtime to support this directly on `Socket`.

> * The linux APIs are not async

This is another main reason we don't plan to do this.

Closing as we don't plan to add this support.
