### ISSUE TITLE
Using two await inside the blazor lifecycle doesn't work properly

### ISSUE THREAD

**Issue by Indrajith-Sync** [aspnet/AspNetCore#18105]
I am using the following operation in the Blazor lifecycle with multiple await actions.

protected override async Task OnInitializedAsync() {

 //this action is performed.
`forecasts = await Http.GetJsonAsync<WeatherForecast[]>("sample-data/weather.json");`

// this action is not perfomred
`await someOperation(); `
}

Any suggestion on this query ?

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by pranavkm** [comment]
@Indrajith-Sync looks like your question was already answered here: https://github.com/aspnet/AspNetCore/issues/18104#issuecomment-570552966

**Comment by Indrajith-Sync** [comment]
Hi @pranavkm 

Below is the sample repo for my use-case 
https://github.com/Indrajith-Sync/Blazor/tree/master/Await_delay

In the above sample, I have updated the private variable in a button click using two **Task.Delay** with **await**  in which both is executed and only the first value is changed and the second one is not changed. But on the second button click the value is changed.


I just want to know how the await operation takes place when called multiple times in a method.

**Comment by mrpmorris** [comment]
You need to return Task not void, otherwise blazor won't have a task or can await in order to execute StateHasChanged when it finishes.
