### ISSUE TITLE
Async initialization in Main not working

### ISSUE THREAD

**Issue by RedDeathGitHub** [aspnet/AspNetCore#18104]
- Description:

I want/need to do some basic initialization on app startup, like calling an API and getting my initial configuration.
I found a neat solution that it could be done in async Main for ASP Core, so I tried to reproduce it for Blazor.
But, it seems that app just "hangs" in the browser.
You'll find Autofac setup below, but it works fine, it's the Task.Delay part that breaks the App.
Of course, in my code that delay only simulates API call.

If there is better way to achieve this, please provide a sample - actually and update to official docs would be great, as this will be a common scenario.
Again - this is initial/global initialization, not specific page initialization ;).

- To Reproduce:

``` C#
public class Program
    {
        public static async Task Main(string[] args)
        {
            IWebAssemblyHost host = CreateHostBuilder(args).Build();
            await Initialize(host);
            host.Run();
        }
        
        public static IWebAssemblyHostBuilder CreateHostBuilder(string[] args) =>
            BlazorWebAssemblyHost.CreateDefaultBuilder()
                .UseServiceProviderFactory(new AutofacServiceProviderFactory(b => b.RegisterModule<ClientModule>()))
                .UseBlazorStartup<Startup>();

        public static async Task Initialize(IWebAssemblyHost host)
        {
             await Task.Delay(2000);
        }
    }
```

- Other info:
Client side Blazor 3.1.10
Preview Visual Studio 16.5

**Comment by RedDeathGitHub** [comment]
@SteveSandersonMS - hi, sorry to bother you, but I believe you might find this scenario interesting.
Much :heart: to Blazor, it's the best thing MS did in the last decade!

**Comment by SteveSandersonMS** [comment]
Thanks for contacting us!

`async main` isn't supported in the version of Blazor you're using currently. However the good news is that [we have implemented support for it since the last release](https://github.com/aspnet/AspNetCore/pull/17673), and the feature will be included in the next preview release within the next month.

**Comment by RedDeathGitHub** [comment]
Wow, awesome! Thanks.

**Comment by Indrajith-Sync** [comment]
hi @SteveSandersonMS 

Is it possible to use two await inside a blazor lifecyle method as like below.

**protected override async Task OnInitializedAsync() {

//this action is performed.
forecasts = await Http.GetJsonAsync<WeatherForecast[]>("sample-data/weather.json");

// this action is not perfomred
await someOperation();
}**

Any suggestion for this query ?

**Comment by SteveSandersonMS** [comment]
Yes, multiple awaits works fine. Blazor doesn’t even know you are doing that as it’s inherent to C# itself. 

If your code isn’t working that way, you have some other issue.
