### ISSUE TITLE
JsonPatch with Web API and dynamic types

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/AspNetCore#18120]
I have the following method.

```c#
    [HttpPatch("{id}")]
    [AllowAnonymous]
    public async Task<IActionResult> Patch(string id, [FromBody]JsonPatchDocument patchDoc)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var origin = await _documentSession.LoadAsync<dynamic>(id);
        var patched = origin.DeepClone();

        patchDoc.ApplyTo(patched);

        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        await _documentSession.SaveChangesAsync();

        return Ok(new
        {
            original = origin,
            patched = patched
        });
    }
```

Using this PATCH request I end up with a non modified object?

```
curl --location --request PATCH 'https://localhost:5001/pages/homes%2F1-A' \
--header 'Content-Type: application/json' \
--data-raw '{
    "op": "replace",
    "path": "/heading",
    "value": "Bar"
}'
```

**Comment by marcuslindblom** [comment]
I can see now that I patch the wrong object I think 🤔...

**Comment by pranavkm** [comment]
> I can see that this pr is merged into master but I guess that this is not a part of any release yet?

Yes, the PR \ issue is targeted for the 5.0 release.

**Comment by marcuslindblom** [comment]
@pranavkm are there any previews available for release 5?

**Comment by pranavkm** [comment]
@marcuslindblom not as yet. The first preview is scheduled for some time in February - https://github.com/aspnet/AspNetCore/milestone/61, although I'm not entirely certain how accurate that date it. 

In the meanwhile, you could try out our nightlies using the instructions available here https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md.
