### ISSUE TITLE
USING "OVERRIDE" INTELLISENSE HELPER IN VS 2019 INSIDE BLAZOR COMPONENT RESULTS IN ERASURE OF FILE CONTENTS

### ISSUE THREAD

**Issue by borseno** [aspnet/AspNetCore#18122]
### Describe the bug
In visual studio 2019, when using "override" intellisense helper inside blazor component, some part of blazor component's content gets erased.

### To Reproduce

VIDEO: https://youtu.be/oVYKc7UEgdA (IT WAS THE SECOND TRY TO CAPTURE IT, AND AFTER SOME DANCING IT STARTED TO WORK, BUT IT DOESNT WORK IN THE BEGINNING OF THE VIDEO)

Start a new blazor client application, type "override" inside blazor component, choose any method to override.

Consider this repo https://github.com/borseno/TempRepoForBlazorIssue

Add a page with this kind of content:

``` C#
@page "/participatedIn"
@inject IVotingsService service
@using Votings.Shared.DTO

<h3>Votings you have participated in</h3>

@code {
    private OptionInfo optionInfo;

    // add override keyword here and try to choose any of popped up methods
}
```

### Further technical details
- ASP.NET Core version - v3.1.0-preview4.19579.2
- The output of `dotnet --info` 
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE: Licensed Microsoft Visual studio professional 2019 of 16.4.1 version

**Comment by pranavkm** [comment]
@NTaylorMullen could you have a look?

**Comment by NTaylorMullen** [comment]
@borseno thanks for the video, repro and all the information! Such an interesting set of circumstances; I've been plugging away at it for a while and I haven't been able to reproduce it myself which is definitely makes things harder to diagnose.

![image](https://i.imgur.com/AuJIVss.gif)

Sadly with something like this we wont be able to work on a fix without some sort of consistent repro. I know that's a sucky resolution but there's so many factors that happen simultaneously in todays Razor editing experience it's near impossible to fix issues without one.
