### ISSUE TITLE
Adding a custom AuthenticationHandler doesn't work / HandleAuthenticateAsync does not get invoked

### ISSUE THREAD

**Issue by jochenz** [aspnet/AspNetCore#18125]
I started from the example on [the official documentation page](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#mock-authentication) and defined a simple custom authentication handler, which I added to my integration test startup:

``` C#
    internal class DemoApiFactory : WebApplicationFactory<Startup>
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureTestServices(services =>
            {
                services
                    .AddAuthentication(TestAuthentication.Scheme)
                    .AddScheme<AuthenticationSchemeOptions, TestAuthenticationHandler>(TestAuthentication.Scheme, null);
            });
        }
    }
```

When running tests with this code, the `TestAuthenticationHandler` does get challenged, but `HandleAuthenticateAsync` never gets invoked.

[Here's a simple solution on github with integration tests to reproduce the issue](https://github.com/jochenz/aspnetcore-testauth).

The `TestAuthenticationHandler` is defined as:

``` C#
    internal class TestAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
    {
        public TestAuthenticationHandler(IOptionsMonitor<AuthenticationSchemeOptions> options,
            ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock)
            : base(options, logger, encoder, clock)
        {
        }

        protected override Task<AuthenticateResult> HandleAuthenticateAsync()
        {
            var testAuthHeaderPresent = Request
                .Headers[HeaderNames.Authorization]
                .Contains(TestAuthentication.Scheme);

            var authResult = testAuthHeaderPresent ? AuthenticatedTestUser() : AuthenticateResult.NoResult();

            return Task.FromResult(authResult);
        }

        protected override Task HandleChallengeAsync(AuthenticationProperties properties)
        {
            Response.Headers["WWW-Authenticate"] = TestAuthentication.Scheme;

            return base.HandleChallengeAsync(properties);
        }

        private static AuthenticateResult AuthenticatedTestUser()
        {
            var claims = new[] { new Claim(ClaimTypes.Name, "Test user") };
            var identity = new ClaimsIdentity(claims, TestAuthentication.Scheme);
            var principal = new ClaimsPrincipal(identity);
            var ticket = new AuthenticationTicket(principal, TestAuthentication.Scheme);

            return AuthenticateResult.Success(ticket);
        }
    }
```

**Comment by Kahbazi** [comment]
Hi @jochenz. In order to get to `HandleAuthenticateAsync`, you need to call [HttpContext.AuthenticateAsync()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationhttpcontextextensions.authenticateasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.AuthenticateAsync);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=aspnetcore-3.1) or add the `app.UseAuthentication()` in your pipeline which does that for you.

**Comment by jochenz** [comment]
Indeed... how did I manage to lose that much time? :-(

**Comment by jochenz** [comment]
Thank you very much for your help, @Kahbazi 👍. This is one of those moments were I feel rather stupid 😳
