### ISSUE TITLE
TryUpdateModelAsync using JObject

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/AspNetCore#18136]
Is it possible in some way to update one original JObject with the changed values from another JObject?

**Comment by pranavkm** [comment]
JsonPatch would be the closest solution to this, but it [does not currently support](https://github.com/aspnet/AspNetCore/issues/2429) updating `JObject` instances. I'd recommend using StackOverflow to figure out how to do this with the current version of the framework.
