### ISSUE TITLE
[Question] return RedirectToAction(nameof(Authorize), params); causes an Invalid Redirect problem

### ISSUE THREAD

**Issue by ranzeplay** [aspnet/AspNetCore#18146]
Here's my code
```
return RedirectToAction(nameof(Authorize),
      new AuthorizeModel
      {
              AppId = model.AppId,
              RedirectUri = model.RedirectUri,
              State = model.State
      });
```

The logic is when user authorized, I'll redirect him to my Authorize page. But it causes an InvalidRedirect problem and opened the VMS document.
Nothing showed by Chrome, and everything works fine.
It just can't redirect successfully

**Comment by abcdefgabcefg** [comment]
Can you share Authorize action code? And what is VMS document? I just can't get did you fail with exception or not?
