### ISSUE TITLE
build source code using restore.cmd get error: tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props

### ISSUE THREAD

**Issue by huazhb** [aspnet/AspNetCore#18158]
Follow the Build ASP.NET Core from Source, clone the source code, run the restore.cmd and get below error: \AspNetCore\src\Servers\IIS\AspNetCoreModuleV2\OutOfProcessRequestHandler\OutOfProcessRequestHandler.vcxproj(30,3): error MSB4019: The imported project "\AspNetCore\.tools\msbuild\16
.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. 

I check the folder, and there is no \AspNetCore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC folder.

**Comment by huazhb** [comment]
Solved. Need to run the ./eng/scripts/InstallVisualStudio.ps1 to install the correct component. And it required the visual studio enterprise version.

**Comment by huazhb** [comment]
Close

**Comment by plabanauskis** [comment]
The script at ./eng/scripts/InstallVisualStudio.ps1 supports a number of parameters, one of which is `Edition` allowing you to pick any edition of the Visual Studio.
