### ISSUE TITLE
Core 2.0 CORS api doesn't work in IIS 8.5

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/AspNetCore#2232]
Originally opened by @kostyamy here: https://github.com/dotnet/core/issues/951
# Issue Title

Having some troubles with hosting .NET Core 2.0 MVC bases api (not views but pure api) on Windows 2012 R2: IIS 8.5 -> Kestrel on dynamic port.

Client is Chrome both kinds - "fetch" and "XHR" but i don't think it makes any difference

- "same origin" requests work fine
- locally on my dev machine Surface , Windows 10 same origin and cross-domain (faked via system32\drivers\etc\hosts) work fine even using IIS proxy ->Kestrel chain. Please note not IIS Express but actual IIS 10.
- 2012 box IIS 8.5 no luck :-( looks like IIS not passing through any cross-domain api calls since even IIS log and tracing show NO activities on "<domain>/api/<controller>/<method>" urls.  At the same time STATIC html files are being served just fine but not by Kestrel but pure IIS.

Tried to launch api form CLI: dotnet .\<my-api>.dll and looks like it starts just find and hosts on localhost:<dynamic port>

Here is my web.config (pretty much out of box)
```
<system.webServer>
    <handlers>
      <add name="aspNetCore" path="api/*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\<my-api>.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```
i see no system level error in event log, no IIS logs, nothing.
If AspDotNetModule Core fails somehow while starting under IIS then where besides empty system event log i should be looking at ???

If needed I can provide more information.

Thanks in advance,
-K

From: @brockallen

My guess is that IIS is eating OPTIONS requests. Do you have anything configured in IIS to process those? 

https://brockallen.com/2012/10/18/cors-iis-and-webdav/

From: @kostyamy

all clean. no filters of any kind. looks like my original post is missing content of the web.config
but it's actually a default one produced by the dotnet publish -c command
so only AspDotNetModule entry and that's it

**Comment by coin8086** [comment]
Is there anyone looking into this? I have nearly the same problem.

**Comment by Petermarcu** [comment]
+ a few folks from ASP.NET

**Comment by gbfromhb** [comment]
I'm having the same problem with IIS 10, and can not get this working either. 

I'm using Jquery to call the api with the following:
`
      var contactInfo = {
         FullName: $(this).find("input[name='FullName']").val(),
         EmailAddress: $(this).find("input[name='EmailAddress']").val(),
         WebsiteUrl: $(this).find("input[name='WebsiteUrl']").val(),
         Comment: $(this).find("textarea[name='Comment']").val()
      }
      $.ajax({
         url: url,
         xhrFields: {
            withCredentials: true
         },
         crossDomain: true,
         type: 'POST',
         data: JSON.stringify(contactInfo),
         contentType: "application/json",
         error: function(errors, ajaxOptions, thrownError) {
            alert(errors.statusText + ' (' + errors.status + ') : ' + errors.responseText);
         },
         success: function(data) {
            var el = $('#contactInfoThankYou');
            var divEl = el.find('div');

            if (data.fullName != null) {
               divEl.html(divEl.html().replace('@[FullName]', data.fullName));
            } else {
               divEl.html(divEl.html().replace('@[FullName]', ''));
            }
            el.css('display', 'block');
         },
         async: true
      });
   });
`
On my local machine starting with the website making the request on one port address, and the endpoint being on a different port address, I initially was getting the 401 Unauthorized. I then put the following in the Startup.cs in the ConfigureServices on the webapi application,. 

`         services.AddCors(options => {
            options.AddPolicy("ContactInfoCorsPolicy",
               builder => builder
                  .AllowAnyOrigin()
                  .AllowAnyMethod()
                  .AllowAnyHeader()
                  .AllowCredentials()
               );
         });`

In the webapi controller I decorated the controller with [AllowAnonymouse] and the method with [EnableCors("ContactInfoCorsPolicy")]. It started working locally on IIS Express, however I have not been able to get it to work on the IIS server.

I have tried putting the following in the web.config of the WebApi website on the IIS server:

`    <system.webServer>
<httpProtocol>
      <customHeaders>
	<add name="Access-Control-Allow-Credentials" value="true"/>
        <add name="Access-Control-Allow-Origin" value="*" />
	<add name="Access-Control-Allow-Methods" value="GET, PUT, POST, DELETE, HEAD, PATCH" />
        <add name="Access-Control-Allow-Headers" value="content-type" />
      </customHeaders>
    </httpProtocol>
   </system.webServer>`

and still no good, After adding the above II started seeing something in the request and response that looked like it should work, but no good.
![image](https://user-images.githubusercontent.com/2523931/34011994-ef07f10e-e0c6-11e7-911a-980284adea67.png)

Any suggestions would be greatly appreciated.

**Comment by fonbrauzen** [comment]
><add name="Access-Control-Allow-Credentials" value="true"/>
        <add name="Access-Control-Allow-Origin" value="*" />

AFAIK when you use credentials you can use only one trusted origin, so here wildcard can't be used for origins.

Recently I got the same problem - .NET Core Web.API/MVC + IIS 8.5 + CORS. I have installed SharePoint on the same machine, so I have WebDAV here. I ended with a bit not straightforward solution - enabled it on IIS and disabled in Startup.cs. Seems this solve my problems, but on local deployments, it's pretty unusable - each deploy rewrite web.config.

**Comment by brockallen** [comment]
> AFAIK when you use credentials you can use only one trusted origin, so here wildcard can't be used for origins.

Well, you can use any origin, but it must be explicitly emitted at runtime.

**Comment by maikschoeneich** [comment]
I am facing the same issue as @gbfromhb right now. Any suggestions so far?

**Comment by suhasagubb** [comment]
I am facing the same issue as @gbfromhb. Any resolution? [repos:CORS](https://github.com/aspnet/Home/labels/repo%3ACORS)

**Comment by PSausM** [comment]
Any resolution to this?

**Comment by mkArtakMSFT** [comment]
Sorry for the late response on this one.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
@kostyamy, @coin8086, @gbfromhb, @fonbrauzen, @maikschoeneich, @suhasagubb, and @PSausM searching around a bit, I found the many recommendations which cover the IIS OPTIONSVerbHandler, ExtensionlessUrlHandler and CORS module in addition to the WebDav module e.g.
- https://stackoverflow.com/questions/22495240/iis-hijacks-cors-preflight-options-request
- http://geekswithblogs.net/abhijeetp/archive/2016/06/04/adding-cors-support-for-asp.net--webapi-the-no-hassle.aspx
- http://benfoster.io/blog/aspnet-webapi-cors#body%20%3E%20div%20%3E%20section%20%3E%20article%20%3E%20div.post-content%20%3E%20h3:nth-child(13)

Note:
- The ANCM handler (configured per-application) runs _after_ every handler configured machine- or site-wide.
- Some of the above descriptions enable the IIS CORS module which is not what you want when using MVC's CORS service or middleware.

If the above recommendations help, please let us know.

**Comment by dougbu** [comment]
Thank you for your feedback. We're closing this issue as the questions asked here have been answered.
