### ISSUE TITLE
Performance issue with stream download

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/AspNetCore#2233]
@chintan3100 commented on Sep 5
I am downloading 400 MB file on local machine with 7 MB/Second (.net core 2.0) same code run with .net framework 4.6 download speed 100 MB/Second.

public IActionResult DownloadDocument(Guid documentUniqueId)
{
var bytes = System.IO.File.OpenRead(@"D:\home\site\wwwroot\file\Organizer01_2017-09-03 (14) (3).zip");
return File(bytes, "application/octet-stream");

}
File size 400 MB . API on local system. FIle on local system
Performance issue with stream download hasno dependencies

+ add dependency
 @Petermarcu
@JeremyKuhne can we get this tracked in dotnet/corefx?
 @JeremyKuhne
     Member
JeremyKuhne commented on Sep 5
This issue was also opened as: aspnet/Performance#246

@chintan3100 We need to know exactly how the FileStream is being written. What is the File class you're using? If you're writing via ASP.NET apis it would probably be better to start on that end.
 @chintan3100
     
chintan3100 commented 28 days ago
I am using .net core. Please refer below code

public IActionResult DownloadDocument(Guid documentUniqueId)
{
var bytes = System.IO.File.OpenRead(@"D:\home\site\wwwroot\file\Organizer01_2017-09-03 (14) (3).zip");
return File(bytes, "application/octet-stream");

}
 @JeremyKuhne
     Member

Presumably you're talking about System.Web.Mvc.Controller.File. You should probably start with https://github.com/aspnet/Mvc/issues. The ASP.NET team is the right starting point.

**Comment by Tratcher** [comment]
@sebastienros

**Comment by sebastienros** [comment]
Not familiar at all with it. I will ask around who knows about it.

**Comment by Tratcher** [comment]
@sebastienros this is an end-to-end performance question, it's may or may not be related to FileResult. We'd need to start with their sample code and peal off layers to see if it's FileResult, Kestrel, etc..

**Comment by chintan3100** [comment]
Thanks for reply.

I think sample code not require. 
Please run below code with .net core 2.0 and .net 4.5 framework you will see download speed difference.
public IActionResult DownloadDocument(Guid documentUniqueId)
{
var bytes = System.IO.File.OpenRead(@"D:\home\site\wwwroot\file\Organizer01_2017-09-03 (14) (3).zip");
return File(bytes, "application/octet-stream");

}

**Comment by anurse** [comment]
Please post a runnable sample project so we can see the full context of the issue you are seeing. Closing as we don't have a reproducible sample to investigate.
