### ISSUE TITLE
DeveloperExceptionPageMiddleware: add a feature to HttpContext.Features to mark own existence

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/AspNetCore#2249]
There's a common pattern of adding DeveloperExceptionPageMiddleware in development environment like
```
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}
```
Usually we add the middleware first. The middleware catch all exception and shows nice page. But in non-development env user will get a generic response with 500 status code.

If I add my own middleware after DeveloperExceptionPageMiddleware and try to catch exceptions in it then I need to know will DeveloperExceptionPageMiddleware runs or not. If not then I'll show my own error page. If it runs then I'll just do nothing as it's some sense to see nice page from DeveloperExceptionPageMiddleware then my own.

The problem is how can I detect that DeveloperExceptionPageMiddleware  will run. Of cause I can hard-code environment checking but obviously it's not correct.

As a workaround I can add my middleware before DeveloperExceptionPageMiddleware. But if I develop a library I have to tell users to not forget to add my middleware before DeveloperExceptionPageMiddleware and not after. It's not very robust.

My suggestion is to add a runtime feature to context which would allow detecting DeveloperExceptionPageMiddleware. In the same way as it's implemented in StatusCodePagesMiddleware:
```
      StatusCodePagesFeature statusCodeFeature = new StatusCodePagesFeature();
      context.Features.Set<IStatusCodePagesFeature>((IStatusCodePagesFeature) statusCodeFeature);
      await this._next(context);
```

So DeveloperExceptionPageMiddleware could do the similar thing.
```
      DeveloperExceptionPageFeature feature = new DeveloperExceptionPageFeature();
      context.Features.Set<IDeveloperExceptionPageFeature>((IDeveloperExceptionPageFeature) feature);
      await this._next(context);
```

then I could do something like this:
```
	try
	{
		await _next.Invoke(context);
	}
	catch (Exception ex)
	{
		if (context.Features.Get<IDeveloperExceptionPageFeature>() == null)
		{
			// no DeveloperExceptionPageMiddleware in the pipeline, show our own error page:
			var view = new ErrorPage(new ErrorPageModel());
			await view.ExecuteAsync(context);
		} 
		else
		{
			// let DeveloperExceptionPageMiddleware do what it can
			throw;
		}
	}
```

**Comment by Tratcher** [comment]
In the templates we handle this with an else:
https://github.com/aspnet/Templates/blob/f237bb024e1c8f05a7d78c215be2224022d2c153/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Startup.cs#L89-L92

**Comment by evil-shrike** [comment]
Yeah, sure, but it puts some obligations on user code in Startup. If some lib/framework wants to add such a middleware it has no ability to know whether DeveloperExceptionPageMiddleware  exists or not.
Also a middleware could be not an full analogue of DeveloperExceptionPageMiddleware  for production, it could include additional logic like handling status codes as I mentioned, so it cannot be put in `else`.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
