### ISSUE TITLE
Add first class IRouteValuesFeature 

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2323]
_From @davidfowl on Friday, September 1, 2017 9:20:32 PM_

Routing is a such a fundamental feature of http request processing there should be a first class low level feature that describe the available route values as part of the http request. There should also be a first class property along the same lines as HttpRequest.Query, HttpRequest.Headers, HttpRequest.Cookies etc.

```C#
public interface IRouteValuesFeature
{
    IRouteValuesCollection RouteValues { get; set; }
}
```

```C#
public abstract class HttpRequest
{
    public abstract IRouteValuesCollection RouteValues { get; set; }
}
```

```C#
public interface IRouteValuesCollection : IEnumerable<KeyValuePair<string, object>>
{
    int Count { get; }

    ICollection<string> Keys { get; }

    bool ContainsKey(string key);

    bool TryGetValue(string key, out object value);

    object this[string key] { get; }
}
```

Any routing implementation that provides parses route parameters and ends up with essentialy name value pairs should be able to provide this feature.

Example usage:

```C#
app.UseRouter(routes =>
{
    routes.MapGet("/hello/{name}", context =>
    {
         return context.Response.WriteAsync($"Hello {context.Request.RouteValues["name"]}");
    });
});
```

**Open Questions**

1. Should we augment the above with DataTokens? aka items for routes or do we tell people to use HttpContext.Items for that? Either way is fine but I don't think it should be first class on the HttpContext (I can be convinced otherwise though).

Verdict: Items will be the replacement.

2. Should we type-forward and move RouteValueDictionary to HttpAbstractions or should we stick with IRouteValuesCollection? IRouteValuesCollection matches our other collection types. If we do go with the interface (which is what i'm leaning towards), then we need to make sure it can be implemented by RouteValueDictionary (for compat).

/cc @rynowak @jbagga @Tratcher @Eilon 

_Copied from original issue: aspnet/HttpAbstractions#933_

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, September 1, 2017 9:49:47 PM_

Per our IM chat, I don't think Data Tokens are needed on the interface. HttpContext.Items ought to be enough.

**Comment by aspnet-hello** [comment]
_From @jchannon on Friday, September 29, 2017 4:16:05 AM_

Spot on with this @davidfowl I was looking at adding extensions to Request to get a nice api to retrieve route values out. It would also be nice to have it parse and return the values as proper types.  If you have `/person/{id:int}` I dont want to have to do `context.Request.RouteValues["id"]` then convert it to an `int`. Currently I have extensions on RouteData that allows me to do `routeData.AsInt("id")` which does the conversion underneath

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, September 29, 2017 8:28:35 AM_

@rynowak I'm parking this on your plate because we'll either do something, do nothing, or dispatch something based on the work you're doing w/ @jbagga .

**Comment by aspnet-hello** [comment]
_From @rynowak on Friday, September 29, 2017 8:33:17 AM_

@jchannon - what's the ultimate usage of this - can you share the code you want to write, not just the `routeData.AsInt("id")` part, but where are you calling this from and what do you want it to do?

**Comment by aspnet-hello** [comment]
_From @jchannon on Friday, September 29, 2017 8:35:36 AM_

I'm using it in my library Botwin - https://github.com/jchannon/botwin

For example I have:

```
this.Get("/actors/{id:int}", async (req, res, routeData) =>
{
    var person = actorProvider.Get(routeData.AsInt("id"));
    await res.Negotiate(person);
});


OR

this.Get("/actors/{id:int}", async (ctx) =>
{
    var person = actorProvider.Get(ctx.GetRouteData().AsInt("id"));
    await ctx.Response.Negotiate(person);
};
```

If I declare a route constraint that is `{id:int}` I should be able to pull that integer out in my handler.

**Comment by aspnet-hello** [comment]
_From @rynowak on Friday, September 29, 2017 8:44:53 AM_

And when `id` is not convertable, you want a 404?

**Comment by aspnet-hello** [comment]
_From @jchannon on Friday, September 29, 2017 8:45:36 AM_

Yup. I assumed it already did that....

**UPDATE** It does but not sure if thats because it didn't find a route or whether the non int value caused it

**Comment by aspnet-hello** [comment]
_From @asbjornu on Saturday, September 30, 2017 11:29:43 AM_

@davidfowl: Much support from me for this feature. 👍  But would it be possible to have `Request.Route` instead of `.RouteValues` so we have an extension point? The first obvious sub-properties would be `.Name` and `.Values` (the latter being your `IRouteValuesCollection`).

**Comment by aspnet-hello** [comment]
_From @davidfowl on Saturday, September 30, 2017 11:38:31 AM_

@asbjornu whatever is on the HttpContext needs to be the most generic, lowest level thing that all implementations will share. Routes don't necessarily have a name. I'd like this to be similar to query string and headers. The feature itself could have more things on it but I'm not convinced we need anything other than values at the moment.

**Comment by aspnet-hello** [comment]
_From @jchannon on Saturday, September 30, 2017 12:18:22 PM_

Does anything already exist for route data or could this do it? See Nancy's
RouteDescription. Allows you to get/set meta data for routes and can then
use it for things like Swagger

**Comment by aspnet-hello** [comment]
_From @davidfowl on Saturday, September 30, 2017 12:25:00 PM_

@jchannon This isn't about features for swagger, this is about the *lowest* level primitive to represent route values in the request. Each routing framework has their own set of features and for those, you can get another feature which has the extra metadata. This isn't trying to be subsume those features, this is about route values (hence the feature name)

**Comment by aspnet-hello** [comment]
_From @asbjornu on Sunday, October 1, 2017 2:38:52 AM_

@davidfowl: Sure. My point is just that if we ever want to add anything other than values, it will have to go into a new property since this is restricted to values. Having a class that in the first implementation only exposes a `Values` property at least leaves room for extension.

Also, being able to figure out which route was matched has always been a wish I've had when working with MVC. Whether that's identified by name or something else is just an implementation detail.

**Comment by aspnet-hello** [comment]
_From @davidfowl on Sunday, October 1, 2017 7:23:08 AM_

I think that's too implementation specific. You can always add another feature. I'd need to see more routing implementations to know what other cross cutting things could even go there.

 Knowing what route was matched is something that @rynowak mentioned and I working on (but it's a big change from how things work today and is implementation specific).

**Comment by aspnet-hello** [comment]
_From @davidfowl on Sunday, October 1, 2017 7:36:01 AM_

I guess the HttpRequest.Route property would be decoupled from the feature

**Comment by muratg** [comment]
@davidfowl with @JamesNK's work, I think this is irrelevant now. Please bring it back if you disagree.
