### ISSUE TITLE
Move various parsers/formatters into HttpAbstractions

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2324]
_From @davidfowl on Saturday, August 19, 2017 2:37:24 PM_

In our continued effort to provide generally useful abstractions for the greater ecosystem, we should move the low level parsers and formatters into Microsoft.AspNetCore.WebUtilities.

HTTP Parser from Kestrel - https://github.com/aspnet/KestrelHttpServer/blob/59b77bb357f50946ecea310feb8db53473e0e165/src/Kestrel.Core/Internal/Http/HttpParser.cs

The chunked encoding parser from Kestrel - https://github.com/aspnet/KestrelHttpServer/blob/59b77bb357f50946ecea310feb8db53473e0e165/src/Kestrel.Core/Internal/Http/MessageBody.cs#L475

HPackEncoder and HpackDecoder - https://github.com/aspnet/KestrelHttpServer/blob/59b77bb357f50946ecea310feb8db53473e0e165/src/Kestrel.Core/Internal/Http2/HPack/HPackDecoder.cs
https://github.com/aspnet/KestrelHttpServer/blob/59b77bb357f50946ecea310feb8db53473e0e165/src/Kestrel.Core/Internal/Http2/HPack/HPackEncoder.cs

_Copied from original issue: aspnet/HttpAbstractions#916_

**Comment by aspnet-hello** [comment]
_From @muratg on Monday, October 30, 2017 10:41:22 AM_

@davidfowl putting this into the next milestone.

Was Managed HttpClient a potential user of this in your mind?  Any other users?

**Comment by aspnet-hello** [comment]
_From @daniel-white on Monday, November 13, 2017 8:28:46 AM_

The multipart support would be nice to consider too!

**Comment by aspnet-hello** [comment]
_From @litichevskiydv on Monday, December 11, 2017 10:13:37 AM_

Will it be possible to use output and input formatters such as JSON output formatters in the middlewares?

**Comment by aspnet-hello** [comment]
_From @khellang on Monday, December 11, 2017 10:30:50 AM_

It might be soon; https://github.com/aspnet/Mvc/pull/6822#issuecomment-329484272, https://github.com/aspnet/Diagnostics/issues/346 and https://github.com/aspnet/Mvc/pull/6998

**Comment by muratg** [comment]
@davidfowl Assigned to you in 3.0. Please close if you don't think we'll change things here.

**Comment by anurse** [comment]
🤷‍♂
