### ISSUE TITLE
Make it possible to retrieve a factory from the service container

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2347]
_From @SPARTAN563 on Thursday, March 24, 2016 7:09:36 AM_

# Background

Currently, when implementing systems which require the ability to dictate the lifecycles of child services, you are required to make use of `GetService()` or `GetRequiredService()` and inject an `IServiceProvider`.

We've run into issues (in rare cases, but those are always the worst kind) where the services being requested are not registered and this only becomes known when an eventual call to `GetService()` is made.
# Issue

This is specifically caused as a result of there being no clean way to retrieve a lazy constructor for those services from the container. This results in far more use of `GetService()` than really is necessary (possibly related to #287) and leads to fragility in affected systems.
# Suggestions

What I'd love to see is the ability to request something like an `IFactory<TService>` from the container with an API like the following.

``` csharp
/// <summary>
/// Provides a factory which will return an instance of the given type.
/// </summary>
/// <typeparam name="TInstance">The type of object returned by the factory.</typeparam>
public interface IFactory<TInstance>
{
    /// <summary>
    /// Gets an instance of <typeparamref name="TInstance"/>
    /// </summary>
    /// <returns>An instance of type <typeparamref name="TInstance"/></returns>
    TInstance GetInstance();
}
```

These factories would be registered whenever a call to `AddSingleton`, `AddTransient` or `AddScoped` were called and could be implemented as follows.

``` csharp
class DependencyInjectionFactory<TInstance> : IFactory<TInstance>
{
    public DependencyInjectionFactory(IServiceProvider container)
    {
        Container = container;
    }

    protected IServiceProvider Container { get; private set; }

    public virtual TInstance GetInstance()
    {
        return Container.GetRequiredService<TInstance>();
    }
}
```

This approach prevents any changes to the external API while also permitting code to depend on concrete types in situations where they must be responsible for the lifecycles of their children.

``` csharp
public class SuggestedUse {
  // Will fail when GetRequiredService<SuggestedUse>() is called if B isn't registered with the container
  public SuggestedUse(IFactory<B> bFactory) {
    BFactory = bFactory;
  }

  protected IFactory<B> BFactory { get; private set; }

  public Do() {
    var b = BFactory.GetInstance();
  }
}

public class B {

}

public class CurrentUse {
  public CurrentUse(IServiceProvider container) {
    Container = container;
  }

  protected IServiceProvider Container { get; private set; }

  public Do() {
    var b = Container.GetRequiredService<B>(); // Fails at this point if B isn't registered with the container
  }
}
```
# Working with IDisposable

The above example is less interesting than it could be, primarily as a result of it not making use of any scopes. Generally the reason why one would chose to do this is because the services you are requesting are either resource heavy, or because they take out locks on other resources which need to be released while the parent remains active.

In this situation, we've implemented an `IScopedFactory<TService>` type which extends `IFactory<TService>` with a `BeginScope()` method.

``` csharp
/// <summary>
/// Provides a factory which operates using a garbage collection tracking scope
/// </summary>
/// <typeparam name="TInstance">The type of objects which will be returned by this factory.</typeparam>
/// <remarks>
/// You are required to wrap any calls to <see cref="IFactory{TInstance}.GetInstance"/> in a
/// <c>using(<see cref="IScopedFactory{TInstance}.BeginScope"/>)</c> code block.
/// </remarks>
public interface IScopedFactory<TInstance> : IFactory<TInstance>
{
    /// <summary>
    /// Creates a new scope which calls to <see cref="IFactory{TInstance}.GetInstance"/> will make use of
    /// </summary>
    /// <returns>Returns an <see cref="IDisposable"/> which can be disposed to close this factory's scope.</returns>
    IDisposable BeginScope();
}
```
# Remarks

At the end of the day, the question around whether this should be included in the core library comes down to whether there is enough indication of #287 being caused by this use case, or use cases which can be solved through the injection of strongly typed factories, as well as whether you wish to impose an additional API on consumers to provide that functionality, or whether it should be included in the core `Add*` methods.

We've currently got an implementation for a project of ours which makes use of extension methods and the above interfaces to achieve a good level of up-front checking which would otherwise not be possible (with calls to `GetService` and `GetRequiredService`).

As always, if you would like further clarification or assistance from me, please don't hesitate to ask.

_Copied from original issue: aspnet/DependencyInjection#394_

**Comment by aspnet-hello** [comment]
_From @davidfowl on Wednesday, March 30, 2016 1:03:27 PM_

Cool feature idea. As with every feature we've refused to add to the DI container thus far, have you looked at how other DI containers would implement this? So far, we haven't decoupled `IServiceCollection` from our container registration API, that is, the default container only supports `IServiceCollection` as a way to wire up dependencies. This means that we are very careful when we add things because we want it to work with anyone supporting the DI abstraction (autofac, structure map etc).

The other piece of the puzzle is the fact that we don't want to consume features that can't work with a broad set of other containers and the way we keep ourselves honest is by making use of a very set of narrow (YMMV) DI features in our frameworks. We _could_ add this feature but we wouldn't use it ourselves. We would need to have some verification in place where we could separate those 2 things and today we don't have that. We just don't add features that put us closer down that path today.

Post v1 we can re-evaluate how do go about doing this.

**Comment by aspnet-hello** [comment]
_From @davidfowl on Wednesday, March 30, 2016 1:04:50 PM_

On top of that, one of the nice things about having less features is that it makes the container leaner and less complicated. 

You could use autofac or ninject or struturemap to get the factory feature (I'm sure they have it, I know autofac does).

**Comment by aspnet-hello** [comment]
_From @smbecker on Wednesday, March 30, 2016 5:39:59 PM_

One straightforward way to expose this would be to have the constructor take Func<T> to act as the factory. It appears that at least [StructureMap](http://structuremap.github.io/the-container/lazy-resolution/) and [AutoFac](http://docs.autofac.org/en/latest/advanced/delegate-factories.html) support this so precedent is there. Plus this doesn't require any additional types to be added. Granted today you can manually do this with the existing codebase using `services.AddSingleton<Func<T>>(sp => sp.GetRequiredService<T>)`

**Comment by aspnet-hello** [comment]
_From @SPARTAN563 on Wednesday, March 30, 2016 11:12:15 PM_

Hadn't spent much time considering that, and definitely something to keep in mind as you point out. In this case however, my thoughts were that the only thing requiring any changes would be the `AddTransient` and `AddScoped` extension methods, which would transparently register a provider for `IFactory<T>` (or alternatively, as @smbecker mentioned, `Func<T>`).

The `IScopedFactory` is a bit more of a complex beast and not necessarily the core component of this feature, however it can once again be accomplished using nothing more than extension methods (implying that it should work on any underlying container with support for the existing service registration model).

As far as precedent goes, I did notice that you've implemented `IEnumerable<T>` to map to the collection of services registered with type `T` - enabling you to inject a class of services into the constructor instead of needing to rely on `GetServices<T>()` - something I was hoping to extend.

As always though, I do appreciate the wish to keep the framework simple and am not entirely adverse to simply extending it myself to provide this functionality through my own set of extension methods.

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, April 21, 2016 1:45:17 PM_

Another interesting idea, thanks @SPARTAN563 . If you have further thoughts on this we can certainly continue the discussion.

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, April 21, 2016 1:45:22 PM_

(Moved to Backlog)

**Comment by aspnet-hello** [comment]
_From @SPARTAN563 on Thursday, April 21, 2016 2:04:18 PM_

Certainly, anything in particular that you'd like to discuss or any questions you may have? If you'd prefer, I can out together a rough PR with an example of how this would be achieved for further discussion and evaluation. 

Alternatively, as I mentioned, we have managed to implement this as a simple extension on top of the existing framework - so could very easily provide that as a NuGet package if they is a preferred option.

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, April 21, 2016 3:21:30 PM_

If it can all be done as an add-on then perhaps you could publish it as such and see what level of interest there is in it? That would be helpful in order to gauge whether people feel it is sufficiently important to include as a built-in feature.

**Comment by aspnet-hello** [comment]
_From @SPARTAN563 on Thursday, April 21, 2016 9:41:03 PM_

Sounds like a good plan to me, I'll see what I can do about setting aside some time for it in the near future.

**Comment by davidfowl** [comment]
This is basically support for `Func<T>`. Before we add features like this, we'd like to make sure they exist in all of the supported 3rd party containers. As a result we're going to close this out.
