### ISSUE TITLE
Validate presence of constructor argument types when calling BuildServiceProvider

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2348]
_From @SPARTAN563 on Thursday, March 24, 2016 6:35:45 AM_

# Background

When defining a service which accepts dependencies through its constructor, you expect that all required services are present in the container for its construction. One would expect that, failing this contract, an exception would be thrown when building the container.
# Issue

At the moment, it is possible to register a service whose constructor requires services not present in the container. Building of the container (using BuildServiceProvider) succeeds and one will only encounter an error when you attempt to retrieve an instance of that service (or a service depending on it) through the `GetService` call.

From an architectural perspective, this allows for certain edge cases to only be hit when the services are eventually requested at runtime, not necessarily at application start. Ideally, the application should fail to start should a condition like this be possible.
# Reproduction

``` csharp
public class A {
  public A(B b) {

  }
}

public class B {

}

var services = new ServiceCollection();
services.AddSingleton<A>();

var container = services.BuildServiceProvider(); // Expected an exception here

container.GetService<A>(); // Throws exception here
```
# Suggestions

In an ideal world, this would be done as part of building up your call sites and within the call to BuildServiceProvider - throwing an exception if a dependency was not present in the container.

I understand this may not necessarily be possible, especially if you only build up the call sites when they are first required, in which case perhaps we can look at alternative solutions.

/cc @wesleyolis

_Copied from original issue: aspnet/DependencyInjection#392_

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, April 19, 2016 11:34:32 AM_

Definitely an interesting idea, but not planning to build it at this time.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (200/200 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:17087)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuWw-0001tU-3d
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:29:06 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=vuh1UFsDKibgLWmVYxlZR9Fmc5s=; b=hqEPaGF2qWSn/u3M
	BHTgMX4ifzx+Yfe8VR3qp7H1K8C3GNmGyI9AJBcTUR2d3YeysSfrEz1By6Ftx46h
	LGf8XyQggu8XYP+cGhWkXYWmXHJVI4YA1fPHmFRGkBAxI7u/ipkg1ZarETD9ACaA
	aQMZsznytw6BVlG3CwOdgq5FPec=
Received: by filter1237p1mdw1.sendgrid.net with SMTP id filter1237p1mdw1-29227-5A49E32D-7
        2018-01-01 07:28:45.383861491 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0010p1iad2.sendgrid.net (SG) with ESMTP id giBZsqEHR7-HlAxYds3JYg
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:28:45.291 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:28:45 +0000 (UTC)

**Comment by davidfowl** [comment]
A couple of things:
- We can't do this by default, it needs to be a flag.
- You cannot do this for open generics.

We'll investigate for 3.0
