### ISSUE TITLE
Multiple nested scope registrations

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2351]
_From @ghost on Friday, November 13, 2015 3:18:13 PM_

When doing multiple nested scopes through `IServiceScopeFactory.CreateScope()`, you get nested `IServiceProvider`  instances. It doesn't, however, give access to registrations for each scope.

Therefore if you have scopes which are created further down the pipeline (with some service data only accessible from that step in the pipeline, which isn't available at the root), you can't really register services to use in there.

The sought-after structure being:
Scope (root)
     - Register (root)
     - Resolve (root level)
     <- Scope (level 1)
          - Register (level 1)
          - Resolve (root level + level 1)
          <- Scope (level 2)
               - Register (level 2)
               - Resolve (root level + level 1 + level 2)

I don't know if there's an alternative way of achieving this, but so far the documentation is scarce.

_Copied from original issue: aspnet/DependencyInjection#327_

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, January 22, 2016 5:27:13 PM_

Moving this to Backlog as we are not planning to make any changes for this at this time.

**Comment by aspnet-hello** [comment]
_From @dazinator on Thursday, July 13, 2017 10:57:56 AM_

I am looking at how to achieve the following.

As well as an `IServiceProvider` at the Application and at the RequestServices (scoped) level, I'd like have an `IServiceProvider` for each separate tenant of my application. The thing I can't figure out is, if I build an `IServiceProvider` for each tenant, how do I chain this `IServiceProvider` to a parent `IServiceProvider` such as request services - so that resolution fallsback from the tenant container to RequestServices?

**Comment by aspnet-hello** [comment]
_From @dazinator on Thursday, July 13, 2017 11:04:09 AM_

It would be really good if I could register some sort of generic delegate into the child container to be invoked as a fallback for whenever a service wasn't registered - in there I could defer resolution to an alternate IServiceProvider (i.e the parent one).. Is this possible?

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (237/200 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:55698 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVuY5-00023x-8r
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:17 -0600
Date: Sun, 31 Dec 2017 23:29:57 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514791797;
	bh=3m5KVVKG32zgFGUGd2qlh6WEG7H4Ih+OZaySuErU4Y4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=HpH7l01B2xD0rytgr17poUBqQPfwIP45fmzKnwUHQgSGj960zHK8NlG3aD/JHiJKI
	 dd3F7H3cOB3I7ugrL0S5P05tcq4wpVG129DvlYPl2YSSk5QCNnBpSJMCLS8u4ffs8/
	 G1PybgEs4NkWT+hzImkZp7X2tCB7ga6cYAMbCYlg=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (235/200 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:46264)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuY4-00023g-3L
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:16 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=v7Xw9bb0Ukp0i466hImYWK3VMFg=; b=pSITCVIPe2jCSOmJ
	s4XquW4q3DBGlWBn5gClOFsR7PW5v0H7Rf2xpT0X13e8ZOs+2BrsAmMJ7s5yQHLg
	vH7mcBdNuMkk03jjbeooIV7Fh9XCSdVlx28yREAYBrXyCl0eYN86Mhia3wsm/5c+
	GAvQgUCratS+dRxOVcWABbio0FM=
Received: by filter0347p1las1.sendgrid.net with SMTP id filter0347p1las1-23705-5A49E372-1C
        2018-01-01 07:29:55.030407476 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0019p1iad2.sendgrid.net (SG) with ESMTP id cgaGeSfdSROr-s7LVfUqAA
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:29:54.968 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:29:55 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (236/200 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:31578)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuY4-00023i-OH
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:16 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=+hok/o8+2S4qm9pOzhMQcwrh/+o=; b=I7BvNTHJYNeHdjBI
	vigsY1u+ZMu8MW8oTvzQD8Ymvo8dW6Ty5iOmdPyDQAie3rgbVPyD8M78RQuUU306
	d5xAtma6IWyFMLOlViTDo5rO7f9jU9ZvePe/eURDy/3CwtMq/juwauDRY9XycVlT
	Rqmz29azW1mnEfuyXXlusoVd6OE=
Received: by filter0099p1las1.sendgrid.net with SMTP id filter0099p1las1-7011-5A49E373-10
        2018-01-01 07:29:55.61824705 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0009p1iad2.sendgrid.net (SG) with ESMTP id 5Ale8lkNTNqUs064C1M9EA
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:29:55.649 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:29:55 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (238/200 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:32067)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuY7-00024B-VH
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:20 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Mnyn06FwMGf4ceE7RCNy461qxXU=; b=urqONq6C3tTPkHoq
	N0MnFnU2GEeXVadyi16fZU2PpjdBOL95H4/5sDogb6bhOLKnSVB+ypJeZD20yAyv
	VQVfgxaDHyo5tXjg8HK1Zr0rKz/9/E9HIwkgeQmdXbsaNKrzFd3zozvVqev1z14F
	s+ilntMZs/dqZlpWStnE3ieuRM4=
Received: by filter0167p1las1.sendgrid.net with SMTP id filter0167p1las1-1023-5A49E377-7
        2018-01-01 07:29:59.194290079 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0007p1iad1.sendgrid.net (SG) with ESMTP id GA16BPgnRzyrKMagGaCoKg
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:29:59.117 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:29:59 +0000 (UTC)

**Comment by t03apt** [comment]
> When doing multiple nested scopes through IServiceScopeFactory.CreateScope(), you get nested IServiceProvider instances. It doesn't, however, give access to registrations for each scope.

For example AutoFac has this implemented.
See: http://autofaccn.readthedocs.io/en/latest/lifetime/working-with-scopes.html#adding-registrations-to-a-lifetime-scope
```
using(var scope = container.BeginLifetimeScope(
  builder =>
  {
    builder.RegisterType<Override>().As<IService>();
    builder.RegisterModule<MyModule>();
  }))
{
  // The additional registrations will be available
  // only in this lifetime scope.
}
```

**Comment by huysentruitw** [comment]
Can we agree that this issue is closely related to https://github.com/aspnet/Home/issues/2355 ?

**Comment by davidfowl** [comment]
We have no plans to add support to child containers. We recommend you use a 3rd party container for this (like autofac)

**Comment by huysentruitw** [comment]
Yeah, too hard probably. I tried to create a pull-request for this, but it seems like we would need to refactor a very large part in order to allow this.
