### ISSUE TITLE
It's not ISSUE but Question

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2352]
_From @comdiv on Thursday, October 15, 2015 5:07:06 AM_

We have own DI/IoC framework in private code. It has 5 years history and primary was inspired by Castle Windsor.
We think that it will be good if aspnet/DI became the only one to decrease entropy of different solutions. But our framework has greatly another functionality rather than current apnet/DI way. If it's interesting we will try supply improved version of DI if it's not.. it's not... 

Here is some features we suggest to implement (pseudocode - not real names).
Most of them focused on adaption IoC as plugin centralization and extension point centralization facility.

1) DI-bound services - service instance can implement plugin-like API  `void OnCreateFromContainer(IContainer container, IComponent component)`  - so service can realize own DI logic and use container internally

2) Automatic assembly and type setup a) classes that implement `IContainerLibrarySetup.Setup(IContainer container)` - can be used as assembly-wide DI setup logic and`[ContainerComponentAttribute(lifestyle,...)]` that provide decoration for services that we want to register in container, at Container level there are Container.Register(Assembly assembly); and Container.Register(Type type) extension methods

3) Support for multiple mapping `ServiceType -> ServiceImpl*` that allow as not just `Resolve<S>() but ResolveAll<S>()` notation - so it's simple way to inject collections of some services (it's usual for extensions, filters, subproviders and so on)

4) Dual type-based and name-based registry for components, so we can use both `Resolve<S>() or Resolve(Type t)` and `Resolve(name) Resolve<S>(name) and Resolve<S>("prefix*")` - this is very usefull if we have multiple services for service interface but for different tasks. For example we have some kind of`IFilter`( bool IsFiltered(object val) )`but context of filter is very different. We can use namespace-like name notation and call`ResolveAll<IFilter>("out.type.*")``` to get them

5) Extended `[Inject]`  attribute that can decorate Properties, Fields and Method parameters - it can define some hints about how to bind it's target during DI when service is created and allow explicit control how to setup service. So it can provide required name (4) , default factory type (if not container setup) and so on

6) DI not for public only - it can bind privates if it's explicitly required by Inject, DI can work with collections, DI can keep existed collections

In code it looks like:

```
[ContainerComponent(Lifiestyle.Singleton)]
class MyServive:IOurService {
      [Inject]
      protected IList<IOtherService> SubServices {get;}=new List<IOtherService>{new OtherService()};
      ...

}

var c = new Container();
c.Register<MyService>();
...
c.Resolve<IOurService>(); // internally SubServices will be appended with DI with keeping existed list
...
```

7) Inject API that allow us DI into existed classes, aside of main DI process (Angular DI inspired):

```
IContainer c = GetMyMainAppContaner(); // it's not really-existed method )))
var myClass = new MyObject();
c.Inject(myClass);
```

This is things that we think to realize in aspnet/DI.

If it's interesting - we will fork DI, create set of focused issues and start to setup contribute.

_Copied from original issue: aspnet/DependencyInjection#305_

**Comment by aspnet-hello** [comment]
_From @pranavkm on Thursday, October 15, 2015 10:14:51 AM_

In general, we've been avoiding adding features that don't exist in other DI solutions.
That said, some of these could be solved with what we have in the box.

1) You could use service factories to achieve something along these lines. 
2) Auto discovery can be built as an extension on top of the framework. Is there value in having it be built in?
3) We support registering multiple services for the same type. `ResolveAll<S>` is writen as `Resolve<IEnumerable<S>>`.
4) See https://github.com/aspnet/DependencyInjection/issues/228 for discussion on named services.
5) `[Inject]` is a feature of Mvc. I'm not super sure where we stand on this. Also, how would this look like and work with other service containers?
6) See 5
7) Isn't this equivalent to `ActivatorUtilities.CreateInstance<MyObject>(serviceProvider)`?

**Comment by aspnet-hello** [comment]
_From @khellang on Thursday, October 15, 2015 12:39:15 PM_

I thought the whole point of this was to have a "lowest common denominator" way of registering/resolving framework components and that you could BYOC (Bring Your Own Container) if you wanted more features?

Several of the things mentioned are generally viewed as anti-patterns, like property injection (either using an `InjectAttribute` or an `Inject` method) or activating instances using a non-public constructor. It's already bad enough that this library encourages [service location](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/).

Some of the requirements of this library (see [conforming containers](http://blog.ploeh.dk/2014/05/19/conforming-container/)) are already alienating several existing .NET IoC containers and they're [unable to conform](https://github.com/simpleinjector/SimpleInjector/issues/41#issuecomment-111438146). Adding more features to this list of requirements won't help anyone.

So, my :+1: goes to BYOC if you require more features from your IoC container than what this library offers. The current set of features should be more than enough to get by and somewhat enforces good practices like constructor injection :smile:

**Comment by aspnet-hello** [comment]
_From @comdiv on Thursday, October 15, 2015 12:57:42 PM_

Ok. BYOC is way. Property injection can be worst than evil but it's thing that any DI should provide along with ctor injection. So private members binding too if explicitly configured. But it's kind of holywar.

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, January 22, 2016 5:27:22 PM_

Moving this to Backlog as we are not planning to make any changes for this at this time.

**Comment by aspnet-hello** [comment]
_From @IhnatKlimchuk on Wednesday, June 14, 2017 5:45:26 AM_

After implementing several projects in asp.net core faced with problem that `ConfigureServices` function contained spaghetti code of services configuration. Another problem was that information about `ServiceLifetime` etc. is connected with service itself and code cohesion wasn't perfect. 

As solution created temporary library [DIAttributeRegistrar](https://github.com/IhnatKlimchuk/DIAttributeRegistrar) where in readme named several problems. I agree that all new functionality mentioned in discussion above it's not required as part of `Microsoft.Extensions.DependencyInjection` package, but you can add new package with all sugar functionality for end-product developers.

**Comment by aspnet-hello** [comment]
_From @davidfowl on Wednesday, June 14, 2017 5:53:44 AM_

Nice! The biggest downside is loading all assemblies and scanning all types up front. That will dramatically slow down the startup time (especially as the application grows). You can make this a little smarter https://github.com/IhnatKlimchuk/DIAttributeRegistrar/blob/98b8a3641faf685f64417366b6344ee331bb52c6/src/DIAttributeRegistrar/DIAttributeRegistrarExtentions.cs#L39 by looking at assemblies that depend on the DIAttributeRegistrar package. That way you're not scanning *everything* by default.

**Comment by aspnet-hello** [comment]
_From @IhnatKlimchuk on Wednesday, June 14, 2017 6:11:12 AM_

Thanks @davidfowl for pointing that, will add improvements shortly. Anyway you can pass assemblies to scan by your own.

Regarding this discussion, I hope to see new package soon. That definitely should be separate package in order not to decrease base performance. Will be glad to help with it.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (240/200 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 9498 characters long; only the first
------ 5000 or so are included here.
Received: from o10.sgmail.github.com ([167.89.101.201]:3009)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuYE-0002AS-Bc
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:26 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=JyZq8cp9DMAN/w7TPqjvc3usQsM=; b=HjRfcXNPK+5vtvYz
	1pTR5qXAXwHICWcrPNX1h55U8JTLgUBjw/C6/+HVWtzvbWzayBiRDYwXImStw55k
	cmyYg+SaVtyeDtxsdTBWa/A6fQmXw+8rkyvX9UN/AN2rV1dcS7LrmzTl2/5hGd8B
	VQex1vZ21F94Qh6FXnHinRq15KU=
Received: by filter0216p1las1.sendgrid.net with SMTP id filter0216p1las1-28974-5A49E37D-7
        2018-01-01 07:30:05.56786918 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id AzW6IzOhTVGbAYpzQpzk4g
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:30:05.521 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:30:05 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (239/200 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 5510 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:59183 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVuYE-0002AT-79
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:26 -0600
Date: Sun, 31 Dec 2017 23:30:05 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514791805;
	bh=NU0SKs6RE56xcN6+rkMu/4KFjEZ0kSJWf/NZsf+WaK8=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=gTWvWOO27z/dVDWb06j9Np/hW2kRQEGZOeACuDWlJNpI334K+Gr98/zAixsnEB8dZ
	 DYCj71Nz60z0EOMarzNumt22jWiIq9P3nXj9VfiEVgg94mjmyITyBD90kJVgQ8+rFE
	 z6Qw1e48ShWWdXd1il/83SbrLAiNNQ0ZmBQ7kOes=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (244/200 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:27827)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuYL-0002CO-OR
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:33 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=jSe8wJZvr0mhHkeCrZMAvOP06QU=; b=V+3mJT7reWI+RpjM
	ODwb1+785NXQzTUbEh/qUM+8BBuheNMrQb5d9uklKdpkx57BXbEAI7OdYXjPjIjt
	+KpAiDvGVs61QEfbo1sKD/pcJ9Am9hz57PSkbwyqDEu98rxiRtVKC3vo+8OMZGgH
	qE0r2WJqYNH4jhbkmrCxnElZj8o=
Received: by filter0618p1las1.sendgrid.net with SMTP id filter0618p1las1-1397-5A49E384-E
        2018-01-01 07:30:12.596611378 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0014p1iad2.sendgrid.net (SG) with ESMTP id hsuAgOw2QuGBNdUuKljbQg
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:30:12.490 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:30:12 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (242/200 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:14056)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuYI-0002Bl-BL
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:30 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=4OS9lrkWEptNbcnCLP/veJEpkn4=; b=CEQqgVXn+XSy3Smx
	aFx7epDT9q+EBgfCvkgC61Wkvy7XU3sVG5o7wYgh5aXj5szHyBoUlxBEP+6Y5nKB
	W9EpltgJTOfsElzjDq599xBd5ZV6wjJYHylL+aI5dNNTjzxI3vJ8bB9u6o+4tOhL
	Ybvi1XAi9vosVfj2Uya92OwxjNQ=
Received: by filter0457p1las1.sendgrid.net with SMTP id filter0457p1las1-10124-5A49E381-8
        2018-01-01 07:30:09.212198366 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0014p1iad2.sendgrid.net (SG) with ESMTP id OPBomtSTQ_uy7U_KJ5uv2w
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:30:09.127 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:30:09 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (241/200 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6563 characters long; only the first
------ 5000 or so are included here.
Received: from o5.sgmail.github.com ([192.254.113.10]:21112)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuYG-0002BV-S6
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:29 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=V1+kzQfPMonB0jm4/UmCSh/xVgo=; b=K6ItH8yzrybT5cfx
	Lyz68xSlaTXh/IHDcDJZkgdTeSya6puCh6Vp9KwdIP8uFODMwSOYS/z04CxhITP/
	A8LJqW7xQQDJkXKPixTrpnVcs+oET5HYB7DWyAuCI2BMWw5Hg8VEiFWfzFSjo2UL
	3NMv/XSCg/IIULrX2h/ugtp11Tc=
Received: by filter0461p1las1.sendgrid.net with SMTP id filter0461p1las1-26923-5A49E37F-23
        2018-01-01 07:30:07.960094612 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad2.sendgrid.net (SG) with ESMTP id 9y85xT51QwSSr4ocIQqu8Q
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:30:07.866 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:30:07 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (243/200 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:57350 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVuYJ-0002CL-Re
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:31 -0600
Date: Sun, 31 Dec 2017 23:30:11 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514791811;
	bh=rwwQwMFBzd+gOiNr7m4xJjP/DmsikZGwYTjGoS+xDjQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=wLMl9x1lq2dW8zU/AudQUdMshZLaSxaUTkKxc2RqFoVv3+R0amHvSPodz7bDfJ1Ss
	 stpuo+pj5VMNupJ+tb8UOZWQn2R0PNM5XGynsjnOgFxMkephBCAV0N88u/JHL/jVxK
	 +n4YwQQkofNm3VZWC7mefdxDfFaloAewaDupJmm4=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (245/200 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:34303 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVuYO-0002CX-4N
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:36 -0600
Date: Sun, 31 Dec 2017 23:30:15 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514791815;
	bh=ugM+4u7HC/QN4wYybWAE464Y2ksk+oJcDSMAb4ZpfK0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=JXEs2v75lgc7KygiT/0EoKAtKF7FUdIZUqdH3P58edxTwJt0tqV8RkIEA6P8sQe7T
	 JDa5fVgL6w5bANa11MJx3N7JSKiii9cPQsdJ8Mf7DMw1bhZcKJuDCqcJwJyV3m4nUC
	 OPboA9/OgVgKiCAeLjCNK9dNggyxgboyuN+/8Li4=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (246/200 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:17900)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuYO-0002CV-61
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:36 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=K734vNzvV/etSCpdBI9ljPm+DHk=; b=nKVs+Ls/YMlA/TW6
	w1mUEjbK6Md9TyaLZNoFbH8lFE9ZulWJqq67VJHl5WlHiAfWflQD2NJZv7tERiYD
	NUK+xzqtmoDLLJGcl07AeIJgc+yHBNWZlwhKPs82zwXmomCrUBTrErKaKjSYkQOA
	ftxnUNQP9lGiMqC4AyGrfEVp/1U=
Received: by filter0278p1las1.sendgrid.net with SMTP id filter0278p1las1-4699-5A49E387-4
        2018-01-01 07:30:15.259275403 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0009p1iad1.sendgrid.net (SG) with ESMTP id d7nBGVMrRKmFurcLBUupIA
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:30:15.163 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:30:15 +0000 (UTC)
