### ISSUE TITLE
async/await in service registration or service resolution.

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2353]
_From @Antaris on Wednesday, October 14, 2015 3:10:50 AM_

Is it possible to support `async`/`await` and `Task` based service resolution? I'll walk you through an example:

```
public class WorkContext : IWorkContext
{
  public WorkContext(ISecurityContext securityContext)
  {
    SecurityContext = securityContext;
  }

  public ISecurityContext SecurityContext { get; private set; }
}

public class WorkContextFactory : IWorkContextFactory
{
  private readonly ISecurityContextFactory _securityContextFactory;

  public WorkContextFactory(ISecurityContextFactory securityContextFactory)
  {
    _securityContextFactory = securityContextFactory;
  }

  public async Task<IWorkContext> CreateWorkContext(CancellationToken cancellationToken = default(CancellationToken))
  {
    // Get the security context for the current user
    var securityContext = await _securityContextFactory.GetForCurrentUser(cancellationToken);

    return new WorkContext(securityContext);
  }
}
```

 In my example above, I'm defining some implementations of abstractions provided by my framework. In a dependency, the `ISecurityContextFactory` I implement a `Task`-based async/await model because I don't know that the actual implementation _might_ do some DB work to say load the current user information.

 When I come to wire up my services, I want to utilise my `WorkContextFactory` to build my type (seperation of concerns), so I might do something like the following:

```
yield return ServiceDescriptor.Scoped<IWorkContextFactory, WorkContextFactory>();
yield return ServiceDescriptor.Scoped<IWorkContext>(sp => sp.GetService<IWorkContextFactory>().CreateWorkContext().Result);
```

 Obviously at the moment, I'm having to block until I get the result of `Task<IWorkContext>`, but it would be great if I could do something like:

```
yield return ServiceDescriptor.Scoped<IWorkContext>(sp => sp.GetService<IWorkContextFactory>().CreateWorkContext());
```

 And have the DI system understand the `Task` result and await.

 Is this possible?

_Copied from original issue: aspnet/DependencyInjection#303_

**Comment by aspnet-hello** [comment]
_From @davidfowl on Wednesday, October 14, 2015 3:14:00 AM_

Anything is possible but we so far we haven't been adding features that don't exist in other service providers. This looks like Func<T> or Lazy<T> but it's Task<T> being resolved instead of T. Maybe look at how/if other containers solve this and come back with some more data?

**Comment by aspnet-hello** [comment]
_From @Antaris on Saturday, October 17, 2015 3:42:34 AM_

I don't think this scenario is currently widely supported, I've not found a good working examples, so this looks to be one for the backlog until other containers implement something similar.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (247/200 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:32373)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuYU-0002DX-JV
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:42 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=NM1GM3fPTApMGyXgzHJajoPYtSg=; b=gWD488FToafk779A
	ITwKKyjTzQWw78nAhZ8OzRJ+4Vupl+GIfjFkjrOdE+cLCAngK/lcq8h/9Z2/fJpt
	ucL9cDqy5vEP9tueIQqii1Kzt4yaQ3ctXG3LoZVJMDVg1jzI5qFzGno5VTLCiz5p
	3YBma7KpXWvXZ/YZ7ur98LX5Udg=
Received: by filter1134p1mdw1.sendgrid.net with SMTP id filter1134p1mdw1-5065-5A49E38D-18
        2018-01-01 07:30:21.961736912 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad2.sendgrid.net (SG) with ESMTP id -0KG6NoLQJWnCTvUhCYZiQ
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:30:21.805 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:30:21 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (249/200 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:34334 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVuYV-0002Db-SM
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:43 -0600
Date: Sun, 31 Dec 2017 23:30:23 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514791823;
	bh=o32hzyoj7rLXlfrCx/WPeT0UYuNvw/2dHY423bzQyH0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=GNlbQbK3PC+LaPGI8+m0zO8vz/VPm9S3sXy28hlH0qWFmbW36J6AJGDX3KvDPHNpt
	 b85xz0a+O0kJB2CClNlKGsgXJRhEFxRGbcykoAEZjCpFw1vieQiYt3LJv0d8XAZSeu
	 Ey/v/r1WX2sEdjOlw2zEBkXdGoqeYlkmBnHzNjto=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (248/200 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6925 characters long; only the first
------ 5000 or so are included here.
Received: from o8.sgmail.github.com ([167.89.101.199]:40927)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVuYU-0002DW-M3
	for david@spinthemoose.com; Mon, 01 Jan 2018 01:30:42 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=aWI0jGuOn6SV29j4BBW/56hioFM=; b=IsrEVvDI9i9IfcCT
	+FDZz6KaBRsu64ujUnWP1Uty0/dhavRIQ1dwsce65nGAzOFb8nhQ09a3fmmCN8Gz
	vtt4K+lXSKUYuSIRaInjkZV/S50r37jMeu0l8KcK+HhHXM61bW7aBNBd3DHIVMWd
	YEQNhEf22IBS/nryiUurMQxPXCI=
Received: by filter0018p1las1.sendgrid.net with SMTP id filter0018p1las1-579-5A49E38D-A
        2018-01-01 07:30:21.19149818 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0015p1iad2.sendgrid.net (SG) with ESMTP id lj7Z-YS9QfG9bq6uP4vo9w
	for <david@spinthemoose.com>; Mon, 01 Jan 2018 07:30:21.300 +0000 (UTC)
Date: Mon, 01 Jan 2018 07:30:21 +0000 (UTC)

**Comment by davidfowl** [comment]
Currently there's no such thing as an async constructor so the recommended pattern is to use async methods after synchronously resolving the service.
