### ISSUE TITLE
Create infrastructure for testing with docker

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2356]
_From @natemcmaster on Tuesday, June 6, 2017 10:18:11 AM_

Requirements:

 - I should be able to write a functional test that runs .NET Core inside a Docker container
 - I should not have to manually manage the image tag or versions to ensure .NET Core runtime inside the container aligns with current KoreBuild versions
 - I should be able to assert the output of code executed from within a container, either via logs or exit code
 - I should be able to docker options, such as exposed ports, data volumes, etc.

Example: I need a way to verify the behavior added in aspnet/DataProtection#244

_Copied from original issue: aspnet/Testing#277_

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Tuesday, June 6, 2017 10:27:17 AM_

cc @muratg @pakrym - this will be useful as we begin adding more docker-specific runtime features. We don't have a good way to test these at the moment.

**Comment by mkArtakMSFT** [comment]
@natemcmaster, is this obsolete already? Should we just close it?

**Comment by natemcmaster** [comment]
Yeah, were not going to do this. Not sure why it ended up in mvc, but no real need for this anymore.
