### ISSUE TITLE
[Feature request] Make it able to pass custom ClaimsPrincipal when using TestServer

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2357]
_From @kasparkallas on Thursday, May 18, 2017 3:26:49 AM_

_[Use case]_ In my application, I want to test the combination of authorization policies against concrete endpoints with specific users and domain state.

To my knowledge, when using authorization attributes, the "best" way to currently test is to check for existence of attributes through reflection and unit-test the components separately. With `HttpContext` and all sorts of other contexts, base classes etc the unit-tests are not that clear to follow and not easy to write. I would much rather fire up a `TestServer`, create a dummy `ClaimsPrincipal `with a claim or two, and see if I get forbidden result or not against protected resources.

Opinions?

_Copied from original issue: aspnet/Testing#276_

**Comment by aspnet-hello** [comment]
_From @davidfowl on Thursday, May 18, 2017 3:38:55 AM_

This should be moved to aspnet/Hosting. 

@rynowak You were discussing being able to get a `RequestDelegate` instead of an `HttpClient` from the `TestServer`. Did you file an issue for that anywhere?

**Comment by aspnet-hello** [comment]
_From @rynowak on Thursday, May 18, 2017 11:08:34 AM_

https://github.com/aspnet/Mvc/issues/6233

**Comment by aspnet-hello** [comment]
_From @ferrx on Monday, June 5, 2017 12:47:50 PM_

> the "best" way to currently test is to check for existence of attributes through reflection and unit-test the components separately @kasparkallas 

Can you explain further or link to a guide? Do you just mean checking to see if the `[Authorization]` data attribute is attached to a method via reflection and perform some forked set of actions for authorized and not-authorized behavior?

I assume this would not take granular claims assessment into account, i.e. if your controller was checking to see if the current user `HasClaims`..

**Comment by aspnet-hello** [comment]
_From @kasparkallas on Wednesday, June 7, 2017 3:31:47 AM_

@ferrx Yes, I did mean checking for the presence of the attribute via reflection. Which is clearly not a good way to test it because of all the possible combinations of attributes, filters and explicit authorization logic in controller (like you said). Sorry, I don't have an article to share.

I have been informed that the `ClaimsPrincipal` can be passed when using the open-source ASP.NET Core integration testing project [Alba](http://jasperfx.github.io/alba/) which does the same thing as `TestHost` but exposes `RequestDelegate` (if I understand correctly).

A code example setting up `WindowsPrincipal` for `User` that I got from Alba's Gitter room (thanks @joemcbride):

```
private Task<IScenarioResult> run(Action<Scenario> configuration)
{
    using (var system = SystemUnderTest.ForStartup<Startup>())
    {
        system.Environment.EnvironmentName = "Development";
        return system.Scenario(configuration);
    }
}

[Fact]
public async Task authenticated_values()
{
    var result = await run(_ =>
    {
        var identity = WindowsIdentity.GetCurrent();
        var principal = new WindowsPrincipal(identity);
        _.Context.User = principal;
        _.Get.Url("/api/values");
        _.Context.Request.Method.ShouldBe("GET");
    });

    result.Context.Response.StatusCode.ShouldBe(200);

    var output = result.ResponseBody.ReadAsJson<string[]>();
    output.ShouldNotBeNull();
    output.ShouldBe(new []{ "value1", "value2"});
}
```

**Comment by aspnet-hello** [comment]
_From @rynowak on Wednesday, July 5, 2017 8:07:38 AM_

@javiercn - is it possible to use `Microsoft.AspNetCore.Mvc.Testing` to get a `RequestDelegate`?

**Comment by aspnet-hello** [comment]
_From @davidfowl on Wednesday, July 5, 2017 8:34:27 AM_

The test server takes an `IWebHostBuilder` which creates an `IApplicationBuilder` and uses pretty much the entire hosting pipeline. There's no way to get the request delegate directly.

**Comment by aspnet-hello** [comment]
_From @javiercn on Wednesday, July 5, 2017 9:04:18 AM_

I believe is trivial to expose the request delegate from TestServer.

That said, If i were to set the principal in the HttpContext at the beginning of the request, I would just do it with a startup filter in the same fashion that we do to setup the request culture.

Create a startup filter, plug it in DI and make it setup a middleware that sets the principal to whatever you are expecting.

If we were to expose the request delegate you would need to be responsible of creating the HttpContext yourself and I'm not sure of the subtleties that might have (it might be doable)

**Comment by aspnet-hello** [comment]
_From @javiercn on Wednesday, July 5, 2017 9:05:57 AM_

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Testing/Internal/CultureReplacerStartupFilter.cs

**Comment by aspnet-hello** [comment]
_From @davidfowl on Wednesday, July 5, 2017 9:35:55 AM_

> I believe is trivial to expose the request delegate from TestServer.

I'm not sure it is, but we should discuss offline.

**Comment by mkArtakMSFT** [comment]
@davidfowl , @javiercn - have you ever synced regarding this? Can the StartupFilter be used to satisfy the need here?

**Comment by Tratcher** [comment]
TestServer.SendAsync is a new API in 2.1 that can do something like this. You get direct access to an HttpContext instance. That said, you still may need an auth handler for Authorize to work properly.

**Comment by Tratcher** [comment]
If your controller is using the default auth scheme, maybe.

**Comment by javiercn** [comment]
@Tratcher You can setup the auth part with any scheme you need, so I don't think the scheme matters at all. I did the default part cause that's what most people use.

**Comment by Tratcher** [comment]
What matters is what's on your controller, you can't change that from outside the app.

**Comment by javiercn** [comment]
@Tratcher Completely agree, what I'm saying is that you can setup your app in the test environment so that it matches what is on your controller.

Fore example, 
If you have [Authorize] you can set the default scheme as the handler.
If you have [Authorize("SomeScheme")] you can setup your test handler as "SomeScheme"

Similarly if you had an auth policy. If you don't override the auth in the app, being able to "somehow" set the principal on the HTTP context I don't think would be that valuable given that your auth handler would still try to authenticate you

**Comment by ferrx** [comment]
@javiercn Would you be able to set the principal's claims so that you can test controllers that perform granular authorization with `HasClaims` ?

**Comment by mkArtakMSFT** [comment]
@javiercn, what's the status of this issue? Any pending actions?
