### ISSUE TITLE
Session cannot be re-loaded

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2394]
_From @bobuhito on Tuesday, December 5, 2017 11:55:42 PM_

When I have two concurrent requests to my site from the same session, the session keys/values
are not updated until the server responses are fully sent.  One request therefore can not use the
other request's session key/value updates in a timely manner.  In my case, I usually have to reload
the site.

Is there any reason you don't update the session keys/values in real-time (so the second connection
could see them right away, even though the first connection is still getting service)?  I'm guessing
this is a remnant of locking and might give the second connection more stability if it tries to read
a session value just as the first connection is writing it.  Anyway, it would be nice to have an option
to allow faster communication between requests from the same session.

_Copied from original issue: aspnet/Session#203_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, December 6, 2017 8:35:22 AM_

There's very little that can be done to make session work deterministically for concurrent requests, you'd hit race conditions everywhere. Most requests are quick enough you've have a hard time telling that they were concurrent. Do you have very slow concurrent requests to the point where it's obvious? What kind of information are you trying to share between them?

**Comment by aspnet-hello** [comment]
_From @bobuhito on Wednesday, December 6, 2017 4:38:51 PM_

Yes, it's very clear.  I try to keep the connection for a minute, to see who else connects within that minute,
and then tell the original connecter.  You already have race conditions if two people connect and
update the session and disconnect all with identical timing anyway, so the question is what's tolerable.
For my case, you could just update the session value immediately (so that other connections could
immediately see it) and the race condition just occurs sooner.  I still don't see a serious problem, but
imagine a problematic test case could be made...so I was just hoping for the option to allow either
mode of operation.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, December 6, 2017 8:48:40 PM_

Session does not sound like the right infrastructure for this kind of problem. Have you tried using SignalR?

**Comment by aspnet-hello** [comment]
_From @bobuhito on Wednesday, December 6, 2017 9:28:01 PM_

Yes, I use SignalR also, and I do have alternative methods, but simply letting the session update
earlier is the more straight-forward.  I'd be willing to pick through the code and just allow the option
somehow (even just for a private version if no one wants it...thus asking here).

**Comment by aspnet-hello** [comment]
_From @Tratcher on Thursday, December 14, 2017 8:37:51 AM_

It's not as easy as it looks. Let's start with the impossible...

If the session hasn't been established yet then the concurrent requests do not share a session cookie and have no means of being correlated. You need at least one request to complete and set the session cookie on the client before any concurrent requests could be made.

Once you have that cookie you need to look at the lifecycle of session on a request. The whole session is loaded from the cache the first time anyone tries to read from it on a request. Note a session is stored as a whole unit rather than on a per-entry basis. The session can be pre-emptively loaded by calling LoadAsync().  For efficiency and consistency purposes the session is not stored back to the cache until the request is complete. You can also-preempt this by calling CommitAsync(). Even if you do that the other request would have no way of detecting a change was committed without continually calling LoadAsync(). All of these extra operations would severely impede the performance of your cache and application.

**Comment by aspnet-hello** [comment]
_From @bobuhito on Friday, December 15, 2017 12:10:01 AM_

Maybe I'm seeing a bug with LoadAsync since I am doing exactly as you suggest in your last paragraph:

The session has already been established.  Then, I make two concurrent requests, with one starting a
few seconds before the other.  In my simplified test case, the responses take a minute simply using Sleep.  Before the sleep, I increment a session variable and call "await CommitAsync".  After the sleep, I
call "await LoadAsync" and then check that session variable, but the increment of the slightly-later
request is never seen by the slightly-earlier request.  Is that behavior expected?

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, December 15, 2017 7:43:02 AM_

You're right, it can't be re-loaded even after committed. Nobody has ever tried to do that before and it's not one of the intended usage scenarios.
https://github.com/aspnet/Session/blob/49e6920a7caa096997432240777af609e78acb9d/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L203

Manually reloading it from the ISessionStore doesn't look practical as you wouldn't have access to the sessionKey.

I still think session is a poor fit for concurrent cross-request communication, it's not designed for concurrency.

**Comment by muratg** [comment]
I don't expect we'll make changes here.
