### ISSUE TITLE
Remove obsolete options APIs

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2401]
_From @natemcmaster on Monday, July 3, 2017 11:59:25 AM_

Follow-up to https://github.com/aspnet/Session/pull/173

Remove the following obsolete APIs
```
SessionOptions
  .CookieName 
  .CookiePath
  .CookieDomain
  .CookieHttpOnly
  .CookieSecure 
```
~~.SameSideMode~~ already removed.

_Copied from original issue: aspnet/Session#175_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Monday, July 3, 2017 9:55:51 PM_

SameSiteMode was new in this release and can just be removed, no need to obsolete it.
________________________________

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Monday, July 3, 2017 10:45:01 PM_

Good catch. PR to remove it for 2.0.0 https://github.com/aspnet/Session/pull/176

**Comment by JunTaoLuo** [comment]
@Tratcher do you think this needs an announcement? We already made one for deprecating it: https://github.com/aspnet/Announcements/issues/257.

**Comment by Tratcher** [comment]
How about a added comment on that announcement that 3.0 is the version they're being removed in?

**Comment by JunTaoLuo** [comment]
That's not really useful, the discoverability of that comment is negligible. Might as well create a new announcement if we were to bother at all.

**Comment by Tratcher** [comment]
Anybody subscribed to announcements would be notified the same way for a comment as for a new issue.
