### ISSUE TITLE
Replace UseSession(SessionOptions) with UseSession(Action<SessionOptions>)

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2402]
_From @HaoK on Thursday, June 29, 2017 6:47:53 PM_

Since the session middleware is using IOptions, we should mirror how we normally configure options...  It should instead always use IOptions and apply the action to it afterwards (basically a PostPostConfigureOptions)

We should revisit any other middleware that are using this pattern and using IOptions

`UseSession(new SessionOptions())` => `UseSession(o => { })`

_Copied from original issue: aspnet/Session#174_

**Comment by aspnet-hello** [comment]
_From @muratg on Tuesday, September 26, 2017 3:50:16 PM_

@HaoK is this still a valid issue?  Are we going to do this?

**Comment by aspnet-hello** [comment]
_From @HaoK on Tuesday, September 26, 2017 4:15:47 PM_

Its a consistency issue, but I'm not sure this is something we could change in a minor release (breaking changes and all)

**Comment by aspnet-hello** [comment]
_From @Tratcher on Tuesday, September 26, 2017 4:16:50 PM_

We could add the new one.

**Comment by aspnet-hello** [comment]
_From @HaoK on Tuesday, September 26, 2017 4:31:59 PM_

Yeah we could add that across the board, `UseXyz(o => { })` everywhere that's currently only taking `UseXyz(new XyzOptions())`

**Comment by muratg** [comment]
I don't expect we'll make changes here.
