### ISSUE TITLE
Spurious log messages

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2404]
_From @mguinness on Thursday, April 13, 2017 10:10:16 AM_

I'm using session storage in my app primarily for TempData, but I'm noticing several "Accessing expired session" warnings in my logs which is being generated in [LoggingExtensions](https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/LoggingExtensions.cs#L26-L27).

It seems that the message is somewhat misleading.  Would something like "Expired session unavailable" be better than "Accessing expired session"?  The latter seems contradictory.  Also, why would this be a warning and not a debug message?  It seems that this would increase noise to signal for logs filtered to warning.

_Copied from original issue: aspnet/Session#160_

**Comment by aspnet-hello** [comment]
_From @muratg on Wednesday, June 14, 2017 3:43:46 PM_

Agreed that the message can be clearer. @glennc What's your thoughts on what the log level for this message to be?

**Comment by muratg** [comment]
As we haven't heard much from more customers on this, I'm closing this.
