### ISSUE TITLE
Remove obsolete options APIs

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2418]
_From @natemcmaster on Monday, July 3, 2017 11:56:58 AM_

Follow-up to https://github.com/aspnet/Antiforgery/pull/148

Remove the following obsoleted APIs
```
AntiforgeryOptions
  .CookieName
  .CookieDomain 
  .CookiePath 
  .RequireSsl
```

_Copied from original issue: aspnet/Antiforgery#149_

**Comment by mkArtakMSFT** [comment]
**IMPORTANT**: there are many other places where options are exposed which essentially need to be also removed.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/aspnet/AspNetCore/pull/7459
