### ISSUE TITLE
JToken and related Json.NET types are not handled by the current object adapters

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2424]
_From @jbagga on Wednesday, October 25, 2017 4:15:57 PM_

Our current adapters do not handle `JToken` (and related types like `JArray` and `JObject`) correctly. We can look into checking if the current contract is `JsonLinqContract` and write a new adapter or modify the dictionary or dynamic object adapters.

_Copied from original issue: aspnet/JsonPatch#121_

**Comment by mkArtakMSFT** [comment]
Closing as no customer expressed interest in this.
