### ISSUE TITLE
It should be possible to provide a custom JSON serializer

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2425]
_From @MovGP0 on Wednesday, October 25, 2017 2:50:15 AM_

Patching does not work when the entity uses custom datatypes that are not serializeable by default. 

In my case, I use [NodaTime](https://nodatime.org/) to provide time-dependent information in a save manner:  
```csharp
public sealed class MyEntity 
{
    [JsonProperty("created")]
    public Instant Created { get; set; }
}
```

```json
[
    { "op": "replace", "path": "/created", "value": "2017-10-25T12:34:56.000Z" }
]
```

Patching fails, since it cannot convert the ISO date string to an Instant, unless the global JSON serializer is set up to support those datatypes: 

```csharp
JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
     .ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
```

However, one might need a different global configuration than I want to use for patching. Therefore, it should be possible to provide a custom JSON converter for patching, rather than the global one: 

```csharp
var settings = new JsonSerializerSettings().ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
var myJsonSerializer = JsonSerializer.Create(settings);

patch.ApplyTo(myEntity, myJsonSerializer);
```

_Copied from original issue: aspnet/JsonPatch#120_

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
