### ISSUE TITLE
Patching of records (readonly entities) fails

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2426]
_From @MovGP0 on Wednesday, October 25, 2017 2:40:52 AM_

The following code does not work on readonly entities: 
```csharp
patch.ApplyTo(readonlyentity);
```

It should be possible to do something like this: 

```csharp
var patchedentity = patch.ApplyTo(readonlyentity);
```

_Copied from original issue: aspnet/JsonPatch#119_

**Comment by aspnet-hello** [comment]
_From @MovGP0 on Wednesday, October 25, 2017 2:52:59 AM_

One way of doing this would be to convert the readonly entity to an `Newtonsoft.Json.Linq.JObject`, apply the patches, and deserialize to the original datatype.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
