### ISSUE TITLE
Patching of readonly collections fails

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2427]
_From @MovGP0 on Wednesday, October 25, 2017 2:38:39 AM_

Given I have an Entity with an readonly collection like this: 
```csharp
public sealed class MyEntity 
{
    public MyEntity()
    {
    }

    [JsonConstructor]
    public MyEntity(IEnumerable<string> tags)
    {
        Tags = tags?.ToList() ?? new List<string>();
    }

    [JsonProperty("tags")]
    public ICollection<string> Tags { get; } = new List<string>();
}
```

Than it is not possible to patch it, besides the property beeing potentially writeable and also serializeable. 

_Copied from original issue: aspnet/JsonPatch#118_

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
