### ISSUE TITLE
Extension point

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2431]
_From @dario-hd on Wednesday, June 21, 2017 9:31:39 AM_

As far as I can see the extension point is the `ObjectAdapter`. So, basically the idea is to create a wrapper around it which implements the same interface. But `ObjectAdapter` is not injectable because of the `Action<JsonPatchError>` constructor parameter. 

In addition, I saw that [here](https://github.com/aspnet/JsonPatch/blob/dev/src/Microsoft.AspNetCore.JsonPatch/JsonPatchDocument.cs#L159) and [here](https://github.com/aspnet/JsonPatch/blob/dev/src/Microsoft.AspNetCore.JsonPatch/JsonPatchDocumentOfT.cs#L639) it is explicitly set to null.

Does it make sense to make it optional in order to allow it to be injectable?

That's what I did when I used this version https://github.com/KevinDockx/JsonPatch, but the parameterless constructor is not available anymore.

    public interface IPatchAdapter : IObjectAdapter
    {
    }

    public class PatchAdapter : IPatchAdapter
    {
        private readonly IObjectAdapter _objectAdapter;

        public PatchAdapter(IObjectAdapter objectAdapter)
        {
            _objectAdapter = Check.NotNull(objectAdapter, nameof(objectAdapter));
        }

        public void Add(Operation operation, object objectToApplyTo)
        {
            // ...
        }

        public void Copy(Operation operation, object objectToApplyTo)
        {
            // ...
        }

        public void Move(Operation operation, object objectToApplyTo)
        {
            // ...
        }

        public void Remove(Operation operation, object objectToApplyTo)
        {
            // ...
        }

        public void Replace(Operation operation, object objectToApplyTo)
        {
            // ...
        }
    }

_Copied from original issue: aspnet/JsonPatch#88_

**Comment by aspnet-hello** [comment]
_From @Eilon on Monday, August 28, 2017 1:48:27 PM_

@dario-hd can you provide more info on the scenario you are trying to accomplish?

**Comment by aspnet-hello** [comment]
_From @dario-hd on Tuesday, August 29, 2017 12:42:26 PM_

@Eilon the idea is to enhance the original `ObjectAdapter` implementation. In the end I managed to do it by registering `IObjectAdapter` as follow in Autofac:

    builder.Register(c => new ObjectAdapter(new DefaultContractResolver(), logErrorAction: null))
           .As<IObjectAdapter>();

I would create a constructor without `logErrorAction` in order to make it "more injectable".

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, August 30, 2017 9:50:44 AM_

@dario-hd thanks for the extra info, we will evaluate this in our next team bug discussion.

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, September 7, 2017 4:56:09 PM_

@dario-hd we took a quick look at this and we think we still need a bit more info. Can you provide info on what it is you're trying to inject? Maybe show the code that you'd like to be able to write when setting up your container and services?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
