### ISSUE TITLE
Update Microsoft.AspNet.JsonPatch nuget package version

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2433]
_From @en-alepopa on Monday, April 24, 2017 7:55:00 AM_

Hi everyone,

The ASP NET Core version of this package is at version 1.1.1: https://www.nuget.org/packages/Microsoft.AspNetCore.JsonPatch/

But the ASP NET standard version of this package was not updated since 2015, at version 1.0.0-beta8: https://www.nuget.org/packages/Microsoft.AspNet.JsonPatch/1.0.0-beta8

I realise this may not be the proper platform to request this, but can you push to latest stable version for Microsoft.AspNet.JsonPatch on NuGet to 1.1.1 as well? 

_Copied from original issue: aspnet/JsonPatch#77_

**Comment by aspnet-hello** [comment]
_From @rynowak on Monday, April 24, 2017 11:59:09 AM_

The `Microsoft.AspNet.JsonPatch` package is just the old name of this package. You can use `Microsoft.AspNetCore.JsonPatch` on desktop framework (net451)

**Comment by aspnet-hello** [comment]
_From @en-alepopa on Tuesday, April 25, 2017 1:21:35 AM_

Thanks! Can you guys update the https://www.nuget.org/packages/Microsoft.AspNet.JsonPatch/1.0.0-beta8 page with this information? At first sight, it's not clear that AspNetCore.JsonPatch can be used with AspNet 4.6

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, April 27, 2017 9:23:37 AM_

The only thing we can do is un-list the package, which will probably solve this problem for most people. It won't show up in search results, etc.

**Comment by aspnet-hello** [comment]
_From @dennisroche on Thursday, August 3, 2017 10:01:48 PM_

Vote to close as package as been unlisted

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, August 4, 2017 2:45:31 PM_

That specific version is unlisted, but I believe there are other versions that are still listed, such as https://www.nuget.org/packages/Microsoft.AspNet.JsonPatch/1.0.0-beta7.

**Comment by mkArtakMSFT** [comment]
We will unlist the package.
