### ISSUE TITLE
Reduce allocations for a typical patch scenario

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2434]
_From @kichalla on Wednesday, March 1, 2017 11:55:04 AM_

For the following typical `replace` operation
```
[
    { "op": "replace", "path": "/Name", "value": "Roger Federer" }
]
```

**Before:**
![image](https://cloud.githubusercontent.com/assets/6559784/23478151/3a9217f6-fe75-11e6-8483-d2790bf1e665.png)

**After:**
After making the following couple of changes, I see a 30% reduction in memory usage
- Fix the round-tripping issue mentioned here https://github.com/aspnet/JsonPatch/issues/69
- Avoid validating the `JsonPatchDocument` itself (AFAIK this is not required as an end user is not going to validate it but should be validating his model....that said validating the model while patching is an open question currently as we do not validate the model)

![image](https://cloud.githubusercontent.com/assets/6559784/23478303/c45a488c-fe75-11e6-880a-45d97d9d518a.png)

_Copied from original issue: aspnet/JsonPatch#70_

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
