### ISSUE TITLE
Check if round tripping an operation's value is required

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2435]
_From @kichalla on Tuesday, February 28, 2017 10:54:51 AM_

We currently round trip the 'value' provided in an 'operation' here:
https://github.com/aspnet/JsonPatch/blob/dev/src/Microsoft.AspNetCore.JsonPatch/Internal/ConversionResultProvider.cs#L15

**Valid types in JSON:** 
number,
string,
bool,
array,
object,
null

**Some things we need to verify in the above line of code:**
- If the 'value' is of the same type as the 'typeToConvertTo', then we can avoid round tripping. This is being handled in the PR https://github.com/aspnet/JsonPatch/pull/63
- If the value is of type `JArray` or `JObject`, then we could use the `ToObject` on them: http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_ToObject.htm

**Some scenarios to consider if we plan to avoid round tripping:**
value type: string
target type: System.Guid

value type: Int64 (default json.net type for integers)
target type: Int32

@Eilon 

_Copied from original issue: aspnet/JsonPatch#69_

**Comment by aspnet-hello** [comment]
_From @kichalla on Tuesday, February 28, 2017 3:03:20 PM_

A working change (in my private branch): https://github.com/aspnet/JsonPatch/commit/7f7ff71bc00f3fece41ce77e95d2937954baf63b

**Comment by mkArtakMSFT** [comment]
Thanks @kichalla, but it's time to close this as there was no community involvement in this issue for quite a while.
