### ISSUE TITLE
DefaultFilesMiddleware doesn't work with encoded path

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2452]
_From @mifopen on Saturday, February 18, 2017 6:07:06 PM_

Repro:
Embed the following directory structure:

    └───wwwroot
        │
        └───а
            └──index.html
where 'а' is russian letter 'а' (char)1072
Use the folowing code:

```
app.UseDefaultFiles();
```
Go to http://localhost:5000/а/ (on server it will be http://localhost:5000/%D0%B0)

Expected index.html content gets displayed
Actual: 404

_Copied from original issue: aspnet/StaticFiles#175_

**Comment by aspnet-hello** [comment]
_From @mifopen on Saturday, February 18, 2017 6:12:47 PM_

This happens because DefaultFilesMiddleware calls
```this._fileProvider.GetDirectoryContents(subpath.Value).Exists``` with ```subpath.Value```, but calls ```this._fileProvider.GetFileInfo(subpath + defaultFileName).Exists``` with ```subpath.ToString()```.
Example:
request url: http://localhost:5000/%D0%B0
context.Request.Path.ToString(): /%D0%B0
context.Request.Path.Value: /а

**Comment by muratg** [comment]
@Tratcher Do you know if this is still an issue?

**Comment by Tratcher** [comment]
Yes
https://github.com/aspnet/StaticFiles/blob/0755bf3c1ca2069747f03e5a54c278ff74868ac5/src/Microsoft.AspNetCore.StaticFiles/DefaultFilesMiddleware.cs#L76

**Comment by Tratcher** [comment]
Fixed by https://github.com/aspnet/StaticFiles/pull/257
