### ISSUE TITLE
Review FileExtensionContentTypeProvider and document the criteria for being included

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2454]
_From @Tratcher on Wednesday, April 27, 2016 11:44:38 AM_

`FileExtensionContentTypeProvider` contains the file extension to content-type mappings used by the `StaticFilesMiddleware`. Only extensions listed will be served by default. The original list was copied from IIS but we've made some additions.
- [x] Review the APIs and make sure it's easy enough for people to add and remove entries.
- [x] Document the criteria for including an entry in the default list.
- [ ] Review the current entries to make sure they meet the criteria.

@DamianEdwards 

_Copied from original issue: aspnet/StaticFiles#129_

**Comment by aspnet-hello** [comment]
_From @DamianEdwards on Wednesday, April 27, 2016 7:49:16 PM_

As part of the first item, I'd like to see what it would like to have an app set up to read a config file that specifies the file extension to content-type mappings, as an example.

**Comment by aspnet-hello** [comment]
_From @muratg on Wednesday, May 25, 2016 11:55:39 PM_

Moving to post RTM for now. Ping me if you think this has to be done this week.

**Comment by aspnet-hello** [comment]
_From @Tragetaschen on Monday, July 11, 2016 2:57:25 AM_

I've just tried to add a new file extension + content type to use with the file server.
There is definitely room for improvement:

``` csharp
var fileExtensionContentTypeProvider = new FileExtensionContentTypeProvider();
fileExtensionContentTypeProvider.Mappings[".vtt"] = "text/vtt";
var options = new FileServerOptions();
options.StaticFileOptions.ContentTypeProvider = fileExtensionContentTypeProvider;

app.UseFileServer(options);
```

**Comment by aspnet-hello** [comment]
_From @Tratcher on Tuesday, September 13, 2016 4:32:34 PM_

Policy considerations:
- Include file types included in other server's default sets
- Do not include file types likely to contain server-side code or configuration (e.g. cs, cshtml, json, etc..)
- Prefer mime types with well documented standards (e.g. RFCs)

This policy should be placed in the wiki and/or in a doc comment on FileExtensionContentTypeProvider

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, October 12, 2016 3:30:46 PM_

Adding/Removing file types has discoverability issues, but we haven't found a fix without breaking changes. Consider removing the IContentTypeProvider abstraction, it's rarely replaced.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Tuesday, October 25, 2016 3:38:37 PM_

@muratg recommend moving this to the 2.0 milestone for API breaking changes

**Comment by aspnet-hello** [comment]
_From @muratg on Wednesday, June 14, 2017 3:35:51 PM_

@DamianEdwards @glennc Do we want to do this in 2.0.0? (We may need to as it could be a breaking change.)  If so, priority?

**Comment by aspnet-hello** [comment]
_From @muratg on Tuesday, September 26, 2017 3:36:05 PM_

@Tratcher Backlogging this for now.

**Comment by Tratcher** [comment]
@shirhatti @muratg

**Comment by muratg** [comment]
Good find! @shirhatti Let's close on this.

**Comment by weweilep** [comment]
I'm not certain if this is the right place to mention this or not, but FileExtensionContentTypeProvider currently provides to way to support files without extensions.  ASP.NET allowed mapping to "." to match them, but FileExtensionContentTypeProvider currently works with neither "" nor "." nor "filename_of_file_without_extension" though that last one would be least ideal anyway.

**Comment by Tratcher** [comment]
@weweilep that seems like a different issue. Is that covered by ServeUnknonFileTypes? https://github.com/aspnet/AspNetCore/blob/dffe9abf6b6b009e183e808459e65770c9210a52/src/Middleware/StaticFiles/src/StaticFileOptions.cs#L36-L47

**Comment by weweilep** [comment]
@Tratcher I was just editing to acknowledge that that is indeed available, but that is an overly-broad brush as it opens to more than just files with no extensions.  https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.2 contains a pretty stern note saying it is not a recommended use.
