### ISSUE TITLE
Travis builds on Linux fail due to dependency issues

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2463]
_From @ryanbrandenburg on Tuesday, October 10, 2017 12:33:18 PM_

https://travis-ci.org/aspnet/WebSockets/jobs/278439693. This appears to have been caused by a change in Travis images rather than within this repo.

_Copied from original issue: aspnet/WebSockets#205_

**Comment by anurse** [comment]
We don't Travis anymore :)
