### ISSUE TITLE
Dispose the WebSocket at the end of the request

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2466]
_From @davidfowl on Friday, June 23, 2017 7:00:46 PM_

From https://github.com/aspnet/WebSockets/issues/182#issuecomment-306214086, we don't dispose the websocket object at the end of the request. We should be doing this.

_Copied from original issue: aspnet/WebSockets#189_

**Comment by anurse** [comment]
Duplicate https://github.com/aspnet/AspNetCore/issues/2854 (yeah, that one is newer but the discussions are on the other issue so...)
