### ISSUE TITLE
Could not load file or assembly 'System.Net.WebSockets, Version=4.0.0.0, Culture=neutral

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2469]
_From @paulopez78 on Tuesday, June 13, 2017 1:49:59 AM_

This is my scenario:

I've created a nuget package [EasyWebSockets](https://www.nuget.org/packages/EasyWebSockets) that targets `netstandard1.3` and has a dependency to `Microsoft.AspNetCore.WebSockets 1.0.2`

I'm using that package without any issue in ASP .NET Core projects targeting `netcoreapp1.1`

The problem starts when also **targeting net461**, the build is working but in runtime throws: `System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Net.WebSockets, Version=4.0.0.0, Culture=neutral`

Taking a look at the differences between the `deps.json` files in the bin folder when targeting net461 and targeting netcoreapp1.1 looks like the **System.Net.WebSockets** package is not needed for net461. Please correct me if I'm wrong but what I understand is that **System.Net.WebSockets** is an out of band package from the CoreFX and when targeting net framework should provide type forwards to `System.dll` where it is really implemented in the net framework. 

When targeting net461
```json
      "microsoft.aspnetcore.http.features/1.1.2": {
        "dependencies": {
          "Microsoft.Extensions.Primitives": "1.1.1",
          "NETStandard.Library": "1.6.1"
        },
        "compile": {
          "lib/net451/Microsoft.AspNetCore.Http.Features.dll": {}
        }
      }
```
When targeting netcoreapp1.1
```json
      "microsoft.aspnetcore.http.features/1.1.2": {
        "dependencies": {
          "Microsoft.Extensions.Primitives": "1.1.1",
          "NETStandard.Library": "1.6.1",
          "System.ComponentModel": "4.3.0",
          "System.Net.WebSockets": "4.3.0",
          "System.Security.Claims": "4.3.0",
          "System.Security.Principal": "4.3.0"
        }
```
The only way that I was able to fix it was referencing the System.Net.WebSockets package in my project with a conditional. It is really strange because when using straight the package `Microsoft.AspNetCore.WebSockets 1.0.2` in my project instead of my library I don't have that reference problem with `System.Net.WebSockets`. My understanding is that it should be transparent because my package is targeting netstandard1.3 and I shouldn't do this kind of tricks.

That's my csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.1;net461</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="EasyWebSockets" Version="0.0.4" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net461'">    
    <PackageReference Include="System.Net.WebSockets" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
  </ItemGroup>
</Project>
```

_Copied from original issue: aspnet/WebSockets#184_

**Comment by anurse** [comment]
> The problem starts when also **targeting net461**, the build is working but in runtime throws

Does this occur in a `net46` app that just directly references `System.Net.WebSockets`?

FYI, ASP.NET Core 1.x is [nearing end-of-life](https://dotnet.microsoft.com/platform/support/policy/dotnet-core), so if this doesn't repro in 2.1 or higher we aren't likely to be investing in a fix.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
