### ISSUE TITLE
Provide a convenience method to filter logging for health checks

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2581]
_From @Drawaes on Wednesday, October 11, 2017 10:11:50 AM_

Once you start doing health checks in anger and you have say 1 per second, if you have kestrel at info level you get a lot of data in the log you don't care about. Would be nice if there was an extension method on ILoggerFactory to filter anything to do with health checks that isn't an error out.

_Copied from original issue: aspnet/Diagnostics#412_

**Comment by rynowak** [comment]
We don't really have a way right now to configure log verbosity of the other parts of the stack based on where the request is going.

**Comment by rynowak** [comment]
Closing this since we plan to take no action.
