### ISSUE TITLE
Dedicated page for JavaScript invoked on server-side

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2585]
_From @rosieks on Friday, August 18, 2017 1:24:13 PM_

SpaServices project provides ability to run JavaScript on server. When such invocation failed the following error is displayed.

![image](https://user-images.githubusercontent.com/1107959/29476261-7e05f9ca-8463-11e7-9e3d-fbb1cd04425c.png)

It would be nice to have dedicated page that focus on JavaScript error and provide nicefied stacktrace, current npm version, etc

_Copied from original issue: aspnet/Diagnostics#404_

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, August 23, 2017 12:11:12 AM_

@SteveSandersonMS any thoughts on this? We've been thinking of some diagnostics pages extensibility in general, for example: https://github.com/aspnet/Diagnostics/issues/403

**Comment by aspnet-hello** [comment]
_From @SteveSandersonMS on Wednesday, August 23, 2017 12:02:31 PM_

It would definitely be good to present this information more readably - the stack trace at least.

If the new diagnostics extensibility point issued a call back to get the nicely formatted error info, passing the original exception, then it would be easy enough to embed whatever info we need into the `NodeInvocationException` and pull it out.

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, August 24, 2017 10:33:38 AM_

Ok, we'll consider something for 2.1.0 then.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.

**Comment by cjblomqvist** [comment]
It seems this has not been fixed and will not be fixed? Or am I missing something? This would be very helpful. Atm this makes it very cumbersome to develop anything using NodeServices, since it's always guesswork to figure out where errors come from.
