### ISSUE TITLE
Write exception details to response body even after the response has started

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2587]
_From @halter73 on Friday, July 28, 2017 5:43:41 PM_

The developer exception page does not currently write anything to the response body [if the response has already started](https://github.com/aspnet/Diagnostics/blob/23948c5544f947f7c20d01f0bbca81d696523c1b/src/Microsoft.AspNetCore.Diagnostics/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs#L80). This makes some sense considering that anything written to the response body would likely be corrupted and might not even be visible in the browser window. The DeveloperExceptionPageMiddleware also will log the exception which somewhat mitigates the problem of not writing the exception details to the response body.

Despite all this, I still think it would be better for the developer exception page to append some exception details to the existing partial response body. Seeing corrupted yellow screens of death helped me debug some SignalR issues on ASP.NET 4. We could make the developer exception page behave even better than the yellow screen by writing the exception details as plain text in this case.

You might not want to do this for responses with a Content-Length header though.

_Copied from original issue: aspnet/Diagnostics#401_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, August 2, 2017 11:14:19 AM_

@GrabYourPitchforks  is hanging his head in shame....

In addition to checking Content-Length, you'd also have to check Content-Type. Assuming the response was HTML, you then have the challenge of inserting something legible at a random place. The YSOD would attempt to close out tags, tables, etc. to work around this. At the end you also still face the close of aborting the connection or completing it gracefully so the client can actually read the page.

Side note: I've primarily seen this issue when serializing JSON responses, not HTML. Injecting random JSON would cause data corruption.

**Comment by aspnet-hello** [comment]
_From @halter73 on Wednesday, August 2, 2017 11:21:32 AM_

I'm sure the YSOD didn't check the Content-Type. It happily spit HTML out into SignalR's json-encoded event source stream and it was glorious 😄 Like I said, it helped me quickly diagnose more than a few issues.

It's not like the developer error page is enabled in production, right? And if it is, it's probably to make things easier to debug which this would probably do.

Checking Content-Length header is even *that* important. Kestrel will prevent too much from being written and kill the connection immediately after the failed request in any case. The main reason for checking is so the exception thrown by Kestrel for writing too much to the response body doesn't obscure the original exception in the logs.

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, August 4, 2017 11:29:11 AM_

I'd have thought that the logs would be a perfectly sufficient mitigation to this, no? I could imagine that dumping more garbage into the response would likely cause other errors in an app to start manifesting, such as weird SignalR client errors, weird service client errors (that is, whatever is making web requests to your app).

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, August 4, 2017 11:35:33 AM_

We get a lot of bug reports that say "It failed" because they don't know how to get to the logs.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, August 4, 2017 11:37:43 AM_

Even for exceptions that happen prior to the response starting, we get a lot of bug reports complaining about a "blank screen" (e.g. a 500 with no body) when people don't have an exception handler. Many don't know how to check the status code, let alone find the logs.

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, August 4, 2017 11:54:15 AM_

@Tratcher this isn't about having exception handlers, just about developer exception page.

But also, in VS15.3 I think we make the logs very easy to find, no? It's right there in VS.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, August 4, 2017 12:41:24 PM_

I know, it was just a related example where people have trouble finding our logs. If 15.3 makes it that much easier for folks then great, though it will still take some getting used to.

**Comment by aspnet-hello** [comment]
_From @halter73 on Friday, August 4, 2017 12:59:34 PM_

> I'd have thought that the logs would be a perfectly sufficient mitigation to this, no?

You would think that..., but you should really [read this](https://github.com/aspnet/KestrelHttpServer/issues/1858#issuecomment-312375868) to really get an appreciation for how that's not the case. I think that comment illustrates just how many people might be helped (and how much of my time might be saved) if we just spat out exception details to the response body. And that's just accounting for people who found the Kestrel GitHub repo after searching the ERR_INCOMPLETE_CHUNKED_ENCODING error Chrome produces.

I'm also hopeful that VS15.3 will improve things, but I'm not so sure it will help much. And in my mind even if VS15.3 helps a lot, this change will just help even more.

As for weird service client and SignalR client errors, that's going to happen either way. The response is corrupted no matter what.

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, August 4, 2017 2:39:49 PM_

I do still find this very odd, simply because it's a very odd thing to do 😄 I agree that logging won't always be immediately available or obvious even in dev cases.

So... yeah sure I'm ok with doing this.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
