### ISSUE TITLE
Define handlers for status codes with UseStatusCodePages

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2589]
_From @jchannon on Wednesday, April 12, 2017 4:17:48 AM_

In Nancy you can implement a `IStatusCodeHandler` which has CanHandle and a Handle methods. CanHandle returns a boolean that says for this statuscode I can handle it and then in the Handle it writes a response.

In UseStatusCodePages it seems to be a global filter for status codes. How do I say only execute `x` when the statuscode is `y`. Only examples I have seen is to write a Controller method that has a switch statement on the statuscode and that is very ugly. 

Is there a cleaner way of doing it? If not could we make it cleaner?

_Copied from original issue: aspnet/Diagnostics#357_

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, June 6, 2017 10:20:59 AM_

Seems like an interesting idea, but no current plans to implement this.

**Comment by mkArtakMSFT** [comment]
@Tratcher, is there any reason we don't provide a simple way to register a handler per status code?

**Comment by Tratcher** [comment]
Only the complexity of implementing it on our side. I'd be curious to see some proposals.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
