### ISSUE TITLE
Preserving the original exception with multiple exception handlers

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2594]
_From @gustafsonk on Monday, February 15, 2016 12:25:19 PM_

There's already a comment in the code for this feature, but I didn't see an issue created for it so I decided to make this one.

https://github.com/aspnet/Diagnostics/blob/a03b2dc6b4b540391be189cea2a5a8f75c890b29/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L79

My use case is that I want to have different behaviors for exceptions depending on context like the URL, such as returning a JSON response for a failed API request while returning an HTML response for a failed user page request. I also want to use errorHandlingPath behavior on one of the exception handlers so I can have the HTML scenario handled by an MVC controller. Here's what my code relatively looks like:

```
// these are effectively try-catches so define them in reverse order
app.UseExceptionHandler("/Home/Error");
app.UseExceptionHandler(handler =>
{
    handler.Run(async context =>
    {
        var exception = context.Features.Get<IExceptionHandlerFeature>().Error;

        if (context.Request.Path.StartsWithSegments("/api"))
        {
            context.Response.ContentType = "application/json";
            var response = new
            {
                Error = exception.Message
            };
            await context.Response.WriteAsync(JsonConvert.SerializeObject(response));
        }
        else
        {
            // lose the stack trace, otherwise you could rewrap it in another exception
            throw exception;
        }
    });
});
```

The current solution I can come up with involves either throwing the exception stored in the Error property and losing the stack trace of the original exception, or wrapping the exception into another one and making sure that's handled properly across the other exception handlers.

It would be nice to be able to say in an exception handler that the exception was not handled and to keep going up the chain until it is handled. Alternatively I would be happy with a way of combining the 2 handlers in my example into 1 handler if it's simple enough.

_Copied from original issue: aspnet/Diagnostics#248_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Tuesday, February 16, 2016 9:55:00 AM_

Maybe if we made ExceptionHandlerOptions.ExceptionHandler return a bool indicating if the exception was handled or should be rethrown. Give it a try and consider sending a PR if it works.

**Comment by aspnet-hello** [comment]
_From @Eilon on Saturday, February 20, 2016 11:21:38 PM_

Parking in the backlog for now, but definitely would be a nice feature. If you have a PR we will certainly take a look.

**Comment by aspnet-hello** [comment]
_From @Ciantic on Wednesday, April 20, 2016 6:59:34 AM_

This feature should support returning e.g. BadRequestObjectResult() from a custom error handler instead of writing to Response directly.

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, April 20, 2016 9:05:45 AM_

`BadRequestObjectResult` is an MVC feature so that can't quite be used here. This issue is about errors at a lower level in the system.

**Comment by aspnet-hello** [comment]
_From @Ciantic on Wednesday, April 20, 2016 10:46:39 AM_

@Eilon I understand that now, but looking at the @gustafsonk's code there, where he wants to turn exception to JSON result. I was struggling with same thing, I realized using a middleware for that is not a good idea.

I made own middleware and a filter, and filtter is a better approach, you can compare the two here: https://gist.github.com/Ciantic/c771eb07ee2b69d0442ac3986fc07bd9 just register the filter globally or to your Api controllers only and you have granularity.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
