### ISSUE TITLE
Poor diagnostics when UseErrorHandler points to a non-existing URL (IIS/IIS Express)

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2595]
_From @Eilon on Monday, August 31, 2015 12:17:01 PM_

My project has the usual `app.UseErrorHandler("/Home/Error");` call in it, but I forgot that I deleted the `/Home/Error` action from my app. I'm using IIS Express locally, and IIS on Azure Web Sites.

When I run locally, I get the following IIS error:

```
HTTP Error 403.14 - Forbidden

The Web server is configured to not list the contents of this directory.
```

And on Azure it behaves as if my web app never started, showing a "how to upload your site to Azure" default help page.

It would be nice if there was some way to detect this incorrect configuration of my app and show a more meaningful and actionable error. It took me, @muratg, and @anurse quite a while to figure out what was going on.

_Copied from original issue: aspnet/Diagnostics#174_

**Comment by aspnet-hello** [comment]
_From @davidfowl on Monday, August 31, 2015 2:20:05 PM_

Is that beta6?

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, September 8, 2015 9:47:02 AM_

May have even been beta5... I can try with newer bits.

**Comment by aspnet-hello** [comment]
_From @danroth27 on Tuesday, September 15, 2015 10:04:56 AM_

We tried this with beta7 and it looks like you now just get a 404 response for the original request, which his a bit misleading as it's the error page that cannot be found not the originally request resource. Ideally in this situation you would get a 500 because the server is misconfigured.

**Comment by aspnet-hello** [comment]
_From @danroth27 on Tuesday, September 15, 2015 10:06:01 AM_

@Tratcher Let's chat about what we can do here.

**Comment by aspnet-hello** [comment]
_From @davidfowl on Tuesday, September 15, 2015 10:07:28 AM_

We should also try this with the HttpPlatform handler since that's our IIS story going forward.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
