### ISSUE TITLE
Support for IDistributedCache

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2603]
_From @mgroves on Wednesday, September 6, 2017 6:26:09 AM_

It doesn't appear that `ResponseCache` works with `IDistributedCache` ([see this issue](https://github.com/brantburnett/Couchbase.Extensions/issues/8) over at Couchbase.Extensions. Please correct me if I'm wrong.

Will you be adding support for `IDistributedCache` in the future?

_Copied from original issue: aspnet/ResponseCaching#137_

**Comment by aspnet-hello** [comment]
_From @Jetski5822 on Monday, October 23, 2017 1:52:46 AM_

+1

Or at least open the middleware up to allow us to inject a distributes cache implementation in to it. Is there a reason why https://github.com/aspnet/ResponseCaching/blob/dev/src/Microsoft.AspNetCore.ResponseCaching/ResponseCachingMiddleware.cs#L40 is not injected in? Thus allowing us to swap the implementation?

**Comment by aspnet-hello** [comment]
_From @hampos on Wednesday, November 22, 2017 3:43:59 AM_

+1

The constructor should be opened to allow injecting other `IResponseCache` implementations.
@JunTaoLuo Any plans on doing just that?

**Comment by aspnet-hello** [comment]
_From @JunTaoLuo on Wednesday, November 22, 2017 11:28:48 AM_

No current plans for it yet, it will need to be triaged for a future release. cc @muratg

**Comment by aspnet-hello** [comment]
_From @theofanis on Thursday, November 23, 2017 12:42:23 AM_

+1 

@JunTaoLuo Any valid reason why this doesn't depend on an injected `IResponseCache` implementation and go with the `new MemoryResponseCache` when calling the internal constructor? 

If you were set to the `MemoryResponseCache` usage, you could make this optional and initialize to `MemoryResponseCache` when omitted, a good documentation would then steer developers on how to use this correctly.

When you say future release, does this mean wait 6 months? The answer is vital because it may make more sense for us to just fork this and go with our own version until you guys push it.

**Comment by aspnet-hello** [comment]
_From @muratg on Thursday, November 23, 2017 11:54:23 AM_

@DamianEdwards @glennc

**Comment by muratg** [comment]
@DamianEdwards @glennc I'm closing this. Feel free to reopen if you'd like to get this anytime soon.

**Comment by RehanSaeed** [comment]
Does this mean that we are definately not getting this for 3.0 and maybe even beyond?

**Comment by muratg** [comment]
@RehanSaeed Not for 3.0. In case we end up budgeting for this later, this may end up coming back.
