### ISSUE TITLE
I18n, localization roadmap, features

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2635]
_From @brgrz on Monday, July 24, 2017 11:26:34 AM_

I was wondering if the current feature set will be expanded in any way given that i18n support is rather basic  (the only thing new being the two interfaces) and most of the features the same as they were in MVC 5 (Data annotations, resx files).

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization

Also, how come MS is staying with resx files which are a 20 year old technology and have never evolved to cover more complex i18n scenarios.

It'd be nice to see some advances in the field of i18n, simple string replacement methods are not enough or something that would suffice in 2017.

I was thinking something along the lines of Angular.io i18n features, which is based on XLIFF and supports pluralization, genders, selections, etc.

https://angular.io/guide/i18n

What is Microsoft's take on this?

_Copied from original issue: aspnet/Localization#397_

**Comment by hishamco** [comment]
@brgrz I already asked for Pluralization from the early days https://github.com/aspnet/Home/issues/2653, but seems [OrchardCore](https://github.com/OrchardCMS/OrchardCore) build a pluralization APis based on PO files which is something interesting. I'm not sure if there's something else you need to add.
FYI the localization API is more flexible and extensible, so you can build the implementation that you comfortable with

**Comment by mkArtakMSFT** [comment]
@brgrz, as @hishamco pointed out, the API is extensible and you can do extend it in ways you need. OrchardCore's example is a great one.
As for the upcoming release, we have no much planned for localization.
