### ISSUE TITLE
Default Supported(UI)Cultures should be all Cultures available

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2640]
_From @NCC1701M on Wednesday, March 29, 2017 12:19:58 AM_

The default vaule for SupportedCultures and SupportedUICultures should be all Cultures available and not only the current one. I use a different approach for localization because I develop Intranet sites and I like to give administrators the possibility to translate the page on the fly. But with this concept you provide here it's way to complicated to add new languages.

 SupportedCultures and SupportedUICultures should only be there to restrict the cultures if set and not to ignore all cultures than current if not set.

_Copied from original issue: aspnet/Localization#352_

**Comment by aspnet-hello** [comment]
_From @hishamco on Wednesday, March 29, 2017 12:25:38 AM_

@NCC1701M this is back to an old discussion here issue #111

**Comment by aspnet-hello** [comment]
_From @hishamco on Wednesday, March 29, 2017 12:28:08 AM_

FYI I already added an issue today #351 to think about the possibility to add a localization culture dynamically at runtime

Also there's another issue still open to support custom cultures #237, hope you follow those

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
