### ISSUE TITLE
Create Localization template for 'dotnet new'

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2641]
_From @Eilon on Tuesday, March 21, 2017 2:21:47 PM_

With the new `dotnet new` extensibility, it would be nice to have an ASP.NET Core template that is fully localizable.

_Copied from original issue: aspnet/Localization#347_

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, March 21, 2017 2:22:13 PM_

cc @DamianEdwards

**Comment by aspnet-hello** [comment]
_From @hishamco on Tuesday, March 21, 2017 2:44:24 PM_

Why we didn't add starter template like what we have in the [entropy](https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb) repo

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, March 21, 2017 3:04:51 PM_

@hishamco that's essentially what we want in the template. Someone just has to do the work to wrap it in the structure that `dotnet new` uses (and make sure the content is appropriate).

**Comment by aspnet-hello** [comment]
_From @hishamco on Tuesday, March 21, 2017 3:11:13 PM_

Sure, but in which repo shall we add this template, perhaps I 'll contribute to this if it's not assigned to anyone 😄

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, March 21, 2017 4:45:42 PM_

@DamianEdwards where do you want this to live?

**Comment by aspnet-hello** [comment]
_From @DamianEdwards on Tuesday, March 21, 2017 8:53:40 PM_

@Eilon can we just put it in the aspnet/Templates repo? As a new package?

**Comment by hishamco** [comment]
@Eilon this is duplicate for https://github.com/aspnet/Templating/issues/70

**Comment by hishamco** [comment]
@Eilon just skip my last comment, while the issue https://github.com/aspnet/Templating/issues/70 has been transferred

**Comment by ryanbrandenburg** [comment]
Closing this in favor of https://github.com/aspnet/AspNetCore/issues/5406.
