### ISSUE TITLE
Log all searched locations for non existance resources

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2646]
_From @hishamco on Friday, March 3, 2017 10:39:54 PM_

After the PR #331, me as a developer I expect to log all searched locations for non-exist localization resources
Assume that I add the culture `ar`, with enabling parent culture fallback, so when the current culture is `ar-YE` I except the logger logs:
```
searched for 'Hello' in 'LocalizationSample.Startup' with culture 'ar-YE'.
searched for 'Hello' in 'LocalizationSample.Startup' with culture 'ar'.
```
instead of log the first message after fallback

/cc @ryanbrandenburg @pranavkm 

_Copied from original issue: aspnet/Localization#336_

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, August 8, 2017 12:38:05 PM_

@hishamco are you saying that in 2.0.0 only the first log is written, but not the second log?

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, August 8, 2017 12:38:42 PM_

BTW I think this might be happening because ASP.NET Core isn't the one doing the fallback - it's .NET Core / .NET Framework doing it, and we don't participate in the fallback logic it uses.

**Comment by aspnet-hello** [comment]
_From @hishamco on Tuesday, August 8, 2017 12:59:44 PM_

> @hishamco are you saying that in 2.0.0 only the first log is written, but not the second log?

Yep

> BTW I think this might be happening because ASP.NET Core isn't the one doing the fallback - it's .NET Core / .NET Framework doing it, and we don't participate in the fallback logic it uses.

It would be nice if we have the behavior that I mentioned on the first thread, which is similar to MVC fallback for views

@Eilon my aim here is to write a very useful log, because the localization already fallback to the parent culture

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, August 8, 2017 3:40:43 PM_

Yeah I don't think that ASP.NET Core has any control over that. The .NET fallback implementation will run without ASP.NET Core's knowledge - there's nowhere to inject the logging as far as I know. In particular, there's no way I know of to log things *as they happen*. You can log it before or after, but I don't think that's nearly as useful because in case there's an error, it won't be clear what triggered the error.

**Comment by aspnet-hello** [comment]
_From @hishamco on Tuesday, August 8, 2017 8:50:04 PM_

The current implementation is already write a log when the resource is not found. just we need to write another log, because if the resource isn't found and `Fallback` is `true` we are know that we already searched for that resource in the current culture and its parents

**Comment by aspnet-hello** [comment]
_From @Eilon on Monday, August 14, 2017 9:31:19 AM_

@hishamco - I thought it's .NET itself that does the fallback of cultures, no? The only fallback that I can find that ASP.NET Core does is to determine which culture to select based on the incoming request's culture (e.g. headers, cookies, etc.). When it comes to doing the resource lookup, I can't find anything that does a meaningful fallback.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.

**Comment by hishamco** [comment]
@mkArtakMSFT I was waiting for the AspNetCore team to respond to me for what I suggested before?!!

**Comment by hishamco** [comment]
Still I believe there is a value for such feature, especially in debugging. BTW what I suggested is similar what MVC is doing if the view that's looking for is not found
