### ISSUE TITLE
Localization & Output Caching

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2652]
_From @hishamco on Wednesday, June 24, 2015 11:31:06 AM_

I'm wondering if the **Output Caching** will block the localization APIs from retrieving the right values for the current culture, or shall we need sort of `VaryByCustom` to update the correct values based on the current culture

/cc @DamianEdwards 

_Copied from original issue: aspnet/Localization#40_

**Comment by aspnet-hello** [comment]
_From @hishamco on Tuesday, September 15, 2015 6:24:25 PM_

@kirthik please your thoughts about this

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, September 17, 2015 4:32:11 PM_

There are no features currently planned for directly solving this. The correct approach at this time is to set the appropriate VaryBy headers on the response.

**Comment by aspnet-hello** [comment]
_From @hishamco on Thursday, September 17, 2015 4:49:08 PM_

Thanks @Eilon, is there a plan to support such thing

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, September 17, 2015 8:29:49 PM_

It needs to be done by the user manually.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

**Comment by hishamco** [comment]
This issue from the first days of DNX :) no problem if it's closed, while there's a caching mechanism built in the localization APIs
