### ISSUE TITLE
TemplateParser should be able to report multiple errors

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2657]
_From @rynowak on Tuesday, October 17, 2017 5:57:04 PM_

Currently the template parser code throws an argument exception with the first error it encounters in parsing a route template. 

We should have a custom exception type for this and expose rich information including the original template and **all** errors that were found. This will be more useful to extenders and will be needed by us when we do richer diagnostics functionality

_Copied from original issue: aspnet/Routing#476_

**Comment by aspnet-hello** [comment]
_From @rynowak on Tuesday, October 17, 2017 5:57:28 PM_

We should do this after preview 1 as it's not high priority, just polish

**Comment by mkArtakMSFT** [comment]
Closing as low-value work.
