### ISSUE TITLE
InlineRouteParameterParser shouldn't exist

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2658]
_From @rynowak on Tuesday, October 17, 2017 5:54:42 PM_

`InlineRouteParameterParser` is a separate static class from the `TemplateParser` with its own public entry point that is responsible for parsing the contents of a parameter.

Example:
`{controller=Home}/{action=Index}/{id?}`

In this case it would be called once for `controller`, once for `action` and once for `id?`. 

There are some layering problems with this API overall
- It doesn't handle escaping
- It is called with the contents of the parameter, not the whole parameter
- It doesn't need to be public, it's a detail of the template parser
- It can't report errors, it always returns a 'parameter', even if it's in valid

---------

We should obsolete this method in `Microsoft.AspNetCore.Routing` and remove it in 3.0. For the dispatcher we should fix all of the above issues and not make this functionality public.

_Copied from original issue: aspnet/Routing#475_

**Comment by aspnet-hello** [comment]
_From @rynowak on Tuesday, October 17, 2017 5:55:16 PM_

We should do this after preview 1. It's not a critical issue

**Comment by aspnet-hello** [comment]
_From @rynowak on Tuesday, October 17, 2017 6:12:02 PM_

I'm putting a few notes in the code related to this. Do a search for `#475` when you fix this.

**Comment by mkArtakMSFT** [comment]
Closing as low-value work
