### ISSUE TITLE
Add fallback addresses

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2660]
_From @rynowak on Wednesday, September 27, 2017 12:09:01 PM_

We want the dispatchers to be able to work with 'fallback' addresses

This is an address which works like a conventional route - it can generate a URL when no other address matches

_Copied from original issue: aspnet/Routing#458_

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
