### ISSUE TITLE
URL generation should be able to be keyed off of non-string elements

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2664]
_From @Eilon on Tuesday, September 5, 2017 1:25:50 PM_

Today's routing system is based entirely off of string dictionaries. We should have a way to have other data types, such as `Type` (e.g. of an MVC controller) act as inputs into locating a route for URL generation.

_Copied from original issue: aspnet/Routing#436_

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, November 7, 2017 10:55:20 AM_

Moving to Backlog as there are no plans to implement this at this time.

cc @rynowak FYI because of Dispatcher, though this isn't directly related (but might be interesting)

**Comment by mkArtakMSFT** [comment]
No community interest in this.
