### ISSUE TITLE
LowercaseUrls = true in RouteOptions doesn't affect URLs with non-Roman characters

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2665]
_From @DevelAx on Sunday, September 3, 2017 12:17:16 PM_

In ASP.NET MVC CORE 2.0

```
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<RouteOptions>(options => options.LowercaseUrls = true);
    services.AddMvc();
}
```

`<a asp-action="New-Post">New post</a>`

works fine giving URL like http://domain/controller/new-post
But this one

`<a asp-action="Новая-Публикация">Новая публикация</a>`

produces URL like http://domain/controller/Новая-Публикация

**Seems like RouteCollection uses ToLowerInvariant() to lower-case the URL:** https://github.com/aspnet/Routing/blob/032bcf43b2cefe641fc6ee9ef3ab0769024a182c/src/Microsoft.AspNetCore.Routing/RouteCollection.cs#L155

_Copied from original issue: aspnet/Routing#435_

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, September 5, 2017 6:14:49 PM_

Ah, I think the problem here is that the Cyrillic part of the URL is already URL-encoded (to `%xx%xx%xx` etc.), so the `ToLowerInvariant()` doesn't have much to do at that point.

I think to fix this we'd need to have somewhat different logic about how/where to do the lowercase operation.

**Comment by aspnet-hello** [comment]
_From @DevelAx on Tuesday, September 5, 2017 10:04:23 PM_

Thank you for the clarification, Eilon! 
Should I expect it will be fixed in the future?
In modern browsers encoded URLs are usually displayed in a friendly decoded form in the address bar or when the user hovers over a link with the cursor.

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, September 5, 2017 10:42:10 PM_

@DevelAx we'll investigate this issue some more to see what we can do. I'm not sure how easy it will be. Yes, browsers typically show the "friendly decoded" URL, which is why I had to look at the "view source" of the page to get a hint of what was going on.

A not-so-fun workaround in the meantime is to just use lowercase letters everywhere 😄

**Comment by aspnet-hello** [comment]
_From @DevelAx on Tuesday, September 5, 2017 10:57:34 PM_

Ok, thank you!
Sure you will find the most graceful way to fix it.

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, September 7, 2017 4:37:11 PM_

Moving to Backlog for now because this turns out to be quite complicated to fix.

However, we're looking at some bigger changes to Routing in the near future and we'll try to account for fixing this in the new design.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
