### ISSUE TITLE
Don't depend on common.props in samples

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2666]
_From @ryanbrandenburg on Tuesday, May 23, 2017 2:39:50 PM_

We shouldn't depend on common in samples. Import dependency.props instead and add the explicity reference to NETStandard.Library.NETFramework

_Copied from original issue: aspnet/Routing#410_

**Comment by mkArtakMSFT** [comment]
Closing as obsolete!
