### ISSUE TITLE
Slashes incorrectly encoded when building URL with catchall param?

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2669]
_From @Daniel15 on Saturday, September 10, 2016 10:27:27 PM_

Consider this controller:

``` csharp
public class TestController : Controller
{
  [Route("foo/{*path}")]
  public IActionResult Index(string path)
  {
    var url = Url.Action("Index", new { path = "hello/world" });
    return Content("Path = [" + path + "], built URL = " + url);
  }
}
```

When you hit `http://example.com/foo/some/url`, ASP.NET MVC Core will display:

```
Path = [some/url], built URL = /foo/hello%2Fworld
```

Whereas ASP.NET MVC 5 will display:

```
Path = [some/url], built URL = /foo/hello/world
```

Notice that the URL returned by `Url.Action` encodes `/` as `%2F`, whereas the previous MVC version did not do this.

Is this an expected change? If so, how do I render the URL such that the slash is **not** encoded?

_Copied from original issue: aspnet/Routing#363_

**Comment by aspnet-hello** [comment]
_From @SonicGD on Tuesday, November 29, 2016 10:55:46 AM_

Have same problem right now. Any news on this? @Daniel15, did you bypass it somehow?

**Comment by aspnet-hello** [comment]
_From @Daniel15 on Tuesday, November 29, 2016 11:36:18 AM_

I never got time to look into it, these routes on my site are still broken 😞

**Comment by aspnet-hello** [comment]
_From @SonicGD on Wednesday, November 30, 2016 9:21:40 AM_

So i did some investigation... Character encoding happens in https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Internal/UriBuildingContext.cs#L100

and UrlEncoder always filters '/' char - https://github.com/dotnet/corefx/blob/master/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/UrlEncoder.cs#L125

I don't see any way to configure or disable this behavior.

Maybe @NTaylorMullen or @rynowak will help us?

**Comment by aspnet-hello** [comment]
_From @SonicGD on Wednesday, November 30, 2016 9:58:29 AM_

Also, even if i generate correct url - i doesn't match route. ex:

```csharp
[HttpGet("/{parentUrl}/files/{catPath}/{fileName}.html")
```
where `catPath` is path like 'video/others'.

Only workaround i found is to use catchall param and then parse it with regex. And it looks ugly :cry:

**Comment by aspnet-hello** [comment]
_From @DeadSith on Sunday, December 11, 2016 9:02:58 AM_

The only way to bypass it now is to set urls in a tags using href, not built-in tag helpers. It makes it harder to refactor code, but at least you get good-looking urls.

**Comment by aspnet-hello** [comment]
_From @Daniel15 on Saturday, April 29, 2017 11:01:09 PM_

This is still broken :(

I worked around it by using `Url.Action` then calling `.Replace("%2F", "/")` on the resulting string. Ugly but it works: https://github.com/Daniel15/Website/commit/26b1d2ad8c307afda07d70769265ea71ce775d2c

**Comment by aspnet-hello** [comment]
_From @DamianEdwards on Tuesday, May 2, 2017 10:52:01 AM_

@rynowak @Eilon @danroth27 comments?

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, May 2, 2017 4:47:21 PM_

We'll see if we can take another look at this. The problem, if I recall, isn't so much with how to encode slashes, but rather what to do when they come back in. I believe that servers/reverse-proxies such as IIS (and no doubt others) will *decode* the slashes on the way in, so you don't get round-tripping of data. We spent a lot of time back in MVC 1.x-5.x trying to make this work and never could. It's possible that today things are different.

**Comment by aspnet-hello** [comment]
_From @Daniel15 on Tuesday, May 2, 2017 11:47:40 PM_

> I believe that servers/reverse-proxies such as IIS (and no doubt others) will decode the slashes on the way in

Why would the slashes be encoded in the first place? If I have a route like `foo/{*path}`, hitting `/foo/bar/baz` is a valid path. I never had issues with that in older ASP.NET MVC versions, other than IIS6 which is not really a problem these days.

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, May 3, 2017 9:24:07 AM_

I believe that an incoming URL in the form `http://localhost/foo/bar` is *different* from `http://localhost/foo%2fbar`. The first URL has a path with two segments: `foo` and `bar`. The second URL has a path with one segment: `foo/bar` (once it's decoded).

**Comment by aspnet-hello** [comment]
_From @kaa on Wednesday, May 3, 2017 9:45:29 AM_

Arguably, if it was a "normal" path segment, but this is specifically a "catch all" path segment which by its nature is going to contain slashes in unencoded form. For a normal path segment the current implementation is the expected behavior of course.

Currently there is no way to create an url using the UrlHelper that fits your first form, as far as I understand. This is what we're asking for.

**Comment by aspnet-hello** [comment]
_From @Daniel15 on Wednesday, May 3, 2017 10:15:13 AM_

Yeah, @Eilon  I should have clarified that this is a catchall segment, so it should capture everything including slashes. 

The actual routing is working fine, it's just the URL builder that's incorrectly HTML encoding the slashes.

**Comment by doggy8088** [comment]
@DamianEdwards @Daniel15 I think I met the same issue in the **Azure Function Proxy** too..  Check this out: https://github.com/Azure/azure-webjobs-sdk-script/issues/2249

**Comment by mkArtakMSFT** [comment]
@danroth27, any thoughts regarding this?

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please investigate what options we can have here? Just come up with some proposal about this and let's discuss it with the team.
//cc: @Tratcher

**Comment by javiercn** [comment]
I spoke about this with @rynowak a while ago and I spoke to @Tratcher too.

There are some security implications with not completely escaping the path as we need to deal with things like "/Path/../../../" but Kestrel and IIS take care of those things on the inbound path.

We can special case the way we encode a catchAll parameter when we build the url by just creating a new instance of PathString (calling the constructor) and then calling ToString() on the PathString to produce the properly encoded value.

The fix will probably happen somewhere around here
https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Template/TemplateBinder.cs#L228

**Comment by javiercn** [comment]
This would be a breaking change, so we need to think about if we are willing to take it.
@mkArtakMSFT I'm sending this back to triage.

**Comment by juho-hanhimaki** [comment]
I run into this issue in API projects quite often and the workaround is pain in the ass. So my vote to fix this in future.

**Comment by doggy8088** [comment]
@juho-hanhimaki Is there any workaround on this issue right now?

**Comment by doggy8088** [comment]
@javiercn May I ask why this issue would be a breaking change?

**Comment by javiercn** [comment]
@doggy8088 Because the '/' are getting encoded right now into '%2F' and they won't be if we do this change, and that has the potential to break people's apps depending on how their webservers are configured.

**Comment by doggy8088** [comment]
@javiercn It’s obviously a bug on encoding when using catchall routing. I think there is nobody will relying on this feature and the workaround right now is not affecting if you patched this bug.  If user’s backend server is using IIS, no matter what they apply this patch no not, they won’t be affected either. If user use Apache Web server, there is same things. No one will be affected. So I don’t think it’s a breaking change.

**Comment by doggy8088** [comment]
@javiercn Please have a look at my study here: https://github.com/Azure/azure-functions-host/issues/2249#issuecomment-353762199

**Comment by DevelAx** [comment]
Can anyone clarify if it is going to be fixed soon? I couldn't grasp it from the discussion.

**Comment by Eilon** [comment]
@DevelAx I'm not sure we can commit to when, if ever, this might be fixed. It's a very tricky problem and I'm not sure there's a perfect solution. We might have to do some think-outside-the-box solution to this to make sure we preserve compatibility, but maybe have some new way of enabling new functionality. Maybe an option to choose how to encode, or some convention to specify parameters that should be encoded one way or another. Not sure.

**Comment by doggy8088** [comment]
@Eilon I made a demo repo here: https://github.com/doggy8088/CatchAllRouteProblem

Here is the **ASP.NET Core 5** controller sample code:
https://github.com/doggy8088/CatchAllRouteProblem/blob/master/MVC5/Controllers/HomeController.cs

Here is the **ASP.NET Core 2.0** controller sample code:
https://github.com/doggy8088/CatchAllRouteProblem/blob/master/Core2MVC/Controllers/HomeController.cs

These two controllers are exactly identical.   You can check the execution result below.

The following screenshot is the **ASP.NET MVC 5** result:
![image](https://user-images.githubusercontent.com/88981/36495334-d7fdc238-176f-11e8-8f9e-36acf0d70c88.png)

The following screenshot is the **ASP.NET Core 2.0** result:
![image](https://user-images.githubusercontent.com/88981/36495361-e6a5eeaa-176f-11e8-9081-2222d6e4dc12.png)

As you can see, the built URL format is wrong.  That's the problem.

**Comment by DevelAx** [comment]
@Eilon Thank you for replay! I'll be waiting for it. Hope you won't forget about this issue.

@doggy8088 You're right. It worked perfectly in MVC 5. Now it has to be always kept in mind not to use default helpers while using *catchall* option in routes.

**Comment by doggy8088** [comment]
@Eilon The problem only exists in ASP.NET Core.  The ASP.NET MVC 5 is working perfectly!  Can you explain why this is a tricky problem?  I thought ASP.NET Core 2 and ASP.NET MVC 5 are share the same code base. (almost)  The routing logic should be exactly the same, doesn't it?

**Comment by DevelAx** [comment]
@doggy8088 The odd thing is that we have the *catchall* option in routes. But this option is not supported by route-helpers in Core.

**Comment by doggy8088** [comment]
@DevelAx It do support,  It just has a bug in it.  😞

**Comment by Eilon** [comment]
@doggy8088 the code bases are almost entirely different between the two products.

**Comment by valeriob** [comment]
I'm migrating AspNet Mvc application and got bitten by this issue, what's the suggested work around ?

**Comment by DevelAx** [comment]
@valeriob for example, if you want to use `Url.Link` with `<a>` tag, you could create a helper class, like this:
```
public static class MyUrlHelper
{
    public static string LinkFixedSlash(this IUrlHelper urlHelper, string routeName, object values)
    {
        return urlHelper.Link(routeName, values).Replace("%2f", "/");
    }
}
```
Example of usage in a view:
```
<a href="@Url.LinkFixedSlash(RouteNames.PostsRoute, new { path = post.UrlPath })">
    @Model.PostHeader
</a>
```

**Comment by doggy8088** [comment]
Hope this bug can be fixed in **ASP.NET Core 2.1**.  There are tons of potential ASP.NET MVC devs are going to migrate their website to ASP.NET Core.  The inconsistence of the routing feature are really annoying. 😢

**Comment by javiercn** [comment]
Costing here is for the investigation work

**Comment by Eilon** [comment]
@mkArtakMSFT - should we move to preview2? We came up with a design yesterday but the work won't be done by EOD today...

**Comment by rynowak** [comment]
The plan we discussed was to move to 2.2.0

**Comment by mkArtakMSFT** [comment]
We've decided to add a new feature to support this scenario in 2.2
We will add a new syntax `{**catchAll}` that will parse catchAll segments as PathString instances.
Users will be able to generate urls without encoded slashshes in catch all values by passing a `PathString` as the value (or if its on the ambient values)

**Comment by DevelAx** [comment]
The same trouble with `RedirectToRoute` method.
This 
`return RedirectToRoute(RouteNames.HomeRoute, new { path = "xxx/yyy" });`
generates url with _"xxx%2fyyy"_.

**Is there workaround for this?**

**Comment by DevelAx** [comment]
I couldn't find any easy workaround so I wrote a custom `MyRedirectResult` class for this purpose:

    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Routing;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    using Microsoft.Net.Http.Headers;
    using System;
    using System.Text.Encodings.Web;
    using System.Threading.Tasks;

    public class MyRedirectResult : ActionResult, IKeepTempDataResult
    {
        private string _url;

        public MyRedirectResult(string url, bool permanent = false, bool preserveMethod = false, bool local = false)
        {
            Url = url;
            Permanent = permanent;
            PreserveMethod = preserveMethod;
            IsLocal = local;
        }

        public bool Permanent { get; private set; }

        public bool PreserveMethod { get; private set; }

        public bool IsLocal { get; private set; }

        public string Url
        {
            get => _url;
            private set
            {
                if (string.IsNullOrEmpty(value))
                    throw new ArgumentException(nameof(value));

                _url = value;
            }
        }

        public IUrlHelper UrlHelper { get; set; }

        public override Task ExecuteResultAsync(ActionContext context)
        {
            ExecuteResult(context);
            return Task.CompletedTask;
        }

        public override void ExecuteResult(ActionContext context)
        {
            if (context == null)
                throw new ArgumentNullException(nameof(context));

            var urlHelper = UrlHelper ?? GetUrlHelper(context);

            // IsLocalUrl is called to handle URLs starting with '~/'.
            var destinationUrl = Url;
            if (!IsAsciiCharacters(destinationUrl))
                destinationUrl = UrlEncoder.Default.Encode(destinationUrl).Replace("%2f", "/", StringComparison.OrdinalIgnoreCase);

            if (urlHelper.IsLocalUrl(destinationUrl))
            {
                destinationUrl = urlHelper.Content(destinationUrl);
            }
            else
            {
                if (IsLocal)
                    throw new InvalidOperationException("The supplied URL is not local. A URL with an absolute path is considered local if it does not have a host/authority part. URLs using virtual paths ('~/') are also local.");
            }

            context.HttpContext.Response.Headers[HeaderNames.Location] = destinationUrl;

            if (PreserveMethod)
            {
                context.HttpContext.Response.StatusCode =
                    Permanent
                    ?
                    StatusCodes.Status308PermanentRedirect
                    :
                    StatusCodes.Status307TemporaryRedirect;                
            }
            else
            {
                context.HttpContext.Response.StatusCode =
                    Permanent
                    ?
                    StatusCodes.Status301MovedPermanently
                    :
                    StatusCodes.Status302Found;
                context.HttpContext.Response.Redirect(destinationUrl, Permanent);
            }
        }

        #region Helpers

        private IUrlHelper GetUrlHelper(ActionContext context)
        {
            var httpContext = context.HttpContext;

            if (httpContext == null)
                throw new ArgumentException(nameof(ActionContext.HttpContext));

            if (httpContext.Items == null)
                throw new ArgumentException(nameof(httpContext.Items));

            // Perf: Create only one UrlHelper per context
            object value;
            if (httpContext.Items.TryGetValue(typeof(IUrlHelper), out value) && value is IUrlHelper)
                return (IUrlHelper)value;

            var urlHelper = new UrlHelper(context);
            httpContext.Items[typeof(IUrlHelper)] = urlHelper;
            return urlHelper;
        }

        private static bool IsAsciiCharacters(string headerCharacters)
        {
            if (headerCharacters == null)
                return true;
            
            foreach (var ch in headerCharacters)
            {
                if (ch < 0x20 || ch > 0x7E)
                    return false;
            }

            return true;
        }
        #endregion
    }

**Usage**: add to your `BaseController` class methods like these:

        public MyRedirectResult MyLocalRedirect(string url)
        {
            return new MyRedirectResult(url, local: true);
        }

        public MyRedirectResult MyLocalRedirectPermanent(string url)
        {
            return new MyRedirectResult(url, permanent: true, local: true);
        }

        public MyRedirectResult MyRedirect(string url)
        {
            return new MyRedirectResult(url);
        }

        public MyRedirectResult MyRedirectPermanent(string url)
        {
            return new MyRedirectResult(url, true);
        }

and use them as regular redirect methods with return from action.

**Comment by doggy8088** [comment]
@DevelAx In your [sample](https://gist.github.com/DevelAx/f873f1beaf86b1f31ee8bb679762f088#file-myredirectresult-cs-L61), I think you can simply use `return Redirect(URL);` to do the same thing as your custom `MyRedirectResult`.

**Comment by DevelAx** [comment]
@doggy8088 If you try to pass a non-ASCII string, for example, "我的网站", you'll likely get the exception
`System.InvalidOperationException: Invalid non-ASCII or control character in header`. But this is not the major problem: you can't redirect to URL like "xxx/yyy" because the default `RedirectResult` converts all slashes to `%2F`, so the URL will be broken as "xxx%2fyyy", that's why I created `MyRedirectResult`.

**Comment by doggy8088** [comment]
@DevelAx I mean this one below.  Passing "xxx/yyy" in the default `RedirectResult` won't converts all slashes to `%2F`, the URL won't broken.

![image](https://user-images.githubusercontent.com/88981/39943809-cc9a94f6-5596-11e8-97b3-fbbd2ef077b7.png)

**Comment by DevelAx** [comment]
@doggy8088 guess what... you're right, it's my mistake. So, it's useful only for the first case in order not to do encoding for each redirect, example:
```
string url = UrlEncoder.Default.Encode("我的网站/About").Replace("%2F", "/");
return Redirect(url);
```
But this case can be considered a bit offtopic for this thread.

**Comment by mkArtakMSFT** [comment]
@jamesnk, @rynowak, @kichalla please consider this as part of the `Dispatcher` work:

 > We've decided to add a new feature to support this scenario in 2.2.0
We will add a new syntax {**catchAll} that will parse catchAll segments as PathString instances.
Users will be able to generate urls without encoded slashshes in catch all values by passing a PathString as the value (or if its on the ambient values)

**Comment by mkArtakMSFT** [comment]
Closing this as done!

**Comment by russgove** [comment]
Hey, so how do i call an azure function that has a url segment with slashes from typescript? 

I have my function signature set like this:
  public static async Task<HttpResponseMessage> GetRoleToTransactionsForRoleName(
           [HttpTrigger(AuthorizationLevel.Function, "get", Route = "RoleToTransactions/{**RoleName}")]HttpRequestMessage req,
           TraceWriter log,
           string RoleName)
        {

still getting errors

**Comment by doominator42** [comment]
I can't get this to work. My route is `/somepath/{**name}` and here is how i'm trying to generate the url:
```
// name = "x/y"
Url.Action("ActionName", "ControllerName", new { name }) 
// results with "/somepath/x%2Fy"
```
also tried
```
// name = "/x/y"
Url.Action("ActionName", "ControllerName", new { name = new PathString(name) }) 
// results with "/somepath/%2Fx%2Fy"
```

Anyone has managed to make it work and can help me?

**Comment by Eilon** [comment]
**Hi, it looks like you are   posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:

1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem.
