### ISSUE TITLE
Need to rewrite/refactor TemplateBinder to reduce RouteValueDictionary allocation

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2670]
_From @ajaybhargavb on Wednesday, August 3, 2016 12:10:50 PM_

Original issue - https://github.com/aspnet/Mvc/issues/4593#issuecomment-218627205

We want to have a cleaner fix than what we have in https://github.com/aspnet/Routing/pull/314

@rynowak @Eilon 

_Copied from original issue: aspnet/Routing#348_

**Comment by mkArtakMSFT** [comment]
Closing as this is now obsolete.
