### ISSUE TITLE
Need more log info when requests matching conventional routing match actions with attribute routes

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2672]
_From @kichalla on Tuesday, June 14, 2016 2:04:34 PM_

For the following controller

``` c#
public class LinksController : Controller
{
    [Route("api/links")]
    public string Index()
    {
        return "Links.Index";
    }
}
```

and Startup.cs configured like below

``` c#
app.UseMvc(rb =>
{
    rb.MapRoute("default", "{controller}/{action}");
});
```

A request like `links/index` results in 404. This is expected but the logs do not provide much info here. Should we give more detail? 

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/links/index
dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name 'default' and template '{controller}/{action}'.
dbug: Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler[3]
      No actions matched the current request
dbug: Microsoft.AspNetCore.Builder.RouterMiddleware[1]
      Request did not match any routes.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 29.8027ms 404
```

_Copied from original issue: aspnet/Routing#325_

**Comment by aspnet-hello** [comment]
_From @rynowak on Tuesday, June 14, 2016 2:15:47 PM_

agreed, we can do better than "No actions matched the current request" for this case

**Comment by aspnet-hello** [comment]
_From @EvilBeaver on Thursday, November 16, 2017 5:20:54 AM_

Why it's wontfix?

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, November 16, 2017 9:48:45 AM_

@EvilBeaver please see @rynowak 's comment. There isn't anything more to log in this case.

**Comment by aspnet-hello** [comment]
_From @EvilBeaver on Friday, November 17, 2017 1:52:04 AM_

@Eilon i'm looking at @rynowak comment and see "agreed, we CAN do better". For me, this means "There is something else we can log" Isn't it?

**Comment by aspnet-hello** [comment]
_From @rynowak on Friday, November 17, 2017 8:08:20 AM_

@EvilBeaver what additional info could we provide that would help?

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, November 17, 2017 8:08:45 AM_

Oops sorry I somehow misread @rynowak 's comment several times! My bad.

**Comment by aspnet-hello** [comment]
_From @EvilBeaver on Saturday, November 18, 2017 8:02:07 AM_

@rynowak I missed additional log info for process of creating ActionDescriptors by ApplicationModel. Thanks for opened sources - I looked inside and found what framework has wanted from me.

Additional log can be - building app-model, processing all action-controller infrastructure on startup, examining DecisionTree for selecting correct action... Many corners of framework startup are not covered by logging.

**Comment by aspnet-hello** [comment]
_From @EvilBeaver on Saturday, November 18, 2017 8:03:50 AM_

I suppose @kichalla as original issue author can also tell some use-cases

**Comment by aspnet-hello** [comment]
_From @Eilon on Monday, November 27, 2017 3:09:14 PM_

Reactivating in case someone wants to take a stab at this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
