### ISSUE TITLE
Do a full optimization pass on Link Generation

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2674]
_From @rynowak on Monday, November 23, 2015 8:12:59 AM_

We haven't put any work yet into optimizing the link generation process, but we need to give it a look - primarily for allocations of 'scratch' data structures like dictionaries.

_Copied from original issue: aspnet/Routing#236_

**Comment by aspnet-hello** [comment]
_From @Eilon on Saturday, June 4, 2016 9:24:18 AM_

@ajaybhargavb @rynowak can we expect anything here for 1.0.0? I don't think we have time to do anything significant here.

**Comment by aspnet-hello** [comment]
_From @Eilon on Monday, June 6, 2016 9:54:39 AM_

Punt to never, or punt to not-now-but-later?

**Comment by aspnet-hello** [comment]
_From @rynowak on Monday, June 6, 2016 10:18:26 AM_

Punt to 1.0.1 :+1:

**Comment by mkArtakMSFT** [comment]
Closing as Link Generation has now shipped!
