### ISSUE TITLE
Response cookies Append inconsistently applies SameSite default

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2675]
_From @Tratcher on Wednesday, December 27, 2017 9:11:02 AM_

The two Append overloads have inconsistent behavior for the samesite property that was added in 2.0.
```
                context.Response.Cookies.Append("Name1", "Value1");
                context.Response.Cookies.Append("Name2", "Value2", new CookieOptions());
```
```
Set-Cookie:Name1=Value1; path=/
Set-Cookie:Name2=Value2; path=/; samesite=lax
```

The two overloads should have the same defaults.

I noticed because we're making changes to CookiePolicy for http://github.com/aspnet/Security/issues/1561 and adding it to the templates. This will have the side-effect of causing the Append API to consistently use the second overload's behavior. 

_Copied from original issue: aspnet/HttpAbstractions#982_

**Comment by muratg** [comment]
This is a bug, but fixing it is a breaking change. We'll fix this in 3.0.0.

**Comment by muratg** [comment]
@Tratcher feel free to close if you feel breaking change is not worth it.

**Comment by Tratcher** [comment]
SameSite has been such a mine field that the best default here would likely be None.

@blowdart

**Comment by blowdart** [comment]
Yea *sigh* :( None should be the default.

**Comment by Tratcher** [comment]
https://github.com/aspnet/AspNetCore/issues/8212
