### ISSUE TITLE
FeatureCache is over-checked and over-reset

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2693]
_From @benaadams on Wednesday, August 23, 2017 6:59:06 PM_

A simple plantext middleware as below, will check the `Frame` `IFeatureCollection` 7 times and initialize/reset the Context, Resquest and Responses feature caches twice each.
```csharp
public static Task WriteResponse(HttpResponse response)
{
    var payloadLength = _helloWorldPayload.Length;
    response.StatusCode = 200;
    response.ContentType = "text/plain";
    response.ContentLength = payloadLength;
    return response.Body.WriteAsync(_helloWorldPayload, 0, payloadLength);
}
```

![](https://aoa.blob.core.windows.net/aspnet/feature-cache.png)

The extra reset and checks are from initalization; then reinitialization after `RequestServicesFeature` is added to the collection by the host, increasing the `IFeatureCollection`'s version count.

_Copied from original issue: aspnet/HttpAbstractions#924_

**Comment by aspnet-hello** [comment]
_From @muratg on Monday, October 30, 2017 10:45:25 AM_

@davidfowl thoughts?  (PR is assigned to you too.)

**Comment by muratg** [comment]
PR: https://github.com/aspnet/HttpAbstractions/pull/925

**Comment by benaadams** [comment]
Resolved by https://github.com/aspnet/AspNetCore/pull/7659
