### ISSUE TITLE
Don't allocate the FormFeature eagerly per request

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2699]
_From @davidfowl on Thursday, June 29, 2017 8:01:27 AM_

Today, in order to pass the form options to the `FormFeature`, we eagerly allocate it here https://github.com/aspnet/HttpAbstractions/blob/163836fe1f31dd1d2b288659c2dcaf1d827da3c4/src/Microsoft.AspNetCore.Http/HttpContextFactory.cs#L49. We should find a creative way to avoid doing this so eagerly in the common cases. Here are some options:

- Invent a new way to pass things to features lazily (hard, we tried this and ended up with crazy things)
- Only new up the `FormOptions` if they were overridden. We'd need a way to detect if the `FormOptions` were actually set. This is doable but could get ugly as there's no way to detect if options were configured. /cc @HaoK 
- Only set the `FormFeature` if the request is a POST and `HasFormContentType`. Gross, but would be more pay for play than what we have today.

/cc @vancem @Tratcher 

_Copied from original issue: aspnet/HttpAbstractions#880_

**Comment by aspnet-hello** [comment]
_From @HaoK on Thursday, June 29, 2017 9:19:53 AM_

We could add a new bool property to `IOptionsFactory<TOptions>` like `IsConfigured`, so you could then avoid calling IOptions.Value in this case.

**Comment by aspnet-hello** [comment]
_From @muratg on Monday, October 30, 2017 10:26:33 AM_

@davidfowl Backlogging this until we find a good design to prototype.

**Comment by davidfowl** [comment]
This is done
