### ISSUE TITLE
Determine what to do with pdbs for the shared runtime 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#2760]
As a follow up to https://github.com/aspnet/Universe/issues/131, we need to figure out what to do with the pdbs for the AspNetCore shared runtimes. Pdbs for the managed pdbs do not work with pdbs for the x-gened shared runtime binaries. This means we would need a way to distribute x-gened pdbs

**Comment by pranavkm** [comment]
cc @JunTaoLuo \ @Eilon

**Comment by JunTaoLuo** [comment]
We are pushing our symbols to the Microsoft symbol Servers now so no more action items here.
