### ISSUE TITLE
Task to Automatically generate RootNamespaceAttribute

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#2804]
In aspnet/Localization#435 we added an attribute you specify to make assemblies with RootNamespace's different from their AssemblyName work with Localization, but currently you have to create it manually, leaving a chance for it to get out of sync or not created. Let's make a task which is run at compile time (when we still have that info) to create it automatically.

**Comment by natemcmaster** [comment]
You may not need a task at all. As long as the user hasn't disabled assembly info generation, the .NET Core SDK supports using the `<AssemblyAttribute>` item group to generate assembly attributes.

Example: https://github.com/aspnet/BuildTools/blob/e19aeae9e53e87fc98b792adc11e645d858fe2cd/src/Internal.AspNetCore.Sdk/build/Common.props#L40-L43

**Comment by mkArtakMSFT** [comment]
@natemcmaster, are you suggestion to modify the .NET SDK to handle this for us?

**Comment by natemcmaster** [comment]
Not exactly. I'm suggesting you don't need to write an entire MSBuild task to do this. The SDK has a feature you can chain into. All Microsoft.Extensions.Localization needs is to add a package file `build/Microsoft.Extensions.Localization.props` that contains this:

```xml
<Project>
    <ItemGroup>
        <AssemblyAttribute Include="Microsoft.Extensions.Localization.RootNamespaceAttribute">
            <_Parameter1>$(RootNamespace)</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
```

**Comment by hishamco** [comment]
Any update on this?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.

**Comment by hishamco** [comment]
I was asking @natemcmaster since 7 months ago if there's any updates on this, I'm still interested on this if there's something need to be done in localization repo, otherwise closing this is fine for me
