### ISSUE TITLE
MVC Dispatcher

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#2819]

**Comment by mnmr** [comment]
Not that I really care how you you manage your issues/project, but it seems backwards to create a new issue (from a user-reported issue) and then tell people to follow "an existing issue". I'd recommend that you fix your wording ("we've relocated the issue to the proper team/project" or whatever is appropriate).

Also, you should copy or rephrase the description. I can't tell from the headline what needs to be fixed and no additional details are provided, so no-one else will be able to either, nor will they be able to find existing issues that match their problem.

**Comment by mkArtakMSFT** [comment]
Closing this as this is available through `Link Generation` available as part of 2.2.0-preview3 release: https://github.com/aspnet/Docs/issues/8763#issuecomment-431711462
