### ISSUE TITLE
Unexpected no-cache headers on StaticFiles in ASP.NET Core 2.0

### ISSUE THREAD

**Issue by riiight** [aspnet/AspNetCore#2855]
In ASP.NET Core 1.x, static files were being cached automatically on browsers (I believe via the eTag response header). When I upgraded to ASP.NET Core 2.x, I noticed that none of my files (e.g. .images, .woff) were being cached anymore. It looks like many more response headers are now being returned by 2.x's StaticFiles by default. Included in them are:

- Cache-Control:no-cache, no-store
- Pragma:no-cache

I manually removed these in order to return my static files to their 1.x state (i.e. cached).

I'm writing this issue because:

- I feel there should either be better documentation on the default response headers added to StaticFiles.
- Solving this took some investigation and I feel this may help someone else.

**Comment by blowdart** [comment]
@Rick-Anderson

**Comment by muratg** [comment]
@riiight Let us know if you found out what component have added these headers.  Or if you could get a Fiddler trace?
