### ISSUE TITLE
Querystring in path when calling ExceptionHandlerExtensions.UseExceptionHandler causes white screen of death

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/AspNetCore#2860]
Using a querystring in the path when calling ExceptionHandlerExtensions.UseExceptionHandler causes a white screen of death.

app.UseExceptionHandler("/Error/Index");

Works

app.UseExceptionHandler("/Error/Index?foo=bar");

Doesn't.
```
public class HomeController : Controller
{
    public IActionResult Index()
    {
        throw new Exception();
    }

    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseExceptionHandler("/Home/Error?foo=bar");
    app.UseMvc();
}
```

Using ASP.NET Core 2.

**Comment by Matthew-Bonner** [comment]
Actually, could be my code will close for now

**Comment by Matthew-Bonner** [comment]
app.UseExceptionHandler("/Error/Index/bar");

Doesn't work either, it appears the arguments of the action method are not being populated.

**Comment by Eilon** [comment]
@Matthew-Bonner it looks like you can call this overload: https://github.com/aspnet/Diagnostics/blob/3a868d87a2458fd025ca71e2538b3a72f67c7c50/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerExtensions.cs#L84

And pass in a ExceptionHandlerOptions: https://github.com/aspnet/Diagnostics/blob/3a868d87a2458fd025ca71e2538b3a72f67c7c50/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerOptions.cs

With your own PathString: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/PathString.cs

**Comment by Matthew-Bonner** [comment]
Thanks for coming back to me so quick. Is this the recommended way? Is using a querystring when calling UseExceptionHandler intended to be supported by design or are the classes mentioned added to allow this?

**Comment by Eilon** [comment]
@Matthew-Bonner I suspect we just didn't think it was common. You're probably the first to ask. I would certainly say that at this time it's the recommended way, even if only that it's apparently the *only* way 😄 

@Tratcher - any further thoughts on this one?

**Comment by Matthew-Bonner** [comment]
@Eilon not sure this will work, see https://github.com/aspnet/Security/issues/334

I'm hitting the same issue.

**Comment by Matthew-Bonner** [comment]
Based on your comment "We recommend using URL path segments to indicate this type of information." in the following https://github.com/aspnet/Security/issues/334 I will just go with using path segments.

**Comment by Tratcher** [comment]
We'd have to add a separate parameter for the query strings.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
