### ISSUE TITLE
307 and 308 redirects

### ISSUE THREAD

**Issue by miloush** [aspnet/AspNetCore#2864]
Could there be HttpResponse.Redirect methods with 307 and 308 status codes? e.g.
```C#
public void Redirect(string location, bool permanent, bool preserveMethod);
```

**Comment by khellang** [comment]
That method (with a different name) has been there since 2.0... See https://github.com/aspnet/Mvc/pull/6075

**Comment by khellang** [comment]
Ah, sorry, I re-read the question and see what you're asking now; an overload for this?

https://github.com/aspnet/HttpAbstractions/blob/e2dcbea4ecd5655392b6cce534eac820c508c699/src/Microsoft.AspNetCore.Http.Abstractions/HttpResponse.cs#L101-L107

**Comment by miloush** [comment]
Yes, overload for that, though I am not picky about the name. I am not using MVC this time.

**Comment by khellang** [comment]
I wonder why this method got "promoted" to be directly on the `HttpResponse` in the first place. It's not really much code, and it could easily be implemented as an extension method.

https://github.com/aspnet/HttpAbstractions/blob/e2dcbea4ecd5655392b6cce534eac820c508c699/src/Microsoft.AspNetCore.Http/Internal/DefaultHttpResponse.cs#L119-L131

**Comment by Tratcher** [comment]
@khellang only because it's a very common operation and it existed in several prior object models.

An overload that exposed the status code would be a start.

**Comment by khellang** [comment]
> This would make a useful extension.

It would, but I keep thinking it would be best to just keep in line with existing code and have the old overloads just call into the new one?

**Comment by anurse** [comment]
Moving this to the backlog, 3.0 is pretty well booked :). Would make a nice contribution if someone wants to make it though!

**Comment by Tratcher** [comment]
Verified in SDK 3.0.100-preview6-012234
