### ISSUE TITLE
Implementing Individual user accounts in local database in asp.net core 2.0 web API

### ISSUE THREAD

**Issue by 5Series** [aspnet/AspNetCore#2875]
Is there a way to create web api .net core 2.0 with individual user accounts stored in app database and can be extended to use google authentication similar to .net web api template.

currently in the core web api template does not have an option for that, and also is it going to add in the future for the .net core 2.0 web api template?

**Comment by Eilon** [comment]
Hi @5Series , though there isn't a built-in automatic way to do this, you can read the docs at https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/ to learn how to add external auth (such as Google accounts) to an application.

**Comment by Tratcher** [comment]
As for the API aspect, you'll want a token server that can exchange your user cookie for a Bearer token. ASP.NET Core doesn't have one but there are a few 3rd party ones.

**Comment by omotayo89** [comment]
@Tratcher  please point me to any third party

**Comment by Tratcher** [comment]
https://identityserver4.readthedocs.io/en/release/#access-control-for-apis is one example.

**Comment by douglasg14b** [comment]
The answers here are a bit confusing. Asp.net Core WebAPI cannot have local identity management? That seems... absurd.
