### ISSUE TITLE
Reuse adapter instances within an `ObjectAdapter`'s scope

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/AspNetCore#2922]
I just realized how inefficient `ObjectVisitor`'s current implementation is.  It creates a new adapter instance for _every_ segment of _every_ path of _every_ patch operation.  That looks wasteful to me, and I imagine it will become a performance issue for large `JsonPatchDocument`s.  The adapter instances can instead be cached and reused.  Of course, the `ObjectVisitor` instances are also currently being created anew for _every_ patch operation, so that should also be remedied.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
