### ISSUE TITLE
Move BindingAddress to public namespace

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#2979]
I'm not sure why this was made pubternal instead of public and why we're even using pubternal APIs across assemblies. We should fix this and BindingAddress should be public.

PS: This will break https://github.com/aspnet/BasicMiddleware/blob/726035e3fb8c4ee31a32522c16ff73278b9b13e7/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionMiddleware.cs#L124, I'm not sure where else we use it.

/cc @Tratcher @jkotalik

**Comment by anurse** [comment]
We should actually just look at making it `internal`.

**Comment by Tratcher** [comment]
By which we mean shared source.

**Comment by anurse** [comment]
Yes, as a result of making it `internal` we'll need to shared-source it to "share" it properly.

**Comment by davidfowl** [comment]
I'd like to internal all the things as part of preview7 (or make it public why it think it should be public)
