### ISSUE TITLE
Server side session state in dotnet core web api - How to benchmark and validate if it will benefit my application scalability?

### ISSUE THREAD

**Issue by gitfortee** [aspnet/AspNetCore#2986]
Hi, 

Our team is writing an Angular + Dotnet Core 2.0 Web API project. We are expecting this application to scale rapidly in the near future and therefore have some questions below:

Is maintaining server side state using sessions in a web api project a good practice? I understand this is not how REST works however would like to find out if maintaining server side state would benefit my application. We are expecting this application to scale fast in the near feature. 

Can someone help me with how to benchmark and find out numbers to validate our choice? - be it a REST ful approach where we send state with each request or persist session state at server and minimize request payload and database trips..? I don't know where to start hence seeking some guidance.

**Comment by Eilon** [comment]
@gitfortee this is a fairly broad question that clearly has many variables. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` tag.

I think the most we can suggest here is to use a performance analysis tool and measure what you think are likely/common scenarios. The "many variables" listed are things such as session payload sizes, scale-out behavior of the session store, number of clients, and so forth.
