### ISSUE TITLE
OwinFeatureCollection throwing exception in IHttpResponseFeature.OnCompleted and breaks AspNetCore model binding

### ISSUE THREAD

**Issue by damianh** [aspnet/AspNetCore#3022]
When running AspNetCore on an owin pipeline, `[FromBody]` model binding fails because of [this exception being thrown](https://github.com/aspnet/HttpAbstractions/blob/ce49e95239cfca6f857716082fda767ee6590bf3/src/Microsoft.AspNetCore.Owin/OwinFeatureCollection.cs#L172):

![image](https://user-images.githubusercontent.com/57436/38307376-d652b51e-3813-11e8-883c-8243dd8a4ff9.png)

![image](https://user-images.githubusercontent.com/57436/38307394-e848a30a-3813-11e8-90d1-d1d36cd044c5.png)

```
   at Microsoft.AspNetCore.Owin.OwinFeatureCollection.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.OnCompleted(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.OnCompleted(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Http.HttpResponse.RegisterForDispose(IDisposable disposable)
   at Microsoft.AspNetCore.Http.Internal.BufferingHelper.EnableRewind(HttpRequest request, Int32 bufferThreshold, Nullable`1 bufferLimit)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter.<ReadRequestBodyAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.<BindModelAsync>d__7.MoveNext()
```

I copied the `OwinFeatureCollection` code into my own project and commented out the throw...

![image](https://user-images.githubusercontent.com/57436/38307487-3009f93c-3814-11e8-9349-e3c3730f3326.png)

... and model binding now works:

![image](https://user-images.githubusercontent.com/57436/38307554-5ba93df0-3814-11e8-9838-0b72b8e0b0ec.png)

**Comment by damianh** [comment]
Can't believe I'm the first person to hit this 😃

**Comment by Tratcher** [comment]
Can you provide a concrete code sample? Screen shots make poor repros 😁

**Comment by damianh** [comment]
Sure, few minutes.

**Comment by damianh** [comment]
Here you go https://github.com/damianh/AspNetCoreOwinModelBindingRepro/blob/master/src/ConsoleApp1/Program.cs

F5 run should show the stack trace from the ModelState error in the console.

**Comment by Tratcher** [comment]
Removing the NotSupportException and silently ignoring OnCompleted isn't really an option, it would cause memory leaks. We have to find a way to implement OnCompleted even if means invoking the callbacks a bit early as the OWIN middleware exits. OwinFeatureCollection may need a Complete or Dispose method for the OwinHttpListenerServer sample server to call.

Out of curiosity why are you using Katana as a Core server?

**Comment by davidfowl** [comment]
> Can't believe I'm the first person to hit this 😃

🤣

**Comment by damianh** [comment]
We have a our own app server bootstrapping library. It provides a number of services to hosted applications and it is currently OWIN based. It has been working well for us and we're not ready to replace it. However we want to support teams that use AspNetCore while still supporting the teams that are OWIN based.

In the future, as migrations get further along, we'll likely invert things and host the OWIN apps on an aspnet core based bootstrapper. (If dependency management doesn't prevent us).

**Comment by Steve0212a** [comment]
What is the status of this?  I to am hitting this NotSupportedException().  How am I supposed to work around this?

**Comment by Tratcher** [comment]
What server are you using and why?

**Comment by Steve0212a** [comment]
I am not the web developer (on vacation), but I am pretty sure we are using OWin...

**Comment by Tratcher** [comment]
OWIN is not a server, it's a spec. What packages are you using?

**Comment by Steve0212a** [comment]
![2018-07-12_1201](https://user-images.githubusercontent.com/18215939/42645186-6b2f165a-85cb-11e8-85ac-b8fcd793d787.png)

Attached print screen of references.  Sorry again, not the web developer...

**Comment by Tratcher** [comment]
Interop with Microsoft.Owin.Host.SystemWeb is intentionally not supported. You need to have a long talk with your developer.

**Comment by davidfowl** [comment]
Right, running ASP.NET Core via OWIN on System.Web isn’t supported. Well take any changes that are reasonable here but going down that path will be fraught with bugs.

**Comment by damianh** [comment]
> Right, running ASP.NET Core via OWIN on System.Web

That's a bit mad alright.

> In the future, as migrations get further along, we'll likely invert things and host the OWIN apps on an aspnet core based bootstrapper.

I've since done this so this issue is not a concern to me any more. I guess if we wait long enough the need will go away 😄

**Comment by Danielku15** [comment]
@davidfowl I am developing an `IServer` implementation which I can use together with ASP.net core (aspnet/mvc) via `UseServer<>`. I adapted now the FeatureContext class of the HttpSys implementation for my purpose and it is working fine for me. I ended up with a mix of the `OwinFeatureCollection` and the `FeatureContext` source. 

**On topic:** 

The HttpSys implemementation exposes some methods to the the IServer implementation (MessagePump) which will invoke all registered listeners. Maybe this behavior could be adopted in the base `OwinFeatureCollection` instead of throwing directly a exception. This way the middlewares ran safely call all methods and the IServer implementation needs to call the related Invoke methods at the correct time.

**Comment by davidfowl** [comment]
> I ended up with a mix of the OwinFeatureCollection and the FeatureContext source.

I'm not sure why as OwinFeatureCollection was a bridge to the past. Unless you're explicitly trying to expose both the OWIN interface and the ASP.NET Core abstraction I don't see why you would need it.

**Comment by Danielku15** [comment]
In my `IServer` I received `IDictionary<string, object> environment` containing the OWIN compliant keys. The OwinFeatureCollection would be a handy way to execute the received request on the pipeline. Just like in the link I posted earlier. 

Here a simplified example of my implementation: 

```csharp
internal class BridgeContract : IServer
{
    private Func<OwinRequestWrapper, Task<OwinResponseWrapper>> _processRequest;

    public IFeatureCollection Features { get; } = new FeatureCollection();
    public EmpBridgeContract() { }

    // called from external
    public async Task<OwinResponseWrapper> ExecuteRequest(OwinRequestWrapper request)
    {
        reutrn await _processRequest(request);
    }

    public Task StartAsync<TContext>(IHttpApplication<TContext> application, CancellationToken cancellationToken)
    {
        _processRequest = async request =>
        {
            IDictionary<string, object> environment = request.ToOwinEnvironment();
            
            var responseStream = new DisposeNotifyStream();
            environment[OwinKeys.OwinResponseBody] = responseStream;
            environment[OwinKeys.OwinResponseHeaders] = new Dictionary<string, string[]>();

            var owinFeatures = new OwinFeatureCollection(environment);
            var features = new FeatureCollection(owinFeatures);
            var context = application.CreateContext(features);

            try
            {
                await application.ProcessRequestAsync(context);
                // await owinFeatures.OnResponseStart(); 
            }
            catch (Exception ex)
            {
                // await owinFeatures.OnCompleted(); 
                application.DisposeContext(context, ex);
                throw;
            }

            // reset stream for forwarding
            responseStream.Position = 0;
            responseStream.Disposed += () =>
            {
                // await owinFeatures.OnCompleted(); 
                application.DisposeContext(context, null);
            };

            return new OwinResponseWrapper(environment);
        };
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
```

The goal would be to use the OwinFeatureCollection as IFeatureCollection for creating the application context. The ASP.net middlewares (e.g. MVC/WebApi) will call OnCompleted() on the OwinFeatureCollection during the ProcessRequestAsync and currently lead to an exception.

I commented the areas where I now call correctly the OnCompleted and OnStarted callbacks just like the HttpSys implementation.

**Comment by Danielku15** [comment]
@davidfowl I already described the where my data comes from.  

>The values I supply are originally coming from a HttpSys server that lives on another machine so everything should be fine from the content. The custom IServer implementation is a HTTP over WebSocket reverse proxy which I need for architectural reasons.
(https://github.com/aspnet/Home/issues/3022#issuecomment-415070295)

**Comment by Danielku15** [comment]
I prepared a [Gist ](https://gist.github.com/Danielku15/e09a553fc3b19085f58bd75f4cafeac1)implementing a similar architecture than mine (just in-process). When you start it and try to open http://localhost/OWIN/Test you will see in the console that the request will fail with the exception from this issue. 

> So you have data coming from another server. I don't know that it matters that the server is http.sys.

It matters to me because it highlights that all the keys and values for the owin environment dictionary are valid and correct to be used in the OWIN pipeline. 

But still a dictionary with correct keys will lead to an exception in the OwinFeatureCollection when passed to the IHttpApplication. 

>  Why is OWIN in the picture? 

I use the OWIN pipeline to access the raw OWIN environment dictionary for transmission between my internal servers (see gist for details).

**Comment by davidfowl** [comment]
I wasn't asking about the issue, I was asking about your OWIN usage specifically. It seems like you just made the choice to use OWIN. What we have is now completely unusable and should be fixed. Maybe we should just implement a very basic method for triggering OnCompleted, or make the things that throw virtual so that they can be implemented.

**Comment by Danielku15** [comment]
Sure, I will try to extend the class and file a pull request on the weekend in my spare time.

**Comment by anurse** [comment]
Closing this as the OWIN interop is not a primary use case and it looks like there are workaround on this thread for all the issues.
