### ISSUE TITLE
Add OperatingSystems.NonWindows or OSSkipNonWindowsCondition and OSSkipWindows

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#3032]
When using OSSkipCondition on tests the most common combinations are:
`[OSSkipCondition(OperatingSystems.Linux | OperatingSystems.MacOSX)]`
`[OSSkipCondition(OperatingSystems.Windows)]`

These are used extensively in MusicStore, ServerTests, and also in a few places in HttpSys. These could be consolidated down to `[OSSkipCondition(OperatingSystems.NonWindows)]` or even further to  `[OSSkipWindowsCondition]` and `[OSSkipNonWindowsCondition]`

**Comment by mkArtakMSFT** [comment]
Closing as there is no clear need for this.
