### ISSUE TITLE
Generic Types Should Be Able to Be Depended and Injected by Implementation Factory repo:DependencyInjection

### ISSUE THREAD

**Issue by IndreamLuo** [aspnet/AspNetCore#3036]
https://github.com/aspnet/DependencyInjection/blob/4708d11dfe2a3df540578f026fc14d11a4f9ef48/src/DI/ServiceLookup/CallSiteFactory.cs#L36

Also refer to: [https://github.com/aspnet/DependencyInjection/issues/634](url)

Where:
``` 
if (implementationTypeInfo == null || !implementationTypeInfo.IsGenericTypeDefinition)
{
    throw new ArgumentException(
    Resources.FormatOpenGenericServiceRequiresOpenGenericImplementation(descriptor.ServiceType),
                            nameof(descriptors));
}

if (implementationTypeInfo.IsAbstract || implementationTypeInfo.IsInterface)
{
    throw new ArgumentException(Resources.FormatTypeCannotBeActivated(descriptor.ImplementationType, descriptor.ServiceType));
}
```
When there's generic type dependency with no concrete generic type injection but instance factory it'll throw the exception. Should be changed to like:
```
if ((implementationTypeInfo == null || !implementationTypeInfo.IsGenericTypeDefinition) **&& descriptor.ImplementationFactoryWithType == null**)
{
    throw new ArgumentException(
    Resources.FormatOpenGenericServiceRequiresOpenGenericImplementation(descriptor.ServiceType),
                            nameof(descriptors));
}
**else** if (implementationTypeInfo.IsAbstract || implementationTypeInfo.IsInterface)
{
throw new ArgumentException(
                            Resources.FormatTypeCannotBeActivated(descriptor.ImplementationType, descriptor.ServiceType));
}
```
In the case of using factory declaration of dependency as will be throwing exception "An unhandled exception of type 'System.ArgumentException' occurred in Microsoft.Extensions.DependencyInjection.dll: 'Open generic service type '[name of the type]' requires registering an open generic implementation type.'" in building web host which should be right in where new service descriptor is being added:
```
public class Startup
{
... ...
    public void ConfigureServices(IServiceCollection services)
    {
        ... ...
        services.Add[lifecycle type](myGenericType, provider => myFactory.GetInstance(myGenericType));
        ... ...
    }
}
```
And a new method should be provided as:
```
services.Add[lifecycle type](myGenericType, (provider, requiringType) => myFactory.GetInstance(requiringType));
```
And FactoryCallSite should be extended or new type of IServiceCallSite for factory with requiring type provided in invoking should be implemented.

**Comment by khellang** [comment]
I think you're asking for https://github.com/aspnet/DependencyInjection/issues/498? There's also https://github.com/aspnet/DependencyInjection/issues/450 and https://github.com/aspnet/DependencyInjection/issues/474.

**Comment by IndreamLuo** [comment]
Yes, I am. Seems it's a long unsolved problem.

I read the code and think there's fundamentally reconstruction required in storing dependency and invoking implementation injected. Of cause the generic implementation is not required in service descriptor building and passed on when getting the injection. Also in container cache the factory/inject implementation is stored as without parameter of invoking type required.

For a functionality purpose generic type injection may require more in D/I relationships. Such as specific concrete types may required some other injections as user wishes. User may want to do:
```
service.Add[Life Cycle](typeof(MyGeneric<>), implementation1);
service.Add[Life Cycle](typeof(MyGeneric<SomeType>), implementation2);
```
I haven't checked the current implementation of generic type D/I with open generic type injected's implementation. So I don't know if this is implemented or designed as another way.

I'd love to do it by my own self but realizing that there's only 2G less in my drive and the DI repo is on unpublished Core 2.1 which means I need to download the whole newest core repo to build it.

**Comment by khellang** [comment]
> User may want to do:
> 
> ```csharp
> service.Add[Life Cycle](typeof(MyGeneric<>), implementation1);
> service.Add[Life Cycle](typeof(MyGeneric<SomeType>), implementation2);
>```

This should already be possible?

Anyway, the reason this is a "long unsolved problem" is that in order for service descriptors include a factory delegate that requires more contextual information, like `requiringType` in your example above, all ASP.NET Core DI adapters have to be able to provide the same information. It's also a big breaking change.

All of this has been discussed back and forth many many times. I suggest you read through the issues in the DependencyInjection repository.

Oh, BTW, found another issue asking for the same thing; https://github.com/aspnet/DependencyInjection/issues/588 😉

**Comment by IndreamLuo** [comment]
Yes, it is possible. Technically, what needed is to change the hash algorithm of dependencies container cache. But it's more a production decision than tech. There's more works to do to define the behaviour details of contracts. Such as which define go first or which get covered.

Such an example:
···
service.Add[*](typeof(MyGeneric<,>), implementation1);
service.Add[*](typeof(MyGeneric<MyType1,>), implementation1);
···
Things may go crazy as a product to define clear rules of which go first or last.

Yeah, as you say. The first thing is to get a generic type factory being valid. Above are too early.

**Comment by davidfowl** [comment]
We'd recommend using one of the 3rd party containers that supports this feature. Currently it's not part of abstraction and work would have to be done to get all implementations implement this.
