### ISSUE TITLE
Using a common resource file for different classes jointly with owned resources of classes

### ISSUE THREAD

**Issue by XelaNimed** [aspnet/AspNetCore#3044]
Hello. 
I'm looking for the possibility of using a single resource file to localize error messages in the annotations of data models. As I understand it, we can use one common file to localize all data models, but in this case the resource keys will be very long, because in the presence of properties with the same name in different classes, we need to distinguish them in some way. If we use the usual approach (one model - one resource file), the resource keys become more compact, but the same error lines appear, for example, the length of the string or the required field. This means that if we need to change the error message (for ex.: Required or StringLength), we will need to change a large number of resources.

I asked question at comments feed [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) and at StackOverflow, but to no avail.

Can we somehow combine these two approaches? In the Display Attribute there is a parameter "ResourceType", can we use it? If "Yes", then how?

``` csharp
namespace MyProject.Models {
  public class Person {

        // Property "Nickname" used owned resource file for localization.
        // In file "/Resources/Models/Person.de.resx" exists string with key "Nickname". Works.
        [Display(Name = "Nickname")]
        public string Nickname { get; set; }

        // Property "FirstName" used owned resource file too.
        // In file "/Resources/Models/Person.de.resx" exists string with key "FirstName". Works.
        // But I want to use a single resource file to localize all the error strings.
        // What should I pass to the parameter "ResourceType"?
        [Display(Name = "FirstName")]
        [Required(ErrorMessage = "RequiredError", ResourceType = ?)]
        public string FirstName { get; set; }
    }
}

**Comment by ryanbrandenburg** [comment]
You most likely want `ErrorMessageResourceType` and `ErrorMessageResourceName` instead of ResourceType. But it's still a little unclear to me what exactly you're asking. If using those two parameters doesn't work can you link me a reproduction app as a GitHub repo so that I can see things as you do?

**Comment by ryanbrandenburg** [comment]
Try:
```
[Required(ErrorMessageResourceName= "TheKeyOfTheResource", ErrorMessageResourceType= typeof(YourSharedResourceType))
```

**Comment by mkArtakMSFT** [comment]
@XelaNimed, did @ryanbrandenburg's suggestion help?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by XelaNimed** [comment]
@ryanbrandenburg thanks! This is what I was looking for!
