### ISSUE TITLE
Dependency Injection, allow registering open generic of Func<>

### ISSUE THREAD

**Issue by AceHack** [aspnet/AspNetCore#3085]
I am able to do open generics of Types like the following

        class Lazier<T> : Lazy<T> where T : class
        {
            public Lazier(IServiceProvider provider)
                : base(() => provider.GetRequiredService<T>())
            {
            }
        }

        services.AddTransient(typeof(Lazy<>), typeof(Lazier<>));

But I have no way of doing this for Func<>

Thanks.

**Comment by MattJeanes** [comment]
This would be a great addition, as trying to port from Unity to ServiceProvider means I have to change everything from Func<T> to Lazy<T> which isn't a simple task for our (and I'm sure many others) codebases

**Comment by davidfowl** [comment]
We don't have plans to add native support for Func\<T\>, we'd need all supported containers adapters.
