### ISSUE TITLE
UseStaticFiles with [ or ] gives error 404

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#3093]
_From @fredriksknese on April 25, 2018 15:1_

In my Configure I have added 
```
app.UseStaticFiles(new StaticFileOptions() { RequestPath = "/archive", FileProvider = new PhysicalFileProvider("e:\\") });
app.UseDirectoryBrowser(new DirectoryBrowserOptions() { FileProvider = new PhysicalFileProvider("e:\\"), RequestPath = "/archive" });
```
and it works. When I then browse to http://localhost:5000/archive/ it shows the files and I can click to view all files except files that contain ```[``` and ```]```. It handles spaces and åäö (swedish characters) perfectly.

In console it prints
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:57205/archive/%5BWindows%5D%20tor.docker
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.1952ms 404
```
I'm using Microsoft.AspNetCore.All version ```2.0.6``` and TargetFramework ```netcoreapp2.0```

_Copied from original issue: aspnet/AspNetKatana#197_

**Comment by huysentruitw** [comment]
I cannot reproduce this. It works flawless with there configurations:

- netcoreapp2.0 with Microsoft.AspNetCore.All 2.0.6
- netcoreapp2.1 with Microsoft.AspNetCore.App 2.1.1
- netcoreapp2.2 with Microsoft.AspNetCore.App 2.2.0

**Comment by Tratcher** [comment]
Closing this as no-repro.
