### ISSUE TITLE
JavaScript content-type should be "text/javascript" instead of "application/javascript" and should contain charset=utf-8

### ISSUE THREAD

**Issue by molant** [aspnet/AspNetCore#3099]
[The WHATWG recommendation is to use `text/javascript`](https://html.spec.whatwg.org/multipage/infrastructure.html#dependencies)

![image](https://user-images.githubusercontent.com/606594/39325448-10fa2c94-4947-11e8-9452-9edc83aeb7c0.png)

Also, text based resources should contain `charset=utf-8` (if they are in `utf-8` which should be the case):

* [make sure things render correctly](https://www.w3.org/International/questions/qa-what-is-encoding)
* prevent the browsers from going down more complicated paths to guess what's the right charset of the file

There's more documentation in [this documentation](https://sonarwhal.com/docs/user-guide/rules/rule-content-type/)

**Comment by Tratcher** [comment]
PR: https://github.com/aspnet/StaticFiles/pull/220
@glennc

**Comment by shirhatti** [comment]
@Tratcher I think we should make this change in 3.0. It could potentially be breaking for some clients, so better to get it out early in one of the previews. Thoughts?

**Comment by shirhatti** [comment]
cc @RehanSaeed as the OP for his thoughts as well

**Comment by Tratcher** [comment]
With conflicting specs I don't see a clear right answer. It's not obvious that one will work better than the other, we haven't had any reports of a functional problem.

As for setting `charset=utf-8`, we've been over that and decided against it. We don't know what the encoding is for contents of the files.

**Comment by shirhatti** [comment]
What's the conflicting spec?

**Comment by Tratcher** [comment]
https://github.com/aspnet/AspNetCore/issues/3614#issuecomment-428919803

**Comment by shirhatti** [comment]
So can we close this for good?

**Comment by poke** [comment]
For what it’s worth, the [RFC that should have standardized this change](https://tools.ietf.org/html/draft-ietf-dispatch-javascript-mjs) also expired in November. So unless there is some fresh developments on this, I don’t think we need to do anything.
