### ISSUE TITLE
Enhancement to JsonPatch to provide a comparison method which compares two objects and returns a JsonPatchDocument

### ISSUE THREAD

**Issue by jmcginty** [aspnet/AspNetCore#3104]
Would you consider a pull request to implement this? 
I was thinking the API would be a static method like 

    /// <summary>
    /// Compares two objects and returns a JsonPatchDocument describing the changes
    /// </summary>
    /// <param name="original">original object</param>
    /// <param name="modified">modified object</param>
    /// <returns></returns>
    public static JsonPatchDocument CreatePatch(object original, object modified)

called like so:

     JsonPatchDocument patch = JsonPatchDocument.CreatePatch(originalObject, modifiedObject);

**Comment by jimmyheaddon** [comment]
Upvoting, as this'd really round off this library.  Currently you have to generate the JSONPatch documents with other libraries (e.g. [JsonDiffPatch](https://github.com/benjamine/jsondiffpatch)), whereas a first-class API like the suggestion above would be great.

One thing to watch out for is that Newtonsoft is used by the `Microsoft.AspNetCore.JsonPatch` library, so you can end up with JSONPatch documents that result in semantically identical objects, but the JSONPatch document itself can be different.  For example, Newtonsoft breaks ISO DateTime objects (see this [Github Issue](https://github.com/JamesNK/Newtonsoft.Json/issues/862)).  You need a test like below to spot this:

```
[TestCase("{a:\"2017-01-01T12:34:56.789Z\"}", "{a:\"2017-01-01T16:34:56.789+0400\"}", ExpectedResult = "[{\"op\":\"replace\",\"path\":\"/a\",\"value\":\"2017-01-01T12:34:56.789+00:00\"}]", TestName = "JsonPatch replace works for semantically identical ISO 8601 date/time strings where only 1 uses the zero UTC designation")]

```

**Comment by jimmyheaddon** [comment]
For reference, [it looks like someone is already working on this](https://github.com/morganabel/CSharpJsonPatchGenerator), although the author mentions they haven't checked deeply nested objects, etc.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
