### ISSUE TITLE
Antiforgery : API misleading

### ISSUE THREAD

**Issue by jchannon** [aspnet/AspNetCore#3112]
`IAntiforgery` - `Task<bool> IsRequestValidAsync(HttpContext httpContext);`

If you setup Antiforgery with header name `Foo` and on the client set this value and try a POST/PUT, all is well.

On the client then add the header again.

What you end up with is a header with that key with two values.

Agreed, not what you should do but lets look over that.

Send a request and you get:
```
System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
```

This is because https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgeryTokenStore.cs#L41 pulls out the header as `StringValues` which will have a 2 values. Then passes this to the constructor of `AntiforgeryTokenSet` whose first argument is a string. Converting a `StringValues` to `string` implicitly with more than one value will pull out the first value.  In our case the incorrect value.

Further down the stack where it takes this value and calls `IAntiforgeryTokenSerializer.Deserialize` it blows up with the exception not return an expected false.

**Comment by blowdart** [comment]
Well don't do that :) But yes, we could be clearer here.

What do you think the right thing to do would be if we encounter multiple headers? Throw an exception? Try each one?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
