### ISSUE TITLE
[Question] Diagnostics - UseExceptionHandler culture in url

### ISSUE THREAD

**Issue by joacar** [aspnet/AspNetCore#3116]
Hi,

I've written a middleware that handles localization via url if the culture is not present in the url segment. So `home/about` will be redirected to e.g `sv/home/about`. 

When adding the `ExceptionHandleMiddleware` I've a few options and I choose `UseExceptionHandler("/error/500")`.  In the method the `HttpContext.Features.Get<IExceptionHandlerPathFeature>` is always `null`, most likely to the redirect my middleware performs due to the lack of culture. How to I best solve this issue?

1. Re-write my middleware to **not** delete the related items/features/.... Maybe doing this copy is expensive and that is something I would like to avoid.
2. Add an overload to the `UseExceptionHandler` which allows me to construct the path at runtime. Perhaps `Func<HttpContext, string>` then I can resolve `IRequestCultureFeature` from context and extract the culture and create the correct path. This would be added to the options object
3. Perhaps just make `ExceptionHandlerOptions.PathString` virtual would suffice. This allows for creation of a new options instance that can take `IHttpContextProvider` from which it would be possible to get the current context instance and resolve culture.

**Edit:** The above concept would also be useful when setting `CallbackPath` in `RemoteAuthenticationOptions` and other similar cases.

Thanks

**Comment by Tratcher** [comment]
Have you considered re-ordering your middleware so the localization one is before the exception handler? I assume your localization middleware is less likely to generate exceptions.

**Comment by joacar** [comment]
Yes that would probably be the best option for this case. Reviewed my library and currently it is **not** a middleware, merely methods to handle case when routing is missing the registered identifier: `culture`. So this is currently just tied with routing. Perhaps rewrite as middleware and create extensions methods to register the necessary classes to also have working routing in MVC. Regarding the other cases, I would like an option to provide the culture as format, or by other means, just to reduce the number of redirects.  

@Tratcher Refactoring and adding the middleware won't fix the redirects thought.

**Comment by Tratcher** [comment]
Any reason you're doing redirects for culture rather than a server side url re-write?

**Comment by joacar** [comment]
No - just ignorance. My "middleware" currently does the follow

1. Check if the request url contains the culture specific placeholder.
2. If missing, invoke custom method to make a good guess. Otherwise check cookie or other registered providers. 
(**If not found add marker** <-- Maybe will be possible then since the redirect won't clear the property bag)
3. Fix url by formatting url according to options.
4. Redirect.

Step four doesn't add any value as far as I can see since the steps will be short circuit at step 1. Can url re-write suffice as last step?

**Comment by Tratcher** [comment]
It depends. If you're only trying to fix it up for routing then yes. However it has side effects for things like caching where it could cause cross contamination.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
