### ISSUE TITLE
StaticFiles that return a 404 could use more diagnostic information

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#3123]
_From @csharpfritz on May 5, 2018 16:36_

A little diagnostic information when logging a 404 for a static file would be very helpful.

Perhaps adding something like "searched in folder '/app/wwwroot/lib/WHATEVER'" would be beneficial to help debug simple configuration errors

_Copied from original issue: aspnet/KestrelHttpServer#2549_

**Comment by Tratcher** [comment]
There is a debug log:
https://github.com/aspnet/StaticFiles/blob/afdb39309506711a60aaf6ac1a3216cf73989b4c/src/Microsoft.AspNetCore.StaticFiles/StaticFileMiddleware.cs#L89
https://github.com/aspnet/StaticFiles/blob/afdb39309506711a60aaf6ac1a3216cf73989b4c/src/Microsoft.AspNetCore.StaticFiles/LoggerExtensions.cs#L47-L50

It doesn't know the directory, that's abstracted via the IFileProvider.

Also, the static file middleware doesn't return 404's, it falls through and you only get a 404 if you reach the end of the pipeline without something handling it.

**Comment by shirhatti** [comment]
Closing as this isn't actionable. We believe there is enough fidelity of information in the debug log.
