### ISSUE TITLE
Posting empty file input behaves differently in 2.0 and 2.1

### ISSUE THREAD

**Issue by chrarnoldus** [aspnet/AspNetCore#3137]
When a form is posted that has an empty file input in it, ASP.NET Core 2.0 represents the value as an `IFormFile` of 0 bytes, while 2.1 represents it as a single empty string value.

When the file input has an actual empty file, behaviour is the same (0-byte `IFormFile`).

I noticed this when trying to update an existing app. Is this an intentional change in behaviour?

# Steps to reproduce

Code: https://github.com/chrarnoldus/FileInput

* Run `dotnet run`
* Go to [localhost:5000](http://localhost:5000) in a browser (I tried Firefox 60.0 and Chrome 66.0)
* Click submit (do NOT select a file)

```C#
app.Map("/post", app2 =>
{
    app2.Run(async context =>
    {
        await context.Response.WriteAsync(
            string.Join("\n", context.Request.Form.Select(kvp => $"{kvp.Key} ({kvp.Value.Count}): '{kvp.Value}'"))
        );

        await context.Response.WriteAsync(
            string.Join("\n", context.Request.Form.Files.Select(f => $"{f.Name}: {f.Length} bytes"))
        );
    });
});

```

When the package version in the project file is set to `2.0.8`, the output is:

```
file: 0 bytes
```

which means that there are no entries in `Form`, while there is a single 0-byte entry in `Form.Files`. When the version is `2.1.0-rc1-final`, the output is:

```
file (1): ''
```

which means that there is a single entry in `Form`, with a single (empty) value.

**Comment by anurse** [comment]
This may not have been intentional, but it is that way in the 2.1 release (which is our Long-Term Support release) so we generally have to preserve that behavior.
