### ISSUE TITLE
IOptionsSnapshot is not working with non API/Web scenarios

### ISSUE THREAD

**Issue by cilerler** [aspnet/AspNetCore#3153]
It looks like `IOptionsSnapshot` with `reloadOnChange: true` set on [`HostBuilder`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostbuilder?view=aspnetcore-2.1) is not updating the options value when the **appsettings.json** content changes.

This behavior works fine on `WebHost`.  As far as my understanding `IOptionsSnapshot` gets generated as `Scoped` in `WebHost` for each call.  However this doesn't apply to `HostBuilder` since there is no outside caller exist.

We should be able to detect setting changes and I would like you to consider this issue as a feature request.  

Thanks in advance

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
So your scenario has no concept of scope?  You should just use IOptionsMonitor.CurrentValue then

**Comment by cilerler** [comment]
@HaoK Correct but I really don't think it is the best practice to split IOptions, IOptionsSnapshots, IOptionsMonitor for different kind of scenarios.  I wish we had only one IOptions service and it decides what to do based on its DI registration.

**Comment by davidfowl** [comment]
These projects have completely jagged versions of dependencies

**Comment by cilerler** [comment]
@davidfowl they should be latest now, and comment on below?

> I really don't think it is the best practice to split `IOptions`, `IOptionsSnapshots`, `IOptionsMonitor` for different kind of scenarios.  I wish we had only one `IOptions` service and it decides what to do based on its DependencyInjection registration.

**Comment by HaoK** [comment]
This behavior is by design
