### ISSUE TITLE
JsonPatch including a move doesnt update data as expected

### ISSUE THREAD

**Issue by slubowsky** [aspnet/AspNetCore#3192]
A JsonPatch that includes both a move and updating data fails to update the data as expected - presumably due to the move.
For example, after executing the following patch:
```
[{"op":"replace","path":"/myArray/0/index","value":1},{"op":"move","from":"/myArray/1","path":"/myArray/0"},
{"op":"replace","path":"/myArray/1/index","value":0}]
```
I see only the second value actually being changed. The object that was initially at index 0 remains with its original value

**Comment by slubowsky** [comment]
A more careful reading of the spec shows that operations are to be applied in order [https://tools.ietf.org/html/rfc6902#section-3](https://tools.ietf.org/html/rfc6902#section-3). So in the given example, the same entity should perhaps be updated twice, once when at position 0 then again after being pushed into position 1 after the old element at position 1 was moved to position 0. I don't see how only the object originally in position 1 being updated can be correct.

In any event, the patch as shown is incorrect for my purpose, as I really want 2 different elements updated. The patch I should be issuing is:
```
[{"op":"replace","path":"/myArray/0/index","value":1},{"op":"move","from":"/myArray/1","path":"/myArray/0"},
{"op":"replace","path":"/myArray/0/index","value":0}]
```
which does indeed work as expected updating the values of both the object originally at index 0 and the object moved there by the move.

The behavior in the first case does still seem incorrect so Ill leave the issue open.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
