### ISSUE TITLE
Azure is often not updated quick enough to run latest .Net Core updates.

### ISSUE THREAD

**Issue by DanJ210** [aspnet/AspNetCore#3243]
Usually when I create a new .Net Core project on the latest framework version using VS 2017, the app won't run on Azure. I'll get the 502.5 process failure. This happens without me touching the code at all, just using the template as is. I'll have to go into the NuGet packages and downgrade the Microsoft.AspNetCore.All to a lower version and then publishing the Azure app works and the app runs. Otherwise publishing works but the app won't run because the template version has versions that have not yet been installed on Azure. Even though when I first create the project I'm advertised to publish straight to Azure when doing so results in process failures. 

I spent a lot of time figuring out that Azure wasn't prepared for these updated versions which sucked. I'm not sure where or the best place to share this would be but to me this is a good place. Any version of aspnet Core that gets put out should be installed on Azure before being released and marketed heavily to the public. No?

**Comment by WinthorpeCross** [comment]
I'd like to echo @DanJ210 's comments.  I too wasted several hours troubleshooting the 502.5 error for the very same reason.  Surely you could delay the release of the NuGet updates until after Azure is updated?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
