### ISSUE TITLE
DataProtection AuthenticatedEncryptorDescriptorDeserializer version missmatch

### ISSUE THREAD

**Issue by oliverluethi** [aspnet/AspNetCore#3255]
Hi there...

I'm using the NugetPackages "Microsoft.AspNetCore.DataProtection 2.1.1" and "Microsoft.AspNetCore.DataProtection.Extensions 2.1.1" in a .NET Standard 2.0 library.

Initializing of the DataProtectionProvider and Protector

```c#
var destFolder = Path.Combine(System.Environment.GetEnvironmentVariable("LOCALAPPDATA"),"myKeys");
            provider = DataProtectionProvider.Create(
                new DirectoryInfo(destFolder));
            _protector = provider.CreateProtector("MyCache");
        }
```

If I try to protect a plain string `var encrypted = _protector.Protect(json);` I get the following message:

> The type 'Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' is not assignable to 'Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.IAuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Maybe I'm doing something wrong here?

**Comment by Tratcher** [comment]
Your dependencies are misaligned, you're trying to reference 1.0.2.0 and 2.1.1.0 of the same package.

**Comment by oliverluethi** [comment]
@Tratcher Yes, I see this. After some more investigation I saw that the .NET Standard Library works fine with a clean ConsoleApp project, but fails with an AzureFunctions project. I don't see any reference of a DataProtection library in the AzureFunctions project, but it seems there is something which causes this problem.

**Comment by Eilon** [comment]
@oliverluethi - were you able to resolve the issue? If not, please upload a repro project to GitHub (in a new repo, or a ZIP) so that we can investigate. Thanks!

**Comment by oliverluethi** [comment]
@Eilon No, error still exists. I'll upload a sample project shortly, Thanks!

**Comment by oliverluethi** [comment]
@Eilon Here is a sample project, thanks for your help!
[FunctionApp1.zip](https://github.com/aspnet/Home/files/2205378/FunctionApp1.zip)

**Comment by natemcmaster** [comment]
To solve this, we need a fix to https://github.com/aspnet/DataProtection/blob/master/src/Microsoft.AspNetCore.DataProtection/TypeForwardingActivator.cs which understands that multiple versions of an assembly may exist in a .NET app, and has a way to determine correctly which one should be used.

The only simple solution I can think of right now is one that keeps a list of well-known data protection assemblies, and attempts to resolve types against those assemblies before falling back to `Type.GetType`.

**Comment by muratg** [comment]
@pakrym if we can't fit the fix in preview3, we can punt this.

**Comment by muratg** [comment]
We won't be fixing this in DataProtection in 2.2

Recommendation is to move to Azure Functions V2. (Or if you have to work on V1, consider moving to .NET Core.)
