### ISSUE TITLE
Websocket disable ping

### ISSUE THREAD

**Issue by sneltyn** [aspnet/AspNetCore#3267]
How to disable ping for **Websocket**. Used by http.sys without IIS integration.

I tried to change the timeout of the keep-alive:

```csharp
var webSocketOptions = new WebSocketOptions()
{
  KeepAliveInterval = TimeSpan.FromSeconds(10)
};

app.UseWebSockets(webSocketOptions);
```

But for some reason this option is ignored and I get a **ping** every 120 seconds (the default value).

**SDK for .NET Core**
  Version: 2.1.301
  Commit: 59524873d6

**The runtime:**
  OS Name: Windows
  OS Version: 10.0.17134
  OS Platform: Windows
  RID: win10-x64

**Host (useful for support):**
   Version: 2.1.1
   Commit: 6985b9f684

**Comment by Tratcher** [comment]
It can be disabled using Timeout.InfiniteTimeSpan.
https://github.com/dotnet/corefx/blob/6182c9c53f3931461b228fed963e44c0c16d5c45/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L169

Though your example isn't trying to disable it, but to make it happen more frequently?

**Comment by sneltyn** [comment]
@Tratcher, all right I would have applied `Timespan.Infinite`, but it does not work. The example shows that after setting 10 s, the keep-alive remains 120 s

**Comment by anurse** [comment]
Can you provide a sample project that reproduces the issue?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
