### ISSUE TITLE
Update Ajax CDN resources related to core ASP .NET project client dependencies

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/AspNetCore#3283]
There are no related repo, it seems to be the best place.

There is an ASP MVC template update pending here:
https://github.com/aspnet/templating/pull/595
for moving web templates dependencies and design forward. 
There is a problem that version of main library used as dependency (code and design) released by library authors is current at 4.1.1:
https://www.bootstrapcdn.com/
while the version of the same library hosted by MS at Ajax CDN is still locked on the 4.0.0 (the very first version from 4.*)
https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#Bootstrap_Releases_on_the_CDN_14

How can we trigger some update on MS CDN?

Thanks!

**Comment by Eilon** [comment]
@blowdart where would we track adding new versions of libraries to the CDNs? Generally we include in the ASP.NET CDN the libraries that we use in our templates, so if we update our templates to use new libraries, we'd want to add them to the CDN as well.

cc @ryanbrandenburg @mkArtakMSFT

**Comment by Eilon** [comment]
I talked to @blowdart and it appears that Chris Sfanos is the right contact for when we settle on new library versions.

**Comment by mkArtakMSFT** [comment]
Closing as this is not something we support any more:
![image](https://user-images.githubusercontent.com/34246760/66853551-672f4600-ef34-11e9-8c0c-7b7184a2eb3e.png)
Source: https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview
