### ISSUE TITLE
.Net Core template based on BS4 are missing core dependency on MS Ajax CDN

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/AspNetCore#3285]
The ASP.NET templating team is working on update of client/design dependencies to BS4
https://github.com/aspnet/templating/pull/595

There is a problem with update in my opinion:
- the template authors use Ajax CDN for production (hosted) dependencies
- the Ajax CDN is missing core Bootstrap 4 dependency required for tooltips/pop-overs/modals, etc

e.g. see comment on this non-merged, staled PR:
https://github.com/aspnet/templating/pull/476#issue-181709995

> also upgrade libs to latest version. used cdnjs instead of the MS cdn since popper.js is missing (bs4 dependency) and because MS cdn doesn't show integrated strings.

If possible, can someone add that core dependency to Ajax CDN resources (and later update docs)?
https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#Bootstrap_Releases_on_the_CDN_14

To re-iterate issue: 
- some features of BS 4 depends on JavaScript
- if JavaScript components are to be used (think: business-line apps) the BS needs:
- jQuery, Popper.js and its own library ('bootstrap.js')

The page author can use`bootstrap.bundle.js` to use Popper.js bundled, but that is just an option (and she or he needs to know what is the difference between `bootstrap.js` and `bootstrap.bundle.js`)

Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

**Comment by peterblazejewicz** [comment]
It seems to be fixed in the CDN resource itself already, this issue was never updated properly.
Thanks!
