### ISSUE TITLE
IFormFile bug

### ISSUE THREAD

**Issue by karelz** [aspnet/AspNetCore#3304]
_From @cristian1975 on July 5, 2018 9:21_

If you upload a excel file to a web api endpoint,  IFormFile object type from Request.Form.Files collection  has bigger size than the original excel file and if you try to open the uploaded file from the upload folder is in incorrect format. The method to upload a file is taken from .net core 2.1 documentation site:

```c#
           using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await formFile.CopyToAsync(stream);
            }
```

where fromFile is IFormFile type.
This bug is happen from .net core version 2.0.6 and above.

_Copied from original issue: dotnet/corefx#30842_

**Comment by karelz** [comment]
_From @khellang on July 5, 2018 11:16_

This issue belongs in https://github.com/aspnet/Home 😄

**Comment by Tratcher** [comment]
Asp.Net does not change the contents of uploads, it's all treated as raw bytes. One possibility is that you're not accounting for the file encoding as specified in the headers.

**Comment by Eilon** [comment]
@cristian1975 can you provide more info about your scenario?

**Comment by SiarheiHelis** [comment]
Usually, the following issue raise this kind of incorrect behavior:
A lot of open-source Middleware's implementations (and articles with samples) use UTF8 encoding for binary content to log requests. It cause incorrect encoding for binary content for future processing. First of all, please review that your Middleware don't change body content

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
