### ISSUE TITLE
CORS for CrossDomain is not working

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#3308]
_From @skkanagaraj on June 12, 2018 11:6_

 OPTIONS https://xyz.co.uk/front/api/Eze/GetEcPrt?_=1528800677059 401 (Unauthorized)

1. Automatically Converts 'Get' to 'Option' request.
2. Failed to load.  https://xyz.co.uk/front/api/Eze/GetEcPrt?_=1528800677059: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://liontrust.sharepoint.com' is therefore not allowed access. The response had HTTP status code 401.

_Copied from original issue: aspnet/Proxy#95_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @skkanagaraj.
Are you still facing this issue? If so, can you please share a repro proejct so we can investigate this further?

**Comment by pranavkm** [comment]
@skkanagaraj please feel free to reopen the issue once you have a repro project
