### ISSUE TITLE
Obsolete `ResourceManagerWithCultureStringLocalizer` and `WithCulture` interface member

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#3324]
The [ResourceManagerWithCultureStringLocalizer](https://github.com/aspnet/Localization/blob/43b974482c7b703c92085c6f68b3b23d8fe32720/src/Microsoft.Extensions.Localization/ResourceManagerWithCultureStringLocalizer.cs#L18) and [WithCulture](https://github.com/aspnet/Localization/blob/master/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L154-L170) interface member are often sources of confusion for users of Localization, especially if they want to create their own `IStringLocalizer` implementation. These items give the user the impression that we expect an `IStringLocalizer` instance to be "per-language, per-resource", when actually they should only be "per-resource", with the language searched for determined by the `CultureInfo.CurrentUICulture` at execution time.

Neither of these has any usage that I was able to find with a cursory search, and it's difficult for me to imagine when they would be the correct option, so let's just get rid of them in 3.0.

**Comment by hishamco** [comment]
Or we can move `WithCulture` as extension method as I mentioned [here](https://github.com/aspnet/Home/issues/3289)

**Comment by hishamco** [comment]
@ryanbrandenburg can we mark them as `Obsolete` in release 2.2 branch and removing them in the master branch?

**Comment by ryanbrandenburg** [comment]
Yeah, marking them as Obsolete would probably be step one, but this is just a suggestion on my part at this point. We'll have to talk it over with @mkArtakMSFT and probably @DamianEdwards to decide if they want this and what the plan would be first.

**Comment by hishamco** [comment]
Sound good .. hope you check my earlier points in the issue that I referenced with them too ..

**Comment by hishamco** [comment]
Another issue in `WithCulture` is if we passed a `null` it will create another instance with the same culture!!

**Comment by hishamco** [comment]
@ryanbrandenburg any updates on this?

**Comment by hishamco** [comment]
@mkArtakMSFT any update on this? Can we mark the types as `Obsolete`? or shall we make a PR for 3.0.0?
