### ISSUE TITLE
Cannot capture 405 error with CORS - CORE API

### ISSUE THREAD

**Issue by avechuche** [aspnet/AspNetCore#3325]
Hi, I am trying to get a 405 method not allowed error but it is impossible and I do not know why. I have the following configuration.

```
//Startup.cs
servicesCollection.AddCors(x =>
{
    x.AddPolicy(CORS.AllowPutMethod,
        policyBuilder =>
        {
            policyBuilder.WithOrigins("http://localhost:4200")
                .WithMethods(HttpMethods.Put).AllowAnyHeader();
        });
    x.AddPolicy(CORS.AllowPostMethod,
        policyBuilder =>
        {
            policyBuilder.WithOrigins("http://localhost:4200")
                .WithMethods(HttpMethods.Post).AllowAnyHeader();
        });
});

public static class CORS
{
    public const string AllowPutMethod = nameof(AllowPutMethod);

    public const string AllowPostMethod = nameof(AllowPostMethod);
}

[ApiController]
[Route("api/[controller]")]
public class UserController : ControllerBase
{
    // PUT: api/User/5
    [HttpPut("{id}")]
    [EnableCors(CORS.AllowPostMethod)]
    public void Put(int id, UserDTO currentUser)
    {
    }

}
```
My intention is that this method only accepts a PUT request, to which I add [EnableCors (CORS.AllowPostMethod)] to force an error, but this does not generate any errors, it works perfectly, but if I comment that part // [EnableCors (CORS .AllowPostMethod)] method does not work and returns error 500. Its a ASP CORE bug or or i am the bug?

**Comment by Tratcher** [comment]
The 500 implies a server side exception. What's in your logs?

**Comment by avechuche** [comment]
@Tratcher Hi Tratcher, excuse me, I am forcing the 500 error with throw new Exception (). Pretend that does not happen. The only problem here is that EnableCors does not work correctly.

**Comment by pranavkm** [comment]
CORS does not generate errors - it's driven by the presence or absence of CORS specific headers that the browser can use to determine if a XHR or fetch request can be accessed by the client.  The `HttpPut` method constraint that you have should generate 404s (when using 2.1, or 405 when using endpoint routing that is being added in 2.2).

**Comment by pranavkm** [comment]
@avechuche feel free to reopen if you have further questions.
