### ISSUE TITLE
CORS did not add valid Origins to Response if Method is not Allowed

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/AspNetCore#3327]
I have configured CORS like below:
```
services.AddCors(x =>
            {
                x.AddPolicy(CORS.AllowPostMethod,
                    policyBuilder =>
                    {
                        policyBuilder
                            .WithOrigins("https://localhost:44326")
                            .WithMethods(HttpMethods.Post)
                            .AllowAnyHeader();
                    });
            });
```
And use it like this:   
```
[HttpPut("{id}")]
        [EnableCors(CORS.AllowPostMethod)] 
        public void Put(int id)
        {
        }
```
If I send request like this:
```
$.ajax({
    url: "https://localhost:44329/api/User/12",
    type: "PUT",
});
```
It will throw error below instead of "Method PUT is not allowed by Access-Control-Allow-Methods in preflight response".

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:44326' is therefore not allowed access.

After checking the source code [EvaluatePreflightRequest](https://github.com/aspnet/CORS/blob/8e4d3aacb3153f2a1338e228f0ea096e242d746a/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsService.cs#L111). It did not add the valid `Origin` to `CorsResult `.

Should the `EvaluatePreflightRequest` like below?

```
                 public virtual void EvaluatePreflightRequest(HttpContext context, CorsPolicy policy, ref CorsResult result)
        {
            var origin = context.Request.Headers[CorsConstants.Origin];
            if (!IsOriginAllowed(policy, origin))
            {
                return;
            }
            result.AllowedOrigin = origin;

            var accessControlRequestMethod = context.Request.Headers[CorsConstants.AccessControlRequestMethod];
            if (StringValues.IsNullOrEmpty(accessControlRequestMethod))
            {
                return;
            }

            var requestHeaders =
                context.Request.Headers.GetCommaSeparatedValues(CorsConstants.AccessControlRequestHeaders);

            if (!policy.AllowAnyMethod)
            {
                var found = false;
                for (var i = 0; i < policy.Methods.Count; i++)
                {
                    var method = policy.Methods[i];
                    result.AllowedMethods.Add(method);
                    if (string.Equals(method, accessControlRequestMethod, StringComparison.OrdinalIgnoreCase))
                    {
                        found = true;
                        break;
                    }
                }

                if (!found)
                {
                    _logger?.PolicyFailure();
                    _logger?.AccessControlMethodNotAllowed(accessControlRequestMethod);
                    return;
                }
            }
            
            if (!policy.AllowAnyHeader &&
                requestHeaders != null)
            {
                foreach (var requestHeader in requestHeaders)
                {
                    if (!CorsConstants.SimpleRequestHeaders.Contains(requestHeader, StringComparer.OrdinalIgnoreCase) &&
                                                  !policy.Headers.Contains(requestHeader, StringComparer.OrdinalIgnoreCase))
                    {
                        _logger?.PolicyFailure();
                        _logger?.RequestHeaderNotAllowed(requestHeader);
                        return;
                    }
                }
            }

            AddOriginToResult(origin, policy, result);
            result.SupportsCredentials = policy.SupportsCredentials;
            result.PreflightMaxAge = policy.PreflightMaxAge;
            result.AllowedMethods.Add(accessControlRequestMethod);
            AddHeaderValues(result.AllowedHeaders, requestHeaders);
            _logger?.PolicySuccess();
        }
```

**Comment by FlyingWraptor** [comment]
This has to do with issue #3323.

Your fix will not resolve the issue (Tested when debugging own fix).
My comment on issue #3323 shows why it does not return any value as you are using `HttpMethods.Post` (non prefetch simple request) for Put requests (Requires OPTIONS). Try changing it to `.WithMethods("PUT")`. And `[EnableCors(methods: "PUT")]`

And it'll work just fine.

**Comment by pranavkm** [comment]
cc @Eilon \ @javiercn 

We should consider simplifying the CORS middleware. The [spec](https://fetch.spec.whatwg.org/#http-responses) does allow for not returning any of these headers like the middleware does now, but I'm not entirely sure why it needs to be doing any work. Going by the specs, once a policy is selected, this is what needs to be done:

* For a CORS preflight requests, return

1) `Access-Control-Allow-Origin`
2) `Access-Control-Allow-Credentials`
3) `Access-Control-Allow-Methods`
4) `Access-Control-Allow-Headers`
5) `Access-Control-Max-Age`

* For subsequent CORS requests,
1) `Access-Control-Allow-Origin`
2) `Access-Control-Allow-Credentials`
3) `Access-Control-Expose-Headers`

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/CORS/pull/179. Outside of the allowed origin check, `CorsService` no longer uses allowed headers or allowed methods to determine if a policy succeeded.
