### ISSUE TITLE
Not allowing to post huge data in AJAX call in ASP .net core 2

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#3328]
_From @SattarMomin on May 16, 2018 9:52_

# Issue Title

Not allowing to post huge data in AJAX call in ASP .net core 2

# General

I have created 1 page in ASP .net core 2 MVC. Now I am posting data of form by AJAX call and calling Controller Action. But when data is huge on page it is giving error "Failed to load resource: the server responded with a status of 500 (Internal Server Error)", same is working fine when data is less.

I am sure issue is due to exceeding data size limit. 

I have tried '[DisableRequestSizeLimit]' at action level and .UseKestrel(options => { options.Limits.MaxRequestBodySize = null; }) at global level, but giving same error.

Kindly suggest

_Copied from original issue: dotnet/core#1566_

**Comment by Eilon** [comment]
Hi @SattarMomin , this is likely an issue with *form size* limits and perhaps not Kestrel's own limits.

Here's some more info on request size limits in ASP.NET Core: https://github.com/aspnet/Announcements/issues/267

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
