### ISSUE TITLE
Session OnStart and Session OnEnd

### ISSUE THREAD

**Issue by huazhenhz** [aspnet/AspNetCore#3331]
To reopen the issue #3025 
https://github.com/aspnet/Home/issues/3025

I hope Session can have "Session_Start" and "Session_End" event mechanism.

If the mechanism is the same as Spring Session in Java Web, that's preferred.

Spring Session has the similiar events such as "SessionCreatedEvent" and "SessionDestroyedEvent" ("SessionDestroyedEvent" includes "SessionDeletedEvent" and "SessionExpiredEvent".).

The relevant web sites about Spring Session below:

SessionCreatedEvent:
https://docs.spring.io/spring-session/docs/1.3.0.RELEASE/reference/html5/#api-redisoperationssessionrepository-sessioncreatedevent

SessionDestroyedEvent:
https://docs.spring.io/spring-session/docs/1.3.0.RELEASE/reference/html5/#api-redisoperationssessionrepository-sessiondestroyedevent

I think the mechanism is important to .NET developers, and it can make ASP.NET Core more perfect.

So, "Session_Start" and "Session_End" events should be provided continuously in ASP.NET Core.

Thanks!

**Comment by hishamco** [comment]
I opened the same issue as the early days of ASP.NET Core https://github.com/aspnet/Session/issues/20

**Comment by huazhenhz** [comment]
https://github.com/aspnet/Session/issues/20
It was closed last month.

**Comment by huazhenhz** [comment]
2 months passed, and no actions yet.

**Comment by shirhatti** [comment]
As alluded in https://github.com/aspnet/Session/issues/20, we aren't doing this
