### ISSUE TITLE
Internal redirect for UseStatusCodePages

### ISSUE THREAD

**Issue by ygoe** [aspnet/AspNetCore#3332]
The [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.1) explains how to use `app.UseStatusCodePages();` to show some content when a controller action returns `NotFound()` or something. This only shows very basic plain text. I could also redirect the user to another URL that has more content like /Error/404. But that would redirect the user away from the originating URL that caused the error. Redirecting the user away from the actual error page to a static page that always shows an error message is a bad thing. The user will not be able to verify the URL and probably find the problem. Also, reloading the page will not bring back the expected content when the error has been resolved meanwhile. Reloading the /Error/404 page will always show the error even if it doesn't exist anymore.

So what I need is an internal redirect to a more rich page that fits my site design, but doesn't change the visible URL.

How can I do that?

**Comment by Tratcher** [comment]
You want UseStatusCodePagesWithReExecute. The description on that page is confusing (@guardrex), read this one:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.statuscodepagesextensions.usestatuscodepageswithreexecute?view=aspnetcore-2.1

**Comment by ygoe** [comment]
Thank you, that works. The parameters of that method are not documented yet. But I could add a controller action and view that properly handles such errors.

**Comment by mkArtakMSFT** [comment]
@ygoe, feel free to send us a PR for parameter documentation. We'll happily consider it.
