### ISSUE TITLE
Move localization builder APIs into an extension methods

### ISSUE THREAD

**Issue by hishamco** [aspnet/AspNetCore#3335]
After revising the localization builder APIs that we introduce in `2.1`, it would be nice to move those into an extensions methods, because they rely on the existing members

**Comment by hishamco** [comment]
This is add possibility to add other extension methods like what I suggest in #3336

**Comment by hishamco** [comment]
@rynowak is this fine to send a PR for it?

**Comment by mkArtakMSFT** [comment]
@hishamco, what are you trying to do? Is this only to support the other issue?

**Comment by mkArtakMSFT** [comment]
Also, please add more details regarding which specific APIs you're referring to and from where to where you suggest them to be moved.

**Comment by hishamco** [comment]
I mention it in the title, all the builder APIs, including:
1. `AddSupportedCultures(params string[] cultures)`
2. `AddSupportedUICultures(params string[] uiCultures)`
3. `SetDefaultCulture`

All these APIs that we added in 2.2 are simplify the building of `RequestLocalizationOptions`, nothing but mainly they rely on original properties of that class, so it would be nice to move those to an extensions methods, so no breaking-changes required here

**Comment by hishamco** [comment]
If the proposal is fine, I can send a PR for it

**Comment by hishamco** [comment]
Why it's be a breaking change while these will be moved to the same assembly?!! if there's a guidelines about what binary changes mean in ASP.NET Core, please refer it to me.

BTW if it's breaking changes as you said, we can suggest this for 3.0.0

**Comment by mkArtakMSFT** [comment]
@hishamco, it's still unclear what the value of the proposed change is, other than code organization.

**Comment by hishamco** [comment]
@mkArtakMSFT Even if it's code organization, what's block us to add this in 3.0.0?

**Comment by mkArtakMSFT** [comment]
Well, the rule of thumb is to avoid breaking changes unless it's really required. This is not the case.
Sorry @hishamco, I'm going to close this now. I understand it would be nice, but there is not enough value to afford a breaking change.

**Comment by hishamco** [comment]
No problem @mkArtakMSFT but still it's not clear to me, 3.0.0 it will contain many breaking change, why we will not consider any changes for code organization, there's some places in localization repo that need to be organized
