### ISSUE TITLE
Adding AddRequestCultureProvider as extension method

### ISSUE THREAD

**Issue by hishamco** [aspnet/AspNetCore#3336]
For all that are familiar with localization, adding new culture provider is something confusing, because the developer expect that the newly added provider is winner provider, but it's not!!

Have a look to [this](https://github.com/aspnet/Localization/blob/master/samples/LocalizationSample/Startup.cs#L34) we should use `Insert` instead of `Add`, to let our culture provider wins over the other predefined culture providers.

Using this
```csharp
options.AddRequestCultureProvider(new CustomRequestCultureProvider(async context =>
{

}));
```

is slightly better than
```csharp
options.RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(async context =>
{

}));
```

/cc @ryanbrandenburg

**Comment by hishamco** [comment]
@rynowak is this fine to send a PR for it?

**Comment by mkArtakMSFT** [comment]
@hishamco, yes, feel free to send us a PR.
