### ISSUE TITLE
System.ArgumentOutOfRangeException: Count cannot be less than zero. Parameter name: count

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#3357]
_From @nagarjunacts on July 25, 2018 13:8_

My app hosted in azure had lot of failure on secondary instance. When investigating the app logs we had x number of requests returning 500 and no corresponding exception in application insights. The ones that did made to server returned this error tagged to operation_Id.

> System.ArgumentOutOfRangeException: Count cannot be less than zero.
> Parameter name: count
>    at System.String.CopyTo(Int32 sourceIndex, Char[] destination, Int32 destinationIndex, Int32 count)
>    at System.IO.StreamWriter.Write(String value)
>    at Microsoft.AspNetCore.Hosting.Views.ErrorPage.<ExecuteAsync>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Extensions.RazorViews.BaseView.<ExecuteAsync>d__29.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

I am not sure if this is an issue, could anyone tell me how to solve this from happening. THis happens intermittently and i believe this brings the app down.

Extra information
```
{
   "parsedStack":[
      {
         "method":"System.String.CopyTo",
         "assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
         "level":0,
         "line":0
      },
      {
         "method":"System.IO.StreamWriter.Write",
         "assembly":"System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
         "level":1,
         "line":0
      },
      {
         "method":"Microsoft.AspNetCore.Hosting.Views.ErrorPage+<ExecuteAsync>d__6.MoveNext",
         "assembly":"Microsoft.AspNetCore.Hosting, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
         "level":2,
         "line":0
      },
      {
         "method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
         "assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
         "level":3,
         "line":0
      },
      {
         "method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
         "assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
         "level":4,
         "line":0
      },
      {
         "method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
         "assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
         "level":5,
         "line":0
      },
      {
         "method":"Microsoft.Extensions.RazorViews.BaseView+<ExecuteAsync>d__29.MoveNext",
         "assembly":"Microsoft.AspNetCore.Hosting, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
         "level":6,
         "line":0
      },
      {
         "method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
         "assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
         "level":7,
         "line":0
      },
      {
         "method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
         "assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
         "level":8,
         "line":0
      },
      {
         "method":"Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1+<ProcessRequestsAsync>d__2.MoveNext",
         "assembly":"Microsoft.AspNetCore.Server.Kestrel.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60",
         "level":9,
         "line":0
      }
   ],
   "outerId":"0",
   "message":"Connection id \"0HLFGA416MUIK\", Request id \"0HLFGA416MUIK:00000313\": An unhandled exception was thrown by the application.",
   "type":"System.ArgumentOutOfRangeException",
   "id":"28060465",
   "severityLevel":"Error"
}
```

Thanks
 

_Copied from original issue: aspnet/KestrelHttpServer#2753_

**Comment by Tratcher** [comment]
_From @Eilon on July 25, 2018 17:53_

I wonder if maybe this is really an issue with the diagnostics page?

**Comment by pacojones** [comment]
Can anyone on earth explain why this was closed without any explanation?!?

**Comment by Eilon** [comment]
@pacojones - this issue still open.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pacojones.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
@nagarjunacts or @pacojones does this issue occur with more recent releases such as 2.0.4, 2.1.3 or 2.2.0-preview3-35497?

What are the failing project's exact dependencies? Ideally, please provide us with a minimal repro project that illustrates the problem -- preferably hosted in a GitHub repo.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
