### ISSUE TITLE
[Discussion] CorsMiddleware must be explicitly configured to specify all allowed headers

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#3376]
In versions of ASP.NET Core 2.1.0 and earlier, the CorsMiddleware always allowed certain headers in the `Access-Control-Request-Headers` to be sent regardless of the values configured in `CorsPolicy.Headers`. This list of headers includes:

* `Accept`
* `Accept-Language`
* `Content-Language`
* `Origin`

For instance, consider an application configured as follows:

```C#
app.UseCors(policy => policy.WithHeaders("Cache-Control"));
```

In 2.1 and earlier, the CORS middleware would respond successfully to a preflight request with the following request header:

`Access-Control-Request-Headers: Cache-Control, Content-Language`

For 2.2.0, the CORS middleware would no longer treat this as a policy match. The server must explicitly configure policy to allow the `Content-Language` header:

```C#
app.UseCors(policy => policy.WithHeaders("Cache-Control", "Content-Language"));
```

For more information on CORS, please refer to [the documentation](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.1).

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
