### ISSUE TITLE
Migrate from ASP.NET Core 2.0 to 2.1- Request to Web API failed(503-Service Unavailable )

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#3381]
_From @280919911 on August 1, 2018 16:33_

I have changed target framework 2.1 and also replaced the packages Microsoft.AspNetCore.All to Microsoft.AspNetCore.App.

On Web API project- I have set environment variable and enabled SSL from the project property
I am able to run the Web project but while calling Web API from web project 
I'm getting following error
Response status code does not indicate success: 503 (Service Unavailable).

_Copied from original issue: dotnet/core#1830_

**Comment by Eilon** [comment]
_From @joshfree on August 1, 2018 20:21_

@Eilon

**Comment by Eilon** [comment]
@280919911 do you have steps to reproduce this issue? Can you upload the app to a GitHub repo? Also, can you show any log info from the Event Log or other locations?

**Comment by 280919911** [comment]
@Eilon  Event log shows following exception :The Open Procedure for service "ASP.NET_64_2.0.50727" in DLL "C:\Windows\Microsoft.NET\Framework64\v2.0.50727\aspnet_perf.dll" failed. Performance data for this service will not be available. The first four bytes (DWORD) of the Data section contains the error code.

**Comment by Eilon** [comment]
@280919911 unfortunately that does not seem related. That is from ASP.NET 4.x and doesn't seem like a severe problem, so it's not likely the cause.

**Comment by Eilon** [comment]
@shirhatti - do we have guidance on how to diagnose 503 errors?

**Comment by shirhatti** [comment]
We have docs for diagnosing app start errors at https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1

**Comment by shirhatti** [comment]
@280919911 The 503 error you're observing sounds like an Http.Sys error.

Are you using IIS or HttpSysServer?

**Comment by 280919911** [comment]
I'm using IIS

**Comment by shirhatti** [comment]
@pan-wang Can you weigh in here?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
