### ISSUE TITLE
Test failure: ExecuteReader_honors_CommandTimeout

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#3393]
This test [fails](http://aspnetci/viewLog.html?buildId=525066&buildTypeId=XPlat_Windows_Win7_Universe) occasionally with the following error:
```
Assert.InRange() Failure
Range:  (1000 - 1999)
Actual: 2995
   at Microsoft.Data.Sqlite.SqliteCommandTest.ExecuteReader_honors_CommandTimeout() in /_/test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs:line 863
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
@ajcvickers this looks like an EF area, please assign someone to confirm that it's resolved.

**Comment by Eilon** [comment]
cc @bricelam FYI

**Comment by Eilon** [comment]
Closing because this is ancient.
