### ISSUE TITLE
After building from source, how to create a project using my build

### ISSUE THREAD

**Issue by willcoughlin** [aspnet/AspNetCore#3401]
#### Background
My machine runs Windows 10 and I have both Visual Studio 2017 and VS Code installed, along with an official release of .NET Core SDK.

#### Steps Taken
I have succeeded in building after following the [instructions ](https://github.com/aspnet/Home/wiki/Building-from-source)on the Wiki regarding building from source. I've updated my PATH, and all that, and made sure `C:\Program Files\dotnet` was removed from my system PATH.

#### Question
I am having trouble figuring out where to go from here. How can I create a new project using this custom build?

I would suggest adding to the Wiki a guide on how to do this.

**Comment by natemcmaster** [comment]
Depends what you are trying to do. Which repo did you compile and what are you trying to do with your custom build?

**Comment by willcoughlin** [comment]
I built the MVC repository and am attempting to create an ASP.NET Web Application.

**Comment by natemcmaster** [comment]
A few more questions. The answer really depends, so just want to make sure we're on the same page. Are you are trying to use a build of MVC that has some custom changes you made? If so, which branch did you base your changes on? Are you trying to get changes made by someone on our team, but that we haven't released yet? Or are you just trying to create an ASP.NET Web Application, in general?

**Comment by willcoughlin** [comment]
I have built with custom changes I have made, based on the release/2.2 branch. Now, I am trying to create the web application with that custom build.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
