### ISSUE TITLE
Asp.net Core not Collecting Garbage (acornies)

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#3411]
Copied from https://github.com/aspnet/Home/issues/1976

_@acornies commented on Jan 13_

It looks like I have a similar issue in our production service (20-100 req/s) using a combination of:
- ASP.NET Core 2.0.4
- ServiceStack.Core 1.0.44
- SkiaSharp 1.59.2
- Docker v17.09.0-ce, build afdb6d4 on Ubuntu 16.04 x64
- x4 servers @ 40 CPUs, 128 GB memory
- Server GC is true
- each Docker container is set to 12k (mhz) cpu shares, 8GB ram

The application has a front-end web server and worker (shown respectively in the graphs below).

web server (last 6h)
<img width="821" alt="screen shot 2018-01-13 at 1 06 24 pm" src="https://user-images.githubusercontent.com/2882297/34908819-33cf8f4a-f864-11e7-9ee6-9cd32b0162ee.png">

worker (last 6h)
<img width="827" alt="screen shot 2018-01-13 at 1 07 55 pm" src="https://user-images.githubusercontent.com/2882297/34908829-72eaf318-f864-11e7-9262-aca41d966eff.png">

They both make use of large byte arrays because the service is acting as an object storage proxy, and consequently puts objects in the LOH. My question is, is this a known limitation of .NET Core at the moment? It seems as though the LOH in never fully cleaned up or fragmented.

Having said that, SOH seems to be working fine, as typical web api objects are cleaned up. Any suggestions? Is there a problem with my setup? I've analyzed the code and can't find any glaring memory leaks, and I'm not using anything special outside of ServiceStack library.

**Comment by sebastienros** [comment]
@acornies

Are you still having issues with your scenarios? Have you tried to pool the objects you are creating to prevent LOH contention?

**Comment by acornies** [comment]
Unfortunately, I've moved companies since posting this and can't comment on this particular application in it's current state.
However, I did try to use object pooling, as well as converting to steams to no avail (at the time). Is it normal to have to do "special handling" for large arrays/objects?

**Comment by acornies** [comment]
@Izraphil Is this still an issue for this application?

**Comment by Izraphil** [comment]
It's working a lot better now: 
![image](https://user-images.githubusercontent.com/17456505/44408994-82b8df80-a52f-11e8-896c-79a116d9cda3.png)

**Comment by acornies** [comment]
@Izraphil can you elaborate? Was ASP.NET Core upgraded at all? Looks like it's still OOMing which is not what you want.

**Comment by sebastienros** [comment]
What is the 100% representing on these graphs?

As for an old question you asked, the LOH gets cleaned completely on my tests.

@Izraphil what are the changes between the two snapshots?
