### ISSUE TITLE
QueryCollection Is Not Case Sensitive

### ISSUE THREAD

**Issue by thefringeninja** [aspnet/AspNetCore#3450]
According to [RFC3986](https://tools.ietf.org/html/rfc3986#section-6.2.2.1), everything in a URI except the host and scheme should be case-sensitive. However the current implementation [is case insensitive](https://github.com/aspnet/HttpAbstractions/blob/8b3c308c/src/Microsoft.AspNetCore.WebUtilities/KeyValueAccumulator.cs#L19), except [when there is no query string](https://github.com/aspnet/HttpAbstractions/blob/e854d3a/src/Microsoft.AspNetCore.WebUtilities/QueryHelpers.cs#L116). Personally I think the best choice is to make it configurable, defaulting to the current behavior as not to break anyone.

**Comment by thefringeninja** [comment]
Sorry but that seems like an odd choice given that it's not what the spec says. For my particular issue it's about maximizing cache hits. aspnet core may think that `?a=1&b=2` and `?A=1&B=2` are equivalent but a caching proxy will not.

In any case I was able to work around this issue.

**Comment by anurse** [comment]
As @Tratcher said, we made this choice intentionally. If you need to do case-sensitive comparisons and lookups the raw string is available in `HttpRequest.QueryString`
