### ISSUE TITLE
Improve documentation for RequestHeaders.Get(String) Method

### ISSUE THREAD

**Issue by Powerhelmsman** [aspnet/AspNetCore#3465]
This issue was created by @StevenLiekens from https://github.com/MicrosoftDocs/feedback/issues/626. 
I couldn't find the comment section for this article so consider this a comment.
Link to article:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.headers.requestheaders.get?view=aspnetcore-2.1#Microsoft_AspNetCore_Http_Headers_RequestHeaders_Get__1_System_String_

Problem:
There is no good documentation for `RequestHeaders.Get<T>(string): T`. I tried using it and thought I could substitute T with anything I want, like string. That turned out not to work.

```c#
var myHeader = requestHeaders.Get<string>("X-My-Header");
```

I found out the hard way that there is an implicit constraint on T: it needs to be a type with a static TryParse method.

```
System.NotSupportedException: 'The given type 'T' does not have a TryParse method with the required signature 'public static bool TryParse(string, out T).'
```

That should be documented.

**Comment by Eilon** [comment]
@StevenLiekens poor poor formatting 😦 . I fixed it a little bit to be a bit more readable.

**Comment by StevenLiekens** [comment]
Thanks haha

**Comment by Tratcher** [comment]
There are also a few pre-registered parsers:

https://github.com/aspnet/HttpAbstractions/blob/55ba639657370e40841c56f44b06b911ca3b57df/src/Microsoft.AspNetCore.Http.Extensions/HeaderDictionaryTypeExtensions.cs#L151-L159

**Comment by anurse** [comment]
Putting this tenatively in the queue for 3.0. It's just a matter of adding the XML doc comments to https://github.com/aspnet/HttpAbstractions/blob/55ba639657370e40841c56f44b06b911ca3b57df/src/Microsoft.AspNetCore.Http.Extensions/RequestHeaders.cs#L282 .

@Powerhelmsman if you or anyone else are interested, this could make a quick an easy contribution.
