### ISSUE TITLE
Recognition of user's language issue

### ISSUE THREAD

**Issue by Unders0n** [aspnet/AspNetCore#3472]
FIrst of all i have to tell that seems like there's an errors in sample localization project: https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/localization/sample/Localization, when trying convention resolving i found that InfoController localization not working until you place resources in Resources/StarterWeb/Controllers/…. Folder where it searching them for.

Now to my main issue: I’ve tried to add  all logic to my project from that sample project where everything’s seems working after fix I mentioned. Project is on net core 2.1 . I just copied all configuration stuff as it was. What is working: Configuring, injecting localization service to controller, finding resources. What’s not working: resolving locale is broken, setting locale in query string, setting locale in “Accept-Language” (haven’t tried cookies) – not working. Strange thing is that as result I’m always getting Russian locale – my pc is on Russian, but I’m not sending it in any place and not getting it in headers , can confirm that incoming request header is correct.
Some facts:
- redefining providers didnt help:	
    options.RequestCultureProviders.Clear();
    options.RequestCultureProviders.Insert(0, new AcceptLanguageHeaderRequestCultureProvider());

    Custom provider also seems to be ignored, I believe lambda function should be called on each request and it’s not
-	Upgrading to 2.2 not helping, downgrading to 2.0 also.
-	Different types of naming “fr”, “fr-FR” , different type of resource naming not helping.
-	no errors in _missingManifestCache, seems like no problems with files itself and resolving them
-	Tried postman and fiddler

Please tell where to investigate. Also please tell how can I get more info on which exactly locale is chosen and how it happened.	Tell if I need to provide more info.

**Comment by Eilon** [comment]
BTW I logged a Docs issue for the first item above: https://github.com/aspnet/Docs/issues/8323

**Comment by Unders0n** [comment]
@hishamco sorry, if this question addressed to me i didn't got it :(

**Comment by Unders0n** [comment]
Modified sample solution works fine - if i place all in correct folder resources/StarterWeb/controllers/InfoController.fr-FR.resx and if then i send Accept-Language = "fr-FR" it takes correct resource, also default locale is working. But in my solution all of this not working , it ignores my headers and always teking russian (wich especcially weird) localization.
I can see any difference in my setup code, here it is:
`  services.AddLocalization(options => options.ResourcesPath = "Resources");`


`var supportedCultures = new[]
            {
                new CultureInfo("en-US"),
                new CultureInfo("en-AU"),
                new CultureInfo("en-GB"),
                new CultureInfo("en"),
                new CultureInfo("es-ES"),
                new CultureInfo("es-MX"),
                new CultureInfo("es"),
                new CultureInfo("fr-FR"),
                new CultureInfo("fr"),
                new CultureInfo("ru-RU")
            };
            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("en-US"),
                // Formatting numbers, dates, etc.
                SupportedCultures = supportedCultures,
                // UI strings that we have localized.
                SupportedUICultures = supportedCultures
            });
`

my project name is AgriSync.Api, controller namespace is AgriSync.Api.Controllers, name is UserAccountController
and i have corresponding resources in folder Resources/Controllers/
UserAccountController.fr.resx, UserAccountController.ru-RU.resx, UserAccountController.en-US.resx
Im injecting localizer using ctor injection:
 ` public UserAccountController(IUserAccountService accounts, IStringLocalizer<UserAccountController> localizer)
        {
            _accounts = accounts;
            this.localizer = localizer;
        } `
and it also working fine.
But when i'm trying to send same header like in sample it just ignores it and gining me russian strings. And even default is not working (when i'm setting default to en-US and not sending a header.
I just wanted to know maybe i can debug it somehow and go step by step though this localization pipeline?
PS: sorry for formatting, i have no clue why it's not working.

**Comment by hishamco** [comment]
As I mentioned above, share a minimal repo to reproduce your issue, so we can investigate what's going on

**Comment by hishamco** [comment]
FYI @Unders0n I already updated the localization sample

**Comment by Unders0n** [comment]
@hishamco i've updated my solution and reconfigured localization part and it now working! Dunno what exactly helped but locale resolving correctly now, so issue can be closed, thanks.

**Comment by hishamco** [comment]
Happy to hear that, regarding the locale name may it differ if you app support many French cultures fr-FR, fr-CA .. etc
FYI you can use fallback option, so all the sub cultures fr-FR and fr-CA will fallback into fr.resx

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

Thanks @hishamco!
