### ISSUE TITLE
RequestHeaders - favor empty collection over null values

### ISSUE THREAD

**Issue by gimlichael** [aspnet/AspNetCore#3486]
When working with the different request headers, we have to do null-checks for now.

Please consider following the [best practises for working with collections](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections), that clearly states:

**X DO NOT return null values from collection properties or from methods returning collections. Return an empty collection or an empty array instead.**

Thanks.

**Comment by Tratcher** [comment]
Worth considering for 3.0.

**Comment by anurse** [comment]
@gimlichael Can you provide examples of the values you are getting `null` from? The headers shouldn't ever be `null` since the value is a `struct`.

**Comment by gimlichael** [comment]
@anurse i don't know why you are talking about structs all the sudden.

If you have a look at the RequestHeaders.cs (namespace: Microsoft.AspNetCore.Http.Headers, assembly: Microsoft.AspNetCore.Http.Extensions.dll) you will notice several places, where you are returning an IList of T.

As one example, lets take the property `IfNoneMatch`, then you are internally calling `return this.Headers.GetList<EntityTagHeaderValue>("If-None-Match");`

This code is located in HeaderDictionaryTypeExtensions.cs (namespace: Microsoft.AspNetCore.Http, assembly: Microsoft.AspNetCore.Http.Extensions.dll).

Looking on Github, https://github.com/aspnet/AspNetCore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/Http.Extensions/src/HeaderDictionaryTypeExtensions.cs, here is a copy-paste version of the problem:

```
        internal static IList<T> GetList<T>(this IHeaderDictionary headers, string name)
        {
            if (headers == null)
            {
                throw new ArgumentNullException(nameof(headers));
            }

            object temp;
            var values = headers[name];

            if (StringValues.IsNullOrEmpty(values))
            {
                return null;
            }

            if (KnownListParsers.TryGetValue(typeof(T), out temp))
            {
                var func = (Func<IList<string>, IList<T>>)temp;
                return func(values);
            }

            return GetListViaReflection<T>(values);
        }
```

The big problem with this code is, that in the case of a header not being present or whatever, you are returning NULL instead of returning an empty collection.

Again, Framework Design Guidelines clearly states, that collections should always be initialized and never returns null.

I hope this can help you guys fixing the (IMO) important overlook in following best practices.

Thanks.

Happy Easter :-)

**Comment by anurse** [comment]
> i don't know why you are talking about structs all the sudden.

I was referring to [the return value](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Features/src/IHeaderDictionary.cs) from `IHeaderDictionary`'s indexer. Apologies if that wasn't clear.

Thanks for the specific example to clarify the issue! I agree that we should avoid returning `null` collections!

**Comment by gimlichael** [comment]
@anurse ah, okay - my apologies back for not being entirely clear from the beginning.

I am just glad that you guys will fix it - appreciated by one developer to another.
