### ISSUE TITLE
Add Array elements with JsonPatchDocument not suporrted

### ISSUE THREAD

**Issue by SergeBerwert** [aspnet/AspNetCore#3491]
I am working on a project with Json Patch. I Tried to add an element to an array. JsonPatchDocument reported the following problem: 
Message: 

`The type 'ContactDetail[]' which is an array is not supported for JSON patch operations as it has a fixed size.
`

I Think JsonPatchDocument should be able to extend arrays in this case. It doesn’t make sense to me because Json dos do not differentiate any list types. It is impossible for a client to know if the server is capable of handling the patch or not. I know the operation is maybe slow, but I would expect that this works.

Thats What i tried:

Source Json:
```
 {
  "Id": "1",
  "Name": {
    "Title": "Prof. Dr. Dr. ind Inf",
    "FirstName": "Firstname",
    "MiddleName": "MiddleName",
    "LastName": "LastName",
    "Suffix": "Msr."
  },
  "Type": 1,
  "ContactDetails": [
    {
      "Id": "1",
      "Type": "Phone",
      "Icon": null,
      "Name": "Mobile",
      "Value": "+41 000 000000"
    },
    {
      "Id": "2",
      "Type": "EMail",
      "Icon": null,
      "Name": "Email",
      "Value": "person@email.com"
    }
  ],
  "Locations": null
}
```

Patch:
```
[
  {
    "op": "add",
    "path": "/ContactDetails/-",
    "value": {
      "Name": "NewName",
      "Type": "Mobile",
      "Value": "Add 5 Element"
    }
  }
]
```

Result:
```Message: The type 'ContactDetail[]' which is an array is not supported for json patch operations as it has a fixed size. - Operation: Microsoft.AspNetCore.JsonPatch.Operations.Operation`1[Profile] - AffectedObject Profile```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SergeBerwert.
This is not something we plan to do in the upcoming future.
