### ISSUE TITLE
React to the new StackExchange.Redis v2.0 package 

### ISSUE THREAD

**Issue by oerodriguezn** [aspnet/AspNetCore#3536]
Please update Microsoft.AspNetCore.DataProtection.Redis to use Redis.StackExchange 2.0 where there is no more a StackExchange.Redis.StrongName. 

https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes

**Comment by ghd258** [comment]
Microsoft.Extensions.Caching.Redis update   StackExchange.Redis 2.0

**Comment by blowdart** [comment]
@natemcmaster One for 2.1

**Comment by Tratcher** [comment]
Nope, it's a major break. See https://github.com/aspnet/Caching/issues/410

**Comment by Eilon** [comment]
Thanks @Tratcher I just commented on https://github.com/aspnet/Caching/issues/410#issuecomment-422876276.

We can solve this in many places by shipping a new package (with a new name) that has the new dependency and new APIs to enable it. Apps would have to opt-in to this. We could, if we wanted to, also release a 2.1 compatible package. That might be reasonable given that 2.1 is LTS.

**Comment by muratg** [comment]
We'll be creating a new package: Microsoft.AspNetCore.SignalR.StackExchange.Redis which uses that.

cc @anurse @Tratcher @DamianEdwards @Eilon

**Comment by sereeth** [comment]
Sigh.  Well, this issue has us dead in the water as Hangfire.Pro.Redis brings in StackExchange (not strongly named), and Microsoft.AspNetCore.DataProduction.Redis brings in the strong named version.  How do people get around this incredibly frustrating issue?   For the love of Pete, all we were trying to do was use the ConnectionMultiplexer.

**Comment by Eilon** [comment]
We are updating DataProtection.Redis to use the strong-named StackExchange Redis package. Once we have that published, are you still anticipating an issue?

**Comment by BrennanConroy** [comment]
This has been merged https://github.com/aspnet/DataProtection/pull/325
