### ISSUE TITLE
Not an Issue, First Post.  Want to discuss AOP in Core

### ISSUE THREAD

**Issue by FastTracOnline** [aspnet/AspNetCore#3541]
Willing to contribute to discussion and/or maturation (coding) of Aspect Oriented Programming support in .Net Core.  Not sure what repository this would work best.

40+ years developing software, coming out of my isolation :)

**Comment by Tratcher** [comment]
Something like this? https://msdn.microsoft.com/en-us/magazine/dn574804.aspx?f=255&MSPPError=-2147217396

That seems like it would work well with the Dependency Injection system. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1

**Comment by Tratcher** [comment]
Ah. Have you considered Dependency Injection as a related/alternative pattern?

**Comment by FastTracOnline** [comment]
Sorry for the delay.  Been a lot busy evangelizing .Net Core 2.0 in a large organization.  DI would be an obvious alternative, but I am looking to abstract the horizontal functionality completely outside of the vertical processing.

For example, if I have a repository pattern and my repository has a method that does a CRUD operation, to follow SOLID principles I should abstract logging and audit functions externally.  My repository knows nothing of these things being focused on what it takes to perform CRUD.  

Aspect Oriented Programming as I see it in Core would be like creating a "listener/proxy/interceptor" that knows what methods to watch across the application scope and what actions to take, like track requests/inputs/outputs (audit/log), process flow (log), exception logging, etc.  RealProxy did that.  I'm just trying to engage so that a solution to "horizontal" functionality can be determined in Core.

**Comment by Eilon** [comment]
Hi @FastTracOnline , for these more general types of topics that are not specific to ASP.NET Core, I recommend discussing with the folks at https://github.com/dotnet/core and they can involve the right set of folks.

AOP is certainly an interesting topic but within ASP.NET Core itself it's not something that can be generally enabled. Certain components in ASP.NET Core, such as MVC, have a system of filters that can be applied to actions without the action's involvement, but that's about it.
