### ISSUE TITLE
How can I get the Controller instance from HttpContext in asp.net core

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/AspNetCore#3543]
I want to get the Controller instance from HttpContext or HttpRequest in the Extension Methods like

public static returntype Getitem(this HttpRequest request,string name)
or
public static returntype Getitem(this HttpContext request,string name)

how can I get it?

**Comment by pranavkm** [comment]
The earliest you can get is in an [`ActionFilter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.actionexecutingcontext.controller?view=aspnetcore-2.1). You could stash it in the `HttpContext` 
 at this point.

**Comment by Eilon** [comment]
@kugarliyifan can you share more details about what you're trying to do?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
