### ISSUE TITLE
Minification HTML out of the box

### ISSUE THREAD

**Issue by DmitriyKulagin** [aspnet/AspNetCore#3546]
It would be good to get minification HTML functionality without the need for third-party extensions. Do you plan the implementation of this functionality in the near future?

**Comment by davidfowl** [comment]
No, we have no near term plans to do this.

**Comment by Taritsyn** [comment]
@DmitriyKulagin What you do not like in existing solutions?

**Comment by JustCallMeAD** [comment]
Being able to minify Razor files at "compile time" would be a great & a small performance increase. I know that you can minify the html at runtime but obviously this is not the best solution because of the extra processing required for every request. 

I understand that there are currently a few more important features to roll out first but hopefully it might be something that can be revisited sometime in the future :)

**Comment by Taritsyn** [comment]
> I know that you can minify the html at runtime but obviously this is not the best solution because of the extra processing required for every request.

Yes, I agree with you that minification of HTML output at runtime has some additional costs, but at the moment it is the only available solution for ASP.NET Core (even [Microsoft uses it](https://sway.com/)).

For ASP.NET Core does not yet exist any finished solutions for minification of Razor views. Unfortunately, the old time-tested solutions for minification of Razor views (such as [Meleze.Web](https://github.com/meleze/Meleze.Web), [RazorHtmlMinifier.Mvc5](https://github.com/tompazourek/RazorHtmlMinifier.Mvc5) and [Dean Hume's HTML Minifier](https://github.com/deanhume/html-minifier)) do not support .NET Core and modern Razor-syntax. Although I know of one [unfinished solution for ASP.NET Core](http://www.guardrex.com/post/razor-minification.html).

The main disadvantage of Razor views minification is that the blocks of web page into which HTML content is loaded from external sources (such as databases) remain unminified. I believe that the future behind hybrid approach, when we will use minification of Razor views together with minification of content by using HTML minifiers (for example, [WebMarkupMin](https://github.com/Taritsyn/WebMarkupMin), [NUglify](https://github.com/xoofx/NUglify), [HtmlCompressor.Core](https://github.com/joshcomley/HtmlCompressor.Core), etc.) before saving it to external storage.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
