### ISSUE TITLE
[Question] Hosting .NET Core app from normal ASP .NET Application

### ISSUE THREAD

**Issue by Chrissx** [aspnet/AspNetCore#3547]
Hi,

Is is possible to boostrap ( host ) a .NET Core Application ( ASP .NET Core WebApi mostly ) from a non-core enviroment? Boostrap from the startup but different port? Is there any drawback/problems with this approach?

**Comment by Tratcher** [comment]
You mean to host ASP.NET Core from System.Web? No.

**Comment by davidfowl** [comment]
Anything is possible without enough will power but it's completely unsupported.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
