### ISSUE TITLE
Localization works on Edge but fails on IE and Chrome using sample code

### ISSUE THREAD

**Issue by JNickVA1** [aspnet/AspNetCore#3556]
I have an ASP.NET Core Razor web app, non-MVC, that I am trying to localize using the code sample, Localization, referenced in the "Globalization and localization in ASP.NET Core" docs (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1) I needed to make a few adjustments due to the fact that I am writing a Razor web app and the sample is written for MVC.

After adding what I believe are the necessary ServiceCollection and ApplicationBuilder configurations, my app can change languages without any problem, but only in the Edge browser. When I run in both IE and Chrome, the language change fails. 

I have a repo at https://github.com/JNickVA1/CoreMasterTemplate that contains the code used. I suspect that I am either configuring the ServiceCollection or the ApplicationBuilder incorrectly or in the wrong order OR my _SelectLanguagePartial.cshtml is not browser independent. In either case I am not able to localize my app on all browsers I mentioned.

**Comment by JNickVA1** [comment]
Which app was fixed? The sample code in the documentation?

**Comment by hishamco** [comment]
Yep

**Comment by JNickVA1** [comment]
The code is in much better shape now. I have no issues in any of the browsers anymore. Thank you.

**Comment by hishamco** [comment]
So I think this should be closed

**Comment by JNickVA1** [comment]
I agree. I have tested the revised code in the master repo and it works perfectly now. Thank you.

**Comment by mkArtakMSFT** [comment]
Thanks folks!
