### ISSUE TITLE
Cookie policy and localization

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#3557]
_From @clintm90 on Friday, 21 September 2018 18:22:36_

Hello,

When the user does not had agree cookie using, it's not possible to save the localization cookie so the user cannot change the language, i think it's a little issue, or just a mindless

Thank you

_Copied from original issue: dotnet/core#1956_

**Comment by Eilon** [comment]
@clintm90 can you provide more info about what the problem is?

**Comment by Tratcher** [comment]
Ah, the loc cookie must be considered non-essential so it can't be written until the user agrees to the consent prompt. Marking the loc cookie as essential would override the cookie policy. Where is that cookie written?

**Comment by markusschaber** [comment]
I think current behaviour is correct - if the user doesn't agree to cookies, we must not use cookies, right?

**Comment by clintm90** [comment]
Yes is a very little issue, I have understand the system of essential cookies right now but for auto localisation it's a problem if the user change the language and he does not have accepted collie policy the change is not saved, I think I will had an essential value to the culture cookie but maybe it can do natively

**Comment by Eilon** [comment]
@markusschaber - some cookies are considered "essential" and I think the consent rules for those are different.

We have some info on GDPR and cookies here: https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1

**Comment by Tratcher** [comment]
Auth cookies are some of the few we mark as essential by default. The loc cookies you can opt to mark as essential in your own app.

**Comment by clintnetwork** [comment]
Yes it's the case, by default now I set this cookie as essential

**Comment by Eilon** [comment]
Closing because no further action is planned on this issue.
