### ISSUE TITLE
Should we assume Internal Server Errors can be triggered by user input?

### ISSUE THREAD

**Issue by fschmied** [aspnet/AspNetCore#3558]
I've a question regarding error handling strategy with ASP.NET Core and MVC in particular. In a system we're building, we've been following the philosophy that we should return an HTTP 4xx result code for every error that can be triggered by the user/client. HTTP 5xx error codes should only be returned if we really have a server error: resource problems (e.g., DB connection down), programming errors, etc.

Therefore, whenever an HTTP 500 Internal Server Error is rendered to a user, we log a message that causes the operations and development teams to investigate.

We've observed that sometimes ASP.NET Core and MVC infrastructure will throw exceptions in situations that can be causes by the user, e.g., https://github.com/aspnet/Mvc/issues/5631.

While that issue is going to be fixed anyway, I'm wondering if in general we can assume that ASP.NET Core and MVC will not throw exceptions for specific inputs, e.g., malformed requests. Or should we assume that user input can result in unhandled exceptions while processing the request?

Specifically, @Tratcher said in https://github.com/aspnet/Mvc/issues/5631#issuecomment-419794212 that

>[...] a 5xx response does not qualify as a server crash, the server is still operating fine, only the request was rejected. 4xx just means we understood what was wrong with the request and decided it was worth the effort to give you a more specific response. These only get added for common errors where it's obvious that the client was at fault and how.

Is this the indeed general ASP.NET Core policy? If so, we need to redefine our operations strategy, we don't want to by design raise an alert every time someone crafts a malformed request...

**Comment by Tratcher** [comment]
Indeed, you must understand the cause of an error to return a 4xx response. The server can do this when parsing the initial request headers as it's clear something is wrong with the message. However there are some errors that can't be raised until the app is processing the request and body. Unfortunately exceptions are sometimes used to communicate this and it's up to the app to catch them and decide if a 4xx is appropriate. Errors in antiforgery are one example. Errors in the request body format are another.

**Comment by fschmied** [comment]
Okay, thanks for giving concrete examples.

> exceptions are sometimes used to communicate this and it's up to the app to catch them and decide if a 4xx is appropriate

Is there a list of expected exceptions thrown by ASP.NET Core in reaction to request input so we can explicitly handle them? Or any other guidance on how we could differentiate system errors from request errors?

**Comment by Eilon** [comment]
@fschmied unfortunately the list of exceptions is ever changing, and also varies based on 3rd party components, so providing such a list would be infeasible. However, in cases such as ASP.NET Core MVC, we've done work for API controllers to return better status codes by default, which would just avoid certain exceptions from being thrown in the first place.

But I'm not aware of any general purpose solution.

**Comment by Eilon** [comment]
@fschmied I think in general yes that's the pattern. Another issue with having it be too "automatic" is that the right way to deal with an unhandled exception can vary dramatically between apps. Some apps might want to retry an operation, some might fall back to a default behavior, or who knows what.

I think what might be reasonable is that if you find an unhandled exception that you think that ASP.NET Core should definitely just handle in a definitive way, we could look at that and see if there should be a default behavior.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
