### ISSUE TITLE
Asp.net core app won't start after Win 10 upgrade.

### ISSUE THREAD

**Issue by LeslieMurphy** [aspnet/AspNetCore#3565]
I have asp.net core 2.0 app that used to work when launched from Visual Studio before a Win 10 update (after the update I am now at Version 1809 Build 17763.1) .  Now my app fails with:

System.IO.IOException: Failed to bind to address http://localhost:49913
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4092 EACCES permission denied

I changed the port in launchSettings.json to 49914, and it also fails.  Changed it to 5000 and it works.  Go figure!

.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by Tratcher** [comment]
If it works on 5000 then there's no indication anything is wrong with the app or framework. It sounds like normal port conflicts. Have you tried a wider variety of ports?
