### ISSUE TITLE
Accessing HttpContext after the request has completed

### ISSUE THREAD

**Issue by ItsVeryWindy** [aspnet/AspNetCore#3581]
Until recently I didn't actually realise that there were issues using the context after the request had completed.

Just as a basic example, when I run this and execute a request with a path and query string, after the delay it writes to the console but the path and query string are empty.

I wouldn't mind the fact that it could be no longer used, but there's nothing to indicate there is any sort of problem. In our case we had a background task we were passing the context to and certain logic we would execute based off something in the request wasn't being executed.

```csharp
public static class Program
{
    public static void Main(string[] args)
    {
        WebHost.CreateDefaultBuilder()
            .Configure(appBuilder => appBuilder.Run(context =>
            {
                Execute(context);

                return context.Response.WriteAsync($"your request is {context.Request.Path} with query string {context.Request.QueryString}");
            })).Build().Run();
    }

    static async void Execute(HttpContext context)
    {
        await Task.Delay(10000);

        Console.WriteLine($"your request was {context.Request.Path} with query string {context.Request.QueryString}");
    }
}
```

**Comment by Tratcher** [comment]
> Does that mean it's also not thread safe even within the context of its own request? 

Correct.

> ObjectDisposedException 

Understood. We haven't gone that route yet because it requires a lot of bookkeeping and disposed checks. We've added some checks to the places most commonly misused like the streams. It also takes some effort to get into this situation, we've only had a few reports of this class of mistake.

**Comment by Eilon** [comment]
It's worth noting that in general, no objects are thread-safe. It has to be an explicit decision made by the author of a component, and then documented (i.e. guaranteed) as such.

**Comment by ItsVeryWindy** [comment]
Good to know 👍

**Comment by davidfowl** [comment]
The logging scope is intended to be safe to examine during logging but that wasn't 100% safe in previous releases (just looking at the code). The scope held onto the `HttpContext` and logged properties which is problematic for things like this. In 2.2 we copy the data required from the HttpContext into simple fields to avoid this problem.

**Comment by davidfowl** [comment]
@ItsVeryWindy how are you triggering the background task? Do you want to preserve the logging scope there?

**Comment by ItsVeryWindy** [comment]
@davidfowl At the moment the task is triggered during the request but don't bother to await it. Preserving the logging scope is beneficial for us as the it gives us context around the request that was responsible for kicking it off.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
