### ISSUE TITLE
Poison the HttpContext after it's disposed by the HttpContextFactory

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#3586]
The default HttpContextFactory should poison the HttpContext so that it throws `ObjectDisposedException` if the feature collection is accessed after the request is over. We'd do this by setting a feature collection that just throws on GetFeature

Related to #3581

cc @Tratcher

**Comment by Eilon** [comment]
How much of a breaking change is this?

**Comment by Tratcher** [comment]
> How much of a breaking change is this?

A brutal one if you were using it against guidance and somehow managed not to break. Otherwise only a minor one.

**Comment by Eilon** [comment]
Right 😄 I agree there are no legit cases, but as we know, there are cases where people have been lucky and got away with things.

**Comment by rynowak** [comment]
If we at least replace the service provider with an empty one, this would go a long way to becoming resilient to memory leaks via execution context.

**Comment by davidfowl** [comment]
Yep that’s another benefit.

**Comment by anurse** [comment]
With pooling of the HttpContext this is going to be a lot harder. Needs a lot of design.

**Comment by davidfowl** [comment]
Close this

**Comment by anurse** [comment]
The only reason I didn't close it was because I figured you'd get grumpy :trollface:
