### ISSUE TITLE
After install core 2.1.5, the project cannot be published

### ISSUE THREAD

**Issue by leung85** [aspnet/AspNetCore#3587]
I use visual studio 2017 15.8.6, and install core 2.1.5 download from here: 
https://www.microsoft.com/net/download/dotnet-core/2.1

 the version of core SDK, runtime is quite complicated,There are some problem about dependency version, and make me confuse:

1. The **.net core console project** cannot be published using self-contained with visual studio 2017, 
Error:
> The project was restored using Microsoft.NETCore.App version 2.1.0, but with current settings, version 2.1.5 would be used instead. To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish. Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore.

But it can be published using Framework Dependent. Also, it can be publish as self-contained  if i use command `dotnet publish`  <-- Is it  intended behavior ??

After search i lot of similar case, it suggested add `<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>`

ok. that fix the problem, but why i need add this code, i expected if i have not mention the version number ,it should be use the latest.   

However, i found that the **.net core web project** , no need to add above code , and it can be  published using both self-contained and Framework Dependent.  but it still use Microsoft.NETCore.App version 2.1.0. 

so i try create a new web project...

2. Why new created core project default use Microsoft.NETCore.App 2.1.0, not 2.1.5. And i want use NuGet update the package, it is blocked by Project. <---????

![image](https://user-images.githubusercontent.com/8042599/46526554-26cccf00-c8c1-11e8-8f44-225bf687a45d.png)

ok , i add `<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>`, 
then web project use` Microsoft.NETCore.App 2.1.5 `now, but when i run it using docker local, it fail.....:
![image](https://user-images.githubusercontent.com/8042599/46527888-f4bd6c00-c8c4-11e8-8460-1d2d9d131604.png)

then i try use IISExpress it said the port is being used. the docker is still running after i stop debug.
so i cannot simply  switch using docker and IISExpress. i need to delete the docker container.

if i run IISExpress first i need to do the similar thing: close the IISExpressand clean the solution.

Am i doing wrong to update an SDK??

**Comment by Eilon** [comment]
Hi @leung85 , can you show what the CSPROJ file looks like?

**Comment by Eilon** [comment]
Tagging @natemcmaster as well.

**Comment by natemcmaster** [comment]
> Why new created core project default use Microsoft.NETCore.App 2.1.0, not 2.1.5. And i want use NuGet update the package, it is blocked by Project. <---????

Microsoft.NETCore.App and AspNetCore.App are special packages which represent shared frameworks. You do not need to update the package version for a framework-dependent app to run on a newer framework. See https://docs.microsoft.com/en-us/dotnet/core/packages. See my updated description here: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1067/files. Let me know if that answers this question. 

> It was not possible to find any compatible framework version

This is why we attempt to block you from changing the package version.

> am i doing wrong to update an SDK??

It looks like you updated the SDK in Windows, but I'm guessing from the screenshot (which mentions `/usr/share/dotnet`) that you also need to update your Docker container, Linux box, or macbook.

**Comment by leung85** [comment]
> Hi @leung85 , can you show what the CSPROJ file looks like?

I create a console app project, a class library project and a web api project.
Then add the class library reference  to console app project and web project.
Since i use linux-arm ,  i add  `<RuntimeIdentifiers>linux-arm</RuntimeIdentifiers>`

What i found is:

![image](https://user-images.githubusercontent.com/8042599/46591347-bc987200-caec-11e8-8796-02449ebec172.png)

vs2017:
![image](https://user-images.githubusercontent.com/8042599/46591369-e05bb800-caec-11e8-8e2d-f464f090af26.png)

dotnet command i use:
`dotnet publish -r linux-arm -c release --self-contained`

**Btw, if i remove the class library reference, both project can be published with self-contained**

Am i missing some important step??

For console App:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeIdentifiers>linux-arm</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>

```

For Web api app:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <DockerTargetOS>Linux</DockerTargetOS>
    <RuntimeIdentifiers>linux-arm</RuntimeIdentifiers>
    <UserSecretsId>bd13aca9-4a93-4daa-b4f9-835f129d214c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.0.1916590" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>

```

For Class  library:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by leung85** [comment]
> > Why new created core project default use Microsoft.NETCore.App 2.1.0, not 2.1.5. And i want use NuGet update the package, it is blocked by Project. <---????
> 
> Microsoft.NETCore.App and AspNetCore.App are special packages which represent shared frameworks. You do not need to update the package version for a framework-dependent app to run on a newer framework. See https://docs.microsoft.com/en-us/dotnet/core/packages. See my updated description here: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1067/files. Let me know if that answers this question.
> 
> 
> > am i doing wrong to update an SDK??
> 
> It looks like you updated the SDK in Windows, but I'm guessing from the screenshot (which mentions `/usr/share/dotnet`) that you also need to update your Docker container, Linux box, or macbook.

Hi @natemcmaster 
Thanks your explain. much clear now. 
 So i don't have to add  `<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>`
and just update my docker file to use 2.1.5 runtime and 2.1.403-sdk.

**Comment by natemcmaster** [comment]
> So i don't have to add `<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>` and just update my docker file to use 2.1.5 runtime and 2.1.403-sdk.

@leung85: Yes, that is my recommended course of action.

Can I close this issue? Or are you still having issues with publishing 2.1.5 in self-contained mode?

**Comment by leung85** [comment]
@natemcmaster 

In my first reply: https://github.com/aspnet/Home/issues/3587#issuecomment-427714032

Is it intended behavior??

**Comment by AscarGb** [comment]
Same problem
