### ISSUE TITLE
Remove the old Redis dependency

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCore#3591]
We're adding a new dependency in #3536 for 2.2.

In 3.0, let's remove Microsoft.AspNetCore.DataProtection.Redis package.

cc @anurse @Tratcher @DamianEdwards @Eilon

**Comment by BrennanConroy** [comment]
We never shipped Microsoft.AspNetCore.DataProtection.Redis so we just renamed it in 2.2. No work left here.
