### ISSUE TITLE
Test failure: GetNormalizedOrigin_ReturnsPunyCodedOrigin

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3593]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=570630&buildTypeId=XPlat_Windows_Win7_Universe) with the following error:

```
System.UriFormatException : An invalid Unicode character by IDN standards was specified in the host.
   at System.DomainNameHelper.IdnEquivalent(Char* hostname, Int32 start, Int32 end, Boolean& allAscii, String& bidiStrippedHost)
   at System.DomainNameHelper.IdnEquivalent(Char* hostname, Int32 start, Int32 end, Boolean& allAscii, Boolean& atLeastOneValidIdn)
   at System.DomainNameHelper.IdnEquivalent(String hostname)
   at System.Uri.get_IdnHost()
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsPolicyBuilder.GetNormalizedOrigin(String origin) in /_/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsPolicyBuilder.cs:line 68
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsPolicyBuilderTests.GetNormalizedOrigin_ReturnsPunyCodedOrigin(String origin, String expected) in /_/test/Microsoft.AspNetCore.Cors.Test/CorsPolicyBuilderTests.cs:line 377
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @mkArtakMSFT

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=571890&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 5:25:40 PM:
- GetNormalizedOrigin_ReturnsPunyCodedOrigin

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=572659&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 10:53:03 AM:
- GetNormalizedOrigin_ReturnsPunyCodedOrigin

**Comment by pranavkm** [comment]
This particular test was skipped. Tracking further work in https://github.com/aspnet/AspNetCore/issues/3597
