### ISSUE TITLE
Consider making TryAdd(…) extension methods for IServiceCollection fluent

### ISSUE THREAD

**Issue by smarts** [aspnet/AspNetCore#3605]
You can currently do something like:
```csharp
IServiceCollection services = …
services
  .AddTransient<MyTransientService>()
  .AddSingleton<MySingletonService>();
```
but `TryAdd(…)` returns `void` instead of the same fluent API, which is frustrating. It means I have to do this:
```csharp
services.AddTransient<MyTransientService>()
services.TryAdd<MySingletonService>();
```
Even though it's changing the method signature, it seems like a backward-compatible, low-risk change.

I'm happy to add a pull request if the team thinks it's an acceptable change.

**Comment by khellang** [comment]
IMO, it would be much better it they returned `bool`, like most `Try*` methods (see https://github.com/aspnet/DependencyInjection/issues/447).

**Comment by davidfowl** [comment]
This is a breaking change and we're not making those.

**Comment by smarts** [comment]
@davidfowl do you mind clarifying the "we're not making those" statement? Does that mean "ever"? I don't expect the decision to change, but the above proposal - while it is a "breaking change" - doesn't seem like the type of change that would actually break anything at compile time or runtime. Is it simply a line that will not be crossed?
I don't mean to drag this on, I just want to understand to better inform future decisions about whether or not to file an issue.

**Comment by khellang** [comment]
Changing a methods is at least a binary breaking change. It might also be a source breaking change. See https://stackoverflow.com/a/1472967/682105

**Comment by davidfowl** [comment]
Yes it actually is both a runtime and a breaking change. It means any library that called it would need to recompile against this newer version of the system which IMO is a non starter for these Microsoft.Extensions libraries. These libraries are meant to be extremely stable.

**Comment by smarts** [comment]
Cool. Thanks for the clarification. I hadn't thought about the delegate or reflection cases.
