### ISSUE TITLE
Add application/manifest+json ( .webmanifest) Static File MIME Type

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/AspNetCore#3613]
The `.webmanifest` file extension should return the `application/manifest+json` MIME type. See [sonarwhal documentation](https://sonarwhal.com/docs/user-guide/rules/manifest-file-extension/) and [W3C](https://w3c.github.io/manifest/#media-type-registration) for reference.

I raised PR https://github.com/aspnet/StaticFiles/pull/221 for this but it was closed without a reason given.

**Comment by sebastienros** [comment]
Duplicate of https://github.com/aspnet/AspNetCore/issues/2442

But I'd give some point to this, seems to be a new common usage, and it's very simple to implement.
The workaround is to alter `FileExtensionContentTypeProvider` like this https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.1&tabs=aspnetcore2x#fileextensioncontenttypeprovider

**Comment by RehanSaeed** [comment]
Ah, looks like my original issue got moved.
