### ISSUE TITLE
text/javascript is the "correct" Static Files MIME Type

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/AspNetCore#3614]
I noticed this change when I got a warning while trying out [Sonar](https://github.com/sonarwhal/sonar/issues/568). Apparently the standards bodies have changed their minds:

- https://github.com/whatwg/html/pull/3096
- https://github.com/bmeck/I-D/issues/2

This is a breaking change. I raised PR https://github.com/aspnet/StaticFiles/pull/220 but it was closed without a reason given for why.

**Comment by RehanSaeed** [comment]
This post from Sonarwhal which recommended `text/javascript` is what prompted my issue and PR:

https://github.com/webhintio/hint/issues/568#issuecomment-339945844

**Comment by shirhatti** [comment]
Closing as a dupe of #3099
