### ISSUE TITLE
InvalidOperationException in AuthenticationMiddleware while AuthenticationSchemeProvider.RemoveScheme

### ISSUE THREAD

**Issue by blackrek** [aspnet/AspNetCore#3619]
In case of simultaneous execution `AuthenticationSchemeProvider.RemoveScheme` from background Task and any request, which uses `AuthenticationMiddleware `may get 
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext()

```

By default `AuthenticationMiddleware `using `AuthenticationSchemeProvider.GetRequestHandlerSchemesAsync()` for retrieving all schemes and enumerate results via foreach.

Problem occurs when removing scheme from `_requestHandlers `at the moment when enumeration in process from foreach (without any locks)

Microsoft.AspNetCore.Authentication.dll version 2.1.1
Microsoft.AspNetCore.Html.Abstractions.dll 2.1.1

dotnet info:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by Tratcher** [comment]
Hmm, we lock on [add and remove](https://github.com/aspnet/HttpAbstractions/blob/8e4f7365adf304e9704b1db43e3095a267583513/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationSchemeProvider.cs#L132-L171), but not on [enumeration](https://github.com/aspnet/HttpAbstractions/blob/8e4f7365adf304e9704b1db43e3095a267583513/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationSchemeProvider.cs#L125-L126). This [List](https://github.com/aspnet/HttpAbstractions/blob/8e4f7365adf304e9704b1db43e3095a267583513/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationSchemeProvider.cs#L51) needs to be a ConcurrentQueue.

**Comment by HaoK** [comment]
Yeah, should we try to fix this in 2.2 rtm?

**Comment by Tratcher** [comment]
Yeah, it looks like a simple drop in replacement.

**Comment by davidfowl** [comment]
Maybe just add the lock.

**Comment by Tratcher** [comment]
The enumeration takes place in a different class (the auth middleware) that doesn't know about the lock.

**Comment by HaoK** [comment]
Queue isn't a straight replacement since we support Remove, while queue only supports removing at ends :/  We could use ConcurrentDictionary but then we'd have a slight change in behavior that GetAllSchemes no longer would return them in the order they were registered...

If we do this in 3.0 we could just accept that slight behavior change maybe?  Main diff would be the order of the request processing schemes would potentially change (unless we added some complexity to track the scheme order)

**Comment by HaoK** [comment]
We should prob discuss this at next security triage, tagging @Eilon @blowdart since this is issue isn't in security repo

**Comment by HaoK** [comment]
Maybe the short term fix for 2.2, is we just lock and copy the _schemes to another enumerable we return instead of directly returning the values?

**Comment by HaoK** [comment]
Something like this maybe?

```C#
        public virtual Task<IEnumerable<AuthenticationScheme>> GetAllSchemesAsync()
        {
            IEnumerable<AuthenticationScheme> copy = null;
            lock (_lock)
            {
                copy = _schemes.Values.ToList();
            }
            return Task.FromResult(copy);
        }

```

**Comment by Tratcher** [comment]
That's quite expensive to do on every request.

**Comment by HaoK** [comment]
We can cache the copy maybe, and only copy when it changes which shouldn't be often

**Comment by HaoK** [comment]
The copying would only happen when adding/remove schemes which is usually done only during startup, so it wouldn't be noticeable really.  Copying a small list inside the lock shouldn't be a big deal since its already inside of a super slow lock right?

**Comment by Eilon** [comment]
Ah OK

**Comment by HaoK** [comment]
I'll send a PR so its more clear what the fix would be

**Comment by HaoK** [comment]
@Eilon do we want this for 2.2?

**Comment by Eilon** [comment]
Sounds fine to me. The PR is signed off so that looks alright.

**Comment by HaoK** [comment]
Fixed via https://github.com/aspnet/HttpAbstractions/pull/1052
