### ISSUE TITLE
How do I get Microsoft Account to prompt for which account to use

### ISSUE THREAD

**Issue by allenh100** [aspnet/AspNetCore#3621]
Hi,
I have an ASP.NET Core 2.1 application that is using Microsoft Account for authentication and I would like to be able for the user to select which identity they want to use.

I am currently logged into a network that supports my AAD identity as part of MSA (allenh@microsoft.com) and I have an external email account (boddah@comcast.net) that I would like to have the option to use.

The behavior I see currently is as soon as i click on login, the system automatically uses my AAD identity even though I have established a login previously for my external account.

What I would like to achieve is that after clicking login, the user is presented with a dialog of active login identities to choose from as well as the option to use a different one not already logged in.

I have tried experimenting with the various options you have access to via the .AddMicrosoftAccount() call, but nothing seems to have the effect I am looking for.

Is this possible, and if so how?

Thanks,
allen

**Comment by Tratcher** [comment]
This looks like a usage question rather than a product issue. Such questions are better directed to forums like [Stackoveflow.com](Stackoveflow.com). See also https://github.com/aspnet/Security/pull/1401 for a related feature.

**Comment by poke** [comment]
I don't know if Azure AD supports this properly but setting `prompt=select_account` should work with OpenID Connect.

**Comment by allenh100** [comment]
thank you poke.  can you share and short example in code how i would do that?  i am assuming this would be done inside CofigureServices() but it is not obvious how/where to set that value.

**Comment by khellang** [comment]
```csharp
options.Events.OnRedirectToIdentityProvider += context =>
{               
    context.ProtocolMessage.Prompt = "select_account";
    return Task.CompletedTask;
};
```

**Comment by poke** [comment]
You are using the `MicrosoftAccount` scheme which is based on OAuth, so I’m not sure if that one supports the `prompt` parameter. At least the `MicrosoftAccountHandler` does not allow you to specify it so you would have to roll your own scheme here.

Or you switch to OpenID Connect here (replacing the `AddMicrosoftAccount()` call), but then you need to configure OIDC properly.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
