### ISSUE TITLE
 No SDKs were found after installing dotnet-hosting-2.1.5-win.exe

### ISSUE THREAD

**Issue by whizkidwwe1217** [aspnet/AspNetCore#3624]
To address your issues more quickly, please open the issue in the most appropriate repository.

If you're not sure exactly where to log the bug, please log the issue here and we will redirect it.

ASP.NET Core:
 - General issues: https://github.com/aspnet/Home (this repo)
 - MVC and Razor Pages: https://github.com/aspnet/Mvc
 - SignalR: https://github.com/aspnet/SignalR
 - Kestrel HTTP Server: https://github.com/aspnet/KestrelHttpServer
 - Docker: https://github.com/aspnet/aspnet-docker
 - Documentation: https://github.com/aspnet/Docs
 - Microsoft.NET.Sdk.Web: https://github.com/aspnet/websdk
 - See a full list here: https://github.com/aspnet
   - Note: Some repos do not have active issue trackers, so if you see such a warning, please log the issue here

ASP.NET 4.x:
 - ASP.NET MVC/Web API (not Core): https://github.com/aspnet/AspNetWebStack
 - Katana: https://github.com/aspnet/AspNetKatana

Entity Framework:
 - Entity Framework Core: https://github.com/aspnet/EntityFrameworkCore
 - Entity Framework 6: https://github.com/aspnet/EntityFramework6

Other common projects:
 - .NET Core CLI and SDK: https://github.com/dotnet/core
 - .NET Core runtime: https://github.com/dotnet/coreclr
 - .NET Core libraries: https://github.com/dotnet/corefx
 - NuGet: https://github.com/NuGet/home
 - Visual Studio: https://developercommunity.visualstudio.com
 - Visual Studio Code: https://github.com/microsoft/vscode
 - Omnisharp (C# support for VS Code): https://github.com/omnisharp/omnisharp-vscode

If you believe you have an issue that affects the security of the platform please do NOT create an issue and instead email your issue details to secure@microsoft.com. Your report may be eligible for our [bug bounty](https://technet.microsoft.com/en-us/mt764065.aspx).

---

Tips for opening great bugs:

1. Try enabling logging (in the most verbose level) and see if the details help you in fixing the issue you are seeing. Share the logs too if it helps in diagnosing the issue faster. More info: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging
2. If you are seeing an exception, include the full exceptions details (message and stack trace). More info: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling
3. Please try to include as much information as possible:
   1. Description of the problem:
   2. Steps to reproduce (preferrably a link to a GitHub repo with a repro project)
   3. The version of `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`
   4. The output of `dotnet --info`

**Comment by jkotalik** [comment]
I believe this is expected. The dotnet-hosting bundle doesn't include the SDK by default. @joeloff to confirm.

**Comment by jkotalik** [comment]
Which version of the SDK was present? And to confirm, by doing the following steps:
- Install the dotnet SDK from here: https://www.microsoft.com/net/download/dotnet-core/2.1
- Install the windows hosting bundle from the same link
- Check C:\Program Files\dotnet\sdk for SDKs.

That you don't see any SDKs? Also, what exact error message are you seeing on the command line when you try to run `dotnet --info`?

**Comment by whizkidwwe1217** [comment]
@jkotalik That's exactly the steps that I did.
1. Installed SDK version 2.1.403 (latest version) 
2. Ran dotnet --info and 2.1.403 SDK and 2.1.5 runtime (x86 and x64) were present.
3. Checked the C:\Program Files\dotnet\sdk for SDKs and were there.
4. Now the issue comes when I install the latest Hosting Bundle (2.1.5), dotnet --info can't find the SDKS and says "No SDKS were found". I have to uninstall all the .net core SDKs, runtimes, hosting bundle and delete the dotnet folders in both Program Files (x86) & Program Files. And then reinstall the SDK without installing the hosting bundle. But I need the hosting bundle to host my app in local IIS.

**Comment by whizkidwwe1217** [comment]
@jkotalik This is what happens when I install the hosting bundle:
![image](https://user-images.githubusercontent.com/1977391/46912830-d76a5b00-cfb2-11e8-9798-5d066fc244e7.png)

**Comment by joeloff** [comment]
The hosting bundle doesn't remove the SDK. It only installs a new runtime. As you showed in the screenshot the SDK folders are still present. I wonder if the runtime maybe modifies an environment variable that causes dotnet to think the SDK isn't present or that it's looking for an SDK version that matches the runtime.

@livarcocc have you seen this before?

**Comment by livarcocc** [comment]
It seems you installed the x86 hosting bundle, while before, you installed the x64 SDK. This is noticeable from the paths showed in each case: `Program files` VS `Program Files (x86)`.

In this case, what is happening here is that the hosting bundle is updating your PATH, therefore, after installing it, when you type dotnet, it is using the `Program Files (x86)` dotnet, and next to it, there are no SDKs.

**Comment by whizkidwwe1217** [comment]
@livarcocc Are you saying that I installed the incorrect hosting bundle? How will I know if it's x86 or x64? There's only one installer of hosting bundle in the downloads link.

**Comment by joeloff** [comment]
The hosting bundle carries both x86 and x64 runtimes. On a 64-bit OS it will try to install both, unless you disable the x86 install from the commandline.

**Comment by joeloff** [comment]
@whizkidwwe1217 Sorry, let me clarify. By "Both" I meant both x86 and x64 copies of the runtime. The hosting bundle has never shipped or installed the SDK. The hosting bundle is intended solely for running .NET Core applications. It doesn't include any development tools.

**Comment by joeloff** [comment]
I suspect this is an issue with how the CLI and the runtime installers in the hosting bundle deal with updating environment variables.

**Comment by PezeM** [comment]
Got the same problem as @whizkidwwe1217

**Comment by shirhatti** [comment]
@joeloff Are we going to make any change here?

By changing the order in which dotnet is added to the PATH will break the opposite set of folks who have a different bitness SDK installed. My recommendation is to close this issue. We can doc this as known behavior that can be trivially fixed by changing your PATH.

**Comment by joeloff** [comment]
Agree. Since the hosting bundle will install both x64 and x86, not matter which way we arrange them, we'll just get opposite results. I'll raise this with some of the runtime folks as well

**Comment by whizkidwwe1217** [comment]
any update on this? I'm planning to upgrade to latest 2.2.10. Is this issue already resolved in that version?

**Comment by whizkidwwe1217** [comment]
i just installed the latest version I think it's now fixed.

**Comment by whizkidwwe1217** [comment]
@joeloff Can you guys please fix this in version 3 before you ship it?

**Comment by whizkidwwe1217** [comment]
Phew!!! Finally got working! 

> Agree. Since the hosting bundle will install both x64 and x86, not matter which way we arrange them, we'll just get opposite results. I'll raise this with some of the runtime folks as well

I totally missed this comment. It fixed when I reorder the path in environment variables..

**Comment by jkotalik** [comment]
@whizkidwwe1217  glad you got it working 😄

**Comment by joeloff** [comment]
We previously had the order reversed and that ended up breaking people with Visual Studio during the early previews of VS. The hosting bundle was really intended for hosters that needed to support both 32-bit/64-bit applications. You'll still be able to end up in this situation if you manually installed the runtimes in different orders, but we can definitely take this up with the runtime folks

**Comment by shirhatti** [comment]
@guardrex Perhaps we should capture this in the troubleshooting doc for IIS? Looks like a couple of folks have run into this issue already

**Comment by AnunnakiSelva** [comment]
![image](https://user-images.githubusercontent.com/44052102/57356002-f6b61900-718c-11e9-9618-e656e607a46f.png)

Uninstall all  *.x86  and have only x64 versions (if you have windows x64 OS)  It worked for me .

**Comment by anurse** [comment]
It doesn't look like there's actionable work here now. Feel free to comment if I'm wrong and we can reopen.

**Comment by rodrigocaldas** [comment]
> ![image](https://user-images.githubusercontent.com/44052102/57356002-f6b61900-718c-11e9-9618-e656e607a46f.png)
> 
> Uninstall all *.x86 and have only x64 versions (if you have windows x64 OS) It worked for me .

tnx, it helped a lot :)
