### ISSUE TITLE
Extensions Package for DataAnnotations: Recursively validating an entire object graph

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/AspNetCore#3626]
Can the code that validates an object graph in ASP.NET Core MVC be moved to a `Microsoft.Extensions` package to allow for re-use outside of MVC?

---

### Background

I wanted to validate an object and I learned of this limitation on the `Validator`:

>It does not recursively validate the property values of the object.

Source: [Validator.TryValidateObject Method](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validator.tryvalidateobject?view=netcore-2.1)

### MVC Does this, 🤔

But I know ASP.NET Core MVC validates the whole object graph.  How can I use it?

It seems that [`Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVistor`](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs) seems to do the magic but it seems to be tied to MVC based upon the dependencies:

```csharp
public ValidationVisitor(
            ActionContext actionContext,
            IModelValidatorProvider validatorProvider,
            ValidatorCache validatorCache,
            IModelMetadataProvider metadataProvider,
            ValidationStateDictionary validationState)
        { .... }
```

### Additional Notes

Reference: [StackOverflow post](https://stackoverflow.com/questions/7663501/dataannotations-recursively-validating-an-entire-object-graph/7665862)

Open Source Package to validate the object graph: [reustmd/DataAnnotationsValidatorRecursive](https://github.com/reustmd/DataAnnotationsValidatorRecursive)

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8606
