### ISSUE TITLE
Syntax sugar in source code like '?.'

### ISSUE THREAD

**Issue by xyz0822** [aspnet/AspNetCore#3628]
like snipcode in DependencyInjection:
      var implementationTypeInfo = descriptor.ImplementationType?.GetTypeInfo();

for example: "?." Syntax sugar，i do think this Syntax sugar is unnecessary，and sometimes it is poor readability.
could we reduce such code in source code?

**Comment by xyz0822** [comment]
I know this is very comfortable to write.
Just a personal idea......

**Comment by davidfowl** [comment]
Thanks for the feedback but this we actually thinks this feature improves the readability in lots of cases.
