### ISSUE TITLE
Problems with aspnetcore clusters

### ISSUE THREAD

**Issue by anlem12** [aspnet/AspNetCore#3629]
Problems with aspnetcore clusters

Here are a list of errors and warnings that i'm getting constantly

The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {xxxxxxx} was not found in the key ring.
or
the most exception i get:
An exception was thrown while deserializing the token.
or
which i get the most warning is :
Error unprotecting the session cookie.

**Comment by davidfowl** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-2.1#required-configuration for instructions on how to setup the data protection stack in a clustered environment.

**Comment by anlem12** [comment]
I used redies and still got an exception: Error uncheckthe session cookie.

My application is deployed on kubernetes.

Which can be normally accessed if only one pod is deployed.

Exceptions will occur if you deploy to 2 or more, and each refresh of sessionid will change to a new value



` services.AddDistributedRedisCache(options =>
            {
                options.Configuration = Configuration["SessionConfig:Redis:Connection"];
                options.InstanceName = Configuration["SessionConfig:Redis:InstanceName"];
            }).AddDataProtection().SetApplicationName("testname").SetDefaultKeyLifetime(TimeSpan.FromDays(90));


            services.AddSession(m =>
            {
              //  m.Cookie.Domain = "sto-k8s.com";
                m.Cookie.Name = "ASP.NET_SessionId";
                m.IdleTimeout = TimeSpan.FromMinutes(Configuration.GetValue<int>("SessionConfig:SessionTimeOut", 30));// session过期时间
            });`

**Comment by davidfowl** [comment]
Distributed cache has nothing to do with data protection. They both have redis providers but you need to write up the data protection key store separately. See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.1#azure-and-redis.

**Comment by anlem12** [comment]
thanks
