### ISSUE TITLE
Lower kebab case routing url

### ISSUE THREAD

**Issue by TanvirArjel** [aspnet/AspNetCore#3630]
In the `ConfigureServices` method of the `startup` class I am configuring as follows:

`services.AddRouting(option => option.LowercaseUrls = true);`

And it making my routing url `http://localhost:13921/Exception/ExceptionList` as follows:

`http://localhost:13921/exception/exceptionlist`

Actually it should have been:

`http://localhost:13921/exception/exception-list`

for more readability.

Thank you.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Routing#861
