### ISSUE TITLE
unicode url with DefaultFilesMiddleware

### ISSUE THREAD

**Issue by newbienewbie** [aspnet/AspNetCore#3633]
**Version of `Microsoft.AspNetCore.App`** : 

2.1.1

**Description and How to reproduce**

Let's say we are serving a static directory whose path string contains unicode codes : 

* url path string = `blog/categories/大道/index.html` 
* physical file path string = `blog/categories/大道/index.html`

When there's an incoming request to  `blog/categories/大道/`，the [`DefaultFileMiddlware`](https://github.com/aspnet/StaticFiles/blob/4c8df8e5a4e3abe5e7db51685dbd892d160c1e35/src/Microsoft.AspNetCore.StaticFiles/DefaultFilesMiddleware.cs#L69) gets the directory by  `var dirContents = _fileProvider.GetDirectoryContents(subpath.Value);` . And now the middleware will check whether the directory  exists [as below](
https://github.com/aspnet/StaticFiles/blob/4c8df8e5a4e3abe5e7db51685dbd892d160c1e35/src/Microsoft.AspNetCore.StaticFiles/DefaultFilesMiddleware.cs#L69
) :

```csharp
                var dirContents = _fileProvider.GetDirectoryContents(subpath.Value);
                if (dirContents.Exists)
                {
                    // ...

```

The result will be true .  

However , when coming into the default `index.html` ,  the `DefaultFileMiddlware` checks the file path by : 
```csharp
var file = _fileProvider.GetFileInfo(subpath + defaultFile);
```

Here the `subpath` is often urlencoded , so the file path will be something like : 
```
"blog\\categories\\%E5%A4%A7%E9%81%93\\index.html"
```
As a result , ` file.Exists` will return `false` .

**Comment by Tratcher** [comment]
https://github.com/aspnet/StaticFiles/pull/257
