### ISSUE TITLE
2.2 test failures: unexpected output in self-contained publish

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#3635]
The latest builds of 2.2 preview 3 are failing E2E tests: https://dev.azure.com/dnceng/internal/_build/results?buildId=30511&view=ms.vss-test-web.test-result-details. There appear to be two reasons

1. IdentityModel upgraded to 5.3 in https://github.com/aspnet/Universe/pull/1482. This introduced a new assembly into the shared framework (cc @HaoK) which means self-contained publish tests have a new, unexpected assembly, Microsoft.IdentityModel.JsonWebTokens.dll.
2. Updates to jquery in templates. The tests assert these files are present, but they are no longer in publish output: wwwroot\lib\jquery\.bower.json and wwwroot\lib\jquery-validation\.bower.json. cc @ryanbrandenburg 

The test code for this is in https://github.com/aspnet/Universe/tree/release/2.2/test/Cli.FunctionalTests

cc @Eilon @muratg @mkArtakMSFT

**Comment by ryanbrandenburg** [comment]
For 2, those bower files were removed intentionally, but why do we have tests of our Template contents in two places? We already baseline templates as part of our [functional tests](https://github.com/aspnet/Templating/blob/master/test/Templates.Test/template-baselines.json#L6).

**Comment by muratg** [comment]
@ryanbrandenburg these are **E2E tests** implemented by @mikeharder , and in the last few releases it actually found bunch of release blocking issues.

**Comment by Eilon** [comment]
I think @mkArtakMSFT 's team has taken ownership of the tests that @mikeharder wrote.

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT is there anyone in particular I should contact about these tests or should I just make the appropriate changes?

**Comment by mikeharder** [comment]
@Eilon: You might be confusing two different tests I helped write:

1. The first tests are where vendors manually test the MVC repo in dogfood VS, and @ajaybhargavb is taking ownership of these (receiving result emails, triaging issues, infrequent test updates).
2. The second tests are automated, run after every prodcon build, and verify the basic functionality of our templates (restore, build, run, publish, etc).  I don't believe anyone has been assigned to own these.  These tests will need more frequent updating as templates are changed.

**Comment by mikeharder** [comment]
@ryanbrandenburg: There may be some overlap between the end-to-end tests I added to Universe, and the tests already in the Templating repo.  The difference is the end-to-end tests run against the final builds created by ProdCon, so they are testing the end-to-end experience from the customer perspective, rather than the intermediate build we test in Templating.  The end-to-end tests catch unique issues like packages missing from feeds, mismatched package versions in ProdCon, etc.

**Comment by ryanbrandenburg** [comment]
Fair duce, there's definite value in re-confirming that the correct data is in the final bits. Hopefully once we Mondo-ize everything those tests will be able to share the baseline data so we only have to change it in one place.

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT what is that status of this issue?

**Comment by mkArtakMSFT** [comment]
Closing this. whatever issues were rthere are resolved or obsolete already.
