### ISSUE TITLE
Discussion for: ASP.NET Core 2.2.0 Preview 3 known issues

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#3642]
Official announcement blog post: https://blogs.msdn.microsoft.com/webdev/2018/10/17/asp-net-core-2-2-0-preview3-now-available/

Discussion for this announcement: https://github.com/aspnet/Announcements/issues/323

**Comment by Eilon** [comment]
@danroth27 / @blowdart / @javiercn - can you comment?

**Comment by SIkebe** [comment]
@mikeandersun 
https://twitter.com/blowdart/status/1042265047878123520

**Comment by steveoh** [comment]
I'm noticing that my healthcheck response writer is not being invoked in preview 3. I'll dig a little deeper tomorrow.

**Comment by javiercn** [comment]
@rynowak I also ran into this, while verifying and solved it by putting the most specific path first. It’s hard to realize if you don’t know what you are looking for.

It’ll be good to take a look at it.

**Comment by marcrib** [comment]
People are waiting miracle of microsoft on authserver
Just as we have Nhibernate, Dapper with alternative to EF Core. We have IdentityServer, OpenIddict and others for authserver

**Comment by brockallen** [comment]
> People are waiting miracle of microsoft on authserver

And Microsoft is not doing anything here other than including and pre-configuring IdentityServer based on assumptions in a template they're shipping. So all of the non-Microsoft options are still available.

**Comment by marcrib** [comment]
@brockallen the microsoft implementation use implict flow? or only resource password?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
