### ISSUE TITLE
Produce osx crossgen symbols for the shared runtime

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3644]
_From @natemcmaster on Monday, August 20, 2018 10:48:52 AM_

It looks like the build currently disables building symbols for osx-x64. There are osx symbols for Microsoft.NETCore.App. We should look into produce symbols for the aspnetcore shared runtime as well.

_Copied from original issue: aspnet/Universe#1330_

**Comment by Eilon** [comment]
Apparently not needed. @natemcmaster will explain why.

**Comment by natemcmaster** [comment]
No action is required here. The symbols generation that is disabled for macOs is for **crossgen** symbols (.ni.pdb). These are only used by profilers, which coreclr does not support for macOS. The regular, portable PDB's that we already produce and push to symbweb are sufficient for debuggers running on the macOS shared framework.
