### ISSUE TITLE
Remove un-needed instances of MicrosoftNETCoreApp21PackageVersion etc

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3649]
_From @ryanbrandenburg on Monday, May 7, 2018 1:20:43 PM_

When moving to netcoreapp2.2 we started out trying to remove any instances of `MicrosoftNETCoreApp21PackageVersion` and `MicrosoftNETCoreApp20PackageVersion` that weren't needed anymore, but doing the logic for that across 50 repos was bogging down the rest of the work, and they weren't hurting anything, so we stopped trying to enforce that.

This item tracks the work of going back and removing that kind of unused thing, including `DotNetCoreRuntime` , `RuntimeFrameworkVersion` and more.

_Copied from original issue: aspnet/Universe#1153_

**Comment by Eilon** [comment]
@ryanbrandenburg / @natemcmaster - anything left to do here? I couldn't find `MicrosoftNETCoreApp21PackageVersion` or `MicrosoftNETCoreApp20PackageVersion` in this repo anymore.

**Comment by natemcmaster** [comment]
Nope, this was incidentally fixed with #6461 and mondo repo merges.
