### ISSUE TITLE
Reduce size of the nuget fallback folder

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3650]
_From @natemcmaster on Friday, April 27, 2018 3:19:18 PM_

The NuGet fallback folder for 2.1 is a whopping 1.01 GB once expanded on disk. This includes lots of packages that should be unnecessary to *execute* a .NET Core 2.1 application, but are still required to *restore* a .NET Core 2.1 application.

This includes:
 - multiple copies of the same package (Newtonsoft.Json 9, 10, and 11)
 - multiple versions of NETStandard.Library (1.6.0, 1.6.1, and 2.0.3)
 - a bunch of runtime.native.* specific packages. In theory, these should only be consumed when users are producing a self-contained app, but this is out of scope for the offline cache
 - 670 MB of .xml docs
 - 147 MB of .nupkg files (why are they needed -- the contents of the .nupkg have already been unzipped)

Result:

 - bloated Docker images
 - longer first-run experience required to expand all these files
 - wasted disk space on CI machines (xml docs are typically only used by IDEs)

## More details

A peek inside. Here are the packages that consume the most disk space:

<img src="https://user-images.githubusercontent.com/2696087/39387258-7b511e36-4a2d-11e8-9233-478ecbd331c8.png" width="500" />

Also, here is a breakdown of the files inside:

<img src="https://user-images.githubusercontent.com/2696087/39387271-8bbaca74-4a2d-11e8-9bbb-a4a79cf845fa.png" width="350" />

Here are all the runtime.* specific nupkgs inside

<img src="https://user-images.githubusercontent.com/2696087/39387309-c0825f56-4a2d-11e8-8cf7-f978953a50f5.png" width="400" />

_Copied from original issue: aspnet/Universe#1124_

**Comment by natemcmaster** [comment]
This was completed with https://github.com/aspnet/AspNetCore/pull/4061, which reduces the size of the LZMA to about 20 MB. We will continue to make it even smaller with #3610
