### ISSUE TITLE
Run Universe external dependency check on every PR in each repo

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3651]
_From @Eilon on Friday, April 13, 2018 2:48:28 PM_

This will find errors such as mismatched dependencies, including 3rd party packages.

Can also automate checking if OSS approval is registered via some magical script that @anurse knows about.

_Copied from original issue: aspnet/Universe#1071_

**Comment by natemcmaster** [comment]
@Eilon is this basically a duplicate of https://github.com/aspnet/AspNetCore-Internal/issues/1648?

**Comment by Eilon** [comment]
Not quite a dup of that one; more a dup of https://github.com/aspnet/AspNetCore-Internal/issues/1254. So either way, closing this.
