### ISSUE TITLE
Crossgen the linux-arm, linux-arm64 and linux-musl shared runtime

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3652]
_From @natemcmaster on Thursday, April 12, 2018 8:22:54 AM_

Currently, the linux-arm shared runtime is not preoptimized via crossgen. This was not added in the first round because

- we currently lack the infrastructure to run crossgen via CI
- did not have time to validate a crossgen version works correctly
- the value of crossgen perf for linux-arm as not clear (we have a hunch, but did not do any perf tests)

_Copied from original issue: aspnet/Universe#1061_

**Comment by aspnet-hello** [comment]
_From @sdmaclea on Thursday, April 26, 2018 3:38:05 PM_

FWIW crosscomponent crossgen has been added to the runtime packages.

for arm32 it is a x86_arm package, so this can currently be run on x86 to crossgen for arm32.  @echesakovMSFT was working on getting crossgen support for x64_arm as well.  

x64_arm64 crosscomponent crossgen is included in the linux-arm64 runtime.  cli is using this to crossgen in the master branch (for 2.2).

**Comment by muratg** [comment]
@JunTaoLuo was this done already?

**Comment by natemcmaster** [comment]
By the way @JunTaoLuo, @livarcocc said he can give you pointers how to set this up. They enabled crossgen for linux-arm SDK builds a while ago.

**Comment by livarcocc** [comment]
https://github.com/dotnet/cli/pull/9011/files

**Comment by muratg** [comment]
Thanks @livarcocc!

**Comment by JunTaoLuo** [comment]
The task of adding crossgen for linux-arm in 2.2 has been completed.

In 3.0, we'll still need to enable crossgen for the following:
- [ ] linux-arm
- [ ] linux-arm64
- [ ] linux-musl-x64

**Comment by JunTaoLuo** [comment]
@livarcocc FYI all aspnetcore shared frameworks are now crossgen'ed. I'm not sure if there is any reactionary work required on your side for this.
