### ISSUE TITLE
Refactor LZMA and installers targets into individual project builds

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3653]
_From @natemcmaster on Tuesday, February 27, 2018 11:40:11 AM_

Prototype code:
https://github.com/aspnet/Universe/blob/23de03147dc13dc9655882d77f5e21229f5ea168/src/PackageArchive/PackageArchive.targets
https://github.com/aspnet/Universe/tree/23de03147dc13dc9655882d77f5e21229f5ea168/src/Installers

Refactor the targets for building the LZMA, installers (debian, rpm), and tarballs into individual projects instead of repo.targets

_Copied from original issue: aspnet/Universe#923_

**Comment by natemcmaster** [comment]
Finished in https://github.com/aspnet/AspNetCore/pull/3866
