### ISSUE TITLE
Evaluate obsolete APIs from 2.2 and consider removing them in 3.0.0

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3654]
_From @Eilon on Thursday, January 11, 2018 11:54:54 AM_

In theory, when we start working on 3.0.0, we should delete all APIs that have been marked as `[Obsolete]`. There could be exceptions to that, but we should at least look.

_Copied from original issue: aspnet/Universe#776_

**Comment by aspnet-hello** [comment]
_From @davidfowl on Thursday, January 11, 2018 12:04:43 PM_

👍

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, January 11, 2018 1:21:50 PM_

cc @DamianEdwards as well.

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, January 11, 2018 1:22:01 PM_

And credit to @kichalla for the idea 😄

**Comment by aspnet-hello** [comment]
_From @rynowak on Sunday, January 14, 2018 5:40:50 PM_

That's a cool original idea. Bravo @kichalla

**Comment by Eilon** [comment]
Here's everything marked obsolete in 'master' in this repo:

* https://github.com/aspnet/AspNetCore/blob/master/src/Antiforgery/src/AntiforgeryOptions.cs#L99 :        [Obsolete("This property is obsolete and will be removed in a future version. The recommended alternative is " + nameof(Cookie) + "." + nameof(CookieBuilder.Name) + ".")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Antiforgery/src/AntiforgeryOptions.cs#112 :        [Obsolete("This property is obsolete and will be removed in a future version. The recommended alternative is " + nameof(Cookie) + "." + nameof(CookieBuilder.Path) + ".")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Antiforgery/src/AntiforgeryOptions.cs#123 :        [Obsolete("This property is obsolete and will be removed in a future version. The recommended alternative is " + nameof(Cookie) + "." + nameof(CookieBuilder.Domain) + ".")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Antiforgery/src/AntiforgeryOptions.cs#142 :        [Obsolete("This property is obsolete and will be removed in a future version. The recommended alternative is to set " + nameof(Cookie) + "." + nameof(CookieBuilder.SecurePolicy) + ".")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Json/JsonUtil.cs#L12 :    [Obsolete("Use Microsoft.JSInterop.Json instead.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Json/JsonUtil.cs#L20 :        [Obsolete("Use Microsoft.JSInterop.Json.Serialize instead.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Json/JsonUtil.cs#L30 :        [Obsolete("Use Microsoft.JSInterop.Json.Deserialize<T> instead.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http/src/HttpContextFactory.cs#L11 :    [Obsolete("This is obsolete and will be removed in a future version. Use DefaultHttpContextFactory instead.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/DefaultInlineConstraintResolver.cs#L27 :        [Obsolete("This constructor is obsolete. Use DefaultInlineConstraintResolver.ctor(IOptions<RouteOptions>, IServiceProvider) instead.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/IRouteValuesAddressMetadata.cs#L13 :    [Obsolete("Route values are now specified on a RoutePattern.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/RouteValuesAddressMetadata.cs#L16 :    [Obsolete("Route values are now specified on a RoutePattern.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/Tree/TreeRouteBuilder.cs#L38 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended " +
* https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Core/src/BuilderExtensions.cs#L24 :        [Obsolete(
* https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/CORS/src/Infrastructure/CorsService.cs#L29 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/Diagnostics/src/WelcomePage/Views/Obsolete/WelcomePage.cs#L17 :    [Obsolete("This type is for internal use only and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/StaticFiles/src/StaticFileResponseContext.cs#L15 :        [Obsolete("Use the constructor that passes in the HttpContext and IFileInfo parameters: StaticFileResponseContext(HttpContext context, IFileInfo file)", false)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/WebSockets/src/WebSocketMiddleware.cs#L51 :        [Obsolete("This constructor has been replaced with an equivalent constructor which requires an ILoggerFactory.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Abstractions/Formatters/OutputFormatterCanWriteContext.cs#L24 :        [Obsolete("This constructor is obsolete and will be removed in a future version. Please use the constructor taking a HttpContext instead.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DefaultApiDescriptionProvider.cs#L39 :        [Obsolete("This constructor is obsolete and will be removed in a future release.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DefaultApiDescriptionProvider.cs#L57 :        [Obsolete("This constructor is obsolete and will be removed in a future release.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/CompatibilityVersion.cs#L46 :        [Obsolete("This " + nameof(CompatibilityVersion) + " value is obsolete. The recommended alternatives are " +
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/CompatibilityVersion.cs#L58 :        [Obsolete("This " + nameof(CompatibilityVersion) + " value is obsolete. The recommended alternatives are " +
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/CompatibilityVersion.cs#L75 :        [Obsolete("This " + nameof(CompatibilityVersion) + " value is obsolete. The recommended alternatives are " +
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Formatters/FormatFilter.cs#L28 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/LocalRedirectResult.cs#L109 :        [Obsolete("This implementation will be removed in a future release, use ExecuteResultAsync.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/ArrayModelBinder.cs#L27 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/ByteArrayModelBinder.cs#L23 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/CollectionModelBinder.cs#L33 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/ComplexTypeModelBinder.cs#L33 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/DecimalModelBinder.cs#L28 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/DictionaryModelBinder.cs#L31 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/DoubleModelBinder.cs#L28 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/FloatModelBinder.cs#L28 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/FormCollectionModelBinder.cs#L28 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/FormFileModelBinder.cs#L29 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/HeaderModelBinder.cs#L27 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/KeyValuePairModelBinder.cs#L30 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/SimpleTypeModelBinder.cs#L27 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Metadata/ModelAttributes.cs#L22 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative is " + nameof(ModelAttributes) + "." + nameof(GetAttributesForType) + ".")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Metadata/ModelAttributes.cs#L35 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative is " + nameof(ModelAttributes) + "." + nameof(GetAttributesForProperty) + ".")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ModelBinderFactory.cs#L37 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L33 :        [Obsolete("This constructor is obsolete and will be removed in a future version. The recommended alternative"
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L112 :        [Obsolete("This method overload is obsolete and will be removed in a future version. The recommended " +
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L139 :        [Obsolete("This method overload is obsolete and will be removed in a future version. The recommended " +
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/RedirectResult.cs#L119 :        [Obsolete("This implementation will be removed in a future release, use ExecuteResultAsync.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/RedirectToActionResult.cs#L186 :        [Obsolete("This implementation will be removed in a future release, use ExecuteResultAsync.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/RedirectToPageResult.cs#L225 :        [Obsolete("This implementation will be removed in a future release, use ExecuteResultAsync.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/RedirectToRouteResult.cs#L178 :        [Obsolete("This implementation will be removed in a future release, use ExecuteResultAsync.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Routing/KnownRouteValueConstraint.cs#L21 :        [Obsolete("This constructor is obsolete. Use KnownRouteValueConstraint.ctor(IActionDescriptorCollectionProvider) instead.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/ProblemDetails21Wrapper.cs#L16 :    [Obsolete("This type is deprecated and will be removed in a future version")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/ValidationProblemDetails21Wrapper.cs#L14 :    [Obsolete("This type is deprecated and will be removed in a future version")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/XmlDataContractSerializerInputFormatter.cs#L36 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/XmlDataContractSerializerInputFormatter.cs#L58 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/XmlSerializerInputFormatter.cs#L35 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/XmlSerializerInputFormatter.cs#L55 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.NewtonsoftJson/NewtonsoftJsonInputFormatter.cs#L51 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.NewtonsoftJson/NewtonsoftJsonInputFormatter.cs#L74 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.NewtonsoftJson/NewtonsoftJsonInputFormatter.cs#L100 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.NewtonsoftJson/NewtonsoftJsonPatchInputFormatter.cs#L33 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.NewtonsoftJson/NewtonsoftJsonPatchInputFormatter.cs#L55 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.NewtonsoftJson/NewtonsoftJsonPatchInputFormatter.cs#L81 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/CompiledViewDescriptor.cs#L89 :        [Obsolete("Use Item instead. RazorViewAttribute has been superseded by RazorCompiledItem and will not be used by the runtime.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/RazorViewAttribute.cs#L8 :    [Obsolete("This attribute has been superseded by RazorCompiledItem and will not be used by the runtime.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs#L17 :    [Obsolete("This type is obsolete and will be removed in a future version. See " + nameof(IRazorCompiledItemProvider) + " for alternatives.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/PageArgumentBinder.cs#L10 :    [Obsolete("This type is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/RazorPageAdapter.cs#L22 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/RazorPageAttribute.cs#L9 :    [Obsolete("This attribute has been superseded by RazorCompiledItem and will not be used by the runtime.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/ImageTagHelper.cs#L39 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/LinkTagHelper.cs#L106 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/ScriptTagHelper.cs#L89 :        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.ViewFeatures/CookieTempDataProviderOptions.cs#L69 :        [Obsolete("This property is obsolete and will be removed in a future version. The recommended alternative is " + nameof(Cookie) + "." + nameof(CookieBuilder.Path) + ".")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.ViewFeatures/CookieTempDataProviderOptions.cs#L80 :        [Obsolete("This property is obsolete and will be removed in a future version. The recommended alternative is " + nameof(Cookie) + "." + nameof(CookieBuilder.Domain) + ".")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.ViewFeatures/CookieTempDataProviderOptions.cs#L91 :        [Obsolete("This property is obsolete and will be removed in a future version. The recommended alternative is " + nameof(Cookie) + "." + nameof(CookieBuilder.Name) + ".")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Cookies/src/CookieAppBuilderExtensions.cs#L19 :        [Obsolete("UseCookieAuthentication is obsolete. Configure Cookie authentication with AddAuthentication().AddCookie in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Cookies/src/CookieAppBuilderExtensions.cs#L31 :        [Obsolete("UseCookieAuthentication is obsolete. Configure Cookie authentication with AddAuthentication().AddCookie in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Facebook/src/FacebookAppBuilderExtensions.cs#L19 :        [Obsolete("UseFacebookAuthentication is obsolete. Configure Facebook authentication with AddAuthentication().AddFacebook in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Facebook/src/FacebookAppBuilderExtensions.cs#L31 :        [Obsolete("UseFacebookAuthentication is obsolete. Configure Facebook authentication with AddAuthentication().AddFacebook in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Google/src/GoogleAppBuilderExtensions.cs#L19 :        [Obsolete("UseGoogleAuthentication is obsolete. Configure Google authentication with AddAuthentication().AddGoogle in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Google/src/GoogleAppBuilderExtensions.cs#L31 :        [Obsolete("UseGoogleAuthentication is obsolete. Configure Google authentication with AddAuthentication().AddGoogle in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerAppBuilderExtensions.cs#L19 :        [Obsolete("UseJwtBearerAuthentication is obsolete. Configure JwtBearer authentication with AddAuthentication().AddJwtBearer in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerAppBuilderExtensions.cs#L31 :        [Obsolete("UseJwtBearerAuthentication is obsolete. Configure JwtBearer authentication with AddAuthentication().AddJwtBearer in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/MicrosoftAccount/src/MicrosoftAccountAppBuilderExtensions.cs#L19 :        [Obsolete("UseMicrosoftAccountAuthentication is obsolete. Configure MicrosoftAccount authentication with AddAuthentication().AddMicrosoftAccount in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/MicrosoftAccount/src/MicrosoftAccountAppBuilderExtensions.cs#L31 :        [Obsolete("UseMicrosoftAccountAuthentication is obsolete. Configure MicrosoftAccount authentication with AddAuthentication().AddMicrosoftAccount in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/OAuth/src/OAuthAppBuilderExtensions.cs#L19 :        [Obsolete("UseOAuthAuthentication is obsolete. Configure OAuth authentication with AddAuthentication().AddOAuth in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/OAuth/src/OAuthAppBuilderExtensions.cs#L31 :        [Obsolete("UseOAuthAuthentication is obsolete. Configure OAuth authentication with AddAuthentication().AddOAuth in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectAppBuilderExtensions.cs#L19 :        [Obsolete("UseOpenIdConnectAuthentication is obsolete. Configure OpenIdConnect authentication with AddAuthentication().AddOpenIdConnect in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectAppBuilderExtensions.cs#L31 :        [Obsolete("UseOpenIdConnectAuthentication is obsolete. Configure OpenIdConnect authentication with AddAuthentication().AddOpenIdConnect in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Twitter/src/TwitterAppBuilderExtensions.cs#L19 :        [Obsolete("UseTwitterAuthentication is obsolete. Configure Twitter authentication with AddAuthentication().AddTwitter in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Twitter/src/TwitterAppBuilderExtensions.cs#L31 :        [Obsolete("UseTwitterAuthentication is obsolete. Configure Twitter authentication with AddAuthentication().AddTwitter in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.", error: true)]
* https://github.com/aspnet/AspNetCore/blob/master/src/Shared/Diagnostics/AttributeValue.cs#L8 :    [Obsolete("This type is for internal use only and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Shared/Diagnostics/BaseView.cs#L20 :    [Obsolete("This type is for internal use only and will be removed in a future version.")]
* https://github.com/aspnet/AspNetCore/blob/master/src/Shared/Diagnostics/HelperResult.cs#L12 :    [Obsolete("This type is for internal use only and will be removed in a future version.")]

**Comment by Eilon** [comment]
@mkArtakMSFT / @muratg / @ajcvickers - please review the list above and take appropriate action on the items.

**Comment by muratg** [comment]
@Eilon I reacted to 3 of the items that are in my areas, and filed bugs for them. (Nice work BTW!)

**Comment by Eilon** [comment]
Need to check again in the release/2.2 branch and see what's left.

**Comment by Eilon** [comment]
I reviewed all current master Obsolete attributes in our product code repos (EF, AspNetCore, Tooling, and Extensions) and none are remnants from 2.2 So, we're good to go for 3.0!
