### ISSUE TITLE
Change Antares test to use site extensions package as an artifact reference

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3655]
_From @pakrym on Thursday, January 11, 2018 10:20:29 AM_

Right now build pushed the package to aspnetcore-dev myget feed and test has to wait until package appears. This has to change so Antares test configuration pushes the package to Azure blob feed and uses that feed for testing.

_Copied from original issue: aspnet/Universe#772_

**Comment by aspnet-hello** [comment]
_From @pakrym on Thursday, January 11, 2018 10:22:05 AM_

/cc @natemcmaster

**Comment by muratg** [comment]
We'll revisit this at a later time.
