### ISSUE TITLE
Add "don't touch this" doc to all pubternal types in all packages

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3656]
_From @Eilon on Wednesday, January 10, 2018 10:52:11 AM_

We need to add docs to all our pubternal types (i.e. `public` types in a `.Internal` namespace) to indicate that they are not supported.

I suggest writing a tool that uses Roslyn to insert a comment for all applicable types:
```c#
///   <summary>
///       This API supports infrastructure and is not intended to be used directly
///       from your code. This API may change or be removed in future releases.
///   </summary>
```

This will also make it easier in the future to enable the "doc comments required" C# compiler error because we *would* have docs for all accessible types.

For example, here's what EF Core does: https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore/Internal/Graph.cs#L9-L24

```c#
///   <summary>
///       This API supports the Entity Framework Core infrastructure and is not intended to be used
///       directly from your code. This API may change or be removed in future releases.
///   </summary>
```

- Ⓜ️🌊🔨

_Copied from original issue: aspnet/Universe#767_

**Comment by aspnet-hello** [comment]
_From @rynowak on Wednesday, January 10, 2018 11:23:59 AM_

Can we makethings proper internal and leave pubternal for when it's actually required or valuable?

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, January 10, 2018 12:03:30 PM_

You mean even in 2.1? Per our own rules that isn't a breaking change, so we certainly *could*...

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Wednesday, January 10, 2018 12:22:47 PM_

Can we also stop setting NoWarn CS1591? Devs regularly miss documenting API -- even normal API -- because we suppress this warning in many of our projects.

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, January 10, 2018 1:08:10 PM_

@natemcmaster yup that's mentioned in the initial description 😄

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Wednesday, January 10, 2018 1:10:36 PM_

Re-read my question - don't think I was clear. I actually meant something stronger. Could we _forbid_ use of NoWarn CS1591?

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, January 11, 2018 11:07:31 AM_

Oh - well, once we get all the docs actually cleaned up, yes, we'd consider banning it. Though, for some prototype code, or local dev work, we might not want to be quite so strict.

**Comment by natemcmaster** [comment]
Triage team: @Eilon can you provide more direction here for what should be done? e.g. should we enforce this via tooling and PR checks?

**Comment by Pilchie** [comment]
@davidfowl / @rynowak How far did you get on eliminating pubternal altogether? Is this now at the point where it's feasible?

**Comment by davidfowl** [comment]
Yep everything should be internal now and what remains pubternal is public. There are a few API that need this annotation maybe under 10

**Comment by Eilon** [comment]
So enable `CS1591` and see what's left?
