### ISSUE TITLE
Make running Universe locally easier

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3657]
_From @ryanbrandenburg on Wednesday, May 24, 2017 1:44:22 PM_

We would like to make it easier to run Universe on your local machine for the purpose of testing cross-repo changes. I see this as being a couple different steps:

1. Try to build Universe locally, note what steps are required to make it work and document them.
2. Point Universe at a local repo with a breaking change then do step 1 again.
3. Ideally make builds incremental to save build time (right now it can take ~30 minutes).

CC @mikeharder and @Tratcher

_Copied from original issue: aspnet/Universe#512_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, May 24, 2017 1:48:05 PM_

The instructions are here: https://github.com/aspnet/universe#verifying-cross-repo-changes
It was the lack of incremental builds that was killing me.

**Comment by aspnet-hello** [comment]
_From @mikeharder on Wednesday, May 24, 2017 1:56:50 PM_

For the local build, I think we should have instructions of exactly what is required starting from a clean Win10 VM:

* VS: Which channel to install and which workloads and options to select.
* Other Dependencies: Git for Windows, NPM for SignalR, etc.  I would standardize on Chocolatey to install any dependencies with available packages.
* What repo to clone, what command(s) to run the build, etc.

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Friday, June 30, 2017 2:13:24 PM_

Dupe of #495 ?

**Comment by aspnet-hello** [comment]
_From @ryanbrandenburg on Friday, June 30, 2017 2:38:11 PM_

Not entirely, this also encompasses the work of making sure Universe works locally, and that the steps we advise people to take to make that happen are up to date.

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Friday, June 30, 2017 2:46:38 PM_

+:100:. Working with Universe has been especially frustrating lately. I'm trying to verify that my cross-repo changes for the last few hours. Each time I run, a different piece of Universe fails, usually due to floating versions. Even with the `BuildGraphOf` property set, it takes at least 20 minutes to run each time because the errors I'm working at are at the tail end of the build graph.

**Comment by aspnet-hello** [comment]
_From @smitpatel on Friday, June 30, 2017 2:53:42 PM_

You can achieve incremental build by modifying `buildgraph.proj`. It requires to remove certain targets & incrementally remove projects from the file as their build succeeds and packages are dropped in artifacts.

@pranavkm knows exact steps needed but I have used it while reworking API check and it was pretty decent to make cross-repo changes since it built every repo incrementally.

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Friday, June 30, 2017 2:56:43 PM_

Yeah, I've done the same thing, esp to avoid re-cloning the repos. Also,
I usually end up changing `Repositories.props` to drop projects that I know are unaffected, yet would get built each time anyways (in particular, EF). 

Incremental should be default IMO. We can add `/t:Clean` for when you actually want to clean.

**Comment by aspnet-hello** [comment]
_From @smitpatel on Friday, June 30, 2017 2:58:58 PM_

I avoided re-builds. (Had to do it else PinVersion crashed due to multiple built versions available.). Again I don't remember steps, Pranav knows them. But once a repo is built and nupkg created, you can avoid rebuilding it.

**Comment by aspnet-hello** [comment]
_From @pranavkm on Friday, June 30, 2017 3:20:48 PM_

It needs a bit of refactoring to have a inner-loop. We hacked things on @smitpatel's box by just skipping a bunch of steps (which are part of the global build) but get in the way of iterative builds.

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, August 22, 2017 4:46:53 PM_

FYI the incremental build was discussed in https://github.com/aspnet/Universe/issues/495, which I've closed because this bug tracks the overall work.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Tuesday, May 22, 2018 10:53:59 AM_

https://github.com/aspnet/Coherence-Signed/issues/468

**Comment by natemcmaster** [comment]
Closing as I believe build.cmd without arguments should successfully compile in most scenarios. Tests may not pass, but that's a separate issue.

There are a few other specific things we plan to do to make the repo easier to work in. See https://github.com/aspnet/AspNetCore/issues/4246 and https://github.com/aspnet/AspNetCore/issues/4247
