### ISSUE TITLE
Give us an official module system in asp.net core: Microsoft.AspNetCore.Modules.Abstraction

### ISSUE THREAD

**Issue by John0King** [aspnet/AspNetCore#3665]
An official modules system in asp.net core.
support features:
1. one project multiple module for small site (one of the implementation)
2. separate project for large site (one of the implementation)
3. MVC and Route support

There already a greate module system in OrchardCore,  and I hope asp.net core have a build in module system.

and there are some feature need to consider support module system. for example:
`IApplicationBuilder.New()`  may have an override  `IApplicationBuilder.New(PropertiesShareType shareType)` 

A module system will be a good isolation for DI , that will help things like  multiple authentication/authorization  in same site

**Comment by Eilon** [comment]
@John0King is there a reason not to use the OrchardCore module system? Ultimately @sebastienros who works on OrchardCore is on the ASP.NET team, so if we were to build something into ASP.NET, it would probably be very similar to OrchardCore anyway 😄

**Comment by John0King** [comment]
1. the module  system will be part of asp.net core instead of OrchardCore 
2.  It's will be much easier for new developer to lean and use the Modular Architecture (The Microsoft recommendation and doc support).
4. Maybe some feature in asp.net core will have better support for module system.
3.  More out of the box module will release to nuget.

I'm leaning about the OrchardCore ,

and for `is there a reason not to use the OrchardCore module system?` . There are absolutly no reason to not use the  OrchardCore module system . but a  build in module system in asp.net core just make asp.net core better.  and  obviously there are more people know asp.net core than OrchardCore

**Comment by Eilon** [comment]
What if we had proper docs on ASP.NET Core's doc site showing people recommended patterns that used OrchardCore's module system?

Ultimately we can't build-in everything into ASP.NET Core - there is a lot of great work done outside of ASP.NET Core that we want to leverage. That's why we chose Json.NET, IdentityServer, and other great projects, instead of building them ourselves (not that we didn't *try* sometimes).

**Comment by John0King** [comment]
@Eilon 
> What if we had proper docs on ASP.NET Core's doc site showing people recommended patterns that used OrchardCore's module system

Agree , but I still think this shoud be an abstraction of asp.net-core and other framework implement it. (like the `ILogger`).
Can we leave this open , so others can say like or dislike ?

**Comment by Eilon** [comment]
Certainly. I can say with great certainty that for the foreseeable future the guidance is to a project such as OrchardCore, which has done a lot of the heavy lifting (and there are probably other good module systems out there as well).

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
