### ISSUE TITLE
Documentation Clarity in the "CookieSecurePolicy" in the AntiForgeryOptions

### ISSUE THREAD

**Issue by akshita31** [aspnet/AspNetCore#3670]
The [AntiForgeryOptions ](https://github.com/aspnet/Antiforgery/blob/master/src/Microsoft.AspNetCore.Antiforgery/AntiforgeryOptions.cs#L32) say that the default CookieSecurePolicy in "None". However, the ["CookieSecurePolicy" enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.cookiesecurepolicy?view=aspnetcore-2.1) says that the default value is "SameAsRequest". While working with the project I navigated to the "CookieSecurePolicy" and assumed that the default must be "SameAsRequest".

I am not sure whether this is really an issue or it is a common scenario where we create default objects with the enum types that don't use the default enum value, but I thought it might be worth to bring to your notice if it somehow got ignored.

**Comment by Tratcher** [comment]
The [docs](https://github.com/aspnet/HttpAbstractions/blob/d17d9155c7d2677a2eba4075fc472229266ecf19/src/Microsoft.AspNetCore.Http.Abstractions/CookieSecurePolicy.cs#L18) on CookieSecurePolicy are outdated, they were written at a time when that enum was only used in the authentication components. AntiForgery has chosen different defaults.

**Comment by TKharaishvili** [comment]
@Tratcher sent a PR for this - https://github.com/aspnet/AspNetCore/pull/4542 but some of the CI tasks were unsuccessful, however this is only just a comment update and it doesn't require a build to check whether everything's fine.

I'm not sure how to rerun CI or what else to do from this point forward so I'd appreciate some advice.

Thanks.
