### ISSUE TITLE
ViewComponent inside form and Model Biding

### ISSUE THREAD

**Issue by ciacco85** [aspnet/AspNetCore#3673]
Using a Model like
```c#
class A
{
B b {get; set;}
}
class B
{
string testString{get;set;}
}
```

and passing the b property to the viewcomponent

```html
<form aspAction='testMethod'>
<vc:myModel model="@(Model.b)"></vc:myModel>
</form>
```

when posting the form, the model property testString is alwayse null.
I've found a workaround, after a long experience with MVC, inside the viewcomponent, adding the "b" inside name

`<input asp-for="testString" name="b.testString" class="form-control" />`

but in this situation, a ViewComponent should know something about the class in wich the model is placed...two object coupled with no relationship is not that good
Should I use the editor template o change the approch?? ViewComponent are so powerful.
Thanks for your great work!!!

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8625
