### ISSUE TITLE
Recognize WebAssembly wasm files as a known file type

### ISSUE THREAD

**Issue by kumpera** [aspnet/AspNetCore#3681]
It would be great if asp.net would recognize `.wasm` files. It took me, an aspnet noob, some debugging to realize that I had to set `StaticFileOptions::ServeUnknownFileTypes` for aspnet to serve a page using WebAssembly correctly.

This would be a minor quality-of-life improvement for people working with Blazor. 😉 

### Is your feature request related to a problem? Please describe.
It's a minor nuisance

### Describe the solution you'd like
Recognize `.wasm` as a known file type.

### Describe alternatives you've considered
Set the `ServeUnknownFileTypes` property when configuring your app with `UseStaticFiles`.

**Comment by Tratcher** [comment]
@danroth27 looks like you set `fileExtension=".wasm" mimeType="application/wasm"` in [blazor](https://github.com/aspnet/Blazor/blob/f72e03f8fe46735436f80950cac49808fc3e3c11/src/Microsoft.AspNetCore.Blazor.Build/targets/Standalone.Web.config#L12). Should we add that mapping to StaticFiles?

**Comment by Tratcher** [comment]
@kumpera FYI you can also add your own [mappings](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.1&tabs=aspnetcore2x#fileextensioncontenttypeprovider) rather than use ServeUnknownFileTypes.

**Comment by kumpera** [comment]
@Tratcher thanks for the suggestion.

This is for a test harness, so I assume it's save to use `ServeUnknownFileTypes`.

**Comment by Tratcher** [comment]
Are you also setting DefaultContentType?

**Comment by danroth27** [comment]
> @danroth27 looks like you set `fileExtension=".wasm" mimeType="application/wasm"` in [blazor](https://github.com/aspnet/Blazor/blob/f72e03f8fe46735436f80950cac49808fc3e3c11/src/Microsoft.AspNetCore.Blazor.Build/targets/Standalone.Web.config#L12). Should we add that mapping to StaticFiles?

Yes, I think that would make sense.

**Comment by danroth27** [comment]
@SteveSandersonMS

**Comment by Tratcher** [comment]
@muratg @shirhatti this is related to https://github.com/aspnet/BasicMiddleware/issues/376, but for StaticFiles. Also XS.
