### ISSUE TITLE
Razor Pages using EF Scaffolding bug for bool properties of the data model class

### ISSUE THREAD

**Issue by Mimisss** [aspnet/AspNetCore#3688]
### Describe the bug
The *Razor Pages using EF (CRUD)* scaffolding template of Visual Studio 2017 fails to properly reference the bool properties of the data model class in the generated html helper code of the CRUD pages. 

For example, having the following data model class:

```
public class DataModel 
{
    public bool IsFoo { get; set; }    
}
```

the scaffolding template create the the below *Create* page and page model:

```
public class CreateModel : PageModel
{
    [BindProperty]
    public DataModel DataModel { get; set; }
}
```

```
<div class="form-group">
    <div class="checkbox">
        <label>
            <input asp-for="DataModel.IsFoo" /> @Html.DisplayNameFor(model => model.IsFoo)
        </label>
    </div>
</div>
```

### To Reproduce
1. Using Visual Studio Community 2017 Version 15.8.6 and ASP.NET Core 2.1
2. Create a ASP.NET Core Web Application 
3. Add the `DataModel` class shown in the above example
4. Right click on Pages folder > Add > New Scaffolded Item > Razor Pages using EF (CRUD)
5. In the dialog box, select `DataModel` as the model class and create a new Data context class
6. Build the project and see the error

Same applies to *Edit* and *Details* pages.

### Expected behavior
Based on the above example, the reference to the bool property of the binding property of the page class should be:

`@Html.DisplayNameFor(model => model.DataModel.IsFoo)` instead of

`@Html.DisplayNameFor(model => model.IsFoo)`

### Additional context
output of `dotnet --info`:
> .NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

> Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

> Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

> .NET Core SDKs installed:
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

> .NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#920
