### ISSUE TITLE
This issue was moved to aspnet/Identity#2021

### ISSUE THREAD

**Issue by terrainkognito2017** [aspnet/AspNetCore#3690]
_Originally posted by @Eilon in https://github.com/aspnet/AspNetCore/issues/3675#issuecomment-431422124_

Hell! I see that ID is text. I ask why? It takes up more space, it is slower indexed, it works worse when filtering. Why do you make this field as text?

**Comment by poke** [comment]
Why are you opening a new issue about this? As noted in the original issue #3675, it was moved to aspnet/Identity#2021. It’s not closed, so you can add additional comments there.

**Comment by terrainkognito2017** [comment]
Sorry, this is the first time I use the Issues section. I thought that my question was closed.

**Comment by terrainkognito2017** [comment]
Thanks
