### ISSUE TITLE
Microsoft.AspNetCore.App version flip in Mac Visual Studio

### ISSUE THREAD

**Issue by danmosemsft** [aspnet/AspNetCore#3691]
_From @ptletski on October 21, 2018 15:59_

I have an AspNetCore Web App project in Mac VS that is Restoring version 2.1.1 of Microsoft.AspNetCore.App every time I open the solution. I update to v2.1.5 and that works. When close and reopen the solution, the restoration process puts it back to version 2.1.1. Here are the dependencies listed in the deps.json file:

         "Microsoft.AspNetCore.App": "2.1.5",
          "Microsoft.EntityFrameworkCore": "2.1.4",
          "Microsoft.EntityFrameworkCore.Design": "2.1.4",
          "Microsoft.EntityFrameworkCore.Sqlite": "2.1.4",
          "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.1.6",
          "Microsoft.EntityFrameworkCore.Tools": "2.1.4",
          "Microsoft.NETCore.App": "2.1.0",
          "Microsoft.VisualStudio.Web.CodeGeneration.Design": "2.1.5"

Here is the csproj list:

    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Design" Version="1.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.4" />

Anyone have some insight into what is going on?

_Copied from original issue: dotnet/corefx#32942_

**Comment by Eilon** [comment]
Hi @ptletski , you should be able to drop the version entirely on the Microsoft.AspNetCore.App reference and the correct version will be selected based on the `netcoreapp2.x` version that your project is targeting.

You can learn more about the Microsoft.AspNetCore.App package here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1

cc @natemcmaster FYI

**Comment by natemcmaster** [comment]
Can you share the output of `dotnet --info`? The .NET Core SDK team made some changes in 2.2.0 Preview 3 which might have an impact on this.

If you have _not_ installed a 2.2 preview, then I can't explain why the restore result would switch from 2.1.1 to 2.1.5 when you clearly have 2.1.5 in the project. If you are seeing this shortly after making modifications to your project file, then I suspect the culprit is caching. NuGet and MSBuild attempt to do some clever caching with long-running processes, looking at file timestamps, etc., and it's possible the caches restore result is not correctly invalidated when you change your project. Try restarting Mac VS.

**Comment by ptletski** [comment]
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

Visual Studio's Opinion:

=== Visual Studio Community 2017 for Mac ===

Version 7.6.9 (build 22)
Installation UUID: d9b6a453-5884-4da4-9b41-6855e58125df
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.5
	2.1.2
	2.0.6
SDK: /usr/local/share/dotnet/sdk/2.1.403/Sdks
SDK Version: 2.1.403
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/paultletski/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Community)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706090022
Git revision: 0a0ba3c4593e9adb1c6ff6324e641036146af376
Build date: 2018-10-05 16:38:51+00
Build branch: release-7.6
Xamarin extensions: f7856b13f2c03a58e08381d3a5970bba18f5c7d7

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by natemcmaster** [comment]
Thanks for the details. I can reproduce this in VS for Mac 7.6.10. Command line restore using both Mono's `msbuild /t:Restore` and `dotnet restore` work correctly. I suspect there is something wrong in VS for Mac in the way it interprets the .csproj file.

I'm going to close this as the VS for Mac team does not track issues through GitHub. Please follow this issue instead: https://developercommunity.visualstudio.com/content/problem/365280/nuget-restores-the-wrong-version-of-microsoftaspne.html

**Comment by natemcmaster** [comment]
FYI this has been fixed in VS for Mac 7.8 Preview 1.
