### ISSUE TITLE
Add properties to override default location for shared framework installer in Windows

### ISSUE THREAD

**Issue by joeloff** [aspnet/AspNetCore#3697]
VS allows overriding the default install location. This information is passed through to the CLI, which then passes it through to the individual installers. The shared framework for ASP.NET needs to be updated to support this.

Likely two properties since the hosting bundle carries both the x86 and x64 copies.

CLI have started this work, but they'll be blocked until the shared framework is updated.

**Comment by joeloff** [comment]
@muratg FYI

**Comment by muratg** [comment]
@joeloff is this good to close? Or should we move it to preview2?

**Comment by joeloff** [comment]
Oh, I forgot to close. It's done insofar the SDK installs are concerned so we can close this for now.
