### ISSUE TITLE
Application fails to publish on 3.0 sdk docker image with "rzc discover exited with code -2147450730"

### ISSUE THREAD

**Issue by puhovalexey** [aspnet/AspNetCore#3698]
Default application from a template fails to publish on latest 3.0 sdk container with an error:

`C:\Users\ContainerAdministrator\.nuget\packages\microsoft.aspnetcore.razor.design\3.0.0-alpha1-10062\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error : rzc discover exited with code -2147450730. [c:\test\test.csproj]`

microsoft.aspnetcore.razor.design package for 3.0.0 indicates 2.x net core tool however 3.0 sdk docker image doesn't have 2.x installed
rzs.runtimeconfig.json:
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.9"
    }
  }
}
```
-----------------------------------------
### Steps to reproduce:
1. docker run --rm -ti microsoft/dotnet-nightly:3.0-sdk-nanoserver-sac2016
next command execute inside a container
2. md test && cd test
3. dotnet new mvc
4. dotnet publish --source "https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json;https://api.nuget.org/v3/index.json" (use nightly sources for asp.net core 3.0)

### Expected behavior
Publish should succeed

Diag logs: 
[1.log](https://github.com/aspnet/AspNetCore/files/2503554/1.log)

Docker Image info: 
microsoft/dotnet-nightly:3.0-sdk-nanoserver-sac2016, sha256:0465ba2b0f11f490a834906da13bea895b26abda231f95fe90407785b32b4a55

dotnet --info:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-alpha1-009642
 Commit:    8cd38e2a49

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-alpha1-009642\

Host (useful for support):
  Version: 3.0.0-preview1-27004-04
  Commit:  35a0b3f880

.NET Core SDKs installed:
  3.0.100-alpha1-009642 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-27006-1 [C:\Program Files\dotnet\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 3.0.0-preview1-27004-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Eilon** [comment]
@rynowak / @pranavkm / @NTaylorMullen - any idea on this?

BTW `-2147450730` = ‭`0x80008096‬` in case that helps.

**Comment by puhovalexey** [comment]
from what I see here https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.Razor.Design the latest version `3.0.0-alpha1-10655` has still a reference `"tfm": "netcoreapp2.0"` just like in the example I pasted in the description above.
So the answer is no, it has not been updated

**Comment by pranavkm** [comment]
> Has rzc been updated to target netcoreapp3.0

Not as yet.

**Comment by pranavkm** [comment]
Fixed via https://github.com/aspnet/Razor/issues/2696. 3.0 rzc targets `netcoreapp3.0` now.
