### ISSUE TITLE
Configure claims mapping for OAuth middleware 

### ISSUE THREAD

**Issue by joaco-espinosa** [aspnet/AspNetCore#3699]
I'm currently trying to map claims by invoking the `Microsoft.AspNetCore.Authentication.Map()` functions:

```c#
var _claimsToIgnore = new string[] { ... }

services.AddAuthentication(options =>
    .AddOAuth(options =>
    {
        ...

        options.ClaimActions.MapAllExcept(_claimsToIgnore);

        ...
    });
```

Unfortunately, the mapping rules are only applied when redefining one of the OAuth Events, `OnCreatingTicket(context)`, and explicitly invoking `context.RunClaimActions()`

On the other hand, rules are automatically run when configuring OIDC through `services.AddAuthentication.AddOpenIdConnect(context)` --> _i.e. without the need to explicitly invoke RunClaimActions()_

Questions:
1. Is this the expected behavior?
2. If so, is there a way of configuring this extention to avoid having to manually run the mapping rules?

**Comment by Tratcher** [comment]
Yes this is expected. The blocking issue is that the OAuth protocol doesn't actually provide a way to retrieve claims, only tokens. The OAuth auth handler implements all of the generic protocol components, but OnCreatingTicket needs to be overridden for each provider to actually fetch the claims. Then RunClaimActions is available for mapping the claims.   Note there are many [pre-built](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src) providers that handle this for you.

OIDC is a nice upgrade to OAuth because the protocol has a built in mechanic for retrieving claims. Thus the OIDC auth handler can retrieve and map them for you.

**Comment by joaco-espinosa** [comment]
Thank you for the prompt response

**Comment by joaco-espinosa** [comment]
Reopening this to clarify something. Based on your response and on the [suggested](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src) providers, it seems that you are referring to UserInfo Claims. However, I was referring to Claims found inside Access Tokens Payload section.

IOW, what I'm trying to accomplish, without manually invoking the `RunClaimActions()`, is the mapping and provisioning of Claims through the ClaimsPrincipal Principal.Identity object.

Is your response still the same?

**Comment by Tratcher** [comment]
> Claims found inside Access Tokens Payload section.

I don't follow, OAuth access tokens are opaque. Only OIDC specifies the token format (JWT) so you can extract information from it without 3rd party interaction.

**Comment by joaco-espinosa** [comment]
That answers it. I was referring to the particular case in which OAuth access tokens are self-contained tokens using the JWT format.

Based on your response, it seems that, since these are opaque by definition, there's no logic to detect this scenario (token being jwt-formatted) and automatically extract information to perform the mapping I was referring to.

**Comment by Tratcher** [comment]
Exactly. We try not to make any assumptions outside of the protocol.

**Comment by poke** [comment]
Note that if you receive an access token for another resource (e.g. an API), then you are not supposed to parse the access token in any way. You should just pass it on to the resource to authenticate. If you need information about the user that is authenticated using the token, then you should either call some userinfo API with that token, or use OIDC instead in which case you get an identity token that contains claims _for you_ to use.

**Comment by joaco-espinosa** [comment]
Thanks for your answers.
