### ISSUE TITLE
Add authorization based on pre-shared RSA-key

### ISSUE THREAD

**Issue by bjornpaulstrom** [aspnet/AspNetCore#3711]
We have a system where sensors collect data and upload it to a web server at regular intervalls. Data arrives from sensors which are new to the system, which the system does not know about yet. 

The REST interface has to use authorization to prevent others from adding data.

If there was an option to use a pre-shared key and get automatic authorization with annotations (ofc not bound to a user, since all/several users have the same key) it would solve this perfectly for me.

I can not use Identity with token since the system has no notion of new sensors, so a user can not be generated in advance.

**Comment by bjornpaulstrom** [comment]
The second approach, I will try that, thanks alot :)

**Comment by blowdart** [comment]
I think you'd want to go further. Sending the key as a bearer token doesn't add much here, you'd want to sign the request with the private part of the key, then send some sort of key ID, or maybe the public part in the auth header, and validate the request has been signed with the private key you expect.

But really, why use a raw key? Would a certificate not work for you? Then you use cert auth which is already a standard.

**Comment by bjornpaulstrom** [comment]
You are correct, after some investigation, 2-way TLS is what I was looking for.

**Comment by blowdart** [comment]
In that case https://github.com/blowdart/idunno.Authentication/tree/master/src/idunno.Authentication.Certificate

**Comment by blowdart** [comment]
As certificate auth seems to be the better approach, closing the issue.
