### ISSUE TITLE
2.1 projects published to IIS will silently fail HTTPS redirects and HSTS commands

### ISSUE THREAD

**Issue by joshbartley** [aspnet/AspNetCore#3713]
### Describe the bug
A change was introduced to remove the default HTTPS port of 443 in the middleware. When a default project is published to IIS, it cannot detect the HTTPS port and will not honor the redirect or HSTS settings in the Startup.cs thus making the site potentially insecure and only throw a warning, which does not appear in development since the default project template sets the https port for IIS Express.

This change was announced via https://github.com/aspnet/Announcements/issues/301

### To Reproduce
1. Using this version of ASP.NET Core 2.1
2. Create new project using VS 2017 and check "Enable HTTPS"
3. Use Visual Studio Publish to file
4. Setup IIS site with bindings for port 80 and port 443 with certificate
5. Go to the http version of the site, no redirect.

### Expected behavior
IIS and Dotnet core should be able to redirect automatically to port 443 when IIS is configured with SSL and the Startup.cs enabled redirection.

By default, the IIS Integration should be setting the HTTPS port in an environment variable, or the default new project should include a comment, similar to current comments in the project new template.

If HTTPS redirect and HSTS is enabled in the Startup.cs, an error should occur to prevent the site from launching in IIS saying the HTTPS port could not be found. Similar to when an appsettings.json file is marked required and not found.
Documentation should include these details on the following pages if no change to the behavior is made.
https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1

Below documentation should change the Note about IIS to a warning, and be more visible. 
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio

Nginx and Apache documentation includes server level configuration settings to automatically redirect http to https thus working around this issue. 

cc @blowdart per Twitter

**Comment by Tratcher** [comment]
Duplicate: https://github.com/aspnet/IISIntegration/issues/485

**Comment by Eilon** [comment]
@Tratcher should we close this as dup?
