### ISSUE TITLE
TryValidateModel throws exception when unit tested

### ISSUE THREAD

**Issue by mmulhearn** [aspnet/AspNetCore#3714]
When attempting to run a unit test against an ApiController in ASP.NET Core, TryValidateModel throws an exception that ObjectValidator is null.  When trying to set the property, I can't seem to figure out what properties should be set to what.  I can inject the DefaultObjectValidator, but it always passes, even when I purposefully set bad values to my model.

[There was a bug opened for this years ago](https://github.com/aspnet/Mvc/issues/3586) that I found but the only solution seemed to be mocking, which I don't want to do because I want the test to legit fail should I pass it bad data to ensure everything is configured correctly in the controller.

    public UserTests()
        {
            ICompositeMetadataDetailsProvider p = new DefaultCompositeMetadataDetailsProvider(new IMetadataDetailsProvider[]
            {
                new DefaultValidationMetadataProvider(),
                new DefaultBindingMetadataProvider() 
            });
            IModelMetadataProvider metadataProvider = new DefaultModelMetadataProvider(p);
            var objectValidator = new DefaultObjectValidator(metadataProvider, new List<IModelValidatorProvider>
            {
                new DefaultModelValidatorProvider()
            });

            Controller = new UserController
            {
                ObjectValidator = objectValidator
            };
        }`

Setting up a controller should be much easier than this and object validation should be initialized by default. At the very least there should be some documentation somewhere regarding how to initialize this property outside of the full request pipeline.

**Comment by mmulhearn** [comment]
I ended up creating my own IObjectModelValidator, which I'm not sure is the best approach, but it seems to work.

```
public class TestingObjectValidator : IObjectModelValidator
    {
        public ControllerBase Controller { get; set; }

        public void Validate(ActionContext actionContext, ValidationStateDictionary validationState, string prefix, object model)
        {
            var validationContext = new ValidationContext(model, null, null);
            var validationResults = new List<ValidationResult>();
            Validator.TryValidateObject(model, validationContext, validationResults, true);
            foreach (var validationResult in validationResults)
            {
                Controller.ModelState.AddModelError(validationResult.MemberNames.FirstOrDefault() ?? string.Empty, validationResult.ErrorMessage);
            }
        }
    }
```

```
public UserTests()
        {
            Controller = new UserController();
            var objectValidator = new TestingObjectValidator
            {
                Controller = Controller
            };
            Controller.ObjectValidator = objectValidator;
        }
```

I would still like to see a fix so this doesn't need to be done.  Who knows if I'm missing a configuration or edge case that is addressed in the full pipeline.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting is, @mmulhearn.
@pranavkm, is the approach taken here one we'd recommend, or is there a better way to do this?

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Mvc#8640
