### ISSUE TITLE
Overriding kestrel section

### ISSUE THREAD

**Issue by krzychu195** [aspnet/AspNetCore#3720]
Hi, 
I want to allow user to override kestrel settings like url via command line. Unfortunately all my attempts ends up adding another url to the pool instead of overriding the one specified in appsettings.json. How can I disable it when command line arguments were passed? Or be sure that command line args will do the job? Please examples :)

**Comment by Tratcher** [comment]
There's a [PreferHostingUrls](https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.AspNetCore.Hosting.Abstractions/HostingAbstractionsWebHostBuilderExtensions.cs#L150-L160) API that should work with Kestrel. We use it in the IIS reverse proxy scenario so IIS can [override](https://github.com/aspnet/IISIntegration/blob/e1f1705d11d97560c574dbe68a0b560441470f58/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L86-L87) the addresses Kestrel should listen on.

**Comment by krzychu195** [comment]
Thanks, that was what I needed.
