### ISSUE TITLE
InvalidDataException: Line length limit 100 exceeded

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#3724]
_From @thomasd3 on October 25, 2018 20:11_

When uploading data files with RestSharp to a .Net Core 2.1 REST interface, I get this error on some files:

```
System.IO.InvalidDataException: Line length limit 100 exceeded.
   at Microsoft.AspNetCore.WebUtilities.BufferedReadStream.ReadLineAsync(Int32 lengthLimit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)

```
When I do the same operation with Insomnia, I do *not* get any error, only with RestSharp.

I have read here https://stackoverflow.com/questions/44642701/microsoft-aspnetcore-webutilities-line-length-limit-100-exceeded that there is a problem with the line ending formats, but this is the only article about it.

The controller signature is very simple:

```
[HttpPost, DisableRequestSizeLimit]
public async Task<IActionResult> AddPictureAsync(
	IFormFile Picture,
	IFormFile Thumbnail,
	string Title)
{
```

and the code to send is:

```
var Request = new RestRequest("picture", Method.POST) { AlwaysMultipartFormData = true };
Request.AddHeader("SessionId", SessionId);
Request.AddFile("Picture", PhotoData.ToArray(), Photo.PhotoUrl);
Request.AddFile("Thumbnail", ThumbnailData, Photo.PhotoUrl.Replace(".jpg", "-t.jpg"));
Request.AddParameter("Title", Photo.Title ?? string.Empty, ParameterType.GetOrPost);

```

If I understand the error, it means that the data lines are longer than they should. But is there a way to inspect what is coming in? My controller doesn't even  get executed, the error happens before

_Copied from original issue: aspnet/KestrelHttpServer#3057_

**Comment by Tratcher** [comment]
This error is not related to the request size limits, but rather the form [size limits](https://github.com/aspnet/HttpAbstractions/blob/d17d9155c7d2677a2eba4075fc472229266ecf19/src/Microsoft.AspNetCore.Http/Features/FormOptions.cs). And as you say it's likely more of a formatting issue.

Fiddler or Wireshark are good tools for capturing what bytes were written to the wire. Kestrel also has a feature called [connection logging](https://github.com/aspnet/KestrelHttpServer/blob/616aeba156d617c98955e437f3283ae66206c2ba/samples/SampleApp/Startup.cs#L108-L112) for viewing the raw bytes.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
