### ISSUE TITLE
Assembly name is compiling to lower-case in netcoreapp2.1 project.

### ISSUE THREAD

**Issue by alex-bello** [aspnet/AspNetCore#3725]
When I run `dotnet build` to compile my netcoreapp2.1 project, the `System.Reflection.Assembly.FullName` is lowercase. 

`typeof(TestObject).AssemblyQualifiedName` returns
`Test.TestObject, test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

`typeof(TestObject).Assembly.FullName` returns
`test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

### To Reproduce

1. Create new mvc project using `dotnet new mvc`
2. Build project using `dotnet build`
3. Write assembly name to console using `Console.WriteLine(typeof(TestObject).Assembly.FullName`.

### Expected behavior
The expected values should be 

`typeof(TestObject).AssemblyQualifiedName` returns
`Test.TestObject, Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

`typeof(TestObject).Assembly.FullName` returns
`Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008533 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

Also, I tried setting the `<AssemblyName>` is the .csproj file and it then works as expected.

**Comment by natemcmaster** [comment]
What is the name of your .csproj file? The default value of AssemblyName is the file name of your project.

**Comment by NTaylorMullen** [comment]
Hmm, we did but in that case the `csproj` was the wrong casing which mucked with the generated assembly name.

For reference here's the issue that was slightly similar, but different 😞 : https://github.com/Microsoft/msbuild/issues/3665

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now. If you're still facing this issue, feel free to reopen it.
