### ISSUE TITLE
JWT Token not Working with Nginx

### ISSUE THREAD

**Issue by muzzammilhussain** [aspnet/AspNetCore#3728]
### Describe the bug
I am hosting a website using Nginx on website I am using Nginx Basic HTTP auth which also has a header named Authentication while JWT in my application also uses the same header for token..
I want to change the Change the header name in JWT . Cant find it how.

I am using ASPNetcore 2.1 with Angular 6

**Comment by khellang** [comment]
You need to set override the `OnMessageReceived` event:

```csharp
.AddJwtBearer(x =>
{
    x.Events.OnMessageReceived = context =>
    {
        var header = context.HttpContext.Request.Headers["Custom-Authorization"].ToString();

        if (!string.IsNullOrEmpty(header) && header.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
        {
            context.Token = header.Substring("Bearer ".Length).Trim();
        }

        return Task.CompletedTask;
    };
});
```

**Comment by muzzammilhussain** [comment]
Ok so it will change the filter? of authorization?

**Comment by khellang** [comment]
Change the filter? It just picks the token from a different header, `Custom-Authorization`, instead of the deafult.

**Comment by muzzammilhussain** [comment]
Issue resolved thanks alot

**Comment by osvaldo-github** [comment]
Thanks.


In my tests (.NET Core 2.2.) x.Events is equal null, then:

services.AddJwtBearer(x =>
            {
                x.Events = new JwtBearerEvents()
                {
                    OnMessageReceived = context =>
                    {
                        var header = context.HttpContext.Request.Headers["Custom-Authorization"].ToString();

                        if (!string.IsNullOrEmpty(header) && header.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                        {
                            context.Token = header.Substring("Bearer ".Length).Trim();
                        }

                        return Task.CompletedTask;
                    }
                };
                x.RequireHttpsMetadata = false;
                x.SaveToken = true;
                x.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(key),
                    ValidateIssuer = false,
                    ValidateAudience = false
                };
            });

**Comment by FlyDogBR** [comment]
Thanks.

In my tests (.NET Core 2.2.) x.Events is equal null, then:

services.AddJwtBearer(x =>
{
x.Events = new JwtBearerEvents()
{
OnMessageReceived = context =>
{
var header = context.HttpContext.Request.Headers["Custom-Authorization"].ToString();

                    if (!string.IsNullOrEmpty(header) && header.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                    {
                        context.Token = header.Substring("Bearer ".Length).Trim();
                    }

                    return Task.CompletedTask;
                }
            };
            x.RequireHttpsMetadata = false;
            x.SaveToken = true;
            x.TokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = new SymmetricSecurityKey(key),
                ValidateIssuer = false,
                ValidateAudience = false
            };
        });

**Comment by osvaldo-github** [comment]
Thanks.

In my tests (.NET Core 2.2.) x.Events is equal null, then:

services.AddJwtBearer(x =>
{
x.Events = new JwtBearerEvents()
{
OnMessageReceived = context =>
{
var header = context.HttpContext.Request.Headers["Custom-Authorization"].ToString();

                    if (!string.IsNullOrEmpty(header) && header.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                    {
                        context.Token = header.Substring("Bearer ".Length).Trim();
                    }

                    return Task.CompletedTask;
                }
            };
            x.RequireHttpsMetadata = false;
            x.SaveToken = true;
            x.TokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = new SymmetricSecurityKey(key),
                ValidateIssuer = false,
                ValidateAudience = false
            };
        });
