### ISSUE TITLE
webapi batch requests process, such as asp.net framework for webapi

### ISSUE THREAD

**Issue by Microshaoft** [aspnet/AspNetCore#3729]

**Comment by Tratcher** [comment]
This feature is not currently supported.

I wonder if such a feature might be partially or fully replaced by HTTP/2 multiplexing.

**Comment by Eilon** [comment]
ASP.NET Core 2.2 is to be released later this year.

**Comment by Microshaoft** [comment]
Is HTTP/2 multiplexing feature in preview yet in ASP.NET CORE 2.2?
@Eilon

**Comment by Tratcher** [comment]
@Microshaoft yes, it has released.
