### ISSUE TITLE
Data Protection - Tool to generate data protection key

### ISSUE THREAD

**Issue by kevinlo** [aspnet/AspNetCore#3733]
I have a web farm that will save the data protection key to the Couchbase.  The Couchbase can be accessed only through a web services that require access token from the IdentityServer.   When each application is started up, it needs to get the access token from the IdentityServer to call the web services to get the data protection keys from the Couchbase.   These all work fine except that IdentityServer itself needs to get the data protection key.   When the IdentityServer is started up, it needs to get the access token from itself to call the web services, I have this chicken and egg problem.

We don't have a NAS for the shared folder.  One proposed solution is, for the IdentityServer, we generate the key file with long expired date in advance.   This key file will be deployed in each nodes in the web farm.    The IdentityServer will have the  DisableAutomaticKeyGeneration set.   For key rotation, we will generate the new key file and deploy to each nodes.

Do you see any problem with this solution?

Moreover, how can I create a tool to create the key file in advance?   I know the AddDataProtection call will do the magic to generate a new key file if there is no active one available in the PersistKeysToFileSystem path and it can create a IKeyManager.CreateNewKey to create a new key.   

Do I need to write a dummy asp.net core app that will call the AddDataProtection with the same certificate as what the IdentityServer will use and run it once to persist the key file to a folder?

**Comment by kevinlo** [comment]
Find this [KeyManagementSampel](https://github.com/aspnet/DataProtection/blob/master/samples/KeyManagementSample/Program.cs) that I can follow to generate the key.

**Comment by blowdart** [comment]
In theory it would work. But you're heading deep into unsupported territory.

**Comment by kevinlo** [comment]
@blowdart That is NOT the solution I want.  It is architect decision that I need to follow.

I have read your comment on this [thread](https://github.com/aspnet/AspNetCore/issues/466#issuecomment-165214397).   My proposed solution is to store the certificate encrypted key in a network share which is protected by ACL and only the IIS apppool identity can access it.

Unfortunately, we don't have a NAS for the network share purpose and architect does not want to store in another shared folder.   I also read @GrabYourPitchforks [comment](https://github.com/aspnet/AspNetCore/issues/466#issuecomment-165214397)  that 

> The network share should be available for the app to function correctly, but the DataProtection framework can tolerate intermittent outages

Does it mean we don't need a NAS as the network share?

I have used that KeyManagementSample to create a console app that can generate the key file.    I just know from that sample that the revoke just create another revoke XML file, not updating the key file.

Does it mean each key is immutable and we should not update the XML content like the expirationDate.   I was asked to parse the key XML file and update the date of the key.   I don't think that is a good idea as I can see those properties in IKey are read-only.

I have tried the above solution on a single machine.  It works fine.   We'll try it on web farm.   As for they key rotation, from the source codes, the KeyRingProvider will refresh the cacheable key ring every 24 hours.  It should read the new key file we deploy.

Would you mind point out what that potential unsupported territory would be?    I need that to discuss with my architect.

**Comment by blowdart** [comment]
_Would you mind point out what that potential unsupported territory would be?_

Honestly? All of it. Data Protection is designed for a shared store, be it a file share, SQL, azure blob storage, redis or whatever. We don't test you creating a keyring offline and manually putting it on machines (although it's possible using the apis). We certainly don't test you editing keyfiles as once created we expect them to be immutable.

**Comment by kevinlo** [comment]
That's what I thought, it is a hack.   Thanks for your comment, I can close it.
