### ISSUE TITLE
Enable Json custom Converter attribute for reading appsettings

### ISSUE THREAD

**Issue by rizamarhaban** [aspnet/AspNetCore#3734]
### Is your feature request related to a problem? Please describe.
I have a POCO configuration class that has `System.Version` property in it. On my `appsetting.json`, the value is stated as a string. When using the `Configuration.GetSection();` this does not convert the string value to `System.Version`. Example:
```csharp
using System;
public class MySettings
{
    [JsonProperty("api_version")
    [JsonConverter(typeof(VersionConverter))]
    public Version ApiVersion { get; set; }
}
```

The `appsettings.json`:
```json
{
    "mysettings": {
         "api_version": "1.2.3.4"
    }
}
```
This will returns `null` when reading like, e.g.:
```csharp
var mySettings = new MySettings();
config.GetSection("mysettings").Bind(mySettings);
```
However, this will work as usual if using `JsonConvert.DeserializeObject<MySettings>(mysetingsJson);`.

### Describe the solution you'd like
Enable Json custom **Converter** attribute on POCO **Properties** for reading appsettings.

### Describe alternatives you've considered
`Configuration.GetSection<MySettings>("mysettings", /* a list of converters... */  )`

### Additional context
![image](https://user-images.githubusercontent.com/1063940/47599569-a4c55700-d9e3-11e8-8d86-2be00d352922.png)

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Configuration#901
