### ISSUE TITLE
External authentication not working on servers .net core 2.1

### ISSUE THREAD

**Issue by tlg-tejas** [aspnet/AspNetCore#3736]
Bug Description - 
I am trying external authentication for facebook and google with .net core 2.1.
I did the changes in startup.cs and added ExternalCallBack function. Everything worked locally. I deployed my site to AWS, both facebook and google does not work and does not redirect properly.

My startup.cs file
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fantasy.UI.Core.Infra;
using Fantasy.UI.Core.Interfaces;
using Fantasy.UI.Core.Providers.LoginProvider;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;
using Fantasy.UI.Core.Providers.SeriesProvider;
using Fantasy.UI.Core.Providers.MatchProvider;
using Fantasy.UI.Core.Providers.ChallengeProvider;
using Fantasy.UI.Core.Providers.UserTeamProvider;
using Microsoft.AspNetCore.Authentication.Facebook;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace Fantasy.UI
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();
            services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
            .AddJsonOptions(options =>
            {
                options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                options.SerializerSettings.Converters.Add(new StringEnumConverter
                {
                    CamelCaseText = true
                });

            });

            services.AddSession(
             options =>
             {
                 options.IdleTimeout = TimeSpan.FromHours(Convert.ToInt32(Configuration["AppSettings:SessionTimeOut"]));
             });
            services.AddSingleton<ILoginProvider, LoginProvider>();
            services.AddSingleton<ISeriesProvider, SeriesProvider>();
            services.AddSingleton<IMatchProvider, MatchProvider>();
            services.AddSingleton<IChallengeProvider, ChallengeProvider>();
            services.AddSingleton<IUserTeamProvider, UserTeamProvider>();

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            //https://dotnetcoretutorials.com/2018/05/03/httpclient-factories-in-net-core-2-1/
            //one way of creating http client, you can create client without default parameters
            //services.AddHttpClient<ILoginProvider, LoginProvider>(client=> {
            //    client.BaseAddress = new Uri("");
            //});

            //second way of adding http client : 
            services.AddHttpClient();
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAll",
                    builder =>
                    {
                        builder
                            .AllowAnyOrigin()
                            .AllowAnyMethod()
                            .AllowAnyHeader()
                            .AllowCredentials();
                    });
            });
            //third way of creating http client
            //services.AddHttpClient("twitterClient", client =>
            //{
            //    client.BaseAddress = new Uri("https://api.twitter.com");
            //});

            //services.Configure<CookiePolicyOptions>(options =>
            //{
            //    // This lambda determines whether user consent for non-essential cookies is needed for a given request.
            //    options.CheckConsentNeeded = context => true;
            //    options.MinimumSameSitePolicy = SameSiteMode.None;
            //});

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
             .AddFacebook(facebookOptions =>
             {
                 facebookOptions.AppId = Configuration["Authentication:Facebook:AppId"];
                 facebookOptions.AppSecret = Configuration["Authentication:Facebook:AppSecret"];
                 //facebookOptions.CallbackPath = new PathString("/api/Login/");
                 //facebookOptions.UserInformationEndpoint = 
             }).
             AddGoogle(googleOptions =>
             {
                 googleOptions.ClientId = Configuration["Authentication:Google:ClientId"];
                 googleOptions.ClientSecret = Configuration["Authentication:Google:ClientSecret"];
                 //googleOptions.CallbackPath = new PathString("/api/Login/");
             })
            .AddCookie();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }
            app.UseCors("AllowAll");
        
            app.UseAuthentication();

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseSession();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}

CallBack and signIn method

[HttpGet("SignIn/{provider}")]
        public IActionResult SignIn(string provider)
        {
            var redirectUrl = Url.Action(nameof(LoginController.LoginCallback), "Login", new { returnUrl = "/" });

            if (provider == FacebookDefaults.AuthenticationScheme)
            {
                return Challenge(
                    new AuthenticationProperties { RedirectUri = redirectUrl, }, FacebookDefaults.AuthenticationScheme);
            }
            if (provider == GoogleDefaults.AuthenticationScheme)
            {
                return Challenge(
                      new AuthenticationProperties { RedirectUri = redirectUrl, }, GoogleDefaults.AuthenticationScheme);
            }

            return null;

        }   

Can anyone please help me and understand what i am doing wrong? 
P.S. - I am using IIS 8 windows 2012

**Comment by Tratcher** [comment]
Can you share a Fiddler trace?

**Comment by tlg-tejas** [comment]
I am not allowed to add fiddler on servers, but one more strange thing i noticed locally and on servers is

Locally I can see cookies 
![image](https://user-images.githubusercontent.com/31978978/47609104-281f9080-da56-11e8-9314-b0ea2d1820ed.png)

Hosted site
![image](https://user-images.githubusercontent.com/31978978/47609116-3e2d5100-da56-11e8-9404-7eb9f975fa10.png)

Also i saw status 500 for google
![image](https://user-images.githubusercontent.com/31978978/47609139-9b290700-da56-11e8-822b-329b14ffc41b.png)

Any help is much appreciated

**Comment by Tratcher** [comment]
A 500 status usually means there was an exception on the server. Turn on logging to see it.

**Comment by tlg-tejas** [comment]
I got it running by adding this in startup.cs, i am not sure what change it did.

 app.Use((context, next) =>
            {
                if (context.Request.Headers["x-forwarded-proto"] == "https")
                {
                    context.Request.Scheme = "https";
                }
                return next();
            });

and changing cookie authentication to,
 .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme)

**Comment by Tratcher** [comment]
FYI there's [middleware](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#other-proxy-server-and-load-balancer-scenarios) for handling x-forwarded-proto.
