### ISSUE TITLE
ParsingHelpers.GetHeaderSplit - Check if values is empty before parsing

### ISSUE THREAD

**Issue by snakefoot** [aspnet/AspNetCore#3737]
Not calling `GetHeaderSplitImplementation` will skip the allocation of a yield-state-machine:

https://github.com/aspnet/HttpAbstractions/blob/ec176b2e40699c24cc1c0e3bde8a828e93fe67c7/src/Microsoft.AspNetCore.Http.Abstractions/Internal/ParsingHelpers.cs#L19-L23

**Comment by Tratcher** [comment]
Note we avoid micro-optimizations unless we can demonstrate their impact on a benchmark.

**Comment by snakefoot** [comment]
@Tratcher What should the scope of the benchmark be? 

Just calling the HeaderDictionaryExtensions.GetCommaSeparatedValues() on an empty IHeaderDictionary many times ?

**Comment by Tratcher** [comment]
You'd need the negative case as well, where GetCommaSeparatedValues was called with non-empty values.

The difference for such micro-benchmarks would need to be substantial in order to have any effect on the larger application.

**Comment by BrennanConroy** [comment]
Done via https://github.com/aspnet/AspNetCore/pull/9309
