### ISSUE TITLE
Copy sample code issue

### ISSUE THREAD

**Issue by lm28** [aspnet/AspNetCore#3739]
### Describe the bug
A few weeks ago, I told Rick that I was having a problem when I copied the sample course code into my project, but couldn't quite get a grip on what was happening.
I think that I have eventually tracked it down do a Visual Studio!

If I copy the sample code (from ANY tutorial) and paste it DIRECTLY into VS, I get problems. (especially when I copy the code for a MVC VIEW.)
However, If I first save the text in notepad++ (or simply Notepad) and then put the file into the project, there are no issues.

### To Reproduce
1. Using Visual Studio (Ver 15.8.5) and any version of ASP.NET Core from V2.0 (I haven't tried older versions)

2. Copy the sample code from a tutorial and paste DIRECTLY into the project in Visual Studio.
(I have experiences a problem with all of the following tutorials.)
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.0
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-2.0
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-2.0

3. With these arguments '....'

4. See attached screenshot for errors

### Expected behavior
Visual Studio reports errors (particularly when copying the code for the VIEWS.)

### Screenshots
In the attached image, the files surrounded by the red line, were straight copy/pastes, whereas the files in the blue area were 'washed' in notepad++, before being saved in my project.
(sorry about the squiggly line....I am trying out a RollerMouse)

### Additional context
Include the output of `dotnet --info`
![vs_copypaste_issue](https://user-images.githubusercontent.com/40284665/47612525-dc0d3400-dac7-11e8-9047-3086ad27fd29.JPG)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lm28.
@NTaylorMullen, is this something you're familiar with? Thanks!

**Comment by NTaylorMullen** [comment]
@lm28 i'm unable to reproduce your issue. It looks like you have some other Visual Studio extension installed however, normal VS doesn't red curly underline files for instance. My bet is that you're seeing issues due to an installed Visual Studio extension you have.
