### ISSUE TITLE
Overriding Identity default password requirements has no effect

### ISSUE THREAD

**Issue by CristianVladescu** [aspnet/AspNetCore#3750]
### Describe the bug
Overriding default password requirements of a fresh Web Application project with Individual User Accounts enabled, has no effect.

### To Reproduce
1. Create a new Web Application project with Individual User Accounts authentication enabled
2. Override default password requirements like described [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1#password)
3. Attempt to register a new user with a password that doesn't meet default requirements, but meets the newly ones configured
4. Observe the error "The Password must be at least 6 and at max 100 characters long.", despite PasswordOptions.RequiredLength property being set to 1.

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
You will need to scaffold the UI and change the model validation to match, configuring the identity options is just changing the server side validation

**Comment by HaoK** [comment]
Looks like you are 2.1 so you aren't using the default UI, so you just need to change the validation attributes in your RegisterViewModel to match:

```
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
```
