### ISSUE TITLE
2.2: Build fails with error NU5125

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#3751]
I attempted to update our build to use a 2.2.100 RTM candidate of the SDK. This includes changes to NuGet which cause the build to fail with:

> C:\b\w\d1c9b84e58362abc\.dotnet\x64\sdk\2.2.100-rtm-009571\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(202,5): error NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [C:\b\w\d1c9b84e58362abc\src\Framework\Microsoft.AspNetCore.All\pkg\Microsoft.AspNetCore.All.pkgproj]

Presumably this was introduced in https://github.com/NuGet/NuGet.Client/pull/2450.

@nkolev92 @rrelyea - are there known issues in this? The project in question, [Microsoft.AspNetCore.All.pkgproj](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Framework/Microsoft.AspNetCore.All/pkg/Microsoft.AspNetCore.All.pkgproj), is not using a hand-written nuspec.

cc @Eilon blocking issue for 2.2 RTM.

**Comment by nkolev92** [comment]
That's a warning that's getting elevated to an error. 

It's a new feature we are working on. 
https://github.com/NuGet/Home/issues/4628

It will ship in 2.2.1xx and 2.1.5xx, as well as NuGet.exe 4.9 and VS 2017.9.

**Comment by natemcmaster** [comment]
Fixed in #3758
