### ISSUE TITLE
Change projects to target netcoreapp3.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#3754]
As a part of only supporting .NET Core, we can change most projects to target netcoreapp3.0 instead of netstandard2.0.
This change applies to test projects, which no longer need to cross-target .NET Framework.

See https://github.com/aspnet/Announcements/issues/324

Remaining feature areas (I likely missed a few here, keep adding them ~Chris):
- [x] Html
- [x] Razor - make sure to ping @rynowak on this one. We're splitting code here into a new repo soon.
- [x] Http - (Chris) - With exceptions https://github.com/aspnet/AspNetCore/issues/3754#issuecomment-443049198
- [x] Hosting (Chris)
- [x] DataProtection (Chris)
- [x] HttpSysServer (Chris)
- [x] Kestrel (Chris)
- [x] BasicMiddleware (Chris)
- [x] IISIntegration (Justin)
- [x] Antiforgery (Chris)
- [x] StaticFiles (Chris)
- [x] ResponseCaching (Chris)
- [x] Middleware (Chris)

**Comment by natemcmaster** [comment]
I want to emphasize the "most" part of the original post. Some libraries, like the SignalR .NET client, must continue to target .NET Standard when the library is intended for use on other .NET runtimes like Xamarin and UWP. This decision is being made on a case-by-base basis. We should finish going through our list of assemblies and post the decisions to clarify exactly which assemblies should change to netcoreapp3.0-only.

**Comment by bdominguez** [comment]
What about WPF applications that host asp net core? It will no longer be possible to do this.

**Comment by khellang** [comment]
> What about WPF applications that host asp net core?

Just port it over to .NET Core? 😉  https://blogs.msdn.microsoft.com/dotnet/2018/10/04/update-on-net-core-3-0-and-net-framework-4-8/

**Comment by natemcmaster** [comment]
@khellang is correct, WPF and AspNetCore can be used together. A WPF app will be able to set TargetFramework to netcoreapp3.0 and also have a FrameworkReference to Microsoft.AspNetCore.App.

**Comment by benaadams** [comment]
> What about WPF applications that host asp net core? It will no longer be possible to do this.

And if you don't want to port your WPF to .NET Core (though you should 😉) you can keep using ASP.NET Core 2.1 https://github.com/aspnet/AspNetCore/issues/3753#issuecomment-438046364

> In order to give customers a reasonable stepping stone on their path to migrating applications to ASP.NET Core on .NET Core, we are going to extend support and servicing for ASP.NET Core 2.1.x on .NET Framework to match the current support policy for the other package-based ASP.NET frameworks, e.g. MVC 5.x, Web API 2.x, SignalR 2.x. This effectively means the ASP.NET Core 2.1.x related packages (final detailed list TBD) will be supported indefinitely, beyond the 3 year LTS period for the .NET Core 2.1 train overall.

**Comment by natemcmaster** [comment]
@dougbu here are some known exceptions to what changes to netcoreapp3.0: https://github.com/aspnet/AspNetCore/blob/9e73c3382f4d9e6ba47afff6a1467ace945c77e7/build/SharedFrameworkOnly.props#L12-L20

**Comment by Tratcher** [comment]
Session: https://github.com/aspnet/Session/commit/abbdfb72ef54a77623c01d517c85eb8b28c70bc0

**Comment by Tratcher** [comment]
@natemcmaster DataProtection is getting upgraded, right? What about the net461 package Microsoft.AspNetCore.DataProtection.SystemWeb?

**Comment by natemcmaster** [comment]
Yes, we can update DataProtection to netcoreapp3.0. Projects which were .NET Framework-only and have a dependency on ASP.NEt Core can be removed. For 3.0, I believe that includes 

* Microsoft.AspNetCore.DataProtection.SystemWeb
* Microsoft.Owin.Security.Interop
* Microsoft.AspNet.Identity.AspNetCoreCompat

**Comment by Tratcher** [comment]
@rynowak Passing this off to you for HTML and Razor.

**Comment by dougbu** [comment]
Many thanks for all your work on this @Tratcher!

**Comment by rynowak** [comment]
Done for Html and Razor. @Tratcher - is this totally done now?

**Comment by Tratcher** [comment]
Still waiting for a final review on https://github.com/aspnet/AspNetCore/issues/3754, but otherwise I think so.

Doug, want to do a final verification on the package artifacts to see if all the TFMs are what we expect them to be?

**Comment by dougbu** [comment]
@Tratcher sure, I'll have a look-see.

But, #3754 is this issue. What PR hasn't been reviewed?

**Comment by Tratcher** [comment]
Woops, I meant #4625. It just went in this morning.

**Comment by dougbu** [comment]
A few projects aren't mentioned above as hold-outs and haven't been touched:. @Tratcher I haven't checked the PRs for comments on these. Do you recall if any can now be updated?

**All** please check off those that are fine as-is and please add resoning:
- [ ] src\AzureIntegration\src\Microsoft.Web.Xdt.Extensions\Microsoft.Web.Xdt.Extensions.csproj (and its test project)
- [ ] most (all?) of src\Components
  - @SteveSandersonMS @rynowak do the Components target `netstandard2.0` for reasons?
- [ ] src\Features\JsonPatch\src\Microsoft.AspNetCore.JsonPatch.csproj (and its test project)
- [ ] four of the src\Identity\test projects
- [ ] src\Installers\RuntimeSiteExtension\Microsoft.AspNetCore.Runtime.SiteExtension.pkgproj
- [ ] src\Installers\Windows\AspNetCoreModule-Setup\ANCMPackageResolver\ANCMPackageResolver.csproj
- [ ] src\Installers\Windows\tasks\InstallerTasks.csproj
  - @natemcmaster @pakrym @jkotalik do Installers need to target `net461` and (for ANCMPackageResolver.csproj) `netstandard1.0`?
  - same question for the site extension projects further down
- [ ] src\Middleware\HealthChecks.EntityFrameworkCore\src\Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore.csproj (and its test project)
- [ ] src\Middleware\Localization\testassets\ResourcesClassLibraryNoAttribute\ResourcesClassLibraryNoAttribute.csproj
- [ ] src\Middleware\Localization\testassets\ResourcesClassLibraryWithAttribute\ResourcesClassLibraryWithAttribute.csproj
- [ ] src\Mvc\src\Microsoft.AspNetCore.Mvc.Analyzers\Microsoft.AspNetCore.Mvc.Analyzers.csproj
- [ ] src\Mvc\src\Microsoft.AspNetCore.Mvc.Api.Analyzers\Microsoft.AspNetCore.Mvc.Api.Analyzers.csproj
- [ ] most (all?) of src\MvcPrecompilation
  - @pranavkm the last three look like your world. Should / can any of these now target `netcoreapp3.0`?
- [ ] src\PackageArchive\Scenario.ClassLibrary\Scenario.ClassLibrary.csproj
- [ ] src\PackageArchive\ZipManifestGenerator\ZipManifestGenerator.csproj
- [ ] src\Security\test\Microsoft.Owin.Security.Interop.Test\Microsoft.Owin.Security.Interop.Test.csproj
- [ ] src\Servers\Connections.Abstractions\src\Microsoft.AspNetCore.Connections.Abstractions.csproj
- [ ] src\SiteExtensions\src\Microsoft.AspNetCore.AzureAppServices.SiteExtension\Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj
- [ ] src\SiteExtensions\src\Microsoft.Web.Xdt.Extensions\Microsoft.Web.Xdt.Extensions.csproj
- [ ] src\SiteExtensions\test\Microsoft.AspNetCore.AzureAppServices.SiteExtension.Tests\Microsoft.AspNetCore.AzureAppServices.SiteExtension.Tests.csproj

**Comment by Tratcher** [comment]
Microsoft.Web.Xdt.Extensions isn't changing. It's part of the Azure deployment infrastructure and only runs on net461.

**Comment by Tratcher** [comment]
Microsoft.Owin.Security.Interop.Test is disabled for now and needs to be re-written.  It's tests a bridge scenario between core and katana.

**Comment by Tratcher** [comment]
@pakrym to comment on site extension infrastructure and ANCM packages.

**Comment by pakrym** [comment]
TFM shouldn't matter in site extension projects, but I would prefer keeping them as is because Nuget version used by AppServices is very old and I don't want surprises.

**Comment by dougbu** [comment]
@natemcmaster can src\PackageArchive\ZipManifestGenerator be updated?

**Comment by dougbu** [comment]
@joeloff @jkotalik what are your thoughts on the src/Installers/Windows/** projects?

**Comment by joeloff** [comment]
Don't think it matters for setup projects. These build using WiX - they just consume other build outputs

**Comment by dougbu** [comment]
@rynowak I seem to remember you commenting on JsonPatch recently. Is it intentionally _not_ targeting `netcoreapp3.0`?

**Comment by SteveSandersonMS** [comment]
Anything that needs to run on WebAssembly has to be netstandard. Hence the particular subset of Components projects that target netstandard2.0.

________________________________

**Comment by dougbu** [comment]
@SteveSandersonMS your email responded to a message about JsonPatch. Is that used in projects that target WebAssembly too?

**Comment by natemcmaster** [comment]
Btw, I'm updating Doug's check list above. Yes, ZipManifestGenerator  could be updated, but it doesn't really matter. It's a developer tool for this repo only. We don't re-distribute.

**Comment by dougbu** [comment]
@Tratcher was Microsoft.AspNetCore.Connections.Abstractions.csproj left out of #4405 on purpose?

**Comment by rynowak** [comment]
JsonPatch should change to netcoreapp3.0. 

Components stuff can be left alone. We'll be doing more surgery there soon, and much of it will be ns2.0 forever

**Comment by rynowak** [comment]
Precompilation can be deleted.

**Comment by Tratcher** [comment]
@natemcmaster wasn't SignalR client going to need Microsoft.AspNetCore.Connections.Abstractions.csproj transitively?

**Comment by dougbu** [comment]
Actions so far:
- convert to `netcoreapp3.0`:
  - [ ] src\Features\JsonPatch\src\Microsoft.AspNetCore.JsonPatch.csproj
  - [ ] src\PackageArchive\ZipManifestGenerator\ZipManifestGenerator.csproj
- delete
  - [ ] src/MvcPrecompilation/**

**Comment by dougbu** [comment]
@pranavkm that leaves just Microsoft.AspNetCore.Mvc.Analyzers.csproj and Microsoft.AspNetCore.Mvc.Api.Analyzers.csproj. Must the analyzers target `netstandard1.3`?

**Comment by dougbu** [comment]
FYI I'll take the remaining few actions

**Comment by dougbu** [comment]
#5124 closed with 826f950530

**Comment by dougbu** [comment]
Last bit done in e717a8443e

**Comment by dougbu** [comment]
Actually, @pranavkm should the analysers be converted to target `netcoreapp3.0`?

**Comment by natemcmaster** [comment]
I believe analyzers should target netstandard2.0, since csc runs on both framework (in VS) and core (everywhere else).
