### ISSUE TITLE
Unable to extend DBContext table models using partial class with custom Properties

### ISSUE THREAD

**Issue by pixelda** [aspnet/AspNetCore#3760]
In MVC Core 2.1, extending a DBContext table model using another partial class causes an exception when attempting to load data from the database. This works in ASP.NET MVC Entity Framework.

In MVC Core 2.1 with a DBContext model, add another partial class with a new property
Run code to select all records from the database for this model
An exception is raised - System.Data.SqlClient.SqlException: 'Invalid column name 'ColumnName'

From a design perspective having used ASP.NET MVC I was expecting to be able to extend the class with my own properties that would be ignored by DBContext. I assume that EF6 as used in ASP.NET MVC keeps a separate store of information which it then uses to generate the C# code for the table data model. In working wit the database, only the defined columns are associated

I assume that MVC Core DBContext works differently, simply outputting the complete model from which all interaction with the database are performed. My adding additional properties, even to the partial class breaks this design. Seems a bit pointless creating partial classes for the Models in this case

**Comment by ajcvickers** [comment]
@pixelda Partial classes are combined into a single class at compile time. There is no difference in the runtime class generated when compared to adding properties to a non-partial class. That is, partials are source code syntactic sugar.

DbContext typically works in the same way here between EF6 and EF Core when using code mappings. That is, if a new property is added to a class, then that property will be included in the model by-convention. If you were previously using a database-first workflow with an EDMX file to manage your database, then adding properties to entity types might have resulted in them being ignored by default.

To explicitly ignore properties when using code mappings, use either `[NotMapped]` or `.Ignore` in the fluent API. See https://docs.microsoft.com/en-us/ef/core/modeling/included-properties

**Comment by pixelda** [comment]
@ajcvickers - Yes, it is always Database First for me. Forgot about the NotMapped. Thanks
