### ISSUE TITLE
No Individual User Accounts auth option in ASP.NET Core Web API template

### ISSUE THREAD

**Issue by MasHero7** [aspnet/AspNetCore#3772]
I've done this solution to get the feature decribed at this link:
https://stackoverflow.com/questions/41061926/no-individual-user-accounts-auth-option-in-asp-net-core-web-api-template
But when I installed VS Preview as suggested side-by-side with VS 2017, I don't find this feature! Why? and how to solve please? 
The situation for me is like this:
https://i.imgur.com/0LYUTRv.png

**Comment by blowdart** [comment]
It will come just after 2.2 as part of the Identity Server integration, until then there's no support.

**Comment by MasHero7** [comment]
Do you mean it will be supported in core version 2.2 or it needs third party one as identity server 4?
Why did you close the issue before getting my answer?

**Comment by papyr** [comment]
@MasHero7 I was just about to ask why @blowdart @shanselman is closing the issues before they are resolved.

They need new managers to resolve the User Management - blowdart does not seem motivated I have posted many times showing how many people have been asking

**Comment by blowdart** [comment]
@MasHero7 See https://github.com/aspnet/Identity/issues/2048
