### ISSUE TITLE
Update MusicStore tests to run against the shared framework

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#3775]
The music store tests are still configured for ASP.NET Core 2.0 and the runtime store. The behavior of the shared framework is the same, so it should just be a matter of swapping the names of the environment variables used to enable the tests.

**Comment by javiercn** [comment]
@natemcmaster Did you already do this?

**Comment by natemcmaster** [comment]
No.

**Comment by javiercn** [comment]
@mkArtakMSFT I don't even know what this workitem entails. I imagine it involves removing all the references below in favor of using the SDK that was just built. I'm not even sure our build system is prepared to do this. Who's in charge of the build these days now that Nate is on leave? Can he provide some guidance?

https://github.com/aspnet/AspNetCore/blob/master/src/MusicStore/samples/MusicStore/MusicStore.csproj#L18

**Comment by mkArtakMSFT** [comment]
Ok. I had wrong understanding about this one. Seems this is more about how to update csproj file to target the right framework. @ryanbrandenburg, can you please handle this? Thanks!

**Comment by mkArtakMSFT** [comment]
Closing as we don't get to this for quite a while now.
