### ISSUE TITLE
SignalR 2.2 doesn't support Server Sent Events when running through IIS Express in VS

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/AspNetCore#3790]
After creating aspnet/Tooling#359 and reading through #7 / #105, I was under the expression that with RC2, running in IIS Express shouldn't buffer the responses sent to the client. However in my application that's using SignalR 2.2.0 when using Server Sent Events, the browser waits for five seconds before falling back to Long Polling. The way I understand things, this indicates that there is some sort of request buffering between the SignalR Server and the browser client.

When I `dotnet run` my application from the command line and let the browser hit Kestrel directly, the Server Sent Events transport immediately works and quickly connects.

**Comment by muratg** [comment]
@Tragetaschen Closing this one as it's too old. If you're still having issues, please let us know.
