### ISSUE TITLE
Investigate HTTP/2 behavior for RequestAborted and Abort

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#3791]
For Http/1.x RequestAborted is used to detect early disconnects and Abort is used to force them.

For HTTP/2 requests can be multiplexed over a single connection and it's possible to terminate individual requests while leaving the connection active. Investigate how Http.Sys/IIS surfaces this behavior and if RequestAborted and Abort can be adapted accordingly. We may also need to introduce a lower level connection Abort API to kill the underlying connection (if Http.Sys/IIS allows that).

**Comment by anurse** [comment]
We think we're good here. If we get customer feedback that there's an issue we can revisit.
