### ISSUE TITLE
IIS in-process hosting moved out of ASP.NET Core 2.1

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#3794]
Discussion for https://github.com/aspnet/Announcements/issues/302

------

We are moving IIS in-process hosting out of the ASP.NET Core 2.1 to give more time to validate the design and implementation. We will ship IIS in-process hosting as part of the ASP.NET Core 2.2 release.

### Why?

IIS in-process hosting  is a brand new server implementation and hasn't received sufficient attention during the ASP.NET Core 2.1 release for us to feel comfortable shipping it at this time.

**Comment by muratg** [comment]
This is shipping in 2.2.

**Comment by UweKeim** [comment]
So did it actually ship in [2.2](https://dotnet.microsoft.com/download/dotnet-core/2.2)?
