### ISSUE TITLE
TLS leak in out  of process

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#3796]
After recent changes, we started correctly unloading handler DLL and a new error appeared when running with AppVerifier on.

The TSL token we allocate in https://github.com/aspnet/IISIntegration/blob/46285253018e1086cf4e9ba272c0efb86120c486/src/AspNetCoreModuleV2/OutOfProcessRequestHandler/dllmain.cpp#L208 is never freed on dll unload.

**Comment by anurse** [comment]
We believe this is fixed. If something comes up, we can fix it.
