### ISSUE TITLE
Loopback connection

### ISSUE THREAD

**Issue by nikodemrafalski** [aspnet/AspNetCore#3799]
Hi, I raise this issue to ask about something I don't understand and cannot found any explanation in ms docs.

What are the loopback connections? Are they connection of IIS making to my dotnet.exe process?
It's always growing until I restart my application. What could be the cause, is that an issue at all?
My application is an web api, and additionally it allows web sockets connection. Outbound traffic is HTTP.
I also use azure PostgreSQL. 

Would collecting a network trace and analysing it somehow help me reveal this mystery ;)
Thanks in advance

![image](https://user-images.githubusercontent.com/731552/41039718-a319d20a-699a-11e8-94dc-60e78684e00a.png)

**Comment by jkotalik** [comment]
Hey all, the issue originally state with websockets and IIS is fixed fixed. Please download the latest versions of 2.1, 2.2, and 1.x: https://dotnet.microsoft.com/download/dotnet-core/2.1, https://dotnet.microsoft.com/download/dotnet-core/2.2, and https://dotnet.microsoft.com/download/dotnet-core/1.1.
