### ISSUE TITLE
ANCM Installer Removes Custom Settings

### ISSUE THREAD

**Issue by rockerinthelocker** [aspnet/AspNetCore#3800]
The ANCM installer removes custom settings, such as

`<aspNetCore lockAllAttributesExcept="processPath,arguments,stdoutLogEnabled,stdoutLogFile,forwardWindowsAuthToken,disableStartUpErrorPage,hostingModel" />`

, from applicationHost.config during installation. Of course, this breaks things.
 #824

**Comment by anurse** [comment]
We don't plan to fix this.
