### ISSUE TITLE
TCP packet size too small causing poor throughput

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#3803]
Originally reported by @mateanticevic

> I have the same problem and noticed something strange. There's a huge amount of TCP packets as they are way below the MTU size limit. I reckon this is the cause of the slow download. This happens only with IIS in front of Kestrel. With Kestrel alone it doesn't happen.

AspNetCore MVC 1.1.1 ~675kB ~11500 packets ~2s download

![image](https://user-images.githubusercontent.com/4734691/36193084-4d097278-1119-11e8-9e06-9b76c455648c.png)

> Tested a similar call in an old app with Web forms and the difference is obvious.

Web forms ~675kB ~750 packets ~200ms download

![image](https://user-images.githubusercontent.com/4734691/36228140-42b193ae-1188-11e8-9932-830596d8d980.png)

**Comment by muratg** [comment]
We think in-process ANCM is not impacted, but we should verify.

**Comment by skashif** [comment]
I am facing a similar issue where the content-download time is degrading the performance. My issue is that when I access the sites on one of the VMs (irrespective of whether I am running it on the deployed server(VM) or not) I am getting the API response performance as below,

![image](https://user-images.githubusercontent.com/23385818/48412416-92c90f80-e76a-11e8-989c-1efe5687ef0c.png)

On another note, if I am accessing the website from my development machine which is not one of the VMs but a local desktop, I get the following response time,
![image](https://user-images.githubusercontent.com/23385818/48413437-c35e7880-e76d-11e8-9b5c-0d5015ded82d.png)


Before I explain further, I would like to throw light on the application tech stack and versions -
**API solution**
.Net Core 2.1.4 
**Client**
Angular 6
**Host environment**
Windows 2012 R2
IIS 8.5.*

So as you can see with hosting environment I have gone IIS + Krestel route but I have also tried hosting the API solution as a standalone using HTTPsys(formerly know as Weblistener) but the results were no different but even worse.

What am I trying to do?
My API returns a large JSON which has around 18K+ rows with Response compression (gzip) I have got down the response size to 1.9MB. 

It would be great if someone could help me out here also,
1) Open to try a better approach to handle a large dataset?
2) Using different deployment techniques if that helps my cause?
3) Apply addition (IIS/Krestel) configs before deployment to make the API respond better?

This is a dealbreaker for me as you can notice I am making this data available in few ms so the **response time is imperative** for me.

**Comment by shirhatti** [comment]
@skashif There is nothing in your post to indicate that this is at all related to the original issue claiming small TCP packet size causing poor throughput.

There isn't enough information in your ascertain what's going on. I'd recommend taking a look https://docs.microsoft.com/en-us/visualstudio/profiling/beginners-guide-to-performance-profiling?view=vs-2017. Feel free to create a new issue with a CPU profile if you see this issue persist.

**Comment by anurse** [comment]
This only affects out-of-process. We don't have plans to invest significantly in perf here right now.

**Comment by dyslexicanaboko** [comment]
On the off chance that this could help someone, this blog post helped me figure out my slowness issue:
[https://weblog.west-wind.com/posts/2018/Dec/31/Dont-let-ASPNET-Core-Default-Console-Logging-Slow-your-App-down](https://weblog.west-wind.com/posts/2018/Dec/31/Dont-let-ASPNET-Core-Default-Console-Logging-Slow-your-App-down)

## &tldr;
If your logging levels are set to "debug", "trace", "information", etc - then you are going to experience some very slow processing of requests due to the tons of logging that is happening. I was experiencing anything between 40 seconds to 2 minutes for a response. I was getting 502 and 400 errors. Finally after enough digging I found that article, changed my logging level to "warning" now site responds in sub second.

```
"Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  }
```
