### ISSUE TITLE
Add tests for startup timeouts

### ISSUE THREAD

**Issue by mikeharder** [aspnet/AspNetCore#3813]
Tests should be added to verify the behavior of IIS / IIS Express when app startup times out.  For example, the timeout specific to `where.exe` was removed in https://github.com/aspnet/IISIntegration/pull/970, since we believe the global timeout used by IIS is sufficient.  Assumptions like this should be verified by tests.

**Comment by muratg** [comment]
We have test coverage for in-proc mode. Closing this.
