### ISSUE TITLE
Forward TLS token binding

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#3815]
http://tools.ietf.org/html/draft-popov-token-binding-00
http://tools.ietf.org/html/draftbalfanz-https-token-binding-00
http://www.ietf.org/proceedings/91/slides/slides-91-uta-2.pdf
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Features/ITlsTokenBindingFeature.cs
Win10+

**Comment by anurse** [comment]
We haven't seen interest in this. Closing for now, waiting for further customer interest (unless @blowdart has thoughts)
