### ISSUE TITLE
Backend fails to start if you try to connect to physical path with a custom identity

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#3817]
_From @shirhatti on September 20, 2017 23:32_

Fails to start backend process on UNC path even though the worker process has the access permission for the UNC

![image](https://user-images.githubusercontent.com/4734691/30672432-fc7057be-9e31-11e7-8e98-5bdf3ccc3168.png)

_Copied from original issue: aspnet/AspNetCoreModule#162_

**Comment by anurse** [comment]
Meh. If we get customer interest we can revisit.
