### ISSUE TITLE
Server.MapPath in AspNetCore

### ISSUE THREAD

**Issue by upta** [aspnet/AspNetCore#3824]
My company's website's (MVC 5) architecture uses a bunch of IIS sub-applications to organize/sub-divide pieces of the site and we have a couple of components that rely on IIS Server.MapPath functionality to figure out what folders those sub-applications are pointed towards.

I know this sort of thing isn't exactly a high priority, but is there any chance we might see something along the lines of the .Net Core 2.1 Windows Compatibility pack to help those of us that don't need cross-platform support get back some of these Windows + IIS features?

**Comment by anurse** [comment]
We don't have plans to implement this. The concepts don't really map in ASP.NET Core. URLs aren't inherently based on any directory structure. Each component has conventions that may map to directories, but this isn't something that can be generalized.
