### ISSUE TITLE
Supress windows auth token when forwardWindowsAuthToken is set to false

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCore#3828]
1. Enable NTLM authentication for an aspnetcore app which is running in inprocess
2. Send a request to the aspnetcore app

EXPECTED:

The request headers should contain the following headers:

MS-ASPNETCORE-TOKEN
MS-ASPNETCORE-WINAUTHTOKEN

ACTUAL:

The request headers does not have the expected request headers.

**Comment by anurse** [comment]
Closing until we hear customer interest.
