### ISSUE TITLE
Is there a standalone installer for ANCM; i.e., without .NET Core runtime?

### ISSUE THREAD

**Issue by TheBlueSky** [aspnet/AspNetCore#3832]
I'm publishing a self-contained ASP.NET Core application and would like to host it in IIS. To do that, I know I need to install ASP.NET Core Module; however, the [download page](https://www.microsoft.com/net/download/dotnet-core/2.1) lists only the Runtime & Hosting Bundle and there is no installer for ANCM alone.

I don't want to install .NET Core runtime; so, is there a standalone installer for ANCM?

**Comment by muratg** [comment]
We have coverage here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1#install-the-net-core-hosting-bundle

(Thanks @guardrex)
