### ISSUE TITLE
Make AzDO upload native symbols automatically

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#3836]
Part of this work item is to establish exactly which symbols go where, and when (for all symbols for ASP.NET/EF Core), and add it to the AspNetCore wiki.

**Comment by muratg** [comment]
Triage: this is for uploading native symbols to VS builds.

**Comment by jkotalik** [comment]
Dup of https://github.com/aspnet/AspNetCore-Internal/issues/2237
