### ISSUE TITLE
HTTP Error 502.3 - Bad Gateway after 3~4 requests

### ISSUE THREAD

**Issue by npestana** [aspnet/AspNetCore#3841]
Currently we're developing in Visual Studio 2017 and after a rebuild we can only do 3~4 requests without getting the "HTTP Error 502.3 - Bad Gateway". See the next image to view the processes waiting, I think, for the Kestrel response.

![Worker Process Requests View](https://user-images.githubusercontent.com/1201708/46671616-225c2b00-cbcd-11e8-8d63-71310605b4d6.png)

Visual Studio Version: 15.8.5
IIS Version: 10.0.17134.1

Project dependencies in .csproj
`<PackageReference Include="Microsoft.AspNetCore" Version="2.1.2" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.1.1" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Xml" Version="2.1.1" />
<PackageReference Include="Microsoft.AspNetCore.ResponseCaching" Version="2.1.1" />
<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.1" />
<PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0" />
<PackageReference Include="System.ServiceModel.Duplex" Version="4.5.3" />
<PackageReference Include="System.ServiceModel.Http" Version="4.5.3" />
<PackageReference Include="System.ServiceModel.NetTcp" Version="4.5.3" />
<PackageReference Include="System.ServiceModel.Primitives" Version="4.5.3" />
<PackageReference Include="System.ServiceModel.Security" Version="4.5.3" />`

Related issue in Developer Community: https://developercommunity.visualstudio.com/content/problem/324724/net-core-iis-integration.html

EDIT 1: This happens when it's not attached to the process for debug.

EDIT 2: Program.cs

```
public class Program
{
	public static void Main(string[] args)
	{
		CreateWebHostBuilder(args).Build().Run();
	}

	public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
		WebHost.CreateDefaultBuilder(args)
			.UseKestrel(
				(context, options) =>
				{
					options.AddServerHeader = false;
					options.Limits.MaxConcurrentConnections = 600;
				}
			)
			.UseSockets(options => { options.IOQueueCount = 8; })
			.UseStartup<Startup>();
}
```

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
