### ISSUE TITLE
Consider committing binaries to avoid pulling from myget feed for backwards compat tests

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#3850]
Pulling from myget isn't a long term solution; preview builds may get purged eventually and the Microsoft.AspNetCore.AspNetCoreModule package isn't on nuget. We should either commit binaries or create a long term feed to keep a stable version of the package.
cc @natemcmaster

**Comment by anurse** [comment]
> so we shouldn't need to do additional work.
