### ISSUE TITLE
Publish to azure initial request returns "The service is unavailable"

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#3853]
**Repro:**
1. Publish site to azure using inprocess
2. Initial request is sent to site automatically
3. Check response

Expected: Response is the home page of the site
Actual: ~50% of the time, it returns "The service is unavailable". Refreshing the page will return the home page. 

**Cause:**

When ANCM detects app offline, it call IHttpServer::RecycleProcess. This event tells IIS to start shutting down the current worker process. However, requests can still be sent to the worker process before a new worker process is created. If app offline is dropped and removed, sending an HttpRequest to the server immediately may return a 500 for the process shutting down.

We prototyped a fix to avoid calling shutdown until we receive a global notification from IIS, but that didn't seem to help.

**Comment by shirhatti** [comment]
Triage decision: not important
