### ISSUE TITLE
React to SDK/shared runtime custom install location changes

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#3855]
We would need to consume location information that is set by SDK installer to a registry key.

https://github.com/dotnet/cli/issues/10100

**Comment by johnbeisner** [comment]
Discussion regarding: https://github.com/aspnet/AspNetCore/issues/3855
Reference: https://github.com/dotnet/cli/issues/10100


The SDK bundle thru Visual Studio could be installed to a different volume then the default: Program Files\dotnet.
Therefore, our muxers/resolvers will need to be able to find this custom location.

The POR is to write a registry key upon SDK bundle installation:

```
      <Component Id="SDKInstallLocation" Directory="TARGETDIR" Win64="no" Permanent="yes">
        <RegistryKey Root="HKLM" Key="SOFTWARE\dotnet\Setup\InstalledVersions\$(var.Platform)\sdk">
          <RegistryValue Action="write" Name="InstallLocation" Type="string" Value="[DOTNETHOME]" KeyPath="yes"/>
        </RegistryKey>
      </Component>
```

this key is alongside the SDK installed versions in the 32-bit registry
