### ISSUE TITLE
Unable to run localization sample & unit tests

### ISSUE THREAD

**Issue by hishamco** [aspnet/AspNetCore#3870]
While i'm investigating on something in localization, I suddenly notice that i'm unable to run the localization sample nor unit tests, I got the following exception **Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'**

1. Using this version of ASP.NET Core '2.2.100-preview3-009430'
2. Run the localization sample
3. See error

/cc @ryanbrandenburg

**Comment by Eilon** [comment]
@hishamco - which loc sample were you running? Can you point to the exact URL?

**Comment by hishamco** [comment]
The default sample https://github.com/aspnet/Localization/tree/master/samples/LocalizationSample, but the issue isn't only in the sample, it happens in the unit testing too.  FYI there's an exception thrown from `WebHost`

**Comment by mkArtakMSFT** [comment]
@hishamco, there seems to be something wrong with your configuration. Can you try it out on a new VM?
The reason is that we have tests which run daily and this would break our daily tests.

**Comment by hishamco** [comment]
Nothing wrong with my configuration, I test before few weeks ago while I experiment something

> The reason is that we have tests which run daily and this would break our daily tests.

That's why I surprised from this behavior, specially after branch name changes and fetch the latest commits, I will try to clean up the repo and pull it again

**Comment by hishamco** [comment]
After renaming the `dev` branch to `master` and run `build.cmd` the previous exception gone, but another exception show in the sample, I reproduce the exception by running the unit tests, all are passed except the Functional Test

Can anyone run the functional tests and verify?

**Comment by hishamco** [comment]
After I update the repo to the latest bits and use `git clean -xdf` everything worked as expected
