### ISSUE TITLE
Creating new asp mvc project, publishing throws errors NETSDK1061

### ISSUE THREAD

**Issue by MPasadu** [aspnet/AspNetCore#3871]
### Describe the bug
Creating new asp mvc project, publishing throws errors NETSDK1061. 

EDIT: dotnet build throws the same errors

### To Reproduce
1. Installed SDK v2.1.403
2. "dotnet new mvc"
3. Open in VSCode
4. "dotnet publish --self-contained -r win-x64"
5. See error

### Expected behavior
Clean publish without errors

### Errors
1. Error: NETSDK1061: The project was restored using **Microsoft.NETCore.App** version 2.1.5, but with current settings, version 2.1.0 would be used instead. To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish. Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore. For more information, see https://aka.ms/dotnet-runtime-patch-selection.

2. Error: NETSDK1061: The project was restored using **Microsoft.AspNetCore.App** version 2.1.5, but with current settings, version 2.1.1 would be used instead. To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish. Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore. For more information, see https://aka.ms/dotnet-runtime-patch-selection.

### Additional context
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by natemcmaster** [comment]
Just a hypothesis: omnisharp in VS Code may be messing with the project somehow. I tried to repro. The command line publish passed, but Omnisharp logs started showing the error you described. Does it work without VS Code open?

![image](https://user-images.githubusercontent.com/2696087/47944240-8960bd00-deb7-11e8-8fa2-4f276e0217e4.png)

**Comment by MPasadu** [comment]
I only tried in VS Code **and** Visual Studio and both show the same error.
I can try tomorrow with only terminal / cmd
