### ISSUE TITLE
Set EnvironmentName to Development by default

### ISSUE THREAD

**Issue by dustinmoris** [aspnet/AspNetCore#3878]
I was wondering if it would be possible to change the current default value of `IHostingEnvironment.EnvironmentName` to `Development` if nothing else is set.

Currently ASP.NET Core sets the default value to `Production` unless an environment sets the `ASPNETCORE_ENVIRONMENT` environment variable to something different. This feels like an odd choice, because it requires every developer to manually set that environment on their personal machines to `Development` in order to prevent an application trying to do things which it would only do on production (e.g. enable Google Analytics, etc.).

On the other hand it is much more reasonable to expect that a prod environment was configured with that environment variable to `Production` and everything else doesn't have to think about it.

I know this would be a breaking change, but would it be possible to get this into the next major release (ASP.NET Core 3.0)?

**Comment by davidfowl** [comment]
No, this was done because of security reasons. The mitigation is that all of the default templates and experiences set ASPNETCORE_ENVIRONMENT=Development by default.

cc @blowdart

**Comment by blowdart** [comment]
As @davidfowl says no. We default to the safer option. Production excludes things like detailed error messages and other stuff that should never be turned on in a production environment. You must opt-in to lower security. This won't change.
