### ISSUE TITLE
Using miltiple files in internationalization

### ISSUE THREAD

**Issue by Sandeep321** [aspnet/AspNetCore#3879]
I have gone through the .Net core internationalization concept and it looks really scary to me. It says I need to create my resource files matching with lets says a Controller in which I want to use it. Also, I need to inject the same in the controller as IStringLocalizer.

### Describe the solution you'd like
I wanted to create separate resx files for different types of messages(lets say info, warn and error). I would want to use all the files across all my controllers (maybe in some other classes as well). I don't want to face a situation where I will have to inject all the dependencies into my controller, one for each resource file. What if I have 10 resource files, I don't want to insert all of them into my controllers separately. 
Does anyone knows how to achieve that kind of scenario with .Net core.

**Comment by Sandeep321** [comment]
More details on above case:
As of now, I am required to inject the dependency of the resource file (IStringLocalizer) into my controller. What if I have multiple resource files as below:

Messages-Info.en.resx
Messages-Info.es.resx
Messages-Warn.en.resx
Messages-Warn.es.resx
Would you recommend to inject one dependency for each resource type into my controller like
MyController(IStringLocalizer<Messages-Info> infoLocalizer, IStringLocalizer warnLocalizer) {}`. In that case, what would I do if the resource tyes increase to 10 or 15?
Or is there a way to achieve this?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@Sandeep321, did you get an answer from StackOverflow already?
I believe you can register your own IStringLocalizer, which will actually handle the logic of choosing the right resource file internally. That way - you can always rely on a single dependency in your controller. @ryanbrandenburg, feel free to correct me or suggest a better option if there is one.

**Comment by Sandeep321** [comment]
Thank you so much guys for responding and sharing your views. Yes, I was able to achieve the above. I can give a brief below, please let me know if some code sample would be needed:
I actually created a handler which takes the IStringLocalizerFactory as dependency and then it has a private method to create IStringLocalizer based on the type of message being requested (Created an Enum for having the MessageType - Info, Warn and so on). Then the main method (public one which actually exposes the functionality outside) in handler uses that created IStringLocalizer to get the Value from the respective file.
Inject that handler in Controller to use the resource files. 
There are some details which should be taken care to get it really working. Would be happy to share if you want. Please let me know. Cheers.

**Comment by ryanbrandenburg** [comment]
Sounds like this is taken care of then. Closing.

**Comment by Sandeep321** [comment]
@mkArtakMSFT @ryanbrandenburg 
Just created a project to demo what I have done, maybe useful for some one. 
You can check https://github.com/Sandeep321/MultipleResourceForLocalization/tree/master/MultipleResourceForLocalization
