### ISSUE TITLE
how to use a resource file for two views in globalization and localization?

### ISSUE THREAD

**Issue by linghuchong123** [aspnet/AspNetCore#3886]
#how to use a resource file for two views in globalization and localization?
if I create more than 50 views, I need to create the same amount of resource file
， Isn't that a little ridiculous? or am I stupid?

#I Scaffold the identity area and need to use different localization string to sent the verify email, (ll_ll)how to make the page model localization? It doesn't seem to be written in the Microsoft Docs，even the localization of identity area wasn't mentioned

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
