### ISSUE TITLE
Performance issues and unusual CPU cycles in Middlewares

### ISSUE THREAD

**Issue by ftaran** [aspnet/AspNetCore#3890]
### Describe the bug
I have used visual studio performance profiling tool to profile my asp.net core v2.0.7 api.

we are seeing a lot of time being spent in the middle wares, and we cant really check whats causing it as the tool indicates that the time is being spent in the external code.
<img width="635" alt="3" src="https://user-images.githubusercontent.com/7329422/48064369-7bfd4880-e1bf-11e8-8e48-220e09becaeb.PNG">
<img width="634" alt="6" src="https://user-images.githubusercontent.com/7329422/48064367-7b64b200-e1bf-11e8-9ef7-8fb1e985f004.PNG">
<img width="636" alt="2" src="https://user-images.githubusercontent.com/7329422/48064368-7bfd4880-e1bf-11e8-8ca1-328d0442e649.PNG">
<img width="635" alt="4" src="https://user-images.githubusercontent.com/7329422/48064371-7bfd4880-e1bf-11e8-9f1c-ef6d8a8dc914.PNG">
<img width="636" alt="5" src="https://user-images.githubusercontent.com/7329422/48064372-7bfd4880-e1bf-11e8-8bed-c01f7ffd0bcc.PNG">

**Comment by khellang** [comment]
All requests go through the middleware pipeline. Each middleware calls the next, which means most time will be spent in the first middleware, then the next, and the next and so on:

![Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index/_static/request-delegate-pipeline.png?view=aspnetcore-2.1)

This is expected. You can read more about it in [the docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1).

**Comment by ftaran** [comment]
@khellang I already know the above, what stands out here is that a lot of cycles are being spent in external code, and by a lot I mean something around 20%, and the reason I have posted here is that the so called external code in the middleware is all .net core packages and pipeline.

**Comment by Eilon** [comment]
@sebastienros - can you provide assistance on how to investigate this?

**Comment by sebastienros** [comment]
If you use PerfView you should be able to see more information: https://github.com/Microsoft/perfview

I'll let you google for some tutorials and videos on how to do it, and if you have any issues finding out where it's spending the CPU cycles then we might help you.
