### ISSUE TITLE
Test failure: ClosesConnectionOnServerAbort

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3945]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
Should not reach here
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.ServerAbortTests.ClosesConnectionOnServerAbort() in /_/test/Common.FunctionalTests/ServerAbortTests.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test ClosesConnectionOnServerAbort at 2018-11-06T10:52:29
| [0.001s] FIXTURE:HttpTestSite Debug: Method: GET, RequestUri: 'http://localhost:51477/Abort', Version: 2.0, Content: <null>, Headers:
|                                      {
|                                      }
| [0.005s] FIXTURE:HttpTestSite Warning: StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
|                                        {
|                                          Server: Microsoft-IIS/7.5
|                                          Date: Tue, 06 Nov 2018 10:52:29 GMT
|                                          Content-Type: text/html
|                                          Content-Length: 2548
|                                        }
| [0.005s] FIXTURE:HttpTestSite Warning: <!DOCTYPE html>
|                                        <html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
|                                            <head>
|                                                <meta charset="utf-8" />
|                                                <title> HTTP Error 500.0 - ANCM In-Process Handler Load Failure </title>
|                                                <style>
|                                                    body {
|                                                        font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif;
|                                                        font-size: .813em;
|                                                        color: #222;
|                                                        background-color: #fff;
|                                                    }
|                                                    h1, h2, h3, h4, h5 {
|                                                        /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/
|                                                        font-weight: 100;
|                                                    }
|                                                    h1 {
|                                                        color: #44525e;
|                                                        margin: 15px 0 15px 0;
|                                                    }
|                                                    h2 {
|                                                        margin: 10px 5px 0 0;
|                                                    }
|                                                    h3 {
|                                                        color: #363636;
|                                                        margin: 5px 5px 0 0;
|                                                    }
|                                                    code {
|                                                        font-family: Consolas, "Courier New", courier, monospace;
|                                                    }
|                                                    body .titleerror {
|                                                        padding: 3px 3px 6px 3px;
|                                                        display: block;
|                                                        font-size: 1.5em;
|                                                        font-weight: 100;
|                                                    }
|                                                    a {
|                                                        color: #1ba1e2;
|                                                        text-decoration: none;
|                                                    }
|                                                        a:hover {
|                                                            color: #13709e;
|                                                            text-decoration: underline;
|                                                        }
|                                                    li {
|                                                        margin: 5px;
|                                                    }
|                                                </style>
|                                            </head>
|                                            <body>
|                                                <h1> HTTP Error 500.0 - ANCM In-Process Handler Load Failure </h1>
|                                                <h2> Common causes of this issue: </h2>
|                                                <ul>
|                                                    <li> The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found. </li>
|                                                    <li> The in process request handler, Microsoft.AspNetCore.Server.IIS, was not referenced in the application. </li>
|                                                    <li> ANCM could not find dotnet. </li>
|                                                </ul>
|                                                <h2> Troubleshooting steps: </h2>
|                                                <ul>
|                                                    <li> Check the system event log for error messages </li>
|                                                    <li> Enable logging the application process' stdout messages </li>
|                                                    <li> Attach a debugger to the ap
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588632&buildTypeId=XPlat_Windows_Win7_Universe) on master at 1:31:38 AM:
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- (And 1 more test failures in this build)

**Comment by jkotalik** [comment]
@muratg @Eilon I'll look at all of these test failures. 

@ryanbrandenburg We should move all automated test failures to an internal repo. Customers shouldn't be spammed with test failures like this.

**Comment by Eilon** [comment]
I logged https://github.com/aspnet/AspNetCore-Internal/issues/1277 to track consolidating all RAAS issues in one internal repo.

**Comment by jkotalik** [comment]
Tests have been disabled. Will wait for master to pass before closing.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588949&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:15:09 PM:
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- ClosesConnectionOnServerAbort
- (And 1 more test failures in this build)
