### ISSUE TITLE
App_Offline - Linux/Apache

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#3949]
_From @mbuchok on Tuesday, 06 November 2018 16:04:34_

# Issue Title

app_offline equivalent for Linux/Apache

# General

Perhaps I'm still a little new to Linux, but is there an app_offline equivalent for dotnet core hosted in a Linux environment... specifically using CentOS and Apache?

_Copied from original issue: dotnet/core#2039_

**Comment by jkotalik** [comment]
Dropping app_offline.htm to stop a site is purely a feature of the AspNetCoreModule. See: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#app_offlinehtm

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
