### ISSUE TITLE
Invoke component by name

### ISSUE THREAD

**Issue by tidyui** [aspnet/AspNetCore#3958]
I opened an issue in the Blazor repo regarding invoking components here:

https://github.com/aspnet/Blazor/issues/1644

As I’ve read that server side blazor will be a part of .NET Core 3.0 (Razor components) I just thought I’d add a reference to the request here so it doesn’t get missed if different teams are working on the different repositories.

Regards

Håkan

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tidyui.
You're right, very soon the issues will be tracked here. However for now we track all the Blazor related issues in Blazor repo. So we're closing this issue now in favor to the one you've filed in Blazor repo.
