### ISSUE TITLE
Managed Pipeline Mode

### ISSUE THREAD

**Issue by Looooooka** [aspnet/AspNetCore#3960]
### Describe the bug
The instructions on publishing a NET Core app state one should set .NET CLR Version to No Managed Code.
The screenshot in the instructions shows managed pipeline mode set to "Integrated"
If I do that the pool dies immediately. It only works in Classic Mode. 
This happens in 2.1 and 2.2 versions using dotnet.exe or the selfhosted exe option in web.config.
Are those instructions not clear enough or does one have to add something to the code to enable "managed pipeline mode"
I also upgraded to 2.2 in hopes to get the hostingmodel "InProcess" to work again(it does if I set the mode to Class" and perhaps actually get the netcore app to start as soon as the website is turned on.
This of course does not work.
Does anyone have any clear instructions how to enable the website to wakeup/preload?
applicationInitialization settings in web.config are ignored. The "preload" option only works in a managed pipeline and like I stated above I cannot get it to work with "no managed code" and "integrated mode" because it simply dies.

Windows 2016, IIS 10. Just updated everything to 2.2 in hopes it would work there. It does not. I am stuck with classic mode or  setting the CLR version to 2 or 4 to enable "integrated mode" which again does nothing sice applicationInitialization doesn't do anything in that case either.

**Comment by shirhatti** [comment]
> The "preload" option only works in a managed pipeline and like I stated above I cannot get it to work with "no managed code" and "integrated mode" because it simply dies.

Can you share app logs/Windows Event logs in the case where your application "simply dies"?

**Comment by Looooooka** [comment]
Will do tomorrow when I'm at work. But just so we don't waste your time for nothing...should managed pipeline even work when set to 'integrated' and clr version is set to 'no managed code'?
I'm thinking the image used was just took too soon(image on 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1).

I've just settled for classic mode which works.
Unfortunately no application init setting works in any combination I've tried. 
Was hoping iis could at least open the url when the app pool/application was started using the application initialization setting in web.config or iis applicationHost.config so timers inside the application would start without the need to actually open the page first. That was how the whole no clr/managed/classic pipeline problem started.
I'm just going to use classic mode and set up a schedules task to connect to the site every couple of minutes to kickstart the application until some sort of working solution gets added to the aspnet core iis module.

**Comment by Looooooka** [comment]
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-IIS-W3SVC-WP" Guid="{670080D9-742A-4187-8D16-41143D1290BD}" EventSourceName="W3SVC-WP" /> 
  <EventID Qualifiers="32768">2303</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-11-08T11:46:24.017555800Z" /> 
  <EventRecordID>28915</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>******</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="ApplicationPool">******</Data> 
  <Binary>7E000780</Binary> 
  </EventData>
  </Event>

**Comment by Looooooka** [comment]
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-IIS-W3SVC-WP" Guid="{670080D9-742A-4187-8D16-41143D1290BD}" EventSourceName="W3SVC-WP" /> 
  <EventID Qualifiers="32768">2303</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-11-08T11:46:24.017555800Z" /> 
  <EventRecordID>28915</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>******</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="ApplicationPool">******</Data> 
  <Binary>7E000780</Binary> 
  </EventData>
  </Event>`

**Comment by Looooooka** [comment]
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Microsoft-Windows-IIS-W3SVC-WP" Guid="{670080D9-742A-4187-8D16-41143D1290BD}" EventSourceName="W3SVC-WP" /> 
  <EventID Qualifiers="32768">2303</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-11-08T11:46:24.017555800Z" /> 
  <EventRecordID>28915</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>******</Computer> 
  <Security /> 
  </System>
<EventData>
  <Data Name="ApplicationPool">******</Data> 
  <Binary>7E000780</Binary> 
  </EventData>
  </Event>`

**Comment by muratg** [comment]
@Looooooka Can you also share the text representation of the error? Thanks.

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
