### ISSUE TITLE
Identity survey should start with Do You Currently Use

### ISSUE THREAD

**Issue by mwpowellhtx** [aspnet/AspNetCore#3963]
All due respect, but I'm not sure who *Microsoft* and/or *.NET Foundation* are trying to fool with this one. The [survey](/aspnet/Announcements/issues/327) literally ***ends*** with *Do you currently use ASP.NET Core Identity*. The survey should ***begin*** with that. All the rest of that leading up to that is a marketing attempt at phishing for proprietary information.

At any rate, on with the substantive feedback. Chiefly, a couple of critical, I would argue academic, decisions are baked in to the "default" offering:

* First, that I know of, the default ``Id`` is assumed to be ``Int32``, I think. What happens when you want to key on something more robust, like a ``Uuid`` or ``Guid``? Mainly this one is very academic, IMO. It's fine for the academic demo or illustrative exercise, but ``Int32`` is impractical in most vertical, real-world applications.

* Second, assumes a strong dependency on *Entity Framework* is assumed out of the box with the "front-facing" packages. If I wanted to defer to another service, repository, database, etc... ? Speaking as an entrepreneur and architect, I do not want to be roped into this strong of a dependency at this level; I want to leave that point of decision open to as late in the stage as can possibly be managed, and then I want the choice which market offering to run with, which may change depending on the service requirements that I have to meet.

I've broached this topic on several occasions during ASP.NET stand up and received anywhere from peripheral acknowledgement, to downright denial, if dismissal, from the *Microsoft* and/or *.NET Foundation* folks. To be fair, the stand up is neither the time nor the place to go into that much depth on the subject, but I am left with the impression the business models are in tension, at best, when there is no substantive feedback at all following up.

It is possible to re-work those elements with some effort, but it is not trivial. Trust me, I've done it before, even extending through my Claims API. But it's no joke ripping those dependencies out of, say, a *default MVC application* with "login support", for instance.

I am posting here for starters after being forwarded from the "announcements" forum. If there's an Identity repository, I'll be glad to post there instead.

**Comment by blowdart** [comment]
If you'd gone through the survey you'd see this is the first page. The initial questions are standard across all of our devdiv customer surveys to give us comparison points. Choosing Yes for the Do You Currently Use ASP.NET Identity then leads to further questions where you can express concerns such as those above. As for followup on standups, as we don't take any follow up methods in standup (GDPR would make a meal of you giving out email addresses in stand up chat), the survey is your best chance to make your voice heard.

**Comment by mwpowellhtx** [comment]
Do you have a set of those questions and their form of response so that I can evaluate whether it is worthwhile spending the calories there? Thanks!
