### ISSUE TITLE
Realtime Collect GC metrics for .Net Core 2.1  App running on Linux

### ISSUE THREAD

**Issue by alex-user** [aspnet/AspNetCore#3965]
I want to realtime collect GC metrics from applications running on Linux in production. I have an assumption that it is not possible to obtain reliable data about the application memory state(all memory types) running from docker or kubernetes. Accordingly, the data received from the GC may also be not unreliable or completely unreliable.

Perhaps someone faced with similar issues and can share experiences
Very grateful for any answer.

**Comment by gleocadie** [comment]
Hello @alex-user , we (@ Criteo) are working on this. I have PR on TraceEvent library which allows processing event in real-time (https://github.com/Microsoft/perfview/pull/340) . I have implemented the live session protocol of LTTng (not yet open sourced, but will be).
Currently, we are currently facing an issue: the LTTng relay being flooded by events, which makes the processing of events not really real-time :(

**Comment by alex-user** [comment]
Hello @gleocadie, thank you for answer
