### ISSUE TITLE
Add Stream to Pipe Adapter

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#3966]
In 3.0, we will be starting to expose Pipes directly across the AspNetCore stack via PipeReader and PipeWriter. The initial design is to have new properties directly on the HttpContext to get `HttpRequest.Body` as a PipeReader and `HttpResponse.Body` as a PipeWriter. 

One of the first needs we have is the ability to adapt a Stream into a Pipe. For example, when a middleware overwrites the `Response.Body` with a new stream, like [ResponseCompression](https://github.com/aspnet/BasicMiddleware/blob/master/src/Microsoft.AspNetCore.Buffering/ResponseBufferingMiddleware.cs#L36), Calling `response.PipeWriter` should return a PipeWriter that reflects the change made to the stream.

**Comment by Tratcher** [comment]
And a Pipe to Stream adapter...

**Comment by jkotalik** [comment]
https://github.com/aspnet/AspNetCore/issues/3971; probably don't want to implement both adapters in the same PR 😄

**Comment by jkotalik** [comment]
Majority of the work is done.

**Comment by CZEMacLeod** [comment]
@jkotalik I'm slightly worried that these adapters are in the System.IO.Pipelines namespace and will be embedded in aspnetcore rather than available separately as they could be added to the System.IO.Pipelines package and used right now in applications other than aspnetcore.

**Comment by jkotalik** [comment]
Plan is to have this eventually in System.IO.Pipelines in dotnet/corefx. So don't fret 😄
