### ISSUE TITLE
Re-implement the FormReader on top of the PipeReader

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#3967]
To verify that our pipe adapter actually works, we should change FormReader to use PipeReader and verify that the pipe adapter works. Eventually, we will optimize FormReader to not use an adapted pipe and obtain the PipeReader directly from a feature, but this will give us confidence that the PipeAdapter is usable.

**Comment by Tratcher** [comment]
We'll need to redesign the request buffering feature the form reader uses:
https://github.com/aspnet/AspNetCore/blob/f2e6e6ff334176540ef0b3291122e359c2106d1a/src/Http/Http/src/Features/FormFeature.cs#L139-L142
