### ISSUE TITLE
Add IRequestBodyPipeFeature and IResponseBodyPipeFeature

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#3972]
The IRequestBodyPipeFeature and IResponseBodyPipeFeature will be used to detect if the HttpContext has an underlying Pipe behind the HttpRequest.Body/HttpResponse.Body.

When calling HttpRequest.PipeReader/ HttpResponse.PipeWriter, instead of created an adapted stream, if the corresponding feature is set, it will return the pipe directly rather than creating an adapter.

**Comment by davidfowl** [comment]
Strawman:

```C#
public interface IRequestBodyPipeFeature 
{
    PipeReader PipeReader { get; set; }
}

public interface IResponseBodyPipeFeature 
{
    PipeWriter PipeWriter { get; set; }
}
```

**Comment by benaadams** [comment]
One interface and inherit from `IDuplexPipe`?
```csharp
public interface IBodyPipeFeature : IDuplexPipe
{
    new PipeReader Input { get; set; } // override to add setter
    new PipeWriter Output { get; set; } // override to add setter
}

public class HttpRequest
{
    public PipeReader PipeReader { get; set; }
}

public class HttpResponse
{
    public PipeWriter PipeWriter { get; set; }
}
```
Then its a single lookup to get both request and response pipes

**Comment by davidfowl** [comment]
No, we discussed this, we want it to be possible to replace one feature without impacting the other. Nothing deals manipulating both the request body and response body at the same tine.

**Comment by benaadams** [comment]
`DefaultHttpContext` deals with [setting them both up at the same time](https://github.com/aspnet/HttpAbstractions/blob/1d3521113ad69a9903d1590c77d67da04c5f5dfd/src/Microsoft.AspNetCore.Http/DefaultHttpContext.cs#L39-L55); then for changing one at a time its the same cost as two interfaces (as it just ignores the other property).

Unless you are thinking of lazy creating the reader/writer even when its defined (i.e. only when `HttpRequest.PipeReader` is called the first time)?

**Comment by Tratcher** [comment]
Specifically we don't have any examples of middleware that deal with both request and response body. E.g. if response compression wants to wrap / adapt the body it's only going to be dealing with the response body, nothing changes for the request.

**Comment by davidfowl** [comment]
@jkotalik can you make sure we have issues tracking the work in kestrel and iis integration

**Comment by jkotalik** [comment]
For sure.
