### ISSUE TITLE
Use ProducesAttribute to match routes

### ISSUE THREAD

**Issue by ruimaciel** [aspnet/AspNetCore#3974]
In ASP.NET core 2.1, if two actions are assigned the same request and route but are marked with distinct media types with `ProducesAttribute`, a request sent to one of the routes still triggers a 500 Internal Server Error by throwing an exception `Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException: Multiple actions matched`.

As some HATEOAS approaches require sending different contents depending on the media type selected by the content negotiation process (for instance, HAL), it would be very useful if ASP.NET Core considered media types specified with `ProducesAttribute` when matching actions to requests.

(This issue is a concrete suggestion on how to implement #3891)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ruimaciel.
This is not something we plan to support in the near future. However, as @JamesNK has shared in the referenced issue, you can use the sample he had provided https://github.com/aspnet/samples/pull/22/files to achieve what you need.
