### ISSUE TITLE
Have a project-wide flag to disable MVC

### ISSUE THREAD

**Issue by mythz** [aspnet/AspNetCore#3977]
Following from https://github.com/aspnet/AspNetCore/issues/3755#issuecomment-436764013

If MVC is going to be in all "Microsoft.AspNetCore.App" projects it would be useful to have a project-wide flag to specify MVC is not used so all tooling enabled and metadata added because of MVC can check against this flag to prevent them from running.

Issues I ran into when creating a non MVC project was needing to explicitly disable:

    dotnet publish -c Release /p:MvcRazorCompileOnPublish=false

And to prevent non essential metadata to be generated with: 

    <PreserveCompilationContext>false</PreserveCompilationContext>

Ideally this flag would prevent anything else that's only added or running because of MVC.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mythz.
@rynowak, thoughts?

**Comment by rynowak** [comment]
What are the problems you're solving by doing these things?

**Comment by mythz** [comment]
@rynowak please read the linked thread for details, also when enabling invasive magical behaviour by default it’s naturally a good idea to have a feature flag to be able to disable them.

**Comment by rynowak** [comment]
So I'm looking at your comments here: https://github.com/aspnet/AspNetCore/issues/3755#issuecomment-436722829

`PreserveCompilationContext` is a feature of the web SDK that generates a manifest of the application's dependencies and compilation references. It already has an on/off.

What's the issue with `/p:MvcRazorCompileOnPublish=false`? If this is doing work when you have no `.cshtml` files then that sounds like a bug that should be fixed.

**Comment by mythz** [comment]
We shouldn’t have to hunt for all these switches, please provide a feature flag that disables anything required by MVC that we can disable in non MVC apps so these bugs are not possible since they won’t be running.

**Comment by mkArtakMSFT** [comment]
@danroth27, moving this to Backlog for now. Would be interested in your opinion.

**Comment by dcb99** [comment]
I think this is a great idea. I don't use any aspects of MVC in my core apps, and it would be great to not have the extra bloat that comes with having to use MVC.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we can do easily so we will be closing this. Given it's a strategic change, it may come up again in the future if we decide to do this in the future.
