### ISSUE TITLE
Clientvalidation for numbers with decimals are wrong, when using comma as separator

### ISSUE THREAD

**Issue by ClausSuperusers** [aspnet/AspNetCore#3978]
Apparently the Client validation, used by the MVC system, doesn't support comma as separator for decimals.
Unfortunately, the browser does, which results in being unable to enter values correctly.

Values are displayed correctly (with a comma), but validation rejects the value, when saving.
![browsererror](https://user-images.githubusercontent.com/25054509/48209140-b52ae980-e374-11e8-9388-8b6c65f2dffe.PNG)
Definition in the datamodel:
`public decimal Price { get; set; }`
I've tried Edge, Firefox and Chrome - same issue for all.

It's an annoying problem, that makes it difficult to create otherwise simple pages

**Comment by SIkebe** [comment]
@ClausSuperusers ?

**Comment by ClausSuperusers** [comment]
Sorry about the first version - was confused by the layout....

**Comment by SIkebe** [comment]
https://stackoverflow.com/a/48247324/8778560

**Comment by ClausSuperusers** [comment]
@SIkebe You are right, this IS a third party problem, BUT the MVC template applies this by default, effectively making a simple task quite a lot more difficult, for a lot of people.
Microsoft has made a lot of nice work, in order to support different cultures, but unfortunately missed this one.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
