### ISSUE TITLE
automatic compile like Webforms Website

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetCore#3988]
is there a possibilty to automatically rebuild the / one file on code change like ASP.NET Webforms Website?

I am thinking of typically real websites, which a small amount of logic, Admin can go to code and change a line Sourcecode in cs/vb with notepad and done.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hannespreishuber.
This is not something we have support for. We do support runtime compilation for `.cshtml` files, but that's it.
