### ISSUE TITLE
Remove AuthenticationManager in 3.0?

### ISSUE THREAD

**Issue by drieseng** [aspnet/AspNetCore#3999]
**Microsoft.AspNetCore.Http.Authentication.AuthenticationManager** has been marked obsolete in 2.0.
Perhaps you should consider removing it (and related classes) in 3.0.

**Comment by Eilon** [comment]
Please post an announcement when this is done.

**Comment by HaoK** [comment]
I updated the one fowler posted since he had one that covered part of this change already:

https://github.com/aspnet/Announcements/issues/337
