### ISSUE TITLE
Unverifieble and unpredictable behaviour which cause to internal server error but which is not possible to reproduce

### ISSUE THREAD

**Issue by ivankarpey** [aspnet/AspNetCore#4001]
We run our platform on Apline Docker container and .NET Core 2.1 runtime. Yesterday one of our regular pages stop opening and start returning an internal server error page. We don't deploy any new code for a weeks already so that was strange. ok, if not code - than that's should be the data. So I get the local copy of released branch and connect to a production db, but the page was loaded perfectly fine for me on my machine with production data, but still failed on remote server. I checked all server parameters like freespace, memory ammount, pemissions - it all was fine. So I decide to restart app container and after just restarting it start work normally without any issues. So now I can't reproduce the problem. The single thing I have is error log for an exception was throwing before I restart application:

> System.InvalidOperationException: Sequence contains no matching element at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate) at AspNetCore.Areas_Dashboard_Views_Summary_Index.ExecuteAsync() at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context) at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts) at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result) at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync() at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) at KeyMarket.Web.Infrastructure.Middleware.UserActivityTrackMiddleware.Invoke(HttpContext context) in /app/src/Web/Infrastructure/Middleware/UserActivityTrackMiddleware.cs:line 23 at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ivankarpey.
Looks like the cause was the LINQ query which returned no elements, yet the code in the Summary page depends on it.
Unfortunately this is something in your code and you're in the best position to tackle it.

**Comment by ivankarpey** [comment]
The problem is that 'AspNetCore.Areas_Dashboard_Views_Summary_Index' is a static page with only 'Localizer' on it. So there is no any linq queries or whatever executed for that page whan it's loaded.

We also don't have any resource files available so far, but wrap strings to localizer for the future cases.

So I'm 99% confidend it's framework issue.
