### ISSUE TITLE
Logout button logs out but does not refresh the icon to display Login/Register button

### ISSUE THREAD

**Issue by bhrugen90** [aspnet/AspNetCore#4003]
### Describe the bug
Logout button logs out but does not refresh the icon to display Login/Register button after you add Area's to Project.

### To Reproduce
1. Using this version of ASP.NET Core 2.2 Preview 3
2. Run this code 
       a. Create a New Project with individual user account authentication and Scaffold Identity
       b. Add A new Area "Customer" and move home controller inside the Area.
       c. Move the Views for "Home" under "Customer" area.
       d. Run the project and register for a new user. And then hit the logout button.
3. See error : The logout button will still remain after you have logged out.

This works fine if you have not added Areas.

### Expected behavior
Once you hit logout button, it should be modified to Login.

**Comment by blowdart** [comment]
@HaoK

**Comment by HaoK** [comment]
This issue has already been fixed in the UI code, but looks like its just an issue where the scaffolded code is out of sync (needs to be updated)
 In Logout.cshtml.cs:

```
        public async Task<IActionResult> OnPost(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return Page();
            }
        }

```

The return Page should be a RedirectToPage():
```
// This needs to be a redirect so that the browser performs a new
                // request and the identity for the user gets updated.
                return RedirectToPage();
```

See https://github.com/aspnet/AspNetCore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V3/Account/Logout.cshtml.cs#L60

@ajcvickers @blowdart how do we route this to the scaffolding side to fix?

**Comment by ajcvickers** [comment]
Good question. Is this owned by the tools team? If so, I can bring it up in the sync next Thursday when I intend to talk about the need to improve the scaffolding U.I.

**Comment by HaoK** [comment]
i think so, I think its a manual process for them to pick up changes that we make from the UI, so that's why its out of sync

**Comment by HaoK** [comment]
Parking in preview 4 for now, basically need to sync up scaffolding contents with identity ui at some point
