### ISSUE TITLE
Microsoft.AspNetCore.DataProtection.DataProtectionProvider non-DI Create for AzureBlobStorage

### ISSUE THREAD

**Issue by tstone84** [aspnet/AspNetCore#4006]
I have a need to use DataProtectionProvider.Create() with AzureBlobStorage.  Currently, Create() doesn't support this use case.  I understand that with DI, I can use:
`services.AddDataProtection()
                    .SetApplicationName("ApplicationName")
                    .PersistKeysToAzureBlobStorage(blobContainer, "BlobName");`
However, I have a library that is shared with a netStandard application that can't use the ASP.Net Core DI system.

**Comment by blowdart** [comment]
The non-DI scenarios were always very limited to file systems only. This isn't supported I'm afraid.

**Comment by davidfowl** [comment]
Doesn't it work if you use the overload that takes `Action<IDataProtectionBuilder>`?

**Comment by tstone84** [comment]
The only Create overloads that takes `Action<IDataProtectionBuilder>` all take a `DirectoryInfo` as the first param, which I will not have since I'm using AzureBlobStorage. I'm referencing this:
[DataProtectionProvider.Create](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.dataprotectionprovider.create?view=aspnetcore-2.1)

**Comment by davidfowl** [comment]
Pass in a directory then the builder configuration for azure storage will override it (I believe)
