### ISSUE TITLE
Enum serialization in routes

### ISSUE THREAD

**Issue by JuanZamudioGBM** [aspnet/AspNetCore#4008]
using asp.net core 2.1

We have a web API that uses snake case serialization for all the properties including enums, to enable it we used this in the startup:

    services
        .AddMvcCore()
        .AddJsonOptions(opt =>
        {
            opt.SerializerSettings.DateTimeZoneHandling = Newtonsoft.Json.DateTimeZoneHandling.Local;
            opt.SerializerSettings.Formatting = Newtonsoft.Json.Formatting.None;
            opt.SerializerSettings.ContractResolver = new DefaultContractResolver
            {
                NamingStrategy = new SnakeCaseNamingStrategy { ProcessDictionaryKeys = true }
            };
            opt.SerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
            opt.SerializerSettings.Converters.Add(new StringEnumConverter());
        })
        .AddApiExplorer()
        .AddJsonFormatters(j => j.ContractResolver = new DefaultContractResolver { NamingStrategy = new SnakeCaseNamingStrategy() { ProcessDictionaryKeys = true } })

That works great on properties, but we are having problems with routing and enums, for example we have this enum (we also tried with JsonProperty but fails in the same way):

    [DataContract(Name = "document_type")]
    public enum DocumentType
    {
        [EnumMember(Value = "passport")]
        Passport,
    
        [EnumMember(Value = "proof_of_address")]
        ProofOfAddress,
    }

and we are trying to search documents by type, so we have this route:

    /clients/{clientId:guid/documents/{documentType}

and this in the controller:

    [HttpGet]
    [Route("/clients/{clientId:guid}/documents/{documentType}")]
    public async Task<IActionResult> FindClientDocuments([FromRoute] Guid clientId, [FromRoute] DocumentType documentType)

with this route everything works great:

/clients/60a00cd4-59e2-4f52-871a-4029370f6dd8/documents/ProofOfAddress

but does not work with this:

clients/60a00cd4-59e2-4f52-871a-4029370f6dd8/documents/proof_of_address

In the latter case the enum is always the default value or if we add an action filter the error is "The value 'proof_of_address' is not valid."

Is there a way to make this escenario works besides trying to convert the value myself with a filter?

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JuanZamudioGBM.
@JamesNK, can you please look into this? Thanks!

**Comment by JamesNK** [comment]
Hi Juan

The reason you are getting that error is Json.NET isn't the library converting the enum so the `EnumMember` attributes are not being used. You can get around this by writing a TypeConverter and applying it to your enum:

```cs
public class CustomEnumConverter<T> : TypeConverter
{
    public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
    {
        var s = value as string;
        if (string.IsNullOrEmpty(s))
        {
            return null;
        }

        return JsonConvert.DeserializeObject<T>(@"""" + value.ToString() + @"""");
    }
}

[TypeConverter(typeof(CustomEnumConverter<DocumentType>))]
public enum DocumentType
{
    [EnumMember(Value = "passport")]
    Passport,

    [EnumMember(Value = "proof_of_address")]
    ProofOfAddress,
}
```

**Comment by JuanZamudioGBM** [comment]
Thanks @JamesNK

**Comment by JamesNK** [comment]
Great! Closing as answered.
