### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by h0730303779** [aspnet/AspNetCore#4010]
### Describe the bug
Unable Debug ConsoleApp    String exceeds 20W  on  dotnetcore  !!!

### To Reproduce
1. Net Core 2.1 
2. Run this code 
            var  s = '**'; //Please enter the 20W string
            Console.WriteLine(s.Length);
            Console.ReadLine();

3. 
4. See images

5.No problem for Same code  on framework  

why?

### Expected behavior
debug

### Screenshots
on netcore 2.1
![image](https://user-images.githubusercontent.com/16299810/48388375-1582a800-e734-11e8-94fb-e829cce27563.png)

on  framework  4.5
![image](https://user-images.githubusercontent.com/16299810/48388249-a1e09b00-e733-11e8-8aa4-601d1b0a50a9.png)

**Comment by Eilon** [comment]
This issue was moved to dotnet/core#2058
