### ISSUE TITLE
Support embedded AspNetCore Web API in DotNet Native UWP using TestServer

### ISSUE THREAD

**Issue by bridgesquared** [aspnet/AspNetCore#4014]
### Use Case
We have a UWP LOB App designed to talk to an AspNetCore Web API server. Though we are working on server implementations for both local network IIS and Azure, we would also like to be able to provide a MS Store APP that works standalone with as much shared code as possible.

The choice of a MS Store UWP APP would enable us to have an almost frictionless install for single users (which are a big part of our intended market of micro-businesses) but requires that the app be able to pass DotNet native compilation.

### Preferred Solution
The preferred solution is that we would like to embed the back-end logic, including EF Core database context, in the UWP App and to then host that using `TestServer` inside the UWP Process. We would then get maximum code re-use and be able to support both the embedded (local) use case as well as remote (networked) servers with one application.

### Alternatives
The first approach we considered was to separate the server Web API controller logic from the pure business logic and database context, use MediatR as a commanding layer in the client and be able to compile the UWP app using the shared code without the need for AspNetCore. This approach proved expensive in terms of extra layers of code to allow supporting this façade approach as well as pure HttpClient to server comms.

The other approach we have considered is to look to providing a separate install for the server component but we've found that for a lot of our users this is just too difficult as they aren't particular computer savvy - they really just want to download it from the store and get cracking. A similar approach would be just to provide a classic cloud backend but that requires investment in terms of making the server multi-tenant, payment and billing issues and ultimately the app targets very sensitive data and we feel that potential users won't want to immediately incur cloud hosting fees.

### Progress

We have actually made substantial progress in getting the preferred solution to work (currently using Mvc 2.1.3):

-  Instead of using automatic discovery of DLLs during startup (which isn't supported on UWP DotNet Native) we use the `ApplicationPartManager` and `ApplicationPartFactory` to enumerate the project DLLs (thanks to leads from #2116).
- Instead of using full fat AspNetCore.Mvc we only use AspNetCore.Mvc.Core
- The final obstacle was the `async` actions on controllers were throwing `PlatformNotSupported`. We tracked this down to the following lines in `AwaitableInfo` (from the `Microsoft.Extensions.ObjectMethodExecutor.Sources` NuGet package) :

https://github.com/aspnet/Extensions/blob/d2f4c6a2ed30be5fae6ec166bfb7a3073c9f1d17/src/Shared/src/ObjectMethodExecutor/AwaitableInfo.cs#L77-L99

The issue seems to be that `GetRuntimeInterfaceMap()` just doesn't work under DotNet Native. We have forked Mvc.Core  and changed the class to use the following:

https://gist.github.com/bridgesquared/c355b5afbc91592cecdcf8b2e2e6cdec

Where instead of using `GetRuntimeInterfaceMap()` we just use `GetRuntimeMethods()` which is supported. This works for us, I know the fix isn't theoretically solid because in theory an awaitable type could have multiple methods name `OnCompleted` or `UnsafeOnCompleted` but in practice that seems very unlikely, if not impossible.

So I'm looking to see whether we can get `AwaitableInfo` tweaked so that it will work on DotNet Native. This would mean we wouldn't have to fork Mvc :-) 

It seemed right to start the issue here, but can move it over to the Extensions repo if that's preferred. 

Look forward to hearing your thoughts. Thanks

**Comment by Tratcher** [comment]
Have you read https://github.com/aspnet/Announcements/issues/324 yet about the 3.0 framework plans?

**Comment by anurse** [comment]
Closing as we don't plan to support .NET Standard in ASP.NET Core 3.0.
