### ISSUE TITLE
Performance considerations of IQueryable vs async.

### ISSUE THREAD

**Issue by joshmackey** [aspnet/AspNetCore#4018]
Based on my understanding, you should almost always want to use async in controllers during any db calls so that the thread can be released to work on something else.

However, with entity framework and OData, you return either a IEnumerable<T> or a IQueryable<T> which then gets, presumably, iterated over synchronously. Even if the result is paged, this still blocks the aspnet core thread while whatever backing DB exists gets queried right?

Blocking the thread seems like it would be a performance hit over calling async methods directly and then returning a task. Am I correct or am I missing something?

**Comment by divega** [comment]
@joshmackey not sure to what exact version of EF you are referring to, or what OData implementation. In any case, queries from all recent versions of EF and EF Core can be iterated over asynchronously.

We also support methods like ToListAsync and ToArrayAsync, which allow consuming query results asynchronously to build common enumerable types. For example, `ToListAsync<T>()` returns a `Task<List<T>>`.

Not sure if OData .NET handles async query results from EF or EF Core today, but the [upcoming support for IAsycEnumerable in C# 8](https://blogs.msdn.microsoft.com/dotnet/2018/11/12/building-c-8-0/) will establish a standard way to represent async streaming results, which could be adopted by OData .NET.

**Comment by joshmackey** [comment]
Ignoring OData.NET for now, I guess what I'm referring to is, if you're using EF Core and assuming `Foo` is `DbSet<Foo>`, you can return `Foo.Where(b => booleanproperty)` and it appears that aspnet core enumerates the results from the IEnumerable which would make it synchronous. 

Sure you could call the aync methods manually and return those results as a Task, but can aspnetcore detect those and call them automatically?

**Comment by joshmackey** [comment]
Removing the `XY problem` part of this discussion. I'm attempting to write a QueryProvider that is usable with OData.NET and aspnetcore. The OData.NET part is just middleware that modifies the `IQueryable` so I don't think it changes much in the discussion. EF Core also uses its own QueryProvider but when digging through the code, it still appears to me that if the query is returned in a controller directly without executing it asynchronously first, it gets executed synchronously via the `IEnumerable`

**Comment by John0King** [comment]
I have a question of the `IQuerable<T>` :
I know `List<T>`  will hold every object inside it , a large `List<T>` will consume large memory, and u can not add more than `Int32.MaxValue` items.

 `IQuerable<T>` inherit  from `IEnumerable<T>` , and a pure  `IEnumerable<T>` seems can have unlimited items. I wonder that is  `IQuerable<T>` a pure `IEnumerable<T>` implementation or It's like `List<T>`

**Comment by divega** [comment]
@John0King Implementations of IQueryable are typically streaming. I.e. they are consumed like IEnumerable and they don’t need to hold all the elements they return in memory. Of course it is possible to create a LINQ to Objects IQueryable by call AsQueryable on any IEnumerable, including a List.

**Comment by divega** [comment]
> Ignoring OData.NET for now, I guess what I'm referring to is, if you're using EF Core and assuming Foo is DbSet<Foo>, you can return Foo.Where(b => booleanproperty) and it appears that aspnet core enumerates the results from the IEnumerable which would make it synchronous.

This seems interesting. I am not very familiar with functionality that will automatically iterate over an IEnumerable that you return from a controller action in ASP.NET Core. Presumably we could add support for doing it asynchronously if the returned type is IAsyncEnumerable. But out of LINQ query operators, EF Core queries are statically typed as IQueryable. You need to try to cast them to another interface to find out that you can consume the results asynchronously. Maybe this could be made automatic.

@Eilon @rynowak @davidfowl anything like this in the radar for 3.0?

**Comment by Eilon** [comment]
You can return any model data type you want from an MVC controller action. Then in the Razor view you should be able to consume that model data type (e.g. `IAsyncEnumerable<T>`) and iterate over that in the CSHTML file. But I'm not sure quite how async it would be within the CSHTML file.

@rynowak / @NTaylorMullen / @pranavkm - thoughts on that?

**Comment by NTaylorMullen** [comment]
It'd be async and have the same restrictions as any other `await` call had in our cshtml file. Should definitely always `await` a task returning method in a cshtml though 😄, otherwise you'd be asking for problems.

**Comment by pranavkm** [comment]
> You can return any model data type you want from an MVC controller action

The one caveat I would add is that ExceptionFilters in MVC do not handle errors thrown while executing an action result, in this case views. This might be relevant if you expect iterating the async sequence to throw. Handling the exception in a middleware will be fine.

**Comment by rynowak** [comment]
One area where I'd really recommend buffering is when returning data as JSON (formatters). None of the formatter implementations we ship are really async - so they will do blocking calls to iterate.

**Comment by divega** [comment]
Ok, if we returned `IAsyncEnumerable<T>` it wouldn’t actually be a Task returning async method, and based on the restriction that formatters are not async, and the recommendation to buffer, I understand the guidance is still to not return the query directly and instead always call ToListAync() or similar. 

I also hear that there are no plans to handle controller actions that return async streams in ASP.NET Core.

**Comment by joshmackey** [comment]
I'm using webapi specifically, not a razor view.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
