### ISSUE TITLE
Review and update external dependencies

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4019]
We should review our dependencies and see what we should update:

* AngleSharp
* Google.Protobuf
* Microsoft.Azure.\*
* Polly
* StreamJsonRpc
* Serilog
* System.Reactive.Linq
* Utf8Json
* WindowsAzure.Storage

This review does not mean we _have_ to update. We just want to check and make sure we're not missing something important.

**Comment by DarkCompiled** [comment]
Instead of using "WindowsAzure.Storage" on "Microsoft.AspNetCore.DataProtection.AzureStorage", please use the new XSCL "Microsoft.Azure.Storage.*", otherwise we will keep having namespace conflicts all over the place. :confused:

**Comment by hansmbakker** [comment]
This usage of is `Microsoft.AspNetCore.DataProtection.AzureStorage` using a nuget package from 2017 😱 (WindowsAzure.Storage) is an issue for my project as well. Results in:
```
The type 'CloudStorageAccount' exists in both 'Microsoft.Azure.Storage.Common, Version=9.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.WindowsAzure.Storage, Version=8.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

**Comment by natemcmaster** [comment]
@DarkCompiled - I updated our Azure dependency in https://github.com/aspnet/AspNetCore/pull/9465. We will continue to review others in the coming weeks.

**Comment by JunTaoLuo** [comment]
Here's our current status (WIP still checking a few third party dependencies):

| Package | Version in AspNetCore | LatestVersion | Comment
| ----------- | ----------- | --- | --- |
| AngleSharp | 0.9.9 | 0.12.1 / 0.13.0-alpha-748 | 
| Google.Protobuf | 3.7.0 | 3.8.0 | Used in templates, should update. Also applies to Grpc.* packages
| Microsoft.Azure.KeyVault | 2.3.2 | 3.0.3 | 
| Microsoft.Azure.Storage.Blob | 10.0.1 | 10.0.3 | This is not used in our build anymore, remove
| Polly | - | - | Where is this used? I can't find any reference to it in our repos
| StreamJsonRpc | 1.5.43 | 2.0.187 | This is only used in https://github.com/aspnet/AspNetCore/blob/f0df10f211b5ea8192579808c223e82aab549268/src/Components/Blazor/BlazorExtension/src/Microsoft.VisualStudio.BlazorExtension.csproj#L134 which is not managed like the rest of our dependencies. Should consult the blazor team about this.
| Serilog.Extensions.Logging | 1.4.0 | 2.0.4 / 3.0.0-dev-10240 | 
| Serilog.Sinks.File | 4.0.0 | 4.1.0-dev-00838 | 4.0.0 is the latest stable version, should keep using it.
| System.Reactive.Linq | 3.1.1 | 4.1.5 / 4.2.0-preview.102 | 
| Utf8Json | - | - | This is not used in our build anymore, remove
| WindowsAzure.Storage | - | - | This is not used in our build anymore, remove
| StackExchange.Redis | 2.0.513 | 2.0.601 | 
| ... more to come | | |

Also do we care about test dependencies like Moq and XUnit.* packages? And I have only checked the third-party dependencies for AspNetCore, I suppose we should look at the other repos too.

**Comment by khellang** [comment]
> Polly	- Where is this used? I can't find any reference to it in our repos

See https://github.com/aspnet/Extensions/blob/bfea1edf9e2e9a5465f331517149c4f543ac2ba6/src/HttpClientFactory/Polly/src/Microsoft.Extensions.Http.Polly.csproj#L28

**Comment by rynowak** [comment]
We can probably slim down the dependencies of the BlazorExtension to a really minimal set. There's some code in there but it's not used now, and can just be deleted - that would take care of `StreamJsonRpc`.

AngleSharp is just used in tests, so if we update that to latest and everything passes, we should be good.

**Comment by Pilchie** [comment]
Moving to Preview 8.

**Comment by Pilchie** [comment]
@JunTaoLuo do we have more to do here?  Can the work be farmed out if so?

**Comment by JunTaoLuo** [comment]
Yea, we should check our dependencies before releasing. We can farm this out to the product owners if needed.

**Comment by JunTaoLuo** [comment]
We've reviewed all the critical updates. Will create a list of dependencies that have new versions that we should investigate whether we need to update.

**Comment by JunTaoLuo** [comment]
I'm writing a tool to help us in the future. It flags the dependency and reports the current version as well as the latest stable version on NuGet. It also lists src projects that uses it to help us prioritize/investigate impact. Note that test, sample, and other non src projects are excluded so some test only dependencies will not show any impacted projects. 

Currently scanning AspNetCore gives:
```
Microsoft.CodeAnalysis.Common 3.0.0 => 3.2.1
Microsoft.CodeAnalysis.CSharp.Workspaces 3.0.0 => 3.2.1
 - /src/Analyzers/Analyzers/src/Microsoft.AspNetCore.Analyzers.csproj
 - /src/Mvc/Mvc.Api.Analyzers/src/Microsoft.AspNetCore.Mvc.Api.Analyzers.csproj
 - /src/Mvc/Mvc.Analyzers/src/Microsoft.AspNetCore.Mvc.Analyzers.csproj
 - /src/Components/Analyzers/src/Microsoft.AspNetCore.Components.Analyzers.csproj
Microsoft.CodeAnalysis.CSharp 3.0.0 => 3.2.1
 - /src/Analyzers/Analyzers/src/Microsoft.AspNetCore.Analyzers.csproj
 - /src/Mvc/Mvc.Api.Analyzers/src/Microsoft.AspNetCore.Mvc.Api.Analyzers.csproj
 - /src/Mvc/Mvc.Analyzers/src/Microsoft.AspNetCore.Mvc.Analyzers.csproj
 - /src/Components/Analyzers/src/Microsoft.AspNetCore.Components.Analyzers.csproj
System.CodeDom 4.4.0 => 4.5.0
 - /src/Components/Blazor/Build/src/Microsoft.AspNetCore.Blazor.Build.csproj
System.Net.Http 4.3.2 => 4.3.4
Microsoft.AspNet.WebApi.Client 5.2.6 => 5.2.7
Microsoft.IdentityModel.Clients.ActiveDirectory 3.19.8 => 5.2.1
 - /src/DataProtection/AzureKeyVault/src/Microsoft.AspNetCore.DataProtection.AzureKeyVault.csproj
Microsoft.Owin.Security.Cookies 3.0.1 => 4.0.1
Microsoft.Owin.Testing 3.0.1 => 4.0.1
Microsoft.Web.Xdt 1.4.0 => 3.0.0
 - /src/SiteExtensions/Runtime/Microsoft.AspNetCore.Runtime.SiteExtension.pkgproj
 - /src/SiteExtensions/Microsoft.Web.Xdt.Extensions/src/Microsoft.Web.Xdt.Extensions.csproj
 - /src/SiteExtensions/LoggingAggregate/src/Microsoft.AspNetCore.AzureAppServices.SiteExtension/Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj
System.Threading.Tasks.Extensions 4.5.2 => 4.5.3
Microsoft.Build 15.8.166 => 16.0.461
 - /src/Tools/Microsoft.dotnet-openapi/src/Microsoft.dotnet-openapi.csproj
 - /src/Tools/Extensions.ApiDescription.Client/src/Microsoft.Extensions.ApiDescription.Client.csproj
Microsoft.Build.Framework 15.8.166 => 16.0.461
Microsoft.Build.Utilities.Core 15.8.166 => 16.0.461
 - /src/Tools/Extensions.ApiDescription.Client/src/Microsoft.Extensions.ApiDescription.Client.csproj
AngleSharp 0.9.9 => 0.12.1
BenchmarkDotNet 0.10.13 => 0.11.5
FSharp.Core 4.2.1 => 4.7.0
Google.ProtoBuf 3.8.0 => 3.9.1
Microsoft.Azure.KeyVault 2.3.2 => 3.0.4
 - /src/DataProtection/AzureKeyVault/src/Microsoft.AspNetCore.DataProtection.AzureKeyVault.csproj
Microsoft.Azure.Storage.Blob 10.0.1 => 11.0.0
 - /src/DataProtection/AzureStorage/src/Microsoft.AspNetCore.DataProtection.AzureStorage.csproj
Mono.Cecil 0.10.1 => 0.11.0
 - /src/Components/Blazor/Server/src/Microsoft.AspNetCore.Blazor.Server.csproj
 - /src/Components/Blazor/Build/src/Microsoft.AspNetCore.Blazor.Build.csproj
Moq 4.10.0 => 4.13.0
 - /src/Mvc/shared/Mvc.Core.TestCommon/Microsoft.AspNetCore.Mvc.Core.TestCommon.csproj
 - /src/SignalR/clients/csharp/Http.Connections.Client/src/Microsoft.AspNetCore.Http.Connections.Client.csproj
Selenium.Support 3.12.1 => 3.141.0
Selenium.WebDriver 3.12.1 => 3.141.0
Selenium.WebDriver.ChromeDriver 2.43.0 => 76.0.3809.12600
Serilog.Extensions.Logging 1.4.0 => 3.0.1
 - /src/Hosting/Server.IntegrationTesting/src/Microsoft.AspNetCore.Server.IntegrationTesting.csproj
StackExchange.Redis 2.0.593 => 2.0.601
 - /src/DataProtection/StackExchangeRedis/src/Microsoft.AspNetCore.DataProtection.StackExchangeRedis.csproj
 - /src/SignalR/server/StackExchangeRedis/src/Microsoft.AspNetCore.SignalR.StackExchangeRedis.csproj
System.Reactive.Linq 3.1.1 => 4.1.6
```

**Comment by Pilchie** [comment]
@mkArtakMSFT did this for node dependencies. Do we think we have more to do here for 3.1?  @anurse ?   @JunTaoLuo ?

**Comment by anurse** [comment]
> * Microsoft.Azure.*
> * WindowsAzure.Storage

The latest versions of these have breaking changes, so we'll need to handle this as part of #14657 .

**Comment by pranavkm** [comment]
Moving this out to preview3.

**Comment by Pilchie** [comment]
Closing for 3.1
