### ISSUE TITLE
ANCM installer creates incorrect directory name for outofprocess handler

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#4027]
`C:\Program Files\IIS\Asp.Net Core Module\V2\12.2.0.18287`

**Comment by jkotalik** [comment]
I don't see this reproing with the latest windows hosting bundle:
![image](https://user-images.githubusercontent.com/8302101/49302613-6efd0d80-f47c-11e8-8ef9-cf5450e2e281.png)
