### ISSUE TITLE
[Question] Bootstrapping the ASP.NET Core app from multiple assemblies

### ISSUE THREAD

**Issue by Beton** [aspnet/AspNetCore#4033]
I have an app composed from many Class Libraries (Plugins).

My goal is to to add some components to `void Configure(IApplicationBuilder applicationBuilder)` and `void ConfigureServices(IServiceCollection services)` in each of them, at runtime.

I've played with *IHostingStartup* that works pretty well as for runtime discovery and for services regitration but the `void Configure(IApplicationBuilder applicationBuilder)` is never called.

In this case my goal is to register MVC in separate Assembly.
Any help would be appriciated.

    [assembly: HostingStartup(typeof(FrameworkStartup))]

    public class FrameworkStartup : IHostingStartup
    {
        public void Configure(IWebHostBuilder webHostBuilder)
        {
            webHostBuilder.Configure(applicationBuilder =>
            {
                applicationBuilder.UseMvc(routeBuilder =>
                {
                    routeBuilder.MapRoute(
                        name: "default",
                        template: "{controller}/{action}",
                        defaults: new {controller = "Home", action = "Index"});
                });
            });

            webHostBuilder.ConfigureServices(serviceCollection =>
            {
                serviceCollection
                    .AddMvcCore()
                    .AddRazorViewEngine();
            });
        }
    }
}

**Comment by davidfowl** [comment]
Configure does not compose so you can't use it this way. You want to use IStartupFilters instead.  See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.1#extend-startup-with-startup-filters

**Comment by davidfowl** [comment]
Also the ordering of middleware is important so remember to take that into account when designing your system.

**Comment by Beton** [comment]
Thanks for the reply @davidfowl .
It worked but I've realized that I need simpler scenario to expand only the routing table not the whole Middleware.
So right now the Hosting app runs external assembly to "UseMvc" with IStartupFilter and adds default routing, then more IStartupFilter implementations fire up to add more routing (also from external assemblies - Plugins). 
Obvioulsy calling UseMvc in each of them resets the global Routing table - any idea how to just append more routing?

Thanks

**Comment by davidfowl** [comment]
cc @rynowak any suggestions?

**Comment by anurse** [comment]
Closing this as the issue has gone stale. It does seem like the new [endpoint routing features](https://devblogs.microsoft.com/aspnet/aspnet-core-3-preview-2/) may make this easier since routing is now a first class component that MVC plugs in to, so you can call a sequence of `Action<IRouteBuilder>` delegates that come from plugins within `UseRouting` (`UseEndpoints` in the upcoming preview 4) to allow plugins to add routes without MVC getting in the way.
