### ISSUE TITLE
Razor Components startup experience

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#4054]

**Comment by SteveSandersonMS** [comment]
I'm not sure there's anything to change about this in the preview 2 timeframe. So I question whether the `PRI:0` label is correct. Reasoning:

 * For preview 2, Razor Components apps will still be required to be two projects. @rynowak's work on the Razor compiler will eventually make it possible to do it all in one project, but not for preview 2 (correct, Ryan?).
 * If we're having two projects, we might as well retain the benefit of being able to easily switch to client-side execution. Supporting this necessitates keeping the same `Program.cs` and `Startup.cs` in the app project.
 * If we're keeping `Program.cs` and `Startup.cs` in the app project, what is there to change?

So, I suspect there *is* work in this area eventually to enable a one-project system, but only after preview 2. So @danroth27, should we remove the pri-0 label, or is there any other specific work you think we should do on this for preview 2?

**Comment by rynowak** [comment]
Moves this to working, because I think https://github.com/aspnet/AspNetCore/pull/7770 has enough cleanup to call this "done". If we have other things we want to do after preview3 we can track them with separate issues.

**Comment by rynowak** [comment]
I just want to say that the end result of this is D O P E
