### ISSUE TITLE
Tooling for Razor Component files (.razor)

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#4057]
Coordinate with partner teams (Web tools, Roslyn, etc.)

**Comment by danroth27** [comment]
Roslyn tracking issue: https://github.com/dotnet/roslyn/issues/32570

**Comment by danroth27** [comment]
VS Code Razor support: https://github.com/aspnet/Razor.VSCode/issues/278

**Comment by rynowak** [comment]
All of our partner work is done. The only remaining work is to convert our templates to use `.razor`

**Comment by danroth27** [comment]
We also need to update the wildcard in the .Build package that currently specifies *.cshtml

**Comment by mkArtakMSFT** [comment]
Closing this as there is no more action from our end on this.
