### ISSUE TITLE
Add test coverage to ensure interop with Microsoft.Owin.Security and aspnetcore 3.0+ works

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4074]
In https://github.com/aspnet/Security/pull/1916, we had to entirely disable Owin cookie interop tests as a result of changing target framework support. We should re-write these tests in a way that lets us test the supported scenarios without requiring a hack to run aspnetcore assemblies on .NET Framework.

The scenarios we need to ensure continue to work are:

* Cookies and keys created by ASP.NET Core 3.0+ interop with Owin/Katana using Microsoft.Owin.Security.Interop 2.1.
* Vice versa
* Any changes to cookie formats and key formats made in 3.0+ stay backwards compatible with DataProtection 2.1

**Comment by Eilon** [comment]
Closing because we don't have plans to continue supporting this scenario.
