### ISSUE TITLE
HTTP Error 502.5 because of specific folder name

### ISSUE THREAD

**Issue by m-demydiuk** [aspnet/AspNetCore#4076]
### Describe the bug

I started to get HTTP Error 502.5 at 15th of November when my windows system was rebooted. Windows updates were installed at 13th of November, but the system was rebooted at 15th of November.

All my AspNetCore projects hosted under IIS started to return 502.5 error. I started to search how to fix it and found a lot of possible solutions. But no one works in my case. 
In visual studio I got this error:
![image](https://user-images.githubusercontent.com/2910327/48659919-6d395000-ea61-11e8-8cbc-52b6576ba0b7.png)

`Unable to start process C:\Program Files\dotnet\dotnet.exe. The web server request failed with status code 502, Bad Gateway. The full response has been written to C:\Users\Maksym Demydiuk\AppData\Local\Temp\HttpFailure_12-07-22.html.`

In the file I got:
![image](https://user-images.githubusercontent.com/2910327/48659924-84783d80-ea61-11e8-81de-f3e6d573ee8e.png)

In the event viewer I got:
![image](https://user-images.githubusercontent.com/2910327/48659935-c903d900-ea61-11e8-89fd-b443bc6acdbd.png)

`Application 'MACHINE/WEBROOT/APPHOST/<host>' with physical root '<pth to the project>' failed to start process with commandline '<path to the project>\bin\IISSupport\VSIISExeLauncher.exe -argFile IISExeLauncherArgs.txt', ErrorCode = '0x800700c1' : 0.`

stdoutLog returns nothing and Process Monitor returns also nothing

I tried dozen of provided solutions but nothing. In 3 days I found a solution that worked for me.

My project is located at folder `D:\\folder\folder\<folder_name_that_fails>\folder\project_folder`

When I checkout project to the `D:\\folder` or `D:\\folder\folder` it works. But if I checkout project to the  `D:\\folder\folder\<folder_name_that_fails>` or any child folder it fails with 502.5.

I revert windows updates. After that a lot of programs refused to work. I tried to restore to the point before updates - did not helped. So I decided to reinstall windows. But the problem did not gone.

The solution in my case was just rename `<folder_name_that_fails>` to `<foldername_that_fails>` and it works.

Any ideas what has happend and how to properly fix it? I can provide any additional information.

Thanks in advance.

**Comment by m-demydiuk** [comment]
While describing bug above I realized that there should be something related to this exact `D:\\folder\folder\<folder_name_that_fails>` and....

The real folder name that does not work is `D:\Work\0077. <project_name>`
I turned on hidden files and saw a strange file in the `D:\Work` folder. The file name is `0077` - numbers in the folder name above.
![image](https://user-images.githubusercontent.com/2910327/48660144-74625d00-ea65-11e8-8d30-a97cf3fc2328.png)

The content of the file is 
`"App Offline" /a  <path to one of the projects>\app_offline.htm`

After I deleted this file, everything started to work as before.

Any ideas what this can be?

**Comment by m-henderson** [comment]
is this confirmed?

**Comment by m-demydiuk** [comment]
Not relevant to asp net core or IIS.

**Comment by kmjungersen** [comment]
For others who may end up here, closing all active VS sessions and reopening solved this issue for me.  Not sure why it started happening all of a sudden though, and haven't experienced it since.
