### ISSUE TITLE
Question : No Authentication in development possible?

### ISSUE THREAD

**Issue by xaraskas** [aspnet/AspNetCore#4080]
Hi,
I want to use ASP.NET Core Web API for a new Project. One of the requirement is to use a JWT Bearer token authentication. But I don't want in the development of the API the use the authentication. Do you have any idea how I can perform that.

I'm using ASP.NET Core 2.1

Thanks.

**Comment by Tratcher** [comment]
@javiercn you did some work here, right?

**Comment by javiercn** [comment]
Not for this. The best way to achieve this I think is with an auth policy that it’s pivoted based on the environment.

**Comment by Chibitko** [comment]
As I understandt, @xaraskas wants to use JWT token instead of API KEY.
Look at this - http://docs.identityserver.io/en/release/quickstarts/1_client_credentials.html .
This is the equivalent of a system user with login / password that only certain clients know.

**Comment by Eilon** [comment]
Closing because there are no plans to add any direct support for this. There are a few suggestions in this thread that you could use to implement logic like this. Just make sure it doesn't run in production!
