### ISSUE TITLE
Kestrel default certificate store is invalid

### ISSUE THREAD

**Issue by miloush** [aspnet/AspNetCore#4081]
### Describe the bug
The JSON examples in [Kestrel web server implementation in ASP.NET Core]https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1#listenoptionsusehttps section *ListenOptions.UseHttps* suggest the following:

```JSON
"Store": "<cert store; defaults to My>",
```

However, that is not the case. If "Store" is left out from the app settings, `Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: 'The parameter is incorrect'` exception is thrown. Stack suggests that the store's default is not "My":

`Microsoft.AspNetCore.Server.Kestrel.Core.dll!Microsoft.AspNetCore.Server.Kestrel.Https.Internal.CertificateLoader.LoadFromStoreCert(string subject = "...", string storeName = null, System.Security.Cryptography.X509Certificates.StoreLocation storeLocation = CurrentUser, bool allowInvalid = true)`

### Expected behavior

Fix the configuration loader to supply "My" as default for "Store" or eventually fix the documentation so that it says something like
```JSON
"Store": "<cert store; required>",
```

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18272
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  1.0.0-preview3-003788 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009404 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
Can you give the full exception callstack please.

It looks like it would get to [here](https://github.com/aspnet/AspNetCore/blob/137a72f85d294df114f656160c3f8d7bcd18fc17/src/Servers/Kestrel/Core/src/Internal/CertificateLoader.cs#L17-L19) with a null store name and then it's up to X509Store to see what it does with the value.

**Comment by anurse** [comment]
`X509Store` will throw with a `null` store name so it sounds the docs are in conflict with the behavior. Fixing the behavior seems reasonable enough to me.

**Comment by anurse** [comment]
Providing a default value of "My" seems to be the best option here.
