### ISSUE TITLE
Deleting a folder with code is not triggering any change

### ISSUE THREAD

**Issue by kichalla** [aspnet/AspNetCore#4093]
Repro:
- Create a folder with .cs files outside an app
- start dotnet watch on the app
- drop the folder that was created earlier and you should see its content getting picked up
- delete this dropped folder and you should see the content not picked up.

```
C:\temp\DotnetWatchTestApp\src\ConsoleApp [master]> dotnet --info
.NET Command Line Tools (1.0.0-rc2-002659)

Product Information:
 Version:     1.0.0-rc2-002659
 Commit Sha:  11a001706f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by muratg** [comment]
I don't expect we'll make changes here.
