### ISSUE TITLE
Using 'dotnet user-secrets set' reformats JSON and removes comments

### ISSUE THREAD

**Issue by adamtuliper** [aspnet/AspNetCore#4105]
First let me state begrudgingly I understand technically JSON doesn't support comments :D

However - Visual Studio supports it just fine. If you edit your user secrets JSON in VS and create comments, it works ok. They load OK as well in the config system when you run your app. Once you go to the CLI and run the following
`
dotnet user-secrets set KeyName KeyValue
`
your secrets are reformatted and all commented items are lost. I wonder if VS should be consistent and not work with comments in JSON (hence force the user to use some convention like _comment) or the tool shouldn't remove what's in the file. As it stands now they operate a bit differently (and thus just lost a bunch of commented test values). Thoughts?

**Comment by muratg** [comment]
I don't expect that we'll make changes here. JSON should be considered an implementation detail and shouldn't be relied on.

**Comment by adamtuliper** [comment]
Makes sense, thanks @muratg and @natemcmaster
