### ISSUE TITLE
Consider setting background color when writing output

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#4107]
If you set the foreground color it would be a good idea to also set the background color to prevent users console color settings from making the output invisible.
![temp](https://user-images.githubusercontent.com/7574801/27236158-9f05e5ee-5278-11e7-8e52-d743747adc29.PNG)
![temp](https://user-images.githubusercontent.com/7574801/27236245-0a8bb028-5279-11e7-9c74-6547e489846c.PNG)

For example in the console logger we do https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs#L224-L237

**Comment by muratg** [comment]
We haven't heard much feedback from customers so far. Closing.
