### ISSUE TITLE
InvalidOperationException: No authenticationScheme was specified, and there was no DefaultForbidScheme found

### ISSUE THREAD

**Issue by GuitarHero1969** [aspnet/AspNetCore#4123]
Could someone _please_ clear this up for me.

I have a web api built using .net core 2.1

I have a custom database table called tblUser (which doesn't take part in any authorisation like AspNetUsers).

This table contains three boolean fields I wish to utilize in my authorization, these are the same as my policy names.

In my Startup.cs ConfigureServices method:

`services.AddAuthorization(options =>
            {
                options.AddPolicy("CanCreateCallLog", policy => policy.RequireRole("ocm"));
                options.AddPolicy("CanUpdateCallLog", policy => policy.RequireRole("ocm"));
                options.AddPolicy("CanViewCallLog", policy => policy.RequireRole("ocm", "assurance"));
            });`
I have  a controller with a method thus:

`[Authorize(Policy = "CanViewCallLog")] 
        [HttpGet]
        public ActionResult<List<TblCall>> Get()
        {        
            return _repo.findAll();
        }`

With the Authorize attribute present I get an error: "InvalidOperationException: No authenticationScheme was specified, and there was no DefaultForbidScheme found"

Without the attribute everything works properly.

What piece of the puzzle am I missing ?
Do I need to implement a handler:
public class CustomAuthorize : AuthorizationFilterAttribute, IAuthorizationFilter
{

    public override void OnAuthorization(HttpActionContext actionContext)
    {
.....

If so, where is the best place to add this class to my project, e.g Helpers folder ?

Also, in my launchSettings.json file:

"iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false,
    .....
    }
  },

is that correct ?

I just read somewhere that when using Windows authentication, you don't need to use Active Directory like this which I am doing:

`[Authorize]
        [HttpPost]
        public ActionResult Authenticate([FromBody] LoggedInUser loggedInUser)
        {
            if (!IsLDAPAuthenticated("LDAP://bcl.local", loggedInUser.username, loggedInUser.password))
            {
                return StatusCode(403); // assume user not registered in Engage           
            }
...`

Do I need the LDAP stuff (which works fine) ?

**Comment by blowdart** [comment]
If you're taking a username and password and then checking against AD you're not doing integrated auth. If this is an exposed to the internet application you now have a DoS vector if account lockout is enabled. Please don't do this.

**Comment by dotNetAthlete** [comment]
What is a dos vector?
This is an intranet application (not internet)

**Comment by rbonomo** [comment]
Wow

"I started fiddling around with the project templates and noticed that I could reproduce this easily using the standard template ASP.NET Core Web Application (Model-View-Controller) with Windows Authentication."

https://stackoverflow.com/questions/45818095/asp-net-core-2-0-httpsys-windows-authentication-fails-with-authorize-attribute
