### ISSUE TITLE
Demonstrate how to renew access tokens w/ refresh tokens

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#4124]
See https://github.com/aspnet/Security/issues/1668 for some of the challenges that exist today.

**Comment by muratg** [comment]
There's some code here: https://github.com/aspnet/AspNetCore/blob/5a4a001d1878adceda1df9e0e754869e8a97e636/src/Security/Authentication/samples/SocialSample/Startup.cs#L276 

We're not planning to do more here at this point.
