### ISSUE TITLE
Add a sample that shows Azure AD multi-tenant-ish support

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#4125]
Original issue: https://github.com/aspnet/Security/issues/102

E.g. using virtual schemes and adding tenants dynamically.

@blowdart can you fill in the details?

**Comment by Tratcher** [comment]
@jmprieur has a few samples that may help

**Comment by muratg** [comment]
@jmprieur Closing this. If you're interested in adding samples, please go ahead!

**Comment by brockallen** [comment]
Azure already has samples for this, IIRC, in their repo

**Comment by jmprieur** [comment]
@blowdart 
did you have a look at [aspnetcore-webapp-openidconnect-v2](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2)

cc: @muratg
