### ISSUE TITLE
Add more functional tests to auth samples

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#4127]
- [ ] ClaimsTransformation 
- [x] Cookies
- [x] CustomPolicyProvider
- [x] DynamicSchemes
- [ ] Identity.External
- [x] PathSchemes
- [ ] StaticFileAuthZ
- [ ] https://github.com/blowdart/AspNetAuthorizationWorkshop (need to create sample as well)

**Comment by Eilon** [comment]
No plans at this time to add more.
