### ISSUE TITLE
Handle the X-ARR-ClientCert header on Azure

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#4129]
Based on the discussion in https://github.com/aspnet/mvc/issues/7366 it looks like Azure App Service will pass client certificates using the `X-ARR-ClientCert` header. We should investigate if we should add special handling for this header to surface the client certificate appropriately.

See also https://blogs.msdn.microsoft.com/kaevans/2016/04/13/azure-web-app-client-certificate-authentication-with-asp-net-core-2/

@blowdart @shirhatti

**Comment by anurse** [comment]
We'll do this as part of https://github.com/aspnet/AspNetCore/issues/4663

**Comment by Eilon** [comment]
Re-opening because this is important for https://github.com/aspnet/AspNetCore/issues/4663

**Comment by HaoK** [comment]
https://github.com/aspnet/AspNetCore/pull/9756 adds the CertificateForwarding middleware for this
