### ISSUE TITLE
ControllerBase.User null when injecting controller

### ISSUE THREAD

**Issue by bdebaere** [aspnet/AspNetCore#4140]
### Describe the bug
When injecting one controller into another the User property is suddenly always null in the injected controller.

### To Reproduce
1. Using this version of ASP.NET Core 2.1.2
2. Run the code below
3. Notice User is not null originally but is null when entering the injected controller

```csharp
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    //options.Audience = ;
                    //options.Authority = ;
                });

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services.AddScoped(typeof(IUsersController), typeof(UsersController));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseAuthentication();
            app.UseMvc();
        }
    }

    [Authorize]
    public class MeController : ControllerBase
    {
        private readonly IUsersController _usersController;

        public MeController(IUsersController usersController)
        {
            _usersController = usersController;
        }

        [HttpGet]
        [Route("Me/DoSomething")]
        public ActionResult DoSomething()
        {
            return _usersController.DoSomething(5); // 5 as an example.
        }
    }

    [Authorize]
    public class UsersController : ControllerBase, IUsersController
    {
        [HttpGet]
        [Route("Users/DoSomething/{mode}")]
        public ActionResult DoSomething(int mode)
        {
            var user = User; // User == null when accessed through MeController, but not when accessed directly.

            return Ok(true);
        }
    }

    public interface IUsersController
    {
        ActionResult DoSomething(int mode);
    }
```

### Expected behavior
The User property to be filled in, like usual.

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by pranavkm** [comment]
> When injecting one controller into another

Initializing a controller is a bit more involved than getting it from DI. Like you noticed, request specific properties will not be initialized when you do this. Honestly, I wouldn't recommend going down a path where you're injecting controllers in to other controllers. Refactoring your code in to callable services that you could invoke from either controller would be the recommended pattern.

**Comment by bdebaere** [comment]
@pranavkm I understand that this is not a conventional path to go down. The only difference between the functions on the UsersController and the functions on the MeController is that the functions on the UsersController expect a UserId to be given to them while the MeController basically runs them in the context of the current user with the current UserId. How can I name such a service in this instance?

**Comment by pranavkm** [comment]
I'd imagine the service with a method that accepts a User instance and does the work would be the way to go. Either controller should be able to invoke the service without running in to the issue you're seeing here.

>  How can I name such a service in this instance?

Naming is really an application concern and you're the best judge here. Think about the responsibilities of the service you plan to create and name it accordingly.
