### ISSUE TITLE
Using KestrelServerOptions with launchSettings.json

### ISSUE THREAD

**Issue by dotnetchris** [aspnet/AspNetCore#4145]
reopens https://github.com/aspnet/Hosting/issues/1441

I'm getting

```
[##:34:57 WRN] Overriding address(es) 'https://localhost:5001/, http://localhost:5000/'. 
Binding to endpoints defined in UseKestrel() instead.
```

And my config looks like

launchSettings.json
```json
{
  "profiles": {
    "Local": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "https://localhost:44399/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
}
```

appSettings.json
```
{
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://*:80"
      },
      "Https": {
        "Url": "https://*:443",
        "Protocols": "Http1AndHttp2",
        "Certificate": {
          "Path": "muhcert_pk.pfx",
          "Password": "muhcertpassword"
        }
      }
    }
  }
```

appSettings.Development.json
```json
{
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://*:8099"
      },
      "Https": {
        "Url": "https://*:44399"
      }
    }
  }
}
```

There's no usage of 5000 or 5001 in my entire solution (using N++ find in directory)

Also it seems that launch browser is not working / working consistently

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
