### ISSUE TITLE
Undo the change to make the IServiceProvider in Configure scoped

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#4148]
Turns out people were capturing the IServiceProvider here to store in statics. Initially this change was made to make running EF migrations easier but then that pattern was moved into Program.Main. We've had several reports about this breaking things so we should consider reverting it.

Here's the initial change:
https://github.com/aspnet/Hosting/pull/1106

We can consider this for a later patch as well.

**Comment by muratg** [comment]
@davidfowl Do you expect to get this in in a week or so?

**Comment by davidfowl** [comment]
This issue has become irrelevant in 3.0 with the move to generic host. I'm closing this issue because we won't be back porting it. Most of the other issues here don't have much to do with this particular change.
