### ISSUE TITLE
Generic Host Builder and HostingEnvironment.IsDevelopment

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#4150]
_From @dazinator on July 5, 2018 17:7_

I am using the new generic host in 2.1.0 as documented here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1

When the hosting environment is development, I'd like to add user secrets:

```
  .ConfigureAppConfiguration((hostContext, configApp) =>
                   {
                       configApp.AddJsonFile("appsettings.json", optional: true);                   
                       if (hostContext.HostingEnvironment.IsDevelopment())
                       {
                           configApp.AddUserSecrets<Program>();
                       }
                       configApp.AddEnvironmentVariables(prefix: "FOO_");
                       configApp.AddCommandLine(args);
                   })
```

However `IsDevelopment` always returns false.
Yet I have set the `ASPNETCORE_ENVIRONMENT` enironment variable. Here is my launch settings:

```
{
  "profiles": {
    "Foo": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

It would make sense if `ASPNETCORE_ENVIRONMENT` was no longer used to control this for a generic host as we are not in asp.net core land - but in that case is there now a different environment variable name for this, or do we set the Environment name ourselves in code?

_Copied from original issue: aspnet/Home#3298_

**Comment by pksorensen** [comment]
From a user that dont already read the docs i did use some time here to find out that the enviromentname is defaulted to production ( also causing some pain to find out it altered production environment).

I think it would have been a good idea to add environment variables as default to hostconfiguration :)
and use a fallback on aspnetcore_environment.

I just added to my solution
```
              .ConfigureHostConfiguration((configurationBuilder)=>{
                  configurationBuilder
                    .AddInMemoryCollection(new[] { new KeyValuePair<string, string>(HostDefaults.EnvironmentKey, System.Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")) })
                    .AddEnvironmentVariables();
              })
```

**Comment by muratg** [comment]
@davidfowl @Tratcher Are we doing something here for 3.0?

**Comment by Tratcher** [comment]
Yes this needs design.

**Comment by Tratcher** [comment]
There's a PR updating the docs around this:
https://github.com/aspnet/Docs/pull/10531

In 3.0 we've added Host.CreateDefaultBuilder that adds unprefixed environment variable support, so generic host apps are expected to use ENVIRONMENT=Development.

The 3.0 web host integration for generic host adds ASPNETCORE_ prefixed environment variables so web apps can use either the generic ENVIRONMENT or the web specific ASPNETCORE_ENVIRONMENT.

The only remaining question here is if Host.CreateDefaultBuilder should use a prefix when adding environment variables? @glennc?

**Comment by Tratcher** [comment]
Proposal: "DOTNET_"

**Comment by davidfowl** [comment]
I think we should support both `DOTNET_` and `ASPNETCORE_`

**Comment by muratg** [comment]
@davidfowl Which one overrides the other, in case both are specified?

**Comment by davidfowl** [comment]
In that odd case DOTNET wins.

**Comment by Tratcher** [comment]
Adding the web hosted service already adds `ASPNETCORE_` and overwrites the prior one.

**Comment by Tratcher** [comment]
Yes

**Comment by davidfowl** [comment]
Lets write a test for that case to make sure it's covered. The original plan sounds fine in that case. It does mean in the new worker template the DOTNET_ENVIRONMENT flag should be set instead of ASP.NET Core environment. We should also determine if we want to chose the new web templates to use the DOTNET_ENVIRONMENT  in launch settings.

cc @glennc

**Comment by svrooij** [comment]
In a generic host in dotnet core 2.2 you can just use 
```csharp
new HostBuilder()
.UseEnvironment(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production")
```
to set the environment the same way as you would with the aspnet core app.

**Comment by jdang67** [comment]
im my enviroment Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")  always return null and hostContext.HostingEnvironment.IsDevelopment() always return false.

**Comment by dazinator** [comment]
@jdang67 some options:

1. Are those environment variables on your environment?
    A) if yes, is the config provider for environment variables added to your app?
2. Do you run debug builds on your dev environments? If you do #if Debug might suffice.
