### ISSUE TITLE
Is there any alternative to configSource in applicationHost.config?

### ISSUE THREAD

**Issue by nedimsahin** [aspnet/AspNetCore#4151]
An ASP.NET site is load balanced using ARR (Application Request Routing) in IIS. The corresponding URL rewriting rule is placed in **applicationHost.config**. 

Is there any way to separate this rule in a new config file? The tag `configSource `is no longer supported. I read about `childSource `tag but it is only supported in <sites> section.

Here is the rule in **applicationHost.config**:
```
<system.webServer>
        <rewrite>
            <globalRules>
                <rule name="ARR_TestFarm_loadbalance" patternSyntax="Wildcard" stopProcessing="true">
                    <match url="*" />
                    <action type="Rewrite" url="http://TestFarm/{R:0}" />
                </rule>
            </globalRules>
        </rewrite>
</system.webServer>
```

**Comment by skacurt** [comment]
It seems more like an IIS question than ASP.NET (Core). Maybe @ruslany can help.

**Comment by shirhatti** [comment]
@nedimsahin It isn't possible to do what you're asking. The `childSource` element is only supported for sites. Global rules must be authored in the applicationHost.config
