### ISSUE TITLE
IHostingEnvironment/appsettings configuration file dichotomy

### ISSUE THREAD

**Issue by smarts** [aspnet/AspNetCore#4155]
`IHostingEnvironment` has an extension method `IsEnvironment(string environment)` and other similar [methods like `IsProduction()` that are case-insensitive](https://github.com/aspnet/Hosting/blob/master/src/Microsoft.AspNetCore.Hosting.Abstractions/HostingEnvironmentExtensions.cs#L77).

The default/automatic configuration-loading looks for [`$"appsettings.{env.EnvironmentName}.json"`](https://github.com/aspnet/MetaPackages/blob/master/src/Microsoft.AspNetCore/WebHost.cs#L170)

This creates a strange dichotomy in which the resolution of the environment is case-insensitive while the resolution of that environment's configuration is not.

In the increasingly cross-platform world of .NET Core development (e.g., developing on Windows OS and then using an Alpine Linux container) that dichotomy becomes painful.

My anecdote for witnessing this was trying to troubleshoot a production problem by running code locally. We use lowercase environment names, but I was aware of ASP.NET Core's default environment of "Production" (and its case-insensitivity while determining env.), so I left out the specification of the environment. I was getting wildly different results even though any environment-dependent code paths were correct - because the configuration was wrong while the code path was not.

I'd like the team to consider doing something like this:
```c#
config
  .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
  .AddJsonFile($"appsettings.{env.EnvironmentName.ToUpperInvariant()}.json", optional: true, reloadOnChange: true)
  .AddJsonFile($"appsettings.{env.EnvironmentName.ToLowerInvariant()}.json", optional: true, reloadOnChange: true)
  .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
```

It doesn't completely get rid of the dichotomy, but at least it solves for [debatably] the 2 most common letter-case variants.

**Comment by muratg** [comment]
Interesting, but not sure if there's any really good heuristic. Upper, lower and exact cases for example -- what happens if you have files with both cases, and they conflict? Wouldn't that be more confusing?  (With the example above, one of them will "win".) 

@davidfowl any thoughts here?

**Comment by anurse** [comment]
It's unfortunate but I don't think adding more casing options is a viable solution here. Yes, environment name matching is case-insensitive for `IsProduction` but when using it on a case-sensitive file system, it's case-sensitive.
