### ISSUE TITLE
Turn off reloadonchanges for appsettings.json to avoid iNotify Issue

### ISSUE THREAD

**Issue by sorvis** [aspnet/AspNetCore#4156]
We are running our application on a Linux host inside of containers we are seeing iNotify errors as explained in [this article](http://enterpriseyness.com/2018/02/07/dotnetcore-2-0-linux-suffering-inotify-errors/).

We would like to turn off reloadonchanges for appsettings.json which happens within WebHost.cs
``` 
config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
```
We could create our own custom version of WebHost so that we can set those values to false like they did in the blog post I linked to, but that will not be good solution as we update the framework plus the bother of making sure I start with the right version of WebHost. Any suggestions or enhancements that could be made to the framework to enable it to be switched off? Thank you

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
