### ISSUE TITLE
Add a check to the targets file to ensure the ASP.NET Package Graph is consistent

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#4157]
We want to ensure that users aren't "hoisted" out of the supported package graph accidentally. For example, consider the following package graph:

* `App`
  * `Microsoft.AspNetCore.All 2.0.0`
    * `Microsoft.AspNetCore.Mvc 2.0.0`
      * `Microsoft.AspNetCore.Hosting.Abstractions 2.0.0`
  * `SomeCoolLibrary`
    * `Microsoft.AspNetCore.Hosting.Abstractions 2.1.0`

In this scenario, `Microsoft.AspNetCore.Hosting.Abstractions 2.1.0` will be selected, but `Microsoft.AspNetCore.Mvc` will remain at `2.0.0`, thus putting the user into an unsupported configuration.

To fix this, we should add targets to our MSBuild files in `Microsoft.AspNetCore.All` to traverse the final resolved list of package references and make sure they are consistent. The algorithm for this is simple

1. Find `Microsoft.AspNetCore.All` in the final resolved package list (i.e. assets file, or whatever MSBuild representation exists) and identify the version number of that package
2. For each ASP.NET package (known by the metapackage, since it was built from this list, so we can hard-code it), ensure that the version number matches that value.
3. If any package in the ASP.NET set does not match the version number of `Microsoft.AspNetCore.All`, emit a warning (which could be elevated to an Error via `WarningsAsErrors` or suppress using `NoWarn` globally)

Also, we could consider reading the `%(NoWarn)` metadata item on `PackageReference` items, like NuGet is doing for it's downgrade warnings, to allow a user to override this warning for specific packages.

**Comment by Eilon** [comment]
Ancient. Not needed anymore in the new world.
