### ISSUE TITLE
ASPNETCORE_URLS environment variable is ignored by "dotnet run"

### ISSUE THREAD

**Issue by mikeharder** [aspnet/AspNetCore#4159]
# Repro Steps
1. `dotnet new web`
2. `set ASPNETCORE_URLS=http://127.0.0.1:0`
3. `dotnet run` (note ASPNETCORE_URLS is ignored)
```
> dotnet run
Using launch settings from D:\Temp\foo2\Properties\launchSettings.json...
Hosting environment: Development
Content root path: D:\Temp\foo2
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```
4. `dotnet run --no-launch-profile` (note ASPNETCORE_URLS is used)
```
> dotnet run --no-launch-profile
Hosting environment: Production
Content root path: D:\Temp\foo2
Now listening on: http://127.0.0.1:50897
Application started. Press Ctrl+C to shut down.
```

**Comment by obohovyk** [comment]
Do not use `set`
ASPNETCORE_URLS=http://127.0.0.1:8080 dotnet run

**Comment by annokr** [comment]
For me to run successfully with a specified port (44360) on SSL on Windows 10 from `cmd`:

1.`dotnet dev-certs https --trust` (if not installed)
2.`set ASPNETCORE_URLS=https://localhost:44360`
3.`dotnet run --no-launch-profile`

**Comment by anurse** [comment]
This is controlled in the CLI and VS, so it should be filed against dotnet/cli and the VS feedback tool. We don't control this behavior in ASP.NET Core, it's the CLI/VS launcher that is overriding the variable.
