### ISSUE TITLE
Cannot step into source code of AuthorizeFilter

### ISSUE THREAD

**Issue by alealpha2000** [aspnet/AspNetCore#4164]
Hello. I want to debug the AuthorizeFilter class. I have disabled Just My Code, allowed to step into source code if source code is not exactly the same, added Microsoft Symbol Servers as well as https://nuget.smbsrc.net, downloaded the symbols for ASP.NET Core and added them to the symbols folders, built ASP.NET MVC Core from source and added the artifacts folder to nuget.config and added the source code folder to the solution. I still cannot step into the AuthorizeFilter class to see why authorization fails which causes a bug in the Open Id Connect integration of my website. Other classes above the call stack do have source code, but not AuthorizeFilter. I need to to step into AuthorizeFilter to fix this critical bug. Any help, please? I'm using Visual Studio 2017 15.9.2

EDIT: I noticed the problem. For some reason, the AuthorizeFilter source code file is not included in the Microsoft.AspNetCore.Mvc.Core.2.1.3-rtm-t000.symbols.nupkg. How can I add it?

**Comment by Klipi** [comment]
I have the same issue. Steps to reproduce:
1) Create a new .NET Core MVC project
2) Add the `[Authorize]` attribute to `HomeController`
3) Add `services.AddAuthentication().AddCookie()` in `Startup.cs:ConfigureServices()`
4) Add `app.UseAuthentication()`in `Startup.cs:Configure()`
5) Disable Debug > Options > Just My Code
6) Debug > New Breakpoint > Function Breakpoint > Enter `OnAuthorizationAsync` as the Function Name
7) Run the app in debug mode and hit the endpoint with the `[Authorize]` attribute
8) The breakpoint gets hit with a message "Source not available. Source information is missing from the debug information for this module." (see picture)

Expected: Step 8 would have a debugger session with AuthorizeFilter.cs code browsable.

**Comment by natemcmaster** [comment]
@dougbu can you take a look at the latest 2.1 release and see if our recent work on source-link has resolved this scenario?

**Comment by dougbu** [comment]
I'm unable to reproduce a problem debugging pretty anything I tried to to see the source. `AuthorizeAttribute` is a little problematic because it has so little executable code. Nonetheless, breakpoints I set on properties and constructors were hit and the code was loaded correctly.

I tested with both `netcoreapp2.1` and `netcoreapp2.2`.
