### ISSUE TITLE
Identity Still uses Bootstrap 3

### ISSUE THREAD

**Issue by bhrugen90** [aspnet/AspNetCore#4166]
### Describe the bug
The default rendering of Razor Identity class library should be upgraded to bootstrap 4?

**Comment by blowdart** [comment]
Why? What would it give you beyond being "the latest"?

**Comment by danroth27** [comment]
The default identity UI has support for bootstrap 4. You just have to configure it like we do in the templates for you:

```csharp
            services.AddDefaultIdentity<IdentityUser>()
                .AddDefaultUI(UIFramework.Bootstrap4)
                .AddEntityFrameworkStores<ApplicationDbContext>();
```
