### ISSUE TITLE
Considering adding an implicit FrameworkReference in Microsoft.NET.Sdk.Razor

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4176]
We updated Microsoft.NET.Sdk.Web to add an implicit FrameworkReference to Microsoft.AspNetCore.App. in netcoreapp3.0 https://github.com/aspnet/websdk/issues/424.

Does it make sense to also do this for Microsoft.NET.Sdk.Razor? Currently, users must still add an explicit FrameworkReference item.

Users could opt-out with `DisableImplicitFrameworkReferences`. 

cref https://github.com/aspnet/websdk/pull/428

cc @DamianEdwards @pranavkm @rynowak @livarcocc @dsplaisted

**Comment by rynowak** [comment]
I don't think we're totally closed on the story for what an RCL targets yet. Given that we haven't come up with any super duper bright ideas in this area I expect we'd end up doing this.

**Comment by pranavkm** [comment]
Component class libraries may switch to targeting netcoreapp3.0 in the future and we do not want these to reference the AspNetCore shared fx. The RCL templates have an explicit framework reference to the shared fx and this seems perfect for the moment.
