### ISSUE TITLE
Renders <option> tag as OptionTagHelper even when <select> is not TagHelper

### ISSUE THREAD

**Issue by salmanshariati** [aspnet/AspNetCore#4181]
when using <select> in razor views it always highlights <option> tags as OptionTagAHelper and it prevents adding other custom attributes using razor Model such as image below:

**Comment by salmanshariati** [comment]
![option](https://user-images.githubusercontent.com/7315828/48834776-d4257480-ed93-11e8-9ec9-4b860e105683.jpg)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @salmanshariati.
Too many questions come up based on your limited sample shown here.
Can you please share a more comprehensive example. Ideally - a GitHub repo with the sample.

A simple guess is that you're trying to achieve an option to render as:
```cshtml
<option selected />
```

If that's the case, you can rewrite your sample as:
```cshtml
<option selected=@selected />
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
