### ISSUE TITLE
Visual Studio shows NU1105 error even though build and tests pass

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4183]
Currently, opening the solution files in this repo, like src/Servers/Kestrel.sln, shows a bunch of NU1105 errors in the Error List window. The error looks like this:

> Error    NU1105    Unable to find project information for "ProjectXYZ.csproj". Inside Visual Studio, this may be because the project is unloaded or not part of current solution.

We believe this is the result of https://github.com/NuGet/Home/issues/5820. There is a draft of a solution in PR in NuGet, but if that doesn't make it in in a reasonable amount of time, we may need to find workarounds.

FWIW - this does not affect command line builds, and also, it appears you can still build and run tests in Visual Studio despite the error.

cc @jainaashish @rrelyea

**Comment by natemcmaster** [comment]
_Build triage:_ we are going to workaround this by adding projects to our .sln files. Whenever we get NU1105, the solution should be edited to add the missing project.

**Comment by natemcmaster** [comment]
@JamesNK @JunTaoLuo can you take care of doing this for the solutions that your respective teams work on? Some of this is already done in release/2.2. If you find other places this needs to happen, feel free to edit the .sln and make a PR.

**Comment by MarkDixonTech** [comment]
I am getting a series of NU1602 errors when opening in Visual Studio. Is this releated?

**Comment by natemcmaster** [comment]
@MarkDixonTech which solution are you opening?

**Comment by MarkDixonTech** [comment]
@natemcmaster 

src\Mvc\mvc.sln 
I followed the instructions here: 
[https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md](url)

**Comment by natemcmaster** [comment]
I'm not aware of any issues with NU1602 in Mvc.sln. It's likely unrelated. @mkArtakMSFT @NTaylorMullen have you seen this before?

**Comment by MarkDixonTech** [comment]
I put more details here

https://stackoverflow.com/questions/53832737/nuget-error-building-asp-net-core-from-source

**Comment by JamesNK** [comment]
I see this in the release/2.2 branch.

> 19>C:\Development\Source\AspNetCore\src\Mvc\src\Microsoft.AspNetCore.Mvc.Razor\Microsoft.AspNetCore.Mvc.Razor.csproj : error NU1602: Microsoft.AspNetCore.Mvc.ViewFeatures does not provide an inclusive lower bound for dependency Microsoft.Extensions.WebEncoders. An approximate best match of Microsoft.Extensions.WebEncoders 1.0.0 was resolved.

ViewFeatures.csproj references WebEncoders with `<PackageReference Include="Microsoft.Extensions.WebEncoders" Version="$(MicrosoftExtensionsWebEncodersPackageVersion)" />` but `MicrosoftExtensionsWebEncodersPackageVersion` does not exist in dependencies.props.

**Comment by JamesNK** [comment]
MicrosoftAspNetCoreChunkingCookieManagerSourcesPackageVersion is also missing. I'll create a PR to add them to 2.2.

**Comment by JunTaoLuo** [comment]
Oops that's my fault. It was removed in https://github.com/aspnet/AspNetCore/pull/4618. That package was removed in favour of code under Shared/.

**Comment by JamesNK** [comment]
Is re-adding them the correct fix for 2.2? https://github.com/aspnet/AspNetCore/pull/5714

Or should the package be removed in 2.2 and the shared source be referenced instead?

**Comment by JunTaoLuo** [comment]
Second option. Remove the package and reference the shared source.

**Comment by JamesNK** [comment]
@MarkDixonTech I've merged a fix. Can you try getting the latest code from release/2.2 and seeing whether it builds?

**Comment by natemcmaster** [comment]
> Should WebEncoders also reference shared source?

I don't think so. Microsoft.Extensions.WebEncoders is not the same as the code in src/Shared/WebEncoders.

**Comment by Eilon** [comment]
Per @natemcmaster we think this should be taken care of wherever it matters.

Info on how to work around it here: https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#known-issue-nu1105

**Comment by MarkDixonTech** [comment]
There was also a problem running startvs.cmd when space exists in user name. Pull request here

https://github.com/aspnet/AspNetCore/pull/5963
