### ISSUE TITLE
Add Http/2 tests

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#4189]
OS: Win10+
Servers: IIS, IIS Express, WebListener
Client: .NET Core HttpClient (WinHttp)?

This will require SSL/ALPN. IIS Express has pre-registered SSL ports we can depend on. IIS and WebListener do not have pre-registered ports. IIS requries admin to run tests at all, so it could dynamically register certs. WebListener tests do not require admin, so we could write some tests that light up either if the test is run as admin and dynamically registers the port, or if the test detects that the port is already registered.

Secondary problem: How do you verify that HTTP/2 was actually used? That information is not surfaced to the server or client APIs.

https://github.com/aspnet/WebListener/issues/106
https://github.com/aspnet/IISIntegration/issues/160

**Comment by anurse** [comment]
We do test now ;).
