### ISSUE TITLE
Fetch ISession data from client code without refreshing the session

### ISSUE THREAD

**Issue by martelskiy** [aspnet/AspNetCore#4192]
I need to check whether a session is not expired in my client code. But by polling each few minutes HTTP GET and checking session status I'm extending the actual session. Which means unless the user closes the browser tab session will never be expired. Is there any way to specify which GET requests should not extend the session?
 "Microsoft.AspNetCore.App" Version="2.1.4" installed

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
