### ISSUE TITLE
Handle optional extension in conventional route via dispatching

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#4209]
Imagine this conventional route: `"{controller}/{action}.{ext?}"`
When calculating endpoints it is updated to: `"TestController/TestAction.{ext?}"`

The updated template is a problem because the optional extension is following more than just a `.` literal.

**Comment by rynowak** [comment]
@JamesNK - now that we improved how we do this in MVC -> Routing, this is probably fixt right?

**Comment by JamesNK** [comment]
This was already fixed from MVC's perspective here https://github.com/aspnet/Mvc/pull/8249

I believe it is still a bug in code like this: `RoutePatternFactory.Parse("TestController/TestAction.{ext?}");`

**Comment by rynowak** [comment]
yeah bro
