### ISSUE TITLE
Update CORS middleware to use dispatcher

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#4210]
- [x] Update CORS middleware to use endpoint metadata
- [ ] Figure out whether MVC CORS logic should be disabled when the middleware has run. This would be a performance optimization. If they have different behavior then MVC CORS should continue to run. Double check with @rynowak about this
- [ ] If MVC CORS logic should be disabled then do it. Follow the AuthorizeFilter pattern in this PR - https://github.com/aspnet/AspNetCore/pull/6346

**Comment by mkArtakMSFT** [comment]
@JamesNK, is this done? If not, not sure whether you or @javiercn would be a good person to handle this. Please assign as necessary.

**Comment by javiercn** [comment]
I believe this is just the CORS middleware, not the MVC support for CORS

**Comment by JamesNK** [comment]
The CORS middleware update has happened. Updated with tasks for the MVC side.

**Comment by mkArtakMSFT** [comment]
Closing as there is nothing else pending here.
