### ISSUE TITLE
Inbound route parameter transformer

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#4211]
As discussed at EndpointCon 2018

**Comment by rynowak** [comment]
We haven't had anyone ask for this. Moving out to backlog.

**Comment by bojanrajkovic** [comment]
Would love this -- I want to expose [hashids][hashids] to end users rather than raw database IDs, and it would be nice to "abstract" the boilerplate of decoding hashids output to an `IInboundParameterTransformer`.

[hashids]: https://hashids.org/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
