### ISSUE TITLE
Link generation behaviour change: page to controller in area

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#4212]
Linking from a page in an area to a controller in the same area, without specifying the area is changing.

* Succeeded in 2.1
* Succeeded in 2.2 (unintentionally)
* Fails in 3.0 (current behaviour)

We could make 3.0 succeed with a moderate amount of additional work. The question is whether anyone is doing this and if it is important to customers.

This issue is something to evaluate near the end of 3.0 to make a decision.

Affected test: PagesInAreas_CanGenerateLinksToControllersAndPages
```cs
<a asp-controller="Home" asp-action="Index">Link to area action</a>
```

PR that is changing this - https://github.com/aspnet/Routing/pull/914

**Comment by mkArtakMSFT** [comment]
@JamesNK, what else is pending here? We're trying to wrap up preview2 issues within couple of days.

**Comment by mkArtakMSFT** [comment]
If this is not super critical, and work is pending, please move to preview3

**Comment by rynowak** [comment]
This change in behaviour was fixed. There is no breaking change to speak of here.
