### ISSUE TITLE
FindEndpoints_LookedUpByCriteria_MultipleMatches weirdness

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#4217]
https://github.com/aspnet/Routing/commit/25b5ab2c3980569907d7c467dff185d00b9fbd64#diff-d27ab64c4b8a9e9cc5f4487c4b7f2864R227

FindEndpoints_LookedUpByCriteria_MultipleMatches is producing odd results. The same endpoint is returned 3 times. Is this expected?

Also the assert in the test is duplicated.

// @drieseng

**Comment by mkArtakMSFT** [comment]
@JamesNK is this already resolved?

**Comment by JamesNK** [comment]
Was fixed with https://github.com/aspnet/Routing/pull/910
