### ISSUE TITLE
Domains with EP routing

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#4219]
I came across this question while waiting for a flight - https://www.reddit.com/r/dotnet/comments/9jn69g/question_not_having_much_luck_on_stack_overflow/

What can we do to make multiple domains with asp.net core easy? Am I right that a policy could work? Should come up with a sample.

**Comment by mkArtakMSFT** [comment]
@JamesNK is this done already? Is this a sample?

**Comment by JamesNK** [comment]
Its mostly done. Needs to be moved to the sample repo.
