### ISSUE TITLE
Consider adding a way to use strict comparison for routes matching

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#4220]
_From @PinpointTownes on February 6, 2017 4:3_

http://stackoverflow.com/questions/42048770/asp-net-core-openiddict-throws-an-openid-connect-response-cannot-be-returned-fr

Consider this action:

```csharp
[HttpPost("~/path")]
public IActionResult Test() => Empty();
```

Oddly, either the routing stack or MVC seems to consider `/path/` requests as valid candidates for this route/action, which is incorrect as `/path` and `/path/` are two different addresses.

Is there any particular reason for this (abusive) normalization?

/cc @Eilon @rynowak 

_Copied from original issue: aspnet/Mvc#5757_

**Comment by PinpointTownes** [comment]
"c"? These labels are more and more succinct 🤣

**Comment by Eilon** [comment]
It makes GitHub search queries run faster, probably :)

**Comment by mkArtakMSFT** [comment]
Closing this as we have no plans for doing this.

**Comment by PinpointTownes** [comment]
That's unfortunate, since things are still quite inconsistent: https://github.com/aspnet/AspNetCore/issues/4220#issuecomment-279137659

At the very least, this should be documented somewhere.
