### ISSUE TITLE
Simple controller no longer working

### ISSUE THREAD

**Issue by KirillOsenkov** [aspnet/AspNetCore#4226]
1. `git clone https://github.com/KirillOsenkov/SourceBrowser`
2. `msbuild /r`
3. Open `SourceBrowser.sln` in VS and F5 - this will generate a static website
4. Set `SourceIndexServer` project as Startup and F5 again

#### Description of the problem:

`http://localhost:58320/api/symbols?symbol=pro` is supposed to call my SymbolsController

Actual results: 404

This used to work in 2.0.

**Comment by KirillOsenkov** [comment]
Yup, I confirmed that removing that line fixes it. Thanks David!

This was to work around this issue: https://github.com/KirillOsenkov/SourceBrowser/issues/93
and https://github.com/aspnet/MvcPrecompilation/issues/162

**Comment by pranavkm** [comment]
> Why did this work in 2.0 but not 2.1?

In 2.0 the DependencyContext's runtime graph would accurately say that a project referenced MVC. In 2.1, transitive references to shared fx don't show up in the runtime graph: https://github.com/aspnet/Mvc/issues/7617#issuecomment-380194466

**Comment by pranavkm** [comment]
@KirillOsenkov the precompilation tool has been deprecated and is off by default since 2.1. You can safely remove both these lines from your project file.
