### ISSUE TITLE
[Announcement] Empty Microsoft.AspNetCore.Server.Kestrel.Https assembly being removed

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#4228]
In ASP.NET Core 2.1 the contents of Microsoft.AspNetCore.Server.Kestrel.Https.dll were moved to Microsoft.AspNetCore.Server.Kestrel.Core.dll. This was done in a non-breaking way using TypeForwardedTo attributes. In the next major release (3.0) this empty assembly will be removed. Note that the nuget package was already being removed as part of https://github.com/aspnet/Announcements/issues/325.

Action required:
- Libraries referencing Microsoft.AspNetCore.Server.Kestrel.Https 2.0 should update all AspNetCore dependencies to 2.1 or later. Otherwise they may break when loaded into a 3.0 application.
- Applications and libraries targeting AspNetCore 2.1 and later should remove any direct references to the Microsoft.AspNetCore.Server.Kestrel.Https nuget package.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
