### ISSUE TITLE
Don't allocate a closure for IO callbacks in IIS in proc

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#4229]
https://github.com/aspnet/AspNetCore/blob/4d57528704d7ec54570f5960b3b9ddca503d5c89/src/IISIntegration/src/Microsoft.AspNetCore.Server.IIS/Core/IO/AsyncIOOperation.cs#L154

While we're at it we should not capture the ExecutionContext. Lets make the switch to UnsafeQueueUserWorkItem as well.

cc @pakrym @jkotalik

**Comment by muratg** [comment]
@davidfowl Any measurements or guess in how much of a perf gain this would be? What's your take on relative priority of this?

**Comment by muratg** [comment]
cc @shirhatti since he's interested in this as well.

**Comment by davidfowl** [comment]
Priority is low but it can be done trivially so once we properly to the mondo repo, I can send a PR.
