### ISSUE TITLE
ASP.NET CORE Web API: Model value is null when doing HTTP Post requests with null Guid

### ISSUE THREAD

**Issue by balukantu** [aspnet/AspNetCore#4230]
I'm facing a problem doing post requests via ASP.NET Core Web API. So here's my scenario:

I'm trying to do a HTTP Post request to an api endpoint with a complex parameter.

**API Endpoint**
`[HttpPost]
 [Route("api/createstudent")]
 public async Task<ActionResult> CreateStudent([FromBody]Student student)
    {
        // Service logic
    }`

**Model**
`public class Student
{
    public Guid StudentId { get; set; }
    public string StudentName { get; set; }
}`

My problem is that every time I make a post request to this endpoint the model value is null if I pass below the object.
`{"studentId": null,"studentName": "Sam"}`

Whereas If I pass empty Guid as below, I am able to get the model.
`{ "studentId": "00000000-0000-0000-0000-000000000000", "studentName": "Sam" }`

Is this a bug in ASP.NET Core 2? As I was able to pass null / Empty Guid for StudentId in .NET Framework WEB API.

**Comment by balukantu** [comment]
Can't we send null value? as I Was able to send the same (null) value in .NET Framework Api.

**Comment by davidfowl** [comment]
GUID's can't be assigned a null value. I'm not sure what ASP.NET Web API did here.

**Comment by davidfowl** [comment]
cc @rynowak @dougbu

**Comment by dougbu** [comment]
There should be an error in `ModelState` in this scenario. That would be a bug if not.

One difference from ASP.NET Web API in this area is that ASP.NET Core MVC will _never_ create a model for a `[FromBody]` parameter or property when the deserializer (Json.NET in this case) encounters an error. (ASP.NET Web API was inconsistent.)

IIRC the ASP,NET Core reasoning is an API, unlike a view, can't do much with an incomplete model.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by GusBeare** [comment]
I'm enjoying this same issue. Problem is that for db inserts don't have the Guid yet but I want the model to match the table which has the Guid as the non nullable PK.  The client is JS and I don't really want to try and create a guid with JS so I want to do it in the C# or DB once I've hit the endpoint.

Sending an empty guid string works but is there another way?

**Comment by GusBeare** [comment]
I thought I'd solved this by adding [JsonIgnore] to the property. That works by enabling theGuid to be empty on post but it breaks the HttpGet because the Guid is left out.

I've seen fancy methods of with attributes the enable different things for serialise and deserialise but none of them are very elegant.
