### ISSUE TITLE
void Initialize(RequestContext requestContext) doesn't exist in asp core

### ISSUE THREAD

**Issue by vlapenkov** [aspnet/AspNetCore#4233]
In MVC 5 i used Initialize method  in base controller to set up culture, and other controller member variables.
What you offer in asp core.
Thanks in advance!

**Comment by davidfowl** [comment]
You can probably use OnActionExecuting to do the same thing.

```
public virtual void OnActionExecuting(ActionExecutingContext context)
```

cc @rynowak
