### ISSUE TITLE
View discovery is broken for 3.0

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#4241]
Steps:
- Get latest SDK from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe. Currently it is `3.0.100-preview-009784`.
- `dotnet new mvc`
- `dotnet run`
- Navigate to https://localhost:5001

Expected:
Index page loads successfully

Actual:
![image](https://user-images.githubusercontent.com/1579269/49051717-d590db80-f19d-11e8-80a0-df521406b863.png)

Also for `dotnet new webapp`, I get a 404 when navigating to https://localhost:5001

Originally filed:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733888

**Comment by ajaybhargavb** [comment]
Spoke to @natemcmaster about this. His guess is that MVC used to read this file (via DependencyContext) and look for entries for the  "Microsoft.AspNetCore.Mvc" package. In 3.0, the package graph is different. It has been flattened to a single package, Microsoft.AspNetCore.App
​So, if anything in the runtime is expecting specific NuGet packages to appear in the restore graph or in .deps.json, it may have been broken by this change.

@javiercn, do you have any context on this since @pranavkm is out?

**Comment by javiercn** [comment]
I believe this was fixed last week by @natemcmaster. See https://github.com/aspnet/Mvc/commit/bfdecc8f5e06768d7aadb670db3bd2eda9ef15d1#diff-dd65a77cb8648ac368bd71788fe64582R20

**Comment by natemcmaster** [comment]
The 3.0.100-preview-009784 SDK bundles a version of the aspnet runtime with the fix I made in https://github.com/aspnet/Mvc/pull/8751. That fixed controller discovery. This issue appears to be slightly different. Views are not found as expected. I wonder if this is the result of https://github.com/aspnet/Mvc/pull/8755

**Comment by javiercn** [comment]
I'll take a look once I'm in the office

**Comment by rynowak** [comment]
It's possible that this could be "just a bug". It's definitely intended that the templates use build-time compilation only.

**Comment by javiercn** [comment]
Looks like the Razor SDK in the CLI is out of date. We are looking into update, this issue should go away once it's update.

**Comment by natemcmaster** [comment]
I think this is resolved by https://github.com/dotnet/toolset/pull/47. I'm leaving open until we verify this fix in a new SDK build.

**Comment by natemcmaster** [comment]
I validated this is fixed in 3.0.100-preview-009795.
