### ISSUE TITLE
Convert projects in this repo to use ProjectReference

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4246]
Follow-up to #3598.

The first phase of reducing repos was to merge the source code into a single repo. The second phase is to convert them from isolated folders of code with PackageReference across repo boundaries, to projects which use `ProjectReference`.

We've already started some of this work. See https://github.com/aspnet/AspNetCore/pull/4013 for example and https://github.com/aspnet/AspNetCore/tree/master/src/DataProtection.

As done in #4013, we implement this using `<Reference>` items in .csproj and custom Reference resolution targets. This is done so we can automatically pick the right versions of assemblies to used based on conditions such as, is this a test project? is this branch building a patch or a new minor release? what versions were used in the last stable release? etc.

See also https://github.com/aspnet/specs/blob/master/runtime/design-notes/2018-10-03-mondo-source-org.md for the spec on source code organization.

## Repo groups to convert

- [x] Razor @ajaybhargavb  
- [x] HttpSysServer https://github.com/aspnet/AspNetCore/pull/4335
- [x] Antiforgery - Justin
- [x] IISIntegration https://github.com/aspnet/AspNetCore/pull/4311
- [x] CORS - Justin
- [x] StaticFiles - Justin
- [x] Routing @natemcmaster 
- [x] ResponseCaching -Justin
- [x] Session @JunTaoLuo 
- [x] ServerTests @JunTaoLuo @jkotalik 
- [x] Localization @natemcmaster 
- [x] Security @jkotalik 
- [x] MetaPackages @JunTaoLuo 
- [x] Mvc @ajaybhargavb 
- [x] JavaScriptServices @jkotalik 
- [x] AADIntegration @natemcmaster 
- [x] Identity @JunTaoLuo 
- [x] MvcPrecompilation @JunTaoLuo 
- [x] AzureIntegration @natemcmaster 
- [x] SignalR @natemcmaster 
- [x] Components @natemcmaster 
- [x] MusicStore @jkotalik 
- [x] AuthSamples @jkotalik 
- [ ] Templating @natemcmaster

**Comment by natemcmaster** [comment]
cc @jkotalik who is helping do this for src/IISIntegration/

**Comment by jkotalik** [comment]
Once I get this done for IISIntegration, I'll do other repos too. IISIntegration was significantly more difficult to port than other repos (due to native dependencies).

**Comment by natemcmaster** [comment]
I'm adding a checklist to the original issue to track the groups of subrepos that we need to convert. Let's start by doing these one at a time.

**Comment by natemcmaster** [comment]
FYI - here is the script I've been using to convert Project/Package refs to just `<Reference>`

https://gist.github.com/natemcmaster/40556be8f8d821a225f48afbd743bbeb

Usage:
```ps1
PS> Get-ChildItem *.csproj -Recurse | % { C:\src\scripts\mk_ref.ps1 $_ }
```

**Comment by natemcmaster** [comment]
Once https://github.com/aspnet/AspNetCore/pull/4954 is merged and makes its way up to master, I think we should be unblocked to convert Components and Mvc.

FYI @SteveSandersonMS @javiercn - the refactoring on Components is likely to be fairly disruptive. Do you have any big changes that need to go in this week?

**Comment by SteveSandersonMS** [comment]
Thanks for the heads-up, @natemcmaster! I’d definitely like to merge #5166 before any other disruptive change goes in. Should be ready to merge as soon as it’s reviewed.

**Comment by SteveSandersonMS** [comment]
@natemcmaster #5166 is merged now, so you should be OK to do changes to Components to use `<Reference>` etc. When doing so, please be sure to run the E2E tests (`Microsoft.AspNetCore.Components.E2ETest`) manually to verify that it hasn't broken aspects of how we bundle stuff for both server and client-side execution. We're going to run those E2E tests automatically in CI soon (#5158) but for now it's manual.

**Comment by natemcmaster** [comment]
@SteveSandersonMS I started looking into this but found code in src/Components/ that I'm unsure about, specifically, the code in src/Components/blazor/. Can you take a look at the details I posted in this comment? https://github.com/aspnet/AspNetCore-Internal/issues/1535#issuecomment-450685185
