### ISSUE TITLE
Add scripts for partially building subsets of projects in this repo

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4247]
This repo contains a lot of stuff. Building all of it is not necessarily what you want to do. We should add build scripts or MSBuild targets so you can build subsets of projects from this repo. 

This repo currently has these subsets of projects:

* .NET (C#)
* C++
* Visual Studio extensions
* NPM packages
* Java projects (using Gradle)
* Wix projects (windows installers)
* Projects for Deb, rpm, zip, tar.gz installers
* Projects for the shared framework and targeting packs

Furthermore, projects could also be broken down by categories

* Test projects
* Samples
* Shipping product assemblies
* Reference assemblies (once #3610 is done)

**Proposals**
1. I believe the most common scenario for running build.cmd is for contributors to build enough projects so they can open Visual Studio and continue work from there. Therefore, I propose `build.cmd` with no arguments should print a message about usage and compile just enough to make most `.sln` files work in this repo.

```
> build.cmd
Warning: running the build script without arguments will only build a subset of assets. 
Run `build.cmd -help` for more details on usage.
```

2. Add additional flags for `build.cmd` to build the various groups mentioned above. Example usage might look like this:
```
build.cmd -jar
build.cmd -npm
build.cmd -vsix
build.cmd -installers
build.cmd -managed
build.cmd -native
```
These flags could also be combined.
```
build.cmd -jar -npm -vsix
```
Finally, we can add a flag for building everything, which would be invoked by CI. `build.cmd -all`.

3. Update build.cmd to build subdirectories. Example usage:
```
cd src/Servers/Kestrel/
../../../build.cmd .
```
This would build the projects in src/Servers/Kestrel/.

**Comment by Tratcher** [comment]
On 3, why not have a local build.cmd for feature areas like kestrel? It can refer to the root one if it needs to.

**Comment by natemcmaster** [comment]
I would be okay with that, but only if build scripts in subdirectories are just sugar for invoking the root build script. Example:
```bat
@ECHO OFF
SET RepoRoot="%~dp0..\.."
%RepoRoot%\build.cmd '%~dp0' %*
```
