### ISSUE TITLE
AspNetCore on .Net Framework threads hang

### ISSUE THREAD

**Issue by valeriob** [aspnet/AspNetCore#4253]
### Describe the bug
Running the repro attached causes aspnetcore 2.1.6 application running on .net framework 4.7.2 to hang and cause thread starvation, the same use case works well on aspnetcore.

### To Reproduce
1) Run the ConsoleApp LatencyTest (wich sends one request every 100ms to the web app)
2) Run WebApplication and observe the number of threads of the process raise because the are all blocked, and only one request/s get served.

1) Run the ConsoleApp LatencyTest
2) Run WebApplicationCore and observe that the number of threads converge quickly to a number and then the process starts handling request normally.

### Expected behavior
That WebApplication behaves like WebApplicationCore

We where able to reach this small repro after quite some time, and we observed the starvation in production also during normal operation, not only on startup. Doing it on startup is just the convenient way to reproduce. 

[AspNetCoreHangs.zip](https://github.com/aspnet/AspNetCore/files/2621052/AspNetCoreHangs.zip)

**Comment by ayende** [comment]
Maybe you haven't attached it yet? But there is no attachment here.

**Comment by valeriob** [comment]
My bad, it's there now :D

**Comment by davidfowl** [comment]
I didn't run the sample but I did look at the code.

https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait 

The thing that's saving you in the WebApplication is likely the request queue (you can verify that with performance counters). Do you have a real repro here or something else that doesn't block like this? Did you encounter this behavior in some other way that non-obvious? 

The advice here is basically to avoid making blocking calls like this and to use async/await instead.

**Comment by davidfowl** [comment]
You can't do sync over async and expect it to scale. That's what the link I sent tries to explain. If your sync APIs are wrappers around your async APIs that call .Wait/GetAwaiter().GetResult() then you're going to have a **BAD** time. If you want to do something like this then you can write a request queue middleware that throttles the number of concurrent requests to something reasonable (that's based on the specific application).

We have discussed shipping a middleware like this but there's no concrete plan at the moment. Writing a simple middleware that tracks concurrent requests and rejects requests over that limit shouldn't be too hard though.

**Comment by ayende** [comment]
The issue isn't that I don't expect it to scale, that is fine.
But the issue is that we are seeing _hangs_ because of this.

The minimum reproduction for this is:

```
    public JsonResult Ping()
    {
        Task.Delay(100).GetAwaiter().GetResult();
        return Json(new { Status = "OK" });
    }
```

The test application is sending a request per 100 ms, so in theory, this should be a match.
I would expect this to be using 2 - 3 threads overall to handle this kind of load, and that would be perfectly fine.

The problem is that it isn't actually doing that, and it will eventually grind to a halt.

**Comment by davidfowl** [comment]
> I would expect this to be using 2 - 3 threads overall to handle this kind of load, and that would be perfectly fine.

2-3 threads per request you mean right? And you're sending how many requests in parallel before you see these hangs? Are the hangs permanent or are you just seeing slow thread pool ramp up?

https://blogs.msdn.microsoft.com/vancem/2018/10/16/diagnosing-net-core-threadpool-starvation-with-perfview-why-my-service-is-not-saturating-all-cores-or-seems-to-stall/

Running through those steps in perf view should give you some information about what's happening when you're making those requests.

**Comment by benaadams** [comment]
>  sends one request every 100ms to the web app

This sync over async line requires 2 threads; one that's blocked and can't do anything else, and then a second one to unblock it after the delay:
```csharp
Task.Delay(100).GetAwaiter().GetResult();
```
The ThreadPool tries to counter thread starvation by injecting new threads; but that rate is one every 500ms. So sending a request that eats one thread and requires a second to unblock it every 100ms means you are eating threads x5 faster than the ThreadPool will inject new ones; which means you will have no threads to unblock the blocked threads. 

This is why `.Wait`/`.Result`/`.GetAwaiter().GetResult()` or "sync over async" is particularly bad as you run out of threads to release the blocked threads.

If instead you had the following it would be fine as while its awaiting its using 0 threads:
```csharp
public Task<JsonResult> Ping()
{
    await Task.Delay(100);
    return Json(new { Status = "OK" });
}
```

**Comment by ayende** [comment]
In that case, why does it only happen when it is asp.net core on full .NET?

And I assume that the workaround would be to set `ThreadPool.SetMinThreads` to a high enough number to ensure that this works?

**Comment by benaadams** [comment]
Works on .NET Core
```
Started
... 265 ms
... 466 ms
... 155 ms
... 371 ms
... 113 ms
... 110 ms
... 107 ms
... 109 ms
... 109 ms
... 114 ms
... 108 ms
... 108 ms
... 114 ms
... 109 ms
... 107 ms
... 114 ms
... 109 ms
... 108 ms
... 108 ms
... 107 ms
... 107 ms
... 110 ms
... 108 ms
... 108 ms
... 109 ms
... 107 ms
```

Seems to work on full .NET also 
```
Started
... 1784 ms
... 1999 ms
... 1453 ms
... 1676 ms
... 2095 ms
... 1892 ms
... 1238 ms
... 1560 ms
... 1403 ms
... 882 ms
... 1430 ms
... 1214 ms
... 1322 ms
... 1759 ms
... 999 ms
... 1652 ms
... 1107 ms
... 1549 ms
... 453 ms
... 669 ms
... 346 ms
... 778 ms
... 233 ms
... 888 ms
... 125 ms
... 561 ms
... 108 ms
... 116 ms
... 108 ms
... 112 ms
... 110 ms
... 110 ms
```
What results are you seeing?

**Comment by benaadams** [comment]
Note this is on an 4 core + 4HT machine so MinThreads probably starts at 8; which is likely high enough to to starve at that input rate and blocking rate.

> And I assume that the workaround would be to set ThreadPool.SetMinThreads to a high enough number to ensure that this works?

Yes; though that's just pushing out the issue to a high threshold and will consume a lot more memory. Whereas going async will completely resolve the issue.

**Comment by valeriob** [comment]
I was able to mitigate the issue in production by increasing the threadpool min value.
What i do not yet understand is that the same business logic and load was fine with mvc5.
Thanks for the support.

**Comment by davidfowl** [comment]
@valeriob I'd be interested in 2 things:
- What do the performance counters for the request queue look like under this load on .NET Framework
- What are the min threads set to on .NET Framework.

**Comment by valeriob** [comment]
hi David,
1) they pile up, and then suddenly they all get served, in the meanwhile the thread count rises with speed 1 thread per second.
2) never had to mess up with them, so the default. It's a 4 core vm.

**Comment by davidfowl** [comment]
> they pile up, and then suddenly they all get served, in the meanwhile the thread count rises with speed 1 thread per second.

Do you have access? What does the queue look like?

> never had to mess up with them, so the default. It's a 4 core vm.

Sure but your hoster might. Azure App service for example changes the defaults.
