### ISSUE TITLE
Support for AES256 encryption in DataProtection

### ISSUE THREAD

**Issue by aevitas** [aspnet/AspNetCore#4256]
I am currently working on an ASP.NET Core application that runs in several Docker containers. We are using cookie based authentication, and to avoid users being logged out when load balanced between containers, we use a shared key persisted in Azure Blob Storage. 

When persisting keys in storage, ideally they'd be encrypted. Currently, as I see it, we have two options: DPAPI, which is Windows only, or X.509 certificates, which I can't get to work for the life of me with anything other than a PFX.

Would there be any significant downsides in using plain old AES256 encryption to secure the keys in storage? Something along the lines of `[...].ProtectKeysWithAes(key, iv)`.

As a developer who mainly targets Linux environments (therefore DPAPI is out of the question, and I doubt it'd work in a container environment) it would vastly simplify my code while still making the keys secure in storage.

Looking forward to your thoughts!

**Comment by blowdart** [comment]
Not in the box no. You could write your own protection layer (IXmlEncryptor, IXmlDecryptor), but as plain old AES wouldn't support key rotation it's not something we'd be interesting in doing.

**Comment by aevitas** [comment]
Thanks for your reply. I suspected as much - I'll roll my own in that case.
