### ISSUE TITLE
How to start AspNetCore in a different thread from another process?

### ISSUE THREAD

**Issue by rprimora** [aspnet/AspNetCore#4280]
Currently we have a Windows Service running at our customer. This service hosts two WCF services. It works perfectly. Now we want to add another service to this. For this we made an AspNet Core project(targeting net461) and the output type of this project is set to class library.

We were hoping we could simply build the application the same way it is built by the Main method and simply call Run on it. In fact this is exactly what we do and we can actually see the application booting up since we have that starting info that AspNet Core application prints out such as Hosting environment, Content root path, Now listening on, etc...

The problem with this is that no request gets passed to Kestrel. If I use Postman I won't get any result back. However, application works fine if we set up the output type to Windows or Console.

Is there a way to start the AspNetCore(that is a class library) from another process?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
