### ISSUE TITLE
Problem in user passwords when moving from MVC5 to asp.Core 2.1

### ISSUE THREAD

**Issue by vlapenkov** [aspnet/AspNetCore#4281]
### Describe the bug
I have MVC5 project with EF and  Identity version 2.0.0.0 and authentication by login and password.
I decided to move project to asp 2.1 Core, but have one trouble.

Identity Core generates other password hashes than Identity 2.0.0.0 (from MVC5). So I can't restore asp user passwords.

For instance 'facility' password in Identity 2.0.0.0 (MVC5 ) corresponds ANflHJvWgWouno9jBDM3IFMBzdXEkJYh+k01zikmWJfVv+2jsckkyRWB3d2o1iu8OQ==.
The same password in asp.core Identity is AQAAAAEAACcQAAAAEIVjHvVvcyEEQf+JnrpNsu3ir9NRKJGRhvgR4w6E1AkAz0CyiZrmw+09QBMC1Sy/5g==.

My users can't login when i move project from MVC5 to CORE.
Please any suggestions.

**Comment by blowdart** [comment]
The password storage also includes a version number for the hashing algorithm and we support the older, less secure one precisely for this. Did you implement a custom hashing algorithm at all?

**Comment by vlapenkov** [comment]
I didn't implement any custom algoritms.

**Comment by blowdart** [comment]
But did you actually try logging on with an old password? The data in the password field is not just the hash, it's also a version number which points to the hashing configuration. It should work.

**Comment by vlapenkov** [comment]
You are right!  I didn't change password but i filled 'NormalizedUserName' (it was empty)  and i logged in. Thanks! Identity is using NormalizedUserName instead of Username?

**Comment by blowdart** [comment]
Yes, because normalized allows us to detect ascii "almost" duplicates, and stop attempted impersonation.
