### ISSUE TITLE
POST body is null intermittently on Linux self hosted app

### ISSUE THREAD

**Issue by prajwalmr62** [aspnet/AspNetCore#4283]
### Describe the bug

We have two environments, one running on virtual Windows instance and another on AWS Linux instance.

Configuration of both environment is as of below.

**Windows:**
Operating System: Windows Server 2012 R2,
Dotnet Core: version 2.0.7
Server: IIS 8.5.9600

**AWS Linux:**
Operating System: Amazon Linux release 2 (Karoo)
Dotnet Core: version 2.0.6
Dotnet Tools: version 2.1.101
Server: Self hosted by `dotnet run <dll>`

Same code has been hosted in both the environment. In Windows the app is able to get the request and request body has content. But on AWS Linux, app is getting the request, but the request body is null sometimes.

### To Reproduce

1. Have large request body. In our case it is somewhere around 10KB.
2. Entire request is contained in single model in action using `[fromBody]`.
3. Send the request.
4. You should see null request body for some requests.

### Expected behavior
Request should contain a body.

### Additional context
We have multiple post calls from UI, written on Angular 6. For all post calls both environments are working fine. But the request body is less than a KB, except for this case.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
