### ISSUE TITLE
Microsoft.AspNetCore.AspNetCoreModuleV2 doesn't have preview sufix in 2.2.1 build

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#4289]
http://aspnetci/viewLog.html?buildId=597957&tab=artifacts&buildTypeId=Releases_22xPublic_UniverseCoherence#!-8lo9sf546pu2,1u62nn99uqscm

@jkotalik @natemcmaster

**Comment by sebastienros** [comment]
Maybe unrelated, but are `Microsoft.AspNetCore.Server.IIS`, `Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv` and `Microsoft.NET.Sdk.Razor` supposed to be built and pushed on myget too for servicing? I only see 2.2.0 versions.

**Comment by natemcmaster** [comment]
@sebastienros Microsoft.AspNetCore.Server.IIS yes. The others aren't shipping updates in 2.2.1.

**Comment by muratg** [comment]
This is in 2.2.2 just for tracking purposes. This is infra-only change.

**Comment by muratg** [comment]
@pakrym this is approved as infra only change in 2.2.2

**Comment by pakrym** [comment]
Not true anymore.
