### ISSUE TITLE
Investigate why we didn't catch Razor SDK regressions building a 2.2 project

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4292]
We have integration tests for building a 2.1 project with the latest Razor SDK in the Razor codebase - however we managed to regress this scenario (see https://github.com/aspnet/AspNetCore/pull/4290) without detecting it. This is an important test case because the newer SDK will be used by default by VS, and it needs to be able to build older versions.

**Comment by rynowak** [comment]
I spent about 5 mins investigating this and reached the conclusion that in our test the 2.2 tasks are used with the 2.2 rzc, but in the actual product the 3.0 tasks are used with the 2.2 rzc. We definitely intend for the 3.0 tasks to be used in all cases, so fixing this in our test setup would make this test more honest.

**Comment by pranavkm** [comment]
Think we're just missing a test here - https://github.com/aspnet/AspNetCore/issues/5101

**Comment by ajaybhargavb** [comment]
> We have integration tests for building a 2.1 project with the latest Razor SDK

Spent sometime looking at this with @pranavkm. This was because we didn't have an integration test for 2.2 project similar to what we have for a 2.1 project

**Comment by ajaybhargavb** [comment]
Closing this as we already have an issue to add this test https://github.com/aspnet/AspNetCore/issues/5101

**Comment by rynowak** [comment]
Are you *really* sure about that?

When I looked into it, I found out this:

>  spent about 5 mins investigating this and reached the conclusion that in our test the 2.2 tasks are used with the 2.2 rzc, but in the actual product the 3.0 tasks are used with the 2.2 rzc. We definitely intend for the 3.0 tasks to be used in all cases, so fixing this in our test setup would make this test more honest.

Is that the same conclusion you came to? What's the root cause of **that**?

**Comment by rynowak** [comment]
I'm reopening this *just* to be mean 😝

**Comment by ajaybhargavb** [comment]
> reached the conclusion that in our test the 2.2 tasks are used with the 2.2 rzc

We don't have an integration test for 2.2 yet. I assume what you were seeing was for the 2.1 integration test. In that case, yes, the 2.1 test is using the 2.1 tasks (from the Razor.Design package) instead of the 3.0 tasks. @pranavkm said that 2.1 projects will always use the 2.1 tasks and it's okay for it to be that way. So the only action left was to add a test for the 2.2 case for which we already have an issue. We just need to make sure in the test that we add 2.2 test uses 3.0 tasks.
@pranavkm, could you add to this why 2.1 doesn't use 3.0 tasks?

**Comment by pranavkm** [comment]
We fixed 2.2 Razor.Design package to use the singleton task and consequently it uses the task from the SDK. We never got around to fixing \ patching 2.1 and it'll continue using the task in the Razor.Design package.

**Comment by rynowak** [comment]
Ok cool beans. We should prioritize adding a 2.2 test case, it won't take long...
