### ISSUE TITLE
Reconsider versioning story for rzc

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4294]
see: https://github.com/aspnet/AspNetCore/pull/4290

The Razor SDK tasks are a singleton and currently talk to all version of the rzc command line tool - the version depends on what project you're building. However, since we ship rzc in the SDK, it is also a singleton for 3.0 and future releases. 

This means that we already have to deal with the complexity of making all future release of rzc backwards compatible for 3.0. We might limit the overall complexity by making rzc that ships in the SDK backwards compatible all the down to 2.1 - or else it will always be possible to introduce this kind of bug.

**Comment by mkArtakMSFT** [comment]
Closing this as we will not probably change anything here.
