### ISSUE TITLE
Add CompatibilityVersion.Version_3_0

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#4296]
### Describe the bug
We need to add a new enum [here](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/CompatibilityVersion.cs#L84) to reflect the new version. This also needs to be update in the templates.

CC @mkArtakMSFT @DamianEdwards and @davidfowl who talked about this previously.

**Comment by mkArtakMSFT** [comment]
This is done as part of https://github.com/aspnet/AspNetCore/commit/747420e5aa7cc2c7834cfb9731510286ded6fc03
