### ISSUE TITLE
DataProtection and Streams

### ISSUE THREAD

**Issue by skinkade** [aspnet/AspNetCore#4303]
While this may be beyond the scope of what DataProtection is intended for, it would be useful in certain circumstances if IDataProtector could be used with streams.

For example, if users are uploading potentially large files, the general course of action is `uploadStream.CopyTo(targetFileStream)`. At the moment, it seems like Protecting the file before writing it to its destination would require buffering the entire upload and encrypting the whole thing in-memory. Something along the lines of `Protect(inputStream, outputStream)` would help with this.

**Comment by blowdart** [comment]
This is not what data protection is designed for, it's aimed at ephemeral data. We certainly weren't expecting it to be used on large files.

**Comment by Kiechlus** [comment]
@blowdart Is there any workaround how this could be achieved? We rely heavily on Data Protection Middleware in our project but run into memory issues as we always have to copy large streams into a byte[] for encryption.

**Comment by blowdart** [comment]
Please don't comment on closed issues, especially one that has been closed over 6 months ago, it's generally luck that this will get noticed.

And no, there's no work around. It's not what it was designed for.
