### ISSUE TITLE
No .NET Core SDKs were detected - bad help URL

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#4305]
### Describe the bug
In Visual Studio, create a new project, choose ASP.NET Core Web Application. When no SDKs are detected then this page is displayed:

![image](https://user-images.githubusercontent.com/303201/49188434-aa8dce00-f3cf-11e8-8319-2d6d26cfe893.png)

**Learn more** opens a browser at https://review.docs.microsoft.com/en-us/aspnet/core/testing/troubleshoot?view=aspnetcore-1.0&branch=pr-en-us-6203#no-net-core-sdks-were-detected

This is a page on the review site. A user will see "Forbidden"

### To Reproduce
1. Remove SDK path
2. Open above dialog
3. Click link

### Expected behavior
Browser is opened at https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot#no-net-core-sdks-were-detected

### Additional context
VS 2017 15.9.3

**Comment by JamesNK** [comment]
Moved to https://developercommunity.visualstudio.com/

**Comment by ShrutiCRC** [comment]
Copy "C:\Program Files\dotnet\sdk\2.1.400\Sdks" to "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks"

**Comment by ShrutiCRC** [comment]
and make sure to replace all the files on the destination if similar file exist window pops up.
