### ISSUE TITLE
IIS AspNet Core module - Port Assignment Race Condition

### ISSUE THREAD

**Issue by ashkabarnya** [aspnet/AspNetCore#4306]
### Describe the bug
It looks like IIS AspNet Core module tries to assign the same port to multiple .NET Core based web apps when the apps are first hit at the same time. As the result the apps give 502 error responses on the first request.

### To Reproduce
Multiple .NET Core Based Web Services are hosted behind IIS. 
When several apps are hit at the same time after a period of inactivity they return 502 error. 
The event log shows the following error for multiple applications (the port for all apps is the same):
"Application 'xxx' with physical root 'xxx' created process with commandline 'dotnet .\xxx.dll' but failed to listen on the given port 'xxxxx'"

The same issue has been mentioned in the following bug report a year ago, but it doesn't look like it has been fixed:
https://github.com/aspnet/AspNetCoreModule/issues/64

**Comment by jkotalik** [comment]
What version of the AspNetCoreModule are you using (dll version)? We added a fix in the latest release of 2.1.x that helps with app starting at the same time.

**Comment by ashkabarnya** [comment]
We have version 8.2.1991.0 version of aspnetcore.dll installed

**Comment by jkotalik** [comment]
Try downloading the latest version of the .NET Hosting bundle from here: https://dotnet.microsoft.com/download. I believe 8.2.1991 didn't include the fix.

**Comment by ashkabarnya** [comment]
Great! Thank you!
Is there any document that maps versions of IIS AspNetCoreModule to specific versions of .NET Hosting Bundles?

**Comment by jkotalik** [comment]
https://dotnet.microsoft.com/download/dotnet-core/2.1 includes the ASP.NET Core IIS Module version on the lefthand side.

Closing for now, go ahead and reopen if you are still hitting this issue.
