### ISSUE TITLE
New ASP.NET Core Web Application dialog is messy

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#4312]
### Describe the bug
The yellow box used to display a warning overlaps with dropdowns.

### To Reproduce
1. Introduce the issue talked about [here](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot?view=aspnetcore-2.1#the-net-core-sdk-is-installed-in-multiple-locations).
2. Open **New ASP.NET Core Web Application** dialog

### Expected behavior
There is some space between the yellow box and the dropdowns.

### Screenshots
![image](https://user-images.githubusercontent.com/303201/49192022-15de9c80-f3de-11e8-9c30-b328e0e267d0.png)

**Comment by natemcmaster** [comment]
This is probably a better issue for https://developercommunity.visualstudio.com. The code for this dialog lives in Visual Studio and is owned by @barrytang's team.

**Comment by JamesNK** [comment]
Cool cool. Have reported on https://developercommunity.visualstudio.com/
