### ISSUE TITLE
Message in the CLI 3.0 installer needs to be updated for 3.0.

### ISSUE THREAD

**Issue by v-lawu** [aspnet/AspNetCore#4313]
The message in the .NET Core 3.0 installer still shows for .NET Core 2.2, it needs to be updated for 3.0.

**Screen:**
![image](https://user-images.githubusercontent.com/12129698/49194166-f71bde00-f3bc-11e8-9098-3ebc5a191fd9.png)

**Comment by natemcmaster** [comment]
Thanks @v-lawu. Can you open this issue on https://github.com/dotnet/core-sdk? The installers for the SDK are built in a different project.

cc @livarcocc @leecow

**Comment by v-lawu** [comment]
@natemcmaster  OK, I got it, I've opened issue [#189](https://github.com/dotnet/core-sdk/issues/189) on  https://github.com/dotnet/core-sdk and closed this issue. Thanks for your remind.
