### ISSUE TITLE
Apphost doesn't find framework installations if libhostfx.so is in the same directory

### ISSUE THREAD

**Issue by habibs** [aspnet/AspNetCore#4315]
### Describe the bug
Published app as a 'framework-dependent' and deployed into Ubuntu 16.04.3
Latest asp.net core run-time is installed , but application does not start. 

### To Reproduce
1. Using this version of ASP.NET Core '2.1.6'
2. Run this code 'sudo ./MyWebApi'
3. With these arguments '....'
4. See error : ""It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.6' was not found.""

### Expected behavior
It should resolve shared dependencies and start correctly

### Additional context
 `dotnet --info` :

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

 csproj file: 
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
	  <RuntimeIdentifiers>win10-x64;linux-x64;</RuntimeIdentifiers>    
    <TargetLatestAspNetCoreRuntimePatch>true</TargetLatestAspNetCoreRuntimePatch>
    <GenerateFullPaths>true</GenerateFullPaths>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>  

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.5" />
    <PackageReference Include="DapperExtensions.NetCore" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.7.0" />
    <PackageReference Include="Npgsql" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
```
*.runtimeconfig.json:
```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "2.1.6"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}

**Comment by natemcmaster** [comment]
Can you capture a corehost trace? Launch your app with the COREHOST_TRACE environment variable set and redirect stderr to a file. 

    COREHOST_TRACE=1 dotnet MyWebApp.dll 2>log.txt

**Comment by habibs** [comment]
Hi, Nate. Thanks for helping, here it is:

[log.txt](https://github.com/aspnet/AspNetCore/files/2627978/log.txt)

**Comment by natemcmaster** [comment]
The log does not show an error. You closed the issue, so did you figure out the problem?

**Comment by natemcmaster** [comment]
By the way, the screenshot you sent says that KazhomWebApi is looking for dotnet in /home/habib. Do you have the DOTNET_ROOT environment variable set?

**Comment by habibs** [comment]
No, I don't have any .net core related environment variables set. 
Here what 'printenv' shows:
`XDG_SESSION_ID=2348
TERM=xterm
SHELL=/bin/bash
SSH_TTY=/dev/pts/3
USER=habib
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/habib
PATH=/home/habib/bin:/home/habib/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/habib
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/habib
LOGNAME=habib
LESSOPEN=| /usr/bin/lesspipe %s
XDG_RUNTIME_DIR=/run/user/1005
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/printenv
`

> Can you share the log when you run this?
> 
> ```
> COREHOST_TRACE=1 ./KazkomWebApi 2>log.txt
> ```

Here is the result:
```
Tracing enabled
--- Invoked apphost [version: 2.1.6, commit hash: 3f4f8eebd842c5f7f8b2941828c75384c2e2f1ab] main = {
./KazkomWebApi
}
The managed DLL bound to this executable is: 'KazkomWebApi.dll'
Resolved fxr [/home/habib/libhostfxr.so]...
Invoking fx resolver [/home/habib/libhostfxr.so] v2
Host path: [/home/habib/KazkomWebApi]
Dotnet path: [/home/habib/]
App path: [/home/habib/KazkomWebApi.dll]
Tracing enabled
--- Invoked hostfxr v2 [commit hash: 3f4f8eebd842c5f7f8b2941828c75384c2e2f1ab] main
Checking if CoreCLR path exists=[/home/habib/libcoreclr.so]
--- Executing in a native executable mode...
Using dotnet root path [/home/habib/]
App runtimeconfig.json from [/home/habib/KazkomWebApi.dll]
Runtime config is cfg=/home/habib/KazkomWebApi.runtimeconfig.json dev=/home/habib/KazkomWebApi.runtimeconfig.dev.json
Attempting to read runtime config: /home/habib/KazkomWebApi.runtimeconfig.json
Attempting to read dev runtime config: /home/habib/KazkomWebApi.runtimeconfig.dev.json
Runtime config [/home/habib/KazkomWebApi.runtimeconfig.json] is valid=[1]
--- Resolving FX directory, name 'Microsoft.AspNetCore.App' version '2.1.6'
Searching FX directory in [/home/habib]
Attempting FX roll forward starting from [2.1.6]
'Roll forward on no candidate fx' enabled with value [1]. Looking for the least production greater than or equal to [2.1.6]
No production greater than or equal to [2.1.6] found. Looking for the least preview greater than [2.1.6]
No preview greater than or equal to [2.1.6] found.
Applying patch roll forward from [2.1.6]
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.6' was not found.
  - Check application dependencies and target a framework version installed at:
      /home/habib/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

**Comment by habibs** [comment]
Before doing 'framework dependent deployment' i did 'self-contained' and it worked fine. Several days after installed .net core runtime using instructions from [here](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/runtime-current) and tried 'framework dependent' variant.

**Comment by natemcmaster** [comment]
This issue was moved to dotnet/core-setup#4819
