### ISSUE TITLE
View discovery is broken for 3.0 (F# only)

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#4320]
Steps:

Get latest SDK from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe. Currently it is 3.0.100-preview-009806.
dotnet new mvc -lang F#
dotnet run
Navigate to https://localhost:5001
Expected:
Index page loads successfully

Actual:
![image](https://user-images.githubusercontent.com/1579269/49051717-d590db80-f19d-11e8-80a0-df521406b863.png)

Also for dotnet new webapp, I get a 404 when navigating to https://localhost:5001

Originally filed:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733888

**Comment by mkArtakMSFT** [comment]
The original issue here was applicable to all mvc projects. Now it's only applicable to F# ones.
https://github.com/aspnet/AspNetCore/issues/4241

**Comment by pranavkm** [comment]
Re-assigning. We're going to modify the template to produce a F# + RCL project.

**Comment by pranavkm** [comment]
Blocked on #4947
