### ISSUE TITLE
Run Templating tests on PR-validation builds

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#4321]
Currently tests for Templating are not run on PR-validation builds because it requires the [previous shared runtime](https://github.com/aspnet/AspNetCore/blob/0cbfa9ce6dd03829199977bf8855021580c3171d/build/RepositoryBuild.targets#L74), which is not installed.

It would be really good to start running those tests so templating can get test coverage on its PR's like anything else.

**Comment by natemcmaster** [comment]
The primary challenges for this right now are

1. the templates tests depend on the aspnetcore shared framework
2. the templates tests depend on product .nupkg files existing in the artifacts/ folder.

I believe #4257 will help with part 1. But for now, running the tests locally is a huge pain.

**Comment by ryanbrandenburg** [comment]
As part of this we also need to make it easy/possible to run tests locally. That probably means a `runtests[-setup].ps1` script.

**Comment by ryanbrandenburg** [comment]
Blocked by https://github.com/aspnet/AspNetCore/issues/4257.

**Comment by natemcmaster** [comment]
Should be unblocked by https://github.com/aspnet/AspNetCore/pull/7293

**Comment by ryanbrandenburg** [comment]
These tests are running again.
