### ISSUE TITLE
Different site structure with physicalPath

### ISSUE THREAD

**Issue by ritchxu** [aspnet/AspNetCore#4325]
For a traditional ASP.NET site, we typically have site structure like below under C:\siteFoo
> bin
views
web.config

When programmically adding application with `Site.Applications.Add(string path, string physicalPath)` method, we usually pass `C:\siteFoo` to the parameter `physicalPath`. If we now host ASP.NET Core with the same structure, it seems we have to pass `C:\siteFoo\bin`. Is this expected behavior and right solution by concatinating `\bin`?

**Comment by davidfowl** [comment]
> When programmically adding application with Site.Applications.Add(string path, string physicalPath) method

Are you talking about Microsoft.Web.Administration API?

> If we now host ASP.NET Core with the same structure, it seems we have to pass C:\siteFoo\bin. Is this expected behavior and right solution by concatinating \bin?

There's is no concept of a bin folder in ASP.NET Core, I'd recommend flattening the folder into the root. Appending bin may break other scenarios like the ability to find configuration files that may be in the root of the project (appsettings.json).

**Comment by davidfowl** [comment]
I'd expect your ASP.NET core application to also have more different kinds of assets:

c:\siteFoo

```
Foo.dll
Foo.Views.dll
Foo.pdb
Foo.deps.json
Foo.runtimeconfig.json
wwwroot
web.config
appsettings.json
```
