### ISSUE TITLE
dotnet.exe' has exited - Access violation

### ISSUE THREAD

**Issue by razvan-panda** [aspnet/AspNetCore#4334]
After upgrading .NET core from 2.0 to 2.1 I started getting following error when running the tests:

> The program '[12372] dotnet.exe' has exited with code -1073741819
> (0xc0000005) 'Access violation'.

When in debug mode VS just exits debug mode and prints the message above in the output -> Debug window.

The error happens when stepping over `httpClient.SendAsync(...)`.

I think [this](https://developercommunity.visualstudio.com/content/problem/155641/stackoverflow-causes-access-violation-in-net-core.html) might be the same issue.

**Comment by Eilon** [comment]
Hi @razvan-panda , sorry for the delay getting back to you. If you're still having this issue please log a new issue with full details at https://developercommunity.visualstudio.com/. It is unlikely this is an ASP.NET issue, so I'm closing this item.
