### ISSUE TITLE
Switch package versions to SemVer 2.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4339]
In 3.0, most other .NET Core packages have started using semver 2.0. This solves a common problem with semver v1, which sorts pre-release labels alphabetically instead of numerically. We've worked around this by zero padding, but still occasionally get this wrong.

e.g. (semver 2) `3.0.0-preview.18572.1` vs (semver 1) `3.0.0-preview-18572-01`

Depends on https://github.com/dotnet/core-setup/issues/4795

**Requirements**

- [ ] We used semver v1 in 3.0 preview 1. Ensure NuGet, npm, and Maven would sort preview 2 packages higher. e.g. ensure `3.0.0-preview.18580.1` > `3.0.0-preview-18579-0056`
- [x] Make sure corehost can handle semver2 - tracking https://github.com/dotnet/core-setup/issues/4795
- [ ] Ensure Maven supports semver2.  If not, keep versioning .jar's with semver v1   (Update: it does not, so keep semver1.)
- [x] Ensure npm supports semver2. If not, keep versioning npm packages with semver v1

**Comment by natemcmaster** [comment]
I think it's too late to do this. At least according to MyGet sorting, SemVer v2 packages would sort as older than SemVer v1 packages.

![image](https://user-images.githubusercontent.com/2696087/49529553-18704480-f86b-11e8-87d7-b18691a4adce.png)

**Comment by natemcmaster** [comment]
Now that we include preview numbers, we could consider doing this. Re-opening for consideration.

**Comment by natemcmaster** [comment]
Based on what I see in https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855, Maven does not support semver2, so we'll keep the .jar packages using semver1. (cc @anurse) I'm going to update everything else to use semver2.

**Comment by anurse** [comment]
Yeah, Maven isn't technically semver at all. However it does seem to support `.` and do proper integer sorting now: https://stackoverflow.com/questions/13004443/how-does-maven-sort-version-numbers/31482463#31482463.

Might be worth a try, we can do a quick test of the updated package and see if it works in our core environments (Android Studio, etc.).

**Comment by anurse** [comment]
cc @mikaelm12
