### ISSUE TITLE
Cleanup remaining issues in StreamPipeReader/StreamPipeWriter

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#4344]
Epic https://github.com/aspnet/AspNetCore/issues/8829

There are a few more issues that need to be addressed:
- [ ] Add MaxBufferSize setting
- [x] OnReaderCompleted
- [x] OnWriterCompleted
- [ ] Throw on overlapping Reads/Flush
- [ ] Refactor ReadAsync to avoid an extra async state machine.
- [ ] Creating a new tail segment if we have consumed a certain percentage of the segment.
- [ ] Remove _completedSegments.RemoveAt(0); from StreamPipeWriter

**Comment by anurse** [comment]
What's the story here? @jkotalik @davidfowl

**Comment by jkotalik** [comment]
Let's put this to the next preview. A lot of these types may change based on discussions with Corefx.

**Comment by anurse** [comment]
This is dependent upon all the corefx discussions.

**Comment by anurse** [comment]
Let's clarify the situation here in triage today.

**Comment by davidfowl** [comment]
We should change this bug to reflect the new plan (as casting with interfaces).

**Comment by anurse** [comment]
Perhaps not this one, but yes, we'll revisit the epic to make sure it has issues tracking the right work.

**Comment by anurse** [comment]
Closing in lieu of #9223
