### ISSUE TITLE
I/O aborted because of either a thread exit or an application request. (Error Code 995) 

### ISSUE THREAD

**Issue by kwefah** [aspnet/AspNetCore#4347]
We're currently hosting an AspNetCore 2.0 API on Service Fabric, using HttpSys as our webserver. Every once in a while, we get the following exception from the HttpSys middleware.

Microsoft.AspNetCore.Server.HttpSys.HttpSysException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request. (Error Code 995)

From looking around, it seems that this exception is thrown at the IO completion port layer when the process fails to read from a socket because it's been closed. I wonder if the assumption then is that the client was the one who dropped the connection in this particular scenario. Could anyone shed a bit of light on this?

**Comment by Tratcher** [comment]
It's possible for the request to be terminated from the client or server. Do you use cancellation tokens with your reads or writes, or call HttpContext.Abort() anywhere? Those might cause this error from the server side. Otherwise it would be the client aborting.

**Comment by kwefah** [comment]
Thanks for the response. We're not currently using any cancellation tokens or explicitly aborting the http context on the API side

**Comment by anurse** [comment]
Apologies for the delayed response @kwefah. Can you post a runnable sample project that reproduces the issue?

**Comment by anurse** [comment]
I'm going to close this just because it's a little stale now. Feel free to re-open it if you're still seeing this and can provide more information!
