### ISSUE TITLE
Variation in behavior of status code handlers with mixed Windows and anonymous auth

### ISSUE THREAD

**Issue by jcasale** [aspnet/AspNetCore#4352]
### Describe the bug
I am trying to use mixed Windows and anonymous authentication for an application that is hosted in IIS. Controllers are decorated with `[Authorize(nameof("UserGroup"))]` with the exception of the home controller decorated with `[AllowAnonymous]` which contains an index view providing links and a status code handler view.

In Visual Studio 15.9.3 with anonymous disabled, both `UseStatusCodePagesWithRedirects` and `UseStatusCodePagesWithRedirects` work. Actual auth failures or errors are correctly rendered and the error parameter is passed to the action.

When anonymous  is enabled, I get spurious authentication errors for each request, however the site works if `UseStatusCodePagesWithReExecute` is enabled but the page never renders correctly. The url is constructed correctly such as `/Home/StatusCodeHandler/400` but the action never has the parameter bound. If `UseStatusCodePagesWithRedirects` is enabled, nothing works as the initial auth failure always triggers it?

My app is configured as follows:
```cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    // app.UseStatusCodePagesWithReExecute("/Home/StatusCodeHandler/{0}");
    app.UseStatusCodePagesWithRedirects("/Home/StatusCodeHandler/{0}");
}
public void ConfigureServices(IServiceCollection services)
{
    services.AddAuthorization(options =>
    {
        options.AddPolicy(nameof("UserGroup"), policy =>
        {
            policy.RequireAuthenticatedUser();
            policy.RequireRole("CN=...DC=example,DC=com");
        });
    });
    services.AddAuthentication(IISDefaults.AuthenticationScheme);
}
```

### Expected behavior
I assumed both handlers would behave the same. I have two issues, I want to use `UseStatusCodePagesWithReExecute` but it doesn't function correctly in VS. I don't understand why the model binder works correctly when `UseStatusCodePagesWithRedirects` is enabled, but I can't ever authenticate.

### Additional context
 ```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by muratg** [comment]
Does your app run with in-proc or out-of-proc mode ANCM? (You can check your web.config)

**Comment by jcasale** [comment]
I am using 2.1 in this project so out-proc as far as I understand.

**Comment by Eilon** [comment]
With Windows Auth the redirect pattern won't work because when the 401 is returned from the server, the status page redirect will try to show the appropriate page for the 401 status, at which point the authentication flow is stopped.

For this case we recommend using the re-execute option because it's all part of one request (no redirect happens, and the status code won't be changed).

**Comment by jcasale** [comment]
The re-execute handler receives the correct url but fails to bind the parameter, so the actual integer code is lost though.

**Comment by Eilon** [comment]
@jcasale - can you show how you were trying to get the integer code? Were you following the example at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.2#redirect-re-execute-extension-methods ?

**Comment by jcasale** [comment]
Hi @Eilon, I had the action parameter designated as a nullable int however after finishing the upgrade to 2.2 and trying to repro this, it is now working as expected.

Thanks!
