### ISSUE TITLE
Anchors in default _Layout should specify empty area

### ISSUE THREAD

**Issue by AlbertoPa** [aspnet/AspNetCore#4355]
The automatically generated _Layout.cshtml contains anchor tags without specified area. This leads to inconsistent behavior of the Home and "AppName" links in the navigation bar when the default layout is used in areas. if they have a page named "Index". In this case, the anchor links to the main home page are modified to point to the area page.

Steps to reproduce:

1. Create an empty App with Razor Pages
2. Add an area
3. Add a page called Index to the Pages subfolder of the area, using the _Layout.cshtml in /Pages/Shared
4. Navigate to the area
5. Check the "Home" link in the navigation bar. It points to localhost/AreaName/ rather than to localhost

A possible solution would be to explicitly specify asp-area="" in all anchors in /Pages/Shared/_Layout.cshtml. Identity seems to work around the issue by changing the path to the Index page, but that isn't a workable solution for areas in general.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AlbertoPa.
This is fixed already.
