### ISSUE TITLE
TempData is lost if using serviseworker preload navigationPreload.enable()

### ISSUE THREAD

**Issue by rommilg** [aspnet/AspNetCore#4359]
TempData is lost if using serviceworker preload
makes two hits on index.cshtml 
but TempData is null on both
i use session instead 
    
    async function () {
                // Feature-detect
                if (self.registration.navigationPreload) {
                    // Enable navigation preloads!
                    await self.registration.navigationPreload.enable();
                }
            }(),

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rommilg.
It seems that the issue you're facing is a limitation in browser, which prevents the service worker to set the cookies. Using session is indeed the desired approach here.
