### ISSUE TITLE
Asp.net Core 2.1 and VueCliMiddleware 2.1

### ISSUE THREAD

**Issue by Ethan0007** [aspnet/AspNetCore#4362]
Hi,

I just want to share something on my development issue, i have asp.net core 2.1 and and using vue cli 3, I'm having issue when start debugging of the project and the issue is not consistent sometimes it work and sometimes it fails. please see screenshot below:

![image](https://user-images.githubusercontent.com/12542052/49374165-14d9a200-f733-11e8-892c-ecca2e5c05e6.png)

Thank you!

**Comment by vertonghenb** [comment]
Is Vue Supported?

**Comment by Eilon** [comment]
@SteveSandersonMS - any idea on this? Is this something we would try to support?

**Comment by SteveSandersonMS** [comment]
@Ethan0007 [VueCliMiddleware](https://www.nuget.org/packages/VueCliMiddleware) is a 3rd-party library, so I'd recommend following up with the developer of that library if there's an issue with it. If you have reason to believe there's a bug in ASP.NET Core itself, could you provide more details about what part of ASP.NET Core you think has a bug, ideally with a repro case?

I'll close this as external, but please let us know if you think this is mistaken! Thanks.
