### ISSUE TITLE
HttpContext with reverse proxy

### ISSUE THREAD

**Issue by lolpop16** [aspnet/AspNetCore#4363]
Hey guys, I have the following problem: 
I set up an apache2 server with reverse proxy for my asp.net core project. So everything works fine, expect `HttpContext.Session.SetString("username");` and  `HttpContext.Session.GetString("username");`. If i redirect from the login page to another page the string is null.  How can i fix this problem?
That's my apache2 config:
<VirtualHost *:*>
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>

<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyRequests On
    CookieTracking On
    ProxyPass / http://127.0.0.1:5000/
    ProxyPassReverse / http://127.0.0.1:5000/
    ProxyPassReverseCookiePath / /dashboard
    ErrorLog ${APACHE_LOG_DIR}helloapp-error.log
    CustomLog ${APACHE_LOG_DIR}helloapp-access.log common
</VirtualHost>

I hope someone can help me, thanks!

**Comment by Tratcher** [comment]
Are you running multiple instances behind the reverse proxy?
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-2.2

General reverse proxy guidance:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2

Also capturing a Fiddler trace to make sure the session cookie is flowing across requests.

**Comment by lolpop16** [comment]
@Tratcher I found my problem, I had to disable `options.CheckConsentNeeded = context => true;` in the Startup.cs. Thank you for your help!
