### ISSUE TITLE
Getting null values in API while using RestSharp on version 2.1.6

### ISSUE THREAD

**Issue by b1shonen** [aspnet/AspNetCore#4366]
I'm using AspNetCore v.2.1.6 as an API app and when I try to send data through RestSharp, the parameters of a method are always being received as null. This don't happen when I use a client generated with AutoRest or AspNetCore v2.0, but I need to use RestSharp because my specific request size is too long and the last version of AspNetCore available. By the way, I'm testing the petition in a console app.

Petition Code:

        static void Main(string[] args)
        {
            Console.Write("id:");
            var id = Console.ReadLine();
            Console.Write("picture:");
            var picture = Console.ReadLine();

            RestClient _restClient = new RestClient("http://localhost:1012");

            RestRequest request = new RestRequest("/api/SuperUser/UpdateProfilePicture", Method.PUT);
            request.AddParameter("id", id);
            request.AddParameter("picture", picture);           
            var res = _restClient.Execute(request);
            Console.WriteLine(res.Content);
            Console.ReadKey();
        }

API Method:

        [HttpPut]
        [Route("UpdateProfilePicture")]
        [Produces("application/json", Type = typeof(bool))]
        [SwaggerOperation(OperationId = "SuperUserUpdateProfilePicture")]
        public bool UpdateProfilePicture(Guid id, string picture)
        {
            SuperUser su = _repository.Get(id);
            if (su != null)
            {
                su.ProfilePicture = picture;
                return _repository.Edit(su); //This update the user and return a boolean.
            }
            else
            {
                return false;
            }
        }

Parameters Sent:
![console](https://user-images.githubusercontent.com/45568290/49384853-b1cc1900-f6fa-11e8-8055-895fb720e7f2.PNG)

Result:
![response](https://user-images.githubusercontent.com/45568290/49384876-bee90800-f6fa-11e8-8a73-61063c813ac2.png)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
