### ISSUE TITLE
Ensure all of the SignalR client's dependencies are available on netstandard2.0 

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4370]
In manually reviewing the list of packages we are shipping in 3.0 Preview 1, it appears we may be missing some dependencies required by the SignalR client in non-shared-framework scenarios.

**Requirements**
* Verify that all of Microsoft.AspNetCore.SignalR.Client's dependencies
  - [ ] target netstandard2.0
  - [ ] ship as packages
* Add tooling to test for this scenario automatically

Notably, it appears we need to fix the packaging for Microsoft.AspNetCore.Connections.Abstractions.

cc @davidfowl

**Comment by muratg** [comment]
Nate, https://github.com/aspnet/AspNetCore/blob/f0b4ac75c479f207b16331316034910632761e4e/src/Servers/Connections.Abstractions/src/Microsoft.AspNetCore.Connections.Abstractions.csproj#L5

Looks like it's targeting netstandard2.0. Is there an issue with packaging or something?

**Comment by natemcmaster** [comment]
There appears to be a packaging issue as a result of https://github.com/aspnet/AspNetCore/pull/4178. The client apparently needs Microsoft.AspNetCore.Connections.Abstractions, but there is not package for this in 3.0 preview 1.

**Comment by natemcmaster** [comment]
I manually fixed the list, but we should still consider adding better tooling to ensure we don't regress this.

**Comment by muratg** [comment]
@mikaelm12 feel free to sync-up with me to clarify this.

**Comment by los93sol** [comment]
I understand this is corrected now, but when can we expect it to be publicly available?  Just pushing the correct version of Microsoft.AspNetCore.Connections.Abstractions to nuget would at least allow me to manually pull it in now so I can continue testing without waiting for preview2

**Comment by BrennanConroy** [comment]
@mikaelm12 Have we manually verified that this works in preview2 now?

**Comment by mikaelm12** [comment]
I haven't tested this yet. But I verified that the missing packages are now being included in TeamCity in our list of shipping packages

**Comment by muratg** [comment]
Let's make sure we test this ASAP as preview2 window is closing pretty quickly.

**Comment by los93sol** [comment]
Was System.Tasks.Channels missed in preview2?  I'm getting the following exception when trying to start a HubConnection with .net signalr client....

System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Channels, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
      File name: 'System.Threading.Channels, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
         at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
         at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
         at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes)
         at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
         at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
         at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
         at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
         at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
         at System.Diagnostics.StackTrace.TryResolveStateMachineMethod(MethodBase& method, Type& declaringType)
         at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
         at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
         at System.Exception.GetStackTrace(Boolean needFileInfo)
         at System.Exception.get_StackTrace()
         at System.IO.FileNotFoundException.ToString()

**Comment by los93sol** [comment]
Additional info....

I have an Asp.Net Core templated project that is self contained on linux-arm and it works fine, the one that is problematic is built using the .Net Core console app template, self contained targetting linux-arm.  Both apps contain System.Threading.Channels, but it is clearly a different version of it based on the size of the file

**Comment by los93sol** [comment]
If I manually replace the System.Threading.Channels dll with the one from the Asp.Net Core project then I end up with a FileNotFoundException on System.IO.Pipelines

**Comment by muratg** [comment]
@mikaelm12 was this verified for P2?

**Comment by los93sol** [comment]
Any news?

**Comment by mikaelm12** [comment]
Hi @los93sol. It looks like some build infrastructure changes that we made to our repository might have excluded packages such at System.Threading.Channels and Microsoft.Extensions.Logging for  example that were thought to be shared framework only. We've updated this for preview 3 and are currently waiting on a .NET Core SDK preview 3 to verify the changes.

**Comment by los93sol** [comment]
Great, hopefully Preview 3 is coming sooner rather than later, rather disappointing that this was missed in Preview 1 and again in Preview 2 when it was called out with plenty of lead time.

**Comment by mikaelm12** [comment]
Sorry about that. A lot of moving pieces that need to be coordinated. Thanks for your patience.

**Comment by mikaelm12** [comment]
@los93sol You can try client and sdk builds for preview3 that I've gotten to work. They aren't official preview builds but if you want to try it out and see if things work for you
SignalR Client: https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.AspNetCore.SignalR.Client/3.0.0-preview3-19110-02
SDK : https://github.com/dotnet/core-sdk/tree/release/3.0.1xx#installers-and-binaries

**Comment by mikaelm12** [comment]
@los93sol Did you get a chance to try out those builds?

**Comment by los93sol** [comment]
Trying again now, I tried a few hours after your post, but didn't have any luck

**Comment by los93sol** [comment]
App doesn't even run with that configuration.  I'm publishing a self-contained app targetting linux-arm and getting "libhostpolicy.so: undefined symbol: __atomic_fetch_add_4"

**Comment by los93sol** [comment]
I'll just wait for the next preview, hopefully everything will be sorted in the next preview.

**Comment by anurse** [comment]
@mikaelm12 what's the status on this? We expect it to be fixed in preview4? If so, let's close it (can always be re-opened if there's still an issue!)

**Comment by mikaelm12** [comment]
It is actually fixed in preview 3. I verified it before release and we have a nightly functional test scenario for the .NET client. I also just tried it right now. Going to close this as resolved.

**Comment by los93sol** [comment]
The issue I'm having is with a project targetting netcoreapp3.0 that is created from the console app template.  The preview version of Microsoft.AspNetCore.SignalR published to nuget does not seem to be there...it is for the client, but not for the server side.  Is hosting a hub only supported now if using the web template?  If that's the case then not a big deal, but the way I am doing it used to work before the codebase was moved into the aspnetcore repository so I was assuming it was a supported workload.

**Comment by mikaelm12** [comment]
The server side components you're looking for are now contained in the `MIcrosoft.AspNetCore.App` package

**Comment by anurse** [comment]
Yeah, you need to reference the Microsoft.AspNetCore.App framework (it’s not actually a NuGet package either), the server-side packages are no more. If you use the web app template it gets everything set up for you. The easiest way to do it is to have an “Sdk=‘Microsoft.NET.Web.Sdk’” attribute on the <Project> element of your csproj.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by los93sol** [comment]
Thanks for the info, that explains the issues I was having.
