### ISSUE TITLE
Mvc.Analyzers are no longer imported in 3.0 projects

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4373]
As a part of #4061 and #3612, we removed Microsoft.AspNetCore.Mvc.Analyzers from Microsoft.AspNetCore.App since we do not plan to continue to ship AspNetCore.App as a metapackage. We should find a way to re-add these analyzers to netcoreapp3.0 projects.

**Ideas**

* Ship as a PackageReference. Projects must reference as a package
   * Add the PackageRef to templates?
   * Make the PackageRef implicit in the WebSDK?
* Or, work with the SDK team to ship analyzers in-box without a package reference.

cc @davidfowl @pranavkm @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
@danroth27, assigning this to you to define which way should we go here.

**Comment by danroth27** [comment]
I think we shoudl have a single package reference in the templates for the analyzers that we think should be enabled by default.

**Comment by pranavkm** [comment]
FYI @davidfowl

**Comment by mkArtakMSFT** [comment]
To summarize the discussion we had with @danroth27 and @glennc, we're moving forward with the following approach here:
> * Make the PackageRef implicit in the WebSDK?

**Comment by davidfowl** [comment]
Um what? why?

**Comment by DamianEdwards** [comment]
I thought we'd said we'd look to get them integrated with the SDK?

**Comment by pranavkm** [comment]
Spoke offline, here's the plan. We'll add ASP.NET Core analyzer binaries to the WebSdk and use the `Analyzer` MSBuild itemgroup to add these analyzers to the build. Like other implicitly enabled features, we'll have a property to turn these analyzers off.

**Comment by davidfowl** [comment]
Doesn’t this mean that we need these packages in cache for offline storage? It also means we need a way to turn it off and change the version? And all of other things that come when you have implicit package references.

**Comment by pranavkm** [comment]
> Doesn’t this mean that we need these packages in cache for offline storage?

There aren't packages - just binaries that ship in the SDK. Psuedo code:

```xml
<ItemGroup Condition="$(TargetFramework) &gt; 'netcoreapp3.0''">
   <Analyzer Include="analyzers/$(TargetFramework)/*.dll" />
</ItemGroup>
```

**Comment by davidfowl** [comment]
Ahhh clever. How do you turn them off?

**Comment by pranavkm** [comment]
We would do a flag - see updated psuedo code.

**Comment by pranavkm** [comment]
Some thoughts as I was working on this: when we ship `netcorepp3.1`, we want to avoid shipping two copies of the analyzers particularly if they're source equivalent. However, we do want the ability to ship new analyzers without affect existing products i.e. updating the SDK should not result in new or different warnings in your existing applications. 

One way to go about this would be to do a version detection in the analyzers i.e. look for the version of AspNetCore.App \ Mvc before lighting up a change. Using `AssemblyVersionAttribute` on one the AspNetCore assemblies should likely be sufficient to determine this.
