### ISSUE TITLE
CORS functional tests fail until npm restore is manually run

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#4381]
Error:
```
Message: FunctionalTests.Assert+ProcessAssertException : cmd /c npm test --no-color exited with 1.


> @ test C:\Development\Source\AspNetCore\src\CORS\test\FunctionalTests
> jest

'jest' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```

1. Open CORS solution
2. Build
3. Ensure `AspNetCore\src\CORS\test\FunctionalTests\node_modules` does not exist
4. Run tests
5. See error
6. Run `npm restore` in `AspNetCore\src\CORS\test\FunctionalTests`
7. Run tests again
8. Passes

### Expected behavior
I would expect the .NET logic in functional tests to handle restoring packages prior to running.

At the very least it should be documented somewhere. I didn't see any instructions.

**Comment by pranavkm** [comment]
Most of our repos require running `build /t:Restore` to install the correct shared runtime the first time around and will fail to run \ test in the absence of it. This is no different.

**Comment by JamesNK** [comment]
There is no longer a build.cmd in `AspNetCore/src/CORS`. Restoring with build.cmd located in the base of AspNetCore doesn't restore node packages. Has this been lost in the mondo move?

**Comment by natemcmaster** [comment]
Nothing has changed for CORS yet. npm restore should happen when this runs. Run 

https://github.com/aspnet/AspNetCore/blob/c487f019f51f75c0d9bd45df0590db4850661196/src/CORS/build/repo.targets#L2-L9

> There is no longer a build.cmd in AspNetCore/src/CORS.

In the meantime, `build.cmd -path src/Cors -lockfile ./korebuild-lock.txt /t:Restore`. 

FYI - @jkotalik and I are working on #4246 for CORS soon. As a part of that, I want to add a target that would run `npm install` for all NodeJS projects in our repo. Based on current thinking (https://github.com/aspnet/AspNetCore/issues/4247), you would need to run `build.cmd -nodejs -restore` before running tests in Visual Studio. Thoughts?

**Comment by JamesNK** [comment]
> Based on current thinking (#4247), you would need to run build.cmd -nodejs -restore before running tests in Visual Studio. Thoughts?

If it is documented 👍

Bonus points if there is a friendly error message telling you that you need to run that 😄

**Comment by mkArtakMSFT** [comment]
Closing this as it seems this is an effect of the state we're in in regards to our engineering systems. This will get fixed as a result of the referenced issues being resolved.
