### ISSUE TITLE
3.0 ForgotPassword regression in AzureB2C templates

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#4384]
https://github.com/aspnet/Security/pull/1887 added a new AccessDenied feature that breaks the ForgotPassword flow from 2.2.

From @Tratcher 

Ah, this was a new feature to standardize error responses: https://github.com/aspnet/Security/pull/1887

It looks like B2C used to handle this error themselves in OnRemoteFailure. This logic would need to move to the new OnAccessDenied event.

https://github.com/aspnet/AspNetCore/blob/c7d63649005c4c2863b34794994eef57595e7bb7/src/AADIntegration/src/Microsoft.AspNetCore.Authentication.AzureADB2C.UI/AzureAdB2COpenIDConnectEventHandlers.cs#L68

**Comment by Tratcher** [comment]
Ah, I see the problem. It was that PR but not for the reason I thought. Before the PR the exception was an OIDCException and AAD checked both the type and for a specific message, but after it’s this generic error instead. The new feature tried to be non-breaking by checking context.AccessDeniedPath.HasValue before doing the new event and redirect, but not before diverting off to the new shared method that has the different error message.

We could fix this in Authentication by checking for the presence of AccessDeniedPath before taking the new code path.
