### ISSUE TITLE
[SignalR/Java] JCenter version information not synchronized with Maven Central

### ISSUE THREAD

**Issue by ncthbrt** [aspnet/AspNetCore#4387]
A version of SignalR appears as a listing on [Bintray's JCenter](https://bintray.com/bintray/jcenter/com.microsoft.signalr%3Asignalr/1.0.0-preview3-35501). However it is very out of date and missing some important fixes. The latest version that appears there is `v1.0.0-preview3-35501`

I do realise that I can just pull from central, but it was quite misleading seeing the package present in JCenter (I actually set up a private CD pipeline to publish Signal R to our maven before I realised it was in central).  It would probably be a good idea to either pull the listing, or ensure it's synchronized with Maven Central.

**Comment by BrennanConroy** [comment]
I believe jcenter automatically mirrors Maven Central, you just need to be patient. We only pushed to Maven a few hours ago.

**Comment by mikaelm12** [comment]
Yeah, like Brennan said, jCenter should mirror Maven Central, I guess it just takes a little longer to index the new items. It should be there soon.

**Comment by ncthbrt** [comment]
Oh apologies. I was struggling to see when this version was published.
Didn't realize it was yesterday.

**Comment by ncthbrt** [comment]
It appears that the package information still hasn't updated

**Comment by mikaelm12** [comment]
I'll take a look

**Comment by BrennanConroy** [comment]
JCenter has the package now https://bintray.com/bintray/jcenter/com.microsoft.signalr%3Asignalr/1.0.0

**Comment by mikaelm12** [comment]
So I guess for future reference this takes about a month to update? Kind of unfortunate.

**Comment by ncthbrt** [comment]
It's instant if you do it the other way around (use bintray jcenter to publish to maven central)

**Comment by mikaelm12** [comment]
>Otherwise a note or something explaining the situation might be helpful

Will do. The fist time we checked Jcenter for one of our preview releases it had already been mirrored so we didn't know exactly how long it took. Now we have a much better idea.

**Comment by ncthbrt** [comment]
Thanks a lot @mikaelm12 
Offtopic: very glad the android lib is getting some TLC.

**Comment by mikaelm12** [comment]
Glad you're enjoying the Java client @ncthbrt! 😄
