### ISSUE TITLE
When returning 205 it works with IISExpress, but takes 2 minutes with commandName": "Project"

### ISSUE THREAD

**Issue by fuzzy-afterlife** [aspnet/AspNetCore#4388]
When returning a 205 from an Api with return StatusCode(205); the Api hangs when using it from the cli, but works fine when using IISExpress. It works for the CLI when you change it to StatusCode(205, null).

To reproduce is very simple.
1. Create a new Api in VS 2017
2. Change the ValuesController to 
    [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            //return new string[] { "value1", "value2" };
            return StatusCode(205);
        }
3. Launch it via IISExpress and call the end point, it will respond normally, as expected.
4. Launch it via the CLI, either by launching WebApplication1 in VS, or dotnet run. It will take up to 2 minutes to respond.
5. Change return StatusCode(205); to return StatusCode(205, null); and repeat step 4, it will now work as normal

**Comment by Tratcher** [comment]
@halter73

**Comment by halter73** [comment]
This is caused because Kestrel won't automatically set a `Content-Length: 0` response header for 205 responses. This is apparently acceptable/expected for 204/304 responses and HEAD requests, but not for 205 responses.

Semi-related: #4382

**Comment by halter73** [comment]
@fuzzy-afterlife `return StatusCode(205, null);` works around this issue because it explicitly sends an empty response body. Alternatively you could work around this by including `HttpContext.Response.ContentLength = 0;` in your action method.

**Comment by fuzzy-afterlife** [comment]
@halter73 Thank you very much for the information, it explains it perfectly. I guess for now we will just stick with the return StatusCode(205, null);
