### ISSUE TITLE
Need to check HubConnectionState for calls to Invoke

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#4393]
Before calling methods that require the HubConnection to be connected we run a simple connection state check like 
https://github.com/aspnet/AspNetCore/blob/e310ccac7b30e901f657f81c86c4048fecfedf7b/src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java#L464-L466

We don't have this check for the `invoke` method.

**Comment by mikaelm12** [comment]
This was approved for the 2.2.2 patch

**Comment by natemcmaster** [comment]
Tentatively, later this week. I'll send email to the team when the branch opens up.

**Comment by mikaelm12** [comment]
Merged into 2.2.2 and master now 
https://github.com/aspnet/AspNetCore/pull/4400
