### ISSUE TITLE
ParameterAttribute Inherited = true

### ISSUE THREAD

**Issue by nenaaki** [aspnet/AspNetCore#4412]
Can 'Inherited' of ParameterAttribute be set to 'true'?
It is useful to be able to use parameters with inherited classes.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nenaaki.

**Comment by mkArtakMSFT** [comment]
@nenaaki, feel free to send a PR for this.

**Comment by mkArtakMSFT** [comment]
Closing as done.
