### ISSUE TITLE
Endpoint Routing does not allow for subdomain constraints

### ISSUE THREAD

**Issue by mscrivo** [aspnet/AspNetCore#4414]
### Describe the bug
In our asp.net core 2.1 app, we were making use of an `IRouteConstraint` implementation that looked at the host in the request to match it against a subdomain, in combination with Areas to achieve separation of what is essentially 2 (or more) apps.  Perhaps it would be better to separate these projects completely since they don't really share any concerns, but I digress.  The solution we had was pretty much what's shown here: https://stackoverflow.com/questions/49378474/different-domain-in-the-same-app-asp-net-core-2-0
When upgrading to 2.2 and setting the compat flag to 2.2, the subdomain constraints no longer work.  Disabling Endpoint Routing makes it work it again.

### To Reproduce
1. Using ASP.NET Core 2.2 with Endpoint Routing Enabled
2. Setup routes with different Subdomain constraints as in SO link above
3. Observe that routes that are supposed to be restricted to a certain subdomain are actually available regardless of subdomain.

### Expected behavior
I understand Endpoint Routing is a big change, I'm just wondering if there is a way to do this with Endpoint Routing enabled, or if I should just separate these apps.

**Comment by mscrivo** [comment]
Yeah the constraint still gets called, and I can step through it without any exceptions, but it just appears to not work in the same way.

Here's one such route that I had restricted to the subdomains `public` and `spotlight`:
```
builder.MapRoute(
    "spotlight",
    "",
    new { area = "Spotlight", controller = "Spotlight", action = "Index" },
    new { _ = new SubdomainConstraint("public", "spotlight") }
);
```
at the bottom, we had our default route configured:

```
builder.MapRoute(
    "Default",
    "{controller}/{action}/{id?}",
    new { controller = "Home", action = "Index" }
);
```

There is a third sudomain called `app`.  In 2.1, the Spotlight route could only be reached by hitting either `public.domain.com` or `spotlight.domain.com`, but not `app.domain.com`.  `app.domain.com` would fallback to the default route config.  Now, in 2.2, all 3 variants resolve to the Spotlight route.

**Comment by JamesNK** [comment]
Hi @mscrivo 

I believe this issues is the same as #4591. There is detail in that issue about potential workarounds. I'm closing this one as a duplicate.

**Comment by weitzhandler** [comment]
Related: #10574.

In my scenario, the subdomain information is stored in a database and needs to be retrieved by one of the registered services.
