### ISSUE TITLE
Resolve root cause of `DefaultApplicationModelProviderTest` test failures

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#4417]
### Describe the bug
The following Mvc tests have been failing for about a week:
```
Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProviderTest.CreateActionModel_RouteOnController_CreatesOneActionInfoPerRouteTemplateOnAction(controller: typeof(Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProviderTest+MultipleRouteAttributeController))
Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProviderTest.CreateActionModel_RouteOnController_CreatesOneActionInfoPerRouteTemplateOnAction(controller: typeof(Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProviderTest+SingleRouteAttributeController))
```
I'm going to skip the test method (has only these two cases) in #4415 to resolve all four test failures in src/Mvc.

### To Reproduce
1. checkout `master` branch in this repo or 3cfa6c0526 commit
  - use commit once #4415 is in `master`
2. `cd src/Mvc`
3. `./build.sh` or `.\build.cmd`

#### Expected behavior
Clean build
#### Actual
The two test failures listed above. (Well, see two more failures already fixed in #4415.)
### Additional context
Root cause seems to be a behaviour change in CoreFx. The failing assertion checks whether two `[HttpGet]` attributes on an action are both found. This used to work and no longer does.

`dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009750
 Commit:    84dcc2bfd8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\dougbu\.dotnet\x64\sdk\3.0.100-preview-009750\

Host (useful for support):
  Version: 3.0.0-preview1-27029-03
  Commit:  631e219c26
...
Microsoft.AspNetCore.All 3.0.0-alpha1-10663 [C:\Users\dougbu\.dotnet\x64\shared\Microsoft.AspNetCore.All]
...
Microsoft.AspNetCore.App 3.0.0-alpha1-10663 [C:\Users\dougbu\.dotnet\x64\shared\Microsoft.AspNetCore.App]
...
Microsoft.DesktopUI.App 3.0.0-alpha-27113-1 [C:\Users\dougbu\.dotnet\x64\shared\Microsoft.DesktopUI.App]
...
Microsoft.NETCore.App 3.0.0-preview1-27029-03 [C:\Users\dougbu\.dotnet\x64\shared\Microsoft.NETCore.App]
```

Using KoreBuild `3.0.0-build-20181120.4`

**Comment by dougbu** [comment]
Test method skipped in commit 6a8d7dc12c

**Comment by mkArtakMSFT** [comment]
@dougbu, assigning this to you as you've done a lot of investigation already here. Handle it when you'll be back.

**Comment by pranavkm** [comment]
Filed CoreFx issue: https://github.com/dotnet/corefx/issues/37261
