### ISSUE TITLE
Is there a way to get hierarchical values on Azure Portal from Application Settings?

### ISSUE THREAD

**Issue by ozkank** [aspnet/AspNetCore#4419]
I want to get some connection string secret value from **Application settings** or **Connection Strings** tab on Azure App Service Portal. 
I don't want to use File Configuration Provider and store the connection string on source control.

I cannot use KeyVault service on slots from some reasons. I know that for this on AzureKeyVault service we can able to use two dashes(--)
Is there a way?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
