### ISSUE TITLE
ASP.NET Core 3.0 Preview SDK not available in Visual Studio dropdown when creating new 3.0 project

### ISSUE THREAD

**Issue by adrian109** [aspnet/AspNetCore#4420]
Hi,

I have just installed the latest production and preview SDKs:
.NET Core 2.2
.NET Core 3.0.0-preview-27122-01

Along side those I have also installed Visual Studio 2019 Preview 1.

I went to create my first ASP.NET Core 3.0 Razor Pages project using Visual Studio 2019 Preview 1.

In the project creation dialog I was expecting to be able to choose ASP.NET Core 3.0 from the dropdown of available ASP.NET Core frameworks, but the only option in the dropdown is ASP.NET Core 2.2 as shown below:
![image](https://user-images.githubusercontent.com/16767194/49504496-b109c300-f871-11e8-82b5-6c7e4c75f5e6.png)

Is this a bug, or do I have to target using the ASP.NET Core 3.0 framework using a `global.json` file ?

**Comment by mdh2g2** [comment]
I have the same question.  Did you find the answer anywhere else?

**Comment by adrian109** [comment]
It just seemed to appear one day and started working.  Not sure if it appeared before or after I upgraded to: [Visual Studio 2019 Preview 1.1 Servicing Update](https://docs.microsoft.com/en-gb/visualstudio/releases/2019/release-notes-preview#VS2019_Preview1.1)

**Comment by cetindogu** [comment]
same stiation. jsut aspnet core 2.1 exists in the dropdown.  this is a bug ????
