### ISSUE TITLE
Generic Host and Entity Framework Logging Configuration

### ISSUE THREAD

**Issue by zanate4019** [aspnet/AspNetCore#4426]
I'm not sure if this is the proper place to log the issue...

I'm using the generic host builder to construct a host for my local service. Logging is configured with a logging level of Error across the board. This is working except in EF Core which is still logging at the info level. I suspect that EF is using a separate logger. Is there something different I need to do to tell EF to use the same log configuration as the rest of the application. Below is the code for my host:

```
        public static async Task Main(string[] args)
        {
            var host = new HostBuilder()
                .ConfigureHostConfiguration(configHost =>
                {
                    configHost.SetBasePath(Directory.GetCurrentDirectory());
                    configHost.AddJsonFile("hostsettings.json", optional: true);
                    configHost.AddEnvironmentVariables(prefix: "PREFIX_");
                    configHost.AddCommandLine(args);
                })
                .ConfigureAppConfiguration((hostContext, configApp) =>
                {
                    configApp.AddJsonFile("appsettings.json", optional: true);
                    configApp.AddJsonFile(
                        $"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json",
                        optional: true);
                    configApp.AddCommandLine(args);
                })
                .ConfigureServices((hostContext, services) =>
                {
                    // register ABS data context
                    var configuration = hostContext.Configuration;
                    services.AddDbContext<AbsContext>(options =>
                    {
                        options.UseSqlServer(configuration.GetConnectionString("AbsConnection"));
                    });
                   
        <--- omitted for brevity --->

                    // register hosted applications
                    services.AddHostedService<ProviderUpdateService>();
                })
                .ConfigureLogging((hostContext, configLogging) =>
                {
                    configLogging.AddConsole();
                    configLogging.AddDebug();
                    configLogging.AddEventLog();
                })
                .Build();

            await host.StartAsync();
            await host.StopAsync();
            host.Dispose();

        }
```
Here is the logging level configuration from both of my appsettings.json files:
```
{
  "Logging": {
    "LogLevel": {
      "ARA":  "Information",
      "Default": "Error",
      "System": "Error",
      "Microsoft": "Error"
    }
  }
}
```
Finally here is what is getting logged.  Notice ARA is logging at info level like it should, but EF is also logging at info when it should be logging at error:
![image](https://user-images.githubusercontent.com/10452739/49532735-d2bf7600-f882-11e8-9f05-7572027c8000.png)

**Comment by dallancarr** [comment]
Firstly, make sure the appsettings are being picked up.

But if you want to test log levels pass these settings into `AddConsole`

`            var settings = new ConsoleLoggerSettings();
            settings.Switches.Add("Microsoft", LogLevel.Error);
            settings.Switches.Add("Default", LogLevel.Information);`

**Comment by zanate4019** [comment]
@dallancarr Thanks.  I have been able to verify that my appsettings are being picked up.  I'll try your suggesting about configuring within the AddConsole() call to see if the behavior is the same..

**Comment by zanate4019** [comment]
Found it...

needed to add
`            builder.AddConfiguration(context.Configuration.GetSection("Logging"));`
to my ConfigureLog() call.

Looks like the sample project for Generic Host needs it too...

**Comment by dallancarr** [comment]
There is the culprit

https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging/LoggingServiceCollectionExtensions.cs#L45
