### ISSUE TITLE
AspNetCore-Tooling build includes unsigned binaries in the VS For Mac payload

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4429]
This is a new issue as part of the onboarding to arcade. We probably need to author some custom logic during the signing phase to unzip the MPack, sign the binaries and repack it.

I found this as part of a verification pass that the artifacts produced by our build are signed. Packages and VSIX are appropriately signed 👍

**Comment by natemcmaster** [comment]
SignTool should support MPack files. My guess is that the Arcade SDK may not include them by default in the items it passes to sign tool.

cref https://github.com/dotnet/arcade/pull/1283

**Comment by rynowak** [comment]
That's cool. It sounds like the work then is to make the mpack visible to arcade somehow then. I totally forged my own path for producing an MPack from the build.

**Comment by rynowak** [comment]
Fixed aspnet/AspNetCore-Tooling@d370cdb7bc4229ae759e2e28d91520f386ddc289
