### ISSUE TITLE
addTagHelper in _ViewStart for ViewComponent not respected

### ISSUE THREAD

**Issue by kswoll** [aspnet/AspNetCore#4434]
### Describe the bug
When calling `addTagHelper` in `_ViewStart.cshtml` tag helpers for ViewComponents do not work.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Create a new web application and add a view component per the docs (https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2) -- I named it `CopyrightViewComponent`
3. Register the the tag helper in `_ViewStart.cshtml` via `addTagHelper`:  `@addTagHelper *, WebApplication1`
4. Consume it via:

```
<vc:copyright></vc:copyright>
```

5. View component doesn't render (just the raw `<vc:copyright></vc:copyright>` directly in the outputted html)

### Expected behavior
For the view component to render.

### Workaround
Register the tag helper in each razor page consuming the view component -- move the `addTagHelper` into `Index.cshtml` away from `_ViewStart.cshtml`.  While this workaround works, it is tedious as you have to remember to do this for every page that consumes it.  In contrast, tag helpers do respect it being registered in `_ViewStart.cshtml`

**Comment by NTaylorMullen** [comment]
@kswoll if you `@addTagHelper` in `_ViewImports.cshtml` things work as expected. `_ViewStart.cshtml` files only support having C# code (not directives)

**Comment by kswoll** [comment]
@NTaylorMullen ah, thank you!  I was misguided from some stackoverflow posts I saw (and evidently didn't pay enough attention to the difference between those two files).  Bug verified you're right and it's working fine.  Thanks again!
