### ISSUE TITLE
Intermittent errors from ASP.NET Core 2.2.0 application

### ISSUE THREAD

**Issue by martincostello** [aspnet/AspNetCore#4437]
Raised as possibly related to #4398.

Intermittently when running the test suite for an existing ASP.NET Core 2.1.6 application that has been ported to ASP.NET Core 2.2.0 with in-process IIS hosting, requests fail. Both applications are hosted on Amazon EC2 instances running Windows Server Core 2012 R2.

The specific requests that fail are HTTP GET requests from an ASP.NET 4.6.1 application that acts as a proxy for the ASP.NET Core application.

Requests are made as standard HTTP 1.1 using `HttpClient`, rather than with HTTP/2 (at least, not explicitly).

The flow of the tests are as following:

  1. Perform an HTTP GET for an entity, which returns an HTTP 200.
  1. Perform an HTTP POST against the entity, which returns an HTTP 204.
  1. Re-perform the same HTTP GET to validate the HTTP POST took effect by inspecting the response.

When the request to validate the POST is made within the ASP.NET 4.6.1 proxy application, the following exception occurs:

```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Refit.RequestBuilderImplementation`1.<>c__DisplayClass13_0`1.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
  <snipped application stack trace>
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Refit.RequestBuilderImplementation`1.<>c__DisplayClass13_0`1.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext()<---
```

Requests _directly_ to the ASP.NET Core 2.2.0 application from the tests (which are in the same code base and are .NET Core 2.2.0 also) do not exhibit this behaviour and behave as expected, i.e. they pass.

It appears that _something_ is behaving differently in the server's responses that is causing the ASP.NET application to reject the responses to the requests, as this behaviour has never been observed before in this test suite with previous versions of ASP.NET Core.

At this time due to the size and nature of the two applications involved, I cannot provide a simple repro.

Upon changing the web.config file of the ASP.NET Core application to use out-of-process hosting, the tests no longer fail.

For reference, this is the web.config of the application when deployed to the server:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <httpProtocol>
      <customHeaders>
        <remove name="X-Powered-By" />
      </customHeaders>
    </httpProtocol>
    <urlCompression doDynamicCompression="true" doStaticCompression="true" />
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\Application.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
  </system.webServer>
</configuration>
```

**Comment by jkotalik** [comment]
This actually may be the same issue in #4398 

Few things I would check:
- I think the ASP.NET 461 application is probably using a WinHttpClientHandler underneath the HttpClient which will upgrade requests to HTTP/2 if available. If you can, check the first GET HttpResponse and see if is HTTP/2.
- Add the recommended workaround to your app and see if that fixes your problem.

**Comment by martincostello** [comment]
As it's easier in my particular setup, as a first step I'll try adding the workaround now and see what happens.

**Comment by martincostello** [comment]
I just checked our IIS logs and there's no references to HTTP/2 there. All the requests to the ASP.NET Core application are listed as `HTTP/1.1` for `cs-version`.

**Comment by martincostello** [comment]
If it helps and/or is relevant, the ASP.NET 4.6.1 application uses `ServicePointManager.FindServicePoint()` to specify a `ConnectionLeaseTimeout` value, and sets `ConnectionClose = false` on the `HttpClient`'s `DefaultRequestHeaders` property.

Just thought I'd mention it in case that might contribute to the intermittent nature of the issue from my observations.

**Comment by jkotalik** [comment]
I don't think `ServicePointManager.FindServicePoint()` is relevant.

Try the workaround for now and see if you continue getting failures. If the issue is fixed, this issue may affect HTTP/1.1 too.

**Comment by martincostello** [comment]
Cool - I'll try that tomorrow and see how I get on.

**Comment by martincostello** [comment]
Having applied the middleware workaround from #4398 to our application and re-running the tests multiple times, the ASP.NET 4.6.1 application is no longer throwing the exceptions when In-Process hosting is enabled.

That would seem to suggest that this is another manifestation of the same bug and isn't specific to HTTP/2.

**Comment by muratg** [comment]
We're patching this (#4398).
