### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Api.Analyzers not respecting XML comments.

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/AspNetCore#4439]
### Describe the bug

When I first installed `Microsoft.AspNetCore.Mvc.Api.Analyzers` I got a ton of: 

> Action method returns undeclared status code '404'.

After clicking on them, they went away. Swashbuckle supports a nonstandard XML comment `<response ...` [as seen here.](https://github.com/domaindrivendev/Swashbuckle#response-codes). Is this supported?

It also has an attribute for [`[SwaggerResponse(404...`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#enrich-response-metadata) is this support in lieu of `[ProducesResponseType]`? I assume so since [it inherits from `ProducesResponseTypeAttribute`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Annotations/SwaggerResponseAttribute.cs). But i didn't see any of this information in the announcement [here](https://blogs.msdn.microsoft.com/webdev/2018/08/23/asp-net-core-2-20-preview1-open-api-analyzers-conventions/).

Are we locked into using `[ProducesResponseType]` and/or `[SwaggerResponse]`?

### To Reproduce

```csharp
/// <summary>
/// Gets a single Product.
/// </summary>
/// <param name="productId">The requested Product identifier.</param>
/// <returns>The requested Product.</returns>
/// <response code="200">The Product was successfully retrieved.</response>
/// <response code="404">The Product does not exist.</response>
[HttpGet("{productId}", Name = ITILLifecycleControllerRoute.GetProduct)]
[HttpHead("{productId}", Name = ITILLifecycleControllerRoute.HeadProduct)]
public async Task<ActionResult<ProductViewModel>> Get(int productId)
{
    var product = await _genericGetters.GetByIdAsync(productId);

    if (product == null)
    {
        return NotFound();
    }

    return product;
}
```

### Expected behavior

If `/// <response ...`  XML tags are used to state we return a 404, then the `Microsoft.AspNetCore.Mvc.Api.Analyzers` should not complain about it because this is official supported by Swashbuckle and the correct Swagger doc will in fact be generated. Just as it would by using `[SwaggerResponse]` and `[ProducesResponseType]`.

### Screenshots

![image](https://user-images.githubusercontent.com/2934507/49542206-8da73e00-f89a-11e8-9518-f00d411e964f.png)

### Additional context

To see why I want this, it might be helpful to see this discussion I had with @domaindrivendev https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/816#issuecomment-405442154

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @VictorioBerra.
@glennc, is this something we should consider adding support for?

**Comment by mkArtakMSFT** [comment]
This is not something we plan to provide support for. We rely on attributes to produce the expected responses.

**Comment by VictorioBerra** [comment]
This deeply saddens me.
