### ISSUE TITLE
Is there more information about the endpoint routing?

### ISSUE THREAD

**Issue by stulzq** [aspnet/AspNetCore#4456]
I am very happy that asp.net core 2.2 is officially released.I noticed a new feature ‘Endpoing Routing’, I read the blog https://blogs.msdn.microsoft.com/webdev/2018/08/27/asp-net-core-2-2-0-preview1-endpoint-routing/ . Where is there more information about endpoint routing?.Thanks.

**Comment by rynowak** [comment]
The routing docs have been updated and call out differences where they are relevant https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2

**Comment by stulzq** [comment]
Thanks
