### ISSUE TITLE
Endpoint Routing - IActionConstraint

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/AspNetCore#4461]
According to https://blogs.msdn.microsoft.com/webdev/2018/08/27/asp-net-core-2-2-0-preview1-endpoint-routing/ we should open issues regarding our usage of ``IActionConstraint`` here. 
So this is neither a bug nor a feature request, but just for documentation purposes.

In one of the applications I maintain we use a concept similar to the system described in http://byterot.blogspot.com/2012/12/5-levels-of-media-type-rest-csds.html
The interesting part is the table at the end.
We offer the possibility to supply additional tokens in the Accept-Header and/or Content-Type header (depending on http method) and we use ``IActionConstraint`` to check for these tokens (specifically version and some model tokens) and route to the appropriate actions.

**Comment by Tornhoof** [comment]
I ported my ``IActionConstraint`` to EndpoitnRouting and MatcherType, yes I know that it's not really for public consumption yet, but I didn't run into any serious issues. My code looks like this, it handles the mentioned model token (domain-model in this case). The specific tokens are in a custom RouteAttribute called ``ExtendedMediaTypeRouteAttribute``.

```csharp
public class ExtendedMediaTypeRouteMatcher : MatcherPolicy, IEndpointSelectorPolicy
{
    public override int Order => 100;

    public bool AppliesToEndpoints(IReadOnlyList<Endpoint> endpoints)
    {
        if (endpoints == null)
        {
            throw new ArgumentNullException(nameof(endpoints));
        }
        for (var i = 0; i < endpoints.Count; i++)
        {
            var endpoint = endpoints[i];
            var md = endpoint.Metadata.GetMetadata<ExtendedMediaTypeRouteAttribute>();
            if (md != null)
            {
                return true;
            }
        }

        return false;
    }

    public Task ApplyAsync(HttpContext httpContext, EndpointSelectorContext context, CandidateSet candidates)
    {
        var typedHeaders = httpContext.Request.GetTypedHeaders();
        var domainModel = httpContext.Request.Method == HttpMethods.Get
            ? ParseAcceptHeader(typedHeaders.Accept)
            : ParseMediaTypeHeaderValue(typedHeaders.ContentType);
        for (int i = 0; i < candidates.Count; i++)
        {
            var md = candidates[i].Endpoint.Metadata.GetMetadata<ExtendedMediaTypeRouteAttribute>();
            if (domainModel == null && md == null)
            {
                candidates.SetValidity(i, true);
            }
            else if (domainModel != null && md != null &&
                     domainModel.Equals(md.DomainModel, StringComparison.OrdinalIgnoreCase))
            {
                candidates.SetValidity(i, true);
            }
            else
            {
                candidates.SetValidity(i, false);
            }
        }

        return Task.CompletedTask;
    }

    private static StringSegment ParseMediaTypeHeaderValue(MediaTypeHeaderValue headerValue)
    {
        if (headerValue != null)
        {
            foreach (var parameter in headerValue.Parameters)
            {
                if (parameter.Name.Equals(ExtendedMediaTypeValues.DomainModel, StringComparison.OrdinalIgnoreCase))
                {
                    return parameter.Value;
                }
            }
        }

        return null;
    }

    private static StringSegment ParseAcceptHeader(IList<MediaTypeHeaderValue> accept)
    {
        if (accept != null)
        {
            foreach (var mediaTypeHeaderValue in accept)
            {
                var result = ParseMediaTypeHeaderValue(mediaTypeHeaderValue);
                if (result != null)
                {
                    return result;
                }
            }
        }

        return null;
    }
}
```

**Comment by rynowak** [comment]
Thanks for posting this @Tornhoof - is this working out the way you expect? 

As a general question - is what you're doing here similar to `[Produces(...)]` but with an effect on action selection?

This code looks roughly like what I would expect to see for this.

**Comment by Tornhoof** [comment]
I never deployed my code snippet above to production, I still use the normal ``IActionConstraint``, simply because the old code works and then was christmas and there was no real need to use it. I only ran my tests and a few short benchmarks and didn't see any problems.

As for the question:
Yes, for the query side via ``Accept Header`` it's basically ``[Produces]`` with action selection, the API User sends the model type he expects/wants and the code above routes it to individual controller methods.
This allows customer specific rest api extensions without having a multitude of visible endpoints.
```csharp
// simplified
[HttpGet]
[Produces(typeof(Model)]
public async Task<ActionResult<Model>> Get(Guid id);

[ExtendedMediaTypeRoute(typeof(ModelForCustomerA)]
[Produces(typeof(ModelForCustomerA)]
public async Task<ActionResult<ModelForCustomerA>> Get(Guid id);
```
Simply said all the URLs look like  /api/ValueController/:id and not /api/ValueController/ModelForCustomerA/:id etc. 
CustomerB might react a bit suprised if he suddenly has an endpoint in his OpenAPI spec which references CustomerA.
The command side via ``Content-Type Header``  is pretty much the same, only that the change is not the response type, but the model bind parameter type to the controller action.
```csharp
// simplified
[HttpPost]
public async Task<ActionResult> Post(Guid id, Model model);

[ExtendedMediaTypeRoute(typeof(ModelForCustomerA)]
public async Task<ActionResult> Post(Guid id, ModelForCustomerA model);
```

The main difference I think I saw while developing is, that the code above needs fewer "tries" than ``IActionConstraint``, with ``IActionConstraint`` you can see how the router matches the constraint against each candidate with the same route template  until the specific constraint is matched. It looked like the new matcherpolicy is more precalculated so it did less comparisons, but this might just have been a different runtime behaviour.

**Comment by rynowak** [comment]
> The main difference I think I saw while developing is, that the code above needs fewer "tries" than IActionConstraint, with IActionConstraint you can see how the router matches the constraint against each candidate with the same route template until the specific constraint is matched. It looked like the new matcherpolicy is more precalculated so it did less comparisons, but this might just have been a different runtime behaviour.

Yeah, this is definitely intentional. My learning is that policies that select an action are usually collaborative in nature: they have a priority system intrinsic to the domain. Real-world stuff based on `IActionConstraint` can get really really complex: https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/OverloadActionConstraint.cs

I'm going to close this issue since I think we've discussed everything there is to discuss. As always thanks for your feedback :)
