### ISSUE TITLE
RedirectRoute and map route default values issue with AspNetCore 2.2

### ISSUE THREAD

**Issue by jpiquot** [aspnet/AspNetCore#4462]
### Describe the bug
When a default value is defined for a parameter in the route map, the values defined in redirect methods are ignored.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Run this code : 
`RedirectToRoute(new { action = nameof(Details), id=10 });
`
Or
`RedirectToAction(nameof(Details), new {id=10 });
`
With route defined like this:
```
routes.MapAreaRoute(
                   name: entityName,
                   areaName: _moduleName,
                   template: "App/" + _route + "/{controller}/{action}/{id?}",
                   defaults: new { action = "Index", id="" },
                   constraints: new { controller = entityName }
               );
```
Controller action is : 
 `      public virtual Task<IActionResult> Details(int id)
 `

When I use this code with AspNetCore 2.1 everything works. But with 2.2, the action is called with id = 0.

If I remove the id in the map route definition, everything works:
```
routes.MapAreaRoute(
                   name: entityName,
                   areaName: _moduleName,
                   template: "App/" + _route + "/{controller}/{action}/{id?}",
                   defaults: new { action = "Index"},
                   constraints: new { controller = entityName }
               );
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jpiquot.
@JamesNK, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
