### ISSUE TITLE
Reference to type 'IUserTwoFactorStore<>' claims it is defined in 'Microsoft.AspNetCore.Identity', but it could not be found

### ISSUE THREAD

**Issue by ngohungphuc** [aspnet/AspNetCore#4464]
### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Expected behavior
I'm using ASP.Net Core Identity with MongoDB and I get error of reference of IUserTwoFactorStore
### Screenshots

![devenv_2018-12-06_22-23-22](https://user-images.githubusercontent.com/13591213/49593195-920c4d80-f9a5-11e8-9d64-ea0dfff94ec1.png)

### Additional context
Include the output of `dotnet --info`

My package version
```
    <PackageReference Include="IdentityServer4" Version="2.3.2" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.MongoDB" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="2.1.6" />
    <PackageReference Include="MongoDB.Driver" Version="2.7.2" />
```

**Comment by blowdart** [comment]
@HaoK
