### ISSUE TITLE
Cannot generate routes that are defined but not implemented in ASP.NET Core 2.2.0 compared to 2.1.x

### ISSUE THREAD

**Issue by martincostello** [aspnet/AspNetCore#4468]
### Describe the bug

In ASP.NET Core 2.1.x, it was possible to define routes without having to implement handlers for them and then use `IUrlHelper` to build URLs for these routes in the application.

This was useful for microservice scenarios where multiple applications are deployed behind a load balancer for the same domain name and could generate URLs for other applications. For example, you could use them for `Location` HTTP response headers and other HATEOS/HAL-style scenarios where links to other resources servied by other applications are contained in the response.

In ASP.NET Core 2.2.0, attempts to build such routes using `IUrlHelper` just return `null`.

The previous behaviour can be restored by setting `MvcOptions.EnableEndpointRouting` to `false`.

### To Reproduce

```csharp
public void Configure(IApplicationBuilder app)
{
    app.UseMvc(
        (routes) =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");

            routes.MapRoute("foo", "/foo/foo");
            routes.MapRoute("bar", "/bar/bar/{id}");
        });
}

public IActionResult Index()
{
    var data =  new
    {
        foo = urlHelper.RouteUrl("foo", new { page = 1 }),    // Actual: null; Expected: "/foo/foo?page=1"
        bar = urlHelper.RouteUrl("bar", new { id = "myId" }), // Actual: null; Expected: "/bar/bar/myId"
    };

    return Ok(data);
}
```

### Expected behavior

Routes can be defined and built with `IUrlHelper` or `LinkGenerator`, even if they do not map to an MVC action.

**Comment by JamesNK** [comment]
Hi @martincostello 

I've looked into this and your problem comes from a change in how routing now works. In old routing (pre 2.2) a route could be created for an action that doesn't exist. This is what you're doing here:

```cs
routes.MapRoute("foo", "/foo/foo");
routes.MapRoute("bar", "/bar/bar/{id}");
```

In 2.2 there is no public API to achieve what you want. I recommend you disable endpoint routing with `MvcOptions.EnableEndpointRouting = false` in your `Startup.cs`.

In 3.0 you can add an endpoint that is just for link generation. This is what the code (currently) looks like in `Startup.cs`:

```cs
routes.Map("/foo/foo", context => Task.CompletedTask, new SuppressMatchingMetadata(), new RouteNameMetadata("foo"));
routes.Map("/bar/bar/{id}", context => Task.CompletedTask, new SuppressMatchingMetadata(), new RouteNameMetadata("bar"));
```

We have the pattern, an action that does nothing, metadata to tell the matcher to not match this pattern (the link generator will still use it), and the route name.

Now your code returns JSON with the routes you want:

```
{
    "foo": "/foo/foo?page=1",
    "bar": "/bar/bar/myId"
}
```

Let me know what you think of this. 3.0 is under development so there is time for changes.

**Comment by martincostello** [comment]
@JamesNK Thanks for looking into this. If this happened to be more of a quirk of the old implementation, rather than being by design, then I guess it's not the end of the world.

I've already implemented a "fake" controller to provide the equivalent functionality when endpoint routing is enabled with 2.2.

I wonder, is there enough of use case to make a built-in extension method to support the scenario using the code you've suggested but in a less verbose way?

For example something like this (horrible name, just illustrative):

```csharp
public static IEndpointConventionBuilder MapForLinkGeneration(
    this IEndpointRouteBuilder routeBuilder,
    string routeName,
    string url)
{
    return routes.Map(
        url,
        context => Task.CompletedTask,
        new SuppressMatchingMetadata(),
        new RouteNameMetadata(routeName));
}

routes.MapForLinkGeneration("foo", "/foo/foo");
routes.MapForLinkGeneration("bar", "/bar/bar/{id}");
```

**Comment by martincostello** [comment]
@JamesNK Any thoughts on the above?

**Comment by BBGONE** [comment]
Consider generating URLs for a SignalR, which does not have a controller.

```
routes.MapRoute(
name: "signalr",
template: "{action}");
```

It has workarounds , but why to complicate the things without a reason?

**Comment by JamesNK** [comment]
> @JamesNK Any thoughts on the above?

I think it is something we could do in the future. It is not difficult to add an extension method. For now I think we should wait to see if there is demand for it.

@BBGONE SignalR hubs will use endpoint routing in 3.0. I'm not sure why an app would want to generate links to them but it should be possible.

**Comment by BBGONE** [comment]
@JamesNK As for me, i vote for the builtin extension method. I use a SPA application which obtains the main page layout from standard MVC controllers, but it gets the data which is rendered on the page from web api dataservices (they provide only JSON). So these endpoints for the data are not inside the main application and i need to create URLs for those endpoints.
