### ISSUE TITLE
Move diagnostics out of Hosting into a StartupFilter or middleware

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#4499]
This PR attempted to move the diagnostic logic into a middleware and default IStartupFilter but there were some breaking changes we were worried about making in a minor release. I think it's time to revisit this logic to see if we can move it out of the core hosting logic and into a replaceable component. There are a few goals:
- Allow turning off these diagnostics
- Allow customizing these diagnostics
   - Setting a custom request id
   - Adding/Removing data from the default log scope.

Here's the original PR https://github.com/aspnet/Hosting/pull/1548. This was the main piece of feedback https://github.com/aspnet/Hosting/pull/1548#discussion_r218512835. It may require adding another event that servers fire so that this could be done from the middleware pipeline.

**Comment by anurse** [comment]
Triage decision:

![image](https://user-images.githubusercontent.com/7574/55838548-b013c700-5ad9-11e9-8c68-f146cd21238f.png)
