### ISSUE TITLE
[Blazor] Referencing the project name

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#4501]
This issue is intended for project maintainers and developers that are building custom tooling and/or projects for _Blazor_. Now that _Blazor_ is going to be renamed to _Razor Components_, how are we going to reference the _Blazor_ when describing our project? Are we going to reference to the _Blazor_ or _Razor Components_?

As I can see the _Blazor_ is mentioned in [README](https://github.com/aspnet/AspNetCore/tree/master/src/Components) along with Razor Components. 

Also what will happen with the [web page](https://blazor.net/)?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
