### ISSUE TITLE
In-Process Response.WriteAsync exception

### ISSUE THREAD

**Issue by unaizorrilla** [aspnet/AspNetCore#4505]
### Describe the bug
With ASP.NET Core 2.2 version
HttpContext.Response.WriteAsync throw object disposed on in-process project inside a middleware with OnStarting.

### To Reproduce
Map a new middleware like 
```
            app.Map("path", appBuilder =>
            {
                appBuilder.Run(context =>
                {
                    context.Response.OnStarting(async () =>
                    {
                        context.Response.ContentType = UIMain.ContentType;
                        await context.Response.WriteAsync("the content");
                    });
                    return Task.CompletedTask;
                });
            });
```

### StackTrace 

System.ObjectDisposedException: Cannot write to the response body, the response has completed.
Object name: 'HttpResponseStream'.
   at Microsoft.AspNetCore.Server.IIS.Core.HttpResponseStream.ValidateState(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)

**Comment by jkotalik** [comment]
Calling WriteAsync inside of OnStarting is unsupported behavior. I don't believe any of our other servers support this either. Can you see what happens when you run this with Kestrel?

**Comment by unaizorrilla** [comment]
This works well on kestrel 
Unsupported?? This is the way to write on response of other to it also, not?

**Comment by muratg** [comment]
cc @Tratcher thoughts on this?

**Comment by Tratcher** [comment]
@jkotalik is correct. It may work by accident in a few scenarios but in most cases it will cause deadlocks, data corruption, ObjectDisposedException, etc... 

E.g. In the most most common scenario the call stack looks like this:
App-Code -> HttpContext.Response.Body.WriteAsync -> OnStarting -> App-OnStarting-Code.
If you then called WriteAsync inside OnStarting it would either become recursive or it would write your data to the wire in the wrong order.

**Comment by Tratcher** [comment]
Why are you even trying to use OnStarting here? I'd expect the code to look like this:
```
                appBuilder.Run(async context =>
                {
                        context.Response.ContentType = UIMain.ContentType;
                        await context.Response.WriteAsync("the content");
                });
```

**Comment by unaizorrilla** [comment]
Well, for the typical exception like "some header can't be added because the response is started", in understand that onstarted work for headers and also for response stream, but probably is my fault
