### ISSUE TITLE
JsonConverter Deserializing Polymorphic List and ModelState Error Context

### ISSUE THREAD

**Issue by michaelvannevel** [aspnet/AspNetCore#4506]
### Description
When using a Polymorphic JsonConverter on a list of objects in a request to an Asp.Net Core Web app ModelStateValidation for properties of the objects in that list lose their context.  For example if i have an object Person and that object has a property Friends which is a List<Person>, if I set the Gender enum to an invalid enum value when using  JsonConverter i get a response like:

```json
{
    "gender": [
        "The input was not valid."
    ]
}
but if you take the JsonConverter off of the model you get:
{
    "friends[0].gender": [
        "The input was not valid."
    ]
}
```

I tried to place JsonConverters in the AddJsonOptions extension method on IServiceCollection, or directly on the model with the same result, not that I expected it to change.

### To Reproduce
1. Using this version of ASP.NET Core 2.1 or 2.2
2. Open the solution contained inside of the Stuffies.zip file.
3. Hit Debug
4. Make a request via postman or whatever tool you like and post to https://localhost:5001/api/values.
using the following json:

```json
{
	"name":"Bob Jones",
	"gender":"Male",
	"friends":[
		{
			"name":"Steven",
			"gender":"cat"
		}
	]
}
```

5. You'll see that the context of the response exists in the response: friends[0].gender
6. Now go into the ValuesController and uncomment the Attributes on the Person class
7. Debug again and do the same Post
4. See the differences in the previously mentioned responses between when you add or remove the Attributes from the Person class.  Now the response will have : gender without the context.

### Expected behavior
I expected the response to have the context on the ModelState error.

### Screenshots/Sample Project
![stuffies](https://user-images.githubusercontent.com/32906437/49656041-ee04bf80-fa01-11e8-8c0d-ea593812a4d0.PNG)
[Stuffies.zip](https://github.com/aspnet/AspNetCore/files/2657774/Stuffies.zip)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
