### ISSUE TITLE
Angular 4 with .Net core 2.1 role based authorization issue

### ISSUE THREAD

**Issue by jai00271** [aspnet/AspNetCore#4508]
I am using Angular 4 with dot net core 2.1(project skeleton is the one which gets created by default in visual studio 2017). I am doing claim based policy validation as below in my startup.cs :

```c#
services.AddAuthorization(options =>
            {
                options.AddPolicy("ReaderRole", policy => policy.RequireClaim("role", "READER"));
            }); 
```

and along with this I am decorating my API controller action with the attribute as shown below:

```c#
[Authorize(Policy = "ReaderRole")]
[HttpGet("{id}")]
public async Task<JsonResult> Get(string id)
{
}
```

Now authorization is working as expected and in case if user is not authorized controller is throwing below error but the response is in HTTP which browser(chrome) is blocking and I am not able to proceed further. My angular is not receiving the repose of the api call(.Net api) and it breaks in between.

Mixed Content: The page at 'https://myURL/home' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://myURL/Account/AccessDenied?returnUrl=%2Fapi%2FAccount%2Frandomemail@xxx.com'. This request has been blocked; the content must be served over HTTPS.

**Comment by Eilon** [comment]
@jai00271 - can you provide more info about your app? Is there any additional setup, such as a reverse proxy? And how is the XMLHttpRequest AJAX call being done? Any additional info you provide would be helpful.

**Comment by jai00271** [comment]
Hi Eilon,

the issue was with dot net core converting 502 to 302. I changed it to 401 and it is working fine. But still not sure why .Net core is converting 502 to 302.

**Comment by Eilon** [comment]
@jai00271 can you provide exact info on how to reproduce the issue and what the question is?

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
