### ISSUE TITLE
Add [FromQuery] Constructor to make parameter name assignment more simple

### ISSUE THREAD

**Issue by Psypher9** [aspnet/AspNetCore#4514]
### Describe the solution you'd like
The `FromQuery` attribute is great, though it could be helpful to have an optional constructor for the attribute to allow use like this:
`[FromQuery("a_param_name")]` instead of having to use the constructor like this:
`[FromQuery(Name = "<a_param_name")]`, 
similar to the pattern used in the `HttpMethodAttribute`'s template parameter.

I would like to offer my time to make the change. Can I make a PR for this feature change?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Psypher9.
Unfortunately, we're not going to take your PR for this change, as this is not something we've heard much community ask for.
