### ISSUE TITLE
Automate AspNetCore-Tooling dependency flow with DARC

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4521]
- [x] Get updates from dotnet/arcade
- [x] Get updates from dotnetcore-dev
- [ ] List packages that should be updated
- [x] Add subscription in dotnet/sdk
- [x] Add subscription in aspnet/AspNetCore

**Comment by natemcmaster** [comment]
This is done.

**Comment by natemcmaster** [comment]
Psych! it's not done. It looks like the repo is building against some rando-versions of System.* packages from MyGet. We need to update the eng/Versions.props and eng/Versions.Details.xml files to properly flow dependencies.

**Comment by Eilon** [comment]
@rynowak - we believe this is done. Do we need to do a "test PR" to see that eng/Versions.props and eng/Versions.Details.xml are in sync?

**Comment by Eilon** [comment]
Actually @natemcmaster will log a new issue for verifying this + adding logic to check it automatically. So, closing this.
