### ISSUE TITLE
Doesn't redirect Environment.CurrentDirectory and causes problems

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#4530]
### Describe the bug
After enabling In-Process hosting, the web app's Environment.CurrentDirectory becomes "C:\Program Files\IIS".

### To Reproduce
1. Using this version of ASP.NET Core 2.2.0
2.
```
dotnet new mvc
```
and then add a line in Program.cs above CreateWebHostBuilder:
```
Console.WriteLine(Environment.CurrentDirectory);
```
3. Run this web app under IIS.
4. You will find it output "C:\Program Files\IIS", but not the actual website's physical path. 

This will cause a lot of problems when there're File/Directory operations in a web application.

### Expected behavior
Output is the actual website's physical path.

**Comment by mac-bhaird** [comment]
This is covered here also: https://github.com/aspnet/AspNetCore/issues/4206
