### ISSUE TITLE
Basic UTF-8 encoded html pages served through UseStaticFiles don't have their ContentType charset correctly set

### ISSUE THREAD

**Issue by Abarbz** [aspnet/AspNetCore#4546]
### Description
When serving static utf-8 encoded html pages with Asp.Net Core's UseStaticFiles, the response ContentType is set to `text/html` and not `text/html; charset=utf-8`

### To Reproduce
1. Using ASP.NET Core v2.1.0, create a new Web API project, and disable IIS integration.
2. Add `.UseDefaultFiles().UseStaticFiles()` to `Startup.Configure()`
3. Create an html page named default.html in wwwroot and containing the following html fragment:
```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>My page title</title>
</head>

<!--Some static content-->

</html>
```
4. Run the project and use postman or equivalent to GET the default url `http://localhost:61106/` 
5. Check the response header. It shows `Content-Type →text/html` 

### Expected behavior
Content-Type should be `text/html; charset=utf-8` (or whatever charset is declared in the html page).

**Comment by Tratcher** [comment]
StaticFiles sets the Content-Type based on file extension, it has no knowledge of the file encoding. Where would you get that information?

**Comment by Abarbz** [comment]
Maybe I was misled by the [Asp.Net core Integration test documentation](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#disposal-of-objects) that actually shows the following:
```
[Theory]
    [InlineData("/")]
    [InlineData("/Index")]
    [InlineData("/About")]
    [InlineData("/Privacy")]
    [InlineData("/Contact")]
    public async Task Get_EndpointsReturnSuccessAndCorrectContentType(string url)
    {
        // Arrange
        var client = _factory.CreateClient();

        // Act
        var response = await client.GetAsync(url);

        // Assert
        response.EnsureSuccessStatusCode(); // Status Code 200-299
        Assert.Equal("text/html; charset=utf-8", 
            response.Content.Headers.ContentType.ToString());
    }
```
In this case though, pages are not plain html. Maybe this is the reason why my results differ?
Would it be possible to parse the charset from the `<meta charset="utf-8" />` attribute in the HTML page header to populate the `ContentType` when served?
Or maybe default to utf-8, as it is the default character encoding for HTML5?

**Comment by Tratcher** [comment]
Right, those tests cover dynamic content where ASP.NET generates the HTML and does the encoding.

Is your client having any trouble consuming the response without the charset specified? If it's not broken then don't fix it.

Parsing static files is a non-starter, hundreds of file types are supported. The same goes for assuming utf-8, we don't know the contents are HTML5. 

In your app you may be able to replace the `.html` entry in the [FileExtensionContentTypeProvider](https://github.com/aspnet/AspNetCore/blob/87629bbad906e9507026692904b6bcb5021cdd33/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs#L122) to include the charset. There's also the [OnPrepareResponse](https://github.com/aspnet/AspNetCore/blob/87629bbad906e9507026692904b6bcb5021cdd33/src/Middleware/StaticFiles/src/StaticFileOptions.cs#L53) event where you could customize the content-type header.

**Comment by Abarbz** [comment]
No issue per say, my tests were just expecting UTF-8 as my html was declaring it as charset.
I'll look into your suggestions, thanks!
