### ISSUE TITLE
[RPS] Roslyn Completion Provider is now also loading Razor.Language

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4548]
## The hits keep coming!

Our (old) completion provider is now loading Razor.Language when it loads. This is failing RPS and blocking us doing an insertion.

I'm not sure why this is suddenly happening - but we're inserting about 5-6 weeks worth of open development in this PR.

![image](https://user-images.githubusercontent.com/1430011/49747884-3bc73500-fc59-11e8-9cb0-73050b8b9743.png)

/cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
Verified offline.
