### ISSUE TITLE
Microsoft.AspNetCore.Signalr 1.1.0 cannot be install via NuGet

### ISSUE THREAD

**Issue by leung85** [aspnet/AspNetCore#4562]
### Describe the bug
Microsoft.AspNetCore.Signalr 1.1.0 cannot be installed with a simple web api project
because of version not compatible vserion of Microsoft.AspNetCore.App 2.1.1

### To Reproduce
1. Create new WebAPI project with vs2017
2. Open NuGet Manager
3. Search Microsoft.AspNetCore.Signalr
4. Install Microsoft.AspNetCore.Signalr
5. Error

### Expected behavior
Success install. As a new project, it should be easy and success install via NuGet Manager. Should not have conflict because i expected everything should be the latest and compatible. 
Or Should block install version Microsoft.AspNetCore.Signalr 1.1.0.

### Screenshots
![image](https://user-images.githubusercontent.com/8042599/49790629-aebfd100-fd69-11e8-9982-0dc3104a162f.png)

**Comment by BrennanConroy** [comment]
If you update SignalR you need to update the runtime too, so Microsoft.AspNetCore.App 2.2.0

**Comment by leung85** [comment]
@BrennanConroy  
Yes, i know that . i have a lot experience to due with the update problem loop :(
I am not update the package. i am create a new project and search signalr then install. i think it should block the version signalr 1.1.0. if i am use 2.1 SDK. 

Why i report this as bug, because i have an 2.1 SDK project, when i check update, NuGet tell me you have an update, so i go to update , after that everything not work , cannot be build due to version not compatible. 

I expected it should block my install like this
![image](https://user-images.githubusercontent.com/8042599/49816544-0af61580-fda9-11e8-8946-118ae49b7b6f.png)

 , it is not good to tell me you can update. 
I always use a lot of time to handle those version issue, not on programming my project.

DONT make .net core update become a **Window 10 update**, .... After update a lot of issue......  so make people don't want to update

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
