### ISSUE TITLE
AspNetCoreModuleV2 - web.config - but no module in publish 

### ISSUE THREAD

**Issue by kenso23** [aspnet/AspNetCore#4568]
Hi 

I have an asp.net core 2.2.1 application, that i upgraded from 2.0, using the full framework. When i deploy the application to Azure It writes this to the web.config file: 
```xml
<system.webServer>
      <handlers>
        <remove name="aspNetCore" />
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="%LAUNCHER_PATH%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" arguments="%LAUNCHER_ARGS%">
        <environmentVariables />
      </aspNetCore>
    </system.webServer>
```

But the AspNetCoreModuleV2 module is not publish to Azure App Service. I can not find it in Nuget or as a part of the All package. 

Hope somebody can clarify this.

**Comment by Code-DJ** [comment]
@kenso23 did you see the "Availability in Azure App Service" section in the announcement blog: https://blogs.msdn.microsoft.com/webdev/2018/12/04/asp-net-core-2-2-available-today/

**Comment by kenso23** [comment]
Ahh, no I didn’t- sorry I should have noted it. 

Thank you for quick answer!
