### ISSUE TITLE
Change logging site extension package name/description

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#4570]
as noted by @guardrex 

> It's named "ASP.NET Core Logging Extensions" but only a single service extension, so it seems a little strange when I write in the topic ...
> 
>     ... by the ASP.NET Core Logging Extensions. This extension enables ...
> 
> plural 👉 singular mismatch
> 
> Second thing is the description:
> 
>     This extension enables additional functionality for ASP.NET Core on Azure WebSites, such as enabling Azure logging.
> 
> I might be wrong, but didn't "Azure WebSites" (naming) fall out-of-favor with marketing? Should it be "Azure Apps" or "Azure App Service"? I can make the doc state the description that way. If I should go that way, let me know if I should open an engineering issue for it (perhaps for the extension name, too ☝️).
> 
> [EDIT] Noticed one thing in the portal ... they DO use "Web App" quite a bit.
> 
> Last thing while I'm here ..... description is "such as" ... is there anything else you would like the Azure Apps topic to say about what this extension does besides supplying logging scenarios.

I think he is correct about all of them, we should fix it before 3.0

**Comment by muratg** [comment]
@DamianEdwards FYI
