### ISSUE TITLE
Outbound route parameter transformer not working on ASP.NET Core MVC unless I use attribute routing

### ISSUE THREAD

**Issue by BrightSoul** [aspnet/AspNetCore#4578]
### Describe the bug
An outbound route parameter transformer works only when I use attribute routing. Instead, I think it makes more sense if it worked even with the default route.

### To Reproduce
Register an outbound route parameter transformer like this.
```
services.AddMvc(options =>
{
    var routeParameterTransformer = new MyParameterTransformer();
    var routeConvention = new RouteTokenTransformerConvention(routeParameterTransformer);
    options.Conventions.Add(routeConvention);
}).SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
```
Where `MyParameterTransformer` is an implementation of ` IOutboundParameterTransformer`.
```
public class MyParameterTransformer : IOutboundParameterTransformer
{
    public string TransformOutbound(object value)
    {
        if (value as string == "Home") {
            return "Welcome";
        }
        return value?.ToString();
    }
}
```
Now, when I visit the path `/Welcome` I get a 404 when I should be able to see the homepage instead. It starts working only if I use `[Route("[controller]")]` on the `HomeController`, which is inconvenient for UI applications.

### Expected behavior
I'd expect the route parameter transformer to work with any route defined in the `Startup` class but it seems I must rely on attribute routing to make it work.

**Comment by BrightSoul** [comment]
Thanks for the quick reply, however I still cannot make it work. The documentation you provided states:
> Are configured using ConstraintMap.

But... how exactly? A detailed example would be nice since this is somewhat confusing... Basically it's asking me to add a class that's not implementing `IRouteConstraint` to the constraint map? Like so?
```
services.Configure<RouteOptions>(routeOptions =>
{
  routeOptions.ConstraintMap.Add("my", typeof(MyParameterTransformer));
});
```

**Comment by JamesNK** [comment]
Correct

**Comment by BrightSoul** [comment]
Ok, thanks for your reply. I made it work but I think the route template your provided is not right. The constraint and default value should be in reversed orded, e.g.
```
routes.MapRoute(
    name: "default",
    //template: "{controller=Home:slugify}/{action=Index:slugify}/{id?}");
    template: "{controller:slugify=Home}/{action:slugify=Index}/{id?}");
```
Otherwise you'd get some weird behavior (i.e. `TransformOutbound` not invoked at all and default values ignored altogether).

Also... I don't know what the original intent with the outbound transformers was but I think the  `TransformOutbound`  method should receive the whole route data context and not just a single value of type `object`. I mean, when it gets passed a value of "Home", how do I know which route path are we trying to generate here? And with which parameter values?

Thanks.

**Comment by JamesNK** [comment]
The purpose of a transformer is to apply a consistent pattern to a parameter. For example, making the controller and action parameters use camel case.

Thanks for the feedback on the documentation. I've made changes here - https://github.com/aspnet/Docs/pull/9987

**Comment by BrightSoul** [comment]
Ok, cool, I'm closing this issue.
