### ISSUE TITLE
Refactor Microsoft.Extensions.Identity.Core and Identity.Stores as netstandard2 packages

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#4582]
@blowdart @PinpointTownes 
https://github.com/aspnet/AspNetCore/pull/4523#issuecomment-446323776

There's some desire for these as standalone packages. Unfortunately they were never properly factored for that.
- The packages depended on AspNetCore DataProtection
- The namespaces inside the packages are all AspNetCore, not Extensions

**Comment by PinpointTownes** [comment]
Yes, please :+1:

**Comment by PinpointTownes** [comment]
Don't forget the EF Core stores package that should be renamed and whose dependency on [`Microsoft.AspNetCore.Identity` should be removed](https://github.com/aspnet/Identity/pull/1188#issuecomment-304474562).
