### ISSUE TITLE
Latest Razor tooling source link not working in VS

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#4584]
### Describe the bug
We did a VS insertion yesterday (12/10) which had new Razor tooling bits from our AspNetCore-Tooling repo. I tried debugging those bits and found that I could download symbols for the binary and upon doing so would be prompted to download the source file. In VS after clickign "Download source and continue" it attempts to do it multiple times and then fails.

### To Reproduce
1. Open d16.0stg
2. Open a web project
3. Open a Razor file
4. Add a function breakpoint for `RazorDirectiveCompletionProvider.ProvideCompletionsAsync`.
5. At the top of the Razor file type `@p`
6. Your breakpoint will hit, at which point it will attempt to load the sources.

### Expected behavior
Source file is properly downloaded

**Comment by rynowak** [comment]
This worked for me just now on another part of the razor tooling code. I'm going to close this.
