### ISSUE TITLE
Razor Class Library dynamic loading as ApplicationParts. Views can't use models

### ISSUE THREAD

**Issue by GrilleGustav** [aspnet/AspNetCore#4588]
### Describe the bug
Can not use dynamic loading RCL. because the views can't find the models.

### To Reproduce
1. netcore2.2
2. https://aqua-wirbellose.visualstudio.com/HostingPanel 
Open Branche: 33_Implementierung_Plugin_System
3. Start Project and open: https://localhost:44397/Wiki/Wiki/Create
4. System.IO.FileNotFoundException: Could not load file or assembly 'HostingPanel.Wiki, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'HostingPanel.Wiki, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.IO.FileNotFoundException: Could not load the specified file.

### Expected behavior
I want to use mvc in a "Razor Class Library". All looks good. I have ony one problem, when i open the view, the view can't find the model. When i reference all RCL ther is no error. Only an dynamic loading the error exist. How can i resolve it ?

### Screenshots
https://upload.crunkbass.de/big486f7374696e6750616e656c5f57696b695f4372656174655f457863657074696f6e2e6a7067.jpg

### Additional context
I want to use dynamic loaded RCLs. I Use ApplicationParts for that.
What i have:
I have a RCL that named Wiki and i need EFCore and AutoMigration.

PM> dotnet --info
.NET Core SDK (gem„á "global.json"):
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-009171 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009297 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009404 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GrilleGustav.
@pranavkm, can you please look into this? Thanks!

**Comment by GrilleGustav** [comment]
I already solfed the Problem and i have multiplugin support.

**Comment by taori** [comment]
@GrilleGustav how did you solve it?

**Comment by GrilleGustav** [comment]
Yes I solve the Problem. Now i ahve full plugin with Own DBContext in Each Plugin.
Can upload this when you want.

**Comment by GrilleGustav** [comment]
It is on DevOps https://dev.azure.com/aqua-wirbellose/HostingPanel

**Comment by taori** [comment]
Thanks. it wasn't visible. that is why i asked :)

**Comment by taori** [comment]
whatever you did to fix it is probably in the pluginservice, right? just so you/me can publish the resolution here in case you drop that repo at some point
