### ISSUE TITLE
Open Id Connect implementation does not play well with Web Application Firewall

### ISSUE THREAD

**Issue by pierslawson** [aspnet/AspNetCore#4589]
The default implementation of Open Id Connect uses a Data Protection Provider that generates strings that fall foul of a Web Application Firewall implementing the OWASP rule set's SQL Injection checking. For example, a Nonce cookie is created where the name of the cookie has `Options.StringDataFormat.Protect(nonce)` appended. This means the cookie often has the string "--" somewhere within it. This then gets picked up as a potential SQL Comment Sequence and blocked. I have also seen the SQL Hex Encoding rule triggered.

Other places I have seen the issue:

 * Contents of the Authentication Cookie
 * Contents of the Anti Forgery Cookie
 * Contents of the Anti Forgery request verification token form data

For my WAF I am using the Azure Application Gateway Web Application Firewall. I can configure its Exclusion rules to mitigate against these last three instances of the issue. However, Exclusions are only available in "Preview" of the WAF so should not be used in production. Also, they don't help with the Nonce issue as the exclusion rules only exclude the checking of a cookie's value, not of its name!

My only alternative is to turn off the checks for SQL Injection... however since that is the considered the most common attack vector it seems to go against the point of using a WAF!

### To Reproduce
1. Create an ASP.Net Core web application and use an Identity Server for authentication (using the code id_token flow)
2. Host the application behind Azure Application Gateway
3. Turn on WAF in the Application Gateway, enabling the Firewall, setting the Firewall mode to Prevention and use the OWASP 3.0 rule set
4. Repeatedly log in and log out of the application

### Expected behavior
I would expect the log in and log out to always succeed, however perhaps 1 in 5 / 1 in 10 attempts to login will fail with a 403 returned by the Application Gateway.

### Additional context

Using the Preview exclusion feature I have added the following exclusions to the WAF on the Application Gateway:

Field | Operator | Selector
------|----------|---------
Request attribute name | Equals | id_token
Request attribute name | Equals | state
Request cookie name | starts with | .AspNetCore.OpenIdConnect.Nonce.
Request cookie name | starts with | .AspNetCore.Correlation.oidc.
Request cookie name | starts with | .AspNetCore.Cookies
Request cookie name | starts with | ABC.AuthCookie
Request cookie name | starts with | .AspNetCore.Antiforgery.
Request attribute name | starts with | __RequestVerificationToken

But as I said above, Exclusions should not be used in production and they do not fix issues with the names of cookies containing character sequences that trigger SQL Injection rules.

**Comment by muratg** [comment]
Are you sure it's the names, and not the values with "--" in them that cause this? Perhaps one of your values has this in it's Base64 encoded form? 

Anyway, this doesn't look actionable from our side.

**Comment by brockallen** [comment]
The data protected state string is what he's talking about. // @HaoK

**Comment by blowdart** [comment]
Yea, the trigger here is "--" and we're not about to invent a new encoding just to bypass an overly sensitive rule.

The Azure folks said exclusions are available in production and that's their solution.

**Comment by pierslawson** [comment]
@murtag I was very sure at the time I raised this that it was the name that had a problem. The logging by the WAF was quite explicit about the cause. Currently we are having to run our system with the rules "942440 SQL Comment Sequence Detected" and "942450 SQL Hex Encoding Identified" turned off.

I raised this on the WAF UserVoice forum as it seems to be the only place to communicate with the team:
https://feedback.azure.com/forums/217313-networking/suggestions/36260122-web-application-firewall-cookie-exclusions-only-ex
No feedback yet.

**Comment by brockallen** [comment]
> Yea, the trigger here is "--" and we're not about to invent a new encoding just to bypass an overly sensitive rule.
> The Azure folks said exclusions are available in production and that's their solution.

I do know those exclusions are app-wide, and can't be set for a specific path/url, so unfortunately this means the entire app will not longer have the rule in place, rather than just the redirect uri for OIDC.

**Comment by Eilon** [comment]
First step is to get an app set up with WAF and see if we can reproduce the "bad SQL injection rule" thing, and then come up with possible alternative cookie characters that do pass the rule.

**Comment by Eilon** [comment]
Closing because we decided not to make any change to the Auth behavior because we believe the current behavior is correct.

**Comment by pierslawson** [comment]
@Eilon It would be good if you suggested a work around... or are you able to raise this with the team responsible for the WAF. To those of us outside of Microsoft there only seems to be a UserVoice forum to allow us to suggest new features rather than report bugs.

**Comment by danieljsc** [comment]
I still have problems with compatibility between Open Id Connect and Microsoft Authentication and WAF Firewall throwing unauthorized access errors some times. It was seeming random, and if I reproduce the sign out/sign in multiple times, sometimes it works, others it gets blocked.

Is there any workaround beside of disabling/adding exceptions to the rules?

**Comment by pierslawson** [comment]
No... it still appears to be an issue. From the above, the ASP.Net Core team are not going to fix it and it looks like the WAF team are not doing anything about it either. Please vote on their uservoice account:
https://feedback.azure.com/forums/217313-networking/suggestions/36260122-web-application-firewall-cookie-exclusions-only-ex
