### ISSUE TITLE
Razor Components hitting F12 key in Razor markup doesn't take you to other components

### ISSUE THREAD

**Issue by wanton7** [aspnet/AspNetCore#4593]
### Describe the bug
F12 key doesn't take you to other components in Razor markup. Also hitting F12 over a component's type in `.cs` only component doesn't take me to Razor markup but to components generated `.cs` file. For `BasicField` component it took me to `BasicField.g.i.cs`.

### To Reproduce
Let's say you have two components `Component1` and `Component2` and you have `<Component2></Component2>` in `Component1`'s markup.  Then you move your cursor over `<Component2>` and hit F12 key. Nothing happens.

I'm using `Microsoft.AspNetCore.Components` NuGet version `0.8.0-preview1-20181126.4` , Blazor extension version `15.7.20181126.4` and Visual Studio 2017 `15.9.4`

### Expected behavior
Hitting F12 key takes me to `Component2`'s markup or code if `Component2` only has `.cs` file.

**Comment by rynowak** [comment]
Thanks for the feedback. We do plan to enable this eventually, but since it's part of visual studio, it's tracked elsewhere.
