### ISSUE TITLE
SignalR WWW-Authenticate: Bearer error="invalid_token"

### ISSUE THREAD

**Issue by ranouf** [aspnet/AspNetCore#4620]
Hi,

The authentication process works perfectly with controller, I can use `[Authorize]` without any problem.
Signal worked perfectly before I added the authentication.
What I know is:
- the token is correctly send by Angular (I can it in the server in the authorization header)
- the signing key validation works, because controllers works
- signalR without authentication works

What I dont know is:
- how to set up SignalR correctly to make it work with authentication?

I configured SignalR with Authentication, but it doesnt work, each time I have an **error 401** with 

> WWW-Authenticate: Bearer error="invalid_token"

I followed this tutorial:
https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1

Here is how I generate the Token:

```
 public static string GenerateToken(AuthenticationSettings authSettings, User user)
        {
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Issuer = authSettings.Issuer,
                Audience = authSettings.Audience,
                NotBefore = DateTime.UtcNow,
                IssuedAt = DateTime.UtcNow,
                Subject = new ClaimsIdentity(new Claim[]
                {
                    new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                    new Claim(ClaimTypes.Role, user.RoleName),
                }),
                Expires = DateTime.UtcNow.AddDays(authSettings.ExpirationDurationInDays),
                SigningCredentials = GetSigningCredentials(authSettings.SecretKey)
            };
            var tokenHandler = new JwtSecurityTokenHandler();
            var tokenId = tokenHandler.CreateToken(tokenDescriptor);
            return tokenHandler.WriteToken(tokenId);
        }

        public static SigningCredentials GetSigningCredentials(string secretKey)
        {
            var encodedKey = Encoding.ASCII.GetBytes(secretKey);
            var symecticSecurityKey = new SymmetricSecurityKey(encodedKey);
            return new SigningCredentials(symecticSecurityKey, SecurityAlgorithms.HmacSha256Signature);
        }
```

Startup:
```
     public IServiceProvider ConfigureServices(IServiceCollection services)

            services.AddDbContext<AppDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection"),
                    opt => opt.EnableRetryOnFailure()
                )
            );

            //Identity
            services.AddIdentity<User, Role>()
                .AddEntityFrameworkStores<AppDbContext>()
                .AddDefaultTokenProviders()
                .AddUserStore<UserStore<User, Role, AppDbContext, Guid, IdentityUserClaim<Guid>, UserRole, IdentityUserLogin<Guid>, IdentityUserToken<Guid>, IdentityRoleClaim<Guid>>>()
                .AddRoleStore<RoleStore<Role, AppDbContext, Guid, UserRole, IdentityRoleClaim<Guid>>>();

            //Cors
            services.AddCors(options =>
            {
                options.AddPolicy(
                    "CorsPolicy",
                    config => config
                        .AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                        .AllowCredentials()
                );
            });
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(o =>
            {
                o.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidIssuer = Configuration["Authentication:Issuer"],
                    ValidateAudience = true,
                    ValidAudience = Configuration["Authentication:Audience"],
                    ValidateActor = false,
                    RequireExpirationTime = true,
                    ValidateLifetime = true,
                    LifetimeValidator = (before, expires, token, param) => expires > DateTime.UtcNow,
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = TokenHelper.GetSigningCredentials(Configuration["Authentication:SecretKey"]).Key
                };
                o.RequireHttpsMetadata = false;
                o.IncludeErrorDetails = true;
                o.SaveToken = true;
                o.Events = new JwtBearerEvents
                {
                    OnMessageReceived = context =>
                    {
                        // If the request is for our hub...
                        if (context.HttpContext.Request.Path.StartsWithSegments("/hubs")
                            && context.HttpContext.Request.Headers.TryGetValue("Authorization", out var accessToken))
                        {
                            // Read the token out of the query string
                            context.Token = accessToken.ToString();
                        }
                        return Task.CompletedTask;
                    },
                    OnAuthenticationFailed = context =>
                    {
                        var te = context.Exception;
                        return Task.CompletedTask;
                    }
                };
            });

            services.AddAuthorization(options =>
            {
                options.DefaultPolicy = new AuthorizationPolicyBuilder(JwtBearerDefaults.AuthenticationScheme)
                    .RequireAuthenticatedUser()
                    .RequireClaim(ClaimTypes.NameIdentifier)
                    .Build();
            });
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)

            //SignalR
            services.AddSignalR();
            services.AddSingleton<IUserIdProvider, UserIdProvider>();
            [...]
     }

     public void Configure(
            IApplicationBuilder app,
            IHostingEnvironment env,
            ILoggerFactory loggerFactory,
            IApplicationLifetime appLifetime
        )
        {
            //Cors
            app.UseCors("CorsPolicy");

            app.UseAuthentication();

            //SignalR
            app.UseSignalR(routes =>
            {
                routes.MapHub<SampleHub>("/hubs/sample");
                routes.MapHub<UserHub>("/hubs/user");
                routes.MapHub<NotificationHub>("/hubs/notification");
            });

            //https
            app.UseHttpsRedirection();
            app.UseHsts();

            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseMvc();
    }
```

SampleHub:
  ```
  [Authorize]
    public class SampleHub : Hub
    {
        public override async Task OnConnectedAsync()
        {
            await Groups.AddToGroupAsync(Context.ConnectionId, "SignalR Users");
            await base.OnConnectedAsync();
        }

        public override async Task OnDisconnectedAsync(Exception exception)
        {
            await Groups.RemoveFromGroupAsync(Context.ConnectionId, "SignalR Users");
            await base.OnDisconnectedAsync(exception);
        }
    }

    public class SamplesHubHandler :
        BaseHubHandler<SampleHub>,
        IEventHandler<SampleCreatedEvent>,
        IEventHandler<SampleUpdatedEvent>,
        IEventHandler<SampleDeletedEvent>
    {
        public SamplesHubHandler(
            IHubContext<SampleHub> connectionManager,
            INotificationManager notificationManager,
            IMapper mapper
        ) : base(connectionManager, notificationManager, mapper)
        {
        }

        public void Handle(SampleCreatedEvent args)
        {
            SendNotification<Guid?, Sample, SampleDetailsDto>(args, args.Sample, args.Sample.Text);
        }

        public void Handle(SampleUpdatedEvent args)
        {
            SendNotification<Guid?, Sample, SampleDetailsDto>(args, args.Sample, args.Sample.Text);
        }

        public void Handle(SampleDeletedEvent args)
        {
            SendNotification<Guid?, Sample, SampleDetailsDto>(args, args.Sample, args.Sample.Text);
        }
    }

```

here is the code I use for Angular to connect to SignalR
 ```
 private connectToSignalServer(): void {
    let builder = new HubConnectionBuilder();
    this._hubConnection = builder.withUrl(
      environment.apiUrl + '/hubs/sample',
      { accessTokenFactory: () => `${myToken}` } // eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhOTQxOTM4NS1iZGU0LTQxZWMtNjIzYS0wOGQ2NGM1NzQ4ODMiLCJyb2xlIjoiQWRtaW5pc3RyYXRvciIsIm5iZiI6MTU0NDY1MjQ1MCwiZXhwIjoxNTQ1MjU3MjUwLCJpYXQiOjE1NDQ2NTI0NTAsImlzcyI6IkFsbEluT25lIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo5MzM0LyJ9.k_80AXyiU2UylKhG0vi9_O8FUdlRbZxC64bdj31QfWA
    ).build();
    this._hubConnection.start()
      .then(() => {
        this._isConnected.next(true);
        console.log('[SignalR] Connection to Sample hub established.');
      })
      .catch(err => {
        this._isConnected.next(false);
        console.error('[SignalR] Error while establishing connection to Sample hub.');
      });
  }
```

![image](https://user-images.githubusercontent.com/1764519/49902932-80a6c380-fe33-11e8-9234-9e6e88f8b74b.png)

1: request to [Authorize] api actions works correctly
2: request to login to SignalR returns error 401

Where is my mistake? Each answer I found on google, stackoverflow, github didn t work. Maybe you have an idea?

**Comment by BrennanConroy** [comment]
Try turning on Server logs to see what it says about auth.

**Comment by ranouf** [comment]
I use Serilog to redirect the log in a file. There is no error about SignalR Authentication.

In ApplicationInsight, I can see the request which has failed:
![image](https://user-images.githubusercontent.com/1764519/49903994-daf55380-fe36-11e8-9306-e3615e67cbb6.png)

Here are the detail for one request
![image](https://user-images.githubusercontent.com/1764519/49904024-f2ccd780-fe36-11e8-9b94-af901d593ad1.png)

In the output console, only ApplicationInsight telemetry are logged:

> Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.11111111222233334444555555555555.Request","time":"2018-12-12T22:54:48.1086915Z","iKey":"11111111-2222-3333-4444-555555555555","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"DESKTOP-5VOT5BA","ai.operation.id":"f3a43bf34d955749840c745e64a1a0b7","ai.operation.name":"OPTIONS /hubs/notification/negotiate","ai.location.ip":"::1","ai.internal.sdkVersion":"aspnet5c:2.5.1","ai.internal.nodeName":"DESKTOP-5VOT5BA"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|f3a43bf34d955749840c745e64a1a0b7.7d3f375c_","name":"OPTIONS /hubs/notification/negotiate","duration":"00:00:00.0002932","success":true,"responseCode":"204","url":"http://localhost:2887/hubs/notification/negotiate","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.1')"}}}}
> Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.11111111222233334444555555555555.Request","time":"2018-12-12T22:54:48.1321844Z","iKey":"11111111-2222-3333-4444-555555555555","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"DESKTOP-5VOT5BA","ai.operation.id":"57893fa38420a648891ddaea5b8c316c","ai.operation.name":"OPTIONS /hubs/sample/negotiate","ai.location.ip":"::1","ai.internal.sdkVersion":"aspnet5c:2.5.1","ai.internal.nodeName":"DESKTOP-5VOT5BA"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|57893fa38420a648891ddaea5b8c316c.7d3f375e_","name":"OPTIONS /hubs/sample/negotiate","duration":"00:00:00.0003287","success":true,"responseCode":"204","url":"http://localhost:2887/hubs/sample/negotiate","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.1')"}}}}
> Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.11111111222233334444555555555555.Request","time":"2018-12-12T22:54:48.1946080Z","iKey":"11111111-2222-3333-4444-555555555555","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"DESKTOP-5VOT5BA","ai.user.id":"KILUl","ai.operation.id":"aa0e282ce2700a4381f0ec396ffde199","ai.operation.name":"POST /hubs/sample/negotiate","ai.location.ip":"::1","ai.internal.sdkVersion":"aspnet5c:2.5.1","ai.internal.nodeName":"DESKTOP-5VOT5BA"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|aa0e282ce2700a4381f0ec396ffde199.7d3f3762_","name":"POST /hubs/sample/negotiate","duration":"00:00:00.0005623","success":false,"responseCode":"401","url":"http://localhost:2887/hubs/sample/negotiate","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.1')"}}}}
> Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.11111111222233334444555555555555.Request","time":"2018-12-12T22:54:48.1946080Z","iKey":"11111111-2222-3333-4444-555555555555","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"DESKTOP-5VOT5BA","ai.user.id":"KILUl","ai.operation.id":"a49a56adf3bb224e85f3da1ee63a48c0","ai.operation.name":"POST /hubs/notification/negotiate","ai.location.ip":"::1","ai.internal.sdkVersion":"aspnet5c:2.5.1","ai.internal.nodeName":"DESKTOP-5VOT5BA"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|a49a56adf3bb224e85f3da1ee63a48c0.7d3f3761_","name":"POST /hubs/notification/negotiate","duration":"00:00:00.0005623","success":false,"responseCode":"401","url":"http://localhost:2887/hubs/notification/negotiate","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.1')"}}}}
> 

If you know a way to get more log on SignalR, please let me know.

Thanks for your help

**Comment by BrennanConroy** [comment]
One thing I noticed is that you use https for MVC and http for SignalR, not sure if that affects anything.

There should be some sort of logs from Auth saying what happened. Try turning up the log level to Debug

**Comment by BrennanConroy** [comment]
Ok, don't do ```context.HttpContext.Request.Headers.TryGetValue("Authorization", out var accessToken)```, that probably breaks the token by including "bearer" and only in signalr because you're only doing it on a "/hubs" request. The docs you linked to, show we only grab the "access_token" query string value, I'm guessing the auth system will automatically grab the "Authorization" header and correctly set the `context.Token` property.

**Comment by ranouf** [comment]
The documentation is not really up to date.
In Angular, when I want to connect to signalR Server I use this:
 this._hubConnection = builder.withUrl(
      environment.apiUrl + '/hubs/sample',
      { accessTokenFactory: () => `${myToken}` }
    )

The package is "@aspnet/signalr": "1.1.0", (https://www.npmjs.com/package/@aspnet/signalr).

When I do that, 'Bearer' is automatically added to myToken and added as header authentication. 
here is an example: https://kimsereyblog.blogspot.com/2018/07/signalr-core-with-angular.html (or the code directly: https://github.com/Kimserey/signalr-core-sample-ng/blob/master/src/app/message.service.ts)

About the https, currently I run the app in local so both http and https are available, but for sure, I will have to make it work correctly when I will deploy it on Azure, thanks to have notice it :)

**Comment by BrennanConroy** [comment]
> The MSDN documentation is not really up to date.

What isn't up to date in it?

**Comment by ranouf** [comment]
In the documentation it s written:
angular:
```
this.connection = new signalR.HubConnectionBuilder()
    .withUrl("/hubs/chat", { accessTokenFactory: () => this.loginToken })
    .build();
```

server:
`var accessToken = context.Request.Query["access_token"];`

But when I test it, I have no value:
![image](https://user-images.githubusercontent.com/1764519/49906271-2b70af00-fe3f-11e8-87d5-36e8df46a383.png)

but when I do :
`context.HttpContext.Request.Headers.TryGetValue("Authorization", out var accessToken)`

I have a value:
![image](https://user-images.githubusercontent.com/1764519/49906322-5eb33e00-fe3f-11e8-9d56-334bd01b739d.png)

**Comment by BrennanConroy** [comment]
That's because during the /negotiate request the "Authorization" header is used, if you look at `context.Token` it probably already has the token set so there is no need to modify it. However, after /negotiate we have to use the "access_token" query string because browser APIs don't allow setting headers in some situations.

**Comment by ranouf** [comment]
Sorry to answer no again :(
![image](https://user-images.githubusercontent.com/1764519/49906519-41cb3a80-fe40-11e8-9fe0-df56690b86b2.png)

the context.Token is null before I set it.

But you were true about the header authorization :). I updated the angular part to:
```
    this._hubConnection = builder.withUrl(
      environment.apiUrl + `/hubs/sample?token=bearer ${this.authenticationService.token}`//,
      //{ accessTokenFactory: () => `${this.authenticationService.token}` }
    ).build();
```

and the backend part to:
```
if (context.HttpContext.Request.Path.StartsWithSegments("/hubs")
                            && context.HttpContext.Request.Query.TryGetValue("token", out var accessTokenFromQueryString
                            ))
                        {
                            // Read the token out of the query string
                            context.Token = accessTokenFromQueryString;
                        }
```

and now it works!

So I will contact https://github.com/aspnet/SignalR about their npm package which doesnt work correctly.

Thanks @BrennanConroy  and @brockallen for your help, I was stocked for a while on it.

**Comment by BrennanConroy** [comment]
Don't file an issue there, use this one

**Comment by BrennanConroy** [comment]
Did you actually try the **exact** code from the sample? And did it not work?

**Comment by BrennanConroy** [comment]
Ok, I was guessing the `context.Token` value would be set, but turns out it will be null and is only used if the user sets it. Otherwise it will do the correct thing with the "Authorization" header, see https://github.com/aspnet/AspNetCore/blob/02ca469ea1ee06be2769ebbb0252bc88847d6378/src/Security/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L61-L65

**Comment by ranouf** [comment]
> Don't file an issue there, use this one

How to do that? I thought created an issue on their github and put a link to this issue.

> Did you actually try the exact code from the sample? And did it not work?

I didnt take the example but I took some piece on it like this one which failed:
{ accessTokenFactory: () => `${myToken}` }

**Comment by BrennanConroy** [comment]
Try something real quick for me, replace your `OnMessageReceived` handler with:
```
OnMessageReceived = context =>
{
    var accessToken = context.Request.Query["access_token"];

    // If the request is for our hub...
    var path = context.HttpContext.Request.Path;
    if (!string.IsNullOrEmpty(accessToken) &&
    (path.StartsWithSegments("/hubs/chat")))
    {
        // Read the token out of the query string
        context.Token = accessToken;
    }
    return Task.CompletedTask;
}
```

and use your original client code:
```
this._hubConnection = builder.withUrl(
     environment.apiUrl + '/hubs/sample',
     { accessTokenFactory: () => `${myToken}` }
   ).build();
```

**Comment by ranouf** [comment]
I feel stupid :( You were true, it works like this. It probably didn t work the first time I tried because the order in the instruction was not the good one (always put AddSignalR after AddAuthentication).

thanks for your help, we can close the issue. I hope it will help other people :).
