### ISSUE TITLE
InvalidOperationException: Cannot resolve scoped service 'Microsoft.AspNetCore.Authentication.Cookies.ITicketStore' from root provider.

### ISSUE THREAD

**Issue by jarrettv** [aspnet/AspNetCore#4631]
Is it possible to resolve a scoped service for use with ITicketStore? For example, if I want to use a DbContext to load the ticket data upon renew.

If not, does that mean I need a singleton DbContext?

**Comment by amccool** [comment]
> ITicketStore needs to be a singleton. What you'd do is inject the IHttpContextAccessor into your store and then per request resolve the DBContext from the already scoped request services container.

sorry for the late quote @Tratcher  ---- I didnt see in the ITicketStore docs where it mentions that ITicketStore implementations need to be Singletons

**Comment by Tratcher** [comment]
ITicketStore isn't even automatically resolved from DI, you have to do that manually.

**Comment by amccool** [comment]
oh - I was using this move and it seems to be resolving
```
            services.AddSingleton<ITicketStore, MoviesWebApp.DistributedSqlServerTicketStore>();

            services.AddOptions<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme)
                .Configure<ITicketStore>((options, store) => options.SessionStore = store);
```

**Comment by Tratcher** [comment]
Right, you're manually adding and resolving it. ITicketStore needs to be a singleton in this example because CookieAuthenticationOptions are treated like singletons (per scheme).
