### ISSUE TITLE
How do I change client_id & client_secret in Middleware

### ISSUE THREAD

**Issue by seven1986** [aspnet/AspNetCore#4633]
As before,I have config Google OAuth Client_ID & Client_Secret in Startup.cs.
Then, I want change google oauth Client_ID  & Client_Secret at my custom Middleware.
How can I do that?

**Comment by Eilon** [comment]
Unfortunately there is no direct support for this scenario and we are not planning to make any changes in that area. So, this is left as an operation for developers to solve within their own apps. If you do come up with a good solution to this please let us know.
