### ISSUE TITLE
AspNet.Identity doesn't respect LowercaseUrls

### ISSUE THREAD

**Issue by u-abramchuk** [aspnet/AspNetCore#4640]
Hi,

I have an application base on IdentityServer4 and AspNet.Identity. I use the following configuration to make all URLs lowercase:
```csharp
services.Configure<RouteOptions>(options => options.LowercaseUrls = true);
```
But after the latest update (from Microsoft.AspNetCore.Identity v2.0.1 to v2.1.1) URL pointing to login page '/account/login' started to appear in pascal case like '/Account/Login'. 

After some investigation I found that exact place where this string comes from is [IdentityServiceCollectionExtensions.cs#L53](https://github.com/aspnet/Identity/blob/master/src/Identity/IdentityServiceCollectionExtensions.cs#L53):
```csharp
.AddCookie(IdentityConstants.ApplicationScheme, o =>
            {
                o.LoginPath = new PathString("/Account/Login");
                o.Events = new CookieAuthenticationEvents
                {
                    OnValidatePrincipal = SecurityStampValidator.ValidatePrincipalAsync
                };
            })
```

**Comment by Eilon** [comment]
@JamesNK - in the wonderful world of Endpoint Routing, do you have any thoughts on this?

**Comment by JamesNK** [comment]
That's related to this issue about using LinkGenerator to build paths: https://github.com/aspnet/AspNetCore/issues/4277

I think it falls into a nice to have category, and it hasn't been looked at closely yet.

**Comment by Eilon** [comment]
Cool. We'll leave it assign to you and you can do with it as you please.

**Comment by muratg** [comment]
@JamesNK @Eilon is this to be done in Preview3? If not, could you move it out?

**Comment by muratg** [comment]
(Moving this to MVC as it's more related to routing than cookies.)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
