### ISSUE TITLE
Microsoft Security Advisory:  iOS12 breaks social, WSFed and OIDC logins

### ISSUE THREAD

**Issue by blowdart** [aspnet/AspNetCore#4647]
# Microsoft Security Advisory:  iOS12 breaks social, WSFed and OIDC logins

## <a name="executive-summary"></a>Executive summary

Microsoft is releasing this security advisory to provide information about an incompatibly between iOS12 and some types of authentication. This advisory also provides guidance on what developers can do to remove current security restrictions added by ASP.NET to their applications to become compatible with iOS12.

## Announcement

The original announcement for this issue can be found at https://github.com/aspnet/Announcements/issues/318

## Discussion

Discussion for this issue can be found at https://github.com/aspnet/Identity/issues/1984 for ASP.NET Core Identity

### <a name="how-affected"></a>What has changed

The recent iOS12 update has changed Safari's handling of [SameSite](https://tools.ietf.org/html/rfc6265) cookies. The SameSite attribute allows a developer to control when cookies are sent to a web site, enabling the flow to only occur when requests are from the same site. This standard was introduced to reduce exposure to Cross Site Request Forgery (CSRF) attacks. By default ASP.NET Core 2.0 and later protects its authentication cookies using the SameSite property. The change on Apple's part is not limited to ASP.NET Core applications, it is affecting multiple frameworks and authentication software which relay on HTTP forms in a browser, for example authenticating to a third party via Facebook, Twitter or browser based Open ID Connect (OIDC) mechanism.

Apple have stated they believe [their change is correct behavior](https://bugs.webkit.org/show_bug.cgi?id=188165), and that the fault lies in every other browser's implementation.

While we take no stance on the correctness of browser behavior we feel that removing the SameSite protections would expose our customers, and their customers to a wider risk, as it would remove the protection provided everywhere, for all users, in any browser.

### <a name="how-affected"></a>How do I know if I am affected?

If your users can no longer login to your web application on iOS12 using Safari then you are affected.

### <a name="how-fix"></a>How do I fix this?

Developers can allow iOS12 Safari users to log into their applications by turn off SameSite protection in `ConfigureServices()`.

If you are using ASP.NET Core Identity you disable the protection by configuring cookies with the following code

```c#
services.ConfigureExternalCookie(options =>
{
    // Other options
    options.Cookie.SameSite = SameSiteMode.None;
});
services.ConfigureApplicationCookie(options =>
{
    // Other options
    options.Cookie.SameSite = SameSiteMode.None;
});
```

If you are using cookie authentication without ASP.NET Core identity you can turn off the protection with the following code

```c#
services.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
{
    // Other options
    options.Cookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None;
})
```

If you are using external OIDC providers you may be able to avoid the issue by changing the response mode your provider uses from a POST to a GET request, using the following code. Not all providers may support this.

```c#
.AddOpenIdConnect("myOIDProvider", options => {
    // Other options
    options.ResponseType = "code";
    options.ResponseMode = "query";
};
```

_Note that in making these changes protection is removed for all users and all browsers. You should ensure that all your actions that make state changes are protected with [CSRF anti-forgery mechanisms](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery) built into ASP.NET Core.

#### Rebuilding your application

After making these configuration changes you rebuild your application, test, and redeploy.

### Reporting Security Issues

If you have found a potential security issue in .NET Core, please email details to secure@microsoft.com. Reports may qualify for the .NET Core Bug Bounty. Details of the .NET Core Bug Bounty including terms and conditions are at [https://aka.ms/corebounty](https://aka.ms/corebounty).

### Support

You can ask questions about this issue on GitHub in the .NET Core or ASP.NET Core organizations. These are located at https://github.com/dotnet/ and https://github.com/aspnet/. The Announcements repo for each product (https://github.com/dotnet/Announcements and https://github.com/aspnet/Announcements) will contain this bulletin as an issue and will include a link to a discussion issue. You can ask questions in the discussion issue.

### Disclaimer

The information provided in this advisory is provided "as is" without warranty of any kind. Microsoft disclaims all warranties, either express or implied, including the warranties of merchantability and fitness for a particular purpose. In no event shall Microsoft Corporation or its suppliers be liable for any damages whatsoever including direct, indirect, incidental, consequential, loss of business profits or special damages, even if Microsoft Corporation or its suppliers have been advised of the possibility of such damages. Some states do not allow the exclusion or limitation of liability for consequential or incidental damages so the foregoing limitation may not apply.

### External Links

[Bug 188165 - iOS 12 Safari breaks ASP.NET Core 2.1 OIDC authentication](https://bugs.webkit.org/show_bug.cgi?id=188165)

### Revisions

V1.0 (September 28, 2018): Advisory published.

**Comment by brockallen** [comment]
FYI, here's a different approach to solving this issue, while being able to use same-site cookies.

https://brockallen.com/2019/01/11/same-site-cookies-asp-net-core-and-external-authentication-providers/

**Comment by ilatypov** [comment]
It's sad that the Microsoft-blames-Safari issue has no link to a test.  Just trying to reverse analyze the issue from the text "security advisory" makes me think that either the failures in authentication may occur due to different reasons:

- the browser cached the original `GET /resource` request and therefore entered a loop (I see a work-around by Nicolás Sabena of Auth0 in Safari's bug's [comment 26](https://bugs.webkit.org/show_bug.cgi?id=188165#c26) and by @brockallen here; the work-around addresses browsers *using the cached content by the Location address* on receiving the 302 response at the end of the flow).  Perhaps, the root cause of this lies in the browsers incorrectly *caching the original redirect location* received in response to the original `GET /resource`.  The storing-and-using the original redirect response by following to the location of the IdP may be governed by the `Cache-Control` response header: https://stackoverflow.com/questions/12212839/how-long-is-a-302-redirect-saved-in-browser.
- [Comment 38](https://bugs.webkit.org/show_bug.cgi?id=188165#c38) implies that some SAML cookies may exceed the "cookie size limit".
- I don't know if Microsoft's authentication flows rely on additional cookies (in which case I would understand the suspicion on the SameSite attribute in the additional cookie; the default "lax" behaviour will prevent such cookies from accompanying POST requests across origins).  Perhaps, Microsoft's flows intend to POST the session cookie across domains?  The SameSite's default anti-CSRF intent will prevent that by design.
- The CSRF attack scenario mentioned in the RFC 6749 (The OAuth 2.0 framework) [section 10.12] (https://tools.ietf.org/html/rfc6749#section-10.12) does not rely on cookies at all: the attacker makes the victim user click or get the victim browser's follow a redirect 
   - to the malicious "grant" URL containing the attacker's previously obtained authorization code or 
   - to the malicious "access" URL containing the attacker's previously obtained access token.

**Comment by gusgonnet** [comment]
Hi,

would any of you know of a way to implement the sameSite cookie workaround in a javascript Single Page App (SPA) doing authentication with Azure Active Directory (AAD) using the [ADAL.js library](https://github.com/AzureAD/azure-activedirectory-library-for-js) as per the flow described here?
https://docs.microsoft.com/en-us/azure/active-directory/develop/single-page-application
![image](https://user-images.githubusercontent.com/12150030/53095394-bda1cd00-34ea-11e9-8313-1adaa3c865a5.png)

Thank you,
Gustavo

**Comment by DonKeyHote** [comment]
public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            services.AddMvc(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();

                options.Filters.Add(new AuthorizeFilter(policy));
            })
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            services.ConfigureExternalCookie(options =>
            {
                // Other options
                options.Cookie.SameSite = SameSiteMode.None;
            });
            services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.SameSite = SameSiteMode.None;
            });

            services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
             .AddAzureAD(options => Configuration.Bind("AzureAd", options))
             .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options => {
                 options.Cookie.SameSite = SameSiteMode.None;
             });

        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            //app.UseCookiePolicy();
            app.UseCookiePolicy(new CookiePolicyOptions
            {
                MinimumSameSitePolicy = SameSiteMode.None,
            });
            app.UseAuthentication();
            app.UseMvc();
        }

**Comment by DonKeyHote** [comment]
public void ConfigureServices(IServiceCollection services)
    {
        services.Configure<CookiePolicyOptions>(options =>
        {
            options.CheckConsentNeeded = context => true;
            options.MinimumSameSitePolicy = SameSiteMode.None;
        });
        services.AddMvc(options =>
        {
            var policy = new AuthorizationPolicyBuilder()
                .RequireAuthenticatedUser()
                .Build();

            options.Filters.Add(new AuthorizeFilter(policy));
        })
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

        services.ConfigureExternalCookie(options =>
        {
            // Other options
            options.Cookie.SameSite = SameSiteMode.None;
        });
        services.ConfigureApplicationCookie(options =>
        {
            options.Cookie.SameSite = SameSiteMode.None;
        });

        services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
         .AddAzureAD(options => Configuration.Bind("AzureAd", options))
         .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options => {
             options.Cookie.SameSite = SameSiteMode.None;
         });

    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseExceptionHandler("/Error");
            app.UseHsts();
        }

        app.UseHttpsRedirection();
        app.UseStaticFiles();
        //app.UseCookiePolicy();
        app.UseCookiePolicy(new CookiePolicyOptions
        {
            MinimumSameSitePolicy = SameSiteMode.None,
        });
        app.UseAuthentication();
        app.UseMvc();
    }

I added SameSiteMode.None in multiple areas. There are no changes in ios devices. This is a Razor Pages app with dotnet core 2.2 if that helps.

**Comment by DonKeyHote** [comment]
This worked for me for Azure Authentication on dotnet core 2.2.
Got this from @Tratcher and @thdotnet  Conversation.

services.Configure<CookieAuthenticationOptions>(AzureADDefaults.CookieScheme, options =>
{
  options.Cookie.SameSite = SameSiteMode.None;
});

**Comment by ilatypov** [comment]
Before finding what "works for me", can I reproduce what did not work for anyone?

**Comment by DonKeyHote** [comment]
> Before finding what "works for me", can I reproduce what did not work for anyone?

I created a new .net core 2.2 Razor Pages Web Application from Visual Studio 2017 with organizational authentication (work or school accounts) through Azure AD. After the site was published with IIS, on ios devices it would prompt users to login to the application but loop infinitely once credentials were entered. Solution from @blowdart did not fix the issue. Once I set AzureADDefaults CookieScheme to none, it has not hit that loop again.

**Comment by superdevguy** [comment]
I see this issue is still open, was any fix every implemented or are we just supposed to remove all of the security protection associated with SameSite cookie mode? I find it hard to believe that this is the only solution available. If it is, it's quite disappointing that we need to apply this insecure workaround and rely on anti forgery CSRF checks. Not to say that it isn't important to also implement those checks. Just sad to see that only a workaround was found and no action is being taken aside from that.

**Comment by Tratcher** [comment]
iOS's non-conformant implementation has significantly undermined the usefulness of the SameSite standard. There have been a few proposed mitigations for AspNetCore but we don't have any concrete plans at this time.

**Comment by ilatypov** [comment]
To this day I did not see a test or a sample project that clearly demonstrates a reproducible failure. I noticed that humans tend to enter heated debates when complexity of issues increases.

**Comment by minhhieugma** [comment]
> This worked for me for Azure Authentication on dotnet core 2.2.
> Got this from @Tratcher and @thdotnet Conversation.
> 
> ```
> services.Configure<CookieAuthenticationOptions>(AzureADDefaults.CookieScheme, options =>
> {
>   options.Cookie.SameSite = SameSiteMode.None;
> });
> ```

Above code works for me as well. Thank guys all. You save my life!

>  options.ResponseType = "code";
>  options.ResponseMode = "query";
-> These code bring me to another issue

**Comment by blowdart** [comment]
As same site is now going to be broken by google in other ways, closing, and a new discussion issue will open when the support for the Chrome same-site updates arrives.
