### ISSUE TITLE
SameSite default value update

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/AspNetCore#4655]
According to https://github.com/hapijs/bell/pull/355 (which I found as it links to https://github.com/aspnet/Security/issues/1231) chrome > v65 has fixed their samesite behavior to be in line with other browsers. This should allow `SameSite.Strict` in a few cases again.

I haven't tested this but I do think it's important to see if the default security can be increased again.

**Comment by Eilon** [comment]
Putting in Backlog while we wait for the state of common browsers to settle. In the meantime apps can set the policy themselves.

**Comment by Tratcher** [comment]
iOS has implemented a much different policy than other browsers and that discourages us from making further investments here until they get it sorted out.
Related: 
- https://github.com/aspnet/Announcements/issues/318
- https://github.com/aspnet/AspNetCore/issues/8212

**Comment by blowdart** [comment]
Closing as updates for 3.1 and 3.0 and 2.2 were released for new samesite changes google made
