### ISSUE TITLE
Creating JwtSecurityToken vs using OpenID connect for Web API

### ISSUE THREAD

**Issue by dark2201** [aspnet/AspNetCore#4658]
I currently create JwtSecurityToken and return the token to the user after request to /account/login. I use jwt bearer middleware that handles token verification upon each request. Everything works fine. I don't use OpenID Connect nor OAuth2. 

Does it also mean I use my own protocol?

Now, what would be the advantage over this approach if I used OpenID Connect (through IdentityServer or OpenIddict)?

I'm still new to these protocols and I'm only familiar with JWT (format) itself. 

From my basic understanding OAuth2 or OpenID Connect is used when I want to expose my API to third parties, but what if I need to  secure my private API and I don't want anything else except my programs (native,mobile,web) to have access to it. Would those protocols still help?

I was reading one advantage is Single sign-on (SSO) but if JWT itself can be shared across domains etc. wouldn't it mean I can achieve the same without OpenID?

Please note that I know JWT is format and OpenID Connect is extended OAuth2 protocol standard that use JWT. And IdentityServer, OpenIddict are implementations of these protocols.

**Comment by ajithkumarrai** [comment]
> Essentially, you're implementing your own ROPC-like flow (ROPC = resource owner password credentials), which is the simplest OAuth2 flow (but also the only one not suitable for third-party client authorization). I say "ROPC-like" because it doesn't use standard-compliant parameters and doesn't take things like client authentication into account.
> 
> Whether you go with your custom thing or with an OIDC server that will do it for you, the client part will be roughly the same, as it only consists in sending a HTTP request with the username/password and extracting the access token from the response in both cases.
> 
> > Yes, it will save you a bunch of time writing client side code, but that's offset by the time taken to implement the server side pieces needed via OpenIddict or Identity Server, which would become your login endpoint.
> 
> Well, implementing the ROPC flow is super easy and only requires a few lines of code (at least, with OpenIddict): http://kevinchalet.com/2017/01/30/implementing-simple-token-authentication-in-aspnet-core-with-openiddict/
> 
> If you're afraid of OpenIddict and IdSrv being "too heavy" for your scenario, here's the equivalent of what's done in the blog post using ASOS, the OIDC server handler being OpenIddict, which can be done in a totally stateless way (i.e with no backing DB):
> 
> ```cs
> private static readonly SecurityKey Key = new SymmetricSecurityKey(
>     Encoding.UTF8.GetBytes("your HMAC key, hopefully generated using a crypto-secure RNG"));
> 
> public void ConfigureServices(IServiceCollection services)
> {
>     services.AddAuthentication()
>         .AddOpenIdConnectServer(options =>
>         {
>             options.TokenEndpointPath = "/token";
>             options.AllowInsecureHttp = true;
> 
>             options.SigningCredentials.AddKey(Key);
>             options.AccessTokenHandler = new JwtSecurityTokenHandler
>             {
>                 OutboundClaimTypeMap = new Dictionary<string, string>()
>             };
> 
>             options.Provider.OnValidateTokenRequest = context =>
>             {
>                 if (!context.Request.IsPasswordGrantType())
>                 {
>                     context.Reject(OpenIdConnectConstants.Errors.UnsupportedGrantType);
>                 }
>                 else
>                 {
>                     // Don't enforce client authentication.
>                     context.Skip();
>                 }
>                 return Task.CompletedTask;
>             };
> 
>             options.Provider.OnHandleTokenRequest = context =>
>             {
>                 // Implement context.Request.Username/context.Request.Password validation here.
>                 // Using password derivation and time-constant comparer is STRONGLY recommended.
>                 if (context.Request.Username == "bob" && context.Request.Password == "bob")
>                 {
>                     var identity = new ClaimsIdentity(context.Scheme.Name);
>                     identity.AddClaim(new Claim(OpenIdConnectConstants.Claims.Subject, "Bob"));
> 
>                     var ticket = new AuthenticationTicket(
>                         new ClaimsPrincipal(identity),
>                         new AuthenticationProperties(), context.Scheme.Name);
>                     ticket.SetResources("resource_server");
> 
>                     context.Validate(ticket);
>                 }
>                 else
>                 {
>                     context.Reject(OpenIdConnectConstants.Errors.InvalidGrant);
>                 }
> 
>                 return Task.CompletedTask;
>             };
>         })
> 
>         .AddJwtBearer(options =>
>         {
>             options.TokenValidationParameters.ValidAudience = "resource_server";
>             options.TokenValidationParameters.ValidIssuer = "http://localhost:54540/";
>             options.TokenValidationParameters.IssuerSigningKey = Key;
>         });
> 
>     services.AddMvc();
> }
> ```

I implemented as mentioned above, but while validating webapi endpoint (https://localhost:44383/api/Values) with token i am receiving 401 error.

PFA it is related sample 
[OpenIDdictSample.zip](https://github.com/aspnet/AspNetCore/files/2729195/OpenIDdictSample.zip)

Could you please help me on this

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
