### ISSUE TITLE
CookiePolicyOptions sets minimumsamesitelevel to lax by default and that breaks oauth providers

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#4661]
This happens when you plug-in the cookie policy middleware on the app and use an oauth provider for authentication.

**Comment by Eilon** [comment]
@blowdart - let's discuss when you're back whether we can lower the default to None.

**Comment by muratg** [comment]
Triage: We can drop this to None only if we check ALL the cookies the ASP.NET stack drops to see if they have appropriate value.

**Comment by brockallen** [comment]
Another idea is to change how the remote authentication handler plumbing works in ASP.NET Core handles responses: https://brockallen.com/2019/01/11/same-site-cookies-asp-net-core-and-external-authentication-providers/

**Comment by Tratcher** [comment]
https://github.com/aspnet/AspNetCore/issues/8212
