### ISSUE TITLE
IAuthenticationSchemeProvider needs a TryAddScheme()

### ISSUE THREAD

**Issue by damianh** [aspnet/AspNetCore#4666]
Looking at this example/test to dynamically add authentication schemes at runtime:

https://github.com/aspnet/Security/blob/0959c941b40086b131b1e01d304fc23bb887fdc8/test/Microsoft.AspNetCore.Authentication.Test/DynamicSchemeTests.cs#L137-L143

If the endpoint is invoked twice, it will result in an `InvalidOperationException`: 
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationSchemeProvider.cs#L121

Instead perhaps this method should be `bool TryAddScheme(AuthenticationScheme scheme)` so users don't have to wrap it in a try-catch.

Also it appears that the underlying `_map` should be a `ConcurrentDictionary`?

**Comment by Tratcher** [comment]
Re-opening based on offline discussion:

Extra small. It would be one new overload of this method that doesn’t throw:
https://github.com/aspnet/HttpAbstractions/blob/bc7092a32b1943c7f17439e419d3f66cd94ce9bd/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationSchemeProvider.cs#L136-L156

We might want to wait for C# 8 default interface implementations though (later in 3.0).

**Comment by anurse** [comment]
We have default interface members so we believe this is non-breaking now.

**Comment by HaoK** [comment]
Issues with dim still, moving to preview 8

**Comment by damianh** [comment]
Glad to see this happening :)

**Comment by anurse** [comment]
Contingency plan if we can't get DIM working (having some issues) is to punt to 3.1.

**Comment by anurse** [comment]
We're going to punt on DIM changes due to the limitations (VB support, crossgen issues). Let's move TryAddScheme out to 3.1.

**Comment by HaoK** [comment]
crossgen dim works now in master, still doesn't work in release/3.1, so the fix looks good for 5.0 at least

**Comment by HaoK** [comment]
Added in https://github.com/aspnet/AspNetCore/pull/14448
