### ISSUE TITLE
Clarify behavior of CookieAuthenticationOptions.Cookie.Expiration

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4671]
https://github.com/aspnet/Security/pull/1285 added `CookieAuthenticationOptions.Cookie.Expiration`, a nullable `TimeSpan`, but we still have `CookieAuthenticationOptions.ExpireTimeSpan`. Cookie.Expiration is ignored. We should clarify what Cookie.Expiration is meant to do and how it interacts with ExpireTimeSpan

**Comment by winzig** [comment]
So is this going to be resolved in .NET 3.0? I just spent an hour trying to figure out why my cookies were always expiring in 2 weeks even though I was setting options.Cookie.Expiration to another timespan. I searched for a while, and then finally decided to search the source code where I finally found a clue:

https://github.com/aspnet/AspNetCore/blob/32da2679f86ec0b19c6bcad25ed500ddf5ff845f/src/Security/Authentication/test/CookieTests.cs#L148
