### ISSUE TITLE
Add metadata which says whether or not the type of authentication was persistent

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4675]
For **Antiforgery by default** in MVC - we need a way to know that the type of authentication used was a persistent auth.

This should be implemented such that the non-persistent auth schemes (bearer) make a declaration that they **are not persistent**. The antiforgery infrastructure in MVC will look for confirmation that the scheme is **not persistent**.

**Comment by Eilon** [comment]
@rynowak - at this point we should either do something or close the issue. Given what we've done with APIs, what seems worthwhile?

**Comment by muratg** [comment]
Closing this as there doesn't seem to be a decision on this so far. Please re-open as necessary.
