### ISSUE TITLE
Binding Secure cookies to ITlsTokenBindingFeature

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#4680]
Any protected cookie marked as Secure should also use ITlsTokenBindingFeature as part of its protection.

Today CookieAuth always uses ITlsTokenBindingFeature if it's available, ignoring CookieSecureOption. Check CookieSecureOption before applying ITlsTokenBindingFeature.

Other protected data to consider:
OAuth state field
OIDC state fields
OIDC nonce
Twitter request token

**Comment by Eilon** [comment]
Moving to backlog because it is unclear when we would bring this in.

**Comment by blowdart** [comment]
Closing as it's unlikely token binding is alive any more.
