### ISSUE TITLE
Add OIDC test coverage

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#4681]
OIDC does not have sufficient test coverage. Many tests were removed or disabled due to breaking changes or redesigns. Check our coverage and fill in the gaps.

Note there are some pseudo-functional tests in MusicStore that could be moved here.

Related: https://github.com/aspnet/Security/issues/349 - Move OIDC tests to their own project.

**Comment by anurse** [comment]
This is just reminding us of what we aren't doing. It's not useful to keep open.
