### ISSUE TITLE
Support QUIC

### ISSUE THREAD

**Issue by ststeiger** [aspnet/AspNetCore#4695]
Support QUIC on Kestrel 
Page-load speed (and quality), and therefore QUIC, affect google-ranking. 

> Like HTTP/2, QUIC multiplexes multiple streams into one connection, so that a connection can serve several HTTP requests simultaneously. But HTTP/2 uses TCP as its transport, so all of its streams can be blocked when a single TCP packet is lost—a problem called head-of-line blocking. QUIC is different: Loss of a UDP packet within a QUIC connection only affects the streams contained within that packet. In other words, QUIC won’t let a problem with one request slow the others down, even on an unreliable connection.

Source: https://cloudplatform.googleblog.com/2018/06/Introducing-QUIC-support-for-HTTPS-load-balancing.html

**Comment by gradx** [comment]
3.0 shipped, please reopen

**Comment by davidfowl** [comment]
cc @jkotalik

**Comment by jkotalik** [comment]
I'm drafting an announcement for our plans with QUIC and HTTP/3 for 5.0 soon. Exciting things are coming 😄. I'll re-ping this issue when the announcement is made.

**Comment by jkotalik** [comment]
Announcement here: https://github.com/aspnet/Announcements/issues/393. Going to close this issue for now as it will be eclipsed by other individual issues.
