### ISSUE TITLE
Kestrel ended slowly. And when I run it again, I get an error that the port is in use.

### ISSUE THREAD

**Issue by wxilas21** [aspnet/AspNetCore#4696]
These events are left in the event viewer.
Event ID : 16002
Closing a TCP socket with local port number 50000 in process 3584 is taking longer than expected. The local port number may not be available until the close operation is completed. This happens typically due to misbehaving network drivers. Ensure latest updates are installed for Windows and any third-party networking software including NIC drivers, firewalls, or other security products.  

These events are left in the event viewer.
Event ID: 1002
The program GameServer.exe version 0.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Action Center control panel.
 Process ID: f78
 Start Time: 01d4756a17377dab
 Termination Time: 4294967295
 Application Path: C:\Server\GameServers\GameServer.exe
 Report Id: 87a58e30-e15d-11e8-8217-0ab6b219a55a
 Faulting package full name: 
 Faulting package-relative application ID: 

I need help with what to do.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
