### ISSUE TITLE
Alow bin\Web.config to override Web.config

### ISSUE THREAD

**Issue by jez9999** [aspnet/AspNetCore#4702]
One major issue I continually have with ASP.NET is the inability to perform XDT transformations on my Web.config file when I debug.  I want to hit F5 and get an XDT transformation that inserts config values appropriate for my debugging setup.  It seems to me that a good way to do this would be for the web server to first search for bin\Web.config, which could be the output location for the base Web.config with XDT transformations applied (from a base `Web.Debug.config` file).  If it finds that file, it uses it, otherwise it falls back to the base Web.config.  Could this be implemented?  Then we could press F5, VS does the XDT transformation for our Web.Debug.config, writes it to the bin directory, and the web server uses that when we're debugging.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
