### ISSUE TITLE
Kestral is very slow when posting data

### ISSUE THREAD

**Issue by cibinmathewjose** [aspnet/AspNetCore#4711]
Please get the sample source from  https://github.com/cibinmathewjose/KestrelPostIssue.git 
run the code and post {"Name":"test","Price":1} to http://{machine}:5000/api/products, it will take ~6 seconds.

if you post {"Price":1} to http://{machine}:5000/api/products it will work normally.

The put request endpoint is always slow with machine name url, regardless of the data posted.

Also if you use localhost instead of machine name in url, it will always works normal. 
this is the same issue as #2229

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
