### ISSUE TITLE
Kestrel (or something I don't know) caches my API

### ISSUE THREAD

**Issue by nefcanto** [aspnet/AspNetCore#4713]
I've created a bunch of services using ASP.NET Core. I've hosted them in IIS using AspNetCoreModule. Nowhere I've used caching. In fact, I'm not familiar with the concept of caching at all in ASP.NET Core.

I've published this service to two different servers. Both have this environment:

Windows Server 2012 R2 Standard
IIS 8.5.9600.16384

The problem is that one works just fine, the other caches my API requests. I've compared IIS configuration of two servers by comparing `Windows\System32\inetsrv\config` folders, and they are the same.

Also `Web.config` files are the same on both machines. I'm stuck at this point on how to find and solve the problem. The problem should be environmental, since I've not configured anything related to caching in my codebase. In other words, codebase is the same across two machines. So that can't be the source of the caching problem.

Is Kestrel the culprit here? How can I make sure that Kestrel is not caching my API responses without me knowing it?

This is the response header on when it's not cached:

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Vary: Origin
Server: Kestrel
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://admin.vas.taak.io
Date: Mon, 01 Oct 2018 11:37:44 GMT
Content-Length: 8804

```

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
