### ISSUE TITLE
Route arguments are weirdly decoded

### ISSUE THREAD

**Issue by dustinmoris** [aspnet/AspNetCore#4718]
Hi,

So currently Kestrel seems to have made an odd choice to weirdly decode route arguments.

An ASP.NET Core web application doesn't get to see the real route arguments which a client has sent, but equally doesn't get presented with properly URL decoded arguments either. It doesn't follow any standard decoding algorithm and sort of returns an unexpected result.

For example, a route argument would decode `%3A`, but wouldn't decode `%2F`. This is extremely annoying, because code which works with route arguments doesn't really know what is going on. Is the string already decoded or not? There is also no function in the standard library which would help to correctly decode the remaining encoded parts of a route argument. If the string value would be passed into `WebUtility.UrlDecode` then it would create bugs, because the `+` sign would get decoded twice.

I would like to propose that Kestrel, the web server, shouldn't take the decision to decode any route arguments and leave that responsibility up to the actual framework on top of it (MVC, NancyFx, Giraffe, etc.). As a framework author it would make more sense to give this control to the web framework which might want to see the original URL which a client has actually called.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
