### ISSUE TITLE
[Discussion] Kestrel Connection Adapter Logging Namespace Changes

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#4719]
The logging namespaces for Kestrel's HttpsConnectionAdapter and LoggingConnectionAdapter are changing in 2.2.0.

1. The `HttpsConnectionAdapter` logging namespace is now `Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter`.
2. The `LoggingConnectionAdapter` logging namespace is now `Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.LoggingConnectionAdapter`.

Here's an example HttpsConnectionAdapter log prior to the change:

```
dbug: HttpsConnectionAdapter[2]
      Authentication of the HTTPS connection timed out.
```

And after:

```
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter[2]
      Authentication of the HTTPS connection timed out.
```

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
