### ISSUE TITLE
Add an exception for responses that are prematurely cut off due to their size.

### ISSUE THREAD

**Issue by honkmother** [aspnet/AspNetCore#4728]
This is a "feature" that has plagued me for months, until I realized there was a very easy fix - https://stackoverflow.com/questions/16436533/how-to-modify-the-default-allowed-response-size-settings-for-a-web-api-applicati .

Unless configured, there seems to be a (configurable) upper limit on the response size for JSON strings and responses in general - instead of throwing returning 500 and an exception that tells us the response is too large for the server to handle, it trims the response to the limit and sends it, leading to malformed JSON strings and 〈capslock〉developer frustration〈/capslock〉. 

I feel that an  exception (maybe can be toggled on/off) should be implemented here that at least tells us the server encountered an error instead of sending half of a response that inevitably breaks the client.

🐊

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
