### ISSUE TITLE
Kestrel dies because of Out of Memory exception

### ISSUE THREAD

**Issue by HassanHashemi** [aspnet/AspNetCore#4731]
One of our MVC projects keeps growing memory, and it seems that Garbage collector dose not do anything with it.

The process keeps growing until it is killed by the OS.

`dmesg` outputs this log:

```
[961030.365411] Out of memory: Kill process 3673 (dotnet) score 913 or sacrifice child
[961030.365725] Killed process 3673 (dotnet) total-vm:29592364kB, anon-rss:3565416kB, file-rss:256kB, shmem-rss:0kB
```

**What makes me think that it is related to, GC not working as expected is that, i have periodically called `GC.Collect() ` and memory immediately drops down significantly but still keeps growing in a much slower pace.**

Also GC is running under Server mode.

**Environment Info** 
```
Runtime: .Net Core 2.1
ASP.NET Core 2.1
Web server: Kestrel (directly exposed)
OS: Centos 7

4 Core processor
4GB Memory
```

Also not sure if it any how related, i thought maybe GC dose not recognize memory limits, so here is the output of `ulimit` command:
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15062
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 15062
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
**Notes**
* the apps works as expected on Windows server 2016.
* this may or may not be a duplicate of #1976 but all the issues in there are being tracked separately.

**Update**
Adding entire `dmesg` log [here ](https://gist.github.com/HassanHashemi/d1aa177a9cf552ef0cc8572f84e2dce3)as gist to keep things clear.

**Comment by HassanHashemi** [comment]
![untitled](https://user-images.githubusercontent.com/6805984/50043370-09b63880-0088-11e9-9b4c-e5e5b28a2be5.png)

@benaadams I believe this thing is still there.

**Comment by HassanHashemi** [comment]
So @benaadams what are your thoughts?

**Comment by benaadams** [comment]
@HassanHashemi is that in an idle state? How many requests had it done? (as there doesn't seem too many instances handing around in that diagram)

**Comment by benaadams** [comment]
Unless the number after a # is also an instance count?

**Comment by benaadams** [comment]
Unless the number after a # is also an instance count? However that doesn't seem to make sense as the numbers are way too high :)

**Comment by HassanHashemi** [comment]
@benaadams It's an idle state.
Yes, it dose not leak too much memory. (less than 1GB for 13 million requests)

**Comment by davidfowl** [comment]
@HassanHashemi Took a quick look at there are 2 areas of interest here:
1. StackExchange.Redis - It's capturing the execution context when the initial connection to redis is made. This will end up capturing any AsyncLocals hanging around on the request at the time of connection. That's the call to ReadFromPipe capturing the ExecutionContext that ends up capturing the HttpContext. cc @mgravell 
2. I'm still not sure what's holding onto the ArticleView. I'm still trying to figure out this part of the object graph:

![image](https://user-images.githubusercontent.com/95136/50323950-2a6bfd00-0491-11e9-8677-af3a16812c38.png)

**Comment by davidfowl** [comment]
Are you using the MemoryCache anywhere with these objects?

**Comment by HassanHashemi** [comment]
@davidfowl No memory cached is used in the app, However i see some trace of EF down the graph, might that be related?

**Comment by davidfowl** [comment]
If you can get more data about what's holding onto UrlHelper it would help. What is that `Dictionary<object, object>`? Is it HttpContext.Items? Then which object is holding onto that Dictionary<object,object>? dotMemory for example shows gc roots like this:

![image](https://user-images.githubusercontent.com/95136/50342810-7c387580-04d9-11e9-93e0-2d95cc3923aa.png)

I'd like to see something like this for the UrlHelper

**Comment by HassanHashemi** [comment]
@davidfowl Here is the path.
![image](https://user-images.githubusercontent.com/6805984/50375176-64aed900-060e-11e9-9c3c-7e0d991528a5.png)

**Comment by davidfowl** [comment]
I need to see what’s holding onto UrlHelper. The GC roots of that.

**Comment by HassanHashemi** [comment]
It turns out it's hard to export the path in dotmemory, So here is a two part image:

![1](https://user-images.githubusercontent.com/6805984/50381498-adfa3980-069d-11e9-8bee-17e273eb879b.png)
![2](https://user-images.githubusercontent.com/6805984/50381499-afc3fd00-069d-11e9-8b23-74822e562322.png)

**Comment by HassanHashemi** [comment]
It turns out either Jetbrains guys have not added some thing that is obviously needed for a profiler "export as image!" or i could not find the button for that.
Any way, here is a bunch of screenshots, I will post better pics if necessary.

![image](https://user-images.githubusercontent.com/6805984/50381706-dd5f7500-06a2-11e9-90c5-c8c43de134a1.png)
![image](https://user-images.githubusercontent.com/6805984/50381707-e3555600-06a2-11e9-9bdc-a425f9302d47.png)
![image](https://user-images.githubusercontent.com/6805984/50381708-ec462780-06a2-11e9-89e9-b3b71f259d91.png)
![image](https://user-images.githubusercontent.com/6805984/50381709-f2d49f00-06a2-11e9-91f5-4ba2af9ead5f.png)
![image](https://user-images.githubusercontent.com/6805984/50381710-fbc57080-06a2-11e9-9560-067da1c6213a.png)
![image](https://user-images.githubusercontent.com/6805984/50381712-0849c900-06a3-11e9-9be2-6b6a2ee67700.png)

**And last one (Contains duplicates)**
![image](https://user-images.githubusercontent.com/6805984/50381721-5363dc00-06a3-11e9-822a-777e87f527c3.png)

**Comment by davidfowl** [comment]
OK, hmm I thought we verified that the ExecutionContext wasn't captured on Tasks created as a promises. It seems like the Task\<CompiledViewDescriptor\> here https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Razor/Internal/RazorViewCompiler.cs#L184 is capturing the ExecutionContext (HttpContextAccessor).

 cc @stephentoub @pranavkm

**Comment by davidfowl** [comment]
This will be less of an issue once we backport https://github.com/aspnet/AspNetCore/pull/6036

**Comment by stephentoub** [comment]
I'll look after the new year. Most likely if that is the case, it was a regression introduced in https://github.com/dotnet/coreclr/pull/17407. Can you please open an issue?

**Comment by stephentoub** [comment]
(actually probably https://github.com/dotnet/coreclr/pull/9342)

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
