### ISSUE TITLE
Add IIPEndPointConnectionFeature

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#4732]
Right now the only way to get IP information is to go through the IHttpConnectionFeature which is a bit unfortunate:

```C#
public interface IIPEndPointConnectionFeature
{
    IPEndPoint RemoteEndPoint { get; set; }
    IPEndPoint LocalEndPoint { get; set; }
}
```

**Comment by anurse** [comment]
Let's take a quick look since this may be something we want to take a breaking change for (to rename the shared feature)

**Comment by davidfowl** [comment]
We fixed this differently with a more generic feature as part of https://github.com/aspnet/AspNetCore/commit/04bf1bf32e13d35d4d7f61f9cbeb9bfa22e0c617

**Comment by davidfowl** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [VERSION]
            * ASP.NET Core Runtime: [VERSION]
            * .NET Core Runtime: [VERSION]
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
