### ISSUE TITLE
Convert Write100ContinueAsync to sync

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#4740]
IHttpOutputProducer.Write100ContinueAsync is only ever called synchronously from HttpProtocol.ProduceContinue. It can and should be reimplemented synchronously.

https://github.com/aspnet/KestrelHttpServer/blob/2191327b59f87f23f69fff2ac0dba9e58b67141b/src/Kestrel.Core/Internal/Http/HttpProtocol.cs#L969

**Comment by anurse** [comment]
Way too marginal :)
