### ISSUE TITLE
Libuv.Internal.Networking.UvException: Error -4095 EOF end of file 

### ISSUE THREAD

**Issue by rahul24** [aspnet/AspNetCore#4741]
The following exception is being logged by Kestrel when performing HTTP requests to our application hosted in an Azure Web App. All requests were returning 400 HTTP status. The service was running without any problem from quite a while but all of sudden throwing 400 status and after restarting it all resolved. Do we have anywhere the description of error code published (4095)? 

Version: 2.0.8

```
StackTrace:
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4095 EOF end of file
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerPrimary.PipeReadContext.ReadCallback(UvStreamHandle dispatchPipe, Int32 status)
fail: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[0]
      ListenerPrimary.ReadCallback
```

**Comment by muratg** [comment]
@halter73 are you doing this in the next few days?

**Comment by halter73** [comment]
@muratg Yes.
