### ISSUE TITLE
Support HTTP/2 response headers with END_STREAM, no body

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#4744]
If the response completes without a body there's no reason to send a data frame. Flush the headers with an End_Stream flag.

**Comment by anurse** [comment]
We don't expect to have capacity for this in 3.0. If gRPC wants it to improve performance, you're welcome to have it :) (@jamesnk @juntaoluo @Eilon)

**Comment by anurse** [comment]
Backlogging, as per my comment above. Again, if gRPC has higher priorities here, let us know and we can revisit.

**Comment by JamesNK** [comment]
I believe this is needed to properly support gRPC "Trailers-Only" responses. Some clients require that gRPC status is in the HEADERS frame with end stream set. Kestrel having a separate DATA frame with end stream set makes this not possible.

https://github.com/grpc/grpc-dotnet/issues/241

**Comment by Tratcher** [comment]
Those aren't trailers anymore...

**Comment by JamesNK** [comment]
That's why I air-quoted it 😋

**Comment by anurse** [comment]
@shirhatti confirms that this was verified against a nightly build in gRPC interop tests (cc @JamesNK)
