### ISSUE TITLE
Server unexpectedly returns http status 200 (OK) with empty content in release 2.1.0

### ISSUE THREAD

**Issue by baal2000** [aspnet/AspNetCore#4746]
@halter73 
After upgrading from AspNetCore NuGet package **2.1.0-rc1-final** to **2.1.0-rtm-30787** that [differ](https://github.com/aspnet/KestrelHttpServer/compare/2.1.0-rc1-final...da21fc8) slightly with #2533 and #2562 we noticed instances of 200 server responses containing empty content. This behavior messes with JSON-RPC client functionality. The behavior is intermittent in our production environment. We can not reliably reproduce (i.e. trigger in a controllable manner). 

In our view the change to optional `_streams?.Abort` in https://github.com/aspnet/KestrelHttpServer/pull/2533/commits/6e003d8847040c2c64cb41f0d87bf6c825548ccf

```
            if (error != null)
            {
                 _streams?.Abort(error);	             
            }
```
could have had wider effect than for WebSocket connections only.

The issue #2530 mentions #2533 may or may not be similar and we are not sure about the timing wither it preceded or followed the change.

Note that HttpProtocol.Abort in [dev branch](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel.Core/Internal/Http/HttpProtocol.cs) has remained untouched v.s. [release/2.1](https://github.com/aspnet/KestrelHttpServer/blob/release/2.1/src/Kestrel.Core/Internal/Http/HttpProtocol.cs) leaving `_streams?.Abort` non-optional. It has been changed in #2612 but essentially remained intact.

Is this (the empty response symptom and the differences between the branches) something that you can give some insight or there is a duplicate issue I missed? 

Thanks.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
