### ISSUE TITLE
Config support for SNI

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#4749]
In 2.1 preview2 we added support for SNI:
https://github.com/aspnet/KestrelHttpServer/issues/2357

This is a code only approach and isn't supported by the new config system also introduced in 2.1.

Proposal: See if there's sufficient user demand for supporting SNI from config.

Recommend revisit in 2.2.

**Comment by anurse** [comment]
Backlogging until there is more customer demand.

**Comment by Tratcher** [comment]
Closing as a duplicate of #15144 since that one actually represents a customer.
