### ISSUE TITLE
Benchmark corefx Sockets epoll exhaustion strategy

### ISSUE THREAD

**Issue by tmds** [aspnet/AspNetCore#4751]
When there is a lot of I/O transfer, at some point the epoll thread becomes the bottleneck.

There are two ways to deal with that:
- create multiple epoll threads
- delegate I/O transfer to the threadpoll, so epoll thread only handles notification

corefx does both, implemented in https://github.com/dotnet/corefx/pull/19820 and https://github.com/dotnet/corefx/pull/23115 respectively.
That doesn't make much sense.

It would be nice if we could benchmark the two and keep the one that performs best.

CC @geoffkizer @halter73 @stephentoub @vancem @davidfowl

**Comment by tmds** [comment]
I've benchmarked this in https://github.com/dotnet/corefx/pull/36693 and there was no clear winner.

**Comment by stephentoub** [comment]
Thanks, Tom.
