### ISSUE TITLE
dotnet core 2 app returning 502.3 error

### ISSUE THREAD

**Issue by zhongj2** [aspnet/AspNetCore#4755]
### Description
Occasionally, we are observing our dotnet core 2 application returning 502.3 errors.

The application is been served via IIS and we verified that the application process is indeed running and listening to a port. That exact port number is also been set in by environment variable ASPNETCORE_PORT for that process.

When attempting to telnet to the process on that port number, we are seeing Connect failed error.

### Reproduce
Intermittent, unable to consistently reproduce.

### Environment
Windows Server 2012
IIS 8
Dotnet Core 2

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
