### ISSUE TITLE
Slow response when sending concurrent requests from the same connection

### ISSUE THREAD

**Issue by qazq** [aspnet/AspNetCore#4756]
I have a web API server that implements by ASP.NET core 2.0.

I have a web page that implements by Angular5. The page calls two different API concurrently. Each API response time about 300ms, but If I call API one by one, each response about 20ms. It seems like the request are locked by something?

To verify this issue, I create a Web API project by using default Visual Studio 2017 template.

```cs
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }
  }
```
And a console program that calls API by HttpClient.

```cs
        public static HttpClient _http = new HttpClient();

        static async Task<HttpResponseMessage> HttpGet(string uri)
        {
            var watch = new Stopwatch();
            watch.Start();

            var response = await _http.GetAsync(uri);

            watch.Stop();
            Console.WriteLine("time = " + watch.ElapsedMilliseconds);

            return response;
        }

        static void TestWebApi()
        {
            // call first time to initial the httpClient
            var x = HttpGet("http://localhost:52876/api/values").Result;

            Console.WriteLine("Sync....");
            for (var i = 0; i < 5; i++)
            {
                var r = HttpGet("http://localhost:52876/api/values").Result;
                var j = r.Content.ReadAsStringAsync().Result;
            }

            Console.WriteLine("Async....");
            for (var i = 0; i < 5; i++)
            {
                Task.Run(() =>
                {
                    var id = Guid.NewGuid();
                    Console.WriteLine($"[{id}] send...");
                    var r = HttpGet("http://localhost:52876/api/values").Result;
                    var j = r.Content.ReadAsStringAsync().Result;
                    Console.WriteLine($"[{id}] got response");
                });
            }
        }

        static void Main(string[] args)
        {
            TestWebApi();

            Console.ReadLine();
        }
```

Output:

```text
time = 314
Sync....
time = 38
time = 16
time = 97
time = 16
time = 16
Async....
[382a2624-520c-4ee2-b652-9a22f623263d] send...
[41b61a01-046d-4679-b71b-86976d5ac190] send...
[e2c32f5d-2e16-4e96-a337-a3d8d4dcca6e] send...
[227beb1d-3732-4b73-8cfa-99ab883689a3] send...
[78400e4c-841b-4c83-9936-a13d9acad8bc] send...
time = 298
[227beb1d-3732-4b73-8cfa-99ab883689a3] got response
time = 334
[e2c32f5d-2e16-4e96-a337-a3d8d4dcca6e] got response
time = 358
[78400e4c-841b-4c83-9936-a13d9acad8bc] got response
time = 461
[382a2624-520c-4ee2-b652-9a22f623263d] got response
time = 488
[41b61a01-046d-4679-b71b-86976d5ac190] got response
```

The result matches my production website. The response time of the concurrent request is slow.

P.S I got the same result if I run web API on the IIS server 8.5

**Comment by bilginkilic** [comment]
> This is the log from the server side.
> 
> Call by synchronize
> 
> ```
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 12.1845ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 22.1856ms 200 application/json; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with arguments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 7.259ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 15.2308ms 200 application/json; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with arguments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 8.5591ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 16.1255ms 200 application/json; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with arguments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 7.0577ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 14.6971ms 200 application/json; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with ar
> guments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 6.3281ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 13.9168ms 200 application/json; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values/1
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with arguments (1) - ModelState is Valid
> ```
> Call by asynchronous
> 
> ```
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with arguments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with arguments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with arguments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:52876/api/values
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 145.4706ms
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 114.9856ms
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with arguments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method TestApi.ValuesController.Get (WebApiTest2) with arguments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 216.1646ms 200 application/json; charset=utf-8
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 309.6592ms 200 application/json; charset=utf-8
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 115.6636ms
> info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
>       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 179.9712ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 237.727ms 200 application/json; charset=utf-8
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action TestApi.ValuesController.Get (WebApiTest2) in 282.8264ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 331.2385ms 200 application/json; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 379.6267ms 200 application/json; charset=utf-8
> ```
> The execution time increase from 12.18ms to 282.8ms

How did you get this log on IIS . I need it because >> https://stackoverflow.com/questions/54219294/the-more-request-means-slower-read-from-cached-objects

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
