### ISSUE TITLE
Improve performance of Kestrel functional tests

### ISSUE THREAD

**Issue by mikeharder** [aspnet/AspNetCore#4758]
The Kestrel functional tests (`Kestrel.Transport.Libuv.FunctionalTests` and `Kestrel.Transport.Libuv.FunctionalTests`) take about 1m20s on my machine.  The long poles are:

# Test Discovery (20s)
```
[xUnit.net 00:00:00.0053998] xUnit.net VSTest Adapter v2.4.0-beta.1.build3945 (64-bit .NET Core 4.6.26130.05)
[xUnit.net 00:00:00.6509470]   Discovering: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.FunctionalTests
[xUnit.net 00:00:21.3632566]   Discovered:  Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.FunctionalTests
```

We may need to profile xUnit and/or `dotnet test` to see why discovery is taking so long.  Command to profile:

```
dotnet test --no-build -f netcoreapp2.1 --filter "FullyQualifiedName=foo"
```

# KeepAliveTimeoutTests.TestKeepAliveTimeout (60s)
Measure each of the 6 tasks executed in parallel.  I know some of them take at least 30s.

**Comment by davidfowl** [comment]
This is pretty much fixed now
