### ISSUE TITLE
warn: Microsoft.AspNetCore.Server.Kestrel[22]       Heartbeat took longer than "00:00:01" at "01/31/2018 19:56:53 +00:00".

### ISSUE THREAD

**Issue by cheesebar** [aspnet/AspNetCore#4760]
when i used 'dotnet app.dll' run dotnetcoremvc application on windows server,there only little traffic on this application,There is no response on website when i use browser access the second day,then i pressed enter key in console application,then show list

warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/24/2018 14:22:35 +00:00".
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/24/2018 14:22:37 +00:00".
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/24/2018 14:22:36 +00:00".
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/24/2018 14:22:39 +00:00".
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/24/2018 14:22:38 +00:00".
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/24/2018 14:22:40 +00:00".
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/24/2018 14:22:41 +00:00".

After a while the browser get a normal response. but sometimes is bad

version is dotnetcore 2.0.3

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
