### ISSUE TITLE
Add interop tests to verify that Kestrel's HTTP/2 implementation works with HttpClient's implementation

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#4763]
There are not currently any functional test for the Http2 features. We accidentally disabled the entire feature when merging the https and core packages due to a missing TFM and didn't notice. https://github.com/aspnet/KestrelHttpServer/pull/2224

The big blocker here is the lack of consistent client support. However, even if there's one client on one of the OS's then that would be a good start.

**Comment by anurse** [comment]
We think there's enough support to do this now.

**Comment by anurse** [comment]
@Tratcher to follow up on the status of HTTP/2 support in `HttpClient`.

**Comment by anurse** [comment]
@Tratcher turned the existing tests on again 🎉

We do need some additional interop tests that use Trailers.

**Comment by anurse** [comment]
This issue is now tracking adding tests that use Trailers to the HttpClient interop test suite.

**Comment by Tratcher** [comment]
HttpClient interop to verify:
- [ ] ALPN handshake
- [ ] H2C (via app context switch `AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);`)
- [ ] Response Trailers
- [ ] Reset
  - [ ] Reset after CompleteAsync (kill the request body)
- [ ] Multi-frame request & response headers
- [ ] Settings
  - [ ] Concurrent request limits
  - [ ] Frame size limits
  - [ ] Header table size
  - [ ] Window size
  - [ ] Max header list size
- [ ] Header validation (e.g. Custom host, url encoding, header encoding)

**Comment by anurse** [comment]
Moving to preview9 for now. The bar for test-only changes is super low (basically just tell mode)

**Comment by anurse** [comment]
We can keep churning on this in master for now. We have a lot of tests now, but @Tratcher's list has some things we still want to cover. We'll look at backporting test coverage if it would be helpful.
