### ISSUE TITLE
Put request trailers in a separate collection

### ISSUE THREAD

**Issue by cesarbs** [aspnet/AspNetCore#4771]
Right now we merge them with request headers. They should go into their own collection. There should also be some way (likely a `Task`) to allow an application to wait until trailers have been received.

**Comment by Tratcher** [comment]
Bumping for triage, this needs to happen in 3.0. At a minimum we need to stop putting 1.x headers into the request header collection, it's a safety concern, even if it means they aren't available.

**Comment by anurse** [comment]
Work:
* Remove the trailers from the main headers collection (breaking change)
* Add `IHttpTrailersFeature` and do the needful.

**Comment by Tratcher** [comment]
Announcement: https://github.com/aspnet/AspNetCore/issues/10519

**Comment by Tratcher** [comment]
Covered in unit tests. Almost no clients support request trailers so I'm skipping manual tests.
