### ISSUE TITLE
Razor Components Throttling support for development

### ISSUE THREAD

**Issue by wanton7** [aspnet/AspNetCore#4784]
### Is your feature request related to a problem? Please describe.
No browser currently supports throttling for WebSockets to emulate slow network.

### Describe the solution you'd like
Add support for throttling directly to Razor Components so that developer can emulate slow network during development.

### Describe alternatives you've considered
No alternatives.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @wanton7.
This is not something we plan to do.
