### ISSUE TITLE
The name "WebHost" does not exist

### ISSUE THREAD

**Issue by elciopa** [aspnet/AspNetCore#4787]
### Describe the bug
I get the following error:
The name 'WebHost' does not exist in the current context. As I can see the WebHost 

### To Reproduce
I would like to create a WebApi project using .Net Core 2.2.0.
I'm using the scaffolded solution proposed from Visual Studio. 

Program.cs (which I see is the same as the doc):

```
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
}
```
Throws the following error

![image](https://user-images.githubusercontent.com/3214597/49935976-d4b4b500-fed2-11e8-9013-82b28f8239e1.png)

VS Community 15.9.4
NetCore 2.2.101

**Comment by davidfowl** [comment]
Looks like it might be a resharper issue. Try updating reaharper

**Comment by elciopa** [comment]
thanks for your tip, you're right. 
After disabling it the error disappears.

**Comment by quentingarlan** [comment]
I had the same issue without resharper, could not find any solution but going back to .Net core 2.1.0. It seems that I am not the only one : https://stackoverflow.com/questions/53623730/webhost-doesnt-exist-in-the-current-context-in-asp-net-core-2-2-default-api-tem

**Comment by PaperMixed** [comment]
I had the same problem but I found the solution: In properties of the project select as Target framework one of the .NET Core framework, ex. .NET Core 2.1 then select correct framwork - .NET Core 2.2 
![2 1](https://user-images.githubusercontent.com/26246157/50207385-9f92e180-036e-11e9-87c4-66305814802c.png)
Rebuild project. That's all.

**Comment by elciopa** [comment]
I tried but it doesn't work for me. 

Just to repeat your steps:

1. Change Target Framework to 2.1
2. Save
3. Rechange Target Framework to 2.2
4. Save and Rebuild Projects 

Correct?

**Comment by elciopa** [comment]
No luck even with administrator mode enabled, for the moment I'm switching back to 2.1.

**Comment by PaperMixed** [comment]
> I tried but it doesn't work for me.
> 
> Just to repeat your steps:
> 
> 1. Change Target Framework to 2.1
> 2. Save
> 3. Rechange Target Framework to 2.2
> 4. Save and Rebuild Projects
> 
> Correct?

Yes, steps are correct. But check if in csproj file something has been change after 1 and 3 steps. And make sure that Microsoft.AspNetCore.App (2.2.0) dll is added to the project.
![answ](https://user-images.githubusercontent.com/26246157/50236480-ce36a980-03ba-11e9-99e5-40e7a43859d5.png)

**Comment by elciopa** [comment]
Ok I didn't have that package. 
I don't know how to add it on SDK, I tried to added it via Nuget package, using the command:

PM> `Install-Package Microsoft.AspNetCore.App`


![image](https://user-images.githubusercontent.com/3214597/50277003-a5a6c200-0443-11e9-9489-1bef5e4e4fe8.png)

But nothing has changed. Other advices?
Ar you using the community edition or the professional one?

**Comment by elciopa** [comment]
> > I tried but it doesn't work for me.
> > Just to repeat your steps:
> > 
> > 1. Change Target Framework to 2.1
> > 2. Save
> > 3. Rechange Target Framework to 2.2
> > 4. Save and Rebuild Projects
> > 
> > Correct?
> 
> Yes, steps are correct. But check if in csproj file something has been change after 1 and 3 steps. And make sure that Microsoft.AspNetCore.App (2.2.0) dll is added to the project.
> ![answ](https://user-images.githubusercontent.com/26246157/50236480-ce36a980-03ba-11e9-99e5-40e7a43859d5.png)

Ok I added manually the line:

`<PackageReference Include="Microsoft.AspNetCore.App" />`

to the .csproj file of the project.
Then I also noticed that for new application scaffolded by vs studio 2017 15.9.4 , the .csproj also adds in PropertyGroup:

`<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>`

Rebuilded, and then now no more issues

**Comment by Eilon** [comment]
Glad you got it working!

**Comment by Zenexer** [comment]
@Eilon, could you reopen this?  The instructions on the Microsoft website [explicitly state](https://aka.ms/sdkimplicitrefs) that the target framework shouldn't be referenced with a PackageReference, and you'll see a warning in the console pointing to https://aka.ms/sdkimplicitrefs if you attempt to add it.  Additionally, NuGet package updates will fail once a new framework is released.

**Comment by Zenexer** [comment]
I believe this is caused by issues such as https://github.com/dotnet/core-setup/issues/4350.  The underlying problem is that the correct version of the target framework is unavailable.  This may be caused by a target architecture mismatch, for example.
