### ISSUE TITLE
2.2 IIS InProcess Hosting Question

### ISSUE THREAD

**Issue by twurm** [aspnet/AspNetCore#4795]
### Describe the bug
We aren't quite the bug phase yet, is there any way to tell once the app starts if its being run InProcess vs OutOfProcess in IIS?  Does changing the setting in web.config override setting the value in the csproj?

**Comment by pakrym** [comment]
Is it locally or in Azure? The main difference is that there would be no `dotnet.exe/Application.exe` process running in InProcess case.

**Comment by twurm** [comment]
This would be locally but on a server we we won’t have access to.  So I was hoping there was a way programmatically we could get access to the info. Thanks for the quick response @pakrym.
