### ISSUE TITLE
Cloning this repo creates files that exceed MAX_PATH on Windows

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#4799]
> git.exe clone --progress --recursive -v "https://github.com/.../AspNetCore.git" "C:\Users\...\source\repos\...\AspNetCore"
> 
> Cloning into 'C:\Users\...\source\repos\...\AspNetCore'...
> POST git-upload-pack (gzip 6575 to 3130 bytes)
> remote: Enumerating objects: 210, done.
> remote: Counting objects: 100% (210/210), done.
> remote: Compressing objects: 100% (172/172), done.
> remote: Total 385056 (delta 101), reused 89 (delta 37), pack-reused 384846
> Receiving objects: 100% (385056/385056), 189.84 MiB | 6.77 MiB/s, done.
> Resolving deltas: 100% (297534/297534), done.
> error: unable to create file src/Mvc/test/Mvc.Api.Analyzers.Test/TestFiles/ApiActionsDoNotRequireExplicitModelValidationCheckAnalyzerIntegrationTest/NoDiagnosticsAreReturned_ForApiActionsReturning400FromNonModelStateIsValidBlocks.cs: **Filename too long**
> error: unable to create file src/Mvc/test/Mvc.Api.Analyzers.Test/TestFiles/ApiActionsDoNotRequireExplicitModelValidationCheckAnalyzerIntegrationTest/NoDiagnosticsAreReturned_ForApiActionsReturningNot400FromNonModelStateIsValidBlock.cs: **Filename too long**
> error: unable to create file src/Mvc/test/Mvc.Api.Analyzers.Test/TestFiles/ApiConventionAnalyzerIntegrationTest/DiagnosticsAreReturned_IfAsyncMethodReturningValueTaskWithProducesResponseTypeAttribute_ReturnsUndocumentedStatusCode.cs: **Filename too long**
> Checking out files: 100% (12222/12222), done.
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'
>

**Comment by natemcmaster** [comment]
@ajaybhargavb @pranavkm can we shorten folder names inside MVC's analyzer tests?

@grahamehorner most of us use a shorter prefix, like `C:\src\AspNetCore\` to workaround MAX_PATH limitations, but I still think we should try to avoid this problem.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @grahamehorner.
This is indeed something we need to find a good solution for. We'll see what we can do about this during 3.0 timeline. As for now, @natemcmaster's suggestion regarding using a shorter root path would do it.

**Comment by grahamehorner** [comment]
@mkArtakMSFT if you clone from within vs then the default will be the users folder\source\repos it would IMHO good if this was a symbolic link with a short alias and/or have some global tool that allows the user to change the location that a symbolic link referenced.

**Comment by grahamehorner** [comment]
FYI, while not ideal I have avoided the issue by using group policy to enable log paths and doing the same with `**git config --system core.longpaths true**
`
![ljkov](https://user-images.githubusercontent.com/3924941/49973701-0eff7000-ff2e-11e8-9610-e0ce23d13e13.png)

**Comment by mkArtakMSFT** [comment]
This is done now.
