### ISSUE TITLE
Components Build - error : rzc generate exited with code -2147450730

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#4800]
> C:\DEV\AspNetCore\src\Components\src\Microsoft.AspNetCore.Components.Build\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\blazor\samples\StandaloneApp\StandaloneApp.csproj]
> C:\DEV\AspNetCore\src\Components\src\Microsoft.AspNetCore.Components.Build\targets\RazorCompilation.targets(236,5): error : rzc discover exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\blazor\samples\MonoSanityClient\MonoSanityClient.csproj]
> C:\DEV\AspNetCore\src\Components\src\Microsoft.AspNetCore.Components.Build\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\blazor\samples\HostedInAspNet.Client\HostedInAspNet.Client.csproj]
> C:\Users\local.user\.nuget\packages\microsoft.aspnetcore.components.build\0.8.0-preview1-20181122.3\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\blazor\src\Microsoft.AspNetCore.Blazor.Templates\content\BlazorLibrary-CSharp\BlazorLibrary-CSharp.csproj]
> C:\DEV\AspNetCore\src\Components\src\Microsoft.AspNetCore.Components.Build\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\blazor\benchmarks\Microsoft.AspNetCore.Blazor.E2EPerformance\Microsoft.AspNetCore.Blazor.E2EPerformance.csproj]
> C:\Users\local.user\.nuget\packages\microsoft.aspnetcore.components.build\0.8.0-preview1-20181122.3\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\blazor\src\Microsoft.AspNetCore.Blazor.Templates\content\BlazorHosted-CSharp\BlazorHosted-CSharp.Client\BlazorHosted-CSharp.Client.csproj]
> C:\DEV\AspNetCore\src\Components\src\Microsoft.AspNetCore.Components.Build\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\samples\ComponentsApp.App\ComponentsApp.App.csproj]
> C:\Users\local.user\.nuget\packages\microsoft.aspnetcore.components.build\0.8.0-preview1-20181122.3\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\blazor\src\Microsoft.AspNetCore.Blazor.Templates\content\Components-CSharp\Components-CSharp.App\Components-CSharp.App.csproj]
> C:\DEV\AspNetCore\src\Components\src\Microsoft.AspNetCore.Components.Build\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\test\testapps\TestContentPackage\TestContentPackage.csproj]
> C:\Users\local.user\.nuget\packages\microsoft.aspnetcore.components.build\0.8.0-preview1-20181122.3\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code -2147450730. [C:\DEV\AspNetCore\src\Components\blazor\src\Microsoft.AspNetCore.Blazor.Templates\content\BlazorStandalone-CSharp\BlazorStandalone-CSharp.csproj]
>     0 Warning(s)
>     10 Error(s)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by grahamehorner** [comment]
If you clone the aspnet/aspnetcore repo and try to component solutions using the build script then you’ll get these issues.

**Comment by mkArtakMSFT** [comment]
@grahamehorner, are you still facing this issue?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by raghavendra-udyavar** [comment]
@mkArtakMSFT I see this issue with All new blank blazor project and hit F5 .

**Comment by jcapellman** [comment]
Also saw this with a .NET Core 2.2 app (VS 2019 16.1.1) yesterday.  For others hitting this, doing a **dotnet --info** I realized I only had 3.0 Preview 5 installed.  Installed the latest 2.2.300 SDK and the error went away (just had to rebuild once I installed the 2.2.300 SDK).
