### ISSUE TITLE
Using optional method parameters in F# project

### ISSUE THREAD

**Issue by pavelm** [aspnet/AspNetCore#4811]
Not sure if this is the right repo to post to...

I was converting a C# webapi project to F# using the F# ASP.NET templates. Everything is working great except optional query parameters. I keep getting this error

```
{
    "message": "The request is invalid.",
    "messageDetail": "The parameters dictionary contains an invalid entry for parameter 'start' for method 'System.Threading.Tasks.Task`1[System.Net.Http.HttpResponseMessage] GetVendorFiles(Int32, System.Nullable`1[System.DateTime])' in 'Thor.WebApi.VendorFilesController'. The dictionary contains a value of type 'System.Reflection.Missing', but the parameter requires a value of type 'System.Nullable`1[System.DateTime]'."
}
```

F# function signature:

```
[<HttpGet; Route("")>]
member x.GetVendorFiles( [<Optional; DefaultParameterValue(100)>] count, [<Optional; DefaultParameterValue(null)>] start : Nullable<DateTime> ) =
```

C# function signature:

```
[HttpGet]
[Route("")]
public async Task<HttpResponseMessage> GetVendorFiles(int count = 100,DateTime? start = null)
```

I tracked the issue down to the way ASP.NET extracts default values for controller actions using ParameterInfo. Apparently the F# compiler doesn't compile default values the same way as C# does (even with the DefaultParameterValueAttribute). I couldn't find the same code in this repo but it's in the aspnetwebstack repo: https://github.com/ASP-NET-MVC/aspnetwebstack/blob/0ee98f84b41b6bef6bde6945e2797de9dac7d48a/src/System.Web.Http/Controllers/ReflectedHttpParameterDescriptor.cs#L37

What's the best way or working around this? Would it be some filter that I need to inject or implement my own ParameterBinding?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
