### ISSUE TITLE
Action with (missing) optional Dictionary param, ModelBinder maps all request params to Dict

### ISSUE THREAD

**Issue by senritsu** [aspnet/AspNetCore#4814]
**tldr**
If an optional dictionary parameter is missing in the request, the ModelBinder tries to cram all other parameters into the dictionary. If the parameter is supplied in the request, even as empty or null value, everything works.

**Details**

Given an action like

```
public void SomeAction(string foo, string bar, Dictionary<Guid,string> problematicDict = null) {...}
```

any request with a payload of the form

```
foo = "something"
bar = "something else"
```

results in a `System.FormatException`, as the ModelBinder tries to use `foo` and `bar` as dictionary keys with their respective values for `problematicDict`, but the keys are not valid `Guid` representations.

This can be further illustrated if the dictionary is changed to accept string keys

```
public void SomeAction(string foo, string bar, Dictionary<string,string> problematicDict = null) {...}
```

The same request results in the parameters `foo` and `bar` having the correct values set In addition to that, the dictionary also has a Count of 2, with keys `foo` and `bar` and the values from the request parameters.

**Workaround**

If `problematicDict` is added to the request as a parameter, even with an empty value or `null` as value, everything works just fine. This leads to believe that the default specified in the action is not properly handled.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
