### ISSUE TITLE
InputFormatter, OutputFormatter, and IApiRequestMetadata

### ISSUE THREAD

**Issue by tuespetre** [aspnet/AspNetCore#4821]
I've been having some difficulty with these APIs when trying to use some custom media types.

Here's a recap:
- **InputFormatter**
  - **CanRead**
    `if (parsedContentType.IsSubsetOf(supportedMediaType))` (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Formatters/InputFormatter.cs#L78)
  - **GetSupportedContentTypes**
    `if (parsedMediaType.IsSubsetOf(parsedContentType))` (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Formatters/InputFormatter.cs#L153)
- **OutputFormatter**
  - **GetSupportedContentTypes**
    `if (parsedMediaType.IsSubsetOf(parsedContentType))` (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Formatters/OutputFormatter.cs#L69)
  - **CanWriteResult**
    `if (supportedMediaType.IsSubsetOf(parsedContentType))` (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Formatters/OutputFormatter.cs#L122)

Basically, the `InputFormatter` is liberal in what in can read because of `CanRead`, but when the time comes to use Api Explorer, the custom media type from the `Consumes` attribute does not show up because of `GetSupportedContentTypes`. Meanwhile, the `OutputFormatter` is very conservative and requires developers to either add every possible permutation of a custom media type to `SupportedMediaTypes` in order for it to allow it, or re-implement each formatter (XML, JSON) they wish to use with the custom media type (of course by inheriting and overriding the relevant methods.)

Since the `InputFormatter` will say it `CanRead` _subsets_, I propose that `GetSupportedContentTypes` be modified to include the supplied content type in the `results` list when the supplied content type is a subset of a supported media type. I'm not sure about the `OutputFormatter`, I feel like there may be a good reason I'm not seeing for its current behavior. But for reference, to get around it, I've had to create a custom `OutputFormatter` that extends `JsonOutputFormatter`, which needs an `ArrayPool<char>` and `IOptions<MvcJsonOptions>`, and because formatters are registered on `MvcOptions`, I've also had to declare an `IConfigureOptions<MvcOptions>` class in order to get it all registered... kind of clunky.

**Comment by glennc** [comment]
We will be evaluating this as part of our general swagger improvements issue sometime in 3.0: https://github.com/aspnet/AspNetCore/issues/4854
