### ISSUE TITLE
Remove unnecessary dependencies in Microsoft.AspNetCore.Mvc.Localization

### ISSUE THREAD

**Issue by atuzovic** [aspnet/AspNetCore#4829]
This is proposal related on how Microsoft.AspNetCore.Mvc.Localization package is structured.

Microsoft.Extensions.Localization.Abstractions contains all abstractions that are related to string localization, without any concrete implementation.

If you want to use resource files as resource persistence store, then you state dependency on Microsoft.Extensions.Localization, call AddLocalization extension method on IServiceCollection implementation and you are good to go which is nice and convenient (even though method itself does not indicate usage of resource files).

Otherwise, if you don't want to use resource files, you don't have to reference Microsoft.Extension.Localization package, but instead just Microsoft.Extension.Localization.Abstractions and then you can create your own resource persistence logic.

And that is really nicely done.

Now when it comes to localization in MVC, all of this falls apart because as soon as you add reference to Microsoft.AspNetCore.Mvc.Localization, every single package that has anything to do with the word "localization" is pulled in, including Microsoft.AspNetCore.Localization which is in no way related to the code in Microsoft.AspNetCore.Mvc.Localization as it plays completely different role in localization process (I didn't see any references to request culture providers). 

To test the above statement, comment out Microsoft.AspNetCore.Localization in project.json - Microsoft.AspNetCore.Mvc.Localization will still build without any issues.

So first proposal is to:

**Remove completely the dependency on Microsoft.AspNetCore.Localization as it's not used at all in the code and you still have to enable request localization manually.**

Other part of this issue relates to continuous calls to AddLocalization method in both Microsoft.AspNetCore.Mvc.Localization and Microsoft.AspNetCore.Mvc.DataAnnotations packages.

Previously mentioned separation between Microsoft.Extensions.Localization.Abstractions and Microsoft.Extension.Localization becomes irrelevant when it comes to MVC, since two above mentioned packages reference the latter always, and therefore pull in resource files related logic and register ResourceManagerStringLocalizerFactory as IStringLocalizerFactory by default.

Reason why I am raising this as an issue is because this is not consistent behavior for a developer. 

At certain times you have to explicitely opt in for something, which I believe is the right approach, as other stacks follow the same rule of thumb.

In other situations however, things are pulled in for you and registered behind the scenes and you have to dig through the source code to figure out where and how - just to be able to break existing dependencies and register your own implementations. Even though that can be fun at the times, I am not sure if that was part of your plan.

I understand that removing internal calls to AddLocalization method when view localization / data annotations localization services are registered with IoC container would cause major backwards compatibility issues, but please just consider that as an option.

**EDIT (one more remark):**

Class MvcLocalizationServices contains the following method:

```
public static void AddMvcLocalizationServices(
            IServiceCollection services,
            LanguageViewLocationExpanderFormat format,
            Action<LocalizationOptions> setupAction)
        {
            services.Configure<RazorViewEngineOptions>(
                options =>
                {
                    options.ViewLocationExpanders.Add(new LanguageViewLocationExpander(format));
                });

            services.TryAdd(ServiceDescriptor.Singleton<IHtmlLocalizerFactory, HtmlLocalizerFactory>());
            services.TryAdd(ServiceDescriptor.Transient(typeof(IHtmlLocalizer<>), typeof(HtmlLocalizer<>)));
            services.TryAdd(ServiceDescriptor.Transient<IViewLocalizer, ViewLocalizer>());
        }

```
This method takes in **setupAction** parameter as an input but does not use it for anything.

**Comment by mkArtakMSFT** [comment]
There is going to be no package going forward so this is obsolete now.
