### ISSUE TITLE
Consider some convenience changes for MVC options

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4832]
It would be really nice to be able to write:

```c#
services.AddMvc(options => options.ModelBinderProviders.RemoveByType(typeof(ByteArrayModelBinderProvider));
```

or 

```c#
services.AddMvc().RemoveModelBinderProvider(typeof(ByteArrayModelBinder));
```

Instead of:

```c#
services.AddMvc(options => options.ModelBinderProviders.Remove(options.ModelBinderProviders.OfType<ByteArrayModelBinderProvider>().Single()));
```

See https://github.com/aspnet/Mvc/issues/6160#issuecomment-295296083

---- 
The first option would be expose a custom collection type, the second would be to just add more stuff to the `IMvcBuilder`. Either one of these could work for this scenario, but I think the builder approach could be to basically anything we want to make into a one liner.

**Comment by mkArtakMSFT** [comment]
Closing as we have no capacity to handle this.
