### ISSUE TITLE
Add IAsyncEnumerable support to MVC

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#4833]
**Edit: @rynowak hijacking top post for great justice**

This would include adding support for returning `IAsyncEnumerable<>` from an action method and letting MVC do the buffering for you because giving the data to the formatter.

This would require integrating with JsonResult and ObjectResult

**Comment by pranavkm** [comment]
For 3.0, we're doing a fairly scoped change viz to add support for `IAsyncEnumerable<T>` in MVC. Using https://github.com/aspnet/AspNetCore/issues/11558 to track further work based on the initial issue and ideas suggested in this issue.
