### ISSUE TITLE
CSS link helper tag with fallback class not working with subclasses

### ISSUE THREAD

**Issue by johnwc** [aspnet/AspNetCore#4835]
The [bootstrap-dialog.css](https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.35.4/css/bootstrap-dialog.css) stylesheet does not have any classes that are single non subclasses. The below taghelper is not working.

```html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.35.4/css/bootstrap-dialog.min.css"
      asp-fallback-href="~/lib/bootstrap3-dialog/dist/css/bootstrap-dialog.min.css"
      asp-fallback-test-class="bootstrap-dialog modal-header"
      asp-fallback-test-property="border-top-left-radius"
      asp-fallback-test-value="4px" />
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

**Comment by johnwc** [comment]
Sorry, I did not see your reply from Sep. I've not worked in ASP.Net for a few months, if I do get into a project with it I will come back and open this and do a PR for this update, if that works for y'all?
