### ISSUE TITLE
Add support to create HtmlHelper instances for testing purposes

### ISSUE THREAD

**Issue by drauch** [aspnet/AspNetCore#4843]
We are writing our own tag helpers which make use of `HtmlHelper` internally (e.g., to render an Editor). This seems to be the recommended behavior, see also https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro#tag-helpers-compared-to-html-helpers

For unit testing purposes we could "rather easily" instantiate an HtmlHelper in ASP.NET MVC 5 (e.g., see https://stackoverflow.com/questions/25206507/unit-testing-htmlhelper-extension-method-fails/25216750#25216750). This is no longer the case in ASP.NET Core. Is there a utility or some other easy way to instantiate an HtmlHelper for a unit test?

**Comment by peterson1** [comment]
I'm stuck here as well.
I can't figure out how to create an instance of IHtmlHelper<T> for testing purposes.
Mocking it didn't work.
Did anyone find a way to write unit tests for custom HTML/Tag helpers?

**Comment by drauch** [comment]
We ultimately decided to use an `IHtmlHelper` interface in our tag helpers and simply mock it for our tag helper unit tests. This is somewhat bad, because we can't really test some stuff, e.g., that the correct editor template is rendered, but it is better than no tests for our tag helpers.

**Comment by mkArtakMSFT** [comment]
> We ultimately decided to use an `IHtmlHelper` interface in our tag helpers and simply mock it for our tag helper unit tests. This is somewhat bad, because we can't really test some stuff, e.g., that the correct editor template is rendered, but it is better than no tests for our tag helpers.

This sounds exactly what we would suggest. For the rest we would recommend using integration tests: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0#test-app-prerequisites
