### ISSUE TITLE
Make-method-async code fix breaks ASP.NET MVC action routing after 'Async' suffix is appended to method name

### ISSUE THREAD

**Issue by terrajobst** [aspnet/AspNetCore#4849]
_From @jeremymeng on August 28, 2017 18:31_

**Version Used**: 

**Steps to Reproduce**:

1. create a ASP.NET Core project
2. select MVC template, create the project, and F5 to make sure the home page is shown
3. open HomeController.cs
4. changing return type of `Index()` to `Task<IActionResult>`
5. Add `await Task.Delay(1);` inside `Index()`
6. Invoke code fix to make the method async

Now the method looks like 

```csharp
        public async Task<IActionResult> IndexAsync()
        {
            await Task.Delay(300);
            return View();
        }
```

7. F5
**Actual Behavior**:
HTTP 404

if rename the method back to `Index()` F5 works again.

_Copied from original issue: dotnet/roslyn#21770_

**Comment by pranavkm** [comment]
@Eilon \ @mkArtakMSFT would this entail an announcement or would we just make note of it in the 3.0 migration notes?

**Comment by Eilon** [comment]
Seems pretty minor, so I'd sa not worth it.
