### ISSUE TITLE
Test changing MediaType as a wrapper around MediaTypeHeaderValue

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#4850]
To verify that changing MediaType to MediaTypeHeaderValue, we would like to see:
- Performance difference
- Test impact (how many tests fail)
- Number of modifications

First, we will alter MediaType to wrap MediaTypeHeaderValue. This is probably the easiest way to check if MediaTypeHeaderValue needs extra features, as a lot of the methods are similar, but may not be exactly the same. 
See #5416 and aspnet/HttpAbstractions/issues/825

**Comment by mkArtakMSFT** [comment]
Closing as this has been filed for a while ago and we never found time to do this.
