### ISSUE TITLE
Remove [Obsolete] action result code

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4855]
We have obsolete overrides of `ActionResult.ExecuteResult(...)` that are unused by any of our other code and should be removed in a major release. 

This isn't an API breaking change, but users might have called these methods, which will now no-op.
```
RedirectResult
LocalRedirectResult
RedirectToActionResult
RedirectToPageResult
RedirectToRouteResult
```

**Comment by pranavkm** [comment]
Addressed as part of 88ae930fad4ddbc0a2c7ccaeb2154c39fe13ff6b
