### ISSUE TITLE
LocalRedirectExecutor should redirect to a well known endpoint instead of throwing when the URL is not local

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#4864]
Right now LocalRedirectResult throws when the URL given to it is not local. This is not ideal as it ends up becoming a 500 and its not useful for many applications.
It would be better if instead, it redirected the user to a well known local endpoint (like ~/) by convention or by giving the user the ability to specify it on a per result basis or globally.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
