### ISSUE TITLE
Supporting open generic models in Views

### ISSUE THREAD

**Issue by mansoor-omrani** [aspnet/AspNetCore#4865]
**The story:**

The idea came to my mind when summarizing multiple views using partials. I thought it would be great if we could define partial views with open generic models.

I thought at first to post the idea in ASP.NET uservoice website. When I searched there, I noticed the same idea was suggested a few years ago [https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/2706166-support-for-generics-in-razor-view](https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/2706166-support-for-generics-in-razor-view).

There, @danroth27 had directed users to a new track ( #727 ) in ASP.NET github and asked users to comment practical examples/use cases of the suggestion.

After visiting the issue, I noticed that it was closed, because nobody had given any comment. I didn't know if someone was still allowed to comment on a closed issue or not, but I dared to try it.

I was happy to see @Eilon's quick reply some hours later still welcoming use cases for this idea.

As the scenario I wanted to mention was a little long, he recommended me to post it as new issue.

So, here am I.

The scenario involves multiple pieces of code fragments (C#, Razor views), but I do my best to make it short and only mention the meat.

**Comment by realtorfico** [comment]
I strongly support the need for passing a generic item into the model of a view. This is very much needed in all future versions of Asp.Net Core.

**Comment by mkArtakMSFT** [comment]
This is not something we plan to do.
