### ISSUE TITLE
Update compatibility infrastructure in 3.0

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#4866]
# Summary
The new compatibility infrastructure introduced in 2.1 will need to be updated in 3.0 to rationalize our overall philosophy for breaking behavior changes.

The basic idea is: when we introduce a **change in existing behavior in a minor release**, we make it opt-in to avoid creating barriers for users to update to the latest ASP.NET Core. We make these changes for a good reason, and we believe that the **new behavior is compelling enough** that we want it to eventually become the default.

This item tracks what's needed to make those new things the default 👍 

## Checklist of small things

- [x] Update `MvcCompatiblityOptions.CompatibilityVersion` to point to a new enum value (`Version_3_0`)
- [x] Obsolete all of the `Version_2_X` enum values
- [x] Make `ConfigureCompatibilityOptions` throw when presented with an old value
- [ ] Empty-out all implementations of `ConfigureCompatibilityOptions.DefaultValues`
- [ ] Remove all current uses of `CompatibilitySwitch` including the properties on options types
- [x] Update template to use `Version_3_0`
- [ ] Copy the content of this issue and create a new issue for 4.0 😁 

## Removing old features

Now that you've done all of the above, you should have bunch of code that doesn't compile due to removing properties from options types. Congratulations! We are free of these old behaviors forever. We can delete the code and tests that implement the legacy behaviors.

**Comment by dougbu** [comment]
Part two of three: 708dc5cb5a

**Comment by dougbu** [comment]
Work completed in f113a20dfd
