### ISSUE TITLE
RemoteAttribute and multiple submit buttons don't work together

### ISSUE THREAD

**Issue by habex-ch** [aspnet/AspNetCore#4867]
I have a ViewModel with a Property which uses a RemoteAttribute
```
public class MyViewModel
{
  ...
  [Remote(action: "MyValidationAction", controller: "MyController")]
  public string MyProperty{ get; set; } 
}
```
My form in the View have beside MyProperty multiple submit buttons.

```
<form asp-action="DefaultAction" >
  <input asp-for="MyProperty"  />

  <input type="submit" value="DoDefault" />
  <input type="submit" value="DoSomethingElse" asp-action="OtherAction" />
</form>
```
When I click on the DoSomethingElse-Button the path goes to the DefaultAction instead the OtherAction.

The RemoteProperty itself works fine. The DoSomethingElse-Button works fine if I remove the RemoteAttribute from the myProperty.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
