### ISSUE TITLE
ViewModel DataAnnotation translations not found is base class

### ISSUE THREAD

**Issue by aguerot** [aspnet/AspNetCore#4870]
# Background
I did setup a simple mvc site and enable localization for both EN and FR languages.
The resources are located in a folder named Resources where Views and Models ressource files are stored. *ViewLocalization* and *DataAnnotationLocalization* are both enabled. I use QueryStringRequestCultureProvider to set the current culture. HomeController has a simple Index action that is associated with a model class *HomeViewModel*. This view model inherits from a base classe *BaseViewModel*.

Those classe are defined as such in their respective file: 
`    public class HomeViewModel: BaseViewModel
    {
        [Display(Name = "TITLE")]
        [Required]
        public string Title { get; set; }
    }
`

`   
    public class BaseViewModel
    {
        [Display(Name = "COMMON")]
        [Required]
        public string Common { get; set; }
    }
`

Under *Resources/Models* folder I created 4 resource files (HomeViewModel.en.resx, HomeViewModel.fr.resx, BaseViewModel.en.resx, BaseViewModel.fr.resx). 
Where translations for *Title* property are defined in HomeViewModel.*.resx and translations for *Common* are defined in BaseViewModel.*.resx

# Issue
*HomeViewModel Title* property is properly translate depending on the current culture
However, *Common* is not translated and its key is displayed

# Expected result
Translation of properties with *DataAnnotation* are looked down the inheritance chain.

Am I missing something?

Sample repro project available here: https://github.com/aguerot/l10n-dataannotation

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
