### ISSUE TITLE
Fix model binding testing setup to use the dependent components consistently

### ISSUE THREAD

**Issue by kichalla** [aspnet/AspNetCore#4872]
Example: [Here ](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.TestCommon/TestModelBinderFactory.cs#L29)we create options but this is not present in DI services as `IOptions<MvcOptions>` service.

Example: In [this ](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.IntegrationTests/ArrayModelBinderIntegrationTest.cs#L16)test, we use different instances of services when [getting ](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.IntegrationTests/ArrayModelBinderIntegrationTest.cs#L19)a ParameterBinder and when [getting ](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.IntegrationTests/ArrayModelBinderIntegrationTest.cs#L26) a TestContext.

Just like how an application in general starts with configuring services, and later requests are executed, we should setup the DI container with all the required services in the test and use this across. I can imagine the usage experience might become a bit undesirable but at least we would have the setup correct. 

cc @dougbu

**Comment by pranavkm** [comment]
Closing this. We can always clean up our tests as we go
