### ISSUE TITLE
Localized views with Razor Pages

### ISSUE THREAD

**Issue by MisterGoodcat** [aspnet/AspNetCore#4873]
In Razor Pages, we can inject IViewLocalizer to work with localized resources - good. But sometimes, especially on content-heavy, rather static pages, it would be nice to have location specific views, i.e. `MyPage.en.cshtml` and `MyPage.de.cshtml` etc. 

My expection was that once I configure `AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix, ...)` Razor Pages also would be resolved by their base name, but I quickly realized there might be a problem with how the corresponding PageModel should be used/resolved. I couldn't get this to work at all - is this scenario even supported with Razor Pages?

In any case, I think the corresponding [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) should be more explicit about what's possible with Razor Pages and potential limitations.

**Comment by hishamco** [comment]
While the issue #8207 has been fixed, why we didn't resolve this /cc @pranavkm @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
