### ISSUE TITLE
Remove RazorProject ViewEngine constructor

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#4876]
It's currently marked as obsolete. In the next major release we should remove it.

**Comment by mkArtakMSFT** [comment]
Closing as per @pranavkm this is done! @NTaylorMullen, if that's not the case, please ping.

**Comment by mkArtakMSFT** [comment]
https://github.com/aspnet/Mvc/commit/f80490f99d4e38e1630e8cce739daf1b3a2b96a8

**Comment by NTaylorMullen** [comment]
Nah, this isn't done. I'll take care of it.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/AspNetCore-Tooling/commit/57df0ea9cf71b3424de8b32bcf6e79e7453b57a5
