### ISSUE TITLE
Add support for ViewDataAttribute in Razor views

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#4877]
As part of https://github.com/aspnet/Mvc/issues/6525, one interesting idea was to introduce a new directive + supporting semantics to add ViewDataAttribute to Razor views.

Some ideas:
```
@viewdata string Title

@viewdata string Title "Home Page"
``` 
A possible prereq for this might be revisit the architecture of `RazorView`. Unlike controllers and Razor Pages which have a way to control behavior and lifecycle without having to bake things in via filters, `RazorView` does not a similar mechanism. It would be worth while to see if we could bestow upon it traits similar to filters that let you manipulate execution without having to build it in.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
