### ISSUE TITLE
Plugin System—Providing PartialViewResult with no Model

### ISSUE THREAD

**Issue by ghost** [aspnet/AspNetCore#4886]
Could be related:
https://github.com/aspnet/Mvc/issues/6984
https://github.com/aspnet/Home/issues/343
https://github.com/aspnet/Mvc/issues/4572#issuecomment-216351033

What about providing `RenderPartialAsync/RenderPartialCoreAsync` versions without `object model, ViewDataDictionary viewData`?
Coupled with Application Parts, we would have, out of the box, everything ready to add a Plugin System.
(Each Plugin with its own MVC, embedded in the "webapp-host" pages.)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
