### ISSUE TITLE
Razor tooling broken for ClassLibrary  on Visual Studio for mac

### ISSUE THREAD

**Issue by nukedbit** [aspnet/AspNetCore#4889]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):

Tried with my own project but found the same issue as with the example repo from docs.

https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/razor-pages/ui-class/samples/cli

#### Description of the problem:

When running the project from Visual Studio for Mac or Jetbrains Rider if you try to access the feature page inside the classlib you will get a 404. But if you execute the same code from command line everything works as expected.

**Comment by mkArtakMSFT** [comment]
Closing this as this is external and hopefully already fixed.
