### ISSUE TITLE
IUrlHelper.Link generation from action names

### ISSUE THREAD

**Issue by Sigvaard** [aspnet/AspNetCore#4890]
Currently `IUrlHelper.Link` allows for generating absolute URLs when passing to it [route names which must be unique application-wide](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.0#route-names). 

This method looks like this: `string Link(string routeName, object values)` and this is currently the only official way when implementing HATEOAS or any hypermedia format.

[**This doesn't work when someone works with generic controllers**](https://stackoverflow.com/questions/48633939/route-name-for-httpget-attribute-name-for-base-generic-controller-class-in-asp-n).

It would be nice if absolute URL could be generated using action name which should always work even with derived controllers with the same action method names.

Currently I solved it with extension defined in my project:

```csharp
public static class UrlHelperExtensions
{
    /// <summary>
    /// Generates an absolute URL for the specified <paramref name="actionName"/> and action
    /// <paramref name="values"/>, which contains the protocol (such as "http" or "https") and host name from the
    /// current request.
    /// </summary>
    /// <param name="actionName">The name of the action that is used to generate URL.</param>
    /// <param name="values">An object that contains action values.</param>
    /// <returns>The generated absolute URL.</returns>
    public static string LinkAction(this IUrlHelper urlHelper, string actionName, object values)
    {
        var httpContext = urlHelper.ActionContext.HttpContext;
        return urlHelper.Action(new UrlActionContext()
        {
            Action = actionName,
            Protocol = httpContext.Request.Scheme,
            Host = httpContext.Request.Host.ToUriComponent(),
            Values = values
        });
    }
}
```

**Comment by TKharaishvili** [comment]
@mkArtakMSFT 
Sent a new PR - https://github.com/aspnet/AspNetCore/pull/4960, but one of the CI jobs failed. Not sure how to proceed from here.

**Comment by TKharaishvili** [comment]
@dougbu I understand the not pushing one's pull requests idea, I also understand that there's a ton of stuff to get done and everyone's incredibly busy. But I still have to say that the lack of attention to this particular issue is a bit discouraging. The fact that three different people have been sending PR-s, hoping to have contributed but none of them have been able to do so so far, kind of demonstrates my point.

Again, I don't mean to be annoying here. I just always get hyped up by all these Microsoft conferences talking about open source and contributions from the community. And would like to help out. :blush:
