### ISSUE TITLE
Make ControllerBase.User virtual for unit testability.

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#4893]
This issue is to track a repo wide impacting changes:
### Remove the compatibility switches
 - [x] Remove compat switch for Enum DataAnnotation localization. In #7748 we decided to fix the fact that Enum localization didn't use DataAnnotationLocalizerProvider behind a compat switch because it was a breaking change. For 3.0.0 we should remove that compat switch and only support the new behavior (usage of DataAnnotationLocalizerProvider).

### Remove all the obsolete methods
- [x] See https://github.com/aspnet/Mvc/issues/6497

### Unit testing cleanup
- [ ] Make `ControllerBase.User` virtual for unit testability.

**Comment by mkArtakMSFT** [comment]
@pranavkm, what is left here? Are some of these listed items done already?

**Comment by pranavkm** [comment]
> Make ControllerBase.User virtual for unit testability.

I think that's the only one. I'll update the title

**Comment by pranavkm** [comment]
Looking at "Make ControllerBase.User virtual for unit testability.", it's fairly trivial to assign the `User` property using `ControllerContext`. In addition, none of the properties on the `ControllerBase` type are virtual. I'm going to close this until we get more feedback here.
