### ISSUE TITLE
Add client code generation from OpenAPI documents

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#4896]
#### Is this a Bug or Feature request?:
Feature request

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
See comments in aspnet/specs#159 and aspnet/specs#161 about client code generation for services described using OpenAPI. The most specific comments are in the **API client generation (C# & TypeScript)** section of aspnet/specs#161

#### Description of the problem:
With a focus on MSBuild integration, build one or more wrappers for tools that can generate client code for a service described using OpenAPI. This includes:
- OpenAPI document available at a URI
- OpenAPI document available in a file on disk
  - This may be treated as a derivative case of URIs. Could also require some special-casing. For example, though not required initially, we may eventually want to refresh clients in a running application when the OpenAPI document changes i.e. file watching / cache flushes similar to how we handle .cshtml file changes at runtime.
- Project-to-project references that indicate the "other" project can provide an OpenAPI document
  - Most general case i.e. something independent of _how_ that document is produced may be a way to start a project, use a described URI to download the OpenAPI document, then generate a client for that document.
  - As mentioned in aspnet/specs#161, an "inside man" approach may also be useful when tighter integration with whatever generates the OpenAPI document may be helpful.

#### Code generation itself
To the extent possible, will outsource the exact OpenAPI to C# or TypeScript conversion. This interface is likely to be behind a small MSBuild `Task` that can be easily overridden or a set of properties that control the exact `Exec` task used to perform code generation.

#### Inspirations to investigate
- [x] https://github.com/aspnet/scaffolding
  - Scaffolding provides a relatively simple approach for wrapping very different code generators into a common command-line UI. Though the lower (Razor-based) code generators are likely to be irrelevant, this high-level integration may provide an intuitive CLI for our users. Likely not needed until we're done providing MSBuild itegration.
- [x] Add Service Reference
  - What artifacts remain in the project after a service reference is added? Can we reuse some of these artifacts for generator-to-project and generator-to-URI integration?
- [x] `<Compile>` and `<EmbeddedResource>` links
  - Can we reuse some of these artifacts and their specific metadata for generator-to-project and generator-to-URI integration?
  - If we decide to do something completely different on one side or the other, what inspiration can we take from the `<Compile>` and `<EmbeddedResource>` linkage approach

**Comment by mkArtakMSFT** [comment]
Moved to 3.0 as this is the uber tracking issue. The work is still happening in preview milestones.

**Comment by dougbu** [comment]
@mkArtakMSFT though I've reset the checkboxes [above](https://github.com/aspnet/AspNetCore/issues/4896#issuecomment-419576178) to reflect what work is complete, this issue overlaps the [Client Code Generation project](https://github.com/orgs/aspnet/projects/21). Suggest we close this and just track the work in that project. Any objection?

**Comment by Eilon** [comment]
@dougbu / @mkArtakMSFT - is this a PRI-0 bug, and is it in the correct milestone?

**Comment by dougbu** [comment]
This is a tracking bug for the overall service reference feature. I suggest we close it because we now have a project that makes it more obvious what's going on: https://github.com/orgs/aspnet/projects/21

@mkArtakMSFT any objections to closing this?

**Comment by StevenRasmussen** [comment]
Hmmm... I get a 404 when trying to go to the new project. Should I be able to see it? Or is it internal or something?

**Comment by dougbu** [comment]
@StevenRasmussen the project is visible only to those in the organization. What information were you looking for?

**Comment by StevenRasmussen** [comment]
@dougbu, nothing in particular. I was just tracking this issue and now that it’s closed due to this other project I was wanting to see if there was a better issue to track in that project. Ultimately I’m just trying to track any progress regarding client generation with .Net Core (which I thought this issue was about). Is there a better issue to be tracking? Thanks

**Comment by dougbu** [comment]
> Is there a better issue to be tracking?

I suggest following the issue or issues of most interest to you. For example, #7639 may be worth following if you're looking for tooling features or #8242 if you want to generate Open API documents in your ASP.NET Core MVC projects.
