### ISSUE TITLE
Remove Roslyn types from the API surface of ASP.NET Core 3.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#4900]
We’re planning on building reference assemblies for ASP.NET Core 3.0 and putting them in a targeting pack. We would like to be able to remove Roslyn's types from the API surface of Razor/Mvc so we do not need to put a Roslyn ref assembly in the aspnet targeting pack.

Proposed changes:

* In 2.2, obsolete APIs which use roslyn types and provide a replacement which does not use Microsoft.CodeAnalysis types directly. The implementation can map our types into roslyn, but that should be internal implementation detail. For example, https://github.com/aspnet/Mvc/blob/a67d9363e22be8ef63a1a62539991e1da3a6e30e/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/MetadataReferenceFeature.cs#L17 
* In 3.0, remove the publicly visible Microsoft.CodeAnalysis types completely

cc @pranavkm @rynowak

**Comment by pranavkm** [comment]
Addressed as part of https://github.com/aspnet/Mvc/commit/f80490f99d4e38e1630e8cce739daf1b3a2b96a8
