### ISSUE TITLE
Built in File Validation (Feature Request)

### ISSUE THREAD

**Issue by mattferderer** [aspnet/AspNetCore#4903]
#Feature Request

As noted in the [docs](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/upload-files?view=aspnetcore-2.1#add-a-helper-method-to-upload-files) uploading files & validating them forces the developer to check for several validations & security threats. Any chance this could be simpler & built in somewhat to encourage best practices for common types of file uploads?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
