### ISSUE TITLE
UrlResolutionTagHelper shoul have an asp-absolute-url attribute

### ISSUE THREAD

**Issue by zippy1981** [aspnet/AspNetCore#4906]
What I'd like to see is as follows.

If I have a tag in razor templates like `<img src="~/cats.png" asp-absolute-url="true">`, on a web app that IIS is serving from `http://whatever.domain/someroot` I would like the generated link to be `<img src="http://whatever.domain/someroot/cats.png" asp-absolute-url="true">` instead of `<img src="http://whatever.domain/someroot/cats.png" asp-absolute-url="true">`.

Basically, code changes would be around here:
https://github.com/aspnet/Mvc/blob/a67d9363e22be8ef63a1a62539991e1da3a6e30e/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs#L147 

Why do I want this? Well I'm using Razor pages to write a custom login page Azure B2C. The way B2C works is it takes my custom login URL, reads that html as an Ajax call, and then injects it, with some customization into the login page served at `https://login.microsoftonline.com` Therefore relative URLs for the img and css don't work. Since I have a dev and production tenant, and want to be able to test out changes to the login page, I don't want to hard code the img and css urls.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
