### ISSUE TITLE
Route Localizer ( Area, Controller and Action Names )

### ISSUE THREAD

**Issue by caioliberali** [aspnet/AspNetCore#4909]
#### Is this a Bug or Feature request?:

Feature request

#### Description of the problem:

As ASP Net Core already implements StringLocalizer and ViewLocalizer, it would be great if it implemented "RouteLocalizer" so that an application could be fully localizable.
Example:

**[ControllerNameLocalizer(**"Resource.Key"**)]**
**[ActionNameLocalizer(**"Resource.Key"**)]**

```csharp
public class HomeController : Controller
    {
        [ActionNameLocalizer("About")]
        public IActionResult About()
        {
            return View();
        }
    }
```

localhost:5000/Home/**About** ( en-US )
localhost:5000/Home/**Sobre** ( pt-BR )

**Comment by fabercs** [comment]
@mkArtakMSFT any activity on that? Or anyone could provide a workaround to support route localization?

**Comment by hishamco** [comment]
@caioliberali @fabercs hopefully I find time to implement this and write a blog post about it ..

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
