### ISSUE TITLE
XML Model State Validation

### ISSUE THREAD

**Issue by saibaskaran57** [aspnet/AspNetCore#4917]
#### Description of the problem:
On JSON content-negotiation formatting, all exception are wrapped into a ModelState validation which provides flexibility for each controllers to decide the handling on the bad input models. 

#### Steps to reproduce
1) Configure XML Formatters for content-negotiation on .NET Core Web API
```
builder.AddMvcOptions(options =>
{
       options.InputFormatters.Add(new XmlSerializerInputFormatter(options));
       options.OutputFormatters.Add(new XmlSerializerOutputFormatter());
});
```

2) Submit an invalid XML input(e.g. invalid XML root)

**C# Model**
```
[DataContract(Namespace = "")]
[XmlRoot("Request")]
public class Request
{
        [Required]
        [DataMember]
        public string Attribute{ get; set; }
}
```
**Client Input(take note on XML root)**
```
<Request1>
 <Attribute>attribute1</Attribute>	
<Request1>
```
3) XML formatter will throw **InvalidOperationException** which does not propagate down to filters/controllers and Exception Middlewares will catch the exceptions with a message - _There is an error in XML document_

#### Question:
Are there any plans in roadmap to have the similar handling for ModelState wrapping on XML Serialization?

**Comment by dougbu** [comment]
be7dfa30af
