### ISSUE TITLE
Support CRUD with strongly typed sorting, filtering and pagination (paging) out of the box

### ISSUE THREAD

**Issue by snebjorn** [aspnet/AspNetCore#4918]
#### Feature request:
Support sorting, filtering and pagination out of the box.

Pretty much all API's need this, unless you're doing a simple demo. So instead of every developer having to invent and implement these standard feature I think it would be greatly beneficial if this came with the framework.

You already have some work you can draw on. https://github.com/OData/WebApi already give you access to sorting, filtering and pagination via the `[EnableQuery]` attribute. But OData might not be suitable for everyone.

The current documented way of doing the above is relying on `switch`ing on strings. 

> ```csharp
> public async Task<IActionResult> Index(
>     string sortOrder,
>     string currentFilter,
>     string searchString,
>     int? page)
> {
>     ViewData["CurrentSort"] = sortOrder;
>     ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
>     ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
> 
>     if (searchString != null)
>     {
>         page = 1;
>     }
>     else
>     {
>         searchString = currentFilter;
>     }
> 
>     ViewData["CurrentFilter"] = searchString;
> 
>     var students = from s in _context.Students
>                    select s;
>     if (!String.IsNullOrEmpty(searchString))
>     {
>         students = students.Where(s => s.LastName.Contains(searchString)
>                                || s.FirstMidName.Contains(searchString));
>     }
>     switch (sortOrder)
>     {
>         case "name_desc":
>             students = students.OrderByDescending(s => s.LastName);
>             break;
>         case "Date":
>             students = students.OrderBy(s => s.EnrollmentDate);
>             break;
>         case "date_desc":
>             students = students.OrderByDescending(s => s.EnrollmentDate);
>             break;
>         default:
>             students = students.OrderBy(s => s.LastName);
>             break;
>     }
> 
>     int pageSize = 3;
>     return View(await PaginatedList<Student>.CreateAsync(students.AsNoTracking(), page ?? 1, pageSize));
> }
> ```
> source: https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.0

While versatile it's rather cumbersome/annoying to write and maintain. Just imagine an entity where you'd want to sort and filter on 10 properties and not just do it on single properties but do stuff like (pseudo example) `/resource?filter=PropA=foo & sort=PropB,desc & sort=PropC`. That's a nightmare to write.

Why can't we have something like this:

```csharp
public PagedResult<Foo> Get(QueryParams<Foo> params)
{
    var filteredSortedPagedFoos = _db.Foos.ApplyQuery(params);
    return Ok(filteredSortedPagedFoos);
}
```

While this might be a bit over simplified it should demonstrate the "out of box" feeling I'm looking for :)

I basically want something similar to what Spring Boot has "out of the box". 

```java
@RepositoryRestResource
public interface FooRepository extends JpaRepository<Foo, Long> {}
```

This code snippet gives me a fully functional CRUD controller with paging and sorting. Not filtering though. While I don't advocate Spring Boot because it's absolutely terrible compared to ASP.NET Core that particulier feature is pretty cool. Though it's rather limited and has all sorts of problems - as does everything with Spring Boot... Anyway...

Last but not least. The implementation should take DTO usage into account.

I know there are some packages that try to solve this "problem". I haven't found one that fully solves it. Since it's something every API or MVC site needs I think it would be handy with a default way to implement it.

**Comment by glennc** [comment]
Moving to backlog because it's a substantial spec that we don't have planned for any of the future releases we've talked about.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
