### ISSUE TITLE
ViewEnginePath doesn't handle blackslashes

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#4931]
This line https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Internal/ViewEnginePath.cs#L32

will fail if the second part starts with a backslash. Though they are expected as we can see in the `PathSeparator` field.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
