### ISSUE TITLE
LinkGeneration for Razor Pages seems to be broken in MvcSandbox \ master

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#4933]
* Run `MvcSandbox` sample from this repo

**Expected**

Link says `/PagesHome` 

**Actual**

Link says `/endpoints?page=%2FPagesHome`

**Comment by JamesNK** [comment]
I'm not sure exactly what change fix this but sandbox now correctly writes link as `/PagesHome`.
