### ISSUE TITLE
Unwrap reflection exceptions when doing reflection on user code

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#4934]
See https://github.com/aspnet/Mvc/issues/8531#issuecomment-426850989

The suggestion is to catch `LoaderExceptions` etc when loading user types and unwrap it to produce a more meaningful error.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
