### ISSUE TITLE
Custom naming when binding nested objects as properties of a model in controllers actions

### ISSUE THREAD

**Issue by andrecarlucci** [aspnet/AspNetCore#4935]
Hi guys,

I'm creating another API with .net core mvc 2.2.
Every time we have some date as a parameter, we follow the same behavior. I need a date start, date end or a relative time info as parameter (today, yesterday, this month, last month, etc).

So imagine a bill report and I want to bring all bills with reference date between X and Y, but I also want to filter by generated bill date between Z and W.

A possible model for just the date related parameters:

```cs
public class DateInfo {
	public DateTime? DateStart { get; set; }
	public DateTime? DateEnd { get; set; }
	public RelativeTime? RelativeTime { get; set; }
}
```

So far so good. My hope was to use that in my request models:

```cs
public class MyModel {
	[FromQuery]
	public DateInfo Reference { get; set; } = new DateInfo();

	[FromQuery]
	public DateInfo Generated { get; set; } = new DateInfo();
       
        //other
}
```

Swagger will generate the api explorer correctly using the namespace to get to the properties. Binding works as well:

- Reference.DateStart
- Reference.DateEnd
- Generated.DateStart
- Generated.DateEnd

However:

That's ok for Razor pages, but as this is an API, and it's not our standard to have "."s in our parameters. 
It's much more popular on REST APIs to use hyphen, not camelcase, dots or underscores as words delimiters.
Also, I loose the ability to lowercase the property names. Ex:

```cs
public class DateInfo {
	[FromQuery(Name = "date-start")]
	public DateTime? DateStart { get; set; }
	public DateTime? DateEnd { get; set; }
	public RelativeTime? RelativeTime { get; set; }
}
```

That will break everything, as having two properties of this same class in a parent model object will combine both DateStart (parent property's name is not applied anymore).

So the feature would be a way to:

1 - ability to replace the "." with whatever I want (in my case, hyphen) when creating the map to the property
2 - change the external property name to a custom one without breaking the classe hierarchy

So with attributes like this:

```cs
public class MyModel {
	[FromQuery(Name = 'reference')]
	public DateInfo Reference { get; set; } = new DateInfo();

	[FromQuery(Name = 'generated')]
	public DateInfo Generated { get; set; } = new DateInfo();
}


public class DateInfo {
	[FromQuery(Name = "date-start")]
	public DateTime? DateStart { get; set; }
	[FromQuery(Name = "date-end")]
	public DateTime? DateEnd { get; set; }
}
```

The final endpoint parameters would be:
- reference-date-start
- reference-date-end
- generated-date-start
- generated-date-end

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
