### ISSUE TITLE
Allow throwing HttpResponseException from MVC (non WebApiCompatShim) controllers

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#4937]
Based on discussion in https://github.com/aspnet/Mvc/issues/8570#issuecomment-431892499

**Comment by glennc** [comment]
Reconsider after 3.0

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
