### ISSUE TITLE
RazorPages do not respect HtmlFieldPrefix

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#4938]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
In any RazorPage add: 
```
@{
    ViewData.TemplateInfo.HtmlFieldPrefix = "Prefix";
}

<form>
    <input asp-for="SomeModelProperty" />
</form>
```

#### Description of the problem:
The generated input tag helper does not respect the `Prefix` field prefix.

This works: `ViewContext.ViewData.TemplateInfo.HtmlFieldPrefix = "Prefix";`

@pranavkm said he had an idea as to why.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
