### ISSUE TITLE
Fix $(ServiceProjectReferenceCheckIfNewer) not working

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#4941]
#### Is this a Bug or Feature request?
Enhancement that's part of #4896

#### Description of the problem
Users can currently set the `$(ServiceUriReferenceCheckIfNewer)` property to `false` (default is `true`) and disable downloading for all `<ServiceUriReference>` items in their project. However
1. The existing `$(ServiceProjectReferenceCheckIfNewer)` and `$(ServiceFileReferenceCheckIfNewer)` properties aren't wired up (oops).
2. Would be better to be able to disable document retrieval and code generation on a per-item basis e.g. `<ServiceUriReference ... CheckIfUriIsNewer="false" CheckIfDocumentIsNewer="true" />`.

Should wire up the existing properties (renamed) as defaults for the new metadata. And, should use the new metadata in our glue code i.e. [Microsoft.Extensions.ApiDescription.Design.targets](https://github.com/aspnet/Mvc/blob/7c6823312540c72a0579f4a4b2e8357b1df42de8/src/Microsoft.Extensions.ApiDescription.Design/buildMultiTargeting/Microsoft.Extensions.ApiDescription.Design.targets).

This issue is somewhat related to #8567.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`
See the [Microsoft.Extensions.ApiDescription.Design](https://github.com/aspnet/Mvc/blob/7c6823312540c72a0579f4a4b2e8357b1df42de8/src/Microsoft.Extensions.ApiDescription.Design/) project which is scheduled to ship soon.

**Comment by glennc** [comment]
This is bug is now just about number 1 in the description. Updating title to represent that.

**Comment by dougbu** [comment]
Closing this issue because document and code generation occurs much less frequently with the new design. While doing unnecessary work should be avoided, the complications involved in detecting unchanged files make this work item less palatable. Will wait for customer feedback.

**Comment by dougbu** [comment]
See also #4913 (which is currently on the backlog) because it covers the most important part of this feature
