### ISSUE TITLE
Generated files re-appearing without explicit build

### ISSUE THREAD

**Issue by glennc** [aspnet/AspNetCore#4944]
If I delete a generated client file then it will reappear immediately. My theory for this was that changing the files in the project was causing a design-time build to happen.

**Comment by glennc** [comment]
From discussion today: Implement ability to either generate files during design time build or not. Once we have that configuration (A property, we think global to the project is OK) we will play with the feature both ways and see which experience we like better for the default.

**Comment by dougbu** [comment]
ce8f053af7e9
