### ISSUE TITLE
Change default document directory to obj

### ISSUE THREAD

**Issue by glennc** [aspnet/AspNetCore#4945]
Today the directory that we store the API document is empty, meaning that we put it in the root of the project. For this type of asset, one that is purely used to make sure we don't redo work we don't need to, I think obj is a better default.

**Comment by glennc** [comment]
1. Is it fine to leave the code generation default to the root of the client project? Yes.
2. Will users by default check the documents in on the server project? Because if yes, we should put it in root. I think we should start with no until people tell us otherwise. So the server doc would go to into obj or somewhere not visible by default.

**Comment by dougbu** [comment]
ce8f053af7e9 addresses code generation location. Will add a note to remind me to include documents location in #8242
