### ISSUE TITLE
Add IDocumentProvider service to Swashbuckle

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#4948]
#### Is this a Bug or Feature request?
Enhancement related to #4896

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project)
The overall aim of in-progress work in ASP.NET Core 3.0 is to give customers simple ways to annotate their project files for automated code generation during every build (as source API descriptions change). This issue is about including Swashbuckle in that new goodness.

The ASP.NET Core work includes a "generic" document-fetching tool which can get the Open API / Swagger document from a web site project. This tool can download from a service implementing `Microsoft.Extensions.ApiDescription.IDocumentProvider`.

Specific work in the https://github.com/domaindrivendev/Swashbuckle.AspNetCore repo would include:
- define chosen `IDocumentProvider` interface in the Swashbuckle.AspNetCore package or one of its dependencies
  - the supported signature of the invoked method is `Task GenerateAsync(string documentName, TextWriter writer)`
  - the generic tool in the Microsoft.Extensions.ApiDescription.Design package does not define this `interface` and the full name of this service type as well as the method name may be overridden in MSBuild
- implement `IDocumentProvider` in the same package
- update the `AddSwagger(...)` extension methods to register the new `IDocumentProvider` service
  - may require additional supporting services in DI though Swashbuckle seems to already register what's needed

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`
3.0-preview2

**Comment by mkArtakMSFT** [comment]
Moved to preview4 as it's just a tracking issue.

**Comment by dougbu** [comment]
Merged in domaindrivendev/Swashbuckle.AspNetCore@478d73d781
