### ISSUE TITLE
How to setup Http.Sys with SSL

### ISSUE THREAD

**Issue by schneiderpat** [aspnet/AspNetCore#4965]
I created a new Project with `dotnet new webapi`.
I want to use Http.Sys with Windows Authentication.
My setup looks like this
```charp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseHttpSys(options =>
                {
                    options.Authentication.Schemes = AuthenticationSchemes.NTLM | AuthenticationSchemes.Negotiate;
                    options.Authentication.AllowAnonymous = false;
                    options.MaxConnections = null;
                    options.MaxRequestBodySize = 30000000;
                })
                .UseStartup<Startup>()
                .UseSerilog();
    }
```

And the launchsettings.json like this
```json
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "MyProject": {
        "commandName": "Project",
        "launchBrowser": false,
        "environmentVariables": {
            "ASPNETCORE_ENVIRONMENT": "Development",
            "ASPNETCORE_URLS": "https://localhost:5101;http://localhost:5100",
            "ASPNETCORE_HTTPS_PORT": "5101"
        }
    }
  }
}
```

I´m getting redirected to https://localhost:5101/api/values when trying with http://...:5100 but all i get is this:
![image](https://user-images.githubusercontent.com/25080162/50006641-b02e0b00-ffae-11e8-8f0c-40ba7105ce33.png)

If i remove the `UseHttpsRedirection` Middleware everything works fine.
It looks like HttpSys is not binding to 5101.
What am i making wrong?

**Comment by dallancarr** [comment]
There are quite a few hoops to jump through go get this setup on windows.

https://stackoverflow.com/questions/51823878/how-to-https-ssl-with-self-hosted-asp-net-core-2-app-httpsys

**Comment by blowdart** [comment]
Yea, as @dallancarr says it's complicated. HTTP.SYS requires you to register an SSL certificate against the ports you want to listen on, but a VS install should be doing this for you (assuming you installed VS)

What version of the SDK are you using? 
What does `dotnet dev-certs https -c -v` say?
Finally what does `netsh http show sslcert` show? (You'll probably want to pipe that output to a text file.

What you're looking for is an IP:port combination of `0.0.0.0:5001` in the output from `netsh http`. If that isn't there you need to manually bind the certificate with 

`netsh http add sslcert ipport=0.0.0.0:5001 certhash=THECERTHASH appid={ANY NEW GUID}`

You can get the cert hash by looking in your certificate store for the ASP.NET development cert (if you're using the self signed cert the dev-certs command generates) or whatever cert you want to use, and just generate any old guid for the app id

**Comment by schneiderpat** [comment]
Thanks guys. The stackoverflow link solved it! :)
