### ISSUE TITLE
Easier validation for Controller ModelState for unit tests

### ISSUE THREAD

**Issue by juniormayhe** [aspnet/AspNetCore#4966]
### Could model validation be improved for unit tests?

We could get model automatically validated for any verb: GET POST when triggering a validate method.

Now you have to call [controller.ModelState.AddError](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.1) when you just could call controller.Validate():
 
```
[Fact]
public async Task IndexPost_ReturnsBadRequestResult_WhenModelStateIsInvalid()
{
    // Arrange
    var mockRepo = new Mock<IBrainstormSessionRepository>();
    mockRepo.Setup(repo => repo.ListAsync())
        .ReturnsAsync(GetTestSessions());
    var controller = new HomeController(mockRepo.Object);
    controller.ModelState.AddModelError("SessionName", "Required");
    var newSession = new HomeController.NewSessionModel();

    // Act
    var result = await controller.Index(newSession);

    // Assert
    var badRequestResult = Assert.IsType<BadRequestObjectResult>(result);
    Assert.IsType<SerializableError>(badRequestResult.Value);
}
```

### Describe the solution you'd like

Why not evaluate if model is valid in NET Core 2.1+ with `controller.Validate()` or `controller.ValidateModel()`?

```
[Fact]
public async Task IndexPost_ReturnsBadRequestResult_WhenModelStateIsInvalid()
{
    // Arrange
    var mockRepo = new Mock<IBrainstormSessionRepository>();
    mockRepo.Setup(repo => repo.ListAsync())
        .ReturnsAsync(GetTestSessions());
    var controller = new HomeController(mockRepo.Object);
    controller.ValidateModel(); // that would validate required fields or trigger ModelState.AddModelError("SessionName", "Required") to make ModelState.IsValid be false
    var newSession = new HomeController.NewSessionModel();

    // Act
    var result = await controller.Index(newSession);

    // Assert
    var badRequestResult = Assert.IsType<BadRequestObjectResult>(result);
    Assert.IsType<SerializableError>(badRequestResult.Value);
}
```

### Additional context
In unit tests I am not able to use ModelState.IsValid since it always returns true, whatever model I provide (valid or invalid with missing data).

If there is any workaround or correct way of validating model in unit tests in netcore 2.1 and higher please let me know

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @juniormayhe.
Could you please provide us with a repro project (ideally as a repo in GitHub)?
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
If you are unit testing the controller, the right approach is to set the modelstate to match your expectations on the test by using AddModelError, and pass a model in whatever state you expect.

If you are trying to validate the model state based on the input, the right approach to follow is to perform an integration test as described in https://docs.microsoft.com/es-es/aspnet/core/test/integration-tests?view=aspnetcore-2.2 as what you are trying to accomplish is to determine how the system behaves given a specific input.
