### ISSUE TITLE
Error compiling Razor Components project from Templates

### ISSUE THREAD

**Issue by Boglen** [aspnet/AspNetCore#4967]
### Describe the bug
Error compiling Components sample project from Microsoft.DotNet.Web.ProjectTemplates.RazorComponentsWeb in Visual Studio 2019 Preview and dotnet

### To Reproduce
1. Using this version of ASP.NET Core '3.0.100-preview-009812'
2. 
> dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-18613-0142 --nuget-source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
> dotnet new razorcomponents

![oldblazorbuild](https://user-images.githubusercontent.com/10594440/50014311-6c0a2d00-ffe5-11e8-9bc5-67d4776e9384.JPG)

**Comment by mkArtak** [comment]
Thanks for contacting us, @Boglen.
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@Boglen, can you please share with us the output of `dotnet --info`? Thanks!

**Comment by Boglen** [comment]
C:\Users\Boglen>dotnet --info
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.2.100-preview3-009430 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27014-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\Boglen>

**Comment by Boglen** [comment]
I think Microsoft.AspNetCore.Blazor.Build assembly wants a Microsoft.NETCore.App 2.2.0-rtm-27105-02.
I found this is in SDK 2.2.100-rtm-009578, but I can't find this SDK to download.

**Comment by Boglen** [comment]
I searched in nuget package "Microsoft.AspNetCore.Components.Build" 3.0.0-preview-18614-0151 and found the Microsoft.AspNetCore.Components.Build.runtimeconfig.json
`{
  "runtimeOptions": {
    "tfm": "netcoreapp3.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.2.0-rtm-27105-02"
    }
  }
}`

**Comment by Boglen** [comment]
.. changed the version to 2.2.0 and I see "Hello world!"
Hope this help you.
![image](https://user-images.githubusercontent.com/10594440/50099372-cacae300-023f-11e9-9559-1404cedb0fc6.png)
![image](https://user-images.githubusercontent.com/10594440/50099387-d7e7d200-023f-11e9-9056-d9133f9b42ef.png)

**Comment by ryanbrandenburg** [comment]
@Boglen it's hard to tell because the error messages are partially in Russian but as images so I can't copy to a translation service, but it seems like you've got a 3.0.0 preview version of the templates that you're trying to run against 2.2? If I had to guess I'd say this was due to the contents of your global.json. Make sure your global.json references all 3.0.0 stuff and if you're still having problems a repro app would be most helpful.

Also when you say "changed the version to 2.2.0 and I see "Hello world!"" I'm not sure what version you changed. Could you be more specific?

**Comment by Boglen** [comment]
There is no global.json in my project.
I'm trying to create a project from this source (https://github.com/aspnet/AspNetCore/tree/master/src/Templating/src/Microsoft.DotNet.Web.ProjectTemplates)
RazorComponentsWeb (former Blazor)

@SteveSandersonMS can you please look?

**Comment by Boglen** [comment]
Steps to reproduce

1. > dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-18614-0151 --nuget-source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
2. > dotnet new razorcomponents -n TestProject
3. > dotnet build
![image](https://user-images.githubusercontent.com/10594440/50108851-15f0f000-0258-11e9-8dcf-5ef9e40d47d5.png)

How to fix:
Go to nuget packages, open Microsoft.AspNetCore.Components.Build\{Current version}\tools
Open file Microsoft.AspNetCore.Components.Build.runtimeconfig.json
And fix version of Microsoft.NETCore.App from 2.2.0-rtm-27105-02 to 2.2.0
![image](https://user-images.githubusercontent.com/10594440/50109155-d1b21f80-0258-11e9-80dd-338a02574a13.png)

Then try again
![image](https://user-images.githubusercontent.com/10594440/50109198-ef7f8480-0258-11e9-83d5-07c39b091d7c.png)

**Comment by SteveSandersonMS** [comment]
Sorry, we don’t support running that on the 3.0 SDK yet. You’ll need to wait until that is implemented, or use a 2.0 SDK.
