### ISSUE TITLE
Add ability to specify IntelliSense mode at design time for TagHelper attributes.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#4977]
Much like #382 it'd be useful to provide a way to indicate what sort of IntelliSense an attribute should have at design time. This would enable the editor to provide auto-complete options that are useful to the `TagHelper` attribute being used.

Ex:

``` C#
public class ScriptTagHelper : TagHelper
{
...
    [AttributeIntelliSense(AttributeIntelliSenseModes.ScriptUrlPicker)]
    public string AspFallbackSrc { get; set; }
...
}
```

Should discuss what modes are available and if we should allow multiple/conflicting `AttributeIntelliSenseAttribute`s.

**Comment by mkArtakMSFT** [comment]
No community involvement for quite a while.
