### ISSUE TITLE
Hierarchical Parent Tag restriction

### ISSUE THREAD

**Issue by IlyaKhD** [aspnet/AspNetCore#4981]
We're working on a custom Tag Helpers package, and one feature we really miss is a parent tag restriction based on tag hierarchy (not only immediate parent).
We already described our problems here: https://github.com/aspnet/Razor/issues/474#issuecomment-144108209 and https://github.com/aspnet/Razor/issues/570.

Currently, we choose the only appropriate Tag Helper in runtime (the `Process` method), but it is ineffective because all applicable Tag Helpers are already instantiated by the moment they are checked, and then rejected.

We have made a research and found that it is fairly easy to implement hierarchical parent restriction:
https://github.com/IlyaKhD/Razor/commit/53b8141aebab6823a1c6672d99cf7af5dc660c13

Consider adding this feature, please.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
