### ISSUE TITLE
Invalid script tag inside a TagHelper element invalidates parent

### ISSUE THREAD

**Issue by glennc** [aspnet/AspNetCore#4983]
``` html
<TagHelperTag>
    <script src="" />
</TagHelperTag>
```

If TagHelperTag is a TagHelper then you will get an exception stating that your TagHelperTag is invalid, and doesn't have a closing tag, when in fact it is the script tag that is invalid.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
