### ISSUE TITLE
HtmlTargetElement ParentTag doesn't work with @tagHelperPrefix

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#4984]
Given the following `TagHelper`s:

``` C#
[HtmlTargetElement("row", ParentTag = "grid")]
public class RowTagHelper : TagHelper
{
}

public class GridTagHelper : TagHelper
{
}
```

Both of the following should work, but don't:
![image](https://cloud.githubusercontent.com/assets/2008729/12279755/e6493fda-b93d-11e5-8c5d-a5901e7e7aff.png)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
