### ISSUE TITLE
Allow C# to exist inside body of a [RestrictChildren] TagHelper

### ISSUE THREAD

**Issue by lothistvan** [aspnet/AspNetCore#4987]
Version: rc1-final

My taghelper definition is

```
[HtmlTargetElement("panel")]
[RestrictChildren("panel-heading", "panel-body", "panel-footer")]
public class PanelTagHelper : TagHelper
{
    ...
}
```

The problem is that I'd like to show the footer depends on something in the model:

```
<panel>
   <panel-body>
   ...
   </panel-body>
   @if(Model.NeedsFooter)
   {
   <panel-footer>
      ...
   </panel-footer>
   }
</panel>
```

The error message:

> The parent <panel> tag helper does not allow non-tag content. Only child tag helper(s) targeting tag name(s) 'panel-heading, panel-body, panel-footer' are allowed.

Please let us to use code block inside a taghelper (with restricted childrens).

Thanks, 
Istvan

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
