### ISSUE TITLE
Razor Templating Improvements

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCore#4988]
## Introduction

Today, Razor doesn't expose much functionality to enable app developers to leverage Razor templates at runtime. That is, Razor **is** a templating language, but it doesn't have many features that allow the developer to use templates written in Razor as a first-class primitive in view/page composition.

The one feature that does exist is that of ["Templated Razor Delegates"](http://haacked.com/archive/2011/02/27/templated-razor-delegates.aspx/) (or "Template Expressions"), which allow for fragments of Razor to be captured as delegates and thus passed into functions, including HTML Helpers, and then executed to produce HTML output. E.g. in the following code, the block `@<li>@item</li>` is the "template expression".

**Helpers.cs**

``` c#
public static class Helpers
{
    public static IHtmlContent ForEach<T>(IEnumerable<T> data, Func<T, IHtmlContent> template)
    {
        var builder = new HtmlBuilder();
        foreach (var item in data)
        {
            builder.AppendHtml(template(item));
        }
        return builder;
    }
}
```

**View.cshtml**

``` html
<ul>
@ForEach(new [] { "one", "two", "three" }, @<li>@item</li>)
</ul>
```

This feature has a number of limitations that if addressed, and expanded upon, can provide a more powerful and expressive set of first-class templating features in Razor.
## Support Declarative Template Authoring & Re-use via an `@template` Directive

Rather than trying to add new features to the existing template expressions feature, which could be limited by issues of backwards compatibility, we'll add a new directive to support declaratively creating Razor templates in CSHTML files:

``` html
@template HelloWorld(string name) {
    <div>Hello @name!</div>
}
```

This would be roughly equivalent to (and thus generate):

``` c#
public IHtmlContent HelloWorld(string name)
{
    var builder = new HtmlBuilder();
    builder.AppendHtml("<div>Hello ");
    builder.Append(name);
    builder.AppendHtml("!</div>")
    return builder;
}
```

This could be declared in any Razor file, including in `_ViewImports.cshtml` in an MVC application, to allow for easy re-use across the application.

The templates could then be executed directly in Razor files. In this way they're very similar to the `@helper` directive from ASP.NET Web Pages:

``` html
@HelloWorld("Frank")
```

They can also be passed in to other methods that accept the template delegate signature:

```
@{ var names = new [] { "Frank", "Mary", "Jane" }; }
@ForEach(names, HelloWorld)
```
## Support Truly Async Template Expressions

Currently, while the delegates generated by template expressions support async statements, they are always evaluated synchronously (i.e. the calling thread is blocked while the delegate is executed). This logic is [actually in MVC](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/HelperResult.cs#L61), so we'd need to make some changes to the contract between Razor and a Razor host, or limit this functionality to the new `@template` directive (see above).

``` html
@template async HelloWorldAsync(string name) {
    await Task.Delay(100);
    <div>Hello @name!</div>
}
```

This would be roughly equivalent to (and thus generate):

``` c#
public async Task<IHtmlContent> HelloWorld(string name)
{
    await Task.Delay(100);
    var builder = new HtmlBuilder();
    builder.AppendHtml("<div>Hello ");
    builder.Append(name);
    builder.AppendHtml("!</div>")
    return builder;
}
```
## Support Multiple Arguments

Template expressions are currently limited to a single argument. We should extend this to support multiple arguments when using the `@template` directive, e.g.:

``` html
@template HelloWorld(string firstName, string lastName) {
    <div>Hello @firstName @lastName!</div>
}
```

This would be roughly equivalent to (and thus generate):

``` c#
public IHtmlContent HelloWorld(string firstName, string lastName)
{
    var builder = new HtmlBuilder();
    builder.AppendHtml("<div>Hello ");
    builder.Append(firstName);
    builder.AppendHtml(" ");
    builder.Append(lastName);
    builder.AppendHtml("!</div>")
    return builder;
}
```

The templates could then be executed directly in Razor files. In this way they're very similar to the `@helper` directive from ASP.NET Web Pages:

``` html
@HelloWorld("Mary", "Lou")
```

They can also be passed in to other methods that accept the template delegate signature:

``` c#
public static class Helpers
{
    public static IHtmlContent MyHelper<T1, T2>(T1 data, T2 state, Func<T1, T2, IHtmlContent> template)
    {
        var builder = new HtmlBuilder();
        builder.AppendHtml(template(data, state));
        return builder;
    }
}
```
## Support Templated Tag Helpers

We should extend Tag Helpers to make working with templates a first-class experience. Binding templates to properties as well as treating the content or even the entire element of a Tag Helper as a template should be possible.

**Tag Helper with content as a template**

``` c#
[HtmlTargetElement("*", Attributes = "asp-repeat")]
public class RepeatTagHelper<TItem> : TemplatedTagHelper<TItem>
{
    [HtmlTargetAttribute("asp-repeat")]
    public IEnumerable<TItem> Items { get; set; }

    public override async Task ProcessAsync(TagHelperContext<TItem> context, TagHelperOutput output)
    {
        foreach (var item in Items)
        {
            output.AppendHtml(await context.GetChildContentAsync(item));
        }
    }
}
```

``` html
@{
    var customers = DB.GetCustomers().ToList();
}
<table>
    <tbody asp-repeat="customers">
        <tr>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
        </tr>
    </tbody>
</table>
```

**Tag Helper with template properties**

``` c#
public class ListViewTagHelper<TItem> : TagHelper
{
    public IEnumerable<TItem> Data { get; set; }

    public Action<IHtmlContent> HeaderTemplate { get; set; }

    public Func<TItem, IHtmlContent> ItemTemplate { get; set; }

    public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        foreach (var item in Items)
        {
            output.AppendHtml(await context.GetChildContentAsync(item));
        }
    }
}
```

``` html
@model IEnumerable<Customer>
@template ContentTemplate(IEnumerable<T> items, Func<T,IHtmlContent> rowTemplate) {
    <tbody>
        @foreach (var item in items)
        {
            rowTemplate(item);
        }
    </tbody>
}
@template HeaderTemplate() {
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.FirstName)</th>
            <th>@Html.DisplayNameFor(m => m.LastName)</th>
        </tr>
    </thead>
}
@template CustomerRowTemplate(Customer customer) {
    <tr>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
        </tr>
}
<table>
<list-view data="customers" header-template="HeaderTemplate" content-template="ContentTemplate" item-template="CustomerRowTemplate" />
</table>
```

_TODO: Update with some details about integration with #791_
## Support Template Compilation & Packaging

To enable sharing of declared templates across projects without having to restore to writing them manually in C#, we should build a tool that allows compiling templates from CSHTML files directly to assemblies/NuGet packages. This could be a project tool that works with the .NET Core CLI (e.g. `dotnet razor compile-templates`) or a Roslyn compilation extension/module that allows for templates (and potentially other Razor primitives) to be compiled as part of project compilation.

**Comment by Danielku15** [comment]
It is quite unfortunate that this topic is not followed up as with the removal of @helper syntax it is a bit hard to have some page-local piece of code for templates. The templated razor delegates are not really a proper replacement for real templates. I attempted to use a simple local function that returns a `IHtmlContent` but this also does not work as the `@<text>SOME_RAZOR_SNIPPET</text>` translates to a lambda. 

The following snippet is the closest what I could write to "well-formed" syntax in Razor: 

```cs
@{
    IHtmlContent MyTemplate(string param1, double param2)
    {
        if (param2 < 0.5)
        {
            return @<text>@param1</text>;
        }
        else
        {
            return @<text>@param1.ToUpper()</text>;
        }
    }
}
@MyTemplate("a", 1)
@MyTemplate("a", 0)
```

But the output expression translates to a lambda instead of a simple HelperResult: 

```cs
IHtmlContent MyTemplate(string param1, double param2)
{
    if (param2 < 0.5)
    {
        return item => new global::Microsoft.AspNetCore.Mvc.Razor.HelperResult(async(__razor_template_writer) => {
            PushWriter(__razor_template_writer);
            BeginContext(6257, 6, false);
                 Write(param1);
            EndContext();
            PopWriter();
        });
    }
    else
    {
        return item => new global::Microsoft.AspNetCore.Mvc.Razor.HelperResult(async(__razor_template_writer) => {
            PushWriter(__razor_template_writer);
            BeginContext(6336, 16, false);
                 Write(param1.ToUpper());
            EndContext();
            PopWriter();
        });
    }
}
```

**Comment by mkArtakMSFT** [comment]
Closing as this issue is outdated. Things which matter will come back up again.
