### ISSUE TITLE
Hierarchical Tag Helper binding

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCore#4989]
## Summary

This feature would add support for directly binding Tag Helper properties to child Tag Helper instances from the source document, thus making it much simpler to author related Tag Helpers that are designed to work together in a hierarchy.
## Background

Today, we provide a number of features to assist with authoring sets of Tag Helpers that are intended to be used together in a logical hierarchy, including:
- `RestrictChildrenAttribute` to restrict which tags are valid as children of the element a Tag Helper instance is attached to
- `HtmlTargetElementAttribute.ParentTag` to restrict which tag is valid as a parent of an element a Tag Helper instance is attached to
- `TagHelperContext.Items` to allow passing of data between different Tag Helpers attached to the same element, and between Tag Helpers attached to an element and Tag Helpers attached to that element's children

The use of `TagHelperContext.Items` to pass data between related Tag Helpers is somewhat cumbersome, e.g.:

``` c#
public class ParentChildContext
{
    public string SomeData { get; set; }
}

[RestrictChildren("child")]
public class ParentTagHelper : TagHelper
{
    private ParentChildContext _context;

    public override void Init(TagHelperContext context)
    {
        _context = new ParentChildContext();
        context.Items.Add(typeof(ParentChildContext), _context);
    }

    public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        // Force children to process
        var childContent = await output.GetChildContentAsync();

        // Read context data set by child here
        // _context.SomeData
    }
}

[HtmlTargetElement("child", ParentTag = "parent", TagStructure = TagStructure.WithoutEndTag)]
public class ChildTagHelper : TagHelper
{
    public string SomeData { get; set; }
    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        var parentContext = context.Items[typeof(ParentChildContext)];
        parentContext.SomeData = SomeData;
    }
}
```

``` html
<parent>
    <child some-data="This will be accessible to the parent" />
</parent>
```
## Proposal

Tag Helper property binding would be expanded to support directly binding Tag Helper instances to properties on a Tag Helper using Tag Helpers attached to the current element's children as the source.

Binding will:
- Support the binding of any type that implements `ITagHelper`
  - In the case where multiple children of the matching type are present, the first instance will be bound
- Support the binding of `IEnumerable<T> where T : ITagHelper` to enable simple access to multiple child Tag Helper instances of the same type
  - When the binding applies, it will always create and set an `IEnumerable<T>` instance to the property, irrespective of the property's initial value (i.e. it will overwrite any current value of the property)
- Bind only the first level of children (i.e. it would not perform a "deep" or "recursive" bind)
- Only support binding to `public` settable properties (like other bindings)
- Be implied (i.e. automatic) based on the property being `public` and the type being derived from `ITagHelper`
  - _Review: Should this be opt-in via a new attribute rather than implied?_
- Support being disabled via `HtmlAttributeNotBoundAttribute` on the property that would otherwise be bound
### Example

Here is the example from above reimplemented with the proposed behavior implied:

``` c#
[RestrictChildren("child")]
public class ParentTagHelper : TagHelper
{
    public ChildTagHelper Child { get; set; }

    public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        // Force children to process
        var childContent = await output.GetChildContentAsync();

        // Read data directly from child here
        // Child.SomeData
    }
}

[HtmlTargetElement("child", ParentTag = "parent", TagStructure = TagStructure.WithoutEndTag)]
public class ChildTagHelper : TagHelper
{
    public string SomeData { get; set; }
}
```

``` html
<parent>
    <child some-data="This will be accessible to the parent" />
</parent>
```
### More Examples

``` c#
/// <summary>This Tag Helper applies to all elements and effectively creates a server-side DOM, albeit with a single, forward-only pass rather than being stateful.</summary>
[HtmlTargetElement("*")]
public class DomTagHelper : TagHelper
{
    public DomTagHelper Parent { get; set; }

    public IEnumerable<DomTagHelper> Children { get; set; }

    public override void Init(TagHelperContext context)
    {
        // Set parent on all children
        foreach (var child in children)
        {
            child.Parent = this;
        }
    }

    public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        // Run children
        var childContent = await output.GetChildContentAsync();

        // 
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
