### ISSUE TITLE
Optimize string allocations in parsing

### ISSUE THREAD

**Issue by Yves57** [aspnet/AspNetCore#4992]
I have seen that many strings are allocated in the `Microsoft.AspNetCore.Razor.Tokenizer.Tokenizer.EndSymbol()` method.
But some strings are in fact often the same. So I modified the end of the method like that:

```
.....
string tokenContent;
if (Buffer.Length != 1)
{
   tokenContent = Buffer.ToString();
}
else
{
   if (!_oneCharTokenCache.TryGetValue(Buffer[0], out tokenContent))
   {
      tokenContent = Buffer.ToString();
      _oneCharTokenCache.Add(Buffer[0], tokenContent);
   }
}
sym = CreateSymbol(start, tokenContent, type, errors);
```

I have made a test with an extrem case ([LargePageMvc page](https://github.com/aspnet/Performance/blob/dev/testapp/LargePageMvc/Views/Home/Index.cshtml)).

Before the modification, 215643 strings where allocated. After the optimization, 131577 strings allocations where saved (more than half). And the `_oneCharTokenCache` dictionary had only 17 items inside: some symbols like <, !, >, =, and all digits.

Two additional remarks:
- As a bonus, it improves performances from 587ms to call `MarkupParser.ParseDocument()` down to 510ms on my (old!) computer. It can improve a little bit F5 startup scenarios with large pages...
- Of course, we can extend the concept to any `string` lengths, but there is less redundancy, and it will be probably less performant.

If you think that it is interesting, I can propose a PR...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
