### ISSUE TITLE
Indentation problems with code blocks

### ISSUE THREAD

**Issue by tuespetre** [aspnet/AspNetCore#4997]
I wasn't sure if this should go to VS or if it belongs here (especially with the Evolution work going on.)

In Visual Studio, when auto-formatting a Razor document, a code block nested inside of an `if` block will cause the indentation of any code following the `if` block to be increased to match the indentation of the code inside of the code block.

This is driving me 🔩 🔩 ! 

![bloody-razor](https://cloud.githubusercontent.com/assets/4853540/23904725/e9295060-0896-11e7-902f-91e7edf126ff.png)

Moving the code out of the code block to be just inside the `if` block seems to clear it up:

![bloody-razor-2](https://cloud.githubusercontent.com/assets/4853540/23904887/675caa2c-0897-11e7-8657-9b14ddcd8fc7.png)

**Comment by mkArtakMSFT** [comment]
Closing as we track this separately.
