### ISSUE TITLE
Razor Language Service sign off activities.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#5004]
- [ ] TagHelpers highlight in pre-opened files.
- [ ] TagHelpers from primary application refresh on change.
- [x] TagHelpers from packages highlight without build.
- [x] TagHelpers from primary application highlight without build.
- [x] TagHelpers from referenced libraries highlight.
- [x] TagHelpers from referenced libraries refresh on change.
- [x] TagHelpers highlight when restore completes.
- [x] TagHelpers get auto-complete entries when typing elements.
- [x] TagHelpers get auto-complete entries when typing attributes.
- [x] `@addTagHelper` can turn on TagHelpers for an entire assembly
- [x] `@addTagHelper` can turn on a single TagHelper
- [x] `@addTagHelper` can be used in _ViewImports.cshtml
- [x] `@addTagHelper` can be used directly on a view
- [x] `@removeTagHelper` can turn off TagHelpers for an entire assembly
- [x] `@removeTagHelper` can turn off a single TagHelper
- [x] `@removeTagHelper` can be used in _ViewImports.cshtml
- [x] `@removeTagHelper` can be used directly on a view
- [x] `@tagHelperPrefix` works as expected.
- [x] `@tagHelperPrefix` can be used in _ViewImports.cshtml
- [x] `@tagHelperPrefix` can be used directly on a view
- [x] The extension has an icon.
- [x] ViewComponents do not cause errors in views.
- [x] The extension can be upgraded.
- [x] Breakpoints can be hit in cshtml files.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen let's make sure everything here is tracked by CTI instead.
