### ISSUE TITLE
RazorPage WriteLiteral could more compact/fast-path types

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#5010]
_From @benaadams on April 27, 2017 10:2_

Currently it uses `string` which means each time a page is rendered it needs to convert from UTF16 to the output encoding (likely utf8)
```
  IL_0019:  ldstr      "\r\nDuis sollicitudin mauris nec molestie molestie. "
    + "Etiam ipsum quam, tincidunt quis egestas non, euismod id lacus. Nulla n"
    + "isi magna, auctor vitae turpis ut, congue interdum lectus. Nulla vehicu"
    + "la, dui id venenatis tincidunt, magna lacus tristique enim, ut sodales "
    + "nulla neque quis ligula. Vivamus volutpat laoreet molestie. Pellentesqu"
    + "e elementum porta volutpat. Curabitur dui sapien, imperdiet nec velit i"
    + "nterdum, venenatis pulvinar neque. Vivamus venenatis hendrerit nunc, ve"
    + "l mattis justo tristique nec. Mauris ullamcorper posuere tellus, eget c"
    + "ongue ipsum sagittis eget. Integer ultrices sit amet nisl at venenatis."
    + " Sed vel venenatis urna, ac scelerisque augue."
IL_001e:  callvirt   instance void [Microsoft.AspNetCore.Mvc.Razor]
    Microsoft.AspNetCore.Mvc.Razor.RazorPage::WriteLiteral(object)
```

Instead they could be stored as an new type `asciiBytes` and if non-ascii chars were encountered in the compilation `utf8Bytes` in class readonly static which would be shims on `byte[]`.

This would mean they would use on average half the memory; and could if output encoding was compatible just be put directly on the wire without re-encoding. (Hence ascii/utf8 split as more encodings are compatible with ascii); then only re-encode if it needs to switch.

`string` could still be used for shorter literals (< *n* chars) e.g. tag names to make use of string interning; if a custom interning scheme wasn't to be devised.

This would allow larger chunks of html in pages to be stored and output more efficiently.

_Copied from original issue: aspnet/Mvc#6216_

**Comment by benaadams** [comment]
Can use the C#7.3 ReadOnlySpan<byte> property optimisation and write ReadOnlySpans now: https://vcsjones.com/2019/02/01/csharp-readonly-span-bytes-static/
```csharp
ReadOnlySpan<byte> utf8Literal1 => new byte[] { 1,2,3,4,5 };
ReadOnlySpan<byte> utf8Literal2 => new byte[] { 1,2,3,4,5 };

WriteLiteral(utf8Literal1);
WriteLiteral(utf8Literal2);

I understand it may work in method also (not needing higher property); should not sure of the semantics here though

**Comment by benaadams** [comment]
Can do it inline in the method also [sharplab.io](https://sharplab.io/#v2:EYLgHgbALANALiAlgGwD4AEAMACdBGAbgFgAoLXPAOgCUBXAOzkQFsBTSgYQHtmAHFVgCcAykIBuiAMasAzsRKl0AZlwAmbAAUAhgHNW2UgG9S2U7hXoo2AKJhWk2nFYBBGQE96kgBQBKAyTNsYwDAs2pWLQATAHl6ZDdhXi16AB5gNycAPmxkRCdBLWR5ULMTEuwAegrsAAlWZGQubAB1LkFkSIBCMpLc/MLsAF5selYAd2xwqNj4xOS0jNZMr1GJ9KcAbQBdQwB2VRhsPEw8Q+OADjPMS6O8U+wlA+xz3bO7t9gj66vMQ6UlAC+PmK5WagjyrAAMhCCsgvH0hIVgT1sACUSiNgBZVhwAAWXEiAEk+HDsXiCcTeMhorwmFx6DJKAA5LiEuKIegcnQ+LYo3jgsRaJy4KxgiHQ/pwqYxOIJJKpdZLbAyeV+Qyo0gAoA==):
```csharp
public class Page 
{
    public void ExecuteAsync() 
    {
        ReadOnlySpan<byte> literal;
        
        // Hello World!
        literal = new ReadOnlySpan<byte>(new byte[]{72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 33});
        WriteLiteral(literal);
    }
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private void WriteLiteral(ReadOnlySpan<byte> span) { }
}
```
Produces
```
    instance void ExecuteAsync () cil managed 
{
    // Method begins at RVA 0x2050
    // Code size 22 (0x16)
    .maxstack 3
    .locals init (
        [0] valuetype [System.Memory]System.ReadOnlySpan`1<uint8>
    )

    IL_0000: ldloca.s 0
    IL_0002: ldsflda valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=12' '<PrivateImplementationDetails>'::'2EF7BDE608CE5404E97D5F042F95F89F1C232871'
    IL_0007: ldc.i4.s 12
    IL_0009: call instance void valuetype [System.Memory]System.ReadOnlySpan`1<uint8>::.ctor(void*, int32)
    IL_000e: ldarg.0
    IL_000f: ldloc.0
    IL_0010: call instance void Page::WriteLiteral(valuetype [System.Memory]System.ReadOnlySpan`1<uint8>)
    IL_0015: ret
} // end of method Page::ExecuteAsync
```
Or
```asm
mov r8, 0x2046dc30830 // Get static data
lea r9, [rsp+0x20]
mov [r9], rax
mov [r9+0x8], r8
mov [r9+0x10], edx
lea rdx, [rsp+0x20]
call Page.WriteLiteral(System.ReadOnlySpan`1<Byte>)
```

**Comment by rynowak** [comment]
I'm trying to scrounge up where my data is for this. 

The way things currently work it ended up being a lot slower for us to start throwing in random UTF8 content. The problem was that there was so much mixing of UTF8 (static content) and UTF16 (dynamic content).

The best case was like 30% less memory consumption (all static content, network saturated). Realistic cases (real world code samples) where about 15% higher CPU usage.

**Comment by rynowak** [comment]
Basically, a lot more has to go into this can optimizing the codegen, the optimization has to flow through a bunch of layers.

**Comment by davidfowl** [comment]
To do this efficiently, we would need to store pointers into the data segment on the heap (which doesn't work with span). It would to be unsafe as well. The prototype @rynowak did still had to copy since all of the razor writes are initially buffered (correct me if I'm wrong).

**Comment by rynowak** [comment]
yup. Can't use span. 

Razor is **fundamentally buffered** - that's how features like `Layout` and `@section` work.

**Comment by benaadams** [comment]
> To do this efficiently, we would need to store pointers into the data segment on the heap (which doesn't work with span)

Could also store a delegate reference or an index into a delegate array, and invoke it to get the `ReadOnlySpan<byte>`

```csharp
public class Page
{
    delegate ReadOnlySpan<byte> LiteralAction();

    static ReadOnlySpan<byte> _utf8Literal1() => new byte[] { 72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 33 };
    static ReadOnlySpan<byte> _utf8Literal2() => new byte[] { 72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 33 };

    static readonly LiteralAction[] _literalActions 
        = new LiteralAction[] { _utf8Literal1, _utf8Literal2 };
}
```

**Comment by benaadams** [comment]
Might be slower than just converting the string though

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
