### ISSUE TITLE
Make it easier to use static assets that are part of a RCL project

### ISSUE THREAD

**Issue by kichalla** [aspnet/AspNetCore#5070]
A RCL project could have static assets like css, js and images. Currently these files don't get published to the referencing application's published `wwwroot` folder. They need to be included as embedded files in a RCL project and need to use `ManifestEmbeddedFileProvider` to serve their contents. Its a lot of work for users to set this up. To give an idea, this is what IdentityUI does currently:

https://github.com/aspnet/Identity/blob/dev/src/UI/IdentityDefaultUIConfigureOptions.cs#L50-L66

**Comment by pranavkm** [comment]
This is covered by the Static Web Assets feature.
