### ISSUE TITLE
Implement DocumentSnapshot tracking in VS 4 Mac

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#5073]
When we eventually move all of our internal parsing infrastructure to use DocumentSnapshots we'll need to  have the correct information flowing through the VS4Mac side of the world.

**Comment by mkArtakMSFT** [comment]
This hasn't been a priority nor we heard many asks for this.

**Comment by NTaylorMullen** [comment]
Actually, this was done by Kirill.
