### ISSUE TITLE
ASP.NET Core tag helpers don't allow me to escape attributes annotated with @

### ISSUE THREAD

**Issue by luisabreu** [aspnet/AspNetCore#5075]
Hello guys.

While migrating an existing app, I've noticed that the new tag helpers won't let me escape attributes annotated with  @. In my case, I have an existing MVC 5 app that I'm migrating to the ASP.NET Core. The existing code looked like this:

```html
<form action="@Url.Action(...)" @@submit="save()">
```

The server side is trying to use the shortcut notation for Vue's v-on: and the generated HTML looked like this:

```html
<form action="/..." @submit="save()">
```

When this view got migrated to ASP.NET Core, the code was changed to look like this:

```html
<form asp-action="..." asp-controller="..." @@submit="save()">
```

However, now the @«submit attribute isn't outputted (it's simply discarded from the generated HTML).

Is this a bug? If that is not the case, how can I output attributes annotated with @?

 @Thanks.

Luis

**Comment by mkArtakMSFT** [comment]
Closing this as there has not been much activity and need for this.
