### ISSUE TITLE
Directive usage errors need to appear in runtime too

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#5084]
There are cases like https://github.com/aspnet/Razor/issues/2539#issuecomment-416384015 when using directives as variables in cshtml results in a weird csharp error at runtime. Instead we should provide a Razor error like it does during design time.

cc @dougbu @NTaylorMullen

**Comment by mkArtakMSFT** [comment]
Closing as no customers complained about this.
