### ISSUE TITLE
Parser treats the whitespace between a directive and its first token as C#

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#5090]
The parser incorrectly maps the whitespace text that appears below into C# (syntax tree). Since this token isn't significant in any way, it gets thrown away harmlessly instead of mapped into the C# editor buffer. 
```
@page "foo"
```

So what I'm saying is that the 'space' character above is treated as C# by the buffer instead of metacode/none. Unfortunately the fix for this breaks completion for partial parsing. So it looks like we cut a corner or two when implementing this to make it easier to support completion.  

Found while implementing #2266

**Comment by mkArtakMSFT** [comment]
Closing as no customers complained about this.
