### ISSUE TITLE
Parser computes the wrong length for C# code with an escaped transition

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#5091]
The parser parses the following code into the correct C# but gets the length wrong - it includes `@@` when computing the length. 

```
@{ @@Da }
```

I'm not aware of the impact of this issue. This is somewhat unlikely to occur, and would only happen when someone needs to use a verbatim identifier in C# from Razor. This could cause a variety of incorrect editor behaviors including issues with completion or crashes.

Found while investigating #2266

**Comment by mkArtakMSFT** [comment]
Closing as no customers complained about this.
