### ISSUE TITLE
C# 8 Readiness

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#5092]
We need to evaluate and update Razor for C# 8. This will align with 3.0

https://github.com/dotnet/csharplang/milestone/8
https://channel9.msdn.com/Events/dotnetConf/2018/S103

**Comment by NTaylorMullen** [comment]
1df8128b877ac9ffec5c7547e84927b0ecbe8c16
c9e0d2a60f7287d14c282555669b67a1000fef20
76c1352d2c4136ab4c3515ffca823377cbc7b2d9

**Comment by rynowak** [comment]
Are we missing test coverage for some of the *lesser* features? like range

**Comment by NTaylorMullen** [comment]
> Are we missing test coverage for some of the _lesser_ features? like range

I'll add some.

**Comment by NTaylorMullen** [comment]
> Are we missing test coverage for some of the _lesser_ features? like range

Good thing you mentioned this. Found that we weren't perfect with using declaration syntax 👏 

PR out: https://github.com/aspnet/AspNetCore-Tooling/pull/367

**Comment by NTaylorMullen** [comment]
Done
