### ISSUE TITLE
Figure out how RCLs in 3.0 work

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#5100]
* Project TFM
* What does it compile against?
* How does it specify language version \ Razor Configuration?
* How does it use the compiler in the SDK (currently behind the `_EnableAllInclusiveRazorSdk` property)

**Comment by Eilon** [comment]
@pranavkm / @mkArtakMSFT - is this a PRI-0 bug, and is it in the correct milestone?

**Comment by pranavkm** [comment]
This was resolved as part of https://github.com/aspnet/AspNetCore/issues/6392
