### ISSUE TITLE
Use namespace specified in project system \ MSBuild to calculate default namespace for components

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#5106]
The current code uses the path to calculate the base namespace for RazorComponents. We should instead use the `RootNamespace` property specified in MSBuild

**Comment by nvmkpk** [comment]
This also applies to blazor applications.

**Comment by ajaybhargavb** [comment]
Assigning this to myself as I'm working on it now.

**Comment by ajaybhargavb** [comment]
Closing as this is done pending merge to master.
