### ISSUE TITLE
Figure out how ComponentDocumentClassifierPass knows what files are components

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#5111]
The Sdk uses an `ItemGroup` to determine what constitutes a `RazorComponent`. By default, it's populated with files with a `.razor` extension, but we want this information to come from MSBuild evaluation. `ComponentDocumentClassifierPass` needs to know this information. In the 2-phase compile PR, this is done by adding a feature that sets a value `RazorCodeDocument.SetInputDocumentKind` and the classifier uses this to figure out if it needs to do a component. This needs to be designed correctly. Using this issue to track this work

**Comment by rynowak** [comment]
I did a thing here already that solves this problem. `RazorProjectItem` and `RazorCodeDocument` now have a `FileKind` - so it's easy for code in the compiler to know if it's a component or legacy.

Closing this as done, holla back if you disagree.
