### ISSUE TITLE
2-phase compile in SDK follow up items

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#5112]
* [ ] Make `ComponentTagHelperDescriptorProvider` not public.
* [ ] `GenerateCommand` uses `IImportFeature` to locate imports. There is only one implementation of the interface today that returns `_ViewImports.cshtml`.
* [ ] Need a nicer way to set `RazorCodeGenerationOptions`

**Comment by rynowak** [comment]
This area has changed a bit since this work item was followed, so use your common sense and try to clean it up. Let's talk first if you feel like you need to go on any major adventures.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We think that this issue is fixed now. If you are still facing this problem, please file a new issue.
