### ISSUE TITLE
Are hosted services guaranteed to run

### ISSUE THREAD

**Issue by granthoff1107** [aspnet/AspNetCore#5118]
I've created a hosted service that executes a recurring task in .Net-Core. 
(I'm using shared hosting so I don't have control over iis)

    public class SchedulerService : IHostedService
    {
        private readonly ILogger _logger;
        private Timer _timer;

        public SchedulerService(ILogger<SchedulerService> logger)
        {
            this._logger = logger;
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            this._timer = new Timer(ExecuteTask, null, TimeSpan.Zero,
                TimeSpan.FromMinutes(30));

            return Task.CompletedTask;
        }

        private void ExecuteTask(object state)
        {
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            this._timer?.Change(Timeout.Infinite, 0);
            return Task.CompletedTask;
        }
    }

I'd like to ensure that this task is always run.  But Hosted Service's are **NOT** [guaranteed to complete](https://stackoverflow.com/questions/51144048/net-core-hosted-services-guarenteed-to-complete) due to app-pool recycles etc.

I'm a bit confused on this notion.  I'm under the impression now that Hosted services are only run in the background after a request is made and once the app pool is recycled the background task is killed (e.g 90 second limit from the older version of .net)

If this is the case, and no request are made to my site, can I still be guaranteed that my SchedulerService will run?

Or should I just have my scheduler service send a request every ~75 seconds to myself, to ensure that a new thread will restart the scheduler?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
