### ISSUE TITLE
Creating new app on MAC with dotnet cli with Core3 Preview SDK - CRITICAL PackageReference not added

### ISSUE THREAD

**Issue by atljoseph** [aspnet/AspNetCore#5131]
MAC
dotnet SDK Core 3 Preview (3.0.100-preview-009812)

After doing this:
dotnet new webapi -o CupcakeApi

Project does not compile: Fail, Microsoft.

Works after manually adding this line to the .csproj file:
```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

Two words. More Testing.

Thanks

**Comment by atljoseph** [comment]
Actually that didn't fix it. Still broken. Sad. You give us something to look at it. First time I look at it, the thing doesn't work. Fail. Super Fail for a company like MS

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @atljoseph.
Closing as this should be resolved at this point.
