### ISSUE TITLE
Integration Test: API controller failed to call another controller via ASP.NET Core API 

### ISSUE THREAD

**Issue by PingPongSet** [aspnet/AspNetCore#5132]
I have a problem getting an API controller to call another API controller within the same project. 

Specifically, the integration project is able to call a controller in the production project, and the controller will make another call to a dummy controller within the same project, but the first controller failed with internal server error. 

However, the first controller can call google.com.

Please note that it works when the production project is hosted via either console or windows services. It only happens when tests in integration project run.

The production project is an ASP.NET CORE Web API project v2.1, and the integration test project, v2.1 via xUnit by following below

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2

Integration project with xUnit below:

    public class RetryPolicyTests: IClassFixture&lt;WebApplicationFactory&lt;Startup&gt;&gt;
        {
            private readonly WebApplicationFactory&lt;Startup&gt; _factory;
    
            public RetryPolicyTests(WebApplicationFactory&lt;Startup&gt; factory)
            {
                _factory = factory;
            }
    
            [Theory]
            [InlineData("http://localhost:1234/api/v1/Book/")]        
            public async Task Test(string url)
            {
                // Arrange
                var client = _factory.CreateClient();
    
                // Act           
    
                var body = "{}";
                using (var content = new StringContent(body, Encoding.UTF8, "application/json"))
                {
    			
                    var response = await client.PostAsync(url, content);
    
                    // Assert
                    response.EnsureSuccessStatusCode(); //Failed here with internal server error
                    Assert.Equal(StatusCodes.Status200OK,
                        (int) (response.StatusCode));
                }
            }
        }

	

BookController		

      [ApiVersion("1")]
        [Route("api/v{version:apiVersion}/[controller]")]
        [ApiController]
        public class BookController : ControllerBase
        {
            private readonly ILog _logger;
            private readonly IConfiguration _configuration;
            private IHttpClientFactory _httpClientFactory;
    
            public BookController(ILog logger , IConfiguration configuration, IHttpClientFactory httpClientFactory)
            {
                _logger = logger;            
                _configuration = configuration;
                _httpClientFactory = httpClientFactory;
            }
    
    
            [HttpPost]
            public async Task&lt;ActionResult&gt; Post()
            {           
                using (StreamReader reader = new StreamReader(Request.Body, Encoding.UTF8))
                {
                    string body = reader.ReadToEnd();
    
                    var url = "http://localhost:1234/api/v1/Author/"
                    using (var content = new StringContent(body, Encoding.UTF8, "application/json"))
                    {                    
                        var _httpClient = _httpClientFactory.CreateClient();
                        var s = _httpClient.GetAsync("http://google.com").Result;  //works here
    					
                        var response = await _httpClient.PostAsync(url, content);   //internal server error
                         var statusCode = response.StatusCode;
                        return StatusCode((int)statusCode);
                    }
                
                }      
            }
    
        }

AuthorController 

	
	 [ApiVersion("1")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]        
    public class AuthorController : ControllerBase
    {
        ILog _logger;

        public AuthorController(ILog logger)
        {
            _logger = logger;
        }

        [HttpPost]
        public void Post()
        {
            using (StreamReader reader = new StreamReader(Request.Body, Encoding.UTF8))
            {
                var body = reader.ReadToEnd();

            }

    }
	
It works if integration test hits directly at Author controller.

Error:

    Result StackTrace:	
    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
       at IntegrationTests.xUnit.RetryPolicy.RetryPolicyTests.Test(String url) in C:\IntegrationTests.xUnit\RetryPolicy\RetryPolicyTests.cs:line 46
    --- End of stack trace from previous location where exception was thrown ---
    Result Message:	System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).

Please note that after integration test hits the first controller and before hits the second controller, I tried to send the same data to the first controller via external tools, like Postman, or fiddler. But all controllers are not available to external tool, unlike if it is hosted on console or Windows service (In this case, all controllors can process requests).

Cross-reference: https://github.com/aspnet/Docs/issues/10022

**Update**

I upgraded to 2.2, issue still exists

**Update**
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Controllers.BookController.Post() in C:\src\Controllers\BookController.cs:line 84}	System.Exception {System.Net.Http.HttpRequestException}

   
InnerException	{System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)}	System.Exception {System.Net.Sockets.SocketException}

**Comment by PingPongSet** [comment]
**Update**

I upgraded to 2.2, issue still exists

**Comment by pranavkm** [comment]
What's the exception that results in the internal server error?

**Comment by PingPongSet** [comment]
please see exception updated on the opening ticket

**Comment by PingPongSet** [comment]
@pranavkm 

Do you have a chance to look into the issue?

**Comment by pranavkm** [comment]
@PingPongSet sorry I was out these past few weeks. It `http://localhost:1234` supposed to be the application being tested? If so, TestHost doesn't actually set up a server that listens to network requests. 

As part of your test, you might be able to configure `IHttpClientFactory` to use the TestHost created message handler to perform a test host loopback. cc @Tratcher for suggestions

**Comment by Tratcher** [comment]
@rynowak for IHttpClientFactory.

I question the larger design here though. If you know the functionality you need is available elsewhere in your application then why invoke it via HTTP? Why not factor your code so you can call the functions directly?
