### ISSUE TITLE
Incremental Build

### ISSUE THREAD

**Issue by josejmoran** [aspnet/AspNetCore#5141]
I noticed that the build process in ASP.NET Core takes a lot of time. I think too much for a small application. Even when I just changed a razor page. Which is supposed to just works if I change just a razor page, there is no compilation needed(I have seen it work sometimes, but not always). That situation got me thinking about: is this compiling the whole project every time?

Is is possible that we can get some way of just compile the file that I just changed. I ran the application a minute ago and the compilation of whatever was compile still apply for the most part.

I remember back in the days of small RAM size PC's Pascal had .OVL extensions. Can we implement something like this in ASP.NET Core so we get the may things compiled once  and just compile the little change I did to a file into a separate executable maybe and this way I also make the application smaller so is faster to load, works in small memory devices by using .OVL files that will only load when I click on the menu that needs that code?

It will be great to be able to run ASP.NET core in a small RAM device, but it will also improve build time, run time and the programmer close loop (compile-run-fix).

**Comment by Eilon** [comment]
This type of incremental compilation is not really supported in .NET, but you can post your thoughts in the C# compiler repo here: https://github.com/dotnet/roslyn
