### ISSUE TITLE
Can't host 2.2 in Azure App Service

### ISSUE THREAD

**Issue by johnkwaters** [aspnet/AspNetCore#5145]
I upgraded from 2.1.6 to 2.2.0, works nicely locally on IIS or Kestrel, but when deployed to Azure App Service, the API (it's an aspnetcore webapi app) won't start. I get

HTTP Error 500.21 - Internal Server Error
Handler "aspNetCore" has a bad module "AspNetCoreModuleV2" in its module list

Is this not supported yet? I can see the SDK is available on the machine.

**Comment by Tornhoof** [comment]
The new ANCM is not yet on Azure App Service.
See Damian Edwards' comment in https://blogs.msdn.microsoft.com/webdev/2018/12/04/asp-net-core-2-2-available-today/

**Comment by jkotalik** [comment]
We will make an announcement when ANCMV2 is publicly available on Azure App Services. There isn't an easy way to get module information from IIS via command line.

**Comment by johnkwaters** [comment]
Thanks. With previous updates I would just wait until I saw the SDK available on the machine, by going to the console on Azure App Services and doing dotnet --list-sdks. So this time I was surprised when I saw 2.2.0 was on the machine but it still didn't work. I guess this one went deeper! As far as feedback goes, though, it's quite hard to know when things that are released as nuget packages actually work on App Services...its a trial and error process, not the best.

**Comment by johnkwaters** [comment]
Any updates?

**Comment by jkotalik** [comment]
ANCMV2 should now be available on Azure App Services as of recently. Please go ahead and try!

**Comment by johnkwaters** [comment]
Appears to work thanks!

**Comment by renzors** [comment]
@jkotalik just to verify, Is there an official announce about the  ANCMV2 availability over Azure App Services?

**Comment by jkotalik** [comment]
@renzors I don't believe there was an announcement. cc @suwatch

**Comment by anurse** [comment]
Closing as ANCMV2 is now supported on App Service
