### ISSUE TITLE
Run MVC filter before authorization

### ISSUE THREAD

**Issue by uokitomer** [aspnet/AspNetCore#5151]
### Is your feature request related to a problem? Please describe.
At the moment I am authorizing my api by using policies. To call my authorized endpoints I need to be able to verify that some headers are present in the request, otherwise, I cannot authorize the user.

I need to be able to return status code 400 if these headers are not present and tell the user they are required.

I have a ServiceFilterAttribute filter in place to verify these headers are in place, unfortunately, authorization filter is executed first in the pipeline.

### Describe the solution you'd like
Ideally, I would like to mark my actions or controllers to evaluate that the request headers are in place before authorization is initiated.

### Describe alternatives you've considered
It would be very useful to change the response status and message depending on which requirement failed.

**Comment by rynowak** [comment]
I'd suggest implementing `IAuthorizationFilter` and `IOrderedFilter` on your filter class, and setting the `Order` to a low value so you run first.
