### ISSUE TITLE
Global Filters Order

### ISSUE THREAD

**Issue by Ali-Doustkani** [aspnet/AspNetCore#5152]
Filters of the same type (like `IResourceFilter`), with the same `IOrderedFilter.Order` are supposed to be ordered by their scope, which is working just fine. But when I add Global filters using the `Add<T>()` or `Add(Type)` method, it's not working correctly!
Version: 2.1

### To Reproduce
1. Create some filters:
```c#
public class Global1 : Attribute, IResourceFilter, IOrderedFilter
{
    public int Order => 1;

    public void OnResourceExecuted(ResourceExecutedContext context) { }

    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        Console.WriteLine("Global1");
    }
}

public class Global2 : Attribute, IResourceFilter, IOrderedFilter
{
    public int Order => 2;

    public void OnResourceExecuted(ResourceExecutedContext context) { }

    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        Console.WriteLine("Global2");
    }
}

public class Controller1 : Attribute, IResourceFilter, IOrderedFilter
{
    public int Order => 1;

    public void OnResourceExecuted(ResourceExecutedContext context) { }

    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        Console.WriteLine("Controller1");
    }
}

public class Controller2 : Attribute, IResourceFilter, IOrderedFilter
{
    public int Order => 2;

    public void OnResourceExecuted(ResourceExecutedContext context) { }

    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        Console.WriteLine("Controller2");
    }
}

public class Action1 : Attribute, IResourceFilter, IOrderedFilter
{
    public int Order => 1;

    public void OnResourceExecuted(ResourceExecutedContext context) { }

    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        Console.WriteLine("Action1");
    }
}

public class Action2 : Attribute, IResourceFilter, IOrderedFilter
{
    public int Order => 2;

    public void OnResourceExecuted(ResourceExecutedContext context) { }

    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        Console.WriteLine("Action2");
    }
}
```

2. Decorate an Action and a Controller with the appropriate filters:
```c#
[Controller1]
[Controller2]
public class HomeController : Controller
{
    [Action1]
    [Action2]
    public IActionResult Index()
    {
        return View();
    }
}
```

3. Configure MVC with global filters:
```c#
services.AddMvc(cfg =>
{
    cfg.Filters.Add<Global1>();  // or cfg.Filters.Add(typeof(Global1));
    cfg.Filters.Add<Global2>();  // or cfg.Filters.Add(typeof(Global2));
});
```

### Expected behavior
I suppose the output should be something like this:
> Global1  Controller1  Action1  Global2  Controller2  Action2

but it's not! Something's wrong with the global filters. This is what I get:
> Global1  Global2  Controller1  Action1  Controller2  Action2

You can generate the correct result only if you pass an instance of global filters to the add method:
```c#
cfg.Filters.Add(new Global1());
cfg.Filters.Add(new Global2());
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Ali-Doustkani.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Using `FilterCollection.Add` wraps the filter type in an instance of `TypeFilter` which has a default order of 0. There are overloads to `FilterCollection.Add` that let you specify the intended order of the filter: 

* https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.filtercollection.add?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_Filters_FilterCollection_Add_System_Type_System_Int32_
* https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.filtercollection.add?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_Filters_FilterCollection_Add__1_System_Int32_

The docs aren't clear about this behavior. We'd be happy to consider a PR to improve this in our API documentation: 
https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Filters/FilterCollection.cs
