### ISSUE TITLE
.net core 2.2 Downward compatibility problem（about cross domain）

### ISSUE THREAD

**Issue by JiangJiaqi90** [aspnet/AspNetCore#5155]
The code which developmented on .net core 2.1 SDK , when it  runs on the .net core 2.2 runtime, the signalr does not support cross-domain.
When I switch back to 2.1 runtime,the cross-domain problem solving.
In the same way, only signalr does not support cross-domain on Windows , and even common API on ubuntu do not support cross-domain .The solution is the same as above.

**Comment by BrennanConroy** [comment]
Dupe of https://github.com/aspnet/AspNetCore/issues/4483#issuecomment-445081348?

**Comment by pranavk** [comment]
@bradygaster I think you incorrectly mentioned me.

**Comment by pranavkm** [comment]
Very likely a dup of the other issue. @JiangJiaqi90 feel free to reopen if you believe this is a different issue.
