### ISSUE TITLE
Double compression when response returns ContentEncoding header

### ISSUE THREAD

**Issue by samisil** [aspnet/AspNetCore#5160]
When the back-end returns a compressed response, Microsoft.AspNetCore.ResponseCompression is double-compressing the response unnecessarily.

My sugestion is to check the response header ContentEncoding before begin to write and compress the content.

Here how I fix the problem locally:
```csharp
        private async void InternalWriteAsync(byte[] buffer, int offset, int count, AsyncCallback callback, TaskCompletionSource<object> tcs)
        {
            // Avoid to compress responses with any ContentEncoding header.
            if (_context.Response.Headers.ContainsKey(HeaderNames.ContentEncoding))
                _compressionChecked = true;

            try
            {
                await WriteAsync(buffer, offset, count);
                tcs.TrySetResult(null);
            }
            catch (Exception ex)
            {
                tcs.TrySetException(ex);
            }

            if (callback != null)
            {
                // Offload callbacks to avoid stack dives on sync completions.
                var ignored = Task.Run(() =>
                {
                    try
                    {
                        callback(tcs.Task);
                    }
                    catch (Exception)
                    {
                        // Suppress exceptions on background threads.
                    }
                });
            }
        }
```
Please consider those changes.

Regards

**Comment by Tratcher** [comment]
That exact check already exists over here:
https://github.com/aspnet/AspNetCore/blob/9e0d354e1bc261163e098a294bd811e73bc2bb8f/src/Middleware/ResponseCompression/src/ResponseCompressionProvider.cs#L179

Your change shouldn't have any effect. Can you debug through WriteAsync -> OnWrite -> ShouldCompressResponse?

**Comment by samisil** [comment]
Hi @Tratcher ,

I see that the check was added before I noticed. No need for my changes.

Thank you for your time.
