### ISSUE TITLE
Health Check - Provide support for OpenAPI

### ISSUE THREAD

**Issue by tomkerkhove** [aspnet/AspNetCore#5161]
The built-in support for health checks are great, but when you are using OpenAPI specifications this will not surface.

Are there plans to provide this capability/integration for 3rd party libraries?

This is currently holding me off of using it.

### Additional context
OpenAPI are a great way to describe your APIs, bot internally as externally. Health checks are a great example of an internal endpoint that you want to expose for tools/teams inside the company.

When you are exposing your APIs via an API Gateway (ie. Azure API Management/Kong) you will want to use OpenAPI specs to decorate your APIs and surface that information for your users.

**Comment by rynowak** [comment]
Hi @tomkerkhove - I don't think we have any easy path to provide this through the health checks *middleware*.

However, that shouldn't stop you from being able to use health checks with OpenAPI. You can write an MVC controller endpoint that calls into `HealthChecksService` (available from DI). This will enable you to do all of the things that MVC usually does for OpenAPI/Swagger support.

**Comment by tomkerkhove** [comment]
But then I would need to duplicate it given I need to create a health endpoint for OpenAPI anyway or am I missing something?

**Comment by rynowak** [comment]
The middleware is a really small piece of code. I runs the health checks service and then figures out how to respond.  https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/HealthChecks/src/HealthCheckMiddleware.cs#L51 

I suspect that if you care about having an OpenAPI description for health checks, then you'll probably want to customize the output 

Another alternative would be a use extensibility provided by your OpenAPI library to add support for it. How Swashbuckle and NSwag work today is through deep integration with MVC. For a bare piece of middleware, there isn't really any contract that describes the metadata your OpenAPI library is using. So I guess, which it would be theoretically possible for us to do this in the future, the health checks middleware doesn't have a realistic path to doing this automatically.
