### ISSUE TITLE
Name 'WebHost' does not exist

### ISSUE THREAD

**Issue by quentingarlan** [aspnet/AspNetCore#5162]
### Describe the bug
When using netcoreapp2.2 and Asp net Core 2.2.0 I get the error 'WebHost' does not exist in my buildWebHost function, going back to net Core 2.1 fix the issue.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run this code
```
public static IWebHost BuildWebHost(string[] args) =>
             WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
```
3. With these arguments '....'

### Screenshots

![image](https://user-images.githubusercontent.com/35103585/50089119-35aaf880-0205-11e9-8b17-ab4af3a24965.png)

### Additional context
CsProj

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <DockerTargetOS>Linux</DockerTargetOS>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>obj\Debug\netcoreapp2.1\Itga.Saam.WebApi.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\ValuesController.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="8.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
  </ItemGroup>

</Project>

**Comment by quentingarlan** [comment]
[Itga.Saam.WebApi.csproj.zip](https://github.com/aspnet/AspNetCore/files/2686126/Itga.Saam.WebApi.csproj.zip)

**Comment by quentingarlan** [comment]
For information a SO thread exists about this issue: 

https://stackoverflow.com/questions/53623730/webhost-doesnt-exist-in-the-current-context-in-asp-net-core-2-2-default-api-tem

**Comment by Eilon** [comment]
@Tratcher - any idea what could cause this issue?

**Comment by Tratcher** [comment]
It's either a dependency mismatch or a restore error. Or the using statement is missing?
@quentingarlan you included the csproj, can you also include program.cs?

**Comment by quentingarlan** [comment]
[Program.zip](https://github.com/aspnet/AspNetCore/files/2693862/Program.zip)

**Comment by quentingarlan** [comment]
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore;

namespace Itga.Saam.WebApi
{
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
             WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }
}

**Comment by quentingarlan** [comment]
Something must have been missing in bin/debug, I noticed a permission error while building with VS code. I could fix it by building in administrator mode.

**Comment by glatzert** [comment]
I've experienced this too, when I created a new project with ASP.NET Core 2.1 and then moved to ASP.NET Core 2.2 (by installing the SDK).

Deleting the obj folder fixed it for me.
