### ISSUE TITLE
Blazor: Error: Cannot write embedded resource from assembly 'Blazor.Extensions.SignalR.JS'

### ISSUE THREAD

**Issue by Apollo3zehn** [aspnet/AspNetCore#5163]
I am just setting up a project with ASP.NET as server and Blazor as client. I also use a `Directory.Build.props` file to load another .props file whose purpose is to redirect `bin` and `obj` folders into artifacts folder. This redirection causes the following error:

Cannot write embedded resource from assembly 'Blazor.Extensions.SignalR.JS' to 
C:\Users\wilvin\Desktop\IBOW\artifacts\obj\xx\Debug\netstandard2.0\blazor\_content\Blazor.Extensions.SignalR.JS because it is outside the expected directory
C:\Users\wilvin\Desktop\IBOW\build\..\artifacts\obj\xx\Debug\netstandard2.0\blazor

The difference is: `IBOW\build\..\artifacts` vs `IBOW\artifacts`, which is the same path. If I normalize the path with msbuild first, there is no problem. Example:

```
<ArtifactsPath>$([MSBuild]::NormalizePath($(MSBuildThisFileDirectory)../artifacts))</ArtifactsPath>

<BaseIntermediateOutputPath>$(ArtifactsPath)/obj/$(MSBuildProjectName)</BaseIntermediateOutputPath>
<IntermediateOutputPath>$(BaseIntermediateOutputPath)/$(Configuration)</IntermediateOutputPath>
<OutputPath>$(ArtifactsPath)/bin/$(MSBuildProjectName)/$(Configuration)</OutputPath>
```

I think the best way to solve it in general is if [this](https://github.com/aspnet/AspNetCore/blob/master/src/Components/src/Microsoft.AspNetCore.Components.Build/Core/EmbeddedResources/EmbeddedResourcesProcessor.cs#L79-L82) code block is normalizing the paths before comparison, so that no msbuild normalization is required.

**Comment by rynowak** [comment]
We're recommend that static content use a project relative path within the project. We have no plans to address this for now, will reconsider based on feedback.
