### ISSUE TITLE
[Blazor] Blazor client-side BrowserHttpMessageHandler uses Uri.ToString() which unescapes characters

### ISSUE THREAD

**Issue by zdenek-jelinek** [aspnet/AspNetCore#5164]
### Symptoms
Sending a HTTP Request with URI containing escaped ``{``, ``:`` or ``}`` characters (``%7B``, ``%3A``, ``%7D``) through HttpClient in Blazor client-side causes the browser to request a resource on the URI with those characters unescaped.

### Reproduction
Using Blazor 0.7.0 client-side, execute the following:
``` C#
string complexParameter = @"{""key"":""value""}";
string encodedParameter = WebUtility.UrlEncode(complexParameter); // %7B%22key%22%3A%22value%22%7D"
string uri = $"https://contoso.com?parameter={encodedParameter}";

await _httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Get, uri));
```
**Actual behavior**
The browser sends `GET https://contoso.com?parameter={%22key%22:%22value%22}` to which some webservers respond with HTTP 400 Bad Request as that URI contains invalid characters according to [RFC-3986](https://tools.ietf.org/html/rfc3986). This is somewhat complicated by the fact that browsers also attempt to neaten the URI and unescape the characters.

**Expected behavior**
The browser sends `GET https://contoso.com?parameter=%7B%22key%22%3A%22value%22%7B`, which is [RFC-3986](https://tools.ietf.org/html/rfc3986)-compliant.

### Further details
Blazor's client-side [BrowserHttpMessageHandler.SendAsync](https://github.com/aspnet/AspNetCore/blob/cc899e2be729364589ba7f4392bce9942e4faca4/src/Components/src/Microsoft.AspNetCore.Components.Browser/Http/BrowserHttpMessageHandler.cs#L40) uses [HttpRequestMessage.RequestUri.ToString()](https://github.com/aspnet/AspNetCore/blob/cc899e2be729364589ba7f4392bce9942e4faca4/src/Components/src/Microsoft.AspNetCore.Components.Browser/Http/BrowserHttpMessageHandler.cs#L66) to supply the URI to JavaScript's Fetch API. [Uri.ToString()](https://docs.microsoft.com/en-us/dotnet/api/system.uri.tostring?view=netstandard-2.0) is specified in the .NET Standard as "All characters are unescaped except #, ?, and %.". This basically undoes any escaping done so far on the C#-side, which is all the escaping a developer using Blazor might do.

Passing into JavaScript realm, the [Fetch API is invoked](https://github.com/aspnet/AspNetCore/blob/cc899e2be729364589ba7f4392bce9942e4faca4/src/Components/src/Microsoft.AspNetCore.Components.Browser.JS/src/Services/Http.ts#L27) with the unescaped URI, attempting to escape it as best as it can before sending it, escaping back many of the previously unescaped characters (see [Fetch API URL spec/URL Parsing](https://url.spec.whatwg.org/#url-parsing)).

Therefore, a lot of escaping cases still work as the unescaping is covered up by the Fetch API. In the case of ``:``, ``{`` and ``}`` characters, however, the unescaped form is kept and sent as part of the HTTP request.

**Comment by rynowak** [comment]
The fix for this is for us to use the built-in message handler that mono provide.

**Comment by mkArtakMSFT** [comment]
Will be tracking the work as part of: https://github.com/aspnet/AspNetCore/issues/10489
