### ISSUE TITLE
Clarify browser support for Blazor

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/AspNetCore#5165]
I don't see much information on browser support, although I get the impression this is supposed to work on any browser thanks to the JavaScript fallback, but when I google about Blazor I read up that support for Internet Explorer 11 is not a priority.

I also found the following snippet of text:

> For older browsers that don't support WebAssembly, we recommend running Blazor with server-side execution. This produces the same interactive client-side application feel, but with your components executed on the server and events proxied over a socket connection. This removes all the heavy load from the browser and allows excellent performance and compatibility with even the oldest browsers. Please note however that the default Blazor project templates do not include all the polyfills needed for Internet Explorer or some other older browsers, so if you need to support them, you'll need to reference suitable polyfill JS libraries (example).

But this again doesn't explicitly mention about Internet Explorer 11, in which support seems contrary to information on the same page, despite me thinking that most would consider IE 11 a modern browser in the sense that it is very much in the mainstream.

Could you please clarify whether Blazor runs in Internet Explorer 11, and if so, what steps are needed to get Blazor running in Internet Explorer 11, and also update the notes in regards to Blazor so that others with the same question can find the answer they are looking for.

This is all the more important with Blazor being part of the conglomerate ASP.NET Core 3 release.

**Comment by Matthew-Bonner** [comment]
Source for my quote:
https://github.com/aspnet/Blazor/wiki/FAQ

**Comment by SteveSandersonMS** [comment]
> Could you please clarify whether Blazor runs in Internet Explorer 11

Only server-side execution is supported for IE11, because IE11 doesn't support WebAssembly.

> I get the impression this is supposed to work on any browser thanks to the JavaScript fallback

No, we removed the asm.js fallback because it isn't fast enough. For pre-WebAssembly browsers, you should use server-side execution.

> what steps are needed to get Blazor running in Internet Explorer 11

Use server-side execution. You may also need to add polyfills such as https://polyfill.io/v2/docs/

**Comment by Matthew-Bonner** [comment]
Thanks for your explanation, could you please clarify what is meant by "may need to add polyfills" as I've heard this before but the explanation doesn't really specify in what scenarios polyfills are required.

**Comment by Andrzej-W** [comment]
@Matthew-Bonner 
> in what scenarios polyfills are required

Blazor is modern framework and even in server-side mode it uses some new JavaScript constructs which are not supported by older browsers, for example promises.
https://caniuse.com/#search=promises
