### ISSUE TITLE
Example for authentication

### ISSUE THREAD

**Issue by lednhatkhanh** [aspnet/AspNetCore#5167]
Hi, I want to ask if there is any example for authentication for angular 2? I'm very new to this so I have no idea about this, it would be good if we can have a working example for authentication!

**Comment by arshadwhoami** [comment]
Hi ,Is there any sample for msal authentication  through react  as frontend and asp.net core as backend in which tokens has to be passed for calling web api's

**Comment by mkArtakMSFT** [comment]
@javiercn isn't this now covered with the recent changes in SPA templates?

**Comment by javiercn** [comment]
@mkArtakMSFT Yes, but for modern versions of angular. The code is in the template, so users can grab it as a starting point to adjust it for an older version.
