### ISSUE TITLE
Recursive fetch doesn't work on server-side

### ISSUE THREAD

**Issue by rosieks** [aspnet/AspNetCore#5168]
I tried to run such code on server-side but for some reason it doesn't work. `fetch` function is imported from `domain-task`

    return fetch('https://jsonplaceholder.typicode.com/posts/1')
        .then(response => response.json())
        .then(response => {
            return fetch('https://jsonplaceholder.typicode.com/posts/2')
                .then(response2 => response2.json())
        });

I receive the following error:

    Exception: Call to Node module failed with error: Error: 
    When running outside the browser (e.g., in Node.js), you must specify a base URL
    before invoking domain-task's 'fetch' wrapper.
    Example:
    import { baseUrl } from 'domain-task/fetch';
    baseUrl('http://example.com'); // Relative URLs will be resolved against this

**Comment by SteveSandersonMS** [comment]
Sorry this never got a timely response.

I think the behavior reported here comes down to a [Node issue whereby it fails to preserve domain context in native Promise continuations](https://www.google.com/search?client=firefox-b-d&q=node.js+domain+promises). That's not something we can directly fix, so if you're chaining promises and using `addTask`, I think you'll unfortunately have to re-assign the `baseUrl` at the start of each continuation (e.g., by calling `baseUrl('http://example.com')`).

@mkArtakMSFT Propose we close this as it's an external (Node) bug that we're not planning to work around.
