### ISSUE TITLE
Cannot find module 'aspnet-webpack'

### ISSUE THREAD

**Issue by RaleS** [aspnet/AspNetCore#5169]
Exception thrown when starting the app created by using Service Fabric Asp.Net Core 2.0 Angular template. Running on Service Fabric 5.7.198.

"Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'\n    at Function.Module._resolveFilename (module.js:485:15)\n    at Function.Module._load (module.js:437:25)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (C:\\SfDevCluster\\Data\\_App\\_Node_2\\Application4Type_App59\\temp\\nlcuhlos.kzt:83:19)\n    at __webpack_require__ (C:\\SfDevCluster\\Data\\_App\\_Node_2\\Application4Type_App59\\temp\\nlcuhlos.kzt:20:30)\n    at createWebpackDevServer (C:\\SfDevCluster\\Data\\_App\\_Node_2\\Application4Type_App59\\temp\\nlcuhlos.kzt:62:26)\n    at C:\\SfDevCluster\\Data\\_App\\_Node_2\\Application4Type_App59\\temp\\vyr4pqpo.yvi:114:19\n    at IncomingMessage.<anonymous> (C:\\SfDevCluster\\Data\\_App\\_Node_2\\Application4Type_App59\\temp\\vyr4pqpo.yvi:133:38)\n    at emitNone (events.js:105:13)\nCurrent directory is: C:\\SfDevCluster\\Data\\_App\\_Node_2\\Application4Type_App59\\Web1Pkg.Code.1.0.0\r\n"

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
