### ISSUE TITLE
Formatting issues (dots replaced by underscores) in namespaces generated by the SPA templates.

### ISSUE THREAD

**Issue by ehouarn-perret** [aspnet/AspNetCore#5170]
When creating a new solution and say a project with name like `SolutionName.ProjectName` using one of the SPA templates, the generation of the `*.cs` files (and maybe some others?) ends up with an underscore instead of the original dot in the namespaces, e.g. `SolutionName_ProjectName`. Is there anything that can be done in that regard?

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
