### ISSUE TITLE
Invalid/Old documentation for nodejs debugging

### ISSUE THREAD

**Issue by CamiloTerevinto** [aspnet/AspNetCore#5171]
The documentation [here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-it-runs-on-the-server) states:

```
warn: Microsoft.AspNetCore.NodeServices[0]
      Debugger listening on port 9229.
warn: Microsoft.AspNetCore.NodeServices[0]
      Warning: This is an experimental feature and could change at any time.
warn: Microsoft.AspNetCore.NodeServices[0]
      To start debugging, open the following URL in Chrome:
warn: Microsoft.AspNetCore.NodeServices[0]
          chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

However, I do not see any of those messages:

```
warn: Microsoft.AspNetCore.NodeServices[0]
Debugger listening on ws://127.0.0.1:50251/3d85c7fc-39bc-44c2-a3c4-e38dbb2c80e1
warn: Microsoft.AspNetCore.NodeServices[0]
 For help see https://nodejs.org/en/docs/inspector
```

And the nodejs help is useless.

If I go to (manually, of course): 

`chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:50251/`

I get:

> Debugging connection was closed. Reason: Websocket disconnected

Further info:

```
node -v => 8.2.1
Microsoft.AspNetCore.All => 2.0.0
Windows 10
```

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
