### ISSUE TITLE
Please update ReadMe documentation

### ISSUE THREAD

**Issue by RichDef77** [aspnet/AspNetCore#5173]
Hello,

I've set up a new .Net Core 2.0 project using the Angular SPA template provided by the JavaScript Services library. This template uses Angular 4 but I noticed that the documentation seems to be outdated.

Could you please update the documentation/ read me file to reflect the updates to Angular 4 and Webpack 3?

I'm trying to understand how the webpack configuration works with the latest version of the Angular SPA template. Having the documentation outdated is just making things more confusing.

Many thanks!

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
