### ISSUE TITLE
IE11 works at the beginning with polyfills, but making an exception right after 45 seconds.

### ISSUE THREAD

**Issue by okmoogle** [aspnet/AspNetCore#5174]
My enviroment simply,
 - VS2017
 - core 2.0
 - using spa template which VS supplies
 - dubuging mode
 (after deploying it to iis, it dosen't make an exception error.)

I still have a problem with IE11, even though I followed the guidline as below link.
I did install core-js 2.5.1, and import all the polyfills in this article.
(https://github.com/aspnet/JavaScriptServices/wiki/Supporting-Internet-Explorer-11-(or-older))
That sample program runs with the treat, however after 45 secs without any touching the web browser, it emit exceptions as below.

![image](https://user-images.githubusercontent.com/23288784/33217175-3c2c4f9a-d17a-11e7-970e-e9bbc7d45027.png)

Is there anyone who had same problem with me?
I can't use any other ever-green browsers because of some policy.

Thanks in advance.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
