### ISSUE TITLE
404 when publicPath is set to "/"

### ISSUE THREAD

**Issue by crhairr** [aspnet/AspNetCore#5175]
The bug appears to be related to this this line:

https://github.com/aspnet/JavaScriptServices/blob/5f6f288056b3263a61a55631257db14314a02795/src/Microsoft.AspNetCore.SpaServices/Webpack/WebpackDevMiddleware.cs#L114

My webpack config has the following output:

```#js
        "output": {
            "filename": "js/[name].js",
            "path": OutputPath,
            "publicPath": "/"
        },
```

If I set the and the WebpackDevMiddleware like such:

```C#
                    .UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                    {
                        HotModuleReplacement = true
                    });
```

Then the hmrEndpoint defaults to "/__webpack_hmr" and the SpaProxy url ends up as "//__webpack_url". Every request to `[xxx].hot-update.json` (e.g.: `http://localhost:5000/7d73bb05e2e2c47519ea.hot-update.json`) fails with a 404.

However, if I set up my webpack config like this:

```#js
        "output": {
            "filename": "js/[name].js",
            "path": OutputPath,
            "publicPath": "/dist/"
        },
```

Then the SpaProxy url is set to "/dist//__webpack_url" and any request to find the hot-update config (e.g.: `http://localhost:5000/dist/7d73bb05e2e2c47519ea.hot-update.json`) works.

FWIW: overriding the HmrEndpoint to "__webpack_hmr" does not seem to get around the problem:

```C#
                    .UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                    {
                        HotModuleReplacement = true,
                        HotModuleReplacementEndpoint = "__webpack_hmr"
                    });
```

Also, leaving the `publicPath` blank ("") results in an error.

EDIT: if this is the expected behavior (that `publicPath` is required to be set to "/dist/") then the documentation should reflect this. Otherwise, this is a bug likely due to oversimplification of the logic that builds the proxy server URLs.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment]
I wasn't able to replicate this locally using our [WebPack sample](https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/SpaServices/samples/Webpack). Could someone still experiencing this produce a repro project that I could use to investigate?

**Comment by ryanbrandenburg** [comment]
Closing this as we have no repro. If someone is still having trouble here create a new issue with a reproduction app and reference this issue.
