### ISSUE TITLE
aspnet-webpack: mismatch in environmentvariables

### ISSUE THREAD

**Issue by rjgotten** [aspnet/AspNetCore#5176]
The Microsoft.AspNetCore.SpaServices 2.0.2 NuGet package sends a property named `EnvironmentVariables` for the environment variables passed to the Webpack dev middleware.

The aspnet-webpack 2.0.3 NPM module expects a property `EnvParam`.

The result is that a webpack configuration that exports a function expecting an environment, is passed `undefined` instead of an object.

(Also; I'm not sure, but it may need to be passed the values in `process.env` and at the very least should be passed an empty object. Not `undefined`.)

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
