### ISSUE TITLE
Retain custom added response headers when serving UseSpaPrerendering response

### ISSUE THREAD

**Issue by speige** [aspnet/AspNetCore#5177]
UseSpa has configuration.options.DefaultPageStaticFileOptions.OnPrepareResponse
UseSpaStaticFiles has options.OnPrepareResponse

UseSpaPrerendering does not have this option.

Without this, I cannot add http cache headers, so any server-side rendered Angular/React pages will be re-requested by the browser on each refresh. They also cannot be server-side cached via app.UseResponseCaching(); because it is looks at the http cache headers.

app.UseResponseCaching() would be ideal for server-side rendering because TimeToFirstByte can be slow for non-trivial apps. UseSpaPrerendering actually boots up a separate node instance to run your server app for every incoming request, it doesn't leave the app running in-beween requests. This can be worse if your app bootup is slower than normal (i.e. has setTimeouts, needs ajax data, parses large json files, etc). Also, if you're using extra Middleware like app.UseResponseCompression() TTFB will be even slower. 

One workaround is to create a custom middleware to add the headers after SpaPrerendering is done. However, it is a little tricky because you can't easily modify the response after SpaPrerendering is complete. One option used by many other middlewares is to create a "shim" to wrap the real response stream with a fake one.
Example below:
```
  public class ShimmedResponseContext
  {
    public HttpContext _httpContext { get; }
    private Stream _originalResponseStream { get; set; }
    private MemoryStream _shimmedResponseStream { get; set; }

    public ShimmedResponseContext(HttpContext httpContext)
    {
      _httpContext = httpContext;
    }

    public void ShimResponseStream()
    {
      _originalResponseStream = _httpContext.Response.Body;
      _shimmedResponseStream = new MemoryStream();
      _httpContext.Response.Body = _shimmedResponseStream;
    }

    public void UnshimResponseStream()
    {
      _shimmedResponseStream.Position = 0;
      _shimmedResponseStream.CopyTo(_originalResponseStream);
      _httpContext.Response.Body = _originalResponseStream;
    }
  }
  
  app.Use(async (context, next) =>
  {
	var shimmedContext = new ShimmedResponseContext(context);
	shimmedContext.ShimResponseStream();

	await next();

	context.Response.Headers[HeaderNames.CacheControl] = "public,max-age=" + TimeSpan.FromDays(30).TotalSeconds;
	context.Response.GetTypedHeaders().CacheControl = new CacheControlHeaderValue()
	{
	  Public = true,
	  MaxAge = TimeSpan.FromDays(30)
	};
	context.Response.Headers[HeaderNames.Vary] = new string[] { "Accept-Encoding" };
	shimmedContext.UnshimResponseStream();
  });
  
  app.UseSpa(spa => { ...
	spa.UseSpaPrerendering(options => ...
```

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.

**Comment by vahivsky** [comment]
Hey, I've just ran into the same issue, while trying to use SPA prerendering libraries with Response Caching middleware. Took me a while to find that `context.Response.Clear();` in SPA prerendering, preventing response caching to work. 

That is important to be able to cache prerendering result, as prerendering takes time. This is surprising to see this issue closed without any fix.
