### ISSUE TITLE
aspnet-webpack-react not compatible with react-hot-loader v4

### ISSUE THREAD

**Issue by Guymestef** [aspnet/AspNetCore#5178]
Hello,

react-hot-loader/patch has been removed from react-hot-loader v4: [See documentation here](https://github.com/gaearon/react-hot-loader#no-patch-required)

A new package for aspnet-webpack-react (v4.0.0?), removing support of "reactHotLoaderPatch", need to be created I suppose.

[To remove?](https://github.com/aspnet/JavaScriptServices/blob/04b8c17bdded1d7652f18587a920f740d42985ff/src/Microsoft.AspNetCore.SpaServices/npm/aspnet-webpack-react/src/HotModuleReplacement.ts#L4)
```typescript
const reactHotLoaderPatch = 'react-hot-loader/patch';
```

[To remove?](https://github.com/aspnet/JavaScriptServices/blob/04b8c17bdded1d7652f18587a920f740d42985ff/src/Microsoft.AspNetCore.SpaServices/npm/aspnet-webpack-react/src/HotModuleReplacement.ts#L52)
```typescript
        let entryValueArray = entryConfig[entrypointName] as string[];
        if (entryValueArray.indexOf(reactHotLoaderPatch) < 0) {
            entryValueArray.unshift(reactHotLoaderPatch);
        }
```

[react-hot-loader release note](https://github.com/gaearon/react-hot-loader/issues/707)

**Comment by mkArtakMSFT** [comment]
Closing as this seems to be resolved now.
