### ISSUE TITLE
Corrupted characters in response

### ISSUE THREAD

**Issue by andreymir** [aspnet/AspNetCore#5179]
I found this code in HttpNodeInstanceEntryPoint.ts file. As I understand, it read and parse request stream and chunk is a byte array. We convert it to string and append to requestBodyAsString.
In utf-8 a symbol could be represented not only by a single byte, but by sequence of bytes. So, the start or the end of the chunk could contain incomplete character sequence.
``` typescript
function readRequestBodyAsJson(request, callback) {
    let requestBodyAsString = '';
    request.on('data', chunk => { requestBodyAsString += chunk; });
    request.on('end', () => { callback(JSON.parse(requestBodyAsString)); });
}
```

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
