### ISSUE TITLE
Incorrect angular cli port when running using UseAngularCliServer middleware

### ISSUE THREAD

**Issue by asadsahi** [aspnet/AspNetCore#5183]
Is this me or something's wrong when trying to run with UseAngularCliServer I get this:

![image](https://user-images.githubusercontent.com/3470892/40681322-b90fb8a6-6380-11e8-8c63-b482ec15d45a.png)

As can be seen that the port that angular cli is running is wrong. I also tried running using --port=4200 but then I get this in browser:

![image](https://user-images.githubusercontent.com/3470892/40681469-2025c9d6-6381-11e8-85be-4b6992b1ba6a.png)

I have just updated SPA extension package to 2.1.

Can be replicate in [this](https://github.com/asadsahi/AspNetCoreSpa/tree/sln) branch

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
