### ISSUE TITLE
Location of aspnet-webpack

### ISSUE THREAD

**Issue by dogwith1eye** [aspnet/AspNetCore#5187]
I'm building a development docker container, so the ASPNETCORE_ENVIRONMENT is set to Development, as i would like to support hmr in the development container.

However, i keep running into the following issue.

Error was: Error: Cannot find module 'aspnet-webpack'

I guess it's not clear to me where this file is supposed to exist. If i'm running in development mode natively, then it's a few folder up in node_modules from the application.dll. I've looked through the source code and it's still unclear to me what the path to the 'aspnet-webpack' from the application.dll is supposed to be?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
