### ISSUE TITLE
Too limited

### ISSUE THREAD

**Issue by JCKodel** [aspnet/AspNetCore#5188]
I develop using vue with hot reloading (meaning that my node server is in port 8080 with a websocket for hot reloading).

Using the react spa option the hot reloading kinda works, but the port is random (I have cookies and other stuff that cannot be lost between compilations - a random port for each execution is so stupid).

Using the proxy version disables the hot reload.

So... pretty useless =\

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
