### ISSUE TITLE
ReactDevelopmentServer does not honor ContentRoot

### ISSUE THREAD

**Issue by pardahlman** [aspnet/AspNetCore#5189]
I noticed that `ReactDevelopmentServer` starts a process with [working directory set to `SourcePath`](https://github.com/aspnet/JavaScriptServices/blob/96d7f853277788d52dc33027f31a8db4c4786cf1/src/Microsoft.AspNetCore.SpaServices.Extensions/Npm/NpmScriptRunner.cs#L56)  from `SpaOption` without considering that it may be relative, and thus should be relative to the [content root](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/index?view=aspnetcore-2.1&tabs=aspnetcore2x#content-root).

I think that it would make sense to append content root to `SourcePath` if `SourcePath` is relative. Then, as a bonus, I think it would be nice if an `DirectoryNotFoundException` was thrown if the source path doesn't exist. I got tricked by [generic error message](https://github.com/aspnet/JavaScriptServices/blob/96d7f853277788d52dc33027f31a8db4c4786cf1/src/Microsoft.AspNetCore.SpaServices.Extensions/Npm/NpmScriptRunner.cs#L122) when this failed for me and started to troubleshoot elsewhere.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
