### ISSUE TITLE
Angular SPA Template Returning Status Code from Angular App

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/AspNetCore#5190]
It seems that the SpaPrerendering services support returning proper status code such as 404 for not found error (https://github.com/aspnet/JavaScriptServices/issues/1423).

But the documentation lacks the details on how do we return the status code from the Angular App.

Can you please guide and update the docs?

Thank you

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
