### ISSUE TITLE
publish ssr angular example doesn't work

### ISSUE THREAD

**Issue by j-nord** [aspnet/AspNetCore#5191]
When we use your example in Visual Studio 2017 with the angular template and want publish with server side rendering we get an errror:

Unable to find app with name or index. Verify the configuration in `.angular-cli.json`

We have only changed the property BuildServerSideRenderer=true in the project file "csproj". All other code was not changed.

Regards
j-nord

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
