### ISSUE TITLE
POST /index.html fails with 500 error

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/AspNetCore#5192]
Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware+<>c__DisplayClass0_0.<Attach>b__1

No doubt this is the result of people trying to hack our site by POSTing instead of GETing but it's throwing 500 errors as a result:

The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

This was fine in RC2 but now errors in Final of 2.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JohnGalt1717.
@SteveSandersonMS, @ryanbrandenburg any suggestions regarding what's causing this behavior?

**Comment by mkArtakMSFT** [comment]
We're closing this issue as we will not be supporting NodeServices going forward, as is pointed out at https://github.com/aspnet/AspNetCore/issues/12890.
