### ISSUE TITLE
npm is not looked up in External Web Tools Path

### ISSUE THREAD

**Issue by atiq-cs** [aspnet/AspNetCore#5193]
Here's the reference sourcecode where npm is invoked with a cmd command
  https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices.Extensions/Npm/NpmScriptRunner.cs

It looks like if for some reason we don't include node path in environment's path npm is not found. npm should be looked up in External Web Tools Path first. If not found then should be invoked like `cmd /c npm ....`

Here's an example, how node is updated for VS and it will not work if we don't update environment's path. https://stackoverflow.com/questions/43849585/update-node-version-in-visual-studio-2017

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
