### ISSUE TITLE
Pre-populating redux state on the server

### ISSUE THREAD

**Issue by onionhammer** [aspnet/AspNetCore#5195]
I noticed that the `reactredux` template includes a reference to server side rendering, but I can't find any guidance on how to actually fill that (idiomatically)

```C#

// Get the application-wide store instance, prepopulating with state from the server where available.
const initialState = window.initialReduxState;

const store = configureStore(history, initialState);

```

that `initialReduxState` is exactly what I want to pre-fill, but index.html that comes with the template is static

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
