### ISSUE TITLE
EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

### ISSUE THREAD

**Issue by tachyon77** [aspnet/AspNetCore#5196]
I have looked at the existing threads on this. 
But my issue is happening on production mode, not development. So the 

> HotModuleReplacementEndpoint = "/dist/__webpack_hmr"

Fix doesn't work for me.

I am using ASP.NET Core 2, Angular 6, Webpack, Visual studio.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please have a look at this when there'll be a repro? Thanks!

**Comment by ryanbrandenburg** [comment]
A reminder that in order to investigate this we'll need a repro app.

**Comment by ryanbrandenburg** [comment]
As there's been no repro I'm closing this issue. If anyone is experiencing this issue and has a repro app that they can share with us please open a new issue and tag this one in it.
