### ISSUE TITLE
__webpack_hmr is being requested in release/production build

### ISSUE THREAD

**Issue by tachyon77** [aspnet/AspNetCore#5197]
This results in the following error printed out every 20 seconds in browser console. 20 seconds the timeout set in HMR.

**EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.**

My configure doesn't have anything funny for the production case:

`if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true
                });
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }`

And I **don't** get any message saying "Angular is running in development mode. Call enableProductionMode()" so I am hoping production mode is turned on.

My guess is, my configuration is still somewhere telling it's a debug env. In that case, I need to know what's the right way to set env mode.

My setup is:

- ASP.NET CORE 2.x, 

- Used Visual Studio 2017 Angular project template to create the project

- Angular 6

- "webpack": "4.11.0",
    "webpack-command": "0.2.0",
    "webpack-hot-middleware": "2.22.2",
    "webpack-merge": "4.1.2"

- Azure for production deployment

- The publish GUI in visual studio to deploy/publish.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tachyon77.
@ryanbrandenburg, can you please look into this? Thanks!
Ping @SteveSandersonMS, in case you know what's going on here.

**Comment by mkArtakMSFT** [comment]
Seems related: https://github.com/aspnet/AspNetCore/issues/5196

**Comment by ryanbrandenburg** [comment]
As there's been no repro I'm closing this issue. If anyone is experiencing this issue and has a repro app that they can share with us please open a new issue and tag this one in it.
