### ISSUE TITLE
InvokeAsync<Task<Stream>> react streaming

### ISSUE THREAD

**Issue by morriq** [aspnet/AspNetCore#5199]
Hello,

I would like to use react **streaming** server side rendering.

To do this I can't  wait for whole resposnse from `InvokeAsync<Task<Stream>>`

does this library support this approach?

My code is simple:
```
            Console.WriteLine(DateTime.Now + " start");

            Task<Stream> task = nodeServices.InvokeAsync<Task<Stream>>("./async-react");
```

Adding on the bottom:

`var stream = task.Result;`

blocks response till streaming ends.

Thanks for any help.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
