### ISSUE TITLE
Add create-react-app SSR template

### ISSUE THREAD

**Issue by JoshClose** [aspnet/AspNetCore#5200]
It looks like the templates have moved to using create-react-app. This is great and makes things more standard.

We still need server side rendering.

I've been looking into this a little and there seems to be some libraries that claim to add SSR to a CRA project without ejecting. Here are a couple.

https://github.com/antonybudianto/cra-universal
https://github.com/smooth-code/loadable-components

It would be nice if there was an option when doing `dotnet new` to create a react/redux project that has SSR built in for ASPNET Core. `dotnet new reactreduxssr` or something like that.

Not having SSR really makes CRA apps not usable for public websites.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

**Comment by JoshClose** [comment]
This is still a feature that I would very much like.

**Comment by TomasHubelbauer** [comment]
Please consider reopening this feature request. There may be no community involvement, but it is still a valid feature request.

**Comment by JoshClose** [comment]
I'm happy to talk about what features we would like. I know @SteveSandersonMS is a busy guy so I didn't want to bug him about this.

**Comment by TomasHubelbauer** [comment]
You mentioned there used to be a template with SSR which was removed in favor of a CRA based on. Maybe there is value in finding how compatible the previous SSR solution would be with CRA? For myself, I would like the ultimate solution to .NET Core SSR to be standalone so that it can be used without starting off from a CRA based template, but even when that would not be an option, there is still value in making it work with a template that encompasses both the FE and BE.

**Comment by JoshClose** [comment]
If you create the project using core 1.1, you'll get the old SSR template. I think moving to CRA is a good idea since that is the industry standard now. I think SSR just needs to be added into it.

**Comment by TomasHubelbauer** [comment]
Sorry, that is what I meant to express in my previous comment.

**Comment by Weffe** [comment]
@JoshClose Are you looking for a project like [ReactJS.NET](https://reactjs.net)? They have outlined a guide on how to configure SSR [here](https://reactjs.net/features/server-side-rendering.html). But I do understand and support the importance of having an SSR template available for .NET Core. I was just reading up on [GatsbyJS](https://www.gatsbyjs.org/) and really liked how simple it was to create static sites but that's not true SSR. I think trying to integrate SSR as a template could be very messy if we want to use CRA. I think if we want to provide a good developer UX then it might be necessary to abstract things away into its own framework but then that's just repeating the work of ReactJS.NET.

**Comment by JoshClose** [comment]
All that stuff is actually currently available as a part of ASP.NET JavaScript Services, so I don't think there would be a need for ReactJS.NET. MS also published some NPM packages to allow for this.

I use [React Static](https://react-static.js.org/) for static sites, as Gatsby was missing a few features that I needed.

If I ever get to a point where I need SSR and want to use CRA, I'll probably end up doing it myself. I just don't have the time right now as there isn't an urgent need.

**Comment by NickMaev** [comment]
Look at the [React Core Boilerplate](https://github.com/NickMaev/react-core-boilerplate). It includes SSR, React, Redux and many other things. It's not a CRA, but it is used in many projects in production.
