### ISSUE TITLE
SSR Publishing - Unable to copy file node_modules\.cache\uglifyjs-webpack-plugin\content-v2\sha512...

### ISSUE THREAD

**Issue by CybrZr00** [aspnet/AspNetCore#5202]
Hi,

 When attempting to publish (to folder) the SSR version of the Angular Template it fails trying to copy dev deps over with the error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Unable to copy file "G:\users\markp\source\repos\cbl-5ssr\MergateCottage\ClientApp\node_modules\.cache\uglifyjs-webpack-plugin\content-v2\sha512\94\0b\d3cf31226e585196aa96c3622c8466b425df3355dd7a7cfde2f6b2fd035eac22af113377667b301007c33ff35cbf2e53176bf339b369ffd3931dec2e1dff" to "G:\users\markp\source\repos\cbl-5ssr\MergateCottage\obj\Release\netcoreapp2.1\PubTmp\Out\ClientApp\node_modules\.cache\uglifyjs-webpack-plugin\content-v2\sha512\94\0b\d3cf31226e585196aa96c3622c8466b425df3355dd7a7cfde2f6b2fd035eac22af113377667b301007c33ff35cbf2e53176bf339b369ffd3931dec2e1dff". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.	MergateCottage		0	
>  

Even when I changed the target location to the root of my drive.  I remember reading that when publishing this template using ssr it VS trys to copy the whole node_modules folder, but I didn't expect it to not work at all. 

Here's my package.json:

```
{
  "name": "MergateCottage",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --extract-css",
    "build": "ng build --extract-css --aot",
    "build:ssr": "npm run build -- --app=ssr --output-hashing=media",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/platform-server": "^5.2.9",
    "@angular/router": "^5.2.9",
    "@nguniversal/aspnetcore-engine": "^6.0.0",
    "@nguniversal/common": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "angular-bootstrap-md": "^6.1.3",
    "angular-oauth2-oidc": "^4.0.2",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^4.1.1",
    "chart.js": "^2.7.2",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "ng-recaptcha": "^3.0.3",
    "primeicons": "^1.0.0-beta.8",
    "primeng": "^6.0.0-rc.1",
    "rxjs": "^5.5.6",
    "smart-buffer": "^4.0.1",
    "source-map": "^0.7.3",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.0",
    "@angular/compiler-cli": "^5.2.9",
    "@angular/language-service": "^5.2.9",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  },
  "optionalDependencies": {
    "node-sass": "^4.9.0"
  }
}
```
Are there any work arounds?

**Comment by ryzhovalexandr** [comment]
Have same problem. Any news about fix it from dev team? Half a year has gone.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
