### ISSUE TITLE
DefaultSpaStaticFileProvider should allow RootPath to be absolute or relative

### ISSUE THREAD

**Issue by simeyla** [aspnet/AspNetCore#5203]
**Issue**
Currently the `RootPath` that is specified in `SpaStaticFilesOptions` must be relative to the environment's `ContentRootPath`. This means you must keep your SPA source files under the containing project.

It is currently a silent failure if someone were to pass in an absolute path.

```
services.AddSpaStaticFiles(configuration =>
{
    configuration.RootPath = "ClientApp/dist";
})
```

**Requested feature**
`RootPath` should be able to be an absolute path. This would allow me to keep my SPA files outside of my 'bootstrapping' project. It would also reduce confusion if somebody tries to pass in a root path - which currently will be ignored.

```
services.AddSpaStaticFiles(configuration =>
{
    configuration.RootPath = @"d:\SharedAngularStuff\AngularProject1";
})
```

Currently doing this will fail because [`DefaultSpaStaticFileProvider.cs`](https://github.com/aspnet/JavaScriptServices/blob/30333e250abbfa8ce45cdcdb5b575f0397403a05/src/Microsoft.AspNetCore.SpaServices.Extensions/StaticFiles/DefaultSpaStaticFileProvider.cs) just uses `Path.Combine` to construct the absolute root path.

There also doesn't seem to be a way to pass in an alternative FileProvider.

**Complexity of fix**
Very simple:

```
var absoluteRootPath = Path.IsFullyQualified(options.RootPath) ? options.RootPath : Path.Combine(
                env.ContentRootPath,
                options.RootPath);
```

Must use `IsFullyQualified` and [not]((https://github.com/dotnet/corefx/issues/22345)) `IsPathRooted`.

(This would only apply to people who modify the .csproj file to change the source

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
