### ISSUE TITLE
HotModuleReplacement requires config to resolve `.js` extensions

### ISSUE THREAD

**Issue by AdamWillden** [aspnet/AspNetCore#5205]
Whilst attempting to experiment with how HMR works when enabling using `HotModuleReplacement = true`  I encountered the following console error at runtime:

```
Uncaught Error: Cannot find module 'webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true'
    at webpackMissingModule (client:1)
    at eval (client:1)
    at Object.0 (main.bundle.js:813)
    at __webpack_require__ (main.bundle.js:722)
    at main.bundle.js:789
    at main.bundle.js:792
```

This was due to my `webpack.config.ts` containing:
``` 
resolve: { extensions: ['.ts'] },
````
Instead of
``` 
resolve: { extensions: ['.js', '.ts'] },
````

I figured that my application was only going to be written in TypeScript and therefore I could omit `'.js'`. However I now realise that the HotModuleReplacement results in the modification of entry points to add the `webpackHotMiddlewareEntryPoint` which is a js file.

What are your thoughts on adding a check to error if `.js` is not contained within the extensions array or alternatively force adding it to the end of the array?

At very least I'm happy to have documented this for anyone else who may experience this 'issue'. I searched online only to find those who encountered the error [never shared the fix](https://github.com/aspnet/JavaScriptServices/issues/628#issuecomment-276346359) 🤦‍♂️

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AdamWillden.
@ryanbrandenburg, sounds reasonable to me. Is there any reason we won't include `.js` by default?

**Comment by ryanbrandenburg** [comment]
As I understand the ask here it's not that we should "include `.js` by default" in a webpack.config.ts file (as far as I can tell none of our tempates contain one of those). Rather, the ask was that we should throw an error in the WebpackDevMiddleware if .js is not in the "resolve.extensions" list. @AdamWillden did I interpret that correctly?

My instinct is that it's not really the MiddleWares place to police that kind of thing, but @SteveSandersonMS is in a position to correct me if I'm wrong.

**Comment by SteveSandersonMS** [comment]
> My instinct is that it's not really the MiddleWares place to police that kind of thing

I agree.

We can't imagine that `WebpackDevMiddleware` can realistically detect and correct a wide range of Webpack misconfigurations, so I don't see why we should handle this one specifically. If *lots* of people hit this then maybe there's an argument, but I think we've only heard of one person make this particular misconfiguration.

**Comment by ryanbrandenburg** [comment]
@AdamWillden given that we won't be doing the suggested work item I'm going to close this. But as you said, I'm sure someone else will find having the fix documented useful, so thanks!

**Comment by AdamWillden** [comment]
No problem :-) Thanks for taking the time to consider this.
