### ISSUE TITLE
Remove CRA dependence of ReactDevelopmentServerMiddleware

### ISSUE THREAD

**Issue by stephtr** [aspnet/AspNetCore#5207]
At the moment, the `ReactDevelopmentServerMiddleware` just works with apps bootstrapped by create-react-app, since in [ReactDevelopmentServerMiddleware.cs#L87](https://github.com/aspnet/JavaScriptServices/blob/cf659b3fda367619f3873bd5f0e445698cebe340/src/Microsoft.AspNetCore.SpaServices.Extensions/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs#L87) it waits for a specific text output "Starting the development server".
Custom react/webpack dev server apps work, as soon as one adds a `console.log('Starting the development server');`. I wonder if there would be another solution possible (or at least adding a parameter which skips this check and assumes, that the server is ready as soon as we start it)?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
