### ISSUE TITLE
Clash between server and client side routing for serving of js files and images

### ISSUE THREAD

**Issue by jjgriff93** [aspnet/AspNetCore#5209]
I'm having an issue where my Angular app, hosted by ASP.NET Core MVC, isn't serving images and files like vendor.js, with a `Failed to load resource: the server responded with a status of 404 (Not Found)` error.

I'm using an Angular app template called ngx-admin, and it has an option to prepend the app's routing with /#/ (so the full url would be `https://localhost:5001/#/pages/dashboard`). With this enabled everything works fine, and the images are served from the angular app /assets/ folder as expected; however because I can't use fragments (#) in a callback URL for Azure AD B2C authentication that I'm currently setting up, I can't use this hash option. 

I think the issue is that without the hash, the server side routing is clashing with the client side routing, and it's looking for images and scripts in `wwwroot` instead of the Angular application. 

How can I go about changing the routing so there aren't any clashes? Would really appreciate any help here (happy to share code examples etc.)

Thanks in advance!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
