### ISSUE TITLE
minifying/webpack node_modules for NodeServices

### ISSUE THREAD

**Issue by ADringer** [aspnet/AspNetCore#5211]
Hi,

I have a dotnet core Web Api that makes use of NodeServices. To deploy this to a local IIS site during the build I do `npm install` and then copy the `node_modules` folder into the publish folder.

This is now taking ~25 mins to build due to the size of node_modules and the number of files within.

I've had a look at the samples but can't see anything related to server side use. The examples are usually webpack'd and then the output file is referenced in the client HTML but in my case there is no client, just server side.

 Is it possible to webpack or minify this? Also it's obviously looking at the node_modules folder for it's references, if this was minified can I tell it to look at a different folder?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ADringer.
We're closing this issue as we will not be supporting NodeServices going forward, as is pointed out at https://github.com/aspnet/AspNetCore/issues/12890.
