### ISSUE TITLE
Angular: Prerendering does not work when app is published on server, does not display HTML tags on ViewSource page. On Local host It is working fine

### ISSUE THREAD

**Issue by MMilan19** [aspnet/AspNetCore#5212]
I have create the application with [ASP.NET Core X Angular] (14) - Server side rendering for SEO. All is working fine when publishing on local host but when I published on Server it is not working, It doesn't display HTML tags on view source.

Hope anyone find anything which can be helpful to me.

Thanks
Milan.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
