### ISSUE TITLE
Can't run sample app "Webpack"

### ISSUE THREAD

**Issue by evolvedlight** [aspnet/AspNetCore#5213]
### Functional impact
App runs but all requests to http://localhost:5000/__webpack_hmr are 404s

### Minimal repro steps

1. Clone this repo
2. Open sample app "WebPack"
3. Change target framework to netcoreapp2.1 as 2.2 isn't installed
4. Build, run the app
5. Check the network traffic/console - see that requests are failing

### Expected result
HMR requests work

### Actual result
Periodic requests to the __webpack_hmr page fail

### Further technical details
λ dotnet --version
2.1.300
λ node --version
v8.9.0
λ npm --version
5.5.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @evolvedlight.
As per https://github.com/aspnet/AspNetCore/issues/12890 we're deprecating support for HMR and will be relying on support for HMR from the underlying SPA services CLIs.
