### ISSUE TITLE
How to upgrade existing project with older template version to latest template version?

### ISSUE THREAD

**Issue by AlejandroFlorin** [aspnet/AspNetCore#5215]
I've just converted my existing Angular .Net Core 2.1 project in VS 2017 15.7.4 to the latest released version of the template (I was using the older version that came installed with VS). I installed the template with _dotnet new --install Microsoft.AspNetCore.SpaTemplates::*_, created a default project and them manually reworked my project by comparing the two. 

My question is, when version 2.1 is officially released, what is the best way to update my project to include the changes from 2.0.7 to 2.1? Do I need to do the same and compare the changed files or is there a better way?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
There is no automated path in doing this. The best suggestion would be to follow the migration guide for each release, where we point out the specific things to be updated/replaced.
