### ISSUE TITLE
The loading of the "aspnet-webpack" module does not follow Node.js rules

### ISSUE THREAD

**Issue by eric-914** [aspnet/AspNetCore#5221]
My particular situation is that I have multiple projects in my solution that make use of Node.js and its `/node_modules/` folder.  I want to have these projects share the same `/node_modules/` folder.  Each project copy is 350+Meg, plus I want to keep the projects using the same version of dependencies.

Node.js doesn't require that `/node_modules/` be in the same directory as the **project**, only that it exist somewhere up the parent-tree: [https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)

I simply moved `/node_modules/` up one folder, so it's at the **solution** level, rather than the **project** level.  This works fine for everything except for `WebpackDevMiddleware.UseWebpackDevMiddleware(...)`.  It is looking for `/node_modules/` at the **project** level, and only there.  It will not do the traversal.  Hence this issue.

I have found a workaround:  Create an empty `/node_modules/` folder at the **project** level, then add a symlink to the real location of "aspnet-webpack"

_(In <project>/node_modules/)_
`mklink /J aspnet-webpack ..\..\node_modules\aspnet-webpack`
 
This works, but it does show that the problem is the search for "aspnet-webpack" is locked to the **project** folder only.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
