### ISSUE TITLE
packages in current release/branches?

### ISSUE THREAD

**Issue by dyardyGIT** [aspnet/AspNetCore#5225]
1. in the sample code why is there references to webpack version 1.13.3 when the latest is 4.x
JavaScriptServices/samples/misc/Webpack/package.json

2. error doing npm install 'couldn't find module extendify'

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dyardyGIT.
The repo you've posted this issue on was archived and that area is not being maintained any more.
