### ISSUE TITLE
slow data fetching in asp core react redux template in VSCode 

### ISSUE THREAD

**Issue by AliAUZ** [aspnet/AspNetCore#5226]
Recently I created more than 3 times some Asp core react redux template with :

dotnet new --install "Microsoft.DotNet.Web.Spa.ProjectTemplates"
dotnet new reactredux

in VSCode and if I make any changes in the code ( for example change the js to jsx or change store)
then in "Fetch data" section, it gets freeze 

![2018-07-28_9-57-16](https://user-images.githubusercontent.com/29033729/43350696-e6724a8e-924c-11e8-8b38-2221b995fb74.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
