### ISSUE TITLE
Microsoft.AspNetCore.NodeServices[0]  FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out o  f memory

### ISSUE THREAD

**Issue by saliniasok** [aspnet/AspNetCore#5230]
Hi, 
I am using node service (Microsft.AspNetCore.NodeService 1.1.1) in my asp.net core web api service to generate the Stimulsoft Report as a string. NodeService added in the start up file like
`  services.AddNodeServices(options =>
            {
                options.ProjectPath = Directory.GetCurrentDirectory();
                options.InvocationTimeoutMilliseconds = 2000000;
            });`
Calling the node js method by using the following method
`nodeServices.InvokeAsync<string>(`

While running the code, I am getting the error 'Javascript heap out of memory'. Please see the details below

> Microsoft.AspNetCore.NodeServices[0] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

This error occurs when the memory allocated for the execution application is less than the required memory when run application.
By default the memory limit in Node.js is 512 mb. To solve this issue we need to increase the memory limit by setting the command max-old-space-size. I did the command 
`node --max-old-space-size=8192 MyNodeJSFileName.js`
as per the link https://medium.com/@vuongtran/how-to-solve-process-out-of-memory-in-node-js-5f0de8f8464c

But still I am getting the same error. Is there any solution for this issue?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @saliniasok .
The version you're referencing is no longer supported. Please update to a supported version and let us know if you're still experiencing this error.
