### ISSUE TITLE
Support Webpack4 function export `argv` argument

### ISSUE THREAD

**Issue by jeremyVignelles** [aspnet/AspNetCore#5231]
The v4 of webpack introduced an `argv` as a second argument to the `webpack.config.js`  exported function

It is useful to know in which environment this is running on, by using `argv.mode === 'production'`.

Can you implement that in aspnet-webpack ?

More info here : https://webpack.js.org/configuration/configuration-types/#exporting-a-function

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
