### ISSUE TITLE
Improve interaction with DotNet.Watcher.Tools

### ISSUE THREAD

**Issue by andradf** [aspnet/AspNetCore#5235]
I'm not sure it is possible to improve it, but the experience while using angular SpaServices while also using DotNet.Watcher.Tools is pretty bad when making changes to the server. Any time a change is made a new background 'npm start' is run. For large projects webpack is notoriously slow during the first build. It would be amazing if SpaServices could maintain the instance of 'npm start' across DotNet.Watcher.Tools restarts.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @andradf .
@SteveSandersonMS is this in the legacy system area or not?

**Comment by SteveSandersonMS** [comment]
The recommended way to handle this is described at https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio#run-the-cra-server-independently (for React) or https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.2&tabs=visual-studio#run-ng-serve-independently (for Angular).
