### ISSUE TITLE
Why not publish the nuget for 2.1.1 or more

### ISSUE THREAD

**Issue by beefsteak** [aspnet/AspNetCore#5236]
https://www.nuget.org/packages/Microsoft.AspNetCore.SpaTemplates/
Version | Downloads | Last updated
-- | -- | --
  | 2.1.0-preview1-final | 824 | 6 months ago
  | 2.0.7 | 12,383 | 4 months ago
  | 2.0.6 | 4,180 | 5 months ago
  | 2.0.5 | 9,034 | 7 months ago
  | 2.0.3 | 8,529 | 9 months ago

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @beefsteak.
That package has been discontinued. You can read more details about this at https://github.com/aspnet/Announcements/issues/289
