### ISSUE TITLE
Running with webpack publicPath="/path" locally with IISExpress causes HMR endpoint to be hosted under "/path/path/__webpack_hmr"

### ISSUE THREAD

**Issue by ascott18** [aspnet/AspNetCore#5237]
Running my ASP.NET Core 2.1 app through Visual Studio using IIS Express. 

launchsettings.json:
``` json
{
  "iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false,
    "iisExpress": {
      "applicationUrl": "http://localhost:54163/AppName",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

In my webpack config, I have `output.publicPath = "/AppName/"`

In my Startup.cs, I have
``` cs
                    app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                    {
                        HotModuleReplacement = true,
                    });
```

With this configuration, all requests that should be getting proxied through webpack-hot-middleware are being proxied under `/AppName/AppName` instead of just `/AppName`. For example, the `__webpack_hmr` endpoint is being hosted at `/AppName/AppName/__webpack_hmr`, even though attempts to request it in the browser are going after `/AppName/__webpack_hmr`. The same goes for all my static files & for the hot-update js/json files. No amount of tweaking `WebpackDevMiddlewareOptions.HotModuleReplacementEndpoint` was able to fix this, because this value is always added in additionally to the path - there's no way to remove one of the repeated bits of base path.

I was able to work around this in the interim by adding the following rewrite rule in my Startup.cs just before I call `UseWebpackDevMiddleware`:
``` cs
app.UseRewriter(new RewriteOptions()
    .AddRewrite("^__hmr__(.*)", "AppName/__hmr__$1", true)
);
```
and then changing my webpack `publicPath` to `/AppName/__hmr__/` (the reason I changed the public path was to ensure that all HMR requests had a unique bit of path to them so I could distinguish them from other requests.

I believe this is because `WebpackDevMiddleware.UseProxyToLocalWebpackDevMiddleware` does not accommodate for the fact that my ASP.NET Core application already has a root URL configured via `IISSetupFilter`: https://github.com/aspnet/Home/issues/2302#issuecomment-350801537

Could checks be added to `ConditionalProxyMiddleware` that would accommodate for `context.Request.PathBase` somehow?

**Comment by nlivaic** [comment]
Similar problem.

```
output: {
    path: path.resolve(__dirname, 'wwwroot/dist'),
    publicPath: '/dist',
    filename: 'bundle.js',
  },
```

Everything is fine as long as I am requesting from root of my site, but when I request from another URL within my site, `/dist` gets appended. E.g.

```
http://localhost:5000/dist/__webpack_hmr
http://localhost:5000/DedicatedTasks/dist/__webpack_hmr
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
