### ISSUE TITLE
NpmScriptRunner leaves NodeJs running (after test session)

### ISSUE THREAD

**Issue by dstj** [aspnet/AspNetCore#5239]
When running the functional tests of my dotnet core / angular app I noticed that the NodeJS processes are not stopped after my tests finishes. After 5 minutes after my tests completed, they are still there... 

![image](https://user-images.githubusercontent.com/467692/45259872-531a2c00-b3a5-11e8-8dd7-03556b826fff.png)

My NUnit `OneTimeTearDown()` also seems to be hanging when that happens. I'm guessing that's because I'm trying to dispose the web server in it.

![image](https://user-images.githubusercontent.com/467692/45259914-54982400-b3a6-11e8-93c0-c89b4aace3eb.png)

I'm creating the server with `_server = new WebApplicationFactory<Startup>()` and calling both `_server.Server?.Dispose();` and `_server?.Dispose();` in the tests' teardown, just in case.

The culprit section in `Startup` is:
```
if (env.IsDevelopment()) {
   spa.UseAngularCliServer(npmScript: "start");
}
```

I went through the source a bit and in the [`NpmScriptRunner`](https://github.com/aspnet/AspNetCore/blob/7269dbb73f4aa0ebf5ebb8bc07a076ee181851be/src/Middleware/SpaServices.Extensions/src/Npm/NpmScriptRunner.cs#L67), there's an external npm process created that never seems to be killed and no reference to the `process` variable is maintained. Where is this process terminated? Could that be it?

More findings:
* When running a single test by itself, the NodeJS processes are terminated, albeit after my test finishes
* I tried reproducing on a newly created angular template project, no luck. It seems to only happen when multiple tests are ran...

Related issues: 
* #5204

**Comment by dstj** [comment]
With the latest .NET Core (v2.2.204), I'm still having `node.exe` processes hanging after my functional tests complete.

I recently changed my tests startup to use a real web server (i.e. `WebHost.CreateDefaultBuilder().UseStartup<Startup>()...`) instead of the testing `WebApplicationFactory`. No change, `node.exe` still hangs.

I stumbled on this issue from the archived JavaScriptServices repo: https://github.com/aspnet/JavaScriptServices/issues/270. @SteveSandersonMS, sorry the direct tag, but you were the one who closed that [aspnet/JavaScriptServices#270](https://github.com/aspnet/JavaScriptServices/issues/270) issue. My experience seems to show that it is not fixed, at the very least, not fully fixed...

**Comment by smartcodinghub** [comment]
I'm having this issue con 2.2.300 too. I use the Readt template.

When I stop Visual Studio Debugging, the console keeps open with the title "npm" until I close it manually.

**Comment by mkArtakMSFT** [comment]
We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.

**Comment by ChristopherHaws** [comment]
@mkArtakMSFT The middleware being referenced by this issue (`UseAngularCliServer` and `UseReactDevelopmentServer`) is part of `Microsoft.AspNetCore.SpaServices.Extensions`. The announcement you linked to says:

> When ASP.NET Core 2.1 was released in May 2018, we responded to the change in standards by providing a newer and simpler way to integrate with the SPA frameworks' own toolchains. This new integration mechanism exists in the package Microsoft.AspNetCore.SpaServices.Extensions and remains the basis of our Angular and React project templates since ASP.NET Core 2.1.

The post does not mention `Microsoft.AspNetCore.SpaServices.Extensions` being deprecated. I believe this issue should be reopened, as I am having this issue as well after switching to the newer, recommended `UseReactDevelopmentServer` middleware.

**Comment by mkArtakMSFT** [comment]
Seems this was a mistake. we will, however, track the issue as part of the referenced issue: #5204
