### ISSUE TITLE
Targeting .NET Core 2.1 - Startup error for new Aurelia WebApp - JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0

### ISSUE THREAD

**Issue by luboid** [aspnet/AspNetCore#5243]
Problem can be seen in dotnet/core#1726, dotnet/corefx#30962,

My point is to make config option in WebpackDevMiddlewareOptions, which to allow HttpClient to use  WinHttpHandler or SocketsHttpHandler on a call-by-call basis.

**Sockets Performance and SocketsHttpHandler**
https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/

I'am under corporate proxy when I switch off it all working fine 
PS:
I get copy of source code and where HttpClient is created I put
```C#
            HttpClientHandler handler = new HttpClientHandler()
            {
                UseProxy = false
            }
            _client = new HttpClient(handler);
```
now all working fine

screenshot from debug 

![image](https://user-images.githubusercontent.com/383517/45871787-f8b29f80-bd96-11e8-83ba-e980d6ac085a.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
