### ISSUE TITLE
Window is not defined with .net core and Angular Template

### ISSUE THREAD

**Issue by Usman15B** [aspnet/AspNetCore#5244]
It works fine when i run with node Express server (I use @ng-toolkit/universal) But with aspnet core node engine throwing NodeInvocation Exception Reference Error: Window is not defined in a third party modules like ngx-bootstrap and angular-jwt.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
