### ISSUE TITLE
Webpack: allow dynamic timeout

### ISSUE THREAD

**Issue by Sebazzz** [aspnet/AspNetCore#5245]
I require a higher timeout than the [default 100 seconds](https://github.com/aspnet/JavaScriptServices/blob/0050b505ec42d32dae42a4925c6cc03e01ee7dd0/src/Microsoft.AspNetCore.SpaServices/Webpack/WebpackDevMiddleware.cs#L115). I propose to make the timeout configurable. This would become an property on `WebpackDevMiddlewareOptions`.

Please let me know if you are open for this, and like a pull request.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
