### ISSUE TITLE
NpmScriptRunner.LaunchNodeProcess can't locate npm, but it exists

### ISSUE THREAD

**Issue by yamaoto** [aspnet/AspNetCore#5246]
I have installed node and npm. When i executing project aspnetcore-spa project from command line or VS, it working normally. When executing published (dotnet publish -r win-x64) version on same machine, in browser i have error: Ensure that 'npm' is installed and can be found in one of the PATH directories

PS C:\Program Files\nodejs> ls

Directory: C:\Program Files\nodejs

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       07.05.2018     12:21                node_modules
-a----       29.03.2018     23:06       22832792 node.exe
-a----       11.02.2018      1:08            702 nodevars.bat
-a----       11.02.2018      1:08           8997 node_etw_provider.man
-a----       11.02.2018      0:08           4974 node_perfctr_provider.man
-a----       11.02.2018      1:08            867 npm
-a----       11.02.2018      0:08            483 npm.cmd
-a----       29.03.2018     22:37            867 npx
-a----       29.03.2018     22:37            483 npx.cmd`

Error details:
[1] Ensure that 'npm' is installed and can be found in one of the PATH directories.
Current PATH enviroment variable is: 
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;
c:\app\product\11.2.0\client_1\bin;
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\nodejs\ <-----------------------------
C:\Program Files\Git\cmd;
C:\Program Files\TortoiseSVN\bin;
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;
C:\Program Files\Microsoft VS Code\bin;
C:\Users\user\AppData\Local\Microsoft\WindowsApps;
C:\Users\user\AppData\Roaming\npm;
C:\Program Files\Microsoft VS Code\bin;
C:\Users\user\.dotnet\tools

Make sure the executable is in one of those directories, or update your PATH.
Stack trace:
Microsoft.AspNetCore.NodeServices.Npm.NpmScriptRunner.LaunchNodeProcess(ProcessStartInfo startInfo)
Microsoft.AspNetCore.NodeServices.Npm.NpmScriptRunner..ctor(string workingDirectory, string scriptName, string arguments, IDictionary<string, string> envVars)
Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(string sourcePath, string npmScriptName, ILogger logger)

dotnet info:
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-009063 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

npm info:

node --version
v8.11.1

**Comment by garethjensen** [comment]
I know this is old, but I ran into the same issue. The problem isn't npm, but rather the arguments being passed into npm. You can resolve this by setting the current working directory of the application to the top directory of the ASP.NET Core project. For example, in my launch.json file, I set "cwd" to the top directory of my project (which was located in a "src/project.name" named folder). Here's my launch.json file for reference:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Web Server",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/src/Project.Name/bin/Debug/netcoreapp2.1/Project.Name.dll",
            "args": [],
            "cwd": "${workspaceFolder}/src/Project.Name",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/src/Project.Name/Views"
            }
        }
    ]
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
