### ISSUE TITLE
Ability to use yarn instad of npm with Microsoft.AspNetCore.SpaServices

### ISSUE THREAD

**Issue by alexandrudanpop** [aspnet/AspNetCore#5247]
Is it possible to use yarn instead of npm to install packages using Microsoft.AspNetCore.SpaServices?

The Microsoft.AspNetCore.SpaServices installs client side packages internally with npm, but we want to use yarn so we can use the yarn.lock file for consistent package versions. I know npm has a similar lock file but we don't want to use that one. 

Could this be implemented? A lot of the JS community are using yarn instead of npm, for certain things that it does better and also because it's slightly faster.

Thanks!

**Comment by alexeyzimarev** [comment]
SPA extensions use npm hard-coded. Although it is very much possible to fix the build steps in the `csproj` file, using the Angular CLI or React dev server with yarn is currently impossible.

I am not sure what's the strategy for the npm script runner class, since the comment says that it will be moved to the NodeServices package after 2.1 but it is still in SpaServices.Extensions at 3.0 preview. If it stays put in the Spa project, it can be changed to run whatever.

**Comment by alexandrudanpop** [comment]
Adding those 2 targets in the .csproj file fixed it to run ```yarn install``` and ```yarn build```:

```
  <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" ('$(Configuration)' == 'Debug') And !Exists('$(SpaRoot)node_modules') ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'yarn'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="yarn install" />
  </Target>

<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <Exec WorkingDirectory="$(SpaRoot)" Command="yarn install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="yarn build" />
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)build\**; $(SpaRoot)build-ssr\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
