### ISSUE TITLE
Can't hit clientside breakpoints in projects generated from SPA Templates

### ISSUE THREAD

**Issue by flyfishMT** [aspnet/AspNetCore#5250]
Hi, 
Running Visual Studio 2017 15.8.6
Created new ASP.NET Core, React project.
Put a breakpoint in /ClientApp/src/components/Counter.js, incrementCounter method.  F5.
Does not hit breakpoint on increment counter button click. 
Breakpoint says "The breakpoint will not currently be hit. No symbols have been loaded for this document. Location Counter.js, line 13, character 5"

Incidentally, the angular spa and knockout spa project have the same issues.  I am really after a solution to knockout (with typescript), since this is what I am using, but built the other projects since knockout no longer seems supported.  

I could not hit the breakpoints in VS Code either, but I could hit them in the browser debug tools.

UPDATE - can hit breakpoint in IE and Edge. Still cannot in Chrome or FireFox.

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
