### ISSUE TITLE
(SSR) Provider for both Server and Client

### ISSUE THREAD

**Issue by riiight** [aspnet/AspNetCore#5251]
I created an ASP.NET Core Angular project using the VS 2017 template.

I followed these [directions](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio#server-side-rendering) to get server-side rendering working. 

In the section called [Pass data from .NET code into TypeScript code](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio#pass-data-from-net-code-into-typescript-code), it says:

"Your main.server.ts code receives this as params.data. For example, the preceding code sample passes a boolean value as params.data.isHttpsRequest into the createServerRenderer callback. You can pass this to other parts of your app in any way supported by Angular. For example, see how main.server.ts passes the BASE_URL value to any component whose constructor is declared to receive it."

Ok, so that appears to say that you can use Angular dependency injection. However, if I have a piece of data that is passed from .NET code to TypeScript code (e.g. MyData), and add it as an "extraProvider" in main.server.ts so that it can be dependency injected, if I land on the site then navigate to a component that has that injected (important note: I'm navigating there so main.ts is in play, not main.server.ts), MyData will not be there because the regular "main.ts" has no knowledge of a provider for MyData.

So my question is, if we pass data from .NET code into TypeScript using the method described in the article and then we try to dependency inject that data into components, how can we make that same data available on the browser via dependency injection?

Thanks in advance.

EDIT: I tried using "globals" as described in the section [Passing data from server-side to client-side code](https://github.com/aspnet/JavaScriptServices/tree/master/src/Microsoft.AspNetCore.SpaServices) but when I do that I get the error:

"Globals is not supported when prerendering via UseSpaPrerendering"

**Comment by Calx-Takeno** [comment]
Same Issue,
I am using UseSpaPrerendering in .NET CORE.
An unhandled exception occurred while processing the request.
InvalidOperationException: Globals is not supported when prerendering via UseSpaPrerendering(). Instead, your prerendering logic should return a complete HTML page, in which you embed any information you wish to return to the client.
Microsoft.AspNetCore.Builder.SpaPrerenderingExtensions.ServePrerenderResult(HttpContext context, RenderToStringResult renderResult)

Stack Query Cookies Headers
InvalidOperationException: Globals is not supported when prerendering via UseSpaPrerendering(). Instead, your prerendering logic should return a complete HTML page, in which you embed any information you wish to return to the client.
Microsoft.AspNetCore.Builder.SpaPrerenderingExtensions.ServePrerenderResult(HttpContext context, RenderToStringResult renderResult)
Microsoft.AspNetCore.Builder.SpaPrerenderingExtensions+<>c__DisplayClass0_0+<<UseSpaPrerendering>b__1>d.MoveNext()
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details
System.InvalidOperationException: Globals is not supported when prerendering via UseSpaPrerendering(). Instead, your prerendering logic should return a complete HTML page, in which you embed any information you wish to return to the client.
   at Microsoft.AspNetCore.Builder.SpaPrerenderingExtensions.ServePrerenderResult(HttpContext context, RenderToStringResult renderResult)
   at Microsoft.AspNetCore.Builder.SpaPrerenderingExtensions.<>c__DisplayClass0_0.<<UseSpaPrerendering>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
