### ISSUE TITLE
Utilising Node Clustering to scale Server Side Rendering

### ISSUE THREAD

**Issue by timothywisdom** [aspnet/AspNetCore#5256]
We're running this package under heavy load in production and Node's Server Side Rendering cannot keep up to the number of requests coming in. We're experiencing "request pile-up" as React's RenderToString function blocks Node's event loop from handling more requests. Our server's response times are terrible when SSR is enabled.

I found an article from AirBnB describing the exact same problem (and their solution):
https://medium.com/airbnb-engineering/operationalizing-node-js-for-server-side-rendering-c5ba718acfc9

I'm wonder if this package has some configuration (that I may have missed) to enable [Node Clustering](https://nodejs.org/api/cluster.html) and/or some type of load balancing

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
