### ISSUE TITLE
Recommendations for injecting appsettings.json configuration into Angular

### ISSUE THREAD

**Issue by jjgriff93** [aspnet/AspNetCore#5257]
Hi all, I'm looking for the best practice in sharing configuration with the Angular client app - for example database connection strings and auth keys. 

I've seen some blogs around using a Controller API and then fetching these from within the Angular app. I've also seen an article suggesting you can inject from the Home controller into the razor page, which then adds fields to the app-root tag, however in the latest template there is no home controller.

In Angular you have the environment.ts files, would be interested to hear if there's some good practice around how to share/structure this configuration properly between server and client

Thanks in advance

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
