### ISSUE TITLE
Issue with Angular Spa template

### ISSUE THREAD

**Issue by chrisckc** [aspnet/AspNetCore#5261]
Following on from: https://github.com/aspnet/JavaScriptServices/issues/1781

I wanted to check the behaviour of the default Angular Spa template. I have a repo here: https://github.com/chrisckc/DotNetCoreAngularSpa
but there seems to be a temporary issue with github not accepting my push and returning a 404 for that particular repo intermittently.

Run the repo in Production mode as per the instructions in the Readme.md, but instead of building Angular with the package script: `npm run build -- --prod`

Build using ng directly: `ng build --env=prod` which builds without the --extractCss option, which should be a valid and working choice?

Now run the dotnet app in production mode and visit: https://localhost:5001, scroll back through the dotnet console output and notice this:

> info: DotNetCoreAngularSpa.Startup[0] ... app context.Request.Path: /bootstrap.min.css.map

> dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[5]
      The request path /bootstrap.min.css.map does not match an existing file

Correct as the file bootstrap.min.css.map does not exist in the bundled app in 'ClientApp/dist' dir

> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/index.html'. Physical path: '/xxxxxxxx/ClientApp/dist/index.html'

> info: DotNetCoreAngularSpa.Startup[0] inside app.UseSpa context.Response.StatusCode: 200 Url: /index.html

Notice that the Request reached the UseSpa middleware, which unconditionally rewrites the Request.Path to /index.html before passing it to UseSpaStaticFilesInternal which then serves the contents of index.html from the 'ClientApp/dist' dir.

As a result of the unconditional rewrite, if the Angular app requests a file which does not exist it always get the contents of index.html with a 200 OK status code, masking the real issue. A request for any file which does not exist will always result in the index.html being served from the 'ClientApp/dist' dir.

The Chrome console log shows the following:
> DevTools failed to parse SourceMap: https://localhost:5001/bootstrap.min.css.map

Chrome DevTools thinks it got the file it asked for and tried to parse it, which fails because it's actually not the file it asked for and contains unexpected content.

Commenting out the app.UseSpa block and then visiting the site using https://localhost:5001/index.html shows that the console warnings are no longer there because the Chrome DevTools correctly receives a 404 and presumably just ignores the missing map file.

There are 3 issues here:

1. There is an issue with the Angular App inside provided in the Angular Spa template out of the box by 'dotnet new angular' when running without extractCss option on both dev and prod modes. In dev mode the DevTools error is not seen because the request for /bootstrap.min.css.map is proxied to the dev server which returns a 404 not found.

2. The behaviour of the Angular Spa template seems to be suboptimal, i can't see why the  UseSpa (uses SpaDefaultPageMiddleware under the hood) middleware has been designed to unconditionally rewrite the Request Path.  It could cause headaches when trying to debug issues with the built/bundled app etc unless you are aware of the unconditional rewrite behaviour. I think that the Request rewrite should only occur when the request path is '/' so that the index.html file can be served.  _**EDIT: I noticed that the Angular app is using HTML5 pushstate so that real url's can be used rather than hash based url fragments off root such as /#/somepage. Because of this it would need to also rewrite non-root requests.**_
Serving the index file for any non-matching file does not make sense. **_EDIT: to support HTML5 pushstate, maybe only rewriting requests that do not contain a dot, ie. ones that do not look requests for files would be better?_** . As it stands at the moment, to make this behave sensibly will require a custom UseSpa extension class and custom SpaDefaultPageMiddleware class to be added to the project which is coded to only rewrite requests to '/' or '' **_EDIT: and also requests that do not contain a dot if we want to use pushstate_**

3. The Spa template should have UseSpaStaticFiles wrapped in ` if (!env.IsDevelopment()) {` so that it does not serve files from ClientApp/dist in preference to the Angular Dev server when in dev mode. To see the issues this can cause, perform an angular build using `npm run build -- --prod` then rename the dist dir to dist-copy prevent it from being deleted. replace `UseAngularCliServer` with `UseProxyToSpaDevelopmentServer(baseUri: "http://localhost:4200")` then run `npm start`. Once started rename the dist-copy dir back to dist. Run the dotnet app in Dev mode and notice that the bundles are now served from the dist dir instead of the proxy.

> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/main.bundle.js.map'. Physical path: 'xxxxxxxx/ClientApp/dist/main.bundle.js.map'

Luckily the build scripts inside the Angular CLI delete the dist dir when `npm start` is ran, but it is not unreasonable to expect that devs may run into that issue when ejecting from the CLI or changing build options etc.

**Comment by mkArtakMSFT** [comment]
This seems to be a set of multiple unrelated issues. Please file separate issues for those which are still applicable and we'll consider those.
