### ISSUE TITLE
How to pass environment variables to the react client?

### ISSUE THREAD

**Issue by eparizzi** [aspnet/AspNetCore#5266]
I couldn't find any documentation on how to pass environment variables from the ASP.NET Core server to the React client when using the ASP.NET Core 2.1 React template.

I know I can add an API endpoint to get the data, but I was wondering if there's something similar to [dotenv-webpack](https://www.npmjs.com/package/dotenv-webpack) so that we can use environment variables in the SPA and get them replaced by the build.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
