### ISSUE TITLE
How to properly load an EventSource polyfill for HMR?

### ISSUE THREAD

**Issue by EPinci** [aspnet/AspNetCore#5268]
Hello,

to use HMR on Edge an EventSource polyfill is required.
What is the proper way to load one with webpack itself?

Most polyfills require some form of initialization: I can put the polyfill package in the webpack entries but then, what ever JS file I put the initialization code in gets actually executed after the HMR tries to load and fail. How can configure webpack to work with this?

Thank you.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
