### ISSUE TITLE
UseWebpackDevMiddleware with latest version of Angular

### ISSUE THREAD

**Issue by junalmeida** [aspnet/AspNetCore#5269]
Since angular does not use webpack.config.js anymore, it is impossible to make HMR working with only aspnetcore. 

When trying to use it it complains that `webpack.config.js` does not exist, but it's not supposed to exist on the latest angular version.

**Comment by mkArtakMSFT** [comment]
Hi. It's been a while this bug has been open. If you haven't resolved it yet and still need help with it, please reopen.
