### ISSUE TITLE
Update Docs for 2.2 Template

### ISSUE THREAD

**Issue by mbeckenbach** [aspnet/AspNetCore#5271]
The Asp.Net Core Angular SPA Template in Asp.Net Core 2.2 has finally been updated to Angular 6, which is great since we can simply use ng update to go to Angular 7 now.

But the docs are still for an older Angular Version. So the required configuration for SSR is missing.
Could you please update the docs?

https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.2&tabs=visual-studio

**Comment by dominikfoldi** [comment]
It would be great to have documentation on how to enable SSR. We are (and I am sure lots of other people) stuck with it :S

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mbeckenbach.
We are not doing anything explicit to support SSR.
We've decided to rely on the underlying CLI for SSR support. Please see https://angular.io/guide/universal for details on how to do that.

**Comment by lonix1** [comment]
I don't get it? SSR as far as I understand is supported... it's run in an in-process node instance. So surely there should be docs for that?
