### ISSUE TITLE
Angular Template - WebSocket connection failed: Error during WebSocket handshake with Windows 7

### ISSUE THREAD

**Issue by k-vekos** [aspnet/AspNetCore#5272]
Using the latest `dotnet new angular` template, I get this error message in my browser console:

```
WebSocket connection to 'ws://localhost:4200/sockjs-node/507/xg3xa0xl/websocket' failed: Error during WebSocket handshake: Unexpected response code: 500
WebSocketBrowserDriver @ sockjs.js:1679
```

I'm aware WebSockets isn't supported on Windows 7, however, if I just host the SPA using `npm start` from the `ClientApp` directory then I don't get this error. What is the reason for this, and is there a way to stop this error when hosting via Visual Studio's debug launch?

**Comment by FAlmeidaActionpoint** [comment]
I have the same issue here

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @k-vekos.
@ryanbrandenburg can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@k-vekos, @FAlmeidaActionpoint do you still face this issue?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
