### ISSUE TITLE
Client proxy on the server for JavaScript/C#/Swift clients

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCore#5276]
* Generate proxies using MSBuild targets in separate packages for each language:
   - C#
   - TypeScript
   -  Javascript
   - Swift
* Proxies are output to a default location, configurable with MSBuild properties
* No runtime generation of proxies (i.e. `/signalr/hubs`) for now.

**Comment by anurse** [comment]
Proxy Gen! It seems users aren't super enthusiastic here. I haven't heard a lot about it. If customers are clamoring for it, we can re-evaluate.
