### ISSUE TITLE
Should SignalR pass a resource into IPolicyEvaluator?

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#5279]
MVC passes in the AuthorizationFilterContext.  SignalR should decide what resource is appropriate (if any)

**Comment by muratg** [comment]
@Tratcher Thoughts on this?

**Comment by anurse** [comment]
I don't think this is much work. We should just look at what MVC passes in and pass a similar thing that contains SignalR-related state. For the HTTP connection level we can't pass much extra in, but when authenticating a specific invocation we can.

**Comment by rynowak** [comment]
Pass in the endpoint IMO. We're converging around that as the thing that has all of the infoZ.

**Comment by anurse** [comment]
Is that true for SignalR though? There's all the connection metadata on `ConnectionContext` and I don't know if that's replicated on the endpoint.

**Comment by rynowak** [comment]
If it's truly metadata then you should add it to the endpoint metadata. If it's part of the request, then I dunno 🤷‍♂️

**Comment by anurse** [comment]
Triage decision:
* Add relevant metadata to the endpoint
* Pass the endpoint in as the resource

**Comment by anurse** [comment]
We don't have Hub-level auth any more, but we do still do method-level auth. We need to prepare a resource and pass it in. We can't *just* use the endpoint here because we need to include the method being executed (and the args?)

**Comment by rynowak** [comment]
How does that work if you're doing middleware-based auth?

**Comment by anurse** [comment]
We still do that auth ourselves by manually calling `AuthorizeAsync`.

**Comment by rynowak** [comment]
Ah gotcha. I saw you reply and had a minor panic because I thought I understood what you were doing here already. It makes sense since the middleware won't run on arbitrary signalR messages.

**Comment by BrennanConroy** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [x] Relevant XML documentation comments for new public APIs are present.
    * [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [x] The change requires a new article. An issue with an outline has been filed here: [aspnet/AspNetCore.Docs/issues/13050]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [3.0.100-preview7-012687]
            * ASP.NET Core Runtime: [3.0.0-preview7.19326.10]
            * .NET Core Runtime: [3.0.0-preview7-27826-04]
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
