### ISSUE TITLE
TCP support in SignalR

### ISSUE THREAD

**Issue by Suvarnnan** [aspnet/AspNetCore#5284]
ASP.NET Core 2.0 SignalR supports different middle ware options like TCP,AMQP etc.

Can anyone give details about it like a sample where TCP is used as signalr middle ware.

Any good explanation of this concept and illustration with samples are appreciated.
Please consider this as a request for updating

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
