### ISSUE TITLE
Compile hub method invoke as needed

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#5285]
Today SignalR will compile invoke code for all methods on a hub the first time the hub is accessed, e.g. if a hub has 1000 methods on it then all 1000 will be compiled at once.

MVC compiles invoke code as needed, e.g. a lightweight list of actions is calculated for a controller, and then when an action is first used the invoke code is compiled.

**Comment by anurse** [comment]
I'm going to close this. We'll always continue evaluating performance and can consider this as a possible improvement when we get there. I don't feel like tracking a bunch of individual perf ideas on GitHub is the most effective structure.
