### ISSUE TITLE
Consider caching connection list for HubLifetimeManager operations

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#5288]
![capture](https://user-images.githubusercontent.com/7574801/38157793-1a896a76-343f-11e8-9b81-27b2d1b6055e.JPG)

We can cache the connectionlist on access and update it whenever a connection is added or removed

**Comment by anurse** [comment]
I'm going to close this. We'll always continue evaluating performance and can consider this as a possible improvement when we get there. I don't feel like tracking a bunch of individual perf ideas on GitHub is the most effective structure.
