### ISSUE TITLE
Optimize Groups data structure

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#5291]
Groups are basically stored as `ConcurrentDictionary<string, ConcurrentDictionary<string, HubConnectionContext>>` (groups by name, containing connections by ID)

`ConcurrentDictionary` uses a lot of memory. Optimize how groups are stored to use a more light-weight data structure on the server to increase scalability.

**Comment by muratg** [comment]
Backlogging for now.

**Comment by anurse** [comment]
I'm going to close this. We'll always continue evaluating performance and can consider this as a possible improvement when we get there. I don't feel like tracking a bunch of individual perf ideas on GitHub is the most effective structure.
