### ISSUE TITLE
What should HubConnection.StopAsync cancellation token do?

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#5294]
https://github.com/aspnet/SignalR/pull/2000#discussion_r181334729

> Not sure yet. Need to look deeper. Maybe we need to pass it to DisposeAsync or use it from the outside to cancel dispose. But we can just not support it for now. File an issue.

**Comment by muratg** [comment]
Option 1) remove the CancellationToken from StopAsync, it doesn't seem useful for this method, and it would be confusing.

Option 2) Use the CancellationToken's for the same purpose as the current timeout in connection's StopAsync. 

Let's make a decision on this. @davidfowl @halter73

**Comment by anurse** [comment]
![Why not both?](https://media.giphy.com/media/zbzNUbpFnlw8E/giphy.gif)

Let's just leave it. It's there for us to use when we want to, but we don't really see a scenario for cancelling stop. One thing that is clear: Cancelling `StopAsync` **will not** '
'stop the stop', it might transform from a graceful shutdown to ungraceful but the moment `StopAsync` is called, the connection is considered dead.
