### ISSUE TITLE
Wildcards in MapHub path

### ISSUE THREAD

**Issue by rotsin** [aspnet/AspNetCore#5295]
Hi, we've just upgraded to preview2 as we've been having issues with websocket connections not closing properly on disconnects/reconnects when interacting with an azure webapp. In the alpha2 build I could specify an url as {tenant}/hub with the {tenant} part serving as a wildcard that would respond to tenant1/hub, dude1/hub etc.

This was useful for us as we're storing authentication specific cookies on each tenant path. If we were to be using a generic /hub map, onConnected will no longer resolve the user.identity correctly (as auth cookies are not present for this path).

Is there a way with preview2 to replicate the previous functionality?

Thank you, and great job on what you are doing with this project :)

**Comment by muratg** [comment]
Moving this to backlog.
