### ISSUE TITLE
Allow more granular control over the ApplicationMaxBufferSize

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#5299]
Today the ApplicationMaxBufferSize is a single setting per server, we should consider a callback model where this can be configured per connection. That would give more control over which connections get to buffer more incoming data than other connections.

We could also consider 2 limits:
- Anonymous users and Authenticated users

The default limits are there to protect against unauthenticated users from blowing up server buffers but if users are authenticated the limits might be purely driven by your application. Also, since users are authenticated you have a way to audit and disallow misbehaving users.

Related to https://github.com/aspnet/SignalR/issues/2266

**Comment by anurse** [comment]
This isn't really relevant after #8223

**Comment by davidfowl** [comment]
Well it is but we already handled it in SignalR with my latest change
