### ISSUE TITLE
Set up alerting and monitoring for performance scenarios

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#5300]
Now that we have long running job support for our benchmarking runs we should add a long running test that is under constant load. The recommendation is creating a custom workload that causes ~50% CPU for the entire duration of the job.

**Comment by muratg** [comment]
@sebastienros I believe you have a system for the perf tests. Would it be easy to add SignalR coverage there as well?

**Comment by anurse** [comment]
We want to do this across the stack and we're tracking that in all kinds of fun places. Let's close this.
