### ISSUE TITLE
Please add WebRTC support 

### ISSUE THREAD

**Issue by AceHack** [aspnet/AspNetCore#5302]
I would like to use SignalR as a mediator/rendezvous/fallback for WebRTC.  It would be great if I could facilitate direct peer to peer communications via signal r.

I realize this is a big enhancement.

Thanks for all your hard work.

**Comment by anurse** [comment]
We need to figure out if peer-to-peer support is something we want and how to do it. I'm going to close this as we have no plans on our radar to directly support WebRTC.
