### ISSUE TITLE
Use Karma to run JavaScript functional tests in browsers

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#5303]
* [x] Convert tests to use [Karma](https://karma-runner.github.io/2.0/index.html) when running locally
* [x] Use [`karma-sauce-launcher`](https://github.com/karma-runner/karma-sauce-launcher) to run tests on SauceLabs
* [x] Create VSTS build that runs these tests
* [x] Report VSTS build results to email and GitHub checks.
* [ ] Consider running builds on PRs (only ones issues by or approved by team members though)

**Comment by muratg** [comment]
For the remaining checkbox, we're tracking work with #5114.
