### ISSUE TITLE
Communication between two WebAPIs possible?

### ISSUE THREAD

**Issue by LeonidasFettikus** [aspnet/AspNetCore#5304]
Hi guys,

I am a super noob when it comes to WebSockets and SignalR. I am currently looking for a way to speed up one of our projects which consists of multiple WebAPI projects and a MVC project which communicate with each other. Basically, one WebAPI project serves the data, one acts as a central hub and one acts as the UI.

Currently, we use REST calls and timers to periodically transfer data between each project. However, we need to optimize the time it takes for the data to reach its destination. So I thought of using SignalR. But every example I find uses the classic Server-Client scenario. What I need is a WebAPI-WebAPI-Client scenario.

So is this possible? If yes, could you give a very basic example on how this could be done?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
