### ISSUE TITLE
Insufficient Documentation Regarding Scaling  

### ISSUE THREAD

**Issue by wpitallo** [aspnet/AspNetCore#5305]
Hi,

Apologies for asking this here not sure where else to turn :(

I have been searching endlessly for any decent documentation regarding scaling benchmarks / architecture for SignalR .Net Core 2. I have seen the documents for the Redis cache but this does not provide any benchmarks and scale out limitations. At the moment I am just trying to figure out if it is at all possible to scale out SignalR to millions of connected uses (my use case is MMO gaming), from what I have seen so far this does not seem possible) I am also looking at Azure SignalR Service but there is even less documentation for this, please can you point me to some documentation that could indicate:

Approximately how many connected clients are supported base on the Azure App Service server instance size i.e. some benchmark guidelines. (I feel this is a very reasonable request that many people would be interested in especially if they are considering SignalR for massive scale and this has not as far as I can tell been addressed anywhere)

What type of latency is introduced by implementing Redis cache as you scale out to 100's of nodes. Again it would be nice to see some actual benchmarks. 

What are the maximum number of concurrent users the SignalR architecture team team has managed to successfully test (for real time communication) and how was this accomplished?

Thanks for the help.

Regards,

Warren

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
