### ISSUE TITLE
Require Authorization on Hubs as a Global Option

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#5306]
I was thinking we could introduce a global hub option for requiring auth on all hubs. There was a way to do this in classic SignalR but for ASP.NET Core SignalR you'd have to add the `Authorize` tag to each hub.

It could look something like 
```csharp
services.AddSignalR(options => 
{
    options.RequireAuthorization = true
})
```

**Comment by muratg** [comment]
Backlogging this.

**Comment by anurse** [comment]
Rolling in to #5353
