### ISSUE TITLE
How to get a .Net Core Framework SignalR Core client to connect to .Net Server (SignalR)?

### ISSUE THREAD

**Issue by GuanhongW** [aspnet/AspNetCore#5308]
I am working on ASP.NET Core2.1. I implemented a SignalR Core Client in asp.net core. I want to build the connection between SignalR Core Client and a SignalR Hub (i.e. AspNet.SignalR). Is there a way can fix the issue?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
