### ISSUE TITLE
Is there any client implementation for use with flutter ?

### ISSUE THREAD

**Issue by diegomgarcia** [aspnet/AspNetCore#5310]
Hi guys I dont know if here is the right place to ask this, but I`ve looked for it and doesnt find any client implementation for dart with flutter anywhere, do you guys has any tips on how to do it ?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
