### ISSUE TITLE
Test concurrent connection limit on different Azure VM sizes

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#5311]
Collect connection count, CPU %, Memory Usage
Machine Sizes:
- [ ] B1s (4,900 connections, 1GB RAM limiting factor, CPU ~10%) Specs: 1GB RAM, 1 CPU
- [ ] B2s (82,000 connections, CPU and RAM basically 100%) Specs: 4 GB RAM, 2 CPU
- [ ] D2s_v3 (110,000 connections, CPU 100%, RAM 80%) Specs: 8 GB RAM, 2 CPU
- [ ] D4s_v3 (160,000 connections, CPU 100%, RAM 50%, connections started disconnecting) Specs: 16 GB RAM, 4 CPU
- [ ] D8s_v3 Specs: 32 GB RAM, 8 CPU
- [ ] D16s_v3 Specs: 64 GB RAM, 16 CPU
- [ ] D32s_v3 Specs: 128 GB RAM, 32 CPU
- [ ] D64s_v3 Specs: 256 GB RAM, 64 CPU

Note: Test Linux vs. Windows VMs to see if there is a difference

**Comment by anurse** [comment]
Closing this since performance is a constant concern and workstream for us, but the specifics of this issue aren't really relevant any more. The concern is that this data would be based on our specific conditions and would get stale really fast.
