### ISSUE TITLE
@aspnet/signalr - make connection id available

### ISSUE THREAD

**Issue by Nathan-Ryan** [aspnet/AspNetCore#5314]
I have a reactive angular app where its services contain observables to allow components to react to certain events. i.e. saving a form will cause the adjacent index component to reload. This all works reasonably well, until I have added SignalR into the mix to broadcast these same events between clients. Essentially the same services/observables used to perform the intra-client events are now emitting events when the socket receives the respective event too. 

The problem i now have is that the components receive two events per action, one raised internally when the http request completes (client service -> obserable -> component), and the other from the socket (controller -> hubcontext -> client hubconnection -> client service -> observable -> component).
I need both event sources as I don't want to rely on the socket to perform intra-app communication and it also provides a consistent way, from the subscribing components perspective, to get events.

Ideally I would like to ignore the client who sent the http from getting the signalr message so dont have to do any hacky buffering and grouping on the client app. A good solution would be to include the signalr connection id as a header in the http request which i could then use to filter hubcontext clients.

In the meantime, accessing the connection id via sending an initial message to the client will suffice. Seems odd that the connection id is unavailable client-side. Using groups only works in certain situations.

Appreciate any feedback.

**Comment by BrennanConroy** [comment]
That has actually been done in the 3.0 wave.
