### ISSUE TITLE
StreamItem InvocationId cleanup

### ISSUE THREAD

**Issue by DylanDmitri** [aspnet/AspNetCore#5315]
Previously, stream items were returned from the server in response to an invocation, and so carried an invocation id for routing purposes.

Now, stream items can be sent to the server, and are sorted based on stream id.  Regardless of direction, all id values are stored under the `InvocationId` field on `StreamItem`. This is poor naming and rather misleading.

Possible solutions include:
- StreamItem has two fields, `StreamId` and `InvocationId`, only one of which can be filled at a time
- StreamItem has one field, `RoutingId`, which is used both ways. This breaks backwards compatibility.
- Make a new class `StreamParameterItem` that's identical to stream item but has a `StreamId` field instead.

None of these solutions feels very clean.

**Comment by BrennanConroy** [comment]
Done https://github.com/aspnet/AspNetCore/pull/4559

**Comment by davidfowl** [comment]
Thanks @DylanDmitri ! oh and @BrennanConroy 😉
