### ISSUE TITLE
Update HubProtocol spec with new message types and changes

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#5319]
There are going to be some changes to our HubProtocol including changes to the `InvocationMessage` type and the addition of the new message type `StreamCompletionMessage`.
Spec located here: https://github.com/aspnet/SignalR/blob/master/specs/HubProtocol.md

Note: These changes are going into 3.0, not 2.2 so this PR should be done directly on the `master` branch

**Comment by BrennanConroy** [comment]
Done via https://github.com/aspnet/AspNetCore/pull/4559
