### ISSUE TITLE
Releases page - latest one is 1.0.0-alpha2

### ISSUE THREAD

**Issue by Misiu** [aspnet/AspNetCore#5322]
This issue is similar to https://github.com/aspnet/EntityFrameworkCore/issues/12550.
When navigating to https://github.com/aspnet/SignalR/releases latest release is 1.0.0-alpha2,

**Comment by Spaceman1861** [comment]
Not sure if this is the correct thread but seems pretty close im trying to track down the release notes from 1.0.1 onwards for signalr where can these be found? Those release pages dont seem to have any release notes.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
