### ISSUE TITLE
Client-server streaming support

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#5323]
This issue tracks things still to do before client-server streaming could be released:

* [x] Server support (checked in to 3.0 `master`)
* [x] .NET Client support (checked in to 3.0 `master`)
* [x] Update spec #2619 
* [x] TypeScript support #2595 
* [x] Java Support #7151
* [x] Review protocol changes

**Comment by muratg** [comment]
@mikaelm12 Could you file a separate issue for Java client support?

**Comment by mikaelm12** [comment]
> Consider support for additional input types (Stream in C#, Blob/FileReader in TS, etc.)

Is this something we are still interested in? Seems low interest. I'm of the opinion that we should put that in it's own issue and milestone it (probably backlog) and then we can close out the Client to Server Streaming issue.

**Comment by muratg** [comment]
@mikaelm12 sounds reasonable. Please file the bug and close this one. Thanks!

**Comment by anurse** [comment]
I think this is interesting, but I agree we should track it as a separate feature.

**Comment by mikaelm12** [comment]
Issue: https://github.com/aspnet/AspNetCore/issues/8292

**Comment by faryu** [comment]
For me this feature is very important. I'm having a application with multiple peers, which most of them can function as a server and as a client at the same time. They connect with each other with a singular connection, which makes it important to stream in both directions. Right now I have to use a workaround and increase the max transfer size and use a paging like mechanism.
Right now this is the only new feature I'm missing in SignalR.

I only use the C# client and server at the moment.

**Comment by mikaelm12** [comment]
@faryu The discussion above was about one particular aspect of client to server streaming. The feature is done though and will be available in 3.0 for the C#, TS and Java clients.

**Comment by faryu** [comment]
@mikaelm12 Thank you. I guess I didn't read the posts well enough.

**Comment by mikaelm12** [comment]
No worries! 😄
