### ISSUE TITLE
How to get Connection Id from client as in this example from Microsoft?

### ISSUE THREAD

**Issue by ccarse** [aspnet/AspNetCore#5325]
I'm following this article: https://msdn.microsoft.com/en-us/magazine/mt846469.aspx

I want to achieve the same thing, create a signalR connection from the client, call a long running api method passing in my connection id, have my controller periodically report progress to that connection id. 

It seems it is no longer possible to get the connection id on the client? What's the recommended way of doing what the article is doing? 

I'm using ASP.net core 2.1 and the latest @aspnet/signalr package. 

Thanks,
Cody

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
