### ISSUE TITLE
Is there any way to log when a message is being sent to individual clients?

### ISSUE THREAD

**Issue by rayrase** [aspnet/AspNetCore#5326]
Setting SignalR to verbose does not display when individual messages are sent. However, I can set the _Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSockets_ logging to verbose and see when messages are being transmitted then correlate the connection ids but, unfortunately, I cannot see the contents of those messages.

**Comment by muratg** [comment]
We don't plan to do this.
