### ISSUE TITLE
build failed for VS2017  

### ISSUE THREAD

**Issue by avinashkandukuri** [aspnet/AspNetCore#5327]
I have downloaded the project from the repository and try to build in the local machine, 
below is the error it is showing 
![image](https://user-images.githubusercontent.com/25835213/48044805-67836680-e153-11e8-9361-495994abf2e5.png)
can you let me know what may be the issue in my machine or any missing file in the framework?

**Comment by pranavkm** [comment]
My guess is it's using an older version of the .NET Core Sdk. I'd start by following the [Building from Source](https://github.com/aspnet/AspNetCore/wiki/Building-from-source) instructions here. Feel free to reopen if you continue seeing the error after you've tried the instructions
