### ISSUE TITLE
Check if connection state for a particular hub.

### ISSUE THREAD

**Issue by sukhbirsaini** [aspnet/AspNetCore#5332]
I have a situation where I have to keep a dictionary of connections which are connected via web socket.
how can we get a list of connects which are started?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
