### ISSUE TITLE
Cannot connect from a non-browser Javascript client to Asp.Net Core SignalR

### ISSUE THREAD

**Issue by christiansita** [aspnet/AspNetCore#5334]
Hi, I am trying to write a non-browser javascript client to connect to my Asp.Net Core SignalR and I am having the following error message:

> Debug: Starting HubConnection.
> Debug: Starting connection with transfer format 'Text'.
> Debug: Sending negotiation request: https://localhost:44339/chatHub/negotiate
> Error: Failed to complete negotiation with the server: Error: callback argument missing
> Error: Failed to start the connection: Error: callback argument missing

**My Javascript non-browser javascript client code is as follows(this client powered with Node.Js):**

global.XMLHttpRequest = require('xhr');
var signalR = require('@aspnet/signalr');
var connection = new signalR.HubConnectionBuilder()
       .withUrl("https://localhost:44339/chatHub")
       .configureLogging(signalR.LogLevel.Trace)
      .build();
connection.on("receivemessage", function(user, message) {
    var msg = message.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    var encodedmsg = user + " says " + msg;
    console.log(encodedmsg);
});

connection.start().catch(function(err) {
    //return console.error(err.tostring());
});

**My Asp.Net Core SignalR is that exact implementation from this tutorial:** [click here](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)

**One the Server-side, I am using:**
- Microsoft.AspNetCore.SignalR version 1.0.3
- Microsoft IIS Express (Visual Studio 2017 version 15.8.1)
- C# 
- Operating System: Windows 10 version 1803

**On the client side:**
- Node.js version 9.11.1
- Visual Studio Code version 1.26.1
- ASP.NET Core SignalR JavaScript Client version 1.0.3
- Module xhr, version 2.5.0

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
