### ISSUE TITLE
How to create Hub and new route at run-time using Roslyn scripting?

### ISSUE THREAD

**Issue by fastrocket** [aspnet/AspNetCore#5335]
In my ASP.NET Core 2.1 application, users can create new classes and types at run-time using Roslyn scripting. With that in mind, I'm trying to create a new Hub with a method that can handle this new type (input and output). I can't use generics since they are a compile-time construct. 

I believe the "new" hub will also need to be instantiated via Roslyn scripting. The reason for this is I want a strongly typed Hub and Client for performance reasons. (The strongly-typed C# client can be instantiated via Roslyn.)

However, hubs and their routes need to be declared in Startup.cs which is essentially compile-time. 

One other consideration is using a hub that uses the "dynamic" type. But this is slower than using a strongly-typed type, and could require boxing/unboxing of value types.

Any pointers would be appreciated since I have searched the web and docs to no avail. Thanks!

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
