### ISSUE TITLE
What is default Javascript SignalR Client AuthenticationScheme?

### ISSUE THREAD

**Issue by TareqNet** [aspnet/AspNetCore#5337]
Hello

I have two clients for my SignalR app: Javascript client for web browsers and Android client ([Gurgen/SignalR-.net-core-android-client][1]) that use JWT Bearer Authentication.

I added this attribute to my SignalR Hub:

    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme + "," + CookieAuthenticationDefaults.AuthenticationScheme)]
    public class MyHub : Hub
And my _Startup.cs_ file:

            public void ConfigureServices(IServiceCollection services)
            {
            //…
            services.AddAuthentication()
                .AddCookie(cfg => cfg.SlidingExpiration = true)
                .AddJwtBearer(options =>
                {
                    options.RequireHttpsMetadata = false;
                    options.SaveToken = true;
                    options.TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidIssuer = Configuration["Tokens:Issuer"],
                        ValidAudience = Configuration["Tokens:Issuer"],
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["Tokens:Key"]))
                    };
                });
            services.AddSignalR();
            //…

Android client login successfully with header authentication bearer token. **But** web client comes failed connecting to the hub (401 Unauthorized).

When I remove [Authorize] attribute the javascript client works!

What is default Javascript SignalR Client AuthenticationScheme? Or what is the issue I made?

I use Microsoft.AspNetCore.SignalR and my IDE is Visual Studio for Mac on Mac OS.

  [1]: https://github.com/Gurgen/SignalR-.net-core-android-client

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
