### ISSUE TITLE
HubCallerContext as an injectable

### ISSUE THREAD

**Issue by replaysMike** [aspnet/AspNetCore#5338]
Are there any plans to make HubCallerContext an injectable? This would be nice as IHubContext<> doesn't contain any information about the current user making the request.

I can manually pass around a user context to my services, but it would be better to inject this.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
