### ISSUE TITLE
ASP.NET Core SignalR Authentication on .net WPF returns -  401 (Unauthorized)

### ISSUE THREAD

**Issue by generalpaul** [aspnet/AspNetCore#5340]
I am trying to connecting the server using JWT authentication. I downloaded your sample 
Docs/aspnetcore/signalr/authn-and-authz/sample and works fine. 

However when connecting on .net client, it throws after the .StartAsync():
**Response status code does not indicate success: 401 (Unauthorized).**

I did this.
 options.AccessTokenProvider = async () =>
                          {
                                httpResponse = await new HttpClient().PostAsync("host with token", null);
                                httpResponse.EnsureSuccessStatusCode();
                                return await httpResponse.Content.ReadAsStringAsync();
                          };

the server validates the user and password. and passes ok on JwtSecurityTokenHandler.
but on hubs/chat/negotiate it returns the 401 (Unauthorized).

what i found out is it does not enter on the options.TokenValidationParameters part on jwtbearer.

i followed  #2431 that was recently closed but no success.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
