### ISSUE TITLE
Add In-process ANCM tests/ Re-enable ANCM out of process tests. 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#5346]

**Comment by mkArtakMSFT** [comment]
@muratg, is this still planned to be done? If not, I'd just close it. Though I see the value.

**Comment by muratg** [comment]
@jkotalik do we have test coverage now?

**Comment by jkotalik** [comment]
What repo was this originally filed in? It relates to functional tests up-stack but not sure where.

**Comment by muratg** [comment]
@jkotalik I'm not sure where this was moved from.  Could it be servertests?

**Comment by anurse** [comment]
What's the story here @jkotalik ? Old news?

**Comment by jkotalik** [comment]
Yeah real old

**Comment by anurse** [comment]
![old lady "deal with it"](https://media.giphy.com/media/50rJushu3URtS/giphy.gif)
