### ISSUE TITLE
Poor documentation and error messages

### ISSUE THREAD

**Issue by ptallett** [aspnet/AspNetCore#5348]
I wanted to add SignalR to my existing ASP.NET Core project which was serving my Angular SPA. I started by reading this article https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-getting-started-with-signalr/

where it clearly states that the SignalR route mapping should go at the END of the Configure method. Doing that gave me a 404 error because it was after my UseSpa method which swallows all the routes. However, I thought it might be a Cors issue, or a version mismatch. Moving those lines earlier just gave a "Could not initialize transports" error which sounded like it was happening too soon, so I moved it back. I noticed that putting an invalid hub name in the client made no difference, so I clearly wasn't getting through to the server.

8 hours of hard slog later after reading hundreds of posts, I found one that mentioned the UseSpa swallowing the routes - if only the error had said "Hub not found".

So then I set about fixing the "Could not initialize transports" error. I tried configuring long polling, switching the version of my client library. My server was running ASP.NET Core 2.1 so that should be fine. Nothing I did would resolve the error. 4 more hours of hard slog later, I noticed that although VS was saying I was running .NET Core 2.1, it was loading some funky preview. I'd only ever installed released code on my machine so I don't know where the preview came from. If only the error had said "Client/server version mismatch" - surely not rocket science. So I then updated all the NuGet packages to the latest 2.1 release, but I ran into the "Method was called with 2 arguments but was expecting 0" error, documented in another issue, but I was making progress, it was trying to call my code. Of course my methods had the correct number of arguments but the wrong names - if only it had said "Method not found".

So after 12 hours of hard slog, I finally got it to work! If only the docs had been correct, if only the error messages had not just said Error negotiating: error.

Please improve the error messages and docs, SignalR is awesome!

Cheers,
Paul

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
