### ISSUE TITLE
Discussion: SignalR Java Client Package Name Change

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#5349]
This is a discussion item for https://github.com/aspnet/Announcements/issues/321. Please see the announcement for details.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
