### ISSUE TITLE
Self host and error handling

### ISSUE THREAD

**Issue by bdominguez** [aspnet/AspNetCore#5352]
I'm integrating a SignalR server inside a WPF application.

My problem is that whenever an error occurs on a hub I can't handle it in a global way.

See this line:

https://github.com/aspnet/SignalR/blob/defbadb26b4224d5025549992fc5ae4e95e0d288/src/Microsoft.AspNetCore.SignalR.Core/HubConnectionHandler.cs#L113

As you can see it's handled internally so I can't handle it myself.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
