### ISSUE TITLE
Handling Clients who become un-authorized whilst connected to a hub

### ISSUE THREAD

**Issue by BenjaminOsborne** [aspnet/AspNetCore#5354]
Hi,

I have a scenario (raised during a discussion at work about how we use SignalR) about how to manage Clients who are connected to a Hub (using WebSockets), with Cookie based Auth, who become un-authorized during the connection.

**The critical scenario of interest is**:
- We have User accounts where users can login to our website with a username/password and obtain cookies which are valid for a time period (using AspNetCore Identity).
- A Client (C1) connects to an Authorized hub with valid cookies (obtained by logging in to the site).
- Another malicious Client (C2) obtains their password, logs into their account, obtains valid cookies and then creates a connection with the hub with the same account).
- Client C1, realises, changes their password, so existing cookies obtained with previous password are now invalid
- Client C2 however remains connected, and even after the password reset event, continues to receive data they should no longer have access to.

**Question**:
Is there anything which can be done to kick off a specific connected client when an event occurs which causes their cookie becomes invalid during a connection?
(Assuming that the we cannot trust the Client to honour any specific hand-rolled disconnect message or similar)
(I have observed that putting the Authorise attribute at method-level causes Auth to be evaluate for all Client invocations of those methods, but I have not seen a way to re-auth any pushes from the server back to connected Clients).

Apologies where I have not understood the docs correctly, I hope this is not a completely idiotic question!
Many thanks in advance for your advice.

Ps. Been using SignalR for a few months now, really excellent product, thanks for all here who work on it, made life a lot easier!

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
