### ISSUE TITLE
Add extra parameter in SignalR method without breaking changes

### ISSUE THREAD

**Issue by njangir2** [aspnet/AspNetCore#5355]
I want to pass additional parameter via Signalr without any breaking changes.

SignalR hub web api side signalr nuget package being used is "Microsoft.AspNetCore.SignalR" Version="1.0.3".
Client side nuget package being used is "Microsoft.AspNetCore.SignalR.Client" Version="1.0.3" />

Initial code at signalr hub web api side is given below-

    public async Task<bool> SendResponse(string uniqueId, string param1, string param2, string param3, string param4, string param5, string param6)
    {
    	await HubContext.Clients.Group(uniqueId).SendAsync("SendResponse", param1, param2, param3, param4, param5,param6);
    	return true;
    }

Initial code at client side-

    Connection.On<string, string, string, string, string, string>("SendResponse",
    async (param1, param2, param3, param4, param5, param6) =>
    {
    	//code here.
    });
This client side code is shared with everyone via a nuget package and its on application owner when he want to update the nuget package.

Till now everything is working fine a changed requirement (pass a new parameter with response) arise.

To fulfill this requirement I have made below given code changes in signalr hub side-

    public async Task<bool> SendResponse(string uniqueId, string param1, string param2, string param3, string param4, string param5, string param6, string param7)
    {
    	//send 6 parameters in old method so that client code can continue his work without updating client side code changes.
    	await HubContext.Clients.Group(uniqueId).SendAsync("SendResponse", param1, param2, param3, param4, param5, param6);
    	//Send 7 parameters in new method.
    	await HubContext.Clients.Group(uniqueId).SendAsync("SendResponse2", param1, param2, param3, param4, param5, param6, param7);	
    	return true;
    }
SignalR is hub web api service updated with these code changes and issue start arise after that.
Client applications who has old SignalR client code start receiving errors-

    Exception thrown: 'System.IO.InvalidDataException' in Microsoft.AspNetCore.SignalR.Protocols.Json.dll
    Invocation provides 7 argument(s) but target expects 0.

Changes at client side for SendResponse2 method-

    Connection.On<string, string, string, string, string, string, string>("SendResponse2",
        async (param1, param2, param3, param4, param5, param6, param7) =>
        {
        	//code here.
        });

Please let me know how can I fix this issue.
The main important thing for me is that my end user should work fine if they have updated the client side code or not.

**Comment by anurse** [comment]
Closing this as we don't plan to make these changes. The client can filter out the log messages about invoking non-existent methods. We wouldn't be able just turn off the error since that would be a breaking change.
