### ISSUE TITLE
"Resolve" deadlock with `InvokeAsync` in `On` handler

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#5356]
There's a deadlock that can happen if you call `InvokeAsync` in the `On` handler. Because `On` handlers block the event loop while they run, and `InvokeAsync` doesn't release until the completion message arrives you can end up dead-locked. There are a few solutions and we should look at implementing one of them:

* Throw if `InvokeAsync` is called directly within the context of `On` to alert users that they need to dispatch that call
* Don't block the event loop on calling `On` handlers

**Comment by mikaelm12** [comment]
Done here: https://github.com/aspnet/AspNetCore/pull/8334#pullrequestreview-214864307
No longer blocking the receive loop on the execution of on handlers.
