### ISSUE TITLE
Where does SignalR store UserId for each conenction?

### ISSUE THREAD

**Issue by AwanesowArtem** [aspnet/AspNetCore#5358]
Hi all,

If SignalR supports functionality for sending message to specyfic user, it means that SignalR somewhere stores data about each ConnectionId + UserId

Thank you in advance

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
