### ISSUE TITLE
Question about changing the signalr hub protocol 

### ISSUE THREAD

**Issue by sszakal** [aspnet/AspNetCore#5359]
Hi,

I want to use/change the signalr hub protocol in the following way:
 - clients pass the type of message (instead of method name) together with the message itself (ie. CreateUserCommand or GetAllUsersQuery)
- the hub dispatcher calls Handle method on the Hub 
- the Hub Handle method will dispatch the message to the correct command/query handler. 

What's the best way to do this in Signalr Core? In previous versions of Singalr I could use PersistentConnection to do it. 

Can I override the DefaultHubDispatcher ? by creating a custom one and register it in the IoC?

Thanks,
Stefan

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
