### ISSUE TITLE
Remove Duplication in Clients while Sending Message

### ISSUE THREAD

**Issue by muzzammilhussain** [aspnet/AspNetCore#5363]
I am having an issue with SignalR here, a client in my application can belong to more than 1 groups. When the client connects I add him in specific groups. Within Group there is no duplication. Now the issue is when the same message is broadcasted among different groups having same client and same connection ID.
This is my code. notificationService is HubContext 
 await this.notificationService.SendNotificationToGroups(entity.Roles, NotificationConstants.Announcement, NotificationConstants.AnnouncementMessage);

I am using core 2.1. Thanks alot

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
