### ISSUE TITLE
when invoking a server method from client and passing objects when the model binding in SignalR fails it thrown an exception, why it doesn't work like a controller Action model binding so it doesn't thrown an exception and fill a special object ModelState to be used by developer

### ISSUE THREAD

**Issue by ahmady016** [aspnet/AspNetCore#5364]
### Please consider the following before filing an issue

* If you are using NuGet Packages that start with `Microsoft.AspNet.SignalR`, use the issue tracker at https://github.com/SignalR/SignalR to report the issue. This 
repository is for packages that start with `Microsoft.AspNetCore.SignalR` (and NPM packages that start with `@aspnet/signalr`)

### Please include as much of the following as you can in your bug report

* Versions of Server-Side NuGet Packages:
* Versions of Client-Side NuGet/NPM Packages:
* Are you using the C# client or the JavaScript client:
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
* The Operating System on the Server (Windows/Linux/macOS):
* The Operating System on the Client (Windows/Linux/macOS):
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
* Please use the Diagnostics Guide at https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide to collect server-side and client-side logs and network traces if possible. Please **do not** put the traces and logs in the Issue text as they are quite large. The Diagnostics Guide describes how to attach them to the issue.

When in doubt, feel free to file the issue, we're happy to help answer questions. We also suggest using the `asp.net-core-signalr` tag on StackOverflow to ask questions.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
