### ISSUE TITLE
[question] using SignalR with Azure traffic manager

### ISSUE THREAD

**Issue by gsantopaolo** [aspnet/AspNetCore#5369]
I've multiple instances of the same signalr hub running under traffic manager.
since i look at #2515 it seems not possible to use signalr in such scenario.
But if i use [signalr coupled with Redis](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-redis) i suppose is then possible to use it under traffic manger.
Am i right?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
