### ISSUE TITLE
How do I debug ClientSample by breakpoints？

### ISSUE THREAD

**Issue by akira32** [aspnet/AspNetCore#5371]
I rebuild all projects of SignalR. I run SignalRSample and it shows the message as below:

```
Hosting environment: Production
Content root path: C:\tmp\SignalRJava\SignalR-release-2.2\samples\SignalRSamples\bin\Debug\net461
Now listening on: http://localhost:5000
Now listening on: http://0.0.0.0:9001
Application started. Press Ctrl+C to shut down.
```
I run the ClientSample with debug mode and set the breakpoint at program.cs's Main function. But the code does not stop. So, How do I set the breakpoints and debug the code inside ClientSample?

Another problem is that the SignalRSample and ClientSample is the couple for SignalR Server and Signal Client? How do I run them correctly? Should I use the administrator privilege to run them as previous (.net framework) SignalR Server if it is a windows application?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
