### ISSUE TITLE
Is there build.gradle complete sample for Java project?

### ISSUE THREAD

**Issue by akira32** [aspnet/AspNetCore#5372]
Is there build.gradle complete sample for Java project?

```
implementation 'com.microsoft.signalr:signalr:1.0.0-preview3-35501'
implementation 'io.reactivex.rxjava2:rxjava:2.2.2'
```

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
