### ISSUE TITLE
[Question] Versioning strategy on SignalR

### ISSUE THREAD

**Issue by saibaskaran57** [aspnet/AspNetCore#5373]
Hi there, 

I would want to get some recommendation in regards to versioning strategy on signalr.

My use case will contain a single hubs that has 3 methods. It provides independant result with accepting models in params that is similar to REST. The reason i'm doing this is that to execute the 3 operation using one websocket. However, i may need to evolve it at a point on without having to break client integrations.

What's a better way to achieve it ? I have two options in my mind which is:
1) Method versioning
2) Param versioning

Appreciate for a recommendation and please do share if there are any other better ways to achieve this.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
