### ISSUE TITLE
whether connect to server?

### ISSUE THREAD

**Issue by Mangoxx90** [aspnet/AspNetCore#5375]
Execute the following code:
```java
HubConnection hubConnection = createHubConnection("https://example.com", new MockTransport(true), true, new TestHttpClient());
        hubConnection.start().timeout(1, TimeUnit.SECONDS).blockingAwait();
        hubConnection.on("Send", (name, message) -> {
            System.out.println("*******************************" + name + ": " + message);
        }, String.class, String.class);
        hubConnection.onClosed((ex) -> {
            System.out.println("*********************hubconnection Closed callback ran.");
        });
        hubConnection.stop();
```

only show  the following log：

11-05 16:58:30.865 30150-30150/com.mango.demo I/System.out: *********************hubconnection Closed callback ran.

who can tell me whether connected to server?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
