### ISSUE TITLE
Implement support for IAsyncEnumerable in the .NET client

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#5376]
Epic https://github.com/aspnet/AspNetCore/issues/8796

Split from https://github.com/aspnet/SignalR/issues/3166

Support for IAsyncEnumerable on the client (returning it from `HubConnection.StreamAsync()`). This is just a little thorny because of the open question of .NET Standard support for `IAsyncEnumerable`

**Comment by BrennanConroy** [comment]
`IAsyncEnumerable` is now available. See https://github.com/dotnet/corefx/pull/33104

- We should replace our implementation of the interface at https://github.com/aspnet/AspNetCore/blob/6699fd056e4bbf491397067e01c191223a20f3b0/src/SignalR/src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs#L72

- And we should create a new client method for `StreamAsync` which returns `IAsyncEnumerable`
- We can also consider allowing `IAsyncEnumerable` to be accepted in hub methods for the new streaming from client to server feature

**Comment by BrennanConroy** [comment]
Looks like our builds aren't ready for C# 8 yet

Moving back to 3.0.0
