### ISSUE TITLE
Make IHubClients<T> an abstract class

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#5382]
So that we can add new operators without breaking things. We'd keep the interface, but change the properties to use the abstract class (we could reargue keeping the interface later ;))

**Comment by halter73** [comment]
@davidfowl and I also discussed adding a second generic parameter for single clients (e.g. Caller, not All) which allows for interfaces with value-returning methods.

**Comment by anurse** [comment]
Default interface implementations landed in preview 5 (verified it myself). We believe this is sufficient to solve this problem without converting to an abstract class. Closing for now.

cc @davidfowl

**Comment by mikaelm12** [comment]
Marking as accepted as there is no associated change here

**Comment by mikaelm12** [comment]
**Acceptance checklist** (check one item)
* [X] We decided not to take this fix.
* [ ] The fix is tests-only.
* [ ] The fix contains product changes (**check all items below**).
	* [ ] Relevant XML documentation comments for new public APIs are present.
	* [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [ ] The change requires no docs changes.
	* [ ] Verification has been completed. (**check one item below**)
    	* [ ] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [VERSION]
			* ASP.NET Core Runtime: [VERSION]
			* .NET Core Runtime: [VERSION]
	    * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
