### ISSUE TITLE
can we still get the connection id in the latest version ?

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#5383]
_From @omuleanu on Thursday, 08 November 2018 18:07:22_

I used to be getting the getting the connection id  (in signalr v1)  like this:
```
$.connection.hub.start().done(function () {
            connId = $.connection.hub.id; // was getting different id (guid) for each browser tab
...

now, using the latest version:
```
        var connection = new signalR.HubConnectionBuilder().withUrl("/myHub").build();

        connection.start().then(function () {
            console.log(connection.id); // always 0 (zero)
```
is getting clientId possible, or is it not allowed  ?

_Copied from original issue: SignalR/SignalR#4266_

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
