### ISSUE TITLE
Server error 502 - Web server received an invalid response while acting as a gateway or proxy server

### ISSUE THREAD

**Issue by debashish2014** [aspnet/AspNetCore#5390]
Hi,

I have written a Console application to do load testing and I am using c# Microsoft.AspNetCore.SignalR.Client.Core.**HubConnectionBuilder** for creating connections to AspNet Core SignalR application, which is hosted on IIS running on a Windows Server 2012 R2 having 8 Cores and 32 GB RAM. 

We have a single Hub in the project, with below method.

```
public async Task Send(string name, string message)
{
         await Clients.All.SendAsync("BroadcastMessage", name, message);
}
```

.Net Clr Version of Application pool has been set to No Managed Code.

We are able to reach up to 16000 connections approx. Any subsequent request to the IIS leads to below error:

![image](https://user-images.githubusercontent.com/8132553/48888089-87a36d00-ee57-11e8-90bf-b710575240e9.png)

The application targets .Net Core 2.1

![image](https://user-images.githubusercontent.com/8132553/48888417-a7876080-ee58-11e8-97c4-663e7ac8e149.png)

We have tried deploying the applction on a Azure VM (8 Cores, 32 Gb RAM, Windows Server 2016) as well, but the result is same. 

IIS configuration **appConcurrentRequestLimit** has been set to 80000

`appcmd.exe set config /section:system.webserver/serverRuntime /appConcurrentRequestLimit:80000
`

We also tried modifying below Kestrel settings, but ended up in vain.

```
.UseKestrel(options =>
        {
            options.Limits.MaxConcurrentConnections = 80000;
            options.Limits.MaxConcurrentUpgradedConnections = 80000;
        });
```

Are we missing anything?

**Comment by mikaelm12** [comment]
Any ideas here  as to why the configured concurrent connection limit isn't respected @pakrym @jkotalik? Thanks!

**Comment by pakrym** [comment]
Do you have https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/site/limits `maxConnections` set?

**Comment by MRT-77** [comment]
I received 502 error after upgrading the "Hosting Bundle"
