### ISSUE TITLE
How to benchmark my signalR?

### ISSUE THREAD

**Issue by bluetianx** [aspnet/AspNetCore#5391]
I want to benchmark my signalr, I dose not find Microsoft doc that about benchmark signalr. can you give some advice to me . Tks very .  my  version of asp.net core  is  2.1

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
