### ISSUE TITLE
Question: using ClientWebsocket to connect to SignalR Hub

### ISSUE THREAD

**Issue by riccardobecker** [aspnet/AspNetCore#5396]
Hi all,

not an issue but merely a question. I have a scenario where i need to use a websocketclient (ClientWebsocket, WebsocketSharp) to connect and communicate directly with a signalR hub and thus using "ws://......." to connect to and also being able to specify subprotocol. Is this possible at all?
Thanks in advance,
Riccard

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
