### ISSUE TITLE
feat: in-memory stub for local development

### ISSUE THREAD

**Issue by IlCallo** [aspnet/AspNetCore#5397]
### Please include as much of the following as you can in your bug report

* Versions of Client-Side NPM Packages: 1.1.0
* Are you using the C# client or the JavaScript client: JS/TS
* The Operating System on the Client (Windows/Linux/macOS): Windows
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): All

### Proposal

Have you considered developing an in-memory stub which, if enabled, simulates websocket connection with a developer-given dataset using observables?
Something like [this](https://github.com/angular/in-memory-web-api) (not necessarily built on Angular as the example).

If no, are you interested into making one and what do you think will be the effort to build it (if it's doable at all)?
Would you accept a PR for that?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
