### ISSUE TITLE
How does DI work in regard to DbContext and hubs?

### ISSUE THREAD

**Issue by emilmuller** [aspnet/AspNetCore#5399]
According to the documentation at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2:

> Entity Framework contexts should be added to the service container using the scoped lifetime. This is handled automatically with a call to the AddDbContext method when registering the database context. Services that use the database context should also use the scoped lifetime.

And the definition for a scoped lifetime:

> Scoped lifetime services are created once per request.

What does that mean when injecting scoped instances into hubs, e.g. DbContexts? Are they disposed of at the end of the request - i.e. when the websocket gets closed? Or when a method call ends?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
