### ISSUE TITLE
signalr-protocol-msgpack 1.1.0 TS definitions are incompatible with signalr 1.1.0

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/AspNetCore#5400]
>Error	TS2345	(TS) Argument of type 'MessagePackHubProtocol' is not assignable to parameter of type 'IHubProtocol'.
  Types of property 'parseMessages' are incompatible.
    Type '(input: ArrayBuffer | Buffer, logger: ILogger) => HubMessage[]' is not assignable to type '(input: string | ArrayBuffer, logger: ILogger) => HubMessage[]'.
      Types of parameters 'input' and 'input' are incompatible.
        Type 'string | ArrayBuffer' is not assignable to type 'ArrayBuffer | Buffer'.
          Type 'string' is not assignable to type 'ArrayBuffer | Buffer'.	

https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/ts/signalr-protocol-msgpack/src/MessagePackHubProtocol.ts#L33
https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/ts/signalr/src/IHubProtocol.ts#L184

**Comment by natemcmaster** [comment]
@BrennanConroy can you fill in the shiproom template? https://microsoft.sharepoint.com/teams/netfx/CLR/ProjectK/_layouts/OneNote.aspx?id=%2Fteams%2Fnetfx%2FCLR%2FProjectK%2FDocuments%2FTactics%2FNET%20Core%20Release%2Fnet-core-release&wd=target%28net-core-release.one%7C0CF34A20-F342-FA43-8944-18B555589A6B%2FShiproom%20Info%20and%20Templates%7C30A2770F-73EF-A74D-9C01-0D0B4BEAC431%2F%29

Also, please wait to merge until this approved and https://github.com/aspnet/AspNetCore-Internal/issues/1610 has been resolved.

**Comment by BrennanConroy** [comment]
Keeping this open to track writing automated testing for this.

**Comment by anurse** [comment]
CTI testing for TypeScript might be a better approach here.
