### ISSUE TITLE
QR Codes should be supported in templates 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore#5405]
[Enabling QR Code generation for authenticator apps](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes)

That should be supported in the templates like [SMS 2FA](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/2fa) used to be. 

requested by customer in [Enabling QR Code generation for authenticator apps](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes) comments

**Comment by mkArtakMSFT** [comment]
Closing this as it seems we won't be able to do this in the near future.

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT can we schedule this for 3.1?
