### ISSUE TITLE
Authentication on SPA apps

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#5407]
_From @Dave3of5 on August 23, 2017 7:54_

There seems to be no template for authentication on the SPA templates.

I've been looking up various blog post and third party articles on how to add Jwt Authentication but they are scattered and most are for dotnet core 1.1. It would be nice if there was a template that showed the "correct" way to do this in dotnet core 2.0.

_Copied from original issue: aspnet/Templates#864_

**Comment by brockallen** [comment]
We showed how to do this back in January 2018: https://vimeo.com/254635632

**Comment by javiercn** [comment]
This has been merged for preview3
