### ISSUE TITLE
Poor user and dev experience in Identity email confirmation

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#5409]
_From @natelaff on December 30, 2015 19:42_

There are two issues using the default template for identity when using email confirmation.

Following the guide here: http://docs.asp.net/en/latest/security/authentication/accconfirm.html

Poor user experience: When you click "Register" it sends the email off, but just redirects the user to the Home controller. Redirecting to something else to indicate they have to confirm their account would be a better example. Perhaps the default template should have such a view OOTB.

Poor dev experience: When logging in with an external account (lets say Facebook) if the account doesn't exist you get thrown into AccountController.ExternalLoginConfirmation, great. This screen requires an email, so you complete the registration then you're logged in but never shoots off the email confirmation link here. Perhaps a commented out section in this action to deal with this would improve the dev experience here.

_Copied from original issue: aspnet/Templates#365_

**Comment by HaoK** [comment]
I think this is already in the current templates, after logging in, you can go to manage page and there's a resend confirmation link if not confirmed, its a green checkbox otherwise.  @blowdart is that sufficient?

**Comment by javiercn** [comment]
Is the bit about the external login fixed too? I think that was the main pain ñoknt

**Comment by HaoK** [comment]
Yep that was done already recently in  https://github.com/aspnet/AspNetCore/issues/5767, closing this bug then as it will be taken care of via #8356 when its merged
