### ISSUE TITLE
Feature request: email confirmation  resend

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore#5410]
related issue: Poor user and dev experience in Identity email confirmation #124

We have lots of customer complaints at the end [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?tabs=aspnetcore2x%2Csql-server)

>  I found it odd that, when requiring email confirmation, if for whatever reason the user misses the original email with the confirmation link, the login view reminds you but there is no way to get the app to resend the confirmation.  

> I understand in some cases users miss to confirm their email account, and they should be able to see the option of "Resend Email Confirmation Link" when they try to login. Unfortunately I could not find any documentation to solve this problem, but what I did. I created a controller with Read, Delete action methods that can be used to delete unconfirmed email accounts from admin panel of my application. And then any unverified email can be used again to register in our application. I think that there is a better way to send confirmation link again through the application which I don't know.

**Comment by Rick-Anderson** [comment]
@haok Is the following work around OK?

For those willing to risk *Flood of lost password emails* can I get a work around to document until this feature is supported?


Model a solution by looking at the following methods, `ForgotPassword`, and `Register`.  The register method has the code generating the token (code) and callback for sending the email confirmation.  Create get, post methods named `ResendEmailConfirmation`.

**Comment by HaoK** [comment]
Yep this will be implemented pretty much just as a new form that lets you resend confirmation from somewhere(tbd), but they can do that themselves using that send confirmation code from either method

**Comment by HaoK** [comment]
As of https://github.com/aspnet/AspNetCore/issues/5767 you can resend email confirmations via manage (if you can log in), or from the login links
