### ISSUE TITLE
Revisit default bundling behavior

### ISSUE THREAD

**Issue by poke** [aspnet/AspNetCore#5411]
This is in response to the resolution in #20 and #89:

> No plans to include bundling in the default template at this time. We will revisit in the future.

---

If you currently create a new ASP.NET Core application and you are not using an SPA-template (which uses Webpack for building), then you are in the unfortunate situation that the project appears to be using the [bundling and minification feature](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification) yet that’s not what’s actually happening.

The following things are there:

- A `bundleconfig.json` is in the project root that is configured to produce the `site.min.css` and the `site.min.js` files.
- The `wwwroot` folder contains **pre-built** versions of those exact bundled files.
- The `_Layout.cshtml` contains environment tag helpers that switch to the minified bundles on non-Development builds:
    ```
    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    …

    <environment include="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    ```

So the user is made to believe that bundles are being created and that for production builds, those minified versions will be used automatically. Since minified files are also nested in the solution explorer, users are unlikely to actually *look* inside the files to verify that they actually do contain the desired contents.

Yet, the problem is that with Visual Studio 2017, Visual Studio Code, or when running `dotnet` from the command line, there is by default **nothing** that is actually consuming that `bundleconfig.json` file to generate those files. So users will end up with the default bundle files which contain mostly nothing.

Instead, users are apparently expected to do one of the following three things:
- Install the [Bundler & Minifier VS extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BundlerMinifier) to get the bundling done by Visual Studio
- Add the [`BundlerMinifier.Core` NuGet package](https://www.nuget.org/packages/BundlerMinifier.Core/) to get the `dotnet bundle` command.
- Add the [`BuildBundlerMinifier` NuGet package](https://www.nuget.org/packages/BuildBundlerMinifier/) to actually get a build task automatically added that will bundle the files automatically on every build.

By the indications mentioned above, the user is likely to expect this to work out of the box, just like *everything* in the templates already runs out of the box. Yet, they actively need to add a bundling method without being told to do so. The *only* thing that comes close to a hint is when you happen to open the `bundleconfig.json` in Visual Studio. Then, VS suggests you to look for “helpful extensions”, without actually clearly saying that this is in any way required. Not to mention that users that are not using VS are completely left in the dark.

So I would very strongly suggest that we actually do include the `BuildBundlerMinifier` package in the default templates, to make the bundling that is clearly configured and expected to work actually work. If we cannot do that since the package is not an *“official”* Microsoft package, then I would suggest to get rid of the bundling in the templates altogether.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
