### ISSUE TITLE
'x-content-type-options' header is not specified

### ISSUE THREAD

**Issue by ghost** [aspnet/AspNetCore#5418]
default ASP.NET Core Web Application using Kestrel

- `<script src="/lib/bootstrap/dist/js/bootstrap.js"></script>`
- `<link rel="stylesheet" href="/css/site.css">`
- `<link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css">`
- `<script src="/lib/jquery/dist/jquery.js"></script>`
- `<script src="/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA"></script>`

[Require `X-Content-Type-Options` HTTP response header](https://sonarwhal.com/docs/user-guide/rules/rule-x-content-type-options/)

**Comment by ryanbrandenburg** [comment]
Seems this issue ought to be on the Backlog since the issue it depends on is.

**Comment by ryanbrandenburg** [comment]
Oh, aspnet/Docs doesn't use the same milestones as us. I still think it might belong on the backlog, but I'll leave it up to the managers.

**Comment by mkArtakMSFT** [comment]
We're closing this issue as external. As pointed out in the referenced issue, there will be docs article on how to do this.
