### ISSUE TITLE
Create aspnet testing templates

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#5420]
Following up to https://github.com/aspnet/Mvc/issues/7710. We could consider shipping (either OOB or as part of the next SDK release) a template illustrating how to set up a test project for aspnet apps. The difference between this template and the normal test template is an additional reference `<PackageReference Include="Microsoft.AspNetCore.App" />` and changing the SDK from `Microsoft.NET.Sdk` to `Microsoft.NET.Sdk.Web`.

**Comment by VictorioBerra** [comment]
What does the "C" label mean?

**Comment by pranavkm** [comment]
@VictorioBerra I wanted to bring up some issues sitting in backlog for **C**onsideration as we plan for the 5.0 release.
