### ISSUE TITLE
Move scaffolding content to from aspnet/scaffolding to aspnet/templating

### ISSUE THREAD

**Issue by seancpeters** [aspnet/AspNetCore#5421]
Here is the equivalent issue in aspnet/scaffolding https://github.com/aspnet/Scaffolding/issues/798
(Work needs to be done in both repos).

**Comment by mkArtakMSFT** [comment]
Closing this as this is not possible with Mondo repo given Scaffolding is not part of it.

**Comment by ryanbrandenburg** [comment]
I don't think that's true, we could add Scaffolding to the Mondo repo (possibly easier said than done). Another (less robust but easier to implement) option would be to automatically create PRs that copy the contents of Mondo in to the correct place in scaffolding.

So long as we mandate that the contents of these two places be the same and we make changes to those contents (neither of which I disagree with) we're going to need some sort of solution in this area.
