### ISSUE TITLE
Identify ASP.NET template version installed or used in project

### ISSUE THREAD

**Issue by jasonsturges** [aspnet/AspNetCore#5422]
How can I identify the version of ASP.NET templating currently installed or via `dotnet` commands?  Is this possible; otherwise, an enhancement deemed worthwhille?  Or would this be an issue with the scaffolding project?

For example, ASP.NET Templating repo updated to version 2.0.8 two weeks ago.

Inside Visual Studio, when I look at the templates installed I'm not seeing an identifier that I can correlate back to the template version:

WebTemplateCore.vstemplate

```
<VSTemplate Version="3.0.0" xmlns="http://schemas.microsoft.com/developer/vstemplate/2005" Type="ProjectGroup">
  <TemplateData>
    <Name Package="{0CD94836-1526-4E85-87D3-FB5274C5AFC9}" ID="6001"/>
    <Description Package="{0CD94836-1526-4E85-87D3-FB5274C5AFC9}" ID="6002"/>
    <Icon Package="{AAB75614-2F8F-4DA6-B0A6-763C6DBB2969}" ID="4" />
    <ProjectType>CSharp</ProjectType>
    <ProjectSubType>Web</ProjectSubType>
    <TemplateGroupID>Web</TemplateGroupID>
    <TemplateID>Microsoft.DotNet.CSharp.ASPNET.WebCore</TemplateID>
```

Issuing the `dotnet new` command doesn't give any version of the templates installed

```
Templates                                         Short Name       Language          Tags               
--------------------------------------------------------------------------------------------------------
Console Application                               console          [C#], F#, VB      Common/Console     
Class library                                     classlib         [C#], F#, VB      Common/Library     
Unit Test Project                                 mstest           [C#], F#, VB      Test/MSTest        
xUnit Test Project                                xunit            [C#], F#, VB      Test/xUnit         
ASP.NET Core Empty                                web              [C#], F#          Web/Empty          
ASP.NET Core Web App (Model-View-Controller)      mvc              [C#], F#          Web/MVC            
ASP.NET Core Web App                              razor            [C#]              Web/MVC/Razor Pages
```

Where I personally would desire this information the most is within the generated templates, such as a comment in the generated code.  This way, I could refer to that version information within a project to understand which templates were used in the solution.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
