### ISSUE TITLE
Firefox processes launched by Selenium don't always close

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#5425]
Firefox processes launched by Selenium don't always close, this is a possible cause of hangs in VSTS, pollutes our TC agents and likely contributes to unreliability/slowness of other Templating tests.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, do we still have TC agents? Should we close this?

**Comment by ryanbrandenburg** [comment]
We still have TC agents, but they are no longer the primary shipping mechanisms, and I have not seen the behavior recently. Given that I'm closing this out.
