### ISSUE TITLE
Add template parameter for cookie consent UI to Web Application project template

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCore#5444]
The cookie consent UI in the web application template should be an option in the web application template. I'd make it off by default at the cmd line, and on by default in VS. The option should be visualized in VS with a checkbox. Disabling the option should remove:
- `_CookieConsentPartial.cshtml`
- The `app.UseCookiePolicy()` line in `Startup.cs` (and associated `using`)
- The `services.Configure<CookiePolicyOptions>` call in `Startup.cs` (and associated `using`)
- The `<partial name="_CookieConsentPartial" />` line in `_Layout.cshtml`

@danroth27

**Comment by mkArtakMSFT** [comment]
@danroth27 , you define the priority for this, please.

**Comment by mkArtakMSFT** [comment]
@Eilon FYI

**Comment by mkArtakMSFT** [comment]
@danroth27, there is a tooling aspect here. Can you please handle that with the tooling team? We'll do the rest as part of this work item.

**Comment by danroth27** [comment]
Yes, we've already brought this up with the tooling folks. We just need to firm up the plans.

**Comment by mkArtakMSFT** [comment]
This is actually mentioned in the #9937, where we've decided to turn this into a doc instead of bringing in an option.
