### ISSUE TITLE
Template does not include ProducesResponseType

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/AspNetCore#5445]
The Web API template does not have actions that are decorated using the `ProducesResponseType` attribute.

The `ProducesResponseType` attribute which should be considered to be added since it would improve integration with software such as [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) (Swagger).

**Comment by mkArtakMSFT** [comment]
@pranavkm, doesn't the default API convention cover this? If so, just close this issue please.

**Comment by pranavkm** [comment]
Not everyone uses OpenAPI \ Swagger in their applications and we wouldn't want to add a ton of additional code to the template \ scaffolded code that wouldn't benefit everyone. For the 2.2 release, our recommendation is to use [conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-2.2) and [the analyzer](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-2.2&tabs=visual-studio) that goes with it to remove a lot of boiler plate `ProducesResponseType` attributes from your code and provide code fixes when your action requires being decorated with `ProducesResponseTypeAttributes`.

**Comment by glennc** [comment]
Closing, as @pranavkm said we are trying to move to a world with less explicit declarations of those types of attributes so we wouldn't want to add them to the templates now.
