### ISSUE TITLE
Functional tests are slow

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#5448]
Our functional tests take 30 seconds to 3 minutes, and based on circumstantial evidence I don't think most of that time is spent in browser automation. We should profile the tests and see where we're spending time, and if it can be trimmed down.

This would be helpful for release turn-around, but even more so for local development, where a full build can take quite a while, making it hard to develop with.

**Comment by danroth27** [comment]
No actionable work here.
