### ISSUE TITLE
Enhancements to components

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#5455]

**Comment by SteveSandersonMS** [comment]
Moving out of the preview3 milestone because nothing specific in this issue is planned for preview 3.

**Comment by SteveSandersonMS** [comment]
I've moved the "key" item to a new issue at https://github.com/aspnet/AspNetCore/issues/8232

And as for what remains besides that, it's more a list of mostly-outdated ideas than things we're committed to. We can create new issues for anything that still comes up as a requirement.

A moment of contemplation, if you will, as we finally close what was the original issue 1 at https://github.com/aspnet/blazor/issues/1.

**Comment by rynowak** [comment]
> Press F to pay respects
