### ISSUE TITLE
Enable browser automation in CI

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#5457]
Add a PR validation job that runs the e2e tests.

Windows at a minimum, xplat is a bonus.

**Comment by pranavkm** [comment]
@SteveSandersonMS what's left to be done here?

**Comment by javiercn** [comment]
Done

**Comment by javiercn** [comment]
Xplat still missing

**Comment by javiercn** [comment]
This is Azure Pipelines, not team city. Do we also want it running there?

**Comment by SteveSandersonMS** [comment]
@javiercn As far as I know, Azure Pipelines is all we need now :) I assumed we were retiring TeamCity soon anyway.

**Comment by javiercn** [comment]
Yeah, I filed a different issue to track everything left.
