### ISSUE TITLE
Runtime Culture and Localization

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#5471]
Please consider browser runtime cultural and allow switching of culture with in the Blazor environment

**Comment by SteveSandersonMS** [comment]
When doing this, be sure to check cases around Data Annotations validation and the built-in parsing validators in the `Input*` components to be sure they localize conveniently.

**Comment by DamianEdwards** [comment]
Is this issue intended to cover just the WASM side of the world, or localization in the Razor Components server-side features in 3.0 too?

**Comment by SteveSandersonMS** [comment]
@DamianEdwards Both. Currently this issue is quite high-level and all-encompassing, but will get broken down into several sub-issues as we start work on it.

**Comment by grahamehorner** [comment]
IMHO and just for my two pennies worth @SteveSandersonMS ;) as a developer and a multi-lingual application Razor Component circuits would need some mechanism to send the users browser culture to the server; to allow the rendering component(s) to identifier the correct resources to use and/or having routing determine any culture specifics; so for a starter for 10 a smaller task of the bigger story IMHO would be to possibly update the component circuit implementation to provide browser agent string and culture with in the messages sent to the signalr hub.

NOTE: do you think a user should be able to switch culture of the browser without causing issues/re-login etc. ? or should a user session be forced into a fixed culture ?

**Comment by Franklin89** [comment]
I have experienced a strange behavior (in my opinion strange) as I wanted to try to implement some sort of localization (client side blazor). If I set the `CultureInfo` in the startup of the client app:

```
public void Configure(IComponentsApplicationBuilder app)
{
    System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("de-CH");
    System.Threading.Thread.CurrentThread.CurrentUICulture = new CultureInfo("de-CH");

    app.AddComponent<App>("app");
}
```

and then render a input with a `DateTime` field the input gets rendered in the correct format according to the culture. If I then change the date inside the input and the state gets updated the date gets displayed in the default format. I then tried the same with a string property.

```
public string Birthdate
{
    get
    {
        Console.WriteLine(System.Threading.Thread.CurrentThread.CurrentCulture);
        return Birthdate.ToShortDateString();
    }
    set
    {
        Birthdate = DateTime.Parse(value);
    }
}
```

The culture that gets written to the console first shows the correct culture. After changing the value the culture is empty. So it seems to me that the culture gets cleared somehow.

**Comment by RemiBou** [comment]
The current browser language is quite easy to get with JsInterop and apply it to the current thread ([see my blog post](https://remibou.github.io/Localizing-DateTime-in-Blazor/)

```js
navigatorLanguages = function () {
    return navigator.languages;
}
```

On your Startup.Configure method just init the current culture like this
```
 app.Services.GetRequiredService<IJSRuntime>().InvokeAsync<string[]>("navigatorLanguages")
                .ContinueWith(t => CultureInfo.DefaultThreadCurrentCulture = t.Result.Select(c => CultureInfo.GetCultureInfo(c)).FirstOrDefault());
```

Your date will be translated and your numbers will be formated with the good culture.

**Comment by rynowak** [comment]
We're using https://github.com/aspnet/AspNetCore/issues/9386 to track this area.
