### ISSUE TITLE
Blazor Security/Authorization

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#5472]
Please consider a claim/policy based client-side authorisation framework where user claims/cookies can be evaluated with in the blazor runtime, to enable/disable application functionality/ui features based on user claims/policy evaluation.

**Comment by grahamehorner** [comment]
I have been looking into the authorisation and have a working example for server-side blazor and client-side blazor; the sample uses the users claims token returned from the approved/configured oauth service(s) (Microsoft, Facebook, Twitter, etc) this token is held in a client-side cookie and is signed to prevent unauthorised modification, when blazor is required to perform an authorisation check, the cookie is verified by blazor asking the  oauth provider to confirm the token is validate and active (not expired) if all is well the token is  evaluate decoded and evaluated by the authorisation policy to determine a granted/denied status accordingly.

I will be doing some tied-up of the code and then writing a blog post about this, I welcome feedback should anyone have any ideas or thoughts around this?

**Comment by yberstad** [comment]
Hi @grahamehorner or @robertmclaws, have you gotten time to publish a blog post regarding this issue? It would have been much appreciated! 😃 Thanks in advance!

**Comment by SteveSandersonMS** [comment]
Moved to preview 5 backlog not because I think we really have time to do it then, but to force us to re-triage this to an actual preview release.

**Comment by mkArtakMSFT** [comment]
Closing as a dupe with https://github.com/aspnet/AspNetCore/issues/4048
