### ISSUE TITLE
Routing enhancements

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#5489]
This issue is to track routing features we're likely to want to add in the future:

* Review exactly which parameter constraints we really want to support. For example maybe add `regex`; maybe remove `bool` or limit the set of `datetime` formats more precisely. See https://github.com/aspnet/blazor/issues/295 for more discussion.
* Catch-all segments (e.g., `/products/{*categoryAndName}`)
* 404 handler (it's probably not enough just to have a component that matches `/{*anythingElse}`, because for SSR you'd want to know it's really not a match so you could actually return a 404) - Done!
* Simple method for accessing querystring/hash values (e.g., via new properties on `IUriHelper`)
* Multiple nested routers
* Outbound URL generation (e.g., `<a page=@About>About us</a>`, or perhaps just by codegenning methods like `<a href=@Products.Url(53)>Duck boots</a>` for each `@page` declaration)
* In the `@page` directive, allow the use of compile-time constant expressions, not just literal strings (e.g., https://github.com/aspnet/blazor/issues/1363).
* Optional route parameters

Also the items from https://github.com/aspnet/blazor/issues/636 that were not yet finalised:

 * Discover `[Route]` attributes on types in referenced assemblies that themselves reference `Microsoft.AspNetCore.Blazor` transitively
 * Discover `[Route]` attributes on component base classes (i.e., inherit=true)
 * In the `Router` component, make it simple to subclass and override a virtual method to change the logic for locating the `IComponent` for a given URL. Currently there's no virtual method for this.
 * Make `RouteTable`'s `Routes` property `get`-only
 * Cache route tables per assembly

**Comment by iron9light** [comment]
@SteveSandersonMS Support subfix with catch-all routing.
Something like this: "{controller}/{**path}/{action}"

**Comment by LukeTOBrien** [comment]
Just to add my 2 cent to this.  
With ref to what @Nathan-Ryan said

> similar to the way angular works with the router-outlet component.

I use `router-outlet` in my Angular apps.  
In my apps I have the _main_ outlet and a _dialog_ outlet, this dialog outlet is then navigated to/populated in code and then I have CSS that presents the dialog as a model.

I don't know what method anyone else would do for models in Blazor or Angular, but this is how I do them and it works well.  
I haven't played about with Blazor much yet.

**Comment by CornedBee** [comment]
Router should be more flexible in determining what components it looks at. Currently it simply takes a single assembly and searches that and its dependencies. I think it would be nice if the line `var types = ComponentResolver.ResolveComponents(AppAssembly);` would be turned into an overridable function. Then I could, for example, determine the set of types to look at based on configuration files or similar.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS given the many aspects being touched in this issue I'm going to close it now. Please file separate issues for things which are still valid and important.

**Comment by mrpmorris** [comment]
Allowing custom coded constraints would be nice!
