### ISSUE TITLE
PutJsonAsync<T> cause no exception on http-Status BadRequest

### ISSUE THREAD

**Issue by TiborCsizmadia** [aspnet/AspNetCore#5491]
The extension ethod of the class HttpClient for reading an typed object returns no status information of the response:

CurrentUser = await http.PostJsonAsync<AppUser>("/api/auth/login", credentials);

This line cause no exception or something else, if the http Request returns the status BadRequest

**Comment by SteveSandersonMS** [comment]
This was fixed a few days ago.

**Comment by dbowser** [comment]
Umm, how was it fixed? Still seems to be an issue to me. If there is now a way to handle this please share what it is...
