### ISSUE TITLE
Avoid 'dist' subdirectory in published artifacts (requires changing UseBlazor middleware)

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore#5493]
On publish, the assets are going into a folder with the same name as the app and *web.config* sits at the root of *publish* with rewrite rules to serve from *{app_name}/dist*.

```
publish
    -- StandaloneApp
        -- dist
            -- _framework
            -- css
            -- index.html
    -- web.config
```
... but I was expecting a much flatter structure akin to what has been done with ASP.NET Core ... something along the lines of ...

```
publish
   -- _framework
   -- css
   -- index.html
   -- web.config
```
I have the notion that *dist* is a holdover from other frameworks. Having the app name in the mix seems strange. Just wondering why it was setup this way?

Would it be an improvement to use the flatter structure (following the ASP.NET Core publishing philosophy these days)? The structure is simpler and the rewrite rules can be dropped. There might be an additional reason to use the flatter structure: My understanding was that the *web.config* was placed into a flat structure in ASP.NET Core because it allows publishing of multiple apps with WebDeploy. cc/ @shirhatti

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS is there any action pending here?

**Comment by guardrex** [comment]
@mkArtakMSFT Because I ❤️ this concept so much, I'd like to make a final pitch for it:

If a flat publish directory structure option doesn't become an option, there's no opportunity to host a client-side Blazor (Razor Components) app on the Azure Storage CDN (at the root). `$root` doesn't permit slashes (pseudo folders), and current published output has plenty of folders (e.g., `_bin`, `wasm`, `_framework`).

This has perhaps been considered and rejected by management. I just wanted *one last shot* at suggesting it here because the client-side Blazor (Razor Components) app on the Azure CDN (**Look ma! ... _NO SERVER!_**) approach 🎷 *ROCKS!* 🎸 conceptually.

Thanks for hearing me out.

**Comment by SteveSandersonMS** [comment]
It's good feedback, but not something we have plans to handle currently. Realistic apps just aren't going to be a flat list of files, because the moment you bring in 3rd-party JS libraries or nontrivial amounts of static content, it's going to be in a directory hierarchy for certain, and that hierarchy must be reflected in the deployment otherwise it will fail at runtime. We can't somehow rewrite 3rd-party JS libraries to change their internal expectations about where content should be loaded from.

Since I don't see any way beyond this, and we have considered it at length, I'll mark it closed. But @guardrex / @mkArtakMSFT / @danroth27, if you think this needs further consideration or I've missed something, please reopen or let me know!

**Comment by guardrex** [comment]
> bring in 3rd-party JS libraries or nontrivial amounts of static content, it's going to be in a directory hierarchy for certain

Doesn't have to be that way tho in many cases. The obvious problem is file name conflicts. I don't understand how any other problems with 3rd party JS or static assets could be an issue.

> where content should be loaded from

I don't have your knowledge and experience with that, so I'll take your word for that. If you say that's a problem, I believe you.

Client-side Blazor (Razor Components) on Azure CDN (at the root) is a gorgeous hosting scenario. Hosting outside of `$root` is still an option. That's cool. I'll give that go. I think Option 1/2 :point_up: in the list should work.

Thanks for considering it. The alternative is that `$root` gains the same capability that Azure Storage containers have to contain `/` (forward slashes; pseudo paths). I may pitch an ask to the Azure folks for that.
