### ISSUE TITLE
For missing C# reference, it's going to a compiled code instead of original place.

### ISSUE THREAD

**Issue by ghost** [aspnet/AspNetCore#5494]
I create a basic application. remove the Forecast from C# code and Change it to Task class which I create myself.

Now I am compiling my code. Since WeatherForecast is not exist, Views is not compiling. The compiling error click in error window must be lead user to view. Currently it's leading to compiled .cs file which is a bit harsh if user have too much classes.

it can be improved. Like If things crash the YSOD show the exact code line with call stack and stack trace.
![11](https://user-images.githubusercontent.com/2105258/38166999-624a7c6c-354b-11e8-8815-d4487c444aa8.png)

**Comment by danroth27** [comment]
@rynowak This issue has been sitting around for a while, so I'm guessing it's not urgent. But if you think it needs to be investigated earlier please let us know!

**Comment by rynowak** [comment]
@ajaybhargavb - I suspect this will be fixed by https://github.com/aspnet/AspNetCore/issues/6373 so do that first. We're keeping this bug around so we can verify the case that was reported originally.
