### ISSUE TITLE
Wrap requestAnimationFrame as OnRender interface

### ISSUE THREAD

**Issue by Thaina** [aspnet/AspNetCore#5502]
I would like to propose interface or virtual function that wrap around `requestAnimationFrame` function

Because `requestAnimationFrame` should be called only once at a time and triggered only when any data was changed. So it would be great if the framework would wrap and manage this function instead of us using it directly

It could be that we would have interface contain `void OnRender()`. And whenever the data was changed it would trigger the `requestAnimationFrame` to call all `OnRender` in the list

If possible, I think every component should run on this render callback instead of the main thread

**Comment by rynowak** [comment]
This is not something we're planning to change in this release.
