### ISSUE TITLE
Support chained 'bind' on components

### ISSUE THREAD

**Issue by floreseken** [aspnet/AspNetCore#5504]
I must be doing something wrong.

Made this component:

```
<div>
    <input bind="@myValue" />
</div>

@functions
{
    public string myValue { get; set; }
    public Action<string> myValueChanged { get; set; }
}
```
And use this in a page like this:

```
<input bind="@Test" /><br />

<myInput bind-myValue="@Test"></myInput><br />

test: @Test

@functions {

    public string Test { get; set; }
}
````

Now I expect that typing in either input on this page would result in the same values in both inputs. But this seems to work only one-way: from the input to the control and not the other way around.

This is supposed to work right? What am I doing wrong?
 
# Note (from @SteveSandersonMS)

I expect fixing this will also fix #1490. Any proposed fix for this issue should also be checked to verify it accounts for the scenarios raised at #1490, and if it doesn't we'll reopen #1490 as a separate issue.

**Comment by sbuchok** [comment]
I created a fiddle that shows I believe the same issue:

https://blazorfiddle.com/s/861k07nk

If you change the value in the calendar, the value is updated in the component, but not in the parent.
If you then change the value in the textbox, the value for the calendar is changed to what was originally bound to it. 

I hope this helps.

**Comment by danroth27** [comment]
We expect to handle this as part of #6351
