### ISSUE TITLE
Can't change folder structure of Blazor (ASP.NET Cloud hosted) template

### ISSUE THREAD

**Issue by CraigSelbert** [aspnet/AspNetCore#5505]
I was playing around with the project structure and was seeing how far I could go before I broke it and that took no time at all.

So the default template produces a folder structure like 
```
WebApplication1
├── WebApplication.sln
├── WebApplication1
|   ├── WebApplication1.Client
|   ├── WebApplication1.Server
|   └── WebApplication1.Shared
```
I am trying to make the folder structure look like this
```
WebApplication1
├── WebApplication.sln
├── Client
├── Server
└── Shared
```
What I have ended up with is...
```
WebApplication1
├── WebApplication.sln
├── WebApplication.Client
├── Server
└── Shared
```
For some weird reason when I try to change `WebApplication.Client` to just `Client` the client stops compiling. 

I can commit my code to GitHub with the before and after if you would like. I am guessing this is breaking some convention that I am not aware of and would love to know what that is.

**Comment by rynowak** [comment]
In preview 4 we've made it possible for the compiler to use the `<BaseNamespace>` in the project for namespace of components. This should address this.
