### ISSUE TITLE
Events inside ChildContent are being dispatched to incorrect component

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#5507]
Repro:

```html
<NavLink href="/">
    <button onclick="@(_ => { Console.WriteLine("Hello"); })">Click me</button>
</NavLink>
```

Clicking the button fails with *The component of type Microsoft.AspNetCore.Blazor.Routing.NavLink cannot receive events because it does not implement Microsoft.AspNetCore.Blazor.Components.IHandleEvent.*.

The event should be dispatched to the owner component, not to the `NavLink`.

In most cases it's currently possible to work around this by calling `StateHasChanged` inside the event handler delegate, because any component that inherits `BlazorComponent` does implement `IHandleEvent` and handles events by invoking the supplied delegate. But that workaround doesn't work when the event-receiving component doesn't implement `IHandleEvent`, and in general it's still wrong because you shouldn't have to do this.

**Possible solution**

The intent is for events to be dispatched to the component whose code declares the event handler, not the component whose rendering logic added it to the RenderTree.

We could change the signature of `BindMethods.GetEventHandlerValue<T>(value)` to `BindMethods.GetEventHandlerValue<T>(IComponent target, value)` (for each of the `value` type overloads). Then we change the Razor compiler to supply the value `this` for `target`, hence we've captured a `target` value matching the component whose code contains the actual `onevent=...` syntax. In typical cases where the delegate represents an instance method, the lambda already captures `this` so this change wouldn't trigger any more allocations than we already do.

Then, the overloads of `GetEventHandlerValue` that return `MulticastDelegate` could be changed to return some new `struct`, `ComponentEventDelegate` that has two properties: `IComponent target` and `MulticastDelegate delegate`.

Then we'd change `RenderTreeBuilder`'s `AddAttribute` so that it has an explicit overload for `ComponentEventDelegate` instead of ones for `MulticastDelegate`. Inside that overload, we do the same logic that we used to for `MulticastDelegate`, but on the resulting `RenderTreeFrame`, we also store information about the target component. (To fit into the existing `RenderTreeFrame` memory layout, we might want to locate and store the target component's **id** here rather than a pointer to the actual instance, since pointers are 8-bytes, and we only have 4 bytes spare without expanding the size of a frame).

Then, we change the `AssignEventHandlerId` logic (and data storage) so that it stores the target component ID on the `_eventHandlersById` dictionary entry as well as the delegate itself.

Finally we can remove the whole notion of specifying a component ID during the event dispatching process. It will only be necessary to specify the `eventHandlerId`, and the `Renderer` code will be able to find the correct target component from that alone.

**Comment by manuelbl** [comment]
This is a serious bug and needs a proper fix. I've just wasted hours in a server-side Blazor project, mainly because I didn't get any error message anywhere, neither in the browser console nor on the server-side.

The problem occurred in an attempt to implement form validation and using *two-way data binding*. The form correctly fills the input field with the provided value, but changes are not written to the instance variable (see simplified code below).

Switching to `value="@FormValue" onchange="@((UIChangeEventArgs e) => FormValue = (string)e.Value)"` didn't help because the event handling is the root of the problem.

Form.cshtml:

    <ValidatedForm OnSubmit="@SubmitForm">
        <input bind="@FormValue" />
    </ValidatedForm>

    @functions {
        string FormValue = "Default Value";
    }

ValidatedForm.cshtml:

    <form onsubmit=@HandleSubmit>
        @ChildContent
    </form>

    @functions {
        [Parameter] protected Action OnSubmit { get; set; }

        void HandleSubmit() {
            ... validate and if successful submit ...
        }
    }

**Comment by SteveSandersonMS** [comment]
@rynowak Done, right?

**Comment by rynowak** [comment]
I plan to close this once I had to merge the compiler support and see tests passing in the runtime repo. As it stands *right now* this will be broken depending on what you put in the callback delegate.

**Comment by rynowak** [comment]
This is fixed by: https://github.com/aspnet/AspNetCore/issues/6351
