### ISSUE TITLE
Not able to use Layouts in nested sub-folders

### ISSUE THREAD

**Issue by Smilefounder** [aspnet/AspNetCore#5509]
Hi team,

I tried to use the layouts in nested "Shared" sub-folder but not able to use, the site will freeze once you access to the subpages. Please help advise.

![image](https://user-images.githubusercontent.com/3785721/39239777-26af1b80-48ac-11e8-96e5-3704ddbf0122.png)

Thanks.

**Comment by danroth27** [comment]
It looks like with the latest bits we override `@layout` correctly in *_Imports.razor*. Since this issue is pretty old and the repro is really outdated, I'm going to go ahead and close it. I hope that's ok!
