### ISSUE TITLE
Allow coder to specify BindingFlags in JsonUtil

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/AspNetCore#5511]
I want my state to be read-only, but I also need to be able to serialise/deserialise that state using JsonUtil. As they have private setters these properties are not being set.

Please could you add a BindingFlags parameter to the Deserialize() method which will allow me to tell it to set properties with private setters?

**Comment by rynowak** [comment]
We're not going to be adding features to JSONUtil. Our long term plan is to use the new `System.Text.Json` serializer that's being developed. Newtonsoft.JSON is also available as an option.
