### ISSUE TITLE
Invalid XHTML markup causes lockup

### ISSUE THREAD

**Issue by csnewman** [aspnet/AspNetCore#5518]
Invalid xhtml markup in the form of an unterminated tag causes the CPU to hit 100% and for the page to become completely unresponsive until chrome asks you if you wish to kill the page.

```
@page "/example"

<h5 class="card-title">(some text)</h5>
<p class="card-text">
    (Some text as well)
<p class="card-text">
   (Some other text)
</p>
```

As seen, the first p tag is not terminated.

**Comment by danroth27** [comment]
Tracking this with #6217
