### ISSUE TITLE
.cshtml does not accept 'string' for a 'object' type parameter

### ISSUE THREAD

**Issue by hungdluit** [aspnet/AspNetCore#5520]
I've created a button with

```
[Parameter]
public object Content {get;set;}

<XButton Content="Click Me !" Clicked="@MyHandler" ref="_button"></XButton>
```

Visual studio does not recognize 'Content' value, 

Error:

![image](https://user-images.githubusercontent.com/5623089/39875008-98d9ce6e-5499-11e8-8d70-a521ddbf7873.png)

**Comment by danroth27** [comment]
Tracking this with https://github.com/aspnet/AspNetCore/issues/8581
