### ISSUE TITLE
Namespaces dependent on solution folder name?

### ISSUE THREAD

**Issue by benhysell** [aspnet/AspNetCore#5524]
- Blazor 0.3.0
- VS 2017 15.7.1

Created a new solution via PowerShell:
```c:\projects\CoolNewProject\ dotnet new blazor```

Created a new project in c:\projects\CoolNewProject called CoolNewProject.

Normally I like to have my .sln file a directory above my projects, i.e.
```c:\projects\CoolNewProject\CoolNewProject.sln```

Then throw all of my src in 'src'.
```c:\projects\CoolNewProject\src\CoolNewProject.csproj``` and all of my other project files.

The second I move everything into the 'src' folder from my newly created Blazor project I can no longer compile:
```
Error | CS0246 | The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) | CoolNewProject | C:\projects\CoolNewProject\src\Program.cs | 17 | Active
```

Additionally, none of the Pages can find their namespaces either, i.e.
```
Error | CS0234 | The type or namespace name 'Shared' does not exist in the namespace 'CoolNewProject' (are you missing an assembly reference?) | CoolNewProject | C:\Projects\CoolNewProject\src\obj\Debug\netstandard2.0\Pages\Counter.g.i.cs | 21 | Active
```

**Comment by Sire** [comment]
This has caused a ton of confusion and seems highly illogical. Good that it's going to be fixed. Just curious how it could have happened?

**Comment by guardrex** [comment]
Just want to update (not surprised ... just say'in) that it's still happening (3.0 Preview 3 SDK and VS2019). I changed the solution folder name of the Blazor doc's sample app from `BlazorSample` to `Blazor` ... :boom: with the errors reported on this issue ... changing it back to `BlazorSample` and all is :+1: again.

**Comment by rynowak** [comment]
This was actually fixed in VS 16.1 preview 1 - will be released "soon"

**Comment by robertdunaway** [comment]
I've run into a related problem. I'm not trying to move projects around but I would like to use a different namespace.

When I change the namespace of a shared project class, the C# code and use it but razor pages cannot find it.

I want this because I'm sharing Entities between a blazor project and Angular and I don't want to have a shared project namespace of "bm2portal_blazor.Shared", which is the name of the project.  I want to namespace for my entities to be "Shared.Entities".

Will this be fixed in Blazor to work as it does in other C# code?

Thanks,
Bob

**Comment by rynowak** [comment]
Check if you have `@namespace bm2portal_blazor.Shared` somewhere.

The order that a namespace is resolved for generated code (in priority order):
- `@namespace` 
- `<RootNamespace?` in the project file
- Project name

You can use either of those things above the project name to configure this, but my guess is that you have an `@namespace` somewhere that's causing your issue.

I've also filed this issue to track updating the docs https://github.com/aspnet/AspNetCore.Docs/issues/14685
