### ISSUE TITLE
NavLink customizable tag

### ISSUE THREAD

**Issue by 0xDiddi** [aspnet/AspNetCore#5528]
The `<NavLink>` by default becomes an `<a>` tag. As I wanted to implement a standard bootstrap navbar, the `active` class needed to be on a `<li>` tag instead.

I therefore created a `TaggableNavLink` class that takes an additional parameter
```cs
[Parameter]
string Tag { get; set; }
```
to specify the tag, and used this in the `private void Render(...)` function, where I now write
```cs
builder.OpenElement(0, Tag);
```

instead of hard-coding
```cs
builder.OpenElement(0, "a");
```

I also included logic to parse the parameter and have `<a>` as the default tag.

As I stated, this is part of a small project I'm doing with blazor and as far as I can tell so far, it works without problems and shouldn't have any side effects.

---

Given that this was quite trivial to implement, there might has been a design choice made to hard-code this instead of exposing it as a parameter.

If it was just not considered as a requirement before, I'll happily submit my solution as a PR once I tested it a bit more thoroughly.

**Comment by javiercn** [comment]
We are closing this issue as we have determined that this functionality can be built on top of the framework and that we don't plan to add it to the core framework.
