### ISSUE TITLE
Exception in VS when renaming a Blazor component in a Blazor component library

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#5530]
I got an exception in VS when renaming a Blazor component in a Blazor component library.

https://github.com/danroth27/BlazorClipboard/commit/5c5a31716324fdf09f5af0afa35011e4130eedf3

![image](https://user-images.githubusercontent.com/1874516/40883477-f59ff526-66b2-11e8-8b3f-a456206e6d2c.png)

[ActivityLog.xml.txt](https://github.com/aspnet/Blazor/files/2065696/ActivityLog.xml.txt)

**Comment by mkArtakMSFT** [comment]
Given that only two people were able to run into this behavior during almost a year we're closing this. (we couldn't repro either)
