### ISSUE TITLE
Setting and clearing data for DragDrop operations

### ISSUE THREAD

**Issue by dlr1** [aspnet/AspNetCore#5532]
Can we get methods to SetData, ClearData on DataTransfer object for DragDrop?

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer
https://html.spec.whatwg.org/multipage/dnd.html#dom-datatransfer-setdata
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect
take a look at the example (scroll down)

**Comment by Lupusa87** [comment]
Please check this links to see how drag and drop works in blazor, including firefox.

https://github.com/Lupusa87/BlazorDragAndDrop

https://lupblazordraganddrop.z20.web.core.windows.net/

**Comment by oiBio** [comment]
Is this a bug on Firefox or Blazor/Razor-Components side? 
Do we have to use the JSInterop workaround or is it planned to be fixed?

**Comment by danroth27** [comment]
We don't have any plans to provide anything specific here. You should be able to enable drag & drop scenarios via jsinterop. Closing.
