### ISSUE TITLE
dotnet command with path parameter uses parent folder casing

### ISSUE THREAD

**Issue by Scepheo** [aspnet/AspNetCore#5534]
To reproduce (note the casing):

1. `dotnet new blazor -o Repro`
2. `dotnet build repro/Repro.csproj`

This fails with a whole bunch of errors about not being able to find the namespace `Repro.Shared`, because the build uses the path name specified in the dotnet build/run/publish command as the namespace name. This means that e.g. MainLayout.g.i.cs *defines* the namespace `repro.Shared`, but everything *uses* `Repro.Shared`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We think that this issue is fixed now. If you are still facing this problem, please file a new issue.
