### ISSUE TITLE
Right clicking local anchor tags automatically navigates you instead of displaying a context menu

### ISSUE THREAD

**Issue by Worble** [aspnet/AspNetCore#5536]
### Title
Right clicking local anchor tags automatically navigates you instead of displaying a context menu

### Functional impact
Users cannot use any of the context menu items when right clicking anchor tags

### Minimal repro steps
Given that you have 2 pages defined, say "/" and "/home", right clicking this `<a href="/home">Home<a/>` on the "/" page will cause you to instantly navigate to home instead of displaying the usual browser context menu.

### Expected result
Viewing of the browser context menu

### Actual result
The user is navigated to the anchor as if they left clicked it

### Further technical details
 This does not happen for links outside of the scope of the router, for example `<a href=www.google.com>Google</a>` or `<a href=/images/image.jpg>Image</a>`

**Comment by SteveSandersonMS** [comment]
This was fixed a while ago.
