### ISSUE TITLE
DateTimeOffset client side always show UTC Time

### ISSUE THREAD

**Issue by PicoDevices** [aspnet/AspNetCore#5537]
**var time = DateTimeOffset.Now;**
**time.ToLocalTime().ToString("yyy-MM-dd HH:mm:ss")}"
time.ToUniversalTime().ToString("yyy-MM-dd HH:mm:ss")}"**
Both cases show the same result: UTC time.

**Comment by mkArtakMSFT** [comment]
Closing as this is external, as @Andrzej-W has pointed out!
