### ISSUE TITLE
asm.js not served by default on IIS (no mime type for .mem files)

### ISSUE THREAD

**Issue by TheCamel** [aspnet/AspNetCore#5538]
Hi, 
with the solution i provide in #989 ;
- if i deploy under an application Default Web Site/Test 
             ==> url rewrite does not work for all links in the index.html - got five 404 (not found)
- if i deploy Under a new TEST web site (configured on the same folder)
             ==>404 on edge
             ==>work on chrome
see the screenshot
-left side : Edge and chrome on Default Web Site/Test are not working
-right side : Edge and chrome on /TEST
![blazor_deploy](https://user-images.githubusercontent.com/7381872/41402415-89195c1c-6fc2-11e8-8a0a-add803ad95df.png)

**Comment by SteveSandersonMS** [comment]
Closing because we're no longer supporting asm.js (because the execution speed was inadequate). People who need to support pre-WASM browsers will get better results with running the Blazor app server-side (e.g., using the server-side Blazor template).
