### ISSUE TITLE
State is not being updated on button click

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/AspNetCore#5540]
1: Download the source from this branch https://github.com/mrpmorris/blazor-fluxor/tree/bug/StateNotChanging

2: Set this project as your startup project MiddlwareSample.Server (in the 04-MiddlewareSample solution folder)

3: Run it

4: Now click either of the buttons. Both should update their own counter, but neither do. (If it works then refresh the page and try again to break it).

If you get rid of the `@inherits` line from `index.cshtml` then the counter example with in-view state works (the bottom button) but then the global-state change detection cannot work.

This worked in 0.30

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We think that this issue is fixed now. If you are still facing this problem, please file a new issue.
