### ISSUE TITLE
Cannot bind to nullable types (bool?, int?, etc)

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/AspNetCore#5541]
A lot of work has been done for the bind method, let's add the one for nullable bool. `bool?`

Current error:
Uncaught (in promise) Error: System.ArgumentException: 'bind' does not accept values of type System.Nullable`1[[System.Boolean, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]. To read and write this value type, wrap it in a property of type string with suitable getters and setters.

**Comment by s-haralampiev** [comment]
Hi, what is the state of this issue? Are nullable types supported already in some way? I cannot bind to a nullable type yet and I am receiving the same error as stated above.

**Comment by julienGrd** [comment]
Hi, same behavior here (to bind a datetime? to an input type=date) , there is a "clean" workaround ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We think that this issue is fixed now. If you are still facing this problem, please file a new issue.
