### ISSUE TITLE
CultureInfo didn't set appropriately

### ISSUE THREAD

**Issue by chenyj796** [aspnet/AspNetCore#5543]
In a Blazor cshtml, add "@CultureInfo.CurrentCulture.DisplayName", and then get "Invariant Language (Invariant Country)" while I expect "中文(简体，中国)". 
DateTime.Now is not correct also.

**Comment by alexDevBR** [comment]
Andrzej-W's solution worked for me, but instead of index.cshtml I put it in MainLayout.cshtml. That way even if user doesn't browse the main page it still works.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
