### ISSUE TITLE
Component tag helper matching should be case-sensitive

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/AspNetCore#5550]
Initially started in #1155, make it possible to only match Blazor components as named by the C# class.
The following 2 snippets are not equal: 
```csharp
<Form>
...
</Form>
```
is not equal to (mind the casing)
```html
<form>
...
</form>
```

We could make it easier for component libraries as BlazorStrap for example, which has a [workaround](https://github.com/chanan/BlazorStrap/blob/d771191f7572aae1aba540c8f87fe81695a621d5/src/Sample/Pages/forms.cshtml#L9). Basically this is also what React does.

I'm not really sure if this is Blazor or Razor specific, so if I'm mistaken I do apologise.

**Comment by mkArtakMSFT** [comment]
@rynowak, @danroth bringing this back to preview4 to handle the case-sensitive components completion.

**Comment by ajaybhargavb** [comment]
Looks like this work will require VS changes. We don't have any planned insertions to VS preview1. Shouldn't this be post preview4 then?

**Comment by rynowak** [comment]
Let's get it done when we can. If it doesn't ship right away that's ok.

**Comment by ajaybhargavb** [comment]
Spoke offline. Moving to preview6.

**Comment by vertonghenb** [comment]
Agreed that it's not a first priority but keep in mind that component library creators will love this idea.

**Comment by rynowak** [comment]
Thanks for the feedback. We're using https://github.com/aspnet/AspNetCore/issues/9860 to track this.
