### ISSUE TITLE
[Server side] Exceptions thrown inside of a component are silently ignored

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#5552]
I updated `FetchData.OnInitAsync` to throw an exception:

```C#

@functions {
    WeatherForecast[] forecasts;

    protected override async Task OnInitAsync()
    {
        if (forecasts == null)
        {
            throw new ArgumentException();
        }

        forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
    }
}
```

I can debug the component and see the exception, but the exception is not logged to the server debug logs or visible in the console

**Comment by gulbanana** [comment]
how about react-style error boundary components?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We think that this issue is fixed now. If you are still facing this problem, please file a new issue.
