### ISSUE TITLE
404 on PDBs

### ISSUE THREAD

**Issue by galvesribeiro** [aspnet/AspNetCore#5555]
Hey folks!

After the update to 0.5.0 on BlazorExtensions components, I'm starting to see weird errors on the console pointing that some .pdb files are missing:

![image](https://user-images.githubusercontent.com/4714040/43269101-87d0b90a-90c8-11e8-8e22-4eec758112de.png)

For the record, I'm not even trying to debug. Just running the [BlazorExtensions.Logger test project](https://github.com/BlazorExtensions/Logging/tree/master/test/Blazor.Extensions.Logging.Test) 

Can someone shed a light on that?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We think that this issue is fixed now. If you are still facing this problem, please file a new issue.
