### ISSUE TITLE
Blazor Server and Client side and Javascript

### ISSUE THREAD

**Issue by uazo** [aspnet/AspNetCore#5556]
Blazor Server and Client side, yes, and now?

### PRO CLIENT SIDE

- Speed? **N/A** (firefox is ok, chrome no)
mono interpret is slow, and there are no forecasts about compiling with AOT or directly in WASM

- Quick startup? **No**

- Remove JS? **No**
WASM does not have access to the DOM yet, so JS is always in the way

- Does it work anywhere? **No**
Only latest browsers and devices

### PRO SERVER SIDE

- Speed? **Yup**
The same project in Server Mode is a splinter

- Quick startup? **Yup**
Download only static elements.

- Remove JS? **No**
JS is always there. And accessing the DOM remotely (when it will be implemented) will give performance problems certainty.

- Does it work anywhere? **Yup**
Eureka!

in the medium term, therefore, for the Blazor development of enterprise applications, the Server Mode is definitely to be preferred, at least until WASM will have access to the DOM (without js) and Mono will permit it, and always that the compiler in the meantime will have WASM targets (because current performance is really low when compared to javascript).

But the biggest problem with Server Mode is to interact with the DOM to create the interfaces, which is essential. Developing a new UI library with Blazor without javascript really means starting all over again (unless there are tools from ts to c #, do they exist?).

Currently with Blazor it is not possible to reuse ready-made UI libraries, developed in javascript, except for very complicated DOTNET-JS calls (just thinking about it I get a headache).

What is missing is the ability to abstract the js portion of blazor making it extensible using typescript, to allow a dotnet side component (local or remote) to have associated a custom component in the javascript side.

At this address https://uazo.github.io/BlazorFX/StandaloneApp/ an application test that uses DevExpress components for rendering: the blazor side components are dotnet (without any reference to interop with js), while rendering is done from javascript elements (DevExtreme from the react version). The dotnet component and the javascript component talks through exchange of custom properties and events (like react). In effect, the glue is a middleware beetween blazor and react, simple to do because DevExtreme is not a native react library but the implementation is simple.

So what do you say? Have you ever thought about it? It could also be a temporary solution, which would not deny in future having even full dotnet components (as today for react, not all components are full react made)

For those who want the repo is available with all the changes to the base code of blazor (https://github.com/uazo/Blazor/tree/remove-custom-tag).

**Comment by SteveSandersonMS** [comment]
Since this is a discussion rather than an bug report or proposed enhancement, and the discussion stopped months ago, I'll mark it closed now to keep things tidy.
