### ISSUE TITLE
Chrome debug proxy apparently _requires_ to load debug symbols for all referenced assemblies

### ISSUE THREAD

**Issue by chucker** [aspnet/AspNetCore#5559]
(See also #1199?)

Debugging a Blazor project in Chrome as described in the 0.5 release notes fails as soon as a DLL is referenced for which debug symbols don't exist. (In my case, I had BlazorExtensions.Logging referenced.)

Mono/Cecil reports an error of:

```
got exception System.AggregateException: One or more errors occurred. (Format of the executable (.exe) or library (.dll) is invalid.) ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
```

And Chrome's debug session closes immediately, with:

>Debugging connection was closed. reason: WebSocket disconnected

Blazor should probably skip trying to debug assemblies for which debug symbols cannot be loaded.

This is distinct from #1199 in that @galvesribeiro hadn't actually even _tried_ to debug code (but I did), in which case loading debug symbols probably shouldn't happen at all.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not an area we control.
If you still have this problem, feel free to report it on the https://github.com/mono/mono repo.
