### ISSUE TITLE
JSInterop cannot invoke instance methods

### ISSUE THREAD

**Issue by Suchiman** [aspnet/AspNetCore#5563]
Right now if you try to invoke an instance method, like `localStorage.setItem`, then you'll receive an rather obscure error like `'setItem' called on an object that does not implement interface Storage.` which means that this line https://github.com/aspnet/Blazor/blob/f2232e0699dae28485e07244403385219c1a3832/src/Microsoft.JSInterop/JavaScriptRuntime/src/Microsoft.JSInterop.ts#L160
uses apply to invoke the method on a null reference which isn't supported.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Suchiman.
We're closing this issue as this is now supported. If you still face this problem, feel free to open a new issue.

**Comment by Suchiman** [comment]
@mkArtakMSFT this is not fixed, and the offending code that now lives here https://github.com/aspnet/Extensions/blob/bbe51d0fda2649105515b9fa450aca4948bcf9c9/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L160 is completely unchanged.

**Comment by Suchiman** [comment]
I've opened https://github.com/aspnet/Extensions/issues/1477 to track it in the repo the code now lives in.
