### ISSUE TITLE
Fatal error in IL Linker

### ISSUE THREAD

**Issue by ETsukarev** [aspnet/AspNetCore#5565]
I builded solution, which created from Blazor (Server side in ASP.NET Core) template. Build solution was over by "Fatal error in IL Linker".

Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.identitymodel.protocols.openidconnect\5.2.0\lib\netstandard1.4\Microsoft.IdentityModel.Protocols.OpenIdCnnect.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.identitymodel.protocols.openidconnect\5.2.0\lib\netstandard1.4\Microsoft.IdentityModel.Protocols.OpenIdCnnect.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

my system:
dotnet -- version: 2.1.302
Windows 10 Pro Build 1803 17134.167
VS 2017 Community 15.7.5
Blazor: 0.5.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not an area we control.
If you still have this problem, feel free to report it on the https://github.com/mono/mono repo.
