### ISSUE TITLE
favicon.ico gets reloaded every time tab is changed in server side rendering template

### ISSUE THREAD

**Issue by wanton7** [aspnet/AspNetCore#5567]
I'm using Blazor 0.5.1 and Chrome browser. If I click between Home, Counter and Fetch Data tabs favicon.ico gets reloaded everytime tab is changed.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @wanton7.
We're closing this issue as this is not a priority for us.

**Comment by RomanHubyak** [comment]
The issue is even if you click the same tab e.g. "Counter". On every single click the favicon request is sent.

**Comment by RomanHubyak** [comment]
![image](https://user-images.githubusercontent.com/46841287/58727474-21db0380-83ed-11e9-87bd-70ee558c79da.png)
What is really weird that request returns index.html.

**Comment by RomanHubyak** [comment]
The issue is resolved by putting icon in the wwwroot directory.
