### ISSUE TITLE
Bootstrap intellisense not working in Blazor projects in Visual Studio

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#5568]
Bootstrap intellisense isn't showing up in Blazor projects: 

![image](https://user-images.githubusercontent.com/1874516/43605526-78b1338e-964d-11e8-8e01-7ad4804a954c.png)

Visual Studio provides intellisense based on the CSS files in the project, but it only looks at the unminified versions.

**Comment by mkArtakMSFT** [comment]
Closing as this is external.
