### ISSUE TITLE
Trying to make editable text field - keeps disappearing.

### ISSUE THREAD

**Issue by mandalorianbob** [aspnet/AspNetCore#5570]
I created a small "editable field" where if you click on the text, it'll change to a text box which you can then modify.
However, I'm seeing some really strange behavior from hitting "Escape": If I click on the text, and edit the text, and hit "Enter" everything's fine. If I hit "Escape" it appears to delete the last element.
So if I click on the Text, type something and hit "Escape" it deletes div "savedValue". If I do it again, it deletes span "textField".
My intention was obviously to change "Text" back to "_savedValue" if they hit escape. And it seems like it might work, but it keeps deleting the elements.
Any other warnings, caveats, or better ways to do what I'm trying to do appreciated.
Thanks
```
<div>
    @if (_editing)
    {
        <input id="textField" bind="Text" onkeyup="@OnKeyUp" />
    } 
    else
    {
        <span id="textField" onclick="@OnTextClicked">@Text</span>
    }
    <div id="savedValue">@_savedValue</div>
</div>
@functions{
    [Parameter]
    string Text { get; set; }

    [Parameter]
    private Action<string> TextChanged { get; set; }

    bool _editing = false;

    string _savedValue;

    void OnTextClicked()
    {
        _editing = true;
        _savedValue = Text;
    }

    void OnKeyUp(UIKeyboardEventArgs eventArgs)
    {
        if (eventArgs.Key == "Enter" || eventArgs.Key == "Escape") //This causes the issue
        {
            _editing = false;
        }
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mandalorianbob.
We're closing this issue as it is not clear whether there is anything pending here. If there is, please file a new issue.
