### ISSUE TITLE
Move x-plat testing into VSTS

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#5571]
AppVeyor and Travis are still required to provide full test coverage. To make VSTS provide the same level of coverage, we need to

* Enable selenium-standalone on VSTS
* Add macOS and Linux build phases
* Ensure tests run with `/p:BlazorAllTests=true` (or just make this default)

**Comment by SteveSandersonMS** [comment]
Closing as duplicate of #5457
