### ISSUE TITLE
Nested div onclick event

### ISSUE THREAD

**Issue by pavel-purma** [aspnet/AspNetCore#5573]
I have a overlay background element and dialog inside. The problem is that onclick event of overlay div is fired event if that div is under dialog. That cause me closing the dialog. Then I tried to solve that by addEventListener via JSInterop and use e.stopPropagation() but it fail another way. It stop all blazor onclick events inside of popup dialog. Blazor use document as the only point to attach event listeners. Should I use other way to stop propagation in blazor ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pavel-purma.
We're planning to provide a mechanism to block event propagation and track it as part of #5545.
