### ISSUE TITLE
What can cause Navigation to completely stop working?

### ISSUE THREAD

**Issue by masonwheeler** [aspnet/AspNetCore#5574]
I have a very strange situation in my Blazor app.  Everything was working fine until I updated to 0.5.  Now navigation is broken... mostly.

I can load up the SPA, and whatever page the URL is pointing to comes up as expected.  But if I try to click any link, the URL in the browser's address bar changes, but no content takes place.  The `OnInit` for the target page never gets called (verified by putting a `Console.WriteLine` in the `OnInit`) and neither does the `IUriHelper.OnLocationChanged` event.

However, I have a few pages that perform validation in their `OnInit`, and navigate you to `/` if you're not a valid user.  When I enter one of these pages in the address bar, I end up getting redirected to the SPA's homepage as expected, which means that as of `OnInit` time, navigation is working, but at some later point it's breaking.

No errors are getting logged to the console when I click a link.

I've ruled out that it's any of my external JS scripts by disabling them. The problem still occurs.

It appears that the relevant code that performs the navigation is in [UriHelper.ts](https://github.com/aspnet/Blazor/blob/master/src/Microsoft.AspNetCore.Blazor.Browser.JS/src/Services/UriHelper.ts), but I can't find any of that code in `blazor.webassembly.js`, or anywhere in the `dist\_framework` subtree for that matter, to attempt to debug it.  So at this point I'm completely at a loss for what to do next.

Something is disabling navigation, and doing so in such a way that no errors get displayed on the console.  I don't know what or why.  How do I track it down?

**Comment by SteveSandersonMS** [comment]
With the update startup model, this should no longer be applicable so I'll mark it closed.
