### ISSUE TITLE
Notification about UI state change for long running tasks

### ISSUE THREAD

**Issue by kant2002** [aspnet/AspNetCore#5576]
I play with simple NLP application inside browser.
 I want to add loading indicator. Right now I use following approach

```
this.loading = true;
this.StateHasChanged();
try {
    this.result = await httpClient.GetJsonAsync<SearchResult[]>($"api/search/sentence?content={content}");
} finally {
     this.loading = false;
}
```

Main trick is using `StateHasChanged`. My question is: Is this correct way to do that? How Blazor in general think such cases should be handled. I'm fine with calling `StateHasChanged()` but I prefer that it would be called automatically before `await`. 

## Example 1
```
this.loading = true;
try {
    // this.StateHasChanged(); called here by runtime
    this.result = await httpClient.GetJsonAsync<SearchResult[]>($"api/search/sentence?content={content}");
} finally {
     this.loading = false;
}
```

## Example 2
or better, if I could control that using for example `.ConfigureAwait(false)`

```
this.loading = true;
try {
    // this.StateHasChanged(); called here by runtime
    this.result = await httpClient.GetJsonAsync<SearchResult[]>($"api/search/sentence?content={content}")
             .ConfigureAwait(false);
} finally {
     this.loading = false;
}
```

**Comment by SteveSandersonMS** [comment]
As far as I can see, this is working as expected. You do need to call `StateHasChanged` after each `await` (except for the last one), because Blazor has no way to know about your "awaits" except for your last one.
