### ISSUE TITLE
Adding / Removing element via cshtml prevents click event from firing

### ISSUE THREAD

**Issue by strangesquark** [aspnet/AspNetCore#5581]
If you have an if statement that updates a variable that is used to determine if an element should be rendered or not, and you update this variable in an onblur handler then the onclick handler of a button will not fire if the focus is on the element that has the onblur handler when you click the button.

For example, if you create a new Blazor project and put the code in the attached file in the Counter.cshtml file you can see the issue. Just click in the input, then click the submit button. The onblur event of the input fires, but the onclick event of the button does not.

If you remove the lines that render / prevents rendering (called out in the attached file) from the code, then both events fire as expected:

[CodeToReplicateEventIssue.txt](https://github.com/aspnet/Blazor/files/2311808/CodeToReplicateEventIssue.txt)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @strangesquark.
What is the actual scenario you're trying to solve this for? There may be a better way to achieve what you want.

@SteveSandersonMS, do you have any thoughts here?

**Comment by strangesquark** [comment]
I was doing validation onblur, and then when the button was clicked doing some tasks to prepare data and then sending a Post or Put request. If a user has focus in the input (if they just fixed a validation error for example) and then clicks the submit button, the validation error clears, but the submit does not occur.
