### ISSUE TITLE
Annoying wwwroot folder behavior - no failback mechanism for lack of an accessible index.html file.

### ISSUE THREAD

**Issue by andras-ferencz** [aspnet/AspNetCore#5587]
If your visual studio lags out and in the process you [whack your keyboard](https://dqbasmyouzti2.cloudfront.net/assets/content/cache/made/content/images/articles/BrokenComputer_XL_721_420_80_s_c1.jpg) and it somehow hits the right combination of hotkeys to move the wwwroot folder to, say, Pages or Shared, you're going to have a really bad time with this wonderful error: 

> The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

I understand that managing to achieve this error is the equivalent of winning the [GRAND PRIZE](https://en.wikipedia.org/wiki/Golden_Raspberry_Awards), but hear me out here.

As you frantically search the internet for why your latest deployment destroyed everything for no reason whatsoever, you'll bet met with zero indication that, perhaps, just perhaps, a goddamned little gremlin from Redmond, WA moved your wwwroot folder underneath another folder.

VisualStudio should definitely not let you accidentally move or drag the wwwroot (or any other folder that gets a specialized, unique icon - seriously, how tf has this not been implemented by 2018?); but Blazor itself, should have a failback mechanism for when it gets served without an accessible index.html page; even a single string of text that says "hey i, the magnificent blazor, couldn't find wwwroot". 

🐊

**Comment by SteveSandersonMS** [comment]
I'll close this as it's not something we plan to do specific work for. It's a report about a VS behavior that Blazor doesn't control, and nobody else has yet reported it as an issue, so this would be such a low priority item that realistically there's always going to be other things we need to prioritise above it. Hope that's OK.
