### ISSUE TITLE
Component not rendering after StateHasChanged call

### ISSUE THREAD

**Issue by arkadiuszwojcik** [aspnet/AspNetCore#5588]
I have created simple `NavElement` component that changes a bit standard `NavLink` behaviour. According to log all logic works but somehow component is not re-rendered after `StateHasChanged` call. Relevant code looks like this:

        private void OnLocationChanged(object sender, string newUriAbsolute)
        {
            Console.WriteLine("OnLocationChanged");

            var shouldBeActiveNow = ShouldMatch(newUriAbsolute);

            if (shouldBeActiveNow != IsActive)
            {
                IsActive = shouldBeActiveNow;
                Console.WriteLine("Calling StateHasChanged");
                StateHasChanged();
            }
        }

        protected override bool ShouldRender() => true;

        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            Console.WriteLine("BuildRenderTree");

            builder.OpenElement(0, "li");

            // Set class attribute
            builder.AddAttribute(0, "class", CombineWithSpace(Class, IsActive ? ActiveClass : null));

            builder.AddContent(1, ChildContent);

            builder.CloseElement();
        }

Component renders initialy. Later on when I click on some link logic works like expected and I get `Calling StateHasChanged` in browser console for two nav elements (old active and new active). But after that I can't see in logs `BuildRenderTree`. But when I refresh web page changes are applied.

**Comment by seriouz** [comment]
[Comment from Kaffeegangster](https://github.com/aspnet/AspNetCore/issues/5588#issuecomment-422927824) worked!

**Comment by arivoir** [comment]
> I think in  protected override void BuildRenderTree(RenderTreeBuilder builder) {..} you need to call base.BuildRenderTree(builder) first

I think forcing to call the base is a bad idea, because the component lifecycle can be broken, as demonstrated here, and it doesn't allow to redefine the returned render tree in a sub-class component.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @arkadiuszwojcik.
As there have been many changes in this area since you've filed this issue, we're closing this. If you happen to face this issue with the most recent Blazor release please file a new issue.
