### ISSUE TITLE
Please add Blazor sample with ML.NET

### ISSUE THREAD

**Issue by tauheedul** [aspnet/AspNetCore#5593]
Blazor allows us to use .NET Core features. Now that the .NET Core supports machine learning, it would be very helpful to learn how we can use ML.NET features with Blazor on the client side.

If this works, we could perform machine learning on the client side or server side using our web apps.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
