### ISSUE TITLE
Add Blazor templates for ASP.NET Core 2.2

### ISSUE THREAD

**Issue by JohnyL** [aspnet/AspNetCore#5596]
Visual Studio doesn't show "Blazor" project template:

![IMG1](https://jy6aig.am.files.1drv.com/y4mauLwTx069pbd96LhWvNZx5BPsgsnmIdSAlWlzLbNhPHf2iI3eNqBe_0_vvl5Px4w7YynXwGSQ4eQtsYVPMuabrqf816F1kQiewqcDOiT5FIPT8M0VhGbdkLf30ZMqCfCpW3BZ2tGOqTlJ9F-Wnt4SmRxHiH82YcE7uUcUg1nRXmPmIlEoqIIEOeYDEcr_Xq7LjFgVIFaSXq5xrW3l2WGIA?width=786&height=553&cropmode=none)

Blazor Language Services extension is installed:

![IMG2](https://jy41lw.am.files.1drv.com/y4m7S5LiH6O4ORVvwP67fxjaMpHLPUXjeh8oRIGzEWFkZE4yeLrh9qq-yLQlrNDkTAkrzZC7TE-HuIsZu7nUMAGi4EiRQBvcJF_0efDpcePYwiFKR8rILP2EJs06QiVgbycHx9uiNbjZH7JEesLwHi8drGbyEBNw9CPkEck5RGclG_jINk-PD4ZKHdTAog1gPPi-fJkRmmMVnjzOoa-jmxE9w?width=941&height=653&cropmode=none)

**Configuration**:
- VS 2017 15.9.0 Preview 2
- .NET Core 2.2.100-preview2-009404
- SDK: 2.2.100-preview2-009404
- OS: Windows 10 Home x64

**Comment by loganathanav** [comment]
Is Blazor support .Net Core 2.2?

**Comment by SteveSandersonMS** [comment]
In Blazor 0.8.0, we have added .NET Core 3.0 support. As such, we're skipping 2.2.
