### ISSUE TITLE
Intellisense or language service error

### ISSUE THREAD

**Issue by kant2002** [aspnet/AspNetCore#5597]
1. have `<td></td>`
2. Put caret between `<td>|</td>`
3. Press Enter
4. Type `@if (` fast. After typing `(` the additional `if` appears.

![image](https://user-images.githubusercontent.com/4257079/45607604-5c735a80-ba6f-11e8-9e8e-81bb72d43589.png)

**Comment by rynowak** [comment]
I cannot reproduce this in VS 16.0
