### ISSUE TITLE
Wrong data type in UIKeyboardEventArgs.Location declaration

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#5601]
`UIKeyboardEventArgs.Location` is currently declared as `float` but according to this info:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/location
it can contain only one of a few unsigned integer values. I think this property should be `enum`.

**Comment by SteveSandersonMS** [comment]
This was fixed in a merge a few days ago.
