### ISSUE TITLE
Cannot resolve @typeparam

### ISSUE THREAD

**Issue by kakins** [aspnet/AspNetCore#5608]
I have Blazor 0.6.0 installed, using the VS template.  .NET Core SDK 2.1.402.  I see this, both with ReSharper enabled and disabled.  

The app appears to still compile and run correctly, so perhaps this is an issue with Visual Studio?  I have VS 2017 15.8.6.

![image](https://user-images.githubusercontent.com/14915247/46832614-1fe40780-cd6c-11e8-9cc5-c7ee4a70d848.png)

**Comment by kakins** [comment]
Sorry I haven't responded in some time.  I haven't had time to play around with Blazor much.  I'm still experiencing this issue, but I have not uninstalled ReSharper yet.  I'm pretty sure I've updated it though, since having this problem.

I also haven't tried uninstalling/reinstalling Blazor Language Services.  I suppose I can try this as a last resort.

**Comment by nolisj** [comment]
@kakins , that's interesting. It seems then that Resharper is causing this issue in our cases.

**Comment by limefrogyank** [comment]
Just for the other dummies that are search for this issue, you can also get this to happen when your "Build Action" is set to None rather than Content.  doh!
