### ISSUE TITLE
Use Server-side Blazor, but be able to offload some work to the client, using Client-side Blazor too.

### ISSUE THREAD

**Issue by lalibi** [aspnet/AspNetCore#5615]
Is it a scenario that:

1. is possible at the moment?
1. you think has any merit?
1. you have given any thought to or plan to implement?

I'd like to build a Pokah site ("Pokah" is a Greek variation of Poker) using the Server-side flavor of Blazor. At some point, I'd like to give the users the ability to see an estimate of their chance to win the round (Monte Carlo algorithm), based on their cards and the community ones.

Since this can be taxing for the server, I was thinking that if a user wants to know their odds to win, let their browser calculate that.

I hope the scenario makes sense, I guess using Client-side Blazor+WebAPI is one way to go, but I really like to go the Server-side route.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lalibi.
This is not something we plan to provide support for out of the box.
