### ISSUE TITLE
"Unknown edit type: 0" when calling StateHasChanged

### ISSUE THREAD

**Issue by kswoll** [aspnet/AspNetCore#5618]
When calling `StateHasChanged` in response to a component's callback event, I get the above error in Chrome's Javascript console.  On version 0.6 of Blazor.  

The repro steps are pretty straightforward.  This is a contrived minimal example, but the idea is to respond to `CTRL-Enter` in a textbox (to save the changes, for example). First create a component named `TestComponent.cshtml`:

```
<input type="text" bind="@Text" onkeydown="@OnKeyDown" />

@functions {
    private string text;

    [Parameter]
    private string Text
    {
        get => text;
        set
        {
            text = value;
            TextChanged?.Invoke(text);
        }
    }

    [Parameter]
    private Action<string> TextChanged { get; set; }

    [Parameter]
    private Action Committed { get; set; }

    private void OnKeyDown(UIKeyboardEventArgs e)
    {
        if (e.Key == "Enter" && e.CtrlKey)
        {
            Committed?.Invoke();
        }
    }
}
```

Then use this component in a different file:

```
@if (flag)
{
    <TestComponent bind-Text="@text" Committed="@OnCommitted" />
}
else
{
    @text
}

@functions {
    private bool flag = true;
    private string text;

    private void OnCommitted()
    {
        flag = false;
        StateHasChanged();
    }
}
```

Now type at least one character in the textbox, then hit `CTRL-Enter`.  The view doesn't re-render (i'd expect the textbox to go away and be replaced with the value of `text`) and I see the following errors in the console:

```
blazor.webassembly.js:1 Uncaught (in promise) Error: Microsoft.JSInterop.JSException: Unknown edit type: 0
Error: Unknown edit type: 0
    at e.applyEdits (blazor.webassembly.js:1)
    at e.updateComponent (blazor.webassembly.js:1)
    ...
```

and

```
blazor.webassembly.js:1 Uncaught (in promise) Error: Microsoft.JSInterop.JSException: Cannot read property 'parentNode' of undefined
TypeError: Cannot read property 'parentNode' of undefined
    at Object.e [as removeLogicalChild] (blazor.webassembly.js:1)
    at e.applyEdits (blazor.webassembly.js:1)
   ...
```

**Comment by SteveSandersonMS** [comment]
This no longer repros with current builds. I tried running this code both server-side and client-side, and it now works as expected. So, AFAIK if you update your app to Blazor 0.9.0 or later, you should be OK.
