### ISSUE TITLE
Make it easier to enable client-side SignalR logging when using server-side Blazor

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#5624]
We should provide a simple way to [enable client-side SignalR logging](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#javascript-client-logging) when using server-side Blazor.

**Comment by sven5** [comment]
@danroth27 
Looking forward for this feature. In the meantime, is there any way I can manually enable client-side logging?

Thanks
Sven

**Comment by danroth27** [comment]
@sven5 There are a few [community projects](https://blazor.net/community) out there that you can take a look at:
- https://github.com/BlazorExtensions/Logging
- https://github.com/elmahio/Elmah.Io.Blazor
