### ISSUE TITLE
Suggestion: 401 Redirect Helper

### ISSUE THREAD

**Issue by philipri** [aspnet/AspNetCore#5626]
With the way the HttpClient is working on client side Blazor it's actually super hard to intecept the HTTP errors (even with try/catch).

It would be great on the HttpClient DI Singleton if we could specify a route associated with common HTTP codes that it returns.

e.g. on a 401 it might redirect to a login route or token refresh route etc.
eg. on a 500 it might show an error page etc.

These might be specified in the Startup (i.e. when the dependency is injected).

As a temp workaround I might try wrapping the current singleton - but it seems to be acting strangely (more debugging required by me).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @philipri.
This is not something we plan to do in the near future.
