### ISSUE TITLE
Make SignalR Service usage an aspect of deployment, not source code

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#5629]
For Razor Components (currently, server-side Blazor), the decision to use Azure SignalR Service or not shouldn't be hardcoded into the app code. Ideally it would be something determined by the deployment mechanism.

Somehow we need sufficient abstraction to remove this from the project source code. The tricky bit is that we don't want to bring in a dependency on `Microsoft.Azure.SignalR` for all projects, so I'm not sure how we solve this.

I seem to recall that @DamianEdwards mentioned this is just a one example of a broader class of requirements to make service usage determined by the deployment/hosting mechanism. So perhaps this is not something we need to solve in this repo, because we're going to inherit a broader solution that applies to all services. CC @davidfowl.

**Comment by rynowak** [comment]
@davidfowl - I know you're working on this - is there another item that tracks this?
