### ISSUE TITLE
after intensive use, requests take very long time to execute

### ISSUE THREAD

**Issue by omuleanu** [aspnet/AspNetCore#5630]
My application has many pages which can do many ajax requests, after a while of going from page to page (or just spam click my home link) the requests start to take a very long time 30s ~ 45s, all requests not just ajax,
I see the requests as pending in chrome network tab 
(it can be just 1 request, it's not the browser limit, also I try FF after hit the slow moment and same problem)
I tried to put breakpoints on the controller actions that are pending and breakpoints get hit at the end, so the request is pending a long time without touching the action. 
I've removed everything in Startup.cs to have just the bare minimum.

sometimes I need to iisreset to get it back working normally

I have the same app in mvc5 and it doesn't have this problem (core version converted from mvc5 using a custom console app I wrote (not generic) )

the project uses:
AspNetCore 2.1.4
AspNetCore.Mvc 2.1.3

are there any known issues/bugs regarding this  ?

 UPDATE: after installing .net core SDK 2.2 (https://blogs.msdn.microsoft.com/webdev/2018/12/04/asp-net-core-2-2-available-today/)
I can't reproduce the problem anymore, I haven't even updated the nuget packages.

UPDATE2: 
using now SDK 2.2 and latest packages (aspnetcore, aspnetcore.mvc),
getting the problem again requests pending, taking long time, even if open another browser the page will take forever to load, have to `iisreset` to get it back working

**Comment by Eilon** [comment]
@sebastienros - do you have info on how to try diagnosing this issue?

**Comment by omuleanu** [comment]
I've created a new asp.net core solution and copied from it the code from startup.cs, program.cs and the the csproj file (removed unnecessary lines )
after removing my bin obj folders, and cleanup, I don't have the problem anymore,

before this I was actually trying to isolate the problem and I got to the point that I had an empty page just saying hi, I was holding f5 with chrome console open and after about 5 seconds the request was pending (in network console tab)

**Comment by mkArtakMSFT** [comment]
Glad you've got this resolved, @omuleanu.
