### ISSUE TITLE
Reaction to React Hooks?

### ISSUE THREAD

**Issue by scottsauber** [aspnet/AspNetCore#5635]
Just wanted to open a discussion about the new React Hooks which was announced at ReactConf.  I reach for React when I do a SPA currently (although we have a non-critical IT only app we built in Blazor as well), and React Hooks have me pretty excited, because it groups similar logic together much like Feature Folders do for a folder structure.

**Wrapper Hell**

[One of the things they discussed](https://youtu.be/dpw9EHDh2bM?t=448) that React Hooks is solving is "Wrapper Hell" where you have tons of components nested beneath each other.  [Specifically they call out Context](https://youtu.be/dpw9EHDh2bM?t=1905), which is very close to how Cascading parameters work in Blazor with the `<CascadingValue>` wrapper component.

Curious what the Blazor team thinks about this and if there are any thoughts around perhaps doing something similar to what the React team is moving to with Hooks and getting rid of the need for the wrapper component.

My quick thoughts would be something like making global state injectable instead of using a wrapped component... or having access to some grab bag off of the BlazorComponent base class where you could do something like `.Get<T>` and have it magically grab your value for you.  Those are my crappy 1 minute ideas, but feels like Blazor could do something similar to remove the need for the wrapper component and keep the component trees less nested and easier to follow.

**React is getting rid of lifecycle methods**

[React is also moving away from lifecycle methods](https://youtu.be/dpw9EHDh2bM?t=480) like componentDidMount (OnInit/OnInitAsync in Blazor).  They're mostly doing this so that setup (addEventListener) and cleanup (removeEventListener) is wired up in the same spot instead of separate lifecycle methods which led to bugs when you forgot to cleanup for instance.  Curious to hear other's thoughts on this and how it would apply to Blazor.  I personally haven't done any cleanup of my Blazor components, but maybe I'm causing a memory leak I don't know about.

Obviously it's very early days in React Hooks land, but the concepts behind them makes a lot of sense. 
 Just wanted to generate some discussion.  Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @scottsauber.
We have no plans to do this in the near future.
