### ISSUE TITLE
Generic type bindings

### ISSUE THREAD

**Issue by romanoza** [aspnet/AspNetCore#5636]
I have the following component (myInput.cshtml):

```
@typeparam TProperty

<div>
    <input bind="@myValue" />
</div>

@functions
{
[Parameter]
private TProperty myValue { get; set; }

[Parameter]
private Action<TProperty> myValueChanged { get; set; }
}
```

and I'm trying to use it that way:

`<myInput bind-myValue="@Test"></myInput>`

where Test is defined as

`public string Test { get; set; }`

It results with the following error message:

> 'bind' does not accept values of type System.String. To read and write this value type, wrap it in a property of type string with suitable getters and setters.

I suppose this message comes from the BindMethods.SetValueHandler<T>(Action<T> setter, T existingValue) method.

Is there any way to work it around to create a custom component that would be able to handle `string`, `bool`, and `int` bindings in the same code, or have I just simply create different components for different binding types at the moment?

**Comment by rynowak** [comment]
Thanks for the report, this is indeed a bug. Using https://github.com/aspnet/AspNetCore/issues/9632 since we already have more info there.
