### ISSUE TITLE
Problem with compiling a generic Blazor component

### ISSUE THREAD

**Issue by romanoza** [aspnet/AspNetCore#5637]
I have the following problem.

The **MyClass** class is placed in the BlazorTest.Shared project and it's defined as:

```
namespace BlazorTest.Shared
{
    public class MyClass
    {
    }
}
```

I have also created a simple component, called **MyComponent**:

```
@using BlazorTest.Shared
@typeparam T

<div></div>

@functions {

[Parameter] T PropertyToInferType { get; set; }
[Parameter] MyClass MyProperty { get; set; }

}

```
My page looks like this:

```
@using BlazorTest.Shared
@page "/counter"

<MyComponent PropertyToInferType="3" MyProperty="@MyObject" />

@functions {
    MyClass MyObject = new MyClass();
}
```

I'm getting the compile-time errors:

> The type or namespace name 'Shared' does not exist in the namespace '__Blazor.BlazorTest' (are you missing an assembly reference?)
> Argument 6: cannot convert from 'BlazorTest.Shared.MyClass' to '__Blazor.BlazorTest.Shared.MyClass'

If I remove the `@typeparam` directive and modify the component by removing the `PropertyToInferType`  property, then everything compiles without errors.

Am I missing something?

PS. Blazor is awesome.

**Comment by romanoza** [comment]
@Abdsoft Yep, that works (as a temporary "solution"). Thanks.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb can you please look into this? Thanks!

**Comment by Faolan-dimplex** [comment]
Just ran into this same problem today, ended up having to use that horrible hacky workaround of prefixing namespace with __Blazor

**Comment by ajaybhargavb** [comment]
@Faolan-dimplex, are you on the latest preview? This issue has already been fixed.
If you are still seeing this issue on the latest release, please create a new issue and provide us a simple repro project.

**Comment by ajithr** [comment]
@ajaybhargavb I have created a separate thread for this issue and attached the Github repository in the same thread.

https://github.com/aspnet/AspNetCore/issues/12116
