### ISSUE TITLE
UseUrl Option

### ISSUE THREAD

**Issue by lorranpalmeira** [aspnet/AspNetCore#5643]
Is it possible set a UseUrl like WebApi?
`.UseUrls("http://localhost:7001/")`

Because in Blazor doesn´t has this option:

```
public static IWebAssemblyHostBuilder CreateHostBuilder(string[] args) =>
            BlazorWebAssemblyHost.CreateDefaultBuilder()
                .UseBlazorStartup<Startup>();
```

**Comment by Chinokaiser** [comment]
any updates?

i'm using vagrant to run dotnet, i need to point it to run on a specific ip adress so that i can access the app from host.

UseUrls would help

**Comment by mkArtakMSFT** [comment]
@Chinokaiser please see @michaelvolz's response:
> @lorranpalmeira You can change the URL in the server project.

We're closing this issue as the original question has been answered.
