### ISSUE TITLE
Json variables names

### ISSUE THREAD

**Issue by JulienM28** [aspnet/AspNetCore#5644]
Maybe I didn't find the correct method, but I faced an issue using Dtos.

I'm doing some application with a backent and a frontend sharing the same dtos in a separate dll.

I used to do like this

`     [JsonProperty("qnaList")]
    public List<KBEntry> Entries { get; set; } = new List<KBEntry>();`

but it seems Blazor doesn't support NewtonSoft Data Annottions.

What could be the good solution for that problem if there's one right now.

Thanks.

**Comment by mkArtakMSFT** [comment]
You should now be able to use Json.Net to accomplish this scenario.
