### ISSUE TITLE
How to hook up alternate IServiceProvider implementation?

### ISSUE THREAD

**Issue by DaRosenberg** [aspnet/AspNetCore#5646]
I'm trying to hook Autofac into my Blazor app, but I can't find any way to provide the actual `IServiceProvider` instance myself.

Here's an illustration of what I'm trying to do (as per [Autofac documentation](https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#quick-start-without-configurecontainer)):

```cs
public class Startup
{
    public IContainer ApplicationContainer { get; private set; }

    public IServiceProvider ConfigureServices(IServiceCollection services)
    {
        var builder = new ContainerBuilder();
        builder.Populate(services);
        // Add some custom service and implementation to test whether it can be injected
        builder.RegisterType<DefaultSystemClock>().As<ISystemClock>();
        ApplicationContainer = builder.Build();

        // This return value seems to never be used by the WebAssemblyHostBuilder
        return new AutofacServiceProvider(ApplicationContainer);
    }

    public void Configure(IBlazorApplicationBuilder app)
    {
        app.AddComponent<App>("app");
    }
}
```

A quick glance into the source of `WebAssemblyHostBuilder` and `ConventionBasedStartup` seems to confirm that this is not how it's implemented (there's no code that take care of any return value from the `ConfigureServices()` method.

Is there some other hook I should be using to replace the default `IServiceProvider` implementation with the one provided by Autofac?

**Comment by SteveSandersonMS** [comment]
Implemented in https://github.com/aspnet/AspNetCore/pull/4785
