### ISSUE TITLE
Problem deserializing dictionary with object keys

### ISSUE THREAD

**Issue by andycnguyen** [aspnet/AspNetCore#5648]
I'm trying to send an object of type `Dictionary<Node, decimal>` from my controller to a page, where `Node `is a custom class I've written. When I first attempted this, I got the following error:

`WASM: [System.ArgumentException] The value "App.Shared.Graph.Node" is not of type "App.Shared.Graph.Node" and cannot be used in this generic collection.`

I learned that there is a more general problem of deserializing dictionaries with complex keys, and sure enough I found that if I attempted to serialize and deserialize one of my dictionaries in a unit test using Json.NET, it failed. With this in mind, I implemented the `TypeConverter` solution suggested [here](https://stackoverflow.com/questions/24504245/not-ableto-serialize-dictionary-with-complex-key-using-json-net). Now I can successfully serialize and deserialize my dictionaries in unit tests, but this still fails in my Blazor app. I now get a different error:

`WASM: [System.ArgumentException] The value "{"Username":"123","Name":null,"Degree":0}" is not of type "App.Shared.Graph.Node" and cannot be used in this generic collection.`

(The value cited above corresponds to one of my `Node` objects.)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
