### ISSUE TITLE
Js initialization in OnAfterRender stopped working with 0.7.0

### ISSUE THREAD

**Issue by fs86** [aspnet/AspNetCore#5649]
After I upgraded to Blazor 0.7.0 I noticed that initialization scripts of 3rd party JavaScript libraries which I usually call in OnAfterRender stopped working.
E.g. I use select2 (https://github.com/select2/select2) to apply a custom style for my select fields. But it seems like something has changed with Blazor 0.7.0, because the following code (which used to work in 0.6.0) dosn't work anymore:

```
protected override void OnAfterRender()
{
  base.OnAfterRender();
  JsInterop.InitializeSelect2();
}
```

My JavaScript function:
```
window.JsFunctions = {
  initializeSelect2: function() {
    $('select').select2();
  }
}
```
The control style will get applied when I call StateHasChanged() after JsInterop.InitializeSelect2(), but this will end up in an endless loop. Is there a better place to call InitializeSelect2() than OnAfterRender?

**Edit:**
I found the following statement about lifecycle methods in the official documentation:

> OnAfterRenderAsync and OnAfterRender are called each time after a component has finished rendering. Element and component references are populated at this point. **Use this stage to perform additional initialization steps using the rendered content, such as activating third-party JavaScript libraries that operate on the rendered DOM elements.**

After doing a bit of research I can say that the corresponding field is not accessible in OnAfterRender.

**Comment by Lupusa87** [comment]
I am not sure this will be workaround for this case, but you can try.

Please follow timer2 in [code](https://github.com/Lupusa87/BlazorPerformanceChart/blob/master/BlazorPerformanceChart/Pages/PerformanceChartPage_Logic.cs#L23)

Idea here is to delay some method call.

In my case I used this trick because calling my method inside OnAfterRender was doing nothing, but from timer callback it is working as expected.

Hope it helps.

**Comment by mkArtakMSFT** [comment]
Closing this as this is definitely working now. Please check out a recent release and if you would experience the same issue feel free to file a new issue.
