### ISSUE TITLE
Question about future on ASP.NET Core 3.0 & Components

### ISSUE THREAD

**Issue by xclud** [aspnet/AspNetCore#5650]
Currently we use an static html file with an <app /> tag and a script which does the magic. I am making a PWA for my nextgen product and i am wondering how it will be to integrate Components (Blazor) into Razor pages (Or MVC pages).

Talking about Server-side Rendering specifically, Ideally i am thinking of putting some components tags (e.g using tag helpers?!) directly into the razor pages and i will get those parts of my pages updated in-place.

Is there any overview as we are currently in version 0.8 ? I appreciate any enlightenment.

**Comment by pjmagee** [comment]
@xclud  The new template allows for SSR and using a RazorPage.chstml as the entry point, is this what you mean?

**Comment by xclud** [comment]
@pjmagee Thank you for the reply. The question is old back to Preview 1. I am already using the lastest SDK so the problem is solved now.

Sorry for forgetting to close the issue earlier. I close it now.
