### ISSUE TITLE
'bind' does not accept values of type System.DateTimeOffset

### ISSUE THREAD

**Issue by mwinkler** [aspnet/AspNetCore#5651]
If I try to bind the type `System.DateTimeOffset` I get a

> System.ArgumentException: 'bind' does not accept values of type System.DateTimeOffset. To read and write this value type, wrap it in a property of type string with suitable getters and setters.

Example:

`<input type="date" class="form-control" bind=@Timestamp />`

**Comment by mkArtakMSFT** [comment]
Related issue: https://github.com/aspnet/AspNetCore/issues/9598

**Comment by mkArtakMSFT** [comment]
This is already supported.
