### ISSUE TITLE
How does one do nested child content in the compnent derivation chain?

### ISSUE THREAD

**Issue by DeanRoddey** [aspnet/AspNetCore#5652]
So, how do you go about dealing with multiple levels of child content? Lets say you have this sequence of components deriving from each other:

Modal -> DialogBox -> MyPersonalDialogBox

So DialogBox wants to put the child content of MyPersonalDialogBox inside a DIV, with a title bar on top and buttons on the bottom. Modal wants to put DialogBox's content inside himself so that he can present that content modally.

Obviously we can use containment instead of derivation, and have that working fine, so DialogBox USES a modal component, and my dialog box USES a DialogBox component. But ultimately that's not how OO should work. My dialog box 'is a' dialog box which 'is a' modal component, and we want to have virtual methods that can be called from baser classes up to more derived classes, and helper methods that can accept any modal component or any dialog box and so forth.

But I can't figure out how to deal with the layered child content when doing it this way. No matter what I do, the content ends up not rendered within the parent class' embrace but outside of it, or I end up with one ChildContent hiding the other and so forth. It's probably something so utterly obvious I can't see it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
