### ISSUE TITLE
[Suggestion] Better components inheritance

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#5655]
First let me explain my problem.

I have a `Field `component inside of _MyComponents_ library. All it contains is just a basic div. For example:
`Field.cshtml` in _MyComponents_
```
@inherits Base.BaseField
<div class="@ClassMapper.Class">
    @ChildContent
</div>
```
Everything good so far, it renders, and it's all good.

BUT, here is the problem, if I want to extend the Field component in another components library, let's say that this time I want it to contain a `Label`. I cannot do that. If I wan't custom logic in this new library then I must create a new `Field.cshtml` and write everything, than I have to delete `Field` from by base _MyComponents_ library because it will mess with the new component.

This is an implementation of `Field.cshtml` in _MyComponents.Bootstrap_ library:
```
@inherits BootstrapBase.BaseBootstrapField
<div class="@ClassMapper.Class">
    @if ( Label != null )
    {
        <FieldLabel>@Label</FieldLabel>
    }
    @ChildContent
</div>
```
It would be great If for example I could just inherit Field automatically, maybe if both libraries share the same component names that they would combine.

I propose two way how to do it. Maybe :)

First, here is the main `Field.cshtml` in _MyComponents_
```
@inherits Base.BaseField
<div class="@ClassMapper.Class">
    @ChildContent
</div>
```

**Suggestion 1**: do it automatically based on the component name
`Field.cshtml` in _MyComponents.Bootstrap_
```
@if ( Label != null )
{
    <FieldLabel>@Label</FieldLabel>
}
@ChildContent
```

**Suggestion 2**: explicitly say that it is inherited from `Field.cshtml` in _MyComponents.Bootstrap_
```
@inherits MyComponents.Field
@if ( Label != null )
{
    <FieldLabel>@Label</FieldLabel>
}
@ChildContent
```

**Expected result:**
```
<div class="field">
    <label class="label">Hello label</label>
    Hello field
</div>
```

**Comment by danroth27** [comment]
No plans to do anything here, so closing.
