### ISSUE TITLE
HTML-only templates or plugin-based templating engine

### ISSUE THREAD

**Issue by jtillman** [aspnet/AspNetCore#5658]
Blazor should remove the use of C# within the HTML templates and move to pure HTML Attribute logic like angular/vuejs/knockout.

*Note: This is a follow-up action after asking for vuejs/angular-style templates during the community standup a while back [https://youtu.be/CWuIz9khK-o?list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL&t=3857] (I know it was a super long time ago 🤦‍♂️ )

My intent isn't to copy other popular frameworks but to take the learnings and knowledge that MS already has when developing UI frameworks. Notably the shift to having a declarative language like XAML which uses data binding on attributes like 'ItemSource' or 'Visibility' instead of allowing code to reside inside those templates. It promotes the separation of business logic from residing within the template and makes it more readable for programmers/designers. In the field, I've observed that pure web designers on teams are often discouraged or restricted from committing changes to templates that have languages injected into them which makes them more dependent on developers to make cosmetic changes. Personally, I don't enjoy having two languages in the same file (even in vuejs or angular) and wish it followed the XAML/XAML.cs style. On the other hand, I understand the convenience of having them within the same file, but I do not agree with mixing the languages (one of the main reasons I don't prefer react).

I understand that Blazor uses the Razor templating engine and we are currently restricted to what it offers. IMO, since Razor templates only work on the server, I would relate them to server-side frameworks like jinja2 or Django templates. These frameworks address a different use case of back-end engineers optionally sending parts of HTML to the client and doesn't tool for SPAs. I understand the convience of using it as the engine but I do not think its practices migrate well to a client UI framework.

Since there seems to be a strong tension to have a story for migrating Razor users and templates to Blazor, I would suggest investing in a layer of abstraction where other template engines may be exchanged from the one out of the box. I'd personally invest a large quantity of development time to make sure that a pure attribute option become available.

**Comment by danroth27** [comment]
No plans to do anything here, so closing.
