### ISSUE TITLE
Multiple blazor apps in single website

### ISSUE THREAD

**Issue by nvmkpk** [aspnet/AspNetCore#5659]
I would like to be able to host multiple blazor apps in my website (at different base path).

The idea is to provide multiple downloadable PWA apps and the user will be able to download one or more of them. I am currently using angular to do this. I would like to switch to blazor.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nvmkpk.
It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by nvmkpk** [comment]
This is not about asp.net core. Currently blazor helper method does not allow configuring two separate blazor applications.

**Comment by nvmkpk** [comment]
Also, this issue was transferred from aspnet/Blazor repository. Before transfering, it has a few up votes. That shows more people were interested in this feature.

**Comment by MichelArendt** [comment]
I believe I'm looking for something similar as well. I'm trying to create a hosted app and have multiple different client applications connect to it, each with a different function. For example, an app for the customer, an app for server management, an app for the employees, and so forth. All of them on different base paths like /customer, /server, /employee, etc. Is this possible in any way yet?

**Comment by nvmkpk** [comment]
I do have code to get that working for Blazor that I wanted to contribute here but it seems they are not interested in it. But it currently works with preview 5. I could not find time to update it to work with latest preview.
