### ISSUE TITLE
Blazor server-side publish docker image failure

### ISSUE THREAD

**Issue by agonzalezm** [aspnet/AspNetCore#5662]
I am trying to publish a docker image of my blazor SSR app but i get this error when running build

Error		The "Microsoft.AspNetCore.Razor.Tasks.RazorTagHelper" task could not be loaded from the assembly /root/.nuget/packages/microsoft.aspnetcore.razor.design/2.1.1/build/netstandard2.0/../../tasks/netstandard2.0/Microsoft.AspNetCore.Razor.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/src/testapp/testapp.Server.csproj]	

The command '/bin/sh -c dotnet build "testapp.Server.csproj" -c Release -o /app' returned a non-zero code: 1
C:\Users\agonzalez\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.0.1916590\build\Container.targets(132,5): Error MSB3073: The command "docker build -t "testapp" -f "Dockerfile" ".."" exited with code 1.

**Comment by Gaulomatic** [comment]
Same issue here but without Docker.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @agonzalezm.
This will be fixed in 3.0 release.
