### ISSUE TITLE
Remove comments from html markup

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#5663]
When Blazor is building the html it also builds unnecessary comments along with the html tags.

![image](https://user-images.githubusercontent.com/900302/49376286-10978f80-f707-11e8-90a2-57b782ad6c8b.png)

Is there an option to turn this off? Or is it on your road-map to fix this?

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS thoughts?

**Comment by SteveSandersonMS** [comment]
The comments are there for functional reasons. They let the renderer track the boundaries of components in a more efficient way than we could otherwise, and don’t really have any practical drawback that I know of.
