### ISSUE TITLE
Enhancement suggestion: Components as attributes in other components or tags

### ISSUE THREAD

**Issue by michaelvolz** [aspnet/AspNetCore#5668]
```Html
<MyComponent Memoize="true" ComponentProperty="@SomeValue" />
```

`Memoize` would be another component which defines the `Attribute` and had full access to the underlying component. 

As an example it could even prohibit rendering and inject a dynamic rendertree which could be stored in a cache. I believe `Taghelpers` can do something similar.

More Examples:
```Html
<MyComponent Repeat="5" ComponentProperty="@SomeValue" />
<MyComponent HideWhenEnvironment="Production" ComponentProperty="@SomeValue" />
<MyComponent DisplayWhenEnvironment="Debug" ComponentProperty="@SomeValue" />
<MyComponent LazyLoad="true" ComponentProperty="@SomeValue" />
<MyComponent DataSourceWithCachingAndErrorHandling="/api/category/value/@value;bindto(ComponentProperty)" ComponentProperty="@SomeValue" />

[...]

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @michaelvolz.
This is not something we plan to add in the near future.
