### ISSUE TITLE
Support for Visual Studio 2019

### ISSUE THREAD

**Issue by BerserkerDotNet** [aspnet/AspNetCore#5669]
Make `ASP.NET Core Blazor Language Services` available for VS 2019.

**Comment by rynowak** [comment]
This is done 👍 - this will be going on in VS 2019 preview 2, but will require updated runtime packages/templates to work. Stay tuned for announcements when we release the next set of previews.

**Comment by vchirikov** [comment]
@rynowak VS 2019 preview 2 has been released. But even https://dotnet.myget.org/F/blazor-dev/vsix/ still contain vs 2017 version only.

**Comment by rynowak** [comment]
Yes, we have some enabling features in preview2. Expect to see some new stuff when .NET Core 3.0.0 preview2 (soon). We'll make an announcment when stuff is ready to use.

**Comment by vchirikov** [comment]
Any news?

**Comment by hajekj** [comment]
Just for reference: https://blogs.msdn.microsoft.com/webdev/2019/01/29/aspnet-core-3-preview-2/

**Comment by BerserkerDotNet** [comment]
I've tried on VS 2019 Preview 2.1 with .Net Core 3.0 preview 2 SDK installed, but still, my Blazor app does work. Any extensions I need to install or changes I need to do to my project?

**Comment by vchirikov** [comment]
Same:
![Blazor on vs 2019 2.1](https://user-images.githubusercontent.com/40987940/52196011-407c2400-286b-11e9-9d56-dcb2f8e90a3e.png)

**Comment by chucker** [comment]
This is not currently supported. You can try temporarily moving your project to a prerelease feed, like here: https://github.com/dotnet-presentations/blazor-workshop/pull/47/commits/df702048edddc586bce6ad389b220b27ca8bfeac

**Comment by vchirikov** [comment]
@chucker thanks, works fine.

**Comment by ransagy** [comment]
I'm a little confused; This is marked as done, But the VSIX/Intellisense doesn't seem to be supported yet. Is that intentional?

**Comment by AppiePau** [comment]
> I'm a little confused; This is marked as done, But the VSIX/Intellisense doesn't seem to be supported yet. Is that intentional?

Me too, I have VS 2019 Community RTM installed and both intellisense and debugging don't work properly. Building and running works fine.

**Comment by chucker** [comment]
For ASP.NET Core 3.0 Preview 4 and newer, you need Visual Studio 2019 16.1 Preview.

**Comment by AppiePau** [comment]
> For ASP.NET Core 3.0 Preview 4 and newer, you need Visual Studio 2019 16.1 Preview. 16.0 will work for building, but not for IntelliSense, etc.

Oh wow, thanks. That was just what was missing!

**Comment by aapluse** [comment]
I have Visual Studio 2019 for Mac.
I created a blazor hosted through the cli 2 days ago and it worked fine.
Now I'm performing the same steps but the new app is not building.
The build error description is" rzc generate exited with code 1." in file RazorCompilation.targets.

I'm not sure how to solve this.

**Comment by chucker** [comment]
>I created a blazor hosted through the cli 2 days ago and it worked fine.

Have you updated your .NET Core 3.0 SDK to preview 8?

**Comment by aapluse** [comment]
I have.  Now I'm worse off.  
I'm running Visual Studio for Mac 8.2.3 (build 16).
.Net 3.0.100-preview8-013656

I have updated templates.  From the cli the option for blazorhosted  does not appear.  instead, blazorwasm seems to have replaced it.  I create a project, I build it and get no errors.
However, when I run it without any modifications, it just does not do anything, it does not even give an error message.
I'm attaching the Package console view.

<img width="876" alt="pic" src="https://user-images.githubusercontent.com/4743504/63131218-e6cb8380-bf8a-11e9-9cff-8670e38aaf4c.png">
