### ISSUE TITLE
How to get self referenz from events?

### ISSUE THREAD

**Issue by UrielMhezzek** [aspnet/AspNetCore#5671]
Hello,
how can i get the self referenz by blazor/c# events like javascript?

```html
<a href="" id="someId" onclick="SomeMethod(this);"></a>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
