### ISSUE TITLE
Missing VSIXAssemblyInfo.cs in BlazorExtension output

### ISSUE THREAD

**Issue by nolisj** [aspnet/AspNetCore#5672]
Hi! After removing all errors during the build of the Components solution, I have one pending error that I do not understand how to fix. I keep getting this error:

---
CS2001	Source file '[myrootfolderhere]\src\Components\artifacts\obj\Microsoft.VisualStudio.BlazorExtension\\Debug\Microsoft.VisualStudio.BlazorExtension.VSIXAssemblyInfo.cs' could not be found.
---

(fyi, note that there's a double backslash after DEBUG in the error message but this github editor is not showing it)

I tried searching for the VSIXAssemblyInfo.cs in the solution and the only instance it is mentioned is in the Microsoft.VisualStudio.RazorExtension.csproj file itself (note that it's another project) and not in the BlazorExtension project. 

The other one is in the FileListAbsolute.txt file itself which was created during the build. It has the following entry in the FileListAbsolute.txt: [myrootfolderhere]\src\Components\artifacts\obj\Microsoft.VisualStudio.BlazorExtension\Debug\Microsoft.VisualStudio.BlazorExtension.VSIXAssemblyInfo.cs.

The problem is I don't see anyway for this file to be excluded during the build since it was not there in the first place. 

Is this file, VSIXAssemblyInfo.cs, really intended to be there?

**Comment by mkArtakMSFT** [comment]
This was fixed.
