### ISSUE TITLE
MouseEvent does not adopt the properties

### ISSUE THREAD

**Issue by UrielMhezzek** [aspnet/AspNetCore#5677]
The Javascript function returns normal values like:

> ClientX: 106, ClientY: 285

The C# function only returns default values.

> {"detail":0,"screenX":0,"screenY":0,"clientX":0,"clientY":0,"button":0,"buttons":0,"ctrlKey":false,"shiftKey":false,"altKey":false,"metaKey":false,"type":null}

JavaScript Interop
```javascript
        document.onmouseup = function (event) {
            console.log(event);
            DotNet.invokeMethodAsync('DSA.App', 'JsMouseUp', event);
        }
```

JavaScriptInteropClass
```c#
 [JSInvokable]
        public static Task<bool> JsMouseUp(UIMouseEventArgs eventArgs)
        {
            var found = false;
            Console.WriteLine(Json.Serialize(eventArgs));
            return Task.FromResult(found);
        }
```
Is this an error? This is Blazor ServerSide

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @UrielMhezzek.
@SteveSandersonMS, is there anything else to add here?

**Comment by danroth27** [comment]
Thanks for answering, @AndreasTruetschel !
