### ISSUE TITLE
TypeLoadException

### ISSUE THREAD

**Issue by lsvhome** [aspnet/AspNetCore#5678]
Type load error in deep library code of well known library.
I attached project which demonstrates this bug.
Also I added code (in Program.cs) which fixes bug, but it is hack. 
[BlazorExceptionExample.zip](https://github.com/aspnet/Blazor/files/2684016/BlazorExceptionExample.zip)

Newtonsoft.Json.JsonSerializer serializer = new Newtonsoft.Json.JsonSerializer();
serializer.Serialize(new StringWriter(new StringBuilder()), new SerializableClass()); // error here

stacktrace:

blazor.webassembly.js:1 WASM: System.TypeLoadException: Could not load type of field 'Newtonsoft.Json.Linq.JToken:_parent' (1) due to: Could not resolve type with token 010000f5 from typeref (expected class 'System.Collections.Specialized.INotifyCollectionChanged' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Collections.Specialized.INotifyCollectionChanged member:(null)
blazor.webassembly.js:1 WASM:   at (wrapper delegate-invoke) System.Func`2[System.Type,Newtonsoft.Json.Serialization.JsonContract].invoke_TResult_T(System.Type)
blazor.webassembly.js:1 WASM:   at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) <0x1e98ed0 + 0x0007c> in <82fb964f98d945899c8c2aee07253463>:0 
blazor.webassembly.js:1 WASM:   at Newtonsoft.Json.Utilities.ThreadSafeStore`2[TKey,TValue].Get (TKey key) [0x00000] in /_/Src/Newtonsoft.Json/Utilities/ThreadSafeStore.cs:64 
blazor.webassembly.js:1 WASM:   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract (System.Type type) [0x0000b] in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:198 
blazor.webassembly.js:1 WASM:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe (System.Object value) [0x00005] in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:123 
blazor.webassembly.js:1 WASM:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00028] in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:70 
blazor.webassembly.js:1 WASM:   at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x0023a] in /_/Src/Newtonsoft.Json/JsonSerializer.cs:1149 
blazor.webassembly.js:1 WASM:   at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value) [0x00000] in /_/Src/Newtonsoft.Json/JsonSerializer.cs:1076 
blazor.webassembly.js:1 WASM:   at Newtonsoft.Json.JsonSerializer.Serialize (System.IO.TextWriter textWriter, System.Object value) [0x00000] in /_/Src/Newtonsoft.Json/JsonSerializer.cs:1033 
blazor.webassembly.js:1 WASM:   at BlazorTypeLoadExceptionExample.Program.Main (System.String[] args) [0x00013] in C:\Data\git\BlazorExceptionExample\BlazorTypeLoadExceptionExample\Program.cs:31

**Comment by JamesNK** [comment]
This is Blazor which I have no experience with. A Blazor dev would be better suited to handle this.

**Comment by DerekChasse** [comment]
Issue is being tracked here as far as I can tell.

https://github.com/mono/mono/issues/11848

**Comment by DerekChasse** [comment]
I've run into the exact same issue and it does not look to be a Newtonsoft.Json thing. 
However this workaround does not seem to work in my scenario.  I am using JsonConvert and not JsonSerializer, though I would assume that that doesn't matter.

My serialization happens in a linked client assembly, so I'm not sure where exactly this workaound would need to be applied.

Anyway, this can likely be closed and tracked in the mono repo or associated with https://github.com/aspnet/Blazor/issues/1692 which was the Blazor instigator.

**Comment by SteveSandersonMS** [comment]
This is the same Mono issue that @DerekChasse linked to at https://github.com/mono/mono/issues/11848, so I'll close this as external.
