### ISSUE TITLE
Blazor, How to Invoke .NET methods from JavaScript functions use js timer

### ISSUE THREAD

**Issue by w8w8w8** [aspnet/AspNetCore#5683]
blazor : How to Invoke .NET methods and get values from JavaScript functions use js timer. 
and It goes on and on.

and How to Invokeand JavaScript functions and delivery Mass data from .NET methods  use C# timer. 

when I do it, chrome run 1 hour later , crash.

https://github.com/aspnet/AspNetCore/issues/4365

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @w8w8w8.
Closing this issue as it's very close to the other one you've filed.
