### ISSUE TITLE
Health Checks middleware route execution order

### ISSUE THREAD

**Issue by steveoh** [aspnet/AspNetCore#5684]
### Describe the bug
Health check middleware related to https://github.com/aspnet/Diagnostics/issues/512 and https://github.com/aspnet/Diagnostics/issues/511 does not appear to be fixed in 2.2 or possibly I need to update the order of which i supplied my routes. Can you clarify the specificity order? cc @rynowak 

### To Reproduce
I would refer to the original issue

### Expected behavior
Ordering of the health check routes is not solving the issue where I cannot access all routes.

### Additional context

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.101/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by rynowak** [comment]
Assigning myself to look at this.

**Comment by rynowak** [comment]
This is working correctly for on the lastest 2.2.X build. If you're still having problems in the latest build please provide a repro project (zip or git repo) so I can try exactly what you're seeing.
