### ISSUE TITLE
IIS in-process mode still has "conhost.exe" as child process

### ISSUE THREAD

**Issue by UweKeim** [aspnet/AspNetCore#5689]
On Windows Server 2012 R2, we just switched to .NET Core 2.2 and switched from IIS out-of-process mode to IIS in-process mode.

While this removed our own .EXE as a w3wp.exe child process, we still see "conhost.exe" as a w3wp.exe child process:

![image](https://user-images.githubusercontent.com/415439/50136679-d4346980-0298-11e9-9b1a-8cf6ed865634.png)

I would have expected that in-process completely avoids additional child processes.

**My question:**

Is this expected behaviour, or do we have something misconfigured?

**Comment by pakrym** [comment]
This might be a side-effect of AspNetCore module trying to set up standard output redirection. This process wouldn't execute any application code it's just a part of windows console infrastructure.

**Comment by UweKeim** [comment]
Thanks a lot, Pavel!
