### ISSUE TITLE
[Blazor] Call on application startup

### ISSUE THREAD

**Issue by Hantse** [aspnet/AspNetCore#5692]
### Is your feature request related to a problem? Please describe.
I'm am trying to do a HttpClient call during app init but the result is load after the app is load or the blocking call stop and crash browser.

### Describe the solution you'd like
A posibility to call async during app loading and app wait the call is over to continuous the process.
For example in Angular : 
https://hackernoon.com/hook-into-angular-initialization-process-add41a6b7e

### Describe alternatives you've considered
I try to add a component with async init in App.cshtml but the result is load after the page is render.

**Comment by enetstudio** [comment]
This issue might be related to yours: https://github.com/aspnet/AspNetCore/issues/5664#issuecomment-446448872

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Hantse.
You can see how the `FetchData` page in our sample app is done. It's similar to what you are looking for.

**Comment by Hantse** [comment]
Which sample ?

**Comment by Hantse** [comment]
> Thanks for contacting us, @Hantse.
> You can see how the `FetchData` page in our sample app is done. It's similar to what you are looking for.

Which sample ?

Thx :)

**Comment by karthickthangasamy** [comment]
@Hantse : Create a getting started Blazor application, in which you can see the `FetchData.razor` file inside `Page` folder.

[Getting started with Blazor](https://docs.microsoft.com/en-in/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)

**Comment by Hantse** [comment]
Hello,
@karthickthangasamy 
In this sample it's for load data for one "page", but if  i want load data for shared service between all application ?
