### ISSUE TITLE
Is InProcess hosting mode supported with .net framework aspnetcore apps

### ISSUE THREAD

**Issue by maxence51** [aspnet/AspNetCore#5693]
Hello,

I try to figure out if aspnetcore on .Net Framework can be hosted on IIS with in-process mode.
It's not seems to be the case but It's not clear in the documentation. 

Thank you.

**Comment by Tornhoof** [comment]
No it's not supported. 
It was stated a few times in the old iisintegration repository, e.g https://github.com/aspnet/IISIntegration/issues/1531

**Comment by pakrym** [comment]
Closing this as it's tracked in https://github.com/aspnet/Docs/issues/10297
