### ISSUE TITLE
Combine multiple shared localization resources into one

### ISSUE THREAD

**Issue by fabercs** [aspnet/AspNetCore#5694]
In our project, we have multiple shared localization resources which we classified them logically. 
Like; EnumResource, MessageResource etc.

This is the helper object which we inject as singleton on startup.
```
public class GenericSharedResourceService<T> where T :class
    {
        private readonly IStringLocalizer _localizer;

        public string this[string key] {
            get
            {
                if (_localizer != null)
                    return _localizer[key];
                else
                    return null;
            }
        }

        public GenericSharedResourceService(IStringLocalizerFactory factory)
        {
            //foreach T run below
            var type = typeof(T);
            var assemblyName = new AssemblyName(type.GetTypeInfo().Assembly.FullName);
            _localizer = factory.Create(type.GetTypeInfo().Name, assemblyName.Name); 
            //at the end combine all _localizers into one localizer object
        }

        public LocalizedString GetLocalizedString(string key) => _localizer[key];
    }
```
This is how we call them from views as an example 
```
@inject GenericSharedResourceService<MessageResource> ML
@inject GenericSharedResourceService<EnumResource> EL
```
So what we want is to be able to combine multiple shared resource into one resource in this helper object, so call just one shared resource object instead multiple in controllers and views. I searched the api (`IStringLocalizerFactory.Create` and `IStringLocalizer`) but couldn't find anything useful. Is there any way to do this?

**Comment by mkArtakMSFT** [comment]
Hi @fabercs. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

One way you could take here would be to make the helper a composite of multiple `IStringLocalizer` instances. That will allow you to inject just the helper instance (non-generic already), but you'll need to move the specific type information down to the lookup method - by making it generic instead.

**Comment by fabercs** [comment]
@mkArtakMSFT thanks for your response. Based on your advice, I am sharing the code that I ended up with, working as expected.

```
 public class EnumResource : IShared{}
 public class MessageResource : IShared{}
```

```
public class GenericSharedResourceService
    {
        private List<IStringLocalizer> _sharedLocalizers { get; set; } = new List<IStringLocalizer>();

        public string this[string key] {
            get
            {
                foreach (IStringLocalizer localizer in _sharedLocalizers)
                {
                    if (localizer == null || localizer[key] == null)
                        continue;
                    return localizer[key];
                }
                return null;
            }
        }

        public GenericSharedResourceService(IStringLocalizerFactory factory)
        {
            var assemblies = AppDomain.CurrentDomain.GetAssemblies()
                            .Where(a => a.FullName.StartsWith("_namespace or assembly name_")).FirstOrDefault()
                            .GetTypes().Where(t => typeof(IShared).IsAssignableFrom(t));

            foreach (var assembly in assemblies)
            {
                var assemblyName = new AssemblyName(assembly.GetTypeInfo().Assembly.FullName);
                _sharedLocalizers.Add(factory.Create(assembly.GetTypeInfo().Name, assemblyName.Name));
            }
        }
    }
```

I am keeping the typed version as well for any requirement. I this good to go with, do you see any gotcha in the code?

**Comment by mkArtak** [comment]
Hi @fabercs.

This looks good. Depending on the number of resources you expect to have and the memory stress you are able to tolerate, you may even want to add an additional level of caching in the `GenericSharedResourceService`. The cache will essentially be a map between the key and the actual `localizer` you've found the first time, so there is no need to iterate over the other localizer on the subsequent call for the same key.

**Comment by fabercs** [comment]
Thanks, I will reconsider this based on your caching advice.
