### ISSUE TITLE
.NET Core 3.0 Preview 1 makes app fail to start

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#5700]
_From @godrose on Tuesday, 18 December 2018 06:44:00_

# Issue Title

Using latest version of .NET Core 3.0.0 SDK (009812) introduces regression into an existing app

# General

Upgrading to the preview version and using it instead of 2.2.0 results in the following exception during app start:
```
Application startup exception: System.InvalidOperationException: Scheme already exists: ASOS
   at Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(String name, Action1 configureBuilder)
   at Microsoft.Extensions.Options.OptionsFactory1.Create(String name)
   at System.Lazy1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy1.CreateValue()
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions1 options, IDictionary2 schemes)
```

_Copied from original issue: dotnet/core#2160_

**Comment by Eilon** [comment]
_From @godrose on Tuesday, 18 December 2018 06:49:23_

I'm using OpenId.Connect in my app
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/210

**Comment by Eilon** [comment]
_From @karelz on Tuesday, 18 December 2018 17:15:08_

Do you have a minimal repro for ASP.NET team?

**Comment by Eilon** [comment]
@HaoK - any idea on this?

**Comment by godrose** [comment]
@Eilon Thanks for reaching out. I will try to prepare one today.

**Comment by godrose** [comment]
@Eilon 
Repro steps:

1. Install the `.NETCore 3.0.0 Dec'18 preview`
2. Clone the repo at https://github.com/godrose/asp-netcore-asos
3. `dotnet build`
4. `dotnet` (start)

Expected: app starts 
Actual: exception is displayed
`
Application startup exception: System.InvalidOperationException: Scheme already exists: ASOS
   at Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(String name, Action1 configureBuilder)
   at Microsoft.Extensions.Options.OptionsFactory1.Create(String name)
   at System.Lazy1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy1.CreateValue()
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions1 options, IDictionary2 schemes)
`

**Comment by Eilon** [comment]
Would it be possible to simplify the repro into something simpler? It's hard to tell what's getting added where and because there are so many components involved it's difficult to track down what's what.

**Comment by godrose** [comment]
@Eilon. I thought it was simple enough already. Let me check whether it can be simplified any further

**Comment by godrose** [comment]
@Eilon  I removed some unused packages.
Other than that the code is a simple bootstrapping flow with basic enhancements like composition and modularity.
If I remove the lines
```
.AddAuthentication()
.AddOpenIdConnectServer
``` 
and references to the `OpenId` packages along with `AuthorizationProvider` implementation
then everything works as expected.

**Comment by Eilon** [comment]
Hi @godrose , unfortunately almost everyone is out of the office right now. We should be able to get back to this first thing in the new year.

**Comment by godrose** [comment]
@Eilon 
>such as a custom DI provider

The only DI provider that is being used is the default one - `IServiceCollection`. The only difference is the way the registrations are added - in the modular way. Yet eventually it's the same Dependency Injection engine under the hood.

> that there's an issue with the DI configuration and when it's running

it's running when the app is starting. Not before, not after. The very moment the `Initialize()` method is called. There's no `async` code there, no race condition.

I will try to look how to run the app without the custom config over the weekend.

**Comment by Eilon** [comment]
Thanks for the clarification, but we suspect the root cause is that something is being registered twice (by mistake). What isn't clear to us is how to diagnose this because we're not familiar with that DI's registration mechanism.

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by godrose** [comment]
Thanks.
I guess I found the issue.
This is double registration which is invoked because the build generates both .exe and .dll files with identical types.
Can you expand on this feature and consult on whether it can be disabled and what's it for?
Thanks.

**Comment by Eilon** [comment]
@godrose are you asking about what is an authentication scheme?

**Comment by godrose** [comment]
@Eilon I’m asking about the change of creating two files: [filename].exe and [filename.dll] after building the .Net Core 3.0 console app. In .Net 2.2 there was only one file - [filename].dll

**Comment by godrose** [comment]
Particularly whether this behavior is configurable and what would be its usage.
Thanks.

**Comment by muratg** [comment]
@godrose please see https://docs.microsoft.com/en-us/dotnet/core/deploying/#framework-dependent-executables-fde

**Comment by godrose** [comment]
I see.
I'm not deploying the app though
