### ISSUE TITLE
@Html.Raw(Html.Partial("path")) does not work

### ISSUE THREAD

**Issue by guywithdoubts** [aspnet/AspNetCore#5702]
### Describe the bug
If I use @Html.Partial("someview"), it works fine and returns the markup.  In my case I need to assign that markup to a javascript variable.  First I tried with just @Html.Raw(Html.Partial("path")), and it does not return markup.  It just returns "Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer" instead of raw markup.

My final intention is this:
var jsMarkup = "";
jsMarkup = "@Html.Raw(Html.Partial("path"));

even from the above the javascript variable "jsMarkup" just contains "Microsoft...ViewBuffer".  This is the case whether or not I use a js variable.  If I remove "Html.Raw" it works, but the markup is not js friendly string obviously.

### To Reproduce
1. Using this version of ASP.NET Core '2.1'
2. Run this code '@Html.Raw(Html.Partial("path"))'
3. Will result in:

"Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer"

### Expected behavior
Has to render the markup in a raw way.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @guywithdoubts.
@NTaylorMullen is this expected to work and if so, what should be done?

**Comment by NTaylorMullen** [comment]
@guywithdoubts the reason it's not working as you intend is because `Html.Partial` returns a complex object (`IHtmlContent`) that is usually unwound when it's rendered by the base page; that being said Html.Raw doesn't understand `IHtmlContent`. If you really want to render your partial s a Raw Html string you'll have to do something like this:
```Razor
@{ 
    var partialOutput = await Html.PartialAsync("path");

    using (var writer = new System.IO.StringWriter())
    {
        partialOutput.WriteTo(writer, HtmlEncoder);
        @Html.Raw(writer.ToString())
    }
}
```
