### ISSUE TITLE
BrowserUriHelper is dead, right ?  

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#5710]
Dear friends, I guess you've killed BrowserUriHelper , right ? Unfortunately, in the comment at https://github.com/aspnet/AspNetCore/blob/ceb1c8e562562b2655622b571d2a9ad083806ad5/src/Components/blazor/src/Microsoft.AspNetCore.Blazor/Services/WebAssemblyUriHelper.cs, you still speaks of BrowserUriHelper in two places...

Thanks...

**Comment by SteveSandersonMS** [comment]
We renamed it to `WebAssemblyUriHelper`. You're correct that there are a couple of comments that didn't get updated. If you're keen, you could make a PR to fix this.
