### ISSUE TITLE
The new Endpoint routing behaves in unexpected and undocumented ways

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [aspnet/AspNetCore#5712]
### Describe the bug
I'm migrating a website originally written in `asp.net` to `asp.net core`.
In routing, I had minor problems until 2.1, but in 2.2 lots of things are broken.
I cannot reproduce my original problem, but I've found other problems along the path to diagnose it.

The original problem is that I get:

```
AmbiguousMatchException: The request matched multiple endpoints. Matches: 

MySite.Web.Controllers.HomeController.PermanentNotFound (MySite.Web)
MySite.Web.Controllers.HomeController.Dashboard (MySite.Web)
MySite.Web.Controllers.CompanyController.Index (MySite.Web)
MySite.Web.Controllers.HomeController.Index (MySite.Web)
```
The `2.1` [docs on routing](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1) say that:

> When a request arrives, the routes in the collection are processed in the order that they exist in the collection

Maybe implying that once a route is matched, no further attempt is made.

`2.2` [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2) lack such explanation. Btw, whatever I did to try and reproduce the problem, I failed, even by:

```
        routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action}/{id?}",
                    defaults: new { controller = "Home", action = "Index" });

        routes.MapRoute( //intentionally creating a second, similar route, trying to cause AmbiguousMatchException
            name: null,
            template: "{controller}/{action}/{id?}",
            defaults: new { controller = "Print", action = "Index" });
```

Reading the Routing source code, I could not understand the situation when the first match is chosen vs when such `AmbiguousMatchException` can occur. The compexity is in `DefaultEndpointSelector.ProcessFinalCandidates`:

```
        private static void ProcessFinalCandidates(
            HttpContext httpContext,
            EndpointSelectorContext context,
            CandidateSet candidateSet)
        {
            Endpoint endpoint = null;
            RouteValueDictionary values = null;
            int? foundScore = null;
            for (var i = 0; i < candidateSet.Count; i++)
            {
                if (!candidateSet.IsValidCandidate(i))
                {
                    continue;
                }

                ref var state = ref candidateSet[i];
                if (foundScore == null)
                {
                    // This is the first match we've seen - speculatively assign it.
                    endpoint = state.Endpoint;
                    values = state.Values;
                    foundScore = state.Score;
                }
                else if (foundScore < state.Score)
                {
                    // This candidate is lower priority than the one we've seen
                    // so far, we can stop.
                    //
                    // Don't worry about the 'null < state.Score' case, it returns false.
                    break;
                }
                else if (foundScore == state.Score)
                {
                    // This is the second match we've found of the same score, so there 
                    // must be an ambiguity.
                    //
                    // Don't worry about the 'null == state.Score' case, it returns false.

                    ReportAmbiguity(candidateSet);

                    // Unreachable, ReportAmbiguity always throws.
                    throw new NotSupportedException();
                }
            }

            if (endpoint != null)
            {
                context.Endpoint = endpoint;
                context.RouteValues = values;
            }
        }
```

The problems with this code:

- As soon as it finds two endpoints with the same score, it throws, but reporting on all endpoints in the set. Not all of them might have the same `Score`
- The `Score` value in the comments is supposed to only show the order in a `CandidateSet`, but sometimes it's default (0) and only in one code path it has non-zero value. All in all, the above code looks like a very complex way of selecting the first `Valid` candidate.

Now about constraints, consider this constraint:

```
public class MyConstraint : IRouteConstraint
  {
    public bool Match(HttpContext httpContext, IRouter route, string routeKey, RouteValueDictionary values, RouteDirection routeDirection)
    {
      return false;
    }
  }
```
And these routes:

```
routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action}/{id?}",
                    defaults: new { controller = "Home", action = "Index" },
                    constraints: new { domain = new MyConstraint() });
```

If using `CompatibilityVersion.Version_2_1`, the `MyConstraint.Match` method **will be hit** and the route will match.
With `CompatibilityVersion.Version_2_2`, the `MyConstraint.Match` **will not be  hit** and the route matches.
With `CompatibilityVersion.Version_2_2`, and changing `constraints: new { action = new MyConstraint() })` the `MyConstraint.Match` **will be hit** but although it returns false, the `HomeController.Index` endpoint will be selected. With `CompatibilityVersion.Version_2_1`, none of the routes will match.

Here are my suggestions:

1. Improving the documentation by explicitly stating the expected behavior when multiple endpoints match (even more explicitly than the `2.1` docs)
2. Fixing the code to avoid this strange behavior, or if it is by design, emphasizing it.
3. Fixing endpoint routing constraints to act like the previous version, or documenting the difference.

Thank you very much

**Comment by fish1ric** [comment]
I ran into the same issue with code that was working under 2.1.and had to set the compatibility to 2.1 in the Startup.cs file
//.SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
 .SetCompatibilityVersion(Microsoft.AspNetCore.Mvc.CompatibilityVersion.Version_2_1)

There is one additional issue with simple two types of inputs with one parameter and one optional not shown. If 'rname' is assigned a value such as 'abcdefg' it should load the variable rname to be 'abcdefg'.
It does return that value but it also has prepended the text of the route so the entire return variable value for 'rname' is now returned as 'rname=abcdefg' and not 'abcdefg'.
I will have to parse the return value and remove the 'rname=' part of the string.
Complex Controller HttpGet's that are similar work fine so it maybe related to 2.2 and the single value with the parameter name included in the route. The first GET call option lacking the parameter name returns the correct value of 'abcdefg'. The 2nd GET format of including the parameter name was to follow a more 'RPC' style RESTful call for some customers who need that type of call format.
        [HttpGet("v1/routename2routeidlist/{rname:required}"),
         HttpGet("v1/routename2routeidlist/rname={rname:required}")]

**Comment by felipepessoto** [comment]
I have the same problem, IRouteConstraint doesn't work when compatibility version is 2.2

**Comment by rynowak** [comment]
Apologies for the delay in following up on this issue. This was a bug in the original release of 2.2 and has been patched: https://github.com/aspnet/AspNetCore/issues/4591

**Comment by binraider** [comment]
I had this problem in Core 3.0.  I finally found the solution was to put a route attribute on the action - e.g. [Route("NodeInfo")]. That fixed it
