### ISSUE TITLE
OAuth 2.0 Bearer Token authentication

### ISSUE THREAD

**Issue by alexjusti** [aspnet/AspNetCore#5717]
I've been doing some digging, and I can't find anything regarding ASP.Net 5 and OAuth token based authentication.  Is this a planned feature for a later release, or am I missing something?

**Comment by danroth27** [comment]
We now have support for using IdentityServer with ASP.NET Core 3.0 which I believe covers this scenario: https://docs.microsoft.com/aspnet/core/security/authentication/identity-api-authorization

**Comment by BKlippel** [comment]
A day late and a dollar short.
