### ISSUE TITLE
Configure email/phone confirmation requrement separatelly for each authentication method

### ISSUE THREAD

**Issue by sergeyzwezdin** [aspnet/AspNetCore#5718]
I would like to configure email/phone confirmation requrement separatelly for each authentication method. For example, require email confirmation for password based sign in and don't for google auth.

I noticed it's impossible now, as there is check for all authentication methods - https://github.com/aspnet/Identity/blob/670614cdc59200f70a8045a7a5f346165d816fa1/src/Microsoft.AspNet.Identity/SignInManager.cs#L90-L94

How about changing this to be able to configure per each method?

**Comment by blowdart** [comment]
We're not going to do this. We expect external providers to do their own security checks, we don't want to layer on top of them. It's too far out of scope for the default templates.
