### ISSUE TITLE
AspNetClaims updating a claim from a role 

### ISSUE THREAD

**Issue by jvelezc** [aspnet/AspNetCore#5722]
The fact that an extension method is needed to remove claims in either the aspnetuserclaim and aspnetuserroleclaims is not the best way to interact with the system. It would be best if 
just like there is 
pseudo code
RoleManager<ApplicationRole> _roleManager = 
Exist today
_roleManager.AddClaimAsync
_roleManager.RemoveClaimAsync
My proposal: 
There should also be UpdateClaimAsync

http://stackoverflow.com/questions/24587414/how-to-update-a-claim-in-asp-net-identity

Can I do a PR?

**Comment by blowdart** [comment]
Noone has asked for this in 2 years, so closing
