### ISSUE TITLE
Expose a public CanSignInAsync() method

### ISSUE THREAD

**Issue by msmolka** [aspnet/AspNetCore#5727]
It would be good to use PreSignInCheck separately. I have external logic that requires whole precess except real ASP.NET sign in, so check if user can be successfully signed in. For UserName and Password I can n use CheckPasswordSignInAsync but for external login I don't have such possibility.

So either make PreSignInCheck public or add new CheckExternalSignInAsync method which will behave in the same way.

**Comment by blowdart** [comment]
Closing as we believe is addressed more fully as part of the upcoming account confirmation changes
