### ISSUE TITLE
Consider updating IdentityUserClaim to store the claim value type

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/AspNetCore#5742]
> Be aware that ASP.NET Identity doesn’t store claim value types, so even in cases where the claim is always an integer (as in this example), it will be stored and returned as a string. Later in this post, I explain how non-string claims can be included in JWT tokens.

https://blogs.msdn.microsoft.com/webdev/2016/10/27/bearer-token-authentication-in-asp-net-core/

**Comment by blowdart** [comment]
Killing as the issue is so old it should be on life support, and we're not doing schema changes right now
