### ISSUE TITLE
Consider updating AddIdentity() to avoid overriding default schemes when they were previously set

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/AspNetCore#5755]
> Identity is indeed a bit greedy and if you try to register your default scheme before calling `AddIdentity()`, it will be ignored.

> @HaoK would that be worth considering updating services.AddIdentity() to avoid overriding the default schemes when they are not null (i.e when already set by the developer?).

https://github.com/aspnet/Identity/blob/f3e251167212f18825506de9099a06e35350269c/src/Microsoft.AspNetCore.Identity/IdentityServiceCollectionExtensions.cs#L66-L71

**Comment by blowdart** [comment]
New overloads were added, so we consider those sufficient.
