### ISSUE TITLE
UserManager.Logger is virtual and set in the constructor

### ISSUE THREAD

**Issue by dfederm** [aspnet/AspNetCore#5756]
Pretty much as the title says.

This is considered bad practice, as ctor order is the most base class to the most derived class, so if the property is overridden in a subclass it may not be properly initialized.

Static Analysis even has a rule against this: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2214-do-not-call-overridable-methods-in-constructors (note that properties are effectively just a pair of methods, so the rule does in fact apply).

Here's a hypothetical example of something that could go wrong:

```
public class ApplicationUserManager : UserManager<ApplicationUser>
{
    private IObserver observer;

    public ApplicationUserManager(IObserver observer)
        : base(/* ... omitted for brevity ... */)
    {
        this.observer = observer;
    }

    public override ILogger Logger
    {
        get
        {
            this.observer.RecordPropertyGet(nameof(Logger));
            return base.Logger;
        }
        set
        {
            this.observer.RecordPropertySet(nameof(Logger), value);
            base.Logger = value;
        }
    }
}
```

In that example, the base class will set the `Logger` property, which will be the derived classes's impl, which uses `this.observer`, but oops it's null at that point in time since `ApplicationUserManager`'s ctor hasn't actually executed yet.

I am curious btw why this prop is virtual to begin with. It's a bit odd to see a virtual autoprop.

**Comment by blowdart** [comment]
Closed, as this is common throughout asp.net and should be part of a wider breaking push if one were to happen
