### ISSUE TITLE
Changing the primary key of IdentityUserClaim<> and IdentityRoleClaim<>

### ISSUE THREAD

**Issue by aneequrrehman** [aspnet/AspNetCore#5759]
Well, I have updated everything necessary to change all the Identity tables' primary keys to be `Guid`s, but I couldn't find any way to change the primary keys' types for `IdentityUserClaim<>` and `IdentityRoleClaim<>` tables. 

I have added this line in `ApplicationUser.cs`

    public virtual ICollection<IdentityUserClaim<Guid>> Claims { get; } = new List<IdentityUserClaim<Guid>>();

There should be some way to change the default primary keys (`int`s) for `IdentityUserClaim<>` and `IdentityRoleClaim<>`?. Or am I missing something?

Perhaps something like `IdentityUserClaim<TKey, TUserKey>` instead of `IdentityUserClaim<TKey>` (the name **TKey** is misleading as well unless one looks at the summary, IMHO)?

**Comment by blowdart** [comment]
Grooming old issues.

No, I don't think this is a pressing thing to support. So closing for now.

**Comment by LaterStart** [comment]
I would like to vote up for this feature. I think setting all existing application identifiers to configurable (in this case GUID) type should be possible.
