### ISSUE TITLE
RFC6238 Pin Length

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#5760]
IMHO the service should allow for a configurable PIN length 6/8 and be public; the GenerateCode/ValidateCode should also return/accept a string; the length of the pin is important
is current controlled by the RFC6238 as a const, service which may result in a number that requires padding with 0s and a consumer of the service many not realise resulting in the wrong length code getting passed up the call stack.

public static int GenerateCode(byte[] securityToken, string modifier = null)
public static bool ValidateCode(byte[] securityToken, int code, string modifier = null)

see: https://tools.ietf.org/html/rfc6238 for reference

string generateTOTP
..
while (result.length() < codeDigits) {
             result = "0" + result;
         }
 return result;

**Comment by blowdart** [comment]
Well, as we have no plans to make that class public and supported, we're not doing this, unless you can move it into CoreFX and System.Security where it should be if it was public
