### ISSUE TITLE
[Identity UI] Consider adding more id or similar attributes

### ISSUE THREAD

**Issue by markrendle** [aspnet/AspNetCore#5768]
These packaged UI elements are going to need to be style-able using CSS, so maybe it's worth adding more `id` or `class` or even just `data-xyz` attributes to various elements (for example, the `section`s on the Login page with the user/password and the external providers, or the individual buttons for the providers), and documenting those attributes for designers to work with.

Happy to contribute this if wanted.

**Comment by blowdart** [comment]
As we're not planning to do this I'm going to close. Mark if you want to PR go for it and link.
