### ISSUE TITLE
Consider option to treat email as the username

### ISSUE THREAD

**Issue by blowdart** [aspnet/AspNetCore#5773]
And automatically keep in sync. We got so many issues because the templates conflate the two in a poor way, and the mirroring of this is manual and patchy.

**Comment by camainc** [comment]
What is the status on this? I want to use identity in my site, but I don't want usernames to be the same as email addresses.

**Comment by blowdart** [comment]
Templates fixed to make it work better, as it's a templates thing, rather than identity
