### ISSUE TITLE
UserManager.FindByNameAsync doesn't get roles [QUESTION]

### ISSUE THREAD

**Issue by p2atran** [aspnet/AspNetCore#5785]
I recently just migrated my .NET Core 1.1.4 app over to .NET Core 2. Everything builds and compiles, but my identity stuff are all messed up. When I do a call to `UserManage.FindByNameAsync(email)`, The correct user is found. However, his role count is 0.

I read somewhere that Net Core 2 no longer eager/lazy loads. I'm still new to .NET Core environment and have been put in the deep end. How would I work around this to get the UserManager to work again? It used to work fine in .NET Core 1.1

**Comment by HaoK** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.0 for how to add the navigation properties back, see https://docs.microsoft.com/en-us/ef/core/querying/related-data for discussions on how to configure eager/lazy loading
