### ISSUE TITLE
stay logged in for longer than 30 minutes - why is this so confusing - can anyone help?

### ISSUE THREAD

**Issue by CoderJason123** [aspnet/AspNetCore#5786]
Hello.  So there's a ton of information regarding cookies and expiration, and the ticket vs the cookie containing the ticket.  I get that.

I just need my users to be able to stay logged in, for let's say for 8 hours, if they choose "remember" me, which then gets passed to signinmanager.signinasync().  My "cookie" shows 2 weeks of life in the browser .. which I believe this is from the options.expiretimespan property.  I'm ok with this.

I just do not understand from other articles and logged issues how to allow that 14 day cookie to actually contain "something" (need the term please) that allows them to close the browser, re-open it in 4 hours, and have to log back in because of a 401.  What is the term i am looking for, and where can I set it to make their "credentials via the cookie" value say for 4 hours.  4 hours is probably a good example.

From more reading today -- it looks like i could maybe accomplish this by calling SignInAsync and CheckPasswordSignInAsync, instead of PasswordSignInAsync, for the sole reason of passing AuthenticationProperties containing an ExpiresUtc on the auth ticket.

I hope this is not the case, but it's extremely confusing how I make the auth good for any length of time.  Please help.

**Comment by zyofeng** [comment]
One problem I am having is for a non-persistent cookie, according to Microsoft documentation, ASPNET Core does not recognize ExpireTimeSpan setting, so if I want to have a non-persistent cookie with a sliding expiration AND an expiry timespan of 4 hours currently there is no easy way to do it?

**Comment by dazinator** [comment]
> The expiration is in the [protected] payload of the cookie, not the cookie expiration flag that the browser dev tools show you.

This confused me. When looking at the cookie in chrome dev tools, it shows an expirtation date for two years time. Yet I set an expiration for 1 minute for authentication tickets. I am just wondering - does the cookie still need to be submitted for some reason when the auth ticket expires, or should these two dates be the same!?

**Comment by blowdart** [comment]
Closing as an old issue as it's pretty much by design.
