### ISSUE TITLE
Invalid Token Error when hosted on thrid-party Server

### ISSUE THREAD

**Issue by AdamAnandUS** [aspnet/AspNetCore#5788]
var result = await _userManager.ConfirmEmailAsync(user, code);

This code will never work and always ends up with "Invalid Token" when hosted from a third-party hosting provider where there is no RDP and where I cannot change any IIS Server Settings. Even if you submit the token manually using a POST instead of GET it will fail. I have used encode/decode and examined the token thoroughly.

It works perfectly on the local development machine and always fails on the hosted server.

**Comment by vovikdrg** [comment]
I do have similar issue....https://stackoverflow.com/questions/54411260/aspnetcore-correlation-failed-when-facebook-or-google-login-and-invalid-token-wh

**Comment by bed007** [comment]
Having the same random issue...

**Comment by blowdart** [comment]
Closing as old
