### ISSUE TITLE
RoleManager.UpdateRole caused  EF ChangeTracker already being tracked exception

### ISSUE THREAD

**Issue by tatarincev** [aspnet/AspNetCore#5795]
## Steps to reproduce:
```
var trackedRole = await RoleManager.FindByNameAsync("admin");
var nonTrackedRole = new Role { Id = trackedRole .Id, Name = trackedRole .Name };
await RoleManager.UpdateAsync(nonTrackedRole );
```
Got the exception
`value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.'`

## Assumption 
I understand the main reason for this issue but have just wanted to clarify whether the team is going to do something about this?

**Comment by blowdart** [comment]
Closing as old
