### ISSUE TITLE
Alternative to AuthenticationResponseGrant?

### ISSUE THREAD

**Issue by aneequrrehman** [aspnet/AspNetCore#5797]
Is there any alternative to the following code in AspNet Core 2?

```
var identity = HttpContext.User.Identity as ClaimsIdentity;
identity.RemoveClaim(Identity.FindFirst("AnnounceCount"));
identity.AddClaim(new Claim("AnnounceCount", "Updated Value"));
var authenticationManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
authenticationManager.AuthenticationResponseGrant = new AuthenticationResponseGrant(new ClaimsPrincipal(identity), new AuthenticationProperties() { IsPersistent = true });
```

I would like to change some User Principal values inside the cookie and I do not intend to persist those in the database. Is something like the above code possible in the Asp Net Core version 2? I looked into `OnValidatePrincipal`, `IClaimsTransformation` implementations, but both of those don't fit my needs. Am I missing something here?

Thanks

**Comment by blowdart** [comment]
The authentication manager does not exist in Core. Instead we recommend using identity server.
