### ISSUE TITLE
Wrong media type

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/AspNetCore#5800]
The JSON file to download is served with the file type `text/json`. The proper media type is `application/json`.

https://github.com/aspnet/Identity/blob/release/2.1/src/UI/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs#L70

Since it sets the "Content-Disposition" to "attachment" perhaps `JsonResult` could be used instead of `FileContentResult`, else perhaps there is an overload to specify it to be served as an attachment with a filename.

**Comment by HaoK** [comment]
PR was moved to 5.0

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/AspNetCore/pull/14203
