### ISSUE TITLE
Why isn't MemoryStream in DataProtectionTokenProvider disposed?

### ISSUE THREAD

**Issue by Ztarbox** [aspnet/AspNetCore#5810]
This question is a duplicate from https://github.com/aspnet/AspNetIdentity/issues/7

But since core has more contributors, I reissue it over here:
The `MemoryStream `in `GenerateAsync `and `ValidateAsync `are both not disposed.
https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/src/Identity/DataProtectionTokenProvider.cs#L72
Also the disposing by the `BinaryReader `and `BinaryWriter `is "disabled" through setting the `leaveOpen `parameter to `true`.
https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/src/Identity/DataProtectionTokenProvider.cs#L174

Shouldn't the `MemoryStream `be disposed, cause we don't need him anymore?

**Comment by blowdart** [comment]
@HaoK can you review the PR please? This got lost :(

**Comment by CBaud** [comment]
I'm not trying to steal @zachesposito's thunder, but jumping in since this hasn't been touched for a while.

**Comment by davidfowl** [comment]
Disposing a MemoryStream is pretty much a noop.

**Comment by CBaud** [comment]
> Disposing a MemoryStream is pretty much a noop.

True, but that is an implementation detail. As a class that implements IDisposable, the intended contract is for the object to get disposed when it is no longer needed. Ignoring that abstraction creates tighter coupling. Enforcing the contract makes this class more resilient against changes to the design of MemoryStream. But that's just my 2 cents.

**Comment by blowdart** [comment]
Closing as we didn't take the PR because it doesn't really give us anything
