### ISSUE TITLE
Test failure: CanVerifyPhoneNumber

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#5813]
This test [fails](http://aspnetci/viewLog.html?buildId=524549&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
Assert.False() Failure
Expected: False
Actual:   True
   at Microsoft.AspNetCore.Identity.Test.UserManagerSpecificationTestBase`2.CanVerifyPhoneNumber() in /_/src/Specification.Tests/UserManagerSpecificationTests.cs:line 1682
--- End of stack trace from previous location where exception was thrown ---
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
Closing because old.
