### ISSUE TITLE
Use inferred names in RCL Identity templates

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore#5814]
VS Intellisense suggests [Use inferred names](https://docs.microsoft.com/en-us/visualstudio/ide/common-quick-actions#use-inferred-names)

![image](https://user-images.githubusercontent.com/3605364/43803816-b9ce3254-9a4e-11e8-8490-1da9a2655f5b.png)

![image](https://user-images.githubusercontent.com/3605364/43803890-fc75f5f6-9a4e-11e8-8b31-a3f569575727.png)

Should I make a PR to use inferred member names in these anon types?

CBA (Cost Benefit Analysis)
Benefit: VS users aren't distracted by intellisense suggestion.
Cost: That's a lot of work to review and risk of breaking something for cosmetic reasons. Most customers don't generate these templates, and those who do can make changes.

[Login page](https://github.com/aspnet/Identity/blob/master/src/UI/Areas/Identity/Pages/Account/Login.cshtml.cs#L94)

**Comment by blowdart** [comment]
We're closing this issue as its so old.
