### ISSUE TITLE
The total size of an index or primary key cannot exceed 900 bytes.

### ISSUE THREAD

**Issue by fishingry** [aspnet/AspNetCore#5816]
The default length of `UserId` and `RoleId` should not be 450, it's a `Guid` by default, so the size should match the default value as well.

Once if I need UserId as a foreign key and if it's part of multiple primary keys, MS SQL throws this error:

> The total size of an index or primary key cannot exceed 900 bytes.

For example, table Customer, 2 primary keys:

1.     UserId(nvarchar(450)),   --PK, FK. it does not work even if changing length to 100!
2.     CustomerTypeId(int),   --PK, FK. CustomerType is another table
3.     it will be worse if I had more PKs and FKs

I don't want to customize anything about Identity Framework tables, I want keep using default setup.

**Comment by blowdart** [comment]
We believe we've fixed this for 3.0

**Comment by Inumedia** [comment]
@blowdart is there a commit that can be referenced that contains the fix somewhere?

Sorry for the ping, but we've found a few similar issues relating to this that all seem to say they're fixed but have no link to the actual fix.

Thanks

**Comment by blowdart** [comment]
Honestly no, hence the wooly worded. We (well, the devs) did some work around this and believe they've got everything, but it was multiple PRs, including things in EF, so I can't just point and say here it is.

The only thing I can suggest is testing against the next 3.0 preview release.

**Comment by dongdong-yang** [comment]
I created an asp.net core 3.0 website with individual authentication, but all those Ids are this::

b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");
