### ISSUE TITLE
Compiler error CS0433 caused by duplicate types: IdentityServiceCollectionExtensions

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#5818]
We have two types in the different assemblies with the same name. This can lead to unresolvable compiler errors when referencing Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionExtensions

> error CS0433: The type 'IdentityServiceCollectionExtensions' exists in both 'Microsoft.AspNetCore.Identity, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.Extensions.Identity.Core, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

https://github.com/aspnet/Identity/blob/release/2.1/src/Identity/IdentityServiceCollectionExtensions.cs
https://github.com/aspnet/Identity/blob/release/2.1/src/Core/IdentityServiceCollectionExtensions.cs

**Comment by HaoK** [comment]
Per discussion with @ajcvickers previously we decided this wasn't worth doing since it caused binary breaking changes even in our own template tests
