### ISSUE TITLE
Usage of IdentityRole

### ISSUE THREAD

**Issue by feldrim** [aspnet/AspNetCore#5819]
I know claims are the best practice here but there are some cases where Roles are needed. And I have checked out issues, yet couldn't find any answer. It might be my mistake though.

Although Identity namespace has IdentityRole class, 

1. `Microsoft.AspNetCore.Authorization.AuthorizationPolicyBuilder` does only have `RequireRole(IEnumerable<string> roles)` and `RequireRole(params string[] roles)`, which obviously accepts string as parameter.
2. `System.Security.Claims.ClaimsPrincipal` does only have `IsInRole(string role)`, which also accepts string as parameter.

I have added my own IdentityRole class where some audit properties like CreatedAt, CreatedBy etc. and had to inherit those two classess implementing my own IdentityRole. But at some points it had lead me to reimplement whole Identity assembly, which is a totally bad idea.

While there is IdentityRole class, why we use string as roles?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
