### ISSUE TITLE
Improve UserManager accessibility

### ISSUE THREAD

**Issue by jamiewest** [aspnet/AspNetCore#5821]
I was trying to override the `CreateAsync` method [here ](https://github.com/aspnet/Identity/blob/ed28df1236db01d75463f40bcf58d9e960a206a9/src/Core/UserManager.cs#L466-L483) but I lose access to `UpdateSecurityStampInternal(TUser user)` and `GetUserLockoutStore()`. It would be helpful to make the stores as well as the updating of the security stamp accessible on derived classes.

**Comment by blowdart** [comment]
Those are internal implementation helpers and not are designed for wider use.
