### ISSUE TITLE
License headers incorrect

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#5825]
While working on updating Identity to the newest jquery.validation.unobtrusive I noticed that the license headers [on some files](https://github.com/aspnet/Identity/search?l=C%23&q=%22Copyright+%28c%29+Microsoft%22) doesn't match, reporting that the license is held by Microsoft instead of the .NET Foundation.

CC @Eilon for license issues, @javiercn since we already talked about this a bit.

**Comment by blowdart** [comment]
This files don't exist any more
