### ISSUE TITLE
Microsoft.AspNetCore.Identity.EntityFrameworkCore should not reference Microsoft.AspNetCore.Identity

### ISSUE THREAD

**Issue by soargon** [aspnet/AspNetCore#5827]
![1](https://user-images.githubusercontent.com/775878/46988744-a7df5e00-d12c-11e8-9455-2dd6c629f0fb.png)
![2](https://user-images.githubusercontent.com/775878/46988745-a9a92180-d12c-11e8-9a9a-6cafc20327c9.png)

**Comment by HaoK** [comment]
@ajcvickers is this something worth doing if it causes some friction, apps that were just relying on the EF package to also bring along identity will need to be updated to explicitly bring in the core package with this change.  Maybe not worth doing, thoughts?

**Comment by ajcvickers** [comment]
@HaoK I think it's worth it for 3.0, given that we changing a few things like this already. (For example, pulling EF out of the shared framework.) We should document/announce it as a break.
