### ISSUE TITLE
Null SecurityStamp results in in always invalid token.

### ISSUE THREAD

**Issue by LindaLawton** [aspnet/AspNetCore#5830]
If a user has a SecurityStamp of null and SupportsUserSecurityStamp is true.  The token is created with "" as the stamp.     [L82](https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/src/Identity/DataProtectionTokenProvider.cs#L82)

However when it is validated Its compared against null resulting in always false validation  [L135](https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/src/Identity/DataProtectionTokenProvider.cs#L135)

**Sugestions**

Either the create token should create a stamp for the user if SupportsUserSecurityStamp is true and the stamp is null.    Or the compare in the validation should check for null and set it to space if it is.

**pull request**

I have a fix for this that I can submit as soon as GitHub is stable.  (tomorrow)

**Comment by blowdart** [comment]
Haok forgot to close it :)

**Comment by weitzhandler** [comment]
In my scenario, security stamps are enabled, but I'm checking the DB and there is a security stamp for the user, however, `GetSecurityStampAsync` returns null, why is that?
