### ISSUE TITLE
EmailConfirmationToken generated from UserManager does not reflect user's email address

### ISSUE THREAD

**Issue by jijiechen** [aspnet/AspNetCore#5834]
The token generated by `UserManager.GenerateEmailConfirmationTokenAsync` does not reflect current email address of the user, and no email address assertion is performed when validating a  confirmation token.

Therefore the user is able to "confirm" his/her updated email address (B) by following a link containing a token generated before the changing is made when the email address was actually (A) if he/she changes his/her email address to (B).

This causes some risk that a user could "confirm" an email address doesn't really owned by him/her unless application blocks further email address changing before a pending confirmation completes.

**Comment by HaoK** [comment]
@jijiechen the reason we didn't embed the email, is because as soon as something security sensitive (email/phone number/username) is changed, all old tokens should be invalidated.

So already today, if you generate 5-6 confirm email links.  As soon as one is verified via a successful ChangeEmail, that should invalidate all of the other tokens.

Is this not what you are seeing?  Or is your flow different/using different APIs?

**Comment by jijiechen** [comment]
I see. Thanks for your explanation.
Just saw source of [DataProtectorTokenProvider](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Core/src/DataProtectorTokenProvider.cs#L80) class a second time. You are correct, issued tokens will be revoked automatically on security sensitive (email/phone number/username) changed since these changes will cause the security stamp to change.

But this rely on the system supporting security stamps which could be false in certain cases, especially in a customized integration with AspNetIdentity.

**Comment by HaoK** [comment]
Yeah that's the point of the security stamp, if your app doesn't choose to implement the security stamp, you will need to mitgate the security issues that arise from not having it (like this one)

**Comment by jijiechen** [comment]
So can I understand it as the security stamp functionality is a must have when one wants to provide his own implementations of the stores and when he wants to use the token validation mechanism? 
In my case, I didn't implement a `SecurityStampStore`, so the checking of `SupportsUserSecurityStamp` returned `false`, and the security stamp mechanism did not work.

If so, then it's better to have some kind of documentation about this point. If there already is such doc, please share it out?

Not only my case, but I also found some other threads discussing this confusing.

> https://github.com/aspnet/Identity/issues/598
> ASP.NET Identity generates tokens (e.g. email confirmation, password reset) even when User.SecurityStamp is null 


> https://stackoverflow.com/a/29926407/1817042
> It's interesting that the GenerateEmailConfirmationToken returned a token without complaining about the lack of security stamp, but that token could never be validated.
