### ISSUE TITLE
Make the presence of Identity UI more explicit in the starter template or documentation

### ISSUE THREAD

**Issue by enumjorge** [aspnet/AspNetCore#5837]
I just started looking into authentication for Razor pages, and I found the experience with the starter template to be very confusing. I saw that there's already a couple of GitHub issues related to this, but I think the experience still needs some work. [This post on StackOverflow](https://stackoverflow.com/questions/50802781/where-are-the-login-and-register-pages-in-an-aspnet-core-scafolded-app) exemplifies exactly what I went through earlier today. I wanted to share some feedback.

The idea of packaging UI in a library, especially UI as involved as authentication, is intriguing. But it hasn't been done in an ASP.net template before (that I'm aware of), so when you create a starter project and you see register and login forms that appear nowhere in your project files, it's quite disorienting. Like the poster in the StackOverflow question, I searched for that string to find the source, but found nothing. Other pages like the landing page, About, etc. do exist, but the account pages are there as if by magic.

The source of the UI, the AddDefaultIdentity statement in Startup.cs, gives no hints that it comes with UI included. The previous method of including AddDefaultUI in your service configuration at least had UI in the name.

Mentioning the existence of Identity UI in the documentation or somewhere in the template would help. I'm not sure what the main entry point to Razor pages is as far as documentation goes, but I was using this article: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity). That might be a good place for a heads up about this new thing called Identity UI, which is the component that causing those authentication forms to appear. But you may be aware of a better place to put it.

**Comment by danroth27** [comment]
> @danroth27 do you think just a comment above AddDefaultIdentity would be sufficient?

I'm fine with that, but it's really @blowdart's call.

**Comment by blowdart** [comment]
I already said a comment would do.

**Comment by blowdart** [comment]
Comment should read as

/// .addDefaultUI embeds web pages to support login, logout and other identity functions without having to create pages in your project.
/// For more details see https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity
/// To create pages and code in your project rather than use the library see https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity

**Comment by javiercn** [comment]
We can close this now as the default experience for templates already includes .AddIdentityUI with the framework version.
