### ISSUE TITLE
Bug: doesn't check duplicated email while changing user's email address

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#5839]
When I call UserManager.SetEmailAsync(), it doesn't validate whether there's duplicated email address in database which could cause more than one users having the same email address.

If there're any duplicated email addresses in database, the UserManager.FindByEmailAsync() will not working properly -- it only return one result but not all matching results.

Therefore, it's necessary to validate duplicated email address while creating user and changing user's email address.

**Comment by blowdart** [comment]
That would be a rather large breaking change I'm afraid, so it's not one we're willing to make.

**Comment by Janidbest** [comment]
> But I think that the FindByEmailAsync should return an IEnumerable<TUser>, but not TUser.

If the above is a breaking change, can we atleast have a method in the usermanager to check duplicate email and duplicate username. Currently I have to use `userManager.FindByEmailAsync`  to see if the email already exists before generating the change email token.  This method selects a full user, which is unwanted select queries. 

It make sense to reject the user request to change email address before generating the token rather sending email and when the user come through the link, `userManager.ChangeEmailAsync` is the one verifying the duplicate emails and its a long process.
