### ISSUE TITLE
Add AddClaimsAsync to RoleManager

### ISSUE THREAD

**Issue by Sigvaard** [aspnet/AspNetCore#5843]
`UserManager` has two methods for adding claims (`AddClaimsAsync` and `AddClaimAsync`) but `RoleManager` has only one method (`AddClaimAsync`).

If I'm not wrong calling `AddClaimAsync` in a loop will result in multiple queries to the database?

Calling `AddClaimsAsync` should add multiple claims in 1 query?

**Comment by blowdart** [comment]
This is the first request we've had for this, and it requires an interface change, which is a big change for little value, so I'm closing this as "by design"
