### ISSUE TITLE
RefreshSignInAsync could happen with a different user

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/AspNetCore#5844]
Related: https://github.com/aspnet/Identity/issues/1900

Instead of reiterating what was already said there, we're using it for a different goal, we allow delegated requests in certain cases, these however end up in the same code path which will call refresh.

Could we think about a way to guard the SignInAsync call inside RefreshSignInAsync, e.g. check in an agnostic as possible way that the currently logged in user is the same as the passed in user, and throw otherwise? 

That wouldn't solve my problem per se, I'd want to introduce a condition around this anyway if it'll throw but it will make people aware of this api's pitfalls.  

/cc @blowdart (I'm obviously not the first one that finds this api highly unprincipled and frankly dangerous, mixing in the previous auth properties with any new user you pass in, and to call it  "Refresh")

**Comment by blowdart** [comment]
I don't know if I'd go as far as calling it dangerous, e.g. it does support a user name change, which is a scenario I can see people using.

**Comment by blowdart** [comment]
Also how would you do this check? You can't rely on any claim being present, be it username or a uuid or anything else, validators are generic and not linked to identity.

I'm going to fall back to the documentation here I'm afraid as there's no clear foolproof way to do this.
