### ISSUE TITLE
Nuget Package Dependencies NETCoreApp 3.0, please change to NETStandard 2.0

### ISSUE THREAD

**Issue by Olbrasoft** [aspnet/AspNetCore#5845]
https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.EntityFrameworkCore/3.0.0-preview-18579-0056

**Comment by blowdart** [comment]
Yes, it's related to the announcement. No we're not doing it, but a discussion is pending.

**Comment by gablemire** [comment]
I have currently upgrading to .NET 3.0 preview 8. This is a huge breaking change. I was planning to set my library assemblies to .NET Standard 2.1, but since my DbContext inherits from IdentityDbContext, I can't. What is the upgrade path then if this library targets `netcoreapp3.0`?
