### ISSUE TITLE
Why is there a generic parameter definition TUser for PasswordHasher when it is not used?

### ISSUE THREAD

**Issue by john-luke-laue** [aspnet/AspNetCore#5847]
Not sure if this is the place for this type of question, but I'm curious as to why TUser generic type parameter is used in PasswordHasher<TUser> class when TUser is not used internally in the class anywhere. 

https://github.com/aspnet/Identity/blob/master/src/Core/PasswordHasher.cs#L17

TUser is used to define a parameter [here](https://github.com/aspnet/Identity/blob/master/src/Core/PasswordHasher.cs#L94) and [here](https://github.com/aspnet/Identity/blob/master/src/Core/PasswordHasher.cs#L172), but those parameters are never used.

**Comment by blowdart** [comment]
As brock says. So closing.
