### ISSUE TITLE
Support attaching to an existing request queue

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5866]
Http.Sys has an API where you can attach to an existing request queue by name rather than creating a new one. In this mode you'd assume the queue was already configured so most settings would be ignored (e.g. prefixes, timeouts, auth, etc.).

This can be used in conjunction with the HttpWaitForDemandStart API where a central dispatcher sets up the queue, listens for requests, and then activates the site when the first request arrives.

Complications:
- [ ] Prefixes / PathBase / HotAdd&Remove
- [ ] Auth / Challenge
- [ ] Ignored Options (Timeouts, queue length limit, etc.)

**Comment by Tratcher** [comment]
@shirhatti removing from backlog for re-triage. There's a partner request for this in 3.1.

**Comment by Tratcher** [comment]
Squashed my old branch and moved it here: https://github.com/aspnet/AspNetCore/commit/2c4824398786964af7bb0a0a470235946cab6de9

@bkatms already manually rebased most of it in their PR. Still need to diff them and pull in the tests.

**Comment by Tratcher** [comment]
Thanks for the help @bkatms. This should show up in a 3.1 nightly build in the next few days (https://github.com/dotnet/core-sdk). https://maestro-prod.westus2.cloudapp.azure.com/128/https:%2F%2Fgithub.com%2Fdotnet%2Fcore-sdk/latest/graph should show when.

**Comment by bkatms** [comment]
My pleasure.  I look forward to picking it up.

Cheers, Brian
[he/him]
