### ISSUE TITLE
Allow 304 responses with a Content-Length but no body 

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5878]
(Mirrored from https://github.com/aspnet/KestrelHttpServer/issues/2099)

304 Not Modified responses are not allowed to contain a body, but they may still contain an informative Content-Length header similar to a Head response.

https://tools.ietf.org/html/rfc7230#section-3.3.2
>  A server MAY send a Content-Length header field in a 304 (Not
   Modified) response to a conditional GET request (Section 4.1 of
   [RFC7232]); a server MUST NOT send Content-Length in such a response
unless its field-value equals the decimal number of octets that would
   have been sent in the payload body of a 200 (OK) response to the same
   request.
   A server MUST NOT send a Content-Length header field in any response
   with a status code of 1xx (Informational) or 204 (No Content).  A
   server MUST NOT send a Content-Length header field in any 2xx
   (Successful) response to a CONNECT request (Section 4.3.6 of
   [RFC7231]).

MVC started doing this in 2.0 and running into the `Response Content-Length mismatch: too few bytes written (0 of 42).` error.
https://github.com/aspnet/Mvc/issues/6875
They've patched it for 2.0.1
https://github.com/aspnet/Mvc/issues/6887

**Comment by aspnet-hello** [comment]
Thanks for your feedback. We appreciate your letting us know about the problem you've encountered or suggestion but we are not planning to take further action on this issue because our focus has been on issues with significantly higher customer interest and issues impacting a broad number of customers.
