### ISSUE TITLE
Troubleshooting intermittent 503 errors

### ISSUE THREAD

**Issue by chandimar001** [aspnet/AspNetCore#5889]
We are using WebListener version 1.1.4. We have an issue where approximately 1% of requests return a 503 error. We see these 503 errors in our GTM logs. I can't find anything in our application logs where requests have high latency that could result in timeouts. So I want to see if WebListener got these requests and what it responded with. 

1. I see the following logs. I assume these are from .NET core itself, and not necessarily from WebListener. If so, how do I enable WebListener logs?

> Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 370.1088ms 200 application/json; charset=utf-8

2. We are using the default values for MaxAccepts and RequestQueueLimit. The intermittent 503 errors occur even during low traffic periods when CPU is under 20%, so I assume it can't be caused by these default values.

3. A lot of online searches for 503 errors point at Application Pool configurations when using IIS. Does WebListener have a similar concept of Application Pools that might need configuring?
https://weblog.west-wind.com/posts/2006/Dec/04/503-Service-Unavailable-in-IIS-7-watch-those-Application-Pools

4. Is there a way to enable something similar to "Failed Request Tracing" in Web Listener?
https://blogs.iis.net/richma/502-3-bad-gateway-the-operation-timed-out-with-iis-application-request-routing-arr

5. Any other thoughts or suggestions or greatly appreciated :)

**Comment by aceven24** [comment]
Ever get any conclusions on this, we are experiencing the same thing, but with IIS and ASP.NET Web API.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
