### ISSUE TITLE
Identify and fix tests that do synchronous request and response IO

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#5899]
In preparation for [defaulting AllowSynchronousIO to false](https://github.com/aspnet/KestrelHttpServer/issues/1928) we should identify and fix tests that call synchronous request and response Stream APIs.

Most Universe functional tests use Hosting's TestHost which doesn't need to change to disallow synchronous IO, but doing so allows us to potentially identify use cases (such as [using DeflateStream](https://github.com/aspnet/BasicMiddleware/issues/247)) that make it difficult to avoid using synchronous IO.

Below are the test project that I saw fail when I [modified TestHost](https://github.com/aspnet/Hosting/compare/halter73/no-sync) not to allow sync request and response stream operations (excluding Flush). [Here's the output showing each failed test](https://gist.github.com/halter73/76e719b92884af65299e3aac96595f91).

```
[xUnit.net 00:00:04.0099135]   Finished:    Microsoft.AspNetCore.TestHost.Tests
Total tests: 51. Passed: 47. Failed: 4. Skipped: 0.

[xUnit.net 00:00:01.8295296]   Finished:    Microsoft.AspNetCore.Buffering.Tests
Total tests: 8. Passed: 7. Failed: 1. Skipped: 0.

[xUnit.net 00:00:03.3003836]   Finished:    Microsoft.AspNetCore.ResponseCaching.Tests
Total tests: 269. Passed: 231. Failed: 38. Skipped: 0.

[xUnit.net 00:03:20.8983023]   Finished:    ServerComparison.FunctionalTests
Total tests: 57. Passed: 34. Failed: 5. Skipped: 18.

[xUnit.net 00:00:03.9879504]   Finished:    Microsoft.AspNetCore.Diagnostics.Tests
Total tests: 75. Passed: 63. Failed: 12. Skipped: 0.

[xUnit.net 00:00:05.7808313]   Finished:    Microsoft.AspNetCore.Authentication.Test
Total tests: 224. Passed: 198. Failed: 24. Skipped: 2.

[xUnit.net 00:00:40.4557444]   Finished:    Microsoft.AspNetCore.Mvc.FunctionalTests
Total tests: 1015. Passed: 701. Failed: 314. Skipped: 0.

[xUnit.net 00:00:03.8723760]   Finished:    Microsoft.AspNetCore.Identity.InMemory.Test
Total tests: 190. Passed: 186. Failed: 4. Skipped: 0.

[xUnit.net 00:03:16.7483553]   Finished:    Entropy.FunctionalTests
Total tests: 270. Passed: 135. Failed: 25. Skipped: 110.
```

**Comment by Tratcher** [comment]
Dealt with back in https://github.com/aspnet/AspNetCore/issues/7644
