### ISSUE TITLE
Don't swallow IHostedService.StartAsync exceptions

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/AspNetCore#5900]
As discussed briefly in https://github.com/aspnet/Hosting/issues/1085#issuecomment-305717425 I propose that the [HostedServiceExecutor](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostedServiceExecutor.cs#L24) should not catch exceptions in StartAsync.

By swallowing exceptions, the hosting-layer forces all services to be optional which is undesired IMO. By not swallowing exceptions we give services the option to decide this on its own. If a service is truly optional, it can swallow exceptions in its own StartAsync code.

I also think that StartAsync-exceptions should not be combined into an AggregateException. Instead it should just stop on the first exception.

One thing to consider is that right now this code is executed AFTER the server has been started. Not sure what effects this has when exceptions are no longer caught?!

I still hold the opinion that hosted services should be started before the server is started (a service could always decide to kick off another task in its StartAsync if it wants to be delayed) but this has also been discussed briefly in #1085 and declined.

**Comment by muratg** [comment]
@davidfowl would you be OK getting a breaking change here in 3.0?

Folks, we may accept PRs for this. If you're interested please let me know!

**Comment by davidfowl** [comment]
I'll take this one for 3.0

**Comment by cwe1ss** [comment]
Thank you very much, David!

**Comment by srollinet** [comment]
Workaround for the 2.x version

    public static class ServiceCollectionUtils
    {
        public static void AddCriticalHostedService<TService, TImplementation>(this IServiceCollection services)
            where TService : class
            where TImplementation : class, IHostedService, TService
        {
            services.AddSingleton<TService, TImplementation>();
            services.AddHostedService<CriticalHostedServiceWrapper<TService>>();
        }

        private class CriticalHostedServiceWrapper<TService> : IHostedService
        {
            private readonly IHostedService _hostedService;
            private readonly ILogger _logger;

            public CriticalHostedServiceWrapper(TService hostedService, ILoggerFactory loggerFactory)
            {
                _hostedService = (IHostedService)hostedService;
                _logger = loggerFactory.CreateLogger(_hostedService.GetType());
            }

            public async Task StartAsync(CancellationToken cancellationToken)
            {
                try
                {
                    await _hostedService.StartAsync(cancellationToken);
                }
                catch (Exception e)
                {
                    _logger.LogCritical(e, "Cannot start critical service. The application will exit.");
                    Environment.Exit(1);
                }
            }

            public Task StopAsync(CancellationToken cancellationToken)
            {
                return _hostedService.StopAsync(cancellationToken);
            }
        }
    }

**Comment by AsValeO** [comment]
Looks like behavior still the same in 3.0.

**Comment by davidfowl** [comment]
Update to use the generic host?

**Comment by AsValeO** [comment]
It works with generic host. Damn, I'm so far behind..
