### ISSUE TITLE
Consider adding a IWebHostBuilder.Configure overload that takes a WebHostBuilderContext

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/AspNetCore#5903]
Would be nice/consistent to have this additional overload as it also exists for `ConfigureAppConfiguration` and `ConfigureServices`. It would allow us to access the configuration and environment info without having to resolve it ourselves from DI.

**Comment by danielmarbach** [comment]
Sent in a [PR ](https://github.com/aspnet/AspNetCore/pull/8697)that addresses this. I'm still downloading VS2019RC and see if I can even compile my changes locally but the PR is there
