### ISSUE TITLE
IStartupConfigureServicesFilter is not executed when Configure is used

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#5906]
https://github.com/aspnet/Hosting/blob/872fc80d567892096f6cd6925600285570d866fe/test/Microsoft.AspNetCore.Hosting.Tests/StartupManagerTests.cs#L141-L166

There no reason why we can't do it except internal implementation details.

/cc @Tratcher @javiercn

**Comment by muratg** [comment]
@javiercn is this going in 3.0.0?

**Comment by javiercn** [comment]
@muratg We'll do something different for 3.0 as this doesn't apply with GenericHost.
