### ISSUE TITLE
Display package version instead of assembly version on error page

### ISSUE THREAD

**Issue by glennc** [aspnet/AspNetCore#5913]
The error page we have embedded shows the assembly version of hosting. But AFAIK that's the only place we display that information. If I depend on preview1-final today and then look a the error page it shows me a build number. Which immediately confused me and made me think I had made a mistake about depending on a pre-release somewhere.

Can we embed the `-final` version and use that here instead or as well as the build number?

**Comment by muratg** [comment]
This would be really nice to help customers with diagnostics. Hope we can get some time do to this in 3.0.0.

Somewhat related: https://github.com/aspnet/AspNetCore/issues/5891

**Comment by NatMarchand** [comment]
Hey there, I wanted to grab the task but while digging in the code I noticed that it should already be the case. We can see here that the version is the AssemblyInformationalVersion.
https://github.com/aspnet/AspNetCore/blob/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0/src/Hosting/Hosting/src/Internal/WebHost.cs#L256

Therefore it's more or less the NuGet package version (eg. version 2.2.0-rtm-35687 for package 2.2.0 and 3.0.0-preview-19075-0444 for the latest 3.0 preview)

**Comment by anurse** [comment]
Yep, looks like the version numbers are accurate. I'm going to close this.

![image](https://user-images.githubusercontent.com/7574/55267051-32300000-523d-11e9-8d37-1d7508b35627.png)

**Comment by anurse** [comment]
The `V4.0.0.0` is the version of System.Runtime, which is somewhat relevant, if a little confusing in this case. The full version is shown properly in the `FrameworkDescription` value which displays `.NET Core 3.0.0-preview4-...`
