### ISSUE TITLE
Parent Request Id is mislabeled as Correlation Id in log scope

### ISSUE THREAD

**Issue by ngbrown** [aspnet/AspNetCore#5918]
For the upcoming for ASP.Net Core 2.1; pull #1138 added to the log scope a `CorrelationId`, but the contents are only the parent request identifier and does not appear to be set if there was no parent request (no `Request-Id` header in the incoming HTTP request).

There is documentation/specifications (mostly by @lmolkova) around these terms at:

* [HttpCorrelationProtocol](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HttpCorrelationProtocol.md)
* [FlatRequestId](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/FlatRequestId.md)
* [HierarchicalRequestId](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HierarchicalRequestId.md)

Specifically in the [Activity User Guide](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md), it says:

> When application calls external dependency to complete an operation, it may need to pass some of the context (e.g. ___correlation id___) [emphasis added] along with dependency call to be able to correlate logs from multiple service.

I see that the expectation is that in the logs, there will be a "correlation id" of the context, or `CorrelationId` if you will, that can be used to link the logs entries across multiple services handling a single user request.

In the current preview code, the Log scope outputs a `CorrelationId` which is the value of an incoming header `Request-Id`, and only if that header is set.  This is not useful for seeing the entire request across multiple services in the logs.  What is needed is adding to the log scope the root request id to the log scope of all services involved in handling the request, including within the root service that generated the first request id.

**Comment by muratg** [comment]
@pakrym thoughts on the scope of this one? You agree that removing it from logging scope is the right approach?

**Comment by pakrym** [comment]
I, unfortunately, don't have enough context on this. Would need to discuss with @davidfowl as it seems he understands what's wrong here.

**Comment by lkts** [comment]
I want to agree here that `CorrelationId` is confusing in current implementation because it is always `null` for application which serves "initial" requests. I would expect it to be `Activity.Current.Id` as mentioned here.

**Comment by anurse** [comment]
Epic https://github.com/aspnet/AspNetCore/issues/8924

**Comment by anurse** [comment]
Needs similar design to https://github.com/aspnet/AspNetCore/issues/5926

**Comment by davidfowl** [comment]
This is done now

**Comment by davidfowl** [comment]
See https://github.com/aspnet/AspNetCore/issues/9491
