### ISSUE TITLE
Startup assembly StartupBootstrapper failed to execute

### ISSUE THREAD

**Issue by Bazeloth** [aspnet/AspNetCore#5919]
Im getting this error in my logs currently:

2018-04-23 18:10:25.818 +00:00 [Fatal] Hosting startup assembly exception
System.InvalidOperationException: Startup assembly StartupBootstrapper failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---

Im using the following version of microsoft.aspnetcore:
\.nuget\packages\microsoft.aspnetcore\2.0.1\lib\netstandard2.0\Microsoft.AspNetCore.dll

Am i missing something or is this a known bug? Im hosting this in an Azure App Service.

**Comment by joshmouch** [comment]
@clguimanMSFT I think I was previously confusing a "self-contained" dotnet application with a "self-contained" asp.net core application that uses full framework (4.7.2).  When your Asp.net Core app uses the full framework, does "self-contained" vs. "framework dependent" even apply?  If not, then I'm getting the exceptions noted above when deployed using full framework.

**Comment by clguimanMSFT** [comment]
When the app targets the full frameworks it's still considered a self contained app, so the limitation still applies.

**Comment by joshmouch** [comment]
@clguimanMSFT Thanks!  So to clarify: Any ASP.Net Core application that targets full framework (e.g. .Net 4.7.2) cannot use some of the App Insight features (e.g. App Insights Profiler).

**Comment by clguimanMSFT** [comment]
@joshmouch the Application Insights site extension is not able to automatically inject ApplicationInsights SDK and SnapshotCollector is a self-contained app (it also includes ASP.NET Core apps that target full framework) so you need to enable those from code (https://github.com/aspnet/Hosting/issues/1398#issuecomment-387842930) 
The  Application Insights Profiler continuous web job (ApplicationInsightsProfiler3) will still be installed as long as your AppService has the 'Always On' feature turned on (it doesn't cost extra, you get billed for the App Service Plan)

**Comment by georgiosd** [comment]
I am getting this error with a `netcoreapp2.1` targeted app as well, when the App Insights extension is enabled. Any idea why?

**Comment by clguimanMSFT** [comment]
@georgiosd is it a self-contained app? If so, please read the comment above.
Otherwise please enable extra logging by following these steps (use Kudu): 
1. Update the aspnetCore node in  web.config in d:\home\sites\wwwroot with the following props:
   startupTimeLimit="3600" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout"
2. Add the following app setting: COREHOST_TRACE=1
  Once COREHOST_TRACE is enabled, your application will start very slowly, you should disable this after you collect the logs. 
3. Navigate to your website, and in the mean time look into d:\home\LogFiles. You should see a file the starts with "stdout". Wait until that file has the StartupBootsrapper error in it along with a lot of traces coming from the dotnet runtime.

Please send that file to clguiman@microsoft.com and I'll investigate the issue.

**Comment by georgiosd** [comment]
@clguimanMSFT don't know what to tell ya... I tried to re-enable and reproduce the problem but it's not happening again. Maybe some left over files conflict or something something something...

Merry Christmas!

**Comment by muratg** [comment]
Closing this issue as there's no action on ASP.NET here. @clguimanMSFT what repo (if any) folk should file bugs/discuss issues on this? Thanks.

**Comment by clguimanMSFT** [comment]
Please file future issues in [ApplicationInsights-aspnetcore](https://github.com/Microsoft/ApplicationInsights-aspnetcore)

**Comment by crookedbard** [comment]
still getting same error from Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices.
Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Reflection.RuntimeAssembly.nLoad","level":0,"line":0}
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Reflection.RuntimeAssembly.InternalLoadAssemblyName","level":1,"line":0}
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Reflection.Assembly.Load","level":2,"line":0}
{"assembly":"Microsoft.AspNetCore.Hosting, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices","level":3,"line":0}

**Comment by davidfowl** [comment]
@crookedbard can you provide me with a repro? These failures get logged but should not prevent the application from loading. 

- Are you using ASP.NET Core on .NET Framework or .NET Core?
- Do you have Application Insights configured?

**Comment by muratg** [comment]
@crookedbard Does your app fail to start? If so, could you please file another bug with your repro, and cc me and @davidfowl.
