### ISSUE TITLE
On Linux, failing to bind the address on Start generates a coredump

### ISSUE THREAD

**Issue by tmds** [aspnet/AspNetCore#5920]
When starting Kestrel on a port that is taken an exception is thrown. e.g.:

> System.IO.IOException: Failed to bind to address https://127.0.0.1:5001: address already in use

Since this exception is not handled, the runtime calls `abort` which (normally) generates a coredump (see https://github.com/dotnet/coreclr/issues/17929).

The behavior seems excessive for failing to bind the port. Maybe there should be a try/catch somewhere to turn this into a non-success process exit?
It may not be obvious these coredumps are being generated. And when seeing these dumps on their system, users may get the wrong impression dotnet failed in some bad way.

CC @davidfowl @halter73 @mikem8361

**Comment by muratg** [comment]
It doesn't look like there's any action on ASP.NET here. @davidfowl, if you disagree, please reopen.

**Comment by tmds** [comment]
To address this, either a change is needed in the runtime or in ASP.NET Core.

Proposing a change to ASP.NET Core:

Change the generic host `Run/RunAsync` method so it returns an `int` which is meant to be used as the exit code from Main.

So:
```C#
public static void Main(string[] args)
    => CreateWebHostBuilder(args).Build().Run();
```
becomes:
```C#
public static int Main(string[] args)
    => CreateWebHostBuilder(args).Build().Run();
```

This `Run` method would be the idiomatic way to write an ASP.NET Core application and connect the return value to Main.

When using this `Run` method, the ASP.NET Core app should be bound to the `ConsoleLifetime`.

There should be a another method on the host (`Start`?), that is the idiomatic way to use ASP.NET Core within an another application (e.g. WPF) that doesn't bind to the `ConsoleLifetime` (cfr https://github.com/aspnet/Extensions/issues/574).

Using the `Run` method can also deal with the `ExitCode` as needed for changes in https://github.com/dotnet/coreclr/pull/21300#issuecomment-452684375.

@Tratcher @davidfowl wdyt?

**Comment by Tratcher** [comment]
You would have to plum that through a lot of layers to get down to the server that generated the original binding error. It would also leave us with overlapping error handling mechanics.

I still don't see a reason to special case this class of errors from a framework perspective. failing to bind is fatal and if you don't want a dump for some fatal errors then you can handle those in Main.

**Comment by tmds** [comment]
> You would have to plum that through a lot of layers to get down to the server that generated the original binding error. It would also leave us with overlapping error handling mechanics.
I still don't see a reason to special case this class of errors from a framework perspective. failing to bind is fatal and if you don't want a dump for some fatal errors then you can handle those in Main.

I'm thinking of a try catch for any exception that prints the exception and turns it into a `1` exit code.

That gives you the same behavior like other stacks (ruby, node, python).

This pattern is also in the System.CommandLine package by default: https://github.com/dotnet/command-line-api/blob/750f2365800c8e894f4bc3e54bbc73dcc9623f1d/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L147.

**Comment by muratg** [comment]
@davidfowl **ping**

**Comment by halter73** [comment]
I like aligning our behavior with other stacks, but this proposal doesn't quite do that. dotnet/coreclr/issues/17929 more fully aligns behavior, right? I support doing that instead, since I don't think flowing error codes is idiomatic in C#.

**Comment by tmds** [comment]
> I like aligning our behavior with other stacks, but this proposal doesn't quite do that. dotnet/coreclr/issues/17929 more fully aligns behavior, right? I support doing that instead, since I don't think flowing error codes is idiomatic in C#.

I agree with that.

With the change in https://github.com/dotnet/coreclr/pull/21300, the Host will need to deal with setting the ExitCode (https://github.com/aspnet/AspNetCore/issues/6526). This means the C# becomes anyhow aware of exit codes. So we can't fully push it to the runtime.

This Run method would put everything in one place where we go from C# exceptions to process exit codes.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
