### ISSUE TITLE
Test deployers leaking processes

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#5921]
Recently I've noticed a lot of orphaned processes after running functional tests in IISIntegration, ServerTests, etc.. There are lots of dotnet.exe and similar left over after the test run.

Name	PID	Status	User name	CPU	Memory (private working set)	Command line	Description
dotnet.exe	9464	Running	chrross	00 	24,592 K	"dotnet" run --no-restore --framework netcoreapp2.1 -- --server.urls http://localhost:7834/  --server Microsoft.AspNetCore.Server.Kestrel	.NET Core Host

dotnet.exe	30744	Running	chrross	00 	11,604 K	"dotnet" exec "D:\github\AspNet\ServerTests\test\ServerComparison.TestSites\bin\Debug\netcoreapp2.1\ServerComparison.TestSites.dll" --server.urls http://localhost:7827/ --server Microsoft.AspNetCore.Server.Kestrel	.NET Core Host

ServerComparison.TestSites.exe	5232	Running	chrross	00 	6,704 K	"D:\github\AspNet\ServerTests\test\ServerComparison.TestSites\bin\Debug\net461\ServerComparison.TestSites.exe"  --server.urls http://localhost:8119/ --server Microsoft.AspNetCore.Server.HttpSys	ServerComparison.TestSites

These appear to be from the self-host deployer.

TaskKill doesn't work for getting rid of them, but PsKill does.

**Comment by muratg** [comment]
@Tratcher is this still an issue?

**Comment by Tratcher** [comment]
Couldn't say, I don't run those tests locally anymore. @pakrym @jkotalik have you seen this?

**Comment by pakrym** [comment]
Haven't seen much but I almost never run self-host tests. Maybe it's worth implementing the same things we did for IISExpress: https://github.com/aspnet/AspNetCore/blob/master/src/Servers/IIS/IntegrationTesting.IIS/src/ProcessTracker.cs

**Comment by muratg** [comment]
Closing this one. If we get more complaints, we'll reconsider.
