### ISSUE TITLE
Remove logging config files in deployers

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#5923]
The apphost.config files for IIS and IISExpress are ~1000 lines long. It bloats the logs significantly whenever there is a failed test. If there were modifications done to the apphost.config, maybe we can print the diff rather than the whole file.

**Comment by muratg** [comment]
More work remaining here?

**Comment by jkotalik** [comment]
The original issue has been addressed. I'll file separate issues for work related to deployers.
