### ISSUE TITLE
Make web specific IHostingEnvironment and IApplicationLifetime inherit from generic host versions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#5924]
We made the concrete implementations work this way so that you could write types that took in IHostingEnvironment and IApplicationLifetime but we didn't do it for the interfaces themselves. If you have methods that take the generic IHostingEnvironment and IApplicationLifetime, then you can't just pass the implementation you got from the web host into these methods e.g.

Library

```C#
public static class CustomEnvironmentExtensions
{
    public static bool IsCustomDevelopment(this Extensions.Hosting.IHostingEnvironment env) { ... }
}
```

ASP.NET Core app

```C#
public void Configure(IHostingEnvironment env)
{
    // This is a compile error
    if (env.IsCustomDevelopment())
    {
        
    }
}
```

See https://github.com/aspnet/Hosting/issues/1218#issuecomment-394956520 for more info.

**Comment by muratg** [comment]
@Tratcher Looks like a part of the GenericHost work.

**Comment by Tratcher** [comment]
Triage: We've decided not to inherit these.
