### ISSUE TITLE
Serialize response context as a response header

### ISSUE THREAD

**Issue by SergeyKanzhelev** [aspnet/AspNetCore#5928]
## Motivation

In distributed tracing scenarios it is not uncommon to return extra context as a response headers when possible. DiagnosticsSource Acitvity should implement API that will allow to set the [response context](https://github.com/dotnet/corefx/issues/30335). Fields populated by this API should be serialized as http response headers.

CC: @seth-capistron, @vancem, @jacpull, @lmolkova, @glennc, @davidfowl

**Comment by anurse** [comment]
To clarify, this is blocked on getting https://github.com/dotnet/corefx/issues/30335 in, right?

@lmolkova are these APIs going in to corefx? (cc @glennc)

**Comment by lmolkova** [comment]
@anurse no, at this point there is no work in corefx to support response context. @SergeyKanzhelev do we still need this?

**Comment by anurse** [comment]
Epic #8924

**Comment by anurse** [comment]
Closing as there isn't a W3C spec here yet. @SergeyKanzhelev is working on that and we can re-open when that happens.

**Comment by SergeyKanzhelev** [comment]
Let's re-open when W3C has a spec for response headers
