### ISSUE TITLE
Implement IServerAddressesFeature for TestServer

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#5931]
Using a fairly-generic 2.1 web site with `app.UseHttpsRedirection();` in its `Startup.Configure(...)` method, the following code (after discovering the site's `CreateWebHostBuilder` method) does _not_ prevent the `Failed to determine the https port for redirect.` warning from the middleware:
``` c#
var builder = (IWebHostBuilder)methodInfo.Invoke(obj: null, parameters: args);

// Enable HTTPS in case HttpsRedirectionMiddleware is in use.
builder.PreferHostingUrls(preferHostingUrls: true);
builder.UseUrls("https://localhost", "http://localhost");

using (var server = new TestServer(builder))
{
    var httpClient = server.CreateClient();
    // send a request to HTTP port e.g. client's default base address
}
```

Oddly, the warning goes away and redirection occurs if I remove the `builder.PreferHostingUrls(preferHostingUrls: true);` statement. But, it's not clear why that breaks anything.

This feels like a bug in `TestServer` per @jkotalik. Also per @jkotalik, this is likely a separate issue from #1523.

**Comment by muratg** [comment]
We don't plan to make changes here. @jchannon, please let me know if you're interested in sending a PR and we can discuss possible approaches.

cc @davidfowl
