### ISSUE TITLE
Cancellation Token parameter in BackgroundService.StartAsync is not respected

### ISSUE THREAD

**Issue by CameronAavik** [aspnet/AspNetCore#5936]
I have a suspicion that this is by design but wanted to check. I was planning to unit test an implementation of the background service I had written. To stop it looping forever in the case of a bug in my code I was looking to cancel the service after a certain amount of time. I thought that by passing in a cancellation token into the `StartAsync` and then cancelling it after 1 second, that this would work but it seems that this cancellation token is ignored.

The relevant code is [found here](https://github.com/aspnet/Hosting/blob/712c992ca827576c05923e6a134ca0bec87af4df/src/Microsoft.Extensions.Hosting.Abstractions/BackgroundService.cs#L26-L43), and I've pasted it below for convenience.

```csharp
/// <summary>
/// Triggered when the application host is ready to start the service.
/// </summary>
/// <param name="cancellationToken">Indicates that the start process has been aborted.</param>
public virtual Task StartAsync(CancellationToken cancellationToken)
{
    // Store the task we're executing
    _executingTask = ExecuteAsync(_stoppingCts.Token);

    // If the task is completed then return it, this will bubble cancellation and failure to the caller
    if (_executingTask.IsCompleted)
    {
        return _executingTask;
    }

    // Otherwise it's running
    return Task.CompletedTask;
}
```

The `cancellationToken` parameter is not used and it instead passes in a different cancellation token that is private to `BackgroundService`. I think it might be useful to combine the parameter cancellation token with `_stoppingCts`. I understand that I can call `Dispose` or `StopAsync` to cancel `_stoppingCts`, but that doesn't let me call `CancelAfter` for the behaviour I was looking for and doesn't change that the cancellation token is ignored.

**Comment by muratg** [comment]
Closing this. https://github.com/aspnet/Extensions/issues/813 is tracking work we may potentially do here.

**Comment by AndyPook** [comment]
The simplest workaround is to add await Task.Yield; as line one of ExecuteAsync.

If everything actually returns synchronously then the method never yields and StartAsync does not complete.

Another visible side-effect of this problem is that if you have a background service in an aspnet project then you never see the "Application started" logging on the console. Indicating that the bootstrap process is blocked.
