### ISSUE TITLE
Request.Host not set by Microsoft.AspNetCore.TestHost.WebSocketClient

### ISSUE THREAD

**Issue by kenlyon** [aspnet/AspNetCore#5942]
I am using a `Microsoft.AspNetCore.TestHost.TestServer` to test my application.

Whenever I use `TestServer.CreateClient()` then `HttpClient.PostAsync()`, I can see that my controller correctly has the `Request.Host` property matching `TestServer.BaseAddress`.

However, when I use `TestServer.CreateWebSocketClient()` then `WebSocketClient.ConnectAsync()`, I find that the controller's `Request.Host` is always `null`. 

This is a problem for me as I try to generate a new url relative to the requested url in the controller using `new Uri(Request.GetEncodedUrl())`. The call to `Request.GetEncodedUrl()` returns a url with no host (e,g, "http:///path/here") and `new Uri()` throws a `UriFormatException` because there's no _hostname_.

**Comment by KristianJakubik** [comment]
Hi, I would like to work on this issue. Is it still relevant?

**Comment by kenlyon** [comment]
I think it is.

**Comment by anurse** [comment]
https://github.com/aspnet/AspNetCore/commit/f2f1d7751710342d22c55edf83a01615409f2a49
