### ISSUE TITLE
Remove dependencies from the default set adding by ConfigureWebHost

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#5944]
Today we add a set of dependencies that mirror the WebHostBuilder https://github.com/aspnet/Hosting/blob/d7b9fd480765bdc01f06441f308fb288e6001049/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L270-L285. Things we may want to remove:

- ObjectPoolProvider
- DiagnosticListener/DiagnosticSource

@Tratcher @rynowak

**Comment by sandersaares** [comment]
> more pay for play

What does this phrase in the announcement mean?

**Comment by davidfowl** [comment]
@sandersaares Components that require the ObjectPoolProvider add it instead of it being added for everyone (it was only used in 3 places). Where as something like logging is user by *every* component.

**Comment by davidfowl** [comment]
> I'm not a big fan of dependencies being added by default, and I suspect there are going to be more cases where dependencies are added like so, is there going to be a wider review to see if we can make improvements elsewhere as part of this breaking change?

Yes the dependencies listed are the ones that are problematic/unnecessary. The other dependencies are pretty much required to function.

**Comment by davidfowl** [comment]
I'm not sure we can easily remove the diagnostic source. I need to think about that one more.

**Comment by davidfowl** [comment]
Closing this as we're not going to remove (at least in the short term, the DiagnosticSource)
