### ISSUE TITLE
Expose `TestServer` as public property on `RequestBuilder`

### ISSUE THREAD

**Issue by carusology** [aspnet/AspNetCore#5947]
In order to make our integration tests cleaner, I've been all about adding extension methods to the [`RequestBuilder`](https://github.com/aspnet/Hosting/blob/2.1.1/src/Microsoft.AspNetCore.TestHost/RequestBuilder.cs). For example, to prevent issues around everyone learning for the first time that [HTTP methods are case-sensitive](https://tools.ietf.org/html/rfc2616#section-5.1.1), we can add a simple extension to make sure developers use method casing consistently.

```cs
public static class RequestBuilderExtensions {

    public static Task<HttpResponseMessage> PatchAsync(this RequestBuilder request) {
        if (request == null) {
            throw new ArgumentNullException(nameof(request));
        }

        return request.SendAsync("PATCH");
    }

    public static Task<HttpResponseMessage> PutAsync(this RequestBuilder request) {
        if (request == null) {
            throw new ArgumentNullException(nameof(request));
        }

        return request.SendAsync("PUT");
    }

    public static Task<HttpResponseMessage> DeleteAsync(this RequestBuilder request) {
        if (request == null) {
            throw new ArgumentNullException(nameof(request));
        }

        return request.SendAsync("DELETE");
    }

}
```

These are easy enough to do when the state of the `TestServer` is irrelevant for the construction of the `HttpRequestMessage`, but that's not always the case. For example, what if I want to create an extension method that sets a `Bearer` token in the `Authorization` header for a given `User`.

Here's an example xUnit test:

```cs
[Fact]
public void GetResource_ValidUser() {

    // Arrange

    var path = "path/to/resource";
    var user = new User { EmailAddress = "me@example.com", Id = "i-am-unique" };
    var request = this.TestServer.CreateRequest(path).SetUser(user);

    // Act

    var response = await request.GetAsync();

    // Assert

    Assert.Equal(HttpStatusCode.OK, response.StatusCode);

}
```

In order to create a valid `Bearer` token, I need to be able to fetch the authentication configuration that is currently being used within the `TestServer`, but because `RequestBuilder` doesn't expose it, I can't do this. Here's what I _want_ to do:

```cs
public static class RequestBuilderExtensions {

    public static RequestBuilder SetUser(this RequestBuilder request, User user) {
        if (user == null) {
            request = request.And(message => message.Headers.Authorization = null);
        } else {
            // "request.TestServer" property does not exist at this time.
            var server = request.TestServer;
            var token = CreateToken(server.Host.Services, user);
            var value = new AuthenticationHeaderValue("Bearer", token);

            request = request.And(message => message.Headers.Authorization = value);
        }

        return request;
    }

    // example uses "JWT" nuget package: https://www.nuget.org/packages/JWT
    private static string CreateToken(IServiceProvider services, User user) {
        var config = services.GetRequiredService<IOptions<AuthenticationConfiguration>>.Value;

        var now = DateTimeOffset.UtcNow;

        var builder =
            new JwtBuilder()
                .WithAlgorithm(new HMACSHA256Algorithm())
                .WithSecret(config.ClientSecret)
                .AddClaim("iss", config.Issuer)
                .AddClaim("sub", user.Id)
                .AddClaim("aud", config.ClientId)
                .AddClaim("exp", now.AddHours(1).ToUnixTimeSeconds())
                .AddClaim("iat", now.AddHours(-1).ToUnixTimeSeconds())
                .AddClaim("email", user.EmailAddress)
                .AddClaim("email_verified", true);

        return builder.Build();
    }

}
```

We get around this today by manually recreating the configuration within the static constructor of our `RequestBuilderExtensions` class rather than fetching it from the `TestServer`, but in my opinion that's a hack.

I'm more than happy to submit a PR if Microsoft gives it the 👍 .

**Comment by huysentruitw** [comment]
Seems like it's not the `TestServer` that is needed here, but the `IServiceProvider` so `IOptions<AuthenticationConfiguration>` can be resolved from it.

This could be solved in many ways, so I don't think `TestServer` or `IServiceProvider` should be exposed onto the `RequestBuilder`.

F.e. you could pass the `IServiceProvider` or `IOptions<AuthenticationConfiguration>` to the `SetUser()` extension method yourself. Or create a `TestServer` extension method called `CreateRequestForUser` which takes the `path` and the `user`.

**Comment by carusology** [comment]
Yes, the underlying expectation is that you would have access to the `IServiceProvider` and there are certainly other ways to set an authorization header on a request. This is definitely a DX issue, not a bug. I don't think the alternatives result in code that is as easy to read or use.

1. The `CreateRequestForUser` suggestion prevents chaining these types of extension methods in a fluent way if the consumer wanted to provide some additional token, an e-tag, or really any other well-structured header on this request that require understanding of the dependencies and state on the server that will be parsing the header.

2. Passing the server container to the extension method also works, but is unnecessarily verbose, and all extension methods would need to be this verbose if it were to enable a fluent API.
```cs
this.TestServer.CreateRequest(path).SetUser(user); // vs
this.TestServer.CreateRequest(path).SetUser(user, this.TestServer.Host.Services);
```

3. Another option is to fetch the dependencies for the relevant header in the extension method yourself. You have to do this in tests anyway when you setup the test server, so you can encapsulate that logic for reuse in the static constructor of the extension method's static class. That's what we do today. It's fine, but I'd rather fetch them once off the TestServer directly.

4. One could create a small wrapper around this thing, but now you have to monkey with a new type:

```cs
public static BuildRequest(this TestServer server, string path) {
    return new RequestBuilderWithTestServer(server, path);
}

public class RequestBuilderWithTestServer : RequestBuilder {
    public TestServer TestServer { get; }

    public RequestBuilderWithTestServer(TestServer testServer, path) : base(testServer, path) {
        this.TestServer = testServer;
    }
}
```

**Comment by huysentruitw** [comment]
Thanks for the thorough explanation, it makes more sense to me now. Indeed it would be clumsy once you want to apply multiple settings onto the request builder. Since `RequestBuilder` is a `TestHost` class, I think it would be save to expose `TestServer` as a public property onto the `RequestBuilder` class.

**Comment by andresrsanchez** [comment]
This would be awesome for the little problem i have now :)
