### ISSUE TITLE
WebHostBuilder appears to store two separate Configurations

### ISSUE THREAD

**Issue by daniefer** [aspnet/AspNetCore#5948]
Hello

My question revolves around my inability to change the configuration values used in a WebHostBuilder unless I provide a whole new IConfigurationBuilder. The issue seems to revolve around this line. 

https://github.com/aspnet/Hosting/blob/cfe9b26a34af15c4943240d790ee5d1a168290c9/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L268

Here, new configuration values are only updated in the _context, not the _config. This means in order for me to supply a new config file I now have to recreate all the settings provided by the CreateDefaultBuilder just to add a new config location/setting. Is this a mistake? If it was a design choice, can you provide some context on why this limitation was added?

Thank you

**Comment by muratg** [comment]
Closing this as the discussion seems to have been resolved.
