### ISSUE TITLE
Unable to use ConfigureTestServices with StructureMap

### ISSUE THREAD

**Issue by rossdargan** [aspnet/AspNetCore#5949]
I'm using structure map which means I have to configure my `ConfigureServices` method to return a `IServiceProvider` as per the example here: https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection#example-1.

ConfigureTestServices registers a `IStartupConfigureServicesFilter`  which results in the following exception:

A ConfigureServices method that returns an IServiceProvider is not compatible with the use of one or more IStartupConfigureServicesFilter. Use a void returning ConfigureServices method instead or a ConfigureContainer method.

This is thrown here: https://github.com/aspnet/Hosting/blob/cfe9b26a34af15c4943240d790ee5d1a168290c9/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L185

I'm trying to register a test authentication schema which as far as I can tell should be done via ConfigureTestServices, but I'm using structuremap so I'm not sure how else I can go about this. My customer app factory looks like this:

    public class CustomWebApplicationFactory<TStartup>: WebApplicationFactory<TStartup> where TStartup : class
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureTestServices(services => {
                services.AddScheme<TestAuthenticationOptions, TestAuthentication>("Test", null);
            });
        }
   }

Is there any way to achieve this without putting some testing code in my primary website (the SUT)?

**Comment by muratg** [comment]
No more changes planned here.
