### ISSUE TITLE
Why there's no Authentication.Windows package?

### ISSUE THREAD

**Issue by John0King** [aspnet/AspNetCore#5959]
There's a ` Microsoft.Windows.Compatibility` nuget package now, Can we build a asp.net core native `Microsoft.AspNetCore.Authentication.Windows` now ? or that's some thing must impelement in the Server (eg.IIS,Kestrel,HttpSys) ?

**Comment by Eilon** [comment]
It doesn't exist because currently it's supported only with IIS and HttpSys, where there are options to turn it on. It's not currently supported in Kestrel, but we are tracking that feature request in https://github.com/aspnet/AspNetCore/issues/4662 .

**Comment by John0King** [comment]
@Eilon 
> It's not currently supported in Kestrel

Could you answer my last question : ` or that's some thing must impelement in the Server (eg.IIS,Kestrel,HttpSys) ?`

I see the windows authentication is a module in IIS ,  Can it just be a authentication MiddleWare in Asp.NetCore when it's possible ?
```C#
service.AddAuthentication().AddWindows(WindowsAuthenticationOption);

...

app.UseAuthentication() ;

```

**Comment by Eilon** [comment]
Yes in theory it could be, and that's what the other issue is tracking.
