### ISSUE TITLE
Serilog does not write log to file while using InProcess hosting model

### ISSUE THREAD

**Issue by TanvirArjel** [aspnet/AspNetCore#5961]
If I use `InProcess` hosting model as follows:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>
```
`Serilog` does not write log to file. but if I remove `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` from `.csproj` everything works as expected.

My `Serilog` configuration in the `Program` class as follows:

```
public static void Main(string[] args)
 {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information() // Set the minimun log level
                .WriteTo.File("Logs\\log-.txt", rollingInterval: RollingInterval.Day, retainedFileCountLimit: 7) // this is for logging into file system
                .CreateLogger();

            try
            {
                Log.Information("Starting web host");
                CreateWebHostBuilder(args).Build().Run();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
            }
            finally
            {
                Log.CloseAndFlush();
            }
            
}
```
How can make `Serilog` workable while using `InProcess` hosting model?

**Comment by jkotalik** [comment]
It's probably due to the CurrentDirectory issue: https://github.com/aspnet/AspNetCore/issues/4206. Here is our recommended workaround for now: https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module/samples_snapshot/2.x/CurrentDirectoryHelpers.cs. This will be fixed in a patch.

**Comment by TanvirArjel** [comment]
@jkotalik  Yes! It works perfectly! Thank you much!
