### ISSUE TITLE
Role-based authorization [Authorize (Roles = "Admin")] does not work when upgrading to ASP.NET Core 2.2

### ISSUE THREAD

**Issue by chenzhitong** [aspnet/AspNetCore#5964]
[Authorize (Roles = "Admin")] does not work when upgrading to ASP.net core 2.2

this is controller:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/6295602/50211678-2b7b2c80-03b4-11e9-9883-2d478edefc6d.png">

this is database: [AspNetUsers]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/6295602/50211720-42218380-03b4-11e9-9359-6501841df804.png">

this is database: [AspNetRoles]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/6295602/50211752-5796ad80-03b4-11e9-9a3b-686996a783ac.png">

this is database: [AspNetUserRoles]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/6295602/50211783-6a10e700-03b4-11e9-844d-a28ddfa8302e.png">

This is the result of the run after I login use chris@neo.org
<img width="567" alt="image" src="https://user-images.githubusercontent.com/6295602/50211934-c8d66080-03b4-11e9-8f0b-ebc5697ebb26.png">

This works on asp.net core 2.1, but it doesn't work when I upgraded to asp.net core 2.2

**Comment by rezaab1** [comment]
id must be "Admin"

**Comment by rezaab1** [comment]
In table [AspNetRoles] , change role id to "Admin"

**Comment by rezaab1** [comment]
In table [AspNetRoles], change Id to -> Admin

**Comment by rezaab1** [comment]
In [AspNetRoles] table, change Id to -> Admin

**Comment by rezaab1** [comment]
In [AspNetRoles] table, change Id to -> Admin
In [AspNetUserRoles] table change RoleId to -> Admin

**Comment by rezaab1** [comment]
In [AspNetRoles] table, change "Id" to -> Admin
In [AspNetUserRoles] table, change "RoleId" to -> Admin

**Comment by rezaab1** [comment]
1. In [AspNetRoles] table, change "Id" to -> Admin
2. In [AspNetUserRoles] table, change "RoleId" to -> Admin

**Comment by rezaab1** [comment]
In [AspNetRoles] table, change "Id" to -> Admin
In [AspNetUserRoles] table, change "RoleId" to -> Admin

**Comment by Eilon** [comment]
@HaoK / @Tratcher - any idea on this?

**Comment by chenzhitong** [comment]
@rezaab1 It doesn't work, either.
![image](https://user-images.githubusercontent.com/6295602/50274765-f5ec4700-0478-11e9-8986-d43b21205158.png)
![image](https://user-images.githubusercontent.com/6295602/50274787-fdabeb80-0478-11e9-992b-2ea43869b9bb.png)

**Comment by brockallen** [comment]
I think it's because this code:

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/src/Core/UserClaimsPrincipalFactory.cs#L75

Does not load the roles into the claims in the cookie for the user. You'd need to extend it and do that mapping, or add some sort of claims transformation to your request pipeline that did load from the role manager.

**Comment by rezaab1** [comment]
@chenzhitong In startup change [services.AddDefaultIdentity<IdentityUser>()] to [services.AddIdentity<IdentityUser, IdentityRole>()]

**Comment by rezaab1** [comment]
@chenzhitong In startup change [services.AddDefaultIdentity< IdentityUser >()] to [services.AddIdentity<IdentityUser, IdentityRole>()]

**Comment by HaoK** [comment]
Yes Roles are not enabled by default with AddDefaultIdentity, so you might need to do what @rezaab1 or call `AddRoles<IdentityRole>()` afterwards to enable roles
