### ISSUE TITLE
Question - Why did you move security sources?

### ISSUE THREAD

**Issue by KarenTazayan** [aspnet/AspNetCore#5965]
Why did you move security sources from https://github.com/aspnet/Security ?

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Announcements/issues/320

**Comment by KarenTazayan** [comment]
@davidfowl thank you for the response. Do you plan ship Microsoft.AspNetCore.Authorization as separate package like now?

**Comment by natemcmaster** [comment]
No plans to ship that as an individual package after 3.0. The API is still available via FrameworkReference instead of PackageReference. See https://github.com/aspnet/AspNetCore/issues/3756.
