### ISSUE TITLE
ASP.NET Core 2.2 - [assembly: ApiConventionType(typeof(DefaultApiConventions))] doesnt make warnings go away

### ISSUE THREAD

**Issue by zoinkydoink** [aspnet/AspNetCore#5971]
### Describe the bug
ASP.NET Core 2.2 - [assembly: ApiConventionType(typeof(DefaultApiConventions))] doesnt make warnings go away

### To Reproduce

1. Installed the package for Microsoft.AspNetCore.Mvc.Api.Analyzer
2. Added [assembly: ApiConventionType(typeof(DefaultApiConventions))] to top of my controller namespace
3. still get warnings without individually specifying ProducesResponseType

### Expected behavior
Expects warnings to dissappear

### Screenshots

https://i.stack.imgur.com/rlW4D.png

### Additional context
only works if i put it directly on the method, also tried 3.0 preview version of the package, same problem

    [ApiConventionMethod(typeof(DefaultApiConventions), nameof(DefaultApiConventions.Get))]
    [HttpGet]
    public ActionResult<IEnumerable<string>> Get()
    {
        return BadRequest();
    }

Also tried it on a different machine with vs 2017 enterprise vs pro that I was using, same issue that If  I have

[assembly: ApiConventionType(typeof(DefaultApiConventions))]

```
namespace APIConventiontest.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        // GET api/values
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            return BadRequest();

        
        }

       
    }
```

I get a warning about "BadReqest" "Anction method returns undeclared status code '400'

**Comment by zoinkydoink** [comment]
Adding to this, starting a default MVC project and adding analyzer for a an API controller does NOT seem to have the same problem, this seems to be narrowed to the fact that the project is Web Api 2.2

**Comment by pranavkm** [comment]
@zoinkydoink [`DefaultApiConventions`](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/DefaultApiConventions.cs) are patterned after the scaffolded controller. The parameterless `Get` action in the scaffolded code does not return any status codes other than a success value, consequently it does not have a associated convention method. You may either continue using the `ApiConventionMethodAttribute` which would apply the catch-all `default` status code to the action or [author a custom convention](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-2.2)
