### ISSUE TITLE
ASP.Net Core using .Net 4.7.2 documentation

### ISSUE THREAD

**Issue by joshmouch** [aspnet/AspNetCore#5972]
The documentation and Visual Studio support for "In-process" vs. "Out-of-process" is very confusing when you're using ASP.Net core with .Net Framework 4.7.2, instead of .Net Core.

For example, on the following page:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/aspnet-core-module?view=aspnetcore-2.2

...it says that the "in-process" model uses the "HTTP.sys" driver.  However, every example (including the code inside `WebHost.CreateDefaultBuilder`, which every ASP.Net Core sample uses) is setting up a Kestrel server.  Is this wrong?  If you want to use "in-process", do you have to ditch the Kestrel server and start using the HTTP.sys server instead?

Later on, that same page says that "the ASP.Net Core Module handles requests... [for] the out-of-process Kestrel server", which suggests that Kestrel is the out-of-process option.

However, on the following page:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/aspnet-core-module?view=aspnetcore-2.2

... it says to use WebHost.CreateDefaultBuilder if you want "in-process", which, if you look at the source, internally uses Kestrel.  So those two pages seem to conflict. (As a side note, it says "CreateDefaultBuilder calls the UseIIS method, which isn't true - it calls UseIISIntegration").

As another example, when you run an ASP.Net Core (.Net 4.7.2) application from Visual Studio using IIS or IIS Express, you're given an option to choose "in-process" or "out-of-process" in the Debug tab of the project settings.  

![image](https://user-images.githubusercontent.com/3098820/50244916-1cd64a80-039f-11e9-93f9-88fb3f4a37c4.png)

However, even if you choose "in-process", the ASP.Net Core project's executable still shows up in the Task manager, in addition to "w3wp.exe" or "iisexpress.exe", suggesting that it's running "out-of-process".

Add to that the following page:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2
which *only* talks configuration options for .Net Core, not .Net 4.7.2.  And it says that only .Net Core 2.2 or later supports the "in-process" hosting model, without mention of .Net 4.7.2.
For example, is says that the Process name will be "dotnet" in the out-of-process model, which I don't believe is correct when using .Net 4.7.2.

And to add a little more, none of those mention anything about the "IISHttpServer" module mentioned here:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-2.2&tabs=windows
... which I think plays a role.

I guess just in general: Is there a good full example Visual Studio project that uses "In-Process", "Framework dependent deployment", Net 4.7.2, Asp.Net Core Module, and IIS and that works completely as expected?

**Comment by Eilon** [comment]
@shirhatti / @jkotalik

**Comment by zhiliangxu** [comment]
Does in-process hosting model even work for ASP.Net Core using .Net 4.7.2?

**Comment by jkotalik** [comment]
Hey @joshmouch , sorry for not getting to this sooner (holiday season).

The new in-process mode does not support .Net Framework 4.7.2. It only runs on .NET Core.

>  If you want to use "in-process", do you have to ditch the Kestrel server and start using the HTTP.sys server instead?

In-process doesn't use Kestrel or HTTP.sys; it uses it's own custom web server. Calling UseIIS() will add its own IServer if running in-process with IIS. 

> Later on, that same page says that "the ASP.Net Core Module handles requests... [for] the out-of-process Kestrel server", which suggests that Kestrel is the out-of-process option. ... it says to use WebHost.CreateDefaultBuilder if you want "in-process", which, if you look at the source, internally uses Kestrel. So those two pages seem to conflict. (As a side note, it says "CreateDefaultBuilder calls the UseIIS method, which isn't true - it calls UseIISIntegration").

Yes, Kestrel is the only server compatible with IIS out of process. However, WebHost.CreateDefaultBuilder was updated in 2.2 to call UseIIS() https://github.com/aspnet/AspNetCore/blob/release/2.2/src/DefaultBuilder/src/WebHost.cs#L214-L215.


> As another example, when you run an ASP.Net Core (.Net 4.7.2) application from Visual Studio using IIS or IIS Express, you're given an option to choose "in-process" or "out-of-process" in the Debug tab of the project settings.

Again, this is because in-process doesn't support .NET framework. Therefore, it runs out-of-process.

@guardrex can we update the docs based on this issue. Specifically highlighting:
- IIS In-Process only runs on .NET Core
- Noting that IIS Out-Of-Process doesn't work with IIS In-Process Server.

I also this some of these issues stem from inability to find the right information. I thought we documented many of these issues listed here.

**Comment by muratg** [comment]
Closing as the docs work is tracked by @guardrex's bug above. Thanks!
