### ISSUE TITLE
Add more GZIP compressable MIME types

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/AspNetCore#5992]
I raised the following PR https://github.com/aspnet/BasicMiddleware/pull/181#issuecomment-264494906. This is a justifications for each MIME type to be added:

- `application/rss+xml`, `application/atom+xml` and `image/svg+xml` These are all just special dialects of XML, they are all web related and are fairly common (especially SVG).
- `application/vnd.ms-fontobject`, `application/x-font-ttf`, `font/otf` - TrueType fonts (ttf) and OpenType fonts (otf) can be safely be compressed for smaller size. The answer is unclear when it comes to Embedded OpenType (eot) fonts. It’s possible to compress EOT font files as part of the file creation process, in which case gzipping them is unnecessary. However, to generate compressed EOT font files requires a special tool and an extra step, so it’s likely that most of them are not pre-compressed. However, [Google](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#reducing_font_size_with_compression) recommends compressing EOT fonts.
- `image/x-icon` - Finding references for this is more difficult and I can only provide my own anecdotal evidence and the fact that the [HTML 5 Boilerplate Server Configs](https://github.com/h5bp/server-configs/) project also includes it for NGINX and IIS.

I only added the most used MIME types, this list could double in size if you wanted to support all web formats.

**Comment by shirhatti** [comment]
Spent some time re-visiting compression. As mentioned in triage, the extensibility points we are sufficient.
We will not be adding any new MIME types by default that aren't assets shipped by the templates.
