### ISSUE TITLE
Design Question on URL Rewriting Middleware

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore#5995]
`.AddRedirect()` and `.AddRewrite()` match their regex on the path/resource (not including the scheme, host, port, and query).

Works ...
```
.AddRedirect(@"^rule1/(.*)", "https://www.google.com/?query=$1")
.AddRedirect(@"^rule2/(.*)", "rule2/?query=$1")
```
Doesn't work ...
```
.AddRedirect(@"^http://localhost:5002/rule3/(.*)", "https://www.google.com/?query=$1")
```
Might be because "this is always the way it has always been done," but why is the design such that matching isn't performed on the absolute Url? ... or that there isn't an option to instruct the middleware to match on the absolute Url ... for maximum flexibility.

**Comment by shirhatti** [comment]
Looks like this has already been addressed in the docs https://github.com/aspnet/Docs/pull/8982
