### ISSUE TITLE
app.UseForwardedHeaders() does not use X-Forwarded headers

### ISSUE THREAD

**Issue by kevinoid** [aspnet/AspNetCore#6005]
As @ygoe mentioned in https://github.com/aspnet/Docs/issues/2384#issuecomment-360923957, the behavior of `.UseForwardedHeaders` without arguments is unexpected and counter-intuitive.  Since I was just caught by this as well, I decided to open this issue.  Would it be possible to either have `.UseForwardedHeaders` default to `ForwardedHeaders.All` or to remove the zero-argument overload of this method?

Thanks,
Kevin

**Comment by shirhatti** [comment]
I realize this API in its current iteration is a pit of failure, but we've doced the behavior and at this point do not want to introduce a breaking change.
