### ISSUE TITLE
DI extension methods for configuring HTTPS in Builder namespace

### ISSUE THREAD

**Issue by henkmollema** [aspnet/AspNetCore#6009]
The `AddHttpsRedirection` and `AddHsts` extension methods live in the `Microsoft.AspNetCore.Builder` namespace rather than in usual `Microsoft.Extensions.DependencyInjection` namespace. Is this intentional? 

See:
https://github.com/aspnet/BasicMiddleware/blob/f263e72389fe4468c1c353d2b97ea82704001c31/src/Microsoft.AspNetCore.HttpsPolicy/HstsServicesExtensions.cs#L8-L13

https://github.com/aspnet/BasicMiddleware/blob/f263e72389fe4468c1c353d2b97ea82704001c31/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionServicesExtensions.cs#L8-L13

**Comment by shirhatti** [comment]
@jkotalik @Tratcher Given that it's inconsistent, do we even bother trying to fix this? That's a lot of breaking changes for potentially no gain

**Comment by shirhatti** [comment]
If we do attempt it, we should try and get all the extensions into the right namespace in a single fix

**Comment by Tratcher** [comment]
I'd be nice if it were consistent, but in reality you end up with both namespaces in Startup.cs so it doesn't matter.
