### ISSUE TITLE
HttpsRedirectionMiddleware will not redirect to HTTPS if no port is available

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#6011]
Discussion for: https://github.com/aspnet/Announcements/issues/301

**Comment by punppis** [comment]
HTTP: 5000
HTTPS: 5001

On localhost, redirect works correctly from HTTP 5000 to HTTPS 5001. But on linux server the server redirects to HTTPS 5000 (tries to redirect to HTTP port with HTTPS).

I have set port using

```
services.AddHttpsRedirection(opts =>
            {
                opts.HttpsPort = 5001;
                opts.RedirectStatusCode = StatusCodes.Status308PermanentRedirect;
            });
```
and also I have checked that HTTPS_PORT env var is set to 5001 also, but still redirects to wrong port, but only on linux server.
```
// HTTPS_PORT = 5001
Console.WriteLine("HTTPS_PORT = " + Environment.GetEnvironmentVariable("HTTPS_PORT"));
```

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
