### ISSUE TITLE
Support for request de-compression

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#6012]
https://tools.ietf.org/html/rfc7694
Advertise Accept-Encoding on some responses (by content-type?). This is similar to Accept-Ranges where the client is allowed to use it if it has seen it advertised in the past.

Automatically decompress if encoded.

This is functionally symmetric with response compression.

What clients support this?

**Comment by shirhatti** [comment]
We're closing this issue due to a lack of interest. We'll re-open if there's enough interest
