### ISSUE TITLE
UseRewriter does not allow redirecting empty path to "/"

### ISSUE THREAD

**Issue by lscorcia** [aspnet/AspNetCore#6015]
Hello,
I'm still new to ASP.net Core so I apologize if I'm understanding the pipeline wrong. 

I have an ASP.net Core 2.1 Web API + Angular 6 web application created using Visual Studio 2017 Angular project template. Both the api and the Angular app are in the same web project. In development it runs inside IIS Express, while in production it uses IIS.

When I invoke my application as:
* http://localhost:52000/AngularWebApp/
* http://myserver.domain/AngularWebApp/

Angular is able to build the relative paths correctly and the application loads fine.

When I visit the URLs as (note the missing trailing slash):
* http://localhost:52000/AngularWebApp
* http://myserver.domain/AngularWebApp

IIS serves the index.html web page (why? I would expect a 404!), but then Angular can't compute correctly the relative paths to the JS/CSS resources.

I thought I could use the rewrite module to redirect an empty path to the `/` path, but the browser complains of a redirect loop, because it redirects both the empty path and the `/` path to the `/` path, even if the `^$` pattern does not match `/`.

This is the UseRewriter call I tried:

```
app.UseRewriter(new RewriteOptions()
   .AddRedirect(@"^$", "/", (int)HttpStatusCode.MovedPermanently));
```

Is this an unexpected scenario (bug) or is there a more appropriate solution for my problem?

Meanwhile I used this workaround to get the expected behavior, but it seems a bit hackish and I found very little examples of supplying an action method to the rewrite method. Is this ok?

```
app.UseRewriter(new RewriteOptions().Add(rewriteContext =>
{
    var request = rewriteContext.HttpContext.Request;
    if (request.Path == PathString.Empty)
    {
        rewriteContext.HttpContext.Response.Redirect(request.PathBase + '/', true);
        rewriteContext.Result = RuleResult.EndResponse;
    }
}));
```

Thanks in advance for your help

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
