### ISSUE TITLE
Url rewrite should support option updates

### ISSUE THREAD

**Issue by dlyz** [aspnet/AspNetCore#6016]
Use case: I have a static files host application with some complex configuration and it should support updating the redirects config on the fly.
Currently, RewriteMiddleware accepts IOptions and reads its value only once. It would be great to replace IOptions with IOptionsMonitor and use its CurrentValue for each request.
Similar feature: https://github.com/aspnet/BasicMiddleware/issues/317

**Comment by shirhatti** [comment]
We're closing this issue due to a lack of interest. We'll re-open if there's enough interest
