### ISSUE TITLE
[Authorize(AuthenticationSchemes = AzureADDefaults.BearerAuthenticationScheme)] generates compiler error CS0182

### ISSUE THREAD

**Issue by robinmira** [aspnet/AspNetCore#6020]
According to the [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.0&tabs=aspnetcore2x) it should be possible to explicitly specify or override the AuthenticationScheme for a controller with the Authorize attribute.

The following snippet is from the ValuesController.cs file in the base ASP.NET Core Web Application API template with "Work or School accounts" authentication.

`[Route("api/[controller]")]`
`[Authorize(AuthenticationSchemes = AzureADDefaults.BearerAuthenticationScheme)]`
`[ApiController]`
`public class ValuesController : ControllerBase`
`{ ... } `

However, the above code generates compiler error CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type.

A potential fix could be to change the member properties of AzureADDefaults from **static readonly** to **const** as in the [JwtBearerDefaults class](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerDefaults.cs)

`public const string BearerAuthenticationScheme = "AzureADBearer";`

**Comment by Tratcher** [comment]
@muratg recommend fix for 3.0. We're doing something similar for HttpSys windows auth.

**Comment by muratg** [comment]
@Tratcher :+1:  Let's triage this in the meeting today. cc @Eilon
