### ISSUE TITLE
HTTP 404 when redirecting to the AccessDenied page

### ISSUE THREAD

**Issue by PedroQ** [aspnet/AspNetCore#6021]
### Functional impact
 When accessing a page with no access permissions, an HTTP 404 error is returned (after an HTTP 302 redirect to an invalid location) instead of the AccessDenied page.

### Minimal repro steps
1. Set up a simple project using the ASP.NET Core 2.1 MVC template and add Azure AD authentication.
2. Annotate a controller action with some dummy role requirement that won't be fulfilled (e.g. HomeController.Contact).
3. Launch, navigate to the annotated action (e.g. Home/Contact)
4. An HTTP 302 is returned, redirecting to /Account/AccessDenied, missing the /AzureAD prefix.

### Expected result
An HTTP 302 redirecting to /AzureAD/Account/AccessDenied

### Actual result
An HTTP 302 redirecting to /Account/AccessDenied

### Further technical details
CookieAuthentication Login, Logout and AccessDeniedPath properties are not updated to reflect the new /AzureAD/ area due to a bug in the [CookieOptionsConfiguration](https://github.com/aspnet/AADIntegration/blob/dev/src/Microsoft.AspNetCore.Authentication.AzureAD.UI/CookieOptionsConfiguration.cs) class.
When configuring CookieAuthenticationOptions, the scheme name is compared with the OpenIdConnectScheme name instead of the CookieScheme name. 
[This check](https://github.com/aspnet/AADIntegration/blob/268e97c42453ff33ff7d0ad927b6d93ef201b157/src/Microsoft.AspNetCore.Authentication.AzureAD.UI/CookieOptionsConfiguration.cs#L42) causes the  [GetAzureADScheme](https://github.com/aspnet/AADIntegration/blob/268e97c42453ff33ff7d0ad927b6d93ef201b157/src/Microsoft.AspNetCore.Authentication.AzureAD.UI/CookieOptionsConfiguration.cs#L38) method to return null and to skip the CookieAuthenticationOptions configuration.

**Comment by Tratcher** [comment]
Same issue as https://github.com/aspnet/AspNetCore/pull/6790 ?

**Comment by PedroQ** [comment]
> 
> 
> Same issue as #6790 ?

Yep. My pull request was still in the old repo. #6790 fixes this.

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/commit/23c528c176e654e14cf5d078558420e00154d0e6
