### ISSUE TITLE
Hard to diagnose exception thrown when AzureADOptions.Instance is not set

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCore#6022]
I was migrating an app that uses Azure AD auth from 1.x to 2.1, including using the new UI package. I had not set `AzureADOptions.Instance` (as this is new in 2.x and I didn't know it needed to be set). The exception that results does not have user-code on the stack, and thus has no line numbers. The exception is from the `Uri` constructor, which is being passed a null string (from [this line](https://github.com/aspnet/AADIntegration/blob/master/src/Microsoft.AspNetCore.Authentication.AzureAD.UI/OpenIdConnectOptionsConfiguration.cs#L32)).

We should ensure we validate options properties before using them to create other types where they might throw, as it's incredibly hard for app devs to diagnose.

@javiercn @blowdart

**Comment by muratg** [comment]
@danroth27 @mkArtakMSFT is @javiercn the owner for this? Is is to be done in Preview3 or at a later preview?

**Comment by danroth27** [comment]
@blowdart

**Comment by blowdart** [comment]
When did that happen? It's not identity.

**Comment by javiercn** [comment]
We can validate the options here using "options validation" or just throw an exception, it shouldn't be very costly, but it's very low on priority IMO

**Comment by anurse** [comment]
We should just check the `Instance` for null-or-empty and throw a useful exception.
