### ISSUE TITLE
Can't get the OnTokenValidated event

### ISSUE THREAD

**Issue by Omarkth** [aspnet/AspNetCore#6023]
What's the proper way to add my custom claims to the validated token? I used to do it in the "OnTokenValidated" event by using something similar to:
```

builder.AddOpenIdConnect(o =>
             {
                o.Events = new OpenIdConnectEvents
                 {
                     OnTokenValidated = async ctx =>
                     {
                     ...
```

I'm no longer able to do this with the new AzureAD.UI package.

**Comment by Eilon** [comment]
Looks like this is the same fundamental issue as https://github.com/aspnet/AspNetCore/issues/6447, which we will add better documentation for via https://github.com/aspnet/Docs/issues/10324
