### ISSUE TITLE
AzureADB2CBearer support for dynamic validation of issuers and audiences 

### ISSUE THREAD

**Issue by ddobric** [aspnet/AspNetCore#6025]
When implementing WebApi, we have often requirement to dynamically validate issuers and/or audiences. With JwtBearer we could do it as shown below:

```c#
      services.AddAuthentication().AddJwtBearer(o => {
            (o => {
                Configuration.Bind("AzureAd", o);

                o.Authority = $"{xyz}/common";

                o.TokenValidationParameters = new 
                Microsoft.IdentityModel.Tokens.TokenValidationParameters()
                {
                    ValidateAudience = true,

                    ValidateIssuer = true,

                    AudienceValidator = (audiences, securityToken, validationParameters) =>
                    {
                            return true/false;
                    },
                    IssuerValidator = (issuer, token, tvp) =>
                    {
                         . . .
                        return issuer;
                    },
                };
                o.Events = new JwtBearerEvents()
                {
                    OnAuthenticationFailed = ctx =>
                    {
                        throw ctx.Exception;
                    }
                };
            });
```

The question is, how to do the same with **AzureADB2CBearer** ? Looking for handlers like IssuerValidator and AudienceValidator.
 
My API does not really care about AAD v2 or v2. It just needs a token as it is. I have tried with the more or less same code provided above, but it fails on validation of the signature, because v1 and v2 seems to use different signing mechanism.

Currently supported using of *B2C*works well, but it is very static. This is the code, which I usually use when working with B2C in a WebApi:

```
 services.AddAuthentication(AzureADB2CDefaults.BearerAuthenticationScheme)
            .AddAzureADB2CBearer(options => Configuration.Bind("AzureAd", options));
```

Thanks

**Comment by Eilon** [comment]
Looks like this is the same fundamental issue as https://github.com/aspnet/AspNetCore/issues/6447, which we will add better documentation for via https://github.com/aspnet/Docs/issues/10324
