### ISSUE TITLE
Microsoft.AspNetCore.Authentication.AzureAD.UI is not support v2.0 endpoint?

### ISSUE THREAD

**Issue by karamem0** [aspnet/AspNetCore#6026]
I want to use 'AddAzureADBearer' method with v2.0 endpoint (from Application Registration Portal), but it seems to be not supported. 

Do I have to use this sample? https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/TodoListService/Extensions/AzureAdAuthenticationBuilderExtensions.cs

**Comment by Eilon** [comment]
@jmprieur do you know more about this?

**Comment by jmprieur** [comment]
@karamem0 : I would recommend you look at this sample: https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2
cc: @Eilon
