### ISSUE TITLE
Issuer validation problem

### ISSUE THREAD

**Issue by daymansiege** [aspnet/AspNetCore#6028]
Hello!
Azure AD B2C produces JWT with issuer "https://sts.windows.net/{TENANT_ID}/', however JwtBearerHandler takes issuer from Open ID metadata endpoint (https://login.microsoftonline.com/{TENANT_ID}/v2.0/.well-known/openid-configuration), as I see, which is "https://login.microsoftonline.com/{TENANT_ID}/v2.0".
Is there a way to override thsi behavior? Add some custom issuer validatior or add "sts.windows.net" to the list of valid issuers?
I see that inside AzureADB2CAuthenticationBuilderExtensions.AddAzureADB2CBearer JwtBearerOptionsConfiguration is used. Is it possible to add some injection point or extend AzureADB2COptions to add valid issuers to the list?
Thank you!

**Comment by jmprieur** [comment]
@daymansiege 
The following example is for AAD, but it's transposable to B2C. In the service.Configure, you'd want to add valid issuers (ValidIssuers) to the TokenValidationParameters

Alternatively you can implement your own IssuerValidator and set it to TokenValidationParameters.IssuerValidator as shown in https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/1.%20Desktop%20app%20calls%20Web%20API/TodoListService/Startup.cs#L50         

```CSharp
services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options =>
{
 ...
// Instead of using the default validation (validating against a single tenant, as we do in line of business apps),
// we inject our own multitenant validation logic (which even accepts both V1 and V2 tokens)
options.TokenValidationParameters.IssuerValidator = AadIssuerValidator.ValidateAadIssuer;
});
