### ISSUE TITLE
ClientId is used by default instead of Audience Id in file AzureAdAuthenticationBuilderExtensions.cs in .Net core 2.0

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#6030]
_From @blowdart on September 17, 2018 18:38_

_From @jatingandhi28 on September 17, 2018 9:38_

File name - AzureAdAuthenticationBuilderExtensions.cs
[Note this code has moved [here](https://github.com/aspnet/AADIntegration/blob/28e81276582af23f4c616d9db900664960682074/src/Microsoft.AspNetCore.Authentication.AzureAD.UI/JwtBearerOptionsConfiguration.cs#L33)].

            public void Configure(string name, JwtBearerOptions options)
            {
                options.Audience = _azureOptions.ClientId;
                options.Authority = $"{_azureOptions.Instance}{_azureOptions.TenantId}";
            }

However It should be 

            public void Configure(string name, JwtBearerOptions options)
            {
                options.Audience = _azureOptions.AudienceId;
                options.Authority = $"{_azureOptions.Instance}{_azureOptions.TenantId}";
            }

_Copied from original issue: aspnet/Home#3538_

_Copied from original issue: aspnet/Security#1859_

**Comment by Eilon** [comment]
Closing because we are not planning to make any changes to this.
