### ISSUE TITLE
Alternative SignedOut callback url

### ISSUE THREAD

**Issue by JohnGoldsmith** [aspnet/AspNetCore#6032]
Is there a good way to use Areas/Controllers/AccountController.cs, but have alternative routes for pages like SignedOut.cshtml.  What I'm after is for the signed out user to be redirected to the home page rather than the current https://localhost:44383/AzureADB2C/Account/SignedOut

Is it the intention that the code under https://github.com/aspnet/AADIntegration/tree/master/src/Microsoft.AspNetCore.Authentication.AzureADB2C.UI/Areas/AzureADB2C is just to demo how code should be structured and a real implementation would be code in the project?

Thanks, John

**Comment by Eilon** [comment]
Indeed, there is no built-in way to change just that one option.

In this case we recommend scaffolding the identity code into your app as per https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio

And then you can customize the AccountController as you see fit for your app.

**Comment by JohnGoldsmith** [comment]
@Eilon Thanks very much for responding to this.  I had a go with the scaffolding but wasn't able to get it to behave properly with B2C.  No doubt this highlights the gaps in my own understanding, but it seems to want to add EF context and other things that appear to be handled by B2C already.  Note - I'm sure you're right, it's just not clear to me how to adapt the redirect paths simply from this.

I've ended up going back to the original B2C sample extension builder class and separate AccountController as at least I can then see the wood for the trees.

Anyway, thank you again for reaching out.

**Comment by Eilon** [comment]
@JohnGoldsmith understood. If you have other specific issues, please log new issues for those and we will take a look. BTW sometimes StackOverflow is also a good source for these types of questions because that will often reach an even broader audience if you put the right tags on it.

**Comment by dcaton** [comment]
@JohnGoldsmith There's an easy way to accomplish this.  In your Startup.Configure() implementation, add this.  Not sure if the exact order matters, but it didn't work for me unless I put this before app.UseMvc().

`app.UseRewriter(new RewriteOptions().Add(context =>
            {
                if (context.HttpContext.Request.Path == "/AzureADB2C/Account/SignedOut")
                {
                    context.HttpContext.Response.Redirect("/Home/SignedOut");
                }
            }
            ));`
