### ISSUE TITLE
Blazor page's OnInit/OnInitAsync not called for query string changes

### ISSUE THREAD

**Issue by nvmkpk** [aspnet/AspNetCore#6048]
Blazor page's OnInit/OnInitAsync is not called when navigated to the same page with different query string. 
I am little lazy to describe it using the bug report template but I can demonstrate the issue using a sample code if necessary.

**Comment by IvanJosipovic** [comment]
You can use OnParametersSet/OnParametersSetAsync for that purpose.

`OnParametersSetAsync and OnParametersSet are called when a component has received parameters from its parent and the values are assigned to properties. These methods are executed after OnInit during component initialization.`
From: https://blazor.net/docs/components/index.html

**Comment by nvmkpk** [comment]
@IvanJosipovic I have exact same issue with OnParametersSet/OnParametersSetAsync. It is not invoked after second navigation.

**Comment by mkArtakMSFT** [comment]
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

**Comment by nvmkpk** [comment]
@mkArtakMSFT really? Then blazor should at least provide us a mechanism to know when url query parameter values are changed. Angular provides that and is much better than blazor. Without it, blazor does not work in many scenarios.
