### ISSUE TITLE
Issues transferred by hello-bot and links

### ISSUE THREAD

**Issue by dazinator** [aspnet/AspNetCore#6050]
Where an issue is transferred by hello-bot to another repo and it had links in its description to other issues in the same repo, for example `#1` - after the issue is transferred, the links appear not to have been rewritten, so they now point to irrelevant issues in the new repo.

Example see: https://github.com/aspnet/Extensions/issues/821

**Comment by Eilon** [comment]
That is an unfortunate limitation of even GitHub's new "Transfer issue" feature. Full links work, but just an issue/PR number does not. At this time we have no plans to try to fix these up because it would involve trying to parse Markdown and understand what links would go where.

**Comment by Eilon** [comment]
Closing because there are no plans to go back and fix this. No big issue move planned in the near future, fortunately!
