### ISSUE TITLE
Set bind(ed) object before onkeyup fires

### ISSUE THREAD

**Issue by cyberjaws** [aspnet/AspNetCore#6052]
In this case when the operator presses 'a' in the input form:
```
<input type=text bind="@SomeString" onkeyup="@Validate" />
@functions
{
   private string SomeString;
   private void Validate()
   {
      if(SomeString == "a") { // do something }
      StateHasChanged();
   }
}
```
SomeString is still "". It would be nice to have seen SomeString as "a".

**Comment by enetstudio** [comment]
As far as I know, the value property of the input control is based on the onchange event... You actually ask that the binding would be based on the input event. This can be very useful. Write a Pull Request.

**Comment by cyberjaws** [comment]
I can see how others might prefer the onchange event being the source of the bind. Could there be a way to designate which event is used in the bind? I see that there are [static attributes](https://github.com/aspnet/AspNetCore/blob/62dd8f4bd999e4181cb7e5d9fd8901eee943af30/src/Components/src/Microsoft.AspNetCore.Components/BindAttributes.cs) that are being applied to the types. Likely this would require a more complex change to perhaps add another attribute: "bind-event" perhaps?

**Comment by Andrzej-W** [comment]
You can use code like this:
```html
@page "/"

<input bind-value-oninput="@SomeString" />
<p>@SomeString</p>
```
```c#
@functions{
    private string someString;

    public string SomeString
    {
        get { return someString; }
        set
        {
            if (value == "a")
                someString = "x";
            else
                someString = value;
        }
    }
}
```
Unfortunately `bind-value-onkeyup` throws. You can use workaround:
```html
<input onkeyup="(this.dispatchEvent(new CustomEvent('change', { bubbles: true })))" bind="@SomeString" />
```
Read this #5521. 
In my opinion you can close this issue in favour of #5521.

**Comment by cyberjaws** [comment]
I would concur that this could be closed as a duplicate. Thanks @Andrzej-W !

**Comment by Manishbtech** [comment]
The below syntax is not working in blazor preview9. 

<input onkeyup="(this.dispatchEvent(new CustomEvent('change', { bubbles: true })))" bind="@SomeString" />

**Comment by Manishbtech** [comment]
The syntax  onkeyup="(this.dispatchEvent(new CustomEvent('change', { bubbles: true })))" is not working in Blazor preview9.  Can anyone suggest the solution?
