### ISSUE TITLE
Mvc should reference Razor through project reference instead of a package reference

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#6070]
Note: This is only for release/2.1 and release/2.2 branches

Follow up to https://github.com/aspnet/AspNetCore/pull/6047

We need to figure out a way to reference Razor as a project reference in Mvc. Right now doing that fails because of special needs of `Microsoft.AspNetCore.Razor.Design` and `Microsoft.AspNetCore.Mvc.Razor.Extensions`.

cc @natemcmaster

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, what is the impact of this? Is the build currently broken for those branches?

**Comment by ajaybhargavb** [comment]
> Is the build currently broken for those branches?

Nope. This is just something we want to eventually get done.

**Comment by mkArtakMSFT** [comment]
This is not an issue any more.
