### ISSUE TITLE
Remove side by side outofprocess versioning support from shim

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#6085]
cc @shirhatti

**Comment by davidfowl** [comment]
Uh wut. More details please?

**Comment by pakrym** [comment]
If we are not going to rapid deploy it, there is not reason to split OutOfProc handler.

**Comment by pakrym** [comment]
> Generally, we want to be in a place where the out of process handler can be phased out or optionally installed if that functionality is needed

Sure, but dropping side by side versioning story for out of proc would decrease complexity.

I'm not saying let's make code hight coupled again but if there is no benefit to having a separate dll we shouldn't do it.

**Comment by anurse** [comment]
We don't think removing this complexity is worth losing the potential for using rapid update as an escape hatch. If there's a high maint. cost for this we can revisit.
