### ISSUE TITLE
Input value always null on `onkeydown` or `onkeypress` event in Blazor

### ISSUE THREAD

**Issue by TanvirArjel** [aspnet/AspNetCore#6100]
Input value always null on `onkeydown` or `onkeypress` event but have value on `onclick` event in Blazor.

Here is my code:

```
<input onkeydown="@CheckInput" placeholder="Write To Do" bind="@NewToDo" />
<button onclick="@AddToDo">Add todo</button>
<br />
<span class="text-danger">@errorMessage</span>

@functions {
    List<TodoItem> todos = new List<TodoItem>();
    private string NewToDo { get; set; }
    private string errorMessage;

    private void CheckInput()
    {
        Console.WriteLine(NewToDo); // Strangely input value always null here.
    }

    private void AddToDo()
    {
        if (!string.IsNullOrWhiteSpace(NewToDo)) // Here value is getting as expected
        {
            errorMessage = null;
            todos.Add(new TodoItem() { Title = NewToDo, IsDone = false });
            NewToDo = null;
        }
        else
        {
            errorMessage = "Please enter a To do item!";
        }

    }
}
```
Why I am getting input field value always null on `onkeydown` or `onkeypress` while getting the value on `onclick`?

**Comment by Boglen** [comment]
Try 
onkeydown="@((__value) => NewToDo =  __value)"

**Comment by Mirch** [comment]
It's probably because of the way in which events are triggered?
Since binding essentially raises an OnChange event, I believe that is triggered after OnKeyDown or OnKeyPress. 
If you still want to check the input based on the OnKeyDown event, you could do something like this:

```
<input type="text" bind="@NewToDo" onkeypress="@((e) =>CheckInput(e))" placeholder="Write To Do" />
<button onclick="@AddToDo">Add todo</button>
<br />
<span class="text-danger">@errorMessage</span>

@functions {
List<TodoItem> todos = new List<TodoItem>();
private string NewToDo { get; set; }
private string errorMessage;

private void CheckInput(UIKeyboardEventArgs e)
{
    Console.WriteLine(e.Key);
}

private void AddToDo()
{
    Console.WriteLine(NewToDo);
    if (!string.IsNullOrWhiteSpace(NewToDo))
    {
        errorMessage = null;
        todos.Add(new TodoItem() { Title = NewToDo, IsDone = false });
        NewToDo = null;
    }
    else
    {
        errorMessage = "Please enter a To do item!";
    }

}
}
```

**Comment by Mirch** [comment]
The `bind` property raises an OnChange event. Now, the OnChange event is raised only after the element loses focus. So while you type in your input field, the NewToDo value will remain the same. Try clicking somewhere else and then typing again, you will get your console message right.

**Comment by TanvirArjel** [comment]
@Mirch You are correct! But is there any option to get the current value while typing?

**Comment by Mirch** [comment]
> @Mirch You are correct! But is there any option to get the current value while typing?

What's your use case here? I assume something like a real time search, but maybe there's a workaround for whatever you are trying to accomplish.

**Comment by TanvirArjel** [comment]
@Mirch My requirement is Getting the current value while typing(on each keypress) on input field like JavaScript/jQuery.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
