### ISSUE TITLE
Invalid type parameter 'Microsoft.AspNetCore.Mvc.NoContentResult' specified for 'ActionResult<T>'.

### ISSUE THREAD

**Issue by mark-szabo** [aspnet/AspNetCore#6101]
### Describe the bug
ASP.NET Core 2.2 is throwing an exception if the type param of ActionResult<T> is NoContentResult.

### To Reproduce
``` csharp
public ActionResult<NoContentResult> Repro()
{
    return NoContent();
}
```

### Expected behavior
No exception? :D

### Screenshots
![image](https://user-images.githubusercontent.com/3098994/50377729-cda04c00-0622-11e9-97b2-8cceeefe2fa7.png)

### Additional context
Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by davidfowl** [comment]
This is by design. The T in ActionResult<T> can’t be an IActionResult. The entire goal of that type is to describe your model type directly not the ActionResult type. It means you can have an ActionResult<Product> and return NoContent without changing the return type

**Comment by mark-szabo** [comment]
I see. Thanks for the info!
