### ISSUE TITLE
Passing dynamic objects to MVC views causes RuntimeBinderException

### ISSUE THREAD

**Issue by QuickScoP3s** [aspnet/AspNetCore#6103]
### Describe the bug
When passing a dynamic object to a View with a controller, trying to access a property of this object causes a RuntimeBinderException
This has been reported and fixed before in the AspNet MVC 3 Framework as described by this [post](https://blogs.msdn.microsoft.com/davidebb/2009/12/18/passing-anonymous-objects-to-mvc-views-and-accessing-them-using-dynamic/) in 2009

#### Steps to reproduce the behavior:
Using version ASP.NET Core 2.1
Try passing a dynamic object to a view via the model:
```
public class HomeController : Controller {
   public ActionResult Index() {
      return View(model: new {
            Message = "Welcome to ASP.NET Core!",
            Date = DateTime.Now
         });
      }
}
```
No try to read out the properties inside the View:
```
<h2>@Model.Message</h2>
<p>@Model.Date</p>
```

### Expected behavior
I expect to be able to read the different properties of the object

### Screenshots
![The Exception](https://i.imgur.com/JJcuI3N.png)
![My own code while debugging](https://i.imgur.com/HBpoEt5.png)

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/7773.

> This is a limitation of the language. Anonymous types are internal to the assembly they are defined in. Views are compiled in an assembly different than your application's. Using a model to pass structured data would be our recommendation. You might also have success using value tuples

**Comment by QuickScoP3s** [comment]
Well, yes, this has been said many times, like in [this](https://stackoverflow.com/a/5120501) StackOverflow answer (and the post linked to above)
But it **was** fixed and now it's back again

**Comment by pranavkm** [comment]
> Do you know if this will be fixed in a future version? *hopeful*

Marking this for triage to see what they think. AFAIK, we intentionally avoided performing private reflection on user code when this code was ported to MVC Core.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
