### ISSUE TITLE
OnPost() not hit razor pages 2.2

### ISSUE THREAD

**Issue by Stoyan-Bukovich** [aspnet/AspNetCore#6109]
Hello everyone,

My problem is that the OnPost method is not getting called when the submit button is pressed and I cannot figure it out. Here is the form code:

<form asp-antiforgery="true" method="post">
<div class="row">
<div class="col">
<label for="name">@Localizer.Text("Full name")</label>
<input type="text" id="name" name="name" class="form-control col-6" maxlength="60" />
</div>
</div>

<div class="row mt-4">
<div class="col">
<label for="location">@Localizer.Text("Location")</label>
<select id="location" name="location" class="form-control col-6">
<option selected>@Localizer.Text("Choose...")</option>
<option>@Localizer.Text("Location 2")</option>
<option>@Localizer.Text("Location 1")</option>
<option>@Localizer.Text("Other")</option>
</select>
</div>
</div>

<div class="row mt-4">
<div class="col-2">
<label for="persons">@Localizer.Text("Persons")</label>
<select id="persons" name="persons" class="form-control">
<option selected>@Localizer.Text("Choose...")</option>
<option>50</option>
<option>100</option>
<option>150</option>
<option>@Localizer.Text("Other")</option>
</select>
</div>

<div class="col">
<label for="date">@Localizer.Text("Event date")</label>
<input type="text" id="date" name="date" class="form-control col-2" maxlength="6" />
</div>
</div>

<div class="row mt-4">
<div class="col">
<label for="email">@Localizer.Text("Email")</label>
<input type="text" id="email" name="email" class="form-control col-6" maxlength="100" />
</div>
</div>

<div class="row mt-4">
<div class="col">
<label for="tel">@Localizer.Text("Phone number")</label>
<input type="text" id="tel" name="tel" class="form-control col-3" maxlength="15" />
</div>
</div>

<div class="row mt-4">
<div class="col">
<label for="message">@Localizer.Text("Comments")</label>
<textarea id="message" name="message" class="form-control" maxlength="300" style="resize: none; height: 200px;"></textarea>
</div>
</div>

<div class="row mt-4">
<div class="col">
<button type="submit" id="submit" name="submit" class="btn btn-primary float-right w-25">@Localizer.Text("Submit")</button>
</div>
</div>
</form>

And the OnPost method:

public void OnPost()
{

string Test = "Test";

}

Asp.Net Core 2.2 Razor Pages (not MVC)

Thanks.

**Comment by Stoyan-Bukovich** [comment]
Someone some ideas?

**Comment by execution** [comment]
On the razor page, you need to add @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
hope it will help

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Stoyan-Bukovich.
If this is still an issue, please reopen this issue with a repro project.
