### ISSUE TITLE
HTTP Error 500.0 - ANCM In-Process Handler Load Failure

### ISSUE THREAD

**Issue by patricka2** [aspnet/AspNetCore#6111]
### Describe the bug
How to fix this problem in in-process hosting model?

### Screenshots
![problem](https://user-images.githubusercontent.com/46094177/50388102-85843680-06c1-11e9-8d29-a5d2500e26cd.png)

web.config
![sssssss](https://user-images.githubusercontent.com/46094177/50388104-959c1600-06c1-11e9-8660-1b95846f63e1.png)

.csproj
![p2](https://user-images.githubusercontent.com/46094177/50388107-98970680-06c1-11e9-9c22-eb7548eb541f.png)

### Additional context
SDK Version: 2.2.101

**Comment by huan086** [comment]
You might be facing the issue of configuration files not found. Look at your Windows Event Log.

If so, apply the workaround here https://stackoverflow.com/questions/53628995/directory-to-use-in-asp-net-core-module-in-process-hosting-setbasepath

**Comment by patricka2** [comment]
@huan086 It doesn't work, either.

**Comment by huan086** [comment]
What does your Windows Event Log > Application say?

**Comment by kucxgithub** [comment]
Try including **AspNetCore.Middleware** to your project. To learn more about ASP.NET Core (2.2.0) Middleware, refer to [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2). 

I encountered this issue and used **NWebsec.AspNetCore.Middleware** nuget package to resolve, as well as remove other packages that might have caused conflicts in the process handling (this step does not apply to your issue as your two other packages should work just fine with **NWebsec.AspNetCore.Middleware**.

**Comment by jkotalik** [comment]
@patricka2 what happens when you run `dotnet Test2.dll` on commandline. Does it say that the framework `Microsoft.NETCore.App` cannot be found? If so, make sure the correct version of dotnet is installed (See: https://dotnet.microsoft.com/download/dotnet-core/2.2).

**Comment by Scriptworks** [comment]
@kucxgithub is absolutely spot on. 

This was happening to me when I was trying to webdeploy a dotnet core 2.2 into an IIS server. Another thing that worked for me but isn't necessarily right is to actually change the handler in the web.config from 
`      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule**V2**" resourceType="Unspecified" />
      </handlers>`
to
`      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>`

Thank you

**Comment by fatihyildizhan** [comment]
I am getting same error with .net core 2.2 and 3 preview also.

**Comment by jkotalik** [comment]
@kucxgithub @Scriptworks let me clarify why what you are doing works. In ASP.NET Core 2.2, we released a new Server/ hosting pattern with IIS called IIS InProcess hosting (See: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#enable-the-iisintegration-components). To enable inprocess hosting, the csproj element `AspNetCoreHostingModel` is added to set the `hostingModel` to `inprocess` in the web.config file. Also, the web.config points to a new module called `AspNetCoreModuleV2` which is required for inprocess hosting.

By removing both `AspNetCoreHostingModel` and modifying the web.config to remove `AspNetCoreModuleV2`, you are reverting back to OutOfProcess hosting with Kestrel. This is totally fine to revert back to and is still supported. However, we put a lot of work into making IIS Inprocess hosting a great experience, and would appreciate people trying it.

If the target machine you are deploying to doesn't have ANCMV2, you can't use IIS InProcess hosting. If so, the right behavior is to either install the dotnet hosting bundle (https://dotnet.microsoft.com/download/dotnet-core/2.2) to the target machine or downgrade to the AspNetCoreModule.

@fatihyildizhan , most likely the error you are hitting is a missing version of Microsoft.NETCore.App available for your application. Try to see if there are any event logs from the AspNetCoreModuleV2 or if the app starts by running dotnet run on the commandline.

**Comment by patricka2** [comment]
> @patricka2 what happens when you run `dotnet Test2.dll` on commandline. Does it say that the framework `Microsoft.NETCore.App` cannot be found? If so, make sure the correct version of dotnet is installed (See: https://dotnet.microsoft.com/download/dotnet-core/2.2).

**Comment by patricka2** [comment]
> @patricka2 what happens when you run `dotnet Test2.dll` on commandline. Does it say that the framework `Microsoft.NETCore.App` cannot be found? 
No!

**Comment by patricka2** [comment]
> Does it say that the framework `Microsoft.NETCore.App` cannot be found?

no

**Comment by cdwaddell** [comment]
To add to this conversation, my issue #6465 has the same result when hosting in Azure if I manually build the system using the dotnet CLI and deploy my application to Azure. The application runs as expected locally from the executable (self-contained) and from the dotnet command line (framework dependent). 

Interestingly, if I use Visual Studio to "Publish" the same application to Azure, the application works as expected. If someone can tell me where to find the event logs for ANCM in Azure I will look for them.

Note: I have the AspNetCoreRuntime.2.2.x64 extension installed.

**Comment by mac2000** [comment]
We have similar but different problem, the response from IIS is also 500.0 but nothing more (e.g. standard from windows 2008 r2)

![image](https://user-images.githubusercontent.com/88868/51054344-43298780-15e5-11e9-86b3-273d94d9adf6.png)

What is even worse, I have tried everything (switching environment to dev, turning on logs and module logs, changing apppool identity, turning inprocess on and off building selfcontained etc) and still nothing

Logs are empty, nothing in event viewer

What is interesting side by side on same sever 2.0 is running ok, but 2.2 does not run

If I run it like `dotnet my.dll` everythings starts as expected on `localhost:5000` (in case of selfcontained runing it as exe also works as expected), but via IIS without chances

**Web.config**

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration><appSettings><add key="NewRelic.AgentEnabled" value="false" /></appSettings>
<location path="." inheritInChildApplications="false">
	<system.webServer>
		<handlers>
			<add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
		</handlers>
		<aspNetCore processPath=".\my.exe" stdoutLogEnabled="true" requestTimeout="00:00:30" stdoutLogFile=".\logs\stdout">
			<environmentVariables>
				<environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
			</environmentVariables>
			<handlerSettings>
				<handlerSetting name="debugFile" value=".\logs\aspnetcore-debug.log" />
				<handlerSetting name="debugLevel" value="FILE,TRACE" />
			</handlerSettings>
		</aspNetCore>
	</system.webServer>
</location>
</configuration>
```

**my.csproj**

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
```

Hosting bundle is installed

```ps1
(Get-Item -ErrorAction Stop -Path "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Updates\.NET Core").GetSubKeyNames()
```

output:

```
Microsoft .NET Core 1.1.2 - Windows Server Hosting
Microsoft .NET Core 2.0.7 - Windows Server Hosting
Microsoft .NET Core 2.2.0 - Windows Server Hosting (x64)
Microsoft .NET Core 2.2.1 - Windows Server Hosting (x64)
```

wondering if there is anything else I can check to investigate this issue furthermore?

**Comment by jkotalik** [comment]
@mac2000 that seems like a different issue than listed above. Are you trying to run inprocess or out of process? 

To confirm that things are still working with the original ANCM, can you change modules="AspNetCoreModuleV2" to modules="AspNetCoreModule"?

**Comment by mac2000** [comment]
Yes seems like issue was not in dotnet and/or IIS but with NLB, seems like requests were routed to another machine which has no dotnet core which was a reason for 500 and explains why I did not saw any log records, will be able to check this after rolling 2.2 on all machines

**Comment by patricka2** [comment]
> can you change modules="AspNetCoreModuleV2" to modules="AspNetCoreModule"?

In web.config, I changed modules to "AspNetCoreModule" and its work, but "AspNetCoreModuleV2" do not works

**Comment by dmitrydvm** [comment]
I have same problem.
App version 2.2, Hosting IIS W2016, netcoreruntime 2.2.1
Event Viewer:
```
Failed to start  application '/LM/W3SVC/11/ROOT', ErrorCode  '0x800700b7'.
File Version: 12.2.18346.1. Description: IIS ASP.NET Core Module V2. Commit:  0f9ad16b096ca2535d77efd2ad27645449421b44
```

**Comment by cizirgan** [comment]
> > can you change modules="AspNetCoreModuleV2" to modules="AspNetCoreModule"?
> 
> In web.config, I changed modules to "AspNetCoreModule" and its work, but "AspNetCoreModuleV2" do not works

@patricka2  This worked in my case too.

**Comment by Toby9876** [comment]
The problem also exists for the standard standard .NET Core 2.2 project template using Self-Contained Deploy. The fix for me was the replacement of the "<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>" as suggested above by @kucxgithub. I did not have to do anything else to make it work . It think it would be good to have the default project template work so you'd have something to fall back on testing with when something like this happens.

**Comment by fatihyildizhan** [comment]
How can we upgrade .NET Core version manually from Console?

**Comment by punfai** [comment]
2 things to check that help me:
* In VS publish settings don't select win-x86 runtime, selecting Portable allowed me to dotnet .\[app].dll successfully on the server.
* When you cut and paste the web.config settings make sure you rename .\MyApp.dll to .\YourApp.dll in aspNetCore arguments attribute.

**Comment by RobbyDeLaet** [comment]
This exception is also generated when you try to run more than one InProcess app with the same Application Pool. The first one starts just fine. The moment you try to run another one, this message is displayed.

> Sharing an app pool among apps isn't supported. Use one app pool per app. ([Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#hosting-models))

**Comment by sezginakman** [comment]
> @mac2000 that seems like a different issue than listed above. Are you trying to run inprocess or out of process?
> 
> To confirm that things are still working with the original ANCM, can you change modules="AspNetCoreModuleV2" to modules="AspNetCoreModule"?

it's works on azure.

**Comment by lambiuk** [comment]
Check in your web.config file this line:

      <aspNetCore processPath="C:\Program Files\dotnet\dotnet.exe" arguments="exec &quot;C:\SOME_WEB_APP_PATH\bin\Debug\netcoreapp2.2\SOME_WEB_APP.dll&quot;" stdoutLogEnabled="false" hostingModel="InProcess">

And check the paths are correct. If they aren't you will get this error.

**Comment by staticdev** [comment]
I have 2 WebApi projects, on different applications in IIS. Installed the hosting bundle 2.2.1 and the first one is running ok. Then, when I publish the second one I get on the Event Viewer:

Failed to start application '/LM/W3SVC/4/ROOT/MySecondWs', ErrorCode '0x80004005'.
Only one inprocess application is allowed per IIS application pool. Please assign the application '/LM/W3SVC/4/ROOT/MySecondWs' to a different IIS application pool.

**Comment by pakrym** [comment]
@staticdev you need to assign a separate application pool to every InProcess application.

**Comment by staticdev** [comment]
I see.. but why is that?

I always had many applications running in the same application pool.

**Comment by pakrym** [comment]
Because InProcess hosting mode starts CLR instance inside application pool process and you can't have more then one CLR per process.

**Comment by staticdev** [comment]
@pakrym so what is the recommended best practice in that case? I have many applications on IIS and I share the application pool.

Should I use OutOfProcess or start creating many Application Pools?

**Comment by pakrym** [comment]
@shirhatti what should we recommend here?

**Comment by shirhatti** [comment]
@staticdev The right answer is to measure what works for you. The guidance we've maintained since IIS 7 is that 1 Web Site per application pool unless you need higher density. In the case of ASP.NET Core, it isn't that cut and dry. Based on your workload type, the higher density benefit you get from in-proc might even offset creating additional app pools.

As for your example, you can run sub-applications under separate AppPools in IIS so that you can share the binding.

**Comment by staticdev** [comment]
@shirhatti how I can I do that? Using different Application Pools in the same site?

**Comment by kucxgithub** [comment]
> @kucxgithub @Scriptworks let me clarify why what you are doing works. In ASP.NET Core 2.2, we released a new Server/ hosting pattern with IIS called IIS InProcess hosting (See: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#enable-the-iisintegration-components). To enable inprocess hosting, the csproj element AspNetCoreHostingModel is added to set the hostingModel to inprocess in the web.config file. Also, the web.config points to a new module called AspNetCoreModuleV2 which is required for inprocess hosting.
> By removing both AspNetCoreHostingModel and modifying the web.config to remove AspNetCoreModuleV2, you are reverting back to OutOfProcess hosting with Kestrel. This is totally fine to revert back to and is still supported. However, we put a lot of work into making IIS Inprocess hosting a great experience, and would appreciate people trying it.
> If the target machine you are deploying to doesn't have ANCMV2, you can't use IIS InProcess hosting. If so, the right behavior is to either install the dotnet hosting bundle (https://dotnet.microsoft.com/download/dotnet-core/2.2) to the target machine or downgrade to the AspNetCoreModule.
> @fatihyildizhan , most likely the error you are hitting is a missing version of Microsoft.NETCore.App available for your application. Try to see if there are any event logs from the AspNetCoreModuleV2 or if the app starts by running dotnet run on the commandline.

Sorry but AspNetCoreModuleV2 doesn't look ready / stable enough for me. I will consider upgrading to that when it passes my tests. As for InProcess, please continue to work on it. Thanks

**Comment by mrmowji** [comment]
@Scriptworks I'm new to ASP.Net Core. I tried changing `AspNetCoreModuleV2` to `AspNetCoreModule` and it works, but unfortunately the `web.config` file will be replaced with the released/published version every time I republish the app and I must change that property manually.
@kucxgithub 's way seems more stable.

**Comment by sezginakman** [comment]
@mrmowji <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled> is it help to you?

**Comment by mrmowji** [comment]
@sezginakman If you're asking about which solution worked for me, here it is:
> Also try removing the explicit specification of **InProcess** as the hosting model, replacing
> `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` with `<RuntimeFrameworkName>Microsoft.AspNetCore.App</RuntimeFrameworkName>`

But if it wasn't the answer you asked about, would you please rephrase your question? Thanks.

**Comment by sezginakman** [comment]
Sorry. @mrmowji `<IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>` i meant this , Thanks

**Comment by mrmowji** [comment]
@sezginakman I didn't know about that. Thanks a lot.

**Comment by cicomint** [comment]
deleting `.vs` folder work for me

**Comment by karelkral** [comment]
I have a similar problem. NetCoreApp 2.2 was deployed to IIS by WebDeploy and if set InProcess, application pool constantly crashes.  If I remove InProcess from a web.config, application works.

I have found that if I change target runtime in WebDeploy from win-x64 to Portable, InProcess started to work.

**Comment by aniyan** [comment]
Hi,

 Change your modules="AspNetCoreModuleV2"  into  modules="AspNetCoreModule"  it will work

**Comment by karelkral** [comment]
My developer experience with InProcess is terrible. At half of the cases when starting to debug (F5), an application simply does not start if using InProcess. Without any message. Simply does not start. Disabling Inprocess will help.

The bug is similar with IIS Express or IIS 10. 
NetCore app 2.2, VS 2019 RC 4.

**Comment by ikebig** [comment]
Hi,

Changing modules="AspNetCoreModuleV2" to modules="AspNetCoreModule" worked for me

**Comment by vuducthuong1102** [comment]
You install dotnet-hosting-2.2.3-win.exe. This worked for me.

**Comment by bluebaroncanada** [comment]
I don't recommend leaving it like this, but this is what fixed it for me after HOURS AND HOURS of debugging.
Right click on your site in IIS Manger > Edit Permissions > Security > Edit > Add > Type "everyone", click Check Names > OK.

**Comment by rbonomo** [comment]
What a horrible experience

**Comment by rbonomo** [comment]
For anyone wasting time trying to get their 2.2 app deployed, I just moved my code over to a new 2.1 project and got it up and running.

**Comment by anurse** [comment]
It sounds like there's a lot of different problems here (the error in question: "ANCM In-Process Handler Load Failure" can have a lot of causes). The issue was closed a while ago which generally puts it off our immediate radar (we still see the discussions but it doesn't come up in our review processes).

If you're seeing problems using ANCM In-Process, please file new issues so they get right in our faces and we can investigate them!

**Comment by bluebaroncanada** [comment]
The problem I was having is caused by Plex, so prepare yourself for more of these.

**Comment by Vincent026** [comment]
I had the same issue. It worked like a charm on my developer machine but failed with this message (HTTP Error 500.0 - ANCM - etcetera ) on our testing environment. It turned out that the web.config files where different. 

**Dev version. Works**
'<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\myapp.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="InProcess" />
    </system.webServer>
  </location>
</configuration>'

**Deployed version. Fails.** 
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" hostingModel="InProcess">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_HTTPS_PORT" value="44385" />
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>`

**Comment by bluebaroncanada** [comment]
@Vincent026 I'll bet that port is already open.

Someone should probably drop Plex a ticket for this issue.  I'll bet everyone until me has just given up.  Eventually this is going to land on your doorstep.  I'm not sure if I'm the one who should do that.  Thoughts?

**Comment by Vincent026** [comment]
@bluebaroncanada 
> I'll bet that port is already open.
> 
the port 443 is a default I filled in. The actual port number is 443 something. I also filled in ".\myapp.dl," which obviously should be replaced with ones own app.

**Comment by bluebaroncanada** [comment]
Try unsetting the port.

On Fri, Apr 12, 2019, 9:27 AM Vincent Schol <notifications@github.com<mailto:notifications@github.com>> wrote:

@bluebaroncanada<https://github.com/bluebaroncanada>

I'll bet that port is already open.

the port 443 is a default I filled in. The actual port number is 443 something. I also filled in ".\myapp.dl," which obviously should be replaced with ones own app.

**Comment by stevenjamesfrank** [comment]
In the spirit of contributing to the knowledge base when this pops up, here is my experience.

My project is ASP.NET Core 2.2, upgraded with each release.

I had a syntax error in a Javascript (JQuery) file trigger this error.  The error caused a problem with minification but didn't prevent IIS and my App from starting (at least to the point of getting this error).

I fixed the Javascript bug and poof, everything is good again.  The point being this error was caused by a cascade from a fairly unrelated source.

**Comment by justintoth** [comment]
What a nightmare... It's as if Microsoft is trying to do everything in their power to make us use IIS Express instead of IIS. Every developer I've talked to who has attempted to develop against IIS with ASP.NET Core has run into a ton of issues. After trying every suggestion in this thread, I'm STILL hitting the dreaded HTTP Error 500.0 - ANCM In-Process Handler Load Failure error. I'm at a loss on how to proceed.

**Comment by lextm** [comment]
@justintoth IIS Express is installed as part of VS, so it can receive periodical updates if needed, and it also has integrated ASP.NET Core module. However, IIS requires a separate install of ANCM, and its installer is not perfect either.

In the worst case, build ANCM from source code, https://github.com/aspnet/AspNetCore/tree/v2.2.4/src/Servers/IIS and then you can debug into its code base so as to learn what is the exact cause.

I already built [a tool to diagnose typical ANCM issues](https://docs.jexusmanager.com/tutorials/ancm-diagnostics.html). Sounds like it's time to investigate how to add some in-process model specific checks.

**Comment by justintoth** [comment]
@lextm Many of us follow the philosophy that the dev environment should be as close as possible to the QA and Prod environments, that way more issues are discovered during development rather than in QA testing or by end users in Prod. Thus, we like to use IIS. Also, it has more flexibility with being able to set common subdomains among the team (IIS bindings, e.g. dev.mydomain.com) and being able to run under certain identities (which is important for things like SQL Server windows auth.)

Thanks for the additional links, I'll give them a try. One thing I noticed as I was wrestling with this last night was that often times I'd see a useful error in the Event Log, however "http://localhost" would give me the generic ANCM page. I think at the very least, there is an opportunity for displaying that additional information on the page so it's in your face rather than having to dig into the event logs.

**Comment by scotprince** [comment]
What finally worked for me was a combination of following this great blog post (https://blog.maartenballiauw.be/post/2019/02/26/asp-net-core-iis-express-empty-error-starting-application.htmll) and changing the web.config from modules="AspNetCoreModuleV2" to modules="AspNetCoreModule".

**Comment by mateusconrad** [comment]
> @kucxgithub is absolutely spot on.
> 
> This was happening to me when I was trying to webdeploy a dotnet core 2.2 into an IIS server. Another thing that worked for me but isn't necessarily right is to actually change the handler in the web.config from
> ` <handlers> <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule**V2**" resourceType="Unspecified" /> </handlers>`
> to
> ` <handlers> <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" /> </handlers>`
> 
> Thank you 

I thank you dude. I was having this problem and probably would never find out how to fix it only by my self. Owe you one

**Comment by RamiroGarrido** [comment]
> 
> 
> Also try removing the explicit specification of **InProcess** as the hosting model, replacing
> `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` with `<RuntimeFrameworkName>Microsoft.AspNetCore.App</RuntimeFrameworkName>`

Thank you for the answer....it worked for me.....but next time would you explain why did it work?

**Comment by JayaC19** [comment]
Is there any permanent solution for this issue? Modifying the web.config is a workaround.

**Comment by mateusconrad** [comment]
i have noticed the same thing. When i fixed it, in a few days the error was happening again. I wish i have a permanent solution as well.

**Comment by anurse** [comment]
@JayaC19 @mateusconrad This is an error that can have many causes. One of the things we've improved in 3.0 is that we now produce more detailed error codes and messages in the Windows Event Log (in Production) or an error page (in Development). We are evaluating backporting this to 2.1/2.2 as well, but haven't done so yet. Current 3.0 previews have this new functionality so if upgrading is possible, that may help (Note that the 3.x LTS release is coming in November, so not too much longer now ;)).

Since there are a lot of different issues that can cause this, my suggestion would be to look at the Windows Event Log and file a *new* issue with details of the error you are seeing so we can investigate it. We don't mind having some duplicate issues if they turn out to be the same cause, so don't hestitate to click that "New Issue" button! It's easier than trying to manage a bunch of different problems in one thread :).

**Comment by rbonomo** [comment]
Got this error on fresh box with fresh IIS and fresh Windows Server deploying ASP.NET Core 2.2. I'm confident that this problem will be in the past once .Net 3.0 LTS is released. Targeting .Net Core 2.1 for now has been my solution to this problem.

**Comment by jaydg2000** [comment]
I'm having the exact opposite issue. When deployed to IIS, everything works perfectly. It's only within the IDE and running against IIS Express that I get this exact error. No idea why.

**Comment by lextm** [comment]
@jaydg2000 That's because IIS Express ships with a fixed version of ASP.NET Core module, which can be lower than the version required by your app.

**Comment by AlenToma** [comment]
Just reloaded the project and it worked

**Comment by esurmay** [comment]
you should know that: "Only one inprocess application is allowed per IIS application pool. Please assign the application '/LM/W3SVC/2/ROOT' to a different IIS application pool" 
so, if your are trying to use one App pool for two or more applications, then change and assign one to each one.

**Comment by icexe** [comment]
esurmay's  answer worked for me.  I created a separate App Pool for each app and that fixed the problem.

**Comment by ausernamedtom** [comment]
I've encountered this problem as well we had a small piece of configuration in our `Web.config` that was causing it.

```
<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout">
  <environmentVariables>
    <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
  </environmentVariables>
</aspNetCore>
```

**Comment by jstallm** [comment]
Resolution for me was to remove runtime identifier from dotnet publish command line args. I accidentally placed that in there.

**Comment by BoraKaraca** [comment]
> I'm having the exact opposite issue. When deployed to IIS, everything works perfectly. It's only within the IDE and running against IIS Express that I get this exact error. No idea why.
> 
> EDIT: Deleting the .vs folder fixed it.

Thank you. I fixed I deleted .vs folder

**Comment by theilgazcode** [comment]
I'm using Plesk Onyx 17.8.11. I checked .Net Core support and its fine. Also I installed .Net Core Runtime library then the browser returned this error. After I remove **hostingModel** attribute from this line in ` web.config` file under the published folder:

_before_ 
      `<aspNetCore processPath="dotnet" arguments=".\ProjectName.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" **hostingModel="InProcess"** />`

_after_
`<aspNetCore processPath="dotnet" arguments=".\ProjectName.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />`

and it works for me.

**Comment by roalroga** [comment]
**What is the solution??**

**Comment by 2K3O** [comment]
Publish your service as self-contained, copy the two files "**hostfxr.dll**" and "**hostpolicy.dll**" (Version 3.0.19.46305)
Afterwards publish your service as framework-dependent and replace the false / old dlls with the new ones. 
Worked for me :)

**Comment by joaocolombo** [comment]
for solve this problem you just need change the type of publish mode to self-contained, this mode will have all what your app need to run correctly 
![image](https://user-images.githubusercontent.com/11852987/69293040-6b5f1b00-0be6-11ea-8231-139b7bbd132c.png)

**Comment by WilliamRigby** [comment]
> * In VS publish settings don't select win-x86 runtime, selecting Portable allowed me to dotnet .\[app].dll successfully on the server.

Switching the target runtime from win-x64 to Portable fixed the issue for me.  Also, I'm not sure if this is an important detail, but my app pool also has "Enable 32 bit apps" set to false.

**Comment by majid23** [comment]
Change platform target to Any CPU.

![image](https://user-images.githubusercontent.com/17545658/70880739-52783880-1fdf-11ea-8c75-6148f51e63b1.png)

**Comment by mattxo** [comment]
Removing hostingModel="InProcess" in web.config did the job for me.

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
  <system.webServer>
    <handlers>
      <remove name="aspNetCore" />
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" **hostingModel="InProcess"**>
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_HTTPS_PORT" value="44382" />
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
        <environmentVariable name="COMPLUS_ForceENC" value="1" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>`

**Comment by mswilson4040** [comment]
Why is this closed exactly? Is the solution to the problem to explicitly configure the application to run `OutOfProcess`?

The only time I get this error is when I attempted to upgrade my dotnet core 2.1 project to 3.0/3.1. The application works perfectly fine locally, but when I deploy it to azure, i get the error called out. Adding an explicit `OutOfProcess` configuration in my `csproj` file did the trick, but based on what @jkotalik  is saying, Microsoft moved to a new hosting model and it doesn't work. So, why is this closed? What is the proper fix here? How do I get an azure app service to run a dotnet core 3.1 app when it was previously 2.1? I get that OutOfProcess works, but it's still not clear what the actual impacts are.

**Comment by icexe** [comment]
There seems to be multiple solutions.  The one that I use is to create an different application pool for each .net core app in IIS

**Comment by mswilson4040** [comment]
That's kind of the problem. I'm deploying my project to an Azure App Service. Configuring app pools isn't an easily found setting in there (if it even exists).

**Comment by rsudbdg** [comment]
I have the same problem after publishing my NetCore 3.1 to IIS. But it was fixed after I changed it's Application Pool - Process Model - Identity, from Built-In-Account : ApplicaationPoolIdentity' to 'LocalSystem'

**Comment by sehd** [comment]
> 
> 
> I have the same problem after publishing my NetCore 3.1 to IIS. But it was fixed after I changed it's Application Pool - Process Model - Identity, from Built-In-Account : ApplicationPoolIdentity' to 'LocalSystem'

You are a life saver man. I have upgraded my application from 2.2 to 3.1 and couldn't get it to work. This fixed it.

**Comment by lextm** [comment]
@rsudbdg Using LocalSystem is pretty bad, as you assign a too powerful account.

I think you just need to grant the default pool identity read access to the artifacts folder.

**Comment by rsudbdg** [comment]
> @rsudbdg Using LocalSystem is pretty bad, as you assign a too powerful account.
> 
> I think you just need to grant the default pool identity read access to the artifacts folder.

You are right, LocalSystem is too risky for pool identity :) .... I just changed the Identity back to ApplicationPoolIdentity, then grant IIS_IUSRS access to the App folder with 'read' permissions. It Works.

**Comment by preetam1175** [comment]
This issue Happen due to two thing 

1> don't assign hosting model Inprocess in .cproj file because asp.net core 2.2 by default Inprocess hosting model 
2>Make sure your server don't have multiple version of core run time like both  86 bits and 64 bits

Its going to fix your issue

**Comment by jwisener** [comment]
what a complete mess. trying to troubleshoot this now. what an absolute nightmare.

**Comment by jwisener** [comment]
> To add to this conversation, my issue #6465 has the same result when hosting in Azure if I manually build the system using the dotnet CLI and deploy my application to Azure. The application runs as expected locally from the executable (self-contained) and from the dotnet command line (framework dependent).
> 
> Interestingly, if I use Visual Studio to "Publish" the same application to Azure, the application works as expected. If someone can tell me where to find the event logs for ANCM in Azure I will look for them.
> 
> Note: I have the AspNetCoreRuntime.2.2.x64 extension installed.

Why was that issue closed? It still seems to be a issue if that path is set incorrectly just as @cdwaddell describes. @shirhatti why did you close that issue for?

**Comment by shirhatti** [comment]
@jwisener If you're having an issue, please file an new issue and include and relevant logs (Event Logs, [stdout](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#log-creation-and-redirection), and [ANCM diagnostics logs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#enhanced-diagnostic-logs)). Multiple folks have reported multiple different issues on this thread and it's unclear what impacts your application.

**Comment by AlbertAY** [comment]
> @kucxgithub is absolutely spot on.
> 
> This was happening to me when I was trying to webdeploy a dotnet core 2.2 into an IIS server. Another thing that worked for me but isn't necessarily right is to actually change the handler in the web.config from
> ` <handlers> <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule**V2**" resourceType="Unspecified" /> </handlers>`
> to
> ` <handlers> <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" /> </handlers>`
> 
> Thank you
