### ISSUE TITLE
Angular 7 GET/POST request with ASP.NET Core 2.2 

### ISSUE THREAD

**Issue by publicpublic70** [aspnet/AspNetCore#6114]
I have created ASP.NET Core 2.2 application and I make GET/POST requests with anuglar 7. Sometimes I get good response, sometimes not. This doesn't happen with ASP.NET Core 2.1. 

I have posted question on stackoverflow: https://stackoverflow.com/questions/53906866/neterr-invalid-http-response-error-after-post-request-with-angular-7

**Comment by pakrym** [comment]
Considering https://github.com/aspnet/AspNetCore/issues/6166 was exactly the same issue and is fixed by workaround above I'm closing this as a duplicate. Feel free to reopen.
