### ISSUE TITLE
why does  AspNetCore.Hosting.Internal.WebHost|Hosting shutdown after App start ?

### ISSUE THREAD

**Issue by bluetianx** [aspnet/AspNetCore#6123]
I run my asp net core by IIs, I find that Hosting shutdown when app has been started. I run a background task on asp.net core by using IHostedService feature. 
I has set the startMode of IIs  to AlwaysRunning.
my asp net core version is 2.1. I attach img screenshot about my log output

![tim 20181226180232](https://user-images.githubusercontent.com/29353661/50442511-33017f00-093a-11e9-91f7-f13b2eb58dcb.png)

**Comment by muratg** [comment]
Some of the possibilities:
- Config change from IIS
- AppPool recycles
- AppPool idle timeout
- ...

Given it's 1 sec into the app, probably the first.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
