### ISSUE TITLE
Trying to load signalr from static import module loader 

### ISSUE THREAD

**Issue by pablocastillaquintas** [aspnet/AspNetCore#6125]
### Describe the bug
I am trying to load signalr using the new browser feature in which they can load modules without using webpack. That way I will be able to work faster because I can just change the code, save, reload and see the new code working.

I have copied from node_modules the esm folder and pointed from javascript to it. The problem I see is that using type="module" requires pointing to javascript files, no the name. For instance:
export { HubConnection } from "./HubConnection.js"; <-- this would work
export { HubConnection } from "./HubConnection"; <-- this doesn't work

This explains it better:
https://developers.google.com/web/fundamentals/primers/modules#specifiers 

### To Reproduce
1. using asp.net core 2.1 and copied the signalr/esm folder into the wwwroot
2. importing   <script src="~/js/signalr/esm/index.js" type="module" ></script>   
3. fails with 404s because it can not find the modules

if I put .js at the end of the module names in the "~/js/signalr/esm/index.js" file, for instance 
export { HubConnectionBuilder } from "./HubConnectionBuilder";
to
export { HubConnectionBuilder } from "./HubConnectionBuilder.js";

it starts to work but I would need to change every internal reference.

### Expected behavior
Maybe having another esm compilation with the file extensions could help.

Thanks!

**Comment by BrennanConroy** [comment]
>That way I will be able to work faster because I can just change the code, save, reload and see the new code working.

I don't understand what you're trying to do, you should just be able to include signalr in the normal way through `<script src="~/lib/signalr/dist/browser/signalr.js"></script>` and when you change your code and reload, signalr will still be there.

**Comment by pablocastillaquintas** [comment]
Hi Brennan, thanks for answering

I am trying to use the new browser modules with Vue without webpack. For that I would need the extension ".js" in the esm signalr distribution. 

(I am not saying you should put it there, but maybe creating esm2 if you see demand in what I am trying).

Regards

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
