### ISSUE TITLE
Razor's GetRelatedDocuments does not work if a host documents TargetPath starts with / or \

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#6134]
### Describe the bug
If someone sets the target path of a Razor file to begin with a `/` or a `\` the [ProjectState](https://github.com/aspnet/AspNetCore-Tooling/blob/a04addb86f88cf1321e27d0e9f5440585934cffc/src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs#L444) will incorrectly track its related documents because it normalizes the target path on caching but doesn't re-normalize when trying to lookup a related document.

**Comment by rynowak** [comment]
>If someone sets the target path of a Razor file to begin with a / or a \

How does that work? This isn't something users mess with. Can we change `HostDocument` to validate the value instead, and then require upstream code to normalize the value correctly?

**Comment by mkArtakMSFT** [comment]
Closing, as there were no actual reports of this.
