### ISSUE TITLE
.net core 2.2 appends the environment variable value from web.config file and from user's system

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#6140]
_From @jsowndarrajan on Wednesday, 26 December 2018 07:17:54_

# Issue Title

Environment variable in `web.config` file get appended into system environment variable 

# General

Recently, I'm facing a strange issue while hosting .net core 2.2 application on IIS.

After hosting, I get "An error occurred while starting the application". In order to identify the root cause I enabled the log file and found that its because of environment variable issue.

I configured the environment variable in my `web.config` file as like below, at the same time I also configured the same (ASPNETCORE_ENVIRONMENT) environment variable in my system.

```
<aspNetCore processPath="dotnet" arguments=".\PctrClient.Api.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="InProcess">
    <environmentVariables>
      <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
    </environmentVariables>
  </aspNetCore>
```  

But when I try to host this application in IIS, I get ASPNETCORE_ENVIRONMENT variable value as `Development;Development`, instead of `Development`. I think, application is now appending both system environment value and web.config variable value together.

Program.cs

```
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
               .UseStartup<Startup>()
               .UseIISIntegration();
}
```

From my perceptive, `web.config` should override the system environment variable value.

Please let me know if you need any other information from my end.

_Copied from original issue: dotnet/core#2184_

**Comment by jsowndarrajan** [comment]
Hi Ellison, Thanks for the response. From my perspective we have to check `web.config` first, if the env variable present there we can use it, otherwise we have to check system level configuration. 

But right now we are reading the value from both places and more importantly we are concatenate those value. I think it's strange behavior. 

I don't know the actual intention behind appending the env values?!

If it's working as per the design, is there any plan to change it in the future releases?

**Comment by Tratcher** [comment]
@shirhatti @pakrym @jkotalik 

It's a toss up, different environment variables want different semantics. E.g. for PATH you'd want to append (or prepend?), but for ASPNETCORE_ENVIRONMENT you'd want to replace. It seems like the environmentVariable config node should let you specify the behavior.

**Comment by pakrym** [comment]
Dup https://github.com/aspnet/AspNetCore/issues/4566 we even have PR https://github.com/aspnet/AspNetCore/pull/6083

I think we should just override in most cases. Overriding path seems fine if customer decided to do it.

**Comment by Tratcher** [comment]
Does it support nesting? E.g. `"{PATH};c:\mypath"`

**Comment by pakrym** [comment]
I'll add tests, it should.

**Comment by shirhatti** [comment]
@guardrex Can we have this behavior added to the docs? I believe this would be the appropriate section- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#setting-environment-variables

**Comment by guardrex** [comment]
@shirhatti :+1: I'll get that scheduled.

**Comment by alexlchen** [comment]
I have the same issue. When I changed the environment variable value from "Development" to "Staging" or "Product",  The error happened and showed "HTTP Error 500.30 - ANCM In-Process Start Failure".
After I set it back to "Development", everything is ok.
LaunchSetting.json
{
"profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Product"
      }
    }
  },
}

**Comment by lccarvalho** [comment]
Hi, I see that the issue is closed and to be honest I couldn't conclude if you are still thinking about this or the feature will be let as is. If I can vote here the append solution seems absurd to me. Why couldn't I have a server where most apps are for staging and certain ones are for production?

**Comment by lesscodetxm** [comment]
We're having the same issue. We had a system-level environment variable defined on our server as `Development`, but our app wasn't seeing it so we added `/p:EnvironmentName=Development` to our `dotnet publish ...` command. After we restarted our server we now got `Development;Development` at app startup. Now we can't get `dotnet publish` to _stop_ writing the environment variable to `web.config`. We removed the parameter from our command line but the generated `web.config` still defines the env var. It's obviously being cached somewhere, but no idea where.

How would a list of environments ever be considered valid?

**Comment by guardrex** [comment]
@lesscodetxm It's a known scenario to engineering, and we provided coverage in the topic. You'd need to open an issue with them on the engineering repo to discuss it further; but since they've already responded that the behavior is by-design, I don't think they'll address it further.

See the **WARNING** note at :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#setting-environment-variables

btw - Please use the **This Page** feedback button at the bottom of a topic to open a new issue. We aren't as effective working with closed issues.

**Comment by echuck66** [comment]
All I can say is that for developers obsessed with the concept of Single Responsibility (and if you're not, you should be), it seems very strange to allow so many different ways to set the environment variables. Concatenating the ASPNETCORE_ENVIRONMENT values is idiotic and the Asp.Net Core developers should account for this behavior from other teams having this as a design feature to accommodate other variables such as $PATH, which have a valid reason to concatenate.

When Asp.Net Core uses this specific variable to determine the startup classes and settings files, it would seem prudent to at least look at the issue and ensure that the value is NOT concatenated.

Now my Visual Studio is completely useless for a debugging app  because of this automatic re-write "feature".

**Comment by CarvellWakeman** [comment]
Maybe I'm not understanding the situation - my HostingEnvironment.EnvironmentName is set to "Development;Development" at runtime. However ASPNETCORE_ENVIRONMENT is **only** set in my web.config. There is no ASPNETCORE_ENVIRONMENT variable set in my system or user environment variables. Both the Windows Environment Variables AND powershell Get-Item Env:ASPNETCORE_ENVIRONMENT are showing nothing.

Yet my EnvironmentName is still "Development;Development". What is the argument for this being a "feature", I seem to have missed it in the conversation above...

**Comment by echuck66** [comment]
Check your project properties/options. It's under the Run -> Configurations -> Default. There's a list of Environment Variables (usually just has the ASPNETCORE_ENVIRONMENT variable, and it's set to Development by default.

**Comment by echuck66** [comment]
As a workaround, in Program.cs, you can use something like this:

`#if DEBUG 
       Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT, "Devevlopment");
#endif`

This will override the duplicated values and allow you to work unencumbered on your development machine at least. For deployments, I still have to remember to remove that line from the generated Web.Config file.

**Comment by echuck66** [comment]
From the ASP.NET Core Module document (link further up in comments):

> Environment variables set in this section take precedence over system environment variables.

This is a very misleading statement. It doesn't take precedence because it does not override existing values... it concatenates them, rendering the variable useless.

**Comment by CarvellWakeman** [comment]
Project properties => Debug is just a GUI around launchsettings.json, and launchsettings is used to generate a web.config at build-time when running in IIS (not express). My ASPNETCORE_ENVIRONMENT is set to Banana in launchsettings.json, and therefore also set to Banana in web.config after a build.

I have **no** system environment variable for ASPNETCORE_ENVIRONMENT, so the _only_ value should be coming from the web.config, yet at runtime my HostingEnvironment.EnvironmentName is "Development;Banana".

The GOOD news is that a system reboot fixed this problem. Apparently the ASPNETCORE_ENVIRONMENT variable got sticky and something wouldn't let go of it.

**Comment by bati06** [comment]
I think that concatenating values (from system and web.config) for this variable is definitely a BUG.

I have a scenario where there is a server with different sites hosted on it (in IIS).

Some of the sites which is not managed by me is using the system environment variable ASPNETCORE_ENVIRONMENT=development (They should not do this way but that's the situation.)

The site I manage is using web.config to set the ASPNETCORE_ENVIRONMENT variable not globally but only locally for this website. (ASPNETCORE_ENVIRONMENT=Release)
The end result is that my application gets environment variable ASPNETCORE_ENVIRONMENT=development;Release.
