### ISSUE TITLE
[SignalR] Unexpected behavior with `StreamAsChannelAsync` and `ReadAsync`

### ISSUE THREAD

**Issue by pekkah** [aspnet/AspNetCore#6143]
### Describe the bug

Hub method is called when `ChannelReader.ReadAsync` is called on the client side. I would've expected that calling `StreamAsChannelAsync` would call the hub method.  

I have a integration test where I call the `StreamAs..` method to get the reader. Then I write a message to the channel on server side and then try to read the value from the reader. This does not work as expected as the actual hub method is not getting called when I call the `Stream..` but gets called later when I try to read the value.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Run this code 'todo'
3. With these arguments 'todo'

### Expected behavior

When calling `StreamAs...` method I get a ChannelReader. I would expect that when this call was made the actual hub method on the server side would be called at this point. Now it seems that the call is made when I call ChannelReader.ReadAsync method. 

### Additional context
Include the output of `dotnet --info`

**Comment by bradygaster** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
