### ISSUE TITLE
EventedStreamReader not really emitting OnCompleteLine() per each line received

### ISSUE THREAD

**Issue by dgaspar** [aspnet/AspNetCore#6146]
### Describe the bug
[EventedStreamReader's Run()](https://github.com/aspnet/AspNetCore/blob/cb1917aa5990a701b92fc44f28f76b0718c76197/src/JavaScriptServices/src/Microsoft.AspNetCore.SpaServices.Extensions/Util/EventedStreamReader.cs#L92) method sometimes reads chunks containing multiple `\n`, but it only cares about the first `\n` it sees, and buffers the rest. The problem is when the chunk is the last output coming of npm during `npm run serve`, for a while. The remaining buffer is not notified (`OnCompleteLine()` is not called).

The risk is [WaitFor(Regex regex)](https://github.com/aspnet/AspNetCore/blob/cb1917aa5990a701b92fc44f28f76b0718c76197/src/JavaScriptServices/src/Microsoft.AspNetCore.SpaServices.Extensions/Util/EventedStreamReader.cs#L58) randomly missing the opportunity to finish, because it might miss some lines, as it listens to `onReceivedLineHandler`, and not to chunk events.

### To Reproduce
1. ASP.Net Core 2.2 with Spa extensions;
2. tricky to reproduce: the app reads from `npm`'s stdout a stream chunk that contains multiple `\n` characters in it;
3. notice how only the first chunk (until the first `\n`) gets notified to the event listeners, the rest doesn't.

### Expected behavior
I would expect one call to OnCompleteLine() per actual line.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dgaspar.
Would you be interested in sending us a PR for this? We'll happily consider it.

**Comment by mkArtakMSFT** [comment]
Thanks for your contribution, @dgaspar👍
