### ISSUE TITLE
Stop deleting old or closed Issues...

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#6151]
Please, stop deleting old or closed Issues, which I found to be the best source of learning and understanding Blazor. I'm certain that many developers like me keep a list of bookmarks, which they reference time and again.

**Comment by mikaelm12** [comment]
So we recently consolidated all our repos in the aspnet org to a few repos and in doing so a bunch of links to older issues broke ☹️. At least to my knowledge, we never delete issues on github so in theory the issues you are referring to should still exist in the aspnet/AspNetCore repo. Sorry for the inconvenience though!

**Comment by enetstudio** [comment]
Good to hear that... Thanks a lot, mikaelm12

**Comment by mikaelm12** [comment]
We have a label for the Blazor issues. Here is the query link 
https://github.com/aspnet/AspNetCore/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Afeature-blazor+

Does this contain the issues you were thinking of @A51UK ?

**Comment by A51UK** [comment]
Yes thank you.

**Comment by enetstudio** [comment]
@mikaelm12: Does this contain the issues you were thinking of @A51UK ?

No, it does NOT... Many Issues cannot any longer be accessed. I've dozens of bookmarks to these important issues, though closed, are of immense importance to me, and yet are not available. I've trusted Github, but not any longer. And from now on I store important issues and samples on my computer.
