### ISSUE TITLE
SMTP send throws AuthenticationException only from within Docker container

### ISSUE THREAD

**Issue by kspearrin** [aspnet/AspNetCore#6152]
### Describe the bug

_I understand that SMTP mail sending is not really a ASP.NET thing, however, this issue seems to surface due the application running in a docker container built from the ASP.NET Core image, so I figured it was worthy of being opened as an issue in this repo. Please let me know if I should open elsewhere._

------------

Certain SMTP mail servers (in this case, mailjet.com) will throw an `AuthenticationException` when trying to send mail from an ASP.NET Core application that is running in an ASP.NET Core Docker container.

For example:

    var client = new SmtpClient(_configuration.GetValue<string>("smtp:host"),
        _configuration.GetValue<int>("smtp:port"))
    {
        EnableSsl = _configuration.GetValue<bool>("smtp:ssl"),
        DeliveryMethod = SmtpDeliveryMethod.Network,
        Credentials = new NetworkCredential(_configuration.GetValue<string>("smtp:username"),
            _configuration.GetValue<string>("smtp:password"))
    };

    var message = new MailMessage
    {
        From = new MailAddress(_configuration.GetValue<string>("smtp:from")),
        Subject = "Testing SMTP Email",
        SubjectEncoding = Encoding.UTF8,
        BodyEncoding = Encoding.UTF8,
        BodyTransferEncoding = System.Net.Mime.TransferEncoding.QuotedPrintable,
        Body = "<p>Hi, This is a test email.</p>",
        IsBodyHtml = true
    };

    message.To.Add(new MailAddress(_configuration.GetValue<string>("smtp:to")));
    client.SendCompleted += (sender, e) =>
    {
        if(e.Error != null)
        {
            _logger.LogError(e.Error, "SendCompleted Error");
        }

        if(e.Cancelled)
        {
            _logger.LogError("SendCompleted Cancelled");
        }

        message.Dispose();
        client.Dispose();
    };

    client.SendAsync(message, null);

Using my SMTP settings provided by mailjet.com, I can send email just fine from this application running locally (Windows 10) or when the application deployed to Azure via Visual Studio "Publish".

```
{
  "Smtp": {
    "Host": "in-v3.mailjet.com",
    "Port": 587,
    "Ssl": true,
    "Username": "myusername",
    "Password": "mypassword",
    "From": "myapp@example.com",
    "To": "me@example.com"
  }
}
```

However, if I build this application into a Docker image (smtp appsettings provided via `--env-file`), it fails to send mail with an `AuthenticationException`.

> System.Net.Mail.SmtpException: Failure sending mail. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

I can change my mail settings to another server, such as SendGrid, and it works fine both on my local machine, Azure, and in the Docker container.

It seems like this is a problem with a missing CA for mailjet's SSL cert, but I can see the DigiCert CA inside the Docker container if I bash in and look.

I don't understand why it works in other environments, but not this Docker container.

### To Reproduce
1. Create a free account on mailjet.com
2. Clone this test repo that I created showing the problem: https://github.com/kspearrin/dockersmtptest
3. Create an env-file for your appsettings. Example:
```
smtp__host=in-v3.mailjet.com
smtp__port=587
smtp__ssl=true
smtp__username=myusername
smtp__password=mypassword
smtp__to=myapp@example.com
smtp__from=me@example.com
logDirectory=/app/logs
```
4. Build the docker image and run it:
```
docker build --no-cache -t dockersmtptest ./
docker run -d --env-file=/path/to/appsettings.env -p 5012:80 -v /path/to/logs:/app/logs dockersmtptest
```
5. Visit http://localhost:5012/api/mail to try and send the email

If you mapped the logs directory volume, you should find a log file with the exceptions since Serilog is configured to write to a rolling file.

### Expected behavior
Should be able to send mail using mailjet.com from application running inside ASP.NET Core docker container just like I can when running it locally.

### Screenshots
n/a

### Additional context
n/a

**Comment by kspearrin** [comment]
I have only tested it with a web app from the Docker container so far.

**Comment by Eilon** [comment]
I think that would help narrow it down. As you mentioned earlier, it seems somewhat unlikely to be related to ASP.NET Core. If that's the case, this bug should move over to dotnet/corefx.

**Comment by kspearrin** [comment]
@Eilon The same problem occurs when running this as a console app built using the `microsoft/dotnet:2.1-aspnetcore-runtime` image. Example:

Console app

```
    class Program
    {
        static void Main(string[] args)
        {
            MainAsync().Wait();
        }

        public static async Task MainAsync()
        {
            try
            {
                var client = new SmtpClient("in-v3.mailjet.com", 587)
                {
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    Credentials = new NetworkCredential("user",
                        "password")
                };

                var message = new MailMessage
                {
                    From = new MailAddress("app@example.com"),
                    Subject = "Testing SMTP Email",
                    SubjectEncoding = Encoding.UTF8,
                    BodyEncoding = Encoding.UTF8,
                    BodyTransferEncoding = System.Net.Mime.TransferEncoding.QuotedPrintable,
                    Body = "<p>Hi, This is a test email.</p>",
                    IsBodyHtml = true
                };

                message.To.Add(new MailAddress("me@example.com"));
                client.SendCompleted += (sender, e) =>
                {
                    if(e.Error != null)
                    {
                        Console.WriteLine("SendCompleted Error: " + e.Error.Message + " : " + e.Error.ToString());
                    }

                    if(e.Cancelled)
                    {
                        Console.WriteLine("SendCompleted Cancelled");
                    }

                    message.Dispose();
                    client.Dispose();
                };

                client.SendAsync(message, null);
                Console.WriteLine("Mail sent.");
            }
            catch(Exception e)
            {
                Console.WriteLine("There was an exception. " + e.Message);
            }

            await Task.Delay(2000);
            Console.ReadLine();
            await Task.Delay(2000);
            Console.ReadLine();
        }
    }
```

Dockerfile

```
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ConsoleApp6/ConsoleApp6.csproj ConsoleApp6/
RUN dotnet restore ConsoleApp6/ConsoleApp6.csproj
COPY . .
WORKDIR /src/ConsoleApp6
RUN dotnet build ConsoleApp6.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish ConsoleApp6.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ConsoleApp6.dll"]
```

Build and run

```
> docker build --no-cache -t dockerconsolesmtptest ./
> docker run dockerconsolesmtptest
```

Run output

```
Mail sent.
SendCompleted Error: Failure sending mail. : System.Net.Mail.SmtpException: Failure sending mail. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticateCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
```

**Comment by Eilon** [comment]
And do you know if it happens in the regular, non-ASP.NET Core Docker container (just plain .NET Core)? Either way this bug seems like it's a better fit for https://github.com/dotnet/corefx because this seems more to do with networking/SMTP than with ASP.NET.

**Comment by kspearrin** [comment]
@Eilon I just tried this with dotnet core on Linux (Ubuntu, no docker) and the same issue occurs. So it would appear that is isn't really an issue with the Docker images. I will re-open the issue on corefx. Thanks.

**Comment by kspearrin** [comment]
For reference: https://github.com/dotnet/corefx/issues/34407
