### ISSUE TITLE
Add SaveTokens property to AzureADB2COptions

### ISSUE THREAD

**Issue by ntnext222** [aspnet/AspNetCore#6157]
I want to get the `id_token` of the user who signed in with AzureADB2C.
However, because the **SaveTokens** property does not exist in the `AzureADB2COptions`
used in extension method: `Microsoft.AspNetCore.Authentication.AddAzureADB2C()`.
`id_token` can not be acquired with `HttpContext.GetTokenAsync ("id_token")`.
Can implement the **SaveTokens** property like `OpenIdConnectOptions`?

I think that it is possible, If modify the `Microsoft.AspNetCore.Authentication.AzureADB2C.UI.OpenIdConnectOptionsConfiguration.Configure()`.

**Comment by brockallen** [comment]
Why wouldn't the AzureAD implementation just extend the OIDC one?

**Comment by Eilon** [comment]
@HaoK - can you show how to get to these settings via the scheme? https://github.com/aspnet/AspNetCore/blob/master/src/Azure/AzureAD/Authentication.AzureADB2C.UI/src/AzureAdB2CDefaults.cs#L23

**Comment by Eilon** [comment]
@HaoK - can you log a doc bug to improve https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-2.2 to better describe some of these scenarios?

**Comment by HaoK** [comment]
The actual OpenIdConnectOptions is still there and can be configured via the `AzureADB2CDefaults.OpenIdScheme` by default.

`Configure<OpenIdConnectOptions>(AzureADB2CDefaults.OpenIdScheme, o => { ... }` similarly you can call authenticate against that to get the correct result to get the token from

**Comment by ntnext222** [comment]
Thanks! Resolved.
