### ISSUE TITLE
[Blazor] Creating a onClick event causes problems with custom component bindings

### ISSUE THREAD

**Issue by bytedreamer** [aspnet/AspNetCore#6158]
### Describe the bug
I am trying to create a one-way read binding from a custom component. This read occurs when a user click on a button with a onClick action. When the button is clicked the local variable on the parent assigned to the component binding appears to revert back to the initialized value.

### To Reproduce
1. Using  0.8.0 Preview of Blazor
2. Run this code [index.cshtml](https://github.com/bytedreamer/StringListCompare/blob/Component-Test/Pages/Index.cshtml)

### Expected behavior
 Expect to read the StringList1 and StringList2 values from the StringLists component

### Actual behavior
The values are set to empty strings. 

I'm going to attempt to use the new client debugging capabilities to get more details

**Comment by Mirch** [comment]
I couldn't reproduce it using your code. When are you verifying for the string list values?

**Comment by bytedreamer** [comment]
@Eilon I'm new to this code base. Is there a good place in the codebase to start diagnosing this issue.

**Comment by Eilon** [comment]
Hi @bytedreamer , welcome to the repo! @SteveSandersonMS  and @rynowak are the experts in this area and should be able to assist.

**Comment by rynowak** [comment]
@bytedreamer - you shouldn't need `bind` on your readonly textareas. `bind-...` is for two-way interactions.

I would expect this to look like:
```
<textarea readonly>@_except1</textarea>
```

As for why the binding is clearing the value of `_except1` that's a mystery to me. Using bind on a textarea will hook up the `onchange` event and the value property. https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/test/Microsoft.AspNetCore.Razor.Test.ComponentShim/Microsoft.AspNetCore.Components/BindAttributes.cs#L22

We do have some e2e tests for textarea: https://github.com/aspnet/AspNetCore/blob/master/src/Components/test/Microsoft.AspNetCore.Components.E2ETest/Tests/BindTest.cs#L78

**Comment by bytedreamer** [comment]
It is the _stringList1 and _stringList2 values that are emptying out when the onclick event is fired.

**Comment by bytedreamer** [comment]
Updated the code, it should have had those two values in a custom component. Guess you sometimes forget to commit up when it's past midnight.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
