### ISSUE TITLE
Authentication not work on netcoreapp2.2 http site

### ISSUE THREAD

**Issue by xiaoxin01** [aspnet/AspNetCore#6159]
Hi,

### Describe the bug
If I new a mvc site when individual authentication base on netcoreapp2.2 and disable UseHttpsRedirection, then user can't login in http site (http://localhost:5000) but https site(https://localhost:5001).

Is this a bug, or something more I need to do for http site?

### To Reproduce
1. Using this version of ASP.NET Core 'netcoreapp2.2'
2. dotnet new mvc--no-https -au Individual
3. mark following code:
```c#
            //app.UseHttpsRedirection();
            app.UseStaticFiles();
            //app.UseCookiePolicy();
```
4. access http://localhost:5000, regist and login

### Expected behavior
User can login on http site.

Thanks:)

**Comment by blowdart** [comment]
You disabled cookie policy as well as Https. You need cookie policy to login. 

Out of interest why would you disable HTTPS?

**Comment by xiaoxin01** [comment]
@blowdart Thanks for your response.
I only apply my web in our intranet, so not need https.
