### ISSUE TITLE
StateHasChanged stops working if called during Renderer.ProcessRenderQueue

### ISSUE THREAD

**Issue by bofirial** [aspnet/AspNetCore#6164]
### Describe the bug
I created a timer in a component that calls StateHasChanged every 100ms.  If StateHasChanged is called at a very specific time, then it has no effect and all subsequent calls to StateHasChanged also have no effect.  The component is not rendered and the page does not update.

I believe that the application got into a state where [_hasPendingQueuedRender is true](https://github.com/aspnet/AspNetCore/blob/62dd8f4bd999e4181cb7e5d9fd8901eee943af30/src/Components/src/Microsoft.AspNetCore.Components/ComponentBase.cs#L100) but there is nothing currently rendering in the Renderer.  This can happen if StateHasChanged is called while the [Renderer is finishing Processing the Render Queue](https://github.com/aspnet/AspNetCore/blob/436b5461ad0337aac90089aa7ccb61dd875808e4/src/Components/src/Microsoft.AspNetCore.Components/Rendering/Renderer.cs#L212-L219).  When StateHasChanged is called [_hasPendingQueuedRender is set to true](https://github.com/aspnet/AspNetCore/blob/62dd8f4bd999e4181cb7e5d9fd8901eee943af30/src/Components/src/Microsoft.AspNetCore.Components/ComponentBase.cs#L107-L108) but because the previous batch is still finishing [_isBatchInProgress is true so ProcessRenderQueue is not called](https://github.com/aspnet/AspNetCore/blob/436b5461ad0337aac90089aa7ccb61dd875808e4/src/Components/src/Microsoft.AspNetCore.Components/Rendering/Renderer.cs#L182).  Since ProcessRenderQueue is not called _hasPendingQueuedRender is never set back to false so [StateHasChanged becomes a no-op](https://github.com/aspnet/AspNetCore/blob/62dd8f4bd999e4181cb7e5d9fd8901eee943af30/src/Components/src/Microsoft.AspNetCore.Components/ComponentBase.cs#L100).

I tested this theory by calling [base.BuildRenderTree(null)](https://github.com/aspnet/AspNetCore/blob/62dd8f4bd999e4181cb7e5d9fd8901eee943af30/src/Components/src/Microsoft.AspNetCore.Components/ComponentBase.cs#L55-L56) before calling StateHasChanged and the component renders correctly.  I am also able to get the component to render correctly by delaying the call to StateHasChanged by 100ms.

### To Reproduce
1. Using Blazor 0.7.0

I have not been able to create a simple scenario to reproduce the issue.

[Here](https://github.com/bofirial/BlazorTechnologyCharacterGenerator/tree/state-has-changed-issue) is a branch in my repository that reproduces the problem on my machine.  I'm not sure if it will reproduce the issue on other machines since the problem relies on calling StateHasChanged at a very particular time.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @bofirial.
@SteveSandersonMS is this the bug you've already fixed?

**Comment by danroth27** [comment]
We think this works now. If you're still seeing this problem with the latest bits please let us know!
