### ISSUE TITLE
Razor should name the BackgroundParser threads

### ISSUE THREAD

**Issue by KirillOsenkov** [aspnet/AspNetCore#6171]
![image](https://user-images.githubusercontent.com/679326/50532754-ce2d5c80-0ad2-11e9-9581-1ca1642553bc.png)

It would be nice for debugging if Razor named the threads it's spinning on. I'm also contacting other guilty parties such as Roslyn so that we have a clean Threads window ;)

**Comment by rynowak** [comment]
It would be even nicer if we didn't create a thread-per-editor 😆 - I totally agree through
