### ISSUE TITLE
Middleware not always able to read user when multiple JWT bearer schemes used

### ISSUE THREAD

**Issue by rgmills** [aspnet/AspNetCore#6174]
### Describe the bug
When multiple JWT authentication schemes are registered and you have middleware between Authentication and Mvc only the first handler is evaluated before your middleware is invoked.  If the middleware is attempting to do some early processing on the authenticated user ( it will be unable to reliably do so.

### To Reproduce
1. Using ASP.NET Core 2.1 and/or 2.2
2. Sample code exhibits issue can be found here: https://github.com/rgmills/authmiddleware-issue (project is targeting 2.1, but issue was observed on 2.2 also)
3. Issue a `GET localhost:5000/sample/bearer2`
     - Output is {"token": "jwtgoodness"}
4. Issue `POST localhost:5000/sample/bearer2 Authorization: Bearer "jwtgoodness"`
5. Observe ContextMiddleware emits `False` based on the expression `context.User.Identity.IsAuthenticated`
6. If you replace the calls to `bearer2` with `bearer1` you'll see the expression `context.User.Identity.IsAuthenticated` when evaluated from the middleware emits `True`

### Expected behavior
Middleware would be executed with the `HttpContext.User` filled with the authenticated user regardless of the order in which handlers are registered.

### Screenshots
![image](https://user-images.githubusercontent.com/178635/50533681-b4a10a80-0afc-11e9-9bdb-ebb5c93bea11.png)

### Additional context
I looked at https://github.com/aspnet/AspNetCore/issues/6033 which is similar with multiple JWT bearer schemes, but middleware is not part of that issue.

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by Kahbazi** [comment]
This is not a problem. This is how `UseAuthentication` works. The middleware would only authenticate with the default Schema (https://github.com/aspnet/AspNetCore/blob/62351067ff4c1401556725b401478e648b66acdc/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs#L54) which in your case is `Bearer 1`, therefore the authentication for `Bearer 2` would never be called.

**Comment by Kahbazi** [comment]
This is why
https://github.com/rgmills/authmiddleware-issue/blob/master/Startup.cs#L81

**Comment by rgmills** [comment]
It all makes sense now, thanks @Kahbazi
