### ISSUE TITLE
Blazor - HTTP - Configure between Fetch and XHR

### ISSUE THREAD

**Issue by LukeTOBrien** [aspnet/AspNetCore#6176]
Hello there,

I am interested in Blazor as I am planning to start a new project in perhaps a year or so time (no time scale as yet), at which point Blazor might be stable for production.  
I am interested in developing Cordova and Electron apps using a single codebase.

I have found a [blog article guide to Blazor/Cordova](https://medium.com/@bickellukas98/blazor-cordova-a3b0a6c3bf10).  
In the article one of the issues he had is that the `http` class uses the Fetch API rather than XHR, he had to fix the issue by overriding the browsers Fetch API with his own implementation using XMLHttpRequest.

So my suggestion is that the developer should be allowed to configure `http` to use Fetch or XHR.  
I think this could be done using a simple property or method on the `http` class, something like `http.UseXhr()`.

What do you think about this suggestion?

Hope this meets with you well and I look forward to seeing how this project evolves.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @LukeTOBrien.
This is not something we plan to provide support for in the near future.
