### ISSUE TITLE
Change IsAjaxRequest in IsApiRequest in CookieAuthenticationEvents

### ISSUE THREAD

**Issue by CoolGoose** [aspnet/AspNetCore#6181]
It would be ideal to have a way of overwriting the IsAjaxRequest method in order to cover API only implementations

### Describe the solution you'd like
I would propose renaming IsAjaxRequest into IsApiRequest and use the same function body as we currently have.

### Describe alternatives you've considered
Overwriting each event individually.

**Comment by blowdart** [comment]
Why would this be ideal? If you're calling APIs you really ought to consider switching to bearer tokens, unless you're stuck in the browser, in which case it is an Ajax request.

What are you trying to achieve?

**Comment by CoolGoose** [comment]
I am doing web requests with a JWT token (mostly experimenting with an api only backend to a vuejs spa). Unless I am overwriting the methods I am getting an unwanted http response code (since technically it returns the 302 for the to login page redirect).

**Comment by Eilon** [comment]
Unfortunately this would be a breaking change to gain minimal value, so we are closing this issue.

Also, it seems like cookies and JWT are being mixed, though they shouldn't be used together. If you're having some other issue, please log a new issue with details.

**Comment by CoolGoose** [comment]
@Eilon just to clarify for anybody else that might have this issue. If the cookie auth is on, and you also have JWT , it doesn't matter that JWT works, the cookie technically has precedence on the redirect . Am i reading this correct ?

**Comment by CoolGoose** [comment]
Thanks, makes sense. Will try updating the documentation this week to explain it since it's a bit confusing initially since both the token works and the redirect 'happens' based on the http code
