### ISSUE TITLE
Add guardrails for 2.X Razor mixed with netcoreapp3.0

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6182]
It's easy to get **wierd** errors from MSBuild with unsupported combinations of the Razor.Design package and netcoreapp3.0. These can be like:
```
obj\Debug\netcoreapp3.0\HostedInAspNet.Server.RazorTargetAssemblyInfo.cs(12,12): error CS0579: Duplicate 'Microsoft.AspNetCore.Mvc.ApplicationParts.ProvideApplicationPartFactoryAttribute' attribute [C:\git\aspnet\AspNetCore\src\Components\blazor\samples\HostedInAspNet.Server\HostedInAspNet.Server.csproj]
```

OR

```
C:\Users\rynowak\.nuget\packages\microsoft.net.sdk.razor\3.0.0-preview.18629.1\build\netstandard2.0\Sdk.Razor.CurrentVersion.targets(308,5): error MSB4044: The "FindInList" task was not given a value for the required parameter "ItemSpecToFind". [C:\git\aspnet\AspNetCore\src\Components\samples\ComponentsApp.App\ComponentsApp.App.csproj]
```

Since our version strategy is tied to the shared framework version, we need to introduce some better error messages for these cases. We should detect up front if an invalid combo is being used (based on Razor Configuration) and report a more descriptive error.

**Comment by gulbanana** [comment]
what’s the supported combination, writing components themselves in netstandard2.0 and a backend that hosts them in netcoreapp3.0?

**Comment by mkArtakMSFT** [comment]
@pranavkm is this already done?

**Comment by mkArtakMSFT** [comment]
Confirmed with @pranavkm. This is done!
