### ISSUE TITLE
Anonymous only in ASP.NET core Identity

### ISSUE THREAD

**Issue by QuangDuong120198** [aspnet/AspNetCore#6193]
I am working on my course project, which uses ASP.NET core Identity.

Today, I have just figured out a little problem: **If an user is authenticated, then he/she is still able to access `Login` page and `Register` page.** Some how, I have forgotten to check it until today.

My solution is checking whether the user is authenticated in those files (`Register.cshtml.cs` and `Login.cshtml.cs`) - if yes, I redirect to the index page.
Of course it's work, but for me, at least for me, that solution is not satisfying.
That's my first solution, also the only one worked. I've come up with others ideas:
* Customize an attribute that inherit `Microsoft.AspNetCore.Authorization.AuthorizeAttribute` class, and "reverse" it.
* Redirect from the `_ViewImport.cshtml` file in the `Areas/Identity/Pages/Account` directory.

I prefer the first idea. While `AllowAnonymousAttribute` allow all authenticated and unauthenticated users, `AuthorizeAttribute` only allow authenticated users, I wonder why there is no attribute like `AnonymousOnlyAttribute`. I am pretty sure that the contributors have though about this before.

Is that "attribute" necessary?

**Comment by blowdart** [comment]
Why would we want authenticated users to not create new users, or switch their login to another account?

This requirement isn't generic enough for use to make a default in templates, so I'm afraid it's something you'll have to implement yourself, like you have.
