### ISSUE TITLE
SignalR: Wrongly serialized DateTimeOffset using MessagePack

### ISSUE THREAD

**Issue by emilmuller** [aspnet/AspNetCore#6194]
Receiving a DateTimeOffset on the client side in JavaScript results in an incorrect date if not located at the datum line.

I am unsure if this is a bug in MessagePack (I'm assuming the default behaviour should not yield something incorrect), or if it's a [custom serializer](https://github.com/msgpack/msgpack-cli/wiki/Custom-serialization) in SignalR. If this is not a a SignalR bug, I suggest that SignalR clearly defines how DateTimeOffset is serialized, because the user of the library cannot know if changing the serialization logic for native types will mess with SignalR's internals.

The bug:

When receiving a DateTimeOffset in JavaScript using MessagePack, the output will be an array of what I'm assuming is a Date + time zone offset in minutes. E.g.:

`[Date, time zone offset in minutes]`

In my case, when I send the DateTimeOffset 20:45 (GMT +1), what I receive is:

`[Sun Dec 30 2018 21:45:00 GMT+0100 (Central European Standard Time), 60]`

So it's messing up the time zone, all the while informing me of the time zone offset. I am currently reluctant to create a custom serializer for DateTimeOffset as I'm unsure if SignalR uses that type internally and if it will have any consequences.

Kind regards

**Comment by bradygaster** [comment]
@bradygaster will validate this is in our docs and close this when it is, or if it is. :)

**Comment by halter73** [comment]
This was doc'd as a "quirk" of the messagepack encoding
