### ISSUE TITLE
What is the Difference Between UseIIS and UseIISIntegration?

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/AspNetCore#6197]
[`WebHost.CreateDefaultBuilder`](https://github.com/aspnet/AspNetCore/blob/3c09d644cccdb21801f7a79e1188a1a1212de5d9/src/DefaultBuilder/src/WebHost.cs#L228-L229) calls both [`UseIIS`](https://github.com/aspnet/AspNetCore/blob/45d1c054b2bf1d4df33c98c5a3de88417c9cf1bd/src/Servers/IIS/src/Microsoft.AspNetCore.Server.IIS/WebHostBuilderIISExtensions.cs) and [`UseIISIntegration`](https://github.com/aspnet/AspNetCore/blob/3c09d644cccdb21801f7a79e1188a1a1212de5d9/src/Servers/IIS/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs). Looking at the code for both, they have the exact same comment, suggesting that they do the same thing:

```
/// <summary>
/// Configures the port and base path the server should listen on when 
/// running behind AspNetCoreModule. The app will also be configured 
/// to capture startup errors.
/// </summary>
```

`UseIIS` lives in the `Microsoft.AspNetCore.Server.IIS` package, while `UseIISIntegration` lives in `Microsoft.AspNetCore.Server.IISIntegration`. What is the difference between the two? When do you need to use one versus the other? Why does `WebHost.CreateDefaultBuilder` call both?

**Comment by dallancarr** [comment]
Out-of-proc is the default behaviour, this may change in the future.

**Comment by dallancarr** [comment]
Yes, it essentially checks whether the `aspnetcorev2_inprocess.dll` is loaded and then sets up the pipeline.

**Comment by dallancarr** [comment]
`UseIIS` is not optional in the case of using IIS Express for development.

**Comment by dallancarr** [comment]
Actually, if you are talking out of process vs in process then yes you are right. Sorry I misunderstood but the point it is expected that the switch is driven from web.config so my question is why would you want to bypass this functionality.

**Comment by RehanSaeed** [comment]
Isn't the switch based on the `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` setting in the csproj? I guess that probably just injects something into the web.config which is the real decision maker for which type of hosting to use.

**Comment by dallancarr** [comment]
Yeah the work is done inside the ANCM.

**Comment by RehanSaeed** [comment]
Thanks, I think I get it now.
