### ISSUE TITLE
Removing IIS Modules Results in 500.19 Internal Server Error

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/AspNetCore#6198]
### Describe the bug
Add the following `web.config` file in your project to use a minimum set of IIS modules as outlined by the [documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/modules?view=aspnetcore-2.2#minimum-module-configuration):

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <modules>
      <!-- Only load the minimum number of IIS modules. This requires you to unlock the modules section in IIS.
           See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/modules -->
      <clear/>
      <add name="AnonymousAuthenticationModule" />
      <add name="AspNetCoreModule" />
      <add name="HttpCacheModule"/>
      <add name="UriCacheModule"/>
    </modules>
  </system.webServer>
</configuration>
```

When you run the app using IIS Express, this causes a 500.19 Internal Server Error as show below:

![image](https://user-images.githubusercontent.com/2270364/50559276-22ac2400-0ced-11e9-8f0b-8d750e8499bd.png)

It seems that IIS Express does not like you to add anything into the `<modules>` section of the `web.config` file. I've tried `<clear/>`, `<add>` and `<remove>` which all produce this error. Everything works if I leave the `<modules>` section empty.

### Expected behavior
The app should start.

### Additional context
I'm using the ASP.NET Core 2.2.100 SDK and VS 2017 15.9.4.

**Comment by pakrym** [comment]
cc @shirhatti

**Comment by shirhatti** [comment]
This is because the modules section is locked at your `applicationHost.config` level be default.

Try changing `<section name="modules" allowDefinition="MachineToApplication" overrideModeDefault="Deny" />` to `<section name="modules" allowDefinition="MachineToApplication" overrideModeDefault="Allow" />`

**Comment by shirhatti** [comment]
When running `iisexpress.exe` from the command line, it uses the one in `%USERPROFILE%\Documents\IISExpress\config\applicationhost.config`

**Comment by muratg** [comment]
The recommendation is to carry your own applicationHost.config file for IIS Express. 

@guardrex Any updates we can make to the doc for this?

**Comment by guardrex** [comment]
Sure thing. I'll get it scheduled.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
