### ISSUE TITLE
LogLevel performance by default

### ISSUE THREAD

**Issue by patricka2** [aspnet/AspNetCore#6201]
Is not it better to set "LogLevel" default to "Error" instant "Warring" in appsettings.json in production mode by default? Does it have an effect on performance?

**Comment by rynowak** [comment]
We use warnings for things you would definitely not want to know about in production 😆. If you think something we log as a warning is too noisy then please let us know.

Logging is all pay-for-play. You'll only see a performance difference with `LogLevel.Warning` if there are warnings to log.
