### ISSUE TITLE
Figure out ProblemDetails + System.Text.Json

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#6202]
* [ ] - `ProblemDetails` relied on `JsonExtensionAttribute` to ensure that swagger document generators produced the correct JsonSchema. Since the attribute would no longer be available, we need  to figure out an alternate way to describe this to document generators.

**Comment by khellang** [comment]
> * Since the attribute would no longer be available, we need  to figure out an alternate way to describe this to document generators.

Why can't inheritance be used for this?

**Comment by pranavkm** [comment]
@khellang the tentative plan is to have an attribute that `System.Text.Json` understands and add support for it in swagger generators. Places like so:

* https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/bf455f474784316a2b33ee33eefd277d5729fc3a/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs#L204-L208
* https://github.com/RSuter/NJsonSchema/blob/7fd6a3fa8e5cb71d54148eb26cc3bd46d2397d12/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L367-L368
