### ISSUE TITLE
[Blazor] 32 bit enum flag values upon reflection

### ISSUE THREAD

**Issue by friendlyanon** [aspnet/AspNetCore#6205]
### Describe the bug
A flag enum inheriting from `long` can't have all its values reflected upon that are wider than 32 bits.  
Getting the value of the enum works as expected.

### To Reproduce
1. Create Standalone Blazor project `EnumTest`
2. Add file `Test.cs` with the contents of [this gist](https://gist.github.com/friendlyanon/7a174bb36a1cacfd2f56545192e40f2b/72ea2ca7d6488cf4e1fcc96046b6afcea10429c6)
3. In `Startup.cs` add `Test.PrintEnums();` to the `Configure` method

### Expected behavior
Prints
```
enum01
enum01
1 bit
enum02
enum02
2 bits
enum03
enum03
3 bits
...
enum62
enum62
62 bits
enum63
enum63
63 bits
enum64
enum64
64 bits
```

### Additional context
Blazor version: `0.7.0`
.NET Core: `2.1.502` - `c74ce8f29f`

**Comment by danroth27** [comment]
This issue was moved to mono/mono#13881
