### ISSUE TITLE
Kestrel API to retrieve raw http request bytes

### ISSUE THREAD

**Issue by mjsabby** [aspnet/AspNetCore#6210]
I'm trying to port an application that uses the HTTP.SYS APIs to retrieve the Raw Bytes of the HTTP request -- starting from the first request line till the \r\n\r\n.

The reason it is being done is that the WebListener classes when presenting the data through HttpRequest caused the data to be converted to a .NET String and for certain classes of request this caused problems in this application.

I'd like to be able to have an API that can retrieve the raw bytes of the HTTP request. This will allow me to have backwards compatibility.

Kestrel does have the ability to get to the connection data using Connection Abstractions, which is how Kestrel abstracts the HTTPS code from the core library. I'm wondering if there is a less intrusive way of doing this that I've missed through reading the code.

If not I suppose my needs can be met with whatever exists, but thought I'd ask and see if this has been considered before or if others have asked for such a feature,

**Comment by davidfowl** [comment]
It's not possible today without bigger changes or reaching down to the lower connection level and reusing some of the internal kestrel APIs. Kestrel eagerly parsers headers today when they are encountered and we don't keep those bytes around in any other form but the string. The [PlatformBenchmarks ](https://github.com/aspnet/AspNetCore/tree/master/src/Servers/Kestrel/perf/PlatformBenchmarks) project shows how to write a low level server with Kestrel APIs today.

>The reason it is being done is that the WebListener classes when presenting the data through HttpRequest caused the data to be converted to a .NET String and for certain classes of request this caused problems in this application.

Is it problematic that they will be converted anyways?

**Comment by mjsabby** [comment]
> Is it problematic that they will be converted anyways?

No, the majority of the codebase deals with the managed object and its representation, but certain parts rely on the bytes as-is.

I wonder if it's something people will want for this and/or other reasons. For example when a crash occurs today, we're able to find the raw bytes and replay them exactly as we encountered them and I've seen a few issues here that suggest enabling the Connection Logging to see what bytes really came over the wire.

If you think it may be reasonable to supply some code as part of Kestrel or some package then we can keep the issue open, otherwise I know what I'll have to do.

**Comment by muratg** [comment]
I don't expect we'll do this. @davidfowl please re-open if you disagree.

**Comment by davidfowl** [comment]
Not without major refactoring or something else (like copying the header bytes to keep them around)
