### ISSUE TITLE
OnSignedIn event regardless of the authentication used

### ISSUE THREAD

**Issue by CristianVladescu** [aspnet/AspNetCore#6213]
Is there a way to register a delegate to be called on successful login regardless of the authentication method used (Identity, AzureAD, etc), and not on every request, similar to [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationevents.onsignedin?view=aspnetcore-2.1) one?

Right now I'm using ClaimsTransformationMiddleware, but it's called on every request.

```
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddSingleton<IClaimsTransformation, EveryoneGroupTransformer>();
    ...
}
...

public class EveryoneGroupTransformer : IClaimsTransformation
{
    public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
    {
        Console.WriteLine(principal.Identity.Name);
        return Task.FromResult(principal);
    }
}
```

**Comment by blowdart** [comment]
No, there's no way to have "global" events.
