### ISSUE TITLE
Removing Microsoft.AspNetCore.Mvc.Razor.RazorViewEngineOptions --> AdditionalCompilationReferences will block us

### ISSUE THREAD

**Issue by thiennn** [aspnet/AspNetCore#6215]
Related to #4902

In https://github.com/simplcommerce/SimplCommerce, we apply modular architecture, each module is a Razor Class Library. We manually load modules and then add them to the main web app using ApplicationPart. We also support theming, users can switch between the themes at run time. This feature requires run time compilation of cshtml files.

Currently it works fine. But if you remove the api for adding AdditionalCompilationReferences on RazorViewEngineOptions it will not work.

I have create a simple project to show this issue here https://github.com/thiennn/plugin2_2.

**Comment by pranavkm** [comment]
@thiennn MVC uses deps files to determine the location of compilation references. The plugin assembly that you load has a deps file but with `PreserveCompilationContext` disabled. Consequently it results in MVC determining that there are no references to be loaded from it. A couple of ways for you to fix it:

1) Use a regular P2P reference between your app and the plugin. It'll ensure that your app has the correct closure of references when attempting to runtime compile views. This would be my recommended solution.
2) Alternatively, ensure a deps file does not exist next to the plugin assembly. Targeting `netstandard2.0`, using `<GenerateDependencyFile>false</GenerateDependencyFile>`, or just deleting it as a post build step are all possible ways to go about this.

**Comment by thiennn** [comment]
Thank @pranavkm Option 1 will prevent the ability to add plugins at run-time. Deleting the deps file seems the suitable workaround for us at this moment.

**Comment by pranavkm** [comment]
Closing since the question has been answered.

**Comment by MathiasKowoll** [comment]
@pranavkm thanks for the solution and code, worked perfectly.
@thiennn I just created the following gulp task to remove *deps.json
gulp.task('clean-deps', function () {
    return gulp.src([paths.host.modules + '*'+ paths.host.moduleBin+ '*.deps.json'], { read: false })
        .pipe(clean());

**Comment by MathiasKowoll** [comment]
@pranavkm thanks for the solution and code, worked perfectly.
@thiennn I just created the following gulp task to remove *deps.json
gulp.task('clean-deps', function () {
    return gulp.src([paths.host.modules + '*'+ paths.host.moduleBin+ '*.deps.json'], { read: false })
        .pipe(clean());
