### ISSUE TITLE
The "RepoTasks.JoinItems" task could not be loaded from the assembly...

### ISSUE THREAD

**Issue by TanvirArjel** [aspnet/AspNetCore#6219]
I have downloaded this ASP.NET Core master respiratory into my computer and I have opened MVC solution with Visual Studio 2019. When I try to build the solution, getting the following error from all class libraries:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4062	The "RepoTasks.JoinItems" task could not be loaded from the assembly D:\AspNetCore-master\AspNetCore-master\build\tasks\bin\publish\RepoTasks.dll.
 Could not load file or assembly 'file:///D:\AspNetCore-master\AspNetCore-master\build\tasks\bin\publish\RepoTasks.dll' or one of its dependencies.
 The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available,
 and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	Microsoft.Net.Http.Headers	
C:\Program Files\dotnet\sdk\3.0.100-preview-009812\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	442
	
```

Then I have checked the following directory:

`D:\AspNetCore-master\AspNetCore-master\build\tasks\bin\publish\RepoTasks.dll.`

But no such directory exists the project folder structure.

How can I overcome this error please!

**Comment by natemcmaster** [comment]
Run restore.cmd first. I've updated our docs and made a tweak to our targets to avoid this errors in VS.

**Comment by TanvirArjel** [comment]
@natemcmaster Please tell me more details! I did not understand what you actually mean run `restore.cmd` first? And which doc you have updated or how can I get this updated doc? Thank you.

**Comment by TanvirArjel** [comment]
@natemcmaster I had run `restore.cmd` as administrator but did not help. dotnet-sdk Installation failed. Any more suggestion please!

**Comment by natemcmaster** [comment]
Try pulling the latest code from master. There were two bugs with JoinItems. The first was fixed in #6295 and the other in #6302

**Comment by TanvirArjel** [comment]
@natemcmaster NOw I am getting the following error from all Test MVC website projects in the solution.

```
Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	NETSDK1007	Cannot find project info for 'D:\AspNetCore-master\src\Antiforgery\src\Microsoft.AspNetCore.Antiforgery.csproj'. This can indicate a missing project reference.	SimpleWebSite	C:\Program Files\dotnet\sdk\3.0.100-preview-009812\Sdks\Microsoft.NET.Sdk\targets	C:\Program Files\dotnet\sdk\3.0.100-preview-009812\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	125
```

Would you help me please about whats going here?

**Comment by TanvirArjel** [comment]
@natemcmaster Any help or suggestion or thought on the above error message please? Why I am receiving this?

**Comment by natemcmaster** [comment]
No clue. Make sure you have pulled the latest source code, including https://github.com/aspnet/AspNetCore/pull/6211. If you still have problems, please open a new issue so we can assign the MVC team to investigate.
