### ISSUE TITLE
Blazor - Casting UIEventArgs

### ISSUE THREAD

**Issue by Duxez** [aspnet/AspNetCore#6221]
I'm currently trying out Blazor to see what's possible with it and stuff.
Now trying to catch events for example onscroll events since I want to get the scroll position.

Example:
```
@functions {
    void SetItemClasses(UIWheelEventArgs eventArgs)
    {
        System.Console.WriteLine(eventArgs.Type);
    }
}

<div id="divbody" onscroll="@(e => SetItemClasses((UIWheelEventArgs)e))">
</div>
```
With the div having a width and height so the onscroll event gets fired.

Doing it this way always throws me
`Error: System.InvalidCastException: Specified cast is not valid.`

And I can't seem to find another way to get the event args I want.

**Comment by arivera12** [comment]
I was gonna open an issue regarding on this. The `UIEventArgs` doesn't provide anything about the position of the screen or client. In my case I am trying to check whether or not I have scrolled to the end of a list. I have done this via javascript the others days but if onscroll event received the `UIMouseEventArgs` instead of `UIEventArgs` maybe we could just do something like this:
```
if(eventArgs.ClientY >= eventArgs.ScreenY)
{
    Console.WriteLine("Bottom reached!");
}
```

**Comment by arivera12** [comment]
I think onscroll isn't even working at all. I placed an scroll event on top of one page and started scrolling on it a never gets fired.

**Comment by arivera12** [comment]
I found one quick and dirty way to check whether to know if you are at the end of the page. I used onmousewheel event cause onscroll isn't working for me atm. This is my working solution.

```
var scrollTop = await JSRuntime.Current.InvokeAsync<int>(
           "eval", "document.documentElement.scrollTop");

var windowsInnerHeight = await JSRuntime.Current.InvokeAsync<int>(
            "eval", "window.innerHeight");

var offsetHeight = await JSRuntime.Current.InvokeAsync<int>(
            "eval", "document.documentElement.offsetHeight");

if ((scrollTop + windowsInnerHeight) >= offsetHeight)
            Console.WriteLine("Bottom reached!");
```

**Comment by Duxez** [comment]
onscroll definitely works, or at least it does for me. But yea I did it with JSInterop for now as well

**Comment by arivera12** [comment]
@Duxez can you show me a sample to see how your scroll event is working? The blazor default template onscroll event doesn't work for me when placing the oncroll event on a div. The problem I am facing with the onscroll event is that body is scrolling intead of any div I specify to use the onscroll event. You should had modified the css properly for this to make it work on any div.

**Comment by Duxez** [comment]
Yeah I just made a div wrap around the content with a height of 100vh and a width of 100vw disabling the overflow on the body so that that div's scrollbar would be used instead.

**Comment by Duxez** [comment]
Yeah it was definitely a hassle to set it all up, but at least it works

**Comment by arivera12** [comment]
@Duxez can you share your code for future reference?

**Comment by Duxez** [comment]
Sure thing
have a div that wraps the pages content, with an id or class and put the onscroll event here. The function for the onscroll event should just be a js function, no need for JSInterop here. (I called it scrolling)
For css (I used divbody as the id for my wrapper div):
```
body
{
    overflow: hidden;
}
#divbody
{
    overflow: auto;
    height: 100vh;
}
```

Create the js function in script tags in index.html or in a seperate js file and link that in the index.html file.

The function will get called when you start scrolling. You don't need event args although you can pass the some to get the sender if you want. Since I have only 1 scroll bar I have only 1 sender so I just got it by it's id.

**Comment by mkArtakMSFT** [comment]
We believe this issue has been addressed already. If there is something pending here, please file a new issue.
