### ISSUE TITLE
CSHTML file is not updating the same time when I editing them in vs code.

### ISSUE THREAD

**Issue by anirugu** [aspnet/AspNetCore#6294]
I create a dotnet core 3 project and it's not updating the .cshtml pages as I make changes. this work fine in MVC5. 

Adding more detail for clearify the issue

Create a project from command promt and start modifying the .cshtml project. Add 2 li on top and nothing happen, Only seening changes when I restart the debug session in VS code.

**Comment by pranavkm** [comment]
Is this with a 3.0.0-preview project? We recently removed support for runtime compilation in 3.0.0 and there's a work item to re-add support for it (#4947).

**Comment by anirugu** [comment]
@pranavkm  Thanks for reply is `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation`  is available somewhere, I search in nuget with pre-release. it's not there.

**Comment by pranavkm** [comment]
The feature hasn't been implemented as yet. In the meanwhile, you might have success using `dotnet-watch` to do this. @natemcmaster are there any guides for configuring VS Code to work with the watch command?

**Comment by natemcmaster** [comment]
Yes, you can configure with file changes cause dotnet-watch to restart the web server. See https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-2.2#customize-files-list-to-watch

**Comment by pranavkm** [comment]
Closing this since the question was answered. https://github.com/aspnet/AspNetCore/issues/4947 tracks adding support for the feature.
