### ISSUE TITLE
.NET Core 3 Preview Blazor basic project does not compile

### ISSUE THREAD

**Issue by redradist** [aspnet/AspNetCore#6300]
Hi all,

Recently, I have downloaded .NET Core 3 Preview and tried to create the basic Blazor (standalone) project.
When I first time tried to compile it I got the error:

`RazorCompilation.targets(184, 5): [null] rzc generate exited with code 150`

Guys, any suggestion how to solve this issue ?

**Comment by redradist** [comment]
Seems like this is an issue only on Linux platform. I have currently created a Test Blazor Application on Windows and it is working ...

Maybe it will give some hints

**Comment by vova-lantsov-dev** [comment]
I have also this issue on Linux. I can provide more info but don't know which.

**Comment by vova-lantsov-dev** [comment]
```Blazor.MonoRuntime.targets(439, 5): [MSB3073] The command "dotnet "/home/kiss/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "/home/kiss/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/" -d "/home/kiss/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/Facades/" -o "/home/kiss/projects/BookkeepingNasheDetstvo/BookkeepingNasheDetstvo.Client/obj/Debug/netstandard2.0/blazor/linker/" -x "/home/kiss/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/BuiltInBclLinkerDescriptor.xml" -x "/home/kiss/projects/BookkeepingNasheDetstvo/BookkeepingNasheDetstvo.Client/obj/Debug/netstandard2.0/blazor/linker.descriptor.xml" -a "/home/kiss/.nuget/packages/microsoft.aspnetcore.blazor/0.9.0-preview3-19154-02/lib/netstandard2.0/Microsoft.AspNetCore.Blazor.dll" -a "/home/kiss/.nuget/packages/microsoft.aspnetcore.components/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.dll" -a "/home/kiss/.nuget/packages/microsoft.aspnetcore.components.browser/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.Browser.dll" -a "/home/kiss/.nuget/packages/microsoft.extensions.dependencyinjection/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll" -a "/home/kiss/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "/home/kiss/.nuget/packages/microsoft.jsinterop/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.JSInterop.dll" -a "/home/kiss/.nuget/packages/mongodb.bson/2.8.0/lib/netstandard1.5/MongoDB.Bson.dll" -a "/home/kiss/.nuget/packages/mono.webassembly.interop/3.0.0-preview3.19153.1/lib/netstandard2.0/Mono.WebAssembly.Interop.dll" -a "/home/kiss/.nuget/packages/system.collections.nongeneric/4.0.1/lib/netstandard1.3/System.Collections.NonGeneric.dll" -a "/home/kiss/.nuget/packages/system.componentmodel.annotations/4.6.0-preview3.19128.7/lib/netstandard2.0/System.ComponentModel.Annotations.dll" -a "/home/kiss/.nuget/packages/system.dynamic.runtime/4.0.11/lib/netstandard1.3/System.Dynamic.Runtime.dll" -a "/home/kiss/.nuget/packages/system.io.filesystem.primitives/4.0.1/lib/netstandard1.3/System.IO.FileSystem.Primitives.dll" -a "/home/kiss/.nuget/packages/system.linq/4.1.0/lib/netstandard1.6/System.Linq.dll" -a "/home/kiss/.nuget/packages/system.linq.expressions/4.1.0/lib/netstandard1.6/System.Linq.Expressions.dll" -a "/home/kiss/.nuget/packages/system.objectmodel/4.0.12/lib/netstandard1.3/System.ObjectModel.dll" -a "/home/kiss/.nuget/packages/system.reflection.emit/4.0.1/lib/netstandard1.3/System.Reflection.Emit.dll" -a "/home/kiss/.nuget/packages/system.reflection.emit.ilgeneration/4.3.0/lib/netstandard1.3/System.Reflection.Emit.ILGeneration.dll" -a "/home/kiss/.nuget/packages/system.reflection.emit.lightweight/4.3.0/lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll" -a "/home/kiss/.nuget/packages/system.reflection.typeextensions/4.1.0/lib/netstandard1.5/System.Reflection.TypeExtensions.dll" -a "/home/kiss/.nuget/packages/system.threading/4.0.11/lib/netstandard1.3/System.Threading.dll" -a "/home/kiss/.nuget/packages/system.threading.thread/4.0.0/lib/netstandard1.3/System.Threading.Thread.dll" -a "/home/kiss/.nuget/packages/system.threading.threadpool/4.0.10/lib/netstandard1.3/System.Threading.ThreadPool.dll" -a "/home/kiss/.nuget/packages/microsoft.win32.registry/4.0.0/runtimes/unix/lib/netstandard1.3/Microsoft.Win32.Registry.dll" -a "/home/kiss/.nuget/packages/microsoft.win32.registry/4.0.0/runtimes/win/lib/netstandard1.3/Microsoft.Win32.Registry.dll" -a "/home/kiss/.nuget/packages/system.diagnostics.process/4.1.0/runtimes/linux/lib/netstandard1.4/System.Diagnostics.Process.dll" -a "/home/kiss/.nuget/packages/system.diagnostics.process/4.1.0/runtimes/osx/lib/netstandard1.4/System.Diagnostics.Process.dll" -a "/home/kiss/.nuget/packages/system.diagnostics.process/4.1.0/runtimes/win/lib/netstandard1.4/System.Diagnostics.Process.dll" -a "/home/kiss/projects/BookkeepingNasheDetstvo/BookkeepingNasheDetstvo.Shared/bin/Debug/netstandard2.0/BookkeepingNasheDetstvo.Shared.dll" -a "/home/kiss/projects/BookkeepingNasheDetstvo/BookkeepingNasheDetstvo.Client/obj/Debug/netstandard2.0/BookkeepingNasheDetstvo.Client.dll"" exited with code 150.```

**Comment by vova-lantsov-dev** [comment]
Error occures while building the application.
**Blazor.MonoRuntime.targets** _(line 439)_
```
<!-- Run the linker and put the results in /obj/<<configuration>>/<<targetframework>>/blazor/blazor/linker -->
<Exec Command="dotnet &quot;$(MonoLinkerPath)&quot; $(_BlazorLinkerAdditionalOptions) @(_BlazorFolderLookupPaths, ' ') -o &quot;$(BlazorIntermediateLinkerOutputPath)&quot; @(_BlazorAssemblyDescriptorFiles, ' ') @(_BlazorAssembliesToLink, ' ')"  />
```

**Comment by staff0rd** [comment]
Here's a repro of this issue, inside a docker container, [following these steps](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli).

**REPRO**
```
docker run -it mcr.microsoft.com/dotnet/core/sdk:3.0 bash
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.9.0-preview3-19154-02
dotnet new blazor -o WebApplication1
cd WebApplication1
dotnet run
```

**EXPECTED**: Runs without exception
**ACTUAL**: Following exception is thrown

> /root/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/Blazor.MonoRuntime.targets(439,5): error MSB3073: The command "dotnet "/root/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "/root/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/" -d "/root/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/Facades/" -o "/src/WebApplication1/obj/Debug/netstandard2.0/blazor/linker/" -x "/root/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/BuiltInBclLinkerDescriptor.xml" -x "/src/WebApplication1/obj/Debug/netstandard2.0/blazor/linker.descriptor.xml" -a "/root/.nuget/packages/microsoft.aspnetcore.blazor/0.9.0-preview3-19154-02/lib/netstandard2.0/Microsoft.AspNetCore.Blazor.dll" -a "/root/.nuget/packages/microsoft.aspnetcore.components/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.dll" -a "/root/.nuget/packages/microsoft.aspnetcore.components.browser/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.Browser.dll" -a "/root/.nuget/packages/microsoft.extensions.dependencyinjection/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll" -a "/root/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "/root/.nuget/packages/microsoft.jsinterop/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.JSInterop.dll" -a "/root/.nuget/packages/mono.webassembly.interop/3.0.0-preview3.19153.1/lib/netstandard2.0/Mono.WebAssembly.Interop.dll" -a "/root/.nuget/packages/system.componentmodel.annotations/4.6.0-preview3.19128.7/lib/netstandard2.0/System.ComponentModel.Annotations.dll" -a "/src/WebApplication1/obj/Debug/netstandard2.0/WebApplication1.dll"" exited with code 150. [/src/WebApplication1/WebApplication1.csproj]

**Comment by mkArtakMSFT** [comment]
We've had several issues in the past requiring multiple SDKs and we've resolved a bunch of these for the upcoming release. Closing this issue. If you happen to face similar issues with the upcoming release, please file new issues.
