### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by sierks** [aspnet/AspNetCore#6319]
I am getting a CORS-related error when starting my signalr connection, even though I think I have everything setup correctly. (Though I probably do not.) Any ideas?

Access to XMLHttpRequest at 'https://sparqsignalr.azurewebsites.net/SparqHub/negotiate' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

My client is referencing this JS file:
https://unpkg.com/@aspnet/signalr@1.1.0/dist/browser/signalr.min.js

And my Azure SignalR Server has CORS enabled, and is referencing .NET Framework 4.7.2 (due to other DLLs), AspNetCore 2.2.0, and AspNetCore.SignalR.Common 1.1.0:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options => options.AddPolicy("CorsPolicy", builder =>
            {
                builder
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .WithOrigins("http://localhost")
                    .AllowCredentials()
                    ;
            }));

            services.AddSignalR(configure => configure.EnableDetailedErrors = true)
                    .AddAzureSignalR();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseCors("CorsPolicy");

            app.UseAzureSignalR(routes =>
            {
                routes.MapHub<Hubs.SparqHub>("/SparqHub");
            });
        }

```

If I change the WithOrigins call, I can get the first OPTIONS message to fail. So I think it's setup correctly as it is now. The Hub is (now) completely empty, so I don't think that's the problem. I also don't think it's ever making it to the Azure SignalR, because if I change the connection string to something incorrect it still gives me this same CORS 500 error. 

Here are the console messages from Chrome:
![image](https://user-images.githubusercontent.com/19377079/50617623-c810f480-0eb3-11e9-98b5-31dc88792ebb.png)

And the 2 negotiate requests:
![image](https://user-images.githubusercontent.com/19377079/50617649-e7a81d00-0eb3-11e9-9b4c-eeb888f10980.png)

Here's the OPTIONS message:
![image](https://user-images.githubusercontent.com/19377079/50618355-ccd7a780-0eb7-11e9-8d3e-5ed45e59438f.png)

Here's the failed one:
![image](https://user-images.githubusercontent.com/19377079/50618365-dc56f080-0eb7-11e9-9273-a9314c83f118.png)

And there's nothing in the Azure CORS section:
![image](https://user-images.githubusercontent.com/19377079/50618031-d9f39700-0eb5-11e9-8a46-e249cd718499.png)

And here's some more information:

2019-01-02 22:07:19 SPARQSIGNALR OPTIONS /SparqHub/negotiate X-ARR-LOG-ID=fc21f64a-25ad-4131-a949-f65a3a26c2f8 443 - 72.46.60.2 Mozilla/5.0+(Windows+NT+6.3;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/71.0.3578.98+Safari/537.36 - http://localhost/Everest/Home/Main sparqsignalr.azurewebsites.net 204 0 0 399 1205 31

2019-01-02 22:07:19 SPARQSIGNALR POST /SparqHub/negotiate X-ARR-LOG-ID=0832af8d-f9fa-4549-82e8-46b2c7878870 443 - 72.46.60.2 Mozilla/5.0+(Windows+NT+6.3;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/71.0.3578.98+Safari/537.36 - http://localhost/Everest/Home/Main sparqsignalr.azurewebsites.net 500 0 0 294 1208 31

[IIS Detailed Error - 500.0 - Internal Server Error.html.txt](https://github.com/aspnet/AspNetCore/files/2722355/IIS.Detailed.Error.-.500.0.-.Internal.Server.Error.html.txt)

[https___sparqsignalr_80_SparqHub_negotiate, STATUS_CODE 500, 0 ms, POST.xml.txt](https://github.com/aspnet/AspNetCore/files/2722356/https___sparqsignalr_80_SparqHub_negotiate.STATUS_CODE.500.0.ms.POST.xml.txt)

It also fails on my test site out in Azure, even though I thought it would bypass CORS out there:
![image](https://user-images.githubusercontent.com/19377079/50618489-a23a1e80-0eb8-11e9-8138-ced263bbffbb.png)

**Comment by pranavkm** [comment]
@sierks might be this - https://stackoverflow.com/a/28548756. There are some suggested workarounds in the reply.

**Comment by sierks** [comment]
Well, it seems the problem was Azure SignalR. Removing that fixed it. So apparently I just don't know how to set that up.

Feel free to delete this issue.

**Comment by pranavkm** [comment]
> Well, it seems the problem was Azure SignalR. Removing that fixed it.

FYI @davidfowl
