### ISSUE TITLE
Windows Authentications for Kestrel when hosted in Windows Service or console app

### ISSUE THREAD

**Issue by sandrakim90** [aspnet/AspNetCore#6323]
On Windows, there appears to be no way to get Windows Authentication when hosting Kestrel in a Windows Service or console application. Is this feature under consideration for .NET Core 3 or maybe via Windows compatibility pack?

Windows Service is a more appropriate host than IIS for some applications. For example, I have an application that does stuff like gathering data on dedicated threads via BackgroundService and makes that data available via Web API in Kestrel. Windows Service is a good host because it auto-starts and does not go idle unlike IIS. But Web API needs to have Windows Authentication on it which seems to be only available through IIS or HTTP.sys.

In order to use the best components for my solution, I should be able to combine Windows Service hosting, Kestrel, .NET Core and Windows Authentication to build the application for my needs.

**Comment by Eilon** [comment]
cc @blowdart

**Comment by blowdart** [comment]
What's wrong with hosting via http.sys in a service? Or a console app? 

cc @Tratcher

**Comment by sandrakim90** [comment]
Fear of the unknown I guess. Have been using Kestrel on other projects with success so don't want to introduce an unknown element. Just as an example, after your post, I spent 5 hours trying to replace Kestrel with HTTP.sys because kept getting access denied error despite having read the entire discussion on it. Kestrel and HTTP.sys treat permission for wildcard URLs differently. Learning and dealing with different behavior consumes time and money. I am sure I will run into other differences too.

As far as I can see, the only reason there is a need for HTTP.sys is because the optional modules like Windows Authentication, security, etc. have not been added to Kestrel. When I started working with .NET Core two years ago, I was confused by the need for two application servers. Time would have been better spent reading documentation on how to configure optional features for one application server than reading documentation that talks about differences between application servers. What do you think?

**Comment by Tratcher** [comment]
@sandrakim90 Http.Sys has several features that would be either very expensive or impractical to replicate for Kestrel. Windows auth is expensive and dangerous to re-implement. It may happen eventually but for now you're better off using Http.Sys. The other common feature is port sharing which is impractical to replicate with kestrel's current architecture.

**Comment by sandrakim90** [comment]
Thank you for clarification. Feel free to close incident.
