### ISSUE TITLE
Update xUnit extensibility for 2.4

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6327]
See: https://github.com/aspnet/AspNetCore-Tooling/pull/87 for an example

When we upgrade to xUnit 2.4 (default for dotnet/Arcade) we will need to make some changes to our xUnit discoverers. If we don't do this, then all of our extensibility will start to silently not run tests 😢

**Comment by natemcmaster** [comment]
@rynowak these are the versions of xUnit we are currently using. Are we missing tests as a result of this combination of versions?

https://github.com/aspnet/AspNetCore/blob/a1d49e19b52d457f2bf582339cc68f4975b1ebbf/eng/Versions.props#L174-L180

**Comment by natemcmaster** [comment]
Triage team: let's investigate this first to see if we are impacted by this breaking change in xunit. Try downgrading back to 2.3 to see if we suddenly get more tests running. If we are impacted by this bug, we need to figure out what to do next.

**Comment by ryanbrandenburg** [comment]
Actually, 2.4.1 discovered slightly more tests than 2.3.0 or 2.4.0, so it seems like for AspNetCore if anything we should upgrade earlier.

**Comment by natemcmaster** [comment]
+1 for updating to 2.4.1

**Comment by ryanbrandenburg** [comment]
This is [already done](https://github.com/aspnet/AspNetCore/blob/master/eng/Versions.props#L199).
