### ISSUE TITLE
CORS not working with OPTIONS

### ISSUE THREAD

**Issue by schneiderpat** [aspnet/AspNetCore#6328]
Hi,
[old issue](https://github.com/aspnet/AspNetCore/issues/3121)

I configured cors like that in my startup

app.UseCors(builder =>
    builder.WithOriging("http://localhost:4200")
          .AllowAnyMethod()
          .AllowAnyHeader()
          .AllowCredentials()
);
When my frontend, an angular spa, sends a put request, chrome sends a preflight with an options method. this one does not get handled by the cors middleware.
in the end my controller gets the request and returns unauthorized.

I did the suggestions from [here](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio#update-cors-policy)
But still no progress.

**Comment by schneiderpat** [comment]
I found the issue myself.
I have to allow anonymous requests.
`options.Authentication.AllowAnonymous = true;`

**Comment by viananicolas** [comment]
@schneiderpat , where do you put this line of code?

**Comment by schneiderpat** [comment]
@viananicolas I passed this with the options to in my `CreateWebHostBuilder` method in *Program.cs*
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
      WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseHttpSys(options =>
        {
          options.Authentication.Schemes = AuthenticationSchemes.NTLM;
          options.Authentication.AllowAnonymous = true;
         ...
        });
```

**Comment by viananicolas** [comment]
Worked flawlessly. Thank you!
