### ISSUE TITLE
Making IQueryableUserStore Async

### ISSUE THREAD

**Issue by guylando** [aspnet/AspNetCore#6331]
Could not find such issue in this repository or the old identity repository.
Currently the IQueryableUserStore interface of dotnet identity has a sync property IQueryable<TUser> Users.
This property usually has an async implementation, see: https://stackoverflow.com/questions/30640281/getter-property-with-async-method-doesnt-finish-executing
Maybe you can consider adding async method to the interface or some other solution which will prevent needing to do .Wait() to prevent deadlocks? Such as what have been suggested here: https://stackoverflow.com/questions/30640281/getter-property-with-async-method-doesnt-finish-executing/30643761#30643761
Or maybe I am unaware of some existing solution to this.

**Comment by blowdart** [comment]
Ah history, this was designed long before async was a thing. We don't have the bandwidth for it for 3.0 (interface changes are breaking changes, so it needs to be a major version change), but we would accept a well designed PR.

**Comment by reaction1989** [comment]
@blowdart How do you want the Interface to change?

```c#
Task<IQueryable<TUser>> Users { get; }
```
or
```c#
Task<IQueryable<TUser>> UsersAsync { get; }
```

**Comment by HaoK** [comment]
Per @blowdart 

> Closing as EF already allows async. If another store not based on EF comes through we may reconsider.
