### ISSUE TITLE
How to get users from SQL server database and also how to track changes inside the database by asp.net core signalR?

### ISSUE THREAD

**Issue by farhadibehnam** [aspnet/AspNetCore#6334]
Like telegram and WhatsApp I want to fetch users from a database into a chat app for example when you open up telegram, you can see your contacts in the telegram if your contacts are online telegram show he/she is online if that person leaves chat telegram show he/she is offline. But there is a point about it maybe suddenly one user inserts into database how to can I real-time track database immediately user added into a database I bring it to chat app.in front-end I'm using jquery and ajax.

```
  [Authorize]
    public class ChatHub : Hub
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly ApplicationDbContext _dbContext;
        public ChatHub(UserManager<AppUser> userManager,ApplicationDbContext dbContext)
        {
            _userManager = userManager;
            _dbContext = dbContext;
        }
        public async Task GetAllUsers()
        {
           var users = await _dbContext.Users.ToListAsync();
           
        }
        public async Task SendMessage(string name, string text)
        {
            var personPricture = "https://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg";
            var message = new ChatMessage
            {
                SenderName = name,
                Text = text,
                SendAt = DateTimeOffset.Now
            };
            await Clients.All.SendAsync("ReciveMessage",
            message.SenderName,
            message.SendAt, message.Text, personPricture);

        }

        public async Task SendPrivateMessage(string connectionId, string message)
        {
            await Clients.Client(connectionId).SendAsync("ReceiveMethod", message);
        }

        private readonly HashSet<string> onlineUsers = new HashSet<string>();
        public override async Task OnConnectedAsync()
        {
            if (Context.User.Identity.IsAuthenticated)
            {
                var name = Context.User.Identity.Name;
            }

            onlineUsers.Add(Context.ConnectionId);
            await Clients.Caller.SendAsync("UserConnected", Context.ConnectionId);
            await base.OnConnectedAsync();
        }

        public override async Task OnDisconnectedAsync(Exception ex)
        {
            onlineUsers.Remove(Context.ConnectionId);
            await Clients.All.SendAsync("UserDisconnected", Context.ConnectionId);
            await base.OnDisconnectedAsync(ex);
        }
    }
}
```

```
        [HttpGet,Route("GetAllUsers")]
        public async Task<IActionResult> GetAllUsers()
        {
            List<UsersViewModel> usersList = new List<UsersViewModel>();
            var users = await _dbContext.Users.ToListAsync();
            foreach (var user in users)
            {
                usersList.Add(new UsersViewModel
                {
                    UserId = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    PersonPicture = user.PictureUrl

                });
            }
            return Ok(new { users = usersList });
        }
```

```
<script>
        $(document).ready(function () {
            $('#login').click(function () {
                let UserName = $('#username').val();
                let Password = $('#password').val();
                let user = { UserName: UserName, Password: Password };
                console.log($('#password').val());
                $.ajax({
                    url: '/api/auth/Login',
                    type: 'post',
                    contentType: 'application/json',
                    data: JSON.stringify(user),
                    success: function (data) {
                        let token = data.token;
                        console.log(token);
                        url = "/?jwt=" + token;
                        window.location.href = url;
                    },
                    error: function (data) {
                        console.log(data);
                    }
                })

            });
        });

    </script>
```
     <script>
            $(document).ready(function () {
                let users = { Id, FirstName, LastName, FullName, PersonPicture };
                

                $.ajax({
                    type: "get",
                    url: "/api/auth/GetAllUsers",
                    contentType: "application/json",
                    dataType: "json",
                    data: JSON.stringify(users),
                    success: function (data) {
                        $.each(data,
                            function (index, item) {
                                let liElement = $("li");
                                let dFelx_bd_highlight = $('<div class="img_cont"></div>');
                                let divElement_user_info = $('<div class="user_info"></div>');
                                let spanElement_FullName = $('<span></span>');
                                let pElement_Status = $('<p></p>');
                                let divElement_img_cont = $('<div class="img_cont"></div')
                                let imgSrc = $('<img src="rounded-circle user_img">');
                                let spanElement_online_icon = $('<span class="offline_icon">');
                                divElement_img_cont.append(imgSrc, spanElement_online_icon);
                                dFelx_bd_highlight.append(divElement_img_cont);
                                divElement_user_info.append(spanElement_FullName, pElement_Status);
                                liElement.append(dFelx_bd_highlight, divElement_user_info);
                                spanElement_FullName.text(item.FullName);
                                imgSrc.attr('src', item.PersonPicture);
                                pElement_Status.text(item.FirstName + ' ' + "is offline");
                                $("ul .contacts").append(liElement);
                            });

                    },
                    error: function (data) {

                    }

                });
            });
        </script>

**Comment by BrennanConroy** [comment]
Why not use the "UserConnected" and "UserDisconnected" client methods to add and remove users from an online list? Or if you really want to make use of your controller method `GetAllUsers`, then call it from the client every time you trigger "UserConnected" and "UserDisconnected".

**Comment by farhadibehnam** [comment]
I think I found a wrong solution for that.as you see these code I added a function that name is removeElements everytime user want to be online I remove previous users of HTML and make it again.but previous
 
the problem remains I mean fetching from a database with every user want to be online.

```
function createContacts(users) {
    removeElements();
  $.each(JSON.parse(users),
        function (index, user) {
       
            console.log(user.FullName);
            let dFelx_bd_highlight = $('<div class="d-flex bd-highlight"></div>');
            let divElement_user_info = $('<div class="user_info"></div>');
            let spanElement_FullName = $('<span></span>');
            let pElement_Status = $('<p></p>');
            let divElement_img_cont = $('<div class="img_cont"></div')
            let imgSrc = $('<img class="rounded-circle user_img">');
            let spanElement_online_icon = $('<span class="online_icon offline">');
            imgSrc.attr('src', user.PersonPicture);
            
            divElement_img_cont.append(imgSrc, spanElement_online_icon);
            spanElement_FullName.text(user.FullName);
            let liElement = $("<li></li>");
            liElement.append(dFelx_bd_highlight, divElement_user_info);

            dFelx_bd_highlight.append(divElement_img_cont, divElement_user_info);
            divElement_user_info.append(spanElement_FullName, pElement_Status);

            pElement_Status.text(user.FirstName + ' ' + "is offline");
            $("ul.contacts").append(liElement);
      

        });


}
```

```

function removeElements() {
    $("ul.contacts > li ").remove();
} 
```

**Comment by BrennanConroy** [comment]
Is there still an issue? Looks like you're close to a solution you want.

**Comment by farhadibehnam** [comment]
I mean was two previous comments from this question, not the previously closed question.
