### ISSUE TITLE
IAsyncActionFilter Re-execute action

### ISSUE THREAD

**Issue by oferns** [aspnet/AspNetCore#6335]
I have implemented IAsyncActionFilter as below to try to re-execute the action method after a database error (on insert/update). The idea being that some DB exceptions are actually validation errors. In this case, I am using sql constraints to prevent overlapping dates. The easiest way to check validity is to try to update/insert then catch the error, and return the view with the original data + validation messages. I realise I could do this in the controller code with a try-catch... My controller action has the following code immediately after the signature.

```
           if (!ModelState.IsValid) {
                return View("New", model);
            }
```
 
What I would like to do is add errors to the ModelState and re-execute the action. That is what the implementation below is supposed to do.

```
public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) {

            ActionExecutedContext result = await next();

            if (result.Exception is DbException && result.ModelState.IsValid) {
                result.ExceptionHandled = true;
                context.ModelState.AddModelError("", result.Exception.Message);
                //  result.Result = null;
                //  result.Exception = default(Exception);
                ActionExecutedContext newresult = await next();
                // context.Result = newresult.Result;

            }
        }
```

The controller code is re-executed but I am clearly missing something as the eventual output a 200 code with no body. What am I missing?

TIA

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @oferns.
This is not a supported scenario.
You can achieve this with a custom middleware, which can retry the request as necessary.
