### ISSUE TITLE
Moving Razor Pages Areas Folder

### ISSUE THREAD

**Issue by netleader** [aspnet/AspNetCore#6337]
### Describe the bug
I can't find a way to move the default Areas folder to a subfolder.
This is my project structure:

Project.Web
+-- ClientApp (VUE SPA)
+-- Server (includes all asp.net components)

I moved my pages already to the Server folder but I can't manage to get the Areas folder within the Server folder working.

### To Reproduce
1. Using this version of ASP.NET Core 2.2

### Expected behavior
Having a RazorPagesOptions like options.AreasRootDirectory

**Comment by pranavkm** [comment]
@netleader there isn't an feature to do this as yet. We had some trouble reconciling configurable Areas with Razor Class Libraries like IdentityUI. https://github.com/aspnet/Mvc/issues/7608 goes in to a bit more detail about this. You could explore using [route model conventions](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-2.2) to configure the pages in your application to account for your modified folder structure.

**Comment by netleader** [comment]
Thanks for your reply, those route model conventions are not "convinient" I hope you guys will provide a better solution in the future.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
