### ISSUE TITLE
.net core 2.2 sdk install failed on windows 7 sp1

### ISSUE THREAD

**Issue by livarcocc** [aspnet/AspNetCore#6341]
_From @rakeshsinghranchi on January 2, 2019 19:56_

_From @OpenGDBX on December 26, 2018 9:15_

# Issue Title

.net core 2.2 sdk install failed on windows 7 sp1

# General

 the cabinet file sfx_x64.cab has an invalid digital signature

_Copied from original issue: dotnet/core-setup#4900_

_Copied from original issue: dotnet/core-sdk#234_

**Comment by livarcocc** [comment]
We do not depend on that file, as far as I am aware. @rakeshsinghranchi why did you move this to the sdk?

**Comment by livarcocc** [comment]
_From @rakeshsinghranchi on January 2, 2019 21:1_

Looks like it is aspnet MSI cab file. What repo does this need to go ? Moved this to core-sdk because SDK setup is impacted. 

cc @natemcmaster

**Comment by livarcocc** [comment]
_From @natemcmaster on January 3, 2019 17:55_

Use https://github.com/aspnet/AspNetCore for issues with ASP.NET Core.

**Comment by livarcocc** [comment]
_From @natemcmaster on January 3, 2019 17:57_

@Opengdbx can you share more details about the error message? Screenshots, console errors, log files if you have them, etc?

In 2.2, we stopped signing our installers with SHA1 (see security advisory https://docs.microsoft.com/en-us/security-updates/securityadvisories/2014/2949927). Windows 7 machines may need to be patched to support SHA2 digital signatures.

**Comment by maulikk2000** [comment]
Hi,

I have the same issue on Windows Server 2008 R2 64 bit standard. 
The error I get is 

---------------------------
A file that is required cannot be installed because the cabinet file (location)\sfx_x64.cab has an invalid digital signature.  This may indicate that the cabinet file is corrupt.

any fixes??

thanks,
Maulik Khandwala

**Comment by natemcmaster** [comment]
@maulikk2000 can you make sure your machine has the latest patches? See https://docs.microsoft.com/en-us/security-updates/securityadvisories/2014/2949927#suggested-actions

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by zengqinglei** [comment]
> Hi,
> 
> I have the same issue on Windows Server 2008 R2 64 bit standard.
> The error I get is
> 
> A file that is required cannot be installed because the cabinet file (location)\sfx_x64.cab has an invalid digital signature. This may indicate that the cabinet file is corrupt.
> 
> any fixes??
> 
> thanks,
> Maulik Khandwala

Hi 
I found a solution to this problem from the connection below.

https://docs.microsoft.com/zh-cn/security-updates/SecurityAdvisories/2015/3033929

Install the corresponding version of the patch.
