### ISSUE TITLE
Circuits lifetime and lifecycle

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6353]
Reconnection
 - optimistically restore circuit if not evicted yet
 - rules for eviction
 - UI to tell user they are disconnected and we're trying to reconnect

Disconnection API
 - On .NET side, might be enough that we are disposing the root component
 - On browser side, need to ensure we're exposing something you could hook into with JS

**Comment by BrennanConroy** [comment]
Blocked is a strong word, you can easily write naive reconnect logic, we even have docs for it. https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2#handle-lost-connection

**Comment by pranavkm** [comment]
# Meeting notes:

### What is a circuit?

* Ciruit is tied to an individual user (including anonymous users). 
* Has it's own sync context including it's own state such as `Renderer`. A circuit may have more than one rendered (multi-windows in a browser?)

## Features

* Tomb stoning based on some criteria e.g inactivity
* Expose events for disconnects
* Some effort to be made for reconnect. This may be entirely automated or we provide some nice APIs to allow developers to do so.
* Need to ensure that error handling works with circuits. Ties to (https://github.com/aspnet/AspNetCore/issues/4964, )

 -- Initial pass cut line -- These features don't need to go in the first pass of the feature

* Reconnect gets the user back to the state prior to disconnect.
* Some way for the client to say this is the circuit if it disconnects. If the server has the state, we'll use it. If the state has been evicted, we'll need for a way to allow the developer to rehydrate the state and allow the client to connect to it.

## UI (load screen \ spinner) for disconnects \ connects
* We want something like this in the templates by default.
* We could consider a `div` on the home page that is hidden by default. Pops up on the client on disconnect.

* Clean up circuit content
```C#
public class Circuit
{
    public Circuit(string id)
    {
        Id = id;
    }

    public string Id { get; }
}
```

We want to tie the filter to each instance of entry-point (consequently not DI).

```C#
builder.UseRazorComponents(x => x.UseCircuitManager<MyCircuitManager>());

public abstract class CircuitHandler
{
    /// <summary>A new circuit was established.</summary>
    public virtual Task OnCircuitOpenedAsync(Circuit circuit, CancellationToken cts) => Task.CompletedTask;

    /// <summary>A connection was established for an existing circuit. Fires once initially and each time during reconnect.</summary>
    public virtual Task OnConnectionUpAsync(Circuit circuit, CancellationToken cts) => Task.CompletedTask;

    /// <summary>A connection was disconnected.</summary>
    public virtual Task OnConnectionDownAsync(Circuit circuit, CancellationToken cts) => Task.CompletedTask;

    /// <summary>A circuit is being discarded. This would be the place to do things like tomb stoning</summary>
    public virtual Task OnCircuitClosedAsync(Circuit circuit, CancellationToken cts) => Task.CompletedTask;
}

// Example of a circuit handler:

public class MyCircuitHandler : CircuitHandler
{
    public override Task OnDisconnectedAsync(Circuit circuit, CancellationToken cts); 
    public override Task OnDisconnectedAsync(Circuit circuit, CancellationToken cts); 
}
```

### Client side events
```
window.Blazor.onConnectionUp : function() {}    
window.Blazor.onConnectionDown : function() {}
```

**Comment by pranavkm** [comment]
Server primitives are done. Client primitives and reconnects are being tracked via https://github.com/aspnet/AspNetCore/issues/7537
