### ISSUE TITLE
Automated eviction for circuits

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6358]
This would be a set of features for shutting down circuits that are idle and freeing the server resources associated with them. This could be simple like an idle timeout, or more sophisticated like a cache eviction strategy based on resource constraints.

**Comment by javiercn** [comment]
We should attach to `onbeforeunload` on the client and evict the circuit automatically in that scenario.

**Comment by javiercn** [comment]
We already get rid of the circuit when it becomes disconnected in two cases:
* There are too many disconnected circuits.
* A certain amount of time passes.

**Comment by danroth27** [comment]
We've decided to close this as we already have a timeout and max number for circuits. This issue was tracking adding some sort of smart resource based eviction system, which is not clear is needed.
