### ISSUE TITLE
Add Razor Components project template to SDK

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6365]
Need to add the existing template to the SDK for the preview2 release.

**Comment by pranavkm** [comment]
We got an insertion in to the build. However, the Component template depend on two packages that aren't part of the offline cache \ dotnet-core feed:

* Microsoft.AspNetCore.Blazor.Mono
* Microsoft.JSInterop

I guess the latter gets produced by some team, I'm going to figure out if we can get that inserted in to the dotnet-core feed and restored as part of offline cache. I'm not sure about the former though - should that reference be removed?

**Comment by pranavkm** [comment]
cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
Microsoft.JSinterop is us too (github.com/dotnet/jsinterop). 

If we want to drop the Blazor.Mono dependency we will need to do a bit more refactoring to make it optional.

**Comment by pranavkm** [comment]
This is done. We need a few rounds of updating the versions \ cleanup that @SteveSandersonMS  is already doing.
