### ISSUE TITLE
Debugging Support for Razor Components

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6373]
We need to do code generation work to make the generated code debuggable (proper alignment and line mappings). 

We should add a test that verifies for each generated document that all of the code the user put in that shows up in the output has an associated line-mapping. 

This item **does not** include web assembly debugging, that's it's own item.

**Comment by ajaybhargavb** [comment]
Changing the cost as this includes fixing all the places with incorrect/missing pragmas on top of adding the tests.
