### ISSUE TITLE
RefTagHelperDescriptorProvider should check for the presence of the `ElementRef` type

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6376]
The `RefTagHelperDescriptorProvider` successfully creates the ref tag helper even when there aren't any references to component types in the project. We should make this dependent on a reference to `ElementRef`.

**Comment by SteveSandersonMS** [comment]
Looks like you did this in https://github.com/aspnet/AspNetCore-Tooling/pull/119/files#diff-563a5737fd6efd389fc9bd07a1165b42R31

Can this be closed?

**Comment by rynowak** [comment]
lol that was fast. I was going to close this bug after my important meeting :)
