### ISSUE TITLE
[ApiController] action parameter source inference for collection of complex objects

### ISSUE THREAD

**Issue by Abarbz** [aspnet/AspNetCore#6379]
[Documentation ](https://docs.microsoft.com/en-us/aspnet/core/web-api/index?view=aspnetcore-2.1#binding-source-parameter-inference) states that 
>[FromBody] is inferred for complex type parameters. [...] [FromBody] isn't inferred for simple types such as string or int.

I was thus expecting collections of complex custom type to be inferred [FromBody] which isn't the case.
Sending the exact same request to the following two endpoints produce different results:
```csharp
//Using ASP.NET Core 2.1

[Route("api/[controller]")]
[ApiController]
public class PointsController : ControllerBase
{
        //Always returns Bad request
        [HttpPost("without")]
        public ActionResult<Point[]> PostWithoutFromBodyAttribute(Point[] points)
        {
            return InternalPost(points);
        }

        //Properly returns Ok
        [HttpPost("with")]
        public ActionResult<Point[]> PostWithFromBodyAttribute([FromBody] Point[] points)
        {
            return InternalPost(points);
        }

        private ActionResult<Point[]> InternalPost(Point[] points)
        {
            return points.Any() 
            ? (ActionResult<Point[]>) Ok(points) 
            : BadRequest("Collection was empty");
        }
}
```
As nothing is said about collection maybe my initial assumption was outright wrong. In that case, that would made a nice clarification to the doc.

**Comment by pranavkm** [comment]
@Abarbz this was an unfortunate bug in our 2.1 release that has since been fixed in 2.2. To sum it up, in 2.1, in the absence of a `[From*]` attribute, collection type parameters are inferred to be bound from query. https://github.com/aspnet/Mvc/issues/8536 has more details.

Upgrading to 2.2 would be the recommended fix. If upgrading isn't an option, using `[FromBody]` for collection parameters should work.

**Comment by Abarbz** [comment]
Thanks @pranavkm for the update. Don't you think the documentation should also explain the expected behavior of collection?

**Comment by pranavkm** [comment]
@Abarbz sure, would you like to send a PR to the docs repo to add a remark?
