### ISSUE TITLE
[Blazor] detect key pressed in mouse events

### ISSUE THREAD

**Issue by detachmode** [aspnet/AspNetCore#6382]
Is it possible to detect if the user holds down a key, while a mouse click event fired.
Typical scenario is, where a user holds down shift and I would like to do a different logic if he clicks on something.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @detachmode.
This is already supported via properties on the `UIMouseEventArgs` type: https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/UIEventArgs.cs#L261
