### ISSUE TITLE
How to solution this error?My code and web.config don't have any mistake

### ISSUE THREAD

**Issue by mobi12** [aspnet/AspNetCore#6383]
HTTP Error 500.0 ON Windows IIS
### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`

**Comment by blowdart** [comment]
Thank you for filing this issue. In order for us to investigate this issue, could you please provide us with a minimalist repro project that illustrates the problem?
