### ISSUE TITLE
[Feature,Identity] Add phone number login

### ISSUE THREAD

**Issue by EssenRoc** [aspnet/AspNetCore#6384]
### Describe the solution you'd like
Sign in to your account with your phone number.
I think this is easy to implement.

microsoft.com:
![image](https://user-images.githubusercontent.com/12685126/50687710-5a083100-105d-11e9-9228-f645cd98f952.png)
google:
![image](https://user-images.githubusercontent.com/12685126/50688087-dbac8e80-105e-11e9-81eb-5a9e7f31edda.png)

**Comment by blowdart** [comment]
"Easy" is relative. It would mean changing a lot of assumptions in identity for a feature that isn't commonly asked for and would support a login method that can't be easily verified, so no, this isn't something we'd consider at this time.

**Comment by valeriob** [comment]
Hi,
this feature would be very useful, and we need to implement it our self, may i ask what assumptions should be changed, so i can review what we have done if we missed something ?
