### ISSUE TITLE
Having asp.net razor for service side and Blazor on client side on the same views.

### ISSUE THREAD

**Issue by A51UK** [aspnet/AspNetCore#6387]
The idea is that you could use asp.net razor on service side when making the view but use Blazor to do any change on the clients side, like how with use asp.net razor with JavaScript now. The reason for this is to allow the page to be sent with some data on load and then use Blazor for any update or change after the page been sent.

A example of this would be on a shopping site where the first 10 product would be sent on the page when sent to the user and next load of product would be load on the page by the use of Blazor and Web API. it would be good for SEO as google would be able to see the first 10 product without it need run any Blazor code. In order to do this there would be need a way to say with part of the code is for Blazor and with part for the service side (e.g. razor). This would also allow for a more easy upgrade route for non-Blazor website to be able to use Blazor.

**Comment by Andrzej-W** [comment]
Hopefully this problem will be resolved here #5464

**Comment by mkArtakMSFT** [comment]
Thanks @Andrzej-W. We're closing this as a dupe.
