### ISSUE TITLE
TestServer blocks on HostedService asyncronous background threads

### ISSUE THREAD

**Issue by sjlangleyCSGI** [aspnet/AspNetCore#6395]
A .NET Core 2.1 TestServer instance which adds a HostedService (with an infinite loop) at startup blocks on that thread instead of running it asynchronously.

### To Reproduce
1. Using: ASP.NET Core '2.1', XUnit 2.4, and Microsoft.AspNetCore.Mvc.Testing 2.1.3
2. In service's Startup.cs:
    In ConfigureServices(IServiceCollection services):
    services.AddHostedService<IHostedService>();
    In IHostedService.StartAync() <- infinite loop for background work
3. In Test project, create instance of TestServer using service's IWebHostBuilder and execute tests against service

### Expected behavior
Tests should execute, but instead the tests hang as the service never completes starting up.

I suspect that TestServer is awaiting IHostedService.StartAsync. Have a workaround by refactoring IHostedService's StartAsync to return immediately calling another async method to perform work. Example:

//hangs in TestSever instance
public async Task StartAsync(CancellationToken cancellationToken)
{
    //infinite loop
}

//works in TestServer instance
public async Task StartAsync(CancellationToken cancellationToken)
{
    DoTheWork(cancellationToken);
}
public async Task DoTheWork(CancellationToken cancellationToken)
{
    //infinite loop
}

### Additional context
Does not effect Kestrel server, only TestServer

**Comment by dallancarr** [comment]
Possibly by design. Return the Task or Execute and return `Task.CompletedTask`

**Comment by sjlangleyCSGI** [comment]
So why the difference in behavior with Kestrel?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
