### ISSUE TITLE
Remove Microsoft.AspNetCore.Mvc.Core dependency from Microsoft.AspNetCore.Mvc.Testing

### ISSUE THREAD

**Issue by slang25** [aspnet/AspNetCore#6399]
Currently `Microsoft.AspNetCore.Mvc.Testing` doesn't use anything from the `Microsoft.AspNetCore.Mvc` namespace, so I was surprised to see that it brought in a dependency on `Microsoft.AspNetCore.Mvc.Core`.

It does however depend on `Microsoft.Extensions.DependencyModel`, so I propose it be updated to reflect that. It also seems unnecessary for this package to have `Mvc` in the name, however that ship has sailed.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @slang25.
@javiercn, can you please have a look at this? Thanks!

**Comment by pranavkm** [comment]
@natemcmaster might have a better idea, but for 3.0, it's likely that the package would have a `FrameworkReference` to `Microsoft.AspNetCore.App` rather than package reference. This might not make much sense once it's retargeted.

**Comment by javiercn** [comment]
That's what I would expect.

**Comment by javiercn** [comment]
> It also seems unnecessary for this package to have `Mvc` in the name, however that ship has sailed.

This package contains all the MVC specific tweaks that are needed for unit tests to work properly, that's why MVC was on the name at the time. Many of those restrictions have gone away.

**Comment by natemcmaster** [comment]
> it's likely that the package would have a FrameworkReference to Microsoft.AspNetCore.App rather than package reference. 

Correct. See https://github.com/aspnet/AspNetCore/issues/4257

**Comment by pranavkm** [comment]
Thanks for the issue report @slang25. Since refactoring the references is already being tracked, closing this issue as there's nothing more to do here.

**Comment by slang25** [comment]
Thanks all for the information, that makes sense 👍
