### ISSUE TITLE
Blazor project templates hosted and server-side, why two projects created?

### ISSUE THREAD

**Issue by netbitshift** [aspnet/AspNetCore#6402]
There are 3 different project templates.
- Blazor
- Blazor (ASP.NET Core hosted)
- Blazor (Server-side in ASP.NET Core)

My question is in regards to the last 2.  

When you use one of those projects you get:
(Server-side in ASP.NET Core), which will look something like this in VS 2017
![image](https://user-images.githubusercontent.com/17503279/50710551-eb14e300-1030-11e9-81dd-9c4ea8bfb0df.png)

With the ASP.NET Core hosted template, you get something like this
![image](https://user-images.githubusercontent.com/17503279/50710637-18619100-1031-11e9-9eda-ff6585a1d995.png)

In each case, the ".Server" project "serves" up the ".Client" app, for lack of a better term.
My question(s) are 
(1) In the case of the "Server-side in ASP.NET Core" template, why have one project there only to "serve" up the .Client app?  
(2) Could I convert the base "Blazor" project to use "Server-side" framework? In other words, can I take the 1st project template, which creates a single project that uses the "Client" hosting model and convert that to "Server-side"?

**Comment by netbitshift** [comment]
Components and MVC Views?  In the case of the "Server-side" template, isn't that already the case - the "pages" get converted at build, to views and components, correct?

Also, when you say VS 16 - you're referring to Visual Studio 2019?

**Comment by rynowak** [comment]
> Components and MVC Views? In the case of the "Server-side" template, isn't that already the case - the "pages" get converted at build, to views and components, correct?
All of the Razor files in blazor-hosted.Client will be compiled as Components
All of the Razor files (currently you have none) in blazor-hosted.Server will compiled as MVC Views or Pages

We don't currently provide a project template for a *self hosted* Blazor Server Side application, but there's no technical reason why this couldn't work. You would need basically combine the two projects - keep `Program.cs` from the server project, and rename `Startup` in the client project to something else.


> Also, when you say VS 16 - you're referring to Visual Studio 2019?

Yes, sorry for the confusion 👍  We spend a lot more time talking about projects with their internal name before the official name is announced, so the internal name is more stick 😆
