### ISSUE TITLE
Razor BackgroundParser thread is not marked as background

### ISSUE THREAD

**Issue by KirillOsenkov** [aspnet/AspNetCore#6409]
We've just noticed that when Razor background process runs MonoDevelop process doesn't die after you close the Main Window.

It turns out the background parser doesn't mark its thread as Background, so the runtime doesn't terminate the process until that thread is done.

https://github.com/aspnet/AspNetCore-Tooling/blob/56a7ce9762d9d181048e87620e120d491a48f8d9/src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundParser.cs#L257

We should set https://referencesource.microsoft.com/#mscorlib/system/threading/thread.cs,babbe0201454caa0 to true so the thread is automatically aborted by the runtime during shutdown.

@NTaylorMullen this is in Microsoft.VisualStudio.Mac.RazorAddin_8.0.0.31868.mpack that you've provided for us. Would you be able to provide us with a new .mpack when a fix for this is available? Thanks!

**Comment by NTaylorMullen** [comment]
43d55d00d3c6e863df235ee8e2ebeb4f079ab5ee
