### ISSUE TITLE
antiforgery bad request and hidden 404 result problem

### ISSUE THREAD

**Issue by omuleanu** [aspnet/AspNetCore#6410]
I recently faced a problem in asp.net core 2.2 (latest version atm)

I'll describe the scenario that I was able to isolate and reproduce consistently.
1. In Startup.cs have this in `ConfigureServices`:
 ```
 services.AddMvc(o =>
{               
    o.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
});
```
and this in the `Configure` method:
```
app.UseStatusCodePagesWithReExecute("/Error/HttpError", "?statusCode={0}");
```
2. Now you need to create the `ErrorController` with `HttpError` action and when the statusCode is 404 you need to return a **View** which will **use the _Layout.cshtml** ( !important ), also add `        [IgnoreAntiforgeryToken]` on the `HttpError` action.

3. In `_Layout.cshtml` you need you need to have `@Html.AntiForgeryToken()` (reason being that you want to use it on ajax post requests)
4. Install `signalr` client library and reference it in `_Layout.cshtml` ( we need a js file with .min.js so that Chrome console will ask for .min.js.map )
5. Delete the signalr `.min.js.map` files if you have them.
6. Add some code in `Home/Index.cshtml` that will do ajax requests, in my example:
```
<script>
    function load() {
        var key = '__RequestVerificationToken';

        var token = $('[name="' + key + '"]').val();
        var data = [{ name: key, value: token }];
        $.post('@Url.Action("GetData", "Home")', data)
            .done(function (res) {
                console.log(res);
                $('#result').append('<p>ok</p>')
            }).fail(function (err) {
                console.log('error', err);
                $('#result').append('<p>error</p>')
            });
    };

    $(function () {
        load();

        $(document).click(load);
    });
</script>

<div id="result">
</div>
```
and dont' forget to add the action in HomeController:
```
        public IActionResult GetData()
        {
            return Json(new { abc = 1 });
        }
```
7. Run the demo (on **IIS Express**) in Google Chrome (Home/Index) and you should be getting "ok" lines being appended to the document when clicking on the document, 
Now hit F12 to open the chrome console and the browser will try to load the signalr.min.js.map file which doesn't exist, we will get a **404** which returns a view with `_Layout.cshtml` that has `@Html.AntiForgeryToken()` and from now when you click on the document you'll get **400** `bad request` result from the server.

please note we won't actually notice the request to `signalr.min.js.map` in the chrome console, it's not visible in the Network tab

EDIT: 
another way I got this again using:
`app.UseStatusCodePagesWithReExecute` for status code 101 (signalr/synchub, by accident, I never intended to handle 101) 
I returned again a View that uses the `_Layout.cshtml` with `@Html.AntiForgeryToken()`, obviously this new token never reached the page content,
 and all subsequent requests with the token that is rendered in the page resulted in 400 bad request

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
