### ISSUE TITLE
"No IUserTokenProvider is registered" ASP.Net Core 2.1

### ISSUE THREAD

**Issue by YurasNazar** [aspnet/AspNetCore#6413]
### Describe the bug
So I got the exception when call GenerateEmailConfirmationTokenAsync(user.Id) method. However , in startup class in ConfigureServices method I call AddDefaultTokenProvider() extensions method when service.AddIdentity..... uses.

### To Reproduce
1. Using this version of ASP.NET Core 2.1
2. Run this code 
```
 var emailVerificationCode = await 
 unitOfWork.UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
```
3. In startup I provide:
 ```
services.AddIdentity<User, Role>()
                .AddEntityFrameworkStores<TimerContext>()
                .AddDefaultTokenProviders();
```
4. And I got the following exeption
Message - No IUserTokenProvider is registered.
Source - Microsoft.AspNet.Identity.Core

### Expected behavior
As I know the AddDefaultTokenProviders() extension must provide all the token provider in order to safely generate token for different purpose such as email confirmation , password recover or phone confirmation , but he does not doing it.

### Screenshots
![screenshot_2](https://user-images.githubusercontent.com/45370015/50724711-77d7a380-10fa-11e9-8dd5-102334a1f14e.png)
![screenshot_3](https://user-images.githubusercontent.com/45370015/50724726-a3f32480-10fa-11e9-973e-72c2cbaf3b17.png)
![screenshot_4](https://user-images.githubusercontent.com/45370015/50724733-b66d5e00-10fa-11e9-8606-373b6b181311.png)

### Additional context
Exception thrown: 'System.NotSupportedException' in Microsoft.AspNet.Identity.Core.dll
Exception thrown: 'System.NotSupportedException' in System.Private.CoreLib.dll
Exception thrown: 'System.NotSupportedException' in System.Private.CoreLib.dll
Exception thrown: 'System.NotSupportedException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action method gtdtimer.Controllers.UserController.Post (gtdtimer), returned result Microsoft.AspNetCore.Mvc.OkResult in 4494.0021ms.
An unhandled exception of type 'System.NotSupportedException' occurred in System.Private.CoreLib.dll
No IUserTokenProvider is registered.

**Comment by blowdart** [comment]
Can we get a minimal repro in code? Your code snippets look fine, but NotSupported isn't one we'd throw.

**Comment by YurasNazar** [comment]
> Can we get a minimal repro in code? Your code snippets look fine, but NotSupported isn't one we'd throw.

Here is repository:  [https://github.com/ss-ita/gtd-timer-server](url)

**Comment by YurasNazar** [comment]
Here is repository: https://github.com/ss-ita/gtd-timer-server

**Comment by blowdart** [comment]
@HaoK can you take a look see?

**Comment by HaoK** [comment]
Your token provider is registered against `IUser` while AddDefaultTokens is against `<User>`


```
            // User
            services.AddIdentity<User, Role>().AddEntityFrameworkStores<TimerContext>().AddDefaultTokenProviders();

            // vs IUser
            this.UserTokenProvider = new UserTokenProvider<IUser>();
```
