### ISSUE TITLE
I want snake_case in MVC

### ISSUE THREAD

**Issue by jacobslusser** [aspnet/AspNetCore#6417]
By default, ASP.NET Core MVC will serialize everything as camelCase. I'm not just talking about JSON either... I'm talking about EVERYTHING: controller names, route data, enumerations, query string params, etc.... 

I would like a simple way to change the casing strategy of the whole application from camelCase to snake_case.

I've tried to hook into the many extension points for doing this, but often times they are very complicated or insufficient. Again, I'm not referring to simply JSON serialization. For example, if you want to serialize query params differently you need a custom `QueryStringValueProvider`. If you want to change the controller names to snake_case, you might try a custom `IControllerModelConvention`. etc...

The problem is that these extension points are scattered all over the application instead of in one simple place and despite my best efforts, there are still gaps in my coverage and I can't seem to get it 100% complete.

Finally, once you track down most of these possible extension points and make changes, you're still in a world of hurt when it comes to documentation generation. It seems that the `ApiExplorer` is unaffected by these other approaches and so you're left making similar changes to it so that it generates documentation to match the behavior changes you've made to the casing strategy of the application.

I believe a simple way to change the default behavior across the application would be an excellent feature. In the meantime, I would welcome any direction on how to accomplish this in the current 2.0 - 2.2 frameworks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jacobslusser.
We have no plans about doing this as this is not as straight forward as well as doesn't provide enough value.
