### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.CookiePolicy, Version=2.2.0.0

### ISSUE THREAD

**Issue by vitek-karas** [aspnet/AspNetCore#6422]
Moving from dotnet/core-setup#4923 on behalf of @JulidaRocks

## Steps to reproduce
Upgraded from dotnet core 2.1 to 2.2. When running the integration tests, an exception is thrown when initializing TestServer with 
`var testServer = new Microsoft.AspNetCore.TestHost.TestServer(webHostBuilder);`

## Expected  behavior
Should create the test server object

## Actual behavior
throws exception

## Environment data

Stack trace:

   at <projectname>.Api.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at <projectname>.Api.IntegrationTests.IntegrationTestFixture.CreateServer(String currentDirectory, Boolean authenticated, Boolean useAdAuthentication) in <pathtoproject>.Api.IntegrationTests\IntegrationTestFixture.cs:line 50
   at <projectname>.Api.IntegrationTests.Ability.AbilityCategoryIntegrationTests.Initialize() in <pathtoproject>.Api.IntegrationTests\Ability\AbilityCategoryIntegrationTests.cs:line 41

Packages in .Api-project

  ```xml
<ItemGroup>
    <PackageReference Include="AutoMapper" Version="8.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Equ" Version="2.0.2" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.2.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="2.2.0" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.0" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.18" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.12.0" />
    <PackageReference Include="SimpleInjector" Version="4.4.3" />
    <PackageReference Include="SimpleInjector.Integration.AspNetCore.Mvc" Version="4.4.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
  </ItemGroup>
```

Packages in .Api.IntegrationTests-project:

```xml
<ItemGroup>
    <PackageReference Include="Equ" Version="2.0.2" />
    <PackageReference Include="FluentAssertions" Version="5.5.3" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="NUnit" Version="3.11.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.12.0" />
    <PackageReference Include="SimpleInjector" Version="4.4.3" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>
```

**Comment by cjlotz** [comment]
Also getting something similar for our integration tests - `Could not load file or assembly 'Microsoft.AspNetCore.Cors, Version=2.2.0.0`

**Comment by mrlund** [comment]
I was having the issue with the `Microsoft.AspNetCore` file or assembly, and solved it by adding a package reference to the test project, like so: 
`<PackageReference Include="Microsoft.AspNetCore.App" />`

**Comment by JulidaRocks** [comment]
@mrlund thanks, this fixed the issue!
