### ISSUE TITLE
ASP.NET Core 2.1 custom logger lifetime

### ISSUE THREAD

**Issue by GoFightNguyen** [aspnet/AspNetCore#6423]
I created an a custom implementation of ILogger and ILoggerProvider in order to function with my enterprise's logging system. The lifetime of my custom ILogger appears to be a singleton; I can make numerous requests and see the ILoggerProvider.CreateLogger is only invoked the first time.

Is it possible to configure my custom implementation to have a scoped lifetime?

**Comment by davidfowl** [comment]
Nope. Loggers are singletons. What are you trying to do?

**Comment by GoFightNguyen** [comment]
Without getting into the why, I wanted to experiment with an ILogger acting similar to a StringBuilder in that it builds an aggregation of messages as a single message. As such, it would need a scoped lifetime to prevent cross-request message interference.

In general, I agree with a singleton logger though. I'll consider alternative approaches still able to work within the logging pattern of ASP.NET Core.
