### ISSUE TITLE
To facilitate the development of applications based on Blazor, it is recommended to develop a .NetCore version of electron

### ISSUE THREAD

**Issue by 199621616** [aspnet/AspNetCore#6428]
C#开发者有相当多一部分是开发企业应用的，Blazor可能为传统企业应用的互联网转型带来非常好的一条途径。然而，企业应用中非常重的一部分功能需要调用客户机的资源，而Electron则是个很好的解决方案。Asp.NetCore WebApi + Blazor + Electron，是理想的“三宝”组合。所以，非常希望微软开发一个的.NetCore版的Electron。

**Comment by TheFanatr** [comment]
I agree with this (if Google translate isn't lying)

**Comment by 199621616** [comment]
大量的WinForm、WPF应用无法直接转型为互联网现代应用。难道不能考虑走这个路径：Asp.NetCore WebApi + Blazor + WinForm（WPF）？像mblataric所说的，“海量数据输入，与扫描仪，条形码阅读器，RFID扫描仪等设备的连接......浏览器永远不会成为这种情况的平台。“，而WebApi + Blazor + WinForm（WPF）则很容易做到这一点。让WinForm（WPF） ）直接托管Blazor！实现真正的C＃全栈开发。

**Comment by Eilon** [comment]
> A large number of WinForm and WPF applications cannot be directly transformed into modern Internet applications. Can't you consider taking this path: Asp.NetCore WebApi + Blazor + WinForm (WPF)? As mblataric said, "massive data input, connections to scanners, barcode readers, RFID scanners, etc... browsers will never be the platform for this situation.", while WebApi + Blazor + WinForm (WPF) makes it easy to do this. Let WinForm (WPF) directly host Blazor! Realize true C# full stack development.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback.
We don't have immediate plans to support Blazor on Electron.
