### ISSUE TITLE
I hope the Razor component can build modal components that are referenced by events.

### ISSUE THREAD

**Issue by 199621616** [aspnet/AspNetCore#6429]
医生给病人下诊断时，需要方便的从四五万种疾病编码中找出当前患者所患疾病的编码，查找方式类似https://hisp.chinacloudsites.cn/fetchdata 这里看到的这个查找方式，并且需要返回疾病的编码与名称。如果这个组件能在事件中调用并用模态组件进行查找并返回结果，我认为是一种比较好的操作使用体验。所以，希望Razor组件可用来方便的构建一种能通过事件调用并且可接收返回值的模态组件。

**Comment by Eilon** [comment]
Bing translate:

> When a doctor gives a patient a diagnosis, it is convenient to find out the encoding of the current patient's disease from the forty thousand or fifty thousand disease codes, looking in a way similar to the https://hisp.chinacloudsites.cn/fetchdata seen here, And you need to return the encoding and name of the disease. If this component can be called in an event and found with a modal component and returns results, I think it is a better operational experience.

Therefore, it is hoped that the razor component can be used to facilitate the construction of a modal component that can be called through events and can receive return values.

Google translate:

> When a doctor gives a diagnosis to a patient, it is convenient to find out the coding code of the current patient's disease from the code of four or five thousand kinds of diseases. The search method is similar to https://hisp.chinacloudsites.cn/fetchdata. And you need to return the code and name of the disease. If this component can be called in an event and used modal components to find and return results, I think it is a better operating experience. Therefore, it is hoped that the Razor component can be used to easily construct a modal component that can be called by an event and can receive a return value.

**Comment by wanton7** [comment]
Going by this "great" translation, this issue is maybe about Blazor and modals? If it's about creating modals with Blazor then just use Bulma. It's CSS framework without any JavaScript. It integrates easily with any other framework. So you can use it to create modals with Blazor/Razor Components very easily, because it's just a class toggle. https://bulma.io/documentation/components/modal/

**Comment by 199621616** [comment]
@wanton7 谢谢
