### ISSUE TITLE
DateTime differs for GET and POST

### ISSUE THREAD

**Issue by NCC1701M** [aspnet/AspNetCore#6439]
### Describe the bug
The formatters for a controllers POST and GET requests handles the DateTime formatting different.

### To Reproduce
1. Using this version of ASP.NET Core '2.x'
2. Setup an Asp.Net Core App and run this code
```csharp
using System;
using Microsoft.AspNetCore.Mvc;

namespace MyProject.Controllers
{
	/// <summary>
	/// Simple test controller
	/// </summary>
	public class DateController : Controller
	{
		[HttpGet("[controller]")]
		public IActionResult MyGetHandler([FromQuery] MyRequest req)
		{
			Console.WriteLine(req.MyDate);
			return Ok();
		}

		[HttpPost("[controller]")]
		public IActionResult MyPostHandler([FromBody] MyRequest req)
		{
			Console.WriteLine(req.MyDate);
			return Ok();
		}
	}


	public class MyRequest
	{
		public int MyInt { get; set; }
		public DateTime MyDate { get; set; }
	}
}
```
3. Inspect the `req.MyDate` variable and see the differences

### Expected behavior
The formatted date should always be the same. Either Utc or local.

### Screenshots
![asp net core datetime error](https://user-images.githubusercontent.com/7260053/50767052-b9dc2300-127b-11e9-8282-9e5f645fda38.gif)

### Additional context
Include the output of `dotnet --info`
.NET Core SDK ("global.json"):
 Version:   2.2.101
 Commit:    236713b0b7

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @NCC1701M.
This behavior is coming from the JSON.NET which we consume for parsing DateTime objects from the Body of the request. If you need to customize that logic, feel free to customize it.
In #11584 we are going to try to respect the current DateTime kind passed in to the Model Binding.
