### ISSUE TITLE
JSON standard for REST API and HATEOAS

### ISSUE THREAD

**Issue by rafsanulhasan** [aspnet/AspNetCore#6441]
### Is your feature request related to a problem? Please describe.
With swagger open API definition, I'm try to standardize the JSON schema like defined in JSON-SCHEMA.org or ion specification. 

ASP.NET core does not support this. I've to do it myself

I'm trying to have a self documented API using ASP.NET MVC but can not.

### Describe the solution you'd like
I'd like to have a pure schema specification definition and apply HATEOAS constraints using the framework.

The framework should have a support for self-documentation for RESTful APIs. 

### Describe alternatives you've considered
It is clearly defined in the following linkedin learning video tutorial by Nate Barbettini

https://www.linkedin.com/learning/building-and-securing-restful-apis-in-asp-dot-net-core-2/the-power-of-restful-apis

### Additional context
I'm building an open source project to do it but it would be great if the framework itself has support for it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rafsanulhasan.
@glennc what do you think we do here?

**Comment by rafsanulhasan** [comment]
Hi @Eilon @mkArtakMSFT @glennc,

I've tried to come up with these:
1. https://github.com/sicsbd/JsonTools
2. https://github.com/sicsbd/JsonSpecs

Please have a look and suggest me what can I do with it.
There are a lot of things to do. These are just the starting

**Comment by mkArtakMSFT** [comment]
Thanks @rafsanulhasan.
In 3.0 we're working with community to have great API documentation support through OpenAPI. We have no plans to support any specific hyper-media based formats. You are, however, free to use any existing community-based solutions.
