### ISSUE TITLE
"blazor-dev" gallery not working

### ISSUE THREAD

**Issue by JipingWang** [aspnet/AspNetCore#6444]
### Describe the bug
Added "blazor-dev" gallery to VS, not working
  https://github.com/aspnet/AspNetCore/tree/master/src/Components#using-ci-builds-of-blazor
  https://dotnet.myget.org/F/blazor-dev/vsix/

Error in output Package Manager:
[blazor-dev-vsix] The V2 feed at 'https://dotnet.myget.org/F/blazor-dev/vsix/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework=''&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '404 Not Found'.
[blazor-dev-vsix] The V2 feed at 'https://dotnet.myget.org/F/blazor-dev/vsix/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '404 Not Found'.

but, the old one works
  https://dotnet.myget.org/f/blazor-dev/api/v3/index.json

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JipingWang.
What version of VS are you using? We can not reproduce the issue you're facing while using VS 2017.

**Comment by mkArtakMSFT** [comment]
It would be great if you could provide us with a stable repro, so we can investigate this further.

**Comment by JipingWang** [comment]
You may close this. I setup some Nuget Package source, then VS pick the wrong one "blazor-dev-vsix" to fetch. I've manually cleaned up my Nuget config.
