### ISSUE TITLE
post method not get called on razor pages after migrating to asp.net cor 2.2

### ISSUE THREAD

**Issue by mtad2002** [aspnet/AspNetCore#6446]
I'm facing this problem , after migrating my project from asp.net core 2.1 to asp.net core 2.2 , in one of my razor pages post methods not getting call and browser stuck in posting back form.

**Comment by mtad2002** [comment]
this is some of this PageModel code :

```C#
  public class VerifyModel : PageModel
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly AppDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private FileHelpers _fileHelpers; //this my custom created class for uploading files

        public VerifyModel(
                           UserManager<ApplicationUser> userManager,
                           AppDbContext context,
                           IHostingEnvironment environment,
                           FileHelpers fileHelpers)
        {
            _userManager = userManager;
            _context = context;
            _hostingEnvironment = environment;
            _fileHelpers = fileHelpers;
        }

   public async Task<IActionResult> OnGetAsync()
        {
      //some normal data load
       }

   public async Task<IActionResult> OnPostAsync()
        {
       //getting input from one form and save
       }

   public async Task<JsonResult> OnPostFileUploadAsync()
        {
       //getting file that sent from ajax call and save
      }

   }  

```

my problem is if the page had problem it shouldn't worked with asp.net core 2.1 , beside if my app architectur have problem other pages in the same directory should not work too.

**Comment by mtad2002** [comment]
this from out put window when post form 

``
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/2.0 POST https://localhost:44329/Identity/Account/Manage/Verify application/x-www-form-urlencoded 697
Microsoft.AspNetCore.Routing.EndpointMiddleware:Information: Executing endpoint 'Page: /Account/Manage/Verify'
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker:Information: Route matched with {page = "/Account/Manage/Verify", area = "Identity", action = "", controller = ""}. Executing page /Account/Manage/Verify
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization was successful.
``
i don't know what is application/x-www-form-urlencoded 697  but when other pages post back it doesn't appear

**Comment by NTaylorMullen** [comment]
@mtad2002 can you reproduce the issue on a brand new app? It'd be helpful to have a minimal project that reproduces the issue.

**Comment by mkArtakMSFT** [comment]
@mtad2002, unfortunately we are unable to reproduce the issue given this much info. With the code snippet given - the page handler is being hit. Again, if you could provide a project, which can reproduce the issue for us, we'll happily investigate it further.

As for now we plan to improve the log message you've shown above to include the page handler which was matched:
> Route matched with {page = "/Account/Manage/Verify", area = "Identity", action = "", controller = "", **handler=""**}.

**Comment by mkArtakMSFT** [comment]
@mtad2002, are you saying that the issue doesn't reproduce consistently or you simply can't get the same behavior on a different project?
