### ISSUE TITLE
OnConnectedAsync and OnDisconnectedAsync are not invoked when a client application attempts to establish signalR connection

### ISSUE THREAD

**Issue by Arash-Sabet** [aspnet/AspNetCore#6448]
### Describe the bug
Create a signalR server application, derive a class from `Hub `class and override `OnConnectedAsync `and `OnDisconnectedAsync `in the derived class. Log some distinctive texts upon raising either of those events to ensure that you can track when they are raised. When a signalR client application like an angular application attempts to establish a connection, `OnConnectedAsync` may not raise in signalR server's side. If that happens, `OnDisconnectedAsync ` won't raise too at disconnection attempt. This issue is intermittent but it happens noticeably. This issue's frequency increases when the singalR server is using Azure's SignalR Services.

### To Reproduce
1. Using this version of ASP.NET Core 2.2.
2. Follow the instructions above to setup a client and server application. Try both C# client and angular client applications.

### Expected behavior
OnConnectedAsync and OnDisconnectedAsync events should be raised consistently upon establishing or disconnecting connections.

**Comment by bradygaster** [comment]
Have you seen this locally with a single server as well? Adding @BrennanConroy as well so we can help troubleshoot.

**Comment by Arash-Sabet** [comment]
@bradygaster Yes, I have.

**Comment by BrennanConroy** [comment]
>OnConnectedAsync may not raise in signalR server's side

When this happens can the client send and receive messages still? It sounds like the connection might not actually be established, thus the two methods wont be invoked.

**Comment by Arash-Sabet** [comment]
@BrennanConroy No, they cannot as far as I remember.

**Comment by BrennanConroy** [comment]
Can you take a look at your client and server logs to see if there is any errors?

**Comment by Arash-Sabet** [comment]
No errors raised in client and server. This issue happens silently.

**Comment by BrennanConroy** [comment]
Could you collect and share network traces?

**Comment by Arash-Sabet** [comment]
@BrennanConroy will keep your request in my radar. As soon as I get a chance to get the code undone and this issue raises again, I will share the network traces collected via Chrome.

**Comment by Arash-Sabet** [comment]
@BrennanConroy The attached file is captured from Chrome's Network's console. I masked some names and there were a few lines related to our UI components that I removed to reduce the noise. This log captured when the application is utilizing Azure's SignalR Services. 

According to this log file, first, the signalR client application which is an angular app establishes the connection to the signalR server and later on we have it disconnect. Neither OnConnectedAsync nor OnDisconnectedAsync was raised and no exceptions or failures happened to catch and log on the server side.

Here it is the link to the network trace: [shareongithub.txt](https://github.com/aspnet/AspNetCore/files/2736802/shareongithub.txt)

Reproducing this issue in the absence of Azure SignalR Service is a bit harder but I will keep an eye on it. Hope this log file help you guys move forward.

**Comment by Arash-Sabet** [comment]
@BrennanConroy @bradygaster 
I have attached a few files which include further details from Network tab. These files were captured when `OnConnectedAsync` did not raise when the client app tried to establish the connection with the server. Interestingly the heartbeat kept happening. 
This information was collected and then masked/renamed when the signalR server is not leveraging Azure SignalR Service. Hope it helps.

**Some details:** [details1.txt](https://github.com/aspnet/AspNetCore/files/2741501/details1.txt)

![frames](https://user-images.githubusercontent.com/26050123/50909690-5c221500-13fa-11e9-841d-99067edd7550.JPG)
![screenshot1](https://user-images.githubusercontent.com/26050123/50909693-5c221500-13fa-11e9-93fd-2586c97940ae.jpg)
![cookies](https://user-images.githubusercontent.com/26050123/50909694-5c221500-13fa-11e9-8ed4-c0835d8f03b5.JPG)

**Comment by BrennanConroy** [comment]
What are you doing in your `OnConnectedAsync` function?

Also, could you try enabling client logs and logging message content via:
```typescript
const connection = new signalR.HubConnectionBuilder()
    .withUrl("/hubName", { logMessageContent: true })
    .configureLogging(signalR.LogLevel.Information)
    .build();
```

And I would like to see what is happening when you try to send a message from the client after it has received `{"type":6}` but hasn't invoked `OnConnectedAsync`

**Comment by Arash-Sabet** [comment]
@BrennanConroy 
Meanwhile, did you have a chance to [use this example ](https://github.com/aspnet/AzureSignalR-samples/issues/15)and try to reproduce the issue?

**Comment by muratg** [comment]
@Arash-Sabet, were you able to configure your logging as shown above? It would be help us diagnose this issue. Also, could you share your `OnConnectedAsync` method?

**Comment by Arash-Sabet** [comment]
@muratg we need few more days to test some other scenarios. I will get back to you after our conclusion.

**Comment by Arash-Sabet** [comment]
@muratg @BrennanConroy 
Meanwhile, please see the attached screenshot. It's captured when our signalR hub is leveraging the paid tier of Azure's SignalR Services.

![type7 error](https://user-images.githubusercontent.com/26050123/51408089-a8bccd00-1b2b-11e9-8822-ca7dc97b8160.png)

**Comment by muratg** [comment]
@Arash-Sabet thanks, we'll need to get the client logs though. Also, please share your `OnConnectedAsync` method. Thank you.

**Comment by Arash-Sabet** [comment]
@muratg I cannot share the source code of OnConnectedAsync.

**Comment by ammritt** [comment]
> @Arash-Sabet thanks, we'll need to get the client logs though. Also, please share your `OnConnectedAsync` method. Thank you.

Here are the client side logs:
Debug: Starting HubConnection.
Debug: Starting connection with transfer format 'Text'.
Debug: Sending negotiation request: https://.............................................
Debug: Selecting transport 'WebSockets'.
Information: WebSocket connected to wss://*************************.service.signalr.net/client/?....................
Debug: Sending handshake request.
Information: Using HubProtocol 'json'.
Debug: Server handshake complete.
Information: Close message received from server.
Error: Connection disconnected with error 'Error: Server returned an error on close: Internal server error.'.
Debug: Stopping HubConnection.

**Comment by BrennanConroy** [comment]
You guys are showing two different issues. If you are seeing an unexpected failure with: `'Error: Server returned an error on close: Internal server error.` then please open a separate issue with details about that.

Lets keep this issue to the lack of `OnConnectedAsync` being called even though the connection was connected.

@Arash-Sabet In https://github.com/aspnet/AspNetCore/issues/6448#issuecomment-452740839 you showed the client connected and claim the `OnConnectedAsync` function wasn't called. Could you try to get the same thing to happen and include the client logs starting with "Starting HubConnection."

I know you can't show us your `OnConnectedAsync` but can you confirm that you have a log statement in it and that the server logs **do not** show that log statement when the connection successfully connects.

**Comment by BrennanConroy** [comment]
>We sometimes do not see that logged statement in our log entity and that's why we realized that OnConnectedAsync is not raised consistently.

When you see this and the connection is receiving pings, can you send an invocation from the client?

**Comment by Arash-Sabet** [comment]
@BrennanConroy Let me get back to you on this later on after having some tests executed. Our setup is a bit different and the server is supposed to send objects back to the client.

**Comment by bradygaster** [comment]
cc @chenkennt as we discussed this yesterday and service team wants to peek at it.

**Comment by chenkennt** [comment]
@Arash-Sabet haven't heard from you yet. Please let me know after you send me your resource name to make sure I don't miss your email.

**Comment by Arash-Sabet** [comment]
@chenkennt I did send you the screenshot of the resource last week by email. Please check your mailbox's spam folder just in case. This is the email address that I sent the note to you: kenchen<at>microsoft.com .

**Comment by Arash-Sabet** [comment]
@bradygaster I sent this diagram to @chenkennt in an email too. Please feel free to let me know what your thoughts are about this architecture feasibility. 

![signalr-on-sf](https://user-images.githubusercontent.com/26050123/52440305-b5f62780-2aeb-11e9-8e6c-92f5bf408dcc.JPG)

**Comment by bradygaster** [comment]
cc @davidfowl as i'd like his perspective on this, too. It feels like you'd want to erase the arrows going from the client apps' instances to the Service Fabric services. Since you'd be using ASRS to proxy your communications, why have the direct connections back to the SF services?

**Comment by Arash-Sabet** [comment]
@bradygaster By direct "negotiation" arrows, I was trying to emphasize the initial step of negotiation between the client app and one of the hubs instances within the cluster _(via cluster's exposed endpoint which was missing in the diagram)_.  As you know, it's up to the cluster's LB to route the negotiation request and later on the persistent connection to one of the hubs within the cluster. The persistent communication channel is established using ASRS which proxies the communications between a hub and the client. Hope this new diagram depicts the purpose more accurately. Each separate color set shows a distinctive connectivity.

![signalr-on-sf2](https://user-images.githubusercontent.com/26050123/52451525-60cb0d80-2b0d-11e9-8d18-450dd9a25d26.JPG)

**Comment by Arash-Sabet** [comment]
Not sharing the same Azure SignalR Service instance between two hubs resolved the issue.
