### ISSUE TITLE
Show hosting startup logs in production

### ISSUE THREAD

**Issue by glennc** [aspnet/AspNetCore#6449]
We need to have hosting startup logs be its own category that can be configured to be shown during in production. Now that we put them through the logging system they will not appear in production builds when we set the log level to warning. We want the templates to configure the hosting category to be Information presumably.

**Comment by Tratcher** [comment]
Note this applies to the templates after we move to generic host. https://github.com/aspnet/AspNetCore/pull/5706

We may have to react and edit the generic host's log category.

**Comment by Tratcher** [comment]
@Eilon why are templates lumped under the MVC label?

**Comment by Eilon** [comment]
Because that's where they do 😄

**Comment by Eilon** [comment]
Though if this work will be entirely handled by Hosting folks (e.g. you), we can leave in just area-hosting.

**Comment by Tratcher** [comment]
Current state:

Provider: Microsoft.Extensions.Hosting.Host
Info: "Application started. Press Ctrl+C to shut down."
Info: "Hosting environment: {envName}"
Info: "Content root path: {contentRoot}"

Provider: Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService
 Info: "Now listening on: {address}"

appsettings.json:
```
    "LogLevel": {
      "Default": "Warning"
    }
```
appsettings.Development.json
```
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
```

Proposals: 
Microsoft.Extensions.Hosting.Host -> Microsoft.Extensions.Hosting.Startup
(To be continued...)

**Comment by Tratcher** [comment]
On a related note, [this shutdown message](https://github.com/aspnet/AspNetCore/blob/cc892071b20d350ebdafa63d108d949f547711eb/src/Hosting/Hosting/src/WebHostExtensions.cs#L87) is missing from generic host.

**Comment by Tratcher** [comment]
Preview2 mitigation proposal:
appsettings.json:
```
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.Extensions.Hosting.Host": "Information"
    }
```

This gets you the "Application started." logs so you know the site is working, but not the "Now listening on" logs for the address.
