### ISSUE TITLE
WebApplicationFactoryContentRootAttribute unable to be found (in full .Net Framework)

### ISSUE THREAD

**Issue by CloudStu** [aspnet/AspNetCore#6451]
WebApplicationFactoryContentRootAttribute cannot be used in full .Net Framework applications due to flawed logic in WebApplicationFactory.cs, specifically the GetTestAssemblies method

https://github.com/aspnet/AspNetCore/blob/6699fd056e4bbf491397067e01c191223a20f3b0/src/Mvc/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactory.cs#L216-L219

The code assumes that FriendlyName will contain the test assembly's name like MyTestAssembly.dll, but in my testing it actually contains a 'friendly' string like the following: "TestSourceHost: Enumering Source (c:\path\to\MyTestAssembly.dll)". A cursory search suggests this string is being set by the mstest/vstest code, though I am using xunit to write my tests. Regardless, FriendlyName can not be reliably used to access the test assembly name.

![image](https://user-images.githubusercontent.com/1374626/50788802-b74cee00-12ba-11e9-99fc-abb09db04061.png)

This exception however is immediately caught and silently handled inside the same method with an empty handler, so the only way to determine that the attribute is not being read is through the debugger..
https://github.com/aspnet/AspNetCore/blob/321327f84b2b22dcff2e9beb06a9a64236c5cced/src/Mvc/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactory.cs#L245-L247

This is using 2.1.2 of Microsoft.AspNetCore.Mvc.Testing.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @CloudStu.
@javiercn, isn't this dupe of https://github.com/aspnet/Mvc/issues/8761?

**Comment by CloudStu** [comment]
Apologies for the noise, it does seem a dupe - I missed the issue due to it being in the older repo. I hadn't noticed GetTestAssemblies is virtual, so I'll try overriding it.

That said, I'm not a fan of the default logic, either depending on FriendlyName or on swallowing the exception when the FriendlyName isn't an assembly name, given there seem to be plenty of test runners that set incompatible FriendlyNames (be it JetBrains as mentioned in  aspnet/Mvc#8761, or dotnet cli's vstest command for me). But I guess I can live with it knowing the extensibility point.

Cheers
