### ISSUE TITLE
Blazor onclick event on dynamic li not working for desktop but works for mobile 

### ISSUE THREAD

**Issue by arivera12** [aspnet/AspNetCore#6452]
```
<ul class="list-group">
  @for (int i = 0; i < 5; i++)
   {
   var local_index = i;
   <li   onclick=@(async (e) => await lstItemClick(e, local_index)) class="list-group-item">
    Item @i
    </li>
   }
</ul>

@functions{
//Never gets fired
protected async Task<string> lstItemClick(UIMouseEventArgs eventArgs, int index)
    {
        Console.WriteLine("List clicked at index: " + index);
        return null;
    }
}
```

I tested other events like onmouseover and onmouseout and those events gets fired, I removed them from this sample for simplicity but I could never got the onclick fired.

**Comment by wanton7** [comment]
Bug report should include browsers, browser versions, operating systems and Blazor version you used. Blazor 0.7.0 hopefully? Because it doesn't make sense to run anything older. Are using using Blazor or Razor Components (aka server side Blazor)?

Does your code even work? It looks broken, `async` keyword doesn't work without `await` in the method so it shouldn't even compile and you are also returning null `Task<string>`. So that code can't be actual code you used.

**Comment by arivera12** [comment]
@wanton7 
I am using chrome Version 71.0.3578.98 (Official Build) (64-bit) on windows 7 Ultimate 64x and using blazor 0.7.0. I am using client side blazor and yes my code works it just throws a warning of lack of await inside inside the method but runs fine.

**Comment by wanton7** [comment]
@arivera12 are you sure it's just not `Console.WriteLine()` that is not printing anything? Did you try putting break point in lstItemClick?
If you are running it server side by accident then `Console.WriteLine()` output doesn't go to browsers console output.

Change your code to this

```
<ul class="list-group">
  @for (int i = 0; i < 5; i++)
   {
   var local_index = i;
   <li onclick=@(async (e) => await lstItemClick(e, local_index)) class="list-group-item">
    Item @i
    </li>
   }
</ul>
<div>@selectedIndex</div>

@functions {
    int? selectedIndex = null;

    protected async Task<string> lstItemClick(UIMouseEventArgs eventArgs, int index)
    {
        selectedIndex = index;
        Console.WriteLine("List clicked at index: " + index);
        return null;
    }
}

```

If selected index number changes inside that `div` then your problem isn't with `onclick` event.

**Comment by arivera12** [comment]
@wanton7 I am using blazor client side. I have output stuff to the browser console via the console.writeline on others methods.

**Comment by wanton7** [comment]
@arivera12 Yes tried it with both server and client side Blazor and it works in both. This is with Chrome 71.0.3578.98 (64bit) on Windows 10. Do you have any custom JavaScript running that could be interfering with the click event? How about your package references? They should look like this.
```
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore.Blazor.Browser" Version="0.7.0" />
  <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.7.0" PrivateAssets="all" />
</ItemGroup>
```

**Comment by arivera12** [comment]
@wanton7 I haven't not used a single line of javascript on my project yet. Where I can find this file? I dont see inside the project folder or in the solutions folder as well. I can see the nuget reference and both are on version 0.7.0.
![image](https://user-images.githubusercontent.com/5600102/50854006-507f1180-135a-11e9-8fba-37f0c667507f.png)

**Comment by arivera12** [comment]
@wanton7 I can confirm that this is working. Let me tell you what I am doing. I am doing an autocomplete for blazor using bootstrap and I think that the onmouseout and onmouseover aren't letting the onclick event fire.

```
<li onmouseout=@(async (e) => await lstItemOnMouseOut(e))
                onmouseover=@(async (e) => await lstItemOnMouseOver(e, local_index))
                onclick=@(async (e) => await lstItemClick(e, local_index))
                class="list-group-item @(CurrentItemFocusIndex == i ? "active" : string.Empty)">
                @(IsApiStringArray ?
                            FilteredData[local_index] :
                            (FilteredData[local_index] as Dictionary<string, object>)[DisplayTextPropertyName]?.ToString()
                )
            </li>
```

This is how my li tag looks rigth now.

**Comment by Andrzej-W** [comment]
Could you change return type of your last 3 functions from `Task<string>` to `Task` and remove `return null;` (make them similar to `onBlur` and `onFocus` above).

**Comment by Andrzej-W** [comment]
Often you are not using `eventArgs`. Remove it and call your synchronous function like this:
`onclick=@(() => await lstItemClick(local_index))`
This is not a bug but a small suggestion to cleanup your code.

**Comment by wanton7** [comment]
@arivera12 It's not `onmouseover` or `onmouseout` because this works just fine

```
<div class="form-group">
    <ul class="list-group">
        @for (int i = 0; i < 5; i++)
        {
            var local_index = i;
            <li onmouseout=@(() => ListItemOnMouseOut(local_index))
                onmouseover=@(() => ListItemOnMouseOver(local_index))
                onclick=@(() =>  ListItemClick(local_index))>
                Item @i
            </li>
        }
    </ul>
</div>
@functions{
    void ListItemClick(int index)
    {
        Console.WriteLine("click: " + index);
    }

    void ListItemOnMouseOver(int index)
    {
        Console.WriteLine("mouse over: " + index);
    }

    void ListItemOnMouseOut(int index)
    {
        Console.WriteLine("mouse out: " + index);
    }
}
```

I read your code and I'm pretty sure somethings wrong with way you are using `onfocus` and `onblur` to hide the list that needs to be clicked. Because when you click the list and if you had focus on `input` before, then it's `onblur` will get triggered. Probably before click event happens. I would try removing `onfocus` and `onblur` event handlers and set `ShowList` always to `true` and see if it works then.

**Comment by arivera12** [comment]
@wanton7 I just wanna said that I :heart: u. The onfocus and onblur was the error. @Andrzej-W I will clean the code  with your suggestions I really didn't needed to make Task<async> on all methods I just did copy and paste everywhere to make this work and its already working. Thanks to both of u!
