### ISSUE TITLE
500 error using LibMan

### ISSUE THREAD

**Issue by JeffMushmo** [aspnet/AspNetCore#6463]
When my page requests any scripts brought in from libman, I get a 500 error response, with no other information.

This is an Asp.Net Core app running in Service Fabric.

### To Reproduce
1. Using ASP.NET Core 2.1.1 & Service Fabric 3.3.624.
2. Enable libman and add jquery and/or bootstrap to the libman.js file.
3. Reference any of the files from a web page.
4. 500 error is returned.

### Expected behavior
I would expect that I get the file back being requested, with a 200 response.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
