### ISSUE TITLE
Blazor debug server cannot get assemblies because their names are lower-cased with current culture.

### ISSUE THREAD

**Issue by ud09** [aspnet/AspNetCore#6474]
When I try start debugging a blazor app in chrome  on windows with culture tr-TR, I get the following 404 error:
![blazor-debug](https://user-images.githubusercontent.com/6473521/50812672-b18bf280-1324-11e9-9589-c855e8dfb6c9.jpg)
Capital I is different when lower-cased in Turkish. Trying to get _microsoft.extensions.dependencyınjection.dll_ 
DebugStore ctor calls ToLower here :
```c#
foreach (var f in loaded_files) {
	var file_name = f.ToLower ();
	if (file_name.EndsWith (".pdb", StringComparison.Ordinal))
		pdb_files.Add (file_name);
	else
		asm_files.Add (file_name);
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ud09.
@SteveSandersonMS is this something we should fix, or should this go to the Mono team?

**Comment by SteveSandersonMS** [comment]
Ah yes, that does look like a bug in the Mono debugging proxy (the original source line is at https://github.com/mono/mono/blob/df46658fd1674213e3370513b13e83575f02e841/sdks/wasm/Mono.WebAssembly.DebuggerProxy/DebugStore.cs#L390).

@ud09 Thanks for tracking down the underlying cause. Would you be willing to post the bug report to https://github.com/mono/mono? Thanks!

I'll close this as external.
