### ISSUE TITLE
Permanent redirect (301) is not supported in the PrerenderTagHelper

### ISSUE THREAD

**Issue by basschuitema** [aspnet/AspNetCore#6477]
I was trying to do a 301 redirect from our JavaScript application using SpaServices prerendering. While I was trying to set the RedirectUrl with StatusCode 301 in our JavaScript server-renderer, a 302 redirect was still happening. 

### Investigation
I started looking into the source and I found out that the PrerenderTagHelper is only using the StatusCode from the result if it's not a redirect. If a RedirectUrl was set, the redirect is always a 302 redirect.

### Solution
The solution seems to add a check to the **PrerenderTagHelper** that checks if the result contains a 301 StatusCode, in that case do a permanent redirect. This is also how it's already being done for example in **SpaPrerenderingExtensions**.

So instead of this:
`
if (!string.IsNullOrEmpty(result.RedirectUrl))
{
ViewContext.HttpContext.Response.Redirect(result.RedirectUrl);
return;
}`

It has to be like this:
`if (!string.IsNullOrEmpty(result.RedirectUrl))
{
var permanentRedirect = result?.StatusCode == 301;
ViewContext.HttpContext.Response.Redirect(result.RedirectUrl, permanentRedirect);
return;
}`

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up, @basschuitema.
One of our team members will look into the PR.
