### ISSUE TITLE
Multilingual site

### ISSUE THREAD

**Issue by alirezaseif28** [aspnet/AspNetCore#6481]
hello .
What is the best way to use the resource in Javascript?
thanks.

**Comment by Eilon** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` tag.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @alirezaseif28.
We're closing this issue as there is no action involved from our side regarding it. You can read more about the localization and globalization in ASP.NET Core here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2
To learn about localization in Javascript, you'll need to consult other external resources.

**Comment by alirezaseif28** [comment]
thanks
