### ISSUE TITLE
Folder(s) not created for path to the ANCM debug log

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore#6484]
The ANCM isn't capable of creating a path for the debug log the way that it's able to create the path for the stdout log.

In terms of docs, I'd like to modify our topic to prompt devs to use the same `logs` folder ...

```xml
<handlerSetting ... value=".\logs\aspnetcore-debug.log" />
```

For the stdout log, this request was made on https://github.com/aspnet/AspNetCoreModule/issues/30 and was solved on an unlinked PR for that issue.

Is there interest in offering the same capability for the ANCM debug log?

Cross-references:

* [Folder publish should publish empty folders (aspnet/websdk 273)](https://github.com/aspnet/websdk/issues/273)
* [Logs are not created if the log folder does not exist (aspnet/AspNetCoreModule 30)](https://github.com/aspnet/AspNetCoreModule/issues/30)

For reference, I'll reiterate the entry required to (a) create the folder, and (b) add a dummy file to it in order to force the folder to deploy via WebDeploy 🙈 ...

```xml
<Target Name="CreateLogsFolder" AfterTargets="Publish">
    <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
    <WriteLinesToFile File="$(PublishDir)Logs\.log" Lines="Generated file" Overwrite="True" Condition="!Exists('$(PublishDir)Logs\.log')" />
</Target>
```

**Comment by muratg** [comment]
@guardrex that bug seems over a year old and I've forgotten the context on it :) Would you mind filing a new one (in https://github.com/aspnet/AspNetCore) describing the issue if you think there's something we should fix? Thanks!

**Comment by muratg** [comment]
@guardrex Sounds good, thanks!
