### ISSUE TITLE
Razor Components - SASS/LESS

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#6494]
**Razor Components within RazorViews/RazorPages SASS & LESS**
Using Razor Components from within RazorView/RazorPages you may need to compile the SASS/LESS using parameters/attributes for the client browser and/or the view/page that the component is hosted within, at present this would require ahead-of-time compilation of the SASS/LESS for all variances.

### Describe the solution you'd like
IMHO it would be good to support the server-side compilation of SASS/LESS templates for the Razor Components based on the browser/client/view/page attributes/parameters/state supplied to the server via SignalR circuit and returned to the client in a similar manor to the DOM delta.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @grahamehorner.
Runtime compilation of SASS / LESS files is not something we plan to invest in in the near future.
