### ISSUE TITLE
Is it avoidable that IIS in-process mode locks its own DLL files?

### ISSUE THREAD

**Issue by UweKeim** [aspnet/AspNetCore#6496]
In an ASP.NET Core 2.2 pure Web API project on a Windows Server 2016 with in-process IIS I experienced the following behaviour:

When updating the assemblies of my Web API website, the files are locked (renaming succeeds, deleting failes), so that I'm unable to directly replace the assemblies.

Now when I rename them and then replace them, the new assemblies are not recognized by IIS until I IISRESET the server.

**My question:**

- Am I doing something completely wrong?

- If not, is there an option to make IIS in-process ASP.NET Core projects work like previous ASP.NET MVC projects, where the project files/assemblies can be replaced during running the web application and are instantly recognized without the need for IIS RESET?

**Comment by jkotalik** [comment]
See app_offline.htm: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#locked-deployment-files

**Comment by UweKeim** [comment]
Awesome, thanks a lot!

Good old App_Offline.htm to the rescue 👍
