### ISSUE TITLE
Adding a component via solution explorer adds junk to the project file.

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6500]
Using VS 16.0 preview 2 and the newest SDK.

We're planning on using an MSBuild snippet like:
```
<ItemGroup>
  <RazorComponent Include="Components\**\*.cshtml" />
</ItemGroup>
```

So we can tell the difference between components and views.  

When you add a razor file through the *new item* dialog, it will be added to a bunch of item groups, causing it to act as a view instead of a component. We don't want any of these things to happen.

**Comment by rynowak** [comment]
We plan to change what the recommended gesture is for distinguishing a component from a view to something like:
```
<PropertyGroup>
  <RazorComponentInclude>Components\**\*.cshtml</RazorComponentInclude>
</PropertyGroup>
```

OR
```
<ItemGroup>
  <Content Update="Components\**\*.cshtml">
    <FileKind>Component</FileKind>
  </Content>
</ItemGroup>
``

These changes are in the SDK and don't directly effect the bits we insert into VS.

**Comment by pranavkm** [comment]
Fixed via https://github.com/aspnet/AspNetCore-Tooling/pull/120, https://github.com/aspnet/AspNetCore/commit/82941f9d0f8d17ab3fd7709ba7728b479a70986d

**Comment by andoband** [comment]
I see it is implemented as `<_RazorComponentInclude>` instead of `<RazorComponentInclude>`.  Just curious, why does the tag name start with an underscore?

https://github.com/aspnet/AspNetCore-Tooling/blob/9dd00ac82f474436412497082a7b8b1afa6150de/src/Razor/test/testapps/MvcWithComponents/MvcWithComponents.csproj#L6

**Comment by pranavkm** [comment]
@andoband we plan on removing the flag before the 3.0 release. It was intentionally named as a private variable so that it does not have semblance to a real long-term supported setting.
