### ISSUE TITLE
On Ubuntu Request.Scheme Returns http and Request.IsHttps Returns False When Connection is Secure

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/AspNetCore#6502]
In ASP .NET Core 2.2 you are supposed to be able to check whether the connection is secure or not by using:
```Request.Scheme``` (returns ```https``` or ```http```)

Or
```Request.IsHttps``` (returns either ```true``` or ```false```)

This is working fine on Windows servers but on my Ubuntu server running on Apache it is returning ```http``` and ```false``` even though the connection is showing as secure in the browser and accessed over https.

Is this a bug or is it the way I have Apache2 configured?

I need to output the current website address and am using the following:
```
httpContextAccessor.HttpContext.Request.Scheme + "://" + httpContextAccessor.HttpContext.Request.Host.Value;
```

However due to the issue above it is returning ```http://website``` rather than ```https://website```.

I would rather not hard code this in if possible.

I have already tried the configuration changes here to forward headers but it made no difference:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by jeffputz** [comment]
This is a for real problem still in the v2.2. To repro, output Request.Scheme in any secure page hosted on a Linux-based Azure App Service.

**Comment by Tratcher** [comment]
@jeffputz see https://github.com/aspnet/AspNetCore/issues/4135#issuecomment-493592243

**Comment by Tratcher** [comment]
And https://devblogs.microsoft.com/aspnet/forwarded-headers-middleware-updates-in-net-core-3-0-preview-6/

**Comment by jeffputz** [comment]
@Tratcher Good spot... I figured that was the general necessary direction, but my Google-foo failed me. Thanks!
