### ISSUE TITLE
Warnings from aspnetcore Middleware.sln

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#6505]
Building Middleware.sln produces warnings from the TestServer project. It looks like various test related references are being added to the project incorrectly, e.g. the project doesn't need Moq and xunit. The actual warnings are happening because TestServer.csproj is not an SDK project and probably can't handle the type of references.

Fix TestServer project so test references are not added
Update TestServer to use SDK project format?

**Comment by Pilchie** [comment]
Is this still an issue?  @mkArtakMSFT can you take a look?

**Comment by mkArtakMSFT** [comment]
@BrennanConroy, @halter73 who is best positioned to look into this?

**Comment by halter73** [comment]
Assuming there's no rush, @Tratcher is generally the best person for looking into TestServer-related issues.

**Comment by Pilchie** [comment]
I don't think there is a big rush, considering this was filed back in Jan.  It might not even repro anymore.

**Comment by Tratcher** [comment]
Moving out of 3.0 as this is not blocking anything.

**Comment by Tratcher** [comment]
Note this is regarding a WebSocket manual test asset WebSockets.TestServer, not Hosting's TestServer. https://github.com/aspnet/AspNetCore/blob/1f6d235a5e7fd9427c96b7508610c5d3401a1571/src/Middleware/WebSockets/samples/TestServer/WebSockets.TestServer.csproj
