### ISSUE TITLE
IUserStore doesn't respect to custom type with custom data provider

### ISSUE THREAD

**Issue by dehghani-mehdi** [aspnet/AspNetCore#6513]
Hello,

### Describe the bug
I tired to use Dapper with Identity, everything works, but I faced an issue. `IUserStore` and `IRoleStore` doesn't respect to provided primary key data type (_I like to use int as primary keys's data type_), here is what I did:

```
public class ApplicationUser : IdentityUser<int>
{
}

public class ApplicationRole : IdentityRole<int>
{
}

public class CustomUserStore :
    IUserStore<ApplicationUser>,
    ...
```

There error is:
> 'CustomUserStore' does not implement interface member 'IUserStore<ApplicationUser>.FindByIdAsync(string, CancellationToken)'

_Same for CustomRoleStore_

For now I add `FindByIdAsync(string, CancellationToken)` and inside the method I convert data types, but I think this 2 interfaces should respect to the provided data type. I googled, but I could not find any solution.

### To Reproduce
1. Create new ASP.NET Core web project (v2.2.x)
2. Try to use Dapper instead of EF for identity
3. With custom data type as UserId and RoleId
4. Error already mentioned.

### Expected behavior
`IUserStore` and `IRoleStore` should respect to the provided data type some how.

### Screenshots
-

### Additional context
VS 2017 v15.9.3
.NET Core v2.2.101

Thanks.

**Comment by blowdart** [comment]
string is a deliberate decision as the type of pass around. Once you start implementing stuff yourself you have to do the conversions. But we have an AbstractStore, [UserStoreBase](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Stores/src/UserStoreBase.cs) which does a lot of this for you, so rather than go down to the interface, use the base class instead, or copy the bits from there if you're adverse to our POCOs.

**Comment by dehghani-mehdi** [comment]
@blowdart Thanks for the point, obviously I didn't look at hole project (_Identity I mean_) and I'm not pro as you are, as far as I know it can be happened but maybe I'm wrong, so you saying, it won't be supported by Identity?

**Comment by dehghani-mehdi** [comment]
@blowdart I tried `UserStoreBase`, the `string userId` still there, so it does't help in this issue.

**Comment by blowdart** [comment]
@HaoK can you give some guidance here?

**Comment by HaoK** [comment]
This is by design, you can persist the primary key as whatever you want, but the manager apis always use string for the ids, so your stores need to implement FindById which does a lookup via string id

**Comment by dehghani-mehdi** [comment]
@HaoK by design! you should re-design then, when you accept custom type, all parts should respect that type. I just see hard-coded type there without any acceptable reason, but your are the boss.
