### ISSUE TITLE
Blazor - Wait with loading after preload animation is done playing

### ISSUE THREAD

**Issue by Duxez** [aspnet/AspNetCore#6521]
Is there a way to delay the loading of the first page until after a preload animation is done? I want to replace the boring "loading..." with something more neat to look at but can't find a way to force the animation to be done first.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Duxez.
@SteveSandersonMS, is there an API being called before the "loading" content is about to be replaced by actual content?

**Comment by SteveSandersonMS** [comment]
> can't find a way to force the animation to be done first.

There are various ways you could do that. A simple one would be putting your "loading" animation in a full-width-and-height opaque overlay that appears in front of any Blazor-rendered UI, then you can use JS interop to make it disappear any time you want after your app has started running.

> is there an API being called before the "loading" content is about to be replaced by actual content?

Yes, the `Configure` method in `Startup.cs` is called immediately before the first render.
