### ISSUE TITLE
Specify custom probing folder for loading assemblies

### ISSUE THREAD

**Issue by disklosr** [aspnet/AspNetCore#6523]
### Is your feature request related to a problem? Please describe.
Not really a problem.

### Describe the solution you'd like
I'd like my dependencies to be loaded from a custom folder instead of the app root folder. The goal is to make the generated package clean and well organized.

### Describe alternatives you've considered
The old way of doing this in .Net is to configure the runtime with a path using the `<probing/>` xml tag in `Webconfig`. In dotnet core there doesn't seem to be an equivalent to specify custom probing folders for loading assemblies, which is what I'm trying to achieve.

**Comment by Eilon** [comment]
@disklosr can you provide more info about what you're doing and what exactly you're expecting? Also, is this specific to ASP.NET Core or is it a general NuGet or .NET issue you're having?

**Comment by disklosr** [comment]
I'm working on an asp.net core app and I generate the package to deploy using dotnet package.
This command generates a folder with all the binaries, dependencies and config files in the same folder which can quickly get get pretty messy.

Ideally, I would like to have my dependencies inside a "bin" folder instead of them being in the root folder of my app. Manually moving my dependencies in a "bin" folder will result in the runtime not being able to run my app because it expects my dependencies to be in the app root.

How can I instruct the runtime to look for binaries inside a specific folder, let's say "bin" folder in my case, instead of only checking the root?

Hope this it's more clear now.

**Comment by Eilon** [comment]
Ah OK this seems much broader than just ASP.NET Core, so I recommend filing an issue at https://github.com/dotnet/core/issues to get the attention of the folks who are experts on this topic.

**Comment by disklosr** [comment]
Sure i'll close this then. Thank you.
