### ISSUE TITLE
React to SIGTERM exit code change

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#6526]
https://github.com/dotnet/coreclr/pull/21300#issuecomment-452684375

CoreClr is changing the default behavior for SIGTERM exit codes from zero to non-zero. WebHost and GenericHost both block the ProcessExit event while attempting to shut down.

Proposal:
If the host does shut down gracefully then set the exit code to zero.

**Comment by tmds** [comment]
This change is in coreclr for 3.0. So maybe this should be 3.0 milestone?

**Comment by Tratcher** [comment]
Note for generic host: We're going to have to port some of the Microsoft.AspNetCore.Server.IntegrationTesting infrastructure to Extensions to enable proper functional tests.
