### ISSUE TITLE
Inject Logger In RequestLocalizationMiddleware

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/AspNetCore#6532]
In `RequestLocalizationMiddleware` there's a `EnsureLogger` method which check if the logger variable is null and then get `ILogger<RequestLocalizationMiddleware>` from `HttpContext.RequestServices`.

https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/Localization/src/RequestLocalizationMiddleware.cs#L139

Can we just inject `ILogger<RequestLocalizationMiddleware>` or `ILoggerFactory` in the constructor instead?

**Comment by hishamco** [comment]
AFAIK this will not work, have a try .. probably you will get **Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware**

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/AspNetCore/commit/ba8c6ccf6fd3eeb7fc42a159d362b15eae4fb3a0
