### ISSUE TITLE
[Announcement]: Removed deprecated Authentication property from HttpContext (including all of 1.x auth stack)

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#6533]
This is the discussion item for https://github.com/aspnet/Announcements/issues/337

As part of aspnet/AspNetCore#6504 we've removed the deprecated Authentication property. The Authentication property has been deprecated since 2.0 and a migration guide was published to migrate code using this deprecated property to the new replacement APIs.

**Comment by HaoK** [comment]
We have also removed all of the old 1.x authentication classes and namespaces as well:

Microsoft.AspNetCore.Http.Authentication and most of Microsoft.AspNetCore.Http.Features.Authentication

**Comment by HaoK** [comment]
The `UseIdentity`/`UseGoogle`/`UseFacebook`/`UseTwitter`/etc obsolete 1.x methods have all been removed as well in https://github.com/aspnet/AspNetCore/pull/6965

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
