### ISSUE TITLE
[Announcement] : Removed DefaultHttpContext extensibility

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#6534]
Discussion for https://github.com/aspnet/Announcements/issues/338

As part of performance improvements made to ASP.NET Core 3.0 (aspnet/AspNetCore#6504), we've removed the extensibility of DefaultHttpContext (it is now sealed). This extensibility was provided initially to allow pooling of the HttpContext but it introduced more complexity than necessary and precluded other optimizations. As a result, we decided to remove this extensibility.

If you're using Mock<DefaultHttpContext> in your unit tests, we recommend using Mock<HttpContext> instead.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
