### ISSUE TITLE
Typos/copy-paste in comments

### ISSUE THREAD

**Issue by sungam3r** [aspnet/AspNetCore#6537]
https://github.com/aspnet/AspNetCore/blob/5541a7a02621a3f716b21741a97d3292739fbe43/src/Http/Http.Features/src/IRequestBodyPipeFeature.cs#L14

Should be `PipeReader ` 

https://github.com/aspnet/AspNetCore/blob/5541a7a02621a3f716b21741a97d3292739fbe43/src/Http/Http/src/StreamPipeWriter.cs#L68

There is `_writingStream`, not reading.

**Comment by jkotalik** [comment]
Good catch.

**Comment by muratg** [comment]
@jkotalik please close once the PR is in. Thanks.

**Comment by jkotalik** [comment]
This was done by #6583
