### ISSUE TITLE
Port fix for #4591 to 2.2.2

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6544]
We should patch #4591 for 2.2.2. This is a basic functional bug that can be an adoption blocker for users to use endpoint routing. In the issue, the user is using route constraints to implement multi-tenancy. It's somewhat common for applications to use route constraints to implement features like filtering by the request hostname. If these features can't be implemented in the same way on endpoint routing then the user can't easily adopt it and has to fall back to 2.1 features.

The bug here is that route constraints for a conventional route that don't match a route parameter get ignored by the routing infrastructure.

Ex:
```
routes.MapRoute("default", "{controller=Home}/{action=Index}/{id?}", constraints: new { domain = new DomainMatchingConstraint("example.com"), });
```

The developer expects `DomainMatchingConstraint` to be called when a request matches the route, but in this case that will not happen.

The original fix for this issue is [here](https://github.com/aspnet/AspNetCore/pull/6045) but this is built on top of some other changes that were make in 3.0. The actual fix for this in 2.2.2 will be slightly more involved.

**Comment by JamesNK** [comment]
The PR you linked to is for the `IRouteConstraint` null HttpContext issue in link generation.

The fix for this issue was fixed when routing and the MvcEndpointDataSource was refactored to support the concept of required values. A different fix will be required for 2.2.2

**Comment by rynowak** [comment]
I thought that the PR I linked contains all of the tests we want to add though? Is there another PR where we added tests for the original issue?

**Comment by JamesNK** [comment]
That was just for null HttpContext. I was bad and didn't write tests when I discovered it wasn't an issue in 3.0. Here are some tests I just wrote for 3.0. They can be used to verify on 2.2 - https://github.com/aspnet/AspNetCore/commit/8a30375233905da507af68dbb5f1ccb4ce9cae45

**Comment by JamesNK** [comment]
Patch merged
