### ISSUE TITLE
Make Razor tooling acquire workspace from projection buffer.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#6548]
In order to open source Razor LiveShare we need to change how Razor acquires its Roslyn workspace. Today in Visual Studio there's a global singleton workspace type that's typically used when Razor needs a workspace, in the case of LiveShare we currently depend on internal APIs to extract a LiveShare specific workspace and use that in LiveShare guest scenarios. 

To properly open source LiveShare we need to change our method in acquiring a workspace by lazily instantiating a documents Razor world until a C# project ion buffer has been created and assigned a workspace. To do this we need to make our document parsing system capable of parsing a document without and Roslyn based services because it's possible we don't have a Workspace yet.

**Comment by rynowak** [comment]
Or they can add an API and we can all go home.

**Comment by NTaylorMullen** [comment]
> Or they can add an API and we can all go home.

Yup, that's an option too.

**Comment by NTaylorMullen** [comment]
Went another way with this.
