### ISSUE TITLE
Cannot add UserRole if it has ID field as a PK

### ISSUE THREAD

**Issue by RoboBurned** [aspnet/AspNetCore#6561]
### Describe the bug
Error is raised when adding Role to User if custom UserRole class has PK other than (UserId, RoleId) pair.

### To Reproduce
1. Create custom UserEntity, RoleEntity, UserRoleEntity, ExternalAccountEntity classes
```
    public class UserRoleEntity : IdentityUserRole<long>
    {
	public long Id { get; set; }

	public UserEntity User { get; set; }
	public RoleEntity Role { get; set; }

	public UserRoleEntity()
	{
	}
    }
    public class RoleEntity : IdentityRole<long>, IEntityBase
    {
	public RoleEntity()
	{
	}
    }
```
2. Configure UserRoleEntity model
```
builder.HasKey(m => m.Id);
builder.HasAlternateKey(m => new { m.UserId, m.RoleId });
```
Note that we have a PK (Id field) and an alternative key (UserId, RoleId).
3. Configure Identity in Startup.cs specifying custom classes.
```
services.AddIdentity<UserEntity, RoleEntity>()
	.AddDefaultTokenProviders();
services.TryAddScoped<IUserStore<UserEntity>, UserStore<UserEntity, RoleEntity, DbContext, long, IdentityUserClaim<long>, UserRoleEntity, ExternalAccountEntity, IdentityUserToken<long>, IdentityRoleClaim<long>>>();
services.TryAddScoped<IRoleStore<RoleEntity>, RoleStore<RoleEntity, DbContext, long>>();
```
4. Create a new user and then run this code
```
await _userManager.AddToRoleAsync(user, "Administrator");
```
5. See error
```
An unhandled exception has occurred while executing the request.
System.ArgumentException: Entity type 'UserRoleEntity' is defined with a single key property, but 2 values were passed to the 'DbSet.Find' method.
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindUserRoleAsync(TKey userId, TKey roleId, CancellationToken cancellationToken)
```
The error happens because UserStore.FindUserRoleAsync calls UserRoles.FindAsync that allows to find role by Primary Key only. In our case primary key is Id but not the pair UserId-RoleId
### Expected behavior
The approach used in UserStore.FindUserAsync should be used instead.
```
return UserRoles.SingleOrDefaultAsync(ur => ur.UserId.Equals(userId) && ur.RoleId.Equals(roleId))
```
This will allow to find user role by alternative key.
### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

**Comment by Andrey-Pavlov** [comment]
@HaoK

**Comment by blowdart** [comment]
If you want to change the primary key you need to also change the store implementation, because our implementation can't react to primary key changes.

**Comment by Andrey-Pavlov** [comment]
> If you want to change the primary key you need to also change the store implementation, because our implementation can't react to primary key changes.

Can we expect changes to the store implementation related to the issue?

**Comment by RoboBurned** [comment]
@blowdart I see no issues with approach I suggested. It will make FindUserRoleAsync work consistently with FindUserAsync. Can you please explain?

**Comment by blowdart** [comment]
No you won't see changes. Our stores are optimized for our models, changing a primary key like this requires code changes in the store, so it's up to you to make those changes.

As for your change Robo it slows search apparently.
