### ISSUE TITLE
How to keep the status user in somewhere when he/she is online by asp.net core signalR?

### ISSUE THREAD

**Issue by farhadibehnam** [aspnet/AspNetCore#6564]
I'm working on a chat project. When a user wants to log in and be online every time I fetch database and get all of the users and of course, I sign that user is online by connectionId. in fact, that user has a connectionId display in a view. As an online user and other users don't have a connectionId will display in view as an offline User.but my problem is when a user wants to be online I add a connectionId to the user and if another user wants to be online. A previous user is offline. My idea I keep every online user in a database, and if a user wants to leave the chat, I sign that user in a database as an offline user and vice-versa.  What do you think about that? Is it wrong or lousy idea keeping the status of a user in a database?

![status](https://user-images.githubusercontent.com/15254482/50969319-4fcdb300-14f3-11e9-850d-731473470132.PNG)

```
 public override async Task OnConnectedAsync()
        {
            List<UsersViewModel> usersList = new List<UsersViewModel>();
            var claimIdenity = Context.User.Identity as ClaimsIdentity;
            var userId = claimIdenity.Claims.FirstOrDefault
                (x => x.Type == ClaimTypes.NameIdentifier).Value;


            var users = await _dbContext.Users.ToListAsync();
            foreach (var user in users)
            {
                usersList.Add(new UsersViewModel
                {
                    UserId = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    PersonPicture = "https://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg",

                });
            }


            UsersViewModel loginedUser = usersList.Where(u => u.UserId == userId).FirstOrDefault();
            if (loginedUser != null)
            {
                loginedUser.ConnectionId = Context.ConnectionId;
            }
            string jsonUsers = JsonConvert.SerializeObject(usersList);
            await Clients.All.SendAsync("GetAllUsers", jsonUsers);
            await base.OnConnectedAsync();
        }

```

**Comment by BrennanConroy** [comment]
That's perfectly fine and a very common method people use for this kind of thing.
