### ISSUE TITLE
Can't connect from React Native

### ISSUE THREAD

**Issue by siberianguy** [aspnet/AspNetCore#6565]
I'm using in React Native the same code that works perfectly fine from a web js client but get an error: `Failed to start the transport 'WebSockets': null`. So it seems like SignalR doesn't find any transports (I did not specify any transport explicitly). I've looked through other issues and I've got an impression SignalR is supposed to be working from React Native at this point. Is it the case?

**Comment by bradygaster** [comment]
Are you trying to connect to a Hub running on the server in ASP.NET Core or are you trying to connect to the Azure SignalR Service? If it's the former, are you running your Hub(s) in Azure App Service? 

Thanks!

**Comment by siberianguy** [comment]
Just normal ASP.NET Core Web Api hosted in IIS

**Comment by bradygaster** [comment]
Do you have WebSockets installed on your IIS Server? That doesn't come pre-installed AFAIK and you need to add it as an optional component.

**Comment by mikaelm12** [comment]
Can you get some logs for us? https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide

**Comment by FiveStar0909** [comment]
![screenshot_109](https://user-images.githubusercontent.com/41168694/51329987-775cd800-1a2b-11e9-95ff-19427bef598a.png)

This is screenshot what i faced.

**Comment by mikaelm12** [comment]
This doesn't really give much more information. More detailed logging would be helpful

**Comment by FiveStar0909** [comment]
import { HubConnectionBuilder,HubConnection  } from '@aspnet/signalr'
...
initiateConnection = () => {
    connection = new HubConnectionBuilder()
      .withUrl(config.baseHubURL)
      .build();

      connection.on("update", (message) => {
      this.update(message);
    });
}
The issue that failed to start the transport is happening in new  HubConnectionBuilder().withURl().build().

**Comment by FiveStar0909** [comment]
@mikaelm12  what exactly do you need?

**Comment by mikaelm12** [comment]
> Can you get some logs for us? https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide

**Comment by FiveStar0909** [comment]
![screenshot_123](https://user-images.githubusercontent.com/41168694/51783688-76ded400-20f2-11e9-88a6-588338d9c35a.png)

These logs will help you

**Comment by FiveStar0909** [comment]
any update?

**Comment by anurse** [comment]
"Failed to start the transport 'WebSocket': null" is unfortunately unhelpful (which is our fault). We'll take a look at getting the proper error message out of this.

SignalR does appear to be correctly falling back to Server-Sent Events. Is your app not working properly? The error message indicates we failed to start the WebSocket, but that's a recoverable error, and SignalR should continue to function properly.

**Comment by anurse** [comment]
Triage decision: Let's get the error message cleaned up at least.

**Comment by anurse** [comment]
Logging improved in #12026. Getting a network trace (described in our [Diagnostics guide](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2)) would help us identify the specific issue here since browsers (and React Native) are notoriously bad at giving specific error messages for these issues.

If anyone is still hitting this issue, feel free to open a new issue with a network trace!

**Comment by tr3v3r** [comment]
Have you tried another transport?

```
     const connection = new signalR.HubConnectionBuilder()
          .withUrl(url, {
            transport:
              signalR.HttpTransportType.WebSockets |
              signalR.HttpTransportType.LongPolling,
          })
          .configureLogging(signalR.LogLevel.Debug)
          .build()
```
