### ISSUE TITLE
Improve HTTP/2 allocations per request

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#6567]
Here's a snapshot of the per request allocations for HTTP/2 requests. I was using https://github.com/codesenberg/bombardier to generate load using 125 connections (1 stream per connection).

Here's 100,000 request for HTTP/1 and HTTP/2 with the same application:

HTTP/1: 24MB

![image](https://user-images.githubusercontent.com/95136/50979352-225d1700-14ab-11e9-8fda-66b5f849e1f0.png)

HTTP/2: 650MB

![image](https://user-images.githubusercontent.com/95136/50979606-af07d500-14ab-11e9-9ab1-690bac7b83fb.png)

**Comment by davidfowl** [comment]
I'll do this in preview4

**Comment by muratg** [comment]
Triage: closing this.
