### ISSUE TITLE
Identity Default UI Manage page can potentially lead to user lock outs

### ISSUE THREAD

**Issue by chrisdpratt** [aspnet/AspNetCore#6568]
The default Identity UI has a bug with both changing email and phone number in the [Manage/Index](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Manage/Index.cshtml.cs) page. For example, if the user enters an email in the form field, `SetEmailAsync` is naively called which marks the user's email as unconfirmed.

    var email = await _userManager.GetEmailAsync(user);
    if (Input.Email != email)
    {
        var setEmailResult = await _userManager.SetEmailAsync(user, Input.Email);
        if (!setEmailResult.Succeeded)
        {
            var userId = await _userManager.GetUserIdAsync(user);
            throw new InvalidOperationException($"Unexpected error occurred setting email for user with ID '{userId}'.");
        }

        // In our UI email and user name are one and the same, so when we update the email
        // we need to update the user name.
        var setUserNameResult = await _userManager.SetUserNameAsync(user, Input.Email);
        if (!setUserNameResult.Succeeded)
        {
            var userId = await _userManager.GetUserIdAsync(user);
            throw new InvalidOperationException($"Unexpected error occurred setting name for user with ID '{userId}'.");
        }
    }

If the user now logs out on a site that requires a confirmed email, they will not be able to log in again. To add insult to injury, a confirmation email is not sent automatically, but instead requires the user clicking a link after being returned to the page from the post. If the user neglects to do so, then once they're logged out, they're now locked out. Sending the confirmation email immediately without user intervention would be better as now they have a chance to recover. However, even that only works if the email is good. If the user made a mistake and entered an erroneous email address, they are now completely locked out without hope of ever being able to recover without intervention from the site owner.

Long and short, this code needs to be changed to accomodate using `ChangeEmailAsync` instead. A confirmation email needs to be sent on post, instead of immediately setting the new email address, and then a confirm email change page needs to be  added to actually handle the change.

This likewise applies to the setting of a new phone number, which follows the same broken logic as setting an email address.

    var phoneNumber = await _userManager.GetPhoneNumberAsync(user);
    if (Input.PhoneNumber != phoneNumber)
    {
        var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, Input.PhoneNumber);
        if (!setPhoneResult.Succeeded)
        {
            var userId = await _userManager.GetUserIdAsync(user);
            throw new InvalidOperationException($"Unexpected error occurred setting phone number for user with ID '{userId}'.");
        }
    }

**Comment by blowdart** [comment]
@HaoK remember the improve the email address also equals username work we wanted to do, well, this probably needs addressing at the same time. Schema changes probably needed.

**Comment by chrisdpratt** [comment]
I did a simple implementation for the email change in a fork. This is probably not production-ready code to say the least. In particular, I don't like the email being passed in the confirmation link, but o was attempting to get it done with a minimal amount of change. It would be great if there was a column in the user table to persist the new email instead. Also, please note that my branch is based on release/2.2; I couldn't get master to build.

**Comment by HaoK** [comment]
Yeah I filed https://github.com/aspnet/AspNetCore/issues/6613 to track the all up support for making username as email just work.  We aren't sure exactly what the default UI will look like in 3.0 since its probably a good candidate for switching to razor components, so we will likely revisit the flows then.

**Comment by blowdart** [comment]
Will be fixed in #8356
