### ISSUE TITLE
Select an action by the content of the body (JSON Property)?

### ISSUE THREAD

**Issue by tthiery** [aspnet/AspNetCore#6571]
### Is your feature request related to a problem? Please describe.
In a REST interface I want to utilize a generic end point uri (e.g. `/items/12345/actions`) to be routed to multiple Mvc/Web Api controller actions depending on a JSON property of the content of an uploaded document.

The request would look like ...
````
POST /items/12345/actions

{
   "type": "ActionA",
   "abc": "xyz"
}
````

How do I select a controller action by a part of the JSON body of the request?

### Describe the solution you'd like

Parse selected contents of a JSON request (during routing or other additional middleware) into e.g. RouteData and allow to specify constraints during for controller action selection

See possible example in the controller (with a simplified attribute naming)

````csharp
[Route("api/v1/items")
public class ItemsController : Controller
{
    [HttpPost("{id}/actions")]
    [CheckJsonBody("type", "ActionA")]
    public ActionResult DoActionA(int id, ActionA a)
    {
         // do something Aeish
    }

    [HttpPost("{id}/actions")]
    [CheckJsonBody("type", "ActionB")]
    public ActionResult DoActionB(int id, ActionB b)
    {
         // do something Beish
    }
}
````

### Describe alternatives you've considered
-  I could handle them in one controller action and do a switch on the "type" property but then I need to handle binding, validation, etc on my own.
- I have filed issue https://github.com/aspnet/Mvc/issues/5218 and implemented the suggestion from the helpful answer (implement `IActionConstraint` or `ActionMethodSelectorAttribute`, read from body stream, seek to 0). This is nice but not out of the box and a bit inconvenient. A more generic solution would be nice.

### Additional context
The reason to re-trigger this issue is due to a video about `System.IO.Pipeline` on [Channel 9](https://channel9.msdn.com/Shows/On-NET/High-performance-IO-with-SystemIOPipelines) (
with the awesome @davidfowl. David mentions here that ASP.NET Core 3.0 will expose the Kestrel Pipeline to the middleware. Together with the new JSON parser and a missing advance after reading the JSON till the action property could lead to a high performance solution worthy for inclusion in the ASP.NET Core framework.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
