### ISSUE TITLE
Have unique type names for Azure AAD and ADB2C auth packages

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#6580]
These two:
* https://github.com/aspnet/AspNetCore/tree/master/src/Azure/AzureAD/Authentication.AzureAD.UI/src
* https://github.com/aspnet/AspNetCore/tree/master/src/Azure/AzureAD/Authentication.AzureADB2C.UI/src

Have types that are of the same name/namespace but different assemblies. While this doesn't currently cause any specific technical problem, it's super gross, and can cause internal headaches when looking at stack traces or doing searches.

The types should each be prefixes appropriately.

**Comment by javiercn** [comment]
@Eilon I'm not sure how this causes problems given that they are both internal. I'll change the names as it really doesn't matter

**Comment by Eilon** [comment]
As mentioned, it's not a huge deal, but stack traces are harder to read, and it seems to have caused some customer confusion as well when they were digging into the code. But, it's a good practice to follow anyway.

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/pull/7096

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/commit/23c528c176e654e14cf5d078558420e00154d0e6
