### ISSUE TITLE
SignalR's spec tests have a dependency on an internal-only testing assembly

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#6581]
Added in https://github.com/aspnet/AspNetCore/pull/6433. We do not plan to ship Microsoft.AspnetCore.Testing to customers, so this dependencies needs to be removed, or we can't ship Specification.Tests to customers.

cc @muratg @BrennanConroy @JamesNK this needs to be fixed before 3.0 Preview 2.

**Comment by JamesNK** [comment]
Ah, so that is why copies are used. I'll make it so the spec tests use there own copy and put a comment explaining why.

**Comment by JamesNK** [comment]
Should TaskExtensions in Specification.Tests be public?

**Comment by JamesNK** [comment]
I am not able to compile SignalR.sln in VS2019 preview 1.

Some various issues:
1. Solution has a reference to `Microsoft.AspNetCore.SignalR.Redis` that doesn't load
2. Lots of missing dependencies cause NuGet warnings
3. I think there was a merge mistake with `Microsoft.AspNetCore.SignalR.Common`. I think this reference Newtonsoft.Json was removed in master.

**Comment by BrennanConroy** [comment]
I fixed up some stuff in https://github.com/aspnet/AspNetCore/pull/6622
