### ISSUE TITLE
Add mechanism to disable project build for ProjectServiceReference

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#6582]
From the meeting, it seems like a ProjectServiceReference requires the project referenced to be built. We'd like to add a mechanism to disable this requirement since it would be redundant in GRPC scenarios.

cc @dougbu @rynowak

**Comment by mkArtakMSFT** [comment]
@glennc and @dougbu please sync up regarding this during your next sync up meeting.

**Comment by dougbu** [comment]
We sync'd up.

This property (renamed to `$(OpenApiGenerateOnBuild)`) remains useful after the client / server split. Will control whether projects with (say) an NSwag.AspNetCore dependency get generated JSON files in their project. When `false`, the documents will not be saved to disk unless the user manually runs one of the CLI tools or hooks an `<Exec/>` of a tool into their project.

**Comment by dougbu** [comment]
This will come just after #8242

**Comment by dougbu** [comment]
25672336f92accfa8d24823d11d0bb5528c9ad4d
