### ISSUE TITLE
First class IEndpointFeature and IRoutingFeature in Kestrel

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#6596]
Today Kestrel has a fast path to avoid dictionary lookups by exposing features as fields on the it's IFeatureCollection implementation. We need to add the very commonly used IEndpointFeature and IRoutingFeature to this set this set:

https://github.com/aspnet/AspNetCore/blob/14e606997f8ef409f0ead89c0eda972bd09f96ab/src/Servers/Kestrel/tools/CodeGenerator/HttpProtocolFeatureCollection.cs#L22

cc @rynowak @JamesNK

**Comment by Tratcher** [comment]
Have you checked every feature assigned durring a normal mvc request?

**Comment by davidfowl** [comment]
This isn't for MVC, this is for routing. I haven't looked at all of the features used by default in MVC though.

**Comment by rynowak** [comment]
The additional features MVC commonly uses are:
- Routing
- Endpoint Routing
- Form
- Antiforgery

**Comment by muratg** [comment]
@davidfowl Moved this out to preview3.

**Comment by davidfowl** [comment]
Moving to preview4

**Comment by anurse** [comment]
Not user facing so prioritizing this after preview 5 (we can pull it up if we have time).

**Comment by davidfowl** [comment]
This was done in preview5

**Comment by davidfowl** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [VERSION]
            * ASP.NET Core Runtime: [VERSION]
            * .NET Core Runtime: [VERSION]
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]

**Comment by anurse** [comment]
> * SDK installer: [VERSION]
> * ASP.NET Core Runtime: [VERSION]
> * .NET Core Runtime: [VERSION]

I love .NET Core version `[VERSION]`. It's the best VERSION of all V E R S I O N S.
