### ISSUE TITLE
Release notes URL for 2.2.1 returns 404 error

### ISSUE THREAD

**Issue by fschlaef** [aspnet/AspNetCore#6600]
In https://github.com/aspnet/AspNetCore/releases/tag/v2.2.1 the "Release notes" URL is

https://github.com/dotnet/core/blob/master/release-notes/2.1/2.2.1/2.2.1.md

Should be 

https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.1/2.2.1.md

**Comment by leecow** [comment]
Fixed
