### ISSUE TITLE
Use HttpContextAccessor in .Net Framework 4.7 or a way to convert HttpContext.Current to HttpContextAccessor

### ISSUE THREAD

**Issue by luizvitor89** [aspnet/AspNetCore#6601]
Hey guys.

I am migrating a application .NET framework 4.7 to .NET Standard.

I'm dividing into small layers and migrating layer by layer. It was going very well, with each converted layer the system continued to work perfectly.

I noticed that anyone who developed it used session at the service layer instead of just using the presentation layer.

What I did was isolate the Session calls in a layer (still in .net 4.7) and reference it in the services layer (now .net standard) and the presentation layer (.net 4.7). The application worked perfectly up to this point.

So I migrated this session layer from .NET framework to .NET standard. The code itself seems to work perfectly. The only problem is that I have to pass the HttpContextAccessor to works.

Its my problem... I can't migrate the presentation layer to .Net Core

Its possible use HttpContextAccessor in a .NET Framework 4.7?
I try inject with Unity "container.RegisterType<IHttpContextAccessor, HttpContextAccessor>();", but ever HttpContextAccessor is null.
 
Or convert HttpContext.Current (.net 4.7) to HttpContextAccessor (.net core)?
I tried this too, but found no way to be done.

Can someone help me in this case?

The plan would be to migrate all layers except the presentation layer. And continue with the application working this way. Then create a new presentation layer made in .Net Core taking advantage of all layers already migrated, and replacing the old little by little

**Comment by davidfowl** [comment]
Abstract the session calls (ISessionAccessor or something like this) in an interface and then have 2 implementations, one backed by HttpContext.Current and one backed by IHttpContextAccessor.

**Comment by luizvitor89** [comment]
Great ideia. I will try it, then back here with a feedback. Thanks.

**Comment by luizvitor89** [comment]
@davidfowl your ideia for a solution works fine, thanks.

If anyone comes here looking for the solution (4.7 to core):
PS: I implemented only what I needed

Interface:
    public interface ISessionCompatibilization
    {
        byte[] Get( string key);
        int? GetInt32(string key);
        string GetString(string key);
        void SetInt32(string key, int value);
        void SetString(string key, string value);
        bool IsAvailable { get; }
        string Id { get; }
        IEnumerable<string> Keys { get; }
        void Clear();
        Task CommitAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task LoadAsync(CancellationToken cancellationToken = default(CancellationToken));
        void Remove(string key);
        void Set(string key, byte[] value);
        bool TryGetValue(string key, out byte[] value);
    }
}

Class:

    public class SessionCompatibilization : ISessionCompatibilization
    {
        private readonly ISessionCompatibilization _sessionCompatibilization;

        public SessionCompatibilization(ISessionCompatibilization sessionCompatibilization)
        {
            _sessionCompatibilization = sessionCompatibilization;
        }

        public bool IsAvailable => throw new NotImplementedException();

        public string Id => HttpContext.Current.Session.SessionID;

        public IEnumerable<string> Keys => (IEnumerable<string>)HttpContext.Current.Session.Keys;

        public void Clear()
        {
            HttpContext.Current.Session.Clear();
        }

        public Task CommitAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            throw new NotImplementedException();
        }

        public byte[] Get(string key)
        {

            return (byte[])HttpContext.Current.Session[key];
            
        }

        public int? GetInt32(string key)
        {
            throw new NotImplementedException();
        }

        public string GetString(string key)
        {
            return (string)HttpContext.Current.Session[key];
        }

        public Task LoadAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            throw new NotImplementedException();
        }

        public void Remove(string key)
        {
            HttpContext.Current.Session.Remove(key);
        }

        public void Set(string key, byte[] value)
        {
            HttpContext.Current.Session[key] = value;
        }

        public void SetInt32(string key, int value)
        {
            throw new NotImplementedException();
        }

        public void SetString(string key, string value)
        {
            HttpContext.Current.Session[key] = value;
        }

        public bool TryGetValue(string key, out byte[] value)
        {
            throw new NotImplementedException();
        }
    }
