### ISSUE TITLE
Inconsistency in index.html in Blazor template

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#6610]
Here is a partial listing from index.html file generated by VS template (Blazor 0.7.0)
```html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">
    <title>temptest</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
</head>
```
For consistency second `meta` element should have `/>` at the end.

On the other hand in HTML meta, base and link tags don't have end tags. They have to be properly closed only in XHTML. Do we need XHTML compatibility in Blazor?

**Comment by Andrzej-W** [comment]
@SteveSandersonMS it looks that you are working on Razor Components templates now. Maybe you can look at this ***minor*** issue.

**Comment by danroth27** [comment]
This has been fixed.

**Comment by danroth27** [comment]
This is still an issue in the Blazor (ASP.NET Core hosted) template.
