### ISSUE TITLE
How to read a javascript promise based function result using JsInterop and return to blazor?

### ISSUE THREAD

**Issue by arivera12** [aspnet/AspNetCore#6612]
Lets say I am using navigator geolocation api. How can I return the result (success/error) of this promise based functions to blazor?

**Comment by rynowak** [comment]
This is covered in the docs: https://docs.microsoft.com/en-us/aspnet/core/razor-components/javascript-interop?view=aspnetcore-3.0

**Comment by arivera12** [comment]
@rynowak Not still clear for me but I will give it a try playing with the docs examples to see if I can get a working sample. Thanks anyway.
