### ISSUE TITLE
[Identity] Add ability to UseEmailAsUserName

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#6613]
We've debated this before, but given that this is the normal situation these days, we should probably revisit this and add support to have email be the user name (and iron out all of the issues that come along with that, uniqueness, email confirmation, etc)

See https://github.com/aspnet/Identity/issues/182 for some of the old context, old PR https://github.com/aspnet/Identity/pull/165/files

**Comment by HaoK** [comment]
@blowdart @ajcvickers should this go into 3.0-preview3 or what milestone?

**Comment by blowdart** [comment]
I'd say Preview3.

**Comment by HaoK** [comment]
Discussed a big with @ajcvickers today, current plan is to introduce something like `UserNameIsEmail` which is a runtime only flag which would have the user manager use the username in any APIs that currently use email, this would also have a sideeffect of implicitly turning on RequireUniqueEmails.  Setting one property should also have the effect of setting the other (via identity apis).  

One thing we didn't discuss, what happens if they manipulate the poco directly, i.e.

```
user.Email = "something@foo.com".
user.UserName = "somethingelse@bar.com".
```

As I currently envision things, this would just end up setting Email to "somethingelse@bar.com" via the user manager.  Does that sound reasonable?

**Comment by Andrzej-W** [comment]
In a new application it is probably OK, but what about old applications? Let's assume we have the following user
```c#
user.Email = "john@example.com"
user.UserName = "john"
```
In that case you should rather copy `Email` to `UserName` and inform the user that from now he/she has to use email to login to the service.

**Comment by HaoK** [comment]
Right, I forgot to mention that discussion, this setting will only be meant to be used where the username and email are already the same.  It will not normalize or fix the database automatically, users can normalize their old database before turning on this flag which would work, but its not meant to detect any issues.  New apps starting in 3.0 would have this set to true explicitly, old apps they would have to opt into this behavior as needed.

**Comment by LindaLawton** [comment]
> It will not normalize or fix the database automatically, users can normalize their old database before turning on this flag which would work, but its not meant to detect any issues.

It would be nice if it would at least warn of duplicate emails or UserNames not equal to email.     Someone sets this by mistake and they are going to be pulling out their hair before they figure out the issue.

**Comment by Ponant** [comment]
Isn't it possible to just disconnect Email from Username, the latter being the only unique identifier of the user? This change would be done throughout the api and templates. Twitter style sounds good to me, the handler is the unique username and you can change it at will. Where would this be incompatible with the current Identity framework?

**Comment by Ponant** [comment]
@Haok do you mind explaining what is the problem? To me username and email are semantically different and thus should be kept separate. I currently have unique usernames (built in the api) and I require unique emails. But they are different from each others, and indeed users can change their emails but keep the same username. I just do not understand why you want to drop this kind of scenario?

**Comment by HaoK** [comment]
@Ponant then you would not set this flag to true

**Comment by HaoK** [comment]
We are tabling this for now, and just going to improve the flows, usernames different from emails will remain a scaffold/customization scenario with the default UI for now see https://github.com/aspnet/AspNetCore/issues/8356
