### ISSUE TITLE
[Helix] Razor Test.Common.TestCompilation.GetMetadataReferences will return null

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#6626]
Tracking for tests failing on helix due to: 

```
        D:\a\1\s\src\Razor\test\testassets\Razor.Test.Common\TestCompilation.cs(25,0): at Microsoft.CodeAnalysis.TestCompilation.GetMetadataReferences(Assembly assembly)
        D:\a\1\s\src\Razor\test\testassets\Razor.Test.Common\TestCompilation.cs(46,0): at Microsoft.CodeAnalysis.TestCompilation.Create(Assembly assembly, SyntaxTree syntaxTree)
```

```
Microsoft.AspNetCore.Mvc.Razor.Extensions.ViewComponentTagHelperDescriptorProviderTest.DescriptorProvider_FindsVCTH()
```

https://github.com/aspnet/AspNetCore/blob/haok/helix/src/Razor/test/testassets/Razor.Test.Common/TestCompilation.cs#L25

**Comment by pranavkm** [comment]
This might be because the deps file isn't getting deployed with the application.

**Comment by HaoK** [comment]
So right now the helix payloads are just exactly the results of dotnet publish on each of the test projects, would these tests work if we just included the deps file during publish?  There's also much larger set of test helix failures (in razor and other places) due to the sln not being able to be found as well

**Comment by pranavkm** [comment]
The deps file should already be part of the publish, so that's pretty unusual. As for the sln file, quite a few tests use it to locate other assets \ projects inside the current *repo*.

**Comment by rynowak** [comment]
Yeah we need to be able to load ref assemblies for these tests

**Comment by rynowak** [comment]
Yeah the Razor stuff will probably need a fresh look if it's a good to run on helix. We do a **ton** of nonstandard stuff.

**Comment by mkArtakMSFT** [comment]
Seems this is an issue with the helix specifically, where the deps file isn't being properly published. @HaoK assigning this to you. Feel free to close if this is not relevant any more.

**Comment by HaoK** [comment]
Doesn't look like this directory exists anymore so yeah not relevant anymore
