### ISSUE TITLE
[Failed] Microsoft.AspNetCore.StaticFiles.StaticFileMiddlewareTests.ClientDisconnect_Kestrel_NoWriteExceptionThrown

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#6633]
https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=71434

**Comment by anurse** [comment]
Closing this as these belong in AspNetCore-Internal, plus RaaS sees all :).
