### ISSUE TITLE
Centralized Identity Paths 

### ISSUE THREAD

**Issue by jlchavez** [aspnet/AspNetCore#6641]
I understand how asp.net has changed, and there are a lot of things that are still missing. Is there an easy what to get the Cookie Options programmatically so that I can build links according to the website configuration, and not manually changing it, like we used to have in asp.net webforms.

I'm pulling the IOptionsMonitor<CookieAuthenticationOptions> from HttpContext.RequestServices but the data is initializes to the asp.net core defaults. So I know I'm missing something.

Documentation on sharing cookies between multiple apps on the same domain is ok, but that's just for setting the cookie, but for a SSO site the redirect will be to the main subdomain and integrating the "domain" from this settings is useful for testing for "local redirects", that either are on the same domain of the login url or the current domain of the request. So a default url is useful in various use cases, like redirecting to the principal domain when login without a redirect url on the query string.

I'd have to create code for loading it from appsettings.json and I found all these settings basic requeriments for a site, that if we should be included on the primary assemblies by Microsoft.

¿Any suggestion how could I read those values from the Cookie Authentication Settings?

**Comment by blowdart** [comment]
I don't understand what you're trying to do here? What sort of links? Where does SSO come into this? Do you mean identity as in user identity, or the asp.net core identity libraries?

**Comment by jlchavez** [comment]
I'm building a modular online application that should have a single sign on page with cookies  authentication and OpenID for external authentication. So I finally resolved it, by reading how the code was built, finally found and abstracted a way to retrieve the links for the Identity Default UI, so my complaint is how complex is how to retrieve this urls out of the box, and that there are more links than the basic three (Login, Logout and AccessDeniedPath), that are not even included in the configuration, you must change the UI even if you have it on the Identity RCL. So for almost any adjustment you need to do you must scaffold the 27 pages for the Identity UI, and manually find the links or write them. There should be an out of the box solution for handling how to know where are this pages found, even the Default URL that the user will be redirected after login in or login out. Even loading this configuration from appsettings.json is not an easy task, for basic things, and the DefaltUI extension method for configuring it overwrites it, if you set de DefaultIdentity.

When you are developing small sites that must know where to redirect to login to a Single Sign On site, you write code, you recompile, deploy, and it might be "fast", but having to develop everything from scratch in all sites or subsites, it's really anoying. I've developed in the last month a couple of things, my first month developing in asp.net core, and had to extend all the basic features.

I'm also concerned about "performance", even if it's not that of a big deal, but if asp.net core is about of performance, then if you're site doesn't need to dynamically generate Identity URLs or any other options, you shouldn't be running the IPostConfigureOptions<CookieAuthenticationOptions> on every request, and an overwrite so that it could be loaded from configuration. Yes, you can remove the DefaultUI, and set all the required features by hand, but this is the way you set "options" and give default values for the settings in your application. More complex than in asp.net webforms. 

I've already extended asp.net core to have sitemaps, breadcrumbs, bootstrap tag helpers, for the basic navigation and UI that can be changed without having to rewrite all the html of a site if bootstrap or styles have changed. Building an RCL library is practical, but without localization and writing you URLs everywhere it's not a good practice for maintenance.

Finally I resolved it this way, registering a service...

`    public class AccountManager : IAccountManager
    {
        public AccountManager(IOptionsSnapshot<CookieAuthenticationOptions> cookieOptions)
        {
            this.CookieOptions = cookieOptions.Get(IdentityConstants.ApplicationScheme);
        }

        private CookieAuthenticationOptions CookieOptions { get; }

        public string LoginPath => CookieOptions.LoginPath;

        public string LogoutPath => CookieOptions.LogoutPath;

        public string AccountPath => SecurityOptions.AccountPath;
    }
`

**Comment by Tratcher** [comment]
@HaoK

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
