### ISSUE TITLE
Blazor: Lack of support for INotifyPropertyChanged and INotifyCollectionChanged

### ISSUE THREAD

**Issue by johngsandiford** [aspnet/AspNetCore#6647]
After a lot of experimentation, it appears that Blazor does not currently support auto refresh of the UI based on changes to objects implementing either INotifyPropertyChanged or INotifyCollectionChanged interfaces, that are used in other UI frameworks.

If there is no built-in auto-refresh mechanism, and this is by design,  then I guess Blazor is similar to React in the way refreshes work.  I.e. React is just a view framework, and requires additional support for refreshes, from libraries such as Mobx-react, redux, etc…  

> The fact that Blazor sometimes refreshes based on click and other events is quite confusing, as this does not work in many cases that I have tried. e.g. a) click a button in a component that updates an object passed using [Parameter], the parent does not refresh.  b) click a button in a component that updates an object passed using @inject, the parent does not refresh

However, with .NET already having a built-in equivalent of mobx in the form of INotifyPropertyChanged and INotifyCollectionChanged and these are implemented in many existing libraries, it would be great if Blazor could support auto UI refreshes based on them.

I understand that in order to keep Blazor flexible, this auto refresh mechanism might need to be optional, but it is very important that this is built-in, rather than a bolt on from a third party.

Without this,  Blazor, which up until this point has impressed me greatly is not usable for many of our scenarios. (We have uses for both WASM compute and server rendering).

Thanks, John

**Comment by enetstudio** [comment]
As far as I know the method StateHasChanged is automatically called by Blazor after events are raised. But you, the programmer, can call this method to refresh the UI whenever the state of your components has changed.  

This is what Steve Sanderson has to say about your issue: https://github.com/aspnet/Blazor/issues/1532

**Comment by johngsandiford** [comment]
> So what Steve says makes sense, however the component described is not currently available or built in to Blazor and is exactly what I think is likely to be required by many users. Deriving from BlazorComponent makes for a good optional way of achieving this, without stopping others using other refresh mechanisms.
> 

Additional thought: Deriving from BlazorComponent may not be the best way to do this, as developers creating custom shared components (e.g. DataGrid) would also need to optionally support this refresh mechanism, but also others.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @johngsandiford.
This is not something we plan to do in the near future.
