### ISSUE TITLE
ASP.NET Identity CookieAuthentication middleware results in too many redirects for authorized users visiting login page with a ReturnUrl param

### ISSUE THREAD

**Issue by mansoor-omrani** [aspnet/AspNetCore#6657]
I described it [here](https://github.com/aspnet/AspNetIdentity/issues/18)

I encountered this behavior (I don't know to call it a bug or issue) in traditional MVC. I didn't test it in MVC core, so I don't know if ASP.NET Identity code is affected or not.

I thought to write about that here as well. I noticed the repository I posted the issue there was solitude.

**Comment by blowdart** [comment]
If this reproduces in .NET Core please feel free to reopen this bug, but as it's speculative I'm closing it for now.
