### ISSUE TITLE
Is there a German Language Pack available

### ISSUE THREAD

**Issue by UweKeim** [aspnet/AspNetCore#6659]
Knowing that the full .NET Framework provides Language Packs for various languages, I was searching for something similar on the [.NET Core 2.2 downloads](https://dotnet.microsoft.com/download/dotnet-core/2.2) downloads page without success.

My issue is currently that the validation messages in my ASP.NET Core application for e.g. the `Required` attribute are shown in English, although the Windows Server and the application are German.

**My question:**

Is there any language pack for the .NET Core runtime?

If not, how can I tell the runtime to show built-in messages in German, instead of English?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @UweKeim.
@ryanbrandenburg, can you please look at this? Thanks!

**Comment by ryanbrandenburg** [comment]
You can find background [here](https://github.com/dotnet/corefx/issues/25128) but the long and short of it is that there's no localization of error messages out of attributes likes `[Required]` by default. If this is something you would like you can voice your opinions on the above issue. In the meantime you can localize these elements yourself (as long as you can produce the translations) by following the  advice from [this issue](https://github.com/aspnet/Localization/issues/286#issuecomment-249708911).

I'm going to close this out but if you still have trouble let comment or re-open and we'll see what we can do.
