### ISSUE TITLE
UseStaticFiles after update from 2.1 to 2.2

### ISSUE THREAD

**Issue by KANekT** [aspnet/AspNetCore#6660]
### Describe the bug
```
app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = new PhysicalFileProvider(
                    Path.Combine(Directory.GetCurrentDirectory(), "Files")),
                RequestPath = "/Files"
            });
```

project folder is D:\zaochno\new\src\WebSite

in 2.1 files look in 
'D:\zaochno\new\src\WebSite\Files\'

in 2.2 files look in 
'C:\Program Files\IIS Express\Files\'

**Comment by KANekT** [comment]
I think this is: https://github.com/aspnet/AspNetCore/pull/6150

**Comment by jkotalik** [comment]
Closing as a dup of https://github.com/aspnet/AspNetCore/issues/4206. Please use https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module/samples_snapshot/2.x/CurrentDirectoryHelpers.cs as a work around for now.

**Comment by jkotalik** [comment]
The error: 

```
Request finished in 119.2638ms 206 video/mp4 An unhandled exception of type 'System.ObjectDisposedException' occurred in System.Private.CoreLib.dll The CancellationTokenSource has been disposed.'
```

seems like it is probably coming from your application code. Check the callstack where the exception is thrown.

**Comment by jkotalik** [comment]
Actually it looks like this issue for the ObjectDisposedException: https://github.com/aspnet/AspNetCore/issues/4422
