### ISSUE TITLE
No clear recommended approach for code generation with ASP.NET Core

### ISSUE THREAD

**Issue by FionaHolder** [aspnet/AspNetCore#6663]
I am looking to build an application with ASP.NET Core and I am struggling to find any documentation or guidance on code generation.

Specifically, I am trying to generate controllers and views based upon my entities (I use Entity Framework) at build time. 

All I can find is information about T4 templates, that don't seem to be supported any more. Scaffolding seems to be a related topic, but isn't really automatic generation. There appears to be a CodeGeneration library for Core, but I don't really see any documentation. There are references to CodeDOM, but I think that's .NET Framework specific. I could go on.

Can we please have guidance on what we should be using for scenarios like mine? The documentation is very scattered. Thank you.

**Comment by Eilon** [comment]
Hi @FionaHolder , there's a Scaffolding feature in ASP.NET Core that ships as a set of command line tools you can invoke. By default they can generate MVC views/controllers or Razor Pages, typically based on Entity Framework Core models.

You can learn more about this in the documentation: https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.2&tabs=visual-studio

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
