### ISSUE TITLE
AspNetCore 2.2 Web API Backward Compatibility broken when dealing with Nullable Values

### ISSUE THREAD

**Issue by ksmithRenweb** [aspnet/AspNetCore#6665]
Previously web api endpoints taking Nullable<value> parameters worked when called with explicit "null" from client's. eg.
/api/Values/test/asdf=null or /api/Values/test/null

With AspNetCore 2.2 and the use of the new ApiController attribute. We started getting the error:
{"errors":{"asdf":["The value 'null' is not valid."]},"title":"One or more validation errors occurred.","status":400,"traceId":"80000008-0002-d200-b63f-84710c7967bb"}

To reproduce:
1) Create new web api net core 2.2 project. Using the VS 2017 project template.
2) Add this endpoint.
```C#
        [HttpGet]
        [Route("test")]
        public ActionResult<string> GetTest(int? asdf)
        {
            return "value";
        }
```
3) Run web api.
4) use route /api/values/test?asdf=null
5) error occurs

What does work is:
/api/values/test?asdf=1
/api/values/test   - which sets asdf to default(int?) which is null.

Expected behavior is that no error occurs and asdf is null within the scope of the method.

Work around that defeats some of the purpose, but removes the error in this case. Add SuppressModelStateInvalidFilter code to ConfigureServices.
```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
               .ConfigureApiBehaviorOptions(o => { o.SuppressModelStateInvalidFilter = true; });
            
        }

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ksmithRenweb.
@pranavkm, can you please look into this? Thanks!

**Comment by ksmithRenweb** [comment]
> @ksmithRenweb when you say compatibility was broken, is this between 2.1 and 2.2?

net framework 4.6.2 running the below package version. Most recently. 
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
The code has worked since aspnetcore 1.0.

**Comment by pranavkm** [comment]
By default, controllers marked with `ApiControllerAttribute` trigger a check for invalid model state and return a 400 Bad Request. Using the string "null" as a value for nullable types has always produced an model binding error, your action was likely not checking for it. Not passing in a value i.e `GET /api/Values/test` would be the way to correctly bind the parameter to a null value. 

Using `ApiControllerAttribute` ties you to a couple of opinonated behavior as detailed here: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2. It's a developer's choice to opt in to this behavior by decorating a controller with this attribute. You may upgrade existing 1.x applications to 2.1 or newer without also using `ApiControllerAttribute`. I don't see a reason to treat this as a regression.
