### ISSUE TITLE
Could we get Microsoft.AspNetCore.App.Lite?

### ISSUE THREAD

**Issue by mxmissile** [aspnet/AspNetCore#6671]
I like the idea of this meta package, but could we get a package that does not include the kitchen sink? (ef, logging, identity etc)

Something like `Microsoft.AspNetCore.App.Lite` or `Microsoft.AspNetCore.App.Barebones`

**Comment by natemcmaster** [comment]
Have you seen https://www.nuget.org/packages/Microsoft.AspNetCore/?

**Comment by mxmissile** [comment]
Thanks @natemcmaster
