### ISSUE TITLE
[Helix] Some razor tests fail due to NewLine differences on non windows

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#6675]
Appears to be some line ending diff failures on several razor tests when run on helix (non windows queues)

```
Failed   Lower_TagHelper_InSection
Error Message:
 Microsoft.AspNetCore.Razor.Language.Intermediate.IntermediateNodeAssert+IntermediateNodeAssertException : Failed while validating node Microsoft.AspNetCore.Razor.Language.Intermediate.DirectiveIntermediateNode at 1.

Nodes:
Microsoft.AspNetCore.Razor.Language.Intermediate.DirectiveIntermediateNode
Microsoft.AspNetCore.Razor.Language.Intermediate.DirectiveIntermediateNode

Path:

---- Microsoft.AspNetCore.Razor.Language.Intermediate.IntermediateNodeAssert+IntermediateNodeAssertException : Failed while validating node Microsoft.AspNetCore.Razor.Language.Intermediate.HtmlContentIntermediateNode at 1.

Nodes:
Microsoft.AspNetCore.Razor.Language.Intermediate.DirectiveTokenIntermediateNode
Microsoft.AspNetCore.Razor.Language.Intermediate.HtmlContentIntermediateNode
Microsoft.AspNetCore.Razor.Language.Intermediate.TagHelperIntermediateNode
Microsoft.AspNetCore.Razor.Language.Intermediate.HtmlContentIntermediateNode

Path:

-------- Microsoft.AspNetCore.Razor.Language.Intermediate.IntermediateNodeAssert+IntermediateNodeAssertException : Assert.Equal() Failure
          ↓ (pos 0)
Expected: \n
Actual:   \r\n
          ↑ (pos 0)
```

I fixed a couple easy cases of this, but will using this issue to track skips in the PR

**Comment by HaoK** [comment]
Ah, yea the payloads are all built and checked out on windows and sent to all the target queues, the idea is to build once and send out all the payloads which just run.

So the easy fixes to some of these failures were replacing ```@""``` that had newlines inside the string with split up strings that used `Environment.NewLine` instead.

**Comment by HaoK** [comment]
Is there a larger issue here with the razor tests?  Are there some that really need to depend on being built on the same machine that the tests will be run on?

**Comment by rynowak** [comment]
> So the easy fixes to some of these failures were replacing @"" that had newlines inside the string with split up strings that used Environment.NewLine instead.

Yeah, that kinda thing really doesn't work for Razor in the large. A lot of tests'n'stuff have lengths/indexes in them.

**Comment by HaoK** [comment]
Got it, @natemcmaster looks like some Razor tests are expecting to run on the same machine OS they were built on for some of their calculations to work.  We could still make this work with an additional category of helix test runs that do source checkout onto the test machines and run all of the tests that require source / and or being built on the machine.  

Basically split all the test assemblies into two buckets (helix payload vs build+run). To start, we could just move any test assemblies that rely on finding the sln, or have issues like these razor tests to the second bucket, and just run them all on an single additional helix job per queue that does a full checkout and just runs some new build.cmd option, i.e.

`build.cmd/sh -ci -runOnlyTheseTests="Microsoft.AspNetCore.Razor.Language.Test, Microsoft.AspNetCore.Razor.Extensions.Test,..."`

Thoughts?

**Comment by HaoK** [comment]
Actually, this is pretty similar to what the current PR does already, if we just tweaked things so the existing CI jobs only ran a subset of tests that don't work on helix (and let the helix job run the rest)

**Comment by mkArtakMSFT** [comment]
We already normalize the line endings and this should not be an issue any more.
