### ISSUE TITLE
Restore ExpressionRewriter for build time and runtime compiled views

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#6678]
Runtime compilation of Razor views and Pages used a Roslyn rewriter to produce a less allocation version of the SyntaxTree. Here's the code in use: https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Internal/ExpressionRewriter.cs. When converting to use build time compiled views, this optimization was lost. In addition, we aren't porting this feature as part of reviving runtime compilation until we have a story to maintain parity between build and runtime compiled views.

**Comment by rynowak** [comment]
I don't think we should ever do this.

**Comment by mkArtakMSFT** [comment]
Closing this as there doesn't seem to be a good reason to worry about perf at the cost this will take to do for build-time compilation.
