### ISSUE TITLE
onClick events fail if inside CascadingValue

### ISSUE THREAD

**Issue by owaits** [aspnet/AspNetCore#6684]
If you use a CascadingValue in a component and the child content directly has events such as onclick in a button then when the event is raised an exception occurs to the effect that CascadingValue does not implement IHandleEvents.

CascadingValueComponent.cshtml

```
<CascadingValue Value=this>
    @ChildContent
</CascadingValue>

[Parameter]
private RenderFragment ChildContent { get; set; }
```

UsingComponent.cshtml

```
<CascadingValueComponent>
<button class="btn btn-primary" onclick=@(()=>DoSomething())><i class="oi oi-british-pound" aria-hidden="true"></i> Update Prices</button>
</CascadingValueComponent>

@functions {
async Task DoSomething()
{
Console.WriteLine("Something");
}
}
```

If you now run this with the developer console open you get something like this screenshot.

![image](https://user-images.githubusercontent.com/13810266/51143388-5dae6b80-1846-11e9-8791-24bb2c03f0bb.png)

Its only when the event is handled by code upstream of the CascadingValue, if you have another component with events handled inside the cascading value then those events will be serviced.

**Comment by rynowak** [comment]
This has been fixed, probably as part of preview 3.
