### ISSUE TITLE
Reset the certificate used in the Data Protection after the application is stopped.

### ISSUE THREAD

**Issue by kevinlo** [aspnet/AspNetCore#6690]
My application loads a .pfx file in the application folder for the Data Protection.

```
            var certificate = new X509Certificate2(CertificateFileName, certificatePassword, X509KeyStorageFlags.MachineKeySet);

            services.AddDataProtection()
                .ProtectKeysWithCertificate(certificate)
```

Every time the application is started and new X509Certificate2 is created, a new 3KB file is created in the 
C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys.   This file is never be cleaned up.

There is a new [X509KeyStorageFlags.EphemeralKeySet flag available since .Net Framework 4.7.2](https://blogs.msdn.microsoft.com/dotnet/2018/04/30/announcing-the-net-framework-4-7-2/), setting it really can prevent the file generated in the MachineKeys folder.

`var certificate = new X509Certificate2(CertificateFileName, certificatePassword, X509KeyStorageFlags.MachineKeySet |  X509KeyStorageFlags.EphemeralKeySet);`

However, some of my application requires target net46 where this flag is not available.   I read from this [link ](https://stackoverflow.com/questions/22618568/prevent-file-creation-when-x509certificate2-is-created?noredirect=1&lq=1)that calling the X509Certificate.Reset function will remove the file.   I try it and it can remove the file.   

In fact, when I first trying on application target for netcoreapp2.1, calling Reset does not clean up the.  I change the project target for net461, the Reset works.   Then I change back the project back to netcoreapp2.1, it works too.     Does it have something like garbage collection that trigger cleaning up the MachineKeys folder?

So, for the net461 target application, I need to call the X509Certificate.Reset function when the certificate is not used anymore.   My question is where is the good place to call the Reset?

I check the DataProtection source codes, the certificate is kept in the CertificateXmlEncryptor and the _certs dictionary in the XmlKeyDecryptionOptions.  I think the certificate is needed through the life cycle of the application for data protection use.   Does the DataProtection code call the X509Certificate.Reset or Dispose function after finish using the certificate?   If not, where is the right place to call it?  Is it during IApplicationLifetime.ApplicationStopped?

My main purpose is to clean up the file generated in the C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys.   Any suggestion is welcome.

**Comment by kevinlo** [comment]
@blowdart , thanks for your reply.

Do you mean I should use the DefaultKeySet or UserKeySet and the key will be deleted properly?

I do write a simple console app like the following to test the Reset.   I find that sometime the Reset does delete the file and sometimes don't.   Do you know what control it?

```
        static void Main(string[] args)
        {
            string certificateFileName = args[0];
            string password = args[1];
            var cert = new X509Certificate2(certificateFileName, password, X509KeyStorageFlags.MachineKeySet);

            string uniqueKeyContainerName = "";
            var privateKey = cert.PrivateKey as RSACryptoServiceProvider;
            if (privateKey != null)
            {
                uniqueKeyContainerName = privateKey.CspKeyContainerInfo.UniqueKeyContainerName;
                Console.WriteLine($@"Created C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\{uniqueKeyContainerName}");
            }

            cert.Reset();
        }

```

Currently, I call the Reset at ApplicationStopping event
```
            var appLifetime = app.ApplicationServices.GetRequiredService<IApplicationLifetime>();
            appLifetime.ApplicationStopping.Register(() =>
            {
                _certificate.Reset();
            });
```

But the Reset does not always delete the file.  Do you know how I can find the machinekey file name from RSACng?

Also, is the X509KeyStorageFlags.EphemeralKeySet a right option?

**Comment by blowdart** [comment]
I'd ask in the [dotnet repo](https://github.com/dotnet/corefx/issues) about that, we don't control that code, and we can't call reset for you automatically, or indeed dispose, as we have no way of knowing if you're only using that instance for dataprotection.

**Comment by kevinlo** [comment]
@blowdart  I understand I need to call the Reset somewhere.  I just want to find out the right solution for it.  

What's your comment of using X509KeyStorageFlags.EphemeralKeySet?   As the .pfx file is loaded whenever the application is started up, I think it is ok to keep the key in memory, instead of in the drive.   I am new to these, I need a second opinion about it. 

My current plan is:

1. For component target for netcoreapp2.1, use the X509KeyStorageFlags.DefaultKeySet | X509KeyStorageFlags.EphemeralKeySet flag , 
2. For component target for net461, use the X509KeyStorageFlags.DefaultKeySet,
3. In both cases, call the Reset when the Certificate is not needed anymore, e.g. at ApplicationStopping event.

**Comment by kevinlo** [comment]
I get the answer what I need to do from this thread and the reference thread.  I can close this issue.
