### ISSUE TITLE
Question: ASP.NET core 1 and 2 difference in OpenIDConnect cookie

### ISSUE THREAD

**Issue by ruchanb** [aspnet/AspNetCore#6702]
I have asked this question on stackoverflow also but didnt get any answer 
https://stackoverflow.com/questions/54186959/asp-net-core-1-1-2-openid-connect-cookies-not-being-created-on-redirect-set-coo

I had an issue with **oidc cookie not being stored in browser** for client application, even though `set-cookie` header was being sent. I have this system running for more than a year on same settings and had no issues until today.
System Info:
.NET Core 1.1
SSL enabled on both Client and SSO application. 
Different sub domain for Client and SSO application.

Response Header in .NET core version 1.1
``` 
   Content-Length: 0
   Date: Mon, 14 Jan 2019 18:50:10 GMT
   Location: http://mysso.com/connect/authorize?client_id=8111797110116117109&redirect_uri=http%3A%...ZD7cNnuWSmAoGyk2kERmR4hemQKsP2OKNbABYvybQCrdCMggrggDuY-5ZXnCTFf3oG11cR4Eh5N3Uarh99MD1nvJZrO4WsWDO73OQrEjh-zK3AceJzjfB2GH0gKKw-51SpcUWNgSTbQe517
   Server: Kestrel
   Set-Cookie: .AspNetCore.Correlation.oidc.I3lU6aE3BFH_4uuJ6KlgbpFl6Dij_WC-nyhlbUfvAPI=N; expires=Mon, 14 Jan 2019 18:07:24 GMT; path=/; httponly
   Set-Cookie: .AspNetCore.OpenIdConnect.Nonce.CfDJ8BWkCPQm5ElIof7iuryYpWDHYvyls6nYDr84XfQAIcLzg0ktLHIGOP7Tp_eqbvDOTdcQqnKIIogwMad9tWSy9v8BPnN8VUBucuz8qc9kv5Pkpe5aCg9oh6dgQD79a-w8Lc9haFm_tOEze1Wzna3XG7OzcGhw8kwyU5j3K_sK3Z7Y-u3cE_pey9DVbBzZkZStJXpoNjG_HWJHBjuqv7ADfCc91Oi83Ieuk7bBue8md1v2WqvSji3ziHkqyw9FKTV44Iw2Kg4o8Rf_3G-Q9ITNwr8=N; expires=Mon, 14 Jan 2019 18:07:24 GMT; path=/; httponly
   X-Powered-By: ASP.NET
```

To solve this issue i had to upgrade to .NET core 2.0 which had a bit different cookie header
Response header .NET core version 2.0
```
   Content-Length: 0
   Date: Tue, 15 Jan 2019 10:53:04 GMT
   Location: https://mysso.com/connect/authorize?client_id=8111797110243116117109&redirect_ur...
   Server: Kestrel
   Set-Cookie: .AspNetCore.Correlation.oidc.Iy3pTZ-akQm6BzLMCdBPLz1CAGTJ70QgQtjkY9Kvg1Y=N; expires=Tue, 15 Jan 2019 11:08:04 GMT; path=/signin-oidc; secure; httponly
   Set-Cookie: .AspNetCore.OpenIdConnect.Nonce.CfDJ8Oct5aw6xUJOnpJ_-0Ep-nSLfWIXgaEiH7y-0IN9tx61lNrxFhgAzLvLlBQfOfBBegyRJrEsIZFi00iuUt90cJ_bMQI_1XTVr0SiBCAJ9wqR2682VrYe2IbjIrFuB9d-Mmu-ztw-O2Htzd8Z36ndD8zPsgSCY_RD6JYVRe4MTfFBQbDZRxMQ3rgB_ulvSZmshD7vB4gvgcsbLyiY2wVuKzVGEKgJxgq23nxzkNKkL-vHm6w_41D_rZI5_V9hDsfrShFuTViZNttAes1fmA2jMTQ=N; expires=Tue, 15 Jan 2019 11:08:04 GMT; path=/signin-oidc; secure; httponly
   X-Powered-By: ASP.NET
```
Now the cookies gets stored in browser and work as intended.

The difference I see is Core 1.1 doesnt have `path=/sigin-oidc; secure` in the cookie. 

I have no clue why this would have been issue until now.

**Comment by blowdart** [comment]
Jinx :) Assuming the expiry dates in 1.1 weren't in the past (there's a day's difference in your two headers) I honestly don't know what to tell you. If we're sending the headers the browser should be creating the tickets.

**Comment by ruchanb** [comment]
yeah that seems to be the issue, as i can see too. I am not sure to why it happened on that day only.
