### ISSUE TITLE
SignalR windows authentication error using long polling

### ISSUE THREAD

**Issue by FTWinston** [aspnet/AspNetCore#6704]
I previously had an error on .NET Core 2.1 with SignalR long polling and windows authentication. [This was raised here](https://github.com/aspnet/SignalR/issues/2948) and resolved in the 1.1.0-preview3 release of SignalR.

### Describe the bug
I am now seeing an `UnauthorizedAccessException` when the windows identity is being cloned by SignalR when windows authentication is being used, even when the SignalR hub doens't require authentication.

This error occurs when using SignalR 1.1.0-preview3 with .NET Core 2.1.
It also occurs when using SignalR 1.1.0 with .NET Core 2.2.

The problem is occuring when deployed to a machine running Windows Server 2012 R2.

The problem does not occur when running on a Windows 10 machine, whether running in IIS Express or in IIS.

[Here is a sample repository for reproducing the issue.](https://github.com/FTWinston/SignalrWindowsAuth) Again, the error only occurs when deployed to our Windows Server 2012 R2 box.

The sample site has two MVC controllers, one with [Authorize] and one without, and two SignalR hubs, again one with [Authorize] and one without.

The site is configured in IIS to use Windows Authentication and Anonymous Authentication, like so:
![image](https://user-images.githubusercontent.com/1863145/51187433-c2fc6e00-18d3-11e9-8481-c0cd56877a74.png)

The site shows buttons to calls method in each of the controllers and hubs.

Essentially what happens is that if you click the "Authenticated hub" button, _or_ if you click the "Unauthenticated hub" button after having clicked the "Authenticated controller" button, you get the following error:

```
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at System.Security.Principal.WindowsIdentity.get_AuthenticationType()
   at System.Security.Claims.ClaimsIdentity..ctor(IIdentity identity, IEnumerable`1 claims, String authenticationType, String nameType, String roleType)
   at System.Security.Principal.WindowsIdentity..ctor(WindowsIdentity identity)
   at System.Security.Principal.WindowsIdentity.Clone()
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.CloneUser(HttpContext newContext, HttpContext oldContext)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.CloneHttpContext(HttpContext context)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.EnsureConnectionStateAsync(HttpConnectionContext connection, HttpContext context, HttpTransportType transportType, HttpTransportType supportedTransports, ConnectionLogScope logScope, HttpConnectionDispatcherOptions options)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteAsync(HttpContext context, ConnectionDelegate connectionDelegate, HttpConnectionDispatcherOptions options, ConnectionLogScope logScope)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteAsync(HttpContext context, HttpConnectionDispatcherOptions options, ConnectionDelegate connectionDelegate)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

### To Reproduce
1. Build and deploy the [sample project](https://github.com/FTWinston/SignalrWindowsAuth) and deploy it to a Windows Server 2012 R2 VM, with ASP.NET Core 2.2 installed.
2. Add it to IIS, and enable Windows Authentication (Anonymous Authentication will be enabled by default, leave this on).
3. Browse to the site, click "Unauthenticated hub", wait 5 seconds, and you will see _Result: test ok_.
4. Click "Authenticated controller", enter valid windows credentials, and you will see _Result: ok_,
5. Click "Unauthenticated hub" again and you will see the error.

Alternatively, clicking "Authenticated hub" at any point will cause the same error.

### Expected behavior
The hub methods should complete without error, if the user has already authenticated.

### Additional context
The dotnet --info output from the server where the problem occurs is:
```
E:\wwwroot\SignalrWindowsAuth\logs>dotnet --info

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

On my Windows 10 desktop where this error does not occur, the dotnet --info output is:
```
PS C:\Development\SignalrWindowsAuth\SignalrWindowsAuth\ClientApp> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Might the server deployment be mis-configured somehow in a way that I'm not spotting? Or is this a bug? I'm happy to install the 2.1.1 update locally if that helps track this down.

**Comment by halter73** [comment]
Possibly related https://github.com/aspnet/IISIntegration/issues/231

**Comment by FTWinston** [comment]
Correction: I _am_ seeing this error on my local machine when running through IIS.

I thought I wasn't seeing it yesterday, but it's definitely happening today when I've gone to try and determine whether changing the account the app pool runs as might make a difference. It doesn't seem to.

**Comment by Tratcher** [comment]
@BrennanConroy was investigating this with me last week and had made some progress. Let's get his report.

**Comment by BrennanConroy** [comment]
I can reproduce this with your app on 2.2 but switching to 2.1 stops it from happening.

This issue https://github.com/dotnet/corefx/issues/31841 looks like the exact same issue, and there are a few changes that went into the WindowsIdentity source between 2.1 and 2.2.

Someone made a workaround https://github.com/Cyberboss/tgstation-server/commit/4d4b6a0606cbde5f26392faa601e6bec0dfc34ec which I can test out to see if it fixes the issue for us.

**Comment by BrennanConroy** [comment]
@FTWinston we're fixing this in OutOfProcess IIS in 3.0, if you want to workaround the issue you can host InProcess IIS which will work.

**Comment by FTWinston** [comment]
Thanks @BrennanConroy, much appreciated!
