### ISSUE TITLE
Inconsistent DisplayName CTOR/property documented intent within ExternalLoginInfo and UserLoginInfo

### ISSUE THREAD

**Issue by syndicatedshannon** [aspnet/AspNetCore#6712]
In [ExternalLoginInfo.cs](https://github.com/aspnet/AspNetCore/blob/65ff6e951a29ac026e6528c203f590244948910c/src/Identity/Core/src/ExternalLoginInfo.cs) it says `displayName` is:

> The display name for this user provided by the login provider.

However, in [UserLoginInfo.cs](https://github.com/aspnet/AspNetCore/blob/65ff6e951a29ac026e6528c203f590244948910c/src/Identity/Extensions.Core/src/UserLoginInfo.cs) that parameter is assigned to `ProviderDisplayName`, which it says is:

> The display name for the provider.

The ctor description also diverges in the base class.

However, I don't really see why the ProviderDisplayName is stored with each user, when it is bound to the provider, not the user. Maybe the intent was originally to store the user's Profile.DisplayName from the provider in that field?

**Comment by syndicatedshannon** [comment]
Yeah, it sure seems like the CTOR param description is probably correct, and the prop description as well as the implementation is incorrect. I suppose an individual could name one remote account "Business Facebook Identity" and another one "Personal Facebook Identity", and then disassociate the correct account at a future date; but that login personalization interaction is not plumbed, and storing the person's displayname would provide a reasonable default for that same purpose anyway.

**Comment by syndicatedshannon** [comment]
Plus, from a human data maintenance perspective, it's probably much more helpful to see
facebook:37892347:"Charlie Landry"
than
facebook:37892347:facebook

**Comment by blowdart** [comment]
We'd be more than happy to accept a PR to fix this

**Comment by syndicatedshannon** [comment]
Would a change to store User's DisplayName (instead of ProviderDisplayName) be approved, or would it be rejected as breaking?

**Comment by syndicatedshannon** [comment]
It looks like the field didn't exist in 2015. Then was added by HAOK in 2016:
https://github.com/aspnet/Identity/commit/c80ec3f326a0709dae53105c7f876ffae4804599

But there were no notes about its intent. It was still left null in storage as of this issue in 2016:
https://github.com/aspnet/Identity/issues/862

It was recently flagged as a schematic issue, in 2018:
https://github.com/aspnet/Identity/issues/1892

It was rebound in the UI to the login provider truth to address that issue, in 2018:
https://github.com/aspnet/Identity/pull/1899

However the aschematic field was left in-place.

**Comment by syndicatedshannon** [comment]
I found the original notes on design intent:
https://github.com/aspnet/Identity/issues/97

**Comment by HaoK** [comment]
The xml comments are wrong, the property is for storing the friendly name of the external provider (not the user), i.e. "Google", "Facebook".  Since this is the property that is used by the templates for the text of the buttons shown on the external login

**Comment by syndicatedshannon** [comment]
Are there any remaining scenarios where you would expect this provider DisplayName value will not originate from an IAuthenticationSchemeProvider lookup, i.e.
`(await GetExternalAuthenticationSchemesAsync()).FirstOrDefault(p => p.Name == provider)?.DisplayName ?? provider`

**Comment by syndicatedshannon** [comment]
Does the original WsFed intent still apply? I'm trying to understand under what circumstances an external authenticator would be trusted to name itself.

**Comment by syndicatedshannon** [comment]
what I'm suggesting is that now that the code copies const values into storage, that storage column may no longer be of value. we could perform that assignment on read instead of write.

**Comment by blowdart** [comment]
Yea, we're not going to change the functionality of a field to match the doc columns, which would be a breaking change.

Instead Hao will fix the comments :)

**Comment by syndicatedshannon** [comment]
It's not unusual to consider documentation a valid contract. Thus my historical investigation.
