### ISSUE TITLE
Coloring and intellisense is lost after hitting backspace in some cases

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#6717]
![vsbug](https://user-images.githubusercontent.com/1579269/51206626-57a7a180-18bd-11e9-8918-dd6b9ac8a6dd.gif)

I'm not sure whether the fix for this goes in Razor partial parsing or WTE. Needs some investigation.

Note: This is not a regression. I've verified this problem exists in both VS 2019 (16.0 Preview 2) and VS 2017 (15.9.5)

**Comment by mkArtakMSFT** [comment]
Closing this as there was no community interest in this.
