### ISSUE TITLE
ActionResult<T> class shouldn't be sealed

### ISSUE THREAD

**Issue by wojanator** [aspnet/AspNetCore#6729]
### Describe the bug
I was going to make an inherited class `ActionListResult : ActionResult<List>` to help avoid repeating List everywhere in controllers but I can't do this because this class is marked as sealed. Why mark this as sealed?

### Expected behavior
Be able to use inheritance.

**Comment by blowdart** [comment]
Without the class name we can't really talk about why it's sealed. Could you please supply it?

**Comment by gfoidl** [comment]
The issue got edited (see there) -> `ActionResult<List>`

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/51278309-55f1e280-197e-11e9-8036-801b0b1823fd.png)

**Comment by syndicatedshannon** [comment]
I, too, had to discard the ActionResult<T> implementation because it was sealed.
I ended up re-implementing in AspNetCore the same solution I'd previously used in AspNet.
I didn't duplicate all functionality of ActionResult<T>, as I didn't implement IConvertible<T> or IConvertToActionResults.
However, I recall understanding why it had been sealed when I investigated. I feel like perhaps it was just the issue of IConvertible symmetry?
It wasn't a big deal to re-implement, but it concerns me that other bits of AspNetCore leverage ActionResult<T>, and we can't derive. Sorry, the only bit I currently remember is something about Swagger.

**Comment by syndicatedshannon** [comment]
I should probably also mention why I found `ActionResult<T>` insufficient.
One issue I had is that any `ActionResult<T>` can be implicitly converted to `ActionResult` and any `ActionResult` can be used to construct any `ActionResult<T>`. That leaves a lot of room to defeat useful compiler checks.
Additionally, other useful `IActionResult` implementations can return a specific type, such as `CreatedAtRoute` (I need to extend that as well, so additional sealed types won't help here).
Lastly (that I can remember) various useful Controller methods expect types that won't conform. I don't remember what I found when I tried to drive `ActionResult<T>` through an `Ok<T>()` overload, but something was unpleasant.

**Comment by syndicatedshannon** [comment]
My personal thinking at the time was that `ActionResult<T>` would probably get a pretty significant redesign in v3 due to the above, and I would just not worry about it until then.

**Comment by davidfowl** [comment]
> That leaves a lot of room to defeat useful compiler checks.

Can you elaborate?

**Comment by syndicatedshannon** [comment]
Hey David, sure. A crude example to start. If we are generating proxies or documentation from our return types, of course we'd like the compiler to ensure our proxy/client doesn't throw RT (de)serialization errors. Otherwise attribute-based documentation performs the same function.

However, the following compiles:

```
public ActionResult<int> GetId() {
    return Ok(Guid.Create());
}
```

**Comment by wojanator** [comment]
In my case, I just don't want to write this over and over in conrollers:
`        public async Task<ActionResult<List<InventoryBookingsGetModel>>> GetAvailabilityAsync(DateTime date)
`

Task<ActionResult<List<InventoryBookingsGetModel>>>  that is a ton of noise that I was hoping to simplify as :
Task<ActionListResult<InventoryBookingsGetModel>>
or even 
ActionListResultTask<InventoryBookingsGetModel>

**Comment by syndicatedshannon** [comment]
> just don't want to write this over and over

I hear you and appreciate your intuitive desire to reduce repetition. Of course reducing code shouldn't be the only goal. Readability is important too, and not *always* correlated with fewer characters. e.g. if we just want to reduce code we could simply state the return type as IActionResult in all cases.

By merging the content type with the platform type, we make it harder for consumers (both humans and tooling) to understand the data type that will need to be (de)serialized. We can't apply a simple logical rule and say "our web methods return whatever is inside the ActionResult angle braces".

**Comment by syndicatedshannon** [comment]
I don't know how `ActionListResultTask` would affect Swagger and client proxy generation tools, but I wouldn't be surprised if it broke them.

**Comment by pranavkm** [comment]
>That leaves a lot of room to defeat useful compiler checks.

We're tracking addressing this using an analyzer in https://github.com/aspnet/AspNetCore/issues/8535.

Is there a reason you weren't able to use `IConvertToActionResult`? It's the contract the rest of MVC uses to produce an instance of `IActionResult` from `ActionResult<T>`.

**Comment by syndicatedshannon** [comment]
> Is there a reason you weren't able to use IConvertToActionResult?

@pranavkm I'm not sure. As I noted above, I reviewed it as an option at the time I selected an approach, and chose against it. Looking at what I did, I probably chose to derive from `OkObjectResult` for the following reasons:

 - to avoid re-implementing `StatusCode` and associated domain knowledge
 - provide a migration path, as my API surfaces have grown large and interfaces cannot supply implicit conversions
 - less code; see below:

```
	public class WebOkResult<T> : OkObjectResult, IWebResult<T> {
		public WebOkResult(T content) : base(content) { }
	}
```

> We're tracking addressing this using an analyzer in #8535.

@pranavkm Thanks for the heads-up. I wish it weren't necessary, as those additional layers of tool-dependencies aren't my favorite thing to see growing. It was my intention, when I got back to it, to derive separate branches for the main result and exceptional results. For example, I'm comfortable if `UnauthorizedResult` is convertible to `ActionResult<T1>`, I just don't want `T2` implicitly converting to `ActionResult<T1>` through any typical chain.

Personally, for most of the work I do in the middle tier, what I really desire are raw DTO return values. I could ignore all of this business if there were a better way to return `T1` and `T2` directly, while still allowing a high-performance exceptional response branch.

**Comment by syndicatedshannon** [comment]
@pranavkm Also, I would have naturally preferred returning a well-supported existing type over deriving my own based solely on a conversion interface, both to avoid potential performance issues and to avoid other nuanced serialization/response defects due to my lack of familiarity with the ASP.NET Core codebase.
