### ISSUE TITLE
Re-enable building the Blazor VSIX on CI

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#6734]
CI is not currently building Microsoft.VisualStudio.BlazorExtension. Per chat with @SteveSandersonMS, this is an important thing to resolve ASAP.

It seems when merging source code from aspnet/Blazor, the targets that built the VSIX project were disabled and never re-enabled. 

After https://github.com/aspnet/AspNetCore/pull/6698 is merged, fixing this will involve (at minimum) removing the `ProjectToExclude` entry from build/repo.props.

cc @mkArtakMSFT @pranavkm as this may be time-sensitive.

**Comment by natemcmaster** [comment]
FYI - these are the lines you need to alter to get build.cmd to pick up this project

https://github.com/aspnet/AspNetCore/blob/5a70f5312fb57fc3788e5af56a99e7b43761e195/build/repo.props#L40-L51

Keep the exclusion, but move it down into the one below which has `'$(MSBuildRuntimeType)' == 'Core'`. This exclusion is still necessary because VSIX projects are not supported by `dotnet build`.

**Comment by rynowak** [comment]
Donezo
