### ISSUE TITLE
Consider renaming FunctionalTests.csproj to include Cors in its name

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#6738]
It was really hard to know what area "FunctionalTests.csproj" is in build logs/etc since it doesn't have any namespace or other identifying information in its name. 

https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/CORS/test/FunctionalTests/FunctionalTests.csproj

**Comment by HaoK** [comment]
Wasn't sure if this is supposed to go to area middleware or MVC, since it lives in Middleware, yet the area-mvc description mentions CORS explicitly...

**Comment by mkArtakMSFT** [comment]
Thanks @HaoK.
We won't really get to this given the current priorities. Feel free to do it, if you want.

**Comment by HaoK** [comment]
Project was deleted
