### ISSUE TITLE
IIS Fails With 500 Error With Precompiled Project

### ISSUE THREAD

**Issue by jjxtra** [aspnet/AspNetCore#6747]
### Describe the bug
If you deploy a precompiled asp.net core site, such as Windows-x86 with .NET core 2.2, but on your server you only have the .NET core hosting pack 2.1 installed, the website will fail with a 500 error on all urls. Setting std out log in the web.config has no effect.

### To Reproduce
1. Create a precompiled website using **.NET core 2.2**, a simple hello world page is all that is needed to test. Ensure Windows-x86 is chosen for architecture, but I assume Windows-x64 will also have the problem.
2. On Windows Server 2012, install **.NET core 2.1** hosting pack and runtime.
3. Setup your iis website for .NET core. Create app pool with enable 32 bit apps turned on. Assign app pool to website.
4. Attempt to browse your root url, you will see a 500 error.
5. Turn on std out log in web.config. Restart iis. Attempt to access root url again. No log is written.
6. Nothing is written to the event viewer either.

### Expected behavior
It sure would be nice to have the hosting pack be forwards compatible, at least for major versions. This is the whole point of precompiled packages. If we have to upgrade the hosting pack every time we upgrade our .NET SDK on the developer side, we are no better than .NET framework was.

**Comment by jkotalik** [comment]
@shirhatti

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
