### ISSUE TITLE
shared model for client code generation from OpenAPI

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#6750]
### Is your feature request related to a problem? Please describe.
IMHO it is best practice to use shared code/assembly/nuget packages that contain the models exposed/shared between client/server API surface.

### Describe the solution you'd like
IMHO if the developer has access to shared code/assembly/nuget packages that contain API model information this should be used/added as a reference to the generated strongly typed client.

If the model package is not available or invalid, doesn't match the return/parameters exposed by API and included in the specification then it should be ok to generate the model.

It is also good practice from the point of view with regards versioning of the model.

### Describe alternatives you've considered
This could also save time with regard to generation as the model may/may not change; but the API method calls may change and likewise the opposite may be true.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @grahamehorner.
There are no baked-in client code generators in the ASP.NET Core framework. We rely on external code-generation providers (NSwag) to do that. So this is an ask for them. When/if they have support for it, we'll consider improving our (still to come) tooling to be updated to simplify this process.
