### ISSUE TITLE
Forwarded Headers Middleware dont work on Google App Engine cloud

### ISSUE THREAD

**Issue by yosigolan** [aspnet/AspNetCore#6758]
### Describe the bug
After configuring the Forwarded Headers Middleware as described in the documentation, when getting the RemoteIpAddress the load balancer address is returned instead the client IP address.
this happens on Google App Engine flex environment running .net 2.2

the X-Forwarded-For is holding the correct ip and can be retrieved manually by the headers attribute on the request.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run simple controller, configure Forwarded Headers Middleware and get remote address running on App Engine
3. Run on app engine

### Expected behavior
The client ip should be returned.

### Screenshots
this is the ip returned:
![image](https://user-images.githubusercontent.com/18391088/51274126-0a1f5780-19d7-11e9-916a-4c4f5c840bc7.png)

**Comment by davidfowl** [comment]
Can you provide a sample application?

**Comment by yosigolan** [comment]
sure, i will soon.

**Comment by yosigolan** [comment]
hey @davidfowl .
please find the test app that demonstrate the issue here: https://github.com/yosigolan/ForwardedHeadersMiddlewareBug

the app is also loaded on google app flex engine and you can try accessing it like this:
http://seevoov-clound-infra.appspot.com/api/GetIp

let me know if you need anything else.

Yosi

**Comment by yosigolan** [comment]
@davidfowl 
i stopped the service for now. let me know if you need it started.

Yosi

**Comment by Tratcher** [comment]
See KnownNetworks and KnownProxies. Only loopback proxies are trusted by default. We had a similar scenario here where the proxy IPs were too unstable to preprogram so we only turned it on when we set a specific environment variable:
https://github.com/aspnet/AspNetCore/issues/4135#issuecomment-493592243

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. It sounds like @Tratcher 's comment described the cause of the issue (not using appropriate `KnownNetworks` or `KnownProxies` values). If I'm misunderstanding or that's not working in your scenario, let us know and we can revisit this!

**Comment by yosigolan** [comment]
@anurse i dont understand why you closed it. what do you mean you haven't heard from me? i created a reproducing project for you and you haven't used it. the issue still remains.

Yosi

**Comment by Tratcher** [comment]
@yosigolan did you follow up on my comment? https://github.com/aspnet/AspNetCore/issues/6758#issuecomment-501466612

**Comment by anurse** [comment]
Yep, @Tratcher described that when you aren't using a local proxy, you need to configure `KnownNetworks` and `KnownProxies` otherwise the forwarded headers won't be accepted (since it would be a security vulnerability to accept forwarded headers unless the client is a well-known proxy). There is documentation on this configuration here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#forwarded-headers-middleware-options

If you're still seeing issues after configuring this, let us know!

**Comment by yosigolan** [comment]
@Tratcher  @anurse 
Thanks, i understand, i will check it.

Yosi
