### ISSUE TITLE
GenericWebHostBuilder.UseStartup injects wrong config into Startup

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#6765]
https://github.com/aspnet/AspNetCore/blob/5a70f5312fb57fc3788e5af56a99e7b43761e195/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs#L221-L236

If you inject IConfiguration into Startup you get the host config, not the app config. This breaks EF when it tries to resolve connection strings.

@davidfowl

**Comment by Tratcher** [comment]
GenericWebHostBuilder.ConfigureServices also injects the host config rather than the app config. It's using a cached WebHostBuilderContext that's not updated as the build progresses.

**Comment by JunTaoLuo** [comment]
@ryanbrandenburg maybe this is what's breaking templating?
