### ISSUE TITLE
Home Url in Area in an ASP.NET Core 2.1 Web Application is generated to the Area not to the Home Page

### ISSUE THREAD

**Issue by jlchavez** [aspnet/AspNetCore#6766]
### Describe the bug
When adding a new Area to the Web Application the Links on the _Layout.cshtml for the About and Contat works fine, but for the Home Page Url generated it would point to the Index file of the Area (/Sample/Index) and not to the Index file in the root folder (/Index).

The Identity RCL seems to work fine, since you can click on the Login Link and then click back to Home. But on other areas it won't work as expected.

### To Reproduce
1. Create an ASP.Net Core Web Application
2. Add a folder in the Areas folder
3. Add a Pages folder to that folder
4. Add a _ViewStart.cshtml for setting the Layout to "_Layout"
5. Add a _ViewImports.cshtml for setting the namespace for the folder
     @namespace ApplicationName.Areas.Pages
6. Add an Index.cshtml file

or Pull this sample project https://github.com/jlchavez/WebPx.Sutz

### Expected behavior
Home Page Link ("/Index") should always point to the home page of the app, from any page in the application.

### Screenshots
Structure of the "new" Site...
![image](https://user-images.githubusercontent.com/10183621/51278977-afb7d400-19a1-11e9-86e3-cc0d97d09c86.png)

Links on the _Layout.cshtml file
![image](https://user-images.githubusercontent.com/10183621/51279013-c827ee80-19a1-11e9-8ff4-67d08e97b8b5.png)

Html Output Generated
![image](https://user-images.githubusercontent.com/10183621/51279030-d413b080-19a1-11e9-9c05-04d78a03d09d.png)

### Additional context
Window 10, Visual Studio 2017 15.9.4 with ASP.NET Core 2.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jlchavez.
In order to make this work, you have to explicitly add `asp-area=""`  to the tag helper, as it's done at: https://github.com/aspnet/AspNetCore/blob/release/2.1/src/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Views/Shared/_Layout.cshtml#L33
