### ISSUE TITLE
AzureADB2C(Note: case-sensitive)

### ISSUE THREAD

**Issue by JipingWang** [aspnet/AspNetCore#6773]
Noticed default changed from "AzureAdB2C" to "AzureADB2C". Could you add a Note somewhere in the document. This caused a big trouble not realizing two are different. 

### Note: configuration keys are case-sensitive (only in appsettings.json ?)
if you have configured "AzureAdB2C" for some applications before, be ware that the new default scheme name is "AzureADB2C".

**Comment by Eilon** [comment]
Hi @JipingWang , can you provide info on where the "default changed"? Was this in a project template? Or somewhere else?

**Comment by JipingWang** [comment]
@Eilon , sorry, please ignore. 
The code was not from official repo, but some sample project. (Azure-Samples/active-directory-b2c-dotnetcore-webapp)
