### ISSUE TITLE
[Blazor] Blazor Components to use Shadow DOM elements

### ISSUE THREAD

**Issue by redradist** [aspnet/AspNetCore#6774]
### Is your feature request related to a problem? Please describe.
It is very hard to use external component in application without breaking this component, because of conflicting CSS styles.
Allow to use in Blazor Component Shadow DOM for encapsulating the CSS styles.

**Comment by redradist** [comment]
Actually I event can participate in implementing this feature ...
I just need a hit where to start, where is Browser Render Logic ?

**Comment by redradist** [comment]
@Eilon Hi Eilon and others,

In browsers where Shadow DOM is not yet supported, we can reset all style for particular component with http://html5doctor.com/html-5-reset-stylesheet/ or other reset style-sheet.
We could apply it directly to particular component by assigning to this component Unique Id.

I have made an example [Example of Blazor Component with CSS Style encapsulation in browser which does not support Shadow DOM API](https://www.w3schools.com/code/tryit.asp?filename=FZ0SUFUN7QNG) 

It is pretty easy and I am wondering why it is not yet implemented, 'cause template generator can do it very easily !!

**Comment by rynowak** [comment]
We have no immediate plans to provide encapsulated styling for css, so closing. We may do this in the future, but not as part of this release.

**Comment by tedekeroth** [comment]
This is direly needed: each component should have the option to add its own, specific, encapsulated css, like its possible in Web Components.

**Comment by StevenTCramer** [comment]
@rynowak  This was closed back in March understandable so, but that was a whole 8 months ago now :)

"We may do this in the future" 

So I am wondering if the future is now and we can consider reopening this?
