### ISSUE TITLE
[SignalR] Max Concurrent connection and how to disconnect client from server side

### ISSUE THREAD

**Issue by kenyeung128** [aspnet/AspNetCore#6792]
Hi, we have an application reaching 3000+ concurrent connection and would like to find out what are the max number of concurrent connection that .net core signalr can handle?

also, if there is anyway to disconnect the client from the server side? e.g. disconnect due to client inactivity within a period of time. thanks.

**Comment by BrennanConroy** [comment]
Concurrent connection limits are very dependent on your machine, setup, and workload so it's hard to say "You can have up to X connections" for anyone specifically unless you test on your setup. We do have an issue tracking getting some general numbers in different environments here https://github.com/aspnet/AspNetCore/issues/5311

As for disconnecting clients, you can call `Context.Abort` inside the Hub to kill a connection.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
