### ISSUE TITLE
High Memory utilization in Asp.net core 2.0

### ISSUE THREAD

**Issue by ankitmori14** [aspnet/AspNetCore#6795]
Hi, 

I have created just simple default application still i have't add any piece of code still it is utilizing 354 MB of memory.

Version : Asp.net Core 2.0

![core2 0_test](https://user-images.githubusercontent.com/28730774/51314830-bebc8600-1a76-11e9-8f17-7b33c945c441.PNG)

As you can see in screen shot.
1. Microsoft.CodeAnalysis.PEModule it is utilizing high memory though i am not using any feature of it.
2. Dictionary<String, ValueTuple<Int32, Int32>>	same i am not using this also.

Please help.
Thanks in Advance

**Comment by blowdart** [comment]
Version 2.0 is out of support. You should, at a minimum, upgrade to 2.1 and see if the issue reoccurs. If it does then please open a new issue.
