### ISSUE TITLE
Extending Shutdown Timeout Issue

### ISSUE THREAD

**Issue by mclenney** [aspnet/AspNetCore#6798]
I have a .NET Core 2.1.1 console application I am running in which I have a service that inherits from the BackgroundService class which kicks off a long-running service on a new thread. This service then consumes a scoped service which reads from the database and sends some emails. I am attempting to test my handling of a graceful shutdown of the application but am running into an odd issue in my testing scenario.

In the Program.cs file, I am attempting to increase the shutdown timeout to 20 seconds using:

`.UseShutdownTimeout(TimeSpan.FromSeconds(20))`

After I boot up the application, in my microservice which is called by the BackgroundService, I am attempting to gracefully shutdown the application once I have the thread in a delayed state:

`Log.Information("preparing to sleep thread for 10 seconds");`
`await Task.Delay(TimeSpan.FromSeconds(10));`
`//Thread.Sleep(10000);`
`Log.Information("thread awake");`

What I'm finding, is that once I start the shutdown by closing the console application, the shutdown is only delayed by 5 seconds at most because of the default timeout, but not the 10 seconds that I would expect.  Found this information on an [MSDN Blog Article](https://blogs.msdn.microsoft.com/cesardelatorre/2017/11/18/implementing-background-tasks-in-microservices-with-ihostedservice-and-the-backgroundservice-class-net-core-2-x/)

**Comment by anurse** [comment]
Can you provide a sample project that illustrates the problem? Also can you clarify exactly how you are terminating the console application (by pressing Ctrl-C?)

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
