### ISSUE TITLE
High Memory utilization in Asp.net core 2.2

### ISSUE THREAD

**Issue by ankitmori14** [aspnet/AspNetCore#6831]
Hi,

I have created just simple default application still i have't add any piece of code still it is utilizing 167 MB of memory.

Version : Asp.net Core 2.2

I am using Hosting Model : Default.

![core2 2_blank_sol](https://user-images.githubusercontent.com/28730774/51368575-034b2e80-1b16-11e9-92bf-508ee522f916.PNG)

My blank application is also using 167 MB of memory .

As you can see in screen shot.

1. Microsoft.CodeAnalysis.PEModule it is utilizing high memory though i am not using any feature of it.
2. Dictionary<String, ValueTuple<Int32, Int32>>	same i am not using this also.

Please help my application is dying in production or i should move to .Net Framework
thanks in advance

**Comment by ankitmori14** [comment]
> This looks like an expected behavior if you have more than 256MB of memory and are running with one code.
> 
> How much memory is available on the server?
> 
> > my application is dying in production
> 
> Can you be more specific?

we have 32 GB of memory.

**Comment by ankitmori14** [comment]
> Also please read this thread: #3409
> Thanks

Yes i have go though this article. Can i share anything which can help you to troubleshoot the issue.

**Comment by sebastienros** [comment]
I don't think there is any issue with the behavior, what you are describing is by design.

You can use the Workstation GC mode if you don't want the GC to be gready.
