### ISSUE TITLE
Question: using Material Design Lite with Blazor

### ISSUE THREAD

**Issue by simonziegler** [aspnet/AspNetCore#6835]
Hi, I'm looking to start building a Blazor Server Side app in preparation for the release of Razor Components, and from a UX design standpoint want to use Material Design Lite. 

When I place (purely as a test!) an MDL button before the `<app>...</app>` block I find that the MDL ripple effects work well. When I place the same code inside a Blazor page (e.g. Index.cshtml in the demonstration app), the ripple effect from javascript calls to the MDL material.min.js cease to work, and also the button raises to a higher level (i.e. gets lots of shadow).

Is there a way to fix this please?

Demonstration: https://blazormdlcomponenttest.azurewebsites.net/
Code: https://github.com/simonziegler/BlazorMDLComponentTest

**Comment by simonziegler** [comment]
Thanks @rjmr97. For now I'm setting this aside while I work out what to do.

**Comment by mkArtakMSFT** [comment]
Closing as external.
