### ISSUE TITLE
Stronger Prevention of Brute Force Login Attempts

### ISSUE THREAD

**Issue by HockeyJustin** [aspnet/AspNetCore#6836]
### Is your feature request related to a problem? Please describe.

As a developer, I would like a stronger inbuilt way to protect my website from brute force login attacks in  order to help meet requirements of the [OWasp Security checksheet](https://www.owasp.org/index.php/.NET_Security_Cheat_Sheet).

This microsoft document details how to use [lockouts to prevent brute force attacks](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.1#account-lockout-for-protecting-against-brute-force-attacks), however this only solves part of the problem.

As detailed in this [post](https://stackoverflow.com/a/54250737/852806), it will prevent someone doing

    username: user1@test.com, password: Password121
    username: user1@test.com, password: Password122
    username: user1@test.com, password: Password123

But it won't prevent someone doing:

    username: user1@test.com, password: Password123
    username: user2@test.com, password: Password123
    username: user3@test.com, password: Password123

This could lead to a massive spamming of one's website.

### Describe the solution you'd like

As detailed in the [OWasp security checksheet](https://www.owasp.org/index.php/.NET_Security_Cheat_Sheet), .NET (Framework) has the attribute `AllowXRequestsEveryXSecondsAttribute`, which stops repeating requests from one source e.g. 

`[AllowXRequestsEveryXSecondsAttribute(Name = "LogOn", Message = "You have performed this action more than {x} times in the last {n} seconds.", Requests = 3, Seconds = 60)]`

It would be great if .NET Core could have something similar.

### Describe alternatives you've considered

I am unsure of the alternatives with .NET Core. Maybe a strict CORS policy?

### Additional context

N/A

**Comment by Eilon** [comment]
@blowdart

**Comment by blowdart** [comment]
AllowXRequestsEveryXSecondsAttribute is not built into MVC, OWASP has worded that wrong, instead its from the [3rd party](https://github.com/johnstaveley/SecurityEssentials/blob/master/SecurityEssentials/Core/Attributes/AllowXRequestsEveryXSeconds.cs) they link to. That should be transferable to Core.

I'm going to fall back to saying identity is meant as a simple starting point. For very strong security I'd suggest looking at dedicated identity providers, be it AAD, AAD B2C or Auth0. That's their entire business, and we as a framework have to balance features against demand.

I'll drop this in the backlog, but a requests per second attribute isn't a good answer.

**Comment by HockeyJustin** [comment]
@blowdart - thanks for the response. 

In these days where clients are (rightly) getting more security conscious, pen tests are becoming increasingly common. Brute force attacks are fairly simple to attempt.

I'll look into the options mentioned.

Thanks again. J
