### ISSUE TITLE
NodeInvocationException: Extra line break is added in exception message

### ISSUE THREAD

**Issue by RoboBurned** [aspnet/AspNetCore#6837]
### Describe the bug
I am trying to play with Microsoft.AspNetCore.NodeServices.
When JS script ends executing with an error by passing error message as a first argument to callback function then NodeInvocationException  is raised on NET side with a message that have extra line break added to the end of the message.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Run this code
```
function calc(callback, a,b) {
	var res = a + b;
	callback('123', res);
	return res;
};
module.exports = {
	calc: calc
};
```
```
nodeInstance.InvokeExportAsync<int>("index.js", "calc", 1, 2).GetAwaiter().GetResult();
```
NodeInvocationException with Message = "123\r\n"

### Expected behavior
Exception Message is "123" with no line breaks.

### Screenshots
![image](https://user-images.githubusercontent.com/14316268/51392024-3361f400-1b4d-11e9-92fe-836fec6ccd5f.png)

### Additional context
The line break is added by NodeInvocationException constructor.
I think the issue can be fixed by checking the details argument for null.
```
class NodeInvocationException : Exception
{
	public NodeInvocationException(string message, string details)
		: base(details != null
				? message + Environment.NewLine + details
				: message)
	{
	}
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RoboBurned.
This is not an area of active investment at the moment. We would, however, happily consider a PR, if you're up to it.
