### ISSUE TITLE
Consider obsoleting startup/shutdown time limits on InProcess

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#6839]
We should be covered by applicationPools limits for InProcess case.

https://docs.microsoft.com/en-us/iis/configuration/system.applicationHost/applicationPools/add/processModel 

@shirhatti

**Comment by muratg** [comment]
Would this be usable in App Service?

**Comment by pakrym** [comment]
I'll have to verify if there is an interest in dropping these but I'm pretty sure it does.

**Comment by anurse** [comment]
We should remove this logic from the in-proc code paths. Filing a new bug to track some doc updates (which can include comparing the config options that are relevant to each mode)

**Comment by anurse** [comment]
Investigate if we hit fast failure protection because of this issue. If we trigger WAS timeouts instead of our own timeouts we should revisit this.

**Comment by anurse** [comment]
Triage decision: We decided this isn't an important scenario for us right now.
