### ISSUE TITLE
git clean deletes ts client

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#6845]
`git clean -xdf` keeps deleting `src\SignalR\clients\ts\signalr` and `src\SignalR\clients\ts\signalr-protocol-msgpack`

Repro steps:
- `build /t:restore` (runs npm install)
- `dir /al /s` (shows those folders as hard junctions from `\src\SignalR\clients\ts\FunctionalTests\node_modules\@aspnet`)
- `git clean -xdf` (those folders get deleted)
- `git status` (git shows those folders as deleted)

This happens because we've configured a junction between `src\SignalR\clients\ts\FunctionalTests\node_modules\@aspnet\signalr` and `src\SignalR\clients\ts\signalr` (how?) and `node_modules/` is in the `.gitignore` file. When git clean clears the node_modules dir it follows the junction and deletes the client as well.

Proposal: can we populate the `node_modules\@aspnet\signalr` folder via some other mechanism besides using a junction? E.g. manually copy the files?

Open question: Where is this junction configured? Is it this?
https://github.com/aspnet/AspNetCore/blob/89a7f3cf774d46eaaea26861744a224a6487f31c/src/SignalR/clients/ts/tsconfig.base.json#L21-L28

@davidfowl @BrennanConroy @anurse

**Comment by BrennanConroy** [comment]
Oh nice! Thanks for getting a repro, we have occasionally seen this but never knew how it happened. I don't think the tsconfig has anything to do with creating a junction, it's supposed to tell the typescript compiler where to grab certain imports from.
________________________________

**Comment by natemcmaster** [comment]
https://github.com/aspnet/AspNetCore/blob/c2a0f894482895aa5af6e80dafa1e22724d5bd8f/src/SignalR/clients/ts/FunctionalTests/package.json#L7-L9

**Comment by muratg** [comment]
@BrennanConroy I think we should look into removing symbolic link usage :(

**Comment by muratg** [comment]
@anurse I was thinking that we could do dependencies differently. Perhaps not possible, but I thought there could be a way. Multiple people keep hitting this on Windows unfortunately. It's easy to revert but it's definitely a nuisance.

**Comment by natemcmaster** [comment]
Does `yarn` have a solution for this?

**Comment by bradygaster** [comment]
@natemcmaster do you think a mitigation possibility could be that we move the TS client out of the mondo repo and begin the process of separating the non-.NET SignalR clients into their own repositories somewhere else? If that would mitigate here, we could start talking about doing it soon.

**Comment by natemcmaster** [comment]
The same problem would apply in a new repo too. The problem is a combination of the way npm on windows does “File:/” dependencies and a bug in git-for-windows. Moving to a new repo doesn’t solve either of those problems.

**Comment by Tratcher** [comment]
@natemcmaster but it does reduce the number of people affected by it, and if you're planning to separate the clients anyways...

**Comment by BrennanConroy** [comment]
Moving to a new repo solves the problem of everyone complaining. Only a couple people will hit the issue if we move it, and we can ignore it.

**Comment by muratg** [comment]
IMO, let's not jump to a "new repo" solution just yet. I'd rather have simplified build infra with less repos. Even if it means we can't solve this fully.

**Comment by anurse** [comment]
> Does yarn have a solution for this?
 
Maybe. Worth a shot. The biggest place this is used is in the Functional Tests and they use WebPack. We should probably use a standard version reference instead of a path reference and then use the WebPack config to redirect to the local path.

**Comment by ryanbrandenburg** [comment]
Any chance our new usages of yarn make this simpler? It's always very annoying when I run into this.

**Comment by natemcmaster** [comment]
Yarn does the same thing npm does— symlink a directory— so no. Problem still exists.

**Comment by anurse** [comment]
I just had a crazy idea. This occurs because `git clean` cleans the `node_modules` folder in SignalR, including things like `node_modules/@aspnet/signalr`, which is just a junction to the actual source directory. Git cleans through the link and that wipes everything out.

Given that, the solution is actually super simple. Add `node_modules/@aspnet/signalr` (and `node_modules/@aspnet/signalr-protocol-msgpack` to the `.gitignore` as **unignored** ;):

```
!node_modules/@aspnet/signalr
!node_modules/@aspnet/signalr-protocol-msgpack
```

We could do this just in the `src/SignalR` directory. That would mean that the `node_modules` directory in those folders hangs around after a clean but it only keeps the symlinks, which is _fine_.

@BrennanConroy could you see if this fixes the issue? If so, let's do it. (cc @Tratcher @aspnet/build)

**Comment by BrennanConroy** [comment]
We would need to commit the symlink folders otherwise they would probably appear in `git status`

**Comment by dougbu** [comment]
either way, I likes it 😃

**Comment by anurse** [comment]
@BrennanConroy true, but the files themselves are already committed anyway so it might just work? There could be a recursion issue though since I think the `node_modules` folder is still under there... Beware when trying this out @BrennanConroy, you might hang git ;).

**Comment by BrennanConroy** [comment]
Tried various incantations of the above but couldn't get it working

**Comment by anurse** [comment]
Back to the drawing board I guess :(.

**Comment by anurse** [comment]
There is an issue tracking this in git for windows and it seems like there's a possibility it will be fixed https://github.com/git-for-windows/git/issues/607

**Comment by anurse** [comment]
Pushing this out since we still couldn't get it to work... Maybe we should just switch to Subversion :trollface:

**Comment by Tratcher** [comment]
@dougbu `clean.cmd` deleted the ts client again. Seems like the exclusion didn't work?

**Comment by dougbu** [comment]
@Tratcher I don't understand what's happening here. Directly running the `git` command causes something similar and `git reset --hard` only restores exactly that `node_modules` folder. Worse, the behaviour isn't 💯% consistent.

My only thoughts are:
1. Try a more general exclusion e.g. `-e node_modules/` and combine that with specific `Remove-Item` commands
2. Remove the exclusion entirely but add `git reset --hard HEAD` to the script

What think you?

**Comment by Tratcher** [comment]
The exclusion is relative to the current directory. Is the redirect to ps1 messing with that? Or does this repro running the ps1 directly?

**Comment by dougbu** [comment]
The redirect to the .ps1 file doesn't make any difference. I've seen issues when running the script or the `git` command in the repo root. And, only users make any use of this script -- it's not part of any automation.

**Comment by anurse** [comment]
One thing we could consider doing is not using a link at all and actually directly packing a `.tgz` and installing it in the dependent projects. The junction point just creates all kind of problems it seems...

**Comment by dougbu** [comment]
Found a reasonable way. See #12281

**Comment by anurse** [comment]
I wouldn't call that a fix, but it's a reasonable stop-gap. We shouldn't close this work item based on that, but I will be moving this out from preview 8.

**Comment by dougbu** [comment]
@anurse what is your preference over what was in d641dffdc1? That may be a workaround but it's reliable.

**Comment by anurse** [comment]
My preference is that `git clean` not delete the TS files. Getting people to use a non-standard clean command (particularly external contributors) isn't really a suitable long-term solution IMO. I agree it's the best we've got right now though.

**Comment by Tratcher** [comment]
In other words, keep this open and move it to the backlog.

**Comment by dougbu** [comment]
Thanks for your perspectives and for unassigning me 😺

**Comment by Tratcher** [comment]
Fixed !
