### ISSUE TITLE
Default values for component parameters get overwritten

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6864]
- Create a new Razor Components app
- Add a parameter to the `Counter` component with a default value of 1

    ```csharp
    [Parameter] int IncrementAmount { get; set; } = 1;
    void IncrementCount()
    {
        currentCount+=IncrementAmount;
    }
    ```

- Run the app and try the Counter on the Counter page

Expected result:
- Counter increments

Actual result:
- Counter doesn't increment - stays at zero
- The IncrementAmount parameter was overwritten to zero

**Comment by pranavkm** [comment]
@danroth27, I tried this out with a blazor application, and I see the same outcome. Moving this out to preview3 so we can figure out what the right behavior needs to be.

@SteveSandersonMS, thoughts on what the behavior should be here? ParameterCollection [goes out of it's way](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/ParameterCollectionExtensions.cs#L77-L92) to ensure all parameters get initialized with a value. Is there a reason we don't rely rely on the language to initialize the type to the right value?

**Comment by danroth27** [comment]
@pranavkm This works in Blazor 0.7.0 and and has worked from pretty much the first release of Blazor. This is one of the first scenarios that Blazor users try out when [getting started with Blazor](https://blazor.net/docs/tutorials/build-your-first-blazor-app.html#component-parameters). If this was regressed in the latest update to Blazor it needs to be addressed.

**Comment by RemiBou** [comment]
@pranavkm the code you are seing was made to handle when navigating in the same page  : on a page with this route "/index/{id}" when going from "/index/123" to "/index" the parameter "id" should be set to its default value, just like it would when accessing directly to "/index"

Maybe we could apply this only to parameters from url, but there is no way, yet, to make a difference between route parameter and attribute parameter.

**Comment by RemiBou** [comment]
@SteveSandersonMS maybe splitting Parameter in two concept : the parameter from routing and the parameter from attribute ? I think  it'll be easier to understand as it unusual to have both of them behind the same concept (angular uses ActivatedRoute and @Input() for instance, react uses props and match). So we could ignore the setting of default parameter for the attribute. 

This would mean splitting the property initializaition in two part but it would improve the performance as well because the attribute parameter doesn't need to be updated on route change and route parameter doesn't need to handle cascading. I hope I'm clear enough.

**Comment by RemiBou** [comment]
Yes indeed it difficult (There is some odd solution on SO https://stackoverflow.com/a/48190076/277067 but I don't think it's a good idea).

But the code that reset the parameter to the default value (the code @pranavkm found) would not be called for attribute parameters, only for route parameters. For route we can use the DefaultValueAttribute if someone want to set a different value than default().

**Comment by pranavkm** [comment]
> For route we can use the DefaultValueAttribute if someone want to set a different value than default().

We could use this approach and use the analyzer to flag initialization of parameters.

**Comment by danroth27** [comment]
@SteveSandersonMS  and I discussed this and we agreed to revert to the old behavior for default parameter values for preview2. We'll need to revisit the client routing scenario in preview3.
