### ISSUE TITLE
What are the limitations on background tasks with hosted services?

### ISSUE THREAD

**Issue by vankampenp** [aspnet/AspNetCore#6874]
The IHostedService interface is described here: 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2

I was told here by @Tratcher  that a background task should not access HttpContext. 

When implementing a QueuedHostedService I assume this is also true. Also disposable objects should not be passed to the queue, including anything that comes through DI. Is this correct? 

It would be good to have some guidance on the pitfalls.

**Comment by Tratcher** [comment]
A hosted service would have no direct access to any HttpContext instances. You could technically schedule request related work to such a queued hosted service, but you'd have to take great care to ensure that work was linear and nothing else operated on the request in the meantime.

The disposables question is similar, it's all about lifetime and concurrency. You shouldn't pass objects off to background threads/services that aren't able to honor the lifetime or concurrency guarantees of those objects. If the caller intentionally keeps those objects alive for the duration of the background operation then that's OK. E.g. The request thread passes request resources to a backgound queue, blocks the request from completing (asynchronously), and waits for the queue to perform its operation before continuing.

**Comment by davidfowl** [comment]
Here's some guidance that we;re going to move to the documentation this year:

https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md#do-not-capture-the-httpcontext-in-background-threads

**Comment by vankampenp** [comment]
@Tratcher blocking the request from completing while a background task is running would result in having parallel work done, which is a scenario that could be useful if the foreground task still has a lot to do as well. I think the more general scenario is where you try to reduce the UI response time by not waiting on completion, at least that is what I am doing. I think your remarks would be really helpful in the documentation.

@davidfowl these are great!
