### ISSUE TITLE
[Blazor] CSS inside style tags gets HTML encoded

### ISSUE THREAD

**Issue by MartinF** [aspnet/AspNetCore#6875]
### Describe the bug
Running Blazor 0.7.0.
CSS inside a <style> tag in a Component gets HTML encoded.
For example, when using the direct child selector (.myClass > img etc.) the output ends up being `&gt;` rather than ">"

### To Reproduce
1. Create a new Blazor project with the default template.
2. Open one of the existing components and add a <style> tag and a CSS selector inside using the direct child selector (">" - etc. ".myClass > img").
2. Run the project in your favorite browser
3. Inspect the output

### Expected behavior
Rendered as written - no HTML encoding.

### Screenshots
![capture1](https://user-images.githubusercontent.com/235008/51429474-b8f9a880-1c0e-11e9-8145-6f57e400bf58.PNG)

![capture 2](https://user-images.githubusercontent.com/235008/51429478-c6af2e00-1c0e-11e9-883f-980383b125d7.PNG)

### Additional context
My first thought was that maybe <style> tags in a component are not supported, but haven't been able to find anything about it.
It works fine if it wasn't because of the HTML encoding issue. 
I find it handy being able to include the CSS directly in the Component as it is usually just minor alterations that are needed, which might only be relevant to the component.

**Comment by syedqutub** [comment]
For me the style tag does work in the Components,but when using the @syntax ,css intellisense of the editer breaks

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb can you please validate whether this is fixed already or not?

**Comment by ajaybhargavb** [comment]
Yup this is fixed. Dup of https://github.com/aspnet/AspNetCore/issues/6185
