### ISSUE TITLE
Update Blazor (ASP.NET Core Hosted) project template so that it is easy to toggle between client-side and server-side Blazor

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6882]
The work that remains here is to break up `UseBlazor` into more parts so that it looks similar to the patterns for server-side.

**Comment by StevenTCramer** [comment]
@rynowak  looks like you are going this direction. (One configuration for both client and sever side)

https://github.com/TimeWarpEngineering/blazor-state/blob/master/test/TestApp/TestApp.Client/wwwroot/BlazorDualMode.js

Gives the ability to select client-side or server-side Blazor at run-time without recompiling.

https://github.com/TimeWarpEngineering/blazor-state/blob/master/test/TestApp/TestApp.Server/Startup.cs

This allows the same server to handle either type of client.  The default usage is first visit the client operates server-side second-visit when all is cached it switches to client side.   But all kinds of logic could be put in this to determine dynamically where is the best user experience.

https://thefreezeteam.com/razor-components-dynamic-dual-mode/

This is a very nice use case that I just hope we can maintain :)

**Comment by Andrzej-W** [comment]
Will this enable server side prerendering for Blazor Client Side app?

**Comment by MaherJendoubi** [comment]
I am facing the following regression after using this updated template https://github.com/ElectronNET/Electron.NET/issues/277
