### ISSUE TITLE
Make Razor Components project template a single project and update to use .razor

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6883]
Update the Razor Components template to be a single project, so that it is a simpler starting point for a Razor Components app.

We will also update the Blazor (ASP.NET Core Hosted) template to be easily toggled between client-side and server-side Blazor, for folks that want to be able to switch between the two: https://github.com/aspnet/AspNetCore/issues/6882

As part of this work, we also need to change the Razor components in template to `.razor`.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, I've updated the description to include this:
> As part of this work, we also need to change the Razor components in template to `.razor`.
