### ISSUE TITLE
Razor Components namespace cleanup

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6884]
The Razor Component template currently pulls in the following two namespaces in `_ViewImports.cshtml`:

```
@using Microsoft.AspNetCore.Components.Layouts
@using Microsoft.AspNetCore.Components.Routing
```

We should clean up these namespaces so that these `@usings` are not required by default.

**Comment by javiercn** [comment]
@danroth27 Is the proposal to move the required types to `Microsoft.AspNetCore.Components` 
/cc: @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
Possible ways to solve this:

 * Move everything into one namespace
 * Add the `.Forms`/`.Layouts`/`.Routing` imports into the default compilation so they are there implicitly without needing to show up in any user code

I'm not set on either solution. Though I do have some concerns about "put everything in one namespace". The layering as it is keeps "forms", "layout", and "routing" sufficiently separate from everything else that they could be implemented in a different assembly, or even purely in userspace code. Fusing everything together would work against that clarity.

**Comment by rynowak** [comment]
I think it's worth the discussion and consideration, but I don't agree with the premise of this issue without more justification. It's a non-goal to have the template be *minimal*, it's a goal to have the template by *meaningful*. ie: we should know that everything in the template is there for a a reason.

To me the most important pivot is whether or not we want to give users the obvious ability to use an alternative for names like `Router` or `EditForm`. Moving something into the `Microsoft.AspNetCore.Components` namespace, or adding the namespace to the built-in set of `@using`s is a gigantic hammer. There's no gesture to *un-reference* something brought in by the prelude (the implicit`_Imports.razor`) - you have to fully-qualify or alias those names forever.

Of these, I'm not sure why `.Routing` is imported in view imports. It seems wholly appropriate to put this `@using` in the `App` component. For layout, I mostly feel the same way, I'm not sure why we'd change anything. 

Forms seems like it should be an explicit `@using` in the template.

**Comment by rynowak** [comment]
I also want to mention that these topics always make me miss Java a bit. In Java, namespaces/packages are largely just done for you by the IDE because you usually have an `import` for every type.

The IDE will collapse all of the `import` directives, and manage them for you. It's there you so you have control over what name maps to what type, and with a modern IDE it doesn't require much thought, and it's not in your headspace because you don't ever look at them.

**Comment by javiercn** [comment]
Based on this I would suggest we don’t do anything here and leave them in the viewimports.

**Comment by SteveSandersonMS** [comment]
> Of these, I'm not sure why `.Routing` is imported in view imports. It seems wholly appropriate to put this `@using` in the `App` component

You'd also need to import it in `NavMenu`, because it references `NavLinkMatch.All` (the enum entry). 

> Based on this I would suggest we don’t do anything here and leave them in the viewimports.

Sounds good to me.

**Comment by rynowak** [comment]
> You'd also need to import it in `NavMenu`, because it references `NavLinkMatch.All` (the enum entry)

So then it's worth a thought right.... once component name-binding is based on `@using` - do we want `NavMenu` to be in scope everywhere, or would we add `@using ... ` to the layout for `NavMenu`?

We have to think through these things for all of the built-in components. 
.

**Comment by mkArtakMSFT** [comment]
Closing as it seems we are in agreement here regarding that it's ok to leave it as is.
@rynowak, if you feel that there is something we still need to revisit, please open a specific issue.
