### ISSUE TITLE
Figure out a way to allow configuring SignalR settings on the client.

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6887]
The current SignalR connection on the client is set up to print info logs, but this isn't required in the general case. However it would be useful to retain the ability to configure the log level among other things, in the event the user's attempting to debug connection issues on the client.

---------------------------------------
## Original issue report

When running a Razor Components app you see the following log output in the browser console.

```
Information: Normalizing '_blazor' to 'http://localhost:58443/_blazor'. - components.server.js:16 
Information: WebSocket connected to ws://localhost:58443/_blazor?id=EQLp2HObPNphy4UacPN7Jw - components.server.js:16 
Information: Using HubProtocol 'messagepack'.
```

We should investigate why we are logging Information level messages by default and how a user would change the log level.

**Comment by davidfowl** [comment]
It’s coming from SignalR @BrennanConroy

**Comment by sven5** [comment]
How to change the log level?

**Comment by stsrki** [comment]
I'm trying to update my components libraries to the new RC 3.0 preview. When I start the app it does not show. The pnly thing that I get are this messages in the console

```
Information: Normalizing '_blazor' to 'http://localhost:8211/_blazor'.
content.js:5 --------init----------- http://localhost:8211/
components.server.js:16 Information: WebSocket connected to ws://localhost:8211/_blazor?id=LzFpPrbHiuZQl2XwAKZbVg
components.server.js:16 Information: Using HubProtocol 'messagepack'.
```

I really don't see what is wrong, basically I have updated all my project files according to the default Razor Components app. Can you guys point what can I do?

**Comment by sven5** [comment]
@stsrki 
Have already looked at the output of ASP.NET Core Web Server in Visual Studio? Or run with the debugger in Visual Studio (just hit F5).

**Comment by stsrki** [comment]
I'm just starting it without debugging(CTRL+F5). There is nothing unusual in the output window.

I just saw this in the [blog post](https://blogs.msdn.microsoft.com/webdev/2019/01/29/aspnet-core-3-preview-2/)

> In this preview release ASP.NET Core Razor Components don't yet support using static assets in component libraries, so the support for component class libraries is pretty limited. However, in a future preview we expect to add this support for using static assets from a library just like you can in Blazor today.

Could be the reason why it's not working as I have some js and css files in the component library projects.

**Comment by mkArtakMSFT** [comment]
@BrennanConroy can you please share details regarding how to control this? Also, we'd like to disable the default to not have these logs by default.

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.2&tabs=dotnet#configure-logging
I don't know how razor components handles things but they can just pass a different log level in.

**Comment by sven5** [comment]
In Razor Components, the client connection is established here:https://github.com/aspnet/AspNetCore/blob/33839dc66a9e6eb730e22e7b6d9d381bcf7b4779/src/Components/Browser.JS/src/Boot.Server.ts#L44-L49
There should be a way to control the client log level from outside, i.e. in the options of `RazorComponentsApplicationBuilderExtensions`
