### ISSUE TITLE
IHostingEnvironment object gets a difference in path

### ISSUE THREAD

**Issue by netnr** [aspnet/AspNetCore#6890]
![1628552182](https://gs.zme.ink/2019/01/20/1628552182.png)

![1630334e4b](https://gs.zme.ink/2019/01/20/1630334e4b.png)

In the Linux system, the dotnet is started in different paths. The WebRootPath attribute of the IHostingEnvironment object is different from the ContentRootPath attribute. The dotnet startup path is obtained. Shouldn't it always be the path of the site directory?

CentOS7
dotnet --version 2.2.103

Code
https://github.com/netnr/test/blob/master/src/Netnr.Test/Controllers/PathController.cs

**Comment by John0King** [comment]
This is not a bug, It designed like this ,
the `dotnet ***.dll` start the app in the Terminal‘s current workDirectory (this will be the `ContentRootPath`)
and the `WebRootPath` is equal to `ContentRootPath + '/wwwroot'`

So in your first picture,  the `ContentRootPath` is your workingDirectory and it can not find `/wwwroot` folder in it ,So `WebRootPath` is not point to `wwwroot`

**Comment by netnr** [comment]
If I want to upload an image to wwwroot/upload/image, how do I locate it? WebRootPath should be fixed to the wwwroot directory.

**Comment by davidfowl** [comment]
The WebRootPath ends up being null when it doesn't physically exist. If you create the wwwroot folder then it'll show up.

**Comment by netnr** [comment]
Thank you very much, I already understand; but I still think that the WebRootPath property should always point to wwwroot

**Comment by davidfowl** [comment]
And the WebRootFileProvider will remain null?

**Comment by anurse** [comment]
This behavior is by design and we have no plans to change it.
