### ISSUE TITLE
SignalR connection.invoke should reject promise in case of error

### ISSUE THREAD

**Issue by zdila** [aspnet/AspNetCore#6902]
### Describe the bug
We are using NodeJS library `@aspnet/signalr`. If server throws exception on `connection.invoke` then we see uncaught exception in JS console instead fo rejecting the promise with error.

### To Reproduce
1. Using this version of ASP.NET Core '...' - `"@aspnet/signalr": "1.1.0"`
2. Run this code '....'
    `connection.invoke('Foo').then(console.log).catch(console.err);`
3. ~~With these arguments '....'~~
    `Error: Failed to invoke 'Foo' due to an error on the server. HubException: Method does not exist.`
    (note that this does not come from `catch`)

### Expected behavior
`catch` should be called with error

**Comment by BrennanConroy** [comment]
I believe the error is coming through the `onclose` callback and since you haven't added a callback it will be an uncaught exception.
________________________________
