### ISSUE TITLE
Publish InMemoryUserStore as part of the Identity namespace

### ISSUE THREAD

**Issue by yetanotherchris** [aspnet/AspNetCore#6903]
### Is your feature request related to a problem? Please describe.
Mocking a `UserManager` is unwieldy, or with NSubstitute impossible. Opening up `Microsoft.AspNetCore.Identity.InMemory.InMemoryUserStore` and related classes will making mocking and testing services, controllers and so on with a dependency on a `UserManager` a lot easier.

https://raw.githubusercontent.com/aspnet/AspNetCore/master/src/Identity/test/InMemory.Test/InMemoryUserStore.cs

### Describe the solution you'd like
In the tests part of the `Identity` folder there is an `InMemoryUserStore`. Add this as a first-class citizen in the Identity project instead of hiding in the unpublished `Microsoft.AspNetCore.Identity.InMemory` namespace.

So essentially move the relevant classes in that folder up a level, into the https://github.com/aspnet/AspNetCore/tree/master/src/Identity/Core/src folder

### Describe alternatives you've considered
A standalone Nuget package would work, but would be cumbersome to keep up-to-date.

**Comment by blowdart** [comment]
If we make things public we have to support them. This is not something we have time to design properly and support. So no, I'm afraid this is a not right now.
