### ISSUE TITLE
Response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase is not working in .net core 2.0 above versions

### ISSUE THREAD

**Issue by synckarthik** [aspnet/AspNetCore#6905]
# Issue Title

Response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase is not working in .net core 2.0 above versions

# General

We used the html upload box in our project. While upload fails, we will pass the custom message through httprequest to client side.  Our server side section is in .net core project (2.0).  So we have used the below code to send custom message

**Response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = "File already exists.";**

It working fine.

While using the above code in .net core 2.1 project, it does not works.

How to resolve this in our side? Please suggest your ideas.

**Comment by khellang** [comment]
Which server are you using? Can you show a dump of the response?

**Comment by synckarthik** [comment]
Hi Guys,

I have attached the sample for HTML 5 uploader with xmlHttpRequest to send the form data. 

Steps to reproduce: 

Run the sample and select any file. Then click on uploadFile button,. Your file will be uploaded in to wwwroot folder now.
Upload the same file again, you will receive the custom message which we sent from server end 'File Already Exists' in load event.

But message jot received in dotnet core 2.1 project.

**Below you can get 2.0 project.**

[UploaderDotNetCore2Point0.zip](https://github.com/dotnet/core/files/2786412/UploaderDotNetCore2Point0.zip)


**Below you can get 2.1 project.**

[UploadDotnetcore2Point1.zip](https://github.com/dotnet/core/files/2786413/UploadDotnetcore2Point1.zip)

Please check it.

**Comment by anurse** [comment]
I can't repro this in 2.1 as long as I'm using Kestrel directly. If you are using IIS, then the custom reason phrase does not appear in **both** 2.0 and 2.1. Which server are you using?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
