### ISSUE TITLE
OnTextChanged in Repeater triggered for every textbox with value within the repeater on first call

### ISSUE THREAD

**Issue by stradigy** [aspnet/AspNetCore#6907]
### Describe the bug
On the first call of an OnTextChanged event of a TextBox in a Repeater, all textboxes with a value in the repeater are calling the OnTextChanged function (not only the concerned textbox control)

### To Reproduce
1. Using this version of ASP.NET Core '4.5.2'
2. Run this code:

ASPX Page:
------------

<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="TestEnvironment.Default" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
   <title></title>
</head>
<body>
<form id="form1" runat="server">
<table>
	<thead>
		<tr>
			<th>
                        	<p><asp:LinkButton ID="lbt_Label" runat="server" >Valeur</asp:LinkButton></p>
    		        </th>                                                 
		</tr>
	</thead>				
	<tbody>
		<asp:Repeater ID="rpt_Data" runat="server"> 
	                <ItemTemplate>
			        <tr>                                        
		                           <td>
                		                <asp:TextBox ID="uic_MyData" Value='<%#DataBinder.Eval(Container.DataItem, "MyData")%>' runat="server"  OnTextChanged="TextBox1_TextChanged" ></asp:TextBox>                                                                               
		                           </td>                                                       
			        </tr> 	     		
			</ItemTemplate>	                	       
	        </asp:Repeater>							
	</tbody>                        
</table>	
</form>
</body>
</html>

ASPX.CS Page
---------------

using System;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;

namespace TestEnvironment
{
    public partial class Default : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            // Fill with dummy data
            if (!Page.IsPostBack)
            {
                DataTable dtTable = new DataTable();
                dtTable.Columns.Add("MyID", typeof(int));
                dtTable.Columns.Add("MyData", typeof(int));

                // Here we add five DataRows.
                dtTable.Rows.Add(10, 10);
                dtTable.Rows.Add(20, null);
                dtTable.Rows.Add(35, 30);
                dtTable.Rows.Add(45, null);
                dtTable.Rows.Add(55, 50);

                rpt_Data.DataSource = dtTable;
                rpt_Data.DataBind();
            }            
        }
        // -----------------------------------------------------
        // Update repeater textbox value - ontextchanged
        // -----------------------------------------------------
        protected void TextBox1_TextChanged(object sender, EventArgs e)
        {
            TextBox txtBox = sender as TextBox;

            // SHOULD RETURN -ONLY- THE TEXTBOX VALUE FROM THE UPDATED TEXT BOX - NOT EVERY TEXTBOX (WITH VALUE) FROM THE REPEATER ON FIRST CALL
            lbt_Label.Text += ", " + txtBox.Text;            
        }        
    }
}

3. With these arguments '....'
4. See error: label is updated with all values and should be only with textbox value of OnTextChanged control

### Expected behavior
Only the  TextBox value of the triggered OnTextChanged textbox control should call the event "TextBox1_TextChanged". Not every textbox with value (on the first call of "TextBox1_TextChanged" on the page)

**Comment by stradigy** [comment]
ASPX page should contain an:
- asp:LinkButton ID="lbt_Label" runat="server" 
- asp:Repeater ID="rpt_Data"  runat="server"
In the repeater (ItemTemplate):
asp:TextBox ID="uic_MyData" Value='<%# DataBinder.Eval(Container.DataItem, "MyData")%>' runat="server"  OnTextChanged="TextBox1_TextChanged"

(sorry those got deleted from editing to publishing on this thread)

**Comment by davidfowl** [comment]
This is not the repository for WebForms issues. Try reporting this on https://developercommunity.visualstudio.com/spaces/61/index.html
