### ISSUE TITLE
How to Use Razor Components in .NET Core 3 Preview 1

### ISSUE THREAD

**Issue by TheFanatr** [aspnet/AspNetCore#6910]
# Using Razor Components in .NET Core 3 Preview 1
After wondering why there have not been any new Blazor release announcements nor any news on a Razor Components preview, I did some browsing in this repository and others and found that significant progress was being made, but also that no one on the open internet was posting about how to check it out. I promptly dug out my experimental machine and installed .NET Core 3 Preview 1 and as well as Visual Studio 2019 Preview 1 with the ASP.NET Core Development package then launched it, expecting to be greeted by an easy way to make a new Razor Components website. To my dismay, I had to jump through a couple hoops to even get the .NET Core 3.0 option to appear in the project creation dialog, and once I did, I found that the options exposed were identical to the .NET Core 2.1 ones, with no extra indication that any other project type exists. I then started crawling through the .NET Core MyGet Feeds for ASP.NET Core to see if any newer packages were pushed relating to templates; as I found them, I used the .NET Core CLI to have them installed, and even once the list started looking promising, Visual Studio still gave me nothing. I then looked up the Blazor extension in the Visual Studio Marketplace to see if it was compatible with the 2019 prerelease of Visual Studio yet, and to my surprise, it wasn't. I then tried to edit the manifest files in the package to force support, but the VSIX installer wouldn't have it, so I searched for and found a branch in this repository called `blazor-vsix`, which I compiled the `BlazorExtension` project out of and installed it successfully, but it changed nothing. I then tried making a  test Razor Components project via the .NET Core CLI, but it didn't want to compile because it appeared that the tools that usually run pre-compile on the `.cshtml` files were not being activated. At that point I started getting desperate, having already spent hours trying to make even a basic project work, so I downloaded the ASP.NET Core Tooling source and compiled the `RazorExtension` project with a new minor version and tried to install it, to no avail, after which I ended up creating a local extension gallery with a generated atom file in the build output folder in order to force Visual Studio to use the generated file to update the extension. Once I finally installed it, upon clicking on a `.cshtml` file, I was greeted with an error asking for a preview version of the `CodeAnalysis` assembly, after which I gave up. What am I doing wrong?

**Comment by davidfowl** [comment]
Wait for preview2, you can use daily builds by downloading the latest from https://github.com/dotnet/core-sdk#installers-and-binaries. The razor components templates should be in there now. Also you may need to wait for the next preview of vs2019 to get proper tooling support.

cc @rynowak @SteveSandersonMS

**Comment by rynowak** [comment]
>  After wondering why there have not been any new Blazor release announcements nor any news on a Razor Components preview, I did some browsing in this repository and others and found that significant progress was being made, but also that no one on the open internet was posting about how to check it out

We haven't made any announcements because the bits in 3.0.0-preview1 aren't really in a state that anyone can use 😆 - we'll provide instructions for 3.0.0-preview2 and VS 2019 when those things are available.

**Comment by redowl3** [comment]
Any idea when we can expect preview 2?

**Comment by mkArtakMSFT** [comment]
Preview3 is out already :)
