### ISSUE TITLE
dotnet command line argument to terminate remaining build processes that are finished but dont exit

### ISSUE THREAD

**Issue by CreativeHouseDotOrg** [aspnet/AspNetCore#6913]
### Is your feature request related to a problem? Please describe.
I'm am trying to `build` and `publish`... but unfortunately there are hanging processes in Task Manager .NET Core Host that lead to a publish error if i try to `dotnet publish`

### Describe the solution you'd like
I want the Remaining Tasks to close after the build OR publish process has ended.

### Describe alternatives you've considered
Since now i've been terminating them by hand, it would be good to have a `dotnet <command>` to terminate all open .Net Core Hosts that remain.

### Additional context

Here is a Screenshot of the remaining Tasks:

![1](https://user-images.githubusercontent.com/4038603/51504064-f1e87780-1dde-11e9-8ebd-1424a7654113.PNG)

![unbenannt](https://user-images.githubusercontent.com/4038603/51504000-9f0ec000-1dde-11e9-8419-0216e6945290.PNG)

**Comment by davidfowl** [comment]
This issue should be moved to https://github.com/dotnet/cli

**Comment by CreativeHouseDotOrg** [comment]
@davidfowl Hi! 
Do i have to move the issue myself?

**Comment by CreativeHouseDotOrg** [comment]
Nevermind i created a new issue here:
[https://github.com/dotnet/cli/issues/10642](https://github.com/dotnet/cli/issues/10642)

This topic can be closed! Thank you for your time

Kind Regards
