### ISSUE TITLE
MVC action string param null when empty

### ISSUE THREAD

**Issue by shravan2x** [aspnet/AspNetCore#6914]
### Describe the bug
I have an action in my MVC project which works with URLS like `search?q=xxx`. The action definition is:

```
[HttpGet("search")]
public IActionResult ThreadsJson([FromQuery(Name = "q")] string query)
{
    return Json(listOfStrings.Where(x => x.Contains(q)));
}
```

This works well in general, but causes an error when the URL is called with an empty `q` parameter like `search?q=`. In this case, q is `null` instead of an empty string causing the `.Contains` method to fail.

### To Reproduce
1. Using `Microsoft.AspNetCore.App` 2.1.1.
2. Refer above.

### Expected behavior
The q parameter is an empty string.

**Comment by davidfowl** [comment]
Would you expect it to be null if q wasn't in the querystring at all?

**Comment by shravan2x** [comment]
Yeah, I would.

**Comment by LindaLawton** [comment]
in the instance you send `search?q=` i would expect to see `string.empty`.  What would you expect to see if you just send `search`?  I think i would expect it to fail.  

Things start to get even more confusing if you say change the type to `Int`.   There is a difference between a nullable type and a non nullable type as especially with strings.   

    public IActionResult ThreadsJson([FromQuery(Name = "q")] int query)

vs
    public IActionResult ThreadsJson([FromQuery(Name = "q")] int? query)

**Comment by shravan2x** [comment]
I agree that matching querystrings to ASP actions can be a tricky business. But I think a more intuitive approach would be to use something akin to style _specificity_ in CSS. The framework picks the most specific action that meets the given arguments and 404s if none are found.

> in the instance you send search?q= i would expect to see string.empty. What would you expect to see if you just send search? I think i would expect it to not hit the action.

IMO, when you send `search?q=`
1. If a `search` action exists that specifically expects q, you call it with q=null.
2. If no `search` action expects q, but a `search` action exists that doesn't take q, you treat q as an extraneous parameter and call that action.
3. If neither of these exist, 404.

> Things start to get even more confusing if you say change the type to Int. There is a difference between a nullable type and a non nullable type as especially with strings.

When you have `public IActionResult ThreadsJson([FromQuery(Name = "q")] int query)`,
1. If q is explicitly present as a query parameter as is parse-able, use this action. If q is empty or non-parseable, throw a model binding error (or whatever the current behavior is). This is because the function explicitly expects an `int` and it didn't receive a valid one.
2. If q isn't present, 404.

When you have `public IActionResult ThreadsJson([FromQuery(Name = "q")] int? query)`,
1. \<same as above\>.
2. If q isn't present, call this function with q=null.

Of course, ASP can define its own rules of specificity, those above are just some of my own opinions.

**Comment by LindaLawton** [comment]
I just wonder how your issue / suggestion will be effected by [What's Coming in C# 8.0? Nullable Reference Types](https://blog.cdemi.io/whats-coming-in-c-8-0-nullable-reference-types/)

    public IActionResult ThreadsJson([FromQuery(Name = "q")] string? query)

vs

    public IActionResult ThreadsJson([FromQuery(Name = "q")] string query)

I am concerned that changing how things currently work will have to be undone once C# 8 comes.  I am happy to disagree on how `search?q=` should function. I would just worry that the above actions would end up clashing each other.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @shravan2x.
You can initialize `query` to the default `String.Empty` value and that would do it.

**Comment by shravan2x** [comment]
@mkArtakMSFT While that's a workable solution, it forces you to put the query param at the end of the list of arguments since it has a default value. This results in bad code where you can't put important arguments in the beginning without adding default values to every argument the function takes.

I ended up just using
```c#
if (query == null)
    query = "";
```

Altogether, I don't intend to reopen this issue since it adds to your backlog, but I believe there has to be a better solution to this problem.

**Comment by jingrah1** [comment]
@mkArtakMSFT I've found that defining default empty string values under complex query objects seem to be overridden if the mentioned behavior is performed?

Here's our action definition:
`
public async Task<ActionResult<IEnumerable<Company>>> SearchCompanies([FromQuery] CompanySearchQuery search)
`

And here is our query model:
`
public class CompanySearchQuery : ISearchQuery
    {
        [DefaultValue("")]
        public string SearchString { get; set; } = "";

        [DefaultValue("")]
        public string Name { get; set; } = "";

        public Guid? ParentId { get; set; }
    }
`

Whenever something comes in like 'searchString=', we end up with null in that field, regardless of whether we have a default value for that property. Is this intended? It's a bit cumbersome to have to add a check for the property being null to our queries whenever we're adding a new parameter to the search model.

We're using .NET Core SDK 3.0.100 preview 8
