### ISSUE TITLE
Set operations on SignalR groups in IHubContext

### ISSUE THREAD

**Issue by mbashov** [aspnet/AspNetCore#6922]
It is currently possible to call a method on SignalR clients belonging to a group with exception of specific connections using [this method](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/SignalR/server/Core/src/IHubClients%60T.cs#L61) on `IHubClients`. It would be great if set operations on groups were also provided, with methods, for example, to access connections belonging to one group, but not another.

This would be useful, for example, when there is a number of users connecting to a hub who can subscribe to some message feed, and every message should be delivered to all subscribed users, but one user should get additional information with that message. If a subscription means that the subscribed connection is added to a SignalR group, then there is a need to access a set difference between groups to send the generic message to every connection who is subscribed but who is not the special user. Since there is no such method on `IHubClients`, currently this scenario, as far as I understand, requires either abandoning `IHubContext` and hacking with `HubLifetimeManager`, or creation of groups 'everyone-except-this-user' for each user, which is not practical for a large amount of users.

**Comment by mikaelm12** [comment]
Adding the ability to to perform arbitrary filters across users, essentially allowing you to do set operations, has been something that has been discussed since the inception of SignalR. Unfortunately this is something that we haven't seen enough of a demonstrated need for considering the amount of work that would be required to implement it.
