### ISSUE TITLE
SignalR Subscriber client(.NET Core/Angular 4) connected but not received message after few minutes

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCore#6923]
_From @meerajoy4 on Friday, 28 December 2018 05:54:15_

> I have done a signalR application using asp .net core and angular 4.
> using aspnet core signalR version 1.1.0 and @aspnet/signalr 1.1.0 in client side.
> using the Redis backplane (redis_version 1.1.0)
> We are not using groups though just sending messages by connection id.
> after 5 minutes idle js clients stop receiving messages(client already connected but unable to received data).
> need to connect again for recieving message from sever.

Any idea?

_Copied from original issue: SignalR/SignalR#4283_

**Comment by muratg** [comment]
_From @mikaelm12 on Thursday, 03 January 2019 20:00:41_

Sorry it's a bit unclear to me. Are you saying that you're trying to mix using classic asp.net and asp.net core on the server and client, because that will not work.
Or are you just saying that in the past you have used SignalR on asp.net?

**Comment by muratg** [comment]
_From @meerajoy4 on Friday, 04 January 2019 04:27:28_

@mikaelm12 ,am using asp.net core on the server side. Issue is almost similar https://github.com/SignalR/SignalR/issues/4048. In this issue ,its saying about asp.net signalR , but am using asp.net core signalR.

**Comment by muratg** [comment]
_From @muratg on Friday, 18 January 2019 19:35:44_

@meerajoy4 Are you using a backplane? Or the Signalr service? Or neither?

**Comment by muratg** [comment]
_From @nikunj231991 on Saturday, 19 January 2019 08:51:51_

I am using signalR with websockets and facing same issue. In local its works fine but when i will deploy in Azure and also enabling websockets there after some time not receiving signals client side. Also traced all logs server is sending signals but client not receiving. If i restart azure webapp then it will work for 2-3 minute then same issue.
Don't know it is code issue or azure or library.

**Comment by muratg** [comment]
@nikunj231991 There are known limitations with WebSockets and Azure App Service. I recommend using Azure SignalR Service instead for your app.

**Comment by apowell-barfoot** [comment]
> @nikunj231991 There are known limitations with WebSockets and Azure App Service. I recommend using Azure SignalR Service instead for your app.

@muratg I'm wondering what are the limitations of using Web Sockets and Azure App Services? Other than connection limitations, I'm curious of the other limitations you might be suggesting here? 

We are having similar issues of connections disconnections and packet loss in between an .net core 2.2 API and a VuaJs 2 SPA. Using a Redis backplane. We played around with Azure SignalR service and found it quite slow. Maybe just some links to some articles explaining what you're suggesting would be fine. 

Thanks

**Comment by ChrisProlls** [comment]
Hi !
I faced the same problem here ! After deploying to App Service, sometimes the connection stopped from the server side after a few minutes, sometimes it takes an hour or more ...
I found this issues : 
- https://github.com/aspnet/SignalR/issues/2150
- https://github.com/aspnet/SignalR/issues/1179

Any ideas ?
