### ISSUE TITLE
Microsoft.AspNetCore.Mvc, .NetStandard and .NetCore versions

### ISSUE THREAD

**Issue by darrenlewis1985** [aspnet/AspNetCore#6926]
I understand how .Net Standard and .Net Core relate. However, can you please clarify the relationships between versions of packages like Microsoft.AspNetCore.Mvc and .Net Standard and .Net Core. It would appear that the version numbers for Microsoft.AspNetCore.Mvc seems to track against .Net Core but does that mean there are any dependencies between them or not because Microsoft.AspNetCore.Mvc lists .Net Standard 2.0 as a dependency not .Net Core?

For example, if I've got a .Net Core 2.1 application with a project that is using .Net Standard 2.0 and that references Microsoft.AspNetCore.Mvc 2.1.3, what are the implications of updating Microsoft.AspNetCore.Mvc to 2.2.0?

**Comment by davidfowl** [comment]
In 2.1 and 2.2 the Microsoft.AspNetCore.* packages target .NET Standard and also ship in a the Microsoft.AspNetCore.App share framework as part of 2.1 and 2.2. When you're using .NET Core there's no need to reference individual packages, it's redundant and they are basically ignored and the shared framework is used instead.

**Comment by darrenlewis1985** [comment]
Thanks for confirming. I knew System.Net.Http was in the the metapackage but wasn't sure about Microsoft.AspNetCore.* references. It's on our to-do list to switch over to using the metapackage.
