### ISSUE TITLE
SignalR Websocket handshake error

### ISSUE THREAD

**Issue by marvel420** [aspnet/AspNetCore#6930]
Hello .NETCore Community,

We have a weird situation on hand with SignalR.  We are currently using npm @aspnet/signlr version 1.0.4 on our client solution.  We are using .NETCore SignalR nuget package 1.0.4 for our API.  The client connects to the api hub using the code below:

`
var connection = new signalR.HubConnectionBuilder()
      .withUrl(apiSettings.url + "/generichub")
      .withHubProtocol(new signalR.protocols.msgpack.MessagePackHubProtocol())
      .configureLogging(signalR.LogLevel.Information)
      .build();
`

The issue that we are running into is that for some of our clients, the websocket connection comes back stating that "Error during Websocket handshake".  The response code comes back as either 403 or 200. 
Also, when it tries to use fallback transport method of LongPolling that we get Binary Protocol error.

For us internally in the office or many other clients this issue does not apply so I am assuming this has something to do with firewalll or network settings for these clients.  I would appreciate any insights or any suggestions that you guys might have to debug this scenario.

We are currently using Full Framework 4.7.2 in production.

Client uses the following npm packages related to SignalR:
    "@aspnet/signalr": "^1.0.4",
    "@aspnet/signalr-protocol-msgpack": "^1.0.4",
    "msgpack5": "^4.2.1"

API uses following nuget packages for SginalR:
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.4" />
<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="1.0.4" />
<PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.1.1" />

![websocket_error](https://user-images.githubusercontent.com/17169168/51559789-e33aa880-1e50-11e9-99c8-c812642f8995.png)

Thanks
Akash

**Comment by marvel420** [comment]
it might be related but seems like there has been no suggestion as far as where to start to look into.  As far as we know it seems to be related to network based settings per client but that is just a wild guess.  Would appreciate any insight into any other thing to look into.

**Comment by muratg** [comment]
403 is Forbidden. Do you possibly have some auth issues?

Also, can you get some logs for us? https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide

**Comment by bradygaster** [comment]
Which browser are you using when you see the longpolling error above?

**Comment by mamatamathapati** [comment]
I have the same issue, using dotnetcore SignalR and angular. locally it works fine. but when i deploy it to Pivotal Cloud Foundry, we start seeing this issue intermittently.

**Comment by BrennanConroy** [comment]
Hello, we don't track closed issues. If you are seeing a problem please open a new issue with the details and we can try to help.

The more info you include in the issue the easier it will be for us to help out. Here is a document explaining some of the ways to get more info to include in issues https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2
