### ISSUE TITLE
Web templates should not require HTTPS by default on Linux

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6933]
On Linux there isn't a good consistent way to establish trust of the dev certificate like there is on Windows and macOS. To avoid confusing new users on Linux we should not require HTTPS by default on Linux. On Linux you should be able to create a new web project, run it, and browse to the HTTP endpoint for the app (no forced redirect to HTTPS).

**Comment by blowdart** [comment]
No Dan. We should emulate the actual operating environment we expect people to use, even if it does create an extra initial step we can't automate.
