### ISSUE TITLE
UseAngularCliServer fail on .net core 3.0

### ISSUE THREAD

**Issue by tuxy42** [aspnet/AspNetCore#6938]
### Describe the bug
On net core 3.0 preview, Angular template execution fails on exception : 
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to start 'npm'. To resolve this:.
...
See the InnerException for further details of the cause. ---> System.ComponentModel.Win32Exception: Invalid path name

### To Reproduce
- Allow preview version of .net core in Visual studio 2017
- Generate angular template with cli command : dotnet new angular -o angularbase
- Start application in VS (debug or release)

### Expected behavior
spa.UseAngularCliServer(npmScript: "start") should start ng server correctly

**Comment by tuxy42** [comment]
Just additional information, npm is correctly installed and executable correctly referenced in path. With same project if I go back to target framework 2.2 everything is ok.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tuxy42.
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by tuxy42** [comment]
Another information, it's only true when "IIS express" debugging profil is selected, when I select "Project" name profile (self contained webserver I suppose) everything work well.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tuxy42. Given that there have been many changes in Angular template, we think this issue has been addressed. If you feel otherwise, please open it or file a new issue for us to investigate.
