### ISSUE TITLE
Completion for bind attribute value fails to commit

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#6941]
![vlylbszjne](https://user-images.githubusercontent.com/1874516/51573598-e3da3b80-1e5e-11e9-8d2b-5ddac6af7bd6.gif)

Selecting the completion doesn't get committed to the editor

@rynowak

**Comment by danroth27** [comment]
It seems to only repro when the completion list comes up automatically while typing. If I force the completion list to come up by hitting ctrl-space then the completion commits just fine.

**Comment by mkArtakMSFT** [comment]
Closing as this is external.
