### ISSUE TITLE
[Blazor] Mysterious phenomenon of using Math.Truncate in Blazor

### ISSUE THREAD

**Issue by txgz999** [aspnet/AspNetCore#6973]
### Describe the bug
When I use Math.Truncate in the definition of a property used in data binding, a print window pops up

### To Reproduce
Create a Blazor project in VS2017, add a page with the following content:

```
@page "/mathtruncate"

@test

@functions {
    private int test
    {
        get
        {
            // var k = Math.Max(1, 2); // works fine
            var k = Math.Truncate(20d); // a print window pops up
            return 1;
        }
    }
}
```

### Expected behavior
Browse to that page, you would see just content, which is value 1

### Screenshots
![mathtruncate](https://user-images.githubusercontent.com/29514515/51648932-8e7e5700-1f50-11e9-90b9-00c04ce0ed20.png)

### Additional context
Other Math methods such as Math.Max work as expected.

**Comment by rynowak** [comment]
Wow! This is an amazing bug. Can you file this at https://github.com/mono/mono - this is probably an issue in the underlying runtime.

**Comment by txgz999** [comment]
Thanks a lot, Ryan, for verifying the issue. I agree to your speculation. Regarding your suggestion, I am not sure if i have enough knowledge to explain the issue well. If you want, please go ahead to create a ticket there.


    On Thursday, January 24, 2019, 1:52:20 PM EST, Ryan Nowak <notifications@github.com> wrote:  
 
 
Wow! This is an amazing bug. Can you file this at https://github.com/mono/mono - this is probably an issue in the underlying runtime.

**Comment by gulbanana** [comment]
I've experienced this too, it's very amusing. I have a repro but it's a lot more complex than just calling Math.Truncate (which we don't even use!). Just, doing a lot of work in WASM leads to the print dialog opening..

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#13428
