### ISSUE TITLE
Setting port of .netcore webapp doesn't seem to work right

### ISSUE THREAD

**Issue by CreativeHouseDotOrg** [aspnet/AspNetCore#6976]
I recently began to create a console app that would launch my apis through a process command line. I have 2 apis (1 web api and 1 signalr socket api).

Unfortunately when I try to set the Port of the api in the Program Main Method through the `UseUrls(urls)` things get wonky. 

It seems that the webApi server is started and I can reach the page by browsing to the desired location : `https://localhost:7001`.

**BUT ->** If I try to reach my controller (Named: CelestialObjectController) that is inside the Controllers folder on my webApi next to the ValuesController, I get a Error 500! `https://localhost:7001/api/CelestialObject` <- returns Status 500`

**Here's the funny thing ->** Do you know the ValuesController that VS spawns when you create a new Project? Actually I can reach this Controller and read the Get Method! 

`https://localhost:7001/api/values` WORKS!.. I can see Value 1 and Value 2..... But why does this work?..... And why does my own Controller give me a Error 500 eventhough it's in the same directory as ValuesController?
Also if I modify the values of the ValuesController I can see the changes when recompiling and debugging.

Just to mention that the `.UseUrls($"https://*:{ProgramOptions.SocketPort}")` Method seems to work on my SocketApi which runs with SignalR on the port 7002. I can connnect to the socket hub and calling `https://localhost:7002/api/value` also seems to work. I haven't tested to add a controller, since my socketapi shouldn't rely on controllers, rather more on hubs, and it seems to work when trying to connect to the hub through the signalr client to this adress and port

Another thing I discovered is if I Debug each api individual everything seems to work fine and I can retreive the data, it just seems that it doesn't run in production mode or when being launched as a Process...

I did try to change the Web Settings in launchSettings.json and in the Project Properties, but that seemed to Mess things up so I reverted the changes to the default settings and now I'm hoping I could find an answer here!

**Can someone explain this behaviour to me and what I possibily have to do, to get the Ports set right?**

My CreateWebHostBuilder Method in Program.cs from my WebAPI looks like the following (Basically the same as in my SocketAPI)

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .UseUrls($"https://*:{ProgramOptions.WebPort}");

Any help on this situation is highly appreciated!

**Edit:**

If i look at the request/response headers i see this: 
(From Firefox Devtools)

**Response Headers (111 B)**	
Content-Length	
0
Date	
Thu, 24 Jan 2019 08:40:22 GMT
Server	
Kestrel

**Requestheaders (446 B)**	
Accept	
text/html,application/xhtml+xm…plication/xml;q=0.9,*/*;q=0.8
Accept-Encoding	
gzip, deflate, br
Accept-Language	
de,en-US;q=0.7,en;q=0.3
Cache-Control	
max-age=0
Connection	
keep-alive
Cookie	
Culture={"Language":"de"}; Consent={"Level":3}
DNT	
1
Host	
localhost:7001
Upgrade-Insecure-Requests	
1
User-Agent	
Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/64.0

**Comment by CreativeHouseDotOrg** [comment]
/CC
[https://stackoverflow.com/questions/54339837/setting-port-of-netcore-webapp-doesnt-seem-to-work-right?noredirect=1#comment95517569_54339837](https://stackoverflow.com/questions/54339837/setting-port-of-netcore-webapp-doesnt-seem-to-work-right?noredirect=1#comment95517569_54339837)

**Comment by anurse** [comment]
Can you provide a sample project that reproduces the problem? That way we can look at the entire context and see if there's a problem with the product.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
