### ISSUE TITLE
[SignalR JS | Question] Proper webworker detection

### ISSUE THREAD

**Issue by dukhanov** [aspnet/AspNetCore#6979]
According to the JS code the type of platform which runs client connection is detected by global window object: `const isNode = typeof window === "undefined";`

In case the client is initialized inside of WebWorker (I use `dist/browser/signalr.min.js`) the script execution is failed with an error `Uncaught ReferenceError: window is not defined`

The solution which I made is to add a fake global window object:
```
importScripts(
	'fakeGlobalWindow.js', // global window should be defined for signalR client lib
	'signalr.min.js',
)
```
fakeGlobalWindow.js:
```
const window = self.window = self
```
But it looks like the ugly hack.

Are there any possibilities to change the checking?
https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L74
from:
```
const isNode = typeof window === "undefined";
        if (!isNode && typeof WebSocket !== "undefined" && !options.WebSocket) {
            options.WebSocket = WebSocket;
        } else if (isNode && !options.WebSocket) {
            if (WebSocketModule) {
                options.WebSocket = WebSocketModule;
            }
        }
```
to:
```
const isBrowser = typeof window === 'object';
const isWorker = typeof importScripts === 'function';
const isNode = !isBrowser && !isWorker

        if (!isNode && typeof WebSocket !== "undefined" && !options.WebSocket) {
            options.WebSocket = WebSocket;
        } else if (isNode && !options.WebSocket) {
            if (WebSocketModule) {
                options.WebSocket = WebSocketModule;
            }
        }
```
Is there any caveats to use signalR client inside of the webWroker?

**Comment by bradygaster** [comment]
This is something we'd have to try out, as the web worker is something we've not experimented with in this context.

**Comment by dukhanov** [comment]
Added a PR to support webworkers https://github.com/aspnet/AspNetCore/pull/7058

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
