### ISSUE TITLE
Support for SignalR  C++ client: "aren't currently supported and may never be".

### ISSUE THREAD

**Issue by stukselbax** [aspnet/AspNetCore#6980]
### What to do with old C++ clients that used ASP.NET SignalR client?
We have a C++ application which communicates with ASP.NET SignalR server. We are in phase of migrating our server solutions to AspNetCore, and one of issue is that the state of  C++ client isn't clear.

[On docs:](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-2.1#unsupported-clients)

> The following clients are available but are experimental or unofficial. They aren't currently supported and may never be.
> C++ client

[On github:](https://github.com/aspnet/AspNetCore/tree/master/src/SignalR/clients/cpp)

> There are no plans to ship this client at this time.

It would be great if the cpp client will be officially supported by AspNetCore team. Actually we didn't grab and try current C++ client code due to above reason.

As for now we have to support both ASP.NET SignalR and new AspNetCore SignalR servers.

**Comment by mikaelm12** [comment]
We currently have the ASP.NET Core SignalR C++ client as  part of our 3.0 milestone https://github.com/aspnet/AspNetCore/issues/5301. 👍

**Comment by bradygaster** [comment]
Reiterating what @mikaelm12 said - it is our goal to ship this soon. if you need more info let us know, for now i will close this as we've discussed our plans.

**Comment by wegylexy** [comment]
I think the C++ client is getting a wrong `connection_id`. It doesn't match with the one server side. The server one seems correct.
