### ISSUE TITLE
Kestrel in LAN + IIS in DMZ via reusable reverse/duplex connections

### ISSUE THREAD

**Issue by Danielku15** [aspnet/AspNetCore#6981]
### Is your feature request related to a problem? Please describe.
I am trying to expose one or more applications running in the LAN on Kestrel, via an IIS running in the DMZ to the internet without opening any manual firewall holes from the DMZ machine to the LAN machine. 
Currently you need to operate Kestrel and IIS on the same machine. 

### Describe the solution you'd like
**Basic approach**
It would be great if you could tell the Kestrel IIS integration on which machine the IIS is running. Then Kestrel connects from the LAN into the DMZ (which is allowed from security perspective) and hooks up with the IIS. The IIS can then use this TCP connection to tunnel any incoming HTTP/WSS calls to Kestrel in the backend. 

**Advanced approach**
Kestrel opens 1 control and multiple data connections as connection pool. Via the control connection some keep-alive mechanism ensures that everything is working and via control commands additional data connections can be opened or closed if depending on the needs. 

### Describe alternatives you've considered
Currently one of our application has a manually developed API gateway that is tunneled via a duplex WCF channel. The same WCF contract we have in the backend, is exposed on a service in the DMZ and calls are simply tunneled through. The web application, also running in the DMZ can then call against the "proxy" to reach the LAN service. 

For another new ASP.net core application, we have created also such a duplex WCF channel but with a special pipeline: In LAN service we have a custom `IServer` with this WCF duplex connection to the DMZ. On the DMZ service we have a minimal OWIN host, that simply forwards the OWIN context (dictionary) via WCF call to the LAN. This DMZ service is very thin and simply tunnels calls on HTTP/OWIN context level. So when a HTTP call comes to our DMZ service, we unwrap the OWIN dictionary, make a call to the backend via the duplex channel using this dictionary (and special streams) where it goes through the whole ASP.net pipeline. The response is then unwrapped again on the DMZ service and the data is forwarded to the calling client. 

### Additional context
Overall I would like to simplify our application stack to have a classical ASP.net core web application development. No special cross service communication, no API gateway, no special deployment. Via this proposed small reverseproxy module on top, it can bring this LAN/DMZ separation feature for exposing a local service via a remote IIS.

In the existing out-of-process hosting model, the ASP.net core module already tunnels HTTP calls to Kestrel running in another process. I guess this is done by simply opening a connection to http://localhost:{port} from IIS to Kestrel and then tunnel the data. Simply spoken there would just be a need for a special connection pool that is used for communication between IIS and Kestrel. This connection pool that can be built-up in 2 ways: The current way that IIS opens connections directly as by today. The new way proposed in this issue would tell Kestrel to pre-open a configured number of connections that are then re-used. Dynamic scaling of the pool could then be an advanced feature on top. 

Many people might be confused on this topic and ask why this is really needed: There are many security critical environments where you cannot open ports between LAN and DMZ. There is also some IT maintenance effort to setup and maintain such even if it would be allowed to open individual ports. The only solution for this today is to invest more development effort on application level to have this HTTP/WS tunneling in a semantic fashion via an API gateway. 

Please note that this feature also might bring other use cases like load balancing and scalability: If there are multiple Kestrel applications running in the LAN (e.g. via dynamically scaled docker instances), they could all register them on the IIS and the IIS does the load balancing between the available services.

**Comment by blowdart** [comment]
nginx is designed for this and there is a version that runs on Windows. Windows has a Reverse Application Proxy as a feature in a server SKU. IIS is not designed for this.

**Comment by Danielku15** [comment]
> nginx is designed for this and there is a version that runs on Windows. 

Even though it is likely possible, an additional proprietary/paid software might not be a good solution for most of the people. We are developing software that is shipped to customers for installation on their own environments. We're in a bad position "against" customers to say they need to buy and manually setup an additional nginx for their installation of our software. 

> Windows has a Reverse Application Proxy as a feature in a server SKU.

Haven't heard of this, but unfortunately our Software also needs to run on Non-Server Windows Versions. Development and QA do their every-day work on normal Windows 10 machines. On top of that it seems to require Active Directory Federation Services for gaining access from the DMZ to the LAN which is again something that is not simply available and requires heavy IT administration effort. 

> IIS is not designed for this.

Can you elaborate that more? Is my understanding of the existing ASP.net Core module for the IIS using an Out-of-process hosting model working differently than I tried to explain? I understand that with the existing implementations it is not possible, hence the feature request.

**Comment by anurse** [comment]
We have no plans to add this kind of connection model to Kestrel directly, it doesn't really fit our model. If you need something like this, I expect there is proxy software out there than can do this kind of reverse tunneling (and Windows has a feature for it) but it's well beyond our scope.
