### ISSUE TITLE
TagHelper only works when edited live

### ISSUE THREAD

**Issue by Themodem** [aspnet/AspNetCore#6982]
### Describe the bug
I have some tag helpers

```
<portlet portlet-style="Basic">
  <portlet-header title="Title" icon="BullseyePointer" icon-style="Light"></portlet-header>
  <portlet-description color="Info">
  </portlet-description>
  <portlet-body>
  </portlet-body>
</portlet>
```

They only seem to work when the file "_ViewImports.cshtml" is edited once the application is running.

Its difficult to explain so ive made a video of the issue.
[https://youtu.be/wS0By1q_eeU](https://youtu.be/wS0By1q_eeU)

I run the application and refresh it a few times.
Then tab to the editor (Rider. But the same happens with Visual Studio as well).
Add a space into the file _ViewImports.cshtml
Save and tab back to browser.
Refresh and the tag helpers work as expected.
Tab back to editor and restart the application.
Tab back to browser, refresh and broken again

### Expected behavior
Tag helpers work without having to be edited and compiled at runtime.

### Screenshots
[https://youtu.be/wS0By1q_eeU](https://youtu.be/wS0By1q_eeU)

**Comment by pranavkm** [comment]
@Themodem do you perhaps have the 3.0 preview SDK installed? Trying to see if you're running in to the same issue as https://github.com/aspnet/AspNetCore/issues/6825

**Comment by Themodem** [comment]
@pranavkm You are indeed correct.

This is a dupe of that issue. `global.json` is a working work around for now.

Thanks for the assist.
