### ISSUE TITLE
Memory Leak!

### ISSUE THREAD

**Issue by aropb** [aspnet/AspNetCore#6984]
Hello all,

I found a memory leak in a simple project (.NET Core 2.2.1, OS Windows 10 Pro 1803, Build 17134.523).
Screenshots and project attached.

The problem is very serious, because the production project takes all the memory and falls.
The size of Heap Generation 2 is constantly growing!

gcserver=off kestrel
![webservertest gcserver off kestrel](https://user-images.githubusercontent.com/2377913/51665930-e6a76e80-1fcd-11e9-97eb-bce07e56c189.png)

gcserver=on httpsys
![webservertest gcserver on httpsys](https://user-images.githubusercontent.com/2377913/51665931-e6a76e80-1fcd-11e9-9767-b6930b05b111.png)

gcserver=off httpsys
![webservertest gcserver off httpsys](https://user-images.githubusercontent.com/2377913/51665932-e6a76e80-1fcd-11e9-9465-a64acd29b91b.png)

[WebTest.zip](https://github.com/aspnet/AspNetCore/files/2790839/WebTest.zip)

**Comment by sebastienros** [comment]
More questions:

- How much load should I send to start seeing this behavior? Is running you sample "auto refresh" page enough?
- Can you try to take a dump at some point, and another one later on, ideally when you think it's running out of memory?

**Comment by aropb** [comment]
Hi,

 

Yes, I open 3 browser tabs and see how memory grows.

How best to make a dump? This is a simple example that shows the strange behavior of the server. Production is certainly a more complex project. There's a large dotMemory dump.

 

Regards,

Pavel.

**Comment by muratg** [comment]
@aropb could you please answer @sebastienros's first two questions as well?

**Comment by aropb** [comment]
Hi,

The server becomes unavailable to clients. The Service must be restarted. On the server 6GB is available, the server is virtual.

Production server:

OS Name:                   Microsoft Windows Server 2012 R2 Standard
OS Version:                6.3.9600 N/A Build 9600
System Manufacturer:       VMware, Inc.
Processor(s):              2 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 45 Stepping 2 GenuineIntel ~2397 Mhz
                           [02]: Intel64 Family 6 Model 45 Stepping 2 GenuineIntel ~2397 Mhz

Total Physical Memory:     8 191 MB
Available Physical Memory: 6 328 MB
Virtual Memory: Max Size:  9 983 MB
Virtual Memory: Available: 8 194 MB
Virtual Memory: In Use:    1 789 MB

![prodserver1](https://user-images.githubusercontent.com/2377913/51727113-82db7f00-207b-11e9-9660-dc7856ca2679.png)

If the memory is all over the log file like this:

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context) ExceptionHandlerMiddleware.Invoke => AsyncMethodBuilderCore.Start => <Invoke>d__6.MoveNext
2019-01-11 11:40:22.7350 Microsoft.AspNetCore.Server.HttpSys.LogHelper.LogException Error: ListenForNextRequestAsync An operation was attempted on a nonexistent network connection    at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestsWorker() ExecutionContext.RunInternal => <ProcessRequestsWorker>d__22.MoveNext => LogHelper.LogException
2019-01-11 12:28:42.4670 Microsoft.AspNetCore.Server.HttpSys.LogHelper.LogException Error: ListenForNextRequestAsync An operation was attempted on a nonexistent network connection    at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestsWorker() ExecutionContext.RunInternal => <ProcessRequestsWorker>d__22.MoveNext => LogHelper.LogException
2019-01-11 12:28:42.4670 Microsoft.AspNetCore.Server.HttpSys.LogHelper.LogException Error: ListenForNextRequestAsync An operation was attempted on a nonexistent network connection    at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestsWorker() ExecutionContext.RunInternal => <ProcessRequestsWorker>d__22.MoveNext => LogHelper.LogException

Dump of WebServerTest from dotMemory:
[WebServerTest netcore 2.2.1 gcServer off httpsys.dmw.zip](https://github.com/aspnet/AspNetCore/files/2794738/WebServerTest.netcore.2.2.1.gcServer.off.httpsys.dmw.zip)

**Comment by aropb** [comment]
![jetbrains dotmemory 2019-01-25 08 52 54](https://user-images.githubusercontent.com/2377913/51727853-fa5edd80-207e-11e9-94fe-eab8e5532b9a.png)
![jetbrains dotmemory 2019-01-25 08 54 13](https://user-images.githubusercontent.com/2377913/51727851-f9c64700-207e-11e9-907d-c3b8aff39ac3.png)
![jetbrains dotmemory 2019-01-25 08 53 32](https://user-images.githubusercontent.com/2377913/51727852-f9c64700-207e-11e9-8069-320ecb301ecd.png)

**Comment by sebastienros** [comment]
No, sorry for the delay, I just need more time. Thanks.

**Comment by aropb** [comment]
Hi, @sebastienros, when can I expect an answer?

**Comment by sebastienros** [comment]
I can't repro an issue.

I have published the application you provided with the `publish.cmd` script, and ran it with a much higher load than what you suggested. I also defined logging at the Warning level otherwise every requests were logged on the console. On my machine the memory is very stable at 30MB which makes sense as you disabled server GC.

Does you issue only happen through IIS in-process?

**Comment by aropb** [comment]
No IIS i don't use

**Comment by aropb** [comment]
Please, write your PC and OS specification.

**Comment by sebastienros** [comment]
Windows 10, .NET Core 2.2.1

**Comment by aropb** [comment]
@sebastienros, Hi.
I can not understand why my project memory is always growing. I can't find the cause, but maybe it's normal behavior?

![profiling_ webaccmng windows service - net memory profiler 2019-02-08 12 45 21](https://user-images.githubusercontent.com/2377913/52470541-77ba4000-2b9f-11e9-8f1c-55b2876fef4c.png)
![profiling_ webaccmng windows service - net memory profiler 2019-02-08 12 47 28](https://user-images.githubusercontent.com/2377913/52470613-b94aeb00-2b9f-11e9-89a8-ef31ceb0d580.png)

Dump:
[https://drive.google.com/open?id=1sfIJMmnHf5RQjsPr-P1nZ63iDMj7H1Ot](url)

**Comment by sebastienros** [comment]
It might just be that gen2 GC hasn't triggered yet. Using 60MB of memory is very low, the GC will only start once it hits memory pressure, meaning the OS tells the application that it's about to use too much memory. But I might be wrong. Let it run for hours, take a memory dump (one from the task manager is fine) at the middle of the run and right before your stop it once it's taking half your system memory. Taking two dumps will let us know what objects were created during this window. 

Take a look at [this comment](https://github.com/aspnet/AspNetCore/issues/3409#issuecomment-436677987) where the process takes more than 2GB and the GC is never actually called, only because it doesn't have to as the available memory is still plenty. It might not be the "expected" scenario from an application developer's perspective though, and this will be changed in .NET 3.0.

**Comment by aropb** [comment]
@sebastienros Hi, I found my bug in the controller. I'm sorry.

I used in "Select/Where" from DatabaseContext a not static method of a controller. 
It's bad that the netcore compiler misses such errors.

Thanks.

**Comment by aropb** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/13048

**Comment by Mart-Bogdan** [comment]
@sebastienros by the way, for future cases, as we found out, NET Memory Profiler  triggers GC before snapshot creation, so no unreachable are present inside snapshot.
