### ISSUE TITLE
Razor Components: VS 2019 Preview 2 build hangs if trying to build with unsaved changes

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#6991]
1. Install VS2019 Preview 2 and .NET Core SDK 3.0.100-preview-010154
2. Create a Razor Components project
3. In `Index.cshtml`, make any edit, then save change, then build app. Confirm it builds OK.
4. Make any further edit, but *don't* save the change, then build app. Observe the build hangs indefinitely.

**Comment by rynowak** [comment]
Logged: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/777136 - unfortunately this is not something we control.

**Comment by danroth27** [comment]
This should be fixed in the next VS2019 preview update (preview 4)

**Comment by Lupusa87** [comment]
Using preview3 (today's release) it is taking too long even if I save changes before build.

**Comment by danroth27** [comment]
@Lupusa87 The fix for this build hang should be coming in the next preview update (preview 4).

**Comment by Lupusa87** [comment]
Where can I track progress for preview 4?

**Comment by danroth27** [comment]
@Lupusa87 I don't believe there has been any official announcement about the timing or number of the remaining VS2019 previews, but the VS2019 launch date has been [announced](https://devblogs.microsoft.com/visualstudio/join-us-april-2nd-for-the-launch-of-visual-studio-2019/) for April 2.
