### ISSUE TITLE
SignalR throwing error after stop

### ISSUE THREAD

**Issue by maxisam** [aspnet/AspNetCore#6999]
### Describe the bug
Someone reports this on stackoverflow as well at https://stackoverflow.com/questions/53944572/signalr-core-error-websocket-closed-with-status-code-1006/54355355#54355355. 

The whole thing is like
when the client invoke close connection call to server. The sever receives that and return a message to client to close. The client received and call `stop` to close the connection.

However, sometime it will throw an error like `Invocation canceled due to connection being closed`

I think the reason is causing by the response from server is breaking into 2 pieces

like 
![image](https://user-images.githubusercontent.com/456807/51709687-ae635880-1fec-11e9-9dca-616a2732982e.png)

instead of 
![image](https://user-images.githubusercontent.com/456807/51709704-bc18de00-1fec-11e9-99b1-1a239706ea2b.png)

Therefore, parseMessages  doesn't work properly at 
https://github.com/aspnet/AspNetCore/blob/8ce02ef68eba3ad72d916985e6bd4698092e649f/src/SignalR/clients/ts/signalr/src/JsonHubProtocol.ts#L28

then 

`processIncomingData` can't remove the callback properly because `MessageType.Completion` is in the second piece of return

https://github.com/aspnet/AspNetCore/blob/8ce02ef68eba3ad72d916985e6bd4698092e649f/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L348

Callback never gets deleted at here
https://github.com/aspnet/AspNetCore/blob/8ce02ef68eba3ad72d916985e6bd4698092e649f/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L371

And then the connectionClosed trigger by stop

https://github.com/aspnet/AspNetCore/blob/8ce02ef68eba3ad72d916985e6bd4698092e649f/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L479

and it found there is still a callback left in the array. It throws error.

### To Reproduce
1. asp.net core 2.1
2.  @aspnet/signalr: ^1.1.0

**Comment by BrennanConroy** [comment]
There can be a race between the server sending an invocation response and sending a close message. If the close message wins (which you're seeing in your example) then the connection will close with the error you're seeing.

The only issue I can see is that `processIncomingData` keeps processing messages if they're in the same payload as the close message when it should stop if the close message was read.

**Comment by maxisam** [comment]
@BrennanConroy I see. but why they can be in one payload sometime?

**Comment by maxisam** [comment]
Actually I just realized that I don't need to send a close message. I can just use the invocation response to trigger that.

**Comment by maxisam** [comment]
nope, but I feel like stop should close the connection without checking if there is any callback left. Or there should be a way to let it wait until all callback is remove and call stop internally.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
