### ISSUE TITLE
Missing symbols package for Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by pkapare** [aspnet/AspNetCore#7006]
### Describe the bug
Missing Microsoft.AspNetCore.App.3.0.0-preview-t000.symbols.nupkg package.

### To Reproduce
Build source code using  build.cmd -all  command.

### Expected behavior
artifacts/packages/debug/shipping folder should have Microsoft.AspNetCore.App.3.0.0-preview-t000.nupkg and Microsoft.AspNetCore.App.3.0.0-preview-t000.symbols.nupkg packages post build.

**Comment by natemcmaster** [comment]
I'm closing this as by-design. Symbols are only really useful when debugging an app that is executing. Microsoft.AspNetCore.App is only meant to provide reference assemblies (assemblies which are only used by the compiler...sort of like headers). The runtime assemblies are found in the "runtime.$(RuntimeIdentifier).Microsoft.AspNetCore.App" packages, and there should be a corresponding .symbols.nupkg package.

FYI @pakrym
