### ISSUE TITLE
option to get CSC vs GCM mode using Sslstream 

### ISSUE THREAD

**Issue by anushprabhu** [aspnet/AspNetCore#7007]
We are currently using TLS 1.2 and logging the cipher suite from SslStream in our service but there is no option to log the mode used.

Is it possible to expose this in SslStream or how we can get this information?

**Comment by Eilon** [comment]
@Tratcher / @blowdart - any idea on this? Is this an ASP.NET Core issue?

**Comment by blowdart** [comment]
No, it's an SslStream issue. So .NET Core.

**Comment by Eilon** [comment]
This issue was moved to dotnet/core#2254
