### ISSUE TITLE
Authorization broken in Razor Pages

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#7011]
### Describe the bug
The Authorize attribute no longer works in Razor Pages applications.

### To Reproduce
1. Make a new Razor Pages project with individual auth
2. Add an `[Authorize]` attribute on the Index page
3. Running the application doesn't redirect to the login page.

### Expected behavior
The page should redirect to the Login page.

### Additional context
This is using build `3.0.0-preview-19073-0424`

Seems like the authorize attribute isn't being exposed as authorize metadata.

cc @rynowak @pranavkm @JamesNK

**Comment by rynowak** [comment]
I think the right fix for this is that we need to introduce the concept of a *dynamic* endpoint. This would allow you to run code to replace the `Endpoint` in between the DFA phase and the `EndpointSelectorPolicy` phase. 

This is also really useful for some of the other scenarios that have blocked users from using endpoint routing when they had a custom `IRouter`. 

The Razor pages infrastructure would plug into this feature and use it to *compile* the page asynchronously, which would return the *rich* endpoint.

**Comment by rynowak** [comment]
I've written about this idea before here: https://github.com/aspnet/AspNetCore/issues/4221 and I think it would solve many of this class of problems.

**Comment by rynowak** [comment]
> do you think your suggested solution is something which can fit in preview3 timeframe

Yes absolutely.

**Comment by davidfowl** [comment]
I’m unclear on why a new feature is required but I’ll talk to @rynowak about it later

**Comment by rynowak** [comment]
Because we do routing without having compiled the pages. MVC later swaps in the compiled AD for the routable one.

**Comment by pranavkm** [comment]
@JamesNK assigning to you to fix the issue for preview3.

**Comment by Ponant** [comment]
@rynowak that is closed but not fixed yet on preview 3.
Authorze attribute does nothing
AuthorizePage nothing
AuthorizeFolder nothing
In the default Identity, you can navigate to /Identity/Account/Manage, which should trigger back to login whereas it shows  `Unable to load user with ID ''.`
Is this planned for preview 4?
