### ISSUE TITLE
Is it possible to customize the result file generated by dotnet vstest?

### ISSUE THREAD

**Issue by jaydeept** [aspnet/AspNetCore#7012]
I am using .Net Core 2.2 where to execute the test cases through command line, I am using `dotnet vstest` and generating output file in `XML` format, However I really didn't like the generated XML file, it's bit complex to understand and parse. 
Is it possible to customize the generated result file? 
I really liked the **NUnit Console** generated result file for .Net Framework but that doesn't support .Net Core, so doesn't have that option available.

**Comment by Eilon** [comment]
This issue was moved to Microsoft/testfx#556
