### ISSUE TITLE
Property marked as [Editable(false)] not being bound in controller

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/AspNetCore#7015]
Currently if you add `[Editable(false)]` on a posted property, model binder [sets that property as readonly in binding context](https://github.com/aspnet/AspNetCore/blob/v2.2.1/src/Mvc/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/DataAnnotationsMetadataProvider.cs#L50-L54), resulting in that property not being [bound on post](https://github.com/aspnet/AspNetCore/blob/v2.2.1/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/PropertyValueSetter.cs#L20-L29).

I would expect that readonly values get readonly attribute and are still posted to the controller, because now all readonly values are lost, resulting in an invalid model state and an empty postback.

Is there any other way to mark property as readonly without the need of new attributes? I'm trying to achieve the same result as in MVC5, using `[Editable(false)]` attribute to mark properties to be excluded from back-end `edit` handlers and using an input (tag) helper to add readonly attribute. That way we don't have to keep track of multiple places where readonly fields have to be handled and rendered differently.

Also, maybe someone can elaborate on the current `[Editable(false)]` use case? Is it just for mass assignment prevention?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Muchiachio.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Apologies for the delayed response.

> Is there any other way to mark property as readonly without the need of new attributes?

Doesn't look like it. https://github.com/aspnet/Mvc/issues/6404 has some discussion for supporting a scenario close to what you'd want. If you intend for the client to not edit the value, I'd recommend using a view model without validation attributes. This way you can use to it to display content and not concern yourself with over-binding.
