### ISSUE TITLE
In-Process support for multiple applications on the same application pool

### ISSUE THREAD

**Issue by SolidSoft-Lda** [aspnet/AspNetCore#7019]
I finally be able to convert, compile and run my ASP.NET WebApi (.NET 4.7) to ASP.NET Core WebApi (.NET Core) and run both version exactly with the same performance thanks to In-Process finally added on the latest .NET Core 2.2,

However as soon I add a second application to the application pool, I got the following error:
HTTP Error 500.0 – ANCM In-Process Handler Load Failure

I know by now that .NET Core in-process is limited to one application per application pool, however this is for now, the only issue that is blocking me to move from .NET Framework to .NET Core.

My application is single-tenancy and I can't move that to multi-tenancy and also I can't use separated application pools because they will consume a lot of memory.

Please, provide multiple application support on In-Process.
For me this is only the blocking issue to finally to move to .NET Core.

**Comment by anurse** [comment]
We're limited by what .NET Core supports here. For .NET Framework, we could use AppDomains to launch multiple applications in the same process. That's not support in .NET Core. Only a single application is supported per process.
