### ISSUE TITLE
Type 7 error message was seen when signalR client was connected to the hub in the presence of Azure SignalR Service

### ISSUE THREAD

**Issue by Arash-Sabet** [aspnet/AspNetCore#7020]
### Describe the bug
When the connection between the signalR client application and the server is established, we saw the following client logs in the network tab of Chrome browser:

> Debug: Starting HubConnection.
> Debug: Starting connection with transfer format 'Text'.
> Debug: Sending negotiation request: https://.............................................
> Debug: Selecting transport 'WebSockets'.
> Information: WebSocket connected to wss://*************************.service.signalr.net/client/?....................
> Debug: Sending handshake request.
> Information: Using HubProtocol 'json'.
> Debug: Server handshake complete.
> Information: Close message received from server.
> Error: Connection disconnected with error 'Error: Server returned an error on close: Internal server error.'.
> Debug: Stopping HubConnection.

### To Reproduce
1. SignalR Server using ASP.NET Core 2.2.
2. Leverage the paid tier of Azure SignalR Services in the signalR server code.
3. Implement an angular signalR client app to establish a connection and maintain the connection to view the heartbeats.
4. Type 7 error may or might be seen.

### Expected behavior
Type 7 error must not be seen.

### Screenshots
![type7 error](https://user-images.githubusercontent.com/26050123/51408089-a8bccd00-1b2b-11e9-8822-ca7dc97b8160.png)

### Additional context

- This bug is reported in response to [this conversation](https://github.com/aspnet/AspNetCore/issues/6448#issuecomment-457360552). 
- Suggestion: the information of the SignalR Service resource which may have caused this problem was already shared with @chenkennt in a private email. If this reported bug is due to a possible infrastructural issue in Azure SignalR, it's worth checking your own backend logs dated on Jan 18, 2019 for that particular resource.

**Comment by bradygaster** [comment]
Assigning to @chenkennt as we discussed this in our sync-up together and he's aware of this issue.

**Comment by halter73** [comment]
@chenkennt Are you still working on this? Or should we close?

**Comment by chenkennt** [comment]
@Arash-Sabet Since #6448 is resolved, do you still see this problem? I think these two should have the same cause.

**Comment by Arash-Sabet** [comment]
It's possible that they may or might be relevant. Since we've not seen the issue so far, I am going to close this ticket but monitoring the situation.

**Comment by jsheetzati** [comment]
We are experiencing the same issue with our managed SignalR service in half our environments. Each environment has its own hub and its own managed SiganlR service so I am not sure #6448 applies to us.

https://github.com/Azure/azure-signalr/issues/395

**Comment by chenkennt** [comment]
@jsheetzati I think that may be a different problem. Could you send me your resource name (to my email) so I can take a look at the service side?
