### ISSUE TITLE
Remove obsolete UseIdentity/Auth/Google APIs 

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#7026]
Was obsoleted as part of the 2.0 auth changes

**Comment by HaoK** [comment]
We should also remove all the other UseAuth apis, i.e. https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerAppBuilderExtensions.cs

**Comment by Eilon** [comment]
BTW remember to set milestone on this as appropriate.
