### ISSUE TITLE
Blazor Streaming GetAsync() wants to read whole content

### ISSUE THREAD

**Issue by ColinSchmale** [aspnet/AspNetCore#7032]
I want to receive an endless stream from a web api with this code

`HttpClient httpClient = new HttpClient {
    Timeout = TimeSpan.FromMilliseconds(Timeout.Infinite)
};
var request = await httpClient.GetAsync("https://this.is.my.url", HttpCompletionOption.ResponseHeadersRead);
var stream = await request.Content.ReadAsStreamAsync();
var bufferedStream = new BufferedStream(stream);`

and then read bytes from the BufferedStream in a loop.

My Problem: Blazor wants to read the whole content and because the stream does not end, my program will never get past the GetAsync() function.

Is this the intended behavior? How to fix this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ColinSchmale.
@davidfowl, isn't this scenario something Pipe streams are designed for?
/cc @rynowak

**Comment by mkArtakMSFT** [comment]
@kjpou1, is this something you can help @ColinSchmale with?

Closing the issue here as it's external.

**Comment by marcussacana** [comment]
Same problem here... strange....
