### ISSUE TITLE
HttpContext.Request.Browser in asp.net core

### ISSUE THREAD

**Issue by kshyju** [aspnet/AspNetCore#7033]
Is there an alternative in the asp . net core world for `HttpContext.Request.Browser` ?  .net framework 4.7.2 [has this](https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest.browser?view=netframework-4.7.2). 

If no plans, to add, would you mind sharing the rationale behind that ? recommended alternate solutions ?

**Comment by Eilon** [comment]
Hi, the browser caps feature in ASP.NET 4.x was a server-based way of doing client feature detection. This approach is generally frowned upon in the "modern" era, where runtime client-side feature detection is preferred, using techniques such as progressive enhancement. For that reason, in addition to being a huge maintenance cost to keep the list even reasonably up-to-date, the feature was not brought forward to ASP.NET Core.

**Comment by kshyju** [comment]
Thanks Eilon

**Comment by tb-mtg** [comment]
@kshyju What alternative did you end using?

**Comment by kshyju** [comment]
Ended up writing something which parses user agent string to do this.

**Comment by kshyju** [comment]
There are some valid use cases where browser detection is needed (Example: a proxy server which can do specific routing based browser information). I created a light weight library to do this and published as a [nuget package](https://www.nuget.org/packages/Shyjus.BrowserDetector/). 

Follow steps outlined [here](https://github.com/kshyju/BrowserDetector#how-to-use-) to use it.

**Comment by kshyju** [comment]
@tb-mtg I have published the solution I used as a nuget package. See above response.
