### ISSUE TITLE
NullReferenceException at Microsoft.AspNetCore.Http.DefaultHttpContext.set_User

### ISSUE THREAD

**Issue by yzhoholiev** [aspnet/AspNetCore#7037]
### Describe the bug
We randomly experience exception System.NullReferenceException  at Microsoft.AspNetCore.Http.DefaultHttpContext.set_User, full stack below.

The service is deployed to the Azure Service Fabric service.
We are using the ApplicationInsights for logging.
We are using several ways to authenticate (tokens, headers etc). For this purpose we are registering our own handlers and using this middleware:

```csharp
services.AddApplicationInsightsTelemetry(configuration);
```
...
```csharp
loggerFactory.AddApplicationInsights(app.ApplicationServices, logLevel);
```
...
```csharp
public static IApplicationBuilder UseAuthenticationSchemes(this IApplicationBuilder app, params string[] otherSchemes)
{
    app.UseAuthentication();

    if (otherSchemes == null || otherSchemes.Length == 0)
    {
        return app;
    }

    return app.Use(async (context, next) =>
    {
        foreach (string scheme in otherSchemes)
        {
            AuthenticateResult result = await context.AuthenticateAsync(scheme);
            if (result?.Principal == null)
            {
                continue;
            }

            context.User = result.Principal; // <=== The exception is here.
            break;
        }

        await next();
    });
}
```

I found some related bugs here, and I understand it's related to the fact that HttpContext isn't thread safe, but can someone at least suggest a workaround for this case?

From my perspective, this issue is related to https://github.com/microsoft/applicationinsights-aspnetcore/issues/373

We were trying to whap the
```csharp
context.User = result.Principal;
```
into lock:
```csharp
lock(context) {
    context.User = result.Principal;
}
```
but it didn't help at all.

### Expected behavior
No exception during an authentication.

### Additional context
ASP.NET Core 2.2
Microsoft.ApplicationInsights.AspNetCore 2.5.1

**Comment by anurse** [comment]
Is it `context` that is `null`? Can you provide the full stack trace for the exception?

> it's related to the fact that HttpContext isn't thread safe

This is true, but only if you have multiple code paths accessing the `HttpContext` **for the same request at the same time**. This looks like standard middleware so it should be OK, you don't appear to be doing anything like spawning new threads (i.e. `Task.Run`) or storing the `HttpContext` and accessing it in a background thread.

**Comment by yzhoholiev** [comment]
> Is it context that is null?
The context isn't `null`, but the underlying feature is.
https://github.com/aspnet/AspNetCore/blob/9f202feafc335dd70ae640f2053b465be3879e82/src/Http/Http/src/DefaultHttpContext.cs#L114

**Comment by anurse** [comment]
This should only be occurring if you have two threads trying to access `HttpContext` for the same request at the same time. You don't have any background threads accessing `HttpContext` in your application?

Can you provide a full sample project that reproduces the issue so we can review all the relevant code?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
