### ISSUE TITLE
Move View method out of controller context.

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/AspNetCore#7040]
I would like to have `View `method of the `Controller `move to an separated service .
In the architecture the Controller is just response to the http request ,and it be more consistency that use a Controller as an Api controller or MVC controller.
In an  MVC Controller developer can get the model from any source and get View Template from any source and render those via an external service .

**Comment by pranavkm** [comment]
There's a couple of possible ways to go about doing this:

* You can construct and execute a `ViewResult` or `PartialViewResult` given the right context.
* You can use `ViewResultExecutor` or `PartialViewResultExecutor` to execute an instance of `IView` - See https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.viewfeatures.viewexecutor.executeasync?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_ViewFeatures_ViewExecutor_ExecuteAsync_Microsoft_AspNetCore_Mvc_ActionContext_Microsoft_AspNetCore_Mvc_ViewEngines_IView_Microsoft_AspNetCore_Mvc_ViewFeatures_ViewDataDictionary_Microsoft_AspNetCore_Mvc_ViewFeatures_ITempDataDictionary_System_String_System_Nullable_System_Int32__

* https://github.com/aspnet/Entropy/blob/7a53120c620bbcfd7b54f147c16fa7da1e38d1d4/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs has a sample of calling in to the ViewEngine infrastructure to find and render a view.

**Comment by mikeandersun** [comment]
What i talk about is separate  MVC framework from Api framework with a  lower level controller and extend it with services in to path one for MVC features and one for Api features.
I hate an Api controller that I know have a lot of View rendering features with it that don't need to those feature for an Api controller.

**Comment by pranavkm** [comment]
MVC ships with a `ControllerBase` that does not include any view rendering specific features. Controllers in the web API templates that ASP.NET Core ship with, derive from `ControllerBase` e.g - https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Controllers/ValuesController.cs#L17. You could do the same.
