### ISSUE TITLE
Conventional area routing doesn't work for web api controllers  located in root area folder.

### ISSUE THREAD

**Issue by rpokrovskij** [aspnet/AspNetCore#7042]
Conventional area routing doesn't work for web api controllers  located in root area folder.

### To Reproduce
ASP.NET Core '2.2'

Add Areas and Areas/MyArea folder (add Pages folder and some razor pages to it)

```
+ My Proj
    + Areas
        + MyArea
            + Pages
            - MyApiController.cs
```

Add `MyApiController.cs` to it but without [Area] and [Route] attreibutes, e.g. - we are going to test conventional routing

MyApiController.cs content:
```
    public class MyApiController: ControllerBase
    {
        public ActionResult GetInts()
        {
             return new ContentResult { Content = "[0,1,2,3]", ContentType = "application/json" };
        }
    }
```

configure conventional routing for area (https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#areas):

```
app.UseMvc(routes =>
            {
                // option 1 - doesn't work
                // routes.MapAreaRoute("MyArea", "MyArea", "MyArea/{controller}/{action}");
                // option 2 - doesn't work
                routes.MapRoute("MyArea", "MyArea/{controller}/{action}",
                    defaults: new { area = "MyArea" }, 
                    constraints: new { area = "MyArea" });
                // option 3 - doesn't work
                // routes.MapRoute("MyArea", "MyArea/MyApi/{action}",
                //     defaults: new { area = "MyArea", controller = "MyApi" }, 
                //     constraints: new { area = "MyArea", controller = "MyApi" });
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action}");
            }
```

### Expected behavior

conventional routing`/MyArea/MyApi/GetInts`  should work for MyArea, but it doesn't.

actually this url `/MyApi/GetInts` (without area part) works well

The reason could be that we configure routing for "alone" _api_ controller not for a page or mvc controller. But this should be mentioned in documentation.

**Comment by pranavkm** [comment]
From the docs:

> The AreaAttribute is what denotes a controller as part of an area, we say that this controller is in the Blog area. Controllers without an [Area] attribute are not members of any area, and will not match when the area route value is provided by routing. 

You need the attribute both for conventional and attribute based routing.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
