### ISSUE TITLE
Global Date Format

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#7043]
_From @ZackTech on Friday, 25 January 2019 16:50:23_

I am developing an Asp.net Core version 2 Web Api and Web Front End. In one of my entry forms I am using a Boostrap date picker. When I run the application on my own PC even connected to the Azure database everything runs normally. On Azure when the model validates server side I get Invalid Date Format. I think server side it has decided to use the US date format.

Is there a global setting I can set just once which I can set it to use UK format irrespective of what hardware the software is sitting on. If that does not exist can we please have one?

_Copied from original issue: dotnet/coreclr#22210_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.
