### ISSUE TITLE
[Blazor]  Parameter Value from Sibling Component Issue

### ISSUE THREAD

**Issue by tezine** [aspnet/AspNetCore#7045]
Hi, 
I'm having some issues when passing a value from a sibling component as parameter in Blazor. 
I have a component called Cart.cshtml below:
```
@page "/Cart"
<p>Cart: @item</p>

@functions {
    public string item { get; set; }
    [Parameter] protected string Item {get => item;set => item = value; }
    [Parameter] public Action<string> ItemChanged { get; set; }
}
```
I use the Cart component above twice in the code MyStore.cshtml below:
```
<Cart ref="firstCart" Item="MyItem" />
<Cart ref="secondCart" Item="@firstCart?.item"></Cart>
<button onclick="@IncrementAmountClicked">Increment amount</button>

@functions {
    Cart firstCart;
    Cart secondCart;
    private void IncrementAmountClicked() { }
}
```
When I run it, it displays `Cart: MyItem` in <i>firstCart</i> and `Cart: ` in <i>secondCart</i>, so the <i>secondCart</i> does not receive the <i>firstCart</i> `MyItem` value. 
Even if register firstCart.ItemChanged in MyStore OnAfterRender, it doesn't work. 
Also notice that if you click on `Increment amount`, it will display the correct value in <i>secondCart</i>. 
Any idea on how to make it work automatically? I mean... without injects, states or other solutions?

**Comment by enetstudio** [comment]
You should let your component know that state has changed, and that it should re-render. Notifying the Component is done by manually calling the StateHasChanged() method.

The StateHasChanged() method is automatically called by Blazor after DOM Events are triggered... This explains why when clicking on the Increment amount button the correct value is displayed in the secondCart. Simply put, the parent component was re-rendered...

Hope this helps...

**Comment by tezine** [comment]
Hi @enetstudio, thank you for the response, but i couldn't find a way to make it work.
I changed the Cart.cshtml code to:
```
@page "/Cart"

<p>Cart: @item</p>

@functions {

    public string item { get; set; }
    public void SetItem(string value) =>Item = value;
    [Parameter] protected Action<string> ItemChanged { get; set; }
    [Parameter] protected string ID { get; set; }    
    [Parameter] protected string Item {
        get => item;
        set {
            item = value;
            Console.WriteLine($"{ID} Changed to " + value);
            StateHasChanged();
            ItemChanged?.Invoke(value);
        }
    }
}
```
and I use it in MyStore.cshtml like this:
```
<Cart ID="firstCart" ref="firstCart" Item="MyItem" ItemChanged="@((value) => secondCart.SetItem(value))"/>
<Cart ID="secondCart" ref="secondCart" Item="@firstCart?.item"></Cart>
<button onclick="@IncrementAmountClicked">Increment amount</button>
```
even using StateHasChanged, I get the following Console ouput:
```
WASM: firstCart Changed to MyItem
WASM: secondCart Changed to
```
Either way, as Angular can accomplish this , I think Blazor should do it automatically, without using some extra code :-(.

**Comment by rynowak** [comment]
This works now, I think this was fixed as part of preview 3
