### ISSUE TITLE
[SignalR] Allow preserveAsyncOrder to be easily configurable

### ISSUE THREAD

**Issue by Jon-Murray** [aspnet/AspNetCore#7047]
Hi,

   I've just been suffering through random, hard to reproduce, deadlocks for a few days. I've finally got to the bottom of the issue which was that mixing async/wait()/Result style code can cause deadlocks with StackExchange.Redis. I was able to fix this by setting the preserveAsyncOrder to false within EnsureRedisServerConnection (inside of RedisHubLifetimeManager.cs). See https://stackoverflow.com/questions/30797716/deadlock-when-accessing-stackexchange-redis

Regardless of my particular usecase, setting preserveAsyncOrder to false will allow for performance increases. I'd imagine the majority of people wouldn't care about this setting, so allowing it to be easily configurable would be beneficial to everyone. Perhaps this can be done as a commented bool when AddRedis is called in ConfigureServices? By nicely commented I mean explaining the benefits and the drawbacks of en/disabling it. I'd also say that it should default to false. 

Thanks!

**Comment by bradygaster** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
