### ISSUE TITLE
Make EndpointMiddleware and EndpointRoutingMiddleware public?

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#7050]
Currently `EndpointMiddleware` and `EndpointRoutingMiddleware` are internal and are only accessible by extension methods off `IApplicationBuilder`.

Other middleware in ASP.NET Core are public. Should these new routing middleware be changed to public?

// @rynowak @Tratcher @davidfowl

**Comment by Tratcher** [comment]
As a rule, yes. 
- Some people compose their own extension methods with different combinations of components.
- It makes testing easier.

**Comment by rynowak** [comment]
I'd really prefer not if can't articulate specific ways it adds value. I don't want to make `Matcher` and `MatcherFactory` public.
