### ISSUE TITLE
HTTP/2 response spread across messages

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#7054]
I'm comparing how Kestrel returns gRPC responses vs the C implementation in Wireshark.

One thing I have noticed is the C implementation always returns the response in a single message (packet? I don't know what the HTTP/2 terminology is) vs Kestrel which sometimes splits the response up into two.

C response:

```
0000   02 00 00 00 45 00 00 78 0a db 40 00 80 06 00 00   ....E..x.Û@.....
0010   7f 00 00 01 7f 00 00 01 c3 83 f7 c9 9f c5 c2 5e   ........Ã.÷É.ÅÂ^
0020   ec 87 52 9e 50 18 08 02 46 d7 00 00 00 00 04 01   ì.R.P...F×......
0030   04 00 00 00 07 88 c2 c1 c0 00 00 20 00 00 00 00   ......ÂÁÀ.. ....
0040   00 07 00 00 00 00 1b 0a 0b 48 65 6c 6c 6f 20 57   .........Hello W
0050   6f 72 6c 64 12 0c 08 b5 e6 ba e2 05 10 dc 8f da   orld...µæºâ..Ü.Ú
0060   d3 02 00 00 04 01 05 00 00 00 07 bf 0f 2f 00 00   Ó..........¿./..
0070   00 04 08 00 00 00 00 00 00 00 00 0c               ............

```

Kestrel single response (note that the response is much larger because of [no header compression](https://github.com/aspnet/AspNetCore/issues/4715)):

```
0000   02 00 00 00 45 00 00 dd 51 6c 40 00 80 06 00 00   ....E..ÝQl@.....
0010   7f 00 00 01 7f 00 00 01 c3 83 f4 fb c4 93 41 ca   ........Ã.ôûÄ.AÊ
0020   a6 c2 0e cd 50 18 08 03 0f f9 00 00 00 00 6c 01   ¦Â.ÍP....ù....l.
0030   04 00 00 00 03 88 00 04 64 61 74 65 1d 4d 6f 6e   ........date.Mon
0040   2c 20 32 38 20 4a 61 6e 20 32 30 31 39 20 30 37   , 28 Jan 2019 07
0050   3a 33 38 3a 34 30 20 47 4d 54 00 0c 63 6f 6e 74   :38:40 GMT..cont
0060   65 6e 74 2d 74 79 70 65 10 61 70 70 6c 69 63 61   ent-type.applica
0070   74 69 6f 6e 2f 67 72 70 63 00 06 73 65 72 76 65   tion/grpc..serve
0080   72 07 4b 65 73 74 72 65 6c 00 0d 67 72 70 63 2d   r.Kestrel..grpc-
0090   65 6e 63 6f 64 69 6e 67 08 69 64 65 6e 74 69 74   encoding.identit
00a0   79 00 00 1f 00 00 00 00 00 03 00 00 00 00 1a 0a   y...............
00b0   0b 48 65 6c 6c 6f 20 57 6f 72 6c 64 12 0b 08 81   .Hello World....
00c0   e3 ba e2 05 10 f4 e1 e0 4d 00 00 0f 01 05 00 00   ãºâ..ôáàM.......
00d0   00 03 00 0b 67 72 70 63 2d 73 74 61 74 75 73 01   ....grpc-status.
00e0   30                                                0
```

Kestrel multiple responses:

```
0000   02 00 00 00 45 00 00 c6 38 99 40 00 80 06 00 00   ....E..Æ8.@.....
0010   7f 00 00 01 7f 00 00 01 c3 83 f5 08 a0 05 22 cb   ........Ã.õ. ."Ë
0020   2d 15 9b fc 50 18 08 01 e9 22 00 00 00 00 6c 01   -..üP...é"....l.
0030   04 00 00 1b 4f 88 00 04 64 61 74 65 1d 4d 6f 6e   ....O...date.Mon
0040   2c 20 32 38 20 4a 61 6e 20 32 30 31 39 20 30 37   , 28 Jan 2019 07
0050   3a 33 38 3a 34 38 20 47 4d 54 00 0c 63 6f 6e 74   :38:48 GMT..cont
0060   65 6e 74 2d 74 79 70 65 10 61 70 70 6c 69 63 61   ent-type.applica
0070   74 69 6f 6e 2f 67 72 70 63 00 06 73 65 72 76 65   tion/grpc..serve
0080   72 07 4b 65 73 74 72 65 6c 00 0d 67 72 70 63 2d   r.Kestrel..grpc-
0090   65 6e 63 6f 64 69 6e 67 08 69 64 65 6e 74 69 74   encoding.identit
00a0   79 00 00 20 00 00 00 00 1b 4f 00 00 00 00 1b 0a   y.. .....O......
00b0   0b 48 65 6c 6c 6f 20 57 6f 72 6c 64 12 0c 08 88   .Hello World....
00c0   e3 ba e2 05 10 fc d5 8f da 01                     ãºâ..üÕ.Ú.
```

```
0000   02 00 00 00 45 00 00 40 38 9b 40 00 80 06 00 00   ....E..@8.@.....
0010   7f 00 00 01 7f 00 00 01 c3 83 f5 08 a0 05 23 69   ........Ã.õ. .#i
0020   2d 15 9b fc 50 18 08 01 d4 f6 00 00 00 00 0f 01   -..üP...Ôö......
0030   05 00 00 1b 4f 00 0b 67 72 70 63 2d 73 74 61 74   ....O..grpc-stat
0040   75 73 01 30                                       us.0
```

Why is the response split into two? One response would be more efficient.

// @davidfowl @Tratcher @JunTaoLuo

**Comment by davidfowl** [comment]
We don't have any buffering so this is entirely possible today, it's the same with HTTP/1.1 messages. We don't have any logic that explicitly buffers an entire response (not do we necessarily want to). It might be easier to control this from application code by using the pipe writer in the response.

**Comment by JamesNK** [comment]
It `Response.Body.WriteAsync(byte[])` prompting Kestrel to sometimes flush the response?

**Comment by davidfowl** [comment]
Yes, it does. There's no buffering by default.

**Comment by halter73** [comment]
https://github.com/aspnet/AspNetCore/blob/78fabbdb40f3367f93c6f96038c268cd4fb16c18/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L220

The above line is the proximate cause of the extra data frame. The surrounding loop is scheduled inline which means that PipeWriter.FlushAsync() followed by PipeWriter.Complete() *always* results in an empty data frame to end the response.

It would be  more efficient to set the END_STREAM flag on the last frame to actually contain data, but this can only happen if at least one of the following is true:

1. We know that response's content length up front. This is the one scenario I think we can easily improve.
2. We don't auto flush. If you use the response Pipe directly and buffer the whole response and complete the PipeWriter without calling FluahAsync, that should avoid the empty data frame.
3. We do some sort of nageling. I hope we don't do this.

The problem is that the loop reading the response data and creating the data frames never sees a completed ReadResult until after all the data has been read.

I thought we already had an idea for this, but I couldn't find it. Thanks for filing this.

**Comment by JamesNK** [comment]
I think I fixed this with https://github.com/aspnet/AspNetCore/issues/4744

**Comment by Tratcher** [comment]
No? #4744 was only for responses without bodies.

**Comment by halter73** [comment]
Though it did effectively fix the issue the special case of bodyless responses.

**Comment by halter73** [comment]
> It might be easier to control this from application code by using the pipe writer in the response.

@JamesNK resurrecting this thread got me thinking about if gRPC could use the response body PipeWriter to avoid sending the extra empty END_STREAM data frame. The problem I see is even with a PipeWriter, you want to call FlushAsync to observe backpressure.

The gRPC code could call Complete without calling FlushAsync, and then the Http2OutputProducer write loop wouldn't wake up until it could see a completed ReadResult at which point it could include the END_STREAM flag in the last DATA frame with actual data. We can't just ignore backpressure though 😞

**Comment by halter73** [comment]
There's one more thing we can do right now without API if we think this is important. So far this has been fixed for the special case of bodyless responses, but we should be able to fix this in any case we know the body content length up front.

**Comment by anurse** [comment]
@JamesNK is this still relevant given some of the other issues you filed?

We think we're as done as we can be for this in 3.0. Moving to backlog.

**Comment by JamesNK** [comment]
I think this is the same as https://github.com/aspnet/AspNetCore/issues/11270

Now I understand HTTP/2 and Kestrel a lot more I can be more specific in my issues 😄
