### ISSUE TITLE
Testing for missing SecurityStamp claim.

### ISSUE THREAD

**Issue by LindaLawton** [aspnet/AspNetCore#7055]
I have been trying to debug an issue where the SecurtyStamp is missing from CookieValidatePrincipalContext.    [SecurityStampValidator#99](https://github.com/aspnet/AspNetCore/blob/d7a7c65b2b40a97bb0ba78c07380c46bc5920400/src/Identity/Core/src/SecurityStampValidator.cs#L99).   

![image](https://user-images.githubusercontent.com/6592543/51822057-689fdc00-22db-11e9-8e7f-0fcf798889b8.png)

I have yet to find the cause of this but what happens is that after the user has been logged in for 30 minutes and the security stamp then needs to be validated that the user is then kicked out no matter what they are doing.

My question is wouldn't it not be smart to be testing if this claim exists every time to catch this error the first time though rather than waiting thirty minutes to then kick out a user because their is something wrong with the claims?

**Comment by blowdart** [comment]
Frankly it sounds like there's no stamp for the user's claims in the database. If it's there and given to us by the store we write it, it's not special, its just a claim with a known name. 

If it's not in the cookie, its either not in the user's claims, or custom user store code is doing something wrong.

**Comment by LindaLawton** [comment]
Actually the issue was caused by another hunk of code that was over writing the cookie created by asp .net identity.    So you have a cookie with the same name containing no stamp even though the stamp was correctly set the first time though. 

I agree its an error in my code.  

However I still think this library should check every time to ensure that there is a security stamp present you dont need to validate it you just need to know its there.   It was very hard to debug this issue as users were able to use the system fine for thirty minutes and then got kicked out no matter what they were doing.   I could see in the database that there was no change in the users security stamp.

If you are going to validate the security stamp every thirty minutes then i think it makes sense to validate that the security stamp is actually present at all times.

**Comment by blowdart** [comment]
As we added better errors, closing
