### ISSUE TITLE
double AntiforgeryToken cookie on localhost when switching between iis and iisexpress

### ISSUE THREAD

**Issue by omuleanu** [aspnet/AspNetCore#7056]
using an ASP.NET Core application with:
`o.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());`
 if you run it locally ( Ctrl+F5 in VS2017 ) using IIS and switch the `launchSettings` between `IISExpress` and `IIS` and runt it (launch browser) each time, when you switch back to `IIS` you will get 2 antiforgery cookies with the same name and also the post requests will fail with 400 bad request

![antiforg](https://user-images.githubusercontent.com/2010805/51828507-65fdb080-22f4-11e9-8435-2cfa01b4d748.png)

on mvc5 this is not a problem, I can switch between IIS and IISExpress, and the cookie isn't doubled, and the requests don't fail

**Comment by LindaLawton** [comment]
They have different paths which might be what is causing the post to fail.

**Comment by blowdart** [comment]
It is, as @LindaLawton said. If your application is under a path anti-forgery, and I believe identity, will limit the cookie to the path your app resides under.

You can configure the path, but this isn't really a scenario you'd see outside of development.

**Comment by omuleanu** [comment]
ok, so I configured the path, and the problem is solved, the cookie isn't doubling anymore
```
services.AddAntiforgery(options =>
{
	options.Cookie.Path = "Path";
});
```

**Comment by blowdart** [comment]
Cool :) I'll close the issue.
