### ISSUE TITLE
[SignalR] Transport is not switched after handshake failure

### ISSUE THREAD

**Issue by alexalok** [aspnet/AspNetCore#7057]
### Describe the bug
I am using a SignalR Core .NET client in a .NET Framework 4.6.2 WPF application to connect to a hub that is behind a nginx proxy. This proxy does not allow server-sent events to work. When trying to connect on Windows 7 or below Websocket is unavailable so server-sent events are used. However, after failing with handshake error connection simply stops without trying the last option (long polling). 

### To Reproduce
1. Start application with SignalR .NET client on Windows 7 or older 
2. Start connection to a hub behind a nginx proxy
3. Connection fails due to handshake timeout

### Expected behavior
After handshake error happends client should try to connect using long polling.

### Client logs
```2019-01-28 07:16:19.5826|	Connecting to SignalR hub on https://example.com/hub
2019-01-28 07:16:19.6186|	Starting HubConnection.
2019-01-28 07:16:19.6616|	Starting HttpConnection.
2019-01-28 07:16:19.6806|	Establishing connection with server at 'https://example.com/hub'.
2019-01-28 07:16:20.1296|	Established connection 'ejC3nAjEESgU6eZBHDliCQ' with the server.
2019-01-28 07:16:20.1466|	Skipping WebSockets because they are not supported by the operating system.
2019-01-28 07:16:20.1516|	Starting transport 'ServerSentEvents' with Url: https://example.com/hub?id=ejC3nAjEESgU6eZBHDliCQ.
2019-01-28 07:16:20.1786|	Starting transport. Transfer mode: Text.
2019-01-28 07:16:35.3445|	Starting receive loop.
2019-01-28 07:16:35.3685|	Received 49 bytes. Parsing SSE frame.
2019-01-28 07:16:35.3945|	Passing message to application. Payload size: 36.
2019-01-28 07:16:35.3945|	Receive loop stopped.
2019-01-28 07:16:35.3945|	Starting the send loop.
2019-01-28 07:16:35.4085|	Send loop canceled.
2019-01-28 07:16:35.4085|	Send loop stopped.
2019-01-28 07:16:35.4085|	Transport 'ServerSentEvents' started.
2019-01-28 07:16:35.4085|	HttpConnection Started.
2019-01-28 07:16:35.4085|	Using HubProtocol 'json v1'.
2019-01-28 07:16:35.4085|	Sending Hub Handshake.
2019-01-28 07:16:35.4555|	Error starting connection.
2019-01-28 07:16:35.4555|	Disposing HttpConnection.
2019-01-28 07:16:35.4555|	Transport is stopping.
2019-01-28 07:16:35.4555|	Transport stopped.
2019-01-28 07:16:35.4555|	HttpConnection Disposed.
2019-01-28 07:16:35.4555|	Exception while trying to reconnect to hub, trying again in 1 minute: System.InvalidOperationException: The server disconnected before the handshake was completed
   в Microsoft.AspNetCore.SignalR.Client.HubConnection.<HandshakeAsync>d__61.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__47.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__47.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__39.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MyApplication.MyHub.<Connect>d__7.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MyApplication.MyHub.<Reconnect>d__14.MoveNext()```

**Comment by muratg** [comment]
Is nginx the only in between the client and the server, or is there a corporate proxy in between? Is your nginx setup on Kubernetes?

Did you try just setting long polling directly from client and verify it works?

**Comment by alexalok** [comment]
Hi, @muratg 

> Is nginx the only in between the client and the server, or is there a corporate proxy in between?

Nginx is only between the client and the server and I have made sure it is nginx that is causing the issue because direct client-server connections establish successfully. 

> Is your nginx setup on Kubernetes?

My setup is a regular server without any containers. 

> Did you try just setting long polling directly from client and verify it works?

Yes, explicitly disabling websocket and sse results in a successful long-polling connection. However, the reason I reported the issue is that I believe that in case of a handshake failure another transport should be tried instead of just failing and closing the connection. 

I also found a likely reason for sse to fail is nginx buffering. To disable it every SignalR response from server must contain `X-Accel-Buffering: no` header. Unfortunately, I haven't found the way to do this and it seems like [SO](https://stackoverflow.com/questions/54399578/setting-a-default-header-for-all-signalr-core-hubs-in-self-hosted-asp-net-core-s) isn't of much help as well. Perhaps you could give a piece of advice on that matter?

**Comment by muratg** [comment]
@alexalok can you share your nginx configuration?

**Comment by alexalok** [comment]
Sure thing.

```
server {
	listen 443 ssl http2;
	server_name example.com;

	access_log access.log;
	error_log error.log;

	root /var/www/example.com;
	location / 	{
	proxy_pass		http://localhost:5001;
        proxy_http_version	1.1;
		
        proxy_set_header	Upgrade $http_upgrade;
        proxy_set_header	Connection $http_connection;
        proxy_set_header	Host $host;
        proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header	X-Forwarded-Proto $scheme;
		
	keepalive_timeout	2m;
	keepalive_requests	100000;
	proxy_read_timeout	2m;
	proxy_connect_timeout	1m;
	proxy_send_timeout	1m;
	send_timeout		1m;
		
	proxy_cache_bypass	$http_upgrade;
	}

    ssl_certificate fullchain.pem; 
    ssl_certificate_key privkey.pem; 
}
```

**Comment by BrennanConroy** [comment]
Could you try turning buffering off? `proxy_buffering off;`

@davidfowl Should we consider falling back if the handshake fails? In ASP.NET SignalR we sent a `/connect` request over the selected transport and if that failed I believe we fell back to the next transport.

**Comment by alexalok** [comment]
@BrennanConroy, turning buffering off indeed fixes the issue but I would like to disable it only for SignalR requests.

**Comment by BrennanConroy** [comment]
I don't know if nginx has support for that. For now you can disable ServerSentEvents on the server so your clients wont even try that transport.

```csharp
app.UseSignalR(routes =>
{
    routes.MapHub<HubClass>("/hubroute", options =>
    {
        options.Transports = HttpTransportType.WebSockets | HttpTransportType.LongPolling;
    });
});
```

**Comment by BrennanConroy** [comment]
Maybe the below would work?
```
server {
    location /hubroute {
        // proxy settings here
    }
}
```

**Comment by alexalok** [comment]
Thanks, @BrennanConroy! I've used that as a workaround. However, as I have stated previously, there is also another possible solutuion. Nginx will disable caching for any responses containing `X-Accel-Buffering: no`. Perhaps there is a way to set this header for all SignalR responses?

**Comment by BrennanConroy** [comment]
You can set that yourself by adding to the headers in the options from `WithUrl` on the client. https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.2#configure-additional-options

`X-Accel-Buffering` seems nginx specific, so we probably wouldn't add it by default to every single request. However we might want to talk about it in our docs.

**Comment by alexalok** [comment]
Thanks, just what I needed!

**Comment by BrennanConroy** [comment]
I'm going to keep this open for us updating our docs, and deciding on the handshake behavior

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
