### ISSUE TITLE
connect two .net applications using signalr

### ISSUE THREAD

**Issue by vikasNew** [aspnet/AspNetCore#7059]
Hi,

i have a scenario where i have two .net core applications & i want to communicate between them.

So how to use Signalr to do communication between them.

which one will be client & where to set hubs. i have installed .net client in first application to work as a signalr client & the other end i have put hubs. but i need bi-directional communication so can you please tell me how to call hub methods from a controller action methods in second application.

there are no js in both of the projects, i only have controllers & action methods defined in both the applications. i need to call first app methods from second app & second app methods from first application.

please guide me how to achieve this.

Thanks in anticipation

**Comment by vikasNew** [comment]
any updates on this

**Comment by bradygaster** [comment]
If you have two client applications, both written in .NET, you would **still** need to have a server-side application or a long-running background service that hosts your Hub. You can't host your Hub in a client app, it must be in a server-side app. Or, you could use the Azure SignalR Service if you're an Azure user. Either way, you need a third piece, the Hub, running on a web server or hosted in a background app. 

Now, if what you want to do is call a controller and have the controller push out to the clients using SignalR, that's a little more complex of a scenario. Either way, you will need to host your Hub and your controllers (if you need them because you prefer to use the controllers to receive data rather than use your Hub to invoke methods on the server-side) on a server-side app. Then, both of your client apps can connect to the Hub and/or controllers. 

You can't host the controllers and the Hub in either of your client apps.

**Comment by bradygaster** [comment]
> So i how can i achieve this complete Request/response cycle with two clients.

You can't. You have to have a Hub, *running on a server*, or use the Azure SignalR Service as a channel for the communication. SignalR is **not** peer-to-peer. 

Let's think about your architecture as a Visual Studio solution. You've currently got 2 .NET Client applications - either WPF, Desktop, whatever-it-is. You shouldn't have a Hub in *either* of those projects, as you have nowhere to host them. That is, unless you've bootstrapped one of them as an HTTP endpoint. In that case. one client could be the "client" and the other, the server. But I digress...

If you think of your current topology as a VS Solution, you would need to add a third, new project to it. That project would be a console application or a web app, and it would host your SignalR Hub/endpoint. Then, your two client apps would use the .NET Client for SignalR to communicate with that Hub. That way, each message sent to the hub hosted in the output of "project C" received by either "project A" or "project B" (the client apps), the Hub in project C would bounce those messages out to both of the clients (projects A and B). 

Does that make sense? If it'd help I could try to put together a quick Gist sample to demonstrate the whole thing end-to-end.

**Comment by vikasNew** [comment]
can you please update me this with some examples, i have tried this with Azure SignalR service but still i am not able to get response from the same hub method..

**Comment by bradygaster** [comment]
I have the server and one of the client apps already created. I'll share this with you later today, but I need to finalize one or two things on the second client so you have what you want.

**Comment by bradygaster** [comment]
@vikasNew i've created the example and put it in my personal GitHub organization [here](https://github.com/bradygaster/OneRealTimeServerTwoClients). 

> Note: this isn't "guidance," but an example. YMMV, and you can feel free to customize it all you want. 

This example has the following items in it:

1. Hosting an ASP.NET Core SignalR Hub using a simple EXE. 
1. The Hub is actually a strongly-typed Hub<T>, which is documented [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2#strongly-typed-hubs). 
1. An example of using a `BackgroundService` to trigger events the Hub<T> sends out to the clients. This scenario is a rather large implementation of a server-side clock, so the `T` in this example is an interface `IClock`. As the background service "ticks," the time is sent via the Hub<IClock>.  
1. Client One is a **very** basic .NET Core client in a Console App. 
1. Client Two is another "worker" app that makes use of the ASP.NET Core Hosting runtime. Client Two contains an implementation of the `IClock` interface, so you can see one way in which you could have a shared "service interface." 

> Note: No association with WCF is implied here, this shouldn't be confused with WCF service interfaces. Similar idea, but *very* different technology. 

To run the sample:

1. `dotnet build` in the root
1. `dotnet run` in the server folder
1. `dotnet run` in each/either of the client folders

As this sample demonstrates a "1-hub, N-client" scenario I'll close this issue. Then, we'll use this code in a few upcoming documentation articles. I hope this is helpful!
