### ISSUE TITLE
Access to options in HttpClient configuration?

### ISSUE THREAD

**Issue by thomaslevesque** [aspnet/AspNetCore#7061]
I'd like to configure a typed `HttpClient` based on options. However I don't have access to the options (or to the service provider) in the configuration delegate.

```
services.Configure<FooClientOptions>(Configuration.GetSection("FooClient"));
services.AddHttpClient<FooClient>(client =>
{
    // Here I'd like to access FooClientOptions, but I don't have an IServiceProvider
    client.BaseAddress  = ...
});
```

How can I access the options from the configuration delegate? If it's not currently possible, it would be a useful addition.

**Comment by dallancarr** [comment]
There is an overload which passes `IServiceProvider`

**Comment by dallancarr** [comment]
https://github.com/aspnet/HttpClientFactory/blob/5bb701daaa087dd8dc0f0a882117e316675dda6d/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs#L46

**Comment by thomaslevesque** [comment]
Doh, how did I miss that? Thanks @dallancarr!
