### ISSUE TITLE
[Blazor] Enable SimpleJson Support for IReadOnly*<T> Collection Interfaces

### ISSUE THREAD

**Issue by TheXenocide** [aspnet/AspNetCore#7063]
### Is your feature request related to a problem? Please describe.
I'm torn between considering this a bug or a feature, but I was unable to use some existing contracts across JSON deserialized requests due to the use of an `IReadOnlyCollection<T>` return type. According to the [SimpleJson repository](https://github.com/facebook-csharp-sdk/simple-json), support for deserializing these types is enabled with a compile-time constant. I'm not certain whether there is benefit/intention in using the new UTF-8/`Span`-based JSON implementation forthcoming in Core 3, but either way the use of existing contracts employing these interfaces would be helpful.

### Describe the solution you'd like
Please support deserialization of read-only collection interfaces.

### Describe alternatives you've considered
Use of `IReadOnlyCollection<T>` over `IEnumerable<T>` was defined, in part, to ensure iterator-based implementations were forced to be evaluated before exiting the scope of the request, since response serialization was occurring outside of authorized contexts supplied by middleware. We can convert our contracts to use alternative types (e.g. `List<T>` or an array) but we consider this less expressive of the expectations of use otherwise definable in the contract.

**Comment by Andrzej-W** [comment]
@TheXenocide read this old thread https://github.com/aspnet/Blazor/issues/1283

**Comment by TheXenocide** [comment]
Thanks for the reference (and the subsequent breadcrumb trail I followed through a myriad of other issues lol).
