### ISSUE TITLE
Copyright element in Microsoft.AspNetCore.Blazor.Cli is malformed

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#7065]
Looks like an encoding issue in the nuspec. Due to account restrictions, this is blocking us from uploading this package to nuget.org. We need to fix it so this starts with the &copy; character.

![image](https://user-images.githubusercontent.com/2696087/51854202-18c31400-22df-11e9-8095-c8db966b3a43.png)

**Comment by robertmclaws** [comment]
Out of curiosity, why aren't you using nuspec files instead of packaging from the .csproj file and leveraging the Copyright message from the root's Directory.Build.props?

**Comment by robertmclaws** [comment]
Gotcha! I tried to push a fix for this, I figured it would be a quick thing I could help out with, but I copied the symbol from a couple other places in the repo and GitHub Desktop is not recognizing that anything changed. Can you provide more details abouo the issue?
