### ISSUE TITLE
Possible issue with OAuth with external Identity provider + CORS

### ISSUE THREAD

**Issue by ManaX** [aspnet/AspNetCore#7079]
I am developing a .net core 2.2 webAPI project for RESTful services. I have configured it to challenge OAuth authentication with an external Identity server (to get userinfo from Windows directory) and then use Cookie authentication to manage Identity/access. 

Everything works well for normal http requests. But when I make a XHR request from an Angular app, The request fails at **/Authorize** step because the request header has "Origin": null
![image](https://user-images.githubusercontent.com/3582131/51874247-41262f00-232e-11e9-91c1-70af27e96ac3.png)

### To Reproduce
1. An XHR request to an end-point automatically spawns a challenge (**user/login**) to the Identity server 
![image](https://user-images.githubusercontent.com/3582131/51922383-ef75b700-23b6-11e9-9555-ea0400c89398.png)

2. The **authorize** endpoint as shown in the screen shot is then created but with **Origin: null** in its headers
3. The Identity server copies the header value in request and adds it to **Access-Control-Allow-Origin** in the response
4. The browser rejects the new callback URL, **signin-auth0** redirection and throws:
![image](https://user-images.githubusercontent.com/3582131/51874543-6d8e7b00-232f-11e9-9f30-9e6bff09fadc.png)

**Startup.cs**
```
    public void ConfigureServices(IServiceCollection services)
        {
            . . .
            services.AddCors(o => o.AddPolicy("CORSPolicy", builder =>
            {
                builder.WithOrigins("http://blah.com:8080")
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials();
            }));

            services.Configure<CookiePolicyOptions>(options => AuthenticationHandler.ConfigCookiePolicyOptions(options));

            services
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddCookie(options => AuthenticationHandler.ConfigCookieOptions(options))
                .AddOAuth("OAuth", options => AuthenticationHandler.ConfigOAuthOptions(options));

            . . . 
        }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            . . .
            app.UseCors("CORSPolicy");
            app.UseCookiePolicy();
            app.UseAuthentication();           
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
            . . .
        }

```
 **User/Login route**
```
        [Route("api/[controller]/[action]")]
        [HttpGet, AllowAnonymous]
        public async Task Login(string redirect_uri)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                Redirect(redirect_uri);
            }
            await HttpContext.ChallengeAsync("OAuth", new AuthenticationProperties() { RedirectUri = redirect_uri });
        }
```
### Additional context
This will be deployed on a Heroku server.
And my cookie policy is set to **Lax**

Please let me know if you need more information OR snippets of my OAuth/Cookie Policy configuration. I have omitted excess code for brevity. 

Thank you.

**Comment by pranavkm** [comment]
>  But when I make a XHR request from an Angular app, The request fails at /Authorize step because the request header has "Origin": null

@ManaX is this a browser that sends a `null` origin?

**Comment by ManaX** [comment]
> But I am not sure why the request headers are not copied along with each each redirect.
Authorization headers specifically.

**Comment by pranavkm** [comment]
I'm not entirely sure about the auth headers here, but I want to eliminate CORS as a possible culpint here. 

It looks like browsers will send a `null` origin if the request redirects to a new origin so that would explain the odd value there. 

* The response to `signin-auth0` endpoint in your application shows a 500. Is there an uncaught exception that you have to handle?
* Is the browser client hosted on `http://mpawarpc.pc.factset.net:8080`? Is that the origin listed in the CORS policy configured in your application:

```C#
services.AddCors(o => o.AddPolicy("CORSPolicy", builder =>
            {
                builder.WithOrigins("http://mpawarpc.pc.factset.net:8080")
```

**Comment by ManaX** [comment]
> It looks like browsers will send a null origin if the request redirects to a new origin so that would explain the odd value there.

Yes, this makes sense and furthermore this stackoverflow [answer](https://stackoverflow.com/a/28671822) clears the doubt. My suspect is, when I call ChallengeAsync here,
```
     await HttpContext.ChallengeAsync("OAuth", new AuthenticationProperties() { RedirectUri = redirect_uri });
```
The challenge request sets "Origin" to "null" and then makes the `authorize/` call

> * The response to signin-auth0 endpoint in your application shows a 500. Is there an uncaught exception that you have to handle?

Browser sets this when XHR fails, the console has: 
`origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

> * Is the browser client hosted on http://mpawarpc.pc.factset.net:8080? Is that the origin listed in the CORS policy configured in your application:

Yes, haha I have the right origin in the actual code. Edited it here lol


So my next question would be, is there a work around or a better way to Challenge the OAuth server or hide the  challenge process from the browser?

**Comment by pranavkm** [comment]
cc @javiercn

**Comment by pranavkm** [comment]
> Browser sets this when XHR fails, the console has:

Are you certain about this? That seems suspect since a failed CORS response will not result in the browser changing the server response.

**Comment by ManaX** [comment]
Quoting from here,
> Everything works well for normal http requests. But when I make a XHR request from an Angular app

1. When I make a regular browser call to my endpoint `user`:
![image](https://user-images.githubusercontent.com/3582131/51951323-2de49380-2402-11e9-831c-fa317f3a9fc3.png)

2. When I make XHR call from AngularJS client (`withCredentials: true`)
![image](https://user-images.githubusercontent.com/3582131/51951427-92075780-2402-11e9-8591-8fb6af36be47.png)

#### More context

1. In XHR land, for the first 2 calls, `Origin` is set in request headers and response headers contain 
![image](https://user-images.githubusercontent.com/3582131/51951747-c62f4800-2403-11e9-80e2-15ee5f6881b9.png)
   and authorize has
![image](https://user-images.githubusercontent.com/3582131/51951787-ed861500-2403-11e9-912d-229ac32a1c47.png)

2. I checked fiddler, `authorize/` is called twice and, first returns 401 and then a challenge is added to the same call after which redirection is successful.
![image](https://user-images.githubusercontent.com/3582131/51952103-34c0d580-2405-11e9-9413-4ab8364ef953.png)

3. `/signin-auth0` actually throws this error (I am sorry for wrong information prior)
![image](https://user-images.githubusercontent.com/3582131/51952063-fcb99280-2404-11e9-863b-21a200ab82f1.png)

**Comment by javiercn** [comment]
> services .AddAuthentication(options => { options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme; options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme; }) .AddCookie(options => AuthenticationHandler.ConfigCookieOptions(options)) .AddOAuth("OAuth", options => AuthenticationHandler.ConfigOAuthOptions(options));

I'm pretty sure this is incorrectly configured.

It seems like you are trying to start an oAuth login flow from an XHR request, that's not how it works. If you are building a SPA, you are required to do a full navigation to the identity provider. It can't be done through an XHR request and that's at the core of your issue.

You can do two things:
1) From the client (browser) perform an implicit flow (and get the id_token and an access_token on the SPA app, in JavaScript) and configure the appropriate middleware on the server to validate the access_token. If there is no valid access token API calls will return 401. If there is 
2) Perform an implicit flow from the server, stamp a cookie out of it and use the cookie for authenticating the user against the APIs.

Of the two options the first one is by far the best in terms of security. Id recommend you ask on stackoverflow about the details of how to achieve this scenario.

CORS seem to be working as expected in this scenario.

Hope this helps.

**Comment by ManaX** [comment]
Yes, I was trying to to have one solution for all scenarios. I will now user Token authentication for SPA side of the application and OAuth+Cookie for RESTful aspects.

Thank you for your guidance @pranavkm and @javiercn!
