### ISSUE TITLE
MessagePackHubProtocols error when work on RazorComponent(AddServerSideBlazor) in 3.0 preview

### ISSUE THREAD

**Issue by JialinXin** [aspnet/AspNetCore#7083]
### Describe the bug
Exception details:
![image](https://user-images.githubusercontent.com/15338714/51882069-8e4ee300-23b8-11e9-99d1-8270bd371479.png)

### To Reproduce
Using this version of ASP.NET Core 3.0 preview
1. Create Blazor server side project under core 2.1 with Blazor template
2. Upgrade the project to core 3.0 by update the target framework and update project reference (remove Microsoft.AspNetCore.App)
3. Run the project met above exceptions

### Additional context
Should AddServerSideBlazor() already in the AspNetCore package? But seems add reference of Microsoft.AspNetCore.Blazor.Server is still required.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JialinXin.
Do you experience this issue on the latest version of Blazor?

**Comment by JialinXin** [comment]
Working on the latest version for RazorComponent it's good. I'm closing this issue. Thanks!
