### ISSUE TITLE
[Announcement] : AspNetCoreModule V1 removed from Windows Hosting Bundle 

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7095]
Discussion thread for https://github.com/aspnet/Announcements/issues/339

**Comment by jeremycook** [comment]
It wasn't obvious to me from the announcement exactly what this would break, if anything. If I'm running .NET Core 2.0 (yes I know), 2.1, and eventually 3.0 web apps on the same server, should I be concerned about upgrading with the latest Windows Hosting Bundle installer causing any problems with the applications?

**Comment by poke** [comment]
Since release of ANCM were never publicly talked about, could you please clarify what ASP.NET Core versions each of the ANCM versions supports?

i.e. is ANCM v1 required only for ASP.NET Core 1.x, and ANCM v2 can run ASP.NET Core 2.x and 3.x?

**Comment by pakrym** [comment]
@poke 

AspNetCoreModule V1 is supported with ASP.NET Core 2.1/2.2

AspNetCoreModule V2 is supported with ASP.NET Core 2.2/3.0/onward

**Comment by poke** [comment]
Cool, thanks! So basically, v2 added the in-process support I guess?

**Comment by pakrym** [comment]
> Cool, thanks! So basically, v2 added the in-process support I guess?

Yes

> Btw. it’s still possibly to install both v1 and v2 on the same machine by installing the Hosting Bundle for e.g. both 2.1 and 3.0, right?

Yes

**Comment by John0King** [comment]
Suggest to release the `ANCM` and `dotnet hosting bundle` to the WebPI

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
