### ISSUE TITLE
Get original request url path in the Error handler action 

### ISSUE THREAD

**Issue by omuleanu** [aspnet/AspNetCore#7097]
in `Startup.cs` I use this code:
```
app.UseStatusCodePagesWithReExecute("/Error/HttpStatus", "?code={0}");
```
and the action look like this:
```
public IActionResult HttpStatus(int? code)
{
    if (code == 404)
    {
        var path = Request.Path;
...
```
`path` will have the value = `Error/HttpStatus`, I need to know what was the original url that was requested and wasn't found.

My problem is that I don't want to `return View("HttpError404")`  when the request url is something like `signalr.js.map`

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by omuleanu** [comment]
ok, so basically, in the controller I had to do this:
```
var feature = Request.HttpContext.Features.Get<IStatusCodeReExecuteFeature>();
var path = feature.OriginalPath;
```

**Comment by pranavkm** [comment]
Closing since the question has been answered.
