### ISSUE TITLE
[Static Files] Support .apng files

### ISSUE THREAD

**Issue by clintnetwork** [aspnet/AspNetCore#7101]
Hi,

The .apng file and his mimetype is not supported as a static file, it's a format for PNG animations.

I make this to support it, but I think it should be supporte natively.

```csharp
public void Configure(IApplicationBuilder app)
{
    app.UseStaticFiles(new StaticFileOptions
    {
        ServeUnknownFileTypes = true,
        DefaultContentType = "image/png"
    });
}
```

**Comment by Tratcher** [comment]
Spec reference: https://www.iana.org/assignments/media-types/image/png

Do not use ServeUnknownFileTypes and DefaultContentType for this. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.2#fileextensioncontenttypeprovider for adding your own file extensions.

**Comment by clintnetwork** [comment]
Ha thank you, I will change tomorrow

**Comment by Tratcher** [comment]
@shirhatti. We still don't have clear guidance on what we will and won't add to this list.

**Comment by shirhatti** [comment]
Hmm 😕 

I'm almost certain that we agreed that our stance on this going forth is will not accept any contributions to our known extensions/MIME types. In addition to what we already have, we will limit new extensions to only those assets shipped by our templates.

**Comment by shirhatti** [comment]
@muratg to (hopefully) confirm what I said

**Comment by Tratcher** [comment]
Do we have that in writing somewhere our contributors can see it?

**Comment by shirhatti** [comment]
The latter option

**Comment by Tratcher** [comment]
Ok, write it up pretty and we'll paste it in there.

**Comment by clintnetwork** [comment]
Maybe there some new extensions that add too (webm or webp by example)

**Comment by Tratcher** [comment]
Closing this based on our updated guidance in https://github.com/aspnet/AspNetCore/pull/8213.
