### ISSUE TITLE
Possibility to remove Controllers at runtime

### ISSUE THREAD

**Issue by Fruchuxs** [aspnet/AspNetCore#7118]
### Is your feature request related to a problem? Please describe.
We have a Test-Controller in our Web API which can be used at runtime to determine problems. But this controller should only be present if a Debug-Flag is set in the application config.

### Describe the solution you'd like
Middleware decorator or possibility to reconfigure IRouter to kick out an auto registred controller.

### Describe alternatives you've considered
- IRouter Decorator - but doesnt work
- IControllerActivator with just return "null", but results in an exception - redirect to 404 ErrorController seems complicated
- Authorization-Check, but doesn't feels good

**Comment by RemiBou** [comment]
Why don't you throw an exception on the controller constructor when the config is not set ? And use a filter for changing it to a 404.

**Comment by Fruchuxs** [comment]
Not a bad Idea, but I think its cleaner to just "deregister" the controller.

**Comment by pranavkm** [comment]
You could use application parts to conditionally add or remove the controller: https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.2#application-feature-providers.
