### ISSUE TITLE
Cookie And Session 

### ISSUE THREAD

**Issue by kickgod** [aspnet/AspNetCore#7119]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

I just want to use Session and cookies just like the ASP.NET MVC framework, but the authorization and identity features provided by ASP.NET Core don't allow me to simply use cookies and sessions. I am very annoyed, for the identity and authorization features that come with the framework, and often the permissions and authorization functions are designed by ourselves, rather than using the framework. I think it is as simple as ASP.NET MVC. I hope to provide such a feature!

**Comment by Eilon** [comment]
@kickgod - sorry you were running into some problems. Can you provide more info and code samples that show what you were trying to do, what you expected to happen, and what actually happened?

Session state is fully supported in ASP.NET Core, and uses a cookie to track the user. Authorization and identity can also use cookies (but a different cookie). Your app can also just create its own cookies for other purposes. Much of this code is very similar (though not identical) so previous versions of ASP.NET.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
