### ISSUE TITLE
Console.WriteLine produces strange text in Blazor 0.8.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7124]
Repro steps:
- `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19075-0444`
- `dotnet new blazor -o BlazorApp1`
- Edit *Program.cs* to add `Console.WriteLine("Hello, world!");` in `Program.Main`

Expected result:
- Browser dev console shows: "Hello, world!"

Actual result:

![image](https://user-images.githubusercontent.com/1874516/51972551-8d2ebc00-2473-11e9-81a9-ab5002ebeccf.png)

WASM: mono_pe_file_map: Error opening file mscorlib.dll (3): No such file or directorymono_pe_file_map: Error opening file Mono.WebAssembly.Interop.dll (3): No such file or directorymono_pe_file_map: Error opening file Microsoft.JSInterop.dll (3): No such file or directorymono_pe_file_map: Error opening file BlazorApp1.dll (3): No such file or directorymono_pe_file_map: Error opening file Microsoft.AspNetCore.Blazor.dll (3): No such file or directorymono_pe_file_map: Error opening file Microsoft.Extensions.DependencyInjection.Abstractions.dll (3): No such file or directory﻿Hello, world

**Comment by danroth27** [comment]
@SteveSandersonMS @lewing

**Comment by lewing** [comment]
I think this was a temporary logging regression in mono right around the hash you pulled. See https://github.com/mono/mono/pull/12588

**Comment by tezine** [comment]
In my case, Console.WriteLine simply doesn't write anything. I can hit a breakpoint while debugging razor components, but nothing is displayed in chrome console.

**Comment by danroth27** [comment]
@tezine  Console.WriteLine will only write to the browser console when you're running client-side in the browser. For a Razor Components app Console.WriteLine will write to the console on the server.

**Comment by tomRedox** [comment]
> 

> @tezine Console.WriteLine will only write to the browser console when you're running client-side in the browser. For a Razor Components app Console.WriteLine will write to the console on the server.

For anyone who doesn't know, you can see the server console in the Output window in Visual Studio, just select 'ASP.NET Core Web Server in the select list:

![image](https://user-images.githubusercontent.com/11335350/58373053-56e3e380-7f1f-11e9-855f-c73935e5d964.png)

**Comment by RoroTiti** [comment]
> 
> 
> > 
> 
> > @tezine Console.WriteLine will only write to the browser console when you're running client-side in the browser. For a Razor Components app Console.WriteLine will write to the console on the server.
> 
> For anyone who doesn't know, you can see the server console in the Output window in Visual Studio, just select 'ASP.NET Core Web Server in the select list:
> 
> ![image](https://user-images.githubusercontent.com/11335350/58373053-56e3e380-7f1f-11e9-855f-c73935e5d964.png)

So many thanks for that... I was stuck on Debug log...
