### ISSUE TITLE
Autorebuild not working with Blazor 0.8.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7125]
Repro steps:
- Install the Blazor VSIX
- Create a new standalone Blazor app
- Ctrl-F5 to run it
- Change the heading text in Index.cshtml (or some other visible change)
- Refresh the browser

Expected result: Change to home page is visible after refreshing the browser
Actual result: Home page looks the same

**Comment by mkArtakMSFT** [comment]
Closing as this is external.
