### ISSUE TITLE
@Html.DisplayFor resulting in microsoft.aspnetcore.mvc.viewfeatures.internal.viewbuffer

### ISSUE THREAD

**Issue by ankitgupta2k19** [aspnet/AspNetCore#7129]
### Describe the bug
when using tag helper @Html.DisplayFor at some instances its returning microsoft.aspnetcore.mvc.viewfeatures.internal.viewbuffer in view instead of formatted value.
### To Reproduce
1. Using this version of ASP.NET Core '2.1'
2. Run this code '....'
3. With these arguments '....'

### Expected behavior
Its not happening for all usgaes, but at certain places its giving viewbuffer in output. For Example : when display for used for date format instead of displaying 30 jan 2019 its showing microsoft.aspnetcore.mvc.viewfeatures.internal.viewbuffer in view
### Additional context
Include the output of `dotnet --info`

**Comment by blowdart** [comment]
Can you give code examples of such an @Html.DisplayFor, and the model used?

**Comment by ankitgupta2k19** [comment]
Something like this : addonPrice.Total has 5.65 as value
Html.DisplayFor(modelItem => addonPrice.Total);
But on view it shows microsoft.aspnetcore.mvc.viewfeatures.internal.viewbuffer

**Comment by blowdart** [comment]
What type is total price?

**Comment by ankitgupta2k19** [comment]
Its decimal type. When displayed as string it works fine. But when Html.DisplayFor it renders view buffer

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
