### ISSUE TITLE
Update survey link in the project template for Blazor 0.8.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7130]
Blazor 0.8.0 survey link: ~~https://go.microsoft.com/fwlink/?linkid=2041371~~ https://go.microsoft.com/fwlink/?linkid=2069004

**Comment by SteveSandersonMS** [comment]
That URL is the same one you put in for 0.7.0 in this commit: https://github.com/aspnet/AspNetCore/commit/71cddc35632ac7cd36ef1cb19892a9f55d8333ec

Is there a different URL for 0.8.0?

**Comment by danroth27** [comment]
Sorry about that: https://go.microsoft.com/fwlink/?linkid=2069004
