### ISSUE TITLE
[SignalR] Differentiating disconnect vs manual close event

### ISSUE THREAD

**Issue by niwsa** [aspnet/AspNetCore#7131]
I am trying to implement reconnect logic when signalr disconnects due to network failure as follows.
```
 signalrStartConnection = () => {
    this.state.hubConnection
      .start()
      .then(() => {
        console.log("signalr connected");
      })
      .catch(err => {
        console.error(`could not connect to signalr server ${JSON.stringify(err)} Retrying in 5 seconds`);
        this.signalrRetryTimer = setTimeout(() => this.signalrStartConnection(),5000);
      });
  };
 signalrCloseConnectionHandler = error => {
    console.error(` hubconnection closed reason: ${JSON.stringify(error)}`);
    this.signalrStartConnection();
  };


...
...
this.state.hubConnection.onclose(this.signalrCloseConnectionHandler);
this.signalrStartConnection();
```
But at the same time I need to close the connection on page navigation elsewhere (componentWillUnmount).
```
componentWillUnmount() {
    const { hubConnection } = this.state;
    if (hubConnection !== null) {
      hubConnection.stop();
    }
}
```
Issue is when I call the `hubConnection.stop` the onclose listener (`signalrCloseConnectionHandler`) fires which again starts the connection.Is there a `off` to remove the onclose listener?

**Comment by mikaelm12** [comment]
Hi @niwsa. It looks like you'd be better served by adding a simple flag check to see if you should run your reconnect logic. That seems like a cleaner approach than removing (and potentially having to re add) onClose handlers, which we don't really support.

**Comment by niwsa** [comment]
@mikaelm12 Thanks for the solution.
I am using a `_isMounted` instance field which is set to true on `componentDidMount`,setting it to false on `componentWillUnmount`.Using the flag as below before reconnecting...
```
signalrCloseConnectionHandler = error => {
    if (this._isMounted) {
      console.log(
        `socket disconnect: ${JSON.stringify(error)} Reconnecting ...`
      );
      this.signalrStartConnection();
    }
  };
```
