### ISSUE TITLE
Update Blazor 0.8.0 packages to have a clean version number (no preview moniker)

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7133]
It's harder to install a template package when it has a preview moniker, because you have to specify the version explicitly:

You have to do this:

```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19075-0444
```

Instead of this, which picks up the latest stable version:

```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates
```

At the very least we should do this for Microsoft.AspNetCore.Blazor.Templates and we should consider versioning all the Blazor packages the same way.

**Comment by KexyBiscuit** [comment]
Workaround: `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.*`
Reference: [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/reference/package-versioning)

**Comment by vertonghenb** [comment]
Might want to update https://blogs.msdn.microsoft.com/webdev/2019/01/29/aspnet-core-3-preview-2/ for the time being.
from:
```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates
dotnet new blazorlib
```
to:
```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.*
dotnet new blazorlib
```

**Comment by danroth27** [comment]
@vertonghenb Thanks, I updated the post.

**Comment by danroth27** [comment]
We're keeping the preview moniker for now.
