### ISSUE TITLE
How to set BackchannelHttpHandler/etc settings of Startup when using WebApplicationFactory

### ISSUE THREAD

**Issue by pwen090** [aspnet/AspNetCore#7141]
The following was given as an example of setting BackchannelHttpHandler during testing. I am wondering what is the similar process for when using WebApplicationFactory? Trying to set handlers for AddIdentityServerAuthentication in Startup. Right now just temporarily made a static in Startup that I can overwrite with my handler but that is going to cause an issue if multiple WebApplicationFactories were created. The answer below looked promising but was not sure how to do that with WebApplicationFactory. Probably missing something obvious sorry! Any sample code reference? thank you P.S. Working around this with static was also marked as an answer on stackoverflow but again static will cause problems... [https://stackoverflow.com/questions/52953732/how-can-i-set-my-identityserver4-backchannelhandler-from-within-an-xunit-integra](url)

The following seems to be a better way but i am unsure how to do with WebApplicationFactory

_Originally posted by @javiercn in https://github.com/aspnet/Security/issues/1666#issuecomment-370672398_

```csharp
public class LoopBackHandler : DelegatingHandler { }
```

```csharp
var loopBackHandler = new LoopBackHandler();
var builder = WebHost.ConfigureServices(services => services.Configure<YourOptions>(o => o.BackChannelHandler = loopBackHandler));
var server = new TestServer(builder);
loopBackHandler.InnerHandler = server.CreateHandler();
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pwen090.
You can configure the `WebApplicationFactory` using https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.testing.webapplicationfactory-1.withwebhostbuilder?view=aspnetcore-2.2#Microsoft_AspNetCore_Mvc_Testing_WebApplicationFactory_1_WithWebHostBuilder_System_Action_Microsoft_AspNetCore_Hosting_IWebHostBuilder__ APIs.
