### ISSUE TITLE
Run IIS integration tests on helix

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7145]
Required for VS 2019 migration.

**Comment by pakrym** [comment]
Blocked by https://github.com/aspnet/AspNetCore/pull/6728

**Comment by muratg** [comment]
@pakrym I believe this is not blocked anymore, right?

**Comment by pakrym** [comment]
It's being worked on.

**Comment by pakrym** [comment]
https://github.com/aspnet/AspNetCore/pull/7959 is done and https://github.com/aspnet/AspNetCore/issues/7972 is left.
