### ISSUE TITLE
HTML entities (e.g., &nbsp;) renders as content in Razor Components app

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7147]
If I create a Razor Component that uses an HTML no break space (`&nbsp;`) in its markup, it renders as content instead of as a space.

```html
@page "/counter"

<h1>Counter</h1>

<p>Current count: &nbsp;&nbsp; @currentCount</p>

<button class="btn btn-primary" onclick="@IncrementCount">Click me</button>
```

![image](https://user-images.githubusercontent.com/1874516/52014652-052ecd80-24d8-11e9-8c52-e1a6b8a5acee.png)

In Blazor 0.7.0 you get spaces.

**Comment by danroth27** [comment]
@rynowak @ajaybhargavb  Is this potentially an HTML parsing issue?

**Comment by rynowak** [comment]
We had some code from Anglesharp in 0.7 that decoded HTML entities like this. It seems likely we need to introduce something similar. This has to be component specific legacy razor will still want to treat entities as *text*.

**Comment by ajaybhargavb** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/6185
