### ISSUE TITLE
Remove obsolete member in src/Middleware/WebSockets/src/WebSocketMiddleware.cs

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCore#7150]
Remove this obsolete member in [src/Middleware/WebSockets/src/WebSocketMiddleware.cs](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/WebSockets/src/WebSocketMiddleware.cs#L51):

```c#
        [Obsolete("This constructor has been replaced with an equivalent constructor which requires an ILoggerFactory.")]
        public WebSocketMiddleware(RequestDelegate next, IOptions<WebSocketOptions> options)
            : this(next, options, NullLoggerFactory.Instance)
```

And file a new issue in https://github.com/aspnet/Announcements/issues/ if this is a notable breaking change.

**Comment by BrennanConroy** [comment]
>And file a new issue in https://github.com/aspnet/Announcements/issues/ if this is a notable breaking change.

I don't think this is notable, most use cases are from `app.UseWebSockets()` which will create the `WebSocketMiddleware` from DI

**Comment by muratg** [comment]
@BrennanConroy sounds good, let's skip that.
