### ISSUE TITLE
Add logging to ValidateSecurityStampAsync

### ISSUE THREAD

**Issue by LindaLawton** [aspnet/AspNetCore#7155]
### Is your feature request related to a problem? Please describe.

I would like to see some logging for the security stamp validation.

### Describe the solution you'd like

[SignInManager.cs#L260](https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/Core/src/SignInManager.cs#L260) checks that the securty stamp has not been changed.

1. it does not check if the security stamp is null which links back to [#7055](https://github.com/aspnet/AspNetCore/issues/7055)
2. It does not log that a change was detected

### Describe alternatives you've considered

I would like to see a null check added as well as logging.

1. Log error security stamp null
2. Log info user security stamp changed logging user out.

### Additional context

It took me weeks to figure out what my issue was due to the lack of logging on this.  There was no way to debug the issue as to why the user was getting randomly logged out.

**Comment by blowdart** [comment]
@HaoK This is small in terms of code right?

**Comment by blowdart** [comment]
@LindaLawton in 3.0 we introducing a breaking change, where as soon as we encounter a null security stamp in a code path where a security stamp is required we're going to throw an exception and break. As we wouldn't expect you to encounter this with a correct database, because you'd have tested it, right, it's a developer scenario so we can break.

**Comment by blowdart** [comment]
@HaoK We'll log the second request as Debug

**Comment by LindaLawton** [comment]
@blowdart will that also address [7055](https://github.com/aspnet/AspNetCore/issues/7055) which is related to the cookie testing and has nothing to do with the database.

**Comment by blowdart** [comment]
No, that's unrelated. A cookie simply doesn't drop the stamp. If the stamp is present it's baked into the cookie. Honestly this sounds like whatever implementation you have of a stamp supporting store is quite buggy.

**Comment by LindaLawton** [comment]
>Honestly this sounds like whatever implementation you have of a stamp supporting store is quite buggy.

Actually its a homegrown user system that was covered over to asp .net identity in September.   We have had some teething issues as there is no documentation on how to convert a ten year old legacy system to asp .net identity.   I think we finally have it stable but this may have lead to use finding some places where you are not testing for null security stamps.
