### ISSUE TITLE
signalr-protocol-msgpack 1.1.0 does not support MessageType.CancelInvocation

### ISSUE THREAD

**Issue by balazsmeszegeto** [aspnet/AspNetCore#7157]
### Describe the bug
TS Client implementation of messagepack (signalr-protocol-msgpack) does not support CancelInvation message types as of version 1.1.0. Server/c# implementation of messagepack does support it.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Setup SignalR (server) with AddMessagePackProtocol
3. Create any streaming hub method with cancellation token
4. Install ts client signalr-protocol-msgpack '1.1.0'
5. Connect to streaming hub method and cancel using `dispose()` before the streaming ends
6. See error

### Expected behavior
CancelInvocation message should be sent as defined in the protocol

**Comment by BrennanConroy** [comment]
@davidfowl I think it was you who mentioned backporting? Is this something you still think we should try to do?

**Comment by davidfowl** [comment]
Yes

**Comment by BrennanConroy** [comment]
@muratg We would like to try to get this into the next 2.2 patch, I'll find the template and fill it out. I don't remember does it go on the issue or a PR?

**Comment by muratg** [comment]
@BrennanConroy on the PR. CC me on the PR as well please! Thanks.

**Comment by muratg** [comment]
Fixed in 3.0.0-preview3
