### ISSUE TITLE
Make AwaitableInfo readonly struct

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#7167]
This was proposed during a PR review: https://github.com/grpc/grpc-dotnet/pull/48#discussion_r252778441.

cc @JamesNK

**Comment by JunTaoLuo** [comment]
Note that we need to update this in https://github.com/grpc/grpc-dotnet as well

**Comment by JamesNK** [comment]
https://github.com/aspnet/AspNetCore/pull/7169

**Comment by pranavkm** [comment]
Close?
