### ISSUE TITLE
Intellisense in Razor Component not working

### ISSUE THREAD

**Issue by Swellenator** [aspnet/AspNetCore#7175]
### Describe the bug
I have a new Razor Component project created from `dotnet new` using VS 2019 Preview 2. 

When I open any of the .cshtml files eg. App.cshtml the code is all grey and pressing Ctrl+Space just inserts a space. There is no IntelliSense. 

### To Reproduce
1. Using Preview 3 of ASP.NET Core
2. `dotnet new razorcomponents`
3. Open in VS 2019 Preview V16 Preview 2.1
4. No IntelliSense

Is there a language service or something I need?  Or should it be baked in to VS 2019? Or perhaps a certain workload? I chose the ASP.Net Web Development one and in the installer it has Razor Language Service ticked. 

### Expected behavior
I expect to get IntelliSense in .cshtml files in a Razor Components project.

### Screenshots

![image](https://user-images.githubusercontent.com/14356182/52093915-0f081c00-2611-11e9-8357-5838f7931af9.png)

![image](https://user-images.githubusercontent.com/14356182/52093946-32cb6200-2611-11e9-9254-c89b14b11f67.png)

#### Visual Studio info

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 2.1
VisualStudio.16.Preview/16.0.0-pre.2.1+28529.54
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Azure App Service Tools v3.0.0   16.0.12091.59624
Azure App Service Tools v3.0.0

C# Tools   3.0.0-beta2-19068-12+231aeb8be8357239499d45c0574e5a9a8c9174f0
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.0.0-beta2-19068-12+231aeb8be8357239499d45c0574e5a9a8c9174f0
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: 5f5e68099410f71fc13bb615b9a27abd055da6de.
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

#### dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  1.1.10 [C:\Program Files\dotnet\sdk]
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by TheFanatr** [comment]
Try closing and reopening the page. In previous versions Razor Components, `.cshtml` files would fail to load IntelliSense on first open until they were closed and reopened again. If that doesn't work, try closing the page, then cleaning, closing, and reopening the solution. Past that, I'm not personally sure what to recommend. Also note that `App.cshtml` is the router configuration file. Try opening something like `Index.cshtml` within the `Pages` node in the project.

**Comment by Swellenator** [comment]
@neville-nazerane The blazor extension here https://marketplace.visualstudio.com/items?itemName=aspnet.blazor is for VS 2017 as far as I can tell.

@TheFanatr I've closed, reopened, closed the solution etc. and tried all the .cshtml files, still the same result...

**Comment by TheFanatr** [comment]
Double check that you have the `ASP.NET and web development` and `.NET Core cross-platform development` packages installed via the Visual Studio installer. Based on your list of installed products, you seem to be missing a couple that I have, and I literally only installed the aforementioned packages.
![image](https://user-images.githubusercontent.com/16641853/52107081-dd0f9f00-25a9-11e9-8604-e8857d4489aa.png)
The packages I am talking about are under the `Web & Cloud` and `Other Toolsets` headers, respectively.
![image](https://user-images.githubusercontent.com/16641853/52107134-10522e00-25aa-11e9-8e21-c34a06e2eb1e.png)
![image](https://user-images.githubusercontent.com/16641853/52107157-1f38e080-25aa-11e9-9480-a069c61bef0b.png)
This is something that would very likely cause the behavior you are experiencing, as far as I know. It's worth checking just to be sure.

**Comment by Swellenator** [comment]
As some background, I ran the following command to create my VS 2019 install:

`"vs_enterprise.exe" --layout vs2019offline --lang en-US --add Microsoft.VisualStudio.Workload.Azure --add Microsoft.VisualStudio.Workload.NetCoreTools --add Microsoft.VisualStudio.Workload.NetWeb --includeRecommended`

After @TheFanatr 's comment I have also run 

`"vs_enterprise" --layout vs2019offline --lang en-US --add Microsoft.VisualStudio.Web.Mvc4.ComponentGroup`

So I now have 

`ASP.NET Web Frameworks and Tools 2012   16.0.12091.59624`

installed, which is a bit odd because it says 2012. But it still doesn't work, no IntelliSense. But even more odd is if I go File New Project, there is no option to choose a web site at all! So something is definitely missing. I will continue to investigate.

**Comment by mkArtakMSFT** [comment]
@Swellenator are you seeing this issue with VS 2019 preview4?

**Comment by Swellenator** [comment]
Still a problem. I suspect it is just me though, when I run the installer UI for VS 2019 it says that .NET Core 2.1 can't be installed. I believe it is something to do with group policy. 

The thing is that I have installed .NET Core 2.1 and 2.2 and 3 Preview manually and it is fine. However because it fails during the VS 2019 install I think it aborts the rest of the ASP.NET tooling in the install or something.

So ultimately I think it is to do with an error in the VS 2019 installer to do with the environment's group policy, and probably nothing to do with Razor Components as such, so this can probably be closed.

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @Swellenator.
Seems we won't be able to help you, as it's really external.
