### ISSUE TITLE
Controllers are not getting discovered when using 'Microsoft.AspNetCore.TestHost' in test project

### ISSUE THREAD

**Issue by 1015450578** [aspnet/AspNetCore#7181]
### Describe the bug
I created a integration test project for testing my MVC application.
The server response 404 when I send HTTP request through ```TestServer.CreateClient()```
I start debug the test after create a break point at startup and IMvcBuilder.PartManager.ApplicationParts is empty after AddMvcCore().(but it works well when I set my API Project as start up project.)

When I call method ```DependencyContext.Load(Assembly.GetAssembly(typeof(MvcPartTests)))``` (MvcPartTests is defined in my integration test project),No any 'Microsoft.AspNetCore.App' was found in ```RuntimeLibraries``` and ```Dependencies```,so no any controller found.

Then i repeat above with ```DependencyContext.Load(Assembly.GetAssembly(typeof(Startup)))```(Startup is defined in my mvc api project),'Microsoft.AspNetCore.App' was found.

### To Reproduce
1. Using this version of ASP.NET Core '2.2'

### Expected behavior
ApplicationParts will dicovered in Integration test project

### Screenshots
![image](https://user-images.githubusercontent.com/25654404/52099952-5e018180-2610-11e9-88f9-9598fbbd808b.png)

![image](https://user-images.githubusercontent.com/25654404/52099978-82f5f480-2610-11e9-83cd-c6d5837dbcca.png)

### Additional context

``` cmd
.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

.NET Core SDKs installed:
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009748 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @1015450578.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
@1015450578 Thanks for reaching out.

Seems like you are trying to perform an integration test. You are likely missing copying the .deps.json file of the project to the output folder of the test project. There is a better approach you can take described below:

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2

**Comment by endeffects** [comment]
This fixes the issue: https://github.com/aspnet/AspNetCore/issues/11921#issuecomment-523670519
