### ISSUE TITLE
[RazorComponents] - how to change RazorComponents default startup parameters?

### ISSUE THREAD

**Issue by furoraest** [aspnet/AspNetCore#7185]
### Description
there is a method describing how to change default signalR buffer size for Blazor in
https://github.com/aspnet/Blazor/issues/1614

How to do same in RazorComponents?

**Comment by furoraest** [comment]
I pointed out SignalR as a current need to modify transport buffer, but yes if there is need to change something in configuration, what would be the proper way, currently all is neatly packaged in:
public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorComponents<App.Startup>();
        }

**Comment by furoraest** [comment]
I think it is related to the same topic... how to let notifications to UI side using already existing connection.
I know how to make connection from UI side but it seems bit excessive, since there is already connection up and running.
I think some additional documentation or examples would be appreciated.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @furoraest.
We're going to provide some samples regarding configuring the `ComponentHub` and we track that work as part of https://github.com/aspnet/AspNetCore/issues/8277.
