### ISSUE TITLE
2 identical IIS schema files aspnetcore_schema_v2.xml and aspnetcore_schema.xml

### ISSUE THREAD

**Issue by csharmath** [aspnet/AspNetCore#7188]
### Describe the bug
After installing ASP.NET Core 3.0 Runtime and Hosting bundle I've noticed that there are 2 identical IIS schema files installed under C:\Windows\System32\inetsrv\config\schema.

### To Reproduce
1. Install the hosting bundle on a clean box
2. observe the contents of C:\Windows\System32\inetsrv\config\schema
3. compare the 2 aspnetcore files and see that they are identical

Steps to reproduce the IIS manager confusion
1. Install the .NET Core 2 hosting bundle on a clean box
2. observe the contents of C:\Windows\System32\inetsrv\config\schema
3. iisreset
4. Verify that IIS manager can edit the aspnetcore settings
5. install .NET Core 3 preview bundle as above
6. iisreset
7. observe that stdOutLogFile is missing from the config
8. observe that there are 2 schema files with the same settings

### Expected behavior
There is no need to have 2 files for the exact same schema.
This seems to be a bug with a minimal impact if you only install .NET Core 3 bundle, but can cause some confusion if there were previous versions.
When installed on top of the .NET Core 2.1 version IIS manager actually got confused and didn't show the standard stdOutLogFile option in Configuration editor.
Uninstalling all versions and re-installing .NET Core 3.0 preview bundle fixed the issue but it now has 2 identical files.

**Comment by jkotalik** [comment]
@muratg Let's make sure everything work for this scenario in 3.0.

**Comment by muratg** [comment]
Triage: we're not planning to change anything here.
