### ISSUE TITLE
Q: Please provide sample or guidance on Component Circuit

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AspNetCore#7189]
I would like to understand the following use case with regards to Component Circuits.
1. The user interface has a number of Components that injected shared state which is displayed in a user friendly format,
2. The Server-Side application has a long running task the monitors for external event/data ie. SerialPort data, and as/when data arrives updates the shared state that is injected into the components

Q: how would a developer trigger the components that have the shared state injected to render?
Q: do/would components automatically render as state has changed?
Q: is there any consideration that is needed when hold the state with in the DI system?

**Comment by muratg** [comment]
cc @danroth27

**Comment by danroth27** [comment]
Hi @grahamehorner,

Components don't have any automatic mechanism to detect that their state has changed and need to be rendered. As a sort of heuristic, components are rendered in response to UI events specific to that component. But, in general, you need to call the `StateHasChanged` method on the component to signal that it should be rendered.

So, to handle you're scenario where state is being updated by some long running task you would need some sort of way to call `StateHasChanged` on the component whenever it's state has been updated. For example, the component might subscribe to an event on a service. When the event is fired the component would update it's state and call `StateHasChanged`.

I hope this helps!
