### ISSUE TITLE
IFormFile is null in Razor Page OnPost() method.

### ISSUE THREAD

**Issue by ronebrandao** [aspnet/AspNetCore#7194]
I'm having a tricky problem. 

I created a model with an IFormFile property in my page and binded it. On OnPost() method, the IFormFile property value is null. But, if I try to get the file using `var result = HttpContext.Request.Form.Files[0];` it works.

But that's not the tricky part yet.

At home, I'm using asp.net core on linux and this does not happens. But at work, where I use windows, it does. Don't know if the issue is related to the OS, but it's intriging. In this [issue](https://github.com/aspnet/Docs/issues/9108), I saw that it wasn't happening in version 2.2 _(I'm currently using 2.2.103)_, but it is happening to me.

**Comment by Eilon** [comment]
@ronebrandao sorry you're running into this issue. Can you show what your code looks like? That will help us reproduce the issue and investigate.

**Comment by ronebrandao** [comment]
I have a FileUpload class: 

`public class FileUpload
    {
        [Required]
        [Display(Name = "Title")]
        [StringLength(60, MinimumLength = 3)]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Annotations")]
        public IFormFile Annotations { get; set; }

    }`

My index model looks like this:

`[IgnoreAntiforgeryToken(Order = 1001)]
    public class IndexModel : PageModel
    {
        [BindProperty]
        public FileUpload FileUpload { get; set; }

        [BindProperty]
        public Annotation Annotation { get; set; }

        public IActionResult OnPost()
        {
            var annotations = FileHelpers.ProcessFormFile(FileUpload.Annotations, ModelState, Annotation);
            annotations.Position = 0;

            return File(annotations, "application/octet-stream", "Annotations.zip");
        }

    }`

That's all. The Process method just uses the `FileUpload.Annotations` property. The repository in on my [github](https://github.com/ronebrandao/CRISPR.Annotations) if you want to see it. It's a really simple project.

**Comment by Eilon** [comment]
@ronebrandao thanks for the additional info, we will have someone take a look at this.

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @ronebrandao.
@dougbu, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
@ronebrandao I tried your scenario using 2.2.4 and I'm unable to reproduce the scenario:

![image](https://user-images.githubusercontent.com/174281/57152972-efa49a80-6d89-11e9-9d74-60d4f7406027.png)

Note that `Annotations` isn't null.
