### ISSUE TITLE
build.cmd -arch x64 still builds x86 assets

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#7196]
Running `build.cmd -arch x64` (and `-arch x86`) still builds the Server IIS projects for both CPU architectures. This is currently necessary for two reasons:

* Windows installers bundle both architectures in one output
* NuGet packages that bundle ANCM include both architectures

Fixing this would probably speed up the build because we could build x86 and x64 in parallel, and then join together the bits necessary to create bundle installers.

cc @pakrym

**Comment by natemcmaster** [comment]
cc @Eilon - let's triage this one today. This is causing regular build failures. We get failures due to locked files which are shared between the x86 and x64 build of C++ projects.

**Comment by pakrym** [comment]
There are implications of this for functional testing and dev loop. ANCM handler that goes into shared runtime is not the only native thing that is getting built in parallel. There is also IIS module that is required to be able to run functional tests too.

Things to consider:

Are at the place where we can use composed shared runtime in functional tests?
What's the plan for consuming IIS module (aspnetcorev2.dll) from tests considering we control publish bitness in code.
How does this all integrate with Helix (currently both sets of native assets end up in test project published output, what would happen when we split)?

**Comment by pakrym** [comment]
In addition there is other way to fix these build errors - move files in question to platform specific subdirectory.

**Comment by Eilon** [comment]
Discussed in triage. @muratg please assign/set milestone as appropriate.

**Comment by pakrym** [comment]
@muratg it is a direct clean solution for "This is causing regular build failures. We get failures due to locked files which are shared between the x86 and x64 build of C++ projects." and the fix is already in (https://github.com/aspnet/AspNetCore/pull/7513)

The original issue didn't list other reasons outside of speeding up the build performance so it's up you to judge if this needs implementing considering the impact and amount of work required.

**Comment by Eilon** [comment]
Do we have an idea of how much time it would save? 5 seconds? 5 minutes?

**Comment by pakrym** [comment]
x86 build takes ~3m so running it in parallel can save maximum that.

**Comment by Eilon** [comment]
OK then I'm not sure it's worth spending any more time on it now.

**Comment by Eilon** [comment]
(Unless this is a super common local-dev thing that annoys the people who have to do it. If that's the case, it might be worth it sooner.)

**Comment by anurse** [comment]
Closing as per @Eilon 's comments.
