### ISSUE TITLE
Enable tslint on Microsoft.Interop.Js

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#7197]
The `build` command needs to be updated to perform linting:

`"build": "npm run clean && npm run build:tslint && npm run build:esm",`

**Comment by mkArtakMSFT** [comment]
@pranavkm, please provide more details regarding this ask. Where is this needed and why?

**Comment by javiercn** [comment]
This was done as part of preview4 and we enabled ESLint cuz TSLint is going away.

**Comment by javiercn** [comment]
We don't want to do it at build yet because we have a lot of errors we need to fix across files. The guidance I provided was that every time we modify a file on a PR we fix the errors.
