### ISSUE TITLE
No data saved in the partial view

### ISSUE THREAD

**Issue by MasHero7** [aspnet/AspNetCore#7209]
I'm trying to save data updated on the partial view called in parent Edit action. But the updated data is not saved.

I have a parent table 'Nz' and a child one 'Mkh' and trying to retrieve all the data of it in 'Nz' edit action as a partial view to let the user update it. The data is retrieved correctly but when the user update the data and press submit no data is saved! on the other hand, I want to retrieve 'Select' items with returned values not a normal text item.
I explained the whole code at:
https://stackoverflow.com/questions/54490261/no-data-saved-in-the-partial-view

Now when I press save button (submit) no data is saved for the partial one like days! Why? and How to solve please?

and How to return Select with returned values from MkhType? (using MkhCodeNavigation I think)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MasHero7.
StackOverflow is the best place to take these type of issues, and you've already done that. Seems you're getting some tracking for your issue there already.
