### ISSUE TITLE
[RazorComponents] update dotnet cli template "razorcomponents"

### ISSUE THREAD

**Issue by furoraest** [aspnet/AspNetCore#7222]
### Is your feature request related to a problem? Please describe.
What is described in [https://docs.microsoft.com/en-us/aspnet/core/razor-components/components?view=aspnetcore-3.0#razor-templates](url)#Base class inheritance for a "code-behind" experience, seems currently not working with latest .net core 3.0 preview2

### Describe the solution you'd like
updated template what is created via "dotnet new razorcomponents" and manual/example which will provide working solution

### Describe alternatives you've considered
Blazor server side implementation wont work currently with .net core 3.0 so no good alternatives

### Additional context
Steps to reproduce
1. Add code (component .cs and .cshtml)
2. Add package references: 

- Microsoft.AspNetCore.Blazor.Browser

- Microsoft.AspNetCore.Blazor.Build

3. dotnet build/run produces output:
/home/user/bin/dotnet/sdk/3.0.100-preview-010184/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(93,5): error MSB4063: The "RazorGenerate" task could not be initialized with its input parameters.  [/home/user/src/netcore/myApp/myApp.App/myApp.App.csproj]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @furoraest.
3.0-preview2 release has an updated Blazor template. Please try what we've shipped and let us know if it's not working for you: https://devblogs.microsoft.com/aspnet/aspnet-core-3-preview-2/
