### ISSUE TITLE
Can't compile SignalR+TypeScript with MessagePack plugin

### ISSUE THREAD

**Issue by highfield** [aspnet/AspNetCore#7229]
I've been successful by creating a small app using AspNetCore 2.2, SignalR, and a TypeScript front-end. The bundle is created via WebPack.

What I would like to try is to enable the MessagePack protocol plugin. However, [the docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-2.2) about how to install it seems not accurate enough. Although the command-line compilation (npm run build) goes apparently fine, when I start the application to debug it won't compile because something in the TypeScript code is missing:

> Error TS2688 Build:Cannot find type definition file for 'node'. C:\ ... \node_modules@aspnet\signalr-protocol-msgpack\dist\esm\MessagePackHubProtocol.d.ts 1

> Error TS2580 Build:Cannot find name 'Buffer'. Do you need to install type definitions for node? Try npm i @types/node and then add node to the types field in your tsconfig. C:\ ... \node_modules@aspnet\signalr-protocol-msgpack\dist\esm\MessagePackHubProtocol.d.ts 16

By the way, if I follow that hint, things will go even worse due the "setTimeout" presence in my code. Basically, it seems that the "node" setTimeout overrides the "window"'s one, and their signatures don't match.
Here is the package.json (without the hinted patch):

```
{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "devDependencies": {
    "del": "2.2.0",
    "@types/jquery": "^3.3.29",
    "ts-loader": "^5.3.3",
    "typescript": "^3.2.2",
    "webpack": "^4.28.3",
    "webpack-cli": "^3.2.1",
    "webpack-merge-and-include-globally": "^2.1.14",
    "clean-webpack-plugin": "^1.0.0"
  },
  "dependencies": {
    "@aspnet/signalr": "^1.1.0",
    "@aspnet/signalr-protocol-msgpack": "^1.1.0",
    "axios": "^0.18.0",
    "bootstrap": "^4.2.1",
    "jquery": "^3.3.1"
  },
  "scripts": {
    "build": "webpack --mode=development",
    "watch": "webpack --mode=development --watch",
    "release": "webpack --mode=production",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}

```
Finally, here is the tsconfig.json:

```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "lib": [ "es6", "dom" ]
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}

```
Is it me, or maybe a bug somewhere?

**Comment by muratg** [comment]
@BrennanConroy Can you take a look please?

**Comment by BrennanConroy** [comment]
Could you make a repro app and push it to github?

**Comment by highfield** [comment]
@BrennanConroy here it is: https://github.com/highfield/AspNetCoreTypeScriptSignalR

Open the command prompt at the project folder level, then type npm run build or npm run watch to create the bundle.

Also notice the series of warning. They appear only when the message-pack plugin is bundled. Just comment as below to make them disappear:

```
    const connection = new signalR.HubConnectionBuilder()
        .withUrl("/hub")
        //.withHubProtocol(new MessagePackHubProtocol())
        .build();

```
Finally, if you try to build/run the entire project you'll see it is not possible due a series of problems.

Note: the sample project is a brand new one than the original where I originally found the issue. The PC is also different.

**Comment by BrennanConroy** [comment]
I can build and run your project completely fine from the command line.

However, in VS I do see the node errors with "Try npm i @types/node", so after installing `@types/node` those errors go away and are replaced by `Build:Property 'parseMessages' in type 'MessagePackHubProtocol' is not assignable to the same property in base type 'IHubProtocol'.`

And that error will go away in an upcoming patch of the `@aspnet/signalr-protocol-msgpack` package.

**Comment by highfield** [comment]
@BrennanConroy since nothing changed since yesterday, I can't figure out why the command-line compilation shows no more lots of warnings. Did you make any patch to some npm?

By the way, it's my fault not adding a `setTimeout`/`setInterval` reference in the sample project, because *that* was the other problem. The "parseMessages" error is quite new to me.

So, I added this line to the app.ts module:

`var tmr: number = setInterval(() => console.log('tick'), 1000);`

the command-line compilation runs fine, but the project won't compile because the following problems:

> TS2322	(TS) Type 'Timeout' is not assignable to type 'number'.	
> TS2416	Build:Property 'parseMessages' in type 'MessagePackHubProtocol' is not assignable to the same property in base type 'IHubProtocol'.

Of course, the "Timeout" error won't happen if you remove the node package.

**Comment by BrennanConroy** [comment]
The parseMessages error should be gone now if you update to the latest npm package https://www.npmjs.com/package/@aspnet/signalr/v/1.1.2

**Comment by highfield** [comment]
Great! will wait for the other blocking issue, then.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
