### ISSUE TITLE
JsonModelBinder for POST both model and file

### ISSUE THREAD

**Issue by baruchiro** [aspnet/AspNetCore#7233]
### Is your feature request related to a problem? Please describe.
I'm trying to create a POST action that receives both `IFormFile` and model.

### Describe the solution you'd like
The solution described in [StackOverflow answer](https://stackoverflow.com/a/46344854/839513) and also there is a [Nuget](https://www.nuget.org/packages/JsonModelBinder/) for this solution.

Why not adding this case to an official library?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @baruchiro.
This is not something we've heard a lot of ask for from the community.
May the situation change and we see more community involvement regarding this ask, we'll reconsider this.
