### ISSUE TITLE
Allow Optional Parameters for Razor Components

### ISSUE THREAD

**Issue by TheFanatr** [aspnet/AspNetCore#7237]
# Allow Optional Route Parameters to be Defined in a Razor Component
It would be greatly beneficial for many projects to be able to take advantage of a way to create Razor Component pages which accept optional parameters. Here is a suggested specification for such a feature.

## <code>@params var1, var2, ... var*n*</code> Directive
This directive, specified at the top of the file where all the `@page` directives go, declares all the properties that can be set via case-insensitive query parameters appended to an applicable route. <code>var*n*</code> refers to a reference to either a `ParameterAttribute`-decorated, or `ValueType`/string-typed field or property defined within the `@functions` block. 

## Modified <code>@page "*route*"</code> Directive
Modifications should be made in order for the directive to have the following signature:
<code>@page "*route*" [exclusive] with var1, var2, ... var*n*</code>
The purpose of this change would be to allow other parameters that are not part of the general `@params` case to be declared as valid for a specific route, where the `exclusive` keyword could also be specified to dictate that the general case should be ignored, as in, when that specific route is used, the `@params` directive is ignored. <code>var*n*</code> means the same thing as in the `@params` definition.

## Additions to `ParameterAttribute`
In order to support the usage of non-string and non-`ValueType` parameters for optional route parameters, there needs to be a way to convert to the parsed string from the URI to an object of the parameter type. This can be done by adding `Func<string, object> Converter { get; set; }` to `ParameterAttribute`, which would allow the definition of string-to-instance conversions to be used for populating the parameters. Converting the string to an incorrect type should either result in a run-time failure, or conversion bypass, if possible (i.e.: string can be parsed into type, for if someone accidentally defines a converter for a type that can already have an instance generated for it, or one that already has a conversion defined from a string).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @TheFanatr.
@rynowak, is this how you envision the routing to work for components?
/cc @danroth27

**Comment by mkArtakMSFT** [comment]
@TheFanatr we do have a separate issue tracking the support of optional route parameters and the way we envision that to work is different from what is proposed here. So closing this issue in favor to the one we have already: https://github.com/aspnet/aspnetcore/issues/5489
