### ISSUE TITLE
FormTagHelper doesnt respect aliased routes with parameters

### ISSUE THREAD

**Issue by oferns** [aspnet/AspNetCore#7239]
### Describe the bug
Using the FormTagHelper produces different routes to the Url.Action method when using an aliased route with parameters

### To Reproduce
1. Using this version of ASP.NET Core '2.2.103'
2. Run this simple code repository based on VS2017 default MVC app template'....'
https://github.com/oferns/formtaghelper

3. See startup.cs for the custom routes
4. Run project and go to 

/customroute  <- Form Taghelper produces incorrect aliased Url
See form action is /Apply/Index/1 but Url.Action is /customroute

/anothercustomroute <- Form Taghelper produces incorrect aliased Url
See form action is /Apply/Index/2 but Url.Action is /anothercustomroute 

/customroutenoarg <- Form Taghelper produces correct aliased Url
See form action is /customroutenoarg same as Url.Action

### Expected behavior
Would expect the FormTagHelper to match the aliased route as it does when there is no "id" routevalue

**Comment by oferns** [comment]
I have an update. It is because the value is being passed as a string instead of an int when I use the asp-route-id="" attribute. I have managed to wrap the existing IHtmlGenerator to check for mismatched types in the expected route values (ie the function arguments for your action) and the supplied values to convert if necessary. This is below. This fixes the form action tag, but not any buttons that are using asp-action, asp-controller etc. They dont call the IHtmlGenerator, directly using the IUrlHelper supplied instead and I dont fancy subclassing that. In startup, I get an instance of the default IHtmlGenerator, remove its registration, then inject the default into my decorators constructor. I wont post the whole class as there are quite a few methods to mirror.

In startup.cs ConfigureServices to replace the existing implementation

`            var sp = services.BuildServiceProvider();
            var existingGenerator = sp.GetRequiredService<IHtmlGenerator>();

            var existingGenReg= services.FirstOrDefault(x => x.ServiceType == typeof(IHtmlGenerator));
            services.Remove(existingGenReg);
            services.AddScoped<IHtmlGenerator>(c => new TypeConvertingHtmlGenerator(existingGenerator));`

Then the TypeConvertingHtmlGenerator..

`    public class TypeConvertingHtmlGenerator : IHtmlGenerator {
        private readonly IHtmlGenerator dg;

        public TypeConvertingHtmlGenerator(IHtmlGenerator defaultGenerator) {
            this.dg = defaultGenerator ?? throw new ArgumentNullException(nameof(defaultGenerator));
        }

`  public TagBuilder GenerateActionLink(ViewContext viewContext, string linkText, string actionName, string controllerName, string protocol, string hostname, string fragment, object routeValues, object htmlAttributes) {
            if (routeValues is RouteValueDictionary dict) {
                foreach (var param in viewContext.ActionDescriptor.Parameters) {
                    if (dict.ContainsKey(param.Name) && param.ParameterType != dict[param.Name].GetType()) {
                        dict[param.Name] = Convert.ChangeType(dict[param.Name], param.ParameterType);
                    }
                }
            }

            return dg.GenerateActionLink(viewContext, linkText, actionName, controllerName, protocol, hostname, fragment, routeValues, htmlAttributes);
        }

        public string IdAttributeDotReplacement => dg.IdAttributeDotReplacement;

        public string Encode(string value) => dg.Encode(value);
`
I dont know if I have missed a trick here but by doing this at least my formaction respects my aliases when I have routevalues that are not strings

**Comment by oferns** [comment]
could it be cured by making the RouteValues property of the FormActionTagHelper an  IDictionary<string, object> instead of  IDictionary<string, string>?

**Comment by oferns** [comment]
After all that, if I define the same route with a string and an int then all is well. Its a bit of a hack though,..

```
               routes.MapRoute(
                    name: "StandardApplyInt",
                    template: "/apply",
                    defaults: new { area = "Products", controller = "Apply", action = "Index", eid = 3 }
                );

                routes.MapRoute(
                    name: "StandardApplyString",
                    template: "/apply",
                    defaults: new { area = "Products", controller = "Apply", action = "Index", eid = "3" }
                );
```

**Comment by danroth27** [comment]
No plans to do anything here, so closing.
