### ISSUE TITLE
asp-page adding current route parameters when linking to current page

### ISSUE THREAD

**Issue by mrlife** [aspnet/AspNetCore#7241]
### Describe the bug
In Razor Pages, when on page `/Search` and an anchor tag uses `asp-page`, the route parameters, e.g. `/Search/foo/bar` are used in the generated `href`. Instead, they should not be used, i.e. `href="/Search"`. I can provide a sample project if it would help.

### To Reproduce
1. Using this version of ASP.NET Core: 2.2.1
2. Run this code: 

- create a new Razor Pages app
- on the Index page, create an anchor tag: `<a asp-page="/Index">test</a>`
- add 2 route parameters to the top of the Index page, e.g. `@page "{Foo}/{Bar}"`
- in the .cs file, add this:
```
[BindProperty(SupportsGet = true)] public string Foo { get; set; }
[BindProperty(SupportsGet = true)] public string Bar { get; set; }
```
- run the project
- add 2 route values to the end of the url, e.g. /test1/test2
- check the generated link
3. Notice that it has the parameters in the generated `href`

### Expected behavior
Generated `href` should not include the current page's parameters if the `asp-page` is pointing to the current page.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mrlife.
@JamesNK, can you please look into this? Thanks!

**Comment by rynowak** [comment]
Hi @mrlife  - This an existing long-time behavior of MVC/Routing (back to version 1 of the original ASP.NET MVC).

There's some discussion about it here: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#url-generation - but the general gist is that routing always attempts to re-use route values from the current request when you're linking to the same action/page. 

If you don't want this behavior then you can either *null out* these values `<a asp-page="/Index" asp-route-foo="" asp-route-bar="">test</a>` OR you could remove the route parameters and just use the query string to pass these values around.
