### ISSUE TITLE
Figure out how to reconnect to circuits

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#7243]
As part of of https://github.com/aspnet/AspNetCore/pull/6971, the circuit identifier is a `Guid`. We have to determine if this is a sufficiently random enough value to allow a client to reconnect to a server. It's effectively a session identifier and it's likely not enough to present the identifier in itself as evidence to reconnect to a circuit.

**Comment by danroth27** [comment]
Dup of #5562

**Comment by rynowak** [comment]
> We have to determine if this is a sufficiently random enough value to allow a client to reconnect to a server. It's effectively a session identifier and it's likely not enough to present the identifier in itself as evidence to reconnect to a circuit.

We almost certainly want something cryptographically strong, a guid is not. The choice of a guid for this was as a temporary blocker.
