### ISSUE TITLE
RegisterModel.InputModel Localize

### ISSUE THREAD

**Issue by lucasNewhsarp** [aspnet/AspNetCore#7270]
Hi,

Localization not working in generated class RegisterModel.InputModel

1. Using this version of ASP.NET Core '2.2.103'

I'm following the tutorial: https://docs.microsoft.com/pt-br/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#dataannotations-localization

[EmailAddress(ErrorMessage = "...")]

Everyting work fine, but localization on DataAnnotations not working on generated Identity Classes

I'm creating the flolowing subfolders structure for resource file: Resources\Areas\Identity\Pages\Account

and naming the resource file as: RegisterModel.InputModel.pt-br.resx
Maybe the inner class is the problem, I already tried all possible names for the file. 
Can anyone  help me?

**Comment by lucasNewhsarp** [comment]
I figured out.

The name of resource file should be "RegisterModel+InputModel.pt-br.resx"

**Comment by dudekj** [comment]
Hi Lucas,
I was battling this issue unsuccessfully for a while until I have stumbled upon your post.
Thank you for sharing the solution. Could you please satisfy my curiosity and tell me how you have figured it out? With views, controllers, front pages and code-behind I can debug and see the path where the resource file is expected, but with the data annotations it seems to be a black box. 
Thank you in advance,
Joanna

**Comment by lucasNewhsarp** [comment]
Hi,

I put an IStringLocalizer<InputModel> on RegistrerModel controller constructor.
Since I can have an ILocalizer<...> of any type, the framework take care of create an instance for me and debuggin we can see the "_resourceBaseName" for this type wich have this name.
![001](https://user-images.githubusercontent.com/47319965/60685268-7f44f300-9e78-11e9-9cd1-5fbda5a6b437.png)

**Comment by dudekj** [comment]
Brilliant!
Thank you, Lucas.
Joanna
