### ISSUE TITLE
Add a [Bool] data annotation

### ISSUE THREAD

**Issue by frank-borkin** [aspnet/AspNetCore#7273]
Using dotnet core 2.2, parsing JSON on a REST interface, using [Required] to ensure fields aren't missed.
Along comes a boolean field. If it's missing from the JSON it silently gets transformed to false, when I want it to throw a 400.

Current workaround is [Range(typeof(bool), "false", "true")]. What would be neater is [Bool].

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @frank-borkin.
@dougbu, do we have an existing mechanism to achieve this?

**Comment by dougbu** [comment]
When using JSON, use Json.NET attributes e.g. `[JsonProperty(Required = Required.Always)]`. If you were not using `[FromBody]`, our `[BindRequired]` attribute would help in this scenario.

**Comment by frank-borkin** [comment]
@dougbu Am I right that [JsonProperty(Required = Required.Always)] would simply ensure that it was set, but not validate that it's true || false ? Having something which casts any other or no type to true or false is not desired.

**Comment by dougbu** [comment]
@frank-borkin your question was about missing Boolean properties. But, I'm pretty sure Json.NET fails de-serialization when a value cannot be converted. @JamesNK can you confirm?

**Comment by duzenko** [comment]
Look at the RequiredAttribute source code. For bools it's basically just checking if the field is null.
The validators run after the JSON is deserialized to C# object and at that point the boolean field is already its default type value - false.
You should either change your field to `bool?` or use the JSON-specific validation attributes.

**Comment by JamesNK** [comment]
Newtonsoft.Json attempts to convert/coerce values. For example with boolean `true` works and `"true"` works. An error will be thrown if the JSON value can't be used.

**Comment by dougbu** [comment]
Thank you for your feedback. We're closing this issue as the questions asked here have been answered.
