### ISSUE TITLE
FileResult EnableRangeProcessing is an undocumented breaking change

### ISSUE THREAD

**Issue by maknapp** [aspnet/AspNetCore#7279]
With v2.1.0, FileResult does no longer processes the Range header by default - it needs to be enabled via the EnableRangeProcessing flag. This seems like a breaking change that should be documented in the 2.0 to 2.1 migration.

https://github.com/aspnet/AspNetCore/commit/2fcfc6be7ce0f834feb65b705938fe344153ac1f
https://github.com/aspnet/Mvc/issues/6780
https://github.com/aspnet/Mvc/pull/6895

**Comment by danroth27** [comment]
This issue was moved to aspnet/Docs#10891
