### ISSUE TITLE
dotnet new react requires .env

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/AspNetCore#7286]
_From @Rick-Anderson on February 1, 2019 21:38_

See https://github.com/aspnet/Docs/pull/10423 and [Use the React project template](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio)

Add a *.env* file to the *ClientApp* subdirectory with the following setting:

     `BROWSER=none`

This will prevent your web browser from opening when starting the CRA server externally.

_Copied from original issue: dotnet/templating#1752_

**Comment by mkArtakMSFT** [comment]
@danroth27, is this what we want to do?

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS 	request that [here](https://github.com/aspnet/Docs/pull/10423#issuecomment-459682740)
