### ISSUE TITLE
Simplify toolset resolution in Razor Sdk for 3.0 targeting projects

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#7294]
In 2.x, the Razor SDK had to resolve what the compilation toolset was - Precompilation vs the Sdk. This was required to allow supporting precompilation package while also referencing the Razor Sdk. This has the unfortunate behavior in that if the Sdk cannot conclusively determine it's being used, it gives up and assumes the precompilation tool is in effect. We can simplify this for 3.0 targeting projects since precompilation is no longer supported for it.

**Comment by pranavkm** [comment]
Would be good to front load Sdk changes so we have time to let it bake.

**Comment by mkArtakMSFT** [comment]
@pranavkm, is this just a code cleanup?

**Comment by pranavkm** [comment]
Not really. It makes the code correct for 3.0 scenarios.
