### ISSUE TITLE
Compile error on new project version 0.8.0-preview-19104-04

### ISSUE THREAD

**Issue by ejdoming** [aspnet/AspNetCore#7295]
**Program.cs**
        public static IWebAssemblyHostBuilder CreateHostBuilder(string[] args) =>
            BlazorWebAssemblyHost.CreateDefaultBuilder()
                .UseBlazorStartup<Startup>();

**Error message:**
Error	CS0433	The type 'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.7.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Blazor, Version=0.8.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	GCMobileSPA1	X:\Desenvolvimento\fontes\Jean\GCMobSPA\GCMobileSPA1\Program.cs

**Comment by ejdoming** [comment]
Solved. I was using Blazored.LocalStorage, that use 0.7.0 version of Blazor libs.

**Comment by arivera12** [comment]
Just ran into same issue I was using a component that was running on 0.7.0 instead of 0.8.0.
