### ISSUE TITLE
Blazor component library bug with Razor Components project

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#7300]
### Describe the bug
The blazor component library (dotnet new blazorlib) is not working properly with razor components (blazor server side). Specifically the static files that are embeded in the library are not served when the page is loaded.

### To Reproduce
1. Using dotnet 3.0 preview 2 (3.0.100-preview-010184)
2. `dotnet new razorcomponents -o RazorComponents1`
3. `dotnet new blazorlib -o RazorComponents1\BlazorLib1`
4. `dotnet add RazorComponents1\RazorComponents1.App reference RazorComponents1\BlazorLib1`
5. Add the following code to RazorComponents1.App\Pages\Index.cshtml
`<Component1 />`
6. Add the following code to RazorComponents1\RazorComponents1.App\_ViewImports.cshtml
`@addTagHelper *,BlazorLib1`
7. `dotnet run --project RazorComponents1\RazorComponents1.Server`

**Comment by danroth27** [comment]
Thanks @stavroskasidis for reporting this issue! This is a known limitation with the Razor Components template in Preview 2, but we are tracking addressing this limitation with issue #6349

**Comment by SQL-MisterMagoo** [comment]
@stavroskasidis 
Until the Microsoft team get this working, I have written a project that brings this functionality back for Razor Components [BlazorEmbedLibrary](https://www.nuget.org/packages/BlazorEmbedLibrary/)
If you add this to your App, it will embed the static CSS and JS files at runtime into the head of your app using browser blob storage. 
You might find it useful as a workaround.
