### ISSUE TITLE
Unable to run blazor app - get 502.5 error (Blazor 0.8.0)

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7302]
_From @henrikmbach on Wednesday, 06 February 2019 14:46:21_

VS 2019 Preview 2.2
Blazor 0.8.0

I get this error in my browser:
"HTTP Error 502.5 - Process Failure"

"dotnet --info" on command line gives me:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184

There is no global.json that I can delete from my project (it fixed the problem I had on an earlier version of Blazor).

In the "New ASP.NET Core Web Application" dialog I have selected "Blazor" from the list of templates (not "Razor Components" as described in the getting started thing on the Blazor homepage). Ctrl-F5 gives me the above error in my browser.

NB! If I select "Razor Components" instead of "Blazor" described above, Ctrl-F5 works fine. So it appears that the option "Blazor" is broken. 

_Copied from original issue: aspnet/Blazor#1781_

**Comment by danroth27** [comment]
@henrikmbach Thanks for reporting this issue! I'm sorry you're having trouble getting going with Blazor 0.8.0.

Could you please try switching the Blazor app to run as a standalone project instead of running behind IIS Express and then see what errors show up in the console logs? To do this open a command prompt in the directory of the Blazor app and type `dotnet run`. Report any errors you see here.

**Comment by henrikmbach** [comment]
It works fine without IIS express.
Then I tried to use the Blazor 0.8.0 the normal way and it also worked fine, so this problem was temporary.
This issue can be closed.

**Comment by danroth27** [comment]
Got it. This may have been due to a known issue with the Blazor template when it is the first .NET Core app run. We should have this addressed in a future release.

**Comment by joshcomley** [comment]
I am having the exact same issue with a fresh install of Blazor and the exact same configuration.

How do I configure it to run standalone? If I try to use `dotnet run` from the command line all I get is:

    Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

How can I proceed?

**Comment by danroth27** [comment]
@joshcomley This is a [known issue](https://github.com/aspnet/blazor/releases) with the current preview of .NET Core 3.0. You may see this error when running a standalone Blazor app and you haven't yet restored packages for any .NET Core apps. To workaround this issue create any .NET Core app (ex `dotnet new console`) and then rerun the Blazor app.

**Comment by joshcomley** [comment]
@danroth27 thank you, following your instructions got things working for me
