### ISSUE TITLE
Change runtime SiteExtension to replace AspNetCoreModuleV2 definition

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7307]
Epic https://github.com/aspnet/AspNetCore/issues/8833

Currently, the module is only inserted when missing and it's always present since it was deployed to AppServices.

We need to change xdt to use `Replace` transformation.

This is blocked by AppService having protection from changing default global module location. They have been contacted and are going to relax the rule for AspNetCoreModuleV2, ETA March'19.

**Comment by pakrym** [comment]
@shirhatti

**Comment by muratg** [comment]
Triage notes:
Revisit once Antares fix is out. We need to update the site extension

**Comment by anurse** [comment]
We need to revisit this since we believe the Antares fix is out.

**Comment by jkotalik** [comment]
I'll need to sync with my boy @pakrym to figure out how to test site extensions.
