### ISSUE TITLE
Remove MessagePack dependency from Razor Components

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#7311]
We need to remove the dependency on message pack so that Razor Components can ship in the shared framework.

The work here is to procure a replacement *lite* message pack serializer that we can use as an implementation detail (provided by signalR) - and then adopt it.

**Comment by danroth27** [comment]
This is an ask on the SignalR folks: #7387.

**Comment by BrennanConroy** [comment]
I believe @pranavkm has been working on a prototype for this
