### ISSUE TITLE
SingleOrg auth does not work behind reverse proxy

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/AspNetCore#7312]
_From @chriskuech on February 6, 2019 3:35_

Reverse proxies typically terminate HTTPS and relay requests over HTTP.  SingleOrg auth appears to infer the protocol from the request and use that protocol in the reply URL.  If the SingleOrg auth application is behind a reverse proxy, then the client requests the HTTPS site, the reverse proxy relays the HTTPS request as HTTP to the dotnet app, then the dotnet app receives the HTTP request, and redirects to the AAD endpoint using HTTP in the reply URL.  If we use HTTP in the reply URL, then the client receives a warning for using HTTP.

We should be able to set the reply URL in appsettings.json or set a "use HTTPS in the reply URL" flag to mitigate this issue.

_Copied from original issue: dotnet/templating#1757_

**Comment by Tratcher** [comment]
The recommendation is to use forwarder headers to convey the correct scheme to the app. See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2
