### ISSUE TITLE
Test logs are not being published in internal VSTS builds

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7316]
It worked in https://dev.azure.com/dnceng/internal/_build/results?buildId=88141&view=results
Stopped working in https://dev.azure.com/dnceng/internal/_build/results?buildId=88219&view=results

**Comment by Eilon** [comment]
Those 2 builds are since deleted.

But the work item here is to make sure that test log output (e.g. tests deriving from `LoggedTest`) even during successful test runs needs to be saved to the artifacts folder.
