### ISSUE TITLE
Remove obsolete APIs from Razor

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#7326]
See #3654 for details.

#### (55) src\Mvc\src\Microsoft.AspNetCore.Mvc.Razor\Compilation\CompiledViewDescriptor.cs
Links: <a href="https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/CompiledViewDescriptor.cs#L89">[master]</a> | <a href="https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/CompiledViewDescriptor.cs#L89">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/AspNetCore/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.Razor%2FCompilation%2FCompiledViewDescriptor.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FAspNetCore%2Fblob%2Fmaster%2Fsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.Razor%2FCompilation%2FCompiledViewDescriptor.cs%23L89%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%20%20%20%20%5BObsolete%28%22Use%20Item%20instead.%20RazorViewAttribute%20has%20been%20superseded%20by%20RazorCompiledItem%20and%20will%20not%20be%20used%20by%20the%20runtime.%22%29%5D%0D%0A%20%20%20%20%20%20%20%20public%20RazorViewAttribute%20ViewAttribute%20%7B%20get%3B%20set%3B%20%7D%0D%0A%23pragma%20warning%20restore%20CS0618%20%2F%2F%20Type%20or%20member%20is%20obsolete%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/CompiledViewDescriptor.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
        [Obsolete("Use Item instead. RazorViewAttribute has been superseded by RazorCompiledItem and will not be used by the runtime.")]
        public RazorViewAttribute ViewAttribute { get; set; }
#pragma warning restore CS0618 // Type or member is obsolete
```

---

#### (56) src\Mvc\src\Microsoft.AspNetCore.Mvc.Razor\Compilation\RazorViewAttribute.cs
Links: <a href="https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/RazorViewAttribute.cs#L8">[master]</a> | <a href="https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/RazorViewAttribute.cs#L8">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/AspNetCore/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.Razor%2FCompilation%2FRazorViewAttribute.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FAspNetCore%2Fblob%2Fmaster%2Fsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.Razor%2FCompilation%2FRazorViewAttribute.cs%23L8%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%5BObsolete%28%22This%20attribute%20has%20been%20superseded%20by%20RazorCompiledItem%20and%20will%20not%20be%20used%20by%20the%20runtime.%22%29%5D%0D%0A%20%20%20%20%5BAttributeUsage%28AttributeTargets.Assembly%2C%20AllowMultiple%20%3D%20true%29%5D%0D%0A%20%20%20%20public%20class%20RazorViewAttribute%20%3A%20Attribute%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/RazorViewAttribute.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
    [Obsolete("This attribute has been superseded by RazorCompiledItem and will not be used by the runtime.")]
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    public class RazorViewAttribute : Attribute
```

---

#### (57) src\Mvc\src\Microsoft.AspNetCore.Mvc.Razor\Compilation\ViewsFeatureProvider.cs
Links: <a href="https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs#L17">[master]</a> | <a href="https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs#L17">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/AspNetCore/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.Razor%2FCompilation%2FViewsFeatureProvider.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FAspNetCore%2Fblob%2Fmaster%2Fsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.Razor%2FCompilation%2FViewsFeatureProvider.cs%23L17%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%5BObsolete%28%22This%20type%20is%20obsolete%20and%20will%20be%20removed%20in%20a%20future%20version.%20See%20%22%20%2B%20nameof%28IRazorCompiledItemProvider%29%20%2B%20%22%20for%20alternatives.%22%29%5D%0D%0A%20%20%20%20public%20class%20ViewsFeatureProvider%20%3A%20IApplicationFeatureProvider%3CViewsFeature%3E%0D%0A%20%20%20%20%7B%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
    [Obsolete("This type is obsolete and will be removed in a future version. See " + nameof(IRazorCompiledItemProvider) + " for alternatives.")]
    public class ViewsFeatureProvider : IApplicationFeatureProvider<ViewsFeature>
    {
```

---

#### (58) src\Mvc\src\Microsoft.AspNetCore.Mvc.RazorPages\Infrastructure\PageArgumentBinder.cs
Links: <a href="https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/PageArgumentBinder.cs#L10">[master]</a> | <a href="https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/PageArgumentBinder.cs#L10">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/AspNetCore/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.RazorPages%2FInfrastructure%2FPageArgumentBinder.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FAspNetCore%2Fblob%2Fmaster%2Fsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.RazorPages%2FInfrastructure%2FPageArgumentBinder.cs%23L10%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%5BObsolete%28%22This%20type%20is%20obsolete%20and%20will%20be%20removed%20in%20a%20future%20version.%22%29%5D%0D%0A%20%20%20%20public%20abstract%20class%20PageArgumentBinder%0D%0A%20%20%20%20%7B%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/PageArgumentBinder.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
    [Obsolete("This type is obsolete and will be removed in a future version.")]
    public abstract class PageArgumentBinder
    {
```

---

#### (59) src\Mvc\src\Microsoft.AspNetCore.Mvc.RazorPages\Infrastructure\RazorPageAdapter.cs
Links: <a href="https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/RazorPageAdapter.cs#L22">[master]</a> | <a href="https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/RazorPageAdapter.cs#L22">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/AspNetCore/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.RazorPages%2FInfrastructure%2FRazorPageAdapter.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FAspNetCore%2Fblob%2Fmaster%2Fsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.RazorPages%2FInfrastructure%2FRazorPageAdapter.cs%23L22%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%20%20%20%20%5BObsolete%28%22This%20constructor%20is%20obsolete%20and%20will%20be%20removed%20in%20a%20future%20version.%22%29%5D%0D%0A%20%20%20%20%20%20%20%20public%20RazorPageAdapter%28RazorPageBase%20page%29%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/RazorPageAdapter.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
        [Obsolete("This constructor is obsolete and will be removed in a future version.")]
        public RazorPageAdapter(RazorPageBase page)
        {
```

---

#### (60) src\Mvc\src\Microsoft.AspNetCore.Mvc.RazorPages\Infrastructure\RazorPageAttribute.cs
Links: <a href="https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/RazorPageAttribute.cs#L9">[master]</a> | <a href="https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/RazorPageAttribute.cs#L9">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/AspNetCore/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.RazorPages%2FInfrastructure%2FRazorPageAttribute.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FAspNetCore%2Fblob%2Fmaster%2Fsrc%2FMvc%2Fsrc%2FMicrosoft.AspNetCore.Mvc.RazorPages%2FInfrastructure%2FRazorPageAttribute.cs%23L9%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%5BObsolete%28%22This%20attribute%20has%20been%20superseded%20by%20RazorCompiledItem%20and%20will%20not%20be%20used%20by%20the%20runtime.%22%29%5D%0D%0A%20%20%20%20public%20class%20RazorPageAttribute%20%3A%20RazorViewAttribute%0D%0A%20%20%20%20%7B%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Infrastructure/RazorPageAttribute.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
    [Obsolete("This attribute has been superseded by RazorCompiledItem and will not be used by the runtime.")]
    public class RazorPageAttribute : RazorViewAttribute
    {
```

---

**Comment by NTaylorMullen** [comment]
dfddc4e8ff7dceceafd202ffdd9f5b046424e2df
