### ISSUE TITLE
How to make child component to be rendered in parent component?

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7328]
_From @thainbreese on Wednesday, 06 February 2019 19:07:37_

Both of the parent and child component use the same int array object.

If I change the array in the parent component, the child component has to be rendered again.

How can I do this?

I was tried to bind the object to child component, however it said that cannot bind array object.

_Copied from original issue: aspnet/Blazor#1782_

**Comment by danroth27** [comment]
From @iAmbipinpaul

I believe you want to pass the array to child component and render it there.

**child component** `(child.cshtml)`
```csharp
@if(TTypeNames ==null)
{
// some html to say it's loading 
}else if(TTypeNames.Count ==0)
{
//  // some html to say it's empty
}
else 
{
foreach(var item in TTypeNames )
{
// html
}
}

@functions {   
    [Parameter] List<TType> TTypeNames { get; set; }
    protected override async Task OnParametersSetAsync()
    {
       StateHasChanged();
    }
}
```
now in your **parent component** you can pass data like this 

`<child  TTypeNames ="@TTypeList"></child>`

better to go through this blazor workshop it explains everything in awesome way.
https://aka.ms/blazorworkshop

documentation showing list of orders 
https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/03-show-order-status.md#displaying-the-list-of-orders

**Comment by danroth27** [comment]
Thanks for answering @iambipinpaul!

**Comment by Lupusa87** [comment]
In parent [capture reference](https://docs.microsoft.com/en-us/aspnet/core/razor-components/components?view=aspnetcore-3.0#capture-references-to-components) for child component.

Make inside child public method refresh or any name and call inside statehaschanged.

Call this child.refresh from parent after array change.

Child should receive this array as parameter.

Hope it helps, if answer is not clear I can write more detailed, if it does not help please share your repo.
