### ISSUE TITLE
[Blazor] Json serializer for JSInterop

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#7346]
In the [blog post](https://blogs.msdn.microsoft.com/webdev/2019/02/05/blazor-0-8-0-experimental-release-now-available/) it's mentioned that we can now use NewtonsoftJson.

I want to know is this also supposed to work when serializing object through **JSInterop**?
Or is Blazor still using built-in **Json** serializer?

The problem is that I need it to be able to recognize DataContract and DataMember attributes.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @stsrki.
@SteveSandersonMS, can you please answer this question? Thanks!

**Comment by SteveSandersonMS** [comment]
Currently `JSInterop` is limited to using the built-in serializer. If you want, you can use an external serializer to convert to a `string`, then pass that to `JSInterop`. However this is not as efficient as you will need to receive a `string` at the other side and then use `JSON.parse`.

Later on we plan to swap out the built-in (very limited) serializer for the new standard JSON library that is coming to .NET Core 3.0.

**Comment by StephenOTT** [comment]
Is there a issue we can follow on this for the new Json lib?

**Comment by StephenOTT** [comment]
This seems to be the issue to track https://github.com/dotnet/corefx/issues/33115
