### ISSUE TITLE
Blazor event handlers cause Visual Studio to hang when inside child content

### ISSUE THREAD

**Issue by EdCharbeneau** [aspnet/AspNetCore#7356]
### Describe the bug

Event handlers cause Visual Studio to hang when writing them inside of child content (aka RenderFragment).

### To Reproduce
1. Using Blazor 0.8.0
2. Use a component that has RenderFragment parameter begin typing an event handler
3. The IDE will freeze and attempt to restart.

```
<KendoGrid Data=@GridData>
    <KendoGridColumns>
        <KendoGridColumn Field=@nameof(Product.ProductId)>
            <Template>
                <KendoButton OnButtonClick="@((...*freezes here*
            </Template>
        </KendoGridColumn>
        <KendoGridColumn Field=@nameof(Product.ProductName)/>
        <KendoGridColumn Field=@nameof(Product.UnitPrice)/>
    </KendoGridColumns>
</KendoGrid>
```

### Expected behavior
Intellisense, wonderful IDE magic, and ponies

### Additional context
Using Telerik UI for Blazor
Visual Studio 2019 Preview 
Writing the code outside of the context of the parent seems to work fine.

**Comment by EdCharbeneau** [comment]
https://youtu.be/iNbVwZM4wos?t=3335

Looks like it happens when using `eventName="@()"`

**Comment by rynowak** [comment]
@ajaybhargavb is this one of the issues you fixed?

**Comment by ajaybhargavb** [comment]
Yup, fixed by https://github.com/aspnet/AspNetCore-Tooling/pull/190

**Comment by rynowak** [comment]
@EdCharbeneau - this will be released in VS 2019 Preview 4

**Comment by EdCharbeneau** [comment]
Great to hear. Thanks for letting me know @rynowak
