### ISSUE TITLE
Provide samples for client code generation

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#7359]
Also include samples.

**Comment by mkArtakMSFT** [comment]
@glennc, what do you want to be covered as part of this work? Just want to make sure we don't miss anything.

**Comment by dougbu** [comment]
Is this  a tracking bug for aspnet/Docs#8461 and aspnet/Docs#8465?

**Comment by mkArtakMSFT** [comment]
Depends whether the plan for the docs is to include samples or not. If no, then this can be the issue tracking providing samples.

**Comment by mkArtakMSFT** [comment]
Renaming to title to cover samples work as part of this.

**Comment by mkArtakMSFT** [comment]
@glennc - moved this out to preview8

**Comment by Pilchie** [comment]
@glennc is this happening at some point?

**Comment by mkArtakMSFT** [comment]
Closing this as we have other docs issues in this area, which @dougbu has filed.
