### ISSUE TITLE
angular client to signalr core2.2 blocked by CORS

### ISSUE THREAD

**Issue by foxjazz** [aspnet/AspNetCore#7382]
### Describe the bug
Error trying to negotiate signalR connection (CORS) in asp.net core 2.2
issue described more in detail here:
https://github.com/foxjazz/WebAdmsClient/issues

### To Reproduce
get the client:  https://github.com/foxjazz/WebAdmsClient/issues
get the server: 
https://github.com/foxjazz/WebADMService.git

### Expected behavior
Expect client should connect to the hub on the server.

**Comment by BrennanConroy** [comment]
You need to allow credentials in your cors settings.
https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.2#cross-origin-connections

**Comment by foxjazz** [comment]
@BrennanConroy tried that option. Worse result

**Comment by foxjazz** [comment]
Let's put it this way. It will post updates. But will not connect to Sr hub

**Comment by BrennanConroy** [comment]
>Worse result

Could you share what the result was?

**Comment by foxjazz** [comment]
@BrennanConroy same error but more errors. There are no credentials. So why would it matter. The response doesn't make since. Pull the projects and try them.

**Comment by foxjazz** [comment]
And another thing. For cors why isn't there just an option. Allowanything. Wouldn't someone have considered that?

**Comment by foxjazz** [comment]
this will work in a different project. I give up, I can't figure out what is wrong with mine.
