### ISSUE TITLE
[Blazor] IL Linker not working correctly with IQueryable extensions

### ISSUE THREAD

**Issue by ivanchev** [aspnet/AspNetCore#7383]
### Describe the bug
If you create a class library with some IQueryable extensions, for instance:
```
        public static int CustomCount(this IQueryable source)
        {
            if (source == null) throw new ArgumentNullException("source");
            return source.Provider.Execute<int>(
                Expression.Call(
                    typeof(Queryable), "Count",
                    new Type[] { source.ElementType }, source.Expression));
        }
```

Using that in a WebAssembly Blazor project produces error.

> components.webassembly.js:1 WASM: ﻿[System.InvalidOperationException] No generic method 'Count' on type 'System.Linq.Queryable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic.

### To Reproduce
1. Add the extension method to a new .netstandard 2.0 class library
2. Create a new simple Blazor project, and reference the class library project
3. In the FetchData page, call the following:
```
    protected override async Task OnInitAsync()
    {
        forecasts = await Http.GetJsonAsync<WeatherForecast[]>("sample-data/weather.json");

        var count = forecasts.AsQueryable().CustomCount();
    }
```

### Expected behavior
No error thrown.

If you disable the IL Linker the issue is not observed:
```
<BlazorLinkOnBuild>false</BlazorLinkOnBuild>
```

Tested with both 0.7 and 0.8 versions.

**Comment by danroth27** [comment]
@ivanchev Thanks for reporting this issue!

Since this appears to be an IL linker issue I'm going to move this over to the Mono folks.

**Comment by danroth27** [comment]
This issue was moved to mono/mono#12917
