### ISSUE TITLE
Compact binary SignalR protocol without MessagePack dependency

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7387]
For Razor Components we use a SignalR hub to manage the UI interactions. We need these interactions to be as low latency as possible. Currently we use MessagePack, but we need a default protocol implementation that doesn't have a third party dependency so that it can be fully serviced.

@davidfowl @bradygaster @SteveSandersonMS @mkArtakMSFT

**Comment by AArnott** [comment]
Would a fork of MessagePack satisfy? The one I'm working on is based on neuecc's (and we're collaborating to stay close at this point). I'm currently refactoring and tuning it to work with all the latest .NET Core APIs (e.g. `IBufferWriter<byte>` and `ReadOnlySequence<byte>`).

**Comment by rynowak** [comment]
@AArnott - whatever we ship for Razor Components needs to be *in the box* and have the same support policy as the rest of ASP.NET Core. We're planning to do a reader/writer for this since that meets our requirements to use it.

**Comment by davidfowl** [comment]
After spending some time helping @AArnott refactor MessagePackCSharp, it might make sense to grab and MessagePackWriter and MessagePackReader he's currently writing and bake this into RazorComponents.  It's basically a better version of @pranavkm 's prototype 😄

**Comment by pranavkm** [comment]
Closing in favor of https://github.com/aspnet/AspNetCore/issues/7311 which has more details.
