### ISSUE TITLE
Client Razor Components VS 2019 Lock up - During Runtime

### ISSUE THREAD

**Issue by DragonMastery** [aspnet/AspNetCore#7389]
### Describe the bug
VS 2019 locks up after injecting `@inject HttpClient Http`

### To Reproduce
1. Using this version of ASP.NET Core '3.0 preview 2'
2. Run this code `@inject HttpClient Http`
3. In the Project.App in any .cshtml page
4. Locks up VS 2019 no error code to produce

**Comment by rynowak** [comment]
@ajaybhargavb

**Comment by ajaybhargavb** [comment]
@DragonMastery, I tried to reproduce the hang but couldn't. What version of VS are you using? Also, could you provide a simple repro app? At the very least, could you provide the full contents of the cshtml that causes the hang and the contents of _ViewImports?

**Comment by DragonMastery** [comment]
@ajaybhargavb  [Here is a link to my repo](https://github.com/DragonMastery/BlazorCore)

**Comment by ajaybhargavb** [comment]
@DragonMastery, I tried cloning your repo and running it. I still couldn't reproduce the hang. I tried to type
`@inject HttpClient Http` in most of the cshtml files there. I also tried removing all contents and then typing/copy pasting this but still no hang. I am using the latest VS 2019 preview build which is 2.2. Are you seeing this consistently? Do you have any more specific instructions on how I can repro this?

![norepro](https://user-images.githubusercontent.com/1579269/52511333-5879dd80-2bb4-11e9-9bd7-f95e539a4ecd.gif)

If not, could you try upgrading your VS or uninstall/reinstall VS if you are already on latest and see if it still happens?

**Comment by DragonMastery** [comment]
there is no hang when I type it. it when you run it and go the that page

**Comment by ajaybhargavb** [comment]
Ah this is a runtime issue then. Not sure what you meant by VS locking up. @rynowak, can you please take a look?

**Comment by DragonMastery** [comment]
@ajaybhargavb @rynowak You can also trying putting '@inject HttpClient Http' in the _ViewImports.cshtml file and the runtime completely breaks. It show no errors though and I cannot close VS 2019 without using the task manager.

**Comment by rynowak** [comment]
We made some improvements here in the next release. In Preview 4 this will result in the developer exception page if it throws during prerendering.
