### ISSUE TITLE
Question about enum serialization and routes

### ISSUE THREAD

**Issue by spondishy** [aspnet/AspNetCore#7393]
Hi, I've been struggling with this issue for a day or two and I'm trying to do exactly the same as this link. 

https://github.com/aspnet/AspNetCore/issues/4008

When I run this code it defaults to the first item in the enum. Basically the value in the route appears to be being ignored. The TypeConverter code certainly looks like its not executing to me. I must be missing something somewhere. Is there anything obvious missing in the solution in the link above?

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @spondishy.
Looks like @JamesNK's suggestion to use a custom `TypeConverter` had solved the issue in the related thread. If you're doing that and still are facing an issue, then something is different in your case. Please share a sample project which would repro the issue you're facing, so we can assist you better.
