### ISSUE TITLE
Helix tests fail to install .NET Core on Fedora 28 and 27

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#7398]
Example: https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190208.14

It appears tests on Fedora.28.Amd64.Open consistently fail to boot.

```
./runtests.sh Common.Tests.dll 3.0.100-preview-009750 3.0.0-preview-27405-2
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview-009750/dotnet-sdk-3.0.100-preview-009750-linux-x64.tar.gz
curl: (23) Failed writing body (0 != 16383)
```

Seems like there is something broken in the version of libcurl installed.

cc @Eilon  @HaoK  - I'm going to disable Fedora 28

**Comment by natemcmaster** [comment]
Sometimes `wget` works better. If Fedora 28/27 have that, maybe we can try that instead of curl?

**Comment by HaoK** [comment]
Sure sounds like wget has the ability to recover from broken transfers too which is nice

**Comment by HaoK** [comment]
Most likely due to https://github.com/dotnet/core-eng/issues/5204

**Comment by HaoK** [comment]
Reenabled via https://github.com/aspnet/AspNetCore/pull/7543
