### ISSUE TITLE
Infinite loop in cshtml - application permanently locked until restart, no way to debug

### ISSUE THREAD

**Issue by kanadaj** [aspnet/AspNetCore#7411]
### Describe the bug
It would be nice to have a size limit on the output buffer of the CSHTML files; otherwise, an infinite loop would completely lock down system resources, including CPU and up to 12-13GB of RAM, but the process somehow never runs into an OutOfMemoryException; I believe this is due to the buffer being flushed once it hits a certain size.

### To Reproduce
1. Using ASP.NET Core 2.1.1
2. With the following in the cshtml:
```cs
do
{
    @("Some message\n")
} while(true)
```

### Expected behavior
Get a meaningful exception _eventually_, or at least log a warning into the logging pipeline to make debugging such behaviour easier. Instead, the host system is simply locked up into an infinite loop with no sign of what's happening.

**Comment by davidfowl** [comment]
I don’t think we should do anything here. An infinite loop in lots of other places can have the same effect.

**Comment by kanadaj** [comment]
Maybe it'd have a similar effect, but normally there is no pipeline in the way that automatically flushes the buffer, essentially stopping the system from throwing even an `OutOfMemoryException`.

**Comment by kanadaj** [comment]
Even if not throwing, logging a Warning that can be turned off would already be very helpful, since infinite loops like this are way too hard to diagnose otherwise, as no other log would ever indicate the issue.

**Comment by davidfowl** [comment]
I'm still not convinced we should do anything here. This is like any other logic bug in application code. Do you have an example where this happened in some less obvious way? That might make fore a more convincing argument.

**Comment by kanadaj** [comment]
@davidfowl I have a custom Error page which unwraps InnerExceptions iteratively for the error message for administrators of our website, since the standard error message for EF6 validation errors isn't particularly helpful (it just says "look at the inner exception"), but there as an error made with the code, so inside the while loop, instead of `err = err.InnerException` it said `err = Model.Error.InnerException`, causing the page to print the same message over and over. Sadly, there was absolutely 0 indication this is what caused the freezing of the app servers, I just got lucky the team member who caused it reported back step-by-step what happened.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kanadaj.
This is not something we plan to add support for in the near future.
