### ISSUE TITLE
<summary> description of the BlazorOptions class in Razor Components is wrong...

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#7416]
In the <summary> tag for the BlazorOptions class 
<see cref="ComponentsApplicationBuilderExtensions.UseBlazor(IApplicationBuilder, BlazorOptions)"/>

should be 
<see cref="BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder, BlazorOptions)"/>

Note: I've previously posted issues about similar mistakes, to which the Asp.Net team responded with the suggestion that I should post a Pull request. Unfortunately, I can't post Pull requests. You guys should do it yourselves.

**Comment by enetstudio** [comment]
In the `<summary>` tag for the BlazorOptions class
 `<see cref="ComponentsApplicationBuilderExtensions.UseBlazor(IApplicationBuilder, BlazorOptions)"/>`

should be
`<see cref="BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder, BlazorOptions)"/>`
Note: I've previously posted issues about similar mistakes, to which the Asp.Net team responded with the suggestion that I should post a Pull request. Unfortunately, I can't post Pull requests. You guys should do it yourselves.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @enetstudio.
Sure, we'll fix it.
