### ISSUE TITLE
Blazor onpointerdown event gives error

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/AspNetCore#7418]
### Describe the bug
When onpointerdown event fires I get error.

### To Reproduce
1. In Blazor 0.8.0 standalone app I dynamically create element, register pointer event;
2. `builder.AddAttribute(k++, "onpointerdown", OnPointerDown);`
3. `public void OnPointerDown(UIPointerEventArgs e) {};`
4. When I click on element I get this error:
System.ArgumentException: Object of type 'System.Int64' cannot be converted to type 'System.String'.

### Expected behavior
It should invoke OnPointerDown method with proper UIPointerEventArgs.

### Screenshots
![untitled](https://user-images.githubusercontent.com/40779557/52525497-a6581980-2c78-11e9-8fc4-358647df2bdb.png)

### Additional context
I guess it happens with all pointer events.

**Comment by Lupusa87** [comment]
[EventHandlers.cs](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/EventHandlers.cs#L72) is showing:

`[EventHandler("pointerdown", typeof(UIPointerEventArgs))]`

not **on**pointerdown


but if I do `builder.AddAttribute(k++, "pointerdown", OnPointerDown);` and click element nothing happens.

So another question - which is correct pointerdown or **on**pointerdown?

**Comment by Lupusa87** [comment]
I found where is problem.

According to [this](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerId) PointerID is number.

"pointerEvent.pointerId - The pointer event's unique identifier number."


[Here](https://github.com/aspnet/AspNetCore/blob/5a70f5312fb57fc3788e5af56a99e7b43761e195/src/Components/Browser.JS/src/Rendering/EventForDotNet.ts#L303) in EventForDotNet.ts we have also number.

```
interface UIPointerEventArgs extends UIMouseEventArgs {
  pointerId: number;
  width: number;
  height: number;
  pressure: number;
  tiltX: number;
  tiltY: number;
  pointerType: string;
  isPrimary: boolean;
}
```

But [here](https://github.com/aspnet/AspNetCore/blob/5a70f5312fb57fc3788e5af56a99e7b43761e195/src/Components/Components/src/UIEventArgs.cs#L333) we have string.

```
public class UIPointerEventArgs : UIMouseEventArgs
    {
        /// <summary>
        /// A unique identifier for the pointer causing the event.
        /// </summary>
        public string PointerId { get; set; }
```


So this is giving cast error - Object of type 'System.Int64' cannot be converted to type 'System.String'

If we change PointerID type to long issue will be addressed.

I will try now to make PR.

**Comment by mkArtakMSFT** [comment]
Thanks for finding and submitting a PR, @Lupusa87.
@javiercn, can you please review the referenced PR? Thanks!
