### ISSUE TITLE
ResponseCacheAttribute behavior is different between ASP.NET Core  2.0 and 2.1 Razor Pages apps.

### ISSUE THREAD

**Issue by suffyanaziz** [aspnet/AspNetCore#7421]
I have a Page on which I am displaying a number of widgets. Each widget is a razor page and has its own method (..cshtml.cs) . Each Razor Page method sends a random request to the API (every time the page refreshes) and ofcourse a different response comes every time from the API according to request (because I am using random input values for the request) for each widget.

Anyways, my goal of caching data for each widget on client side has been achieved using [ResponseCache(Location = ResponseCacheLocation.Client, Duration = 30)] on each Razor Page method. 

I have the same project on ASP:NET Core 2.0 and I want to do the same thing for it as well. When I tried the same thing on that project, it is not caching the widgets. May be because Response caching in Razor Pages is available in ASP.NET Core 2.1 or later only? What is the alternative of it in ASP.NET Core 2.0?

Thanks

**Comment by pranavkm** [comment]
Support for the `ResponseCacheAttribute` with Razor Pages was added in 2.1.0 (See https://github.com/aspnet/Mvc/issues/6437). Given that 2.0 went out of support late last year (see https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018), I'd recommend upgrading your application to 2.1
