### ISSUE TITLE
How to save local storage data into a database in ASP.Net Core 2.0 Razor Pages?

### ISSUE THREAD

**Issue by suffyanaziz** [aspnet/AspNetCore#7427]
I am using grid stack in ASP.NET Core razor page to save widgets in locals torage. The same thing I want to do for on server side as well. For that purpose I want to store the dashboard name as key and serializedData as value in database for each user. How can this be done? Thanks

Following is the code :

     this.saveGrid = function () {
                    this.serializedData = _.map($('.grid-stack > .grid-stack-item:visible'), function (el) {
                        el = $(el);
                        var node = el.data('_gridstack_node');  
                         return {
                            x: node.x,
                            y: node.y,
                            width: node.width,
                            height: node.height,
                            minwidth: node.minWidth,
                            maxwidth: node.maxWidth,
                            minheight: node.minHeight,
                            maxheight: node.maxHeight,
                            id: node.id,
                            view: node.view,
                     
                        };
                    }, this);

                    localStorage.setItem("@DashboardName", JSON.stringify(this.serializedData));
                  

                    return true;

                }.bind(this);

                this.clearGrid = function () {
                    this.grid.removeAll();
                    return true;

                }.bind(this);

            

                $('#save-widgets').click(this.saveGrid);

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by NTaylorMullen** [comment]
Definitely a StackOverflow question.
