### ISSUE TITLE
TestServer HttpContext.Abort does nothing

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#7449]
Hosting a website with TestHost and calling `HttpContext.Abort()` inside a request does not set `HttpContext.RequestAborted`.

**Comment by huysentruitw** [comment]
Does this ever work (even outside `TestHost`) ? I'm trying to see what needs to be done here, but all I find is that [`HttpContext.Abort()`](https://github.com/aspnet/AspNetCore/blob/4646ed56189a8ee36ced6397dd4f86fce9e6a8e8/src/Http/Http/src/DefaultHttpContext.cs#L163) calls `LifetimeFeature.Abort();` which is an [empty method](https://github.com/aspnet/AspNetCore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/Http/src/Features/HttpRequestLifetimeFeature.cs#L12).

**Comment by huysentruitw** [comment]
Never mind, it's supposed to be empty as the purpose is to let users implement their own feature implementing `IHttpRequestLifetimeFeature`. 😎

**Comment by davidfowl** [comment]
Yes it works outside of test host. Nothing uses that default feature implementation, servers implement their own.

**Comment by Tratcher** [comment]
Accepted via tests, no out of band SDK testing required.
