### ISSUE TITLE
After update to Blazor 0.8 library _content missing

### ISSUE THREAD

**Issue by sven5** [aspnet/AspNetCore#7451]
### Describe the bug
In Blazor library it's impossible to load client side files from "magical" folder _content after update to .NET Core 3.0 Preview 2 and Blazor 0.8.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.0-preview-19705-0444'
2. Update Blazor library to use the following packages:

` <ItemGroup>
<PackageReference Include="Microsoft.AspNetCore.Components.Browser" Version="3.0.0-preview-19075-0444" />
<PackageReference Include="Microsoft.AspNetCore.Components.Build" Version="3.0.0-preview-19075-0444" />
  </ItemGroup> `

**Edit:** Need to say that my Blazor App runs as a mapped sub-application:
```
app.Map("/Blazor", branchApp =>
{
	branchApp.UseStaticFiles();
	branchApp.UseRazorComponents<App.Startup>();
});

```

But this was no issue in 0.7.
This seems to be only an issue with Razor Components (server-side). In client side scenario (Blazor) it's working correctly.

### Expected behavior
I expect the folder _content to be accessible and visible through debugging tools in the browser as it was with Blazor 0.7

### Screenshots
As you can see in the following screenshot, the folder _content is not available.
![image](https://user-images.githubusercontent.com/8734624/52552461-9ce9c100-2de0-11e9-84c5-fbe98eb786b8.png)

### Additional context
Include the output of `dotnet --info`

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sven5.
We don't yet support content files in Razor Components. This is something on our backlog and we plan to address it in the future: https://github.com/aspnet/aspnetcore/issues/6349

**Comment by SQL-MisterMagoo** [comment]
@sven5 Until the Microsoft team get this working, I have written a project that brings this functionality back for Razor Components [BlazorEmbedLibrary](https://www.nuget.org/packages/BlazorEmbedLibrary/)
If you add this to your App, it will embed the static CSS and JS files at runtime into the head of your app using browser blob storage. 
You might find it useful as a workaround.
