### ISSUE TITLE
Breakpoint not working with .NET Core 2.2, Angular, TypeScript with Windows Auth.

### ISSUE THREAD

**Issue by Horizont77** [aspnet/AspNetCore#7458]
When I use Angular + .Net Core 2.2 with Windows Auth, Angular Debugging does not work.

```json
launchSettings.json:
  "iisSettings": {
    "windowsAuthentication": true, 
    "anonymousAuthentication": false, 
    "iisExpress": {
      "applicationUrl": "http://localhost:55749",
      "sslPort": 44362
    }
  },
```

do you have any solution?

I also tested in .Net Core 3.0 Preview 2 and there is the same problem.

**Comment by muratg** [comment]
Where do you set the breakpoint on?

**Comment by Horizont77** [comment]
Hi Murat,

i'll send you a screenshot where i did it.

(this breakpoint works very well with "anonymousAuthentication:true", "windowAuthentication:false" ). see picture.

![angular_error](https://user-images.githubusercontent.com/12067363/52584054-6b4d1600-2e31-11e9-913a-93ef76ee1302.PNG)

if i do it again Win. Auth set, then only works c# codes. if you want, i can send you the project.

Thanks.

**Comment by Horizont77** [comment]
I have just tested with .Net Core. 2.1. it works without problem

**Comment by muratg** [comment]
Did you try a `console.log` to see if that codepath is even executed? Sounds like an application behavior difference (between your different auth codepaths) to me.

**Comment by Horizont77** [comment]
I did not try it and didn't anything changed.

just;
(Standart settings)
windowsAuthentication": false,
"anonymousAuthentication": true

to

"windowsAuthentication": true,
"anonymousAuthentication": false

Thats all..

Everything works fine if I use standard settings.

**Comment by muratg** [comment]
Well, can you try it? Just add a `console.log` line at the place you're trying to debug. And see if that code path is executed. The only thing I can think of (with the information you provided) is that your TypeScript method is NOT executed when you make the change. `launchSettings.json` changes shouldn't be able to impact TypeScript/JavaScript _debugging_.

**Comment by Horizont77** [comment]
yes. i tried and "console.log" did not executed.

**Comment by muratg** [comment]
OK, so your app code is doing things differently. I'm guessing you're going through an "authenticated" path when "anonymousAuthentication" is set, and through an "unauthenticated" code path when "windowsAuthentication" is set.

**Comment by Horizont77** [comment]
I found the others discussing here. that's almost a similar problem.

https://developercommunity.visualstudio.com/content/problem/348287/typescript-debugging-doesnt-work-within-an-angular.html

**Comment by muratg** [comment]
No, that looks completely unrelated. In your case, if the code path is not executed, the breakpoint of course wouldn't be hit.

**Comment by Eilon** [comment]
To report issues with Visual Studio, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.
