### ISSUE TITLE
Source code for Microsoft.AspNet.WebApi.Client

### ISSUE THREAD

**Issue by poke** [aspnet/AspNetCore#7460]
[`Microsoft.AspNet.WebApi.Client`](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/) is a dependency of ASP.NET Core and also included in the meta package. But I haven’t been able to find any source for this.

The NuGet package information lists the [AspNetWebStack repo](https://github.com/aspnet/AspNetWebStack) as its source repository but the WebApi.Client does not appear to be in there.

Is there any source available for this package?

**Comment by poke** [comment]
Okay, do I get this right that `Microsoft.AspNet.WebApi.Client` is just a terrible package name for [`System.Net.Http.Formatting`](https://github.com/aspnet/AspNetWebStack/tree/master/src/System.Net.Http.Formatting)?

**Comment by muratg** [comment]
cc @danroth27 @Eilon

**Comment by danroth27** [comment]
Yup, that's correct. The code is in the https://github.com/aspnet/aspnetwebstack repo under System.Net.Http.Formatting.

**Comment by davidfowl** [comment]
https://github.com/aspnet/AspNetWebStack/tree/master/src/System.Net.Http.Formatting

**Comment by poke** [comment]
Thanks for the clarification everyone!

Is there a reason why this cannot be properly delivered through the [`System.Net.Http.Formatting` NuGet package](https://www.nuget.org/packages/System.Net.Http.Formatting)? That package is unlisted and says that’s it’s just legacy and the `WebApi.Client` package should be used instead now—but to me, it actually seems like the `WebApi.Client` package is the legacy one now.

**Comment by danroth27** [comment]
The https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/ package is not legacy. The naming of the package was deliberate so that it would be easier to find for folks looking for something to help with client scenarios.

**Comment by poke** [comment]
@danroth27 Thanks for the response, however I do think that the name is particularly confusing. A common practice is to name NuGet packages the same way as the contained assembly, or at least very similar. This has the benefit that you immediately know what namespaces you need to look for when consuming the package.

Since this package only contains `System.Net.Http.Formatting.dll` and everything is inside of the `System.Net.Http` namespace, the usage of the package is very unclear.

I think it would help if the NuGet package description at least made this very clear, explaining what is actually contained.

**Comment by IanKemp** [comment]
Apart from the weirdness that @poke has already mentioned, why does the source for this package (which is required by ASP.NET Core) live in the AspNetStack repo (which is ostensibly only for non-Core stuff)?

The fact that this stuff isn't part of ASP.NET core also makes for some gaps around documentation. For example, if you go to https://docs.microsoft.com/en-us/dotnet/api/system.net.http on either Framework or Core, classes that are shipped in `Microsoft.AspNet.WebApi.Client` - e.g. `PushStreamContent` - aren't listed, and indeed searching doc.smicrosoft.com for `PushStreamContent` yields nothing. But if you F1 on that class name in Visual Studio, you're taken to https://docs.microsoft.com/en-us/previous-versions/aspnet/hh995250(v=vs.118) ...

**Comment by danroth27** [comment]
> why does the source for this package (which is required by ASP.NET Core) live in the AspNetStack repo (which is ostensibly only for non-Core stuff)?

Because it depends on pieces of ASP.NET Web API.

> The fact that this stuff isn't part of ASP.NET core also makes for some gaps around documentation

We should be able to get those addressed regardless of where the source code lives. Please file an issue on https://github.com/dotnet/docs/issues and we'll see about filling the doc gaps.

**Comment by IanKemp** [comment]
> > why does the source for this package (which is required by ASP.NET Core) live in the AspNetStack repo (which is ostensibly only for non-Core stuff)?
> 
> Because it depends on pieces of ASP.NET Web API.

My mistake, I was going on @poke's comment:

> Microsoft.AspNet.WebApi.Client **is a dependency of ASP.NET Core** and also included in the meta package.

which is incorrect (as of this writing) - only the `Microsoft.AspNetCore.App` metapackage depends on `Microsoft.AspNet.WebApi.Client` as well as ASP.NET core itself, and indeed `Microsoft.AspNet.WebApi.Client` is versioned in line with AspNetStack (MVC 5).

I also see that [3.0 will drop this library](https://github.com/aspnet/AspNetCore/pull/6552), which likely means that documentation updates aren't necessary.
