### ISSUE TITLE
[Components][Tooling] Suppport <!DOCTYPE> declarations

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#7464]
Right now the Razor compiler produces content for `<!DOCTYPE html>`. It should produce markup instead so that its not incorrectly encoded when there is a top-level component that acts as the document.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please handle this?

**Comment by mkArtakMSFT** [comment]
@javiercn, is this blocking for pre-rendering? If not, just move this to `preview4` please.

**Comment by pranavkm** [comment]
> Right now the Razor compiler produces content for `<!DOCTYPE html>`

What does that mean?

**Comment by javiercn** [comment]
@mkartakmsft depends on what approach we decide to take.

**Comment by javiercn** [comment]
@pranavkm It produces builder.AddContent instead of builder.AddMarkup

**Comment by javiercn** [comment]
@mkArtakMSFT This is not required for preview3

**Comment by pranavkm** [comment]
Closing - dup of https://github.com/aspnet/AspNetCore/issues/6185
