### ISSUE TITLE
Update HttpConnection (ts) to return a rejected promise rather than throwing (synchronously) when disconnected

### ISSUE THREAD

**Issue by williamwilson** [aspnet/AspNetCore#7465]
### Is your feature request related to a problem? Please describe.
The HttpConnection.send method throws an exception if the connection state is not Connected.  The method returns a Promise<void> however, so the synchronous exception is unexpected and leads to awkward code like:
```typescript
try {
  connection.send('test').catch(e => console.warn(e));
} catch (e) {
  console.warn(e);
}
```
note: Normally the consumer would not be using the HttpConnection directly, but rather a HubConnection.  The code above is the same if connection is of type HubConnection or HttpConnection as HubConnection delegates to HttpConnection in send.

### Describe the solution you'd like
Return a rejected promise with the exception rather than throwing it (note: the start() method returns a rejected promise when the connection is in an unexpected state).

### Describe alternatives you've considered
I've attempted to manually check the state of the connection myself, however this state is kept private forcing me to handle this exception or keep track of the connected state in my own application state as well.

**Comment by williamwilson** [comment]
I apologize, I realized this project is on an older version of the client (1.0.4), and later versions do expose the state.  The initial concern regarding the throwing of an exception synchronously in a method that returns a promise still stands.

**Comment by mikaelm12** [comment]
>and later versions do expose the state

Yeah, was going to point out that we now expose the HubConnection state via the `state()` method. Glad you found that. 

And yes we actually throw in a number of places that we should be returning rejected promises. Thanks for pointing that out. We're going to use this issue to track that work.
