### ISSUE TITLE
HubConnectionState in TS client should have public getter

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#7469]
Currently users have to manually keep track of connection state as mentioned in this bug report https://github.com/aspnet/AspNetCore/issues/7465 As shown below, the method to get the state of the HubConnection in the TS client is private.  https://github.com/aspnet/AspNetCore/blob/abd2a61bdbebfcbc55021bd4212727f0fa95ce52/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L94-L97

This though is a public  API in the C# client https://github.com/aspnet/AspNetCore/blob/abd2a61bdbebfcbc55021bd4212727f0fa95ce52/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L92-L108 and Java client https://github.com/aspnet/AspNetCore/blob/abd2a61bdbebfcbc55021bd4212727f0fa95ce52/src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java#L262-L269

**Comment by BrennanConroy** [comment]
I think the getter is public by default.

https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#16-classes
>Public is the default accessibility for class members, but a programmer can also specify private or protected accessibility for a class member.

**Comment by bradygaster** [comment]
closing as this is the default cc @mikaelm12
