### ISSUE TITLE
Update display name for the Blazor VSIX to just be "Blazor"

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7472]
The current display name for the Blazor VSIX is "ASP.NET Core Blazor Language Service". Besides being really long and cumbersome, the display name is also inaccurate now that the Razor Component tooling is shipping with VS2017. We should update the display name for the VSIX to just be "Blazor".

**Comment by rynowak** [comment]
Or how about just `Blazor Templates`

**Comment by danroth27** [comment]
I prefer to keep it more generic so that we have the flexibility to put whatever Blazor stuff we want in there.
