### ISSUE TITLE
Update HttpSys README

### ISSUE THREAD

**Issue by wjk** [aspnet/AspNetCore#7477]
When I went to the [HttpSys server sources](https://github.com/aspnet/AspNetCore/tree/master/src/Servers/HttpSys), I saw that the README file lists that the library has been archived and moved to the main AspNetCore repo. Of course, we are _in_ the main AspNetCore repo. This message made me confused for a moment because I thought that the HttpSys server has been deprecated, which would be annoying if true. Development on this component has continued since the README was last modified (as of this writing, #7207 was the last PR affecting this component). Would it be possible to please update this README to eliminate this confusion? Thanks!

**Comment by anurse** [comment]
Whoops! We updated the README to show the state as archived before we merged the repos. I submitted https://github.com/aspnet/AspNetCore/pull/8662 to fix this. Thanks for catching this!
