### ISSUE TITLE
VerifyUserTokenAsync() failed with purpose: ResetPassword

### ISSUE THREAD

**Issue by shishir28** [aspnet/AspNetCore#7479]
### To Reproduce
1. Using this version of ASP.NET Core  2.1 
2. When a user try to reset the password I use code like following which is used  to send email to registered user 
 var token = await UserManager.GeneratePasswordResetTokenAsync(user) ;   
            return new ForgotPasswordOperationResult
            {
               ...
                SecurityCode = token, //  I have tried with encoding and decoding as well
               ...
            };

3. Now once when user click on the link and try to change the password  using code like  following , application encounter some problem
    await UserManager.ResetPasswordAsync(user, code, password) // 
4. When the  call to code in step 3 goes to same web server as in step 2 , it works but when it goes to another server it throws VerifyUserTokenAsync() failed with purpose: ResetPassword

### Additional context
I know  I am missing something but not sure what.  
I have tried  services.AddDataProtection().PersistKeysToFileSystem('keyfile path')   and services.AddDataProtection.UseCryptographicAlgorithm(..).SetApplicationName("somename")
but did not help me. 

I dont think it is relevant but I am using same machine key  on app pool level for both web servers . 

I have tried using AddDefaultTokenProviders vs AddTokenProvider (EmailProvider) but end result was same . 

One more finding:  I tried  following  after posting this issue and looks  like it works 
   services.AddDataProtection()
                .PersistKeysToSqlServer(securityDBConnString,"dbo");  
(https://www.nuget.org/packages/AspNetCore.DataProtection.SqlServer/) 

Any pointers will be highly appreciated.

**Comment by KogulVimal** [comment]
@shishir28 , I faced the same issue in my system and found that my entity user model which is inherited from IdentityUser had overridden the field SecurityStamp.

**Comment by shishir28** [comment]
> @shishir28 , I faced the same issue in my system and found that my entity user model which is inherited from IdentityUser had overridden the field SecurityStamp.

Thanks I did not have that problem.  When I used PersistKeysToSqlServer it had solved the issue.

**Comment by jbartolome** [comment]
Hello, regarding the solution that @shishir28 provided, is there any example code on how you enabled the DataProtection and PresistKeysToSqlServer in your Startup.cs file? I'm running into the exact same issue with the same type of configration. Any help is appreciated!
