### ISSUE TITLE
Downlevel OS coverage required for ANCM

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7483]
Moving off teamcity means that we are losing our Windows 7/2012 agents. We've caught real bugs in ANCM that were caused by WinApi or IIS behavioral differences on downlevel OS.

This issue is to track adding the coverage back.

@muratg

**Comment by anurse** [comment]
We have this downlevel coverage now in Helix I believe. Right @jkotalik ?

**Comment by anurse** [comment]
We have this in Helix now.
