### ISSUE TITLE
Support breadth of legal C# identifiers in Razor

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#7485]
The `CSharpIdentifier` class in aspnet/AspNetCore-Tooling supports a subset of the legal Unicode categories for C# identifiers -- something like 4 of 11 valid categories. Should update this class to support the gamut.

See https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/CSharpIdentifier.cs

**Comment by dougbu** [comment]
@Eilon what is the correct label for issues in the AspNetCore-Tooling repo? That repo doesn't seem to have its own issue list and points here.

**Comment by dougbu** [comment]
Nevermind. Use of `char.IsDigit(...)` and `char.IsLetter(...)` covers all of the "missing" categories. There's also a separate special case for `UnicodeCategory.LetterNumber` in `CSharpIdentifier` 😃

**Comment by Eilon** [comment]
To answer the question about labels: Use the label of what area it applies to - changes are, it's `area-mvc`.
