### ISSUE TITLE
SignalR cors issue

### ISSUE THREAD

**Issue by foxjazz** [aspnet/AspNetCore#7490]
https://github.com/foxjazz/AnomaliesClient

![image](https://user-images.githubusercontent.com/867496/52609574-fc74ba80-2e3a-11e9-8b8c-04ea77d020ca.png)

Run the aspnetcore service project first.
after cloning, go into anomaliesclient and run the npm install then ng serve
click the link to http://localhost:4200 for getting angular part running.
You can check for your self at this point the bug is the client fails to connect.

**Comment by BrennanConroy** [comment]
Move the `app.UseHttpRedirection();` call to before `app.UseCors();`

**Comment by foxjazz** [comment]
Hi BrennanConroy, I completely get what you are saying. However  In a previous app, I had this similar setup and posts from angular were working and allowed. But still the signalR hub was unable to connect. So I don't get you.  If you don't mind trying this for yourself, and if you like removing credentials to see this has no affect. There is no cors setting that I have tried in any combination that allows the app to connect to the signalR hub.  If you think there is, please post it, and I will try it. It is easily recreated by pulling the code and running it and seeing that no connection is ever made ever ever ever. I have spent more than a week trying to get this to work. Please let me know if you are able to find a cors setting that will make this work.

**Comment by foxjazz** [comment]
All that said, if credentials are required for using signalR when the origin is not the same, then could we add that to the document somewhere?  Now time to research identity server 4.

**Comment by BrennanConroy** [comment]
>The client was using http to connect, not https.

And that's the problem, you have the https redirect middleware so the client is being redirected to use https which breaks CORS. If you change the client to use https by default then you wont hit an issue with being redirected.

>if credentials are required for using signalR when the origin is not the same, then could we add that to the document somewhere?

https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.2#cross-origin-resource-sharing

**Comment by foxjazz** [comment]
Thank you! I removed the httpsRedirect and it's working.   Thank you thank you.
