### ISSUE TITLE
Remove `CodeGenerator` metadata in default service reference experience

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#7491]
Aim here is to remove the current requirement to specify the `CodeGenerator` metadata on `<Service...Reference>` (soon `<OpenApiReference>` and `<ProtobufReference>`) items in a project file.

Some metadata must remain to say "give me TypeScript" (instead of project's default language) but this should be the exception and not the rule. Fortunately, the type of document is going to be explicit (again `<OpenApiReference>` and `<ProtobufReference>`) and we won't have to choose among multiple tools. Probably best to make `TargetLanguage` the main override we provide in this area. (@glennc agreed?)

This change will require our Open API code generation partners (NSwag, AutoRest, ...) either all implement the same target name or include a well-known property specifying their target's prefix. Either way, the last file that declares a target or updates a property wins. So, unless our partners object, let's avoid the indirection and go with a single Open API target name. (gRPC doesn't have multiple partners for the foreseeable future and should be fine with a single target for that scenario.)

**Comment by dougbu** [comment]
@glennc I put this in Preview4. That make sense to you?

@mkArtakMSFT the "Small" cost here doesn't mean calendar time due to the need for NSwag changes.

**Comment by glennc** [comment]
From discussion today. Generator tag isn't required by default. There will be a language property a customer can add with the values "Default", and "TypeScript" where default means whatever the extensions/language the project is for and TypeScript is TypeScript.

**Comment by dougbu** [comment]
Partially addressed in ce8f053af7e9. Will add language metadata soon.

**Comment by dougbu** [comment]
After offline discussion with @glennc, we've decided to close this issue and await custom input on the feature's overall usability
