### ISSUE TITLE
IFormCollection should provide possibility to check types and headers of form values.

### ISSUE THREAD

**Issue by JulijaRamoskiene** [aspnet/AspNetCore#7498]
### Problem
Provide possibility to get content type and other headers of sections stored in IFormCollection.
For request like this::
```
POST https://localhost:44343/ HTTP/1.1
Content-Type: multipart/form-data; boundary=-------------------------acebdf13572468

---------------------------acebdf13572468
Content-Disposition: form-data; name="jsonPart"
Content-Type: application/json


{"val": 1}
---------------------------acebdf13572468--
``` 
It should be possible to check content-type and other headers while iterating IFormCollection:
```
if (!context.Request.HasFormContentType)
    return;

foreach (var section in context.Request.Form)
    {
    /// I want to check content type of section here
    /// ???
    }

// It is possible to get content type of section with FileName
foreach (var file in context.Request.Form.Files)
    {
    var type = file.ContentType;
    }
```

### Describe the solution you'd like
Interface similar to IFormFile for other form sections.  

### Describe alternatives you've considered
Using MultipartReader as described here:
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.0#uploading-large-files-with-streaming

**Comment by davidfowl** [comment]
@muratg This isn't MVC, it's the core HTTP abstraction.

**Comment by davidfowl** [comment]
Which apparently we've labeled servers...

**Comment by anurse** [comment]
There's a bunch of API needed here and I don't think we're prepared to add that at this time. The multipart reader allows you to access this data.
