### ISSUE TITLE
Exception: Correlation failed. Unknown location

### ISSUE THREAD

**Issue by hnviradiya** [aspnet/AspNetCore#7501]
### Describe the bug
When Hybrid Flow Authentication & Single Page Application combines. This error occurs. It redirects to identityserver & on callback this error is generated. Error is not on identityserver but on client project.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run following 2 projects 
https://github.com/hnviradiya/asp-net-core-vue-starter
https://github.com/IdentityServer/IdentityServer4

& click on Fetch Data. It will try to get authenticated ajax data & will redirect u to identityserver. on return (callback) this error will occur.

3. See error (In browser)

### Expected behavior
It should authenticate from oidc middleware & return single page application index.html file.

### Screenshots
![image](https://user-images.githubusercontent.com/12680915/52652789-c146ba00-2f14-11e9-8d32-0574744eb528.png)

### Additional context
Some discussion below:
https://github.com/SoftwareAteliers/asp-net-core-vue-starter/issues/6

Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by hnviradiya** [comment]
Side Note: If I define spa-fallback route, it is going there.

**Comment by rasitha1** [comment]
Are you changing the RedirectUri in Events.OnRedirectToIdentityProvider? (Or any other value in protocol message).

I ran into the same issue where I wanted to force lowercase on the redirect uri for my sub apps (i.e. localhost:44320/MyApp) where by default framework picks up the request URL and if a user types in "MYApp" that's what will end up in the RedirectUri and OP will reject that endpoint because of the case mismatch.

`ctx.ProtocolMessage.RedirectUri = ctx.ProtocolMessage.RedirectUri.ToLowerInvariant();`

Looking at the code, that a correlation value is calculated before Events are triggered and uses RedirectUri as part of the calculation. So then post correlation calculate will not match original value.

Is that a bug? I can open a separate issue if that's the case. My workaround for now is setup OP to only have https://localhost:44320 and any sub app works. However that's not ideal because there are other apps running under the same IIS site.

**Comment by Tratcher** [comment]
Sharing a Fiddler trace file is the quickest way to debug this scenario.

**Comment by hnviradiya** [comment]
PFA
[Hybrid-Authentication-SPA-Fiddler.zip](https://github.com/aspnet/AspNetCore/files/2858701/Hybrid-Authentication-SPA-Fiddler.zip)

**Comment by Tratcher** [comment]
@hnviradiya That trace does not contain any legible data. You need to enable "Decrypt HTTPS traffic" in the Fiddler HTTPS options.

**Comment by hnviradiya** [comment]
@Tratcher Updated one.
[Https Decrypted Hybrid Flow.zip](https://github.com/aspnet/AspNetCore/files/2865704/Https.Decrypted.Hybrid.Flow.zip)

**Comment by Tratcher** [comment]
Hmm, it's not the usual problem, the expected cookies are there. This method is returning false https://github.com/aspnet/AspNetCore/blob/0ec25d31670beb25d138578d71ddd14ad5197fe2/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L209. It has three possible reasons and they all generate unique logs. Turn on your logs to see which one it is.

Frame 16 confuses me, there's no State field in the initial auth challenge. I see you're generating that challenge manually, that may explain it.
https://github.com/hnviradiya/asp-net-core-vue-starter/blob/613a7f8296fa26259f393bb64c7616967bf6f450/Startup.cs#L85-L86
You're skipping this important step:
https://github.com/aspnet/AspNetCore/blob/0ec25d31670beb25d138578d71ddd14ad5197fe2/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L233

**Comment by hnviradiya** [comment]
**1) I think it is (below log) -> Logger.CorrelationPropertyNotFound(Options.CorrelationCookie.Name);**

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:44375/signin-oidc application/x-www-form-urlencoded 1247
warn: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[14]
      .AspNetCore.Correlation. state property not found.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[4]
      Error from RemoteAuthentication: Correlation failed..
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login. ---> System.Exception: Correlation failed.
```
**2)** 
Reason to generate manually is, it is giving 302 status code which axios is not able to handle (not redirecting entire page but just ajax call), so I had to tweak it. and at client side I have redirected manually if 401 is found.

3) **About** You're skipping this important step: **What I need to do?**

https://github.com/aspnet/AspNetCore/blob/0ec25d31670beb25d138578d71ddd14ad5197fe2/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L233

**Comment by Tratcher** [comment]
Ok, yes, the log does identify this as the issue. You need to include that Protect line in your OnRedirectToIdentityProvider function before calling CreateAuthenticationRequestUrl. The ProtocolMessage, Options, and AuthenticationProperties should all be on the context.

**Comment by Eilon** [comment]
Hi @hnviradiya we have determined that this isn't a bug in ASP.NET Core. This might now be a more suitable topic for a site such as StackOverflow where the broader community can try to provide this type of assistance.

**Comment by hnviradiya** [comment]
Similar issue. Just for reference.

https://github.com/aspnet/Security/issues/1173

**Comment by hnviradiya** [comment]
@Tratcher setting state property is not helping (previously it was null). it is still saying state not found.
```
AuthenticationProperties  properties = new AuthenticationProperties();
                                          properties.RedirectUri = redirectContext.ProtocolMessage.RedirectUri;
                    redirectContext.ProtocolMessage.State = options.StateDataFormat.Protect(properties);
```

**Comment by hnviradiya** [comment]
Never mind. following state led me one step ahead. but got another error. but now this error has been resolved.

redirectContext.ProtocolMessage.State = options.StateDataFormat.Protect(redirectContext.Properties);

**Comment by mayankgaur** [comment]
Hi @all anyone has find solution about this issue?

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
