### ISSUE TITLE
Release notes for 2.2.2

### ISSUE THREAD

**Issue by shapeh** [aspnet/AspNetCore#7502]
I see Asp.Net Core 2.2.2. is released (https://www.nuget.org/packages/Microsoft.AspNetCore.App/2.2.2) but I can't find the release notes.

Also, the roadmap has not been updated for ages (https://github.com/aspnet/AspNetCore/wiki/Roadmap).

**Comment by blowdart** [comment]
That's because it doesn't have release notes, it's a patch due to a .[NET Core update](https://github.com/dotnet/announcements/issues/97). This is why nuget versions aren't indicative of product releases.
