### ISSUE TITLE
Microsoft.SourceLink does not work with Razor components

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#7503]
Projects which use source link (https://github.com/dotnet/sourcelink) and Razor components fail to build with errors like:

```
CSC : error CS0016: Could not write to output file 'C:\src\aspnet\AspNetCore\src\Components\Blazor\testassets\StandaloneApp\obj\Debug\netstandard2.0\StandaloneApp.sourcelink.json' 
-- 'Could not find file 'C:\src\aspnet\AspNetCore\src\Components\Blazor\testassets\StandaloneApp\obj\Debug\netstandard2.0\StandaloneApp.sourcelink.json'.' [C:\src\aspnet\AspNetCore
\src\Components\Blazor\testassets\StandaloneApp\StandaloneApp.csproj]
```

This happens because the target which generates the source link file (GenerateSourceLinkFile) uses `BeforeTargets="CoreCompile"`. Razor components run the `Csc` task as a part of the RazorComponentGenerate target before `CoreCompile`, so sourcelink.json does not exist yet, and Csc will fail.

### Workaround

Add this to your .csproj file
```xml
  <!-- Workaround for target dependency order in Microsoft.NET.Sdk.Razor and Microsoft.SourceLink.Common -->
  <Target Name="_EnsureSourceLinkHappensBeforeRazorComponentGeneration" BeforeTargets="PrepareForRazorComponentGenerate" DependsOnTargets="GenerateSourceLinkFile" />
```

**Comment by mkArtakMSFT** [comment]
Thanks @natemcmaster.
@rynowak , can you please look into this? Feel free to reassign if you believe somebody will be able to handle this easily.

**Comment by pranavkm** [comment]
This was addressed in SourceLink as part of https://github.com/dotnet/sourcelink/pull/272. It sets the `SourceLink` path late enough for us to not run in to it during the initial codegen. We could consider cleaning up the target to not pass this value through during the declaration compilation: https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets#L247, but it doesn't seem pertinent at this point.
