### ISSUE TITLE
ASP.NET Core 2.1 - SPA Using Angular - Cannot access the client app when the App Pool does not allow 32-bit

### ISSUE THREAD

**Issue by GoFightNguyen** [aspnet/AspNetCore#7506]
### Describe the bug
I can invoke the Web API, but accessing the client app (SPA) returns the following error 
![cannotviewclientapp](https://user-images.githubusercontent.com/6308176/52664130-dd733880-2ecd-11e9-9dbc-df2cefe4c87e.PNG)

Here's the stdout log during this time
[stdout_while_unable_to_view_696_2019212142347.txt](https://github.com/aspnet/AspNetCore/files/2857454/stdout_while_unable_to_view_696_2019212142347.txt)

After setting the "Enable 32-Bit Applications" to true on the App Pool, I could successfully access both the client app and the Web API. Here's the stdout log during this time
[stdout_while_able_to_view_3532_2019212142826.txt](https://github.com/aspnet/AspNetCore/files/2857459/stdout_while_able_to_view_3532_2019212142826.txt)

### Expected behavior
I expected to successfully access both the Web API and the client app when "Enable 32-Bit Applications" was false on the App Pool.

### To Reproduce
1. Create an ASP.NET Core Web Application
   * ASP.NET Core 2.1
   * With Angular
   * With Web API
   * Active Solution Platform (TFS Build Configuration) = Any CPU
   * Startup.cs
```
public void ConfigureServices(IServiceCollection services)
{
    var cacheProfile = new CacheProfile()
    {
        Location = ResponseCacheLocation.None,
        NoStore = true
    };

    services.AddMvc(options => options.CacheProfiles.Add("NeverCache", cacheProfile))
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

    // In production, the Angular files will be served from this directory
    services.AddSpaStaticFiles(configuration =>
    {
        configuration.RootPath = "ClientApp/dist";
    });
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UsePathBase("/MyApp");

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
        app.UseHsts();
    }

    app.UseHttpsRedirection();
    app.UseStaticFiles();
    app.UseSpaStaticFiles();

    app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller}/{action=Index}/{id?}");
    });

    app.UseSpa(spa =>
    {
        // To learn more about options for serving an Angular SPA from ASP.NET Core,
        // see https://go.microsoft.com/fwlink/?linkid=864501

        spa.Options.SourcePath = "ClientApp";
    });
}
```
2. Host on Windows with IIS
   * App Pool
     * .NET CLR Version = No Managed Code
     * Enable 32-Bit Applications = False
     * Managed Pipeline Mode = Integrated
     * Identity = ApplicationPoolIdentity
   * App
     * Parent Site = Default Web Site
     * Physical Path = e:\inetpub\wwwroot\MyApp
     * Virtual Path = /MyApp
   * Generated web.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\myAssembly.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
</configuration>
```

### Additional context
Windows Server 2012 R2 Standard
64-bit OS, x64-based processor
IIS v8.5.9600.16384

The output of `dotnet --info`
> Host (useful for support):
>   Version: 2.1.6
>   Commit:  3f4f8eebd8
> 
> .NET Core SDKs installed:
>   No SDKs were found.
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GoFightNguyen.
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by GoFightNguyen** [comment]
This issue arose because of a project at work. The project has shifted away from ASP.NET Core, so I will not be active on this issue. You may close it if you no longer need it open

**Comment by ryanbrandenburg** [comment]
This seems to be the same thing as/related to https://github.com/aspnet/AspNetCore/issues/4206. Between that and the original filer no longer being active I'm closing this.
