### ISSUE TITLE
Blazor 0.8: can no longer mix refs and attributes in one element

### ISSUE THREAD

**Issue by chucker** [aspnet/AspNetCore#7509]
### Describe the bug
Blazor 0.8 appears to have a [new render tree builder](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/RenderTree/RenderTreeBuilder.cs) that is stricter.

In 0.7, this would work:

```csharp
<input type="text" data-slider-min="@Min" ref="@_Element" />

@functions {
    private ElementRef _Element;

    [Parameter] protected int Min { get; set; }
}
```

The intended usage here is that

1. `@Min` gets passed from the parent component, and
2. `@_Element` gets passed on to JS, hence the need for a ` ref`

However, in Blazor 0.8 (0.8.0-preview-19104-04 / 3.0.0-preview-19075-0444), this throws an `InvalidOperationException`:

>Attributes may only be added immediately after frames of type **Element** or **RenderTreeFrameType.Component**

It isn't clear if this is the intended behavior. The check appears overzealous in this case.

### To Reproduce
Just create a component as described above.

### Expected behavior
Blazor 0.8 should probably behave the same as 0.7 here, and allow a `ref` to be in the same element as a parameter value.

### Additional context
There's an easy workaround of putting the `ref` in a parent span:

```csharp
<span ref="@_Element">
    <input type="text" data-slider-min="@Min" />
</span>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chucker.
@SteveSandersonMS, can you please look into this? Thanks!

**Comment by Lupusa87** [comment]
This error is appearing when you try to add attribute after adding contnet.
 
I checked Index.cshtml.g.cs and it shows:   
```
protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
            builder.OpenElement(0, "input");
            builder.AddAttribute(1, "type", "text");
            builder.AddContent(2, Min);
            builder.AddAttribute(3, "data-slider-min", true);
            builder.AddElementReferenceCapture(4, (__value) => {
                                                _Element = __value;
            }
            );
            builder.CloseElement();
        }
```

this line should not be here
`builder.AddContent(2, Min);`

and 
`builder.AddAttribute(3, "data-slider-min", true);`
should be 
`builder.AddAttribute(3, "data-slider-min", Min);`

So it seems to be razor page parsing bug.

**Comment by mkArtakMSFT** [comment]
@danroth27 , @rynowak moving this to preview5, as we;re running out of time.

**Comment by rynowak** [comment]
Fixed by https://github.com/aspnet/AspNetCore-Tooling/pull/443

**Comment by fs86** [comment]
@rynowak This error does not only occur in conjunction with data attributes. Unfortunately I can not always repdoduce it. I noticed it when I added a simple component to a page. Is that known? Could you possibly make a statement about this?

**Comment by SteveSandersonMS** [comment]
@fs86 I'm only aware of it happening in conjunction with `data-*` attributes. If you're saying it happens in other cases we'd need a repro example (even if it only repros intermittently) otherwise I'm not sure how we could investigate. Hope that's OK!

**Comment by fs86** [comment]
@SteveSandersonMS Okay, I will try to create an example. Thank you for your response.

**Comment by fs86** [comment]
@SteveSandersonMS Okay, I created a test repo and then found out that I actually use a data attribute in one of my components :-) Sorry for the false report.
