### ISSUE TITLE
Add support for async to our Components E2E tests

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#7512]
When running the components E2E tests (I hit it easily in VS) it's possible to cause a thread-starvation deadlock on the selenium intialization.

Since we lock around the launch of selenium, ever test that starts has to take a lock - except the first thread to arrive that starts the server. Then it does a synchronous wait on the startup path because in a fixture you can only do synchronous work. This can deadlock because additional threads are required to unblock the `Task.Wait()`.

------

The best fix for this would be to make the initialization of the selenium/browser infrastructure async and make each test await it as its first statement.

There are a few other workarounds for this problem as well such as limiting the amount of concurrency for tests, or to do `task.Wait(...)` in a loop. 

I'm going to implement a really dumb workaround for now and we should monitor this to see if anything more robust needs to be done.

**Comment by danroth27** [comment]
We decided a solution to this would be pretty involved and isn't necessary.

**Comment by danroth27** [comment]
@javiercn
