### ISSUE TITLE
Is there a way to know why my client get the disconnected event frequently?

### ISSUE THREAD

**Issue by nkfeiyang** [aspnet/AspNetCore#7514]
I registered a HubConnection.StateChanged event, and I got the connection disconnected status time to time, but the server side looks good, no exception found at server side. I want to figure out why and what happened on my server or my client side.

Even if I run my client as same machine with the server side, I still get the disconnected event frequently.
Thanks a lot.

**Comment by davidfowl** [comment]
This issue belongs on https://github.com/SignalR/SignalR, and no there's no good way to know without looking at a network trace and/or the SignalR logs for that connection.

**Comment by Eilon** [comment]
This issue was moved to SignalR/SignalR#4306
