### ISSUE TITLE
Consider renaming ConfigureWebHost and ConfigureWebHostDefaults

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#7523]
Looking at the template now I wonder if we should name ConfigureWebHostDefault => ConfigureWebHost and ConfigureWebHost => ConfigureWebHostCore. I want to use the good name for the meta package and have some other name for the underlying API that isn't really usable without more dependencies (like an IServer). I'd like to get this done for preview3 but if we can't agree on some name then we can move it to preview4.

cc @Tratcher @glennc @muratg

**Comment by Tratcher** [comment]
https://github.com/aspnet/AspNetCore/blob/06d7fe73a995000ce79007e03785ee77d4dbb508/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/Program.cs#L21-L26

I like the current names, they're consistent and tell you you're getting a bundle of things.

**Comment by davidfowl** [comment]
I don't, should we bring in an unbiased 3rd party?

cc @DamianEdwards

**Comment by davidfowl** [comment]
To add to this, the thing that made me second guess the name was the fact that if you try to use it without calling adding a server throws, yet it's the most attractive name just doesn't work by default.

**Comment by davidfowl** [comment]
This isn’t a breaking change
