### ISSUE TITLE
Serving static files from wwwroot/dist 

### ISSUE THREAD

**Issue by rl6067** [aspnet/AspNetCore#7530]
I'm trying to add cache control headers to .js and .css files which live in wwwroot/dist. If I output my files directly into wwwroot rather than wwwroot/dist (from webpack) the headers are added without issue via the below code:

            app.UseStaticFiles(new StaticFileOptions
            {
                OnPrepareResponse = ctx =>
                {
                    const int durationInSeconds = 60 * 60 * 24 * 365;
                    ctx.Context.Response.Headers[HeaderNames.CacheControl] =
                        "public,max-age=" + durationInSeconds;
                }
        });
cache-control headers are also added to files contained in wwwroot/images, wwwroot/fonts and wwwroot/assets without any problems however this method seems to ignore the wwwroot/dist folder. Due to this I have added the following code directly below the code seen above:

         app.UseStaticFiles(new StaticFileOptions
        {
            FileProvider = new PhysicalFileProvider(
                Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "dist")),
            RequestPath = "/dist",
            OnPrepareResponse = ctx =>
            {
                const int durationInSeconds = 60 * 60 * 24 * 365;

                    ctx.Context.Response.Headers[HeaderNames.CacheControl] =
                        "public,max-age=" + durationInSeconds;  
            }
        });

The files do ideally need to be contained in the 'dist' folder as this is ignored in source control and the output files contain a hash so I can't feasibly manually add them to my git ignore.

Any advice on this issue would be greatly appreciated.

**Comment by Tratcher** [comment]
What other middleware do you have before this? Some add another instance of the StaticFiles middleware like the SpaServices components.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
