### ISSUE TITLE
[Question] How to realize File downloads in Razor Components

### ISSUE THREAD

**Issue by sven5** [aspnet/AspNetCore#7532]
Hi,

Is there any way to realize file downloads, e.g. a user clicks a button and the browser gets a file download prompt. 

Thanks
Sven

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sven5.
You can have a simple anchor element in your component, which will direct to a controller action, which will result in the file being returned in a specific way, as described https://stackoverflow.com/questions/9195304/how-to-use-content-disposition-for-force-a-file-to-download-to-the-hard-drive.

As for the link generation on the client, we don't have such a feature yet. It's something we're investigating: https://github.com/aspnet/AspNetCore/issues/7552

**Comment by sven5** [comment]
@mkArtakMSFT 
Thanks for your reply. I already thought that there is only this way at the moment and built a Controller action that returns the file. 

Best regards
Sven
