### ISSUE TITLE
[Question] How to naturally accept request with body as plain text?

### ISSUE THREAD

**Issue by crupest** [aspnet/AspNetCore#7533]
I want my controller to have an action that accepts text/plain body with the code below:

``` c#
[Route("[controller]")]
public class TestController : Controller
{
    [HttpPost("[action]")]
    [Consumes("text/plain")]
    public ActionResult<string> Test([FromBody] string content)
    {
        return Ok(content);
    }
}
```

But I failed with 415 response code.

After searching, I **guess** it is because the `FromBody` attribute.

And I try to add a so-called `StringInputFormatter` but only find `StringOutputFormatter`.

I have 3 question:
1. What is the actual reason why it fails?
2. Why is there no `StringInputFormatter`?
3. What is the recommended way to accept a plain text body?

Thanks a lot!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @crupest.
We don't currently have a `StringInputFormatter` in the framework. But it'll be straight forward to add. This one here is created for a test: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/test/WebSites/FormatterWebSite/StringInputFormatter.cs. You should be able to  adopt it with some minor tweaks.
