### ISSUE TITLE
How can I capture mouse event out of the component?

### ISSUE THREAD

**Issue by thainbreese** [aspnet/AspNetCore#7535]
In my component, I did some works on onmousemove event.
However, if I move mouse out of component, it messed up.
Maybe I think I need to do capture mouse event of body or document element.
Can I do this using js interop?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @thainbreese.
Here is a similar example you can look at: https://github.com/danroth27/RazorComponentDemos/blob/master/RazorComponentDemos.App/Pages/EventsAndBinding.cshtml#L5-L11
