### ISSUE TITLE
Change default for Razor Class Libraries to be component class libraries that work with client and server

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7536]
- Switch the Razor Class Library template to be setup for component development by default
- Surface a UI option in VS for this template to select support for components vs pages/views
- Remove the old blazorlib template

**Comment by javiercn** [comment]
@danroth27 any progress in here?
All runtime work is done already, other than switching the default.

https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/RazorClassLibrary-CSharp/.template.config/template.json#L56

**Comment by danroth27** [comment]
Related VS tracking issue: https://developercommunity.visualstudio.com/idea/575690/show-checkbox-option-for-aspnet-core-razor-class-l.html

**Comment by ryanbrandenburg** [comment]
What's the status on this? The issue you filed hasn't gone anywhere, so I assume it's blocked?

**Comment by danroth27** [comment]
The VS issue is no longer relevant. We can now surface UI for template options ourselves through template authoring like we are doing for the "hosted" option for the Blazor WebAssembly App template. So there should be nothing blocked here.
