### ISSUE TITLE
SignalR / Support ServiceWorkers

### ISSUE THREAD

**Issue by unsafecode** [aspnet/AspNetCore#7541]
### Is your feature request related to a problem? Please describe.
Looks like the SignalR Javascript bundle does NOT support ServiceWorkers, due to lacking of XMLHttpRequest object in SW scope.

### Describe the solution you'd like
Provide an additional HttpClient implementation that uses the `fetch` primitive instead.

### Describe alternatives you've considered
No alternatives :(

### Additional context
N/A

**Comment by bradygaster** [comment]
cc @davidfowl this seems similar to an issue @halter73 merged in #7058. Thoughts on this?

**Comment by davidfowl** [comment]
It’s not the same thing service workers an web workers are different and though there might be some overlap in the fixed I’m not sure this covers everything. It seems like we’ll need to switch to fetch when available as part of supporting service workers. 

I’m not 100% sure about using SignalR in service workers though @anurse did some investigation here

**Comment by unsafecode** [comment]
@bradygaster @davidfowl I made some changes and it works now. How can I submit a PR?

**Comment by davidfowl** [comment]
Sure that would be great!

**Comment by halter73** [comment]
> How can I submit a PR?

https://github.com/aspnet/AspNetCore/blob/master/CONTRIBUTING.md#submitting-a-pull-request

@unsafecode Thanks for looking into this. The reason we just added web worker support is because an external contribute submitted PR.

**Comment by unsafecode** [comment]
PR submitted at #7672

**Comment by davidfowl** [comment]
@unsafecode While the PR is good and we're likely going to merge it because fetch support is awesome (we punted it here https://github.com/aspnet/SignalR/issues/1240) but I don't understand the use case for signalr inside of a service worker? How do you plan to use it?

**Comment by unsafecode** [comment]
@davidfowl We're build an enterprise-wide PWA that:
1) Uses Saga-based distributed transactions on microservices-oriented application, so we needed a way to notify the client when operations actually complete
2) We wanted to re-use the same approach to send "push notification" without WebPush. And SignalR in SW enables to trigger Notifications.

**Comment by davidfowl** [comment]
Can you describe how SignalR fits in? Doesn't the service worker die on idle? Isn't the point to avoid a long running connection in the first place? Service Workers are about intermittent connectivity while SignalR/WebSockets are about long running connections. Here's a quote from one of the many blog posts on this topic:

> So, while WebSockets and Service Workers kind of overlap, both being used for client-server communications, WebSockets would be used more for continuous communication so both the client and the server can send messages to each other without having to create new connections, and Service Workers would be used more for one-off client-server communications like syncing an app and the database after the app was offline for some time, like a burst that can then be dropped when the sync is completed

**Comment by brazierdavid** [comment]
> Doesn't the service worker die on idle? 

Yes, that does seem to make it pointless to run SignalR in a service worker.  In the scenario for the server to push notifications even when the web app isn't active, service workers have a role using Web Push API (e.g. [Push Notifications and ASP.NET Core](https://www.tpeczek.com/2017/12/push-notifications-and-aspnet-core-part.html)) but @unsafecode why don't you want to do it that way?

**Comment by anurse** [comment]
We don't believe there's a scenario for SignalR in service workers right now.
