### ISSUE TITLE
Upgrade IIS C++ projects to build with platformtoolset v142 (VS2019)

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#7548]
Depends on https://github.com/aspnet/AspNetCore/pull/7005

Let's update the C++ projects for ANCM to build with the Visual Studio 2019 toolset. This should be a matter of updating the .vcxproj and reacting to any warnings or errors the new toolset finds.
```
<PlatformToolset>v142</PlatformToolset>
```

**Comment by anurse** [comment]
Looks like there are a few still using `v141` (https://github.com/aspnet/AspNetCore/search?q=PlatformToolset%3Ev141&unscoped_q=PlatformToolset%3Ev141). @jkotalik do you know off-hand if there's a reason for this?

Everything else appears to be on `v142`

**Comment by jkotalik** [comment]
They are part of IIS Setup (a repo we source copied). I think I can update them without any problem.

**Comment by anurse** [comment]
Certainly worth a try. I'll put it in preview 6 since it shouldn't impact customer experience.

**Comment by anurse** [comment]
Re-opening this. We still have some projects using 141. I do think we can punt this out a bit though since I don't know that there's a pressing reason to update.

**Comment by anurse** [comment]
Stumped again. See some notes in the linked PR (#10093).

**Comment by anurse** [comment]
We don't expect to be able to resolve this in 3.0. We're getting strange issues (see linked PRs) and there isn't a customer motivated scenario that I'm aware of. We can revisit later as necessary.

**Comment by natemcmaster** [comment]
So, keep open but backlog?

This is the only reason, by the way, that we can't use Azure-hosted build queues for VS2019 instead of ones dnceng maintains.

**Comment by anurse** [comment]
> This is the only reason, by the way, that we can't use Azure-hosted build queues for VS2019 instead of ones dnceng maintains.

This is helpful additional context. Given that I'm fine to put this in to try and get for 3.0. I wasn't aware of what this was actually blocking.

**Comment by natemcmaster** [comment]
It's a "nice to have", so it's ok if this doesn't fit in 3.0. Some c++ projects in the repo are using the VS 2019 toolset already. While they're is nothing technically wrong with using both the VS 2017 and 2019 toolsets, I think keeping our code consistent and using latest tools are good clean-code practices.

**Comment by anurse** [comment]
It's still very nice to be on the hosted agents, and the consistency argument is one I definitely buy. We'll look at this in preview 8. I think it's really just about figuring out what mysterious MSBuild property is "resetting" the toolset version when building `iisca.vcxproj` (see https://github.com/aspnet/AspNetCore/pull/10093#issuecomment-490739435). It only seems to fail on CI though, so it may be a problem with the agent config. If this is the only thing stopping us from using hosted agents, maybe if we switch to those in the same PR things will work?

We'd also need to verify the official build before merging (in case those agents are also affected by whatever config is causing the failures in PR).

**Comment by natemcmaster** [comment]
https://github.com/aspnet/AspNetCore/blob/214ca07b6c1efd48abd07ec10c50db9a6a4b830d/eng/Workarounds.props#L16-L19

**Comment by anurse** [comment]
So do we need to remove that now? The devcommunity link seems to indicate that it's fixed.

**Comment by natemcmaster** [comment]
Yeah, if they fixed the issue in VS, let’s remove the workaround.
