### ISSUE TITLE
Upgrade SignalR C++ client to build with platformtoolset v142 (VS2019)

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#7549]
Depends on https://github.com/aspnet/AspNetCore/pull/7005
Blocked on https://github.com/Microsoft/cpprestsdk/issues/1039

Let's update the SignalR C++ client to build with the Visual Studio 2019 toolset. This should be a matter of updating the .vcxproj and reacting to any warnings or errors the new toolset finds.
```
<PlatformToolset>v142</PlatformToolset>
```

**Comment by muratg** [comment]
We'll see if we will need to do this or not.

**Comment by muratg** [comment]
Still blocked, because CppRestSDK can't build with v142 toolset.

**Comment by wegylexy** [comment]
VS2019 is still in preview. Shouldn't let it block SignalR Core 3.0

**Comment by petke** [comment]
Hi. What is the status here? I dont see any cpprestsdk.v142 nuget package.

**Comment by BrennanConroy** [comment]
We don't build the client with an explicit vcxproj anymore
