### ISSUE TITLE
connection.onclose() does not get called on disconnect

### ISSUE THREAD

**Issue by bigswede74** [aspnet/AspNetCore#7557]
### Describe the bug
connection.onclose() gets called after reconnect

### To Reproduce
1. Using this version of signalr client - signalr-client-1.0.0-alpha2-final
2. Disconnect the client by disconnecting the network cable and observe that connection.onclose() is not called
3. Reconnect the client by reconnecting the network cable and observe that connection.onclose is called

### Expected behavior
Shouldn't connection.onclose() be called when the disconnect happens?

### Additional context
I know this is the alpha2 final client but its already deployed and we are seeing this behavior

**Comment by BrennanConroy** [comment]
Sorry, but that client is unsupported.

We're not going to diagnose a problem that is very likely solved in the shipped product.

Try upgrading to at least 1.0.0.

**Comment by muratg** [comment]
@bigswede74 Let us know if you still have an issue when you upgrade to a supported client. Thanks!
