### ISSUE TITLE
input for checkbox always false

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7560]
_From @drowhunter on Saturday, 26 January 2019 23:32:58_

# General

I just spent two days trying to figure out why this is not working
```
    <form method="post" asp-page-handler="Callback" class="consent-form">
        <input asp-for="ViewModel.UserCode" type="hidden" value="@Model.ViewModel.UserCode" />
            <label>
                <input class="consent-scopecheck" asp-for="ViewModel.RememberConsent" />
                <strong>Remember My Decision</strong>
            </label>                          
            <button name="Button" value="yes" class="btn btn-primary" autofocus>Push</button>
    </form>
```
On Post value of check box is always false, and the user code is null
![wrongvalues](https://user-images.githubusercontent.com/2817488/51794044-7dc02200-2198-11e9-9fad-b279115cca66.png)
but if you look at the request the values are there
![requestform](https://user-images.githubusercontent.com/2817488/51794052-b19b4780-2198-11e9-88f0-e8616fab9511.png)

my code is below

 ```
public DeviceAuthorizationViewModel ViewModel { get; set; }

public async Task<IActionResult> OnPostCallbackAsync(DeviceAuthorizationInputModel model)
 {
            if (model == null) throw new ArgumentNullException(nameof(model));
           // code removed...
}
        
``` 

My model
```
public class DeviceAuthorizationViewModel
    {
        public string UserCode { get; set; }
        public string Button { get; set; }
        public IEnumerable<string> ScopesConsented { get; set; }
        public bool RememberConsent { get; set; }
        public string ReturnUrl { get; set; }
    }
```

_Copied from original issue: dotnet/core#2258_

**Comment by danroth27** [comment]
_From @leecow on Thursday, 14 February 2019 00:51:09_

@muratg - can you have a look and redirect if necessary?

**Comment by danroth27** [comment]
_From @muratg on Thursday, 14 February 2019 01:27:20_

cc @mkartakmsft, @danroth27

**Comment by danroth27** [comment]
_From @drowhunter on Thursday, 14 February 2019 01:33:10_

Just to be clear, in order to work around this issue, I had to go into the Request.Forms Items and select the first value from the `RememberConsent` Array.  And Grab the value for UserCode myself. 

Something is not right with the PageModelBinder or something

**Comment by owk** [comment]
+1, I'm having the same issue where a bool is always false. In the headers I'm seeing the value being posted twice (true and false), and in Request.Forms it has both values as well...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @drowhunter.
@javiercn can you please investigate this? Thanks!

**Comment by SteveSandersonMS** [comment]
This isn't components - changed the label to `feature-Razor-Pages`.

**Comment by javiercn** [comment]
I can repro this

![image](https://user-images.githubusercontent.com/6995051/56751082-03bd1c00-673a-11e9-9d5a-9784aba09912.png)

**Comment by javiercn** [comment]
Found hte issue. This is not a bug. You are trying to bind against the ViewModel property but the ViewModel property is not marked with Bind.

If you want to bind to a custom input model, you either need a separate property or you can't use asp-for. You can explicitly provide the name attribute to override the generated value and make the form bind correctly as follows:

```razor
<form method="post" asp-page-handler="Callback" class="consent-form">
    <input asp-for="ViewModel.UserCode" name="UserCode" type="hidden" value="@Model.ViewModel.UserCode" />
    <label>
        <input class="consent-scopecheck" name="RememberConsent" asp-for="ViewModel.RememberConsent" />
        <strong>Remember My Decision</strong>
    </label>
    <button name="Button" value="yes" class="btn btn-primary" autofocus>Push</button>
</form>
```
