### ISSUE TITLE
Question: Why is the set accessor of RoleManager.Store private but the set accessor of UserManager.Store is not?

### ISSUE THREAD

**Issue by LiangZugeng** [aspnet/AspNetCore#7562]
It's a question, when reviewing the RoleManager and UserManager, I found the Store properties of the two classes are designed differently.

```
protected IRoleStore<TRole> Store { get; private set; }
```

```
protected internal IUserStore<TUser> Store { get; set; }
```

1. RoleManager.Store has a private set accessor but UserManager.Store has a normal set accessor.
2. RoleManager.Store has no internal decorator but UserManager.Store has.

Can anyone clarify this a little bit? Is this an intended design or just a careless mistake.

We would prefer both the Store properties in the two classes have normal set accessors so we can change them in derived classes and have no internal decorators.

**Comment by HaoK** [comment]
The store should be passed into the ctor which sets its, the latter accessor is different due to unit tests setting the store.  In general it should be treated as a private setter

**Comment by LiangZugeng** [comment]
@HaoK thanks for the details. This question is closed.
