### ISSUE TITLE
Build using yarn instead of npm

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#7563]
`npm install` feels horribly slow when building this repo. Yarn seems to use caches much better, at least 4x better on my machines, sometimes more. Prototype: https://github.com/aspnet/AspNetCore/compare/master...natemcmaster:yarn

Ran some experiments comparing "yarn install" and "npm install". They perform about the same on a cold machine (varies widely based on network conditions). But on a warm machine, the inner dev loop using `build.cmd` is much better.

Average of 5 iterations on warm machine

PC | `yarn install` | `npm install`
---|---|--
macOS | 12s | 229s
Windows 10 | 15s | 57s

Thoughts @BrennanConroy @anurse @pranavkm  ?

**Comment by pranavkm** [comment]
@SteveSandersonMS \ @javiercn thoughts? Cursory reading does suggest that yarn's faster - https://www.keycdn.com/blog/npm-vs-yarn - but I'm not sure if there are drawbacks of using it.

**Comment by javiercn** [comment]
@pranavkm Yarn is FBs response to some issues with npm. I belive they are both technically equivalent, but I don't know if we would be loosing things like npm audit. Which might be a considerable drawback

**Comment by SteveSandersonMS** [comment]
Try using “npm ci” instead of “npm install” and see if the speed is adequate. 

It will keep things simpler for ourselves and contributors if we can avoid requiring installation of extra nonstandard tools where possible.

**Comment by natemcmaster** [comment]
Ran the same experiment with npm ci. It's the slowest of the 3 options. It's especially bad on macOS because it doesn't cache the result of compiling modules that have C++.


Average of 5 iterations on warm machine

PC | `yarn install` | `npm install` | `npm ci`
---|---|--|--
macOS | 12s | 229s | 390s
Windows 10 | 15s | 57s | 93s

The only contributors who would need to install yarn are those making changes to our node projects. `build.cmd` will take care of acquiring yarn for everyone else. 

I'm totally fine giving up on npm. On a warm machine/repo, `npm install` on 8 npm projects is slower than `dotnet restore` on hundreds of C# projects.

**Comment by natemcmaster** [comment]
> I don't know if we would be loosing things like npm audit

`yarn audit` :) Also, Doug enabled an internal Microsoft thing yesterday which audits our dependencies regularly, and it supports yarn: https://docs.opensource.microsoft.com/tools/cg.html

**Comment by muratg** [comment]
@anurse thoughts?

**Comment by anurse** [comment]
Yarn it up. I don't see any missing functionality and I think it's worth the extra install.

![Yoshi's Wooly World](https://thumbs.gfycat.com/SoupyQueasyAddax-size_restricted.gif)
