### ISSUE TITLE
Route Templates for HttpClient

### ISSUE THREAD

**Issue by koenigst** [aspnet/AspNetCore#7564]
### Issue
We are currently building a suite of applications using the microservice design-pattern. One of our big pain-points and a frequent source of errors is building the URLs to access resources on other microservices.

### Desired Solution
ASP.NET Core route templates would offer a powerful and well-known syntax for generating URLs. I would like to have a simple solution for creating URLs from route templates and be able to use them together with `HttpClient` for accessing ASP.NET Core APIs. This could look like:

```csharp
var uri = RouteBuilder.FromTemplate("/api/{id}").With("id", 1).BuildUri();
httpClient.GetAsync(uri);
```

My preferred solution would be to have a `Microsoft.Extensions.*` package that contains the route template logic, including URL matching and generating.

### Alternatives
* `LinkGenerator` already has similar capabilities but it is designed to work for the Web-API being served and not for different Web-API being accessed via HTTP.
* It is quite simple to build a custom implementation of this using `TemplateParser` and `TemplateBinder` **but** those types require "pubternal" types (e.g. `UriBuildingContext`), which means the custom implementation could break at any time.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @koenigst.
@rynowak any suggestions here?

**Comment by mkArtakMSFT** [comment]
@koenigst rather than manually constructing URLs manually, you should consider generating a client based on the swagger document of your service and then just calling methods passing proper parameters to them. This is an area we're making active improvements and things will get even simpler in the near future: https://github.com/aspnet/AspNetCore/issues/4896
