### ISSUE TITLE
*.Views.dll not in AppDomain.CurrentDomain.GetAssemblies()

### ISSUE THREAD

**Issue by yuessir** [aspnet/AspNetCore#7567]
### Describe the bug
Creating a new .Net Core 2.2 MVC project.
Why *.Views.dll not in AppDomain.CurrentDomain.GetAssemblies()??

### To Reproduce
1. Using this version of ASP.NET Core '...'
V 2.2
2. Run this code '....'
Using  `AppDomain.CurrentDomain.GetAssemblies() `
3. With these arguments '....'

### Expected behavior
I thought the **ProjectNmae.View.dll** should place in AppDomain.
Is this a misunderstanding??  ="{

### Screenshots
![1](https://user-images.githubusercontent.com/8326310/52777083-f91d4100-307d-11e9-9edb-66fec20fac25.PNG)

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @yuessir.
We load these generated View assemblies at runtime.
