### ISSUE TITLE
[Components] Correct some the `[EventHandler]` entries on EventHandlers.cs that are incorrect.

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#7570]
Some of the `[EventHandler]` entries starting at https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/EventHandlers.cs#L72 are incorrect, because they lack the necessary `on` prefix from the event name. This means you can't register pointer events from normal Razor code and have to register them on the `RenderTreeBuilder` directly using a render fragment as a workaround.

**Comment by rynowak** [comment]
This sounds like a good thing to fix.
