### ISSUE TITLE
How can I get mouse move event of document in blazor?

### ISSUE THREAD

**Issue by wmqsoft** [aspnet/AspNetCore#7571]
I tried to capture mouse move event of document in blazor using js interop.

```
window.vGridServices = {
    example: function () {
        document.addEventListener("mousemove", function (e) {
            console.log('mousemove');
        });
    }
};
```

If I invoke the example function, the console.log displays mousemove when I am moving mouse cursor.
However, I want to return the mouse position to c# code.
How can I do this?

**Comment by enetstudio** [comment]
You can pass the mouse position to a Blazor method using jsinterop. See here how to do it: https://blogs.msdn.microsoft.com/webdev/2018/07/25/blazor-0-5-0-experimental-release-now-available/

But why won't you use native Blazor mousemove event to get the same result ?

Note: If you wish a detailed answer for your question, you may move your question to stackoverflow, as this question is not really an issue but a plain tutorial one...

Hope this helps...

**Comment by Lupusa87** [comment]
You have two options:
1. Have static c# class with JSinvokable method and invoke it from js event, c# side your static class can have public action/event which will be invoked from jsinvokable method, than subscribe for it whenever you need;
usage example [here](https://github.com/Lupusa87/BlazorWindowHelper/blob/master/content/BWHJsInterop.js#L8) and [here](https://github.com/Lupusa87/BlazorWindowHelper/blob/master/BlazorWindowHelper.cs#L23)

2. You can pass DotNetObjectRef parameter to your example function and invoke it from js event.
DotNetObjectRef is reference to your class instance, you will have JSinvokable method there too, which will be called from JS.
usage examples [here](https://github.com/Lupusa87/BlazorScrollbar/blob/master/BlazorScrollbarComponent/content/BsbJsInterop.js#L55) and [here](https://github.com/Lupusa87/BlazorScrollbar/blob/master/BlazorScrollbarComponent/BsbJsInterop.cs#L17) and [here](https://github.com/Lupusa87/BlazorScrollbar/blob/master/BlazorScrollbarComponent/CompThumb.cs#L51)

Good luck :)
