### ISSUE TITLE
[Hosted Blazor] UriHelper.GetBase() or URL routing behaves differently in 0.8

### ISSUE THREAD

**Issue by chucker** [aspnet/AspNetCore#7575]
### Describe the bug
Upgrading to Blazor 0.8 broke the Web API routing in my hosted Blazor project.

In Blazor 0.7, I could use this to make a Web API call:

```csharp
var apiRoot = uriHelper.GetBaseUri() + "/api";
var json = await client.GetStringAsync($"{apiRoot}/…some API route…}");
```

In Blazor 0.8, this fails. Upon further investigation, it appears that:

* `apiRoot` contains two slashes (e.g. `http://someHost/MyBlazorProject//api`, and
* that double slash appears to lead Blazor routing to take precedence over Web API, thus causing the `GetStringAsync` request to incorrectly load the Blazor site.

Either the behavior of `GetBaseUri()` changed to add a trailing `/` when it didn't before, or that slash was always there, and the routing behavior instead changed to make Web API no longer work with a redundant slash.

### Workaround

I can simply remove a slash to fix it:

```csharp
var apiRoot = uriHelper.GetBaseUri() + "api";
var json = await client.GetStringAsync($"{apiRoot}/…some API route…}");
```

However, since it's not clear if this behavior change was intended, I figured I'd file a bug regardless.

**Comment by enetstudio** [comment]
This behavior is by design:
`
/// <summary>
        /// Gets the base URI (with trailing slash) that can be prepended before relative URI paths to
        /// produce an absolute URI. Typically this corresponds to the 'href' attribute on the
        /// document's &lt;base&gt; element.
        /// </summary>
        /// <returns>The URI prefix, which has a trailing slash.</returns>
        public virtual string GetBaseUri()
        {
            EnsureInitialized();
            return _baseUriString;
        } 
`
