### ISSUE TITLE
[Razor Tooling] Remove TypeForwarded TagHelper services from MS.VS.Editor.Razor.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#7587]
@alexgav @ToddGrun I recently moved our TagHelper services from the editor.razor dll to the CodeANalysis.Razor.Workspaces dll. We're type forwarding all the types so you wont have any issues but at some point in the future we should do a coordinated insertion to change your references.

PR in question: https://github.com/aspnet/AspNetCore-Tooling/pull/211

**Comment by rynowak** [comment]
Why would we do anything to follow up on this ever??? TypeForwards are **free** and they work forever. If you want to remove them in 2 years we can.

**Comment by NTaylorMullen** [comment]
Will never do this
