### ISSUE TITLE
Why is the NotAuthenticatedWithFailure message logged as INFO, not ERROR?

### ISSUE THREAD

**Issue by kevinlo** [aspnet/AspNetCore#7592]
Usually, we search log file for ERROR or WARNING whenever it has issues.  It happens sometimes I see no ERROR in the log but my application has issue because the data protection key is messed up.

Why is the NotAuthenticatedWithFailure messaged be logged as INFO, not ERROR or WARNING?

> 2019-02-14 11:40:07,711 -08:00 INFO  [CookieAuthenticationHandler] MyApp.Cookies.Auth was not authenticated. Failure message: Unprotect ticket failed [0HLKIM6U10MO2:00000003 44600:106] 

Should this [line ](https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authentication/LoggingExtensions.cs#L41) use LogLevel.Error or LogLevel.Warning like this?

```
            _authSchemeNotAuthenticatedWithFailure = LoggerMessage.Define<string, string>(
                eventId: 7,
                logLevel: LogLevel.Error,
                formatString: "{AuthenticationScheme} was not authenticated. Failure message: {FailureMessage}");
```

**Comment by Eilon** [comment]
Hi @kevinlo , we use the following definitions for log levels: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=aspnetcore-2.2

So, the ERROR level is reserved for events where the execution of the request must stop. The INFO level is used for items that are interesting to see in logs and that an app might want to monitor.
