### ISSUE TITLE
Don't register @model and other unsupported directives for component apps

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#7601]
Follow up to https://github.com/aspnet/AspNetCore/issues/7384

`@model` is currently being treated as a directive in component apps. This shouldn't be registered as a directive because component apps don't recognize it.

@rynowak

**Comment by rynowak** [comment]
@ajaybhargavb - is this still the case? I thought you had fixed this?

**Comment by ajaybhargavb** [comment]
Oh yeah I did this as part of https://github.com/aspnet/AspNetCore-Tooling/pull/357.
