### ISSUE TITLE
LongPollingTransportOnReceiveGetsCalledMultipleTimes failed

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#7602]
Ran into this in a local build:
`expected: <FIRSTSECOND> but was: <SECOND>`

**Comment by muratg** [comment]
I wonder why RAAS did not file it. It would be weird if it's passing in CI but failing locally. (Reverse is more common! :smile:)

**Comment by BrennanConroy** [comment]
That's flaky for you :D

**Comment by mikaelm12** [comment]
Took a look. Ran it in a loop and was able to repro this. I figured out why the test was failing but we might actually want to add product code to ensure that messages are processed in the correct.
