### ISSUE TITLE
API Proposal: Exposing the upgraded stream as an IDuplexPipe

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#7604]
Epic https://github.com/aspnet/AspNetCore/issues/8829

Right now, the IHttpUpgradeFeature returns a Stream from UpgradeAsync: https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Features/src/IHttpUpgradeFeature.cs#L22. This can be extended to return an IDuplexPipe.

```C#
public interface IHttpUpgradeFeature
{
   Task<IDuplexPipe> UpgradePipeAsync();
}
```

**Comment by davidfowl** [comment]
Note: As it currently stands this is a breaking change for anyone that implemented this interface.

**Comment by anurse** [comment]
We need to resolve the corefx stuff before we can close on this. If that happens in time, let's do it.

**Comment by anurse** [comment]
Closing, as we aren't going to align the corefx stuff for 3.0. We have the following options moving forward:

* Add new `IHttpUpgradePipeFeature`
* If corefx unifies Stream and Pipe, the existing feature can be used.
