### ISSUE TITLE
Redirection Error by using OpenId Connect behind a reverse proxy 

### ISSUE THREAD

**Issue by Kalimshan** [aspnet/AspNetCore#7607]
Hello,

I'm using an OpenId Connect Authentication (with office365) in ASP.NET Core 2. Like this issue (https://github.com/aspnet/Security/issues/1508) on my production server, I’m using a reverse proxy.

https://myserserverintranet.domain.org/area/controler/index -->
https://myserserverinternet.domain.org/asp/area/controler/index

In my apache config of the internet server I have:

ProxyPass /asp/ https://myserserverintranet.domain.org/
ProxyPassReverse /asp/  https://myserserverintranet.domain.org/

The url response in my Administration Center of Azure Active Directory, I have this url 
https://myserserverinternet.domain.org/asp/signin-oidc

I’ve got this error : 

> Message: AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '01f94ad6-9e05-4217-bdbf-b0dc3644bf64'. 

I corrected by intercepting the event « OnRedirectToIdentityProvider »

```
public void ConfigureServices(IServiceCollection services)
{
   .AddOpenIdConnect(opts =>
   {
        Configuration.GetSection("Authentication").Bind(opts);
        opts.Events.OnRedirectToIdentityProvider = async context =>
        {
            context.ProtocolMessage.RedirectUri = "https://myserserverinternet/asp/signin-oidc";
            await Task.FromResult(0);
        };
        opts.CallbackPath = new PathString("/asp/area/controler/index");
        opts.AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet;
        opts.ResponseMode = "form_post";
        opts.ResponseType = "id_token";
        opts.TokenValidationParameters = new TokenValidationParameters
        {
           NameClaimType = "name",
           RoleClaimType = "role"
        };
   
        opts.RequireHttpsMetadata = false;
   });

   services.Configure<ForwardedHeadersOptions>(options =>
   {
     options.ForwardedHeaders =
                   ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
   });

```
Unfortunately now I get a 404 error, 

I do not see what I did wrong and I despair of finding a solution. If anyone has an idea, 
I'll take it.

Thank you all for your attention to this issue.

**Comment by blowdart** [comment]
First thing to check is if the ForwardedHeaders.XForwardedFor and ForwardedHeaders.XForwardedProto headers are being sent by the proxy.

However I have another question, why go the OIDC route and not the specific [app.UseAzureAD](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore) pieces?

**Comment by Tratcher** [comment]
- Do not override OnRedirectToIdentityProvider for this scenario.
- CallbackPath should not point to a controller, it should be a unique endpoint used by the auth handler like the default "/signin-oidc".
- Call UsePathBase to trim request path prefixes like "/asp"
- Follow these troubleshooting instructions and share the output: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#troubleshoot

**Comment by Kalimshan** [comment]
Hello

Before following the troobleshooting above, I deleted the override OnRedirectToIdentityProvider and finaly I solved my problem by forcing the host.
Unfortunately,Apache does not seem to follow the ForwardedHeaders.XForwardedFor and ForwardedHeaders.XforwardedProto.

```
app.Use((context, next) =>
{
       context.Request.PathBase = new PathString("/asp");
       context.Request.Host = new HostString("myserserverinternet.domain.org");
       return next();
});
```
So, I did not need to specify the KnownProxies.

**Comment by ansongoldade** [comment]
I solved this by adding `XForwardedHost` to the forwarded headers.

```
services.Configure<ForwardedHeadersOptions>(options =>
{
  options.ForwardedHeaders = ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedHost;
  // Only loopback proxies are allowed by default. Clear that restriction because forwarders are
  // being enabled by explicit configuration.
  options.KnownNetworks.Clear();
  options.KnownProxies.Clear();
});
```

We don't have a need for the `X-Forwarded-For` value and there seemed to be an issue when that was included and we were integrating with an OIDC provider. Didn't dig into that issue. Anyway, just wanted to share in case it's of assistance to anyone else.
