### ISSUE TITLE
MapControllerRoute doesn't return an endpoint convention builder

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#7611]
@rynowak 

Looking through the updated MVC endpoint startup extension methods I noticed `MapControllerRoute` doesn't return a convention builder: 
https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/Builder/ControllerEndpointRouteBuilderExtensions.cs#L82-L88

Also `MapDefaultControllerRoute` looks like it returns a convention builder that would apply metadata to all routes in the datasource:
https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/Builder/ControllerEndpointRouteBuilderExtensions.cs#L51-L59

I would expect to be able to define a route to controller's and then apply metadata to just that route. For example:

```
routes.MapDefaultControllerRoute();
routes.MapControllerRoute("AdminSection", "admin/{controller=Admin}/{action}").RequiresAuthorization("Admin");
```

**Comment by rynowak** [comment]
This was intentionally cut from the experience. The folks I dicussed it with don't think people will do it. MVC already has two alternative ways of configuring metadata.
