### ISSUE TITLE
Under some edge-case circumstances, SignalR will stop processing DOM Updates for all sessions in Blazor (0.7.0) under ASP.NET Core (2.1) when encountering an runtime exception.

### ISSUE THREAD

**Issue by honkmother** [aspnet/AspNetCore#7613]
### Describe the bug
I am using Blazor 0.7.0 and ASP.NET Core 2.1, my apologies if this has already been flagged or fixed.
Additionally I am using Kestrel by itself without an additional web-server in front of it.

When using server-side Blazor, if you stack dictionaries inline inside of a component to perform a key lookup and encounter a Dictionary KeyNotFoundException on the parent, SignalR will have a nervous breakdown and stop processing updates for ALL active and new sessions. 

Kestrel itself does not hang but issues heartbeat warnings after some period of time and eventually after a long time SignalR resumes functioning correctly.

The behavior was completely resolved by using ContainsKey prior to the lookup. I don't know if this is the case with other exception types.

### To Reproduce
e.g  `<img src="http://s3.amazonaws.com/static-images/@(imageLookup[languageTable["en"].Agency])" />`

### Expected behavior

I expected an exception to be thrown and potentially affect the current session in some way, however it affects ALL SignalR sessions across the process and completely prevents any DOM updates from being issued.

**Comment by rynowak** [comment]
This seems like this has been fixed. 

If you hit this during prerendering, then the developer exception page will show the exception.

When I try your sample without prerendering, this will throw an exception - which is logged to the client console, and then disconnect the client.

We're looking to make error handling better in general in the future, but for now this is what's expected when rendering throws.
