### ISSUE TITLE
Hostable bundle installer IIS Restart question

### ISSUE THREAD

**Issue by WalterEbbers** [aspnet/AspNetCore#7615]
Hi,

I have a question regarding the hosting bundle installer and something i read within the [**docs**](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?tabs=aspnetcore2x&view=aspnetcore-2.2).

Within the chapter [**Install the Hosting Bundle**](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?tabs=aspnetcore2x&view=aspnetcore-2.2#install-the-hosting-bundle) it is stated that when the installer detects a IIS reset is required it will do a reset. 

1. How does this detection work?
2. Does the /norestart switch prevent a IIS restart when installing the hosting bundle?
    - If not=> Is there a switch available that prevents a IIS restart?

I'm asking this because we have certain customers that have different applications running within IIS and it is not desirable that IIS is restarted while other hosted applications are still in use.

**Comment by muratg** [comment]
This is a doc bug. We do not run iisreset

**Comment by WalterEbbers** [comment]
@muratg  Thnx! so this means after install the user must manually reset iis to make it pickup the changes? 
That would be very nice!
