### ISSUE TITLE
Long-lived singleton

### ISSUE THREAD

**Issue by krumal** [aspnet/AspNetCore#7616]
When i use singleton in DI
`
services.AddSingleton<IService, Service>();
`
after some time i get dispose creating singleton
How to make the singleton available at all times during my webserver is running?

net core 2.2, iis 10
Thanks.

**Comment by davidfowl** [comment]
It'll get disposed when the entire application is torn down, not before. That's about as long lived as it gets. What exactly are you seeing?

**Comment by krumal** [comment]
I think I understand. Iis torn down my app. How to disable it?

**Comment by davidfowl** [comment]
Something like this https://stackoverflow.com/questions/35993968/how-to-prevent-iis-from-shutting-down-web-site-when-not-in-use

**Comment by krumal** [comment]
Thanks!
