### ISSUE TITLE
Can an ASP.NET Core app run against the .NET Framework runtime?

### ISSUE THREAD

**Issue by GoFightNguyen** [aspnet/AspNetCore#7617]
There are many enjoyable things about developing an ASP.NET Core application, this includes, but is not limited to:
 
- SPA support
- ease of testing
- separation of concerns
- middleware configuration
- dependency inversion/injection
- tooling
 
It feels like modern web app development.
 
I am creating a web application that will include an Angular SPA and Web API. Unfortunately, my organization will not allow ASP.NET Core deployments for the foreseeable future; **all software must run against the .NET Framework runtime.**
 
What can I do now to satisfy the organizational requirement of the .NET Framework runtime, while still having a great development experience and using the first-class constructs of ASP.NET Core?
 
Through some research, I came across two items that might help:
 
1. the Microsoft.AspNetCore.App and Microsoft.AspNetCore.All metapackages actually encapsulate netstandard packages such as Microsoft.AspNetCore.
2. The csproj can be edited to target net471
 
Here is what I am considering.
 
1. In the csproj, replace the netcore target with net471
2. Remove the dependency upon Microsoft.AspNetCore.App
3. Add dependencies to the netstandard versions of the packages needed such as Microsoft.AspNetCore
4. Host in IIS with an Application Pool configured with a .NET CLR Version belonging to .NET Framework instead of `No Managed Code`
 
Do you see any issues or have any concerns? Even if this is possible, is this something I **should** do?

Here are some questions I had, please answer if you can.
 
1. Will the app execute in the .NET Framework runtime?
2. Will this require the .NET Hosting Bundle?
3. Will it require .NET Core to be installed on the IIS server?
4. As a deployed app, will there be anything ".NET Core" about it?

**Comment by davidfowl** [comment]
ASP.NET Core 2.1 (the LTS aka long term support) runs on .NET Framework and will be supported forever, 2.2 also runs on .NET Framework but isn't an LTS release. ASP.NET 3.0 and onward will only ever work on .NET Core. See this post for more details https://blogs.msdn.microsoft.com/webdev/2018/10/29/a-first-look-at-changes-coming-in-asp-net-core-3-0/.

As for other specific questions:

> * Will the app execute in the .NET Framework runtime?

Yes, if you use an edited meta package though, it'll deploy about ~200 assemblies with the application.

> * Will this require the .NET Hosting Bundle?

To run on ASP.NET Core on IIS, you need the hosting bundle. It's a new module, the old one that ships with windows does not work for ASP.NET Core.

> * Will it require .NET Core to be installed on the IIS server?

No, not if you're targeting .NET Framework.

> 4\. As a deployed app, will there be anything ".NET Core" about it?

No. If you use ASP.NET Core 2.1, it'll work. There are differences running ASP.NET on System.Web and ASP.NET Core on .NET Framework though.

**Comment by GoFightNguyen** [comment]
Thanks @davidfowl 

> Yes, if you use an edited meta package though, it'll deploy about ~200 assemblies with the application.

Please clarify what you mean by an edited meta package.

> To run on ASP.NET Core on IIS, you need the hosting bundle. It's a new module, the old one that ships with windows does not work for ASP.NET Core.

To clarify, even though the app would be targeting net471 and executing in the .NET framework runtime, the hosting bundle is still necessary? I'm trying to reconcile this idea since there isn't anything ".NET core" about the deployed app.

> No. If you use ASP.NET Core 2.1, it'll work. There are differences running ASP.NET on System.Web and ASP.NET Core on .NET Framework though.

Can you explain or provide any resources explaining these differences?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
