### ISSUE TITLE
Disable request body data rate limits per HTTP/2 stream

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#7635]
Epic https://github.com/aspnet/AspNetCore/issues/8858

Currently we can disable the request body data rate limit for the entire server with
```c#
                    webBuilder.ConfigureKestrel(options =>
                    {
                        options.Limits.MinRequestBodyDataRate = null;
                    });
```

However, we want to be able to control this on a finer scale of per request/stream. We need this in since certain gRPC endpoints are client streaming methods which may not satisfy the request body data rate while all other endpoints of the app should still be subject to the request body data rate. Websocket scenarios will also benefit from this feature.

To implement this feature, it's likely we'll need to overhaul the accounting for request data rates. @halter73 has more context about the implementation here. 

cc @Tratcher @davidfowl

**Comment by halter73** [comment]
There are two options we discussed:

1. A stopgap measure where we allow disabling rate limit for specific HTTP/2 streams/requests, but not modifying the rate limit to a non-null value.

2. A more thorough rearchitecture of HTTP/2 rate limiting which tracks and limits data rates at the stream level instead of the connection level. One potential wrinkle with this idea is that the default rate limit for an HTTP/2 connection would become 240 bytes/sec times the number of streams actively reading from the request body instead of just 240 bytes/sec if the app is actively reading from the request body like it is for HTTP/1.

**Comment by blowdart** [comment]
The stopgap seems a deeply undesirable idea.

**Comment by halter73** [comment]
@blowdart Why is that? It's basically what we do for WebSocket requests. If you have an endpoint where you know the client will use the request body to send intermittent messages, the stopgap measure gives you the behavior you want. Even the more thorough rearchitecture will allow you to get the behavior the stopgap solution give you. It just gives you more complete control.

**Comment by blowdart** [comment]
Because it's a half implementation? And more worrying if that feature is there then you known someone, somewhere is going to turn that on for normal requests.

**Comment by JamesNK** [comment]
@muratg @shirhatti Please prioritize this.

**Comment by muratg** [comment]
Do we need a design meeting for this, @shirhatti?

**Comment by JunTaoLuo** [comment]
ping @anurse we spoke offline and we want to take @halter73 suggestion number 1:
> A measure where we allow disabling rate limit for specific HTTP/2 streams/requests, but not modifying the rate limit to a non-null value.

Can we get a milestone commitment for this work?

**Comment by JunTaoLuo** [comment]
@anurse Any updates on the triage decision here? Can we commit to preview 5? That would be nice.

**Comment by anurse** [comment]
We're reviewing Kestrel 3.0 work tomorrow, I'll bring this up.

**Comment by anurse** [comment]
Ack, we missed this. @halter73 @blowdart Can we close the debate on which approach is most appropriate? As @halter73 said, the first approach is exactly what we do with WebSockets today. It shifts the onus of data rate management on to the consumer, but that's the general idea here. gRPC has different data rate expectations than standard HTTP so it makes sense for it to be in control here.

If the cost is still "L", it's going to be very challenging to fit this in to our release, so I'd like to understand the actual cost of the desired solution so we can figure out where to fit this.

**Comment by blowdart** [comment]
OK, throwing out the example at the top, I would presume that neither WebSockets nor grpc would turn off limits? Or am I just hopeful, and because they're long winded/running, they could have no limits at all?

**Comment by halter73** [comment]
> I would presume that neither WebSockets nor grpc would turn off limits?

Minimum request body data rate limit are never enforced for upgraded (i.e. WebSocket) requests. GRPC would manually turn disable the minimum request body data rate limit by setting `HttpContext.Features<IHttpMinRequestBodyDataRateFeature>().MinDataRate` to null on a per-request basis.

**Comment by anurse** [comment]
Triage decision: We can at least add the ability to disable the min data rate for a single HTTP/2 stream.
