### ISSUE TITLE
[Blazor Components] How to pass values from a Component page to its hosting layout Component and vice versa

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#7641]
Does anyone know how to pass values from a Component page to its hosting layout Component and vice versa ?

Thanks...

**Comment by Andrzej-W** [comment]
Create a class which holds your data. Register it as singleton service. Inject it into layout and into page. You should probably add a notification mechanism to inform all your components that something was changed in your data class. You can look here:

https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/FlightFinder

A few interesting places:

https://github.com/aspnet/samples/blob/136b4bb35ba8001b230bd21c8ac632c4b572bb41/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Client/Services/AppState.cs#L52
https://github.com/aspnet/samples/blob/136b4bb35ba8001b230bd21c8ac632c4b572bb41/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Client/Startup.cs#L11
https://github.com/aspnet/samples/blob/136b4bb35ba8001b230bd21c8ac632c4b572bb41/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Client/Main.cshtml#L23

**Comment by enetstudio** [comment]
Great... Many thanks...

**Comment by Andrzej-W** [comment]
@enetstudio One important note. I'm using Blazor on the client (WebAssembly). Here singleton service is OK. Flight Finder was initially created as WebAssembly application and recently ported to Razor Components. In Razor Components you should probable use `scoped` service. Otherwise you will be sharing state between all users and it is probably not what you want.

**Comment by enetstudio** [comment]
I got it. thanks a lot for your help...

**Comment by sven5** [comment]
Any update on this? Still the only way to solve such a scenario?
I think about something like ViewBag or ViewData we're using in MVC.

Thanks
Sven
