### ISSUE TITLE
Extract property AutoSaveChanges into new interface

### ISSUE THREAD

**Issue by michaeldz** [aspnet/AspNetCore#7648]
### Problem
I need to execute multiply actions related with UserStore into scope of one transaction. Easiest way to do it:
``` 
myUserStore.AutoSaveChanges = false; 
// manipulate with users ...
await dbContext.SaveChangesAsync();
```

So I need to use AutoSaveChanges in my service/code. But user store is injected into my code thru DE as `IUserStore<MyUser>`.

AutoSaveChanges is defined into base generic class `UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken, TRoleClaim>`. 

It is very inconvenient to cast the store object to base (or derived) type, especially if my service or code more or less abstract. I mean if my service/code should works with custom implementation of UserStore that unknown. In this case I should cast to base generic UserStore<...>

Solution with reflection like this 
```
var userStoreType = _userStore.GetType();
var genericUserStoreType = typeof(UserStore<,,,,,,,,>);
var t = userStoreType;

while (t != null)
{
    if (t.IsGenericType && t.GetGenericTypeDefinition() == genericUserStoreType)
    {
        userStoreType.InvokeMember(nameof(UserStore.AutoSaveChanges), BindingFlags.SetProperty, null, _userStore, new object[] { false });
    }
    t = t.BaseType;
}
```
doesn't look perfect and optimal.

### Solution
Add new interface IEFStore (perhaps more convenient/right name is required):
```
public interface IEFStore
{
    bool AutoSaveChanges { get; set; }
}
```

and implement it in:
`UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken, TRoleClaim>`
`UserOnlyStore<TUser, TContext, TKey, TUserClaim, TUserLogin, TUserToken>`
`RoleStore<TRole, TContext, TKey, TUserRole, TRoleClaim>` 

my code will look:
```
if(_userStore is IEFStore efStore)
{
    efStore.AutoSaveChanges = false;
}
```

**Comment by blowdart** [comment]
This is not something we can do easily, if at all, without a grander redesign, so I'm sorry, but no.

**Comment by michaeldz** [comment]
Looks strange, probably misunderstanding ...
Adding the interface **IEFStore** to the store class:
```
    public class UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken, TRoleClaim> :
        UserStoreBase<TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken, TRoleClaim>,
        IProtectedUserStore<TUser>,
>>      IEFStore
        where TUser : IdentityUser<TKey>
        where TRole : IdentityRole<TKey>
        where TContext : DbContext
        where TKey : IEquatable<TKey>
        where TUserClaim : IdentityUserClaim<TKey>, new()
        where TUserRole : IdentityUserRole<TKey>, new()
        where TUserLogin : IdentityUserLogin<TKey>, new()
        where TUserToken : IdentityUserToken<TKey>, new()
        where TRoleClaim : IdentityRoleClaim<TKey>, new()
{ ... }
```
Very very small and easy change that should not break compatibility and affect other code.
