### ISSUE TITLE
InputTagHelper use the value from QueryString instead from Model

### ISSUE THREAD

**Issue by John0King** [aspnet/AspNetCore#7653]
### Describe the bug
When a QueryString use ModelBinding then  the `InputTagHelper` will not use the value from Model .
The issue caused by the `ModelState` , ModelBinding add a `AttemptedValue` to the `ModelState`

### To Reproduce
//// url: GET   /testpage?A=666
```C#
//// controller
public IActionResult TestPage(int A)
{
    var m = new MyClass{ A = 11 };
    return View(m);
}
```
```Razor
//// view
@model MyClass
<input asp-for="A" />
```

### Expected behavior
input's value is 11  but the actual value is 666

### To avoid this
`AttemptedValue` should only show after there's a Model Bind Error, so before use the `AttemptedValue` we should check the `ModelState.IsValid`

https://github.com/aspnet/AspNetCore/blob/799b91a324b531e1a91512ec3f77f783f61c3a82/src/Mvc/Mvc.ViewFeatures/src/DefaultHtmlGenerator.cs#L713-L723

**Comment by danroth27** [comment]
This is expected behavior. The date in the model state wins.
