### ISSUE TITLE
KeyNotFoundException: The given key 'OpenIdConnect.Code.RedirectUri' was not present in the dictionary.

### ISSUE THREAD

**Issue by hnviradiya** [aspnet/AspNetCore#7654]
### Describe the bug
When Hybrid Flow Authentication & Single Page Application combines. This error occurs. It redirects to identityserver & on callback this error is generated. Error is not on identityserver but on client project.

### To Reproduce

1. Using this version of ASP.NET Core 2.2
2. Run following 2 projects
   https://github.com/hnviradiya/asp-net-core-vue-starter
   https://github.com/IdentityServer/IdentityServer4

& click on Fetch Data. It will try to get authenticated ajax data & will redirect u to identityserver. on return (callback) this error will occur.

1. See error (In browser)

### Expected behavior
It should authenticate from oidc middleware & return single page application index.html file.

### Screenshots
![image](https://user-images.githubusercontent.com/12680915/52897538-d1ec7e00-31fb-11e9-94b8-c4b95aa40a0f.png)

### Additional context

Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
Version: 2.2.103
Commit: 8edbc2570a

Runtime Environment:
OS Name: Windows
OS Version: 10.0.17134
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
Version: 2.2.1
Commit: 878dd11e62

.NET Core SDKs installed:
1.1.11 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by Tratcher** [comment]
This is again caused by your customizations.
https://github.com/hnviradiya/asp-net-core-vue-starter/blob/b8446d7ad130719874cea86f8c01b7877619f233/Startup.cs#L79-L89

https://github.com/aspnet/AspNetCore/blob/799b91a324b531e1a91512ec3f77f783f61c3a82/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L415

https://github.com/aspnet/AspNetCore/blob/799b91a324b531e1a91512ec3f77f783f61c3a82/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L1097

When you need to customize this much you might be using the wrong flow. JwtBearer would be more appropriate than OIDC to use here.
