### ISSUE TITLE
asp-page anchor tag helper does not create the link without ".../Index" trailing for default pages inside sub folders

### ISSUE THREAD

**Issue by saeed-serpooshan** [aspnet/AspNetCore#7656]
In asp.net core Razor Pages, the `asp-page` anchor tag helper does not create the 'href' if we don't include the ".../Index" for default (index) pages inside sub folders.

For example, consider we want to provide a link to index page inside the Movies sub folder (So, we have a Pages/Movies folder containing several razor pages like as Index.cshtml, Creat.cshtml, Edit.cshtml).

None of following codes generates proper anchor link (the produced `href` will be an empty string):
```
    <a asp-page="/Movies">Movies</a>
    <a asp-page="/Movies/">Movies</a>

```

Both of them generates this wrong html: `<a href="">Movies</a>`

But if we specify the "/Index" as in following code, it will produce expected link:

```
    <a asp-page="/Movies/Index">Movies</a>

```

Output: `<a href="/Movies">Movies</a>`

I'm using asp.net core 2.2 in VS 2017 ver 15.9.3

**Comment by rynowak** [comment]
This is by design. The argument to `asp-page` is a **page name** not a URL Path.

**Comment by saeed-serpooshan** [comment]
> This is by design. The argument to `asp-page` is a **page name** not a URL Path.

@rynowak Thanks for reply, but why its not documented well (and many new docs from Microsoft is not well explanation as we saw 15 years ago!). Please see these references: [Anchor Tag Helper ](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.2#asp-page) and [AnchorTagHelper.Page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.taghelpers.anchortaghelper.page?view=aspnetcore-2.2). 
This is very disappointing that MS Refs are written without detail information nowadays! All info that is provided there (specially the second ref) is the signature of the property, its return type (string!) and a 1 line remark which all of them can already be seen in IntelliSense tool-tips!!!

Anyway, It could be good if behavior of this property be like as what we **normally** expect: i.e. use the default page (i.e. "Index") at least when the given param **ends with a slash**, eg: `<a asp-page="/Movies/">` should simply create: `<a href="/Movies/">` or `<a href="/Movies">`

I'm not sure if there is any drawback if it is implemented this way? if your concern is about collision with same filename as the sub folder in containing folder, then as i said above, one simple way to avoid it is when the specified page name ends with a trailing slash ( "/Movies/") which indicate this is a folder.

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
