### ISSUE TITLE
Link Header CSS Performance

### ISSUE THREAD

**Issue by daikoz** [aspnet/AspNetCore#7661]
### Is your feature request related to a problem? Please describe.
CSS is define in csthml like this:
`   <link rel="stylesheet" href="~/mystylesheet.min.css" asp-append-version="true" />`

### Performance issue:
Browser must start read html code and link element to begin to request the stylesheet.

### Solution:
Use Link header:
`            Response.Headers.Add("Link", "</mystylesheet.min.css>; rel=\"stylesheet\"");`

Now, when browser read header, it can start to request the css in parallel of html page.

### Implemenation:
Add a attribute to link to add this link directly in the Link header:
`   <link rel="stylesheet" href="~/mystylesheet.min.css" asp-append-version="true" header="true" />`

**Comment by pranavkm** [comment]
I don't think the feature is well-supported across browsers. Example: https://bugs.chromium.org/p/chromium/issues/detail?id=19237

Do you have of a more recent listing that describes what the status for HTTP Link headers for is across browsers?

**Comment by daikoz** [comment]
No, it is difficult to found browser compatiblity on it.

**Comment by pranavkm** [comment]
In the absence of standard support across browsers, I don't think it makes sense to support this feature.
