### ISSUE TITLE
Razor components. Handling long operations.

### ISSUE THREAD

**Issue by roboriaan** [aspnet/AspNetCore#7666]
On razor components I have a question regarding operations that takes long. For example waiting for a big database operation to complete.

With the blazor hosted project it is quite simple to show a loading indicator while waiting for a response from the web api but with razor components the browser seems locked up until the response comes back.

Are there any ways to handle a scenario like this?

I'm using blazor 0.8 on sdk 3. 

Thanks in advance

**Comment by rynowak** [comment]
> but with razor components the browser seems locked up until the response comes back.

Can you share your code for the database update part? Make sure you're not using `Task.Result`/`Task.Wait()` or other blocking APIs.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
