### ISSUE TITLE
AspNetCoreModule 502.5 error and 0x80070005 event viewer log

### ISSUE THREAD

**Issue by jokinj** [aspnet/AspNetCore#7678]
We are trying to deploy our application to IIS using Azure Devops. 

Once the deploy finishes ok, we get the 502.5 error.

Taking a look at the event viewer we get the next error (renaming our application name, sorry...):

Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE/XXX.WEBAPI' with physical root 'C:\WebRep\XXX.WebApi\' created process with commandline 'C:\WebRep\XXX.WebApi\XXX.WebApi.exe 'but failed to get its status, ErrorCode = '0x80070005'.

As so many issues reported by other users, std logs are empty.

We tried to execute the exe from line command and everything works fine with kestrel, we only get the error with IIS requests.

Any idea?

OS: Windows Server 2008 R2
net core: 2.1 & 2.2

Thanks!

**Comment by muratg** [comment]
Sounds like an ACLing issue. Can you check that you have the right ACLs and post them here?

**Comment by jokinj** [comment]
Thank you for your support.

This is our ACL setted on the application folder:

BUILTIN\Administrators:(I)(F)
CREATOR OWNER:(I)(OI)(CI)(IO)(F)
NT AUTHORITY\IUSR:(I)(OI)(CI)(F)
NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
NT AUTHORITY\NETWORK SERVICE:(I)(OI)(CI)(F)
BUILTIN\Administrators:(I)(OI)(CI)(IO)(F)
BUILTIN\IIS_IUSRS:(I)(OI)(CI)(F)
BUILTIN\Users:(I)(OI)(CI)(RX)
BUILTIN\Users:(I)(CI)(AD)
BUILTIN\Users:(I)(CI)(WD)
CREATOR OWNER:(I)(OI)(CI)(IO)(F)

As you can see, IIS_IUSRS and IUSR both have full control access.

**Comment by muratg** [comment]
cc @shirhatti

**Comment by shirhatti** [comment]
What identity is your ApplicationPool running as?

**Comment by jokinj** [comment]
Our pool application is running as "ApplicationPoolIdentity".

Finally our application is working fine!! One of our last actions on the pool was to set "Load User Profile" to "false".

Anyway, when @muratg asked us for the ACLs we were correcting some group, I think the resolution is a combination of this action and the value of the "Load User Profile" property.
 
I will do some local tests to clarify this behavior and I will share it in this same ticket.

Thank you!
