### ISSUE TITLE
CascadingValue attribute

### ISSUE THREAD

**Issue by wicked-sick** [aspnet/AspNetCore#7682]
Can the `CascadingValue` Blazor snippet used in `.cshtml` files:
```
// MyComponent.cshtml
<CascadingValue Name="MyValueName" Value=this>
    @ChildContent
</CascadingValue>
```
be available in `.cs` files like an attribute:
```
// MyComponent.cs
[CascadingValue(this, "MyValueName", "ChildContent")]
public class MyComponents : ComponentBase {}
```
The idea is to reduce the boilerplate code and inject the "ChildContent" prop in the class. Using more than one cascading value can be done in the cshtml file, so this is just about a "default export" of the component to its child components.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @wicked-sick.
This is not something we plan to add support for.
