### ISSUE TITLE
[Templating]React template contains unnecessary files

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#7686]
https://github.com/aspnet/AspNetCore/tree/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/React-CSharp/ClientApp/src/store

This seems to have been caused by a recent merge from a customer PR

**Comment by javiercn** [comment]
@mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please have a look at this? Thanks!

**Comment by javiercn** [comment]
@ryanbrandenburg Is this done?

**Comment by ryanbrandenburg** [comment]
Yes, thanks for the reminder.
