### ISSUE TITLE
 <NavLink class="nav-link"> without  href=""

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#7694]
_From @UrielMhezzek on Sunday, 17 February 2019 19:28:27_

If you use NavLink -Component without href in Selfmade-BlazorComponent, the Selfmade-BlazorComponent is no longer loaded and you only get the following message in the console from Browser

> Uncaught Error: No element is currently associated with component 7
>     at e.updateComponent (blazor.server.js:23)
>     at Object.t.renderBatch (blazor.server.js:16)
>     at e.<anonymous> (blazor.server.js:38)
>     at blazor.server.js:16
>     at Array.forEach (<anonymous>)
>     at e.invokeClientMethod (blazor.server.js:16)
>     at e.processIncomingData (blazor.server.js:16)
>     at e.connection.onreceive (blazor.server.js:16)
>     at WebSocket.i.onmessage (blazor.server.js:16)

_Copied from original issue: aspnet/Blazor#1788_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @UrielMhezzek.
@SteveSandersonMS can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@javiercn can you please investigate this? Thanks
