### ISSUE TITLE
Auth cookies not sticking with Desktop versions of Safari

### ISSUE THREAD

**Issue by timgabrhel** [aspnet/AspNetCore#7696]
I have a small handful of users that are unable to log on to our site while using their macOS & Safari browser. These users have confirmed they can authenticate just fine with another browser, or their phones (typically iPhone). This is a preview release of our new version of our product so I have very limited reach to these users in terms of technical troubleshooting. I am hesitant to release this further until I can fix this problem. 

Users attempt to log in, but the login screen just refreshes, with no errors. Think of behavior like a sign in page redirect after accessing a protected resource. My theory is the `Set-Cookie` response headers are for some reason being ignored with the redirect.

I do not have anyone on the company side to reproduce. Any developers with Mac's can't reproduce.

ASP.NET Core 2.2
Auth0 for identity provider
Cookie Authentication
Safari 10.X & 12.X fail, but others also report success.

*What I'm looking for*
Is there anything misconfigured here that could be affecting Safari somehow? I'm at a loss as I can't reproduce this, but enough random users have reported it so it's certainly a problem. 

**Startup Configure**
```
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
    // irrelevant bits removed

    app.Use(next => context =>
    {
        context.Request.EnableRewind();
        return next(context);
    });

    if (Environment.IsDevelopment())
    {
        app.UseDatabaseErrorPage();
        app.UseDeveloperExceptionPage();
        app.UseMiniProfiler();

        loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Trace);
    }
    else
    {
        app.UseHsts();
        app.UseExceptionHandler("/error");
        app.UseStatusCodePagesWithRedirects("/error/{0}");
        loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Warning);
    }

    app.UseHttpsRedirection();
    app.UseSession();
    app.UseStaticFiles();
    app.UseAuthentication();

    app.UseMvc(routes =>
    {
            // commented out
    });
}
```

**Startup Configure Services**
```
public void ConfigureServices(IServiceCollection services)
{
    // irrelevant bits removed 

    services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();

    services.AddHsts(options =>
    {
        options.Preload = true;
        options.IncludeSubDomains = true;
        options.MaxAge = TimeSpan.FromDays(180);
    });

    // add data protection

    // add distributed session

    services.AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    })
    .AddCookie(opts =>
    {
        var cookieDomain = Configuration.GetValue<string>("Auth0:CookieDomain");
        if (!string.IsNullOrWhiteSpace(cookieDomain))
        {
            opts.Cookie.Domain = cookieDomain;
        }
        
        opts.LoginPath = "/login";
        opts.Events = new CookieAuthenticationEvents()
        {
            OnValidatePrincipal = CustomCookieAuthenticationEvents.ValidatePrincipal
        };
    });

    services.Configure<SecurityStampValidatorOptions>(options =>
    {
        options.ValidationInterval = TimeSpan.FromMinutes(1);
        options.OnRefreshingPrincipal = context =>
        {
            var isImpersonatingClaim = context.CurrentPrincipal.IsImpersonating();
            if (isImpersonatingClaim)
            {
                var impersonationClaims = context.CurrentPrincipal.BuildImpersonationClaims();
                context.NewPrincipal.Identities.First().AddClaims(impersonationClaims);
            }
            return Task.FromResult(0);
        };
    });

    // Add AutoMapper
    services.AddAutoMapper(typeof(Startup));
    MappingConfigurator.InitializeAndCompile();

    services
        .AddMvc()
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
}
```

**Login**
```
[HttpPost]
[Route("/login")]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
{
    // irrelevant bits removed 

    if (!ModelState.IsValid) return View(model);

    var ticket = await _authorizeService.Authorize(model.EmailAddress, model.Password);

    var claimsPrincipal = authTicket.CreateClaimsPrincipal();
    var authProps = authTicket.CreateAuthProperties(persistent);

    // Sign user into cookie middleware
    await HttpContextAccessor.HttpContext.SignInAsync(
        CookieAuthenticationDefaults.AuthenticationScheme,
        claimsPrincipal,
        authProps);

    // this uses the claims principal to figure out where to send the user.
    // this will result in a 302 
    return BaseServices.RedirectService.AfterLogin(claimsPrincipal, returnUrl);

    return View(model);    
}
```

**Comment by Tratcher** [comment]
An issue like this is best troubleshot by capturing a trace of the HTTP headers. Tools like Fiddler and Wireshark are good (HTTPS issues aside), manual server side logging of request and response headers.

Safari is known to discard large cookies. How large are your typical auth cookies?

**Comment by benaadams** [comment]
Might be similar to https://github.com/aspnet/Announcements/issues/318?

**Comment by timgabrhel** [comment]
> An issue like this is best troubleshot by capturing a trace of the HTTP headers. Tools like Fiddler and Wireshark are good (HTTPS issues aside), or manual server side logging of request and response headers.
> 
> Safari is known to discard large cookies. How large are your typical auth cookies?

@Tratcher  Here's the trace of a 302 that includes the auth cookies being set, and the redirect to the logged in path for me. When signing the user in, the claims principal is being enriched with data used by the application, but as you can see, ASP.NET is properly chunking cookies, as far as I can tell.

![image](https://user-images.githubusercontent.com/791022/53021604-2d4a8600-341f-11e9-8d01-d48ca46a8b63.png)

![image](https://user-images.githubusercontent.com/791022/53021746-831f2e00-341f-11e9-934b-02f5c54c9cb1.png)

You'll notice the auth cookie's SameSite setting is set to None, as an attempt for what @benaadams linked, though I don't feel it's related as that appears specific to iOS12, and not macOS.

**Comment by benaadams** [comment]
Expires on the cookies (from the safari dev tools) is very in the past; could it be using the Page expires as no value is given in Set-Cookie (from the fiddler trace)

**Comment by timgabrhel** [comment]
> Expires on the cookies (from the safari dev tools) is very in the past; could it be using the Page expires as no value is given in Set-Cookie (from the fiddler trace)

That makes sense to me, but it doesn't explain the sporadic behavior of the issue. I just tested on the CookieSample from the Docs repo, and see the same result on the cookies.

https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authentication/cookie/samples/2.x/CookieSample

![image](https://user-images.githubusercontent.com/791022/53032868-5aa22e80-3435-11e9-94ee-c07f4935e40c.png)

**Comment by timgabrhel** [comment]
Just got a report from a user that explicitly setting the auth expiration did not have an effect.

**Comment by Tratcher** [comment]
Note the expiration should be unrelated. That 1969 date just means that it's a browser session cookie and will be removed if you close the browser.

See http://browsercookielimits.squawky.net/, Safari has the lowest total size per domain. Even chunking may not be adequate. [ITicketStore](https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Cookies/src/ITicketStore.cs) can be used to mitigate storage issues.

**Comment by timgabrhel** [comment]
@Tratcher Thanks a lot Chris. The date bit is helpful.

This cookie limit is great info, though it's a bit out of date on Safari versions. "Per domain" gives me what I need for searching. 

I was already starting to look at ITicketStore, but my hand may be forced. Do you have any recommendations for preferred storage for cookies? I've only seen an in-memory example. I am using Redis for Session, but unsure if there's a security or implication over using this vs SQL.

**Comment by Tratcher** [comment]
No specific recommendations. If you've got multiple servers you'll need some distributed storage like redis.

**Comment by timgabrhel** [comment]
@Tratcher Hey Chris - I have everything all set up, but I'm struggling to handle the storage of the `AuthenticationTicket` into Redis. Do you have any proper guidance for this type? 

I'm trying to serialize the model but I'm unable.

> Type 'Microsoft.AspNetCore.Authentication.AuthenticationTicket' in Assembly 'Microsoft.AspNetCore.Authentication.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' is not marked as serializable.

```
public static byte[] ToByteArray<T>(T obj)
{
    if (obj == null)
        return null;
    BinaryFormatter bf = new BinaryFormatter();
    using (MemoryStream ms = new MemoryStream())
    {
        bf.Serialize(ms, obj);
        return ms.ToArray();
    }
}
```

**Comment by Tratcher** [comment]
You can probobly re-use https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Core/src/TicketSerializer.cs.

**Comment by timgabrhel** [comment]
Just came across that after posting. Works just fine. Thanks!

```
public Task RenewAsync(string key, AuthenticationTicket ticket)
{
    TimeSpan? expiresTimespan = null;

    if (ticket.Properties.ExpiresUtc.HasValue)
        expiresTimespan = ticket.Properties.ExpiresUtc.Value.Subtract(DateTimeOffset.UtcNow);

    var ticketBytes = TicketSerializer.Default.Serialize(ticket);
    
    _cacheProvider.Set(key, ticketBytes, expiresTimespan);

    return Task.CompletedTask;
}
```

**Comment by timgabrhel** [comment]
@Tratcher Is there a recommended best practice for generating the keys used for storage? The memory cache provider example uses a new Guid on each issue, but that's not seemingly practical. It works for a basic sign in session, but I am making use of the CookieAuthenticationEvents.ValidatePrincipal to handle refreshing the current users auth tokens when their access token is nearing expiration. I can't seem to track the call stack down, but because of the randomness of the key being generated, there seems to be a mixup between the auth cookie on the browser & what's stored in the ticket store. 

I'm also utilizing shared cookies between web & api applications which works great, but seems to have the same symptom I described above. 

If I test by generating the key to a known & common value (ie. a user id), everything works perfectly, except I end up with a global cookie session and sign out that affects all browsers.

Am I making sense?

**Comment by Tratcher** [comment]
I don't follow. The identifier is arbitrary but should uniquely identify a login session. Why not use a GUID?

It sounds like you're running into a race condition in ValidatePrincipal where you may be updating the same ID concurrently on two parallel requests. That would be unrelated to the actual key value. If you weren't using ITicketStore then it would be a matter of last-write-wins, whichever last cookie made it to the client would be the one used in the future. How is it different in this case?

**Comment by timgabrhel** [comment]
Ok. So it now makes sense to me that any `HttpContext.SignInAsync()` call will call `ITicketProvider.StoreAsync`. 

In my ValidatePrincipal event, I am generating a new claims principal, as well as new authentication properties. The main point of this method existing is to refresh the auth properties when the access token is expiring. I have the refresh token, so I can make this happen, however, `CookieValidatePrincipalContext` only exposes `ReplacePrincipal`, which will update the claims of the current user, but not the auth properties. In effect, I think, I would perpetually have an expired access token that is continually being refresh. For this reason, I was explicitly calling SignOut/SignIn, thus the race condition you mentioned when looking up the ticket.

Should I be handling expiring access tokens in a different way? To reiterate my OP, I'm using Auth0 as my identity provider, and simple Cookie authentication. No identity.

**Comment by Tratcher** [comment]
Yeah, ValidatePrincipal isn't great for that, you could end up doing a lot of redundant work. You'd be better off verifying and refreshing the tokens when you went to use them instead.

Note you do not need to call SignOut for a refresh, only SignIn.

**Comment by leastprivilege** [comment]
> Yeah, ValidatePrincipal isn't great for that

Hm - I prototyped that as well and it seems to work fine (there is one little edge case that I need to fix)

https://github.com/leastprivilege/AspNetCoreSecuritySamples/blob/aspnetcore21/AutomaticTokenManagement/src/AspNetCoreSecurity/AutomaticTokenManagement/AutomaticTokenManagementCookieEvents.cs

**Comment by timgabrhel** [comment]
> > Yeah, ValidatePrincipal isn't great for that
> 
> Hm - I prototyped that as well and it seems to work fine (there is one little edge case that I need to fix)
> 
> https://github.com/leastprivilege/AspNetCoreSecuritySamples/blob/aspnetcore21/AutomaticTokenManagement/src/AspNetCoreSecurity/AutomaticTokenManagement/AutomaticTokenManagementCookieEvents.cs

I forked your sample & tried to make it match my solution, but I couldn't make it fail. 

I have a few extras at play:
- Redis backed ITicketStore
- Web & Api sharing cookies 

Api looks for the ASP.NET Core cookie on the request, and if found, it'll use the cookie policy. When it's not found, it'll use JWT. Defaulting to cookies gives me a big benefit due to the claims enrichment I'm doing for the user. When I use JWT (mobile app), that enrichment has to be done for each request.

If I only use JWT on the API, the `SignIn` within ValidatePrincipal works fine. When using cookies, I am finding the API cookie key seems to be out of sync with web. That's when the the `ITicketStore.RetrieveAsync` call for the ticket fails.

```
public Task<AuthenticationTicket> RetrieveAsync(string key)
{
    var ticketBytes = _cacheProvider.Get<byte[]>(key);
    if (ticketBytes == null)
        return Task.FromResult<AuthenticationTicket>(null);

    var ticket = TicketSerializer.Default.Deserialize(ticketBytes);
    return Task.FromResult(ticket);
}
```

**Comment by timgabrhel** [comment]
I refactored my expires refresh code out of the ValidatePrincipal into a new service. I ask for the access token just as I'm about to send an HTTP request to the API, except I'm still seeing the same issue. The tokens are refresh, I re-call sign in, but the API is throwing back the 401 still. It can't find the ticket. 

So I added a check to see if we just refreshed the tokens (while getting them off the HTTP context), I will explicitly remove the Cookie headers from the request. This in turn causes the API to use JWT token for authorization.
![image](https://user-images.githubusercontent.com/791022/53256939-a996d080-368e-11e9-8e16-7eeb2e501e7e.png)

And this works. But I feel like I'm bending the system in a fashion that it's not meant to be.

**Comment by Tratcher** [comment]
That smells. You should never have to remove the cookie header. This seems more like an issue with how you've configured your auth policies. You've got so many moving parts here I don't think we can comment further without a complete example app and some repro steps.

**Comment by timgabrhel** [comment]
I understand, and agree. I will try and get a sample repro setup with the same parts.

Thanks for keeping an eye here.

**Comment by timgabrhel** [comment]
I can confirm implementing the ITicketStore solved the problem for some versions of Safari. 

I'll close this for now, big thanks to all the comments. Whenever I can get around to trying to repro my cookie issue, I'll open a separate issue.
