### ISSUE TITLE
Android Client

### ISSUE THREAD

**Issue by xjpmauricio** [aspnet/AspNetCore#7705]
I've been trying to implement an Android chat client, the server-side is based on the project from: https://github.com/aspnet/Docs/tree/master/aspnetcore/signalr/dotnet-client/sample

I managed to create a Windows forms client that connects to the chat with success; the sample also works perfectly on the browser clients, etc. All clients seem to work flawlessly.

My problem is the android client; I cannot make it to work. Whenever I try to connect to the hub I get the error "There were no compatible transports on the server.".
I have websockets installed on the server.

I've tried the url: http://mydomain.com/signalr
I if try with http://mydomain.com I get a 404 (not found).

My Android client is based on: https://github.com/aspnet/SignalR-samples/tree/master/AndroidJavaClient

My great doubt is: is this new java client compatible with signalr applications built using libraries like
Microsoft.AspNet.SignalR.Core
Microsoft.AspNet.SignalR.SqlServer
Microsoft.AspNet.SignalR.SystemWeb

What am I missing?

Thanks.

**Comment by davidfowl** [comment]
> My great doubt is: is this new java client compatible with signalr applications built using libraries like

This new java client does not work with SignalR 2.x, it only supports ASP.NET Core SignalR.

**Comment by xjpmauricio** [comment]
Is there any java-client we could use on Android that works with SignalR 2.x?

**Comment by mikaelm12** [comment]
The SignalR 2.X Android client was **__depricated and is no longer supported__** so we don't suggest using it. That being said, if you want to take a look the source is here: https://github.com/SignalR/java-client
