### ISSUE TITLE
Source linking broken in latest ci bits

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#7710]
### Describe the bug
I can no longer debug into the source code on ASP.NET Core when using builds from https://github.com/dotnet/core-sdk#installers-and-binaries.

### To Reproduce
1. Make a new project
1. Add https://dotnet.myget.org/F/aspnetcore-dev/symbols to your list of symbol servers in the Visual Studio Debugging options
1. Break in the debugger
1. Right click load symbols on the call stack of one of the ASP.NET Core assemblies
1. Double click on the call stack frame
1. Visual studio can't find the source code

### Expected behavior
The source code for the method I double clicked should be loaded

### Screenshots
![image](https://user-images.githubusercontent.com/95136/53031697-34bf5e80-3422-11e9-801f-826f6f6e7b41.png)

### Additional context
latest preview3 build of ASP.NET Core preview3-19117-05

**Comment by pranavkm** [comment]
Verified that this PR - https://github.com/aspnet/AspNetCore/commit/65fa8d57b466b2a087f01fd87affb8b2ee4d3932 - fixed this issue.

**Comment by davidfowl** [comment]
Reflex FTFW
