### ISSUE TITLE
[Tooling] Unskip TryGetExcerptInternalAsync_MultiLine_Boundaries_CanClassifyCSharp

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#7713]
`TryGetExcerptInternalAsync_MultiLine_Boundaries_CanClassifyCSharp` is currently skipped due to https://github.com/dotnet/roslyn/issues/31548. Once the Roslyn issue is resolved we should unskip the test. Putting this in the current milestone + 1 to ensure we revisit this.

**Comment by mkArtakMSFT** [comment]
Closing this as a dupe
