### ISSUE TITLE
FindByEmailAsync inconsistencies should be documented or API fixed

### ISSUE THREAD

**Issue by Ponant** [aspnet/AspNetCore#7716]
`FindByEmailAsync` will return a `FirstOrDefaultAsync` in Asp.Net Identity UserStores, whereas unique emails are not required by default. So if I lookup for a given email I get only the first user that is hit in the db. This is an error that should be documented clearly in the api so that people know that they should treat this method only if `RequireConfirmedEmail` is true.

Ideally this method should return an `IEnumerable/IQueryable` in theory, it will be only one item in the list only if `RequireConfirmedEmail` is set to true. Or make another method `GetUsersByEmailAsync`?

I assume that the reason why the email property is not Indexed in DbContext is because it is the username which is unique, but perhaps this needs to be reconsidered with the above.

**Comment by blowdart** [comment]
If you call this API then you should know that your model has email as a key. If that's not the case, don't call the method. Changing it would differ from all our other Find* methods.

We will make the default implementation throw if there are in fact multiple users, and make that behaviour clear in the doc comments for the interface.
