### ISSUE TITLE
SignalR HubException should allow passing a structured data object back to the caller

### ISSUE THREAD

**Issue by adamra-msft** [aspnet/AspNetCore#7722]
### Is your feature request related to a problem? Please describe.
When throwing a `HubException` in a SignalR Hub, the `message` provided via the `HubException` constructor is (apparently) the only customizable field to pass data back to the client caller. However, there isn't an obvious way to pass structured data back to the caller other than by JSON serializing it into the `message` and unpacking it on the other end because `message` is a string. It would be nice if there were first-class support for serializing structured data, even if it is just string key/value pairs. This would allow sending a bag of data back to the caller without abusing the `message` field for this purpose.

### Describe the solution you'd like
In a SignalR Hub:

```
public async Task HubMethod()
{
    var hubException = new HubException("Error message");
    hubException.Data["Foo"] = "Bar";
    throw hubException;
}
```

On client:

```
try
{
    await connection.InvokeAsync("HubMethod").ConfigureAwait(false);
}
catch (HubException ex)
{
    // this assertion currently fails -- would like for this (or something similar) to work
    Assert.Equal("Bar", ex.Data["Foo"]);
}
```

### Describe alternatives you've considered
JSON serializing the data into the `message` and parsing it out of the `message` on the caller's end (ick)

### Additional context
I'm currently using Microsoft.AspNetCore.SignalR 1.1.0

**Comment by mikaelm12** [comment]
Hmm what would you plan on using this for that the message property wouldn't be enough for?

**Comment by adamra-msft** [comment]
Could you give an example of how I'd use the message property with `HubException`?

Or are you saying I should catch the `HubException` and translate it into a message to return back to the caller instead of letting the `HubException` bubble back? If you're saying this, then there would be two different ways to send errors back to the client (unhandled `HubExceptions` that are bubbled back and handled `HubExceptions` converted to messages), which means on the client-side I have to handle two different types of error cases. I'd like to avoid that if possible.

**Comment by bradygaster** [comment]
We've discussed this in previous iterations. At this time we're not going to add any additional structure to the exceptions.

**Comment by MagicAndre1981** [comment]
I also run into this issue. I get HubException, but the InnerException is null and I expected that the original exception is included. Now I have to parse the exception message to see which kind of Exception I get.

**Comment by mikaelm12** [comment]
> I get HubException, but the InnerException is null

If you're expecting an inner exception and it's not being propagated then that might be a different issue altogether. I'd suggest filing a new issue with more details so that we can investigate further.
