### ISSUE TITLE
Review if Logging and MemoryCache services should be added by other ASP.NET Core services by default

### ISSUE THREAD

**Issue by divega** [aspnet/AspNetCore#7728]
Some changes in 3.0 made Logging and MemoryCache services no longer required for EF Core. For that reason we initially removed them from our main service registration method, AddDbContext. 

That however caused several build breaks, in particular in tests that were relying on AddLogging and AddMemoryCache being called as a side effect of AddDbContext. 

In https://github.com/aspnet/EntityFrameworkCore/pull/14741 we reverted this particular change to fix the build. 

However it still seems weird and against pay-per-play for EF Core to ensure these services are registered even when it doesn't really requires them. 

I believe it should be up to the ASP.NET team to decide:

1. Is it ok for 3.0 users to get an error if their application relies on these services but they don't have a direct or indirect registration in their application?

2. If the answer to (1) is yes, is it ok if AddDbContext (and maybe other ASP.NET Core Add* methods) stops registering the services implicitly (and any tests that are failing for this reason get fixed instead)?

3. If the answer to (1) is no, should some other basic ASP.NET Core Add* method start registering these services instead of relying on a package like EF Core to do it?

Note that I haven't done the due diligence of testing or searching all the ASP.NET Core codebase to understand where/if these services are already being registered by other Add* methods.

**Comment by Eilon** [comment]
Though EF Core 3.0 has made a breaking change, SemVer says that's OK, so we should stick with whatever is the right thing to do there.

> That however caused several build breaks, in particular in tests...

Then those tests should be fixed.

And to answer the questions:
1. Yes it's OK. We should be clear and make an announcement and document it.
2. Yup.
3. That's an interesting question regardless of whether (1) is yes or no.

cc @davidfowl @DamianEdwards

**Comment by ajcvickers** [comment]
@Eilon @davidfowl @DamianEdwards @divega Here is the associated issue in the EF repo: https://github.com/aspnet/EntityFrameworkCore/issues/14756

Personally, I don't think this is a break worth making. There is little downside in EF continuing to add these services even though it doesn't use them. Yes, it would be cleaner for EF to stop doing this, but not sure it's worth causing any adoption challenges for 3.0. However, I believe @divega may disagree.

**Comment by Eilon** [comment]
I would consider "erring" on the side of doing what's "best" for EF here. I think it is incorrect to assume "someone else" has registered services for you because that is not a contractual thing. I think that while updating from 2.x to 3.0 there will be an upgrade "process" (i.e. migration doc) anyway, and we could include a mention of this in there.

But, I'm not pushing strongly on this. If the balance of peoples' opinion is to keep things the way they are, I support that.

**Comment by dougbu** [comment]
> make an announcement and document it

Has this happened?

**Comment by anurse** [comment]
Ping on this. Did an announcement happen for the change in EF behavior (not registering certain services)?

**Comment by anurse** [comment]
Ping again? @ajcvickers @divega ?

**Comment by ajcvickers** [comment]
@anurse It is in the EF breaking changes doc.
