### ISSUE TITLE
How can i add a third attribute to identify my user in user-role table?

### ISSUE THREAD

**Issue by HaniehRezayi** [aspnet/AspNetCore#7732]
We use the user-role based for authorization user in our project. we need to add an attribute to our table (user role table),which results in the user having the role when that attribute established. for example we want to say user A in location X has a special role but same user in location Y has another roles. in another words, if we have a user that have diffrent roles in two companies, if we want to delete company A, the role of user destroyed in in just company A, and this user stay in company B.
Asp.net core mvc - Asp.net core Identity

**Comment by blowdart** [comment]
You have to customize the identity model and avoid the sugar. https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2 has documentation on how to go about this.
