### ISSUE TITLE
'EnvironmentName' is an ambiguous reference between 'Microsoft.AspNetCore.Hosting.EnvironmentName' and 'Microsoft.Extensions.Hosting.EnvironmentName'

### ISSUE THREAD

**Issue by dodyg** [aspnet/AspNetCore#7733]
### Describe the bug
It's not really a bug but it's quite annoying because one will encounter it immediately after modifying a code generated in a new project template

### To Reproduce
```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace HelloWorld.Server
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    webBuilder.UseEnvironment(EnvironmentName.Development);
                });
    }
}
```

**Comment by davidfowl** [comment]
@Tratcher another one we need to tackle.

**Comment by Tratcher** [comment]
Similar to https://github.com/aspnet/Extensions/issues/966.
Replace them both with Extensions.Hosting.Environments?

**Comment by muratg** [comment]
@Tratcher do we _need_ this in preview3? Can we move it to preview4?

**Comment by Tratcher** [comment]
It should go into preview3.
- It's very related to a larger break https://github.com/aspnet/Extensions/issues/966 that went into preview3.
- The Extensions half of this has already been completed (https://github.com/aspnet/Extensions/pull/1141). We're only waiting on a dependency update to finish the AspNetCore half.
- It's a smaller fix in AspNetCore, I only see 7 instances.

**Comment by muratg** [comment]
:+1: Please ping @Eilon for approval. Thanks!

**Comment by Eilon** [comment]
Approved for preview3.
