### ISSUE TITLE
Session is not invalidated on server side after logout

### ISSUE THREAD

**Issue by ManuelHaas** [aspnet/AspNetCore#7737]
We did a security audit with a pentest company and will be informed that the applications logout procedure is insufficient. They criticized that when you click on Logout, the cookie `.AspNetCore.Identity.Application` gets deleted on client-side, but the server-side session stays intact. They tested this by setting the original auth-cookie value manually after logout and got response from the server like being logged in.

### To Reproduce
Used version of ASP.NET Core: 2.2.

Code of the logout function:
```
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> LogOff()
{
	await _signInManager.SignOutAsync();
	HttpContext.Session.Clear();
	_logger.LogInformation(4, "User logged out.");

	return RedirectToAction("Index", "Home");
}
```

So what I am doing wrong and what is the correct way to logout?

**Comment by Tratcher** [comment]
You're not doing anything wrong. The normal logout procedure is cooperative, you ask the client to delete their cookie and they do. There is no "server-side [auth] session" here, it's all contained in the cookie. If your client has been compromised to the point where someone has captured their auth cookie then you have bigger problems than sign-out.

There are two alternate mechanics you could use here. 
1. Sign-out-everywhere. @HaoK where are the docs for this?
2. Use ITicketStore so the auth data really is stored on the server and you can clear it.

**Comment by ManuelHaas** [comment]
> If your client has been compromised to the point where someone has captured their auth cookie then you have bigger problems than sign-out.

Of course you're right, but in such a situation the user doesn't even have the chance to end a compromised session in which an attacker has taken over a session.

According to [OWASP Testing for logout functionality](https://www.owasp.org/index.php/Testing_for_logout_functionality_(OTG-SESS-006)) it should be done. The article also describes that ASP.NET does not.

@Tratcher Thank you for providing the hint to ITicketStore!

Perhaps a server-side ITicketStore implementation should be included in the project templates.

**Comment by blowdart** [comment]
Signout everywhere was never doc-ed, but it's just a matter of updating the security stamp.

As for server-side ticket stores, they're not template code because of the statefulness that entails and the work that would be needed for multiple instances.

**Comment by a-kaplan** [comment]
> 
> 
> > If your client has been compromised to the point where someone has captured their auth cookie then you have bigger problems than sign-out.
> 
> Of course you're right, but in such a situation the user doesn't even have the chance to end a compromised session in which an attacker has taken over a session.
> 
> According to [OWASP Testing for logout functionality](https://www.owasp.org/index.php/Testing_for_logout_functionality_(OTG-SESS-006)) it should be done. The article also describes that ASP.NET does not.
> 
> @Tratcher Thank you for providing the hint to ITicketStore!
> 
> Perhaps a server-side ITicketStore implementation should be included in the project templates.

Did you find a solution?

**Comment by sgopimca7** [comment]
Hi,

The ITicketStore was helping me to invalidate the server side, But can we able to avoid logout after iis restart?

Thanks and Regards,
Gopi.S
