### ISSUE TITLE
[Identity][UI] Register bugs

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#7738]
All these are Identity UI bugs

> 3. Enter email=a@b.com, password=111111, confirm=111111, click Register. You get redirected to `https://localhost:5001/Identity/Account/Register?returnUrl=%2Fauthentication%2Flogin`. 

**Rerrendering the register page causes the returnUrl to change format.**

> 4. Once again, enter email=a@b.com, password=111111, confirm=111111, click Register. This time you get redirected to `https://localhost:5001/Identity/Account/Register`. Again I don't know why the URL has changed format. **Bug 1: the `returnUrl` information has been lost**

**The return url gets lost when clicking on the register link in the default identity UI. This needs to be preserved.**

> 5. This time, enter email=a@b.com, password=qqqQQQ111!, confirm=qqqQQQ111!, click Register. You get redirected to `https://localhost:5001/`, but it doesn't show you as logged in. **Bug 2: The nav menu still has links to "Register" and "Log in"**.

![image](https://user-images.githubusercontent.com/6995051/53088643-30954e80-34bf-11e9-8a21-2933de3ddabe.png)

**At this point the original flow is lost, so the identity UI simply redirects to '/' which is what it does by default when there is no returnUrl.**

> 6. Click on "Register". It shows you are actually logged in (in the title, it says `Hello a@b.com`), but **bug 3: it still lets you register an account while you are already logged in**.

This happens because at this point you are in the identity UI (server-side redered app and not the spa).
We should probably not let a user register while already logged in. You've always been able to it the Register endpoint for as long as I can remember no matter whether you were logged in or not. @blowdart In case you want to chip in.

The differences in login behavior displays happen because of the way things work on SPAs. To make it easier to understand, think of the identity UI as your Microsoft Account. 
You can be logged in your MS Account but not on your SPA. Because one uses an http-only cookie and the other one uses a jwt stored in local storage to determine whether you are logged in or not. What makes it confusing in this case is that the IdP lives on the same app as the SPA, so it's bound to have some issues there.

When you click login on your spa, if you already have logged in on your Microsoft Account you don't introduce credentials and you get redirected back to your app automatically.

_Originally posted by @SteveSandersonMS in https://github.com/aspnet/AspNetCore/pull/7721#issuecomment-465521943_

**Comment by SteveSandersonMS** [comment]
I'm assuming it's intentional that there's no corresponding `--auth Individual` for the Redux template.

**Comment by javiercn** [comment]
@SteveSandersonMS Yeah, we're not doing it right now.

**Comment by blowdart** [comment]
This is in the spa pieces? 

I'm not so concerned about registration if you're already logged in, because we don't have an opposite to AllowAnonymous. It'd be a nice to have. Ditto for flowing a return URL during registration.

**Comment by javiercn** [comment]
@blowdart Yes. When you click register I redirect you back to /authenticate/login which does a silent log in and syncs the state. The returnUrl needs to be preserved across the flow. The alternatives are zillion times more complicated (ask B2C) or we simply remove the registration button and you have to click extra things.

I find the current experience way more 1st party, and keeping the return url is cheap.

**Comment by prince272** [comment]
I've rewritten the Asp Core Identity for Mvc. Feel free to take a look at https://github.com/prince272/AspCoreIdentityMvc

Simply change the url for the area 'Identity' to 'IdentityMvc' and you'll be automatically directed to the Mvc version for Identity.

**Comment by blowdart** [comment]
@javiercn this is rather old, does the problem still exist? If is it UI improvements, or does it need server side code changes too?

**Comment by javiercn** [comment]
We need to change the UI. I plan to do a pass on this this week to do final UI cleanups+switching to PKCE.

**Comment by javiercn** [comment]
Took care of this as part of https://github.com/aspnet/AspNetCore/pull/11227. Will close when it gets merged.
