### ISSUE TITLE
LongPolling requests to include Keep-alive header

### ISSUE THREAD

**Issue by jamesgloverlandmarkcouk** [aspnet/AspNetCore#7741]
### Describe the bug
We have been trying to implement Azure SignalR Service using @aspnet/signalr however the duration of the LongPolling requests (90 secs) exceeds that allowed by our corporate proxy (60 secs) and the connections are terminated, breaking the SignalR connection to Azure. We are able to successfully send messages to the client only within this initial 60 second window.
Our previous implementation of SignalR (which uses uses JQuery.signalR talking to SignalR running on an Asp.Net backend) works through the proxy, this appears due to Keep-Alive headers on the LongPolling requests 

### To Reproduce
1. Using @aspnet/signalr 1.1.2 and Azure SignalR Service
2. Implement the client side code as per the examples with LongPolling (see attached)

### Expected behavior
SignalR LongPolling to be agnostic of client corporate proxies, ideally in the same manner as the library we currently use, or another method.
We are unable to mandate to our customers the setup of their networks.
Please advise if there is already a way to do this with this library.

### Screenshots
![image](https://user-images.githubusercontent.com/7113972/53097753-205e8d00-351a-11e9-8947-b26eb542dfa3.png)
Sample of our application. The same code works fine when directly connected to the internet.

**Comment by BrennanConroy** [comment]
You can change the poll timeout on your server to be less than the proxy timeout.
https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.2#advanced-http-configuration-options
```
MapHub<hub>(options =>
{
    options.LongPolling.PollTimeout = ...;
});
```

**Comment by jamesgloverlandmarkcouk** [comment]
Hi Brennan,
Thank you for your response. I should have mentioned on the original post that we are trying to implement the Rest API for Azure SignalR Service on the backend, and currently have no hub classes we can use to set configuration (our web server is not on .net core). How would we go about changing these settings?

https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-rest-api

Thanks,
James

**Comment by jamesgloverlandmarkcouk** [comment]
We're going to put in a middle layer that allows us access to the configuration mentioned.
