### ISSUE TITLE
View Components flush early

### ISSUE THREAD

**Issue by fatagun** [aspnet/AspNetCore#7742]
is it possible to flush view component result early?

https://www.stevesouders.com/blog/2009/05/18/flushing-the-document-early/

Currently my page is blocked trying to render 5-6 view components, i would like to flush them early then fill it up.

Is that possible in .net core mvc?

**Comment by pranavkm** [comment]
Flushing inside partials or view components doesn't write to the response stream. You can try doing a `FlushAsync` from the page that invokes the view component. 
e.g.

```C#
@await Component.InvokeAsync("SomeComponent")
@await FlushAsync()
```

One caveat here is that that doing a `FlushAsync` from a Razor file would mean that the file cannot have a `Layout` page associated with it. Layouts require the entirety of the page content to be buffered, and flushing early prevents that.
