### ISSUE TITLE
w3wp.exe crashes | Faulting module name: KERNELBASE.dll, Exception code0xc0000005

### ISSUE THREAD

**Issue by r4nc1d** [aspnet/AspNetCore#7743]
### Describe the bug
Updated our application to use ASP.NET Core 2.2, was running fine till the w3wp.exe just crashes
Restarted the application pool and the site seems fine again.

Faulting application name: w3wp.exe, version: 10.0.14393.0, time stamp: 0x57899b8a
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2758, time stamp: 0x5c304900
Exception code: 0xc0000005
Fault offset: 0x0000000000047db0
Faulting process id: 0x40ec
Faulting application start time: 0x01d4c9298d67fcb6
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: f73d033f-46ee-4f24-8eb9-d96c5419cac0
Faulting package full name: 
Faulting package-relative application ID: 

### To Reproduce
1. Cant seem to recreate it, might be intermittent

### Expected behavior
The  w3wp.exe not to crash

### Screenshots
![error](https://user-images.githubusercontent.com/5917232/53101262-147ec500-3532-11e9-974d-2cc6ea4676da.jpg)

### Additional context
Include the output of `dotnet --info`

**Comment by dharmenbavaria** [comment]
As you are hosting this in IIS, did you check app pool recycle settings. Probably you would see this error when the app pool gets recycled, by default its set 29 hours.

**Comment by r4nc1d** [comment]
Yes i am hosting in IIS, also i know about the app pool being recycled, the weird thing is just the app pool never started again. I had to manually start the app pool again.

**Comment by anurse** [comment]
Hey, apologies for the delay. Are you still seeing this issue? Would you be able to collect a process memory dump and share it with us? (I can provide a contact email)

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
