### ISSUE TITLE
Thread leak in asp.net core 2.1

### ISSUE THREAD

**Issue by dharmenbavaria** [aspnet/AspNetCore#7744]
### Describe the bug
We have an issue with one of our asp.net core web api project. We have a scalable application so it runs in multiple instance we have 2 problems:

1) Once in a while sometimes with one instance we have thread count running from 100 - 1000 within a second. And in the process the number of thread count if i see it in graph and it also increase memory resident size byte. 

2) And the thread count once goes higher it doesn't decrease until you terminate those instance. 

We are monitoring the active thread from the process of dotnet.exe.

We have set ThreadPool.SetMinThread(1000).

### To Reproduce
We created a dump out of the process and tried to analyze it but we see lots of threads (800+) with following stack 
00 00000026`185fef58 00007fff`06273acf ntdll!NtWaitForSingleObject+0x14
01 00000026`185fef60 00007ffe`fe9953cb KERNELBASE!WaitForSingleObjectEx+0x8f
02 00000026`185ff000 00007ffe`fe9f3f9b coreclr!CLRSemaphore::Wait+0x63 [e:\a\_work\2188\s\src\vm\synch.cpp @ 581] 
03 00000026`185ff0c0 00007ffe`fe9acf20 coreclr!ThreadpoolMgr::UnfairSemaphore::Wait+0x13b [e:\a\_work\2188\s\src\vm\win32threadpool.h @ 327] 
04 00000026`185ff120 00007ffe`fea4b2cb coreclr!ThreadpoolMgr::WorkerThreadStart+0x3c0 [e:\a\_work\2188\s\src\vm\win32threadpool.cpp @ 2137] 
05 00000026`185ff1e0 00007fff`07f28364 coreclr!Thread::intermediateThreadProc+0x8b [e:\a\_work\2188\s\src\vm\threads.cpp @ 2594] 
06 00000026`185ffa20 00007fff`098ae851 kernel32!BaseThreadInitThunk+0x14
07 00000026`185ffa50 00000000`00000000 ntdll!RtlUserThreadStart+0x21

Those threads are just stuck and doing nothing. The parallel stack looks like below
![image](https://user-images.githubusercontent.com/20542961/53102009-2872f880-352b-11e9-9e8b-d2c206553410.png)

I have also attached the unique stack of threads where you would find 604 threads had same stack trace.
[dump_uniq_stack.txt](https://github.com/aspnet/AspNetCore/files/2885184/dump_uniq_stack.txt)

And as we are using StackExchange.Redis sometimes we have redis timeout because these threads are just blocked those instance with higher number of threads starts throwing redis time out error because they dont have enough threads to serve.

### Expected behavior
If i understand clearly when the number of requests go down i would expect number of thread count go down but it doesn't.

### Screenshots

I dont have much idea of debugging more than this but we have this problem every now and then. I would really appreciate if someone could have a look into it and help with this.

Thanks in advance.

**Comment by davidfowl** [comment]
I don't see a leak per se, but maybe you have some blocking code that caused the thread pool to quickly inject threads (like blocking calls to .Wait or .Result) up to the ~600 or so threads that are allocated in the picture above. Setting min threads to 1000 means that the thread pool will inject aggressively up to 1000 threads but it would only do that if you encounter a burst of traffic or if you're blocking other thread pool threads.

It looks like you captured a dump when the activity on those threads died down and so they're just waiting for the thread pool to drain. If you can capture a dump when the thread pool is ramping up, that would be helpful. If you remove the min threads setting, the problem may show up more obviously as the thread pool will very slowly inject threads and you can capture a process dump to see what's happening.

> 2\. And the thread count once goes higher it doesn't decrease until you terminate those instance.

The threads allocated should get released back to the pool if there's no work after some time.

**Comment by dharmenbavaria** [comment]
@davidfowl thanks for the quick response. But i wanted to understand would that create a problem if those 600 threads are just waiting for the thread pool to drain? I have checked all our apis with ben blocking detector but i didn't show any blocking call. And if it so blocking or waiting it should have occured with other instances also right? But i only see one out of 15 instances.

**Comment by dharmenbavaria** [comment]
@davidfowl  any suggestions? We are still having this problem.

**Comment by MarioHewardt** [comment]
Can you load the dump and send the output of:
> .symfix
> .reload
> .loadby sos coreclr
> ~*e!ClrStack

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
