### ISSUE TITLE
Enable ValidateOnBuild by default in developlemnt environment

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7745]
https://github.com/aspnet/Extensions/blob/master/src/DependencyInjection/DI/src/ServiceProviderOptions.cs#L25

cc @davidfowl

**Comment by davidfowl** [comment]
Assiging to myself in preview6

**Comment by DamianEdwards** [comment]
Let's dooooooooooo it

**Comment by davidfowl** [comment]
This is done in the generic host, should we do this in the WebHost as well? I think we should leave the web host as is for compatiblity reasons. Basically treat it like a legacy API for the most part. 

cc @Tratcher

**Comment by anurse** [comment]
Agreed, it seems like since it's already done for generic host (which is the new regular) I think we can consider this done.
