### ISSUE TITLE
Helix test failure not showing as failure

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#7746]
The logs are located at:
https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190219.46/workItem/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests-netcoreapp3.0/wilogs

Looks like an exception during test discovery is treated as a skipped test, so tests just silently don't run.

cc @pakrym

**Comment by pakrym** [comment]
cc @HaoK

**Comment by HaoK** [comment]
Hrm that's not good, I'll take a look

**Comment by HaoK** [comment]
@BrennanConroy can you see if adding the following to your PRs `eng/helix/vstest/run.cmd` fixes the issue for you?

``` // Add these 3 lines
%HELIX_CORRELATION_PAYLOAD%\sdk\dotnet vstest %target% -lt >discovered.txt
find /c "Exception thrown" discovered.txt
if %errorlevel% equ 0 exit 1

// Original last line
%HELIX_CORRELATION_PAYLOAD%\sdk\dotnet vstest %target% --logger:trx
```

**Comment by BrennanConroy** [comment]
That didn't help https://github.com/aspnet/AspNetCore/pull/8048

**Comment by HaoK** [comment]
I'll take another look tomorrow

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/AspNetCore/pull/8107
