### ISSUE TITLE
Integration TestServer with Generic IHostBuilder

### ISSUE THREAD

**Issue by Fearware** [aspnet/AspNetCore#7754]
### Problem
Hi,

I've updated my website with .Net Core 3.0 preview 2 and I want to make Integration Test with a `TestServer`. In .Net Core 2.2, I've been able to make it using `WebApplicationFactory<Startup>`

I've asked this question on Stackoverflow (https://stackoverflow.com/questions/54792658/net-core-integration-testserver-with-generic-ihostbuilder) and an user replied to me that the feature looks like it does not exist yet. 

As we can see here (https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/TestHost/src/WebHostBuilderExtensions.cs), TestServer only takes IWebHostBuilder parameters, but it's about to be deprecated (https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio).

I'm new to .Net Core and I don't know if there is a new way of doing it.
Thanks for your answers!

If there's not a new way :

### Solution
Add to `TestServer `or  `WebApplicationFactory<TEntryPoint>` functions that accepts the new Generic IHostBuilder as parameters so we can continu to create easy test servers for integration tests.

### Alternatives 
Create a new class `WebApplicationFactory` that accepts the new IHostBuilder.

### Additional context
Here is the code that worked in 2.2 (From Ardalis):

```
public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<Startup>
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureServices(services =>
            {
                // Create a new service provider.
                var serviceProvider = new ServiceCollection()
                    .AddEntityFrameworkInMemoryDatabase()
                    .BuildServiceProvider();

                // Add a database context (ApplicationDbContext) using an in-memory 
                // database for testing.
                services.AddDbContext<ApplicationDbContext>(options =>
                {
                    options.UseInMemoryDatabase("InMemoryDbForTesting");
                    options.UseInternalServiceProvider(serviceProvider);
                });

                services.AddDbContext<AppIdentityDbContext>(options =>
                {
                    options.UseInMemoryDatabase("Identity");
                    options.UseInternalServiceProvider(serviceProvider);
                });

                services.AddIdentity<ApplicationUser, IdentityRole>()
                        .AddEntityFrameworkStores<AppIdentityDbContext>()
                        .AddDefaultTokenProviders();

                // Build the service provider.
                var sp = services.BuildServiceProvider();

                // Create a scope to obtain a reference to the database
                // context (ApplicationDbContext).
                using (var scope = sp.CreateScope())
                {
                    var scopedServices = scope.ServiceProvider;
                    var db = scopedServices.GetRequiredService<ApplicationDbContext>();
                    var loggerFactory = scopedServices.GetRequiredService<ILoggerFactory>();

                    var logger = scopedServices.GetRequiredService<ILogger<CustomWebApplicationFactory<TStartup>>>();

                    // Ensure the database is created.
                    db.Database.EnsureCreated();

                    try
                    {
                        // Seed the database with test data.
                        var userManager = scopedServices.GetRequiredService<UserManager<ApplicationUser>>();
                        AppIdentityDbContextSeed.SeedAsync(userManager).GetAwaiter().GetResult();
                    }
                    catch (Exception ex)
                    {
                        logger.LogError(ex, $"An error occurred seeding the database with test messages. Error: {ex.Message}");
                    }
                }
            });
        }
    }
```
Here is my new `Program.cs` file from my Website.

```
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
```

And finaly, here are the errors that all my tests return :

```
 System.InvalidOperationException : No method 'public static IWebHostBuilder CreateWebHostBuilder(string[] args)' found on 'CompX.Web.Program'. Alternatively, WebApplicationFactory`1 can be extended and 'protected virtual IWebHostBuilder CreateWebHostBuilder()' can be overridden to provide your own IWebHostBuilder instance.
Arborescence des appels de procédure :
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateWebHostBuilder()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at CompX.FunctionnalTest.Web.Models.Validations.AccountModelsFunctionalTest..ctor(CustomWebApplicationFactory`1 factory, ITestOutputHelper output) in c:\Users\SamuelJacques\Documents\Programming\GitRepo\CompX\Tests\CompX.FunctionalTest\Web\Models\Validations\AccountModelsFunctionalTest.cs:line 29
```

**Comment by Tratcher** [comment]
TestServer was already updated in https://github.com/aspnet/AspNetCore/pull/6585 for preview2.

**Comment by mkArtakMSFT** [comment]
@Tratcher is there anything else pending here?

**Comment by Tratcher** [comment]
No, just making sure they can use the new setup.

**Comment by Fearware** [comment]
Alright Tratcher,

Thanks a lot. 
I was looking for an issue, but I wasn't able to find it.

Since I can't work on it for the next 3-4 days, I'll close this issue and use what you gave me. 
Atleast, now I have something to refer to !
Once I'll have a solution, I'll post it as an anwer on my stackoverflow question.

Thanks  again ! 👍

**Comment by benmccallum** [comment]
Managed to use the `WebApplicationFactory` abstraction in one instance, builds but tests fail, prob my issue though.

But for another test class, it was using `.CreateWebSocketClient` which seems to be gone. Will research that now :P

**Comment by Tratcher** [comment]
@benmccallum The calling pattern is different.
https://github.com/aspnet/AspNetCore/blob/a4d9faefe2ed6fbebd500413032336607ec92778/src/Hosting/TestHost/test/TestServerTests.cs#L51-L64

**Comment by benmccallum** [comment]
Ahh, thanks @Tratcher! That's got me further and saved me, as I'd gotten blocked again as the Startup being used was a local class, not part of a real app, so I wouldn't have been able to use the factory abstraction in this case anyway.
