### ISSUE TITLE
Synchronous code switching to other task within lock(...) context after TaskCompletionSource.TrySetResult

### ISSUE THREAD

**Issue by joshlang** [aspnet/AspNetCore#7775]
### Describe the bug
Code within a synchronous void method is being preempted in favour of another task when TaskCompletionSource.TrySetResult is called.  This renders code protected by lock(…) ineffective.

### To Reproduce
1. Blazor 0.7.0 admittedly, one version behind.  .NET Core 2.1.

See this code below.  It's extracted from a JavascriptWebSocket thing we're building:

```
public class EvilJavaScriptWebSocket
{
    readonly Queue<MemoryStream> Messages = new Queue<MemoryStream>();
    TaskCompletionSource<MemoryStream> NextStream;
    MemoryStream CurrentMessage;

    [JSInvokable]
    public void OnMessageOK(string s)
    {
        var ms = new MemoryStream(Encoding.UTF8.GetBytes(s));
        lock (Messages)
        {
            var next = NextStream;
            if (next != null)
            {
                NextStream = null;  /// OK, because called before TrySetResult
                next.TrySetResult(ms);
            }
            else
            {
                Messages.Enqueue(ms);
            }
        }
    }
    [JSInvokable]
    public void OnMessageDIES(string s)
    {
        var ms = new MemoryStream(Encoding.UTF8.GetBytes(s));
        lock (Messages)
        {
            if (NextStream != null)
            {
                NextStream.TrySetResult(ms);  /// This method STOPS at this location and control is transferred to ReceiveAsync, below.
                NextStream = null;     /// This code gets executed later.
            }
            else
            {
                Messages.Enqueue(ms);
            }
        }
    }
    public async Task<int> ReceiveAsync(ArraySegment<byte> buffer)
    {
        if (CurrentMessage == null)
        {
            Task<MemoryStream> getMessageTask = null;
            lock (Messages)
            {
                if (Messages.Count > 0)
                {
                    CurrentMessage = Messages.Dequeue();
                }
                else
                {
                    NextStream = new TaskCompletionSource<MemoryStream>();
                    getMessageTask = NextStream.Task;
                }
            }
            if (getMessageTask != null)
            {
                CurrentMessage = await getMessageTask;
            }
        }

        var toWrite = (int)(CurrentMessage.Length - CurrentMessage.Position);
        if (toWrite > buffer.Count)
        {
            toWrite = buffer.Count;
        }

        CurrentMessage.Read(buffer.Array, buffer.Offset, toWrite);

        return toWrite;
    }
}
```

ReceiveAsync is called in a loop.

The expected flow:
- ReceiveAsync has no messages. Creates a TaskCompletionSource and awaits on it.
- OnMessage fires.  It sees the TaskCompletionSource, calls TrySetResult and sets it to null.
- ReceiveAsync resumes
- Loop back to top

The actual flow:
- ReceiveAsync has no messages. Creates a TaskCompletionSource and awaits on it.
- OnMessage fires.  It sees the TaskCompletionSource, calls TrySetResult and [INTERRUPTED]
- ReceiveAsync resumes
- (loop) ReceiveAsync has no messages.  Creates a TaskCompletionSource and awaits on it.
- [CONTINUED FROM INTERRUPTION] OnMessage continues by setting the TaskCompletionSource to null
- Future OnMessage events fire but it's too late, the TaskCompletionSource is null and it just queues messages, and ReceiveAsync never completes.

Being synchronous code, I would have thought the lock(…) statements are sufficient protection against this sort of stuff.

**Comment by rynowak** [comment]
Have you tried using `new TaskCompletionSource<object>(TaskCreationOptions.RunContinuationsAsynchronously)` ? https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcreationoptions?view=netframework-4.7.2#System_Threading_Tasks_TaskCreationOptions_RunContinuationsAsynchronously

It's valid for `TrySetResult` to *run other code* by default.

If you're running this on the server in response to a JS call then there's a few things you should know...
- Components on the server run in a sync context because it's a UI framework - so you might want locking in this context, but if this object is tied to a single *circuit*/connection then you might not have any reason for it.
- If you want to offload some CPU-intensive processing (out of the UI loop) for a set of components, then you might want to make use of `Task.Run(...)`.

**Comment by joshlang** [comment]
Holy moly what a gotcha :D  You're right.  I've found other instances of SetResult/TrySetResult which result in synchronous execution of OTHER code.  

Restructuring the code is an appropriate workaround.  I appreciate the options and quick response.  Thanks!  Will close this.

**Comment by Eilon** [comment]
@joshlang I get paid per tag so I'm not removing it! 😄
