### ISSUE TITLE
DefaultHttpResponse.StartAsync without feature

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#7778]
If there is no `IHttpResponseStartFeature` then `StartAsync` will call `Body.FlushAsync` every time. Should it only call `Body.FlushAsync` if `HasStarted` is false?

https://github.com/aspnet/AspNetCore/blob/25f1f593783de4819a1e8e30dc09af7388cc68b3/src/Http/Http/src/Internal/DefaultHttpResponse.cs#L147-L155

**Comment by jkotalik** [comment]
Yeah I'd be fine with that change.

**Comment by jkotalik** [comment]
Going to put this in preview3 for now (it's a 1 line fix). @muratg are we still fine to merge into preview3 or does it require approval?

**Comment by muratg** [comment]
@jkotalik would require approval. cc @Eilon

**Comment by Eilon** [comment]
Why do we need it in preview3? What doesn't work that would affect a customer trying preview3?

**Comment by jkotalik** [comment]
We don’t need it, I didn’t know what the new cut line was. We can do this in preview 4 no problem.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Eilon** [comment]
If it's not a critical need or preview 3 then I wouldn't bother and just go with `master`.

**Comment by jkotalik** [comment]
We decided to keep the flush behavior, but we should still check IsStarted too.
