### ISSUE TITLE
Standalone app fails to run "Failed to create CoreCLR"

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#7782]
### Describe the bug
Standalone publishing of aspnet apps appears to be broken on macOS, might be broken on other platforms too. This error doesn't appear in simple console app projects.

### To Reproduce
1. Download latest NET Core 3.0 Preview 3 SDK
1. `dotnet new web -o webapp1/`
1. `dotnet publish -r osx-x64 webapp1/`
2. Run the app `./bin/Debug/netcoreapp3.0/osx-x64/webapp1`

### Expected behavior
Web app should run.

### Actual

```
Failed to create CoreCLR, HRESULT: 0x80070057
```

corehost trace: 
[corehost.log.txt](https://github.com/aspnet/AspNetCore/files/2887804/corehost.log.txt)

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010336
 Commit:    cd75d80883

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /Users/namc/Downloads/dotnet-sdk-latest-osx-x64/sdk/3.0.100-preview3-010336/

Host (useful for support):
  Version: 3.0.0-preview3-27420-6
  Commit:  512360041a

.NET Core SDKs installed:
  3.0.100-preview3-010336 [/Users/namc/Downloads/dotnet-sdk-latest-osx-x64/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview3-19120-02 [/Users/namc/Downloads/dotnet-sdk-latest-osx-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27420-6 [/Users/namc/Downloads/dotnet-sdk-latest-osx-x64/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

cc @Eilon  - seems like something that would block release.

**Comment by Eilon** [comment]
@natemcmaster - does this seem likely to be an ASP.NET Core issue, an SDK/publish issue, or something else?

**Comment by natemcmaster** [comment]
It's sort of an SDK problem, but might require us to change aspnet packaging. The SDK is still using runtime.osx-x64.Microsoft.AspNetCore.App, not Microsoft.AspNetCore.App.Runtime.osx-64. The runtime.osx-x64.Microsoft.AspNetCore.App contains the NuGet placeholder file (`_._`) which the SDK is treating as if it is a .dll.

<img src="https://user-images.githubusercontent.com/2696087/53146487-3e97ad80-3559-11e9-894f-d114f1e364b0.png" width="300" />
[webapp1.deps.json.txt](https://github.com/aspnet/AspNetCore/files/2887848/webapp1.deps.json.txt)

cc @dsplaisted @nguerrera

**Comment by natemcmaster** [comment]
Btw, this would affect all non-Windows platforms.

**Comment by Eilon** [comment]
OK let's see what we find by early-ish tomorrow. Presumably the AspNetCore.App package is legal to have the `_._` file because that's been a NuGet thing since nearly forever so I'd like to see if this is just a case that isn't handled in the SDK/publish layer.

I'm also not sure how common self-contained apps are and how risky a late fix would be. If preview 3 ships with this scenario broken it'd be for only a relatively short time until preview 4 ships so we'd have to balance that as appropriate.

**Comment by dsplaisted** [comment]
This should be a simple fix in the SDK.  We just need to add the `_._` file to [this list](https://github.com/dotnet/sdk/blob/release/3.0.1xx/src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs#L70-L73) of files ignored from the runtime pack.

I've sent https://github.com/dotnet/sdk/pull/2972 to add test coverage of this scenario, and once I've verified that it fails on Mac and Linux in CI, I'll update the PR to include the code fix.

**Comment by Eilon** [comment]
Thanks @dsplaisted !

**Comment by Eilon** [comment]
@natemcmaster - do we still need this issue or will @dsplaisted 's fix resolve this for us?

**Comment by natemcmaster** [comment]
@dsplaisted's fix works. No changes should be necessary in aspnet. I'd like to leave this open to confirm this works with the next rebuild of the SDK.

**Comment by natemcmaster** [comment]
Tested with 3.0.100-preview3-010351 and confirmed standalone for macOS works.
