### ISSUE TITLE
[Blazor] TypeDescriptor is not working

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#7784]
### Describe the bug
I'm trying to use **TypeDescriptor** for conversion between value types but it is not working in Blazor project. As soon as I try to use it it will break and raise an exception. In the example bellow the second `Console.WriteLine` is never called.

### To Reproduce
```
class ValueConverter<TValue>
{
    public TValue Convert( object value )
    {
        try
        {
            Console.WriteLine( "before" );
            TypeConverter conv = TypeDescriptor.GetConverter( typeof( TValue ) );
            Console.WriteLine( "after" );

            return (TValue)conv.ConvertFrom( value );
        }
        catch
        {
            Console.WriteLine( $"error: {value}" );
            Console.WriteLine( exc.ToString() );
            return default;
        }
    }
}
```

### Exception Stack Trace

> WASM: System.MissingMethodException: Constructor on type 'System.ComponentModel.Int32Converter' not found.
> components.webassembly.js:1 WASM:   at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) <0x1de9a28 + 0x00348> in <f586e15a10164c1cb6ac0e5b3b50dd23>:0 
> components.webassembly.js:1 WASM:   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) <0x1ddf940 + 0x000de> in <f586e15a10164c1cb6ac0e5b3b50dd23>:0 
> components.webassembly.js:1 WASM:   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture) <0x22e6cd0 + 0x0002a> in <f586e15a10164c1cb6ac0e5b3b50dd23>:0 
> components.webassembly.js:1 WASM:   at System.SecurityUtils.SecureCreateInstance (System.Type type, System.Object[] args, System.Boolean allowNonPublic) <0x22e6bf0 + 0x0009c> in <485de8e868c44158864a67df7e8a64c8>:0 
> components.webassembly.js:1 WASM:   at System.SecurityUtils.SecureCreateInstance (System.Type type) <0x22e6b18 + 0x0000c> in <485de8e868c44158864a67df7e8a64c8>:0 
> components.webassembly.js:1 WASM:   at System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance (System.Type objectType, System.Type callingType) <0x22e1b90 + 0x0003c> in <485de8e868c44158864a67df7e8a64c8>:0 
> components.webassembly.js:1 WASM:   at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable (System.Collections.Hashtable table, System.Type callingType) <0x22e1608 + 0x002f0> in <485de8e868c44158864a67df7e8a64c8>:0 
> components.webassembly.js:1 WASM:   at System.ComponentModel.ReflectTypeDescriptionProvider+ReflectedTypeData.GetConverter (System.Object instance) <0x22c3400 + 0x00188> in <485de8e868c44158864a67df7e8a64c8>:0 
> components.webassembly.js:1 WASM:   at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter (System.Type type, System.Object instance) <0x22c2cc8 + 0x00022> in <485de8e868c44158864a67df7e8a64c8>:0 
> components.webassembly.js:1 WASM:   at System.ComponentModel.TypeDescriptor+TypeDescriptionNode+DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetConverter () <0x22c2a00 + 0x00042> in <485de8e868c44158864a67df7e8a64c8>:0 
> components.webassembly.js:1 WASM:   at System.ComponentModel.TypeDescriptor.GetConverter (System.Type type) <0x22c7e18 + 0x00014> in <485de8e868c44158864a67df7e8a64c8>:0 
> components.webassembly.js:1 WASM:   at Blazorise.JSRunner+<>c__DisplayClass10_0`1[TValue].<GetSelectedOptions>b__0 (System.String value) [0x0000d] in D:\Projects\Other\Blazorise\Source\Blazorise\JSRunner.cs:96

**Comment by rynowak** [comment]
I think it's definitely the case that the linker is trimming this out. The specific type `Int32Converter` is getting trimmed by the linker because it's not used directly by any code. 

One workaround you could use it to set `<BlazorLinkOnBuild>false</BlazorLinkOnBuild>` in the project file. This will turn off linking, which will increase the size of the app. A more desirable thing would be to change the settings to include the type converters. 

@javiercn any ideas?

**Comment by miroslavp** [comment]
I declared static variables like this to prevent IL stripping:

        private static readonly Int32Converter i32c = new Int32Converter();
        private static readonly Int64Converter i64c = new Int64Converter();
        private static readonly StringConverter sc = new StringConverter();
        private static readonly NullableConverter nc = new NullableConverter(typeof(bool?));
        private static readonly BooleanConverter bc = new BooleanConverter();

@rynowak @javiercn 
Any better solution for this?

> A more desirable thing would be to change the settings to include the type converters.

Where can I find those settings?

**Comment by javiercn** [comment]
@SteveSandersonMS Can users still add a custom descriptor file to tweak the linking process?

**Comment by SteveSandersonMS** [comment]
Yes, but weirdly the docs for that feature seem to have been deleted. I found an old copy in Git history here: https://github.com/aspnet/Blazor.Docs/blob/7ced0029b97b3b8afdda4e2a235bd6cecebfc2fd/docs/host-and-deploy/configure-linker.md

@danroth27 Do you know why that was removed? Also on https://blazor.net/, the "docs" link in the header goes to a 404, and there's still the "experimental" tag in the top right.

**Comment by danroth27** [comment]
> weirdly the docs for that feature seem to have been deleted. @danroth27 Do you know why that was removed?

The IL linker doc is here: https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/configure-linker

> Also on https://blazor.net/, the "docs" link in the header goes to a 404

I'm not seeing this. When I click on Docs I get redirected to https://docs.microsoft.com/aspnet/core/blazor/

> there's still the "experimental" tag in the top right.

That's expected for now
