### ISSUE TITLE
Windows builds failing to install node

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7797]
https://dev.azure.com/dnceng/public/_build/results?buildId=102471
```
##[error]Unable to find Node version '10.x' for platform win32 and architecture ia32.
```

cc @natemcmaster

**Comment by natemcmaster** [comment]
Yeah, just noticed it. I wonder if NodeJS published a new version today, but not for win32. 10.x grabs the latest version.

**Comment by natemcmaster** [comment]
Hmm, that's not it. Maybe this is machine-specific? Some PR build steps are passing.

**Comment by natemcmaster** [comment]
Sent mail to dnceng. Seems like some agents run as x86, and there isn't a way to force the node installer task to acquire x64 (https://github.com/Microsoft/azure-pipelines-tasks/issues/6671)

**Comment by natemcmaster** [comment]
Closing in favor of https://github.com/dotnet/core-eng/issues/5285
