### ISSUE TITLE
[Components] Figure out layering on the server

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#7807]
We want MVC and Components.Server to play nice together.
* MVC has a basic (non-interactive) prerender
* Components.Server has a nicer prerenderer (that supports interactivity).
* We want Components.Server to take over transparently.

They both end up needing some sort of shared abstraction that defines "prerrendering".

* We can leave Components referencing MVC (as it does today).
* We can invert the relationship and have MVC reference components.Server
* We can put the abstractions in Microsoft.AspNetCore.Components but that limits the expressiveness and doesn't apply to WebAssembly scenarios.
* We can create a new assembly that is where the shared abstractions between the server components live.
   * Microsoft.AspNetCore.Components.Http
   * Microsoft.AspNetCore.Components.Core
   * Microsoft.AspNetCore.Components.Html
   * Microsoft.AspNetCore.Components.Prerendering

**Comment by javiercn** [comment]
We discussed this at length and we decided on the following.
* There will be two separate gestures for rendering components from an MVC page/view:
  * "static rendering": Using a component as a partial.
  * "interactive rendering": Prerending some content + reconnecting to the content.

* MVC will have it's own internal mechanism for performing "static rendering".
* MVC will not have out of the box will not have it's own mechanism for "interactive rendering".
* We will create a new library Microsoft.AspNetCore.Mvc.Prerendering that will reference both MVC and Components.Server and will include a couple of extension methods on HTML Helper that can be used for performing "interactive rendering".
  * This library will be part of the shared framework, so it's available to users without anything magic.
  * This library will simply contain a couple of HTML helpers for doing the interactive prerendering.
  * The html Helpers in this library will rely on an abstraction that lives in Components.Server to perform the prerendering and will resolve it from DI or throw otherwise with a clear exception message informing the user that they need to call AddComponents()

**Comment by rynowak** [comment]
Sounds right 👍

**Comment by mkArtakMSFT** [comment]
@javiercn, is there anything pending here? If so, please update the post to reflect on it.
