### ISSUE TITLE
[Templating] Reenable popup authentication on the SPA templates

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#7811]

**Comment by mkArtakMSFT** [comment]
@blowdart should we really do this?

**Comment by blowdart** [comment]
I have no context or, more likely, can't remember why, it was disabled in the first place.

**Comment by brockallen** [comment]
Make sure you test in edge and/or IE.

**Comment by javiercn** [comment]
We are not doing this as per our discussion it’s broken on IE/Edge and would require support from the client library.

The code in the template is commented so as to make this easy to do in the app if the user decides to do so, but we don’t plan to do any work here other than update the oidc library version.
