### ISSUE TITLE
About every third https request to my api takes up to 60 seconds to start executing post method

### ISSUE THREAD

**Issue by josephldooley** [aspnet/AspNetCore#7819]
### Describe the bug
I send a post request to my api using postman. The first few requests get responses in about 1- 2 seconds, after that the next request takes up to 60 seconds before responding. I placed a break point at the start of my method with the HttpPost attribute. The breakpoint is not hit for those 60 seconds so this leads me to believe the timing issues is bettween sending the https request and before the relate method executes. 

### To Reproduce
1. Using this version of ASP.NET Core '1.1'
2. Run this code '
                [HttpPost]
		public JsonResult Post(string key)
		{
                       return Json(-1);
                 }'
3. With these arguments 'https://win2k8JD/myservice/api?key=123'
4. Im using nginx as a reverse proxy configured for https, and I'm also using Kestrel

### Expected behavior
fast responses from my asp.net core api (not 60 seconds of wait before my code starts executing

### Screenshots
![image](https://user-images.githubusercontent.com/13750034/53203414-1a8aa980-35f7-11e9-83be-520eee32a3f4.png)

**Comment by anurse** [comment]
> 4\. Im using nginx as a reverse proxy configured for https, and I'm also using Kestrel

Does this delay also occur when running directly against Kestrel? Or is it only when running through nginx?

**Comment by josephldooley** [comment]
I don't really remember its been awhile since I fixed the issue. I think was a mix of bad setup on both nginx and the kestrel, like urls redirection, or using 302 instead of 307 when sending a post request.

**Comment by anurse** [comment]
Ok, well glad it got resolved in the end. Sorry for the delay!
