### ISSUE TITLE
Add More SignalR Manual Testing Scenarios

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#7820]
We recently added our first manual testing scenario for SignalR and it would probably be a good idea to get more scenarios in. We have a .NET client set up and usage test but that is with an already deployed server.
We should add coverage for setting up and configuring a SignalR server, and using the JavaScript and Java clients as well. I imagine we could start with basic scenarios at first and then discuss what we want to make sure get testing manually since there are a lot of code paths.

**Comment by anurse** [comment]
We created issues for the core scenarios we want to explore. Feel free to open new ones if we find new things to test.
