### ISSUE TITLE
startvs.cmd loads the solution in VS2017 not VS2019

### ISSUE THREAD

**Issue by adrianwright109** [aspnet/AspNetCore#7824]
**N.B.**
I already have Visual Studio 2017 (version 15.9.7) and Visual Studio 2019 preview (version 16.0.0 Preview 3) installed; running on Windows 10 Pro 64-bit.

**Steps to reproduce issue:**
1. Clone the `https://github.com/aspnet/AspNetCore` repo and checkout the `master` branch.
2. Run the command `PS> .\eng\scripts\InstallVisualStudio.ps1` to install VS 2019 preview 3 with the required workloads.
3. Run the command `PS> .\restore.cmd` to build the entire repo.
4. Run the command `PS> .\src\Components\startvs.cmd` to open the `Components.sln` solution in Visual Studio.

**Expected Result:**
`Components.sln` solution opens in Visual Studio 2019 preview 3 (as Visual Studio is a prerequisite for this repo)

**Actual Result:**
`Components.sln` solution opens in Visual Studio 2017 with the following error message:
![image](https://user-images.githubusercontent.com/47532258/53205398-1a55d280-3626-11e9-9f24-78a9aa7ded1f.png)

**BTW**
I have just tried opening up the `Components.sln` solution manually by double-clicking on the `Components.sln` file and it again loads in Visual Studio 2017.

There is a workaround for this:  Open Visual Studio 2019 first and load the solution file directly from within Visual Studio.

**Comment by Eilon** [comment]
Tagging @natemcmaster FYI

**Comment by jkotalik** [comment]
I think you need to swap the default program for the .sln extension. Information here: https://support.microsoft.com/en-us/help/4028161/windows-10-change-default-programs.

You can also set the default extension to open the Visual Studio version selector which will allow you to open either 2017 or 2019.

**Comment by Eilon** [comment]
Yeah the VS Solution Version Selector is the right thing to do. Aren't things normally routed through that? Maybe this was just 'forced' the wrong way on @adrianwright109 's machine?

**Comment by adrianwright109** [comment]
I checked my Windows 10 Default App settings for `.sln` files and it is explicitly set to Visual Studio 2019:
![image](https://user-images.githubusercontent.com/47532258/53238039-2e361e80-3690-11e9-80ec-cb4ec9814b6c.png)

This doesn't seem to be honoured.

I have since change the setting to:
![image](https://user-images.githubusercontent.com/47532258/53238164-7c4b2200-3690-11e9-93c4-dba08c6d50ce.png)

and the `Component.sln` solution is now opening up correctly in Visual Studio 2019 by either method; `startvs.cmd` or by manually double-clicking on the `Components.sln` file.

**Comment by natemcmaster** [comment]
Sounds like you found a solution (pun intended). Thanks for sharing your findings.
