### ISSUE TITLE
Expose MVC JSON formatter using UTF8JsonReader/Writer (System.Text.Json)

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#7837]
cc @rynowak @mkArtakMSFT 

As UTF8 is the only supported encoding, we will create the UTF8JsonReader/Writer if the passed in encoding is UTF8, otherwise we will use a stream.

**Comment by davidfowl** [comment]
Closing as dupe of https://github.com/aspnet/AspNetCore/issues/7256
