### ISSUE TITLE
[Helix] Add equivalent of OSSkipOnHelix

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#7848]
Currently SkipOnlyHelix has no way to target only a specific OS

**Comment by pakrym** [comment]
Why don't we use the existing OSSkip attribute?

**Comment by HaoK** [comment]
Sure that wouldn't be too bad, add some kind of Helix flag on OSSKip you mean?

**Comment by pakrym** [comment]
Why do we need to skip an OS only on helix?

**Comment by HaoK** [comment]
I guess if helix becomes the only way we run CI tests, maybe we don't, so maybe this is a point in time issue only, but right now I can't use the OSSkip attribute since that will disable the tests for the official CI runs (and local runs too).  There's no way to skip tests only on specific helix queues right now, its all only for all helix queues

**Comment by HaoK** [comment]
i.e. for this current logged test failure, I would ideally be able to slap on a `SkipOnHelix(TargetOS = Windows)` or something.  I've resorted to just disabling the entire test projects on helix instead which isn't ideal since its basically all tests in most of these projects

**Comment by HaoK** [comment]
Added ability to target a specific queue for now, can revisit in the future if we need to target a platform instead
