### ISSUE TITLE
fatal error LNK1181 inprocessapplication.obj

### ISSUE THREAD

**Issue by itarsonmg** [aspnet/AspNetCore#7850]
### Describe the bug
when compile AspNetCore\src\Servers\IIS\build.cmd a fatal error LNK1181 inprocessapplication.obj

###Solution
Change into  IIS\AspNetCoreModuleV2\CommonLibTests\CommonLibTests.vcxproj  <Link><AdditionalLibraryDirectories>..\InProcessRequestHandler\\$(Configuration)\;</AdditionalLibraryDirectories> 
by:
Change  <Link><AdditionalLibraryDirectories>..\InProcessRequestHandler\Win32\\$(Configuration)\;</AdditionalLibraryDirectories> 
when $(Plattform) is Win32
In Lines:102 and 158

**Comment by muratg** [comment]
@jkotalik Have you seen this?

**Comment by jkotalik** [comment]
Yeah this repros. I think it was due to moving to     <PlatformToolset>v142</PlatformToolset>. Will fix shortly.
