### ISSUE TITLE
Data Protection and Key Vault possible key caching issue

### ISSUE THREAD

**Issue by januszj** [aspnet/AspNetCore#7853]
### Describe the bug
With configuration described in documentation, you can unprotect content without providing name of the key and vault that was used to protect it.
This was detected in Azure function that used many keys to protect different customers data. 

### To Reproduce
1. Using this version of ASP.NET Core '2.2'

2. Use this code 

```
serviceCollection.AddDataProtection()
                    .PersistKeysToAzureBlobStorage(azureKeyContainer, "keys.xml")
                    .ProtectKeysWithAzureKeyVault($"https://{vault}.vault.azure.net/keys/{nameOfKey}", clientId, clientSecret)
                        .UseCryptographicAlgorithms(
                            new AuthenticatedEncryptorConfiguration()
                            {
                                EncryptionAlgorithm = EncryptionAlgorithm.AES_256_CBC,
                                ValidationAlgorithm = ValidationAlgorithm.HMACSHA256
                            });
```

Also I created console repo for easy reproduction here:
https://github.com/januszj/DataProtectionKeyVaultRepo

3. With these arguments '....'
Use above code to encrypt payload with Data Protection.
Then decrypt payload using any name of vault or nameOfKey they don't need to exists in Azure.

Operation will succeed.

### Expected behavior
Operation should fail. It seems that Data Protection do not use provided key name of Key Vault but rather use directly cached key from storage.
I would expect that payload protected by particular key in Data Protection should be unprotected only using this key when configuring Data Protection using ProtectKeysWithAzureKeyVault.

**Comment by blowdart** [comment]
So yes, because the key name is embedded in the file. This is the expected behaviour, the key you specify in config is the one used for wrapping new keys. Otherwise how would you rotate the key in keyvault without having to update your code? Or decrypt data after a key has expired?

This won't change.
