### ISSUE TITLE
[Templating][SPA] NPM Package Developer Workflow

### ISSUE THREAD

**Issue by kemmis** [aspnet/AspNetCore#7854]
When using the asp.net core 2.1/2.2 Angular Web App Template (File > New Project > Cloud Section > ASP.NET Core Web Application > Angular), I've run into some issues where when a new npm package is added to the project by another developer and the package.json file changes are checked in, then when other developers pull those changes and try to build/run the app, the new package doesn't get installed automatically. The app builds and runs, but the app pukes at the point where the typescript tries to build. In order to make it work you have to run npm install manually so it installs the latest packages.

My questions: What is the intended workflow for this scenario? Should the project or visual studio automatically install missing packages at some point?

One thing I just noticed is that some of us have the "Restore On Project Open" and "Restore On Save" options turned off for NPM in Visual Studio. Is this feature required to make the package install functionality automatic with the SPA Angular template?

**Comment by danroth27** [comment]
There is tooling support for NPM in Visual Studio, but it currently it only works if the package.json file is in the root of the project. In the ASP.NET Core SPA templates the package.json file is in the ClientApp folder with the rest of the code generated using the CLI for the corresponding SPA framework. We're investigating if we can update the VS tooling to work with this setup.
