### ISSUE TITLE
[Blazor] Error when running two server-side Blazor project one after the other with the same browser cache

### ISSUE THREAD

**Issue by darren-zdc** [aspnet/AspNetCore#7857]
I upgraded my previous two server-side projects to Blazor 0.8.0. I believe everything I did everything correctly following the instruction. And I'm able to run the WebApp.

But I think there might be an issue when moving wwwroot from App project to server project...

I have a vs solution which holding two Server-side blazor projects. The only difference between these two projects is they are using different CSS library. 

Then, when I run my first app, it runs perfectly.  However, when I run my second Blazor project right after I end the first one, it causes a problem. They are using the same wwwroot folder, which is the same as my first Blazor project. That because working when I do a browser reload. But, if I have two files with the same name inside the wwwroot/js folder, it won't reload the file in the newest wwwroot folder. 

I'm kinds of new in Blazor, any helps will be appreciated!!

**Comment by darren-zdc** [comment]
Updated: 
Previously using Chrome, still not working when doing a browser reload.
Now, I try to use Firefox, page reload will renew the file will the same name,

**Comment by darren-zdc** [comment]
I think I find the problem. But that problem does not happen in Blazor 0.7.

Because I use the localhost to run the app, Chrome is saving the cache data. So, the next time I run in the other project, they will use the same cache. 
But I'm not sure how to fix it cleanly

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @darren-zdc.
We're going to address this as part of https://github.com/aspnet/AspNetCore/issues/6349 work.
