### ISSUE TITLE
Override Span Writes in PagedBufferedTextWriter

### ISSUE THREAD

**Issue by DaniilSokolyuk** [aspnet/AspNetCore#7858]
Please override Span Writes in [PagedBufferedTextWriter](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.ViewFeatures/src/Buffers/PagedBufferedTextWriter.cs), [default implementations on TextWriter](https://github.com/dotnet/corefx/blob/7817a109400b5b22c02ae6667706cda8a7f3d168/src/Common/src/CoreLib/System/IO/TextWriter.cs#L184) is using ArrayPool for temp array.

I propose to add such a method in [PagedCharBuffer](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.ViewFeatures/src/Buffers/PagedCharBuffer.cs) and use it in PagedBufferedTextWriter
```
        public void Append(ReadOnlySpan<char> buffer)
        {
            if (buffer.Length > 0)
            {
                var index = 0;
                var count = buffer.Length;

                while (count > 0)
                {
                    var page = GetCurrentPage();
                    var copyLength = Math.Min(count, page.Length - _charIndex);

                    buffer
                        .Slice(index, copyLength)
                        .CopyTo(new Span<char>(page, _charIndex, copyLength));

                    _charIndex += copyLength;
                    index += copyLength;
                    count -= copyLength;
                }
            }
        }
```

PagedBufferedTextWriter passes to custom IHtmlContent implementations

**Comment by pranavkm** [comment]
The type's internal and it's unlikely we'd continue using it when working with `BodyPipe`. The recommendation would be to copy the file to your application and modify it as you see fit.

**Comment by DaniilSokolyuk** [comment]
@pranavkm, I do not understand, this is mvc views area, not servers.
Why should I copy it into my application? I and others uses IHtmlConent for custom Html helpers in views, and current implementation are not great
