### ISSUE TITLE
Kestrel not accepting single LF as end-of-line marker

### ISSUE THREAD

**Issue by paaland** [aspnet/AspNetCore#7860]
### Describe the bug
Kestrel not accepting single LF as end-of-line marker. The W3C standard suggest that CR LF is the correct end-of-line marker, but that a single LF should also be accepted.

I have some hardware that sends with LF only, and kestrel fails with:

info: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HLKOPR61MCQ9" bad request data: "Invalid request line: 'POST /query/001A0400EA7E HTTP/1.1\x0A'"
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line: 'POST /query/001A0400EA7E HTTP/1.1\x0A'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectRequestLine(Byte* requestLine, Int32 length)

### To Reproduce
Run an asp.net core 2.x api service served by kestrel and send only LF as line delimiter in http header.

### Expected behavior
Should support both CR LF and single LF as W3C standard suggests.

RFC2616 states at the beginning of Section 2.2 (Basic Rules (!)), quite unambiguously:
    CR = <US-ASCII CR, carriage return (13)>
    LF = <US-ASCII LF, linefeed (10)>

HTTP/1.1 defines the sequence CR LF as the end-of-line marker for all protocol elements except the entity-body

However, recognizing that people will break the standard for whatever purposes, there is a "tolerance provision" in Section 19.3 (note that it re-iterates the correct sequence):

The line terminator for message-header fields is the sequence CRLF. However, we recommend that applications, when parsing such headers, recognize a single LF as a line terminator and ignore the leading CR.

**Comment by blowdart** [comment]
Given than allowing LF into a poorly written app could end up with response splitting vulnerabilities I'm dubious about this from a security perspective. Is it only headers where your hardware is being non-compliant? I assume as it's hardware you can't update it because of age or some other reason?

**Comment by paaland** [comment]
It's only the headers. And yes, upgrading the firmware is costly and not really an option. Has been running for years against and old ASP.net 2.0 endpoint in IIS, which apparently is more flexible regarding http standard. Trying to move to containers and .net core made us aware of this problem. 

Is there any way to intercept the request and modify the headers in middelware of even override the httpparser in kestrel? If not we'll have to see if sticking nginx as a reverse proxy in front might clear up the headers.

**Comment by blowdart** [comment]
We could make it an option, with suitable warnings.

@halter73 / @Tratcher would a middleware help as a temporary bandaid here? Any pointers?

**Comment by Tratcher** [comment]
No, middleware is too late, kestrel is rejecting the requests.

**Comment by benaadams** [comment]
The parser is a property on `ServiceContext` rather than a fixed thing; but the `KestrelServer` constructor that takes on is `internal` (used for tests)

**Comment by benaadams** [comment]
e.g.  the `IHttpParser<Http1ParsingHandler>` *could* be added as a Parser as a property on `KestrelServerOptions` then used [if set in `CreateServiceContext`, rather than always newing up a new one](https://github.com/aspnet/AspNetCore/blob/f19e8da1daf2808f3bbb870141304b73e76a547a/src/Servers/Kestrel/Core/src/KestrelServer.cs#L56-L101); if you wanted to go that way

**Comment by paaland** [comment]
Either that or some compatibility flag to allow LF only would be great. Injecting your own httpParser implementation would be more flexible and even allow for header rewrites etc.

**Comment by muratg** [comment]
Triage: we do not plan to support this. Just curious, what client are you supporting?
