### ISSUE TITLE
Our contributing guidelines don't work when JS is involved

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#7862]
### Describe the bug

Components.sln requires you to have already built the javascript project at src\Components\Browser.JS

It looks like these `npmproj` instance don't participate in the build. The build will fail looking for `components.server.js`

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1566	Error reading resource '_framework\components.server.js' -- 'Could not find a part of the path 'C:\git\aspnet\AspNetCore\src\Components\Browser.JS\src\dist\components.server.js'.'	Microsoft.AspNetCore.Components.Server	C:\git\aspnet\AspNetCore\src\Components\Server\src\CSC	1	Active

```

### To Reproduce

`git clean -xdf` in `src\Components\Browser.JS\src`
Follow the instructions here: https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#building-in-visual-studio
`startvs.cmd src\Components\Components.sln`

Do a build - it will fail with an error message 

### Expected behavior

The build works

## Workaround

The workaround is go to the `Browser.JS` directory and `dotnet build`.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, we'll need some help here with making this build-able.

**Comment by ryanbrandenburg** [comment]
This is no longer the error that happens when you try to follow these instructions. Instead you get:
```
Could not copy the file "D:\dd\AspNetCore\src\Servers\IIS\AspNetCoreModuleV2\InProcessRequestHandler\bin\Debug\Win32\aspnetcorev2_inprocess.dll" because it was not found.	Microsoft.AspNetCore.Server.IIS	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4560
```
and
```
No template files found.	Microsoft.VisualStudio.BlazorExtension	D:\dd\AspNetCore\src\Components\blazor\BlazorExtension\src\Microsoft.VisualStudio.BlazorExtension.csproj	88
```
which seem to be a problem in how the dependencies of `Microsoft.AspNetCore.Server.IIS` and `BlazorExtension` are being pulled in rather than a "build-system" problem.

CC @jkotalik

**Comment by jkotalik** [comment]
Pretty sure it's just a props file missing. I'll investigate.

**Comment by jkotalik** [comment]
Nvrm, I don't believe this ever worked. The problem is that the M.A.Server.IIS packages expects both 32 and 64 bit dlls to be built, which requires you to build the sln with both bitnesses. I'm trying to understand what the differences are between build.cmd vs sln build here.

**Comment by mkArtakMSFT** [comment]
The original issue is fixed. If there is something else pending here, pleas reopen a new issue.
