### ISSUE TITLE
[Templating] add missing favicon.ico to Components template

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#7876]
This prevent's a 500 in the components template for preview3.
The issue is problematic because it causes an exception to be thrown which in debugging it causes the debugger to stop hence degrading the experience.
This fixes the problem for preview3 for favicon.ico (other not found files would keep having this issue) but it can be worked around with a bit of code if needed.

Other templates have this file already, for this same reason.

**Comment by pranavkm** [comment]
Verified the added favicon prevents 500s.
