### ISSUE TITLE
ASP .NET MVC Core 2.2 - ViewComponent's Invoke() oddly genarates an InvalidOperationException after upgrading from Core 2.0

### ISSUE THREAD

**Issue by Slupov** [aspnet/AspNetCore#7892]
### Describe the bug
I am develeping an online store where I've got a ViewComponent that is used to render a shopping cart html in the website's navigation bar.

I render the view component in the shared _Layout.cshtml by doing this:

`@await Component.InvokeAsync("NavbarShoppingCart")`

It used to work fine under MVC Core 2.0 but since I upgraded to 2.2 the same code throws an InvalidOperationException:

> InvalidOperationException: Method 'Invoke' of view component 'ProjectName.Web.Views.Shared.NavbarShoppingCartViewComponent ' cannot return a Task.

Here is the ViewComponent class:

```
public class NavbarShoppingCartViewComponent : ViewComponent
    {
        private readonly IShoppingCartManager shoppingCartManager;

        public NavbarShoppingCartViewComponent(IShoppingCartManager shoppingCartManager)
        {
            this.shoppingCartManager = shoppingCartManager;
        }

        public IViewComponentResult Invoke()
        {
            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();
            var items = this.shoppingCartManager.GetCartItems(shoppingCartId);

            return View("NavbarShoppingCart", items.Count());
        }
    }
```
The Invoke() method clearly returns a View, not a Task. I don't get it why this throws an error now.
I have not changed any code, only upgraded the .net core version from 2.0 to 2.2. Any ideas for the source of the problem?

### To Reproduce
1. Upgrade from Core 2.0 to 2.2

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84
![68c7b419ec7a3d19b319f58febcc9c81](https://user-images.githubusercontent.com/15180413/53285446-2c8c5980-3769-11e9-8322-c305414be648.png)

**Comment by pranavkm** [comment]
@Slupov could you share an application that reproduces the issue? I'm unable to duplicate it.

**Comment by pranavkm** [comment]
Feel free to reopen once you've an repro application to share.
