### ISSUE TITLE
The MVC URL generation with nonexisting controller or action is not working

### ISSUE THREAD

**Issue by BBGONE** [aspnet/AspNetCore#7893]
### Describe the bug
The MVC URL generation with nonexisting controller or action stopped working in ASP.NET Core 2.2

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run this code

In any HTML page with the Razor try to get the URLs for these routes

 ```
 var existing_action_url = '@Url.Action("ExistingAction", "ExistingController")';
 var nonexisting_action_url = '@Url.Action("NonExistingAction", "NonExistingController")';
```

The existing_action_url  will be normally formed as expected
but the nonexisting_action_url  will be empty.

### Expected behavior

Expected to create the URL for  the nonexisting_action_url

### Additional context
In previous version ASP.NET core 2.1 the mapping worked, but after upgrading to ASP.NET Core 2.2.0
the mapping stopped working.
I used it to get the URL to a SignalR hub, which is without controller

**Comment by BBGONE** [comment]
Also i can not get an url for the URL mapping
 routes.MapRoute(
                    name: "signalr",
                    template: "{action}");

Getting URL for this Route using  '@Url.RouteUrl("signalr", new { action = "quotes"})';
is not working

**Comment by Tratcher** [comment]
@JamesNK

**Comment by JamesNK** [comment]
This is a change in behavior with endpoint routing. You can read more here: https://github.com/aspnet/AspNetCore/issues/4468

**Comment by BBGONE** [comment]
> 
> 
> This is a change in behavior with endpoint routing. You can read more here: #4468
Thanks, looks like it was deliberate feature. Although, i don't understand why it was needed. It complicates testing and i can not find the reason to introduce this breaking change.
the generated URLs should be based on the registered routs, not on the presence of a controller or an action. 
It could be implemented as a nonbreaking change, by enabling this feature on demand.

**Comment by BBGONE** [comment]
> 
> 
> This is a change in behavior with endpoint routing. You can read more here: #4468

Thanks, looks like it was deliberate feature. Although, i don't understand why it was needed. It complicates testing and i can not find the reason to introduce this breaking change.
the generated URLs should be based on the registered routs, not on the presence of a controller or an action. 
It could be implemented as a nonbreaking change, by enabling this feature on demand.

**Comment by BBGONE** [comment]
At least this new endpoint routing can be implemented without breaking URLs generation.
You just need to mark that the route is mapped to a valid endpoint and to use only these routes for processing requests, but to use all the routes (valid or not) for URLs generation.

**Comment by rynowak** [comment]
This behavior change has been reverted in 3.0 - conventional routes (`MapRoute`) will be highly compatible with how they worked in 2.1
