### ISSUE TITLE
Make IUrlHelper injectable.

### ISSUE THREAD

**Issue by FilipVanBouwel** [aspnet/AspNetCore#7900]
The IUrlHelper interface is currently not injectable through the build-in DI system. This makes it so we have to revert to solutions like [this](https://codeopinion.com/generating-links-with-urlhelper-outside-of-asp-net-core/) or [this](https://benfoster.io/blog/injecting-urlhelper-in-aspnet-core-mvc). It would be extremely handy to just be able to inject a IUrlHelper into your own classes that always works (like in an email sender that needs links to views/pages).

**Comment by danroth27** [comment]
On .NET Core 2.2 you can use `LinkGenerator`. Otherwise you need to inject `IUrlHelperFactory` and create one.

**Comment by RehanSaeed** [comment]
`LinkGenerator` has it's own problems. See https://github.com/aspnet/AspNetCore/issues/14192.
