### ISSUE TITLE
[Question] Where to find source code of Microsoft.AspNetCore.Authentication.AuthenticationOptions?

### ISSUE THREAD

**Issue by wutever0** [aspnet/AspNetCore#7901]
Sorry if this is a very basic question but I am still learning how to browse the source code on github and I spent few hours trying to look for the source of the **AuthenticationOptions** class.

Cannot find it in AspNetCore/src/Security/Authentication/Core/src/ where I was expecting it to be.

Thanks in advance!

**Comment by natery2000** [comment]
It is located here: 
AspNetCore/src/Http/Authentication.Abstractions/src/AuthenticationOptions.cs

**Comment by davidfowl** [comment]
@wutever0 pro-tip, you can press 't' to search for a file name on github:

![image](https://user-images.githubusercontent.com/95136/53302233-3c5f7880-3811-11e9-80ea-e1a82eb5369d.png)

**Comment by RemiBou** [comment]
You can also use https://source.dot.net/

**Comment by wutever0** [comment]
Thank you guys very useful tips!
