### ISSUE TITLE
[Blazor] SimpleJson serializes Dictionary as if collection of KeyValuePair

### ISSUE THREAD

**Issue by markdchurchill** [aspnet/AspNetCore#7908]
### Describe the bug
In a *web assembly Blazor* client, when posting a model containing a simply keyed dictionary (eg: string, T) to the server using PostJsonAsync(...),  the member is serialized as a collection of KeyValuePair.

> {"myDictionaryMember":[{"key":"1","value":{...}},{"key":"2","value":{...

This prevents round-tripping of a shared model.

### To Reproduce
With a type such as:

````
class Bar { public string Title { get; set; } }

class Foo 
{
   public Dictionary<string, Bar> Bars { get; set; }
}
````

Post this type from a Blazor client, and examine the F12 network stuffs.

### Additional context
This looks like a known issue with SimpleJSON.

There are several workarounds, but this is something that probably should 'just work'.

1. Separate models for posting.
2. Custom converters for JSON.Net to handle this server side - gets complex as you can't put attributes on a shared model.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @markdchurchill.
We plan to switch away from SimpleJSON and that will eliminate this issue.
