### ISSUE TITLE
Sending Image to Web API

### ISSUE THREAD

**Issue by ChethanNag** [aspnet/AspNetCore#7909]
I have a web API which takes image as input and saves the photo in some directory..
From web application controller i will get image and i need to send image to web API. 
How to achieve this using HttpClient ? 
Both web API and web Application are created in Dot net core 2.1

Below are the code details.
        
       **Web API code:**
            
       [Route("api/[controller]")]
       [ApiController]
       public class ImageTestController : ControllerBase
           {
               //Image upload
             [HttpPost]
          public async Task<string> ImageUpload([FromForm]IFormFile file)
                    {
                        if (file.Length > 0)
                        {
                            try
                            {
                                if (!Directory.Exists("actualpath"))
                                {
                                    Directory.CreateDirectory("actualpath");
                                }
                                using (FileStream filestream =   System.IO.File.Create("actualpath" + file.FileName))
                                {
                                    file.CopyTo(filestream);
                                    filestream.Flush();
                                    return file.FileName;
                                }
                            }
                            catch (Exception ex)
                            {
                                return ex.ToString();
                            }
                        }
                        else
                        {
                            return "Unsuccessful";
                        }
            
                    }
                }
            
            
            **web application controller**
        
           public class SampleController : Controller
            {
               [HttpPost]
               public ActionResult SavePhoto(IFormFile fileParameter)
                 {
                        //In fileParameter i will recieve the image
                     and i need to send this to Web API
                 }
            }
        
        **.cshtml : containing kendo UI upload control**
    
        <div class="demo-section k-content">
                    @(Html.Kendo().Upload()
                             .Name("files")
                             .HtmlAttributes(new { aria_label = "files" } )
                              .Multiple(false)
                              .Async(a => a
                    .Save("SavePhoto", "Sample")
                    .AutoUpload(true)
                    .SaveField("fileParameter")
                    
                    ))                       
        </div>

In the view , after image is taken from user ,it will hit to SavePhoto method in Sample controller. From controller i need code to send image to API. Finally i should be able to save the photo.

**Comment by blowdart** [comment]
Hi. It looks like this is a question about how to use  ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to   [StackOverflow](https://www.stackoverflow.com).  

Please consider tagging your StackOverflow question with  asp.net-core and/or asp.net-core-mvc.

**Comment by MovGP0** [comment]
seems like almost every line of code in this example should be improved. improper use of the API isn't an issue with the framework itself and therefore not an issue. 

I agree that such questions should be done on StackOverflow instead.

**Comment by MovGP0** [comment]
for reference: this is more or less how such a controller could be built: 

```csharp
// authenticate and authorize
[Authorize(...)]
// seal the class and only derive from what you need
public sealed class ImageUploadController : Controller
{
    // use logging (i recommend Serilog)
    // inject ILogger<ImageUploadController> for using the native ASP.NET logging infrastructure
    private static Serilog.ILogger Log => Seriog.Log.ForContext<ImageUploadController>();

    // use Dependency Injection
    public ImageUploadController(IConfiguration configuration)
    {
        Configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
    }

    private IConfiguration Configuration { get; }

    // define routes and HTTP methods
    [HttpPost("api/images")]
    // prevent cross site scripting attacks
    [ValidateAntiForgeryToken]
    // always return IActionResult; provide cancellation token, such that the client can cancel the request
    public async Task<IActionResult> Post([FromForm]IFormFile file, CancellationToken cancellationToken)
    {
        // validate the model
        if (!ModelState.IsValid) return BadRequest(ModelState);

        // additional input validation
        if (file == null || file.Length <= 0) return BadRequest();

        try
        {
            // don't hardcode paths, but make them configurable
            var actualPath = Configuration["actualPath"];
            if (!Directory.Exists(actualpath))
            {
                // not sure if async is useful here; it's an I/O operation, but usually also fast, so not sure if creating a task makes sense here
                await Task.Run(() => Directory.CreateDirectory(actualpath));
            }

            // don't concatenate path-strings; always use Path.Combine
            // also the file name is not unique, use a hash of the file data or an unique ID (and check if the file already exists)
            var filePath = Path.Combine(actualpath, file.FileName);

            using (var filestream = System.IO.File.Create(filePath, 1024, FileOptions.SequentialScan)) // specify file options when creating a file for better performance
            {
                // use async/await such that the server can handle another request until the file is written
                await file.CopyToAsync(filestream, cancellationToken);
            } // close stream as early as possible; disposing also flushes

            // get the request url
            // and return the URL where the file can be retrived
            var fileUrlBuilder = new UriBuilder(httpContext.Request.GetEncodedUrl());
            fileUrlBuilder.Query = null;
            fileUrlBuilder.Fragment = null;
            fileUrlBuilder.Path = Path.Combine(fileUrlBuilder.Path, file.FileName);

            return Created(fileUrl.Uri); // HTTP Code 201 with URL to file
        }
        catch (Exception ex)
        {
            // log error and return HTTP Code 500 on Exceptions
            Log.Error(e, e.Message);
            return StatusCode(StatusCodes.Status500InternalServerError);
        }
    }
}
```

**Comment by danroth27** [comment]
Nothing to really address here so closing.
