### ISSUE TITLE
Data Protection key generation warnings should also happen on Kubernetes

### ISSUE THREAD

**Issue by DavidSimner** [aspnet/AspNetCore#7916]
### Background
The default behaviour of [ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction) is to create a data protection key ring when the web application starts.  It is documented [here](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings) that `When hosting in a Docker container, keys should be persisted in a folder that's a Docker volume (a shared volume or a host-mounted volume that persists beyond the container's lifetime) or in an external provider ...`

For users who don't read the extensive documentation, there is also a runtime check in `FileSystemXmlRepository` that logs a warning if the documentation hasn't been followed.

### Describe the solution you'd like
This feature request is about extending that existing check.

Currently, the check only checks for Docker, but there are many other container platforms, for example Kubernetes, which it doesn't currently detect, and therefore it doesn't generate the log entry on those platforms.

The impact this might have on users is that their keys are lost, or that each replica of the web application creates its own key, leading to a confusing situation where if the load balancer ever sends traffic to a different replica an error would occur.  I believe that the development work to implement this feature request is justified because of:
1. the severity of these impacts
2. plus because we are talking about the default behaviour here the likelihood is very high

The log entry is generated here: https://github.com/aspnet/AspNetCore/blob/def36fab1e45ef7f169dfe7b59604d0002df3b7c/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs#L37

And the test for Docker is here: https://github.com/aspnet/AspNetCore/blob/def36fab1e45ef7f169dfe7b59604d0002df3b7c/src/DataProtection/DataProtection/src/Internal/DockerUtils.cs#L96

The problem is that it tests for an internal implementation detail of Docker, whereas it would be better if that test was a more general test for containers.  An example might be to see if the environment variable `DOTNET_RUNNING_IN_CONTAINER` is set to `true`

### Describe alternatives you've considered
Re-designing the Data Protection system or changing its defaults would also be possible, but I think that the least intrusive solution is changing the detection code to show the existing log message when it is relevant.

**Comment by blowdart** [comment]
I'm not sure an environment variable would work, because someone would have to set it. We rely on environment detection because the user doesn't have to do anything for it to be right

**Comment by DavidSimner** [comment]
> I'm not sure an environment variable would work, because someone would have to set it. We rely on environment detection because the user doesn't have to do anything for it to be right

The environment variable I mentioned `DOTNET_RUNNING_IN_CONTAINER` is set in the `Dockerfile` when the official images are created, e.g. https://github.com/dotnet/dotnet-docker/blob/bdc1d62860375b94679244c8d295c10afd666b93/2.1/runtime-deps/stretch-slim/amd64/Dockerfile#L21

Because it's set in the `Dockerfile` a user wouldn't have to do anything for it to be present.

The comment when it's set -- `Enable detection of running in a container` -- explicitly says what the environment variable is to be used for, which exactly matches the use that this feature request would use it for.

**Comment by blowdart** [comment]
Ah if it's official images, then yea, sure. @muratg as Nate is now OOF who would you assign for this? In change size it's pretty small.

**Comment by muratg** [comment]
@blowdart What's the change proposed? To detect that we're running in a Docker container and do what? It's not guaranteed that a volume is attached, so we can't save the key there automatically.

Is the proposal to warn if we detect that we're running in a container? That should be a small change.

The correct change would probably be to detect that the keys are NOT saved in a attached volume and only warn in that case, but not sure how small that would be.

**Comment by blowdart** [comment]
@muratg fall back to ephemeral, and let that log message happen. Or make the detection in `FileSystemXmlRepository` warning more generic. So make AspNetCore/src/DataProtection/DataProtection/src/Internal/DockerUtils.cs more generic and have a container check, which looks for a published and documented environment variable. Kubernetes has some environment variables we can look for too, in addition to a generic one just for us.

Then talk to all the folks who publish our docker and kurbernetes recipes to make sure they're setting the environment variables to trigger the code.

**Comment by muratg** [comment]
So warn even if the user is doing the right thing per the doc? (i.e. configure to save the key to a volume attached while running under docker.)

cc @anurse @pakrym

**Comment by blowdart** [comment]
No, not if they're doing the right thing, because we have IsVolumeMountedFolder to avoid that.

**Comment by muratg** [comment]
@anurse we can discuss the timeline for this offline.

**Comment by blowdart** [comment]
It'd be nice to talk to the Windows container folks too, to fill in the missing bits for those. But only nice, not essential.

**Comment by anurse** [comment]
This seems straightforward assuming we're OK with just using the environment variable in the official image. It means that if someone builds a custom image and doesn't include the env-var they won't get the warning, but I think someone doing that is probably more advanced.

Seems reasonable and straightforward
