### ISSUE TITLE
Render Tag Helper String as HTML

### ISSUE THREAD

**Issue by fatagun** [aspnet/AspNetCore#7924]
We have lots of tag helpers and looking to allow other developers to try and create pages through a code editor, where they write some tag helper and upon submitting, we want to render the output. We want to create something like [w3][1]

Take the minimal example as in the asp.net docs as follows:

```
    public class EmailTagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            output.TagName = "a";
        }
    }
```

We have a code editor when the user writes:

    <email>foo@foo.com<email>

I want to execute this tag helper and render HTML string out of it which should be:

    <a>foo@foo.com</a>

Things can get really complex as you can imagine. 

Is there a way to render Tag Helper from string that comes from MVC controller?

I tried to render partial views and view components as string. But no luck. I tried using `Html.Raw()` with encoding and decoding but didnt help as well. 

Any ideas?

  [1]: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_default

**Comment by JeremyCaney** [comment]
@fatagun: So, basically, you want to be able to dynamically evaluate a string (in this case, provided by the controller as part of the model) as razor syntax and return the processed results, correct? Obviously, in this case, you’re primarily interested in rending tag helpers. But I imagine that any solution that dynamically evaluates a string as razor syntax would also include tag helpers.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @fatagun.
This is not something we plan to do. Hope @JeremyCaney's proposal will help to solve your problem.
