### ISSUE TITLE
Create endpoint routing alternatives for SpaFallback

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#7928]
We want to add some new functionality for the "SPA fallback" scenario based on endpoint routing.

Semantics:
- A *fallback* should match with the lowest priority by default
- A *fallback* should not match things that look like filenames

Scenarios (priority order):
- Use a static file as a fallback - `routes.MapFallbackToFile("index.html")`
- Use a Razor Page as a fallback - `routes.MapFallbackToController("Index", "Home")`
- Use an MVC action/controller as a fallback - `routes.MapFallbackToPage("/Index")`

We should also make a change to the exising spa fallback middleware so that it short circuits when the request has an endpoint. This will make it work with endpoint routing, even though we will recommend the new options.

**Comment by mkArtakMSFT** [comment]
Thanks Ryan!
