### ISSUE TITLE
Question: HttpClientHandler recycled even with traffic

### ISSUE THREAD

**Issue by vkukke** [aspnet/AspNetCore#7937]
We use HttpClientFactory to create HttpClient for our outgoing requests. During our performance run we noticed that even with continuous traffic, underlying TCP connections are being closed every 2 mins. While I understand the default handler lifetime is 2 mins we were not expecting this to recycle with traffic (and delivery resulting in success).  I'm assuming close to happen only with inactivity? 
Are we missing anything here? 

Code snippet of our outgoing request is as follows:-
```
using (HttpClient httpClient = this.httpClientFactory.CreateClient(<someId>))
{
   //deliver
}
```

So we are disposing httpClient (in one the docs, it was suggested that it was OK to close it as the underlying handler is shared and not necessarily disposed with httpclient). 

I then configured PrimaryHttpMessageHandler's lifetime (provided below) and did a another run and noticed very stable runs without TCP connection recycle.  Unfortunately I also happen to not dispose my httpClient object. Regardless I would like to understand what is the expectation. Should we be
disposing httpClient or not and / or configuring lifetime?

```
services.AddHttpClient("defaultwebhookclient").ConfigurePrimaryHttpMessageHandler(() =>
{
    return new HttpClientHandler();
}).SetHandlerLifetime(TimeSpan.FromHours(1));
```

What is the expectation and right way to do this? 

Environment
Linux container 

Our version info
Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by rynowak** [comment]
**I edited your code samples for readability**

> During our performance run we noticed that even with continuous traffic, underlying TCP connections are being closed every 2 mins. While I understand the default handler lifetime is 2 mins we were not expecting this to recycle with traffic (and delivery resulting in success).

This is entirely expected - when the threshold is reached we *retire* the currently activate client handler, and let it drain requests. 

One of the reasons why this might be *good* is that establishing new connections will check DNS again. If you're using a single *very long lived* connection you will not see DNS changes. (The definition of very long lived depends on your exact scenario).

If you care about connection lifetime management at this level of detail, I'd suggest consulting the various mechanisms that are available on the [handler itself](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs). The client factory is general purpose infrastructure and gives you less control than the handler implementation.

> Unfortunately I also happen to not dispose my httpClient object. Regardless I would like to understand what is the expectation

If you're using the client factory then the **only** effect of disposing `HttpClient` is to terminate any requests in progress with that `HttpClient` instance. A friend of mine [just blogged about this](https://www.stevejgordon.co.uk/httpclient-creation-and-disposal-internals-should-i-dispose-of-httpclient).

> Should we be disposing httpClient or not and / or configuring lifetime?

It does not matter if you dispose it or not. 

You can configure the lifetime if you have a reason to. There's a fundamental tradeoff between the cost of making new connections and the risk of missing a DNS update. You know your scenario better than I do 😆 

We try to pick a reasonable default for most scenarios. We don't set platform-specific defaults right now (we might in the future).

**Comment by vkukke** [comment]
I understand about being able to detect DNS changes early, but the current behavior is odd that it recycles even though there are no errors. I'm not sure then what is the purpose of HttpClientFactory.  
It seems to have a limited use case and not meant for scenarios where we are looking at a steady traffic stream.  Additionally creating a new connection seems extremely slow. Is that expected or new versions 
have improvements we can leverage?

I'll check about the handler controls you have pointed. Thanks!

**Comment by rynowak** [comment]
The factory provides a bunch of conveniences for creating clients that include logging by default, and use other message handlers to implement various cross-cutting policies.

It **also** provides lifetime management of the underlying handler, which is optional and can be turned off. In the time period where it was first created (2.0-2.1) there was no really good solution to these issues on linux with .NET. 

If you're *just* interested in having control over details of the connection lifetimes and not the majority of the functionality here then I think you'relooking for the APIs on `SocketsHttpHandler`. 

> Additionally creating a new connection seems extremely slow. Is that expected or new versions
have improvements we can leverage?

This is feedback for https://github.com/dotnet/corefx . The client factory doesn't implement HTTP for .NET, it is a framework built on top of what the BCL provides. 

I'm closing this since I think I've answered the questions here.
