### ISSUE TITLE
Libuv fails to open unix socket if started under load

### ISSUE THREAD

**Issue by sherlock1982** [aspnet/AspNetCore#7944]
### Describe the bug
Sometimes when Kestrel+Libuv transport with unix sockets is launched under load Kestrel doesn't serve requests.

### To Reproduce
1. Using version of .NET Core 2.1.6 and ASP.NET Core 2.2
2. hosting.json should contain something like this `"server.urls": "http://unix:/var/run/foo.socket"`
3. Nginx should be enabled as reverse proxy.
4. Start making requests to Nginx and start the project.
5. You will see that /var/run/foo.socket is created and Kestrel successfully started and initialized.

6. You will see that requests are not getting to Kestrel and end up with Nginx timeout

### Expected behavior
Requests should be processed by Kestrel.

**Comment by muratg** [comment]
Just to check, did you make sure you deleted the descriptor (`/var/run/foo.socket`) after failure?

Also, can you share your logs as well?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
