### ISSUE TITLE
QueryStringRequestCultureProvider and encoded urls not working correctly

### ISSUE THREAD

**Issue by zengouu** [aspnet/AspNetCore#7947]
QueryStringRequestCultureProvider does not seem to work correctly with encoded urls.
(at least in Assembly Microsoft.AspNetCore.Localization, Version=2.0.1.0)

I am using 2.0.1.0 version of Microsoft.AspNetCore.Localization and I've followed instructions from here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2 to implement query string based localization.

My Startup.cs contains following

```
			IList<CultureInfo> supportedCultures = new List<CultureInfo>
			{
				new CultureInfo( "en-US" ),
				new CultureInfo( "fi-FI" )
			};

			var requestLocalizationOptions = new RequestLocalizationOptions
			{
				DefaultRequestCulture = new RequestCulture( "fi-FI" ),
				SupportedCultures = supportedCultures,
				SupportedUICultures = supportedCultures,
				RequestCultureProviders = new List<IRequestCultureProvider>
				{
					// Order is important, its in which order they will be evaluated
					new QueryStringRequestCultureProvider(),
					new CookieRequestCultureProvider()
				}
			};

			app.UseRequestLocalization( requestLocalizationOptions );
```

I've also got Resources set for each controller and view.

When I start the project and go to following url:
_http://localhost:51346/account/login?culture%3Den-US_
the en-US culture is not set.

On the other hand if I go to:
_http://localhost:51346/account/login?culture=en-US_
everything works as expected

If in my controller I try to get culture from encoded url get it returns the default "fi-FI"

Is this intented behaviour?

**Comment by pranavkm** [comment]
This is expected. In the first case, you would have a `QueryString` entry with `key = "culture=en-US", value = ""`, which is not something localization looks for.
