### ISSUE TITLE
spa/npm with VS running as admin

### ISSUE THREAD

**Issue by rgroenewoudt** [aspnet/AspNetCore#7949]
### Describe the bug
I am unable to start my Angular/SPA project which uses npm when Visual Studio 2019 is running as administrator. This is required to deploy my projects to IIS.

### To Reproduce
1. Start VS2019 as Administrator
2. New ASP.NET Core Web Application project, choose Angular.
3. Debug project.
4. Error:
```
Now listening on: http://127.0.0.1:39986
Application started. Press Ctrl+C to shut down.
       Error: EPERM: operation not permitted, mkdir 'C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm'
```

### Additional context
- VS2019 Preview 3
- NodeJS: 11.10.0
- npm 6.8.0

**Comment by muratg** [comment]
Upgrade to 2.2.2. This is a known issue
