### ISSUE TITLE
WsFederation SaveTokens is not working

### ISSUE THREAD

**Issue by mindaugasdirg** [aspnet/AspNetCore#7955]
Hello,

I have tried setting `WsFederationOptions.SaveTokens = true` to get token in `AuthenticationProperties` but it is not being set in Asp.Net Core 2.0 or 2.1.

According to the documentation ([WsFederationOptions documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.wsfederation.wsfederationoptions?view=aspnetcore-2.1))  it should work, but it looks like this functionality is not implemented. In other Authentication models (OpenIdConnect, Oauth, JwtBearer) there is functionality to save tokens if `SaveTokens` is set to `true`. 

I can create pull request to implement it if you will be willing to review it. Or is there a reason why WsFederation does not have it?

**Comment by blowdart** [comment]
What tokens do you expect there to be in WSFed? The token is the identity, there aren't refresh or access tokens in WSFed.

**Comment by Tratcher** [comment]
This has been discussed before: https://github.com/aspnet/Security/issues/1716

**Comment by mindaugasdirg** [comment]
In app I was expecting to get the same token which `WsFederationMessage.GetToken()` returns.

If you prefer to leave SaveTokens options as it is in WSFederation now, maybe it would be good to clarify in WsFederationOptions documentation that this option is ignored.

**Comment by Eilon** [comment]
Let's override the property and:
1. Set `[EditorBrowsable(None)]`
2. Update the doc comment to say it's not supported
