### ISSUE TITLE
Add baseline version test to 2.2 branch

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#7969]
Related to: https://github.com/aspnet/AspNetCore/issues/7546
Need to add a test in the 2.2 Branch for the issue above. The project structure has changed so it couldn't just be merged forward. Will be adding the test in a new PR.

Conceptually the same as: https://github.com/aspnet/AspNetCore/pull/7627

**Comment by mikaelm12** [comment]
cc @dougbu @natemcmaster

**Comment by dougbu** [comment]
👍 note this is fairly urgent. We don't have much runway left even for test-only changes.

**Comment by mikaelm12** [comment]
Okay, I'll get the PR out today

**Comment by mikaelm12** [comment]
Done here: https://github.com/aspnet/AspNetCore/pull/7988
