### ISSUE TITLE
Fix Angular for 7 and SSR

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#7970]
It seems that [in this PR](https://github.com/aspnet/AspNetCore/pull/7721/files) we updated to Angular 7. In addition to being an unexpected change that would should verify the base experience of, we should also fix this for SSR (followed by [updating the documentation](https://github.com/aspnet/Docs/issues/8139)).

CC @mkArtakMSFT

**Comment by ryanbrandenburg** [comment]
As per https://github.com/aspnet/Docs/issues/8139#issuecomment-467613547 we'll want to remove snippets related to SSR instead. The doc work can come first.

**Comment by mkArtakMSFT** [comment]
Closing this as we do not want to rework this area again and again after Angular updates.
