### ISSUE TITLE
Re-enable rest of IIS tests on Helix

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7972]
There are 3 disabled currently:

`StartsWithDotnetInstallLocation`, `StartsWithPortableAndBootstraperExe` and `CheckMofFile`

**Comment by muratg** [comment]
@pakrym Will you get to this as part of your Helix work?

**Comment by pakrym** [comment]
This is a lower priority. I'll try to figure them out.

**Comment by anurse** [comment]
@jkotalik is reviewing flaky/skipped tests across servers right now.

**Comment by jkotalik** [comment]
I'll file three separate issues for these.
