### ISSUE TITLE
Add tests for Worker template

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#7974]
We added [a new template](https://github.com/aspnet/AspNetCore/tree/master/src/ProjectTemplates/Web.ProjectTemplates/content/Worker-CSharp), but it has no tests. Does it contain all the files we expect? Does it compile and run, much less produce the expected results? We have lots of infrastructure to make this easy. [Use this](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/test/MvcTemplateTest.cs#L19) as a template for how to use it to test running results. You can add "which files were produced" tests by just [adding entries here](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/test/template-baselines.json).

CC @muratg

**Comment by Tratcher** [comment]
@ryanbrandenburg already did most of this in #8628. I just need to re-enable the test now that the SDK has been updated.

**Comment by Tratcher** [comment]
Blocked by SDK issue: https://github.com/aspnet/AspNetCore-Internal/issues/2009#issuecomment-497166047
