### ISSUE TITLE
Unintended public APIs in SignalR: HubConnection.ResetSendPing/ResetTimeout

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#7977]
https://github.com/aspnet/AspNetCore/blob/9355c7c1a5bba8c745212ff1a0a768c976b20fc8/src/SignalR/clients/csharp/Client.Core/ref/Microsoft.AspNetCore.SignalR.Client.Core.netstandard2.0.cs#L40-L41

I don't think these were intended to be public. They aren't something we expect a user to call. They may need to be `internal` (via IVT) or something...

cc @halter73 @BrennanConroy @mikaelm12

**Comment by anurse** [comment]
If we can remove these in 3.0 that would be ideal, but if not we should put these on the track to removal...

**Comment by mikaelm12** [comment]
Yeah, I think these should be internal

**Comment by anurse** [comment]
If these shipped this way in 2.2 (or earlier) things get a little tricky :). I think these came from 2.2's client pinging work.

**Comment by halter73** [comment]
I doubt anyone calls these, so I think we should just make these methods internal for 3.0 and make a breaking change announcement. Obsoleting it for a release seems unnecessary.

**Comment by anurse** [comment]
I agree, but want to seek approval from @Eilon first ;)

**Comment by Eilon** [comment]
The only mentions on the internet of `ResetSendPing` I can find are of our own source code (incl. forks/copies). Go ahead with the breaking change. I'm not sure if an announcement is worthy because it is almost certainly just noise. But we could err on the side of caution and announce it anyway, just to be open.

**Comment by anurse** [comment]
I lean towards just putting out an announcement. The text would be something like:

These methods are for internal use only but were unintentionally made public in 2.2. We are making them private (as originally intended) in 3.0.

**Comment by mikaelm12** [comment]
I think that sounds reasonable. Err on the side of over communication

**Comment by mikaelm12** [comment]
Moving this up since the preview 4 window widened and we should try to get breaking changes in early.

**Comment by mikaelm12** [comment]
Announcement here https://github.com/aspnet/AspNetCore/issues/8543

**Comment by Eilon** [comment]
Actual announcement needs to go to Announcements repo. Otherwise most people won't see it. Then link from there to "discussion" issue in regular repo.

**Comment by halter73** [comment]
Just look at one of the other announcements and try to follow the same format and use the same tags. You can probably just use #8543 as the discussion issue. Make sure to lock the announcement.

**Comment by mikaelm12** [comment]
Yup. Filed the legit announcement this morning here: https://github.com/aspnet/Announcements/issues/349
Thanks!
