### ISSUE TITLE
Add tests for SPA authorization

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#7982]
We added [new options to our SPA templates](https://github.com/aspnet/AspNetCore/commit/ea9793412795bbbb9e717c9844972a5bb3bb6707), but it has no tests. Does it contain all the files we expect? Does it compile and run, much less produce the expected results? We have lots of infrastructure to make this easy. [Use this](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/test/MvcTemplateTest.cs#L19) as a template for how to use it to test running results. You can add "which files were produced" tests by just [adding entries here](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/test/template-baselines.json).

**Comment by javiercn** [comment]
This was done in preview4.
