### ISSUE TITLE
[Helix] Cors.FunctionalTest needs additional files to run on helix

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#7990]
This test needs more than just the sample destination/origin files it appears to run.  Whatever files it needs should be included in the publish directory for it to be running via dotnet vstest to work on helix.

The following changes will copy over the samples to the publish directory and find the files, but there were runtime errors related to npm after that

```
    <Compile Include="$(SharedSourceRoot)test\SkipOnHelixAttribute.cs" />
    <HelixContent Include="..\..\samples\SampleOrigin\**\*.*" LinkBase="SampleOrigin" />
    <HelixContent Include="..\..\samples\SampleDestination\**\*.*" LinkBase="SampleDestination" />

  // Inside of CorsMiddlewareFunctionalTest.CreateDeployments
            var samplesPath = SkipOnHelixAttribute.OnHelix() ? AppContext.BaseDirectory : Path.Combine(TestPathUtilities.GetSolutionRootDirectory("Middleware"), "CORS", "samples"); 
```

**Comment by HaoK** [comment]
Files such as project.json will likely need to be published as well

**Comment by mkArtakMSFT** [comment]
@HaoK what's the status of this? Seems like this hasn't been updated for a while.
I'm moving this to preview6, but if you have a PR ready to go - feel free to merge it and bring this back.

**Comment by natemcmaster** [comment]
Looks like this test project is one of many which require refactoring to work on Helix. cref https://github.com/aspnet/AspNetCore/issues/10268

**Comment by HaoK** [comment]
Closing since these tests were removed via https://github.com/aspnet/AspNetCore/pull/13826
