### ISSUE TITLE
React to semver v2 support change in core-setup

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCore#8001]
Epic https://github.com/aspnet/AspNetCore/issues/8833

Once https://github.com/dotnet/core-setup/issues/4795 is done, we'll need to react. (Assuming https://github.com/aspnet/AspNetCore/issues/3839 is not done before)

Related: https://github.com/aspnet/AspNetCore/issues/3839

**Comment by jkotalik** [comment]
This was done by https://github.com/aspnet/AspNetCore/commit/7a1a53d76d62783ae33f116309c5d3745f00dd94.
