### ISSUE TITLE
dotnet publish standalone is VERY slow

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#8012]
I'm not sure if this is an issue for the sdk, but dotnet publish --runtime win-x64 takes around 20 seconds on my dev machine for many samples. For music store, a majority of the time is spent publishing.

**Comment by Eilon** [comment]
The action item here is at least to get some data on where the time is spent, and then see if we need to redirect to other teams.

**Comment by HaoK** [comment]
Initial distilled diagnostic numbers for `dotnet publish -v diag` on various types of projects: -diag prints A LOT which is why everything is so slow.  

ResolveProjectReferences/our msbuild stuff seems to be the main culprit and belongs to us

# Publish target only times
`security Identity.ExternalClaims sample`: 297840 ms
`MusicStore` 256603 ms
`signalr SocialWeather sample`: 18251 ms
`servers SampleApp`: 7670 ms
`hosting Generic Host sample`: 7146 ms
`dotnet new mvc`: 3542 ms
`dotnet new razor`: 3017 ms
`dotnet new web`: 2340 ms

# Target Hall of Shame (Slowest 3 overall targets):
`Identity.ExternalClaims`
    250360 ms  GetCopyToPublishDirectoryItems            65 calls
    513493 ms  GetCopyToOutputDirectoryItems             65 calls
    2814115 ms  ResolveProjectReferences                  65 calls

`Music Store`
    198871 ms  GetCopyToPublishDirectoryItems            69 calls
    798276 ms  GetCopyToOutputDirectoryItems             69 calls
    2938416 ms  ResolveProjectReferences                  69 calls

`GenericHost`
     2853 ms  _GetProjectReferenceTargetFrameworkProperties  15 calls
     5221 ms  ResolveCustomReferences                   30 calls
    42886 ms  ResolveProjectReferences                  15 calls

'SocialWeather'
     6728 ms  ResolveCustomReferences                   59 calls
    10912 ms  CoreCompile                               29 calls
    173095 ms  ResolveProjectReferences                  29 calls

`SampleApp`
     3279 ms  _GenerateRestoreProjectPathWalk           16 calls
     5812 ms  ResolveCustomReferences                   32 calls
    48839 ms  ResolveProjectReferences                  16 calls

'dotnet new razor'
      215 ms  RazorCoreGenerate                          1 calls
      416 ms  ResolveTagHelperRazorGenerateInputs        1 calls
      475 ms  RazorCoreCompile                           1 calls

`dotnet new mvc`
      323 ms  RazorCoreCompile                           1 calls
      343 ms  RazorCoreGenerate                          1 calls
     1280 ms  ResolveTagHelperRazorGenerateInputs        1 calls

`dotnet new web`
       94 ms  ResolveAssemblyReferences                  1 calls
      382 ms  Restore                                    1 calls
     1230 ms  CoreCompile                                1 calls

# Tasks of Infamy (Slowest 3 overall tasks)
`MusicStore`
    12274 ms  Microsoft.Build.Tasks.Git.GetUntrackedFiles  69 calls
    12477 ms  ResolveAssemblyReference                  69 calls
    3975009 ms  MsBuild                                  462 calls

`Identity.ExternalClaims`
    11208 ms  Microsoft.Build.Tasks.Git.GetUntrackedFiles  65 calls
    16807 ms  ResolveAssemblyReference                  65 calls
    3652053 ms  MsBuild                                  436 calls

`GenericHost`
     2103 ms  Microsoft.Build.Tasks.Git.GetSourceRoots  15 calls
     2555 ms  ResolveAssemblyReference                  15 calls
    49491 ms  MsBuild                                  102 calls

`Social Weather`
     6011 ms  ResolveAssemblyReference                  29 calls
    10781 ms  Csc                                       23 calls
    193465 ms  MsBuild                                  212 calls

`SampleApp`
     2241 ms  Microsoft.Build.Tasks.Git.GetUntrackedFiles  16 calls
     2347 ms  Microsoft.Build.Tasks.Git.GetSourceRoots  16 calls
    58896 ms  MsBuild                                  109 calls

'dotnet new razor'
      287 ms  Copy                                       9 calls
      412 ms  RazorTagHelper                             1 calls
      673 ms  Csc                                        2 calls

`dotnet new mvc`
      340 ms  RazorGenerate                              1 calls
      531 ms  Csc                                        2 calls
     1274 ms  RazorTagHelper                             1 calls

`dotnet new web`
      127 ms  MsBuild                                    7 calls
      381 ms  RestoreTask                                1 calls
     1227 ms  Csc                                        1 calls

**Comment by BrennanConroy** [comment]
SocialWeather can definitely be removed from normal builds. Do we have a csproj setting to tell our builds not to include a project?

**Comment by HaoK** [comment]
Just to be clear I wasn't listing the worst offender apps, I just did a sampling across most of the main areas to check the profiles of several apps to see if there's any obvious patterns in which tasks are taking up all that time.  I don't think SocialWeather is that slow, the apps that depend everything (music store/mvc/identity) take forever

**Comment by natemcmaster** [comment]
_Build Team Triage:_ closing as there isn't any specific action item here.

> the total time of the publish looks to be highly correlated to how many dependencies there are

Based on @Haok's analysis, I don't see any obvious problem with the SDK or our repo. Samples that have a lot of dependencies or content are going to take more time. If you've already built once locally, you might be able to reduce build time by using the `--no-dependencies` option on `dotnet publish` or the `-NoBuildDeps` flag on build.cmd.

Also, if there are specific samples causing build perf issues and you feel the sample doesn't need to be re-built on every PR or test, feel free to remove them from the build. Use the `ProjectToExclude` item group. Example: https://github.com/aspnet/AspNetCore/blob/b76d9e2c36b7a90ec143eca3435e6914cb901f92/build/repo.props#L38-L72.

Feel free to re-open if you think there is more action required here.
