### ISSUE TITLE
[Components] UI not updating upon receiving a SignalR data 

### ISSUE THREAD

**Issue by dodyg** [aspnet/AspNetCore#8022]
### Describe the bug

I am creating a Razor Component app that uses its own SignalR. Everything works fine except that the UI does not update itself when receiving the data from SignalR. 

So I have two open tabs side by side. When I broadcast a message, the other tab does not update its UI automatically. The UI will only update with the broadcast message when I force an UI update by assigning a property with value.

![signalr-broadcast-2](https://user-images.githubusercontent.com/1761249/53554034-8dd87200-3b47-11e9-9407-6c8fb2982ae6.png)

So pretty much Message value assignment here does not update the UI.
```
@functions
{
    string Message { get;set;}
    protected override void OnInit()
    {
        Notification.OnMessage = (string user, string message) =>
        {
            Message = $"{user} broadcasts \"{message}\"";
            this.StateHasChanged();
        };
    }
}
```

### To Reproduce
https://github.com/dodyg/practical-aspnetcore/tree/master/projects/3-0/razor-component/chatr

**Comment by springy76** [comment]
I think you should wrap the `StateHasChanged()` call with `Invoke()` since your `OnMessage` will for sure not arrive inside the right `SynchronizationContext`.

**Comment by dodyg** [comment]
Sorry, I am not clear.  This is the where the Invoke happens. I have no idea what to pass to enable `StateHasChanged` within the method.

``
        public async Task ConnectAsync()
        {
            _connection = new HubConnectionBuilder()
                .WithUrl("https://localhost:5001/notificationhub")
                .Build();

            _connection.On<string, string>("BroadcastChannel", (user, message) => 
            {
                this.OnMessage?.Invoke(user, message);
            });

            if (_connection.State != HubConnectionState.Connected)
            {
                await _connection.StartAsync();
            }
        }
```

**Comment by springy76** [comment]
again: Have you tried replacing line #51 in Index.cshtml with `this.Invoke(this.StateHasChanged);` ?

**Comment by dodyg** [comment]
Ah great. Yup. It works. I wasn't aware this.Invoke exists in ComponentBase. Thanks a lot!
