### ISSUE TITLE
VS 2019 Preview 4 throws exception during opening a Razor Components .cshtml-File

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/AspNetCore#8023]
Since updating to VS2019 Preview 4, opening a Razor Components .cshtml - File shows an error box containing:

---------------------------
Microsoft Visual Studio
---------------------------
An exception has been encountered. This may be caused by an extension.

You can get more information by examining the file 'C:\Users\MyUser\AppData\Roaming\Microsoft\VisualStudio\16.0_3beecb4d\ActivityLog.xml'.

In ActivityLog.xml, this error is stored:

**System.InvalidOperationException: Service of type 'Microsoft.VisualStudio.Editor.Razor.ProjectPathProvider' is required to accomplish the task but is not available from the workspace.**

This happens even with the builtin project template.
It's impossible to use now. 👎

**Comment by DNF-SaS** [comment]
Resolved by removing VS2019 Preview completely and reinstalling it.

**Comment by chucker** [comment]
I've tried:

* repairing VS
* uninstalling, reinstalling VS
* reinstalling the Blazor `vsix`
* reinstalling .NET Core 3 preview

I still get this error:

```xml
    <source>Editor or Editor Extension</source>
    <description>System.InvalidOperationException: Service of type &apos;Microsoft.VisualStudio.Editor.Razor.ProjectPathProvider&apos; is required to accomplish the task but is not available from the workspace.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Host.HostWorkspaceServices.GetRequiredService[TWorkspaceService]()&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Razor.DefaultVisualStudioDocumentTrackerFactoryFactory.CreateLanguageService(HostLanguageServices languageServices)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.&lt;&gt;c__DisplayClass4_1.&lt;.ctor&gt;b__2()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]()&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Host.HostLanguageServices.GetRequiredService[TLanguageService]()&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Razor.DefaultRazorEditorFactoryService.TryInitializeTextBuffer(ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Razor.DefaultRazorEditorFactoryService.TryGetDocumentTracker(ITextBuffer textBuffer, VisualStudioDocumentTracker&amp; documentTracker)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Razor.DefaultRazorDocumentManager.OnTextViewOpened(ITextView textView, IEnumerable`1 subjectBuffers)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Razor.RazorTextViewConnectionListener.SubjectBuffersConnected(ITextView textView, ConnectionReason reason, IReadOnlyCollection`1 subjectBuffers)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.NonWpfListener.SubjectBuffersConnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.&lt;&gt;c__DisplayClass7_3.&lt;.ctor&gt;b__3()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
```

This breaks Razor syntax highlighting, IntelliSense, etc. (but not HTML syntax highlighting in the same file). It does not appear to affect actual compilation.

This worked in preview 3.

**Comment by DNF-SaS** [comment]
@chucker Strange, removing and re-installing VS2019 Preview4 helped in my case on two different machines.

**Comment by NTaylorMullen** [comment]
@chucker I'd recommend ensuring your VS is up-to-date. The call stack you pasted rears its head in multiple different flavors. One of which was fixed in an update (sadly I forget which one).

@DNF-SaS chances are your one VS wasn't up-to-date and reinstalling forced the update where as the other one I imagine you updated it to get the fix?

**Comment by springy76** [comment]
I had installed Preview3 some days ago without using it at all. After updating it to Preview4 it's broken too: No .cshtml file works, neither Blazor, Razor components, Razor pages or anything other Razor related.

**Comment by NTaylorMullen** [comment]
@springy76 would you mind trying to uninstall and reinstall VS preview 4 and see if it continues to be broken?

**Comment by chucker** [comment]
It appears for my case, the real culprit is a missing component. I had unchecked various optional components in VS Installer, and it looks like Live Share needs to be enabled.

I've logged https://developercommunity.visualstudio.com/content/problem/474936/razor-language-engine-appears-to-require-live-shar.html for this.

**Comment by NTaylorMullen** [comment]
Thanks @chucker I've filed #8096 to investigate this further.

**Comment by springy76** [comment]
@chucker (re)installing the optional Live Share component did the trick (I just had disabled it either just before or right after upgrading Preview3 to Preview4).

**Comment by eduardoluizm** [comment]
I had the same problem.
Before upgrading to RC I disabled the LiveShare and even disabled it upgraded to the latest version (VS RC requested). With it disabled, razor does not work and gives the error previously reported.
I've enabled LiveShare and everything is back to normal.

**Comment by NTaylorMullen** [comment]
Sorry for the inconvenience @eduardoluizm. We fixed this in a servicing release that should be available within the next month (definitely before RTM 2019). Stay tuned!

**Comment by bryanllewis** [comment]
I was getting this error on opening razor views even with LiveShare installed.  I ran a "Repair" on the VS 2019 install and it now seems to be working.
