### ISSUE TITLE
Add more flexible ways to manage ReactDevelopmentServerMiddleware startup

### ISSUE THREAD

**Issue by elken** [aspnet/AspNetCore#8024]
### Is your feature request related to a problem? Please describe.

I'm adjusting out frontend app to leverage [NextJS](https://nextjs.org/) instead of a cra app and it's currently not possible to properly load the application as it's expecting "Starting the development server" to be present in the output.

### Describe the solution you'd like

As I see it, there are two possible solutions

- Expose the string as a config setting (quick and easy, add to `SpaOptions` and set in the builder)
- Accepting an `Action<bool>` that would return `true` if the application started or `false` after the timeout if not
- Implementing an `ISpaDevelopmentServer` interface to allow the creation of a custom development server, which `ReactDevelopmentServer` can inherit from

### Describe alternatives you've considered

I tried rolling my own development server but too much of the code is internal and I'd end up reimplementing large amounts.

I'm happy to look into adding this myself, just putting it out there to see if there's any chance of it getting merged.

**Comment by danroth27** [comment]
@SteveSandersonMS  Thoughts?

**Comment by SteveSandersonMS** [comment]
@danroth27 This is the same request as was being addressed by this PR: https://github.com/aspnet/AspNetCore/pull/7452. The status of that PR is pending requested changes.

**Comment by SteveSandersonMS** [comment]
Closing as per conversation in #11897
