### ISSUE TITLE
cannot build the source code by build.cmd.

### ISSUE THREAD

**Issue by wzd24** [aspnet/AspNetCore#8025]
### Describe the bug
Build process fails with the message saying "Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview-009750/dotnet-sdk-3.0.100-preview-009750-win-x64.zip.",but i can download this file use any browser.

### To Reproduce
Using this version of ASP.NET Core 'v3.0.0-preview-19075-0444'
1. git clone --recursive https://github.com/aspnet/AspNetCore
2. git submodule update --init –recursive
3. git checkout v3.0.0-preview-19075-0444
3. .\build.cmd

### Expected behavior
All the build processes complete.

### Screenshots
![image](https://user-images.githubusercontent.com/1535315/53559581-5e485a80-3b85-11e9-9df9-a14ff61b4a47.png)

### Additional context
Include the output of `dotnet --info`
C:\Users\wzd>dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   2.2.200
 Commit:    27f814f6ba

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18346
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.200\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by wzd24** [comment]
I found that all branches have the same problem.

**Comment by Eilon** [comment]
See also: https://github.com/aspnet/AspNetCore/issues/6304

**Comment by natemcmaster** [comment]
I'm closing as it appears this issue has gone stale. This error hasn't been reported by others. My guess is the original problem was a network timeout. The install script gives up after 10 minutes.

@wzd24 if this problem is still occurring, feel free to reopen. We might be able to increase timeouts, but that's the only thing we can do to help with networking issues that cause build failures.
