### ISSUE TITLE
Remove CustomRequestCultureProvider class

### ISSUE THREAD

**Issue by hishamco** [aspnet/AspNetCore#8028]
Since the beginning of localization repo I had seen that `CustomRequestCultureProvider` is little bit confusing, while we can create a custom provider by sub classing `RequestCultureProvider`. IMHO `CustomRequestCultureProvider` has less value if the intend is to determines the culture via the configured delegate, so I saw some devs that are using a code with `CustomRequestCultureProvider` which can be done via custom `RequestCultureProvider` and vise versa.

In nutshell the word **Custom** is confusing me and others in this context
/cc @Eilon

**Comment by Eilon** [comment]
It is unlikely we would make a breaking change for such a trivial case. Perhaps we could serve people better by having clearer XML doc comments in the type?

**Comment by hishamco** [comment]
May be, but it's not enough to distinguish between them. BTW 3.0.0 is a major release, breaking changed may occur in such release I'm not which guidelines are using to accept the breaking changes

**Comment by Eilon** [comment]
3.0 means we *can* do breaking changes, but we still only make breaking changes where there is a very strong case. The question we ask is, what is the value in breaking someone who is successfully using this type?

**Comment by hishamco** [comment]
In some cases there is weak design for the APIs, wrong namespace .. etc I knew may it is not strong cases, but major release the only way to fix such breaking changes

**Comment by danroth27** [comment]
This breaking change doesn't seem warranted, so closing.

**Comment by hishamco** [comment]
Strange!! I see this confusing many including me
