### ISSUE TITLE
Long time to first byte when using MvcRazorExcludeRefAssembliesFromPublish false in .csproj

### ISSUE THREAD

**Issue by IanGleeson** [aspnet/AspNetCore#8030]
I've published my Net Core 2.2 application to Azure App Service and receive this message "Cannot find compilation library location for package 'Microsoft.NETCore.App'"

I check the web server through the Kudu console and their is no Microsoft.NETCore.App package there.

According to #7450 I then add the ref folder as mentioned through MvcRazorExcludeRefAssembliesFromPublish in .csproj and it works again. The issue I have is that it is much slower now than it used to be. Looking at Chrome Inspector the TimeToFirstByte for some pages can go over 15 seconds. Could this solution cause this? If so, does anyone know a fix?

As an aside, could someone explain to me what caused this error in the first place? I didn't need the refs folder before a few days ago and it worked fine.

**Comment by pranavkm** [comment]
Could you include the project file (.csproj)? Generally you shouldn't have to include the ref assemblies as part of publish unless you're doing runtime compilation.

**Comment by IanGleeson** [comment]
Here's my .csproj in .txt form(pasting the content of the file here removed the elements and attributes):
[csproj.txt](https://github.com/aspnet/AspNetCore/files/2917245/csproj.txt)

**Comment by pranavkm** [comment]
Is there a reason you have these two blocks in your project file:

```xml
<ItemGroup>
    <Content Remove="Templates\ForgotPassword.cshtml" />
    <Content Remove="Templates\Register.cshtml" />
    <Content Remove="Templates\UserInvite.cshtml" />
  </ItemGroup>
```

and 

```xml

  <ItemGroup>
    <None Include="Templates\ForgotPassword.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Templates\UserInvite.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Templates\Register.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

It basically prevents the RazorSdk from trying to compile them as part of the project build and instead perform runtime compilation. If you remove these, you wouldn't need to set the `<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>` flag and your initial response should be much faster.

**Comment by IanGleeson** [comment]
They're email templates I use with SendGrid, an email service. When trying to reference them without copying to output directory I got an error. But now that I think of it, it is the Register and InviteUser pages that were giving me this issue.

I'll try alter this tomorrow and get back to you, thanks.

For reference this is the forget password code involving SendGrid:

var email = await _emailSender
                        .To(Input.Email)
                        .Subject("Reset Password")
                        .UsingTemplateFromFile($"{Directory.GetCurrentDirectory()}/Templates/ForgotPassword.cshtml", new { CallbackUrl })
                        .SendAsync();

**Comment by pranavkm** [comment]
Do you know what file is being compiled when you see the slowness? If it's one of these files, you might be able to include them in the publish output rather than disabling runtime compilation for it:

```xml
<CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
```

Your publish output would contain all the cshtml files from your app, but it should use the build time compiled output when you use it as part of a view.

**Comment by IanGleeson** [comment]
I've tried your suggestion but the TimeToFirstByte stays around 20 seconds.

This is my current .csprog 

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <WebProject_DirectoryAccessLevelKey>0</WebProject_DirectoryAccessLevelKey>
    <UserSecretsId>916c15bd-f01b-4a62-aa5f-f82de6999d65</UserSecretsId>
    <LangVersion>latest</LangVersion>
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
    <CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn />
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Braintree" Version="4.8.0" />
    <PackageReference Include="BuildBundlerMinifier" Version="2.8.391" />
    <PackageReference Include="FluentEmail.Core" Version="2.5.1" />
    <PackageReference Include="FluentEmail.Razor" Version="2.5.2" />
    <PackageReference Include="FluentEmail.SendGrid" Version="2.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="2.2.0" />
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Ajax" Version="3.2.6" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0" />
    <PackageReference Include="ncrontab" Version="3.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>

</Project>
```

Any help would be appreciated.

**Comment by pranavkm** [comment]
Could you include logs from your first request set to `Trace`? At this point, it's a bit difficult to say what's causing the slowness.

**Comment by IanGleeson** [comment]
Hey, sorry for the late reply. After banging my head against the wall on Friday I changed plugins from FluentEmail to the official SendGrid email plugin. This removes my problem as SendGrid allows you to make templates directly on their website.

I think the problem was Razorlight, the Razor templating engine FluentEmail relies upon for templates, perhaps due to this issue: https://github.com/toddams/RazorLight/issues/203

Thank you for your help @pranavkm
