### ISSUE TITLE
Enable prerendering on the Blazor templates

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#8033]
This will show the application instead of the loading screen.
So it will reduce the time to first meaningful paint.
(Time to interactive still will be the same).

**Comment by mkArtakMSFT** [comment]
Closing as this has been discussed by @danroth27 and @stevesandersonMS.:
> We've decided not to enable prerendering by default in Blazor because of the additional complexity it adds for app developers. We should, however, provide guidance about how to add prerendering to the app so people can opt in to it, if they want.
