### ISSUE TITLE
[Helix] Skipping NodeServices tests on helix (node js not installed)

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#8044]
Tracking issue for getting node js on helix machines here: https://github.com/dotnet/core-eng/issues/5302

In the short term, is nodejs something that's easily installed from command line?  We can try installing it as a custom precommand @SteveSandersonMS ?

**Comment by mkArtakMSFT** [comment]
@HaoK are you following up on this? Is this planned to happen soon?

**Comment by HaoK** [comment]
Its blocked pending the rollout of upgraded helix queues with the updates we need, I think its something they were planning once preview4 is out the door, so hopefuly soon

**Comment by HaoK** [comment]
Fixed via https://github.com/aspnet/AspNetCore/pull/9046
