### ISSUE TITLE
[Test failure] EmitsConnectionStartAndStop

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#8055]
```C#
The collection was expected to contain a single element, but it was empty.

Stack trace
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.EventSourceTests.EmitsConnectionStartAndStop() in /_/src/Servers/Kestrel/test/FunctionalTests/EventSourceTests.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=110702&view=ms.vss-test-web.build-test-results-tab

I guess this is the same as https://github.com/aspnet/AspNetCore/issues/6127 but in the 2.1 branch.

**Comment by anurse** [comment]
Closing this as @jkotalik is doing a review of all our flaky tests right now. RaaS is ever-vigilant too
