### ISSUE TITLE
Update Blazor templates to use .razor files instead of .cshtml

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#8056]
We updated the Razor Components template to use .razor files, but the Blazor templates are still using .cshtml. We should update the Blazor templates as well.

**Comment by Adnaco** [comment]
Thank you! I have lost my development track since Server Side Blazor 0.6. How to find best sources for developer's (developer's guide), any suggestions? Before it was blazor.net resource. Where is located primary resource for Blazor based on .net core 3.0?
Thank you,
Serge

**Comment by Adnaco** [comment]
Looks like here is start point: https://docs.microsoft.com/en-us/aspnet/core/razor-components/?view=aspnetcore-3.0. Is it correct?

**Comment by danroth27** [comment]
@Adnaco Yup, that's the new home for the Razor Components docs.

**Comment by StevenTCramer** [comment]
@danroth27 updated in PR #8544

**Comment by danroth27** [comment]
@StevenTCramer Nice! Thanks!
