### ISSUE TITLE
ApplicationInitialization not executing when using InProcess

### ISSUE THREAD

**Issue by cannehag** [aspnet/AspNetCore#8057]
We have been using Application Initialization in our services to warm up the application before swapping slots (Azure App Services). We are using AppInsights for logging and have seen there initialization requests beeing logged with User-Agent "IIS Application Initialization Warmup".
When switching to InProcess hosting, these logs are missing.

```xml
<system.webServer>
      <applicationInitialization doAppInitAfterRestart="true" skipManagedModules="true">
         <add initializationPage="/api/heartbeat?checkDependencies=true" />
      </applicationInitialization>
</system.webServer>
```

Regardless of InProcess or not, Application Initialization should be executed.

**Comment by cannehag** [comment]
@muratg Any update on this? This is kind of serious since when using swapping in Azure, it will swap over to the production slot before the application is completely initialized.

**Comment by muratg** [comment]
@pakrym @jkotalik any thoughts here? Is this due to how logs are processed, or are we actually skipping this in InProc?

**Comment by pakrym** [comment]
We had a fix for AppInit in 3.0 https://github.com/aspnet/AspNetCore/pull/7024 which might help this.

**Comment by pakrym** [comment]
@cannehag are you able to try 3.0 preview using the site extension as described in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.2#deploy-aspnet-core-preview-release-to-azure-app-service

**Comment by cannehag** [comment]
@pakrym I can test this of course, but that would be on a dummy service since we have production issues with the current version. Are there any plans to adress this before the release of 3.0 ?

**Comment by cannehag** [comment]
@pakrym Just tested and I can verify that it is now running the AppInit although with another User-Agent than it usually do: "SiteWarmup" (Before it was "IIS Application Initialization Warmup")

**Comment by anurse** [comment]
@cannehag Can you try a self-contained deployment of 3.0? Also, I might suggest checking and logging the user agent in the app itself, rather than using App Insights, just to make sure you know if it's coming in. We have tests that seem to indicate this is working, so I want to make sure we know for sure what could be different in your environment :).

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by pseabury** [comment]
I'd like this reopened if possible per https://stackoverflow.com/questions/57679221/asp-net-core-2-2-site-warmup 

Warmup doesn't seem to work with in-process hosting.

**Comment by Indigo744** [comment]
Please reopen this issue. App initialization is not working.

@anurse  self-contained deployment does not help.
