### ISSUE TITLE
Blazor (ASP.NET Core Hosted) template compiles with a warning about use of obsolete API IHostingStartup

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#8058]
Startup.cs(21,56,21,75): warning CS0618: 'IHostingEnvironment' is obsolete: 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'

Repro steps:
- `dotnet new blazorhosted`
- `dotnet run`

**Comment by SteveSandersonMS** [comment]
Can confirm. Yes, we need to fix this in the template.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS , @javiercn is there anything pending here or can this be closed already?

**Comment by javiercn** [comment]
It’s on PR awaiting review

**Comment by javiercn** [comment]
@stevesandersonms did you fix this without me knowing? I had a PR out for it.
