### ISSUE TITLE
Load external vb net

### ISSUE THREAD

**Issue by Razgort** [aspnet/AspNetCore#8059]
Hello guys,

Seems to have an issue here when tyring to load an external dll written in old vb net framework aspnet 4.5. It seems the Datetime Vb net is unknown ...

I'm using asp core 2.2 framework in my current project.
Any idea how to solve this ?

**Comment by Eilon** [comment]
Hi @Razgort can you please provide exact steps to reproduce this problem, and also more details on the exact error(s) you are seeing?

**Comment by Razgort** [comment]
Hello, 
I'm trying to load an external vb dll.
In this DLL i have a class which have a Datetime property.
And it said it failed to load with exception on that dll .

**Comment by Eilon** [comment]
@Razgort unfortunately we'll need more information to reproduce the problem. Please upload a complete app to GitHub along with info on the error(s) you're seeing so that we can investigate.
