### ISSUE TITLE
Strongly typed @page route in Razor Pages

### ISSUE THREAD

**Issue by Ponant** [aspnet/AspNetCore#8065]
On a razor page we can do this to change the default folder-based route:
`@page "/xxx/yyy"`

but trying to do this with a strongly typed property in some class `Constants.Routes` does not work
`        public const string Myroute = "/mysuperroute"; 
`
and
`@page @Constants.Routes.Myroute`

I am getting an error `The 'page' directive expects a string surrounded by double quotes.`

Is there a way around this? I would like to avoid route duplication through the options
e.g. https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-2.2#configure-a-page-route 
Thanks

**Comment by NTaylorMullen** [comment]
@Ponant sadly there is no way around this and is by design due to our requirement to harvest page routes without needing to run the application or do C# advanced logic to determine what a pages route should be.

**Comment by Ponant** [comment]
@NTaylorMullen , I understand but I think it will be a big plus because I find it very hard to scale an app with strings.
