### ISSUE TITLE
Unable to compile the SignalR C++ client on MacOS

### ISSUE THREAD

**Issue by markusstephanides** [aspnet/AspNetCore#8066]
### Describe the bug
I'm not able to compile the SignalR C++ client on MacOS.

### To Reproduce
1. Using the most recent version of the repo and compiled the most recent version of the cpprestsdk
2. Running
`CXX=g++ cmake .. -DCMAKE_BUILD_TYPE=Release -DCPPREST_INCLUDE_DIR=<path_to_cpp_rest_include_dir> -DCPPREST_LIB_DIR=<path_to_cpp_rest_lib_dir>`
3. See errors in the screenshot below

### Expected behavior
Successful compilation (library) of the SignalR cpp client.

### Screenshots
![image](https://user-images.githubusercontent.com/6057570/53631683-6353eb00-3c13-11e9-9d2e-1c8c7d22a683.png)

**Comment by BrennanConroy** [comment]
This is expected right now. We haven't put any effort into the cross-plat build with CMAKE yet, but this is definitely on our radar.

**Comment by anurse** [comment]
Closing in lieu of https://github.com/aspnet/AspNetCore/issues/8706 which is tracking our cross-plat build integration work.
