### ISSUE TITLE
Link tag helper not working asp.net core 2.2

### ISSUE THREAD

**Issue by joovnaz** [aspnet/AspNetCore#8072]
### Describe the bug
Link tag helper stopped working after 2.1 to 2.2 migration

### To Reproduce
The following tag helper stopped working:

>             <a class="icon item" 
>                asp-area="@Model.Area" asp-controller="@Model.Controller" asp-action="@Model.Action" 
>                asp-route-page="@(Model.Page+1)" asp-route-nitems="@Model.NItems" asp-route-search="@Model.Search">
>                 <i class="right chevron icon"></i>
>             </a>

No html link "href" attribute gets rendered. 

### Expected behavior
A complete href attribute should have been generated.

### Additional context
Using work around reported here:
https://stackoverflow.com/questions/54722462/link-tag-helper-not-working-in-asp-net-core-2-2

**Comment by pranavkm** [comment]
@rynowak \ @JamesNK, might be a dup of https://github.com/aspnet/Routing/issues/728, but the `asp-route-page` token also seems suspect.

**Comment by joovnaz** [comment]
You are right. Just changing `asp-route-page` param to `asp-route-pagex` html is rendered as expected.

**Comment by smokeelow** [comment]
Is there any update on this issue?

**Comment by JamesNK** [comment]
Hi

We have added a fix for this issue in 3.0. More discussion is here - https://github.com/aspnet/AspNetCore/issues/5055

**Comment by smokeelow** [comment]
> Hi
> 
> We have added a fix for this issue in 3.0. More discussion is here - #5055

Awesome! Thanks!
