### ISSUE TITLE
IIS Recycle with .NET Core Issues

### ISSUE THREAD

**Issue by T-0pel** [aspnet/AspNetCore#8077]
### Describe the bug
When using .NET core application with IIS the recycle overlap does not work or produces inconsistent behaviour.

### To Reproduce
I have created [a repository with a sample solution](https://github.com/T-0pel/iis-recycle-test) with .NET Core and .NET Framework Apis.

1. Launch/publish a .NET core project in IIS.
2. Call api/values controller that simulates load by using Task.Delay(10000).
3. During these 10 seconds recycle the app pool.
4a. _In Process_ - Request hangs indefinitely while debugging or returns 200 but no data without debugging (Screenshot 1).
4b. _Out Of Process_ - Request fails because the pool is recycled while it still waits (Screenshot 2).

### Expected behavior
The expected behaviour is for the IIS recycle to happen after the request finishes successfully.
This is the behaviour of the sample .NET Framework application with the exact same settings. It waits until the request finishes and only then recycles the pool.

Is the overlapped recycle not supported with .NET Core?

### Screenshots
In Process (200 with no data):
![in-process](https://user-images.githubusercontent.com/9216020/53650117-b477d500-3c3b-11e9-803f-a427e15effdb.PNG)

Out Of Process (HTTP Error):
![out-of-process](https://user-images.githubusercontent.com/9216020/53650130-be013d00-3c3b-11e9-9b4d-ad1d3b1cbc18.PNG)

### Additional context
IIS app pool is set to allow overlapped recycle.
The shutdown time limit is 90 seconds.

**Comment by anurse** [comment]
> Is the overlapped recycle not supported with .NET Core?

Overlapped recycle is not a supported scenario right now. We generally recommend something like [blue-green deployments](https://searchitoperations.techtarget.com/definition/blue-green-deployment) here.
