### ISSUE TITLE
Latest Blazor build hangs when reloading on fetchdata page

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#8079]
Blazor templates version: 0.9.0-preview3-19128-02

Repro steps:

* Create hosted or standalone app, `dotnet run`
* Navigate to "fetch data" page
* Press "reload" in browser

Result:

* Browser tab hangs during page load

This did not happen in 0.8.0, of course!

**Comment by SteveSandersonMS** [comment]
That would be due to this bad boy:

https://github.com/aspnet/AspNetCore/blob/32aebef4d13e0d5fbe0af4a1453b1283627766fc/src/Components/Blazor/Blazor/src/Hosting/WebAssemblyHostExtensions.cs#L22

@rynowak You were so right! Also I did genuinely locate this line using the client-side debugger.

**Comment by chucker** [comment]
Is the resolution of this issue by any chance the difference between 0.9.0-preview3-**19153**-02 and 0.9.0-preview3-**19154**-02? It seems I was seeing a similar hang problem in 0.9 until I updated my NuGet packages.

**Comment by SteveSandersonMS** [comment]
Yes, you’re right. This issue is fixed in that updated build.
