### ISSUE TITLE
Razor projects as transitive references always add content during GetCopyToOutputDirectoryItems

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#8084]
Consider:

```xml
<!-- ProjectA -->
<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\ProjectB\ProjectB.csproj" Targets="Restore" />
  </ItemGroup
</Project>

<!-- ProjectB -->
<Project Sdk="Microsoft.NET.Sdk.Razor"> 
</Project>
```

Where ProjectB has one or more Razor files. A clean build of ProjectA will result in a build failure stating `file ..\Project\obj\Debug\netcoreapp3.0\ProjectB.Views.dll cannot be copied.`

This is because ProjectB does not get compiled but the `_RazorGetCopyToOutputDirectoryItems` target unconditionally adds files to the list of files being copied:
https://github.com/aspnet/AspNetCore-Tooling/blob/2c8a5ff0e95c5767330184dbf691572b8a5c6c7f/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L593-L613

This scenario is fairly unusual so we haven't had any user reports. We did discover it during our test cleanup and the workaround was to replace the `ProjectReference` with a build target:

```xml
<!-- ProjectA -->
<Project Sdk="Microsoft.NET.Sdk.Web">
  <Target Name="RestoreProjectB" BeforeTargets="Restore">
    <MSBuild Projects="..\ProjectB\ProjectB.csproj" Targets="Restore" />
  </Target>
</Project>
```

**Comment by mkArtakMSFT** [comment]
Let's fix this if the fix is straight forward and simple. Otherwise, let's do nothing.

**Comment by pranavkm** [comment]
Closing as we haven't seen any customer reports for this.
