### ISSUE TITLE
Enable helix VSTS test reporting

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#8087]
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/Readme.md

```
    <!-- Enable reporting of test results to azure dev ops -->
    <EnableAzurePipelinesReporter>false</EnableAzurePipelinesReporter>
```

cc @anurse

**Comment by natemcmaster** [comment]
Closing as duplicate of https://github.com/aspnet/AspNetCore/issues/7368
