### ISSUE TITLE
Investigate Razor depending on LiveShare being installed.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#8096]
https://github.com/aspnet/AspNetCore/issues/8023#issuecomment-468767402

**Comment by mqudsi** [comment]
Was just bit by this. @chucker saved me a lot of time tracking this down.
In my case I have Live Share installed but manually disabled.

**Comment by NTaylorMullen** [comment]
Turns out the core issue is due to `Microsoft.VisualStudio.Liveshare.dll` not being available for MEF discovery. Therefore, our Razor.LiveShare services explode and result in those services falling out of the MEF graph.
