### ISSUE TITLE
SignalR:NegotiateAsync always uses proxy 

### ISSUE THREAD

**Issue by lobster2012-user** [aspnet/AspNetCore#8097]
enviroment - win, netcoreapp2.2.
The problem seems to be in the implementation of the system proxy. If there is a proxy in the system, the negotiation request ALWAYS use the proxy (it does not matter what is on the exception list in system proxy). It is impossible to disable the use of proxies, you can simply disable SkipNegotiation or use your proxy.

The reasons:
HttpHandlerDefaults.DefaultUseProxy = true;
and options for `CreateHttpClient` does no have USE_PROXY property.

It's funny, in the new version of system.web.proxy, the problem with loopback has finally been solved, but this nuget version does not exist. You can make your wrapper, of course.

(sorry for english)

**Comment by lobster2012-user** [comment]
I checked it at home.
Forcing a proxy is observed if both the pack and the manual proxy are specified. However, the useproxy option is not available. Later I’ll check back at work (where I’ve watched the forcing with only a manual address).

**Comment by BrennanConroy** [comment]
You can configure the `HttpMessageHandler` used by the client via the `HttpMessageHandlerFactory` property. See our docs at https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.2#configure-additional-options for information on it.

**Comment by lobster2012-user** [comment]
@BrennanConroy 
Thank you. Closed.
