### ISSUE TITLE
Get more information about "Test Run Aborted" failures

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8099]
We see occasional cases where a test run fails with "Test Run Aborted" and no specific failing test. This is usually due to the test process crashing from a failed assertion or background thread exception. We get almost no data from these, so we need to look at how to get more data into the build log so we can identify the problem.

**Comment by natemcmaster** [comment]
Closing in favor of https://github.com/aspnet/AspNetCore-Internal/issues/2079. As you mentioned, "Test Run Aborted" aborted is almost always the result of a test process crashing.

@JunTaoLuo let's add "vstest.console.exe" to the list of processes we monitor for crash dumps in https://github.com/aspnet/AspNetCore-Internal/issues/2079
