### ISSUE TITLE
SignalR client(js) connectionId is always 0, how to match client connectionId with server side connectionId?

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#8108]
_From @handsomeyao77 on Tuesday, 26 February 2019 02:05:20_

### Steps to reproduce

_Copied from original issue: SignalR/SignalR#4318_

**Comment by halter73** [comment]
_From @halter73 on Tuesday, 26 February 2019 02:33:21_

Can you provide the code you are using to read the connection id?

**Comment by halter73** [comment]
_From @handsomeyao77 on Tuesday, 26 February 2019 02:39:44_

![image](https://user-images.githubusercontent.com/7311188/53383445-ac593480-39b2-11e9-89e9-8ba789332b42.png)

![image](https://user-images.githubusercontent.com/7311188/53383467-c0049b00-39b2-11e9-8fa4-81aefc39cbad.png)

Print connection object, the id is 2 now, confused...

**Comment by halter73** [comment]
The new SignalR clients don't expose their connection IDs via public properties. We will consider changing this in 3.0. For now, you can return the caller's connection ID from a hub method as a workaround.

**Comment by handsomeyao77** [comment]
Great! thank you.

**Comment by halter73** [comment]
We probably want to add a note to our docs that it's easy to impersonate a client given their connection id.

**Comment by anurse** [comment]
https://github.com/aspnet/AspNetCore/issues/8681 will fix this.
