### ISSUE TITLE
[SignalR] Wrong error message when invoking a method that doesnt exist

### ISSUE THREAD

**Issue by jannikbuschke** [aspnet/AspNetCore#8124]
SignalR reports `System.IO.InvalidDataException: Invocation provides 1 argument(s) but target expects 0` when invoking a method that does not exist. The error message is irritating. In my case I had a typo in my method name. Took me quite some time to recognize

**Comment by BrennanConroy** [comment]
This should be fixed in version 1.1.X
https://github.com/aspnet/SignalR/pull/2768
