### ISSUE TITLE
Cannot open include file 'aspnetcore_msg.h'

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8126]
PR #7706 is seeing this unrelated failure that seems to be coming from the IIS native code

```
e:\a\_work\1\s\src\servers\iis\aspnetcoremodulev2\commonlib\resources.h(6): fatal error C1083: Cannot open include file: 'aspnetcore_msg.h': No such file or directory (compiling source file GlobalVersionTests.cpp) [E:\A\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\CommonLibTests\CommonLibTests.vcxproj]
```

cc @muratg @Tratcher @jkotalik

**Comment by jkotalik** [comment]
That's an autogenerated file. I think it's an ordering issue with building CommonLibTests. It should always be built after the commonlib folder.

**Comment by anurse** [comment]
I presume all this means you have an idea of how to fix it? 😝

**Comment by pakrym** [comment]
I think two builds of the same project are generating this file causing a conflict. We need to see if it can be move into a platform specific subdirectory. I can take a look.

**Comment by pakrym** [comment]
https://github.com/aspnet/AspNetCore/blob/32aebef4d13e0d5fbe0af4a1453b1283627766fc/src/Servers/IIS/AspNetCoreModuleV2/CommonLib/CommonLib.vcxproj#L276
