### ISSUE TITLE
No packages dropped

### ISSUE THREAD

**Issue by mikedice** [aspnet/AspNetCore#8127]
### Describe the bug
My goal is to build my own debug copy of asp.net core and use it in an application so I can step through the code in my debugger. Following the build steps I do not see any packages to include in my private build
### To Reproduce
Followed the steps [here](https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md)
The result of running build.cmd was the message 'build succeeded' and I don't see any errors

### Expected behavior
Look under the Artifacts directory, there is only one package. I was expecting to see all the packages i would need to run my asp.net mvc application. Is that wrong?
`C:\src\aspnet\AspNetCore\artifacts>dir /s /b packages
C:\src\aspnet\AspNetCore\artifacts\packages\Debug
C:\src\aspnet\AspNetCore\artifacts\packages\Release
C:\src\aspnet\AspNetCore\artifacts\packages\Debug\NonShipping
C:\src\aspnet\AspNetCore\artifacts\packages\Debug\Shipping
C:\src\aspnet\AspNetCore\artifacts\packages\Debug\Shipping\Microsoft.AspNetCore.Blazor.Templates.0.9.0-preview4-t000.nupkg
C:\src\aspnet\AspNetCore\artifacts\packages\Release\NonShipping
C:\src\aspnet\AspNetCore\artifacts\packages\Release\Shipping`

**Comment by davidfowl** [comment]
cc @natemcmaster @dougbu @anurse

**Comment by dougbu** [comment]
@mikedice to generate packages, add the `-pack` (Windows) or `--pack` (otherwise) command-line argument i.e. `.\build.cmd -pack` or `./build.sh --pack`.

In PowerShell, execute `help -full .\build.ps1` to see more about the `.\build.cmd` / `.\build.ps1` command. In Bash, execute `./build.sh --help` to view similar information.

**Comment by natemcmaster** [comment]
Closing as I believe the original question was answered.
