### ISSUE TITLE
Routing doesn't find controllers when using StarterWeb template

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#8132]
The reason is that the template is missing `router.MapControllers()` call in the `Startup.Configure()` method. This results in the Default Identity UI's `AccountController` not routeable hence the error.

**Comment by ryanbrandenburg** [comment]
VSO bug to close when finished: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/797529?src=WorkItemMention&src-action=artifact_link

**Comment by ryanbrandenburg** [comment]
Also this one: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/797529

**Comment by ryanbrandenburg** [comment]
If I understand it correctly [this change](https://github.com/aspnet/AspNetCore/pull/8351) is testing the scenario described here, correct? If so it would seem it doesn't repro (at least through the CLI).

**Comment by mkArtakMSFT** [comment]
May be related https://github.com/aspnet/AspNetCore/issues/8387

**Comment by ryanbrandenburg** [comment]
On review #8387 seems unrelated.

**Comment by ryanbrandenburg** [comment]
Closed in https://github.com/aspnet/AspNetCore/pull/8685.
