### ISSUE TITLE
Razor in code behind (React style classes)

### ISSUE THREAD

**Issue by robertjak** [aspnet/AspNetCore#8150]
Hi,

the current rendering solution of React Components is an amplified Razor syntax. It is an effective and pragmatic way but I am asking myself if in long term the more evident syntax of React, where it is completely clear that the code is wrapped in a class and the whole HTML & CSS part is rendered in one method, would be better.

I imagine a clear code behind class with razor inside of a render method. Additional advantage I see is, maybe we could then use standard custom parameter in components' constructors instead of a bit weird Parameter attributes on fields. 

What do you think, is such a solution maybe already considered for the future?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @robertjak.
We did considered this in the past but have decided not to do this.
