### ISSUE TITLE
Object oriented/imperative Razor Components 

### ISSUE THREAD

**Issue by robertjak** [aspnet/AspNetCore#8154]
Hi,

are there may be some plans for object oriented "flavor" of Razor Components? The current solution is, as far as I know and understand it, actually a .NET equivalent of React, therefore functional oriented. 

I have so far programmed in PHP Spaghetti style, Java Swing, C# WinForms, WebForms, ASP.NET MVC, jQuery, MVVM with WPF and Knockout, AngularJS, React ... and from all those technologies I find the classical object oriented controls like WinForms by far the best ones. Not always the most elegant, but really easy to grasp, easy for full stack development, easy to find appropriate developers ... one needed only a good architecture and discipline not to do too much in event handlers, but this is always needed, frameworks are never enough to enforce this.

As Robert C. Martin says, programming is all about the details, but declarative functional programming seems not to be the best to handle the details and not the best or the easiest to handle state which is in UI essential. It is cool for data transformation which is also needed in UI, but we can always use LINQ, we do not need the whole UI forced in functional style.

Moreover, React has some problems which are in OOP easier to solve:
- state sharing among components (e.g. by singleton services)
- logic reuse - complex patterns like HOC or Render Props (e.g. by using static helpers or composition)

What do you think? Easy, simple object oriented Razor Components with virtual DOM or maybe even with virtual canvas? Reviving the successful Microsoft legacy?

**Comment by SteveSandersonMS** [comment]
If you could post some very specific examples of concrete problems you experience with the existing components programming model, we can evaluate this. Otherwise I suspect this is too abstract to say anything about. Hope that's OK!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This ask is not aligned with our vision and we have no plans to implement this type of functionality going forward. Of course, you're always welcome to fork this codebase and build whatever you wish - sky is the limit!
