### ISSUE TITLE
Support Input arrays without index

### ISSUE THREAD

**Issue by Fruchuxs** [aspnet/AspNetCore#8160]
### Is your feature request related to a problem? Please describe.
Dynamic form with items which can be added and removed, also on existing lists.

### Describe the solution you'd like
Like PHP: 
```
<input name="property[]" />
<input name="property[]" />
<input name="property[]" />
```

With asp.net I tested the following:
```
<input name="property[]" />
<input name="property[]" />
<input name="property[]" />
```
-> empty list

```
<input name="property" />
<input name="property" />
<input name="property" />
```
-> empty list

```
<input name="property[0]" />
<input name="property[1]" />
<input name="property[2]" />
```
-> works fine, but if I remove the mid element via js I must re number all indexes ... this is fragil.

If the sequence is broken, for example 0, 2, 3, the array just contains the first zero indexed element. Feels strange..

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Fruchuxs.
@dougbu, can you please follow up regarding what available options exist. Thanks!

**Comment by Fruchuxs** [comment]
Other strange behavior:

```
<input name="values" value="1" />
<input name="values" value="2" />
<input name="values" value="3"  />

public IActionResult Action(List<int> values) {
   // values.Count == 3
}
```

Works fine, but not with list properties in a model. Here `[index]` is required.

**Comment by dougbu** [comment]
@Fruchuxs could you clarify "list properties in a model"? Do you mean for example `List<SomeComplexType>`?

Separately, an `index` field or fields can help the list-with-gaps case e.g.
``` html
<input type="hidden" name="property.index" value="0;2;3"/>
<input name="property[0]" />
<input name="property[2]" />
<input name="property[3]" />
```

**Comment by Fruchuxs** [comment]
> @Fruchuxs could you clarify "list properties in a model"? Do you mean for example List<SomeComplexType>?

Yes.
As an example:
```c#
class Container {
    public List<Something> Items {get;set;}
}

class Something {
    public string Foo {get;set;}
    public int Bar {get;set;}
}
```

```html
<input type="text" name="Container.Something.Foo">
<input type="text" name="Container.Something.Bar">

<input type="text" name="Container.Something.Foo">
<input type="text" name="Container.Something.Bar">

<input type="text" name="Container.Something.Foo">
<input type="text" name="Container.Something.Bar">
```

Result:
```c#
public IActionResult Action(Container cnt) {
   var hasAnyItems = cnt.Items.Count.Any(); // is false
}
```

But this works:
```html
<input type="text" name="FooBar" value="1">
<input type="text" name="FooBar" value="2">
<input type="text" name="FooBar" value="3">
```

```c#
public IActionResult Action(List<int> items) {
   var hasAnyItems = cnt.Items.Count.Any(); // is true

   foreach(var i in items) {
       Console.WriteLine(i); // Prints 1,2,3
   }
}
```

> Separately, an index field or fields can help the list-with-gaps case e.g.

 So I need to distribute the possible indexes in a hidden field?

For example:
```c#
class Something {
    public string Foo {get;set;}
    public int Bar {get;set;}
}
```

```html
<input type="hidden" name="Something.Index" value="0;2;3">
<input type="text" name="Something[0].Foo">
<input type="text" name="Something[0].Bar">

<input type="text" name="Something[2].Foo">
<input type="text" name="Something[2].Bar">

<input type="text" name="Something[3].Foo">
<input type="text" name="Something[3].Bar">
```

If I understand you correctly, I must say, that this design is just strange. If I got just this:
```html
<input type="text" name="Something[0].Foo">
<input type="text" name="Something[0].Bar">

<input type="text" name="Something[2].Foo">
<input type="text" name="Something[2].Bar">

<input type="text" name="Something[3].Foo">
<input type="text" name="Something[3].Bar">
```

I know which indexes are present by the numbers in the name (0, 2, 3). Buf if I use this HTML Code above (without your index field suggestion), the model binder just binds the first one and ignores the other two values, because the sequence is broken.
It is also hard ans fragile to manage such a index-field with JS.

**Comment by dougbu** [comment]
The feature you're asking for is provided for simple collections e.g. `List<int>` because it's intuitive and hard to get wrong. However, 
``` html
<input type="text" name="Something[].Bar">

<input type="text" name="Something[].Foo">
<input type="text" name="Something[].Bar">

<input type="text" name="Something[].Foo">
```
is easy to get wrong. Is that 3 `Something`s or 2?

Much better to stick with explicit identification of the elements when the elements have complex types.

If an `index` property doesn't work for you, I suggest providing separate pages for adding items, removing items, or changing existing items.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
