### ISSUE TITLE
Razor SDK shouldn't generate the MVC recompilation attributes unless its necessary

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8161]
### Describe the bug
A web SDK project that targets `netcoreapp3.0` with no razor files will unconditionally have these attributes:

```C#
[assembly: Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute("SampleApp.Views")]
[assembly: Microsoft.AspNetCore.Razor.Hosting.RazorLanguageVersionAttribute("3.0")]
[assembly: Microsoft.AspNetCore.Razor.Hosting.RazorConfigurationNameAttribute("MVC-3.0")]
[assembly: Microsoft.AspNetCore.Razor.Hosting.RazorExtensionAssemblyNameAttribute("MVC-3.0", "Microsoft.AspNetCore.Mvc.Razor.Extensions")]
```

This adds extra runtime references to types that are probably not used. 

This logic needs to be updated to consider whether you have any `.cshtml` files, and/or be based on some explicit gesture in the project file, or just obsoleted.

Basing this on the presence of `.cshtml` files could cause issues in the case will cause issues in the following cases:
1. You have no cshtml files at build time, and you are using runtime compilation when published
2. Youe **application** is an F#/VB project, referencing class libraries for views, and you are using runtime compilation

It's also an impactful change, because it requires evaluating an item group to evaluate a property, which means that it has to be in a target. 

-----

The `RelatedAssemblyPartAttibute` is purely for discovery of compiled views/pages and should be made conditional without reservation.

The `Razor.Hosting` attributes are for the settings used by runtime compilation. We could consider obsoleting these now that runtime compilation is outside the shared framework. However - we need to consider the impact on downlevel. If this logic is inside the `Razor.Design` package in 2.1/2.2 we can remove it from the SDK and say that it's not needed/supported in 3.0.

**Comment by mkArtakMSFT** [comment]
Closing this based on the work happening in the linked issue, where we will introduce a dedicated flag on the project level, which will indicate whether those attributes should be generated or not.

**Comment by rynowak** [comment]
That doesn't address this issue.

**Comment by pranavkm** [comment]
This is needed in preview4 (at least with the current state of things).The WebSDK specifies `AddRazorSupportForMvc`. Some Blazor templates reference the WebSDK, so you now get compilation errors stating it can't find Mvc.
