### ISSUE TITLE
Include support for proposed username in WsFederation request

### ISSUE THREAD

**Issue by TPucke** [aspnet/AspNetCore#8163]
### Is your feature request related to a problem? Please describe.
While adding ADFS integration to my v2.2 asp.net core application using WsFederation in the Security namespace I found (just lucky) that if I include a query parameter in the request to ADFS named `username`, the authentication prompt from ADFS will pre-populate the user name.  This improves my user experience because at the time I make this request, I already know who wants to authenticate. I was able to implement this in an event handler override for `WsFederationEvents.OnRedirectToIdentityProvider`, but I think it would be worth supporting this more natively in the WsFederation (or maybe RemoteAuthentication) middleware. 

### Describe the solution you'd like
In method `WsFederationHandler.HandleChallengeAsync`, the instance of `WsFederationMessage` is built and the parameters sent with this request could be expanded to include the username (and perhaps any other currently unsupported fields), maybe by using key/value pairs from the caller supplied properties. If this is unique to WsFederation maybe this means a new properties class derived from `AuthenticationProperties`. 

### Describe alternatives you've considered
I could just continue with my event override but I think you should support the full protocol, even things that are optional for the auth service.  People mostly don't know about these things if you don't have a field for it and this is a great way to document availability of a nice feature. 

### Additional context
na

**Comment by blowdart** [comment]
@Tratcher we don't have a way to pass anything into SignIn/Challenge do we? A key/value dictionary sounds awful, as people are simply going to make parameters up and see what sticks, it's a failure focused API.

**Comment by Tratcher** [comment]
We already do this with Google OAuth and OIDC via AuthenticationProperties. Is username a standard field or adfs specific?

**Comment by blowdart** [comment]
I can't see [anything](http://docs.oasis-open.org/wsfed/federation/v1.2/os/ws-federation-1.2-spec-os.html), but the specs are so spread out, who knows

**Comment by TPucke** [comment]
FYI I originally tried the query parameter because I found it mentioned [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-mwbf/54759c9b-4298-44f7-9026-f5ee815594d8)

**Comment by blowdart** [comment]
Oof, the use of that is super limited,

_<18> Section 2.2.3: The username parameter is not supported on Windows Server 2003 R2, Windows Server 2008, Windows Server 2008 R2, or Windows Server 2012. Additionally, in AD FS, if the AD FS behavior level is set to AD_FS_BEHAVIOR_LEVEL_2 or higher, this parameter is used to derive the IP/STS that receives the wsignin1.0 request message_

**Comment by TPucke** [comment]
For context, the version of server where this was successful for me is 2012 R2.  

Regarding the second part of the footnote, I believe the comment on the elevated behavior level setting (to server 2016 feature set) refers to a requirement that AD FS performs an additional function of identifying another IP/STS (based on the username value) to which the request should be forwarded when acting as a member of an AD FS farm, which is a separate feature, but hopefully not inconsistent with this suggestion. 

Thanks for considering.

**Comment by Eilon** [comment]
Closing because we think the current support is sufficient.
