### ISSUE TITLE
[Helix] InMemory.FunctionalTests-netcoreapp3.0 timeout on Ubuntu.1810.Amd64.Open

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#8164]
https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190303.15/workItem/InMemory.FunctionalTests-netcoreapp3.0/wilogs

cc @anurse

**Comment by anurse** [comment]
Hrm, timeout errors are fun... not sure what is equivalent to "skipping" here, since I don't really want to turn the entire test pass off.

**Comment by anurse** [comment]
We need xunit diagnostic logs and our test logs from Helix. Dumps might help too. #7774 is tracking that work.

**Comment by anurse** [comment]
https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190304.3/workItem/InMemory.FunctionalTests-netcoreapp3.0/wilogs as well.

Not sure the best way to mitigate these. We could disable all of InMemory.FunctionalTests in Helix but that's a really big hammer to apply. Both cases have been on Ubuntu (but different versions), we could try just disabling them on those platforms. That's still pretty big.

#7774 is tracking getting more data out of Helix on why these are failing, but I don't expect immediate progress on that.	

(cc @jkotalik @Tratcher @Eilon @muratg for any thoughts).

**Comment by Tratcher** [comment]
Yeah, getting a dump seems like the best route forward here. We've tried the xunit diagnostic logs before but their noise ratio is really bad. If we had a repro we could turn them on just for a given PR.

**Comment by anurse** [comment]
I propose closing this for now. We need to mitigate these better and I think we've decided to just shut the entire test project (InMemory.FunctionalTests) off on the OSes it hangs on. 

To get a clearer picture of that and avoid confusion, we'll look at BRT reports starting from now.
