### ISSUE TITLE
Allow `SkipOnHelixAttribute` to take specific configurations to skip on

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8169]
We should allow the `SkipOnHelix` to be constrained to only skip the test in certain configurations. We have some tests that are only flaky in one Helix configuration and it seems like a shame to disable that test for all Helix configurations.

**Comment by HaoK** [comment]
Yeah I filed something similar https://github.com/aspnet/AspNetCore/issues/7848

How about something like `[SkipOnHelix(Queues = "<SkipQueueId1>;<SkipQueueId2>")]`

**Comment by anurse** [comment]
Sounds good. I was getting ready to say this should probably just be merged in with the Flaky attribute we talked about but I think there's still a place for tests that need to be completed skipped on Helix because they aren't relevant for some reason.

I'll file a new issue for `[Flaky]`.
