### ISSUE TITLE
Consider alternative approach to determine MVC application parts

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#8176]
We use the deps file to determine what assemblies reference MVC today. In 3.0, this is essentially anything that references `Microsoft.AspNetCore.App`. An alternative to this would be to determine if we could instead look at the assembly metadata to determine if an assembly was compiled against MVC. This may limit the number of assemblies we scan for. In addition, this has two added benefits:

1) We set `PreserveCompilationContext = true` in the Razor.Sdk to persist information about transitive references to AspNetCore.App shared fx. Doing assembly would scan would no longer require that.
2) We do `DependencyContext.Load`  to get the merged graph of application + shared fx dependency file so references to the shared fx show up. With an assembly scan, we could limit to looking at the application's graph by using the `DependencyContextReader` APIs.

**Comment by javiercn** [comment]
I strongly agree with this statement. If we can make this a custom build task that we use on the Web SDK (provided some heuristic and some flag to override) that you are using MVC this would be great.

It can be as simple as to reuse the `[RelatedAssembly]` attribute to find the additional assemblies from the entry point assembly.

**Comment by davidfowl** [comment]
@mkArtakMSFT @pranavkm Isn't this done?

**Comment by pranavkm** [comment]
Yup.
