### ISSUE TITLE
HostBuilder ConfigureAppAConfiguration setup is overwritten with default implementation

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#8179]
_From @rholsman on Thursday, 21 February 2019 20:55:38_

HostBuilder ConfigureAppAConfiguration setup is overwritten with default implementation

When developing an application tar getting .NET Core 2.2, if a user creates a host builder and and uses the ConfigureAppConfiguration method and submits a delegate function as an argument; after the scope of the delegate has ended the default implementation for configuration is applied and seems to override the users configuration setup. 

```c#
var builder = new HostBuilder()
                .ConfigureAppConfiguration((hostContext, configurationBuilder) =>
                {
                    configurationBuilder.Sources.Clear();
                    IHostingEnvironment env = hostContext.HostingEnvironment;
                    configurationBuilder.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
                    configurationBuilder.AddEnvironmentVariables(prefix: "ASPNETCORE_");
                })
```

When creating an AppConfiguration like this at the end of the delegate method that does the configuration that are 3 configuration sources added to the configuration builder. In this example they are appsettings.json, appsettings.staging.json, and the environment variables. This allows the developer to configure the order they load in which controls what values become overridden. 

Once the scope of the delegate ends and you enter another delegate for something such as ConfigureServices; if you look in the HostBuilderContext at the configuration builder present there you can see that additional sources have been added. So the new list of configuration sources is now appsettings.json, appsettings.staging.json, environment variables, appsettings.json, and environment variables. In that order means any settings in the appsettings.staging.json that overrode settings in the base json configuration are overrode again by the base one. I have not determined why the environment specific config is not loaded from the default implementation as it is outlined in the documentation. But this doesn't seem to allow the developer to change how configuration is loaded with the delegate if the default way of loading is applied after it. 

_Copied from original issue: dotnet/core#2333_

**Comment by Tratcher** [comment]
HostBuilder has no default config sources, those must be coming from one of your other calls on the HostBuilder. Can you provide a complete example?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
