### ISSUE TITLE
.Net Core 2.2 Auth AzureAD Startup Generated Code is Complete?

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#8180]
_From @DanJ210 on Wednesday, 20 February 2019 16:08:02_

Generated startup code is very light and when I try it in other .Net Core 2.2 MVC Web Applications it doesn't work. I'm trying to find documentation on this small snippet of code but the .Net Core documentation is on 2.0 and doesn't talk about what's going on in 2.2, [.Net Core Documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/?view=aspnetcore-2.2)

# General

The code below is all that's in the .Net Core `Startup.cs` file to enable AzureAD auth. In previous .Net Core versions I had an `AccountController.cs` along with a couple of other files. In this, 2.2 version, there is none of those files which would be great if they are no longer needed in 2.2. But I'm trying to figure out how this is working because I'm updating .Net Core Web Apps that I have to 2.2 and I'm using the same code as shown below but am being told that `No AuthenticationScheme was specified, and there was no DefaultChallengeScheme found.` Which makes sense because it's not declared in `Startup.cs` but then how does this work for the app that .Net Core generates and not other apps?

So this is what I'm trying to understand, how does the code below work for the generated 2.2 .Net Core app and not when added to other 2.2 .Net Core apps?

```c#
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => Configuration.Bind("AzureAd", options));

            services.AddMvc(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            })
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
```

_Copied from original issue: dotnet/core#2331_

**Comment by Tratcher** [comment]
All of that [controller code](https://github.com/aspnet/AspNetCore/blob/master/src/Azure/AzureAD/Authentication.AzureAD.UI/src/Areas/AzureAD/Controllers/AccountController.cs) was moved into the Microsoft.AspNetCore.Authentication.AzureAD.UI package. If AddAzureAD compiles then you have that dependency already. That doesn't explain your AuthenticationScheme error though.

When you copied that code to a new project did you also copy the appsettings.*.json files to go with it?

**Comment by DanJ210** [comment]
The only settings in appsettings.json are the same settings I've seen every version produce. So the other app which was 2.1 already has the "AzureAd" section.

Yup the code compiles. But no default authentication or challenge scheme is specified. I don't see where it's specified in the 2.2 app either. Both apps have the same Microsoft.AspNetCore.Authentication.AzureAD.Ui package.

**Comment by Tratcher** [comment]
This is the line that sets default schemes: `services.AddAuthentication(AzureADDefaults.AuthenticationScheme)`

**Comment by DanJ210** [comment]
@tratcher yes but it doesn't work in other apps. What I'm trying to understand is how the above code works by itself in a generated 2.2 app but it doesn't work in other 2.2 apps. Other 2.2 apps require more.

**Comment by Tratcher** [comment]
For the complete diff between the app types I suggest looking here:
https://github.com/aspnet/AspNetCore/tree/master/src/ProjectTemplates/Web.ProjectTemplates, See the OrganizationalAuth pivot in in places like this:
https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/StarterWeb-CSharp.csproj.in#L21
https://github.com/aspnet/AspNetCore/blob/d24ec01224726fa85dc7683d0f70a94d9172bc94/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/appsettings.json#L12-L23
https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs
