### ISSUE TITLE
EditText code generation is broken

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8184]
The code generation for EditText is broken

![image](https://user-images.githubusercontent.com/1430011/53761645-ec209000-3e7a-11e9-8a0e-2141343f02be.png)

The expression is being turned into a literal string instead of an LValue. I'm not sure how this was missed - you can work around it by adding changing bind-Value="person.Name" into bind-Value="@person.Name".

**Comment by mkArtakMSFT** [comment]
Closing as a duplicate.
