### ISSUE TITLE
Add and document the pattern for forms and validation in components with collections of items

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8189]
Consider a model like:
```C#

public class Person
{
    public string Name { get; set; }

    public List<Contact> EmergencyContacts { get; set;  }
}

public class EmergencyContact
{
    public string Name { get; set; }

    public string PhoneNumber { get; set; }
}
```

How we would write a form that lets you add a dynamic number of emergency contacts? I tried this during some app building time, and there are some problems with it that we could make better.

## Issue 1

Doing the most obvious thing with a collection throws an IndexOutOfRangeException.

![image](https://user-images.githubusercontent.com/1430011/53763865-a8308980-3e80-11e9-844b-f090f8cf5bf6.png)

This works fine if you do it like this:

![image](https://user-images.githubusercontent.com/1430011/53763898-bbdbf000-3e80-11e9-8b94-09fde7b7549f.png)

## Issue 2

Validation doesn't automatically traverse the members of something so you have to manually add validation support for any sattelite objects you want validated.

Example: https://github.com/rynowak/ComponentFunTime/blob/master/Components/Shared/EmployeeEditor.razor#L85

**Comment by Andrzej-W** [comment]
@rynowak issue 1 is related to this original post:
https://github.com/aspnet/Blazor.Docs/issues/371#issuecomment-453764615
It was moved here:
https://github.com/aspnet/Docs/issues/10768
Unfortunately it is now closed and change in the doc is in my opinion to small - it only mentions lambda expressions. I can bet that people will have problems with binding also and your example is the best proof of it.

**Comment by SteveSandersonMS** [comment]
> Doing the most obvious thing with a collection throws an IndexOutOfRangeException.

One mitigating factor is that the *really* most obvious thing (`foreach`) actually does work.

Of course I do agree we should look for a good fix for the `for` case too though!

**Comment by danroth27** [comment]
For the issue with closing over a loop variable we're considering adding an analyzer to detect that situation: https://github.com/aspnet/AspNetCore/issues/10476

**Comment by danroth27** [comment]
I've filed https://github.com/aspnet/AspNetCore/issues/10526 to separately track the feedback that validation doesn't automatically traverse members. Closing this issue.
