### ISSUE TITLE
Subclassing of Form components doesn't work well

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8192]
I tried subclassing EditNumber to implement something similar to this

It doesn't work because the genered code from a razor file calls` base.BuildRenderTree` - you get the rendering of the base class and what you wrote.

![image](https://user-images.githubusercontent.com/1430011/53764794-1c6c2c80-3e83-11e9-83e4-2c9d43bad69d.png)

We should be able to fix this by making it unnecessary for a component to call `base.BuildRenderTree`. In general, it's a good idea if we can avoid extensibility points where an inheritor has to call `base`

**Comment by arivoir** [comment]
Completely agree, we should not be forced to call the base. Currently if the base is not called the StateHasChanged stops working.
