### ISSUE TITLE
Workarounds for @inherits Page<TModel> are causing spooky issues

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8193]
There is some WIERD stuff going on with using the type object in components. 

I suspect this is due to one of the various workarounds that's in place to allow you to write @inherits Foo<TModel> in _ViewImports.cshtml without a compiler error. I've never understood what's being done for this case and why it's the right solution - and I guess it's time for me to dig into this area.

This is breaking components and my heart. This is in the generated code.

![image](https://user-images.githubusercontent.com/1430011/53764930-7f5dc380-3e83-11e9-97c6-dfebfb80aa65.png)

There's no `TModel` in this class, the dictionary is defined as `Dictionary<object, ValidationMessageStore>`.

**Comment by rynowak** [comment]
Level of spookiness

![image](https://user-images.githubusercontent.com/1430011/53764981-a0beaf80-3e83-11e9-9646-3d0a12467f92.png)

**Comment by mkArtakMSFT** [comment]
@rynowak, if this is something @ajaybhargavb can handle, please reassign.

**Comment by danroth27** [comment]
We think support for _Imports.razor will help here: #6374
