### ISSUE TITLE
Update Razor Components and JSInterop to use System.Text.Json

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8205]
We need to integrate with System.Text.Json and replace our use of SimpleJSON. We don't have to expose the System.Text.Json APIs, but we need to have a default serializer to use with JS Interop.

Since we don't want to use JSON.NET in Blazor (code size), and we don't want to have breaking changes, using System.Text.Json is the most logical choice.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore-Internal/issues/1678?

**Comment by rynowak** [comment]
external > internal

**Comment by mkArtakMSFT** [comment]
Moving this to preview5 as the required .Net Core feature is going to land then.
