### ISSUE TITLE
WebApplicationFactory does not work from .NET Framework test assembly

### ISSUE THREAD

**Issue by woodne** [aspnet/AspNetCore#8210]
### Describe the bug
When attempting to write tests using the WebApplicationFactory from the Testing project, attempting to create a client against the factory, it blows up because it seems like it is assumed this is being run from a .NET Core assembly.

https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L133

```
System.InvalidOperationException : The provided Type 'FilterParamsTestStartup' does not belong to an assembly with an entry point. A common cause for this error is providing a Type from a class library.
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureDepsFile()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
```
### To Reproduce
1. Create a net472 test assembly
2. create an test that creates a WebapplicationFactory
3. attempt to call CreateClient for the factory.

### Expected behavior
The client is created and tests can be executed from a .net framework assembly.

**Comment by JosKrause** [comment]
@woodne  I stumbled upon this ticket when reading this one: https://github.com/dotnet/BenchmarkDotNet/issues/806

Might it be related? That ticket has a bit more detail and also includes the full stack trace, might you then be missing the project property to enable the behavior? (`PreserveCompilationContext `?)

_(If not feel free to remove/mute this comment)_

**Comment by woodne** [comment]
I don't think it is really related, but it is another thing that would fail. In my case I am trying to use a .NET Framework test assembly.

**Comment by javiercn** [comment]
@woodne Thanks for reaching out.
You need to reference a type on the entry point assembly of the app as the error message state. We use TStartup by convention, but you can use Program. We essentially need to know the assembly that contains the CreateHostBuilder method.

**Comment by javiercn** [comment]
Closing as there's no more action to be taken here.
