### ISSUE TITLE
Support for Component Islands

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8214]
**Scope**

You can add a component to a view or page, and it will become interactive once the browser opens a websocket connection. This is similar to pre-rendering except it doesn't require integrating with the client-side router. 

You can have multiple of these on a page.

Additionally, you can pass state (through parameters) to the component and it will *just work* to preserve your state when it becomes interactive.

**Comment by javiercn** [comment]
This is already possible once we have the strong reconnects. It is essentially prerendering.

**Comment by rynowak** [comment]
@danroth - is there anything we're tracking by leaving this issue open? I thought we did this.

**Comment by javiercn** [comment]
Closing this as we already have support for it on server-side blazor. We can file a new issue if we want to cover client-side too.
