### ISSUE TITLE
Run templating tests on Windows

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#8221]
We're [currently skipping Templating tests](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/test/ProjectTemplates.Tests.csproj#L9) on Windows because JAVA isn't available for Selenium to use.

We need to get java on the PATH and then we should be able to turn it back on by deleting the above lines.

**Comment by mkArtakMSFT** [comment]
@Andrew, is this something BRT will be handling as well?

**Comment by mkArtakMSFT** [comment]
If not, please reassign to @ryanbrandenburg.

**Comment by anurse** [comment]
BRT is for maintainance of whatever is running now, not for new stuff. That's not to say there won't be people on the BRT who also do engineering (like adding stuff to agents, new build scripts, etc.) but it's not what the BRT is for.

I don't really have space on my queue right now for this unless it's a higher priority than the stuff I've already taken on in re: BRT.

**Comment by mkArtakMSFT** [comment]
This should be fixed now by @javiercn 's improvements in this area.
