### ISSUE TITLE
Blazor 0.8.0 release blog code highlight is incorrect 

### ISSUE THREAD

**Issue by devSoheilAlizadeh** [aspnet/AspNetCore#8228]
There are some issues in the blog, the code Highlight doesn't show code format correctly.
![2019-03-06_10-43-29](https://user-images.githubusercontent.com/22220356/53862630-2fa30780-3ffd-11e9-8633-098b87bfa93c.png)

_the [blog](https://devblogs.microsoft.com/aspnet/blazor-0-8-0-experimental-release-now-available/)_

cc/ @danroth27

**Comment by danroth27** [comment]
Yeah, we recently migrated to a new blog platform, which caused some havoc with our code snippets. We're working on getting it all fixed up. Thank you for your patience!
