### ISSUE TITLE
DataProtection EFCore + Distributed Cache

### ISSUE THREAD

**Issue by schmitch** [aspnet/AspNetCore#8229]
### Is your feature request related to a problem? Please describe.
Hello, currently we run Asp.Net Core inside Kubernetes and use Redis as our Data Protection Service, however we treat redis storage as epheremal and sometimes it happens that all our infrastructure will be rebooted (kubernetes updates, etc...)

Everything will work out of the box. But since Redis will loose all data it might happen that redis restarts **after** Asp.Net Core which means that Redis will have **NO Protection Keys**, thus our application does not allow any login any more and other stuff like anti forgery

### Describe the solution you'd like
I think a good solution would be to have a Data Protection Service that can be cached through IDistributedCache. 
So the source of truth would be DbContext, however all keys could be gotten from redis until the key is missing there.
If keys are regenerated the Cache should of course be emptied.

The biggest problem here is probablly in case of a lot of requests that there might be a lot of cache misses, but in some scenarios it's probably not that bad if redis should only be treated as an in-memory cache.

I guess it might also be possible to just extend the EFCore Data Protectionen and let it configure to also use IDistributedCache.

So Basically it should be like that:
1. If Keys are in DistributedCache Read them (Bonus: if DistributedCache is dead, timeout after X and go to 2.)
2. Read Keys From DbContext and Save them to DistributedCache (Bonus: timeout after X for saving them to DistributedCache)

This is the Exception I get:
```
System.Security.Cryptography.CryptographicException: The key {d65ea672-3de4-4e63-b8e8-8bc451f65c51} was not found in the key ring.
  Module "Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector", in UnprotectCore
  Module "Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector", in DangerousUnprotect
  Module "Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector", in Unprotect
  Module "Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer", in Deserialize

Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
  Module "Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer", in Deserialize
  Module "Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery", in GetCookieTokenDoesNotThrow
```

Guess I would also be willing to submit a PR, if this Proposal is accepted. The only hardship I probably will have, is writing correct tests.

**Comment by natemcmaster** [comment]
@schmitch acknowledging we've seen your issue. I will discuss more with @blowdart and get back to you on how we will proceed. Tentatively putting in the 3.0 milestone so this gets tracked and reviewed in the next few weeks.

**Comment by schmitch** [comment]
Actually I've learned that this is not so necessary. 
Because DataProtection does in fact keep Secrets inside memory. Thus the database does not have many reads on the key.

So I'm closing this, since the Protection Keys are only loaded roughly at program startup or whenever a new key needs to be written/accessed.
