### ISSUE TITLE
Not Modified (304) returns Content-type

### ISSUE THREAD

**Issue by asn19595** [aspnet/AspNetCore#8230]
Content-type header is set when the response is 'NotModified' by FileStreamResult. Which strange according to 
https://tools.ietf.org/html/rfc7232#section-4.1

1. Using this version of ASP.NET Core 'v2.2.2'
2. Run this test 'WriteFileAsync_NotModified_RangeRequestedIgnored()' from 'FileStreamResultTest.cs'
https://github.com/aspnet/Mvc/blob/65af12f1f575fdaee893e0232416df29bb83d7fa/test/Microsoft.AspNetCore.Mvc.Core.Test/FileStreamResultTest.cs#L401
3. Add an Assert for Assert.Empty(httpResponse.Headers[HeaderNames.ContentType]);
4. The test fails as it contains the Content-type header with value according to the stream.

Expected behavior:
SHOULD NOT generate representation metadata other than the above listed fields (Content-type)
https://tools.ietf.org/html/rfc7232#section-4.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @asn19595.
We would happily consider a PR for this.

**Comment by ChiragRupani** [comment]
I would like to work on this issue. I have done setup and also identified the fix (https://github.com/aspnet/AspNetCore/blob/a673be3b9a2464cb20351f381e189a43beb6f426/src/Mvc/Mvc.Core/src/Infrastructure/FileResultExecutorBase.cs#L75) - either not set content type before it or set to Empty in it. I am verifying it.
Does it require to fix for other IActionResultExecutor classes as well?

**Comment by asn19595** [comment]
> I would like to work on this issue. I have done setup and also identified the fix at line
> [AspNetCore/src/Mvc/Mvc.Core/src/Infrastructure/FileResultExecutorBase.cs](https://github.com/aspnet/AspNetCore/blob/a673be3b9a2464cb20351f381e189a43beb6f426/src/Mvc/Mvc.Core/src/Infrastructure/FileResultExecutorBase.cs#L75)
> 
> Line 75 in [a673be3](/aspnet/AspNetCore/commit/a673be3b9a2464cb20351f381e189a43beb6f426)
> 
>  if (preconditionState == PreconditionState.NotModified) 
> 
> Fix is to either not to set content type before it or set to Empty in it. Should I work on it?
> Does it require to fix for other IActionResultExecutor classes as well?

I have already a PR in process for this. Thank anyways.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/aspnet/AspNetCore/commit/aa89639d629899985b27b4ad749f707efc8892cd
