### ISSUE TITLE
Can we add Razor Pages at Razor Component Server?

### ISSUE THREAD

**Issue by MaiHassanM** [aspnet/AspNetCore#8233]
### My Goal
I'm trying to mix between the usage of Razor component and Razor Page at one project by adding razor pages at the Server project that hosts the Razor Component.

### Steps to Reproduce

1. I've created a Razor Component project.
2. Made a simple Create function using Razor Component "Working perfectly fine"
3. At Startup of Server Project I've added
services.AddMvc(); & app.UseMvc();
4. I've added Pages folder that contains Razor Page.

### Expected Result
I should be able to Get the Razor page and make a post action

### Actual Result
The request never go to the post handler.
When I run the application and navigate to the path of the razor page, I get the page opened but when I make a post action, Its not working.
This is the Startup of the Server where I configured the usage of MVC
![1](https://user-images.githubusercontent.com/34300656/53879785-ff1c9700-4017-11e9-9c07-5c20bd0d228f.png)

This is the Razor Page Code "Simple Create page"
![2](https://user-images.githubusercontent.com/34300656/53879793-0479e180-4018-11e9-8d44-a4be46111a8d.png)
![3](https://user-images.githubusercontent.com/34300656/53879798-08a5ff00-4018-11e9-98de-567e998407d3.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MaiHassanM.
This is something we have it working and the Preview3 templates has a mix of both Razor Pages and components in the same project.
