### ISSUE TITLE
Make it so Helix runs can be rerun and preserve history

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#8235]
Right now, if you rerun a helix build after a build failure, the previous build that failed will be deleted. On VSTS, you see both attempts, but helix overrides it. 

cc @anurse

**Comment by anurse** [comment]
cc @HaoK

**Comment by natemcmaster** [comment]
_Build Team Triage:_ seems like this should be possible. If there is a build variable for the iteration number, we could add it to the Helix job name to make it unique from prior iterations. Putting into the next sprint for further investigation.

**Comment by anurse** [comment]
IIRC there isn't a variable for iteration number but we had the though of capturing a timestamp at the beginning of the run and using that timestamp as part of the job name.
