### ISSUE TITLE
Release Razor views/pages should be minified

### ISSUE THREAD

**Issue by lcsondes** [aspnet/AspNetCore#8236]
### Is your feature request related to a problem? Please describe.
When publishing your application the Razor views should be minified as part of the build.

### Describe the solution you'd like
Build my well-indented code, get output with no extra whitespace.

### Describe alternatives you've considered
Third-party kludges exist but they tend to do heuristic parsing of cshtmls with regexes or IndexOf. This should be built into the system itself which by definition understands cshtml perfectly.

### Additional context
https://github.com/aspnet/Razor/issues/423 is related but it seems to have been closed with no final comment when the project was archived.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lcsondes.
This is not an area we have immediate plans to invest in.

**Comment by effyteva** [comment]
@mkArtakMSFT Could this be scheduled for a future version perhaps?

**Comment by mkArtakMSFT** [comment]
Not really, @effyteva.
We usually prioritize asks based on community asks. So far, we haven't heard much feedback from the community that this is something very important. That said, we don't want to add work on our backlog, for which we don't see any mid-term need.
