### ISSUE TITLE
Add Web Application project support for build-time OpenAPI document generation

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#8242]
@glennc, the experience for this should be defined.
Here are the list of items we need clarity on:
- [x] Define the changes in `csproj` file indicating that the document should be auto-generated
  - no .csproj changes should be needed by default e.g. projects that include the new project must opt **out** of document generation during builds
- [x] Define the details regarding where the generated document should be placed (defaults)
  - will use the `obj/` directory by default
- [x] Define user's options for overriding our defaults
  - minimal
- [x] Define options for generating additional document(s)
  - no new options for this, build getting the document names list into `dotnet-getdocument` tool

**Comment by mkArtakMSFT** [comment]
Here are the list of items we need clarity on:
- [ ] Define the changes in `csproj` file indicating that the document should be auto-generated
- [ ] Define the details regarding where the generated document should be placed (defaults)
- [ ] Define user's options for overriding our defaults
- [ ] Define options for generating additional document(s)

**Comment by dougbu** [comment]
We have enough of a spec that I'll get a design PR out in this milestone. Reassigning to myself and placing the completed installation in Preview6.

**Comment by dougbu** [comment]
Work to do:
- [ ] create new Microsoft.Extensions.ApiDescription.Server project / package containing the bits of the old Microsoft.Extensions.ApiDescription.Design project / package specific to getting documents
- [ ] change MSBuild infrastructure to work on the _current_ project
- [ ] enhance `dotnet-getdocument` tool to use new `GetDocumentNames(...)` method in `IDocumentProvider` interface
  - main point is to avoid user ever having to duplicate document names in .csproj and `Startup` class
  - cache document names somewhere for use in MSBuild infrastructure
- [ ] as a follow up to #4945, place documents in `$(BaseIntermediateOutputPath)`
- [ ] implement `OpenApiGetDocuments` target
- [ ] add a project capability

related issues:
- #4912
- #4941
- #6582

**Comment by dougbu** [comment]
part 1: 4c8ca0b08067f0b821d728b1d3f22559f34fdfe7

**Comment by dougbu** [comment]
part 2 (of 2): b3ddd65a15456d9fdf4642d5f7174418f4e8b9c5
