### ISSUE TITLE
Replace Microsoft.AspNetCore.Blazor.Cli with new .DevServer package

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#8243]
To align with future .NET Core SDK changes, we need to replace our `<DotNetCliToolReference>` in the Blazor standalone app with a regular `<PackageReference>` that bundles the dev server.

This was kindly prototyped for us by @wli3 at https://github.com/aspnet/AspNetCore/compare/master...wli3:close-to-blazor-build2?expand=1

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, feel free to adjust the milestone, as this doesn't seem too important to me.
