### ISSUE TITLE
 System.Net.Http.WinHttpException: The operation timed out

### ISSUE THREAD

**Issue by shakibamor** [aspnet/AspNetCore#8245]
I am testing my code in my win10 machine and works fine.

//myCode
  var req = new HttpRequestMessage(HttpMethod.Get, url);
            var res = await client.SendAsync(req);

I am using .net core 2.0.0 and sdk 2.1.103. 
When i publish the project in a winServer2012 R2
I get below error for my httprequest: 

 [ERR] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---

I am sending request to the secured services. I had this issue just for POST request then I migrate to 2.1 and it got worse because this timeout error happened for both GET and POST requests. I switched it back to 2.0. but still all http requests get timeout issue.

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#35839
