### ISSUE TITLE
Integrated Windows Authentication Library

### ISSUE THREAD

**Issue by JaimeStill** [aspnet/AspNetCore#8252]
### Is your feature request related to a problem? Please describe.  
I've been doing app development on closed government networks for a while now, and these environments all run Windows domains. The issue that I initially encountered in this environment was how to appropriately extend the current user into my database and extend the available properties.  

Namely, this is for things like app-based RBAC, user preferences, things of that nature. I've put together a workflow that I use internally for extending Windows Authentication's `IIdentity` from `HttpContext` when running on IIS. It would be nice to see a workflow for this purpose standardized for Windows Authentication. Additionally, a proper mock library for getting things built on a dev machine that's not connected to an AD domain would be outstanding.  

### Describe the solution you'd like  
I've documented my process in both [Active Directory Authentication](https://gist.github.com/JaimeStill/539af65518091f7b8e6b9e003a493baa), as well as [Active Directory Authorization](https://gist.github.com/JaimeStill/468fca767ffabb977346eff81e2ace0c). I've also confirmed that this approach works with AWS Directory Services, and with some tweaks, with Azure Active Directory.

**Comment by blowdart** [comment]
We've tended to steer away from this because the extending part is always custom to every single customer, people want different properties, different admin models and so on. Making it generic wouldn't really help anyway, as the lines of code to implement would be almost the same as it would be starting from scratch.

Frankly Windows Auth is "special", it doesn't work like any other auth type, and it never will, for example it's IsInRole() works, but enumerating roles gives you nothing but SIDs.

**Comment by JaimeStill** [comment]
It would at least be helpful to specify this in the documentation and use a generic example to point people in the right direction. In my use case, I don't even use Active Directory roles (unless I use a situation where a user has to be in a role to access the app in the first place).

**Comment by blowdart** [comment]
That's fair. We've been looking at kerberos auth as a wider issue, and better documentation would cover both.

**Comment by Zymex** [comment]
I also think it would be good for the docs. It does lay a foundation for customizing your application needs. Def helped me out in certain aspects.

**Comment by JaimeStill** [comment]
Feel free to reach out if there's any way I can help!

**Comment by anurse** [comment]
Closing in favor of #12938
