### ISSUE TITLE
Fix template resource IDs

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#8253]
From @phenning :

> Howvber, it looks like the string has changed since in your repo since I snapshotted it into VS:

```xml
  <data name="1027" xml:space="preserve">
    <value>gRPC Application</value>
    <comment>template name for gRPC application template</comment>
  </data>
  <data name="1028" xml:space="preserve">
    <value>A project template for creating a gRPC ASP.NET Core application.</value>
    <comment>template description for gRPC application template</comment>
  </data>
```

>
>I’ll update the string in our branch to match what you have in your repo.
>
>Additionally, looking at your repo, we already have the strings for Worker Service as well, but the Ids you are using for RazorComponents template are the same Ids as for Worker Service template, so this needs to be fixed for the Razor Components template or you’ll see two Worker Service templates in VS, but one will actually be Razor Components.
>
>https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/RazorComponentsWeb-CSharp/.template.config/vs-2017.3.host.json
>
>Please update RazorComponents to use ids 1029 and 1030, I’ll get those strings into our build today for 16.1, after you do that, all the three visible templates in the bug should be localized after the 16.1 builds start coming out.

**Comment by ryanbrandenburg** [comment]
Fixed by https://github.com/aspnet/AspNetCore/pull/8301.
