### ISSUE TITLE
Provide template(s) for browser extensions built with Blazor

### ISSUE THREAD

**Issue by adm7373** [aspnet/AspNetCore#8255]
### Is your feature request related to a problem? Please describe.
I like building browser extensions (mostly Chrome extensions) and I'd love to try out Blazor, but I'm not sure where to start. It would be useful to have either a template to start from or a Hello World example of a Chrome Extension (or generic browser extension) running Blazor.

### Describe the solution you'd like
It would be super cool to duplicate the example extensions provided by Google: https://developer.chrome.com/extensions/samples

### Additional context
I am interested in working on this, but would love any help from someone more knowledgeable about Blazor!

**Comment by mkArtakMSFT** [comment]
Thanks for your feature request. This is not something we plan to add support for in the near future.
If you're interested in this and are looking for help, feel free to jump on the Blazor community gitter: https://gitter.im/aspnet/blazor
