### ISSUE TITLE
由于配置问题，无法加载模块 DLL“C:\Program Files (x86)\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll”。当前配置仅支持加载为 x86 处理器架构构建的映像。数据字段包含错误号。要了解有关此问题的更多信息，包括如何解决这类处理器架构不匹配错误，请参见 http://go.microsoft.com/fwlink/?LinkId=29349。

### ISSUE THREAD

**Issue by ghd258** [aspnet/AspNetCore#8268]
v3.0.0-preview3-19153-02
由于配置问题，无法加载模块 DLL“C:\Program Files (x86)\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll”。当前配置仅支持加载为 x86 处理器架构构建的映像。数据字段包含错误号。要了解有关此问题的更多信息，包括如何解决这类处理器架构不匹配错误，请参见 http://go.microsoft.com/fwlink/?LinkId=29349。

**Comment by jkotalik** [comment]
Duplicate of https://github.com/aspnet/AspNetCore/issues/8249
