### ISSUE TITLE
[Blazor] Intellisense not suggesting Razor Components in preview3

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#8280]
### Describe the bug
I have a components library with all kinds of components. Every component can be overrided with the custom implementation. The problem is that in the newest version of RC/Blazor I cannot use the components with extensions `*.cshtml` or `*.razor`. For some reason they are not recognized when used through the code.

### Screenshots
![image](https://user-images.githubusercontent.com/900302/53969945-0025f500-40fa-11e9-82a1-63a339896735.png)

![image](https://user-images.githubusercontent.com/900302/53969973-0ddb7a80-40fa-11e9-8a60-18ad00b067e2.png)

### Additional context
It doesn't matter in what project I try to use them. They're not visible even in the same project.

**Comment by stsrki** [comment]
By adding `<_RazorComponentInclude>*.cshtml</_RazorComponentInclude>` to the project file everything works as expected.
Don't know why it will not work with `*.razor` file extension, I thought it should be used to distinguish Razor Components from regular Razor files!?

**Comment by danroth27** [comment]
Correct, there are a number of issues right now with .razor in Preview3. These are known issues and will be addressed in Preview4. To use .cshtml you need the property that you've already discovered.
