### ISSUE TITLE
Please can we have some way to know we are pre-rendering so our components don't error

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [aspnet/AspNetCore#8287]
### Is your feature request related to a problem? Please describe.
Components that inject IJSRuntime in Razor components don't know whether the object they receive can be used.
During PreRendering the JSRuntime injected is non-null but cannot be used, so we get errors which break our components if they are part of the initial page load.
If your component that requires JSRuntime is on another "page", like the Counter page, then everything is good.

### Describe the solution you'd like
Please either do not inject a non-functional JSRuntime, Or provide a property we can check to know whether we can safely use it.

### Describe alternatives you've considered
Don't new up the JSRuntime until after PreRender is complete

**Comment by Andrzej-W** [comment]
Problem is tracked here: #8404

**Comment by pjmagee** [comment]
Is it worth closing this issue if we know it's being tracked elsewhere, so we can keep the log of issues focused and minimum amount of open duplicates?

**Comment by SteveSandersonMS** [comment]
Since this is described in #8404, I'll close this as a duplicate.
