### ISSUE TITLE
 This server does not support the IHttpRequestBodySizeFeature

### ISSUE THREAD

**Issue by andre-ss6** [aspnet/AspNetCore#8293]
I have an MVC action decorated with `RequestSizeLimitAttribute`. However, I'm seeing the following message in my logs every time I hit that route: `A request body size limit could not be applied. This server does not support the IHttpRequestBodySizeFeature`. 

I'm running ASP.NET Core 2.2 with IIS on Windows Server 2016.

I couldn't manage to find not even a single mention of this in Google. I'm guessing it's because I'm running the app behind IIS. If that's the case, does that mean that _only_ web.config limits are supported?

**Comment by jkotalik** [comment]
Are you using IIS In-process? If so, we may have a feature gap there.

So yes, you can set limits on the request body length via https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/ and setting in your web.config, but that isn't ideal. We probably should add it to InProcess.

Can you try running out-of-process and see if the feature exists there?

**Comment by andre-ss6** [comment]
Bummer :/ Yea, I'm using in-process. I'll evaluate whether it's best for me to switch to out-of-process or use web.config limits. 

Do you have any plans on adding support for that on in-process scenarios?

**Comment by jkotalik** [comment]
I feel like this was just an oversight. We can evaluate how hard this would be to do in IISInprocess and try to put it into 3.0.

**Comment by Tratcher** [comment]
We should do this, the web.config settings are not granular enough.

**Comment by blowdart** [comment]
Yes you should.

**Comment by zuckerthoben** [comment]
We have the same problem. We are hosting In-Process in Azure. 
Does this mean that there is no RequestSizeLimit when on IIS? Or does it mean that if I reach the limit and I wanted to disable it, I get an error? 
Is there any workaround to only activate the feature if the hosting platform supports it?

**Comment by jkotalik** [comment]
There is a RequestSizeLimit that is part of IIS: https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/. I'm fairly certain this is used when hosting in Azure (not sure what the value is on top of my head). The RequestSizeLimitAttribute can't be used when hosting with IIS today though, so you would need to know which server type you are deploying for. 

I'm going to start working on a fix for this now though.

**Comment by AFDevMike** [comment]
I see this is closed, but am under impression this is where I would ask.  We are experiencing this issue on Azure hosting with Asp.Net Core 2.2.  We are hosting In-Process in Azure and using the `[RequestSizeLimitAttribute]` [documented here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.requestsizelimitattribute?view=aspnetcore-2.2) to decorate a single controller endpoint.  

Similar question as @zuckerthoben, is there a workaround and or is this attribute deprecated however it works under the hood?

**Comment by Tratcher** [comment]
@AFDevMike it wasn't supported for 2.2 in-proc. It will be supported in 3.0.

The workaround is to use out-of-proc.

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [x] Relevant XML documentation comments for new public APIs are present.
    * [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [x] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: https://github.com/aspnet/AspNetCore.Docs/pull/12318
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: 3.0.100-preview6-012113
            * ASP.NET Core Runtime: 3.0.0-preview6-19279-01
            * .NET Core Runtime: 3.0.0-preview6-27728-04
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
