### ISSUE TITLE
Question: Passing JWT Authentication header

### ISSUE THREAD

**Issue by rodius** [aspnet/AspNetCore#8297]
I Have to implement a push notification service using ASP .Net Core. as obvious choice is to use SignalR Core.

Our platform setup is using Azure App gateway and it is configured to not allow unauthenticated requests.

We have setup WebSockets communication with SignalR.

Under the hood , SignalR Core follows these steps:

    POS ../negociate -> OK with hub_token and supported transport
    GET (sends Upgrade header and WebSockets token)../Hub?id={hub_token} -? fail

when investigating why the step 2 does not upgrade the connection to a WebSocket connection , I have noticed that the GET request is missing Authorization header. Obviously AG block this request and doesn't even get to the API.

I have tried manually to make a "handshake" with postman. the above steps :

    OK
    included Authorization JWT header -> result 101 ,and Fiddler confirm the connection is opened.

I have researched the documentation and found that Authorization headers are not supported.

did anyone tried any workaround ? hen is the next release of the @aspnet/signalr client?

**Comment by muratg** [comment]
Not being able to set headers is a limitation of WebSockets on the browsers. Does Azure Application Gateway support sending the JWT data in the query string instead?
 
If not, only think we can think of is downgrading to another transport. 

cc @bradygaster
