### ISSUE TITLE
Remove pubternal types from Kestrel

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#8306]
MVC recently made all pubinternal types in MVC internal via https://github.com/aspnet/AspNetCore/issues/4932. As a reminder, `pubinternal` types are types that are declared as public but put in an .Internal namespace. 

In ASP.NET Core 3.0, we should do the same in Kestrel, specifically for the Microsoft.AspNetCore.Server.Kestrel.Core.Internal namespace. Reference assemblies will also show any pubinternal changes.

cc @muratg @halter73 @Tratcher

**Comment by Tratcher** [comment]
Just Kestrel? I would expect this to extend to most of AspNetCore.

**Comment by jkotalik** [comment]
I mean sure, but let's start somewhere. The issue for MVC was individualized.

**Comment by muratg** [comment]
With the targetting pack work, I think this is more critical now. Making breaking changes will be harder in these technically public types.

@Eilon @DamianEdwards @davidfowl thoughts?

**Comment by Tratcher** [comment]
@jkotalik Think bigger 😁

**Comment by halter73** [comment]
Definitely not just Kestrel, though I've heard through the grapevine that EF actually likes pubternal.

**Comment by Eilon** [comment]
EF Core is sticking with pubternal. But MVC removed a lot of pubternal (either make true `internal` or make true `public`). Up to each feature area to make a call.

**Comment by pranavkm** [comment]
https://github.com/aspnet/AspNetCore/issues/8308 if there's interest in doing for everything that ships in the targeting pack

**Comment by jkotalik** [comment]
Thanks @pranavkm <3.

**Comment by benaadams** [comment]
You'll break the TE Platform tests though as that uses pubternal apis /cc @davidfowl

**Comment by benaadams** [comment]
If the used apis were made public they'd have to switch from `Span<byte>` to `ReadOnlySpan<byte>`; which they should do eventually anyway.

**Comment by Eilon** [comment]
TE Platform tests definitely shouldn't be using pubternal types 😭

**Comment by jkotalik** [comment]
May be some follow up to decide if some types should be public.
