### ISSUE TITLE
Shipped Blazor 0.9.0 templates still contain RestoreAdditionalProjectSources

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#8316]
Repo steps:
- Install .NET Core SDK Preview 3
- `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.9.0-preview3-19154-02`
- `dotnet new blazor -o BlazorApp1`
- Open *BlazorApp1.csproj*

Expected result:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RunCommand>dotnet</RunCommand>
    <RunArguments>blazor serve</RunArguments>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="0.9.0-preview3-19154-02" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.9.0-preview3-19154-02" PrivateAssets="all" />

    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.9.0-preview3-19154-02" />
  </ItemGroup>

</Project>
```

Actual result:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RunCommand>dotnet</RunCommand>
    <RunArguments>blazor serve</RunArguments>
    <RestoreAdditionalProjectSources>
      https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json;
      https://dotnet.myget.org/F/blazor-dev/api/v3/index.json;
    </RestoreAdditionalProjectSources>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="0.9.0-preview3-19154-02" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.9.0-preview3-19154-02" PrivateAssets="all" />

    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.9.0-preview3-19154-02" />
  </ItemGroup>

</Project>
```

**Comment by danroth27** [comment]
@SteveSandersonMS FYI - looks like we still have issues building the templates without `RestoreAdditionalProjectSources` when we release.

**Comment by Rymix** [comment]
Yeah, without additionnal package, build doesn't work.

**Comment by SteveSandersonMS** [comment]
@danroth27 This is expected. We investigated and determined that our build system currently makes no differentiation between nightly builds and "final" preview releases, so these can't be removed automatically. We decided that there isn't really any serious drawback to including them for the preview releases, so it's only something we need to do finally for RTM, by which stage the build system will have to have some way to differentiate the final build.

If you think this is problematic please let us know, but otherwise I suggest closing this.

**Comment by Rymix** [comment]
I'm getting a weird issue right now :

The specified framework 'Microsoft.NETCore.App', version '3.0.0-preview3-27503-5' was not found.
On the new template.

**Comment by danroth27** [comment]
@Rymix Please open a new issue with the details on you're environment (`dotnet --info` output, OS, Blazor version installed) and well take a look.

**Comment by javiercn** [comment]
We can't do anything about this yet.

**Comment by javiercn** [comment]
Moving to preview5

**Comment by javiercn** [comment]
@danroth27 @SteveSandersonMS Do we need to publish the blazor preview packages to nuget? After that, can this be done?

**Comment by danroth27** [comment]
Yes, the Blazor packages get published to NuGet. For Preview4 we are leaving the additional package sources as is.

**Comment by javiercn** [comment]
I’m talking preview5 now

**Comment by SteveSandersonMS** [comment]
The only reason we explicitly have the `RestoreAdditionalProjectSources` is so people can use the dev feed to get the latest template VSIX continuously.

We can remove it any time we want, but it will make things harder for people trying to use the dev feed.

The ideal would be to remove it conditionally based on whether we're building a "dev" build or a "release" build. Maybe it's possible to do this based on whether the current branch name is `master` or not.

If we can't remove it conditionally, then we either remember to remove it manually once we make a "release" branch, or we just remove it in `master` and let the people using the dev feed suffer.

**Comment by javiercn** [comment]
@SteveSandersonMS What is the value of pointing to the dev feed these days? Is that something people do this days? Or do they rely on the monthly build?

I understand it on the beginning of the project, but now we get pretty stable builds. The only thing I can think of is getting updated mono bits.

**Comment by SteveSandersonMS** [comment]
I don't have any numbers on it. But the value for us, historically, has been that often we've had bug reports about the next version even before it's been released, so we've been able to pre-emptively fix regressions.

**Comment by danroth27** [comment]
Please also note that the dev feeds we include I believe are no longer the correct ones: https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md

**Comment by mkArtakMSFT** [comment]
The decision here is to make a hack and in the Build pipeline use the branch as the indicator for using the right feed.

**Comment by javiercn** [comment]
I’m not sure I understand.

**Comment by SteveSandersonMS** [comment]
The idea is just that, assuming the build system has some way of passing "current branch name" into MSBuild, then we could adjust the conditional-inclusion rule for `RestoreAdditionalProjectSources` to be "include only when current branch name equals `master`".

**Comment by wcrosby5151** [comment]
How do I get the Blazor 0.9.0 templates into the right area so that I can create a new project.  No matter what I do, the templates never become visible with this release.  Is there some trick that I am missing?

**Comment by danroth27** [comment]
@wcrosby5151 You should probably open a new GitHub issue with details about what you've done so far to setup your machine and we can then try to help you out.
