### ISSUE TITLE
ServiceProjectReference Alternative documentname not getting pickedup

### ISSUE THREAD

**Issue by KLuuKer** [aspnet/AspNetCore#8319]
I have a project that contains multiple api's (public, admin specific, etc),
and the appropriate swagger documents generated by nswag all working fine.

In another project that needs to consume the admin specific api i have this block:
```xml
<ServiceProjectReference
 Include="../MyProjectWithApiMyProjectWithApi.csproj"
 CodeGenerator="NSwagTypescript"
 DocumentPath="MyOtherApi.json"
 DocumentName="admin-v1"
 Namespace="My.Custom.Namespace"
 ClassName="MyOtherApiClient"
 GenerateNSwagTypeScriptOptions="/template:Angular /OperationGenerationMode:SingleClientFromOperationId /RxJsVersion:6 /UseSingletonProvider:true /InjectionTokenType:InjectionToken" />
```

**Expected:** it would generate a json file for the admin-v1 document

**Actual:** it's generating json for the default v1 document

@dougbu **said:**
>"...Specifically, the `%(Command)` setup in [Microsoft.Extensions.ApiDescription.Design.targets#L181-L205](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Extensions.ApiDescription.Design/src/build/Microsoft.Extensions.ApiDescription.Design.targets#L181-L205) doesn't include the `--documentName` option"

**Implementation detail invoking my project:**
I added a `Environment.CommandLine` dumper to my project to see the arguments
and it seems someone is forgetting to submit the document name (I think it's the Microsoft design package)
```
C:\Users\yourname\.nuget\packages\microsoft.extensions.apidescription.design\0.1.0-preview1-10773\tools\netcoreapp2.0\GetDocument.Insider.dll
 --assembly C:\path_to_webapi_project\bin\Debug\netcoreapp2.2\project_name.dll
 --tools-directory C:\Users\yourname\.nuget\packages\microsoft.extensions.apidescription.design\0.1.0-preview1-10773\tools\netcoreapp2.0
 --output C:\path_to_project_client\documentpath_here.json
```

**Versions:**
Windows 10 x64
VS2017 15.9.7
.net core sdk 2.2.104
NSwag.ApiDescription.Design 12.0.14

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/NSwag/issues/2005

**Comment by dougbu** [comment]
Self-assigning

**Comment by dougbu** [comment]
edb91d0f
