### ISSUE TITLE
MemoryCached dictionary removed even though CacheItemPriority.NeverRemove was set

### ISSUE THREAD

**Issue by guylando** [aspnet/AspNetCore#8322]
We use MemoryCache to cache a big (thousands of records) dictionary forever. We don't want it to ever be removed from the cache as long as the process is running. We thought that setting CacheItemPriority.NeverRemove will insure that however discovered that some or all items of the memory cache got removed after a while.

Net core 2.1.7 targeting net472
Hosted in kestrel behind iis 10.
The app pool idle time is configured to 20 minutes. When the situation happened there was a user request about 100 seconds before the error we received (our custom error indicating an element was missing from the cache even though it was in there before) and also we see log messages every 2 seconds from the site so there is no chance the worker was killed.

I am thinking to register RegisterPostEvictionCallback to see what is the reason of eviction.

1)
Is there any reason which can remove an element from cache even though CacheItemPriority.NeverRemove was set when all other cache options are the default ones?

`new MemoryCacheEntryOptions() { Priority = CacheItemPriority.NeverRemove }`

2)
Or is there any reason a kestrel worker hosted on iis will be restarted after a while before the app pool idle time was reached?

**Comment by Tratcher** [comment]
You should be able to confirm if the app restarted based on event logs and application logs.

**Comment by guylando** [comment]
Waiting for the new logs writing code to be uploaded to production and will then be able to check.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
