### ISSUE TITLE
. NET core 3 preview 3 - razor component - unable tu use JsRuntime on the component lifecycle

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#8327]
### Describe the bug
Using JsRuntime.InvokeAsync in afterRender (or AfterRenderAsync) on  a component raise exception "System.InvalidOperationException : 'The JavaScript runtime is not available during prerendering.'".
On .NET core 3 preview 2 with the static JsRuntime, i didn't have this problem

### To Reproduce
Inject a IJSRuntime in a component
[Inject]
protected IJSRuntime JsRuntime{ get; set; }

Use it in afterRender
protected override async Task OnAfterRenderAsync()
        {
            await this.JsRuntime.InvokeAsync<object>("tooltip", null);
            await base.OnAfterRenderAsync();
        }

### Expected behavior
Having a method in the component where i can call my js after component rendered. It seem not possible now on the AfterRender method

**Comment by pranavkm** [comment]
cc @javiercn.

**Comment by javiercn** [comment]
Are you prerendering the component?

**Comment by julienGrd** [comment]
for prerendering I don't know, i just migrate my application, before everything was OK (with the static JSRuntime).

**Comment by javiercn** [comment]
Do you have an Index.cshtml in your app with a call to Html.RenderComponentAsync? If so you are prerendering the app and the JS runtime is not available at that point.

You need to wrap the calls to the JSRuntime in a try catch (we will be making this nicer in the future) and that should do it.

If that’s not the case, can you provide a minimal repro project?

**Comment by julienGrd** [comment]
@javiercn yes exactly ! After migration, is see is the new way to render the app. So if i understand, the code is execute two times ? one time during prerendering and one ime during rendering ? (the first js call fail and the second suceed).

**Comment by javiercn** [comment]
@julienGrd That is correct. Prerendering renders the UI for the first time and then after the client connects we render the UI again. During prerendering the JavaScript runtime is not available, so JS interop calls need to be wrapped up in try..catch blocks. we are looking into how we want to expose this situation to users so that the javascript calls can be conditionally emitted, but ultimately it's something you need to be aware of.

**Comment by DNF-SaS** [comment]
@javiercn maybe you could also have a look here? https://github.com/aspnet/AspNetCore/issues/8274

**Comment by julienGrd** [comment]
@javiercn : Maybe i don't understand well but this kind of behavior will be problematic. 
Indeed, what happened if I launch sql orders in my code ? every instruction will be execute two times ? => really bad for performance ! and worst ! if there is some insert/update/delete statement !
But maybe in the future you will find another way to do this ?

**Comment by danroth27** [comment]
We are now tracking some improvements for handling prerendering here: https://github.com/aspnet/AspNetCore/issues/8404. 

Closing this one in favor of the new issue.
