### ISSUE TITLE
Reenable IISExpress tests after SDK update

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#8329]
https://github.com/dotnet/cli/issues/10947 is fixed but we need an update.

**Comment by anurse** [comment]
I sure hope we have the necessary SDK update :). Parking this in preview 6 for now.

**Comment by jkotalik** [comment]
There are a lot of tests disabled and it should be a simple revert.

**Comment by anurse** [comment]
@jkotalik did this already :).
