### ISSUE TITLE
Transport text log does not contain timestamps

### ISSUE THREAD

**Issue by kristoferMoore** [aspnet/AspNetCore#8333]
### Describe the bug
when following the documentation here 
https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-in-the-net-client-windows-desktop-apps
enabling signalr Server side tracing does not produce a log file with timestamps, this makes troubleshooting issues difficult.

using Microsoft ASP.NET Core version 2.4.0.0
enable client side tracing referenced above for net framework 4.6.1 asp.net web app in web.config
generate traffic 
open transport.log and note that no entries contain timstamps

### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Expected behavior
it is expected when looking at trace information that timestamps would be included

**Comment by anurse** [comment]
Moving this to SignalR/SignalR as this is an issue in ASP.NET SignalR.

**Comment by anurse** [comment]
This issue was moved to SignalR/SignalR#4359
