### ISSUE TITLE
Asp.Net Core IIS InProcess AspNetCoreModuleV2

### ISSUE THREAD

**Issue by smokeelow** [aspnet/AspNetCore#8338]
### Describe the bug
Yesterday I reinstalled VS 2017 and it downloaded latest AspNetCoreModuleV2.
After that when i tried to debug/run my asp.net core app via VS 2017 using IIS InProcess i received warning popup
![microsoft visual studio 2019-03-08 18 34 37](https://user-images.githubusercontent.com/1822237/54046659-b1518b80-41dd-11e9-898c-794a43134ee8.png)

I investigated the issue and found out that it related to AspNetCoreModuleV2
Here is the log of the fail request [fr000016.txt](https://github.com/aspnet/AspNetCore/files/2946946/fr000016.txt)

Then I copied Asp.Net Core Module folder from the old IIS Express and it started working correctly.
Below you can download both versions:
[AspNetCoreModuleV2 - LATEST](https://github.com/aspnet/AspNetCore/files/2946953/Asp.NetCoreModule-NEW_GIVES_ERROR.zip)

[Asp.NetCoreModuleV2 - OLD](https://github.com/aspnet/AspNetCore/files/2946971/Asp.Net.CoreModule-OLD_WORKS_OK.zip)

On a video you can see how it works https://monosnap.com/file/Qp9ivyX34VRO6xzEhHnyt6ffxQvrYG
(After replacing AspNetCoreModuleV2 with old one you can see that my app started to accept requests etc.)

Here is my dotnet info
![cmder 2019-03-08 20 20 54](https://user-images.githubusercontent.com/1822237/54047487-d0e9b380-41df-11e9-9606-759cfd8c574e.png)

**Comment by jkotalik** [comment]
To confirm, did you install the 3.0-preview3 hosting bundle? From what I can tell, it looks like you did. Check the event log, you will probably see an error saying something about a bitness mismatch. 

There is a known issue with the latest hosting bundle. See https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md#preview-3. I think this is a dup of https://github.com/aspnet/AspNetCore/issues/8249.

**Comment by smokeelow** [comment]
@jkotalik yes, I installed it yesterday and then removed it.
thanks for the links

**Comment by jkotalik** [comment]
Closing as duplicate.
