### ISSUE TITLE
SignalR: per-client filtering prior to send

### ISSUE THREAD

**Issue by kierenj** [aspnet/AspNetCore#8346]
### Is your feature request related to a problem? Please describe.
I'm looking to implement "watch" functionality: the ability for a client to watch for changes or messages relating to a particular object or set of objects based on their ID, or a certain property.  SignalR seems a great match for this kind of functionality, but I can't think of an efficient way for a client to precisely indicate what kind of invocations it wants to receive.  The server can only help it at the moment by moving it into a group.

### Describe the solution you'd like
I'd like some way to specify a predicate or in some way filter messages (invocations, I suppose) from being passed to a client, perhaps based on the contents of `Items`.

### Describe alternatives you've considered
Groups can do this: a client request to be added to group "Orders:ByCustomer:123".  But server-side invocations would need to send to one group for each possible filter scenario: "Orders:ByCustomer:123", "Orders:ById:456", "Orders:ByCountry:UK", etc.  As I understand it having so many groups (and sending to all of them, even if no-one is connected) won't scale particularly well.

### Additional context
I hope I'm just not seeing the wood for the trees here :)  I am not sure of an appropriate API here, either.  For a non-strongly-typed hub, a `bool ShouldSend(client, method, params)` could exist (I'm guessing predicates should be super quick and not do anything that would warrant `async`).  For strongly-typed, perhaps an Moq-like invocation matching syntax with `Expression`s?  Doesn't sound ideal, I know.

It could be that this use case perhaps just not a great match for SignalR?

**Comment by muratg** [comment]
This is an interesting idea. We do not plan to implement this at this time, but this can be considered in the future.

**Comment by kierenj** [comment]
Thanks, would you be able to advise - is it a really bad idea to use SignalR in this way as it is? Should I go for raw websockets instead?

**Comment by muratg** [comment]
Not knowing your exact design, I'd still recommend using SignalR because of the more integrated programming model and features. If you already have good experience with raw websockets model (and you know you won't need the other fallback transports) than perhaps using websockets directly would be interesting too.

**Comment by kierenj** [comment]
No problem, thanks.  I sketched out some ideas and think that implementing something from scratch would involve solving a large number of problems that SignalR tackles already.  However, it doesn't seem there's a good place to hook in and change behaviour.

As best I can tell, `HubConnectionHandler` is the place where a `HubConnectionContext` is instantiated.  From within the two `WriteAsync` variants of the context, I can make the write to the transport conditional based on the message.

Would you consider using a factory, or just DI, to allow for use of an overridden `HubConnectionContext` type?  Else I can see I can inject a custom `HubConnectionHandler` service, which is fine, but would be 99% the same as the existing implementation, so I'd need to keep it in sync.

**Comment by muratg** [comment]
cc @halter73 and @anurse in case they have thoughts on this as well.

**Comment by anurse** [comment]
> As I understand it having so many groups (and sending to all of them, even if no-one is connected) won't scale particularly well.

I don't think using groups would scale any worse than a predicate system would. Groups are processed almost exactly like the predicate you mentioned. We iterate over clients and if they are in the requested group we send the message to them. So I wouldn't expect to scale any worse than if we implemented this predicate model.

**Comment by kierenj** [comment]
Ah ok - I had figured sending a message for each filter field - eg shipment:byid:123, shipment:bydepot:345 and shipment:bycustomer:456 - would have more overhead than one “shipmentchanged” message with all fields contained within, in terms of (for example) pushing to the redis backplane?

**Comment by anurse** [comment]
Right now, groups have some impact on the Redis backplane (each group is a separate channel and that has some performance impact). However, I'd rather not add another pivot (predicates) and focus on optimizing groups (I think there are places we can improve how we use Redis *when and if* it becomes a bottleneck). Also the subscriptions are per-server, not per-client so they are still fairly optimized.

**Comment by kierenj** [comment]
Ok great, thanks for the open discussion :) Want to leave this open as a roadmap bit or close?

**Comment by anurse** [comment]
To be perfectly honest, I don't think it does much value staying open on the backlog 😄 . We don't have any plans to add per-client filtering since it adds complexity on the backplane that we'd like to avoid. 

Having said that, if you start hitting performance bottlenecks with groups please **do** post something new and we can start exploring that. It's important that we have features that work well for the scenario you described :)

**Comment by kierenj** [comment]
@anurse thanks, I'm trying just that.

To avoid opening a junk issue for a quick question.. I was hoping to have very low overhead triggering of these signals/notifications in backend code.  Ultimately at the moment I'm doing a `await _context.Clients.Groups(groupNames).ProcessSignal(payload);` on an injected strongly-typed hub, but I'd prefer to have a very quick, non awaited method to call.

If I may ask for some advice, would there be a good way to achieve/approach `ILogger`-like low overhead for this send?  I'm thinking of using a `BlockingCollection`, with send operations awaited within a `TaskCreationOptions.LongRunning` background task, a bit like a batching logger I've seen somewhere in `Microsoft.Extensions.Logging`, then there's the option of blocking with `Add`, having an instant-return if the queue is full with `TryAdd`, etc.

But is there a better/different way?  If I simply didn't make the hub context I'm using transient and didn't `await` any of the send ops, would that fill up I/O completion threads or some other horrible scenario, or actually work quite well?

Either way, I'm curious to understand how what the `Groups(...)` send task covers: is it writing to all clients?  And would that depend on all clients reading prior to returning, i.e. one very slow connection would cause backpressure and potentially slow down the whole pipeline I'm describing?

Thanks!

**Comment by anurse** [comment]
> I'd prefer to have a very quick, non awaited method to call.

I'm a little curious what you mean here. Is that method not fast enough? You don't have to await the call if you don't want to, it'll still run in the background (you just won't know if it finishes). If you want to do something after the send completes, but don't want to block your main task you can do something like this:

```csharp
async Task DoTheSend() {
    await _context.Clients.Groups(groupNames).ProcessSignal(payload);
    // Do stuff after it finishes.
}

// In the place you want to actually send the message, but not bother waiting:
_ = DoTheSend();
```

That will trigger the send, and run the "after send" logic you prepare, but it won't block the task that triggers the send.

> If I simply didn't make the hub context I'm using transient and didn't `await` any of the send ops, would that fill up I/O completion threads or some other horrible scenario, or actually work quite well?

As far as I'm aware, there's no problem with not `await`ing the send. Obviously if you call it in a tight loop without `await`ing, you will fill up queues, but if you're sending in response to some event that isn't extremely frequent, you should be fine.

> If I may ask for some advice, would there be a good way to achieve/approach `ILogger`-like low overhead for this send?

I think queuing is a good idea here, but not using `BlockingCollection`. That's old-school stuff from the pre-`await` days ;). We now (finally) have something way better: [`Channel<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.channel-1?view=dotnet-plat-ext-2.1). The Channel API gives you a multi-writer/multi-reader queue that is completely thread-safe and uses `Task`-based asynchrony. So when generating the events you Write them to the channel and then you can just have a single background service Reading items from the channel in batches and sending them.

There aren't fantastic narrative-style docs about Channel right now, but the link above has good reference-style docs and there are some blog posts out there if you search for "System.Threading.Channels" with your favorite search engine. One important thing to note, you should **always** use a "bounded channel" in server-side programming, *especially* if user actions can generate items in the channel. If the reader slows down or gets backlogged, an unbounded channel will just keep consuming memory as items are added to it, causing your app to slow to a crawl. With a bounded channel, if the reader slows down, the channel will take action to ensure memory usage doesn't explode (which action it takes is [configurable](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.boundedchannelfullmode?view=dotnet-plat-ext-2.1))

> Either way, I'm curious to understand how what the `Groups(...)` send task covers: is it writing to all clients?

No, the completion of the task does not guarantee that the message has been sent to **all** clients. It completes when the message has been placed in the send queue (which happens to be a `Channel` btw ;)) for each connection connected **to the same server** and when it has been dispatched to the backplane (Redis, etc.) if there is one. It may take some time after that for the message to actually be sent over the network (especially if you have multiple servers) and even more time for the message to arrive on the clients :).

**Comment by kierenj** [comment]
Thanks, it's really that since what I'm implementing could be used in many different ways - it's part of a framework - it *could* be called in a tight loop, by code that might need to run very quickly, and so I wanted it to be as lightweight as possible to the caller.

That said, in the case of a huge number of these invocations, it'd be fine for some to be lost, and I'd indicate such with a different call to clients.

It sounds like a bounded Channel may be the way to go - with `TryWrite`, maybe incrementing a value such that the next successful write would include a note with that value - indicating "X items lost" by the time that item made it to clients.  The reader would presumably be OK looping with `await Channel.ReadAsync` and `await _context.Clients.Groups(groupNames).ProcessSignal` calls.

Assuming that's fairly sane, one question - can I include a `CancellationToken` on my typed hub methods, and would it be used as expected?

Thanks again, I'm very grateful for the advice!

**Comment by anurse** [comment]
I don't think we support a Cancellation Token on typed hub clients. That'd be worth tracking in an issue if it's important to your scenario.
