### ISSUE TITLE
Sending form with complexobj[] results in not-ending POST, no error, but memory leak instead.

### ISSUE THREAD

**Issue by tezzly** [aspnet/AspNetCore#8348]
### Describe the bug
I'm trying to send a ComplexObj and OtherComplexObj[] to my controller from a form, but browser is jumping into "waiting for localhost' and wont end nor enter that controller's method nor throw an error.

Both of those Complex Objs have ``IFormFile`` prop.

#Edit: I just realized that memory usage is rising very fast during that "POST attempt"

From 38MB to 200MB in like 10sec.

### To Reproduce

Code and reproduction repo below:

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> WithIndexes(InputModel input, OtherInputModel[] otherinput)
	{
		throw new NotImplementedException();
	}
	
	public class InputModel
	{
		public string Title { get; set; }
		public string Body { get; set; }
		public IFormFile Image { get; set; }
	}	 	
	
	public class OtherInputModel
	{
		public string Text { get; set; }
		public string Body { get; set; }
		public IFormFile Image { get; set; }
	}

	<form asp-action="WithIndexes" method="post" enctype="multipart/form-data">
	
		<div class="form-group">
			<label class="control-label">Title</label>
			<input name="input.Title" class="form-control" value="just" />
			<span class="text-danger"></span>
		</div>

		<div class="form-group">
			<label class="control-label">Body</label>
			<input name="input.Body" class="form-control" value="click" />
			<span class="text-danger"></span>
		</div>

		<div class="form-group">
			<div class="col-md-10">
				<input type="file" name="input.Image" />
			</div>
		</div>

		<div class="form-group">
			<label class="control-label"></label>
			<input name="otherinput[0].Text" class="form-control" value="create btn" />
			<span class="text-danger"></span>
		</div>

		<div class="form-group">
			<div class="col-md-10">
				<input type="file" name="otherinput[0].Image" />
			</div>
		</div>

		<div class="form-group">
			<input type="submit" value="Create" class="button" />
		</div>
	</form>

https://github.com/tezzly/BugReproductionRepo

Download this simple ``dotnet new mvc`` repo, start app,

Click "Without Index" tab and click "Create" (submit form)

### Expected behavior

Application actually enters my ``WithIndexes`` method and then hits breakpoint in ``WithIndexes`` method of ``HomeController``

### Expected behavior 2

Even if I did something wrong with param names, then it wouldnt map, so I'd expect those values to be null, but without problems with entering controller's method.

### Actual behavior

Browser tries to send that post for such a long time and then nothing is happening.

Tested on Quant Firefox and Chrome.

### Screenshots

Not-ending "waiting for localhost..."

https://i.imgur.com/ExiCcuX.png

https://i.imgur.com/n5Uyc3C.png

**Comment by frohikey** [comment]
Based on your screenshots (simply put I see Polish language) haven't you uploaded files with accented chars in filename?

I just encountered exactly the same problem. I run my asp.net core app in AKS and if I upload (multi-part / ajax) file with accented chars in filename, my pod is instantly OOMKilled (memory limit 250mb) and nginx (ingress controller) returns 502 (endpoint is not reachable).

```Content-Disposition: form-data; name="uploadfile"; filename="cucuretka.jpg"```

Everything is ok.

```Content-Disposition: form-data; name="uploadfile"; filename="čučuretka.jpg"```

The same file only renamed. Memory leak and OOMKill.

**Comment by tezzly** [comment]
@frohikey 

Hey,  it's probably solved:

https://github.com/aspnet/AspNetCore/issues/4564

https://github.com/aspnet/AspNetCore/issues/4802

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tezzly.
You're right regarding this being already fixed in the referenced issue.
