### ISSUE TITLE
Template Program.Main should use 'await RunAsync' instead of 'Run'

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#8350]
Now that we can use newer C# features such as `async Main`, we can have the code inside `Main` also use `async` patterns.

Use `await RunAsync`:

https://github.com/aspnet/Extensions/blob/6991e2b0e8f7a133208d015dc7d0ca4192523ba0/src/Hosting/Abstractions/src/HostingAbstractionsHostExtensions.cs#L57

Before:

```c#
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }
```

After:

```c#
        public async static Task Main(string[] args)
        {
            await CreateHostBuilder(args).Build().RunAsync();
        }
```

FYI @ajcvickers @bricelam - I don't think this affects Migrations because that doesn't look at `Main`, only the `CreateHostBuilder`, stuff right?

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/5440

**Comment by ajcvickers** [comment]
@Eilon Correct; shouldn't impact EF.
