### ISSUE TITLE
Make Bootstrap4 the default UIFramework for the Identity UI

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#8353]
Change this to `Bootstrap4`:

https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/UI/src/IdentityBuilderUIExtensions.cs#L33

This will help avoid all the places in the templates where the value must be set to Bootstrap4 explicitly, such as:

https://github.com/aspnet/AspNetCore/blob/bc009fc0f180532e003b7d3e466c5a1a2456a630/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Startup.cs#L73

Note: This is super Announcement-worthy, so please make sure an announcement issue gets logged for this.

So, the work here is to:
* [ ] Make the default Bootstrap4
* [ ] Remove the setting from all the templates
* [ ] Post an announcement

**Comment by Eilon** [comment]
Please remember to post an announcement as well.

**Comment by ryanbrandenburg** [comment]
Created #9509 to track that.
