### ISSUE TITLE
Question: Configuring Https Certificate in Kestrel via environment variable

### ISSUE THREAD

**Issue by vkukke** [aspnet/AspNetCore#8363]
My Settings.json file

```javascript
"runtime.Api": {
    "kestrel": {
        "endpoints": {
            "https": {
                "url": "https://*:4438"
            }
        },
        "certificates": {
            "default": {
                "path": null,
                "password": null
            }
        }
    },
    },
},

```
I setup my Kestrel server as follows
``
 IWebHostBuilder hostBuilder = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseConfiguration(configuration)
                .UseKestrel((options) =>
                {
                    IConfigurationSection kestrelConfig = configuration.GetSection("kestrel");
                    options.Configure(kestrelConfig);
                })

I dockerize my app and try to run it by specifying
docker run -e runtime_Api__kestrel__certificates__default__path=<myfile.pfx> -it myimageId

I get the following exception:-
``
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

Clearly the environment variable is not being honored. What am I missing? I know in general the environment variable works but something is off for HTTPs. 

Pointers?

**Comment by VidyaKukke** [comment]
anyone? Is this expected to work?

**Comment by Tratcher** [comment]
I don't think those underscores are being translated they way you think they are. Try dumping the config to make sure it is structured as you expect.

https://github.com/aspnet/AspNetCore/blob/f303a55a8edf632738eb6e15312aac443cdf21b1/src/Servers/Kestrel/samples/SampleApp/Startup.cs#L179-L187

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
