### ISSUE TITLE
Enable SIMD for JSON API

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#8366]
### Is your feature request related to a problem? Please describe.
Feature request. Enable SIMD for the new Json APIs in ASP.NET Core 3.

### Describe the solution you'd like
See [SimdJsonSharp](https://github.com/EgorBo/SimdJsonSharp)  
With SIMD support, SimdJsonSharp is faster than any existing Json library on .NET.  
I think the new Json APIs in ASP.NET Core 3 should add SIMD support to improve its performance.

**Comment by terrajobst** [comment]
This issue was moved to dotnet/corefx#35967

**Comment by mkArtakMSFT** [comment]
Thanks @terrajobst.
