### ISSUE TITLE
SignalR: groups management with NameIdentifier

### ISSUE THREAD

**Issue by rafalschmidt97** [aspnet/AspNetCore#8367]
Hi!

### Is your feature request related to a problem? Please describe.
I'm am trying to add users to groups with name identifier (which is user id in my case).

### Describe the solution you'd like
Would be cool to have another method to add users. By the way I use context outside of a hub class. The same applies for removing. 

So instead of 
```c#
await Groups.AddToGroupAsync(Context.ConnectionId, ...)
```
I would love to see
```c#
await _hubContext.Groups.AddUserToGroupAsync(userId, ...) // userId is my nameidentifier
```
### Additional ideas

- a way to list all users / groups
- access user context in IHubContext

**Comment by muratg** [comment]
Triage discussion: Implementing this would be a big design change. We do not plan to implement this. You can manage this at application level.
