### ISSUE TITLE
Inconsistent naming ValidateAntiForgeryTokenAttribute and IgnoreAntiforgeryTokenAttribute

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/AspNetCore#8370]
I just noticed `IgnoreAntiforgeryTokenAttribute`, `ValidateAntiForgeryTokenAttribute` and `AutoValidateAntiforgeryTokenAttribute` have inconsistent naming. 

`ValidateAntiForgeryTokenAttribute` has a capital `F` while the others do not.

Since the [Antiforgery](https://github.com/aspnet/AspNetCore/tree/master/src/Antiforgery/src) project uses a lower case letter, I guess they all should be this way.

Changing the attribute will be a breaking change, so I don't know what you guys think of this. I just decided to report it, in case you missed it. 

Keep up the good work! ASP.NET Core is awesome!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ivaylokenov.
You're right, there is an inconsistency, but we won't do anything about it as the actual value of the change is neglectable where as the impact - is quite big, given that it's a breaking change.
