### ISSUE TITLE
Error. Registration form keeps popping for a registered user after token has expired

### ISSUE THREAD

**Issue by jgathairu** [aspnet/AspNetCore#8371]
### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`

**Comment by jgathairu** [comment]
I have implemented the WSFederation successfully on Asp.net core. When the idle time of 20 mins lapses, the application re-authenticates by calling the ADFS page. However, the application takes the registered user back to the registration page. I will then either recycle the application pool or restart the website to make it work again. How do I resolve the issue ? The console is showing error 401
![Capture](https://user-images.githubusercontent.com/29246216/54075141-b5001380-42ac-11e9-93c6-63b9977db0ba.JPG)

**Comment by Eilon** [comment]
@jgathairu can you share what your Startup.cs code looks like? Any other interesting settings or configuration that might be relevant here?

**Comment by jgathairu** [comment]
@Eilon thank you for your interest on my issue. on start up
 services.AddAuthentication()
                .AddWsFederation(WsFederationDefaults.AuthenticationScheme, "Login Using Office Account", 
                    options =>
                {
                    options.MetadataAddress = "https://xxxxxxxxxxxx/FederationMetadata/2007-06/FederationMetadata.xml";
                    //options.Wtrealm = "https://localhost:44306/";
                    options.Wtrealm = "https://xxxxxxxxxxxx.org/";
                }).AddCookie();



            services.ConfigureApplicationCookie(options =>
                {
                    options.LoginPath = "/Identity/Account/LogIn";
                }
            );
            services.ConfigureApplicationCookie(options => options.LogoutPath = "/Home/Index");
 and on logout

//delete all cookies first
            foreach (var key in HttpContext.Request.Cookies.Keys)
            {
                HttpContext.Response.Cookies.Delete(key);
            }

            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return SignOut(new AuthenticationProperties { RedirectUri = "/Home/Index" }, 
                CookieAuthenticationDefaults.AuthenticationScheme, 
                WsFederationDefaults.AuthenticationScheme);

The solution I found that works were to increase the application pool idle time from default 20 minutes to any minutes of choice. The user can then work and logout of the application without issues. You can also review the code I have and suggest some improvements if needed

**Comment by Tratcher** [comment]
Calling Cookies.Delete should not be necessary.
