### ISSUE TITLE
Signalr with jsonrpc #SignalR #Feature #jsonrpc

### ISSUE THREAD

**Issue by lobster2012-user** [aspnet/AspNetCore#8375]
| name | about |
|-------|-------------------|
| Feature request  | Add JsonRpc Implementation |

**Is your feature request related to a problem? Please describe.**
Clients are forced to use (or implement for different programming languages) the signalR library, although the functionality of jsonrpc and the signaling device are similar.
Ping/pong off/on
Support of invocations.

**Describe the solution you'd like**

1. Replace the static handshake release with a dynamic one, as there is a hard link to the presence of a record separator. In the future, support for any protocol over the pipe.
2.  JsonRpc Handshake and protocol implementation
3. Some changes in DispatchMessagesAsync (because stream)

**Additional context**
Hello.

The signalR and json-rpc protocols are very similar. Except for batch operations and iprogress <>.
(invocationid = id, target = method, arguments = PARAMS)
It is even strange that the names are generally different, since the latter is the standard.

There are critical differences
Static release handshake with a record separator.

There is a good microsoft / stream-json-rpc library.
**The library lacks DI (+ hub).** I think that there is no sense in duplicating the functionality from signalr.
You can override the handshake and reading,
you can't do it easily, a handshake is a static class. (There are other options leading to code duplication)
Therefore, a single implementation of IJsonRpcProtocol is not enough.

It seems to me that it would be nice to give the opportunity to redefine the handshake, so as not to be tied to only one implementation of the handshake.

**Comment by davidfowl** [comment]
We looked at json rpc when doing the new protocol but didn’t see the benefit (as there was no defecto client libraries) and we wanted to extend it to support things like streaming, ping pongs etc. 

What exactly are you trying to do? What standard json rpc library are you using? Do you care about connection semantics or just the rpc ness? Do you care about server to client invocations as well?

**Comment by lobster2012-user** [comment]
Hi, @davidfowl ! 

Basically, I was talking about a backend that would support clients using the jsonrpc protocol with a single line of code, specifying the required IJsonRpcHubProtocol.
 
(Except for batch operations,
Now streamjsonrpc also does not support batch, does not fully support the stream over a web socket, independent of the end of messages about the protocol web socket, does not support more than one object in one web socket message


In my particular case, a completely different team in another language will be engaged in developing the client part.
I want to use server / signalr (net core), but I do not want them to use signalr.

Whatever jsonrpc library I use, it doesn't know anything about RecordSeparator (and shouldn't know). While I have not used any.

**The only problem that will be solved by the addition of jsonrpc is greater freedom for the client.**

> Do you care about connection semantics or just the rpc ness? Do you care about server to client invocations as well?

Did not quite understand the questions.
There should be support for invocations (id! = Null) and notifications (id == null)
It is in both protocols.

> ping pongs etc.
In the settings of the protocol, you can make the option - support ping pong. (on / off)
It's great that signalr implements features that are not available with jsonrpc.
It does not interfere with anything

**Comment by davidfowl** [comment]
Did you look at implementing the custom protocol?

**Comment by lobster2012-user** [comment]
Hi @davidfowl !
The first problem with adding other protocols is binding to the delimiter during a handshake.
The implementation of a handshake should not be static on the server side.

Ideally, I would add @AArnott  to the discussion.
As it seems to me, adding new features in aspnetcore/signalr and in streamjsonrpc
happened simultaneously.
Now this is all compatible, but why not combine it...

**Comment by AArnott** [comment]
I'm not too familiar with SignalR, but I believe it is based on MessagePack, which is indeed very similar to JSON-RPC, and the reason why StreamJsonRpc can actually use MessagePack to encode all of its JSON-RPC messages. 

> does not fully support the stream over a web socket

I don't understand why you say that, @lobster2012-user. StreamJsonRpc [has full support for web sockets](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/WebSocketMessageHandler.cs).

> Now streamjsonrpc also does not support batch

[True](https://github.com/Microsoft/vs-streamjsonrpc/issues/134).

> does not support more than one object in one web socket message

It's not built-in to the `WebSocketMessageHandler`, but such a thing could absolutely be done with the library via its extensibility model.

The other SignalR unique features like ping-pong I cannot comment on without learning more. 

But I don't yet understand the scenario here, @lobster2012-user. Do you have code running on platforms that want to talk via SignalR but can't actually run the SignalR code, such that you wish the wire protocol were JSON-RPC instead for easier interoperability.

**Comment by lobster2012-user** [comment]
@AArnott 
>> does not fully support the stream over a web socket
I don't understand why you say that, @lobster2012-user. StreamJsonRpc has full support for web sockets.

Unfortunately, I do not remember what I had in mind.
Perhaps I meant, in the current implementation, the end of the web socket of the message should be the end of the json message.

>>I'm not too familiar with SignalR

One of the implementations is the json protocol, it is very similar to json-rpc, the fields are called differently.

>>Do you have code running on platforms that want to talk via SignalR but can't actually run the SignalR code, such that you wish the wire protocol were JSON-RPC instead for easier interoperability?

No. I agree that with a strong desire, signalr can be used instead of json-rpc, but this protocol is not a standard.
The client-side code is now pretty poor (for c# out of the box).
These rpc protocols are so similar (in my opinion)
that I see no reason to separate and duplicate them, maintain, add the same features, like DI)
Start a simple server with a client through Fiddler to verify this.


p.s.
1. There is an incompatibility with multi requests, yes.
2. You need 1 connection to 1 hub, which is not very good, it is not critical and can be solved.

**Comment by lobster2012-user** [comment]
Hello.
It seems to me that my proposal did not interest anyone. I still close the issue.
Now I look towards grpc.
I repeat, I really like dot net, but I prefer not to use (highly) specialized protocols in the presence of widespread ones.
