### ISSUE TITLE
ASP.NET Core 3.0 Preview 3 does not show up in the dropdown using Visual Studio 2019 RC.1 Svc1

### ISSUE THREAD

**Issue by D3MaxT** [aspnet/AspNetCore#8376]
### Describe the bug
ASP.NET Core 3.0 Preview 3 (dotnet-sdk-3.0.100-preview3-010431-win-x64) does not show up in the dropdown using Visual Studio 2019 RC.1 Svc1 when creating a new ASP.Net Core Web Application.

### Additional context
dotnet --info finds the correct SDK version just fine
2.1 and 2.2 show up, just not 3.0 Preview 3.

Similar to 4420, but no solution was ever posted there.

**Comment by davidfowl** [comment]
Did you install it?

**Comment by D3MaxT** [comment]
@davidfowl
yes, I have this happening on two PCs.

Here is the output from dotnet --version

C:\Users\****>dotnet --version
3.0.100-preview3-010431

**Comment by Eilon** [comment]
@vijayrkn - any idea on this or what to look for to diagnose?

**Comment by vijayrkn** [comment]
Can you check if the 'Use Preview Sdk' is checked? For RC builds, this is not enabled by default.

![preview](https://user-images.githubusercontent.com/3981619/54141820-a8caa200-43e3-11e9-8511-656729b9f17e.jpg)

**Comment by D3MaxT** [comment]
@vijayrkn @Eilon @davidfowl
Good call. That is exactly what the issue was.

Thank you.
