### ISSUE TITLE
ASP.NET Core Preview3 Kestrel Console Logging can lag the server under heavy traffic.

### ISSUE THREAD

**Issue by honkmother** [aspnet/AspNetCore#8377]
### Describe the bug
Under heavy traffic, Kestrel in Preview3 appears to get overwhelmed and preoccupied with writing to the Console, which has a measurable degradation in response speed.

### To Reproduce
Using Razor Components and running Kestrel directly (without IIS) under Preview3, click the heck out of something that induces a web-socket request.

### Expected behavior
To not slow the response time to the pace of a snail in slow motion.

### Interim Solution
Disabling logging in BuildWebHost using 
`ConfigureLogging((c,logging) => {
                        logging.ClearProviders();
                    })`

**Comment by davidfowl** [comment]
Yes the console logger can definitely impact performance. Do you have anything to quantify how bad the performance lag is in your specific case? Is this just during development? What exactly were you doing? What were the configured log levels?

**Comment by honkmother** [comment]
Log levels were default; and I was just clicking through a pagination menu (in other words: causing a bunch of requests). I don't have any exact measurements but it was definitely noticeable; I was watching the request pipeline get clogged up and send updates slower and slower. If it helps I am on an i5 Surface Pro 2017 with 8gb of RAM - not the fastest (or highest QA) machine on the Market apparently.

FYI: I didn't experience this prior to Preview3.

**Comment by davidfowl** [comment]
Using razor components? Or all templates?

**Comment by honkmother** [comment]
Sorry - I forgot to respond to this; but I was using Razor Components when I experienced the issues.

**Comment by anurse** [comment]
Can you provide a sample project that reproduces the behavior? Also, can you clarify/quantify what you mean by "the request pipeline [got] clogged up" and "heavy traffic"?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
