### ISSUE TITLE
ASP.NET Core hosting bundle installer makes IIS crash every working AppPool

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#8378]
I downloaded the latest Runtime & Hosting bundle for asp.net core here
https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-preview2-windows-hosting-bundle-installer

I have a Windows Server 2008 R2 running several .NET Framework 4.7 websites in a IIS 7.5.7600 ,  after installing the Hosting Bundle, every application pool crashes instantly (stops), After restarting the server and app pools individually, the issue persists generating this application event in the event viewer:

_The Module DLL 'C:\Windows\system32\inetsrv\aspnetcore.dll' could not be loaded due to a configuration problem. The current configuration only supports loading images built for a x86 processor architecture. The data field contains the error number. To learn more about this issue, including how to troubleshooting this kind of processor architecture mismatch error, see http://go.microsoft.com/fwlink/?LinkId=29349._

So it seems the new modules that the installer adds in the applicationHost.config just can't be loaded.  
Deleting the modules or uninstalling the hosting bundle makes the IIS work again.

I tried to set Enable32BitApplication in the app pools that stopped, but it didn't solve the issue.

**Comment by shirhatti** [comment]
There's a known issue in the preview3 hosting bundle where the installer incorrectly swaps the location of the 32-bit and 64-bit ANCM binaries.

Our recommendation at this moment is to continue to use the preview2 hosting bundle. If you wish to install the preview3 hosting bundle (for the newer runtimes), you may pass the appropriate flag to the hosting bundle to skip installing the new ANCM.

See https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md#preview-3 for more details.

**Comment by chrdlx** [comment]
I know,  but I never said I was using the Preview 3,  I just referenced the Preview 3 issue because the message was similar, I'm having this issue with the Preview 2 Hosting bundle.

**Comment by chrdlx** [comment]
Also, I tried the Preview 2 hosting bundle in 2 different servers having the same issue. Both servers using Windows 2008 R2 with IIS 7.5.7600.

**Comment by chrdlx** [comment]
Any idea how can I solve this in the meanwhile? Thanks!

**Comment by anurse** [comment]
We believe this will be fixed in preview 4. If you still hit it after updating, let us know.

**Comment by dirq** [comment]
We installed dotnet-hosting-3.0.0-preview-19075-0444-win.exe on Windows Server 2016 Datacenter and our .net core 2.1 apps died.  We tried a whole slew of things to get it back up, including removing ALL .net core hosting bundles and runtimes, then reinstalling just 2.1.  Our staging app is core 3 preview 3 and we don't need core 3 up on this server.  but live sites are using 2.1.  HELP!

**Comment by ArkarMoe93** [comment]
I have a Windows Server 2008 running several .NET Framework 4.5 websites inside of a IIS 8.0. 
My problem seems similar to you. When I installed .NET Core Windows Server Hosting, all application pool stopped working. Then I uninstalled it again, they all went back to work as normal..
**[Solved]
Updating the window solved it.**

(coz we cannot update IIS partially)
