### ISSUE TITLE
Bad url when navigating to fetchData url in react template (.net core 3.0 preview 3)

### ISSUE THREAD

**Issue by Amine-Smahi** [aspnet/AspNetCore#8380]
Bad url when navigating to fetchData url in react template (.net core 3.0 preview 3)

Shown url : https://localhost:5001/authentication/login?returnUrl=https://localhost:5001/fetch-data

## Screenshot

![image](https://user-images.githubusercontent.com/24621701/54083550-21b6f480-4325-11e9-8e6f-eb99d1772438.png)

**Comment by marquesm91** [comment]
Fix in #8592
