### ISSUE TITLE
ASP.NET Core 2.2 Conversion

### ISSUE THREAD

**Issue by SSSikora** [aspnet/AspNetCore#8383]
Hello All,

I'm hoping someone can help me with the following error:

3>obj\Debug\netcoreapp3.0\NEP.Portal.RazorTargetAssemblyInfo.cs(16,12,16,92): error CS0579: Duplicate 'Microsoft.AspNetCore.Mvc.ApplicationParts.ProvideApplicationPartFactoryAttribute' attribute

I converted a 2.2 solution that consists of two .NET Core libraries and a single front-end ASP.NET Core project. I'm not sure what is causing this error and after research if I insert the following line in my csproj it will compile but fails to server any pages all resulting in a 404 error:

<GenerateProvideApplicationPartFactoryAttribute>false</GenerateProvideApplicationPartFactoryAttribute>

Any help greatly appreciated.
Regards,

Scott

**Comment by Eilon** [comment]
@SSSikora can you share what your CSPROJ files look like?

**Comment by Eilon** [comment]
Or, if possible, upload the whole app as a GitHub repo so we can take a look?

**Comment by SSSikora** [comment]
Thanks for the response Eilon. Below are the csproj files from the two libraries and the ASP.NET Core app. I've gone as far as to create all three projects in VS2019 using file new and then copying all of the assets into each and the problem remains. It's strange because it's a relatively small and simple application. Appreciate your help with this.

LIBRARY 1:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.0.0-preview3.19153.1" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.6.0-preview3.19128.7" />
  </ItemGroup>


</Project>

LIBRARY 2:

<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0-preview3-19153-02" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0-preview3.19153.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview3.19153.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0-preview3.19153.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.0.0-preview3.19153.1" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.6.0-preview3.19128.7" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\NEP.Core\NEP.Core.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Identity\" />
  </ItemGroup>


</Project>

ASP.NET Core:

<Project Sdk="Microsoft.NET.Sdk.Web">


  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <TypeScriptToolsVersion>3.3</TypeScriptToolsVersion>
    <UserSecretsId>a74b6723-bd0e-4cb0-b79d-839a7aa59d1f</UserSecretsId>
    
</PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0-preview3-19153-02" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview3-19153-02 " />
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.9.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.4.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.2" />
    <PackageReference Include="Telerik.Reporting" Version="13.0.19.222" />
    <PackageReference Include="Telerik.Reporting.OpenXmlRendering" Version="13.0.19.222" />
    <PackageReference Include="Telerik.Reporting.Services.AspNetCore" Version="13.0.19.222" />
    <PackageReference Include="Telerik.UI.for.AspNet.Core" Version="2019.1.220" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\NEP.Core\NEP.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\NEP.Infrastructure\NEP.Infrastructure.csproj" />
  </ItemGroup>


</Project>

Again, thank you so much for any information you might have,

Scott

**Comment by Eilon** [comment]
So you're trying to migrate from ASP.NET Core 2.2 to ASP.NET Core 3.0 Preview 3? It looks like some of the package references are still to 2.2, such as Microsoft.AspNetCore.Identity.

**Comment by SSSikora** [comment]
Thanks for another reply. I see what you mean and have removed references to that Identity package but the problem persists. I think it may have to do with the Telerik controls. When I expand them in the dependencies that show asp net core 2.1.6. Could that have something to do with it? Although I am using them with the 2.2. project so I don't see why that would be a problem.

**Comment by Eilon** [comment]
@javiercn / @pranavkm - any ideas what might cause this?

**Comment by pranavkm** [comment]
Could you attach the `obj\project.assets.json` for the Web app? Perhaps something's pulling in a 2.x version of MVC \ Razor and not getting overriden by the targeting pack.

**Comment by SSSikora** [comment]
Thank you for the help...

[project.assets.zip](https://github.com/aspnet/AspNetCore/files/2954164/project.assets.zip)

**Comment by pranavkm** [comment]
Could you confirm this is from the project that targets the WebSDK (`Microsoft.NET.Sdk.Web`). I think it's called `NEP.Portal`? I don't see any of the Telerik specific package references in it, so just making sure I'm looking at the right file. 

If it is the right one, could you include the preprocessed output for the file: `dotnet msbuild /pp:out.txt` and attach the `out.txt` that MSBuild spits out. The project.assets.json doesn't indicate any reason for you to see the build error.

**Comment by SSSikora** [comment]
A zero-byte file is generated and the error I'm getting in VS appears in the command prompt as the attached photo shows. Thank you, Pranav.


![build failure](https://user-images.githubusercontent.com/7399496/54204408-936c7b00-44aa-11e9-9beb-89a76f1a9b16.png)

**Comment by andrestalavera** [comment]
@SSSikora you must remove package reference to Microsoft.AspNetCore.* v2.0

My csproj corrected (inside an ItemGroup tag):

```xml<PackageReference Include="Faker.Net" Version="1.1.1" />
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.7.0-beta2" />
<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0-preview3-19153-02" />
<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0-preview3-19153-02" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview3-19153-02" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0-preview3.19153.1">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.2.0" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
<PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="1.0.172" />
<PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
<!--
<PackageReference Include="Microsoft.AspNetCore.CookiePolicy" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Localization.Routing" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Localization" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.2.2" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
-->
```

> I had the same error, I corrected it as well

@Eilon that mean that the v3 included what meta package? 
I do not want to reference 1000 packages that I do not need... (It's going to weigh my apps for nothing)

**Comment by SSSikora** [comment]
@andrestalavera - thank you very much for the information and taking the time to look at my issue.

-Scott

**Comment by Eilon** [comment]
@SSSikora we have some migration information at the following links:

* ASP.NET Core migration guide from 2.2 to 3.0: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio
* https://github.com/aspnet/Announcements/issues/325
* https://github.com/aspnet/AspNetCore/issues/3612
* https://github.com/aspnet/AspNetCore/issues/3756

**Comment by pranavkm** [comment]
@SSSikora did the migration guides help?

**Comment by SSSikora** [comment]
I had previously found those guides and updated the app, but I believe my problem is that the Trlerik components are not yet working under 3.0 and so I have set this aside for now until they do.

Thank you to all who took time to comment. I am greatly looking forward to working with this next release.

-Scott

**Comment by Eilon** [comment]
@SSSikora got it, thanks for the update. Should this bug be closed, or is there still any pending action for the ASP.NET Core team?

**Comment by SSSikora** [comment]
I don’t believe the problem lies with ASP.NET Core so the issue can be closed. Thanks again for the help.
