### ISSUE TITLE
ASP.NET Core 3 Razor Components not working without WebSockets on IIS

### ISSUE THREAD

**Issue by chrdlx** [aspnet/AspNetCore#8384]
I installed the latest runtime Runtime 3.0.0-preview3-27503-5,  and when publishing the solution to an IIS without Websocket support,  the interactivity doesn't work.

![Capture](https://user-images.githubusercontent.com/20750172/54085148-44dba700-4319-11e9-9377-e2527f5cd462.JPG)

![Capture](https://user-images.githubusercontent.com/20750172/54085231-66895e00-431a-11e9-84a9-9a380c794943.JPG)

The published application is just the default Razor Components template, browsing the "Counter" page,  the button "Click me" that increments the counter doesn't work..  I tried adding other buttons to the default template and publishing my own project and doesn't work either.  It seems to be a problem with "long polling" as far as I understand how SignalR connects to a server without Websocket protocol available. See the attached screenshots.

I found this when trying to publish my own razor components app to a production server Windows 2008 R2 which doesn't have Websocket support.

**Comment by asterinex** [comment]
Is there a temporary fix for development in Visual Studio 2019 and IIS Express 10 ?

**Comment by springy76** [comment]
The same problem seems to happen when the server **has** web socket support but the clients can't use it because of firewalls or whatever other network reason.

The long polling alternative seems to be entirely broken, don't know whether by SignalR changes or Razor Component changes.
Does anyone have better insight what goes wrong and if there exists a work around?

**Comment by asterinex** [comment]
I just want to share following info.
I have deployed our new .NET Core 3 Prev3 App on our Windows 2012 Server R2 with IIS 8.5.9600.16384.
The app did start but did not respond to events.

I have then added the Websocket Role [()](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-websocket-protocol-support) and everything works fine now.  

Seems the Websocket Support for IIS was  introduced in IIS 8.0.

**Comment by springy76** [comment]
**With** the Websocket Role the app is only broken for the users which can't establish websockets due to their firewalls (or whatever), **without* the Websocket Role the app is broken for everyone: Fallback to long polling is initiated but fails in some way so no render messages get through.

**Comment by mkArtakMSFT** [comment]
Seems this is going to be resolved by https://github.com/aspnet/AspNetCore/issues/6920.

**Comment by vishnupv** [comment]
The counter does not work in IE. But Works in Chrome. Bizzare.

**Comment by chrdlx** [comment]
> The counter does not work in IE. But Works in Chrome. Bizzare.

That's another issue, currently there's no IE support, this is not related with the websocket issue on discussion here.
