### ISSUE TITLE
ZipArchive creation in memory

### ISSUE THREAD

**Issue by theCuriousOne** [aspnet/AspNetCore#8391]
### Describe the bug
Trying to create a zip file completely in memory, but the entries are not written (empty zip)

### To Reproduce
1. .net core 2.2 (SDK 2.2 102)
2. code to run as a console application:
```
static void Main(string[] args)
        {
            using (Stream zipStream = new MemoryStream())
            {
                using(ZipArchive archive = new ZipArchive(zipStream, ZipArchiveMode.Create,true))
                {
                    ZipArchiveEntry readmeEntry = archive.CreateEntry("Readme.txt");
                    using (StreamWriter writer = new StreamWriter(readmeEntry.Open()))
                    {
                        writer.WriteLine("Information about this package.");
                        writer.WriteLine("========================");
                    }
                }

                using (FileStream compressedFileStream = File.Create("test.zip"))
                {
                    zipStream.CopyTo(compressedFileStream);
                }
            }
        }
```
3. /
4. Open the created test.zip (probably inside the debug folder) and inspect the content of the archive

### Expected behavior
I expect to have a readme.txt file which contains some text, but there is no file.

### Screenshots
/

### Additional context
Maybe I am doing something wrong, but after simplifying the problem as above (I have somewhat more complex scenario) it may point out to a bug in .net core.

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#35928
