### ISSUE TITLE
"Error during WebSocket handshake: 'Connection' header is missing" in React app with authentication in ASP.NET Core 3 Preview 3

### ISSUE THREAD

**Issue by loop-evgeny** [aspnet/AspNetCore#8397]
### Describe the bug
A brand new React app with authentication created with ASP.NET Core 3.0 Preview 3 generates a client-side error when browsing to its homepage: `Error during WebSocket handshake: 'Connection' header is missing`

### To Reproduce

1. Using ASP.NET Core 3.0 Preview 3 create a new project with `dotnet new react --auth Individual`
2. Fix the client-side issues described in #8281 and #8283.
3. Build and run the project with VS 2019
4. Browse to the app homepage (e.g. `https://localhost:44341/`) in Chrome and open the developer console to see the error:

```
WebSocket connection to 'wss://localhost:44341/sockjs-node/681/drhzrqa1/websocket' failed: Error during WebSocket handshake: 'Connection' header is missing
WebSocketBrowserDriver @ websocket.js:7
WebSocketTransport @ websocket.js:32
push../node_modules/sockjs-client/lib/main.js.SockJS._connect @ main.js:222
push../node_modules/sockjs-client/lib/main.js.SockJS._receiveInfo @ main.js:197
g @ emitter.js:29
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:53
(anonymous) @ info-receiver.js:68
g @ emitter.js:29
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:53
(anonymous) @ info-ajax.js:38
g @ emitter.js:29
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:53
xhr.onreadystatechange @ abstract-xhr.js:134
```

### Expected behavior
No errors in console.

### Additional context
I'm running on Windows 7, which I know does not support WebSockets. Nevertheless, this is not the expected behaviour. It's unclear to me why it's even trying to use web sockets, why there is no server side error if the server tries to start a WebSocket server and what the impact is.

**Comment by loop-evgeny** [comment]
It seems that the impact is that the authentication doesn't work at all! Is there a way to get this to work on Windows 7? I can't even find any server-side WebSocket code in the generated C# project.

**Comment by javiercn** [comment]
This is a known issue. See Single Page Applications with authentication enabled throws method not found exception when visiting the register or login pages for details on https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md

**Comment by loop-evgeny** [comment]
Thanks, but I'm not getting a MethodNotFoundException or any other exception in the server-side code and applying that workaround made no difference.

**Comment by javiercn** [comment]
Ok, let me take a look. I'll get back to you

**Comment by loop-evgeny** [comment]
FYI, I can register now after applying the `Import error "Cannot find module "./components/api-authorization/Login"` workaround, but I still get the WebSocket error logged in the console and am now running into #8405

**Comment by javiercn** [comment]
@loop-evgeny are you able to repro this issue with a react app and no authorization? I believe this is an issue with the react development server. So I don't think there's anything we can do here.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
