### ISSUE TITLE
Blank page on browsing to the Login or Register page in React app with authentication in ASP.NET Core 3 Preview 3

### ISSUE THREAD

**Issue by loop-evgeny** [aspnet/AspNetCore#8398]
### Describe the bug
When running a React app with Authentication using ASP.NET Core 3.0 Preview 3 on a Windows 7 machine the Login and Register pages are blank and give no indication of what the problem is. The user must open the console to see any error.

### To Reproduce
Follow the steps in #8397, then click on the Login link (`https://localhost:44341/authentication/login`). The menu is still shown, but the body of the page is blank with no indication of anything wrong. I know it's a sample app, but I'd still expect some basic error handling. Same for the Register page.

### Expected behavior
The body of the page shows a login for or some kind of error.

### Screenshots
![image](https://user-images.githubusercontent.com/34301024/54115220-5b9efe00-43ec-11e9-9d14-571bf78f67bc.png)

### Additional context

I suppose this is due to the WebSocket issue (#8397) but this bug is about handling the error better. The client-side code should display some error, but if WebSockets are required for the authentication to work then the server-side code should also throw some exception.

**Comment by loop-evgeny** [comment]
After applying the `Import error "Cannot find module "./components/api-authorization/Login"` workaround from https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md I no longer get a blank page when clicking on Login or Register. (I still get the WebSocket exception, so that's probably unrelated.)

**Comment by marquesm91** [comment]
Fix in #8592
