### ISSUE TITLE
Fighting in the ASP.NET Core Mvc Localization jungle with a SharedResource 

### ISSUE THREAD

**Issue by wstaelens** [aspnet/AspNetCore#8399]
Let me take you on a journey through the Localization jungle.

![img](https://inkindle.files.wordpress.com/2010/09/simba1.jpg)

**My goal:** using sharedresource files as much as possible to minimize the number of resx files and duplicate keys. I prefer to have SharedResource.en-US.resx, SharedResource.nl.resx instead of having per view a resx file where I would have to repeat myself on each view (e.g. If I have an "Edit" button, I would have to add it to every view, resulting in duplicate keys and all the fun that comes with it).
Having just a few resx files makes it also easier to maintain with [Microsoft MAT](https://developer.microsoft.com/en-us/windows/develop/multilingual-app-toolkit). Still I want to keep using the resx files per view/controller in case I need it for something small. My Resources should be in a folder called /Resources. 

my ```Startup.cs``` file:

```
    public void ConfigureServices(IServiceCollection services)
    {
      services.AddLocalization(options => options.ResourcesPath = "Resources"); 
    }


      services.Configure<CookiePolicyOptions>(options =>
      {
        // https://stackoverflow.com/questions/45282853/the-language-does-not-change-in-the-asp-net-core-web-application
        // This lambda determines whether user consent for non-essential cookies is needed for a given request.
        options.CheckConsentNeeded = context => true;
        options.MinimumSameSitePolicy = SameSiteMode.None;
      });

 // other stuff

services.AddMvc().
        SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
.AddViewLocalization(Microsoft.AspNetCore.Mvc.Razor.LanguageViewLocationExpanderFormat.Suffix)
        .AddDataAnnotationsLocalization(); // localization

      services.Configure<RequestLocalizationOptions>(
        options =>
        {
          var supportedCultures = new List<CultureInfo> {
            new CultureInfo("en-US"),
            new CultureInfo("nl"),
            new CultureInfo("fr")
          };
          options.DefaultRequestCulture = new RequestCulture(culture: "en-US", uiCulture: "en-US");
          options.SupportedCultures = supportedCultures; // Formatting numbers, dates, etc.
          options.SupportedUICultures = supportedCultures; // UI strings that we have localized.

        });
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
      var locOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
      app.UseRequestLocalization(locOptions.Value);

   // other stuff...
    }
```

(Note: the Microsoft documentation is confusing and not very clear about where to put the code in Configure and ConfigureServices. You have to find out that the documentation differs from the code samples on github where they reference at. copy/pasting code from stackoverflow, and adding additional javascript which was no where mentioned was a first battle to begin with. (documentation is not very beginner friendly)).

I've created a folder called ```Resources```. In that folder I have created the following files:

- SharedResource.cs  

- SharedResource.en-US.resx

- SharedResource.nl.resx

the ```SharedResource.cs``` file is empty and I have not added ```SharedResource.fr.resx``` to be sure I can correctly test my fallback culture, which is configured as "en-US".

I have added "Welcome!" to the ```SharedResource.en-US.rex``` file and added "Welkom!" to the ```SharedResource.nl.resx``` file.

My ```Index.cshtml``` view from ```HomeController``` has this code:

```
@inject IStringLocalizer<Foo.Bar.Resources.SharedResource> SharedStringLocalizer
      <h1 class="display-4">@SharedStringLocalizer["Welcome"]</h1>
```

Running the code results in this exception:

> System.Resources.MissingManifestResourceException: 'Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Foo.Bar.Resources.Resources.SharedResource.resources" was correctly embedded or linked into assembly "Foo.Bar" at compile time, or that all the satellite assemblies required are loadable and fully signed.'

Ok as you can see we have a **problem** here. The code does not look for ```Foo.Bar.Resources.SharedResource``` but it looks in ```Foo.Bar.Resources.Resources.SharedResource```. 

Thanks to stackoverflow I have found a solution.
In the SharedResource.cs file change the namespace from ```Foo.Bar.Resources``` to ```Foo.Bar```.
In my Index.cshtml I also have to change the DI code from:
```
@inject IStringLocalizer<Foo.Bar.Resources.SharedResource> SharedStringLocalizer
``` 
to
```
@inject IStringLocalizer<Foo.Bar.SharedResource> SharedStringLocalizer
```

Another option is removing the ResourcesPath by changing this code:
```
      services.AddLocalization(options => options.ResourcesPath = "Resources");
```
to 
``` 
services.AddLocalization();
```
But removing this is not an option, as I would like to keep this for a few other localizations, which I don't keep in sharedresource .resx files but in a folderstructure using the naming conventions /Resources/Controllers/etc... .

Ok so we got it working now by changing the namespace of the ```SharedResource.cs``` file, and making it point to the root of the project.

As you could see I have 3 languages: "en-US", "nl", "fr". Remember I did not create an SharedResource.fr.resx file. If I select "nl" I see "Welkom!", for "en-US" I see "Welcome!" but when I select "fr" I expect that it would not find it and defaults to "en-US" because in ```Startup.cs``` I have set this as my default culture.

This gives me the followin error: 
> System.Resources.MissingManifestResourceException: 'Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Foo.Bar.Resources.SharedResource.resources" was correctly embedded or linked into assembly "Foo.Bar" at compile time, or that all the satellite assemblies required are loadable and fully signed.'

and as a result it shows me the key "Welcome" from ```<h1 class="display-4">@SharedStringLocalizer["Welcome"]</h1>``` instead of "Welcome!" from my "en-US" file.

**Problem:**: I don't want to show my key-name as fallback. I want to have en-US value as fallback. I don't want users to see "SexyString" as translation from @SharedStringLocalizer["SexyString"].

**Question:** why does it not use my .en-US.resx file? What is the point of setting a default (fallback) culture in startup.cs if it doesn't even use that file and searches for just the .resx file without a culture?

Ok, we always try to survive in the jungle so we try to find a solution. 

If I remove the file ```SharedResource.cs``` from the ```Resources``` folder and add a file called: ```SharedResource.resx``` this will act as my fallback in case. Because it is a default file, it add also a .Designer.cs file which contains a class SharedResource when I set it from ```No code generation``` to ```Public``` (as I want my resource to be public, nothing wrong with that).  

**Problem:** the autogenerated class SharedResource from the SharedResource.resx file has the namespace: Foo.Bar.Resources.  Which will result in a search at Foo.Bar.Resources.Resources as already mentioned above.   when trying to change it VS will automatically change the namespace again.

**Another problem** is that I will now have to provide duplicate translations, once in .en-US.resx and once in .resx (unless I remove the .en-US.resx file).

**Possible solution**: 
Now if I add a ```SharedResources.cs``` file in the root of my project and change the inject code pointing to the root like this: ```@inject IStringLocalizer<Foo.Bar.SharedResource> SharedStringLocalizer``` it will use the ```SharedResource.resx``` file as fallback.  and my views in Resources will still be used when using naming conventions e.g. ```Resources/Controllers/…```  but I have to add another dummy class in the root because of the namespace problem.

I think I have described the pain that a lot of (new) developers have when they try to localize an asp.net core mvc 2.2 application.

**The possible solution I have added, is this the way localization with a shared resource file should be done, or am I missing something?** 

Please see also this:

- https://github.com/aspnet/Localization/issues/268

- https://github.com/aspnet/Mvc/issues/5426

- https://stackoverflow.com/a/42649361/187650

**Comment by mkArtakMSFT** [comment]
Thanks for your time and patience here, @wstaelens.
Unfortunately, this is not an area we invest in much at this time.
It sounds like you really want to have mixed localization enabled for your app, which is - use the provided `IStringLocalizer` mechanism as is, as well as bring your own custom localization solution. We would recommend you using a composite `IStringLocalizer` impolementation, which would encapsulate the logic of choice for the right localization strategy internally.

**Comment by wstaelens** [comment]
sad to see that not much time will be invested in this.
I'm aware of IStringLocalizer and have found several solutions, but still an area that could be improved a lot.
