### ISSUE TITLE
Conflict: 'Microsoft.Azure.Storage.Blob, Version=9.4.2.0 neutraland 'Microsoft.WindowsAzure.Storage, Version=9.3.1.0 #166

### ISSUE THREAD

**Issue by hamdyghanem** [aspnet/AspNetCore#8401]
I have a .netCore 2.2 Application which has "Microsoft.NET.Sdk.Functions" package

when you I try to use : "Microsoft.Azure.Storage.DataMovement" package to the project I have the following error:

Error CS0433 The type 'CloudBlockBlob' exists in both 'Microsoft.Azure.Storage.Blob, Version=9.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.WindowsAzure.Storage, Version=9.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

I already mentioned this one here: https://github.com/Azure/azure-storage-net-data-movement/issues/166 but it fits here more

**Comment by Eilon** [comment]
Hi, the GitHub repo for Azure Functions is https://github.com/Azure/Azure-Functions. I don't believe this issue is related to ASP.NET Core, so I'm closing this issue.

**Comment by hamdyghanem** [comment]
moved it
