### ISSUE TITLE
With SDK 3.0 Preview4, it will return CSC warning AD0001 when run dotnet build for webapi project at first time

### ISSUE THREAD

**Issue by livarcocc** [aspnet/AspNetCore#8403]
_From @yuki233 on March 11, 2019 8:9_

## Steps to reproduce
1. Install SDK 3.0.100-preview4-010703

## Expected  behavior
1. Run below command
_dotnet new webapi
dotnet build_

## Actual behavior
Dotnet build succeeded with CSC warning AD0001
![image](https://user-images.githubusercontent.com/1578239/54108642-7a66ba00-4417-11e9-8545-7f2f40516ab1.png)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-010703
 Commit:    4ccc726730

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-010703\

Host (useful for support):
  Version: 3.0.0-preview4-27510-12
  Commit:  cf9d52e1f0

.NET Core SDKs installed:
  3.0.100-preview4-010703 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview4-19158-05 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27510-12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27508-60 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

_Copied from original issue: dotnet/cli#10961_

**Comment by livarcocc** [comment]
This seems like an exception on the analyzer itself. Moving to ASP.NET.

**Comment by pranavkm** [comment]
Self assigning for preview4 milestone.
