### ISSUE TITLE
JSInterop improvements

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#8404]
Right now we just throw an exception when JSInterop gets called within prerendering. We want to provide a better experience for that. There are a few ideas:
* Add Try**** extension methods to JSInterop that will not throw.
* Add some way to figure out whether we are prerendering or not.
* Provide a directive to indicate that a given component can't be prerendered and put a placeholder instead.

**Comment by DNF-SaS** [comment]
Please also check why await JsRuntime.InvokeAsync() awaits forever when used in Component.OnInitAsync() - it's a real show-stopper if an application needs data from JS for initialization.
See here: https://github.com/aspnet/AspNetCore/issues/8274

**Comment by SQL-MisterMagoo** [comment]
While we wait for an official solution, I have provided a nuget package to expose the PreRendering status
https://www.nuget.org/packages/PreRenderComponent/
It just uses a CascadingValue to share "IsPreRendering" with your components/pages.

**Comment by SteveSandersonMS** [comment]
I'm going to close this in favour of #8786, because there is now more detail over there.
