### ISSUE TITLE
Remote validation calling server-side Action with inconsistent parameter name

### ISSUE THREAD

**Issue by armitagemderivitec** [aspnet/AspNetCore#8408]
We are using Remote Model validation which is great in AspNetCore since the server-side logic no longer needs to live in the attribute itself, which led to circular dependencies in the past. 

What we are now missing is being able to use generic validation on things like dates, phone numbers etc where between multiple view models the property names are different. 

We would like to try and avoid having an action per property name and rather bind based on property type rather than name. Is this possible currently as from the docs it looks like it isn't?

Our current alternative is to remove the properties from the action method and gather the them from the HttpContext query using ElelmentAt[x].Value assuming that the order is consistent when using additional columns.

A built in solution would be great.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @armitagemderivitec.
This is not something we plan to add to the framework.
