### ISSUE TITLE
Building Mvc from Visual Studio is broken

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#8413]
This was originally reported by CTI team.

Repro:
- Clean and run `restore.cmd`
- Open Mvc.sln in VS using `startvs.cmd`
- Right click the solution and click "Build Solution"

Expected:
Build successful

Actual:
Build failed
![image](https://user-images.githubusercontent.com/1579269/54152412-652f6280-43fa-11e9-8dd8-af357ffacb5a.png)

It looks like this might be related to [this](https://github.com/aspnet/AspNetCore/commit/2d9cba86fd304777ba27a54620a8d315f58d3602#diff-9eeb44021e640e1afee6244400547518R18) change. cc @javiercn

**Comment by javiercn** [comment]
@pranavkm This is also related to not building the js projects by default.
