### ISSUE TITLE
TypeLoadException in Blazor app

### ISSUE THREAD

**Issue by AndreasTruetschel** [aspnet/AspNetCore#8414]
### Describe the bug
I am using a blazor app (version 0.9.0) referencing `System.Memory` nuget-package in version `4.5.2`. The build is fine but when running, the browser console shows an error that types of the package could not be resolved throwing a `System.TypeLoadException`. (See screenshot below)

I managed to get it working by copying the System.Memory.dll from the nuget package to the blazor build output (dist\_framework\_bin\).

### To Reproduce
1. Using this version of ASP.NET Core 3 preview 3
2. Run this code 
The project is hostes here: https://github.com/AndreasTruetschel/BlazorSignalR
It is a port of the library to Blazor 0.9.0
To reproduce, the [copy post-build event](https://github.com/AndreasTruetschel/BlazorSignalR/blob/master/test/BlazorSignalR.Test.Client/BlazorSignalR.Test.Client.csproj#L19) (as described above) has to be removed.

3. With these arguments ---
4. See error (See description)

### Expected behavior
(See description)

### Screenshots
![grafik](https://user-images.githubusercontent.com/12112026/54152943-af3a3780-443e-11e9-85fd-f1f5265b71cc.png)

### Additional context
---

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AndreasTruetschel.
This is a `Mono` issue so please file a bug in `https://github.com/mono/mono` repo instead.
