### ISSUE TITLE
Error during runtime compilation for Razor views

### ISSUE THREAD

**Issue by brett-1hw** [aspnet/AspNetCore#8416]
**REPRO:**

1. Open Visual Studio 2019
2. Create New _ASP.NET CORE Web Application_ project
3. Select _Web Application (Model-View-Controller)_ option
4. Add package _Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation_
5. Update _ConfigureServices_ method in _Startup.cs_:
```
services.AddMvc().AddRazorRuntimeCompilation();
```
6. Start debugging project
7. Edit _Index.cshtml_:
```
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcomeeee</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

```
8. Refresh page to see changes

**EXPECTED:**

- Razor views recompile and display updates in browser

**ACTUAL:**

- 500 error displayed: InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery
![image](https://user-images.githubusercontent.com/20304811/54158017-f95ff080-441f-11e9-986c-c561ad32062b.png)

**Comment by pranavkm** [comment]
@brett-1hw could you try editing your project file to set `<PreserveCompilationReferences>true</PreserveCompilationReferences>`? I suspect you're running in to the issue I described in https://github.com/aspnet/AspNetCore/issues/7966#issuecomment-471047409

**Comment by brett-1hw** [comment]
Yep, that does indeed fix the problem. I should've specified that I'm running a netcoreapp3.0 project with the latest preview 3 SDK.

**Comment by pranavkm** [comment]
@brett-1hw I've documented the workaround in our known issues: https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md. We'll use #7966 to track fixing this.
