### ISSUE TITLE
Send PRs to partner project packages to enable API analyzer

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#8418]
We added a feature to the WebSDK to enable OpenAPI analyzers when a flag is present `IncludeOpenAPIAnalyzers`. We should send PRs to partner teams (e.g. NSwag) to enable this when their packages are referenced.

**Comment by pranavkm** [comment]
cc @glennc

**Comment by pranavkm** [comment]
@mkArtakMSFT adding this to the preview4 milestone as discussed in your sync up.

**Comment by mkArtakMSFT** [comment]
This can happen after Preview7 code complete date, before we actually ship.

**Comment by mkArtakMSFT** [comment]
The flag is now included in this PR: https://github.com/RicoSuter/NSwag/pull/2226
