### ISSUE TITLE
[Blazor] Inject different services during prerendering

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#8422]
I don't know if prerendering already works in Blazor 0.9 on WebAssembly but we should be able to use different services during prerendering and in the client app. The most obvious example:

- during prerendering we can use direct database access to read information
- in the client app we have to use WebAPI calls

I would like to create a common interface (repository pattern) and two different implementations to optimize server performance.

There is an issue related to prerendering and JSInterop already filled in: #8404 Maybe both problems can be solved at the same time.

**Comment by SteveSandersonMS** [comment]
You can already use different DI services during server-side execution (e.g., prerendering) vs client-side execution. By default you already get two different `Startup.cs` classes, so just put whichever services you want in each.

We're not planning to have an entirely separate DI container for prerendering vs other server-side execution, as that wouldn't make sense given that the same component instances will have a lifetime spanning both prerendering and then ongoing server-side execution.
