### ISSUE TITLE
TempData does not clear when using __Host- as cookiename prefix

### ISSUE THREAD

**Issue by MrJoe** [aspnet/AspNetCore#8426]
### Describe the bug
We have configured our cookies to always use the `__Host-` cookiename prefix. Eg for the TempData cookie provider we use `__Host-tmp`. This requires the cookie to always have the `secure` flag set on the cookie (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Directives). This works fine when a new cookie is created however when a cookie should be deleted the `secure` flag isn't set when creating a cookie with an Expire date of 1970-1-1 (https://github.com/aspnet/AspNetCore/blob/master/src/Shared/ChunkingCookieManager/ChunkingCookieManager.cs#L283). This causes the browser to ignore the 'new' cookie and thus it will retain the old TempData value when all TempData normally would have been cleared.

### To Reproduce
1. Using this version of ASP.NET Core 2.1 (we try to keep at the LTS versions)
2. The services.AddMvc is configured with the cookieTempData provider as follows:
```
				.AddCookieTempDataProvider(setupAction => {
					setupAction.Cookie.Name = "__Host-tmp";
					setupAction.Cookie.HttpOnly = true;
					setupAction.Cookie.SecurePolicy = CookieSecurePolicy.Always;
					setupAction.Cookie.SameSite = SameSiteMode.Lax;
				})
```

3. In an action add one value to the tempdata eg `TempData["some"] = "Test";`
4. In the next action read the `var v = TempData["some"];` which would clear the "some" key from the TempData and because this is the only entry in the TempData it should cause the cookie to be deleted.
5. Reload the page and notice `TempData["some"];` still has a value, this is because the `__Host-tmp` is still sent with the request as the browser did ignore the `set-cookie: __Host-tmp=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax` due to the missing `secure` flag.

### Expected behavior
The TempData["some"] should have been null on the page reload, in step 5. And in step 4 the cookie header should have been `set-cookie: __Host-tmp=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; secure; samesite=lax`

**Comment by Tratcher** [comment]
I expect the issue is here where it doesn't copy over the Secure flag:
https://github.com/aspnet/AspNetCore/blob/f303a55a8edf632738eb6e15312aac443cdf21b1/src/Shared/ChunkingCookieManager/ChunkingCookieManager.cs#L283-L305

As called from here:
https://github.com/aspnet/AspNetCore/blob/f303a55a8edf632738eb6e15312aac443cdf21b1/src/Mvc/Mvc.ViewFeatures/src/CookieTempDataProvider.cs#L79

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MrJoe.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
Sure. @tratcher thanks for the initial investigation

**Comment by javiercn** [comment]
@Tratcher While looking into this, shouldn't the cookiechunkingmanager also include max-age in here?
https://github.com/aspnet/AspNetCore/blob/master/src/Shared/ChunkingCookieManager/ChunkingCookieManager.cs#L171

**Comment by Tratcher** [comment]
Yes, include max age. I'm starting to think we need a helper to copy the properties from CookieOptions to SetCookieHeaderValue, it happens in at least three places:
https://github.com/aspnet/AspNetCore/blob/62351067ff4c1401556725b401478e648b66acdc/src/Shared/ChunkingCookieManager/ChunkingCookieManager.cs#L164-L172
https://github.com/aspnet/AspNetCore/blob/62351067ff4c1401556725b401478e648b66acdc/src/Security/CookiePolicy/src/ResponseCookiesWrapper.cs#L102-L110
https://github.com/aspnet/AspNetCore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/Http/src/Internal/ResponseCookies.cs#L60-L68
