### ISSUE TITLE
[SignalR]:Microsoft.AspNet.SignalR.Client 2.4.0 in  Xamarin Forms 3.4. The connection has not been established

### ISSUE THREAD

**Issue by jopima** [aspnet/AspNetCore#8430]
SignalR Connections is Established in the Xamarin Forms App Class in the  OnStart () method

          if (CentralSignalService.GlobalSignalHubManager != null)
                {
                    CentralSignalService.GlobalSignalHubManager.ConnectOnStartAsync();
                }
                else
                {
                    CentralSignalService centralSignalService = new CentralSignalService();
                    centralSignalService.ConnectOnStartAsync();
                }

When Device goes to sleep this is called and kills the Signal Connection
            if (CentralSignalService.GlobalSignalHubManager != null)
                {
                    CentralSignalService.GlobalSignalHubManager.StopConnectionAsync();
                }

When the Device wakes up from sleep and i try to invoke one method. Such as: 
 public async Task<SessionResponseModel> InitializeChatSession(SessionRequestModel model)
        {

            if (CentralSignalManager.SignalConnection.State == ConnectionState.Disconnected)
            {
                await CentralSignalManager.ConnectAsync();
            }

            var result = await MessagingHubproxy.Invoke <SessionResponseModel> "initiateSession", model);

            return result;
        }

 the App Freezes and AppCenter registers the following crash report:
CentralSignalService.<ConnectOnStartAsync>b__18_0 ()
System.InvalidOperationException: The connection has not been established.

Connection.Send (System.String data)
HubProxy.Invoke[TResult,TProgress] (System.String method, System.Action`1[T] onProgress, System.Object[] args)
HubProxy.Invoke[T] (System.String method, System.Object[] args)
CentralSignalService.<ConnectOnStartAsync>b__18_0 ()
Forms+AndroidPlatformServices+<>c__DisplayClass23_0.<StartTimer>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object:3624c80f-7021-434f-909a-8fece68fb5a8 (intptr,intptr)

Note : I implemented this to refresh connection in case is closed
 SignalConnection.Closed += SignalConnection_Closed;

Stop Method:
 public  void StopConnectionAsync() {

            if (SignalConnection == null) { return; }

            if (SignalConnection.State == ConnectionState.Connected) {
                 SignalConnection.Stop();
            }

            if (SignalConnection.State == ConnectionState.Connecting)
            {
                SignalConnection.Stop();
            }

            if (SignalConnection.State == ConnectionState.Reconnecting)
            {
                SignalConnection.Stop();
            }

        }

 public async void ConnectOnStartAsync(){
 if (SignalConnection == null) { return; }
                if (SignalConnection.State == ConnectionState.Connected) { return; }

                await SignalConnection.Start();

                IsConnectionAlive = true;
}

**Comment by halter73** [comment]
This issue was moved to SignalR/SignalR#4348
