### ISSUE TITLE
Make SignalR JavaScript tests output trx files

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#8438]
When the JavaScript tests for SignalR fail it gets reported as a less granular build failure instead of a specific test failure. To fix this VSTS would need to ingest a trx file ([or other supported format](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml)).

CC @muratg

**Comment by halter73** [comment]
@anurse

**Comment by anurse** [comment]
Is the goal here just to get the output ingested into AzP's list of test failures? I think our tests product xunit or junit style files and I'm pretty sure AzP's Publish Test Failures task supports that format.

**Comment by ryanbrandenburg** [comment]
Yes that's the goal. If we're already producing those files it should just be a matter of adding an additional [PublishTestResults task](https://github.com/aspnet/AspNetCore/blob/d7a960604083c98a6cbb38332680bd4487c28ed7/.azure/pipelines/jobs/default-build.yml#L168).

**Comment by anurse** [comment]
We should be producing them then (https://github.com/aspnet/AspNetCore/blob/321327f84b2b22dcff2e9beb06a9a64236c5cced/src/SignalR/clients/ts/jest.config.js). So it's just a matter of adding the YAML. Cool. We'll triage this.
