### ISSUE TITLE
Microsoft.AspNetCore.App implicit refs break production builds

### ISSUE THREAD

**Issue by lwansbrough** [aspnet/AspNetCore#8443]
When using implicit references in the .csproj for the Microsoft.AspNetCore.App package, failing to provide a Version parameter can lead to build failures if the server is not continually updated with the latest version of the .NET platform.

When opting to provide a version, we are presented with a compile time warning: 

> A PackageReference to 'Microsoft.AspNetCore.App' specified a Version of `2.2.2`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs

Following that link leads us to a document which outlines what the recommended procedure is for implicit refs, _but not why they are recommended._ I suspect the recommendation exists to keep .NET users on the latest version. Fair enough, but there's a failure to indicate that this recommendation will cause a build to fail in production if the runtime isn't updated to the latest patch version.

I suggest that the recommendation wording be updated in the original compile time warning (in addition to the text in the link) that while the recommendation exists, such a setting will break your setup without warning in production if you're not auto-updating your server.

**Comment by Eilon** [comment]
> such a setting will break your setup without warning in production if you're not auto-updating your server.

There was one or two times where there was a bug that prevented this from being true, but in the general case (and we've fixed those bugs), a 2.2.x app should work in production on whatever 2.2.x runtime is installed, as long as you *did not* specify the `.App` version, which is the recommended pattern.

Can you provide more info, such as a specific example, where you feel there is still a problem?

**Comment by Kritner** [comment]
We're having an issue related to this as well, some machines are able to build our code, others aren't.  Haven't been able to figure out what exactly is different - both machines at a minimum have the same sdk of 2.2.202 installed.

Here's some related info (note since making the comment linked i've installed the 2.2.202 sdk)
https://github.com/dotnet/sdk/issues/2253#issuecomment-480502212
https://github.com/dotnet/sdk/issues/2253#issuecomment-480510205

**Comment by natemcmaster** [comment]
@Kritner I think what you're running into is unrelated to the original intent of this issue. As far as we currently know, the error you mentioned in https://github.com/dotnet/sdk/issues/2253#issuecomment-480502212 is unrelated to this warning. I would recommend creating a new issue with complete repro steps on https://github.com/dotnet/sdk

**Comment by mairaw** [comment]
I also have filed this issue https://github.com/dotnet/sdk/issues/2879 that is related to this problem.

**Comment by natemcmaster** [comment]
@mairaw until dotnet/sdk#2879  can be addressed, what do you think about this PR https://github.com/dotnet/docs/pull/11736?

**Comment by mairaw** [comment]
I'm reviewing it right now. Finishing soon! Just started following the links and sharing the info. 😄

**Comment by natemcmaster** [comment]
@lwansbrough I believe I've addressed your feedback with an update to docs.
