### ISSUE TITLE
Authorize attribute not working because it's executed before app.UseAuthentication()

### ISSUE THREAD

**Issue by donnyv** [aspnet/AspNetCore#8445]
I just ran across this issue and spent a morning on it. 
https://github.com/aspnet/SignalR/issues/2316

Can this be added in the documentation somewhere? Maybe here?
https://docs.microsoft.com/en-us/aspnet/signalr/overview/security/hub-authorization

**Comment by mikaelm12** [comment]
The docs you linked to are actually referring to Classis ASP.NET SignalR (Sorry for the confusion). The ASP.NET Core SignalR Docs for Auth do show the `AddAuthentication` service being added for the call to `AddSignalR`
https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2#bearer-token-authentication

**Comment by donnyv** [comment]
It doesn't talk about the ordering of the calls though. How UseAuthentication() should be called first before UseSignalR()

**Comment by mikaelm12** [comment]
Sure, we could call out that you have to register the Auth middleware before calling `UseSignalR`

**Comment by mikaelm12** [comment]
Going to close this in favor of a docs issue I opened here: https://github.com/aspnet/Docs/issues/11389
