### ISSUE TITLE
[Razor Components] Programmatically redirect the user

### ISSUE THREAD

**Issue by devnixs** [aspnet/AspNetCore#8465]
Hello,

So far I haven't found a way to programmatically redirect the user to another page.
Here's what I'm currently doing, but it's hacky:

```csharp
        private readonly IJSRuntime _jsRuntime;

        public async Task Redirect(string location)
        {
            if (await IsServerSideRendering())
            {
                _httpContextAccessor.HttpContext.Response.Headers.Add("Location", location);
                _httpContextAccessor.HttpContext.Response.StatusCode = 302;
            }
            else
            {
                await _jsRuntime.InvokeAsync<string>("goTo", location);
            }
        }
```

And then I made a javascript function
```javascript
function goTo(location) {
  window.location.href = location;
}
```

This works great during the server side rendering, but otherwise, it's not ideal because `window.location.href = location` triggers a full page refresh.

Thanks for your help!

**Comment by julienGrd** [comment]
Hi devnixs, you don't have to redirect through Js but use c# code and inject IUriHelper

[Inject]
protected IUriHelper UriHelper { get; set; }

Usage
this.UriHelper.NavigateTo("your relative page url");

**Comment by devnixs** [comment]
Thanks @julienGrd, I'm gonna try this.

**Comment by vertonghenb** [comment]
if it's a MVC controller or page outside of the client router you can use 
```cs
this.UriHelper.NavigateTo("/your relative page url", forceLoad:true);
```
This would skip internal "client side" routing and go to the page

**Comment by devnixs** [comment]
Just checked and UriHelper.NavigateTo only navigates client-side. This means is does no redirection during the prerendering.

So I changed my code to be

```csharp

        public async Task Redirect(string location)
        {
            if (await IsServerSideRendering())
            {
                _httpContextAccessor.HttpContext.Response.Headers.Add("Location", location);
                _httpContextAccessor.HttpContext.Response.StatusCode = 302;
            }
            else
            {
                this.UriHelper.NavigateTo(location);
            }
        }
```

And this works great.
Closing this ticket then.
