### ISSUE TITLE
UseForwardedHeaders does not select correct client IP address from X-Forwarded-For when it has multiple values

### ISSUE THREAD

**Issue by heemskerkerik** [aspnet/AspNetCore#8471]
### Describe the bug
The `ForwardedHeadersMiddleware` does not handle multiple values in the `X-Forwarded-For` header correctly. When there are multiple proxies in front of an application, each proxy appends a remote IP address to the header. The middleware picks up the **right-most** value and assigns it to the connection's `RemoteIpAddress`, but it should be using the **left-most** value ([source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#Syntax)).

### To Reproduce
1. Using ASP.NET Core 2.2.0
2. Run this code: https://gist.github.com/heemskerkerik/2e3a5b1b5088e28c7cc370f466cbef1d
3. Make a HTTP request to the application: 
   ```powershell
   Invoke-WebRequest http://localhost:5000 -UseBasicParsing -Headers @{ 'X-Forwarded-For' = '1.1.1.1, 2.2.2.2' }
   ```

### Expected behavior
The header provided describes a situation where the 'real' client has the IP 1.1.1.1, the request was originally handled by a proxy with the IP 2.2.2.2, and there is yet another proxy after that. 

The output _should_ be the following:

```
X-Forwarded-For:
2.2.2.2
Remote IP: 1.1.1.1
```

The observed behavior is that the output is the following:

```
X-Forwarded-For:
1.1.1.1
Remote IP: 2.2.2.2
```

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\Administrator\AppData\Local\Microsoft\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.104 [C:\Users\Administrator\AppData\Local\Microsoft\dotnet\sdk]
  2.1.505 [C:\Users\Administrator\AppData\Local\Microsoft\dotnet\sdk]
  2.2.105 [C:\Users\Administrator\AppData\Local\Microsoft\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Users\Administrator\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Users\Administrator\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Users\Administrator\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Users\Administrator\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Users\Administrator\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Users\Administrator\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by blowdart** [comment]
Yes. As the [documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2) states

> Forwarded Headers Middleware default settings can be configured. The default settings are:
> 
> There is only _one proxy_ between the app and the source of the requests.
> Only loopback addresses are configured for known proxies and known networks.
> The forwarded headers are named X-Forwarded-For and X-Forwarded-Proto.

There's no way we can actually figure out your proxy setup, and an attacker can, of course, add their own X-Forwarded-For header, with misconfigured proxies not stripping it at all. Thus, if you know you have chained proxies then you need to tell the middleware about them. Set the [ForwardLimit](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#forwarded-headers-middleware-options) on the ForwardedHeaderOptions.

**Comment by heemskerkerik** [comment]
@blowdart, I did as you suggested, changed the `ForwardLimit` to 2 (since there are two proxies in the test scenario described), but the output remains the same.

I also tried setting it to `null`, but that made no difference.

**Comment by heemskerkerik** [comment]
Documentation isn't terribly clear, but as @blowdart says, you have to change the `ForwardLimit`. You also need to either clear `KnownProxies`/`KnownNetworks` or add the values for trusted proxies there.

Enabling logging, as the documentation says, would have revealed the issue.
