### ISSUE TITLE
Asp.net core using storage nuget package from 2017 results in nuget conflict

### ISSUE THREAD

**Issue by hansmbakker** [aspnet/AspNetCore#8472]
### Describe the bug
`Microsoft.AspNetCore.DataProtection.AzureStorage` depends on [`WindowsAzure.Storage`](https://www.nuget.org/packages/WindowsAzure.Storage/8.1.4), a nuget package from 2017 😱. This creates conflicts e.g. when also using Nuget packages that rely on its modern replacement ([`Microsoft.Azure.Storage.*`](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob)). E.g. Bot Framework does this.

This is an issue for my project.

Error I'm getting:
```
The type 'CloudStorageAccount' exists in both 'Microsoft.Azure.Storage.Common, Version=9.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.WindowsAzure.Storage, Version=8.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

**Comment by blowdart** [comment]
@muratg Who can I borrow for data protection right now?

**Comment by muratg** [comment]
cc @Eilon

**Comment by natemcmaster** [comment]
We are updating DataProtection.AzureStorage in 3.0 to use the new Microsoft.Azure.Storage.Blob dependency. This should resolve the compiler conflict in the scenario originally reported.

If you want to use Microsoft.Azure.Storage.Blob in 2.1 and 2.2 apps along with DataProtection.AzureStorage, you can resolve the compiler error by fully-qualifying the type reference, or adding a `using` such as this to the top of your file.

```c#

using CloudStorageAccount = Microsoft.Azure.Storage.CloudStorageAccount;
```

Closing as we do not plan to update 2.1 or 2.2 to use Microsoft.Azure.Storage APIs.
