### ISSUE TITLE
[Razor Components] How to deal with application restarts?

### ISSUE THREAD

**Issue by devnixs** [aspnet/AspNetCore#8476]
Hello,

When the server has to restart, for example to do a new deployment, how do you deal with this?

**Since the page state is kept in memory in the server, when the app restarts the state is lost and the page is left broken.**
The user then has to refresh the page for it to work again.

- Is there a way to keep this state in a more persistent storage?
- Or do you handle this by automatically refreshing the user's page when it detects there's a new version?

**Comment by devnixs** [comment]
I'm doing this for now, so the user doesn't stay in a broken page : 
```javascript
window.addEventListener('unhandledrejection', function(promiseRejectionEvent) {
  if (promiseRejectionEvent.reason.message === "Cannot send data if the connection is not in the 'Connected' State.") {
    location.reload();
  }
});
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @devnixs.
We'll come up with a documentation to cover this.

**Comment by javiercn** [comment]
@pranavkm can probably help you here. If you deploy a new version your server will stop and all the state will get lost. The client will loose the connection to the server and will be left trying to reconnect. The reconnection will fail (as the server has rebooted) and at some point we'll stop reconnecting automatically.

I'm not sure there's anything else you can do other than implementing this yourself. You would need to for example:
* Create an endpoint on your server that you can hit to tell all active sessions they need to persist their state.
* Each session would persist their state (you'll have to implement this)
* Each session would send a message to the client to inform that a new version is going to be deployed.
* The client would wait until the server is back up after the deployment and visit a specific page to allow the server to retrieve the persisted state for the client and restore the app to where it was.

This is just a way it could work. We don't provide anything for this out of the box.

**Comment by devnixs** [comment]
Thanks @javiercn.
This is helpful.
