### ISSUE TITLE
Rename default __RequestVerificationToken

### ISSUE THREAD

**Issue by Jon-Murray** [aspnet/AspNetCore#8479]
Hi,

It is fairly important for us to be able to mask the tech stack in use as much as possible. It seems that there is currently no way to rename the default "__RequestVerificationToken" parameter when CSRF protections are enabled. It would be very beneficial to be able to set this to an arbitrary name, like what is possible by setting the AntiforgeryOptions in Startup.

Is it likely this could be implemented? Stackoverflow/google seem to suggest this is a hard-coded name, and cannot be changed.

Thanks

**Comment by rynowak** [comment]
You should be able to change this.

```
public void ConfigureServices(IServiceCollection services)
{
    ....
    services.Configure<AntiforgeryOptions>(options => options.FormFieldName ="WhateverYouPrefer");
}
```
https://github.com/aspnet/AspNetCore/blob/dbf746d210bf5fd52c994d650b26a06eda41cf47/src/Antiforgery/src/AntiforgeryOptions.cs#L66

**Comment by Jon-Murray** [comment]
Can confirm that this work, sorry for the trouble and thanks for the quick reply.
