### ISSUE TITLE
Update partner packages to consume the latest version of our packages

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#8487]
This is the work we need to do near the end of preview4 so that we don't leave NSwag and Swashbuckle broken.

**Comment by dougbu** [comment]
@mkArtakMSFT near the end or after we have released preview 4 to NuGet?

**Comment by Eilon** [comment]
@dougbu - is this a preview5 thing or later?

**Comment by dougbu** [comment]
It's both. I'll be sending a PR for the NSwag repo later today referencing the preview 5 daily builds. Expect that PR won't close 'til I update it to reference the then-public packages.

**Comment by dougbu** [comment]
RicoSuter/NSwag@4439cf2ec6aa
