### ISSUE TITLE
Add @using Microsoft.AspNetCore.Components.Services in _ViewImports.cshtml by default

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/AspNetCore#8494]
### Is your feature request related to a problem? Please describe.
In a lot of Razor Component apps we'll navigate programatically using `IUriHelper`. However it's needed to always add the namespace `@using Microsoft.AspNetCore.Components.Services` at the top of the file or in the `_ViewImports.cshtml` file. Since it's needed in a lot of applications i'd suggest we add it in the templates by default.

### Describe the solution you'd like
Add `@using Microsoft.AspNetCore.Components.Services` in `_ViewImports.cshtml` in the template.

**Comment by rynowak** [comment]
I think what's much more likely is to move it to another namespace. I agree that this is worth doing something about and that's good feedback 👍

**Comment by vertonghenb** [comment]
@rynowak I was expecting it to be in : `Microsoft.AspNetCore.Components.Routing`. 
Maybe put it there since that is already in the `_ViewImports` file?

**Comment by mkArtakMSFT** [comment]
This is being resolved by the referenced PR in slightly different way.
