### ISSUE TITLE
GDPR accept consent differs between http and https

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/AspNetCore#8503]
### Describe the bug
I did all types of experiments on the _CookeConsentPartial.cshtml normally generated by .net core 2.2 templates. The content of the file is as follows:

```csharp
@using Microsoft.AspNetCore.Http.Features

@{
    var consentFeature = Context.Features.Get<ITrackingConsentFeature>();
    var showBanner = !consentFeature?.CanTrack ?? false;
    var cookieString = consentFeature?.CreateConsentCookie();
}

@if (showBanner)
{
<div id="cookieConsent" class="alert alert-info alert-dismissible fade show" role="alert">
    This website uses cookies, and also may collect some information using Google Analytics. <a href="@ArticleHelpers.ProcessURL(Context.Request, new [] { "home", "legal", "privacy-policy" },"")">Learn More</a>.
    <button type="button" class="accept-policy close" data-dismiss="alert" aria-label="Close" data-cookie-string="@cookieString">
        <span aria-hidden="true">Accept</span>
    </button>
</div>
    <script>
        (function () {
            var button = document.querySelector("#cookieConsent button[data-cookie-string]");
            button.addEventListener("click", function (event) {
                document.cookie = button.dataset.cookieString;
            }, false);
        })();
    </script>
}
```
I did the experiments under an environment that does not enforce https by commenting out `app.UseHsts();` in startup.cs.
I tested the effect of GDPR acceptance under http and https and under www and non-www and studied the effect of each case on the rest for the 4 combinations. 

I found different behaviors under different protocols:
Accept the consent under https, then the GDPR banner becomes hidden under https only (the http version is not affected)
Accept the consent under http, then the GDPR banner becomes hidden under both http and https

### To Reproduce
1. Using this version of ASP.NET Core '2.2.3'
2. Create a new .net core project using templates
3. Comment out the line `app.UseHsts()` in startup.cs
4. Under Incognito, accept the banner under http and see the effect on https and also vice-versa.

### Expected behavior
I expect to make acceptance under https similar to the normal expected behavior under http. The opposite is also OK as long as we unify the behavior between the protocols.

### Screenshots
N/A

### Additional context
Include the output of `dotnet --info`
[dotnet--info.txt](https://github.com/aspnet/AspNetCore/files/2965231/dotnet--info.txt)

**Problem source**
May be it is relates to the behavior in the following code:

https://github.com/aspnet/AspNetCore/blob/62351067ff4c1401556725b401478e648b66acdc/src/Security/CookiePolicy/src/ResponseCookiesWrapper.cs

**Comment by blowdart** [comment]
This is because if a cookie is written out for the first time on https it's marked HTTPS only, and not available to HTTP.

We make this assumption because, frankly, if you support HTTPS you need to start thinking about moving to HTTPS only. There's no excuse any more. Plus, if you're taking PII and GDPR is a concern then HTTPS is going to be a requirement for you anyway, and you should be sending the HSTS header as well.

**Comment by anurse** [comment]
As @blowdart said, this is by-design behavior when on HTTPS.
