### ISSUE TITLE
How to run signalR client(C#) on windows xp?

### ISSUE THREAD

**Issue by bluetianx** [aspnet/AspNetCore#8504]
I was asked to run wpf client used signalr  on windows xp. Can I do it ,How to do it ? I felt so bad when I heard the news.

**Comment by bluetianx** [comment]
I found signalr client wrired by C++ in src.  can it use in product ,can it run winXP?

**Comment by BrennanConroy** [comment]
Windows XP is [out of support as of 2014](https://www.microsoft.com/en-us/windowsforbusiness/end-of-xp-support) so we will not be testing it in that environment.

However you are free to grab the source and try to use it.

> can it use in product

I wouldn't recommend it as we haven't released it yet.
