### ISSUE TITLE
User Impersonation Problem

### ISSUE THREAD

**Issue by Eyadius** [aspnet/AspNetCore#8505]
### Describe the bug
I want to run Powershell scripts from asp.net core, that is hosted as Windows Service. With Windows Authentication
I did it almost, but if i run "whoami" i get the UserName who run the service not the authenticated User.

### To Reproduce
see uploaded File 
[WindowsAuthenticationProblem.zip](https://github.com/aspnet/AspNetCore/files/2965894/WindowsAuthenticationProblem.zip)
deploy it, and start it as Windows Service
call http://localhost:8888

### Actually behavior

If i run it now, i get:

Without	'WindowsIdentity.RunImpersonated'	With	Current Authenticated User	{User: ##The Authenticated User##}
Without	'WindowsIdentity.RunImpersonated'	With	Current Windows Identity	{User: NT AUTHORITY \ SYSTEM}
Without	'WindowsIdentity.RunImpersonated'	With	PowerShell command whoami	{User: NT AUTHORITY \ SYSTEM}
With	'WindowsIdentity.RunImpersonated'	With	Current Authenticated User	{User: ##The Authenticated User##}
With	'WindowsIdentity.RunImpersonated'	With	Current Windows Identity	{User: ##The Authenticated User##}
With	'WindowsIdentity.RunImpersonated'	With	PowerShell command whoami	{User: NT AUTHORITY \ SYSTEM} ####Here, the authenticated username should be printed###

### Expected behavior
The auhtenticated UserName

"Sorry for my bad English."

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
