### ISSUE TITLE
Razor Components escaping new line during prerender

### ISSUE THREAD

**Issue by mashbrno** [aspnet/AspNetCore#8507]
There are many &#xD;&#xA; withing HTML output. While this is OK for standard html, it fails withing <script> element, eg.
<script> \\Middleware: &#xD;&#xA; method();

To Reproduce: The behaviour is visible in default template for Razor Components in Visual Studio, while real problem starts with using Blazor.Fluxor nuget.

Expected behavior: Keep printable characters (newline, tab, etc.) as is.

**Comment by mashbrno** [comment]
Solution was to replace calls `AddContent` by `AddMarkupContent` at `RenderTreeBuilder`.

**Comment by tn-5** [comment]
The escaping of CR/LF in has another effect. In Safari it does not process a CR/LF and an escaped CR/LF the same within HTML. This causes some unwanted "blank lines" when certain layout combinations are used and the CR/LF characters are escaped.
