### ISSUE TITLE
[Components] Compile error when using <CascadingValue></CascadingValue>

### ISSUE THREAD

**Issue by mwinkler** [aspnet/AspNetCore#8508]
### Describe the bug
I build a component library:

Component1.razor:
```
@typeparam TItem

<CascadingValue Name="CasadingValue1" Value="true">
    @ChildContent
</CascadingValue>

@functions {
    [Parameter] MyEnum Style { get; set; }
    [Parameter] IEnumerable<TItem> Items { get; set; }
    [Parameter] RenderFragment ChildContent { get; set; }
}
```

MyEnum:
```
namespace RazorClassLib
{
    public enum MyEnum
    {
        Value1,
        Value2
    }
}
```

If I start using `<CascadingValue></CascadingValue>` inside the component, the consuming project of `Component1` is unable to compile.
It fails on the enum property `Style` of `Component1`.

Error:
`CS1503	Argument 4: cannot convert from 'RazorClassLib.MyEnum' to '__Blazor.RazorClassLib.MyEnum'`

![Error](https://user-images.githubusercontent.com/1729418/54366391-de37ef80-4670-11e9-8e6d-eb95a6ddadb5.PNG)

It seems a issue with this '__Blazor' namespace witch is introduced when using `<CascadingValue></CascadingValue>`

### To Reproduce
1. Clone https://github.com/mwinkler/RazorComponentsIssue.git
2. Open with VS 2019
3. Rebuild
4. Uncomment `<CascadingValue>...</CascadingValue>` block in `RazorClassLib\Component1.razor`
5. Rebuild

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ajaybhargavb** [comment]
Doesn't repro anymore. Dup of https://github.com/aspnet/AspNetCore/issues/5637

**Comment by fs86** [comment]
I still get this error in the current version (preview4)
