### ISSUE TITLE
Performance issue with reading Requies.Form collection

### ISSUE THREAD

**Issue by yevgenyka** [aspnet/AspNetCore#8510]
Hi,
We have a service, which runs kestrel. Our customers sometimes send big requests with 4MB data in the Request.Form collection. In that case, it takes more than 10 sec to read the form collection, using Request.ReadFormAsync method. When running kestrel on the service, based on dotnetframework, it may take more than 30 sec

We found, that this happens when the request contains a mix of Unicode characters, like text, translated to other languages (in our case there are many languages) with some quotes, "<>" characters or even "abc".
The main problem seems to be in the fact, that ReadFormAsync uses Uri.UnescapeDataString method, which takes most of the time (see enclosed dotTrace snapshot)
In our benchmarks (enclosed) we can see that Uri.UnescapeDataString takes about 39 sec, but WebUtility.UrlDecode takes 14 ms

1. In enclosed solution restore packages
2. Run with Ctrl+F5 (that will load the servers and perform benchmarks)
3. See benchmarks results

Enclosed are demo solution to reproduce the issue, benchmarks results and dotTrace snapshot:

[EscapeTest.zip](https://github.com/aspnet/AspNetCore/files/2967147/EscapeTest.zip)
[readFormSnapshot.zip](https://github.com/aspnet/AspNetCore/files/2967150/readFormSnapshot.zip)
![dotTrace](https://user-images.githubusercontent.com/42742603/54369279-52c55b00-467e-11e9-8e72-9f2ea71d426c.PNG)
[BenchmarkDotNet.Artifacts.zip](https://github.com/aspnet/AspNetCore/files/2967151/BenchmarkDotNet.Artifacts.zip)

**Comment by mkArtakMSFT** [comment]
This issue was moved to dotnet/corefx#36050
