### ISSUE TITLE
Razor Components Generating g.cs with AddMarkupContent() instead of AddContent()

### ISSUE THREAD

**Issue by mashbrno** [aspnet/AspNetCore#8511]
Some of the pages (I haven't found the pattern) are generated using AddMarkupContent() which will keep the HTML readable, but some with  AddContent() where all new lines, tabs etc. are replaced by respective &#xD; characters.

Can be AddMarkupContent() widely used?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mashbrno.
We track this fix in https://github.com/aspnet/AspNetCore/issues/6185
