### ISSUE TITLE
Update Razor Components template to have only one `Pages` directory

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#8516]
We should do this after #6374.

**Comment by javiercn** [comment]
@rynowak Can we do something here already?

**Comment by danroth27** [comment]
Proposed project structure:

- Pages
  - _Imports.razor
  - _ViewImports.cshtml
  - Counter.razor
  - FetchData.razor
  - Index.razor
  - Index.cshtml
- Services
  - WeatherForecast.cs
  - WeatherForecastService.cs
- Shared
  - MainLayout.razor
  - NavMenu.razor
- _Imports.razor
- App.razor

Some downsides to this approach
- Two Index files. We could resolve this by implementing #7528
- Subtle differences between Razor Pages and Razor Component pages, like differences in how routing works.

**Comment by SteveSandersonMS** [comment]
Maybe Index.cshtml should be something like Host.cshtml as a shorter-term way to sidestep the first issue.

**Comment by danroth27** [comment]
> Maybe Index.cshtml should be something like Host.cshtml as a shorter-term way to sidestep the first issue.

We would need an explicit route in *Host.cshtml* (`@page "/"`), but I think that works.
