### ISSUE TITLE
Allow configuration of ValidationVisitor.ValidateComplexTypesIfChildValidationFails via MvcOptions

### ISSUE THREAD

**Issue by bordecal** [aspnet/AspNetCore#8519]
### Is your feature request related to a problem? Please describe.
Configuration of ValidationVisitor.ValidateComplexTypesIfChildValidationFails is not currently possible without implementing a custom `IObjectModelValidator`.  Since `DefaultObjectValidator` has internal visibility, it cannot be inherited in user code in order to apply customization of this property, which means that a separate subclass of `ObjectModelValidator` must be created.  While doing so is relatively trivial (including reproducing the current behaviour of `DefaultObjectValidator`), a custom subclass would not inherit any changes made to `DefaultObjectValidator` in the future, making this a somewhat brittle approach.

### Describe the solution you'd like
The `MvcOptions` class already contains multiple properties for customizing validation behaviour.  Would it be possible to add support for toggling `ValidateComplexTypesIfChildValidationFails` as well?

### Describe alternatives you've considered
Making it possible to inherit from `DefaultObjectValidator` in user code might also be an option here, but it doesn't seem to be particularly consistent with the existing design around customizing validation behaviour.

### Additional context
N/A

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @bordecal.
Can you please provide more details regarding what you're trying to achive. It's not clear what's the scenario you need this configuration for.

**Comment by bordecal** [comment]
The goal is simply to allow complete validation results to be returned to an endpoint caller under all circumstances, including when a validation failure is in part due to an invalid child object.  Setting `ValidateComplexTypesIfChildValidationFails` to `true` on any `ValidationVisitor` used in controller validation is necessary to accomplish this.

**Comment by mkArtakMSFT** [comment]
That seems reasonable. Would you be willing to send us a PR for this?

**Comment by bordecal** [comment]
Sure.  Is there anything I should do to indicate that I'm working on it (to avoid having someone else pick it up in parallel)?

**Comment by bordecal** [comment]
@mkArtakMSFT : Is there anything I need to do to request review of the PR, or will that happen automatically?

**Comment by mkArtakMSFT** [comment]
Thanks for your contribution, @bordecal!
