### ISSUE TITLE
[Blazor 0.9.0] How to switch between ASP.NET Core Razor Components and client-side Blazor on 0.9.0?

### ISSUE THREAD

**Issue by ctrl-alt-d** [aspnet/AspNetCore#8523]
I have found instructions to switch between ASP.NET Core Razor Components and client-side Blazor for 0.8.0 at [Server-side Blazor is now ASP.NET Core Razor Components in .NET Core 3.0](https://devblogs.microsoft.com/aspnet/blazor-0-8-0-experimental-release-now-available/)

I miss this information on ["Upgrade to Blazor 0.9.0"](https://devblogs.microsoft.com/aspnet/blazor-0-9-0-experimental-release-now-available/) blog post.

I tried 0.8.0 instructions, unsuccessfully, on 0.9.0: https://github.com/aspnet/AspNetCore/issues/8440

**Question is: How to switch between ASP.NET Core Razor Components and client-side Blazor on 0.9.0?**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ctrl-alt-d.
@danroth27 did the way to change between Blazor and Razor Components change?

**Comment by danroth27** [comment]
Unfortunately it looks like there isn't really a good way to do this with Blazor 0.9.0 and Razor Components in .NET Core 3.0 Preview 3 :-(. We need to get this fixed for Preview 4. I believe https://github.com/aspnet/AspNetCore/issues/8852 should make this scenario reasonable again. @stevesandersonms Can you confirm?

**Comment by SteveSandersonMS** [comment]
As long as you're not doing prerendering, I don't think there's anything stopping you from switching like that. Our E2E tests already do switch between server and client execution: https://github.com/aspnet/AspNetCore/blob/master/src/Components/test/testassets/TestServer/Startup.cs.

I recognize that people still want a simpler sample of how to do this, so I'll leave the issue open until we have one.

**Comment by mkArtakMSFT** [comment]
Since the original question is about Blazor 0.9 we've closed this, as we have some other issues to track improving this experience for the upcoming releases.

**Comment by vchirikov** [comment]
Add link to this issues please, I will subscribe

**Comment by vchirikov** [comment]
So new preview is coming out:
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/
But didn't have any news about this issue.
@danroth27 @mkArtakMSFT any news?
