### ISSUE TITLE
ValuesController in the API template doesn't use modern features or idioms

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCore#8534]
`ValuesController` doesn't have the API Controller conventions configured or the analyzers, and the action methods have parameters that require attributes. We should consider changing it to an example that is more idiomatic.

@glennc

**Comment by mkArtakMSFT** [comment]
@glennc, waiting for you to define how this should look. Should we still have `ValuesController` as this was something we've talked about and never locked down on this.

**Comment by mkArtakMSFT** [comment]
This will be handled as part of https://github.com/aspnet/AspNetCore/issues/10333, given that we're renaming to WeatherController.
