### ISSUE TITLE
cannot get data from response when using HttpClient.GetJsonAsync in AspNetCore MVC

### ISSUE THREAD

**Issue by qwertylb** [aspnet/AspNetCore#8540]
When using HttpClient.GetJsonAsync, docList can't get Json data with Object List&lt;Doc&gt;. I set breakpoint in LogsController.cs, it's obvious that ActionResult already has Value. But docList is null. The following code snippet is a part of the webapplication.
How to get data and use it?
Thank you for your support...

QueryLogs.cshtml

<pre>
&lt;TextEdit Placeholder="PlayerGuid" bind-text="@account" /&gt;

&lt;SimpleButton Clicked="@(async () =&gt; await GetLogs(account))" Class="form-control" Color="Color.Primary"&gt;
    Query
&lt;/SimpleButton&gt;

&lt;table&gt;
    @if (docList == null)
    { &lt;p&gt;there are no doc to display&lt;/p&gt;}
    else
    {
    @foreach (var doc in docList)
    {
        &lt;tbody&gt;
            &lt;tr&gt;
                &lt;td&gt;@doc.account&lt;/td&gt;
                &lt;td&gt;@doc.money_after&lt;/td&gt;
                &lt;td&gt;@doc.money_before&lt;/td&gt;
                &lt;td&gt;@doc.operator_type&lt;/td&gt;
                &lt;td&gt;@doc.item_info&lt;/td&gt;
                &lt;td&gt;@doc.vipLevel&lt;/td&gt;
                &lt;td&gt;@doc.quest_id&lt;/td&gt;
                &lt;td&gt;@doc.weapon_id&lt;/td&gt;
                &lt;td&gt;@doc.zone_id&lt;/td&gt;
                &lt;td&gt;@doc.role_id&lt;/td&gt;
            &lt;/tr&gt;
        &lt;/tbody&gt;}}

&lt;/table&gt;

@functions{

    List&lt;Doc&gt; docList = new List&lt;Doc&gt;();
    string account;
    string document;

    public async Task GetLogs(string acc)
    {
        docList = await Http.GetJsonAsync&lt;List&lt;Doc&gt;&gt;("api/value/" + acc);
    }
}
</pre>
LogsController.cs

<pre>
[HttpGet("{param}")]
[EnableCors("CorsPolicy")]
private readonly ElasticClient _client;
public async Task&lt;ActionResult&lt;List&lt;Doc&gt;&gt;&gt; Search(string param)
{
    return  _client.Search&lt;Doc&gt;(s =&gt; s
        .From(0)
        .Size(10)
        .Query(q =&gt; q.Match(m =&gt; m.Field(f =&gt; f.account).Query(param)))).Documents.ToList&lt;Doc&gt;();     
}
</pre>

**Comment by qwertylb** [comment]
[HttpGet("{param}")]
        [EnableCors("CorsPolicy")]
        public async Task&lt;ActionResult&lt;List&lt;Doc&gt;&gt;&gt; Search(string param)
        {
            return  _client.Search&lt;Doc&gt;(s =&gt; s
                .From(0)
                .Size(10)
                .Query(q =&gt; q.Match(m =&gt; m.Field(f =&gt; f.account).Query(param)))).Documents.ToList&lt;Doc&gt;();     
        }

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @qwertylb.
It's not clear from your example what you're experiencing. Are you getting an error? What is it?

**Comment by qwertylb** [comment]
There is a project that use ASP.NET MVC and elasticsearch to query logs and represent it. In QueryLogs.cshtml, when i input account and click Query button, it will execute GetLogs method and it can get return value of account from LogsController's method Search. But the return value can not pass to the QueryLogs.cshtml by Http.GetJsonAsync&lt;List&lt;Doc&gt;&gt;("api/value/" + acc).

**Comment by qwertylb** [comment]
> Thanks for contacting us, @qwertylb.
> It's not clear from your example what you're experiencing. Are you getting an error? What is it?

There is a project that use ASP.NET MVC and elasticsearch to query logs and represent it. In QueryLogs.cshtml, when i input account and click Query button, it will execute GetLogs method and it can get return value of account from LogsController's method Search. But the return value can not pass to the QueryLogs.cshtml by Http.GetJsonAsync<List<Doc>>("api/value/" + acc). docList is null.

**Comment by mkArtakMSFT** [comment]
@qwertylb, the result of the query in the controller action you're referring to is not null, because it's represented by an asynchornousely executing task. So that's the `Task` object you see. Most probably the task's result ends up being `null` when evaluated, hence you get null when you call it.
