### ISSUE TITLE
Default files does not consider Accept header

### ISSUE THREAD

**Issue by jchannon** [aspnet/AspNetCore#8550]
### Describe the bug
If you have an API that returns json from a `/` path but you also have a index.html in `wwwroot` folder and make a request with `Accept:application/json` you will get back HTML.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. 
```
           app.UseDefaultFiles();
           app.UseStaticFiles();

            app.UseCarter() OR app.UseMvc() OR app.UseRouting()
```
3. `curl -H "Accept:application/json" localhost:5000`
4. See index.html response from wwwroot folder

### Expected behavior
To see the json response

**Comment by rynowak** [comment]
Is there a specific problem you're trying to solve by using default files? This is the documented behaviour.

**Comment by jchannon** [comment]
If I have a browser go to foo.com I'd want the HTML returned, if I curl with application/json i'd expect to see the json.  It's conneg but without invoking anything server side for view rendering i guess

**Comment by Eilon** [comment]
The static files middleware is intended to be quite basic. This sounds like a job for a higher-level system, such as MVC, where con-neg exists, and you can also return static files based on some logic.

**Comment by jchannon** [comment]
I went with this approach

app.MapWhen(context => context.Request.Path == "/" &&
!context.Request.Headers["Accept"].ToString().Contains("json"),
builder =>
{
    builder.UseDefaultFiles();
    builder.UseStaticFiles();
});

app.UseStaticFiles();

app.UseCarter();

**Comment by jchannon** [comment]
I went with this approach

```
app.MapWhen(context => context.Request.Path == "/" && !context.Request.Headers["Accept"].ToString().Contains("json"),
  builder =>
  {
      builder.UseDefaultFiles();
      builder.UseStaticFiles();
  });

app.UseStaticFiles();

app.UseCarter();
```

**Comment by anurse** [comment]
Sounds like this is resolved. Static files isn't really designed to do content negotiation like this.
