### ISSUE TITLE
How to share assembly memory between copies of the same App ?

### ISSUE THREAD

**Issue by SolidSoft-Lda** [aspnet/AspNetCore#8552]
How to implement a ASP.NET Core shared memory strategy for .NET Core assemblies like this:
https://visualstudiomagazine.com/articles/2017/11/29/improve-startup-time.aspx ?

**Comment by Eilon** [comment]
Hi, this feature is not supported in ASP.NET Core. It is specific to .NET Framework apps running ASP.NET 4.x (System.Web).

**Comment by SolidSoft-Lda** [comment]
I understand that the aspnet_intern is .NET Framework specific tool but there is any other similar option to move the assemblies to an external folder and share between copies of the same ASP.NET Core application to save memory ?

**Comment by Eilon** [comment]
@SolidSoft-Lda there is no such feature at this time and no plans for one.
