### ISSUE TITLE
CORS Middleware should set Content-Length = 0 when returning a 204 response

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/AspNetCore#8555]
https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/CORS/src/Infrastructure/CorsMiddleware.cs#L189

Can we please allow this to be set either in AddCors or UserCors?

I need to send a 200 because IIS is seeing the 204, it doesn't see a `Content-Length` header so it tries to chunk the response and that explodes our F5 load balancer because 204 with `Transfer-Encoding: chunked` does not conform to HTTP spec.

**Comment by pranavkm** [comment]
@VictorioBerra would it suffice if the middleware set `Content-Length=0` as part of the response?

@jkotalik would the changes to use Pipelines now send a `Content-Length` header when it wasn't explicitly specified?

**Comment by VictorioBerra** [comment]
Yes that would be a good idea.

**Comment by pranavkm** [comment]
👍 that seems do-able. For 2.x, you could consider setting the `Content-Length` in a middleware when you see a 204 response code and the header is missing.

**Comment by VictorioBerra** [comment]
How can I do this before cors middleware exits and returns the response? I believe it does not call _next when it sees a preflight and sets the 204.

**Comment by amityagov** [comment]
@VictorioBerra Hi, you can subscribe to `Response.OnStarting` event with action which wiil check response.

```
public async Task Invoke(HttpContext context)
{
    context.Response.OnStarting(() =>
    {
        context.Response.Headers["X-Trace-Id"] = context.TraceIdentifier;
        return Task.CompletedTask;
    });

    await _next(context);
}
```

I think this should work.

**Comment by VictorioBerra** [comment]
I didn't know about those response events. Thanks!!!

**Comment by VictorioBerra** [comment]
In case other people come across this, another option:

```csharp
﻿using ...

namespace YourApp.API.Services
{
    public class IISCorsService : CorsService
    {
        public IISCorsService(IOptions<CorsOptions> options) : base(options)
        {
        }

        public IISCorsService(IOptions<CorsOptions> options, ILoggerFactory loggerFactory) : base(options, loggerFactory)
        {
        }

        public override void EvaluatePreflightRequest(HttpContext context, CorsPolicy policy, CorsResult result)
        {
            base.EvaluatePreflightRequest(context, policy, result);

            if (result.IsPreflightRequest)
            {
                context.Response.Headers.Add("Content-Length", "0");
            }

        }

    }
}
```

**Comment by jkotalik** [comment]
@VictorioBerra for my own knowledge, are you seeing this behavior with 204s using ANCM/IIS In-process or Kestrel behind ANCM? We fixed a similar bug related to in-process, so I want to see if this was related.

**Comment by VictorioBerra** [comment]
@jkotalik We are hosting our API on IIS using `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` and targetting netcoreapp2.2.

When did you fix this? Is there a way for me to test the fix today? We might be a few minor versions behind on our ANCM/Hosting Bundle CLR.

**Comment by jkotalik** [comment]
@VictorioBerra can you try removing that line for AspNetCoreHostingModel and try seeing if this issue reproduces without setting the content length? This issue should have been fixed in 2.2.1 in ASP.NET Core, check what version you are currently on. If you are on 2.2.1 or later and the issue doesn't reproduce when removing AspNetCoreHostingModel, we may have an issue.

**Comment by VictorioBerra** [comment]
Looks like we have 2.2.0 on our dev server. Updating and will test momentarily.

**Comment by VictorioBerra** [comment]
Looks like updating maybe have solved the problem.

**Comment by jkotalik** [comment]
Awesome, I’m going to close this issue then.
