### ISSUE TITLE
Razor: VS autocompletion goes wrong when typing

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#8556]
This affects both traditional Pages and Razor Components.

Repro:

 * In a `.cshtml`/`.razor` file, type `@Microsoft.A`
 * Notice that the intellisense is prompting you to complete `@Microsoft.AspNetCore`
 * Press tab *without first using the cursors to navigate through the completion popup*

Expected:

 * Completes as `@Microsoft.AspNetCore`

Actual:

 * Completes as `@Microsoft.<a href="#">content</a>` 😱 

I only started noticing this since VS2019 Preview 4.

It affects *many, many* cases where you're trying to code anything in a Razor file. C# intellisense is hardly usable in Razor right now!

**Comment by DNF-SaS** [comment]
BIG upvote for this one!

**Comment by rynowak** [comment]
This has already been reported to the web editor team and will be fixed in an upcoming VS update.
