### ISSUE TITLE
.Net Core Cookie Authentication - User Getting Wrong Claims

### ISSUE THREAD

**Issue by siblight** [aspnet/AspNetCore#8559]
I have a very strange issue with a .net core mvc site, which is hosted in IIS.

When a user logs in with this code:

```
    var claimsIdentity = new ClaimsIdentity(
                         new List<Claim>() { new Claim(ClaimTypes.Role, "Admin", null), new Claim("Name", userName, null) }, CookieAuthenticationDefaults.AuthenticationScheme);
    
                        var authProperties = new AuthenticationProperties
                        {
                            AllowRefresh = true,
                            ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(30),
                            IsPersistent = false,
                        };
    
                        HttpContext.SignInAsync(
                            CookieAuthenticationDefaults.AuthenticationScheme,
                            new ClaimsPrincipal(claimsIdentity),
                            authProperties);
```

The first user logs in with their name being displayed.  However, when another user logs on they get the first users name displayed rather than their own.

I have tried experimenting with the cookie options all with no success but this is my current configuration:

```
 services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
             .AddCookie(options => {
                 options.Cookie.HttpOnly = false;
                 options.LoginPath = "/Account/Login";
                 options.LogoutPath = "/Account/LogOff";
                 options.Cookie.IsEssential = true;
                 options.Cookie.MaxAge = new TimeSpan(0, 2, 0, 0, 0);
                 options.Cookie.SameSite = SameSiteMode.Strict;
                 options.Cookie.Name = "SITECODEHERE";
             });
```

Any help would be appreciated, as I am sure that I am making a silly mistake somewhere.

**Comment by blowdart** [comment]
Do you have any sort of caching enabled?

Is the second login on a separate machine or browser?

**Comment by siblight** [comment]
The logins are on separate machines and browsers.

The users are presented with the login page (as they are initially not logged in) but when the login is completed they see a different users claims.

As far as I am aware there is no caching enabled, but I have got my network admins investigating our firewall to check for caching there.

**Comment by blowdart** [comment]
If you can get us fiddler traces of two such sessions that would help. If this is from your corporate network to the outside then there is likely a proxy in the way which may be caching.

You should also check for uses of [ResponseCache] in your own code and look for the presence of Cache-Control headers in the response from your app.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by siblight** [comment]
My IT Dept. was able to trace the issue to one of our firewall servers caching traffic for my web server.  
After disabling this the problem I was having was resolved.
Thank you for your help.
