### ISSUE TITLE
Selenium process is not always closed

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#8560]
As we found [here](https://github.com/aspnet/AspNetCore-Internal/issues/1988) Selenium is not always being closed when the tests that use it finish. This can lead to file locking problem on our agents and local machines.

**Comment by javiercn** [comment]
This should be fixed now.

**Comment by ryanbrandenburg** [comment]
What was done to resolve it? Reading the issue content I realize I didn't make it clear that this issue was to track solving the Selenium process staying open in the general case (TC, local dev builds, AzDO, all of it). To my knowledge the only fixes to this area so far are only applicable to AzDO.

**Comment by javiercn** [comment]
Azure pipelines. Selenium tests don't run on aspnetci nor helix.
On local builds it gets killed after running the tests and if you kill the test process you can always kill it with stop-process yourself. We also start a sentinel process to kill them eventually, but takes 1h 30m to run. We can't do better on local builds, but it doesn't matter

**Comment by ryanbrandenburg** [comment]
I knew we weren't doing it in helix but it's news to me that we're not running it on aspnetci. Given that and the sentinel process I agree this is good now.
