### ISSUE TITLE
Remove FileKind from ParserOptions

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#8580]
Razor adds several hacks to configure its parser and code generation options to identify the current document being parsed. This is unneeded because that information is available on the CodeDocument. Not only is it unneeded but it's not fully glued together today; primarily because in several places we don't know the current document when attempting to create the parser options.

**Comment by ajaybhargavb** [comment]
cc @mkArtakMSFT @rynowak to triage and assign it to a specific milestone.

**Comment by rynowak** [comment]
never?

**Comment by NTaylorMullen** [comment]
> never?

We should talk offline. Don't want to ship public API for something that we don't feel 100% about, sooo we'll need to do the work to remove it.

**Comment by rynowak** [comment]
Lets talk about this then. IMO the whole thing needs to be redone - our assumptions were broken as soon as we added components. I don't want to spend a bunch of time polishing what's there.

**Comment by mkArtakMSFT** [comment]
Closing as there doesn't seem to be much value here.
