### ISSUE TITLE
Not rendering HTML for Chart Reports in LocalReport

### ISSUE THREAD

**Issue by chinturathod** [aspnet/AspNetCore#8585]
Hi,

I have try to export report in Html using below code but it is not rendering properly.

.rdl file contains chart

I have attached screen shot of Html

Highly appreciate if you can help on us to resolve this issue.

thanks

PlatForm: ASP.NET Core

```c#
public string _reportPath = @"..\\RenderReportAPI\\employeeChart.rdl";

string mimtype ="";
int extension = 1;

               LocalReport localReport = new LocalReport(_reportPath);

            _dataSourceName = "DataSet1";
            _dataSourceList = Employee.GetEmployees();                                   
            localReport.AddDataSource(_dataSourceName, _dataSourceList);

           

            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
            var result = localReport.Execute(RenderType.Html, extension, null, findString: mimtype);
```

![Chart_html](https://user-images.githubusercontent.com/48618470/54473803-af518300-4802-11e9-828c-91ccb5891280.PNG)

**Comment by Eilon** [comment]
Hi, this looks like a component that isn't part of ASP.NET Core. Please contact the author of the Chart component to report this issue.

**Comment by chinturathod** [comment]
> Hi, this looks like a component that isn't part of ASP.NET Core. Please contact the author of the Chart component to report this issue.

hi,
it is a ASP.NET Core component ,
i used AspNetCore.Reporting nuget package
Any help will be very great full
thanks

**Comment by Eilon** [comment]
It's not from Microsoft. You can contact the owners of the package by visiting this site: https://www.nuget.org/packages/AspNetCore.Reporting/
