### ISSUE TITLE
Using AddAzureSignalR with Razor Conponents 3.0.0 preview 3

### ISSUE THREAD

**Issue by ADefWebserver** [aspnet/AspNetCore#8590]
### Describe the bug
Click events don't work

### To Reproduce
1. Create new Razor Components project
2, Add Microsoft.Azure.SignalR NuGet package
3. In startup.cs, change 

`services.AddRazorComponents()`

to:

```
            services.AddRazorComponents()
                .AddSignalRCore()
                .AddAzureSignalR(
                "{{ Azure SignaleR connection string}}");
```
4. In startup.cs, in the "configure" method, add:

```
            app.UseAzureSignalR(route =>
            {
                route.MapHub<ComponentHub>(ComponentHub.DefaultPath);
            });
```

5. Run the application
6. The Fetch Data page will work, but clicking on the Counter, on the Counter page will not

### Expected behavior
Clicking on the counter button will work

### Additional context
When looking in Azure, there is traffic when the Fetch Data page is viewed

**Comment by davidfowl** [comment]
Yes this is being worked on for preview4. It's currently broken in preview3.

**Comment by asterinex** [comment]
> 
> 
> Yes this is being worked on for preview4. It's currently broken in preview3.

Is there a temporary fix or workaround ?

**Comment by mkArtakMSFT** [comment]
@davidfowl, @anurse is there a separate issue you track the fix with? Should this one be duped?

**Comment by mkArtakMSFT** [comment]
https://github.com/aspnet/AspNetCore/issues/8679

**Comment by anurse** [comment]
I don't think this is the same issue as #8679. Azure SignalR has a very different connection pattern.

**Comment by anurse** [comment]
@mkArtakMSFT We need someone from Razor Components to drive an investigation here, since we need client-side logs from SignalR. Can you look in to that?

**Comment by davidfowl** [comment]
This is already being worked on you can assign it to me

**Comment by anurse** [comment]
![Riiiiiight...](http://www.reactiongifs.com/wp-content/uploads/2013/05/dr-evil-right.gif)

**Comment by davidfowl** [comment]
https://github.com/davidfowl/AzureSignalRLightupPrototype

![B71BE455-9FA8-47A6-8789-FBE33072A3FB](https://user-images.githubusercontent.com/95136/54975753-3954c680-4f3c-11e9-9a6e-4ed023148f7d.gif)

**Comment by davidfowl** [comment]
The work here is mostly done on the SignalR side of things. The Azure SignalR SDK changes will be going in soon. It'll require some code changes as a result though.

**Comment by davidfowl** [comment]
@anurse moving this back into preview4 as we can't ship another preview that doesn't work with the service.

**Comment by anurse** [comment]
@davidfowl sync up with me on this ASAP then. This is super vague and I need to know what we actually need to get done here in order to actually be able to deliver it :).

**Comment by davidfowl** [comment]
The work is done on outside and is being integrated into the SDK, I still want to track it here though

**Comment by anurse** [comment]
Ok. Still want to sync, but that helps me understand the context and timing. Is there a doc or spec describing the change? Mostly, I'm just trying to figure out what the work **is** since that doesn't appear to have been described here, and if you want to use this to track that work it would certainly be nice to know what it is that actually needs to be done (even if you're just doing it) ;)

**Comment by BrennanConroy** [comment]
https://github.com/Azure/azure-signalr/pull/470 FYI

**Comment by davidfowl** [comment]
The runtime work here is done. I'll open bugs if there's remaining work to do in later previews.
