### ISSUE TITLE
Reproducible Razor LSP InvalidOperationException on generating CSS autocompletions in MVC

### ISSUE THREAD

**Issue by mqudsi** [aspnet/AspNetCore#8591]
### Describe the bug
I have a fully reproducible exception that brings down all of Visual Studio when the Razor language client runs into an InvalidOperationException when attempting to generate completions after opening a brace (e.g. `{`) for a new CSS class definition in a `<style>` tag in a MVC .cshtml view.

### To Reproduce
1. Using this version of ASP.NET Core 2.2 (latest SDK) and Visual Studio 2019 16.0.0 Preview 4.2
2. In a MVC view, in a named section defined in the view and rendered in the parent layout, create a `<style>` tag (open and close) and within it reference a HTML class used in the view, e.g. with a `<div class="discountInfo">...</div>` in the main body of the page, type in `.discountInfo {` in the `style` node.

e.g. my document starts like this:

```
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@model PlaceOrderModel
@using EasyRE.Models
@using System.Text.RegularExpressions;
@using NeoSmart.Payments

@{
    ViewBag.Title = "Place an Order | Easy Recovery Essentials";
    @*static*@ var ProductNameRegex = new Regex("Recovery Disc.*", RegexOptions.Compiled | RegexOptions.IgnoreCase);
}

@section head {
    <script type="text/javascript">
        // ....
    </script>
    <environment include="Development">
        <link rel="stylesheet" type="text/css" href="~/css/validation.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" type="text/css" href="~/css/validation.min.css" />
    </environment>
    <style type="text/css">
        .product-name {
            font-weight: bold;
        }
....

    </style>
}
```

Depending on whether asynchronous completions are enabled or not, the IDE will either immediately hang and then crash or it will crash some ms thereafter in the Razor language completions module.

The error generated as reported in the Event Viewer:

```
Fault bucket 2299082020568643789, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: devenv.exe
P2: 16.0.28711.60
P3: 5c86b603
P4: Microsoft.AspNetCore.Razor.Language
P5: 3.0.19.15504
P6: 9b6dfb8b
P7: 10c6
P8: 75
P9: System.InvalidOperationException
P10: 
```

The exception in the Razor language module:

> An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNetCore.Razor.Language.dll
Additional information: The reference is invalid. The node 'Microsoft.AspNetCore.Razor.Language.Intermediate.DirectiveIntermediateNode' could not be found as a child of 'Microsoft.AspNetCore.Razor.Language.Intermediate.DirectiveIntermediateNode'.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Microsoft.AspNetCore.Razor.Language.Intermediate.IntermediateNodeReference.InsertAfter(Microsoft.AspNetCore.Razor.Language.Intermediate.IntermediateNode)
   at Microsoft.AspNetCore.Razor.Language.Extensions.SectionDirectivePass.ExecuteCore(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument, Microsoft.AspNetCore.Razor.Language.Intermediate.DocumentIntermediateNode)
   at Microsoft.AspNetCore.Razor.Language.IntermediateNodePassBase.Execute(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument, Microsoft.AspNetCore.Razor.Language.Intermediate.DocumentIntermediateNode)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorDirectiveClassifierPhase.ExecuteCore(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.ProcessDesignTime(Microsoft.AspNetCore.Razor.Language.RazorProjectItem)
   at Microsoft.VisualStudio.Editor.Razor.BackgroundParser+BackgroundThread.WorkerLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

The exception in devenv.exe that brings down the actual IDE as it fails to handle the exception thrown by the razor client:

```
Faulting application name: devenv.exe, version: 16.0.28711.60, time stamp: 0x5c86b603
Faulting module name: KERNELBASE.dll, version: 10.0.17763.348, time stamp: 0x53015794
Exception code: 0xe0434352
Fault offset: 0x0011c632
Faulting process id: 0x82b8
Faulting application start time: 0x01d4db5daf72ae00
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\devenv.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: bb214052-f940-4bfc-af1f-b574e937f043
Faulting package full name: 
Faulting package-relative application ID: 
```

Some potentially relevant info:

![image](https://user-images.githubusercontent.com/606923/54479069-0a757c80-47e7-11e9-9d1a-ee5c1f59fefb.png)

I'm not able to debug it directly as basically everything has been optimized away, but I suspect that when the following code returns null (due to the null coalescing)

https://github.com/aspnet/AspNetCore-Tooling/blob/f7e10ccacbe0d2d7b897dff7b27fcd58544445c4/src/Razor/src/Microsoft.AspNetCore.Razor.Language/Extensions/SectionDirectivePass.cs#L22

it should bail before reaching 

https://github.com/aspnet/AspNetCore-Tooling/blob/f7e10ccacbe0d2d7b897dff7b27fcd58544445c4/src/Razor/src/Microsoft.AspNetCore.Razor.Language/Extensions/SectionDirectivePass.cs#L45

but I would have to build my own debug copy of Microsoft.AspNetCore.Razor.Language to be sure.

----

More importantly, this is not the first time or the only case that I have had Visual Studio completely crash on me due to an `InvalidOperationException` in `Microsoft.AspNetCore.Razor.Language.dll`. Please consider this bug report to also encompass the issue that devenv.exe is not catching the exception when generating intellisense completions, i.e. addressing this particular crash in Microsoft.AspNetCore.Razor.Language.dll is noble and worthy but it is perhaps more important to make sure that Visual Studio is resilient to such exceptions, which are bound to happen with some (in)frequency even in the most robust codebases. Ideally, this failure to generate intellisense completions should not bring down the entire IDE, and hopefully would not even impact future intellisense generation from the same language/module/service.

**Comment by ajaybhargavb** [comment]
@mqudsi, thanks for the nice detailed report 👍 . I couldn't repro this crash from just what you included above but I suspect the crash you are seeing is because we had a bug in how we handle nested sections. Simpler repro [here](https://github.com/aspnet/AspNetCore-Tooling/pull/319). This has been fixed and will be part of the next preview servicing update.
I suspect what happens in you case is you probably have another section below the `head` section. Something like this,
```cshtml
@section head {
    <style>
        .myclass{
    </style>
}


@section foo {
    <environment>...</environment>
}
```
So when you start typing the `{` in the style tag, it happens to nest section `foo` under `head` causing the crash.

Please re-open if this is not the case or if you see it crash even with just a single section or no section directive at all.

**Comment by mqudsi** [comment]
Thanks for the reply and information, @ajaybhargavb. I do indeed have `@section`s below this one in the document, additionally the template itself I'm using has a parent template so it contains things like `@section head { Html.RenderSection("head") }`.

Any word on making Visual Studio itself resilient to module crashes?
