### ISSUE TITLE
Getting Duplicate Requests on server from browser ASP.NET Core 3 Preview

### ISSUE THREAD

**Issue by iamjassiesandhu** [aspnet/AspNetCore#8595]
### Describe the bug
Hello, i am getting two requests for every request made to server from browser 
--> One Request Comes as HTTP/1.1 
--> Other Request comes as HTTP/2.0 

1. Using 3 Preview version of ASP.NET Core 
2. Only in case of Dynamic request. Static content loads via HTTP /1.1 only
3.  Using Windows server 2016 (AWS) and IIS 10

**Comment by Eilon** [comment]
@iamjassiesandhu can you show a network trace of how this is happening? WHich browser are you using?

**Comment by Eilon** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
How are you viewing these duplicate requests? Can you share the trace?

**Comment by iamjassiesandhu** [comment]
Thanks everyone for your reply.
@Tratcher
I was able to view Duplicate requests by using ILogger logging to file.

I am able to resolve this issue, by changing settings from IIS **.NET CLR Version to  No managed code**

Its currently working fine
