### ISSUE TITLE
Authentication with spa & identity server template

### ISSUE THREAD

**Issue by guyng** [aspnet/AspNetCore#8598]
### Describe the bug
Few hours after registering for the first time using the new SPA(angular) auth template
it will not fetch data anymore when navigating to the fetch-data page.
To clarify, after you sign up and log in it will fetch data fine. BUT, if you try to fetch the data with the same user you've registered **few hours later it will not work.** 

The problem may be with refresh tokens not configured, do you mind to explain how to set them up with this new template? because this is very confusing.

### To Reproduce

1. Using asp.net core 3 preview 3 SPA(angular) & Auth(identity server) template
2. register, login and fetch data, it should work fine.
3. try login and open fetch data page again few hours later
4. you should get 401 not authorized response with the folloing info log msg:
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: '03/14/2019 16:00:15', Current time: '03/17/2019 09:23:25'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)

### Expected behavior
Fetch-data should work even at later period.

### Screenshots
http://prntscr.com/myzn0f

**Comment by guyng** [comment]
Any news? @blowdart  @Eilon

**Comment by blowdart** [comment]
@javiercn is refresh not working? Or does it need to be done manually?

**Comment by javiercn** [comment]
@guyng thanks for contacting us.

Refresh happens automatically using a hidden iframe. That said there are many situations in which this can fail. As a general rule, you should account for 401 responses in your app and handle them appropriately.

@blowdart As far as I know we configure it correctly on the client.
https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/ClientApp/src/api-authorization/authorize.service.ts#L310

**Comment by javiercn** [comment]
For reference, you should always account for manual refresh in your app. Auto refresh is only an optimization. As tokens can be revoked at any time.

**Comment by guyng** [comment]
@javiercn  Thanks for your reply. 
As i'v asked above, can you post an example of handling authorization failure by manual token refresh?
I searched all over the internet for the past few days and i couldn't find a single clear guide, there is a serious lack of documentation regarding this issue.
In addition, because identity server startup configuration has changed(for the good), less boiler plate code and more abstraction it's hard to tell what exactly need to be configured to manually acquire new token.

Looking forward to hear a more elaborated answer.

**Comment by javiercn** [comment]
On your component, when you issue the http request you need to handle the 401 response by:
1. Import the authorize service
2. Call sign-in
3. Check the result.
    3.1. If its a successful result getAccessToken on authorizeService already will contain a refreshed accessToken. You can retry the request and the new access token should be used (or you might need to add it to the request manually, i'm not completely sure).
    3.2. If its a redirect then you need to preserve any state you want and redirect to the login component passing the returnUrl (your current url) in the query string as shown in the third link.

https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/ClientApp/src/api-authorization/authorize.service.ts#L81

https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/ClientApp/src/api-authorization/authorize.service.ts#L67

https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/Angular-CSharp/ClientApp/src/api-authorization/authorize.guard.ts#L23

**Comment by guyng** [comment]
Works great, thanks
