### ISSUE TITLE
BlazorHosted.Client dll should be able to run server-side or client-side from same server.

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/AspNetCore#8599]
### Is your feature request related to a problem? Please describe.
#8584 

### Describe the solution you'd like
I would like it to be an objective of the team to allow for the execution side of the dll to be configurable by the JavaScript in the index.html at run time.  A single server-side version of the application should be able to serve both RazorComponents(server-side) or Blazor(client-side) clients. 

Any dll that is capable of running client side should be able to run server-side.
In 0.8.0 we did this with UseRazorComponents<TStartup>
in 0.9.0 we no longer seem to support a Client side Startup class. See #8584

### Describe alternatives you've considered
Alternatives I have been trying are to extract the code from the old UseRazorComponents, but given so many internal classes and changes this is proving more difficult.  I don't mind updating each iteration but would like this to be an objective and if broken be considered a bug.  And some sort of test case written to validate.

### Additional context
I had "Dynamic dual mode" working previously to start server-side then next session would run client-side, see blog post here: https://thefreezeteam.com/razor-components-dynamic-dual-mode/

Example running in 0.8.0 located here: https://blazor-state.azurewebsites.net/

In the future we could have a client-side event trigger that the application is loaded and SignalR could transition the server-side state to the client and then continue running client-side.
This would allow for quicker page loads on first visit and also let the server scale better as users transition to client side.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @StevenTCramer.
This is not something we plan to provide support for in the near future.

**Comment by StevenTCramer** [comment]
@mkArtakMSFT  I found this #6882 after I posted this issue where is sounds like @danroth27  is asking for similar if not the same thing I am asking for.   Would be nice to be able to switch execution location from server to client easily.
