### ISSUE TITLE
Cannot run basic ASP.NET Core webapp on macOS due to invalid dev certs

### ISSUE THREAD

**Issue by TAGC** [aspnet/AspNetCore#8608]
### Describe the bug

I'm trying to set up a basic ASP.NET Web API project (based on the Todo sample app) to brush up C#/ASP.NET Core. However, when I try to debug it in VS Code I get this error:

```
Unhandled Exception: System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
```

Running the recommended command says that a valid HTTPS certificate is already installed. I'm using v2.2.103 of the .NET Core SDK on macOS 10.14.3.

I can't find any reference to what the certificate is called to see whether it actually exists in the keystore.

### To Reproduce
1. Open a terminal and run `dotnet new webapi -o TodoApi` followed by `code -r TodoApi` 
2. Launch a debug session (using Ctrl+F5 or equivalent).

### Expected behavior

The web application should launch without issue.

### Actual behavior

The web application fails to launch with the error given above. Running `dotnet dev-certs https --clean` doesn't have any apparent effect. I also see the following confusing output:

```
✘  ~/Documents/VSCode/TodoApp  dotnet dev-certs https --check --verbose
No valid certificate found.
✘  ~/Documents/VSCode/TodoApp  dotnet dev-certs https --export-path --verbose
A valid HTTPS certificate is already present.
```

**Comment by Eilon** [comment]
cc @javiercn

**Comment by javiercn** [comment]
@TAGC Thanks for contacting us.

Can you open keychain on your Mac and see if you can find a localhost certificate in the system keychain?

**Comment by TAGC** [comment]
@javiercn Sure thing, I have one yeah. It says:

> Self-signed root certificate
> Expires: Saturday, 27 July 2019 at 16:12:11 British Summer Time
> This certificate is marked as trusted for all users

It's in the "System" keychain.

**Comment by javiercn** [comment]
Hmm, does it contain an extension with the following OID? `1.3.6.1.4.1.311.84.1.1`. If so, does that certificate contain a + symbol and does it contain an imported private key?

You should be able to remove the certificate from the key chain and run the tool again, and that should fix your problem. If that is not the case, let me know.

Best regards,
Javier Calvarro Nelson.

**Comment by TAGC** [comment]
The certificate did list that string within the "Extension" field. I found no reference to a + symbol/imported private key but I tried deleting the certificate anyway.

I ran these commands:

```
 ✘  ~/Documents/VSCode/TodoApp  dotnet dev-certs https --check --verbose
No valid certificate found.
 ✘  ~/Documents/VSCode/TodoApp  dotnet dev-certs https --export-path --verbose
The HTTPS developer certificate was generated successfully.
 ~/Documents/VSCode/TodoApp  dotnet dev-certs https --trust
Trusting the HTTPS development certificate was requested. If the certificate is not already trusted we will run the following command:
'sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <<certificate>>'
This command might prompt you for your password to install the certificate on the system keychain.
Password:
A valid HTTPS certificate is already present.
```

My web app now launches successfully. Thanks for the help.
