### ISSUE TITLE
Onchange event not firing when a bind is used

### ISSUE THREAD

**Issue by TerryFogg** [aspnet/AspNetCore#8610]
### Describe the bug
Adding a bind to the input stops the event from 'firing'?

The example shows three input check boxes that are display.
When 'clicking' each, the onchange with the bind does not 'fire'
                                   the onchange without the bind 'fires'
                                   the onclick with bind 'fires'

```
        <RowTemplate>
            <td>
                @* The onchange event does not fire when bind is used for onchange *@
                <input type="checkbox" id="myCheck" bind="context.Selected" onchange="@(e => SelectedLine(e,  context))" />

                @* The following two events fire *@
                <input type="checkbox" id="myCheck" bind="context.Selected" onclick="@(e => SelectedLineClick(e,  context))" />
                <input type="checkbox" id="myCheck" onchange="@(e => SelectedLine(e,  context))" />
            </td>
            <td>@context.TextContents</td>
        </RowTemplate>

```

**Comment by Andrzej-W** [comment]
Binding uses `onchange` events. You can read about this here:
https://docs.microsoft.com/en-us/aspnet/core/razor-components/components?view=aspnetcore-3.0#data-binding
Proposed workaround: bind to property and execute whatever code you need in property setter.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by TerryFogg** [comment]
By using OnInput the event is fired with binding in place.
```
                <RowTemplate>
                    <td>
                        <input type="checkbox" id="myCheck" bind="context.Selected" oninput="@(e => SelectedLineClick(e, context))" />
                    </td>
                    <td>@context.TextContents</td>
                </RowTemplate>
```
