### ISSUE TITLE
Exceptions on events not calling server-side UnhandledException infrastructure

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8611]
Exceptions thrown as a result of an event handler or JS Interop call don't call the server-side UnhandledException handler. Circuits and the sync context have their own *unhandled exception* events, and they don't fire for JS interop.

Is this right? I suppose the idea is that the exception is *handled* by the JS side. One piece of this that we need to be careful about is the fact that our exceptions aren't all going through a single path. For instance we don't have any hooks in place to sanitize these exceptions in production.

**Comment by mkArtakMSFT** [comment]
Goal:
- exceptions from calls from events should be logged on the server
- exceptions from calls from JSInterop should be handled on the client

**Comment by mkArtakMSFT** [comment]
Closing as there has been covered by the work @javiercn has done.
