### ISSUE TITLE
System.Collections.Generic.NodeColor

### ISSUE THREAD

**Issue by qcjxberin** [aspnet/AspNetCore#8614]
When I debug the bug, I found a parameter named System.Collections.Generic.NodeColor color, but I didn't define this NodeColor type. In the net framework, it should be a bool type. I read the open source code and it is online. No relevant instructions were found.

**Comment by qcjxberin** [comment]
`
var ci = nodeType.GetConstructors();
            var i = 1;
            foreach (var row in ci)
            {
                var ps = row.GetParameters();
                foreach (var pi in ps)
                {
                    Console.WriteLine($"参数{i}：" + pi.ParameterType.ToString() + " " + pi.Name + ",");
                }
                i++;
            }
`
测试1:System.Collections.Generic.KeyValuePair`2[[STSdb4.Data.IData, STSdb4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[STSdb4.Data.IData, STSdb4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
参数1：System.Collections.Generic.KeyValuePair`2[STSdb4.Data.IData,STSdb4.Data.IData] item,
参数1：System.Collections.Generic.NodeColor color,

**Comment by Eilon** [comment]
Hi @qcjxberin can you please provide more information on how to reproduce this problem? This problem doesn't seem to be related to ASP.NET Core.

**Comment by qcjxberin** [comment]
`var t = nodeType.GetConstructors().Where(x => x.GetParameters().Length == 2).FirstOrDefault();
            var tp = t.GetParameters()[1].ParameterType;
            var tt = item;
            var ttt = Expression.Constant((byte)0, tp);
            Console.WriteLine($"测试1:{list.Count}");
            var tttt = Expression.New(t, tt, ttt);`

Like the code tp above, it returns NodeCore

`
using System;

namespace System.Collections.Generic
{
	internal enum NodeColor : byte
	{
		Black,
		Red
	}
}
`
How to assign values through the following code.

`
Expression.Constant
`

`
Unhandled Exception: System.AggregateException: One or more errors occurred. (The type initializer for 'STSdb4.General.Extensions.SortedSetHelper`1' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'STSdb4.General.Extensions.SortedSetHelper`1' threw an exception. ---> System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at STSdb4.General.Extensions.SortedSetHelper`1.CreateReplaceMethod() in E:\Code\HaoCoding\HaoCoding\src\HaoCoding.DcStsDb\General\Extensions\SortedSetExtensions.cs:line 151
`

**Comment by Eilon** [comment]
Hi. It doesn't look like this is a question about ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `.net` tag.
