### ISSUE TITLE
razor components should allow custom attributes

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/AspNetCore#8620]
currently, when assigning html attributes that are not explicitly defined on razor components, system will throw exception. e.g. we can not assign an id to EditForm. custom attributes should be passed down to component's root element and preserved  to apply customization.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kennywangjin.
@danroth27 don't we have a separate issue with a similar ask? I tried to find it, but with no luck.

**Comment by danroth27** [comment]
I think this is it: https://github.com/aspnet/AspNetCore/issues/5071

**Comment by danroth27** [comment]
Closing as a dup.
