### ISSUE TITLE
PartialTagHelper should use IHtmlHelper.RenderPartialAsync()

### ISSUE THREAD

**Issue by Remleo** [aspnet/AspNetCore#8622]
The interface `IHtmlHelper` contains specific methods for dealing with partial views
`RenderPartialAsync()` and `PartialAsync()`.

But `PartialTagHelper` (`<partial/>`) doesn't use it for rendering IHtmlContent. It's very frustrating as the only one service should be responsible for partial-views' logic.

In my project I overrided `HtmlHelper` to add some specific logic into `RenderPartialCoreAsync`. And now there are two different logics of rendering partials in my project as there are no possibilities to change any logic inside `PartialTagHelper`. I could only tell other developers in my team to use `Html.PartialAsync(...)` instead of `<partial />`

**Comment by pranavkm** [comment]
`PartialTagHelper` uses features that are not available in `IHtmlHelper` - fallback view and using the `ModelExpression`. There are no plans to add these features to the `IHtmlHelper` equivalent. My recommendation would be to consider creating a custom partial tag helper that replicates what you currently have in your custom `HtmlHelper` instance.
