### ISSUE TITLE
Http.PostJsonAsync<T> Throws Exception 

### ISSUE THREAD

**Issue by shakeelgithub** [aspnet/AspNetCore#8623]
### Explanation
When I pass my object which has the DateTime Property, It throws exception. But it also send data to api and the records are inserted in database.
For all other objects it works fine. But for this object which has a Nullable DateTime property it throws exception. 
> The Model is valid, before passing it to the method. 

When I handle it in try catch block and print the ``` ex.Message ``` to console it prints *WASM: Invalid JSON string.* 

``` C#
try
        {

            
            await Http.PostJsonAsync<Student>("api/student", StudentModel);
            toaster.Success("Student saved successfully", "New Student");
           
            CallBack?.Invoke();

        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
````
*WASM: Invalid JSON string.*

# Screenshots
### Exception when not handled 
![Exception on Console ](https://user-images.githubusercontent.com/43760740/54533796-d3e95e80-49ac-11e9-9a61-c54e441c7db1.PNG)

### Model Classes
 
![code3](https://user-images.githubusercontent.com/43760740/54534308-e6b06300-49ad-11e9-9154-1b9f0bfeb357.PNG)

![code2](https://user-images.githubusercontent.com/43760740/54534119-89b4ad00-49ad-11e9-8fdc-919fa3f1ad0a.PNG)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @shakeelgithub.
In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by shakeelgithub** [comment]
Hello @mkArtakMSFT 
Here is [ The Repository  ](https://github.com/shakeelgithub/Experiencing-SmartBlazor) with all instructions in **readme.md** file.
> The Issue is in [This File at line 149](https://github.com/shakeelgithub/Experiencing-SmartBlazor/blob/master/SmartLearning/SmartLearning.Client/Pages/Components/Student/StudentAdd.cshtml)

**Comment by mkArtakMSFT** [comment]
Thanks @shakeelgithub.
Looks like this is caused by the fact that the format of the data being passed from the server to client is not something client understands. At the moment, the JSON serializer we use in Blazor has no understanding of the `DisplayFormat` attribute, hence it completely ignores the `DataFormatString` you've specified.
As an alternative, you can use JSON.NET on the client.
