### ISSUE TITLE
Why did we go from targeting the netstandard2.0 to netcoreapp3.0 in Microsoft.AspNetCore.Cors.csproj?

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/AspNetCore#8626]
I trying to use the `Microsoft.AspNetCore.Cors.csproj` as a reference for building my own middleware. I noticed between the latest 2.2.3 and the unreleased core 3 there are some large changes to the csproj. Namely, we no longer target the netstandard which I was told for class library development is the best practice.

So should I be targeting the core framework instead? Or do I need to target standard for now and then modify my middleware for core 3?

[Before](https://github.com/aspnet/AspNetCore/blob/v2.2.3/src/Middleware/CORS/src/Microsoft.AspNetCore.Cors.csproj).

[After](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/CORS/src/Microsoft.AspNetCore.Cors.csproj).

**Comment by blowdart** [comment]
there aren't 3.0 packages for a lot of what's in the Microsoft.AspNetCore.App shared framework in 3.0. Your library instead will need a FrameworkReference to Microsoft.AspNetCore.App in the netcoreapp3.0 target. This was [announced a while back now](https://github.com/aspnet/Announcements/issues/325), but doesn't effect the Microsoft.Extensions packages, only  most of Microsoft.AspNetCore.*

**Comment by VictorioBerra** [comment]
So for a basic shared library, I will be using a proj file like this?

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>    
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```

**Comment by VictorioBerra** [comment]
Alright I read that and Nates blog post like 5 times and I think I have better handle.

I guess my question can be simplified now, should I target netcoreapp3 or netstandard and then nuget all the dependencies I need?

**Comment by pranavkm** [comment]
> I guess my question can be simplified now, should I target netcoreapp3 or netstandard and then nuget all the dependencies I need?

If you're targeting the AspNetCore framework, (most things in the Microsoft.AspNetCore.* namespace), you'd need to target `netcoreapp3.0`.

**Comment by VictorioBerra** [comment]
@pranavkm Just curious if I need `ILoggerFactory`, that is from, `Microsoft.Extensions.Logging` which means I need a `<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.2.0" />` to that. And if I am NOT using anything in `Microsoft.AspNetCore.`, I ambetter off targetting `netstandard2` right?

Because Microsoft.Extensions.* is not part of AspNetCore shared framework so the packages are not on my machine and must be pulled down from NuGet.
