### ISSUE TITLE
Huge POST request hangs in UriHelper.UnescapeString

### ISSUE THREAD

**Issue by drauch** [aspnet/AspNetCore#8627]
### Describe the bug
If I HTTP-POST a huge (300K to 1MB, specially crafted) request to my application, the request hangs for several minutes. Depending on the size it even runs in 502 timeouts (starting from 2MB upwards on my local machine).

The request must have a form-data field with upwards of 300 KB which moreover matches the following regular expression: ```%.*§``` multiplied to the necessary size. I.e., ```%§%§%§...``` triggers the behavior.

### To Reproduce
1. Using this version of ASP.NET Core '2.1.7' (MVC 2.1.3)
2. Have a controller with a POST action taking in a model with a string parameter
3. Post a huge request with input that does NOT match the regular expression above => receive an answer within seconds
4. Post a huge request with input that DOES match the regular expression above => wait for multiple minutes / eventually receive 502

If you debug the application and break it during the time the request hangs you will see a thread hanging in ```System.UriHelper.UnescapeString```.

If I use LINQPad and directly pass this string to Uri.UnescapeDataString() it does not hang. So there seems to be some flaw in how the AspNetCore.WebUtilities.FormReader calls Uri.UnescapeDataString().

### StackTrace
`>	System.dll!System.UriHelper.UnescapeString(char* pStr, int start, int end, char[] dest, ref int destPosition, char rsvd1, char rsvd2, char rsvd3, System.UnescapeMode unescapeMode, System.UriParser syntax, bool isQuery)	Unknown
 	System.dll!System.Uri.UnescapeDataString(string stringToUnescape)	Unknown
 	Microsoft.AspNetCore.WebUtilities.dll!Microsoft.AspNetCore.WebUtilities.FormReader.ReadChar(char seperator, int limit, out string word)	Unknown
 	Microsoft.AspNetCore.WebUtilities.dll!Microsoft.AspNetCore.WebUtilities.FormReader.TryReadNextPair()	Unknown
 	Microsoft.AspNetCore.WebUtilities.dll!Microsoft.AspNetCore.WebUtilities.FormReader.ReadNextPairAsyncImpl(System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
`

**Comment by blowdart** [comment]
We're aware of performance issues in this code path (and calling UnescapeDataString has a fix upcoming in 3.0 for this very issue)

As it's possible to limit form post sizes, and file uploads don't come via this parsing route is a 300k payload a typical size for your applications?

**Comment by drauch** [comment]
> UnescapeDataString has a fix upcoming

Do you have a corresponding issue / pull request for me?

>  is a 300k payload a typical size for your applications

No, we're actually trying to protect us from DoS attacks. How to limit post data size to something around 10KB while still being able to POST-upload 1GB files (which actually is the scenario we have in our application).

**Comment by blowdart** [comment]
https://github.com/dotnet/corefx/issues/36050 is the fix in CoreFx.

@jkotalik can you help with the limit tweaking config please?

**Comment by jkotalik** [comment]
You can use the `RequestFormLimits` attribute to limit lengths for values for form and multipart forms. See: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/RequestFormLimitsAttribute.cs.

**Comment by Tratcher** [comment]
Or configure it globally via:
```
services.Configure<FormOptions>(options =>
{
  options.ValueLengthLimit = ...
});
```

**Comment by drauch** [comment]
I'll give it a try on Monday and will report back to you. Thanks for the advice!

**Comment by drauch** [comment]
Setting `ValueLengthLimit` worked, thank you very much. Still, there should be a proper fix for this in an upcoming ASP.NET Core release ;)

**Comment by anurse** [comment]
This has been fixed in corefx for release in .NET Core 3.0 (https://github.com/dotnet/corefx/pull/36056)
