### ISSUE TITLE
Update launchSettings.json to use system.text.json

### ISSUE THREAD

**Issue by wli3** [aspnet/AspNetCore#8629]
The code is in CLI but it is owned by aspnet
https://github.com/dotnet/cli/tree/7d0f5cdd5508d291bac3dd59adda4efaa968e575/src/dotnet/commands/dotnet-run/LaunchSettings

**Comment by muratg** [comment]
cc @Eilon

**Comment by wli3** [comment]
Close this issue. It is tracked in VSTS
