### ISSUE TITLE
[Tooling] Using TagHelpers in void returning methods at design time does not cause an error

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#8630]
### Describe the bug
TagHelpers aren't indicated as an error inside of a void returning method at design time. This is due to how we change rendering at design time vs. runtime.

i.e. no errors:
![image](https://user-images.githubusercontent.com/2008729/54554913-dc24a800-4972-11e9-9ac7-6e7f832ae171.png)

**Comment by NTaylorMullen** [comment]
An interesting case here will be handling things like `~/` which don't "TagHelperify" at design time but do at runtime.

**Comment by NickCraver** [comment]
Is there a chance of `~/` *not* being async in nature overall? It seems...very odd to experience. As a user, I'd just assume replace it with a static somewhere to avoid all the pain it causes downstream today.

**Comment by rynowak** [comment]
I super duper agree and it's under consideration. The perf implications of this being a tag helper are quite large.

**Comment by NTaylorMullen** [comment]
202ccebb0d259585cdcb3c30d34cd93c0d1bde3b

**Comment by NTaylorMullen** [comment]
This does not cover `~/` so filed https://github.com/aspnet/AspNetCore/issues/10734
