### ISSUE TITLE
Ability to initialize keys in the store from existing keys

### ISSUE THREAD

**Issue by iaiken** [aspnet/AspNetCore#8632]
### Problem statement
We have an existing .NET 4.5 dll-based solution that makes use of Enterprise Library 4.2 and DPAPI to store several shared keys to multiple machines in a web farm.  We are now converting a lot of our code over to AspNetCore Web API and are trying to find a route to provides seamless continuity for the switch over to the new Microsoft.AspNetCore.DataProtection mechanism with future plans to use Key Vault, but for now we are stuck with DPAPI local stores due to internal PCI compliance reasons.

The issue we are having is that there doesn't appear to be a means in the DataProtection library or it's extensions to allow us to populate the store with the same keys as we are using in our EL-DPAPI solutions.

### Describe the solution you'd like
We need the ability to populate our new DPAPI stores with existing shared keys so that we can continue to encrypt/decrypt values in parallel whit the old solution until it can be replaced by the new method. IKeyManager.CreateNewKey accepts only an activation date and expiration date and we cannot find any other means to pass in a value.

### Describe alternatives you've considered
I'm open to any suggestion that would allow us to both use the DataProtection library going forward, and to migrate seamlessly from the old Enterprise Library code as we prepare to move off windows VMs with DPAPI and into Application Containers and Key Vault. 

### Additional comments
Do we need to write our own custom key manager for this migration task? Or does something already exist to help us solve this continuity of service problem?

**Comment by blowdart** [comment]
The protect & unprotect results are in an entirely different format and it's not a migration story we've considered, nor, I'm afraid, are likely too, given the age of Enterprise Library in general, let alone that version. I don't think it's possible at all, you'd have to unprotect the data in the old format, then reprotect in the new. 

In addition we make no claims about Data Protection being PCI compliant, it's aimed at ephemeral data, and that's all we use it for in ASP.NET Core. You should obviously have an PCI auditor or other expert make the determination if it's right for your needs.
