### ISSUE TITLE
We should prevent self-closing tag helpers compile time

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#8639]
I'm targeting ASP.NET Core 3.0 preview3.
Here is my page model:

```csharp
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace WebApplication11.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }

        public string ItemsList { get => "asdf"; }

        public IEnumerable<SelectListItem> Items
        {
            get => new SelectListItem[] {
                    new SelectListItem("item 1", "1"),
                    new SelectListItem("item 2", "2"),
                    new SelectListItem("item 3", "3")
                };
        }
    }
}
```

And here is my Index.cshtml:

```cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <select asp-for="ItemsList" asp-items="Model.Items" />
</div>
```

First, my `select` tag helper is self-closing, and that results in improper rendering:

```html
<select id="ItemsList" name="ItemsList">
            © 2019 - WebApplication11 - Privacy
        <script src="/lib/jquery/dist/jquery.js"></script>
        <script src="/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="/js/site.js?v=dLGP40S79Xnx6GqUthRF6NWvjvhQ1nOvdVSwaNcgG18"></script>
</select>
```

As soon as I change the tag helper to have a separate closing tag, things will work just fine:
```cshtml
<select asp-for="ItemsList" asp-items="Model.Items"></select>
```

**Comment by mkArtakMSFT** [comment]
We should prevent these type of errors by failing the build as well as (lower priority) provide the error in the editor window.

**Comment by mkArtakMSFT** [comment]
Alternatively, we can just allow self-closing tag helpers. This in some cases will not be aligned with the mapped HTML tag. Going to discuss this with @danroth and @rynowak offline later this week.

**Comment by NTaylorMullen** [comment]
This was a heavily debated topic when TagHelpers were initially being designed and we landed on the choice of not influencing the self-closing/start-end-tag states of existing Html tags. Therefore, since a self-closing `<select />` tag wasn't valid Html we didn't support it in the `SelectTagHelper`

**Comment by mkArtakMSFT** [comment]
Chatted about this and the amount of work required to do something better here is huge. So won't be doing anything now.
