### ISSUE TITLE
SignalR Core .net client getting disconnected if any of the client disconnects

### ISSUE THREAD

**Issue by nikheeel** [aspnet/AspNetCore#8642]
### Describe the bug
I am using SignalRCore Hub and connected a UI client and a .net client to the hub. I have some custom logic to connect both UI and .net client internally so that both can send and receive request through SignalR Core Hub. This works fine when i run both applications and I can send and receive data from .net client to Ui and vice versa. Issue is, whenever UI is disconnected from signalr hub, the .net client is also gets disconnected and once disconnected , it is unable to reconnect back to the hub. It throws an error 
"System.TimeoutException: Server timeout (30000.00ms) elapsed without receiving a message from the server". Only resolution right now is to stop the .net client and run it again and then it connects to signalr hub.

### To Reproduce
Steps to reproduce the behaviour:
1. SignalR Hub - uses Microsoft.AspNetCore.SignalR- 1.1.0
2. SignalR .net client - uses Microsoft.AspNetCore.SignalR.Client - 1.1.0
3. UI - Angular 7 - "@aspnet/signalr": "^1.1.2"

SignalRHub Code - 
 ```
public override async Task OnDisconnectedAsync(Exception exception)
        {
            await base.OnDisconnectedAsync(exception);
        }
```
.Net Client - 
` public HubConnection _connection;
        private readonly IList<KeyValuePair<string, object>> _messageQueue;
        private readonly ILogger _logger;

        public WebsocketManager(string hubUrl, string hubName)
        {
            _logger = LogManager.GetCurrentClassLogger();
            _messageQueue = new List<KeyValuePair<string, object>>();

            _connection = new HubConnectionBuilder()
                .WithUrl(hubUrl)
                .Build();

            _connection.Closed += async (error) =>
            {
                _logger.Error(error, $"Connection closed at {DateTime.UtcNow}");
                await Task.Delay(new Random().Next(0, 5) * 1000);
                await _connection.StartAsync();
            };

            _connection.StartAsync().Wait();
        }`

3. UI Client -
`constructor() {
		this.connection = new HubConnectionBuilder()
			.configureLogging(LogLevel.Trace)
			.withUrl(environment.signalr)
			.build();

		this.connection.on('Error', err =>
			this.onError$.next(TargetNotFoundError.fromString(err) || new UnknownError(err)),
		);

		this.connection.on('Notification', msg => this.notification$.next(msg));

		from(this.connection.start())
			.pipe(
				switchMap(() => this.register()),
				switchMapTo(this.messageQueue),
				mergeMap(msg =>
					this.connection.invoke(msg.method, ...msg.params).then(msg.resolve, msg.reject),
				),
			)
			.subscribe();
	}`

SignalR Hub has some custom functions to connect Ui and .net client but that are not relevant to this as OnDisconnect is only function called when i close UI

### Expected behavior
When UI is disconnected from SignalR hub, the .net client should not disconnect. In case the .net client disconnects, it should be able to connect back to hub.
### Additional context
Include the output of `dotnet --info`

**Comment by BrennanConroy** [comment]
>SignalR Hub has some custom functions to connect Ui and .net client but that are not relevant to this as OnDisconnect is only function called when i close UI

Everything else about your scenario should be working probably. I'm guessing you're doing something in this part such as blocking the .net client. Could you either provide a repro app or at least the methods you said are not relevant?

**Comment by mikaelm12** [comment]
Does your .net client block in any on handlers currently? If it's blocking waiting for a message from the disconnected web client that could be a cause of the timeout you're seeing. 
Sharing a repro app would help us diagnose.

**Comment by nikheeel** [comment]
I have a register and subscribe function which are called as client connects
` public void Register(string clientName)
        {
            try
            {
                Groups.AddToGroupAsync(Context.ConnectionId, clientName);
                ConnectionManager.RegisterOrUpdateClient(Context.ConnectionId, clientName);
                Clients.Group(clientName).SendAsync("RegistrationSuccess", $"{clientName} registered with Hub.");
                _log.Info($"RegistrationSuccess at {DateTime.UtcNow}, {clientName} registered with Hub.");
            }
            catch (Exception ex)
            {
                Clients.Group(clientName).SendAsync("Error", ex.Message);
                _log.Error(ex, $"Register Failed at {DateTime.UtcNow} for client {clientName}");
            }
        }`

Subscribe
` public void Subscribe(string targetName)
        {
            try
            {
                ConnectionManager.Subscribe(Context.ConnectionId, targetName);
                Clients.Group(Context.ConnectionId).SendAsync("SubscriptionSuccess", $"Subscribed to {targetName}.");
                _log.Info($"SubscriptionSuccess at {DateTime.UtcNow}, Subscribed to {targetName}.");
            }
            catch (Exception ex)
            {
                Clients.Group(ConnectionManager.GetByConnectionId(Context.ConnectionId).Client.ClientName).SendAsync("Error", ex.Message);
                _log.Error(ex, $"Subscription Failed at {DateTime.UtcNow} for target {targetName}");
            }
        }`

Register makes an entry with connection id and client name in a list and subscribe is called buy ui to connect to the .net application .

**Comment by nikheeel** [comment]
> ### Describe the bug
> I am using SignalRCore Hub and connected a UI client and a .net client to the hub. I have some custom logic to connect both UI and .net client internally so that both can send and receive request through SignalR Core Hub. This works fine when i run both applications and I can send and receive data from .net client to Ui and vice versa. Issue is, whenever UI is disconnected from signalr hub, the .net client is also gets disconnected and once disconnected , it is unable to reconnect back to the hub. It throws an error
> "System.TimeoutException: Server timeout (30000.00ms) elapsed without receiving a message from the server". Only resolution right now is to stop the .net client and run it again and then it connects to signalr hub.
> 
> ### To Reproduce
> Steps to reproduce the behaviour:
> 
> 1. SignalR Hub - uses Microsoft.AspNetCore.SignalR- 1.1.0
> 2. SignalR .net client - uses Microsoft.AspNetCore.SignalR.Client - 1.1.0
> 3. UI - Angular 7 - "@aspnet/signalr": "^1.1.2"
> 
> SignalRHub Code -
> 
> ```
> public override async Task OnDisconnectedAsync(Exception exception)
>        {
>            await base.OnDisconnectedAsync(exception);
>        }
> ```
> .Net Client -
> ` public HubConnection _connection;
> private readonly IList<KeyValuePair<string, object>> _messageQueue;
> private readonly ILogger _logger;
> 
> ```
>     public WebsocketManager(string hubUrl, string hubName)
>     {
>         _logger = LogManager.GetCurrentClassLogger();
>         _messageQueue = new List<KeyValuePair<string, object>>();
> 
>         _connection = new HubConnectionBuilder()
>             .WithUrl(hubUrl)
>             .Build();
> 
>         _connection.Closed += async (error) =>
>         {
>             _logger.Error(error, $"Connection closed at {DateTime.UtcNow}");
>             await Task.Delay(new Random().Next(0, 5) * 1000);
>             await _connection.StartAsync();
>         };
> 
>         _connection.StartAsync().Wait();
>     }`
> ```
> 1. UI Client -
>    `constructor() {
>    this.connection = new HubConnectionBuilder()
>    .configureLogging(LogLevel.Trace)
>    .withUrl(environment.signalr)
>    .build();
>    ```
>     this.connection.on('Error', err =>
>     	this.onError$.next(TargetNotFoundError.fromString(err) || new UnknownError(err)),
>     );
>    
>     this.connection.on('Notification', msg => this.notification$.next(msg));
>    
>     from(this.connection.start())
>     	.pipe(
>     		switchMap(() => this.register()),
>     		switchMapTo(this.messageQueue),
>     		mergeMap(msg =>
>     			this.connection.invoke(msg.method, ...msg.params).then(msg.resolve, msg.reject),
>     		),
>     	)
>     	.subscribe();
>    ```
>    }`
> 
> SignalR Hub has some custom functions to connect Ui and .net client but that are not relevant to this as OnDisconnect is only function called when i close UI
> 
> ### Expected behavior
> When UI is disconnected from SignalR hub, the .net client should not disconnect. In case the .net client disconnects, it should be able to connect back to hub.
> 
> ### Screenshots
> If applicable, add screenshots to help explain your problem.
> 
> ### Additional context
> Add any other context about the problem here.
> Include the output of `dotnet --info`

**Comment by BrennanConroy** [comment]
We need either a small repro app or logs and network traces. You can see how to get those here: https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
