### ISSUE TITLE
Asp.Net Core Reporting (SSRS) 

### ISSUE THREAD

**Issue by achester75** [aspnet/AspNetCore#8644]
Hi

I have used alan juden code to run a ssrs report within my c# website. Running the code within visual studio works fine. 

Running from the web address after uploading to IIS it fails due to authentication

The default code in the controller is "return System.Net.CredentialCache.DefaultNetworkCredentials;"

I'm new to all this so am unsure what needs to be done to run the report. How to I ensure the correct credentials entered?

Thanks

**Comment by Eilon** [comment]
Hi, can you provide more info on what you're trying to do? Perhaps provide sample code and show what error(s) you're getting?

**Comment by blowdart** [comment]
Does your web site authenticate at all? Is IIS hosted on a machine within the same domain as your SQL Reporting Server?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
