### ISSUE TITLE
navigation in blazor with urihelper after http call is navigating to same page with "?"

### ISSUE THREAD

**Issue by pmaheshgupta** [aspnet/AspNetCore#8647]
Hi all,

I am trying to navigate to another page in onclick event after a http service call, but i am unable to navigate, instead it is loading the same page with "?" appended at the end.

My onclick event is as follows

```
protected async Task checkpnr()
    {
        string uri = baseurl + "api/pnr/" + pnr + "/check";     
       string isvalidpnr = await Http.GetStringAsync(uri);
        if (isvalidpnr == "true")
        {
            await JsRuntime.InvokeAsync<bool>("setpnr", pnr);
            UriHelper.NavigateTo("/selectpassenger");          
        }
        else
        {
            showerror = true;
        }
    }
```

in the output I am getting

```
Navigated to http://localhost:50506/?

[Violation] 'setTimeout' handler took 178ms      mono.js
```

In the above code if i remove service call and assign a static value to isvalidpnr, I am able to navigate to the mentioned page.

please let me know what the issue is and how to solve it.

**Comment by SteveSandersonMS** [comment]
I'm afraid I don't know. I've never seen anything like this happen, and can't guess where the `?` is coming from.

If you are able to post a simplified repro example (as in, what code do I have to add to the default project template to be able to see this happening?), then we can certainly diagnose and find the solution. However without a repro example we probably can't offer any further information.

**Comment by SteveSandersonMS** [comment]
From another issue, I can now probably guess what's going on.

My guess is that you're triggering this event from a `<button>` which is inside a `<form>`. By default, buttons submit forms, which would cause this navigation to the URL with `?`. Since that doesn't appear to be what you want, you should add the attribute `type="button"` to your button so it no longer submits the form.

**Comment by mcfarland43** [comment]
Changing from type="submit" to type="button" resolved the issue for me too.
