### ISSUE TITLE
Memory Leak in the Unmanaged Heap, Core 2.2.2, Windows, Azure AppService, Always On

### ISSUE THREAD

**Issue by yahorsi** [aspnet/AspNetCore#8648]
Hi Guys!

We, have ASP.NET Core 2.2.2 based app running on Azure with AppInsights enabled.
Periodically, after private bytes reaches aprox 2gb app fails and get's restarted, so we see that with time private bytes grows significantly. We made several memory dumps and initial investigation showed that managed heap size does not grow and stays about 200mb but UNmanaged one grows. Any advise on how to investigate this issue would rock! :)

## Here is an output from !EEHeap -gc
EEHeap -gc
Dump 1 GC Heap Size:    Size: 0xbc22a04 (197274116) bytes.
Dump 2 GC Heap Size:    Size: 0xa485dbc (172514748) bytes.
Dump 3 GC Heap Size:    Size: 0xc6a5638 (208295480) bytes.

So in all 3 dumps GC heap is about 200mb

## If we look at the unmanaged memory we will find that
heap -s

dump 1 
```
  Heap     Flags   Reserv  Commit  Virt   Free  List   UCR  Virt  Lock  Fast 
                    (k)     (k)    (k)     (k) length      blocks cont. heap 
-----------------------------------------------------------------------------
01090000 00000002  **453472 442964 453440**    626   969    32    7      5   LFH
```
....

dump 2
```
  Heap     Flags   Reserv  Commit  Virt   Free  List   UCR  Virt  Lock  Fast 
                    (k)     (k)    (k)     (k) length      blocks cont. heap 
-----------------------------------------------------------------------------
01090000 00000002  **518224 516880 518192**    415   989    36    7      5   LFH
```
....

dump 3 
```
  Heap     Flags   Reserv  Commit  Virt   Free  List   UCR  Virt  Lock  Fast 
                    (k)     (k)    (k)     (k) length      blocks cont. heap 
-----------------------------------------------------------------------------
01090000 00000002  **841984 837892 841952**    487  1051    56    7      6   LFH
```
....

Output from heap -s stripped as there are changes only in 1st heap.
So, according to the heap -s unmanaged heap size grows significantly.

The problem we have now is that we don't know any futher steps we could make to investigate the issue.

And last thing to mention, we observer the leak above in several App's we have. Basically in all of them and we don't do anything bad in our code :) 

Thanks for any advise!

### To Reproduce
We don't know how to repo and it seems it does not reproduces locally, just when deployed on azure

### Expected behavior
With time private bytes and unmanaged heaps stays the same size

**Comment by jkotalik** [comment]
To confirm, are you running with or without IIS In-process? What process are you collecting memory dumps from?

**Comment by yahorsi** [comment]
>>What process are you collecting memory dumps from?
dotnet.exe

>>To confirm, are you running with or without IIS In-process?
Will check it tomorrow

Seems we have AppsInsights enabled if it may help.

**Comment by jkotalik** [comment]
If the process is dotnet.exe, it isn't running inprocess, which help narrow down things. Can you send a dump to me at my email listed on my github profile?

**Comment by yahorsi** [comment]
It seems this is wrong repo for the issue. Here is one in the correct place
https://github.com/dotnet/corefx/issues/36473

So closing

**Comment by yahorsi** [comment]
Just linking:
https://github.com/dotnet/corefx/issues/36473
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/1102
