### ISSUE TITLE
InvalidToken error message is generated when resetting password by .net core identity

### ISSUE THREAD

**Issue by Arash-Sabet** [aspnet/AspNetCore#8652]
### Describe the bug
The following code snippet depicts the process of generating a token to reset a user's password:

```
var user = await _userManager.FindByNameAsync(model.Email);
var code = await _userManager.GeneratePasswordResetTokenAsync(user);
var callbackUrl = Url.Page(
				string.Empty,
				pageHandler: null,
				values: new
				{
					userId = user.Id,
					code = code
				},
				protocol: model.Request.Scheme);
```
The email sender routine sends the following encoded string message to the user's mailbox:

```
var message = $"Please have your password reset by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.",
```
When the user clicks on the generated link, they're directed to a small online form to collect the new password and a POST action is submitted to the backend containing the code, userId and the new password. The backend code tries to reset the password by the following code snippet:

```
var foundUser = await _userManager.FindByIdAsync(model.UserId);
var confirmation = await _userManager.ResetPasswordAsync(foundUser, model.Code, model.NewPassword);
```
The ```confirmation``` object always exhibites ```InvalidToken``` failure.

### To Reproduce
1. Using this version of ASP.NET Core  2.2
2. Steps explained above.

### Expected behavior
```confirmation``` should not exhibit ```InvalidToken``` error message.

### Screenshots
N/A

### Additional context
N/A

**Comment by blowdart** [comment]
In between sending the email are you doing anything else to the user object? Certain things, like changing email addresses will invalidate the security stamp, invalidating all issued tokens. But we've never seen this out of the box with the template code.

Also please check your logs for application startup for Data Protection messages. If you see anything about ephemeral keys, or if you're using multiple servers, then you need to configure data protection

**Comment by Arash-Sabet** [comment]
> In between sending the email are you doing anything else to the user object? Certain things, like changing email addresses will invalidate the security stamp, invalidating all issued tokens. But we've never seen this out of the box with the template code.
> 
No, there is nothing done.

>Also please check your logs for application startup for Data Protection messages. If you see anything about ephemeral keys, or if you're using multiple servers, then you need to configure data protection

None of these cases apply.

**Comment by blowdart** [comment]
This is strange. We know of cases where it happens every now and again (tokens with a + in them), but not every time.

@HaoK any ideas?

**Comment by Arash-Sabet** [comment]
@blowdart @HaoK Any updates on a possible solution?

**Comment by blowdart** [comment]
Without a repo there's not a lot we can do, beyond fixing the known problem with + signs. This isn't a bug we've seen, or had reported before.

**Comment by Arash-Sabet** [comment]
@blowdart I will try to get you a small repo in a few days. Hope that will help.

**Comment by blowdart** [comment]
It would be extremely helpful, thank you

**Comment by bmikkelsen22** [comment]
@blowdart, I am having the same issue as @Arash-Sabet. Just as a test, I run the following code
```csharp
var token = await _userManager.GeneratePasswordResetTokenAsync(user);
var result = await _userManager.ResetPasswordAsync(user, token, "asdf");
```
Which returns an `IdentityResult` with error `InvalidToken`. 

Worth noting that we were previously able to reset passwords via email. Still trying to figure out where the issue got introduced on our end.

**Comment by artem-hryb** [comment]
@bmikkelsen22 , I can see this issue as well. I am getting InvalidToken.  Setting `options.TokenLifespan = TimeSpan` did not help me.

**Comment by blowdart** [comment]
Closing as user discovered the problem
