### ISSUE TITLE
WSFederation options.Validate() throws if ConfigurationManager is null even when configuration and metadata address are filled in

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/AspNetCore#8654]
### Describe the bug
WSFederation options.Validate() throws if ConfigurationManager is null even when configuration and metadata address are filled in. Looking at the source it just checks if ConfigurationManager is set or not and throws a very confusing error message if not.

The ConfigurationManager will be created automatically based on the MetadataAddress and Configuration if available which should mean that the options.Validate should not throw in this case.

### To Reproduce
1. Using this version of ASP.NET Core '...'
2.2

2. Run this code 
```c#
builder.AddWsFederation(authMethod.Id.ToString(), authMethod.Name, options =>
					{
						try
						{
							options.MetadataAddress = authMethod.IdPUrl;							
							options.CallbackPath = $"/signin-wsfed/{authMethod.Id}";
							options.RemoteSignOutPath = $"/signin-wsfed/{authMethod.Id}";
							options.Wtrealm = authMethod.Audience;
							options.RequireHttpsMetadata = false;
							options.SaveTokens = true;
							options.TokenValidationParameters = new TokenValidationParameters
							{
								ValidAudiences = new string[] { authMethod.Audience, $"spn:{authMethod.Audience}" },
								ValidateIssuerSigningKey = !string.IsNullOrEmpty(authMethod.Certificate),
								IssuerSigningKey = string.IsNullOrEmpty(authMethod.Certificate) ? null : new X509SecurityKey(KeyVaultService.GetCertificateFromString(authMethod.Certificate))
							};
							
							options.Validate();
						}
						catch (Exception ex)
						{
							logger.LogError(ex, $"Saml2 Provider configuration invalid: { authMethod.Name } with Id: { authMethod.Id }.");
						}
```

3. With these arguments

Doesn't matter. If the MetadataAddress, Wtrealm and callbackpath are set it shouldn't error on options.Validate()

### Expected behavior
It should validate correctly based on what actually is needed per even the error message that it generates.

### Additional context
This also causes issues if you're attempting to add a wsfederation endpoint at runtime which is still not documented properly.

**Comment by JohnGalt1717** [comment]
The same is true for OpenIdConnectOptions.Validate:

'Provide Authority, MetadataAddress, Configuration, or ConfigurationManager to OpenIdConnectOptions'


The order of operations isn't clear from the error message but with the metadataaddress, clientid, clientsecret and audience on openIdConnect it works the same as metadataaddress and wtrealm works for WsFederation.

**Comment by Tratcher** [comment]
Why are you calling Validate directly? There's PostConfiguration that sets ConfigurationManager.
https://github.com/aspnet/AspNetCore/blob/26c487b0c0d55ac73493547126a65a745cf95abf/src/Security/Authentication/WsFederation/src/WsFederationPostConfigureOptions.cs#L70

**Comment by JohnGalt1717** [comment]
I'm calling Validate because I need to know that my options are right or wrong at time of creation, not later when it trys to access them and something goes wrong on one of our dozens of WsFed and OpenIdConnect options (because we're multi-tenant)

And if it isn't supposed to be called by end code writters, it should be marked protected internal.

**Comment by Tratcher** [comment]
Fair point, but don't call it.

**Comment by JohnGalt1717** [comment]
Ok, well then how else do a validate and fail fast on setup?

**Comment by Tratcher** [comment]
@HaoK? How about in Startup.Configure you eagerly resolving the options? E.g. Resolve `IOptionsMonitor<WsFederationOptions>`, call Get(schemeName), and Validate. PostConfigure should run.

That's how the validation works later:
https://github.com/aspnet/AspNetCore/blob/9f724f6ac4a65160c9847d29bc748e07ce06c7d2/src/Security/Authentication/Core/src/AuthenticationHandler.cs#L57-L86

**Comment by HaoK** [comment]
Yep what @Tratcher says should work

**Comment by JohnGalt1717** [comment]
Thanks!
