### ISSUE TITLE
ResolvedRazorConfiguration, ResolvedRazorCompileToolset not used by tooling

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#8658]
From https://github.com/aspnet/AspNetCore-Tooling/pull/343#discussion_r266967560

This is concerning. All of our project systems (VSWindows, VSMac, VSCode) are definitely not using that 😨 . See below for a list of all the various impls. In VS Windows case the configuration bits are in a separate location:

- [RazorConfiguration.xaml](https://github.com/aspnet/AspNetCore-Tooling/blob/25fe68e2bc95d69154be35e96219cc978241f146/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Rules/RazorConfiguration.xaml)
- [RazorConfiguration.cs](https://github.com/aspnet/AspNetCore-Tooling/blob/25fe68e2bc95d69154be35e96219cc978241f146/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/Rules/RazorConfiguration.cs)

**Comment by rynowak** [comment]
We should close this. This can't and shouldn't change.

**Comment by pranavkm** [comment]
@NTaylorMullen spoke to @rynowak offline. Tooling uses `RazorDefaultConfiguration` and `RazorConfiguration` and resolves these. `ResolvedRazorConfiguration` is calculated inside a target which tooling cannot rely on.
