### ISSUE TITLE
React to core-setup SemVer 2.0 support in ANCM in-proc

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8663]
https://github.com/dotnet/core-setup/issues/4795

Easy mode: Copy the file again once they've updated

Ideal case: Get an export from them that does the hostfxr logic so we don't need to copy code. (https://github.com/dotnet/core-setup/issues/4330)

**Comment by jkotalik** [comment]
https://github.com/aspnet/AspNetCore/pull/8725
