### ISSUE TITLE
Antiforgery token being loaded out of wrong (legacy) cookie?

### ISSUE THREAD

**Issue by mqudsi** [aspnet/AspNetCore#8667]
### Describe the bug
I'm seeing this only in production, so I don't have a repro case (despite poking around pretty hard and faking cookies and playing with cookie names), but:

I have a classic ASP.NET MVC4 application deployed to a Windows Server 2012 IIS application at `/` and a virtual application folder `/foo` to where I have deployed an ASP.NET Core 2.2 app (in-proc with a separate application pool). Both are using the (different) default names for the antiforgery cookies.

In my logs for `/foo` I am seeing messages like the following (which I know are being logged but not actually propagating up the call stack):

```
[01:00:32 ERR] [GET /?utm_source=EasyBCD&utm_medium=software&utm_campaign=Bootable%20EasyBCD&utm_content=Learn%20More] [Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery] An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {b479e916-144f-4ee7-9013-37a17c4e8b72} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

*In the excerpt above, the `GET /...` fragment should be interpreted as being relative to the `/foo` deployment endpoint, not to be confused with the ASP.NET application living at the true `/`.*

The key in question (`{b479e916-144f-4ee7-9013-37a17c4e8b72}`) is the `machineKey` in use by the application deployed to `/`. (**I have no questions about where that came from nor how to get keys to persist between apps or across servers.**) It isn't used by the ASP.NET Core `/foo` app at all, and I'm not wondering why it has no access to the key - it shouldn't.

I suspect there is something wrong because the ASP.NET Core app at `/foo` is fully cognizant of its deployment URL, and generates headers like the following when visiting a page that requests an XSRF token under its virtual directory:

```
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
...
Set-Cookie: .AspNetCore.Antiforgery.8AwjPdqED-c=CfDJ8Hlf0yx7q41FkNt8kheEdIqYST_iybMTAM8BJHHZbUPaBiYDUbERwMxWeVMjZRx76RpVxZN4eniRT3ng51n4R7g2nXc4Z8fhzyIJmpFg8TRRCarER4NUPdf_9qWB89DoWxzHvT_ysIc6sXzaUPKrnvg; path=/EasyRE; samesite=strict; httponly
```

As can be seen, the antiforgery cookie name is correctly suffixed with the encoded `/foo`. The ASP.NET non-Core application at `/` was deployed before the application at `/foo` and not touched since, i.e. it has no knowledge of ASP.NET Core and cannot possibly - anywhere - be sending a `Set-Cookie: .AspNetCore.Antiforgery.8AwjPdqED-c=...` which is specific to both ASP.NET Core and the app deployment path `/foo`.

I realize the error (being on `GET` pages that aren't xsrf-secured) is caught and causes no real harm beyond clogging up the logs, but it makes me wonder if there is a subtle bug somewhere where the unadorned, legacy `__RequestVerificationToken` cookie name is somehow being loaded?

I `grep`d through the asp.net core sources for literal instances of `__RequestVerificationToken` but didn't find anything apart from the `AntiforgeryTokenFieldName` default value, which should be OK (as you can see in the above exception log, it was a `GET` request without a `__RequestVerificationToken` form field included in the www-url-encoded query string). 

I think I'm going to have to add full request logging to find out which payload is triggering the bug, but I can't see any other explanation for an ASP.NET Core application loading/decoding a legacy `__RequestVerificationToken` cookie? If any of the developers have insight into how that might happen, I'm all ears!

----

Environment: IIS 8.5.9600.16384, ASP.NET Core 2.2 in self-contained mode deployed with the latest 2.2 SDK, running as in-proc, `web.config` loading `AspNetCoreModuleV2` v12.2.19024.2`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mqudsi.
You're right - it's just clogging up the logs:
> I realize the error (being on GET pages that aren't xsrf-secured) is caught and causes no real harm beyond clogging up the logs, but it makes me wonder if there is a subtle bug somewhere where the unadorned, legacy __RequestVerificationToken cookie name is somehow being loaded?

If you can come up with a repro, we may be able to investigate it further to see what may be causing it.
Of course, if you find the cause and propose a PR, we'd happily consider it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
