### ISSUE TITLE
Razor Components Detect DotNet is initialized

### ISSUE THREAD

**Issue by mashbrno** [aspnet/AspNetCore#8671]
### Is your feature request related to a problem? Please describe.
In my component I need a hook to a binded property, which is not available until `components.server.js` properly loaded. Is there a way to detect DotNet class is initialized?

Current workaround Is polling:

```javascript
var __intervalid;
var invokenet = function () {
  if (typeof DotNet != 'undefined') {    
    DotNet.invokeMethodAsync('assemblyName', 'OnPageLoadedId').catch(function (err) {           
	  setTimeout(invokenet, 100) 
    });
  if (__intervalid) {
	clearTimeout(__intervalid);    
  } else {
    __intervalid = setTimeout(invokenet, 100);	
  }
}
invokenet();

**Comment by SteveSandersonMS** [comment]
The best way to respond to .NET starting up is to put your logic into the .NET startup code :) I'd recommend putting logic into your `Startup.cs` (e.g., in `Configure`) to call your JS code that does whatever initialization depends on .NET already being running.
