### ISSUE TITLE
What's the difference between using _ and () in the following code 

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#8673]
<button onclick=@(_ => showFragment = !showFragment)>Toggle</button>

I'm not sure when should I use _ before the => operator versus ()
What does each represent ?

Many thanks in advance...

**Comment by gfoidl** [comment]
Hava a look at [Lambda expressions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions).

In short: `()` is when there are no arguments passed in, and `_` is used when you don't care about the argument (more or less a empty placeholder).

BTW: here is not really the right place to ask questions like these :wink:

**Comment by enetstudio** [comment]
Many thanks to you, gfoidl
