### ISSUE TITLE
Surprise: VB.NET has built-in razor pages, so let's have VB.NET project template for ASP.NET MVC Core! 

### ISSUE THREAD

**Issue by VBAndCs** [aspnet/AspNetCore#8674]
Surprise: VB.NET has built-in razor pages! 

Suppose we have this C# razor view:
```
@model IEnumerable<MvcMusicStore.Models.Genre>
@{
    ViewBag.Title = "Store";
}
<h3>Browse Genres</h3>
<p>
    Select from @Model.Count()
genres:</p>
<ul>
    @foreach (var genre in Model)
    {
        <li>@genre.Name</li>
    }
</ul>
```
 
It can be represented perfectly by this VB class:
```VB.NET
Friend Class View1
    Dim Model As IEnumerable(Of MvcMusicStore.Models.Genre)

    Public Sub New(model As IEnumerable(Of MvcMusicStore.Models.Genre))
        Me.Model = model
        ViewBag.Title = "Store"
    End Sub

    'ViewBag.Title = "Store"
    Public ReadOnly Property Razor
        Get
            Return _
    <html>
        <h3> Browse Genres</h3>
        <p>
    Select from <%= Model.Count() %> genres:
    </p>
        <ul>
            <%= (From genre In Model Select <li><%= genre.Name %></li>) %>
        </ul>
    </html>
        End Get
    End Property

End Class
```

The only thing we need is an ASP.NET core template for VB, and a little adjustments to generate the render HTML page from the View1.Razor property! Voila!

Note:
The previous code is not limited to using LinQ only. We can use Lambda expressions (and call them inline) to do any thing we want:
```VB.NET
        <ul>
            <%= (Iterator Function()
                     For Each genre In Model
                         Yield <li><%= genre.Name %></li>
                     Next
                 End Function)() %>
        </ul>
```

**Comment by VBAndCs** [comment]
I want to integrate this idea with the MVC Core, but I can't do it alone, becuase I am not aware of the structure of the project. What I want is to:
 1- Craete a VB.NET template for ASP.NET MVC Core.
 2- Create the view as a VB.NET class as showed in here.
 3- Create an instance of this calss in the controller's action method and pass the model object to its constructor.
 4- Use the Razor property to generate the Html page.
Other than that, every thing should work as usual.
 I need some help to show me where to start, and what parts of the MVC project need to change to make this new approach, encloding the erasing all about cshtml (and vbhtml) files, replacing them with the new vb classes.

**Comment by Eilon** [comment]
Hi @VBAndCs , we appreciate your enthusiasm but for the reasons mentioned in https://github.com/aspnet/AspNetCore/issues/8583#issuecomment-474133744 it is still not something we plan to have in the product. Project templates are one of the most expensive items we have to maintain, so we try to keep them down to a minimum that is necessary for ASP.NET Core.

I encourage you to pursue this idea as an installable template. The template system in .NET Core is fully extensible and you can publish your templates as NuGet packages to share with others.

You can learn more about custom templates on our documentation site:
* https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template
* https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates

**Comment by VBAndCs** [comment]
Finally: A working VB.NET ASP.NET MVC Core Razor sample!
https://github.com/VBAndCs/VB.NET-Razor
I implemented a simple VBRazorViewEngine in the VbRazor project. 
To use VBRazorViewEngine in the project, I added these two statements to the Startup.ConfigureServices method:
```VB.NET
services.AddTransient(Of IConfigureOptions(Of MvcViewOptions), VBRazor.VBRazorMvcViewOptionsSetup)()
services.AddSingleton(Of IViewEngine, VBRazor.VBRazorViewEngine)()
```

The VBRazor is just a VB class that implements the IVBRazor Interface:
```VB.NET
Public Interface IVBRazor
    ReadOnly Property Razor As String

End Interface
```

The Razor property uses the xml literals to compose the HTML code and returns it as a string.. Example:
```VB.NET
Imports VbRazor

Public Class IndexView
    Implements IVBRazor

    Dim students As List(Of Student)

    Public Sub New(students As List(Of Student))
        Me.students = students
    End Sub

    Public ReadOnly Property Razor As String Implements IVBRazor.Razor
        Get
            Dim x = <html>
                        <h3> Browse Students</h3>
                        <p>Select from <%= students.Count() %> students:</p>
                        <ul>
                            <%= (Iterator Function()
                                     For Each std In students
                                         Yield <li><%= std.Name %></li>
                                     Next
                                 End Function)() %>
                        </ul>
                    </html>
            Return x.ToString()

        End Get
    End Property
End Class

```

To use the IndexView from the Controller, I passed it to the View method as the model data in the action method, and passed the actual model data to its constructor:
```VB.NET
Public Function Index() As IActionResult
    Return View(New IndexView(Students))
End Function
```

That’s all!! If you run the project, you will see this web page:
![VBRazor](https://user-images.githubusercontent.com/48354902/54750111-4b9ecf80-4bdf-11e9-8249-773bc6bcca27.jpg)

This was really easy, but needs more work, so I hope you start contribute to this project to make it a real productive tool!
The first thing to do, it to create a VB.NET template for ASP.NET MVC Core. I had to create a C# project then convert it to VB!

The second thing to do, is to add intellisense support for html attributes in xml literals in VB!

**Comment by chucker** [comment]
@VBAndCs I'm confused about your code samples. They clearly show the ASPX view engine, [_not_ the Razor view engine](https://weblogs.asp.net/scottgu/introducing-razor).

For an example of Razor in VB, [check this page](https://docs.microsoft.com/en-us/aspnet/web-pages/overview/getting-started/introducing-razor-syntax-vb) (which, to be clear, does _not_ run in Core).

**Comment by Eilon** [comment]
I recommend that additional questions and comments about the work @VBAndCs has done to be at https://github.com/VBAndCs/VB.NET-Razor.

**Comment by VBAndCs** [comment]
@Eilon
OK.

@chucker
The difference is ussing `<%= > and `Function() ... End Function` ` instead of `@` and `Code End Code`. The purpose is to dynamically generate HTL views whaever the code notation used. Using XML literals makes this a task of VB compiler, so it saves a lot of work and open new possibilities. We are discussing this in VB repo in https://github.com/dotnet/vblang/issues/397

**Comment by VBAndCs** [comment]
Vazor now have project and item templates:
 Download this file:
https://github.com/VBAndCs/Vazor/blob/master/VazorTemplateSetup.zip?raw=true
 then unzip it. Double-click the file VazorTemplateSetup.vsix to setuo the Vazor templates:
 1- A Vazor project template for ASP.NET MVC Core 2.2 .
 2- A Vazor project template for ASP.NET MVC Core 3.0 .
 3- A Vazor project template for ASP.NET Web Pages Core 2.2 .
 4- A Vazor project template for ASP.NET Web Pages Core 3.0 .
 5- A VazorView item template to add a new vazor view (.vazor and .vbxml files) to the MVC project.
 6- A VazorPage item template to add a new vazor page (.cshtml, .cshtml.vb, .vazor and .vbxml files) to the Razor Pages project.
 After installation, open .net and create a new project. In the search box, write Vazor, and choose one of the 4 vazor project templates. In the project created, right-click a folder in solution explorer and select Add/New Item. From the dialoge box select VazorView (if this is an MVC project) or VazorPage (if this is a Razor Pages project).
