### ISSUE TITLE
SignalR DateTimeOffset in Javascript client depends on protocol

### ISSUE THREAD

**Issue by mcparry** [aspnet/AspNetCore#8675]
### Description
A Javascript client receiving a DateTimeOffset value gets a different datatype depending on whether the protocol is JSON or MsgPack.

### To Reproduce
1. Using ASP.NET Core 2.2
2. Create a SignalR hub containing this method: -
        public DateTimeOffset GetTimestamp()
        {
            return new DateTimeOffset(new DateTime(2019,3,15), TimeSpan.FromHours(5));
        }
3. Call this from a Javascript SignalR client, and try it with the JSON protocol as well as the MsgPack protocol.
4. Inspect the returned value (I did this using Chrome developer tools).
5. When using JSON the returned object is a Javascript string containing the ISO 8601 datetime.
6. When using MsgPack the returned object appears to be a Javascript array of 2 elements.  The first element is a Javascript Date object with a GMT timezone (zero offset).  The second element appears to be the timezone offset in minutes, so in my example this is 300.

### Expected behavior
The author of Javascript client code should not have to build different implementations based on whether they choose JSON or MsgPack.  A change of protocol should not require a change of client implementation.  Therefore, the datatype returned to the calling Javascript code should be the same, regardless of which protocol is used.

**Comment by BrennanConroy** [comment]
This is unfortunately a limitation of the msgpack format, see https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-2.2#messagepack-quirks for more info.

**Comment by mcparry** [comment]
I'm not sure that really covers it.  The same information is present on the client-side in both cases, it is just presented to client application code using different data types.  There's no reason why those data types have to be used.  Granted, in at least one case the client-side SignalR library might have to do more work to transform the data into a different type, and for some users that price would not be worth paying.  It seems like a design error to not at least provide the option for the same data type to be presented to client code, independent of protocol choice.

**Comment by anurse** [comment]
JavaScript doesn't have a native data type to carry this data. You're right that having a different type between the protocol feels awkward though. I think the appropriate thing to do here is change the MsgPack format to confirm the data to what the JSON protocol would produce. This would mean normalizing the date to UTC before sending it. To avoid a breaking change, we may have to make it an opt-in option in the message pack config (and doc it).

**Comment by anurse** [comment]
After reviewing our protocol logic, this isn't something we plan to resolve. In general, it is not guaranteed that the JSON and MessagePack protocols return data in exactly the same format. Making this guarantee isn't really feasible.
