### ISSUE TITLE
DecoderFallbackException: Unable to translate bytes [BF] at index 75 from specified code page to Unicode

### ISSUE THREAD

**Issue by Txaran** [aspnet/AspNetCore#8676]
### Describe the bug
POST Request containing non-ASCII characters in its body, throws an exception without having the chance to catch it and fail or perform some action.

### To Reproduce
1. Create a new ASP.NET Core App, targeting Core 2.2: dotnet new webapi
2. Add this class:

```C#
public class TestModel
    {
        public string Name {get; set;}
    }
```
    
3. In ValuesController.cs change POST method:

```C#
 // POST api/values
        [HttpPost]
        public void Post([FromBody] TestModel model)
        {
        }
```

4. Run the application: dotnet run
5. Using BURP issue the following HTTP Message:

```
POST /api/Values HTTP/1.1
Host: localhost:5001
Content-Type: application/json
Content-Length: 21

{
   "name" : "ç"
}
```
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Text.DecoderFallbackException: Unable to translate bytes [E7] at index 16
 from specified code page to Unicode.
   at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int3
2 index)
   at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, I
nt32 index)
   at System.Text.DecoderFallbackBuffer.InternalFallback(Byte[] bytes, Byte* pBy
tes, Char*& chars)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* char
s, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteC
ount, Char[] chars, Int32 charIndex, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteC
ount, Char[] chars, Int32 charIndex)
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.ReadIntoBuffer()
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.Read(Char[] buff
er, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequire
d)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasC
onverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Jso
nReader reader, Type objectType, Boolean checkAdditionalContent)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter.ReadRequestBodyAsyn
c(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsy
nc(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(Actio
nContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider,
ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__Di
splayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilte
rAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter
()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecuted
Context context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope&
 scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsyn
c()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpCon
text)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext
httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(H
ttpContext context)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 331.7931ms 500 text/html; charset=utf-8
```

Note: Using Postman or Even Fiddler won't fail since it seems that they adds charset=utf-8 to Content-Type Header. BURP doesn't.

### Expected behavior
Let developer decide what to do: Fail gracefully, log the error, or try to fix the request /encode on the fly.
From my understanding, this is a vulnerability since it allows a possible attacker to easily flood the server's log with exceptions messages that should not be there. In fact, this issue comes from a PenTest made by InfoSec guys to an Web API that I have to put in production.
Since I've found any other solution, and just as workaround, I've had to remove the [Frombody] input parameter of the method, and deserialize the body inside the method with an extension method:

```C#
// public async Task<ActionResult<FooDto>> CreateAsync([FromBody]BarDto input) //<----Before
 public async Task<ActionResult<FooDto>> CreateAsync() 
{
   var input = await Request.FromBodyAsync<BarDto>(Encoding.UTF8);
   //blah blah blah
}

  public static async Task<T> FromBodyAsync<T>(this HttpRequest request, Encoding encoding = null)
    {
        if (encoding == null)
            encoding = Encoding.UTF8;
        try
        {
            var settings = new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.None //Any value except TypeNameHandling.None is vulnerable
            };
            using (StreamReader reader = new StreamReader(request.Body, encoding))
            {
                string objString = await reader.ReadToEndAsync().ConfigureAwait(false);
                return JsonConvert.DeserializeObject<T>(objString, settings);
            }
        }
        catch (Exception ex)
        {
            return default(T);
        }

    } 
```

But now my tests are broken since the input data is not not wraped into a class anymore, but in the request itself.

```
### Additional context
dotnet --info
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\trodrigu>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

* Edited to clean up the formatting - @pranavkm

**Comment by blowdart** [comment]
Putting the security hat on;

_From my understanding, this is a vulnerability since it allows a possible attacker to easily flood the server's log with exceptions messages that should not be there. In fact, this issue comes from a PenTest made by 
InfoSec guys to an Web API that I have to put in production._

I disagree. You should have the ability to properly interrogate your server logs, and rotate them, without being confused by multiple exception messages. Logging this sort of thing is the right thing to do security wise, because it indicates someone may be sending you malformed messages in an attempt to bypass whatever input validation controls you have in place.

_Let developer decide what to do: Fail gracefully, log the error, or try to fix the request /encode on the fly._

Attempting to fix is definitely not the right thing to do here from a security point of view, because guessing at what encoding was going to have instances where the guess is wrong, and that in turn has security implications depending on the code that is going to parse the payload.

**Comment by Txaran** [comment]
First of all, thanks for your feedback. I really appreciate it.

_You should have the ability to properly interrogate your server logs, and rotate them,_ 
I agree so far.

_without being confused by multiple exception messages_
Exactly. If I easily let someone fill my log with exceptions that were not thrown directly by my application, log file will be polluted with exceptions that I "accept as normal", making very difficult to distinguish them from other exceptions generated for other reason.
Again, from my understanding, and exception is an issue that should be handled somehow, more that letting them just in the log.
_ because it indicates someone may be sending you malformed messages in an attempt to bypass whatever input validation controls you have in place._
Exactly. I can't validate anything because this error happens somewhere before the controllers method. 

_Attempting to fix is definitely not the right thing_
I Agree...I wouldn't attempt to fix, I think that it should be my decision.

**Comment by pranavkm** [comment]
Similar issue - https://github.com/aspnet/AspNetCore/issues/3959. The suggestion there is to treat this as a 4xx response, which is the inline with the response you'd get with any other malformed input.

**Comment by Txaran** [comment]
@pranavkm thanks for your feedback and reformatting

As far as I understand from the liked issue, a 4xx response is returned, without generating an exception but just for .net core 3.xx or above. Could this feature be merged with .net 2.2?

**Comment by pranavkm** [comment]
> Could this feature be merged with .net 2.2?

We typically do not port new features to a patch release. The shared runtime rolls forward to the latest available patch release by default. Consequently any changes in behavior in a patch require a very strong justification. 

A fairly close approximation that could work as a workaround would be to add a global [exception filter](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.2#exception-filters) and respond with a 400 when you observe a `DecoderFallbackException`.

**Comment by Txaran** [comment]
I finally ended up implementing an Exception Filter as suggested. That allows me to take the required action for each case, which was one of my requirements.
