### ISSUE TITLE
Copy IEndpointFeature to the cloned HttpContext for LongPolling

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#8679]
Endpoint routing is the new cool thing, we should copy the feature to our cloned HttpContent when using LongPolling so that things like Auth on Hubs and Razor Components continue to work.

See: https://github.com/aspnet/AspNetCore/issues/8407

**Comment by rynowak** [comment]
Officially requesting that we **definitely** fix this in preview 4. I think this is the reason why fallback hasn't been working for Razor Components.

**Comment by anurse** [comment]
Agreed. This is blocking Razor Components so we should get it done ASAP.
