### ISSUE TITLE
Expose ConnectionId on SignalR Clients

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#8681]
We've had users ask about how to get a client's connectionId Our current guidance to users on how to get it is to create a Hub method to return it to them e.g.

```csharp
public string GetConnectionId() 
{
    return Context.ConnectionId
}

```
Which is less than ideal.

Another thing we planned on doing for the `onReconnected` events is making it have a single parameter which would be the client's new connectionId. 

- [x] .NET
- [x] Java
- [ ] JavaScript

**Comment by anurse** [comment]
Still have JavaScript to do here right? Is this going to land for preview 4 (end of this week)?
