### ISSUE TITLE
TopLevelParameterNameAnalyzer threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by fuocor** [aspnet/AspNetCore#8686]
### Describe the bug
dotnet build throws using ```3.0.100-preview4-010911``` of the sdk
```Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer threw an exception of type 'System.NullReferenceException' ```

### To Reproduce
on my builds

### Expected behavior
should build

### Additional context

I attached the diagnostic build logs and dotnet --info

[build.zip](https://github.com/aspnet/AspNetCore/files/2989869/build.zip)
[ditnet.info.txt](https://github.com/aspnet/AspNetCore/files/2989873/ditnet.info.txt)

**Comment by pranavkm** [comment]
Thanks for the report. We addressed this as part of https://github.com/aspnet/AspNetCore/issues/8403. If you get the most recent SDK (`3.0.100-preview4-010913`), the issue should be resolved.

**Comment by spydacarnage** [comment]
@pranavkm 

I've just download SDK (3.0.100-preview4-011223) and I am now also getting this NRE - has something reverted?

**Comment by pranavkm** [comment]
@spydacarnage not that I know of. I'll reopen this issue for investigation.

**Comment by spydacarnage** [comment]
Thanks

**Comment by Enngage** [comment]
I'm getting the same on Preview 5, but as **warning** and it does not prevent me from building the app:

` warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.`

**Comment by pranavkm** [comment]
Thanks @Enngage. I think I sorted out of the last null refs from this analyzer.

**Comment by hellfirehd** [comment]
I'm still getting this with v3.0.100-preview6-012264:
```
warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```
This is no `global.json` in use.

```text
D:\Source> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

What else can I provide to help troubleshoot this?

**Comment by pranavkm** [comment]
@hellfirehd do you happen to have the stack trace for this?

**Comment by hellfirehd** [comment]
I don't know how to get a Stack Trace from inside Visual Studio 2019 Community but it only happens during build, but on several different projects.

https://gist.github.com/hellfirehd/9720846be7aa1880f794861921f3c03a

I'm willing to share the Source Code/Project Files for Project1.txt

**Comment by pranavkm** [comment]
> I'm willing to share the Source Code/Project Files for Project1.txt

That would be great!

**Comment by hellfirehd** [comment]
@pranavkm How do I get it to you? It's a 2.2MB .zip

**Comment by pranavkm** [comment]
Could you publish it as a GitHub repo? I think GitHub might also allow you to attach zip files to comments.

**Comment by hellfirehd** [comment]
Invite sent.

**Comment by pranavkm** [comment]
Your netcoreapp3.0 application is referencing 2.2 versions of packages which is unsupported. Have a look at https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio for migrating to 3.0.

**Comment by sunildixit** [comment]
I am still seeing this issue. 

Here's the stack trace

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	ConnectorApp.Web		1	Active	Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: ConnectorApp.Web
ISymbol: Create (Method)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CodeAnalysisExtensions.IsAssignableFrom(ITypeSymbol source, ITypeSymbol target)
   at Microsoft.CodeAnalysis.CodeAnalysisExtensions.<GetAttributes>d__2.MoveNext()
   at Microsoft.CodeAnalysis.CodeAnalysisExtensions.<GetAttributes>d__4.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer.<>c__DisplayClass3_0.<InitializeWorker>b__0(SymbolAnalysisContext symbolAnalysisContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__43_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

**Comment by spydacarnage** [comment]
What version of Core, VS2019, etc. are you using?

I had the problem as well, but it went away weeks ago after an upgrade.

**Comment by pranavkm** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!

**Comment by deathcat05** [comment]
I am having an issue as well. 
I have several cs projects that target netstandard2.0. But, I have a asp.net app targeting the netcoreapp3.0 which has a dependency on these 2.0 projects. 
 
My netstandard projects reference these packages: 
```
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
<PackageReference Include="Microsoft.Extensions.Http" Version="2.2.0" />
```

I don't have any need for these packages in the .csproj for my netcoreapp3.0.

**Comment by SimonCropp** [comment]
@pranavkm 

> Your netcoreapp3.0 application is referencing 2.2 versions of packages which is unsupported.

would it be worthwhile having some better interactive feedback as to this scenario? I assume most people will just change to `<TargetFramework>netcoreapp3.0</TargetFramework>` (as i did) and then cant build to a null reference in the `TopLevelParameterNameAnalyzer `

**Comment by GammaFour** [comment]
I had a working solution with no warnings or errors.  Just downloaded the production release of Visual Studio 2019 16.3.0.  Now I'm getting:

```
5>CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
5>CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
5>CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
5>CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
5>CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.


```

**Comment by pranavkm** [comment]
@SimonCropp our migration guide is fairly elaborate, so hopefully this should be covered.

@GammaFour \ @deathcat05 please file a separate issue, possibly with a minimal repro. I'm locking this issue since we've resolved the original issue and it's just incredibly noisy at this point.
