### ISSUE TITLE
Update Grpc.AspNetCore.Server version in templates

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#8693]
This is required to get the fix https://github.com/grpc/grpc-dotnet/issues/143. Right now the manual template tests are broken due to this. Needs https://github.com/grpc/grpc-dotnet/issues/179 first though.

**Comment by JamesNK** [comment]
Is this done?

**Comment by JamesNK** [comment]
Will need to update again prior to preview 4 release.

**Comment by JunTaoLuo** [comment]
Need to update to 1.20.0-pre2 or newer for Grpc.Tools and a new version of Grpc.AspNetCore.Server when available.

**Comment by JunTaoLuo** [comment]
This has now been merged for preview 4.
