### ISSUE TITLE
Cannot read request body when passing cancellation token

### ISSUE THREAD

**Issue by Andrusha26** [aspnet/AspNetCore#8702]
When I pass the cancellation token as a parameter to my web API action and try to read Request.Body via StreamReader, I get an empty string, even if the body cannot be empty. I send the request via POSTMAN.

Aspnet core 2.1
 Run this code 
```
        [AllowAnonymous]
        [HttpPost("test")]
        public async Task<string> HandleOrderCallbackAsync2(CancellationToken cancellationToken)
        {
            Request.EnableRewind();
            Request.Body.Position = 0;
            using (var stream1 = new StreamReader(Request.Body))
            {
                var content1 = await stream1.ReadToEndAsync().ConfigureAwait(false);
                await Task.Delay(100, cancellationToken).ConfigureAwait(false);
                return content1;
            }
        }
```
Then I get empty content1 variable. But, the same request, and the same method without cancellation token, reads the body.

```
        [AllowAnonymous]
        [HttpPost("test")]
        public async Task<string> HandleOrderCallbackAsync2()
        {
            Request.EnableRewind();
            Request.Body.Position = 0;
            using (var stream1 = new StreamReader(Request.Body))
            {
                var content1 = await stream1.ReadToEndAsync().ConfigureAwait(false);
                return content1;
            }
        }
```

### Screenshots
Request
![image](https://user-images.githubusercontent.com/30469229/54757300-9aa23000-4bf2-11e9-8a20-fe347f3a3078.png)

Showing that I get the body.
![image](https://user-images.githubusercontent.com/30469229/54757259-88c08d00-4bf2-11e9-8383-6081ed9beb66.png)

Showing that I don't get the body.
![image](https://user-images.githubusercontent.com/30469229/54757405-d4733680-4bf2-11e9-9072-b9cff7e349b9.png)

**Comment by vaskiv99** [comment]
Have the same issue(

**Comment by muratg** [comment]
@Tratcher What area label would this go to?

**Comment by Tratcher** [comment]
Seems like an issue with model binding. What is the request content-type?

**Comment by Andrusha26** [comment]
@Tratcher request content type is application/x-www-form-urlencoded, but I think the existence of cancellation token shouldn't have an influence on the body? Please correct me, if I'm not right.

**Comment by pranavkm** [comment]
> but I think the existence of cancellation token shouldn't have an influence on the body? 

MVC will actively read form-urlencoded request bodies if it has to do model binding. Having the `CancellationToken` will result in model binding. You can use a filter to disable this behavior. 

* https://github.com/aspnet/Entropy/blob/7a53120c620bbcfd7b54f147c16fa7da1e38d1d4/samples/Mvc.FileUpload/Controllers/FileController.cs#L43
* https://github.com/aspnet/Entropy/blob/7a53120c620bbcfd7b54f147c16fa7da1e38d1d4/samples/Mvc.FileUpload/Filters/DisableFormValueModelBindingAttribute.cs

**Comment by Andrusha26** [comment]
@pranavkm Thank you, it solves the issue.

**Comment by Tratcher** [comment]
Or not inject the CT and instead take it from HttpContext.RequestAborted.
