### ISSUE TITLE
UriHelper NavigateTo new tab

### ISSUE THREAD

**Issue by TFTomSun** [aspnet/AspNetCore#8703]
Hello,

is it somehow possible (in Blazor) to programatically open a url in new tab? 

Best regards,
Thomas

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @TFTomSun.
@SteveSandersonMS is this something possible with pure Blazor, or should this be achieved with JSInterop for now?

**Comment by SteveSandersonMS** [comment]
You'll need to use JS interop for this.

**Comment by TFTomSun** [comment]
Just in case someone else come accross this post...

```csharp
        public async Task NavigateToUrlAsync(string url, bool openInNewTab)
        {
            if (openInNewTab)
            {
              await JSRuntime.Current.InvokeAsync<object>("open",url,"_blank");
            }
            else
            {
                this.UriBuilder.NavigateTo(url);
            }
        }


```
