### ISSUE TITLE
Blazor Data-Attribute rendering error

### ISSUE THREAD

**Issue by SamProf** [aspnet/AspNetCore#8704]
### Describe the bug
When you add ref all data-attributes not working anymore.
We have exception: System.InvalidOperationException: Attributes may only be added immediately after frames of type Element or Component
```
<div ref="Ref" data-test1="@test1"></div>
    @functions
    {
        ElementRef Ref;
        string test1 = "111";
    }

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SamProf.
This is a known issue which we track at https://github.com/aspnet/AspNetCore/issues/7509
