### ISSUE TITLE
Build C++ Client on macOS, Windows and Linux with CMake

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#8706]
Epic #5301 

- [x] Works on Windows, Linux, and Mac
- [x] CI integration
- [x] Optional flag/define for building tests (off by default?)
- [x] ReadMe describing how to build/consume the client

**Comment by anurse** [comment]
Pre-triage notes:
* Not necessary for preview 5, suggest moving to a later preview.

**Comment by BrennanConroy** [comment]
I'd argue this is good for preview4, I already have a draft PR 95% working for this, https://github.com/aspnet/SignalR-Client-Cpp/pull/4

**Comment by anurse** [comment]
Triage decision: We'll leave this in preview 5 but it's fine if it slips.

**Comment by anurse** [comment]
Let's see about getting this done in Preview 8 (though I think it's basically done?)

**Comment by BrennanConroy** [comment]
Almost, there was some feedback I'd like to react to.

**Comment by BrennanConroy** [comment]
Done via https://github.com/aspnet/SignalR-Client-Cpp/pull/4
