### ISSUE TITLE
Support automatic reconnect in the .NET client

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8710]
Epic https://github.com/aspnet/AspNetCore/issues/8797

Split from https://github.com/aspnet/AspNetCore/issues/5282

We will support automatic reconnect in 3.0 **without message replay**. We will also allow customization of the reconnect logic. This will be opt-in via a `HubConnectionBuilder` option. The default behavior will continue to be manual reconnection.

**Comment by anurse** [comment]
Pre-triage notes:
* Seems reasonable for preview 5 given that TS already drove the "design".
* Need to determine if we can close on this quickly enough

**Comment by anurse** [comment]
Triage Decision: We expect to have this done (in an initial form at least) for preview 5.

**Comment by mikaelm12** [comment]
*Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [X] The fix contains product changes (**check all items below**).
	* [X] Relevant XML documentation comments for new public APIs are present.
	* [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [X] The change requires a new article/updated article. An issue with an outline has been filed here: [aspnet/AspNetCore.Docs/issues/12586]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [ ] The change requires no docs changes.
	* [X] Verification has been completed. (**check one item below**)
    	* [X] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [3.0.100-preview6-012105]
			* ASP.NET Core Runtime: [3.0.0-preview6-19278-05]
			* .NET Core Runtime: [3.0.0-preview6-27728-04]
	    * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
