### ISSUE TITLE
[Tooling] Referencing Microsoft.AspNetCore.Razor.Design causes VS' out of process host to crash

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#8722]
Basically [this](https://github.com/aspnet/AspNetCore-Tooling/blob/d0a8aa3f9717994f2567e4caf7c0061dd89d3459/src/Razor/src/Microsoft.VisualStudio.Editor.Razor/LegacyProjectEngineFactory_3_0.cs#L34) will explode since there isn't guaranteed to be the component classifier pass when lang version < 3.0

**Comment by NTaylorMullen** [comment]
@pranavkm this is your specialty, Was able to reproduce by simply adding the Razor.Design reference. Typically this will happen when a user is updating so it's definitely something we should fix or at least warn the user about via MSBuild errors.

Here's a VS msbuild binlog of [my repro](\\NTaylorMullen2\SHARED\RazorDesignIssue\msbuild.binlog)

**Comment by pranavkm** [comment]
From https://github.com/aspnet/AspNetCore-Tooling/pull/365#issuecomment-476417245

> As part of verifying this, I tried out https://github.com/aspnet/AspNetCore/issues/8722. With the more recent changes to how we infer the configuration, with a 2.1 Razor Design package in a 3.0 project, you get, `RazorLangVersion=2.1, RazorConfiguration=<Empty>`. The `RazorTagHelper`  task gracefully fails validation saying it requires a valid value for configuration. I did not see a crash with a recent build of tooling. If there was a specific build where the problem was reproduced, I'd be happy to try it out.

@NTaylorMullen?

**Comment by NTaylorMullen** [comment]
The issue didn't crash VS it crashed the out of process host which resulted in a yellow banner across VS saying that a VS process failed unexpectedly. The one I reprod it on was VS' master branch with a 3.0 CLI/SDK installed.

If everything fails gracefully without an out of process crash/banner that's ideal. That being said, does Razor end up parsing the 3.0 project as if it's 2.1 (the default Razor config)?

**Comment by pranavkm** [comment]
> That being said, does Razor end up parsing the 3.0 project as if it's 2.1 (the default Razor config)?

Yup. Closing since this issue was resolved.
