### ISSUE TITLE
Make SignalR Java tests output test results to AzP

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8724]
JUnit should support outputting a JUnit-style XML file... otherwise... wat?

We should do that and then make sure AzP is scooping up junit xml files in a [Publish Test Results](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml) task.

**Comment by mikaelm12** [comment]
Done here: https://github.com/aspnet/AspNetCore/pull/9214

**Comment by mikaelm12** [comment]
Here is the reporting with some forced failures.
![SignalRTestReport](https://user-images.githubusercontent.com/4809660/55919602-78754f80-5bab-11e9-8b18-8333069663a7.png)
