### ISSUE TITLE
Customer modelbinder has null reference in Ubuntu 18.04 from .Net Core 2.1

### ISSUE THREAD

**Issue by Penergy** [aspnet/AspNetCore#8732]
### Customer Modelbinder return null reference in Ubuntu
I used Customer Modelbinder to get Object ParameterOptions from request query. In windows environment, it worked fine. However when I deployed in Ubuntu18.04, it failed. Could you check this feature in Ubuntu.

### To Reproduce
1. Using this version of ASP.NET Core '2.1.9' in Ubuntu 18.04
2. Code in Binder:
```
public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            if (bindingContext == null)
            {
                throw new ArgumentException(nameof(bindingContext));
            }

            try
            {
                ParameterOptions option = null;
                // Try to fetch the value of the argument by name "unitTestOption"
                var result = bindingContext.ValueProvider.GetValue("unitTestOption");
                if (result != ValueProviderResult.None)
                {
                    var value = result.FirstValue;
                    if (String.IsNullOrEmpty(value))
                    {
                        return Task.CompletedTask;
                    }
                    bindingContext.ModelState.SetModelValue("ParameterOptions", result);

                    option = JsonConvert.DeserializeObject<ParameterOptions>(value);
                   if (option == null)
                    {
                        Console.WriteLine("Test Controller binder 0: hahaha");
                    }
                    else
                    {
                        Console.WriteLine("Test Controller binder 1: yyyyyy");
                    }
                    bindingContext.Result = ModelBindingResult.Success(option);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("model binding error: " + ex.Message);
            }
            
            return Task.CompletedTask;
        }
```
the Object Class:
```
public class ParameterOptions
    {

        public string Filename { get; set; } = "";
        public string Start { get; set; } = "";
        public string End { get; set; } = "";
        public TestType UnitTestCategory { get; set; } = TestType.None;
        public string caseName { get; set; } = "";

    }
```
REST API in controller
```
public async Task<IActionResult> UploadFile(
            IFormFile file = null,
            string modelId = null,
            string repository = ModelRepositoryName.Dss,
            ParameterOptions paramOption = null,
            ) {
           if(paramOption == null)
            {
                Console.WriteLine("Test Controller is hahaha");

            }else
            {
                Console.WriteLine($"have value {paramOption.Filename}");
            }
}
```
Provider class:
```
public class ParameterOptionsBinderProvider : IModelBinderProvider
    {
        public IModelBinder GetBinder(ModelBinderProviderContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (context.Metadata.ModelType == typeof(ParameterOptions))
            {
                return new ParameterOptionsBinder();
            }
            return null;
        }
    }
```

### Expected behavior
In Windows Visual Studio 2017, I use .Net Core 2.1.400, it worked fine. 

However, in Ubuntu 18.04, the option object in binder existed and the ```paramOption ``` in Controller return null reference. 

I am not sure whether the object reference pass from ``` bindingContext.Result ``` is failed or not in Ubuntu. 

### Additional context
 I use this for Unit Test by using XUnit. When I run unit test pipeline, it failed.

**Comment by pranavkm** [comment]
> I use this for Unit Test by using XUnit. When I run unit test pipeline, it failed.

Can you share an end-to-end repro app? It's difficult to piece together what your inputs looks like from the issue report.

**Comment by Penergy** [comment]
@muratg Thanks for reply. This is a private repo which I couldn't share with you. But I will look into deep in docker ubuntu 18.04 and give you the lastest situation.

**Comment by Penergy** [comment]
I have tested in Ubuntu Environment in Docker. It worked fine. But still when I used XUnit Unit Test, it failed. 
**This is the desensitization log**
![Untitled2](https://user-images.githubusercontent.com/4522788/54899851-37730f00-4f0c-11e9-8492-15cb95aa551c.png)
**Modelbinder**
![Untitled3](https://user-images.githubusercontent.com/4522788/54900125-1d85fc00-4f0d-11e9-861f-08787f015885.png)
**Controller**
![Untitled4](https://user-images.githubusercontent.com/4522788/54900183-3ee6e800-4f0d-11e9-8e32-37080af0103c.png)

**Comment by pranavkm** [comment]
In the absence of a minimal application to reproduce the issue, we're going to be unable to investigate this issue further. In particular when it seems like the app works fine, but your unit tests fail, this could very well be an issue with test setup. Feel free to reopen it once you have an application to share with us with that shows what the inputs are, and what the expectations are.

**Comment by Penergy** [comment]
@pranavkm @muratg , I've found the problem which is not the issue from ASP.NET Core. It's the problem about APSNETCORE_ENVIRONMENT in my project. 

Sorry to disturb your guys and thanks for your help! You are creating such a wonderful framework!
