### ISSUE TITLE
Problem with Blazor "full screen" application

### ISSUE THREAD

**Issue by Patrick8639** [aspnet/AspNetCore#8734]
### Describe the bug
With a "full screen" application, the height is not the height in the browser.

### To Reproduce
1. Create a Blazor application.

2. MainLayout.cshtml
```
@inherits LayoutComponentBase
<div>
  @Body
</div>
```

3.  Index.html
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Blazor test</title>
    <base href="/" />
    <style>
      html, body {
        margin: 0;
        height: 100vh;
        width: 100vw;
      }

      canvas {
        background-color: lightblue;
        width: 100%;
        height: 100%;
      }

    </style>
  </head>

  <body>
    <app>Loading...</app>

    <script src="_framework/components.webassembly.js"></script>

  </body>
</html>
```

4. Index.cshtml
```
@page "/"
<canvas id="Canvas" />
```

### Expected behavior
The canvas should be full screen, as if it's not in a Blazor application.

### Additional context
With the same HTML code outside of a Blzor application, the canvas is full screen.
When looking at the DOM properties, the "app" tag has its height set to a specified value. Even adding `style="width: 100%; height: 100%;"` to it doesn't work

**Comment by adrianwright109** [comment]
I have copied your repro steps and I'm not able to reproduce the issue.  The Blazor version and the non-Blazor version render the same for me in Chrome Version 73.0.3683.86

I have added `expected.html` to `wwwroot` to show how the non-Blazor version is rendered.

I have created have created a repo of it working here: https://github.com/adrianwright109/BlazorApp

**Comment by Patrick8639** [comment]
Hello Adrian,
Thank you for your answer.

When I run your application, I have the following display in Firefox, Chrome or Edge. The height of the canvas depending on the width of the browser window.

![image](https://user-images.githubusercontent.com/26135035/54835494-79107980-4cc2-11e9-8aee-8238a081ec68.png)

As you can see, the canvas doesn't fill the browser window.

NB: I'm also using the latest Blazor release

**Comment by adrianwright109** [comment]
It doesn't work for me in the non-Blazor version so don't think this is Blazor related.

Try changing your `<style>` tag in the `wwwroot\Index.html` to:
```
    <style>
        html, body {
            margin: 0;
            width: 100%;
            height: 100%;
        }

        canvas {
            background-color: lightblue;
            width: 100vw;
            height: 100vh;
            display: block;
        }
    </style>
```

**Comment by Patrick8639** [comment]
Hi Adrian,
Your solution seems to be correct, but if I add a border to the canvas, the browser displays scroll bars, so it seems that the canvas has not the right dimensions. The style block looks then as:
```
    <style>
      html, body {
        margin: 0;
        height: 100vh;
        width: 100vw;
      }

      canvas {
        background-color: lightblue;
        border: 1px solid black;
        width: 100%;
        height: 100%;
      }

    </style>
```

With the following HTML/CSS only source file, the display is always correct:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Blazor test</title>
    <base href="/" />
    <style>

      html, body {
        margin: 0;
        width: 100vw;
        height: 100vh;
        overflow: hidden;
      }

      canvas {
        background-color: lightblue;
        border: 1px solid black;
        width: 100%;
        height: 100%;
      }

    </style>
  </head>

  <body>
    <canvas id="canvas"></canvas>
  </body>
</html>
```

With the same style sheet in Blazor, it doesn't work!

**Comment by adrianwright109** [comment]
That's because in Blazor the `<canvas id="canvas"></canvas>` tag is wrapped in an `<app><div>` that's not present in the markup above.

E.g.
```
<body>
    <app>
        <div>
            <canvas id="canvas"><\canvas>
        </div>
    </app>
</body>
```

**Comment by Patrick8639** [comment]
Hi Adrian,
You're right that it's the cause of the problem.

But we're again at what I say at the beginning: **there's a problem when we want to make a Blazor "full screen" application** . And the problem is not easy (if not impossible) to correct on our side.

**Comment by Patrick8639** [comment]
With the help of Adrian, that has pointed me to the right direction, I have found the solution:

1. The MainLayout.cshtml file must be:
```
@inherits LayoutComponentBase
@Body
```

2. The styles must be:
```
    <style>

      html, body {
        margin: 0;
        width: 100vw;
        height: 100vh;
        overflow: hidden;
      }

      canvas {
        background-color: lightblue;
        border: 1px solid black;
        width: 100%;
        height: 100%;
      }

    </style>
```
