### ISSUE TITLE
How to use signalr web workers in javascript client

### ISSUE THREAD

**Issue by malled** [aspnet/AspNetCore#8736]
Hello,
according to this pr https://github.com/aspnet/AspNetCore/pull/7058, signalr should support web workers. But the instructions are not clear to me.

I installed version 1.1.2 through npm (`"@aspnet/signalr": "^1.1.2"`). The readme tells me to copy the webworker folder at `dist/webworker` into my script folder and use these files. But the npm release does not contain any webworker related files.

How can I use webworks with npm inside an angular app? Is it available only in >=3.0.0?

**Comment by BrennanConroy** [comment]
>Is it available only in >=3.0.0?

Correct, the README is changed for the 3.0.0 release to include instructions on how to use a webworker. You can try it out by using a preview build, for example https://www.npmjs.com/package/@aspnet/signalr/v/3.0.0-preview3-19153-02
