### ISSUE TITLE
Blazor: IJSRuntime.InvokeAsync<dynamic>("...")

### ISSUE THREAD

**Issue by oliversturm** [aspnet/AspNetCore#8742]
When returning complex values from JavaScript functions, I would like to choose whether to create a static type for them or to receive them in a `dynamic`. Currently the use of `dynamic` results in a compiler error message, as does the use of a `dynamic` property in Razor content (`CS0656 Missing compiler required member`).

Let's say I have this JavaScript function:

```js
window.getTheAnswer = () => ({
  description: 'The answer to life, the universe and everything',
  value: '42'
});
```

I should be able to use this component to interface with it:

```cs
@inject IJSRuntime Js

<div>
  <button onclick=@GetTheAnswer>Get the answer to life, the universe and everything</button>
  <p>Description: @Answer.description</p>
  <p>Value: @Answer.value</p>
</div>

@functions {
  dynamic Answer { get; set; }

  async Task GetTheAnswer()
  {
    Answer = await Js.InvokeAsync<dynamic>("getTheAnswer");
  }
}
```

**Comment by SteveSandersonMS** [comment]
This comes down to whether the underlying JSON library supports deserializing to `dynamic`, which currently it doesn't and isn't something we plan to add.

Once we move to the new System.Text.Json library, you'll be able to deserialize to something like a `JObject` or whatever name the new library uses for an untyped JavaScript object.
