### ISSUE TITLE
Razor components should always clean solutions

### ISSUE THREAD

**Issue by kardokh** [aspnet/AspNetCore#8751]
Hi,

in the razor components i should always clean solution in vs 2019 then run the app to update the result,example like change the label then run the app without clean solution the will not update the ui,
also when i run dotnet watch run the ui will not update.

**Comment by kardokh** [comment]
Hi,

i should always clean solution in vs 2019 then run the app to update the result,example like change the label then run the app without clean solution the will not update the ui.

**Comment by aiqoo** [comment]
same problem...

**Comment by SteveSandersonMS** [comment]
You don't need to clean the solution - you just need to run the build again after making a change.

For `dotnet watch`, you need to configure it to rebuild when `.cshtml`/`.razor` files change.

**Comment by kardokh** [comment]
not working when i just run the build, always i should clean solution

**Comment by sven5** [comment]
not working, always needs a rebuild. 
I checked with blank template and preview3. Changes are not reflected through a build.

**Comment by aiqoo** [comment]
i manage to fixit in my project

first i install from nuget Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation

and and edit my csproj file:
`
  <PropertyGroup>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>
`
also i run my project in wach mode' add this lines to csproj :
`
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.0.0-preview3-19153-02" />
    <UpToDateCheckInput Include="@(Content-&gt;WithMetadataValue('Extension', '.razor'))" />
    <Watch Include="**\*.cs" />
    <Watch Include="**\*.cshtml" />
    <Watch Include="**\*.razor" />
  </ItemGroup>
`

for Auto watch run add thois to launchSettings.json:

`"DotnetWatchRun": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "workingDirectory": "$(ProjectDir)",
      "commandLineArgs": "watch run",
      "launchBrowser": true,
      "launchUrl": "https://localhost:5001/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HTTPS_PORT": "44393"
      }
    }`

I hope that in the future, compiling at run time will work faster.

**Comment by SteveSandersonMS** [comment]
@kardokh Oh, you're probably hitting the fast-up-to-date-check bug that we're fixing in the next preview.

Temporary workaround: https://github.com/aspnet/AspNetCore/issues/8181#issuecomment-469725182

**Comment by sven5** [comment]
@SteveSandersonMS 
Thanks. It's working now.

**Comment by kardokh** [comment]
@SteveSandersonMS @aiqoo Thanks, its working.
