### ISSUE TITLE
Allow PII to be displayed for debugging purposes

### ISSUE THREAD

**Issue by roblframpton** [aspnet/AspNetCore#8752]
I am trying to debug a problem I have with my JwtBearer authentication, but I am having difficulty because PII is being hidden.  Obviously I understand why this is the default, and rightly so, but when I am debugging on my local machine it means I am given frankly useless messages such as:

```
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match keys:
kid: '[PII is hidden]',
token: '[PII is hidden]'.
```

I'm not sure why it bothers to try showing the `kid` and `token` if PII is always hidden, and as far as I can make out from #1259, there is no option to override this.  I cannot find any documentation which states otherwise.

### Describe the solution you'd like
A flag which can be set, ideally through the config, which displays PII for debugging purposes.

**Comment by blowdart** [comment]
This is a question for the Identity Model team. Their repo is at https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

**Comment by lust4life** [comment]
@roblframpton `IdentityModelEventSource.ShowPII = true;` when `ConfigureServices` will give what you want.
