### ISSUE TITLE
When client doesn't handle hub message, don't generate System.IO.InvalidDataException

### ISSUE THREAD

**Issue by paultobey** [aspnet/AspNetCore#8753]
### Is your feature request related to a problem? Please describe.
While watching debug messages from one of my SignalR clients, I noted regular System.IO.InvalidDataException thrown by the client. After debugging into the SignalR source, it looks like this exception will be thrown for any hub message for which the client hasn't set up an On() handler.

### Describe the solution you'd like
Situations where a hub message is received and no handlers are defined for it by the client should exit silently ignoring the hub message. They should NOT fire an exception that's completely wrong for the situation. If you must fire an exception how about a new SignalR.Exceptions.NoClientHandler(string methodName)?

### Describe alternatives you've considered
There's nothing my client code can do, as the event triggering the exception is asynchronous to any action I'm taking.

### Additional context
The problem fires from this sequence of operations while trying to match On handlers and their arguments to incoming hub messages:

HubConnection.cs near line 702 - call TryParseMessage()
|
->JsonHubProtocol.cs near line 85 - call ParseMessage()
    |
    -> JsonHubProtocol.cs near line 229 - call binder.GetParameterTypes() - When no handler is found, GetParameterTypes returns Type.EmptyTypes (how about returning a NO-HANDLER indication?), which is then treated as "the handler is expecting zero arguments", rather than "there is no handler; move on!"

**Comment by halter73** [comment]
This seems to be a complaint about first chance exceptions for hub messages without an attached handler. We also might log the exception. Both seem unnecessary.

Is that correct @paultobey?

**Comment by paultobey** [comment]
@halter73 
There are a couple of cases:
1. Average, normal operation case: the user doesn't have a handler for the message, there's no reason to either a) throw the exception, or b) log the condition. (Seems like a simple test would be faster than throwing and handling the exception.)
2. Client *intends* to attach a message handler but it's not getting called. In debugging/tracing, logging the fact that no handler *for message "XYZ"* exists should help debug misspellings of the message name. Throwing the exception should be reserved for the case where a) we found a handler for the message, but b) its parameter list is wrong. In that case, the exception should include enough information to identify "mismatched parameter lists between actual message "XYZ" and On handler" as the cause.

Thanks!

**Comment by anurse** [comment]
We don't intend to change this behavior. Calling a method that isn't defined on the client isn't a supported scenario. If you want to suppress this message you can register a no-op message, or simply filter these messages out of your logs.

**Comment by paultobey** [comment]
@anurse Could you at least clean up the exception so it's obvious *why* it's thrown? Right now, it's like the check-engine light in the car, could mean anything and provides no guidance for someone debugging the issue at all.

**Comment by anurse** [comment]
That's a good point, we can definitely do that :).

**Comment by anurse** [comment]
@paultobey can you clarify what version of the client you are using? I think we actually fixed something like this in the 1.1 version of Microsoft.AspNetCore.SignalR.Client.

**Comment by paultobey** [comment]
@anurse I'm presently using 1.0.4. I'll try 1.1.0 as an experiment and advise.

**Comment by mikaelm12** [comment]
On the client we improved the error message the scenario where the callback didn't exist.
https://github.com/aspnet/AspNetCore/blob/b6d8c96a98c9e5673cd10162616ed98799c60d88/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1868-L1874

If you update you shouldn't see this issue anymore

**Comment by anurse** [comment]
Ok, I'm going to close this for now since we did fix this exception message in 1.1. Please feel free to comment if you can still repro this issue and we can investigate further!

**Comment by paultobey** [comment]
Yes, this is significantly better than before:

Microsoft.AspNetCore.SignalR.Client.HubConnection: Warning: Failed to find handler for 'StationStatusChange' method.

Scheduling client upgrades now.

**Comment by mikaelm12** [comment]
Glad to hear it 👍
