### ISSUE TITLE
rzc generate exited with code -2147450730

### ISSUE THREAD

**Issue by raghavendra-udyavar** [aspnet/AspNetCore#8755]
### Describe the bug
Compiler error: rzc generate exited with code -2147450730

### To Reproduce
1. Using version of ASP.NET Core 3.0 for server component and .Net Standard 2.0 target framework on client, Visual Studio 2019 preview Community
2. Create a 'Blank ASP.net Web project with Blazor'
3. Hit F5
4. See error: rzc generate exited with code -2147450730

### Expected behavior
The default project should have compiled and run.

### Screenshots
![rzcerror](https://user-images.githubusercontent.com/10252438/54862216-69923e80-4d5d-11e9-85fe-3fd9ff23abb3.png)

### Additional context
Include the output of `dotnet --info`

**Comment by raghavendra-udyavar** [comment]
Got the error fixed and working. But not sure exactly what fixed the issue. I did 3 things
1. Downloaded and installed the latest version of .NET Core 3.0
2. Changed the target framework from .Net Standard 2.0 to .Net Standard 2.1, which changed the error to something else.
3. Changed the target framework to .Net Standard 2.0 back again.

It would be great to know from the team which one might have fixed the issue and why?

**Comment by mkArtakMSFT** [comment]
Thanks @raghavendra-udyavar.
Glad that your issue got fixed.
@pranavkm do you have thoughts regarding what may have fixed this?

**Comment by pranavkm** [comment]
The error code indicates that you were missing a version of the .NET Core 3.0 runtime required to run the tool. Perhaps you picked up the Blazor VSIX, but not the preview3 SDK required to build or run the app. The first step (`Downloaded and installed the latest version of .NET Core 3.0`) likely fixed the issue. Feel free to reopen if you continue seeing this issue so we can investigate further.

**Comment by chrisw000** [comment]
I installed the x86 SDK and got this error.
After uninstalling the x86 SDK and installing the x64 SDK the error went away.

**Comment by RaulSebastian** [comment]
> 
> 
> I installed the x86 SDK and got this error.
> After uninstalling the x86 SDK and installing the x64 SDK the error went away.

Had the same issue and this fixed it for me aswell.
