### ISSUE TITLE
[Feature Request] Blazor: Ability to run some components completely on server-side

### ISSUE THREAD

**Issue by RyoukoKonpaku** [aspnet/AspNetCore#8758]
### Is your feature request related to a problem? Please describe.
The ability to run a portion of Components in Blazor as a Razor Component Island which is planned on the roadmap #8214 which targets if I recall only MVC. 

For instance one use-case for this is to run some business logic that you don't want to expose to the client side completely. One example I could think of is the one presented by @danroth27 at NDC for Razor Components wherein they used an ML.NET model to determine sentiment analysis on a text review on every keystroke, but also would like to only restrict these online components on some areas that needs them.

### Describe the solution you'd like
Possibly a directive on the component to determine on what context it will run, I'd assume it should be seamless and easy to switch on both modes.
```
@RuntimeContext Components.ServerSide
```
```
@RuntimeContext Components.ClientSide
```
This should work both ways, Razor Components wanting some areas client-side and Blazor wanting some areas server side.

This would compliment DI as well. Say the component calls `ISomeService.DoSomething()`, when running on a `Blazor` context it would look into the registered service on the `Blazor` IOC container and when running on a `Razor Components` context it would look into the Server container for `ISomeService`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RyoukoKonpaku.
This is not something we plan to do in the near future.

**Comment by honkmother** [comment]
I know this was shot down and closed, but I wanted to add my two cents here: 

I don't know what "near future" is defined as, but if it's a polite way of saying "never" then I want to express that I think a serverside/client runtime context could be extremely valuable for Blazor's long term viability.

I understand keeping track of the DOM differences between both could be haughty but, as OP stated, there are a lot of scenarios Blazor where it doesn't make sense to run certain components on the client or server. This could enable functionalities such as being able to search and filter enumerables acquired from the server locally without any overhead.

I would love to see this implemented at some point in the future to the point where blatant bribery is not out of the question.
