### ISSUE TITLE
Question/Suggestion - Can we do in C# what JS "Service Worker" does in client?

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#8760]
Hello Blazor Team;

Suppose I write a Vue PWA application and I use JS Service Worker to perform background process even if my app is not open in User's browser. For example I could occasionally check with a REST server for certain data, and if I see new one, I can then activate the User's app in the browser.
This is one of the important features of PWA.

First question is, are we going to be able to create PWA apps with Blazor?
If yes, I want to use Blazor Technology (client side), is it possible to use C# to create a similar "Service Worker" functionality (to check with backend server in the background) and notify the Blazor app on the client?

If not, do we create JS Service Workers and then through interops we communicate with C# code in the Web Assembly?

I bring this up at this time, so the team would consider PWA technology as a very important aspect of adopting Blazor.

Thank you in advance
..Ben

**Comment by enetstudio** [comment]
SteveSandersonM:
We're definitely keen to ensure Blazor can be used for PWAs! At the moment it seems like a fairly independent concept, in that you could use Blazor with PWA-type APIs to enable offline support and all the other PWA features, but you could also choose not to.

Eventually we might have some kind of out-of-the-box PWA template though for now we're focused on building the core technology.
Source: https://github.com/aspnet/AspNetCore/issues/5479

Reading:
https://medium.com/@k.l.mueller/create-progressive-web-apps-with-net-using-blazor-6aa719e38000
https://www.nuget.org/packages/RC.Blazor.Hosted.Service.Worker/

**Comment by BenHayat** [comment]
@enetstudio;
Thank you Issac for the reply and providing the info and links. 
Having SteveS as the chief architect of Blazor and knowing his past history, it gives me great confidence in Blazor.

**Comment by mkArtakMSFT** [comment]
Thanks folks. Closing this in favor of the linked issue.
