### ISSUE TITLE
Host vs IWebHost Major performance difference(for the worse)

### ISSUE THREAD

**Issue by guyng** [aspnet/AspNetCore#8763]
### Describe the bug
Using HostBuilder for the new asp.net core 3 has been drastically affecting the web app performance. My web app is running thousands of http requests to external api's every few minutes. Until now i'v been doing background services in a asp.net core 2.2 web api application.
Since preview 3 of asp.net core 3 i'v tried out the new Worker template and i witnessed major performance difference. i'v done lots of bench marking and in all of them the new worker application perform much worse than the usual web api core 2.2 app. 
I found out where is the issue. If i change IHostBuilder to IWebHostBuilder in program.cs 
then the performance is back to normal again. 
my guess is that the new hostbuilder output object isn't as optimized as webhostbuilder object.
Hence, as long as Main running IWebhost built object the performance is great, but, if it is running IHost built object the performance isn't as good.

There is probably more to it but i haven't had the time to dive into asp.net core 3 open source code so i can't tell the exact problem.

Some benchmark i ran: 15 external Http requests , 
with IWebHost it took on average 0.25 ms, 
with IHost it took on average 0.412 ms.

750 external http requests, 
with IWebHost it took on average 3.02 seconds,
with IHost it took on average 13 seconds(major difference)

10,000 external http requests,
with IWebHost it took on average 23.45 seconds,
with IHost it took on average 70 seconds

Looking forward to hear your reply.
Best Regards,

### To Reproduce
1. Using this version of ASP.NET Core 3 preview 3
2. Run Worker template/ web api 
3. Try running some simple benchmarking task(either cpu or IO bound) with IWebHostBuilder in program.cs and measure the time it takes then switch to IHostBuilder and 
4. check the time difference.

### Expected behavior
No performance difference, or, a slightly better performance.

### Screenshots
I'll upload bench marking screenshots if requested.

### Additional context
Include the output of `dotnet --info`

**Comment by benaadams** [comment]
Is it using a different logging level? (i.e. outputting more log data)

**Comment by guyng** [comment]
@benaadams No, it is using the exact same logging settings.

**Comment by guyng** [comment]
@davidfowl any news?

**Comment by davidfowl** [comment]
Can’t think of any thing that would make a difference for web requests. The only thing that should be affected is startup code.

**Comment by Tratcher** [comment]
Agreed, the host layering should have little or no effect on the per-request performance. It would affect configuration, logging, which could have secondary perf effects.

@sebastienros We should covert our benchmarks to HostBuilder anyways to keep them in line with our 3.0 templates/guidance.

**Comment by guyng** [comment]
@Tratcher @davidfowl "It would affect configuration, logging, which could have secondary perf effects."
I ran the exact same web app with the **same** log settigs, app.settings,startup code,libraries,etc etc..
the **only** difference was using IHostBuilder in contrast to IWebHost and then i was able to reproduce the perf differences. i ran it thousands of times and the result was the pretty much the same, so, as you've mentioned, there may be secondary effects that are causing these perf diff. If the hostbuilder has different  configurations/logging settings then you should dig in what exactly may cause this perf issue because otherwise i see no reason of using the new template.

**Comment by guyng** [comment]
Any news yet? I really hope this issue will be sorted out in one of the next preview's. 
If you weren't able to reproduce this perf issue, i can upload & link a sample demonstration project.
I'm an early adopter type of person so my goal is to use asp.net core 3 on my live app right when it's out but only if these issues will be sorted out beforehand.

**Comment by Tratcher** [comment]
Yes, please share your two apps, (before and after). Our initial measures didn't show any difference.

**Comment by guyng** [comment]
Okay, so on my sample projects doing ordinary http requests to a list of random api's, the results show the same performance for both web api and worker project. But, on my real product app projects it actually shows great difference(even tho they use the exact same code & dlls) so i need to investigate and dive deeper to find if it's actually because of the worker service or may be something else.
I'll do it during the weekend and update here if i got any insights.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
