### ISSUE TITLE
[Blazor 0.9.0] does not accept accents in the component parameters

### ISSUE THREAD

**Issue by eglauko** [aspnet/AspNetCore#8766]
### Describe the bug
When I have a component with a string parameter, when passing a string with an accent, for example: "Início", the accented character is replaced by "?".

### To Reproduce
I'm using the component this way
`<AsideItem active="true" text="Início">`
The browser appears as follows
In�cio

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @eglauko.
@javiercn, can you please investigate this? Thanks!

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb  can you please confirm this is fixed already? Thanks

**Comment by ajaybhargavb** [comment]
Yup. I can no longer reproduce it. @eglauko, please re-open if you are seeing this issue in the latest version.

**Comment by eglauko** [comment]
Hi @ajaybhargavb.
In preview 5 the error continues.
You can see it in this project: https://github.com/eglauko/Blazor.Chat

![image](https://user-images.githubusercontent.com/8996206/58676337-50de7000-832e-11e9-8de3-5df95437c23a.png)
![image](https://user-images.githubusercontent.com/8996206/58676376-7a979700-832e-11e9-9fa0-c0ac0b57fd86.png)

**Comment by rynowak** [comment]
@eglauko - do you know what encoding your file is using? Is it saved as UTF8?

Do you have a repro project we could try out?

**Comment by eglauko** [comment]
Eu não sei onde posso ver o encoding, mas deve ser o padrão do visual studio 2019.
Quando eu utilizo uma palavra com um acento como text do html funciona, o problema só ocorre quando é um parâmetro de componente.
Eu acho que o erro ocorre durante a geração do método BuildRenderTree

You can see it in this repro project: https://github.com/eglauko/Blazor.Chat

**Comment by eglauko** [comment]
This way it works
![image](https://user-images.githubusercontent.com/8996206/58677996-73738780-8334-11e9-931a-4f5e63dc2738.png)

![image](https://user-images.githubusercontent.com/8996206/58677970-5939a980-8334-11e9-9a8d-d2ba27832413.png)

**Comment by vdandrade** [comment]
Same problem here. I have a lot of projects that works with UTF8, only in Blazor project we get this errors.

**Comment by mkArtakMSFT** [comment]
This should be fixed already as part of https://github.com/aspnet/AspNetCore/issues/11435
