### ISSUE TITLE
Blazor template was not showing on VS 2017 15.9.9 and VISX error. 

### ISSUE THREAD

**Issue by redar84** [aspnet/AspNetCore#8767]
After I installed the VS2017 15.9.9 I tried to install the Blazor template through NuGet package manager. However, the search did not show the template, so I went to the website and downloaded VISX. I run the installation I got this error.
![Capture](https://user-images.githubusercontent.com/10550117/54875058-69c62480-4dc5-11e9-8b36-7fd225210920.PNG)

I reinstall the VS2019 and the same error popped up. What I did, I copied the Blazor template folder from my old surface which runs VS2017 and pasted in the same path inside my new laptop. I started VS2015 and I saw the template back. however, I got this error message :
![Capture1](https://user-images.githubusercontent.com/10550117/54875190-08ec1b80-4dc8-11e9-8692-af655cef292b.PNG)
I tried to uninstall and reinstall since it is shown inside my package manager, again I got VISX error message that made me unable to remove it. Then I reopened package manager and stopped the Roaming. 
![Capture2](https://user-images.githubusercontent.com/10550117/54875209-726c2a00-4dc8-11e9-9ec7-448cb4ce65b3.PNG)
Currently, I am getting three templates under the Core 2.1 and I run a demo app which worked fine. 
inside the Blazor folder, I have 
Templates.pkgdef => [$RootKey$\TemplateEngine\Templates\Blazor\0.2.0]
"InstalledPath"="$PackageFolder$\ProjectTemplates"
ProjectTemplate => Microsoft.AspNetCore.Blazor.Templates.0.7.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us,  @redar84.
The Blazor project template requires VS 2019. It sounds like you have some issues with the actual VS installation. I'd recommend to repair it, and then try to reinstall Blazor extension again.
