### ISSUE TITLE
New '3.0.0-preview3-19153-02' does not work when published to Azure WebApp

### ISSUE THREAD

**Issue by BitProgress** [aspnet/AspNetCore#8774]
It is not possible to deploy the default Razor Components app to Azure WebApp using the latest AspNetCore '3.0.0-preview3-19153-02'.

![image](https://user-images.githubusercontent.com/12260741/54902937-f282b480-4eda-11e9-8767-bae83961c806.png).

I am using the deployment mode 'Self-Contained'.

The App does appear, but the SignalR is not working, and no clicks are handled...

How do I figure out what is wrong?

Thanks
Martin

**Comment by xclud** [comment]
Is it serving on HTTPS? Is the SSL certificate valid?

**Comment by BitProgress** [comment]
Yes, it is serving via HTTPS and the certificat is valid.
The exact same WebApp "instance" worked when I deployed a "preview" version.
But "preview3" does not work.
I will try to disable the https just to see, if it makes a difference...

**Comment by BitProgress** [comment]
I think that something changed regarding WebSockets.

I just saw, that the WebApp was configured NOT to use WebSockets.
After changing that setting:
![image](https://user-images.githubusercontent.com/12260741/54905252-df72e300-4ee0-11e9-86d6-07a1c119eb5b.png)
It worked.
But it has worked before, even though the WebSockets was disabled in the WebApp.

Perhaps someone knows, if the application (Razor Components) is - or should - be able to override that setting?

**Comment by BrennanConroy** [comment]
>if the application (Razor Components) is - or should - be able to override that setting?

No.

>But it has worked before

I'm assuming it worked in a previous preview version? There was a change recently in Components that broke the fallback of SignalR. So when it worked before it was most likely using LongPolling. But is now failing to use LongPolling. A change went in last week to fix this, and should be available in the next preview or nightly bits.

**Comment by BitProgress** [comment]
@BrennanConroy 
Yes, it worked in the previous version.
I will definetly want the WebSocket enabled.
I did see, that LongPolling was not working properly, and that explains what I have seen.
I will close this issue.
Thanks!
Martin
