### ISSUE TITLE
ASP.NET Core 3 Preview 3 authorization does not work with Identity

### ISSUE THREAD

**Issue by bhrugen90** [aspnet/AspNetCore#8785]
### Describe the bug
Authorize keyword does not work with register page (I have a requirement in which I only want authorized user to access the register page, since I will create user through seeding database).

### To Reproduce
1. Using this version of ASP.NET Core 3 preview 3
2. Create a project with Identity Autentication level (MVC Project) and update database to push migrations.
3. Scaffold existing item and then add identity pages, and use dbcontext already created.
4. Change authorization level from anonymous to [Authorize] at register page model.
5. Run the project and you are still able to access the page without logging in.

### Expected behavior
It should redirect to login page when i click register page, since only authorized user should be able to see that page.

### Screenshots
![image](https://user-images.githubusercontent.com/20101947/54935937-5b742780-4eef-11e9-8997-d3c9f486b5df.png)

### Additional context
Include the output of `dotnet --info`

**Comment by marquish** [comment]
Sorry, but why would you need authorization on a Model ?
It is generally applied in Controller isn't it ?

**Comment by blowdart** [comment]
Razor Pages authorization works [differently](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-2.2). However Identity is already telling Razor that register should be anonymous, so overriding that may be problematic.

I know it doesn't fix the problem, but what's the scenario where you want an already logged in user to be able to create a new account?

**Comment by bhrugen90** [comment]
In my scenario I do not want end user to be able to register to the website, only an Admin account could be registered and they cannot register directly, an existing admin can only create account for other employees/admin user.
So if an anonymous user wants to access the page by typing in the url they should be redirected to the login page and they cannot register.

**Comment by bhrugen90** [comment]
I have a workaround in which I can check in the razor Page is the User.IsInRole and if not I display a blank page, but wanted to bring the issue to picture.

**Comment by blowdart** [comment]
Given your scenario is rather outside the scenarios we've aimed identity at I don't think this is something we'd look at fixing. In your case I'd suggest going further, and just returning forbidden for everyone, and moving new user creation to a new page/URL.
