### ISSUE TITLE
AspNetCore 2.1 LTS - No CORS headers sent in case of error 500

### ISSUE THREAD

**Issue by DanielHabenicht** [aspnet/AspNetCore#8789]
### Describe the bug
Bug is described at #2378

### Expected behavior
This Bug should be fixed in the LTS Version of AspNetCore (2.1)

### Additional context
We are currently using AspNetCore 2.1, because it is LTS.
We can't update because other versins are not LTS.
This way we can't get the fix from #2378.

**Comment by Eilon** [comment]
Hi @DanielHabenicht , to request support with an LTS product, please contact Microsoft Support at https://support.microsoft.com/. Otherwise, I believe the issue was fixed in ASP.NET Core 2.2.
