### ISSUE TITLE
CS0246 error in a razor view points to a generated file (.g.cshtml.cs) instead of the actual view (.cshtml)

### ISSUE THREAD

**Issue by yepeekai** [aspnet/AspNetCore#8790]
If your rename a model used in a razor view (.cshtml) The build output will display an error but for a generated file (.g.cshtml.cs) instead of displaying it for the actual source (.cshtml)  It is not possible to double click on the error to see the source.

### To Reproduce
1- Rename the class for a model used in a view
2- Compile

### Expected behavior
The error should be listed in the output window and in the error window and the error must be correctly linked to the view source file  Views\SomeController\SomeView.cshtml

### Actual behavior
The error is listed but is linked to a generated cs file: obj\Debug\netcoreapp2.2\Razor\Views\SomeController\SomeView.g.cshtml.cs
I have tested this behavior in both VS2017 15.9.9 and VS2019 RC.3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @yepeekai.
@ajaybhargavb, will this be covered by https://github.com/aspnet/AspNetCore/issues/6373?
If yes, feel free to close this issue as a dupe.

**Comment by ajaybhargavb** [comment]
@mkArtakMSFT it is related to that because this happens due to a lack of line mappings. But this is not components related. The fix will be different.

**Comment by mkArtakMSFT** [comment]
We're closing this as there isn't anything we can do about this with small investment.
