### ISSUE TITLE
How to diagnose runaway thread in production causing 100% CPU?

### ISSUE THREAD

**Issue by jarrettv** [aspnet/AspNetCore#8791]
I have an app running in Azure App Service as a docker container and I keep having issues with 100% CPU usage. The app may run fine for 10 minutes to 4 days until this issue happens. I then need to restart to fix it.

At 100%, I get issues with oauth logins and you can tell an increase in latency. However, the app continues to handle requests.

### Questions

Is it possible to have the runtime kill a thread after some timeout occurs and then log that as an error?

Is there an easier way to diagnose this problem?

Should the runtime prevent this from happening?

### More details

Things I've tried:
* Update from 2.1 to 2.2
* `UseLibuv()`
* Disable signalR
* Fix all Html.Partial to async Html.PartialAsync
* Disable ApplicationInsights
* Using HttpClientFactory via AddHttpClient

Things I have yet to try:
* Turn on debug logging
* Correlation of CPU spike with log entries

The debug logging and manual correlation will likely be labor intensive which why I haven't tried them yet.

For the record, I did find a bug in my code causing an endless loop. 😳 But I found this by chance. 🤷

Hopefully that fixed it 🤞

![image](https://user-images.githubusercontent.com/219295/54942720-abf28180-4efd-11e9-9937-5a6e0f1bfdd5.png)

**Comment by Eilon** [comment]
Killing random runaway threads is a sure way to make an app have unexpected, and potentially dangerous behavior. The only safe thing to do is to kill the entire process.

Having said that, tagging @sebastienros who might have some suggestions on how to diagnose these types of issues.

**Comment by effyteva** [comment]
+1
