### ISSUE TITLE
Produce a SignalR 'dotnet new' template

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8802]
@bradygaster is driving this work but the team needs to provide feedback.

**Comment by anurse** [comment]
Has anyone reviewed this? @halter73 @mikaelm12 @BrennanConroy ? @bradygaster can you link to the template here, if it's ready for review?

**Comment by bradygaster** [comment]
@anurse yes - @halter73 provided feedback and i respectfully didn't agree with @BrennanConroy's feedback, but that is primarily because i think `BackgroundService` is like, the second coming and we should make a bigger deal about it. 👍

**Comment by rynowak** [comment]
I am here to say that this is dope.

**Comment by anurse** [comment]
That's basically your job, right? 😝

**Comment by rynowak** [comment]
It's the best way I know how to add value.

**Comment by anurse** [comment]
If the template isn't coming in actual template form until EOW, this won't land in time for preview4. Moving to preview5

**Comment by anurse** [comment]
Pre-triage notes:
* Seems valuable for preview5.
* If this is going to land for preview5, we need a templating PR by 4/12.

**Comment by anurse** [comment]
Triage decision: Keeping it in, let's try to get this in for preview 5.

**Comment by anurse** [comment]
Bumping to preview 7 since we're still chugging on it.

**Comment by bradygaster** [comment]
After discussing this with @halter73 @davidfowl and more, we should scrap this. One suggestion was an OOB template set that would satisfy some of the use-case scenarios Zhidi and the others in the Azure SignalR Service team have struggled to satisfy. Suggestion was to try this out as an experiment to see if the community responds to having "starting points" for some of the canonical scenarios (chat, geo-placement of active connections, etc.). We can close this issue (leaving for triage/milestone review).
