### ISSUE TITLE
Increase Gradle max retries and backoff

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8804]
See https://github.com/aspnet/AspNetCore-Internal/issues/2052 and https://github.com/gradle/gradle/commit/156b5ebd00971cc7fd6bd94420f0fa63b5488e8d for some context here.

Gradle is timing out in some of our builds. It has retries but they seem to be insufficient for our needs. However, there are internal Gradle properties that allow this to be controlled. We should increase the number of retries and possibly the backoff as well to make our build more reliable.

- `org.gradle.internal.repository.max.retries` (default 3) is the number
of retries (initial included)
- `org.gradle.internal.repository.initial.backoff` is the initial time
before retrying, in milliseconds (default 125)

**Comment by mikaelm12** [comment]
Helpful note from AzDo docs actually
>How do I fix timeouts when downloading dependencies?
To fix errors such as Read timed out when downloading dependencies, users of Gradle 4.3+ can change the timeout by adding to Options `-Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000`. This increases the timeout from 10 seconds to 1 minute.

**Comment by anurse** [comment]
Awesome!

**Comment by mikaelm12** [comment]
So after some investigation through github issues and old prs and scanning release tags, the version of gradle we use **does not have retries**. So I'll work on upgrading the version of gradle we use to take advantage of the new feature.

**Comment by anurse** [comment]
This is blocking some builds fairly frequently. Can you make this your top priority @mikaelm12 ?
