### ISSUE TITLE
Build targeting pack pkg installers for macOS

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#8806]
Looks like we are not building these. Currently we are building the msi, deb, rpm only.

**Comment by dougbu** [comment]
Thanks for making this easy to track @JunTaoLuo

**Comment by dougbu** [comment]
@johnbeisner we're trying to decide on the priority and urgency of this issue.
1. What will the user experience be when this one targeting pack is missing in a release?
2. Is the macOS targeting pack mandatory for the next VS for Mac insertion?
3. Is the macOS targeting pack mandatory for the go-live preview release (the one we may need to patch)?
4. Is the macOS targeting pack mandatory in 3.0.0-preview4 for some reason?

**Comment by johnbeisner** [comment]
Ideally we would like to be done with SDK Target Pack authoring before 3.0.0 Preview 4 moves into its next phase.
@leecow 
Can you answer @dougbu questions from a release perspective.

**Comment by leecow** [comment]
1. I presume there would be some unexpected behaviors if the targeting pack were missing but someone would need to verify
2. Don't know - you'll need to as the VS for Mac folks what their expectation are.
3. Targeting packs should be in for Preview 5 at the latest. However, given the amount of work we'll have heading into that release it may be nice/wise to complete in Preview 4 if the work fits
4. No

**Comment by dougbu** [comment]
@mkArtakMSFT do you now have enough info to decide on the priority and milestone?

**Comment by johnbeisner** [comment]
We are implementing a work-around for the ASP.Net Targeting Packs
https://github.com/dotnet/core-sdk/pull/1173
 - copy the ASP.Net Targeting Pack to the internal layout with the ASP.Net Runtime

**Comment by Eilon** [comment]
Given that we have a workaround, moving the rest of this to preview6.

**Comment by natemcmaster** [comment]
Closing as "won't fix". Our understanding of the installer plan for macOS is that we currently only want the latest targeting pack included in the SDK's pkg installer. NuGet will be used to acquire targeting packs that are not bundled with the latest SDK.
