### ISSUE TITLE
Why Request.Body has to be read? if not 502.3 is returned

### ISSUE THREAD

**Issue by s-krawczyk** [aspnet/AspNetCore#8808]
I have a strange behavior on IIS that is hosting Kestrel ASPNetCore app. I am sending body that is multipart with file of size around 150MB. In controller code we decide by accesing headers if body should be processed or not. There are situations in which we are not reading request body but returning specific status code. In FREB logs I see that IIS returns 502.3 and it really comes. But in .NET Core code (logs) I see it was set to our desired http status code. What is going on under the hood that ANCM changes it to 502.3?? I have wasted a lot of time and figured out how to really fix this but this is not acceptable from my perspective. Reading whole body to Stream.Null solves the issue. But really why I have to do it if I really will not use this data?

**Comment by Tratcher** [comment]
Short answer: Use 2.2's new IIS In-proc support to avoid this error.

When you're not going to consume the request body the server tries to drain the body so it can continue re-using the connection. There's a limit to how much it's willing to try draining (5 seconds?), after which it closes the connection. In the ANCM reverse proxy scenario the error from closing the connection is reported with a higher priority than the normal response. The simplest solution is to avoid the reverse proxy configuration by using the new in-proc support.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
