### ISSUE TITLE
[Tooling] Update .NET SDK

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#8809]
AspNetCore-Tooling can already consume a new SDK but is blocked by AspNetCore acquiring a new SDK (if we checked toolings update in it'd break the build). The motivations behind getting a new SDK is to update these two files to use `preview` as the `LangVersion` instead of `8.0`. The current SDK that we're pinned to doesn't understand `preview` which is the root of the problem:

- https://github.com/aspnet/AspNetCore-Tooling/blob/9f929e6fffe2c89d8f28d4d599c57f2988301e56/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets#L117
- https://github.com/aspnet/AspNetCore-Tooling/blob/9f929e6fffe2c89d8f28d4d599c57f2988301e56/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets#L181

@rynowak here's the issue we'll use to ensure the SDK in AspNetCore-Tooling is updated once AspNetCore can.

@anurse assigning to you for now so you can re-assign to ensure both SDK updates go in for preview4.

**Comment by anurse** [comment]
Assigned @jkotalik just to get the ball rolling. When it's moving, ping back here and I'll find someone to help drive things to green and checked in. It's likely to be targetting pack/runtime/etc.-related so we'll probably need some support from @JunTaoLuo here :).

**Comment by jkotalik** [comment]
Sdk is updated!

**Comment by NTaylorMullen** [comment]
@jkotalik it got updated in the AspNetCore-Tooling repo as well? (asking because that's what this issue is for)

**Comment by jkotalik** [comment]
My bad, yes it looks like it hasn't been updated in tooling.

**Comment by Eilon** [comment]
@NTaylorMullen / @jkotalik - this bug is still in preview4. What action needs to be taken, and when?

**Comment by anurse** [comment]
What updates it in Tooling? Is that not automated? Sorry, I missed that this also needed to go in to Tooling.

**Comment by NTaylorMullen** [comment]
@pranavkm is working on this now. Re-assigned.

**Comment by pranavkm** [comment]
Resolved in https://github.com/aspnet/AspNetCore-Tooling/pull/413
