### ISSUE TITLE
File changes to page models (c# files) are not doing anything when reloading razor pages in browser

### ISSUE THREAD

**Issue by spacecat** [aspnet/AspNetCore#8810]
### Describe the bug
File changes to c# files (.cs) isn't doing anything when reloading razor page in browser (F5).

### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Create a default Razor Pages web app using ASP.NET Core 2.2.
3. Create a string property in pagemodel class. Assign it a value.
4. Add the property to the index.cshtml razor view
5. Ctrl + F5
6. Make a file change in index.cs
7. Reload browser

### Expected behavior
The file change from point 6 should be reflected when refreshing the page in the browser

### Additional context
Manually compiling (ctrl + shift + b) and then refreshing the page works as expected

I tested the same but with the 2.1 asp.net core razor page template and changes to c# files are reflected as expected.

Not sure if these are related:
https://github.com/aspnet/AspNetCore/issues/4567
https://github.com/aspnet/AspNetCore/issues/8140

**Comment by jkotalik** [comment]
This is a known issue with the new InProcess hosting model with IIS. We are actively working on fixing it. To fix your issue, in your `csproj`, change the value of AspNetCoreHostingModel from `inprocess` to `outofprocess`.

@BillHiebert let's sync soon to figure out E2E for this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
