### ISSUE TITLE
[SignalRCore] User.Identity.Name is null, with JWT authentication

### ISSUE THREAD

**Issue by btbensoft** [aspnet/AspNetCore#8812]
### Describe the bug
On my signalR Hub context, the User.Identity.Name is empty. Bellow you can see all details :

### Client side SignalR hanshake User.Identity.Name

```
//urlSignalR example : https://localhost:44396/enginehub?token=eyJhbGciOiJIUzI1NiIsInR5cCI.........
this._hubConnection = new HubConnectionBuilder().withUrl(urlSignalR).build();  

this._hubConnection.onclose(() => this.Reconnect());

//Start connection to signalR
this.StartConnection();
```

### Startup.cs
```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.Audience = audienceId;
                    options.ClaimsIssuer = serverAuth;
                    options.TokenValidationParameters = tokenValidationParameters;
                    options.Events = new JwtBearerEvents
                    {
                        OnMessageReceived = context =>
                        {
                            if (context.Request.Query.TryGetValue("token", out StringValues token))
                            {
                                context.Token = token[0];
                            }

                            return Task.CompletedTask;
                        },
                        OnAuthenticationFailed = context =>
                        {
                            var catchException = context.Exception;
                            return Task.CompletedTask;
                        }
                    };
                });
```

### Screenshots on the hub context
![image](https://user-images.githubusercontent.com/36570423/54978182-d0069f00-4f9f-11e9-91dc-0739ae65a522.png)

### Additional context
If i call my API with bearer authentication i can get my user claims on my controller. My problem is only on the SignalR Hub.

Other information, is look like when SignalR connecting i did not pass on the **OnMessageReceived** function (startup)

The connection with signalR handshake is working :
![image](https://user-images.githubusercontent.com/36570423/54978566-01339f00-4fa1-11e9-8372-5575e0ee953c.png)

Can you help me to get my user claims on the signalR context?

**Comment by davidfowl** [comment]
Is UseAuthentication before UseSignalR in your Configure method?

**Comment by btbensoft** [comment]
> Is UseAuthentication before UseSignalR in your Configure method?

2 hours debug for the wong function position on my configuration.

Thanks David :)
