### ISSUE TITLE
Component Dispose() not called in sync context of renderer

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#8816]
This is the underlying cause of https://github.com/aspnet/AspNetCore/issues/8814

When a component is disposed normally during the ongoing lifetime of a circuit (e.g., because the user took an action causing the component to be removed from the current UI), we call `Dispose` on that component, and the call is correctly within the sync context of the renderer.

However, during **evicted circuit disposal** and after **prerendering** (so arguably this is two separate bugs), we dispose the entire `Renderer` which in turn calls `Dispose` on all the disposable components currently attached to the renderer. Unfortunately these `Dispose` calls are *not* in the renderer's sync context, so if they trigger any logic that requires this sync context, you get a pretty weird error.

Expected fix: for both post-prerendering and evicted-circuit-disposal, we should take care to ensure that component disposal runs on the renderer's sync context.

**Comment by javiercn** [comment]
I believe this was fixed. The circuithost now disposes the renderer within the sync context. Which in turn disposes the components:
https://github.com/aspnet/AspNetCore/blob/master/src/Components/Server/src/Circuits/CircuitHost.cs#L281
