### ISSUE TITLE
Routing error in ASP.NET Core 2.1 Web API when running on Ubuntu via Systemd

### ISSUE THREAD

**Issue by AndyBhag** [aspnet/AspNetCore#8821]
Hi,

I am running a ASP.NET Core 2.1 Web API on Ubuntu. When i run it directly from the folder using "dotnet app.dll" it works fine. However when I try to run it wrapped in a systemd I get a routing error.

The config I have is , I have Nginx which  for request to port 80 serves Angular files , and for any url with /api in it, forwards the request to Kestrel.

**Comment by AndyBhag** [comment]
![StandaloneRun-Success](https://user-images.githubusercontent.com/48953915/55007189-fe6a9580-5004-11e9-8a33-d8b0c6446e65.png)
![Systemd-Fail](https://user-images.githubusercontent.com/48953915/55007207-0591a380-5005-11e9-9ca6-8e7198990bcc.png)

**Comment by AndyBhag** [comment]
Closed by mistake., re-opening

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
