### ISSUE TITLE
Razor Components - Intellisense error when using EventCallback<T> of a component of a different project

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#8822]
### Describe the bug
When consuming a component from an other project (e.g. blazorlib), using an exposed `EventCallback<T>` parameter, the following intellisense error appears (code compiles and runs normally):

```
Error CS1503 Argument 1: cannot convert from 'method group' to 'EventCallback<...>'
```

### To Reproduce
1. Create a blazor lib and add the following component
MyButton.razor
```
<button onclick="@OnClickInternal">My Button</button>

@functions{
    public class MyParams
    {
        public string SomeProperty { get; set; }
    }

    [Parameter] EventCallback<MyParams> OnClick { get; set; }

    async Task OnClickInternal()
    {
        if (OnClick.HasDelegate)
        {
            await OnClick.InvokeAsync(new MyParams());
        }
    }
}
```

2. Create a blazor app and reference/consume the `MyButton` component like so:
```
<MyButton OnClick="@MyButtonClick"></MyButton>
@functions{
    void MyButtonClick(TestEvents.Shared.MyButton.MyParams e)
    {

    }
}
```

3. See error

### Screenshots
![image](https://user-images.githubusercontent.com/12549761/55003698-89d22f80-4fe1-11e9-9a09-78b754afcd34.png)

### Additional context
Aspnet core 3.0 preview 3
Visual studio 2019 preview 4.3

**Comment by rynowak** [comment]
Hi @stavroskasidis - this was a known issue with preview 3. This is fixed in the next release.

**Comment by eddyekofo94** [comment]
I am getting this error dotnet core 3.

**Comment by cbrit** [comment]
I updated to the latest ASP .NET Core 3.0 today and am getting the same error.

**Comment by eLPe21** [comment]
I've got the same with 3.1 preview on Mac Os 

![image](https://user-images.githubusercontent.com/34479304/69677297-7c9ea080-109a-11ea-8d12-def939b3a2a6.png)

**Comment by IvNen** [comment]
I had a similar issue and noticed that when I remove the parameters in the defined method it accepts it. 

![image](https://user-images.githubusercontent.com/35492007/71314280-26c0dc80-243d-11ea-8550-fa7aae7cd3c8.png)
