### ISSUE TITLE
New Overload: DataProtectionProvider.Create(appName, setupAction)

### ISSUE THREAD

**Issue by Aculeo** [aspnet/AspNetCore#8823]
I'm currently facing the following problem: We have an app that runs on an Azure, and I want to extend the DP key lifetime. Right now I only provide an *appName* in order to create a DP provider:

    DataProtectionProvider.Create(appName)

But if I understand correctly we need to add a *setupAction* to extend the key lifetime. However, this only works with the overload where I'm forced to provide a *keyDirectory* instead of an *appName*.

    DataProtectionProvider.Create("keyDirectory", x => x.SetDefaultKeyLifetime(TimeSpan.FromDays(365)))

The problem I have with this: I have to specify the directory even though the logic exists in ASP.NET to pick a directory for me, depending on the platform, just because I want to extend the key lifetime. And on top of this, it is not clear to me just how to even determine what the path is on Azure, since I have no visibility into the file system. FTP doesn't give me full paths.

### Solution I'd like

It would be nice to have an overload that lets me specify a *setupAction* and just an *appName*.

    DataProtectionProvider.Create(appName, x => x.SetDefaultKeyLifetime(TimeSpan.FromDays(365)))

If this is not an option, having a simple way to use the default path on Azure would be nice, so I don't have to go through the headache of figuring it out.

**Comment by blowdart** [comment]
Is this outside of an asp.net core app then? Because inside asp.net core you can happily do

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddDataProtection()
        .SetDefaultKeyLifetime(TimeSpan.FromDays(14));
}
```

**Comment by Aculeo** [comment]
Ah, should've mentioned that. I guess the app is mixing things unfortunately. It's an Asp.NET Web API / OWIN app with custom DI (Autofac), so no `ConfigureServices()` I'm afraid:

```csharp
[assembly: OwinStartup(typeof(Foo.Startup))]
namespace Foo
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var configuration = new HttpConfiguration()
            {
                IncludeErrorDetailPolicy = IncludeErrorDetailPolicy.Always
            };
            AutofacConfig.Configure(configuration);
            app.UseAutofacMiddleware(AutofacConfig.Container);
            app.UseWebApi(configuration);
            [...]
        }
    }
}
```

**Comment by blowdart** [comment]
Ah. The back compat piece is as simple as it can possibly be, it's not meant to be a long term solution so it's not something we really want to add features to.

**Comment by Aculeo** [comment]
Not ideal I guess, but I decided to just copy the logic for determining the key directory based on the environment. I'll leave the code here in case someone else wants to do the same.

```csharp
/// <summary>
/// Returns the key storage directory for ASP.NET data protection mechanism.
/// Creates the directory if it does not exist yet.
/// </summary>
private static DirectoryInfo GetKeyStorageDirectory()
{
    try
    {
        var directoryInfo = GetKeyStorageDirectoryBasedOnEnvironment();
        directoryInfo.Create();
        return directoryInfo;
    }
    catch
    {
        return null;
    }
}

/// <summary>
/// Get the key storage directory based on the current environment.
/// </summary>
private static DirectoryInfo GetKeyStorageDirectoryBasedOnEnvironment()
{
    string appPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
    string localAppDataPath = Environment.GetEnvironmentVariable("LOCALAPPDATA");
    string userProfilePath = Environment.GetEnvironmentVariable("USERPROFILE");
    string homePath = Environment.GetEnvironmentVariable("HOME");

    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && !string.IsNullOrEmpty(appPath))
        return GetKeyStorageDirectoryFromBasePath(appPath);

    if (localAppDataPath != null)
        return GetKeyStorageDirectoryFromBasePath(localAppDataPath);

    if (userProfilePath != null)
        return GetKeyStorageDirectoryFromBasePath(Path.Combine(userProfilePath, "AppData", "Local"));

    if (homePath != null)
    {
        return new DirectoryInfo(Path.Combine(homePath, ".aspnet", "DataProtection-Keys"));
    }

    if (string.IsNullOrEmpty(appPath))
        return null;

    return GetKeyStorageDirectoryFromBasePath(appPath);
}

private static DirectoryInfo GetKeyStorageDirectoryFromBasePath(string basePath)
    => new DirectoryInfo(Path.Combine(basePath, "ASP.NET", "DataProtection-Keys"));
```
