### ISSUE TITLE
SignalR: Template for new protocol

### ISSUE THREAD

**Issue by MagicAndre1981** [aspnet/AspNetCore#8824]
### Is your feature request related to a problem? Please describe.

I'm am trying to use a different protocol, but I currently there are only Json/MessagePack available, so I plan to experiment with my own (maybe XML and nothing json related).

### Describe the solution you'd like

I want a template in VS2017/2019 where I can easily create a new SignalR protocol.

### Describe alternatives you've considered

currently I think of cloning current code, copy current code to new repository, rename it and check all current methods and replace the implementation and hope the protocol later works.

But which functions do the protocols have to support?

**Comment by BrennanConroy** [comment]
I don't think we would make a VS template for this. It's not a common enough scenario to warrant one.

We do have an issue filed for making a doc around this though. https://github.com/aspnet/Docs/issues/10861

The protocol needs to implement [IHubProtocol](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/common/SignalR.Common/src/Protocol/IHubProtocol.cs) and be injected into DI.

**Comment by MagicAndre1981** [comment]
> We do have an issue filed for making a doc around this though. [aspnet/Docs#10861](https://github.com/aspnet/Docs/issues/10861)

ok, hopefully the documentation is finished soon.
