### ISSUE TITLE
[Epic] ASP.NET Core servers should support exposing a Pipeline-based request/response body API

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8829]
All our servers should evaluate how to best expose a pipeline-based API for request/response bodies.

Child Items:
* ~~https://github.com/aspnet/AspNetCore/issues/8661 Add Pipelines-related http features in IIS~~ (Cut, want to wait to align with corefx plans to unify pipes and streams)
* ~~https://github.com/aspnet/AspNetCore/issues/8660 Add Pipelines-related http features in TestServer~~ Postponed
* ~~Add Pipelines-related http features in HttpSysServer~~ (Cut, it doesn't really provide value and we already have a wrapper feature to allow consumers to use the API)
* ~~https://github.com/aspnet/AspNetCore/issues/4344 Cleanup remaining issues in StreamPipeReader/StreamPipeWriter~~ Reframed and opened a new issue.
* ~~https://github.com/aspnet/AspNetCore/issues/7868 Implement Multi-part readers with Pipelines~~ Moved to 3.1
* ~~https://github.com/aspnet/AspNetCore/issues/8165 Create a BufferedPipeReader~~ Postponed
* ~~https://github.com/aspnet/AspNetCore/issues/7836 Reimplement HttpRequestStreamReader and HttpResponseStreamWriter with pipes~~ Postponed
* ~~https://github.com/aspnet/AspNetCore/issues/7604 API Proposal: Exposing the upgraded stream as an IDuplexPipe~~ (Cut due to missing corefx alignment)
* [x] https://github.com/aspnet/AspNetCore/issues/9223 Pipelines in ASP.NET Core 3.0

**Comment by anurse** [comment]
@jkotalik @Tratcher to see if there are any other things that relate to this work. Just tag them here if you think they are relevant.

**Comment by anurse** [comment]
Re ^

Not the biggest fan of how GitHub reports me editing @jkotalik 's issue to include a link to the epic...

**Comment by Tratcher** [comment]
Link in the completed Kestrel work for reference?

**Comment by anurse** [comment]
In a perfect world, sure, but I don't really know what query would get me that information at the moment...
