### ISSUE TITLE
ServiceFilterAttribute causes stackoverflow exception in 2.2

### ISSUE THREAD

**Issue by ericcoleman** [aspnet/AspNetCore#8831]
### Describe the bug
In Asp.Net Core 2.2, when trying to execute a filter that extends `ServiceFilterAttribute` and implements `IAsyncActionFilter` a stackoverflow exception is thrown. This previously had worked in 2.1. 

### To Reproduce
1. Create a .Net Core 2.2 Web Application
2. Create an Attribute Class that extends `ServiceFilterAttribute` and implements `IAsyncActionFilter`
3. Add the attribute using the Service Filter `[ServiceFilter(typeof(SampleFilter))]` to a Controller
4. Start the App and try to hit the endpoint. 

I've duplicated this issue in this [repo](https://github.com/ericcoleman/DotnetSandbox) with a failing [integration test](https://github.com/ericcoleman/DotnetSandbox/tree/master/IntegrationTests). 

### Expected behavior
The attribute to execute without exception.

### Screenshots
![image](https://user-images.githubusercontent.com/5933413/55021204-bc266180-4fce-11e9-9256-a6ff1b6a17b8.png)

### Additional context
Duplicated on both Windows and OS X
```.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.0.2 [/usr/local/share/dotnet/sdk]
  2.1.105 [/usr/local/share/dotnet/sdk]
  2.1.300-rc1-008673 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.402 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ericcoleman.
This is not a recommended way to do it:
> Create an Attribute Class that extends ServiceFilterAttribute and implements IAsyncActionFilter

Instead you should implement the `IFilterFactory` interface.
