### ISSUE TITLE
Prerendering support for Blazor

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#8842]
We enabled prerendering support for Razor Components, but we need to do some work to make the experience good for Blazor apps. Prerendering for Razor Components is based on a Razor Page, but the UseBlazor method currently calls UseSpa which requires an index.html file be present.

**Comment by SteveSandersonMS** [comment]
Can we close this in favour of #8852, since that is more specific about the planned solution?

**Comment by danroth27** [comment]
Sounds good to me.
