### ISSUE TITLE
Automate acquisition of latest SDK

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#8845]
Depends on: https://github.com/dotnet/arcade/issues/811

We're doing a one-off here: https://github.com/aspnet/AspNetCore-Internal/issues/2001, PR: https://github.com/aspnet/AspNetCore/pull/8670

And we should automate it with maestro once the Arcade issue is fixed.

**Comment by natemcmaster** [comment]
This was implemented by Arcade. No action required on our end to take advantage of automated SDK updates.

Arcade will only update the SDK to a higher minimum version, but it won't give us regular SDK updates. Arcade is intentionally keeping the minimum version set to an LKG version that works in source-build. We should attempt to follow this SDK update cadence as well to avoid breaking source-build.
