### ISSUE TITLE
Model Binding & Type Converter usage

### ISSUE THREAD

**Issue by epignosisx** [aspnet/AspNetCore#8846]
I'm trying to create a `TypeConverter` to handle comma separated values coming from the request. The documentation on this topic is very light, so I'm not sure if I'm missing something.

The type converter executes, it receives the value of friends, but the return value never makes it to the action method model.

This is how the code looks:

```cs
/**
* GET /home/personget?friends=james,john
**/
[HttpGet]
public IActionResult PersonGet([FromQuery]Person person)
{
    return Json(person);
}

/**
* POST /home/personpost
* Content-Type: application/x-www-form-urlencoded
* 
* friends=james,john
**/
[HttpPost]
public IActionResult PersonPost([FromForm]Person person)
{
    return Json(person);
}

public class Person
{
    public Friends Friends { get; set; }
}


[TypeConverter(typeof(CommaSeparatedValues))]
public class Friends : List<string>
{
}

public class CommaSeparatedValues : TypeConverter
{
    public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
    {
        return sourceType == typeof(string);
    }

    public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
    {
        var str = value as string;
        if (str == null)
            return null;

        return new List<string>(str.Split(','));
    }
}
```

What am I doing wrong? By the way, it would be great if [TypeConverter] was supported in properties. That would remove the need to create a custom classes.

cc: @rynowak

**Comment by rynowak** [comment]
Shouldn't you be returning a value of type `Friends`?

**Comment by epignosisx** [comment]
Yes! That was it (I got inheritance backward). Thank you!

Any reason why type converters on properties are not supported? In this particular example, it would be much better to have:

```cs
public class Person
{
    [TypeConverter(typeof(CommaSeparatedValues))]
    public List<string> Friends { get; set; }
}
```

**Comment by rynowak** [comment]
No, there's really no good reason why we don't support this. Funnily enough it hasn't come up before, but I agree that it would be useful. 

I'm sure we'd except a PR for something like this if you're interested. The starting point would be to use the model metadata system to get it to treat this property as a simple type, and then start hacking away at https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/Binders/SimpleTypeModelBinderProvider.cs#L23

**Comment by epignosisx** [comment]
That’s great! I’ll try to venture into implementing it.
