### ISSUE TITLE
Building the repo fails on a clean repo

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8848]
Running the following fails for me on a clean repo

```
.\restore.cmd
.\build.cmd
```

```
Microsoft (R) Build Engine version 16.0.452+g01bae6224c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Skipping project "C:\git\aspnet\AspNetCore\src\**\*.vcxproj" because it was not found.
C:\git\aspnet\AspNetCore\.dotnet\buildtools\korebuild\3.0.0-build-20190314.2\modules\projectbuild\module.targets(90,5):
 error MSB3202: The project file "C:\git\aspnet\AspNetCore\src\**\*.vcxproj" was not found. [C:\git\aspnet\AspNetCore\.
dotnet\buildtools\korebuild\3.0.0-build-20190314.2\KoreBuild.proj]

Build FAILED.

C:\git\aspnet\AspNetCore\.dotnet\buildtools\korebuild\3.0.0-build-20190314.2\modules\projectbuild\module.targets(90,5):
 error MSB3202: The project file "C:\git\aspnet\AspNetCore\src\**\*.vcxproj" was not found. [C:\git\aspnet\AspNetCore\.
dotnet\buildtools\korebuild\3.0.0-build-20190314.2\KoreBuild.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:16.33
msbuild.exe failed with exit code: 1
(AspNetCore) C:\git\aspnet\AspNetCore [rynowak/routing-middleware]>
```

**Comment by rynowak** [comment]
I can work around this for now using `build.ps1 -NoBuildNative` but it looks like something basic is broken

**Comment by jkotalik** [comment]
Dup of https://github.com/aspnet/AspNetCore-Internal/issues/2008, but this one has more details. I'll close the other.

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/AspNetCore-Internal/issues/1857

**Comment by rynowak** [comment]
But it doesn't seem incredibly related?

**Comment by Eilon** [comment]
No?

**Comment by Eilon** [comment]
Why re-opened? The other bug should be a superset of this issue.

**Comment by Tratcher** [comment]
Re-opening because this is still happening and all linked issues are closed.
Restore.cmd on a clean repo fails with the vcxproj error given above. build.cmd work.

**Comment by jkotalik** [comment]
I'm trying to repro this but having no luck. I'm running clean.cmd and then restore.cmd and I'm not hitting this issue.

I have a few ideas how to get around it.

**Comment by Tratcher** [comment]
It's gone again after a rebased and `git clean -xdf`. Temporary tooling issue?
