### ISSUE TITLE
Update templates/middleware to use MapFallbackToPage/File

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#8852]
Not long ago @rynowak implemented `MapFallbackToPage` and `MapFallbackToFile`, but our templates and the Blazor middleware don't yet use them.

The Razor Components template still has `@page "/{*catchall}"` in `Host.cshtml`, but I think this should be replaceable just by `@page` (right? or is that even needed?), with `MapFallbackToPage` added to `Startup.cs`. This should fix the current issue whereby 404 requests actually trigger a 500, and means we can remove the `favicon.ico` from the template contents.

Related, the `UseBlazor` middleware still relies on `UseSpa`, which has the drawback of not integrating properly with endpoint routing. We should replace this with `MapFallbackToFile`, and then we can remove the whole reference to `SpaServices.Extensions`. Arguably we could do more refactoring on `UseBlazor` to make it more composable but this isn't an area we want to spend too much time on in the short term given that we can freely change this further even after the 3.0 release.

**Comment by SteveSandersonMS** [comment]
Whatever change we make in UseBlazor needs to allow some mechanism by which the developer could use a .cshtml host page instead of index.html.

**Comment by d668** [comment]
is this about prerendering? are any walkthroughs available? thanks

**Comment by d668** [comment]
is this about prerendering? are any walkthroughs available? thanks
