### ISSUE TITLE
Razor components circuit used for prerender is not connected to by SignalR but a new one is created

### ISSUE THREAD

**Issue by springy76** [aspnet/AspNetCore#8869]
Using 3.0 preview-3 and this sample: https://github.com/springy76/RazorComponentsProblems/blob/problem/PrerenderCircuitsAreDiscarded/WebApp/Components/Pages/Index.razor

The sample shows that after a full prerender (which takes 4 seconds for all (async) operations without seeing anything) you can see the result of the prerender for a second before the new circuit destroys the view and does all init(async) again.

I would expect to (re)connect the SignalR connection to the circuit used for prerender which would result that after the initial 4s delay the view would not change again because the circuit differ has no changes/deltas to transmit.

**Comment by mkArtakMSFT** [comment]
We're fixing this as part of #8911

**Comment by springy76** [comment]
Thank you for not saying "works as designed" :)

**Comment by springy76** [comment]
I updated the sample to [preview4](https://github.com/springy76/RazorComponentsProblems/tree/problem/PrerenderCircuitsAreDiscarded/WebApp) and the initial render now works as expected.

**But**
On FireFox (but neither on Chrome/Opera nor on Edge) when pressing F5 or Ctrl+F5 something strange happens:
* the page immediately gets transparent and shows "reconnecting"
* 1-2s later you see the page rendered using the old GUID (from the scoped service)
* additional 1-2s later the GUID changes
