### ISSUE TITLE
TempData has poor round-tripping fidelity

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#8873]
This issue applies to using `TempDataDictionary` although it is generally much worse with `TempDataAttribute`. By round-tripping, I mean a value being set, serialized to bytes that gets written to cookie or session, and deserialized back to `TempDataDictionary` and read.

Consider, 
```C#
public class IndexModel
{
    [TempData]
    public int Value { get; set; }
    
    public ActionResult OnPost()
    {
        Value = 10;
        return RedirectToPage();
    }
    
    public void OnGet()
    {
        // We should expect Value to be 10 here
    }
}
```

For the above scenario, outside of a few types such as a `int`, `DateTime`, `string` and `Guid`, round-tripping using the Json.NET based serializer will fail due to a mismatched round-trip type. This is because no type information is preserved in the payload, and we get Json.NET's best guess results which for types such as `TimeSpan` or `Uri` is `string`. 

With the `TempData[".."]` lookup, users may have written code anticipating the round trip to be a string value, however, using `TempDataAttribute` would result in a runtime `InvalidCastException`.

**Comment by rynowak** [comment]
Are you suggesting that we take steps to mitigate this or explain it? I'd generally be supportive of something like an analzyer that provides guidance, or better errors messages when it does fail, or blocking things that can't work with an exception.

**Comment by pranavkm** [comment]
> Are you suggesting that we take steps to mitigate this or explain it?

In theory, we could do a better job with `TempData` attributes since we know the `Type` that's being round-tripped. However, in the shorter term, it might be better to limit `TempData` properties to a more limited subset - `int`, `bool`, `string`, and `DateTime`.

**Comment by mkArtakMSFT** [comment]
Let's see whether anybody even asks for it. Parking in the backlog for now.

**Comment by rynowak** [comment]
This is going to be asked for as soon as we ship :) I'd be happy to be wrong.

**Comment by pranavkm** [comment]
> I'd be happy to be wrong.

Closing as we haven't had any specific user feedback here. I guess you have a reason to be happy now 😄

**Comment by rynowak** [comment]
I'm super happy now.
