### ISSUE TITLE
Windows Authentication - Double Hop Issue

### ISSUE THREAD

**Issue by dharmeshtailor** [aspnet/AspNetCore#8880]
We have Micro Services being developed on Service Fabric platform that are deployed on stand alone local cluster. We have a website, that is configured to use windows authentication and then the logged in User is impersonated to fetch SSRS reports. We have used HttpSys to build the web host. And we are facing double hop issue when website is accessed from any server other than app box itself.

Code looks like below for stateless service :

```
protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
{
	return new ServiceInstanceListener[]
	{
		new ServiceInstanceListener(serviceContext =>
			new HttpSysCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
			{
				return new WebHostBuilder()
					.UseHttpSys(
						options =>
						{
							options.Authentication.Schemes = AuthenticationSchemes.Negotiate | AuthenticationSchemes.NTLM;
							options.Authentication.AllowAnonymous = false;
						}
					)
					.ConfigureServices(
						services => services
							.AddSingleton<StatelessServiceContext>(serviceContext))
					.UseContentRoot(Directory.GetCurrentDirectory())
					.UseStartup<Startup>()
					.UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
					.UseUrls(url)
					.Build();
			}))
	};
}
```  

In Startup.cs:

```
public void ConfigureServices(IServiceCollection services)
{
	services.AddAuthenticationCore(options =>
	{
		options.DefaultScheme = HttpSysDefaults.AuthenticationScheme;
	});
}
```

We have tried everything. All the SPNs are properly created. We already have a legacy Silverlight website which is working alright and works on same basis of windows authentication and impersonate user to fetch SSRS reports.

Just to verify if issue is with how service fabric creates services, I created stand alone DotNet core  website using HttpSys self host server. Still same issue.

I tried to find online, but there is no documentation or any other person that have faced similar issue.

Any help is appreciated.

The exception we get is:

> The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'NTLM'.

**Comment by Tratcher** [comment]
How are you doing the impersonation, and how do you call SSRS from there? .NET Core's impersonation support is quite limited.

Also note that to achieve multi-hop auth you need full delegation permissions, not just impersonation. Also note that HttpSys uses kernel mode auth so the SPN must be assigned for the machine account, not the user account. See https://github.com/aspnet/HttpSysServer/issues/450#issuecomment-385954391
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-2.2#kernel-mode-authentication-with-kerberos

**Comment by dharmeshtailor** [comment]
Sorry I thought I uodated the original post to include the call. Anyways here is how we call SSRS.

```
if (User.Identity is WindowsIdentity currentUser)
{
    WindowsIdentity.RunImpersonated(currentUser.AccessToken, async () =>
    {
        var reportServer = ReportServer();
        var trustedUserHeader = new ReportService2010.TrustedUserHeader();
        reportServer.ClientCredentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Identification;
        var items = await reportServer.ListChildrenAsync(trustedUserHeader, ReportFolder, true);
    });
}
```
We have assigned SPN for machine as well as user. But I will reconfirm that point.

**Comment by Tratcher** [comment]
Note RunImpersonated does not work as you'd expect for async code, the impersonation will terminate synchronously. There is no current support for async impersonation. At best you need to call .Result on your async APIs inside RunImpersonated.

**Comment by dharmeshtailor** [comment]
@Tratcher Have done that as well. I am in middle of checking few SPN settings and will update you.

**Comment by dharmeshtailor** [comment]
Following are the SPN applied:

App Server : 

> http/AppServer.domain
> http/AppServer

SSRS Service User:

> HTTP/SqlServer.domain
> HTTP/SqlServer
> MSSQLSvc/SqlServer
> MSSQLSvc/SqlServer.domain:1433
> MSSQLSvc/SqlServer.domain

Delegation is applied on DC.

**Comment by Tratcher** [comment]
> Delegation is applied on DC.

To which object? This needs to be enabled for the app server's machine account.

**Comment by dharmeshtailor** [comment]
Yes Delegation is applied on App Server's machine account.

Just to confirm, with machine account you mean "AppServer" name?

**Comment by Eilon** [comment]
Hi @dharmeshtailor we're not able to see what specifically is wrong here. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` tag or contacting [Microsoft Support](https://support.microsoft.com/) for additional assistance.
