### ISSUE TITLE
Need assistance understanding how /signin-oidc gets registered

### ISSUE THREAD

**Issue by fendric** [aspnet/AspNetCore#8894]
I am trying to write an authentication plugin for the NopCommerce 4.0 ecommerce engine, which is just an Asp.Net Core 2.0 application, using the microsoft.aspnetcore.authentication.openidconnect library.

In ConfigureServices I have the registration for my OpenIdConnect, which I've tested in a vanilla Asp.Net Core app an works beautifully.

When I click the Login button on the app, I am taken to our Auth0 provider for authentication.
However, when I get the redirect back to **/signin-oidc** I am getting a 404.

In order to make this work I need to understand what the Microsoft OpenIDConnect library is doing behind the scenes to self-register the **/signin-oidc** endpoint to figure out why it is not working in the NopCommerce engine. My guess is however the routes are being constructed, somehow is blocking the OpenIDConnect library from doing its thing.

Can someone help me understand how the OpenIDConnect library is registering the /signin-oidc endpoint, please?

I've spent some time looking at the code for microsoft.aspnetcore.authentication.openidconnect but I can't figure it out, so likely it is done in a dependency somewhere.

Thanks in advance. Any help appreciated.

PS - source code for NopCommerce is here (if it helps): https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.00

**Comment by blowdart** [comment]
Its doesn't work like you think it does. Authentication Handlers run on every request, regardless of the path. The handler decides if it needs to intervene based on, among other things, the path. 

For example; RemoteAuthenticationHandler (which OIDC uses) does it inside [ShouldHandleEvent()](https://github.com/aspnet/AspNetCore/blob/d8381656429addead2e5eb22ba1356abfb419d86/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L41)

```c#
        public virtual Task<bool> ShouldHandleRequestAsync()
            => Task.FromResult(Options.CallbackPath == Request.Path);
```

This default implementation looks at the Options for the handler, which contains a CallbackPath property, then compares the inbound request path against that value. The base implementation of [HandleRequestAsync()](https://github.com/aspnet/AspNetCore/blob/d8381656429addead2e5eb22ba1356abfb419d86/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L46) calls this function right at the start to see if it needs to run. There's no registration or anything of that ilk.

**Comment by Tratcher** [comment]
You've forked AuthenticationMiddleware? Why? It doesn't look like you modified it. 

AuthenticationMiddleware is what calls HandleRequestAsync on each auth handler to see if they will handle that request.

**Comment by fendric** [comment]
@Tratcher - I didn't fork anything myself... I don't work for NopCommerce... I'm just a client.
I am making a plugin for my company to allow using our Auth0 provider for Authentication.
NopCommerce allows us to extend the product by writing plugins than contain classes that implement certain interfaces, which they pull with reflection at startup and run for us. This allows injection at ConfigureServices(), Configure() and other points during runtime, where we can extend behavior.
If NopCommerce forked AuthenticationMiddleware that is a questionable decision I would pose to them. Might be a clue as to why things aren't working.

@blowdart - Thank you - that is a very helpful explanation. What do you think would cause the path I assigned in the callback (/signin-oidc) to NOT be handled, do you think? Because the symptom I am getting is that endpoint goes to a 404. The auth handler is not responding to it.
Is there anyway to turn on some logging to see why it is not handling it?

**Comment by blowdart** [comment]
Without seeing your startup.cs it's hard to say what's going on

**Comment by fendric** [comment]
@blowdart - give me a minute and I'll compile together the Nop startup along with what my plugin is trying to do.

**Comment by fendric** [comment]
@blowdart - OK, here we go:

For starters, NopCommerce 4.0 is an AspNetCore 2.0 application running on .Net Framework 4.6.1.

The NopCommerce startup is pretty sparse:
`    public class Startup
    {
        #region Properties

        /// <summary>
        /// Get configuration root of the application
        /// </summary>
        public IConfigurationRoot Configuration { get; }

        #endregion

        #region Ctor

        public Startup(IHostingEnvironment environment)
        {
            //create configuration
            Configuration = new ConfigurationBuilder()
                .SetBasePath(environment.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();
        }

        #endregion

        /// <summary>
        /// Add services to the application and configure service provider
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            return services.ConfigureApplicationServices(Configuration);
        }

        /// <summary>
        /// Configure the application HTTP request pipeline
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public void Configure(IApplicationBuilder application)
        {
            application.ConfigureRequestPipeline();
        }
    }`

The real magic happens in these classes:
This first one is for the ConfigureServices() call
`    /// <summary>
    /// Represents extensions of IServiceCollection
    /// </summary>
    public static class ServiceCollectionExtensions
    {
        /// <summary>
        /// Add services to the application and configure service provider
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        /// <param name="configuration">Configuration root of the application</param>
        /// <returns>Configured service provider</returns>
        public static IServiceProvider ConfigureApplicationServices(this IServiceCollection services, IConfigurationRoot configuration)
        {
            //add NopConfig configuration parameters
            services.ConfigureStartupConfig<NopConfig>(configuration.GetSection("Nop"));
            //add hosting configuration parameters
            services.ConfigureStartupConfig<HostingConfig>(configuration.GetSection("Hosting"));
            //add accessor to HttpContext
            services.AddHttpContextAccessor();

            //create, initialize and configure the engine
            var engine = EngineContext.Create();
            engine.Initialize(services);
            var serviceProvider = engine.ConfigureServices(services, configuration);
            
            if (DataSettingsHelper.DatabaseIsInstalled())
            {
                //implement schedule tasks
                //database is already installed, so start scheduled tasks
                TaskManager.Instance.Initialize();
                TaskManager.Instance.Start();

                //log application start
                EngineContext.Current.Resolve<ILogger>().Information("Application started", null, null);
            }

            return serviceProvider;
        }

        /// <summary>
        /// Create, bind and register as service the specified configuration parameters 
        /// </summary>
        /// <typeparam name="TConfig">Configuration parameters</typeparam>
        /// <param name="services">Collection of service descriptors</param>
        /// <param name="configuration">Set of key/value application configuration properties</param>
        /// <returns>Instance of configuration parameters</returns>
        public static TConfig ConfigureStartupConfig<TConfig>(this IServiceCollection services, IConfiguration configuration) where TConfig : class, new()
        {
            if (services == null)
                throw new ArgumentNullException(nameof(services));

            if (configuration == null)
                throw new ArgumentNullException(nameof(configuration));

            //create instance of config
            var config = new TConfig();

            //bind it to the appropriate section of configuration
            configuration.Bind(config);

            //and register it as a service
            services.AddSingleton(config);

            return config;
        }

        /// <summary>
        /// Register HttpContextAccessor
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        public static void AddHttpContextAccessor(this IServiceCollection services)
        {
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
        }

        /// <summary>
        /// Adds services required for anti-forgery support
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        public static void AddAntiForgery(this IServiceCollection services)
        {
            //override cookie name
            services.AddAntiforgery(options =>
            {
                options.Cookie.Name = ".Nop.Antiforgery";
            });
        }

        /// <summary>
        /// Adds services required for application session state
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        public static void AddHttpSession(this IServiceCollection services)
        {
            services.AddSession(options =>
            {
                options.Cookie.Name = ".Nop.Session";
                options.Cookie.HttpOnly = true;
            });
        }

        /// <summary>
        /// Adds services required for themes support
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        public static void AddThemes(this IServiceCollection services)
        {
            if (!DataSettingsHelper.DatabaseIsInstalled())
                return;

            //themes support
            services.Configure<RazorViewEngineOptions>(options =>
            {
                options.ViewLocationExpanders.Add(new ThemeableViewLocationExpander());
            });
        }

        /// <summary>
        /// Adds data protection services
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        public static void AddNopDataProtection(this IServiceCollection services)
        {
            //check whether to persist data protection in Redis
            var nopConfig = services.BuildServiceProvider().GetRequiredService<NopConfig>();
            if (nopConfig.RedisCachingEnabled && nopConfig.PersistDataProtectionKeysToRedis)
            {
                //store keys in Redis
                services.AddDataProtection().PersistKeysToRedis(
                    () =>
                    {
                        var redisConnectionWrapper = EngineContext.Current.Resolve<IRedisConnectionWrapper>();
                        return redisConnectionWrapper.GetDatabase();
                    }, RedisConfiguration.DataProtectionKeysName);
            }
            else
            {
                var dataProtectionKeysPath = CommonHelper.MapPath("~/App_Data/DataProtectionKeys");
                var dataProtectionKeysFolder = new DirectoryInfo(dataProtectionKeysPath);

                //configure the data protection system to persist keys to the specified directory
                services.AddDataProtection().PersistKeysToFileSystem(dataProtectionKeysFolder);
            }
        }

        /// <summary>
        /// Adds authentication service
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        public static void AddNopAuthentication(this IServiceCollection services)
        {
            //set default authentication schemes
            var authenticationBuilder = services.AddAuthentication(options =>
            {
                options.DefaultChallengeScheme = NopCookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultSignInScheme = NopCookieAuthenticationDefaults.ExternalAuthenticationScheme;
            });

            //add main cookie authentication
            authenticationBuilder.AddCookie(NopCookieAuthenticationDefaults.AuthenticationScheme, options =>
            {
                options.Cookie.Name = NopCookieAuthenticationDefaults.CookiePrefix + NopCookieAuthenticationDefaults.AuthenticationScheme;
                options.Cookie.HttpOnly = true;
                options.LoginPath = NopCookieAuthenticationDefaults.LoginPath;
                options.AccessDeniedPath = NopCookieAuthenticationDefaults.AccessDeniedPath;
            });

            //add external authentication
            authenticationBuilder.AddCookie(NopCookieAuthenticationDefaults.ExternalAuthenticationScheme, options =>
             {
                 options.Cookie.Name = NopCookieAuthenticationDefaults.CookiePrefix + NopCookieAuthenticationDefaults.ExternalAuthenticationScheme;
                 options.Cookie.HttpOnly = true;
                 options.LoginPath = NopCookieAuthenticationDefaults.LoginPath;
                 options.AccessDeniedPath = NopCookieAuthenticationDefaults.AccessDeniedPath;
             });

            //register and configure external authentication plugins now
            var typeFinder = new WebAppTypeFinder();
            var externalAuthConfigurations = typeFinder.FindClassesOfType<IExternalAuthenticationRegistrar>();
            var externalAuthInstances = externalAuthConfigurations
                .Where(x => PluginManager.FindPlugin(x)?.Installed ?? true) //ignore not installed plugins
                .Select(x => (IExternalAuthenticationRegistrar)Activator.CreateInstance(x));

            foreach (var instance in externalAuthInstances)
                instance.Configure(authenticationBuilder);
        }

        /// <summary>
        /// Add and configure MVC for the application
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        /// <returns>A builder for configuring MVC services</returns>
        public static IMvcBuilder AddNopMvc(this IServiceCollection services)
        {
            //add basic MVC feature
            var mvcBuilder = services.AddMvc();

            //use session temp data provider
            mvcBuilder.AddSessionStateTempDataProvider();

            //MVC now serializes JSON with camel case names by default, use this code to avoid it
            mvcBuilder.AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());

            //add custom display metadata provider
            mvcBuilder.AddMvcOptions(options => options.ModelMetadataDetailsProviders.Add(new NopMetadataProvider()));

            //add custom model binder provider (to the top of the provider list)
            mvcBuilder.AddMvcOptions(options => options.ModelBinderProviders.Insert(0, new NopModelBinderProvider()));

            //add global exception filter
            mvcBuilder.AddMvcOptions(options => options.Filters.Add(new ExceptionFilter()));

            //add fluent validation
            mvcBuilder.AddFluentValidation(configuration => configuration.ValidatorFactoryType = typeof(NopValidatorFactory));

            return mvcBuilder;
        }
    }
`
And the second one is for the Configure() call
`    /// <summary>
    /// Represents extensions of IApplicationBuilder
    /// </summary>
    public static class ApplicationBuilderExtensions
    {
        /// <summary>
        /// Configure the application HTTP request pipeline
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void ConfigureRequestPipeline(this IApplicationBuilder application)
        {
            EngineContext.Current.ConfigureRequestPipeline(application);
        }

        /// <summary>
        /// Add exception handling
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UseNopExceptionHandler(this IApplicationBuilder application)
        {
            var nopConfig = EngineContext.Current.Resolve<NopConfig>();
            var hostingEnvironment = EngineContext.Current.Resolve<IHostingEnvironment>();
            var useDetailedExceptionPage = nopConfig.DisplayFullErrorStack || hostingEnvironment.IsDevelopment();
            if (useDetailedExceptionPage)
            {
                //get detailed exceptions for developing and testing purposes
                application.UseDeveloperExceptionPage();
            }
            else
            {
                //or use special exception handler
                application.UseExceptionHandler("/errorpage.htm");
            }
        }

        /// <summary>
        /// Add diagnostic listener
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UseDiagnosticListener(this IApplicationBuilder application)
        {
            var diagnosticListener = EngineContext.Current.Resolve<DiagnosticListener>();

            //listen for middleware events
            diagnosticListener.SubscribeWithAdapter(new NopDiagnosticListener());
        }

        /// <summary>
        /// Adds a special handler that checks for responses with the 404 status code that do not have a body
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UsePageNotFound(this IApplicationBuilder application)
        {
            application.UseStatusCodePages(async context =>
            {
                //handle 404 Not Found
                if (context.HttpContext.Response.StatusCode == StatusCodes.Status404NotFound)
                {
                    var webHelper = EngineContext.Current.Resolve<IWebHelper>();
                    if (!webHelper.IsStaticResource())
                    {
                        //get original path and query
                        var originalPath = context.HttpContext.Request.Path;
                        var originalQueryString = context.HttpContext.Request.QueryString;

                        //store the original paths in special feature, so we can use it later
                        context.HttpContext.Features.Set<IStatusCodeReExecuteFeature>(new StatusCodeReExecuteFeature()
                        {
                            OriginalPathBase = context.HttpContext.Request.PathBase.Value,
                            OriginalPath = originalPath.Value,
                            OriginalQueryString = originalQueryString.HasValue ? originalQueryString.Value : null,
                        });

                        //get new path
                        context.HttpContext.Request.Path = "/page-not-found";
                        context.HttpContext.Request.QueryString = QueryString.Empty;

                        try
                        {
                            //re-execute request with new path
                            await context.Next(context.HttpContext);
                        }
                        finally
                        {
                            //return original path to request
                            context.HttpContext.Request.QueryString = originalQueryString;
                            context.HttpContext.Request.Path = originalPath;
                            context.HttpContext.Features.Set<IStatusCodeReExecuteFeature>(null);
                        }
                    }
                }
            });
        }


        /// <summary>
        /// Adds a special handler that checks for responses with the 400 status code (bad request)
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UseBadRequestResult(this IApplicationBuilder application)
        {
            application.UseStatusCodePages(context =>
            {
                //handle 404 (Bad request)
                if (context.HttpContext.Response.StatusCode == StatusCodes.Status400BadRequest)
                {
                    var logger = EngineContext.Current.Resolve<ILogger>();
                    var workContext = EngineContext.Current.Resolve<IWorkContext>();
                    logger.Error("Error 400. Bad request", null, customer: workContext.CurrentCustomer);
                }

                return System.Threading.Tasks.Task.CompletedTask;
            });
        }

        /// <summary>
        /// Configure middleware checking whether requested page is keep alive page
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UseKeepAlive(this IApplicationBuilder application)
        {
            application.UseMiddleware<KeepAliveMiddleware>();
        }

        /// <summary>
        /// Configure middleware checking whether database is installed
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UseInstallUrl(this IApplicationBuilder application)
        {
            application.UseMiddleware<InstallUrlMiddleware>();
        }

        /// <summary>
        /// Adds the authentication middleware, which enables authentication capabilities.
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UseNopAuthentication(this IApplicationBuilder application)
        {
            //check whether database is installed
            if (!DataSettingsHelper.DatabaseIsInstalled())
                return;

            application.UseMiddleware<AuthenticationMiddleware>();
        }

        /// <summary>
        /// Set current culture info
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UseCulture(this IApplicationBuilder application)
        {
            //check whether database is installed
            if (!DataSettingsHelper.DatabaseIsInstalled())
                return;

            application.UseMiddleware<CultureMiddleware>();
        }

        /// <summary>
        /// Configure MVC routing
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UseNopMvc(this IApplicationBuilder application)
        {
            application.UseMvc(routeBuilder =>
            {
                //register all routes
                EngineContext.Current.Resolve<IRoutePublisher>().RegisterRoutes(routeBuilder);
            });
        }

        /// <summary>
        /// Create and configure MiniProfiler service
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public static void UseMiniProfiler(this IApplicationBuilder application)
        {
            //whether database is already installed
            if (!DataSettingsHelper.DatabaseIsInstalled())
                return;

            //whether MiniProfiler should be displayed
            if (EngineContext.Current.Resolve<StoreInformationSettings>().DisplayMiniProfilerInPublicStore)
            {
                application.UseMiniProfiler(miniProfilerOptions =>
                {
                    //use memory cache provider for storing each result
                    miniProfilerOptions.Storage = new MemoryCacheStorage(TimeSpan.FromMinutes(60));

                    //determine who can access the MiniProfiler results
                    miniProfilerOptions.ResultsAuthorize = request =>
                        !EngineContext.Current.Resolve<StoreInformationSettings>().DisplayMiniProfilerForAdminOnly ||
                        EngineContext.Current.Resolve<IPermissionService>().Authorize(StandardPermissionProvider.AccessAdminPanel);
                });
            }
        }
    }
`

Now at some point in that code, there is an AuthenticationStartup class that gets called:
`    /// <summary>
    /// Represents object for the configuring authentication middleware on application startup
    /// </summary>
    public class AuthenticationStartup : INopStartup
    {
        /// <summary>
        /// Add and configure any of the middleware
        /// </summary>
        /// <param name="services">Collection of service descriptors</param>
        /// <param name="configuration">Configuration root of the application</param>
        public void ConfigureServices(IServiceCollection services, IConfigurationRoot configuration)
        {
            //add data protection
            services.AddNopDataProtection();

            //add authentication
            services.AddNopAuthentication();
        }

        /// <summary>
        /// Configure the using of added middleware
        /// </summary>
        /// <param name="application">Builder for configuring an application's request pipeline</param>
        public void Configure(IApplicationBuilder application)
        {
            //configure authentication
            application.UseNopAuthentication();

            //set request culture
            application.UseCulture();
        }

        /// <summary>
        /// Gets order of this startup configuration implementation
        /// </summary>
        public int Order
        {
            //authentication should be loaded before MVC
            get { return 500; }
        }
    }
`

At this point we have the Cookies authentication wired up, which NopCommerce uses for their Authentication/Authorization mechanism.

Now at this point, they are looking (via Reflection) for any plugins that implement their IExternalAuthenticationRegistrar.
This is where I come in.
I tell the builder I get passed in to AddOpenIdConnect and use the same settings I used in my plain vanilla AspNetCore test project (which worked.):

`    /// <summary>
    /// Registration of BAS authentication service (plugin)
    /// </summary>
    public class BasAuthenticationRegistrar : IExternalAuthenticationRegistrar
    {
        /// <summary>
        /// Configure
        /// </summary>
        /// <param name="builder">Authentication builder</param>
        public void Configure(AuthenticationBuilder builder)
        {
            builder.AddOpenIdConnect(BasAuthenticationDefaults.AuthenticationScheme, options =>
                {
                    options.SignInScheme = BasAuthenticationDefaults.AuthenticationScheme;
                    var settings = EngineContext.Current.Resolve<BasExternalAuthSettings>();
                    options.ClientId = settings.ClientKeyIdentifier;
                    options.ClientSecret = settings.ClientSecret;
                    options.Authority = BasAuthenticationDefaults.Domain;
                    options.ResponseType = "code";
                    options.Scope.Clear();
                    options.Scope.Add("openid");
                    options.CallbackPath = new PathString("/signin-oidc");
                    options.ClaimsIssuer = BasAuthenticationDefaults.AuthenticationScheme;
                    options.GetClaimsFromUserInfoEndpoint = true;
                    options.SaveTokens = true;
                    options.Events = new OpenIdConnectEvents
                    {
                        //handle the logout redirection
                        OnRedirectToIdentityProviderForSignOut = (context) =>
                        {
                            var logoutUri =
                                $"https://cimpress.auth0.com/v2/logout?client_id={settings.ClientKeyIdentifier}";
                            var postLogoutUri = context.Properties.RedirectUri;
                            if (!string.IsNullOrEmpty(postLogoutUri))
                            {
                                if (postLogoutUri.StartsWith("/"))
                                {
                                    var request = context.Request;
                                    postLogoutUri =
                                        $"{request.Scheme}://{request.Host}{request.PathBase}{postLogoutUri}";
                                }

                                logoutUri += $"&returnTo={Uri.EscapeDataString(postLogoutUri)}";
                            }
                            context.Response.Redirect(logoutUri);
                            context.HandleResponse();
                            return Task.CompletedTask;
                        }
                    };
                });
        }
    }
`
Then, I wired up a controller so that when my user clicks the Login button it runs this code, which issues the ChallengeAsync call to Auth0:
`        public IActionResult Login(string returnUrl = "/LoginCallback")
        {
            if (!_externalAuthenticationService.ExternalAuthenticationMethodIsAvailable(BasAuthenticationDefaults.ProviderSystemName))
                throw new NopException("BAS Authentication module cannot be loaded");

            if (string.IsNullOrEmpty(_basExternalAuthSettings.ClientKeyIdentifier) || string.IsNullOrEmpty(_basExternalAuthSettings.ClientSecret))
                throw new NopException("BAS Authentication module not configured");

            //configure login callback action
            var authenticationProperties = new AuthenticationProperties
            {
                RedirectUri = Url.Action("LoginCallback", "BasAuthentication", new { returnUrl = returnUrl })
            };

            return Challenge(authenticationProperties, BasAuthenticationDefaults.AuthenticationScheme);
        }
`
(The Challenge() call is issued directly against the Microsoft Authentication library.)

I assigned the CallbackPath to "/signin-oidc" which I expected the Microsoft OpenIdConnect to handle for me, so that the token and auth cookies can be validated back to the Auth0 engine.
My login page make the call to Auth0, I get the prompt to Authenticate, then Auth0 redirects my browser back to the CallbackPath (/signin-oidc) but at this point that endpoint gets a 404.

I have tried creating a custom callback endpoint in a controller and that verified that Auth0 is making the callback to my endpoint and using Fiddler I captured the following (code and state sanitized):
`POST https://localhost:44368/signin-oidc HTTP/1.1
Referer: https://cimpress.auth0.com/login/callback
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US
Content-Type: application/x-www-form-urlencoded
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
Accept-Encoding: gzip, deflate, br
Host: localhost:44368
Content-Length: 332
Connection: Keep-Alive
Cookie: .AspNetCore.OpenIdConnect.Nonce.CfDJ8OdAhkiHj4lCpLcgWo2PZ_dWc0Fd3Z4w9XYckQlYbjbbYGD-slSXYUBfblhU5hrM7dyu3dlOTCKmYR-EY20NRr3R8W3ODjcbINjOkWG7Hmfur83Jdf2Da0oD3rUTC_zYcTwIXLFAGakqjPILyKnLuYQ4wl6AdOOzsJGXx8EHNeyTu3RooH8wc4_8k0DLxQlBNzmY806UBC3tuNaqztqmtQNlyxkt5wYUel8Hj2D1YD2v0TCA4EHfhYU4dTNisf1jG8eK6adYbNyY5IFkwIu4LqY=N; 
.AspNetCore.Correlation.Auth0.5M2vhQ0b_e829ZRaNO_8AxmPNsp2LSGBM_IWwNqleWc=N; __atuvc=4%7C8

code=XXXXXXX&state=XXXXX
`
I can make my own endpoint and have it respond accordingly, but I'm not sure how to do that myself.
The sample I have from Auth0 that shows how to handle this assumes that the Microsoft library will handle the callback.
The sample I have from NopCommerce which is based on a Facebook authentication, suggests that we should then make a call like this:

`            var authenticateResult =  await this.HttpContext.AuthenticateAsync(BasAuthenticationDefaults.AuthenticationScheme);
`
And use the result to then validate the user and authenticate him/her with the NopCommerce cookie Auth.
However, when I tried that I get a 500 error from Auth0.

So either I am doing something terribly wrong or there is something I grossly misunderstood about how this whole thing works.

Grateful for any guidance/assistance.

Thanks in advance.

**Comment by fendric** [comment]
Sorry - having some trouble with the editor...
It's messing up my code blocks somehow

**Comment by fendric** [comment]
Fixing it - reading documentaiton

**Comment by fendric** [comment]
@blowdart - Apologies for the delay. Should be readable now.

**Comment by Tratcher** [comment]
I don't see anything you've done wrong. You'll have to take this up with Nop, they've made some pretty extreme customizations. The most suspect part is here:
```
        public static void UseNopAuthentication(this IApplicationBuilder application)
        {
            //check whether database is installed
            if (!DataSettingsHelper.DatabaseIsInstalled())
                return;

            application.UseMiddleware<AuthenticationMiddleware>();
        }
```

Leaving out the AuthenticationMiddleware would cause this kind of 404. See if DatabaseIsInstalled is true or false.

Unrelated:
- Remove `options.SignInScheme = BasAuthenticationDefaults.AuthenticationScheme;`, it would create a circular reference.

**Comment by fendric** [comment]
@Tratcher - thank you for the feedback.
The DatabaseIsInstalled will be true at runtime. The first time (ever) you run NopCommerce, it will not have a database and will run scripts to create one, but in subsequent runs the database will exist.

I would love to take this up with Nop (which I have) but they are looking at me saying they don't know what the Microsoft Authentication library expects and referred me to Microsoft. I think it's going to take knowledge from this group to give me the necessary standing to tell them what they are doing wrong.

I will try your suggestion for removing the options.SignInScheme. Thank you for that. Although I would love to better understand how that creates the circular reference, so if you could explain that to me, I would be grateful. I'm not sure what goes on under the covers. I got that from a code sample from Auth0.

**Comment by blowdart** [comment]
The authorization pieces would expect to be in the pipeline before anything else that could handle requests, such as MVC or static files. That's pretty much the only requirement.

**Comment by Eilon** [comment]
We'll get in touch with nopCommerce and try to get this resolved with them directly. I'll work on setting up a discussion with them.

**Comment by fendric** [comment]
Thank you so much, @Eilon ! Very much appreciated.

**Comment by Eilon** [comment]
I contacted nopCommerce to see if we can get in touch with them to resolve this. I'll update this issue with whatever we find out.

**Comment by Eilon** [comment]
Still waiting to hear back from nopCommerce with details.

**Comment by fendric** [comment]
Thank you for the progress update, @Eilon .

**Comment by Eilon** [comment]
I heard back today that the nopCommerce folks said they would take a look.

**Comment by fendric** [comment]
That is great news! Thank you for that!

**Comment by Eilon** [comment]
Hi, we haven't heard back yet from the nopCommerce folks, so I'm closing this issue because we can't investigate this further on our own. I'll re-open when we have further updates. I recommend following up directly with nopCommerce for any urgent support.
