### ISSUE TITLE
Create an analyzer for Endpoint Routing + UseMVC

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8898]
In 3.0 we won't support this combo anymore, since we expect this to impact lots of folks updating to 3.0 this definitely deserves an analyzers so users can know.

The conditions I would expect to check for is:
- Is `MvcOptions.EndableEndpointRouting == false` not found?
- Is `UseMvc()` present

**Comment by rynowak** [comment]
https://github.com/aspnet/AspNetCore/tree/rynowak/startup-analyzer

**Comment by JamesNK** [comment]
Questions:

1. Does CompatibilityVersion.Version_2_1 still disable endpoint routing? From what I can tell it does not.
2. How funky do we want to get with detecting the correct Startup.cs? For example, someone may have renamed it. Would require parsing `Program.Main` (which, if we want to be really thorough would require us to look in the csproj file to see if the entry point had changed).
3. I'll remove the other analysis logic that is in your branch. Can look at in the future. Cool?

**Comment by rynowak** [comment]
1. We don't need to handle that. These analyzers are 3.0+ and 3.0 doesn't support that setting.

2. Not funky at all. We should do something really simple.

3. Yes please, we should do something reasonable to try and make the migration experience have better feedback.

**Comment by JamesNK** [comment]
Help file article - https://github.com/aspnet/AspNetCore/issues/8898
