### ISSUE TITLE
Support strongly typed builders with IEndpointConventionBuilder

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#8902]
Map extensions that hang off `IEndpointRouteBuilder` return `IEndpointConventionBuilder`. This is fine and good.

Can we imagine scenarios where someone wants to return a more strongly typed builder? For example, from gRPC's `MapGrpcService` I return an `GrpcEndpointRouteBuilder`. It implements convention builder but there is also some gRPC specific stuff on there, and gRPC extension methods.

```cs
public class GrpcEndpointRouteBuilder : IEndpointConventionBuilder
{
    public GrpcEndpointRouteBuilder ConfigureCrazyGrpcStuff(Action a)
    {
        a();
        return this;
    }
}
```

Today all our `IEndpointConventionBuilder` extension methods return `IEndpointConventionBuilder` which would make using a strongly typed builder difficult.

```cs
routes.MapGrpcService<MyService>()
    .RequireAuthorization("policy")
    .ConfigureCrazyGrpcStuff(() => {}) // error, reference is no longer the gRPC builder
```

Should our extension methods be more like:

```cs
public TBuilder RequireAuthorization<TBuilder>(TBuilder builder, string policyName) where TBuilder : IEndpointConventionBuilder
{
    // stuff
    return builder;
}
```

// @davidfowl @rynowak

**Comment by rynowak** [comment]
It's absolutely intended that you return a strongly-typed builder for a case like this.

We do need to update these methods to have a `T`. That was part of the original design and prototypes but I guess it got lost? 

I agree 100% and this was always the plan.

**Comment by rynowak** [comment]
I would also strongly encourage that you return a CLASS and not an interface so it can grow.

**Comment by davidfowl** [comment]
I dunno, the generics make me sad.

**Comment by rynowak** [comment]
Then I guess you're sad? The builders returned from endpoint routing methods are the application builder replacements. The `IEndpointConventionBuilder` is there to be implemented for all of the *common* stuff.

**Comment by davidfowl** [comment]
I guess I should write a bit more about why it makes me sad. The problem with generics is that they instantly become hard to use once type inference fails. That happens the moment you have a second generic argument that needs to be specified. Maybe we'll get lucky and won't end up with multiple generic arguments but I am suspicious of that.

**Comment by rynowak** [comment]
Yeah agreed. So the example with `MapHub` should change to use typeof instead of non-generic.

**Comment by mkArtakMSFT** [comment]
@JamesNK, if this is going to be a breaking change, please apply the label.

**Comment by rynowak** [comment]
Moving to the current milestone since you're werking on this

**Comment by mkArtakMSFT** [comment]
@JamesNK please close this bug, when you'll merge the PR.
