### ISSUE TITLE
Returning ActionResult attempting to auto submit form fails using MVC 2.2, succeeds 4.7.2.

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/AspNetCore#8903]
### Describe the bug
I used visual studio to create two asp.net mvc apps.
One was created using asp.net 2.2 core.
One was created using asp.net 4.7.2 desktop.

The following code has different results.  
```
public ActionResult About()
{
    var content = "<html><body onload=\"document.frm1.submit()\"><form action=\"http://www.google.com\" name=\"frm1\"><input type=\"hidden\" name=\"q\" value=\"Hello world\" /></form></body></html>";

    return new ContentResult
    {
        Content = content// strBuilder.ToString()
    };
}

```
asp.net core 2.2, the browser will just show the code.
asp.net 4.7.2 desktop will submit to www.google.com where the browser will be.

### Expected behavior
I expect them to work the same way. If not, what do I have to do?

**Comment by Tratcher** [comment]
Offline notes: He had to set the ContentType to text/html for this to work on core.

**Comment by blowdart** [comment]
So we can close?

**Comment by brentschmaltz** [comment]
It's curious why the two runtimes have a different behavior.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @brentschmaltz.
In the core example above we default to `text/plain` content type, which browsers interpreted as normal text, instead of normal HTML.
