### ISSUE TITLE
Adding Swagger Generation Support in Asp.Net Core 3.0

### ISSUE THREAD

**Issue by osharko** [aspnet/AspNetCore#8908]
Swagger is nowadays a standard for Api Documentation, expecially when we work on microServices or simple Api.

At this moment, there's no full support, in .Net/.Net Core for Swagger code generation, neither from swagger's editor because of some problem ( like this [7945](https://github.com/swagger-api/swagger-codegen/issues/7945) and so on) neither from .Net/.Net Core Framework.

The situation is different in Java, where the support for swagger-code generation via plugin is a very solid reality.

Could we be able to add a native Swagger support in .net core for better working in this microServices age?

Thank you

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @osharko.
This seems to be something on our radar already: https://github.com/aspnet/AspNetCore/issues/7639
Closing this one as a dupe.
