### ISSUE TITLE
[Components] Multiple component entry points in an app

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#8913]
- [ ] Should we support the idea of having multiple component entry points in an application? 
  - For example. Given pages A and B render different components in each of them and have them be interactive.
- [ ] Should this require a fork in the pipeline or work just with normal routing.
- [ ] Its not clear how to implement this scenario and what works and what doesn't.
  - We should decide what we want to work here and define what the experience is.
  - The current base path based implementation is brittle and full of cave-heats. You need to make the stars align and it's not easy.
- [ ] Should the fallback routing overloads play well together?
  - If I have '/Admin' and '/' as entry points, should paths that start with '/Admin' get routed there and the remainder caught by '/'? I haven't been able to make this work to this day.

**Comment by danroth27** [comment]
@javiercn We think your recent PR (#8911) address these questions. If you think there are remaining issues that should be address, please open specific issues for those topics.

**Comment by javiercn** [comment]
My work makes it a bit easier, but there are things still to consider.

> Should the fallback routing overloads play well together?
> * If I have '/Admin' and '/' as entry points, should paths that start with '/Admin' get routed there and the remainder caught by '/'? I haven't been able to make this work to this day.

This is orthogonal to my changes and I'm not sure if it needs to be addressed. @rynowak will know.
