### ISSUE TITLE
Preflight CORS request returning NoContent instead of Forbidden

### ISSUE THREAD

**Issue by danql** [aspnet/AspNetCore#8922]
### Describe the bug
I have seen other frameworks return a 403 when preflight cors requests fail. According to the name of this test that may be the intention although the assert is for a no content status.
https://github.com/aspnet/AspNetCore/blob/6dc28d8a4ecb53a1890d0c14c9914b46dc0573b8/src/Middleware/CORS/test/UnitTests/CorsMiddlewareTests.cs#L261

### To Reproduce
1. https://github.com/aspnet/AspNetCore/blob/6dc28d8a4ecb53a1890d0c14c9914b46dc0573b8/src/Middleware/CORS/test/UnitTests/CorsMiddlewareTests.cs#L261
2. Test name doesn't match assert

### Expected behavior
Expected to assert against 403(Forbidden)

**Comment by pranavkm** [comment]
The Fetch spec recommends returning a 403 in case the server does not want to participate in a CORS protcool - https://fetch.spec.whatwg.org/#http-responses. It's debatable if not allowing CORS for an origin is the same as not participating in CORS. That said, is there an actual scenario that's broken here?

**Comment by danql** [comment]
The name of the test says ReturnsForbidden. I was wondering if returning Forbidden was the original intention. If that's not the case then the name of the test should be changed to PreFlightRequest_DoesNotMatchPolicy_DoesNotSetHeadersAndReturnsNoContent.

**Comment by pranavkm** [comment]
Ahh, yes, that does look incorrect. We'd be happy to accept a PR to get the test name fixed.
