### ISSUE TITLE
Languages IPageRouteModelConvention custom convention for all pages using Razor Pages

### ISSUE THREAD

**Issue by spacecat** [aspnet/AspNetCore#8936]
### Describe the bug
Question

From:

https://github.com/aspnet/Mvc/issues/6671#issuecomment-323133037

```
public class LanguagePageRouteModelConvention : IPageRouteModelConvention
{
   public void Apply(PageRouteModel model)
   {
        var selectorCount = model.Selectors.Count;
        for (var i = 0; i < selectorCount; i++)
        {
            var selector = model.Selectors[i];
            model.Selectors.Add(new SelectorModel
            {
                AttributeRouteModel = new AttributeRouteModel
                {
                    Template = AttributeRouteModel.CombineTemplates("{language}", selector.AttributeRouteModel.Template),
                }
            });
        }
   }
}

// In Startup
options.Conventions.Add(new LanguagePageRouteModelConvention());
```
**Main question**:
How do you generate the link to that route template (`Template = AttributeRouteModel.CombineTemplates("{language}", selector.AttributeRouteModel.Template)`) in a page using Razor Pages?

I've tried all sorts of combinations in the `asp-page` attribute of the anchor tag helper but the anchor tag is not picking up the template I added for my `IPageRouteModelConvention` implementation.

`<a asp-page="privacy">Privacy</a>` <-This should be enough to generate `<a href="/en/privacy">Privacy</a>` ?

Also, I've tried the following lines of code before iterating the `PageRouteModel` selectors:

```
    // SuppressLinkGeneration for existing routes
    foreach (var selector in model.Selectors)
    {
        selector.AttributeRouteModel.SuppressLinkGeneration = true;
    }
```
I also tried setting `SuppressLinkGeneration` manually for each and every route - I still can't generate a proper anchor tag. 

Please advice.

### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please share a sample here, if you have one? Thanks!

**Comment by keatkeat87** [comment]
i just open a bug issue maybe relate with this. [#10036](https://github.com/aspnet/AspNetCore/issues/10036) 
same problem in my case, the "asp-page" generate a wrong url 
[asp.nect core tutorial for localization ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) didn't use razor page. it use a mvc as a demo. 
i don't know is it support to use razor page in this localization ?
