### ISSUE TITLE
Passing type of 'Action' to JsInterop ?

### ISSUE THREAD

**Issue by moataz1991** [aspnet/AspNetCore#8937]
I want something like this while CallBack is `Action<string>`

`JSRuntime.Current.InvokeAsync<string>("Site.GetImageById", guid,CallBack)`
and then from javascript
`Window.Site={ GetImageById:function(id,callback)`
`... some file reader doings.. then `
`callback(data);
}`

is passing parameter of type `Action<T>` doable ? at least in the near future ?
Thanks

**Comment by danroth27** [comment]
You can pass a `DotNetObjectRef` to JS and then invoke methods on it. See https://docs.microsoft.com/en-us/aspnet/core/razor-components/javascript-interop?view=aspnetcore-3.0#invoke-net-methods-from-javascript-functions.

**Comment by moataz1991** [comment]
i know about that , but in my case i can't callback to static method !
so please help !

**Comment by moataz1991** [comment]
sorry , found it in the link you provided 
I'll try it
Thanks !
