### ISSUE TITLE
HostingLogScope should include Request.BasePath

### ISSUE THREAD

**Issue by penenkel** [aspnet/AspNetCore#8942]
When logging the request path the `HostingLogScope` should also include the`HttpContext.Request.BasePath`. 

At the moment only `HttpContext.Request.Path` is logged. This leads to the unexpected behavior that the URL triggering the request is not necessarily equal to the request path logged. This is the case if for example the `UsePathBaseMiddleware` is used.

I expected the request path logged to always be equal to the triggering URL.

In my opinion both `Path` and `BasePath` should be logged. Either as two separate fields or as concatenation.

**Comment by davidfowl** [comment]
This seems reasonable, I would just contact them (if the base path isn't empty). Do you want to send a pull request?
