### ISSUE TITLE
AspNet Core 2.2  forget markup Microsoft.AspNetCore.Hosting.IApplicationLifetime obsolete in source code

### ISSUE THREAD

**Issue by linkanyway** [aspnet/AspNetCore#8949]
### Describe the bug
the [official document](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.iapplicationlifetime?view=aspnetcore-2.2) mark up the Microsoft.Extensions.Hosting.IApplicationLifetime obsolete  and looks like move it to Microsoft.AspNetCore.Hosting.IApplicationLifetime, but haven't markup obsolete in source code

![image](https://user-images.githubusercontent.com/44063944/55289637-72d57800-53fb-11e9-9628-aa971c8c3719.png)

it make developer confused and also haven't any compiler warning

Expected:
There is Obsolete markup to the Microsoft.Extensions.Hosting.IApplicationLifetime, and should be have compiler warning.

**Comment by Tratcher** [comment]
It's not obsolete until 3.0. See https://github.com/aspnet/Announcements/issues/344.

**Comment by Tratcher** [comment]
@guardrex That obsolete warning is really misleading, it's showing up on all versions of the docs, not just 3.0. Who maintains that?

**Comment by guardrex** [comment]
@dend

**Comment by anurse** [comment]
Filed https://github.com/aspnet/ApiDocs/issues/115, we can track the docs issue there.

The attribute is appropriately marked obsolete in 3.0 so I'm going to close this bug.
