### ISSUE TITLE
Blazor Debugging in Visual Studio 2019 Fails to Connect

### ISSUE THREAD

**Issue by jamsoft** [aspnet/AspNetCore#8950]
### Describe the bug
When I try to connect VS2019 to a running Blazor application I get 

Unable to connect to `<localhost address>` Operation not supported. `Unknown error 0x80070057`

![blazor2](https://user-images.githubusercontent.com/2502211/55290662-e1034600-53cd-11e9-8f47-44ca1749fd66.PNG)

### To Reproduce
1. Start Blazor App
2. Run Chrome with debugging (%programfiles(x86)%\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222 http://localhost:50601/)
3. Attempt to attach to process in VS
4. Connection refused

![blazor](https://user-images.githubusercontent.com/2502211/55290609-430f7b80-53cd-11e9-98c0-d4a92439d450.PNG)

### Expected behavior
Debugger should connect.  I've been following Steves talk from NDC London but I just cannot get any of this working.  Debugging in the browser is working but attempting this from VS fails every time.

I'm running v73 of Chrome.

**Comment by Andrzej-W** [comment]
If you want to debug Blazor application in VS you have to use Blazor on the server (Razor Components). Blazor on the client (WebAssembly)  can be debugged directly in Chrome. Here are details:
https://docs.microsoft.com/en-us/aspnet/core/razor-components/debug?view=aspnetcore-3.0

You cannot debug Blazor WebAssembly in VS. Currently Blazor is compiled to IL code and then ***interpreted*** in the browser. It is not compiled to native WebAssembly code.

**Comment by danroth27** [comment]
@SteveSandersonMS Are there any additional steps to reproduce your demo of attaching VS to a client-side Blazor app?

**Comment by mkArtakMSFT** [comment]
Closing as this is a non-supported scenario yet but we will be doing that in the future: #9035
