### ISSUE TITLE
Serving server-side blazor from subfolder

### ISSUE THREAD

**Issue by yevhen** [aspnet/AspNetCore#8953]
Using server-side rendered Blazor, I moved `Pages` and `Components` folder into GUI subfolder. I also changed `<_RazorComponentInclude>Components\**\*.cshtml</_RazorComponentInclude>` to `<_RazorComponentInclude>GUI\Components\**\*.cshtml</_RazorComponentInclude>`. Then compiling and running the app (F5 from VS19) shows blank screen (localhost page not found). The `Index.cshtml` is not served.

### To Reproduce
1. Using the latest VS19 preview create the ASP.NET Core Web Application with Razor Components
2. Move Pages and Components folders into GUI subfolder
3. Fix namespaces to be able to compile and run the app
4. Change blazor-related property in csproj file to `<_RazorComponentInclude>GUI\Components\**\*.cshtml</_RazorComponentInclude>`
5. Compile and run the app
4. See the error

Not sure whether it's a bug or is there something I miss which need to be additionally configured?

**Comment by danroth27** [comment]
Thanks for submitting this issue! We do our best to respond to all questions, but you may get a faster response by posting to [StackOverflow](https://stackoverflow.com/questions/tagged/blazor).

**Comment by ehouarn-perret** [comment]
Not sure this is exactly the same issue, but I have experienced something similar: 

https://stackoverflow.com/questions/58456272/blazor-changing-blazor-folder-gives-me-cannot-find-the-fallback-endpoint
