### ISSUE TITLE
Razor Page Type in PageActionDescriptor

### ISSUE THREAD

**Issue by xsoheilalizadeh** [aspnet/AspNetCore#8959]
In the `ControllerActionDescriptor` I have access to the attributes that have decorated on the controllers and action. I use this option for implementing the dynamic permission scenario and with `GetCustomAttribute` I fetch the `AuthorizeAttribute` that has decorated on my controllers and actions.
```c#
descriptor.ControllerTypeInfo.GetCustomAttribute<AuthorizeAttribute>()?
     .Policy == ConstantPolicies.DynamicPermission
     
descriptor.MethodInfo.GetCustomAttribute<AuthorizeAttribute>()?
     .Policy == ConstantPolicies.DynamicPermission;
```
Now, I want to use this feature for the projects that use Razor Pages instead of MVC. So here I need to to use the `PageActionDescriptor` rather `ControllerActionDescriptor` than for the Razor Pages. The information that PageActionDescriptor Gives me are above:

```c#
public string AreaName { get; set; }
        
public string DisplayName { get; set; }

public string ViewEnginePath { get; set; }

public IList<ParameterDescriptor> Parameters { get; set; }

public IList<ParameterDescriptor> BoundProperties { get; set; }

public IList<FilterDescriptor> FilterDescriptors { get; set; }

// more
```
I've tried following code for getting `AuthorizeAttribute`:

```c#
descriptor.GetType().GetCustomAttribute<AuthorizeAttribute>()?
    .Policy ==  ConstantPolicies.DynamicPermission;
```
I've faced with the null value and in the debugging there hadn't been any Attribute, It's clear cuz the descriptor isn't the Razor Page Type.

Here I need to access the Razor Page Type for getting the decorated attributes and there aren't any properties for this fact.

_Note that the AuthorizeAttribute isn't there in the `FilterDescriptors` property if you want to forward me to the [doc](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.2#authorize-filter-attribute)._

Versions: 
```
ASP.NET Core 2.1 +

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011004
 Commit:    563371c23a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011004\

Host (useful for support):
  Version: 3.0.0-preview4-27529-01
  Commit:  4626102114
```

**Comment by danroth27** [comment]
@pranavkm Can you take a look?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @xsoheilalizadeh.
@blowdart what would you recommend here?

**Comment by blowdart** [comment]
I have no recommendations, this isn't a security decision, but rather one about the differences between MVC and Razor. The thing attempting to be done is valid, so Razor would need to find a way to expose the same sort of information.

**Comment by pranavkm** [comment]
You could get to the `CompiledPageActionDescriptor` using `IPageLoader`. `HandlerType` \ `HandlerTypeAttributes` are the equivalent to attributes on the controller.

**Comment by danroth27** [comment]
Closing as this questions now seems to be answered.
