### ISSUE TITLE
Question: Registry key for AspNetCoreModule

### ISSUE THREAD

**Issue by yashwanthreddyg** [aspnet/AspNetCore#8961]
Is there a registry key to check if AspNetCoreModule is installed?

**Comment by jkotalik** [comment]
@joeloff I was trying to see if there is a reg key for the windows hosting bundle and didn't see it. Does it exist.

I don't believe we have reg keys for AspNetCoreModule itself, but we do register reg keys for the eventlog. You should be able to check `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\IIS AspNetCore Module or IIS AspNetCore Module V2.

**Comment by joeloff** [comment]
Bundles don't generally create registry keys, though it does write some information into HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall (but it's arranged by GUIDs and will be different for each bundle). Also, detecting the bundle may not be sufficient as it would only install ANCM if all the required IIS features are enabled.

@yashwanthreddyg another option would be to simply check for the ANCM DLL on disk. @jkotalik correct me if I'm wrong, but the location of the DLL is pretty fixed.
