### ISSUE TITLE
[FromForm] and a model that contains a list of items does not split the items correctly

### ISSUE THREAD

**Issue by sander1095** [aspnet/AspNetCore#8962]
### Describe the bug
See my stackoverflow post: https://stackoverflow.com/q/55452461/3013479

TLDR:
`[FromForm]` combined with a model that contains a list of items will not split the items correctly.

### To Reproduce
The repo to reproduce the issue:
https://github.com/sander1095/FromFormGuidListBug

### Expected behavior
I expect the list of items to equal the amount of items I enter in swagger.

**Comment by danroth27** [comment]
@mkArtakMSFT Please assign

**Comment by sander1095** [comment]
I noticed that if the frontend sent the items as "Items="Foo","Bar"" It also didn't work. Sending it as 2 seperate arguments as noted in the stackoverflow question does work. 

It could be that this is a .NET Core issue (or maybe a configuration issue but then maybe the default form data model binding configuration should accept arrays better?) so that could need to be investigated.

In any case, swagger should support arrays with formdata :)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sander1095.
This is not something we support and we have no plans to make changes in this area.
We'll track documenting this as part of https://github.com/aspnet/AspNetCore.Docs/issues/12069
