### ISSUE TITLE
Current usage of Utf8JsonReader needs to use TextEquals (e.g. NegotiateProtocol/etc.)

### ISSUE THREAD

**Issue by ahsonkhan** [aspnet/AspNetCore#8969]
Currently, consumers of Utf8JsonReader are comparing the ValueSpan/ValueSequence directly (using SequenceEqual). This could be problematic if the payload contained escaped data which would be incorrectly flagged as not matching (when it should).

For example, the following should be re-written to use the new `TextEquals` APIs:
https://github.com/aspnet/AspNetCore/blob/9de42d516e6ee9c8eb17700e134f3ac8a7a682ff/src/SignalR/common/Http.Connections.Common/src/NegotiateProtocol.cs#L215-L217

```C#
if (reader.TextEquals(TransportPropertyNameBytes))
```

Similarly here/elsewhere:
https://github.com/aspnet/AspNetCore/blob/9de42d516e6ee9c8eb17700e134f3ac8a7a682ff/src/SignalR/common/SignalR.Common/src/Protocol/HandshakeProtocol.cs#L122-L124

See https://github.com/dotnet/corefx/issues/34938 for more context.

cc @BrennanConroy, @JamesNK

**Comment by BrennanConroy** [comment]
Yeah, I've been waiting for updated bits. We're currently consuming bits from 18 days ago, just a couple commits before your change.
