### ISSUE TITLE
Use a cryptographically strong identifier for circuit ID

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8973]
Since Circuit IDs are sent to clients, we need to use something cryptographically strong (not a guid) - this is similar to a sessions ID

**Comment by blowdart** [comment]
What happens if an attacker starts changing the circuit ID?

**Comment by rynowak** [comment]
The same thing that happens if someone changes their session id? It doesn't match anything on the server. Let's discuss this tomorrow.

**Comment by blowdart** [comment]
:) Session cookie is signed, so you can't just edit it. So Circuit IDs should be the same. Which now means data protection pain.

**Comment by rynowak** [comment]
GOOD

**Comment by rynowak** [comment]
I know who handle this then... (eyes dart towards Spain)

**Comment by blowdart** [comment]
The Data Protection on the plain falls mainly on Javier.

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/pull/10688

**Comment by javiercn** [comment]
The only missing part here is considering using a cookie

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/issues/10717
