### ISSUE TITLE
Make it possible to set SignalR log level in javascript with strings

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8974]
see: https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/ts/signalr/src/HubConnectionBuilder.ts#L30

It would be really useful we we could pass in a string with one of the named values of `LogLevel`. We have a use case for this in Blazor where the user won't be writing typescript and probably won't have SignalR imported.

**Comment by anurse** [comment]
This is quite straightforward and seems like it adds plenty of value for very little cost. Let's do it.

We should make sure to support `info` **and** `information` (along with all the other names). And update the config doc as part of this work.

**Comment by anurse** [comment]
Pre-triage notes:
* Super simple (cost XS) and makes a Razor Components scenario super clean.
* I could take a stab a this (manager value go!)
* Preview 5 candidate.

**Comment by anurse** [comment]
Triage decision: Let's do it!
