### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by Plasma** [aspnet/AspNetCore#8980]
### Describe the bug
When trying to launch an ASP.NET Core 2.2 web app locally (Windows 10) I receive `HTTP Error 500.30 - ANCM In-Process Start Failure` error message when the browser opens.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
1. Configure to use IIS in-process model

### Expected behavior
It to work without error.

### Screenshots
![image](https://user-images.githubusercontent.com/229209/55377964-f362b880-5562-11e9-871e-1f28adec2682.png)

### More information
None of the other bug reports appear to have a resolution.

Is this an Azure only feature, and wont ever work locally? How is it supposed to work locally?

Assuming its the most performant option, can I make it so local development continues to use Kestrel and only production/Release-mode uses IIS in-proc?

Thanks

**Comment by Plasma** [comment]
This also breaks with the same exact message on Azure App Service sometimes when restarting the website. Is it meant to be this broken? :(

**Comment by tonyatl** [comment]
i have the same problem on windows data center 2016 iis 10. i created vs 2017.9 asp.net .net core mvc application - no changes. it runs successfully on windows 10 iis but not on server. i am using asp.net core 2.2.3 runtime. i am running DotNetCore.2.0.8-WindowsHosting and httpPlatformHandler_amd64 and dotnet-hosting-2.2.3-win. the application starts as a kestrel process - ie i run the exe of my application or dotnet myapp.dll

**Comment by anurse** [comment]
Have you looked at the troubleshooting guidance in our documentation? https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.2#50030-in-process-startup-failure

If you still have failures after going through those steps, let us know.

**Comment by Plasma** [comment]
I think I may have a lead on this, at least for local development.

I started my project with using the legacy out of process hosting system, and then later switch to the InProcess system. This seemed to have broken things with this obtuse error.

I then changed the port number and it started to work. Does it have something to do with the applicationHost.config file perhaps?

**Comment by anurse** [comment]
Have you looked at the [Event log](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.2#application-event-log) or [standard output logs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.2#aspnet-core-module-stdout-log) as described in the doc I linked?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by deanilvincent** [comment]
This error appears to me after I accidentally registered the same interface in my `ConfigureServices`

    `services.AddScope<IMyInterface, IMyInterface>();`

Make sure to double check your `Startup.cs` `ConfigureServices`

**Comment by worldspawn** [comment]
I can confirm I also had some dynamic registrations registering an interface as both service type and implementation type. What an astonishingly awful job aspnetcore does of communicating this. We're like one or two steps away from the bad old days of Error 0x80001000.

**Comment by KooshkakiH** [comment]
I get this error and problem was mistake connection string.

**Comment by anurse** [comment]
Just a heads-up that since this is a closed issue we don't track it in our regular issue management processes. If you are still seeing this error and need assistance, please do file a new issue so it gets right in our face :).

@worldspawn these kinds of errors should definitely be reported on the error page when in Development mode. We can't report them in production environments because it's a security risk. If you have a situation where you aren't seeing the detailed error page in development mode (when `dotnet run`ing or launching from VS) please feel free to file a new issue.

**Comment by robinwilson16** [comment]
I got this error and realised I had missed a comma out of the appsettings.json file.
May be worth a try for anyone still getting this issue.

It would be good if it did give a less generic error though to speed up troubleshooting.

**Comment by GerFVersteegGitHub** [comment]
The ANCM error is after I have installed the "Key Vault" for my web app. with ASP.Net Core 2.2
When I remove this function everything goo fine now.

**Comment by edimarmartins** [comment]
Please, check the Database Connection string at appsettings.json and assure the path, user and password is correct

**Comment by GerFVersteegGitHub** [comment]
Hi, when I use a Key Vault than I don't have a Database Connection string in appsettings.json. 
I use the Key Vault for more security. Only in that way I have the ANCM error (only with ASP.net Core 2.2.
With Core 21 there where no problems.
Now I have changed back to work with appsettings.json everything is fine. But the best secure way is with the Key Vault.

**Comment by Diomos** [comment]
I got this error in this scenario:
- registered my own service 'MyService' (tried Singleton, Scope and also Transient)
- tried to inject dbContext in it's constructor

I thought chain dependency injections are supported but apparently not. What baffles me is why I can inject dbContect to controller but not into custom service? Another fact: I was able to inject ILogger<MyService> (log4net version) and that went OK.

**Comment by DimaSUN** [comment]
Work for me

ASP.NET Core 2.2 or later: For a 64-bit (x64) self-contained deployment that uses the in-process hosting model, disable the app pool for 32-bit (x86) processes.

In the Actions sidebar of IIS Manager > Application Pools, select Set Application Pool Defaults or Advanced Settings. Locate Enable 32-Bit Applications and set the value to False. 

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0#create-the-iis-site

**Comment by GerFVersteegGitHub** [comment]
Hi DimaSun,
The ANCM error is not on my local web, but in Azure. How can I change the IIS settings for web aps in Azure? I work with Visual Studio 2019.

**Comment by AHTA** [comment]
This work for me

In the file _MyProject.csproj_ 

I Change this line
`<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>`

For this
`<AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>`

I'm looking for a better solution...

**Comment by GerFVersteegGitHub** [comment]
Hi AHTA,

Sorry, but everything is the same as before. only the error header is changed in Azure:
HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure
I hope you will find something else. Thanks for your devotion

**Comment by eaguerrerov** [comment]
Net Core 2.2
Check your lines "addScope" or "addSinglenton" in Startup.cs, probably you have two o more lines same.

**Comment by GerFVersteegGitHub** [comment]
Sorry Eaguerrerov, this was one of my checks. The only problem is when I work with a "Key fault" in my program. Without the key vault and use the appsettings.json, then every thing is Ok.

**Comment by KhalilHemissi** [comment]
Hi !! 
i want to lunch my api (asp core 2.2)on IIS Server ,  I receive HTTP Error 500.30 - ANCM In-Process Start Failure . 
i configured Web.config , and myProject.csproj and program.Cs . 
the same error .. 
Any One can help me !! thanks

**Comment by eaguerrerov** [comment]
@KhalilHemissi is working with dependency injection in your application asp net core 2.2 ?

**Comment by worldspawn** [comment]
@khalilhemissi this is a generic error and there are many causes. Check the windows event viewer application log for a cause and if you don't find anything there check the log file setup in web.config. Usually ./logs, it's off by default, enable in web.config.

**Comment by KhalilHemissi** [comment]
@eaguerrerov Yes . 
it works on local but when i wanna to lunch it on server IIS ! it causes problem .. 
this is the first time , i deploy app on iis , it can be problem of setup ???
i follow instruction of this documentation : 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2

**Comment by KhalilHemissi** [comment]
@worldspawn
 when i enable stdoutLogEnabled with module AspNetCoreModuleV2 ./log created but files of logs is empty.and when i enable it with module AspNetCoreModule the log files contains :
Hosting environment: Production
Content root path: C:\Deploy\IXIGraphiqueApi\09-DEV
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

**Comment by KhalilHemissi** [comment]
@worldspawn 
 when i enable stdoutLogEnabled with module AspNetCoreModuleV2 ./log created but files of logs is empty.and when i enable it with module AspNetCoreModule the log files contains :
Hosting environment: Production
Content root path: C:\Deploy\IXIGraphiqueApi\09-DEV
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

Thanks for answering ..

**Comment by KhalilHemissi** [comment]
@eaguerrerov  Yes .
it works on local but when i wanna to lunch it on server IIS ! it causes problem ..
this is the first time , i deploy app on iis , it can be problem of setup ???
i follow instruction of this documentation :
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2

Thanks for answering ..

**Comment by KhalilHemissi** [comment]
even when i create a new project api core 2.2 !! it didn't work , same problem !!! :(  :(

**Comment by eaguerrerov** [comment]
@KhalilHemissi 
Try download and install manually asp net core 2.2 in this url. 
No required Visual Studio Installer.

url here:
https://dotnet.microsoft.com/download/dotnet-core/2.2

**Comment by KhalilHemissi** [comment]
@eaguerrerov thanks , i will try but  i have new news !!
I created an MVC Web Application (asp.core 2.2) then i deploy it on IIS and it's works !! 
and re-create and other project but WEB API , but on IIS didn't !!! okay

**Comment by KhalilHemissi** [comment]
@eaguerrerov i re-installed .NET Core SDK 2.2.0 and 2.2.0 Runtime & Hosting bundle.
Finally it works !! thanks a lot

**Comment by NUlliiON** [comment]
Perhaps your problem is that you missed the comma in "appsettings.json"

**Comment by vladlee098** [comment]
In my case we had to change '\' with '/' in one of the path settings in logging.json which was referenced in startup.

**Comment by Kunze** [comment]
I got that error after removing all contents in "appsettings.Development.json". Then I added an empty json object (" { } ") and it started working again.

**Comment by mickey-stringer** [comment]
Apparently many conditions can trigger this error code. In my case, I had to re-authenticate VS with Azure so my Key Vault client could be created,
Running your app from the command line should give you a more specific error output. See https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-2.2#troubleshoot-on-iis

**Comment by KoenvHaren** [comment]
> I got this error and realised I had missed a comma out of the appsettings.json file.
> May be worth a try for anyone still getting this issue.
> 
> It would be good if it did give a less generic error though to speed up troubleshooting.

Brilliant, this solved it for me. This error seems like the dumping ground for whatever exception pops up during startup.

**Comment by joacar** [comment]
Run the application from command line since that might reveal the actual error. First got this generic one and then I ran `dotnet run` and the issue was revealed.

**Comment by mmhgarcia** [comment]
> I get this error and problem was mistake connection string.

A friend had the same problem, the error was in the connection string, wrong host name.
Thanks.

**Comment by ronnygunawan** [comment]
I solved mine by deleting all obj and bin folders then rebuild solution and published it again.

**Comment by arafat198717** [comment]
Thanks you.
I got same problem but It was connecting string error, after correction of connecting string its working.

**Comment by dowla021** [comment]
Same problem (connection string), but in my case it was "SERVER\INSTANCE", after correction to "SERVER\\INSTANCE" it works. 

Thanks for your hints.

**Comment by dowla021** [comment]
Server\\Instance with double backslash...
