### ISSUE TITLE
Browser.JS typescript improvements

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#9007]
* We added eslint to our typescript project.
* We should configure a sensible ruleset that defines our style and rules.
* We should eslint in autofix mode to clean up what we can.
* We should fix the remaining issues as we modify the codebase or do a pass to fix all the issues.

**Comment by SteveSandersonMS** [comment]
If you don't mind, I'm going to fold these notes into #8986 so there's less to keep track of.
