### ISSUE TITLE
Better client-side and server-side logging improvements

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#9008]
* We added logging to the client side.
* We should add more logging in places where there is not enough.
* We should allow users to configure the login level.

**Comment by mkArtakMSFT** [comment]
We do have logging already, so nothing specific actionable here.

**Comment by javiercn** [comment]
Debugging certain types of issues where the UI does not update is incredibly hard. We should have logging statements (debug or trace for the following events).
* Client-side (blazor.server.js):
  * Receiving a new render batch from the server.
  * Receiving a request to invoke a js function from the server.
  * Dispatching an event in response to a UI action.
* Server-side:
 * Receiving a batch confirmation.
 * Receiving a request for invoking a dotnet function from the client side.
 * Receiving a request to invoke an event on the server-side.

Diagnosing issues on customers apps becomes really difficult without these. For example, on a real case, debugging an app where the UI doesn't update

**Comment by mkArtakMSFT** [comment]
Closing as almost everything here are done.
