### ISSUE TITLE
Azure Storage Data Protection SAS token expiration 

### ISSUE THREAD

**Issue by johnayoub** [aspnet/AspNetCore#9012]
### Is your feature request related to a problem? Please describe.
Currently the extension method for persisting the keys to Azure Storage using a sas token will run into issues when the sas token has expired and there's no mechanism to renew it.

### Describe the solution you'd like
I would recommend exposing the `PersistKeystoAzureBlobStorageInternal` method so that a new sas token could be fetched. This could also allow authentication using managed identities which is not currently supported by any of the existing extension methods. It would be nice to have something similar to KeyVault for handling Managed Identity authentication as well

`var azureServiceTokenProvider = new AzureServiceTokenProvider();
 KeyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));`

### Describe alternatives you've considered
I thought about creating an extension method with the same content as `PersistKeystoAzureBlobStorageInternal` as a workaround but would prefer if one is added by the team.

**Comment by johnayoub** [comment]
@blowdart  Any update on this?

**Comment by blowdart** [comment]
It's being discussed now the dev is back from maternity :)

**Comment by johnayoub** [comment]
Thanks! Welcome back :)

**Comment by natemcmaster** [comment]
Have you tried using the overloads of PersistKeysToAzureBlobStorage which don't use a SAS token? For example, you could construct a client using `AzureServiceTokenProvider`, create the container reference, and then call `PersistKeysToAzureBlobStorage(CloudBlobContainer container, string blobName)`

Example:
```c#
            var tokenProvider = new AzureServiceTokenProvider();
            var token = await tokenProvider.GetAccessTokenAsync("https://storage.azure.com/");
            var creds = new StorageCredentials(new TokenCredential(token));
            var storageAccount = new CloudStorageAccount(creds, "mystorageaccount", "core.windows.net", useHttps: true);
            var client = storageAccount.CreateCloudBlobClient();
            var container = client.GetContainerReference("key-container");
            await container.CreateIfNotExistsAsync();

            var services = new ServiceCollection()
                .AddDataProtection()
                .PersistKeysToAzureBlobStorage(container, "keys.xml")
                .Services
                .BuildServiceProvider();
```

**Comment by johnayoub** [comment]
No I haven't but we'll run into the same issue of the managed identity token expiring. I could use the overload of `TokenCredential` as it takes a delegate to renew the token. Also, this is startup code and as far as I know none of the methods are async.

**Comment by natemcmaster** [comment]
> No I haven't but we'll run into the same issue of the managed identity token expiring.

Ah, so like when a long-running app needs to roll new keys? Yeah, try using this constructor: https://github.com/Azure/azure-sdk-for-net/blob/e7dc3b48c8037ee9cd04a428e454088f082e1d8c/sdk/storage/Azure.Storage.Common/src/TokenCredential.cs#L43

Let me know if that doesn't work.

**Comment by johnayoub** [comment]
Sure! I'll go ahead and try it but will this be supported in ASP.NET CORE 3.0?

**Comment by natemcmaster** [comment]
Passing DP an instance of `CloudBlobContainer` is already supported in 2.1. You'll have to use the older version of the Azure SDK (WindowsAzure.Storage), but I believe the API you need to call is present. In 3.0, the only change you'll need to make is to update the namespaces you use because we have updated our dependency on the Azure SDK to the latest version. (See https://github.com/aspnet/Announcements/issues/355)

**Comment by johnayoub** [comment]
That was a silly question on my end. Sounds good, thanks a lot Nate :)

**Comment by natemcmaster** [comment]
Happy to help! Let me know if this doesn’t work.

I think I’ll leave this open on our end. @blowdart I don’t think we need to add new API, but let’s document this. I think using Microsoft.Azure.Services.AppAuthentication to get an auth token is a more user-friendly way to authorize the Azure Storage provider.

**Comment by natemcmaster** [comment]
PR => https://github.com/aspnet/AspNetCore.Docs/pull/12826
