### ISSUE TITLE
Find All References for model type not showing up after scaffolding Razor Pages

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#9013]
.NET Core 2.2 SDK: 2.2.202
VS2019

[WebApplication2.zip](https://github.com/aspnet/AspNetCore/files/3036185/WebApplication2.zip)

Repro steps:
- Open the attached project
- Right click on the *Pages/Products* folder and select Add -> Razor Page
- Scaffold Razor Pages using Entity Framework (CRUD)
- Specify the `Product` model type and the existing data context
- Example the CodeLens annotations on the `Product` class

Actual result:

Razor references for the `Product` type in Razor files don't show up.

![image](https://user-images.githubusercontent.com/1874516/55441171-bb597680-555e-11e9-99e7-9f75b858bfe0.png)

Expect result:

![image](https://user-images.githubusercontent.com/1874516/55441531-0c1d9f00-5560-11e9-907c-b02c0a941190.png)

![image](https://user-images.githubusercontent.com/1874516/55441541-150e7080-5560-11e9-8fdd-0f33b5085417.png)

Workaround:
- Close and reopen the solution

**Comment by danroth27** [comment]
@rynowak

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen can you please have a look at this? Thanks!

**Comment by NTaylorMullen** [comment]
Investigated this and Razor is behaving as expected. That being said here's what's happening:
- Scaffolding creates the files and opens them
- Razor suppresses our global Razor generated .cs file to avoid C# ambiguity errors (we do this for all open docs)
- We start parsing the new files
- No C# buffers seems to be created/assigned to the Workspace to represent the open documents.

I've reached out to the WTE team for further info/clarity.

**Comment by NTaylorMullen** [comment]
Given that this is external tracking the fix to this here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/888224
