### ISSUE TITLE
Add ReconnectPolicyBuilder to SignalR TS client

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#9016]
Epic #8797 

See https://github.com/aspnet/AspNetCore/pull/8566/files#r266168117

```TS
var reconnectPolicy =  new ReconnectPolicyBuilder()
    .withExponentialBackoff()
    .withDelayIntervals(1,2,5,10, 30)
    .maxRetries(5)  //These last two options wouldn't be used with the withDelayIntervals option
    .withConstantDelay(10)
    .build()
```

We'd have to consider how to best handle conflicting options being configured.

**Comment by anurse** [comment]
Triage: This seems like it's a solution waiting for customer problems ;). As soon as we find a need for more configuration in our default policy, we can add this.
