### ISSUE TITLE
Why processPath attribute of aspNetCore tag need full dotnet path under web.config?

### ISSUE THREAD

**Issue by srinudhulipalla** [aspnet/AspNetCore#9021]
I am using Asp.Net Core 2.2 and noticed a weird situation when I deployed my build to server in IIS.

Before deploying the application to IIS, just to make sure I ran the below command:
> **dotnet .\myApp.dll**

My app was deployed to http://localhost:5000 and I can browse the app without any issue.

Later I have hosted the app in IIS and when I browse the app, got an error. And finally I was able to fix the issue by providing full dotnet path in web.config as shown below:

Changed from **<aspNetCore processPath="dotnet" .........**   to
**<aspNetCore processPath="C:\Program Files\dotnet\dotnet" .........**

Is it something known issue in Asp.Net Core or Am I missing anything?

**Comment by ilanthendral** [comment]
I think adding C:\Program Files\dotnet\ to environment path variable help ?

`set PATH=%PATH%;C:\Program Files\dotnet\`

**Comment by srinudhulipalla** [comment]
environment variables can detect the dotnet path. If I do below info command it works, seems there is other issue aground it.
dotnet --info

**Comment by jkotalik** [comment]
You shouldn't need a full path to dotnet. Can you confirm that dotnet is on your path?

**Comment by srinudhulipalla** [comment]
@jkotalik dotnet is at C:\Program Files\dotnet
and I can call the command >dotnet --info and no issues
But if I give full path only it was working in IIS.

**Comment by anurse** [comment]
Have you tried restarting after installing the hosting bundle? IIS runs as a system service and sometimes you have to restart the machine in order to get the environment variables sorted out (even if it's on the PATH in your command prompt).

**Comment by anurse** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#install-the-hosting-bundle for more information on this.

Let us know if that doesn't resolve your problem!

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by vvasanth14** [comment]
Restarting the machine after installing the hosting bundle helped to resolve the issue (y)

**Comment by mcp111** [comment]
Do I need to manually edit processPath="dotnet" to processPath="C:\Program Files\dotnet"?
Why IIS gives error 

Could not load configuration. Exception message: Attribute 'processPath' is required.
--

**Comment by anurse** [comment]
@mcp111 this is a closed issue and is not tracked in our triage process. Please file a new issue.
