### ISSUE TITLE
Relative LaunchUrl in launchSettings.json and KestrelServerOptions

### ISSUE THREAD

**Issue by ilanthendral** [aspnet/AspNetCore#9023]
### Description
If relative url is specified in LaunchUrl, say api/Status, then this gets appended to the applicationUrl for the browser instead of the KestrelServerOptions.

### Reproduction
```
- launchSettings.json    Staging ->
                            applicationUrl: "http://localhost:6000",
                            launchUrl: "api/Status" 

- appSettings.json          Kestrel ->Endpoint->Http  "http://localhost:3001"

- appSettings.Staging.json  Kestrel ->Endpoint->Http  "http://localhost:4001"
```
Kestrel currenty launches http://localhost:6000/api/Status.

### Expected behavior
Browser should launch with http://localhost:4001/api/Status which configured in the Kestrel Server Option instead of applicationUrl (http://localhost:6000) in launchSettings.json.

### Screenshots
```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:6000'.
      Binding to endpoints defined in UseKestrel() instead.
	  
Now listening on: http://localhost:4001
Now listening on: https://localhost:4002
Application started. Press Ctrl+C to shut down.
```

**Comment by Tratcher** [comment]
Launchsettings is self-contained, it's not aware of anything in appsettings. Also note that this is VS launching the browser, not kestrel. 

You're using VS to run the app, correct?

**Comment by ilanthendral** [comment]
Yes that is correct, I am using VS for debugging.

**Comment by Tratcher** [comment]
This is working as expected then, you need to set applicationUrl to what you want to launch. Tooling doesn't know about any of the overrides you're setting in appsettings.

**Comment by anurse** [comment]
Closing as this is by design.
