### ISSUE TITLE
I have created an asp.net web application with ADFS on premisis authentication this was done by .net framework . we have microservices needs to be consumed in .net framework application we want to provide adfs authentication for .net core web services when trying to create api with asp .net core it is not showing on premisis option 

### ISSUE THREAD

**Issue by mukeshmuvva** [aspnet/AspNetCore#9036]
I have created an asp .net framework web application with ADFS on-premises authentication. we have microservices needs to be consumed in .net framework application we want to provide adfs authentication for .net core web services when trying to create api with asp .net core it is not showing on premisis option

**Comment by Eilon** [comment]
Hi @mukeshmuvva , we have a doc on using WS-Fed with ASP.NET Core. It supports both ADFS (on-prem) and Azure AD (cloud). Please follow those steps and let us know if you have any problem.
