### ISSUE TITLE
Compile exception when passing null as component attribute

### ISSUE THREAD

**Issue by AndreasTruetschel** [aspnet/AspNetCore#9038]
### Describe the bug
When `null` is put into a components attribute within a .razor/.cshtml file, a compilation error is reported. 
Example: 
`<NavMenuItem href="/modules" Title="Module" Icon="IconType.ViewDashboard" Match="@(null)">`

The reported error is (freely translated):  

`CS0121: The call does not distinguish clearly between the members or properties "RuntimeHelpers.TypeCheck<T>(T)" and "RuntimeHelpers.TypeCheck<T>(Func<Task>)"`

The razor compiler translates the above attribute assignment to:  

` builder.AddAttribute(37, "Match", Microsoft.AspNetCore.Components.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.Routing.NavLinkMatch?>(null));`

**Comment by rynowak** [comment]
I assume you're seeing this error in the editor, and not when you build from the command line correct?

**Comment by AndreasTruetschel** [comment]
@rynowak Exactly

**Comment by rynowak** [comment]
OK cool then. You're seeing this as result of [some hacks](https://github.com/aspnet/AspNetCore/pull/8975) we had to do in preview 3. We added some new/language features in that release but did have a VS release that would update the editor.

This is already fixed for preview 4.
