### ISSUE TITLE
Workaround for Preview3 ANCM/HB installer problem not working

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore#9040]
@anurse @shirhatti The [workaround](https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md#preview-3) of ...

* Uninstall all hosting bundles.
* Install the Preview2 hosting bundle (`dotnet-hosting-3.0.0-preview-19075-0444-win.exe`) at a command prompt with `OPT_NO_SHAREDFX=1 OPT_NO_RUNTIME=1`.
* Stop was/start w3svc. (Tried a full system restart, too.)

... isn't working.

> The Module DLL 'C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll' could not be loaded due to a configuration problem. The current configuration only supports loading images built for a AMD64 processor architecture.

*Advice?* ... manually delete modules and try again?

**Comment by shirhatti** [comment]
Odd. Shouldn't be the case? AFAIK, we verified that it works

Did you just repro it? If so, @jkotalik might have some questions for you

**Comment by guardrex** [comment]
Yep ... minutes ago.

**Comment by guardrex** [comment]
There's no way to just look at it and know if I have the broken one (i.e., from the version perhaps)?

<img width="226" alt="Capture" src="https://user-images.githubusercontent.com/1622880/55507252-da1e4280-561c-11e9-82fe-89834feb7ac5.PNG">

**Comment by jkotalik** [comment]
The version of ANCM you are showing is the one from preview3 (which shouldn't have been installed in the first place?). Did you install the preview3 hosting bundle originally? 

Uninstall may be broken with the preview3 hosting bundle due to this issue. Can you see if C:\Program Files(x86)\IIS\Asp.Net Core Module\V2 exists with a dll?

**Comment by jkotalik** [comment]
If you have any msi/hosting bundle logs from uninstall of the hosting bundle, can you share those too?

**Comment by guardrex** [comment]
Yes, I installed the Preview 3 hosting bundle when it came out.

I read your remarks on another issue on how uninstall(s) might not get the Preview 3 ANCM off of the machine.

Stand-by ... I have a bunch of log files from all of my troubleshooting attempts. Let me run the uninstall again so that I can give you a fresh uninstall log.

**Comment by guardrex** [comment]
I emailed them. Those are the log files from running the Preview 3 installer and selecting **Uninstall**.

Why is it that if I delete the `C:\Program Files\IIS\Asp.Net Core Module` folder and run the Preview 2 installer that I don't get that folder and the V2 ANCM back?

I was attempting to follow the procedure of @cole-acepph at https://github.com/aspnet/AspNetCore/issues/8249#issuecomment-470341366, where the ANCMs are set aside and physically put back into place. The Preview 2 installer gave me back the V1 ANCM; but if I can't get it to give me a new V2 ANCM, then that procedure isn't going to work.

**Comment by jkotalik** [comment]
> Why is it that if I delete the C:\Program Files\IIS\Asp.Net Core Module folder and run the Preview 2 installer that I don't get that folder and the V2 ANCM back?

Most likely the msi is still installed on the machine somehow. It would be really unfortunate that installing preview3 causes future installs to fail. My guess is that installing the preview2 is not changing anything because the msi version of preview2 is less than the msi version of preview3. @shirhatti for thoughts.

Workaround could be taking a nightly hosting bundle and installing it. If you can't find a nightly, I'll help you.

>What about the VS2019 RTM installer ... can it give me good V2 ANCMs for manual placement over the bad setup provided by the Preview 3 hosting bundle installer?

No, the VS msis are much older than what it is 3.0 preview3.

**Comment by guardrex** [comment]
<img width="294" alt="Capture" src="https://user-images.githubusercontent.com/1622880/55515080-4c981e00-562f-11e9-86ad-2a5ccf8f1fe6.PNG">

### :tada:

... and we're back up and running now. Thanks @jkotalik! :beers:

**Comment by shirhatti** [comment]
> Most likely the msi is still installed on the machine somehow. It would be really unfortunate that installing preview3 causes future installs to fail. My guess is that installing the preview2 is not changing anything because the msi version of preview2 is less than the msi version of preview3. @shirhatti for thoughts.

Yup. That's exactly what happens. The higher version msi gets cached in %windir%\installer. When you try reinstalling preview2 without uninstalling preview3 first, the msi engine uses the higher versioned cached installer as opposed to the one in the preview2 bundle.

**Comment by guardrex** [comment]
`--force` switch would've been nice in this case ... i.e., "Idc what you find installer, give me *your files*."

Wonder about offering the module+schema files in the .NET Downloads pages for each release. If something like this ever happens again, the dev can get the actual module and schema files. We can (and do!) document where they go (although I need to check our docs and make sure that the current locations listed are correct).

The Preview2 installer did give me the V1 ANCM in `inetserv` ... but not the V2 in `Program Files/IIS/Asp.Net Core Module/V2`. *Really glad* that I didn't have to use the crappy old laptop to obtain the files I needed via flash drive for the PC! 🤦‍♂️😅
