### ISSUE TITLE
[Components] Better circuit ids

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#9060]
* We should use 128 bits of entropy for the ids.
  * We should data protect the bits and put them in an http only cookie.
  * We should hash the bits, protect them and use that protected hash as the id for the circuit.
  * Upon connection/re-connection we should grab the circuitid cookie, we should unprotect it, hash it and compare it to the unprotected bits when starting the circuit.

**Comment by rynowak** [comment]
Whatever, you do please review with @blowdart before you are the do. 

> We should data protect the bits and put them in an http only cookie.

How would we do this since you can have multiple circuit Ids (one per tab)?

**Comment by javiercn** [comment]
@rynowak Same way we do with oauth cookies.
Microsoft.AspNetCore.Blazor.<<payload>>

Then we get all the cookies that start with Microsoft.AspNetCore.Blazor and party on

**Comment by blowdart** [comment]
Data Protection is the same thing we do elsewhere, so I'm good with that approach for securing it.

**Comment by mkArtakMSFT** [comment]
This is a dupe of #8973
