### ISSUE TITLE
Difference between Native and Wrapper razor components?

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#9062]

**Comment by enetstudio** [comment]
You should learn to ask questions. This is a nonsensical question. And this site is for serious issues. Go back to Stackoverflow, where some answers to this question are awaiting you. When you finish reading them, please come here to close this issue.

Have a good day...

**Comment by Eilon** [comment]
@kmuthukumar23 can you please provide more information about your question?

**Comment by kmuthukumar23** [comment]
Hi @Eilon ,

thanks for your interest ;)

what i m asked, difference or comparison between pure razor components(blazor) and javascript embedded razor components.
