### ISSUE TITLE
Re-enable SignalR functional tests

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#9069]
After many failures of these tests in #8877, I skipped the entire test suite by adding `<SkipTests/>` to src/SignalR/clients/ts/FunctionalTests/SignalR.Npm.FunctionalTests.npmproj Tests should be examined and re-enabled when failures are understood.

Problem has occurred in multiple Test&hellip; jobs but affected mostly the macOS job in #8877.

See https://dev.azure.com/dnceng/public/_build/results?buildId=142691 for example.

@anurse please added any further labels and otherwise do the needful.

**Comment by BrennanConroy** [comment]
>Problem has occurred in multiple Test… jobs

I only saw it fail on macOS, could you link other failures?

**Comment by dougbu** [comment]
I remember one of the builds for #8877 saw this failure in the Test: Windows Server 2016 x64 Job. I'll look back through the history to find it&hellip;

**Comment by dougbu** [comment]
Ah, it was an @anurse PR's build: https://dev.azure.com/dnceng/public/_build/results?buildId=142443

**Comment by dougbu** [comment]
Different test group but similar `yarn` exit

**Comment by BrennanConroy** [comment]
All yarn exits will look the same. But it's completely different tests with completely different failures most likely.

You can see I just added test reporting for SignalR TS tests at https://github.com/aspnet/AspNetCore/pull/9058

Components should do a similar thing so we can actually see what the failures are.

**Comment by BrennanConroy** [comment]
@dougbu I think we can close this now?

**Comment by dougbu** [comment]
Yup
