### ISSUE TITLE
[Components] Add signalr service E2E integration test

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#9071]
We should have a test to validate that our assumptions for server-side blazor work with the signalr service and that we don't break things by mistake.

**Comment by mkArtakMSFT** [comment]
Let's just add a scenario for CTI folks to handle

**Comment by danroth27** [comment]
I'll take care of this.

**Comment by danroth27** [comment]
This is covered today: https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.1/E2EWalkthroughs/VS/AspNetCore30/30_SimpleWebAppWithServerSideBlazor.md. We'll need to update this test once the SignalR detection logic is available with d16.2.
