### ISSUE TITLE
Blazor app publish "Self Contained" doesn't work

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/AspNetCore#9072]
### Steps to reproduce the behavior:
1. Create `Blazor (ASP.NET Core hosted)` project
2. Right click on `Server` project and select `Publish`
3. In `Pick a publish target` window click `Advanced` (on the left I have `App Service` selected)
4. Change `Deplyment Mode` to `Self Contained` and click `Save`
5. In `Pick a publish target` window select `Select Existing` and click `Publish`
6. If necessary login to Azure and select App Service.
7. Click `OK` - publishing process starts and in a few seconds you will see
![obraz](https://user-images.githubusercontent.com/32604409/55570374-9e11dd00-5703-11e9-8b96-1c46877b7509.png)
and the following error is displayed in the `Error List` window:
> Metadata file 'D:\Blazor\PublishTest\PublishTest.Client\bin\Release\netstandard2.0\win-x86\PublishTest.Client.dll' could not be found

There is no `win-x86` folder and `PublishTest.Client.dll` file is only here:
d:\Blazor\PublishTest\PublishTest.Client\bin\Release\netstandard2.0\PublishTest.Client.dll

### Additional context
Tested on VS 2019 Preview 5.0, Blazor 0.9, ASP.NET Core 3.0 Preview 3, Windows 10 1809 x64 

 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by danroth27** [comment]
Thanks for reporting this @Andrzej-W!
Looks like the same issue as #9285. Since we're currently looking at this for Preview4 I'm going to close this as a duplicate.
