### ISSUE TITLE
<text> tags should not be rendered 

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#9090]
In a component, the following code results in the `<text>` tag showing up in the output instead of being omitted.

```
<div class="footer">
    @if (_sections.TryGetSection("footer", out var footer))
    {
        @footer
    }
    else
    {
        <text>Copyright 2019.</text>
    }
</div>
```

The `<text>` is needed in this case because the inside of the `else` is in the C# context. We need to transition back to markup which requires `@:` or a tag. 

![image](https://user-images.githubusercontent.com/1430011/55592834-95fb7280-56ee-11e9-9741-49efb0e42dfd.png)

In generated code 

```
builder.AddMarkupContent(31, "<text>Copyright 2019.</text>");
```

**Comment by ajaybhargavb** [comment]
Moving this to preview4 as this is fixed.
