### ISSUE TITLE
Razor Components project template doesn't have a favicon.ico

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCore#9096]
All our other web app templates have a `favicon.ico` in the `wwwroot` folder. We should probably have the same one in the Razor Components project template too. Without it, Chrome makes a request anyway then shows an error in the dev console which is less than pleasant.

![image](https://user-images.githubusercontent.com/249088/55595794-5175d400-56fa-11e9-80ac-7812d9a16519.png)

@danroth27

**Comment by danroth27** [comment]
@SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
Oh, I only just removed the `favicon.ico` for "consistency". I guess that was wrong then. Will put it back.
