### ISSUE TITLE
Question: When will there be a 1.0 (Non-experimental) release of Blazor?

### ISSUE THREAD

**Issue by SeppPenner** [aspnet/AspNetCore#9103]
We are planning to use Blazor in some project(s) but are waiting for a 1.0 release. Is there a roadmap when it will (probably) come? Can we expect it to be available in Q3 of 2019?

**Comment by danroth27** [comment]
Support for server-side Blazor is shipping with .NET Core 3.0 and should be available later this year.

The roadmap for client-side Blazor on WebAssembly is still to be determined.

**Comment by SeppPenner** [comment]
I guess, it's answered now: https://github.com/dotnet/core/blob/master/roadmap.md:

> .NET Core 3.0: RC (Release Candidate) scheduled for July 2019
> .NET Core 3.0: GA (General Availability) scheduled for September 2019
