### ISSUE TITLE
SPA templates need to be updated for endpoint routing

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#9108]

**Comment by javiercn** [comment]
@JamesNK Seems like you left these puppies behind :(

**Comment by rynowak** [comment]
Awww don't call them puppies, it makes me sad to think of puppies being left behind.

**Comment by javiercn** [comment]
@rynowak That way I encourage you both to fix them. 🐶

**Comment by ryanbrandenburg** [comment]
Could I get some context on this? A link to the issue for the work which drove this would be helpful. A link to existing examples or descriptions of best practices would also be good.

**Comment by javiercn** [comment]
Look at the configure method on the startup class for the razor pages templates. Those use endpoint routing. You can probably figure out the rest from there. If not, @rynowak or @JamesNK can probably help you, but I trust you'll figure out.

**Comment by isaac2004** [comment]
@javiercn is this statement from the routing docs no longer true for 3.0?

>  Note
>
> With the release of endpoint routing in ASP.NET Core 2.2, endpoint linking is limited to MVC/Razor Pages actions and pages. The expansions of endpoint-linking capabilities is planned for future releases.
