### ISSUE TITLE
[SPA templates] React service-worker interferes with identity.

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#9110]
When publishing a react app with individual auth on, react includes a service-worker by default. This service-worker captures all the requests for identity/identity-server so they never make it to the server.

**Comment by javiercn** [comment]
Seems like we are using an ancient version of react scripts. Updating it seems to fix it.

**Comment by blowdart** [comment]
@javiercn Does this mean you checked-in updates to use the latest react and we can close this?

**Comment by javiercn** [comment]
I updated the react scripts and got rid of the problem
