### ISSUE TITLE
Can no longer use templated parameters on components in a library project

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#9114]
Again, maybe this will get fixed by the ongoing SDK work, but raising this to track it anyway. Apologies if I'm being excessively fussy.

I've not been successful in upgrading my Material Design components library to work with the preview 4 code due to the following.

### Repro

* Using .NET Core 3.0.100-preview4-011074 and Microsoft.AspNetCore.Blazor.Templates.0.9.0-preview4-19204-04, create a new Blazor (client-side) standalone and Blazor library alongside each other:
    * `dotnet new blazor -o MyStandalone`
    * `dotnet new blazorlib -o MyBlazorLib`
* Apply workarounds to the Blazor standalone app so you can run it
    * Add `<RazorLangVersion>3.0</RazorLangVersion>` and `<GenerateRazorAssemblyInfo>false</GenerateRazorAssemblyInfo>` to its csproj
    * Check it builds and runs
* Apply workarounds to the Blazor library project so you can build it
    * Add `<RazorLangVersion>3.0</RazorLangVersion>` and `<GenerateRazorAssemblyInfo>false</GenerateRazorAssemblyInfo>` to its csproj
    * Check it builds
* Add a project reference from `MyStandalone` to `MyBlazorLib`
* In `MyStandalone`'s root `_Imports.razor`, add `@using MyBlazorLib`
* In `MyStandalone`'s `Index.razor`, add a `<Component1 />`
    * See it runs and renders the component from the library correctly
* In `Component1.razor`, try to add two parameters:

```cshtml
@functions {
    [Parameter] string SomeString { get; set; }
    [Parameter] RenderFragment<DateTime> SomeDateThing { get; set; }
}
```

* **Problem 1:** For some reason, `ParameterAttribute` and `RenderFragment` aren't in scope, even though (AFAIK) the compiler is meant to add `@using Microsoft.AspNetCore.Components` implicitly
    * Workaround: Explicitly add `@using Microsoft.AspNetCore.Components` to the top of `Component1.razor`
* Now try to pass values for these parameters. Back in the other project's `Index.razor`, see that it is aware that both parameters exist:

![image](https://user-images.githubusercontent.com/1101362/55638377-eb06b980-57be-11e9-92fd-4497e7d4b685.png)

* You can successfully pass a value for `SomeString`. See it lights up correctly:

![image](https://user-images.githubusercontent.com/1101362/55638703-ba734f80-57bf-11e9-8278-3d0e94567d6b.png)

* **Problem 2:** You *cannot* pass a value for `SomeDateThing`. Intellisense doesn't show it as an option, and it doesn't light up in purple:

![image](https://user-images.githubusercontent.com/1101362/55638433-17bad100-57bf-11e9-8ae8-14178a59f987.png)

It's not just a VS thing. It's really broken at compile-time. If you try to reference the `@context` value (since this is a parameterised template), the compiler doesn't know what you're talking about. The build will fail.

![image](https://user-images.githubusercontent.com/1101362/55638503-4042cb00-57bf-11e9-976f-6153c9d8da19.png)

* **Problem 3** The error list shows completely different errors. The build output only gives one error (`The name 'context' does not exist in the current context`), but VS shows:

![image](https://user-images.githubusercontent.com/1101362/55638600-7bdd9500-57bf-11e9-9a53-a230544d0180.png)

@rynowak @pranavkm

**Comment by rynowak** [comment]
@ajaybhargavb

**Comment by rynowak** [comment]
> Again, maybe this will get fixed by the ongoing SDK work, but raising this to track it anyway. Apologies if I'm being excessively fussy.

You're not being fussy, this is regression and an absolutely show-stopping bug.

**Comment by rynowak** [comment]
I can confirm that this repoduces in a server-side blazor app.

**Comment by ajaybhargavb** [comment]
Sent a PR with the fix for Problem 2. Problems 1 and 3 refer to the same issue and @pranavkm is working on fixing those.

**Comment by ajaybhargavb** [comment]
The workaround for Problem 2 for design time btw is to use fully qualified component tags,

```cshtml
<MyBlazorLib.Component1 SomeString="Hello">
    <SomeDateThing>@context</SomeDateThing>
</MyBlazorLib.Component1>
```
will work fine in both design-time and runtime.

**Comment by ajaybhargavb** [comment]
@pranavkm, could you link the commits for your fix and close this issue?

**Comment by pranavkm** [comment]
Verified using 3.0.100-preview4-011136 that the remaining issues are fixed.
