### ISSUE TITLE
OnInit() called twice

### ISSUE THREAD

**Issue by dkurok** [aspnet/AspNetCore#9116]
### Describe the bug
The OnInit()-event is called twice / handler runs twice

### To Reproduce
1. Visual Studio 2019; create new project using Razor components template
2. In MainLayout.razor add the following to the end of the file:
`@functions{      protected override void OnInit()
    {
        base.OnInit();
        Console.WriteLine("OnInit called");

    }
}`
3. Place a breakpoint on the Console.WriteLine-call in OnInit()
4. Debug and see in Output -> ASP.NET Core Web Server:
The breakpoint will be hit twice! From what I've read it should only be hit once at the initialization of the component

### Expected behavior
OnInit() should only be called once

### Additional context
Visual Studio Enterprise 2019 Version 16.0.0 on Windows 10, 1809

**Comment by dkurok** [comment]
Addon: It is .NET Core 3.0 (3.0.100-preview3-010431) (otherwise there wouldn't be no Razor components template)

**Comment by Andrzej-W** [comment]
In razor components template prerendering is enabled. In YourApp\YourApp\Pages\Index.cshtml file there is line
```html
<app>@(await Html.RenderComponentAsync<App>())</app>
```
Change it to
```html
<app></app>
```
Of course now prerendering doesn't work.

**Comment by dkurok** [comment]
Great, this works!
Is there somewhere a deeper explanation for that behaviour and intention of the prerendering? I want to use a dynamic nav-menu (rendered from DB-content depending on user's rights); I fill a List<menuEntry> at the very beginning (in OnInit())  but saw this gets called twice. Can I "ask" for a status like "isInPrerendering" or alike? found just a very small introduction of prerendering in the announcements of ASP.NET Core 3.0 preview

**Comment by Andrzej-W** [comment]
@dkurok Temporary solution for "isPrerendering": https://github.com/aspnet/AspNetCore/issues/8404#issuecomment-471802300
Discussion about problems during prerendering: https://github.com/aspnet/AspNetCore/issues/8786
It is now closed and should be releases in preview 4.
Here you can see prerendering in action (great demo by Steven Sanderson)
https://www.youtube.com/watch?v=0RfUPr0KrSM&feature=youtu.be&t=2818

**Comment by danroth27** [comment]
Thanks for answering, @Andrzej-W
