### ISSUE TITLE
[Tooling] Blazor Libraries are treated as 2.1 MVC at design time 

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#9119]
### Describe the bug
Basically Blazor libraries do not work in tooling. They're treated as MVC 2.1 projects. In order to work around this you need to currently do 2 things:

1. Add `<RazorLangVersion>3.0</RazorLangVersion>`
2. Add `<AddRazorSupportForMvc>true</AddRazorSupportForMvc>`

Then it treats the components properly. I'm not confident if we want the `AddRazorSupportForMvc` bit there but currently it's the only way to force the `DefaultRazorConfiguration` to be something other than `Default`. 

The reason why this is currently an issue is that when `DefaultRazorConfiguration` is `Default` the IDE lifts that and interprets it as MVC 2.1. Therefore it doesn't understand components and generates the pages as if they were normal views:
![image](https://user-images.githubusercontent.com/2008729/55644097-b2002200-5789-11e9-8cd1-cd629d567014.png)

**Comment by NTaylorMullen** [comment]
Here's binlogs/logs for this as well if it helps: \\NTaylorMullen2\SHARED\BlazorLogs

**Comment by pranavkm** [comment]
Closing this as the immediate issue is resolved. We'll use https://github.com/aspnet/AspNetCore/issues/9126 to track fixing this in tooling and removing workarounds.
