### ISSUE TITLE
Resolve potential conflicts between CORS and HTTP method metadata

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#9127]
See here: https://github.com/aspnet/AspNetCore/pull/9099#discussion_r272421570

MVC is smart enough to figure this out, but it's not incredibly obvious. The HttpMethod metadata contains a setting that says whether the endpoint is CORS aware or not. It's not clear how you could use a convention to correctly enable CORS for a random endpoint.

**Comment by mkArtakMSFT** [comment]
Closing as we won't find time doing this.
