### ISSUE TITLE
Change default LanguageVersion to Latest prior to 3.0 RTM

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9129]
In runtime compilation, we need to assume LangVersion.Preview during 3.0-preview releases when no value is specified in the deps file. 
Prior to RTM, this needs to be changed to `LangVersion.Latest`. This matches Roslyn's versioning strategy.

**Comment by Eilon** [comment]
What is this a change in? Templates? MVC/Razor compilation? Our own build infrastructure?

**Comment by pranavkm** [comment]
This would be in code (runtime compilation): https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Razor.RuntimeCompilation/src/CSharpCompiler.cs#L214-L217
