### ISSUE TITLE
Fixup Blazor template names

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#9132]
Here's what the Blazor template names should be both on the CLI (template.json) and in VS (vs-2017.3.host.json):

Blazor (client-side)
Blazor (ASP.NET Core hosted)
Blazor (server-side)

**Comment by MarkStega** [comment]
I'm good with the names, but for those newly introduced to Blazor consider:

Blazor (client-side)
Blazor (client-side + ASP.NET Core host)
Blazor (server-side)
