### ISSUE TITLE
VS shows documentation for attributes when writing the component tag

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9133]
![image](https://user-images.githubusercontent.com/174281/55659790-1afe8e80-57b8-11e9-883d-fe85f41156f9.png)

Reproduced using 3.0.0-preview4 SDK and d16.1stg

**Comment by rynowak** [comment]
The fix for this would be in WTE. They build the tooltip.

**Comment by mkArtakMSFT** [comment]
@danroth27 can you please follow up with the tooling team so that this can be fixed? Thanks!

**Comment by danroth27** [comment]
Adding @NTaylorMullen since he was seeing something similar in VS Code as well.

**Comment by NTaylorMullen** [comment]
Ya there's a good chance the way we're generating bind, event handlers etc. TagHelperDescriptors may be resulting in this behavior. Would have to investigate more. Either way it's consistent in VSCode.

**Comment by rynowak** [comment]
That's because you implemented tooltips the same thing WTE does.

 IDK how we would generate different descriptors without redoing everything. What we generate is "correct" - but we don't like how that displays, so we should change how it displays.

**Comment by danroth27** [comment]
Assigning to Taylor as he still believe this is under our control.

**Comment by mkArtakMSFT** [comment]
This should be fixed already.

**Comment by NTaylorMullen** [comment]
> This should be fixed already.

Wait really? When?

**Comment by mkArtakMSFT** [comment]
@rynowak?

**Comment by rynowak** [comment]
IDK LOL?

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen please follow up on this. Let's either get this fixed, if we can do it on our own, or please follow up with the owners to get this fixed.
