### ISSUE TITLE
New Razor components project shows warning about not found `components.server.js` file

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#9138]
Create Razor Components project, open index.cshtml file then meet a warning:
`File 'C:/Users/.../Pages/_framework/components.server.js' not found.`

**Comment by rynowak** [comment]
This is WTE - not us.

**Comment by javiercn** [comment]
Yep. I believe @danroth27 is tracking this.

**Comment by rynowak** [comment]
If we want a direct solution to this we could add a static readonly property to something, so this appears in your code as:

```razor
<script src="@ServerSideBlazor.DefaultScriptPath"></script>
```

That would resolve this warning - I'm not sure if we see this as an overall good thing to hide the script path.

**Comment by SteveSandersonMS** [comment]
I'd strongly prefer that the real underlying bug is fixed (in WTE) rather than us layering on a hack that diminishes the developer experience.

**Comment by javiercn** [comment]
Agree with @SteveSandersonMS 

Its very likely that static content from libraries will also suffer from this, so I think we will have to collaborate on a solution.

**Comment by danroth27** [comment]
This has been fixed in the latest VS preview.
