### ISSUE TITLE
Changes to Razor Component pages are not reflected - Preview 3

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#9142]
When I change any page in Component|Pages|index.razor or any other page, save and run, I don't see the new changes.

Steps:
Very easy, just change a page, save it and run it.

Same behavior shows on FF and Chrome.
This is the latest version I'm running.

Update: I changed the counter page to add 2 to each count, and that works. But if I make any changes to static text, do not get updated on the next run.

![index](https://user-images.githubusercontent.com/7861196/55672245-db42b000-5866-11e9-8331-fb770784312c.jpg)
![index-razor](https://user-images.githubusercontent.com/7861196/55672246-dbdb4680-5866-11e9-902f-02c4dd87197e.jpg)

**Comment by BenHayat** [comment]
Is anyone experiencing this? Band new installation of .Net core preview 3 with VS2019. I create a basic app. 

If I change anyone of the component text the first time, I build and run, I see the changes at runtime. After that any new changes are ignored.
I cleared Browser cache but no help.

How are people are progressing with this bug? Am I doing something wrong?
Could someone from the team shed some light on this?
Thanks!

**Comment by BenHayat** [comment]
**Update - How to get around it.**
Every time I make changes and save, before I run, I  need to do a "clear Solution", then I see the new changes.

**Comment by danroth27** [comment]
Yes, this is a know problem with Preview3 😢. Fortunately, this has been fixed for Preview4.
