### ISSUE TITLE
Documentation for startup analyzer endpoint routing warning

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#9143]
https://github.com/aspnet/AspNetCore/blob/69f4b6d227bb8b3e809b0c99855d8a253637da90/src/Mvc/Mvc.Analyzers/src/Startup/StartupAnalyzer.Diagnostics.cs#L18

This help link currently goes to https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing

Before 3.0 final the link should point to an article on migrating MVC from 2.0 to 3.0

// @rynowak

**Comment by rynowak** [comment]
Assigning myself. I'm planning to have this content available as part of the preview 4 rollout.

**Comment by rynowak** [comment]
We have a link. @JamesNK since you own that link, can you please update it:

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#use-mvc-without-endpoint-routing

**Comment by JamesNK** [comment]
donezo

**Comment by rynowak** [comment]
Thanks Jimmy!

**Comment by JamesNK** [comment]
np rayray
