### ISSUE TITLE
Aspnet core with azure Ad failing only when hosting on docker

### ISSUE THREAD

**Issue by pauloortins** [aspnet/AspNetCore#9146]
I have an aspnet.core project that is using Azure Ad to authenticate. Everything works ok if I run it on localhost or if I host it on Azure. When using docker it works locally but it not works when I host my docker image on azure. I'm seeing an error like that:

No webpage was found for the web address: https://xxxxx.azurewebsites.net/signin-oidc

And this is what I see on the server logs:

`Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[14]
.AspNetCore.Correlation. state property not found.
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
       An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login. ---> System.Exception: Correlation failed.
--- End of inner exception stack trace ---
at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler1.HandleRequestAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)`

I'm using basically the same code that is provided by the Visual Studio Template:

```c#

   public void ConfigureServices(IServiceCollection services)
    {
        services.Configure<CookiePolicyOptions>(options =>
        {
            // This lambda determines whether user consent for non-essential cookies is needed for a given request.
            options.CheckConsentNeeded = context => true;
            options.MinimumSameSitePolicy = SameSiteMode.None;
        });

        services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
            .AddAzureAD(options => Configuration.Bind("AzureAd", options));

        services.AddMvc(options =>
        {
            var policy = new AuthorizationPolicyBuilder()
                .RequireAuthenticatedUser()
                .Build();
            options.Filters.Add(new AuthorizeFilter(policy));
        });


        services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseExceptionHandler("/Home/Error");
            // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
            app.UseHsts();
        }

        app.UseHttpsRedirection();
        app.UseStaticFiles();
        app.UseCookiePolicy();

        app.UseAuthentication();

        app.Use(async (context, next) =>
        {
            context.Request.Scheme = "https";
            await next.Invoke();
        });

        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");
        });
    }
```

**Comment by blowdart** [comment]
Can you capture a fiddler trace, or something shows us the OIDC login flow?

**Comment by pauloortins** [comment]
The flow is:

POST https://login.microsoftonline.com/xxx-xxx-xxx/login HTTP/1.1 200
POST https://login.microsoftonline.com/kmsi HTTP/1.1 200
POST https://content-provider-web.azurewebsites.net/signin-oidc HTTP/1.1 404

This one results in a 404. 

POST https://content-provider-web.azurewebsites.net/signin-oidc HTTP/1.1
Host: content-provider-web.azurewebsites.net
Connection: keep-alive
Content-Length: 1887
Cache-Control: max-age=0
Origin: https://login.microsoftonline.com
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Referer: https://login.microsoftonline.com/kmsi
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: .AspNetCore.OpenIdConnect.Nonce.CfDJ8AuPpRF4EmhDnvcdOrlkcD_MBv5cV34kmvH5pgPiQ6eALCucji7KFFV6-LMVayvxTgb85HDZFt3mefGl19dsM4irr1OZ4Iw6xHcbRKAie1wGROKAWS2Sv8SdizcmpZk4M5MD-cQhUOMWayyG9zOJuTavrlocimLIeXzDq3WjdaGw0PVBG5Cd2e3at7GK4uHv54ndhpt-WpTHvIN6EHLv83GHOp1hHRbjDpEfuCj40_Q-hDULm1WQUkI1cNaXQnmZT3g-DQtSClzT4_t7R4Vnomg=N; .AspNetCore.Correlation.AzureADOpenID.paMMzlwE52ZOQEHhOkABIF9d_ylzVitSUCqUbUyEQjk=N

id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik4tbEMwbi05REFMcXdodUhZbkhRNjNHZUNYYyIsImtpZCI6Ik4tbEMwbi05REFMcXdodUhZbkhRNjNHZUNYYyJ9.eyJhdWQiOiIwNTllMjk4NC04MjMxLTRjNWEtOTA3ZS00MGUzYzUzM2I0NjciLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zNzAwZjg1Ny03OTY0LTQwMjktOWRiNC1hNzFjZjcyZjViNmMvIiwiaWF0IjoxNTU0NzIzOTAzLCJuYmYiOjE1NTQ3MjM5MDMsImV4cCI6MTU1NDcyNzgwMywiYWlvIjoiNDJaZ1lJaDIzblE5MERKcUtiK2JMdHVMc0RXaGlwYVgveTgxRkorOXNmajRLNis4QjVrQSIsImFtciI6WyJwd2QiXSwiZmFtaWx5X25hbWUiOiJPcnRpbnMiLCJnaXZlbl9uYW1lIjoiUGF1bG8iLCJpcGFkZHIiOiIxNzcuNDIuMTE1LjE3OCIsIm5hbWUiOiJQYXVsbyBPcnRpbnMiLCJub25jZSI6IjYzNjkwMzIwOTk1ODk2MjQ1Ni5OR1UwWmpkak0yUXRZVFpsTmkwMFpEUTRMV0kxT0RjdE9UUTBaVGcyWmpnd1pUTTJNRGRrWldNNU16RXRPR1V4TVMwME5EWXpMVGc1TURndE9USXlZelV3WkdWbE5ETTIiLCJvaWQiOiJmYjc0Y2RkYi1iMmM1LTRhMTEtYTk1OS0yNjk0OGZhYzQyYzciLCJzdWIiOiI0WWlkSGR5NUJDT0xiZTdTbVZXeHZGTm55R0djd2ZkWEVBTEVvckFxYXZjIiwidGlkIjoiMzcwMGY4NTctNzk2NC00MDI5LTlkYjQtYTcxY2Y3MmY1YjZjIiwidW5pcXVlX25hbWUiOiJwb3J0aW5zQHZlbmFkb3RlY2guY29tIiwidXBuIjoicG9ydGluc0B2ZW5hZG90ZWNoLmNvbSIsInV0aSI6IkZNX2g5ajQ1YkVDQmJ5ajV4Qm91QUEiLCJ2ZXIiOiIxLjAifQ.Pf0lADHG9CI9dYDc9ESRGdv8CquG7rVTdfPh-y_rkNw_oJlyxt31F6ifoQQh8ujg-HjSgx1jZuv4VHR4Ac7fygzns8Wg8pPs1FpHrZlVjP4qEpbJ8hIDgM42uPpREcpPqrSz2YRwjE7trpl0bPwTGArQMKJhoVh3jR2Ma350myKlWa_P30LiPv54EDdmglyuSgq5CrL8tc3Z9plaZjWNMR7QSo4YNYBqu2PbqvPSVYRFvvoKmz3yLZuTlYh75ImtWfR2N14x4evATNv53Qls6Cy45uDBO5p63hFQ3b0jbrt8PaNYGiQ8ak5Omq3Cq5CG2pMb-cr3IKbKnOhyCghd_A&state=CfDJ8AuPpRF4EmhDnvcdOrlkcD_OHDDzC7LOZQPDB9HfOit-Q_HL8uEvjWXoKfbzh8BGJWMmFOawu56mV4w9qXE4y4ePoN7-wB6_m0J4VZa3I9We1vUcf4zCfl90DeCwBjZQJmBLoqxH7G_Np0kfOZY9wiBYPD9C0OzCm7DZpFWMft5Ty7-sgR6sdNnj1uBpot_6SLXHZBW4YhrMC1ww49wYCYQYPaQ6Lc7_03535Q06_1PE40dRarsoKPIZ15BcF1vsgGkapax5AIWn8__L-eqZAVItz-ZQGGL3agPNlonqDbJLi60wKoUakmQnrTO1pgeMi9Io-ZfgE3dRMaS7j3jAIAiOKX59wPVRsUK-vHNg4l-9EIVmnz3QpsQZJMkschWYsQ&session_state=34f66f7d-bad7-4c0a-9e65-3d803cc03eed

Only on docker/azure. I have another app with the same code but published without docker and it's working perfectly.

**Comment by Tratcher** [comment]
Note this hack is a last resort (see https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2 and https://github.com/aspnet/AspNetCore/issues/4135):
```
        app.Use(async (context, next) =>
        {
            context.Request.Scheme = "https";
            await next.Invoke();
        });
```

And it needs to go before everything else.

However I don't think that would cause a 404 here. Also, that error log shouldn't cause a 404 unless "/Home/Error" is missing.

".AspNetCore.Correlation. state property not found" Is a very unusual error, I haven't seen anyone achieve that without heavily customizing the auth components.
https://github.com/aspnet/AspNetCore/blob/d8381656429addead2e5eb22ba1356abfb419d86/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L218
It implies that the state field in the request was properly decrypted to an AuthenticationProperties collection, but that the collection was missing a value.

You could try hooking into the OnMessageReceived event and logging the contents of the AuthenticationProperties collection. https://github.com/aspnet/AspNetCore/blob/74bba27f4389c5a064cc6b9c417af2b3237e89d4/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L510

**Comment by Eilon** [comment]
If you haven't solved this yet, could you please provide an app that reproduces this issue? That will help us investigate this.

**Comment by pauloortins** [comment]
Guys, I had it on the blocked column and suddenly it started to work. I will keep an eye on it.

**Comment by Eilon** [comment]
@pauloortins thanks for the update. I'll close this issue because we currently can't reproduce the issue anyway. If you see this come up, please let us know so we can take another look.
