### ISSUE TITLE
Broken link in Blazor README

### ISSUE THREAD

**Issue by lol768** [aspnet/AspNetCore#9147]
https://github.com/aspnet/AspNetCore/tree/master/src/Components#blazor

>To see Blazor in action, check out _Steve Sanderson's demo_ at NDC London. You can also try out a simple live Blazor app.

Directs to https://www.youtube.com/watch?v=Qe8UW5543-s which states "This video has been removed by the user"

**Comment by mkArtakMSFT** [comment]
@danroth27 moved this to `preview6` milestone given that it's been delayed so long. @javiercn the referenced issue related to a failing test is blocking this PR from being merged. Please fix that so we can proceed here and merge the associated PR.

**Comment by conficient** [comment]
Looks like this moved to https://www.youtube.com/watch?v=0RfUPr0KrSM&t=1417s ?

**Comment by conficient** [comment]
May want to close this, @danroth27 is rewriting it in #9769

**Comment by lol768** [comment]
Thanks folks
