### ISSUE TITLE
HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure

### ISSUE THREAD

**Issue by bluebaroncanada** [aspnet/AspNetCore#9151]
After wading through tons and tons of documentation and errors, I believe I have a truly unique underlying issue.

Right now I'm getting `Failed to start application '/LM/W3SVC/31/ROOT', ErrorCode '0x8007023e'.` in my event viewer.

The most common error I've had is
`Application '/LM/W3SVC/31/ROOT' with physical root 'C:\Inetpub\vhosts\tmlinc.net\subdomains\cd\' failed to start process with commandline 'dotnet .\test.dll' at stage 'CreateProcessW', ErrorCode = '0x80070002', assigned port 19731, retryCounter '0'.`  which I cannot find anywhere.  It seems to be unique.

I'm getting either 500 or 502 errors.  ACNM seems to be the issue.
I've tried enable debug output, but no output log is produced.
```
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\test.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="InProcess">
	    <handlerSettings>
    <handlerSetting name="debugLevel" value="file" />
    <handlerSetting name="debugFile" value="c:\temp\ancm.log" />
  </handlerSettings>
	  </aspNetCore>
    </system.webServer>
  </location>
</configuration>
```

I repaired(reinstalled) .Net Core 2.2.3.  Installed VC++ Redistributable
I've also tried OutOfProcess.
I can run with `dotnet .\test.dll`.  It opens up port 5000 and I can connect in a local browser.
I have tried enabling stdoutlogfile.  I get empty log files.
I tried taking everything out of my `main()` and replacing it with `Console.WriteLine("test")` and `File.WriteAllLines("abc", new List<string>(){"test"});`

I have tried setting `AspNetCoreModuleV2` to `AspNetCoreModule`.
I think I'm out of things to try here.

**Comment by bluebaroncanada** [comment]
Here's a list of related documents I have looked at:
https://github.com/aspnet/AspNetCore/issues/4566
https://github.com/aspnet/AspNetCore/issues/5973
https://github.com/aspnet/AspNetCore.Docs/issues/8555

https://github.com/aspnet/AspNetCore/issues/8134 - Doesn't apply.  I have recreated two brand new trivial projects in both Rider and Visual Studio.

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference?view=aspnetcore-2.2

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.2#iis-configuration
Added note about this one: We have several other .Net Framework projects running

https://github.com/aspnet/AspNetCore/issues/6111 
This one looked the most promising.  One of the solutions had 9 upvotes, but I just got a different error.  I later found from the event viewer the error was telling me `Microsoft.AspNetCore.App` is an invalid value.  It has to be either InProcess or OutOfProcess.  This is also where I learnt to turn on the logger for ACNM, but I'm getting no output from that.

It's quite possible that some combination of information in these documents is a winner.  I just haven't found it.

**Comment by jkotalik** [comment]
My initial guess is that the folder you are trying to use doesn't have permissions to be used by IIS. 0x80070002 is an error code for FileNotFound. Make sure  that the folder that your published application is in has permissions to IIS_IUSRS. https://stackoverflow.com/questions/14934006/iis-iusrs-and-iusr-permissions-in-iis8 for more info.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by efsandino** [comment]
I have to comment, that I got this fucking error... but I restarted the server and everything worked nice !

**Comment by anurse** [comment]
@efsandino Feel free to file a new issue with the details if you're seeing a problem! If it consistently requires restarting your server that sounds like a bug we should look at! If it was just a one-off restart, then it may have just been a glitch somewhere.

**Comment by efsandino** [comment]
@anurse Thanks... but this happened just one time ! Amazing... just restart and worked ! :)

**Comment by brunoalreis** [comment]
In my case, this happened to me because i updated the .net framework of the project and didn't installed it on production server. Hope it helps someone.

**Comment by IanMercer** [comment]
I have also seen this issue when two webapi projects were deployed to a single app service. In the `/LogFiles/eventlog.xml` file contains *The command line `dotnetfailed to start process with commandline 'dotnet .\<project1>.dll .\<project2>.dll' , ErrorCode = '0x8027025b', ...*

Maybe worth checking this after you've tried all the other reasons for Error 502.5.

**Comment by fagnercarvalho** [comment]
I'm getting this as an intermittent issue for almost one month right now and I don't know how to fix it. To reproduce this issue I'm killing the process where the app is running and then trying to access the site again. After doing this sometimes I will get this error and I don't know why.

**Comment by fagnercarvalho** [comment]
I believe I finally resolved my issue. I used [this ](https://github.com/aspnet/AspNetCore/issues/8122#issuecomment-469062247) as a reference to set the `ASPNETCORE_PORT` environment variable. I know this is not a good approach but at least this is working now. 

Here is my web.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore" />
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" arguments="%LAUNCHER_ARGS%">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_PORT" value="45200" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>
```

What seems to be happening in my case is that a lot of ports in the range 1025 - 48000 (the ports used by ANCM) are being used and the number of retries ANCM does is limited. I saw some discussions here in GitHub (can't find the issue) where it is being considered checking the port being trying to bind to it but until this happens I will keep these ports fixed.
