### ISSUE TITLE
Razor Components to Web API - DateTime is an hour behind

### ISSUE THREAD

**Issue by LaurenceFrost** [aspnet/AspNetCore#9155]
### Describe the bug
I am using .Net Core 3.0 Preview 3 and I am having an issue with the DateTime values. I have a solution split into 3 projects.

- Razor Components project
- Web API project
- Web shared project containing view models for the above projects to share

The issue is that if I post a view model containing a DateTime property from Razor Components, the view model arrives at the Web API endpoint just fine, **but the DateTime is exactly 1 hour behind the value posted from Razor Components.**

### To Reproduce
Steps to reproduce the behaviour:

**Set machine timezone to London UK.**

1. Create a Razor Components project using .Net Core Preview 3.
2. Create a class library containing a view model. The view model should contain a DateTime property.
3. Create a Web API project.
4. Reference the class library project from both the Web API project and the Razor Components project.
5. Get the Razor Components project to post the populated view model to a Web API end point.
6. The DateTime in the view model will be 1 hour behind the one posted from Razor Components when received by Web API.

### Expected behavior
I would expect that the DateTime value posted from the Razor Components project should be the same as what gets received by the Web API project.

### Observations
The Razor Components DateTimeKind seems to be set to "Local", whereas the Web API DateTimeKind seems to be set to UTC. So I think this is where the hour is being lost, due to local time in London currently being UTC + 1.

### Additional context
I have created a sample solution which exhibits the problem. You can see it by using the "Add Person" link, and setting a breakpoint in the Web API endpoint.
[BlazorDateIssue.zip](https://github.com/aspnet/AspNetCore/files/3051905/BlazorDateIssue.zip)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
