### ISSUE TITLE
[question] is it possible to render with SkiaSharp clientside via Brazor ?

### ISSUE THREAD

**Issue by YordanYanakiev** [aspnet/AspNetCore#9164]
I am just wondering if it is possible to render with SkiaSharp (or alike) client side via Brazor engine?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @YordanYanakiev.
This is not something we have plans for.

**Comment by SteveSandersonMS** [comment]
To clarify, this is something you can certainly do on your own, in the sense that you have access to JS interop and can therefore call any third-party API that you want.

We are just not planning any built-in features that are specific to SkiaSharp.

**Comment by YordanYanakiev** [comment]
Oww. Thank You for the clarification. For a second I was thinking that You are abandoning the client side of this project, which well.. would make the whole super-awesome project just meaningless.
Waiting impassionately for the client side implementation ! :)
