### ISSUE TITLE
Razor Components feature request: Microsoft.AspNetCore.Components.Forms.InputPassword

### ISSUE THREAD

**Issue by caleblloyd** [aspnet/AspNetCore#9179]
### Is your feature request related to a problem? Please describe.

I am trying to use `Microsoft.AspNetCore.Components.Forms.InputText` with `type="password"`.  As far as I can tell though there is no way to add `type="password"`

### Describe the solution you'd like
 
1. Allow specifying `type` in `Microsoft.AspNetCore.Components.Forms.InputText`

or

2. Add a  `Microsoft.AspNetCore.Components.Forms.InputPassword` class

### Describe alternatives you've considered

For now I plan to just extend `Microsoft.AspNetCore.Components.Forms.InputText` and add `type="password"`.  But this seems like something a lot of apps would need, so it'd be nice to put it in the standard library.

### Other info

Currently using .NET Core 3.0 Preview 3

**Comment by SteveSandersonMS** [comment]
We decided this is no longer required, since the splatting feature will allow developers to put `type="password"` on a regular `<InputText>`.

**Comment by RemiBou** [comment]
You can use this https://github.com/RemiBou/Toss.Blazor/blob/master/Toss.Client/Shared/Forms/MyInput.razor
