### ISSUE TITLE
When do we get IdentityServer4 working with Razor Components?

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#9182]
Hello Team;
When is Razor Component going to be integrated with IdentityServer4, that we can build our app with authenticating user via Razor Component page, where the server side gets token and we can then authorize different parts of our app?

**Comment by danroth27** [comment]
We plan to do work to enable authentication and authorization in 3.0.0-preview6. Currently the thinking is that the out of the box experience will be based on cookie authentication. Integration with IdentityServer4 should also be possible, but we don't currently plan to have an end-to-end template experience for this.
