### ISSUE TITLE
Duplicate AddRazorSupportForMvc in RCL templates

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9183]
The `AddRazorSupportForMvc` property appears twice in the RCL (non-Blazor) templates. One of these should be removed as part of #9126 in preview5. This issue tracks fixing the template in preview4

**Comment by pranavkm** [comment]
cc @danroth27

**Comment by Eilon** [comment]
Rejected for preview4; let's fix in preview5.
