### ISSUE TITLE
Verify SignalR scenarios with new C# 8 types/features

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#9184]
We need to make sure SignalR reacts appropriately to C# 8 types/features:

* New types (it's probably fine for these to be unsupported, we just need to know what happens):
  * [`Index`](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Index.cs)
  * [`Range`](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Range.cs)
* Nullable reference types - What happens in a SignalR app when you turn it on? How does it affect your models?

**Comment by rynowak** [comment]
> How does it affect your models?

It makes each one a compiler warning 😆

**Comment by anurse** [comment]
Yeah, already seen this with EF :(

**Comment by rynowak** [comment]
I'm planning on drafting a *"style guide"* the explains what the options are for MVC. I'd be share when I have something.

**Comment by rynowak** [comment]
https://github.com/aspnet/AspNetCore/issues/9194

**Comment by anurse** [comment]
I think we should do a quick investigation of what happens when you try to send an `Index` or a `Range` to the client, but otherwise the rest is up to the serializers to handle.

**Comment by anurse** [comment]
Currently https://github.com/dotnet/corefx/issues/37434 is blocking any further `Index`/`Range` testing.

**Comment by anurse** [comment]
`Index`/`Range` use private fields so aren't serializable

`IAsyncEnumerable` is how we support streaming, yaay!

Nullable has the same issues in SignalR as MVC Model Binding, EF models, etc. If you're using Json.NET you can use constructor binding:

```csharp
public class Customer
{
    public Customer(string firstName, string? middleName, string lastName)
	{
		FirstName = firstName ?? throw new ArgumentNullException(nameof(firstName));
		MiddleName = middleName;
		LastName = lastName ?? throw new ArgumentNullException(nameof(lastName));
	}

	public string FirstName { get; }
	public string? MiddleName { get; }
	public string LastName { get; }
}
```

If you're using `System.Text.Json` or otherwise want the traditional constructor-less POCO pattern of get/set properties, you'll need to do one of:

* Mark every property nullable
* Initialize every property
* Use the `default!` workaround and trust that SignalR will initialize the model (we don't support `[Required]` or other validation though so this is probably not a good idea)

```csharp
public class Customer
{
	public string FirstName { get; set; } = default!;
	public string? MiddleName { get; set; }
	public string LastName { get; set; } = default!;
}
```
