### ISSUE TITLE
Blazor component should start rendering only after OnInitAsync is completed

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/AspNetCore#9190]
### Describe the bug
Currently, when we override component's OnInitAsync, blazor will render components immediately after sync part of [OnInitAsync] completes, and then wait for its async part completion and rerender component. 
While the name [OnInitAsync] means that the component is still initializing and not ready, then it should also not be rendered.

### Expected behavior
Component should wait for [OnInitAsync] to complete and then start its first rendering. If we put async code in this lifecyle, it would means that component needs some more data to be ready.

**Comment by Andrzej-W** [comment]
I think it is not a bug. With this behaviour component have a chance to display some info to the user like "loading data". Component is automatically rerendered when OnInitAsync is finished.

**Comment by danroth27** [comment]
Like @Andrzej-W mentioned, this behavior is by design to allow rendering of content before the component has been initialized.

**Comment by ZvonimirMatic** [comment]
Was this changed? Currently when I'm running async function in OnInitAsync method the browser is just loading until the data is fetched.

**Comment by krystofzacek** [comment]
I second to that. Something got broken in Preview 7. If I go to Blazor @page using GET (not by click) then the following occurs:
- sync part of OnInitAsync gets executed
- rendering is called afterwards as expected but NO output is sent to browser, Browser is waiting for response.
- when the async part of OnInitAsync completes then rendering occurs again and only then the output is sent to browser.

This is apparently a bug which I have filed.

**Comment by danroth27** [comment]
> This is apparently a bug which I have filed.

@KrystofZacek What is the issue number for the issue you filed for this?

**Comment by KrystofZacek** [comment]
I guess it is 676312. It is still marked as new. 

https://developercommunity.visualstudio.com/content/problem/676312/blazor-oninitasync-method-not-rendering-asynchrono.html

**Comment by danroth27** [comment]
@KrystofZacek Thanks for reporting this issue!  Would you mind opening the same issue here in this GitHub repo? For Blazor framework related problems we track the issues here. You'll get a faster response that way.

**Comment by KrystofZacek** [comment]
No problem:
https://github.com/aspnet/AspNetCore/issues/12866
