### ISSUE TITLE
old version doesn't work after install new version of Dotnet Core

### ISSUE THREAD

**Issue by Penergy** [aspnet/AspNetCore#9192]
### Describe the bug
I've install the new version of .Net Core 2.2.202. But I have a project with .Net Core 2.0. 
![image](https://user-images.githubusercontent.com/4522788/55770934-ad54aa00-5ab8-11e9-87cf-d72e61c0a300.png)

When I trid to build in Visual Studio 2017, it showed the following message:
![image](https://user-images.githubusercontent.com/4522788/55770904-944bf900-5ab8-11e9-9607-1e62b88a77e7.png)

Since I couldn't build the project with current 2.2.202. I uninstalled the SDK 2.2.202. But It still didn't work.

So how can I revert to the old environment or I can exchange the .Net Core SDK in Visual Studio 2017?

**Comment by rynowak** [comment]
@kathleendollard

**Comment by KathleenDollard** [comment]
Visual Studio 2017 requires 2.1.5nn or 2.2.1nn. It will not run with 2.1.6nn or 2.2.2nn.

I know this is crazy confusing and we are working on a couple of possible solutions. 

I was also surprised that you don't have an AspNetCore for 2.0. But I'm not familiar with how AspNet was packaged in that time frame @rynowak 

@peterhuene

**Comment by Penergy** [comment]
@KathleenDollard Is it possible to config global.json in the project and Visual Studio can automatically detect the specific version from global.json?

**Comment by nguerrera** [comment]
@Penergy Can you share the full error messages from the output window. In particular, I'm interested to see if the error is coming from C:\Program Files\dotnet\... or from the fallback 1.1 SDK that VS 2017 unfortunately has.

Also, what do you get from `dotnet --info` if you run it from the same directory as your project in a VS 2017 developer command prompt. Check to make sure there isn't a global.json file that specifies a version that you do not have in that directory or above it.

**Comment by nguerrera** [comment]
Can you also share the full VS version from Help -> About Microsoft Visual Studio. This now looks to me like behavior of the resolver prior to 15.9 where it would abort if it resolved an SDK with too high minimum msbuild version instead of backing off to next highest. The abort then triggered a fallback to a global location with 1.1.

If you have VS 2017 lower than 15.9. can you upgrade to 15.9?

**Comment by nguerrera** [comment]
That would explain the behavior before you uninstalled 2.2, but not afterwards, did you experiement with global.json in between? The lack of 2.1.5nn also suggest to me that you have < 15.9.

Here's what I recommend:

1. Make sure there is no global.json file in your project file directory or higher
2. Run VS installer, get update to 15.9.Latest, make sure .NET Core workload is selected

**Comment by Penergy** [comment]
@nguerrera You are right. My VS 2017 version is < 15.9, actually 15.8.1. I will try it again.

The behavior in VS 15.8.1:
![image](https://user-images.githubusercontent.com/4522788/55924754-b753e580-5c3d-11e9-9b7f-6f120728fa74.png)
The output in VS 2017:
`
![image](https://user-images.githubusercontent.com/4522788/55924838-fbdf8100-5c3d-11e9-8563-4bad8cb41139.png)

`

**Comment by anurse** [comment]
@Penergy are you still seeing this issue? Do you have further questions on how to resolve this?

**Comment by anurse** [comment]
I'm going to close this just because it's a little stale now. Feel free to re-open it if you're still seeing this and can provide more information!
