### ISSUE TITLE
StopApplication shuts down host but not application

### ISSUE THREAD

**Issue by Hoffs** [aspnet/AspNetCore#9198]
### Describe the bug
When calling StopApplication() on IApplicationLifetime which is resolved from DI it only stops the host but application is kept alive and running.

### To Reproduce
Using ASP.NET Core Web API template call StopApplication() on resolved interface in either controller or hosted service.
Startup:
```csharp
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
```
Stopping, where `_serviceProvider` is `IServiceProvider` and `IApplicationLifetime` is `Microsoft.Extensions.Hosting` interface.
```csharp
var lifetime = _serviceProvider.GetService(typeof(IApplicationLifetime)) as IApplicationLifetime;
lifetime.StopApplication();
```

### Expected behavior
Entire application shuts down.

### Additional context
This is happening on dotnet 2.2 using WebHost to start the application.

**Comment by Tratcher** [comment]
Where did you call StopApplication from?

**Comment by Hoffs** [comment]
Called from inside HostedService that gets IApplicationLifetime injected on startup and also tried calling from inside a controller method with also injected IApplicationLifetime.

**Comment by Tratcher** [comment]
Can you upload a complete sample app?

**Comment by Hoffs** [comment]
Sorry for not responding sooner, but it was a programming error on our side. Some services that were being injected weren't disposed properly and kept the application from completely shutting down. Once we have implemented IDisposable's on them all issues went away and it works completely as expected.
