### ISSUE TITLE
SIGTERM graceful request shutdown?

### ISSUE THREAD

**Issue by schmitch** [aspnet/AspNetCore#9201]
Hello, currently I'm not sure but currently it looks like that dotnet core does correctly respond to SIGTERM, however requests are still getting killed.

Current behavior:
1. Request Started
2. SIGTERM
3. New Request Blocked
4. Request "Killed" (i.e. empty response)

Wished behavior:
1. Request Started
2. SIGTERM
3. New Request Blocked
4. Request Served Successfully if within a configurable timeout.

The good thing is that with `IApplicationLifetime` and `ApplicationStopping` somebody can actually handle that in a way that is good for K8s, i.e.:

```
bool IsStopping {get;set;}

        private void OnShutdown()
        {
            IsStopping = true;
            Console.WriteLine("Shutting Down");
            Thread.Sleep(500000); // suitable timeout
            Console.WriteLine("Stopped");
        }

        [AllowAnonymous]
        [HttpGet("healthz")]
        public async Task<IActionResult> Healthz()
        {
            Thread.Sleep(60000); // await Task.Delay(60000) does not change a thing

            return Ok();
        }
```

however that still means that somebody needs to implement that by himself. I think dotnet core should have a built-in way of doing that.

if there will be no built-in way I think at least the docs should be improved for things like k8s
or at least document the current sigterm behavior.

**Comment by halter73** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2#shutdown-timeout

**Comment by anurse** [comment]
We should do this already, our timeout is 5 seconds at the moment, so your sample code is blocking too long. @halter73 posted the configuration for this above. Does increasing this timeout solve your problem?

**Comment by schmitch** [comment]
oh ok, looks like with a higher timeout it is working, did not tought that the timeout of shutdown is so low.
Sorry for the inconvenience.

**Comment by anurse** [comment]
No problem! Glad to have answered your question :)
