### ISSUE TITLE
Reconsider AddAuthorizationPolicyEvaluator required for the authZ middleware

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9208]
Setting up the Auth middleware requires calling `services.AddAuthorizationPolicyEvaluator`. The name isn't particularly discoverable. We should instead see if we could repurpose `services.AddAuthorization`

**Comment by Eilon** [comment]
We should look at merging the AuthZ.Core and AuthZ.Policy into one assembly and have `.AddAuthorization()` do all the work.

**Comment by Eilon** [comment]
@JamesNK do you have cycles for this in preview5?

**Comment by JamesNK** [comment]
If my gRPC tasks go well, I think so.

Double checking we want this:
Core depends on logging and options. Policy depends on authentication, HTTP and routing.

Are we ok with authz assembly having hard dependencies on authentication, HTTP and routing?

**Comment by Eilon** [comment]
@rynowak / @davidfowl - any thoughts on the dependency changes?

**Comment by rynowak** [comment]
hmm. I thought I had commented on this. I don't think there's a reason not to do this - it's better for users. 

There's little meaning to our assembly factoring anymore as long as it doesn't make building the product insane.

**Comment by davidfowl** [comment]
> Are we ok with authz assembly having hard dependencies on authentication, HTTP and routing?

Yes this makes sense to me. I'm not aware of anyone that was trying to use auth outside of http scenarios.

> There's little meaning to our assembly factoring anymore as long as it doesn't make building the product insane.

Not true but I don't want to discuss that on github 😄. Remember there's still a thing called self contained applications. If no layers exist, trimming is *extremely* hard.
