### ISSUE TITLE
500 error when deployed to prod, solved adding .UseApplicationInsights() in program.cs

### ISSUE THREAD

**Issue by kkagill** [aspnet/AspNetCore#9215]
### Describe the bug

Basically, the web app worked in local IIS but once deployed to live via azure, I get 500 server error. So I 
attached debugger and debugged remotely. Here's what I found out:

1. once it hits the line in controller 
```var user = await _userManager.FindByEmailAsync(HttpContext.User.FindFirst(ClaimTypes.Name).Value);``` 
it throws with 500 error. 

2. once I added  `.UseApplicationInsights()` in `Program.cs`, error went away. 

    ```public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                .UseStartup<Startup>()
                .Build();```

I'm not sure why adding `.UseApplicationInsights()` would fix the problem. Is this related to the settings in Azure web instance?

.net core version is 2.0

**Comment by Eilon** [comment]
Indeed, these two things don't seem related...

When you get the HTTP 500 error, can you look in your logs to see what the stack trace was? Without that information it will be difficult to investigate further.

Also, .NET Core 2.0 is no longer supported. The newest released version is .NET Core 2.2, so it might be a good idea to update to that and see if this problem still happens.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
