### ISSUE TITLE
Invalid content root is set in integration tests if they are in a subfolder and use WebApplicationFactory with inherited Startup

### ISSUE THREAD

**Issue by satano** [aspnet/AspNetCore#9218]
### Describe the bug

I have found this during some investigation in #8428, so I use the same [demo repository](https://github.com/satano/WebApiIntegrationTests) as an example.

The tests in the projects are failing when:
  - Test project is located in some subfolder.
  - `WebApplicationFactory` and inherited `Startup` class is used.

The exception si:

> Message: System.ArgumentException : The content root '...\WebApiIntegrationTests\SubFolder_InheritedStartupTests_Workaround' does not exist.
Parameter name: contentRootPath

So it seems the framework set invalid content root path. The subfolder `tests` is missing in the middle. The correct path is: `...\WebApiIntegrationTests\tests\SubFolder_InheritedStartupTests_Workaround`

When `TestServer` is used, everything works as expected regardless the location of the test project.

### To Reproduce

1. Clone the [demo repository](https://github.com/aspnet/AspNetCore/issues/8428), build it and run all the tests.
2. Observe following:
    -  `SubFolder_InheritedStartupTests` and `SubFolder_InheritedWebApplicationFactoryTests` are failing. These test projects are in the `tests` subfolder.
    - `SubFolder_TestServerTests` are passing. These test projects are also in the `tests` subfolder.
    - `TestServerTests`, `InheritedStartupTests` and `InheritedWebApplicationFactoryTests` are all passing. These test projects are in the same folder as the SUT. The projects' location is the only difference here. _(Please look here on `_WithVersion` and `_Workaround` projects.The projects without suffix are also failing here, but this is problem filed in the issue #8428.)_

### Expected behavior

Correct content root should be set and the tests should work. In the demo repository, all the `SubFolder_` test projects should work.

**Comment by mkArtakMSFT** [comment]
@javiercn can you please look into this?
@satano this may be just a matter of overriding the content root for things which aren't in the expected location.

**Comment by mkArtakMSFT** [comment]
This thread will help: https://github.com/aspnet/AspNetCore/issues/9275

**Comment by satano** [comment]
@mkArtakMSFT I do not think, that this is the same thing. I do not have troubles finding config file. My test project fails while trying to build WebHost (`WebHostBuilder.Build()`).

I found out something more. The content root in those failing projects **is not working even if set explicitly**. When I [set content root](https://github.com/satano/IntegrationTestsContentRoot/blob/master/tests/SubFolder_InheritedStartupTests/Program.cs#L14) to some folder: `UseContentRoot(@"Q:\this\folder\does\not\exist")`, the tests still fail with the same message - the folder name in the message is `C:\projekty\satano\IntegrationTestsContentRoot\SubFolder_InheritedStartupTests`. The message is the same if I explicitly set correct folder as content root.

I created a new [demo project](github.com/satano/IntegrationTestsContentRoot) just for this issue and updated the issue's text with my new observations.

**Comment by javiercn** [comment]
You need to use a class from the app with WAF.

I changed your failing tests to use DemoAPI.Program and everything works as expected.

`public class TestsWebApplicationFactory : WebApplicationFactory<DemoApi.Program>`

**Comment by satano** [comment]
Oh. Now I understand. Thank you.

**Comment by erizzo** [comment]
What if the tests need to override some behavior of the Api bootstrap, like change services that are configured in the IServiceCollection, etc? I ran into this because I started extending the API's Startup class for my IntegrationTestsStartup; before I did that. How can the tests override API initialization behavior and still use WAF?

**Comment by javiercn** [comment]
Hi @erizzo. 
 
**It looks like you are posting on a closed issue!**

We're very likely to lose track of your bug/feedback/question unless you: 
1. Open a new issue 
2. Explain very clearly what you need help with 
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

**Comment by jukkahyv** [comment]
I found this via Google and had the same problem as @erizzo, so I'll post the solution here, which I found in [this blog](https://gunnarpeipman.com/aspnet-core-integration-test-startup/):

```csharp
public HomeControllerTests(MediaGalleryFactory<FakeStartup> factory)
    {
        _factory = factory.WithWebHostBuilder(builder =>
        {
            builder.UseSolutionRelativeContentRoot("MediaGallery");
 
            builder.ConfigureTestServices(services =>
            {
                services.AddMvc().AddApplicationPart(typeof(Startup).Assembly);
            });
                
        });
    }
```
