### ISSUE TITLE
Pipelines in ASP.NET Core 3.0

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#9223]
* Replace our default wrapping with the wrappers present in corefx
* Make the features read-only.

cc @davidfowl

**Comment by anurse** [comment]
@davidfowl to run the corefx stuff
@jkotalik to react in ASP.NET

**Comment by davidfowl** [comment]
I'm going to do this all in ASP.NET Core and nothing in corefx. Then we can react once we get the changes into corefx. That will allow us to make all of the changes to upstream components (just the form reader) and it'll let use flesh out the API.

**Comment by anurse** [comment]
Ok, updating description (above) to reflect recent discussion. Also moving to preview6 for remaining work.

**Comment by anurse** [comment]
We decided *not* to remove the BodyReader/BodyWriter properties...right?

**Comment by jkotalik** [comment]
Yeah... we still should try to start using the corefx adapters though.

**Comment by davidfowl** [comment]
Right. I’ll do the update to make the pipe properties readonly

**Comment by anurse** [comment]
I took a first look at this in #10154

**Comment by anurse** [comment]
This was done in preview6
