### ISSUE TITLE
Update SampleDataController in blazorhosted template to use standard ApiController conventions

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#9226]
The `SampleDataController` in the blazorhosted template doesn't follow our latest ApiController conventions.

Current code:

```csharp
    [Route("api/[controller]")]
    public class SampleDataController : Controller
    {
        private static string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        [HttpGet("[action]")]
        public IEnumerable<WeatherForecast> WeatherForecasts()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            });
        }
    }
```

Expected code:

```csharp
    [Route("api/SampleData/[controller]")]
    [ApiController]
    public class WeatherForecastsController : ControllerBase
    {
        private static string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        [HttpGet]
        public ActionResult<IEnumerable<WeatherForecast>> GetWeatherForecasts()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            }).ToList();
        }
    }
```

We should also update the routing setup in the Server project to call `MapControllers` instead of `MapDefaultControllerRoute` and call `AddControllers` instead of `AddMvc`.

**Comment by danroth27** [comment]
@glennc Does the suggested API code above look ok to you?

**Comment by isaac2004** [comment]
@danroth27 there was an earlier issue to modify the default controller to be WeatherController, and it is already [merged](https://github.com/isaac2004/AspNetCore/blob/14f590829cd1c0204a8945d546ddb4d5fc4d5d9c/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Controllers/WeatherController.cs). Should we have all the WeatherController templates be the same?

**Comment by danroth27** [comment]
@glennc Could you please take a look at the new [WeatherController](https://github.com/isaac2004/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Controllers/WeatherController.cs) and let us know if it's ready to take to our other templates?

**Comment by mkArtakMSFT** [comment]
Thanks @pranavkm !

**Comment by isaac2004** [comment]
@mkArtakMSFT did you close the wrong issue?

**Comment by mkArtakMSFT** [comment]
Not really, @isaac2004.
@pranavkm has already fixed this as part of https://github.com/aspnet/AspNetCore/pull/11351
