### ISSUE TITLE
Templates - default port of 50051 may fail with socket error if docker or hyper-v is installed

### ISSUE THREAD

**Issue by vincentparrett** [aspnet/AspNetCore#9233]
### Is your feature request related to a problem? Please describe.

The choice of 50051 as the default port may be problematic if Docker or Hyper-v is installed. This manifests as  

````an attempt was made to access a socket in a way forbidden by its access permissions````

Not sure yet if all templates use the same port, I was using the gRpc template. 

### Describe the solution you'd like
Either move the port outside if the range of ports reserved by docker and hyper-v or include a comment in the code to describe what may happen.

### Additional context

These reserved ports do not show up under netstat, so it took a while to figure out what was going on. 

FWIW, I did find a reference to this in the notes for [kb4074588](https://support.microsoft.com/en-us/help/4074588/windows-10-update-kb4074588)

````
C:\WINDOWS\system32>netsh interface ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
        80          80
      4800        4800
      5341        5341
      5357        5357
      8900        8900
      9996        9996
     35112       35112
     35118       35118
     49670       49769
     49870       49969
     49975       50074
     50415       50514
     50515       50614
     50615       50714

* - Administered port exclusions.
````

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vincentparrett.
We set the 50001 as the default port for GRPC  template only.
@shirhatti FYI

**Comment by shirhatti** [comment]
@JunTaoLuo FYI

**Comment by JamesNK** [comment]
@shirhatti

**Comment by JunTaoLuo** [comment]
@shirhatti

**Comment by shirhatti** [comment]
Unfortunately, there isn't a really good solution for this. You can reserve the port prior to installing Docker and then un-reserve the port

```sh
# Reserve the port
netsh int ipv4 add excludedportrange protocol=tcp startport=50051 numberofports=1

# Now install Docker

# Un-reserve the port
netsh int ipv4 delete excludedportrange protocol=tcp startport=50051 numberofports=1
```

It should become less of a concern since we're now changing the default port in the templates to 5001

**Comment by JamesNK** [comment]
The default port is now 5001. Thanks for bringing this to our attention.
