### ISSUE TITLE
URL Analytic problem  With  [Area]

### ISSUE THREAD

**Issue by ratku** [aspnet/AspNetCore#9235]
Action parameter  Analytic problem when the route is a [area] and the parameter  has the field name is area.

1. Using this version of ASP.NET Core '2.2'
2. when a controller under a area,the route like  test.com/abc/test/save,the "abc" is area name
3. if the [action]的parameter ,eg .   class  Address,contain a filed name Area  
4. then address.Area will be set to "abc",is a problem ,means i can't use name "Area" in any class filed define if the class  use to be a action parameter

**Comment by pranavkm** [comment]
> then address.Area will be set to "abc",is a problem ,means i can't use name "Area" in any class filed define if the class use to be a action parameter

See https://github.com/aspnet/Mvc/issues/7876 for some previous discussion on this. Certain keywords like `controller`, `action`, or `area` are considered reserved keywords in MVC. Renaming the parameter would be one option. Alternatively, you could specify a model binding attribute such as `[FromQuery]` or `[FromForm]` to prevent the property or parameter from being bound from route.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
