### ISSUE TITLE
Inject configuration into ASP Core correctly

### ISSUE THREAD

**Issue by AndersMalmgren** [aspnet/AspNetCore#9237]
We host a ASP Core web api inside a service fabric instance. I want to forward all configs to the Core app. I use this method

https://dzimchuk.net/configuring-asp-net-core-applications-in-service-fabric/

And then I invoke it using `ConfigureAppConfiguration`

```csharp
protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
{
    return new[]
    {
        new ServiceInstanceListener(serviceContext =>
            new KestrelCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
            {
                ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting Kestrel on {url}");

                return new WebHostBuilder()
                            .UseKestrel()
                            .ConfigureServices(
                                services => services.AddSingleton(serviceContext))
                            .ConfigureAppConfiguration(builder => builder.AddServiceFabricConfiguration(serviceContext))
                            .UseContentRoot(Directory.GetCurrentDirectory())
                            .UseStartup<Startup>()
                            .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.UseReverseProxyIntegration)
                            .UseUrls(url)
                            .Build();
            }))
    };
}
```

The inected configration in startup class do have the configs applied, like connection string and logging

![image](https://user-images.githubusercontent.com/817577/55858161-40e8b200-5b6f-11e9-8c9f-5a2e8362ef86.png)

But it seems its not fully jacked into the framework.

For example I need to explicit supply ApplicationInsights with the config `services.AddApplicationInsightsTelemetry(Configuration);` otherwise it does not pickup the instrument key. And the logging does not work (the log level is not applied).

**Update:**
I tried doing a custom config provider in a standard core project without service fabric and it works.
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration(builder => builder.AddServiceFabricConfiguration())
            .UseStartup<Startup>();
}

internal class ServiceFabricConfigurationProvider : ConfigurationProvider
{

    public override void Load()
    {
        Data["Logging:Debug:LogLevel:Default"] = "Information";
    }
}

internal class ServiceFabricConfigurationSource : IConfigurationSource
{


    public IConfigurationProvider Build(IConfigurationBuilder builder)
    {
        return new ServiceFabricConfigurationProvider();
    }
}

public static class ServiceFabricConfigurationExtensions
{
    public static IConfigurationBuilder AddServiceFabricConfiguration(this IConfigurationBuilder builder)
    {
        builder.Add(new ServiceFabricConfigurationSource());
        return builder;
    }
}
```

So it seems something i service fabric land is not working as it should.

**Comment by AndersMalmgren** [comment]
I also tried

```csharp
 return new WebHostBuilder()
   .UseConfiguration(new ConfigurationBuilder().AddServiceFabricConfiguration(serviceContext).Build())
   .UseKestrel()
```

And got a slightly different IConfiguration object. Though no difference, also notice that Warnign is enabled and info is not (this is default settings).

![image](https://user-images.githubusercontent.com/817577/55861658-1ac71000-5b77-11e9-960f-c03a8b45e256.png)

**Comment by davidfowl** [comment]
Is it just app insights that isn't working or something else?

**Comment by AndersMalmgren** [comment]
Hi @davidfowl The built in logging does not pickup my config so `_logger.IsEnabled(LogLevel.Information) `returns false even though I confirted it both for App insight logger and Debug logger

**Comment by AndersMalmgren** [comment]
This is with app insight enabled using `services.AddApplicationInsightsTelemetry(Configuration);`

Only one logger even though I have configured Debug logger too
![image](https://user-images.githubusercontent.com/817577/55867895-aba3e880-5b83-11e9-866f-74a317f3ca7a.png)

And as you can see MinLevel is at Warning but its confiugred for Information

Here with App insight off

![image](https://user-images.githubusercontent.com/817577/55868118-1fde8c00-5b84-11e9-921d-b0eae40b4f86.png)

No loggers found even though I have configured Debug logger

**Comment by AndersMalmgren** [comment]
@davidfowl Hi again, I created a repro project here

https://github.com/AndersMalmgren/ServiceFabricLoggingRepro

**Comment by AndersMalmgren** [comment]
I updated the repro with the offical service fabric asp core configuration package `Microsoft.ServiceFabric.AspNetCore.Configuration`. But no difference. Not so strange because all it does it spitting out a IConfiguration

**Comment by AndersMalmgren** [comment]
Please advice. We need to push this to our test environment soon

**Comment by AndersMalmgren** [comment]
fyi: I got logging to work changing from service fabric template that used 
```csharp
return new WebHostBuilder()
   .UseKestrel()
```
to use
```csharp
return WebHost.CreateDefaultBuilder()
   .UseKestrel()
```

But application insights still fail to pickup the config. I need to expliciit supply it with the Config which indicates something is still setup different from vanilla ASP Core

In vanilla Core this works `services.AddApplicationInsightsTelemetry()` but in service fabric i need to supply iy with the config for it to work `services.AddApplicationInsightsTelemetry(Configuration)`

**Comment by anurse** [comment]
Apologies for the delay, we're catching up a bit on some backlog.

Can you clarify a little what the expected behavior is and what you're actually seeing? When you use `new WebHostBuilder` instead of `WebHost.CreateDefaultBuilder` you do lose a lot of the [default configuration provided in that default builder](https://github.com/aspnet/AspNetCore/blob/f9ca0ffd7103380625ce473d0c599c57ca985e19/src/DefaultBuilder/src/WebHost.cs#L155).

If `WebHost.CreateDefaultBuilder` is working for you, I'd suggest you use it rather than trying to build the `WebHost` manually from scratch.

> In vanilla Core this works `services.AddApplicationInsightsTelemetry()` but in service fabric i need to supply iy with the config for it to work `services.AddApplicationInsightsTelemetry(Configuration)`

This is a perfect example of a default configuration that you lose when not using `CreateDefaultBuilder`. The automatic binding of config to application insights is provided by the ["Options" infrastructrure](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2) which has to be enabled using `services.AddOptions`. If you aren't using `CreateDefaultBuilder` and aren't registering Options yourself, you lose that magic.

**Comment by AndersMalmgren** [comment]
The problem is that the service fabric project template uses 'new WebHostBuilder' and it's very easy to miss this which we did. I suggest all templates should work the same and use 'CreateDefaultBuilder'.

The second problem is that app insight do not use DI to receive the 'IConfiguration' they instead try to resolve the .JSON config file. I suggest you unify behaviour across all Core frameworks and use DI to fetch the config.

**Comment by anurse** [comment]
> I suggest all templates should work the same and use 'CreateDefaultBuilder'.

That may be the case. The service fabric template is, I believe, owned by the service fabric team (cc @glennc). I'd suggest filing a VS Feedback issue (through the feedback icon in the top right of Visual Studio).


> The second problem is that app insight do not use DI to receive the 'IConfiguration' they instead try to resolve the .JSON config file.

Similarly, App Insights owns that experience. I suggest reaching out to them at https://github.com/microsoft/applicationinsights-aspnetcore .

Closing as there's no action for ASP.NET Core here.
