### ISSUE TITLE
how can I use iis and kestrel same time?

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/AspNetCore#9238]
My website delpoy in iis 7.5,,but I need to use WebSocket,so I want to use IIS and kestrel same time,,,normal http request use IIS 80 port,,and WebSocket use kestrel......so,,I want to get kestrel runtime port from iis, it like , when my websocket client application start, send a http request to iis website to get the kestrel port,and use WebSocket Client to connect kestrel to use WebSocket

**Comment by kugarliyifan** [comment]
so....how the IIS know the kestrel server runtme port?

**Comment by anurse** [comment]
> My website delpoy in iis 7.5,,but I need to use WebSocket,so I want to use IIS and kestrel same time

You want browser clients to be able to connect through IIS **and directly to Kestrel**? This isn't possible since only one of them can use port `80`. If you want to use WebSockets when running with IIS, the only supported scenario is to use IIS 8.0 or higher.

**Comment by Tratcher** [comment]
When running in the reverse proxy configuration we actively block requests to Kestrel that did not come from IIS.

**Comment by kugarliyifan** [comment]
I saw the Kestrel's log,,,In IIS mode ,Kestrel  only bind 127.0.0.1........so...it can't work...so.....I use SignalR instead it,,,,,,thanks every one

> When running in the reverse proxy configuration we actively block requests to Kestrel that did not come from IIS.

**Comment by ErcinDedeoglu** [comment]
https://docs.microsoft.com/tr-tr/dotnet/api/microsoft.aspnetcore.hosting.webhostbuilderiisextensions.useiisintegration?view=aspnetcore-2.2
