### ISSUE TITLE
NullReferenceException from DefaultHttpContext.Abort()

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#9239]
gRPC for ASP.NET Core has an interop test fail: https://github.com/grpc/grpc-dotnet/issues/206

This part of the logs stands out:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature,TState](TFeature& cached, TState state, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpContext.Abort()
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.DeadlineExceeded(Object state) in /var/local/git/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs:line 267
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

A gRPC request can have a timeout. When a timeout is specified we start a System.Threading.Timer, and call HttpContext.Abort() when it is triggered. If the request app logic completes before then the timer triggers then the timer is disposed.

This is DefaultHttpContext.Abort():

https://github.com/aspnet/AspNetCore/blob/3b32f43453eba8edf03bebb9d893af59ada0e431/src/Http/Http/src/DefaultHttpContext.cs#L161-L164

What could cause the feature to be null?

**Comment by davidfowl** [comment]
@JamesNK this is running during the request right?

**Comment by JamesNK** [comment]
Yes. The timer is wrapped in a try/finally to dispose it before the request finishes.

**Comment by JamesNK** [comment]
Logic looks like this:
1. gRPC endpoint is executed
2. Request has a grpc-timeout header so a timer is started inside try/finally
3. User code is called
4. Timer is disposed in finally block
5. Done

Could a `System.Threading.Timer` execute after it is disposed? Is there a race condition?

**Comment by anurse** [comment]
@JamesNK can you fill me in on the work here? Timers can definitely be running after they `Dispose` (if they were `Dispose`d right after the timer callback is fired). HttpContext isn't intended to be thread-safe, though it isn't great if `Abort` can't be called from a timer like this since it's a common cancellation scenario.

Thoughts @davidfowl ?

**Comment by davidfowl** [comment]
It's a bug in the gRPC logic (looking at the log below) though from the code it looks as though everything is written fine. Seems like something needs to guard against calling abort after the request is done.

Log:

```
fail: Grpc.Testing.TestServiceImpl[3]
      Error when executing service method 'FullDuplexCall'.
System.IO.IOException: The client reset the request stream.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync(PipeReader input, HttpContextServerCallContext context, CancellationToken cancellationToken) in /var/local/git/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/PipeExtensions.cs:line 271
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Grpc.AspNetCore.Server.Internal.HttpContextStreamReader`1.<MoveNext>g__MoveNextAsync|10_0(ValueTask`1 readStreamTask) in /var/local/git/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/HttpContextStreamReader.cs:line 48
   at InteropTestsWebsite.AsyncStreamExtensions.ForEachAsync[T](IAsyncStreamReader`1 streamReader, Func`2 asyncAction) in /var/local/git/grpc-dotnet/testassets/InteropTestsWebsite/AsyncStreamExtensions.cs:line 35
   at Grpc.Testing.TestServiceImpl.FullDuplexCall(IAsyncStreamReader`1 requestStream, IServerStreamWriter`1 responseStream, ServerCallContext context) in /var/local/git/grpc-dotnet/testassets/InteropTestsWebsite/TestServiceImpl.cs:line 76
   at Grpc.AspNetCore.Server.Internal.CallHandlers.DuplexStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext) in /var/local/git/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/CallHandlers/DuplexStreamingServerCallHandler.cs:line 55
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /grpc.testing.TestService/FullDuplexCall'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.1099ms 200 application/grpc
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature,TState](TFeature& cached, TState state, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpContext.Abort()
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.DeadlineExceeded(Object state) in /var/local/git/grpc-dotnet/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs:line 267
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

Notice the `Request finished in 2.1099ms 200 application/grpc` before the null ref. That means the request was disposed. 

I'm not sure yet if this warrants building a first class API as yet, if we do though, it would be something like Abort(TimeSpan) that would guard against this.

**Comment by JamesNK** [comment]
Inside the request handler the simplified logic looks like this:

```cs
public Task DoRequest(HttpContext httpContext)
{
  var serverCallContext = new HttpClientServerCallContext(httContext);
  try
  {
    serverCallContext.Initialize(); // Starts timer
    // DO STUFF (streaming, user logic, etc)
  }
  finally
  {
    serverCallContext.Dispose(); // Stops timer
  }
}
```

From the log it appears the client is killing the connection, and the server is disposing of HttpContext before the request delegate exits. Now if the deadline timer executes before it is disposed then it will call HttpContext.Abort() and get an NRE because the lifetime feature has been cleared. Is that correct description of events?

**Comment by JamesNK** [comment]
A couple of ideas:
* gRPC could test whether the cancellation token has been triggered before calling `Abort()`
* gRPC could be to get the lifetime feature from the HttpContext and check if it is null or not before calling

Alternatively ASP.NET Core could make calling Abort() safer:
* Make `Abort()` noop after the context has been reset
* Not reset the context until the request delegate has exited

**Comment by davidfowl** [comment]
> From the log it appears the client is killing the connection, and the server is disposing of HttpContext before the request delegate exits. 

That should never happen. That would be a bug in the HTTP/2 logic that we have. @halter73  @Tratcher can you take a look at that. 

> Alternatively ASP.NET Core could make calling DefaultHttpContext.Abort() safer:

No, we shouldn't do this. It's not even Kestrel throwing, it's a null ref coming from somewhere in HttpAbstractions. This should throw an object disposed exception or something else.


> Not reset the context until the request delegate has exited

It shouldn't, if anything, that's the bug here.

**Comment by JamesNK** [comment]
An alternative explanation could be gRPC's timer still triggering after `Timer.Dispose()` has run. https://docs.microsoft.com/en-us/dotnet/api/system.threading.timer.dispose?view=netframework-4.8#System_Threading_Timer_Dispose

```cs
Callbacks can occur after the Dispose() method overload has been called, because the timer queues callbacks for execution by thread pool threads. You can use the Dispose(WaitHandle) method overload to wait until all callbacks have completed.
```

Checking a flag inside the timer's callback could improve this. It wouldn't be perfectly threadsafe without some additional locking.

**Comment by davidfowl** [comment]
My guess is that it's a callback firing after dispose rather than an issue in Kestrel but we should verify.

> Checking a flag inside the timer's callback could improve this. It wouldn't be perfectly threadsafe without some additional locking.

This is where the TimerAwaitable is superior in it's consumption model. You kick off the timer awaitable, then get a task back, then when you're about to exit the request delegate, you stop the timer, and wait for the task to end. That will ensure that any pending callbacks have already fired and that the consuming code is no longer running before you exit the callback.

**Comment by JamesNK** [comment]
That would be cleaner. However waiting for the task to complete would add some overhead to each gRPC call. This is a hot path. Here we don't care about the very rare case of the Timer callback executing afterwards, so long as it doesn't do anything.

Do you know if TimerAwaitable + stopping the timer + awaiting it has much perf impact?

**Comment by davidfowl** [comment]
Why not use a Task.Delay then, this is a one shot timer right? You just need a task returning method that you can wait on if it's not already completed. You can avoid the cost if you just skip the await in the common case (like we do other things).

**Comment by JamesNK** [comment]
Hmm, I don't follow. The timer should abort the request while it is in progress. How would Task.Delay be used to do that?

For example, if there is a 5 second deadline. A SQL query goes out of control for 30 seconds, and 5 seconds into the query the deadline triggers, aborting the request and triggering the cancellation token.

**Comment by Tratcher** [comment]
Are you actually trying to kill the connection (e.g. prevent any response) or just trigger the cancellation token? Abort is the rudest way to end a request. Giving some kind of HTTP error status code response is usually preferred.

If you only want to trigger the cancellation token after a given timer then how about just chaining/replacing it?

**Comment by JamesNK** [comment]
> Abort is the rudest way to end a request. Giving some kind of HTTP error status code response is usually preferred.

This is gRPC. Clients handle RST_STREAM and give the user a nice, known error status code.

However, I'll double check what other gRPC implementations do with the connection when they hit a deadline.

**Comment by JamesNK** [comment]
@Tratcher Issue about gRPC and abort https://github.com/aspnet/AspNetCore/issues/10886

**Comment by Tratcher** [comment]
Hmm, we might have to come up with a way to special case Abort as thread safe. Pre-resolve the feature?

**Comment by anurse** [comment]
Special-casing `Abort` as thread-safe does seem OK to me. My understanding here is that the likely culprit for the null-ref is here: https://github.com/aspnet/AspNetCore/blob/214ca07b6c1efd48abd07ec10c50db9a6a4b830d/src/Http/Http.Features/src/FeatureReferences.cs#L68

Unless `FeatureReferences.UpdateCached` is getting inlined (I presume this stack is from a Debug build @JamesNK ?), that's the main way this could happen. It could become null in `DefaultHttpContext.Uninitialize`: https://github.com/aspnet/AspNetCore/blob/214ca07b6c1efd48abd07ec10c50db9a6a4b830d/src/Http/Http/src/DefaultHttpContext.cs#L60

So my hunch is that `Abort` is being called after the request has already ended. Pre-resolving the feature, while probably necessary for thread-safety, wouldn't resolve this issue. We probably also need to "no-op" `Abort` if the feature collection has been uninitialized.

**Comment by halter73** [comment]
> Special-casing Abort as thread-safe does seem OK to me.

As you mention, one problem is that the whole feature collection is not thread-safe.

That being said, in Kestrel, IHttpRequestLifetimeFeature.Abort() *is* thread-safe, and accessing IHttpRequestLifetimeFeature specifically is also thread-safe since Kestrel stores the IHttpRequestLifetimeFeature object (which is the HttpProtocol instance unless it's been set to something else) in a dedicated object field.

Furthermore, Kestrel never sets the IHttpRequestLifetimeFeature object field to null. When HttpProtocol resets the field between requests, it gets reset to [this](https://github.com/aspnet/AspNetCore/blob/177ad2b96678a86854a2833314552718588942de/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.Generated.cs#L86).

Frankly, with as much code that tries to abort request from an unobserved thread, if Kestrel did set the IHttpRequestLifetimeFeature to null between requests, I suspect we would have found out about it before now.

As for the NullReferenceException, DefaultHttpContext.Uninitialize could definitely be the culprit.

**Comment by JamesNK** [comment]
Instead of making DefaultHttpContext.Abort safe, an alternative is to move its logic into gRPC.

Current:

```cs
try
{
    HttpContext.Abort();
}
catch (Exception ex)
{
    Log.DeadlineCancellationError(_logger, ex);
}
```

New:

```cs
try
{
    HttpContext.Features?.Get<IHttpRequestLifetimeFeature>()?.Abort();
}
catch (Exception ex)
{
    Log.DeadlineCancellationError(_logger, ex);
}
```

But would that move the problem somewhere else, i.e `IHttpRequestLifetimeFeature.Abort` now throws because the request had just ended

**Comment by halter73** [comment]
> But would that move the problem somewhere else, i.e IHttpRequestLifetimeFeature.Abort now throws because the request had just ended.

While I think it's good code hygiene to wait for any potential/scheduled calls to HttpContext.Abort() to complete before completing the middleware. However, at least in Kestrel, calling IHttpRequestLifetimeFeature.Abort after a request ends should not cause a problem other than potentially aborting a future request in HTTP/1.

In HTTP/2 we don't pool streams (which are represented the HttpProtocol objects I referenced in my last comment), so there isn't yet the potential of aborting future requests in HTTP/2. Given the code like that above that calls HttpContext.Abort() from unobserved background threads, we might never want to pool HTTP/2 streams.

**Comment by JamesNK** [comment]
To be clear, I don't like the idea of HttpContext.Abort being called after the request has finished. I want to add state to gRPC to test and prevent abort being called.

**Comment by JamesNK** [comment]
FYI @davidfowl 

Timer:
```
                  Method |     Mean |     Error |    StdDev |      Op/s | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
------------------------ |---------:|----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
 DeadlineHandleCallAsync | 2.811 us | 0.0114 us | 0.0089 us | 355,729.0 |      0.1221 |           - |           - |               520 B |
```

CancellationTokenSource + CancelAfter(TimeSpan):
```
                   Method |     Mean |     Error |    StdDev |      Op/s | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
------------------------ |---------:|----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
 DeadlineHandleCallAsync | 2.907 us | 0.0425 us | 0.0398 us | 344,022.6 |      0.1984 |           - |           - |               840 B |
```

**Comment by halter73** [comment]
> I'm guessing he meant Dispose will prevent the token being raised immediately

If only that were enough. It also blocks until any currently-executing registrations complete.

Make sure you don't acquire any locks while disposing CTS that one of your registrations may need. Otherwise you could end up with a deadlock where the disposing thread both waits on and prevents the cancellation from completing on another thread.

**Comment by anurse** [comment]
@JamesNK do we still need something here given your changes?

**Comment by JamesNK** [comment]
I think the bug was in gRPC - calling abort after the request delegate has finished - and it has been fixed in gRPC. Closing.

**Comment by anurse** [comment]
![A man in a car waves two thumbs up](https://media.giphy.com/media/xHMIDAy1qkzNS/200.gif)
