### ISSUE TITLE
Asp.Net Core Bug

### ISSUE THREAD

**Issue by bidianqing** [aspnet/AspNetCore#9241]
Hi, Asp.Net Core Team, I am currently using Hangfire framework in Asp.Net Core Application. I encountered a problem，https://github.com/HangfireIO/Hangfire/issues/1394#issuecomment-481644190

**Comment by jkotalik** [comment]
This was already fixed by https://github.com/aspnet/AspNetCore/commit/010139ac8a3ad9f4cebdf7013baba2c844f155f1. If you'd like the fix now, please download our nightlys here: https://github.com/dotnet/core-sdk
