### ISSUE TITLE
ASP.NET (security) patches while running on .NET Framework

### ISSUE THREAD

**Issue by SjoerdWesterhof** [aspnet/AspNetCore#9246]
I would like to verify the following:

If i run an ASP.NET 2.1 Core web application on .NET Framework and a patch comes out (10 came out last year i think) in ASP.NET Core, i would like to install these to maintain support and stay as secure as possible*.
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

It seems to me if have no other option then:
A: Subscribe to AspNET announcements to see if there is a patch that is essential to install
B: Update to the patched ASP.NET assemblies from my application
C: publish the application
D: Deploy the application

This is necessary since i can't use the Shared Framework or something similar.
Am i correct in drawing this conclusion?

Thanks in advance, 
Kind regards,
Sjoerd

**Comment by blowdart** [comment]
You are yes. Those are your steps I'm afraid.

**Comment by SjoerdWesterhof** [comment]
Thank you for taking the time to answer my question.
