### ISSUE TITLE
Templates VS 2019 (16.0.0 or above) 

### ISSUE THREAD

**Issue by WILLEM-LENS** [aspnet/AspNetCore#9247]
### Describe the bug
Template VS2019 (version 16.0.0 and 16.0.1) with integration of AAD routing does not work. Menu-item "SignIn" points to homepage. 

### To Reproduce
Using this version of ASP.NET Core '3.0.0-preview3-19153-02.' Use standard temple: Razor application (not component) with AD integration (1 tenant or multitenant).

### Expected behavior
Sign-in screen for AAD should appear. 
Link should show: https://localhost:xxxx/AzureAD/Account/SignIn

### Additional context
The following code does work (comment out UseRouting and add UseMVC() as below:

            //app.UseRouting(routes =>
            //{
            //    routes.MapRazorPages();
            //});

            app.UseCookiePolicy();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseMvc();`

**Comment by blowdart** [comment]
@javiercn I though we had tweaked this in other places?

**Comment by javiercn** [comment]
I believe this was fixed in preview4. @ryanbrandenburg can confirm. 

Calling routes.MapControllers() will also work. No need for app.UseMvc()

**Comment by ryanbrandenburg** [comment]
Yeah I believe this should be solved and regardless the code in Startup.cs has changed, so presentation and solution will be different and warrant a new issue.
