### ISSUE TITLE
Model binding 

### ISSUE THREAD

**Issue by adriaanmyob** [aspnet/AspNetCore#9261]
### Describe the bug
In Web API we could use a query string like `filter[firstname]` and it would bind to our complex type `FilterOptions.FirstName`. This does not seem to work for ASP.NET Core. Is there another approach to make this work or would this end up with a custom model binder?

### To Reproduce
1. Using 2.2 of ASP.NET Core

**Comment by pranavkm** [comment]
@adriaanmyob could you share some steps to reproduce the error? It's not entirely clear what you're attempting to do, what the inputs are, and what the expectations are.

**Comment by adriaanmyob** [comment]
We fixed it with adding the following ValueProvider 
```
options.ValueProviderFactories.Add(new JQueryQueryStringValueProviderFactory());
```
