### ISSUE TITLE
Proposal: Add ZML Views and ZML Pages

### ISSUE THREAD

**Issue by VBAndCs** [aspnet/AspNetCore#9270]
# Proposal:
I suggest to support a new ZML views / pages with the file extension .zml. `ZML` stands for `raZor XML`, where I represented language statements as XML tags.

# Benefits:
This can achieve the following:
1. Using a more homogeneous code, which is just an XML code!
2. Using less `{ } ; @` symbols, so, the code will be more compact and more friendly.
3. Using one generalized view syntax makes it valid for use for all programming languages.
4. This will eliminate the need to create vbxml and fshtml  razor views!
5. All Razor rules still applies, so the learning curve is low.
6. Building ZML views on the top of Razor engine means it will benefit from any future new features added to the Razor engine, which uses C# as the internal language. 
7. Pages designed in apps written by any language, can be reused in other languages as they are!

The cost to implement ZML in .NET is the cost of witting an easy ZML tags to C# translator and add VS.NET editor support for ZML files.

#Implementation: 
I add a ZML support in [Vazor](https://github.com/VBAndCs/Vazor-DotNetCore2). I translate ZML tags to C# code to get a C# Razor, then send it to Razor engine to carry the work!
This [ZML Module](https://github.com/VBAndCs/Vazor-DotNetCore2/blob/master/Vazor/ZML.vb) contains a simple implementation of ZML using XML literals in VB.NET. It doesn't do any syntax check, assuming the ZML format is reviewed by the editor. 
Currently, it supports:
* `<page/>` for `@page`

* `<model type="mtype" />` for `@model mtype`
   Note: if the type is generic, use VB syntax `<model type="List(Of mtype)" />`, because XML literals considers `List<mtype>` as an opining tag without the closing one! 

* `<set object="obj" value="val"/>` for C# Razor:
```c#
@{
    obj = val;
}
```

* ZML tag:
```xml
<if  condition="cond">
    block of zml code
</if>
```

for C# Razor:
```xml
@if  (cond)
{
    block of zml code
}
```

* ZML tag:
```xml
<if  condition="cond1">
  <then>
    block of zml code
  </then>
  <elseif condition="cond2">
    block of zml code
  </elseif>
  <!--repeate elseif tags as you need -->
  <else>
    block of zml code
  </else>
</if>
```

for C# Razor:
```xml
@if  (cond1)
{
    block of zml code
 }
 elseif (cond2)
{
    block of zml code
}
else
{
    block of zml code
}
```

Note: you can nest if tags as you need.

* ZML tag:
```xml
<foreach var="m" in="Model">
    block of zml code
</foreach>
```

for C# Razor:
```xml
@foreach (var m in Model)
{
    block of zml code
}

```

These are the supported ZML tags until now (which are the most used), but every language structure can be represented in the same way.

# Example:
ZML code:
```cshtml
<page />
<model type="CatalogModel"/>
 
<set object="ViewData["Title"]" value="zml sample" />
<set object="ViewData("Message")" value="another syntax" />

<div class="container">
       <if  condition="CatalogModel.CatalogItems.Any()">
          <then>
             <partial name="_pagination" for="CatalogModel.PaginationInfo"/>
                   <div class="esh-catalog-items row">
                       <foreach   var="catalog" in="CatalogItems">
                            <div class="esh-catalog-item col-md-4">
                                <partial name="_product" for="@catalog" />
                            </div>
                       </foreach>
                 </div>
              <partial name="_pagination" for="CatalogModel.PaginationInfo"/>
          </then>
          <elseif condition="X>3">
                <!--we can have elseif too-->
          </elseif>
          <else>
              <div class="esh-catalog-items row">
                     THERE ARE NO RESULTS THAT MATCH YOUR SEARCH
              </div>
         </else>
     </if>
</div>
```

Which can is translated to this C# Razor:
```cshtml
@page 
@model CatalogModel

@{
     ViewData["Title"] = "zml sample";
     ViewData["Message"] = "another syntax";
}

<div class="container">
       @if  (@Model.CatalogModel.CatalogItems.Any())
          {
             <partial name="_pagination" for="CatalogModel.PaginationInfo"/>
                   <div class="esh-catalog-items row">
                       @foreach (var catalog in @Model.CatalogItems)
                        {
                            <div class="esh-catalog-item col-md-4">
                                <partial name="_product" for="@catalog" />
                            </div>
                        }
                 </div>
              <partial name="_pagination" for="@Model.CatalogModel.PaginationInfo"/>
          }
          elseif (X>3)
          {
                <!--we can have elseif too-->
          }
          else
          {
              <div class="esh-catalog-items row">
                     THERE ARE NO RESULTS THAT MATCH YOUR SEARCH
              </div>
         }
</div>
```

Vazor contains a working simple sample, the [index.vbxml.vb](https://github.com/VBAndCs/Vazor-DotNetCore2/blob/master/WebApp1/Views/Home/Index.vbxml.vb) file contains this ZML block
```xml
  <ul>
      <foreach var="m" in="Model">
           <li>
                Id: @m.Id<br/>
                Name: @m.Name<br/>
                <p>Grade: @m.Grade</p>
           </li>
      </foreach>
  </ul>
```

Which generates this C# Razor:
```xml
<ul>
   @foreach (var m in Model)
   {
     <li>
        Id :  @m.Id<br />
        Name: @m.Name<br />
        <p>Grade: @m.Grade</p>
    </li>
   }
</ul>
```

# Note:
I can't create ZML editor myself. It is easier for you to modify the Razor editor to deal with ZML tags. If this to happen, I expect there will be no need to use the @ inside the ZML attributes, nor the Model keyword in most cases. The editor can also allow the use of `<T>` for generics. I advise to allow using (Of T) or <T>, and (`(i)` or `[i]` notations, to let VB and C# developers write the syntax they are familiar with. 

# Conclusion:
ZML is an easy to write, read and learn code, because  it is an XML code but very close to C# and VB.NET code. It can add a great value to VS.NET with low cost, and will give VB.NET and F# developers the ability to design web pages with homogeneous XML code. C# programmers also can find this ZML views attractive.

**Comment by hishamco** [comment]
Have a look to [Fluid](https://github.com/sebastienros/fluid)

**Comment by VBAndCs** [comment]
@hishamco  
Nice, but away from ZML. The idea here is to use the existing to0ls (i.e low coast and less effort) to generate something that can be used by all languages. ZML is just new XML tags that can coverted in a small xsd schema. I can write it tody in cshtml file, or I can put it in XML file and use an xsd to force the editor to check its syntax (and it is supposed to offer intellisense but this feature is broken for some reason!). Modifying current Razor editor to support a few new xml tags should be easy for the team.
Besides, ZML can be easily extended as needed. I am abiyt to define a `<ViewData Title="test" Message="OK" ....>` tag to ease dealing with the ViewData. You can add as menay attr as you want and I will add them as keys in the ViewData:
```xml
@{
   ViewData["Title"] = "test";
   ViewData["Message"] = "OK";
}
```

Too easy implementaion and usage!

**Comment by hishamco** [comment]
Perhaps this is good as community project

**Comment by VBAndCs** [comment]
I am working on it. But I am out of the VS.NET plug-iins zone, so I can't create an ZML editor.
Besides, I think this is the ultimatum abstraction of view design for the benefit for all .net languages. In this layer, you can define as many tags as you need to simplify creating the page.I hope the team considers this. This will not eliminate C# razor, but will add a really nice choice for those who don't like C# syntax. We can even allow user defined tags using some sort of xsd schema or whatever. Sky is the limit here.
By the way, I implemented the ViewData tag in between the two replies :)

**Comment by Eilon** [comment]
Hi, we are closing this issue because there are no plans to add additional view engines to ASP.NET Core at this time.

We encourage you to work on this as a community project.

**Comment by VBAndCs** [comment]
Ok.
But for the record, this is not a viewi engine. It is just a thin layer on top of your existing Razor view engine.

**Comment by Eilon** [comment]
@VBAndCs understood, but we have no plans to add this support.

**Comment by VBAndCs** [comment]
Ok.
To any one who is interested in this idea:
I added a working example of zml pages to my repo, so please, lets take the discussion to this topic: VBAndCs/Vazor-DotNetCore2#1
Thanks.

**Comment by VBAndCs** [comment]
ZML 1.0 now has its own [repo](https://github.com/VBAndCs/ZML) and [NuGet](https://www.nuget.org/packages?q=zml).
