### ISSUE TITLE
Model not accepted by view (ViewDataDictionary) and/or view expecting different model than it supposed to

### ISSUE THREAD

**Issue by jakubsvobodacz** [aspnet/AspNetCore#9271]
### Describe the bug
I have .net core web app based on razor pages. I use a _Layout structure with some partials and pages that need to be rendered in @renderbody(). I have a _Sidebar partial with links that should link to the pages that should load in the @renderbody() section. I add the link using the asp-page directive and I scaffold a razor page item (view + pagemodel) in the Pages folder. I do not make any changes to the scaffolded code in the files. I only add the name of the files to the asp-page directive in the sidebar link. I run the web app and click the link and I get the following error:
```
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'NetworkManagementPortal.Pages.WhitelistingModel', but this ViewDataDictionary instance requires a model item of type 'NetworkManagementPortal.Pages.IndexModel'. 
```

The Index page is the only one working fine.

Could it be some issue with the razor itself? I do not think I have much influence on this considering very basic code + scaffolded razor page. I was unsure whether this problem belongs here but I cannot seem to understand the problem being in the code but rather something in the background within razor, so that is why I post it here.

### Code Used for Links (_Sidebar partial)
```
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-page="Index">
                        <i class="ni ni-settings text-blue"></i> CIL
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-page="Whitelisting">
                        <i class="ni ni-pin-3 text-orange"></i> White-list IP
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-page="About">
                        <i class="ni ni-single-02 text-yellow"></i> Find Devices
                    </a>
                </li>
                <li class="nav-item">
                    <partial name="_LoginPartial">
                </li>
            </ul>
```

### Scaffolded Code by VS 2017 (Razor pages to appear in renderbody())
```
@page
@model NN.NetworkManagementPortal.Pages.WhitelistingModel
@{
    ViewData["Title"] = "Whitelisting";
}

<h2>Whitelisting</h2>
```
### Expected behavior
The associated model is passed and expected and the page loads within renderbody().

### Additional context
.NET Core 2.1
I noticed that there is some item in the solution explorer that got generated for the whitelisting razor page and not for the other pages: ```_Pages_Whitelisting```

![screenshot](https://user-images.githubusercontent.com/21977019/55933262-047b8b80-5c2d-11e9-92ff-78606756a5f3.PNG)

**Comment by wangkanai** [comment]
Has this been resolve? Because i have the same problem.
