### ISSUE TITLE
Change 502 Bad Gateway to 504 Gateway Timeout

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/AspNetCore#9287]
### Is your feature request related to a problem? Please describe.
I'm am trying to understand why I'm getting 502.3 Bad Gateway responses when the real issue is a timeout.

Reference: [HTTP Error 502.3 - Bad Gateway when timeout](https://github.com/aspnet/AspNetCoreModule/issues/48#issuecomment-367070499)

### Describe the solution you'd like
Change the response from 502 to 504.

### Describe alternatives you've considered
None

### Additional context
A few comments from the reference issue:

>Looks like we should be returning a 504 instead of a 502

>504 makes much more sense, since I just spent hours troubleshooting middleware and routing due to misleading Bad Gateway (it implies something's wrong with infrastructure or configuration instead of timeout error).

**Comment by anurse** [comment]
This is a pretty severe breaking change and we don't think the benefit is worth it. We don't have any plans to change this behavior at this point.
