### ISSUE TITLE
WS Fed configuration for IIS Asp.Net Core app

### ISSUE THREAD

**Issue by tomagnew** [aspnet/AspNetCore#9290]
I work for a large enterprise which has an existing legacy Asp.Net Web Forms app using .Net 4.71 which utilizes WS Fed authentication via the WSFederationAuthentication module configured in the web.config at the root of the application. 
We are trying to port the application forward to Asp.Net Core 2.2. We followed the instructions given for the WS Fed module listed [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.2) When we deploy the app to our IIS server, the app successfully authenticates against our WS Fed configured Identity server, but **only** if “allowAnonymousAuthentication” is enabled on the IIS application. This setting is **not** allowed by our enterprise for security reasons. 

How can we can configure the IIS application to allow for WS Federation authentication to pass through?

**Comment by blowdart** [comment]
Can I ask the reasoning behind not allowing “allowAnonymousAuthentication"? 

The reason I ask is that even in older .NET Frameworks if you used a federated identity you'd have to have this option turned on in IIS, because until the federation happens you would have to be anonymous.

That setting really only makes sense for WebForms applications, or for integrated authentication against an AD, which of course WSFed would replace. 

If it makes things easier, you can loop me into an email conversation with them, and I'll wear my .NET Security PM hat in my responses.

**Comment by tomagnew** [comment]
Thanks @blowdart for the response. I agree with what you say, however we have to comply with DOD Stigs which are pretty adamant about that setting. I think that because .Net Core is so "new" the DOD has not had time to re-evaluate its position on this. Its frustrating because we've spent a great deal of time upgrading the site but we can't deploy it until we figure this out. Just out of curiosity if you know, is there any way to make the old WSFederationModule work in conjunction with the Asp.Net Core WS-Fed middleware or is that module only limited to a process running on the full .Net Framework?

**Comment by blowdart** [comment]
WIF and the old pieces just won't work I'm afraid, the architecture is too different.

**Comment by tomagnew** [comment]
That's what I thought, we tried it several times with no luck.

**Comment by tomagnew** [comment]
Here is a link to one of the Stigs I'm referring to: [2018-01-03/finding/V-76811]( https://www.stigviewer.com/stig/iis_8.5_site/2018-01-03/finding/V-76811)
Do you think its possible to enable authentication for a specific user account with lower privileges and implement impersonation so that the federated request can pass thru to the Kestrel server?

**Comment by blowdart** [comment]
It's asking you to check if the anonymous user is part of a privileged group, if anonymous access is enabled,

Anonymous being enabled in and of itself is not a finding.

The auditors are reading it wrong. But good luck in convincing them of that.

**Comment by tomagnew** [comment]
I completely agree, thank you for taking your time on this issue!

**Comment by blowdart** [comment]
The offer to talk to them is there, it might be more effective coming from an MS employee, which is kinda of horrid, but it's like consultancy sometimes, companies listen more to someone outside than someone inside, even if the message is the same

**Comment by blowdart** [comment]
I'm going to close this, as I think I've addressed it. If you need more, please reopen and @ me

**Comment by tomagnew** [comment]
@blowdart 
Just wanted to let you know that my company finally agreed that the Stig mentioned in our discussion is not violated for anonymous authentication as long we have "Specific user" checked and the account does not have elevated privileges. Many thanks for helping me resolve this.
