### ISSUE TITLE
On creating Startup, custom services do not resolves

### ISSUE THREAD

**Issue by sergeyshaykhullin** [aspnet/AspNetCore#9294]
### Describe the bug
I have a library for strongly typed IConfiguration wrapper, it works fine on 2.2, but in 3.0.0 `GenericWebHostBuilder.UseStartup` does not resolve custom services, already added to `IServiceCollection` to `HostBuilder`/`WebHostBuilder` at the moment `Startup` created using `ActivatorUtilities`.

For now used `GenericWebHostBuilder.HostServiceProvider`. It can resolve only `IHostingEnvironment` and `IConfiguration`.

### To Reproduce
Complete example: https://github.com/phema-team/Phema.Configuration/tree/master/examples/Phema.Configuration.Example
1. Use `builder.ConfigureServices((c, s) => s.AddSomeService())`
2. Use `builder.ConfigureWebHostDefaults` (call `builder.ConfigureWebHost`) and add `Startup`
3. In `Startup` add `SomeService` to constructor

### Expected behavior
All services added previously to `IServiceCollection` can be resolved in Startup creation

### Screenshots
![image](https://user-images.githubusercontent.com/46970457/55984928-46e1ae80-5ca7-11e9-8e23-58b9176233e6.png)
![image](https://user-images.githubusercontent.com/46970457/55984988-637de680-5ca7-11e9-90c9-96db93fbbe5e.png)

### Additional context
I think we should use in `GenericWebHostBuilder.UseStartup` for creating `Startup` all previously registered services passing `IServiceProvider` built from `IServiceCollection` parameter to `GenericWebHostBuilder.HostServiceProvider`. Logic the same, if `IHostingEnvironment`/`IConfiguration` resolve from `WebHostBuilderContext`, else try to resolve from already added services

I added pull request with potential fix https://github.com/aspnet/AspNetCore/pull/9296

**Comment by Tratcher** [comment]
This was an intention design change for 3.0. @davidfowl We need to write up an announcement.

**Comment by sergeyshaykhullin** [comment]
It has any workaround?

**Comment by Tratcher** [comment]
For your example here (https://github.com/phema-team/Phema.Configuration/blob/master/examples/Phema.Configuration.Example/Startup.cs), you can inject services directly into Configure.
`public void Configure(IApplicationBuilder app, IOptions<WebConfiguration> options)`

**Comment by sergeyshaykhullin** [comment]
Yes, that works fine, but any for ConfigureServices?

**Comment by Tratcher** [comment]
No, we don't support injecting services into ConfigureServices, it caused too many problems with singletons.

**Comment by Tratcher** [comment]
Announcement discussion post: https://github.com/aspnet/AspNetCore/issues/9337.

@sergeyshaykhullin note for database config we use IConfiguration directly, which is still supported.
https://github.com/aspnet/AspNetCore/blob/b1ca2c1155da3920f0df5108b9fedbe82efaa11c/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L61-L65

**Comment by Tratcher** [comment]
And the official announcement: https://github.com/aspnet/Announcements/issues/353

**Comment by springy76** [comment]
How shall the workaround be "inject services directly into Configure" when `Startup.Configure` doesn't have the information what to do at all because that info can't be transferred into the `Startup` class any more????

**Comment by Tratcher** [comment]
This issue is closed, please follow the announcement issue instead.
