### ISSUE TITLE
Update client-side Blazor projects to reference the Razor SDK instead of the Web SDK

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#9301]
@rynowak @SteveSandersonMS Is there any reason why the client-side Blazor projects reference the Web SDK instead of the Razor SDK? Should we update them to reference the Razor SDK?

**Comment by SteveSandersonMS** [comment]
Yes, if it was Razor SDK, then you can't launch it as an application in IISExpress from VS, because the tooling doesn't think it's meaningful to launch what appears to be a class library not an app.

We could change this, but it would be a tooling change (probably by Bill).

**Comment by danroth27** [comment]
We also discovered that the Web SDK includes the globbing patterns needed for publishing the content under the wwwroot folder.

**Comment by danroth27** [comment]
Closing this as this as this change seems to create more problems than it solves.
