### ISSUE TITLE
asp core 3.0  API Cant Return more than 120 item 

### ISSUE THREAD

**Issue by hossam300** [aspnet/AspNetCore#9322]
### Describe the bug
On Blazor ( Asp.net Core hosted ) default  Template Cant produce more than 120 item  
### To Reproduce
1. Create new Blazor ( Asp.net Core hosted ) 
2. Go to Blazor.Server Project => controller >SampleDataController.cs
3. replace WeatherForecasts Action With 
```C#
 public IEnumerable<WeatherForecast> WeatherForecasts()
        {
            var rng = new Random();
            return Enumerable.Range(1, **500**).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            });
        }
```
4. On browser console Failed to load resource: the server responded with a status of 500 (Internal Server Error)
![image](https://user-images.githubusercontent.com/6240222/56030466-32d89400-5d1d-11e9-8221-54a3d8e25856.png)
if you go to url/api/SampleData/WeatherForecasts  
![image](https://user-images.githubusercontent.com/6240222/56030546-64515f80-5d1d-11e9-8232-e7735add6722.png)

**Comment by Andrzej-W** [comment]
I can confirm that I observe exactly the same behaviour. It worked correctly in Blazor 0.6 ASP.NET Core Hosted. My old bug report for Bazor server-side https://github.com/aspnet/Blazor/issues/1223.
Current environment: ASP.NET Core Preview 3 + Blazor 0.9.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/8302. This is addressed in the preview4 release.
