### ISSUE TITLE
CSS folder not found on IIS .net core wwwroot

### ISSUE THREAD

**Issue by nyongrand** [aspnet/AspNetCore#9325]
Somehow I decided to build my web API and client separately after several hours failed to combine .net core 2.2 with vue+vuetify.

I build the client using Vue CLI, with this config:

    module.exports = {
      publicPath: process.env.NODE_ENV === 'production' ? '/joblist/' : '/',
    }
Then place the content of dist folder to wwwroot folder on .net core project, I use below code to enable static files serving:

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseHsts();
        }

        app.UseDefaultFiles();
        app.UseStaticFiles();
        app.UseMvc();
    }

Everything looks perfect when I debug with APP URL set to http://localhost:49602/joblist. But somehow when I publish to my Server, which is myserver/joblist, the server can't serve EVERYTHING placed inside wwwroot/css folder, so the site looks ugly.

At first, I thought the problem is the wwwroot path or something like that, but I can browse to wwwroot/js folder perfectly, I try add an empty txt file on css folder, but still I can’t open it from web browser, then I try to rename wwwroot/css folder to wwwroot/notcss, then update the HTML file to point at notcss folder, the site works perfectly this time.

Can anybody help me with this problem?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
