### ISSUE TITLE
Too many "Failed connection handshake" errors in our logs

### ISSUE THREAD

**Issue by rfrancisco** [aspnet/AspNetCore#9327]
### Describe the bug
In each of our servers logs we see dozens of "Failed connection handshake" errors every second. Each of our signalR servers is running in an AWS EC2 instance behind an AWS Application Load Balancer. 
We have taken a look at prevously reported issues related to this error message, and the solutions they presented had to do with NGINX configuration. We are not using nginx, since we rely on AWS ALB (with sticky sessions enabled) to route traffic to the servers, so we tried setting up a server that nginx (using the recommended settings), and removing the AWS ALB from the equation, but the problem persisted.

The clients connect to our servers using a javascript that uses @aspnet/signalr 1.1.4. In our local tests, in the most common desktop and mobile browsers, we don't find any problems connecting to signalR and we have hundreds of thousand os users connected, but we also don't know how many may not be connecting due to this error.

### To Reproduce
Can't reproduce the error locally, we just see it in our production environment logs.

### Expected behavior
Expect not to have these errors happening. Or at least not so frequently.

### Screenshots
![ubuntu_ip-172-31-54-19___opt_insurads_log](https://user-images.githubusercontent.com/1242411/56038430-d9c32d00-5d29-11e9-9e8b-d676c57d4fbd.png)

### Additional context
![ubuntu_ip-172-31-54-19___opt_insurads_log](https://user-images.githubusercontent.com/1242411/56037552-746e3c80-5d27-11e9-9033-f4264c85bd70.png)

Here are some logs taken with "Microsoft.AspNet.SignalR" at Debug log level: [log.zip](https://github.com/aspnet/AspNetCore/files/3073503/log.zip)

Also, the client script that users use to connect is built with @aspnet/signalr-1.1.4 but we've had these error messages even before we upgraded from 1.0.0-rc-final.

Let me know if there's any other information i can provide to help troubleshoot this.

**Comment by mikaelm12** [comment]
Can you share any client logic you're using to connect? Just a hunch but are you trying to implement any reconnect logic?

**Comment by rfrancisco** [comment]
Yes. We do have reconnect logic implemented on the client. 

Here is the related code: [messaging.ts.zip](https://github.com/aspnet/AspNetCore/files/3076093/messaging.ts.zip)

**Comment by anurse** [comment]
Thanks for the logs, we'll look at this in our upcoming milestone. If you are able to capture any network traces from the server side when this error occurs, that would be very helpful.

At the very least, we need a better log message than "Failed Connection Handshake" :)

**Comment by rfrancisco** [comment]
I provided a log file captured with debug log level. Did you see that?

**Comment by halter73** [comment]
The action item here is to distinguish between timeouts and invalid handshake responses in the error message.

**Comment by BrennanConroy** [comment]
@halter73 Is this still open on purpose?

**Comment by halter73** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [x] Relevant XML documentation comments for new public APIs are present.
    * [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [x] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [ ] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [VERSION]
            * ASP.NET Core Runtime: [VERSION]
            * .NET Core Runtime: [VERSION]
        * [x] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: Microsoft.AspNetCore.SignalR.Client 3.0.0-preview6.19304.6
