### ISSUE TITLE
Question: SignalR JWT authorization

### ISSUE THREAD

**Issue by daniel-ITC** [aspnet/AspNetCore#9329]
### Describe the bug
Due to the limitation of the Browser WebSocket, we cannot set custom headers to the connection so I had to find another way to secure it. I don't like to set the authorization token as a query parameter because it can be intercepted by malicious people and used to access also the other APIs. So I was thinking if I cannot secure the WebSocket with an HTTP header I can put under authorization only the POST /negotiate call.

I successfully did that by implementing my own HttpClient and passed to the client HubConnectionBuilder. But now I don't know how to put the /negotiate call under the authentication on the server side.

On my Startup.cs, under AddJwtBearer option, I'm listening for the call to /negotiate but I don't know how to validate the JWT token... Is there another way to validate authentication rather than the Authorize attribute? Or has someone a better solution?

### To Reproduce
1. Using this version of ASP.NET Core 2.2 with Angular 7

**Comment by anurse** [comment]
> I can put under authorization only the POST /negotiate call.

This isn't sufficient to secure your application. The connection ID returned by the `/negotiate` call is not designed to be used as a security token.

**Comment by daniel-ITC** [comment]
Thanks for your answer. Maybe I badly explained myself. I don't want to use the connection Id returned by the /negotiate call to secure my API. I already use an JWT token and I set it as an Authentication header to the /negotiate throw my custom HttpClient.
Server side I want to validate my token inside the Startup.cs. The only way that I found to validate an JWT token (server side) is throw the Authorize attribute. But I can't use it inside the Startup.cs.

**Comment by anurse** [comment]
I was referring to the fact that you only wanted to secure the `/negotiate` call. It's not sufficient to secure the `/negotiate` call, you **also need to** secure the actual WebSocket request. It's possible for a client to simply connect a WebSocket and spoof a connection ID. It's not something we'd expect a client to do, but the connection ID isn't designed as a security token (for precisely this reason).

**Comment by daniel-ITC** [comment]
@anurse Ok, you are right. Is there any way to secure also the WebSocket with a JWT token without passing it as a query parameter? The token can be sniffed from the WebSocket URL and used to access also the other API.
If not I was thinking to use a Cookie to secure the /negotiate and the WebSocket. The JWT will be used for the other API. But I don't think is an elegant solution. What do you think about?

**Comment by BrennanConroy** [comment]
If you're using https/wss then the URL should not be sniffable. https://security.stackexchange.com/questions/176164/is-it-possible-to-sniff-https-urls

**Comment by daniel-ITC** [comment]
Oh, nice to hear that. Thank you @BrennanConroy. So, if the query parameters cannot be sniffed throw https/wss the problem is solved. Thanks again.

**Comment by anurse** [comment]
> The token can be sniffed from the WebSocket URL and used to access also the other API.

The token can **always** be sniffed if the request is sent plain-text (non-`https`). Even when it's in a header, it's still just part of the plaintext request. It is **essential** that you always use `https` when dealing with user authentication.
