### ISSUE TITLE
400 Bad Request HttpDelete

### ISSUE THREAD

**Issue by JeremyButts** [aspnet/AspNetCore#9331]
### Describe the bug
I am getting a 400 bad request when using the HttpDelete.  Works when I use HttpGet.  I doubt this is a bug, but I have no idea what I am doing incorrectly.  This should be easy.

### To Reproduce
1. Using this version of ASP.NET Core 2.1
Mac OS 10.12.6
Using Kestrel
2. Run this code '....'
`[HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var request = new Delete.Command {Id = id};
            await _mediator.Send(request);
            return NoContent();
        }`
3. With these arguments '....'
DELETE https://localhost:5001/subscription/api/v1.0/participant/3
Accept: */*
Cache-Control: no-cache
400 Bad Request

### Expected behavior
Not get a bad request

### Additional context
Include the output of `dotnet --info`

**Comment by pranavkm** [comment]
Could you include Debug logs for the application? Perhaps an MVC filter is executing that's returning the 400.

**Comment by JeremyButts** [comment]
You are correct, it was the global AutoValidateAntiforgeryTokenAttribute filter. I added the IgnoreAnitforgeyToken to the api controller.  Thank you!
