### ISSUE TITLE
IHostedService don't run

### ISSUE THREAD

**Issue by future81** [aspnet/AspNetCore#9344]
I'm using Asp.net Core Timed background task to run a daily task on my site on Amazon ElasticBeanstalk Ec2 t2.micro instance

code is from [Docs][1]
    
    public Task StartAsync(CancellationToken cancellationToken)
    {
           
            DateTime now = DateTime.Now;
            
            DateTime Daily= DateTime.Today.AddHours(8.0);

               
            if (now > Daily)
            {
                Daily= Daily.AddDays(1.0);
            }
            var mylog = Path.Combine(Path.GetTempPath(), "mylog.txt");
            var logs = new List<string>();
            logs.Add(Daily.ToString());            
            var timeToGo = Daily- now;
            logs.Add(timeToGo.ToString());
            File.AppendAllLines(mylog, logs);
            _timer = new Timer(DoWorkAsync, null, timeToGo,
                TimeSpan.FromDays(1));

            return Task.CompletedTask;
        }
        
        private async void DoWorkAsync(object state)
        {
            var mylog = Path.Combine(Path.GetTempPath(), "mylog.txt");
            var logs = new List<string>();
            logs.Add("Resync started at" + DateTime.UtcNow.ToString("s"));
            
            File.AppendAllLines(mylog, logs);
            //my task here
         }

but my logging of task shows that `StartAsync` is repeated at random times and that `DoWorkAsync`is actually don't run 

here's two samples of log one when `DoWorkAsync` didn't run in its supposed time 

    4/12/2019 8:00:00 AM <---- when next task will run
    05:34:46.1320712     <---- time remaining to run it
    4/12/2019 8:00:00 AM <---- that means StartAsync had runned again
    02:25:30.0774712
    4/12/2019 8:00:00 AM
    01:00:23.8784953
    4/12/2019 8:00:00 AM
    00:21:29.8735978  <---- it should run after this line but no record
    4/13/2019 8:00:00 AM
    23:43:40.0857128
    4/13/2019 8:00:00 AM

here's the other log sample when `DoWorkAsync` had runned

    4/11/2019 8:00:00 AM
    00:48:47.3551756
    4/11/2019 8:00:00 AM
    00:17:53.6569079
    Resync started at2019-04-11T08:00:00 <---- this message is from DoWorkAsync
    other logs of my task
    4/12/2019 8:00:00 AM
    23:23:28.4222248
    4/12/2019 8:00:00 AM
    22:29:50.2246145
    4/12/2019 8:00:00 AM

I'm using ASP.net core 2.1
I don't know if this is AWS Ec2 problem or IHostedService and what's suitable solution

  [1]: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1#timed-background-tasks

**Comment by davidfowl** [comment]
Does it work locally?

**Comment by future81** [comment]
I didn't leave it open for that time because I would need to leave it open more than one day anyway I'm testing now a solution including setting IIS idle timeout to 0 and recycling time to specfic daily time not every 29 hours as the default It'll need to be tested for 2 or more days though

**Comment by davidfowl** [comment]
Reduce the interval to make sure it works? Try to narrow down the issue so that we can figure out what the root cause is. It sounds like there’s a lot of variables at play here.

**Comment by eiva** [comment]
Not sure that it is a proper way to doing this but it works and pretty simple:
```
private async Task doSomething(CancellationToken cancellationToken) {
   while (!cancellationToken.IsCancellationRequested) {
      ... DO Stuff
      await Task.Delay(TimeSpan.FromHours(_interval), cancellationToken);
   }
}

public Task StartAsync(CancellationToken cancellationToken) {
   var worker1 = trackerUpdateTask(_stoppingCts.Token);
   .... another workers
   _executionTasks = Task.WhenAll(worker1, ....);

   if (_executionTasks.IsCompleted) return _executionTasks;
   return Task.CompletedTask;
}

public async Task StopAsync(CancellationToken cancellationToken)  {
    if (_executionTasks == null) return;
    try {
      _stoppingCts.Cancel();
   } finally {
      await Task.WhenAny(_executionTasks, Task.Delay(Timeout.Infinite, cancellationToken));
   }
}
```
Hope it will be helpful.

**Comment by Tratcher** [comment]
Yeah, it sounds like the site is being shut down due to idleness.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
