### ISSUE TITLE
Expose CipherSuitesPolicy on Kestrel

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#9349]
SslStream has a new API for controlling ciphers that Kestrel should surface.
https://github.com/dotnet/corefx/pull/36775/files#diff-bd768ea3857573965e853e2ce2563434R134

HTTP/2 requires restricting the ciphers used. Do we do this by default or leave it as an option?

**Comment by Tratcher** [comment]
@davidfowl:

> it would be good if we could expose this entire type (if it makes sense) so we could avoid the property by property copy when new features are added.

Since we need to create one per connection you could expose a `Action<SslServerAuthenticationOptions>` to let people tweak the configuration, but it's not the simplest type to configure:

https://github.com/aspnet/AspNetCore/blob/7bd1e5ea2022039e23d0f83f0535a7570891176b/src/Servers/Kestrel/Core/src/Internal/HttpsConnectionAdapter.cs#L135-L171

**Comment by anurse** [comment]
Let's add the configuration callback.

**Comment by Wayne-Xiong** [comment]
Is there an example showing how to set the cipher suites in Kestrel? We are running our .NET core service in a Linux container and would love to see how we can make our service compliant. Thanks!

**Comment by Tratcher** [comment]
@Wayne-Xiong no, the in-app feature hasn't been built yet. For now you need to configure your ciphers directly on the machine in OpenSsl.

**Comment by Wayne-Xiong** [comment]
Thanks Chris. Do we have an estimate on when we will have this feature ready? Also, do you know how to config that in OpenSSL? Is there a sample somewhere we can take a look?

**Comment by Tratcher** [comment]
This is scheduled for 3.0.0-preivew6, our next milestone.

@blowdart for OpenSsl config suggestions.

**Comment by blowdart** [comment]
AFAIK You can't configure it in OpenSSL without recompiling a custom version. Instead you'd block in nginx or apache (https://medium.com/@davetempleton/tls-configuration-cipher-suites-and-protocols-a01ee7005778)

**Comment by Wayne-Xiong** [comment]
Thanks guys. @Tratcher, when is the 3.0.0-preview6 release scheduled? Would love to understand about the timeline a little bit. Thanks!

**Comment by Tratcher** [comment]
@shirhatti for schedule questions.

**Comment by anurse** [comment]
> when is the 3.0.0-preview6 release scheduled?

We don't commit to specific dates for individual previews, we're currently aiming for early June for preview 6. To view our current committed timeline, see the [.NET Core Roadmap](https://github.com/dotnet/core/blob/master/roadmap.md).

**Comment by anurse** [comment]
We should look at two aspects to this:
* Make sure our options are configured right for HTTP/2
* Add the `Action<SslThingyOptions>` callback.

**Comment by Tratcher** [comment]
`Action<SslThingyOptions>` change merged.

Need to experiment with the new CipherSuitesPolicy on SslServerAuthenticationOptions to see how to use it to meet the HTTP/2 spec requirements. It's unclear yet if that will be a sample, kestrel change, etc..

**Comment by Tratcher** [comment]
Notes:
https://github.com/dotnet/corefx/blob/025bb33e27b15d973e8be430a9329309ecac37d3/src/System.Net.Security/src/System/Net/Security/CipherSuitesPolicy.cs
https://github.com/dotnet/corefx/blob/025bb33e27b15d973e8be430a9329309ecac37d3/src/System.Net.Security/src/System/Net/Security/TlsCipherSuite.cs
TlsCipherSuite is an enum! 
At least it's backed by well defined RFC values. You'd have to constantly update the list, but failing that you could always cast an int and it should work.

How do we enumerate available Ciphers on the machine (so we can filter out the ones prohibited by HTTP/2)? Is it sufficient to enumerate the enum values? You wouldn't get new ones without a runtime update.

**Comment by Tratcher** [comment]
Nevermind, CipherSuitesPolicy isn't implemented on Windows, we can't enable anything by default.
https://github.com/dotnet/corefx/blob/025bb33e27b15d973e8be430a9329309ecac37d3/src/System.Net.Security/src/System/Net/Security/CipherSuitesPolicyPal.Windows.cs
https://github.com/dotnet/corefx/issues/24588#issuecomment-482764511

**Comment by Tratcher** [comment]
https://youtu.be/x5vbM3zB0_I?t=4321

**Comment by Tratcher** [comment]
Verified the new callback in SDK 3.0.100-preview6-012234.
