### ISSUE TITLE
Simple Way To Handle Minfication At Development Mode or Not

### ISSUE THREAD

**Issue by prince272** [aspnet/AspNetCore#9357]
This code will determine whether to add a .min at development mode or remove it if not.

     public static class HtmlExtensions
    {
        public static IHtmlContent Minify(this IHtmlHelper html, string filename)
        {
            var hostingEnvironment = html.ViewContext.HttpContext.RequestServices.GetRequiredService<IHostingEnvironment>();

            filename = Minify(filename, !hostingEnvironment.IsDevelopment());

            return new HtmlString(filename);
        }

        public static string Minify(string filename, bool minify, string minifyExtension = ".min")
        {
            string ext = Path.GetExtension(filename);
            string name = Path.GetFileNameWithoutExtension(filename);
            string result = string.Empty;

            if (minify)
            {
                if (!name.EndsWith(minifyExtension))
                    result = $"{name}{minifyExtension}{ext}";
                else
                    result = filename;
            }
            else
            {
                if (name.EndsWith(minifyExtension))
                    result = $"{name.Remove(name.LastIndexOf(minifyExtension))}{ext}";
                else
                    result = filename;
            }

            return result;
        }
    }

 To use:
    <script src="~/libs/jquery/@Html.Minify("jquery.js")" asp-append-version="true"></script>

**Comment by blowdart** [comment]
This doesn't appear to be a bug, or a feature request, so I'm closing the issue.
