### ISSUE TITLE
[Blazor] create my own component base class

### ISSUE THREAD

**Issue by aboimpinto** [aspnet/AspNetCore#9363]
Hello team, 

I'm glad that we can create SPA with only C#, this will level the WebDevelopment field. I use to be a Silverlight / WPF developer and Iove the MVVM pattern because of the separation of the UI code and the UI representation and testability.
Here is my experience of the MVVM patter in Blazor 
https://github.com/aboimpinto/BlazorMVVM

I already made the forecast page full MVVM like I want but (there is always a but), I need to have this code in the "code-behind" (function area)
![image](https://user-images.githubusercontent.com/1231687/56091124-f5a20c80-5eaa-11e9-961e-9325c6f67bac.png)

How can I create a component base class where all my components inherit from where I can override the OnInitAsync method and call the "Load" method if the ViewModel implement the ILoadable interface?

I would like to remove as max as possible the code from the "code-behind" (functions area)

what are the experiences in this area?

best regards
Paulo Aboim Pinto

**Comment by Andrzej-W** [comment]
You can create something like this:
```c#
    interface ILoadable
    {
        Task Load();
    }
    public class MyModel: ILoadable
    {
        public string MyProperty { get; set; }

        public async Task Load()
        {
            await Task.Delay(1000); // simulate data loading
            MyProperty = "Hello";
        }
    }
    public class GenericComponentBase<T> : ComponentBase where T : new()
    {
        protected T dataModel = new T();
        protected override async Task OnInitAsync()
        {
            if (dataModel is ILoadable)
                await (dataModel as ILoadable).Load();
        }
    }
```
Now you an create a view (Blazor page).
```html
@page "/mypage"
@inherits GenericComponentBase<MyModel>
<h1>Message: @dataModel.MyProperty</h1>
```

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @Andrzej-W. 

Yes, you can use @inherits.

**Comment by aboimpinto** [comment]
Thanks for the answer ...

This solution works +/- .... now I cannot have any contructor injection on the ViewModel .... 

do you have a solution for that too?

**Comment by aboimpinto** [comment]
I could make it work but the had to twist a little bit the MVVM pattern.
you can check on my project https://github.com/aboimpinto/BlazorMVVM

the ViewModel file looke liks this

`namespace BlazorMVVM.ViewModels
{
    public class FetchDataBlazorComponent : BlazorComponent
    {
        [Inject]
        public IWeatherForecastModel WeatherForecastModel { get; set; }

        public IReadOnlyCollection<WeatherForecast> WeatherForecast { get; private set; }

        protected override async Task OnInitAsync()
        {
            await this.FetchWeatherForecast();
        }

        public async Task FetchWeatherForecast()
        {
            this.WeatherForecast = await this.WeatherForecastModel.FetchWeatherForecast();
        }
    }
}`

works but I implement the solution that you provide as it is because I need to inject in ViewModel the Model that need injection of the HttpClient .... 

Anyone has a better solution or everyone reach the same solution?
