### ISSUE TITLE
ASP.NET Core + Angular template doesn't support monorepo projects

### ISSUE THREAD

**Issue by lonix1** [aspnet/AspNetCore#9369]
### Describe the bug
The ASP.NET Core (2.2) + Angular template doesn't work in a monorepo setup.

The template puts everything in the root:

````
/
  bin/
  obj/
  ClientApp/
  Server.csproj
  Startup.cs
  etc.
````

A monorepo has more structure because there are multiple library and client (angular) projects:

````
/
  libs
    client --------------------------------------->  was originally in the root
    client2
    server
      bin/ -------------------------------------
      obj/                                     |
      Server.csproj                            |-->  was originally in the root
      Startup.cs                               |
      etc. -------------------------------------
    lib1
    lib2
````

### To Reproduce
1. `dotnet new angular`
2. Move directories to suit the structure above
3. Edit paths in `Startup.cs` to match the new structure
3. Run server app

### Expected behavior
I expect it to work, but I get `InvalidOperationException: Failed to start 'npm'`

Both the server and client work properly when run separately (`dotnet run` and `npm run start`), but not when run together.

### Additional context
aspet core 2.2.4
sdk 2.2.105
ubuntu 18.10
vscode

**Comment by lonix1** [comment]
I got it working like this:

1. changed to monorepo structure as shown in my question above

2. edited `Server.csproj` (paths are relative to server app's directory):

````xml
<!--<SpaRoot>ClientApp\</SpaRoot>-->
<SpaRoot>../client/</SpaRoot>
````

3. edited `Startup.cs` (paths are relative to workspace's directory):

````csharp
services.AddSpaStaticFiles(configuration => {
  //configuration.RootPath = "ClientApp/dist";
  configuration.RootPath = "./libs/client/dist";
});
````

and

````csharp
app.UseSpa(spa => {
  //spa.Options.SourcePath = "ClientApp";
  spa.Options.SourcePath = "./libs/client";
  // etc.
});
````

This is not explained anywhere, and would be a good idea to have as documentation or a sample repo - most devs who work on client and server (and supporting libs) separately, will be using a monorepo structure.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lonix1.
Glad you've found solution to your problem. Happy to accept a PR for docs if you want.

**Comment by lonix1** [comment]
I take back what I wrote - the fix wasn't reproducible. Right now no way to get this to work in monorepos. (Which it the default for large systems)

Please reopen.

If someone gets this working, please comment here.
