### ISSUE TITLE
[Feature] Support for pnpm

### ISSUE THREAD

**Issue by lonix1** [aspnet/AspNetCore#9373]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
The "SPA services" use `npm`. It would be nice to have the option to use  [`pnpm`](https://github.com/pnpm/pnpm) instead.

### Additional context
pnpm is **CLI-compatible** with npm, so everything works without any change. And it would be optional for those who want it, the rest could carry on using npm.

But, pnpm is much more useful, as amongst other things:
- it's MUCH faster
- symlinks packages instead of downloading them again and again and again - this means we can save literally gigs and gigs of diskspace (which is at a premium on systems with small SSD drives)
- provides much more friendly and informative CLI feedback
- has built-in equivalent to `npx npm-check -u`
- works great for monorepos
- please see [the readme](https://github.com/pnpm/pnpm#pnpm) for more benefits

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lonix1.
This is not something we plan to do in the near future.
