### ISSUE TITLE
Blazor forms validation system...

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#9374]
Could you please point out the location of the code that prevents the form posting back to the server when the user taps the submit button. I guess that somewhere in the pipeline there is code (perhaps in JS) that should prevent the default behavior.

Thank you for your kindness..

**Comment by campersau** [comment]
Here it is:

https://github.com/aspnet/AspNetCore/blob/3988f3b0bab04fb6f3e3bdd7067550f18b11cdca/src/Components/Browser.JS/src/Rendering/BrowserRenderer.ts#L379-L381

https://github.com/aspnet/AspNetCore/blob/3988f3b0bab04fb6f3e3bdd7067550f18b11cdca/src/Components/Browser.JS/src/Rendering/BrowserRenderer.ts#L9

**Comment by enetstudio** [comment]
Thank you so much, @campersau !
