### ISSUE TITLE
Expose tags in HealthReport

### ISSUE THREAD

**Issue by viktorpeacock** [aspnet/AspNetCore#9378]
### Is your feature request related to a problem? Please describe.
New health checks feature supports custom tag creation when defining the health checks. We can then specify a custom ResponseWriter instance for writing out a HealthReport. The problem is that the HealthReport and its entities do not contain tags.

### Describe the solution you'd like
When defining a custom ResponseWriter instance, i would like to write out health check tags into the response.

`       private Task CustomResponseWriter(HttpContext httpContext, HealthReport healthReport)
        {
           var tags = healthReport.Entries[0].Value.Tags;  
        }`

### Describe alternatives you've considered
I have all names of the health checks in the report, so I can have an in-memory list of health check names and their tags. This is not ideal, but will work.

**Comment by rynowak** [comment]
@viktorpeacock - willing to send a PR for this? The code change would go here: https://github.com/aspnet/Extensions/blob/master/src/HealthChecks/HealthChecks/src/DefaultHealthCheckService.cs#L109

**Comment by viktorpeacock** [comment]
@rynowak sure!

**Comment by rynowak** [comment]
This was done in preview 5. Thanks @viktorpeacock
