### ISSUE TITLE
Dynamically adding the "runat" attribute to DropDownList inside a GridView

### ISSUE THREAD

**Issue by Malik-G** [aspnet/AspNetCore#9383]
### Is your feature request related to a problem? Please describe.
I am trying to dynamically add the "runat" attribute to a series of DropDownLists that are being dynamically rendered inside of a GridView, with each DropDownList being its own column. This needs to be dynamic because the user's settings effect the number of columns.

The GridView "ID" is gv1...
I tried gv1.runat = "server"...
and gv1.Attributes.Add("runat", "server")...
but neither approach works.

### Describe the solution you'd like
I'd like some kind of explanation as to why this isn't possible, and any possible solutions. Also curious if DropDownLists can display data from the database without using runat="server"?

### Describe alternatives you've considered
I've found multiple discussions online regarding this nuance but have not found a sufficient answer to solve the problem.

### Additional context
I am working with .NET Framework 4, ASP.NET, C#, and JavaScript.

**Comment by blowdart** [comment]
This repo is for asp.net core. As you've said you're using .NET Framework 4 and GridView you aren't using core.

Usage questions for .NET Framework are fit better on StackOverflow, please post your question there.
