### ISSUE TITLE
Remove AuthorizationOptions.RequiredPolicy

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9398]
Discussed this offline and support for this newly added option can be removed

**Comment by Tratcher** [comment]
@blowdart @HaoK Very disappointed. I tried to build an app today that required all requests to be authenticated. You'd think this would be easy with a default policy and the UseAuthorization middleware. Nope.

I'm not using endpoints and therefor I cannot use the AuthZ middleware. I have to write my own AuthZ middleware that does this:
```
            var result = await context.AuthenticateAsync();
            if (!result.Succeeded || !result.Principal.Identity.IsAuthenticated)
            {
                await context.ChallengeAsync();
                return;
            }
            context.User = result.Principal;
```

**Comment by blowdart** [comment]
We didn't touch default policy :)

So this went because

a) Nothing was using it
b) No-one could explain what it was for
c) It was badly named.

If you want to create a clear issue with your requirements, we can bring something back, just not "RequiredPolicy"

**Comment by HaoK** [comment]
I did a bad job explaining just how common a scenario it would be I think, given that Chris tried to do it like 1 day after we removed it...

**Comment by blowdart** [comment]
The bad name doesn't help.

Chris will create a new issue, specifically focusing on this and we can thrash out approaches.

**Comment by HaoK** [comment]
Not saying the names are good, but DefaultPolicy doesn't do what you would think either, RequiredPolicy makes sense if you understand what DefaultPolicy is (which noone probably does)

**Comment by Tratcher** [comment]
One question before I start: Do we expect everything to move to endpoints? E.g. static files, custom app middleware, etc.?

**Comment by blowdart** [comment]
Oi. Closed issue. Take it elsewhere. You both should know better :)
