### ISSUE TITLE
Identity UI experience issues on SPA apps

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#9403]
Found during verification.

1. Identity UI pages have a footer, but SPA apps do not.
2. Identity UI NavBar does not contain non-auth links, but Home/Counter/FetchData pages do.
3. The link to the Privacy page in the footer of an Identity UI page actually points to the current page.

**Comment by ryanbrandenburg** [comment]
4. When deployed to an Azure App Service the register and login links are not removed once you login, and  there are console errors in the browser
```
HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(Fetch)GET - https://angularauthtest.azurewebsites.net/_configuration/Angular
```
5. Needed to change the bitness of the publish profile to x86 before it would work as a self-deployed app.

**Comment by ryanbrandenburg** [comment]
All of the above were from testing Angular.

For React on Azure App Service the "Could not load settings" error seems to be even more pronounced as it seems to totally prevent Registration or Login. That one seems pretty bad, @mkArtakMSFT to re-prioritize as he sees fit based on this new info.

**Comment by javiercn** [comment]
I was not able to repro this for angular on preview4.
I deployed following the instructions on the tutorial and worked just fine (self-contained x86) https://angularindividualpreview4final20190422064054.azurewebsites.net/

**Comment by javiercn** [comment]
I can't repro this with React either. (I deployed on top of the angular website for convenience).

**Comment by ryanbrandenburg** [comment]
The register page to the site you just linked doesn't work on Chrome for either me or Pranav (no console errors, just never loads any content but the navbar). I see the same behavior for the Identity/Account/Manage link that you get once you log in on either Chrome or Firefox.

**Comment by javiercn** [comment]
@ryanbrandenburg You are right, I see this now. This is really weird, seems like the url is not being caught by identity and it's going to the client-side router.

**Comment by javiercn** [comment]
@danroth27 @ryanbrandenburg It's the react service worker causing grief again.

**Comment by javiercn** [comment]
That's why you don't see it the first time you visit the page, but only later on.

**Comment by javiercn** [comment]
I don't think there's anything left to do here.
> * Identity UI pages have a footer, but SPA apps do not.

They use different layouts, so unless we decide to sync layouts across spa and non spa templates there's nothing to do here.

> * Identity UI NavBar does not contain non-auth links, but Home/Counter/FetchData pages do.

One is using the layouts from the app (which contains app specific links) vs the embedded identity UI layout, which obviously doesn't contain any link. Again there's nothing we can do here. Users can override the identity UI layout to provide a more consistent experience, but they will have to duplicate layout code.

> * The link to the Privacy page in the footer of an Identity UI page actually points to the current page.

That is because there is no privacy page on the SPA templates, we either add an endpoint or we remove it completely, at the cost that it will not be in the non-spa templates either.

@danroth27 I'm closing this but tagging you in case you have some spicy thought about fixing any of these things.

**Comment by danroth27** [comment]
We should at least do something to fix the broken privacy link. 

Also don't we add a *_ViewImports.cshtml* to other web templates to have the identity UI pick up the layout from the app?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg is the privacy link fixed already? If not, let's do that only during preview 9.

**Comment by mkArtakMSFT** [comment]
@javiercn assigning this to you to tackle the remaining work here. Please work with @danroth27 to lock down on what the experience should look like.

**Comment by mkArtakMSFT** [comment]
Reassigned this to @HaoK who owns the IdentityUI

**Comment by HaoK** [comment]
@danroth27 @blowdart what's the work left to be done here?

**Comment by blowdart** [comment]
Make the privacy link work.

**Comment by HaoK** [comment]
change merged into Preview9, will merge/cherry pick to master for 3.1/5.0
