### ISSUE TITLE
Proxy scenario perf regression

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#9404]
Actually in CoreFx, but opening in aspnet until I get more information

![image](https://user-images.githubusercontent.com/1165805/56170987-7e4aa680-5f98-11e9-82ee-9a0e2fc50a76.png)

__Updated__

3.0.0-preview-27408-1 -> 3.0.0-preview-27409-1

Microsoft.NetCore.App / Core FX
https://github.com/dotnet/corefx/compare/c2bbb6a5ee5ff67e5e8353e154d7b4c4f2f83143...e1c0e1d4928b27113cdb2d021f4abbb202c9892a

Microsoft.NetCore.App / Core CLR
https://github.com/dotnet/coreclr/compare/a51af0838709ca81b51bee236865a39b31f68f41...4e5df11e42457b6201545e672a2f3d1eb18e47e7

Command lines:

```
dotnet run -- --server http://10.10.10.2:5001 --client http://10.10.10.4:5002 `
-j ..\Benchmarks\benchmarks.httpclient.json -n HttpClientFactory --sdk Latest --self-contained --aspnetcoreversion 3.0.0-preview3-19116-01 --runtimeversion 3.0.0-preview-27408-1

dotnet run -- --server http://10.10.10.2:5001 --client http://10.10.10.4:5002 `
-j ..\Benchmarks\benchmarks.httpclient.json -n HttpClientFactory --sdk Latest --self-contained --aspnetcoreversion 3.0.0-preview3-19116-01 --runtimeversion 3.0.0-preview-27409-1
```

**Comment by benaadams** [comment]
Looks like two drops?

![image](https://user-images.githubusercontent.com/1142958/56207318-5580ea80-6046-11e9-80d4-76ee71171268.png)

**Comment by sebastienros** [comment]
The first drop corresponds to when I changed the benchmarks to actually flow the headers.

**Comment by sebastienros** [comment]
@stephentoub this benchmark is mostly about HttpClient under load, no SSL. Do you see anything in the changes I linked to that could explain the regression?

**Comment by stephentoub** [comment]
> Do you see anything in the changes I linked to that could explain the regression?

Nothing jumps out at me.

**Comment by sebastienros** [comment]
I will investigate then.

**Comment by sebastienros** [comment]
After investigating, it looks like a regression between 

3.0.0-preview-27408-1 -> 3.0.0-preview-27408-3

Microsoft.NetCore.App / Core FX
https://github.com/dotnet/corefx/compare/c2bbb6a5ee5ff67e5e8353e154d7b4c4f2f83143...ede577ca971a46a54f53ff7daa3e9ce5e725bc95

Microsoft.NetCore.App / Core CLR
https://github.com/dotnet/coreclr/compare/a51af0838709ca81b51bee236865a39b31f68f41...4e5df11e42457b6201545e672a2f3d1eb18e47e7

Then I fetched both runtimes and tried to find which changed assemblies might cause this, and I can recover the previous performance by using `System.Globalization.Native.so` from the previous runtime.

Looking at the diff, there is this file that has changed:

`src/corefx/System.Globalization.Native/pal_collation.c`

Something I need to mention also is that after this runtime version is taken into account only this benchmarks is changed. Everything seems stable.

Here is the code that the benchmark is running:

https://github.com/aspnet/Benchmarks/blob/711f2b81cbd5dc1c2022cae0606e76a7eb79edc1/src/Proxy/Program.cs#L134-L144

**Comment by sebastienros** [comment]
/cc @filipnavara @janvorli as it seems to come from this commit: https://github.com/dotnet/coreclr/pull/22390/files

I'd say that it's not because of this PR https://github.com/dotnet/coreclr/commit/34d50b056150ba9101ee977dded9cee3c663fab6 though they are pretty close and the but the diff starts on Feb 04. To be sure I could run a benchmark if someone could give me the System.Gloablization.Native.so that only reverts this commit.

**Comment by filipnavara** [comment]
Are you absolutely positive about those commit lists? I'd expect https://github.com/dotnet/coreclr/pull/22378 to be the primary suspect if System.Globalization.Native is involved. The change in https://github.com/dotnet/coreclr/pull/22390/files should be harmless unless the C runtime library is significantly broken.

I'll try to reproduce the results on the weekend, but if you find anything out please share it here.

**Comment by filipnavara** [comment]
I'm going through possible regressions from dotnet/coreclr#22378.

[This line](https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/pal_collation.c#L283) is missing `customRules->size == 0` condition. Some `calloc`s could be replaced with `malloc`s and avoid zeroing memory. There's potential for some performance regression in some of the `*SortHandle` functions, but not sure if it's big enough to account for this. I will submit patch to address the obvious things.

**Comment by janvorli** [comment]
I have applied a delta to the current master that undoes the change made in https://github.com/dotnet/coreclr/pull/22390 and shared the System.Globalization.Native.so with @sebastienros. He has verified that it fixes the perf regression.

**Comment by sebastienros** [comment]
@filipnavara if you are not sure whether a change is beneficial or not, just build many versions and I can run the numbers for each build. Put them on //scratch2.

**Comment by filipnavara** [comment]
@janvorli Wow. That's very surprising. I'll look at it again. The change itself doesn't fix any bug and it should have generally improved performance which makes it surprising that quite the opposite happened. If I don't come up with a good explanation I'll submit a PR to revert it.

**Comment by sebastienros** [comment]
I am quite confident with the way I ran it, but there is always space for a human error (me). To be very confident feel free to give me versions with obvious regressions, even based on the reverted commit, to be sure I get the expected results. That would also make me fell more confident.

Something I want to insist on also is that I just patch "this" file, no other one, and I am not sure if one or the other versions could actually trigger some behavior coming from a separate module. I can also share the full standalone application if you want to check which bits are measured. But you will see that only this file will have changed in the end.

**Comment by filipnavara** [comment]
I don't doubt your findings. It must be some weird thing with the way the `tsearch` function is used. I'll try to produce a more localized test to see if I can reproduce the behaviour. I'd actually be happy if it turns out to be caused by this small change since the one preceding it was huge and much harder to check for any regressions.

**Comment by filipnavara** [comment]
I'm getting a suspicion that the problem is actually the changed structure layout in that commit that causes the pthread mutex to be aligned differently. However that's kinda hard to measure.

@janvorli Would it be possible for you to make a build that swaps these two lines: https://github.com/dotnet/coreclr/blob/42b5509b1b8f3be12876579aa23a3cb3ed2ca7a4/src/corefx/System.Globalization.Native/pal_collation.c#L45-L46 ? My only Linux build machines are in the cloud and it would take me a while to set it up properly.

**Comment by janvorli** [comment]
Sure, I will do that.

**Comment by janvorli** [comment]
@filipnavara that change had no effect.

**Comment by filipnavara** [comment]
Thanks for testing it. I will submit a PR to revert the change and continue investigating on my Linux machine to see if it's anything I can reproduce.

**Comment by filipnavara** [comment]
I reduced it to the following test case in plain C: https://gist.github.com/filipnavara/31791b216078706e0b465f7a103ff01f

On macOS using `tsearch` is a notch faster than `tfind`, but it's close to a measurement error for a sparse distribution. On Ubuntu (Linux mono-linux-build 4.15.0-1019-azure #19-Ubuntu SMP Thu Jul 26 19:54:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux) running in Azure `tsearch` is consistently around 15%-18% slower.

**Comment by sebastienros** [comment]
How do you run measure the differences? I ran the code but it simply output `12`.

**Comment by filipnavara** [comment]
@sebastienros by running it under `time` command.

**Comment by sebastienros** [comment]
on my physical machines I get this:

| Cores  | tsearch  | tfind  |
|---|---|---|
| 6/12 HT  | 0.900s  | 0.750s  |  
| 14/28 HT | 1.113s  | 0.927s  |

**Comment by benaadams** [comment]
A side question; if the regression is in Globalization; how is HttpClient using globalization? Wouldn't have thought it would be involved; though I may be wrong?

**Comment by benaadams** [comment]
A side question; if the regression is in Globalization; how is HttpClient using globalization? Wouldn't have thought it would be involved; though I may be wrong?

i.e isn't it all mostly ascii formats and fairly invariant?

**Comment by stephentoub** [comment]
It's not just HttpClient involved here... isn't this an ASP.NET site that in turn makes HttpClient requests?

**Comment by benaadams** [comment]
Yeah; but it doesn't do anything particularly interesting, except this line...

`new Uri(UriHelper.BuildAbsolute(_scheme, _host, _pathBase, context.Request.Path, context.Request.QueryString.Add(_appendQuery)))`

Checking [`UriHelper`](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Extensions/src/UriHelper.cs) its doing a bunch of `string.IndexOf(string)` which is CurrentCulture, so it might be that...

**Comment by benaadams** [comment]
Made a PR for that class https://github.com/aspnet/AspNetCore/pull/9537

**Comment by benaadams** [comment]
Looks like its back to normal

![image](https://user-images.githubusercontent.com/1142958/56472213-98323080-6453-11e9-96ff-2c25baf93280.png)

**Comment by filipnavara** [comment]
Thanks for checking (and fixing the incorrect usage of Current culture)!

**Comment by sebastienros** [comment]
Fixed, thanks @filipnavara @benaadams @janvorli 

And as a side note, we are now measuring on windows with the same hardware, and it's more than 200K RPS where Linux is at 80K. For some comparison, on the same proxy scenario HAProxy is at 110K RPS on linux with the same conditions. And we keep a 99th latency of 6ms. 

@NickCraver maybe something interesting for you here? Providing my numbers are correct, there is always room for errors.
