### ISSUE TITLE
Dotnet Core cookies are getting expired within 5 minutes with WSFederation and SSO

### ISSUE THREAD

**Issue by sankp** [aspnet/AspNetCore#9407]
Hi,

I have aspnet core 2.2 mvc application which is also using web api. I am using WSFederation Security with SSO. Login and Cookies are working fine with this but after 5 mins my cookies are getting expired somehow and my web api calls turns into 302 response because SSO redirects.
How can I make my cookie valid for longer period of time. I have tried different options available but nothing seem to be working.

Here is my code.

`services.Configure<CookiePolicyOptions>(options =>
                {                    
                    options.CheckConsentNeeded = context => true;
                    options.MinimumSameSitePolicy = SameSiteMode.None;                   
                });

                services.AddAuthentication(sharedOptions =>
                {
                    sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
                })

                .AddWsFederation(options =>
                {
                    // Set the Metadata Address
                    options.MetadataAddress = requestUri.AbsoluteUri;
                    // Set the WS-Federation realm.
                    options.Wtrealm = pingFederateSettings.Wtrealm;
                })

                .AddCookie(p =>
                {
                    p.SlidingExpiration = true;
                    p.Events.OnSigningIn = (context) =>
                    {
                        context.CookieOptions.Expires = DateTimeOffset.UtcNow.AddDays(30);
                        return Task.CompletedTask;
                    };
                    p.Events.OnRedirectToAccessDenied = (context) =>
                    {                        
                        return Task.CompletedTask;
                    };                    
                    p.Events.OnValidatePrincipal = (context) =>
                    {
                        return Task.CompletedTask;
                    };
                });
`

**Comment by blowdart** [comment]
You can't use SlidingExpiration with an expiry date on the cookie. It's either/or.

**Comment by Tratcher** [comment]
The default is 14 days, sliding. You shouldn't need to do anything else.
https://github.com/aspnet/AspNetCore/blob/4649449206edae4992e09419334e736726fd2c8e/src/Security/Authentication/Cookies/src/CookieAuthenticationOptions.cs#L32-L34

Start by removing OnSigningIn.

WsFederation does have UseTokenLifetime=true by default. Do your WsFed tokens have a 5 min expiration? Try disabling UseTokenLifetime.
https://github.com/aspnet/AspNetCore/blob/4649449206edae4992e09419334e736726fd2c8e/src/Security/Authentication/WsFederation/src/WsFederationOptions.cs#L155

**Comment by sankp** [comment]
Thanks @Tratcher UseTokenLifetime = false worked. Cookies are not getting expire now. However I can override ExpireTimeSpan to any TimeSpan right ? which will become actual expiration TimeSpan of the cookie.

**Comment by Tratcher** [comment]
Yes you can set ExpireTimeSpan. Note that value is primarily embedded inside the cookie and used by the server for verification. We don't set the normal cookie expiration value you'd see in the browser debugger tool sunless you set the "Remember Me" (IsPersistent) option for persisting cookies beyond this browser session.

**Comment by sankp** [comment]
Thanks @Tratcher for your help. We don't provide login or logout functionality. It's all handled by SSO site. so I am good for now.
