### ISSUE TITLE
The gRPC template spits out a debug log by default

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#9408]
### Describe the bug
Make a new preview4 grpc template.

### To Reproduce
1. Run it.
2. See the debug log coming from the GrpcServiceBinder

### Expected behavior
No debug logs get printed.

### Screenshots
![image](https://user-images.githubusercontent.com/95136/56187995-2bddaa00-5fd9-11e9-9d1d-2dd09da7a67c.png)

This is happening because by default the templates turn on debug logs for everythnig except Microsoft and System, the GRPC template needs to add one for GRPC as well.

```JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```

cc @JamesNK @JunTaoLuo @shirhatti

**Comment by JamesNK** [comment]
IT'S FIXED @Eilon
