### ISSUE TITLE
Bind collection of custom types from Jquery.params formatted query string

### ISSUE THREAD

**Issue by achobanov** [aspnet/AspNetCore#9415]
#### Disclaimer 
Created as bug, because I found this [issue](https://github.com/aspnet/Mvc/issues/6372) in **MVC5** and my problem seems to be solved there. 

### Issue description
API model binder does not bind collection from the following query value:
```js
collection[0][propertyName] = value
collection[0][propertyName2] = value2
collection[1][propertyName] = value
```
It works for:
```js
collection[0].propertyName = value
```
The query comes from Jqx widget lib, using `JQuery.params`.

### To Reproduce
1. Using this version of ASP.NET Core '2.2.0'

### Expected behavior
It should map to following property
```c#
class Model {
    IEnumerable<CustomType> Collection { get; set; }
}
```
with the appropriate values.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/6106. See https://github.com/aspnet/AspNetCore/issues/6106#issuecomment-458359368 for the resolution.
