### ISSUE TITLE
 Localized resources from Razor component library not working in Blazor project

### ISSUE THREAD

**Issue by gustavnavar** [aspnet/AspNetCore#9417]
Strings from resources files (.resx) in a component library are not localized correctly when used by a Blazor project. 

But they are ok when used by a Razor component project.

You can download the attached solution (WebApplication.zip) to reproduce this issue:
1. Run the "Blazor.Server" project
2. Go to /fetchdata page. The page content should be translated to Spanish
3. On the other side, if you run the "RazorComponent" project, the /fetchdata page is correctly translated to Spanish

[WebApplication.zip](https://github.com/aspnet/AspNetCore/files/3085415/WebApplication.zip)
![Blazor Client](https://user-images.githubusercontent.com/30131949/56219400-f8496100-6066-11e9-9b10-470eb6800acc.png)
![RazorComponent](https://user-images.githubusercontent.com/30131949/56219424-039c8c80-6067-11e9-9a27-cc760a22062c.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gustavnavar.
This will be addressed as part of https://github.com/aspnet/AspNetCore/issues/5471.
