### ISSUE TITLE
Run templates tests on all the platforms

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#9420]
We've identified issues where some templates don't run on MacOS. To avoid issues like this in the future we should enable the Templates tests to run on all the OSes our Test infrastructure supports.

**Comment by jkotalik** [comment]
I thought template tests ran on MacOS and Linux already? Anyways, isn't there a difference between how we test our templates and what we actually produce as part of the sdk? Wouldn't the only way to get proper verification is to manually/automatically test the sdk for dotnet new scenarios?

**Comment by mkArtakMSFT** [comment]
We do have a manual verification in place (CTI handles this most of the time and we do once per release type of activities near the end of the milestone). However, the manual tests aren't ideal as timing is a big factor for those. The idea here is to avail of the test infrastructure as much as we can in an automated way.

**Comment by ryanbrandenburg** [comment]
Yeah, it turns out that the `dotnet new|restore|build` scenarios are already tested on Linux and Mac, so it's unclear to me how we would have gotten into this state. What was the specific failure scenario that prompted this?

**Comment by mkArtakMSFT** [comment]
I believe we ended up doing something about this already.
