### ISSUE TITLE
Calling InvokeMethod in server-side blazor

### ISSUE THREAD

**Issue by Stamo-Gochev** [aspnet/AspNetCore#9423]
Is there a way to support synchronous calls in server-side blazor using `InvokeMethod` rather than `InvokeMethodAsync`? 

Right now, there is a check for that:
https://github.com/dotnet/jsinterop/blob/a1042e35240662ee54e4cc49c4913541177be803/src/Microsoft.JSInterop.JS/src/Microsoft.JSInterop.ts#L65
which explains that this is not currently supported. Can you shed some light if this can be changed and why it isn't supported?

The issue I am facing is that I want to make a synchronous interop call  (using `InvokeMethod`) from a JavaScript code, which cannot be modified to be asynchronous (let's say I have no control over this, thus the limitation to simply modify it). I cannot just use a client-side blazor application, because I need to support both client and server-side scenarios, which requires `InvokeMethodAsync` only. 

Is there an alternative that you can suggest?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Stamo-Gochev.
@SteveSandersonMS can you please answer this? Thanks!

**Comment by SteveSandersonMS** [comment]
Sorry, no. JavaScript simply does not support blocking the thread until some network call completes (because it's a single-threaded environment). For server-side Blazor, JS interop is a network call.

This is a fundamental limitation of JavaScript.
