### ISSUE TITLE
Blazor/Razor Components docs links are broken

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#9426]
Hi Team;

As of last night all MSFT Docs links pointing to Blazor or Razor components are broken

https://docs.microsoft.com/en-us/aspnet/core/razor-components/

![Docs](https://user-images.githubusercontent.com/7861196/56230188-c675d180-6049-11e9-88e9-e9f6a124c509.png)

**Comment by Andrzej-W** [comment]
Razor Components are renamed back to Blazor. Doc is now here:
https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0
