### ISSUE TITLE
H2 perf regression

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#9445]
Significant regression that matches a runtime update. ~~And it happens that there were some changes on the http2 stack: https://github.com/dotnet/corefx/commit/d6e36e4ecb0d004de54eb7bdf0ed6cdcb042e3c9~~

I will do some measurement to be sure it's due to this change.

~~/cc @rmkerr~~

**Comment by sebastienros** [comment]
![image](https://user-images.githubusercontent.com/1165805/56248836-8240fc00-605e-11e9-9fb6-9bb601c36376.png)

**Comment by sebastienros** [comment]
Might also be fixed by https://github.com/dotnet/coreclr/pull/24045

**Comment by Tratcher** [comment]
Does this test cover the .NET client, server, or both?

**Comment by sebastienros** [comment]
Server only, load is generated by h2load.
I have applied the fix I mentioned but the perf didn't recover fully. I will now try by switching System.Net.Http before and after the change to verify my assumptions.

**Comment by Tratcher** [comment]
The client and server implementations are completely independent. Kestrel should not be affected by the linked commits.

**Comment by sebastienros** [comment]
Didn't see it was client only, but that makes sense, thanks, I will wait for the new runtime to get in then.

**Comment by sebastienros** [comment]
Also it doesn't repro on windows, so most probably related to dotnet/coreclr#24045 which is already merged.

**Comment by sebastienros** [comment]
I verified that this is now fixed. However this test doesn't run anymore for another reason I am looking into.
