### ISSUE TITLE
Issue while running restore file due to MAX_PATH

### ISSUE THREAD

**Issue by jai00271** [aspnet/AspNetCore#9450]
### Describe the bug
Getting error while running restore file via **.\restore.cmd** command

### Expected behavior
Should able to setup core in local

### Additional context
getting below error:

Run C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\eng\scripts\InstallVisualStudio.ps1 to install Visual Studio prerequisites.

Could not find an installation of MSBuild which satisfies the requirements specified in korebuild.json.
At C:\Users\Name\source\repos\AspNetCore\.dotnet\buildtools\korebuild\3.0.0-build-20190412.2\s
cripts\KoreBuild.psm1:524 char:5
+     throw 'Could not find an installation of MSBuild which satisfies  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...korebuild.json.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find an installation of MSBuild which satisfies the requirements specified in
   korebuild.json.

**Comment by jai00271** [comment]
After running the Installation file while loading the solution I get below error:

Detailed Information:
Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.

![image](https://user-images.githubusercontent.com/26379288/56257746-eb6e5100-60ea-11e9-810a-05b226247f9f.png)

**Comment by jai00271** [comment]
Also in command prompt, I get below error:

C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore>.\restore.cmd
Using KoreBuild 3.0.0-build-20190412.2
WARNING: dotnet found on the system PATH is 'C:\Program Files\dotnet\dotnet.exe' but KoreBuild will use 'C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\.dotnet\x64\dotnet.exe'.
WARNING: Adding 'C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\.dotnet\x64' to system PATH permanently may be required for applications like Visual Studio or VS Code to work
correctly.
Adding C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\.dotnet\x64 to PATH
.NET Core SDK 3.0.100-preview4-011136 is already installed. Skipping installation.
Detected Visual Studio Enterprise 2019 (16.0.28803.156) in 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
>>> msbuild.exe C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\build\tasks\RepoTasks.csproj -v:m -restore -t:Publish -p:Configuration=Release -p:PublishDir=C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\build\tasks\bin\publish -nologo -p:RepoTasksSdkPath=C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\.dotnet\buildtools\korebuild\3.0.0-build-20190412.2\scripts\..\msbuild\KoreBuild.RepoTasks.Sdk\Sdk /p:BuildAllProjects=true /p:_RunBuild=False /p:_RunPack=False /p:_RunTests=False /p:_RunSign=False /p:TargetArchitecture=x64 /p:TargetOsName=win @C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\artifacts\logs\msbuild.logger.rsp
  Restore completed in 67.7 ms for C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\build\tasks\RepoTasks.csproj.
C:\Users\mritunjai_pratapsing\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-18618-05\build\Microsoft.Build.Tasks.Git.targets(36,5): warning : Submodule 'googletest' doesn't have any commit,
the source code won't be available via source link. [C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\build\tasks\RepoTasks.csproj]
C:\Users\mritunjai_pratapsing\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-18618-05\build\Microsoft.Build.Tasks.Git.targets(36,5): warning : Submodule 'src/submodules/MessagePack-CSharp' do
esn't have any commit, the source code won't be available via source link. [C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\build\tasks\RepoTasks.csproj]
  RepoTasks -> C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\build\tasks\bin\Release\net472\RepoTasks.dll
  RepoTasks -> C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\build\tasks\bin\publish\

Build succeeded.

C:\Users\mritunjai_pratapsing\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-18618-05\build\Microsoft.Build.Tasks.Git.targets(36,5): warning : Submodule 'googletest' doesn't have any commit,
the source code won't be available via source link. [C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\build\tasks\RepoTasks.csproj]
C:\Users\mritunjai_pratapsing\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-18618-05\build\Microsoft.Build.Tasks.Git.targets(36,5): warning : Submodule 'src/submodules/MessagePack-CSharp' do
esn't have any commit, the source code won't be available via source link. [C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\build\tasks\RepoTasks.csproj]
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.48
>>> msbuild.exe @C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\artifacts\logs\msbuild.rsp @C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\artifacts\logs\msbuild.logger.rsp
Microsoft (R) Build Engine version 16.0.461+g6ff56ef63c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\.dotnet\x64\sdk\3.0.100-preview4-011136\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(235,13): error MSB4248: C
annot expand metadata in expression "$([MSBuild]::ValueOrDefault('%(FullPath)', '').StartsWith($([MSBuild]::EnsureTrailingSlash($(MSBuildProjectDirectory)))))". The item metadata "%(FullPath)" canno
t be applied to the path "TestFiles\ApiActionsDoNotRequireExplicitModelValidationCheckAnalyzerIntegrationTest\NoDiagnosticsAreReturned_ForApiActionsReturning400FromNonModelStateIsValidBlocks.cs". Pa
th: C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\src\Mvc\Mvc.Api.Analyzers\test\TestFiles\ApiActionsDoNotRequireExplicitModelValidationCheckAnalyzerIntegrationTest\NoDiagnosticsAre
Returned_ForApiActionsReturning400FromNonModelStateIsValidBlocks.cs exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\Users\mritunjai_pratapsing\sour
ce\repos\Learning\AspNetCore\src\Mvc\Mvc.Api.Analyzers\test\Mvc.Api.Analyzers.Test.csproj]

Build FAILED.

C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\.dotnet\x64\sdk\3.0.100-preview4-011136\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(235,13): error MSB4248: C
annot expand metadata in expression "$([MSBuild]::ValueOrDefault('%(FullPath)', '').StartsWith($([MSBuild]::EnsureTrailingSlash($(MSBuildProjectDirectory)))))". The item metadata "%(FullPath)" canno
t be applied to the path "TestFiles\ApiActionsDoNotRequireExplicitModelValidationCheckAnalyzerIntegrationTest\NoDiagnosticsAreReturned_ForApiActionsReturning400FromNonModelStateIsValidBlocks.cs". Pa
th: C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\src\Mvc\Mvc.Api.Analyzers\test\TestFiles\ApiActionsDoNotRequireExplicitModelValidationCheckAnalyzerIntegrationTest\NoDiagnosticsAre
Returned_ForApiActionsReturning400FromNonModelStateIsValidBlocks.cs exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\Users\mritunjai_pratapsing\sour
ce\repos\Learning\AspNetCore\src\Mvc\Mvc.Api.Analyzers\test\Mvc.Api.Analyzers.Test.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:52.05
msbuild.exe failed with exit code: 1
At C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\.dotnet\buildtools\korebuild\3.0.0-build-20190412.2\scripts\common.psm1:11 char:9
+         throw "$cmdName failed with exit code: $exitCode"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (msbuild.exe failed with exit code: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : msbuild.exe failed with exit code: 1

**Comment by natemcmaster** [comment]
> exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.

Try moving your source code into a shorter prefix. "C:\Users\mritunjai_pratapsing\source\repos\Learning\AspNetCore\" is too long. Most developers on our team use something like "C:\source\AspNetCore" instead.

**Comment by natemcmaster** [comment]
_Build Team Triage:_ closing as there is no action item pending here. See previous comment for recommendation on working around git + Windows max_path limitations.

**Comment by danrien** [comment]
Is it unreasonable to expect that a modern runtime understands path lengths beyond 260 characters? Windows Explorer doesn't seem blocked by this issue, the `max_path` constant as far as I understand it is for compatibility these days.
