### ISSUE TITLE
blazor not start with vscode

### ISSUE THREAD

**Issue by mammadkoma** [aspnet/AspNetCore#9451]
Hi
I have vscode 1.33.1 & C# extension 1.19.0 and dotnetcore 3.0.100-preview3-010431
I created a blazor project named Blazorr and build it.
But when I open project with vscode and start (F5) , it give us error :
**A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'E:\Projects\Blazorr\bin\Debug\netstandard2.0\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the E:\Projects\Blazorr\bin\Debug\netstandard2.0\Blazorr.runtimeconfig.json file specifying the appropriate framework.
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[9964] Blazorr.dll' has exited with code -2147450749 (0x80008083).**
![image](https://user-images.githubusercontent.com/17564001/56265782-be786900-60ff-11e9-9849-bcec22f4fa7a.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mammadkoma.
@NTaylorMullen can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@mammadkoma you would probably get a faster response on `StackOverflow`.

**Comment by dharmaturtle** [comment]
@mammadkoma this may be helpful: https://stackoverflow.com/questions/38085430/the-library-hostpolicy-dll-was-not-found

**Comment by mammadkoma** [comment]
Where is buildOptions and emitEntryPoint in my project? I can not find them.

**Comment by mammadkoma** [comment]
New dotnetcore and blazor versions released but problems exists.

**Comment by NTaylorMullen** [comment]
@mammadkoma are you able to run Blazor outside of VSCode? Aka dotnet run?

**Comment by mammadkoma** [comment]
Yes _dotnet run_ command works successfully.

**Comment by mammadkoma** [comment]
I tested in both my labtop and my work pc and blazor template project not create correct launch file and don't start and get errors:

**1. A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'E:\Projects\Blazorr\bin\Debug\netstandard2.0'.Failed to run as a self-contained app. If this should be a framework-dependent app, add the E:\Projects\Blazorr\bin\Debug\netstandard2.0\Blazorr.runtimeconfig.json file specifying the appropriate framework.The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.The program '[9964] Blazorr.dll' has exited with code -2147450749 (0x80008083). 
2. The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) (CS0246) [Blazor]**

**Comment by NTaylorMullen** [comment]
Thanks @mammadkom, I can reproduce your issue. I'll look into it more.

**Comment by NTaylorMullen** [comment]
@SteveSandersonMS this issue looks to be due to how VSCode boots a .NET Core app. It essentially does `dotnet bin/path/to/debug/TheTFM/SomeBlazorApp.dll`. I'm not sure what Blazor adds to the `dotnet run` pipeline but it looks like that's required in order to run the application. Is this something that's fixable on our side? If not, we'll need to make changes on the O# side to make F5 work in VSCode.

@mammadkoma if you want to semi-workaround your issue for now you can change your `launch.json`'s program/args section to be:
```
            "program": "dotnet",
            "args": ["run", "${workspaceFolder}/bin/Debug/netstandard2.0/Preview4Blazor.dll", "--no-build" ],
```

**Comment by pranavkm** [comment]
Would this need to use the blazor dev server?

**Comment by mammadkoma** [comment]
> @SteveSandersonMS this issue looks to be due to how VSCode boots a .NET Core app. It essentially does `dotnet bin/path/to/debug/TheTFM/SomeBlazorApp.dll`. I'm not sure what Blazor adds to the `dotnet run` pipeline but it looks like that's required in order to run the application. Is this something that's fixable on our side? If not, we'll need to make changes on the O# side to make F5 work in VSCode.
> 
> @mammadkoma if you want to semi-workaround your issue for now you can change your `launch.json`'s program/args section to be:
> 
> ```
>             "program": "dotnet",
>             "args": ["run", "${workspaceFolder}/bin/Debug/netstandard2.0/Preview4Blazor.dll", "--no-build" ],
> ```

Thank you
program & args options worked and F5 starts project in my browser.

                  "program":"dotnet",
                  "args": [
                        "run",
                        "${workspaceFolder}/bin/Debug/netstandard2.0/Blazorr.dll",
                        "--no-build"
                  ]

**Comment by SteveSandersonMS** [comment]
@NTaylorMullen It's what @pranavkm said - to launch a Blazor standalone app, you have to use the Blazor dev server (because there's nothing else to act as the server - your app code is purely what runs in the browser, and is not the web server itself).

The `Microsoft.AspNetCore.Blazor.DevServer` package includes MSBuild props that modify the behavior of `dotnet run` so that it launches the dev server. I don't know why VS code doesn't launch .NET apps by running `dotnet run` (since that's the standard).

**Comment by NTaylorMullen** [comment]
Gotcha, alright going to log an issue over on the omnisharp-vscode side of the world to properly detect Blazor apps and "do the right thing" when generating assets to run a .NET Core app that happens to be Blazor.

**Comment by NTaylorMullen** [comment]
Given that this is external going to track the resolution of this work here: https://github.com/OmniSharp/omnisharp-vscode/issues/3024
