### ISSUE TITLE
"No server certificate was specified" - despite developer HTTPS cert existing

### ISSUE THREAD

**Issue by olitomlinson** [aspnet/AspNetCore#9453]
### Describe the bug
Trying to use the default ASP.NET Core HTTPS Development Certificate to set up Kestrel WebServer (in a Service Fabric project) to debug locally.

```
.ConfigureKestrel((context,options) =>
{
    int port = serviceContext.CodePackageActivationContext.GetEndpoint("ServiceEndpoint").Port;
    options.Listen(IPAddress.IPv6Any, port, listenOptions =>
    {
        listenOptions.UseHttps();
    });
})
```

Even though the Cert is installed with `dotnet dev-certs https --trust`

I still get the error :

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
  Source=Microsoft.AspNetCore.Server.Kestrel.Core
  StackTrace:
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Management.Api.Api.<>c.<CreateServiceInstanceListeners>b__1_5(ListenOptions listenOptions) in C:\dev\webhookGuru\Management.Api\Api.cs:line 59
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPEndPoint endPoint, Action`1 configure)
   at Management.Api.Api.<>c__DisplayClass1_0.<CreateServiceInstanceListeners>b__4(WebHostBuilderContext context, KestrelServerOptions options) in C:\dev\webhookGuru\Management.Api\Api.cs:line 56
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
```

I've tried clearing all the certificates manually from the Current User - Personal and Current User -Trusted RCA store, and recreating them.

### Additional context
Visual Studio 2019
.Net Core 2.2.4 (SDK 2.2.203)
Service Fabric Runtime 6.3.654.9590
Service Fabric SDK 3.3.654.9590

**Comment by masterjs** [comment]
@olitomlinson , someone will likely confirm it soon, but my understanding of the `dev-certs` is that its only for `IIS Express` (and `IIS` if you want), not `Kestrel`

**Comment by olitomlinson** [comment]
@masterjs thanks! 

I've done some reading around, and interestingly I can't find any evidence to support or deny what you're saying. 

I would have at least hoped for a note in the documentation to say that this is incompatible with Kestrel?

**Comment by masterjs** [comment]
You're right, It shouldn't be an issue.
Just saw this nice post: https://devblogs.microsoft.com/aspnet/asp-net-core-2-1-https-improvements/

**Comment by Tratcher** [comment]
The dev cert is explicitly for Kestrel.

Do service fabric projects have special dev environments? e.g. emulators, containers, etc??

**Comment by olitomlinson** [comment]
@Tratcher Good question which prompted me to do some reading and I found this. 

Looks like its not that simple to get HTTPS running locally in Service Fabric due to (NETWORK SERVICE needing to access the certificates private key)[https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint#give-network-service-access-to-the-certificates-private-key] in Service Fabric.
