### ISSUE TITLE
Question:  How to get WebHost Start Uri when using the generic IHost?

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/AspNetCore#9455]
I am updating my E2E tests in blazor-state and my test application now uses the new Generic IHost in Program.cs

In my ServerFixture I was doing StartAndGetRootUri just like @SteveSandersonMS [code](https://github.com/aspnet/AspNetCore/blame/5a70f5312fb57fc3788e5af56a99e7b43761e195/src/Components/test/E2ETest/Infrastructure/ServerFixtures/WebHostServerFixture.cs).

```
protected override string StartAndGetRootUri()
        {
            _host = CreateWebHost();
            RunInBackgroundThread(_host.Start);
            return _host.ServerFeatures
                .Get<IServerAddressesFeature>()
                .Addresses.Single();
        }
```

With the new IHost I don't have ServerFeatures,  So I am wondering how do we get the Addresss information from IHost?

If you update your [DevHostServer](https://github.com/aspnet/AspNetCore/blob/5a70f5312fb57fc3788e5af56a99e7b43761e195/src/Components/Blazor/Cli/src/Server/Program.cs)  You will be in the same boat.

I searched and couldn't figure out so asked where I thought it would be most helpful.

Thanks!

**Comment by davidfowl** [comment]
```C#
protected override string StartAndGetRootUri()
{
    _host = CreateWebHost();
    RunInBackgroundThread(_host.Start);
    return _host.Services.GetRequiredService<IServer>().Features
        .Get<IServerAddressesFeature>()
        .Addresses.Single();
}
```

**Comment by StevenTCramer** [comment]
@davidfowl Thanks I knew you guys would know.   Now I guess I can do a PR to update your tests?

**Comment by anurse** [comment]
You mean to update the tests to use `Host` instead of `WebHost`? Sure, I think that would be OK.

**Comment by davidfowl** [comment]
It might be very hard but give it a shot.

cc @natemcmaster
