### ISSUE TITLE
Multiple web hosts

### ISSUE THREAD

**Issue by Diaskhan** [aspnet/AspNetCore#9470]
Is there possible to implement few webhosts? 

For example 
1.host of main application (port 80)
2. Adm console that could reload first host ! (Port 8080) need full reload of first host because runtime assemblyes has changed !

If there is possible could give link for documentation ?

**Comment by Tratcher** [comment]
It's fully supported for the self-host scenario (not IIS). There's no specific doc, you just create two webhosts and give them different config.

**Comment by Tratcher** [comment]
Note for the reload you'd need to recycle the whole process. See IApplicationLifetime.StopApplication.

**Comment by RaulSebastian** [comment]
Should be closed, as not an issue.

**Comment by Diaskhan** [comment]
How then shutdown host ?

**Comment by Tratcher** [comment]
That's what IApplicationLifetime.StopApplication is for. 

I suggest moving this question to a community forum like stackoverflow.
