### ISSUE TITLE
Microsoft.AspNetCore.SignalR.Client for .net45x

### ISSUE THREAD

**Issue by generik0** [aspnet/AspNetCore#9472]
Hi

Thanks for the great work on aspnetcore, and in this case the aspnetcore signalr

I have seen this question asked other places. I just want to make sure.
If we want to migrate our "old" Microsoft.AspNet.SignalR self hosted to Microsoft.AspNetCore.SignalR.
But we still have som clients we cannot migrate to net461+ than this is a no go?

I.e. there in no net452 signalr client that can connect to Microsoft.AspNetCore.SignalR host?
Atleast a Microsoft.AspNet.SignalR.Client does not appear to be able to connect to a Microsoft.AspNetCore.SignalR host.

Since there is a java, TS, and netstandard client. shouldn't there really be a net40 / net452 client?

Any thoughs please?

**Comment by generik0** [comment]
releated=? https://github.com/aspnet/SignalR/issues/1484

**Comment by mikaelm12** [comment]
>  there in no net452 signalr client that can connect to Microsoft.AspNetCore.SignalR host?

That is correct. The points in the issue you linked (https://github.com/aspnet/SignalR/issues/1484) still hold true. We don't plan on supporting anything below NET Standard 2.0

**Comment by generik0** [comment]
@mikaelm thanks for the fast answer.
To be honest I think you guys are shooting yourself in the foot, not allowing “legacy” applications to connnect eg a new aspnetcore SignalR Microservices...
At least for a while yet...


It isn’t always a case of just changing an application to run net461+.
Sometimes when you do this and have installed net framework packages and net standard packages the build stops working, and the apps get confused as to which system dependancies it should use. Then you need a mass dependence mappings in the app.config (auto doesn’t always work).l and even this doesn’t always help.

We also have old xamavarin apps, that can also not use a combination of the two types of framework...

Also, While Win7 and Win8 is still in support, we also have industrial customers that run a “default” validates OS.

Hence the long life of net452...

Just thoughts... I feel a net452 client is missing.
