### ISSUE TITLE
Create an RPS EventCounter

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#9486]
Let's add an RPS EventCounter in ASP.NET for use with the [dotnet-counters](https://github.com/dotnet/diagnostics/tree/master/src/Tools/dotnet-counters) tool.

Previous attempt at adding EventCounters to Hosting- https://github.com/aspnet/Hosting/pull/886

Relevant docs
- https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestEventCounter.cs
- https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/documentation/EventCounterTutorial.md

**Comment by shirhatti** [comment]
@davidfowl I'm assuming just RPS to start with, unless you had something else in mind?

**Comment by shirhatti** [comment]
As an example, we already have [EventCounters in SignalR](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionsEventSource.cs)

**Comment by shirhatti** [comment]
@anurse Can we get a milestone for this?

**Comment by davidfowl** [comment]
I'm going to do this in preview6

**Comment by davidfowl** [comment]
This is for @anurse:

![image](https://user-images.githubusercontent.com/95136/59003405-a43b3d00-87ca-11e9-92a5-c247958d9a3a.png)

![image](https://user-images.githubusercontent.com/95136/59003413-adc4a500-87ca-11e9-9d5a-28020806dba3.png)

**Comment by anurse** [comment]
![image](https://www.bing.com/th?id=OGC.66282c4d998c402196dddfea0b18769a&pid=1.7&rurl=https%3a%2f%2fmedia.giphy.com%2fmedia%2fA1etPWqtba6je%2fgiphy.gif&ehk=kIEAZ8MLNt%2bXOFFJ3Hidpg)
