### ISSUE TITLE
Blazor , RenderFragment to Raw Html string

### ISSUE THREAD

**Issue by moataz1991** [aspnet/AspNetCore#9493]
as the question title says
can you add the ability to get raw html from RenderFragment?
maybe something like this
`RenderFragment renderFragment;
renderFragment.ToRawHtml()`
or `property `saving the rawHtml generated by the `renderFragment `object ?
with events and everything...
for code-behind purposes
**Thanks**

**Comment by SteveSandersonMS** [comment]
This isn’t a feature we’re currently planning to have. It would involve having a new way of turning render trees into strings. Bear in mind that render output is *not* a string for Blazor - it’s a structured tree of elements and attributes. 

If this becomes a highly requested feature we’d certainly consider adding infrastructure for this, but if not then we have more highly prioritised things to work on. Hope that makes sense. 

Also in general it’s hard to see what the use cases would be for this.

**Comment by moataz1991** [comment]
@SteveSandersonMS  most use cases when dynamically building view with integration with 3rd party JS libraries , when u simply want to send raw HTML to be inserted as a popup for a marker in map library ;)

thanks

**Comment by BrainSlugs83** [comment]
Because you might want to inspect the contents of a render fragment.  I think as Blazor gets more attention, this is going to be a feature people want...  Can you at least document how the `RenderTreeBuilder` works so that we can create one that renders the fragment to a string?
