### ISSUE TITLE
DirectoryBrowser not showing or downloading .exe files

### ISSUE THREAD

**Issue by malichishti** [aspnet/AspNetCore#9494]
### Describe the bug
I'm using Directory Browser and StaticFiles as per the code below:

### To Reproduce
```
app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = new PhysicalFileProvider(
                    Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "downloads", "MyFiles")),
                RequestPath = "/MyFiles"
            });

            app.UseDirectoryBrowser(new DirectoryBrowserOptions
            {
                FileProvider = new PhysicalFileProvider(
                    Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "downloads", "MyFiles")),
                RequestPath = "/MyFiles"
            });

```

### Expected behavior
I have noticed for some users certain files dont show up in the directory the file in question is a zip file roughly 200mb in size. 
The bigger issue however right now is that it is unable to show or download *.exe files

Regards,
Ali

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.2#fileextensioncontenttypeprovider
`.exe` isn't on the default list.
https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs
