### ISSUE TITLE
Is it possible to have Windows Authentication AND Individual User Accounts (Anonymous Authentication) in 2.2?

### ISSUE THREAD

**Issue by kevingates** [aspnet/AspNetCore#9498]
### Is your feature request related to a problem? Please describe.
We are wanting to build multiple web apps, and furthermore, we're wanting to create a Single Sign-On app so that it's easy for our employees to use.

Most of our apps will be used only internally, therefore Windows Authentication would be the easiest. However, certain apps over time (or initially) will need to allow outside users.

In `launchSettings.json`, we have this:
```
"iisSettings": {
    "windowsAuthentication": true, 
    "anonymousAuthentication": true, 
    "iisExpress": {
      "applicationUrl": "http://localhost:3833",
      "sslPort": 44375
    }
```
If you have Windows Auth as **true**, and anonymous as **false**, then in the code, `User.Identity.Name` shows the user logged in.

However, as soon as you enable **anonymousAuthentication** (i.e.: set to *true*), then it never sees the logged in Windows User anymore.

I cannot find documentation anywhere.

### Describe the solution you'd like
Presuming I can enable both, I would like essentially to do the following:

Be able to write a conditional statement. On load of the app:
(Pseudo code):
```
IF User.Identity.Name is not null or empty (so Windows Authenticated)
THEN do something (in my case I want to send a bearer authentication token via httpOnly cookie).
ELSE provide a login form (in my case, this must be an External User, and I want them log in with Username + Password)
```

### Describe alternatives you've considered
Option 1: Create 2 Different Apps. One for Windows Auth, One for Anonymous Auth

Option 2: Use a Third Party Authentication app. But this costs money.

### Additional context
Personally, I'm relatively new to C# and .Net world. Started about 6 months ago. Now, I've learned a lot but if you provide solutions, can you use the K.I.S.S. principle? That is: "Keep It Stupid Simple". Can you give specific steps such as "Go to your Startup.cs file, within your Configure method and add ______ just below `app.UseCookiePolicy()`, and paste this: ____, etc.

Many thanks!

**Comment by kevingates** [comment]
@blowdart : I saw you comment on another security / Identity question. Would you be able to give me some wisdom on this?

Please pardon my ignorance if I'm missing something obvious.

**Comment by blowdart** [comment]
Not easily, and not in a supported way. You could, if you knew the IP addresses of the intranet, attempt to trigger Windows auth on those requests, but that seems rather unsafe.

Third party auth doesn't have to cost, you may be able to do it with identity server, by taking the approach above. I'd ask them.

**Comment by brockallen** [comment]
IdentityServer might be a good candidate for this. Our templates have both password and windows auth.

**Comment by kevingates** [comment]
@brockallen yeah, we're working for a County Government, with occasional outside users. So Windows Auth or WS-Federation (which you do) should work.

@brockallen : Do you have a recommended resource for a novice when it comes to security? Our team has had historically more windows-based apps, or web apps needing just windows auth OR external only. I've only been here for 5-6 months and my background was mostly on front-end work.

I've seen the Identity Server docs. Portions are straight-forward, but some guides have some missing steps (again, probably because I'm pretty new to security so maybe it's crystal clear for advanced C# users).

But if there is a great course, video, guide for understanding and implementing Identity Server enough so I can teach the fringe stuff myself, I'd be very appreciative. Getting to the point of knowing enough to know what to Google is a good milestone, so I'm just trying to get there.  :) 

Once more, @blowdart and @brockallen , I'm very grateful for both of your fast and kind responses. I had been attempting this for hours my way (which I now know was an exercise in futility). Much obliged!

**Comment by Tratcher** [comment]
> However, as soon as you enable anonymousAuthentication (i.e.: set to true), then it never sees the logged in Windows User anymore.

Once you allow anonymous then you have to specify which actions require authentication, and what type. That usually involves `[Authorize]` on controllers and either specifying the type on the attribute or via `AddAuthentication` like this:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=visual-studio#iis

How do you choose between requesting windows auth or WsFed for a given anonymous request?

**Comment by brockallen** [comment]
> How do you choose between requesting windows auth or WsFed for a given anonymous request?

That's the classic HRD (home realm discovery) problem.

**Comment by kevingates** [comment]
@Tratcher : I may be coming at this the wrong way.

My ultimate goal is to address the security issue that takes into consideration:

1. Growing number of web apps.
2. Most users are employees and in our network
3. Occasional need for out-of-network users
4. Desire to limit the amount of logins the users need, so a Single-Sign-On solution is an option.

With that, I was thinking of creating an app that serve as a way of asking:

- Are you Windows Authenticated? Yes? Send back token for authentication.
- No WA? Okay, are sign in with Username and Password. Passed? Send back token for authentication.
- Neither? Reject.

So I'm just learning a lot and trying to figure out the best way. :)

**Comment by Tratcher** [comment]
You're missing a step. All requests start as anonymous, even if windows auth is possible. At that point you need to be able to make a determination if that request should attempt windows auth or something else. That's what @brockallen was talking about above https://github.com/aspnet/AspNetCore/issues/9498#issuecomment-484617037.

Worst case you forward all anonymous users to a login page that lets them choose if they want windows auth or wsfed.

**Comment by kevingates** [comment]
@Tratcher : I'm watching this video now on IdentityServer: [IdentityServer for ASP.NET Core 2 - Brock Allen & Dominick Baier
](https://www.youtube.com/watch?v=TZzFPhVkzo4)

I think I see what you're talking about. I guess I just need to re-read some of the Identity Server documentation. Parts of it presume a few steps, so I'm getting lost. 

Feel free to keep the comments / ideas / suggestions coming. Seriously, you all have been super helpful.

**Comment by blowdart** [comment]
Closing due to age, and its discussion based nature.
