### ISSUE TITLE
Username still displayed after logging out from the user profile page in the React template

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#9503]
Repro steps:
- Install .NET Core 3.0 Preview 4
- Create React app for ASP.NET Core
- Build and run
- Register a new user
- Navigate to the user profile page
- Click logout

![goHfhjxnGj](https://user-images.githubusercontent.com/1874516/56372245-7d419100-61b3-11e9-8de1-9d2c5db54577.gif)

**Comment by mkArtakMSFT** [comment]
@javiercn, please work on this when you'll be back from vacation, as we want this to be part of preview5.

**Comment by mkArtakMSFT** [comment]
Seems related https://github.com/aspnet/AspNetCore/issues/9503

**Comment by javiercn** [comment]
@mkArtakMSFT @danroth27  This is by design. 

When you log out from within identity you log out from the IdP but not from the SPA. 

To draw an analogy, you might log-in with Facebook on a third party site, and then when you log out from facebook, you won't be automatically logged-out from the site. This is the same.

**Comment by danroth27** [comment]
OK, I get it, but I think that's going to confuse quite a few folks. The app isn't setup to feel like the identity provider is a third party. It's setup to feel like everything is first party. Given the architecture I'm not sure what is reasonable to do here. @blowdart thoughts on this?

**Comment by javiercn** [comment]
@danroth27 We can override stuff and make it look an feel "identical" at the cost of yet another thing to maintain. (and a new file on the template, the overriden layout).

More generally there are a bunch of features like cookie consent that are not part of the SPA templates. Either you or @blowdart should go through the templates and file bugs with the things that you guys want fixed.

**Comment by blowdart** [comment]
I'm with Dan on this. The IS server in this case isn't a third party, and doesn't need to be treated like one.
