### ISSUE TITLE
Apply API Review feedback to JsonHubProtocolOptions

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#9519]
Specifically, we should review the `JsonHubProtocolOptions` for the new System.Text.Json based protocol.

**Comment by anurse** [comment]
Let's do a brief online API review. @BrennanConroy post the ref assembly code here when you've locked it down. We can probably approve this without a meeting.

**Comment by BrennanConroy** [comment]
Current API

```csharp
namespace Microsoft.AspNetCore.SignalR
{
    public partial class JsonHubProtocolOptions
    {
        public JsonHubProtocolOptions() { }
        public System.Text.Json.Serialization.JsonSerializerOptions PayloadSerializerOptions { [System.Runtime.CompilerServices.CompilerGeneratedAttribute]get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute]set { } }
    }
}
namespace Microsoft.AspNetCore.SignalR.Protocol
{
    public sealed partial class JsonHubProtocol : Microsoft.AspNetCore.SignalR.Protocol.IHubProtocol
    {
        public JsonHubProtocol() { }
        public JsonHubProtocol(Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.SignalR.JsonHubProtocolOptions> options) { }
        public string Name { get { throw null; } }
        public Microsoft.AspNetCore.Connections.TransferFormat TransferFormat { get { throw null; } }
        public int Version { get { throw null; } }
        public System.ReadOnlyMemory<byte> GetMessageBytes(Microsoft.AspNetCore.SignalR.Protocol.HubMessage message) { throw null; }
        public bool IsVersionSupported(int version) { throw null; }
        public bool TryParseMessage(ref System.Buffers.ReadOnlySequence<byte> input, Microsoft.AspNetCore.SignalR.IInvocationBinder binder, out Microsoft.AspNetCore.SignalR.Protocol.HubMessage message) { throw null; }
        public void WriteMessage(Microsoft.AspNetCore.SignalR.Protocol.HubMessage message, System.Buffers.IBufferWriter<byte> output) { }
    }
}
namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class JsonProtocolDependencyInjectionExtensions
    {
        public static TBuilder AddJsonProtocol<TBuilder>(this TBuilder builder) where TBuilder : Microsoft.AspNetCore.SignalR.ISignalRBuilder { throw null; }
        public static TBuilder AddJsonProtocol<TBuilder>(this TBuilder builder, System.Action<Microsoft.AspNetCore.SignalR.JsonHubProtocolOptions> configure) where TBuilder : Microsoft.AspNetCore.SignalR.ISignalRBuilder { throw null; }
    }
}
```

Semi-related to API are our default Json options, currently we have:
```csharp
options.WriteIndented = false;
options.ReadCommentHandling = JsonCommentHandling.Disallow;
options.AllowTrailingCommas = false;
options.IgnoreNullValues = false;
options.IgnoreReadOnlyProperties = false;
options.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
```

There are a couple other settable options right now, do we want to set them or just keep the defaults?:
```
DefaultBufferSize = 16 * 1024;
DictionaryKeyPolicy = null;
MaxDepth = 0; // meaning 64
PropertyNameCaseInsensitive = false;
```

@davidfowl @mikaelm12 @halter73 @anurse

**Comment by anurse** [comment]
All the methods/properties on `JsonHubProtocol` (except the constructors) are just the ones that come from `IHubProtocol` right? So they're not really negotiable anyway :)

Given that, I think we're in a good place. Now that we can just expose the `JsonSerializerOptions` type, we basically have the same API and the Newtonsoft.Json one.

**Comment by halter73** [comment]
`MaxDepth = 0; // meaning 64` Why not just make it 64 then?

**Comment by BrennanConroy** [comment]
Those are the defaults set by `new JsonSerializerOptions();` I'm not setting 0 or 64.

**Comment by anurse** [comment]
Are we all good with this design? I don't think this needs an in-person review if everyone is on board.

**Comment by halter73** [comment]
I don't know too much about the requirements, but it seems reasonable.

**Comment by anurse** [comment]
Two action items:

1. Set all the defaults explicitly, including `MaxDepth = 64`
1. Set `PropertyNameCaseInsensitive` to `true`

**Comment by BrennanConroy** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [x] Relevant XML documentation comments for new public APIs are present.
    * [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
        * [x] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: [3.0.100-preview6-012096]
            * ASP.NET Core Runtime: [3.0.0-preview6-19277-03]
            * .NET Core Runtime: [3.0.0-preview6-27727-02]
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
