### ISSUE TITLE
GRPC benchmark is broken

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#9524]
Since https://github.com/grpc/grpc-dotnet/commit/77b3ba3fb8eb5cc20ff2f39af727a15e176dd0d7

```
-j https://raw.githubusercontent.com/grpc/grpc-dotnet/master/perf/benchmarkapps/BenchmarkServer/grpc-aspnetcore.json -n GrpcUnaryAspNetCore --webHost KestrelSockets --connections 128 --warmup 1 --duration 5 --hash 77b3ba3fb8eb5cc20ff2f39af727a15e176dd0d7
```

**Comment by sebastienros** [comment]
We still have a problem

```
Grpc.AspNetCore.Server -> /tmp/BenchmarksServer/g5ncw113.mbj/grpc-dotnet/src/Grpc.AspNetCore.Server/bin/Release/netcoreapp3.0/Grpc.AspNetCore.Server.dll
Startup.cs(27,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) [/tmp/BenchmarksServer/g5ncw113.mbj/grpc-dotnet/perf/benchmarkapps/BenchmarkServer/BenchmarkServer.csproj]
```

**Comment by JamesNK** [comment]
gRPC has recently been updated to a newer version of .NET Core 3.0, and an explicit Newtonsoft.Json was added.

Is the benchmark still failing with the same error?

**Comment by sebastienros** [comment]
Benchmarks were broken due to DHCP issues. They are back and I will check. But it could definitely be broken by the new nuget feeds. Can you check what I did in my latest pr on this repos?

**Comment by JamesNK** [comment]
The results show that numbers are being gathered from lin-sockets. win-sockets is returning a constant zero.

![image](https://user-images.githubusercontent.com/303201/57272738-0d0a9900-70e9-11e9-8907-f711f76a72aa.png)

**Comment by sebastienros** [comment]
Both managed and native scenarios fail on windows only.

**Comment by sebastienros** [comment]
So the issue is on Windows only. Could it be because IIS is broken there, is it using it?

**Comment by JamesNK** [comment]
gRPC should be using Kestrel.
