### ISSUE TITLE
Run helix tests on arm queues

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#9526]
Need to update the helix scripts to enable this properly as there are x64 things hardcoded today

PR working on this https://github.com/aspnet/AspNetCore/pull/8844

**Comment by natemcmaster** [comment]
cc @JunTaoLuo looks like a duplicate of issues I just pinged you on in aspnet/AspNetCore-Internal.

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/AspNetCore/pull/11422
