### ISSUE TITLE
Developer Certificate file names don't match up between Visual Studio and Kestrel

### ISSUE THREAD

**Issue by jcoutch** [aspnet/AspNetCore#9528]
### Describe the bug
When attempting to run a Docker container locally with an ASP.NET Core web site using HTTPS, under certain circumstances, developers will see the following error message when starting the site:

```
Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
```

I was able to track down the issue to `KestrelConfigurationLoader.TryGetCertificatePath()`:
https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs

TryGetCertificatePath() is using the **application name** to get the path to the certificate.  But, Visual Studio uses the **project name** to create the certificate in `%APPDATA%/ASP.NET/Https`.  So if both names don't match up, `FindDeveloperCertificateFile()` won't be able to find the path that is returned by `TryGetCertificatePath()`, and you get the error message.

### To Reproduce
1. Create a brand new ASP.NET Core site (Web API) named `certificate-error-repro`
2. Right click on the project, go to Properties, and change the Assembly Name and Default Namespace to: `MyFancyAssembly.CertificateErrorRepro`
3. Right click on the project, click Add, and click "Container Orchestration Support"
4. Select Docker Compose, click OK, select Linux, click OK.
5. Run the project.

**For ease of reproduction, I created this project:**
https://github.com/jcoutch/aspnetcore-devcert-repro

### Expected behavior
The development certificate should be generated with the correct name, and the site should start up in the container as expected.

### Workaround
To work around this issue, I re-named my project to match the application name and restarted Visual Studio.  When I started the project, the certificate was generated with the correct name, and Kestrel was able to load it successfully.

**Comment by Tratcher** [comment]
Note this was with 2.2. We'll also want to re-verify this code with the 3.0 generic host as ApplicationName initialization has changed.

The repro breaks because it explicitly override the assembly name:
`<AssemblyName>MyFancyAssembly.CertificateErrorRepro</AssemblyName>`
https://github.com/jcoutch/aspnetcore-devcert-repro/blob/704c5bc4dd660ece0802256e4101491a0eb2a4be/certificate-error-repro/certificate-error-repro.csproj#L7

The fix here is likely in VS as the runtime does not have access to the original project name. VS would have to use the assembly name instead. @BillHiebert is that in your area? Or in one of the SDKs?

**Comment by Tratcher** [comment]
This is being tracked as a visual studio fix. (Private link https://devdiv.visualstudio.com/DevDiv/_workitems/edit/852005). I'm closing this one for now.

Also "as a temporary workaround, you can rename the certificate here %APPDATA%\ASP.NET\Https to match the assembly name."

**Comment by jcoutch** [comment]
@tratcher - Is there someone from the Visual Studio team that can update this ticket as progress is made...so we know what update to expect this fix in?  Thanks!

**Comment by Tratcher** [comment]
I've left them a reminder but it will be a manual process for them. The best way to ensure you get notified is to open an issue via the VS feedback tool, but let them know they can close 852005 as a duplicate.
