### ISSUE TITLE
Pubternal API in ClientHandler

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#9532]
Pubternal API check error:
```
ClientHandler.cs(34,51): error PUB0001: Pubternal type ('Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context') usage in public API [C:\gh\AspNetCore2\src\Hosting\TestHost\src\Microsoft.AspNetCore.TestHost.csproj]
```

**Comment by Tratcher** [comment]
Here:
https://github.com/aspnet/AspNetCore/blob/7669cf0d036cc0cb3b481aba49253cd35d85c633/src/Hosting/TestHost/src/ClientHandler.cs#L34

That constructor could be internal, it's called from here:
https://github.com/aspnet/AspNetCore/blob/7669cf0d036cc0cb3b481aba49253cd35d85c633/src/Hosting/TestHost/src/TestServer.cs#L93-L97

**Comment by anurse** [comment]
Assigning to you @JunTaoLuo since you already opened the PR :).
