### ISSUE TITLE
Session event Provider configuration in session middleware

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/AspNetCore#9536]
### Is your feature request related to a problem? Please describe.
For session in .net core, it is implemented by session and controlled by `SessionOptions`.   

As issues #3331, #3025, https://github.com/aspnet/Session/issues/20, I am wondering it is possible to add event to the session object like start, end or maybe change event.

**Comment by Tratcher** [comment]
We've rejected these at least three times before, what do you have to add to the discussion that hasn't already been covered?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
