### ISSUE TITLE
ssr(serve side render) -> csr(client side render) gradual switch

### ISSUE THREAD

**Issue by juepiezhongren** [aspnet/AspNetCore#9541]
1) ssr is to firstly be launched when browsing starts;
2) if browser supports wasm, all bsr dependencies start downloading and try to cache;
3) after dependencies downloaded, switch into csr mode

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future.

**Comment by juepiezhongren** [comment]
@mkArtakMSFT  the request which is not within near plan does not have to be closed and not be seen by other people from community

**Comment by SteveSandersonMS** [comment]
@juepiezhongren We don't mean to shut down any discussion about this. It's just that keeping issues open is an administrative burden. We have a lot of issues flowing through, and the open/closed flag is an important signal about whether there's work to do on them. The only way we can manage the project effectively is to close things when there's no further action for us to take on them. Hope that's OK.

**Comment by juepiezhongren** [comment]
thx, steve @SteveSandersonMS. 
but i have to say switch is important, considering the wasm-related diversity for browsers.
there r quite a lot scenarios for switch:
1) safari supports wasm but with too much limitations, ssr or csr switch must be configurable;
2) wasm 2.0 and wasm mvp r different which even impact bcl' implementation, switch needs to cover different wasm-bcl' imple.
3) don't forget timing, considering dependencies-download, if it costs too much time, the switch will be forbidden.
....
i have to say there will be too many requests for switch, which would result in a much more solid web-solution than current js ones.
