### ISSUE TITLE
Dynamic property in typed object not serialized to camelCase JSON

### ISSUE THREAD

**Issue by Mortana89** [aspnet/AspNetCore#9543]
### Describe the bug
When calling an API that returns a typed object that holds a dynamic property, the properties of the typed object are (correctly) returned as camelCase, while the dynamic property properties are in (Upper)PascalCase.
Setting the default JsonSerializer ContractResolver to CamelCase does not seem to work.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Create an API Controller that returns a typed object, with a dynamic property

### Expected behavior
Properties of dynamic objects should follow the configured JSON Contract Resolver settings.

**Comment by davidfowl** [comment]
You likely need to set ProcessDictionaryKeys to true on the CamelCaseNamingStrategy. Something like

```C#
new DefaultContractResolver()
            {
                NamingStrategy = new CamelCaseNamingStrategy()
                {
                    ProcessDictionaryKeys = true
                }
            };
```

cc @JamesNK

**Comment by Mortana89** [comment]
> You likely need to set ProcessDictionaryKeys to true on the CamelCaseNamingStrategy. Something like
> 
> ```cs
> new DefaultContractResolver()
>             {
>                 NamingStrategy = new CamelCaseNamingStrategy()
>                 {
>                     ProcessDictionaryKeys = true
>                 }
>             };
> ```
> 
> cc @JamesNK

I tried this as well, but it didn't bring any solution, the situation is the same, with one minor difference that, when setting the contractresolver to a defaultcontractresolver with above settings, any property that has a JsonProperty annotation, is serialized according to that jsonproperty annotation, what we don't want either.

Thanks for the suggestion, any other ideas?

**Comment by JamesNK** [comment]
Is your dynamic property a JObject? A JObject's JSON is not changed by a naming strategy, it is serialized as is.

**Comment by Mortana89** [comment]
No, basically our dynamic object is an event class.
We have events being thrown on a service bus, and one of the consumers picks up the events, and puts these in a 'payload' property of another object type. But the event is typed, and at runtime converted to dynamic.

So the flow is like this:
- An event object (A) is created
- The event is serialized to JSON
- It's put on the service bus
- A consumer picks up the event from the service bus
- The event is casted to the original event object type (A)
- A new object (B) is created, and passed the instance of this event object(A) (the method signature expects a dynamic, so runtime casting)
- This object (B) is stored in our database

API Call:
- The JSON is retrieved from the database
- JSON is serialized to B
- B is returned

At the moment the API call is being done, and the data is being fetched, there's no track anymore of the original event object's type (A), so perhaps that's the issue here, and this is causing it to be handled as a JObject? I don't see a way around this though :/

**Comment by JamesNK** [comment]
> No, basically our dynamic object is an event class.

> and this is causing it to be handled as a JObject?

I'm confused, is it a JObject or not? A JObject will not be effected by a naming standard. It is written as is because as far as the serializer is concerned it is already JSON.

**Comment by darrynhoskingluna** [comment]
I have the same problem.

```
using System;
using Newtonsoft.Json;	
using Newtonsoft.Json.Serialization;

public class Program
{
		
	public class TestViewModel
	{
    	public string P1 { get; set; }
    	public dynamic SomeDymamic { get; set; }
	}
	
	public static void Main()
	{
		var test = new TestViewModel();
		test.P1= "Test";
		
		var settings = new JsonSerializerSettings();
		settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
		
		test.SomeDymamic = JsonConvert.DeserializeObject<dynamic>("{\"Property\":\"test\"}", settings);
		
		
		Console.WriteLine(JsonConvert.SerializeObject(test,settings));
		
	}
}
```
Output: {"p1":"Test","someDymamic":{"Property":"test"}}
Expected Output: {"p1":"Test","someDymamic":{"property":"test"}}


when returned from the controller i would expect the above to follow the settings provided in the DefaultContractResolver (in my case camel case), except it defaults to pascal case.

Currently you would get a mix of casing returned. The view model will follow Camel Case, but the dynamic property would not.
