### ISSUE TITLE
UriHelper Namespace in Preview4

### ISSUE THREAD

**Issue by endeffects** [aspnet/AspNetCore#9544]
From the migration guide of Blazor Preview 4

> Remove any use of the Microsoft.AspNetCore.Components.Services namespace and replace with Microsoft.AspNetCore.Components as required.

The IUriHelper Interface was not moved into the new namespace. Is this correct?
I also get a TypeLoaderException when i try to use the old Namespace.

Same for the IComponentContext Interface.

> System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
> Could not load type 'Microsoft.AspNetCore.Components.Services.IComponentContext' from assembly 'Microsoft.AspNetCore.Components, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
> Could not load type 'Microsoft.AspNetCore.Components.Services.UriHelperBase' from assembly 'Microsoft.AspNetCore.Components, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

From Decompiler:

```
// Assembly location: ...\Packages\microsoft.aspnetcore.components\3.0.0-preview4-19204-02\lib\netstandard2.0\Microsoft.AspNetCore.Components.dll

using System;

namespace Microsoft.AspNetCore.Components.Services
{
  /// <summary>Helpers for working with URIs and navigation state.</summary>
  public interface IUriHelper
  {
...
```

**Comment by endeffects** [comment]
Seems to be a problem with the nuget restore.

**Comment by QadiymStewart** [comment]
How to fix getting same error cannot find urihelper in Microsoft.AspNetCore.Components intellisense keeps bringing up Microsoft.AspNetCore.Http.Extensions;
