### ISSUE TITLE
NavLinkMatch does not exists after creating a Blazer (server-side) project

### ISSUE THREAD

**Issue by MarcelJoestingmeier** [aspnet/AspNetCore#9546]
### Describe the bug
NavLinkMatch does not exists after creating a Blazer (server-side) project. The error disappears when prefixing `NavLinkMatch` with `Microsoft.AspNetCore.Components.Routing.` or adding a using to that namespace. The using declaration in the `_Imports.razor` seems to have no effect. The project compiles though and works fine.

### To Reproduce
1. Using this version of ASP.NET Core 3.0.100 Preview 4
2. Create a new C# Aspnet Core project
3. Choose `Blazor (server-side)` from SDK 3.0.100-preview4-011223
4. Goto `Shared/NavMenu.razer`

The error appears at line 11 in this part of the code:
`
<NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                <span class="oi oi-home" aria-hidden="true"></span> Home
</NavLink>
`

### Screenshots
`Shared/NavMenu.razor`
![image](https://user-images.githubusercontent.com/12977777/56416619-adf7f800-6291-11e9-9af6-8a719caca62b.png)

`Shared/NavMenu.razor` with prefixed `NavLinkMatch`
![image](https://user-images.githubusercontent.com/12977777/56416659-d3850180-6291-11e9-88d7-2fcfae49ba51.png)

`Shared/NavMenu.razor` with using
![image](https://user-images.githubusercontent.com/12977777/56416700-f7e0de00-6291-11e9-96aa-02ff22fc48d5.png)

`_Imports.razor` note that the usings are greyed out
![image](https://user-images.githubusercontent.com/12977777/56416781-2bbc0380-6292-11e9-93bf-154c18968853.png)

### Additional context
I did not uninstall the previous preview if that matters. I use Windows 10 and Visual Studio 2019. I also have Visual Studio 2017 and several other installations of the SDK installed.

**Comment by MarcelJoestingmeier** [comment]
I have found other similar issues in other files, all of them can be fixed the same way. It seems that the usings inside `_Imports.razor` do not have an effect outside the file itself. At least in the editor.

Because by adding the using from `_Imports.razor` to `Pages/_Imports.razor` solved the namespace issue with the `MainLayout` but creating an `_Imports.razor` inside the `Shared` folder had no effect to the namespace issues in `Shared/NavMenu` or `Shared/MainLayout`

`Pages/_Imports.razor` with fix, note that the projects namespace is now in normal color
![image](https://user-images.githubusercontent.com/12977777/56417933-beaa6d00-6295-11e9-90a1-6de098f6c9bb.png)

**Comment by MarcelJoestingmeier** [comment]
I missed step 2 of the installation guide on https://docs.microsoft.com/en-gb/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

**Comment by SharePointSean** [comment]
I am pretty sure I did everything right in the setup, but am still experiencing this issue. What is the proper fix to this? Do you know? Thanks in advance.

**Comment by MarcelJoestingmeier** [comment]
Try a complete reinstall of everything and if that does not help, i can try to help you analyze the problem.

**Comment by MarcelJoestingmeier** [comment]
I think there is no other fix besides that, and since it does not appear in my solutions anymore i did no analysis on the problem in general.

**Comment by darylib** [comment]
I have the same problem in VS2019 stable version 16.0.4. 
But in preview 3.0 version 16.1.0 it's not an issue.
