### ISSUE TITLE
Blazor: _Imports.razor not working

### ISSUE THREAD

**Issue by rjmr97** [aspnet/AspNetCore#9552]
### Describe the bug
Trying to import a namespace inside _Imports.razor to use in multiple files inside the folder but it doesn't work on the new version (details below). Placing the `@using` inside the file itself does work.

### To Reproduce
Visual Studio Community 2019 16.0.2
ASP.NET Core & .NET Core 3.0.100-preview4-011223
Blazor 3.0.0-preview4-19216-03
> dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview4-19216-03
> dotnet new blazorlib
> create files according to the screenshot

### Screenshots
![image](https://user-images.githubusercontent.com/30321188/56430432-3be9d800-62be-11e9-9b5d-407fd87d2105.png)

**Comment by rjmr97** [comment]
After some tests it looks like the problem was having a folder with the same name as the namespace I was trying to use (Layouts).

**Comment by kmuthukumar23** [comment]
I also faced this issue in my Proj. _Imports.razor not working in blazor. Please help me

**Comment by vova-lantsov-dev** [comment]
Also true for me
