### ISSUE TITLE
ViewComponent Tag Helper is not rendering if placed inside a script tag

### ISSUE THREAD

**Issue by mesuttalebi** [aspnet/AspNetCore#9553]
Edit: All tag helpers not render inside script tag not just view component's taghelper.

I'm working with vuejs and trying to create a viewcomponent that should render inside the vuejs's template, vuejs template is a script tag with type of text/template for exmaple as below:

```
<script type="text/template" id="function-template">
want to render viewcomponent here 
</script>
```

but when I try to use ViewComponent Tag helper, the viewcomponent is not render. the source code of my page in chrome is as below :

![image](https://user-images.githubusercontent.com/3634757/56431201-a0faf900-62d1-11e9-8145-4158e8c5f406.png)
 as you see in picture the tag helper remained as is.

```html
<!-- Template for Function Selector Component -->
<script type="text/template" id="function-template">
  <vc:functions-list is-for-cheatsheet="false"></vc:functions-list>    
   <div v-show="SelectedFunction !== ''">
```
the workaround for is to use Invoke method for Component.

```
@await Component.InvokeAsync("FunctionList")
``` 

![image](https://user-images.githubusercontent.com/3634757/56431465-6f366200-62d2-11e9-8e32-6efc55adcc91.png)

and then successfully rendered in browser:
![image](https://user-images.githubusercontent.com/3634757/56431528-a99fff00-62d2-11e9-90b3-e5ba19efa1a0.png)

### To Reproduce
1- create a simple viewcomponent in an asp.net mvc core project
2- inside the index.cshtml add a script tag
3- add viewcomponent tag helper inside script tag.
4- run the app and right click and select view source code in browser.

### Expected behavior
Rendered ViewComponent

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300-preview-010046
 Commit:    d6f4b3dc39

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.300-preview-010046\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010046 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by danroth27** [comment]
This is by design. Tag helpers are not supported inside of JavaScript based script tags.

**Comment by mesuttalebi** [comment]
@danroth27 Hi Daniel, Could you please say what is the reason for this, or can I found a detailed documentation for understand the reason for this design.
