### ISSUE TITLE
Inconsistent "wrong password" errors in identity UI

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#9556]
The error message for a bad password in `https://localhost:XYZ/Identity/Account/Manage/ChangePassword` is `Incorrect password.`

![image](https://user-images.githubusercontent.com/202643/56433127-ba298880-6284-11e9-927d-81a363a5e2f9.png)

But the error message for a bad password in `https://localhost:XYZ/Identity/Account/Manage/DeletePersonalData` is `Password not correct.`

![image](https://user-images.githubusercontent.com/202643/56433181-e218ec00-6284-11e9-8226-4220788bb944.png)

These should at least be consistent, because they're the same error. And the first one (`Incorrect password`) sounds better, so let's use that.

**Comment by HaoK** [comment]
Merged thanks wenz!
