### ISSUE TITLE
Update SignalR Samples Repo

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#9573]
Putting this in this repo since we don't really triage https://github.com/aspnet/SignalR-samples. People still use that repo for reference so I wanted to create this issue to track updating it for 3.0.
This might be a good candidate for the 3.0.0 milestone

**Comment by Pilchie** [comment]
@anurse is this ready to be done now?  Should it be assigned?

**Comment by anurse** [comment]
Yeah, let's do it. It seems @BrennanConroy has volunteered ;P.
