### ISSUE TITLE
I can not publish the previous version (3.0.0-preview4-19216-03) blazor to azure Blazor Host Server

### ISSUE THREAD

**Issue by carlosalcantara2668** [aspnet/AspNetCore#9576]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\Users\calcantara\Source\Repos\WebApplicationBlazorENDBEGIN.Client\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project.	WebApplicationBlazorENDBEGIN.Client	C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	233

**Comment by danroth27** [comment]
Unfortunately there is a known issue currently with the Web SDK that prevents publishing the Blazor (ASP.NET Core hosted) template to Azure: https://github.com/aspnet/websdk/issues/604

**Comment by danroth27** [comment]
Please also note that in general to publish .NET Core 3.0 apps to Azure you need to publish the app as a self-contained app as .NET Core 3.0 has not been deployed to Azure yet.
