### ISSUE TITLE
[Blazor] Creating a .nupkg of a blazorlib with dotnet pack includes the .razor files

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#9577]
### Describe the bug
Running `dotnet pack` on a blazorlib project includes the `.razor` files in the `.nupkg`, making the package produce duplicates on reference and be unusable.

### To Reproduce
1. Using ASP.NET Core 3.0 preview 4
2. dotnet new blazorlib -o Lib
3. cd Lib
4. dotnet pack
5. Inspect the .nupkg in bin\Debug

### Workaround
I added the following in my csproj to prevent the .razor files from being included in the nupkg
```xml
<ItemGroup>
    <Content Update="*.razor">
      <Pack>false</Pack>
    </Content>
</ItemGroup>
```

### Screenshots
Contents of .nupkg
![image](https://user-images.githubusercontent.com/12549761/56441750-bb939900-62f6-11e9-84e2-13817e4cc840.png)

**Comment by danroth27** [comment]
@javiercn We should make sure this issue is addressed when we do the work for #6349.

**Comment by javiercn** [comment]
@danroth27 That's orthogonal to the static context, we should do this on the razor SDK, the same way we mark .cshtml files as pack=false.
 
@pranavkm thoughts?

**Comment by pranavkm** [comment]
It's marked as [content](https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.props#L72), but we don't disable including it during pack https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L475.

**Comment by javiercn** [comment]
Fixed as part of 
https://github.com/aspnet/AspNetCore-Tooling/commit/8e70013b70a5392519aebfcf417c95e7c6bb8dfd#diff-95bef683fe9f3425f979df61c894d65bR485

**Comment by Mercurial** [comment]
Thanks for the work around!
