### ISSUE TITLE
How to disable Blazor server side render?

### ISSUE THREAD

**Issue by enetstudio** [aspnet/AspNetCore#9584]
Could you please tell me how to disable Blazor server side render in .NET Core 3.0 Preview 4

Thanks...

**Comment by alexandrereyes** [comment]
This might be a regression because in preview 3, you just needed to remove @(await Html.RenderComponentAsync<MyApp>()) from cshtml page. In preview 4 this doesn't work anymore.

**Comment by cores-system** [comment]
I believe that preview rendering should turn off.
This is not always useful and may lead to unnecessary code for the interaction of the preliminary and hub rendering.

**Comment by cores-system** [comment]
@enetstudio, Found a solution at https://github.com/aspnet/AspNetCore/pull/8911

```
app.UseEndpoints(endpoints =>
{
   endpoints.MapBlazorHub().AddComponent<App>(selector: "app");
   endpoints.MapFallbackToFile("index.html"); // or - endpoints.MapFallbackToPage("/_Host");
});
```

**Comment by danroth27** [comment]
Thanks for answering, @cores-system!

**Comment by enetstudio** [comment]
Many thanks, @cores-system!

**Comment by alexandrereyes** [comment]
Am I missing something? I'm using VS 2019 16.1 preview 2 and can't make this work (dotnet core 3 preview 4).
I just started a new Blazor Server side template then, I change from:

```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });
```

to

app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub().AddComponent<App>("app");
                endpoints.MapFallbackToFile("index.html");
            });

And then, create index.html inside pages folder

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BlazorClientSide</title>
    <base href="~/" />
    <environment include="Development">
        <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="css/bootstrap/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link href="css/site.css" rel="stylesheet" />
</head>
<body>
    <app></app>
    <script src="_framework/blazor.server.js"></script>
</body>
</html>

```

When deployed to browser: 404
