### ISSUE TITLE
ASP.NET Core MVC - Binding to model at runtime

### ISSUE THREAD

**Issue by nfplee** [aspnet/AspNetCore#9596]
Hi, would anyone know if the following is possible?:

https://stackoverflow.com/questions/55765427/asp-net-core-mvc-binding-to-model-at-runtime

I managed to do this in ASP.NET with the following model binder:

```csharp
public class IRuntimeBindableModelBinder : DefaultModelBinder {
    public override object BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext) {
        var newBindingContext = new ModelBindingContext() {
            // In the original method you have:
            // ModelMetadata = ModelMetadataProviders.Current.GetMetadataForType(() => bindingContext.Model, typeof(TModel)),
            ModelMetadata = ModelMetadataProviders.Current.GetMetadataForType(() => bindingContext.Model, bindingContext.Model.GetType()),
            ModelName = bindingContext.ModelName,
            ModelState = bindingContext.ModelState,
            PropertyFilter = bindingContext.PropertyFilter,
            ValueProvider = bindingContext.ValueProvider
        };

        return base.BindModel(controllerContext, newBindingContext);
    }
}
```

However from looking at the source, it seems model binding has been rewritten in ASP.NET Core.

**Comment by danroth27** [comment]
It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://stackoverflow.com) using the asp.net-core-mvc tag.

**Comment by nfplee** [comment]
Thanks, I've already posted it on [StackOverflow](https://stackoverflow.com/questions/55765427/asp-net-core-mvc-binding-to-model-at-runtime) and opened a bounty to get more attention but I'm yet to receive a response.

I guess posting it over the Easter holiday was not the best of ideas. However since it's more of an advanced topic I hoped someone on the team would have more of an idea.

**Comment by nfplee** [comment]
[WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3107487/WebApplication1.zip)

I've attached a very basic sample application incase it helps.

**Comment by nfplee** [comment]
Someone has posted a solution on the referenced StackOverflow post.
