### ISSUE TITLE
Blazor : cannot bind nullable DateTime to input

### ISSUE THREAD

**Issue by glacasa** [aspnet/AspNetCore#9598]
The issue #5541 is supposed to be solved on the last preview.

It works fine with `int?` and `bool?`, but I'm still not able to bind a nullable DateTime to an `<input type="date">`

The error is different than on the previous issue :
error CS0029: Cannot implicitly convert type 'string' to 'System.DateTime?'

Is it supposed to work, or is there a workaround for that ?

**Comment by danroth27** [comment]
Instead of handling this as a one off case we should look at handling this scenario in a more general way (maybe using TypeConverters or something similar?)

**Comment by mkArtakMSFT** [comment]
This is already supported.
