### ISSUE TITLE
Calling HttpContext.Request.BodyReader.Complete causes an exception

### ISSUE THREAD

**Issue by stephan-tolksdorf** [aspnet/AspNetCore#9600]
In ASP.NET Core 3.0 Preview 4 calling `HttpContext.Request.BodyReader.Complete()` eventually triggers an exception with the following call stack:

```
Http1ContentLengthMessageBody.ThrowIfCompleted() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
Http1ContentLengthMessageBody.TryRead() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
Http1MessageBody.OnConsumeAsync() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
Http1ContentLengthMessageBody.ConsumeAsync() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
async HttpProtocol.ProcessRequests<Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context>() in Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http, Microsoft.AspNetCore.Server.Kestrel.Core.dll
...
```

**Comment by davidfowl** [comment]
Good catch! This is because we drain the body after the request has ended just in case it wasn't consumed. We can be smarter here 😄 

cc @jkotalik

**Comment by stephan-tolksdorf** [comment]
By the way, it would be great if the ASP.NET Core documentation contained some guidance on how best to use `Request.BodyReader` and `Response.BodyWriter` in a HTTP request handler. For example, it is not obvious to me, whether calling `Complete` on the reader or writer could be useful, whether calling `Advance` on the reader is important even when returning immediately afterwards, or under which circumstances one should call `FlushAsync` on the writer.

**Comment by davidfowl** [comment]
@jkotalik wrote some docs on this https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-3.0. They need to be updated for preview4 as the properties were renamed. 

These new properties are for low level access to the buffers and we expect them to be used in places where you were directly using the Request.Body or Response.Body Stream before. This background should also be helpful https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/.

Agree though, we need more docs in this area

**Comment by anurse** [comment]
Let's suppress `Complete` on the request body reader. @jkotalik will take a further look.

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        *[x] Verified against ASP.NET Core App Version 3.0.0-preview7.19351.2
