### ISSUE TITLE
Missing NuGet for latest Microsoft.AspNetCore.Http.Abstractions preview

### ISSUE THREAD

**Issue by stsrki** [aspnet/AspNetCore#9611]
I have a component library that is configured to work for Blazor and for Razor Components. In the previous version of Blazor/RC there was a version **3.0.0-preview3-19153-02** of **Microsoft.AspNetCore.Http.Abstractions** that matched the **.Net Core 3** preview number. Now in the latest **preview 4** there is no equivalent package to be found.

**Questions:**

1. Should there be a version 3.0.0-**preview4-19216-03** of Microsoft.AspNetCore.Http.Abstractions?

2. If not, what version should I include in my build process so that users of my library can safely add my NuGet packages without breaking anything?

**Additional info:**

For your reference, current version of build configuration for preview 3 can be found on https://github.com/stsrki/Blazorise/blob/master/Build/Blazorise.props

**Comment by neven10** [comment]
Probably related

https://github.com/aspnet/AspNetCore/issues/8527

If you look at 
C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0-preview4-19216-03\
you'll find Microsoft.AspNetCore.Http.Abstractions so you don't have to reference it individually.

**Comment by stsrki** [comment]
@neven10 thanks for pointing me in the right direction. I have managed to make it work by just adding a `FrameworkReference` instead of `PackageReference`.

**Example**
```
<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
```

**Comment by rynowak** [comment]
This is the correct thing to do if you need to reference `Microsoft.AspNetCore.Http.Abstractions` for some reason.

However, I'm a little concerned if you end up needing libraries from the server side framework in a general-purpose component library. This is going to negatively impact app size for client-side Blazor. I'd be interested to know what your needs are, and if we can address them in some other way.

**Comment by neven10** [comment]
Weren't there plans to implement some sort of tree shaking in client side blazor? Like JS SPAs do?
I think i've read that somewhere.

**Comment by rynowak** [comment]
We already have support for running the mono linker - that's not a cure-all though. Suppose that you're using part of HttpAbstractions that has a really thick set of real dependencies (Span, Memory, vectorized string operations) - those won't be linked out because they are needed. 

We're trying to avoid you needing our server-side stack inside a client-side app.

**Comment by stsrki** [comment]
@rynowak The only thing that I need from `Microsoft.AspNetCore.Http.Abstractions` is `IApplicationBuilder`. I need it so I can register custom implementation of my "base" components in Blazorise, which is my root library. The base library contains all of the components with default behaviour and then I have custom implementation for Bootstrap, Bulma, Material etc. 

By using `IApplicationBuilder` or `IComponentsApplicationBuilder` I can get `IServiceProvider` with which I can register custom components. Registered components are later rendered by using `RenderTreeBuilder`.

In the following example you can see how I register some of the components for Bootstrap implementation:

```
private static void RegisterComponents( IComponentMapper componentMapper )
        {
            componentMapper.Register<Blazorise.Addon, Bootstrap.Addon>();
            componentMapper.Register<Blazorise.BarToggler, Bootstrap.BarToggler>();
            componentMapper.Register<Blazorise.BarDropdown, Bootstrap.BarDropdown>();
            componentMapper.Register<Blazorise.CardSubtitle, Bootstrap.CardSubtitle>();
            componentMapper.Register<Blazorise.CloseButton, Bootstrap.CloseButton>();
            componentMapper.Register<Blazorise.CheckEdit, Bootstrap.CheckEdit>();
            componentMapper.Register<Blazorise.Field, Bootstrap.Field>();
            componentMapper.Register<Blazorise.FieldBody, Bootstrap.FieldBody>();
            componentMapper.Register<Blazorise.FileEdit, Bootstrap.FileEdit>();
            componentMapper.Register<Blazorise.ModalContent, Bootstrap.ModalContent>();
            componentMapper.Register<Blazorise.SimpleButton, Bootstrap.SimpleButton>();
        }

#if NETSTANDARD2_0

        public static IComponentsApplicationBuilder UseBootstrapProviders( this IComponentsApplicationBuilder app )
        {
            var componentMapper = app.Services.GetRequiredService<IComponentMapper>();

            RegisterComponents( componentMapper );

            return app;
        }

#else // netcoreapp3.0

        public static IApplicationBuilder UseBootstrapProviders( this IApplicationBuilder app )
        {
            var componentMapper = app.ApplicationServices.GetRequiredService<IComponentMapper>();

            RegisterComponents( componentMapper );

            return app;
        }

#endif
```

and then I call it on the application Startup:

```
app
    .UseBootstrapProviders();
```

This way I can have same usage for both Blazor(client-side) and for RC(server-side).

I could create extension methods based on `IServiceProvider` but then I couldn't chain my registration for other libraries like:

```
app
    .UseBootstrapProviders()
    .UseFontAwesomeIcons();
```

**Comment by stsrki** [comment]
PS. This is the configuration for my project(s) now adjusted for .Net Core 3-preview 4

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<Version>0.6.4-preview1-19154-02</Version>
		<PackageVersion>0.6.4-preview1-19154-02</PackageVersion>

		<Description>Blazorise is a component library built on top of Blazor and CSS frameworks like Bootstrap, Bulma and Material.</Description>
		<Authors>Mladen Macanovic</Authors>
		<Company></Company>
		<Copyright>Copyright 2019 Mladen Macanovic</Copyright>
		<RepositoryUrl>https://github.com/stsrki/Blazorise</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		
		<TargetFrameworks>netstandard2.0;netcoreapp3.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<IsPackable>true</IsPackable>   
		<LangVersion>7.3</LangVersion>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		
		<_RazorComponentInclude>*.cshtml</_RazorComponentInclude>
		
		<RestoreAdditionalProjectSources>
			https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json;
			https://dotnet.myget.org/F/blazor-dev/api/v3/index.json;
		</RestoreAdditionalProjectSources>

		<RazorLangVersion>3.0</RazorLangVersion>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	</PropertyGroup>
	
	<PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
		<DefineConstants>$(DefineConstants);NETSTANDARD2_0</DefineConstants>
	</PropertyGroup>
	
	<PropertyGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
		<DefineConstants>$(DefineConstants);NETCORE3_0</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
		<PackageReference Include="Microsoft.AspNetCore.Components.Browser" Version="3.0.0-preview4-19216-03" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
```
