### ISSUE TITLE
JavaScript interop calls cannot be issued at this time

### ISSUE THREAD

**Issue by cores-system** [aspnet/AspNetCore#9613]
It is forbidden to use JSRuntime during pre-rendering.

```
[Inject]
protected IJSRuntime JS { get; set; }

protected override void OnAfterRender()
{
   JS.InvokeAsync<bool>("paceDone");
   base.OnAfterRender();
}
```

```
System.InvalidOperationException: "JavaScript interop calls cannot be issued at this time. This is because the component is being prerendered and the page has not yet loaded in the browser or because the circuit is currently disconnected. Components must wrap any JavaScript interop calls in conditional logic to ensure those interop calls are not attempted during prerendering or while the client is disconnected."
```

How do I know that JSRuntime is unavailable?
There are some solutions to this problem besides resource-intensive try { } ?

Blazor 0.10

**Comment by cores-system** [comment]
In addition, I cannot figure out how to call IJSRuntime after a user connects to BlazorHub

**Comment by kennywangjin** [comment]
inject IComponentContect

**Comment by cores-system** [comment]
@kennywangjin IComponentContect not found

**Comment by kennywangjin** [comment]
call  jsruntime in onafterrender， using componentcontext to determine whether it is prerendering

**Comment by guardrex** [comment]
It's partially covered by the recent updates at [Blazor: JavaScript interop: Detect when a Blazor app is prerendering](https://docs.microsoft.com/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#detect-when-a-blazor-app-is-prerendering). Although we have an example for `IComponentContext`, we're bit light on `OnAfterRenderAsync` with only the remark ...

> To delay JavaScript interop calls until after the connection with the browser is established, you can use the OnAfterRenderAsync component lifecycle event. This event is only called after the app is fully rendered and the client connection is established.

I've opened [Provide code example of OnAfterRenderAsync in Blazor JSInterop topic (aspnet/AspNetCore.Docs \#12087)](https://github.com/aspnet/AspNetCore.Docs/issues/12087) to expand the coverage.

**Comment by cores-system** [comment]
@guardrex, OnAfterRenderAsync is called several times, which leads to additional checks, but how do I understand this crutch is the only solution?

**Comment by guardrex** [comment]
AFAIK, it's **_the_** solution ... the *only* solution. One or more of the engineers will answer soon and provide more info. Stand-by.

**Comment by cores-system** [comment]
Ideally, a solution to disable pre-rendering would help, so that JSRuntime could be used anywhere, including OnInit without additional switches in OnAfterRenderAsync.

**Comment by cores-system** [comment]
Reshil problemu otklyucheniyem predvaritel'nogo renderinga https://github.com/aspnet/AspNetCore/pull/8911  (on mne ne nuzhen dlya tekushchego proyekta)
142/5000
I solved the problem by disabling the preliminary rendering https://github.com/aspnet/AspNetCore/pull/8911 (I do not need it for the current project)
