### ISSUE TITLE
ASP.Net hosted blazor client default project uses the old WebHostBuilder rather than the generic HostBuilder

### ISSUE THREAD

**Issue by MarkStega** [aspnet/AspNetCore#9614]
### Is your feature request related to a problem? Please describe.
ASP.Net documentation states that the preferred host is the GenericHost

### Describe the solution you'd like
I believe the generated Blazor project should follow the 'best practices' outlined in the documentation.

### Describe alternatives you've considered
n/a

### Additional context
The generated program.cs should be:
`using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace WebApplication1.Server
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}`

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/9225.

**Comment by blowdart** [comment]
Closing as dupe
