### ISSUE TITLE
[SignalR] Binary payload inflated by 33% with MessagePack transport

### ISSUE THREAD

**Issue by BrightSoul** [aspnet/AspNetCore#9615]
Hello there,
I made a small sample application (ASP.NET Core 2.2) to demonstrate how to push images from server to client. Here it is: it's using ASP.NET Core SignalR and MessagePack as transport.
[https://github.com/BrightSoul/aspnetcore-realtime-binary](https://github.com/BrightSoul/aspnetcore-realtime-binary)

The application is indeed working but I've noticed that my `byte[]` payload is being inflated by 33% when going through the websockets transport via MessagePack.

![inflated-payload](https://user-images.githubusercontent.com/1888641/56473692-f8829b80-646e-11e9-8512-6254bb211821.png)

No matter the size: if I send 1000 bytes, the client receives 1333+ bytes.
If I send 10000 bytes, the client receives 13333+ bytes.
Unfortunately, Chome doesn't let me peek at a binary payload. I might have to use Wireshark to see what's inside.

Is the payload, by any chance, encoded in base64? Would you explain why I'm observing this?
MessagePack should be able to handle binary payloads wihtout base64 encoding, [according to specification](https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family).

Thanks

**Comment by davidfowl** [comment]
There’s framing surrounding your message (dispatch data to invoke the right callback). That includes the method name, argument count, type of invocation. These are all stored in a msg pack array itself so that adds some framing as well.

**Comment by BrightSoul** [comment]
Thank you for your answer.

> There’s framing surrounding your message

Indeed, but why is that proportional to the payload size?
Look at this: when I send 100k bytes, the client receives 133k bytes.
![proportional](https://user-images.githubusercontent.com/1888641/56474826-a8f89b80-647f-11e9-9cae-d47c2b1f8c20.png)

If this is normal for SignalR, I might go back to writing my own custom protocol over websockets to improve throughtput.

**Comment by BrightSoul** [comment]
@davidfowl Nevermind, I think it's just Google Chrome that's reporting the wrong length (but I don't know why).
When I inspect the frames using Fiddler, then it reports che correct size. These are some frames with a 1000 byte payload. A small overhead (method name, etc), followed by zeros (the payload).

![fiddler](https://user-images.githubusercontent.com/1888641/56475326-c41ad980-6486-11e9-8cb6-af1140884beb.png)

I'm sorry for the fuss, I was misled by what I saw on Google Chrome.

**Comment by BrennanConroy** [comment]
Glad you figured it out! Thanks for trying out Messagepack :)

**Comment by BrightSoul** [comment]
> Glad you figured it out! Thanks for trying out Messagepack :)

Yeah, it's great!
