### ISSUE TITLE
Blazor Components namespace

### ISSUE THREAD

**Issue by SamProf** [aspnet/AspNetCore#9616]
From Preview 4 we have Resolve components based on @using, that's is really right way.
For example I have this project file structure.
```
Project MatBlazor
   Components
      MatButton
         MatButton.razor
      MatSelect
         MatSelect.razor

````

And of course i have full type name - MatBlazor.Components.MatButton.MatButton
At previous versions of Blazor all you need to use all components from one library was `@addTagHelper`, but now you need every component write `@using MatBlazor.Components.MatButton`  but this is not useful.
It would be better if you can write `@using MatBlazor` in `_Imports.razor` and that's all!
The best solution if I put all Blazor classes in one namespace MatBlazor, but I can not change generated namespace for `*.razor` files.

So, my request is to add posibillity to change namespace of the components. Somthing like `@namespace MatBlazor`.

Of course I can write thin "proxies" using inheritance, but this is not useful.
```csharp
namespace MatBlazor
{
    public class MatButton : MatBlazor.Components.MatButton.MatButton
    {
    }
}
```

**Comment by rynowak** [comment]
We do plan to add `@namespace`. We already have it for views so it's easy to enough to add.

What's the problem with putting all of your components in the same folder? just curious?

**Comment by rynowak** [comment]
We plan to support `@namespace` for preview 6 https://github.com/aspnet/AspNetCore/issues/8007

**Comment by SamProf** [comment]
Thank you.
