### ISSUE TITLE
Blazor Client-Side throws unhelpful errors under netcoreapp3.0

### ISSUE THREAD

**Issue by robertmclaws** [aspnet/AspNetCore#9617]
### Describe the bug
I had a Blazor Client-Side app previously running under netcoreapp3.0 (by mistake). When updating an existing project to 3.0 Preview 4, I encountered the exception `Could not find the type 'MonoWebAssemblyJSRuntime' in the namespace 'Mono.WebAssembly.Interop' in the assembly 'Mono.WebAssembly.Interop'` in the browser console when the app tried to initialize. When breaking earlier in the JS call stack to find the problem, the code says that `mono_wasm_assembly_load` is not a registered function. 

The only way to track down the error was to create a new Blazor project and use Beyond Compare to diff the output of a clean app vs my app.

### To Reproduce
1. Create a new Blazor client-side project with the latest version of .NET Core 3.0 (Preview 4) and Blazor. 
2. Change the `TargetFramework` in the project file to netcoreapp3.0.
3. Hit F5 and run the app.

### Expected behavior
I expect the compiler to warn me when I am using a `TargetFramework` that is incompatible with Blazor's operation, OR I expect the `Could not find the type 'MonoWebAssemblyJSRuntime'...` error to suggest ways to fix the problem.

### Additional context
Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009748 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009804 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009969 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  2.2.201 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010046 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by danroth27** [comment]
Thanks for reporting this issue @robertmclaws! I'm glad to hear you were able to figure this one out. Since the target framework of the app was incorrect, there isn't really anything that we could do here since Blazor is currently based on .NET Standard. We are looking at reconciling Blazor with .NET Core in the future, which may help make this experience better

**Comment by robertmclaws** [comment]
So, in my "Expected Behavior" section, that the error message thrown was hiding the actual error, and that the message could also suggest ways to fix the problem (i.e. make sure the app is correctly targeting netstandard2.0). Is that not something that is possible? I can't be the only person that is ever going to make that mistake...

Thanks!

**Comment by danroth27** [comment]
It may certainly be possible! But right now we have way more work than we think we can get done for this release, so unless we hear more customer feedback that this is a common error case, it's unlikely that we will get to this any time soon. We know that's not ideal. We wish we could polish all the cases like this, but right now we really need to focus on more critical functional issues.
