### ISSUE TITLE
IIS Host Module InProcess Performance slow with both V1 and V2 installed

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/AspNetCore#9626]
### Describe the bug
I've been doing some informal perf testing on a local machine where I've recently tested performance various local simple requests. Orignially I was able to get performance around 37k req/sec out of the InProcess module for both hello world and hello json controllers which is pretty good (much better than OutOfProcess)

Today I came back to find the same exact app and re-testing and found that performance had dropped to ~1.9k req/sec. Same app, no changes. Out of Process hosting, raw Kestrel and IIS static file hosting all were pretty much the same as the old tests, but InProc hosting consistently down to under 2k r/s.

After a lot of trial and error of uninstalling newer SDKs, I finally looked in the IIS Module list to find both the  V1 and V2 modules installed in IIS:

![image](https://user-images.githubusercontent.com/1374013/56481852-bf413000-645c-11e9-9d93-68a56f9f5a57.png)

I removed the V1 module from the application and perf for InProc hosting jumped back up to ~37k req/sec as I would expect.

Put the V1 module back in and boom it's back down to 1.9k r/s. Looks like changing the order will also fix the problem.

### To Reproduce
Check to see if V1 ASP.NET Core module is installed. If not install it explicitly and compare performance between V1 and V2 in use.

### Expected behavior
When V2 module installs it should take precedence over the V1 module to ensure that the right one does get run.

I did reinstall the .NET Core 2.2 SDK last, so the V2 module would have installed or updated last, but even so the V1 module was first in the module list.

If V1 and V2 are compatible then maybe the V1 should be removed when V2 is installed.

**Comment by RickStrahl** [comment]
Argghhh... looks like it might be something else after all. After reinstalling and adding and removing the issue has returned and removing the V1 module doesn't help. It also looks like in process is working no matter what.

Turns out the issue is related to switching into a Development build and the info logging bogging down the 

My error although I haven't been able to trace down where the development flags are coming from. Unrelated so closing. Sorry for false circumstancial alarm (once again).

**Comment by Kossx2** [comment]
@RickStrahl I've been having this exact problem. After 2 days of try everything, I've found that, atleast in my case, the problem was the Microsoft Logging category. For example, changing its value from "Information" to "Warning" solved the problem. Now I'm trying to figure out why it can be.
