### ISSUE TITLE
Visual studio 2019 test code coverage analyze could not calculate the blazor code when using WebDriver

### ISSUE THREAD

**Issue by yukozh** [aspnet/AspNetCore#9630]
### Describe the bug
Run UI test with Web Driver but the code coverage shown 0%.

![image](https://user-images.githubusercontent.com/2216750/56494459-e9f6bb80-6524-11e9-82d7-ede7f23af2e8.png)

### To Reproduce
Run the UI test: https://github.com/yukozh/YukoBlazor/tree/master/test/YukoBlazor.Client.Tests

### Expected behavior
The tested code path should be marked as covered.

### Additional context
- VS2019 
- Blazor 0.9.0

**Comment by danroth27** [comment]
This isn't something we really control on the Blazor side. Could you please file a VS Feedback issue for this?

**Comment by yukozh** [comment]
How to?

**Comment by anoooin** [comment]
Hi @yukozh / @danroth27  ,

Is there an existing VS issue that has been raised please?

Thank you!

**Comment by danroth27** [comment]
@anoooin @yukozh I don't see one yet. You can open one here: https://developercommunity.visualstudio.com.

**Comment by anoooin** [comment]
@danroth27  - I have raised an issue https://developercommunity.visualstudio.com/content/problem/593469/visual-studio-2019-analyze-code-coverage-code-cove.html

Thank you!
