### ISSUE TITLE
Native dependencies can cause BadImageFormatException in build

### ISSUE THREAD

**Issue by ErikApption** [aspnet/AspNetCore#9633]
### Describe the bug
I have a project with the DinkToPdf nuget package. That package includes native DLLs.
The new blazor preview4 seems to use Cecil which fails on these DLLs and causes the whole build to fail.

### To Reproduce
1. Add DinktoPDF to a blazor project
2. Run build

### Expected behavior
Successful build - the build should ignore that native DLL since it is only used in the controllers.

### Additional context
See below for the build log

4>------ Build started: Project: WebAppBootStrap, Configuration: Debug Any CPU ------
4>Controllers\PdfGeneratorController.cs(35,42,35,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
4>Startup.cs(120,13,120,41): warning MVC1005: Using 'UseMvcWithDefaultRoute' to configure MVC is not supported while using Endpoint Routing. To continue using 'UseMvcWithDefaultRoute', please set 'MvcOptions.EnableEndpointRounting = false' inside 'ConfigureServices'.
4>Controllers\PdfGeneratorController.cs(35,42,35,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
4>Components\Pages\Review.razor(102,16,102,26): warning CS0649: Field 'Review.SideBarRef' is never assigned to, and will always have its default value
4>Startup.cs(120,13,120,41): warning MVC1005: Using 'UseMvcWithDefaultRoute' to configure MVC is not supported while using Endpoint Routing. To continue using 'UseMvcWithDefaultRoute', please set 'MvcOptions.EnableEndpointRounting = false' inside 'ConfigureServices'.
4>WebAppBootStrap -> D:\code\Cloud Data Tools-ml\DataTools\WebAppBootStrap\bin\Debug\netcoreapp3.0\WebAppBootStrap.dll
4>Fatal error in IL Linker
4>
4>Unhandled Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
4>   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics, UInt16& linker)
4>   at Mono.Cecil.PE.ImageReader.ReadImage()
4>   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
4>   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
4>   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
4>   at Mono.Linker.LinkContext.Resolve(String name)
4>   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
4>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
4>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
4>   at Mono.Linker.Pipeline.Process(LinkContext context)
4>   at Mono.Linker.Driver.Run(ILogger customLogger)
4>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
4>   at Mono.Linker.Driver.Main(String[] args)
4>C:\project\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview4-19216-03\targets\Blazor.MonoRuntime.targets(439,5): error MSB3073: The command "dotnet "C:\project\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\project\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/mono/bcl/" -d "C:\project\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/mono/bcl/Facades/" -o "D:\code\Cloud Data Tools-ml\DataTools\WebAppBootStrap\obj\Debug\netcoreapp3.0\blazor\linker/" -x "C:\project\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview4-19216-03\targets\BuiltInBclLinkerDescriptor.xml" -x "D:\code\Cloud Data Tools-ml\DataTools\WebAppBootStrap\obj\Debug\netcoreapp3.0\blazor\linker.descriptor.xml" -a "C:\project\.nuget\packages\accord\3.8.0\lib\netstandard2.0\Accord.dll" -a "C:\project\.nuget\packages\accord.math\3.8.0\lib\netstandard2.0\Accord.Math.Core.dll" -a "C:\project\.nuget\packages\accord.math\3.8.0\lib\netstandard2.0\Accord.Math.dll" -a "C:\project\.nuget\packages\accord.statistics\3.8.0\lib\netstandard2.0\Accord.Statistics.dll" -a "C:\project\.nuget\packages\csvhelper\12.1.2\lib\netstandard2.0\CsvHelper.dll" -a "C:\project\.nuget\packages\dinktopdf\1.0.8\lib\netstandard1.6\DinkToPdf.dll" -a "C:\project\.nuget\packages\electronnet.api\0.0.11\lib\netcoreapp2.1\ElectronNET.API.dll" -a "C:\project\.nuget\packages\engineioclientdotnet\1.0.5\lib\netstandard1.3\EngineIoClientDotNet.dll" -a "C:\project\.nuget\packages\fastenshtein\1.0.0.5\lib\netstandard1.0\Fastenshtein.dll" -a "C:\project\.nuget\packages\microsoft.aspnetcore.blazor\3.0.0-preview4-19216-03\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\project\.nuget\packages\microsoft.aspnetcore.jsonpatch\3.0.0-preview4-19216-03\lib\netcoreapp3.0\Microsoft.AspNetCore.JsonPatch.dll" -a "C:\project\.nuget\packages\microsoft.aspnetcore.mvc.newtonsoftjson\3.0.0-preview4-19216-03\lib\netcoreapp3.0\Microsoft.AspNetCore.Mvc.NewtonsoftJson.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.language\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Razor.Language.dll" -a "C:\project\.nuget\packages\microsoft.azure.keyvault.core\3.0.3\lib\netstandard1.4\Microsoft.Azure.KeyVault.Core.dll" -a "C:\project\.nuget\packages\microsoft.azure.storage.blob\9.4.2\lib\netstandard2.0\Microsoft.Azure.Storage.Blob.dll" -a "C:\project\.nuget\packages\microsoft.azure.storage.common\9.4.2\lib\netstandard2.0\Microsoft.Azure.Storage.Common.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.codeanalysis.common\2.8.0\lib\netstandard1.3\Microsoft.CodeAnalysis.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.codeanalysis.csharp\2.8.0\lib\netstandard1.3\Microsoft.CodeAnalysis.CSharp.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.codeanalysis.csharp.workspaces\2.8.0\lib\netstandard1.3\Microsoft.CodeAnalysis.CSharp.Workspaces.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.codeanalysis.workspaces.common\2.8.0\lib\netstandard1.3\Microsoft.CodeAnalysis.Workspaces.dll" -a "C:\project\.nuget\packages\microsoft.data.dataview\0.11.0\lib\netstandard2.0\Microsoft.Data.DataView.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\lib\netstandard2.0\Microsoft.ML.Core.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\lib\netstandard2.0\Microsoft.ML.Data.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\lib\netstandard2.0\Microsoft.ML.FastTree.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\lib\netstandard2.0\Microsoft.ML.KMeansClustering.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\lib\netstandard2.0\Microsoft.ML.PCA.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\lib\netstandard2.0\Microsoft.ML.StandardLearners.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\lib\netstandard2.0\Microsoft.ML.Transforms.dll" -a "C:\project\.nuget\packages\microsoft.ml.cpumath\0.11.0\lib\netstandard2.0\Microsoft.ML.CpuMath.dll" -a "C:\project\.nuget\packages\microsoft.visualstudio.web.codegeneration\2.2.3\lib\netstandard2.0\Microsoft.VisualStudio.Web.CodeGeneration.dll" -a "C:\project\.nuget\packages\microsoft.visualstudio.web.codegeneration.contracts\2.2.3\lib\netstandard2.0\Microsoft.VisualStudio.Web.CodeGeneration.Contracts.dll" -a "C:\project\.nuget\packages\microsoft.visualstudio.web.codegeneration.core\2.2.3\lib\netstandard2.0\Microsoft.VisualStudio.Web.CodeGeneration.Core.dll" -a "C:\project\.nuget\packages\microsoft.visualstudio.web.codegeneration.design\2.2.3\lib\netstandard2.0\dotnet-aspnet-codegenerator-design.dll" -a "C:\project\.nuget\packages\microsoft.visualstudio.web.codegeneration.entityframeworkcore\2.2.3\lib\netstandard2.0\Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.dll" -a "C:\project\.nuget\packages\microsoft.visualstudio.web.codegeneration.templating\2.2.3\lib\netstandard2.0\Microsoft.VisualStudio.Web.CodeGeneration.Templating.dll" -a "C:\project\.nuget\packages\microsoft.visualstudio.web.codegeneration.utils\2.2.3\lib\netstandard2.0\Microsoft.VisualStudio.Web.CodeGeneration.Utils.dll" -a "C:\project\.nuget\packages\microsoft.visualstudio.web.codegenerators.mvc\2.2.3\lib\netstandard2.0\Microsoft.VisualStudio.Web.CodeGenerators.Mvc.dll" -a "C:\project\.nuget\packages\mono.webassembly.interop\3.0.0-preview4.19216.2\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\project\.nuget\packages\newtonsoft.json.bson\1.0.2\lib\netstandard2.0\Newtonsoft.Json.Bson.dll" -a "C:\project\.nuget\packages\nlog\4.6.2\lib\netstandard2.0\NLog.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\nuget.frameworks\4.7.0\lib\netstandard1.6\NuGet.Frameworks.dll" -a "C:\project\.nuget\packages\socketioclientdotnet\1.0.5\lib\netstandard1.3\SocketIoClientDotNet.dll" -a "C:\project\.nuget\packages\supersocket.clientengine.core\0.9.0\lib\netstandard1.3\SuperSocket.ClientEngine.dll" -a "C:\project\.nuget\packages\system.codedom\4.4.0\lib\netstandard2.0\System.CodeDom.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.composition.attributedmodel\1.0.31\lib\netstandard1.0\System.Composition.AttributedModel.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.composition.convention\1.0.31\lib\netstandard1.0\System.Composition.Convention.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.composition.hosting\1.0.31\lib\netstandard1.0\System.Composition.Hosting.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.composition.runtime\1.0.31\lib\netstandard1.0\System.Composition.Runtime.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.composition.typedparts\1.0.31\lib\netstandard1.0\System.Composition.TypedParts.dll" -a "C:\project\.nuget\packages\system.configuration.configurationmanager\4.6.0-preview3.19128.7\lib\netstandard2.0\System.Configuration.ConfigurationManager.dll" -a "C:\project\.nuget\packages\system.data.sqlclient\4.6.0\lib\netcoreapp2.1\System.Data.SqlClient.dll" -a "C:\project\.nuget\packages\system.data.sqlite.core\1.0.110\lib\netstandard2.0\System.Data.SQLite.dll" -a "C:\project\.nuget\packages\system.reactive\4.1.3\lib\netstandard2.0\System.Reactive.dll" -a "C:\project\.nuget\packages\system.reactive.core\4.1.3\lib\netstandard2.0\System.Reactive.Core.dll" -a "C:\project\.nuget\packages\system.reactive.linq\4.1.3\lib\netstandard2.0\System.Reactive.Linq.dll" -a "C:\project\.nuget\packages\system.security.cryptography.protecteddata\4.6.0-preview3.19128.7\lib\netstandard2.0\System.Security.Cryptography.ProtectedData.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.text.encoding.codepages\4.5.0\lib\netstandard2.0\System.Text.Encoding.CodePages.dll" -a "C:\project\.nuget\packages\websocket4net\0.15.1\lib\netstandard1.3\WebSocket4Net.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\runtimes\win-x64\native\FactorizationMachineNative.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\runtimes\win-x64\native\FastTreeNative.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\runtimes\win-x64\native\LdaNative.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\runtimes\win-x86\native\FactorizationMachineNative.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\runtimes\win-x86\native\FastTreeNative.dll" -a "C:\project\.nuget\packages\microsoft.ml\0.11.0\runtimes\win-x86\native\LdaNative.dll" -a "C:\project\.nuget\packages\microsoft.ml.cpumath\0.11.0\runtimes\win-x64\native\CpuMathNative.dll" -a "C:\project\.nuget\packages\microsoft.ml.cpumath\0.11.0\runtimes\win-x86\native\CpuMathNative.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\runtime.win-arm64.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-arm64\native\sni.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\runtime.win-x64.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-x64\native\sni.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\runtime.win-x86.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-x86\native\sni.dll" -a "C:\project\.nuget\packages\system.data.sqlclient\4.6.0\runtimes\unix\lib\netcoreapp2.1\System.Data.SqlClient.dll" -a "C:\project\.nuget\packages\system.data.sqlclient\4.6.0\runtimes\win\lib\netcoreapp2.1\System.Data.SqlClient.dll" -a "C:\project\.nuget\packages\system.data.sqlite.core\1.0.110\runtimes\linux-x64\native\netstandard2.0\SQLite.Interop.dll" -a "C:\project\.nuget\packages\system.data.sqlite.core\1.0.110\runtimes\osx-x64\native\netstandard2.0\SQLite.Interop.dll" -a "C:\project\.nuget\packages\system.data.sqlite.core\1.0.110\runtimes\win-x64\native\netstandard2.0\SQLite.Interop.dll" -a "C:\project\.nuget\packages\system.data.sqlite.core\1.0.110\runtimes\win-x86\native\netstandard2.0\SQLite.Interop.dll" -a "C:\project\.nuget\packages\system.security.cryptography.protecteddata\4.6.0-preview3.19128.7\runtimes\win\lib\netstandard2.0\System.Security.Cryptography.ProtectedData.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.text.encoding.codepages\4.5.0\runtimes\win\lib\netcoreapp2.0\System.Text.Encoding.CodePages.dll" -a "D:\code\Cloud Data Tools-ml\DataTools\Recognizer\bin\Debug\netstandard2.0\CoreRecognizers.dll" -a "D:\code\Cloud Data Tools-ml\DataTools\DataTools\bin\Debug\netstandard2.0\DataTools.dll" -a "D:\code\Cloud Data Tools-ml\DataTools\MLRecognizerTools\bin\Debug\netstandard2.0\MLRecognizers.dll" -a "D:\code\Cloud Data Tools-ml\DataTools\SecondPassExecution\bin\Debug\netstandard2.0\SecondPassExecution.dll" -a "D:\code\Cloud Data Tools-ml\DataTools\WebAppBootStrap\obj\Debug\netcoreapp3.0\WebAppBootStrap.dll"" exited with code -532462766.
4>Done building project "WebAppBootStrap.csproj" -- FAILED.
========== Build: 3 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by danroth27** [comment]
In general native dependencies are not expected to work when running on WebAssembly. We do however plan to make the error message better. Since we have that tracked elsewhere, I'm going to go ahead and close this issue.
