### ISSUE TITLE
.razor parsing forces code blocks, even in functions block

### ISSUE THREAD

**Issue by tn-5** [aspnet/AspNetCore#9637]
### Describe the bug
The compiler does not allow "single-statement control flow statements" In the "cshtml" part of a .razor file. I understand that is required, but currently it also enforces this rule in the "@functions" block. My understanding was that in the @functions block any normal c# syntax can be used.

### To Reproduce
"dotnet new blazorserverside"
Edit the "components.razor" file and replace the "IncrementCount" function with:

```csharp
 void IncrementCount()
    {
        if (true)
        currentCount++;
    }
```

### Expected behavior
It should not give a compile time syntax error

**Comment by cores-system** [comment]
I would also like to support the code without using `{}`

**Comment by danroth27** [comment]
We are able to reproduce this.

**Comment by chucker** [comment]
(This appears to be a regression in preview4 compared to preview3.)

**Comment by vertonghenb** [comment]
Using VS 2019 16.1 Preview 2

**Comment by MaherJendoubi** [comment]
I am facing the same issue using VS2019 16.1 Preview 2 and .NET Core 3.0.0-preview4.

https://gist.github.com/MaherJendoubi/d6e15a1da422dc33cb8b4d27916a5fe5

**Comment by NTaylorMullen** [comment]
Still working on fixing this :)

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/AspNetCore-Tooling/commit/cf474c97aa560268abc2334e12799c7c767e356f
