### ISSUE TITLE
Defining an alternative path for Blazor Cient hosted on Asp.Net Core

### ISSUE THREAD

**Issue by simonpbond** [aspnet/AspNetCore#9639]
Before upgrading to the latest version of Blazor, we were able to specify an alternative path for the Blazor client in Startup (when hosted on ASP NET Core):

```
Startup.cs (Server)
app.map("/app", subdirApp =>
{
app.UserBlazor<Client.Startup>();
});
```
We would then update the index.html file like so:
```
Index.html (Client)
<base href="app/">
```
Both **/app** and **app/** need to be in this format and are case sensitive.
This allows accessing the Blazor client site at: **localhost/app**    
   
However, trying to access a Blazor page at a URL such as **localhost/app/counter** only seems to route within the **_client side routing_,** and does not work when trying to access the URL directly (ie. hitting refresh in browser when at the given url)

It would be great to know why this no longer works and how to overcome the issue.

Thanks for any assistance in advance.

**Comment by danroth27** [comment]
@simonpbond I think you also need the leading slash in the base URL:

```
<base href="/app/">
```

**Comment by danroth27** [comment]
While we do our best to look through all the issues filed here, to get a faster response you might also try posting your questions to [StackOverflow](https://stackoverflow.com).

**Comment by simonpbond** [comment]
Thanks Dan, for anyone else experiencing an issue upgrading their project, this helped:
Having it in this order also allowed MVC and Blazor to work nicely.
```
Startup.cs (Server)
            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
            });
            app.UsePathBase("/app");
            app.UseBlazor<Client.Startup>();
```
and
```
Index.html (Client)
<base href="/app/" />
```
