### ISSUE TITLE
Blazor (client project) does not compile if cshtml file present in folder structure

### ISSUE THREAD

**Issue by tn-5** [aspnet/AspNetCore#9640]
### Describe the bug
It looks like the sdk uses the presence of a file with a ".cshtml" extension to detect that mvc is required. For a normal blazor project it then complains that:
The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore'

### To Reproduce
* dotnet new blazor
* create file "a.cshtml" with no content in root of project
* dotnet build fails

### Expected behavior
* Provide a more meaningful error message
* Allow the cshtml file to be excluded (currently if it is put in an itemgroup with build action=none it still has an effect, it should probably be ignored in those conditions)

Ideally what is required is any way (such as build action none in project file) to allow this file to be in the project structure but be ignored for the purposes of this.

**Comment by stefanjarina** [comment]
Hi,
I think we should use `.razor` instead of `.cshtml` file extension now.

At least this is in release notes for preview4:
```
New features in this preview release:

Templates updated to use the .razor file extension
_Imports.razor
...
```

Or is there still a need to use `.cshtml` and `.razor` together?

**Comment by tn-5** [comment]
The issue is not whether you use .razor or .cshtml. I understand that .razor is used for blazor. The issue is that there is no way to force the build system to ignore a specific file and not process it. Normally in VS if you tag a file with "build: none" it can stay part of the project file structure and will be ignored.

In our use case we have a dual client / server side project - we have one project file for the client side blazor project and one project file for the server side project. These are in same folder since it uses the same source files. The problem is that the server project requires the "_host.cshtml" for startup. If we compile the client project using this source structure it complains about the mvc error. If we delete or rename the file it works 100%. We can of course build this into the build scripts but fundamentally there needs to be a way to force a file to be ignored.

**Comment by danroth27** [comment]
In general we don't expect that Blazor to contain .cshtml files, but we can potentially look at making the experience better when you do.

**Comment by rynowak** [comment]
We definitely want to fail loudly by default if the project has something we don't understand.

You can exclude files like:
```
<ItemGroup>
  <Content Remove="Foo.cshtml" />
</ItemGroup>
```

**Comment by dylankdreyer** [comment]
I'm having a similar problem... I create a new Blazor solution using the Blazor extension.  Initially it builds and runs fine. and then if I make changes to any of the razor pages and then try to build and run it... I get errors telling me that " The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' for each razor page in the client project.... the client project is .net standard 2.0. I am stumped......
![image](https://user-images.githubusercontent.com/3283012/56655209-6bb82780-6692-11e9-9d3a-a7e6f4a5fffe.png)

**Comment by danroth27** [comment]
@dylankdreyer Can you share the csproj file for the project that is failing to build?

**Comment by HelvioMarkman** [comment]
I have the same problem, I created a API but when I add a new Page to the Pages Folder come the same error dylankdreyer shows above.

**Comment by HelvioMarkman** [comment]
I have tried cshtml and razor.

**Comment by HelvioMarkman** [comment]
Looks like first error is "_framework/blazor.webassembly.js File not found"

**Comment by libcitra** [comment]
The problem was also bothering me.
("MVC" dose not exit)
However, I solved the problem by re-installing the latest vsix from here.
https://github.com/aspnet/Blazor/releases

**Comment by LaughingJohn** [comment]
Same here. I just created a Blazor project using Visual Studio. It all compiles fine but as soon as I open Index.razor I get a bunch of errors. Mainly: 
The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore'
But also one of each:
'_Pages_Index_razor.ExecuteAsync()': no suitable method found to override
The name 'PageContext' does not exist in the current context

Clicking the errors does not navigate to any line of code.

**Comment by enricoreich** [comment]
Maybe you should consider to switch to VS 16.1preview2 for testing 3.0.0-preview4 blazor bits.

**Comment by jimmyheaddon** [comment]
I'm seeing these same errors with Visual Studio 2019 v16.0.3, having followed these instructions - https://devblogs.microsoft.com/premier-developer/exploring-blazor-with-visual-studio-2019/

Would VS16.1 preview 2 definitely fix this?

**Comment by danroth27** [comment]
@jimmyheaddon To use Blazor you need the latest Visual Studio preview: https://visualstudio.com/preview

**Comment by rynowak** [comment]
I'm not sure how this issue got placed in the backlog, but right now there's no action we're aware of that we need to take.

1. Make sure you are using the latest VS Preview (currently 16.2-preview1)
2. Make sure you have the lastest .NET SDK (currently 3.0-preview6)
3. Make sure you project has `<LangVersion>3.0</LangVersion>`
4. Check your project for any cases of `<Content Remove="Foo.razor" />`
5. If you have open documents that you renamed from `.cshtml` to `.razor` you may need to reopen them (we are investigating a fix for this)

We've seen a variety of reports here and none of them have lead to discovering any bugs. We've definitely heard that the migration experience with this preview was not smooth 😢 - we will do a better job documenting exactly what you need in the next release announcement.

If you are still having issues, please create a new issue and include your `.csproj` content as well as VS and `dotnet --info` output and we will try to help.

**Comment by MyShore** [comment]
I have the same issue.
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview7.19365.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview7.19365.7" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview7.19365.7" PrivateAssets="all" />
  </ItemGroup>

</Project>
![Errors](https://user-images.githubusercontent.com/46633234/62713551-99d53380-ba05-11e9-9056-8d2bab7ca124.png)
Adding any item with *.schtml extension implicates errors depicted in the above image.
My DotNet info:
![DotNet-1](https://user-images.githubusercontent.com/46633234/62714528-714e3900-ba07-11e9-9d1d-2459dc48f6eb.png)
![DotNet-2](https://user-images.githubusercontent.com/46633234/62714545-77441a00-ba07-11e9-9c1a-3f6d8d79e941.png)
![DotNet-3](https://user-images.githubusercontent.com/46633234/62714554-7ad7a100-ba07-11e9-8239-25dacc01c711.png)
I really appreciate any help you can provide.

**Comment by MyShore** [comment]
I have the same issue.
My Csproj content:
![Csproj](https://user-images.githubusercontent.com/46633234/62715685-a6f42180-ba09-11e9-8b32-d8dbbf763390.png)
Adding any empty item with *.cshtml extension implicates the following errors:
![Errors](https://user-images.githubusercontent.com/46633234/62715921-0eaa6c80-ba0a-11e9-84cc-93b3641b5f94.png)
DotNet infof:
![DotNet-1](https://user-images.githubusercontent.com/46633234/62716043-431e2880-ba0a-11e9-9f59-1d0933a24999.png)
![DotNet-2](https://user-images.githubusercontent.com/46633234/62716096-55986200-ba0a-11e9-9f5b-b49cc557147a.png)
![DotNet-3](https://user-images.githubusercontent.com/46633234/62716116-5af5ac80-ba0a-11e9-9674-1262eb6aa0c4.png)
I really appreciate any help you can provide.

**Comment by rynowak** [comment]
The answer is right here:

![image](https://user-images.githubusercontent.com/1430011/62716618-4b994380-b9b7-11e9-8c1e-ec9018cd60ad.png)

A Blazor client-side project doesn't include support for MVC views `.cshtml.

**Comment by MyShore** [comment]
Well, does it mean that I cannot add any Razor View page to my Blazor Client-side project? 
![AddingRazorViewPage](https://user-images.githubusercontent.com/46633234/62717724-1ae3f900-ba0d-11e9-93a1-6822527f723a.png)

**Comment by rynowak** [comment]
> Well, does it mean that I cannot add any Razor View page to my Blazor Client-side project?

Correct.

But what would that even mean? Razor Views are a server-side concept - they handle HTTP requests.

What do you ultimately want to accomplish?

**Comment by MyShore** [comment]
Really, I tried to understand what kind of project created in the video:
https://www.youtube.com/watch?v=bbHzyIsqGuU
![CreatingBlazorApplicationVideo](https://user-images.githubusercontent.com/46633234/62728423-6fdf3980-ba24-11e9-9ebf-db047c7a6c03.png)
Is this server-side project?

**Comment by rynowak** [comment]
No, that's a client-side webassembly project.

This is what I see: 

![image](https://user-images.githubusercontent.com/1430011/62728834-93c55f80-b9d1-11e9-8dba-b973d6517b4c.png)

What version of visual studio is that?

**Comment by MyShore** [comment]
In the mentioned video (https://www.youtube.com/watch?v=bbHzyIsqGuU), the VS version is unknown.  It is pointed out that the VS 2019 is running and that is all that was said about VS. A little later Razor View item is added without errors – the result, I cannot accomplish on my VS preview of the latest version.

**Comment by rynowak** [comment]
Does your VS have the `Blazor Server App` template in this list? That's the one you're looking for.

**Comment by MyShore** [comment]
Yes, it does. I'll try to use the Blazor Server App template.
Thank you so much for your attention and participation!
