### ISSUE TITLE
Cannot convert method group 'startsearch' to non-delegate type 'object'. Did you intend to invoke the method?

### ISSUE THREAD

**Issue by huto1** [aspnet/AspNetCore#9643]
I get this when calling on a method in `@@functions{}` from onclick in an elment. This happens in my web api projects, it's done exactly the same as in blazor template.

**Comment by SteveSandersonMS** [comment]
Can you please post repro code? Also specify the file name you’re using, and which template you used to create your project. 

My suspicion is that you’re trying to do this in a non-.razor file, which would not be supported.

**Comment by huto1** [comment]
I am using a non-.razor file. Where can I find some description on differences between those?

**Comment by SteveSandersonMS** [comment]
.razor files are components, which is what supports real-time interactivity (e.g. event handlers). 

.cshtml files are views or pages, which just render non-interactive HTML on the server.

We don’t have specific docs about syntactical/keyword differences, though it would be good if we did. cc @danroth27

**Comment by LaughingJohn** [comment]
![image](https://user-images.githubusercontent.com/305820/60333257-6f1ca780-9990-11e9-8326-e471a37528eb.png)

![image](https://user-images.githubusercontent.com/305820/60333301-8d82a300-9990-11e9-9e3f-34badd5ef844.png)

I appreciate this could be a pre-release thing, but I get this all the time, although everything works. My code looks like this:

<button onclick="@ShowHideWindow">Show/Hide Dialog</button>

**Comment by SteveSandersonMS** [comment]
`onclick` should now be `@onclick`. We made this syntax change in preview 6 - it's the final event-handler syntax for the 3.0 release.

**Comment by LaughingJohn** [comment]
Thanks Steve, that did the trick. I thought I'd tried that before and the event had stopped working, but it seems OK now, so probably just me!!

**Comment by Scobiform** [comment]
> `onclick` should now be `@onclick`. We made this syntax change in preview 6 - it's the final event-handler syntax for the 3.0 release.

can you explain why?

**Comment by SteveSandersonMS** [comment]
We made all the directive attributes (i.e. attributes that do C# things and aren't just HTML) have an `@` prefix to ensure they don't clash with current or future HTML attribute names, and so developers have an easy way to identify attributes that have special runtime behavior.

**Comment by tjorxwrynch** [comment]
> We made all the directive attributes (i.e. attributes that do C# things and aren't just HTML) have an `@` prefix to ensure they don't clash with current or future HTML attribute names, and so developers have an easy way to identify attributes that have special runtime behavior.

@SteveSandersonMS In the default template for a new Blazor (Client-Side) project, it would appear as though the syntax needs to be updated in the following line:
~~~~
 <button class="btn btn-primary" onclick="@IncrementCount">Click me</button>
~~~~
 within the Counter.razor page. Currently, intellisense will mark it as an error on a new project:

![image](https://user-images.githubusercontent.com/29150300/61376787-dd59d900-a86f-11e9-9e2e-2059059de7ef.png)

![image](https://user-images.githubusercontent.com/29150300/61376804-e8146e00-a86f-11e9-9f50-cadfbde03a96.png)


**This can be replicated by** opening up a new Blazor (Client-Side) project in Visual Studio, navigating to the "Counter.razor" file in the "Pages" folder, and opening it.

**I am using the following to replicate this:**

Visual Studio Microsoft Visual Studio Professional 2019 Preview
Version 16.2.0 Preview 3.0
VisualStudio.16.Preview/16.2.0-pre.3.0+29021.104
Microsoft .NET Framework
Version 4.8.03752

Apologies if it's annoying that I didn't just open a new issue for this. I wanted to reference this comment and ~~probably~~ definitely have a lot to learn about Github :) 

Furthermore, I would be happy to contribute to (seemingly) simple things like these once I learn how to navigate everything.

**Comment by SteveSandersonMS** [comment]
Thanks @tjorxwrynch for the suggestion!

The good news is that this change has already been made in the latest template source code: https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Templates/src/content/BlazorWasm-CSharp/Client/Pages/Counter.razor#L7
