### ISSUE TITLE
Ensure razor and cshtml files are watched for changes by dotnet-watch and VS

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9644]
Related to #9014

**Comment by pranavkm** [comment]
For VS, 

* RazorSDK needs to set `<UpToDateReloadFileTypes>$(UpToDateReloadFileTypes);*.cshtml;*.razor</UpToDateReloadFileTypes>` 
* Runtime compilation needs to remove this.

Do something similar for dotnet net watch.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb handing this off to you to help out @pranavkm with his load.
