### ISSUE TITLE
Razor: consider making LiveShareProjectPathProvider optional

### ISSUE THREAD

**Issue by KirillOsenkov** [aspnet/AspNetCore#9645]
For VSMac we don't have Live Share yet. We could implement a dummy LiveShareProjectPathProvider, but I thought it would be cleaner to make this an optional dependency via `AllowDefault = true` when importing a LiveShareProjectPathProvider.

This way Razor would be easier to host, less requirements from a host.

**Comment by KirillOsenkov** [comment]
@NTaylorMullen something we've discovered ^^

**Comment by mkArtakMSFT** [comment]
Thanks @KirillOsenkov.
@NTaylorMullen this is your to tackle.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/AspNetCore-Tooling/commit/115e416cdab678e6dd57211edb5eaab67366b6c2
