### ISSUE TITLE
ASP.NET Core Web Server Output in Dev16 does not work for 2.2 applications

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#9665]
The ASP.NET Core Web Server Output window in Visual Studio does not work for ASP.NET Core 2.2 applications

**Comment by scottsauber** [comment]
I hit this and assumed it was just a limitation of IIS being In-Proc.  Guess I should have filed a bug.

**Comment by jkotalik** [comment]
@anurse I can confirm this repros and would be something to consider in a patch. This requires a decent amount of investigative work.

**Comment by anurse** [comment]
If 3.0 works, I don't think we're going to fix this in 2.2 since it's EOL in December and the next scheduled patch is November.
