### ISSUE TITLE
Do not CaptureStartupErrors when running in IIS

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#9667]
We currently capture startup errors in Hosting when running in IIS- https://github.com/aspnet/AspNetCore/blob/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Servers/IIS/IIS/src/WebHostBuilderIISExtensions.cs#L33

We initially did this to prevent triggering rapid failure protection in IIS by crashing the worker process too often.

However, given that we now have https://github.com/aspnet/AspNetCore/pull/8518, we should stop capturing the exception in Hosting and let ANCM capture it instead. This ensures that the .NET Runtime will still log the exception message and stack trace to the event log. By capturing the exception in hosting, we prevent the runtime from logging this exception

**Comment by davidfowl** [comment]
When using the `WebHost` and `CaptureStartupErrors(false)`, the process exits, we should see why that is.

**Comment by bradygaster** [comment]
@anurse or @shirhatti - i don't see any milestones on this. is it slotted for a specific preview release?

**Comment by anurse** [comment]
We'll cover it in triage. I don't have any specific preview planned.

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: 3.0.100-preview6-012113
            * ASP.NET Core Runtime: 3.0.0-preview6-19279-01
            * .NET Core Runtime: 3.0.0-preview6-27728-04
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]

**Comment by jkotalik** [comment]
Actually, I think we didn't do this for Out of Process: https://github.com/aspnet/AspNetCore/blob/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Servers/IIS/IISIntegration/src/WebHostBuilderIISExtensions.cs#L81. It should be a small change. @anurse cool if I squeeze this into preview6?

**Comment by anurse** [comment]
Yep, no prob.
