### ISSUE TITLE
Stop buffering stdout in ANCM

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCore#9668]
We used to buffer the console output in ANCM to write to the EventLog in the event that an exception was thrown.
Now that we have https://github.com/dotnet/coreclr/pull/23054, we rely on the .NET runtime to log exceptions to EventLog for. There is no longer a need for us to buffer stdout in ANCM.

**Comment by shirhatti** [comment]
@davidfowl

**Comment by jkotalik** [comment]
We aren't doing this.
