### ISSUE TITLE
Blazor versioning in the future?

### ISSUE THREAD

**Issue by scottsauber** [aspnet/AspNetCore#9669]
Just curious as I just thought of this.  So Blazor is now aligned with ASP.NET Core 3.0 so it's 3.0 Preview 4 per the [announcement](https://devblogs.microsoft.com/aspnet/blazor-now-in-official-preview/) @danroth27 made.

> Also, since Blazor is now part of .NET Core, the client-side Blazor package versions now align with the .NET Core 3.0 versions. For example, the version number of all the preview packages we are shipping today is 3.0.0-preview4-19216-03. We no longer use separate 0.x version numbers for client-side Blazor packages.

What happens when ASP.NET Core 3.0 RTMs and client-side Blazor won't RTM (as is the current public plan)?  Is client-side Blazor going to continue to be 3.0 Preview <continue incrementing here> or go to some other versioning scheme?

This just randomly hit me so was wondering since versioning has been a point of confusion in the past.

**Comment by BenHayat** [comment]
I've also thought about that when I read Dan's comment on the versioning of Client, but client version won't RTM as ASP.Net Cor 3.

**Comment by SteveSandersonMS** [comment]
Any packages that aren't ready to RTM with the rest (i.e., client-side Blazor) will retain their `-preview` suffix in the version number.
