### ISSUE TITLE
IAsyncActionFilter for asp.net core signalR

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/AspNetCore#9670]
### Is your feature request related to a problem? Please describe.
For Asp.Net Core MVC, we could try `IAsyncActionFilter` to capture the action event and to calculate the action hanlding time, or handle something before and after processing the action.

For signalr, it supports `OnConnectedAsync` and `OnDisconnectedAsync` for connection event which will fire when connection start and disconnect.

I am wondering whether there is a similar functionality like actionfiler in aspnetcore, and then we could custom the lifecycle to do something before and after the action executes

**Comment by davidfowl** [comment]
Dupe of https://github.com/aspnet/AspNetCore/issues/5353. We don't have this yet but it's planned for a future release.
