### ISSUE TITLE
Improve error message for incorrectly configured authentication.

### ISSUE THREAD

**Issue by voroninp** [aspnet/AspNetCore#9671]
I'm am trying to setup authentication, but this part is not very well documented in the docs. The first and obviously wrong attempt yields:

> System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.

I believe this message is helpful mostly to those who know the details. Otherwise it does not add much clarity. [[1](https://stackoverflow.com/q/55794061/921054), [2](https://stackoverflow.com/q/52492666/921054)]

It would be much appreciated, if message contained not just reasons for error, but how to fix it as well.

For example:

> System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.
>
> Call either `AddAuthentication(string defaultScheme)` or `AddAuthenticate(Action<AuthenticationOptions> configureOptions)` to specify defaults. If you just called parameterless version of `AddAuthentication()` then schemes must be set ....(WHERE/HOW???)

**Comment by davidfowl** [comment]
Good idea! We should also beef up the docs here so its clearer.

**Comment by Eilon** [comment]
Let's see what we can improve in this scenario.
