### ISSUE TITLE
Directory.GetCurrentDirectory not correct in test project

### ISSUE THREAD

**Issue by jingliancui** [aspnet/AspNetCore#9675]
I have 2 projects , the one is another's test project
Now I have to read an image from `wwwroot/images`.
So i call `Directory.GetCurrentDirectory` first for read the project's directory.
Then i run the integration test( not unit test) project.
and its' Directory.GetCurrentDirectory result is the directory of the test project.
and i write this in the WebApplicationFactory's sub class still useless:
`builder
                .UseContentRoot(@"E:\TFSWorkspace\WorkspaceForDotNetDevCoder\DotNetDevCoder\Services\Identity\IdentityService")`

or  programs.cs:
`WebHost.CreateDefaultBuilder(args)
            .UseContentRoot(@"E:\TFSWorkspace\WorkspaceForDotNetDevCoder\DotNetDevCoder\Services\Identity\IdentityService")
                .UseStartup<Startup>();`

other info :
asp.net core 2.2 on windows vs 2017
and use this helper class for fix the Directory.GetCurrentDirectory [issue](https://stackoverflow.com/questions/54508735/directory-getcurrentdirectory-doesnt-return-the-correct-directory) which not get the right path from iis express

**Comment by jingliancui** [comment]
Temporarily copy the folder and content from wwwroot/images/someimg.png  to the integration test project.But i know it's still the bug its use `UseContentRoot` and `UseWebRoot` but useless in the `customize WebApplicationFactory` which still locale result of `Directory.GetCurrentDirectory` target to the bin folder of the integration test project.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jingliancui.
@javiercn  can you please answer this question? Thanks!

**Comment by javiercn** [comment]
Thanks for reaching out @jingliancui 

I'm not sure I understand your issue. Could you provide a repro project showcasing the issue?

**Comment by jingliancui** [comment]
ok I will upload sample code later.thanks

**Comment by jingliancui** [comment]
[WebSample.zip](https://github.com/aspnet/AspNetCore/files/3210438/WebSample.zip)

Today i use vs2019 to repeat the step and found that this issue https://github.com/aspnet/AspNetCore/issues/4206 fixed .

Then focus on the test project/Unitest1.cs and modify the path locale the code project or sln
```
            _factory = factory.WithWebHostBuilder(builder =>
            {
                //not work
                builder.UseContentRoot(@"D:\TempApps\WebSample\WebSample");

                //not work
                builder.UseSolutionRelativeContentRoot(@"D:\TempApps\WebSample");//.sln path

            }) as CustomWebApplicationFactory<Startup>;
```

Then Debug Test1(not debug webproject)
Then exception throw.

I can do trick now is to set property of the PrivateResources/cat1.png to `"copy if newer"` then vs will copy the file with path to the webproject when test run or debug.

other info:
`var projectRootDirectory = Directory.GetCurrentDirectory();`
in web project 's HomeController.ImageResource action.

So I don't know if is the bug with `UseContentRoot` and `UseSolutionRelativeContentRoot` methods
