### ISSUE TITLE
Connection Lost When Refresh (client-side)

### ISSUE THREAD

**Issue by muhammedMoussa** [aspnet/AspNetCore#9678]
in angular, i have one service manage signalr whole the app.
- at the top config connection withUrl, this fire this one time when home page run.
- then I've slices under this connection every one call it's hub, this fire only at the component which need it's slice.
- Problem: if app start from home to any page signal r works fine, BUT, if i got any route without fire home route first i have no connection, AND if i refresh any page connection lost again.. how to handle this, without call start connection slice every time when open any page?

**Comment by anurse** [comment]
Can you clarify your situation here? I'm assuming you have some client-side routing code that allows users to navigate around the app without actually requesting a new page? If that's the case, then yes, the connection stays open as the user navigates. However, if you allow users to enter your application from any page, you'll need to initialize the connection when the user first arrives, regardless of what page they enter on.

If you can provide a sample project that illustrates the problem you want to solve, that would help.

**Comment by muhammedMoussa** [comment]
@anurse, right, i solved it by change place of start connection slice, it was in place that's load before authorization done, so it was not working correctly.
