### ISSUE TITLE
PackageReference "Exact range, exclusive" is not working

### ISSUE THREAD

**Issue by cilerler** [aspnet/AspNetCore#9680]
### Describe the bug
PackageReference exclusive definition does not work correctly.  

> **_According to [Microsoft Docs](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards)_**
> _Notation `(1.0,2.0)` Applied Rule `1.0 < x < 2.0` Description `Exact range, exclusive`_

### To Reproduce

1. Confirm that you have **SDK 2.2.203** through `dotnet --info`
2. Create a new console project `dotnet new console`
3. Add a package with `dotnet add package Ruya.AppDomain`
4. Locate the error message `error: Unable to find package Ruya.Primitives with version (> 1.0.470)`
5. You may see the complete Ruya.AppDomain.csproj file [here](https://github.com/cilerler/ruya/blob/0676f0eb70c84fc2f169c458d2d440f828b3ed7d/src/Ruya.AppDomain/Ruya.AppDomain.csproj#L20)
6. Go to https://www.nuget.org/packages/Ruya.Primitives/
7. Locate that there is a version above 1.0.487 

![image](https://user-images.githubusercontent.com/385958/56580794-7777f100-65a1-11e9-9d60-1ff2132dea9f.png)

### Expected behavior
It should pick the correct version of the package _(Ruya.Primitives 1.0.487 in this case)_ correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/385958/56582060-6381be80-65a4-11e9-8e85-ad9b434de189.png)

### Additional context

output of `dotnet --info`

![image](https://user-images.githubusercontent.com/385958/56582264-dbe87f80-65a4-11e9-84d3-236a2c5cfbc3.png)

**Comment by Eilon** [comment]
Hi @cilerler , this appears to be a question about NuGet, so please post at https://github.com/nuget/Home/issues/ so that the NuGet team can take a look. Thank you!
