### ISSUE TITLE
Child components that are placed in different folder than the main page component are not rendered

### ISSUE THREAD

**Issue by jesiuu** [aspnet/AspNetCore#9682]
Child components that are placed in different folder than the main page component (with `@page` directive) are not rendered.

If I put the child component in the same folder as the page component, then it's rendered correctly.

### To Reproduce
1. Use the Blazor server-side template
1. Create new folder Components and create a Text.razor component in there with content:
`<p>This text should be rendered</p>`
1. In the Index.razor file include newly created component by adding:
`<Text />`
1. Run the app
1. Text "This text should be rendered" is not visible on the page.

### Expected behavior
Text "This text should be rendered" should be visible on the page.

### Screenshots
The folders structure in which the new component is not rendered:
![image](https://user-images.githubusercontent.com/1926292/56586944-ee80aa00-65e0-11e9-8eba-0866d13d39f7.png)

**Comment by cores-system** [comment]
Use `using`. display error is discussed here https://github.com/aspnet/AspNetCore/issues/9642

**Comment by jesiuu** [comment]
Thanks @cores-system, it worked. I also see that it's listed on known issues in [here](https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md#preview-4):
> Design-time errors in Visual Studio when using a component with child content from a component that lives in a different namespace
> This issue will be addressed in a future preview of Visual Studio. To workaround this issue, fully qualify the name of the child component

**Comment by SteveSandersonMS** [comment]
It’s not an error. If your tag doesn’t match any component, it’s regarded as HTML and rendered that way. We can’t know that’s not what you intended, since (for example) <MyComponent /> is perfectly legal markup. 

To be sure your component is recognised as in scope, watch out for syntax highlighting showing your tag as being a component and not just HTML.

**Comment by jesiuu** [comment]
Thanks, that makes sense @SteveSandersonMS . The only problem is that when you highlight that tag without having correct `@using` in place, Visual Studio will still tell you that it's your component, even though it's not, so it's quite misleading.

In the screenshot below you can see Visual Studio telling me that `<Text />` is a component from my project, but it's wrong because I didn't put needed `@using`, so after rendering I won't see the content. 

![image](https://user-images.githubusercontent.com/1926292/56622588-008a3900-6631-11e9-8e2c-3297ab69956a.png)

So in my opinion VS could change the formatting for that tag to make it look like this:

![image](https://user-images.githubusercontent.com/1926292/56622887-1fd59600-6632-11e9-97bf-e0f502349a98.png)
