### ISSUE TITLE
ASP.NET Core 2.2 stops serving local files after running for several hours

### ISSUE THREAD

**Issue by genifycom** [aspnet/AspNetCore#9684]
### Describe the bug
I created an ASP.Net Core 2.2 application using a Javascript file referenced as follows from a cshtml file.
    <script type="text/javascript" src="~/js/my-javascript-1.0.0.js"></script>

The app was published as the following:
dotnet publish -c Release -r linux-arm

The app runs perfectly on the Raspberry Pi Model 3B+ for several hours and refreshes the update page every 15 seconds.

After some time (last time was 6 hours), the page stops refreshing and the console log shows a 404 for localhost:5000/js/my-javascript-1.0.0.js

In fact, my tests show that any local static file (e.g. favicon.ico in wwwroot) will now give a 404.

Restarting the ASP.Net server fixes this behavior.

### To Reproduce
1. Create a refresh page using Javascript setinterval that refreshes a page
2. Run the ASP.Net server for some time
3. See if a 404 appears

### Expected behavior
The ASP.Net application should continue to run without changing behavior

### Additional context
I am checking for memory increases on the Pi to see if it is a memory leak issue

**Comment by Tratcher** [comment]
Do any non-static urls still work?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
