### ISSUE TITLE
Generic SignalR Messaging

### ISSUE THREAD

**Issue by endeffects** [aspnet/AspNetCore#9685]
My hub receives various types of domain events over a message bus.
These message types are shared for the blazor client and the service.

In the past it was possible to share the connection of different hub 
implementations for the client and for that reason it was easy
to group messages "contexts" by hubs.

With the current version of SignalR Core i'm not able to share the connection
for different hubs anymore. Merging all hubs into one seems not to be 
a good option, so i thought having a more generic message "contract"
could be a nice solution.

Which means, i wanna be able to send different message types with a marker interface
to the client where the deserializer picks the original (shared) type out of the message envelope.
I know that nobody likes to get back to a wcf contract, but with the new upcoming
blazor framework a better support of generics would be nice.

So a simple solution could be adding the original class type into the message envelope
and pass them internally to the deserializer.

Shared Types

```
	public class NotificationA : INotification
	{
		public Guid Id { get; set; }
	}
	
	public class NotificationB : INotification
	{
		public string Name { get; set; }
	}
```

Service

```
        public async Task Handle(INotification notification)
        {
            await this.hubContext.Clients.All.SendAsync("OnNotification", notification);
        }

```
Envelope (class added)

```
	Content: '{"type":1,"target":"OnNotification","class":"NotificationA","arguments":[{"id":"3a2efba3-594c-413a-a1c8-76e4b1bc5611"}]}'
	Content: '{"type":1,"target":"OnNotification","class":"NotificationB","arguments":[{"name":"Geronimo"}]}'
```

Client

```
        public async Task OnNotification(INotification notification)
        {
            await this.mediator.Publish(notification); // processing notification client side
        }

	private void RegisterForNotifications()
        {
            this.hubConnection.On<INotification>("OnNotification", this.OnNotification);
        }
```

There exist a related discussion that was closed a year ago:
https://github.com/aspnet/SignalR/issues/2325

**Comment by davidfowl** [comment]
This is serializer specific behavior, SignalR isn't involved here. When using JSON, you should be able to use the appropriate JSON options to preserve the type (like JSON.NET's type name handling). I'm not sure you can do this with messagepack.

cc @JamesNK for any advice here.

**Comment by JamesNK** [comment]
I don't know about message pack either. With Json.NET you can use type name handling, or just have a message that has a bag for data and a field to say the data's type.

```cs
public class GenericMessage
{
    public JObject Data { get; set; }
    public string Type { get; set; }
}

public Task DoTheThing(GenericMessage message)
{
    switch (message.Type)
    {
        case "Person":
            var person = message.Data.ToObject<Person>();
        // etc
    }
}
```

**Comment by endeffects** [comment]
Thanks for your advice. Well, I know it's suitable to wrap / envelope the generic message by my own and i did this before. But i don't like to wrap an existing wrapper, the HubInvocationMessage.

https://github.com/aspnet/SignalR/blob/c852bdcc332ffb998ec6a5b226e35d5e74d24009/src/Microsoft.AspNetCore.SignalR.Common/Protocol/HubMethodInvocationMessage.cs

So i thought, it's maybe possible to have a more comfortable way to get some details of the source type.
This could be enabled by configuration if required.

My current solution:

Generic Message

```
    public class Message
    {
        public Message(object value)
        {
            this.Value = value ?? throw new ArgumentNullException(nameof(value));

            var type = value.GetType();

            this.Type = $"{type.FullName}, {type.Assembly.GetName().Name}";
        }

        public object Value { get; }
        public string Type { get; }
    }
```

Message Converter

```
    public class MessageConverter : JsonConverter 
    {
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            var message = JObject.Load(reader);

            var messageType = message?["Type"]?.ToString();
            if (messageType == null) return null;

            var nestedType = Type.GetType(messageType);
            if (nestedType == null) throw new InvalidCastException("Message Type not found!");
            
            var nestedValue = message["Value"]?.ToObject(nestedType);

            return nestedValue;
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }

        public override bool CanConvert(Type objectType)
        {
            return true;
        }
    }

```
Test

```
    var message = new Message(new NotificationA { Id = Guid.NewGuid() });

    var json = JsonConvert.SerializeObject(message);

    var notification = JsonConvert.DeserializeObject<INotification>(json, new MessageConverter());

```

**Comment by anurse** [comment]
Agree with @davidfowl that this is a serializer configuration thing, rather than something SignalR itself should handle.

For JSON, @JamesNK 's example is great, using your own type field and then casting the rest of the payload itself.

For MessagePack, there are various options available. I'd suggest checking out the docs for the MessagePack library we use: https://github.com/neuecc/MessagePack-CSharp . For example, they have a concept of a ["union" type](https://github.com/neuecc/MessagePack-CSharp#union) that allows you to annotate an interface and have the implementation selected based on a discriminator field.

**Comment by endeffects** [comment]
Thanks for your feedback. I know it's easy to solve by wrap / envelope the messages by my own. But i really don't like to wrap an existing wrapper, the HubInvokationMessage. So i thought a more comfortable way to solve this would be to extend the existing implementation. I'm not saying this should be the default behavior, but for an blazor application that receives various events over the same hub connection would this a great improvement.

My current solution / workaround:

Service

```
        public async Task Handle(INotification notification)
        {
            await this.hubContext.Clients.All.SendAsync("OnNotification", notification);
        }
```

Envelope

```
        public class Message
        {
            public Message(object value)
            {
                this.Value = value ?? throw new ArgumentNullException(nameof(value));

                var type = value.GetType();

                this.Type = $"{type.FullName}, {type.Assembly.GetName().Name}";
            }

            protected Message()
            { }

            public object Value { get; protected set; }
            public string Type { get; protected set; }
        }
```

Client

```
        public async Task OnNotification(Message message)
        {
            var notification = MessageConverter.Convert<INotification>(message);
            await this.mediator.Publish(notification);
        }
```

Converter

```
    public static class MessageConverter 
    {
        public static TResult Convert<TResult>(Message message)
        {
           return (TResult)Convert(message);
        }

        public static object Convert(Message message)
        {
            if (message == null) throw new ArgumentNullException(nameof(message));

            var type = Type.GetType(message.Type);
            if (type == null) throw new InvalidCastException("Message Type not found!");

            var result = JsonConvert.DeserializeObject(message.Value?.ToString(), type);
            if (result == null) throw new JsonSerializationException("Message could not be deserialized!");

            return result;
        }
    }
```

**Comment by davidfowl** [comment]
> Thanks for your feedback. I know it's easy to solve this by wrapping the messages by my own. But i really don't like to wrap an existing wrapper, the HubInvokationMessage. So i thought a more comfortable way would be to extend the existing implementation. I'm not saying this should be the default behavior, but for a blazor application that receives various events over the same hub connection this would be a great improvement.

No matter what you do this is still serializer specific (as the implementation of IHubProtocols are). If you want to go deep, you can look at implementing a custom IHubProtocol to see if that helps.

How is Blazor related to this?

**Comment by endeffects** [comment]
Thanks, i'll check this out. Well with Blazor i'm able to share .net model libraries with the client, so it was a good example for knowing the source type.

**Comment by anurse** [comment]
> But i really don't like to wrap an existing wrapper, the HubInvokationMessage. So i thought a more comfortable way would be to extend the existing implementation.

There's nothing wrong with adding your own wrapper here. The HubInvocationMessage wrapper isn't designed for this, so if you need additional metadata, you should definitely use your own wrapper type. Nested wrappers are much more powerful than any attempt we could make at adding additional metadata to the HubInvocationMessage itself.

**Comment by endeffects** [comment]
Thanks for your Feedback. For now i‘ll stay with my current Solution and i‘ll have a look to write a custom protocol handler to prevent the double deserialization.
