### ISSUE TITLE
Errors when add namespace in ViewImports and 'System' folder exists

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [aspnet/AspNetCore#9689]
If _ViewImports.cs define 'namespace' and there is folder called 'System' within that or underlying level then all 'using System...' statements percieved as they are under defined namespace.

### To Reproduce
1. Create ASP.NET Core Web Application using ASP.NET Core '2.2' and Razor Pages
2. Create folder called 'System' into 'Pages'
3. Create any Razor Page (like Index.cshtml) with model (Index.cshtml.cs) inside 'System' folder.
4. See errors

### Expected behavior
No errors

### Screenshots
![image](https://user-images.githubusercontent.com/8963134/56603875-58ad4500-6609-11e9-8227-6d48a4968b6c.png)

### Additional context
I didn't check if same behavior occures with MVC approach or just in any .cs file where using any assembly within System namespace, but i think the reason will be obvious when reproduce.
Error observed in VS2019 Community and last VS Code

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/7823. See https://github.com/aspnet/Mvc/issues/7823#issuecomment-391835615 for possible workarounds.
