### ISSUE TITLE
InputSelect bind-Value or Value doesn't set selected value from model

### ISSUE THREAD

**Issue by cyberjaws** [aspnet/AspNetCore#9694]
Say I have a Model class that has a default value for an InputSelect such as :
```
public class DmsModel
    {
        [Required]
        public int Deg { get; set; }
        [Required]
        public int Min { get; set; }
        [Required]
        public int Sec { get; set; }
        [Required]
        public int Ms { get; set; }
        [Required]
        public string Direction { get; set; } 
    }

DmsModel _lon = new DmsModel { Direction = "W" };
```
and then want to use the model here:
```
<InputSelect class="custom-select" bind-Value="@_lon.Direction"> 
    <option value="E">E</option>
    <option value="W">W</option>                            
</InputSelect>
```
How can I set the selected item in the InputSelect? I have tried both bind-Value and Value tags and it always defaults to the first item in the option list.

**Comment by enetstudio** [comment]
Perhaps this may work:

 public string Direction { get; set; } = "W"

**Comment by cyberjaws** [comment]
Thanks for the suggestion! I simplified the example, however I am setting all the other fields the same way and their corresponding InputNumber tags populate with the default values correctly. I believe this is an issue with the InputSelect object.

**Comment by Andrzej-W** [comment]
I think it is tracked here #5616

**Comment by mkArtakMSFT** [comment]
Closing as a dupe.
