### ISSUE TITLE
Environment Variables is not overriding appsettings.* values

### ISSUE THREAD

**Issue by TrieBr** [aspnet/AspNetCore#9700]
### Describe the bug
According to the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#default-configuration), the order of configuration loading (by default) is the appsettings.* files, Secrets Manager, Environment variables and then command line arguments.

Furthermore, in the [Conventions](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#default-configuration) section, it mentions:

> If a value for the same key is set by the same or different configuration providers, the last value set on the key is the value used.

With these two pieces of information, I would expect to be able to override a variable defined in appsettings.Development.json with an environment variable since environment variables are loaded after and would be the "last value set". Maybe I'm just crazy, but I'm almost certain this behavior was working correctly previously. I had a project which suddenly stopped working recently because the environment variable was no longer having any effect. Nevertheless, this behavior doesn't seem to be consistent with what the documentation describes, or maybe I'm misunderstanding something.

### To Reproduce
1. Create a blank (API or MVC) ASP Core 2.2 project.
2. Add some sort of configuration object:
```
public class ApplicationSettings
    {
        public string SomeProperty { get; set; }
    }

```

3. In `ConfigureServices`, inject the configuration into the DI:

```
services.Configure<ApplicationSettings>(Configuration.GetSection("AppSettings"));
```

4. Add the following into your appsettings.Development.json:
```
 "AppSettings": {
    "SomeProperty":  "Hello World" 
  },
```

5. In `Configure` function in `Startup.cs` output the value of the configured field. This will output "Hello World".
```
var settings = app.ApplicationServices.GetService<IOptions<ApplicationSettings>>();
            Console.WriteLine(settings.Value.SomeProperty);
```

6. Add an environment variable called `ASPNETCORE_AppSettings__SomeProperty` with the value `Show Me!`.

7. Run the program again. Using a breakpoint or the printed message you can see `SomeProperty` is still `Hello World`. 

(The next two steps simply demonstrate that the environment variable indeed works, but only when there isn't the same property contained in the appsettings file)

8. Remove `"SomeProperty":  "Hello World" ` from appsettings.Development.json

9. The value of SomeProperty is now 'Show Me!'.

### Expected behavior
Environment variable should override anything in the appsettings.* files according to the documentation.

### Additional context
```

.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.100-preview2-009404 [C:\Program Files\dotnet\sdk]
  2.2.100-preview3-009430 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009748 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009804 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview2-35157 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview2-35157 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview2-26905-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27014-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

```

**Comment by Eilon** [comment]
@HaoK - any idea on this?

**Comment by davidfowl** [comment]
Try removing the ASPNETCORE_ prefix.

**Comment by TrieBr** [comment]
@davidfowl removing the prefix worked. Perhaps this is just a documentation issue then. The documentation isn't entirely clear that `ASPNETCORE_` behaves differently than other prefixes and is only called for the host configuration, and not app configuration:

> AddEnvironmentVariables is automatically called for environment variables prefixed with ASPNETCORE_ when you initialize a new WebHostBuilder. For more information, see Web Host: Set up a host.

> The Environment Variables Configuration Provider is called after configuration is established from user secrets and appsettings files. Calling the provider in this position allows the environment variables read at runtime to override configuration set by user secrets and appsettings files.

The above paragraphs gave me the understanding that `ASPNETCORE_` variables are always applied after the appsettings files.

**Comment by anurse** [comment]
There is this documentation on [host vs. app configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#host-vs-app-configuration) furthur up the page. It might be a good idea to link that in the below section you cited though.

**Comment by anurse** [comment]
I filed https://github.com/aspnet/AspNetCore.Docs/pull/12775 to clarify this documentation.

**Comment by anurse** [comment]
The docs PR is merged, so the docs will be updated. Closing now as we don't believe there is any further action to take.
