### ISSUE TITLE
[blazor] minify dlls

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/AspNetCore#9702]
Is it possible to make minified versions for blazor's common dlls, e.g. mscorlib.dll?

Decompilation shows that it contains unnecessary data, e.g. method and parameters infos

![aaa](https://user-images.githubusercontent.com/40779557/56617702-89cc4c00-65ee-11e9-808b-2b1f68731520.png)

Do we really need this large summaries?

Also can we use some minification techniques to make size smaller?
For example shortening variable/method/field/class names.

We can have regular and minified versions and use them relatively regular for developing and minified for production.
If minification breaks reflection or serialization code developer will decide not to use minified versions.

Does linker do things like this?

I was playing with mono.cecil and did parameter renaming for mscorlib.dll methods with minimum lengh names and got some small improvement in size, without affecting anything and blazor continued work as expected.

I believe we can reduce dlls if implement techniques from web world which concentrates on efficient traffic.

I think dlls size was not so important before blazor and because this it never got aggressive optimization, but now because load time is critical for blazor and dlls should be downloaded each time, size needs to be optimized with all possible ways.

**Comment by danroth27** [comment]
We already run the IL linker to do static analysis to strip out unneeded IL. To give feedback on the current behavior of the IL linker please open an issue on the https://github.com/mono/mono repo.

**Comment by benaadams** [comment]
Opened https://github.com/mono/linker/issues/552
