### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by zanate4019** [aspnet/AspNetCore#9705]
### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Expected behavior
to launch application

### Screenshots
![500 30](https://user-images.githubusercontent.com/10452739/56624468-98bafa80-65fe-11e9-88cf-75bb9dd1f301.png)

### Additional context
Include the output of `dotnet --info`
Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524
.NET Core SDKs installed:
  No SDKs were found.
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Also ran through the troubleshooting steps at 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.2#50030-in-process-startup-failure

Attaching the acm
[ancm.log](https://github.com/aspnet/AspNetCore/files/3110074/ancm.log)

stdout is blank

**Comment by zanate4019** [comment]
Tried installing the SDK so the dotnet info now looks like this:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.203\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.203 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by davidfowl** [comment]
@zanate4019 did you look in the event log?

**Comment by zanate4019** [comment]
Yes, nothing really useful

Application '/LM/W3SVC/2/ROOT' with physical root 'D:\Program Files\ARA Development\Box Workflow G3\' failed to load clr and managed application. CLR worker thread exited prematurely

Since it was also mentioned in the ancm log, I didnt mention it.

Side note:  The same application has been deployed on a WIndows 2008 R2 server and is working fine.

**Comment by zanate4019** [comment]
Tried to moving it to Out of Process and saw a SQL access error in the event log.  Moved it back to In-Proc and changed the account on the AppPool and now its running.  I think our custom logging engine (ported from PODF - "plain old dotnet framework"), must not be using the correct creds.  Thanks for your help

**Comment by DimaSUN** [comment]
ASP.NET Core 2.2 or later: For a 64-bit (x64) self-contained deployment that uses the in-process hosting model, disable the app pool for 32-bit (x86) processes.

In the Actions sidebar of IIS Manager > Application Pools, select Set Application Pool Defaults or Advanced Settings. Locate Enable 32-Bit Applications and set the value to False. 

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0#create-the-iis-site
