### ISSUE TITLE
onclick method does not work

### ISSUE THREAD

**Issue by huto1** [aspnet/AspNetCore#9714]
No matter what I do, the onclick event does not work. I am using .razor file for this.

```
    <div><button   onclick="@testmethod">top</button>
    </div> 
@functions{
    public string tst { get; set; }
   
    public void testmethod()
    {
        tst = "testttt";
    }
}
```

**Comment by danroth27** [comment]
It looks like the error is coming from the Bootstrap javascript code, so this doesn't look like a Blazor issue. To get help on figuring out what's going on I would suggest posting additional details on what you're trying to do on [StackOverflow](https://stackoverflow.com).

**Comment by huto1** [comment]
It has nothing to do with the bootstrap, I shouldn't have posted that error output. If I remove bootstrap there will be no errors, but it still does not work.

**Comment by danroth27** [comment]
Can you share your project with us? Is this a client-side or server-side Blazor app?

**Comment by huto1** [comment]
original the template was API, I think. But, I added server side blazor in startup, then I created cshtml view, in which the .razor file was rendered, up to that point everything works perfectly. The problem is with the click. It all seemed like a good idea, but I think it is not yet ready to be tested in any realistic environment.

**Comment by danroth27** [comment]
@huto1 Which browser are you testing with?

**Comment by enetstudio** [comment]
@huto1: It all seemed like a good idea, but I think it is not yet ready to be tested in any realistic environment.

Yes, you've got a good idea...why don't you try it first in plain HTML page, and see if it works for you. Sorry, but I want allow you to disparage this awesome SPA framework.

**Comment by huto1** [comment]
@danroth27 I was using MX5, but then also tried on opera and edge. If I open the blazor template project, that will run fine on MX5.

**Comment by danroth27** [comment]
> If I open the blazor template project, that will run fine on MX5.

OK, that would suggest there's something not quite right with the way you setup your own project. If you can share the project with us, or the steps needed to reproduce the issue, we can take a look.

**Comment by huto1** [comment]
I will see how much I can publicly share.

**Comment by danroth27** [comment]
@huto1 Can you also please check if the blazor.server.js file is successfully downloaded to the browser in your app and that the websocket connection to the server gets established successfully?

**Comment by huto1** [comment]
I think the blazor.server.js might be the problem here, it does return 404 response.

**Comment by tomasoplt** [comment]
The reason is <body> tag inside your HTML code ( layout page or body page ) If you remove body tag, OnClick events will work.
