### ISSUE TITLE
UriHelper.GetAbsoluteUri() does not return hash

### ISSUE THREAD

**Issue by Suchiman** [aspnet/AspNetCore#9717]
### Describe the bug
In 3.0 Preview 3, `UriHelper.GetAbsoluteUri();` used to return the URL you can see in the browser. Starting in Preview 4, it cuts off everything after, including `#arg1=...`

### To Reproduce
1. Create a fresh Server Side Blazor Project.
2. Add Code in `Index.razor` to print the result of `UriHelper.GetAbsoluteUri()`
3. Open `http://localhost:port/#hello`
4. The Code will only print `http://localhost:port/`

### Expected behavior
The AbsoluteUri includes the hash

**Comment by SteveSandersonMS** [comment]
Turns out this is already working as expected. For details, see #12422.

**Comment by Suchiman** [comment]
Odd, seems that has changed recently again though.
In my original usecase, i was using the OAuth2 Implicit grant which meant that i would receive the access token as a hash parameter like `http://app/auth#access_token=abcde123` and starting with preview 4, this didn't seem to work anymore. I could have sworn i've tried `OnAfterRender` without success, but with preview 8 bits, this seems to work fine.
