### ISSUE TITLE
Using Identity for multiple web applications

### ISSUE THREAD

**Issue by LeonidasFettikus** [aspnet/AspNetCore#9719]
I am trying to design a way to handle authentication AND role-based authorization across multiple web apps. I have taken a look at Identity Server and it seems that it doesn't do role-based authorization well. At least it's much more complex to set up than just using .Net Identity. Because of this, I decided to just use Identity and come up with a way for it to handle multiple applications.

Here's an example:

![image](https://user-images.githubusercontent.com/8888670/56676684-265e1f00-66bf-11e9-99d0-b07a827f421a.png)

As you can see, I have 3 web applications here. All share the same Identity database and they all have identity set up. The main difference is, the Blog and IoT applications only authorize against the database while the UserManagement application actually handles the creation of users, roles and their relationships.

My question is, is this a viable approach or will I regret it down the line? I don't really need anything else other than authentication and role-based authorization. I don't really want to deal with tokens, claims and other stuff.

**Comment by brockallen** [comment]
> I have taken a look at Identity Server and it seems that it doesn't do role-based authorization well. 

it's not designed to, and it's debatable if you should want it to: https://policyserver.io/

**Comment by blowdart** [comment]
Hi. It looks like this is a question about how to use  ASP.NET Core. This really isn't suitable for github as its asks for opinions. We suggest posting your questions to   [StackOverflow](https://www.stackoverflow.com).  

Please consider tagging your StackOverflow question with  asp.net-core and/or asp.net-core-mvc.

(I'm also with Brock in saying the industry has moved on from roles)
