### ISSUE TITLE
React to changes in Microsoft.NETCore.App

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspNetCore#9720]
As a part of FrameworkReference refactoring, the packaging structure for Microsoft.NETCore.App will be changing to split into several packages. https://github.com/dotnet/core-setup/issues/4775 We need to update aspnet repos to consume the new package IDs.

- [x] aspnet/Extensions - https://github.com/aspnet/Extensions/pull/1828
- [x] aspnet/AspNetCore-Tooling
- [x] aspnet/AspNetCore
- [x] aspnet/EntityFrameworkCore
- [x] aspnet/EntityFramework6

The new package IDs:

* Microsoft.NETCore.App.Ref
* Microsoft.NETCore.App.Runtime.$(Rid)

**Comment by JunTaoLuo** [comment]
FYI for the crossgen parts, we need to update at least:
https://github.com/aspnet/AspNetCore/blob/e4328b2a96564758ca12d47d07549923ce83b9a6/eng/Dependencies.props#L172-L180
https://github.com/aspnet/AspNetCore/blob/1b500858354efe26493af632bf0e3f5462dc6246/src/Framework/src/Microsoft.AspNetCore.App.Runtime.csproj#L115

**Comment by natemcmaster** [comment]
Waiting on https://github.com/dotnet/core-setup/issues/4775 from core-setup

**Comment by natemcmaster** [comment]
Initial PR - https://github.com/aspnet/Extensions/pull/1828. If this is the right change (waiting for review from others), then it needs to be applied to all repos listed in the issue above.

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] Let's just say, the product wouldn't build if this didn't work.
