### ISSUE TITLE
Q: [Blazor] How can I change background color of Razor syntax in VS2019?

### ISSUE THREAD

**Issue by BenHayat** [aspnet/AspNetCore#9726]
In Vs2019, when we write Razor code VS2019 applies a dark gray background which makes the code harder to read in dark theme. How can I remove this BG color?

I checked in the Options|Fonts&Color, but couldn't find any reference.
Thanks!

**Comment by rjmr97** [comment]
Tools > Options > Environment > Fonts and Colors
Display Items: HTML Razor Code Background

![image](https://user-images.githubusercontent.com/30321188/56696483-df365500-66e3-11e9-92fa-e5b58a5e9c12.png)

**Comment by BenHayat** [comment]
@rjmr97 ;

Thank you Ricardo; Looks so much better
I missed it on the list as it was prefixed with HTML and I was searching for Razor.
Ended up fixing a few other color issues too.

**Comment by NTaylorMullen** [comment]
@rjmr97 thanks for the assistance!
