### ISSUE TITLE
DateTime-Local is not honoring the 24-hour conversion to AM/PM

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore#9727]
### Describe the bug
Using Blazor client/server, the binding for control type datetime-local is not converting the 24-hour format in DateTime object to the AM/PM format required by the UI control. If 16:45 is entered for time, it is being converted to 04:45 AM but should be 04:45 PM.

### To Reproduce
```
<input type="datetime-local" id="Test" name="Test" class="form-control" bind="@testDateTime" format-value="yyyy-MM-ddThh:mm" />
<small class="form-text text-muted">@testDateTime</small>

@functions {
    DateTime testDateTime { get; set; } = new DateTime(2019, 12, 15, 16, 45, 15);
}
```

### Expected behavior
Time in the input control should match the time shown in the <small> tag above. 

### Additional context
Project Type: Blazor Client-Server
Visual Studio 16.1.0 Preview 2
Microsoft.AspNetCore.Blazor 3.0.0-preview4-19216-03
Microsoft.AspNetCore.Blazor.Build 3.0.0-preview4-19216-03
NETStandard.Library 2.0.3

**Comment by Andrzej-W** [comment]
Try to change your `format-value` string to "yyyy-MM-ddTHH:mm" (uppercase letters H). Value of input element is represented in ISO format (24-hour clock). Value is displayed accoording to your operating system settings.

**Comment by VR-Architect** [comment]
You are awesome! That worked. Thanks.
