### ISSUE TITLE
Azure Web App FileLoadException at Microsoft.AspNetCore.WebHost+

### ISSUE THREAD

**Issue by flatproject** [aspnet/AspNetCore#9733]
### Describe the bug
App hosted on Azure Web App crashes every night and not being able to recover after upgrade to 2.2.4.

The error i get is:
```
There is an issue with your application code. Exceptions found: at Microsoft.AspNetCore.WebHost+<>c.<CreateDefaultBuilder>b__8_2(Microsoft.AspNetCore.Hosting.WebHostBuilderContext, Microsoft.Extensions.Logging.ILoggingBuilder) at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action1<Microsoft.Extensions.Logging.ILoggingBuilder>) at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(System.AggregateException ByRef) at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build() at V8.Web.Program.Main(System.String[]) - Please check your d:\home\LogFiles\eventlog.xml
```

and the eventlog.xml

```
<Data>
Application: V8.Web.exe Framework Version: v4.0.30319 Description: 
The process was terminated due to an unhandled exception. Exception Info: System.IO.FileLoadException 
at Microsoft.AspNetCore.WebHost+<>c.<CreateDefaultBuilder>b__8_2(Microsoft.AspNetCore.Hosting.WebHostBuilderContext, Microsoft.Extensions.Logging.ILoggingBuilder) at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action`1<Microsoft.Extensions.Logging.ILoggingBuilder>) at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(System.AggregateException ByRef) at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build() at V8.Web.Program.Main(System.String[])
</Data>
```

Why do i get these exceptions? They all seem to happen around 5-6am UK time.

My Program.cs looks like this:

````
internal class Program
    {
        protected Program()
        {
        }

        public static void Main(string[] args)
        {
            var host = BuildWebHost(args);

            using (var scope = host.Services.CreateScope())
            {
                var services = scope.ServiceProvider;
                try
                {
                    var root = (IConfigurationRoot) host.Services.GetRequiredService<IConfiguration>();

                    root.Reload();
                }
                catch (Exception ex)
                {
                    var logger = services.GetRequiredService<ILogger<Program>>();
                    logger.LogCritical(ex, "An error occurred while reloading configuration");
                }
            }

            host.Run();
        }

        public static IWebHost BuildWebHost(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .UseKestrel(opts => { opts.AddServerHeader = false; })
                .ConfigureAppConfiguration((builderContext, config) =>
                {
                    var readyConfig = config.Build();

                    var sqlConnection = readyConfig.GetConnectionString("V8Connection");
                    config.AddDbConfig(options => options.UseSqlServer(sqlConnection));

                    readyConfig = config.Build();

                    var keyVaultUrl = readyConfig["V8Settings:KeyVaultUrl"];
                    if (!string.IsNullOrEmpty(keyVaultUrl))
                    {
                        var azureServiceTokenProvider = new AzureServiceTokenProvider();
                        var keyVaultClient = new KeyVaultClient(
                            new KeyVaultClient.AuthenticationCallback(
                                azureServiceTokenProvider.KeyVaultTokenCallback));

                        config.AddAzureKeyVault(keyVaultUrl, keyVaultClient, new DefaultKeyVaultSecretManager());
                    }
                })
                .UseStartup<Startup>()
                .ConfigureLogging(logging =>
                {
                    logging.AddApplicationInsights();
                    logging.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Warning);
                })
                .Build();
        }
    }
````

**Comment by Tratcher** [comment]
Is there message text for the FileLoadException?

**Comment by flatproject** [comment]
All I can find in the telemetry is the below:

> 

Event time | 25/04/2019, 06:36:09 |  
-- | -- | --
Message | Hosting startup assembly exception Could not load file or assembly 'Microsoft.AspNetCore.AzureAppServices.HostingStartup' or one of its dependencies. The system cannot find the file specified. |  
Exception type | System.IO.FileNotFoundException |  
Failed method | System.Reflection.RuntimeAssembly._nLoad |  
Problem Id | System.IO.FileNotFoundException at System.Reflection.RuntimeAssembly._nLoad |  
Assembly | mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 |  
Severity level | Critical |  
Telemetry type | exception |  
Application version | 1.0.0.0 |  
Device type | PC
AspNetCoreEnvironment | Production |  
{OriginalFormat} | Hosting startup assembly exception |  
CategoryName | Microsoft.AspNetCore.Hosting.Internal.WebHost |  
EventId | 11


And the Call Stack:

> System.InvalidOperationException:
System.IO.FileNotFoundException:
   at System.Reflection.RuntimeAssembly._nLoad (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Reflection.Assembly.Load (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices (Microsoft.AspNetCore.Hosting, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)



If i can supply you with any further information please let me know.

**Comment by davidfowl** [comment]
This exception should not terminate the process, it should be caught and logged. So if it is crashing the process then there might be something else going on. Are you running on .NET Framework? (It looks like yes from the call stack).

Install this into your project to https://www.nuget.org/packages/Microsoft.AspNetCore.AzureAppServices.HostingStartup/2.2.2 and this specific exception should go away.

On the main app service page, click on **Diagnose and Solve problems**:

![image](https://user-images.githubusercontent.com/95136/56836994-b7530880-682d-11e9-94ac-7498620a97ed.png)

Then click Diagnostic Tools

![image](https://user-images.githubusercontent.com/95136/56837020-cdf95f80-682d-11e9-8784-bf4df6549eb7.png)

Then click Application Events

![image](https://user-images.githubusercontent.com/95136/56837044-e2d5f300-682d-11e9-9778-d85145160d3f.png)

Tell me if there's anything in the logs there.

**Comment by flatproject** [comment]
Yes the app is on net471.

I have installed HostingStartup and you are right that specific exception has gone away.

The Appplication Events has this Error at the time of the application crash which is the same as in my first post from the eventlog.
```
Application: V8.Web.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at Microsoft.AspNetCore.WebHost+<>c.b__8_2(Microsoft.AspNetCore.Hosting.WebHostBuilderContext, Microsoft.Extensions.Logging.ILoggingBuilder)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action`1)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(System.AggregateException ByRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at V8.Web.Program.Main(System.String[])

```

**Comment by davidfowl** [comment]
Can you give me more data? Show me the screen shot of the viewer and with this exception selected.  I’d also like to see if there’s anything else in there.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by vpaulino** [comment]
Hi there. I have the same issue. I have follow @davidfowl advice to install that nuget but another exception happen:

This are the logs that happen in my application when it starts in the Web App Service: 

===> 2019-08-27 10:31:43.091 +00:00 [Information] Startup.ConfigurationServices starting
===> 2019-08-27 10:31:50.247 +00:00 [Information] ConfigurationServices is finished with sucess
===> 2019-08-27 10:31:50.270 +00:00 [Information] Hosting environment: Cloud
===> 2019-08-27 10:31:50.278 +00:00 [Information] OS: Microsoft Windows 10.0.14393  Framework: .NETCoreApp,Version=v2.2
===> 2019-08-27 10:31:51.898 +00:00 [Information] Startup.Configure starting
===> 2019-08-27 10:31:54.735 +00:00 [Information] Startup.Configure finished with sucess
===> 2019-08-27 10:31:55.398 +00:00 [Error] Unexpected exception in IISHttpServer.HandleRequest.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.GetOriginalPath()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.InitializeContext()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.HandleRequest(IISHttpContext context)
===> 2019-08-27 10:31:55.937 +00:00 [Warning] Failed to determine the https port for redirect.

I have this settings on my csproj regarding framework and hosting model: 

```

 <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
```

I have the following nugets installed in my aspnet core 2.2 csproj: 
```

 <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    
<PackageReference Include="Microsoft.AspNetCore.AzureAppServices.HostingStartup" Version="2.2.2" />
    
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.2.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.2.2" />
    
    <PackageReference Include="Microsoft.AspNetCore.Server.IIS" Version="2.2.6" />
    
    <PackageReference Include="Serilog.AspNetCore" Version="2.1.1" />
    
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    
    <PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />

    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
```
On my application startup ConfigureService I have this to support IIS Deploy scenarios: 

 ```
services.Configure<IISServerOptions>((options) =>
            {
                options.AutomaticAuthentication = false;
            });

            services.Configure<IISOptions>((options) =>
            {
                options.ForwardClientCertificate = false;

            });
```
On my application startup configure method I 'm also calling these methods:

```
 app.UseHsts();
app.UseHttpsRedirection();
 app.UseMvc();

```
On the environment I have two extensions installed: 

![image](https://user-images.githubusercontent.com/859157/63766691-a8579200-c8c3-11e9-80de-983b34bc69ea.png)

My application event log in azure is this one:
![image](https://user-images.githubusercontent.com/859157/63766822-e6ed4c80-c8c3-11e9-972c-97eedb2ad8d4.png)

**Comment by DAllanCarr** [comment]
This is a closed issue.

That said you should be able to disable the redirect middleware and let the front ends where the SSL/TLS is configured handle it.
