### ISSUE TITLE
Protractor consider signalr connection as a pending request and waits infinetelly

### ISSUE THREAD

**Issue by pavelpykhtin** [aspnet/AspNetCore#9735]
### Describe the bug
I'm running e2e tests with protractor against angular2+ application. I'm using browser.waitForAngularEnabled(true) to ensure that application is stable (no running animations, no pending requests and etc.) before the next step of test.
At some point test stops because protractor considers application state as unstable.
I found that the issue is related to these particular lines:
```JavaScript
this.zone.runOutsideAngular(() => {
    this.started = this.connection
        .start()
        .then(_ => {
            console.log('[signaler] started');
            this.isStarted = true;
            this.connection.on(
                'notify',
                (messageType: string, signal: Signal) => {
                    signal.messageType = messageType;
                    this.zone.runGuarded(() => this.signalsSubject$.next(signal));
                }
            );
        })
        .catch();
});
```
When I comment/remove this.connection.start test runs whitout problems again.
Though connection.start is wrapped with runOutsideAngular call signalr connection is considered as a pending request and thus blocks protractor from continuing the spec.

### To Reproduce
1. Create a angular app that connects to signalr endpoint.
2. Create a protractor spec with waitForAngularEnabled(true) specified.
```JavaScript
describe('protractor with typescript typings', () => {
    it('should greet the named user', async () => {
        await browser.waitForAngularEnabled(true);
        await browser.sleep(2000); //wait until signalr started

        await $('button').click(); //Click a button but only when all pending tasks are done
   }
});
```
3. Propractor stucks on line await $('button').click() as it thinks that signalr connection is a pending http request that must finish first. After a while (200 seconds by default) test is halted.

### Expected behavior
It is possible to start signalr connection outside angular's zone.

### Additional context
Test output:
```
Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:427:11)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)
  Message:
    Failed: script timeout: result was not received in 200 seconds
      (Session info: chrome=73.0.3683.103)
      (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)
```

Related issue in protractor's repo:
#https://github.com/angular/protractor/issues/4300

**Comment by anurse** [comment]
How frequently is your `notify` callback called? My initial investigation shows that as long as all the operations you perform on the connection are done within `runOutsideAngular`, the callbacks should all be fired outside Angular's Zone and the Zone becomes stable.

Perhaps if you can post a sample project that reproduces the issue it would be easier to understand the issue you're seeing. Are you able to try not waiting for angular (i.e. https://github.com/angular/protractor/blob/ed955e56a839d7f69da43acb6755763220d3681d/docs/timeouts.md#how-to-disable-waiting-for-angular)? Does the issue still repro when you remove that synchronization?

Also, do you **create** the connection inside `runOutsideAngular`?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
