### ISSUE TITLE
Microsoft.AspNet.WebApi.Core 5.2.7 is not compatible with .NET Core 2+

### ISSUE THREAD

**Issue by SaeidSabzalizadeh** [aspnet/AspNetCore#9746]
I tried to install nuget package [Microsoft.AspNet.WebApi.Core] in 
.NET core Class library 2.0, 2.1, 2.2 and .NetStandard 2.0 and I got an error in all of them:

`Package 'Microsoft.AspNet.WebApi.Core 5.2.7' was restoring using '.NETFramework, Version=v4.6.1' instead of targeting framework '.NETCoreApp, Version=v2.1'. This package may not be fully compatible with your project.
`

**Comment by Sevall** [comment]
Yaaa yeter Bee devamlı ileti ileti abonelik den cıkartın ileti almak istemiyorum nereden bulastım size d
Tlf hiç susmadı
--
Android için Outlook Email App uygulamasından gönderildi Perşembe, 25 Nisan 2019, 05:04ÖS +03:00 gönderen: Saeid Sabzalizadeh  notifications@github.com :

**Comment by davidfowl** [comment]
Why are you trying to install WebApi into a .NET/.NET standard class library?

**Comment by SaeidSabzalizadeh** [comment]
> Why are you trying to install WebApi into a .NET/.NET standard class library?

I'm trying to add customAuthorize attribute
 `public class MyAuthorizeAttribute: System.Web.Http.AuthorizeAttribute`

Which I know it just used in .NetFramework projects but still need to keep all the Authorization attributes in one library.

Furthermore I don't see any restriction in the nuget package. I assume it should be supported.

**Comment by davidfowl** [comment]
> Furthermore I don't see any restriction in the nuget package. I assume it should be supported.

No it isn't support. The error says it's .NET Framework only and it is.

> I'm trying to add customAuthorize attribute
public class MyAuthorizeAttribute: System.Web.Http.AuthorizeAttribute
> Which I know it just used in .NetFramework projects but still need to keep all the Authorization attributes in one library.

https://stackoverflow.com/questions/31464359/how-do-you-create-a-custom-authorizeattribute-in-asp-net-core

Assuming you want to use ASP.NET Core.

**Comment by SaeidSabzalizadeh** [comment]
> > Furthermore I don't see any restriction in the nuget package. I assume it should be supported.
> 
> No it isn't support. The error says it's .NET Framework only and it is.
> 
> > I'm trying to add customAuthorize attribute
> > public class MyAuthorizeAttribute: System.Web.Http.AuthorizeAttribute
> > Which I know it just used in .NetFramework projects but still need to keep all the Authorization attributes in one library.
> 
> https://stackoverflow.com/questions/31464359/how-do-you-create-a-custom-authorizeattribute-in-asp-net-core
> 
> Assuming you want to use ASP.NET Core.

That's not my case, I want to use .NETFramework.

**Comment by davidfowl** [comment]
> That's not my case, I want to use .NETFramework.

I see, then you need to use a .NET Framework class library. 

PS: This repository is for ASP.NET Core specifically.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
