### ISSUE TITLE
Backport #6075 to 2.2 - NullReferenceException in IISHttpContext 

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#9749]
We've had some requests to backport the fix for https://github.com/aspnet/AspNetCore/issues/6075 to 2.2.x. This issue is tracking a possible backport (will need to be approved by shiproom).

**Comment by anurse** [comment]
Closing this because we think there are a few more cases. We want to solve this in 3.0 before backporting. Filed https://github.com/aspnet/AspNetCore/issues/9873.

**Comment by bartdk-be** [comment]
@anurse : Any idea when a fix will be available for 2.2 ?
Can we check link these issues to a realease notes site ?

**Comment by anurse** [comment]
No word yet, but we'll be doing some looking at it soon. I'll re-open this to track that :).

**Comment by anurse** [comment]
Putting this in a 3.0 milestone to keep it on our radar. Right now we have some higher priority 3.0 work to get this in. Also, this is *fixed* in the coming 3.0 release (in September) and 2.2 goes end-of-life in December, so we'll be using that to evaluate the prioritization here.

**Comment by anurse** [comment]
Given that the fix is coming in 3.0 which ships in September and the next 2.2 patch is targeting September, backporting doesn't feel valuable here. Plus, 2.2 will be end-of-life in December of this year.
