### ISSUE TITLE
Port to 2.1: JsonResult causes thread pool exhaustion via synchronous flushes aspnet/Mvc#8486

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9762]
https://github.com/aspnet/Mvc/issues/8486

There isn't a very good workaround for this and the code fix is fairly trivial.

**Comment by pranavkm** [comment]
cc @mkArtakMSFT

**Comment by clavecoder** [comment]
@pranavkm, We seem to have the same symptoms as #8486 but we're using .NET 2.2. This issue shows as Open but #8486 seems to indicate a patch in 2.2 that fixes it. Does this problem exist in .NET 2.2? Is it fixed in 3.0?

**Comment by pranavkm** [comment]
@clavecoder 

* In 2.1, using `JsonResult` always results in a synchronous Flush on the Response Stream. This is the cause of the thread pool starvation that this issue is intended to fix.
* 2.2 resolves the issue with sync flushes. However, in both 2.1 and 2.2, a JSON payload that's larger than 64k result in synchronous writes which result in the same behavior as this issue. 
* 3.0 resolves both these issues. The System.Text.Json based serializer is async and does not perform sync writes. With the Json.NET based serializer, we buffer the entirety of the response in memory before writing to the response.

**Comment by mkArtakMSFT** [comment]
Closing as this is not approved for servicing. Please use one of the provided workarounds or update to a later version of the framework.
