### ISSUE TITLE
Blazor (client side) "dotnet run" does not respect "outputpath" settings in project file

### ISSUE THREAD

**Issue by tn-5** [aspnet/AspNetCore#9770]
### Description
The output folder in dotnet can be set in the project file using a combination of "outputpath", "baseoutputpath" etc. settings. This can be used to change the location of the generated binaries from the default "bin" project subfolder.

In preview 4 the `dotnet build` command respects this and it generates the binaries in the correct location.
However when running with `dotnet run` it expects the binaries in the default `bin` folder and fails with `Cannot find bin directory for Blazor app`

### To Reproduce
* `dotnet new blazor`
* Edit csproj file and add `<BaseOutputPath>test</BaseOutputPath>`
* `dotnet build` -> builds and generates binaries in `test` subfolder
* `dotnet run` -> error, cannot find binaries in `bin` folder

This only happens with the client side blazor template.

### Expected behavior
`dotnet run` should look for binaries in the same folder as used to build

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tn-5.
This is a known issue and we track this at https://github.com/aspnet/AspNetCore/issues/6623
