### ISSUE TITLE
asm.js fallback, please...

### ISSUE THREAD

**Issue by GoranHalvarsson** [aspnet/AspNetCore#9772]
It seems that the fallback asm.js is removed(in latest blazor release). Is there a reason for this?
I think it's good idea to put it there. Safari(Apple) can suddenly do some critical changes, to not support webassembly. They did this for not so long ago, then they turned it on again... I think it's a good idea to have the fallback asm.js.

**Comment by binki** [comment]
The asm.js fallback also enables supporting IE11 (with the help of polyfills) at all. It was reportedly working in https://github.com/aspnet/Blazor/issues/654 .

**Comment by binki** [comment]
Looks like it was dropped in https://github.com/aspnet/Blazor/commit/4006cd543900fcc1cf76cd75a1b24007e60c8a67 with the reasoning being that the binary distribution of mono includes wasm but not asm.js.

**Comment by danroth27** [comment]
Thanks for answering, @binki!
