### ISSUE TITLE
MaxLengthAttribute added to Textarea by default

### ISSUE THREAD

**Issue by LukaszBalazy** [aspnet/AspNetCore#9776]
Removing CompatibilitySwitch<T> in [f113a20](https://github.com/aspnet/AspNetCore/commit/f113a20dfd9d0c7c991e425fd8000ed6b64d19a5#diff-efb2475852eb61aeb367882891a7757eL740) creates textarea with maxlength attribute which prevents user to paste more characters and receive configured error message.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run this code:
`       [DataType(DataType.MultilineText)]
        [MaxLength(4500)]
        public string Test { get; set; }`

`<textarea asp-for="@Model.FurtherDetails"></textarea>`
3. User is unable to paste more then characters in MaxLengthAttribute which is automcatically converted to maxlength html attribute.

### Expected behavior
Switch to either add maxlength attribute to html element or prevent it from rendering which would display error message to span element and display it.

**Comment by mkArtakMSFT** [comment]
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.
