### ISSUE TITLE
Unable to get startup parameters when windows service starts

### ISSUE THREAD

**Issue by okman523** [aspnet/AspNetCore#9777]
### Describe the bug
After deploying the asp.net core project as a windows service, I started the project with (Get-Service "ServiceName").Start(@("--tag=dev")), but the args parameter in the Program.Main method is not. Get "--tag=dev", what is the reason?
### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`

**Comment by davidfowl** [comment]
Arguments aren't supported, this isn't something that works with the current windows service support.

@okman523 Can you fill in the other information please? Like version information?

cc @glennc @Tratcher

**Comment by glennc** [comment]
How are you verifying that you don't get the args in Program.Main?

**Comment by davidfowl** [comment]
I believe OnStart has args. They don’t get passed into main

**Comment by Tratcher** [comment]
So it does:
https://github.com/aspnet/Extensions/blob/1112d7bcb46fb5848f29a84cb3f906f75c07c8bc/src/Hosting/WindowsServices/src/WindowsServiceLifetime.cs#L64
The trouble is that we've already built and 'started' the app, it's just paused waiting for the go signal. At best you could give some kind of reloadable config provider, but most components don't check for config changes.

**Comment by okman523** [comment]
@davidfowl I need to get the command line parameters in Main, as the parameters needed for the program initialization, it is too late to get the parameters in OnStart, it means nothing to me.

**Comment by okman523** [comment]
@Tratcher  Yes, this is not reasonable, it is right to get the parameters when the program starts.

**Comment by Tratcher** [comment]
Here's an interesting thread:
https://stackoverflow.com/questions/1488851/how-to-pass-a-parameter-to-a-windows-service-once-and-for-all-at-install-instead

There are two places to put parameters:
1. In the image path: `myapp.exe options`. These get passed to Main
2. In StartService, these get passed to ServiceBase.OnStart.

There's nothing for us to do here, this is just how Windows Services work. Can you try the image path approach?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
