### ISSUE TITLE
Empty Template is missing AddRouting()

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#9791]
The empty template is missing a call to `AddRouting()` so it doesn't start :(

**Comment by Eilon** [comment]
Preview5?

**Comment by rynowak** [comment]
Nevermind. This is not broken https://github.com/aspnet/AspNetCore/blob/master/src/DefaultBuilder/src/WebHost.cs#L227

The default host does this.

----

The explantion is that I started with the empty template, and then I changed Program.cs to not use the default builder.
