### ISSUE TITLE
Unknown html tags raise no warning.

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/AspNetCore#9799]
### Is your feature request related to a problem? Please describe.
When one is missing an import for a Component, the tag is just rendered into the HTML. Which may be fine and desired but when not it is hard to find them.

### Describe the solution you'd like
I would like a setting that can enable "Unkown HTML tags": severity: warning.

### Describe alternatives you've considered
Manually looking for them in the editor.  Or running app and look for missing pieces.

**Comment by conficient** [comment]
Related to #9786

**Comment by mkArtakMSFT** [comment]
Thanks @conficient.
This is indeed a dupe of the referenced issue
