### ISSUE TITLE
[Blazor] Missing events from intellisense

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#9802]
### Describe the bug
Some events are missing from intellisense and they seem to generate a bit different output in the `.razor.g.cs` file, although the code compiles and seems to be working,

Some of the events that I have noticed misbehaving are: `onpointermove`, `onpointerup`, `onpointerdown`, `onpointercancel`, `ongotpointercapture`, `onlostpointercapture`. Please look at the provided screenshot for more details.

### Screenshots
![image](https://user-images.githubusercontent.com/12549761/56847962-58ec5f80-68eb-11e9-87e9-d350434a8373.png)

**Comment by rjmr97** [comment]
I don't know why but it seems the events are `pointermove`, `pointerup`, `pointerdown`, `pointercancel`, `gotpointercapture `and `lostpointercapture` without the "on" word.

In my opinion they should all have the "on" prefix.

Sources:
https://github.com/aspnet/Blazor/issues/763
https://github.com/aspnet/Blazor/pull/765

**Comment by danroth27** [comment]
This should be fixed in Preview5 (see #7570).
