### ISSUE TITLE
Model binding to a complex type from Route Data

### ISSUE THREAD

**Issue by nfplee** [aspnet/AspNetCore#9809]
Hi, I'm trying to invoke an action and feed a complex type into the parameters. For example say I say:

```csharp
var newHttpContext = _httpContextFactory.Create(ViewContext.HttpContext.Features);
var routeData = new RouteData();

routeData.PushState(null, new RouteValueDictionary(new { parameters = new CustomParameters {
    Foo = "Bar"
} }), null);

var actionDescriptor = _actionDescriptorCollectionProvider.ActionDescriptors.Items
    .FirstOrDefault(i => i.RouteValues["Action"] == "Custom" && i.RouteValues["Controller"] == "Parameters");

var actionContext = new ActionContext(newHttpContext, routeData, actionDescriptor);

var invoker = _actionInvokerFactory.CreateInvoker(actionContext);

await invoker.InvokeAsync();
```
To invoke the following method:

```csharp
public class ParametersController : Controller {
    public IActionResult Custom(CustomParameters parameters) {
        return View(parameters);
    }
}
```

This invokes the method correctly, however the parameters are null. I found the following issue:

https://github.com/aspnet/Mvc/issues/5833

The suggested model binder fixed this. However as they mentioned this doesn't play kindly with the ComplexTypeModelBinder. Unfortunately I cannot comment on that issue so I thought I would create a new one.

From my understanding the suggested model binder will override the ComplexTypeModelBinder and now all my forms which post back a complex view model are broken (the parameter is set to null). I'd appreciate it if someone could let me know how I can modify the model binder so it doesn't break the ComplexTypeModelBinder.

I don't get why this isn't built into the framework. I've seen multiple people with a similar problem and this used to work fine in ASP.NET MVC.

**Comment by nfplee** [comment]
I managed to achieve this with the following model binder and provider:

```cshtml
public class RouteDataComplexTypeModelBinder : IModelBinder {
    private readonly IModelBinder _complexTypeModelBinder;

    public RouteDataComplexTypeModelBinder(IModelBinder complexTypeModelBinder) {
        _complexTypeModelBinder = complexTypeModelBinder;
    }

    public async Task BindModelAsync(ModelBindingContext bindingContext) {
        if (bindingContext.ActionContext.RouteData.Values.TryGetValue(bindingContext.ModelName, out var value))
            bindingContext.Result = ModelBindingResult.Success(value);
        else if (_complexTypeModelBinder != null)
            await _complexTypeModelBinder.BindModelAsync(bindingContext);
    }
}

public class RouteDataComplexTypeModelBinderProvider : IModelBinderProvider {
        private readonly IModelBinderProvider _complexTypeModelBinderProvider;

        public RouteDataComplexTypeModelBinderProvider(IModelBinderProvider complexTypeModelBinderProvider) {
            _complexTypeModelBinderProvider = complexTypeModelBinderProvider;
        }

        public IModelBinder GetBinder(ModelBinderProviderContext context) {
            if (context.Metadata.IsComplexType && !context.Metadata.IsCollectionType)
                return new RouteDataComplexTypeModelBinder(_complexTypeModelBinderProvider.GetBinder(context));

            return null;
        }
    }
```

This is then registered like so:

```cshtml
options.ModelBinderProviders.Insert(0, new RouteDataComplexTypeModelBinderProvider(options.ModelBinderProviders.Single(provider => provider is ComplexTypeModelBinderProvider)));
```

It basically provides the custom model binder with the complex type model binder as a fallback. Whilst this works for now. I feel this should be built in to the framework (not necessarily implemented this way).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nfplee.
Glad you've found a way to resolve this. Since we don't have any plans to do any additional work here closing this issue.
