### ISSUE TITLE
Microsoft.AspNetCore.JsonPatch is not netstandard any more

### ISSUE THREAD

**Issue by springy76** [aspnet/AspNetCore#9812]
Since 3.0 preview2 Microsoft.AspNetCore.JsonPatch is only available for netcoreapp3.0, before it was for netstandard2.0.

I'm using this in a net472 WPF client app - should I use another package on client side? Which?

**Comment by davidfowl** [comment]
What types were you using?

**Comment by springy76** [comment]
I'm using `JsonPatchDocument<T>` to build the patch which gets posted using Flurl or HttpClient.

**Comment by mkArtakMSFT** [comment]
@glennc what should we do here?
