### ISSUE TITLE
WebException: Unable to complete handshake with the server due to an error: Handshake was canceled

### ISSUE THREAD

**Issue by krychaszek** [aspnet/AspNetCore#9818]
Hello,

We are currently using .Netcore.SignalR version 1.1.0 both on our external server and in our Unity game on client side.
We have everything working on PC platform with scripting backend IL2CPP, however when we build for PS4 after 15 seconds of connecting we are getting an error stating that handshake with our server was canceled:

"HubException: Unable to complete handshake with the server due to an error: Handshake was canceled."

That's really weird situation, because regular build with IL2CPP scripting backend on PC works fine, so we think that it is something platform specific that is stopping us from connecting with our server.

I didn't find any information about using real-time communication using SignalR on PS4. Are there any limitations of this solution we are not aware of?

If anyone knows how to fix this issue we would be very grateful.

Thanks very much

**Comment by BrennanConroy** [comment]
This is not a scenario we have ever tried so you're more of an expert in it than we are.

The best we can offer is tips on debugging the issue.

Try to get a network trace and client + server logs. The handshake canceled error you're seeing is from the server, saying that the client didn't send a handshake response within 15 seconds. So you should check to see if the client has sent the handshake, and if it has, was it the correct payload or did it send the incorrect payload. And did the server receive the handshake if the client did send it?

**Comment by anurse** [comment]
Our docs have some information about how to collect logs and diagnostic info. I'm not sure how well they will transfer to running on PS4 :).

https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2

**Comment by krychaszek** [comment]
Hello,

Thank You for your help, we've finally managed to resolve our issue. After analysing Wireshark capture it turned out that the handshake packets are send to server, however it takes about 21 seconds on Playstation4 to fully connect with the Hub. By default in .Netcore SignalR handshake timeout is set to 15 seconds. After setting timeout time to a little bit bigger value everything works as it should.

Regards,
Marcin

**Comment by anurse** [comment]
That's good to know! Thanks for the update :). I'll close this for now. I don't think we want to update our default timeout right now, but it's good to know that updating that config works for you! If you run in to anything that we could do to make things work better, let us know!
