### ISSUE TITLE
Question: aspnetcore netsh self hodted appid to allow http add sslcert ipport=x.x.x.x:yyyy certhash= appid=

### ISSUE THREAD

**Issue by generik0** [aspnet/AspNetCore#9821]
Hi

When registering the https sert for net framework wcf window services it was easy to:

- netsh http add sslcert ipport= certhash= appid=

The appId is the guid in the executing assembly  AssemblyInfo.

Question:

Can we do the same with aspnetcore self-hosted (as windows service).
if so, There is no Guid in the new csporj format. What do we add to the project file to add the Guid/Appi id for the host?

I know there is:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#endpoint-configuration.  But this only references using the stores. 
We deploy our product on many servers with different certs, domains and names. and therefore the "http add sslcert" is best

is the appid as simple as adding:
![image](https://user-images.githubusercontent.com/2411563/56898148-99d1a900-6a90-11e9-9978-50a494f2fdc2.png)

Best Regards @generik0

**Comment by blowdart** [comment]
AppID isn't linked to your app, it's just an identifier so you can use it to identify the binding later, if you want. 

You can use any GUID you'd like,

**Comment by generik0** [comment]
Hi @Blowdart

Well call me a newbie...
Strange, last time we changed our guid for our net framework host, the netsh didn’t work until I change it to the Assembly Guid...

Please tell me then, how can I use the guid in the aspnetcore application, so it is linked to the binding?

If it is a link, I would expect the aspnetcore app need to know the guid for the link?

**Comment by blowdart** [comment]
That's super weird, I don't believe there is any real connection here. If, for example, I look at the default bindings we create as part of the SDK install;

```
    IP:port                      : 0.0.0.0:44397
    Certificate Hash             : a774dd1f4944a95baa94f9a143095a90b1b437ab
    Application ID               : {214124cd-d05b-4309-9af9-9caa44b2b74a}
    Certificate Store Name       : MY

```

Now, if that required an app id in a core application then VS wouldn't be able to run ASP.NET Core apps, because, as you point out, there's not concept of an application ID any more. All kestrel cares about is the port number.

What errors are you getting on your app servers when you try to run your kestrel hosted apps?

**Comment by generik0** [comment]
Hi @blowdart.
Ok, maybe Its just me WHO is seeing ghosts.
I will be putting our new aspnetcore microservice on our dev and test server with https. 
Can we leave the question open until the start of next week?

I still dont understand what the AppId is for in the netsh, If it isnt used for anything :-/

**Comment by blowdart** [comment]
I think it was for manually mapping ports/configs to apps, if you wanted to keep your own records. 

Sure, we'll leave it open, I'll pop it into the discussions milestone.  Please @ me once you've tried it out.

**Comment by generik0** [comment]
Hi @blowdart 
Deployment day.

![image](https://user-images.githubusercontent.com/2411563/57020976-48a9ec80-6c2b-11e9-8238-726c0b793106.png)

even though cert registered:

![image](https://user-images.githubusercontent.com/2411563/57021020-6b3c0580-6c2b-11e9-8dee-5fe21aaade14.png)

![image](https://user-images.githubusercontent.com/2411563/57020994-5a8b8f80-6c2b-11e9-9a2f-839be5d03781.png)

What is missind that the kestrel links the port to the cert?

I have tried with;

```json
"Kestrel": {
    "EndPoints": {
      "Https": {
        "Url": "https://*:9091"
      }
    }
  }
```

and

```json
"Kestrel": {
    "EndPoints": {
      "HttpsDefaultCert": {
        "Url": "https://localhost:5003"
    },
    }
  }
```


Any thoughts? 
on https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#endpoint-configuration i don't see how to link to a certhash :-/

**Comment by blowdart** [comment]
You can manually retrieve it via the X509Certificate2 class and set it with httpsOptions.ServerCertificate, or you pass in the store and subject name in UseHttps. We don't do thumbprints because that doesn't allow for certificate rollover, unlike subject names.

Or you set the host name in the bindings and it'll get it based on that.

Setting the host name is much safer than listening on *, we've had MSRC cases around wildcard configurations and I don't recommend them.

**Comment by generik0** [comment]
@blowdart This is our dev serv. just trying to get it to work right now. Hence "Url": "https://*:9091"

What do you mean by: "Or you set the host name in the bindings and it'll get it based on that."

**Comment by generik0** [comment]
@blowdart the **netsh** used to "just work" with net framework console/services. its a big shame that it doesn't for aspnetcore!

**Comment by blowdart** [comment]
"Kestrel": {
    "EndPoints": {
      "HttpsDefaultCert": {
        "Url": "https://localhost:9091"
    },
    }
  }

This would look for a certificate that matches localhost.

**Comment by blowdart** [comment]
netsh is of course rather windows specific, and is only usable with http.sys. You could go back down that route, if you wanted a slower host :)

**Comment by generik0** [comment]
@blowdart 
Just to be clear. This is the appsettings that should be used:

"HttpsInlineCertStore": {
      "Url": "https://localhost:5002",
      "Certificate": {
        "Subject": "<subject; required>",
        "Store": "<certificate store; defaults to My>",
        "Location": "<location; defaults to CurrentUser>",
      }
    }

**Comment by blowdart** [comment]
That's what I'd go for. @halter73 do you have any better suggestions?

**Comment by generik0** [comment]
@blowdart 
It works. But its going to be a settings hell for us with all our urls / deployments..

Dammit. Build hell..

Any thoughs to improving this?

![image](https://user-images.githubusercontent.com/2411563/57026195-79911e00-6c39-11e9-91c0-a9f813602545.png)

**Comment by blowdart** [comment]
You can bind to * but have your own middleware that rejects host names you don't expect. In config you'd load the cert before the binding and pass it in as an X509Certificate2 instance

**Comment by generik0** [comment]
Thanks @blowdart. Will close for now.
Will think about it all.
Please let me know if you guys have other ideas :-)
