### ISSUE TITLE
[Blazor] Move Blazor FAQ content from aspnet/Blazor to this repo.

### ISSUE THREAD

**Issue by RyotaMurohoshi** [aspnet/AspNetCore#9824]
### Is your feature request related to a problem? Please describe.

`Blazor` sources and issues for Blazor have moved from aspnet/Blazor to aspnet/AspNetCore, this repo.

By the way, there is no FAQ content for `Blazor` in this repo.

But it is in old repo, aspnet/Blazor.

see : https://github.com/aspnet/Blazor/wiki/FAQ

### Describe the solution you'd like

How about move [FAQ](https://github.com/aspnet/Blazor/wiki/FAQ) content from from aspnet/Blazor to aspnet/AspNetCore, this repo.

### Describe alternatives you've considered

Or how about put FAQ content in official page.

### Additional context

[Awsome Blazor](https://github.com/AdrienTorris/awesome-blazor) has FAQ link to old aspnet/Blazor repo.

**Comment by danroth27** [comment]
Thanks for this suggestion @RyotaMurohoshi! To avoid breaking links to the existing Blazor FAQ we prefer to leave it where it is. However, all of the relevant content from the original Blazor FAQ should now be covered by the [Blazor docs](https://blazor.net/docs).
