### ISSUE TITLE
SignalR .NetCore 3.0-- HubConnectionBuilder' does not contain a definition for 'WithUrl' 

### ISSUE THREAD

**Issue by Grey007** [aspnet/AspNetCore#9827]
### Describe the bug
Hi, 
I'm trying to create a HubConnection on a Console App, but getting an error with .WithUrl. 

Receiving the following error: 

> HubConnectionBuilder' does not contain a definition for 'WithUrl' and no accessible extension method 'WithUrl' accepting a first argument of type 'HubConnectionBuilder' could be found

My code: 
```
using Microsoft.AspNetCore.SignalR.Client;

    class Program

    {

        public static async Task Main(string[] args)

        {

            var connection =  new HubConnectionBuilder()

           .WithUrl("https://localhost:44386/NotificationHub")

           .Build();

            await connection.StartAsync();
            while (true)
            {
                try
                {
                    await connection.StartAsync();

                    break;
                }
                catch
                {
                    await Task.Delay(1000);
                }
            }

            Console.WriteLine("Client One listening. Hit Ctrl-C to quit.");
            Console.ReadLine();
        }
    }
}
```

**Comment by BrennanConroy** [comment]
What does your .csproj look like?

**Comment by Grey007** [comment]
Yeah, looks like that was the issue. Just a comment, I followed a prompt from VS19 suggesting I install that Microsoft.AspNetCore.SignalR.Client.Core. 

Thanks for the help!

**Comment by BrennanConroy** [comment]
Was this prompt a `ctrl-.` on `HubConnectionBuilder` in the editor?

**Comment by Grey007** [comment]
Yeah,

**Comment by anurse** [comment]
Unfortunately the `HubConnectionBuilder` type **is** in that package (`Client.Core`), but the `WithUrl` extension method is in `Client`. There isn't really a way to tell VS to suggest a different package (though that could be an interesting idea for the future).

`Ctrl-.` on the `WithUrl` method itself might have offered the right package.

Out of curiocity, did you look at a doc or tutorial before starting? Most of [our docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2) should be referring to the correct package, but if you followed a different reference (or even if you followed one of our docs and missed the package ID) that's useful information for us in helping others avoid confusion :)

**Comment by davehutton** [comment]
I got confused by which version I needed to install. Not sure if that would catch anyone else
http://assets.gocreative1.net/wp-content/uploads/sites/38/2019/11/signalrVersionConfused.jpg
