### ISSUE TITLE
Invoke MVC ViewComponent with generic type parameter

### ISSUE THREAD

**Issue by ajruckman** [aspnet/AspNetCore#9828]
### Is your feature request related to a problem? Please describe.
I would like to be able to invoke a Razor Pages ViewComponent with a generic type parameter. For example, I want to be able to pass any List to a component, like this:
```csharp
public Task<IViewComponentResult> InvokeAsync<T>(List<T> data)
{
    ...
    return Task.FromResult<IViewComponentResult>(View("Default", new ComponentConfig { }));
}
```
and to somehow call the component in a .cshtml file:
```csharp
@await Component.InvokeAsync<Schema.Schema.VM>("ListTable", new {data = Model.AuditResult})
```
but I don't know where the type specifier would go in the .cshtml file.

### Describe alternatives you've considered
Using an "object" type instead of a generic list parameter. But this isn't very clean.

<details><summary>below is kindof a different issue but maybe it's relevant; if this worked, I might not need generic parameters</summary>

I tried to ensure that the 'object' passed is any type of List with a function like [this](https://stackoverflow.com/a/17190236/9911189):
```csharp
public bool IsList(object o)
{
    if(o == null) return false;
    return o is IList                &&
           o.GetType().IsGenericType &&
           o.GetType().GetGenericTypeDefinition().IsAssignableFrom(typeof(List<>));
}
public Task<IViewComponentResult> InvokeAsync(object data)
{
    if (!IsList(data))
    {
        throw new Exception("component parameter is not a list");
    }
    ...
    return Task.FromResult<IViewComponentResult>(View("Default", new ComponentConfig { }));
}
```
but this function doesn't work; it seems like the 'object' is a:
```
<>f__AnonymousType1`5[System.Collections.Generic.List`1[Schema.Schema+VM],System.String,System.Boolean,System.Boolean,System.String]
```
rather than a `System.Collections.GenericList`; maybe Razor is modifying the 'object' or something, or maybe I misunderstand how generics work.
</details>

**Comment by enetstudio** [comment]
Razor component is actually a Blazor component. You meant ViewComponent, right ? Language is the source of misunderstandings...

**Comment by ajruckman** [comment]
Yes you are right, my bad... I will edit it.

**Comment by rynowak** [comment]
Hi @ajruckman  - we don't have support for using generics in View Components.

**Comment by ajruckman** [comment]
Hi @rynowak, I was pretty sure that was the case so that's why I thought I should use the feature request template.

Do you think there is any possibility of having generic View Components in the future? If not I will understand but I think they could be very powerful. 

Thank you!

**Comment by rynowak** [comment]
It's really unlikely that we'll add this as a feature to view components since we consider that feature area pretty much **done**. 

What would help us understand the need for this more would be an example of seeing where `T` is used. For instance, we've had many requests for open generics for views over the years, and generally the requirements that are presented in those requests don't really align with generics. 

Most of the infrastructure we provide for **output** (views/action results) uses the runtime type of the object. So having a base class (or using `object`) is just as good for producing **output**.

**Comment by ajruckman** [comment]
I have pretty much solved all of the problems I had when I opened this issue with `object` and `dynamic` types. I'm sure this is a very niche use case but I will still try to explain why generic components would make what I want to do easier and safer.

I define classes that act as schema for things I want to display on a page. Each property has multiple attributes that define how it should be displayed. Here is a sample:
```c#
public class Change
{
        [Contexts(Context.List, Context.Form, Context.Info)]
        [HiddenIn(Context.Form)]
        [ReadOnly]
        public int ID { get; set; }

        [Contexts(Context.List, Context.Form, Context.Info)]
        [InputType(InputTypes.Select)]
        public string Type { get; set; } = null!;

        [Contexts(Context.Info)]
        [DisplayName("Type Description")]
        public string TypeDescription { get; set; } = null!;
}
```

One use case I have for generic components is that I want to pass a `List<Change>`, which I get from a database query, to a component, and iterate over the rows in it to display an HTML table. Right now, I accept an `object` in my component, which I ensure is an `IEnumerable`. Then I use reflection to get the class of elements in the List, instantiate a new instance of that class with `Activator.CreateInstance`, iterate over all the properties in the instance, and iterate over all the attributes in each property. This way, I can translate the attributes in the class to define how the class should be displayed based on the given context (List, Info, Form, Select...).

With generics, I wouldn't have to use reflection to get the class of elements in the List, and then create a new instance of that class.

I have other classes like `Change`, such as `Facility`, `Property`, `Purchase`, etc.. I want to be able to display any of these classes in a list by passing a list of them to my List component. With generics, I wouldn't have to accept an `object`, so my code could be verified at compile time, to make sure I'm passing the right thing to my components. And I have several other components that accept the classes too, such as `InfoTable`, `FormTable`, etc., but these others don't accept a List, just a single instance of the class.

This is probably way overcomplicated so I understand that it's likely not worth it to add generics support for components if it would require a lot of work to do so, but...

**Comment by mkArtakMSFT** [comment]
Thanks for all the details, @ajruckman.
This is not really something we'll add support for.
