### ISSUE TITLE
Blazor Component Embedded in Razor Page

### ISSUE THREAD

**Issue by CarrotSolutions** [aspnet/AspNetCore#9834]
Repo: https://github.com/CarrotSolutions/WebApplication1.git

Please Help! We created a basic template razor page app.  We added Blazor components.  We have no problem getting this to work via replicating the steps in the 04/16 Blazor Update video or using the Blazor documentation.  However, once we add the Blazor component to a Razor page, all of our asp-page links no longer work.  The url changes in the address bar, but we remain on the same page.  The startup file is as follows:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
            });


            services.AddRazorPages()
                .AddNewtonsoftJson();

            services.AddServerSideBlazor();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseCookiePolicy();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapBlazorHub();
            });
        }
```

Page with working Component and broken link
```

<a asp-page="./Index">Home</a>

<br /> 

<div id="Counter"> 
    @(await Html.RenderComponentAsync<Counter>()) 
    <script src="~/_framework/blazor.server.js">
</script> 

```

**Comment by CarrotSolutions** [comment]
I can replicate this scenario in any standard MVC or Razor Page default template.  Link to a page with a Blazor component and all of the other page links will no longer function.  You can even replicate the same situation using the boilerplate template app for a Blazor Server Side app and linking to any mvc view or razor page.  All links no longer work.  This has to be a Startup issue.  Removing 
endpoints.MapBlazorHub(); will allow the links to work again but obviously that breaks the Blazor component.

**Comment by CarrotSolutions** [comment]
MVC Repo with same issue - [https://github.com/CarrotSolutions/Blazor12MvcWebApp.git](https://github.com/CarrotSolutions/Blazor12MvcWebApp.git)

**Comment by stavroskasidis** [comment]
I can also replicate this. I guess it has something to do with the client-side router, probably hijacking the url changes and trying to resolve them to components.

**Comment by CarrotSolutions** [comment]
Exactly, The capability of being able to use Blazor components inside of existing Razor or MVC apps is where this tech will gain traction in the beginning .  Note, I also tried mapping the razor pages inside Startup, verifying all pages has unique routes, etc.  Nothing works.

**Comment by chrdlx** [comment]
I also replicated this using razor pages.

**Comment by chrdlx** [comment]
Just curious, when an issue like this is CLOSED, does it mean that if I download the latest master, should it be fixed?  Thanks

**Comment by danroth27** [comment]
@chrdlx Yes, but potentially with some latency as it takes some time for all the ASP.NET Core bits to make their way into the .NET Core SDK builds: https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md
