### ISSUE TITLE
FileBufferingReadStream _maxRentedBufferSize is used as an exclusive bound

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/AspNetCore#9838]
FileBufferingReadStream `_maxRentedBufferSize` is checked as an exclusive bound staying just below 1MB.

We currently carry around our own constant that computes 1024 * 1024 -1 just to stay under that slightly unnatural max buffer rent size.

In the interest of usability it should probably just respect any size up to and including 1MB.

**Comment by anurse** [comment]
So you're basically saying that [this code](https://github.com/aspnet/AspNetCore/blob/e925df6a85ee6a1bb0b35a393107717fbf748278/src/Http/WebUtilities/src/FileBufferingReadStream.cs#L74) should be a `<=` instead of a `<`? Seems reasonable. Interested in sending a quick PR?

**Comment by cjaliaga** [comment]
We can do this change as part of https://github.com/aspnet/AspNetCore/pull/11569 or create a quick one here with the change to have it isolated.
