### ISSUE TITLE
Blazor Server-Side Client won't compile after project dependency added (-532462766)

### ISSUE THREAD

**Issue by Knarzi** [aspnet/AspNetCore#9848]
I have a VS-sln and added a Blazor-Server-Side-Template-Project to this Sln. Directly after adding it build without any error.  Now, when I add another Project as Project Dependency to the Blazor-Client, it doesn't compile anymore. I get only the Error **_The Command exited with code -532462766._**

`Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	MSB3073	Der Befehl "dotnet "C:\Users\andre.grub\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\Users\andre.grub\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/mono/bcl/" -d "C:\Users\andre.grub\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/mono/bcl/Facades/" -o "C:\Users\andre.grub\Source\Repos\LHHi\KiGa-Bestellungen\LHHi.KiGaOrders.BlazorSS.Client\obj\Debug\netstandard2.0\blazor\linker/" -x "C:\Users\andre.grub\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview4-19216-03\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Users\andre.grub\Source\Repos\LHHi\KiGa-Bestellungen\LHHi.KiGaOrders.BlazorSS.Client\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\andre.grub\.nuget\packages\microsoft.aspnetcore.blazor\3.0.0-preview4-19216-03\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\andre.grub\.nuget\packages\microsoft.aspnetcore.components\3.0.0-preview4-19216-03\lib\netstandard2.0\Microsoft.AspNetCore.Components.dll" -a "C:\Users\andre.grub\.nuget\packages\microsoft.aspnetcore.components.browser\3.0.0-preview4-19216-03\lib\netstandard2.0\Microsoft.AspNetCore.Components.Browser.dll" -a "C:\Users\andre.grub\.nuget\packages\microsoft.extensions.dependencyinjection\3.0.0-preview4.19216.2\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\andre.grub\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.0.0-preview4.19216.2\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\andre.grub\.nuget\packages\microsoft.jsinterop\3.0.0-preview4.19216.2\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Users\andre.grub\.nuget\packages\mono.webassembly.interop\3.0.0-preview4.19216.2\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Users\andre.grub\.nuget\packages\system.componentmodel.annotations\4.6.0-preview4.19212.13\lib\netstandard2.0\System.ComponentModel.Annotations.dll" -a "C:\Users\andre.grub\Source\Repos\LHHi\KiGa-Bestellungen\LHHi.KiGaOrders.Shared\bin\Debug\netstandard2.0\LHHi.KiGaOrders.Shared.dll" -a "C:\Users\andre.grub\Source\Repos\LHHi\KiGa-Bestellungen\LHHi.KiGaOrders.Shared\bin\Debug\netstandard2.0\LHHi.KiGaOrders.Core.DB.dll" -a "C:\Users\andre.grub\Source\Repos\LHHi\KiGa-Bestellungen\LHHi.KiGaOrders.BlazorSS.Client\obj\Debug\netstandard2.0\LHHi.KiGaOrders.BlazorSS.Client.dll"" wurde mit dem Code -532462766 beendet.`

Blazor Client Project-Settings

```<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RestoreAdditionalProjectSources>
      https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json;
      https://dotnet.myget.org/F/blazor-dev/api/v3/index.json;
    </RestoreAdditionalProjectSources>
    <LangVersion>7.3</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview4-19216-03" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview4-19216-03" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LHHi.KiGaOrders.Shared\LHHi.KiGaOrders.Shared.csproj" />
  </ItemGroup>
</Project>
```

Project-Settings for the Dependency

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>
    </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LHHi.KiGaOrders.Core.DB\LHHi.KiGaOrders.Core.DB.csproj" />
  </ItemGroup>
</Project>
```

Steps to Reproduce:
*Use Existing Net Core SLN
*Add Brazor Server-Side-Template
*Add Project Dependency to Blazor Client
*Compile

Used Version is Blazor Preview 4

**Comment by danroth27** [comment]
Hi @Knarzi,

It looks like you have a dependency on Microsoft.EntityFrameworkCore.SqlServer from your client-side Blazor project. This will pull in a native dependency for the SQL client which then causes the IL linker to fail. This scenario isn't expected to work in the browser, but the IL linker should ideally provide a better error message. We'll need to follow up with the Mono folks on this.

Since this issue is external to Blazor I'm going to go ahead and close this issue.

**Comment by jorgearana** [comment]
I see that the subject is closed, then, I understand that we can not work with the Entity Framework. My question then is, what is the use of Blazor and .Net core 3.0 if it is not possible to work with data?

**Comment by Knarzi** [comment]
It is possible, but you have to Split the Backend and the Client. Here is an example:

`YourProject.Backend -> ASP Web API Project -> Target NetCore3 -> Contains your Data-Controllers and Entity Framework DB-Context`

`YourProject.Shared -> Simple Class Library -> Target NetStandard2 -> Contains the DB-Models and other Stuff you want to share between Client and Backend`

`YourProject.Backend -> Blazor Client -> Target NetStandard2 -> Contains the Cllient-App` 

YourProject.Backend References YourProject.Shared and EFCore. Now you can Create your DB-Context from the DB-Models the are defined in the Shared-Project. Create a Controller for the Communication with the DB with Functions like GetUser(int id), GetUsers(), UpdateUser(User user) with Json-Return-Values.

Next step is to Reference the YourProject.Shared to your ClientApp.  The last step is to call Post and Get and deserialize the returned Json-String to your DB-Model.

It's just not like standalone applications, because Blazor is primarily a frontend API for web applications. If you want direct data access without a backend, Mono or NetCore is the choice. Like Javascript, Blazor is locked in the browser and its sandbox and therefore cannot communicate directly with the outside world.
