### ISSUE TITLE
Problems in runnig Blazor Project

### ISSUE THREAD

**Issue by ImadMichaelAyoub** [aspnet/AspNetCore#9849]
Dears:

I'm using Microsoft Visual Studio Community 2019, Version 16.0.2 on the right side, Microsoft .Net Framework, Version 4.7.03062 (I got the info from help). I'm using ASP.NET Core 3 Preview 4, I also installed Blazor latest version.

I created a Blazor project successfully, but when I run the application as it is without any modifications, it gives me Loading... and it stops here, it doesn't redirect me to Index.razor page, I think it reads index.html in wwwroot then it stops there, I uninstall and reinstalled every things fout times, same problem. Knowing that Razor Project without Blazor is working great.

I have tested the above with VS 2019 Preview, the application runs correctly, it gives https://localhost:44393/ in the URL and application run properly.
When I click Counter in the menu for the first time it gives https://localhost:44393/counter in the URL but if I press any other button such as: Home or Fitch Data, it directs to it in the URL but it doesn't directs to it phisically and remains in the same page.

If you need any further information, please let me know.

Please help.

Thanks a lot.

**Comment by uwefms** [comment]
Hi @ImadMichaelAyoub, 
  you need Microsoft Visual Studio Community 2019, Version 16.1.0 Preview 2.0 form the preview Channel.

https://visualstudio.microsoft.com/de/vs/preview/?rr=https%3A%2F%2Fdotnet.microsoft.com%2Fdownload%2Fdotnet-core%2F3.0

   regards

         Uwe

**Comment by danroth27** [comment]
@ImadMichaelAyoub Could you please provide the console output from the browser dev tools?

**Comment by ImadMichaelAyoub** [comment]
Dears:

I have uninstalled everything and I installed Microsoft Visual Studio Community 2019, Version 16.1.0 Preview 2.0 from the link you provided, application runs normally, but the behavior still not OK as preview 1.0, knowing that I'm using .Net Core 3 Preview 4, the behavior is as follows:

The application runs correctly, it gives https://localhost:44393/ in the URL and application run properly.
When I click Counter in the menu for the first time it gives https://localhost:44393/counter in the URL but if I press any other button such as: Home or Fitch Data, it directs to it in the URL but it doesn't directs to it phisically and remains in the same page.

**N.B.** Please see attached screen shot, please see the URL and see the screen.
![Blazor Error](https://user-images.githubusercontent.com/17528147/57008438-dc15fa00-6bf8-11e9-9a5f-117d6e44a0bc.jpg)

If you need anything from my side to solve this problem, I'm ready.

Thanks.

**Comment by danroth27** [comment]
@ImadMichaelAyoub What version of Windows are you using?

**Comment by danroth27** [comment]
I believe we have a known issue with server-side Blazor on Win7 that I believe you are hitting.

**Comment by ImadMichaelAyoub** [comment]
Dear: I am using Windows 7

**Comment by danroth27** [comment]
Got it. To work around this issue, could you please try running the app without using IIS Express? You can select the project from the Run button drop down in VS.

**Comment by ImadMichaelAyoub** [comment]
You are right dear. I have tried it several times now, it is working
properly when I select project name in Run Box instead of IIS Express, is
this normal or a bug will be fixed? Thanks a lot for your help.

**Comment by danroth27** [comment]
It's a bug. We need to investigate.

**Comment by ImadMichaelAyoub** [comment]
OK dear. If I face any other issue, I will let you know. Love Microsoft.
Have a great day.

**Comment by mkArtakMSFT** [comment]
Closing this as we're tracking the fix for this as part of a different issue, which is already being worked on.
