### ISSUE TITLE
[Identity] Edit User Profile -> Add another service to log in throw InvalidOperationException

### ISSUE THREAD

**Issue by Duavide** [aspnet/AspNetCore#9855]
### Describe the bug
Add external login to a logged in user will throw InvalidOperationException if the external login is already connected to another existing account.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.100-preview4-011223'.
2. Create a new Web Application MVC with Identity enabled.
3. Execute database migration to create the identity db.
4. Configure one or more valid external login in Startup.cs (Google, Facebook…).
5. Add all Identity Views with scaffolding.
6. Run the website and register a user with username and password.
7. After login in the profile page -> 'External Logins' connect one external login to the current account.
8. Logout and register a second user with new credential.
9. After login go to the profile page -> 'External Logins' and try to connect the same external login to this second account.
10. The app will throw: 
> InvalidOperationException: Unexpected error occurred adding external login for user with ID '...'. MultipleIdentity.Server.Areas.Identity.Pages.Account.Manage.ExternalLoginsModel.OnGetLinkLoginCallbackAsync() in ExternalLogins.cshtml.cs, line 102

### Expected behavior
Anything except an exception.

### Screenshots
![Error](https://user-images.githubusercontent.com/7583353/56970196-eab3d100-6b66-11e9-9a12-9f525b538dd1.jpg)

**Comment by HaoK** [comment]
Putting this in preview 8 as its just a simple change to set the status message instead of throwing an excpetion

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/AspNetCore/pull/11768
