### ISSUE TITLE
BuildRenderTree does not get called in Preview 4

### ISSUE THREAD

**Issue by DerekChasse** [aspnet/AspNetCore#9857]
### Describe the bug
I've added a simple component which overrides `BuildRenderTree` and attempts to wrap ChildContent in a simple `<div>`.  I've more complex logic in a real-world usage, but this simple test demonstrates the issue.

I'm wondering if this is related to the ix for #8192

### To Reproduce
See reproducible demo here:
https://github.com/DerekChasse/BuildRenderTree

Index.razor has a `<p>` tag which should, as part of rendering the `TestComponent`, be wrapped in a `<div>` and that `<div>` should have a GUID identifier as a simple test of `AddAttribute`.

### Expected behavior
I would expect that, as in preview 0.9.0 calls to the overridden `BuildRenderTree` be honored.

### Screenshots
![image](https://user-images.githubusercontent.com/1869236/56977626-99461a80-6b43-11e9-84e1-0de62cc788de.png)

### Additional context
There is also simple logging with `Console.Writeline` in the `BaseIndex` baseclass which was previously honored in and is no longer being called.

Visual Studio `16.1.0 Preview 2.0`
dotnet `3.0.100-preview4-011223`

**Comment by chrissainty** [comment]
As I mentioned on Gitter @DerekChasse. This is an issue with your code, you've overridden `BuildRenderTree` in a base class, `TestComponentBase.cs`, which is inherited by `TestComponent.razor` but you've also specified markup in `TestComponent.razor` file. This is overriding your code in `BuildRenderTree`.

**Comment by rynowak** [comment]
The explanation from @chrissainty is correct. Generated Razor code will replace override  `BuildRenderTree()` and will not call call `base.BuildRenderTree()`. This is the intended behavior, we want to make it possible to subclass a component and totally replace its markup.
