### ISSUE TITLE
"HTTP Error 500.30 - ANCM In-Process Start Failure" with Microsoft.AspNetCore.App on Azure

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#9858]
_From @vRITHNER on Thursday, 11 April 2019 08:06:38_

# Issue Title
"HTTP Error 500.30 - ANCM In-Process Start Failure" with Microsoft.AspNetCore.App on Azure

# General
Hi,
I recently learned you'll remove soon

> Microsoft.AspNetCore.All

.
To anticipate this move, I replaced in my solution the package in all projects with 

> Microsoft.AspNetCore.App

Now, both projects (AspNet Core 2.2 Web + AspNet Core 2.2 WebApi work in localhost both in IISExpress or Dotnet.exe

When I re-deploy the same projects on Azure, both projects get an error at start time:

> **HTTP Error 500.30 - ANCM In-Process Start Failure**

The question is:
How can I check which dependencies or settings are missing on Azure ?
FYI, I installed 2.2 extensions and both projects are working fine if I change back to 

> Microsoft.AspNetCore.All

# DotNet environment :

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18356
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009648 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009804 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  2.2.201 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

Thanks for any Help
-Vince

_Copied from original issue: dotnet/core#2572_

**Comment by Eilon** [comment]
_From @Houuse on Sunday, 28 April 2019 18:08:05_

it's happened with once where i was deploying to azure (maybe a different reason from your case), 
my case where my app was deploying targeting 64bit run-time whereas azure app instance(shared tier) were set to run 32bit apps , so you may deploy targeting 32 bit , or maybe upgrade your app instance in azure portal (and tweak it's settings)

**Comment by Eilon** [comment]
_From @Eilon on Tuesday, 30 April 2019 16:32:28_

@shirhatti / @jkotalik - any thoughts on this? Should I move to the AspNetCore repo?

**Comment by Eilon** [comment]
_From @jkotalik on Tuesday, 30 April 2019 16:34:48_

Just move to the aspnetcore repo.

**Comment by anurse** [comment]
@vRITHNER are you still encountering this issue?

**Comment by vRITHNER** [comment]
@anurse Yes. As I wrote before, my web site works on Azure only with `Microsoft.AspNetCore.All `.
The issue here is I don't know which dependency is missing when I set `'Microsoft.AspNetCore.App'`.
My site is working on my local machine but not on Azure.

**Comment by vRITHNER** [comment]
And it's nothing to do with x86 or x64 because it's working with Microsoft.AspNetCore.All

**Comment by anurse** [comment]
To clarify, you're still using 2.2, just switching to `Microsoft.AspNetCore.App`? (Your `dotnet --info` output indicated you had 3.0 installed, which is *fine* just clarifying that you aren't doing two changes at once here ;)). I ask because .NET Core 3.0 isn't pre-installed on Azure Web Apps right now so you'd have to do a self-contained deployment to publish 3.0 apps to Azure.

Can you check the Windows Event Log on your Azure Web App? See our [Troubleshoot ASP.NET Core on Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/troubleshoot?view=aspnetcore-2.2#application-event-log) doc for more information on how to collect this.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
