### ISSUE TITLE
Ask: Aspnet core Docker images

### ISSUE THREAD

**Issue by VidyaKukke** [aspnet/AspNetCore#9861]
I refer to microsoft/dotnet:2.1.5-aspnetcore-runtime-nanoserver-1803 as my base docker image. Turns out it does not install on Windows 10 Enterprise. So I thought of switching to 
microsoft/dotnet:2.1.5-aspnetcore-runtime-nanoserver-1809 and of course it does not exist. 
But what is more head scratching is I can't find those tags on 
https://hub.docker.com/_/microsoft-dotnet-core-aspnet/ even though I'm able to pull microsoft/dotnet:2.1.5-aspnetcore-runtime-nanoserver-1803.  I'm obviously not looking to upgrade to some newer version as I don't have cycles to retest everything.
Can someone please point me to all supported tags of 2.1.5 verson of aspnetcore-runtime? 

While we are on the topic of images I notice in my future I will need to move to 2.2 and then maybe 3.0. For linux we seem to have 2.1.10-alpine3.7(same for 2.1.5). But in 2.2 I see alpine-3.8 and alpine3.9 (no 3.7) and in 3.0 only 3.9. I don't know as a user which base image I should be using as ideally I don't want to change 2 things. Version and alpine3.7->3.8->3.9. Our test infra and matrix keeps getting more complicated. What is the recommendation? 
Just relying on -alpine might be too generic and not "safe". Please advise.

**Comment by Eilon** [comment]
This issue was moved to dotnet/dotnet-docker#1097
