### ISSUE TITLE
Blazor is calling properties get on every user interaction

### ISSUE THREAD

**Issue by alexandrereyes** [aspnet/AspNetCore#9863]
Why Blazor calls property get every time a user interact with some component?
For example:

```
@FullName

<button onclick="@(() => Console.Write(""))">button</button>

@functions{


    public string GivenNames { get; set; }
    public string FamilyName { get; set; }
    public string FullName => $"{GivenNames} {FamilyName}";

}
```

When I hit the button, FullName is recalculated again, why does this happen? The button above doesn't interact with anything.

This can lead to a huge performance problem.

**Comment by enetstudio** [comment]
I think it is because the StateHasChanged method is called automatically after the click event to re-render the component. In other words, this is an inherent limitation you should live with.

**Comment by arivera12** [comment]
Every time a blazor event is fired StateHasChanged gets called. I know this is not the way like angular or vuejs does. Angular and Vuejs watch properties to change to then call the re render process, but blazor doesn't seem to work that way.

**Comment by rynowak** [comment]
This is the expected behavior. Handling an event will trigger a re-render which will evaluate all of your markup. If you want to customize when a component re-renders you can override `ShouldRender()`
