### ISSUE TITLE
Support retrieving TLS-unique

### ISSUE THREAD

**Issue by irium** [aspnet/AspNetCore#9864]
We are developing EST server on .NET platform. Currently we're struggling with getting 'tls-unique' somehow using available options. We tried: WCF, HttpListener.Request.TransportContext.GetTlsTokenBindings(), TcpListener->SslStream.TransportContext.GetTlsTokenBindings()

None of them is working so :( I see in the AspNetCore sources that it's support is postponed.
https://github.com/aspnet/HttpSysServer/issues/231

We've sent questions to MSDN Forums, stackoverflow...
No one is know how to get 'tls-unique' from TLS using .NET platform (any technology).

So the question is: *when* ITlsTokenBindingFeature support is planned to be implemented???

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
I believe the same response still stands, when there's enough demand for it. Given the move of Edge, to Chromium, where it's not supported, it really does take a back seat these days to features that have a higher customer demand and value.

**Comment by irium** [comment]
I've found that TLS-Unique is actually supported via SslStream.TransportContext.GetChannelBinding(ChannelBindingKind.Unique).
HttpsConnectionAdapter puts SslStream into ConnectionContext.Features when HttpsConnectionAdapterOptions.ServerCertificateSelector is set (i.e. not null).
