### ISSUE TITLE
Update Streaming to not use our AsyncEnumerableAdapters

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#9866]
Cancellation should be fully supported on `IAsyncEnumerable` now (or soon?) so we shouldn't need to use our `AsyncEnumerableAdapters` and `CancelableAsyncEnumerable` helper classes anymore.

**Comment by anurse** [comment]
Duplicate of https://github.com/aspnet/AspNetCore/issues/7960
