### ISSUE TITLE
Regression on JsonPlatform

### ISSUE THREAD

**Issue by sebastienros** [aspnet/AspNetCore#9868]
![image](https://user-images.githubusercontent.com/1165805/56985065-5b91c380-6b3c-11e9-8c0d-784ee832fdbc.png)

I could reproduce the results and isolate it to these commits:
https://github.com/dotnet/coreclr/compare/f360bbc0cf893bcd612516563145729743d3af2b...df2f4c4feb273545e91fd8d7d170dc424b741f19

As I still have the patched version that @janvorli gave me with this changes:
https://github.com/dotnet/coreclr/pull/24045 which fixed a perf regression for Json, I can confirm that these changes introduced the new one on JsonPlatform.

**Comment by sebastienros** [comment]
ResponseCachingResponseNoCache and ResponseCachingRequestNoCache have also regressed (10%) at the same time, so probably related too.

**Comment by sebastienros** [comment]
@janvorli any chance you could take a look at this or assign it to someone who could understand the changes? It's one of the most visible scenarios in the TE benchmarks.

**Comment by janvorli** [comment]
> As I still have the patched version that @janvorli gave me with this changes:
> [dotnet/coreclr#24045](https://github.com/dotnet/coreclr/pull/24045) which fixed a perf regression for Json, I can confirm that these changes introduced the new one on JsonPlatform.

To make sure I understand - do you mean that my fix to the previous regression has introduced the other regression?

**Comment by sebastienros** [comment]
Exactly

**Comment by janvorli** [comment]
Ok, since the only thing the change did was to fix setting the affinity and the respective function is used only for GC threads, it seems that that benchmark dislikes affinitized GC threads for some reason.
Can you please try to run the test with COMPlus_GCNoAffinitize set to 1?

**Comment by sebastienros** [comment]
I tried with this value and even though it's better (+5%) it's still not up to the results we had before the change (1M RPS).

```
|              Description |     RPS | CPU (%) | Memory (MB) | Avg. Latency (ms) | Startup (ms) | First Request (ms) | Latency (ms) | Errors | Ratio |
| ------------------------ | ------- | ------- | ----------- | ----------------- | ------------ | ------------------ | ------------ | ------ | ----- |
| COMPlus_GCNoAffinitize=0 | 909,239 |      96 |         475 |              0.96 |          232 |              52.85 |         0.15 |      0 |  1.00 |
| COMPlus_GCNoAffinitize=1 | 953,860 |      99 |         507 |              0.88 |          232 |              53.34 |         0.15 |      0 |  1.05 |
```

I also tried on the `ConnectionClose` scenario which saw a regression as the exact same time, and the results are similar, with some good improvement, but not as much as before the change.

|              Description |    RPS | CPU (%) | Memory (MB) | Avg. Latency (ms) | Startup (ms) | First Request (ms) | Latency (ms) | Errors | Ratio |
| ------------------------ | ------ | ------- | ----------- | ----------------- | ------------ | ------------------ | ------------ | ------ | ----- |
| COMPlus_GCNoAffinitize=0 | 23,688 |      78 |         506 |             16.79 |          276 |              51.04 |         0.48 |      1 |  1.00 |
| COMPlus_GCNoAffinitize=1 | 27,018 |      92 |         503 |               9.2 |          276 |              50.78 |         0.42 |      0 |  1.14 |

**Comment by janvorli** [comment]
It seems the regression is likely due to a bug that we've discovered today: https://github.com/dotnet/coreclr/pull/24706

**Comment by sebastienros** [comment]
Would you mind giving me some binaries so I can test this change in isolation?

**Comment by janvorli** [comment]
Sure. Would build of coreclr from master work for you or would you prefer if I built it from an older commit and applied my fix to that? It would be easy to do both ways.

**Comment by sebastienros** [comment]
Any baseline is fine as long as you give me both versions, before and after the change. With only the files that actually changed.

**Comment by sebastienros** [comment]
Fixed
