### ISSUE TITLE
Make local template tests not depend on SharedFramework

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#9870]
Currently in order to test the templates you must first build the Shared framework with something like eng\scripts\cibuild.cmd. That takes quite a while and makes doing templating work slow and arduous. If there was a way we could not have to build the Shared framework to test locally (the CI tests should still test against the Shared framework) that would help speed things up.

It's possibly not worth it to do this if it requires a big investment, but if it's medium or small it could really help template development speed.

**Comment by mkArtakMSFT** [comment]
Let's consider doing this only if it's a small issue.

**Comment by mkArtakMSFT** [comment]
Can you please assign a cost to this issue, @ryanbrandenburg? If it'll take time to evaluate, let's postpone till 3.1. If it's `S` feel free to move it to preview7.

**Comment by mkArtakMSFT** [comment]
Closing as a dupe
