### ISSUE TITLE
[blazor] Not to hard code blazor component property names in RenderTreeBuilder

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/AspNetCore#9872]
Is it possible **not to hard code** blazor component property names in RenderTreeBuilder?

Instead:
 `builder.AddAttribute(2, "Title", "How is Blazor working for you?");`
to have:
` builder.AddAttribute(2, SurveyPrompt.Title, "How is Blazor working for you?");`

```
protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.AddMarkupContent(0, "<h1>Hello, world!</h1>");
            builder.OpenComponent<SurveyPrompt>(1);
            builder.AddAttribute(2, "Title", "How is Blazor working for you?");
            builder.CloseComponent();
        }
```

This will have **two benefit**:

1. If developer is manually building blazor component using RenderTreeBuilder, it will be **easier to work with class properties** rather than hard coded names.

2. I do blazor source mangling using mono.cecil and when I rename property names, hard coded names stay same because mono.cecil does not know about it and blazor is breaking.

If we will do some manipulations on blazor dlls in future (obfuscating/mangling and etc) it will be better not to have hard coded property names.

I can add logic and if try hard I can find and replace this hard coded names too, but it will be much easier if compiler will do it for us.

https://github.com/Lupusa87/BlazorSourceMangler/blob/master/BlazorSourceMangler/Mangler.cs#L74

For more details re **Blazor Source Mangler** you can check [repo](https://github.com/Lupusa87/BlazorSourceMangler) or [video](https://www.youtube.com/watch?v=nlXax81b1UE)

**Comment by chucker** [comment]
>If developer is manually building blazor component using RenderTreeBuilder, it will be easier to work with class properties rather than hard coded names.

Wouldn’t `nameof` accomplish this?

**Comment by Lupusa87** [comment]
@chucker 

> Wouldn’t `nameof` accomplish this?

Sure it will but it is optional and developer can continue hard coding if they don't know why to use nameof and it is not required by compiler.

In ideal case compiler should complain if it sees hard coded names.

It will be hard to achieve because builder.addattribute is receiving string parameter but maybe there can be some way.

If developer is manually building render tree he/she can be advised from documentation to use nameof instead of hard coded names and it can be enough but for razor compilation need to be changed hard coded names to class properties maybe using nameof as easiest option.

**Comment by danroth27** [comment]
Thank you for this feedback. This is not something we plan to invest in given the complexity involved the impact on our ability to evolve the implementation going forward.

**Comment by Lupusa87** [comment]
I think it is not hard razor compiler to generate:

`builder.AddAttribute(2, nameof(SurveyPrompt.Title), "How is Blazor working for you?");`

Instead of:

`builder.AddAttribute(2, "Title", "How is Blazor working for you?");`

Hard will be compiler to require not to hard code name in manual buildRenderTree use and I am ok if we don't go in this direction, because it could be lot work.

But I ask to estimate using nameof(SurveyPrompt.Title) istead "title" and if it is easy to do please do it.
