### ISSUE TITLE
[ANCM In-proc] Improve handling of malformed warmup requests

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#9873]
Epic https://github.com/aspnet/AspNetCore/issues/8833

In some versions of Windows (RS1 or below), we get a malformed warm-up request that has missing data. We throw `NullReferenceException`s in that case, which is not ideal. We should investigate this further and try to make our logic more resiliant to these nulls, but **only** during these malformed warmup requests.

**Comment by anurse** [comment]
https://github.com/aspnet/AspNetCore/issues/6075 covered some of this.

**Comment by anurse** [comment]
When this is done, consider backporting.

**Comment by anurse** [comment]
Let's time box this a little as well. We know we can get some cheap wins with the changes we've already taken.

**Comment by anurse** [comment]
The 3.0 work is finished with #10053. Filing a new thing for backporting.

**Comment by jkotalik** [comment]
I just span up an app service instance with Always On enabled. I'll confirm if this fixes the issue by tomorrow.

**Comment by jkotalik** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [x] The fix contains product changes (**check all items below**).
    * [ ] Relevant XML documentation comments for new public APIs are present.
    * [ ] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
        * [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
        * [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
        * [ ] The change requires no docs changes.
    * [x] Verification has been completed. (**check one item below**)
        * [x] The change is in the shared framework and was verified against the following versions 
            * SDK installer: 3.0.100-preview6-012113
            * ASP.NET Core Runtime: 3.0.0-preview6-19279-01
            * .NET Core Runtime: 3.0.0-preview6-27728-04
        * [ ] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: [PACKAGE ID] [VERSION]
