### ISSUE TITLE
[Blazor] How to bind window key down event?

### ISSUE THREAD

**Issue by yukozh** [aspnet/AspNetCore#9885]
How to bind window key down event?

**Comment by danroth27** [comment]
You should be able to bind to the onkeydown event on a specific element like this: `<input onkeydown="@OnKeyDown" />`. You should be able to put this on a high level component like a top level div in your layout. Alternatively you can always use JS interop: https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0.
