### ISSUE TITLE
How to refer the Components Libraries in Blazor with .net core 3.0.0.preview4

### ISSUE THREAD

**Issue by kmuthukumar23** [aspnet/AspNetCore#9886]
### Describe the bug
Thanks in advance..:)..I have created the blazor client side project and create the Blazor component library as per the [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&tabs=visual-studio-code#razor-class-libraries-not-supported-for-client-side-apps).

And then also import the name space in '_Imports.razor' file. But the blazor library components are not accessinble in the blazor project. 

Can any one please help me to configure the import.razor file for refer the components in the blazor components library.

### To Reproduce
1. Create the blazor client side (.net core v3.0.0.Preview4)
2. Create the blazor component library for blazor client side and add reference this to main project. [refer this](https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&tabs=visual-studio-code#razor-class-libraries-not-supported-for-client-side-apps)
3. then import the component libs namespace in bazor client-side project's _Imports.razor file.
4. Access the component in the blazor project's index.razor page. There is no intellicense for that component.

### Expected behavior
the component's name should be shown as intelisence.

### Screenshots
![bla](https://user-images.githubusercontent.com/31958591/57014460-dd154e80-6c2d-11e9-92e9-4d00c8000251.png)

### Additional context
dotnet --info
![image](https://user-images.githubusercontent.com/31958591/57014729-f8cd2480-6c2e-11e9-9b56-c3433a97df79.png)

Also attached my blazor proj and components lib.
[githubsample.zip](https://github.com/aspnet/AspNetCore/files/3134324/githubsample.zip)

**Comment by hosezelt** [comment]
Are you using VS2019 Preview 2?

**Comment by kmuthukumar23** [comment]
Hi @hosezelt 

I am using VS2019 RC..  :(

**Comment by hosezelt** [comment]
Blazor currently only works properly with the Preview version of Visual Studio. You can find it here: [VS Preview](https://visualstudio.microsoft.com/vs/preview/)

**Comment by danroth27** [comment]
@hosezelt Thanks for answering!
