### ISSUE TITLE
Blazor sample gets 63 Errors

### ISSUE THREAD

**Issue by dbaechtel** [aspnet/AspNetCore#9890]
Blazor sample solution of Blazor Client side app gets **63** Errors
Like:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)	WebApplication1	C:\Users\dbaec\source\repos\WebApplication1\Pages\Counter.razor	1	Active

How do I Fix all of these errors?

**Comment by 0ptim** [comment]
Allready issued at #9851

**Comment by danroth27** [comment]
This is most likely due to not using the correct version of Visual Studio. You will see these errors if you try to use the stable release of Visual Studio 2019. Instead, you need to use the latest Visual Studio *Preview* release: https://visualstudio.com/preview.
