### ISSUE TITLE
Breakpoints not activated in Blazor Client side sample solution.

### ISSUE THREAD

**Issue by dbaechtel** [aspnet/AspNetCore#9891]
### Describe the bug
Breakpoints set in Program.cs in the Main routine in Debug mode says "Breakpoint will not be Hit. No Symbols have been loaded for this document."

How do we Debug without breakpoints?

### To Reproduce
1. Using this version of NET Core 3.0 Preview 4 SDK (3.0.100-preview4-011223)
2. Follow https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started
3. Set Breakpoint at Program.cs line 9.
4. Build in Debug mode.
5. Run using IIS Express.
6. See Breakpoint status in Program.cs while running.

### Expected behavior
Breakpoints should be activated and should be triggered.

**Comment by danroth27** [comment]
Client-side Blazor apps run directly in the browser via a WebAssembly based .NET runtime. We don't have support yet for attaching the debugger to the browser from Visual Studio quite yet, but we do have some preliminary support for debugging using the browser dev tools: https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0
