### ISSUE TITLE
razor pages no longer accept single lines without {}

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9892]
@pranavkm:

More info:
```C#
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview4-19216-03" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview4-19216-03" PrivateAssets="all" />
  </ItemGroup>
```

Annoying but not a killer: razor pages no longer accept single lines without {}
eg. for(...)
   singleLine();

input & select onchange events no longer accept a method name.  Throws this error: 
Error	CS0029	Cannot implicitly convert type 'void' to 'object'		
Other errors I can't fix:
Error	CS0103	The name 'StateHasChanged' does not exist in the current context	
Error	CS0103	The name 'PageContext' does not exist in the current context	
Error	CS0246	The type or namespace name 'HttpClient' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0115	'_Pages_mypage_razor.OnInitAsync()': no suitable method found to override

_Originally posted by @TJatITJ in https://github.com/aspnet/AspNetCore/issues/9851#issuecomment-488214898_

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/AspNetCore/issues/9637
