### ISSUE TITLE
[Blazor] In wasm (client-side blazor) HttpClient post request does not save cookie in browser

### ISSUE THREAD

**Issue by stavroskasidis** [aspnet/AspNetCore#9894]
### Describe the bug
I have a Blazor hosted project set-up with identity authentication. Using 3.0 preview 4, after an HttpClient request to the server Login api, the response correctly contains a `Set-Cookie` header with the identity cookie. However the cookie is not stored in the browser making subsequent requests unauthorized. This was working in preview 3. I am doing something wrong ?

#### Startup.cs (Server project)
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<CookiePolicyOptions>(options =>
    {
        options.CheckConsentNeeded = context => false;
    });

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseLazyLoadingProxies().UseSqlite("Filename=data.db"));
    services.AddCors();

    services.AddIdentity<ApplicationUser, IdentityRole<Guid>>()
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultTokenProviders();

    services.ConfigureApplicationCookie(options =>
    {
        options.Cookie.HttpOnly = false;
        options.Cookie.IsEssential = true;
        options.Events.OnRedirectToLogin = context =>
        {
            context.Response.StatusCode = 401;
            return Task.CompletedTask;
        };
    });

    services.Configure<IdentityOptions>(options =>
    {
        options.Password.RequireDigit = false;
        options.Password.RequiredLength = 6;
        options.Password.RequireNonAlphanumeric = false;
        options.Password.RequireUppercase = false;
        options.Password.RequireLowercase = false;

        options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(30);
        options.Lockout.MaxFailedAccessAttempts = 10;
        options.Lockout.AllowedForNewUsers = true;

        options.User.RequireUniqueEmail = false;
    });

    services.AddControllersWithViews().AddNewtonsoftJson();
    //TODO: Remove when fixed
    //AllowSynchronousIO is required for newtonsoft serialization
    services.Configure<KestrelServerOptions>(options =>
    {
        options.AllowSynchronousIO = true;
    });
    services.Configure<IISServerOptions>(options =>
    {
        options.AllowSynchronousIO = true;
    });

    services.AddResponseCaching();
    services.AddDistributedMemoryCache();

    services.AddSession(options =>
    {
        options.IdleTimeout = TimeSpan.FromMinutes(120);
    });

    services.AddResponseCompression(options =>
    {
        options.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[]
        {
            MediaTypeNames.Application.Octet,
            WasmMediaTypeNames.Application.Wasm,
        });
    });

    //....
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseCors();
    app.UseResponseCompression();
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseBlazorDebugging();
    }

    app.UseStaticFiles();


    app.UseCookiePolicy();
    app.UseRouting();
    app.UseAuthentication();
    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapDefaultControllerRoute();
    });

    app.UseBlazor<Client.Startup>();
}
```

#### AuthorizeController.cs
```csharp
[AllowAnonymous]
[Route("api/[controller]/[action]")]
[ApiController]
public class AuthorizeController : ControllerBase
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly SignInManager<ApplicationUser> _signInManager;

    public AuthorizeController(UserManager<ApplicationUser> userManager, 
                               SignInManager<ApplicationUser> signInManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginParameters parameters)
    {
        var user = await _userManager.FindByNameAsync(parameters.Username);
        if (user == null) return BadRequest("User does not exist");
        var singInResult = await _signInManager.CheckPasswordSignInAsync(user, parameters.Password, false);
        if (!singInResult.Succeeded) return BadRequest("Invalid password");

        await _signInManager.SignInAsync(user, true);

        return Ok();
    }
    
    //...
```

#### Client-side project HttpClient code
```csharp
public class AuthorizeApi : IAuthorizeApi
{
    private readonly HttpClient _httpClient;

    public AuthorizeApi(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task Login(string username, string password)
    {
        var stringContent = new StringContent(Json.Serialize(new LoginParameters
        {
            Username = username,
            Password = password
        }), Encoding.UTF8, "application/json");
        var result = await _httpClient.PostAsync("api/Authorize/Login", stringContent);
        if (result.StatusCode == System.Net.HttpStatusCode.BadRequest) 
            throw new Exception(await result.Content.ReadAsStringAsync());
        result.EnsureSuccessStatusCode();
    }

    //...
```
#### Request info
![image](https://user-images.githubusercontent.com/12549761/57037744-b02e5f00-6c60-11e9-9579-2c95b86d6408.png)

**Comment by GerritBergen** [comment]
I had this issue yesterday, putting this in the startup file of the client fixed it.

`public void Configure(IComponentsApplicationBuilder app)
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY")))
            {
                WebAssemblyHttpMessageHandler.DefaultCredentials = FetchCredentialsOption.Include;
            }

            app.AddComponent<App>("app");
        }`

**Comment by GerritBergen** [comment]
Referenced here: https://github.com/aspnet/Blazor/issues/515

With code here: https://github.com/aspnet/AspNetCore/blob/3189146b4e5c1811f6599ba38b5c8a0077128f24/src/Components/test/testassets/BasicTestApp/Startup.cs#L23

**Comment by stavroskasidis** [comment]
@GerritBergen Thanks for replying. However I tried using that fix but the cookie is still not saved.

**Comment by rxelizondo** [comment]
I  probably should not be replying because I an pretty new to all this, however, I have the following (see below) and the identity cookie appears to be working just fine.

```
            services.AddDefaultIdentity<IdentityUser>()
                    .AddEntityFrameworkStores<ApplicationDbContext>();

```

Essentially, using `AddDefaultIdentity `instead of `AddIdentity`

This `AddDefaultIdentity  `is reference from:

```
#region Assembly Microsoft.AspNetCore.Identity.UI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Users\abc\.nuget\packages\microsoft.aspnetcore.identity.ui\3.0.0-preview4-19216-03\lib\netcoreapp3.0\Microsoft.AspNetCore.Identity.UI.dll
#endregion
```

**Comment by stavroskasidis** [comment]
@rxelizondo I don't think that helps. According to documentation

> `AddDefaultIdentity` was introduced in ASP.NET Core 2.1. Calling `AddDefaultIdentity` is similar to calling the following:
> 
> `AddIdentity`
> `AddDefaultUI`
> `AddDefaultTokenProviders`

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio#adddefaultidentity-and-addidentity

**Comment by rxelizondo** [comment]
Or maybe I am doing something wrong with a side effect of it working for some strange reason...

By the way, I should have mentioned that in order to get this to work, I created a brand new MVC project with the individual user account authentication option selected. The I just copy / paste the auto generated authentication code from the MVC project into the Blazor server side project. I did the same thing with the project references because I believe the code was not compiling (its been a while so I don't remember), so my references in the Blazor sever side project look like this:

```

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Server" Version="3.0.0-preview4-19216-03" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview4-19216-03" />

    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.0.0-preview4-19216-03" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0-preview4-19216-03" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0-preview4-19216-03" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview4.19216.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0-preview4.19216.3" />
  </ItemGroup>

```
The I login like this (this was a test so the code is minimal).

```
        public async Task SignIn()
        {
            var user = await m_UserManager.FindByEmailAsync("abc@xyz.com");
            await m_SignInManager.SignOutAsync();
            Microsoft.AspNetCore.Identity.SignInResult result = await m_SignInManager.PasswordSignInAsync(user, "xyz", true, false);
        }
```

And so far, I am able to make calls to action decorated with the `[Authorize]` attribute with no issues. The cookie is remembered.

Hope this help.

**Comment by stavroskasidis** [comment]
Here is a sample project that works using preview 3. This is almost the exact thing I am also doing in my private project


https://github.com/stavroskasidis/BlazorWithIdentity

**Comment by stavroskasidis** [comment]
I cannot reproduce the issue. I have uploaded a branch of the sample project using preview 4 and everything works fine. 

I will keep trying to find the issue, but until then I am gonna close this. I don't want to waste your time with a possible misconfiguration. I will reopen if needed.

**Comment by stavroskasidis** [comment]
Turns out, it was a problem with chrome on my PC. I have no idea why it didn't work, maybe some extension was jamming it. When I used Firefox (or Chrome in Incognito mode) everything worked fine. 

I have never seen something like that before. I did a clean re-install of Chrome and now it is working again.

Sorry if I wasted anyone's time.
