### ISSUE TITLE
Razor does not resolve layout view properly inside area

### ISSUE THREAD

**Issue by thiagomajesk** [aspnet/AspNetCore#9895]
### Describe the bug
Razor doesn't seem to be searching inside the `Area/Views/Shared` folder when using partial names to define a layout view inside `_ViewStart.cshtml` - works only if `_Layout.cshtml` is in the area's view root folder.

### To Reproduce
1. Run provided repo with `dotnet run`
2. Go to area `~/admin`
3. Remove the root `Areas\Admin\Views\_Layout.cshtml`
4. See error:
```
InvalidOperationException: The layout view '/Areas/Admin/Views/_Layout.cshtml' could not be located. The following locations were searched:
/Areas/Admin/Views/_Layout.cshtml
````

### Expected behavior
[Docs states that:](https://docs.microsoft.com/pt-br/aspnet/core/mvc/views/layout?view=aspnetcore-2.2#specifying-a-layout) 

> When a partial name is provided, the Razor view engine searches for the layout file using its standard discovery process. The folder where the handler method (or controller) exists is searched first, followed by the Shared folder. This discovery process is identical to the process used to discover partial views.

Then, the order should be like bellow (but the second one does not seem to be attempted):

```
/Areas/<Area-Name>/Views/<Controller-Name>
/Areas/<Area-Name>/Views/Shared
/Views/Shared
/Pages/Shared
```
Also, it does not even report that the framework tried to search inside other folders (like it normally does). I tested against AspNetCore 2.2 and the latest 3.0; the behavior is exactly the same.

[repro.zip](https://github.com/aspnet/AspNetCore/files/3135916/repro.zip)

**Comment by pranavkm** [comment]
Your `_ViewStart` has a `Layout = "_Layout.cshtml"` and Razor View Engine would attempt to treat it as a relative path. Changing it to `Layout = "_Layout"` would cause it to be treated as name and used as part of the view lookup.

**Comment by thiagomajesk** [comment]
@pranavkm Thanks! Shouldn't this behavior be disclosed somewhere in the docs though? I'm sorry if it already is, in that case, could you link it to the discussion?

**Comment by pranavkm** [comment]
@thiagomajesk there's a small gist:

> The layout specified can use a full path (for example, /Pages/Shared/_Layout.cshtml or /Views/Shared/_Layout.cshtml) or a partial name (example: _Layout)

but we'd be happy to accept improvements to the documentation.
