### ISSUE TITLE
[Blazor] Allow ability to change page title dynamically.

### ISSUE THREAD

**Issue by rxelizondo** [aspnet/AspNetCore#9897]
Sometimes you may want to change the page title dynamically depending on certain circumstances. As far as I can see, the page title is set on `index.html` and given that this is just a regular html page I can’t use something like razor syntax to perhaps call a function that would get the correct page title dynamically.

I realize that there are other ways to accomplish this such as using JavaScript but it would be nice to not have to.

**Comment by mkArtakMSFT** [comment]
This will be covered as part of https://github.com/aspnet/AspNetCore/issues/10450
