### ISSUE TITLE
[Blazor server-side] Breakpoints doesn't works on Visual Studio 2019.

### ISSUE THREAD

**Issue by lorenzomelato** [aspnet/AspNetCore#9911]
### Describe the bug
In Visual Studio 2019, I can set a breakpoint in the razor page but the breakpoint doesn't hit.

### To Reproduce
1. Using Visual Studio 2019 (both V16 and V16.1 preview 2), ASP.NET Core 3.0-preview-4;
2. Generate a new project with the last Blazor server side template.
3. Put a breakpoint inside the counter razor view function;
4. The breakpoint doesn't hit.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lorenzomelato.
This should be fixed now. If, however, you still face the issue with the latest Blazor bits, please reopen.
