### ISSUE TITLE
[.NET Core 3.0] HTTP 500.0 - ANCM In-Process Handler Load Failure

### ISSUE THREAD

**Issue by sujayvsarma** [aspnet/AspNetCore#9912]
The symptom is similar to the OP's issue in #6111. However, CODE circumstances are mightily different.

Here is what I did:

Visual Studio 16.1.0 Preview 2.0 > Created a brand new ASP.NET Core Web application. On the Template selection screen, I selected "Empty", let it configure HTTPS and No Authentication.

Once the project was ready in VS, I simply hit F5. The resulting webpage showed the HTTP 500.0 ANCM In-Process Handler Load Failure error, and a Google search led me to #6111.

I don't have a web/other config file like the OP in 6111. 

Reading through the other thread, I made the following notes:

1. VS configured my project to build as a "Console Application". So this generated the following files in the bin/debug/netcoreapp3.0 folder:

```
WebApplication1.dll
WebApplication1.exe
WebApplication1.pdb
WebApplication1.deps.json
WebApplication1.runtimeconfig.dev.json
WebApplication1.runtimeconfig.json
```

2. When I ran `dotnet WebApplication1` from a command prompt, I was told:

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-WebApplication1 does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

3. For `dotnet WebApplication1.exe`, I got:

```
Error:
  An assembly specified in the application dependencies manifest (WebApplication1.deps.json) has already been found but with a different file extension:
    package: 'WebApplication1', version: '1.0.0'
    path: 'WebApplication1.dll'
    previously found assembly: 'D:\temp\WebApplication1\bin\Debug\netcoreapp3.0\WebApplication1.exe'
```

4. If I tried to execute the DLL directly, I get:

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'D:temp\WebApplication1\bin\Debug\netcoreapp3.0\WebApplication1.dll'. An attempt was made to load a program with an incorrect format.
```

So I changed the project's properties to output a Class Library instead of the Console Application EXE. With this, I got:

```
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'D:\temp\WebApplication1\bin\Debug\netcoreapp3.0\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the D:\temp\WebApplication1\bin\Debug\netcoreapp3.0\WebApplication1.runtimeconfig.json file specifying the appropriate framework.
```

I literally have not changed a single line of code or text anywhere in this template-built project. What's wrong with it?

**Comment by drk-mtr** [comment]
> When I ran `dotnet WebApplication1` from a command prompt...

Doesn't seem like a bug - that's not a valid dotnet CLI command. It's `dotnet run WebApplication1` or similar e.g. `build` or `publish` instead of `run`.

Try `dotnet run WebApplication1 -v d` in order to see detailed information.

**Comment by sujayvsarma** [comment]
Interesting -- 

So following @drk-mtr's [reply](https://github.com/aspnet/AspNetCore/issues/9912#issuecomment-489433875), I ran:

```
dotnet run WebApplication1.csproj
```

And the app started correctly and there were no ANCM errors. 

But, when I ran the same thing from VS (VS 2019 Community Edition, 16.1.0 P2), I hit the same ANCM error I posted in my original report on top.

**Comment by anurse** [comment]
Can you send us a sample project that reproduces the issue so we can clone it and try it out to explore further?

**Comment by sujayvsarma** [comment]
Visual Studio 16.1.0 Preview 2.0 > Create new Project > ASP.NET Core Web application. 

On the Template selection screen, selected "Empty", let it configure HTTPS and No Authentication.

That's it.

**Comment by anurse** [comment]
Are you on a 32-bit machine? It sounds like you could be hitting this issue which was resolved in Preview 3: https://developercommunity.visualstudio.com/content/problem/544171/microsoftancmv2iisexpressmsi-installs-64-bit-aspne.html

Can you update to the latest released 16.1 preview and see if this issue still happens?

**Comment by sujayvsarma** [comment]
No, I have a 64-bit machine, with a 64-bit Win 10. 

> Can you update to the latest released 16.1 Preview (should be Preview 3) and see if this issue still reproduces?

Yes. 

I am not sure if this will help, but some additional info:

I do not have IIS (the Windows 10 IIS) or any web server separately installed. The VS web experience is using the IIS Express that is installed by VS. 

Also, based on this observation (mine, above), 

> Interesting --
> So following @drk-mtr's reply, I ran:
> dotnet run WebApplication1.csproj
> 
> And the app started correctly and there were no ANCM errors.
> But, when I ran the same thing from VS (VS 2019 Community Edition, 16.1.0 P2), I hit the same ANCM error I posted in my original report on top.

It looks like something is different between doing a `dotnet run` and an F5 run from VS.

**Comment by anurse** [comment]
Yes, there is definitely a lot different between `dotnet run` and F5 in VS. VS launches IIS Express, but `dotnet run` does not (it runs as a console app and directly launches Kestrel).

Can you look in a few more places for some extra information?

1. The VS Output Window has a dropdown option "ASP.NET Core Web Server". Can you open that when you run and grab the output from there and put it here

1. The Windows Event Log (Start > Event Viewer), under "Windows Logs/Application", may have entries at the "Error" level related to the ASP.NET Core Module.

1. Run `dotnet --info` on the command line and paste the output

The 500.0 ANCM In-Process handler error generally indicates a failure to load the .NET runtime itself.

**Comment by sujayvsarma** [comment]
I shall do this later today or tomorrow. .NET Core isn't a priority for me. I was only trying it out post the announcements made at //build.

**Comment by anurse** [comment]
No problem. Let us know when you can get a little more info and we'll do our best to help!

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
