### ISSUE TITLE
[Tooling][Blazor] Support Reformat File in VS Code

### ISSUE THREAD

**Issue by detachmode** [aspnet/AspNetCore#9914]
Not sure if this fits here, but I don't know where else to put it.
But I would like to have a reformatting feature in VS Code, which should respect the html tags and the C#/Razor code.  At least it should reindent the code. But it would also be nice, if it puts the brackets in the right line and so on.

**Comment by NTaylorMullen** [comment]
@detachmode glad you want this as well 😄. It's on our roadmap and we're tracking the work: https://github.com/aspnet/Razor.VSCode/issues/21
