### ISSUE TITLE
Provide a way to automatically create code behind .razor files

### ISSUE THREAD

**Issue by guidevnet** [aspnet/AspNetCore#9924]
I know it is possible to move the C# code from inside the `@functions` section to a partial class, and then I can inherit it in the .razor file. However, this process is not automatic. For each razor file:

- I need to name the C# file myself
- I need to manually inherit the C# file in the Razor file
- I need to choose a location for the C# file, because the files don't get nested in the solution explorer

I believe the solution is simple: When adding a new item to the project, an option to create a "code behind" razor file would be nice. Let's say I name the new added item as "MyPage.razor", then in the solution explorer I can see the MyPage.razor, with a file named MyPageFunctions.cs, nested in it.

Is this possible?

**Comment by danroth27** [comment]
The plan is to support partial classes with .razor files #5487
