### ISSUE TITLE
WebHost always calls StopAsync on a Server even if StartAsync wasn't called.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#9929]
Discovered as part of https://github.com/aspnet/AspNetCore/pull/9859. We have logic in IIS inproc that tries to drain all existing requests before shutting down, which relies on a callback to be set in StartAsync for a tcs to be completed. If an exception is thrown from Configure/ConfigureServices, the server will still call Server.StopAsync from WebHost.StopAsync even if StartAsync wasn't called.

The fix I'm adding is to check if StartAsync was called before doing anything in StopAsync. I feel like this should be solved in a more universal way though. Looking at Stop async in Kestrel https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/KestrelServer.cs#L172, I think the start/stop logic I suggested is safe here too.

**Comment by Tratcher** [comment]
DisposeAsync calls StopAsync:
https://github.com/aspnet/AspNetCore/blob/4cb86bc15160e493e6331190da9973736f0fc240/src/Hosting/Hosting/src/Internal/WebHost.cs#L355-L371

GenericHost no longer does this:
https://github.com/aspnet/Extensions/blob/1b1558ebc1f33a70c76736f6a26d907b6dcca270/src/Hosting/Hosting/src/Internal/Host.cs#L110-L121

Possible fix:
WebHost.StopAsync already checks _stopped to prevent double calls.
https://github.com/aspnet/AspNetCore/blob/4cb86bc15160e493e6331190da9973736f0fc240/src/Hosting/Hosting/src/Internal/WebHost.cs#L312-L316

We could also add a _started and set it at the end of StartAsync and have StopAsync only run if _started.

**Comment by jkotalik** [comment]
I'll do this as part of https://github.com/aspnet/AspNetCore/issues/9929.
