### ISSUE TITLE
After adding Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation, no new razor pages can be added by scaffolding.

### ISSUE THREAD

**Issue by bhrugen** [aspnet/AspNetCore#9930]
### Describe the bug
After adding Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation, no new razor pages can be added by scaffolding. Once i add that nuget package for runtime compilation, I cannot add anything to project by right clicking add new razor page.

### To Reproduce
1. Using this version of ASP.NET Core 3 preview 4
2. Install preview version of  Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 
3. Try Adding a new razor page you will get the following error

![image](https://user-images.githubusercontent.com/20101947/57096249-7601a380-6cda-11e9-9dd3-6d39022f05e9.png)

### Expected behavior
It should create a new razor page

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @bhrugen.
This is a VS issue, which is not actionable for this repo. Please report this issue through the VS feedback (the button in the top right corner of VS), and reference this link for the context.
