### ISSUE TITLE
Unsupported Media Type on ApiController GET action

### ISSUE THREAD

**Issue by mdmoura** [aspnet/AspNetCore#9932]
Using ASP.NET Core 2.2 I have the following ApiController actions:

    [ApiController, ApiVersion("1.0", Deprecated = false), Route("v{version:version}")]
    public class PostController : ControllerBase {
    
      [HttpGet("users/{userId}/posts")]
      public async Task<IActionResult> GetByUserId(GetModel model) {
  
      }
    
      [HttpPost("users/{userId}/posts")]
      public async Task<IActionResult> CreateByUserId(CreateModel model) {
    
      }
    
    }

I tried to access both actions using Angular and the Rest Client Insomnia ...

I am able to access CreateByUserId [POST] but I get an error on GetByUserId [GET]:

    {
      "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
      "title": "Unsupported Media Type",
      "status": 415,
      "traceId": "0HLMF7BM7U94L:00000001"
    }

What am I missing? This is simply a Get action. It has no body just the userId in URL.

### Additional context

.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.2.104 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by pranavkm** [comment]
Is `GetModel` a complex type? `ApiController` assumes complex types come from the body. If it's meant to be a value from query, you need to add a `FromQuery` on the action parameter.

**Comment by mdmoura** [comment]
@pranavkm Yes, it is a complex type and I tried using FromQuery but I get the same error.

**Comment by pranavkm** [comment]
Have you looked at the application logs with logging for MVC set to `Information`. It might give a hint.

**Comment by mdmoura** [comment]
> Have you looked at the application logs with logging for MVC set to `Information`. It might give a hint.

Ok, that helped! Adding [FromQuery] attribute solves the problem. Thank you.

**Comment by Tolitech** [comment]
@pranavkm 
How would it be possible to use [ApiController] being the same complex object with 2 properties one for [FromRoute] and one for [FromQuery] for example?

public class Dto
{
     public string Prop1 { get; set; }
     public string Prop2 { get; set; }      
}

[HttpGet("test/{prop1:alpha}")]
public ActionResult<Result> Test(Dto dto)

https://localhost:xxxx/test/aaa?prop2=bbb

Without ApiController it works correctly.
With ApiController it gets the value by route or by query.
(Or one or the other)

**Comment by Tolitech** [comment]
I got it using ApiController.

`options.SuppressInferBindingSourcesForParameters = true;`
