### ISSUE TITLE
Investigate SignalR Streaming Performance

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/AspNetCore#9934]
We've done a lot of feature work in our streaming story but now we should focus on looking at the performance. Especially since we can now compare the `StreamAsChannel `and `StreamAsync` APIs to each other directly and the differences between uploading via a `Channel  `vs an `IAsyncEnumerable`

**Comment by mikaelm12** [comment]
Some initial numbers for accepting a `ChannelReader<string>` vs `IAsyncEnumerable<string>` as a hub method parameter.

Method |       Mean |     Error |    StdDev |      Op/s |  Gen 0 | Allocated |
-------------------------------------- |-----------:|----------:|----------:|----------:|-------:|----------:|
UploadStream_One |  21.036 us | 2.0988 us | 5.8157 us |  47,536.9 | 0.1221 |   2.98 KB |
UploadStreamIAsyncEnumerable_One |   9.011 us | 0.2105 us | 0.5902 us | 110,972.9 | 0.1678 |   3.23 KB |
UploadStream_Thousand | 409.314 us | 1.5328 us | 1.1967 us |   2,443.1 | 1.4648 |   10.3 KB |
UploadStreamIAsyncEnumerable_Thousand | 366.784 us | 3.9036 us | 3.2597 us |   2,726.4 | 1.4648 |   5.73 KB |

**Comment by mikaelm12** [comment]
This is comparing using `ChannelReader<int>` vs `IAsyncEnumerable<int>` as a hub method return value . The difference between the `StreamIAsyncEnumerableCount` and and `StreamIAsyncEnumerableCompletedTaskCount` is how we make the hub method go "async". Awaiting `Task.Yield()` vs awaiting `Task.CompletedTask`

Method |       Mean |      Error |      StdDev |     Median |      Op/s |  Gen 0 | Allocated |
-------------------------------------------------- |-----------:|-----------:|------------:|-----------:|----------:|-------:|----------:|
StreamChannelReaderCount_Zero |   4.970 us |  0.1220 us |   0.3596 us |   4.873 us | 201,215.2 | 0.2441 |   2.92 KB |
StreamIAsyncEnumerableCount_Zero |   3.861 us |  0.0771 us |   0.1029 us |   3.840 us | 258,991.8 | 0.1373 |   1.52 KB |
StreamIAsyncEnumerableCompletedTaskCount_Zero |   3.138 us |  0.4504 us |   1.3279 us |   2.584 us | 318,649.5 | 0.0648 |   1.23 KB |
StreamChannelReaderCount_One |   5.306 us |  0.1236 us |   0.1156 us |   5.283 us | 188,457.1 | 0.2670 |   3.01 KB |
StreamIAsyncEnumerableCount_One |   4.039 us |  0.0651 us |   0.0609 us |   4.042 us | 247,558.4 | 0.1297 |   1.52 KB |
StreamIAsyncEnumerableCompletedTaskCount_One |   2.886 us |  0.4148 us |   1.2230 us |   2.366 us | 346,505.1 | 0.0687 |    1.3 KB |
StreamChannelReaderCount_Thousand | 526.187 us | 45.6944 us | 134.7309 us | 500.570 us |   1,900.5 | 1.9531 |   9.68 KB |
StreamIAsyncEnumerableCount_Thousand |  88.871 us |  1.7644 us |   3.9463 us |  87.767 us |  11,252.3 | 3.1738 |   1.59 KB |
StreamIAsyncEnumerableCompletedTaskCount_Thousand |  74.060 us |  1.4768 us |   2.8803 us |  73.927 us |  13,502.6 | 3.4180 |  63.74 KB |

**Comment by anurse** [comment]
We're feeling good about the perf now. There's always room for improvement but we'll look at that in other issues.
