### ISSUE TITLE
Adding a reference to a (working) class library project breaks the build of my Blazor project

### ISSUE THREAD

**Issue by BenjaminCharlton** [aspnet/AspNetCore#9940]
### Describe the bug
Adding a reference to a class library project breaks the build of my Blazor project. There are no build errors in the class library itself, and both projects target .NET Standard 2.1, and I don't understand the error message, so I'm a bit stuck. Can anybody see what I've done wrong, please?

### To Reproduce
I created a new client side Blazor project from the latest template in Visual Studio 2019. In _Properties_, I set it to target .NET Standard 2.1. I rebuilt it, still worked fine. Then I added a reference from the Blazor project to an existing class library project I had made. My class library also targets .NET Standard 2.1. The class library project builds fine in isolation and runs fine when referenced by other projects, such as Console applications and MVC applications. However, when I reference the class library from the Blazor app it breaks the build of the Blazor app with the error message below.

### Expected behavior
I would expect to be able to reference a .NET Standard 2.1 class library from the Blazor template.

### Screenshots
I get the following build error in the Blazor app in Visual Studio 2019 after referencing the .NET Standard class library, even when the code of the Blazor app doesn't call anything in the class library:

Error	MSB3073	The command "dotnet "C:\Users\USER\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\Users\USER\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/mono/bcl/" -d "C:\Users\USER\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/mono/bcl/Facades/" -o "C:\Users\USER\BlazorClient\obj\Debug\netstandard2.1\blazor\linker/" -x "C:\Users\USER\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview4-19216-03\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Users\USER\BlazorClient\obj\Debug\netstandard2.1\blazor\linker.descriptor.xml" -a "C:\Users\USER\.nuget\packages\microsoft.aspnetcore.blazor\3.0.0-preview4-19216-03\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\USER\.nuget\packages\microsoft.aspnetcore.components\3.0.0-preview4-19216-03\lib\netstandard2.0\Microsoft.AspNetCore.Components.dll" -a "C:\Users\USER\.nuget\packages\microsoft.aspnetcore.components.browser\3.0.0-preview4-19216-03\lib\netstandard2.0\Microsoft.AspNetCore.Components.Browser.dll" -a "C:\Users\USER\.nuget\packages\microsoft.extensions.dependencyinjection\3.0.0-preview4.19216.2\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\USER\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.0.0-preview4.19216.2\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\USER\.nuget\packages\microsoft.jsinterop\3.0.0-preview4.19216.2\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Users\USER\.nuget\packages\mono.webassembly.interop\3.0.0-preview4.19216.2\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Users\USER\.nuget\packages\system.componentmodel.annotations\4.6.0-preview4.19212.13\lib\netstandard2.0\System.ComponentModel.Annotations.dll" -a "C:\Users\USER\ClassLibrary1\bin\Debug\netstandard2.1\ClassLibrary1.dll" -a "C:\Users\USER\MyApp.Core\bin\Debug\netstandard2.1\MyApp.Core.dll" -a "C:\Users\USER\MyApp.Core\bin\Debug\netstandard2.1\Microsoft.Extensions.Identity.Stores.dll" -a "C:\Users\USER\BlazorClient\obj\Debug\netstandard2.1\BlazorClient.dll"" exited with code -532462766.	BlazorClient	C:\Users\USER\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview4-19216-03\targets\Blazor.MonoRuntime.targets	439

Many thanks for any insights!

Benjamin

**Comment by SteveSandersonMS** [comment]
Apologies that the error message is unclear. One of your dependencies (`Microsoft.Extensions.Identity.Stores`) includes native code, which isn't usable on WebAssembly. Only plain .NET dependencies can be used on WebAssembly.

**Comment by vdiallonort** [comment]
Hello, Could you explain a bit more why one library will be supported and not another? I was looking to use Blazor client side to do database connection ( Customer database  behind a firewall ). So I am trying to use System.Data.SqlClient and running into similar issues.

**Comment by SteveSandersonMS** [comment]
> Could you explain a bit more why one library will be supported and not another?

Some features are supported by web browsers, and some aren't. For the SqlClient example, that won't work from a web browser because web browsers don't offer any ability to create raw TCP socket connections - they only allow you to make HTTP requests. Also you almost certainly wouldn't want to expose your database across the internet.
