### ISSUE TITLE
Ensure SystemTextJsonHelper always HTML encodes user content

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#9946]
As part of https://github.com/dotnet/corefx/issues/37192, `JsonSerializerOptions` would expose a property that allows customizing the JavaScript encoder. `SystemTextJsonHelper` uses the user configured `JsonSerializerOptions`. 

We need to do the same thing here as we do with Json.Net i.e. copy the settings, but reset the encoder to ensure it's restrictive.

* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.ViewFeatures/src/Rendering/SystemTextJsonHelper.cs
* https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonHelper.cs#L82-L88

**Comment by pranavkm** [comment]
cc @ashson

**Comment by ahsonkhan** [comment]
> cc @ashson

Presumably, this was meant to be @ahsonkhan? ;)
