### ISSUE TITLE
"dotnet run" command fails if path has spaces

### ISSUE THREAD

**Issue by GabrielBB** [aspnet/AspNetCore#9948]
### Describe the bug

"dotnet run" command does not work. It says "but dotnet-C:\Users\Gabriel does not exist" when my windows user is "C:\Users\Gabriel Brito\...". It looks like the problem is the space in the user name.

### To Reproduce

1. Windows account with spaces in the name. For example: "C:\Users\Gabriel Brito\..."
2. Using ASP.NET Core 'SDK 3.0.100-preview4-011223'
3. Run these commands:

```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview4-19216-03
dotnet new blazor -o WebApplication1
cd WebApplication1
dotnet run
```

4. See error in Screenshots

### Expected behavior

Application should be deployed on 5001. See: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli)

### Screenshots

![image](https://user-images.githubusercontent.com/8752823/57149929-d8ba7400-6d9a-11e9-8565-c6347b82ec2b.png)

### Additional context

I have (not because i want to) Windows 8.1. Here is "dotnet --info" output:

![image](https://user-images.githubusercontent.com/8752823/57150009-099aa900-6d9b-11e9-9155-76d71ce16ce2.png)

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/9597. The issue's been fixed in the preview5 release. For preview4, https://github.com/aspnet/AspNetCore/issues/9597#issuecomment-489186006 has workarounds.

**Comment by GabrielBB** [comment]
@pranavkm Do you know when preview5 will be available?
