### ISSUE TITLE
Environment.StackTrace don't work

### ISSUE THREAD

**Issue by ray440** [aspnet/AspNetCore#9950]
I'm trying to get the stack trace in my Blazor.Shared DLL.
But `Environment.StackTrace` returns an empty string 
and `System.Diagnostics.StackTrace(0, true)` returns an empty stack

**Comment by SteveSandersonMS** [comment]
This is controlled by the underlying Mono runtime. Would you therefore be able to report this to https://github.com/mono/mono?

Thanks!

Closing as external.
