### ISSUE TITLE
Blazor templates missing TemperatureF data

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#9955]
The Blazor (server-side) and Blazor (ASP.NET Core hosted) templates show 0 for the entire TemperatureF column. The data isn't returned by the server and it isn't calculated on the client.

**Comment by conficient** [comment]
[Hosted templates](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Templates/src/content/BlazorHosted-CSharp/BlazorHosted-CSharp.Shared/WeatherForecast.cs) look okay, it was only the server-side template that was missed. Perhaps it should be moved to `src/Components/Blazor/Templates/src/content/` so it's in the same area as the other Blazor templates?
