### ISSUE TITLE
[QUESTION] Is it possible to ship Razor engine / pages in a nuget for a webapi

### ISSUE THREAD

**Issue by tebeco** [aspnet/AspNetCore#9970]
### Is your feature request related to a problem? I'm am trying to do ship dynamic html content (Razor Pages would be perfect) from a nuget
The idea is exactly the same as `Swashbuckle.Aspnetcore` ships a pages
if i understand correctly `Swashbuckle` ship raw html/js and this does not feels like a good idea for simple but dynamic content.
Our naive implementation generates html in a  `StringBuilder` (this is even worse i guess)

### Describe the solution you'd like / tried / context
We are releasing nuggets for multiple teams and these teams mainly creates WebApi and separated SPA
the webapi is created with `dotnet new webapi -n foo` then `dotnet add package Corpo.Aspnetcore`
I would like to know if in these `Corpo.xyz` there is a way for me to ship and enrich the webapi with Razor engine (razor pages)

usually these nuget add monitoring / streaming / auth / etc ....
the perfect example would be the monitoring one where we could render simple but nice thing when hitting for example `/health/ui`

We tried to add razor pages to the main webapi then move them to the nuget but it never went really well. I almost never fully used Razor Engine so the question may looks obvious but i still don't get how to do that.

**Comment by poke** [comment]
So just to clarify:

You want to run custom middleware and have that return content based on the result of rendering a Razor view?

Is this limited to just view logic (i.e. what you can do within a `.cshtml`), or do you also want “code-behind” like in a Razor page? And is this just limited to a few static results with little server-side interaction (i.e. no back and forth through form submits or something)?

**Comment by tebeco** [comment]
As discussed with @poke on slack i'm pretty sure i missused the template `razorclasslib`
closing this issue and will re-open if stuck with a repository for repro
