### ISSUE TITLE
[Helix] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.ShutdownTests.GracefulShutdownWaitsForRequestsToFinish fails on Fedora.28.Amd64.Open flaky on other linux distros

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#9985]
I'm seeing consistent failures of this test. I've disabled it for now but it needs investigation. https://dev.azure.com/dnceng/public/_build/results?buildId=179820&view=ms.vss-test-web.build-test-results-tab&runId=4336858&paneView=debug&resultId=118191. 

cc @Tratcher

**Comment by Tratcher** [comment]
Link to the disable PR/commit?

Note this test was enabled on linux for the first time this week when we got the new SocketHttpClient HTTP/2 work. From the logs I saw it looks racy.

**Comment by JunTaoLuo** [comment]
https://github.com/aspnet/AspNetCore/pull/8094/commits

**Comment by JunTaoLuo** [comment]
Actually it seems like it's consistent on Fedora.28 but flaky on others. https://dev.azure.com/dnceng/public/_build/results?buildId=180258&view=ms.vss-test-web.build-test-results-tab

**Comment by anurse** [comment]
Is there a reason this was filed manually instead of letting RaaS handle it? Can we move it to aspnet/AspNetCore-Internal and put the failure text in code-fences so that RaaS sees future failures?

It's difficult to track the failures if they're spread across different places...

**Comment by anurse** [comment]
@JunTaoLuo Is there a reason this was skipped instead of using RaaS and marking as flaky? If not, I'm going to switch it to `Flaky` and close this so it can be tracked by RaaS.

**Comment by anurse** [comment]
It seems to already be marked flaky everywhere anyway...

https://github.com/aspnet/AspNetCore/blob/bde1b164987eead227975bd2e11d935e2ea1fa19/src/Servers/Kestrel/test/FunctionalTests/Http2/ShutdownTests.cs#L45-L48

**Comment by JunTaoLuo** [comment]
It was consistently failing on Helix's Fedora28 queue. We have an iddue on Helix right now where flaky tests are still reported as test failures and fails the build. I wanted to avoid having the Helix tests "permanently fail" and turned off the test all together on that queue instead.

**Comment by anurse** [comment]
Closing in lieu of https://github.com/aspnet/AspNetCore-Internal/issues/2481 which is tracking this work. We have some plans to deflake here in preview 7.

**Comment by anurse** [comment]
Accepted since this was just closed as a dupe.
