### ISSUE TITLE
Cookie added to HttpResponse.Cookies is NOT immediately available in the HttpRequest.Cookies (unexpected breaking change from System.Web)

### ISSUE THREAD

**Issue by guylando** [aspnet/AspNetCore#9987]
System info:
net 472
dotnet cli 2.1.602

The documentation here: https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest.cookies?view=netframework-4.7.2 
says "After you add a cookie by using the HttpResponse.Cookies collection, the cookie is immediately available in the HttpRequest.Cookies collection, even if the response has not been sent to the client."

This is wrong as reported here: https://forums.asp.net/t/2137634.aspx?Cannot+Append+to+cookie+in+ASP+NET+Core+2+0+MVC+ and as observed if you do in a middleware (which runs before mvc middleware):

```c#
context.Response.Cookies.Append("aaa", "value", new CookieOptions()
                                    {
                                        Secure = true,
                                        Path = "/",
                                        HttpOnly = true,
                                        Expires = DateTime.UtcNow + TimeSpan.FromDays(10),
                                        Domain = ".domain.com",
                                        SameSite = SameSiteMode.None,
                                    });
```

And then in an mvc controller the following is equal to null

```c#
Request.Cookies["aaa"]
```

https://stackoverflow.com/questions/52191376/using-cookies-in-asp-net-core-2-1

**Comment by guylando** [comment]
Indeed if you look at the implementation of .Append there is nothing which adds the cookie to the request headers "immediately ": https://github.com/aspnet/AspNetCore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/Http/src/Internal/ResponseCookies.cs#L36

**Comment by guylando** [comment]
Ah that is the documentation of System.Web.HttpRequest and not Microsoft.AspNetCore.Http.HttpRequest.
The question is why they are inconsistent on this

**Comment by Tratcher** [comment]
Because we wanted HttpRequest to represent what was actually sent by the client, not an assumption about what the client side state will be in the future. 

An example of this is authentication cookies. Sign-in can be a multi-stage process where you transition through a series of different cookies over multiple requests. It makes a meaningful difference what cookies the client provided on this request vs which ones we are sending them for future use.

State within a request is better tracked via mechanisms like HttpContext.Items.

**Comment by guylando** [comment]
maybe adding a flag parameter which falls back to old behavior can make life easier for developers which are adding cookies which they DO want to appear immediately in the request?

for me for now I solved it by rewriting other code places so that I save the value also in httpcontext items (and if cookie exists then insert it into context) and then code looks at context instead of cookie. However if the fallback flag would exist would require less code rewriting
