### ISSUE TITLE
dotnet new react should use latest create-react-app and react-scripts

### ISSUE THREAD

**Issue by joewhite** [aspnet/AspNetCore#9989]
### Describe the bug
When I create a new ASP.NET Core + React project with `dotnet new react`, the template uses an old version of create-react-app. Specifically, it installs an old version of create-react-app's "react-scripts" package.

This causes a lot of `npm audit` warnings that wouldn't be there if it used the latest react-scripts, and prevents using the TypeScript support that's [built into react-scripts 2.1.0 and later](https://facebook.github.io/create-react-app/docs/adding-typescript) without a lot of juggling.

### To Reproduce
1. Using this version of ASP.NET Core: **2.2.203**
2. Run this code: `dotnet new react -o new-react-project`
3. Look at `new-react-project/ClientApp/project.json` and find the version of `react-scripts` that the template is using

### Expected behavior
The new project should specify `"react-scripts": "3.0.0"`.

That's because the template supposedly uses create-react-app to create the ClientApp folder, and if you run `npx create-react-app ClientApp`, it *does* create a package.json with `"react-scripts": "3.0.0"`.

### Actual behavior
The new project's `ClientApp/package.json` specifies `"react-scripts": "^1.1.5"` - a version that's currently 8 months old. Somehow, in spite of using create-react-app, the "dotnet new react" template is forcing an old version of react-scripts.

### Additional context
Output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.203\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @joewhite.
We are going to update the version of React for .Net Core 3.0 as part of https://github.com/aspnet/AspNetCore/issues/5432
