### ISSUE TITLE
请教如何使用类似<partial> 标签调用 Razor ClassLib?

### ISSUE THREAD

**Issue by ioer2008** [aspnet/AspNetCore#9990]
想使用<partial> 标签 直接调用,类似这样,
`<partial name="/Areas/MyFeature/Pages/Page1.cshtml" />,
<partial name="/MyFeature/Pages/Page1.cshtml" />,`
startup添加services.Configure<RazorViewEngineOptions>(options =>
{
options.ViewLocationFormats.Add("/MyFeature/{0}");
options.ViewLocationFormats.Add("/MyFeature/{0}.cshtml");
});
怎么样都不行,试来试去,发现只有https://localhost:44348/MyFeature/page1 ,这样可以显示页面,
请教如何使用类似<partial> 标签进行调用?

**Comment by ioer2008** [comment]
我发现放在shared目录下,就可以了

**Comment by mkArtakMSFT** [comment]
Translated using Google Translator:

I want to use the tag to call it directly, like this,
<partial name="/Areas/MyFeature/Pages/Page1.cshtml" />, <partial name="/MyFeature/Pages/Page1.cshtml" />,
Startup adds services.Configure(options =>
{
options.ViewLocationFormats.Add("/MyFeature/{0}");
options.ViewLocationFormats.Add("/MyFeature/{0}.cshtml");
});
I can't do it, try it out and find that only https://localhost:44348/MyFeature/page1 can display the page.
Ask how to use a similar tag to call?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ioer2008. You can customize view discovery following this article: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-2.2#view-discovery
