### ISSUE TITLE
The type or namespace name 'App' could not be found in blazor client side project

### ISSUE THREAD

**Issue by synckarthik** [aspnet/AspNetCore#9991]
### bug

We have created the blazor(client side) project in visual studio 2019 and run the application.

It throws the build error as

The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "WebApplication1.csproj" -- FAILED.

**Note:** We didn't add any of our codes in created project, we just build the created project and facing the above issue.

### To Reproduce

For your reference, we have attached the created sample below

[WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3146720/WebApplication1.zip)

out Visual studio version: VS 2019 (16.0.2)
.net core preview 4 installed
Blazor extensions installed

Can you please suggest how to resolve this issue in our side?

**Comment by Andrzej-W** [comment]
You need latest ***preview*** version of VS to work with Blazor. Now it is 16.1.0 Preview 2.0.

**Comment by lennilobel** [comment]
The latest preview does not help. I installed VS 2019 Preview Version 16.1.0 Preview 3.0 today, and the compiler still fails to build the Blazor template with this error (type or namespace 'App' could not be found). And this VS 2019 Preview doesn't have a "Use previews of the .NET Core SDK" checkbox under .NET Core options, like the VS 2019 16.0.3 (non-preview) does, which was another reported fix to this problem.

This is very frustrating. Blazor is hot and awesome. But first impressions are everything, and a buggy rollout like this can do tremendous damage to its reputation.

So, can someone *please* post a resolution to this, so we can all create our first Hello World Blazor app?!?!?

**Comment by SteveSandersonMS** [comment]
> The latest VS 2019 preview is not needed

I'm afraid this is incorrect. The latest preview **is** needed to get the correct tooling experience.

Closing as this will not occur with the correct version of VS.

**Comment by sapatelbaps** [comment]
I have latest Visual Studio 2019 and .NET Core Preview 3 latest as well as of today. 
But still I am unable to compile my first Blazor project as it says unable to find "App".
Did "Update-Package –reinstall" and restart VS but nothing worked for me.

**Comment by abritabroad** [comment]
For those of you coming late to the party, the "Use previews of the .NET Core SDK" checkbox has now moved to "Tools -> Options -> Environment -> Preview Features"
as per: https://developercommunity.visualstudio.com/content/problem/576973/use-previews-of-the-net-core-sdk-checkbox-is-now-m.html

**Comment by thiagodebastos** [comment]
Adding this to your `.csproj` file fixed it for me in VSCode on MacOS:
```diff
<ItemGroup>
+   <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="3.1.0-preview1.19508.20" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.1.0-preview1.19508.20" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.1.0-preview1.19508.20" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.1.0-preview1.19508.20" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.1.0-preview1.19508.20" PrivateAssets="all" /
</ItemGroup>
```

**Comment by Tigerhajen** [comment]
> 
> 
> You need latest _**preview**_ version of VS to work with Blazor. Now it is 16.1.0 Preview 2.0.

What about Visual Code? Why is this error so difficult to fix?
