### ISSUE TITLE
AuthorizationHandler to have access to ActionArguments

### ISSUE THREAD

**Issue by phillip-haydon** [aspnet/AspNetCore#9993]
### Is your feature request related to a problem? Please describe.
I have alot of routes define on my API, some routes have an optional argument via Query String, some are defined in the route itself, and some are sent as part of the payload. 

Because some are not defined on `[FromRoute]` and are instead defined via `[FromQuery]` and `[FromBody]`, they are not available in the bound model of the action.

```csharp
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, MustHaveResourceAccessRequirement requirement)
{
    if (context.Resource is AuthorizationFilterContext filterContext)
    {
        var request = filterContext.RouteData.Values["request"];

        ...
    }
}

...

public ActionResult GetResource([FromBody] GetResourceRequest request)
{
    ...
}
```

I do have access to HttpContext, however that would mean I manually need to go and figure out where the id I need is. Is it in the payload? in the Query? In the Route?!?

I want to pull the id from the bound model so I can verify if the logged in user has access to that specific piece of content, as lots of different actions can be made on that content or in relation to it, it doesn't always make sense to have it as part of the route. 

### Describe the solution you'd like
To be given access to the Bound Model similar to what's available in an ActionFilter via the `ActionArguments`.

### Describe alternatives you've considered
I've sort of figured out how to implement it as an ActionFilter, however this seems more of a hack or work-around, since I've had to go from Authorization Policy to something that isn't an authorization policy... So half the authorization is policy based and the other half is now hacked into an ActionFilter.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @phillip-haydon.
@blowdart, @HaoK do you have any suggestions here?

**Comment by HaoK** [comment]
Sounds like this is in the grey area.  From the Authorization side of things, the only thing you get from MVC as you discovered, is the `AuthorizationFilterContext`, which lets you access the `HttpContext` and whatever you can reach from that.  I'm not very familiar with the specifics of how MVC model binding works, but I imagine you can probably get to what you need from the context?  @pranavkm @rynowak any ideas on how he can access the `BoundModel` from the `AuthorizationFilterContext`

**Comment by rynowak** [comment]
There's no way to do this currently. We intentionally don't run model binding at this stage because we want to avoid doing work when the request is unauthorized.

**Comment by phillip-haydon** [comment]
The first auth when you challenge forms auth or jwt token etc is unauthorised. But any policy run after that returns forbidden as its (i assume) doing resource authorisation at this point. It’s just at this point there are many different ways to interact with the resource so I need to get the identifier from 1 of 3 places. 

It gets more difficult because I don’t know the name. So in 1 request it may be OrderId and in another a StoryBoardId. Etc. And these could be passed as part of the payload. Or part of the route or query. Once I have the bound model I can easily get the info I need. But it’s getting the bound model that’s difficult. 

I wouldn’t mind an opt in way to force binding earlier to Ensure that what’s binder isn’t bound again.

I feel like it’s super hacks needing to do this in an action filter. Right now I check in a filter and then set the result to ForbiddenResult which short circuits the execution of the action. It works great. But what bothers me is I have 5 policies but 1 is moved to action filter and it feels completely wrong :(

I’m prob an edge case here and if it’s not something you want to support that’s cool. I just thought I would raise it and hope you may consider bending your knee to my request, haha. Too much GOT.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @phillip-haydon.
This is not something we plan to do in the near future.
