### ISSUE TITLE
WebDeploy 3.6

### ISSUE THREAD

**Issue by gaoconggit** [aspnet/AspNetCore#9996]
**Describe the bug**

When installing MS WebDeploy 3.6, Asp.net core 2.2 webapi does not work properly，How 
to fix?

**Screenshots**

![QQ截图20190506212448](https://user-images.githubusercontent.com/10905068/57266132-50471680-70ad-11e9-9f97-5c0435efa2c7.png)

web.config

![image](https://user-images.githubusercontent.com/10905068/57266339-16c2db00-70ae-11e9-9dd5-fee44f0fe5a0.png)

.csproj

![image](https://user-images.githubusercontent.com/10905068/57266363-30fcb900-70ae-11e9-9662-8e8cc1eb9a55.png)

**Additional context**

 .net core 2.2.4 windows server hosting 

When webconfig is

```xml
<add name="aspNetCore" path="*" verb-"*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
```

Http page exception 

The https page is normal 

Changed to 

```xml
<add name="aspNetCore" path="*" verb-"*" modules="AspNetCoreModule" resourceType="Unspecified" />
```

It's all normal

**Comment by davidfowl** [comment]
@gaoconggit can you provide some more details, the exception message you're seeing, the version of ASP.NET Core you're using etc. (Can you fill out the template provided by the issue?)

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
